### ISSUE TITLE
Get Elementor divs outside content

### ISSUE THREAD

**Issue by oceanwp** [pojome/elementor#1000]
Hello, I have a question, is it possible to have elementor divs outside the content of a page?
I would like to create an option in the customizer to choose a page that will replace the content of the header with the content of the selected page, but the elementor divs are not there.
Is that possible?

To have the content of the page, I use a very simple method:
<pre>$page_id = get_theme_mod( 'header_page_id' );
// Get page content
if ( ! empty( $page_id ) ) {
	$page = get_post( $page_id );
	if ( $page && ! is_wp_error( $page ) ) {
		$page_id = $page->post_content;
	}
}</pre>

Thank you a lot :)

**Comment by KingYes** [comment]
This feature write inside in our Pro version. You can use that with `shortcode` (Pro version need to be active for that)

**Comment by oceanwp** [comment]
Hello, it is not possible to do it for the free version?
I'm not talking about shorcodes but the divs appear when I put the code to have the contents of a page, the divs are exported with the xml file, so logically it should be possible to do so.

**Comment by KingYes** [comment]
In `post_content` we don't store anything. Just the plain text for fallback when the use want to deactivate Elementor plugin. For all div's and more, you need to use the `shortcode`.

**Comment by agusmu** [comment]
@oceanwp, there is someone who created Anywhere Elementor shortcode, check this one,
https://wordpress.org/plugins/anywhere-elementor/

**Comment by oceanwp** [comment]
Hi, thank you very much @agusmu, I will see how to do with this plugin.
@KingYes, I created a free theme, I will not tell users, if you want to display your page created with elementor in the footer or the header, you must have the pro version of the plugin, it would not be very nice for them even though I think most of them will buy the pro version :)

**Comment by KingYes** [comment]
So you can use what @agusmu offered up :)

**Comment by oceanwp** [comment]
Hello, yes, thank you very much, I managed to do it for Elementor and Beaver Builder :)

**Comment by mbautista** [comment]
Hello,
For the ones who have Elementor Pro, you can use the following code : 
```
$post_content = do_shortcode("[elementor-template id=$post_id]");
```
