### ISSUE TITLE
After upgrading to version 1.0.0 stopped working counter

### ISSUE THREAD

**Issue by oto-xara** [pojome/elementor#1001]
http://prntscr.com/dg384h

No animation

**Comment by arielk** [comment]
Hi

Please deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache.

thanks

**Comment by iamntz** [comment]
Ahem.... #993

**Comment by oto-xara** [comment]
@arielk I tried, it didn't help

@iamntz I did fix which are described in #993

I made changes to the file:
wp-content/plugins/elementor/assets/js/frontend.js

it did not help, counter still not working

**Comment by luisvivasb** [comment]
Hi oto-xara, if you make change in .js file you have to activate the "SCRIPT_DEBUG" because Elemenor use frontend.min.js

Add this on plugins/elementor/elementor.php
define('SCRIPT_DEBUG', true);

**Comment by oto-xara** [comment]
@luisvivasb, it's still not working, what am I doing wrong?

http://prnt.sc/dgdhvx

**Comment by iamntz** [comment]
Can you open console and check if you see any errors there?

**Comment by oto-xara** [comment]
@iamntz, yes when I load the page in elementory

http://prntscr.com/dgeg9g

**Comment by iamntz** [comment]
You need to add `SCRIPT_DEBUG` constant into your `wp-config.php` file.

**Comment by oto-xara** [comment]
Thank you! it helped! uhh...not easy to fix it)

this code needs to stay in there? or it can be removed?

the following updates will not break this code?

**Comment by iamntz** [comment]
Well, it will break only if @cobicarmel will agree that there is a problem there. Otherwise... :)

**Comment by oto-xara** [comment]
it's definitely a bug. I hope it will be fixed

**Comment by agusmu** [comment]
I tried to test it on my Elementor v1.0.0

on live editor, counter widget works... 

but on frontend, counter widget doesn't work...

**Comment by KingYes** [comment]
Thanks!
We fixed this by this PR: #1007
