### ISSUE TITLE
Can't save edited post after upgrade to 1.0.0 + Read More tag problem

### ISSUE THREAD

**Issue by lcrl** [pojome/elementor#1002]
I upgraded to 1.0.0 this morning, and now when I try to save changes to a post, it'll get to about 98% saved on the progress bar and then just stop. I've waited up to 15 minutes before giving up. Any ideas?

http://prnt.sc/dg4fc2

Also, I don't know if this is related because this is the first post I've used Elementor for, but the "Read More" tag didn't work when I published the post (after giving up on making changes, they were just tweaks anyway) so I had to 'pend' it to figure that out too. It clearly shows on the text editor, but didn't work on the main Blog page when published.

Thanks!

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
