### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by axiomteck** [pojome/elementor#1011]
on the social media icon it will be nice if you can add options on icons like share us on, like us on, when they click on those options it will do what it suppost to do, if they click on like a like will be added to facebook and so on. THANK YOU i cant wait to see the PRO Version

**Comment by arielk** [comment]
Did you mean "Sharing Buttons"?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
