### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by axiomteck** [pojome/elementor#1013]
I Pre order the new Pro Version is it posible that you guys can create a simple theme that goes with elementor. i dont want to spend more money on any theme. i love all about elementor and it will be nice if some how it can edit everything like the menu and so on

**Comment by kadoogan55** [comment]
I support this request - the nearest page builder competitor does this for the same price or less (can't recall the pricing but it is in the neighbourhood for a pro version).

**Comment by arielk** [comment]
For now we do not plan to create a simple theme for Elementor, maybe in the future. Thanks for your feedback!
