### ISSUE TITLE
How to improve Tabs when responsive

### ISSUE THREAD

**Issue by pauljnye** [pojome/elementor#1016]
I have a page with Elementor tabs. Looks great on desktop..
http://screencast.com/t/PACsSK5ztcw
but on phone some tabs are out of view...
http://screencast.com/t/Lo2GUVr2Ul

Is there a way to improve it?
Thanks

**Comment by Teddii** [comment]
Try to change the design idea. Creating an accordion maybe will help you. Or use another plugin to create the "more responsive" tabs and embeed it by shortcode.

**Comment by arielk** [comment]
We're going to improve the Tabs widget will work like an Accordion widget in the mobile screen.

I merged this issue with another issue #443 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.
