### ISSUE TITLE
Texteditor stops working after upgrade

### ISSUE THREAD

**Issue by andreaskviby** [pojome/elementor#1019]
I just upgraded to version 1.0.2 and the Text Editor stops to enable me to edit text.

**Comment by paaljoachim** [comment]
All the Text Editors? Or just some of them?
Any difference if you add a new Text Editor? Will the new work?

I ask these things as I noticed a glitch in the layout of a site I am working on. I had to duplicate/create new some of the layout. I was in relation to responsive design that did not show up as it should so I had to recreate some of it.

**Comment by arielk** [comment]
@andreaskviby We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
