### ISSUE TITLE
Simple slider as a background

### ISSUE THREAD

**Issue by kadoogan55** [pojome/elementor#1024]
It would be great if a background could be a simple photo slider in the free version. Beaver builder has this feature and I have found it useful on several occasions. It has the basic transitions including the Ken Burns effect. This is a nice limited effect that brings the free version up to a new level of usefulness while advertising the full slider available in pro.

**Comment by kadoogan55** [comment]
By background I mean section backgrounds, btw.

**Comment by joshmarom** [comment]
The free version of BB doesn't have this feature, and I don't think Elementor free should have it either.

**Comment by kadoogan55** [comment]
Neither version has it - I wish it did. Thank you [joshmarom](https://github.com/joshmarom) for adding that "feature request" label. I haven't figured out how to do that myself just yet.

**Comment by kadoogan55** [comment]
So how about having the feature in the Pro version?

**Comment by joshmarom** [comment]
> So how about having the feature in the Pro version?

It's not out of the question. We will put it on our (long) list of features to consider adding in the future. :)

**Comment by nivniv44** [comment]
There's a third party solution for that, although I believe Elementor should've added it long time ago:
https://codecanyon.net/item/elementor-background-image-video-slider/21598997
