### ISSUE TITLE
[Bug] Colour picker auto-prefills HEX value

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1026]
Hi,

The colour picker seems to be prefilling data automatically, which makes it frustrating when typing in a full colour value. Here's a video demo:

https://gfycat.com/ConventionalTerribleDipper

---

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.5
	PHP Version: 7.0.8-0ubuntu0.16.04.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.7
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-AU
	Timezone: 9.5
	Debug Mode: Inactive

== Theme ==
	Name: Sage Starter Theme
	Version: 8.4.2
	Author: Roots
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

== Active Plugins ==
	404 Redirection
		Name: 404 Redirection
		Version: 1.8
		Author: flippingwp.com

	All In One SEO Pack
		Name: All In One SEO Pack
		Version: 2.3.11.1
		Author: Michael Torbert

	Better WordPress reCAPTCHA
		Name: Better WordPress reCAPTCHA
		Version: 2.0.3
		Author: Khang Minh

	Bulk Page Creator
		Name: Bulk Page Creator
		Version: 1.1.0
		Author: Dagan Lev

	Contact Form 7
		Name: Contact Form 7
		Version: 4.6
		Author: Takayuki Miyoshi

	Contact Form 7 - Success Page Redirects
		Name: Contact Form 7 - Success Page Redirects
		Version: 1.2.0
		Author: Ryan Nevius

	Elementor
		Name: Elementor
		Version: 1.0.3
		Author: Elementor.com

	Elementor Addon Widgets
		Name: Elementor Addon Widgets
		Version: 1.0.3
		Author: WPDevHQ

	Flamingo
		Name: Flamingo
		Version: 1.5
		Author: Takayuki Miyoshi

	Flexible Map
		Name: Flexible Map
		Version: 1.12.1
		Author: WebAware

	Search & Replace
		Name: Search & Replace
		Version: 3.1.0
		Author: Inpsyde GmbH

	W3 Total Cache
		Name: W3 Total Cache
		Version: 0.9.5.1
		Author: Frederick Townes

	WP Retina 2x
		Name: WP Retina 2x
		Version: 4.7.4
		Author: Jordy Meow

	WP Sync DB
		Name: WP Sync DB
		Version: 1.5
		Author: Sean Lang

	WP Sync DB Media Files
		Name: WP Sync DB Media Files
		Version: 1.1.4b1
		Author: Sean Lang

**Comment by dasigna** [comment]
jep. confirmed.
thats been from the beginning :-). if you put in the hex without hash everythings allright, but the behaviour is annoying anyway.

second thing: the field for the color value often is too small especially for rgba-values - you cant see transparency-value completely, so its impossible to hit a certain factor visually when operating with the controller bar ... and even worse: if you try to edit manually, elementor comes to life again with its own rules when e.g. trying to edit a 0.7-value: as soon as deleting the  '7' and changing to '5' the number '5' suddenly appears behind the brackets and the dot inside is gone... quite annoying too.

but easy to fix as i hope! :-)

**Comment by dasigna** [comment]
... cant we have the color-value-field a little bit bigger please?
stumbling over this again and again ...

(issue with hash is the same as with '-' in margin and padding-settings btw.)

**Comment by joshmarom** [comment]
The color picker in Elementor is the native WordPress color picker ([Iris](https://github.com/Automattic/Iris)).
Thank you for pointing out those issues.
