### ISSUE TITLE
[Bug] Can't type minus values in Margins / Padding fields

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1035]
## Description

I can't type minus characters into the margins / padding panels (for example if I want to set a negative margin). You can use the tiny up / down controls, or press up or down on a keypad to scrub through minus numbers, but it would be handy to just type the number off the bat.

## Steps to reproduce

Happens across all margin / padding panels, see this GIF for more info
https://gfycat.com/SelfassuredCommonHarpyeagle

## Environment
	
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.5
	PHP Version: 7.0.8-0ubuntu0.16.04.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.7
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-AU
	Timezone: 9.5
	Debug Mode: Inactive

== Theme ==
	Name: Sage Starter Theme
	Version: 8.4.2
	Author: Roots
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

== Active Plugins ==
	404 Redirection
		Name: 404 Redirection
		Version: 1.8
		Author: flippingwp.com

	All In One SEO Pack
		Name: All In One SEO Pack
		Version: 2.3.11.1
		Author: Michael Torbert

	Better WordPress reCAPTCHA
		Name: Better WordPress reCAPTCHA
		Version: 2.0.3
		Author: Khang Minh

	Bulk Page Creator
		Name: Bulk Page Creator
		Version: 1.1.0
		Author: Dagan Lev

	Contact Form 7
		Name: Contact Form 7
		Version: 4.6
		Author: Takayuki Miyoshi

	Contact Form 7 - Success Page Redirects
		Name: Contact Form 7 - Success Page Redirects
		Version: 1.2.0
		Author: Ryan Nevius

	Elementor
		Name: Elementor
		Version: 1.0.4
		Author: Elementor.com

	Elementor Addon Widgets
		Name: Elementor Addon Widgets
		Version: 1.0.3
		Author: WPDevHQ

	Elementor Pro
		Name: Elementor Pro
		Version: 1.0.2
		Author: Elementor.com

	Flamingo
		Name: Flamingo
		Version: 1.5
		Author: Takayuki Miyoshi

	Flexible Map
		Name: Flexible Map
		Version: 1.12.1
		Author: WebAware

	Search & Replace
		Name: Search & Replace
		Version: 3.1.0
		Author: Inpsyde GmbH

	W3 Total Cache
		Name: W3 Total Cache
		Version: 0.9.5.1
		Author: Frederick Townes

	WP Retina 2x
		Name: WP Retina 2x
		Version: 4.7.4
		Author: Jordy Meow

	WP Sync DB
		Name: WP Sync DB
		Version: 1.5
		Author: Sean Lang

	WP Sync DB Media Files
		Name: WP Sync DB Media Files
		Version: 1.1.4b1
		Author: Sean Lang

**Comment by netgain** [comment]
I noticed this, too. It seems that the fields are strictly numeric and don't recognize that the dash is intended for numeric values.

**Comment by dasigna** [comment]
jep - those fields dont take the '-' if entering complete value, which is quite uncommon...
but if you click once on arrow-down-button to get '-1' you can replace the '1' to whatever you want - only be shure to leave the '-' in the field :-).

a bit tricky and should be corrected - yes.

**Comment by pingram3541** [comment]
I'm sure you already know that negative padding isn't a thing but I see what you mean about the margins. Fastest method for me is to use the mouse to go from zero to negative than adjust it manually leaving the hyphen as you suggested.

**Comment by drawcard** [comment]
> I'm sure you already know that negative padding isn't a thing

Yes, I meant margins only - but I figure it's a global problem all the same :)

The method you describe works fine for me too but it's a bit fiddly if you're used to tabbing around and typing stuff out, also it's rather tricky hitting those tiny scroll buttons in each field especially with a trackpad. 

I imagine this is a problem with the number validator, which rejects negative numbers, or dashes in the field. If it can be tweaked to allow those items it would probably fix the problem.

**Comment by pingram3541** [comment]
Kind of trivial but got an updated tip, (left arrow + minus).  Still not perfect but...the problem appears to be adding the minus in place of the value (because its highlighted) or when a value doesn't exist.  As long as there is a value one can just tab into it and tap the left arrow (un-highlight value) to add the minus no problem.  The minus just can't exist by itself even if you plan to add a value after it.

**Comment by bainternet** [comment]
answer here: https://github.com/pojome/elementor/issues/3677#issuecomment-376103282
