### ISSUE TITLE
[Request] Allow media queries in custom CSS editor

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1036]
For example, if I want to adjust the exact positioning of a background image on a given panel for mobiles (handy if you want to keep a particular headshot in frame), I am unable to do this unless I use the "selector" target and affect the entire viewport range. It seems that media queries aren't parsed at all in the Custom CSS panel.

It would also be handy for situations where you might want to modify an element to be more print-friendly, by using @media print on it.

Edit: I just discovered that any attempt to use media queries will break the rest of the CSS layout on the front-end, from the point that the code is inserted.

**Comment by pingram3541** [comment]
Yes I've opened [another feature request](https://github.com/pojome/elementor/issues/1086) that hopefully is a nice compromise to this issue.  If the Elementor team can relax the forced inclusion of wrapping all rules written in the custom css fields with the uniqueue elementor selector then we can have full css freedom.

They can keep the "selector" keyword for simplicity but then we can now add media queries, @font rules etc.

**Comment by pingram3541** [comment]
You should now be able to add media queries to custom CSS.

**Comment by arielk** [comment]
We fixed this issue in the last version of the E-Pro (1.0.5), please update the plugin and get it.
