### ISSUE TITLE
Content Field is missing in POSTS widget

### ISSUE THREAD

**Issue by andreaskviby** [pojome/elementor#1037]
So finally the PRO version ended up in my hands. The new Widget POSTS that I have been dreaming about is missing one important thing. There is no way to include the actual content of the posts, why?

I have a page where I want to list the headline and the content of the post. So why have you only included the excerpt field and not the content itself?

The king of widgets should let me choose which fields I want, just like the Forms widget.

You rock!

**Comment by drawcard** [comment]
I think the idea of the widgets plugin is to just show a teaser of the content, a bit like an index page. 

How do you have your content currently set up? Do you use excerpts for instance?

I guess it's probably possible to tweak the output of the widgets plugin once the API is released too.

**Comment by WPDevHQ** [comment]
Could you explain the use case scenario please?

Are you trying to output the entire content of a post as it would appear on it's single post view on a page authored via the builder with other content on it or jus the full post by itself? If the intent is just the post by itself then doesn't that defeat the purpose of the single.php template?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by nonstop-paul** [comment]
I'm also mystified why it strips out formatting and <p> tags. I've 3 posts set up as testimonials and I'd like to pull them in with a short excerpt BUT Name and Occupation and the first paragraph all come in without paragraph breaks and text formatting which is annoying. This is potentially a very powerful widget BUT stripping out formatting in the excerpt makes it almost redundant....

**Comment by MafuraG** [comment]
Hello, Is there a way to make the posts widget display the full content of a post?

**Comment by andreaskviby** [comment]
Hey
Why do I get this?

Sent with ❤️ from Sweden

**Comment by drawcard** [comment]
@andreaskviby you are probably subscribed to the thread, you can log in and click "Unsubscribe" on the issue page to leave it.
