### ISSUE TITLE
Bug: Embed Template

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#1038]
## Description

Trying out the Pro feature of embedding a template using the Elementor Library widget.

<img width="463" alt="widget" src="https://cloud.githubusercontent.com/assets/974442/21184518/adfa6b58-c1c1-11e6-8011-b5f25e2d30f4.png">

## Steps to reproduce

When I then go back to edit a page using Elementor, the whole things breaks:

<img width="1269" alt="broken" src="https://cloud.githubusercontent.com/assets/974442/21184528/b6449bda-c1c1-11e6-9a1a-0ae7140104ad.png">

The same thing happens if I use the shortcode approach too.

## Environment								
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.5.24 mod_perl/2.0.8-dev Perl/v5.16.3
	MySQL version: 5.6.24
	PHP Version: 5.5.24
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.7
	Site URL: http://wpsite01-working-copy.dev
	Home URL: http://wpsite01-working-copy.dev
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Permalink Structure: /news/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Dynamik-Gen
	Version: 1.9.3
	Author: The Cobalt Apps Team
	Child Theme: Yes
	Parent Theme Name: Genesis
	Parent Theme Version: 2.4.2
	Parent Theme Author: StudioPress

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

== Active Plugins ==
	Breadcrumb NavXT
		Name: Breadcrumb NavXT
		Version: 5.5.2
		Author: John Havlik

	Elementor
		Name: Elementor
		Version: 1.0.4
		Author: Elementor.com

	Elementor Pro
		Name: Elementor Pro
		Version: 1.0.3
		Author: Elementor.com

	Genesis Dambuster
		Name: Genesis Dambuster
		Version: 1.5.5
		Author: Russell Jamieson

	Insert Pages
		Name: Insert Pages
		Version: 3.1.8
		Author: Paul Ryan

	Sticky Menu (or Anything!) on Scroll
		Name: Sticky Menu (or Anything!) on Scroll
		Version: 2.0.1
		Author: Mark Senff

	User Role Editor
		Name: User Role Editor
		Version: 4.31
		Author: Vladimir Garagulya

	WordPress Importer
		Name: WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

**Comment by SniffleValve** [comment]
Just a shot in the dark, but perhaps give it a go with a dash in the template name instead of a forward slash.

e.g.  hours-search in lieu of hours/search

I run into issues regarding the use of forward slashes in this manner although not with Elementor.

Cheers!
Lyle

**Comment by dudaster** [comment]
I've tried different themes with no plugins active and it's tha same bug. It appears when the Elementor Library widget is before content(<?php the_content(); ?>). Put after, it works, otherwhise not.

**Comment by arielk** [comment]
Thanks for your report, the fix will be released soon in V1.0.5

**Comment by arielk** [comment]
Fix https://github.com/pojome/elementor/commit/b1dd4e412503ee06d1b7e8e03f2d1fe859800d21

**Comment by dudaster** [comment]
with 1.3.0 this bug resurfaced.
