### ISSUE TITLE
Video background disappears when using min height adjustment

### ISSUE THREAD

**Issue by dax702** [pojome/elementor#104]
When using a background video mp4 in a section, if I set the height to minimum height option, then use the slider, the video disappears. I have to exit and come back in to see the video again. I'm using Elementor with GeneratePress theme locally with DesktopServer.

**Comment by arielk** [comment]
We released yesterday a new version with some fixes, please update and check it again. tnx

**Comment by dax702** [comment]
I checked the issue with the new version and it seems to still be happening. Do you want to see a screen cast video? I can make one......

**Comment by arielk** [comment]
It would be nice :)

Please copy and paste your System Info (excluding personal information) in pastebin.com to give us more information about your environment.

**Comment by dax702** [comment]
http://pastebin.com/Gq7dPMji

https://youtu.be/fWtQFk1vSKg

I forgot to show in the video that if you save, and refresh the page, the video is still there. It just disappears for some reason when you use that size slider.

**Comment by arielk** [comment]
What browser are you using?

**Comment by dax702** [comment]
Chrome Version 51.0.2704.84 m (second to latest version)

**Comment by arielk** [comment]
Totally weird :( 
Is this always happen, every section or every page?

**Comment by dax702** [comment]
There's just one page on this test site I was using to test Elementor so I haven't tried it on other pages or sections. I was trying to make a background video header

**Comment by arielk** [comment]
Hi, released a new version (0.6+) with some fixes in this field, please update the plugin and check it again
