### ISSUE TITLE
[Bug / Improvement] Hovering over slides shows underlined text

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1041]
## Description

When a slide is set to be entirely clickable, any text contained within the slide shows an underline (because it's contained within the <a> element). This might be technically correct but it looks messy, perhaps the default should be to style the slider contents with ```text-decoration: none;```.

![image](https://cloud.githubusercontent.com/assets/1435638/21208432/db5d0bee-c2bd-11e6-958d-ccf33ad11e5d.png)

## Steps to reproduce

1. Create a slide & add some text (heading / body text)
2. Set "Apply link on" to "Whole slide"
3. Preview the slide and over over it with your mouse

**Comment by drawcard** [comment]
Sorry - this appears to be a bug with the theme I'm using rather than Elementor... :blush:

**Comment by arielk** [comment]
:)
