### ISSUE TITLE
[Bug] Cloning Global Element after Unlink

### ISSUE THREAD

**Issue by talesg** [pojome/elementor#1042]
It's easy to workaround, therefore there is no urgency. But it's a bug nonetheless. 

## Description

After clicking to duplicate, a gray box appears (instead of the cloned element).  
No settings show up. 
Can't delete. 

Workaround is to insert global element, unlink, save page, reload and then duplicate.

## Steps to reproduce

1. Insert global element
2. Unlink
3. Duplicate

**Comment by arielk** [comment]
Fix in E-Pro v1.0.4 https://elementor.com/pro/changelog/

**Comment by enjoyyourwax** [comment]
https://enjoyyourwax.com/wp-admin/plugins.php
