### ISSUE TITLE
[Bug] Submit button and form on same row alignment issue.

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#1048]
<img width="398" alt="screen shot 2016-12-16 at 08 44 52" src="https://cloud.githubusercontent.com/assets/13979799/21256747/065d10b0-c36c-11e6-8a89-9e5b6676d0c8.png">

If you set the input field and submit box on the same row there doesn't seem to be a way to remove the margin/padding from the input field so they align.

Form is fantastic though, really easy to use. Maybe conditional logic could be added in the future hehe!

**Comment by joshmarom** [comment]
Seems like your theme adds margin to your input fields.
I suggest try to inspect the input element and find it, then eliminate it using Elementor custom-CSS.

If you couldn't resolve it, please contact support@elementor.com for priority support for Elementor-pro users.

**Comment by rafaelcabo** [comment]
I had the same issue.

I have used in the Form:
 Advanced -> Custom CSS:

#testform .elementor-button {
      outline-style: none;
      margin: 0px auto;
}

#testform .elementor-field {
 margin: 0px auto;
}

Where "testform" is the name I have given to my form,
under Form:  
Content -> Additional Options -> Form ID

**Comment by xguiboy** [comment]
@rafaelcabo great thanks a lot, works just great, i'm using phlox i was having this problem, but no more.
