### ISSUE TITLE
[Request] Ability to paginate gallery

### ISSUE THREAD

**Issue by Aiken-Drum** [pojome/elementor#1049]
The gallery widget is great, but it would be even better if you could choose to paginate the gallery after showing x number of images (so for example, if you have a gallery with 48 images, you can choose 12 images per page, which will then show 4 pages with 12 images on each).

That would be a really useful addition.

Thanks

**Comment by arielk** [comment]
We make the Image Gallery via WP Shortcode. Unfortunately we can't adding pagination for this shortcode gallery.

Thanks for your feedback!
