### ISSUE TITLE
the elemet Portfolio is not displaying correctly in Chrome

### ISSUE THREAD

**Issue by oto-xara** [pojome/elementor#1050]
Element Portfolio

Firefox
http://prntscr.com/dk5vja
Chrome
http://prntscr.com/dk5vwc

**Comment by joshmarom** [comment]
The portfolio widget had undergone a thorough makeover. An update for Elemento pro will be released today.

Let us know of the status of this issue after the update.

**Comment by arielk** [comment]
In recent days, we released a new version of E-Pro, please update and let us know if it worked for you. Feel free to reopen the issue and we'll be happy to help you further.
