### ISSUE TITLE
The priority of CSS is strange

### ISSUE THREAD

**Issue by imagepit** [pojome/elementor#1051]
I adjusted the font size of desktop and mobile titles in Elementor.
On the preview screen, as expected, the font size was switched to mobile, 

![](https://www.evernote.com/l/AB1E1pBCC61CDJNna5zHnzRd6Vsu1gwHuHIB/image.png)

but in the actual browser it did not display as expected.
As far as confirmed with developer tools, I think that CSS's priority rankings are wrong with actual browsers.

![](https://www.evernote.com/l/AB39R_lMmb9LULdBq_sWh_QG1xr3xjGOCPQB/image.png)

My environment is blow. please help.
	
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.7 (Ubuntu)
	MySQL version: 5.5.43
	PHP Version: 5.5.9-1ubuntu4.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.7
	Site URL: https://wordpress-test-imagepit1.c9.io
	Home URL: https://wordpress-test-imagepit1.c9.io
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: ja
	Timezone: Asia/Tokyo
	Debug Mode: Active

== Theme ==
	Name: Twenty Seventeen
	Version: 1.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: ja
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

== Active Plugins ==
	Adminer
		Name: Adminer
		Version: 1.4.5
		Author: Frank Bültge

	Elementor
		Name: Elementor
		Version: 1.0.4
		Author: Elementor.com

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
