### ISSUE TITLE
Changelog for PRO

### ISSUE THREAD

**Issue by rawzone** [pojome/elementor#1052]
Is there a changelog for the PRO version of this plugin?

When clicking the "info" link in the dashboard you get an error (My guess you updater don't support supplying this information). Is there any other way to be in the loop of what bugs gets fixed etc.?

Thanks.

**Comment by SniffleValve** [comment]
There is a changelog.txt file in the Elementor Pro folder.
/wp-content/plugins/elementor-pro

**Comment by rawzone** [comment]
@SniffleValve Thanks - I guess that will do.

**Comment by joshmarom** [comment]
The info for Elementor Pro will be available from the dashboard in the next update.
