### ISSUE TITLE
[Request] Include Alt tag value for each image insertion

### ISSUE THREAD

**Issue by netgain** [pojome/elementor#1053]
Including Alt tags on every image of the site is considered one of the most basic SEO best practices. Another best practice is to reuse the same images whenever possible so that pages can use cached images for faster page load times. Although the "alt" value can be set in the Media Library, that is often not sufficient. While that is okay for setting a default value, the alt tag often needs to be unique for each instance of the image being used.

The alt tag issue is especially significant because the site I am converting to Wordpress already has unique alt tags assigned and has Google rankings impacted by the values of those alt tags. Switching to Elementor will result in losing some of our unique alt tag values, which may have an adverse impact on search engine rankings, thereby reducing visibility, traffic, sales, market share, revenues, and profits.

Alt tag reference: http://tinyurl.com/hkedssf

**Comment by SniffleValve** [comment]
+1 for this please :)

**Comment by joshmarom** [comment]
Thank you for emphasizing the importance of alt tags and its effect on SEO, though the delivery seemed a bit condescending (reference: http://tinyurl.com/hj99tg4).

Elementor is using WordPress native functions to generate img tags. the alt tag is the alt tag set by the user in the media library.
We believe this is the default behavior the average WordPress user would expect.

**Comment by joshmarom** [comment]
Elementor used to have a "custom alt text" field for images.
It was removed after creating some confusion for our users.

We believe the way WordPress handles it is quite sufficient and we try not to interfere with standard WordPress functionality.

**Comment by netgain** [comment]
I totally didn't mean for the post to sound condescending. It came out like that because I explain everything to "my boss" in terms of monetary ROI gained from each decision affecting SERPs. My apologies for setting such a tone. Elementor is way too awesome for that.

As for the alt tags, I create alt tags while I'm editing the page more often than I do through Media Library view. I drag & drop images from Windows Explorer onto the page/post as I am typing, update, then from that view I have a more accurate understanding of the context of how the image is going to appear on the page. It's from there that I know what the alt tag should say.

**Comment by ChazzMonkey** [comment]
The alt text tabs don't seem to be showing up for me even when they are set in the WP image/media gallery. I think setting them in the widget is a great convenience and an SEO tool.

**Comment by louson21** [comment]
You can actually insert alt text on images [in bulk] through installing WP Meta SEO plugin.

**Comment by tannerchung** [comment]
Is there a way to add a filter to the current Elementor widgets to add a new attribute tag? I'm trying to add the Pinterest attribute tags to existing Elementor widgets: https://css-tricks.com/using-pinterest-data-attributes-and-meta-tags/

**Comment by avs1291** [comment]
What I've found is that the images I added using the image component from elementor are showing the alt attributes I set on media library but the background images I put behind each column from elementor aren't showing my alt attributes at all.

**Comment by About2git** [comment]
> What I've found is that the images I added using the image component from elementor are showing the alt attributes I set on media library but the background images I put behind each column from elementor aren't showing my alt attributes at all.

That a normal Website HTML vs. CSS Behaviour: The Background Images your are talking about are in fact: CSS- Backgroudn images and so they can not technically set an Alt Tag.
