### ISSUE TITLE
PRO: With SendGrid, form emails lose all formatting

### ISSUE THREAD

**Issue by dax702** [pojome/elementor#1054]
With Elementor Pro, when you submit a form and your Wordpress site is configured to send transactional emails through SendGrid, for some reason, all formatting, e.g. each field on a new line, is removed.  All the data runs together. We confirmed this by disabling SendGrid and sending through the normal Wordpress method.

**Comment by arielk** [comment]
We're added a Tweak to allow sending form as HTML, please update the plugin and check this option: https://elementor.com/pro/changelog/
