### ISSUE TITLE
Incompatibility with video Tag

### ISSUE THREAD

**Issue by luizeof** [pojome/elementor#1058]
## Description

When Elementor is Active, the video tag on posts not Working.

## Steps to reproduce

I'm using Mautic Gated Videos with de video tag:

< video width="640" height="360" data-form-id="1" data-gate-time="15">
    < source type="video/youtube" src="https://www.youtube.com/watch?v=QT6169rdMdk" />
< /video >

* Spaces on tag is only to reproduce on github editor.

When Elementor is active, the video is Black. When deactivate Elementor Works Fine.

## Environment

Elementor Pro
Wordpress 4.7
Theme GeneratePress Premium

**Comment by luizeof** [comment]
@benpines

**Comment by arielk** [comment]
What is mean Mautic Gated Videos, can you share with us the link for this service or plugin?

**Comment by luizeof** [comment]
Mautic.org is a popular Open Source Marketing Automation platform.

Gated videos are videos that have an form that shows after X seconds and the video continue only when the form is filed by user.

With elementor plugin enabled the videos shows an black screen. After disable Elementor gated videos works fine.

I believe Elementor plugin have an CSS ou Javascript that manipulate videos on a page.

**Comment by KingYes** [comment]
If you try this code outside from Elementor, is still not working for you?

We don't have any code from outside our content..

**Comment by arielk** [comment]
@luizeof do you have any idea how we can reproduce this problem?

We are not familiar with this service and we want to test it thoroughly. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by luizeof** [comment]
@arielk  @KingYes this page https://landingpress.com.br/no-elementor/ have an example of Mautic Gated Videos. After 5 seconds of vídeo an form appear and the continues after fill the form.

This site has no reference of any Elementor widget. If i only enable Elementor Plugin the video do not appear. I also have Elementor Pro.

**Comment by luizeof** [comment]
Here mautic Gated Videos Documentation 

https://mautic.org/docs/en/video/index.html

**Comment by luizeof** [comment]
This issue was resolved on latest elementor update. ;)

**Comment by arielk** [comment]
Glad to hear, thanks for your update!
