### ISSUE TITLE
Image widget link-to field UX

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#106]
I would expect to see here the same functionality as is wordpress image library.

Replace the "Link to" input field with a select box with 3 options: image url, custom url, none;

And when the user select the "custom url", he will see a new input field where he can enter the url.

**Comment by ramiy** [comment]
![image-link](https://cloud.githubusercontent.com/assets/576623/16180036/ed24647c-3680-11e6-96ae-21b76078aa8e.png)

**Comment by ramiy** [comment]
![image-widget](https://cloud.githubusercontent.com/assets/576623/16180047/5daf17d2-3681-11e6-824e-eeec8c27d97b.png)

**Comment by KingRussel** [comment]
hi, the link works only image and title but i need wrap link full image box content together. how can i do this.
