### ISSUE TITLE
Photos added in COVER mode not functioning properly in iOS mobile view

### ISSUE THREAD

**Issue by kadoogan55** [pojome/elementor#1062]
Having ongoing issues with Elementor not doing a proper job of displaying images in sections set to COVER mode as section backgrounds. Also, when set to other modes, the images tend to repeat even though settings may set otherwise.

The images tend to over-zoom in, often looking like there is nothing in the background which is not true - it just looks that way because it may be zooming into a portion of the photo that is solid black or white.

This is a problem in both the free and Pro versions, btw.

It may not be an issue on Android. Possibly only iOS. Not totally sure because I have only had a client tell me it was working on his android phone.

I have compared this between two sites - one using Elementor and the other using Beaver Builder - no such issues with Beaver Builder.

http://goodf1gures.com  (Elementor)

http://stcroixelectricltd.com  (Beaver Builder)

It was suggested on the Facebook Elementor group page that the issue might be being caused by the latest version of Wordpress, but I am not sure this is the case given that Beaver Builder does not suffer from this issue. Maybe they are doing it differently, however, so not totally sure. 

This does probably mean that BB is doing it and so there is a solution, however.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
