### ISSUE TITLE
https post-90.css?ver=1482339322

### ISSUE THREAD

**Issue by Amstramgram** [pojome/elementor#1077]
## Description
`Mixed Content: The page at was loaded over HTTPS, but requested an insecure stylesheet '/uploads/elementor/css/post-90.css?ver=1482339322'. This request has been blocked; the content must be served over HTTPS.`

## Steps to reproduce
Add HTML5 navigator.geolocation in my page

## Environment
Wordpress : 4.7
Elementor : 1.0.6

**Comment by AdsonCicilioti** [comment]
Is it something related to this query string?? Ver = 1482339322`?
I also have a website that uses https that is adding this query string to all urls.

Do you know how to take it? The Site is on an AWS EC2 with Ubuntu 14, nginx, hhvm and mariadb.

(Sorry for getting out of focus here on your isseo.)

**Comment by KingYes** [comment]
How you change the URL of your website to HTTPS?

**Comment by Amstramgram** [comment]
`<link rel='stylesheet' id='elementor-post-90-css'  href='http://mywebsite.fr/wp-content/uploads/elementor/css/post-90.css?ver=1482426135' type='text/css' media='all' />`

this style isn't in https and i have mixed content error.

**Comment by KingYes** [comment]
How you configure your website to get HTTPS links?

**Comment by galaxyweb** [comment]
I just posted https://wordpress.org/support/topic/multisite-ssl-mixed-content-error-css-doesnt-load/ . Please let me know if it helps.

**Comment by KingYes** [comment]
Thanks :)
