### ISSUE TITLE
Image custom size

### ISSUE THREAD

**Issue by iameviliam** [pojome/elementor#1080]
I faced an Issue with the custom size. When I insert the numbers and click apply, on the editing page it shows me the pic edited with custom sizes, but when I publish the page and I view it, the pic appears in it's original sizes

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
