### ISSUE TITLE
Bug in shortcode widget

### ISSUE THREAD

**Issue by wp-src** [pojome/elementor#1082]
Hi, I'm working on a theme and wanted make it compatible with elemenetor.
I created a shortcode to show list of posts with their excerpt. When i insert that shortcode in the elementor shortcode widget, elementor loads the content and everything is fine, but when i save the changes and try to reopen the builder it says the_content function not exists. When i switch to the normal editor and remove the short code from that page, elementor works again.

When i was working around the issue found that the problem is with the get_the_excert() function. Not sure what causes that but when i remove this function from my short code output, it works fine.

		
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7
	MySQL version: 5.5.27
	PHP Version: 5.4.7
	PHP Max Input Vars: 7000
	PHP Max Post Size: 200M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.6.1
	Site URL: http://127.0.0.1/mysite
	Home URL: http://127.0.0.1/mysite
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fa-IR
	Timezone: +3.5
	Debug Mode: Inactive

== Theme ==
	Name: mytheme
	Version: 1.0
	Author: wpmagic
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0

== Active Plugins ==
	Elementor
		Name: Elementor
		Version: 1.0.6
		Author: Elementor.com

	Redux Framework
		Name: Redux Framework
		Version: 3.6.3
		Author: Team Redux

	Theme Check
		Name: Theme Check
		Version: 20160523.1
		Author: Otto42, pross

	WooCommerce
		Name: WooCommerce
		Version: 2.6.11
		Author: WooThemes

**Comment by arielk** [comment]
Could you please share with us your code so we can see why it doesn't work?

If you can share your theme with GitHub It would be great.

**Comment by wp-src** [comment]
@arielk Thanks for your response.
Unfortunately the theme is not free and am unable to share it on github.
But i switched to twenty sixteen , diabled all plugins except elementor and just used my short code in twenty sixteen.

Here is my shortcode source:

```
add_shortcode( 'mytheme_posts', 'mytheme_posts_shortcode' );

/**
 * Prints a list of posts
 * shortcode: mytheme_posts
 * @param mixed $atts
 */
function mytheme_posts_shortcode( $atts ) {
	// Attributes
	$atts = shortcode_atts(
		array(
			'title' => '',
			'limit' => '4',
			'ptype' => 'any',
            'order' => 'rand',
            'cols'  => 3
		),
        $atts,
        'mytheme_posts'
	);

    $query = new WP_Query( array(
        'post_type'         => $atts['ptype'],
        'posts_per_page'    => $atts['limit'],
        'orderby'           => $atts['order']
    ) );

    $title = ! empty( $atts['title'] ) ? '<h2 class="title"> '. $atts['title'] . '</h2>' : '';

    $output = '';

    if( $query->have_posts() ) {
        $output .= '<div class=" posts_sc">' . $title . '<ul class="cols ">';

        while( $query->have_posts() ) {
            $query->the_post();
            $output .= mytheme_posts_shortcode_content( $atts );
        }

        wp_reset_query();

        $output .= '</ul></div>';
    }

    return $output;
}

/**
 * Prints content of mytheme_posts shortcode
 * @param mixed $atts
 */
function mytheme_posts_shortcode_content( $atts ) {
    $output = "<li class='item col col1-{$atts['cols']}'>";
    $output .= '';

    $output .= "<div class='item-content'>
    <h2 class='title'><a href='" . get_the_permalink() . "'>" . get_the_title() . "</a></h2>
    <span class='excerpt'>" . get_the_excerpt() . "</span>
    </div>";
    $output .= "</li>";
    return $output;
}
```

And this is what i tried : 
1- opened a page with elementor
2- created a full width section
3- inserted a shortcode widget
4- called above shortcode in that widget textbox
5- everything loaded , then i saved changes
6- reloaded the page.

**Comment by wp-src** [comment]
Update to the issue:
Currently i created a widget that has a teaxterea and accepts shortcodes, then i send its contents to the do_shortcode function. this way i made it working, but i think using a widget for this approach is not a clean way. Is it not ?

**Comment by KingYes** [comment]
Please change from `wp_reset_query()` to `wp_reset_postdata();`.

**Comment by wp-src** [comment]
Hi @KingYes , Thanks for response.
Result is the same. Actually i was changed that for test!

**Comment by KingYes** [comment]
I tried your code in my local server, and all work's perfect.

Please send us your WP-Admin/FTP password to our `support` [at] `elementor.com`

**Comment by wp-src** [comment]
Hi again, Thanks for your effort.
I'm working in local.
After your comment i updated my wordpress from 4.6.1 to 4.7 and it works now!
Thanks.

**Comment by asnever** [comment]
Hi, @KingYes. 
> Please change from `wp_reset_query()` to `wp_reset_postdata();`
It's worked for me! Thank you

**Comment by juniorngangeli** [comment]
> Please change from `wp_reset_query()` to `wp_reset_postdata();`.

It's worked for me too. Thanks

**Comment by gonzalo-teamthunderfoot** [comment]
> Please change from `wp_reset_query()` to `wp_reset_postdata();`.

That worked for me. Thanks!
