### ISSUE TITLE
Better implementation Section

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1084]
It would be great if it were possible to insert new sections between two already existing in a simpler way. Currently if we have many sections of a page, add new sections between two existing is very complicated, especially for people impractical. Also, if you do not use a wheel mouse, I find uncomfortable move through 10 or more existing sections. Maybe it would be great to add a sign in sections and predict whether the new section must be placed before or after the current.

This is a suggestion, but I'm sure you will do better! Last thing, I PRO license Elementor. How can I contribute to the translation into Italian of the plugin? Thank you in advance.

Davide

**Comment by arielk** [comment]
Thanks for your feedback!

I merged this issue with another issue #493 in the same subject so that our Dev staff could deal with it more efficiently.

Regarding the issue of translation of EPro we're working on solution based GlotPress. Stay tuned.
