### ISSUE TITLE
Editing with Elementor redirects to a 404 (Can't make a new post with Elementor)

### ISSUE THREAD

**Issue by Benowar1** [pojome/elementor#1085]
## Description

When clicking on Edit with Elementor on a new post, I'm redirected to a 404 page (attached image)
![error](https://cloud.githubusercontent.com/assets/24756896/21468509/5c593a24-ca0c-11e6-9282-d75226d3a44b.png)

(Thanks in advance and merry Christmas!)

## Steps to reproduce

Posts > Add new > Edit with Elementor.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 5.6.27
	PHP Max Input Vars: 3000
	PHP Max Post Size: 300M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.7
	Site URL: http://www.off-side.co.uk
	Home URL: http://www.off-side.co.uk
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Valenti
	Version: 5.4
	Author: Cubell
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

== Active Plugins ==
	Akismet
		Name: Akismet
		Version: 3.2
		Author: Automattic

	Audiomack
		Name: Audiomack
		Version: 1.3
		Author: Audiomack.com

	Cubell Themes - Functionality
		Name: Cubell Themes - Functionality
		Version: 5.4
		Author: Cubell

	Elementor
		Name: Elementor
		Version: 1.0.6
		Author: Elementor.com

	Google XML Sitemaps
		Name: Google XML Sitemaps
		Version: 4.0.8
		Author: Arne Brachhold

	Infolinks Official Plugin
		Name: Infolinks Official Plugin
		Version: 3.1.9
		Author: Infolinks

	Jetpack by WordPress.com
		Name: Jetpack by WordPress.com
		Version: 4.4.2
		Author: Automattic

	Soccer Info
		Name: Soccer Info
		Version: 1.9.2
		Author: Szilard Mihaly

	W3 Total Cache
		Name: W3 Total Cache
		Version: 0.9.5.1
		Author: Frederick Townes

	WP Crontrol
		Name: WP Crontrol
		Version: 1.4
		Author: <a href="https://johnblackbourn.com/">John Blackbourn</a> & <a href="http://www.scompt.com/">Edward Dale</a>

	WP Facebook Open Graph protocol
		Name: WP Facebook Open Graph protocol
		Version: 2.0.13
		Author: Chuck Reynolds

	WP Smush
		Name: WP Smush
		Version: 2.5.2
		Author: WPMU DEV

	Yoast SEO
		Name: Yoast SEO
		Version: 4.0.2
		Author: Team Yoast

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
