### ISSUE TITLE
Lock sections/columns for editing

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1090]
It would be great to have a checkbox in the properties of a column/section so we can lock it. When the client logs in they are limited with what they can edit, but if they want to edit the section/column they can go in an unlock it. It would require a conscious unlocking and not a ops I happen to move something and then save it kind of thing. Making it one step harder for for anyone to happen to make an adjustment they did not mean to make.

**Comment by drawcard** [comment]
A toggle would be good for this in the settings page (eg. so you just turn on the lock option before handover to the client), as it could be messy to track individually locked / unlocked columns across larger sites.

**Comment by paaljoachim** [comment]
Having a global setting to lock everything would be nice, but locking specific sections/columns would also be helpful as the client might want to edit some text etc in specific columns.
So as a developer I would be able to leave specific sections editable.

Btw
Locking through global settings, section or column a semi transparant lock icon could show up across the section/column to signalize that it is locked for editing.

**Comment by enkota** [comment]
+1 Very nice idea. Ability to stop clients going in and messing up sections that have custom CSS would be very handy!

**Comment by pingram3541** [comment]
Great ideas. For now I cya by saving as templates and exporting.

**Comment by ramonztro** [comment]
+1

**Comment by bainternet** [comment]
This can be done via "Content Only mode" and/or via saving the section as global.


thanks for the suggestion.
