### ISSUE TITLE
Split column - element into two columns

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1094]
I made a one column section. 
But notice that the Text Editor text is taking too much space. I want to add a video to the right of it. Meaning I click into the text editor look to the top right and see Edit - Duplicate - Remove. Beside Duplicate there could be a split. So that I could split the Text Editor into two columns. As clicking duplicate copies the existing layout which in this case is a single column. I want to split so that I could have two text editors beside each other in two columns.

I am looking at my options right now.
I can then drag the columns element into the text editor which seems like the best method to split it.
I will post this issue even though there is a column element. It might be a good idea to have a split column icon beside duplicate.

**Comment by SniffleValve** [comment]
Click on the Column label and you will see the Duplicate, Add and Remove icons ... click Add and it will add a column to the right :)

**Comment by paaljoachim** [comment]
What I was trying to do was:
Inside a column one has elements. I wanted to click a full width element and have the option in the top right to split it. Somewhat similar to adding the column element directly below the same area, but then I have to move the full width element into the newly added extra column right below and then delete the full width column.

Adding a new column through the Column label adds a new column next to everything that is in the column. I just wanted to take 1 element into a two column area. Today one has to then add the column element move the text editor element that I was working with into the left or right column and then delete the full width column.

**Comment by joshmarom** [comment]
Can you please attach a visual reference of the design you are trying to achieve?

**Comment by paaljoachim** [comment]
Basically any element one wants to split into two columns. I am testing out the Addon Elements by Anand.

What is seen here is the mouse hovering over the 1 column Price Table.

The next step here is to split the Price Table into 2-3-4 equal parts to create multiple Price Tables.
Having a split icon next to duplicate icon would split the existing 1 column width element layout into 2 columns. Then click split again and the 1 element would be split again. Having 3 columns. Click the split again then 4 columns.

The existing option:
Drag the Columns element and drop it above the Price Table. Click the Column label and click duplicate twice to create 4 columns. Drag the existing Price Table into 1 of the new columns. Click the Price Table duplicate icon to duplicate and drag it into column 2. Follow the same procedure 2 more times.

![screen shot 2017-01-01 at 17 16 52](https://cloud.githubusercontent.com/assets/5323259/21581940/427f981a-d046-11e6-9662-a35b076f50d0.png)

**Comment by joshmarom** [comment]
I don't understand why you don't just duplicate the column or add an empty one?
<img width="345" alt="screen shot 2017-01-02 at 10 47 03" src="https://cloud.githubusercontent.com/assets/2726148/21586365/0c64483c-d0d9-11e6-819f-12ad2726d7d5.png">

**Comment by paaljoachim** [comment]
Various methods here:
1. I hovered over an element. Duplicating an element the duplicate shows up below the existing element. 

![screen shot 2017-01-02 at 11 37 38](https://cloud.githubusercontent.com/assets/5323259/21587751/ec356d28-d0df-11e6-8724-c73507f405ea.png)


2. Duplicating column duplicates all the elements that are inside that specific column. If one has just one or two elements inside a column then it is simply a matter of dragging elements into the new column. IF one has many elements within the column that it is more work to drag them to the correct place.

![screen shot 2017-01-02 at 11 37 05](https://cloud.githubusercontent.com/assets/5323259/21587757/02b714ac-d0e0-11e6-98f5-9b870563bd17.png)

3. Adding an empty column.

![screen shot 2017-01-02 at 11 37 05](https://cloud.githubusercontent.com/assets/5323259/21587759/143aa356-d0e0-11e6-9f81-1b11019313fd.png)

So the main reason to split an element automatically creating another column in the exact place where the split happens is that it would be a lot quicker then the above methods.
Element: duplicate icon adds the element below the original element. Split icon would instead add it to the right of the original element creating a column 2 for the new element.

**Comment by joshmarom** [comment]
You probably need more sections.
Unfortunately It is not possible to "split" a widget into two columns.
However, you can always use the "Columns" widget.
