### ISSUE TITLE
Very slow save -bug-

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1097]
I have noticed multiple times that there is a problem with saving.
It goes in a loop that takes a long time before (hopefully) the layout is saved.
This happens with multiple themes.

Please let us know what kinds of information you need for us to contribute to get this solved.

I am using Chrome and working on a local development site through Desktop Server.
I have three plugins installed. Elementor, Elementor Navmenu by WPDevHQ and Caldera Forms. I am using the theme Actions Pro by WPDevHQ.

When a button goes into a loop it would be good to hold down the mouse button on it for a few seconds and have whatever is going on cancel its operation. Then one can click the button again and see if it saves.

I will just have to wait and see if it has saved within the next 20 minutes or somehow cancels it self out.

**Comment by arielk** [comment]
When you turn off the 2 other plugins and change the theme to Twenty Sixteen (for example), it work fine?

**Comment by WPDevHQ** [comment]
@paaljoachim Does the page you are editing contain the Parallax header by any chance?

Working through possible scenarios that may cause the issue as I've noticed it too but again, its very sporadic. Sometimes when the issue occurs if you look at the bottom left of the screen you'll see the message "waiting for....", what do you see? - in my case this has been cdn.cloudflere.... although I have nothint in the theme or the plugin that would make a call to cloudflare!

**Comment by agusmu** [comment]
on my experiences with my clients, saving Elementor page should be less than 1-5 minutes. If it is longer than 1-5 minutes, then something is wrong on the website. 

In many cases, i can see an error message on browser console log. In some cases, I can solve it by adding higher WP_MEMORY_LIMIT.

**Comment by paaljoachim** [comment]
Hey 
@WPDevHQ I turned off all that I could turn off to get as blank space as I could. What was left was the site title and the page title.

@agusmu Thanks for the reminder to turn on wp_debug so that I can see the console log.

I can turn on wp_debug and just leave it on. Then the next time it happens I can check the log file and post here.

**Comment by joshmarom** [comment]
Any updates on that?

**Comment by paaljoachim** [comment]
Hey Josh

Just close this issue for now and I will comment on it if I notice the problem again.
