### ISSUE TITLE
[req] - less markup

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1099]
![schermata 2016-12-28 alle 16 30 48](https://cloud.githubusercontent.com/assets/437598/21525133/7247d2a2-cd1b-11e6-90a7-bbc3daf99f07.png)

12 levels before getting to my paragraph :P It would be great if there was way to lower the number of containers... In my case (a 2-columns layout), if I did it manually, I'd just need 1 main-box and 2 sub-boxes (left and right). So here there are 10 useless levels.

I understand that maybe they make for easier styling (not always, though, it depends..), but It would be great if we could bypass all this markup. Google and pagespeed would be happier too.. ;)

Regards

**Comment by hansnolte** [comment]
An extremely important point that stratboy addresses.

What good is the most beautiful plugin, if search engines punish it.

**Comment by arielk** [comment]
If you are using Elementor just for a single paragraph of text, don't do it. Use the regular text editor of WordPress. The example that you brought is not a good example of fair use with Elementor.

If you build a more complex page layout, with sections, columns and widgets, with different backgrounds, and you need the ability to control many aspects of the style of each element, that requires some markup.

A few extra divs will not interfere with SEO.

**Comment by stratboy** [comment]
Ok, this is the second thread I opened, and to be honest, I'm quite disappointed with you developers. You really do not accept any debate, you do not accept anything and you seem to assume your software is already the best sofware ever (wrong, definitely). To the point that you even do not carefully read the threads.

In this case, 2 screenshots and a detailed description were not enough to make you understand that here we are speaking of a 2 columns layout, not a single paragraph. Doesn't elementor feature 2 columns layouts? Am I wrong???

And about SEO, well, maybe you're not too much into the thing. You should.
But still, come on, 12 containers where 1 is enough... You cannot defend this in any way...

You're software is really good, but please do not make the mistake of thinking you're the God of code know, it won't make you win, anything.

**Comment by joshmarom** [comment]
Firstly, I am sorry you are choosing to make this personal and accuse us of being arrogant and whatnot ...
Elementor is a free open-source plugin and it is hosted on github, and the reason for that is because of how much we value the feedback of our users and fellow developers.
If you look at the 120+ open issues that are still open because we are considering them, and if you check out our changelog and see all the fixes and enhancements we made following issues opened by users, I'm sure you will realize we are very attentive and we try to constantly improve this product and make it better.

As to the issue itself: This structure is what's necessary in order to create complex layouts with many sections and columns and widgets with a wide range of design options.
In some situations it may seem a little too much, but with more intricate pages, it makes a lot more sense.
Now, if you have a concrete suggestion as to how markup can be cut-down, without giving up any existing features, we would love to hear about it, otherwise, I'm afraid this is not going to change anytime soon and this issue will be closed.

**Comment by stratboy** [comment]
Hi  joshmarom, your is a fair and good answer, your collegue's one is not, at all. That's why I was disappointed. 

You well clarified what I supposed on my first post, so that's fine, thank you. That said, this thread is a feature request (I marked it as [req] because I cannot label it), so just that, a request and  a suggestion.

a. One thing that maybe could be a starting point, could be some kind of API, an exposed (and, above all, well documented) set of functions a developer could use to easily build widgets or sections himself. Those functions could provide functionality to add very basic markup widgets meant for developers. For example, in our case, basic markup for column layouts output would always be just 1 container DIV and N column DIVS. That's all.

b. OR (probably better than the a. solution), for example, there could be some kind of 'developer mode', where the backoffice would just have the bare-bones tools without most of the css-related UI. Somewhat a 'light mode'. Your plugin's live preview already correctly shows the developer's css overrides during preview/editing, so in 'develper mode' (almost) all the styling could be left to the developer. The developer could therefore code up the main templates, save them and make them available to his clients to use.

In fact, I guess this is probably the most common reason a developer can look for tools like Elementor: to let his clients use columns within the wp editor. In my own experience (19+ years of coding..), that's the main thing the standard wp editor lacks (unless one is fine with plain old tinymce advanced  tables, but usually it's not the case..).

Regards

**Comment by drawcard** [comment]
An API is in the works if I'm not mistaken to address things like point a): https://github.com/pojome/elementor/issues/851

If you really want to get rid of all unwanted divs entirely, you could work with a framework like [Bourbon Neat](http://neat.bourbon.io/) and compile some SCSS for a few standard column layouts, and then just set everything up with custom CSS classes. 

The concern about excess DIV's is valid, but it's also negligible - while it would slow a page crawler down to parse more DIV's, that slight impact is so minor in comparison to other typical problems like unoptimised images, non-minified CSS / JS etc.

**Comment by stratboy** [comment]
@drawcard If I correctly understand your answer I don't think it's the case: the main point, the main reason one often looks for tools like Elementor is the lack of columns managements on the wpEditor. In other words, sometimes a developer would like his client (which can't code) to be able to setup and use columns (but without using tables). This implies that all markup must come from the editor.

I already have my own scss grid framework, but that's not the point. The columns must come from the editor and must be visible and well usable from the editor. Here comes Elementor and the like tools.
I insist on the 'developer/light mode', a 'mode' that only does bare-bones structure and let the developer be responsible for frontend layout/styles (the client would then use the developer's saved templates). I realy think it would be a good solution and an opportunity to further open up the plugin's own market. :)

**Comment by joshmarom** [comment]
Like @drawcard said, developer docs are already available, (although still not complete), they allow a great amount of freedom for developers to extend Elementor.

As far as a "developer mode" version of Elementor, this is not something that we can shift our efforts to at the moment. Nevertheless, Elementor is an open source software and you are welcome to fork it and make it your own. 😃

**Comment by drawcard** [comment]
I don't want to reopen this issue but I should explain my response a bit - My suggestion was in relation to your original concern about excessive DIV's in the markup. One way around that is to write a few presets of your own (or use some in the CSS framework of your choice) and then have your client type in the required CSS classes in the "Custom CSS" field in Elementor. 

Eg. if you want 50%/50% columns with minimal markup, you could write your own CSS for that, whether it targets DIV's you create or just stuff higher up in the DOM. Then it's totally hands off for your client (or they can implement one of your own presets).

Mind you, unless you're using something like Bourbon Neat, you'd probably have to create empty "row" and "container" DIV's for each column - that would duplicate the functionality of Elementor anyway, and it would be more of a pain in the long run. So really it's a trade between how much you care about optimised markup vs. ease of use and manageability for your client.

**Comment by stratboy** [comment]
> Eg. if you want 50%/50% columns with minimal markup, you could write your own CSS for that, whether it targets DIV's you create or just stuff higher up in the DOM. Then it's totally hands off for your client (or they can implement one of your own presets).

Mmm. It's interesting but probably I'm not fully understanding what you mean. To make columns and let clients see and use them to put content in, I still need divs, and if I create those with Elementor, elementor will add all the surrounding markup. As far as I know, even boubon neat needs divs for columns. So, do you maybe mean I should use a custom standard wordpress template, assign it to a specific page or post type, so that the columns (or the whole structure) would already be there when the clients opens elementor? Does elementor allow this? If that's the case, it could be a partial solution. Still, as soon as a client would use some of the default elementor structure tools, probably he would break the layout, I guess. Not sure, though.

**Comment by drawcard** [comment]
> To make columns and let clients see and use them to put content in, I still need divs

That's correct but with Neat, you don't need to create non-semantic "container" divs. You can use any DIV you already have set up in a template, like #sidebar & #content inside #main. Neat lets you set up grid frameworks with no superflous divs at all. The docs and examples at http://neat.bourbon.io/ show you how to include their SCSS rules to do this. You can do the same sort of thing with Bootstrap too, but I just have a preference for Bourbon (being more lightweight than BS).

I think though your original concern wasn't about SEO / excess markup, and more about having a bare-bones version of Elementor, letting you configure the container structure to your liking. I can't answer that part of it, but I have poked around the innards of Elementor (in the interests of learning how it works) and you can modify the way Elementor generates the column layout, if you want to dive into the PHP code. But it is totally wild west from there, things could fall out of compatibility and break badly if you aren't sure of what you're doing. So it's probably best to wait for a proper API to extend Elementor with.

**Comment by stratboy** [comment]
Yes yes I know bourbon and the like, that's really not what I need, I code since 1998, I already have my own css framework that does optimised things, no need for third party tools of this kind.

So I'll wait for an API or a dev mode ;) Thank you for all your explanations and for your good work, regards.

**Comment by drawcard** [comment]
No worries.
