### ISSUE TITLE
.elementor-col column classes do not mirror layout settings

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1100]
Hi, I just found out that .elementor-col classes do not mirror layout settings, nor thery are coherent through different sections. Please see the screenshots. Both layouts are basically 2 cols layout, where 1 is 25% and the other is 75%.

On a screenshot we've got .elementor-col-50, while on the other we've got .elementor-col-33 + .elementor-col-66. In both cases they are wrong, and also they are wrong in different ways, so not reliable at all for custom stylings.

![schermata 2016-12-28 alle 16 53 21](https://cloud.githubusercontent.com/assets/437598/21525646/f208a81a-cd1e-11e6-807c-527c3db5f7d7.png)
![schermata 2016-12-28 alle 16 54 06](https://cloud.githubusercontent.com/assets/437598/21525645/f2072b5c-cd1e-11e6-8cd4-446cd85b2fa8.png)

**Comment by joshmarom** [comment]
The .elementor-col classes are just fine.
What you are describing is most probably a result of changing the column width manually. When you do so, the new width is set by a custom css rule written specifically for this element and overrides its original width.

**Comment by stratboy** [comment]
Excuse me, I personally don't think so, they're not fine. You're right, the columns width have been changed manually, but in general frontend classes are meant to be used for styling purposes (or as js hooks), otherwise they're useless. Since those classes are totally unreliable, they can't be used for those purposes and thus, at least, they shouldn't be written out.

Anyway, not a big problem since there are other ways one can use to properly style the columns, in this case for example the nth selectors. But it would be great if you could fix them in future releases.

**Comment by joshmarom** [comment]
I am not sure I understand exactly what is your point.
We have our own responsive grid system (which we never encouraged anyone to make use of), this grid system is very reliable and is used for various purposes throughout the project.
When the user alters a column's width manually, a CSS rule specific for the given column is generated and overrides the class.
The user is also given the option to reset the columns to their original size (through the section settings).

Now I don't quite understand what's wrong with that and what exactly do you suggest we should do?

**Comment by stratboy** [comment]
Ok, maybe I didn't saw the new class you add: what's that?

What I mean is: if I've got an element setted to be 25% width, and it has a class named elementor-col-33, I cannot reliably use that class to reference that element. In fact, the class is describing a non-existent layout (thus, a somewhat non-existent element). It does not describe anything usefull.

So it would be great if, after manually changing a column width to, say, 25%, (within the elementor interface), the column gains a class like elementor-col-25 instead of retaining elementor-col-33. That way I could use it to reference all the 25% columns. Currently, this is not directly possible, and I have to add some other custom class or, where I can, use nth selectors (again, not a really big problem, though).

Luca

**Comment by joshmarom** [comment]
I don't think it is a good Idea to use these classes as selectors in your css because we use them in other scenarios, not just for column width.

> So it would be great if, after manually changing a column width to, say, 25%, (within the elementor interface), the column gains a class like elementor-col-25

This will not work because:
a. We don't have a class elementor-col-46 or elementor-col-47 or many other in-between numbers
b. Keeping the original class allows us to offer the "reset" option in the section panel.

**Comment by stratboy** [comment]
Ok, probably you assume elementor is mainly used by non-develpers, and that's fine, I was wrong since I was starting from the exact opposite point of view.

As a developer, I build wp themes from scratch (based on my own libraries) for each and every project/client. So I only do custom themes. Thus, the way I use Elementor is just to have backoffice tools and frontend markup, not styles. Most of the elementor's elements frontend presentation is overridden by my own styles, and that's why I would like the ability to hook into different types of columns more easily.

As for the 'in-between' numbers, I supposed they could be changed via javascript in real time just as you already do with the visual preview elements.

But anyway, now I understand your point of view, so that's ok.
On another post about markup nesting, I suggested some kind of 'developer mode' for elementor, and this post makes me trying to suggest it again :) Maybe in the future..

Thank you, regards
