### ISSUE TITLE
Timber Integration

### ISSUE THREAD

**Issue by JakeHenshall** [pojome/elementor#1101]
## Description

I'm trying to integrate this with Timber for Wordpress but when I click on  the button to edit with elementor it just hangs and doesnt do anything.

## Steps to reproduce

Using Timber and Kirki within my theme

**Comment by WPDevHQ** [comment]
Please provide code example so that we can see what is going on

**Comment by arielk** [comment]
Still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by JakeHenshall** [comment]
@arielk All that I have done is integrated [timber](https://github.com/timber/timber) and then installed elementor as a plugin through WPackagist.

There may just need to be a certain hook on the page.

Heres my file structure and page.php and page.twig. [Here](http://imgur.com/a/Z3ReZ)

Thanks Jake.
