### ISSUE TITLE
Ajax w/ Elementor Forms

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1113]
I'm using smoothstate.js to transition page content using ajax.  The script targets the .elementor container and also updates the doc head with meta and dependencies such as any different js libraries or unique css however submitting Elementor Pro forms just reloads the page rather than submitting the ajax and the email is never received.

Ex:

-If I navigate from Home to Contact (uses smoothstate.js) and then fill out and submit the form, it reloads the page without form success or email being sent.

-If I go straight to the Contact page and load the url directly and submit the form, the ajax submits correctly, the success message is seen and the email is received.

CF7 had a js trigger you could execute as a callback [wpcf7InitForm()](https://github.com/miguel-perez/smoothState.js/issues/312) and I was wondering if I can do something like this with Elementor too.

**Comment by pingram3541** [comment]
I've made it a little bit further in that I now have form data passing between ajax calls:

```
//capture webform data
var post_id = $(document).find('input[name="post_id"]').val();
var form_id = $(document).find('input[name="form_id"]').val();
var _nonce = $(document).find('input[name="_nonce"]').val();
var referrer = $(document).find('input[name="_wp_http_referer"]').val();
var v_email = $(document).find('input[placeholder="Email"]').val();
var v_msg  = $(document).find('textarea[placeholder="Message"]').val();
var v_name = $(document).find('input[placeholder="Name"]').val();
var v_phone = $(document).find('input[placeholder="Phone"]').val();
                    
//if we have form data, create data object
if( v_name && v_email && v_phone ){
    var webform = [
        {
            "post_id"   : post_id,
            "form_id"   : form_id,
            "_nonce"    : _nonce,
            "email"     : v_email,
            "message"   : v_msg,
            "name"      : v_name,
            "phone"     : v_phone
        }
    ];
    console.log( webform );  //object w/ form data
}
```

Obviously there are validations to be checked, notices to be rendered and of course what to do with this json object to have successful form transactions.

**Comment by matipojo** [comment]
Hi, 
Can you add a script that will run after the page is changed?
Try to run this code only if it's a `smoothstate` loading: 
`elementorFrontend.hooks.doAction( 'frontend/element_ready/form.default' );`

**Comment by pingram3541** [comment]
Sorry I was out of town, going to test this out right now and post results back.

**Comment by pingram3541** [comment]
Except other things like Toggles double up on animations =(

**Comment by matipojo** [comment]
Do you have a public page that we can see it in action?

**Comment by pingram3541** [comment]
Yes, not complete by any means - [http://ekc.tellatek.com/](http://ekc.tellatek.com/)

**Comment by matipojo** [comment]
Its because every ` elementorFrontend.init(); ` is register the animation again.
you need to use the `action`: 
`
onAfter: function( $container ){
   elementorFrontend.hooks.doAction( 'frontend/element_ready/form.default' );
}
`

**Comment by pingram3541** [comment]
Yes but that breaks my site with the UncaughtTypeError mentioned above.  It feels like it needs additional arguments.

**Comment by iShubhamRaj** [comment]
Hi @pingram3541 
I tried to contact you outside this thread, but couldn't get through to you.
I just want to know that how did you manage to load page specific JS and CSS after navigating to new page?
as you said here: 
> updates the doc head with meta and dependencies such as any different js libraries or unique css
