### ISSUE TITLE
Manually set column widths

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#1114]
I have searched the Issues and have not found a request for this but I am certain it was posted a while back.

Anyway, what would be super beneficial is the ability to manually input the values for the column widths, as opposed to the current method of dragging the column handles; not very accurate in most circumstances. 

"Cough cough" ... another popular page builder has this feature and it sure does make life a lot easier :)

Cheers!
Lyle

**Comment by pingram3541** [comment]
Yeah I remember seeing it too. Other refinements would also be having manual controls for selecting elements parent/child/sibling when they are hard to click and moving the current selected element up/down like many of the older back end builders had. I still have daily issues with drag and drop fairly frequently (mega bounce or just can't find the spot easily) and occasionally custom CSS breaks ability to use the builder so I have to prefix everything with body: not(.elementor-editor-active) which adds up to a lot of extra code in the end.

**Comment by arielk** [comment]
This issue has already been written, you can read it here: #847

@SniffleValve please note that your comment there :)

So I merged this issue so that we could deal with it more efficiently. So please let's continue the conversation there.

**Comment by SniffleValve** [comment]
Thanks Ariel, I just KNEW it was already posted  :) I did a search but could not find it.

**Comment by hufer** [comment]
Piotnet Addons For Elementor can do it
https://pafe.piotnet.com/#column-width

**Comment by boltruchok** [comment]
Elementor 5.2.2 doesn't support manual dragging columns width. Probably could you help me with advise?
