### ISSUE TITLE
Italian Translation Elementor PRO

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1116]
[elementor-pro-it_IT.zip](https://github.com/pojome/elementor/files/685459/elementor-pro-it_IT.zip)

Hi guys, I attach here the full Translation for Elementor PRO in italian. 
I hope this is appreciated and included in future versions of Elementor PRO. 

Thank you :)
Davide

**Comment by arielk** [comment]
Thanks for your translation!

I merged your translation. Now go to > Dashboard > Updates > and update the available translations

**Comment by sododesign** [comment]
Thank you very much @arielk 👍
