### ISSUE TITLE
Notice Warning Elementor with element deprecated

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1117]
## Description

In last version of Elementor, with debug true, I Have multiple Notice Warning like this:

<b>Notice</b>:  elementor/frontend/enqueue_scripts/before is <strong>deprecated</strong> since version 1.0.10! Use elementor/frontend/before_enqueue_scripts instead. in <b>C:\Program Files (x86)\Ampps\www\customizer\wp-includes\functions.php</b> on line <b>4034</b><br />

I use the last version of GeneratePress and Elementor. I not have other plugin installed

**Comment by arielk** [comment]
Thanks for your report! Please update to the latest version with patch (1.0.11) and let me know if your errors gone.

**Comment by sododesign** [comment]
Yes, I have this error with 1.0.11 of Elementor

**Comment by KingYes** [comment]
Please disable the `WP_DEBUG` for now until we will release the new Pro version

**Comment by sododesign** [comment]
Thanks. The problem is with Elementor PRO. 

I shall await eagerly the update to fix the problem 👍

**Comment by sododesign** [comment]
HI guys, with the version of Elementor PRO 1.0.7 the problem for Notice is solved.

Thank you very much.
Davide
