### ISSUE TITLE
Update Translation Italian for Elementor PRO 1.0.7

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1121]
Hi guys, I attach here the full translation of Elementor PRO 1.0.7 for Italian Language.

As soon as you can, replace it with the earlier sent.
Thanks,

Davide

[elementor-pro-it_IT.zip](https://github.com/pojome/elementor/files/687652/elementor-pro-it_IT.zip)

**Comment by arielk** [comment]
Do you have an account on the Elementor.com website?

**Comment by sododesign** [comment]
Yes, @arielk. My account is d.pante@sododesign.it. Why?

**Comment by arielk** [comment]
I just added you to manage Italian language in our https://translate.elementor.com/ :)

Please log in to the system and translate it directly.

**Comment by arielk** [comment]
Fully automated :)

**Comment by sododesign** [comment]
You guys Rock!  \--/
