### ISSUE TITLE
Button column height

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1125]
Hey

I inserted a button and noticed the column was higher then I thought, so I did a preview and there it looked fine.

Edit screen:
![screen shot 2017-01-06 at 13 31 02](https://cloud.githubusercontent.com/assets/5323259/21717951/6b7d4a74-d414-11e6-9126-a5043566fec9.png)

Previewing the site:
![screen shot 2017-01-06 at 13 26 38](https://cloud.githubusercontent.com/assets/5323259/21717936/576c3a04-d414-11e6-84be-2e82f7660277.png)

I am not sure what to think of it...

**Comment by drawcard** [comment]
Could be some conflicting CSS in your theme, or maybe you have some padding or margins applied somewhere?

**Comment by paaljoachim** [comment]
Probably. I will keep looking into it and see what comes up.
I will just close this for now.
