### ISSUE TITLE
Missing string translation

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1126]
Hi guys, I noticed that in the Widget Image missing the translation for Insert Media string. In my case, Italian, the po file is translated to 100%, but the string is highlighted in red in English. You can kindly check and add the ability to be able to put these two translatable strings? 

![error-translation](https://cloud.githubusercontent.com/assets/7602983/21718878/94ad037a-d41a-11e6-8828-a8bcba3097a1.jpg)

Thanks so much,
Davide

**Comment by sododesign** [comment]
Here's another missing translation string

![error-string-search](https://cloud.githubusercontent.com/assets/7602983/21718944/10e1dbbe-d41b-11e6-8be2-a4089de5bb20.jpg)

**Comment by KingYes** [comment]
Thanks.

About the "Please enter 2 or more characters", I can't get translate for this right now. It's return by select2..

**Comment by sododesign** [comment]
Thanks @kingyes :)
