### ISSUE TITLE
Suggestion - Elementor Theme Helper Library

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1137]
I've mentioned this around the web quite a bit actually and it's regarding the fact that page builders are bundled on top of themes that often included their own builders and of course their own css/js as it pertains to the structure often called css grid framework.

What I'd like to propose is an Elementor theme helper for those of us that would like to support Elementor right out the gate within our themes and build the theme's grid framework/foundation from Elementor's dependencies so as to minimize bloat and unnecessary duplication of code, sections, wrappers, containers, rows and all that jazz.

Could it ever be feasible that we use a public Elementor library within our themes in such a fashion that when Elementor is activated that it detects the "theme provided" library and bypasses loading it's own built-in version (and of course smart enough to also point out when the theme library is out of date) thus keeping everything as lean as possible?

**Comment by joshmarom** [comment]
The concept you are suggesting makes a lot of sense.
I would recommend including and using the Elementor frontend css files in your theme and use it as a helper css file for grid purposes and other utils:
https://github.com/pojome/elementor/blob/develop/assets/css/frontend.min.css
https://github.com/pojome/elementor/blob/develop/assets/css/frontend-rtl.min.css

And I would only Enqueue it if elementor is not active.

Example:
```php
<?php
function elementor_frontend_enqueue_style() {
	wp_enqueue_style( 'elementor-frontend', get_stylesheet_directory_uri() . '/css/frontend.min.css', false ); 
}
if ( ! class_exists( '\Elementor\Plugin' ) ) {
    add_action( 'wp_enqueue_scripts', 'elementor_frontend_enqueue_style' );
} ?>
```

**Comment by pingram3541** [comment]
@joshmarom Thank you for this.  This actually helps reinforce what I am doing now but was unsure if it was the "right" way or as "complete" as it could be.

I'll be providing a theme welcome page upon activation and can also use that class_exists check to provide a link to install and activate Elementor.  I was curious how Pojo themes handles this if in any way different than other themes.

Also do you suppose this would sensible enough to suggest this as a recommended approach for theme integration in the dev API docs?

Thanks again, this is great stuff and Elementor is quickly overtaking my front end dev workflow =)
