### ISSUE TITLE
[Feature request] SEO & more customization

### ISSUE THREAD

**Issue by Teddii** [pojome/elementor#1138]
Hello all guys. First of all Elementor is an amazing project. Create a section for donation, I think a lot of people would donate to support that project in addition to Pro version.

## Feature requests
I read a lot of requests that can be resolved through a little of self-ingenuity so I think we should focus on bug fixes and expansion of existing functions.
For example:

### Customization

- The ability to enter numeric value in animations, the delay and maybe later the possibility to create complex animations
- The ability to insert the animation on each item of each widget in which it is logical to put them. For example The Lists
- More articulate hover effects and widgets
- Responsive functions on more elements. For example change the background/color or hide icons on tablet and smartphones
- More 2017 web-design trends, like horizzontal scroll and svg, gradient backgrounds and rotations

### SEO improvements
It would be nice to have the ability to implement google snippets and schema.org items. The code on pages seems to be good.

**Comment by netgain** [comment]
As for animations
On any element that includes transitions, (such as the Testimonials) it's important to be able to set
1. delay
2. transition speed, and
3. optional pause on rollover

In my case, testimonials were switching quicker than people could finish reading. I added a separate plugin that lets me set those variables, but it would be better if I could avoid redundant 3rd party plugins.

**Comment by arielk** [comment]
Elementor v1.5 included some of this list, please see the changleog: https://github.com/pojome/elementor/issues/1827

- [x] Element Hover
- [x] Delay of Entrance animation
- [x] Gradient (v1.2)

If you have any more feature request please add a separate new issue.

Thanks for your feedback!
