### ISSUE TITLE
[Request for Widget Posts] - Elementor PRO

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1139]
Widgets Posts is fantastic, but the pagination is not available.
Can we expect in future release of pagination for Widgets Posts?

Thank you very much,
Davide

**Comment by arielk** [comment]
Yes, It's something we're working on so you can expect this upcoming releases (Scheduled to 1.2.0)

**Comment by KingYes** [comment]
We added this on EPro 1.2.0: https://elementor.com/pro-v120-flip-box/
