### ISSUE TITLE
Color select box showing a default white color - Bug -

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1140]
Hey

I have noticed this across all Elementor color select boxes. They all start out with showing a white little square even though the default starting color might be for instance green as in this following screenshot example:

The background color select box is white but look at the button it shows a green background.

![screen shot 2017-01-10 at 03 11 30](https://cloud.githubusercontent.com/assets/5323259/21791408/d6691824-d6e2-11e6-8572-95324ad74143.png)

Selecting another background color as I have with the color grey changes the color select white box to also show a grey box.

![screen shot 2017-01-10 at 03 14 30](https://cloud.githubusercontent.com/assets/5323259/21791435/fef931ca-d6e2-11e6-86c3-dcf406b5761f.png)

**Comment by arielk** [comment]
For now this is something we can not deal with it, because we do not keep the default values in the database (for improved performance) just after you change it to your custom color.

Thanks for your feedback!
