### ISSUE TITLE
Opening a color select - hides other options.

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1141]
One opens the color select.

![screen shot 2017-01-10 at 03 20 47](https://cloud.githubusercontent.com/assets/5323259/21791553/d3817934-d6e3-11e6-9f61-9e37a127a65f.png)

Color select is seen. Selecting a color and clicking outside of it closes the button accordion.
Opening the button accordion again the color select is still seen. 

These areas are not seen when color select is open.
(I have closed color select to show the other areas hidden when it is open.)

![screen shot 2017-01-10 at 03 22 39](https://cloud.githubusercontent.com/assets/5323259/21791593/1ff3986a-d6e4-11e6-84d1-25cd7bf688f8.png)

One has to click the color select box to close the color select area. Clicking outside the color select area does not close the color select area.

When color select is open the other areas should not be hidden away but instead be pushed further down. Like this wireframe example:

![elementor-color-select](https://cloud.githubusercontent.com/assets/5323259/21791717/1021ac78-d6e5-11e6-9e93-b8de68209099.jpg)

**Comment by arielk** [comment]
In the last version of E we added a shadow to improve the UI, check this out:
![2mo8lyo](https://cloud.githubusercontent.com/assets/1778512/22434237/ec72fb52-e723-11e6-954e-1c2d972c6723.png)

Thanks for your feedback!
