### ISSUE TITLE
Request: Navigation Widget

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#1146]
hy,

i would like to use Elementor for One-Page sites. with the anchor-widgets and text-links, buttons, ... there are already good possibilities to jump between sections, but not a ready-to-use menu/navigation.

the problem is, that when i use custom wordpress menus to insert a navigation, i can't customize typography and layout of the list elements there.
another possibility i tried was to insert buttons with nice styling in multiple columns next to each other. this works fine so far (and also breaks into one column on mobile), but is a lot of work to style all buttons.

for both tries, i am missing an option to make this section sticky.

i am not sure if you want to include such functionality, but i guess there would be many sites that do not need anything more than a "blank page template" as a theme. especially when you want to have very different pages in one environment, it would be nice to have such a functionality as widget per page.

thank you for any feedback or hints on how you think it is best to build such a functionality. i would like to avoid external css/js as much as possible.

matt

**Comment by WPDevHQ** [comment]
We have an addon available for download here: http://wpdevhq.com/downloads/elementor-navmenu-addon/

The plugin is still in its infancy but should do what you need :)

**Comment by matthiaswagnerwy** [comment]
@WPDevHQ thanks for the hint ;)
i guess i will stay with my "button-solution" for the current project and give your solution a try next time. would be great if you put it in the wordpress plugin repository so we are informed about updates.

**Comment by SniffleValve** [comment]
Something like this? :)

http://stuffingeneral.com

How to do it here :)

http://snifflevalve.com/tutorials/generatepress-elementor-page-scroll-id-one-page-website

Cheers!
Lyle

**Comment by arielk** [comment]
I think that the solution of @WPDevHQ is very logical. You can set sections by Anchor Menu widget and insert the links by the WP menu widget on the page.

We don't plan to add this feature soon, but thanks for your feedback!
