### ISSUE TITLE
API Request: Re-Use existing widgets

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#1147]
hy,

i would like to see functionality in the API to re-use existing widgets. in my special case i would like to use the image carousel functionality as wrapper for dynamic content which i retrieve from external sources.

it would be good for the frontend to provide the same user experience and easier for the developer.

so in this example, only the image source and image size controls would not be shown, instead other options for content sources. all other controls should stay the same. 

do you have any plans on building such possibilities in elementor (pro)?

matt

**Comment by iamntz** [comment]
Would be possible if the Elementor team would use some kind of a template system (I described a variant in #966 ).

Unfortunately, this is doesn't looks like is going to happen any time soon.

**Comment by KingYes** [comment]
@matthiaswagnerwy How you think it's will be work?

**Comment by iamntz** [comment]
@KingYes sorry I pop in, but this is _somehow_ possible with #971 (which may need a rethinking though):

- you can add extra widget controls
- you can edit existing controls (e.g. add extra options to select fields)

Then #992 will allow you to customize class names (tbh i think it's an overcomplicated solution, but can't think to any other viable alternative to deal with both js AND php at once)

In fact, most of my (ignored) [PR](https://github.com/pojome/elementor/pulls/iamntz)s are focused on extensibility of the existing widgets :)

**Comment by matthiaswagnerwy** [comment]
hy @KingYes ,
i thought of filters without exactly thinking through the whole process. looks like @iamntz has some good inputs on this.
i hope you understand the idea behind this request, which was important for me to place here :)

**Comment by KingYes** [comment]
You can so that with our API. Please read there: https://github.com/pojome/elementor/blob/master/docs/README.md
