### ISSUE TITLE
dependencies question

### ISSUE THREAD

**Issue by robbisy** [pojome/elementor#1155]
Hi 
I've seen in your library that elementor use plenty libraries that I use in my theme like waypoints for my navbar, slick and so on. I would like to know if there's something that can be done to avoid loading many times the same files ?

**Comment by KingYes** [comment]
We are working on some filters/actions you (Theme Author) can use to prevent loading our scripts..  Is will be Okay for you?

**Comment by robbisy** [comment]
It will be great 💯 
@KingYes Do you know if you can add this [feature](https://github.com/pojome/elementor/pull/1124/commits) on you next releases ?

**Comment by KingYes** [comment]
We split the dependencies of our scripts/styles, so you can deregister our scripts/styles.
