### ISSUE TITLE
JS BUG in 1.1.0 and 1.1.1 

### ISSUE THREAD

**Issue by Nirvsoner** [pojome/elementor#1156]
Hi guys, everything is fine on live editor, but when I publish/save this loads the layout broken.

![image](https://cloud.githubusercontent.com/assets/19965325/21858816/d8dfa5c2-d800-11e6-9ce2-076b3ae94627.png)

I did a downgrade again to 1.0.12 and everything works well.
Cheers!

**Comment by KingYes** [comment]
Please clear your browser cache

**Comment by KingYes** [comment]
Or upgrade to v1.1.2
