### ISSUE TITLE
Title elementor

### ISSUE THREAD

**Issue by soniapello** [pojome/elementor#1158]
When I try to edit with elementor without having a title I get this in the title area
<img width="689" alt="title" src="https://cloud.githubusercontent.com/assets/20027271/21876551/29722a2c-d884-11e6-8250-a6079ede46f2.png">

**Comment by KingYes** [comment]
It's from WordPress. WordPress don't use HTML5 placeholder :(

**Comment by soniapello** [comment]
@KingYes  Elementor gives me title by default likes Elementor #363 or Elementor #347 when I don't put title. Is it possible to use elementor on page or post without title ?
