### ISSUE TITLE
editor preview issues for mobile

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1161]
sad to say, that suddenly the preview in editor for mobile does not work as expected:
it does not render correctly when using full width stretched sections - in this case theres horizontal sroll and therefore content cant be controlled...
think that did work untill 1.0.9 or so. still trying to find older version to verify

**Comment by arielk** [comment]
Can you please deactivate the all plugins (except Elementor), change to default theme and let me know if this solves the problem?

**Comment by arielk** [comment]
Please let continue in #1169
