### ISSUE TITLE
Suggestion - Advanced - Navigator Panel

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1165]
This addresses many issues reported regarding the fact that editor controls are inline with the actual preview content DOM and often there are themes, plugins, or just plain desired website designs that will break edit-ability.

Furthermore, it addresses the current drag and drop experience outside of those examples where the default behavior leaves more to be desired.  I've had frustrations as recent as today just trying to drag an image widget from one column to the next.

Here is a screenshot of how webflow provides a tree like navigator that lets you move elements up/down/in/out while also being able to change the css class assigned to that element completely outside the preview.

![navigator](https://cloud.githubusercontent.com/assets/319284/21903020/0b3aa9c4-d8b3-11e6-9d40-4b8f92c207d4.jpg)

**Comment by WPDevHQ** [comment]
This suggestion/enhancement gets my vote. +1

**Comment by dasigna** [comment]
second vote +1 from my side.
but it seems to me , that this should possibly going hand in hand with some highlighting of current choosen element (would sometimes be great anyway - maybe ability to toggle on or off ?)

**Comment by pingram3541** [comment]
@dasigna Yes, that is a great suggestion.  If I understand correctly, what you propose is while one hovers over or has selected, a section, column, or widget in the navigator panel, the preview area highlights that particular item for easy identification of the desired element to adjust?

**Comment by dasigna** [comment]
... completely correct understanding.

i know things like these may easy go too far and get things overcomplicated very easy... tweaking drag'n'drop might come first, but highlighting is a great idea anyway - sometimes having lots of items in view and suddenly seeing myself searching for the choosen one (often clicking again to be sure :-) )
so this might come at some later point.

in the end there may be many things that might be possible as well as helpful - and to let the user (or developer) choose if needed or want to use it, it might be still another good idea to toggle those items on or off from a settings page.

**Comment by pingram3541** [comment]
Yes and I'm even ok with a "development mode" flag in functions.php or similar so the general public get's the easy peezy editor while the pro's get the tools they really desire =)

**Comment by arielk** [comment]
Very interesting 👍

**Comment by ehausen** [comment]
Example from [Pinegrow](https://pinegrow.com/) website editor

They have a [online demo](https://pinegrow.com/edit.html?page=index.html) of their old version: 

![screen shot 2017-03-11 at 16 03 48](https://cloud.githubusercontent.com/assets/6204129/23823880/5e43c97c-0674-11e7-82cb-6f7fc331589f.png)

**Comment by ehausen** [comment]
Also the mentioned GrapeJs has a decent element navigator  http://grapesjs.com/demo.html

**Comment by pingram3541** [comment]
@ehausen I also like how grapge.js provides a way to toggle the visibility of each block too.

**Comment by ehausen** [comment]
This would also allow a clear way to select multiple elements #1173

**Comment by camilosw** [comment]
Flatsome theme has a builder with that feature, but unfortunately their builder can't be used with other themes. I just started using Elementor and I like it, and also want to see this feature implemented.

![image](https://user-images.githubusercontent.com/1142037/28467731-6f5d1f44-6df6-11e7-9894-4d33f4106926.png)

**Comment by Fxcrafter** [comment]
I've attempted to create an add-on plugin for this. I'm about 50% there, but struggling with the js side of things, if anyone with backbone/marionette experience wants to help me out, it won't take much effort at all to get a basic version out.

**Comment by black-eye** [comment]
+1 This would be really handy

**Comment by tristanleboss** [comment]
+1 @Fxcrafter Did you manage to finish your work? The JS of Elementor is a nightmare to work with due to the lack of action/filter hook points.

**Comment by Fxcrafter** [comment]
@tristanleboss Here is the [plugin](https://wordpress.org/plugins/navigation-tree-elementor) I hope it helps.

**Comment by joelbqz** [comment]
@Fxcrafter just made a prototype of this: https://jumpshare.com/v/GRRp6nrkOmAgLWEj7CWd feel free to use my design if you find it useful! :) Cheers.

**Comment by joelbqz** [comment]
@bainternet is this feature really on your roadmap? This issue has more than 1 year, most of us thinks this feature is must for any page builder.

**Comment by themedleb** [comment]
+1

**Comment by ArekZw** [comment]
+1

**Comment by parfilov** [comment]
Hooray! It's already in beta =)

**Comment by Clubware** [comment]
Show / hide elements on button click.
Show/hide elements after time. 
Clickfunnels has this feature built in. Surely Elementor can do it.
