### ISSUE TITLE
pro cant be updated on local? - issue

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1166]
bug or feature? pro refuses to update within plugins panel on local enviroment.
"_Update Failed: Could not create directory. elementor-pro/modules/panel-posts-control/controls_"
its the only plugin that shows this behaviour... !!
php memory limit ist set to 512M in xampp - elementor reports only 40M, when adressing 128M over config elementor shows 128M but update doesnt work anyway ... ???

**Comment by SniffleValve** [comment]
> its the only plugin that shows this behaviour... !!
Not particularly ... Beaver Builder Pro, GeneratePress Premium, WP Show Posts Pro ... and others, exhibit this same behavior on local installs for me. There was a discussion about this in one of the support forums, GP I believe, and it had to do with the number of characters that are generated during an update and this number exceeded the maximum allowed under Windows. Hmm ... I'll have to try this on my Mac :)

**Comment by raydale** [comment]
Elementor Pro updates successfully on Mac (using MAMP at the moment) as does Beaver Builder Pro etc.

As @SniffleValve mentions, this seems to be a Windows / XAMPP issue?

**Comment by dasigna** [comment]
o.k. @SniffleValve ist right - its not the only one - GPpro seems to do the same indeed.
but all others do work as expected. maybe a WIN thing in fact ...?

only detail that makes me wonder is the reported 40M memlimit from elementor where all others report the correct 512M.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
