### ISSUE TITLE
no pro templates?

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1167]
... just wanted to show some pro template - but its not shown in library!
its 'the coffee shop' one i cant find - amongst others ... 

could swear there was a day when those templates showed up with a 'pro'-mark. but cant see this any longer, so where to grab them???

**Comment by galaxyweb** [comment]
I do see the "Pro" templates myself but even though I am a Pro user with an active license, I am seeing the "Go Pro" button instead of "Insert".
https://www.screencast.com/t/EPN8F88h5L

**Comment by joshmarom** [comment]
Which version of the plugin are you guys using?

**Comment by galaxyweb** [comment]
I just tested with plugin v1.1.3 and pro v1.0.8 and am not experiencing the issue any longer. I was previously on pro v1.0.4.

**Comment by dasigna** [comment]
... just tested with both latest versions and they are there... exept for the 'coffe shop' template shown on pro-site in preview. sadly that was the one a client has asked for :-)

**Comment by joshmarom** [comment]
> ... exept for the 'coffe shop' template shown on pro-site in preview. sadly that was the one a client has asked for

You are right. We haven't published this template yet. It will be released soon.
If you would like to get it already, please email us (support@elementor.com) and we'll send it to you 😁
