### ISSUE TITLE
Timber Integration

### ISSUE THREAD

**Issue by JakeHenshall** [pojome/elementor#1168]
Description

I'm trying to integrate this with Timber for Wordpress but when I click on the button to edit with elementor it just hangs and doesnt do anything.

Steps to reproduce

Using Timber and Kirki within my theme

Environment

All that I have done is integrated [timber](https://github.com/timber/timber) and then installed elementor as a plugin through WPackagist.

There may just need to be a certain hook on the page.

Heres my file structure and page.php and page.twig. [Here](http://imgur.com/a/Z3ReZ)

Thanks Jake.

**Comment by JakeHenshall** [comment]
I've answered my own question. I was using my own version of jQuery which it didnt like. As long as {{ body.content }} is in the twig file it should work fine.

Thanks Jake.

**Comment by tiagomatosweb** [comment]
Hi @JakeHenshall, I have the same issue, and the body.content didn't do the trick.
What have you actually done?

**Comment by tiagomatosweb** [comment]
I forgot to add wp_foot function. dammm
