### ISSUE TITLE
Feature Request: Better handling of global colors

### ISSUE THREAD

**Issue by Stegosource** [pojome/elementor#1170]
## Description

I like the concept of global color swatches that make it fast and easy to select brand colors, but I feel like the current implementation in Elementor is not the best approach. I really dont like how the global colors are tied directly to certain elements. This means that if I want to use the global colors to take advantage of the easy access, Elementor will overwrite the theme's color scheme for things like headers or paragraphs. But I dont want my elements to automatically get the global colors, I want to keep the theme styles in tact, but make the global colors easy to select.

## Recommendation

What I would propose as the ideal solution would be to separate the connection between global styles and element styling. This way, the global styles are just an easy access theme, and the theme's default styles do not get overwritten. 

For users that want to overwrite elements, there is already the global fonts section. We can just apply the color selection there. And in that selection, you can have a dropdown for how to handle colors for each element. The default option is to use theme styles, the second option is to use a global color (this would tie it to 'primary' or 'secondary' so if those change, it is reflected), and the last option is custom color which could then offer a colorpicker. 

To me, this is a great solution to keep theme styles easily available while offering better style management features, and still using most of the current setup/implementation the plugin already offers.

Would love to hear your feedback on this.

**Comment by SniffleValve** [comment]
The functionality you describe is already available :)

- Dashboard > Elementor > Settings > tick the two boxes: Disable Color Palettes and Disable Default Fonts > Save Changes
Now your theme's fonts and colors will be the defaults for all Ementor items.

For "Branding" colors: 

- from the Elementor menu on the Elementor panel > Color Picker
- edit any or all of the top eight colors with your brand's colors > Apply > Save

Now those colors will be available in any of the Elementor items where the color may be selected :)

Cheers!
Lyle

**Comment by Stegosource** [comment]
Ahhhh. I see now. I thought that's what the global colors tab was for. Well this is helpful. Thank you :)

Well, it may still be nice to have more font style options in the global fonts, but for my purposes the theme styles is right.

Thanks a lot for the response. Consider this feature request closed ^_^

**Comment by raydale** [comment]
The default font and color settings in Elementor seem a really odd choice. The theme installed should govern font and colour choices by default and not have other defaults imposed as soon as Elementor is installed.

I can't think of any circumstance where I have wanted 'Disable Color Palettes' or 'Disable Default Fonts' not checked. Shouldn't this be the default on install of Elementor? The current defaults must be confusing for people?

**Comment by arielk** [comment]
@raydale Thank you for your feedback, we will consider it for next versions

**Comment by ineagu** [comment]
@arielk there is any way for a theme to disable colors/fonts by default? like using a filter?

**Comment by carasmo** [comment]
+1 Yes, Elementor's colors/fonts should be off by default or a filter.

**Comment by ineagu** [comment]
To add more context here, I believe that the theme should take care of default styling, color schemes, typography etc, while the builder provide the 'building' experience.

I understand that this comes in conflict with the newly introduced skins concept for example, however going in a site builder direction rather than a page builder one, conflict with theme developers like us. Not sure if is a public roadmap or so, but would be great to know what are pojo plans with this to see how much it makes sense to recommend it to our users.

**Comment by carasmo** [comment]
I created a PR for filters, fingers crossed! https://github.com/pojome/elementor/pull/1784.

```
function myprefix_elementor_filter_typography_color_default_checkbox(){
	return 'yes';
}
add_filter( 'elementor_disable_typography_schemes', 'myprefix_elementor_filter_typography_color_default_checkbox' );
add_filter( 'elementor_disable_color_schemes', 'myprefix_elementor_filter_typography_color_default_checkbox' );

```

**Comment by mehedi-sharif** [comment]
@carasmo , Your small hack does not works for me.

**Comment by carasmo** [comment]
That's because it's not part of Elementor. It was a PR and it never got applied.

**Comment by alfgago** [comment]
Absolutely agree, it should be a filter. I'm starting to build a theme using Elementor as Page Builder, but I need to be able to disable this by default. Maybe even block the option to activate it again as long as the theme is active.

Also, couldn't find this in the API, any built in way to get the Global Colors and Global Fonts in a template or in my own shortcodes/functions?
