### ISSUE TITLE
Feature Request: reset/cancel local parameter 

### ISSUE THREAD

**Issue by remyrichard** [pojome/elementor#1171]
Hi
It would be usefull to have a button to cancel a property (to reset and return to global css)
Divi has an icon "return arrow" to do this ...

thanx

**Comment by arielk** [comment]
I'm not sure what do you mean, can you please explain more about this feature ?

**Comment by remyrichard** [comment]
Hi ! 

Here is the images of divi vs. elementor.
If i want to delete the properties, Divi offers a return arrow which appears to delete all fields.
With elemetor, we have to delete the field.

But this is not a big deal ;)

<img width="355" alt="divi" src="https://cloud.githubusercontent.com/assets/3696345/21975182/7eae30ea-dbcb-11e6-950e-81d02919daba.png">
<img width="613" alt="elementor" src="https://cloud.githubusercontent.com/assets/3696345/21975181/7ead85be-dbcb-11e6-8309-c63a1ee1f42d.png">

**Comment by arielk** [comment]
Actually, you should know that if you delete the value in a single field, all fields are changed. This saves us from the need to add a reset button, and keeps Elementor's UI minimal, like I know folks like yourself appreciate :)

Thanks for your feedback!
