### ISSUE TITLE
Feature request: extend global widgets to also enable global templates

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#1172]
## Description
Just started to use the global widgets Pro feature and while it is great, I was very disappointed to realize that global templates are not also an option. I've been hoping to be able to create global templates of sections or columns of my site that repeat several times (but not on every page.)

Here's an example: A whole subsection of pages on our site has the same chunk of information at the bottom of each page (this is not the sitewide footer.) Having this as a global section or template would be a huge timesaver.

![sub-footer-section](https://cloud.githubusercontent.com/assets/974442/21940670/360939aa-d97a-11e6-96fc-cf847d78e2f3.jpg)

**Comment by joshmarom** [comment]
I believe what you need is the "Template" widget.
<img width="322" alt="template_widget" src="https://cloud.githubusercontent.com/assets/2726148/21962017/02bba3fe-db22-11e6-8050-5e1be68ee0a8.png">

First save the design you want to re-use as a template, then you can insert it anywhere using the Template widget.

Let me know if that resolves your issue.

**Comment by pingram3541** [comment]
Yes and to add, using that template throughout the site via widget or shortcode makes that template itself "global" but don't forget, it can also contain global widgets within it.  That way those widgets that are global can be within or outside that template but still update without having to go back and edit your template.

**Comment by mizejewski** [comment]
Inception indeed :)
Sounds like what's described above *would* work, but it would be much simpler conceptually and to manage if there could be global **sections** as well as global **elements**. Thanks for considering this feature @arielk

**Comment by napa-web-designer** [comment]
I would still like to make the case and request for Global Templates. Example in case, I am creating a page header for the title of each page of a large site. I created a Template of the Section but the styling of the Section and Column provide specific margins for the block style layout of my site. I have a global widget inside but that does not help if I need to change the margins set in the Section or Column. In order to do that across the site I would and will have to go to every page and change it (or use CSS which is likely what I would do).

**Comment by pingram3541** [comment]
As I suggested above this can be done by simply using the Template widget.

- Save section as a template, delete it from the page
- Add a new section
- Set it to full width and no gap (if desired)
- Drop in a Template Widget
- Choose original template from the drop down

_* may need to refresh page if template didn't already exist before loading the editor_

rinse. repeat.
