### ISSUE TITLE
Elementor plugin stuck on loading

### ISSUE THREAD

**Issue by AjandanAmuthan** [pojome/elementor#1174]
## Description

So I have had some issues while trying to use the Elementor plugin. I have tried using this is chrome, mozilla firefox. Changed the PHP and even went as far as deleting all the files and trying to install wordpress and elementor fresh. However whatever I do I still face the same issue of having the elementor loading on a loop as soon as i click edit with elementor. 
I have tried using different version of the plugin and still no help.
I have probably tried following all the steps that others had followed to resolve their problem, but still get the same outcome of having it stuck on loading.

## Steps to reproduce

Install elementor
Click edit with elementor
Get stuck on loading loop

## Environment

					
== Server Environment ==
	Operating System: WINNT
	Software: Microsoft-IIS/8.5
	MySQL version: 5.6.26
	PHP Version: 7.0.14
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.4.6
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Permalink Structure: /index.php/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Sixteen
	Version: 1.1
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.1.2
		Author: Elementor.com

**Comment by WPDevHQ** [comment]
Is this a localhost on a Windows machine or is it a live server running Windows Server? If it's a live server, what's your Web.config configuration?

Have you tried upgrading WordPress to the latest version?

Switch your permalink to `%year%/%monthnum%/%day%/%postname%/` and try reloading the Elementor Editor.

**Comment by AjandanAmuthan** [comment]
I somehow got it to work my deleting everything again and installing the latest update of WordPress and elementary, however now when I try to use a static page instead of a blog. I keep getting the error message of "you have been redirected too many times" and this problem automatically goes away when I don't use a static page.

**Comment by WPDevHQ** [comment]
That is one of the drawbacks of IIS and rewrite rules configuration - its a pain to get it right. The main issue is that it insists on using the above permalink structure which pertain to posts and not pages.

See this: https://www.iis.net/learn/extensions/url-rewrite-module/enabling-pretty-permalinks-in-wordpress - there doesn't seem to be an easier way around this issue

**Comment by AjandanAmuthan** [comment]
Sorry im not really familiar with doing this. In my wordpress app ( using it with smarterasp hosting ) I was able to change the permalink structure to the one you listed. However I am unable to find out how to paste the following XML section into the system.webServer element. I could not find any file with that name. I tried just creating a new file and pasting the XML section, but it still redirecting me. Is there any other way to get have a static page instead of a blog section.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by Gabrielmrpr** [comment]
Hello guys in my case was the Addons for Elementor by  Livemesh Version 1.6 on WP  4.9.6 elementor ver is   v2.0.14 last version of fire fox and chrome on windows 10 pro 64. So know I just need to get an alternative well guys hope this can help or at least give some ideas. until the next time.
