### ISSUE TITLE
How to create a custom control?

### ISSUE THREAD

**Issue by iamntz** [pojome/elementor#1175]
Just like the title says, because the docs doesn't cover this.

I manage to display the custom controls:

```php
use \Elementor\Control_Base_Multiple;
class MyCtrl extends Control_Base_Multiple
{

  public function get_type()
  {
    return 'myctrl';
  }

  public function content_template() {
    ?>
      <input type="text" data-setting="foo" />
      <input type="text" data-setting="bar" />
    <?php
  }
}
```

And I registered like so:

```php
add_action('elementor/init', function () {
  \Elementor\Plugin::instance()->controls_manager->register_control('myctrl', 'MyCtrl');
});
```

When I hit save, the data is sent to the server (i.e. appears in console), but when I reload the page, the control is empty. (also when I switch to a different widget then back to my control, the field is empty)
 
Thanks.

**Comment by cobicarmel** [comment]
Hi @iamntz 

Currently there isn't an official API way to build a correct multiple control.

For now, you can do it at your own risk by doing the following steps:

- Create a JS class that extends the `ControlBaseMultipleItemView` JS class.
- Listen to the `controls:initialize` event on `elementor.channels.editor` and then add your previously created class to the `elementor._controlsItemView` object, under a same key as your custom control type.

For example:
```JavaScript
elementor.channels.editor.on( 'controls:initialize', function() {
	elementor._controlsItemView.myctrl = MyCtrlClass;
} );
```

**Comment by iamntz** [comment]
> Create a JS class that extends the ControlBaseMultipleItemView JS class.

This is exactly where I was stuck last evening.

`require` resolves some Ace-related code, and `ControlBaseMultipleItemView` is not there

```
console.log(typeof ControlBaseMultipleItemView); // undefined
````

**Comment by iamntz** [comment]
I _think_ that this could be fixed by adding `require` as a param:

```
this.channels.editor.trigger( 'controls:initialize', require );
```

**Comment by cobicarmel** [comment]
That's right. Currently the `ControlBaseMultipleItemView` is a private class which is available only inside the elementor system.

However, you can include the [browserify](http://browserify.org/) module in your own project, that will allow you to require any private module from the elementor JS library.

**Comment by iamntz** [comment]
I'm pretty sure that's not how it works.

> Browserify creates self-contained bundles, without exposing anything to the global namespace unless you use the --standalone flag, in which case only the library's name gets a global binding.

http://stackoverflow.com/a/29134736

Keep digging...

**Comment by cobicarmel** [comment]
You don't need the global namespace. If your project folder located in the same environment as the elementor plugin, you can simply require any of its modules by specifying the module absolute path.

For example:
`require( 'elementor/assets/dev/js/editor/views/controls/base-multiple' ) `.

Please note that if the required module includes any alias directory, you will also need to define the alias in your own project.

**Comment by iamntz** [comment]
>  If your project folder located in the same environment as the elementor plugin

Ah, i know what you're saying now, to `require` the actual file and build it like that. The problem with this is that it will be *very* sensitive to updates, which I'm pretty sure I don't want (it's a plugin for a customer)

**Comment by cobicarmel** [comment]
Of course, and as noted above, this is **not** the correct way to do that.

**Comment by iamntz** [comment]
Alright. Hopefully this will be addressed soon.

Or maybe there is any suggestion on having this functionality:

1. having multiple fields into a component (somehow like box shadow component);
1. having an autocomplete field (that fetches info by ajax) and some of other fields can be filled by the first autocomplete;
1. some of the subsequent fields should be also autocomplete.

Or [chained selects](https://www.appelsiini.net/projects/chained). Etc.

**Comment by pingram3541** [comment]
Yes I wanted this from day 1 especially in the case of section and column controls.  I had anticipated the API would allow for this but as long as the classes and functions are defined as private the 3 main things I wanted with the API are currently locked (at least from doing it properly), and those 3 are:

1) Ability to add custom control
2) Ability to modify the section control (specifically settings array, i.e. add a custom field)
...I was going to add an ID field before this was added into core but could not do it without core edits
3) Modify Column Control - (add more grid choices, option to disable 20px bottom margin)

As far as I can tell we're currently limited to a small subset of allowed filters or tapping a global var but outside of that, the API limits us to widgets and everything higher in the chain is still private / protected.

**Comment by Quaked** [comment]
So I'm guessing me appending, adding and changing settings for a **section** is also limited and the current API won't help? That's really a bummer. Unlock the potential please!

**Comment by sandeshjangam** [comment]
Still, Developer API is in progress? Is there any way now to create a custom control?

**Comment by bainternet** [comment]
Its in the developers API https://developers.elementor.com/creating-a-new-control/

**Comment by Ginoggi** [comment]
I created the class EmojiOneArea_Control like described in this example above.

now i don't  know how to implement it:
        $this->add_control(
			'custom_html',
			[
				'label' => __( 'Emoji', 'plugin-domain' ),
				'type' => 'emojionearea',
			]
		);

Who can help? The Final Notes are too short for me. 

=========================
...
use EmojiOneArea_Control\Control\EmojiOneArea_Control;

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

class PXElementorFormfieldWidgetPlugin {

	/**
	 * Plugin constructor.
	 */
	public function __construct() {
		$this->add_actions();
	}

	private function add_actions() {
		add_action( 'elementor/widgets/widgets_registered', [ $this, 'on_widgets_registered' ] );
		add_action( 'elementor/controls/controls_registered', [ $this, 'on_controls_registered' ] );       
	}

	public function on_widgets_registered() {
		$this->includes();
		$this->register_widget();
	}
	
	public function on_controls_registered(){	
		$this->includes_control();
		$this->register_control();
	}

	private function includes_control() {
		require __DIR__ . '/control/EmojiOneArea_Control.php';
	}
	
	private function register_control() 
        {	    
                $controls_manager = \Elementor\Plugin::instance()->controls_manager;
		$controls_manager->register_control( 'EmojiOneArea_Control', new EmojiOneArea_Control() );
	}
       ....

**Comment by tomjefferson** [comment]
correct last function like this:
private function register_control() 
    {	    
            $controls_manager = \Elementor\Plugin::instance()->controls_manager;
	$controls_manager->register_control( 'emojionearea', new EmojiOneArea_Control() );
}

**Comment by yashprajapati1617** [comment]
Thank You So much @tomjefferson
