### ISSUE TITLE
request: Cc field for elementor forms

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#1181]
hy,
it would be great to have a Cc and Bcc field in the forms widget. so we could create a mail that the site visitor receives as confirmation and inform the site owner via the same mail.

in addition, it would also be great to have a custom "reply-to" field instead of the dropdown, as well as the possibility to select "E-Mail Field" for the recipient to achieve the above workflow.

thanks :)

**Comment by drawcard** [comment]
What would also be cool, is if there was an option on the frontend to let the sender of the form  receive a copy of it as well (by using the email address they fill out in the form). The sender can then have a copy of the form submission for their records.

**Comment by svipic** [comment]
+1 on that. It would be very useful when there will be Bcc option for forms

**Comment by pmmueller** [comment]
+1 for an option to let the sender of the form receive a copy as suggested by @drawcard.

**Comment by arielk** [comment]
release in E-Pro v1.3.0

**Comment by matthiaswagnerwy** [comment]
@arielk i am trying this out right now and it is great to have Cc and Bcc fields, but i can not find a way to send a copy to the visitor who fills out the form. in none of the fields "To", "Cc" and "Bcc" it is possible to select an e-mail field from the form.
the best would be, if in any of these fields there is a dropdown with every available e-mail field and another option "custom". when selected "custom" there appears a text-field to enter this custom e-mail-address.

**Comment by arielk** [comment]
We have just added the infrastructure for this. In the next version we will add option like you wrote using Field Shortcode

**Comment by localpcguy** [comment]
Allowing custom emails via the client side is extremely dangerous and opens up your form to being used for spam. Bots will use that field to send emails to whoever they want (by submitting it with custom email addresses over and over). Just replying here to raise awareness.
