### ISSUE TITLE
caption suggestion

### ISSUE THREAD

**Issue by soniapello** [pojome/elementor#1183]
When we use image carousel we can add cation under each image we choose but it is use in the alt of the image. Is it possible to have the caption text on the image ?

**Comment by soniapello** [comment]
https://github.com/pojome/elementor/pull/1124

**Comment by drawcard** [comment]
Just so you know I am working on this solution a bit more, to offer an option to absolutely position the caption and pick a background colour for it. I'll keep the PR updated!

**Comment by soniapello** [comment]
@drawcard It will be a great functionality. 🥇
I'll stay tuned
