### ISSUE TITLE
add some fields to image-carousel request

### ISSUE THREAD

**Issue by michellomp** [pojome/elementor#1197]
Hi
I want to know if it's possible to add caption on carousel-image widget and also the centerMode control of slick slider. By default slick add slick-current to the first slide and slick-active class to all visible slide. There is no way to add animation on the center slide. With a centerMode control which can be a toggle true false, we can add animation on the center slide

**Comment by drawcard** [comment]
I wrote a pull request for this one: https://github.com/pojome/elementor/pull/1124

Though I'm not sure how to fix the Travis CI failure on it (do I need to merge in any updates from pojome/elementor/master first?)

**Comment by arielk** [comment]
Thanks @drawcard ! We will review it soon, I want to push it to the next major release 1.2.0

**Comment by michellomp** [comment]
@arielk Will it have  the centerMode control ?

**Comment by arielk** [comment]
@michellomp Unfortunately this made some strange conflicts, maybe in the future we will add it.
