### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by marcofrasson** [pojome/elementor#1201]
I noticed that the default margin and padding values are not shown when opening these areas.

It would be interesting to them, because if we need to change only one value (eg padding-top), the other values will be “0”.

If you have two or more columns, which have 10 standard padding, and want to add an extra padding to some, it loses the default value unless you already have in the field and the person can keep.

I did this, and had to look at the elemental inspector to see what the pattern was, to keep.

**Comment by arielk** [comment]
For now this is something we can not deal with it, because we do not keep the default settings in the database (for improved performance).

Thanks for your feedback!
