### ISSUE TITLE
Default WordPress widget checkboxes not holding values

### ISSUE THREAD

**Issue by raydale** [pojome/elementor#1210]
I cannot find mention of this issue anywhere else, so please ignore if this is a duplicate anywhere.

The problem is that the default widgets don't seem to be holding their values when a checkbox is selected within an elementor enabled page.

To recreate this simply drag a default WP widget such as the Archive widget into Elementor on a page. Check 'Display as dropdown' and save the page. The actual widget behaves as expected. However, upon saving and refreshing the 'Display as dropdown'  checkbox will revert back to unchecked even though the widget shows its checked setting in the editor.

I'm testing in the latest version of Google Chrome on OSX with MAMP.

**Comment by KingYes** [comment]
WordPress don't handle with selected values in Archives widget.

This is the Form method from WP code:

```
/**
	 * Outputs the settings form for the Archives widget.
	 *
	 * @since 2.8.0
	 * @access public
	 *
	 * @param array $instance Current settings.
	 */
	public function form( $instance ) {
		$instance = wp_parse_args( (array) $instance, array( 'title' => '', 'count' => 0, 'dropdown' => '') );
		$title = sanitize_text_field( $instance['title'] );
		?>
		<p><label for="<?php echo $this->get_field_id('title'); ?>"><?php _e('Title:'); ?></label> <input class="widefat" id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name('title'); ?>" type="text" value="<?php echo esc_attr($title); ?>" /></p>
		<p>
			<input class="checkbox" type="checkbox"<?php checked( $instance['dropdown'] ); ?> id="<?php echo $this->get_field_id('dropdown'); ?>" name="<?php echo $this->get_field_name('dropdown'); ?>" /> <label for="<?php echo $this->get_field_id('dropdown'); ?>"><?php _e('Display as dropdown'); ?></label>
			<br/>
			<input class="checkbox" type="checkbox"<?php checked( $instance['count'] ); ?> id="<?php echo $this->get_field_id('count'); ?>" name="<?php echo $this->get_field_name('count'); ?>" /> <label for="<?php echo $this->get_field_id('count'); ?>"><?php _e('Show post counts'); ?></label>
		</p>
		<?php
	}
```

You can see the title has value, but the `checkbox` are not :(

**Comment by KingYes** [comment]
Thanks.
