### ISSUE TITLE
changes not save

### ISSUE THREAD

**Issue by raulversus** [pojome/elementor#1211]
## BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions, or need general support, send the issue to: https://wordpress.org/support/plugin/elementor 
- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/
- To read more about Elementor, check out our documentation: https://docs.elementor.com

===== Guidelines ====

- Search this repository (top of the page) for the issue, and make sure it has not been fixed or reported before.
- Make sure you are using the most updated versions of Elementor, WordPress & your theme.
- Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).
- If you're requesting a new feature, explain why you'd like it to be added. Try to add as much detail as you can, and be specific.

-->

## Steps to reproduce

Changes saved on a page do not always apply later in
"See the page"

I works whit generate press theme 

## BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions, or need general support, send the issue to: https://wordpress.org/support/plugin/elementor 
- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/
- To read more about Elementor, check out our documentation: https://docs.elementor.com

===== Guidelines ====

- Search this repository (top of the page) for the issue, and make sure it has not been fixed or reported before.
- Make sure you are using the most updated versions of Elementor, WordPress & your theme.
- Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).
- If you're requesting a new feature, explain why you'd like it to be added. Try to add as much detail as you can, and be specific.

-->

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
