### ISSUE TITLE
PHP Hooks to change defaults [developer api]

### ISSUE THREAD

**Issue by Nirvsoner** [pojome/elementor#1224]
Hi guys, I'm building a wordpress theme that uses elementor as main builder, is there a hook or something I can do to change this settings as default via theme?

![image](https://cloud.githubusercontent.com/assets/19965325/22321873/7b2d3fb0-e36e-11e6-81d9-cdaa5f306f51.png)

I would like to have 'elementor_disable_color_schemes' and 'elementor_disable_typography_schemes' disabled by default when installing elementor with my theme active.

Cheers!

**Comment by KingYes** [comment]
You can disable by override the options by this:

```
update_option( 'elementor_disable_color_schemes', 'yes' );
update_option( 'elementor_disable_typography_schemes', 'yes' );
```

**Comment by Nirvsoner** [comment]
Thank you!
