### ISSUE TITLE
Docs: Missing Group_Control_Typography documentation

### ISSUE THREAD

**Issue by luizeof** [pojome/elementor#1232]
## Description

Documentation for Group_Control_Typography missing on elementor repository.

I'm creating an widget for extending elementor and the following code not working and I not found any documentation for help.

		$this->add_group_control(
			Group_Control_Typography::get_type(),
			[
				'name' => 'typo_label',
				'label' => __( 'Label Typography', 'my-form-designer' ),
				'scheme' => Scheme_Typography::TYPOGRAPHY_4,
				'selectors' => [
					'{{WRAPPER}} .form-label',
				]
			]
		);

		$this->add_group_control(
			Group_Control_Typography::get_type(),
			[
				'name' => 'typo_btn',
				'label' => __( 'Button Typography', 'my-form-designer' ),
				'scheme' => Scheme_Typography::TYPOGRAPHY_4,
				'selectors' => [
					'{{WRAPPER}} .form-button',
				]
			]
		);

When running on Elementor Builder the second Group_Control_Typography overrides the first even the selectors pointing to different css classes.

Any help?

Thanks!

## Environment

Elementor Pro + GeneratePress Premium

**Comment by luizeof** [comment]
@benpines

**Comment by luizeof** [comment]
@arielk

**Comment by luizeof** [comment]
I've Pushed to #1237

**Comment by luizeof** [comment]
Fix #1232

**Comment by KingYes** [comment]
In Group Controls use `selector` key. You can see this example: https://github.com/pojome/elementor/blob/bf563f65e3ce176eae6c35e73f8240a92fdf1bb6/includes/widgets/common.php#L111
