### ISSUE TITLE
animation delay request

### ISSUE THREAD

**Issue by robbisy** [pojome/elementor#1233]
Is it possible to add delay to entrance animation ?

**Comment by robbisy** [comment]
@KingYes @arielk In the advanced section there's by default entrance animation which add data-animation and elementor-invisible class to elementor-widget div.
I wonder if there's a hook and something else for adding this to another div class ?
Thanks

**Comment by TheMangoTrain** [comment]
This issue should be closed.

Elementor now has Delay controls for entrance animations (for at least 6 months now).
