### ISSUE TITLE
pro: empty img-tag if no thumbnail available

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#1234]
hy,

when i use the "Posts" widget from elementor-pro to show pages, it displays an empty image tag with all the margins around when there is no featured image set for a page.

that should be handled somehwere to show either a placeholder or an according view with no img tag, so that it also looks good if some pages have a featured image and some not.

**Comment by KingYes** [comment]
Thanks,
We fix this and will release in EPro `1.3.2`
