### ISSUE TITLE
Bulk Import / Export for Template Library

### ISSUE THREAD

**Issue by luizeof** [pojome/elementor#1241]
## Description

Elementor makes web development great again. We can create Entire Pages and even some sections to automate website creation and reuse some sections and templates on another websites.

But today we have more than 70 templates for elementor and import one by one consuming a lot of time.

There are a chance to make Elementor Import more than one template at time or make an zip import with some templates inside?

Thanks for all your support.

## Environment

I'm using Elementor Pro

**Comment by WPDevHQ** [comment]
A better solution would be the ever popular request for cloud hosted templates.

Members can add, share and/or even sell their creations and then all it would take is connect, sellect and sync!

**Comment by arielk** [comment]
@WPDevHQ It's definitely something that is on the table.

Maybe we'll add a tool to export all the library to the ZIP file.

**Comment by teolaz** [comment]
@arielk Another funny thing would be to have a tool which can allow to bulk export directly from the "Pages" section of Wordpress. Let's speak about it with an example.

I have a multisite network with 2 identical sites, 1 in italian, 1 in english. 30 pages are all done with different templates, and i finished the italian insertions. Now, to have the exact copy of the site in english, with all the media imported to the correct multisite folder, i should:

- goto each template, and save into the library (30 times)
- export any single template (30 times)
- import any single template (30 times)
- rebuild the information architecture in english
- assign each template to each page (30 times)

**Comment by teolaz** [comment]
@arielk please refer to #1884

**Comment by arielk** [comment]
Merged #2077 

@teolaz Thanks for great work!

**Comment by mohitsth4** [comment]
Need to import 4000 templates in one take is that possible ???

**Comment by oooh-boi** [comment]
It's a dead end, right?

**Comment by mredodos** [comment]
+1

**Comment by talha-rafique** [comment]
bulk import and export should be included, and also images are not included in .json file when export from localhost, also include images in BASE64 form and include in JSON file of template.

**Comment by javothemes** [comment]
+1

**Comment by MilesTails01** [comment]
+1

**Comment by almahmudbd** [comment]
alas +1.
not it is 2024.
