### ISSUE TITLE
Problemas con Gmedia Gallery

### ISSUE THREAD

**Issue by caesarcd** [pojome/elementor#1242]
Buenas noches. 
Utilizando el plugins Gmedia Gallery (codeasily.com), y el modulo Phantom, no carga las fotos. Las miniaturas se ven bien, pero al pinchar en ellas, sale el mensaje de “The image could not be loaded”, y si vueles a pinchar, se carga la foto, pero en una ventana, y sin las opciones de compartir, veces visto, etc…Es una incompatibilidad de Elementor o de Gmedia Gallery. Gracias.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
