### ISSUE TITLE
Allow user choose custom section ID

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#1248]
Is there anyway to allow user choose a custom ID for section? instead of auto generated IDs?
I want to make a template with sections for an onepage page, and need to set anchors on menus for sections:

Section About: **#aboutus**
on menu <a href="#aboutus"></a>

But currently section IDs are like: **#elementor-element-px4s9dr**

any idea?

**Comment by KingYes** [comment]
Added on `v1.2.0`.
#939
