### ISSUE TITLE
elementor does not start up on fresh posts in multisite for editor-role

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#1254]
hy,

i have a multisite-network with elementor enabled for pages and some custom post types. all user roles in the elementor-settings page are excluded, except editor.
when i am logged in as an editor, i can see the elementor-switch-mode-button where it is supposed to be, but when i click it it does not load elementor - instead the post is saved (post.php?post=xxx$action=edit&message=4 gets called). i can even see the normal save/publish button gets grayed out, as if i would click this.

when i open such a post as an admin first and save it in elementor, then try to open it as editor again, it works fine.

thanks for your help :)

this is the system info (from this network-page, logged in as network-admin)
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.33
	PHP Version: 7.0.14-nmm1
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.2
	Site URL: http://tmk-allhartsberg.vereinsheim.at
	Home URL: http://tmk-allhartsberg.vereinsheim.at
	WP Multisite: Yes
	Max Upload Size: 3 MB
	Memory limit: 64M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Vienna
	Debug Mode: Active

== Theme ==
	Name: Musik 2016
	Version: 1.0.0
	Author: Matthias Wagner, FALKEmedia GmbH
	Child Theme: No

== User ==
	Role: 
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12

== Network Plugins ==
	Advanced Custom Fields PRO
		Version: 5.5.5
		Author: Elliot Condon

	Elementor
		Version: 1.1.7
		Author: Elementor.com

	Elementor Pro
		Version: 1.1.1
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.5
		Author: Till Krüss

	EWWW Image Optimizer
		Version: 3.2.3
		Author: Shane Bishop

	FakerPress
		Version: 0.4.7
		Author: Gustavo Bordoni

	MCE Table Buttons
		Version: 3.2
		Author: Jake Goldman, 10up, Oomph

	Redirection
		Version: 2.5
		Author: John Godley

	Yoast SEO
		Version: 4.1
		Author: Team Yoast

== Must-Use Plugins ==
	vereinswebsite-functionality.php
		Version: 
		Author:

**Comment by matthiaswagnerwy** [comment]
additional note: it is also not possible to switch back to wordpress editor when logged in as an editor...

**Comment by matthiaswagnerwy** [comment]
another note: it is possible to just open the site with ?elementor as url-appendix and then the functionality is as expected. so it looks like it is only a problem of the button, nothing bigger behind it ;)

hope you are able to reproduce this issue

**Comment by matthiaswagnerwy** [comment]
i have another note for you on this case. i just saw that it has nothing to do with multisite - it occurs even on a fresh installation of a single site.
if you are an editor and click "edit with elementor" (if the page has not been edited with elementor before) it just saves the page and nothing more happens.

additionally, you have the admin-menu "Elementor" with sub-menu "Settings" visible. If you click it, it tells you that you don't have the rights to access this page.

sorry, but this looks like you do not switch user roles often when testing ;) if you want to enable elementor for clients, this is a big issue in my eyes. would be happy about feedback :/

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by matthiaswagnerwy** [comment]
thanks for your feedback - i just tested it out in another fresh single-site installation with the newest version of elementor and it is working there.

**Comment by matthiaswagnerwy** [comment]
hy,
i just found out that it is a problem of the yoast seo plugin. if anyone has the same problem, please see this thread for workarounds (the issue there is still open): https://github.com/Yoast/wordpress-seo/issues/4367
