### ISSUE TITLE
request: make elementor only accessible on certain page templates

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#1259]
hy,
as i do often code uniqe page templates in web projects it would be great to have not only the possibility to choose on which post types elementor should be possible to use, but also depending on which template is used in that page/post.

and as always, keep on your great work - i love elementor :)

**Comment by L00Cyph3r** [comment]
I just remove the 'action' that adds the button.
Code I use for removing the 'Edit with Elementor'-button on certain post-types:
```PHP
add_action('admin_enqueue_scripts', 'removeElementorSwitchButton', 0);
function removeElementorSwitchButton() {
    if (is_plugin_active('elementor/elementor.php')) {
      self::removeFilter(
        'edit_form_after_title',
        'Elementor\Admin',
        'print_switch_mode_button'
      );
    }
  }
```

Hope this helps.

**Comment by matthiaswagnerwy** [comment]
@L00Cyph3r thanks for the hint. i have made the workaround with admin CSS styles which hide the button under specific conditions. your solution is smarter ;)

**Comment by bainternet** [comment]
Glab you figured this out.
