### ISSUE TITLE
Icons Hook

### ISSUE THREAD

**Issue by Nirvsoner** [pojome/elementor#1260]
Hi,

Is there a way/hook to add our own iconfonts to the ICON CONTROL list?

`$this->add_control(
    'icon',
    [
        'label' => __( 'Social Icon', 'your-plugin' ),
        'type' => Controls_Manager::ICON,
        'include' => [
            'my-icon icon-name-1',
            'my-icon icon-name-2',
        ],
    ]
);`

I was thinking to add some CSS to identify the icon in the list, but I dont think this is the correct way

`.select2-results__option .icon-name-1:after { content: 'icon-name';  }`

Cheers

**Comment by arielk** [comment]
Thanks for your feedback!
We're considering it for the future, right now I merge it to previous issue in the same subject #110
