### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#1261]
Any chance of getting more explainers on the API of all things please?

I'm more interested in the difference between schemes i.e.
Scheme_Color::COLOR_1, Scheme_Color::COLOR_2, Scheme_Color::COLOR_3

Scheme_Typography::TYPOGRAPHY_1, Scheme_Typography::TYPOGRAPHY_2, Scheme_Typography::TYPOGRAPHY_3

The difference(the why), the how and the when to use which scheme would be very much appreciated

**Comment by joshmarom** [comment]
Hi @WPDevHQ 
In Elementor there is a Typography scheme that consists of 4 typography types and there is a Color Scheme that consists of 4 colors.
The typography defaults can be set by the user from the panel menu > Global Fonts
<img width="300" alt="screen shot 2017-02-08 at 15 42 06" src="https://cloud.githubusercontent.com/assets/2726148/22739920/6a516d26-ee16-11e6-8223-3a464842adf3.png">
The Color Scheme can be set (or chosen from a collection of presets) from the panel menu > Global Colors
<img width="299" alt="screen shot 2017-02-08 at 15 42 32" src="https://cloud.githubusercontent.com/assets/2726148/22740026/df07aac2-ee16-11e6-8adc-06a59930551d.png">

These four types of defaults are meant to allow widget developer to maintain a consistent visual pattern.
Any Element that has the Schemes design setting, will be automatically effected by any change on the global settings.

I hope this helps you understand the concept. If you have any more questions let me know.

**Comment by WPDevHQ** [comment]
Getting to know Elementor better and you have been a great help @joshmarom, thank you.
