### ISSUE TITLE
Issues when debug is true

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1266]
Hi guys, with last version of Elementor I have two warning when debug is set to true.

Warning: Invalid argument supplied for foreach() in /home/vouuwltn/ucm.sododesign.it/wp-content/plugins/elementor/includes/css-file/post-css-file.php on line 61

PHP Notice:  Undefined index: max in /home/vouuwltn/ucm.sododesign.it/wp-content/plugins/elementor/includes/stylesheet.php on line 265

**Comment by sododesign** [comment]
Hi @KingYes I have another big notice for Javascript:

Uncaught TypeError: Cannot read property 'addExternalListener' of undefined

File: /wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.1.1

This notice is in version PRO of Elementor

**Comment by arielk** [comment]
Can you please define debug as true ?

**Comment by KingYes** [comment]
Fixed on EPro `v1.1.2`. Thanks.

**Comment by sododesign** [comment]
Please, any notice for this bug??

Warning: Invalid argument supplied for foreach() in /home/vouuwltn/ucm.sododesign.it/wp-content/plugins/elementor/includes/css-file/post-css-file.php on line 61

PHP Notice: Undefined index: max in /home/vouuwltn/ucm.sododesign.it/wp-content/plugins/elementor/includes/stylesheet.php on line 265
