### ISSUE TITLE
When content does not cover the full height of a page.

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1267]
Hey

The issue is this:
Some pages might not have enough content to cover the full height of a page.
Even though one fills in the sections with a background color there will likely be an area below the content where the body background color of the theme shows through.

This means we need default page settings to where one can add a background color or image etc.

For reference:
#632

**Comment by paaljoachim** [comment]
Detailing the issue:

The page builder only stretches as far as one adds sections and columns to the page. Below the default the inserted sections/columns the theme body background color is seen.
Se screenshot 1. The default body background of the theme is white and can be seen below the sections added with Elementor.

![screen shot 2017-02-02 at 14 35 22](https://cloud.githubusercontent.com/assets/5323259/22551839/b6411764-e956-11e6-86b1-e37a7f9e4d4e.png)


I go into the customizer -> Additional CSS.
Se screenshot 2.

![screen shot 2017-02-02 at 14 36 49](https://cloud.githubusercontent.com/assets/5323259/22551842/be45e2c8-e956-11e6-8d3e-867f38ae6aa1.png)


I uncomment the body.home CSS background color. 
Se screenshot 3.

![screen shot 2017-02-02 at 14 38 04](https://cloud.githubusercontent.com/assets/5323259/22551845/c202b198-e956-11e6-844a-31674c579ba9.png)


I go back to editing the front page with Elementor. Because I added another body background color. The default white body background is now changed outside of Elementor to a violet.
Se screenshot 4.

![screen shot 2017-02-02 at 14 38 54](https://cloud.githubusercontent.com/assets/5323259/22551850/c804fd12-e956-11e6-8fd7-735e30664373.png)


I need a way for Elementor to add a full page body background color.
The customer wants a violet on the front page. I add it through Elementor as background color in the sections. BUT I also have to change the theme body.home background color.

The customer has split the site into two parts. One orange background and another a blue background. This is in addition to the front page that has a violet color.
This means I have to through CSS be sure to add the correct body background color to all the pages used. As some of the pages do not have enough Elementor content to cover the default theme background color. Similar to the front page. So that means I have to be sure that atleast those pages have the correct background color.

NB!
IF the customer takes away content of the page leaving just a little content made through Elementor the theme body background color will shine through.
This is way one needs a per page settings in Elementor.

Thanks.

**Comment by joshmarom** [comment]
This is not an Elementor issue.
Elementor Is designed to handle only what's in the content area.

**Comment by carasmo** [comment]
@paaljoachim I noticed this too, but if you know how CSS behaves, then a min-height will work as expected. In my Section settings, I choose Min Height (rather than Fit to Screen) and choose 100vh. Then the content flows page when I scroll or if content is taller than the viewport height.

![screen shot 2017-04-27 at 2 17 54 pm](https://cloud.githubusercontent.com/assets/1124594/25498037/7cff8d1a-2b54-11e7-8891-bb1ae3e86093.png)

**Comment by paaljoachim** [comment]
@carasmo That is a very good idea! Thanks!

**Comment by fairchic** [comment]
Thanks @carasmo - that solved my issue too.
A new one then sprang up - I used a nest section to create a horizontal menu across the bottom of the screen within the same outer section and now that gets pushed off the bottom of the VH and I'm having to use negative margins, etc. to get it back. Surely if the layout of the whole section is set to the settings above, it should just fit on the screen?
