### ISSUE TITLE
[Enhancement] Sync Templates

### ISSUE THREAD

**Issue by lunacroft** [pojome/elementor#1268]
Imagine a website with 50, 100, 200 pages. Now imagine you create a partners block and save it in My Templates area. Then, 6 months later you need to update partners images, you will need to update them in 50, 100, 200 pages.

My propose is just update your base template saved at My Templates, and this will be automatically updated to all pages.

Is is possible? It would be great and would save a lot of time!

**Comment by arielk** [comment]
Sorry, but I could not understand what you mean, could you please explain a bit more about the problem? Perhaps you mean [Global Widget](http://docs.elementor.com/article/100-global)?

**Comment by lunacroft** [comment]
Yes, exactly! Thanks!
