### ISSUE TITLE
Element Toggle not displayed in mobile

### ISSUE THREAD

**Issue by oto-xara** [pojome/elementor#1269]
Element Toggle not displayed in mobile
http://prntscr.com/e3wosz
http://prntscr.com/e3wp01
http://prntscr.com/e3wpce

screenshot of my phone
http://prntscr.com/e3wquc

**Comment by arielk** [comment]
Which mobile device you checked it? Can you send us a link to the page?

**Comment by oto-xara** [comment]
I have tried on different phones
link to the page
http://romantic.ua/concierge/

this block is not visible on the phone
http://prntscr.com/e4qq1h

**Comment by arielk** [comment]
Please go to your section of this widget > Advanced tab > Responsive > Visibility > and check your settigns
