### ISSUE TITLE
Javascript click events

### ISSUE THREAD

**Issue by vfxdude** [pojome/elementor#127]
The Elementor click events override the widgets click events. For example there is no way to see tab 2 of the tab widget. And it would be useful to see tab 2 etc. while editing it's content.

A related idea would be make it possible to navigate to other pages using the site navigation (like the wp customizer does).

**Comment by yehudah** [comment]
Hi,

You can enter preview mode by closing the edit panel or pressing the second tab , see the image.

![elementor](https://cloud.githubusercontent.com/assets/1655373/16306111/4b5db692-3965-11e6-8f8d-a5c745510ba9.png)

**Comment by vfxdude** [comment]
ok, I did not know that. It helps, but is a bit cumbersome approach. Why can't there be a edit widget button instead, so that it doesn't block the widgets javascript click events?

**Comment by vfxdude** [comment]
Take a look at the tab module of Live Composer, how it can create stuff in the webpage. Elementor blocks this possibility. I'm not saying that the frontend javascript should work, but that it should be possible to add custom builder js for widgets to do such things. And a js api to sync with the sidebar and saving. I see you are using js templates for widgets, this opens up a lot of possibilities, but not if click events are blocked.

**Comment by vfxdude** [comment]
Just to further explain what I'm talking about. If I add the css below, the tabs works in builder mode:

```
#elementor .elementor-element>.elementor-element-overlay {   
    z-index: -1;
}
```
There is an overlay container on top of all widgets used as an edit widget button. Wouldn't it be better with a small button on the side or top?

**Comment by vfxdude** [comment]
Buttons that appear on hover, like the widget label, and maybe replace the label with buttons like this:
![widget-buttons](https://cloud.githubusercontent.com/assets/20110677/16356397/23fbfb14-3ad6-11e6-972e-dbb71f45a0a1.png)

Then there will be no need for a click event over the whole widget, just hover.

**Comment by yehudah** [comment]
The full overlay give you the option to drag and drop in each place on the widget insted of searching the specific point to grab it.

Think of the case, when you press the tabs the editor pane open and by click the tabs there you can easily see you content, so nothing hard about it.

**Comment by vfxdude** [comment]
When I tested it, for some reason, the tabs did not open when I wrote in the title or content. I see now that it does that, same with the accordion. Then clicking in the website is not that important.

> Think of the case, when you press the tabs the editor pane open and by click the tabs there you can easily see you content, so nothing hard about it.
It doesn't focus the tab in the website before you write something, maybe the focusing can be on expanding the item or a focus button. Just seeing the textarea is not good enough.

**Comment by vfxdude** [comment]
I guess this can be implemented per widget. The overlay can be toggled on click/blur. Just thinking about the implementation of an inline text editor like the [Note widget plugin](https://nb.wordpress.org/plugins/note/) (not that I'm going to implement it).

**Comment by vfxdude** [comment]
Weebly.com's solution:

![image](https://cloud.githubusercontent.com/assets/20110677/16560286/b66e4dda-41f2-11e6-9c7b-ac12cf6838f2.png)

There is a drag handle at the top (centered) of every widget, and they are using an inline text editor.

btw, the builder of weebly.com looks at first look very much like Elementor.
