### ISSUE TITLE
Posts element causes javascript error

### ISSUE THREAD

**Issue by dax702** [pojome/elementor#1271]
Having the Posts element on a page causes this javascript error you see in the screenshot, which causes Elementor form submissions not to work.  See related post on Facebook group: 
https://www.facebook.com/groups/Elementors/permalink/1057036447755474/

![code](https://cloud.githubusercontent.com/assets/19275233/22612463/1f0eb38c-ea2e-11e6-9603-76e1e33485d3.PNG)
All we were able to determine is that it's somehow caused by the Posts element. Duplicated the problem on two different sites.

**Comment by KingYes** [comment]
Fixed on EPro `v1.1.2`. Thanks.
