### ISSUE TITLE
Remove control

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#1272]
Currently we have the ability to `add_control()` and `update_control()` - do we also have the ability to `remove_control()`?

If not, is there any plans to add the option in?

**Comment by joshmarom** [comment]
Yes.
See https://github.com/pojome/elementor/blob/master/includes/base/element-base.php#L140

**Comment by WPDevHQ** [comment]
Awesome, thank you.

**Comment by Basilakis** [comment]
@WPDevHQ 

Hey mate,

I am trying to remove the " icon " box, from the Buttons, so I can register mine.
Have you made the remove_control work, can you please drop me a hand of help, please?

Thank you

**Comment by WPDevHQ** [comment]
Sorry @joshmarom - I need to reopen this.

Due to lack of documentation I've been unable to get this to work in line with the `add_control` aproach.

Can you shed some light on how we could implement a removal of a control please?

**Comment by Basilakis** [comment]
+1

**Comment by joshmarom** [comment]
Can you give me an example of what you are trying to do and how do you go about it?

Also, are you familiar with our hooks like: https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md#elementorelementelement_namesection_idbefore_section_end ?

**Comment by Basilakis** [comment]
@joshmarom 

I am trying to remove the " icon " box, from the Buttons, so I can register mine.
Have you made the remove_control work, can you please drop me a hand of help, please?

**Comment by atMaarten** [comment]
Can their be documentaction added for the update_control() and the remove_control() functions?

**Comment by norewp** [comment]
@joshmarom this still needs attention please
