### ISSUE TITLE
Settings: Control for Page Templates

### ISSUE THREAD

**Issue by l3enito** [pojome/elementor#1276]
The feature request: Lots of great templates,  BUT:  We have our own templates and sections in perfect layout to build pages. 

-> BUT why the Elementor template library  is always showing up first? I do not want editors to chose nor to see other "designs". 

PLEASE add a check to remove elementor "free page templates" (they are nice, but we have our owns :) )

**Comment by pingram3541** [comment]
Yes, this should be a filter so we can add out own templates in place of or in addition to the built-in Elementor templates.

**Comment by Nirvsoner** [comment]
bump :)

**Comment by arielk** [comment]
Thanks for your feedback! 
I merged this issue with another issue #417 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.
