### ISSUE TITLE
Pro: Conflict with Yoast SEO Plugin (PHP Notice)

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#1278]
hy,
i have a multisite network running both Yoast SEO and Elementor + Pro in the latest versions (see info below). debug is on. when i use the posts widget from the pro elements in a page with default settings, there appears a php notice in the html head (no matter if logged in or not):

looks like this widget is somehow conflicting with the twitter functionality from yoast...

```
<br />
<b>Notice</b>:  Uninitialized string offset: 0 in <b>/www/htdocs/w01579fc/wp-content/plugins/wordpress-seo/frontend/class-twitter.php</b> on line <b>476</b><br />
<!-- / Yoast SEO plugin. -->
```

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.33
	PHP Version: 7.0.14-nmm1
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.2
	Site URL: http://tmk-allhartsberg.vereinsheim.at
	Home URL: http://tmk-allhartsberg.vereinsheim.at
	WP Multisite: Yes
	Max Upload Size: 3 MB
	Memory limit: 64M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Vienna
	Debug Mode: Active

== Theme ==
	Name: Musik 2016
	Version: 1.0.0
	Author: Matthias Wagner, FALKEmedia GmbH
	Child Theme: No

== User ==
	Role: 
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8

== Network Plugins ==
	Advanced Custom Fields PRO
		Version: 5.5.5
		Author: Elliot Condon

	Elementor
		Version: 1.2.0
		Author: Elementor.com

	Elementor Pro
		Version: 1.1.2
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.5
		Author: Till Krüss

	EWWW Image Optimizer
		Version: 3.2.5
		Author: Shane Bishop

	FakerPress
		Version: 0.4.7
		Author: Gustavo Bordoni

	Loco Translate
		Version: 2.0.11
		Author: Tim Whitlock

	MCE Table Buttons
		Version: 3.2
		Author: Jake Goldman, 10up, Oomph

	Redirection
		Version: 2.5
		Author: John Godley

	Yoast SEO
		Version: 4.2.1
		Author: Team Yoast

== Must-Use Plugins ==
	vereinswebsite-functionality.php
		Version: 
		Author:

**Comment by arielk** [comment]
Please deactivate all of other plugins (Include mu plugins). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by matthiaswagnerwy** [comment]
it is not a problem for me by now, as debug mode will be disabled for the project when going live of course.
just wanted to report to help you make elementor even better :)

**Comment by arielk** [comment]
I tried to reproduce the problem in our development environment, and I could not see any notice. So I thought if we could check the problem in your environment we can test it more thoroughly :(
