### ISSUE TITLE
Uncaught ReferenceError: Trying to move button after non-existing button `removeformat`

### ISSUE THREAD

**Issue by IamAdamJowett** [pojome/elementor#1280]
## Description

When adding a new Text Editor component when creating a template I get the following error when clicking on it to edit:

"Uncaught ReferenceError: Trying to move button after non-existing button `removeformat`"

Below is the full output:

![error](https://cloud.githubusercontent.com/assets/294948/22726709/a0216b86-ee20-11e6-8d1d-0be13cfb736e.png)

## Steps to reproduce

- Create a new template
- Add a Text Editor component
- Click on the added component to edit
- Check the console for errors

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.33
	PHP Version: 5.6.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.6.1
	Site URL: http://tob.mettroproof.com.au
	Home URL: http://tob.mettroproof.com.au
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Training Ombudsman
	Version: 1.0.0
	Author: Mettro
	Child Theme: Yes
	Parent Theme Name: Project ME
	Parent Theme Version: 1.0.0
	Parent Theme Author: Mettro Pty Ltd

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 4.4.11
		Author: Elliot Condon

	Breadcrumb NavXT
		Version: 5.6.0
		Author: John Havlik

	cPanel & WHM® Site Software
		Version: 1.0
		Author: cPanel, Inc.

	Duplicate Page
		Version: 2.2
		Author: mndpsingh287

	Elementor
		Version: 1.2.0
		Author: Elementor.com

	TinyMCE Advanced
		Version: 4.4.1
		Author: Andrew Ozz

	Visualizer: Charts and Graphs Lite
		Version: 1.7.6
		Author: Themeisle

	Wordfence Security
		Version: 6.3.1
		Author: Wordfence

	WordPress Charts
		Version: 0.7.0
		Author: Paul van Zyl

	Yoast SEO
		Version: 4.2.1
		Author: Team Yoast

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by isaacsgraphic** [comment]
I'm getting the same error. 

![screen shot 2017-02-09 at 13 33 49](https://cloud.githubusercontent.com/assets/16480575/22785543/a161c99e-eecc-11e6-896d-c30365575265.png)

I'm in a situation where I can't remove the plugins since it's a live site, and haven't been able to reproduce it on the separate site I set up to test, even when I add the same plugins which the original site has.

The only thing I have in common with Adam is the Advanced Custom Fields plugin, but adding that to my test site doesn't cause the error.

**Comment by isaacsgraphic** [comment]
Good news! 

I was able to replicate the problem on a different site of mine, and narrow it down to a conflict with TinyMCE editor (which we also both share). I think it must be a new option or something in TinyMCE. To fix: Open up **Settings>TinyMCE Advanced**, scroll to the bottom section "**Administration**" and uncheck "**Editors on the front end of the site**". Remember to hit Save Changes.

I bet you have the same issue Adam.

**Comment by arielk** [comment]
@isaacsgraphic thanks for your comment!

**Comment by IamAdamJowett** [comment]
@isaacsgraphic that was exactly it, it is the TinyMCE Advanced plugin (not the standard one that is part of WP) it seems. Nice find mate, thanks!
