### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by ligne13** [pojome/elementor#1287]
## Description

jQuery is not defined in my custom theme when I activate Elementor. I guess Elementor unregister the default Wordpress jQuery and should register its own instance of jQuery, but in my case I get this error : 

```Uncaught ReferenceError: jQuery is not defined```

## Environment

Wordpress
Elementor
My own custom theme (very basic for now) :

page.php :

```
<?php
/* Template Name: Full width */

get_header(); ?>

    <div class="container-fluid">
		<?php
		if ( have_posts() ) :

			/* Start the Loop */
			while ( have_posts() ) : the_post();

				the_content();

			endwhile;

		endif;
		?>
    </div>


<?php get_footer();
```

header.php :

```
<!DOCTYPE html>
<html <?php language_attributes(); ?> class="no-js no-svg">
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="profile" href="http://gmpg.org/xfn/11">

	<?php wp_head(); ?>

</head>

<body <?php body_class(); ?>>
```

footer.php :

```
<?php wp_footer(); ?>

</body>
</html>
```

and my functions.php is empty for now !

thanks

**Comment by KingYes** [comment]
We are register jQuery lib in Editor mode. The error you get in Frontend?

**Comment by ligne13** [comment]
The bug is gone now... Obviously this was not really a bug ;-)

**Comment by Kevinlearynet** [comment]
To be clear, this could still exist with the latest up to date version as of today 7/25/2017. If your theme is deregistering jQuery, having something like this in it:

`wp_deregister_script( 'jquery' );`

Then make sure you're calling the `wp_enqueue_scripts` action hook at the default priority (12). I had this issue in a custom theme using an add_action $priority of 1:

`add_action( 'wp_enqueue_scripts', 'kevinlearynet_assets', 1 );`

Changing it to this solved the issue:

`add_action( 'wp_enqueue_scripts', 'kevinlearynet_assets' );`
