### ISSUE TITLE
Isotope (Masonry) JS library not working in preview

### ISSUE THREAD

**Issue by ryanlabelle** [pojome/elementor#1288]
Thank you for an amazing plugin. We are developing a theme using Elementor but I can't seem to get Isotope masonry mode working in preview. 

I'm using a simple example: http://codepen.io/desandro/pen/mIkhq

We are using wp_enqueue_script to enqueue the library and our js file. but when I 

`$('.grid').isotope({
  itemSelector: '.grid-item',
  percentPosition: true,
  masonry: {
    columnWidth: '.grid-sizer'
  }
});`

.grid is not available. It's like the script is loading before the element is available. I ran a check just before and I can't detect the element I'm targeting.

`console.log('BEFORE');
    if ($('.grid').length){
    	console.log('FOUND IT');
	}else{
        console.log('NOT THERE');
	}`

and I get a "NOT THERE" when in preview mode, but it everything works in the frontend. 

I think this is similar to : https://github.com/pojome/elementor/issues/762#issuecomment-257116760 but the solution does not help this issue. 

Any advice?

**Comment by KingYes** [comment]
The element is build after the page is ready (in Preview Mode).

Is it widget based on Shortcode or what?

**Comment by ryanlabelle** [comment]
Thank you for responding. 

it's a JS library, you can see the codepen here: http://codepen.io/desandro/pen/mIkhq

We are enqueue using wp_enqueue_script and then:

`$('.grid').isotope({
  itemSelector: '.grid-item',
  percentPosition: true,
  masonry: {
    columnWidth: '.grid-sizer'
  }
});`

except the .grid element is not yet available or accessible so the script never get initialized. It only means the masonry effect does not run in preview, but runs fine in the frontend. 

Any advice? 

Tomorrow I'll take apart your slider widget and see how you get that to work. I'm sure there is something I don't know or am missing. I figured you might be able to throw some light on it. 

I really love using your plugin, it's been a real pleasure to work with. Thank you.

**Comment by michellomp** [comment]
I have the same problem. I've tried to add an isotope widget to elementor but it only works on front end .
Probably the wp enqueue isn't enough and we need an "enqueue" function in elementor for adding more js libraries to elementor preview

**Comment by lasida** [comment]
You can use this Hook for enquene jquery lib https://github.com/pojome/elementor/blob/develop/docs/content/hooks/php-hooks.md
in my case this is working in editor / preview mode, and in frontend work as well

**Comment by ryanlabelle** [comment]
@lasida You are running isotope? Using elementor/editor/before_enqueue_scripts or elementor/frontend/before_enqueue_scripts for me does not make a difference. I'm already wp_enqueue_script the isotope script in my theme, and when I inspect in preview mode, the script is included inside the preview iframe. However it's almost as if the element isn't available yet when isotope tries to find it:

`$('.grid').isotope({ itemSelector: '.grid-item', percentPosition: true, masonry: { columnWidth: '.grid-sizer' } });`

Does not work because .grid is not found. I checked the same time I run isotope and .grid length is 0 using...

`$('.grid').length`

I know the preview is done in an iframe, I'm not sure if this is throwing things off.

**Comment by lasida** [comment]
I am running OwlCarousel, you can use **elementor/editor/before_enqueue_scripts** for enquene jquery in editor panel elementor, and **elementor/frontend/before_enqueue_scripts** for frontend without editor panel. you can load the code in **window.load** and accessing iframe child with **contents()**, element always be not available if you accessing without **contents()**, because element position inside iframe.

**Comment by robbisy** [comment]
@lasida I try to add OwlCarousel widget but I have one problem  When I add a new widget the js doesn't see it . I had to save and reload the elementor preview in order to make it work. Have you find a way to look after each change on preview page ?

**Comment by lasida** [comment]
for make jquery working after saving, i use event when input change, or keydown, it will trigger to my interval function to check loader ajax available or not, if loader available, status will be on and will trigger the function, and element working as well, maybe this is not good way, cause if your internet slowly sometimes it will affect to your element, maybe author plugin can explain the good way for creating custom element with jquery lib.

**Comment by ryanlabelle** [comment]
@lasida Thank you. Yes an even trigger was the next step. I've also tried iframe contents() and I still was not able to make it work. I'll spend more time on this. The strange things is that somethings already work well, some scripts are only loaded in the original theme and elementor includes them no problem in the preview, others need to have an key up event or be enqueued specifically in the editor. 

@robbisy Maybe that's right, I've only tried Isotope, I'm going to spend some more time on it and I"ll post any findings here. :) Yes, the only way to make it works in some cases to to save and reload, but with isotope, not even saving makes it work. It only works in the frontend.

**Comment by michellomp** [comment]
@ryanlabelle  Do you manage to make it work ?

**Comment by KingYes** [comment]
If you using with Shortcode / WP widget, try to press "Apply" button and check if it's working for you.

BTW, in frontend mode is working okay for you?

**Comment by michellomp** [comment]
@KingYes For me it's working in preview and frontend. No issue anymore.

**Comment by KingYes** [comment]
@ryanlabelle: We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by mehedi-sharif** [comment]
I am having the same issue but with owl carousel , When I am trying to edit the element and it just broke . @lasida Can you please help me.
Thanks

**Comment by Simpleqode** [comment]
Did you sort out this issue? None of my JS plugin work in the preview mode when editing an element. Workin fine in the front-end.

**Comment by mehedi-sharif** [comment]
@Simpleqode 
Yes I got a solution . 
jQuery(window).on('elementor/frontend/init', function () {
    elementorFrontend.hooks.addAction('frontend/element_ready/team_section.default', function(){
        
        //Add your js code here


    });
});

**Comment by soyket** [comment]
Hello have you guys figured any way to make this work? 
I am trying to load owl caresole preview it works fine on the front end but doesn't show anything in the preview !

**Comment by mohanrc13** [comment]
> @lasida Thank you. Yes an even trigger was the next step. I've also tried iframe contents() and I still was not able to make it work. I'll spend more time on this. The strange things is that somethings already work well, some scripts are only loaded in the original theme and elementor includes them no problem in the preview, others need to have an key up event or be enqueued specifically in the editor.
> 
> @robbisy Maybe that's right, I've only tried Isotope, I'm going to spend some more time on it and I"ll post any findings here. :) Yes, the only way to make it works in some cases to to save and reload, but with isotope, not even saving makes it work. It only works in the frontend.

Yes you are correct... It's not working in preview. I found what is the issue. Isotope library file have that issue. All the other major js libraries working fine. But isotope library not working. I edited library file and make some alert message inside isotope lib file. It's not having stuff to find dynamic elements inside iframe.
