### ISSUE TITLE
Set predefined colour palettes 

### ISSUE THREAD

**Issue by Nigelballa** [pojome/elementor#1290]
Should have the option to set a predefined colour palette so as not to paste specific colors when designing. Global is good for elements already designed but a colour palette that can be chosen would be a good feature.

**Comment by sigersmit** [comment]
I use this plug-in for that. Works site-wide: https://wordpress.org/plugins/kt-tinymce-color-grid/

**Comment by joshmarom** [comment]
Under the panel's hamburger menu, you can find the Color Picker settings, where you can select a palette of 8 colors that will appear under the color picker.
Does that address the issue?

**Comment by Nigelballa** [comment]
Thanks a lot joshmarom. Problem solved

**Comment by eplanetdesign** [comment]
@sigersmit I can't get https://wordpress.org/plugins/kt-tinymce-color-grid/ to work in elementor, any tips?
