### ISSUE TITLE
Media Library button not working on front end

### ISSUE THREAD

**Issue by Stegosource** [pojome/elementor#1295]
## Description

I've created a WordPress widget the traditional page and it shows up fine in the Elementor library, but my Javascript is not loading on the Elementor editing screen even though the widget enqueues it properly.

## Steps to reproduce

Create a simple WordPress widget and in your admin resources enqueue function, wp_enqueue_script() for your JS file. 

## Environment

http://pastebin.com/EUjyZZC9

Im not sure if there is simply a hook I need to work with or what. I feel like it should be easy, but I wasn't able to figure it out. Any help would be much appreciated.

PS. Love the plugin. Looking forward to the developer API and adding some nice functionality to it :)

**Comment by Stegosource** [comment]
Oh man, I just found this page that shows the hooks. I think this is exactly what I was looking for: https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md

**Comment by Stegosource** [comment]
Small update on this. I think this may have brought up a different Elementor bug. If I create my own WordPress media library modal popup, it works fine. The resources load, and using Elementors hooks, my JS file loads.

When I click the image I want to select, it returns the URL value to the correct input field in Elementor, but the page does not trigger an update and I still see the old image even though the input has the new image's URL. And here's the problem: if I click save right away, the new URL is not saved. 

The only way to trigger an update in Elementor is to go to another field (like a text field) and make a small change. Then Elementor updates and the correct image is shown. I can save, and the changes will persist.

Is there a way to trigger an update when the WP media library modal returns the value maybe?

**Comment by KingYes** [comment]
Can you share your widget?

**Comment by Stegosource** [comment]
Hi KingYes. Thanks for the quick response. 

Not sure if it makes sense to share the whole widget code, so Ive stripped out everything but the fields. Also note that I'm working with an actual WordPress widget, and not an Elementor specific widget.

Widget class: http://pastebin.com/D5WtenMC

In the standard WordPress admin Im also enqueuing these scripts with the hook "admin_enqueue_scripts":
    wp_enqueue_script('media-upload');
    wp_enqueue_media();
    wp_enqueue_script('visceral-page-elements-admin'); // My admin scripts

I had to manually enqueue my admin scripts to the hook "elementor/editor/before_enqueue_scripts"

And finally, I have the following JS in my admin JS file: http://pastebin.com/ARMJ8433

Note that I DID find a way to trigger Elementor to update the page but manually triggering an input's change event (line 29)

Now I have two questions. 1) is this the best way to trigger Elementor to update? and 2) Why doesnt Elementor recognize a script handle in "elementor/editor/before_enqueue_scripts" that has already been registered in "admin_enqueue_scripts"? Instead I have to enqueue it with the source as well.

**Comment by KingYes** [comment]
Please try the version on branch `release/1.4.0` and tell me if it's okay for you

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
