### ISSUE TITLE
post carousel request

### ISSUE THREAD

**Issue by robbisy** [pojome/elementor#1299]
Is it possible to have latest post option for image carousel ?
There's a lot of sites which use their latest post in carousel and by now the only way to do that is to constantly change image in the carousel widget

**Comment by joshmarom** [comment]
This feature is in our pipeline, it will be introduced soon.

**Comment by WPDevHQ** [comment]
Awesome @joshmarom 

I had this on my TODO list but its now crossed off :D

**Comment by WPDevHQ** [comment]
Ca we also push for Woo Products too?

**Comment by arielk** [comment]
@WPDevHQ Yes.

**Comment by chalgerro** [comment]
I believe carousel itself is so useful for many other purposes, mainly showcases of Team, Product (both require photo and text) but also testimonials. 
And how about having Clients carousel with their logos rolling aroung and when hovered with mouse they would "flip-over" (new additiona to Elementor) to show a testimonial from this client, **wouldn't that be awesome**? :)
 
I know this may be difficult but I would consider enabling most of the Elementor's widgets to be embeddable inside carousel (same type of widgets of course)

best.

**Comment by stevehardaway** [comment]
What is the current status of this feature? Has it been added and I'm just missing it?

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
