### ISSUE TITLE
[Conflict] WP Image Elevator Free doesn't work in Text Editor widget

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1301]
## Description

There seems to be some incompatibility with [WP Image Elevator Free](https://wordpress.org/plugins/image-elevator/) / [Pro](https://codecanyon.net/item/image-elevator-for-wordpress/4311188?ref=OnePress)

This plugin allows pasting of images directly into Wordpress, a huge timesaver if you happen to post things like screenshots regularly on your site. Though the plugin works fine in a standard post editor, it doesn't work in Elementor's Text Editor widget. I think it's due to the widget being a cut down version of the WP text editor, and external plugins are being prevented from running.

EDIT: I understand the reasoning behind that in order not to clutter up the area, but it would be cool to just allow the actual Ctrl-V paste action.

## Steps to reproduce

1. Install WP Image Elevator Free / Pro
2. Open two tabs (one with an one with a standard WP page editor, and one with Elementor active + Text Editor widget)
3. Copy an image to clipboard
4. Paste into each editor (one will work, the other won't)

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.0.29
	PHP Version: 5.6.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.2
	Site URL: http://drawcard.com.au
	Home URL: http://drawcard.com.au
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%
	Language: en-AU
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Drawcard 2017
	Version: 9.0.0-beta.2
	Author: Roots
	Child Theme: Yes

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

== Active Plugins ==
	Coming Soon Page & Maintenance Mode by SeedProd
		Version: 5.0.7
		Author: SeedProd

	Contact Form 7
		Version: 4.6.1
		Author: Takayuki Miyoshi

	Duplicate Post
		Version: 3.1.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 1.1.2
		Author: Elementor.com

	Flamingo
		Version: 1.5
		Author: Takayuki Miyoshi

	GitHub Updater
		Version: 6.2.2
		Author: Andy Fragen

	OnePress Image Elevator
		Version: 2.5.8
		Author: OnePress

	Pods - Custom Content Types and Fields
		Version: 2.6.8
		Author: Pods Framework Team

	Regenerate Thumbnails
		Version: 2.2.6
		Author: Alex Mills (Viper007Bond)

	Sunshine Photo Cart
		Version: 2.5.11
		Author: Sunshine Photo Cart

	SVG Support
		Version: 2.3.6
		Author: Benbodhi

	Theme Check
		Version: 20160523.1
		Author: Otto42, pross

	The SEO Framework
		Version: 2.8.2
		Author: Sybre Waaijer

	The SEO Framework - Extension Manager
		Version: 1.0.0
		Author: Sybre Waaijer

	Wordfence Security
		Version: 6.3.1
		Author: Wordfence

	WP Sync DB
		Version: 1.5
		Author: Sean Lang

	WP Sync DB Media Files
		Version: 1.1.4b1
		Author: Sean Lang

**Comment by arielk** [comment]
Sorry, but this plugin does not work for me on regular text editor. It seems that the plugin is not updated in the last year, so please check it with the developer of this plugin.
