### ISSUE TITLE
Post Problem

### ISSUE THREAD

**Issue by lobensen** [pojome/elementor#1306]
Hello im just started to use elementor with oceawp theme, i did a normal index, with a preloaded template from elementor and started modificating.. but then when i do a new post, it show after all the index content i made.. and dont find how to remove it for posts sections.. and blog section.. i will share all info i can:

Site
http://www.coffeeshops-nearme.com/
blog:
http://www.coffeeshops-nearme.com/blog/
Post:
http://www.coffeeshops-nearme.com/everything-need-know-dinner-coffee/

System information:

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 5.5.52
	PHP Version: 5.5.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 800M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.2
	Site URL: http://www.coffeeshops-nearme.com
	Home URL: http://www.coffeeshops-nearme.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.1.4
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.2.3
		Author: Elementor.com

	mPress Custom Front Page
		Version: 1.1
		Author: Micah Wood

	Ocean Custom Sidebar
		Version: 1.0.2
		Author: OceanWP

	Ocean Extra
		Version: 1.1.6
		Author: OceanWP

	Ocean Product Sharing
		Version: 1.0.1
		Author: OceanWP

	Post Slider WD
		Version: 1.0.33
		Author: WebDorado

	Ultimate Widgets Light
		Version: 1.5.9.4
		Author: KhoThemes

	W3 Total Cache
		Version: 0.9.5.2
		Author: Frederick Townes

	WP Review
		Version: 4.0.9
		Author: MyThemesShop

	WP Tab Widget
		Version: 1.2.7
		Author: MyThemeShop

	Yoast SEO
		Version: 4.3
		Author: Team Yoast

Thanks

**Comment by drawcard** [comment]
Is the index content you're describing embedded in your PHP template? The Elementor content will render in the designated area <?php the_content()> where ever that's found in your template.

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
