### ISSUE TITLE
Can no longer edit with Elementor

### ISSUE THREAD

**Issue by dax702** [pojome/elementor#1309]
I can no longer edit pages in Elementor.  Seems to have started after the last update, but I can't be sure

This is what I get when I try to edit a page with my theme (OceanWP)
![issue](https://cloud.githubusercontent.com/assets/19275233/23001876/9d1dc6bc-f3a4-11e6-9f99-d486fdaf467c.PNG)

This is what I get when I switch the theme to TwentySixteen:
![new error](https://cloud.githubusercontent.com/assets/19275233/23001877/9d1dcf0e-f3a4-11e6-9f6d-16daa16b82b2.PNG)

I've disabled all plugins except Elementor, Elementor Pro, Simple CSS, and WP Staging.  I also put cloudflare into development mode, cleared local browser cache multiple times. The problem persists.  Discussed on the Elementors facebook group here:

https://www.facebook.com/groups/Elementors/permalink/1066268980165554/
Someone here said that downgrading their PHP from 7 to 5.6 solved the problem. I am also on PHP 7, however, so are a lot of other people who haven't posted this problem so I don't know if that's the cause or not.

I looked at my system info. Memory was set to 40, so I used define( 'WP_MEMORY_LIMIT', '64M' ); to make it 64 as recommended. But that didn't fix the issue

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
