### ISSUE TITLE
Custom Control

### ISSUE THREAD

**Issue by devcdg** [pojome/elementor#1312]
Hi,

This is not an issue but a query and I don't know where exactly to post it.

I am looking to buy Pro but before I buy I wanted to try if I can add my own controls.

I understand and I did add my own widgets but it appears under Wordpress and with their icon on the editor panel. I do not want that.

I would like to add a control, say for eg: Contact Info Block. 
What file hierarchy should I follow? Should I create a elementor/includes/widgets in my wp-content folder ?

All the default controls are in plugins/elementor/includes/widgets . If I add my custom control here, then on update will it be deleted. 

Also, if I have to edit an existing control then do I use an action hook in my functions.php file or do I recreate a control, again what file hierarchy should i follow ?

Thank you very much for any help.

**Comment by arielk** [comment]
Please read our API docs for developers: https://github.com/pojome/elementor/tree/master/docs

**Comment by devcdg** [comment]
Hi,
I have gone through the documentation but no where it shows from start to finish how to create a custom element. Alteast, an example file or blog post would help.
I created a custom widget file but I cannot see it in elementor page builder. What is the file structure should I follow ? Do you have any examples that I could follow? Please help.

Thank You.

**Comment by joshmarom** [comment]
Hi @devcdg, for refference, check out https://github.com/pojome/elementor-hello-world
also, you may want to check out some other Elementor complimentary plugins in the WordPress rpo, for example: https://wordpress.org/plugins/addon-elements-for-elementor-page-builder/ and some others.

**Comment by devcdg** [comment]
Hi,
I installed plugin press elements for reference which helped me understand where to place the files.
Thank You
