### ISSUE TITLE
WP Inline Styles

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#1320]
Is it possible to use `wp_add_inline_style` within a widget module?

Basically I have a widget that has a backdrop overlay (color with opacity). The CSS rule is defined in frontend.min.css as being `.prefix-backdrop{ background-color: #000; }

While using `add_control` in respect of the background color  the CSS generated in to the post-1776.css does not seem to have effect on the target. I can see the rule being output as `.elementor-1776 .elementor-element.elementor-element-ow61bzb .prefix-backdrop` and those selectors before my selector seem to be the blockers.

As a workaround I'm trying to generate the CSS via `wp_add_inline_style` but not getting the output at all.

What I have in my Widget file is something like this:
```
public function show_inline_css( $settings ) {		
	$settings = $this->get_settings();
	$color = $settings['prefix_backdrop_bg'];
	$css = '.prefix-backdrop {background-color: ' . $color . ';}';
	wp_add_inline_style( 'elementor-show', $css );
}	
protected function add_actions() {
	add_action( 'wp_enqueue_scripts', [ $this, 'show_inline_css' ], 10, 2 );
}		
public function __construct( $data = [], $args = null ) {
	parent::__construct( $data, $args );
	$this->add_actions();
}
```
Not sure where I'm goiong wrong.

**Comment by KingYes** [comment]
If you use `selectors` array is not working for you?

**Comment by WPDevHQ** [comment]
This doesn't work no!
`'selectors' => [
     '{{WRAPPER}} .modal-backdrop' => 'background-color: {{VALUE}};',
],`

However, elswhere this works!
`'selectors' => [
					'{{WRAPPER}} .prefix-dialog .prefix-content .prefix-header' => 'background-color: {{VALUE}};',
				],`

**Comment by WPDevHQ** [comment]
Could the fact that the class is being added via js be the issue?

**Comment by joshmarom** [comment]
I am not sure I understand. 
When you inspect the element in the browser inspector, do you see the CSS rule generated by the 'selectors' applied to it?
Does it get overridden? if so, which rule overrides it?

**Comment by WPDevHQ** [comment]
In my stylesheet this `.prefix-backdrop` and applying a background color to it works from within the stylesheet. Also applying a color change via the inspector directly to that rule works fine.

The following selectors are output in the related post stylesheet generated by Elementor
`.elementor-1776 .elementor-element.elementor-element-ow61bzb .prefix-backdrop`

However the generated background color to these in the post-1776.css does nothing - even in the inspector it doesn't change.

The selector is from Bootstrap and is output is via js on a click event if that helps.

I'll probably drop that selector and use another one that does not get effected by selectors before it but would be nice to know a) why the original isn't being picked up for targeting and b) how/what is the best way to override styles with wp_inline_style() function.

**Comment by joshmarom** [comment]
Are you sure the div `.prefix-backdrop` is actually inside of `.elementor-1776 .elementor-element.elementor-element-ow61bzb`?

**Comment by WPDevHQ** [comment]
Not on the page via the inspector but it's generated in the post-1776.css file as that - this output however has no effect on the element when it's triggered.

I've since moved to a different selector which works perfectly fine for my needs.

If you could however advise on the the best way to return an output via wp_inline_style() that would be totaly awesome. If it's something that can not be entertained right now then I understand, so please feel free to close this issue :)

**Comment by joshmarom** [comment]
I suspect the div `.prefix-backdrop` is not actually inside your widget.
Which means you should have not used `{{wrapper}}` in the selectors. like so:
```php
'selectors' => [
     '.prefix-backdrop' => 'background-color: {{VALUE}};',
],```
