### ISSUE TITLE
[BUG] RIGHT ALT + S saves the project. 

### ISSUE THREAD

**Issue by chalgerro** [pojome/elementor#1328]
## Description
RIGHT ALT + S saves the project. 
In many languages, including Polish the RIGHT ALT key is required to enter local characters in this instance Polish letter "Ś". In a typical application the right ALT key is normaly reserved for entering special characters. 
Saving a file or project normally reserves CTRL+S shortcut for this purpose. 
CTRL+S does also work in Elementor so I assume there's no need for another shortcut which also makes entering text more difficult (entering, copying and pasting single chars from the address bar in my case)

## Steps to reproduce
Press RIGHT ALT + S

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.31
	PHP Version: 5.4.36-0+tld0
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.2
	Site URL: http://t.inventi.pl
	Home URL: http://t.inventi.pl
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 1.3.44
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 2.8.0
		Author: Shea Bunge

	Elementor
		Version: 1.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 1.1.2
		Author: Elementor.com

	Portfolio
		Version: 2.2.9
		Author: Huge IT

**Comment by arielk** [comment]
Fixed for the next version. Thank for your report!
