### ISSUE TITLE
Themes Section/Showcase

### ISSUE THREAD

**Issue by Nirvsoner** [pojome/elementor#1330]
Hi team,

We would like to have a section in your site where you showcase themes that are compatible/built with Elementor for sale on different marketplaces, of course, the idea is to be selective and pick only high quality items, I think this could help us both.

Cheers,
Joel.

**Comment by arielk** [comment]
You can find many themes that work with Elementor properly, please read this article: https://docs.elementor.com/article/78-themes

I hope we can publish more and more compatible themes in the future :)

Thanks for your feedback!
