### ISSUE TITLE
FOUC Shortcode embed template

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1332]
Hi guys, you also have the so-called problem of FOUC when using the shortcode to show the portions of the template with Elementor? This is not very good as it

![fouc_elementor](https://cloud.githubusercontent.com/assets/7602983/23215552/22f4d4b0-f913-11e6-8f86-da49b0a4716e.gif)

**Comment by arielk** [comment]
For now you can add the CSS file in the header by this action in your `functions.php` (change the page_id of the template):
`add_action( 'wp_enqueue_scripts', function() {
	if ( ! class_exists( '\Elementor\Post_CSS_File' ) ) {
		return;
	}

	$header_page_id = 4567;

	$css_file = new \Elementor\Post_CSS_File( $header_page_id );
	$css_file->enqueue();
}, 500 );`

**Comment by sododesign** [comment]
Do you plan to solve this little problem in future versions?

**Comment by KingYes** [comment]
This is not bug. We can't print your CSS in `<head>` if we called this from your `<header>`.. So if you want to print CSS use what @arielk write..

**Comment by andrewmaney** [comment]
What about more than 1 embedded element...do we repeat this function for every element?
