### ISSUE TITLE
[issue] element-ID as anchor has no smooth scroll

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1333]
following up the issue described in [#925](https://github.com/pojome/elementor/issues/925) (closed and referended to #939) i tried to use a custom CSS-ID for sections as an anchor to prevent the '1px space experience'.

as it works well as an anchor, theres no smooth scroll as when using the dedicated anchor-widget.
maybe i've overlooked something - but without the smooth scroll the replacement is not really pleasing the eye ...

really an issue - or any hint how to get over it?

**Comment by arielk** [comment]
Please try to add `.elementor-menu-anchor` class to the CSS classes field of the section and let me know if it works for you.

**Comment by dasigna** [comment]
thanks - but unfortunately this doesnt make any change :-/

**Comment by arielk** [comment]
Can you please share with us the link to the page?

**Comment by dasigna** [comment]
[here you go](tectra.design/grafikdesign)

**Comment by arielk** [comment]
Sorry but I don't see any section with these selectors in the page.

Please add your CSS ID (e.g. `#graf02`) and CSS Classes as I wrote `.elementor-menu-anchor` to the section instead of the Menu Anchor widget

**Comment by dasigna** [comment]
ahhhh - sorry. switched back after it did not work... now you maight take a look again (but does not work eighter...)

thanks.

**Comment by arielk** [comment]
Hoops, your right. I checked it in my dev environment. We'll check it asap.

**Comment by arielk** [comment]
Fix https://github.com/pojome/elementor/commit/2552cc11215cb9ffa2ee4c044e88bf6fc8f7b431
