### ISSUE TITLE
Improve Posts Widget by adding box shadow and border options

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1335]
Give pictures a box shadow option.

Make a border not only around the complete widget, but also around the individual posts; including box-shadow options.

**Comment by aky01** [comment]
any update to this particular request? Specifically drop shadow can only be turned on or off and not actually styled therefore does not match anything else with a drop shadow specific styling on the page.

**Comment by arielk** [comment]
This tweak has been added to E-Pro v2.1.0

Thanks for your feedback!
