### ISSUE TITLE
Create a new feature: Single blog post

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1343]
Absolutly necessary – soon. I’m working on a site which should have around 5.000 posts, another in planning around 20.000 posts. Since BB released something that could be interesting for me (and many other webdesigners) to, meet that problem, you under pressure to release that feature soon. I’ve communicated that issue already some month ago.

**Comment by joshmarom** [comment]
We have some plans for this kind of functionality, it is on our roadmap, but I'm afraid it might take a little while before we release this as a feature.

**Comment by HelmutGoebel** [comment]
Can you give an idea, if it will be a month or two, or rather half a year or longer?
As of January, you are ahead of competition. Once "Beaver Themer" is released in Beta, that might change. So you got to speed up, but please not by lacking quality.

**Comment by arielk** [comment]
I merged this issue with another issue #543 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
