### ISSUE TITLE
Background Section not change, if column move, Background Stuck

### ISSUE THREAD

**Issue by lasida** [pojome/elementor#1346]
i was setup background in section, but if i move the columns, the background stuck in position, not following the column, or section move.

**Comment by joshmarom** [comment]
## Steps to reproduce

**Comment by lasida** [comment]
1.I create a new section
2.I click Section -> Style -> Background Type
3.I choose Classic
4.I set the background with image
5.I click tab Layout, and change Height -> Fit to screen
6.I Drag Column to another position
7.and I found background not following column, but stuck as background, can't edit,can't remove

that's the step ?

**Comment by joshmarom** [comment]
Thank you for reporting this bug.
We will fix it soon.
In the meantime, please avoid leaving sections empty without columns.
