### ISSUE TITLE
hiding segment in toggle on mobile device while showing same segment without toggle on desktop

### ISSUE THREAD

**Issue by nicolasblume** [pojome/elementor#1353]
**hiding a segment, column or picture etc. in a toggle on a mobile device, while showing the same segment, column or picture without a toggle on a desktop or tablet**

That would be really helpful, if you still need access to all content that the Desktop view provides, but dont want to scroll that much on your phone. 

(Sorry if I use the wrong words, I use the german version)

**Comment by arielk** [comment]
I hope that I understand. If you click the "Preview" button you should not see elements that are hidden by device.
See the screenshot: http://i.imgur.com/KiVX3hs.png

**Comment by nicolasblume** [comment]
You could do the same if you would have 2 independant sections for the same content: One only visible for phones, inside a toggle and one only for tablets and desktops that is not in a toggle. 

But my team does not want to deal with 2 identical texts that they have to edit. 

So my idea was to add a new function to do this with a single section or text: In the responsive settings there would be the option "hide inside toggle" that could be activated for phones, tablets or desktops.

**Comment by arielk** [comment]
I'm afraid I did not understand you so well, if you can explain better with this screenshot it will greatly help.

**Comment by nicolasblume** [comment]
Do you mean I should choose a screenshot where I edit it so it looks like I want it to be?

Your said "this screenshot", did you forgot to attach a specific screenshot?

**Comment by arielk** [comment]
My mistake :( I'm just trying to figure out exactly what you mean, so if you have a screenshot it will greatly help.

**Comment by nicolasblume** [comment]
I would like to achive the following 2 looks with a single segment where I could choose, that the segment is hidden inside a seperator only on mobile devices.
When I want to change the text, I have to do it only once and it is more organized.

So this is a feature request, I do know that it is not possible yet 😄 

![responsive seperator](https://cloud.githubusercontent.com/assets/14913584/25243335/f496a938-25fc-11e7-833c-4be035b2c9a2.png)

**Comment by arielk** [comment]
It's very interesting!

I think it's very similar to something else they asked us to, please check the following issue #880 
Feel free to continue the discussion here, if it's not like what you're asking for.

Thanks for your feedback!

**Comment by nicolasblume** [comment]
Unfortunately that is not what I am asking. I hoped that the screenshot and my explanation were clear enough 😄 I would just like to see the toggle widget as it is now already integrated as an responsive option for a standard segment. But maybe I am the only one in the world who would like this 😆

**Comment by arielk** [comment]
To be honest, this is a very unique request, but you know, may be in the future we will add it.
Thank you very much for the idea and the feedback.
