### ISSUE TITLE
screensize specific values for column arrangements

### ISSUE THREAD

**Issue by nicolasblume** [pojome/elementor#1355]
**setting values for the arrangement of columns and their order individually for the 3 screensizes**

For example: On desktops the arrangement of 2 columns is 33%-66%, but I want that to be 50%-50% on tablets.

Another possible feature:
If there are 3 or more columns, the option to reverse the order on mobile devices is not enough. We need to be able to choose the order individually for the 3 screensizes. For example: On a desktop the order is 1-2-3-4, but on a mobilde device I want it to be 3-1-2-4.

(sorry if I use the wrong words, I use the german version)

**Comment by arielk** [comment]
We try to keep the logic and simplicity all the possibilities, so we added a "responsive control" for mobile columns.

Maybe we will add control for tablet columns in the future, you can follow this issue: https://github.com/pojome/elementor/issues/418
