### ISSUE TITLE
screensize specific characters, words or segments in Texts/HTML Code

### ISSUE THREAD

**Issue by nicolasblume** [pojome/elementor#1356]
**swapping out specific characters, words or segments in Texts or HTML Code for the 3 screensizes**

For example the text says: "look at the calendar on the left", but in mobile view it should be "look at the following calendar".

Another example: I need the height of a calendar, that is defined in the Html code, to be different for every screensize. So the value for height in the code must be different for every screensize option.

(sorry if I use the wrong words, I use the german version)

**Comment by arielk** [comment]
Unfortunately I do not see the option to add this feature, but please show/hide elements by device. You can do this by using the tab in every element > Advanced > Responsive
