### ISSUE TITLE
inconvenient display of progress bars on small screens

### ISSUE THREAD

**Issue by nicolasblume** [pojome/elementor#1358]
As you can see in the picture, the "1%" is cut off to "1" in the progress bar on small screens.
On mobile devices, an option to move the "1%" to the right and out of the bar (and changing it's colour to green) would  be great.

Another solution would be to make the whole widget narrower and put the numbers in percent to the left of each bar (in green colour)

The easiest solution would probably be to move the numbers a bit to the left, although that could look weird. Then it would be helpful to control the length of the bars independently from the displayed value

![skizze](https://cloud.githubusercontent.com/assets/14913584/23305873/190d7ef4-faa1-11e6-8da2-3dfe7cdd1ec3.png)

**Comment by arielk** [comment]
Fix https://github.com/arielk/elementor/commit/c766d9e4e8149ab51f514809e9d51e06e971660b
Thanks for your feedback!
