### ISSUE TITLE
MutationObserver request in elementor 

### ISSUE THREAD

**Issue by robbisy** [pojome/elementor#1361]
Is there a chance for having a  function like mutationobserver in elementor.
I mean I've created an owlcarousel widget but when I add a new widget in the preview 
the js load with before_enqueue_scripts doesn't seem to see it . I had to save an reload the preview page to see the difference.
The solution may be a function which look after each change in the preview

**Comment by KingYes** [comment]
If you write custom widget, you can use our Handlers to run jQuery code. Like this: https://github.com/pojome/elementor/blob/master/assets/dev/js/frontend/handlers/alert.js

And register like this:
https://github.com/pojome/elementor/blob/master/assets/dev/js/frontend/elements-handler.js#L30

**Comment by robbisy** [comment]
@KingYes 
With this method I had to make modifications on elementor plugin and on every update I had to make the modification again. Is there a way to make the modification from the theme itself ?

**Comment by KingYes** [comment]
Each widget has own handler. But please read our Developer API how to write widgets to Elementor..
