### ISSUE TITLE
[issue] editor panel not showing up

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1362]
strange error since today...
the editor panel is not showing up when trying to edit site - i only get this:

![elementor-error-2017-02-25-02](https://cloud.githubusercontent.com/assets/22448174/23333062/2f230de6-fb85-11e6-8447-4a92f204a414.PNG)

searching in inspector found the marked line and unchecked it - panel is there.

![elementor-error-2017-02-25](https://cloud.githubusercontent.com/assets/22448174/23333078/83360e2e-fb85-11e6-9507-bd3dbbf1ba6a.PNG)

no clue whats causing this!
latest elementor and wp versions, already tried deactivating plugings as well as reinstalling elementor - no change.

**Comment by arielk** [comment]
Did you try to replace a theme?

**Comment by dasigna** [comment]
unfortunately i am not able to do so at the moment due to activities on the live page.
but i doubt it will change something. had no trouble with generatepress and elementor so far...

**Comment by dasigna** [comment]
... tried it meanwhile - switched to twentysixteen and no change / same error.

really could cry. its the only page with wp4.7.2/elementor/generatepress that shows this behaviour. and completely no clue why its the only one where the 'position: relative'/the 'ui-resizable' class is called ...

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
