### ISSUE TITLE
Hide section by condition

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1363]
Hide a section (column/widget) by condition. Those conditions can be: role (visitor/subscriber/author etc.), meta data (author/category/tag/date) of this post, value of a taxonomy or custom field of this post, number of posts available for specific meta data, number of posts availbale for specific value of taxonomy or custom field. The value to compare, should not only be the a list to choose from, but also the value of the current post, in order to make it "global".
This feature makes is possible to create very dynamic content.

**Comment by arielk** [comment]
I'm not sure what did you mean exactly. Is it related to this issue #536 ?

**Comment by HelmutGoebel** [comment]
No. This is going towards a single post widget, although it's a different issue. I'm working on a project, which will have 5.000 or more posts, another project I have in planning will have at least 25.000 posts. Currently I'm editing every single post in Elementor. That will not work on the long-run. I need, and certainly many webdesigners too, a chance to design a template (in Elementor)  and every post will look, like it is designed individually. In order to achieve that, I have to use taxonomies and custom fields, where the post-specific data is stored. In same cases, the content of a taxonomy or a custom field decides, wether a section (column/widget) is needed and should be displayed or not. Also, when you not think about high number of posts, this feature makes webdesign very flexible.

**Comment by arielk** [comment]
I merged this issue with another issue #543 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by HelmutGoebel** [comment]
I don't think, this is the same issue as #543 . Independent from creating a "post template", a section (maybe also a column and a widget) should be switched of from displaying by setting a condition, like a taxonomy or a custom field has a certain content; or for a certain role, like explained above. This can not only be used in "post template" (which some 3rd party dev's are also so "kind of" covering) but on normal website, where (as an example) a looked-in user get more information, or an author/editor gets adice, how to edit. Just dev it. It shouldn't be so difficult (;-). The community will give you a lot of positiv feedback for that.

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.19.0! 🥳 

You can now use Display Conditions for widgets based on User Role and a lot of other conditions (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
