### ISSUE TITLE
Respect SCRIPT_DEBUG constant when loading the `color-picker.min.js`

### ISSUE THREAD

**Issue by Nikschavan** [pojome/elementor#1364]
The plugin loads the minified version[ of color-picker](https://github.com/pojome/elementor/blob/master/includes/controls/color.php#L25) despite the SCRIPT_DEBUG constant is defined in `wp-config.php`

This is more of a problem when using trunk version of WordPress where the minified file is not present.

**Comment by KingYes** [comment]
Thanks :)
