### ISSUE TITLE
Improve Posts widget: Add display of taxonomy and custom fields

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1367]
In the posts widget you can display besides the image and the excerpt, the meta data. Please expand that to the taxonomie and the custom fields. That would make the posts widget much more usefull.

**Comment by joshmarom** [comment]
If you mean the same as #1071, please close this issue and add your ideas in the existing one; otherwise, please explain what you mean.

**Comment by nicolamanes** [comment]
With Posts Widget (PRO) can you show posts with specific ACF value? if not do you know  any widget that can do this?
