### ISSUE TITLE
Trello Public Roadmap and Ideas

### ISSUE THREAD

**Issue by luizeof** [pojome/elementor#137]
Hi Folks,

Any chance of having a public Trello board with the Roadmap and a voting system of future features? I believe there are several collaborators and have a vision of what needs to be done help collaboration and also testing.

**Comment by yehudah** [comment]
Great idea !

We hope to publish it very soon.

Thanks.

**Comment by bmwillrath** [comment]
Where are we at with this? Almost 1 year later, really keen to see what awesome features you've got lied up for Elementor & Elementor Pro. Might also be a good way for people to vote on ideas that are important to them?

**Comment by luizeof** [comment]
can you reopen this? @yehudah @arielk
