### ISSUE TITLE
Ken Burns slider effect 

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#1370]
The Ken Burns effect introduce in the last update has a smooth slide effect on Chrome. However, on Microsoft Edge, it jitters rather than running smoothly.

I created a three slide slider with image backgrounds and applied the Ken Burns effect to all three slides. This was created on a test website on my Localhost. Wampserver 64 - Windows 10.

This was also reported by another user.

**Comment by Luxamman** [comment]
Also a problem with the ken burns effects: the picture zooms in and just before it switches to the next picture, the picture jumps back to the first zoom position.

**Comment by nickdgreen** [comment]
It doesn't matter whether you set the Ken Burns Effect to zoom "in" or "out" it only zooms out.

**Comment by joshmarom** [comment]
I can't see a problem. Seems to be working just fine.

**Comment by slomeli79** [comment]
Same here. Any slide set to Ken Burns effect (whether zoom in or out), when viewed on MS IE or MS Edge, is jittery and shaky during the scaling.

**Comment by nickdgreen** [comment]
@joshmarom the Zoom in / zoom out setting also seems to have no effect it always zooms out. Se this page http://wpdemo.websitesdesigned4u.com/templates/test_page/ column one is set to zoom in and column 2 is set to zoom out - they both zoom out.

**Comment by JustDevelop** [comment]
It is so unprofessional that the bug @Luxamman mentioned still isn't fixed yet...

**Comment by ludertal** [comment]
> Also a problem with the ken burns effects: the picture zooms in and just before it switches to the next picture, the picture jumps back to the first zoom position.

still the same problem since 2 years with the very last updates

**Comment by hellopas** [comment]
Three years later and no one has addressed this issue yet. Could someone please figure out why this is happening? @joshmarom

**Comment by itsViney** [comment]
I'm seeing this issue too, three years since it was reported. The zoom directions seems to reverse when the transition to the next image starts.

**Comment by KevTheHuman** [comment]
I hope potential buyers see this post before they buy.
I hope people would copy and paste common issues of elementor on videos that promote the product.

**Comment by fabienlege** [comment]
More than 4 year, to do nothing...
And this is far from being the first bug reported for several years that I encounter 
Good job Elementor !

**Comment by ludertal** [comment]
> More than 4 year, to do nothing... And this is far from being the first bug reported for several years that I encounter Good job Elementor !

2 years ago I said the same as you, I bought another plugin in the meanwhile... that's a shame...

**Comment by Ulysses888** [comment]
Yes, I'm seeing this issue on Chrome and Firefox. Elementor obviously not interested in fixing it ...

**Comment by ashanthilochana** [comment]
More than 7 years. This bug is still there.

**Comment by projectpi-ca** [comment]
Running Elementor 3.27.6  and Elementort Pro 3.27.4. It is definitely not fixed.
