### ISSUE TITLE
Display breaks, when saving widget as global widget

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1372]
Update to version (PRO) 1.2.2 supposed to fix that. But it doesn't completely. The problem doesn't appear, when you save a widget, but after saving the edits and reload the (backend-) page the display breaks.
![global widget 1 2 2](https://cloud.githubusercontent.com/assets/14095280/23359262/c1cfea86-fce5-11e6-83a5-f7a4301ab15e.JPG)

**Comment by arielk** [comment]
@HelmutGoebel Can you explain all the steps needed to reproduce your issue, so we can replicate it ourselves?

**Comment by HelmutGoebel** [comment]
I create a section with 1 column and put in a previously defiend global widget (a text widget). Looks fine. I save the template. And then I reload the page. Than it breaks and continue to be broken.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by HelmutGoebel** [comment]
I haven't seen this bug I think since 1.2.3. So looks like the problem is solved.
