### ISSUE TITLE
Idea: Edit multiple elements at once / bulk edit elements

### ISSUE THREAD

**Issue by ehausen** [pojome/elementor#1374]
Elementor as the other leading visual builders seem to be lacking in this particular feature:
How to quickly edit multiple elements (if not using css of course).

Lets's say I want to set the background color for three columns at once instead of clicking on each one individually. This goes for almost any other setting also.

So I'm suggesting a feature:
* Be able to select multiple elements at once
* Be able to control at least some of the settings at once

**Comment by HelmutGoebel** [comment]
The answer to that is "single post widget". And I hope with you, they are coming up with this soon.

**Comment by arielk** [comment]
I merged this issue with another issue #879 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
