### ISSUE TITLE
Pages and Sections Templates

### ISSUE THREAD

**Issue by edirpedro** [pojome/elementor#138]
Could be available on the same list of widgets, but separated with the titles "Page templates" and "Section templates".

Page Templates would be a pre-built page, with sections and widgets pre-configured and styled.

Sections Templates would be small parts of that page with widgets pre-configured and styled.

Imagine your elementor.com website with each of that sections pre-built to just drag & drop and change text and images. For non designers this would be a wonderful help. I would like to provide a set of built in designs and let the user customize entirely if they really want.

For both Pages and Sections Templates, we could elaborate using the editor and save the content into a JSON file inside the theme folder. This will be loaded by the Elementor to list on the Page or Section Templates available from my theme. Advanced Custom Fields does that for example, there I can create forms and save them inside the theme folder as a JSON files to let ACF open it and use, I can edit my forms on my local version and the plugin updates the content on the JSON files, when I deploy the updates, the new setup inside these JSON are available instantly.

**Comment by edirpedro** [comment]
Thinking a little bit more, Sections Templates is more useful than and entire Page Templates. And a Page Template could be done simply building a page and offer as a demo to import into WordPress, than the user could duplicate this demo page to use it.

The Section Templates could be offered inside the Add New Section button. On this screen could be listed the saved templates, would be "Structures | Templates". (The same Templates could build a section or more than one section, building a page)

![captura de tela 2016-06-25 as 11 54 01](https://cloud.githubusercontent.com/assets/831507/16357381/9bd7260a-3acb-11e6-8eb0-804af40282a2.png)

Maybe saving automatically as JSON could create a problem, users could replace my theme templates if this tool is available to them and not for developers only. So Exporting a section as a template and put this file into the theme folder `/elementor` would be better. Than these saved sections 
could be listed into the Add New Section button. The icons could be localized into `/elementor/img` with the same file name as the exported file.

**Comment by yehudah** [comment]
Hi,
Thanks for you feedback.

You really submitted some great ideas and all of them will be considered.

Thanks again for your time and help.

**Comment by pingram3541** [comment]
Great idea.  I added to this on this thread as they are very similar https://github.com/pojome/elementor/issues/221

Taking this a bit further into the realm of re-usable but also dynamic sections which can be done using cpt for storing the data.  The sections can be set as dynamic and given a descriptive name.  When these dynamic sections are modified it applies everywhere that dynamic section appears and of course provides a nice notice explaining so.  Section can also be duplicated and converted back to a static section, edited and refined further and then saved as a new dynamic section if desired.  Grouping of these dynamic sections could be the path towards full page templates.  I'd love the growth I'm seeing in this plugin and want to help in any way on this.

**Comment by arielk** [comment]
Finally template library has been released, please update!

Link to post release: https://elementor.com/introducing-template-library/
