### ISSUE TITLE
Pagination doesn't work on custom post types

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1380]
Pagination works fine on pages. I don't know about posts; it definatly doesn't work on custom post types. When you click on "next page", the page reloads but sticks on page 1. The php-error, we had previously, disappeared.

**Comment by arielk** [comment]
Please update the plugin to the last version v1.2.3 and let me know if this issue has been resolved.

**Comment by HelmutGoebel** [comment]
I've been updating to 1.2.5 and bug is still there.

**Comment by arielk** [comment]
Does WooCommerce products work for you? Can you share with us a link to the page with the problem?

**Comment by arielk** [comment]
Does WooCommerce products work for you? Can you please share with us a link to the page with the problem?

**Comment by HelmutGoebel** [comment]
I don't use Woocommerce. I'll sent the link to the support-Email-Adress.

**Comment by KingYes** [comment]
It's bug from WP: https://core.trac.wordpress.org/ticket/15551

**Comment by hitty** [comment]
@HelmutGoebel  I have the same problem. Did you manage to overcome it?
