### ISSUE TITLE
Responsive Settings in Posts Widget

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1381]
There are plenty of responsive settings in the posts widget. One I'm missing: The numbers of posts on 1 page. My normal setting (on desktop) is 3 and 3 in a row; so that means 1 row on one page. On Tablet, I want to have 2 in a row, but the 3 in total on a page remains. The result is: 2 posts in the first row, only 1 in the second row, although there are more posts to be displayed. So it is better, to distinguish the number of posts on one page by device.

**Comment by joshmarom** [comment]
Hi @HelmutGoebel.

You need to understand the difference between the Columns setting and the Posts count setting.
The first is a style setting, but the second is a content setting. 
Elementor can change the CSS for each breakpoint, but it doesn't change the content.

**Comment by HelmutGoebel** [comment]
But this does not eliminate the problem. Maybe the content setting should not be the number of posts, but the number of lines to be displayed, maybe we should be able to choose between those 2 settings.

**Comment by arielk** [comment]
The number of columns option is appropriate for most of our users, so at this moment, we are not planning to add such an option.

Thanks for the feedback!
