### ISSUE TITLE
Error in Post Widget with posts without featured image

### ISSUE THREAD

**Issue by josecristobal** [pojome/elementor#1382]
When the post does not have a featured image, a square appears in the place of the image. This error appears in Chrome, but not in Firefox.

![image](https://cloud.githubusercontent.com/assets/856497/23385109/30b45352-fd4e-11e6-91ce-22717cfa158d.png)

**Comment by KingYes** [comment]
Thanks,
We fix this and will release in EPro `1.3.2`
