### ISSUE TITLE
Link-URL in a Button

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1383]
I'm an affiliate marketer and use elementor to design the product pages. That does include the link-button to Amazon and other marketplaces. Currently I have to manually get the link from Amazon PartnerNet. It should be possible to calculate the URL by putting together a couple of strings and a custom field with the ASIN should be part of that.

**Comment by arielk** [comment]
Unfortunately I don't see any option to add this feature at this point of time.
I suppose that you can add this URL by external plugins or shortcode.

Thanks for your feedback!
