### ISSUE TITLE
Create a new Feature Parallax Scroll Effect and Blur Mouse Hover

### ISSUE THREAD

**Issue by Putzzz** [pojome/elementor#1385]
Hello,

Just purchased elementor pro because it's really great, I regret not to found this plugin a long while ago before I decided to purchase slider revolution.

Don't get me wrong, slider revolution is good, but the problem is, they sometime make the page load slower, and not to mention, its responsive is not good and not fit perfectly unlike elementor.

I know both are different category plugin, and perhaps not fair to compare it.
But what I want to say is...
The things that I like from elementor is its versatility, speed and responsive <-- this is really important.
While the feature that I like from slider revolution is its effect, like parallax scroll effect, blur mouse hover and film strip.

So perhaps it would be great to add these as additional effect feature, I know we can build a parallax effect too on elementor, but it is not exactly like I wanted like in slider revolution.

The latest ken burn effect is also a great addition and warm welcomed, I cannot say any better word how much I love it. But if it also could apply on a page and not a just slider, maybe it would looks great.

Design is crucial on these days, so having a nice and beautifully website is a must.
I think that is why you guys create elementor, to create, easy, nice and beautifuly website as fast and easy as we can.

I don't know whether this request would like to consider by elementor's team, just saying because I love elementor and I'd like to see it growing better and bigger everytime.

**Comment by arielk** [comment]
Thanks for your feedback!

This feature has already been asked in the past so I merged this issue with another issue #72 in the same subject so that we could deal with it more efficiently.

So please let's continue the conversation there.
