### ISSUE TITLE
Anchor Element position offset [request]

### ISSUE THREAD

**Issue by Nirvsoner** [pojome/elementor#1389]
Hi, can you add a control in Anchor Element for push/pull the anchor position? because sometimes we have a fixed header, then we want to deduct the header height to the smooth scroll

Actually I do this manual via css, example:

`#anchor {
	position: absolute;
	top: -30px; 
}`

Cheers,
Joel

**Comment by KingYes** [comment]
Try this:

```
jQuery( function( $ ) {
	// Add space for Elementor Menu Anchor link
	if ( undefined !== window.elementorFrontend ) {
		elementorFrontend.hooks.addFilter( 'frontend/handlers/menu_anchor/scroll_top_distance', function( scrollTop ) {
			return scrollTop - 30;
		} );
	}
} );
```

**Comment by Nirvsoner** [comment]
Yeah, thats perfect, thank you so much

**Comment by KingYes** [comment]
I'm updating my code to compatibility with late version of Elementor (1.5.0)

**Comment by carlosnpz** [comment]
Any chance it becomes a native feature?

**Comment by JacquesGoudreau3000** [comment]
A strange thing happens on my side.  The script in function.php works but when I logout, it doesn't have any effect anymore. Strange...  Any ideas?

**Comment by zeinnicholas** [comment]
@KingYes Someone raised the question about this issue at the FB group today.

How taxing to the performance could it be to make the hook provided look for an attribute in the anchor widget tag to apply the offset dynamically. Then all a user would need to do is to set an offset height within the anchor widget, and the script would do the calculations by itself looking for the value of that attribute. Something like:

1. You add your Anchor Menu widget.
2. You set an offset with a slider control (with options to choose units). 
3. The control value is rendered as an attribute of data-offset="value" in html.
4. The script looks for the value of that attribute before scrolling, and adds the offset on the fly.

This would really improve the usability of the widget, other than only being useful to drag it around. 

I know that the CSS approach (https://docs.elementor.com/article/62-menu-anchor) is less taxing and easy to implement. But how much is the difference between the two?

**Comment by erikeliasson** [comment]
Would it be possible to increase the anchor offset for the TOC widget. We have a sticky top menu, which will overlap the target anchor.

**Comment by quangthien27** [comment]
If you have custom coded id and `frontend/handlers/menu_anchor/scroll_top_distance` hook doesn't work for you, just add `elementor-menu-anchor` to the section's class, and/or add `.elementor-section.elementor-sticky--active` to the header's class, Elementor will add the

**Comment by andrewvink** [comment]
If anyone comes back here - updated script, that can be added to Elementor > Custom Code > </body> - End

`<script>
	jQuery(function( $ ) {
		// Add space for Elementor Menu Anchor link
		if ( window.elementorFrontend ) {
			elementorFrontend.hooks.addFilter( 'frontend/handlers/menu_anchor/scroll_top_distance', function( scrollTop ) {
				return scrollTop - 90;
			} );
		}
	});
</script>`
