### ISSUE TITLE
Configurations saved as JSON for Theme builders

### ISSUE THREAD

**Issue by edirpedro** [pojome/elementor#139]
I could configure the Elementor with my default options for Color Palette, Grid and others including all Widgets setups too, every element available on the elementor panel, they could be saved as a JSON file inside my Theme. If Elementor founds this/these files on the theme, it loads the content and use as defaults options for my theme. This option would be useful to make all the elements offered by the Elementor, perfectly combine with the styles of my Theme. Instead I let the user set the style of a widget to combine with the theme, i could pre-set this to them.

Advanced Custom Fields does that for example, there I can create forms and save them inside the theme folder as a JSON files to let ACF open it and use, I can edit my forms on my local version and the plugin updates the content on the JSON files, when I deploy the updates, the new setup inside these JSON are available instantly.

**Comment by KingYes** [comment]
Hey @edirpedro,

This config file we don't have, but you can write your custom code to write this in your theme. Just see how we save this values and put this by yourself.
