### ISSUE TITLE
Elementor stopped Working When Cloudflare Attached.

### ISSUE THREAD

**Issue by shariffrb** [pojome/elementor#1390]
I no longer able to edit my website, as elementor is not working, after shifting to cloudflare to use Flexible SSL.

My website : http://www.cctvdubaihq.com

Required your earliest response.
 Thanks and regard
Imran

**Comment by arielk** [comment]
Your site doesn't load at all, I do not think there is a connection Elementor.

Feel free to reopen the issue when your site is back online.
