### ISSUE TITLE
Conflict field reCaptcha whith Formidable Pro

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1393]
I wanted to point out that there is a bug in conflict with Elementor for reCaptcha.

When both plugins are active, the Formidable form does not show the recaptha field on the form.

Disabling Elementor, the reCaptcha form back to work correctly.

**Comment by sododesign** [comment]
I opened the discussion toward them. I find it right that you were aware of the problem

**Comment by sododesign** [comment]
I opened the discussion in Formidable PRO support:

https://formidableforms.com/help-desk/conflict-field-recaptcha-whit-elementor/

I find it right that you were aware of the problem

**Comment by arielk** [comment]
Fixed for E-Pro v1.2.3

Thanks
