### ISSUE TITLE
Hook to filter font icons

### ISSUE THREAD

**Issue by edirpedro** [pojome/elementor#140]
The control Icon does not allow me to change the set of icons available, its use font Awesome but my theme works with the Material Design Icons set. A simple hook to let me filter this list would be enough.

**Comment by yehudah** [comment]
Hi,
Thanks for you feedback.
We will consider it in future releases.

**Comment by edirpedro** [comment]
I was thinking about filters that enables me to manipulate any widget field I want, to let me change some idea of a default widget instead of creating another one to replace it just because a single field. I know it's not possible to edit many things because of the template of the widget, but I could change default values and choice lists for example. Some ideas above:

```
// Default icon control found on controls-manager.php:get_controls_data()
add_filter("elementor/controls/data/type=icon", ...); 

// Manipulating any element field
add_filter("elementor/controls/type=icon", ...); // Any field using icon control
add_filter("elementor/controls/name=social_icon_list", ...); // Single field, a complete repeater field
add_filter("elementor/controls/name=social", ...); // Single field, part of the repeater field
```

**Comment by luizbills** [comment]
Because of this that I suggested a icon font manager #110

**Comment by yehudah** [comment]
we are referring this issue to #110

**Comment by merianos** [comment]
@edirpedro may this post can help you: https://merianos.wordpress.com/2017/09/22/elementor-register-custom-font-family-in-the-fonts-control/
