### ISSUE TITLE
CSS files loads at the bottom of the page when using Elementor Library Widget

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1404]
When you insert the Elementor Library Widget in a sidebar, the css of that template loads at the bottom of the page and it stays unstyled until  the whole page loads. The same happens with the google fonts link tag. This is a big issue.

**Comment by arielk** [comment]
Unfortunately for now we have no other option to load the style of embedded element in the page. I hop that in the future we will find a better way to deal with it.

Thank you very much for your feedback!
