### ISSUE TITLE
Combine all css files into one.

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1405]
To minimize the number of requests that a page has, especially if you use multiple elementor shortcodes, it would be nice to have an option to combine all css.

**Comment by kekkster** [comment]
I agree, that would be great!

**Comment by joshmarom** [comment]
Can you explain what's the scenario you are referring to?

**Comment by dudaster** [comment]
I have an website and I use elementor to create multiple ads. Each ad is a template so I can manage it quicker. The ads are in different places so I cannot create them as one, so I insert them with the shortcode, for each ad( inserted template) it creates a css file (wrongfully calling it at the end of the page, but that's another disscusion) and there are multiple css calls instead of just one.

I'll prefer 1mb css file rather then 10 files each 10kb (which is 10 times less).

I also have an website that constructs  itself from different elementor templates depending of the custom fields and other criteria and it can get up to 10 different css at once.

Nowadays the server can serve pages with GB/s of data but the number of server requests is a killer, so there's no brainer that is a nice feature to have.

**Comment by kekkster** [comment]
For me it´s mainly to reduce the overall number of requests to increase performance.
On my main site it´s 4 js-files and 6 css files just from Elementor (basic and pro).

**Comment by ehausen** [comment]
I don't think this the job for Elementor there are several Worpress plugins that specialize in combining, minifying, caching.  Elementor should stick to its core competency: Page editing

**Comment by dudaster** [comment]
Have you test them with Elementor pro? Are they working? Please give me some working plugins that does this. 

Thanks.

Currently I'm using litespeed cache which is the best but it doesn't minify or combine the css scripts all together.

**Comment by arielk** [comment]
You can do it by other plugins like: [Autoptimize](https://wordpress.org/plugins/autoptimize/) or WP Rocket

If you are using with Autopimize don't forget to add this code to your functions.php file, for fully compatible with Elementor or another page builder:
```add_filter('autoptimize_filter_noptimize','pagebuilder_noptimize',10,0);
function pagebuilder_noptimize() {
  if (is_user_logged_in()) {
    return true;
  } else {
    return false;
  }
}```

**Comment by joffreycarle** [comment]
Hi everyone!
@arielk you can simplify your code with:
```php
function pagebuilder_noptimize() {
    return is_user_logged_in();
}
```
