### ISSUE TITLE
Menu Navigation element

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1406]
You said that you are working at an menu element. When do you think it would be released?

**Comment by arielk** [comment]
Unfortunately I have no precise target date, but it certainly is on our roadmap for the next Pro versions.

**Comment by nicolasblume** [comment]
does this mean we will be able to modify the header, or will it be just an additional menu as a normal widget?
Would be so amazing, if we had an "elementor theme" were we could use the same environment for the header and footer 😄

**Comment by michaelsage** [comment]
I would love to see a menu widget. It is probably the main widget missing for me. Can't wait to see this in the pro version!

**Comment by arielk** [comment]
We are currently working on a widget menu for Elementor Pro and I hope we can release it as soon as possible.

Thanks for your patience!

**Comment by VadymVolos** [comment]
NavMenu Addon For Elementor
https://wordpress.org/plugins/navmenu-addon-for-elementor/

**Comment by arielk** [comment]
Finally is here, released in E-Pro v1.8.0

Thanks everyone for your feedback!
