### ISSUE TITLE
Responsive Element style

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1407]
It would be nice to have a responsive element style settings, just like in advanced tab, to be able to choose the background and color for each device (desktop, mobile, tablet).

For example the linear fill looks great on desktop when everything is align in a certain way, but on mobile it should be displayed in another way.

**Comment by arielk** [comment]
Unfortunately we do not plan to add this enhancement, for now you can use the show / hide the element by device under the Advanced tab.

Thanks for your feedback!
