### ISSUE TITLE
Responsive font sizes

### ISSUE THREAD

**Issue by edirpedro** [pojome/elementor#141]
There is no option to set different font sizes for desktop and mobile on each widget. For some large elements like Quotes and Titles for example, this could be useful to stay readable on mobile. Maybe if the Responsive section on the Advanced tab could list additional font sizes for text elements found on that widget.

**Comment by yehudah** [comment]
Hi,
Thanks for you feedback.
We will consider it in future releases.

**Comment by Nat-Faeeria** [comment]
It would also be great to be able to set the margins and padding for different screen sizes. For example, right now I want a margin-bottom for mobile size, but not for laptop size. I can either add css classes and style a bit (which is pretty bad for non-technical end users), or duplicate elements and play with the "show on device" options (which is bad, I don't want to duplicate my content).

**Comment by arielk** [comment]
Fixed #522
