### ISSUE TITLE
[Idea] Fetching Elementor Pro using a script

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1416]
This is just an idea, and may or may not be possible. But it would be great if we could fetch a copy of Elementor Pro without having to log into my.elementor.com to manually fetch and install it on new WP builds.

My scenario is that I work on a development server on client websites, before rolling each of them out on their own servers. When things get busy I tend to use a bash script (kind of like [WP Distillery](https://wpdistillery.org/)) and this helps me set up many sites at once. While I can fetch and install the Elementor Free plugin automatically, I am not seeing a way to do this with Elementor Pro.

I do get that the reasoning behind that is to protect the plugin from outside access, but there could be a way of doing it in the download URL with an SSH token or something, to verify the downloader's credentials. Or the plugin could be hosted via SFTP and retrievable using the Elementor account login info. Plus, the filename could be "elementor-pro-latest.zip" so scripts don't need to be updated all the time.

Or maybe the plugin could be made more useless without an activation key, so it could be more freely downloadable.

It's not an important issue and I have another workaround but I just thought it would be a nice idea to contemplate in the future :)

**Comment by dtbaker** [comment]
Try putting a `print_r($body_args);exit;` into elementor-pro/license/api.php. That should give you a URL to hit. Then a `update_option( 'elementor_pro_license_key', 'YOUR KEY HERE' );` on the deployed site should kick elementor into registering your downloaded Pro version against the new installed URl automatically 

:)

**Comment by KingYes** [comment]
We can't write any Pro code in our free version. So I can't download the Pro version from the free..

Sorry about that..

Thank you for your feedback..

**Comment by abhiyanshrestha** [comment]
In api.php, in which function should print_r.... and update_option()... should be used.
