### ISSUE TITLE
The page doesn't load with the new updated v1.3

### ISSUE THREAD

**Issue by befreeglobal** [pojome/elementor#1425]
I can't edit the pages after refreshing / updating to v 1.3.0. 
Only the Big E ikon can bee seen and nothing happens.
Below the F12 screenshot can help maybe:

https://www.screencast.com/t/R7XZjzve

Thansk for a fast fixing.

**Comment by goranmitic** [comment]
Same here. It was happening to me also in version before so my colleague made some fixes in plugin. Some includes didn't coded right, he told me. It was connected with wp-admin/admin-ajax.php.
After new update it's same again.
I hope you will fix it fast.

**Comment by arielk** [comment]
We managed to fix this issue, please update Elementor to V1.3.1. Sorry for inconvenience.

**Comment by goranmitic** [comment]
I've updated Elementor, clear cache nut i'm getting error again.

![error-shot](https://cloud.githubusercontent.com/assets/4747200/23648605/a95427a6-031b-11e7-8bde-5e639edda796.png)

**Comment by arielk** [comment]
Please edit the wp-config.php file in your WordPress and set the value of `WP-DEBUG` to `true` and then resend the screenshot of the errors.

**Comment by goranmitic** [comment]
I found in error.log:
PHP Notice:  Undefined offset: 0 in /wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php on line 799

**Comment by KingYes** [comment]
Please use default theme of WordPress & Deactivate all your plugins.. and show me the error again.

**Comment by goranmitic** [comment]
After plugins deactivation and switching to theme Twenty Seventeen I have not new errors.

**Comment by goranmitic** [comment]
I've activated again my theme and Elementor Free and Pro and i successfully open editor now.
What was a problem for future occasion?

**Comment by goranmitic** [comment]
Hmmm, i was wrong.. Pro version made me problems...
From error log:
PHP Notice:  Undefined offset: 0 in /wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php on line 794
PHP Notice:  Undefined offset: 0 in /wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php on line 799

**Comment by goranmitic** [comment]
@arielk @KingYes

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website and FTP, and our support team will try to assist.
