### ISSUE TITLE
[PRO] Editor not working when you have Elementor Library Widget in 1.3.0 before content

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1426]
I think issue #1038 resurfaced with this version.

you can replicate this with generatePress theme and add an Elementor Library Widget in Header sidebar, and then try to edit the first page with elementor.

![elmentor](https://cloud.githubusercontent.com/assets/8319178/23618359/cc34676e-0298-11e7-9c4b-51c01af849e5.JPG)

**Comment by arielk** [comment]
We managed to fix this issue, please update Elementor to V1.3.1. Sorry for inconvenience.

**Comment by dudaster** [comment]
I'm afraid the issue is not fixed

**Comment by arielk** [comment]
Please clear the cache in the browser or try to open the editor in private tab and let me know if it works for you.

**Comment by dudaster** [comment]
Allready checked on multiple sites.Tried with different browsers also. (chrome, firefox safari).

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
