### ISSUE TITLE
New Toggle Control

### ISSUE THREAD

**Issue by edirpedro** [pojome/elementor#143]
Control Checkbox could be a Switcher/Toggle instead of a simple checkbox, or maybe another control.

![toggle](https://cloud.githubusercontent.com/assets/831507/16353261/4476b358-3a4e-11e6-9d2e-1a45ab7d7504.png)

**Comment by yehudah** [comment]
Hi,
Thanks for you feedback.
We will consider it in future releases.

**Comment by edirpedro** [comment]
Audio widget could be better with toggle controls. :o)

https://codepen.io/mallendeo/pen/eLIiG
![toggles](https://cloud.githubusercontent.com/assets/831507/16526484/d961abe2-3f87-11e6-9003-4bcd7aa2836b.jpg)
