### ISSUE TITLE
editor stuck on loading screen

### ISSUE THREAD

**Issue by isaacfeldman** [pojome/elementor#1430]
## Description

i've updated to the latest version of elementor and wordpress - i have a video background on the page and it gets stucked on the loading elementor icon - bellow is the console output:

Uncaught TypeError: Cannot read property 'url' of null
    at editor.min.js?ver=1.3.0:4
    at underscore.min.js?ver=1.8.3:5
    at Function.m.each.m.forEach (underscore.min.js?ver=1.8.3:5)
    at Function.m.filter.m.select (underscore.min.js?ver=1.8.3:5)
    at Object.isActiveControl (editor.min.js?ver=1.3.0:4)
    at editor.min.js?ver=1.3.0:4
    at Function.m.each.m.forEach (underscore.min.js?ver=1.8.3:5)
    at n.getActiveControls (editor.min.js?ver=1.3.0:4)
    at n.getStyleControls (editor.min.js?ver=1.3.0:4)
    at n.renderStyles (editor.min.js?ver=1.3.0:4)

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: 5.6.32
	PHP Version: 5.5.22
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.3
	Site URL: http://siman.isaaac.me
	Home URL: http://siman.isaaac.me
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 1.3.44
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 3.3
		Author: Automattic

	Duplicate Post
		Version: 3.1.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.3.0
		Author: Elementor.com

	GP Premium
		Version: 1.2.79
		Author: Thomas Usborne

	Gumroad
		Version: 1.1.9
		Author: Gumroad

	Kirki Toolkit
		Version: 2.3.7
		Author: Aristeides Stathopoulos

	LTR <=> RTL Admin content
		Version: 0.4.4
		Author: Ronny Sherer

	Meta Box
		Version: 4.10.4
		Author: Anh Tran

	W3 Total Cache
		Version: 0.9.5.2
		Author: Frederick Townes

	WordPress Database Reset
		Version: 3.0.2
		Author: Chris Berthe

== Must-Use Plugins ==
	Endurance Browser Cache
		Version: 0.2
		Author: Mike Hansen

	Endurance Page Cache
		Version: 0.4
		Author: Mike Hansen

**Comment by pembelajar** [comment]
I have the same issue! 
![elementor error](https://cloud.githubusercontent.com/assets/17371139/23646205/656badb2-0342-11e7-9463-8e99f7733649.png)

**Comment by arielk** [comment]
We managed to fix this issue, please update Elementor to V1.3.1. Sorry for inconvenience.

**Comment by damiandabcom** [comment]
I have the same issue with the latest version 1.3.1

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by pembelajar** [comment]
I don't have pro. Initially after update to 1.3.1 it's fine but later the problem comes again with 1.3.1

**Comment by arielk** [comment]
We managed to fix this issue, please update Elementor to V1.3.2
Sorry for inconvenience.

**Comment by pembelajar** [comment]
Thanks @arielk you are awesome, so fast!

**Comment by lpsup** [comment]
Hi,
I have a problem with elemeto 1.7.2 in standard edition and 1.8.3 in pro edition
![capture](https://user-images.githubusercontent.com/32271465/30816370-18cde3e4-a216-11e7-9b1b-e95893eb4e35.JPG)

**Comment by trinitywebmedia** [comment]
This is an ongoing issue for us while using Elementor v 2.3.1. Elementor Pro v 2.1.13 
I tried the toggle setting fix and deactivating all plugins.
