### ISSUE TITLE
Error Loading Elementor after last update (Pro)

### ISSUE THREAD

**Issue by luizeof** [pojome/elementor#1432]
## Description

Error loading elementor (pro) after last update.

TypeError: Cannot read property '[object Array]' of undefined
 /wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.3.1:2

## Environment

Wordpress 4.7.3
Hosted on Digital Ocean
PHP 7.0
Elementor Pro
GeneratePress Premium Theme

**Comment by luizeof** [comment]
@arielk @benpines @anandau

**Comment by luizeof** [comment]
![download](https://cloud.githubusercontent.com/assets/257004/23657666/f8252220-031d-11e7-9977-45e4b2a888fb.png)

**Comment by arielk** [comment]
Please try to install the Dev version of Elementor: https://downloads.wordpress.org/plugin/elementor.zip 
and let me know if it works for you.

**Comment by luizeof** [comment]
Hello @arielk ... works great!

Thanks!

**Comment by berkinimamoglu** [comment]
I did try to increase memory and update php but still have this? can you please help me?

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.51
	PHP Version: 7.1.4
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: https://iceberg-technologies.com
	Home URL: https://iceberg-technologies.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Istanbul
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.5.10
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6

== Active Plugins ==
	All In One WP Security
		Version: 4.3.2
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Auto Post Thumbnail
		Version: 3.4.1
		Author: Aditya Mooley <adityamooley@sanisoft.com>, Tarique Sani <tarique@sanisoft.com>

	Contact Form 7
		Version: 5.0.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 2.0.3
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 7.0.4
		Author: MonsterInsights

	Jetpack by WordPress.com
		Version: 6.0
		Author: Automattic

	LiteSpeed Cache
		Version: 2.2.0.2
		Author: LiteSpeed Technologies

	myStickymenu
		Version: 2.0.4
		Author: m.r.d.a

	Ocean Extra
		Version: 1.4.10
		Author: OceanWP

	Polylang
		Version: 2.3.4
		Author: Frédéric Demarle

	Really Simple SSL
		Version: 2.5.26
		Author: Rogier Lankhorst

	Show Current Template
		Version: 0.3.0
		Author: JOTAKI Taisuke

	Use Any Font
		Version: 4.9.2
		Author: Dinesh Karki

	WooCommerce
		Version: 3.3.4
		Author: Automattic

	WooCommerce Bookings
		Version: 1.10.11
		Author: Automattic

	WooCommerce iyzico checkout form Payment Gateway
		Version: 1.0.6
		Author: KahveDigital

	WP Rollback
		Version: 1.5
		Author: WordImpress

	Yoast SEO
		Version: 7.2
		Author: Team Yoast


== Must-Use Plugins ==
	Endurance Page Cache
		Version: 1.1
		Author: Mike Hansen


== Debug ==
	Errors: 
		TypeError: undefined is not an object (evaluating '$.validator.messages')
			at undefined - 5:21
			2018-03-05 21:39 +00:00
			x 3 times

		TypeError: e.elementorWaypoint is not a function. (In 'e.elementorWaypoint(function(){var e=this.element||this,i=t.apply(e,arguments);return n.triggerOnce&&this.destroy&&this.destroy(),i},n)', 'e.elementorWaypoint' is undefined)
			at https://iceberg-technologies.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.9.6 - 2:4541
			2018-02-28 20:15 +00:00
			x 15 times

		TypeError: undefined is not an object (evaluating '$.validator.messages')
			at undefined - 5:21
			2018-02-28 20:13 +00:00
			x 6 times

		TypeError: jQuery is not a function. (In 'jQuery(e)', 'jQuery' is undefined)
			at https://iceberg-technologies.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.9.6 - 2:1714
			2018-02-26 21:17 +00:00
			x 48 times

		TypeError: undefined is not an object (evaluating 'elementorFrontend.getElements("window").jQuery.holdReady')
			at https://iceberg-technologies.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.6 - 2:78978
			2018-02-26 20:54 +00:00

		TypeError: jQuery is not a function. (In 'jQuery(e)', 'jQuery' is undefined)
			at https://iceberg-technologies.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.9.6 - 2:1714
			2018-02-26 20:54 +00:00
			x 4 times

		TypeError: jQuery is not a function. (In 'jQuery(e)', 'jQuery' is undefined)
			at http://iceberg-technologies.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.9.6 - 2:1714
			2018-02-24 09:55 +00:00
			x 21 times

		TypeError: undefined is not an object (evaluating 'elementorFrontend.getElements("window").jQuery.holdReady')
			at http://iceberg-technologies.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.6 - 2:78978
			2018-02-24 09:55 +00:00

		TypeError: jQuery is not a function. (In 'jQuery(e)', 'jQuery' is undefined)
			at http://iceberg-technologies.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.9.6 - 2:1714
			2018-02-24 09:55 +00:00
			x 4 times

		TypeError: e.elementorWaypoint is not a function. (In 'e.elementorWaypoint(function(){var e=this.element||this,i=t.apply(e,arguments);return n.triggerOnce&&this.destroy&&this.destroy(),i},n)', 'e.elementorWaypoint' is undefined)
			at http://iceberg-technologies.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.9.6 - 2:4541
			2018-02-24 08:47 +00:00
			x 2 times

**Comment by prashant1k99** [comment]
Same here in Pro Version, it stuck on to loading screen and goes nowhere... Even after waiting for an hour...
