### ISSUE TITLE
"Column" and "Section" buttons

### ISSUE THREAD

**Issue by marcofrasson** [pojome/elementor#1433]
Hello,

I have difficulty selecting the "Column" or "Section" of overlapping elements, especially when I make a "sticky" element in the header of the site, the "Column" and "Section" buttons are hidden.

It also happens when there is some element superimposed on the other, with negative margin.

Perhaps a solution is to leave the "Column" and "Section" buttons fixed when clicking on an element inside them, because currently they only appear with the mouse: hover.

And when it's glued to the top of the browser, make the "Column" and "Section" buttons stay in the bottom or something along those lines, as they do not appear when glued to the top.

**Comment by arielk** [comment]
In the latest version we made another patch for this issue.

You can please update Elementor to v1.3.2 and let me know if it works for you.

Thanks

**Comment by marcofrasson** [comment]
Hi Ariel,

Thanks for the reply ... I did the update, and it seems that it improved a bit on the selection of buttons, but still persists when one elementor behind another. I've done a screencast here, if you can take a look, you'll understand what I'm saying.

I select the item (slide) within the section, hoping to be able to tinker with the section, but to no avail.

https://www.dropbox.com/s/c6h1l79m3ef4txq/Elementor_Buttons-Column-Section.mp4?dl=0
