### ISSUE TITLE
Default and synchronized template for custom type

### ISSUE THREAD

**Issue by olivier-perrier** [pojome/elementor#1435]
Hi everyone,

I would like to post a new functionally that could be useful in general even more in Elementor.

What I would like to be able to do: have a custom post containing by default an Elementor template.
The second part: a synchronized Elementor template for a custom post type.

I using Elementor with custom field, I define custom fields for the client and I use them inside the elementor Template. Then I hide the basic content for the client. The post is very easy to use for the client and the interface is build inside Elementor.

The problems are: we a new post is created the content is empty then a first operation of loading the Elementor template to the post is necessary.
In addition, when the template change, all the post using this template should change.

Here maybe a first mind about how realize these new features.
The first one should be easier: adding an option for associating an Elementor template to a default custom type. Then, a hook when a custom type is created calling the template adding.

The second one should be a bit harder, I think a new Meta is necessary for containing the name of the template using inside a post
The update of the Elementor template is done when the template is saved. At this point, every post containing the Meta of the name of the elementor Template are replaced with the new one.

I really would these new feature appear because it no more resource efficient and it could avoid a template coding.

Tell me if these feature interested you, if it is possible and if I can help.

See you 

Olivier

**Comment by dudaster** [comment]
I'm working on a template that does this. But rather then assign like you said, it does it like this:
-create a elementor template with the name _post_type / _post_type-single / -post_type_term etc.
-Each template contains text keys like {title}, {content} { custom field} etc. that would be replaced with the actual value.

The end result should be as much as code free as possible designing a theme from scratch.

**Comment by olivier-perrier** [comment]
Thank you for your answer. 
It really nice to nice an active community, really good plugin.
Hope to see it soon !

**Comment by arielk** [comment]
I merged this issue with another issue #543 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
