### ISSUE TITLE
Elementor Inaccessible after adding WooCommerce Search Product Widget

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#1437]
After adding the WooCommerce product search widget we can no longer access Elementor on any page created with Elementor on any site. This includes new and existing pages created before the last Elementor update.

Right now a number of our client sites are completely inaccessible from the back end but the front end is functional.

Using Elementor & Pro latest release and running WP 4.7.3 Multi site with the GeneratePress theme

This is not a caching issue.

See screenshot below and screenshot of console error

![woocommerce search widget crashes site](https://cloud.githubusercontent.com/assets/20524372/23669343/b14a0832-035b-11e7-9264-e81a10e7c818.jpg)

![woo search widget console errors](https://cloud.githubusercontent.com/assets/20524372/23669125/14b04c7a-035b-11e7-9f74-7a2cd69962ac.jpg)

**Comment by arielk** [comment]
You can please update Elementor to v1.3.2 and let me know if it works for you.

Thanks
