### ISSUE TITLE
[bug] Shape divider (bottom) not working properly

### ISSUE THREAD

**Issue by marcusig** [pojome/elementor#1438]
Hi there,

I've just tried using the shape divider on a project I'm working on, and I get a slight problem on the BOTTOM one. 
see this page http://letstalkfamily.indigogroup.net/ at the end of the section called "Let's talk", the waves (and other dividers I've tried) are up side down. It looks fine when the editor is active, but not when viewing the page? 
I tested in Chrome and Safari, logged in and not, same result, cleared server and browser cache. 

nb: the first "tilt" effects on the link are NOT elementor but my own css solution I did before the Shape divider was introduced.

**Comment by dudaster** [comment]
you have invert button there, push it!

**Comment by arielk** [comment]
Thanks for your report!

https://github.com/pojome/elementor/pull/1436 foxed for the next version (v1.3.3)
