### ISSUE TITLE
Feature Request - "Custom" Icons

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#1441]
The list of Font Awsome Icons continues to grow and it would be unusable for all of them to be included in a drop down list. The feature request is for the ability to have a "custom" icon option that if selected would enable the entry of the Font Awsome "fa" codes for that item (for example "fa fa-xing" for the xing icon). It is understood that with a custom icon it would not be possible for the icon to have the "official colour" when it is in the social media 'element' and that it would have to be styled separately. The existing custom colours option would override and the custom setting for the "custom icon".

**Comment by ryanlabelle** [comment]
Related to : https://github.com/pojome/elementor/issues/110#issuecomment-285202740

**Comment by ericadyson** [comment]
Hi there. How do I use Custom Icons for Elementor plugin. It worked perfectly before. I created the icons in Fontello and uploaded the .zip file and with the aid of the plugin, they were then available along with the other icons. Now I can't get at them. Also, I see an upload button on your new feature but it goes to a page where there are no icons (or icon set). What am I doing wrong? I need my own custom icons added to the drop down option when selecting icons. Help please!
