### ISSUE TITLE
Bug: "Required" option when duplicate a form field

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1442]
When you duplicate a form field in a form, where the required-option is switched on, the new field seem to have the required-option switched off (in the editor-area), but in fact it is set on; in both backend and frontend the "*" is displayed. The workaround is to switch off and on the required-option. But it should be fixed.

**Comment by KingYes** [comment]
Thanks. It's fixed in v1.4 and next version of EPro.
