### ISSUE TITLE
Problems with update installation  (Elementor Pro 1.2.3)

### ISSUE THREAD

**Issue by goranmitic** [pojome/elementor#1446]
## Description

When I tried to update Elementor Pro to 1.2.3 I got:

Update Failed: Could not copy file. elementor-pro/modules/panel-posts-control/controls/group-control-posts.php

## Environment

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
	MySQL version: 5.6.21
	PHP Version: 5.6.3
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.3
	Site URL: http://elementorpro.loc
	Home URL: http://elementorpro.loc
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Elementorist Pro
	Version: 1.0.2
	Author: Goran Mitic
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

== Active Plugins ==
	Elementor
		Version: 1.3.3
		Author: Elementor.com

	Elementor Pro
		Version: 1.2.2
		Author: Elementor.com

	Theme Check
		Version: 20160523.1
		Author: Otto42, pross

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by ivrok** [comment]
The same problem. I tryied even disable all another plugins and left active just 2 (elementor and elementor-pro). 
Elementro - Version 2.0.12
Elementor-pro - Version 1.15.6
