### ISSUE TITLE
[Idea] Template export with images

### ISSUE THREAD

**Issue by goranmitic** [pojome/elementor#1447]
It could be great if template export has option to save, besides json file, also all template's images.
This will be very useful and time-save for all designer who want to offer Elementor themes and templates to people.
What do yo think?

**Comment by arielk** [comment]
Once you import template from other website the all images imported also automatically.

Note: this feature is not work when you import template from localhost.

Thanks for your feedback!

**Comment by joffcrabtree** [comment]
Thanks ArielK but I am always building in local dev first. How can we set up so that we can export images with the template from local dev environment?
