### ISSUE TITLE
Image carousel - image height

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#1449]
I have a problem (or a suggestion) with the image carousel and the image heights in the carousel. 

For example i have three pictures - all in the same resolutions, but one is upright. Two are 1920x1080 and one is 1080x1920. 
So, the carousel splits the width, to fit in the three images on the screen. But, the carousel dont care about the height of the pictures. And so the height of the images differs a lot and it destroys the "visual flow". I would love to see, that the pics has a certain height and stretches the width as far as it need to be. Like setting "Slides to be displayed" on flow... depending on the height.

Example pic of how it is now: http://luxam.at/downloads/screen2.png

I could not find a way to bind the pictures to the height. Is there a way or can you implement the option to make this happen? Or is there a reason why this is not implemented yet?

Best wishes! Steven

**Comment by arielk** [comment]
I hope I understand you well...

But you simply can set the image size by using size "custom" and determine the exact size of each image slide, see the screenshot: http://i.imgur.com/L6OdezM.png

**Comment by Luxamman** [comment]
That is true, but it ignores the format (16:9, 4:3...) of the pictures. With that i can set it right for one format, every other format will be cut to that resolution. 
So my problem is more the mixing of pictures with more height with pictures with more width - without cutting away parts of some pictures.

**Comment by MondeLionel** [comment]
@arielk Solved it for me. Thanks. Great plugin, well done.

**Comment by chdonncha** [comment]
Same problem, cuts off the images if they're not the correct aspect ratio, this is problematic when adding a bunch of company logos to a companies that use us carousel.

**Comment by taropaa** [comment]
I agree with @Luxamman, this field should support mixed aspect ratios.

**Comment by mechaphone** [comment]
I have the same issue in the image carousel. **Please Elementor fix this** for since the world combines different formats all together.

**Comment by benrosati** [comment]
### Here's a work-around:
Select the skin option **Slideshow**.
An option titled thumbnails will appear, select **16:9**.
Under the advanced tab add **Custom CSS**:
```
selector .elementor-swiper:last-of-type {
    display: none;
}
```

**Comment by MiguelRuizDesign17** [comment]
> I hope I understand you well...
> 
> But you simply can set the image size by using size "custom" and determine the exact size of each image slide, see the screenshot: http://i.imgur.com/L6OdezM.png

I have set these to Width=100% and Height=546px. This does work to set the size of the container for the image slides but the doesn't seem to be any options for the images within. I think the widget setting option missing on the Elementor Image Carousel widget is the ability to set the images to **cover its container**. That way images with varying aspect ratios and orientations that are uploaded will at the very least take up space appropriately. Much like the settings available in the Elementor Slides widget (Cover or Contain).

I have encountered this problem on a custom post type using a Pods Gallery Field. Is there a way to do this with custom CSS? I have been looking for ways but what I have tried has not worked:

`.elementor-slick-slider .slick-slide img {
  height: 100%; /* What this does is it stretches the images, which is not favorable */
}

.elementor-slick-slider .slick-slide img {
  background-size: cover; /* Since this is an image pulled up dynamically via a custom field, it may be more complicated than this */
}`

Any help would be very appreciated.
Thank you

**Comment by tkontogi** [comment]
Having the same issue using Elementor 2.9.9 / WP 5.4.1

A css is a workaround but not solution.

I believe that the issue remains open.

**Comment by Linabassiouny** [comment]
Hello!
This is my first comment on Github, hope you can help me, please!

I am trying to set all the images on the carousel at the same height, but not with the same width because I don't want the images to be cut. I am working with elementor.

I try to add the code that @benrosati paste here but didn't work for me.

Is there any way to solve this?

**Comment by brandondeveloper2016** [comment]
i have the same problem, what i do is i select the image size in custom, then give my image width = 100% and height that is equals to the image with the lest height, they have the same height now on the carousel, but i dont know if this is the best option or  practice..haha

**Comment by traceyweb** [comment]
This is a bit old but I solved it by setting a custom height for the Image Carousel settings, leaving the width blank. And then adding CSS to get the width to adjust based on the image size:

.swiper-slide {
    width: auto !important;
}

**Comment by semmtex** [comment]
Just putting it here for others that might stumble upon this thread. Together with @brandondeveloper2016 and @traceyweb info, you can get the Image Carousel to behave as it should and keep aspect ratio in check:

FYI: Slides to show no longer matters. Simply set the image size to custom and only fill in the height. Then add the custom css from traceyweb to the element, et voila....

**Comment by justgkp** [comment]
**Can’t adjust the width and height. tried different themes..tried with same h*w images… etc..etc….still issue remains the same...Elementor page builder everything is okay and showing the real h*w...but in the front page it’s showing something else….** Please find the pics below for you ref.
![for-team](https://user-images.githubusercontent.com/71189434/149400167-74cc4b9c-39e5-477f-902f-cbff0ccfbc38.jpg)
![Screenshot-2022-01-14-at-12 35 21-AM](https://user-images.githubusercontent.com/71189434/149400193-7ee59678-55f7-44da-be0f-8e5758c961f7.jpg)

**Comment by mikeciffone** [comment]
> This is a bit old but I solved it by setting a custom height for the Image Carousel settings, leaving the width blank. And then adding CSS to get the width to adjust based on the image size:
> 
> .swiper-slide { width: auto !important; }

Also needs `max-width: 100%;` otherwise the right arrow is gone but this works. For anyone else a combination of this and the other is not the answer. Just use this method.

**Comment by jovalreseauformation** [comment]
This solved our problem !
`selector .swiper-slide img {
    height: 400px;
    width: 100%;
    object-fit: cover;
}`

**Comment by knalleDK** [comment]
This works for me. Using **aspect-ratio** instead of fixed height.

```
selector .elementor-image-carousel-wrapper {
    aspect-ratio: 16 / 9;
}

selector .swiper-slide-inner {
    height: 100%;
}

selector .swiper-slide .swiper-slide-image {
    height: 100%;
    width: 100%;
    object-fit: cover;
    object-position: center center;
    -moz-user-select: -moz-none; /* optional to prevent accidental selection of images when swiping */
    -webkit-user-select: none;
    user-select: none;
}
```

**Comment by mariannementink** [comment]
@jovalreseauformation I used your solution! it works on a desktop screen. 
Do you also have a code which i can use for tablet and mobile screen?

**Comment by speedxcz** [comment]
+1
Ideal if you could set it Image Fit Cover as is the case with Media Carousel. Which in turn is not ideal because it cannot place the momo carousel arrows.

**Comment by stuartleech** [comment]
In every scenario where I add additional CSS to make it look right it cuts off the last image?

**Comment by markobakic-srb** [comment]
> This works for me. Using **aspect-ratio** instead of fixed height.
> 
> ```
> selector .elementor-image-carousel-wrapper {
>     aspect-ratio: 16 / 9;
> }
> 
> selector .swiper-slide-inner {
>     height: 100%;
> }
> 
> selector .swiper-slide .swiper-slide-image {
>     height: 100%;
>     width: 100%;
>     object-fit: cover;
>     object-position: center center;
>     -moz-user-select: -moz-none; /* optional to prevent accidental selection of images when swiping */
>     -webkit-user-select: none;
>     user-select: none;
> }
> ```

Thank you for inspiration to make much easier and for me better solution:
`selector .swiper-slide img {
aspect-ratio: 4 / 3;
width: 100%;
object-fit: cover;
object-position: center center;
}`

**Comment by TautvydasSerepka** [comment]
> This is a bit old but I solved it by setting a custom height for the Image Carousel settings, leaving the width blank. And then adding CSS to get the width to adjust based on the image size:
> 
> .swiper-slide { width: auto !important; }

Custom height&width options are in Pro version, custom CSS also in paid.

**Comment by TautvydasSerepka** [comment]
> This solved our problem ! `selector .swiper-slide img { height: 400px; width: 100%; object-fit: cover; }`

Where should I put this cope so that it'd be active? Customise - additional CSS doesn't work, Custom CSS in Elementor - Pro version
