### ISSUE TITLE
?elementor on specific pages returns 200 with empty body

### ISSUE THREAD

**Issue by MilanMaric** [pojome/elementor#1450]
## Description

Elementor has worked on all pages regularly, but there is an newly issue with it and /page/?elementor returns an empty body response (200).

When I have enabled the WP_DEBUG the response is

Notice: wp_enqueue_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in ~/public_html/wordpress1/wp-includes/functions.php on line 4137

Notice: wp_enqueue_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in ~/public_html/wordpress1/wp-includes/functions.php on line 4137

Notice: wp_enqueue_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in ~/public_html/wordpress1/wp-includes/functions.php on line 4137

## Environment
http://pastebin.com/WhEp83iA

**Comment by WPDevHQ** [comment]
That may well be either one of the active plugins or the theme that's doing it wrong.

Have you tried deactivating all plugins but for Elementor and check? Also switch to one of the default themes and check that it's not the theme which is causing the issue

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
