### ISSUE TITLE
Fix issue — change private static $_default_breakpoints from 'lg' => 1024 to 'lg' => 1025

### ISSUE THREAD

**Issue by Githubhem** [pojome/elementor#1454]
Hello!

You should change private static $_default_breakpoints from 'lg' => 1024 to 'lg' => 1025.
Now its 1024 and we have @media(max-width:1023px) for tablet, but we must have @media(max-width:1024px) for tablet.

**includes/responsive.php** 

```
private static $_default_breakpoints = [
		'xs' => 0,
		'sm' => 480,
		'md' => 768,
		'lg' => 1025,
	];
```

If you change private static $_default_breakpoints from 'lg' => 1024 to 'lg' => 1025 — all new pages will be working right — @media(max-width:1024px) for tablet. 

Old pages still be @media(max-width:1023px). We must go to Elementor Tools and Regenerate CSS.

**Comment by arielk** [comment]
This is something they fixed in the past. Where do you see the that we use a width of 1023px?

**Comment by Githubhem** [comment]
Elementor uses 1023px in @media(max-width:1023px) for tablet. But must be @media(max-width:1024px). Here: http://relfy.ru

![1023](https://cloud.githubusercontent.com/assets/16056748/23947013/db6721da-098d-11e7-95d3-37697bd29e58.PNG)

It happens because **private static $_default_breakpoints = ['lg' => 1024,];** (responsive.php ).
Tablet "md" max = lg-1 **($screen-md-max: map_get($breakpoints, lg) - 1;)**
And we have: 1024-1=**1023 px.**

If you change private static $_default_breakpoints from 'lg' => 1024 to **'lg' => 1025** — all new pages will be working right — @media(max-width:1024px) for tablet (1025 px -1 = 1024 px). Old pages still be @media(max-width:1023px). We must go to Elementor Tools and Regenerate CSS.

**Comment by arielk** [comment]
Fixed for the next version. Thanks for your feedback!
