### ISSUE TITLE
Enhancement Request - Add FontAwesome to Social Icons

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1455]
It would be great to have a filter to enable font-awesome into the drop down so we can choose things like the envelop and cart icons as well.  Turn the filter off to show just the social networks for ease of use in finding them.  Actually, just leave it off as default so the user experience is still the same.

**Comment by arielk** [comment]
It's a little tricky, if you have specific icons missing you, please write to us and we will add.

**Comment by pingram3541** [comment]
Do you prefer direct via Pro support on the website or just ask here?

I provided two icon types I'd like to see, one for email links and another for shopping cart links.  In some cases it makes sense to combine these into the same widget space as social links for design cohesion.

For now I am using custom css to convert the icons but it is much pain to do and customer cannot edit without confusion because it appears as a social network they are not using in the editor.

i.e. I use pseudo elements in custom css to accomplish but can also cause a FOUC during page load which is undesirable.  Thx

**Comment by arielk** [comment]
You can ask here :)

Latest PR for the social icons widget with new icons: 
https://github.com/pojome/elementor/pull/1417
https://github.com/pojome/elementor/pull/1273
https://github.com/pojome/elementor/pull/955

**Comment by pingram3541** [comment]
Thanks, I've added them both =)

https://github.com/pojome/elementor/issues/1463
https://github.com/pojome/elementor/issues/1462
