### ISSUE TITLE
PRO ManageWP panel Sync Websites error

### ISSUE THREAD

**Issue by Makar** [pojome/elementor#1456]
Fatal Error (E_ERROR): Class 'Elementor\Admin' not found occurred in wp-content/plugins/elementor/includes/plugin.php on line 215. Please make sure that your website is accessible.

**Comment by KingYes** [comment]
Please try to re-install Elementor and tell me if it's working for you or not.

**Comment by Makar** [comment]
Just removed version 1.3.3
On the new installed 1.3.4
Activated for the network
Error left :'(

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
