### ISSUE TITLE
[Idea] CSS pipette or Custom CSS connection to make styling easier

### ISSUE THREAD

**Issue by MaskaZan** [pojome/elementor#1467]
Hi again! It would be very cool if you made a CSS pipette (eye dropper) tool (like a color pipette). In order that you can easily copy Custom CSS from one element to another, because I often use the Custom CSS tab and when I need to change the styles for one element, I have to do the same for others. It will be even better to create not a pipette, but a connection of styles between elements.

**Comment by arielk** [comment]
I merged this issue with another issue #1479 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
