### ISSUE TITLE
Resize the editor pane

### ISSUE THREAD

**Issue by vfxdude** [pojome/elementor#147]
The editor pane is too narrow when using the text editor widget or any textarea. The ability to make it wider would be good.

**Comment by edirpedro** [comment]
Try the Fullscreen button present on the WP Editor.

![captura de tela 2016-06-26 as 13 53 51](https://cloud.githubusercontent.com/assets/831507/16363594/7195766e-3ba5-11e6-9ace-3c783a5b13ea.png)

**Comment by vfxdude** [comment]
You don't see the preview pane then, and it doesn't work with the text mode or other textareas. And a
the media button also is gone.

**Comment by arielk** [comment]
Resolved V0.6
