### ISSUE TITLE
Bug with FORMS in Elementor PRO

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#1472]
Hi Guys, with last version of PRO Elementor, the required label not working. It does not maintain check REQUIRED when you try to edit the form.

**Comment by arielk** [comment]
Does this happen only when you duplicate the field like this issue #1442?

**Comment by sododesign** [comment]
No, to me it always happens in reality. Not only in the duplicate fields

**Comment by KingYes** [comment]
Thanks. It's fixed in v1.4 and next version of EPro.
