### ISSUE TITLE
Feature request: Image Gallery - Rel Attribute

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1473]
For those of us using themes with different [light]box options, typically the trend is that most of them will associate the gallery js trigger using the `rel` attribute.

Similar to how we can add a custom css `classes`, it would be nice to be able to define a `rel="prettyphoto[gallery-1]"` attribute that would be applied to all images in the gallery.

I currently use js to append these atts to get the [light]box capability working rather than use the gallery shortcode inside a text editor because the gallery element is much nicer on the experience for administration.

**Comment by drawcard** [comment]
It's not a bad idea, perhaps the idea could be advanced to allow any HTML5 data attribute, eg ```"data-lightbox='prettyphoto'"`` or ```"data-prettyphoto"``` as well.

As a workaround I use Jquery to [apply a data attribute](http://stackoverflow.com/a/13524139) as needed.

**Comment by pingram3541** [comment]
Yes indeed.  Adding and deleting of atts + values is an excellent suggestion, it's simplistic while still living in the advanced area not to mess with the feng shui of the user experience.

**Comment by pingram3541** [comment]
On second thought, this would be handy for button links too, especially when integrating other things like modal pop-ups, ajax trigger, etc.  Maybe the consideration should be for ALL elements in which you can provide a url, simply an extra option to add html attribute to the anchor element, and I still like the idea of being able to add/delete more than one attr key/value pair.

**Comment by arielk** [comment]
At the moment, we are not planning to add such an option.

In any case we're working on Image Lightbox for the next version. 

Thanks for the feedback!

Ref: https://github.com/pojome/elementor/issues/359

**Comment by pingram3541** [comment]
We can use wp filters to add atts to Elementor content right?

**Comment by matipojo** [comment]
Yes, You can!

https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md#elementorwidgetrender_content
