### ISSUE TITLE
Image widget and media library SVG broken

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1474]
I've uploaded an svg for an image element and in the element settings it shows the rendered svg image in the "choose image" area however it does not render in the preview editor nor on the front end.

If I choose to open the media library from within the Element it does not show any svg files however if I open the media library in wp-admin I can see all my svg files.

If I use a text element and try to add the svg image there, it shows in the media library dialog and I can choose it however when I set it and it renders in the text editor dialog, it shows as an anchor tag linking to the svg file rather than an img or svg html tag.

edit: I can use a text element but must change the anchor tag manually into an img tag and change href to src attribute.

**Comment by arielk** [comment]
I'm trying to figure out how I can reproduce this problem.

If your WP Media supports SVG files ([read more here](https://css-tricks.com/snippets/wordpress/allow-svg-through-wordpress-media-uploader/)) everything works great just like PNG or JPG.

Can you have any screenshot for this?

**Comment by pingram3541** [comment]
I think it has to do with WordPress not *fully* supporting svg files *yet*.  Also, sbg files are not treated by WordPress as "image" type files, they are treated like some other document i.e. pdf.

For example, I found that I can upload svg no problem but the media area does not render the svg.  If I insert it into a post, it is just the file name text that is insert unless I choose to also insert the permalink which results in an anchor link to that image.

I can use the text editor to change the anchor tag into an img tag and it renders beautifully in the wp editor instance.

If I try o add it as a featured image, it doesn't show up in the library because the Featured image behavior only shows "image" files.  If I choose to upload an svg from the featured image dialog it allows me to upload it but setting it does not take or save nor does it render in the featured image meta box nor ultimately the front end.

So, not an Elementor issue WordPress is just a few years behind the times when it comes to svg =)

If one wants to use svg with Elementor, the only way is manual via html / text element.

**Comment by badcat** [comment]
I've had success with the SVG Support plugin https://wordpress.org/plugins/svg-support/ and then was able to use SVG mostly everywhere I wanted within Elementor's UI.

**Comment by arielk** [comment]
@pingram3541 @badcat thanks for sharing!

**Comment by juanpasolano** [comment]
:( I'm still having this issue even though I installed the suggested plugin.

![nov-22-2018 13-57-35](https://user-images.githubusercontent.com/1621720/48919130-0b148c80-ee5f-11e8-8b19-779172bb3441.gif)

**Comment by dtbaker** [comment]
My SVG just stopped working, I'm trying to figure out why
