### ISSUE TITLE
Page scroll at magnificpopup opening

### ISSUE THREAD

**Issue by akimad** [pojome/elementor#1478]
Hi,

I just updated Elementor to its last version and now, when I open a magnificpopup on my webpage, the page scroll automatically.

Here is the webpage: [website](https://akimad.com)

And the problem is on the contact link at the top of right corner of the header.

Thank you for your help

**Comment by akimad** [comment]
Solved with the last update (1.4.0). Thanks!

**Comment by arielk** [comment]
Cool!
