### ISSUE TITLE
Many nested divs

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1480]
I noticed there are a lot of nested html divs used in Elementor.
Is this an issue you guys plan on fixing?

**Comment by paaljoachim** [comment]
I posted about multiple nested html divs here to get some feedback to see what various developers thought: https://www.facebook.com/groups/advancedwp/permalink/1435951346467075/

**Comment by joshmarom** [comment]
Please explain what is the issue, why do you believe it is an issue, and what is the desired solution.

**Comment by paaljoachim** [comment]
I just want to tell folks who drop by this thread that you made a very good reply to the Facebook thread. Thank you Josh!
