### ISSUE TITLE
 forms file upload filed

### ISSUE THREAD

**Issue by ushmid** [pojome/elementor#1482]
Please add file upload filed type to the pro form builder.

So that form submissions can include attachments.

**Comment by lukecav** [comment]
Should be able to use, **wp_insert_attachment**. Then store that attachment in the form post type.

**Comment by Basilakis** [comment]
File Upload should exist as general field, not just for form.

**Comment by enkota** [comment]
+1 - Had a few clients needing file uploads and having to replace with another third party form.

**Comment by sugarchrist** [comment]
Hello,
Could you add file upload filed to the Elementor Pro form to include attachments please.
Thank you
Christian

**Comment by dumbledorian** [comment]
Hello, same here. Bought Elementor Pro mainly to be able to build forms. Works great, but cannot use it because of missing file upload functionality. Please be so kind to add this feature, thank you!

**Comment by black-eye** [comment]
+1 Oh yes, this would be really handy. I actually had to use other form plugin, just because of the absence of this feature.

**Comment by kirstenray** [comment]
Piling on here, having file upload is critical when building forms and I would welcome this feature in Elementor.  I will volunteer my time to help with this.

**Comment by useyourblinker** [comment]
I would really like to be able to use the Forms widget for this as well.

It would be much better looking (as the Elementor Pro forms are) than the patchwork of Contact forms that get used for different purposes.

**Comment by jvascomarques** [comment]
File upload in Forms is a very important feature and could really add value to a **New Pro Forms widget** that could also include a Date and Time Picker.

C'mon E-Team lets make this happen!

**Comment by nesoor** [comment]
I need this option too ! 👍

**Comment by timmywheela** [comment]
Any ETA on this feature?

**Comment by ghorcades** [comment]
Look at this plugin:
https://github.com/yehudah/Elementor-Forms-Upload-Field

**Comment by nesoor** [comment]
Hey ghorcades,
I just tried the plugin but it didn't work for me.
Not even a document of 50kb :(

**Comment by apasdevant** [comment]
upload files in form with Epro should be now.

Thanks for your consideration.

**Comment by NanoCr** [comment]
I have Epro but still dont see any file upload!
:-/

**Comment by ApollyonGrim** [comment]
Please add a file upload field to the Elementor form. I have clients needing this feature and I hate having to add another form plugin to their site just for this purpose.

**Comment by urmamb** [comment]
Please add file upload. It will totally complete the form. I want to use it for job applications so the applicants can upload their CVs.

**Comment by Basilakis** [comment]
@arielk You do not have any other post with such big demand. Just do it :)

**Comment by mrandt** [comment]
vote for this too

**Comment by arielk** [comment]
We're working on this field (and some more new form fields) for the next version. 
Thanks.

**Comment by bainternet** [comment]
Done!

**Comment by sugarchrist** [comment]
Hi, I have a follow up comment on the last version of Elementor Pro about the upload file in the form.

Is it possible to make the file uploaded, be in the email as a attachment and not just a link on my server.
Thank you

**Comment by pedroviana** [comment]
I can't send attachment from mobile, why? on desktop works fine

**Comment by J1rogerson** [comment]
elementor file uploader changes the original file name when transmitting files. Is there a way to save original file name when transmitting files?

**Comment by sugarchrist** [comment]
Hello,
Is there any update on making the file uploaded be in the email as a attachment and not just a link on my server.
Thank you

**Comment by atMaarten** [comment]
File as attachement would be great!

**Comment by Artneo7** [comment]
+1 for file on email as an attachment.

**Comment by JumaDM** [comment]
+1 for that too

**Comment by Xquiset** [comment]
+1 would be awesome to have that ability

**Comment by team-webstudio** [comment]
Yes, please make the file uploads be in the email as a attachment and not just a link on my server. And also please retain and save the original file name when transmitting files, thanks!

**Comment by gfdesign** [comment]
Please, add the option to specify a destination folder as wp-contents/uploads in order to be able to delete manually the attachments.

In that way, we'll be able to delete them from WordPress admin and not as we're doing throguh FTP
Thanks

**Comment by pebneter** [comment]
Hi there,
the upload of the files works fine (stored under /wp-content/uploads/elementor/forms/...).
But how can I find and delete those files if I do not have FTP access to the folder? i.e. if I want to delete sensitive files that someone uploaded.
