### ISSUE TITLE
Using externally hosted media (CDN)

### ISSUE THREAD

**Issue by KRline** [pojome/elementor#1491]
Feature request
I am using Cloudinary.com to host my media files on external server (in fact using a Content Delivery Network only for media files). When editing a page (outside Elementor), the Cloudinary integration button is displayed alongside the "add media" button of the Wordpress Media Library. Or as they explained on a support mail I sent to Cloudinary:
"We developed the plugin in such way that the "Cloudinary Upload/Insert" button is supposed to be displayed in any place where native WP media library [button] is present."
When using Elementor, selecting an image immediately opens Wordpress Media Library, so the Cloudinary button is not displayed (and is not shown inside the media library). My solution now is to open another browser tab with wordpress edit of a dummy page where I insert images from Cloudinary so they get imported into media library (database). Then go back to elementor tab, select image to open media library, search for new file (to refresh the display), and select the newly added media file. Rather cumbersome.
One solution would be to give the option to enter the URL of an external media file into Elementor. This could then be used to link to any external media/image file on any external server (dropbox, google, ...). The idea is to put the link to the image into the (media library) database without downloading te image file itself to the webserver.
Another solution (maybe better) would be to display a selection screen when configuring/selecting an image: add media (to open media library), and alongside any plugin such as the Cloudinary plugin. Or make a setting for Elementor to either directly open Media Library or another plugin/media-selection-tool.

I also tried to use the "External Media" plugin with the Dropbox option. It worked as designed in a normal page edit, but not when opening Media Library from within Elementor. Clicking on the "external URL" button just did not react. (But anyway, this plugin does not work as I want it, as it needs to download the external image to the local server to be able to use it as an image...)

**Comment by arielk** [comment]
I'm not familiar with this plugin, for now we only work with built-in Media Library. I think that we need to do custom integration between the plugins. Unfortunately, this is not something we plan to do soon. 
About inserting image using an external URL, you can follow this issue #413

**Comment by lukecav** [comment]
@arielk 
https://github.com/cloudinary/cloudinary_wordpress

**Comment by dave-hiddendepth** [comment]
If you provide an option to add media via a URL this might be a step towards using CDN images

**Comment by KRline** [comment]
Indeed, as dave-hiddendepth mentioned, if one could add a URL to external media directly into elementor, without going trough the WordPress media library, this would alreday be a great help, also for people using other external media servers.

**Comment by rwillox** [comment]
Something similar for video would be useful rather than just YT or Vimeo.

Currently, use S3 and CloudFront for hosting images and other media. When media is added, S3 plugin uploads to S3 bucket and returns CloudFront url as link to media rather than storing on the server.

**Comment by gioglifx** [comment]
With the optimal practice for SEO and many other reasons, the use of a CDN is very useful and necessary for websites nowadays.  Using images and any other media that live somewhere other than your own server makes for faster loading, security plus more!  Unfortunately since there aren't that many people [ here ] that are requesting for this feature, the developers aren't considering this vital addition.  Though, at this point in 2018 - this type of feature should be a default anyway.  No real idea as why this isn't implemented and needs requests, but hopefully this gets included very soon.  The idea of adding an image widget and having the option to choose where the image is being pulled from is what I'm talking about here.  Like this: https://my_external_url"

**Comment by arielk** [comment]
I merged this issue with another issue #413 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
