### ISSUE TITLE
Bug at the forms widget

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1496]
At the forms widget the font and probably font size of the button isn't displayed correctly on the frontend. On the backend everything is fine.
![form - backend](https://cloud.githubusercontent.com/assets/14095280/24101942/75501bd6-0d7a-11e7-954b-bf14cc66cc84.JPG)
![form - frontend](https://cloud.githubusercontent.com/assets/14095280/24101941/754f154c-0d7a-11e7-97a0-1b360cbd5b53.JPG)

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by HelmutGoebel** [comment]
The problem report was false. Obviously the font is controlled by "Akzent-Text" (german version). I've never seen a documentation where "Akzent-Text" setting and "Sekundäre Überschrift" setting is applied, Nore there is a video about the global fonts and other general settings. That should be covered somehow.
