### ISSUE TITLE
"Edit with Elementor" and "Back to dashboard" buttons point to wrong pages

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#1497]
Hi guys,
i've a problem since the beginning of one of my project, the first one completely done with Elementor.
I think this is an annoying bug, as then the site will go completely in client's hands.
If you can see the administration bar, and you see the "Edit with Elementor" button, it seems that some pages point to the wrong /?elementor link.
I would give you a frontend example....

![image](https://cloud.githubusercontent.com/assets/19909323/24103477/b24891f8-0d7f-11e7-8ca6-201f137c1a0d.png)

As you can see, http://vivatek.websolution.link/erogatori-per-casa/ is my page, Elementor's edit button points to http://vivatek.websolution.link/erogatori-per-casa/addolcitore/?elementor .

![image](https://cloud.githubusercontent.com/assets/19909323/24103728/72f049e6-0d80-11e7-86bf-3280f3f79c97.png)

Same thing here, i have as address http://vivatek.websolution.link/vantaggi-erogatori-per-ristorazione/, but Elementor points to http://vivatek.websolution.link/erogatori-per-ristorazione/fonte-blu/?elementor .

The same happens on backend, where the "back to dashboard" button is clicked...

![image](https://cloud.githubusercontent.com/assets/19909323/24103914/138c744c-0d81-11e7-9b1f-bad930e34f12.png)

it points to the Wrong post ID, infact you finish:

![image](https://cloud.githubusercontent.com/assets/19909323/24104025/5bf06c48-0d81-11e7-910f-a950130414a5.png)

I think you're badly calculating the post ID after all...

**Comment by KingYes** [comment]
I think it's problem with your theme or any plugin in your website. Please change to default theme from WP and deactivate all your plugins and check if you still get this issue..

**Comment by teolaz** [comment]
Solved, i forgot to insert a wp_reset_postdata(); after having generated a shortcode...
