### ISSUE TITLE
Feature Request - Add Divider / Headings / HTML to Form Elements

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1500]
Similar to other form builders it would be nice for longer forms to have divider elements that we can add and place in between form elements so as to break longer forms up into logical sections.

Additionally, it would be nice to place titles for those sections and lastly, it would also be great if we had a way to drop in a text editor instance between form elements so we can provide images, text noticies and even a little html as needed, thx.

I can also foresee a 4th element being very handy, a page/step separator that can be dragged in between input fields allowing for a multi-step web form using ajax but I wouldn't want that to hold back the simplicity of the request above =)

**Comment by joshmarom** [comment]
Yes, we have that in mind.
Good call.

**Comment by JoelEadeDesign** [comment]
+1 for me :)

**Comment by markusila** [comment]
Use checkbox and dont put any options. Its title can be also embeded in <b> tags to be a bold title.

**Comment by bainternet** [comment]
Done in v1.13.0
