### ISSUE TITLE
Control Dependency

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#1501]
Hello,

I am creating my own Widgets, and while integration the shortcodes seems to drive somewhere, I would need some help with the following

```
array(
            "type" => "colorpicker",
            "heading" => __("Outline Button Skin", "mk_framework"),
            "param_name" => "outline_skin",
            "value" => "#444444",
            "description" => __("This option is for outline style.", "mk_framework"),
            "dependency" => array(
                'element' => "style",
                'value' => array(
                    'outline',
                    'line',
                    'fill',
                    'radius'
                )
            )
        ),
```

That is a previous from VC array. You see that I have the " dependency " value, that helps to show things, only when actually need it.
I am trying to find something similar here, but I can not. Can you please let me know if it exists?

**Comment by KingYes** [comment]
Yeha, you can do that. You just add `condition` array in your control. You can example there: https://github.com/pojome/elementor/blob/master/includes/widgets/icon-list.php#L159-L178
