### ISSUE TITLE
Elementor reusable

### ISSUE THREAD

**Issue by olivier-perrier** [pojome/elementor#1507]
Hello, 

I have a request for the improvement of the Elementor plugin.
The issue I am face to is the style heritance of the Elementor class when I am using the tool. Actually, I lose the heritance of theme CSS because I place my plugin with Elementor.

Currently the only solution is to rewrite the CSS of the theme I want it apply in my widget or not using the Elementor WYSIWYG.

A better solution should be to add the option of disable the heritance of Elementor CSS, especially fontend.css by avoiding classes in the elementor item. This functionality could be just for no Elementor widget and/or widget using none CSS property

Another question is about the generation of the CSS. The css meta is generating from the elementor data meta which one create the css file, I guess for better performance. All that work is necessary?
A really good improvement that could make the plugin much more reusable should be to use it only as a template for placing widget without adding only class or something (like page builder plugin). 
I actually really like to real time update in the interface and possibility of WYSIWYG options and of course your widgets.

Thanks for consideration, I am open to discuss. I think this plugin has a really good potential but some close features make the reusable hard.

See you,

Olivier

**Comment by arielk** [comment]
Have you read our [documentation for developers](https://github.com/pojome/elementor/tree/master/docs#hooks)?

Basically you can replace the contents of the elements using filters.
