### ISSUE TITLE
Add more icons to Icons Element

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#1513]
Hello,

I am using more icons for my elements, so I would like to load more fonts, on the fontawesame array.
Can you please let me know how can I hook to it with an example?

Thank you very much.

**Comment by arielk** [comment]
For now, this is not possible, but we plan to add this feature in the future. You can follow on this issue: #110 

Thank you for your feedback!

**Comment by Basilakis** [comment]
@arielk I can not hook and use something like the skins_init that google maps have?
https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md

**Comment by Basilakis** [comment]
@arielk any udpate to that question, based on our hooks?
Please do not close tickets before you hear back from us, or before a normal reply rate.

Your documentation has an example, I want to know why there is an option to add a skin for google maps and why that can not work for adding more icons.

**Comment by arielk** [comment]
For each of our widget you can add your own skin (Google Maps is just an example), but for adding more icons, you should also add a custom control for it.

You can learn more about it in the following docs: https://github.com/pojome/elementor/blob/master/docs/content/controls/README.md

As I wrote above, we are working on this feature for the following versions, I do not currently have a time estimate for this.

Thanks

**Comment by merianos** [comment]
@Basilakis may this can help : https://merianos.wordpress.com/2017/09/22/elementor-register-custom-font-family-in-the-fonts-control/

**Comment by Basilakis** [comment]
@merianos more than what u believe! Do you mind if I create a GIST for it?

**Comment by merianos** [comment]
@Basilakis I already did one ;)

https://gist.github.com/merianos/cb22c831d51e2566083eb6ac1adc2d9b#file-functions-php
