### ISSUE TITLE
Elementor code remains on post after disabling from Post Type

### ISSUE THREAD

**Issue by katart** [pojome/elementor#1519]
## Description

The Elementor markup is still in the front end code for a post that was edited using Elementor, even after Elementor has been disabled for the Posts post type.

## Steps to reproduce
I enabled Elementor on the Posts post type and edited a Post using Elementor. I eventually reverted back and disabled Elementor on the Posts post type. I went back to the post, edited some content using the default WordPress Editor and then clicked the Update button. 

I viewed the code on the front end and the Elementor markup is still part of the code.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 5.6.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 65M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.3
	Site URL: http://www.tigerseyeinsurance.com
	Home URL: http://www.tigerseyeinsurance.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Tiger's Eye
	Version: 1.0
	Author: KatArt Graphics
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

== Active Plugins ==
	Black Studio TinyMCE Widget
		Version: 2.3.1
		Author: Black Studio

	Coming Soon Page & Maintenance Mode by SeedProd
		Version: 5.0.9
		Author: SeedProd

	Elementor
		Version: 1.3.5
		Author: Elementor.com

	Elementor Pro
		Version: 1.2.4
		Author: Elementor.com

	Menu Icons
		Version: 0.10.2
		Author: Dzikri Aziz

	Ninja Forms
		Version: 3.0.31
		Author: The WP Ninjas

	WP Smush
		Version: 2.6.1
		Author: WPMU DEV

== Must-Use Plugins ==
	System Plugin
		Version: 3.5.0
		Author:

**Comment by katart** [comment]
Ok. The only way to get it to work is if I click on the Go Back To WordPress Editor button when Elementor is enabled and then Update the Post. Now, after disabling Elementor on the Posts post type, I can see the edits made in the Default WordPress Editor.

**Comment by arielk** [comment]
That's exactly how it should work, so I do not think there's any bug here.

**Comment by jgarcianewemage** [comment]
The bug still exists, and after you disable for posts the "edit with wordpress" editor button disappears even if you change the content IT WONT UPDATE.
so you have to rollback one by one then disable elementor for posts

**Comment by jakerodriguez-act** [comment]
This issue persists for me. These are the steps I took:

1.) Elementor Settings and disabled Elementor for my post type
2.) Opened a post within the post type and clicked the "Go Back To WordPress Editor"
3.) Removed all content within the classic WYSIWYG
4.) Removed the following post meta from the database:
_elementor_css
_elementor_data
_elementor_edit_mode
_elementor_page_assets
_elementor_template_type
_elementor_version
5.) Confirmed the Page Template is set to default
6.) Updated the post which I am trying to revert back to default
7.) Page content still persists upon viewing the page
8.) Checked the database and all the deleted post meta repopulated 
9.) Checked the Elementor settings and confirmed Elementor is still disabled for the post type

I would say this is indeed a bug
