### ISSUE TITLE
Ability to remove default margins/gaps between modules

### ISSUE THREAD

**Issue by IkeTen** [pojome/elementor#1521]
This is a feature request. The ability to remove the default margins between modules in columns would improve work flow. Elementor adds this margin bottom rule to all modules. 
.elementor-widget:not(:last-child) {
    margin-bottom: 20px;
}
One setting to remove it from between modules  would be great

**Comment by arielk** [comment]
Elementor 1.5 has already been released with this enhancement, lease update your plugin and let me know if this solved your problem.

Thanks for the feedback!
