### ISSUE TITLE
Buttons Wrapper

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#1522]
When Adding 2 buttons, on the same column
if you align them one left and one right, they do not get on the same line.
It seems that the button wrapper takes the full column width, so the aligment does not work with anything else also ( content text etc )

https://nimbus.everhelper.me/client/notes/share/829646/ymyn05rr414t2nybbiog

Is that a possible bug, or an interaction for a certain way?

**Comment by Basilakis** [comment]
Do you guys see and participate on the issues?

**Comment by Zarioza** [comment]
Hi,
try add class in button advanced options in CSS classes something like **button-inline** and then add to your css file:
`.button-inline{
    display: inline-block;
}` 
you can add margin etc,
see:
https://ibb.co/jfP1WQ

**Comment by arielk** [comment]
Each widget is 100% of the width of the column.

If you want to put two buttons next to each other, you can add a "columns" widget and insert the buttons inside.

Thanks
