### ISSUE TITLE
uneven "fade in up" effects for seperators

### ISSUE THREAD

**Issue by nicolasblume** [pojome/elementor#1523]
If you scroll through our site http://www.mmweg.rwth-aachen.de/ags/ in mobile view, the "fade in up" effects look uneven: While scrolling, some seperators appear "too early", so the following element crosses over this seperator.
I want the elements to appear in the order that they have after scrolling through the whole page in mobile view.

**Comment by arielk** [comment]
I try to understand it exactly, Is this screenshot okay? https://vid.me/Y096

**Comment by nicolasblume** [comment]
In your video it looks fine. 
Sorry, I forgot to mention: you have to scroll faster to see this unwanted effect (later appearing sections "crossing over" earlier appearing seperators) 
I hope you can see it in this video: vid.me/KuG0

**Comment by nicolasblume** [comment]
In your video it looks fine. 
Sorry, I forgot to mention: you have to scroll faster to see this unwanted effect (later appearing sections "crossing over" earlier appearing seperators) 
I hope you can see it in this video: https://vid.me/KuG0

**Comment by arielk** [comment]
For now, we have no solution for this issue, but I think if we add an option to set a speed of Animation that will solve the problem, this is something we plan to add in the future, you will be able to follow this issue #558
