### ISSUE TITLE
elementor/preview/enqueue_styles invalid results

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#1528]
```
add_action( 'elementor/preview/enqueue_styles', function() {
   wp_enqueue_style(
   	'elementor-preview-style',
   	url/to/style.css',
   	[],
   	'plugin-version'
   );
} );
```

That from the documentation, is not working properly. I have tried other variations also
```

add_action( 'elementor/preview/enqueue_styles', function() {
   wp_enqueue_style(
   	'theme-styles', THEME_STYLES . '/theme-styles.css',
   	[],
   	'style_version',
   	false // in_footer
   );
} );
```

but still I can not get it to show the theme stylesheet.
Can you please define which is the proper way for it?

Thank u

**Comment by KingYes** [comment]
Please use `elementor/frontend/after_register_styles` action to print your styles in Editor & Frontend

**Comment by Basilakis** [comment]
@KingYes still not works. Also that action does not return any result to all elementor files with a quick search.

Thank you for your reply, would love to get that shorted out, the API docs are wrong on that.

**Comment by Basilakis** [comment]
@KingYes I have tried search hole elementor and did not find anywhre that one you suggested.
Can you please check again and let me know?
I am only stuck to that and I would love to finish my work

**Comment by KingYes** [comment]
Sorry, you right. This action is for next version of Elementor.

But you need this action: `elementor/frontend/before_enqueue_styles`.

**Comment by Basilakis** [comment]
The correct seems to be

```
add_action( 'elementor/editor/before_enqueue_scripts', function() {
    wp_enqueue_style(
   	'theme-styles', THEME_STYLES . '/theme-styles.css',
   	[
   	],
   	THEME_VERSION
   );
} );
```
