### ISSUE TITLE
Elementor 1.4.0 - Beta Release (RC2 updated)

### ISSUE THREAD

**Issue by arielk** [pojome/elementor#1530]
===========
## [RC2 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/1530#issuecomment-289507786)
===========

In this upcoming version, we put the focus on making Elementor a more stable page builder, with better compatibility to other plugins and servers.

We also did a lot of coding, making everything faster. We strive to improve the designer workflow, and have added some interesting new features that are directed toward the more heavy and professional Elementor user. Users who work with Elementor on a daily basis.

**Please download the new version here, and go over each of the following new updates:**

### Maintenance mode
Set your site on Maintenance mode, and build your site without your visitors seeing it. 
If you pick Maintenance mode, the website will return an HTTP 503 response to visitors and search engines, meaning the site is temporarily down for maintenance, come back later.

If you pick Coming soon, the website will return an HTTP 200 response to visitors and search engines, meaning the site is indexable.

`Dashboard > Elementor > Tools > Maintenance mode > Coming soon / under construction `

### Elementor Canvas Template
Design the native blank page in Elementor. No header, no footer, just Elementor. 
You can set the Canvas template in the backend dashboard of WP as well as through page settings inside the editor.

`Elementor Editor > Left Hamburger Icon > Page Settings > Page Template > Canvas`

### Page Settings

- **Status**: Set the page status as draft / published etc from within Elementor
- **Page Template**: Set the page template from within Elementor
- **Hide Page Title**: Easily hide the page H1 title from within Elementor
- **Edit Page Title**: Change the text of the title from within Elementor.
If your theme uses a different selector, then you can customize the title selector through the Page Settings inside the editor

`Elementor Editor > Left Hamburger Icon > Page Settings`

### Whole Page Styling
Change the background of the your entire page, including: color, image, gradient. You an also set padding and margin.

`Elementor Editor > Left Hamburger Icon > Page Settings > Style`

### Drop cap
Make the first letter of your text editor widget a drop cap (Extra large first letter).

`Elementor Editor > Widgets > Text Editor`

### Debugger
We have added an error catcher for the editor, so you can easily understand compatibility issues and conflicts with themes, plugins, server configurations and addons.

`Dashboard > Elementor > System info > Debugger`

### More
- New icons, hover style options, animation to Social Icons widget
- Load time improvements, sequential loading for better loading on weak shared hosting servers
- <s>The "View Page" button now opens in the same window</s> (RC2 updated)

### Instructions what exactly to do
- You are invited to download the new Beta <s>RC1</s> here: (RC2 updated)
https://downloads.wordpress.org/plugin/elementor.1.4.0-RC2.zip 
- This is not a stable version and we advise to use it in your dev website. We would really appreciate if you could do as many tweaking and testing of the different options, to squeeze out any possible bugs.
- Designated time for release:  March 29, 2017

**For bugs and remarks, please reply with a comment below!**

Many thanks for your support and help!

[Elementor Beta - Sign Up Now For Our Elite Group Of Early Access Testers](https://my.elementor.com/beta/)

**Comment by Basilakis** [comment]
@arielk Are there Page Setting API, so we can add ( or remove ) elements based on our theme?
Nice addition BTW.

**Comment by pastemedia** [comment]
When I click on "View Page" it leaves the editing interface and goes to the page instead of opening a new tab

**Comment by arielk** [comment]
@pastemedia Right, this is one of the new changes.

**Comment by pastemedia** [comment]
@arielk I think the former style was better i.e. opening new tab. BTW, drop cap of text editor works fine and I love it

**Comment by arielk** [comment]
@pastemedia We received a lot of complaints about it. You can always click on the "Open in New Tab", but we'd love to hear more opinions...

Thanks

**Comment by Basilakis** [comment]
@arielk Are there Page Setting API, so we can add ( or remove ) elements based on our theme?
Nice addition BTW.

**Comment by arielk** [comment]
@Basilakis Yes, you can add or remove controls in the Page Settings

**Comment by Basilakis** [comment]
@arielk Can we read somewhere more about it and the usage, please?

**Comment by arielk** [comment]
@Basilakis We'll write about this in the API docs, currently we're focusing on bugs and compatibility for stable version.

**Comment by vertiges** [comment]
Hello, I can't get the canvas template, it's not listed in the dropdown menu... The only choice I've got is "default". (Elementor Editor > Left Hamburger Icon > Page Settings)
BTW, I'm not using the PRO version.

**Comment by arielk** [comment]
@vertiges Please try on the backend of the page (see the screenshot), If you’re still get it, please share with us the system info by using pastebin.com 
![sknvmnk](https://cloud.githubusercontent.com/assets/1778512/24334444/102d9622-1273-11e7-820e-43fae9c1513f.png)

**Comment by paaljoachim** [comment]
I am testing the Maintenance mode. 

Elementor -> Tools then testing out Coming Soon and Maintenance.
I click the create one (as in create a template that will be seen by not logged in visitors)
Create a template through Elementor. Then go back to Tools. Go to Choose a template and notice it is not listed. I go to My Library and see It is in draft mode. I click edit. Wonder what to do. I click publish. Then go back again to Tools and can now see it listed in the Choose Template drop down.

Should creating a maintenance template automatically become published? So one can right away see it in the Choose Template drop down after having created it? As right now it requires the extra step of going to My Library selecting the template which is in draft mode to then publish it.

--

Elementor Canvas Template

1. I go to a content creation of a page. Look for Page Attributes to select the Canvas template.
There are no templates to choose from. It shows only Parent and order.

2. I click Edit with Elementor.
Elementor Editor > Left Hamburger Icon > Page Settings > Template... There is no option. Only default.

3. I go to My Library.
Edit one of the saved templates. In the Post Attributes I can see the Canvas available.
IF I edit this with Elementor and there go to Page Settings -> Template. Then I will see the Canvas template available.

I retest using another local dev site with the same results.

----

Page Settings
Change title works.
Hide title works.
Template: only Default available.
Post Status looks to be working.

--

Whole Page Styling
Page Settings -> Style -> 
I add a color/image/gradient to the background but it does not show up. After clicking Apply it leaves Style and goes back to Settings.

--

Drop cap
Make the first letter of your text editor widget a drop cap (Extra large first letter).
Elementor Editor > Widgets > Text Editor
---- I can not see the icon for this in the text editor.-----

--

It is awesome that you guys have added a Debugger!
Here is a pastebin of the debugging for two sites:
http://pastebin.com/gf7TMHaf
http://pastebin.com/fgQBPu7E

--

Hover:
I added an image.
I went to Style. There really should be an area for hover (as there is an area for Caption.)
I noticed the option to add a Hover Animation.

Area could be something like this:
-> Hover
Change background color or image.
Animation
Caption (color of caption etc).
Link 
etc.

**Comment by vertiges** [comment]
@arielk : http://pastebin.com/3SnAxenS 
Exactly the same as @paaljoachim described.

**Comment by vertiges** [comment]
Page settings :

Hide Title works.
Template: only default listed.
Post Status: works.

Whole Page Styling
Page Settings -> Style ->
Everything works (all the backgrounds options, margins, padding). You have to click "Apply" to see the result. And yes, after clicking "apply", goes back to "settings".

**Comment by vertiges** [comment]
Drop Cap : amazing!

**Comment by pingram3541** [comment]
Great stuff here!

-- Page Settings (Apply)  --

I tested everything and the only issue I encountered was with the Page Settings as well.  Every setting is not applied until you press the green "Apply" button which does a full page reload vs a nice, clean ajaxy experience =)

This makes the background gradient feature a bit of a rough experience because you cannot see your changes immediately and a forced to "apply" the blind settings to see the result.

-- New Canvas Template --

I had no issues with the new template feature and I very much like that it can be applied to Library elements as well which comes in handy for maint. mode if you don't want the template showing header/footer.

Also, it was showing both in the wp-admin Page Attributes meta box as well as the Page Settings when editing in Elementor so I'm not sure what is different between my install the the two gents above but in my child theme the only override is that I am not loading the twenty-sixteen parent theme style.css because I am using StylePress Beta as well.

-- Maint Mode --

Love this feature and everything worked as expected testing both logged in users and role options as well, great job!

-- Social Icons extra icons --
TY very much!

-- Drop Cap --
Works great, took me a sec to see the little toggle in the bottom corner.  Will there be styling options to come in the future?

Here is my set up if it helps: http://pastebin.com/U4VDzEvv

**Comment by tscheipi** [comment]
### Whole Page Styling:
Ony works with Elementor Canvas. Background will be overwritten by themes background settings (e.g. in twenty seventeen there is a bg-color:white).
Missing: % etc. for margin/padding.
Annoying: missing live-preview; applying changed styles ends up in the settings-view - you have to go back to the styles to make further style-changes ... and again and again

### Drop cap:
Missing possibility to style padding (too much padding yet)

### Debugger:
Might be usefull - no errors displayed yet

### System Info:
http://pastebin.com/Hj5MvCNF

**Comment by arielk** [comment]
## Elementor 1.4.0 RC2

Elementor 1.4.0 RC2 is available for testing. This fixes a bunch of issues from 1.4.0 RC1, thanks everyone for your help and your collaboration!

Notable fixes include:
- Added **LIVE PREVIEW** for Page Settings!
- Fixed Canvas template not showing when Elementor settings have not been saved
- Added `line-height` option for default DropCap
- Added `%` and `em` options for Page Settings > Style > Padding
- Added `body` selector for better handling with some themes (like Twenty Seventeen)
- Removed Margin option from page settings style (creates conflicts)
- Restored "View Page" button to open in new tab (as it previously was)

**If you haven’t tested 1.4.0 yet, now is the time! You are invited to download the new Beta RC2 here:**
https://downloads.wordpress.org/plugin/elementor.1.4.0-RC2.zip

For bugs and remarks, please reply with a comment below!

**Comment by arielk** [comment]
@paaljoachim @vertiges @pastemedia @pingram3541 @tscheipi new version is available with your comments, please update.

**Comment by cowdar** [comment]
SiteOrigin widget is not working with the update

**Comment by pingram3541** [comment]
@arielk  - I'm experiencing several issues with the Page Settings if one has not used the Elementor builder yet for that page.  For example, if i create a new page and go straight to the Page Settings, the upper green Apply button doesn't work as expected nor does output on the front end.  However, once I add a section, save and then delete that section, I can proceed making Page Setting changes that will take effect on the front end, however the upper green Apply button still remains green.  Here are the details:

-- Title - works but with a quirk --

Changing the title text is immediate in the preview however the green Apply button isn't working quite right.  Clicking it doesn't change it from "green" to grey but the setting does appear to change the title regardless of whether one has used the builder yet.


-- Hide Title - works in preview, broken on front end --

This works immediately in the preview which is great but same as above, the green Apply button remains green AND the title is not hidden on the front end.  Inspecting the code I do not see anything that would suggest how this is achieved.  The entry-tittle element has no Elementor rules applied to it nor do I see any css files from Elementor for my page in /wp-content/media/...

This was later discovered to work so as long as you have saved something in the Editor first.  once that has happened at least once on a page, this setting does indeed work on the front.


-- Template - works but could be better --

Change is immediate in the preview however this also fires a "save" immediately so if you want that to take effect immediately great but many I am sure would prefer to preview this first before applying to the live site.


-- Post Status - works but with quirk --

Appears to work perfectly except again for the green Apply button not becoming grey to indicate the save actually completed.  Checking the back/front end, each change appears to save as it should.


-- Background Type / Padding Controls - broken --

- Initially I didn't see any of the control icons.  I had to refresh.
- Changing background color, gradient, image etc all work in the preview but I am not getting any css on the front end.
- Same issue w/ green Apply button, shows the save progress bar upon click but never goes grey to indicate the save completion.
- There is no background overlay option but I could see this effect being desirable.

Again, once content is actually saved in the editor, this works.


-- Delete All Content - works, but with quirk --

When choosing this option, the page settings are not reset along with the editor content.  The chosen background settings, hidden title and padding all remain unaffected by this setting and are not reset.


https://pastebin.com/0CQBH2zx

**Comment by lukecav** [comment]
@arielk 

Any reason why 1.4.0 RC2 is not tagged as a release?
https://github.com/pojome/elementor/releases

Similar to WC and then add a pre-release tag to it.
https://github.com/woocommerce/woocommerce/releases/tag/3.0.0-rc.2

**Comment by WPDevHQ** [comment]
The Canvas template issue is still persistent on New Pages unless I go to Elementor Tools and click save there - revisiting a brand New Page write screen only then do I see the template.

**Comment by paaljoachim** [comment]
Another test.
I made a new page. Clicked to edit the page. 

1. Elementer Canvas is now seen under the Page Attributes in the page content screen. (In RC1 it was not seen.)

2. I click Edit with Elementor.
Elementor Editor > Left Hamburger Icon > Page Settings > Template. I can now choose Elementor Canvas. (In RC1 it was not seen.)

--

Testing Page Settings -> Page Style.
Color shows.
Image: Testing multiple images adjusting position, attachment and no-repeat.
**Bug:** The first image I used is still seen even though I tested other images and saved. I removed the image and the color I used is then seen. (I was using the theme Elementorist.)
I repeated the same test using Twenty Seventeen with the same result. This means testing multiple images the frontend shows the first image tested. Clicking delete and then selecting a new image the new image is seen.
NB! 
I also tested gradient and it seems to be stuck on the first image, as the gradient is not showing.
Deleting the image the gradient will now show. 


I switched to Twenty Seventeen. Edit in Elementor. Added no section or columns but adjusted the Page Settings to include a background image and a lot of padding to see the background image outside of the white theme background color. Saved and checked the page. 
**Bug:** Edit Elementor page and just adjusting the Page Settings and saving. Any adjustment is then not seen when viewing the page on the regular frontend view.
Adding just an empty section the page settings come into effect and are seen on the frontend.

Dropcap:
Line-Height. Minimum are 3 lines dropped. The minimum should be 1. Default could start at 3. The user can then adjust it down or up.

A side note to the testing.
There are Global Colors and Global Fonts in the regular version but the addon Pro version will then add the Global Section. They seem tied together. (I have still not purchased the Pro addon so that I can take a closer look at it.)

Since the new version includes the possibility to remove any remains of the existing theme such as site branding and copyright notice at the bottom of the page. It would be good to include Elementor widgets for these areas.

**Comment by WPDevHQ** [comment]
Editing a page with the default template and the content isn't where it's supposed to be!
![pageondefaulttemplate](https://cloud.githubusercontent.com/assets/16872407/24376415/b99c0750-1333-11e7-84fa-7b48b41000b0.png)

**Comment by WPDevHQ** [comment]
More screenshot FYI
![odd goings on](https://cloud.githubusercontent.com/assets/16872407/24376836/39b024d4-1335-11e7-9569-909652c3ee1a.png)

![more quarks](https://cloud.githubusercontent.com/assets/16872407/24376857/4ca186aa-1335-11e7-9276-dba4522fb352.png)

**Comment by WPDevHQ** [comment]
Revisiting the page from the dashboard and refreshing it in the Editor gets the color going on the front end.

**Comment by tscheipi** [comment]
### Whole Page Styling:
still the same: _**.site-content-contain** color_ overwrites _**body.elementor-page-391** color and image._
btw: it´s ok with the elementor canvas template

**Comment by arielk** [comment]
@cowdar, Thanks, we'll look into it.

@pingram3541, First of all we going to remove this APPLY button and moving to Auto Save, so all problems with this button are irrelevant

About the Revision History and Delete all content: the page settings is not connected to the content of the page. You can delete all content, and page settings will remain the same. ( it is saved in separate post meta so it's not affiliated with the content)

@lukecav, You're right, we'll do it in the next version, thanks for your advice.

@paaljoachim, @tscheipi, Some themes like TwentySeventeen can be a bit tricky, but it always works fine with the new Canvas template

**Comment by arielk** [comment]
1.4.0 released
