### ISSUE TITLE
Automatically "Regenerate Files" after Database Migration

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#1537]
Hello!

My standard workflow for client sites, like a lot of devs, is to work on localhost then push changes up to a remote site for review. With each push of the database to the remote site, using WP Migrate DB Pro, I have to log into the remote site, go to Elementor > Tools and click Regenerate Files in order for the CSS to be regenerated and for the local and remote sites to be in sync.

Is there a link or an action that I can use with WP Migrate DB Pro's post-migration action, [wpmdb_migration_complete](https://github.com/deliciousbrains/wp-migrate-db-pro-tweaks/blob/master/wp-migrate-db-pro-tweaks.php), to trigger the Regenerate Files process?

**Comment by KingYes** [comment]
Just use this method: `\Elementor\Plugin::$instance->posts_css_manager->clear_cache();`.

**Comment by JoelEadeDesign** [comment]
Thanks @KingYes!
