### ISSUE TITLE
URL change tool does not affect certain widgets

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#1538]
hy,
i just used the url canger tool after moving my site from http to https. it said that a certain number of rows were affected, but afterwards i noticed issues:
- the background image of the slides widget are not affected
- if i have "link to file" activated for an image widget, this link is not affected
- as well an internal link on an image widget is not affected
- an internal link on a button is also not affected

is this not a search/replace over the whole database tables with elementor content?

thanks, matt

**Comment by matipojo** [comment]
Hi @matthiaswagnerwy, 
Please paste your system info from Dashboard > Elementor > System info

**Comment by matthiaswagnerwy** [comment]
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.33
	PHP Version: 7.1.1-nmm1
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.3
	Site URL: https://www.wwl-steiner.at/wp2017
	Home URL: https://www.wwl-steiner.at
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Vienna
	Debug Mode: Inactive

== Theme ==
	Name: WWL Steiner (Sitepoint Base)
	Version: 1.0
	Author: Sitepoint
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE_formal
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.3.5
		Author: Elementor.com

	Elementor Pro
		Version: 1.2.4
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.5
		Author: Till Krüss

	EWWW Image Optimizer
		Version: 3.2.7
		Author: Shane Bishop

	Language Fallback
		Version: 1.0.3
		Author: Bernhard Kau

	MainWP Child
		Version: 3.3
		Author: MainWP

	UpdraftPlus - Backup/Restore
		Version: 1.12.35
		Author: UpdraftPlus.Com, DavidAnderson

	WP Mail Logging
		Version: 1.8.0
		Author: Christian Zöller

	Yoast SEO
		Version: 4.5
		Author: Team Yoast

**Comment by matipojo** [comment]
Hi, @matthiaswagnerwy 
Can you regenerate the css and tell if it helps?
Dachboard > Elementor> Tools > Regenerate CSS

**Comment by matthiaswagnerwy** [comment]
hy,
i already changed the urls manually as it was not much work, and as it is a live site i do not want to play around there :/ for me it looked like these fields were just not affected by the search/replace...

**Comment by matipojo** [comment]
OK, in our test environment it works as well. So for now it seems to work fine. If it occurs again please let as know.

**Comment by matthiaswagnerwy** [comment]
alright, strange behaviour...
