### ISSUE TITLE
Editing an existing page scrolls when selecting a section/column/widget

### ISSUE THREAD

**Issue by markd-apadmi** [pojome/elementor#1544]
## Description

When editing a page with multiple sections, clicking in the section or column labels scrolls the page to the first section.  This also happens when you edit a widget in any section other than the first.  If you add a new section then that can be selected without the scrolling issue.  If the page is saved and edited again then the new section now has the scrolling issue.

We are currently trialling Elementor for use on landing pages and these can be quite long.  This issue becomes a major annoyance when the page gets long.

## Steps to reproduce

Create a page.  Add multiple sections with some content.  I created 3 instances of a full height section containing a "Heading" widget.  I changed the colour of the 2nd section to make it easier to see.

Clicking on the section or column selectors stays on the respective section or column and displays the details in the side panel..

Save the page.

Go back to the page list and select the page you just created.  Select "Edit with elementor" from within the page editor.  The issue also occurs if you select "edit with elementor" from the quick menu.

Scroll down to the last section and click on the column or section selector.  The page is scrolled so that the first section is in view.  The selected section details are displayed in the panel.

Add another section at the bottom of the page.  Again add some content.  Clicking the section selector correctly stays put and displays the section data in the panel.  

Save and reload the page and the newly added section now has the same problem.

This can also be recreated using the built in page templates by inserting the template, saving the page and then reloading to edit.

## Environment

This is on our development VM running Ubuntu 14.04 linux, Wordpress 4.7.3 and Elementor 1.3.5.  There is no external access to this box.

**Comment by arielk** [comment]
Does this issue still occur in v1.4.2 of Elementor?

**Comment by markd-apadmi** [comment]
Hi Arielk.  

I going to close this as it appears to be an issue with some custom code written for our theme.  I'm not sure why we have this bit of code but if I disable it the problem goes away.

Thanks for getting back to me.
