### ISSUE TITLE
[Bug] Page Settings can't be saved (v1.4.0)

### ISSUE THREAD

**Issue by agusmu** [pojome/elementor#1546]
## Description

Page Settings can't be saved, especially background styles when we edit page settings only, without editing any existing elements on editor.

## Steps to reproduce

Case 1 (OK, page settings can be saved)

1. Edit existing elementor page
2. Edit background styles on page settings
3. Edit any existing element on editor
4. Click save button 

Case 2 (NOT OK, page settings can not be saved)

1. Edit existing elementor page
2. Edit background styles on page settings
(Do not edit any existing element on editor)
4. Click save button 

## Note 

I can see that when you edit any existing element, the save editor button changes to "green". 

But when you edit page settings ONLY, the save editor button doesn't change to "green".

**Comment by cobicarmel** [comment]
Page settings are saved automatically. You don't need to click the save button for saving the settings.

**Comment by ramiy** [comment]
@cobicarmel @arielk
the changes are saved on the data base but the user don't see the changes being updated on the page. For some people it's very confusing. I hear complains too.

I think the best solution is to add an "**update changes to page**" BUTTON like the one you have on the Shortcode Widget. This will force Elementor to update the preview with updated content.

![update-changes](https://cloud.githubusercontent.com/assets/576623/24584283/3d2b10a2-1771-11e7-9d71-0d8193f1bdbf.png)

It's also a good solution for dynamic widgets like the widgets in my "[Press Elements](https://wordpress.org/plugins/press-elements/)" plugin that display post elements.

When updating post fields from the elementor "Page Settings" pannel, the data is not updated on the page. With the new button to update changes to page will resolve all the issues.

**Comment by ryanlabelle** [comment]
@ramiy Thank you. So the button would invoke a "save changes" and also previewReload()? and this would be in the page settings panel? 

That would be amazing!

**Comment by ramiy** [comment]
Amazing and very intuitive for non-techy users!

**Comment by ryanlabelle** [comment]
It's been a real pleasure working with Elementor from the frontend to the api. Your team is adding great new features. I'm very pleased to see you making it developer friendly too.

**Comment by arielk** [comment]
This issue has been resolved in b1.4.1 by auto-save every 3 sec. please update.

**Comment by ryanlabelle** [comment]
Thank you. I needed it to refresh the preview as well so I tapped into the onchange event. 

https://github.com/pojome/elementor/issues/1556#issuecomment-291003600

**Comment by ramiy** [comment]
@arielk It saves the data on the server every 3 sec, but it doesn't update the Elementor preview screen. [Press Elements](https://wordpress.org/plugins/press-elements/) widgets display the old title.

**Comment by kobizz** [comment]
@ramiy see #1586

**Comment by ryanlabelle** [comment]
Thank you.
