### ISSUE TITLE
Suggestions for Sticky Header / Section

### ISSUE THREAD

**Issue by wmarsh95** [pojome/elementor#1555]
Hi, 

I was wondering if you guys could implement the feature to the sections to not be fixed but scrolling long with the user. What I'm suggesting can be found in the Tora theme by Theme Blue. Here's the demo: [https://theme.blue/tora-demo/]. Thanks!

Will

**Comment by arielk** [comment]
I merged this issue with another issue #72 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by wmarsh95** [comment]
Hey @arielk,

I didn't really mean the background of the section. I meant the section actually traveling with the person. So like the section where it would be the header of the site title and menu slightly fading background traveling down with the user.

**Comment by wmarsh95** [comment]
https://theme.blue/tora-demo/. This theme has I what I am suggesting. If you scroll down the page, the site title and menu comes with you.

**Comment by arielk** [comment]
Did you mean "Sticky Header"?

**Comment by wmarsh95** [comment]
Yes, sorry I couldn't remember the right name.

**Comment by themedleb** [comment]
And sticky column/element.

**Comment by parfilov** [comment]
@arielk I'll paste my suggestions here to not create new issue.

- Sticky on scroll top — when scroll down sticky section is hidden, scroll up — is appear.
- Sticky appear effects — fade, shrink or something else.
- Different background state for usual and sticky. For example, transparent header, but with background on sticky.

Thanks!

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
Available since Elementor Pro v2.0
