### ISSUE TITLE
CHOOSE control on Page Settings - Would like to reloadPreview on change.

### ISSUE THREAD

**Issue by ryanlabelle** [pojome/elementor#1556]
I've added a custom CHOOSE control for a sidebar on the page settings panel, I'd love to know if I can reloadPreview() on change just like the Templates Select you have added. Any suggestions?

https://cl.ly/002O3T2Q393y

Basically when I select your template select list, the preview reloads to show the new template, I would like to fire the same event when I choose different sidebar options.

Here is my code:

`add_action( 'elementor/element/page-settings/section_page_settings/before_section_end', function( $element, $args ) {

    $element->add_control(
        'th_page_layout',
        [
            'label' => __( 'Sidebar', 'your-plugin' ),
            'type' => \Elementor\Controls_Manager::CHOOSE,
            'default' => 'full',
            'options' => [
                'left'    => [
                    'title' => __( 'Left', 'your-plugin' ),
                    'icon' => 'fa fa-long-arrow-left',
                ],
                'full' => [
                    'title' => __( 'No Sidebar', 'your-plugin' ),
                    'icon' => 'fa fa-times',
                ],
                'right' => [
                    'title' => __( 'Right', 'your-plugin' ),
                    'icon' => 'fa fa-long-arrow-right',
                ],

            ],
            'return_value' => 'yes',
        ]
    );
}, 10, 2 );`

Thank you so much of your help. We are big fans of this builder and we hope to release a new theme  that will help promote it.

**Comment by ramiy** [comment]
Related: https://github.com/pojome/elementor/issues/1546#issuecomment-290963268

**Comment by cobicarmel** [comment]
You can use the `elementor.pageSettings.addChangeCallback()` method. This method allow you to bind custom behavior for your field after every change. Then you can reload the preview using the `elementor.reloadPreview()` method.

Here is an example:

```JavaScript
elementor.pageSettings.addChangeCallback( 'th_page_layout', function( newValue ) {
    // Here you can do as you wish with the newValue
    elementor.reloadPreview();
} );
```

**Comment by ryanlabelle** [comment]
@kobi-zaltzberg , thank you. I was looking for something like this. This solves my issue. I'll test today.  👍

**Comment by ryanlabelle** [comment]
I would like to share my code for anyone else that is trying to do this. A big thank you to @kobi-zaltzberg for helping me connect the JS.

I've added two new controls, transparent header and page layout (https://cl.ly/002O3T2Q393y)

Right now I'm not checking the newValue but I might do some validation in the future. 

Everything works well. :)

PHP
`// Add custom controls to the Page Settings inside the Elementor Global Options.

if ( ! function_exists( 'th_add_custom_controls_elem_page_settings' ) ) {
    function th_add_custom_controls_elem_page_settings($element, $args)
    {
        $element->add_control(
            'themo_transparent_header',
            [
                'label' => __( 'Transparent Header', 'your-plugin' ),
                'type' => \Elementor\Controls_Manager::SWITCHER,
                'default' => '',
                'label_on' => __( 'On', 'your-plugin' ),
                'label_off' => __( 'Off', 'your-plugin' ),
                'return_value' => 'on',
            ]
        );

        $element->add_control(
            'themo_page_layout',
            [
                'label' => __( 'Sidebar', 'your-plugin' ),
                'type' => \Elementor\Controls_Manager::CHOOSE,
                'default' => 'full',
                'options' => [
                    'left'    => [
                        'title' => __( 'Left', 'your-plugin' ),
                        'icon' => 'fa fa-long-arrow-left',
                    ],
                    'full' => [
                        'title' => __( 'No Sidebar', 'your-plugin' ),
                        'icon' => 'fa fa-times',
                    ],
                    'right' => [
                        'title' => __( 'Right', 'your-plugin' ),
                        'icon' => 'fa fa-long-arrow-right',
                    ],

                ],
                'return_value' => 'yes',
            ]
        );
    }
}
add_action( 'elementor/element/page-settings/section_page_settings/before_section_end', 'th_add_custom_controls_elem_page_settings',10, 2);`

JS
`// Page Settings Panel - onchange save and reload elementor window.
    if ( undefined !== elementor.pageSettings ) {

        elementor.pageSettings.addChangeCallback( 'themo_page_layout', function( newValue ) {
            // Here you can do as you wish with the newValue

            this.save( function() {
                elementor.reloadPreview();

                elementor.once( 'preview:loaded', function() {
                    elementor.getPanelView().setPage( 'settingsPage' );
                } );
            } );
        } );

        elementor.pageSettings.addChangeCallback( 'themo_transparent_header', function( newValue ) {
            // Here you can do as you wish with the newValue

            this.save( function() {
                elementor.reloadPreview();

                elementor.once( 'preview:loaded', function() {
                    elementor.getPanelView().setPage( 'settingsPage' );
                } );
            } );
        } );

    }`

**Comment by xttn** [comment]
Hi, i have few question
1, How to change piority my custom control `Transparent Header`
![image](https://i.imgur.com/KY8iy1f.png)
2, Where i can enqueue the js file?
Thank

**Comment by ryanlabelle** [comment]
We've added a control for this "Transparency Header" as well as an alternative logo for the header. Check out. https://github.com/ryanlabelle/th-widget-pack for a sample.

https://cl.ly/0M2z3t1t3g38

**Comment by nicmare** [comment]
> I would like to share my code for anyone else that is trying to do this. A big thank you to @kobi-zaltzberg for helping me connect the JS.
> 
> I've added two new controls, transparent header and page layout (https://cl.ly/002O3T2Q393y)
> 
> Right now I'm not checking the newValue but I might do some validation in the future.
> 
> Everything works well. :)
> 
> PHP
> 
> ```
> // Add custom controls to the Page Settings inside the Elementor Global Options.
> 
> if ( ! function_exists( 'th_add_custom_controls_elem_page_settings' ) ) {
>     function th_add_custom_controls_elem_page_settings($element, $args)
>     {
>         $element->add_control(
>             'themo_transparent_header',
>             [
>                 'label' => __( 'Transparent Header', 'your-plugin' ),
>                 'type' => \Elementor\Controls_Manager::SWITCHER,
>                 'default' => '',
>                 'label_on' => __( 'On', 'your-plugin' ),
>                 'label_off' => __( 'Off', 'your-plugin' ),
>                 'return_value' => 'on',
>             ]
>         );
>         $element->add_control(
>             'themo_page_layout',
>             [
>                 'label' => __( 'Sidebar', 'your-plugin' ),
>                 'type' => \Elementor\Controls_Manager::CHOOSE,
>                 'default' => 'full',
>                 'options' => [
>                     'left'    => [
>                         'title' => __( 'Left', 'your-plugin' ),
>                         'icon' => 'fa fa-long-arrow-left',
>                     ],
>                     'full' => [
>                         'title' => __( 'No Sidebar', 'your-plugin' ),
>                         'icon' => 'fa fa-times',
>                     ],
>                     'right' => [
>                         'title' => __( 'Right', 'your-plugin' ),
>                         'icon' => 'fa fa-long-arrow-right',
>                     ],
> 
>                 ],
>                 'return_value' => 'yes',
>             ]
>         );
>     }
> }
> add_action( 'elementor/element/page-settings/section_page_settings/before_section_end', 'th_add_custom_controls_elem_page_settings',10, 2);
> ```
> 
> JS
> 
> ```
> // Page Settings Panel - onchange save and reload elementor window.
>     if ( undefined !== elementor.pageSettings ) {
> 
>         elementor.pageSettings.addChangeCallback( 'themo_page_layout', function( newValue ) {
>             // Here you can do as you wish with the newValue
> 
>             this.save( function() {
>                 elementor.reloadPreview();
> 
>                 elementor.once( 'preview:loaded', function() {
>                     elementor.getPanelView().setPage( 'settingsPage' );
>                 } );
>             } );
>         } );
> 
>         elementor.pageSettings.addChangeCallback( 'themo_transparent_header', function( newValue ) {
>             // Here you can do as you wish with the newValue
> 
>             this.save( function() {
>                 elementor.reloadPreview();
> 
>                 elementor.once( 'preview:loaded', function() {
>                     elementor.getPanelView().setPage( 'settingsPage' );
>                 } );
>             } );
>         } );
> 
>     }
> ```

copied your code but custom fields do not appear nor any errors. does the code actually works in 2020?

**Comment by ryanlabelle** [comment]
Yes. The source code may have been updated but you can find our public repo here: 

https://github.com/themovation/th-widget-pack
