### ISSUE TITLE
Shape divider width

### ISSUE THREAD

**Issue by Ryan147** [pojome/elementor#1557]
The shape divider expands to full width of the browser even though the layout has a fixed width. This makes for a weird layout in full screen desktop mode.

**Comment by arielk** [comment]
If you want to apply the shape to a narrower width, you can use the Columns widget for this and set the content width > boxed.

**Comment by Ryan147** [comment]
Shape divider follows the settings of sections and not columns if I understand it correctly.

**Comment by arielk** [comment]
Columns widget behaves like an inner section, so you should get most of the settings as the regular section.

**Comment by Ryan147** [comment]
Ah I see what you mean. It is a column within a column. I was indeed able to set the shape at the appropriate width. Thank you @arielk!
