### ISSUE TITLE
Feature request: 404 page

### ISSUE THREAD

**Issue by Ryan147** [pojome/elementor#1558]
Elementor now allows for a coming soon / maintenance mode page.

Would be nice if there is also an option for a 404 page.

**Comment by ramiy** [comment]
@Ryan147 

Elementor has no builtin support for coming soon / maintenance mode page.

I think you are using a plugin for that, on the custom theme that support this feature.

**Comment by Ryan147** [comment]
@ramiy 

Changelog

1.4.0 – 28.03.2017

New! – Canvas: Native Blank Page Template. No header, no footer, just Elementor
New! – Maintenance Mode for Under Contraction and Coming Soon page

**Comment by Ver3** [comment]
+1 for the custom 404-page (maybe even the search page)

One of my themes (OceanWP) lets me select an Elementor Library Item to use as 404-page. My other themes (Astra en GeneratePress) do not have this. Would be awesome if you could set it just like Maintenance Mode and Under Construction, in settings.

This way I can set it in my default local install to be used in all new sites.

**Comment by bainternet** [comment]
closing in favore of #3826 

thanks everyone.
