### ISSUE TITLE
Add Section "button" in the Section Tab

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#1560]
[Feature Request]
 If you are in the process of creating a long page and don't remember to add in an unused blank section now and again (that you have to clean up later), adding a new section at the bottom can be a pain. I know you can duplicate a section but then you have to delete the content from it and that slows you down. Could we have a "+" button on the section tab that adds a new section (it could default to the single column) either above or below the section where you clicked the "+"?

**Comment by arielk** [comment]
Thanks for your feedback!

I merged this issue with another issue #1564 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.
