### ISSUE TITLE
Column / section layout consistency question.

### ISSUE THREAD

**Issue by Ryan147** [pojome/elementor#1561]
When I have 1 section and 1 column and I add another column Elementor shows I have 2 different sections next to eachother.

This layout is differently when I add the column element which is basically: 2 columns in a seperate section which again is in a section as well.

**Comment by arielk** [comment]
I try to understand more what you mean, can you please add a screenshot of the issue?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
