### ISSUE TITLE
Feature request: enable/disable elements per device

### ISSUE THREAD

**Issue by Ryan147** [pojome/elementor#1562]
Being able to enable/disable sections/columns per device (desktop, tablet, mobile)

**Comment by Basilakis** [comment]
You do not need that ( and it is funny how you overflowed github with issues. Please do less, so we can actuyally have some help to things that matter, like creating elements for you ).

You can make some classes and assign to elements, with CSS.
For mobile, you can have a class called " hide_mob " and have a display:none;

**Comment by Ryan147** [comment]
Yes thank you for pointing out that many things can be done in CSS. Sorry for having overflowed github with requests/issues. Perhaps github allows for hide_ryan147, display:none; as well.
