### ISSUE TITLE
Feature Request : Add section above or below an existing section

### ISSUE THREAD

**Issue by anandau** [pojome/elementor#1564]
Hi Team Elementor

As per feedback from Elementor Community a lot of time we have to struggle when we have to add a section in between  existing section or at the top of all section. 
Only way is to add section at the bottom and drag it to desired place. It is very annoying and difficult also a lot of time.

I have a suggestion to get around this situation. I just have a UI mockup and want to know from you guys if it can be implemented. It yes, then it will provide great ease.
![elementor-suggestions2](https://cloud.githubusercontent.com/assets/376489/24503485/f2e9766c-156f-11e7-8538-60a0d0d00d56.jpg)
![elementor-suggestions1](https://cloud.githubusercontent.com/assets/376489/24503486/f32e2618-156f-11e7-8196-62ec54f547bd.jpg)

**Comment by WPDevHQ** [comment]
Cross referencing: https://github.com/pojome/elementor/issues/1560

**Comment by Basilakis** [comment]
+1

**Comment by ramiy** [comment]
The **moving buttons** are nice, but the **adding buttons** are confusing - you have the duplicate button for that.

**Comment by pastemedia** [comment]
yes, moving sections up and down is an issue and sometimes, I cannot drag the section to above at all

**Comment by paulherzlich** [comment]
I like this suggestion.

**Comment by bainternet** [comment]
Well since 1.5 we've added the plus (+) button.

as for up/down, maybe we will look into it if we see a large demand for it.
thanks.

**Comment by rwill007** [comment]
Yes, there's a large demand. Moving sections between sections is a pain

**Comment by panopticdesign** [comment]
This is a required function and should be added. Thank you.

**Comment by Basilakis** [comment]
@bainternet can u re open it? How u will see big demand if you close a ticket?

**Comment by paulherzlich** [comment]
It is closed because a solution has been implemented. Click on the + at the top of any section and you generate a section above this one, which is below the previous one. After the last section you have the Add Section / Add Template buttons to insert a section after the last one. It seems to me that all this works fine. Start a new request if you don’t think so and perhaps you should say why you don’t like the current solution.

**Comment by panopticdesign** [comment]
paulherzlich: Thank you for the prompt reply. I now see the "+" option within the section top. This is a 
perfect solution and it seems to work really well.

![add-section](https://user-images.githubusercontent.com/6885910/39652682-64b5298a-4fbc-11e8-94ac-b121079aa9c4.jpg)
