### ISSUE TITLE
Meta Data doesn't come through on Pro Form emails

### ISSUE THREAD

**Issue by dtbaker** [pojome/elementor#1566]
I have this selected:

![image](https://cloud.githubusercontent.com/assets/543073/24509443/bf1d19bc-15a9-11e7-896f-005097577b60.png)

but the email doesn't contain these meta values:

![image](https://cloud.githubusercontent.com/assets/543073/24509483/d6386fca-15a9-11e7-8e05-53892cd7a54a.png)

I really need the current page URL coming through

**Comment by dtbaker** [comment]
It seems the default don't make their way through to `ajax_send_form`

You have to remove the "Meta Data" fields and add them again before they work. Same goes for other defaults (required etc..) that you have to toggle before they are actually applied.

**Comment by matipojo** [comment]
Hi, @dtbaker, Thanks for your feedback.
We already fixed it in Elementor Pro 1.3. It will be release in the next coming weeks.
