### ISSUE TITLE
Javascript Rendering

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#1567]
Hello everyone,

I and developing some elements.
Every single of them work fine, except of those that are related to JS.
My Slider for example ( swiper slider ) is not working right.
When I load the shortcode ( and I have rendered the JS of the theme to the ?elementor edit page also )
when I change shortcode, it is not updating the elements as should. 
Even if I update the page manually ( for checking ) it is not working.

Do I really need to move all the JS at rending() or there is an easier way to do that?

**Comment by Basilakis** [comment]
Example:

```
/* Fix isotop layout */
function isotop_load_fix() {
    if ($.exists('.mk-blog-container') || $.exists('.mk-portfolio-container')) {
        $('.mk-blog-container>article, .mk-portfolio-container>article').each(function(i) {
            $(this).delay(i * 100).animate({
                'opacity': 1
            }, 100);

        }).promise().done(function() {
        	setTimeout(function() {
        		$('.mk-theme-loop').isotope('reLayout');
        	},500);
        });
    }

};
```

and it runs inside $(window).load(function() { }

**Comment by KingYes** [comment]
Hey @Basilakis,

I just write new commit on our example plugin with your request. You can see this: https://github.com/pojome/elementor-hello-world/commit/9e11c31c67440fa3be7e3a35df196d7b049a74cd

**Comment by Basilakis** [comment]
Thank you very much for that.
I will go through it!

/respect

**Comment by Basilakis** [comment]
@KingYes actually one thing:

frontend/element_ready/hello-world.default

what isthe hello-world.default I can not locate the existing anywhere else. Should it be something else?

**Comment by KingYes** [comment]
`frontend/element_ready/{{WIDGET_NAME}}.{{SKIN_NAME}}`

In regular widget the `SKIN_NAME` is `default`.

**Comment by Basilakis** [comment]
@KingYes 
Question.
Can I load all my JS, so I do not do that for each function with that way?
Generic load of all the file properly?

**Comment by KingYes** [comment]
Yeha, sure. Just embed your JS, and write your code under trigger `elementor/frontend/init` on `window` object.

**Comment by Basilakis** [comment]
Hey @KingYes 

I have loaded all my functions into the frontend/init and, first time it loads, everything is working fine.
Although, if I change lets say from

" Scroller " effect ( that needs isotop_load_fix() ) on the window, if I try to go at " Slider " which again needs it, the results do not work to re-call it, only if I save and refresh page.

Is there a solution on that implemented, which I could use?

Thanks a lot

**Comment by Basilakis** [comment]
@KingYes 
Can I get a hand of help here, if possible? :)
While it works when I re-load the page, it does not work on DropDown triggering.

**Comment by atashinbar** [comment]
Thank you @KingYes . My problem solved
