### ISSUE TITLE
Feature request: : copy paddings and margins from one section to another with one click

### ISSUE THREAD

**Issue by hartiberlin** [pojome/elementor#1569]
Feature request: : Please put a function in there to copy padding and margins from one section to another
section and also copy all paddings and margins from the inner elements of this section to...

So if you have already made 8 sections, where you already have different content inside
multiple columns and text editor boxes, but you have screwed up the paddings and margins in several of them... just go to the sections, where paddings and margins are set right for all elements and
copy them with one click and assign them to the other 7 sections...
That would really save a lot of time to build bigger sites...
Many thanks.
Regards, Stefan.

**Comment by arielk** [comment]
I merged this issue with another issue #1479 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
