### ISSUE TITLE
Add video, audio or PDF support for Media control

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#1573]
Hey Guys,

What is the option to upload custom file ( not media ).
It seems that there is no one? I am trying to have option for custom videos and I do not want to use Youtube or Vimeo for them.
There is no such option?

**Comment by arielk** [comment]
If you want to upload a media file, you can upload your video by WP media and embed the video by the native shortcode: https://codex.wordpress.org/Video_Shortcode

**Comment by Basilakis** [comment]
Yea, and that is so nice for users, I mean I am making the element and I will tell them " Hey guys you know my theme is so powerfull, if you want to add video uplaod from the media gallery and after use the shortcode ".

**Comment by arielk** [comment]
I just want to be sure I understand correctly. Are you looking for a way to **develop a widget** that enable to embed video from the WP media?

Basically we have a plan to add in the future to add this option into the existing video widget.

**Comment by Basilakis** [comment]
@arielk Lets say I want to upload a video, so I can have my own Video Player, or a custom Video Player element. Or, a PDF reader.

What we can use on that to make it work?
Upload Image field could not work for that.

**Comment by arielk** [comment]
For now, you can use a media control only for an image, but maybe it's something we'll add in the future.

You can read more about the Developer API here: https://github.com/pojome/elementor/blob/master/docs/content/controls/_media.md

**Comment by Basilakis** [comment]
Media element, adds a ' preview ' of image below to the elements, so when it is not image, it is blank there. Not so friendly to be honest.
If there was an option to disable that, then media could be used for any type - or if based on the type ( Image, Video, File ) could so a different previewer. That could make the element better.

**Comment by camilosw** [comment]
Any update on this? I need to create a widget that allow to add a list of downloadable documents (pdf, doc, ppt, etc.).

**Comment by bainternet** [comment]
You can now extend the [media control](https://code.elementor.com/classes/elementor-control_media/) and apply a JavaScript handler as described in the [developers docs ](https://developers.elementor.com/creating-a-new-control/#Control_JS_file)

thanks.

**Comment by jezweb** [comment]
Being able to insert a button element and upload the pdf at that point rather than going via the media library would be much easier for users to understand and save a bunch of clicks and time.

**Comment by bompus** [comment]
I have the same request from my users. They want to insert a button (or link) and then have the ability to upload/link to the media item directly from within Elementor.

It would be good if they could easily link to a media library item by picking it from a list. It would be even better if they could upload to the media library from within Elementor and then select the item they uploaded.

This would solve many of my headaches as I am constantly being asked why they have to leave Elementor, upload a media item, get the URL, then go back into Elementor to use it, for each link or button they want to use on a page.

Hope that helps outline my use case!

**Comment by CaerCam** [comment]
This has been a long-time request from most of my clients, so I took a couple of hours to build a small plugin that makes this possible.

Basically the plugin filters the parameters of the autocomplete search to add attachments to the list, so users can find media by searching titles just like they do for pages/posts. The plugin also adds the media type to the results instead of 'Media File' to make it easier to find relevant files. I don't really plan to add the possibility to upload media as searching for files is simpler and seems easier for users, but I might consider it if my clients feel the need for it.

I've just submitted the plugin to the official WordPress plugin repository, meanwhile you can find here: https://github.com/caercam/media-link-for-elementor Hope this helps someone!

**Comment by abdulawal39** [comment]
I was looking for the same and finally I've created a custom control to allow selecting any type of files, posting here as it may help someone else: 
Source Code: https://github.com/abdulawal39/elementor-file-select-control
Article/Instructions: [https://abdulawal.com/elementor-file-select-control/](https://abdulawal.com/elementor-file-select-control/)

**Comment by marekmaurizio** [comment]
Thank you @abdulawal39. How something like this did not make core in years it's beyond me.

**Comment by brittaweller** [comment]
In my case I found a simple solution in this issue [#6818](https://github.com/elementor/elementor/issues/6818)

Quote: 

_"The media control can accept more types in it's media_type parameter which in your case should be either pdf or application/pdf. Which should solve your First and second issue. ex:"_

```
$this->add_control(
	'pdf_file',
	[
		'label' => 'PDF',
		'type' => Controls_Manager::MEDIA,
                 'media_type' => 'application/pdf',
	]
);
```
