### ISSUE TITLE
HTML Element Editor display issue

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#1575]
When you have a larger number of lines of html code it overflows over the "view page" and "go to dashboard" links.
![html-oveflow](https://cloud.githubusercontent.com/assets/22448787/24587494/b71d268c-17af-11e7-8c33-a7910d6715c8.png)

**Comment by kobi-zaltzberg** [comment]
Thanks for your reporting. It'll be fixed by the next version.
