### ISSUE TITLE
Enhancing the "Page Setting" panel

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#1579]
## Description

The page setting panel added in v1.4.0 is awesome! I like the direction where it's going.

The next step should be to allow users to update all the page content from Elementor - titles, excerpts, authors, publish date, etc.... Also, the content should be separated from the settings.

This is my suggestion:

![page-settings](https://cloud.githubusercontent.com/assets/576623/24593314/d7ae5da0-182a-11e7-849e-3e36b350d285.png)

**Comment by WPDevHQ** [comment]
+1
WYSIWYG for the excerpt input. The featured image field would be an added bonus!
Maybe split it into 3 tabs instead of 2? i.e. Settings - Content - Style

**Comment by kokers** [comment]
What would be great also, is to move this as a tab next to elements|global http://prntscr.com/hgvx45 I find myself going there quite a lot, especially when there are some custom settings added. This could be optional, but either way, Elements/Global in sidebar are related to current page. All options hidden under hamburger menu are somewhat global settings. Adding a link to page settings upfront is more fitting imo. It could be as a simple gear icon.
