### ISSUE TITLE
Shape Divider 'Bring To Front' does not work in Editor

### ISSUE THREAD

**Issue by dollhousedigital** [pojome/elementor#1581]
Shape Divider 'Bring To Front' does not work on the back end.

It shows fine on the front end but nothing while in the editor at all.

Have tried using Chrome and Firefox and it is the same.

For example - if you have a section that has 2 columns. And you have added background colour or images to the columns. Then the shape divider will not show anything in the back end with 'Bring To Front' selected but all is fine when viewing the site on the front end.

**Comment by arielk** [comment]
I just checked it again and everything seems to work well in the back-end also.

In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
