### ISSUE TITLE
Is anybody alive?

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#1583]
Do you guys even see the Issues at github?
170 tickets, 100 of them are actually dev questions who need assistance and noone replies.

Are you interested for us to use your product and work on it or you do not care and just want to self only for your self?

@benpines @KingYes and who else.
It starts to get pretty much annoying to have no plan, no assistance and more no support ( or even when we got replies, they was wrong ), no API for devs.

Can you please try catch up a bit? I know you might be working for free, but if we develop our products, most probably Elementor Pro ( or anything else you have in mind ) might work even better.

**Comment by arielk** [comment]
We work hard to respond to development questions, but our top priority is to answer bugs or conflicts, so please be patient, we try to reach every question.
