### ISSUE TITLE
You are doing a good job...

### ISSUE THREAD

**Issue by kadoogan55** [pojome/elementor#1585]
I have been pretty critical with regards to a few issues I have had with Elementor and some of my comments...I imagine this can be bad for morale, and so I just wanted to say that overall Elementor is an excellent product and all the devs are doing a great job with it.

Any harsh-sounding comments from me personally are meant not to crush your spirits or seem ungrateful for what you are doing, but rather to try to get results on issues that are preventing me from using Elementor the way I want or need to at the time.

Regardless - I appreciate what you do, and the great product that Elementor continues to be because of it.

Thank you!

**Comment by arielk** [comment]
We do go through the issues regularly and answer as much as we can, but urgent bug get a higher, but don't worry, we try to reach every question.

Thanks for your support!
