### ISSUE TITLE
Page Settings Reload on template change not firing anymore

### ISSUE THREAD

**Issue by ryanlabelle** [pojome/elementor#1586]
Under page settings, the preview window used to reload when a change was made to the Template dropdown. This isn't happening any longer. I also invoke a reload for my custom controls. 

ref: https://github.com/pojome/elementor/issues/1556

I understand that the panel auto saves every 3s now, but their should be an option to reload the preview. 

Probably the changes here: https://github.com/pojome/elementor/commit/9a93186419853658353732bcd63f82a40e85d6d6

Steps to recreate:

1. Open Page Settings
2. Make a change the the template dropdown.
3. No preview reload so you can't see the changes. 

Cheers!

**Comment by kobi-zaltzberg** [comment]
This is a known bug that will be fixed by the next release. see #1584.
