### ISSUE TITLE
Overlap prevents editing

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#1587]
## Description
Bug? I've noticed lately that when elements are close together, I sometimes can't edit something because the controls overlap the adjacent section and vanish when I try to click the pencil icon.

<img width="689" alt="overlap" src="https://cloud.githubusercontent.com/assets/974442/24632141/edca45d4-1877-11e7-95f7-3e2a324543c9.png">

In the image above, it is not possible to edit the icon element to the left of text element "Open 24/7 access..." because I cannot click on the edit icon. It disappears and I find myself clicking on a section of the lefthand column instead. 

## Environment
								
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: 5.5.49
	PHP Version: 5.6.30-7+deb.sury.org~precise+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.3
	Site URL: https://www.library.ucsf.edu
	Home URL: https://www.library.ucsf.edu
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 200M
	Permalink Structure: /news/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Dynamik-Gen
	Version: 2.1.0
	Author: The Cobalt Apps Team
	Child Theme: Yes
	Parent Theme Name: Genesis
	Parent Theme Version: 2.4.2
	Parent Theme Author: StudioPress

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 3.3
		Author: Automattic

	Breadcrumb NavXT
		Version: 5.6.0
		Author: John Havlik

	Compress JPEG & PNG images
		Version: 2.2.2
		Author: TinyPNG

	Elementor
		Version: 1.3.5
		Author: Elementor.com

	Elementor Pro
		Version: 1.2.4
		Author: Elementor.com

	Genesis Dambuster
		Version: 1.5.5
		Author: Russell Jamieson

	Graceful Email Obfuscation
		Version: 0.2.2
		Author: Nicholas Wilson, Jason Hendriks

	Insert Pages
		Version: 3.1.8
		Author: Paul Ryan

	Jetpack by WordPress.com
		Version: 4.7.1
		Author: Automattic

	MailChimp for WordPress
		Version: 4.1.0
		Author: ibericode

	Redirection
		Version: 2.5
		Author: John Godley

	Relevanssi
		Version: 3.5.8
		Author: Mikko Saari

	Sticky Menu (or Anything!) on Scroll
		Version: 2.0.1
		Author: Mark Senff

	TablePress
		Version: 1.8
		Author: Tobias Bäthge

	UCSF Library Search Filter
		Version: 1.0.0
		Author: Stefan Topfstedt

	User Role Editor
		Version: 4.32.3
		Author: Vladimir Garagulya

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WPForms
		Version: 1.3.6
		Author: WPForms

	WPForms Conditional Logic
		Version: 1.1.9
		Author: WPForms

**Comment by arielk** [comment]
I do not recommend creating such narrow columns. Unfortunately, this is not something that can be fixed, it's part of the editor's UI.

We're working to improve the interface, I hope it will be improved in one of the upcoming versions.

Anyway I tagged this issue for us so we could deal with it more efficiently.

Thanks for your feedback!

**Comment by mizejewski** [comment]
Thanks @arielk. Another thing to consider is that I would not be using such a narrow column, if I could position an icon to the left of a line of text while controlling its size and vertical alignment. Adding that feature may be an easier fix.

**Comment by arielk** [comment]
In version 1.5 we made several UI fixes, please update your plugin and let me know if this solved your problem.

**Comment by mizejewski** [comment]
Yes, version 1.5 fixes this. The UI fixes are SO GREAT I'm doing back flips!
