### ISSUE TITLE
Suggestion: Deactivate own CSS 

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#1593]
Hello,

i use Elementor also for developing own designs with functionalities, like mobile menu and CSS positioning and animations. 

It works well and fast, but Elementor is also (sure) reacting to my custom CSS theme changes, witch makes it difficult, because elements sometimes are not visible or overlapping and so on. 

So, can there be a way to deactivate the own CSS? So it would be possible to work on the page and the elements without searching for it, or deactivate certain CSS in the own CSS files. 

Thanks!

**Comment by KingYes** [comment]
Did you mean Elementor CSS (global) or CSS elementor make in this page?

**Comment by Luxamman** [comment]
Only the CSS of the site (not the elementor css), when working with elementor. Not when you look at the page as a customer/visitor.

**Comment by KingYes** [comment]
Sorry but I still don't understand you :|

Can you try explain yourself again?

**Comment by Luxamman** [comment]
Imagine you like to build a page in Elementor. Most of the thinks and designs are working out of the box, but some thinks i have to configure in the Theme CSS.

Like for example a element, that should have a fixed position on a page. 
In that case, the element will have a definitive name like "#fixelement". 
So i design the element in elementor and than, i use the Theme CSS to give it a fix position and size. 

When i visit the page, the "#fixelement" will be on that position, like configured in the Theme CSS. When i reload the page in Elementor, Elementor also try to follow the rules of the Theme CSS, but sometimes its not right and/or it is impossible to work on the "#fixelement", without deleting the rule from the Theme CSS. 

So the main problem is when you give the Elementor elements ID`s and when you want to give that elements custom CSS positions/sizes/effects. 

So, it would be a real benefit to deactivate all of the Theme CSS (or something like that) to work on the page. 

Hope i explained it a little better^^
Greetings!

**Comment by arielk** [comment]
How do you imagine it will work?
Note that if you use the Pro Elementor you can override the style of your theme using Custom CSS.

**Comment by carasmo** [comment]
I did something like this. I can't think of a way for this to be done with a click.

In my theme style.css file:

```
.my-fixed-element {
    position: fixed;
    top: 0;
}
```

I created a stylesheet that loads when logged in.

```
/**
 *
 * If User Is Logged In Style Sheet
 *   adjust the path and the constant for the path to your theme directory
 */
function yourprefix_logged_in_css() {	
	if ( ! is_user_logged_in() ) return;
	
	wp_enqueue_style( 'logged-in', CHILD_URL . '/assets/css/logged-in.css', null, null );	
	      	
}
add_action( 'wp_enqueue_scripts', 'yourprefix_logged_in_css', 99 );

```

In this logged-in.css file, I change the position for when Elementor is active.

```
.elementor-editor-active .my-fixed-element {
    position: relative;
    top: auto;
}
```

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we’ll be happy to help you further.
