### ISSUE TITLE
Padding tablet x Padding mobile

### ISSUE THREAD

**Issue by edertuffic** [pojome/elementor#1599]
Hi!

In the same section, if I type 200px in the Top padding in Tablet and 100px in Mobile, when I open the site on the mobile the padding is 200px (even I typing 100px in the Elementor).

If I type 300px in the top padding in Tablet and 100px in Mobile, when I open the site on the mobile the padding is 300px.

Thank you,
Eder.
![img2](https://cloud.githubusercontent.com/assets/18623361/24762593/3570ac26-1ac5-11e7-9893-789073975fd5.jpg)
![img1](https://cloud.githubusercontent.com/assets/18623361/24762594/357331a8-1ac5-11e7-9880-9158fe208924.jpg)

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by arielk** [comment]
Update: This issue happens with the old versions of PHP.

Please contact your hosting company and ask them to upgrade the PHP version to PHP 7 or higher.

We recommend using the latest version of PHP to avoid bugs and security breaches.
