### ISSUE TITLE
Conflict with ManageWP on Multisite

### ISSUE THREAD

**Issue by luizeof** [pojome/elementor#1600]
## Steps to reproduce

Install Elementor on Wordpress Multisite with ManageWP and try to connect. 

Error log:

Class 'Elementor\Admin' not found occurred in wp-content/plugins/elementor/includes/plugin.php on line 241. Please make sure that your website is accessible.

## Environment

PHP 7
Elementor Pro
VPS Digital Ocean
Nginx

**Comment by luizeof** [comment]
@arielk  @benpines

**Comment by KingYes** [comment]
Do you have any error before this line? [In this line](https://github.com/pojome/elementor/blob/master/includes/plugin.php#L207) we include that class...

**Comment by luizeof** [comment]
@KingYes Elementor Works fine, but when connect via ManageWP Panel ... this error appear

**Comment by KingYes** [comment]
Please send me your FTP + WP Admin to support at elementor.com I want to see that..

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by arielk** [comment]
Update: Added patch fix in v1.6, please update the plugin.
