### ISSUE TITLE
Conflict with IDX Omnibar

### ISSUE THREAD

**Issue by KyleMLoranger** [pojome/elementor#1602]
Anyone have any experience with an IDX plug-in conflicting with Elementor? We've inserted the IDX Omnibar (it searches real estate listings) into Elementor and it fails to work. Insert it without Elementor turned on and it works just fine. I'm suspecting a js conflict...

## Description

Inserted IDX Omnibar as a widget into an Elementor page. It looks, ok but the form does not generate drop down help suggestions, nor does it return any results. 

## Steps to reproduce

Install IMPress for IDX Broker - (you need an account to connect it to unfortunately) 

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 10.1.21
	PHP Version: 7.0.17
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.3
	Site URL: http://kldwebsites.com/si
	Home URL: http://kldwebsites.com/si
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Edmonton
	Debug Mode: Inactive

== Theme ==
	Name: Sitepoint Base
	Version: 1.0
	Author: Sitepoint
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12

== Active Plugins ==
	Elementor
		Version: 1.4.0
		Author: Elementor.com

	Elementor Pro
		Version: 1.2.4
		Author: Elementor.com

	Enhanced Media Library
		Version: 2.4.4
		Author: wpUXsolutions

	IMPress for IDX Broker
		Version: 2.3.2
		Author: IDX Broker

	Imsanity
		Version: 2.3.8
		Author: Shane Bishop

	s2Member Framework
		Version: 161129
		Author: s2Member / WebSharks, Inc.

	Simple Custom CSS
		Version: 3.3
		Author: John Regan, Danny Van Kooten

	Simple Social Icons
		Version: 2.0.1
		Author: Nathan Rice

	Toolset CRED
		Version: 1.8.8
		Author: OnTheGoSystems

	Toolset Layouts
		Version: 1.9.3
		Author: OnTheGoSystems

	Toolset Types
		Version: 2.2.9
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.3.1
		Author: OnTheGoSystems

	Yoast SEO
		Version: 4.5
		Author: Team Yoast

== Must-Use Plugins ==
	LB-MU
		Version: 4.0.2
		Author: Chris Piepho, Original Author: Mika Epstein

	Plugin Organizer MU
		Version: 6.0.5
		Author: Jeff Sterup

== Debug ==
	Errors: There are no errors to display

**Comment by KyleMLoranger** [comment]
Apparently turning off YOAST SEO makes the IDX form work again. Weird.

**Comment by arielk** [comment]
I'm not familiar with the IDX plugin, anyway did the problem work out?
