### ISSUE TITLE
Template Library Hooks

### ISSUE THREAD

**Issue by adilelsaeed** [pojome/elementor#1603]
We want to include Elementor in our premium themes put we need some WordPress actions and filters to alter template library. mainly to do the following:
1. Disable/enable remote source.
2. Alter remote source URI.
3. Import local template using code [documentations]  

Could you please add necessary hooks and docs so we don't had to fork and maintain our own Elementor copy.

**Comment by arielk** [comment]
This is something we plan to add in the future. I merged this issue with another issue #417 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by Basilakis** [comment]
@arielk Is there a hook for that nowdays?
