### ISSUE TITLE
Issue with default widgets

### ISSUE THREAD

**Issue by oceanwp** [pojome/elementor#1604]
## Description

Hello, I have a small problem, I explain.

I have created a "Custom Header" option in the customizer for my OceanWP theme, this option allows users to select a page created with elementor to display its content instead of the header.

Everything works fine but since the last update, the default WordPress widgets no longer work in front end, if I add an elementor widget, it works.
I have created a logo and navigation wordpress widgets so to display the logo and the navigation but if I do not use any elmentor widget the header no longer appears at all.

## Steps to reproduce

1. Install OceanWP (https://github.com/oceanwp/oceanwp).
2. Create a new page named "My Header", in this page insert the "Custom Header Logo" and "Custom Header Nav" widgets that are in "WordPress".
3. Go to the customizer in the "Header > General" section, select "Custom Header" in the "Style" option, then select your "My Header" page in the "Page ID" option.

Before the last update of Elementor, the content of the page "My Header" would have replaced the header of the site, now it no longer works if no elementor widget is added in the page where you created the header (My Header) .
If you added an elementor widget, for example the "Spacing" widget, the header will appear.

I use this code to display the content of a page created with elementor:

```
// Get page ID
$get_id = get_theme_mod( 'ocean_header_page_id' );
Plugin::instance()->frontend->get_builder_content_for_display( $get_id );
```

## Environment
https://pastebin.com/UzCkUuJ0

**Comment by KingYes** [comment]
Hey @oceanwp,

In your render method you need to check every variable if is not empty, and when it's empty just handle with that. I can run `WP_Widget::update()` method every render, but I think we can get huge bad performance.

BTW, can you show me your widget?

**Comment by oceanwp** [comment]
Hello, thank you for your reply.
The problem is not only with my widgets but all the WordPress widgets.
Here are screenshots.

I selected the Custom Header style and the Header page in the customizer, the page is created with Elementor, if I only put the Calendar widget: http://imgur.com/a/aWJJL
The header does not appear in front end: http://imgur.com/a/ZhraV

Now if I add any elementor widget, for example the Heading widget: http://imgur.com/a/bPT2s
The header appears in front end: http://imgur.com/a/VWGRv

Before there was not this problem.

**Comment by KingYes** [comment]
I try this right now and it's working perfect.

BTW, are you print the content in your HTML? In your example code you don't echo the HTML...

**Comment by oceanwp** [comment]
You've tried and it works with OceanWP?
Here is my code for the custom header:

```
namespace Elementor;

// Get page
$get_page   = oceanwp_header_page_id();

// Get page ID
$get_id     = get_theme_mod( 'ocean_header_page_id' );

// Check if page is Elementor page
$elementor  = get_post_meta( $get_id, '_elementor_edit_mode', true );

// Check if there is page for the header
if ( $get_page ) : ?>

    <div id="site-header-inner">

        <?php
        // If Elementor
        if ( class_exists( 'Elementor\Plugin' ) && $elementor ) {

            echo Plugin::instance()->frontend->get_builder_content_for_display( $get_id );

        }

        // Else
        else {

            // Display page content
            echo do_shortcode( $get_page );

        } ?>

    </div>

<?php
endif;
```

You think there's something wrong?
Thank you.

**Comment by KingYes** [comment]
1) Why your `oceanwp_header_page_id()` function return the content of the header?

2) I think it's better coding:

```
<?php
namespace OceanWP;

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

$custom_header_query = false;

$header_page_id = get_theme_mod( 'ocean_header_page_id' );

if ( ! empty( $header_page_id ) ) :
	$custom_header_query = new \WP_Query( array( 'p' => $header_page_id, 'post_type' => 'any' ) );
endif;

if ( ! empty( $custom_header_query ) && $custom_header_query->have_posts() ) : ?>
	<div id="site-header-inner">
		<?php
			$custom_header_query->the_post();
			the_content();
			wp_reset_postdata();
		?>
	</div>
<?php endif; ?>
```

**Comment by oceanwp** [comment]
Thanks for the code but I have exactly the same issue :)
If no Elementor widget is added, the header does not appear in front end.

**Comment by KingYes** [comment]
How you include this file?

**Comment by oceanwp** [comment]
Here is all my code, with your added:

```
namespace Elementor;

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// If is not PHP version 5.2+
if ( ! version_compare( PHP_VERSION, '5.2', '>=' ) ) {
    return;
}

// Get page
$get_page   = oceanwp_header_page_id();

// Get page ID
$get_id     = get_theme_mod( 'ocean_header_page_id' );

// Check if page is Elementor page
$elementor  = get_post_meta( $get_id, '_elementor_edit_mode', true );

// If page ID
$header_query = false;
if ( ! empty( $get_id ) ) :
    $header_query = new \WP_Query( array( 'p' => $get_id, 'post_type' => 'any' ) );
endif;

// Add container class if the header is not full width
$class = '';
if ( true == get_theme_mod( 'ocean_add_custom_header_container', true ) )  {
    $class = ' container';
}

// Check if there is page for the header
if ( $get_page ) : ?>

    <?php do_action( 'ocean_before_header_inner' ); ?>

    <div id="site-header-inner" class="clr<?php echo esc_attr( $class ); ?>">

        <?php
        // If Elementor
        if ( class_exists( 'Elementor\Plugin' ) && $elementor && ! empty( $header_query ) && $header_query->have_posts() ) {

            //echo Plugin::instance()->frontend->get_builder_content_for_display( $get_id );
            $header_query->the_post();
            the_content();
            wp_reset_postdata();

        }

        // If Beaver Builder
        else if ( class_exists( 'FLBuilder' ) && ! empty( $get_id ) ) {

            echo do_shortcode( '[fl_builder_insert_layout id="' . $get_id . '"]' );

        }

        // Else
        else {

            // Display page content
            echo do_shortcode( $get_page );

        } ?>

    </div>

    <?php do_action( 'ocean_after_header_inner' ); ?>

<?php
endif;
```

**Comment by KingYes** [comment]
Can you send me all your theme with this code? I want to check this in my local..

**Comment by oceanwp** [comment]
Hello @KingYes, you can download my theme here: https://github.com/oceanwp/oceanwp
The "custom-header.php" file is located in "partials/header/style/".
To select the custom header, I mentioned the steps in "Steps to reproduce".
Thank you very much :)

**Comment by oceanwp** [comment]
Hello @KingYes, have you had time to see what the problem was?
Thank you.

**Comment by KingYes** [comment]
I just this right now, and it's seen working as well.

The template preview: http://i.imgur.com/6dNr5S1.png

The final page (with custom header): http://i.imgur.com/4V50bss.png

**Comment by oceanwp** [comment]
Hello, yes it works with the widgets of elementor, if you add only widgets of WordPress, the custom header will not be displayed.

**Comment by KingYes** [comment]
Still.. It's working as well.. :|

**Comment by oceanwp** [comment]
Hi @KingYes, you have not put any elementor widgets, not even spacer or divider?
I am not the only one to have this issue, several users have reported to me.
I made a little video to show you what it makes me, I selected the custom header option with a page: https://drive.google.com/file/d/0B_VGLTDVH6yCUlBhVGsxcWFqYzQ/view?usp=sharing

**Comment by plsrespond** [comment]
I can confirm I have to put somewhere spacer set to 0 just to see the custom header even on fresh wordpress install.

**Comment by oceanwp** [comment]
Hello @KingYes, any news on this issue?
Thank you :)

**Comment by KingYes** [comment]
As I say, use this code (For `partials/header/style/custom-header.php`):

```
<?php
/**
 * Custom Header Style
 *
 * @package OceanWP WordPress theme
 */

namespace OceanWP;

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

$custom_header_query = false;

$header_page_id = get_theme_mod( 'ocean_header_page_id' );

if ( ! empty( $header_page_id ) ) :
	$custom_header_query = new \WP_Query( array( 'p' => $header_page_id, 'post_type' => 'any' ) );
endif;

if ( ! empty( $custom_header_query ) && $custom_header_query->have_posts() ) : ?>
	<div id="site-header-inner">
		<?php
		$custom_header_query->the_post();
		the_content();
		wp_reset_postdata();
		?>
	</div>
<?php endif;
```

**Comment by oceanwp** [comment]
Hello @KingYes, thank you for this code but I have exactly the same issue, if no elementor widgets is added to the page where I created my custom header, there is no header on all pages.

**Comment by KingYes** [comment]
But I try your theme with one widget and you right it's not working. But when I replace this code with my, it's working as well..

**Comment by oceanwp** [comment]
It's very weird, wait, I'll make sure I've entered the correct code.

**Comment by oceanwp** [comment]
Yes I entered the correct code, look: https://pastebin.com/aJZsj1vX

If I add only the Custom Header Logo widget, the header does not appear on any page, if I add one elementor widget, the header is displayed correctly.

**Comment by KingYes** [comment]
No. You added some code and you broke the code. Please add ALL my code without any change..

**Comment by oceanwp** [comment]
Yes it works :)
I had not paid attention to my code.
Thank you very much for your help :)
