### ISSUE TITLE
Image Carousel Fade Transition

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#1605]
In Elementor v1.4.2, the Image Carousel only seems to Scroll between images, and doesn't give the option for the Fade effect. I could be wrong but I thought there was the option for both.

**Comment by drawcard** [comment]
Seems to work fine for me. There is an option for both:

![image](https://cloud.githubusercontent.com/assets/1435638/24910938/86231ab8-1f08-11e7-9ab1-a29ee8b367cb.png)

**Comment by JoelEadeDesign** [comment]
How strange... The "Effect" setting is "display:none;" for some reason:
![slider-carousel](https://cloud.githubusercontent.com/assets/1729832/24933949/6c5b0cc2-1f5c-11e7-8536-c70069b599af.jpg). Even if I show the field, save it as "Fade" it still slides the images.

It's occurring on a few sites for me, not just this one, both on localhost and on a hosted server.

Would my system info be of any help?

**Comment by drawcard** [comment]
> Would my system info be of any help?

Absolutely :) Post it here if you can.

**Comment by JoelEadeDesign** [comment]
Easy as :)

[system-info-localhost-11-04-2017.txt](https://github.com/pojome/elementor/files/914930/system-info-localhost-11-04-2017.txt)

**Comment by drawcard** [comment]
I wonder if editor.min.css is missing / corrupted on your side. Have you tried completely removing Elementor in wp-plugins and reinstalling? Also have you tried rebuilding your style sheets in Elementor's settings?

Failing that you may have to write a rule in your own CSS sheet that overrides the "display: none;" setting going on with something like "display: block !important". Make sure you nest it inside the .elementor-editor-active body class, so it doesn't interfere with anything on the frontend. Then in time when the bug is fixed you can remove the rule.

**Comment by JoelEadeDesign** [comment]
Thanks @drawcard! 

After some tinkering with the settings, I've found the **Effect** drop-down only appears if the **Slides to Show** is set to **1**.

![image](https://cloud.githubusercontent.com/assets/1729832/24943190/aea79c30-1f98-11e7-8108-1887c1275b05.png)

![image](https://cloud.githubusercontent.com/assets/1729832/24943185/a82c4e5a-1f98-11e7-96e5-def91b544370.png)

I assume this is a bug and not the intended functionality.

**Comment by drawcard** [comment]
Ah that explains it, I didn't know about that myself. Usually it's set to 1 by default. I would say that's the correct function.

**Comment by JoelEadeDesign** [comment]
Could be but I don't understand why it wouldn't be an option. Perhaps it's a limitation of Slick Slider, although I can't see any notes on their Github page: http://kenwheeler.github.io/slick/

It's not a deal-breaker for me but thought it worth asking. Do you recommend I close this issue or leave it open?

**Comment by drawcard** [comment]
Oh I see your point - the counter shouldn't ever be set to "0" or blank.

Up to you if you want to close it, but I'm sure someone from the official dev team will get around to addressing it :)

**Comment by JoelEadeDesign** [comment]
Cool, thanks @drawcard. I wasn't sure if you were on the core team or not. I think I'll leave it open, as it's an option I'd like in my tool belt.

Thanks so much for your help. Now, I'm off to the WP Melbourne Meet Up to do a talk on Elementor! :)

**Comment by drawcard** [comment]
Nice! Good luck with the talk and nice to meet another fellow Aussie Elementorian (I'm in Adelaide!)

**Comment by JoelEadeDesign** [comment]
Oh nice! Thanks mate :)

**Comment by arielk** [comment]
The _Effect_ control is displayed only if you set _Slides to Show_ = 1, if you choose to display one slide, you will see the Fade effect properly.

Please let me know that it's OK.

**Comment by JoelEadeDesign** [comment]
Thank you for the clarification, @arielk. 

Ideally, I'd like to have the option to Fade between images when _Slides to Show_ = 2 or more but after some more research on Slick Slider I've found it's [not supported](https://github.com/kenwheeler/slick/issues/830), however, I found a workaround using CSS from [this suggestion](https://github.com/kenwheeler/slick/issues/830#issuecomment-267843811).

Unfortunately, you have to set the _Animation Speed_ to zero seconds, so there's an abrupt change between the shown slides and the new slides as I can't fade-out the active images with CSS but I can made the new images fade-in so I guess it's not too jarring. Here's a video of it in action: https://www.useloom.com/share/a4a5687bec8447dda5d77417048f7da7

Cheers!

**Comment by vaucci** [comment]
**SOLUTION IN CSS:** 

.swiper-fade .swiper-slide {pointer-events:initial}

**Comment by PandaNeon** [comment]
> Thank you for the clarification, @arielk.
> 
> Ideally, I'd like to have the option to Fade between images when _Slides to Show_ = 2 or more but after some more research on Slick Slider I've found it's [not supported](https://github.com/kenwheeler/slick/issues/830), however, I found a workaround using CSS from [this suggestion](https://github.com/kenwheeler/slick/issues/830#issuecomment-267843811).
> 
> Unfortunately, you have to set the _Animation Speed_ to zero seconds, so there's an abrupt change between the shown slides and the new slides as I can't fade-out the active images with CSS but I can make the new images fade-in so I guess it's not too jarring. Here's a video of it in action: https://www.useloom.com/share/a4a5687bec8447dda5d77417048f7da7
> 
> Cheers!

could you bring back here the css workaround you used ? the link is no longer active (404)

**Comment by JoelEadeDesign** [comment]
Hey @PandaNeon. Ah, that's a shame. From the best of my memory from 7 years ago (!) here's the CSS I used on the site. The client has replaced the image carousel with a video for the hero section but the CSS is still in the theme:

`.slick-slide-fade {
    background: black
}

.slick-slide-fade .slick-slide {
    opacity: .5;
    -webkit-transition: opacity 1s ease-in-out;
    transition: opacity 1s ease-in-out
}

.slick-slide-fade .slick-slide.opacidown {
    opacity: 0
}

.slick-slide-fade div.slick-current {
    opacity: 1;
    -webkit-transition: opacity 1s ease-in-out;
    transition: opacity 1s ease-in-out
}

.slick-slide-fade div.slick-active {
    opacity: 1;
    -webkit-transition: opacity 1s ease-in-out;
    transition: opacity 1s ease-in-out
}`

**Comment by PandaNeon** [comment]
thank you very kind
