### ISSUE TITLE
wp_enqueue_scripts not possible with latest update

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#1606]
Since the last update Elementor appears to not load wp_enqueue_scripts anymore, why ?

We had a couple of custom CSS snippets loaded to change some of the icons and point the help links to our own helpdesk rather than Elementors help page for a clearer customer experience but now its not possible

Significant client volume impacted by this

**Comment by artifex-it** [comment]
Same problem.

With registration and enqueue splitted scripts doesn't compare but with full enqueue they compare.

**Comment by Pagester** [comment]
I have also tried Elementors own hooks **elementor/frontend/before_enqueue_scripts** and **elementor/editor/before_enqueue_scripts** which also don't work

I need an official response on this please

**Comment by KingYes** [comment]
If you want to embed scripts for Elementor (it's run just when we using Elementor in the page). So you can use action: `elementor/frontend/before_enqueue_scripts` or `elementor/frontend/after_enqueue_scripts`.

What is not work for you right now?

**Comment by Pagester** [comment]
@KingYes I have just tried elementor/frontend/before_enqueue_scripts to call a file that has a function to re-write the help link and change some of the icons but its not getting called at all.

Previous we used wp_enqueue_scripts which worked fine until we did the last elementor update. Swapping out wp_enqueue_scripts for elementor/frontend/before_enqueue_scripts has no effect, if we roll back it works fine

**Comment by KingYes** [comment]
Can you show me your code here?
