### ISSUE TITLE
Uncaught TypeError: c.slick is not a function

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1607]
I am getting the following error when using the Elementor Carousel Widget - it loads fine in the editor, but doesn't display on the frontend:

![image](https://cloud.githubusercontent.com/assets/1435638/24914851/9f2c7f8e-1f14-11e7-8f7b-aa036b0b69f8.png)

I've read that this is possibly due to Jquery loading after frontend.min.js but this is not the case with my theme.

**Comment by KingYes** [comment]
Do you have any `slick` jQuery plugin in your theme? Please check if Elementor load this library...

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by drawcard** [comment]
Hi, I have just had this problem happen on another website I run, it doesn't use slick anywhere else except within Elementor.

![image](https://cloud.githubusercontent.com/assets/1435638/26337746/424b004e-3fba-11e7-8472-a169d316f345.png)

You can visit this page and inspect the code if it helps: https://drawcard.com.au/service/commercial-photography

The slider should be loading under "Examples of our work"

Thanks

**Comment by KingYes** [comment]
Hry @drawcard 

Please try deactivate all your plugins & Change to default theme, and check if the problem is resolved. If all work's okay, try to activate your plugins one by one until your website crash again..

**Comment by drawcard** [comment]
Thanks for replying. On a third website I administer, the image carousels were loading fine (under Elementor Free 1.2.5). However when updating that to the latest version (1.4.7) the site broke.

Also on the second site I reported (my personal site, www.drawcard.com.au) I deactivated all plugins and that didn't work. But switching the theme to TwentySixteen got the gallery working. So there is some conflict between the theme framework I use [(Sage)](http://roots.io/sage) and one of the methods that Elementor uses. 

I think the problem is to do with enqueueing scripts, something is declaring "slick" twice and it's deregistering the function.

**Comment by KingYes** [comment]
I don't see any code about Slick or other thing to conflict with Elementor. Are you use Sage 8.5.1?

**Comment by KingYes** [comment]
I just install Sage to my dev server, and all work's perfect for me. Are you sure you don't have any custom code there?

**Comment by drawcard** [comment]
Thanks for testing - sorry I should clarify, I am using Sage 9 which is downloadable here: https://github.com/roots/sage 

If you follow the README, you can go through the steps of compiling NPM modules / Composer files that are needed for a basic installation.

I will also test on a clean template tomorrow and see what results come up.

**Comment by KingYes** [comment]
I waiting for your tests.. Thanks.

**Comment by drawcard** [comment]
Cheers. Also for the CSS / JS framework I am also using Foundation 6 (instead of Bootstrap 4 alpha) which is selectable during the Sage Composer setup script.

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we’ll be happy to help you further.

**Comment by drawcard** [comment]
No worries - it's been busy around end of financial year here in Australia :) I should be able to take a second look in a couple of days.

**Comment by drawcard** [comment]
Solved: https://github.com/roots/sage/pull/1949
