### ISSUE TITLE
Unable to resize columns

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#1608]
I have a page that contains a "parent" section with a single column. The parent section contains two "child" sections. The top child section contains five columns and the second child section contains a single column. When the divider between two columns in the top child section is hovered over it becomes visible but the two-headed arrow for column size adjustment does not appear. If additional columns are added to the second child sections they are adjustable.

Login details are available if required.

				
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.51
	PHP Version: 7.0.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.3
	Site URL: http://wpdemo.websitesdesigned4u.com/templates
	Home URL: http://wpdemo.websitesdesigned4u.com/templates
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 0.1
	Author: Thomas Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 1.3.46
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

== Active Plugins ==
	Elementor Pro
		Version: 1.2.4
		Author: Elementor.com

== Network Plugins ==
	Add From Server
		Version: 3.3.3
		Author: Dion Hulse

	Comet Cache
		Version: 170220
		Author: WebSharks, Inc.

	Easy Google Fonts
		Version: 1.4.2
		Author: Titanium Themes

	Elementor
		Version: 1.4.2
		Author: Elementor.com

	Elementor Addon Elements
		Version: 0.5
		Author: Webtechstreet.com

	GP Premium
		Version: 1.2.96
		Author: Tom Usborne

	NavMenu Addon For Elementor
		Version: 1.0.4
		Author: WPDevHQ

	Page Templater For Elementor
		Version: 1.1.3
		Author: WPDevHQ

	Simple CSS
		Version: 0.4
		Author: Tom Usborne

	SJ Elementor Addon
		Version: 0.1.2
		Author: sandesh055

	TinyMCE Advanced
		Version: 4.4.3
		Author: Andrew Ozz

	Wordfence Security
		Version: 6.3.6
		Author: Wordfence

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WordPress Version Info
		Version: 1.1.2
		Author: alpipego

	WP Smush
		Version: 2.6.2
		Author: WPMU DEV

	WP Universal Functions
		Version: 1.0.2
		Author: WPDevHQ

== Debug ==
	Errors: 
		TypeError: Cannot read property 'pageYOffset' of undefined
			at http://wpdemo.websitesdesigned4u.com/templates/wp-includes/js/jquery/jquery.js?ver=1.12.4 - 4:30810
			2017-03-30 08:51 +00:00
			x 2 times

**Comment by drawcard** [comment]
The columns may not be resizable if they reach a certain threshold of width, ie they are too narrow. That's just my educated guess though. You may be able to use the Custom CSS panel to achieve what you want with the widths.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
