### ISSUE TITLE
Removing space before html close tag breaks Elementor pages.

### ISSUE THREAD

**Issue by nullmem** [pojome/elementor#1610]
## Description

I would hope the code in Elementor is not dependent on Appendix C of the XHTML1.0 specification. Ok all joking aside this issue was found because the Google ngx_pagespeed module for nginx removes these spaces from the code. When enabling ngx_pagespeed in pass-through mode (no filters) the Google code removes these spaces breaking my page. The Google pagespeed module should not be touching the code in pass-through mode, so I will open a bug report with them as well. However, this is not the 1990’s and this should not break my page. I have tried disabling all plugins and have tried 3 themes, and the result is always the same. 

With ngx_pagespeed disabled I get the following result:
Visual: https://www.dropbox.com/s/q3hf0kn6lelh1jb/pagespeed-off.png?dl=0
Code: https://pastebin.com/Y08QQiTB

With ngx_pagespeed enabled I get the following result:
Visual: https://www.dropbox.com/s/pbflm7x87rjy20n/pagespeed-on.png?dl=0
Code: https://pastebin.com/70yqfra4

## Steps to reproduce

Create an Elementor page and run it on nginx with ngx_pagespeed module turned on, which removes spaces from the html close tags

## Environment

System Info (via plugin):
https://pastebin.com/aZL82UjN

Server Info:
nginx version: nginx/1.11.8
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' --add-module=/root/ngx_pagespeed-1.12.34.2-beta

**Comment by KingYes** [comment]
Hey @nullmem 

Elementor don't write any `<html>` tags, just inside your content.

This spaces append just when you use with Elementor?

**Comment by nullmem** [comment]
This problem seems to have resolved itself in the most recent version of Elementor.

**Comment by KingYes** [comment]
I don't know if it's from new Elementor version, but I glad to hear the problem is gone :)
