### ISSUE TITLE
Elementor allows multiple page instances

### ISSUE THREAD

**Issue by AllanSJ** [pojome/elementor#1612]
I'm working on a site with a colleague in another location and this morning while chatting to her I realised that we had the same page open in Elementor at the same time. Luckily I hadn't made any changes or saved my page version over her updated one. I had already noticed that it is possible to have multiple instances of a page open in Elementor on the same PC and I have saved an older version of a page over a newer one a couple of times.

I believe some sort of page checkout system is urgently needed to make it impossible for multiple instances of a page to be edited at the same time. This would eliminate the possibility of saving a previous version of a page over a new version and eliminate conflicts when two people are working on a site.

**Comment by arielk** [comment]
Elementor knows how to work perfectly with multiple users at the same time, just like WordPress.

In any case you can use Revision History to switch between versions, read more here: https://elementor.com/v110-revision-history/

Thanks for your feedback!

**Comment by AllanSJ** [comment]
Two people working on the same page at the same time is a good idea? It
should at least indicate in the page list if it is being worked on.

Regards

Allan Jackson
___________________
Allan Jackson Communications
Mobile: 0403 943 970
LinkedIn: https://au.linkedin.com/in/allansjackson
Portfolio: https://allanjackson.net/allan-jackson-portfolio/
More writing: http://allanjackson.net/blog/
Website of my book: http://www.fad.co.za/
