### ISSUE TITLE
Pro Custom CSS horizontal scroll issue

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1613]
I no longer get a horizontal scroll bar when my css code exceeds the width of the sidebar.  I know I can drag the sidebar but even in doing so, when the cursor is anywhere positioned in the css code editor that is past the initial 300px, the editor window scrolls right but no horizontal scroll bar is present below to be able to scroll back so one has to click and drag to highlight text to the left to get it to go back (or just increment cursor back towards the left).

Whats even worse, when the sidebar is dragged wider, say 600px and all text is showing and there is no need to scroll horizontally, i.e. nothing overflowing right, any time the cursor get's past that initial 300px, the window autoscrolls horizontally to the right even though all the text is visible.

Here is an example video of what I'm talking about.  I did try a fresh install of the latest chrome on a fresh VPS so I think that helps rule out browser plugins and such.  Thx

https://drive.google.com/file/d/0B5wiR8Fq8vfROUdueW5yRnlucW8/view

Example showing scrollbar before expanding but then once expanded and code windows scrolls right losing test to the left, there is no H scroll bar.

https://drive.google.com/file/d/0B5wiR8Fq8vfRWDBrbWZMTGM5aE0/view

**Comment by arielk** [comment]
I'm trying to reproduce the bug but it still works perfect for me on Chrome (Mac). Do you get any errors in the console?

**Comment by pingram3541** [comment]
It was something in the theme that I use for the majority of my builds.  Once I tried WP default theme the problem is no longer.  Sorry for the false alarm and thanks for all you do! =)
