### ISSUE TITLE
feature request: activate/deactivate widgets

### ISSUE THREAD

**Issue by tscheipi** [pojome/elementor#1618]
you sure know siteorigin widget bundles. there you can de-/activate widgets. woud it be possible to add this feature to elementor?

**Comment by arielk** [comment]
We call it "Advanced Role Manager". This feature is probably going to be a part of the Elementor PRO in the future.

I merged this issue with another issue #536 in the same subject so that we could deal with it more efficiently.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello @tscheipi!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.18.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
