### ISSUE TITLE
feature request: adding a tab for accessibility

### ISSUE THREAD

**Issue by tscheipi** [pojome/elementor#1620]
lots of widgets aren´t accissible in the frontend when js is deactivated. what about one more tab in a widget, where one can paste content to be shown when js is deactivated?

**Comment by arielk** [comment]
Can you be more specific which elements are inaccessible enough?
What options would you expect to appear in this tab?

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by tscheipi** [comment]
Answered by mail, as there is written one can answer directly by mail:

Presently the toggle widget.
When js is deactivated the content will remain closed.
I solved this item with a no-js class:
.no-js .elementor-toggle-content {display:block !important;}
As I´m not a programmer there might be a better (already in elementor implemented) way!?
I suppose it will be the same with accordion and tabs and some other widgets.
I´m going through all of the widgets one by one when I find time.
As mentioned above I´m not a programmer but I can imagine that there will be one more tab to add content which will appear in a <noscript> tag, if you know what I mean.
E.g. I suppose one will not be able to send a message with the form widget if js is deactivated.
In that case one could provide a simple email-link and a hint to activate js.
Imho accessibility in mind for pro users would be an outstanding, great thing which nobody else offers. Particularly if you consider that the current pro widgets could be easily replaced with free widgets.
Kind regards
Johannes
