### ISSUE TITLE
Icon List - Alignment - Inline?

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1624]
I thought this was requested before but had a hard time finding it.  Is it possible to make an icon list display inline without custom css?  Thx

**Comment by pingram3541** [comment]
After doing a little playing around this is a known quirk of using flex model with inline elements.  I found that if you add an option to toggle the elements inline, just also toggle the ul to have following properties:

here is the css output:

Inline - justify right - desktop
Inline - justify left - tablet
Inline - justify center - mobile

selector .elementor-icon-list-items {
    display: flex;
    justify-content: flex-end;
}
@media (max-width: 1024px){
    selector .elementor-icon-list-items {
        justify-content: flex-start;
    }
}
@media (max-width: 767px){
    selector .elementor-icon-list-items {
        justify-content: center;
    }
}

And of course the logic should be smart enough to set inline for only specific modes and when not inline for a particular device width, we remove the flex props from the ul and everything works as it does now.  

This would give the utmost design flexibility for icon lists both vertical and horizontal.  Thanks.

**Comment by pingram3541** [comment]
Yes, please see my response on the other thread, they are similar yet still individual.  Thx - https://github.com/pojome/elementor/issues/1601#issuecomment-296486010

**Comment by muzaffarsiddiqui** [comment]
Hi,
Very nice tip. It solves my problem too except a little problem. I need to have space in between icon list items. Not the first one and last one. 

What will be the css code?

I will appreciate your help.
Thanks
Muzaffar

**Comment by sigersmit** [comment]
@muzaffarsiddiqui I used:
```
.elementor-icon-list-item:not(:first-child) {
    padding-left: 10px;
}
```
This would be a great enhancement!

**Comment by maxwellhibbert** [comment]
Need this.

**Comment by vongoh** [comment]
+1.   Just realized Elementor Icon List element doesn't have an inline option

**Comment by pingram3541** [comment]
It's the simple things that take the longest to curate

**Comment by arielk** [comment]
Done https://github.com/pojome/elementor/pull/3522
