### ISSUE TITLE
Feature request: Embedding objects within other objects

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#1625]
I would like to see the possibility of embedding certain objects, like images, shortcodes, even multiple columns, within other objects, such as tabs, accordeons and other container-like like objects. While it is generally possible to code what I want in HTML within the editor in these objects, this defeats the purpose of a tool such as Elementor, which should allow one to achieve those effects without coding.

**Comment by arielk** [comment]
With [Elementor Pro](https://elementor.com/pro/) you can do it by Global widget or by save your section or page as a template in the library and insert it in other element by shortcode or widget.

Feel free to check it out: https://elementor.com/pro/
