### ISSUE TITLE
FEATURE REQUEST: post_parent Query-Parameter on Posts Element Widget

### ISSUE THREAD

**Issue by patrickbruckner** [pojome/elementor#1627]
FEATURE REQUEST 

I would love to see more Query-Parameters on Posts Element Widget and other widgets where WP-Queries are used.

Especially useful would be the 'post-parent' parameter.

Thanks

**Comment by arielk** [comment]
I merged this issue with another issue #1748 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
