### ISSUE TITLE
latin-ext subset for google fonts

### ISSUE THREAD

**Issue by meande** [pojome/elementor#1630]
In Czech we use characters like "ščřž..." that are not embeded in standard "latin" subset in google fonts.

So if I use Open Sans font in my headlines and elementor only embeds "latin" subset, all of the "ščřž..." characters are replaced with system sans-serif font and it looks ugly.

There are already cyrillic, hebrew, greek and vietnamese subsets in print_google_fonts() function in includes/frontend.php. Is it possible to add one more line `'cs_CZ' => 'latin-ext',` to the $subsets array, so it looks like this?

`$subsets = [`
`'ru_RU' => 'cyrillic',`
`'bg_BG' => 'cyrillic',`
`'he_IL' => 'hebrew',`
`'el' => 'greek',`
`'vi' => 'vietnamese',`
`'uk' => 'cyrillic',`
`'cs_CZ' => 'latin-ext',`
`];`

**Comment by KingYes** [comment]
We will release this on `v1.5.0`. Thanks!

**Comment by meande** [comment]
You are the best! Thank you :)

**Comment by dudaster** [comment]
The same must be done for Romanian
Please add:
'ro_RO' => 'latin-ext',

It's working on most of the browsers without latin-ext, but for some reason in microsoft edge browser needs this latin-ext.

Thanks!

**Comment by vinkoprelac** [comment]
It should be also added for Croatian
'hr_HR' => 'latin-ext',

And also for the following languages, but I'm not sure about the correct locale codes (this is per https://stackoverflow.com/a/28357857):

Serbian
    sr_Latn: "Serbian (Latin)",
    sr_Latn_BA: "Serbian (Latin, Bosnia and Herzegovina)",
    sr_Latn_ME: "Serbian (Latin, Montenegro)",
    sr_Latn_RS: "Serbian (Latin, Serbia)",

Slovenian
    sl_SI: "Slovenian (Slovenia)",
    sl: "Slovenian",

Bosnian
    bs_BA: "Bosnian (Bosnia and Herzegovina)",
    bs: "Bosnian",

**Comment by sztivoo** [comment]
Please make the same for Hungarian

Please add:
'hu_HU' => 'latin-ext',

**Comment by andrejm** [comment]
... aaaand `'sk_SK' => 'latin-ext',` for Slovakia would be also very appreciated :)

**Comment by ogio** [comment]
Any update regarding implementation of google font subsets?

**Comment by vsosp16** [comment]
This line must be added too for Turkish. We always need the latin-extended.
`'tr_TR' => 'latin-ext',`

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!

**Comment by skorenjak** [comment]
I have Elementor v3.1.4 and the issue with Slovenian ('sl_SI' => 'latin-ext',) persists. Is there a setting I'm missing?

**Comment by mateitudor** [comment]
It just hasn't been completed for romanian.
