### ISSUE TITLE
Suggestion: Edit Tempate from My Library

### ISSUE THREAD

**Issue by badcat** [pojome/elementor#1633]
Would like to be able to call up the Templates > My Library and click on any individual template and edit directly from that dialog.

Additionally, it might be nice to have a shortcut to wp-admin/edit.php?post_type=elementor_library from within the global Elementor hamburger menu - maybe under Elementor Settings?

thank you

**Comment by KingYes** [comment]
You can press "Preview" and in the Admin bar you can press "Edit with Elementor".

Thanks for your feedback !

**Comment by badcat** [comment]
@KingYes said, "You can press "Preview" and in the Admin bar you can press "Edit with Elementor"."  

Not if the user doesn't have the admin bar turned on. :( 
Adding Edit to the context list seems a useful feature. Why dismiss this?

You also didn't respond to the suggestion of adding a Templates shortcut to the global hamburger nav?

**Comment by KingYes** [comment]
We have a lots buttons on this nav, so we don't want (right now) to add more buttons..

About your Shortcut, you right.. We need to talk about this with my team..

**Comment by bainternet** [comment]
We have updated the library since and we feel this is not relevant anymore.
