### ISSUE TITLE
Templates Hooks

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#1634]
Hey,

Can we add more templates, to the template library, through a hook or something related?

**Comment by joshmarom** [comment]
This is not supported at the moment.

**Comment by Basilakis** [comment]
@joshmarom 

Thank you for the update and the comment.
It would be nice to have it.
I can create a custom importer, to import on your custom post type the JSONs' but the work would be way to much for the theme I offer for free :D

**Comment by Basilakis** [comment]
@joshmarom Hey mate, any update here? Any way for us to serve our own templates to the library?

**Comment by bainternet** [comment]
A template in "My library" is a custom post type. So standard WordPress import/export should work or,
If you want you can code something that would utilize the [`save_item()`](https://github.com/pojome/elementor/blob/master/includes/template-library/sources/local.php#L217) method of Elementor\TemplateLibrary\Source_Local class.

I'm closing this for now and its already taעged as [developer api](https://github.com/pojome/elementor/labels/developer%20api) So it will be added there when we have something formal.
