### ISSUE TITLE
Feature request - Widget style dependency

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#1636]
Elementor 1.3 introduced `get_script_depends()` method to load scripts only if a widget is used on the page. Now this is an awesome feature to reduce the unneeded JS code. As a developer I can create many small scripts to reduce the plugin footprint on the page - MAKING ELEMENTOR FASTER!

I would like to do the same with styles. instead of loading one huge CSS file, I want to load only the part that are used. When developing multiple widgets in a single plugin, I want to be able to `get_style_depends()` to load small bits of CSS files.

**Comment by arielk** [comment]
Added in v1.9.0: https://github.com/pojome/elementor/commit/0340f8b0fc56c15f8a4989cb6d7ce219abe48a37
