### ISSUE TITLE
Add a Class to a Section That Has a Background Image

### ISSUE THREAD

**Issue by abaney** [pojome/elementor#164]
I'd like to be able to target sections that have an image background. Would it be possible to add a class to those types of sections, e.g. "elementor-section-image-bg"?

Thank you!

**Comment by yehudah** [comment]
Hi,

Can you share your target ?

**Comment by abaney** [comment]
Basically, this is how a section created by Elementor looks:

`<section class="elementor-section elementor-element elementor-element-lc5uj7s elementor-top-section elementor-section-height-default elementor-section-height-default">section's content</section>`

The image background makes the space above and below those types of sections appear smaller. I would like to target sections that contain a background image (or background color), and make the spacing equal with that of sections that do not have a background image or color applied (e.g. just text).

Here is a visual of what I'm trying to explain. I hope this makes more sense. Thank you for your attention and help!

<img width="1323" alt="elementor-sections-wbackgrounds" src="https://cloud.githubusercontent.com/assets/2255186/16493348/5807cda0-3ea2-11e6-9a32-313fb8411ed8.png">

**Comment by pingram3541** [comment]
I think you are asking for Elementor to add this additional class automatically if a bg image is applied to a section, no?

You can do this now by simply adding your own class to each section that has a bg image under the section's advanced tab.  Multiple classes can be added by separating them with a space.  I'm sure you know this but this is how I'm dealing with this right now.

Section-1 - classes: "section-one"

Section-2 (has bg) - classes: "section-two has-bg"

Section-3 (has bg) - classes: "section-three has-bg"

Section-4 ...

The just add desired rules to .has-bg class in your theme's style.css or other custom css mechanism.

**Comment by abaney** [comment]
@pingram3541 You totally got it. That is a good solution. For me this is easy, however, for clients, they won't remember to do this each time they add this type of an element. I'd rather just target a specific class, and (essentially) let the code do that job automatically. Thanks for the suggestion!

**Comment by abaney** [comment]
I just noticed this class `elementor-section-full_width` in this type of section. Is the usage described above the intention of this class and its placement? I want to make sure that I'm understanding this correctly.

**Comment by arielk** [comment]
@abaney Sorry for the delay, yes, when the section is full width you will always see this class.

Anyway, thanks for your feedback.
