### ISSUE TITLE
Tabs isn't displying like table-cell

### ISSUE THREAD

**Issue by jmbarroso84** [pojome/elementor#1640]
Good afternoon.

I introduce myself although I have read you for months.

The tabs are not working in style. I have read the issue # 279, but I have .elementor-tabs .elementor-tabs-wrapper .elementor-tab-title {
    Display: table-cell! Important;} and the tabs still do not work.

Attached is an image of the problem.

![image](https://cloud.githubusercontent.com/assets/28014254/25396073/86756986-29e3-11e7-8d4e-9cbe6b13e34c.png)

Sorry for my english, and thank you for this wonderful space to share, help and develop!

Hugs.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
