### ISSUE TITLE
footer panel editor area not showing

### ISSUE THREAD

**Issue by laurarinot** [pojome/elementor#1642]
Hi
My client can't see the small editor panel at the bottom right (where the save button is).
class .elementor-panel-footer
She tried different computers, browsers, users. Nothing helps.
When I login through her user, I do see it.
It disappeared after she switched to text editor. When she returned to elementor, the panel was gone.
Can you please help?
Thanks

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
