### ISSUE TITLE
Better loading for video backgrounds

### ISSUE THREAD

**Issue by ehausen** [pojome/elementor#1644]
Currently when loading a video background there is some flickering/flash of black when loading the video from youtube. The situation gets little bit better by adding a fallback image, the the fallback image loads while the video is still loading. But still when video replaces the fallback image there is a flash of a black square over the area.

Maybe something like fading the fallback to video when video is loaded?
How do others do it smoothly?

**Comment by joshmarom** [comment]
Can you please give an example of somewhere it's done more smoothly?

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by ehausen** [comment]
Of course I didn't find any perfect example for you. I found some solutions: https://github.com/rochestb/jQuery.YoutubeBackground/issues/41

I'll get back to you with and example

**Comment by ehausen** [comment]
https://y.co/
http://mediaboom.com/#/home
https://www.myprovence.fr/snapshots2012/en
http://www.nike.com/fi/en_gb/c/jordan
https://revolution.themepunch.com/wordpress-youtube-header/
https://revolution.themepunch.com/fullscreen-4k-youtube-video-gallery-slider-revolution-plugin/

@KingYes, not sure can I re-open the issue. Can't find the option

**Comment by ehausen** [comment]
This might help https://www.themepunch.com/faq/remove-black-preloading-screen-videos/

**Comment by ehausen** [comment]
ping @KingYes @joshmarom, I cannot opent this. Are gettting this?

**Comment by upekshapriya** [comment]
There's a production example listed on https://github.com/rochestb/jQuery.YoutubeBackground viz: http://www.cpbgroup.com/ - much less ugly than the present set up.

I've been using a preloader plugin to cover it but it's a bit of a hack and makes the site look like it's taking a long time to load :(

**Comment by upekshapriya** [comment]
Vimeo doesn't seem as much of an issue loading https://codepen.io/mattgrosswork/pen/jrdwK
compared with YouTube https://codepen.io/dudleystorey/pen/PZyMrd - white flash then black then loading symbol then video starts

**Comment by dudaster** [comment]
The example of the issue is here #793 .
This is a very old bug, please fix it!

**Comment by arielk** [comment]
We just released a patch for this issue, please update v1.5.1 

Thanks for your feedback!

**Comment by wolfmaster8** [comment]
Hello @arielk today is v2.7.4 and I'm having this same issue. [https://ultimateshadesandblinds.com/](https://ultimateshadesandblinds.com/)

**Comment by MtrIbnereza** [comment]
@wolfmaster8 
There is no option to improve video fallback timing, there is just fallback video

**Comment by designdevelopnow** [comment]
Same thing here for one of our clients - www.burgoslawgroup.com

**Comment by brentbarkley** [comment]
+1, seeing this on a site we're building right now too.

**Comment by EricJammin** [comment]
+1, still seeing this issue, even with self-hosted videos.

**Comment by nikkoearion** [comment]
+1 seeing it here too

**Comment by DeLimeWebsiteServices** [comment]
+1 here also.  Very annoying and not cool

**Comment by revr0t** [comment]
+1

**Comment by play4uman** [comment]
Same here. Please provide assistance as the whole appearance of the site gets downgraded by a lot

**Comment by TheUmbralPyre** [comment]
A workaround I found was downloading the video, [optimizing it](https://www.wpzoom.com/docs/tips-for-optimizing-self-hosted-video-backgrounds/), and hosting it yourself.  Although the video doesn't look so good, it takes almost no time to load.

**Comment by TheUmbralPyre** [comment]
There is a workaround for this if you are using the video as a section background. 

1: Download the video
2: Convert it to WEBM format (Mp4 videos sometimes bug out and disappear)
3: Add the video to your Media Library
4: Give the link of the video to the section

**Comment by Karendev** [comment]
Still seeing this black splash in 2021

**Comment by eastriverstudio** [comment]
Still seeing this issue in 2021 on vimeo video in recent client site, getting very noticeable black band between transition of static fallback image and vimeo video loading. Since this has been an ongoing issue since 2017 @arielk or anyone from Elementor team care to comment on a solution? Seems like this should be fixed by now. 

Looking at the iframe code we have some params, one of which is transparent=0, according to vimeo docs changing this to transparent=1 would remove the black background thus solving the issue? I've tried changing this with some jQuery but it seems as the video is probably loaded in programmatically it doesn't work or at least I've not found a way to.

**Comment by yapofire** [comment]
+1 for the same issue

Vimeo Backgrounds in Elementor are currently completely unusable due to this issue

**Comment by capstonedesign** [comment]
Please re-open. This issue lingers.

**Comment by asansano** [comment]
same here, hey @arielk are you able to reopen and assign this ticket?

**Comment by yapofire** [comment]
Hi @asansano , I found this workaround:

https://www.pdms.ca/how-to-maximize-website-speed-by-lazy-loading-backgrounds/

It works, but does mean you cant see any of the images in the Elementor Interface as all called in CSS

This ticket should really be opened as you say. Lazy loading support is pretty crucial

**Comment by asansano** [comment]
hi @yapofire thank you for your help. I'm more referring to the 'black splash' effect on elementor's integration of vimeo and yt especially in backgrounds sections for example. it looks like the fallback image gets replaced too early and you see first some black background flashing for 1-2s (depending on bandwidth)  before the video starts. it's not really about lazy loading of img backgrounds (which is important too but not related).

**Comment by yapofire** [comment]
Haha, Sorry, thought this was another thread!

Yes, agree all my testing recently also shows the Vimeo Background Black Flash is still an issue

Have tried to raise multiple tickets but support always fail to admit its an issue and say thats how vimeo works, Clearly other website builders dont have the issue, so that doesnt seem quite right.

**Comment by asansano** [comment]
yes totally agree, now this is right thread ! and yes obviously not happening on self hosted videos. looks like the fallback img goes away too early or the implementation of transparent=1 or background=0 (vimeo) is not ok in elementor. for example slider revolution does this way better, even the compress more in the beginning, but it sounds a bit over engineered to embed vimeo ot yt over revslider into elementor... I agree with you it's not about how the streaming service works, it's about what you show till it works. so how can we link all these tickets to one and get this reopen in 2021!? @KingYes you still there?

**Comment by capstonedesign** [comment]
Hi all. I think this is the wrong thread. I didn’t message today about video backgrounds and I am receiving all of your correspondence.

**Comment by kapmes** [comment]
This needs to be fixed. The video background option is completely useless unless you have a dark website to begin with.

**Comment by sch-ma** [comment]
+1 for the same issue.

**Comment by PeteMuzz** [comment]
+1 for this. Still happening in 2022 for Vimeo and YouTube. Currenty hosting my own videos but its not ideal.

**Comment by mtorrance** [comment]
I can confirm this is still an issue. It's VERY disappointing that this has been an issue since 2017. If someone from Elementor can't respond and re-open this issue I may just cancel and switch back to WPBakery or give Divi a try. Ridiculous!

**Comment by mtorrance** [comment]
After hours of testing, reading and trial and error it seems that this works using Vimeo.
First Don't use the Video Background button on the section to set the background.
1) I made a top section full width single column, no margin or padding and dropped an html widget in it.
2) Go to Vimeo and get your embed code, the responsive one, and paste it in the html widget.
3) Then you'll need to make one edit to the URL. Just before the closing " add &amp;background=1

Here's the embed code I used.
on this test site. http://www.torrancephoto.com/centralink/

`<div style="padding:56.25% 0 0 0;position:relative;">
<iframe src="https://player.vimeo.com/video/687201880?h=5a36f4c9f3&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479&amp;background=1" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="BlueSkiesTest.mp4">
</iframe>
</div>
<script src="https://player.vimeo.com/api/player.js"></script>`

**Comment by dietcheese** [comment]
+1. Still happening with YouTube.

**Comment by pauloconnor360** [comment]
Whyyyyy!?!?! Ughhh so annoying... Elementor please fix. I have tested everything.

**Comment by matokist** [comment]
+1

**Comment by JPOak** [comment]
+1. Will this help get attention. LOL. I see other people do it so just copying. Haha.

**Comment by JPOak** [comment]
> +1 this is still an issue. I had a client complain about the flicker just after launching their new site. I see why they complained because it definitely lowers my perception of the website when my first view is a jarring flicker of the video loading.
> 
> I pieced together a temporary CSS solution for anyone who's still looking. I set the opacity on the Iframe from the section where I was using a background Vimeo video to fade in so it avoids the time at the beginning where the flicker occurs. I added this block of code to the section's Custom CSS under the advanced tab for that section. Seems to work pretty decently
> 
> ` selector iframe { opacity: 1; animation-name: fadeInOpacity; animation-iteration-count: 1; animation-timing-function: ease-in; animation-duration: 1.75s; }
> 
> @Keyframes fadeInOpacity { 0% { opacity: 0; } 80% { opacity:0; } 100% { opacity: 1; } } `
> 
> Anyone have a better solution/modification? Why is Elementor quiet about this issue?

Props for this. I need to test more, but it seems to work well with the fallback image. The video fades without the jarring flicker.

**Comment by eberswine** [comment]
> 



> 

Hey @designdevelopnow , How did you get your video background to load so quick ? What is your setup like? Section, hosted MP4? Also, do you have a fallback image ? What else did you do to get that video to play right away ? I am struggling to get one of my clients site videos to load that quick.. thanks!

**Comment by mtorrance** [comment]
Hey There,

I created a section at the top of the page and added an HTML widget with the following

<div style="padding:56.25% 0 0 0;position:relative;”>
<iframe src="https://player.vimeo.com/video/687201880?h=5a36f4c9f3&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479&amp;background=1" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="BlueSkiesTest.mp4”>
</iframe>
</div>
<script src="https://player.vimeo.com/api/player.js"></script>

replace the URL for the iframe SRC with your videos URL. I’m using vimeo to host the file.

I also applied a gradient on the section that is shown until the video loads but that could be a fallback image as well.

Hope this helps!

**Comment by joshpaschall** [comment]
I used this and it works pretty well https://css-tricks.com/prevent-white-flash-iframe/#aa-the-solution

Best solution I could find so far

**Comment by askwpgirl** [comment]
This is still a massive issue that I did not have using my former theme. We do need to solve it.

**Comment by askwpgirl** [comment]
What I've seen work for that seamless play is to specific a "poster" image for the video, like this:

`<video class="hero_background_video" poster="https://mywebsite.com/wp-content/uploads/2020/09/still.jpg" autoplay="" loop="" muted="">
                <source src="https://player.vimeo.com/external/xxxxxx.hd.mp4?s=xxxxxxxxxxxxx&amp;profile_id=xxx" type="video/mp4">
            </video>`

Imho, perhaps the fallback image should be used as the poster for the video.

**Comment by askwpgirl** [comment]
> +1 this is still an issue. I had a client complain about the flicker just after launching their new site. I see why they complained because it definitely lowers my perception of the website when my first view is a jarring flicker of the video loading.
> 
> I pieced together a temporary CSS solution for anyone who's still looking. I set the opacity on the Iframe from the section where I was using a background Vimeo video to fade in so it avoids the time at the beginning where the flicker occurs. I added this block of code to the section's Custom CSS under the advanced tab for that section. Seems to work pretty decently
> 
> ` selector iframe { opacity: 1; animation-name: fadeInOpacity; animation-iteration-count: 1; animation-timing-function: ease-in; animation-duration: 1.75s; }
> 
> @Keyframes fadeInOpacity { 0% { opacity: 0; } 80% { opacity:0; } 100% { opacity: 1; } } `
> 
> Anyone have a better solution/modification? Why is Elementor quiet about this issue?

Thank you for this CSS solution. It does work, and you can play with the animation duration depending on how long it takes the video to load.

**Comment by msnadeem96** [comment]
I've been face with the same issue and couldn't get this resolved so I resorted to jQuery:

```
jQuery($ => {
    const $vid = $('.homevid') // replce with ur id/class of the container/section
    $vid.on('DOMSubtreeModified', e => {  // using listener because iframe is not available before DOM loads. 
        if ($vid.find('iframe').length > 0) {
            let link = $vid.find('iframe').attr('src')
            link = link ? link.replace('transparent=0', 'transparent=1') : link // in my case, changing transparent seemed to work
            $vid.find('iframe').attr('src', link)
        }
    })
})
```

This is only a workaround but seems to get it working. Although TTFB is slightly increased because we are changing the url _after_ DOM loads.

**Comment by EricJammin** [comment]
Almost SEVEN years later... still not fixed.

And still no option added to simply defer the video loading or load asynchronously to improve performance either.

No wonder everyone is moving to better options like Bricksbuilder, Breakdance, etc.

**Comment by askwpgirl** [comment]
I think the tip is to avoid video backgrounds in general, but they are still ubiquitous and this not working at all really is a bummer. 

@nicholaszein - is this on the roadmap at all to fix? So many other tools handle video background loading better. Vimeo videos are the main culprit. It's a deal breaker.

**Comment by orofri** [comment]
+1

**Comment by nicholaszein** [comment]
Hello everyone, 

we did some tests and cannot reproduce the issues you are reporting. Everything loads as expected on all three major browsers, Chrome, Firefox, and Safari as you can see in the screen recording below.


https://github.com/elementor/elementor/assets/113993460/3384d830-b8ab-4cbe-bdce-9dd4feccfa78
> _In the video above you see me showing the settings of a Container with a Vimeo background using the latest version of the Chrome browser. I then proceed to switch to another tab where the post is shown in the frontend, and reload it to show it from the beginning. Next, I switch to the Firefox browser and also reload the page. I repeat the process with Safari in the last step. All browsers are set to disable any cache, which is not enable in the live server where this site is hosted (NY location)._


Keep in mind that in the example below, the placeholder image is purposefully large in file size (a whopping 7Mb) as you can see in the screenshot below. The idea is to trigger the problem you are reporting here. However, as you can see in the video above, it still loads as expected without any flickers when playing Vimeo videos.

![image](https://github.com/elementor/elementor/assets/113993460/8292b0c6-64c5-4cfa-9b30-ab5de20c797e)

This issue has already been solved a long time ago. Whatever issues you may be experiencing, could be related to your device performance, or most likely cache conflicts.

I hope with this report everyone can understand why we haven't reopened this issue.

Kind regards

**Comment by askwpgirl** [comment]
I have tested again and see that this was fixed recently. I am not seeing the black flash I was seeing before. I did have to use a CSS workaround as of last fall, so sometime in the last 6 months, this was addressed.

**Comment by askwpgirl** [comment]
An issue that is persisting with this is that if you use a background overlay, it is applied 2x to the fallback image. So if you set to 35%, the fallback image appears very dark, then the video displays lighter. 

https://www.loom.com/share/0485366d2ccb49e6a35514d67bfccaec?sid=6bf8a975-b273-4839-ae60-33d01e52fb8b

But this is separate for a separate ticket I can create.

**Comment by nicholaszein** [comment]
Thank you for reporting this was fixed @askwpgirl!

I am closing the comments on this issue, as things have changed significantly over the years, and no longer match our requirements. If anyone thinks this is still an issue, we ask you to please open a [new Bug Report](https://elemn.to/gh-new-bug-report), and we will take a look on it!

Kind regards
