### ISSUE TITLE
Option to interpret line breaks in non-WPEditor fields

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1647]
Currently if I want to use multiple lines in the title field of elements (or in other fields where a WP visual editor doesn't make sense) I currently have to use ```<br />``` to force a line break, like so: 

![image](https://cloud.githubusercontent.com/assets/1435638/25467662/fe51305e-2b4e-11e7-9639-1feac7076ad2.png)

My clients often don't know what ```<br />``` does or they might accidentally delete a bracket which of course messes up the layout. It would be awesome if a return character (eg. splitting the line naturally with the Enter key) would interpret as ```<br />``` in the HTML output.

I know this change will probably break a ton of websites if implemented, so I had an idea that you could have a toggle option in the Elementor preferences page, to interpret line breaks as ```<br />``` or maybe even a filter that can be used in a template (similar to [wpautop](https://codex.wordpress.org/Function_Reference/wpautop) )

**Comment by KingYes** [comment]
Hi drawcard

We are currently developing a new logistics for the fields and it might meet your needs.
