### ISSUE TITLE
Use Lightbox script for other elements on site?

### ISSUE THREAD

**Issue by katart** [pojome/elementor#1651]
Can that lightbox script be used (or targeted) in other areas of the site?

**Comment by KingYes** [comment]
Hey @katart 

It's not LightBox script. It's just custom JS code with write this video widget. Maybe in feature release we include LightBox lib..

**Comment by katart** [comment]
It would be nice to have a trigger for a lightbox function throughout the site; at least for consistent style/design reasons. 

It's not user friendly for the site visitor or the site designer to have different modal styles throughout the site. If I use Elementor's built-in Video Lightbox functionality and then have to use another plugin for an image Gallery Lightbox or a Modal popup window, I will most likely have different style popups. That is not good design.

Elementor should really consider allowing a consistent Modal/Popup/Lightbox style throughout the site.
