### ISSUE TITLE
On tab widget, configure separately the content background and the tab header background

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#1652]
Currently, the background style is applied to both the tab header and the tab content. This results in a visually unappealing display on a smartphone, where you do not readily see the contrast between the tab header and either the previous tab of the content of the tab. Being able to set the background colors separately. Would improve the readability.

**Comment by arielk** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
