### ISSUE TITLE
Tab background color inconsistent between wide and narrow screens

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#1653]
On a wide screen, the background color is displayed only on the currently selected tab. THus, the other tab headers have a different background color and are easily distinguished one from the other. On a narrow screen, however, all the tabs are always displayed with the same background color, no matter which one is selected. If the behavior were as for the wide screen, it would be easier for the user to see just where he or she is among the various tabs.

**Comment by arielk** [comment]
I'm not sure I understand exactly what you mean, can you please explain more clearly?

**Comment by JosiahCarberry** [comment]
OK. go to www.3cs.ch/consulting-coaching-services/. You will see on that page tabbed output. If you view it with a telephone or other narrow screen, all the tabs, both the tab labels and the contents, have the same background color, which doesn't change no matter which tab you select. If you view the same page on a wide screen, say, a laptop, then the background color for the non-selected tabs is different than the background color of the selected tab. In my view, this latter display is better. In any case, I would expect the same styling, no matter what the viewport size.

**Comment by arielk** [comment]
I do not think it's a bug, this is reasonable behavior in mobile mode, it is just like an Accordion widget.

Thanks for your feedback!

**Comment by JosiahCarberry** [comment]
Well, so much for the customer always being right! Your response is frustrating.

**Comment by arielk** [comment]
You're right! Do you have any suggestions on how to create a better mobile view?

**Comment by JosiahCarberry** [comment]
Here is what I would expect:

1) Initial display:
The first tab is displayed with a shaded background. All other tabs are displayed with a white background. (This is not what I see on my phone. All tabs have shaded background.)

2) After tapping on a different tab:
The first tab changes to white background. The tapped tab changes to a shaded background. The other tabs remain unchanged.

I note that font color of the label of the tab is indeed changing, depending on which tab is selected, and I am fine with that.
