### ISSUE TITLE
sizes attribute

### ISSUE THREAD

**Issue by strarsis** [pojome/elementor#1654]
Elementor columns break at specific breakpoints, it would be great if the sizes-attribute of the images is adjusted accordingly. Just defining a static size won't help with this issue because the image size changes continuously (responsive, not just adaptive layout), hence there should be an individual size in vw for each breakpoint.

**Comment by drawcard** [comment]
I like this idea. I currently use media queries in Custom CSS for that kind of thing.

**Comment by arielk** [comment]
The all images in Elementor already come with a special size for each device using the built-in WP function: https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/

Screenshot attached:
![iazwyot](https://cloud.githubusercontent.com/assets/1778512/26173801/d2bb9594-3b55-11e7-9659-96fb45bf9f2a.png)

Thanks for your feedback!
