### ISSUE TITLE
scroll-to anchor problems

### ISSUE THREAD

**Issue by jerzyk** [pojome/elementor#1655]
On chrome (tested on 57) there is an issue, when clicking on a links with anchor (with #id):
- when trying to scroll up or down when visible part of the animation looks like finished, there is a fight with the script itself - trying to scroll, and script is scrolling to the previously selected position (missing canceling of this transition by scroll event)
- history is ignored, every click is handled within script without proper handling of the history, can't go back 

Additionally, scrolling is hardcoded and enabled for every `.elementor-element` and menu-anchor widget making it difficult to override, because there are no options to disable it (nor globally, nor per page) - which is a great nice-to-have.

**Comment by parfilov** [comment]
Yeah! It works strange. Sometimes scrolling to right point, sometimes wrong and sometimes stops in ~200-300px to anchor.
Kinds browsers the same problem.

**Comment by carasmo** [comment]
I don't see the issue but there should be history support. Actually this smooth scroll should be something that we can remove if we don't want it. I had my own perfectly working version and this messed up my version.

**Comment by arielk** [comment]
We made some corrections in Anchor Menu, please update to the latest version and let me know if this solved your problem.

**Comment by parfilov** [comment]
I've found the cause. It was lazy load. When page is loading images are not load and page to anchor were mistake. After page scrolled down and images fully load scroll to anchor worked fine.

**Comment by arielk** [comment]
Thanks for your update!

**Comment by coder618** [comment]
How to set offset for default element smooth scroll
