### ISSUE TITLE
Video lightbox alignment

### ISSUE THREAD

**Issue by damjanuzelac** [pojome/elementor#1656]
## Description

At some browser widths between desktop, tablet and mobile the video image is aligned left and there is no way to get it to be centered without playing around with padding.

**Is it possible to add an alignment option?**

## Steps to reproduce

Place a video widget and activate lightbox feature (with an image overlay).

**Comment by arielk** [comment]
Can you please share the link to page with the problem?

**Comment by damjanuzelac** [comment]
You can check it out here: nova.angla.hr
**note the switch from tablet to mobile**

**Comment by arielk** [comment]
Everything looks great, which browsers should I check it out?

**Comment by damjanuzelac** [comment]
Hm, I use chrome. Here's a screenshot: [https://www.imageupload.co.uk/images/2017/05/04/align.jpg](url)

**Comment by arielk** [comment]
Sorry, but I see columns on both sides of the video and can not seem to see the problem
