### ISSUE TITLE
what this code does ? i know its a very basic question 

### ISSUE THREAD

**Issue by techsaqib** [pojome/elementor#1657]
/*! elementor - v0.11.2 - 21-11-2016 */
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var HandleAddDuplicateBehavior;

its in the editor.js files and in many files , i want to understand , this plugin also use required() function as much as i know this function is related to nodejs , how it can be used in wp plugin 
and  what is  ( 1:[function() do in this code its starts from 1 to 100 

please explain  this code , is something new come in javascript 

reply as soon as possible

**Comment by KingYes** [comment]
This created by Browserify. WordPress media also work with this: https://make.wordpress.org/core/2015/01/22/the-case-for-js-modules/
