### ISSUE TITLE
Editor panel add section/templater filter

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#1658]
Hello Elementor team :)

Other than hacking the Editor global file to introduce my own templates file selector button, is there an easier way to achieve the following?

![elementorpanelglobal](https://cloud.githubusercontent.com/assets/16872407/25559996/247655c8-2d40-11e7-9eb2-da09b614603c.png)

If not, could you consinder adding a filter to `$_editor_templates` so that it can be manipulated for additions?

**Comment by Basilakis** [comment]
Reference: https://github.com/pojome/elementor/issues/1634

**Comment by bainternet** [comment]
Same as [this](https://github.com/pojome/elementor/issues/1634#issuecomment-349231472).

will be added to our developer docs once there is something formal.
