### ISSUE TITLE
Fit to screen and column position setting does not stick on mobile

### ISSUE THREAD

**Issue by pixelxcode** [pojome/elementor#1668]
## Steps to reproduce
1. Set section height to "Fit to screen"
2. Column position set to "Bottom"
3. Switch to mobile view
4. Setting does not work.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.44
	PHP Version: 5.4.45
	PHP Max Input Vars: 1000
	PHP Max Post Size: 55M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.4
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.1165

== Active Plugins ==
	Advanced Custom Fields
		Version: 4.4.11
		Author: Elliot Condon

	All In One SEO Pack
		Version: 2.3.12.4
		Author: Michael Torbert

	Anti-Malware Security and Brute-Force Firewall
		Version: 4.16.53
		Author: Eli Scheetz

	Elementor
		Version: 1.4.4
		Author: Elementor.com

	Elementor Pro
		Version: 1.2.6
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 3.3.0
		Author: Shane Bishop

	Instagram Feed
		Version: 1.4.8
		Author: Smash Balloon

	Ocean Extra
		Version: 1.2.1.2
		Author: OceanWP

	Ocean Hooks
		Version: 1.0.0
		Author: OceanWP

	Ocean Modal Window
		Version: 1.0.6.1
		Author: OceanWP

	Ocean Sticky Header
		Version: 1.0.5
		Author: OceanWP

	Popup Maker
		Version: 1.6.0
		Author: WP Popup Maker

	Sticky Menu (or Anything!) on Scroll
		Version: 2.0.1
		Author: Mark Senff

	SVG Support
		Version: 2.3.8
		Author: Benbodhi

	TapTap, by Bonfire
		Version: 3.4
		Author: Bonfire Themes

	The Grid
		Version: 2.3.5
		Author: Themeone

	UpdraftPlus - Backup/Restore
		Version: 1.12.40
		Author: UpdraftPlus.Com, DavidAnderson

== Debug ==
	Errors: 
		TypeError: elementorFrontend.getScopeWindow(...).jQuery is not a function
			at http://(url redacted)/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.4 - 6:21499
			2017-04-24 13:55 +00:00

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
