### ISSUE TITLE
Feature requests: A/B Testing Pages (split test)

### ISSUE THREAD

**Issue by VadymVolos** [pojome/elementor#1669]
Hi! 
Idea: A/B Testing Pages (split test)

Does the idea match your development?
Thanks

**Comment by VadymVolos** [comment]
Maybe: Experiments API

https://support.google.com/analytics/answer/1745210?hl=en&ref_topic=1745207

**Comment by arielk** [comment]
Elementor does not include a/b split testing feature.

However, this is something you can do with [Google Optimize](https://www.google.com/analytics/optimize/) for free: https://www.youtube.com/watch?v=vDDMMbhvSVU

You can also use plugin like this: https://wordpress.org/plugins/simple-page-tester/

**Comment by thenovacreator** [comment]
And you can use the new split test for elementor plugin: https://wordpress.org/plugins/split-test-for-elementor/
