### ISSUE TITLE
Feature requests: Image Gallery (Full screen show: Previous Image,  Next Image)

### ISSUE THREAD

**Issue by VadymVolos** [pojome/elementor#1670]
Image Gallery (Full screen show)
Link to: Media File
Need add buttons: Previous Image,  Next Image.

Thanks!

**Comment by Basilakis** [comment]
That is plugin thing, nothing to do with Elementor and what elementor is supposed to be :)

**Comment by VadymVolos** [comment]
Easy FancyBox
https://wordpress.org/plugins/easy-fancybox/

Works with this plugin!
You need to add this information to the instruction for Elementor.

**Comment by arielk** [comment]
There is a lot of lightbox plugins in the WordPress repository, just pick one like https://wordpress.org/plugins/simple-lightbox/ or https://wordpress.org/plugins/easy-fancybox/

Thanks for your feedback!
