### ISSUE TITLE
Content flashes before entrance animation

### ISSUE THREAD

**Issue by teaganm** [pojome/elementor#1672]
## Description

Just recently I have found that when I add an animation to an element and then view the page, the content will appear for a brief moment before the animation runs. I don't think this happened with previous versions of Elementor.

Here is a quick video where you can see the content flash before the animation: https://cl.ly/0O390t0u2D22

The video was captured in the Chrome browser on a site running WP 4.7.4 on Twenty Sixteen with no plugins other than Elementor 1.4.5.

On macOS I see the issue when viewing in Chrome or Firefox, but not Safari.

## Steps to reproduce

1. Add content
2. Add an animation onto the widget or the section
3. View the site in Chrome or Firefox and go to another page and then back to the page in question

## Environment

https://pastebin.com/rhPJwZR2

**Comment by kobizz** [comment]
It's a known problem that will be fixed by the next release.

**Comment by Ricarditu** [comment]
Hi!

Despite being an issue with over a year now, I'm still getting this.

I animated a section and it flashes before it animates. If I apply some delay, it appears for a while longer (maybe 200/300ms) and then it animates normal. But the fact of appearing before the animation completely spoils the effect.

Please, check the video at the link below:
https://drive.google.com/file/d/18KC9asJ-Muubb-mFXs4-GX1GSyPGwo-C/view

Another detail, I also enabled the scrolling effect to Sticky Upper and Effects offset s now, besides the previous issue, I also have a duplicate in the element animation.

Please, check the video at the link below:
https://drive.google.com/file/d/1cNfeBGjCv8pQlUIq7wcHlNFeM_WS8jft/view

I'm using:
- WP 5.0.1
- Astra 1.6.1
- Elementor 2.3.5
- Elementor Pro 2.2.5
- all other plugins disabled

on Chrome 71.0.3578.80.

Thank you!

**Comment by fourstripes** [comment]
This get solved?

**Comment by pckz** [comment]
same issue for me, the appear effect is not effective because wehen you enter the page, image loaded is displayed, blink to be hide, and after that is animated to entrance... same as video reported by @Ricarditu

**Comment by lockstock123** [comment]
I am also seeing this issue, makes the site look really crappy and not professional at all.

**Comment by vitezcommerce** [comment]
Instead to use Elementor widget for Image, use Elementor widget for text and then click button Add media, to add image you want to text widget, adjust size and position as you want and the image will not appear before animations starts. It is likely that flashes or flickers of images before animations appears when using Image widget, Image carousel or anything like that...
