### ISSUE TITLE
Default Template

### ISSUE THREAD

**Issue by rafaael-figueiredo** [pojome/elementor#1673]
It's needed to add an option to set the default template. This way ever we open the elementor page a default template is called.

**Comment by carasmo** [comment]
Do you mean the **elementor_library** post type? In your theme create template named:

single-elementor_library.php

See:
https://developer.wordpress.org/themes/basics/template-hierarchy/

**Comment by rafaael-figueiredo** [comment]
Hi Carasmo,

Thanks for your answer but my issue is with elementor. I want to create a elementor template and when create a new page it imports the default elementor template automatic.

There is a class (importTemplate) inside editor.js. I want to use this function to extends and create a plugin to do what I'm mentioning above. There is a way to extends this class inside my plugin?

**Comment by KingYes** [comment]
When Elementor create new blank page, this code running: https://github.com/pojome/elementor/blob/c64f26f9d7369454d1e62e69a47a59f0547c5351/includes/db.php#L132

So, what you think about any filter to handle with that by your plugin/theme?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by xttn** [comment]
Hi, i have same issue here.  I want to create a elementor template and when create a new page it imports the default elementor template automatic.
Are you complete your code @rafael-figueiredogluz  ?

**Comment by jrc2** [comment]
@arielk I am trying to make it so when I add a new page, certain elements are already there. SHould I open a new issue, or is that what this is about? I'm not quite sure what @KingYes is saying to do.
