### ISSUE TITLE
Adding JS capability to functionality

### ISSUE THREAD

**Issue by Kenko76** [pojome/elementor#1679]
Is it possible to add JS support to the Elementor widgets. I want the ability to add a JS code to hide email addresses in the html code to prevent spambots. 

All the Pojo widgets allow for this, but Elementor does not

thanks
Ken

**Comment by KingYes** [comment]
Hey @Kenko76 

What you mean about JS support?

**Comment by Kenko76** [comment]
I have used Pojo forms on my contact page:

http://thinkstaging.com/think2016beta/contact-us

Within the email dropdown box it allows me to add some simple code to hide the email address within the main html code, but if I try to add it to the Elementor flip boxes button it doesn't recognise it.

The code is:

mailto:john.innes@thinkpublishing@@@@@@@" onmouseover="this.href=this.href.replace('@@@@@@@','.co.uk')"

**Comment by KingYes** [comment]
I really don't understand you.. sorry.. How in Pojo widgets you can do that? Can you show me screenshot on this?

**Comment by Kenko76** [comment]
the code is added to this box
![screen shot 2017-05-04 at 16 17 47](https://cloud.githubusercontent.com/assets/28388305/25710968/ad5baaa2-30e5-11e7-8d05-b06351cc870a.png)

**Comment by KingYes** [comment]
Where you write your JS code?
