### ISSUE TITLE
PRICING TABLE TOOLTIPS?

### ISSUE THREAD

**Issue by mickyriquelme** [pojome/elementor#1680]
Hi!
How do I add tooltips on pricing tables?

It is possible to have tool tips on pricing tables for each feature? It would be great to show a description of each feature when someone hovers over the column. 
Thank you in advance for your help.

**Comment by drawcard** [comment]
I have used https://github.com/iamceege/tooltipster on Elementor elements in the past, and it works great. The content for the tooltips can go into a hidden div on your page and can be called via Tooltipster's JS.

**Comment by parfilov** [comment]
I vote "YES" with tooltips!

**Comment by arielk** [comment]
To be honest, we do not have a plan to add a Tooltip for this widget, so for now I close the issue, maybe in the future we'll add it.

Thanks for your feedback!
