### ISSUE TITLE
element preview js 

### ISSUE THREAD

**Issue by michellomp** [pojome/elementor#1681]
Hi I've create a parallax widget for elementor it works great except in the preview. The js are enqueue in the preview but does nothing. I wonder if there's a hook for preview. Just find a css hook for preview elementor/preview/enqueue_styles but no js one. 

```
( function( $ ) {
	var WidgetHelloWorldHandler = function( $scope, $ ) {
		$scope.find('.jarallax').jarallax({
		    speed: 0.2
		});
	};
	
	// Make sure you run this code under Elementor..
	$( window ).on( 'elementor/frontend/init', function() {
		elementorFrontend.hooks.addAction( 'frontend/element_ready/parallax.default', WidgetHelloWorldHandler );
	} );


	
} )( jQuery );
```

Thanks

**Comment by KingYes** [comment]
When this widget rendered, this code will be run.. Why you need more codes for preview code?

**Comment by michellomp** [comment]
@KingYes It may be interesting to see a widget working in the preview no ?

**Comment by KingYes** [comment]
You just register your JS files in frontend mode, and Elementor take a care on preview..

**Comment by michellomp** [comment]
I register them as you did in your hello world plugin. 
```
private function add_actions() {
		add_action( 'elementor/widgets/widgets_registered', [ $this, 'on_widgets_registered' ] );
		add_action( 'elementor/frontend/after_register_scripts', function() {
			wp_register_script( 'jarallax', plugins_url( 'parallax/js/jarallax.min.js'), [], false, true );
			wp_register_script( 'parallaxi', plugins_url( 'parallax/js/parallaxi.js'), [ 'jquery','jarallax' ], false, true );
		} );
	}
```
Is this what you mean by frontend mode ?

**Comment by KingYes** [comment]
And you override your `get_script_depends()` method?
( ref: https://github.com/pojome/elementor-hello-world/blob/master/widgets/hello-world.php#L38 )

**Comment by michellomp** [comment]
yes

**Comment by KingYes** [comment]
If you write like this:

```
public function get_script_depends() {
		return [ 'jarallax', 'parallaxi' ];
	}
```

It's need to work to you. What your console error log?

**Comment by michellomp** [comment]
I gave me a TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.

**Comment by KingYes** [comment]
Can you print me your trace code?

**Comment by michellomp** [comment]
![error](https://cloud.githubusercontent.com/assets/13666439/25714339/f42b592a-30f7-11e7-876f-a40ebfddecb2.png)

**Comment by michellomp** [comment]
![error2](https://cloud.githubusercontent.com/assets/13666439/25714603/d51dc684-30f8-11e7-9321-b9bd33ea24ac.png)

**Comment by michellomp** [comment]
Is that what you mean by trace code ?

**Comment by michellomp** [comment]
I replace
```
 $scope.find('.jarallax').jarallax({
		    speed: 0.2
		});
```
by
```
 jarallax(document.querySelectorAll('.jarallax'), {
    speed: 0.2
});
```
the error disappears but it still doesn't work in preview
