### ISSUE TITLE
Feature requests: Background -  Attachment: Parallax scrolling

### ISSUE THREAD

**Issue by VadymVolos** [pojome/elementor#1682]
Hi! :)

Edit Section - Background -  Attachment: Parallax scrolling
Example: http://materializecss.com/parallax-demo.html

Is it possible to do this?
Thanks!

**Comment by badcat** [comment]
@VadymVolos Maybe these are helpful?
https://wordpress.org/support/topic/parallax-in-elementor/ 
http://snifflevalve.com/tutorials/elementor-parallax-section-background-image/

**Comment by VadymVolos** [comment]
@badcat thanks!
https://youtu.be/bqIvPFssa3k

But I wanted it to work by default ...
