### ISSUE TITLE
Elementor Pro Mailchimp not showing all lists

### ISSUE THREAD

**Issue by armada** [pojome/elementor#1683]
I can only see 10 list in the new mailchimp form feature. I have more than 35 lists in my mailchimp account. See attached image for reference.

![mp error](https://cloud.githubusercontent.com/assets/17282554/25735894/222a6e20-31a1-11e7-9e1b-1ed20a381e25.png)

**Comment by armada** [comment]
Any answers to this? I read somewhere that the default list in mailchimp is 10. Can elementor override that value?

**Comment by arielk** [comment]
Fixed for the next version E-Pro 1.4.4.

Thanks for your report!

**Comment by armada** [comment]
Thank you very much!
