### ISSUE TITLE
Can't see "link options" modal

### ISSUE THREAD

**Issue by Twisterking** [pojome/elementor#1684]
When I want to edit a link inside a simple text, the modal does not show up! I only get two weird rectangles in the upper left corner (one grey, one blue). See [Screenshot](http://666kb.com/i/diyb8agivkjnktyhw.png).
Chrome 57.0.2987 on a Mac

**Comment by katart** [comment]
Are you using another plugin to change the TinyMCE Editor? Maybe the TinyMCE Advanced plugin?

**Comment by Twisterking** [comment]
Hmm yes and no. When I tried Elementor I had installed the [SiteOrigin Widget Bundle](https://srd.wordpress.org/plugins/so-widgets-bundle/) - maybe this was somehow interfering?! I will try it again while having the Widget Bundle deactivated.

**Comment by KingYes** [comment]
Please deactivate all your plugins and try again..

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
