### ISSUE TITLE
Responsive feature does not work in some (popular) smartphones

### ISSUE THREAD

**Issue by gfdesign** [pojome/elementor#1687]
## Description

Firstly, I am big fan of Elementor. Congratulations for such as great tool!

I want to inform that Elementor responsive feature does not work well in some versions of popular smartphones like Iphone and Samsung. To be sure, I've installed the last WP versión at the moment (4.7.4) with default theme 'Twenty Sixteen' and no plugins, except Elementor and I've created a blank page with two columns, in one just text and the other one an image, but when you visit the site with Iphone 6 for example, the columns remains together. You can take at look here https://goo.gl/N4D49b

I've tested the page using Browserstack and unfortunately I can confirm the responsive feature of Elementor wouldn't work as expected in some smartphones.

## Steps to reproduce

1. Install Wordpress with a default theme as 'Twenty Sixteen'
2. Create a page and set up content using more than one column with Elementor.
3. Visit that page with some smartphone as Iphone 6, Iphone 5S or Samsung Galaxy S3, you'll see the columns remains together and push up outside of container.

## Environment

Wordpress: 4.7.4
Elementor: 1.4.5
Theme: Twenty Sixteen 1.3
PHP: 7

_Here some captures:_

**Safari on iPhone 6**
OS: iOS, v8
Browser: Safari
<img src="http://i.imgur.com/zparbcp.jpg" alt="Iphone6" />

**Chrome on iPhone 5S**
OS: iOS, v7
Browser: Chrome
<img src="http://i.imgur.com/DBw4rG3.jpg" alt="Iphone5" />

**Samsung Galaxy S3**
OS: Android 4.1
<img src="http://i.imgur.com/mkjCzzQ.jpg" alt="Samsung Galaxy S3" />

I hope this info helps.
Best regards

**Comment by drawcard** [comment]
Have you checked these out on real phones or just BrowserStack?

**Comment by carasmo** [comment]
I can confirm this issue on IOS 8, gone in 9, and back in 10 (but I can't test 10). It or a variation of it is listed in many places, here's some:

https://bugs.webkit.org/show_bug.cgi?id=136041#c2
https://github.com/angular/material/issues/1720
https://github.com/angular/material/issues/10516
http://stackoverflow.com/questions/35489725/iphone-6-flexbox-wrapping-issue

To correct this since it's VERY horrible:
What I did is to make sure my theme css file priority, is **after** elementor's css and then since Elementor starts stacking at 767px, I added the following to correct this. 

Ideally, if Elementor would use mobile first, the display: flex should go on a min width and not be set below that, then this would not be a problem since block would not need to be reset like this. 

```
@media screen and (max-width: 767px) {
	.elementor-row {
		display: block;
	}
}
```

**Comment by gfdesign** [comment]
@drawcard yes, I discovered it when I was reviewing a site that I am working on through real smartphones, then I've tested on BrowserStack to be sure.

@carasmo Your solution worked on the site I've put here but no luck on site I am working on. I supose this is because I have more than two columns. I'll have to see.

Some more devices I've tested on BrowserStack:
Nexus 4
Android 4.2
<img src="http://i.imgur.com/86HPQYp.jpg" alt="Nexus" />

Xperia Tipo 
Android 4
<img src="http://i.imgur.com/07jY603.jpg" alt="Xperia" />

**Comment by carasmo** [comment]
I have any amount of columns and it works. But if this is not after Elementor's CSS, then it won't work.

**Comment by gfdesign** [comment]
@carasmo How did you do to place your css rule after Elementor's css? What I did was to put it in my child theme using an !important declaration. But as I said, in my current development it does not work, but it works on the site I indicated here.

**Comment by carasmo** [comment]
Sorry, I didn't see this until now.  I used `elementor/frontend/after_enqueue_styles` hook in my child theme or plugin to put custom Elementor specific CSS after all of Elementor's CSS.

**Comment by carasmo** [comment]
I do hope that the devs will correct this. It's on a lot of phones and what 
 It's on a lot of phones and what. Display block to correct this is will prevent the Reverse Mobile option.

**Comment by gfdesign** [comment]
Thanks @carasmo 
I'll try. Yes, I hope the same.
Regards

**Comment by arielk** [comment]
@gfdesign 
In Elementor v1.4.8, we added CSS support in the last 5 versions of browsers, can you please update and check if this problem has been resolve?

**Comment by gfdesign** [comment]
I've updated the plugin.
Now it's working. Thanks for corrected it.
Regards

**Comment by gfdesign** [comment]
Dear support
Unfortunetly, in one of Elementor upgrades, this issue has back :(
Could you review it again please?
https://goo.gl/N4D49b

**Comment by gfdesign** [comment]
This ticket is closed but the issue is back :(
Please, could you review it again?

**Comment by gfdesign** [comment]
Will you resolve this issue sometime?

**Comment by eplanetdesign** [comment]
This needs to be fixed.

**Comment by lhwitherspoon** [comment]
Yes. It's showing up on my both my iPhone 8+ and a Nokia 6.1 (Oreo 8.1) Plus Moto G4 (Nougat 7.0). Please fix - I've got an entire website that's not mobile.

**Comment by Latigresa** [comment]
It's happening to me today. full width is not showing on iphone 8+ and ipad

**Comment by mredodos** [comment]
the problem occurs again, on apple devices and some android versions, but not on the entire site only on some pages
