### ISSUE TITLE
Feature request list

### ISSUE THREAD

**Issue by ghost** [pojome/elementor#1689]
Hy don´t know if there´s a place to put these gathered experiences...

1) Custom Font integration
There should be a custom font integration that actually leads to a standard pulldown with all custom and standard fonts in the list of every type containing element
Reference:
http://useanyfont.com

2) Interactive CSS Styleguide
All CSS informations should be visually gathered in one place sorted within sections such as Typography, Colors, Buttons, Imagesizes, Icons etc. and if necessary all widgets and the style presets done for them. At that place the user should be able to see small previews and make edits directly in the in this style overview.
Reference:
http://stylifyme.com

3) Custom Menue
Elementar should have it´s own menu widget with lots of predefined options but still connected to the main wp menue panel
Reference:
https://de.wordpress.org/plugins/navmenu-addon-for-elementor/

4) Custom Breakpoints
There should be the option to modify existing breakpoints or even add custom ones
Reference:
http://waspthemes.com/yellow-pencil/
https://www.elegantthemes.com/plugins/divi-builder/

5) Block Builder or Wireframe View
There should be the option to view the site without the css styling information to more easily setup and structure the sites content.
Reference: 
https://www.elegantthemes.com/plugins/divi-builder/
http://waspthemes.com/yellow-pencil/

6) In-Editor Drag and Drop Margin and Padding
Not only the column width should be dragable in the editor but also all margins and paddings of all elements
Reference:
https://www.elegantthemes.com/plugins/divi-builder/

7) CSS Animation Builder
There should be a timeline+layers based keyframe editor to build or customise CSS animations
Reference:
http://waspthemes.com/yellow-pencil/

8) Responsive Editorview
Browser width should toggle breakpoints media query views not only the dedicated device buttons in the customizer panel
Reference:
https://www.elegantthemes.com/plugins/divi-builder/
http://waspthemes.com/yellow-pencil/

9) User votable feature top 100 wishlist
There should be an interactive simple feature wishlist flowchart where users can vote on features that are brought into functional and roadmap categories and duplicates-cleaned by the elementor-team
Reference:
Never seen anything like that but the classic feature forums are always a mess

**Comment by Ver3** [comment]
Number 9 would be awesome! As long as it doen't hamper the creativity of the team. Them going exactly for what they believe in, is also a nice though. But having a votable list like you suggest 'for consideration' would really be nice.

**Comment by dasigna** [comment]
... actually most desired one would be No.4. - custom breakpoints!

**Comment by ramonztro** [comment]
I think your suggestions are great. Anyway, I feel like they would be better discussed and would had more chance to be implemented if they were broke down into different specific posts.

I would like to see number 9.

**Comment by bainternet** [comment]
@ghost

- Custom Font integration:  https://elementor.com/custom-fonts/
- Custom Menu: https://docs.elementor.com/article/244-nav-menu
- Custom Breakpoints - Dup #78
- Block Builder: https://elementor.com/introducing-blocks/
- Responsive Editorview: its in elementor sence v0.1 
![xkrvlhx](https://user-images.githubusercontent.com/660572/39418738-c9d03478-4c64-11e8-8323-14341cdb1dcf.png)


As for the rest, maybe in the future.

thanks.

**Comment by hufer** [comment]
https://pafe.piotnet.com/#custom-media-query-breakpoints Custom Media Query Breakpoints Feature in Piotnet Addons For Elementor Pro can do it for you
