### ISSUE TITLE
[Feature Request] Edit WooCommerce Product Pages with Elementor

### ISSUE THREAD

**Issue by Ver3** [pojome/elementor#1690]
When you currently try to Edit a Woo Product, you can only edit the description. It would be very useful for shop owners to be able to edit and style all elements on a product page.

Several plugins (Like Elementor Anywhere, WooStore for Elementor and Press Elements) have proven it to be possible. But none hit the mark just right or come with a lot of other stuff you don't need (even Widgets already in the Pro Version).

**My ideal would be this (for Elementor Pro version)**

- Go to a product and Edit with Elementor.
- All Woo Elements (like Title, Price, Add to Cart button, etc..) will be 'transformed' to an upgraded version of the current Woo Elements Widget.
- Now simply style the page as you please.

This would prevent the need for separate info-, and product pages. It will also open possibilities no other builder currently offers. This would make Elementor a MUST for shop builders/owners.

**Does the above make sense?**

Please let me know. If needed, I'll make mockup screenshots to further clarify.

**Comment by arielk** [comment]
It's definitely something we're working on.

I merged this issue with another issue https://github.com/pojome/elementor/issues/543 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by Ver3** [comment]
@arielk Ok, I will go there (this will be my last comment here) Just wanted to say how much I appreciate your work and thanks for getting back to me. Cheers.

**Comment by abdusfauzi** [comment]
Released in 2.1! Awesome!
