### ISSUE TITLE
PHP shortcode in Elementor Select Dropdown. Show/Hide Labels on Desktop/Mobile

### ISSUE THREAD

**Issue by vinner0** [pojome/elementor#1692]
## Description

I am trying to create a form with a dropdown box. The dropdown options will come from a PHP script. I wrote the shortcode in the Form field options, but it did not expand into the output. 

Please create a way to get a php generated list into a form field dropdown using Elementor. 

Also, I want to display labels in the Desktop version of the form, but no labels in the Mobile version of the form. I could not find the option to selectively enable or disable labels for a responsive site.  Suggest that you build this into Elementor Forms options.

**Comment by bainternet** [comment]
@vinner0 

You can already do that by registering a custom field type which would extend the select field and would get its options/choices from dynamic PHP settings.

as for the labels its currently only available via custom CSS only

thanks for the feadback.

**Comment by KyleDotNet** [comment]
> @vinner0
> 
> You can already do that by registering a custom field type which would extend the select field and would get its options/choices from dynamic PHP settings.
> 
> as for the labels its currently only available via custom CSS only
> 
> thanks for the feadback.

Would you mind sharing the method of filling the select field with custom options via PHP?

**Comment by besaanigit** [comment]
gus how to active two labels other lebels is disable when i choose category job with php, please help this code
