### ISSUE TITLE
Feature request: option to set first (all) item in accordion closed by default

### ISSUE THREAD

**Issue by tscheipi** [pojome/elementor#1694]
an option to set first (all) item in accordion closed by default woult be great

**Comment by nickdgreen** [comment]
There is already a plugin to do this https://github.com/WPDevHQ/universal-functions

**Comment by tscheipi** [comment]
I will not be able to do anything about it but to be honest, with the answer I´m not satisfied. You have a lot of outstanding widgets but some of them are somehow not completely. E.g. this one, or the form-widget where I miss the ability to upload files or to make a checkox required (e.g. as a confirmation of terms of service). In my opinion these should be standard features. Often I get the answer to use another plugin for this and that but is this a solution? Using a lot of plugins just to complete elementor will end up in an unnecessary elementor.

**Comment by arielk** [comment]
If you want all items to be closed, please use the Toggle widget for this: http://docs.elementor.com/article/115-toggle

Thank you very much for your feedback!
