### ISSUE TITLE
Feature Request: Text Shadow Controller

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#1696]
## Description

It would be awesome if there could be a "**Text Shadow**" controller.

`text-shadow: {horizontal-shadow} {vertical-shadow} {blur} {color);`

Elementor already has a similar (and a very useful) "**Box Shadow**" controller.

`box-shadow: {horizontal-shadow} {vertical-shadow} {blur} {spread} {color};`

![elementor-box-shadow-controller](https://cloud.githubusercontent.com/assets/576623/25784859/e77bb882-337c-11e7-8439-6aa2ec6dacda.png)

**Comment by ramiy** [comment]
I should mention that the [text-shadow](https://caniuse.com/#search=text-shadow) property has better browser support than [box-shadow](https://caniuse.com/#search=box-shadow).

**Comment by drawcard** [comment]
As a current workaround you can add the CSS you need to do this in the "Custom CSS" field.

**Comment by ramiy** [comment]
Yes, I know that but I'm not talking as a user, I'm talking as a plugin developer.

Firsts I wanted to develop my own text shadow widget. But on second thought - a core Elementor controller seemed to be a better solution. This way **all** the widgets can use it. Including external plugin developers.

**Comment by drawcard** [comment]
Sorry I misunderstood :)

**Comment by arielk** [comment]
https://github.com/pojome/elementor/pull/2048/
