### ISSUE TITLE
[Request] File attachment function for Elementor /E Pro form

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1697]
Hi, I am currently building a form in Elementor, as a basic bug tracker for clients:

https://drawcard.com.au/support

I would like to add the ability to let the client upload a file (eg a screenshot) to the form repsonse, through the form. Is there a plan to add that sort of functionality in the near future?

Bonus awesomness: If you can specify max upload size & whitelisted file attachment extensions!

**Comment by arielk** [comment]
I merged this issue with another issue #1482 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
