### ISSUE TITLE
[Bug?] Missing Content below Posts after Editing with Elementor Page Builder

### ISSUE THREAD

**Issue by chrisk87** [pojome/elementor#1700]
Hi,

i use the elementor page builder and found a bug. I hope you can help and check it.

I create all my posts with the Elementor page builder. All is showing corretly.

After i edit with the elementor page builder the posts again following happens:

- lose related posts, that are displayed under the main post article (Yuzo - Related Posts Plugin) 
- lose social media icons under the post (Easy Social Share Buttons Plugin)

It's only happens if i edit the post with elementor. If i edit the post with normal wordpress functions, nothing wrong happens. I also purge all caches. I also use the current version (Version 1.4.5).

1. Post without any update : https://www.weltenbummler-unterwegs.de/zweiter-youtube-video-test-anzeige-fehler-zeigt-link-in-kurzbeschreibung-an/
--> Works correct
2. Post that are edited with elementor: https://www.weltenbummler-unterwegs.de/mein-erster-reisebeitrag-test-2/
--> Works not correct

I also create a new post and reproduce the issue. The same happens again. First all is looking fine. After editing the new post the content below the post is missing (social icons and related posts).

**Comment by chrisk87** [comment]
I got also some information from one of the plugin teams (Easy Social Share):

"The problem come out because once you save setting in elementor the builder removes the custom meta." That is something that we are aware of and our developers working along with Elementor team".

Please check the issue in elementor for a fix in the next version. The bug deletes the custom meta from all my other plugins, after i save a edited elementor element (e.g. posts).

**Comment by arielk** [comment]
Please update v1.5 + and let me know if this solved the problem.

**Comment by chrisk87** [comment]
Hi,

i use already Version 1.5.2 and today i update to version 1.5.3.

Now i got more and more errors with elementors. We use also now Wordpress
4.8.

If i create a new post with elementor i loose all meta data information.

Example:

I create a new post with one text and one video element.

On my page www.weltenbummler-unterwegs.de i see on the startpage and also
in the archive (https://www.weltenbummler-unterwegs.de/2017/07/) no
information in the preview of the posts.

I see:
- *no* picuture thumbnail
- *no* text preview (even the wordpress editor said i have zero words in
the posts)
- *no* video preview like before

Thats horrible!

It's starts with version 1.5.2 of elementor and wordpres 4.8.

Please fix it!

I use now an workaround. I create my video posts with the normal wordpress
editor and for text posts i duplicate old posts and editor only the text
widgets (that works). But i can't create new posts with elementor without
such errors!!!






Mit freundlichen Grüßen,

Christoph Weigl

2017-07-10 0:51 GMT+08:00 Ariel Klikstein <notifications@github.com>:
