### ISSUE TITLE
Standard Table no button not working.

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#1702]
I was just trying out the 'Standard Table' and found you can't turn the buttons off. I had assumed that if you deleted the button text the button would not be displayed but instead, you get a very small blank button. My understanding is that this is incorrect and that the button should not be displayed.

**Comment by arielk** [comment]
I'm not sure I realized what exactly the problem is, if you have a link to the page with the issue it will help us.

Thanks

**Comment by nickdgreen** [comment]
If I wanted a comparison table but did not want a button in the header I would expect that deleting the text for that button would mean that it would not be created/displayed. This is the case with buttons in other elements. If you delete the text from the button the default wording for that button is still shown in the edit panel but there is no content and the button is still shown but it is empty of text. The result can be seen on this page: http://wpdemo.websitesdesigned4u.com/templates/scratch-pad/ and the editor view is attached
![standard table](https://cloud.githubusercontent.com/assets/22448787/25995846/277da2aa-370c-11e7-9377-dcd9eaef6411.png)
.

**Comment by nickdgreen** [comment]
My apologies this is a plugin not a core element I'll refer it to the developer.
