### ISSUE TITLE
Feature Request: Radio Buttons and Check Boxes

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#1706]
To set a checkbox or radio button "on" you have to put the parameter "checked" in the HTML of the <input type> definition but there is no way to access that parameter from withing Elementor. It would be good to be able to either add a specific syntax to the element "options box" to achieve this, for example <active> after the option value. It would be acceptable for the first option in the list being checked.

**Comment by KingYes** [comment]
You have `return_value` for this. For more info: https://github.com/pojome/elementor/blob/master/docs/content/controls/_switcher.md
