### ISSUE TITLE
Default Color Setting

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#1709]
Hi!
I have tried with the api document. I have added a text field for which I want elementor to have a default color . But I can't set it ! Can anyone give me a good example ! 

			$this->add_control(
			'title_color',
			[
				'label' => __( 'Text Color Before Span', 'elementor' ),
				'type' => Controls_Manager::COLOR,
				'defult' => '#a0a0a0',
				'selectors' => [
					'{{WRAPPER}} .section-title h2' => 'color: {{VALUE}};',
				],
			]
		);

Thanks !

**Comment by KingYes** [comment]
You write `defult`. Change to `default`.

**Comment by soyket** [comment]
Ah! Thanks ! typo !
Another thing is that i want to add say my own font awesome icon / flat icon to the icon list ! How do i do it ?

**Comment by KingYes** [comment]
For now you cannot. But if you see new icons on FA, please tell us and we will add them.

**Comment by soyket** [comment]
Ah sad ! . No I wanted to add some flat icons . So thought there might be some api to extend the default icons !. Btw in _content_template part function I see that you guys used parser. Is there a documentation to this parser ?
