### ISSUE TITLE
Issues with making content fill the width of the page

### ISSUE THREAD

**Issue by yosefeliezrie** [pojome/elementor#171]
Hello,

Firstly you have an awesome plugin this is simply the best plugin in the repo for page building. I am using a child theme based on the showcase pro genesis theme (almost identical code base), and having an issue with full width content. I want to be able to set a element to be full width so it takes up the whole width of the screen. Also, how do i get the whole page to be full width.

I am trying to make first section with the image with the vw beatle in background fill the full width of the page. The issue seems to be that by default everything is in a wrap div which makes it not full screen and i want to make one element or a few be full width of the page.

Can you please advise with how to fix this?
Here is the URL
[dev-golend.pantheonsite.io](url)

Here is my current template page code
[https://www.dropbox.com/s/2219g5edwmv4oxy/page_full-width.php?dl=0](url)

Please advise TIA

**Comment by arielk** [comment]
It's just a CSS settings in your theme. You can read this article: http://docs.elementor.com/article/40-full-width-template
