### ISSUE TITLE
Feature request: Make Elementor async-CSS compatible

### ISSUE THREAD

**Issue by Benqzq** [pojome/elementor#1710]
I use a minimal Ubuntu 16.04.2, Apache2, Varnish, and mod_pagespeed environment.

If I install any of the free CSS delivery optimizers out there for Wordpres (all of which basically load CSS asynchronously), then Elementor won't load...

This happened in more than one site, with different themes. It also happened in a fresh site.

This is quite frustrating, because async CSS is the main thing I need to raise my GPI score.

Any chance Elementor will be async CSS friendly soon?

@arielk @yonilux @benpines @KingYes @kobizz @matipojo

**Comment by Benqzq** [comment]
This issue is unrelated to the question if either CSS or Js are loaded in the header or footer. Where ever they are loaded - It still happens. 

I am not a PHP programmer and don't know how to debug Elementor so to know what breaks and one, when CSS is served async.

**Comment by carasmo** [comment]
Chasing after the Google Speed Insights Score is a cottage industry these days for those who think it's actually important. It isn't. What matters for SEO is speed and not the score you get. 

You will need to research SEO and learn development to understand that it is a tool for insights and that is it. Use https://tools.pingdom.com/ and other tools to measure speed.

![screen shot 2017-05-11 at 5 17 36 pm](https://cloud.githubusercontent.com/assets/1124594/25972409/dcc515e8-366d-11e7-8cf1-08c3a7f010a8.png)

To get very fast loading install (and set up) the following 2 plugins:

Simple Page Cache
https://wordpress.org/plugins/simple-cache/

Merge Minify Refresh
https://wordpress.org/plugins/merge-minify-refresh/

Read (**naughty words alert**): [Learn More](https://glueckpress.com/8117/fuck-pagespeed/)

**Comment by Benqzq** [comment]
You seem to me to have several mistakes here:

1. I worked as an SEOer in the past and have managed to raised a page from page 16 to page 1 in the Google SERP. I know what happened there, you really don't have to believe me on this. Yet I do believe speed is important and maybe even more.

2. "You will need to learn development"... Sounds like sarcasm as there are many types of development that have nothing to do with Web performance and I, as a Bash programmer tell you that Google (as a company who wants to supply quality to its customers) gives these insights for a good reason, at least in their perception. moreover, these things have to do with speed as well, not necessarily significantly - but as well).

3. The plugins you mention are seemingly irrelevant simply because this is not a matter of caching. I am on a VPS with a tested Varnish, mod_pagespeed, mod_deflate (Gzip compression), mod_expires, and and a minimal, optimal environment. Moreover, caching mechanisms (and I tried almost all of them) brought no increase whatsoever in the score.

**Comment by carasmo** [comment]
I apologize. From Yoast to WPRocket they all say speed is important but not your grade. I'm only a user of Elementor.

**Comment by arielk** [comment]
Can you be more specific which file causes you the problem?

Is the problem at the front of the site or when editing the page with Elementor?

If you work with optimized plugins like WP Rocket or Autoptimize you can set it to not work on logged-in users.

**Comment by Benqzq** [comment]
I encounter the problem whenever I click "Edit this page with Elementor". 

It happens with **all** plugins that make CSS async. I usually work with [Above the fold optimization](url) plugin to make it async but I emphasize that all of these plugins do so.

You mention WP rocket or Autoptimize but I don't use these or any caching mechanism actually because I do caching from backend via Varnish, and Apache mods.

My only plugins are basically Elementor, Wordfence, CF7, and Yoast.

**Comment by arielk** [comment]
I missed your link, you probably mean this plugin? https://wordpress.org/plugins/above-the-fold-optimization/

**Comment by Benqzq** [comment]
Indeed, that's the one.

**Comment by arielk** [comment]
Where exactly is the problem with it, on the front of the site or just inside the editor of Elementor?

I'm afraid it should be set to work only for visitors and not for the logged-in users.
The Autoptimze plugin allows you to set it up easily and it works fine.

Please ask the developer of this plugin if it possible to do it.

**Comment by Benqzq** [comment]
The problem is on the front: The moment I click "Edit this page with Elementor" when CSS loads async, I get the message:

> The session has expired.

---
![a](https://cloud.githubusercontent.com/assets/13021900/26008564/fc5c68da-374d-11e7-9d12-d73e1536119c.PNG)

---

Autoptimize, unlike Above _The Fold Optimization_, [WP async CSS](https://wordpress.org/plugins/wp-async-css/), _Fast Velocity Minify_ and _WP rocket_, doesn't allow async CSS (not in the free version at least) so it can't cause this.

**Comment by arielk** [comment]
As I wrote above, all you have to do is set up this plugin that will not work with logged-in users, only for non-logged site visitors. You can not work with any of these plugins in the edit mode of the page.
