### ISSUE TITLE
Feature Request: Template Library Filter and Search

### ISSUE THREAD

**Issue by badcat** [pojome/elementor#1711]
Would love to see the ever growing Template Library get a Filtering system and/or Search Function.

![elementor-library](https://cloud.githubusercontent.com/assets/26096/25953106/684d8f48-3630-11e7-90e6-714b20e976e9.png)

**Comment by ShaMSofT** [comment]
Even it would be better if developers could add or remove tabs from Library. Or at least a separate tab for pre-designed templates which is bundled by the theme author.

**Comment by humemedia** [comment]
Yes, this would be a massive help! As we leverage the library system, we're finding it increasingly difficult to find the saved section, element, etc. that we need. It's like a needle in a haystack at times, which is getting frustrating. Please, please, Elementor peeps, add this function to the library system!
