### ISSUE TITLE
portfolio widget filter bar issue again [pro] bug ?

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1712]
when setting a filter bar for portfolio widget there is the option to style this: color, active color.

BUT: this works here ONLY for 'ALL' items. there is no active state for the set taxonomy.
after a closer look it seems there is a _.elementor-portfolio__filter.elementor-active class_ for 'all' but obviously not applied when another taxonomy is selected.

sems to me a bug that has to be solved.

the disadvantage besides not having the optical feedback for what is choosen actually is, that one is not able to style this...

btw: a hover state even would be nice too.

**Comment by KingYes** [comment]
Hey @dasigna 

Thank you for your report. We fixed this and will release soon.
