### ISSUE TITLE
parallax does't work in preview

### ISSUE THREAD

**Issue by soniapello** [pojome/elementor#1713]
Hi I create my own parallax widget with [paroller](https://github.com/tgomilar/paroller.js/) and then with [enllax ](https://github.com/mmkjony/enllax.js/tree/master) but none of them work in preview (there's no error in console and work in frontend). So I wonder why ?

**Comment by arielk** [comment]
Is this something related to the Elementor?

If so, please give more details and information about the problem. Feel free to reopen the issue and we'll be happy to help you further.
