### ISSUE TITLE
Not really an issue, more of a suggestion:

### ISSUE THREAD

**Issue by Benqzq** [pojome/elementor#1715]
Hi dear Pojo team. I personally believe that with Page builders like Elementor, the use of "themes" in the classical sense, grows short, at least for small-scale websites (by means of number of pages and minimal design).

What I am looking for (and here's the idea for you) is a what I call a "minimal framework theme" aimed for Page builders like Elementor that gives you only these aspects:

1. Basic header layout (choose between 1/2/3/4/5 header columns).
2. Main menu (desktop version).
3. Main menu (mobile version, position: fixed / position: sticky).

I yearn for such solution because the I could do all the rest besides the header and main menu development, **fast** with Elementor - I won't need to start solving conflicts between Elementor and the team, to think what should replace what and where; I could just plan everything on scratch, and execute with Elementor (not all small websites need that but it could be good for websites with about 5-6 pages which are all built with Elementor).

A fast mini theme, serves as base for the daily Elementor work, rather than a theme in the classical sense. Please think about it and let me know what you think.

**Comment by arielk** [comment]
There is some themes that compatible with Elementor, for example: GeneratePress, OceanWP or Pojo themes.

To be honest, we do not have a plan to do it, but we have a few related features that we're working on for the future versions, so for now I close the issue.

Thanks for your feedback!
