### ISSUE TITLE
another issue with portfolio widget [pro]

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1717]
when inserting portfolio widget into section defining e.g. two rows and four items total they show up correctly in editor. on frontend there are all (!) items of the choosen category shown (which of course blows up the layout), not only the demanded four ...

no clue why - no errors found.
theme is workality from northeme.

any help would be highly appreciated.

**Comment by dasigna** [comment]
update: this is the case in el editor also when leaving elementor editor and entering new or just reloading editor window. -> same error in editor and browser preview.

always the case as long as selecting whole category(s) to choose from - not the case when manually selecting the items to query! even if there are more selected than shown ...

weird! anyone able to reproduce this???

**Comment by arielk** [comment]
I tried to reproduce this bug but everything works well. In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by dasigna** [comment]
thanks to elementor and and the devs from the northeme 'workality' theme the issue is solved.
this was due to elementor not being able to override themes post limit settings.

the message from northeme:

`Apparently Elementor cannot override the post limit. You can edit /framework/front-end/classes/class.core.functions.php file :

// Line 1850
if((isset($query->query_vars[‘post_type’]) || isset($info->taxonomy)) && !is_search()) {

// Change it as follows :
if(!isset($query?query_vars[‘posts_per_page’]) && (isset($query?query_vars[‘post_type’]) || isset($info->taxonomy)) && !is_search()) {`

maybe this helps others facing the same issue.

btw northeme announced to implement this into next update, so it will be solved for the future.
