### ISSUE TITLE
Adding class to image 

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#1718]
Hi
So I am getting the image from my created widget just like you have done in your image widget. Problem is I want to add a class to the <img > tag . But I can't figure out how to do it !!
						echo $this->get_render_attribute_string( 'img' );
this would print out an attribute added by : 		$this->add_render_attribute( 'img', 'class', 'elementor-image' ); . 
How to add this class to : echo Group_Control_Image_Size::get_attachment_image_html( $settings );
Or is there any way to get the url only for the image ? 

Thanks

**Comment by KingYes** [comment]
For now you cannot do that. Maybe in the future we extend this class.

**Comment by soyket** [comment]
Well yeah ! Because the image size control is really needed when I want to load a little image of the same image in different place with different classes! Maybe you could add a class adding method to the img tag !

Thanks btw !

**Comment by tannerchung** [comment]
@KingYes , needing to add extra data attributes to the img tag. Is there any work around at the moment? I saw that Elementor Pro has an Attributes manager but only applies to the wrapper and not the actual image.

**Comment by roireshef** [comment]
@KingYes What about that feature? It's been almost 3 years since this was opened

**Comment by Salimoh** [comment]
Since the introduction on Core web vitals all SEOs are struggling with this problem. Please add this feature sooner.

Thanks

**Comment by eduardovillao** [comment]
Hey everyone, use this for add custom class to image: [https://github.com/eduardovillao/add-class-to-elementor-image](https://github.com/eduardovillao/add-class-to-elementor-image)

**Comment by TommiContursi** [comment]
@Salimoh Raised a good point in here. At least I would like to add classes to certain images, for example, a class to exclude lazy loading for header images which affects the Largest Contentful Paint time. This shouldn't be a feature that requires using an additional plugin.

**Comment by Salimoh** [comment]
Elementor does not add class to the <img> tag so that you can lazyload it
. the abovementioned plugin worked fine for me @TommiContursi

**Comment by eduardovillao** [comment]
@sermalefico unfortunately, Elementor don't have this feature. But you can use this plugins to solve it: https://wordpress.org/plugins/add-class-to-elementor-image/

**Comment by sermalefico** [comment]
ya... more plugs for crucial options... tipical

**Comment by tamal-sen** [comment]
Wow, almost 5 years but there is still no built-in fix for this. Please focus on this issue.

**Comment by markbosky** [comment]
+1

**Comment by subbame** [comment]
+1

**Comment by pckz** [comment]
+1 / opened 5 years ago. thanks!

**Comment by MikeLikesThat** [comment]
+1

**Comment by nisiwi** [comment]
I also need the image class for lazy loading and resizing control on all widgets with images.

**Comment by gercheq** [comment]
Same needed on this end as well. Without the id/class on the actual <img> element, we can not disable lazyloading using SmushPro plugin on post pages. This causes LCP to go up on our post pages.

**Comment by khahina** [comment]
+1

**Comment by maximedesro** [comment]
This would be useful.

**Comment by luxpatrick** [comment]
+1

**Comment by luxpatrick** [comment]
@eduardovillao plugin doesn't seem too work anymore

**Comment by eduardovillao** [comment]
@luxpatrick thanks for report that. I will check and update it!

**Comment by luxpatrick** [comment]
@eduardovillao pls keep us updated

**Comment by luxpatrick** [comment]
Cool, will test it. Had you in my thoughts today, but as this is a free project I wouldn’t want to bother you with it! Thanks mate! Am 17.10.2023 um 19:46 schrieb Eduardo Villão ***@***.***>:﻿
@luxpatrick Done! version updated (1.3) and now is working as expected. Please let me know if you need anything. Cc: @maximedesro @khahina @gercheq @nisiwi @MikeLikesThat @pckz @subbame @markbosky

**Comment by MrPrainx** [comment]
The plugin by @eduardovillao works perfectly. But it's confusing to me why such a crucial option  should be achieved with a 3rd party plugin.

**Comment by sarit026** [comment]
+1

**Comment by kweidner14** [comment]
+1
It's been **8 years**. I can't believe this _still_ isn't a core feature.
