### ISSUE TITLE
FR: Center all content in region for mobile devices

### ISSUE THREAD

**Issue by Benqzq** [pojome/elementor#1719]
I have an Elementor region of 2 columns. The **left column** has an image I positioned in the **left corner** of the column.

On Desktop it looks good, but on mobile devices it isn't, because it breaks symmetry of appearance (think about it, an image which isn't 100% width, uncenterd in mobile).

I suggest adding a button like "centeralize all images for all columns, in mobile devices" in **Region > Responsivenes**.

**Comment by Benqzq** [comment]
I changed the title because maybe it will be better to add such a button to center everything for mobile devices, and not just images, at least in some designs.

**Comment by arielk** [comment]
Please update v1.5 + and let me know if this solved the problem.
