### ISSUE TITLE
Feature suggestion: Hive element

### ISSUE THREAD

**Issue by Benqzq** [pojome/elementor#1720]
I love to build certain pages with Elementor in what is called "Hive arechitecture" (I am not sure this is the right term in English, but in hebrew I know it's called "**Kaveret**" - The Hebrew word for **hive**).

This is how it looks in Desktops:

```
Text Image
Image Text
```

My problem is that when I build this with Elementor **2-column regions** in **RTL** sites, I get this situation in Mobile devices:

```
Text
Image
Image
Text
```

Logically this should be the natrual result but I do wonder what is the solution without starting to flip everything specifically with CSS classes up until 480px (or 720) pxs.

I humbly suggest to consider adding a ready-to-work **hive element** that doesn't have this behavior in responsive modes, or at lease, share a fix to those prefer to work with 2-column regions (to me it's most efficient, and usually also more convenient to construct columns, whether hived or not, from scratch, with 2-column regions).

**Comment by carasmo** [comment]
It looks weird on LTR too. Elementor has a builtin solution for this. Click on the the second Section tab, go to Advanced, then choose Responsive, and click the Reverse Columns switch. 

![screen shot 2017-05-13 at 11 24 36 pm](https://cloud.githubusercontent.com/assets/1124594/26031033/9597bef6-3833-11e7-9868-01fd91b526b2.png)

**Comment by arielk** [comment]
Thanks @carasmo for your answer!
