### ISSUE TITLE
Feature Request - Forms Widget - Please Add a Field for a Password (for user account) and Password confirmation

### ISSUE THREAD

**Issue by Webmaster3dDiet** [pojome/elementor#1721]
I love Elementor Pro!  I would like to request that the Form Widget include a Field for a unique Username as well as a field for a Password and Password Confirm.  This could be used for new user subscriptions.
Thank you!
Webmaster,  The3dDiet.com

**Comment by arielk** [comment]
Maybe we'll add this in the future to the Login widget, you can read about it here: https://elementor.com/pro-v140-login-widget/

Thanks for your feedback!
