### ISSUE TITLE
Just a suggestion to add a  Call to Action Modules

### ISSUE THREAD

**Issue by smavanga** [pojome/elementor#1722]
I have find an idea to make things easy by trying to have a  **Call to Action Modules**
, whereby you have a title, a content and a button you understand what I mean.
I used a template and save it to the My Library but I find it nice if it has its own modules with setting that belong to it like other modules for every part of the content : Title can be settle in style, and so on ..Thank u

**Comment by Basilakis** [comment]
That can be the " Marketing Package " as a module. Nice idea, if you have any suggestions or screenshots, I will be happy to develop it. :)

**Comment by smavanga** [comment]
It will be a good idea in the attachements you have some screenshots about
that and the options details for every tab

*General tab*
Title

Insert the title of your Call to Action module here.
Button Text

Specify the button text here, or leave it blank if you do not wish to have
a button.
Content

This field is where you can enter the Call To Action content.
Button URL

Inserting a valid web URL in this field to specify the destination of your
CTA.
URL Opens

Here you can choose whether or not your link opens in a new window
Use Background Color

If enabled, a background color will be applied to the module. If a
background color has been enabled, additional padding is added inside the
module to separate the text content from the visible edge of the module. If
a background color is not enabled, the background of the module becomes
transparent and the additional padding is removed.
Background Color

Define a custom background color for your module, or leave blank to use the
default color. This option will only appear when Use Background Color has
been enabled.
Background Image

If defined, this image will be used as the background for this module. To
remove a background image, simply delete the URL from the settings field.
Background images will appear above background colors, which means your
background color will not be visible when a background image is applied.
Admin Label

This will change the label of the module in the builder for easy
identification.

------------------------------------------------------------------------------------------------------------------

*CTA Advanced Design Options*
Within the design tab you will find all of the module’s styling options,
such as fonts, colors, sizing and spacing. This is the tab you will use to
change how your module looks.
Text Color

If your CTA Background Color is dark, the Text Color should be set to
‘Light’. Visa versa, if the CTA Background Color is light, the Text Color
should be set to ‘Dark’.
Text Orientation

This dropdown menu allows you to specify the orientation of your text to be
Left Justified, Centered, or Right Justified.
Header Font

You can change the font of your header text by selecting your desired font
from the dropdown menu. Divi comes with dozens of great fonts powered by
Google Fonts.  You can also customize the style of your text using the
bold, italic, all-caps and underline options.
Header Font Size

Here you can adjust the size of your header text. You can drag the range
slider to increase or decrease the size of your text, or you can input your
desired text size value directly into the input field to the right of the
slider. The input fields supports different units of measurement, which
means you can input “px” or “em” following your size value to change its
unit type.
Header Text Color

By default, all text colors will appear as white or dark gray. If you would
like to change the color of your header text, choose your desired color
from the color picker using this option.
Header Letter Spacing

Letter spacing affects the space between each letter. If you would like to
increase the space between each letter in your header text, use the range
slider to adjust the space or input your desired spacing size into the
input field to the right of the slider. The input fields supports different
units of measurement, which means you can input “px” or “em” following your
size value to change its unit type.
Header Line Height

Line height affects the space between each line of your header text If you
would like to increase the space between each line, use the range slider to
adjust the space or input your desired spacing size into the input field to
the right of the slider. The input fields supports different units of
measurement, which means you can input “px” or “em” following your size
value to change its unit type.
Body Font

You can change the font of your body text by selecting your desired font
from the dropdown menu. You can enable the dozens of great fonts powered by
Google Fonts. By default,. You can also customize the style of your text
using the bold, italic, all-caps and underline options.
Body Font Size

Here you can adjust the size of your body text. You can drag the range
slider to increase or decrease the size of your text, or you can input your
desired text size value directly into the input field to the right of the
slider. The input fields supports different units of measurement, which
means you can input “px” or “em” following your size value to change its
unit type.
Body Text Color

By default, all text colors can appear as white or dark gray. If you would
like to change the color of your body text, choose your desired color from
the color picker using this option.
Body Letter Spacing

Letter spacing affects the space between each letter. If you would like to
increase the space between each letter in your body text, use the range
slider to adjust the space or input your desired spacing size into the
input field to the right of the slider. The input fields supports different
units of measurement, which means you can input “px” or “em” following your
size value to change its unit type.
Body Line Height

Line height affects the space between each line of your body text If you
would like to increase the space between each line, use the range slider to
adjust the space or input your desired spacing size into the input field to
the right of the slider. The input fields supports different units of
measurement, which means you can input “px” or “em” following your size
value to change its unit type.
Use Border

Enabling this option will place a border around your module. This border
can be customized using the following conditional settings.
Border Color

This option affects the color of your border. Select a custom color from
the color picker to apply it to your border.
Border Width

By default, borders have a width of 1 pixel. You can increase this value by
dragging the range slider or by inputting a custom value into the input
field to the right of the slider. Custom units of measurements of
supported, which means you can change the default unit from “px” to
something else, such as em, vh, vw etc.
Border Style

Borders support eight different styles, including: solid, dotted, dashed,
double, groove, ridge, inset and outset. Select your desired style from the
dropdown menu to apply it to your border.
Max Width

By default, the module will extend 100% the width of the parent column. If
you would like to restrict this max width, a max width value can be input
here. If you input 50%, for example, the module will be restricted to 50%
of the width of the column that contains it.
Custom Margin

Margin is the space added outside of your module, between the module and
the next element above, below or to the left and right of it. You can add
custom margin values to any of the module’s four sides. To remove custom
margin, delete the added value from the input field. By default these
values are measured in pixels, but you can input custom units of
measurement into the input fields.
Custom Padding

Padding is the space added inside of your module, between the edge of the
module and its internal elements. You can add custom padding values to any
of the module’s four sides. To remove custom margin, delete the added value
from the input field. By default these values are measured in pixels, but
you can input custom units of measurement into the input fields.
Use Custom Styles for Button

Enabling this option will reveal various button customization settings that
you can use to change the appearance of your module’s button.
Button Text Size

This setting can be used to increase or decrease the size of the text
within the button. The button will scale as the text size is increased and
decreased.
Button Text Color

By default, buttons assume your theme accent color as defined in the Theme
Customizer. This option allows you to assign a custom text color to the
button in this module. Select your custom color using the color picker to
change the button’s color.
Button Background Color

By default, buttons have a transparent background color. This can be
changed by selected your desired background color from the color picker.
Button Border Width

All Divi buttons have a 2px border by default. This border can be increased
or decreased in size using this setting. Borders can be removed by
inputting a value of 0.
Button Border Color

By default, button borders assume your theme accent color as defined in the
Theme Customizer. This option allows you to assign a custom border color to
the button in this module. Select your custom color using the color picker
to change the button’s border color.
Button Border Radius

Border radius affects how rounded the corners of your buttons are. By
default, buttons in Divi has a small border radius that rounds the corners
by 3 pixels. You can decrease this to 0 to create a square button or
increase it significantly to create buttons with circular edges.
Button Letter Spacing

Letter spacing affects the space between each letter. If you would like to
increase the space between each letter in your button text, use the range
slider to adjust the space or input your desired spacing size into the
input field to the right of the slider. The input fields supports different
units of measurement, which means you can input “px” or “em” following your
size value to change its unit type.
Button Font

You can change the font of your button text by selecting your desired font
from the dropdown menu. You can enable the dozens of great fonts powered by
Google Fonts.  You can also customize the style of your text using the
bold, italic, all-caps and underline options.
Add Button Icon

Disabled this setting will remove icons from your button.
Button Icon

If icons are enabled, you can use this setting to pick which icon to use in
your button.
Button Icon Color

Adjusting this setting will change the color of the icon that appears in
your button. By default, the icon color is the same as your buttons’ text
color, but this setting allows you to adjust the color independently.
Button Icon Placement

You can choose to have your button icon display on the left or the right
side of your button.
Only Show Icon On Hover for Button

By default, button icons are only displayed on hover. If you would like the
icon to always appear, disable this setting.
Button Hover Text Color

When the button is hovered over by a visitor’s mouse, this color will be
used. The color will transition from the base color defined in the previous
settings.
Button Hover Background Color

When the button is hovered over by a visitor’s mouse, this color will be
used. The color will transition from the base color defined in the previous
settings.
Button Hover Border Color

When the button is hovered over by a visitor’s mouse, this color will be
used. The color will transition from the base color defined in the previous
settings.
Button Hover Border Radius

When the button is hovered over by a visitor’s mouse, this value will be
used. The value will transition from the base value defined in the previous
settings.
Button Hover Letter Spacing

When the button is hovered over by a visitor’s mouse, this value will be
used. The value will transition from the base value defined in the previous
settings


----------------------------------------------------------------------------------------------------------------------------

*Call To Action Custom CSS or Options*

Within the advanced tab, you will find options that more experienced web
designers might find useful, such as custom CSS and HTML attributes. Here
you can apply custom CSS to any of the module’s many elements. You can also
apply custom CSS classes and IDs to the module, which can be used to
customize the module within your child theme’s style.css file.
CSS ID

Enter an optional CSS ID to be used for this module. An ID can be used to
create custom CSS styling, or to create links to particular sections of
your page.
CSS Class

Enter optional CSS classes to be used for this module. A CSS class can be
used to create custom CSS styling. You can add multiple classes, separated
with a space.
Custom CSS

Custom CSS can also be applied to the module and any of the module’s
internal elements. Within the Custom CSS section, you will find a text
field where you can add custom CSS directly to each element. CSS input into
these settings are already wrapped within style tags, so you need only
enter CSS rules separated by semicolons.
Visibility

This option lets you control which devices your module appears on. You can
choose to disable your module on tablets, smart phones or desktop computers
individually. This is useful if you want to use different modules on
different devices, or if you want to simplify the mobile design by
eliminating certain elements from the page.


You can find some image for the builder that I was using, so I will it to
be inserted into Elementor to make it more Pro

See you seen
2017-06-04 18:23 GMT+02:00 Basilis Kanonidis <notifications@github.com>:

**Comment by bainternet** [comment]
@smavanga 
you are describing the Button widget.

Closing as Implemented.

feel free to reopen if I'm missing something.
