### ISSUE TITLE
Add Section and Add Templates buttons overlapped by menu on empty page

### ISSUE THREAD

**Issue by ehausen** [pojome/elementor#1723]
Add Section and Add Templates buttons are overlapped by menu on empty page and are non clickable. I had to display title to get the buttons pushed down.

Maybe show them at middle or bottom? 

Top of empty page:
![screen shot 2017-05-15 at 9 26 04](https://cloud.githubusercontent.com/assets/6204129/26045078/0db20072-3951-11e7-9247-f0c7ddf3c893.png)

**Comment by arielk** [comment]
It looks like a conflict with your theme. Which theme are you using?
