### ISSUE TITLE
Feature Request: WPGlobus integration

### ISSUE THREAD

**Issue by AiratHalitov** [pojome/elementor#1724]
Can you add integration with [WPGlobus plugin](https://wordpress.org/plugins/wpglobus/)?

It can be includet to core of Elementor or working like [WPGlobus for WPBakery Visual Composer](https://wordpress.org/plugins/wpglobus-for-wpbakery-visual-composer/) plugin ([GitHub](https://github.com/WPGlobus/wpglobus-for-wpbakery-visual-composer)).

Elementor 1.4.6
WP forum: https://wordpress.org/support/topic/wpglobus-integration/

Thanks!

**Comment by AiratHalitov** [comment]
https://wpglobus.com/wpglobus-page-builders-support/

**Comment by arielk** [comment]
Hi

It seems that WPGlobus should do integration with us. We will be happy to review this issue, please let us know how we can help.

Thanks
