### ISSUE TITLE
Layouts Fail when migrating site from local dev to live server

### ISSUE THREAD

**Issue by RobsWebDev** [pojome/elementor#1725]
This is related to closed issue 403. I see that this issue has been closed but I am now having this same issue as well. I have used all of these methods described above, but my layout is still getting broken, as if there is no CSS being added to the page. My host does not allow Duplicator, but I have tried the WP Migrate DB plugin and it does not work. I have also tried the All-In-One- Migration plugin with the same result. I was able to create a new page on the live site and use the same template from the previous one, but it just seems like extra work to do this. Has there been any other discoveries in this regard?

**Comment by arielk** [comment]
Hi @RobsWebDev 

Please read this docs: http://docs.elementor.com/article/131-replace-url-change-domain
