### ISSUE TITLE
Feature request: Tablet mode 1024px instead of 768px

### ISSUE THREAD

**Issue by Glowchester** [pojome/elementor#1726]
Hi, 

Would be great if you could if it was possible to change the tablet mode (in the page builder) to 1024px instead of 768px. The most of the modern tablets are 1024px, like Samsung and Ipad. 

I also think many themes has 1024px as a standard breaking point for things like menu and footer. 

Hope you understand my request!

**Comment by arielk** [comment]
For now, a breakpoint for a tablet is 1025px and lower, and for mobile is 768px or lower.
Maybe we will add in the future the possibility of customizing the breakpoints, you can read more about this here: #78 

I merged this issue with this issue so we could deal with it more efficiently.

Thanks for your feedback!
