### ISSUE TITLE
Feature Request: Expanded Blog options

### ISSUE THREAD

**Issue by forcedlogic** [pojome/elementor#1727]
First thank you to the team of Elementor. You make a great product and I have really enjoyed your work. Keep up the great work.

Features I'd be interested in seeing:

**Expanded Blog options:**
Is it possible to have the blog similar to the forum sections where you could drag and drop sections? For instance...if I want the TITLE and META above the IMAGE? That would be really great.

Also I'd like to see more options other than masonry and just stand posts for blogs.

**Post Slider:**
I'd like to see the ability to do some sort of post slider without the use of an additional plugin.

Thank you for your consideration.
Patrick

**Comment by arielk** [comment]
Hi

For blog elements you can follow this issue: https://github.com/pojome/elementor/issues/543

For post carousel you can follow this issue: https://github.com/pojome/elementor/issues/1299

Thanks for your feedback!
