### ISSUE TITLE
[Feature Request]: Category for template library

### ISSUE THREAD

**Issue by ShaMSofT** [pojome/elementor#1729]
It would be great if you add category to templates. So templates will display with a horizontal text divider or even  users should be able to filter available templates by category. Would be nice to see this feature in v1.5.

**Comment by badcat** [comment]
Agreed - I added similar to this here:  https://github.com/pojome/elementor/issues/1711

**Comment by arielk** [comment]
I merged this issue with another issue #1711 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
