### ISSUE TITLE
Feature request: ability to query elements contents

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1732]
Hi, I'd like an API to query elementor's elements contents. That's for getting  contents (for example) from an elementor's editor and use them on other pages/templates than the one where it is used within elementor.

Since quite about every elementor's element has an ID, this maybe could be not too difficult to implement?

something like `get_elementor_content($element_id);`

Regards

**Comment by Basilakis** [comment]
Creating a universal shortcode, could be easier for that.
Example, any elementor item used, has a specific id. Calling it like

[elementor content-id='1']

could get the element that is stored and has ID 1!

**Comment by KingYes** [comment]
@stratboy

I don't know if we want to add this method to your core files. But for now you can use with this method (Just cut from our Forms Module):

```
	public static function find_element_recursive( $elements, $element_id ) {
		foreach ( $elements as $element ) {
			if ( $element_id === $element['id'] ) {
				return $element;
			}

			if ( ! empty( $element['elements'] ) ) {
				$element = self::find_element_recursive( $element['elements'], $element_id );

				if ( $element ) {
					return $element;
				}
			}
		}

		return false;
	}
```
