### ISSUE TITLE
Change the way css is generated to help versioning

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#1733]
Hi guys,
this is a feature request, quite simple.

Let's take this example: i have _example.test.com_ and _www.example.com_ , the first is the dev domain, the second is the production one. I use git for versioning everything in my projects.

So, when in dev i edited my pages using some background images too, and everything went perfect, every time you press the save button on elementor, a css is generated for each post (page, cpt etc... all saved as post-ID) and created onto the uploads folder like these files...

```
wp-content/uploads/elementor/css/post-1265.css
wp-content/uploads/elementor/css/post-34.css
wp-content/uploads/elementor/css/post-46.css
wp-content/uploads/elementor/css/post-527.css
wp-content/uploads/elementor/css/post-532.css
```

Now, i add and commit these files to my repo, and fetch all modifies to my production environment.
Naturally, this is what happens: **background images and all linked resources point to the dev domain**, and to make Elementor work i need to go to the backend panel, search for Elementor --> Tools --> regenerate css. If you think on _www.example.com_ as a site already online, there will be downtime and frontend glitches until i regenerate the css files.

Well, after this i should remove the dev environment generated css from git and add to git the new css files. And, Well, this is funny, because i need to do this every time i need to modify something with Elementor from an environment to another. 

At this point, i tried to .gitignore completely the files, to solve this "dog biting is own tail", but i still need to regenerate manually the css files. 

Personally, **gitignoring** these ones is the perfect solution, and would solve my problems, **IF AND ONLY IF THE css file is autogenerated on page/post/cpt loading**, when the file is missing. 

When the file is present, you could add a field to the database to check any time you load a page/post/cpt if the last modified parameter of the css file is equal to the last modified date saved on database for that page/post/cpt (this is only a db request and a file parameter parsing, it won't cost a lot speaking about performance). I.e.:

File : /elementor/css/post-1265.css --> Date of last modify 10/05/2017 10:00
Database: post 1265 --> Date of last modify 17/05/2017 10:00
The database date of last modify for the post 1265 is greater than the post-1265.css file, i need to regenerate that file.

What you think?

**Comment by KingYes** [comment]
Hey @teolaz 

You right. But I can't check all CSS files in all request.. It's poor performers.
BTW, you can write own script when you upload new version of the product. The script just run the method to clear cache and you finally get the new one..

**Comment by teolaz** [comment]
@KingYes you don't have to check ALL css files in one request, you need to check the css file FOR 1 REQUESTED PAGE ONLY.... You know, if you try smart slider 3 pro it works exactly in this way, so it's simple to gitignore the css generated files...And it's not so poor at all!

**Comment by teolaz** [comment]
@KingYes an idea...
The main problem is the absolute link for background images and so on right?
Why not to pass to a relative link while saving all the link css directives? It should still work, for everyone who is already using elementor, while the approach is more vcs "savingass" based... do you agree?

**Comment by matipojo** [comment]
Hi, You can simply set a git hook `post-receive` that uses `wp-cli` to clear the css generated files:
`wp eval "Elementor\Plugin::$instance->posts_css_manager->clear_cache();"`

**Comment by teolaz** [comment]
@matipojo i'm trying to understand if it is possible to have a working Elementor with a simple plus functionality, without having to mess server side...

**Comment by joshmarom** [comment]
@teolaz We held a discussion about your case. We believe your work practice is a bit unusual and although we would very much like to help you, we don't agree that something needs to be changed on Elementor's end.

We provide the option to regenerate CSS files when that's required, and we don't think we should be checking if the file exists every time the page loads.

I think the solution @matipojo provided you with, is a rather good one and will resolve your issue effectively.

**Comment by teolaz** [comment]
@KingYes, @joshmarom, @matipojo if you didn't read it, an idea...
The main problem is the absolute link for background images and so on right?
Why not to pass to a relative link while saving all the link css directives? I.e.:

background-image: url(http://example.test.com/wp-content/uploads/sites/4/2017/04/perhome1.jpg);
to
background-image: url(../../2017/04/perhome1.jpg);

It should still work, for everyone who is already using elementor, while the approach is more vcs "savingass" based... do you agree?

If you don't trust the "still work for everyone" thing, you can simply put a new option on settings page where to check if to use this method or not...

**Comment by KingYes** [comment]
Hey @teolaz 

In next release we will add option to print all your styles in `<head>` tag. No based on file.

I think it's will be great solution for you.

**Comment by teolaz** [comment]
@KingYes just to precise, is every link calculated by using the same get_home_url function? Or is the link cached?

**Comment by KingYes** [comment]
It's by WordPress functions. I don't handle with that..

**Comment by ryanlabelle** [comment]
@matipojo thank you! That is a great solution when one is rsyncing or running an import via bash script. Nice job. Saved my a lot of time :)
