### ISSUE TITLE
SOLVED - Elementor shows incorrect hex colors.

### ISSUE THREAD

**Issue by dollhousedigital** [pojome/elementor#1735]
Elementor shows incorrect hex colors.

For example.
If I insert an image with a block of turquoise color #00b4c4
It comes out incorrectly.
A jpg comes out as #31b1b9
A png comes out as #31b1ba

I have run loads of tests using background section images / image modules etc.

But always the same results.

If I add a font (for example) with #00b4c4 it comes out correctly.
So why is the color always incorrect when I add a jpg or png?

And no - I have no filters or layers on the images.

The colors are very close - but not correct.

I have tried this with other colors as well - but they are ALWAYS incorrect on a site.
However - Blacks and Greys always come out fine.

Colors are fine for the nav logo (with any theme) - it is only Elementor on the pages that is incorrect.

Try for yourselves...
Choose any color - add it as jpg or png to your site and then test the color hex code.

This is a MAJOR ISSUE for anyone working with strict branding guidelines.

Does anyone know why this is happening?

**Comment by dasigna** [comment]
... as far as i can say this is in all likelyhood NOT to due to elementor.

much more likely this is an color profile issue with your sreen or browser. have had this before after a calibration error and drove me quite crazy.

tested it again a minute ago after having read this and your suggestion - everythings alright here!! :-)

**Comment by dollhousedigital** [comment]
Heya,

Thanks for your response.

However this is definitely an Elementor issue as far as I can tell.

Here is an example page.
http://exuberant-toucan.w3.poopy.life/

Using Chrome and Firefox on Mac or PC:
A jpg comes out as #f70e0b
A png comes out as #f80eob
Direct Color comes out correctly as #ff0000

Using Safari all colors are #fe0008

Using Microsoft Edge all colors are correct.

The only way to test is to take a screenshot and put the image in Photoshop and use the color dropper tool.
Or use a color dropper extension on your browser.

Cheers...

**Comment by dasigna** [comment]
... still seems to be a calibration thing on your side:

direct is correct.
png is correct.
jpg shows #fe0000 - but that eventually may be due to lossy compression.

???

**Comment by carasmo** [comment]
It's not Elementor. Read: https://graphicdesign.stackexchange.com/questions/78265/why-is-the-hex-color-in-my-png-different-from-the-same-hex-code-in-browser.

It's your color space. Read up: https://forums.adobe.com/thread/1074577?tstart=0

Here's the same three on JS bin, not WordPress or Elementor:

http://output.jsbin.com/sofacibasi

**Comment by dollhousedigital** [comment]
Very interesting - Thanks!!!!

I saved the file using Adobe - Save For Web (Legacy)
Not sure why it is a legacy feature?

But all seems good now!

Thanks again!
Panic attack over! :-)

**Comment by dasigna** [comment]
still of the opinion it has nothing to to with elementor or browser

its definitely a color space and calibration thing and a if color correction is involved (in any way) or not.

if i am working on webdev-environment which is strictly set to srgb without corection, all colors are correct - regardless of browser and application (assumed they're also set to no correction/srgb).
when switching to print-calibrated environment the colors change - logically.

so i think you really have to take look on your overall color settings.

'save for web' by the way also can change colors in one or another way... :-)

**Comment by dollhousedigital** [comment]
Cheers guys...

Much appreciated.

I have a lot of reading to do now!
I have made what I currently have work with 'Save for Web'.

However I assume if I pay close attention to color profiles as I create my artwork I will have all this covered and not need to use 'Save to Web' - Which I assume just strips the color profile?

Thanks again..

**Comment by carasmo** [comment]
Since this is neither a bug or a feature request, please https://graphicdesign.stackexchange.com/ site for further questions. The second link in my prev post has the answer, please read the entire thread.
