### ISSUE TITLE
Full screen background video does not resize correctly.

### ISSUE THREAD

**Issue by dollhousedigital** [pojome/elementor#1737]
Heya,

When I add full screen video background to a section at the top of a page I am having some problems.

If I move the browser window onto another monitor with a lower resolution - and then back to the larger monitor - the background video does not resize back to full width.
It stays at the size of the previous window - in the center of the screen with large white padding all around the edges.

I have the JS full width switch enabled - and if I recall correctly this worked ok on a previous version of Elementor but it has stopped working recently.

This issue can also occur sometimes if you make your browser window small and then suddenly maximize the window. It doesn't happen all the time however - seems temperamental.

Is this an issue or is there something I can do to ensure the video background is always at 100%?

Thanks..

**Comment by dasigna** [comment]
more of a browser thing due to not recognizing the sudden change of the viewport?
what happens if you reload the page after moving/resizing - should be o.k. then - no?

**Comment by dollhousedigital** [comment]
Yes - if you refresh it is ok again.

A while ago it wasn't working and I noticed I did not have the JS Stretch Section switch on.
So I turned this on and it seemed to work ok - for a while.
But not anymore.

Images resize perfectly - and everything else on a site is great. Just a problem with video section backgrounds.

Same problem on Firefox and Chrome.

**Comment by arielk** [comment]
In version 1.5 we made several video background fixes, please update your plugin and let me know if this solved your problem.

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by joycarone** [comment]
I have the same issues!!!!

**Comment by omarkhatibco** [comment]
I have the same problem also
