### ISSUE TITLE
Why is My Library post type set to public?

### ISSUE THREAD

**Issue by Stegosource** [pojome/elementor#1738]
## Description

If I use get_post_types and filter to public post types, the Elementor library post types show up. I can't think of any reason they should be public, but I may be wrong.

## Steps to reproduce

Install Elementor.
Add this line to a public facing template <?php var_dump(get_post_types(array('public' => true))); ?>

The post type is registered here in includes/template-library/local.php on line 66. https://github.com/pojome/elementor/blob/e281b7827e87dc9878b343d22dea4bed4c42911c/includes/template-library/sources/local.php#L66

Right now I can manually exclude the post type from showing up, but would it make more sense to make this not public?

**Comment by KingYes** [comment]
The reason it's public because Elementor allow the admin to edit this. But we disallow other users to access to this pages. As you can see there: https://github.com/pojome/elementor/blob/e281b7827e87dc9878b343d22dea4bed4c42911c/includes/template-library/sources/local.php#L322

**Comment by Stegosource** [comment]
OK, I guess that makes sense. But couldnt you allow the admin to access the page without making it public as well?

**Comment by KingYes** [comment]
Nope. It's just get 404 error.. :|
