### ISSUE TITLE
Feature Request: Testimonial Slider

### ISSUE THREAD

**Issue by GAPP99** [pojome/elementor#1739]
Currently it's only possible to use static testimonials. Would be really great for alot of us, if there was possibility of a Testimonial Slider.

**Comment by Basilakis** [comment]
With Builders like Elementor, the point is to use it for your pages, but keep that functionality for other stuff. Example, you can use THE GRID or Essenstial Grild, to make a Testimonial slider.

**Comment by arielk** [comment]
I merged this issue with another issue #715  in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
