### ISSUE TITLE
Localhost Shows Error while adding new section

### ISSUE THREAD

**Issue by mehedi-sharif** [pojome/elementor#1742]
I am not sure is it a bug or issue from my end. Elementor works fine in server but in localhost while I am trying to add new section it show error in console -
`editor.js?ver=1.4.7:6877 Uncaught TypeError: Cannot read property 'add' of undefined
    at n.addChildModel (editor.js?ver=1.4.7:6877)
    at n.addSection (editor.js?ver=1.4.7:6892)
    at n.onPresetSelected (editor.js?ver=1.4.7:9247)
    at HTMLDivElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDivElement.r.handle (jquery.js?ver=1.12.4:3)`
What I did, 
1- Clear my cache .
2- Change my browser . 
3- Reinstall elementor plugin. 
But still now the issue is same. 
For details please check the screenshot.
Thanks
<img width="305" alt="screen shot 2017-05-20 at 8 30 27 pm" src="https://cloud.githubusercontent.com/assets/5304905/26276537/376a2ac2-3d9b-11e7-8fee-adf531a268ca.png">

**Comment by mehedi-sharif** [comment]
I got the issue. I made a shortcode for EDD plugin . With that shortcode I pull all the products from that plugin. After adding that shortcode elementor just crash. I have tested with all other shortcodes . Those are works fine but not this one. I am not sure which making the problem . 
`add_shortcode('swift-product' , 'swift_products_func');
function swift_products_func ($atts){
	ob_start();

	$option = shortcode_atts(
		array(
			'product-limit' => '6',
			'product-category' => '',
		),$atts
	);
	$product_limit = $option['product-limit'];
	$product_category = $option['product-category'];
	$loop = new WP_Query(
		array(
			'post_type' => 'download',
			'posts_per_page' => $product_limit,
			'post_status'       => 'publish',
			'download_category'=> $product_category,
		)
	);
	if($loop->have_posts()) :
		while ($loop->have_posts()): $loop->the_post() ;  ?>
			<div class="col-md-4">
				<div class="product-item">
					<div class="product-thumb">
						<a href="">
							<?php the_post_thumbnail();  ?>
						</a>
					</div>
					<div class="content">
						<div class="product-meta">
							<span class="price"> <i class="tf-pricetags"></i> </span>
							<a class="author" href=""><i class="tf-profile-male"></i><?php the_author();  ?></a>
						</div>
						<h4><a href="<?php the_permalink();  ?>"><?php the_title();  ?></a></h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, animi.</p>
						<div class="product-buttons">
							<a href="<?php the_permalink();  ?>" class="btn btn-main-sm">Details</a>
						</div>
					</div>
				</div>
			</div>
		<?php endwhile;  endif ;
	return ob_get_clean();
}`
Here is that code.

**Comment by KingYes** [comment]
The code it's seen okay for me. Please try to remove some part from this code and check where is your problem..
