### ISSUE TITLE
Elementor Widget Wrap z-index!

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#1743]
Hello team,

Is there any reason why `.elementor-widget-wrap` has it's z-index set to 1?

Removing it altogether solves a lot of design issues and I've yet to encounter any side effects, so I was wondering if you guys could look into removing it unless there is a valid reason for having it in place :)

TIA,
Zulf

**Comment by arielk** [comment]
It seems to be there for compatibility with the setting buttons in the editor. But in the next version we are making a significant UI update to the editor, so probably it will be deleted.

Thanks for your attention.

**Comment by WPDevHQ** [comment]
That's great news, thanks @arielk

**Comment by arielk** [comment]
https://github.com/pojome/elementor/pull/1820/commits/cce3493a28593b6beb168252af943c79f602791c
