### ISSUE TITLE
Improvement with Portfolio widget

### ISSUE THREAD

**Issue by gfdesign** [pojome/elementor#1744]
Dear support
I see an issue that could be enhaced. When you display your posts with this widget and one of them no has image, the title is hard to see, specially if the text title and the background container are white.
Could you add an option to specify a background color for the items?
Thanks

**Comment by joshmarom** [comment]
Hi @gfdesign.

I am not sure I understand exactly what you mean.
Could you please attach screenshots to demonstrate what you are referring to?

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by gfdesign** [comment]
Sorry guys for my delay. This is what I am talking about:
When the portfolio items have no image, users can't see them: 
<img src="http://i.imgur.com/pcRT2qC.jpg" alt="" />

at least user makes over them with the cursor:
<img src="http://i.imgur.com/FYifJKV.jpg" alt="" />

I tried to fix it with CSS but according to HTML that Elementor generates, it's impossible.
Any idea how to solve it?
Thanks
