### ISSUE TITLE
I think I found a bug regarding editing the post-page (blog-page) of each site

### ISSUE THREAD

**Issue by Benqzq** [pojome/elementor#1745]
Hi, I use Wordpress 4.7.5 with the theme GeneratePress. 

I have a page I setted as the "post page" or "blog page" of the site.

When I edit this page with Elementor and create a new Elementor region, I can't position it above the H1 of **uppermost** blog article.

---

**Current situation:**

```
SITE_LOGO
MAIN_NAVIGATION
PAGE WRAPPER:

    POST H1
    Elementor_region
    POST CONTENT
```

**Desired situation:**

```
SITE_LOGO
MAIN_NAVIGATION
PAGE WRAPPER:

    Elementor_region
    POST H1
    POST CONTENT
```

**Comment by carasmo** [comment]
I think that is expected behavior, the page title is not part of the `the_content()` which is where Elementor goes. The work around is that you title and re-create it where you want it, there's a video here: https://docs.elementor.com/article/193-page-settings.

**Comment by Benqzq** [comment]
Hi Christina, I am not sure this is a good solution because the titles are added automatically with each blog post. I actually want to keep these titles, and just give a new nice heading to the blog-page itself like "Blog Page".

I believe it should be re-opened @KingYes .

**Comment by Benqzq** [comment]
@carasmo @KingYes , I think I found a near solution but reported feature suggestion regarding it:

https://github.com/pojome/elementor/issues/1755
