### ISSUE TITLE
Add custom query options for Query control

### ISSUE THREAD

**Issue by dineshlalvani** [pojome/elementor#1748]
## Description

Add the ability to create a custom query in the portfolio or posts module. This could be good to filter results based on custom fields using the meta_key and meta_value to build the query_post arguments.

**Comment by Ver3** [comment]
And hopefully allow for NOT displaying Woo Products that have visibility set to Hidden.

**Comment by arielk** [comment]
It's a great idea. In the upcoming version we added the option "Exclude" in the query control.

**Comment by Ver3** [comment]
That's great Ariel, thanks! We launch in three weeks, any possibility this will be released before then?

**Comment by arielk** [comment]
E-Pro 1.5.0 has been released the last few hours and include an Exclude option. Please update your version and check this out.

**Comment by Ver3** [comment]
Thank you Ariel, I just updated and used the exclude option. Great addition! Sadly you can only exclude specific products (or posts, pages..) not all products saved in Woo with visibility set to hidden.

If it would except a search term, I could rename hidden products (they are part of Variable or Composite products). Maybe better to have a check box after selecting "Products" from "Source" that says "Exclude content set to hidden" or something like that?


![image](https://cloud.githubusercontent.com/assets/20367733/26354700/feb4f982-3fc5-11e7-88a1-683ebd07251e.png)

**Comment by KingYes** [comment]
Hey @Ver3 

How you want to add this option (In UI level)? By the way I think you get security problem to allow this..

BUT - if you want to write some custom code, use with `parse_query` action (current `WP_Query` instance in first param), and add your custom query..

About your last question: Current Post exclude the current page you in. For example if you open Elementor in Post linked to "General" category. And you want to exclude this on your Query, so the current post not show there..

**Comment by Ver3** [comment]
Hi @KingYes

- UI level & Functionality suggestion: By default all Woo Products with visibility status set to "Hidden" will not show up. If a user wants to show them (very unlikely) they check the box "Show hidden post type". See screenshot for the place I have in mind. 

- Coding: Sadly not an option.

- Current Post: Thank you for explaining. Using Posts that makes sense. I use the Portfolio Widget for Woo Products only. But now I know for the future. Cheers.

<img width="628" alt="screen shot 2017-05-23 at 15 29 37" src="https://cloud.githubusercontent.com/assets/20367733/26356548/afdb192a-3fcc-11e7-87b8-4ffbb57a6e8c.png">

**Comment by KingYes** [comment]
But what you ask is special condition for WC. How you think we can do this for whole plugin?

**Comment by Ver3** [comment]
Apologies, English is not my native language. I will try to rephrase the 'problem' based on a quote I found:

"Any plugin that enables you to show WooCommerce products, should not show hidden products by default."

IF portfolio widget is set AND query source is 'products' AND filter bar is active THEN 'all'-link will result in showing all products, including ones set as 'hidden'.

I hope this helps. Am not sure how to explain better. Cheers.

**Comment by Ver3** [comment]
Just realised it might be easier to add a filter bar tot the "Woo Products" widget. That one does not show hidden products by default.

**Comment by KingYes** [comment]
I know. It's not WC widget.. :|

By the way, since WC3.0 hidden products based on Taxonomy (not Custom Field). Reference: https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#product-visibility-is-taxonomy-based-instead-of-meta-based

**Comment by Ver3** [comment]
I know it's not a WC widget, but it does support display of products. But never mind, sorry to bother you, have a great evening.

**Comment by carasmo** [comment]
In the WooProducts Elementor widget, if a product is hidden, the posts number is affected so if I want 6 posts, and I have a hidden product, then I get 5. I think it would be up to the person using the plugin to adjust the posts per page based on how many hidden products are in the query.


As far as the portfolio widget, if you chose `product` as the post type (Source), then you could adjust portfolio.php (Elementor Pro) to the following. However, like the WooProducts widge, it also messes up posts per page. No clue how to address that.

![screen shot 2017-05-23 at 1 28 31 pm](https://cloud.githubusercontent.com/assets/1124594/26367229/de2a2714-3fbb-11e7-9e86-67898b92bfea.png)

**Comment by KingYes** [comment]
@carasmo

You need override `query_posts()` method before WP_Query created. But maybe I'll add some filters there...

**Comment by dineshlalvani** [comment]
Hi All. Just to bring this back to the original query, is this something that is possible in a future release?

**Comment by KingYes** [comment]
What you mean @dineshlalvani ?

**Comment by dineshlalvani** [comment]
hi @KingYes See the attached mockup. The idea is to get a set of posts that match values based on custom fields. Alternatively, if there was a way to pass your own query_vars would also work. Do you think this is a good approach?

<img width="315" alt="elementor 2017-05-29 08-42-08" src="https://cloud.githubusercontent.com/assets/1092328/26536707/c109d6e6-444a-11e7-90be-14da79690326.png">

**Comment by KingYes** [comment]
But the query can be [complex queries](https://codex.wordpress.org/Class_Reference/WP_Query#Custom_Field_Parameters). How we can deal with that?

**Comment by Basilakis** [comment]
@KingYes Why not - make the query to also allow which Custom Post Type will be used?
That way we can have grids that can loop for example through Testimonials, Employes, Team Members etc.

**Comment by formulaclick** [comment]
This feature is included un Visual Composer as yo can see here: https://francoz.me/wp-content/uploads/2015/11/Schermata-2015-11-15-alle-23.31.30-580x386.png

This shoud be very usefull and I think it's easy to implement

**Comment by dasigna** [comment]
@formulaclick - YES! thats EXACTLY what i am after in elementor too!!
used this on occasion in VC and is really useful. (unfortunatly i do hate VC meanwhile - even more sice i know EL)

should be really an option, very soon!
just think of one simple scenario: having a post type called 'events' to show an image and description. then you would have one page to show 'upcoming events' and another to show 'past events' (kind of archive) - a natural split in this case, sorted out by the date of the post.
no way this time to achieve this within elementor (at least not known by me).

indeed extremely useful.

**Comment by dineshlalvani** [comment]
@formulaclick This is perfect. I hope they will add it to the Post and Portfolio modules.

**Comment by Ver3** [comment]
@dasigna This is EXACTLY the use case I'm now facing, and have not yet found a solution for. I;m now looking at plugins like Pods/ACF in combo with "Elementor Extra's" (timeline widget) and 'Woo show products as tables' plugins. Still no good solution found though.

We sell classroom trainings using woo, and would like to offer an overview of upcoming courses, without having to add them in Woo AND something else.

If you do find a solution, please let me know. I will do the same.

If this could be done with EM, would be superb.

**Comment by dasigna** [comment]
@ver3 - as already stated: i wish i had a proper solution for this in elementor. sadly i have not.

me too facing that scenario again, and giving me headaches because elementor does not provide a way to do this yet! as much as i am in big love with EL - as much i cant understand why the dealing with custom post types and such is so left behind by EL up til now
the ability of using cpts is (one of) THE big deal with wordpress and actually the use of them within EL is kind of caponised ;)  .... so i hope they will change this soon.

the only way i found to achieve this particular demand regarding events is using a plugin that can handle this, but there are not many good ones out there and even if so they're far to bloated and full of features you wont need - not to speak of mostly lacking the ability of _really_ personal styling.

so theres only one simple and proper way to achieve this: convince WP to show future posts (which is the easy part) and then be able to sort them by query (and/or custom taxonomies etc.) to show them on frontend.

EL currently does not provide any way to do so (if anyone knows better PLEASE tell us) - VC does easily. but i dont want to use VC again only because of this...!
simple solution: EL has to catch up! better today than tomorrow!! :-)



btw: where to find the 'Elementor Extra's Plugin' - dont know this one ...

**Comment by Ver3** [comment]
@dasigna It's in beta, https://www.facebook.com/groups/Elementors/permalink/1169930653132719/?match=dHVkb3I%3D

**Comment by pingram3541** [comment]
Glad I found this thread and would love this to be in Pro and save me loading up my functions.php with shortcodes to execute my queries within EL.  Another feature would be sorting buttons that can be shown on the front end, i.e. newest, oldest, category, tags similar to needs of the gallery UI/UE

**Comment by dasigna** [comment]
@pingram3541 - how do you execute queries via shortcode??? for posts and such? if you've found a way to combine a post widget with this, i would be highly interested in the way how it can be achieved ...

**Comment by pingram3541** [comment]
@dasigna - glad you asked, I just found this and going to have to test it out soon - https://wordpress.org/plugins/custom-content-shortcode/

**Comment by dasigna** [comment]
> @dasigna - glad you asked, I just found this and going to have to test it out soon - https://wordpress.org/plugins/custom-content-shortcode/

ahh yeah, thanks to this - think i already saw this before (but cant remember well...). maybe have to look again.
but two dowsides:
- seems not very well maintained (last update over a year ago)
- how do i get the two two worlds of shortcode and the possibilities of the el post widgets together ??? (always same problem...)

custom one might be cool - but only by melting it into el for seamless use! :-)

cant help - but i really think elementor guys should speed up and implement this into their widgets. otherwise one wont be able to link the abilities of the EL widgets with custom queries (or shortcodes) ... at least not in any satisfying and painless way i fear.

**Comment by pingram3541** [comment]
I agree, for the Pro offering to continue to retain value it needs more attention in my opinion.  I know we just got flashy animated titles which is great but I think one very big thing missing is the ability to re-order each of Elementor's elements, inner elements on the output, especially the posts widget.

A powerful (custom) post query widget is what has been lacking for a very long time and I'd prefer not to seek external plugins for this because they are not written as well as Elementor =)

**Comment by pingram3541** [comment]
@dasigna found this neat little gem - https://www.wp-hasty.com/tools/wordpress-wp-query-loop-generator/

**Comment by dasigna** [comment]
indeed - nice little thing :-). similar to generatewp but obviously more comfortable.
but same question again: how to combine it with the design power of elementor?????

as you mentioned before - the *powerful* (custom) post query widget is really missing!
totally agree there with your post too.

recently commented already in the elementor blog post for animated titles...
we already have plenty of powerful design options and fancy things (which is great), but what is really lacking is the power of generating (custom) dynamic content and make use of the possibilities of wp within(!) elementor.
really thinking that this is one of the main goals to achieve for the pro version ...
so el-guys should leave the 'playing' for a while and focus on the real deals! then afterwards i will be happy with more fancy again  ;-)

**Comment by black-eye** [comment]
+1 also curious about this feature

**Comment by ideasandpixels** [comment]
+1 On this issue. It should very extremely easy to add. Just a simple field for filtering by meta key/meta val. Right now, I have to leave Elementor to do this.

**Comment by notrealdev** [comment]
+1 billion

**Comment by whatsnewsisyphus** [comment]
Is there a hook at parse query?  Below is an example of a typical relationship query to list what classes a teacher is assigned to

You could code a little meta builder that allows you to stack key/value/compare operators (with sanitization so that you can't inject php code.)

UI integration would also need to incorporate some variables like $currentpost_id $currentpost_category and so forth. Or you could let very specific functions roll by in sanitization.
```
if (is_singular('faculty')) {// If a faculty page, find classes taught by that faculty
  $course_query['meta_query'] = array(
    array(
      'key' => 'course_faculty', // name of custom field
      'value' => '"' . get_the_ID() . '"', // id of current post to check against
      'compare' => 'LIKE'
    )
  );
```

**Comment by tristanleboss** [comment]
Same thing here : https://generatewp.com/wp_query/
This UI should be available in Elementor for each block querying posts as a popover, for example.

**Comment by joyspringmedia** [comment]
@bainternet any ETA for any implementation of a hook for wp_query on the posts module? This is a crucial feature for many of us. It's available on other popular page builders but having it in Elementor is going to solve so many of our issues. Thanks!

**Comment by joyspringmedia** [comment]
Pardon me for mentioning a competitor of yours, but this is how Beaver Builder have tackled this issue:
https://kb.wpbeaverbuilder.com/article/591-create-a-filter-to-customize-the-display-of-post-data

At minimum, this is what we need. Or, if you can implement this very same thing in the UI (as a text area where we can type in our query, as long as how to do this is properly documented), this would be highly appreciated. Thanks!

**Comment by joyspringmedia** [comment]
@bainternet why is the dev team silent on this? This is obviously one of the most important features that are missing here. Not just for casual designers but for bigger agencies with bigger clients. We need this desperately... :-/

**Comment by bfrye26** [comment]
Have you managed to select multiple post types with edits to the core files @ideasandpixels?  I would be open to ideas, in BB it is very easy to make these changes with a simple hook, but Elimentor does not seem to have a way to do it. It is such a useful feature

**Comment by formulaclick** [comment]
Web need this!!! Any ETA??? Why this silence?

**Comment by bainternet** [comment]
Probably next version, 🤞

**Comment by joyspringmedia** [comment]
@bainternet will this be a solution to do a fully custom query or just filter by a single meta key? We need the full solution pleaseee. Also, any ETA for next version?

**Comment by bainternet** [comment]
@joyspringmedia 

Full control via filter hook. as for ETA, I can only say soon. But stick around we will have a beta cycle for it here.

**Comment by gasmas75** [comment]
May I add my voice to this thread the importance of a taxonomy based on custom field value. It's a powerful feature.

**Comment by stein70090** [comment]
@bainternet Can you please supply example code on how to use the new Query Filter?

**Comment by bainternet** [comment]
@stein70090  

Sure, action hook is `elementor_pro/posts/query/{$query_id}` and is set per query instance. So first give the query and id so you can identify the query: 
![y1vdfhh](https://user-images.githubusercontent.com/660572/42203890-ce9d3610-7ea8-11e8-9c2e-a49f97bc9d17.png)

For this example my query id is: "stein70090" so my custom action hook becomes: 
`elementor_pro/posts/query/stein70090` and then you can apply the modifications like you would on any `pre_get_posts` hook:

```PHP
add_action( 'elementor_pro/posts/query/stein70090', function ( $wp_query, $posts_widget ) {
	$expire = get_field( 'post_end_date' ) ? : date( 'Ymd' );
	$wp_query->set( 'meta_query', [
		'relation' => 'OR',
		[
			'key'     => 'post_end_date',
			'value'   => $expire,
			'compare' => '>=',
			'type'    => 'NUMERIC',
		],
		[
			'key'     => 'post_end_date',
			'compare' => 'NOT EXISTS',
		],
	]);
}, 10 ,2 );
```

**Comment by stein70090** [comment]
@bainternet Great! Thanks 👍

**Comment by gfdesign** [comment]
Hi there
Could anyone guide me how to make a custom query filter with more than one CPT but that share a taxonomy?
For example, I have a real estate site where I have as CPTs: house, aparment, office and land, and all of them have a taxonomy 'property-type' with slug 'for-rent' or 'for-sale'.

I have this code to list 'house' and 'office' posts to for rent and I'd like you tell me if I can improve it.
```

// Showing multiple post types in Posts Widget
add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {

  // Add our tax query
  $tax_query = array(
	array(
	  'taxonomy'         => 'property-type',
	  'terms'            => 'for-rent',
	  'field'            => 'slug',
	),
  );

  // Modify the query
  $query->set( 'tax_query', $tax_query );    
  $query->set( 'post_type', [ 'house', 'office' ] );  
} );
```

Thanks in advance.
Best regards

**Comment by bryanbartow** [comment]
Forgive my ignorance, but where is one supposed to add this `add_action` declaration? While file does it need to be added to? It's unclear to me from [the docs](https://developers.elementor.com/custom-query-filter/)

**Comment by stein70090** [comment]
@bryanbartow Add it to the functions.php file in your current theme folder.

**Comment by bryanbartow** [comment]
@stein70090 That was it. Thank you very much.

**Comment by deviis** [comment]
could this be used for the woocomerce widget? I dont see a place where to write my query ID...

**Comment by AkhilAniyan** [comment]
Hi,

Can someone help me why this is not working? Its been 2 days I can't figure out why this is not working!

```
add_action( 'elementor_pro/posts/query/agency_filter_featured', function( $query ) {
	// Get current meta Query
	$meta_query = $query->get( 'meta_query' );
	// Append our meta query
	$meta_query[] = [
		'key' => 'agency_featured',
		'value' => 'yes'
	];
	$query->set( 'meta_query', $meta_query );
} );
```
Notes: 

- This is a custom post created using CPTUI
- Added custom query on posts widget query
- Created a custom field called "agency_featured" with a checkbox "yes" to feature the listing using ACF. I checked the meta in the database, and meta is working fine: https://prnt.sc/lcjrq6

I'm I missing something?

Thanks!

**Comment by AkhilAniyan** [comment]
> Hi,
> 
> Can someone help me why this is not working? Its been 2 days I can't figure out why this is not working!
> 
> ```
> add_action( 'elementor_pro/posts/query/agency_filter_featured', function( $query ) {
> 	// Get current meta Query
> 	$meta_query = $query->get( 'meta_query' );
> 	// Append our meta query
> 	$meta_query[] = [
> 		'key' => 'agency_featured',
> 		'value' => 'yes'
> 	];
> 	$query->set( 'meta_query', $meta_query );
> } );
> ```
> 
> Notes:
> 
>     * This is a custom post created using CPTUI
> 
>     * Added custom query on posts widget query
> 
>     * Created a custom field called "agency_featured" with a checkbox "yes" to feature the listing using ACF. I checked the meta in the database, and meta is working fine: https://prnt.sc/lcjrq6
> 
> 
> I'm I missing something?
> 
> Thanks!

It worked when I changed from Checkbox to radio button...!!!

**Comment by FiveHorizons79** [comment]
Dear all,
I have Elementor Pro 2.2.0 installed and Events Manager 5.9.5
I would like to have "post" or "portfolio" widget listing my events and sorted by "event starting date" not by the "publishing date".
after some surfing looking for solutions, I suppose to have to create this kind of function but I don't know how.

A kind help would be really appreciated.

My best regards
Alberto

**Comment by mwittmann** [comment]
Alberto's tip above was very helpful. To get future events sorted by both date and time, I ended up with the following:

                add_action( 'elementor_pro/posts/query/events_sortasc', 'events_sort_ascending' );
            public function events_sort_ascending($query){ 
                $query->set('post_type', 'event'); 
                $today = Date('Y-m-d');
                $query->set('meta_query', array(
                    'start_date' => array(
                        'key' => '_event_start_date',
                        'value' => $today,
                        'compare' => '>=',
                    ),
                    'start_time' => array(
                        'key' => '_event_start_time',
                        'value' => '',
                        'compare' => '>=',
                    )
                ));
                $query->set('orderby', array('start_date'=>'ASC','start_time'=>'ASC'));
            }

**Comment by Basilakis** [comment]
I do not understand why this is marked as closed - it is a topic with amazing stuff inside :)

Thank you everyone for sharing.

**Comment by boabjohn** [comment]
Howdy all, apologies, PHP is not my native language.
Desperately trying to get a sort order to work on my CPT and this thread is very helpful.
I have a CPT called cemperson
There is an ACF field key = family_name
But this is not working:

`// Posts Widget my_function_name
add_action( 'elementor_pro/posts/query/my_function_name', function( $query ){
	$query->set('post_type', 'cemperson');
	$query->set('orderby', '_family_name');
	$query->set('meta_key', '_family_name');
	$query->set('order', 'ASC');
} );`

Could any of you generous PHP folk help me get this function working?

**And gosh yes it would be nice to have even a basic version of this sort of functionality in the Elementor UI**

**Comment by gasmas75** [comment]
Hi boabjohn,
Why do you have an extra underscore on your variable setting? it should be 'family_name'; and not '_family_name';

**Comment by boabjohn** [comment]
Sorry for slow reply, and thanks for help...BUT, the sort is not sorting even with the underscores removed.
Just added a new post, with family name "Abelard". The post appears as the last in the list, indicating the orderby is still defaulting to date of the post, not my custom field:

 `// Posts Widget cem_sort_familyname
add_action( 'elementor_pro/posts/query/cem_sort_familyname', function( $query ){
	$query->set('post_type', 'cemperson');
	$query->set('orderby', 'family_name');	
	$query->set('meta_key', 'family_name');	 
	$query->set('order', 'ASC');
} );`

**Comment by pournamikp** [comment]
Hi, I am using elementor with woocommerce. I am using posts widget to show products in the archive page. Now i need to add a custom query to that widget where it will include an extra category name along with the current query.
i.e., i want to show products that is coming under current query and an extra category.
i tried custom query but its not working.

**Comment by FiveHorizons79** [comment]
> Alberto's tip above was very helpful. To get future events sorted by both date and time, I ended up with the following:
> 
> ```
>             add_action( 'elementor_pro/posts/query/events_sortasc', 'events_sort_ascending' );
>         public function events_sort_ascending($query){ 
>             $query->set('post_type', 'event'); 
>             $today = Date('Y-m-d');
>             $query->set('meta_query', array(
>                 'start_date' => array(
>                     'key' => '_event_start_date',
>                     'value' => $today,
>                     'compare' => '>=',
>                 ),
>                 'start_time' => array(
>                     'key' => '_event_start_time',
>                     'value' => '',
>                     'compare' => '>=',
>                 )
>             ));
>             $query->set('orderby', array('start_date'=>'ASC','start_time'=>'ASC'));
>         }
> ```
> 
> The 'compare' for the time isn't really needed, but it seemed to be the only way to get the 'orderby' clause to recognize both sort fields.

Thanks Mwittmann, very good.
In my case it doesn't work due to the "public" declaration, so I moved in this way
`add_action( 'elementor_pro/posts/query/eventi_HP', function ($query){ 
            $query->set('post_type', 'event'); 
            $today = Date('Y-m-d');
            $query->set('meta_query', array(
                'start_date' => array(
                    'key' => '_event_start_date',
                    'value' => $today,
                    'compare' => '>=',
                ),
                'start_time' => array(
                    'key' => '_event_start_time',
                    'value' => '',
                    'compare' => '>=',
                )
            ));
            $query->set('orderby', array('start_date'=>'ASC','start_time'=>'ASC'));
        } );`

**Comment by budlix** [comment]
Wow! This shouldn't be closed. Such an useful info here.
What I am struggling with (as I'm not into code) is how to merge both functions mentioned here?

I mean following: 
Function by @bainternet for excluding past posts from loop via ACF date field is working. But I am not able to SORT them via same date field.
Function by @mwittmann for sorting posts via ACF date field is working but I need also that Exclude function. 

Was trying play with it around for hours, but only result was my hair is even more gray...
Do you have any tip or help how to compile those two functions into one?
Thank you in advance guys!

**Comment by soyket** [comment]
If anyone is looking at this in 2020, I came across a plugin and maybe this plugin will be of use http://elequerybuilder.com/

**Comment by Dmwds** [comment]
> 
> 
> Dear all,
> I have Elementor Pro 2.2.0 installed and Events Manager 5.9.5
> I would like to have "post" or "portfolio" widget listing my events and sorted by "event starting date" not by the "publishing date".
> after some surfing looking for solutions, I suppose to have to create this kind of function but I don't know how.
> 
> A kind help would be really appreciated.
> 
> My best regards
> Alberto
> 
> ok, I solved it.. just in case could be helpful for someone that's the code..
> 
> ```
> add_action( 'elementor_pro/posts/query/id_of_the_query', function( $query ){
> 	$query->set('post_type', 'event');
> 	$query->set('orderby', '_event_start_date');	
> 	$query->set('meta_key', '_event_start_date');	 
> 	$query->set('order', 'ASC');
> } );
> ```

did you get to add scope?
