### ISSUE TITLE
[Feature Request] Portfolio item title permanently visible & placement

### ISSUE THREAD

**Issue by moschx** [pojome/elementor#1750]
Hi there,

I'm a pro user and i'm really loving Elementor. Only thing I would really enjoy is an option to have the title of a portfolio item be visible at all times (now visible on roll-over). Especially important for browsing on mobile devices. Which would suggest it would be great if this can be activated based on screen type. Also would be great to have an option to place the title onder or above the thumbnail. 

Hope this can be incorporated soon 👍

**Comment by arielk** [comment]
You can use a Posts widget with Cards skin for a nice view of posts or a portfolio.

Unfortunately at the moment there are no other options to do this using a portfolio widget, but in the future we will add more skins for it.

Thanks for your feedback!

**Comment by ge2tis2** [comment]
I would love to have same option portfolio item be visible at all times (now visible on roll-over). When will you introduce this option? @arielk

**Comment by drawcard** [comment]
The one limitation with @arielk 's suggestion is that there is no Filter Bar for the Posts widget, so if we want to use a filter bar and have permanent titles, that is sadly not possible. I would like to put my vote in for the option of persistent titles to be displayed below the item.

**Comment by drawcard** [comment]
This is a hacky workaround that I've just discovered but it's based on the idea that the title data is actually already on the page at all times, it's just toggled on and off by the thumbnail hover CSS.

So if the data is already there in the page:
![image](https://user-images.githubusercontent.com/1435638/44453393-17a70000-a638-11e8-941f-7d63c4d96ab4.png)

You can disable the opacity hover to show it at all times:
![image](https://user-images.githubusercontent.com/1435638/44453486-491fcb80-a638-11e8-8aa1-626aac8a538d.png)

Resulting in:
![image](https://user-images.githubusercontent.com/1435638/44453621-a6b41800-a638-11e8-9355-c77bf07d10f8.png)

Now you need to play around with the CSS a bit more to style it to your needs, and of course you lose the opacity hover effect altogether, but if you really need to throw something together this is a way to do it.

This is the custom code you need to drop into the Custom CSS panel of the Portfolio widget to make it work:

![image](https://user-images.githubusercontent.com/1435638/44453873-4a9dc380-a639-11e8-9078-136fd9e89678.png)

In saying all of this -- I still think it's better to have this option provided to us and not have to resort to hacking CSS that is prone to breaking at any point in the future 😄

**Comment by weblad** [comment]
+1

**Comment by Dynojezz** [comment]
thx @drawcard... works pretty well :)
