### ISSUE TITLE
Feature request: Please let us choose if "Last posts" element feature only heading or whole content

### ISSUE THREAD

**Issue by Benqzq** [pojome/elementor#1755]
I searched for a way to create an Elementor page of blog posts. I found a near solution with the "Last posts" element:
![1](https://cloud.githubusercontent.com/assets/13021900/26387334/640bd280-4055-11e7-9d3c-d849f978eb21.PNG)

This nice element shows a list of the h1 headings of current blog posts.

Yet, I would love to have the possibility to choose between showing the whole posts, or just their headings.

**Comment by arielk** [comment]
You need to do it with [Elementor Pro](https://elementor.com/pro/), you can learn more about this widget here:
https://elementor.com/pro-posts-in-action/
https://elementor.com/pro-v150-cards-skin/

**Comment by Benqzq** [comment]
I can do it with it or with some custom call to mine the data. Thanks for noting it is is possible with it. Good to know. I will recommend it to customers with that need.

**Comment by Benqzq** [comment]
I can do it with it or with some custom call to mine the data. Thanks for noting it is is possible with it. Good to know. I'll probably recommend it to customers with that need.
