### ISSUE TITLE
Card Skin and H tags

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#1757]
## Steps to reproduce

When using the Posts Widget with the Classic skin, I can change the H tag for the title, and it updates based on my theme styles for headings. 

When using the Posts Widget with the new Card skin, changing the H tag for the title does not alter the size in keeping wth my theme styles for headings. Note that the H2 should be significantly bigger than the H3 in the Classic example, yet it is not. Possible bug?

<img width="1048" alt="classic" src="https://cloud.githubusercontent.com/assets/974442/26433556/572f95ca-40b8-11e7-94dc-ae4e00269969.png">
<br><br><br>
<img width="1049" alt="card" src="https://cloud.githubusercontent.com/assets/974442/26433557/573190aa-40b8-11e7-90f7-516c58309bfc.png">

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: 5.5.49
	PHP Version: 5.6.30-7+deb.sury.org~precise+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.5
	Site URL: https://staging.ucsflibrary.flywheelsites.com
	Home URL: http://staging.ucsflibrary.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Permalink Structure: /news/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Dynamik-Gen
	Version: 2.2.0
	Author: The Cobalt Apps Team
	Child Theme: Yes
	Parent Theme Name: Genesis
	Parent Theme Version: 2.5.0
	Parent Theme Author: StudioPress

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 3.3.2
		Author: Automattic

	Breadcrumb NavXT
		Version: 5.7.0
		Author: John Havlik

	Compress JPEG & PNG images
		Version: 2.2.2
		Author: TinyPNG

	Elementor
		Version: 1.4.7
		Author: Elementor.com

	Elementor Pro
		Version: 1.5.0
		Author: Elementor.com

	Genesis Dambuster
		Version: 1.6
		Author: Russell Jamieson

	Graceful Email Obfuscation
		Version: 0.2.2
		Author: Nicholas Wilson, Jason Hendriks

	Insert Pages
		Version: 3.2.2
		Author: Paul Ryan

	Jetpack by WordPress.com
		Version: 4.9
		Author: Automattic

	LH HSTS
		Version: 1.20
		Author: Peter Shaw

	LibCal Hours for WordPress
		Version: 1.0.1
		Author: Stefan Topfstedt

	Loginizer
		Version: 1.3.4
		Author: Raj Kothari

	MailChimp for WordPress
		Version: 4.1.3
		Author: ibericode

	Redirection
		Version: 2.5
		Author: John Godley

	Relevanssi
		Version: 3.5.10
		Author: Mikko Saari

	Sticky Menu (or Anything!) on Scroll
		Version: 2.0.1
		Author: Mark Senff

	TablePress
		Version: 1.8
		Author: Tobias Bäthge

	UCSF Library Search Filter
		Version: 1.0.0
		Author: Stefan Topfstedt

	User Role Editor
		Version: 4.33
		Author: Vladimir Garagulya

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WPForms
		Version: 1.3.7.3
		Author: WPForms

	WPForms Conditional Logic
		Version: 1.1.9
		Author: WPForms

== Debug ==
	Errors: 
		TypeError: Cannot read property 'getActiveControls' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.4.4 - 2:5358
			2017-05-22 21:43 +00:00
			x 119 times

		TypeError: Cannot read property 'getActiveControls' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.4.2 - 2:5358
			2017-04-20 23:26 +00:00
			x 68 times

		TypeError: e is null
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.2 - 4:1
			2017-04-11 06:50 +00:00
			x 2 times

		TypeError: d is undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.4.2 - 2:5355
			2017-04-11 06:26 +00:00
			x 4 times

		TypeError: Cannot read property 'pageYOffset' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 - 4:30810
			2017-04-10 18:40 +00:00

		TypeError: $.LibCalWeeklyGrid is not a constructor
			at https://staging.ucsflibrary.flywheelsites.com/about/hours/?elementor - 4:13
			2017-04-10 18:39 +00:00
			x 5 times

		TypeError: Cannot read property 'getActiveControls' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.4.2 - 2:5358
			2017-04-05 19:13 +00:00

**Comment by KingYes** [comment]
I don't know if it's a bug. Please see from where you get the title size. Maybe Elementor override your theme styles..

**Comment by mizejewski** [comment]
@joshmarom @arielk there was a similar problem affecting headings, in general, back on https://github.com/pojome/elementor/issues/533

**Comment by carasmo** [comment]
I use the classic skin or the card skin it's always 18px. That is due to this:

![screen shot 2017-05-26 at 3 42 28 pm](https://cloud.githubusercontent.com/assets/1124594/26510238/6848e794-422a-11e7-8dc3-588acbb96d6b.png)

**Comment by mizejewski** [comment]
Yes, I created a similar style to @carasmo for my own particular use. However, the issue I am pointing out is the fact that without applying any custom CSS, changing from one H tag to another in Elementor settings *should* change the size of the title (regardless of the widget) to reflect the heading styles set in the theme.

**Comment by carasmo** [comment]
I have not applied any custom CSS either. I agree. If you choose h3 it should be the theme's h3 if you choose span or h2 it should be the base font size or the h2 respectively.

**Comment by arielk** [comment]
We strive to give pretty design ready for each element, so unfortunately we can not handle it in another way.

Thanks for your feedback!

**Comment by mizejewski** [comment]
I don't understand why H tag styles are passed from the theme when using Posts Widget with the Classic skin but not when using the Card skin. Shouldn't they be the same. Not sure what "We strive to give pretty design ready for each element" means @arielk

**Comment by arielk** [comment]
Different themes put special style for heading which sometimes can break the structure, so we had to set a spesific size for the title.

But you can change the default by custom CSS..
