### ISSUE TITLE
Option/Filter to modify core element 

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#1759]
Is there any way to modify core shortcode element. Say I want to add extra setings/option to column . May be 

1. Using filter
2. Overight (If shortcode exist in plugin/theme directory then load from there if not load from core plugin).
3. Filter to change shortcode folder.  

I have seen other page builder like [Unyson](https://github.com/ThemeFuse/Unyson/), [Tailor](https://github.com/andrew-worsfold/tailor) have such feature.

**Comment by arielk** [comment]
We're not using shortcode at all. You can learn how Elementor works by the API for developers: https://github.com/pojome/elementor/tree/master/docs

Let me know if you any more questions

Regards

**Comment by Basilakis** [comment]
You can take a look here also:
https://gist.github.com/dtbaker/aacac996beddc3bcfb1632c3b3d5347b

To understand how things work.
