### ISSUE TITLE
Tiny WYSIWYG editor for Repeater control

### ISSUE THREAD

**Issue by lindseywb** [pojome/elementor#176]
Would love if elements that have text blocks (accordions, tabs, etc.) had a WYSIWYG for clients who aren't comfortable with HTML.

**Comment by edirpedro** [comment]
Maybe if create a new control `basic_editor` that instantiate the TinyMCE with only few buttons likes bold, italic, underline, insert link, remove link, strike, text color, clear formatting, special chars ...

**Comment by arielk** [comment]
Yep. We're trying to figure out how to do it with the necessary minimum in order that the UI will still beautiful.

**Comment by arielk** [comment]
merged to: https://github.com/pojome/elementor/pull/830
