### ISSUE TITLE
Bug in the video widget/lightbox

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1763]
When choosing lightbox off, the cover image is displayed fine (centered), but when choosing Lightbox on it align the cover image to the left.
Lightbox off:
![videocover without lightbox](https://cloud.githubusercontent.com/assets/14095280/26498867/d2d10406-4230-11e7-8050-6965f4fe5286.JPG)

Lightbox on:
![videocover with lightbox](https://cloud.githubusercontent.com/assets/14095280/26498885/e5f0aa3c-4230-11e7-81fd-0be324a4d5ea.JPG)

**Comment by KingYes** [comment]
@HelmutGoebel 

Thanks!
