### ISSUE TITLE
Post issue with read more 

### ISSUE THREAD

**Issue by bobocop4u** [pojome/elementor#1764]
If a query is made it will give you the appropriate posts. On this page you have a read more that works with the permalink. Everything works fine. Except with the following example.

If a query is made it will give you the appropriate posts. If those post include a query as well (even if it is not visible on your query) the Elementor builder will give you the permalink on the read more text.  When you save the page it will result in a non functional read more with the parent page as link. So you will stay on the same page.

**Comment by arielk** [comment]
I'm not sure I understand exactly what you mean. I would be happy if you explain better or bring an example.

Perhaps you meant this issue https://github.com/pojome/elementor/issues/462?

**Comment by bobocop4u** [comment]
I guess it's not. I do not use a seperate tag outside the elementor pr plug-in.  I use the option provided By the plug-in. If you go to my website an chose archief - voorstellingen. You can see the problem. The First two wil work alk the other Will not. 
The inkt difference is rhy have a query inside the plogpost. 

If you click on the subject it does work.... strange thing. 

Bo

Verstuurd vanaf mijn iPhone

**Comment by arielk** [comment]
I will glad to check it, what's the URL of your website?

**Comment by bobocop4u** [comment]
www.dbwtoneel-be.pcxtmp.nl

Verstuurd vanaf mijn iPhone

**Comment by arielk** [comment]
This is something that comes from the GeneratePress theme, you need to add filter to remove the "read more" that come from your theme. Please contact the author of the theme with the problem.
