### ISSUE TITLE
Add black_list filter to Widgets_Manager->_init_widgets()

### ISSUE THREAD

**Issue by ShaMSofT** [pojome/elementor#1765]
As you can see in [Widgets_Manager->_register_wp_widgets()](https://github.com/pojome/elementor/blob/master/includes/managers/widgets.php#L82), there is a 'elementor/widgets/black_list' filter. It would be great if you add this filter to Widgets_Manager->_init_widgets() as well. So theme/plugin developers can exclude some widgets from initialization.

**Comment by KingYes** [comment]
Hey @ShaMSofT 

Thanks for your request, but you can unregister them by `elementor/widgets/widgets_registered` action.
