### ISSUE TITLE
Elementor W3 Validator issue 

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#1773]
Did you guys notice that elelmentor has several error issue with w3 validator when using the video embeed, the map?

https://validator.w3.org/

Can you check these issues and fix em in new update ? :) Because if Themeforest projects these problems are very serious. But seeing the errors tells me it won't take much time for you guys to update it and make a new release

Thanks !

**Comment by arielk** [comment]
We embed the video and the map exactly the same if you embed it yourself with the official Google and YouTube code.

Did you try to embed the code directly into the text editor of WP and check it with the validator?

**Comment by soyket** [comment]
Nope I didn't ! I generally use plugin or custom code (with js) . Maybe you guys should use free js to embeed videos! because w3 validation is very important when you want to submit it to TF and other market place !

**Comment by arielk** [comment]
As I said above, we use YouTube's standard code and we do not add anything beyond that, so if there are errors, it probably comes from the YouTube source code.

Thanks for your feedback!

**Comment by carasmo** [comment]
When I embed, I change the ampersand to `&amp;` and this removes the validation errors.
