### ISSUE TITLE
Documentation Error 

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#1774]
Hi, 
I noticed that you documentation / developer api : https://github.com/pojome/elementor/blob/master/docs/content/controls/_url.md
has an error with video default setting . It should be : 

'default' => [	'url' 	=> 'https://www.youtube.com/watch?v=YaNHssp_Jqg',
					],

but it's written as 'default'  => 'http://'

which doesn't work. Do update that

**Comment by KingYes** [comment]
You right. Thanks.

**Comment by soyket** [comment]
@KingYes  @joshmarom  I still see same old setting in the documentation !

**Comment by KingYes** [comment]
It's on our dev branch.. when we release this, it's will be in master branch..
