### ISSUE TITLE
Custom padding bug (mostly on Columns)

### ISSUE THREAD

**Issue by Stegosource** [pojome/elementor#1776]
## Description

When you add custom padding to elements, it's not possible to leave an input blank (ie. padding-left). Instead, as soon as I turn off the linked padding feature, all options are set to 0 and it is impossible to leave any input blank. The result is that if I only want to add top and bottom padding, the default padding is set to 0 and I have to manually add it back. It would be much better if the default remains until I overwrite it. 

Another issue I have which is less of a bug and more of a feature is to have the linked padding turned off by default. It is much less common that I want the top, right, bottom, and left padding to all be the same. Much more often that I only need top and bottom, or that they are all different.

## Steps to reproduce

Install Elementor and create a page. Add a section with a couple columns. Edit one of the columns and go to the advanced tab. Uncheck the option to link all padding sizes. Edit just the top or bottom padding.

If you check the page on mobile devices. the content in that column will touch on the left and right because those values were overwritten by Elementor to 0 instead of keeping their default values.

## Environment
			
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
	MySQL version: 5.6.35
	PHP Version: 5.6.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.5
	Site URL: https://dev-tfs.thisisvisceral.com
	Home URL: https://dev-tfs.thisisvisceral.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 96M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Tools for Schools
	Version: 1.0.0
	Author: Visceral
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.881

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.5.14
		Author: Elliot Condon

	Broken Link Checker
		Version: 1.11.2
		Author: Janis Elsts, Vladimir Prelovac

	Custom Post Type UI
		Version: 1.5.3
		Author: WebDevStudios

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Easy Forms for MailChimp
		Version: 6.3.19
		Author: YIKES, Inc.

	Elementor
		Version: 1.4.8
		Author: Elementor.com

	Enable Media Replace
		Version: 3.0.6
		Author: Måns Jonasson

	EWWW Image Optimizer
		Version: 3.3.1
		Author: Shane Bishop

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.0.0.1
		Author: Alin Marcu

	Gravity Forms
		Version: 2.2.3
		Author: rocketgenius

	Gravity Forms Repeater Add-On
		Version: 1.0.9
		Author: Kodie Grantham

	Intuitive Custom Post Order
		Version: 3.0.8
		Author: hijiri

	iThemes Security Pro
		Version: 3.8.0
		Author: iThemes

	MainWP Child
		Version: 3.4
		Author: MainWP

	Optimize Database after Deleting Revisions
		Version: 4.2.2
		Author: CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands

	Password Protected
		Version: 2.0.3
		Author: Ben Huson

	Redirection
		Version: 2.6
		Author: John Godley

	SearchWP
		Version: 2.6.1
		Author: Jonathan Christopher

	Visceral Page Elements
		Version: 1.0.0
		Author: Visceral

	WP Help
		Version: 1.5.1
		Author: Mark Jaquith

	Yoast SEO
		Version: 4.8
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property 'pageYOffset' of undefined
			at https://dev-tfs.thisisvisceral.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 - 4:30810
			2017-05-24 20:35 +00:00
			x 11 times

		TypeError: Cannot set property 'isManualRemoving' of undefined
			at https://dev-tfs.thisisvisceral.com/tfs-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.6 - 5:3589
			2017-05-16 20:51 +00:00

		TypeError: Cannot read property 'pageYOffset' of undefined
			at https://dev-tfs.thisisvisceral.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 - 4:30810
			2017-05-10 21:32 +00:00
			x 60 times

**Comment by arielk** [comment]
Sorry about the delay, I just see this problem, has she got along already?

If not, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by Stegosource** [comment]
Yes this issue is still open. I thought bug fixes were supposed to be created in GitHub? 

Anyway, this issue is not just on my site, it's for any Elementor install. If you add a column and drop in a widget, it's easier to see. Then go to the column settings, the advanced tab, and unlink the custom padding values. As you can see, each value automatically gets set to 0. The default is actually 10px, so it should by default be set there and then someone can change each as they please.

**Comment by arielk** [comment]
Ok, this is not a bug, it's the default behavior of Elementor.

We prefer not to save default values, to keep the database clean as we can.

Thanks for your feedback!

**Comment by Stegosource** [comment]
Ok, I can understand that point and it's fair. But in that case, couldn't the logic just live in the files and check whether a custom value has been set or if it's null? If it's a custom value, set it. If not, use the default 10px?

Sorry for pushing the issue, I just feel like it's not a great user experience if I only want to add bottom padding to a column, I have to also reset the top, left, and right to the default value.
