### ISSUE TITLE
Gallery Widget on Elementor  does not allow you to add alphabetically or manually order the images

### ISSUE THREAD

**Issue by Charlesweb01** [pojome/elementor#1781]
Image gallery widget does not give the option to alphabetically or manually order the images on the gallery. 

Sometimes we wish to show some images first and other last. 

For this case, I could rename the files and call them:  pic01.jpg, pic02.jpg, pic03.jpg ... etc.

**Comment by Basilakis** [comment]
It's not that simple.

When uploading multiple images the upload order also depends on how the image files are displayed and sorted in the OS (top to bottom and left to right). A much better sort order for photos/JPEGs would be by the EXIF creation date. That should probably be the default sort order for galleries.

That is also something from WordPress Core, not solved 5 years now. If WordPress core allows that, then Elementor would inherit automatically.
