### ISSUE TITLE
Social media share

### ISSUE THREAD

**Issue by axiomteck** [pojome/elementor#1782]
Can you make social media share and visit our page on social media on a single icon instead of add share buttons and visit us on social media buttons. You should combine them togeter

**Comment by Basilakis** [comment]
You can instead use a 3rd party plugin for that, it is not a request that could help everyone :)

An other option, is to make that as 3-4 different options as layouts for the widget, but I guess other stuff have priorities.

**Comment by arielk** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
