### ISSUE TITLE
Feature suggestion - Blog post element

### ISSUE THREAD

**Issue by ghost** [pojome/elementor#1787]
I suggest adding a Blog post element. This will look something like this:

```
-o
--
```

Where `-` is text and where `o` is an image. 

- Such an element could alternatively be called "text with image".
- It would save the need to create 4 regions: The first of two columns are text (from left) and image (from right), and the second two underneath are text (from left) and text (from right).

---

Sometimes, especially for short blog posts, you don't want a sophisticated layout, just some text and image.

It reminds a newspaper layout where some of the text usually goes under the image.

Now we could do this in Elementor this way:
```

Text column, Image column
Text column under the two
```

Or alternatively
```

Text column, Image column,
Text column, Text Column.

```
All of this could be saved with a dedicated element.

This could hasten the process of laying out blog posts with Elementor.

**Comment by Basilakis** [comment]
The best case scenario, is to actually use the " template function " and allow users to use elementor to create the grid we want, with a drag n drop and usage of #flexbox @benpines

**Comment by arielk** [comment]
I want to understand the issue, can you please explain more about the idea?

**Comment by Benqzq** [comment]
I've greatly edited the original post.

**Comment by arielk** [comment]
Thanks for the explanation, just for the better clarify, can you please attach example screenshots?

**Comment by Benqzq** [comment]
Here is approximately how it should look like. Note the textual part should be more fluent without the spacing between the vertical and horizontal part.

![option](https://user-images.githubusercontent.com/13021900/28752439-f75c644e-7527-11e7-9ecc-1bb4b0741872.PNG)

**Comment by Benqzq** [comment]
Ofcourse, this is good, usually only for Desktop...

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
