### ISSUE TITLE
make a way to exprt the global.css with theme file

### ISSUE THREAD

**Issue by rony747** [pojome/elementor#1790]
we need an option to export the global css and other css file that is on uploads folder. simple xml export does not contains the style files. so its very hard to export an elementor theme properly. thanks

**Comment by KingYes** [comment]
You don't need the CSS files. You just need the JSON we stored on the DB. And when you done with the import task, you just need to run re-generate CSS files, and all will be good.

**Comment by Micemade** [comment]
Hi,
any suggestion on which hook / function to use for re-generate global.css ?

Thanks
