### ISSUE TITLE
video widget not working on my live server 

### ISSUE THREAD

**Issue by sheli21** [pojome/elementor#1792]
Hello

On my localhost everything works perfectly. But after I uploaded to the live server I started having problems.

http://clglaw.co.za/

I went in and made a new section to try upload the videos again but it still does not work. I also made a new page. Pls see these two clips to show problem:

https://youtu.be/J0a7rldL48k
https://youtu.be/fH20eFQyO0w
<img width="1023" alt="screen shot 2017-06-04 at 7 39 01 pm" src="https://cloud.githubusercontent.com/assets/20577455/26764127/1f427978-4961-11e7-825d-d28e202b0078.png">
<img width="734" alt="screen shot 2017-06-04 at 7 46 42 pm" src="https://cloud.githubusercontent.com/assets/20577455/26764128/2355274a-4961-11e7-8d08-3f66727a3e26.png">
<img width="819" alt="screen shot 2017-06-04 at 7 47 17 pm" src="https://cloud.githubusercontent.com/assets/20577455/26764129/24fd577a-4961-11e7-8ede-41a84661d5c1.png">

**Comment by sheli21** [comment]
it was a problem with the server! All is sorted now!

**Comment by jodelfritz** [comment]
Hey, I got a pretty similar issue. Can you elaborate on the server problems and how you fixed it? Thanks!
