### ISSUE TITLE
Anchor element upset my page layout

### ISSUE THREAD

**Issue by sheli21** [pojome/elementor#1793]
When I added in the anchor element it upset the flow of my page. Here are screen shots to show you:
<img width="1202" alt="screen shot 2017-06-02 at 5 14 24 pm" src="https://cloud.githubusercontent.com/assets/20577455/26774391/60c280cc-49d0-11e7-9e68-9d8676cac9ba.png">
 Once I removed the anchor elements the layout went back to normal:

<img width="1319" alt="screen shot 2017-06-04 at 3 07 18 pm" src="https://cloud.githubusercontent.com/assets/20577455/26774419/77719e2a-49d0-11e7-8c18-c620ddb1d70e.png">

## Description
When I added in the anchor element it upset the flow of my page. Here are screen shots to show you:
<img width="1202" alt="screen shot 2017-06-02 at 5 14 24 pm" src="https://cloud.githubusercontent.com/assets/20577455/26774391/60c280cc-49d0-11e7-9e68-9d8676cac9ba.png">
 Once I removed the anchor elements the layout went back to normal:

<img width="1319" alt="screen shot 2017-06-04 at 3 07 18 pm" src="https://cloud.githubusercontent.com/assets/20577455/26774419/77719e2a-49d0-11e7-8c18-c620ddb1d70e.png">

## Steps to reproduce

I am using the 2017 theme.

## Environment

localhost

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
