### ISSUE TITLE
Can't set image custom size

### ISSUE THREAD

**Issue by ivan133** [pojome/elementor#1798]
1. I add image
2. set width (or height) or both
3. press apply and after if I see in preview and in the website
![elementor - main](https://cloud.githubusercontent.com/assets/4018236/26828289/5932d4f2-4ac9-11e7-94ab-f39858b01931.png)

WordPress version 4.7.5
Elementor version  1.4.8

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
