### ISSUE TITLE
[Feature Request] Tabbed section | Advanced Tabs

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#1804]
Hello! What we do when we need to place more content? We hide it, ex. in tabs or toggle. But now elementor has very short opportunities to place content in tabs. Then I propose to do tabbed section which we can use to place rows and widjets into them.

The best case is Webflow. I did [this project](http://coffee-online.kz/) in it and it's good. It's in russian but you can intuitive understand (refuse translation in chrome it brakes layout).
At the 2nd section you can see tabs with icons with methods of preparation. In each tab we have rows with content. It's very comfortable to place content with this method.

I hope you understood my russian english =)

Thanks!

**Comment by enkota** [comment]
+1 - Nested elements would be awesome. For instance top level elements such as 'Tabs' or 'Toggle' would allow elements such as text/images/video etc to be placed on each tab. This would be a good way to filter out content on pages with lots of text.

**Comment by parfilov** [comment]
Hi again!
[Here is](https://www.ultimatebeaver.com/modules/advanced-tabs/) the beaver builder addon example about this whish. And [here](https://www.wpcrafter.com/contact/) they are in action.

So much content in one place and compact view — awesome!

**Comment by bainternet** [comment]
I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by GavinVDH** [comment]
Hi , Can a person not get this feature on default in elementor ?

add advance features , like nested widgets on the tabs widget?

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
