### ISSUE TITLE
Default language in settings

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#1805]
Hello! Elementor Pro translation was updated in my Russian but its auful. A half not translated. Somewhere layout has gone because of the different length of words.
I've delete russian.po and mo via FTP but it's not convenient. Do the default language selector in Elementor settings please.
It is more convenient to work in English, when the documentation too.

Thank you!

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
