### ISSUE TITLE
Pricing features text color

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#1806]
Hello! Now we have only icon color at pricing features. Why don't to do feature text color too?

![pricing](https://user-images.githubusercontent.com/12493645/26903196-27ca2e48-4bfe-11e7-8fa1-60b8b8298a25.png)
Thanks!

**Comment by bainternet** [comment]
You do have an option to set the color and typography of the features list, in the style tab.
![tpllnz3](https://user-images.githubusercontent.com/660572/33599634-6ebe4354-d9af-11e7-811f-095d16e5011a.png)

**Comment by parfilov** [comment]
@bainternet please look at the image again carefully. I meant that part of the text is gray, and part of it is black. Look at the picture to see what I mean.
![pricingtextcolor](https://user-images.githubusercontent.com/12493645/33602028-44c7646c-d9d8-11e7-90eb-5de942717d89.PNG)
