### ISSUE TITLE
Smooth Scroll issues - smooth scroll NOT working on anchor links

### ISSUE THREAD

**Issue by afroniquely** [pojome/elementor#1808]
Hey, I came across this previously mentioned [issue](https://github.com/pojome/elementor/issues/1333) and tried the fix suggested there, but still, it's not letting smooth scroll work on Desktop (tried in Chrome and Safari).

Whenever I add an anchor to a button/text like #services it just hard-jumps to the area instead of gracefully scrolling down to the area.

Also, any way to let elementor jump to links without adding them into the url box itself, similar to how a bak-to-top plugin would allow us to scroll back up to top but it doesn't actually add to the url of the page we're on?

Here's page for reference that has the [hard-jumps](https://jjsconsulting.tech)

**Comment by arielk** [comment]
Can you please add `define( 'SCRIPT_DEBUG', true );` to wp-config.php file so we can check it.

https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
