### ISSUE TITLE
Edit style only in GLOBAL widget

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#1810]
Hello! Globals are realy nice but I want to offer to expand their functionality.

What if we have many of the same widgets (ex. icon or image boxes) with the same style but different content. It will be very useful to drop some widgets (my example 8 image boxes), change content for each of them and then change style for all of them in one touch. 

It will give +800 points to visual editing expirience =)

Thanks!

**Comment by arielk** [comment]
I merged this issue with another issue #912 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
