### ISSUE TITLE
Order of CSS files

### ISSUE THREAD

**Issue by nicomollet** [pojome/elementor#1812]
Hello Elementor team,

I have some issues trying to style elementor pages and templates. The CSS are not loaded the same way depending on if we are in an elementor page or if you use the shortcode.

## Description

When using the shortcode `elementor-template`, the elementor CSS files are loaded in the footer.
And my main CSS file in the header, that I use for overriding some elementor styling, is overriden by the elementor styles in the footer.

## Steps to reproduce

1/ Create an elementor template.
2/ Create a page
3/ Copy the shortcode for the elementor template, and paste it in the page.
4/ Preview the page, and see the elementor .css files are loaded in the footer (just before `</body>`)

If there a technical reason for loading the CSS in the footer, is there a fix for this?

Kind regards

**Comment by anandau** [comment]
I would also like to know the reason for putting css in footer. 
I makes the layout flash on load. All widgets, elements loads with their default css  and on complete load css from postcss file is applied with a flash effect. 

Temporary workaround is to use Autoptimize which combine all css files and put them in header,

**Comment by KingYes** [comment]
We can't embed the styles in header if it's based on shortcode. But if you know what is the page ID of your template, you can use with this code:

```
add_action( 'wp_enqueue_scripts', function() {
	if ( ! class_exists( '\Elementor\Post_CSS_File' ) ) {
		return;
	}

	$header_page_id = 1996; // Or other your page ID...

	$css_file = new \Elementor\Post_CSS_File( $header_page_id );
	$css_file->enqueue();
}, 500 );
```

**Comment by nicomollet** [comment]
Hello @KingYes 
Thank you, I will use your code and try to make it global.

**Comment by nicomollet** [comment]
I created a Gist that put all Elementor CSS files in head:
https://gist.github.com/nicomollet/fc8a69b447f21cf8f4245f77d5a33d63

Since I am using Elementor to style all my footer (using a elementor_library), Elementor frontend CSS are loaded on every page.
