### ISSUE TITLE
New WP 4.8 widgets not working in Elementor

### ISSUE THREAD

**Issue by LearnWPBasics** [pojome/elementor#1814]
This post in the support forum sums it up.

https://wordpress.org/support/topic/wordpress-4-8-new-widgets-not-working/#post-9215000

I have confirmed this on a few test sites with the latest of everything. 

Cheers!
Lyle

**Comment by carasmo** [comment]
Yes, all the new 4.8 widgets not working in Elementor.

**Comment by lukecav** [comment]
You can try.
https://github.com/gitlost/ye-olde-text-widget

1.4.9 version of Elementor might have fixed those issues.

https://wordpress.org/plugins/elementor/#developers

https://wordpress.org/plugins/elementor/#developers
