### ISSUE TITLE
Remove extra margin bottom on Textarea

### ISSUE THREAD

**Issue by edirpedro** [pojome/elementor#182]
The textarea has an extra margin effect that makes the description a little far from the element. 

Correction: elementor/assets/scss/editor/_forms.scss
````
textarea {
    resize: vertical;
    vertical-align: top;
    display: block;
}
```

**Comment by arielk** [comment]
I'm not sure about the issue, can you take a screen capture please?

**Comment by edirpedro** [comment]
Before
![no-correction](https://cloud.githubusercontent.com/assets/831507/16526671/afb7e936-3f88-11e6-9980-a57da8be7ac6.png)

After
![with -correction](https://cloud.githubusercontent.com/assets/831507/16526670/afb27668-3f88-11e6-9364-6bd68fbd1677.png)
