### ISSUE TITLE
Adding Animation Delay time control 

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#1823]
Hi!
I see elementor features a fully working animation control for every element . But the problem is there isn't any time control in that! Say I want to show my first col after x time, 2nd after 2x and on .. that isn't possible with the current config of animation of elementor ; Please Do have a look at it and add this feature to the control 

Thanks !

**Comment by arielk** [comment]
It's something we're working on, please read this issue: https://github.com/pojome/elementor/issues/558
