### ISSUE TITLE
Elementor prevents plugins that insert content from working

### ISSUE THREAD

**Issue by cavalierlife** [pojome/elementor#1826]
BUG: I've noticed that in most cases, if a page or post has been edited/saved using Elementor, then plugins that dynamically inject content into the code will fail to function. For example, when using most of the social sharing icon plugins I tried, the icons would be successfully injected after the post if the post was never edited/saved via Elementor. All Elementor-based posts and pages however, would fail to have the icons injected after the content. (I did find one plugin that still worked). I could, however, force it to work by putting the plugin's shortcode directly into the template or into a theme's hook. (Of note: I tried Sassy Social Icons and AddThis, among others. One that does work is AccessPress Social Share. Why it works and the others don't, is beyond me.

At first, I thought it was just a fluke or maybe a conflict with Elementor's own social icons, but now I see it's a broader issue. I just tried two different Author Box plugins, and both have the same problem. I tried Simple Author Box and Starbox. They do not show up under content on any elementor-edited pages or posts, but they show up fine if a page or post was not edited by Elementor. Also, I can force them to show up if I use the shortcodes in php templates, or via theme's hooks (I use GeneratePress), but this method leaves out some functionality I'd get by using the plugin directly).

So Elementor is blocking or overriding this insertion functionality in some way.

My system info:
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.0.30
	PHP Version: 7.0.19
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	Site URL: https://wpdesignduo.com
	Home URL: https://wpdesignduo.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 0.1
	Author: Thomas Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 1.3.48
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

== Active Plugins ==
	Accelerated Mobile Pages
		Version: 0.9.51
		Author: Ahmed Kaludi, Mohammed Kaludi

	AMP
		Version: 0.4.2
		Author: Automattic

	Anywhere Elementor
		Version: 0.4
		Author: WebTechStreet

	AnyWhere Elementor Pro
		Version: 2.0
		Author: WebTechStreet

	Cache Enabler
		Version: 1.2.2
		Author: KeyCDN

	Code Snippets
		Version: 2.8.6
		Author: Shea Bunge

	Custom Dashboard Widget & Dashboard Contact Form
		Version: 1.1.7
		Author: Pavel Riha

	Display All Image Sizes
		Version: 1.1.6
		Author: Press Up

	Elementor
		Version: 1.4.8
		Author: Elementor.com

	Elementor Addon Elements
		Version: 0.5
		Author: Webtechstreet.com

	Elementor Contact Form DB
		Version: 1.1
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 1.5.0
		Author: Elementor.com

	GA Google Analytics
		Version: 20170324
		Author: Jeff Starr

	GP Premium
		Version: 1.3
		Author: Tom Usborne

	Lazy Load for Videos
		Version: 2.3.1
		Author: Kevin Weber

	MainWP Child
		Version: 3.4
		Author: MainWP

	MainWP Child Reports
		Version: 1.7
		Author: MainWP

	MRT4E (More Responsive Tablet 4 Elementor)
		Version: 1.0
		Author: Nicolas ANDRÉ

	Popup Maker
		Version: 1.6.3
		Author: WP Popup Maker

	Postman SMTP
		Version: 1.7.2
		Author: Jason Hendriks

	Pretty Link
		Version: 2.0.9
		Author: Blair Williams

	Simple Lightbox
		Version: 2.6.0
		Author: Archetyped

	StarBox
		Version: 3.0.6
		Author: Squirrly UK

	The SEO Framework
		Version: 2.9.2
		Author: Sybre Waaijer

	UpdraftPlus - Backup/Restore
		Version: 2.13.4.21
		Author: UpdraftPlus.Com, DavidAnderson

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WP Force SSL
		Version: 1.3
		Author: Kostas Vrouvas

	WP Universal Functions
		Version: 1.0.3
		Author: WPDevHQ

== Debug ==
	Errors: 
		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js - 2:2458
			2017-06-10 14:00 +00:00
			x 27 times

		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.5.0 - 2:2458
			2017-06-06 14:51 +00:00
			x 2 times

		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js - 2:2458
			2017-05-29 15:45 +00:00

		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.5.0 - 2:2458
			2017-05-28 16:35 +00:00
			x 13 times

		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.4.4 - 2:2458
			2017-05-21 15:53 +00:00
			x 4 times

		TypeError: Cannot read property 'cid' of undefined
			at https://www.wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.4.4 - 2:2458
			2017-05-21 15:51 +00:00
			x 48 times

**Comment by arielk** [comment]
I think that's something we've dealt with for the upcoming version of Elementor

You are welcome to try out our [new beta version](https://github.com/pojome/elementor/issues/1827) and let me know if it worked for you: https://github.com/pojome/elementor/issues/1827

**Comment by cavalierlife** [comment]
Yes, it seems to work in the beta version! Excellent!
