### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by gabrierf** [pojome/elementor#183]
Possibility of adding Header and Footer with custom Menu and Logo!

**Comment by arielk** [comment]
Basically It's a "PAGE Builder" not a "THEME" builder. What do you mean exactly?

**Comment by Nat-Faeeria** [comment]
I quite don't understand. How did you do your example pages ? Which theme did you use ? Because I'm facing the same problem as gabrierf : I want to style a static page, and I can suppress some elements (like the page title, the header or the footer)
Do you use something like a blank theme ?

**Comment by luizbills** [comment]
Just create a completely blank theme ([like this](https://livecomposerplugin.com/downloads/blank-theme/)) and use widgets like image and custom menu to build your own header and footers.

**Comment by Nat-Faeeria** [comment]
Thank you very much !

**Comment by pingram3541** [comment]
Yep, or a custom theme template can be used to exclude the header/footer but I'd prefer a theme that allows for different headers such as BeTheme which allows for creating templates and layouts specifying which header style and wp menu to use per page/post.

However, again you could create a theme page template the excludes the header/footer and use default wp widgets to create the menu inside Elementor.
