### ISSUE TITLE
Custom CSS broken in 1.5.1 - Only works for sections and page

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1830]
Only sections and page settings but no custom css for elements or columns.

I'm VERY concerned as this is the core feature as to why I bought Pro and what should I expect if I were to upgrade my sites heavily using custom css?  How do I access that data anymore, will it be wiped out?

Testing to ensure roll backs don't result in data loss of custom css...will report back.

[EDIT] I'VE CONFIRMED NO DATA LOSS, just no "edit" access to those element's custom css until  this is patched, thanks @joshmarom for quick response!

**Comment by WPDevHQ** [comment]
modules/custom-css/module.php this code from line 34:
`if ( $element instanceof Element_Section || $element instanceof Widget_Base ) {
			$required_section_id = 'section_advanced';
		} elseif ( $element instanceof Element_Column ) {
			$required_section_id = '_section_responsive';
		} else {
			$required_section_id = 'section_page_style';
		}`

Should be:
`if ( $element instanceof Element_Section || $element instanceof Widget_Base ) {
			$required_section_id = '_section_responsive';
		} elseif ( $element instanceof Element_Column ) {
			$required_section_id = 'section_responsive';
		} else {
			$required_section_id = 'section_page_style';
		}`

**Comment by WPDevHQ** [comment]
Note that `$required_section_id = 'section_advanced';` only works for the Element_Section instance and not for the Widget_Base instance

**Comment by pingram3541** [comment]
Yep, I now see custom css again.  Thanks for this snippet @WPDevHQ

**Comment by joshmarom** [comment]
Thanks for reporting.
An update will be released promptly.

**Comment by arielk** [comment]
E-Pro v1.5.2 has been already released in the last hour with the patch of this issue, please check it out.

**Comment by pingram3541** [comment]
Awesome, tested and confirmed fixed!
