### ISSUE TITLE
Feature requests: Top Left Logo + Adaptive Menu

### ISSUE THREAD

**Issue by VadymVolos** [pojome/elementor#1837]
Elementor 1.4.8  

Hi!  
Need Element: Top Left Logo with Menu (and menu adaptive for mobile)

Example:  
![logo-menu](https://user-images.githubusercontent.com/12669290/27100770-dd179ce4-5087-11e7-98a1-7532b881cf62.png)

**Comment by arielk** [comment]
I merged this issue with another issue #1406 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by VadymVolos** [comment]
NavMenu Addon For Elementor
https://wordpress.org/plugins/navmenu-addon-for-elementor/
