### ISSUE TITLE
[Idea] Dynamic dark / light UI elements for slideshows / button text / etc?

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1838]
I was fiddling around with this library the other day:
https://github.com/kennethcachia/Background-Check

As we all know, it sucks when you have a carousel full of white images, and black UI elements - but there's that change request to insert a black image in, and you have to figure out how you're going to make your UI elements stand out on it.

So I thought, how nice would it be if Elementor had an option to automatically adjust the colour of UI elements based on the brightness of the image behind them? This would be really useful for slideshow buttons, but could be extended to automatically colouring the text on regular buttons as well, keeping button designs simpler for clients to manage.

This could be activated by checkbox on the Style tab for these elements, and then having the option to set the light and dark / intermediary colours used to fill the UI elements.

Demo:
http://www.kennethcachia.com/background-check/slider.html
http://www.kennethcachia.com/background-check/flexslider.html

Edit: This library also does a third intermediary colour as well, eg grey, for those more complex images that are harder to detect. [Noice!](https://www.youtube.com/watch?v=UBX8MWYel3s)

**Comment by arielk** [comment]
Nice reference! I really liked it :)

But to be honest, it's a little complicated to put it in. I would recommend that you use a neutral color (e.g. gray with transparency) to deal with this problem.

Thank you for your feedback.

**Comment by drawcard** [comment]
Yep that's understandable. Trouble is that sometimes grey images get added as well! 😱 I may go ahead and write a 3rd party plugin for it if I get the time.
