### ISSUE TITLE
1.5RC1 and DIVI builder 3 conflict

### ISSUE THREAD

**Issue by nextend** [pojome/elementor#1839]
When Divi Builder version 1.3 enabled with Elementor 1.5RC1, Elementor throws the following warning messages:
https://jsfiddle.net/2w2wxxnz/

**Comment by KingYes** [comment]
Hey @nextend 

I installed Divi Builder 2.0.13 and it's working perfect.

Do you have any custom code there? or maybe custom setting to handle the image sizes?

**Comment by nextend** [comment]
It might be fixed in Divi 2.0.13.  It is not serious for me, I just had a test site where Divi 1.3 was installed with Elementor and Elementor do not work when Divi was active.

**Comment by nextend** [comment]
@lukecav As I told, it is a test site. I have 10 or more page builder installed on this dev site :)

If user migrates from Divi to Elementor or other way, It would be hard if she can not activate both plugin at the same time...

**Comment by lukecav** [comment]
I user would migrate from Divi to Elementor and not the other way around, since Divi is shortcode based.
