### ISSUE TITLE
1.5RC1 and relative site_url: some assets do not load

### ISSUE THREAD

**Issue by nextend** [pojome/elementor#1840]
Go to the `wp_options` table and edit the `option_value` where the `option_name = 'siteurl'`. If you have
http://elementor.com/testsite/ then modify it to /testsite/
It forces WordPress to use relative urls instead of absolute.

So after you do the change, start to edit a page with Elementor. The following JS files will not load as their url points to the wrong place:
```
http://***/roland/wordpress5/roland/wordpress5/wp-admin/js/image-edit.min.js?ver=4.8 
http://***/roland/wordpress5/roland/wordpress5/wp-admin/js/iris.min.js?ver=1.0.7
http://***/roland/wordpress5/wp-admin/js/color-picker.min.js?ver=4.8 
http://***/roland/wordpress5/roland/wordpress5/wp-admin/js/image-edit.min.js?ver=4.8 
```

**Comment by KingYes** [comment]
Hey @nextend 

It's not 1.5 issue, but it's fixed now. Thanks!
