### ISSUE TITLE
Google Maps Widget no longer works

### ISSUE THREAD

**Issue by grrog** [pojome/elementor#1842]
## Description

Google Maps widget no longer works. There is just a blank area.

Error:
Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) >> https://maps.gstatic.com/maps-api-v3/embed/js/29/5/intl/fr_ALL/init_embed.js

**Comment by kobizz** [comment]
Please provide us with your environment and system info (Can be found under Admin => Elementor => System info)

**Comment by grrog** [comment]
Hello,

It seems that it was a Google's problem, because I tested yesterday your [one-page-wedding](https://library.elementor.com/one-page-wedding/) and it did the same :
![screen capture](https://user-images.githubusercontent.com/21369582/27179626-b398e438-51cf-11e7-855d-64b8f4bb13ed.png)

Anyway, I don't know why but today it's ok.
Thank you for your impressive page builder, it's a pleasure to work with it :)
