### ISSUE TITLE
Feature Request: Embed Wistia videos

### ISSUE THREAD

**Issue by mmjaeger** [pojome/elementor#1844]
Hello
It would be helpful if e.g. Wistia videos could be embedded just like youtube, vimeo.

Thanks

**Comment by arielk** [comment]
We are using [oEmbed](https://codex.wordpress.org/Embeds) to embed the video in the page. Try to use this official plugin by Wistia: https://wordpress.org/plugins/wistia-wordpress-oembed-plugin/

**Comment by accetturo** [comment]
I agree, Wistia is used by most enterprise and professionals and not having a compatibility box is troubling at best. Any update on if we can get a compatibility patch? The oEmbed is now a default part of WordPress for Wistia and Wistia directly replied to another thread explaining how you could add compatibility to your plugin, but the question specifically is in relation to using the Elementor video widget. If Wistia's support is directly offering to help, why not take them up on it?

@ArrHarper
@arielk 

https://github.com/pojome/elementor/issues/1931

@arielk
