### ISSUE TITLE
A bug in resizing column width

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#1847]
When I have only one column in a section and try to resize the width (which does not make sense, I know) the value changes to 190 than immidiatly to 10 and remains there. The value can't be changed any more. And the column stick on 10% width. I guess you check the number of columns in that row to late.
![column size](https://user-images.githubusercontent.com/14095280/27200358-b93df370-5219-11e7-8e57-ff125cf74bff.JPG)

I also don't understand the meaning of "widget space".

**Comment by arielk** [comment]
Please update to RC2 and let me know if it solve the problem https://github.com/pojome/elementor/issues/1827#issuecomment-309757319
