### ISSUE TITLE
Child column stretches background

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#1849]
Seems the child column stretches the own background, when the parent column is set to "stretch section" and "full width".

Thats a little awkward, because i can't build section backgrounds in stretch sections. The only way is to give every column a background - which is also very time consuming.

http://luxam.at/downloads/ScreenshotCol.png

Tanks, Steven

**Comment by arielk** [comment]
@Luxamman 

Can you share with us a link to this page or steps to reproduce this situation?

**Comment by Luxamman** [comment]
Try this - its a stretcht section on a Elementor Canvas, inside is a 500px section, boxed.

http://stefaneduardkrenn.com/elementor-test/

**Comment by arielk** [comment]
The background of the section always appears from side to side, if you want to give a different background only to the content, you can set the background of the column instead.

**Comment by joshmarom** [comment]
Hi @Luxamman

It seems like you might have a slight misunderstanding of the meaning of the "content width" setting.

Content width controls the width of an **inner container** inside the section, that holds the columns in it. Restricting content width **will not** affect the section width, and therefore the section background.

So if you would like to have an inner section with a background and you want to keep it at a restricted width, you should do as follows:
1. Create a (parent) section and set its content width to the desired width
2. Insert an inner section (columns widget) into the parent section
3. Apply a background to the inner section

The inner sections' width will be restricted to the parent sections' content-width.

I hope that clarifies things for you.
