### ISSUE TITLE
Feature Request: Side-by-Side Slider Widget

### ISSUE THREAD

**Issue by nickkask** [pojome/elementor#1850]
Using the Slider Pro Widget, I'd like to see a way to make a "side by side" slider with an image on one side and text/buttons on the other side. See attachment for a mock-up/example.

![sidebyside-request](https://user-images.githubusercontent.com/25444915/27227586-0f41299c-5272-11e7-8f3f-4ed4798e6cbc.png)

**Comment by arielk** [comment]
You can do it by Slides widget in Elementor Pro, you can learn more about this here: https://docs.elementor.com/article/93-slides

**Comment by nickkask** [comment]
I watched that video before I posted and it shows nothing like what I'm seeking, and I posted to the Elementor Support and they said it didn't exist and to add it as a feature request. Can you maybe quickly explain how I can get the above screenshot example using the Slider Widget as is? I've found no way to make an image side-by-side with the text.

Thanks!

**Comment by gfdesign** [comment]
This is a bit matted and I've not tried but, try to create the slides with templates. I mean, create every slide as template and insert its shortcode into each slide content and we'll see what happen.
