### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by mmjaeger** [pojome/elementor#1852]
does anybody know where this error is coming from:

TypeError: undefined is not an object (evaluating 'elementorFrontend.hooks.addAction')
(anonymous function) — frontend.min.js:1
Global Code — frontend.min.js:1:370
Selected Element

**Comment by KingYes** [comment]
Please deactivate all your plugins and change to default theme, and try again. If not working again, please enable `SCRIPT_DEBUG` ( Like this: `define( 'SCRIPT_DEBUG', true );` ), and post again the console error (and what you doing before you get this error).

**Comment by anandau** [comment]
I can also confirm this. 
Even mine and few other third party elementor addons are facing this issue. 

This is happening with code implementing Js Hooks.

Is there any change in js hooks api ?

**Comment by mmjaeger** [comment]
@KingYes 
if enabling debugging - it leads to the following errors - please see attachment
<img width="1431" alt="screen shot 2017-06-20 at 12 51 45 pm" src="https://user-images.githubusercontent.com/1554580/27352985-671335c8-55b7-11e7-8878-4178303109e3.png">

**Comment by KingYes** [comment]
@mmjaeger Which widget you use in this page? And are you deactivate all your plugins and move to default theme?

**Comment by mmjaeger** [comment]
@KingYes 
Hello
I disabled an Elementor plugin for devices and the error is gone.
thanks

**Comment by KingYes** [comment]
So please contact with developer of this plugin to resolve the problem..

**Comment by tudormnt** [comment]
@mmjaeger Please update to 1.0.1 to fix this. Thanks!
