### ISSUE TITLE
popups please...

### ISSUE THREAD

**Issue by kadso** [pojome/elementor#1856]
» I'm attempting to implement bigfoot.js footnotes on a new site. I'm running into problems getting this popup styled footnote to present on time of everything else. Specifically when the popup displays over the next section that follows while scrolling down, the contents of the popup and the next section bleed into each other.

 » having the ability to design BOTH the button AND the popup content environment with elementor is the request. In our view, elementor is a fundamentally new presentation tool*. Similar to pen and paper, the printing press, typewriter, electronic word processor, it is our view what is happening now as websites move from the early versions to the anticipated 'regrouping' version, presents humans with yet another chance to improve our communication skills—a necessary precondition to improving our physical world.

*Unlike other presentation environments (writing, audio, video) a website offers the opportunity to present to the user in multi-level, multi-dimensional ways that are designed to be consumed the way the human brain works.

**Comment by lukecav** [comment]
Have you looked at.
https://wordpress.org/plugins/modal-for-elementor/

**Comment by kadso** [comment]
no. it totally slipped my radar. I'll check it out. thank you lukecav!

**Comment by arielk** [comment]
You can also try this plugin: https://wordpress.org/plugins/popup-maker/

**Comment by kadso** [comment]
Thanks Ariel  » One thing to keep in mind is that popup-maker does not (at least from what I can tell) provide a way to create an inline icon or ‘button’ that is also automatically implemented through mark-down.

By using bigfoot.js, not only can I make “popups” by way of a “footnote” on static pages (where the z-index is working to convention), I can us it for when I’m writing a blog and what a “popup/footnote” in the blog itself. It’s a great way to provide additional context/details to the readers who want more, without encumbering the other readers.

And that’s what it is all about right? The customer experience? By being able to use the bigfoot.js footnote throughout my entire site, I’ll be able to provide a more consistent customer experience.

I hope elementor keeps the above interactions in mind as you consider your versions of ‘inline footnotes/popups” 

Thanks for the help.

Best ~ 

Russ Curry
Lead Designer
Agnetic, LLC
317.696.2824
Optimizing human ∞ machine learning, starting with the food ∞ healthcare spectrum

**Comment by arielk** [comment]
Ref: #628
