### ISSUE TITLE
Feature request: Only display visible elements in each device view

### ISSUE THREAD

**Issue by lozmatic** [pojome/elementor#1861]
I have two sections for logos on my site, one for desktop / tablet and the other for mobile.

When I preview and edit in mobile, I don't want to be able to see the logo for the desktop / tablet version.

And vice-versa.

This could be a 'only display elements visible for his view' option for each view.

Thanks,

Lawrence

**Comment by arielk** [comment]
@lozmatic 

You need to click on the Preview button and then you can see the element per device.
![image](http://i.imgur.com/NeE9Ze1.png)


Thanks
