### ISSUE TITLE
import export list items

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1862]
Would be nice to have a bulk import (html feed)/ export of list items in icon list, price box etc.

If you try to redesign a website with different custom price boxes with lots of bullet points, it's tedious to add them one by one.

**Comment by arielk** [comment]
You can save the section to the library and then export/import to another site or page.

Please read more here:
https://elementor.com/introducing-template-library/
https://docs.elementor.com/article/60-library

**Comment by dudaster** [comment]
At least import from a text, cvs or something. I want to port non elementor websites to elementor. It's useless what you suggested for that.

**Comment by arielk** [comment]
Sorry, but it is not possible for now.

Thank you for your feedback!

**Comment by teolaz** [comment]
@arielk @dudaster please check my PR here #1884

**Comment by brian2199** [comment]
Hi @dudaster & @arielk,

I'm new to GitHub apologize if this is not allowed but I was wondering about the same functionality. Was this ever added? 

I tried doing a ton of searches but I haven't found an official or 3rd party solution.

This feature would be awesome. 

Thank you,
Brian

**Comment by dudaster** [comment]
Sorry, I don't think so.

**Comment by noxludo** [comment]
Why this issue is closed ? It's a very good idea for a new feature. It will be a nice improvement. "It's not possible" is not an answer. Ok it's not possible. But it could be, so let the issue open for a next release ! You don't think so ?
