### ISSUE TITLE
columns in columns in columns

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1865]
Now you can create a section with columns and you can add other columns in that [[][]]. But if you want to add other columns in columns you can't[[[][]][]]. So basically if you want to add more the 2 level depth of columns is not working. the workaround is to create a template and add it but it can get tedious.

**Comment by arielk** [comment]
Unfortunately this is not possible for now. Perhaps in the future we will add this possibility.

Thanks for your feedback!
