### ISSUE TITLE
How to Use Elementor Elements in Programmatically Created Posts?

### ISSUE THREAD

**Issue by seees** [pojome/elementor#1866]
Hi,

I am creating Wordpress posts programmatically via php and wp_insert_post().
Is there any way to use Elementor elements in these automatically created posts?

Thanks in advance!

Cheers,
Chris

**Comment by joshmarom** [comment]
Can you explain what you mean by "using Elementor elements" in these posts?

**Comment by seees** [comment]
"General Elements" for example.
Elements like Image Box, Icon Box, Image Gallery, Icon List etc.

**Comment by joshmarom** [comment]
I am still not sure I understand what you mean by "using" elements.
Do you want to programmatically create Elementor content for these posts?
If that's the case, currently the only way I can think of is to construct a JSON object according to Elementors' data structure and saving it under the `_elementor_data` meta key for that post.

In the future, there is probably going to be an API to facilitate such requirements.

**Comment by seees** [comment]
Exactly! Is there any tutorial how to do this? Where can I find some information about the json object's structure?

**Comment by joshmarom** [comment]
Unfortunately, there is no tutorial or guide for that.
You can inspect the data that gets saved to the DB and try to figure it out yourself...

**Comment by seees** [comment]
Ok, thank you very much!
