### ISSUE TITLE
Date type field in Form widget

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1868]
Would be nice to have a date type in the form widget

**Comment by parfilov** [comment]
Yes! I need too. And my subscribers asks about it.

**Comment by odivius** [comment]
I was just looking for this too. It would be nice for booking requests.

**Comment by keithrust** [comment]
I agree.  I'm required to capture a user's birthdate and need a date field, vs. a bunch of select fields.

**Comment by nicomollet** [comment]
I need this too.

**Comment by Spencemeister** [comment]
Chalk me up as one more.  I was hoping to be able to use the Elementor Forms widget exclusively, but its just not there yet.  No date widget. No ability to review submissions in a table format or export submissions. I'd gotten around the database issues with a 3rd party DB plugin and All Export plugin, but the lack of a date plugin is a deal breaker.  I guess I have to go back to Gravity Forms.

**Comment by bainternet** [comment]
Done in v1.13.0

**Comment by roseaubenjamin** [comment]
Hello everyone !
The date field is good in the forms but do you have a solution to translate the appearance of the calendar? I am French and this one appears in English ...
Tank's
