### ISSUE TITLE
portfolio widget not showing all the filterable items

### ISSUE THREAD

**Issue by armada** [pojome/elementor#1869]
I'm using the portfolio widget with the source being my blog posts. I have 7 items in a category but the filter is showing only 4.

See attached images:

![categories](https://user-images.githubusercontent.com/17282554/27329332-d1f23f30-55e7-11e7-8199-ff4278ab5cd3.png)

![filtered](https://user-images.githubusercontent.com/17282554/27329298-bc237b92-55e7-11e7-8be9-523d66e841e5.png)

**Comment by joshmarom** [comment]
Maby you didn't set a large enough number on the **Posts Per Page** setting, so not all the posts are loaded.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
