### ISSUE TITLE
Multiple attr for Control_Select2 option control

### ISSUE THREAD

**Issue by shinTM** [pojome/elementor#1872]
Hi
I would like to use Select2 control multiple mode.
I'm sorry but I can not understand how I can overwrite the default multiple value https://github.com/pojome/elementor/blob/master/includes/controls/select2.php#L26
After merging https://github.com/pojome/elementor/blob/master/includes/controls/base.php#L45
my setting 'multiple'=> true will be overwritten

**Comment by kobizz** [comment]
When you add a new Select2 control to your element, just specify `'multiple' => true` in the args list.

For example:
```php
$this->add_control(
  'my_control',
  [
     'label' => __( 'My Control', 'my-plugin' ),
     'type' => Controls_Manager::SELECT2,
     'options' => [
     	'a' => __( 'Option A', 'my-plugin' ),
     	'b' => __( 'Option B', 'my-plugin' ),
     ],
     'multiple' => true,
  ]
);
```

**Comment by shinTM** [comment]
Thank you kobizz
