### ISSUE TITLE
Elementor 1.5beta - Slider breaks layout

### ISSUE THREAD

**Issue by mmjaeger** [pojome/elementor#1876]
Hello
When placing a slider it breaks the layout and leads to a horizontal scrollbar - anybody else experiencing this - is there a fix I'm not aware of?

thanks

**Comment by arielk** [comment]
Which slider widget do you use exactly: Image Carousel, Slides or 3rd party plugin?

**Comment by mmjaeger** [comment]
@arielk 
I'm talking about the image carousel in Elementor Pro 1.5.3

**Comment by arielk** [comment]
Can you please share with us a link to the page with the problem?

**Comment by mmjaeger** [comment]
@arielk - unfortunately it's on localhost - however as my client is awaiting a showing of the site I'm really looking forward to a fix soon.

**Comment by joshmarom** [comment]
> hope you'll have a solution soon as I need to present the progress to my client

It is not recommended to use beta versions on production sites
