### ISSUE TITLE
Place a column which will be dragged out of the background image of the section

### ISSUE THREAD

**Issue by orenatan** [pojome/elementor#1877]
How can I place a column which the bottom part of the column will be dragged down out of the background image of the section? 
See please attached file for an exemple what I mean.
![eitanmiller_v1](https://user-images.githubusercontent.com/29592545/27370884-b0c3fae8-565e-11e7-8791-3bbceaab8ad1.jpg)

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
