### ISSUE TITLE
Feature Request: Avoid repeating posts when using more than one post widget in Pro version

### ISSUE THREAD

**Issue by formulaclick** [pojome/elementor#1878]
If you want to create a magazine layout where post widgets are placed as blocks (one for featured category, another for sports category, another for travel category...) and some posts are located in more than one category (very common) this post **will be displayed in more than one widget** so it will be **repeated**. It would be great an option on post widget to **avoid duplicating posts** automatically, so if in a widget are displayed last 5 posts of a category, but one of the posts already was displayed in other post widget, the 6th post will be displayed instead. This is an existing feature in many magazine themes.

**Comment by joshmarom** [comment]
> This is an existing feature in many magazine themes.

Which themes?

**Comment by formulaclick** [comment]
For example, TagDiv's Newspaper theme:
http://forum.tagdiv.com/unique-articles/

**Comment by joshmarom** [comment]
Any more examples?

**Comment by formulaclick** [comment]
@joshmarom Also Publisher theme does it
http://docs.betterstudio.com/publisher/#theme-duplicate-posts
I've seen and used this 2 themes, but I guess this feature is implemented in more magazine oriented themes

**Comment by joshmarom** [comment]
Okay, we will look into it and see what can be done.

**Comment by NAROLLES** [comment]
I arrive here after #4312 
if you want one theme ....Extra Elegant Theme
Thanks

**Comment by formulaclick** [comment]
No updates about this @arielk? :-(

**Comment by bainternet** [comment]
Available in Elementor pro 2.1 ( currently beta 4 #4923 )

thanks.

**Comment by formulaclick** [comment]
Great news!!!
