### ISSUE TITLE
Animation starts after page has already loaded.

### ISSUE THREAD

**Issue by Cyberdemon87** [pojome/elementor#1879]
Hello.

I'm trying to use an entrance animation for the first thing the visitor sees when he visits the site.
However the animation starts after the page has loaded making it useless, so the result is a static page that just starts animating after a while.

Can you please look into it?
Thank you.

**Comment by arielk** [comment]
We did some changes about the entrance animation in v1.5 of Elementor, please try the [beta version here](https://github.com/pojome/elementor/issues/1827) and let me know if that resolved the problem.

**Comment by Cyberdemon87** [comment]
Thanks, I will.

Or should I wait for the stable version? Does it have a release date?

**Comment by arielk** [comment]
Hopefully tomorrow!

**Comment by Cyberdemon87** [comment]
That's great, I'll wait then :)

**Comment by arielk** [comment]
v1.5.1 released.
