### ISSUE TITLE
Posts: Author/Comments not clickable.

### ISSUE THREAD

**Issue by Cyberdemon87** [pojome/elementor#1880]
Hello.

Can you please make the author and comments clickable in the Posts element?

Additional styles for "Read More" link would be great too.

Thank you.

**Comment by arielk** [comment]
Author and comments clickable like the title or link to author archive and comments part inside the post?

**Comment by Cyberdemon87** [comment]
The second. 

I'm talking about the Meta Data to link to Author, comments, etc when clicked, as you said.

**Comment by arielk** [comment]
I merged this issue with another issue #1071 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
