### ISSUE TITLE
Custom Elementor widget with custom control bug

### ISSUE THREAD

**Issue by nextend** [pojome/elementor#1882]
I have a custom Elementor widget which also registers a custom Field into Elementor. It turned out it is very easy to run into an unexpected error, which could be easily fixed on your side. You can produce an error when editing in and an ajax call made for this custom widget with the `action:elementor_render_widget` parameter. It will throw an error for an inbuilt Elementor field which used in the control section.

The problem lies in the `_register_controls()` call. As I see `Controls_Manager::register_control`s not called yet in this phase. It seems like `Widget_Base::start_controls_section` initialize the default Elementor control fields. So If I register mine control before start_controls_section call with  `\Elementor\Plugin::instance()->controls_manager->register_control('smartsliderfield', new Control_SmartSliderField());`, I populate Controls_Manager::_controls so the default controls won't load because:
```
	public function get_controls() {
		if ( null === $this->_controls ) {
			$this->register_controls();
		}

		return $this->_controls;
	}
```
Possible solutions:
1: Reorder code and register my control after the start_controls_section:
```
        $this->start_controls_section('section_my_custom', [
            'label' => esc_html('Smart Slider'),
        ]);

        \Elementor\Plugin::instance()->controls_manager->get_controls();
        NextendRegisterControlSmartSliderField();
        \Elementor\Plugin::instance()->controls_manager->register_control('smartsliderfield', new Control_SmartSliderField());
```
2: get_controls() before adding my custom control
```
        \Elementor\Plugin::instance()->controls_manager->get_controls();
        NextendRegisterControlSmartSliderField();
        \Elementor\Plugin::instance()->controls_manager->register_control('smartsliderfield', new Control_SmartSliderField());
        
        $this->start_controls_section('section_my_custom', [
            'label' => esc_html('Smart Slider'),
        ]);
```
**3. The best would be if you load the in-built controls before calling the _register_controls() on the widget**

       
Original code which can produce error:
```
add_action('elementor/widgets/widgets_registered', function () {
    $widget_manager = \Elementor\Plugin::$instance->widgets_manager;
    $widget_manager->register_widget_type(new \Elementor\Nextend_Widget_SmartSlider());
}, 100);

class Nextend_Widget_SmartSlider extends \Elementor\Widget_Base {
.....
protected function _register_controls() {
        NextendRegisterControlSmartSliderField();
        \Elementor\Plugin::instance()->controls_manager->register_control('smartsliderfield', new Control_SmartSliderField());
        $this->start_controls_section('section_my_custom', [
            'label' => esc_html('Smart Slider'),
        ]);
        $this->add_control('smartsliderid', [
            'label'   => 'Slider ID',
            'type'    => 'smartsliderfield',
            'default' => '',
            'title'   => __('Enter some text', 'elementor-custom-element'),
        ]);

        $this->end_controls_section();
}
.....
}


function NextendRegisterControlSmartSliderField() {
    static $registered;
    if (!$registered) {
        if (class_exists('\Elementor\Base_Data_Control')) {

            class_alias('\Elementor\Base_Data_Control', '\Elementor\NextendElementorFieldAbstract');
        } else {

            class_alias('\Elementor\Control_Base', '\Elementor\NextendElementorFieldAbstract');
        }

        class_exists('\Elementor\Group_Control_Background');

        class Control_SmartSliderField extends \Elementor\NextendElementorFieldAbstract {

            public function get_type() {
                return 'smartsliderfield';
            }

            public function content_template() {
                ?>
                <div class="elementor-control-field">
			<label class="elementor-control-title">{{{ data.label }}}</label>
			<div class="elementor-control-input-wrapper">
                <a style="margin-bottom:10px;" href="#" onclick="return NextendSmartSliderSelectModal(jQuery(this).siblings('input'));" class="button button-primary elementor-button elementor-button-smartslider" title="Select slider">Select slider</a>
				<input type="{{ data.input_type }}" title="{{ data.title }}" data-setting="{{ data.name }}""/>
			</div>
		</div>
                <# if ( data.description ) { #>
		<div class="elementor-control-field-description">{{{ data.description }}}</div>
		<# } #>
                <?php
            }

            public function get_default_settings() {
                return [
                    'input_type' => 'text',
                ];
            }
        }

        $registered = true;
    }
}
```

**Comment by KingYes** [comment]
Why you don't register your custom control by this action: `elementor/controls/controls_registered` ?

**Comment by nextend** [comment]
Because it is ambigous that the widget which extends `\Elementor\Widget_Base` has the method: `protected function _register_controls() {` so I would assume that this is the right place to register my custom control through `\Elementor\Plugin::instance()->controls_manager->register_control('...', ...);`, but as you noted, this is not the right place.

Is it safe to use the first parameter of the elementor/controls/controls_registered?
 Does it work with older versions of Elementor? As I saw the first parameter is not used in Elementor pro v1.5.0, so I'm not sure if it is safe to use :)

add_action('elementor/controls/controls_registered', function ($controls_manager) {....});

**Comment by KingYes** [comment]
You can but not really need this. It's just for shortcut..
