### ISSUE TITLE
Form Mailchimp Field Mapping Showing only 11 fields

### ISSUE THREAD

**Issue by kaelmawn** [pojome/elementor#1888]
Even if I have 13 fields on my MailChimp list, only 11 of them are showing in the Field Mapping.

![image](https://user-images.githubusercontent.com/5869873/27459903-a3a58f72-577e-11e7-86b2-b2863d0cd0e5.png)

**Comment by arielk** [comment]
v1.5.5 released with a patch for this issue.
@kaelmawn thanks for your report!
