### ISSUE TITLE
javascript errors - latest version of Elementor and Elementor Pro

### ISSUE THREAD

**Issue by mmjaeger** [pojome/elementor#1890]
I'm running Elementor RC 1.5 and Pro 1.5.4 and I'm running not some javascript errors:

http://localhost/cms/wp-thx/wp-content/plugins/elementor/assets/lib/backbone/backbone.radio.min.js.mapFailed to load resource: the server responded with a status of 404 (Not Found)

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (backbone.marionette.min.js.map, line 0)

Do you guys have any idea what's causing those and how to get rid of it?

<img width="1263" alt="screen shot 2017-06-24 at 5 53 30 pm" src="https://user-images.githubusercontent.com/1554580/27512889-1e2b6ae0-5906-11e7-8d41-5c6a0ae3b6e5.png">

**Comment by KingYes** [comment]
It's Okay. We just exclude the `*.map` files from the production version.
