### ISSUE TITLE
How to globally remove controls

### ISSUE THREAD

**Issue by ffoodd** [pojome/elementor#1896]
Hi there,

I’m searching for a way to disable some controls globally, such as the font family control or the color control.

I did find this [`remove_control()`](https://github.com/pojome/elementor/blob/04db53ef2502e1696b18dca9be07e57b11b4f13c/includes/base/controls-stack.php#L105) function but as far as I understand this, it needs to be done for **every single widget**.

I read a lot of issues and support topics, without any luck.

Is this possible, and how?

Thanks a lot and keep going, your plugin is great 🙂

**Comment by KingYes** [comment]
If you want to remove control from `common` (shared for all widgets) so just remove from there. But for every single widget has unique controls, so you can't use with this method globally..

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by ffoodd** [comment]
Hi there,
I found what I wanted to do.

This action can be used to unregister a plugin:
```php
add_action(
    'elementor/widgets/widgets_registered',
    function($widgetManager) {
        $widgetManager->unregister_widget_type('sidebar');
    }, 10,  3
);
```

This action can be used to remove control or add control in a widget:
```php
add_action(
    'elementor/element/before_section_end',
    function($section, $section_id, $args) {
        if( $section->get_name() == 'text-editor' && $section_id == 'section_style' ) 
        {
            $section->remove_control('typography_typography');
        }
    }, 10, 3
);
```

This is what I searched. So to me this issue is closed: thanks for helping :)

**Comment by andreas83** [comment]
is there any convenient way to list all section names and corresponding controls?
