### ISSUE TITLE
Feature Request: Mute toggle on video widget

### ISSUE THREAD

**Issue by webdevelgin** [pojome/elementor#1897]
The option to toggle if the video widget can be muted when auto-play is selected would be very useful. If users would like to hear audio they simply need to click the video player.

**Comment by arielk** [comment]
Do you have any example for this?

**Comment by arielk** [comment]
Thanks for the reference, so if I understand you correctly, you want us to add a Mute option when embedding the video, right?

**Comment by carasmo** [comment]
Neither YouTube or Vimeo (of the many video sources) provide a parameter for muting video. You have to use their API.

**Comment by arielk** [comment]
Merged #2077 

Thanks for your feedback!
