### ISSUE TITLE
Show/hide content to logged-in/logged-out

### ISSUE THREAD

**Issue by Cyberdemon87** [pojome/elementor#1899]
Hello.

Please consider adding this functionality to Elementor.
I tried this plugin but it has bugs and does not perform well:

https://wordpress.org/plugins/woorocks-magic-content/

This feature would grant another step forward to Elementor.

**Comment by arielk** [comment]
I merged this issue with another issue #1592 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by Spencemeister** [comment]
Add another individual to the request list

**Comment by Cyberdemon87** [comment]
Hopefully this may come in the upcoming v. 2.0.?

**Comment by evanomondi** [comment]
Hoping for the same!

**Comment by MDCR55** [comment]
Is there any updates on this feature ?

**Comment by amit1sharma** [comment]
any update?
