### ISSUE TITLE
Use Background Fallback while video is loading

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1901]
When you choose a video background to a section,no one wants to see the loading screen of a video, the background turns black and ugly.
Use Background Fallback until the video loads and starts, this is far more elegant solution and you can play with more creatively. 

It  was also brought up here: #793 #41 #1644. 
An working example of what it should look like https://revolution.themepunch.com/wordpress-youtube-header/

**Comment by pasog** [comment]
it would be very useful..

**Comment by askwpgirl** [comment]
This should be re-opened as issue has not been solved.
