### ISSUE TITLE
Feature Request - WordPress run action for forms

### ISSUE THREAD

**Issue by nullmem** [pojome/elementor#1902]
Other advanced form plugins such as Caldera provide the ability to hook a WordPress action/filter as an option to submit data for more advanced setups. I love the design capabilities of the forms feature in PRO, but the options for what to do with the data are very limited. Adding a WordPress hook option would make us developers who use Elementor very happy.

**Comment by matipojo** [comment]
Hi, @nullmem, 
You can use our Forms API:
https://github.com/pojome/elementor/blob/master/docs/content/pro/forms.md
