### ISSUE TITLE
Ver. 1.5 editor controls are weird

### ISSUE THREAD

**Issue by cavalierlife** [pojome/elementor#1904]
## Description

The editing controls look weird, as shown below.
![weirdicons](https://user-images.githubusercontent.com/28687464/27641468-83b284e2-5be1-11e7-805a-8e111b1766a7.PNG)

## Steps to reproduce

1. Upgrade to Elementor 1.5. 
2. Cry.

Seriously, though, I tried with all plugins disabled, and with all additional CSS removed. Didn't help. Tried it on a clean install and it works fine, so it's something to do with my site setup.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.0.30
	PHP Version: 7.0.20
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	Site URL: https://wpdesignduo.com
	Home URL: https://wpdesignduo.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 0.1
	Author: Thomas Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 1.3.48
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

== Active Plugins ==
	Accelerated Mobile Pages
		Version: 0.9.53
		Author: Ahmed Kaludi, Mohammed Kaludi

	Akismet Anti-Spam
		Version: 3.3.2
		Author: Automattic

	AMP
		Version: 0.4.2
		Author: Automattic

	Anywhere Elementor
		Version: 0.5
		Author: WebTechStreet

	AnyWhere Elementor Pro
		Version: 2.0
		Author: WebTechStreet

	Cache Enabler
		Version: 1.2.2
		Author: KeyCDN

	Code Snippets
		Version: 2.8.6
		Author: Shea Bunge

	Compress JPEG & PNG images
		Version: 2.2.3
		Author: TinyPNG

	Custom Dashboard Widget & Dashboard Contact Form
		Version: 1.1.9
		Author: Pavel Riha

	Display All Image Sizes
		Version: 1.1.6
		Author: Press Up

	Duplicate Page
		Version: 2.3
		Author: mndpsingh287

	Elementor
		Version: 1.4.10
		Author: Elementor.com

	Elementor Addon Elements
		Version: 0.5
		Author: Webtechstreet.com

	Elementor Contact Form DB
		Version: 1.1
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 1.5.3
		Author: Elementor.com

	GA Google Analytics
		Version: 20170324
		Author: Jeff Starr

	GP Premium
		Version: 1.3.1
		Author: Tom Usborne

	MainWP Child
		Version: 3.4.1
		Author: MainWP

	MainWP Child Reports
		Version: 1.7
		Author: MainWP

	MRT4E (More Responsive Tablet 4 Elementor)
		Version: 1.0
		Author: Nicolas ANDRÉ

	Popup Maker
		Version: 1.6.3
		Author: WP Popup Maker

	Postman SMTP
		Version: 1.7.2
		Author: Jason Hendriks

	Pretty Link
		Version: 2.1.1
		Author: Blair Williams

	Redirection
		Version: 2.6.2
		Author: John Godley

	Simple Lightbox
		Version: 2.6.0
		Author: Archetyped

	SyntaxHighlighter Evolved
		Version: 3.2.1
		Author: Alex Mills (Viper007Bond)

	The SEO Framework
		Version: 2.9.2
		Author: Sybre Waaijer

	UpdraftPlus - Backup/Restore
		Version: 2.13.4.21
		Author: UpdraftPlus.Com, DavidAnderson

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WP Force SSL
		Version: 1.3
		Author: Kostas Vrouvas

	WP Staging
		Version: 1.1.6
		Author: WP-Staging, René Hermenau

	WP Universal Functions
		Version: 1.0.3
		Author: WPDevHQ

	YouTube Pro
		Version: 11.8.1
		Author: EmbedPlus Team

== Debug ==
	Errors: 
		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js - 2:2458
			2017-06-28 13:51 +00:00
			x 33 times

		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.5.0 - 2:2458
			2017-06-06 14:51 +00:00
			x 2 times

		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js - 2:2458
			2017-05-29 15:45 +00:00

		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.5.0 - 2:2458
			2017-05-28 16:35 +00:00
			x 13 times

		TypeError: Cannot read property 'cid' of undefined
			at https://wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.4.4 - 2:2458
			2017-05-21 15:53 +00:00
			x 4 times

		TypeError: Cannot read property 'cid' of undefined
			at https://www.wpdesignduo.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.4.4 - 2:2458
			2017-05-21 15:51 +00:00
			x 48 times

**Comment by kobizz** [comment]
Please hard-empty your browser cache and try again.

**Comment by cavalierlife** [comment]
You KNOW I'd already done that and it didn't work, so I almost didn't try it again, but darned if it didn't work this time around. DOH. Ok, my bad. Clearing cache again worked. All good. Thank you.
