### ISSUE TITLE
BUG: Elementor v1.5.0 - Widget Save Only Visible if Elementor Pro is active!

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#1908]
Hello team,

I'm missing the widget save icon on all Elementor and Custom widgets - the icon is only available if Elementor Pro is active.

See images:

![elementorwidget](https://user-images.githubusercontent.com/16872407/27667546-5380f514-5c73-11e7-87ff-bc43b1546563.png)
![nosaveicon](https://user-images.githubusercontent.com/16872407/27667548-57f1e022-5c73-11e7-936d-99803c998dae.png)

**Comment by LearnWPBasics** [comment]
Zulfikar - 

Pretty sure that saving a widget is a Pro feature only :)

Cheers!
Lyle

**Comment by arielk** [comment]
As Lyle wrote above, Global widget is a pro version only

**Comment by WPDevHQ** [comment]
So it is :) 

Goes to show what happens when you are given awesome premium tools and take them for granted :D
