### ISSUE TITLE
Custom Widget Not Showing Up

### ISSUE THREAD

**Issue by BetaStacks** [pojome/elementor#1909]
I am working on building some custom widgets. I created one using the Hello World example that I found on here. However, after placing the widget in the Widgets folder I do hot see a new widget option in the editor. Is there a document that has more information of what I need to do in order to install and use my custom widgets?

**Comment by arielk** [comment]
Can you share with us the code that you wrote?

**Comment by BetaStacks** [comment]
Certainly, I used the code I found here: https://github.com/pojome/elementor-hello-world/blob/master/plugin.php#L35-L49

`<?php
namespace HelloWorld;
use HelloWorld\Widgets\Hello_World;
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly
/**
 * Main Plugin Class
 *
 * Register new elementor widget.
 *
 * @since 1.0.0
 */
class Plugin {
	/**
	 * Constructor
	 *
	 * @since 1.0.0
	 *
	 * @access public
	 */
	public function __construct() {
		$this->add_actions();
	}
	/**
	 * Add Actions
	 *
	 * @since 1.0.0
	 *
	 * @access private
	 */
	private function add_actions() {
		add_action( 'elementor/widgets/widgets_registered', [ $this, 'on_widgets_registered' ] );
		add_action( 'elementor/frontend/after_register_scripts', function() {
			wp_register_script( 'hello-world', plugins_url( '/assets/js/hello-world.js', ELEMENTOR_HELLO_WORLD__FILE__ ), [ 'jquery' ], false, true );
		} );
	}
	/**
	 * On Widgets Registered
	 *
	 * @since 1.0.0
	 *
	 * @access public
	 */
	public function on_widgets_registered() {
		$this->includes();
		$this->register_widget();
	}
	/**
	 * Includes
	 *
	 * @since 1.0.0
	 *
	 * @access private
	 */
	private function includes() {
		require __DIR__ . '/widgets/hello-world.php';
	}
	/**
	 * Register Widget
	 *
	 * @since 1.0.0
	 *
	 * @access private
	 */
	private function register_widget() {
		\Elementor\Plugin::instance()->widgets_manager->register_widget_type( new Hello_World() );
	}
}
new Plugin();`

**Comment by KingYes** [comment]
@BetaStacks Please share all your folder of your project..

**Comment by BetaStacks** [comment]
[elementor.zip](https://github.com/pojome/elementor/files/1112258/elementor.zip)
Here is the elementor file. Under widgets I added the hello-world widget and one called total-admin-text

**Comment by KingYes** [comment]
No no no no! NO!!.... You don't merge this code with Elementor core..

You need to create new custom WordPress plugin and write your widget there!

**Comment by BetaStacks** [comment]
Doh! That would explain a lot. 
I'll give that a go. 
I've been developing for a completely different IDE for years. This is my first go at a WP pluggin. 

Thanks for the help!

**Comment by molikh** [comment]
I got same problem, I created new custom plugin and new custom widget in it.
I want to use my widget 3 times in a page. 
In elementor I can see 3 instance of my widget but in preview only one of them shows up.
