### ISSUE TITLE
BUG: Rollback feature in 1.5 removes Elementor from all pages

### ISSUE THREAD

**Issue by LearnWPBasics** [pojome/elementor#1911]
I tried the Rollback feature in 1.5 on a live and a local site. In both cases, when the Rollback to 1.4.10 was complete, Elementor had been removed from all pages. My Library items were still there and as I had no posts created using Elementor I can't vouch for that.

Updating to 1.5 did however restore Elementor to all the pages. 

The local site was a test site so no big issue, but the live one was a live one and good thing I had made and verified a backup first. 

Also of note is that the local site where this happened had Elementor as the only plugin. No caching or anything of that nature. On the live site, all caches were cleared numerous times.

**Comment by LearnWPBasics** [comment]
UPDATE:

Tried rolling back on another local site and it was "hit and miss" - some pages were fine, others were not. One that was not was using a Slider from E-Pro; just the text from the slides remained.

So I set up a hosted dev site and everything works fine and as expected. 

All sites are on PHP 7.1.4. 

Not sure what to say other than always backup and verify before proceeding :)

**Comment by KingYes** [comment]
Thanks!
