### ISSUE TITLE
Latin-ext subset for google fonts for Romanian

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1915]
As stated here #1630 we need to have a latin-ext subset for romanian language also.
'ro_RO' => 'latin-ext',

I added myself the code in the subsets in print_google_fonts() function in includes/frontend.php and it worked. can you please add it in future updates?

Thanks!

**Comment by KingYes** [comment]
Thanks!

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!
