### ISSUE TITLE
Unable to edit section at top of page with video background since v1.50

### ISSUE THREAD

**Issue by upekshapriya** [pojome/elementor#1919]
I have a menu above a video background on our front page and the section controls appear as normal
![screen shot 2017-06-29 at 16 45 01](https://user-images.githubusercontent.com/438647/27697063-2599a2c2-5ceb-11e7-9e5d-44f65ed6c1a9.png)
except when moving the mouse over the menu items which are overlaid over the video at the top - then the section controls disappear.
![screen shot 2017-06-29 at 16 45 23](https://user-images.githubusercontent.com/438647/27697493-4e476e74-5cec-11e7-8019-15fd517ad926.png)

As a workaround, if I go into the Developer Tools in Chrome and give the site-header class a z-index of 0 the header disappears and the section controls are always visible. (I'm using the Sydney theme.)

In the previous versions of Elementor the section shape didn't match the video background, which was a little confusing in itself and the new version is definitely an improvement as the section edge matches the background video edge, but it meant that this issue didn't arise.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
