### ISSUE TITLE
image carousel issues

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1920]
since latest updates theres some strange behaviour of the image carousel:

1. navigation dots and arrows are both always shown even theyre set to 'none' - especially annoying on mobile when only one or two  image(s) shown with lots of dots beneath.

2. setting the scrollable slides to '5' (showing 5 on desktop) - all 5 are moving at change. on tablet (below 768px) and mobile theyre suddenly only moving one by one... is that the intended behaviour?

3. not shure where are the expected breakpoints... if e.g. setting desktop to '5', tablet to '4' and mobile to '2' there are still 5 on 768px table portrait, breaking at 766 and breaking to 2 below 480?
mainly expected to see the 4 already at 768 ...
(strange in the way because e.g. post grid tablet break already seems to be at 1024px - means the post grid breaks already, the image carousel does far later...? - so: different breakpoints???)

any kind of enlighting highly appreciated.

(btw leads to the conclusion that custom breakpoints are needed... :-) )

**Comment by arielk** [comment]
I think that we already fix this issue, can you please update to the beta version 1.6 RC2 and let me know if it works for you?

Feel free to reopen the issue and we'll be happy to help you further.
