### ISSUE TITLE
Undefined index selectors in css-file.php

### ISSUE THREAD

**Issue by andreasnrb** [pojome/elementor#1923]
I get a notice and warning.
```
Notice: Undefined index: selectors in [...]/web/app/plugins/elementor/includes/css-file/css-file.php on line 132
Warning: Invalid argument supplied for foreach() in [...]/web/app/plugins/elementor/includes/css-file/css-file.php on line 132
```
## Steps to reproduce

It happenes somewhat randomly. Might be after visiting pages after a template has been saved. But since its not always that way hard to tell. On refresh it disappears.

### Workaround 
Check if selectors index is set if not bypass loop.

## Environment
Version 1.4.9, 1.4.10 and 1.5.1.

**Comment by arielk** [comment]
Fixed for the next version: https://github.com/pojome/elementor/pull/1979 

Thanks for your report!
