### ISSUE TITLE
Entrance animations for sections in 1.5 

### ISSUE THREAD

**Issue by nullmem** [pojome/elementor#1924]
My last bug report was closed, but it was not fixed. #1906 

After updating to 1.5 I notice entrance animations for sections are glitchy. When you scroll up and down the page they all glitch out. I think for some reason the animation is being reset when you scroll up but it's not smooth. There is no reason to ever reset the animation. Once the entrance animation is complete it should never reanimate unless the page is refreshed.

Here is a video showing the problem:
https://drive.google.com/file/d/0B0Pvq57aPGz6WHdqczQtY05oWTQ/view

**Comment by korkusuzca** [comment]
Well I installed the new version, okay okay. The bill is broken. Everything works incomplete. I also set up the old one again. But my problem continues. https://www.youtube.com/watch?v=RAajdjhP1po

**Comment by arielk** [comment]
Hi @nullmem
v1.5.2 released with a patch for this issue, please update and let me know if this solved the problem.

**Comment by nullmem** [comment]
Problem resolved.

**Comment by orrydorry** [comment]
If you refresh though whilst looking at a section with an animation, don't you find that the animations case the sections to center to the left of the screen?
