### ISSUE TITLE
Background Video not centered?

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#1925]
It seems the video background is not vertically center. Can something be done about it?

**Comment by drawcard** [comment]
Do you have a screenshot and can you submit a bug report as per the instructions on the GitHub issue template?

**Comment by joram1979** [comment]
Got the same issue... and as I cant center the video it shows the roof as my video is a timelapse in a room... :D

**Comment by arielk** [comment]
Fixed for the next version: https://github.com/pojome/elementor/commit/32a375d6c70cbcdc18f2ed0b713d6f7c903dedbd

Thanks for your report!

**Comment by nolanmanning703** [comment]
Hi, I'm having the same issue with my background video not being centered. I see that you addressed this issue, but it doesn't seem to have solved the problem for me.

Here is the website that I'm working on so you can see the problem: [site](http://studycrafter.com/homepage/)

**Comment by joram1979** [comment]
> The reason this conflict occurs is that you have a left sidebar, but the BG video still calculates it as a part of the page.  
> So it is actually centered, but part of it is sitting "under" the sidebar.  
>   
> We fixed it by setting this (under *Elementor > Settings > Style*):
  
|||||||||||||||||||||||||||||||||||||||  
repreZent.ch  
  
rue de la Côte 133  
CH-2000 Neuchâtel  
Tél. +41 78 775 45 54  
|||||||||||||||||||||||||||||||||||||||  
  
http://www.reprezent.ch  
  
https://www.facebook.com/repreZent.ch  
http://twitter.com/#!/repreZent  
instagram : reprezent_ch
