### ISSUE TITLE
Unknown text input into Group_Control_Border

### ISSUE THREAD

**Issue by kaskad88** [pojome/elementor#1926]
![ss screen capture 6657](https://user-images.githubusercontent.com/14362877/27724911-ab6447a4-5d7c-11e7-9c8a-2a53a06ce92d.png)

## System info
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.9 (Win64) PHP/5.5.12
	MySQL version: 5.6.17
	PHP Version: 5.5.12
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	WP Multisite: No
	Max Upload Size: 1,000 MB
	Memory limit: 40M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Twenty Sixteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.5.1
		Author: Elementor.com

WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

== Debug ==
	Errors: There are no errors to display

**Comment by WPDevHQ** [comment]
Confirming as a bug on some Controls that uses the `'separator' => 'before',` call on them.

In this case it's on the `Group_Control_Border::get_type()` add_control call! File: button.php L291

**Comment by KingYes** [comment]
@WPDevHQ I'm really want to debug this, but I can't see this in my install (just random). Do you know how to get this always?

**Comment by arielk** [comment]
Fix for next version: https://github.com/pojome/elementor/commit/a125234c6917f25ee6e3ff02bd23efa1a7840a35

Thanks for your report!
