### ISSUE TITLE
[Minor bug] Colour of global widget editor buttons

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#1927]
Running the latest versions of Elementor and Pro - I noticed that the global widget editor buttons are blue (not the traditional yellow my eyes have grown accustomed to): 

![image](https://user-images.githubusercontent.com/1435638/27726328-3648f86a-5db9-11e7-985b-3c772d92e5cd.png)

Not a big problem but I have OCD when it comes to this sort of thing!

**Comment by drawcard** [comment]
I wonder if it's a good idea (for accessibility reasons) to also make the icon colours black (against the yellow background) if you do fix this one.

**Comment by arielk** [comment]
v1.5.5 released with a patch for this issue.
@drawcard thanks for your report!

**Comment by drawcard** [comment]
You're welcome 👍🏻
