### ISSUE TITLE
Responsive Custom Column Width Bug

### ISSUE THREAD

**Issue by kaskad88** [pojome/elementor#1928]
## Steps to reproduce
I created a custom column structure for the desktop: 20% - 60% - 20% 

![ss screen capture 6660](https://user-images.githubusercontent.com/14362877/27726155-e85eb14e-5d81-11e7-8e9d-f884cc71c718.png)

On the tablet, I changed the structure of the columns to 100% - 50% - 50%

![ss screen capture 6661](https://user-images.githubusercontent.com/14362877/27726190-0d896a54-5d82-11e7-8a87-400245b8f940.png)

In the editor, the width of the columns will change correctly.

But on the front-end, the width of the columns is displayed incorrectly (conflict of specificity of selectors css)

![ss screen capture 6662](https://user-images.githubusercontent.com/14362877/27726253-592df920-5d82-11e7-8554-2513b2f09624.png)

## System info

== Server Environment ==
Operating System: WINNT
Software: Apache/2.4.9 (Win64) PHP/5.5.12
MySQL version: 5.6.17
PHP Version: 5.5.12
PHP Max Input Vars: 10000
PHP Max Post Size: 1000M
GD Installed: Yes
Elementor Library: Connected

== WordPress Environment ==
Version: 4.8
WP Multisite: No
Max Upload Size: 1,000 MB
Memory limit: 40M
Permalink Structure: Plain
Language: en-US
Timezone: 0
Debug Mode: Active

== Theme ==
Name: Twenty Sixteen
Version: 1.3
Author: the WordPress team
Child Theme: No

== User ==
Role: administrator
WP Profile lang: en_US
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

== Active Plugins ==
Elementor
Version: 1.5.1
Author: Elementor.com

WordPress Importer
Version: 0.6.3
Author: wordpressdotorg

== Debug ==
Errors: There are no errors to display

**Comment by arielk** [comment]
As I know, this bug is related to the PHP version of your server. If you upgrade to PHP 7.0 or higher it should work out.
