### ISSUE TITLE
Elementor v1.5 issue with slider revolution

### ISSUE THREAD

**Issue by ahm-3d** [pojome/elementor#1929]
## Description

After I updated to Elementor v.1.5, the slider revolution widget on my page disappeared on the front end, however the slider appears as expected when I revisit the same page in elementor.

## Steps to reproduce
edit page with Elementor, add new section then add slider revolution widget into the new section, then save and visit the page on the front end

## Environment

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.35
	PHP Version: 5.6.22
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	Site URL: http://www.maltonlaser.com
	Home URL: http://www.maltonlaser.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: chris@pureagency.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Malton Laser
	Version: 1.0.0
	Author: Chris Poole
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0

== Active Plugins ==
	Black Studio TinyMCE Widget
		Version: 2.3.2
		Author: Black Studio

	Breadcrumb NavXT
		Version: 5.7.0
		Author: John Havlik

	CMB2
		Version: 2.2.4
		Author: WebDevStudios

	Contact Form 7
		Version: 4.8
		Author: Takayuki Miyoshi

	Elementor
		Version: 1.4.10
		Author: Elementor.com

	Flamingo
		Version: 1.6
		Author: Takayuki Miyoshi

	Flexible Posts Widget
		Version: 3.5.0
		Author: DPE WS&D LLC

	Google Analytics by WebKinder
		Version: 1.6.2
		Author: WebKinder

	Redirection
		Version: 2.6.2
		Author: John Godley

	Slider Revolution
		Version: 5.3.1.5
		Author: ThemePunch

	Wordfence Security
		Version: 6.3.12
		Author: Wordfence

	WP Migrate DB
		Version: 0.9.2
		Author: Delicious Brains

	Yoast SEO
		Version: 4.9
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: $(...).slick is not a function
			at http://www.maltonlaser.com/wp-content/themes/malton-laser/js/scripts.js?ver=1.0.0 - 49:5
			2017-06-30 08:46 +00:00
			x 5 times

		TypeError: $(...).slick is not a function
			at http://www.maltonlaser.com/wp-content/themes/malton-laser/js/scripts.js?ver=1.0.0 - 49:27
			2017-06-29 16:10 +00:00
			x 7 times

		ReferenceError: quicktags is not defined
			at http://www.maltonlaser.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.2 - 6:11229
			2017-06-29 10:56 +00:00

		ReferenceError: tinyMCEPreInit is not defined
			at http://www.maltonlaser.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.2 - 6:11654
			2017-06-29 10:56 +00:00

		TypeError: $(...).slick is not a function
			at http://www.maltonlaser.com/wp-content/themes/malton-laser/js/scripts.js?ver=1.0.0 - 49:5
			2017-06-29 10:56 +00:00

		TypeError: null has no properties
			at http://www.maltonlaser.com/wp-includes/js/tinymce/tinymce.min.js?ver=4506-20170408 - 10:25574
			2017-06-29 10:56 +00:00

		TypeError: $(...).slick is not a function
			at http://www.maltonlaser.com/wp-content/themes/malton-laser/js/scripts.js?ver=1.0.0 - 49:27
			2017-06-29 10:56 +00:00

		TypeError: $(...).slick is not a function
			at http://www.maltonlaser.com/wp-content/themes/malton-laser/js/scripts.js?ver=1.0.0 - 49:5
			2017-06-29 10:56 +00:00

		TypeError: $(...).slick is not a function
			at http://www.maltonlaser.com/wp-content/themes/malton-laser/js/scripts.js?ver=1.0.0 - 49:27
			2017-06-29 10:53 +00:00
			x 51 times

**Comment by arielk** [comment]
Please try update your revolution slider plugin to last version (5.4.5.1 StarPath - 10th June 2017) and let me know if it solved for you.
