### ISSUE TITLE
Bug in Posts Widget when setting image ratio on mobile

### ISSUE THREAD

**Issue by formulaclick** [pojome/elementor#1930]
![screenshot-elementor-bug-image-ratio](https://user-images.githubusercontent.com/2376672/27742326-88d4e298-5db8-11e7-8f5f-210465d35a5f.jpg)
I'm using last Elementor & Elementor Pro versions. This issue occurs with Post Widget. In classic mode and in Cards mode. If I set an explicit image ratio for mobile or tablet version, this is the CSS code is generating for each post thumbnail's "elementor-post__thumbnail" div:

padding-bottom: calc( 0,5 * 100% );

Chrome and Firefox (I tried in both) doesn't read this due to the comma (0,5) so no image is shown. If I edit CSS with code inspector and change "0,5" by "0.5" (point instead comma) then it works fine and image is shown.

Can this be fixed?

**Comment by bainternet** [comment]
@formulaclick 

I can't replicate in the latest version 1.8.5
please feel free to reopen if the issue persists.
