### ISSUE TITLE
[Feature Request] Add "Show Title" option to Social Icons Widget

### ISSUE THREAD

**Issue by jessbudd** [pojome/elementor#1932]
It would be really great if the "Social Icons" widget gave an option to show the words as well as the icon (Eg facebook link would show the facebook icon and then the word "facebook", so it would look like long social media buttons).

This would make the widget more versatile, as we could duplicate a footer/sidebar widget that has icons and just change one setting to re-use the widget on pages as a row of social media buttons.

**Comment by arielk** [comment]
Actually you can using a Button widget for this results, right?

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
