### ISSUE TITLE
[Feature Request] Add attachment option to the form widget

### ISSUE THREAD

**Issue by sugarchrist** [pojome/elementor#1933]
Hello,

I would like to request a small feature: 
Could you consider adding attachment option to the form widget so that web user can upload file with the form?

Thank you
Christian (Elementor Pro user)

**Comment by arielk** [comment]
I merged this issue with another issue #1482 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
