### ISSUE TITLE
Problems with animated entrances since 1.5

### ISSUE THREAD

**Issue by nullmem** [pojome/elementor#1942]
In 1.5 the way entrance animations work completely changed. I already reported one problem #1924 and it seems to be resolved, but the problems don't end there. Here are 2 examples of issues I consider to be a big enough problem for me to just not use any animations on my site anymore:

1) When refreshing the section should not appear, then disappear.
https://drive.google.com/file/d/0B0Pvq57aPGz6ajZTMEoyNmR0c3c/view

2) When scrolling down, the animation should happen much sooner. In this screenshot, you can see that any customer reading to this point will just assume there is nothing else on the page and move on.
https://1drv.ms/i/s!ApNSWRRSjVPIjBpBCSyRHjW3PpnT

**Comment by arielk** [comment]
Which browser are you using?

**Comment by nullmem** [comment]
Chrome

**Comment by arielk** [comment]
Is your Chrome updated the latest version?
I just want to reproduce the bug (I can’t find it in the version 59.0.3071.115).

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
