### ISSUE TITLE
Can we add "+" option to inner-section hover controls too?

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1943]
In the new 1.5 redesign of the hover controls for sections and columns, we now have the ability to add (insert) a section above the current section.  This is very convenient but currently only available for top-level sections.

Can we add this feature to inner-sections too please? =)

**Comment by arielk** [comment]
The regular section needed the "+" option to prevent you from having to scroll to the bottom to add a new section
With inner section you don't have that problem, because you can simply drag and drop another **Columns widget** to add another inner section.

I hope that's clear

**Comment by pingram3541** [comment]
Yes, just seems like it would be simple to implement, no?  Also less trouble with exact placement...but yes you're right, it's not necessary as we can continue to use drag method.

**Comment by arielk** [comment]
Unfortunately, this is a bit complicated. A columns widget is a hybrid of section and widget, so there are slight differences between them.

Anyway, we think that it’s not necessary, but thank you for the feedback!
