### ISSUE TITLE
[feature request] global custom CSS view and/or management

### ISSUE THREAD

**Issue by jefechang** [pojome/elementor#1945]
How about a global css view to display all custom css added on all widgets/sections/elements.
This would show in a glance all customizations done and it would give more control and consistency at the whole project.
Thanks and keep up with the good work.

**Comment by pingram3541** [comment]
Great suggestion, +1 for me!

**Comment by gahawkey** [comment]
...especially if there was a small indicator (like an icon) in the corner of each widget/column/section that has custom CSS applied. This would make it much quicker to hunt down unique overrides etc!

**Comment by arielk** [comment]
Merge to #2180
