### ISSUE TITLE
Link Images Carousel 

### ISSUE THREAD

**Issue by ANDERSONPADUARJ** [pojome/elementor#1948]
Firstly, I would like to congratulate you on the excellent project. I would like to present CAROUSEL implementation suggestion so that it was possible to include a link for each image. I created carousel with the logo of my main client and I would like that when clicking on the logo would take the user the page of it.

Anderson Miranda
Santo Antonio de Pádua
Rio de Janeiro
Brasil

**Comment by WPDevHQ** [comment]
There's a couple of solutions in an older thread including the plugin I linked to in this comment: https://github.com/pojome/elementor/issues/216#issuecomment-307950046

**Comment by arielk** [comment]
I merged this issue with another issue #216 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
