### ISSUE TITLE
Revolution Slider

### ISSUE THREAD

**Issue by Silver176** [pojome/elementor#1950]
Very disappointing. Using the Pro version and Rev Slider I can add a slider using the shortcode widget but after saving I can’t see the slider on a test site, localhost. As far as Facebook is concerned you should have your own forum for support not everyone uses Facebook and I can’t look at it without registering, no chance of that. With respect you should make yourself independent. Anyway clearly your system is not working with Revolution Slider which is great shame and clearly no support for those not using Facebook. Looks like I have wasted my money and no way to contact directly.

**Comment by arielk** [comment]
We have excellent support for pro users through our website: https://my.elementor.com/support/

Please send a message from your account and our support team will be happy to help.
