### ISSUE TITLE
Feature request: Different-device settings for background attachment

### ISSUE THREAD

**Issue by brycewray** [pojome/elementor#1954]
I suggest allowing different devices to have different settings for Background Attachment, to get around the common issue wherein tablets ultra-magnify fixed backgrounds that look normal on phones or desktops.

**Comment by KingYes** [comment]
At this time, we do not plan to add this. But you can do that by our [Custom CSS](https://docs.elementor.com/article/95-custom-css).

Thanks for the suggestion!

**Comment by brycewray** [comment]
OK. Tried that and it worked, although I'm glad I didn't have to do it in too many places. I still think that, since you provide the capability to set other parameters based on media queries, this should be added to the list.
