### ISSUE TITLE
Accordion module is not showing content of copied items.

### ISSUE THREAD

**Issue by sitepilot** [pojome/elementor#1958]
## Description

Accordion module is not showing tab content when copying an item.

![elementor_accordion](https://user-images.githubusercontent.com/20165378/27900442-aca7ddfe-622e-11e7-99d2-68d7fb34dc11.PNG)

## Steps to reproduce

1. Insert the Accordion module.
2. Change the last item.
3. Copy the last item.
4. Change the content of the copied item.
5. Click on one of the other items.
6. Go back to the last item, the text (in the editor) is still in place but the view is empty.

## Environment

* Operating System: Linux

* Software: Apache/2.4.10 (Debian)
* MySQL version: 5.5.5
* PHP Version: 7.1.6
* PHP Max Input Vars: 1000
* PHP Max Post Size: 64M
* GD Installed: Yes
* Wordpress 4.8

**Comment by arielk** [comment]
I did the whole process you described, but unfortunately I can't seem to reproduce your problem.

Have you tried to deactivate other plugins on your WordPress?

**Comment by sitepilot** [comment]
Strange, i've tried again (and updated Elementor) and now it works. Only plugin active is Elementor Pro :+1: 

Thank you for your time!
