### ISSUE TITLE
Polylang Pro + Elemento Pro post duplication small issue

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1959]
Hi, I just found a little bug. Steps to reproduce:

1. Have both Polylang Pro and Elementor Pro installed (I guess it'd the same with Elementor Free)

2. Create a page on default lang, do something with elementor, save.

3. Activate polylang content duplication on that page. > note it was not activated before

4. Click another language to translate. > till now all fine, you will see the post traslation wp edit page

- Now click the blue button to modify with Elementor > here's the issue: you will be redirected to the frontend and see the 404 page template (page not found)

---

This does not happen if polylang content duplication was already active before (so before point 2.). In that case all goes fine and elementor's content seems to be correctly duplicated between languages (tried only few simple widgets).

Using wp 4.8, on latest firefox, osx 10.11.6

**Comment by arielk** [comment]
Try to save the page as a draft before you edit the page and let me know if it solved the problem.

**Comment by stratboy** [comment]
It's almost the same as I said before. I guess it'll work. 
I didn't need a temp solution, I just wanted to post the bug.
Thank you, regards

Ariel Klikstein ha scritto:

**Comment by arielk** [comment]
We fix the issue in the next version 1.6, please try the beta version and let me know if this resolve the problem: #2077
