### ISSUE TITLE
Custom CSS back-end broken in Pro 1.5.5

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1961]
## Description

When editing back end using Pro 1.5.5 custom pro css is broken for any "selector" defined rules.

## Steps to reproduce

Apply custom css in Elementor editor and use a rule with "selector" then inspect the css generated, it is adding a space between two classes that should be concatenated and the rule will never apply.

Instead of:
`.elementor-element.elementor-element-zxfgtvs` (which is how the html expects)

it's:
`.elementor-element .elementor-element-zxfgtvs`

I was able to find a copy of 1.5.4 and verify the problem goes away.

**Comment by matipojo** [comment]
Thank you for reporting!
It's been fixed in 1.5.6 and it will be released in the upcoming days.

**Comment by pingram3541** [comment]
TY!
