### ISSUE TITLE
Rollback Pro from 1.5.5 fatal error

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1962]
I've opened an issue with pro level support but have since got my site back up and running.

## Description

Rollback feature rolls back to 1.5.2 with no option of 1.5.3 or 1.5.4 and results in fatal error.

## Steps to reproduce

Rollback Pro from 1.5.5

https://pastebin.com/SP62UBcU

**Comment by KingYes** [comment]
What is `ElementorExtras\Widget_Timeline`?

Please deactivate all your plugins and change to WordPress default theme..

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by pingram3541** [comment]
Sorry didn't get email notifications as I typically do.  That is an add-on plugin but this issue was fixed and I couldn't duplicate even after testing again with the Extras plugin active among others.
