### ISSUE TITLE
Posts element bug

### ISSUE THREAD

**Issue by EdenK** [pojome/elementor#1963]
There is bug in the Posts element (PRO) when using posts taxonomy the arguments are wrong in the "field"

File
/elementor-pro/modules/panel-posts-control/module.php
Line 244

`$query_args['tax_query'][] = [
    'taxonomy' => $object->name,
    'field' => 'terms_ids',
    'terms' => $settings[ $setting_key ],
];`

The field should be **term_id** and not **terms_ids** please fix it in the next versions.

**Comment by KingYes** [comment]
Thanks! Will release in the next version of EPro..
