### ISSUE TITLE
Chrome JS error "Cannot supply flags when constructing one RegExp" with editor.min.js. Elementor won't load.

### ISSUE THREAD

**Issue by carasmo** [pojome/elementor#1965]
![screen shot 2017-07-06 at 2 09 59 pm](https://user-images.githubusercontent.com/1124594/27926038-ffbd2672-6254-11e7-8c9b-b6fb0c17131b.png)

Just doesn't load in Chrome, the logo just stays on the page.

**Comment by carasmo** [comment]
Cannot supply flags when constructing one RegExp. 5 errors.
![screen shot 2017-07-07 at 10 14 28 am](https://user-images.githubusercontent.com/1124594/27961574-2f414786-62fd-11e7-8ed2-7eba4c00f2d6.png)

**Comment by KingYes** [comment]
Please add `define( 'SCRIPT_DEBUG', true );` to your wp-config.php, and print this again..

**Comment by carasmo** [comment]
There are no php errrors. I have this in my wp-config.php. 

It's this line: https://github.com/pojome/elementor/blob/master/assets/js/editor.js#L4532

**Comment by KingYes** [comment]
@carasmo  Please try to check the regex to this and check again if it's fixed `/\{\{(?:([^.}]+)\.)?([^}]*)\}\}/g`

**Comment by carasmo** [comment]
``/\{\{(?:([^.}]+)\.)?([^}]*)\}\}/g``

I put this in editor.js and pasted the entire file in to editor.min.js cleared all cache and it does the same thing. But when I change `/g` to anything else, the editor loads but the elementor CSS for that particular page doesn't load.

**Comment by KingYes** [comment]
@carasmo If you have Pro version, please contact with our support to see your site (with FTP access to debug this)

**Comment by carasmo** [comment]
It's my version of Chrome. Upgraded Chrome (which I barely use only for testing and not building).

**Comment by carasmo** [comment]
I do have Pro version, btw. But this was related to local setup not your plugin.
