### ISSUE TITLE
What's the controls template engine?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1969]
Hi, I was looking at the code, I can't fully understand. I'm creating a new widget and I'd like to be sure of what's the template engine for rendering. For example, in toggle.php I found:

```
	protected function _content_template() {
		?>
		<div class="elementor-toggle">
			<#
			if ( settings.tabs ) {
				var counter = 1;
				_.each(settings.tabs, function( item ) { #>
					<div class="elementor-toggle-title" data-tab="{{ counter }}">
						<span class="elementor-toggle-icon">
							<i class="fa"></i>
						</span>
						{{{ item.tab_title }}}
					</div>
					<div class="elementor-toggle-content elementor-clearfix" data-tab="{{ counter }}">{{{ item.tab_content }}}</div>
				<#
					counter++;
				} );
			} #>
		</div>
		<?php
	}

```

What is it? Maybe Handlebars? But I don't recognize both '<#' and '{{{' tags (Handlebars uses '{{'). So what? Thank you

**Comment by KingYes** [comment]
It's underscore with tags supplier by WordPress to fix some servers configures..

For more info: https://github.com/pojome/elementor/commit/f48a902997da45e0bbced59ea39175c1f433a53f
