### ISSUE TITLE
Feature Request: Slide always visible in Slider widget

### ISSUE THREAD

**Issue by gfdesign** [pojome/elementor#1970]
Hi guys
Such as Revolution Slider has, the idea is that there is a permanent slide where user enter some content and this remains visible between the rest slides. In other words, suppose you want to create an slider where images go changing but the content be always same, as a logo plus a introductory texts.
Does it make sense for you?
Best regards

**Comment by dasigna** [comment]
... already (nearly) achieveable ?

create one slide with content / duplicate / change only image / etc. etc ... setting content animation to 'none'.

thats pretty much it. yes, the content transforms with the slide anyway... but a little more indication of a change cant do much harm - no? :-)

**Comment by gfdesign** [comment]
You're right. That would work. Thanks for your approach.
However, this feature would be convenient when there are several slides.
Don't you think?

**Comment by arielk** [comment]
You can also set the background of the widget (under > advanced) for this option.

**Comment by pingram3541** [comment]
@arielk - I know this was closed but it still would be nice to have a static content option vs re-animating and duplicating the same text content for every slide.

Only way I know to do this now is with z-index overlap of a heading widget layered above a slider widget but then page builder admin becomes difficult to access the "clickables" to edit things later.
