### ISSUE TITLE
Custom widgets js loading order - better if loaded after frontend.js

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1972]
Hi, in Element_Base, I can see this code:

```
	final public function enqueue_scripts() {
		foreach ( $this->get_script_depends() as $script ) {
			wp_enqueue_script( $script );
		}
	}
```

This will load scripts declared as dependencies in an Elementor's Widget class (or custom ones).
But scripts will be loaded before elementor's frontend.js. I know we have the init action. Though, wouldn't it be better if you just take care of loading custom scripts after frontend.js?

**Comment by KingYes** [comment]
It's not the core widget handle. It's just for the library to base your code. The handle code about this need to embed by the global action..

**Comment by stratboy** [comment]
So what?
The problem remains: custom js should be naturally loaded after core frontend.js.

Yakir Sitbon ha scritto:

**Comment by stratboy** [comment]
I can answer by myself here: we can use the 'elementor/frontend/after_enqueue_scripts' filter like this (from my widget):

``` php
add_action('elementor/frontend/after_enqueue_scripts', function(){
  wp_enqueue_script( 'lr-elementor-addons', plugins_url( '/assets/js/lr-elementor-addons.js', LR_ELEMENTOR_ADDONS_FILE__), [ 'jquery' ], false, true );
});
```
