### ISSUE TITLE
Toggle bar doesn’t unfold. 

### ISSUE THREAD

**Issue by elemounter** [pojome/elementor#1975]

**Comment by elemounter** [comment]
When working in Elementor the toggle bar works with unfolding. But when you visit the page, the unfolding of the toggle bar doesn't work anymore.

**Comment by KingYes** [comment]
Do you have any errors on your console?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
