### ISSUE TITLE
Fatal Error: Page completely broken, saving HTML wrong 

### ISSUE THREAD

**Issue by accetturo** [pojome/elementor#1977]
**CRITICAL ISSUE**
After saving one of our posts, we get this error and can no longer use the page. We have Elementor Pro as well installed and lost 10 hours of work... Fatal error at the end

-----------------------------------------------------
Warning: Illegal string offset 'post_title' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'hide_title' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'template' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'post_status' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_background' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_color' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_color_stop' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_color_b' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_color_b_stop' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_gradient_type' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_gradient_angle' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_gradient_position' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_image' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_position' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_attachment' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_repeat' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_size' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_video_link' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'background_video_fallback' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'padding' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'padding_tablet' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'padding_mobile' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Warning: Illegal string offset 'custom_css' in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 448

Fatal error: Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::_get_items() must be of the type array, string given, called in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 256 and defined in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php:48 Stack trace: #0 /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php(256): Elementor\Controls_Stack::_get_items('\x00:3569:"a:13:{s...', NULL) #1 /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php(87): Elementor\Controls_Stack->get_settings() #2 /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php(71): Elementor\Controls_Stack->get_controls_settings() #3 /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php(137): Elementor in /srv/users/devsitename/apps/shop-sitename/public/wp-content/plugins/elementor/includes/base/controls-stack.php on line 48

**Comment by KingYes** [comment]
Please contact with us in [our support](https://my.elementor.com/support/), and we'll fix this for you.

**Comment by coder618** [comment]
I am facing same problem
```

# | Time | Memory | Function | Location
-- | -- | -- | -- | --
1 | 0.0019 | 372720 | {main}( ) | .../edit.php:0
2 | 2.5061 | 9401408 | WP_Posts_List_Table->display( ) | .../edit.php:362
3 | 2.5098 | 9408496 | WP_Posts_List_Table->display_rows_or_placeholder( ) | .../class-wp-list-table.php:1097
4 | 2.5099 | 9408496 | WP_Posts_List_Table->display_rows( ) | .../class-wp-list-table.php:1165
5 | 2.5099 | 9408872 | WP_Posts_List_Table->_display_rows_hierarchical( ) | .../class-wp-posts-list-table.php:639
6 | 3.0894 | 10334608 | WP_Posts_List_Table->single_row( ) | .../class-wp-posts-list-table.php:755
7 | 3.0908 | 10335088 | WP_Posts_List_Table->single_row_columns( ) | .../class-wp-posts-list-table.php:1195
8 | 3.0920 | 10336784 | WP_Posts_List_Table->_column_title( ) | .../class-wp-list-table.php:1245
9 | 3.0920 | 10336784 | WP_Posts_List_Table->column_title( ) | .../class-wp-posts-list-table.php:857
10 | 3.0935 | 10336816 | _post_states( ) | .../class-wp-posts-list-table.php:943
11 | 3.0937 | 10337192 | apply_filters( ) | .../template.php:1791
12 | 3.0937 | 10337592 | WP_Hook->apply_filters( ) | .../plugin.php:203
13 | 3.0937 | 10338368 | Elementor\Core\Admin\Admin->add_elementor_post_state( ) | .../class-wp-hook.php:286


```
Please help
