### ISSUE TITLE
[Feature requests] Elementor Pro as template builder for single & CPT post, archive, tags and category pages

### ISSUE THREAD

**Issue by gfdesign** [pojome/elementor#1980]
Dear developers

I am wondering if you are going consider Elementor Pro as template builder for single post, single CPT, archive, tags or category pages. I know some templates could be done with some add-on plugins (such as 'Press Elements', 'AnyWhere Elementor', etc ) but you aren't the developers of them. So, it would be great you include into Elementor Pro roadmap the idea to be able to build template for the mentioned pages in order to these templates depend on just on plugin / developer. These features should include post title, body content, excerpt, post images, custom fields (ACF)

FYI, the [Layout plugin of Toolset](https://wp-types.com/home/layouts/) has some similar features where user can built these pages. Would be great to see those functions in Elementor Pro.

Best regards

**Comment by arielk** [comment]
I merged this issue with another issue #543 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by dudaster** [comment]
You can try to use my theme, while is working with Elementor, I strongly advice buying buy Elementor Pro. I used it on a dozen of websites so far and perfected it over a year now: https://github.com/dudaster/eletheme/
