### ISSUE TITLE
Replace URL - allow without protocol please

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#1981]
I prefer to use protocol-less urls such as //mydomain.com/ without the http/https and simply let the headers control this.  Is there a reason this is not allowed in the find / replace tool?  Just curious is this is a problem to allow this, thx.

**Comment by KingYes** [comment]
It's just to be sure you don't replace other text.

**Comment by pingram3541** [comment]
Gotcha, I understand sometimes it is better to have that "Apple" mentality of locking things down to protect the general public from themselves.

The downside is if I ever need to push this db to an evironment without https it will break and I'll be forced to run the reversal.  Is my logic flawed on this topic?

**Comment by matipojo** [comment]
Hi, @pingram3541, Because the Elementor data is saved in JSON format, The data might brake while replacing text. for example: `http:` could be a JSON property key.
