### ISSUE TITLE
{Feature Request} Animated Text

### ISSUE THREAD

**Issue by TTS12** [pojome/elementor#1982]
I would really find it useful if you could had a feature that allows us to have a word change automatically within a sentence.

For example : if I have the following sentence on my homepage : "Learn how to swim/run/jump" I would like the word "swim" to change automatically (after 1 second) to "run" and then to "jump"...I know that Beaver builder has that option, but I can't seem to see it with you guys. 

FYI - one of the top youtuber on page builders WP Crafter (http://wpcrafter.com/) has said during one of his tutorial video that this feature is the only reason why he hasn't switched from Beaver Builder to Elementor Pro. You can see he is using this feature on his homepage.

Thanks

**Comment by bainternet** [comment]
Already implemented https://elementor.com/introducing-animated-headline/
