### ISSUE TITLE
«Columns» widget is not saved as a widget, but as a section

### ISSUE THREAD

**Issue by ShialMeth** [pojome/elementor#1983]
There is a widget named «Columns» that gives us opportunity to use section inside column as a widget in terms of dragging and replacing it.

But when it comes to save this widget as a template, it doesn't act as a widget, it is not saved as a «global widget», but it's saved as section template. With that, i have to insert this template and drag every column into a new-created «Columns» and copy every setting like classes and custom-CSS into this new-created «Columns».

It would be very nice if there was a solution to this problem, regardless of which way to go: make the Columns a true widget, or some other way. Thanks.

**Comment by joshmarom** [comment]
Although it is in the widgets panel and it is dragged into the page just like you drag a widget, technically it isn't really a widget, but a Section.
That's why there's no way to save it as a global widget.
