### ISSUE TITLE
Text editor backoffice issue with Elementor 1.5.3

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1984]
Hi, I found out that the text editor doesn't work as expected in admin.

1. It doesn't show the preview (remains empty)
2. It --seems-- that it's using php refreshing instead of js/underscore (so it's quite sluggish)

It will anyway save the (invisibile) content, and in frontend it's all ok.
I also found that the 'wordpress' text editor version (the one under wordress widgets) does not have first issue, but retains the second one.

Currently on wp 4.8, tested both with ff and chrome on macos 10.11.6

**Comment by dasigna** [comment]
... not encountered here. all works as expected.
??
wp4.8 ff, chrome, etc. win7pro

**Comment by stratboy** [comment]
Yes, there was a conflict with my own css, sorry. Closing.
