### ISSUE TITLE
Css overrides don't get reflected in elementor's admin

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1985]
Hi, another issue at least with elementor 1.5.3 (but maybe present before): if I override some css, it's won't be reflected/visible in admin. It anyway will be correctly displayed in frontend.

Currently on wp 4.8, tested both with ff and chrome on macos 10.11.6

**Comment by KingYes** [comment]
What you mean "Elementor Admin"? Do you mean about the Editor?

If yes, you need embed that CSS by `elementor/editor/after_enqueue_styles` action..

**Comment by stratboy** [comment]
ok

Yakir Sitbon ha scritto:

**Comment by stratboy** [comment]
One manual way is to regenerate styles via backoffice elementor's preferences > tools
