### ISSUE TITLE
Few Elementor Ajax Calls Failing

### ISSUE THREAD

**Issue by PranavManiar** [pojome/elementor#1987]
I was evaluating elementor for my site and I have come across below issue. 

**Precondition:**
When wordpress admin is configured to run on http and only login is redirected to https, then this issue occurs. 

Elementor admin ajax request like "heartbeat" request refers correctly to the http address and hence works correctly 

Other elementor requests like "elementor_get_templates", "elementor_save_builder" refers to the "https" address, but wordpress admin was loaded from "http" address. 
So browser treats it as CORS request and it does not send cookie and "X-Requested-With: XMLHttpRequest" header. 
Because of this valid elementor ajax function does not get called and the request returns 0. 
Due to this, "Template Library" screen gets stuck on loading only.

**Comment by KingYes** [comment]
We are fix this issue in [`release/1.6.0`](https://github.com/pojome/elementor/tree/release/1.6.0). Please try on on your dev install, and tell me if it's fix your problem..
