### ISSUE TITLE
2 different javascript files with elementor pro

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1989]
Hi, I just noticed that with Elementor Pro, 2 distinct frontend.js files are loaded in footer, one for Elementor and one for Elementor Pro.

It would be great if they are just 1. Probably, Elementor Pro should come with the entire frontend js (elementor + elementor pro). So when activated, it should load something like frontend-pro.js INSTEAD of the default frontend.js, since when Elementor Pro is activated, you are absolutely sure that standard Elementor is not needed.

This doesn't really apply for php files and in admin environment. It's just frontend optimisation, that is really important.

Regards

**Comment by arielk** [comment]
Elementor Pro Is extension of Elementor with different versions.

It is not clear which is better, heavier files or a few smaller files that are loaded on demand.

You can always use an optimization plugin like this to minify the files: https://wordpress.org/plugins/autoptimize/

**Comment by stratboy** [comment]
Thank for the plugin suggestion, can be usefull. Anyway, it's really clear what's best: 1 file. This is a best pratice since years and years, especially for these kind of files where server zip compression is really effective. You can find tons of articles, and books too about this very topic. The main object here, is reduce concurrent http requests. Also, if that count, in almost 20 years of web development I've tried quite everything, and I can say this is a very important thing. Last but not least, it's one of the first things pagespeed will ask you when validating a website. So me + google + articles +  books should be enough to take this thing into consideration, I think :) 

Also, in this specific context, keep in mind that yours will be often (and sadly enough) only one of many installed plugins. They often clutter the pages with a ton of http requests, and I think that 9 requests (7 css + 2 js) are really, really a lot for only one plugin.

You are doing an excellent work with this plugin, you can make it shine even more.

**Comment by heyjoecampbell** [comment]
I find JCH Optimize to be the best optimization plugin available for WordPress:
https://wordpress.org/plugins/jch-optimize/

It can combine and minify your local and external files (even omit troublesome files) leaving you with 1 CSS and 1 JS

Note: a Pro subscription is required for all optimization features, but you can use the subscription on an unlimited number of site :)

**Comment by MGParisi** [comment]
Just an FYI, please DON'T combine the JS and CSS on HTTP/2, as this will reduce performance.
