### ISSUE TITLE
Add filters to modify breakpoints in /includes/responsive.php

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1990]
Hi, this is somewhat an already discussed topic, but I'd like to be more specific: how about adding a filter in responsive.php? Just to make basic breakpoints editable? Or, eventually, a set_breakpoints method? (But I guess a filter would be a better solution).

Thank you

**Comment by arielk** [comment]
I merged this issue with another issue #78 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
