### ISSUE TITLE
Too much css files

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1991]
Hi, it would be great if you could combine as much css files as possible. 7 css http requests are definitely too much for a single plugin.
File it as a feature request :) Regards.

![schermata 2017-07-11 alle 11 32 09](https://user-images.githubusercontent.com/437598/28062018-e5483e86-662c-11e7-8943-5707fcae1b11.png)

**Comment by arielk** [comment]
It is not clear which is better, heavier files or a few smaller files that are loaded on demand.

You can always use an optimization plugin like this to minify the files: https://wordpress.org/plugins/autoptimize/

Thanks for your feedback!
