### ISSUE TITLE
Docs elementor/frontend/after_register_styles possibly wrong?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1992]
Hi, on the docs of [elementor/frontend/after_register_styles](https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md#elementorfrontendafter_register_styles), I can read this code:

``` php
add_action( 'elementor/frontend/after_register_styles', function() {
   wp_dequeue_style( 'font-awesome' );
});
```

Usually, wp_dequeue_style is used after enqueueing  styles, not after registering. So maybe you should write wp_deregister_style or change filter to elementor/frontend/after_enqueue_styles.
I would have done the edit, but I'm no sure if this code is somewhat related to elementor's internals.

Anyway, docs also lacks  'elementor/frontend/after_enqueue_styles'. They're not complete for scripts hooks too.

**Comment by KingYes** [comment]
Thanks!
