### ISSUE TITLE
Full width sections with css only

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#1994]
Hi, I see that the full width option uses javascript. Maybe you could consider using css only, just adding proper classes to the document body and the selected sections. Please take a look here:

https://cloudfour.com/thinks/breaking-out-with-viewport-units-and-calc/

Please consider this as a feature request.

Regards

**Comment by joshmarom** [comment]
As much as we would like to have a CSS-based solution for magic-full-width section, I'm afraid it isn't possible.
The suggested solution, (which is very cool for what it is), doesn't cover everything covered by our existing JS solution.

Thanks for the suggestion!
