### ISSUE TITLE
Feature request: Delay elements

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#1997]
Delay elements would be a great feature, sometimes we want to show a button after 20 seconds and hide some elements and show after X seconds, please consider to add this feature.

**Comment by arielk** [comment]
From v1.5.0 of Elementor you can set the delay by Entrance Animation (under > Advacned tab).

At this time, we do not plan to add the Hide element in upcoming versions, so right now I close the issue!

Thanks for your feedback!
