### ISSUE TITLE
sections background black since pro 1.5.6 [ISSUE]

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1998]
since update to pro 1.5.6 the backgrounds of the sections are all black in editor due to this elementor-background-video-container / elementor-background-video-hosted class :

`video {
    background: #000;
    ...
}`

have to eliminate this temporarily to see the dark font again...

**Comment by arielk** [comment]
We didn't add anything to the style in this version. We just added a patch to Custom CSS, please check that you do not have any custom code or something like this.

**Comment by dasigna** [comment]
WTF...

SORRY!!! definitely NOT due to elementor - its coming from theme! dont know why all of sudden without updating it, but its theme. (stumbled into wrong file...)

sorry again for bothering. its not elementor :-)

**Comment by arielk** [comment]
Thanks for your update!
