### ISSUE TITLE
manual selection in portfolio widget [issue]

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#2000]
since last update, the manual selection of items for query in _existing_ portfolio widget isnt working...
the search gives absulutely no results, even when typing the exact name of the item. search shows only results of already existing items in query when characters match.
when creating new portfolio widget, this works as expected... weird? weird!

any idea what might cause this?

EDIT:
tried manual reinstall of 1.5.4 - doesnt work eighter... :-/

**Comment by dasigna** [comment]
UPDATE:

tried several things - no change to the better...
even when creating a new portfolio widget the manual selection of items only works for the first time. as soon as leaving editing this widget and coming back one second later you cant select or search other/new items. deleting the 'old' ones and starting with blank selection does not work eighter, the search wont function any more, you cant add other items ...

sadly wasnt able to follow back since which version this stopped working.

any solution for this please?

**Comment by arielk** [comment]
Fixed E-Pro v1.5.7, please update.

Thanks for your report!

**Comment by dasigna** [comment]
solved. works again. :-)

thanks guys!
