### ISSUE TITLE
[Idea Pro] Label the ReCaptcha module

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#2002]
It would be handy if we had a "Label" field for ReCaptcha, so we can easily identify it in the form builder. Currently it only allows for an autogenerated label.

(For instance, "Honeypot" has this feature and I can rename it as "Spam Blocker" for clients to identify it)

![image](https://user-images.githubusercontent.com/1435638/28147310-b9c98cc2-67be-11e7-8d38-8b23d1ec9d62.png)

**Comment by drawcard** [comment]
Alternately it could just have a more user friendly autolabel, eg "Recaptcha #1" - and the honeypot could do something similar too :)

**Comment by drawcard** [comment]
Oooh. I just thought of another feature - add a description field for the ReCaptcha, so that a custom message can be written to explain the captcha to the user (for instance, "Please click this box to verify you're not a spammer") etc.

**Comment by KingYes** [comment]
You're right. We will add the label in reCAPTCHA in the next EPro release..
