### ISSUE TITLE
[BUG] Missing constant in Controls_Manager class from last versions

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#2003]
Hey,
i developed some widgets to integrate with Elementor existent ones...
When i updated Elementor, the error below appeared

`Fatal error: Uncaught Error: Undefined class constant 'CHECKBOX' in /var/www/sites/vivatek/wp-content/themes/websolution-complete-theme/inc/classes/Elementor/Widgets/LightboxGallery.php:68 Stack trace: #0 /var/www/sites/vivatek/wp-content/plugins/elementor/includes/base/controls-stack.php(471): WebSolution\CompleteTheme\Elementor\Widgets\LightboxGallery->_register_controls() #1 /var/www/sites/vivatek/wp-content/plugins/elementor/includes/base/controls-stack.php(60): Elementor\Controls_Stack->_init_controls() #2 /var/www/sites/vivatek/wp-content/plugins/elementor/includes/base/controls-stack.php(130): Elementor\Controls_Stack->get_controls() #3 /var/www/sites/vivatek/wp-content/plugins/elementor/includes/css-file/global-css-file.php(75): Elementor\Controls_Stack->get_scheme_controls() #4 /var/www/sites/vivatek/wp-content/plugins/elementor/includes/css-file/global-css-file.php(34): Elementor\Global_CSS_File->render_schemes_css() #5 /var/www/sites/vivatek/wp-content/plugins/elementor/includes/css-file/css-file.php(310): Elem in /var/www/sites/vivatek/wp-content/themes/websolution-complete-theme/inc/classes/Elementor/Widgets/LightboxGallery.php on line 68`

I checked the old plugin version, file controls.php
![image](https://user-images.githubusercontent.com/19909323/28156678-069cf274-67b4-11e7-9f03-43f2b8a0a60f.png)

Who should i blame for this? :D @KingYes @kobizz @matipojo 
Please pay attention to not remove main functionalities instead of enhancing them.

**Comment by nextend** [comment]
https://github.com/pojome/elementor/commit/942d3b89354a3626c288163135a633e43bb08882#diff-5e5fa7206b1efb0536c93ace620bbe58

**Comment by teolaz** [comment]
@nextend tnks!
@kobizz why?

**Comment by joshmarom** [comment]
@teolaz These controls were never officially a part of [our API](https://github.com/pojome/elementor/tree/master/docs#controls).

The official "Checkbox" control is [Switcher].(https://github.com/pojome/elementor/blob/master/docs/content/controls/_switcher.md)
The official method for dividers between controls is [separator](https://github.com/pojome/elementor/blob/master/docs/content/controls/controls-and-the-editor.md#separator)

Sorry for the inconvenience, it is in order to have a more concistent and homogeneous methodology across the board. Thanks for the understanding.

**Comment by teolaz** [comment]
@joshmarom do you agree with me when something is written it needs to be maintained or at limit deprecated in favour of something else?

**Comment by joshmarom** [comment]
@teolaz Ok, you are right we should not have removed it without allowing time for developers to fix their code. we just never really saw these controls as an official part of the system. 

Here's what we're going to do:
In the next version, we will temporarily put those controls back, but they are deprecated and should not be used anymore.
In the future, they will be completely removed again.

**Comment by teolaz** [comment]
@joshmarom what i intend is to deprecate the method, not removing it.
Rewriting the add_control method should work, like this:
```php
public function add_control( $id, array $args, $overwrite = false ) {
		
		// deprecated CHECKBOX and DIVIDER controls type are shaped into SWITCHER and SEPARATOR
		
		if( 
			!empty($args['type']) &&
			in_array($args['type'], [Controls_Manager::CHECKBOX, Controls_Manager::DIVIDER])
		){
			/*
			 * Here the code to deprecate all unused fields
			 * the best thing is transforming CHECKBOX args into SWITCHER ones
			 * and same thing for DIVIDER
			 * .........
			 */
		}
		
		if ( empty( $args['type'] ) || ! in_array( $args['type'], [ Controls_Manager::SECTION, Controls_Manager::WP_WIDGET ] ) ) {
			if ( null !== $this->_current_section ) {
				if ( ! empty( $args['section'] ) || ! empty( $args['tab'] ) ) {
					_doing_it_wrong( __CLASS__ . '::' . __FUNCTION__, 'Cannot redeclare control with `tab` or `section` args inside section. - ' . $id, '1.0.0' );
				}
				$args = array_merge( $args, $this->_current_section );

				if ( null !== $this->_current_tab ) {
					$args = array_merge( $args, $this->_current_tab );
				}
			} elseif ( empty( $args['section'] ) ) {
				wp_die( __CLASS__ . '::' . __FUNCTION__ . ': Cannot add a control outside a section (use `start_controls_section`).' );
			}
		}

		return Plugin::$instance->controls_manager->add_control_to_stack( $this, $id, $args, $overwrite );
	}
```

**Comment by ryanlabelle** [comment]
Thanks for posting the issue and linking to fixes. I ran into these issues as well. Good thing you have future release branches to test against before updating to production. 

I love what you guys are doing. Keep up the great work. :)

**Comment by teolaz** [comment]
@KingYes why you closed this without a word on what i wrote on correctly deprecating?

**Comment by joshmarom** [comment]
Yes @teolaz , we saw your suggestion.

Checkbox and Switcher are not 100% compatible and we are not interested in gracefully converting checkbox controls into switcher controls.

Even more so, there simply is no practical way to convert divider control into separator since separator isn't even a standalone control, but [an attribute](https://github.com/pojome/elementor/blob/master/docs/content/controls/controls-and-the-editor.md#separator).
