### ISSUE TITLE
Feature request - Links to pages/posts.. not just manual entry

### ISSUE THREAD

**Issue by ianstudio** [pojome/elementor#2004]
Hello, I think an important thing missing is that anywhere a link can be added (buttons etc) one gets the option to access the existing pages, posts selector.. I imagine it's hard to implement otherwise it would already be part of Elementor?! But it is mandatory IMO..
--

**Comment by KingYes** [comment]
We have open issue about this https://github.com/pojome/elementor/issues/255

Continue there..
