### ISSUE TITLE
[feature request] [Pro] Forms upload fuctionality

### ISSUE THREAD

**Issue by Creative2000** [pojome/elementor#2009]
In creating forms we need for an "upload" function so that visitors can attach/upload photos/files. 
Please add this feature to make the Pro even more awesome!
Thanks and keep up the great work.

**Comment by KingYes** [comment]
I merged this issue with another issue #1482 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
