### ISSUE TITLE
Site not loading at all after elementor update!

### ISSUE THREAD

**Issue by Gabirell** [pojome/elementor#2012]
Site: www.andar7.com/blog 
Parse error: syntax error, unexpected T_STRING in /home/andar7/public_html/blog/wp-content/plugins/addon-elements-for-elementor-page-builder/inc/elementor-helper.php on line 2

**Comment by KingYes** [comment]
The problem is from `addon-elements-for-elementor-page-builder` plugin. Please contact with the developer of this plugin to fix your error..
