### ISSUE TITLE
Space before/after "$" symbol bug

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2014]
Hello! I've found "$" bug. Please try to write something like "49$" or "$49" using Text Editor or Heading widget. In Elementor all good but when viewing page there is space rendering behind digits and "$". 
"Works" only with digits with letters all normal.

Thanks!

**Comment by KingYes** [comment]
It's seems problem with your theme or other plugin. Try change to default WP theme & deactivate all your plugins.. and try again..
