### ISSUE TITLE
[Request] ID attribute for Form Submit button - Elementor Pro

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#2017]
Hi, I have two Elementor Pro forms set up, the first is an introductory lead capture and the second is a more detailed quote form I'd like to have the data from one form carry over onto the second form on a seperate page, on clicking a Submit button. 

I'm thinking of using [PHP sessions](https://www.w3schools.com/php/php_sessions.asp) to make this happen with cookies. Does anyone know if this is possible with Elementor's Form widget? Or is it better to do this with  Javascript or REST API?

**Comment by drawcard** [comment]
I managed to solve this using jQuery, [jQuery Cookies](https://github.com/carhartl/jquery-cookie) plugin, and a bit of scripting. Just posting here in case anyone needs it.

Perhaps I can transform this post into an idea / request - it would be awesome if the button element for the Form widget could have a unique ID of some kind, so we can target it for cases like this. At the moment, my scripts below target just the general button element with a type=submit attribute, which is not ideal if multiple forms exist on the page.

```php
# form-a.php

<script type="text/javascript">
  // Request a quote form - store information in cookies for prefilling other form
  $(function () {
// Adapted from https://goo.gl/VpS5NX
$('#form-field-first_name').val($.cookie('first_name'));
        $("button[type='submit']").click(function () {
            // Each cookie expires after 31 days and is accessible site-wide
            // ID is derived from the Elementor field
            $.cookie("first_name", $("#form-field-first_name").val(), { expires: 31, path: '/' });
            $.cookie("last_name", $("#form-field-last_name").val(), { expires: 31, path: '/' });
            $.cookie("email", $("#form-field-email").val(), { expires: 31, path: '/' });
            $.cookie("phone", $("#form-field-phone").val(), { expires: 31, path: '/' });
            $.cookie("company", $("#form-field-company").val(), { expires: 31, path: '/' });
        });
    });
</script>
```

```php
# form-b.php
<script type="text/javascript">
  // Retrieve form data from set cookies
  $(function () {
      // Get the ID of each field and insert the cookie data
      $('#form-field-first_name').val($.cookie('first_name'));
      $('#form-field-last_name').val($.cookie('last_name'));
      $('#form-field-email').val($.cookie('email'));
      $('#form-field-phone').val($.cookie('phone'));
      $('#form-field-company').val($.cookie('company'));
    });
</script>
```

**Comment by arielk** [comment]
I don't think it's possible at the moment, for advanced capability like this you can use Gravity or Ninja Forms.

Thanks

**Comment by drawcard** [comment]
No worries, that's fine. It was a bit of a weird edge case scenario and solvable with a bit of custom JS :)
