### ISSUE TITLE
[feature request] Displaying image on 'WooCommerce product categories' widget 

### ISSUE THREAD

**Issue by gfdesign** [pojome/elementor#2018]
Dear support
Please consider to include the image of product category on this widget since currently just it displays the category title and products quantity. Would be great something similar to 'Posts' or 'Portfolio' widgets how they handle the image.
Best regards

**Comment by arielk** [comment]
I'm not sure I understood you, can you please explain more?

If you have an example it would be great.

**Comment by gfdesign** [comment]
Sorry for my delay.
Categories of products in Woocommerce have support to upload images.
<img src="http://i.imgur.com/y6znNZL.jpg" alt="" />
I guess it's a good idea to include the option to display the category image on this widget.
Let me know if you need more info.
Best regards

**Comment by bainternet** [comment]
It should be available in Elementor Pro 2.1 which is currently in beta #4923

Thanks.

**Comment by markusreklambyra** [comment]
Hi, sorry to interupt but how do I achive this in the beta? I can set featured image for products, but not for categories. I can't seem to figure it out. Thank you!

**Comment by bainternet** [comment]
@markusreklambyra 

Thanks for clearing that up,

Well no, currently, its not possible. But Please open a new Feature request and we will look at it.

thanks

**Comment by markusreklambyra** [comment]
@bainternet - Will do that, thank you! :)
