### ISSUE TITLE
enqueue scripts/styles site wide not only on Elementor pages

### ISSUE THREAD

**Issue by mmjaeger** [pojome/elementor#2019]
Hello
I'd like to have e.g. "FontAwesome" available site wide, not only on Elementor enabled pages - however, I'd like to avoid having "FontAwesome" loaded twice into the site.

Could anybody please tell me how to achieve this.

any help is very much appreciated.

Thanks

**Comment by carasmo** [comment]
I make a functions plugin and use this.

https://gist.github.com/carasmo/162ae95af66b99c86c1c851eb17238a2

**Comment by stratboy** [comment]
Good, thank you. Can I ask you the reason of `if ( ! class_exists( 'Elementor\Plugin' ) ) return;` on row 34? Since I'm building some custom pugins for a client, I'm curious. I also dequeued the icons but didn't use that directive.

**Comment by carasmo** [comment]
Good catch. It was unnecessary to use that since I was using the`elementor/frontend/after_enqueue_styles` action.
