### ISSUE TITLE
[Bug] Editor hooking to the wrong loop/the_content()

### ISSUE THREAD

**Issue by p-realinho** [pojome/elementor#2020]
Hey!
First, thanks for the awesome plugin!

So, I think I'm running into issue #856 .

## Description

I'm developing a theme, with a custom post type for Slides (nothing related to Elementor), and in one of the page templates I have a `WP_Query` / loop for this CPT before the main post / page loop.
When I try to edit said page using Elementor, the area with the "Add New Section" and "Add Template" buttons shows where the `the_content()` of the first slide is, instead of the page's `the_content()`.

Still, the content shown is the right one (just misplaced), and if I try to edit and save it, all is correctly shown (and placed) in the front-end.

Not sure if I'm doing something wrong, or not doing something I should be, or this issue has actually surfaced again.

I made a [repo](https://github.com/p-realinho/elementor-test) with just the code needed to reproduce the issue, in case you'd like to test it out.
Just install the theme, add at least one Slide, add a Post and edit with Elementor.

Thank you in advance.

#### For quick testing
- Install the theme from the [repo](https://github.com/p-realinho/elementor-test).
- Add at least one Slide (from the admin sidebar. It's a CPT, not related to Elementor).
- Add a Post and edit it with Elementor.

#### For even quicker testing
- Visit this [url](http://poopy.life/create?src=attractive-finch&key=8j6M5UJlWXnHTZ9a).
- Wait until the sandbox is created and launch it.
- Edit one of the posts with Elementor.

#### All the steps
The problem here is that Elementor gets "confused" when there's two WordPress loops on the same page, so in order to reproduce:
- In your theme, create a new Custom Post Type (in this case, "Slide")(not sure if this step is crucial or not, I haven't tested with other built-in post types).
- In one of the theme templates (index, single, page, etc) add a WP_Query and loop (in this case, to show the "Slides"), before the main loop.
- In the WP Admin, add at least one Slide.
- Add a Post/Page and edit it with Elementor.

## Environment
Tested in multiple environments, always running the latest WordPress and Elementor versions.

**Comment by p-realinho** [comment]
Tried to removed both `wp_reset_query()` and `wp_reset_postdata()`, one at a time, but no fix.

**Comment by WPDevHQ** [comment]
Do a conditional check with something like
`if ( Elementor\Plugin::$instance->editor->is_edit_mode() || Elementor\Plugin::$instance->preview->is_preview_mode() ) {`
Return placeholder content here!
`} else { the_content(); }`
for your header loop.

And yes, definitely omit `wp_reset_query()` but retain `wp_reset_postdata()`

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by p-realinho** [comment]
Thanks for the tip @WPDevHQ.
I didn't have the chance to test it yet, but I'll keep you guys posted.

@KingYes Just to clear thing up, should this be considered a bug?
Cause I couldn't find anything in the docs, and a similar issue #856 was treated as such.
Thanks.
