### ISSUE TITLE
style.css doesn't always override elementor's css in editor view

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#2025]
Hi, when in the editor view (/my-page/?elementor), not all of my custom css styles are going to override elementor's one. 
I mean, all works fine on the frontend. Instead, on the editor view, some of the properties/edits/overrides (even simple ones like margins) written in /my-theme/style.css are not always visible.
This implies that even if I know that they will be perfectly honored in frontend, the elementor end user (read: my client..) doesn't have a real preview while editing the page, and can be quite disoriented, believing there's something wrong.

I took a look to the page source, I can't see WHERE (or when) style.css is written, in fact I cannot find it. It should be written after elementors styles. First elementor, then the theme.

Is there a way to fix this issue?

**Comment by arielk** [comment]
We made some changes to the editor's loading in the upcoming version, please try using the beta version and let me know if this fixes your problem: https://github.com/pojome/elementor/issues/2077

Feel free to reopen the issue and we'll be happy to help you further.

**Comment by stratboy** [comment]
Hi @arielk I've got latest elemento pro on latest wp, and still have this issues.

**Comment by stratboy** [comment]
Ok I'm closer to the issue. On the preview frame you are writing a somewhat cached version of theme/style.css. I can see my edits only after re-saving elementor's advanced settings. I have ro re-save them every time I want to see my new css ruels on elementor's editor preview.

This is not desiderable: it should be enough to refresh the browser just like a live site.

**Comment by stratboy** [comment]
Again on this topic: sometimes, totally randomly, overrides don't get written even after re-building css via elementor's advanced settings. You should make a more reliable system, because currently there's no way to ensure the admin user will see a real reflection of the end user site.
