### ISSUE TITLE
Feature Request: Hotkey to exit Elementor

### ISSUE THREAD

**Issue by gahawkey** [pojome/elementor#2028]
The existing hotkeys for saving, previewing, mobile view switching etc. are great.

It would be awesome to have an additional one for exiting the Elementor interface and staying on the same page/post in the same tab.

I suggest the hotkey of Ctrl/CMD + Shift + E (for exit).

Not that it's a comparison, but Divi has a similar one and it's been super handy :)

Cheers!

**Comment by drank** [comment]
I would second that. The current hotkeys are great but since exiting Elementor is happening quite often (although with reluctance :) ) I would be happy to have a hotkey for that as well.

Best regards,
Drago

**Comment by arielk** [comment]
More Keyboard Shortcuts #3526

**Comment by shilo-ey** [comment]
This enhancement has been added in [Elementor v2.3.0](https://elementor.com/blog/introducing-finder/)



Thank you for your feedback
