### ISSUE TITLE
How to disable widgets?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#2030]
Hi, is it possible to disable/hide some widgets? This would be to give my clients only the tools they really need based on my custom themes.

I generally find myself teaching the clients only 4 or 5 widgets, the others are very often useless, because we use elementor only to solve certain editor content layout problems otherwise not possible with the default wordpress editor.

So it would be great if I could present my clients only the tools they need, so they don't have to search for the widgets up and down the toolbar.

**Comment by KingYes** [comment]
Use `elementor/widgets/widgets_registered` action to remove unused widgets..

**Comment by stratboy** [comment]
Could you maybe post an example? Docs are not explicit about this specific task.

**Comment by stratboy** [comment]
Ok this code works for default widgets:

``` php
global $elementor_widget_blacklist;

// can find full list in elementor/includes/managers/widgets.php > _init_widgets()
$elementor_widget_blacklist = [
  'heading',
  'icon',
  'icon-box',
  'alert',
  'audio',
  'sidebar'
];


add_action('elementor/widgets/widgets_registered', function($widgets_manager){
  global $elementor_widget_blacklist;

  foreach($elementor_widget_blacklist as $widget_name){
    $widgets_manager->unregister_widget_type($widget_name);
  }
});
```

Still, can't find a way to selectively disable elementor pro widgets.

**Comment by stratboy** [comment]
`$widgets_manager->unregister_widget_type` doesn't work for elementor pro widgets. How to?

**Comment by stratboy** [comment]
Ok done even for Elementor Pro widgets. Still can't hide the Wordpress ones form elemento editor. How to?
