### ISSUE TITLE
Feature Request: Social Icons Widget, Official Color on Icon Hover, while custom on Icon.

### ISSUE THREAD

**Issue by luckydux** [pojome/elementor#2032]
Currently, if the Icon is set to Custom Color then Icon Hover must also be Custom (albeit it could be a different custom color but it applies to all icons).  Instead, I suggest that the Official Color or Custom Colors for Icon and Icon Hover be independent settings from one another.

Taking Elementor.com page as an example.  The social icons are custom dark gray but imagine that when hovering over YouTube, it turned red, but all the other icons remained as custom dark gray.  That is what I'm trying to accomplish on my site without coding.    

Attached are screen shots.

Thank you for your consideration and a such a great product 

[Elementor Social Icon Widget Enhancement Request.pdf](https://github.com/pojome/elementor/files/1156160/Elementor.Social.Icon.Widget.Enhancement.Request.pdf)

**Comment by ShadowXVII** [comment]
+1

The "Colour" property for the icons should be available at the Icon Hover level also.
