### ISSUE TITLE
Get setting outside the widget class

### ISSUE THREAD

**Issue by oceanwp** [pojome/elementor#2034]
Hello, I have a small question, it is possible to get a widget setting outside the widget class?
I created a custom widget who need ajax and I need some settings outside the class to put in the ajax function.
It is possible?
Thanks a lot :)

**Comment by WPDevHQ** [comment]
I've been scratching my head on this one too!

**Comment by IronLady** [comment]
You can encode the settings into a json string and use it as data attribute where you can get the object easily using js.

**Comment by oceanwp** [comment]
Hello @IronLady, Thanks for this but I want to get the settings in my PHP function not JS :)

**Comment by WPDevHQ** [comment]
@oceanwp - This might help point you in the right direction, although I'm still trying to get my head around the concept :)

https://github.com/dtbaker/stylepress/blob/master/extensions/email-subscribe/email-subscribe.php#L32 - that's how David is pulling in the Element settings for the mailchimp module!

**Comment by oceanwp** [comment]
Thank you Zulfikar, I'll check that :)

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by oceanwp** [comment]
Hello @KingYes, sorry I was busy with something else. Unfortunately, I have not managed to make it work. Have you a solution?
Thanks a lot :)
