### ISSUE TITLE
[Features Request] Add more controls Multicheckboxes, autocomplete

### ISSUE THREAD

**Issue by wpaholic** [pojome/elementor#2035]
It would be great if you guy can add these fields in the next versions since these controls are really useful. 

For example:

Autocomplete control: if you have ever used Visual Composer, it has autocomplete field to retrieve post ids, category/tag ids or custom taxonomies ids, so we don't have to manually look for IDs and go back to Elementor to enter.

Multicheckboxes allows us to store more than one value. As in [my previous ticket](https://github.com/pojome/elementor/issues/2013#issuecomment-316264819) i can create my own multiselect control but it would be better if multicheckboxes is added.

Thanks

**Comment by bainternet** [comment]
@wpaholic 

You can create any kind of control you can think of, simply follow the [ creating a new control](https://developers.elementor.com/creating-a-new-control) developers guide.

thanks for the suggestions.
