### ISSUE TITLE
Image gallery border issue.

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#2046]
If you set a border color or set it to none it does nothing. This issue is here since forever, I don't think is hard to fix.

Video of the issue: https://youtu.be/_8GgMR87kww

Is there a way to create a symmetrical spacing on both vertical and horizontal?

**Comment by arielk** [comment]
It looks like the theme (or other plugin) override the border properties from Elementor.

Can you please share with us the link to page with the problem?

**Comment by dudaster** [comment]
gym.1002.ro

**Comment by arielk** [comment]
As I thought, there is another code that overrides what you are designing with Elementor, see screenshot:
![ovver](https://user-images.githubusercontent.com/1778512/28717546-ef2a9c38-73aa-11e7-86ec-bc5ee8690f0f.png)

Try turning off other plugins, as well as switching to a default theme and checking to see if it fixes the issue.

Note, don't forget to set the border width of the image, for example 5px

Thanks

**Comment by dudaster** [comment]
Believe me is not a plugin that does that. It's Wordpress core itself that does that. 
It's a common known Wordpress problem:

https://wordpress.org/support/topic/remove-borders-from-gallery-images/
http://wpcrux.com/blog/wordpress-default-gallery-css/
https://amethystwebsitedesign.com/remove-border-on-wordpress-gallery-images/

P.S. It's a simple fix. Please don't dismiss it.

**Comment by dudaster** [comment]
selector .gallery a img { border: 0 !important; } would remove the border for example. so basically you need to add the !important at the end of the css line.

**Comment by arielk** [comment]
We prefer do not to add anything like this to all of our users.

The solution is shown in the [link above](http://wpcrux.com/blog/wordpress-default-gallery-css/). You can enter the following code into the functions.php file in your child theme:
`add_filter( 'use_default_gallery_style', '__return_false' );`

Thanks

**Comment by andrewmaney** [comment]
Sorry arielk, but dudstar's correct. Your plugin (Gallery Widget) is no longer fully compatible with the WordPress core.

You need to include this filter in your plugin (even if it's just a switch to activate this filter), so customers (I have a PRO licence) can use your gallery widget as expected. You would not be "adding anything", just fixing a bug that currently stops people being able to use your product as intended.

Thanks.

**Comment by evabrands** [comment]
Same issue here. This hasn't been fixed yet, right?

**Comment by dudaster** [comment]
Elementor support is a JOKE and it will be Elementor's demise! 
This Widget is almost useless.
A year has passed and there's no fix...

**Comment by raulillana** [comment]
Crazy this isn't resolved… :\

**Comment by philmatt** [comment]
+ 1
need a fix for this ASAP

**Comment by GH-RPDN** [comment]
Using Astra, E-Pro, Woocommerce ... same issue.
Why is this not resolved yet?

**Comment by winteliu** [comment]
The caption below the picture can be solved with this method

.gallery-caption {
border: none!important;
}

**Comment by Naaktgeboren** [comment]
> .gallery-caption {
> border: none!important;
> }

I concur this method works also in my case, which is elementor + astro theme + starter template + elementor free image gallery, many many thanks to @winteliu
