### ISSUE TITLE
[Feature Request] Discussion widget

### ISSUE THREAD

**Issue by StreathamHill1** [pojome/elementor#2049]
I'd like to see an Elementor discussion widget. It would allow the design of a customisable comments section on individual pages and posts. It would also avoid the need to use the one in whichever native wordpress theme you are using. These inevitably look out of place and jarring at the bottom of an amazingly designed Elementor page.

Thanks!

Francis

**Comment by arielk** [comment]
Done for Pro v1.11: https://elementor.com/single-post-widgets/

Thanks for your feedback!
