### ISSUE TITLE
Custom templates libraries

### ISSUE THREAD

**Issue by jorgebarrero** [pojome/elementor#2050]
Thanks for creating Elementor. Very good tool. We included it in our site (Pro version) and the objective of this page is that every subscriber designs his or her own profile page with Elementor. But we have found some issues:

1. The custom templates can not be created, assigned or administrated on a per user base.
2. Should have a way to make templates with thumbnails (just as shown on the main template Area)
3. Should have a way to make collections of several templates in a package (a whole site for example)
4. It would be nice if our subscribers could start giving back and create a huge template library to share.

Please comment this request.

**Comment by bainternet** [comment]
@jorgebarrero 

1) Not sure this will ever be implemented by us.
2) We are thinking about a way to save a thumbnail on save action. (tricky to do.)
3) Can already be done, select the templates you want and export them at once.
4) Maybe in the future, but not anytime soon.

thanks for the suggestions and feedback.
