### ISSUE TITLE
Issue with custom CSS ID and Classes in Advanced Button Editor

### ISSUE THREAD

**Issue by salsa-system** [pojome/elementor#2051]
## Description

When adding a custom CSS ID or CSS Class in the Advanced Button Editor, it looks like it's applied at the wrong `<div>` level. Example with `my-custom-css-id`:

```
<div data-id="c7v4m36" class="elementor-element elementor-element-c7v4m36 elementor-align-center elementor-widget elementor-widget-button" id="my-custom-css-id" data-element_type="button.default">
	<div class="elementor-widget-container">
		<div class="elementor-button-wrapper">
			<a class="elementor-button elementor-size-lg elementor-animation-grow">
				<span class="elementor-button-content-wrapper">
					<span class="elementor-button-text">Button text</span>
				</span>
			</a>
		</div>
	</div>
</div>
```

The `<div data-id="c7v4m36">` is as wide as the section width, that means that `my-custom-css-id` is applied on all the section element width, when it should be applied only on the button.

## Steps to reproduce

On my website I am currently using a lightbox custom CSS ID trigger with the Elementor Button, the area on the left and on the right of the button is clickable, and it should not.

You can test il live here moving the mouse on the left and on the right of the "Get a free quote for a new website" button.

https://salsa-system.com/wordpress-website-creation/

**Comment by arielk** [comment]
Sorry, but this is not possible, because there are widgets with several elements and we can't insert a custom class for every element in the widget.

Thanks for your feedback!
