### ISSUE TITLE
Page Settings Hook no longer works in 1.5 +

### ISSUE THREAD

**Issue by ryanlabelle** [pojome/elementor#2053]
## Description

Page Settings Hook no longer works in 1.5 +

Using your example here: https://github.com/pojome/elementor/blob/master/docs/content/controls/page-settings.md#adding-a-new-settings

When I roll back to anything pre 1.5 everything works. Looking into it more but maybe someone has some help. Thanks!

## Steps to reproduce

Try adding your example to any version > 1.5 (https://github.com/pojome/elementor/blob/master/docs/content/controls/page-settings.md#adding-a-new-settings)

## Environment

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.23 (Unix) PHP/5.6.28 LibreSSL/2.2.7
	MySQL version: 5.7.16
	PHP Version: 5.6.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Debug Mode: Active

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.5.5
		Author: Elementor.com

	Kirki Toolkit
		Version: 3.0.9
		Author: Aristeides Stathopoulos

**Comment by kobizz** [comment]
Hi @ryanlabelle,
As you mentioned, since 1.5.0 the page settings hooks was changed from `elementor/element/page-settings`... to `elementor/element/page-settings-{ID}`...

We now updating our docs as you can see [here](https://github.com/pojome/elementor/pull/2065/commits/368810fa5cd07d26bd53364f5e4efbd94fba05a4).

Sorry about your inconvenience, i hope that will not happen again.

**Comment by ryanlabelle** [comment]
Awesome! Thank you.

**Comment by ryanlabelle** [comment]
Thanks @kobizz , one question, get_the_ID(); is not available outside of the loop so the action is limited to where it can be used. Where do you recommend I place the new example? Do I need to extend the page setting class?

**Comment by ryanlabelle** [comment]
Also, wondering what release do I find the solution that allows the old hook to work? I've got several page settings that aren't working at the moment and I would love to get them back. Thanks @kobizz  :)
