### ISSUE TITLE
Is it possible to add custom field in widget?

### ISSUE THREAD

**Issue by chayaneng** [pojome/elementor#2054]
I am developing a new addon in my plugin. But I have come across point in where I need to customize an existing field. I was adding a link to an image using `Controls_Manager::URL`. There I can see two show external fields to open new tab and nofollow check box. 

I searched that options are coming from elementor/includes/controls/url.php file. I know if I add codes, that won't wise you know that.  I am trying to add more fields there such as checkbox or anything. Is there any way to add more fields overriding class `Control_URL` or any way?

**Comment by KingYes** [comment]
Do you need to update control fields?

**Comment by chayaneng** [comment]
I want to add more fields in url controls field. Show External true has two fields 1.nofollow link and 2. open new tab. There I want one more filed such as Select field having some options. So how can I add that select filed under the open tab without touching the elementor main plugin?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future.

Thanks for the feedback.
