### ISSUE TITLE
Custom Settings Section?

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#2055]
Hello team Elementor,

I'm in need of some pointer/docs on (if possible at all) adding a custom settings section to the Settings Panel!

Basically what I'm asking for is how to add a section similar to that of the Page Settings - hope you guys can point me in the right direction if the ability to do such an addition is built :)

**Comment by ryanlabelle** [comment]
The devs just updated their example of how to hook into the Settings Panel here: 

https://github.com/kobizz/elementor/blob/368810fa5cd07d26bd53364f5e4efbd94fba05a4/docs/content/controls/page-settings.md

but I think they made it backwards compatible in the updated 1.5.6 branch, so you could also try the old way here:

https://github.com/pojome/elementor/blob/master/docs/content/controls/page-settings.md#adding-a-new-settings

**Comment by ryanlabelle** [comment]
@WPDevHQ have you been able to get this to work? I'm finding that the get_the_ID() is not useable because I'm adding page setting options in the admin (plugin or functions file), and post id is not available outside of the content loop.

**Comment by WPDevHQ** [comment]
No not yet @ryanlabelle - and thank you for the links.

However, what I'm trying to achieve is add a "new" settings block rather than hook into an existing one - so right underneath the "Page Settings" block I want to have a "My Settings" block specific to my plugin/theme!

**Comment by ryanlabelle** [comment]
Have you tried extending the Page Class?

https://github.com/pojome/elementor/blob/d0165ddaa781f1c30aa07dc4a648401d10be232c/includes/page-settings/page.php

**Comment by WPDevHQ** [comment]
Been trying to extend the Controls_Stack itself and hadn't thought of the Page Class - going to dig in this week and see what can be done :)

**Comment by WPDevHQ** [comment]
@arielk / @KingYes - looking at the classes_map for the autoloader, how would this `'PageSettings\Manager' => 'includes/page-settings/manager.php',` work if the location has been moved to core?

I'm still trying to figure out how General is loaded so any pointers will be appreciated 👍

**Comment by kobizz** [comment]
Hi @WPDevHQ,
You can add a new settings block by doing something like the following:

Assuming you want to add a new section after the first 'Page Settings' section:

```php
function add_new_page_settings_section( \Elementor\Core\Settings\Page\Model $page_model ) {
	$page_model->start_controls_section(
		'my_custom_section',
		[
			'label' => __( 'My Custom Section', 'my-domain' ),
			'tab' => \Elementor\Controls_Manager::TAB_SETTINGS
		]
	);

	$page_model->add_control(
		'my_control',
		[
			'type' => \Elementor\Controls_Manager::TEXT,
			'label' => __( 'My Control', 'my-domain' ),
		]
	);

	$page_model->end_controls_section();
}

add_action( 'elementor/element/page-settings/section_page_settings/after_section_end', 'add_new_page_settings_section' );
```

**Comment by WPDevHQ** [comment]
Thank you @kobizz - this works fine on adding a "Controls Section" to the existing "Section".

However, what I'm looking for is to a Top Level Section similar to the newly introduces "Global Settings" with my own controls in it!

Possible?

**Comment by ryanlabelle** [comment]
@WPDevHQ - Where did you place @kobizz 's example? I've got this in my functions file using version 1.5.5. but nothing. I must be missing something.

**Comment by WPDevHQ** [comment]
Doesn't work on v1.5.5 but works on v1.6 RC1

**Comment by ryanlabelle** [comment]
Ah, thanks for that.

**Comment by kobizz** [comment]
Hi @WPDevHQ,

If I understood you correctly, you actually want to add a new settings page to the panel. It's might be a little more complex, but definitely possible.

In short, you should do something which implements the following steps:

- Extending `Elementor\Core\Settings\Base\Manager` and `Elementor\Core\Settings\Base\Model`.
- Adding your new manager to the Elementor system by calling `Elementor\Core\Settings\Manager::add_settings_manager()`.
- Optionally, if you need a custom behavior for your settings on the panel, you can extend the `editor\settings\base\manager` in JS level.

It might be helpfully to take a look at how 'General Settings' doing this steps.

Hope that help.

**Comment by WPDevHQ** [comment]
Thank you @kobizz - going to give this a shot :)
