### ISSUE TITLE
[Bug] Image widget previews do not reflect full size image

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#2057]
## Description

I am running the latest E / E Pro and every time I place a new image inside an Image widget, only the low-res image appears in the editor. If I switch between other thumbnail sizes (eg full) nothing changes. 

![image](https://user-images.githubusercontent.com/1435638/28499493-8b71546e-6ff6-11e7-90be-3dac07bd1486.png)

## Steps to reproduce

1. Drag a new Image widget to a section in the editor
2. Click "Edit image" and select a hi-res image
3. Wait for the results

## Environment

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.0.31
	PHP Version: 7.1.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	Site URL: https://drawcard.com.au
	Home URL: https://drawcard.com.au
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%
	Language: en-AU
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Drawcard 2017
	Version: 9.0.0-beta.2
	Author: Roots
	Child Theme: Yes

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

== Active Plugins ==
	dflip
		Version: 1.2.8
		Author: Deepak Ghimire

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.5.5
		Author: Elementor.com

	Elementor Pro
		Version: 1.5.6
		Author: Elementor.com

	Enable Media Replace
		Version: 3.1
		Author: Måns Jonasson

	EWWW Image Optimizer
		Version: 3.5.1
		Author: Shane Bishop

	GitHub Updater
		Version: 6.3.5.7
		Author: Andy Fragen

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.1.1.1
		Author: Alin Marcu

	OnePress Image Elevator
		Version: 2.5.8
		Author: OnePress

	Pods - Custom Content Types and Fields
		Version: 2.6.10
		Author: Pods Framework Team

	Really Simple SSL
		Version: 2.5.19
		Author: Rogier Lankhorst

	Regenerate Thumbnails
		Version: 2.2.6
		Author: Alex Mills (Viper007Bond)

	Sunshine Photo Cart
		Version: 2.5.20
		Author: Sunshine Photo Cart

	SVG Support
		Version: 2.3.10
		Author: Benbodhi

	Theme Check
		Version: 20160523.1
		Author: Otto42, pross

	TinyMCE Advanced
		Version: 4.6.3
		Author: Andrew Ozz

	Wordfence Security
		Version: 6.3.14
		Author: Wordfence

	WP-Optimize
		Version: 2.1.1
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Featherlight
		Version: 1.1.0
		Author: WP Site Care

	WP Hotjar
		Version: 0.0.1
		Author: Thiago Guimarães

	WP Sync DB
		Version: 1.5
		Author: Sean Lang

	WP Sync DB Media Files
		Version: 1.1.4b1
		Author: Sean Lang

	Yoast SEO
		Version: 5.0.2
		Author: Team Yoast

== Must-Use Plugins ==
	WP Sync DB Compatibility
		Version: 1.0
		Author: Sean Lang

== Debug ==
	Errors: 
		TypeError: Cannot read property 'removeClass' of undefined
			at https://drawcard.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.4 - 5:11873
			2017-07-18 05:19 +00:00
			x 2 times

		TypeError: Cannot read property 'removeClass' of undefined
			at https://drawcard.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.2 - 5:11873
			2017-07-07 02:45 +00:00

		ViewDestroyedError: View (cid: "view706") has already been destroyed and cannot be used.
			at https://drawcard.com.au/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2017-07-07 01:32 +00:00

		TypeError: Cannot read property 'removeClass' of undefined
			at https://drawcard.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.2 - 5:11873
			2017-07-07 01:31 +00:00
			x 2 times

		TypeError: Cannot read property 'cid' of undefined
			at https://drawcard.com.au/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.5.4 - 2:2458
			2017-06-24 08:56 +00:00

		TypeError: Cannot read property 'cid' of undefined
			at https://drawcard.com.au/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.5.2 - 2:2458
			2017-06-19 08:48 +00:00
			x 3 times

		TypeError: Cannot read property 'cid' of undefined
			at https://drawcard.com.au/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.4.2 - 2:2458
			2017-05-08 01:32 +00:00
			x 3 times

		TypeError: Cannot read property 'getActiveControls' of undefined
			at https://drawcard.com.au/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.4.5 - 2:5357
			2017-05-08 01:02 +00:00
			x 6 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://drawcard.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.5 - 2:31401
			2017-05-08 00:20 +00:00
			x 3 times

**Comment by drawcard** [comment]
I've also just tried rolling back E / E Pro to v1.4, and switched themes - I am still having the same problem. Is it something to do with Wordpress / Plugins / GD / ImageMagick I wonder?

![image](https://user-images.githubusercontent.com/1435638/28499974-44616988-7000-11e7-99e3-ee5d6d46cc03.png)

**Comment by arielk** [comment]
Does this happen to you in all images or only in a specific one?

Have you tried turning off plugins and switching to a default theme?

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by drawcard** [comment]
Thanks. I'm in the process of rebuilding the template so I'll post here again if I notice the problem reocurring.
