### ISSUE TITLE
[Feature Request] Link to dropdown box

### ISSUE THREAD

**Issue by dabouncer071** [pojome/elementor#2058]
Is there a chance Elementor  can have another option in the Dropdown box of all elements that use a "Link to" option.

This choice would be to show all pages in the current website in another dropdown box, it then stores maybe the page id value and when adding the link to the page have it create the full http: link.

So Elementor would store page id 34 but would output the text http://website.com/doughnuts/ to the webpage.

Regards,
Paul.

**Comment by arielk** [comment]
I try to understand it correctly, do you have a demo of this idea in WordPress (plugin or something else)?

**Comment by dabouncer071** [comment]
Hi

An example can be got from siteorigins page builder button option. I have
attached an image which shows i clicked the contacts page but it logs the
id of that page to dynamically create the link later.

This works better as you can port a test site to live and not worry links
going to wrong addresses.

I hope this helps

**Comment by arielk** [comment]
Where is the screenshot?

**Comment by dabouncer071** [comment]
Hi,
It should have been attached.....  but here is a linkto the image via dropbox https://www.dropbox.com/s/tu06m5tqy66umn5/Screenshot_2017-07-29-08-06-03.jpg?dl=0
Thak you for your time on this.
Kind regards,Paul.

Sent from Samsung tablet

-------- Original message --------

**Comment by dabouncer071** [comment]
Hi all,
Is there any further thoughts to this one?

**Comment by arielk** [comment]
I merged this issue with another issue #255 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
