### ISSUE TITLE
ACF Widget fields not rendering in Elementor

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#2059]
Not sure if this is already known but currently ACF Widget fields will not render within Elementor, they output within the standard WP widget area however. Are there plans to support this?

Thanks!

**Comment by arielk** [comment]
Can you explain please what is mean ACF widget, plugin?

**Comment by enkota** [comment]
@arielk Apologies, so I am displaying ACF fields in a normal WP widget I've created. When adding this widget via the elementor editor, the ACF fields will not display. 

Default widget page
<img width="323" alt="screen shot 2017-07-28 at 19 23 23" src="https://user-images.githubusercontent.com/13979799/28731089-6a30ae4e-73ca-11e7-9f71-65ef043e8c74.png">

Elementor editor
<img width="295" alt="screen shot 2017-07-28 at 19 24 12" src="https://user-images.githubusercontent.com/13979799/28731102-745538ea-73ca-11e7-8382-eecab38994de.png">

**Comment by arielk** [comment]
Can you please share with us the code of your widget?

**Comment by enkota** [comment]
Sure could do, but just done some further testing.

1. Create new text field in ACF that will display in the default WP text widget.
<img width="927" alt="screen shot 2017-07-30 at 09 23 43" src="https://user-images.githubusercontent.com/13979799/28751821-259870ce-7509-11e7-8762-b166b3b6720a.png">

2. Go to widget area to check it appears.
<img width="463" alt="screen shot 2017-07-30 at 09 23 11" src="https://user-images.githubusercontent.com/13979799/28751824-2c58a2da-7509-11e7-87d1-59e12bc6d927.png">

3. Go to Elementor editor and drag in the WP text widget. No field appears. I believe it could be related to how ACF render fields outside the widget area.
<img width="798" alt="screen shot 2017-07-30 at 09 24 10" src="https://user-images.githubusercontent.com/13979799/28751827-355dac40-7509-11e7-995d-85aa114732b5.png">

**Comment by nicooprat** [comment]
Can confirm it doesn't work. Using Wordpress 4.8, ACF Pro 5.6 and Elementor 1.5.5. No error in PHP or JS console. ACF compatibility would be the killer feature! I'd like to use it to create custom components in a easy way (instead of creating them using Elementor API).

**Comment by MaskaZan** [comment]
@nicooprat +1

**Comment by NailKhalimov** [comment]
@nicooprat +1

**Comment by ShialMeth** [comment]
@nicooprat ++ acf+elementor for the win

**Comment by enkota** [comment]
hey @arielk should we maybe merge with this ticket to consolidate ideas about custom fields rendering in widgets? - https://github.com/pojome/elementor/issues/1071

**Comment by arielk** [comment]
I think it’s a bit differentת this issue relates to compatibility with ACF, in order to build a new widget for Elementor under WordPress widgets, but the other issue is for adding a custom field into existing widgets.

**Comment by enkota** [comment]
@arielk I see! Okay no worries, keep us updated if you need any further testing with ACF. Thanks!

**Comment by ffoodd** [comment]
FWIW I managed to show ACF fields in Elementor by adding:
```php
do_action_ref_array( 'in_widget_form', array( &$instance, null, $this->get_settings( 'wp' )  ) );
```
right after ``$instance->form()` in [`includes/widgets/wordpress.php` at line 145](https://github.com/pojome/elementor/blob/67ddcf242e675b328f1bdd9b3cd0c2f83720c76e/includes/widgets/wordpress.php#L145).

Doesn't work for any reason, ACF scripts aren't loaded I think but I don't have time to search anymore.

Hope it'll help someway.

**Comment by bainternet** [comment]
In Elementor Pro v2 we added partial support for ACF integration, as for ACF WordPress native widget, it's not something we can change or update, it has to come from the 3rd party plugin author.

thanks for the suggestions.

**Comment by imadeel96** [comment]
> FWIW I managed to show ACF fields in Elementor by adding:
> 
> ```
> do_action_ref_array( 'in_widget_form', array( &$instance, null, $this->get_settings( 'wp' )  ) );
> ```
> 
> right after `$instance->form()` in: https://github.com/pojome/elementor/blob/67ddcf242e675b328f1bdd9b3cd0c2f83720c76e/includes/widgets/wordpress.php#L145
> 
> Doesn't work for any reason, ACF scripts aren't loaded I think but I don't have time to search anymore.
> 
> Hope it'll help someway.

Where to add that do_action_ref_array code in WordPress?
