### ISSUE TITLE
Elementor in wordpress categories

### ISSUE THREAD

**Issue by JuanFcoRomero** [pojome/elementor#2061]
Hello,

I tried to edit wordpress categories with Elementor but I can't. I think it will be a very demand new feature in Elementor for wordpress users. I will love see it!

(Posts > Categories and editing de Categori with Elementor)

**Comment by chemocool** [comment]
Juan, you should try creating new section with elementor (Elementor > My library > Add New).

Then using it's shortcode [elementor-template id="00000"] inside a Wordpress Template.

You could open for Example category_blog.php and add 
<?php
    echo do_shortcode( ' [elementor-template id="00000"]' );
?>

That's what i did also for my site footer... its included in the main template using a shortcode, it works really good.

**Comment by bainternet** [comment]
closing in favore of #3826 

thanks everyone.

**Comment by ninjajs** [comment]
So is the category description field now editable with Elementor Pro? I'm using the latest version of Elementor (2.4.1) but I don't see a way to edit the category description using Elementor.
