### ISSUE TITLE
[Feature Request] Portfolio widget as a slider

### ISSUE THREAD

**Issue by boostercb** [pojome/elementor#2064]
Hi, is there any way to accomplish turning the portfolio widget into an image gallery slider? I'd love to have 4 columns show thumbnails that link to individual video pages, but if I have more than 4 videos in a category, I'd love for them to slide over like the Image Carousel widget instead of load as masonry. Any good way to make this happen? Thanks!

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/pojome/elementor/issues/1299 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
