### ISSUE TITLE
[Feature Request]  Reverse column on tablet

### ISSUE THREAD

**Issue by dam62500** [pojome/elementor#2070]
Hello,

I think it's a good features to allow reverse columns for tablets like mobile feature.

**Comment by mmjaeger** [comment]
+1

**Comment by pingram3541** [comment]
Is it shameful for me to put a bump on this one?  It seems like a simple thing to implement no?

**Comment by vongoh** [comment]
+1

**Comment by dam62500** [comment]
Any news about that? I need to invert the columns even on tablet and I'm not the only about that. I think that'll be a good features :)

**Comment by breizhwave** [comment]
just perfect solution   @dam62500

**Comment by black-eye** [comment]
+1

**Comment by denishacquin** [comment]
+1
