### ISSUE TITLE
tabs/accordion and bookmarks

### ISSUE THREAD

**Issue by mmjaeger** [pojome/elementor#2071]
Hello
I was wondering whether it is possible to have a link that would open a specific tab or accordion panel?

thanks

**Comment by casperroux** [comment]
Just what I am looking for....... Currently using Visual Composer for this

**Comment by mmjaeger** [comment]
@casperroux 
this little function does the trick:
`// open specific tab based on hash tag
	function _toggleTabs() {
		
		var url = document.URL;
		var tab = url.split( '#' )[1];
		if ( tab == 'undefined' )
			return;
		
		if ( ! $( '.elementor-tabs' ) )
			return;
		
		$( '.elementor-tabs' ).data( 'active-tab', tab );
	}`

**Comment by casperroux** [comment]
Thanks.. do I just add it to my theme 's functions.php ?

**Comment by mmjaeger** [comment]
you need to add it into a javascript file that you load in your functions.php file

**Comment by casperroux** [comment]
How would I go about creating this? Could you please assist me
Thanks

**Comment by arielk** [comment]
Sorry, but for now we do not support such an option, thanks.
