### ISSUE TITLE
Share Buttons Alignment at breakpoints

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#2080]
Heyo!

Could you add breakpoint control for the alignment of the Share Buttons element please?

![image](https://user-images.githubusercontent.com/1729832/28598006-59e116d8-71e4-11e7-8883-96d0b70ce00f.png)

Cheers :)

**Comment by arielk** [comment]
Unfortunately we cannot add this option in the near future, it's a bit complicated in the current structure of the code.

But maybe in the future ... so thanks for your feedback!

**Comment by JoelEadeDesign** [comment]
Thanks anyway, @arielk . I managed to work around it by applying some custom css for my situation:
`@media (max-width: 767px) {
	.elementor-widget-share-buttons .elementor-grid {
		justify-content: center;
	}
}`

Just documenting it here for future reference ;)

**Comment by arielk** [comment]
Of course you can using custom CSS, like almost anything :)
