### ISSUE TITLE
Add integration with Mautic for Elementor forms

### ISSUE THREAD

**Issue by luisgennari** [pojome/elementor#2084]

**Comment by arielk** [comment]
Hi

We have documentation for developers on how to integrate with any other service using the API: https://github.com/pojome/elementor/blob/master/docs/content/pro/forms.md

Also, note that you have the option to integrate to any other service (like Zapier) using Webhook, you can learn about it here: https://elementor.com/pro-v140-form-integrations/

Thanks for your feedback!

**Comment by arbex5** [comment]
Hello there.
I see this topic was opened and closed twice. 
Mautic is a leading FREE leading Marketing Automation platform that is very robust.
You guys care about the community and your customers, right? A native integration would be great for everyone. If you can't make a native integration, at least show us how can we make it work.

Thanks.

**Comment by amankapoor** [comment]
Hi, please natively integrate the form with Mautic. This would be a great addon. All these ActiveCampaign, Drip and similar companies charge hefty prices whereas the same thing is possible in Mautic and one only needs to pay for hosting and email, which again is available at cheaper prices by few vendors out there, thus making Mautic a great choice.

Close integration with Elementor forms would be a great feature. Kindly look into it.

Thanks

**Comment by dcambria** [comment]
+1 for mautic integration.

**Comment by arbex5** [comment]
> Hi, please natively integrate the form with Mautic. This would be a great addon. All these ActiveCampaign, Drip and similar companies charge hefty prices whereas the same thing is possible in Mautic and one only needs to pay for hosting and email, which again is available at cheaper prices by few vendors out there, thus making Mautic a great choice.
> 
> Close integration with Elementor forms would be a great feature. Kindly look into it.
> 
> Thanks

Hello. I find out a workaround for this issue that is free and don't require technical expertise. 
It's in portuguese but I made it visual. You can also use google trasnslate to help you.

[https://fernandoarbex.com/integrando-o-mautic-com-formularios-do-elementor-e-demais-outros-formularios-de-contato/](url)

Anyway, if you have any issue, just comment that I try to help you.

**Comment by verygoodplugins** [comment]
We support sending Elementor forms to Mautic with WP Fusion. Here are the details: https://wpfusion.com/documentation/lead-generation/elementor-forms/

**Comment by Paras16699** [comment]
+1

**Comment by lucashassuike** [comment]
+1

**Comment by MonikaHodkinson** [comment]
> > Hi, please natively integrate the form with Mautic. This would be a great addon. All these ActiveCampaign, Drip and similar companies charge hefty prices whereas the same thing is possible in Mautic and one only needs to pay for hosting and email, which again is available at cheaper prices by few vendors out there, thus making Mautic a great choice.
> > Close integration with Elementor forms would be a great feature. Kindly look into it.
> > Thanks
> 
> Hello. I find out a workaround for this issue that is free and don't require technical expertise.
> It's in portuguese but I made it visual. You can also use google trasnslate to help you.
> 
> [https://fernandoarbex.com/integrando-o-mautic-com-formularios-do-elementor-e-demais-outros-formularios-de-contato/](url)
> 
> Anyway, if you have any issue, just comment that I try to help you.

**Comment by MonikaHodkinson** [comment]
Has this been deleted - I can't find the link - I am new to this and would also like to know how to integrate Elementor with Mautic.  Thanking you

**Comment by MonikaHodkinson** [comment]
> We support sending Elementor forms to Mautic with WP Fusion. Here are the details: https://wpfusion.com/documentation/lead-generation/elementor-forms/

**Comment by arbex5** [comment]
No Sr. The link still up. Try copy and paste.

Em seg, 2 de dez de 2019 09:08, MonikaHodkinson <notifications@github.com<mailto:notifications@github.com>> escreveu:

Has this been deleted - I can't find the link - I am new to this and would also like to know how to integrate Elementor with Mautic. Thanking you

**Comment by MonikaHodkinson** [comment]
Thank you Arbex5 for your help.  

 

I am not a programmer, I am very uneducated in these matters.  I can follow what you are saying all the way to the cPanel and I can log in and add those Cron Jobs.  

 

You then go on to say that you use Bitnami and AWS – if I can add the Cron Jobs do I also need to log in to my server and try to do that – that is the only part I cannot understand.  

 

Thanking you for your help 

Monika
