### ISSUE TITLE
Generated media queries for responsive columns are wrong

### ISSUE THREAD

**Issue by ceap80** [pojome/elementor#2086]
## Description

When adjusting the width size for columns in tablet mode the width are overwrited by the width of the desktop column size

## Steps to reproduce

Set column desktop width to 25%
Set column tablet width to 100%

Expected: Width of column in tablet mode should be 100%
Result: Width is 25%

![selection_052](https://user-images.githubusercontent.com/403520/28623893-46c0a5d6-71e5-11e7-88fd-456a6d444e15.png)
![selection_053](https://user-images.githubusercontent.com/403520/28623901-4ccdb82e-71e5-11e7-9e64-e8399bc55ddd.png)
![selection_054](https://user-images.githubusercontent.com/403520/28623941-78ed967c-71e5-11e7-9217-c12824325deb.png)

![selection_055](https://user-images.githubusercontent.com/403520/28623915-561843cc-71e5-11e7-8442-43f4e37788e4.png)

## Environment

                    
== Server Environment ==
    Operating System: Linux
    Software: Apache
    MySQL version: 5.5.5
    PHP Version: 5.6.31
    PHP Max Input Vars: 5000
    PHP Max Post Size: 64M
    GD Installed: Yes
    Elementor Library: Connected

== WordPress Environment ==
    Version: 4.8
    Site URL: <redacted>
    Home URL: <redacted>
    WP Multisite: No
    Max Upload Size: 64 MB
    Memory limit: 40M
    Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
    Language: en-US
    Timezone: 0
    Debug Mode: Inactive

== Theme ==
    Name: Twenty Seventeen Child
    Version: 1.0.0
    Author: John Doe
    Child Theme: Yes
    Parent Theme Name: Twenty Seventeen
    Parent Theme Version: 1.3
    Parent Theme Author: the WordPress team

== User ==
    Role: administrator
    WP Profile lang: en_US
    User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

== Active Plugins ==
    Elementor
        Version: 1.5.5
        Author: Elementor.com

== Debug ==
    Errors: 
    
        TypeError: Cannot read property 'removeClass' of undefined
            at https://dev1.strawberrytours.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.5 - 5:11873
            2017-07-26 13:03 +01:00
            x 4 times

        TypeError: Cannot read property 'errors' of undefined
            at https://dev1.strawberrytours.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.5 - 5:17840
            2017-07-26 12:58 +01:00
            x 8 times

        TypeError: Cannot read property 'removeClass' of undefined
            at https://dev1.strawberrytours.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.5 - 5:11873
            2017-07-25 22:03 +01:00
            x 2 times

        TypeError: Cannot read property 'removeClass' of undefined
            at https://127.0.0.1/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.0 - 5:11873
            2017-07-05 15:49 +01:00

        TypeError: Cannot read property 'errors' of undefined
            at https://dev1.strawberrytours.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.0 - 5:17833
            2017-06-28 21:33 +01:00
            x 4 times

        TypeError: Cannot read property 'removeClass' of undefined
            at https://dev1.strawberrytours.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.0 - 5:11873
            2017-06-28 21:30 +01:00

**Comment by arielk** [comment]
This problem rarely occurs only in older PHP versions (<7), please update to PHP 7+ and this should work correctly.

**Comment by ceap80** [comment]
Could you elaborate what the issue is? To see if I can workaround this issue. Or at least point me to the right direction?

**Comment by kobizz** [comment]
Hi @ceap80,

You can check this out in `includes/stylesheet.php` in line 258 (as of v1.6.0).

When `$query_hash` is `min_tablet` and it's came before other rules (such as `max_tablet`, `min_mobile` etc.), prior tp php 7 the `uksort` method returns a wrong order.

**Comment by MatthewDVance** [comment]
I'm using PHP7, and this is still an issue.  What else do you got?

**Comment by ceap80** [comment]
@kobizz @MatthewDVance 
The comparisons in here return 0 sometimes (maybe always? I' haven't had the time to test it properly)  

    if ( isset( $a_query['min'] ) ) {
        return $a_query['min'] - $b_query['min'];
    }

And according to the uksort docs: 

> If two members compare as equal, their relative order in the sorted array is undefined.

This definitely seems like a bug. It can work on some versions but can break in another ones.

**Comment by MatthewDVance** [comment]
Any ideas for a work around?  I've got as complicated landing page that is completely broken on tablets and half screen width on a desktop. 

Maybe adding in a "if zero, make it not zero or compare maxes"

**Comment by MatthewDVance** [comment]
This fixed it for me:
```
if ( isset( $a_query['min'] ) ) {
	if($a_query['min'] === $b_query['min']){
		if(isset($a_query['max'])){
			return 1;
		}
		if(isset($b_query['max'])){
			return 0;
		}
		return $a_query['min'] - $b_query['min'];
	}
}
```
It's a little arbitrary, but it at least checks to see if one has a min AND a max... and the one with the max takes priority...  this doesn't take into consideration what to do if they both have a max.  but being as this resolves MY issue, it's good enough for now.

**Comment by perusoa** [comment]
@MatthewDVance @ ceap80 @kobizz I had this same issue and when I tested it on a PHP7 version on my local it works, but the issue is that I have some production sites with this issue and I can't upgrade to PHP 7 just yet, where would I be able to put your recommendations above in order to patch this for a PHP 5.6.x version of a site using Elementor?

**Comment by MatthewDVance** [comment]
> @MatthewDVance @ceap80 @kobizz I had this same issue and when I tested it on a PHP7 version on my local it works, but the issue is that I have some production sites with this issue and I can't upgrade to PHP 7 just yet, where would I be able to put your recommendations above in order to patch this for a PHP 5.6.x version of a site using Elementor?

This issue was apparent in versions prior to PHP7.  I believe I was running PHP6 at the time.  So editing this file as shown should resolve.
