### ISSUE TITLE
web font lazy load

### ISSUE THREAD

**Issue by luizbills** [pojome/elementor#2088]
An option to lazy load web fonts (google fonts and icon fonts) will increase performance and prevent from text blinking on page loading.

### Useful links

- https://www.zachleat.com/web/comprehensive-webfonts/
- https://github.com/typekit/webfontloader

**Comment by bainternet** [comment]
I merged this issue with  #2987  , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by maxwellhibbert** [comment]
Better font loading is really needed. Currently ALL weights of any fonts used are loaded!
