### ISSUE TITLE
(Bug?) Column Background Opacity not working

### ISSUE THREAD

**Issue by formulaclick** [pojome/elementor#2093]
Hi

I want to put a background color / degraded color in a column combined with a background image with an opacity. You can check on first screenshot that in elementor I get just what I want. Fine. But in screenshot 2 you can see what really is rendered on frontend. There are some CSS errors due to commas instead of points. If I edit opacity value with Chrome's Developer Tools and set 0.15 instead of 0,15 then it is displayed fine. Can this be solved?

I'm using last versions of Elementor & Elementor PRO.

![elementor-bug-opacity1](https://user-images.githubusercontent.com/2376672/28681787-fc35aa2c-72fa-11e7-93e4-015d359bb545.jpg)
![elementor-bug-opacity2](https://user-images.githubusercontent.com/2376672/28681788-fc40dc9e-72fa-11e7-9be3-ebe9020afe12.jpg)

Thanks

**Comment by arielk** [comment]
Why in your panel there is a comma instead of point?

Which language are you using?

**Comment by formulaclick** [comment]
I'm using spanish. In Spain decimal numbers are written with comma instead of point. A similar bug happened with image ratio on other widgets. I think this is the problem. It should always appear points. Thanks

**Comment by formulaclick** [comment]
Is this going to be fixed? It id quite annoying :_(

**Comment by arielk** [comment]
We tried to reproduce this bug in our development environment, but we could not.

It's true that you get a comma instead of a dot, but what is kept as a value for the browser is a dot so it still works well for us :(

Do we also need to change the browser language to Spanish to get it?

**Comment by formulaclick** [comment]
With Firefox, if I change Wordpress language from Spanish to English, then automatically appears a point instead of comma in Elementor panel (so it's displayed fine in browser). If I set back language to Spanish, then again appears comma. So it is a WP related bug. 
In chrome, if I change Wordpress language, the comma remains always in Elementor panel, even if I write a point and save.

**Comment by formulaclick** [comment]
Any news on this bug? Is quite annoying. I've created a video with the bug:
https://expirebox.com/download/8aaeac14f3e003235e5c112627ef9c24.html
It happens with every Elementor Widget control field with a number with decimals.

**Comment by arielk** [comment]
Fixed by the support team.

**Comment by milsorm** [comment]
Same behaviour in last version for font-size in em (1,2em). In Czech and Slovak is also decimal comma instead of decimal point.

But in preview (elementor frontend) everything seems fine, only on real web....

**Comment by milsorm** [comment]
What really helps is change Control_Base_Multiple class, method get_style_value, to check, if returned value is_numeric() and if true -> replace decimal comma with decimal point. 

I'll try to add some patch later.

**Comment by milsorm** [comment]
Pull request for this https://github.com/pojome/elementor/pull/2300
