### ISSUE TITLE
Datepicker control NAN bug - Safari browser

### ISSUE THREAD

**Issue by badcat** [pojome/elementor#2095]
The Countdown element resets itself to Zeros via the not a number NaN-aN-aN aN:aN in **Safari 10.1.2** every time it is reselected for editing style. Each time I need to reset the date which the Datepicker dropdown looks like this by default.

![screen shot 2017-07-27 at 5 34 30 pm](https://user-images.githubusercontent.com/26096/28693277-e68425c2-72f1-11e7-94db-9e9bc8bfa23a.png)

This is using Elementor Version 1.5.5 (and even with 1.6.0 rc3) and Pro Version 1.5.8

Seems OK in Chrome and FF.  thanks.

**Comment by chayaneng** [comment]
what would be the solution?

**Comment by phpbits** [comment]
Any solution? I'm getting the same issue. Thanks!

**Comment by phpbits** [comment]
Found it! Digging on Elementor Pro just found out that you'll be needing to change the default date() format and it will work perfectly 👍 

`$element->add_control(
    			'widget_options',
    			[
    				'label' => __( 'Sample DatePicker', 'widget-options' ),
    				'type' => Elementor\Controls_Manager::DATE_TIME,
    				'default' => date( 'Y-m-d H:i' ),
    				'description' => __( 'Checkout Widget Options for WordPress', 'widget-options' ),
    			]
    		);`

**Comment by bainternet** [comment]
Should be fixed in next version.

related PR: https://github.com/pojome/elementor/pull/3006
