### ISSUE TITLE
Dividers - HTTPS for w3.org XMLNS links on SVG elements please

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#2096]
Such a simple thing, but hard coded and bugs for those that are ADHD like me =)

**Comment by arielk** [comment]
Can you explain more?

**Comment by pingram3541** [comment]
@arielk Sorry thought the title said it all.  There are hard coded links in Elementor's html output that are not https when they *could* be.  For example, looking at the shape divider output, each svg has an xmlns attribute with a w3.org url but via http when w3.org fully supports https.

This popped up when using one of the many page rank utilities to scan a site recently built with Elementor and thought I'd mention it since the fix literally breaks nothing.

**Comment by joshmarom** [comment]
Hi Phil.

The xmlns attribute is a namespace for the tags allowed within the SVG.
It only happens to be a url, but it isn't actually a link, it's just a name.
Changing it to https wouldn't make sense.

For more info refer to:
https://stackoverflow.com/questions/39960017/does-svg-xmlns-attribute-value-requires-protocol-can-it-be-https-or-relative

https://www.w3schools.com/xml/xml_namespaces.asp

**Comment by pingram3541** [comment]
Yep, thx @joshmarom - what I didn't know is that changing http to https would actually change the "keyword" name and make it wrong, good catch.

The odd thing is that GT Metrix was reporting this last week as something needing to be fixed but today it is not.
