### ISSUE TITLE
Feature Request - Offset X and Y position for background images by device

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#2097]
The title pretty much says it =)

Can't count how many times I've relied on the trusty custom css in Elementor Pro but would be really cool if we could do it in the UI panel.

**Comment by bainternet** [comment]
I merged this issue with  #2355, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by hufer** [comment]
https://pafe.piotnet.com/ This plugin can do it for you
