### ISSUE TITLE
Feature Request - Apply Style to Anchor - Toggle

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#2098]
So many times I've seen someone on the forums struggle to overcome font and color changes when an element such as heading or text, etc includes anchors and the underlying theme css overrides the desired look.

Those of us w/ the know how can use custom css but its certainly not intuitive for future edits or clients making adjustments, they'll just think it's broken.

![screen shot 2017-07-27 at 11 19 05 pm](https://user-images.githubusercontent.com/319284/28705065-ee9920b0-7322-11e7-9fa1-5fc9d8b64c94.png)

But I had a thought...why not just place a toggle that switches the underlying style selector generated by Elementor to target an anchor as well?

` .elementor-element h2, .elementor-element h2 a { .... }`

` .elementor-element p, .elementor-element p a { .... }`

Of course these are simple examples but the proper selectors would be a tad more authoritative to get the job done (i.e. elementor body class + .. + unique element selector)

The toggle could simply be a check box when an anchor exists, right below the other choices for open in a new window and no follow.

![screen shot 2017-07-27 at 11 20 41 pm](https://user-images.githubusercontent.com/319284/28705142-41bd69cc-7323-11e7-8c66-f669bb7d194c.png)

Or maybe just make it intuitive enough to detect a value in the url/link field and then provide it's own style color/font settings for the "Anchor" in the Style tab?

**Comment by arielk** [comment]
Do you have a specific theme with a problem?

I want to check out what we can do to resolve this.

**Comment by pingram3541** [comment]
Yes, this one in particular was using the free Astra theme. https://wordpress.org/themes/astra/
