### ISSUE TITLE
Reduce DOM Elements & use of CSS GRID

### ISSUE THREAD

**Issue by MaximPro** [pojome/elementor#2100]
Hi, 

Well I saw the progress from elementor since it came out. Great Work Guys!
It really now comes out as one or the best Builder these Days!

However I still used Divi until now, but now I will switch to Elementor. 
Also because I found out how many DOM Elements Divi used and it made my site slow.

1 Thing that made me hesitate to buy the Pro Version or fully go all into Elementor is the following:

https://youtu.be/7kVeCqQCxlk?t=8m31s

WTF - See how many Lines Elementor created ???
Is it still that way?

Also the video explains everything else!

I want to make my Wordpress Site as Fast as Possible.
I already have a LEMP Stack Server with Redis, wich is pretty fast, but I also want the builder to be as fast as possible by embracing new techniques for a better web.

Another Thing I missed on Elementor was the Inline Text Editing, wich is pretty useful... just this on the side.

Here are the Points of this posts, that I would like to bring to your attention!
• CSS GRID
• DOM ELEMENT OPTIMIZATION
• INLINE TEXT EDITING

Please let me/us know about your plans on this!

Thanks and have a great day! :+1: 
Best regards from Germany

**Comment by joshmarom** [comment]
Hello @MaximPro.
Thank you for using Elementor and thank you for your important feedback.

We make every effort to make sure Elementor pages are as quick to load as possible. The way we handle CSS, JS, fonts and other resources loading, are optimized for best speed and performance.

CSS Grid is a very neat new approach for creating web layouts, we will be more than happy to introduce into Elementor once it is properly supported by enough browsers. Unfortunately, it's going to take a little while before we can do that without risking browser compatibility issues.
Additionally, it should be noted, that despite being a great system, CSS grid will have an extremely minimal to no effect on the page loading speed.

Regarding what you refer to as "DOM ELEMENT OPTIMIZATION", I would like to refer you to the answer I wrote back when it was originally posted on #1480 and on [Facebook](https://www.facebook.com/groups/advancedwp/permalink/1435951346467075/):

> I think the way this issue is presented is quite unfair and doesn't accurately reflect the common case.

> First of all, the first 7-8 levels of depth in the screenshot are not related to Elementor anyway. They come from the theme.

> Secondly, the given example is of a more complex layout, using a nested section inside a column - this obviously doubles the depth.

> Now before we make any judgment, we need to have a point of reference - let's take twitter bootstrap as an example: if you had to create a similar structure using bootstrap, you'd end up with something that is pretty close to what you got here. Yes, it would be a little shorter, but not by far, I would guess around 4 tags shorter.

> Obviously, every div in this structure has a reason and plays a role in allowing the user to control various aspects of the design.

> At the end of the day, markup generated by a page builder will never be as minimalist as manual coding, but if you consider the amount of design flexibility and customization options Elementor gives you, I think this is very reasonable.

> Lastly, I would like to remind you that Elementor is an open source project and developers are welcome to contribute. If you have any concrete suggestions on how it may be optimized, we would love to hear them on GitHub.

Regarding "Inline Editing", There is already an open issue on this ( #437 ), you are invited to add your thoughts and ideas about it, there.

Thanks for your feedback.
Josh from Elementor

**Comment by alriksson** [comment]
@joshmarom Isn't reduce DOM elements still relevant?

https://stackoverflow.com/questions/2120953/best-ways-to-reduce-number-of-dom-elements

I think Elementor could have used so much fewer DIVs than you are today. Just by adding the ID or class directly to e.g the H-, span- or p-attributes. Instead of wrapping it into 2 divs and then an H3. That would reduce the DOM elements significantly. And something you guys for sure should elaborate and investigate if you prioritize performance on the front end for the users of Elementor.

**Comment by arielk** [comment]
Ref: https://github.com/elementor/elementor/issues/18839

**Comment by nicholaszein** [comment]
Hello everyone!

We are happy to announce that the first beta implementation of the Grid Container is live! 🙌 

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪 

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards

**Comment by nicholaszein** [comment]
Hello, there everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the first phase of the Grid Container was released with Elementor **v3.13.0**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
