### ISSUE TITLE
Provide names for editing tools and make them reachable via name even when hidden

### ISSUE THREAD

**Issue by cavalierlife** [pojome/elementor#2102]
## FEATURE REQUEST

Many times, the editing tools for sections, columns, or widgets are behind other tools, and are impossible to get to, without changing something else. This may sometimes happen because some elements use negative margins, or some widget elements may be too far to the right of the screen to reach. (Not sure why on that one). In any case, whatever the reason, it would be handy to be able to reach these under any circumstances. I was thinking perhaps something like the following could be implemented:

1. Have the ability to assign a user-friendly unique custom name to each tool, as desired. So perhaps I could assign a name to the outermost section tools area, a separate name for the left column tools, another for the right column tools, etc.

Now that each tool icon set has a name, it would be nice if:

2. There was a list of assigned names I could choose from so that the one chosen would immediately cause that set of tools to take focus and become visible and clickable, even when hidden behind something else.

## Steps to reproduce

1. Make a section that covers the screen, and place a text widget at the bottom of it.
2. Make another section beneath it, and then use a negative margin to place that section above the other at the top. 
3. You won't be able to edit the text widget because it's hidden by the section using the negative margin.

## Environment

N/A
![2017-07-29](https://user-images.githubusercontent.com/28687464/28745739-cc8b8842-7443-11e7-9398-b9764e9ecf92.png)

**Comment by cavalierlife** [comment]
Sorry, I forgot to edit that screenshot to point out the fact that one of the editor tools cannot be seen in the upper right corner.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/pojome/elementor/issues/1165 in the similar  concept so we could deal with it more efficiently. 


Thanks for your feedback!
