### ISSUE TITLE
Button now showing correctly and the icons aren't in the same line with texts

### ISSUE THREAD

**Issue by hanycalan** [pojome/elementor#2107]
## Description

I created a new page by simply using Elementor template, and the buttons and icons aren't showing correctly. Here is the link:http://hanyc.staging.wpengine.com/3234-2/

I couldn't find out what the problem is. 

Could you please help?

Thanks!

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.36
	PHP Version: 5.6.30-1+wpengine8
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	Site URL: http://hanyc.staging.wpengine.com
	Home URL: http://hanyc.staging.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: -4
	Debug Mode: Inactive

== Theme ==
	Name: HANYC
	Version: 1.0.0
	Author: ThemeFusion / SR & VH from ACH
	Child Theme: Yes
	Parent Theme Name: Avada
	Parent Theme Version: 4.0.3
	Parent Theme Author: ThemeFusion

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4

== Active Plugins ==
	Admin Columns
		Version: 3.0.2
		Author: AdminColumns.com

	Autoptimize
		Version: 2.2.2
		Author: Frank Goossens (futtta)

	Contact Form 7
		Version: 4.8
		Author: Takayuki Miyoshi

	Download Manager
		Version: 4.6.7
		Author: Shaon

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.5.5
		Author: Elementor.com

	EventON
		Version: 2.5.5
		Author: AshanJay

	Fusion Core
		Version: 2.0.3
		Author: ThemeFusion

	Google XML Sitemaps
		Version: 4.0.9
		Author: Arne Brachhold

	Paid Member Subscriptions
		Version: 1.4.8
		Author: Cozmoslabs, Mihai Iova, Madalin Ungureanu, Adrian Spiac, Cristian Antohe

	Raw HTML
		Version: 1.5
		Author: Janis Elsts

	Slider Revolution
		Version: 5.2.5
		Author: ThemePunch

	Tabby Responsive Tabs
		Version: 1.2.3
		Author: cubecolour

	Ultimate Member
		Version: 1.3.87
		Author: Ultimate Member

	UserPro
		Version: 4.9.12
		Author: Deluxe Themes

	WP Content Copy Protection & No Right Click
		Version: 1.6
		Author: wp-buy

	WPDM - Button Templates
		Version: 1.2.0
		Author: Shaon

	WPDM - Extended Short-codes
		Version: 2.7.2
		Author: Shaon

	WPDM - Image Button
		Version: 2.3.3
		Author: Shaon

	WPDM - Page Template
		Version: 1.1
		Author: Shaon

	WPDM - TinyMce Button
		Version: 2.7.0
		Author: Shaon

	WPFront Notification Bar
		Version: 1.7
		Author: Syam Mohan

	WP Security Audit Log
		Version: 2.6.5
		Author: WP White Security

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	Stop long comments
		Version: 0.0.4
		Author: WPEngine

	WP Engine System
		Version: 3.2.1
		Author: WP Engine

== Debug ==
	Errors: 
		TypeError: undefined is not an object (evaluating 'elementorFrontend.config.elements.data')
			at https://hanyc.staging.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.4 - 4:6812
			2017-07-27 19:51 +00:00

		TypeError: undefined is not an object (evaluating 'a.ui.triggerButton.removeClass')
			at https://hanyc.staging.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.4 - 5:11873
			2017-07-27 19:46 +00:00

		TypeError: undefined is not an object (evaluating 'elementorFrontend.config.elements.data')
			at https://hanyc.staging.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.4 - 4:6812
			2017-07-27 19:43 +00:00
			x 4 times

**Comment by kobizz** [comment]
Please try to deactivate all other plugins and switch back to the default theme. Then check if the problem still exists.

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
