### ISSUE TITLE
Session Expired message whenever I try to use elementor on multisite.

### ISSUE THREAD

**Issue by suedenning** [pojome/elementor#211]
Starts aver about 30 seconds, no matter where I am. I've tried on two different servers, and had the same issue. System info is below. Any help?

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16
	MySQL version: 5.5.47
	PHP Version: 5.4.16
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes

== WordPress Environment ==
	Version: 4.5.3
	Site URL: https://commons.trincoll.edu/portfolio2
	Home URL: http://commons.trincoll.edu/portfolio2
	WP Multisite: Yes
	Max Upload Size: 98 MB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: Susan.Denning@trincoll.edu
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Sixteen
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

== Active Plugins ==
	Elementor
		Name: Elementor
		Version: 0.4.0
		Author: Elementor.com

== Must-Use Plugins ==
	More Privacy Options
		Name: More Privacy Options
		Version: 3.5
		Author: D. Sader

![screen shot 2016-07-05 at 10 56 43 am](https://cloud.githubusercontent.com/assets/20305257/16594446/6e5ab0b2-42b8-11e6-9f61-eac6038c44ac.png)

**Comment by arielk** [comment]
If you deactivate or remove "MustUse" plugin (More Privacy Options) the error is still there?

**Comment by suedenning** [comment]
I’ll try that – I might not be able to do that until next week when our WP admin is back from vacation. That’s a pretty important plugin for us, so I’d only be able to take it off the test server.

- Sue
—
Sue Denning
Instructional Technologist
Trinity College
LITC 135
book an appointment<http://libcal.trincoll.edu/>

**Comment by suedenning** [comment]
Hey Ariel,

Just deleted the Must Use More Privacy Options plugin from our test server, and I experienced the same “session expired” issue – so there does not appear to be a conflict. Does Elementor need any specific file permissions to work on our side that we should try adjusting?

- Sue
—
Sue Denning
Instructional Technologist
Trinity College
LITC 135
book an appointment<http://libcal.trincoll.edu/>

**Comment by yehudah** [comment]
Maybe I shoot in the dark, but I notice your site url is SSL and home url isn't. Can you copy the value from home url to site url ? Try it WITHOUT SSL in both url's.

**Comment by suedenning** [comment]
Huh – so changing the home url to SSL does seem to fix the problem, but does that introduce other issues with our WP setup?

- Sue
—
Sue Denning
Instructional Technologist
Trinity College
LITC 135
book an appointment<http://libcal.trincoll.edu/>

**Comment by yehudah** [comment]
I don't why it was the decided to make two diffrent url's but I don't THINK any error should happen and if both ur's point to the same location THEY SHOULD MATCH.

Glad the issue fixed !

**Comment by suedenning** [comment]
I’ll check with my server admin when he is back from vacation. Thanks!

- Sue
—
Sue Denning
Instructional Technologist
Trinity College
LITC 135
book an appointment<http://libcal.trincoll.edu/>

**Comment by arielk** [comment]
Hi @suedenning 
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by suedenning** [comment]
Hi - sorry for the late response. Our server admin says there are reasons why the dashboard should be https and the live site should be http. Changing the home site to https works in a pinch, but is there a way to redirect the plugin to use https? I've got many users on a multisite install, so a global fix would be better...

**Comment by arielk** [comment]
OK, As a temp workaround, please try to add this code to your theme functions.php
```
add_filter( 'admin_url', function( $url ) {
    if ( is_ssl() || force_ssl_admin() ) {
        $url = str_replace( 'http://', 'https://', $url );
    }
    return $url;
} );
```

**Comment by suedenning** [comment]
Will do.

- Sue
—
Sue Denning
Instructional Technologist
Trinity College
LITC 135
book an appointment<http://libcal.trincoll.edu/>
