### ISSUE TITLE
Pro Feature request: ability to set a min-height for an Element

### ISSUE THREAD

**Issue by NoemiNL** [pojome/elementor#2115]
Sometimes you want to have a couple of columns with the same height, for example when you have  buttons underneath them for actions.

Now you have to add custom css for this.
It would be great if this could be added as an Element setting.
(somewhere near to the margin/padding settings?)

**Comment by arielk** [comment]
You can already do this by "Content Location" under the section settings, please check it.

**Comment by NoemiNL** [comment]
Found it thanks!

Only this way (section min-height) isn't a solution for mobile view. 

When you have 3 columns with text and set the section min-height then you have to add another section with 3 columns to add a button.
This results on mobile that first you get the column with the 3 text widgets and then underneath those the 3 buttons, so the buttons make no sense anymore..

When you do place the buttons into the same section you still have to add custom css to positions them on the bottom of the section.
```
.elementor-widget-button {
    position: absolute;
    bottom: 0;
}
```

This is a large learning curve to teach customers.
Therefor it would be great if the min-height could also be set to the widget itself, think that's the easiest way to establish the above.

**Comment by arielk** [comment]
Sorry, we are not planning to add this option soon, but maybe in the future.

Thank you very much for your feedback!

**Comment by hufer** [comment]
https://pafe.piotnet.com/#equal-height This plugin can do it for you. Equal Height Feature for Elementor
