### ISSUE TITLE
elementor/frontend/after_enqueue_styles not working properly

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#2117]
Hi, after upgrading to v1.6, the elementor/frontend/after_enqueue_styles action is not working properly, hiding icons even in backend:

``` php
add_action( 'elementor/frontend/after_enqueue_styles', function() {
   wp_dequeue_style('elementor-icons');
});
```

The action above was used to unload icons in frontend, since they're not used (probably you should add it by default for all it's strictly backend-only). Now it's not working, meaning that it will strip out icons even in backend/admin.

By the way, I'm not seeing 'beatiful sharpness' with the new icons...
![schermata 2017-08-02 alle 11 39 28](https://user-images.githubusercontent.com/437598/28867897-ee57dcaa-7777-11e7-87f0-5c8718480b71.png)
![schermata 2017-08-02 alle 11 40 02](https://user-images.githubusercontent.com/437598/28867898-ee5c6824-7777-11e7-9c96-c3bd9869ffa9.png)

**Comment by KingYes** [comment]
Backend = Elementor Editor or WP Dashboard?

**Comment by stratboy** [comment]
Backend is what frontend it's not.

**Comment by KingYes** [comment]
In `1.5.x` we used with Font Awesome and with Elementor-Icons just in the panel. Since `1.6.x` we replaced FA by E-Icons. And the preview window using frontend styles with more.

Please try this one:

```
add_action( 'elementor/frontend/after_enqueue_styles', function () {
	wp_dequeue_style( 'elementor-icons' );
} );

add_action( 'elementor/preview/enqueue_styles', function () {
	wp_enqueue_style( 'elementor-icons' );
} );
```
