### ISSUE TITLE
1.6 Issue with PHP 7

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#2119]
We have updated to 1.6 today on PHP 7.0. When you click on 'Edit with Elementor' it will download the post file instead of execute. Works fine in 1.5.5. 

					
```
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.35
	PHP Version: 7.0.21
	PHP Max Input Vars: 1000
	PHP Max Post Size: 12M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	WP Multisite: No
	Max Upload Size: 12 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4

== Active Plugins ==
	Elementor
		Version: 1.6.0
		Author: Elementor.com

	Elementor Pro
		Version: 1.5.8
		Author: Elementor.com

== Debug ==
	Errors: 
		TypeError: undefined is not an object (evaluating 'a.ui.triggerButton.removeClass')
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.5 - 5:11873
			2017-08-02 08:32 +00:00
			x 9 times
```

**Comment by KingYes** [comment]
Can you record your screen?

**Comment by enkota** [comment]
https://www.youtube.com/watch?v=b_Oa_kXnGH0

It's possible there is a conflict with our server config but all that's changed is the update to Elementor. 

Thanks!

**Comment by KingYes** [comment]
Please send to support@elementor.com your WP Admin + FTP access to see that.

**Comment by enkota** [comment]
@KingYes Sure, in contact with our host to see if there is an issue on their end first. Cheers!

**Comment by carlchan** [comment]
Can confirm, having the same issue here after the update.  Doesn't seem to be a PHP7 issue, I swapped my wordpress to php5 temporarily and it still does the same thing.

**Comment by enkota** [comment]
@carlchan Interesting, we switched back to PHP5 and it's working on 1.6. Still to hear back from host. Will update once I hear back.

**Comment by enkota** [comment]
@KingYes I've sent an email with login details. Let me know if you need anything else. Thanks!

**Comment by KingYes** [comment]
Thanks @enkota !
