### ISSUE TITLE
Images bug since 0.4

### ISSUE THREAD

**Issue by patatus** [pojome/elementor#212]
Hi !
Since the update this afternoon, my images are resized and no longer centered.
For instance, when I put a single image into a section, telling it to be centered (via text align like it used to work), the image renders smaller and aligned to the left, even though the preview inside Elementor is fine…

I didn't find any workaround yet, except using the image as a background to the section (but this isn't great due to responsive issue).
I noted that, inside the "advanced" parameters, there is no longer an "auto" value to the right and left margins. When adding them manually inside the web inspector, the image centers again, but still no proper size.

This :
![image](https://cloud.githubusercontent.com/assets/20305403/16594859/9faa8d02-42ec-11e6-8174-1b139f4f279b.png)

Renders into this :
![image](https://cloud.githubusercontent.com/assets/20305403/16594872/b65dbc86-42ec-11e6-857e-9dfba9f69372.png)

Thanks !

**Comment by yehudah** [comment]
Sorry about that.

This bug was fixed on 0.4.1 so you can update now.

**Comment by patatus** [comment]
Thanks a lot for the great work !
