### ISSUE TITLE
Lightbox issues

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2121]
Hi! Thanks for update, but have some issues.

1. There is no setting to set "yes/no" Image Gallery widget lightbox
2. Video lightbox has auful frame

Thans for fix!

**Comment by arielk** [comment]
1. I'll check it

2. Do you have any screenshot?

**Comment by parfilov** [comment]
![frame_elementor](https://user-images.githubusercontent.com/12493645/28884222-c99081aa-77d2-11e7-9129-ad1f941dcf2f.jpg)
It's in Firefox. Almost the same in Chrome.

**Comment by arielk** [comment]
Thanks https://github.com/pojome/elementor/pull/2122

**Comment by arielk** [comment]
fix https://github.com/pojome/elementor/pull/2130
