### ISSUE TITLE
Issue with Form API. Absensce of hook to register own Action.

### ISSUE THREAD

**Issue by collizo4sky** [pojome/elementor#2123]
I am building an integration for Elementor pro. There is no Action hook to call `$this->add_form_action( 'serviceNane', new serviceNane() );` Outside of `elementor-pro/modules/forms/module.php`

I added my service after `$this->add_form_action( 'webhook', new Webhook() );` like so `$this->add_form_action( 'serviceNane', new serviceNane() );` and it worked.

I tried overriding the class and calling `parent::__construct()` but the hack didnt work.

Or is there an alternative way of registering form actions and component outside of `elementor-pro/modules/forms/module.php` ????

**Comment by collizo4sky** [comment]
@arielk any update? I can submit a pull request to fix this issue if you want. This is one missing piece if you would love developers to build with the form API in Elementor.

**Comment by matipojo** [comment]
Hi, @collizo4sky, you should use:
`\ElementorPro\Modules\Forms\Module::instance()->add_form_action( 'service-name', new Service_Name() );`

**Comment by collizo4sky** [comment]
Wao. That worked.
