### ISSUE TITLE
Polylang issue with new update

### ISSUE THREAD

**Issue by Birbo** [pojome/elementor#2124]
Hi,

Today's update (02/08) ruined Polylang compatibility. I noticed one of the "Tweaks" was Polylang compatibility, regarding a past issue, (#1959).

But something created a much bigger issue. Basically, if a page in a certain language wasn't created with elementor, and the other one was... They will both appear in the language that uses elementor.
In other words, my website is available in 3 languages, but only english language pages are created with elementor. The other 2 languages are now forced to use elementor on the backend. And on the front end, the displayed language is english, even when the url is the correct one (non english).

When my readers change language, it always redirect them to the english version of the page, the only one that uses elementor. Please fix this issue asap, it's chaotic and it can have a very negative impact on many levels.

Thanks and regards.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by chemocool** [comment]
I have an issue also with polylang pro and elementor pro

Step to reproduce

1. Create new post
2. Edit with elementor and add some Elementor content
3. Save
4. Click Polylang "duplicate" switch then create a copy in another language
5. In that duplicated copy in another language, change some elementor content
6. Save
7. Click Update on the duplicated post
8. Original post content is now the Duplicated version's Elementor content.
9. It works the same if you change elementor content in the original version then "update" the post after saving the change.

Only way to avoid that is to break the tie between both articles, which of course is a major issue on a multilingual website.

**Comment by chemocool** [comment]
As soon as i edit a page/post SEO and press update, the elementor content is pushed to all languages, so i have to open other languages & load the latest revisions to have them back to the proper language.

**Comment by arielk** [comment]
Which SEO plugin are you using?

**Comment by vickiviaja** [comment]
I have the same problem since days. I cannot connect my posts anymore otherwise one of them  will change automatically mirroring the other text if I save or update. Today I had to update an already published post from May in English and suddenly the German version was in English as well. (Only post title keeps the same) it took me so much timing fixing it and I had to unlink these posts. Will the next update fix this issue?

**Comment by arielk** [comment]
@vickiviaja In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by chemocool** [comment]
@vickiviaja  

While they fix this, you can easily restore the right language using "revisions" in Elementor.

Click the last revision, it's going to bring back the right version in Elementor, then save.

It's annoying to do that, but it's the best way to restore the right version.

As a Elementor Pro user, I hope they can fix this soon, I have to launch my company site in 2 weeks, and this bug severely compromise it.

**Comment by arielk** [comment]
Fix for v1.7.0 https://github.com/pojome/elementor/commit/1b0c6d356c6878c01a3c3285d3bebbbf651de2cb

Thanks for your feedback!

**Comment by chemocool** [comment]
Awesome, this is great news. Thanks a lot.
