### ISSUE TITLE
Duplicate Entries in the Database when using 2 Actions After Submit

### ISSUE THREAD

**Issue by katart** [pojome/elementor#2126]
## Description

I'm using the Elementor Contact Form DB plugin to have a UI for email signup entries. I noticed that when I use Email and Email2 in the Actions After Submit field that the DB plugin captures 2 entries in the database. Would this be a bug with Elementor or Elementor DB?

## Environment
				
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.1.45
	PHP Version: 5.5.17p1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	Site URL: http://mforafrica.org/dev
	Home URL: http://mforafrica.org/dev
	WP Multisite: No
	Max Upload Size: 22 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Active

== Theme ==
	Name: Miracle for Africa
	Version: 1.0.0
	Author: FaircomNY
	Child Theme: Yes
	Parent Theme Name: FaircomNY Default Theme
	Parent Theme Version: 2.1.5
	Parent Theme Author: FaircomNY

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.6.1
		Author: Elementor.com

	Elementor Contact Form DB
		Version: 1.1
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 1.5.8
		Author: Elementor.com

	WP All Export
		Version: 1.1.5
		Author: Soflyy

== Debug ==
	Errors: 
		TypeError: Cannot read property 'on' of undefined
			at http://mforafrica.org/dev/wp-content/plugins/elementor/assets/js/editor.min.js - 2:88899
			2017-08-02 14:35 +00:00

		TypeError: Cannot read property 'removeClass' of undefined
			at http://mforafrica.org/dev/wp-content/plugins/elementor/assets/js/editor.min.js - 5:11873
			2017-07-27 18:18 +00:00
			x 6 times

**Comment by arielk** [comment]
I have no idea why this is happening, but please contact the developer of the plugin:
https://www.sean-barton.co.uk/2017/04/elementor-contact-form-db-free-plugin/

We will be happy to help as much as possible.

**Comment by katart** [comment]
Thanks @arielk 

I have a question out to the developer, but haven't heard back yet.
