### ISSUE TITLE
Package as a module to allow for more developer access

### ISSUE THREAD

**Issue by bensteers** [pojome/elementor#2127]
I'm trying to extend Elementor's container widgets (Section/Columns), but I am running into roadblocks where I can't access certain objects, for example: `var EmptyView = require('elementor-views/element-empty');` returns undefined. 

I realize that this is because Browserify doesn't allow for the use of `require` outside of the Elementor plugin directory. I don't have experience with Browserify, but it seems that if you added `--standalone elementor` to the command line arguments that'd it'd expose the entire package under the name `elementor`. 

In this case, it seems like you just have to edit `Gruntfile.js` 
```javascript
grunt.initConfig( {
	...
	browserify: {
		options: {
			browserifyOptions: {
				standalone: elementor // add this
				...
			},
			...
		}
		...
	}
	...
} );
```

I'm not sure if this would solve my problem though so your input would be great. I would just really like to be able to make my own container widgets without having to touch the core.

Thanks!

**Comment by KingYes** [comment]
Which classes you need and why? We can declare some in global scope to reuse by 3th-party.

**Comment by bensteers** [comment]
I'm trying to create a widget that can run custom queries and display the results using Elementor. It would be similar to the Posts widget, but instead of having it be one widget handling everything, it would act like a section and use its child column and the elements inside it to loop over and display the posts (i.e. build one column and use that for each query result. Or add two and have them alternate etc.). Then you'd be able to use something like Press Elements and drag in your own custom fields and design your own query layout within the confines of Elementor.

As far as I can tell right now, the behaviors and the empty element view are the modules I'd need, but I haven't really tested that out. Maybe you would know what I would need in order to give a widget the capability to accept children via drag and drop?

**Comment by KingYes** [comment]
You can download dev version of Elementor, and just require the files like this:

`require( '../elementor/assets/dev/...' );
