### ISSUE TITLE
Load generated CSS in header instead of footer!

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#2128]
Anyway to force the generated CSS files to be loaded in the header instead of the footer?

The delay in browser rendering is causing a lot of frustration with users and site visitors alike.

Maybe an improvement to the settings of "CSS Print Method" with an option of load location?

**Comment by KingYes** [comment]
You can write custom code for that, like this:

```
add_action( 'wp_enqueue_scripts', function() {
	if ( ! class_exists( '\Elementor\Post_CSS_File' ) ) {
		return;
	}

	$header_page_id = 1996;

	$css_file = new \Elementor\Post_CSS_File( $header_page_id );
	$css_file->enqueue();
}, 500 );
```

**Comment by WPDevHQ** [comment]
That is great @KingYes but...... For every instance of a generated post-xxxx.css? These are also dynamic and difer from site to site and page to page.

Surely there has to be a better way? Why not give the option for user to choose how the generated css are loaded? Which seems to be a more logical approach than for every developer having to write out these custom functions!

Also whay are issues closed before being fully resolved?

**Comment by KingYes** [comment]
In the head of the page, we can't know what write inside (by custom code or shortcode). In your own code, where you manage your templates, you need to embed all used styles..

**Comment by arielk** [comment]
I think this issue has been fixed in version 2.0. Feel free to reopen the issue and we'll look into it again.

**Comment by JohnMulderFrance** [comment]
Don't think so. When using a nav menu in a header template, only the menu is temporarily unstyled. (fouc) all other elements on the page are styled. When loading the css asynchronously and fiddling around with a critical css path this fouc in the menu can be solved. Unfortunately other elements on the page then suffer from a fouc.

**Comment by webdevs-pro** [comment]
```$css_file = new \Elementor\Core\Files\CSS\Post( $header_page_id );```

Actually here is a new docs here https://elementor.com/help/dealing-with-flickers-fouc/

**Comment by andrinda** [comment]
how if any more template header ?

example 
```

add_action( 'wp_enqueue_scripts', function() {
	if ( ! class_exists( '\Elementor\Core\Files\CSS\Post' ) ) {
		return;
	}
	$template_id = 15636;
	$css_file = new \Elementor\Core\Files\CSS\Post( $template_id );
	$css_file->enqueue();
}, 500 );
```

**Comment by skdev6** [comment]
What do you think about this solution? 

function sk_get_elementor_css_files() {
    $css_dir = WP_CONTENT_DIR . '/uploads/elementor/css/'; 
    $css_files = glob($css_dir . 'post-*.css');
    return $css_files;
}
add_action('wp_enqueue_scripts', function() { 
	$css_files = sk_get_elementor_css_files();
	foreach ($css_files as $key => $css_file) {
		$filename = basename($css_file);
		$file_url = content_url('/uploads/elementor/css/' . $filename);
		wp_enqueue_style('elementor-'.pathinfo($filename, PATHINFO_FILENAME), $file_url, null, '471', null);
	}
}, 10000);
