### ISSUE TITLE
Elementor-Pro - FormModuel - Labels are not connected with input fields

### ISSUE THREAD

**Issue by SoftwareManufakturDresden** [pojome/elementor#2133]
For inputfield of typ checkbox, radio, text and email it is not possible to activate the field by clicking on the label.
Reason for that is a wrong creation of the for-attribute of the label.

**The solution for checkboxes and radio field is:**

File: elementor-pro/modules/forms/classes/form-base.php
Line: 122
	
Updated the line 
	`id="' . $this->get_attribute_id( $item_index ) . '-' . $key . '"`
to
	`id="' . $this->get_attribute_id( $item ) . '-' . $key . '"`

**The solution for other input field is:**

File: elementor-pro/modules/forms/classes/form-base.php
Line: 153
	
Old code 
	`'for' => $this->get_attribute_id( $i ),`

Fixed code
	`'for' => $this->get_attribute_id( $item )`

**Comment by SoftwareManufakturDresden** [comment]
See also patch file
[patch.diff.txt](https://github.com/pojome/elementor/files/1210792/patch.diff.txt)

**Comment by micha77dd** [comment]
We would like to update to latest Elementor Pro version but this issue prevents simple 'one-click'-updates. Do you plan to integrate the attached patch into one of the next Elementor Pro releases?

**Comment by bainternet** [comment]
should be fixed from version 1.8 and up.

thanks for the feedback.
