### ISSUE TITLE
Elementor 1.6.2 not working on WP multisite

### ISSUE THREAD

**Issue by varkstad** [pojome/elementor#2137]

**Comment by varkstad** [comment]
I have had Elementor 1.5.5 on a WP multisite installation without problem. Yesterday I updated to 1.6.1 and now to 1.6.2. Both these versions have problems. I can´t open a page in Elementor. I have purged the cache tried to inactivate the plugin autooptimize, increased php memory to 250 MB, advices that I have got. But it didn´t help me open a page with Elementor.  I have now reinstalled version 1.5.5 which works okay.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by arielk** [comment]
@varkstad In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by thekaku** [comment]
Is this issue solved?

**Comment by varkstad** [comment]
Yes, the issue is solved.

**Comment by thekaku** [comment]
what is the solution?

**Comment by varkstad** [comment]
It was half a year ago, i can´t remember how the issue was solved.

**Comment by thekaku** [comment]
i am facing the same problem, do u have any suggestion where to find the  solution? any record about this?
