### ISSUE TITLE
Thrive Themes using Elementor code???

### ISSUE THREAD

**Issue by markwatney87** [pojome/elementor#2138]
Hi,

I use and support Elementor, it's the best editor for wordpress right now.

A friend of mine send me this:-

https://thrivethemes.com/thrive-architect-sneak-peek

Here is the video:  https://www.youtube.com/watch?v=3W3cEfeIk5E

Check at 1:32 for the mobile preview.

How much of this looks exactly like Elementor?  

They are using the exact same sidebar on the left.  A huge departure from their previous UI.
They are using the exact same mobile preview style.
They are using the exact same mobile animation!

Now, when I say exact.  They look very similar.  I do not know if it's the same code, because it's not been released yet.

Maybe the guys behind Elementor should investigate on whether some source code is being used in their product?  

Especially, when they may be taking elements from the "PRO" version and putting it in their product?

What do you guys think?

---------

Edit: Images in-case the pull down the video.

Sidebar:
![Sidebar](http://i.imgur.com/NiMuG0y.png)

Responsive Editor:
![Responsive Editor](http://i.imgur.com/vsLGf9o.png)

Mobile Preview:
![Mobile Preview](http://i.imgur.com/gZo9MuC.png)

**Comment by dasigna** [comment]
interesting... that seems to be quite close - close to copy :-)

**Comment by arielk** [comment]
Thank you for bringing this to our attention.

Since we first launched Elementor, we always stated to be leading the WordPress page builder market. This example, and other ones as well, proves we are indeed in the head.

As long as we keep developing Elementor further, and competitors keep busy copying us, we can be sure to leave all competition behind.

**Comment by markwatney87** [comment]
No problem.

What about the license though?  If they are indeed using YOUR code, because they are distributing their code to their paying customers.  Won't they have to make available THEIR source code, because now too it should use the GPL3 license?

**Comment by dasigna** [comment]
hmmm...

in fact, i dont think they would copy code exactly from elementor (that would be dumb as can be...). but they seem kind of "inspired" from elementor. so much inspired they even choose identical colors and layout mostly ... at least close to walking around a grey area in law for my taste.

so if i were an elementor dev i would keep an eye on that! very closely.
but @arielk obviously is right - thats also kind of a compliment to elementor, so its up to them to deal with.

interesting though: thrive seems to expand available widgets in way that again leads to the conclusion they're reading all those threads here very, very well :-)

**Comment by gobi77** [comment]
still thinking the same, guys? :)
