### ISSUE TITLE
Problem with Elementor 1.6.2 and Blog Page error in console

### ISSUE THREAD

**Issue by HartLarsson** [pojome/elementor#2140]
I use WP 4.8.1 with OceanWp theme and Elementor 1.6.2
Since elementor 1.6 (not on the previous version) i get every time i reach the blog page this consiole error:

![image](https://user-images.githubusercontent.com/16102074/28963979-4739335c-790b-11e7-8522-2d23902e2e6e.png)

With 1.5.x I'd no problems.

Thank you for any suggest to fix it

**Comment by arielk** [comment]
Can you please send us a link to the page with this problem?

**Comment by HartLarsson** [comment]
sure, I've sent an email to support
