### ISSUE TITLE
Enhance display of first add column bounding box

### ISSUE THREAD

**Issue by LearnWPBasics** [pojome/elementor#2141]
It has been suggested by a client as well as a member of the Elementor FBG to perhaps add this as an "Accessibility Setting" in a future release.

Some of us (myself included) find that the dashed outline for the column bounding box when first added can be a bit difficult to readily see because of it’s light color and thin width.

I have created an Elementor "Quick Tip" that provides some CSS to enhance this display for those of us with less than perfect vision :) 

http://snifflevalve.com/quick-tips/elementor/enhance-display-first-add-column-bounding-box/

Cheers!
Lyle

**Comment by bainternet** [comment]
@LearnWPBasics 

Thanks for the suggestion, we have since added the tutorial videos for new users, and we feel this should remain in the "Quick Tip" territory.

thanks again.
