### ISSUE TITLE
Reset to default settings

### ISSUE THREAD

**Issue by themedleb** [pojome/elementor#2145]
Reset to default settings for each customization option that can be modified, for example: If I change padding from a certain value to 50px, I can click on a little button to reset it to it's original value.

**Comment by dasigna** [comment]
... just delete your entry and you're back to original :-)

unnecessary to have an extra button i think. (just my 2ct)

**Comment by themedleb** [comment]
Yeah, but there are not only text-boxes, there are list-boxes, radio-buttons, switch-buttons, ... having a default button will help us find the bad mis-configurations we made before we messed up the element options.

**Comment by arielk** [comment]
@themedleb 

Sorry, we are not planning to add this option soon, but maybe in the future.

Thank you very much for your feedback!

**Comment by themedleb** [comment]
Thank you.

**Comment by murshed** [comment]
Any updates about resetting to default settings?
