### ISSUE TITLE
[Not An Issue] Just Taking A Long Shot

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#2146]
[Probably A Very Long Shot But Maybe Not Impossible!]

I probably know the answer (at least for now) but I'm going to be cheeky and ask anyway :D 

In a not too far distant future, do you guys think that we will ever have the ability to put repeaters inside a top level repeater control?

On another level, how likely that we get some functionality that would allow us to define the # of controls needed and have those generated automatically? Somewhat of a controls_section repeater instead of fields inside of a control - if that makes sense?

Say I want the user to specify a certain number items. This figure is then taken and used to generate that many controls - I know this can somehow be achieved with the repeater controls but I'm trying to be clever (maybe too clever for my own good) !

As an example, I can write a function that would generate a widget area for each menu item which has a designated class attached to it - Now in this widget area I can add as many widgets (read fields) as I need ready for further tweaking before being output as a sub-menu item of the top level item for which they were generated for :)

It's a long shot but one can always ask and the worst they can get is a straight "No"!

**Comment by arielk** [comment]
If I understand correctly, you want to make the repeater control like the WordPress menu management?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
