### ISSUE TITLE
BUG - Background Attachment Scroll vs Fixed on Tablet/Mobile

### ISSUE THREAD

**Issue by BrianBatzli** [pojome/elementor#2153]
I have noticed with many of my sites now that the Background images in sections do not display properly anymore on tablets and mobile devices. Issue does not exist on the desktop view.

This issue is in version 1.6.3 and pro 1.5.8 when attachment is set to "fixed" and size set to "cover".

Changing attachment to "scroll" corrects the image size to match "cover".

**Comment by arielk** [comment]
The problem is with the definition of `background-attachment: fixed;` that not working perfectly on mobile.

Unfortunately we have no way to fix it, it is related to the support of browsers.
