### ISSUE TITLE
Rounding error with three columns in IE10, IE11 & Edge

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#2154]
When using a three column layout Windows IE10, IE11 and Edge shows two columns due to rounding error when using **width: calc(100% / 3)**. 

Here's a screenshot from Internet Explorer 11 on Windows 10: 
![image](https://user-images.githubusercontent.com/1729832/29051883-3d25ea9c-7c29-11e7-8c68-f0b15ecfce63.png)
Here's a screenshot from Edge on Windows 10: ![image](https://user-images.githubusercontent.com/1729832/29052044-8c389994-7c2a-11e7-84b3-c1c2eab8fc65.png)

One possible solution is to change this to **width: calc(100% * 0.333)**. 

Here's a screenshot from Internet Explorer 11 on Windows 10: ![image](https://user-images.githubusercontent.com/1729832/29051832-d1edfa6c-7c28-11e7-968c-05238f818f50.png)
Here's a screenshot from Edge on Windows 10: ![image](https://user-images.githubusercontent.com/1729832/29052060-aa170acc-7c2a-11e7-9677-dd912e523f06.png)

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
