### ISSUE TITLE
[Feature request] Set section's background to the featured image of the post/page

### ISSUE THREAD

**Issue by themedleb** [pojome/elementor#2156]
Set section's background to the featured image of the post/page.

**Comment by themedleb** [comment]
It's so useful when we want to design our own single post layout.

**Comment by arielk** [comment]
I merged this issue with another issue #1071 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by themedleb** [comment]
Thanks @arielk
