### ISSUE TITLE
[Feature request] Heading/Text element to pull meta automatically

### ISSUE THREAD

**Issue by themedleb** [pojome/elementor#2158]
Set heading/text element to pull meta automatically.

**Comment by themedleb** [comment]
It's so useful when we want to design our own single post layout.

**Comment by arielk** [comment]
I merged this issue with another issue #543 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by themedleb** [comment]
Thank you :)
