### ISSUE TITLE
Forms: Add a password type field

### ISSUE THREAD

**Issue by SoftwareManufakturDresden** [pojome/elementor#2164]
Hey Elementor-Team,

we have a feature-request to the elementor pro version.
We need in the form-module beside inputfields of type text, email and so one, also the type password.

Currently we fixed that manually by adding the password type into the form.php

See also git-patch.
[patch.diff.txt](https://github.com/pojome/elementor/files/1211791/patch.diff.txt)

Thanks in advance,
Markus

**Comment by micha77dd** [comment]
We would like to update to latest Elementor version but this missing feature prevents simple 'one-click'-updates. Do you plan to integrate the attached patch into one of the next Elementor releases?

**Comment by bainternet** [comment]
We do have plans to add this field in next releases but I'm not sure about the provided patch being integrated.

But rest assure its on our to-do list.

**Comment by bainternet** [comment]
Done in v1.13.0
