### ISSUE TITLE
Saving Changes in Elementor always trigger a "publish_post" Action event.

### ISSUE THREAD

**Issue by collizo4sky** [pojome/elementor#2165]
This Action https://codex.wordpress.org/Plugin_API/Action_Reference/publish_post is always triggered when changes in Elementor builder is saved. Why?

**Comment by arielk** [comment]
It depends on the current status of the page.

If the page is published, then "Save" will post the changes, if the page is in draft status then the content will be saved to draft.

Note that you can change the status of the page using the > Page Settings. 

Please read more about it here: 
https://elementor.com/v140-blank-page/ (go to page settings section)

Thanks

**Comment by collizo4sky** [comment]
Hi, what i am saying is, `publish_post` action hook is always triggered after every save action in the editor/customizer. I don't mean the post status itself.

I have a custom plugin that listen to `publish_post` and it always get triggered each time i save changes in elementor.

**Comment by KingYes** [comment]
Every update we are change the post content by `wp_update_post()`. We are need to use with this function..

**Comment by collizo4sky** [comment]
I think you somewhere in your code, you are explicitly telling re-publishing every post that is edited/saved in elementor. That is, you are explicitly setting the post status to `publish` or something.

In wordpress, when you updated an already published post, `publish_post` hook isn't triggered. But this is not the case with elementor.

This is a bug and please look into it.

**Comment by collizo4sky** [comment]
My bad. This was an error on my part. Bug fixed.
