### ISSUE TITLE
[FEATURE REQUEST] Column Animation "when hover"

### ISSUE THREAD

**Issue by VadymVolos** [pojome/elementor#2168]
Hi! 

Edit Column / Advanced / Entrance Animation - need add when hover "Hover Animation".

Thanks!

**Comment by arielk** [comment]
You can do it by Hover effect, please read this article: 
https://elementor.com/v150-hover-effect/

Thanks

**Comment by VadymVolos** [comment]
The article does not have what I need.

I temporarily solved the problem this way:
Edit Column / Advanced - CSS Classes ( add elementor-animation-grow )


Need Column (Hover Animation) elementor-animation-grow

**Comment by VadymVolos** [comment]
Images (Hover Animation) elementor-animation-grow - Yes
Columns (Hover Animation) elementor-animation-grow - Why not?

**Comment by arielk** [comment]
Not every element needs such transition animations, but perhaps we will add in the future.
Thanks for the idea!

**Comment by Just1CodeBullet** [comment]
> Not every element needs such transition animations, but perhaps we will add in the future.
> Thanks for the idea!

Totally agree with @VadymVolos, why not? And why is there a default animation you can´t really change without CSS Classes?
