### ISSUE TITLE
theme layouts - integration with pods - field connections

### ISSUE THREAD

**Issue by smatzis** [pojome/elementor#2169]
Hello and many thanks for this wonderful builder.
I think that elementor's power should be unleashed for custom theme layouts. Not only headers and footers layout but also custom post templates and section layouts that can hook to posts or pages if conditions are met.
Integration with Pods and Advanced Custom Fields plugins could do that possible.
Beaver themer does all of the above and makes advantage of beaver builder to create all of the templates and field connections to pass the needed data.
I really like elementor and the gui it provides would be perfect for all of these advanced operations.

Many thanks again. You are doing a beautiful work.

**Comment by arielk** [comment]
I merged this issue with another issue #1071 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
