### ISSUE TITLE
Social Icons: Snapchat missing icon

### ISSUE THREAD

**Issue by brianroach** [pojome/elementor#217]
![2016-07-06 at 10 58 am](https://cloud.githubusercontent.com/assets/9772694/16628956/b58a8bdc-4368-11e6-9f4d-f29d2a7bc8e4.jpg)

**Comment by yehudah** [comment]
any chance you can share that page so I can examine it ?

**Comment by brianroach** [comment]
its on localhost, sorry. :/

**Comment by yehudah** [comment]
I checked it and it's working on my installation.

I can only guess some css rule giving the color of the icon the same color of the background 
so it look like there is nothing there.
