### ISSUE TITLE
Swiper slider style conflict

### ISSUE THREAD

**Issue by bdthemes** [pojome/elementor#2170]
## Description
I am developing a new element "Post Carousel" for elementor but when i trying to use swiper jquery slider plugin it's not showing exact design what i design for my caousel. When i trying to search swiper in elementor plugin i found some css and javascript that never used there. Can you remove them or set prefix of them.

**Comment by arielk** [comment]
Please be more specific in problems that we can fix it, which code exactly make the conflict?

**Comment by bdthemes** [comment]
Anyway now i using elementor builtin swiper script and css and override them as per needs.
