### ISSUE TITLE
How to override any existing widget?

### ISSUE THREAD

**Issue by bdthemes** [pojome/elementor#2171]
## Description
I did not find any solution for override an existing widget. For example: I want to add sub heading in Heading widget but i can't find any doc how i do that?

## Steps to reproduce
Nothing here for reproduce

## Environment
WordPress 4.8.1 + Elementor 1.6.3 Free Version

**Comment by KingYes** [comment]
Just create new widget (class extends) and override what you need with OOP method.

After that, unregister our widget, and register your new one.

**Comment by ohid** [comment]
Hi @KingYes 
How to unregister the Elementor widget from my theme?

Thanks

**Comment by stivoox** [comment]
@KingYes But How to unregister the Elementor widget ?
