### ISSUE TITLE
[FEATURE REQUEST or BUG?]  Drag-and-drop Columns

### ISSUE THREAD

**Issue by VadymVolos** [pojome/elementor#2174]
Hi!
 
Drag-and-drop Columns no work...

![2017-08-10](https://user-images.githubusercontent.com/12669290/29169954-3904604e-7ddf-11e7-833c-56b13b9ca372.gif)

**Comment by arielk** [comment]
This is the normal behavior in the editor.

You can not drag inner column to regular section, just into another inner section (Columns widget)

Thanks
