### ISSUE TITLE
VERY IMPORTANT FEATURE REQUEST: Word Count

### ISSUE THREAD

**Issue by loganmarketing** [pojome/elementor#2175]
In the standard Wordpress editor, you are given a word count. This helps with SEO as you know how many words you have written. This option is missing in Elementor's standard editor. If it could be added that would be great.  For anyone doing SEO on a website this is an essential item to have in place.

**Comment by nicomollet** [comment]
WRITING IN CAPS doesn't make it more important than other requests I think.

**Comment by arielk** [comment]
You can use the Yoast SEO plugin that allows it and works well with the Elementor.

Thanks for your feedback!
