### ISSUE TITLE
Custom CSS Page Settings code: pseudo elements content error

### ISSUE THREAD

**Issue by optimizewp** [pojome/elementor#2179]
If Custom CSS with a pseudo element like .icon-envelope:before{content:"\e086";} is added in the Custom CSS of the Page Settings Style tab, it gets saved loosing the \, then the element is rendered wrong.
This not happens if the same code is added to a section/column/widget. I checked the relative code stored in the _postmeta db table and for the first case, it is saved in the _elementor_page_settings meta_key column as .icon-call-in:before{content:"e047";} while in the second case, it is saved in the _elementor_data meta_key column as .icon-call-in:before{content:\"\\e047\";}.
Is is evident the css code is processed in two different ways, the second one is correct, where there are escaped characters.
I do not know if this way of processing the code in the page settings afflicts other css rules/selectors. But this worries me because I used a lot this feature in preproduction phase, a couple of Elementor versions ago, without noticing problems, and know site is live, not knowing if everything is working fine, with the need of review it. But with the others bugs opened about "Page Setting Bug: title and Template wrong and cannot be saved" I cannot edit the page, without incurring in the risk of loosing the injected css code.

**Comment by optimizewp** [comment]
I replicated this test with older versions of the plugin:
Elementor v.1.5.5 and Elementor Pro v.1.5.5.
and it is still present.
I made progressive upgrades to reach the current ones, and the problem is still present.
I built a brand new site, based on the latest releases and the problem is present there too.

Please consider it a bug.

It is possible to keep the pseudo element working adding the code escaping the "\" writing the code this way:
.icon-envelope:before{content:"\\e086";} 
but if other code is added in a second time, after a previous save, obviously the first one, in which one of the two \ has already been stripped, will loose the remaining one, representing the problem again.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by FullstackWEB-developer** [comment]
I think this issue not solved yet.
Please share correct answer.
