### ISSUE TITLE
[Feature request] Living Styleguide and Custom CSS selector with preview

### ISSUE THREAD

**Issue by saschakoeth** [pojome/elementor#2182]
The following features would make the perfect tool for consistent styling:

In the Global Settings integrate an interface that:

1 Reads out all existing Theme and used Plugins CSS elements incl. Media Querie settings
2 Shows all those editable elements in a visual preview that lists all elements with dummy content in a structured by the custom folder setup
3 Manage and assign custom categories to those editable CSS elements and handle them in a folder structure with drag and drop feature
4 While editing an element you get a list of all available editing parameters not only those which have been already assigned to a class or ID
5 There is never the need to right in the CSS Syntax. All parameters or text descriptions can be edited visually or entered in a simple textfield
6 Preview how elements interact on different screen sizes
7 Has a documentation text field to each element
8 Has a huge preset library like: https://www.uxpower.tools
9 Syncs back all changes done in the Preview mode to the site´s CSS itself

10 Additional to that central CSS manager / Living Styleguide there should then be a Custom CSS Pulldown at every Custom CSS fields that shows the folder structured CSS IDs and classes and make them selectable with out having to write them in a correct syntax.
11 If parameters are defined by CSS, there should be the option to override those with the styling features of each widget. 

Some examples of style guides (Without Wordpress or Elementor integration and not for non-coders):
http://livingstyleguide.devbridge.com
http://atomicdocs.io
http://styleguide.sc5.io
http://fractal.build
https://www.livingstyleguides.com
http://patternry.com/features/
http://hugeinc.github.io/styleguide/

A very good integration of a living styleguide into a wordpress theme page builder is shown here:
https://www.youtube.com/watch?v=4RfFZEkoB7o&t=527s
Done with this theme: https://yootheme.com/pro/
But this theme´s living style guide only works within the themes rather reduced options setting and is not adaptable to other themes or plugins.

Thanks

**Comment by bainternet** [comment]
@saschakoeth 

Great suggestions, I can tell you that some of them are on our roadmap, maybe not in the exact form as you described.

For now you can try [CSS Hero](https://www.csshero.org/plugins/elementor/) which works pretty well with Elementor.

thanks for the feedback
