### ISSUE TITLE
Multisite Error - Blocked a frame with origin

### ISSUE THREAD

**Issue by Beor18** [pojome/elementor#2183]
## Description

Hi, I have an error with Elementor is updated to the latest version but the editor does not load in multisite. Before the upgrade worked perfectly

The following appears:

Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://www.mi-domain-principal.org" from accessing a frame with origin "http: // my-domain -configured-multisite.com ". Protocols, domains, and ports must match.

On the server side, everything is ok.

From already thank you very much! And I expect a prompt solution.

**Comment by optimizewp** [comment]
Please check if there is any other plugin interfering with that, I have Elementor + Elementor Pro currently installed on several multisite WP  installations and it works fine.
I had some problems, and every time it was an incompatibility with some free related Elementor plugin, maybe one of those not regularly updated. 
Hope this helps.

**Comment by arielk** [comment]
Do you use a standard multisite installation (subdomain / folder) or with Domain Mapping?

**Comment by Beor18** [comment]
Fixed!
I use Domain Mapping

Deactivate the remote login option in multisite so that it works again Elementor

Thanks for the answers!

Sorry for my bad English

**Comment by samuelcerezo** [comment]
Hi, same problem using Polylang with "Domain mapping" option.
`Uncaught DOMException: Blocked a frame with origin "https://xxxxxxxxx.es" from accessing a cross-origin frame.`

**Comment by JanWebofka** [comment]
Getting same error with multidomain Polylang
