### ISSUE TITLE
[Feature request] PRO menu and more meta option on posts

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#2189]
Hello guys,

Would be perfect to have a pro menu with responsive options and the possibilities to customize this menu.

And on posts cards would be good to have an option to put a customized META, not only the pre made option that you give.

**Comment by arielk** [comment]
I merged this issue with another issues, this #1406 for the menu widget, and this #1071 for the meta tags in the posts widget.

Thanks for your feedback!
