### ISSUE TITLE
Font selection.

### ISSUE THREAD

**Issue by wwwanhidemacom** [pojome/elementor#2190]
I would like to suggest you something. Please make the font selection scrollable . Like photoshop, to be able to choose by scrolling but not all the time separately click to choose. It would be a nice thing to do. Long Live Elementor ! Hats off to the creators !

**Comment by CiriousJoker** [comment]
Would be awesome if this existed

**Comment by bainternet** [comment]
This is a tricky one,
Not sure if its even possible to do using Select2.

We use [Select2](https://select2.org/) for two main reasons:
1) The font list is too long to use a browser native select.
2) We find that being able to search for a font is much more useful the plain "browsing" through the list.

So, for now, I'll close this but I labeled it so we'll know to get back to it, and yea I agree that it would be awesome :).

thanks for the feedback.
