### ISSUE TITLE
How to disable Responsive Tabs on Mobile

### ISSUE THREAD

**Issue by dbybanez** [pojome/elementor#2194]
Is there a way to disable the tabs on mobile? The accordion type wouldn't fit my current design. I want to customize it wherein the tabs when viewed on mobile are still displayed in tabs, so if you want to view more items on the tab, you just have to drag the tab left or right. Similar behavior of Material Design's tabs.

**Comment by arielk** [comment]
Unfortunately not, but you can do this with Custom CSS.

Thanks

**Comment by smokingbehind** [comment]
Hi! Can somebody help me to write this Custom CSS? Please

**Comment by TanvirAli** [comment]
Please try this.

@media (min-width: 320px) {
  .elementor-tabs-wrapper {
    display: flex;
        flex-direction: row;
  }
  .elementor-tab-mobile-title {
    display: none;
  }
}

**Comment by ofmarconi** [comment]
Not work

**Comment by ofmarconi** [comment]
**This work:**

.e-n-tabs-heading {
    display: flex!important;
}

.e-n-tab-title:not(.e-normal) {
    display: none;
}
