### ISSUE TITLE
[Feature Request] Hide Background image on Small Device

### ISSUE THREAD

**Issue by bdthemes** [pojome/elementor#2196]
## Description

Please add Background hidden option for mobile device in Section and column options. for example: Sometimes no need to load/show background images in mobile device because of small screen so it's better if we turn off it from section (if we set it from section then section if we set it from column then column).

## Steps to reproduce
Here an example of bg control: https://codepen.io/bdthemes/pen/prdozZ

**Comment by arielk** [comment]
I merged this issue with another issue #2355 in the same subject so we could deal with it more efficiently.

Thanks for your feedback!
