### ISSUE TITLE
Selecting sections under other sections when they over lap.

### ISSUE THREAD

**Issue by darenjm** [pojome/elementor#2200]
It would be a great feature if you you click the section under another section. As it is now I can not do it so I have to write down the margin value, move the section out of the way, then edit the section below. 

Thanks

**Comment by cavalierlife** [comment]
Yes, I've mentioned this too, and there could be alternatives ways of reaching section, column, and element toolbars. First, we should be able to rename them, optionally, but they should all give themselves a default name when created. Then, if there's no other way to get to them via mouse, we could simply choose from a pick list of all toolbars on the page via their names, and that section/column/widget becomes selected, with its options immediately available.

**Comment by gahawkey** [comment]
A breadcrumb like Thrive Architect would achieve this kind of functionality 👍  If it was something that could be toggled to show/hide as wanted, then it wouldn't have to take up UI space constantly, but when laying out elements overall, or when trying to access obstructed elements, it would be so handy 😃

**Comment by arielk** [comment]
We call it Navigator -- which is already implemented in v2.2 beta version, please check it out #5493 !
