### ISSUE TITLE
 buttons on elementor are not working on my site but work fine on the editor?

### ISSUE THREAD

**Issue by syed-sohaaib** [pojome/elementor#2207]
![error_page](https://user-images.githubusercontent.com/31104819/29421225-d796ca2c-838d-11e7-9bae-1c023268f3fd.PNG)
I am using the sydney theme. And to design my page I am using elementor. Everything works fine except the buttons. Buttons are working fine on the editor but problem arises when I see my page on my site. I have  attached the images if someone not get my point. Thanks!
![editor verison](https://user-images.githubusercontent.com/31104819/29421197-bd911fb0-838d-11e7-85f9-79e98e7d59cf.PNG)

**Comment by arielk** [comment]
Can you share with us a link to this page?

**Comment by weibenfalk** [comment]
Hi .. did you solve this issue? Because I got the same issue with the buttons in my theme. 
Thanks!

**Comment by vewass** [comment]
I  have the same problem ? What is the solution ?
