### ISSUE TITLE
Sticky Menu Hides Section Editor Buttons

### ISSUE THREAD

**Issue by DerekBess** [pojome/elementor#2208]
If a theme uses a sticky menu, the first section editor buttons become hidden not allowing for that section to be editable.

**Comment by arielk** [comment]
You need to do little compatibility in order for it to work well, there are a number of themes that have made compatibility with us, such as OceanWP or GeneratePress.

What theme are you using?

**Comment by DerekBess** [comment]
I'm using a custom theme. For now, i'm simply hiding the menu with CSS while in the editor. Can you please let me know what these other themes are doing for the fix?

**Comment by arielk** [comment]
You can use `body.elementor-editor-active` class to set a custom CSS in your theme while Elementor is active, for example:

`body.elementor-editor-active {padding-top: 100px;}` (replace the 100px with your header height)

**Comment by DerekBess** [comment]
yea, that's the selector Im' using now. I just didn't know if there was an option in our pro version or not. Thanks.
