### ISSUE TITLE
Enhancement - Gallery and Carousel

### ISSUE THREAD

**Issue by kaelmawn** [pojome/elementor#2209]
Just like the carousel, we should be able to select the image Title as a caption when using the Gallery, instead of having to type a caption for every image.

Also, it would be great to be able to change the dot navigation from the carousel for thumbnails of selected images.

**Comment by arielk** [comment]
Finally Media Carousel is here with thumbnails and image title, released in E-Pro v1.9.0

Thanks for your feedback!
