### ISSUE TITLE
Suggestion: Template to use on multiple pages

### ISSUE THREAD

**Issue by Bobbutterfly** [pojome/elementor#221]
Hey Folks!

No surprise, your page builder is Awesome.

It would be even greater if we could build some widgets to be applied on all pages at once!
Like, templates that we don't need to put in every page individually :)

Would it be possible? :D 

Cheers!

**Comment by pingram3541** [comment]
Great idea.  I was thinking this would be perfect for Sections.  Define them as dynamic content blocks regardless of what is inside of them.  We could store this info inside a unique custom post type adding minimal queries on the front end.  A bit extensive here but a good specification is a great foundation for any great achievement.  Here goes...

1. Define Section Short Description -i.e. Name
2. Define Section as dynamic (re-usable) content block (i.e. ref special cpt id behind the scenes)
3. Enhance "Add Section" - When adding a new section, show and select from list of already existing dynamic sections or simply add column(s) to new static section
4. Enhance Editor Section Controls - Provide visual differences when hovering/navigating preview window controls such as colors to indicate as re-usable section - tool tip or other mechanism to also show the descriptive name for the reusable section - easily identify (when editing) which sections are normal static blocks and which are reusable content blocks
5. Enhance updating Section content anywhere it is used by providing a smart notice that updating will occur across all instances of this Section - i.e press OK to confirm.
6. Enhance updating Section - re-usable set/unset - When unsetting a section already set as reusable, section converts to standard section (i.e. static data copied to post meta vs using dynamic block cpt) and can be set again as re-usable however it would become a new re-usable instance requiring a new short description name - this allows for duplicating and creating a new modified reusable section - i.e. slightly different call to action banners, etc.
7. Enhance updating Section - change re-usable section to another re-usable section, i.e. function that shows current reusable section chosen along with other reusable section's short description names that can be chosen to change which reusable section is used in this space
8. Future or Pro feature - Group re-usable sections into named templates which allow for creating entire pages with a short simple function.  The sections can individually be switched on/off from being dynamic as needed allowing quick prototype/mock capabilities

**Comment by yehudah** [comment]
Thanks for the great ideas.

Some of the ideas all ready in our road map and will be includes in future releases.

**Comment by KingYes** [comment]
We are working hard on this feature, you can keep updates from this PR: #132
