### ISSUE TITLE
Anchor links smooth scrolling not working when admin bar is disabled

### ISSUE THREAD

**Issue by johnnyluu** [pojome/elementor#2210]
The anchor link smooth scroll breaks when the admin bar is disabled because in your frontend.js, you check the admin bar's height. If admin bar doesn't exist, the height() returns null, and the calculated scrollTop is NaN. Adding a default 0 for when admin bar doesn't exist of checking if admin bar exists would fix this.

**Comment by KingYes** [comment]
Thanks!
