### ISSUE TITLE
Add responsive selector to Custom CSS

### ISSUE THREAD

**Issue by MaskaZan** [pojome/elementor#2212]
It's difficult to create responsive styles in Custom CSS.
Please add responsive control to Custom CSS.
Or add variables for media queries, like a selector.

**Comment by arielk** [comment]
A responsive control is a bit tricky, but it can be an interesting idea to make a dedicated selector for each device.

Thanks for your feedback!

**Comment by maxwellhibbert** [comment]
Maybe an input for each breakpoint.. could be tabbed. I'd really like this feature also.

**Comment by SNeilson** [comment]
I would like all styles that I've set for the widget be displayed in the Custom CSS section as well as the responsive breakpoints, that way I could truely adjust the styles as I want, at the moment the Custom CSS section isn't very user friendly.

**Comment by dtbaker** [comment]
Are `@media` queries supported in the custom css area?

**Comment by maxwellhibbert** [comment]
@dtbaker yes

**Comment by maxwellhibbert** [comment]
I had an idea for how to tackle this here:
https://github.com/pojome/elementor/issues/3345

**Comment by bainternet** [comment]
we don't see the need right now, especially when the custom CSS editor supports `@media `queries.

We'll keep #3345 open for now.

**Comment by HQRaja** [comment]
While the custom CSS editor does support media queries, it becomes quite a bit of a hassle to enter them each time for tablet and mobile when we're adding custom CSS.

It also affects readability of the CSS that's added, since the editor window isn't too large.

Lastly, if breakpoints ever need to be changed in the future, any custom CSS added to elements will need to be modified accordingly.

This could all be solved by adding responsive controls to the custom CSS editor. It'll make for far better UX.

**Comment by MaxZiebell** [comment]
+1

**Comment by ruihildt** [comment]
Instead or rewriting every media query, you could have it automatically align it with the default breakpoints!

It make sense to have the same icons controlling next to every design, and make it available for the Custom Css field.

Please @bainternet reconsider the addition of this feature. Here's a quick mockup of how it could look.

![alt text](https://image.noelshack.com/fichiers/2019/10/4/1551972806-capture-d-ecran-du-2019-03-07-16-24-35.png "Reponsive selector for Custom CSS")

**Comment by R2wix9mtdI** [comment]
ruihildt nailed it - that's exactly what I need. CSS that aligns with breakpoints. The only other feature i would add to this is a toggle button to determine style sheet dependancy. So for example if I have custom CSS on desktop I may want to cascade them to the smaller devices. On the other hand I may want to disgard the desktop rules and have distinct rules for each device.

The toggle could therefore be named 'cascade' on/off or 'distinct' on/off or 'share rules' on/off - you get the idea

**Comment by sbc640964** [comment]
Waiting for such development ... +1

**Comment by Bestulo** [comment]
+1, this is just what we need

**Comment by cworf** [comment]
+1 for this, would be amazing to simply type something like:
```css
tablet_selector .alignleft {
  float: right;
}

mobile_selector .alignleft {
  float: none;
}
```

**Comment by mdrideout** [comment]
# Solution 
Use css attribute selectors to select only when the <body> tag has the attribute **data-elementor-device-mode** of "mobile".

[Information on attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)

## Example
```
body[data-elementor-device-mode=mobile] selector article {
    display:block;
}
```

**Comment by bouveng** [comment]
@mdrideout Thanks!

**Comment by sshdoc** [comment]
> Use css attribute selectors to select only when the `<body>` tag has the attribute **data-elementor-device-mode** of "mobile".

Could you elaborate on this with a real example for a style I oly want only on desktop, and a style I only want on tablet?

I didn't see `data-elementor-device-mode` anywhere in my pages. Maybe it's added on the fly with JS?

**Comment by ryanerwin** [comment]
> Use css attribute selectors to select only when the `<body>` tag has the attribute **data-elementor-device-mode** of "mobile".

Could you elaborate on this with a real example for a style I oly want only on desktop, and a style I only want on tablet?

I didn't see data-elementor-device-mode anywhere in my pages. Maybe it's added on the fly with JS?

**Comment by mdrideout** [comment]
@ryanerwin - it's visible on "inspect element", not in the source code. You are correct, the param is added dynamically with JavaScript. All options for the `data-elementor-device-mode` param happen dynamically, including **"desktop"**, **"tablet"**, and **"mobile"**
