### ISSUE TITLE
Video Widget issues after 1.4.10

### ISSUE THREAD

**Issue by bbuchan10** [pojome/elementor#2213]
Hi, does anyone know what is up with the video widget after 1.4.10? I havnt been able to update because everytime I try, it breaks the videos on the site. Youtube and Vimeo.

Red: Video with overlay
Blue: Start of next section
Yellow: The problem

![elementor video issue](https://user-images.githubusercontent.com/7221686/29479887-60749926-843a-11e7-90d2-de85574eaee1.jpg)

**Comment by arielk** [comment]
Can you share with us a link to this page or steps to reproduce this situation?

**Comment by bbuchan10** [comment]
Unfortunately, this is a live site and I cannot leave it broken. The only steps to reproduce are just using the video widget. I simply put the video widget on the page and when i go to the live site, it overstretched it's container. I even tried fiddling with the CSS and could even find the rouge style setting causing it.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
