### ISSUE TITLE
Contextual Display of fields in Form Element as Seen in MailChimp "Action after Submit"

### ISSUE THREAD

**Issue by collizo4sky** [pojome/elementor#2215]
Hi, collins from MailOptin team here. We want to achieve contextual display of fields as well ajax request to populate the fields as you guys did here 

![](https://media.giphy.com/media/3ohv4h3IWHJ7HRHS5q/giphy.gif)

I took a peep and saw the logic are in the editor.js file. How do i pull this off from a plugin angle?

Any link/pointer would be helpful.

cc @arielk @KingYes @matipojo @kobizz

**Comment by arielk** [comment]
Unfortunately we do not have a developer API for this, but we plan to add a more neat API for it (by data source ajax) in upcoming versions.

**Comment by collizo4sky** [comment]
Any ETA when this will be done? Developer oriented stuff like this are necessary for the extensibility of elementor and as a result, should be a matter of priority.

**Comment by arielk** [comment]
I hope in the coming weeks.

**Comment by collizo4sky** [comment]
Please keep me in sync on this.

**Comment by collizo4sky** [comment]
@arielk any news on this?

**Comment by collizo4sky** [comment]
Any news

**Comment by joffcrabtree** [comment]
+1

**Comment by bainternet** [comment]
No docs yet but, while you wait for them, here is a simple starter points:

Contextual display of controls is easily done with the control's `condition` or `conditions` parameters, just take a look at almost any one of our widgets to see it in action( and code).

As for ajax request, simple ajax request, like any other you just need to make sure to update the control `options` once your ajax response is received and the whole thing needs to be triggered by the section being activated. something like:

```js
jQuery( window ).on( 'elementor:init', function() {
	function bindSectionActive( section, callback ) {
		elementor.channels.editor.on( 'section:activated', function( sectionName, editor ) {
			var model = editor.getOption( 'editedElementView' ).getEditModel(),
				currentElementType = model.get( 'elType' ),
				_arguments = arguments;

			if ( 'widget' === currentElementType ) {
				currentElementType = model.get( 'widgetType' );
			}

			if ( 'WIDGET_NAME' === currentElementType && section === sectionName ) {
				setTimeout( function() {
					callback( _arguments );
				}, 10 );
			}
		} );
	}
	bindSectionActive( 'YOUR_CONTROLS_SECTION_NAME', function(){
		// Do your stuff.
	})
});

**Comment by collizo4sky** [comment]
`almost any one of our widgets to see it in action` can you link to any of the widget on Github here so I can take a peep? @bainternet

**Comment by bainternet** [comment]
@collizo4sky 

lazy you!!! https://github.com/pojome/elementor/tree/master/includes/widgets

**Comment by bainternet** [comment]
[Developer docs](https://developers.elementor.com/) are now live, and more specify : [Creating a New Control](https://developers.elementor.com/creating-a-new-control/).

Thanks.
