### ISSUE TITLE
Elementor 404 erroe after updating 1.6.4

### ISSUE THREAD

**Issue by ARUNRS94** [pojome/elementor#2216]
after updating my elementor im getting 404 error while trying to edit with elementor.

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by ARUNRS94** [comment]
i tried all the steps u have mentioned but im getting the same error...pls help me

**Comment by ARUNRS94** [comment]
im getting the same issue in 1.6.5 also

**Comment by arielk** [comment]
Please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
