### ISSUE TITLE
Elementor 1.7 - Beta Release (RC3 updated)

### ISSUE THREAD

**Issue by arielk** [pojome/elementor#2220]
===========
## [RC3 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/2220#issuecomment-324676947)
===========

Hi everyone,

We have been working on version 1.7.0 for several weeks now, and are excited to share the new History feature for you to test out.

Please review the new features carefully, preferably on your staging sites and not in production.

### History

Back in version 1.1.0, we introduced the [revision history](https://elementor.com/v110-revision-history/). Now, we have added another layer of history, so versions are made for every action you make, not only after you press save.

Every action you make in Elementor is backed up, so you can trace your steps and undo / redo everything.

- Make some changes on the page (without saving)
- Click on the History icon in the bottom of the panel (Or press Ctrl + Shift + H)
- The history list will open, showing you all the actions you've made since you started editing.

You can still view all your revisions by going to: History > Revisions tab

### New Hotkeys

The history feature also comes with two new hotkeys for undo and redo:

- Ctrl / Cmd + Z (Undo)
- Ctrl / Cmd + Shift + Z (Redo)
- Ctrl / Cmd + D = Duplicate
- Delete = Delete element

We removed the 'Are you sure?' modal from the deleting function, so you can delete things easier. If you delete by mistake, just 'Ctrl-Z' it.

### Notes

If you are using Elementor Pro, please update to the latest 1.5.9 version for maximum compatibility.

Designated time for release: August 28, 2017

### Install Beta Version

If you still haven't enabled beta testing in Elementor, please follow these steps:

- Go to Elementor > Tools > Versions
- Enable the beta tester feature
- Go to Dashboard > Updates and update to the latest beta version

This will get you testing the new Elementor 1.7.0 RC3. You can also download the new version here:
https://downloads.wordpress.org/plugin/elementor.1.7.0-RC3.zip

**For bugs and remarks, please reply with a comment below!**

Many thanks for your support and help!

[Elementor Beta - Sign Up Now For Our Elite Group Of Early Access Testers](https://my.elementor.com/beta/)

**Comment by mandava** [comment]
Undo & Redo options are working nice. Thanks for adding the hotkeys, they are really handy. Any plans to introduce Undo & Redo buttons in the editor UI?

**Comment by tscheipi** [comment]
Very useful features that works fine here.

**Comment by nullmem** [comment]
If you make changes, then save, then use history to go back to the beginning of editing, the save button is still greyed out. This is the desired behaviour if I had not already saved. Now that I have previously saved the beginning of the editing is different than the live page so save button should be green.

**Comment by arielk** [comment]
## v1.7 Beta Version RC2

We just released a new beta version, please update your version to v1.7.0 RC2:

- New! - Hotkey: Delete = Delete element
- Fix! - Added compatibility for Multisite installation with Domain Mapping
- Fix! - CSS Animations names no longer minified, in order to prevent unexpected conflicts
- Fix! - Sometimes content in Repeater control disappears
- Fix! - Conflict rollback to the last version when beta testing mode enabled

Please update or download the new version here: https://downloads.wordpress.org/plugin/elementor.1.7.0-RC2.zip

Thanks everyone for your help and feedback!

**Comment by Manuel-SG** [comment]
> New! - Hotkey: Delete = Delete element
Wohoo. This is great!!! I just checked - it works very nice.

**Comment by arielk** [comment]
## v1.7 Beta Version RC3

Please update your version to v1.7.0 RC3:

- New! – Hotkey: Ctrl / Cmd + D = Duplicate
- Tweak! - Added color control for UI elements in the lightbox
- Twaek! - Added compatibility for Table of Contents Plus plugin (#2248)
- Fix! - Conflict with Polylang plugin (#2124)
- Fix! - Allow fullscreen in the editor preview for video player

@nullmem please check the save button again :)

Link to download: https://downloads.wordpress.org/plugin/elementor.1.7.0-RC3.zip

Thanks everyone for your help and feedback!

**Comment by tudormnt** [comment]
In RC3, hitting Cmd+Z after editing the title of an accordion item throws a JS error. This issue occurs for all widgets using **repeater** fields.

```
Uncaught ReferenceError: attrs is not defined
    at n.fillCollection (editor.js:8835)
    at n.onAfterExternalChange (editor.js:9044)
    at Object._triggerMethod (backbone.marionette.js:690)
    at n.triggerMethod (backbone.marionette.js:1944)
    at n.onSettingsExternalChange (editor.js:7697)
    at _ (backbone.min.js:1)
    at m (backbone.min.js:1)
    at f (backbone.min.js:1)
    at n.u.trigger (backbone.min.js:1)
    at n.setExternalChange (editor.js:3716)
```

**Comment by arielk** [comment]
v1.7 is here!

Thanks everyone for your help!!
