### ISSUE TITLE
[Enhancement Request] Equal outer section padding

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#2221]
Changing gaps between columns affects the main content width as well (see the screenshot below). 

![obrazek](https://user-images.githubusercontent.com/5634870/29495549-edda8130-85c1-11e7-89c6-1543f1d9d7a4.png)

It would be nice to have an option to maintain the content width the same. Actually it would be nice if it worked exactly as it is pictured on your website ;-)

![column-gap_small](https://user-images.githubusercontent.com/5634870/29495576-84f2ae76-85c2-11e7-8b05-621de1cb71f2.gif)

I suppose, it is well known issue/characteristic, since there are some custom CSS attempts to solve it but it would be nice to have it in the core.

**Comment by mmjaeger** [comment]
+1

**Comment by arielk** [comment]
This is actually what happens with the columns (see the source code), but we add some padding to the column so that the content does not stick to the edge of the column and will look good when you set a column background. If you have a better idea, we'd love to hear.

You can also read the discussion here: https://github.com/pojome/elementor/issues/452

Thanks for the feedback.

**Comment by black-eye** [comment]
Thanks for your reply. I actually know exactly, why this is happening and I know the negative-margin-on-parrent-row hack as mentioned on #452 (although I haven't found the thread before).

My point was, that it would be nice to have it managed by Elementor itself, rather than by the custom CSS (as mentioned on the other thread aswell). It could be managed on an on/off base.

Not sure whether you are working on the solution (hope you are, since the other thread is still open), in any case, I will address my future comments there.

Don't get me wrong, I actually love your plugin very much, these little tweaks could just make Elementor even geater.
