### ISSUE TITLE
Bug: Can't Reach The Section and Paragraph Buttons On An Elementor Section

### ISSUE THREAD

**Issue by LogoLogics2** [pojome/elementor#2223]
When using the "merge header" in GeneratePress and/or OceanWP theme, it's not possible to grab the edit section and edit the upper section ( because it is laying under the header ). One always needs to disable the merge header first, then edit, and then check the merge header again, which is very frustrating and time consuming.

**This is a known issue please look here:**
https://generatepress.com/forums/topic/transparent-header-for-all-pages/#post-366748)
**and here:**
https://generatepress.com/forums/topic/cant-reach-the-section-and-paragraph-buttons-on-an-elementor-section/

Until the recent Elementor update, this css workaround worked:
```
.elementor-editor-active .page-header-content {
    pointer-events: none;
}
```
Now, even that workaround does no longer fix this bug.
I started using Generate Press and OceanWP as they are recommended and are supposed to work seamlessly with Elementor. Please fix this bug and or provide a workaround that still works. Apart from this, love Elementor!!!

Thanks!
Annie

**Comment by LogoLogics2** [comment]
Hi,

In the Elementor FB community David Beckwit came up with a working solution for this.
( See topic here: https://www.facebook.com/groups/Elementors/permalink/1244610965664687/?sw_fnr_id=1246982896&fnr_t=0 )

**GENERATEPRESS**
Place this in the simple css:

**.elementor-editor-active .generate-merged-header .site-header {
display: none;
}**


**OCEAN WP THEME**
put this in custom css/js tab:

```
.elementor-editor-active .transparent-header {
display: none;
}
```
Ofcourse it would be better is this was fixed within Elementor, so it can work seamlesly with these ( Elementor compatible ) themes, without the need of tweaks in the themes itself?

Thanks,
Annie

**Comment by arielk** [comment]
As far as I know, OceanWP has added compatibility for this, I hope that GeneratePress will add soon.

Thanks for the solution!

**Comment by LogoLogics2** [comment]
Correct, I can confirm OceanWP has fixed this and I could remove the code!
