### ISSUE TITLE
How to create rows with columns in desktop view?

### ISSUE THREAD

**Issue by DerekBess** [pojome/elementor#2233]
I cannot figure out why this is not possible with the plugin. I'm in need of creating a section that houses three rows such as in the screenshot below. I cannot get this working, perhaps I am missing something but I do not see a pro widget for adding rows with one column.

![layout-mode](https://user-images.githubusercontent.com/4481041/29570481-93645f14-8724-11e7-9801-d0ee21b7a6c7.png)

**Comment by norewp** [comment]
First add a section via the "Add New Section" button

Then drag and drop the Column widget to the newlly created section - do this 3 times. You'll end up with 3 rows of 2 columns each.

Finally, proceed to delete a column from each of the 3 rows leaving you with 1 column in each row - add content and style as desired :)

**Comment by DerekBess** [comment]
@norewp thanks, however this doesn't give the ability to make one of the row 100%.
![columns-2](https://user-images.githubusercontent.com/4481041/29585106-f1ef27b0-8753-11e7-9f11-aa61ec7a5493.png)

**Comment by norewp** [comment]
Set the initial section to fullwidth with column gap set to No Gap.

Hover on the column you want to make fullwidth and select that section repeating the above process - see attached for example results

![multiple-columns](https://user-images.githubusercontent.com/30980808/29585737-25c834ce-8780-11e7-9b0e-6dad0a21ea3d.png)

**Comment by DerekBess** [comment]
@norewp thanks, that still isn't working as expected tho.

Essentially this is what I'm looking to mimic in terms of dumbed down code, which actually works in my framework but this client absolutely needed to use this drag and drop builder.
![column-3](https://user-images.githubusercontent.com/4481041/29586003-29e350da-8757-11e7-9b3e-379b31623334.png)


```
<section class="has_bg_cover">
    <!-- Content 1 -->
    <div class="container>
    <div class="row">
        <div class="col-6">Content Here</div>
        <div class="col-6">Content Here</div>
    </div>
    <!-- Content 2 -->
    </container>
    <div class="container>
    <div class="row">
        <div class="col-6">Content Here</div>
        <div class="col-6">Content Here</div>
    </div>
    </container>
    <!-- Content 3 -->
    <div class="bg_2">
        <div class="container>
            <p>Content Goes Here</p>
        </container>
    </div>
</section>
```

**Comment by DerekBess** [comment]
@norewp nevermind I'm dumb as fuck. I figured it out. Thanks for the help.

**Comment by filch** [comment]
Perhaps you could share with us?

**Comment by samuelnub** [comment]
haha no

**Comment by samuelnub** [comment]
no

**Comment by samjco** [comment]
Strange that this isn't straightforward in Elementor.
Whatever happened to simply make row or make column?
