### ISSUE TITLE
hello , how to hide this text editor 

### ISSUE THREAD

**Issue by ayoubsaadouni** [pojome/elementor#2234]
![capture_1](https://user-images.githubusercontent.com/26653718/29572918-83a5837e-8755-11e7-9db0-d7376fdb4b24.PNG)

## Environment

how to hide it

**Comment by norewp** [comment]
Check your active plugins as that is not an Elementor generated!

**Comment by ayoubsaadouni** [comment]
thnx norewp, Black Studio TinyMCE Widget is active
