### ISSUE TITLE
One column, specify width?

### ISSUE THREAD

**Issue by DerekBess** [pojome/elementor#2236]
Is it possible to only have one column and specify the width? I cannot for the life of me find an example of this. Screenshot included if that helps.
![one-column-split](https://user-images.githubusercontent.com/4481041/29586973-7847ba2e-875a-11e7-8ae9-a18f03a33d60.png)

**Comment by arielk** [comment]
I hope I understood well, but you can set the width of the boxed container under the Section settings, or just add right padding to the column/

**Comment by DerekBess** [comment]
This is what I'm asking. Adding padding is horsey approach guys.

<div class="container">
    <div class="row">
        <div class="col-9-tablet col-8-desktop">CONTENT HERE</div>
    </div>
</div>

**Comment by arielk** [comment]
I agree, you can also add more column with Space widget. If you have any other idea I'd love to hear.
