### ISSUE TITLE
[feature request] Setting the 'Unlink' Margins and Padding to Unlinked by Default

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2239]
Hey guys,

I'm loving negative margins, and use them across most of my site.

I prefer to use a percentage over pixels, so It's currently a two-step process where I need to always select % first over px, and then remember to unlink the controls to only affect one side of my section.

9 times out of 10, I always forget to unlink first and end up adding margin or padding to everything, instead of one side.

As useful as the linking feature is, being able to switch it off by default would greatly improve the UX, for me at least haha!

Thoughts?

**Comment by bainternet** [comment]
@enviedbymost 

This is more of a personal preference thing than a workflow blocker...

Currently, this feature is not supported, but we may look into it in the future in some kind of global preference settings.

Thanks for the feedback.
