### ISSUE TITLE
[feature request] Support for Emojis in Text (or Headings)

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2241]
Hey guys,

Many studies have concluded that consumers of your content are more engaged when you've used periodic emojis throughout your work.

Emojis can help to convey a message, especially those with less obvious undertones or sarcasm. As a person from the UK, I love me some sarcasm ;)

It's amazing how the tone of text can be transferred just by using an emoji. A blunt 'Hello' is now a fun, and friendly 'Hello' when used alongside a sunglasses wearing emoji.

Please please consider support for emojis in future versions of Elementor!

Thanksssss

**Comment by bainternet** [comment]
I can happily tell you that we are actively working on adding Emojis options to Elementor.

**Comment by enviedbymost** [comment]
Hey bainterest,

Is this still the case?! :)

**Comment by shilo-ey** [comment]
Hi @enviedbymost, 

Thanks for your feedback,
We will not implement this feature in our releases soon.
However, [in this article](https://developers.elementor.com/creating-a-new-control/#Simple_Elementor_Control), you can see how you can add this feature using custom code.

Thanks
