### ISSUE TITLE
Use without Wordpress?

### ISSUE THREAD

**Issue by vladdu** [pojome/elementor#2244]
I am looking for a frontens editor that will work with other CMS than WP, preferably a generic one that can work with all of them with the right adapters. Elementor looks very cool and thus I'd like to ask if (with the current architecture) it would even be possible to start to consider this thought - or is WP deeply hardcoded? If the latter, is there any kind of interest to change it?

**Comment by KingYes** [comment]
No, Elementor is only for WordPress.

Ref: https://github.com/pojome/elementor/issues/1096
