### ISSUE TITLE
[Feature request] Label for missing pro widgets in templates for free users

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#2245]
If I create a template and add the form widget (or any pro widget), pro users will see the form, however, free users don't see anything. The form widget is completely missing without any explanation. In certain cases this makes it seem like the template is broken or installed incorrectly.

Could there be some sort of notification, label, or box or free users that says "This widget is only available with Elementor Pro" or something like that? I think that might help make it more clear.

**Comment by arielk** [comment]
I merged this issue with another issue #1055 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
