### ISSUE TITLE
Button Size Icon size and align to center HTML widget

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#2247]
1) Add the option to change the size of the icon of the button;

2) The possibilite to change the size of the button, like 100% width;

3) Options to align the HTML widget.

4) Put the Underline option on text widget

BUGS: The BOXSHADOW of the columns are not working properly, you can't paste the rgba color.

**Comment by silvioghedin** [comment]
5. Customize differents types on text widget like LINKS, H1, H2, P... (hover too)

**Comment by arielk** [comment]
>Add the option to change the size of the icon of the button;

Basically you can change the font size of the text for change the icon size also, but maybe we add it in the future

>The possibilite to change the size of the button, like 100% width;

You can do it by Alignment control > Justified 

> Options to align the HTML widget.

You can change the font size of the text for change the icon size also

>Put the Underline option on text widget

You can use `Ctrl + U` for it (please [read more here](https://wptavern.com/wordpress-4-7-removes-the-underline-and-justify-buttons-from-the-editor))

> BUGS: The BOXSHADOW of the columns are not working properly, you can't paste the rgba color.

Please read this issue https://github.com/pojome/elementor/issues/298

> Customize differents types on text widget like LINKS, H1, H2, P... (hover too)

That something that come from your theme.

Thanks for your feedback!
