### ISSUE TITLE
Elementor doesn't work with Table of Contents Plus

### ISSUE THREAD

**Issue by cedri7c** [pojome/elementor#2248]
I downloaded the Table of Contents Plus plugin, added the shortcode "[toc]" to add a table of content to my page where I wanted it to be , hit save and went to display the page to see if it worked, it did.
But after I tried editing the page with Elementor again it first tried to load and then there was a white screen, had to disable the plugin to make Elementor work again.
Really hope this can be fixed since I need table of content, and the plugin is very good.
Link: https://de.wordpress.org/plugins/table-of-contents-plus/

**Comment by arielk** [comment]
Fix for v1.7.0

Thanks for your feedback!
