### ISSUE TITLE
Suggestion - Widget Advanced Tab - Margin Auto

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#225]
For margins allow "auto" to be set for positioning such as centering vertically or horizontally.

**Comment by arielk** [comment]
I'm very sorry, but after several attempts to solve it, I don't see a way to deal with this issue for now. I think the best way is to write some custom CSS to do this.

So at this time I close the issue. Thanks for your feedback!

**Comment by Slapbox** [comment]
Anything changed since 2017? No `auto` makes some things a real headache.

**Comment by ibqn** [comment]
Are there plans for reopening this issue?

**Comment by ttodua** [comment]
I don't know too, why 'auto' will make problems, rather then solve our problems?

**Comment by pingram3541** [comment]
A simple checkbox could provide this that when selected disables the margin left and margin right fields and reveals a greyed out "auto" which renders on the front end just like custom css would.

**Comment by pingram3541** [comment]
@arielk please reconsider such a simple request.

**Comment by Slapbox** [comment]
@arielk I would hope that this would be made possible by some of the upgrades made in the past 4 years? If the team isn't able to find a path to supporting this feature even now then I think that bodes poorly for the future of Elementor.

**Comment by arielk** [comment]
Hi @pingram3541 @Slapbox, 

We are going to add this feature to the next version of Elementor (v3.1.0). You can follow this issue: https://github.com/elementor/elementor/issues/11997

Thanks

**Comment by pingram3541** [comment]
Thanks @arielk this is great news.  FYI, that linked issue seems to be for the "Tab" widget only whereas this is referencing the Advanced Tab margin settings of every widget...but I'm sure you know this already.

**Comment by arielk** [comment]
> Thanks @arielk this is great news. FYI, that linked issue seems to be for the "Tab" widget only whereas this is referencing the Advanced Tab margin settings of every widget...but I'm sure you know this already.

Oops my bad :( 
I was confused because of the title, these are the right issues to follow:
https://github.com/elementor/elementor/issues/3319
https://github.com/elementor/elementor/issues/2219

**Comment by Slapbox** [comment]
Does this mean that margin auto still isn't planned to your knowledge @arielk? Because it would be astonishing if this still isn't even planned four years later. Four years of asking for `margin: 0 auto` support.

**Comment by pingram3541** [comment]
@arielk Please correct me if I'm wrong.

@Slapbox I think the goal is to combine many of these similar type requests into one big update.  From what I gather...

- Ability to set margin auto - this request
- Ability to set each padding/margin position value individually instead of defaulting all to 0, i.e. instead of padding 40px 0 0 0, it would just be padding-top: 40px while the rest use either default values (desktop) or assume values from previous break point until the designer actually wants to place values for those other positions.
- Ability to change each padding/margin value unit type, i.e. padding-top: 40px, padding-bottom: 10%

I'd like to add it would even be beneficial when viewing in tablet and mobile break points, if the margin/padding/font-size etc when not being overridden specifically for that break point, showed us a greyed out value of what was set previously in the next higher breakpoint so we don't have to manually switch between modes just to be able to reference what is already set, especially the unit type chosen such as px, em, rem.

The challenge for all of these requests being, to provide the most granular level of changes without 1) breaking existing sites and 2) without making the editor so complex non-code/web dev users will never use it.

**Comment by arielk** [comment]
Correct!

@pingram3541 I could not write it as well as you, so thank you!

**Comment by nicholaszein** [comment]
This issue was solved with the release of Elementor v3.10.
