### ISSUE TITLE
Conflict with Siteorigion Widgets

### ISSUE THREAD

**Issue by sujaypawar** [pojome/elementor#2250]
I came across an error that said the content area was not found as you can see in this screenshot:
http://screenshots.sharkz.in/sujay/170824140351.png

When I debugged further, it seems is is an conflict with a widget from SiteOrigin Widgets bundle:
http://screenshots.sharkz.in/sujay/170824123314.png

When Call to Action widget is disabled, the error goes away. I believe this is what needs to be done - 

1. Improve the documentation and explain why this might be happening. [Existing article](https://docs.elementor.com/article/56-content-area-not-found) does not cover this case.
2. Resolve this conflict if possible :)

**Comment by arielk** [comment]
It looks like they have released a new version with compatibility to Elementor, you can see [it here](https://wordpress.org/plugins/so-widgets-bundle/#developers): 
> 
> 1.9.9 – 31 August 2017
> - Fixed compat with latest Elementor update.

Please try updating the plugin and see if it works for you.
