### ISSUE TITLE
Video Widget play button only with lightbox on click

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2257]
Hello. Some situations like [this](https://www.smartpassiveincome.com/passive-income-101/) we need the play icon only and video lightbox on click.
I have my own case [here](https://wplovers.pw/podderzhka-sajtov-na-wordpress/) (in russian, but simly sroll to 2-nd section with mass of icons and video icon). The trick is in 1px transparent png video cover but it's "ax and felt boots" method =)

Thats will be nice to have this function from the box. Thanks!

**Comment by arielk** [comment]
I think it has to do with another issue #628, so I merged this issue so we could deal with it more efficiently.

Thanks for your feedback!
