### ISSUE TITLE
Developer Request - Port Customizer Plugin to Elementor

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#226]
I wrote a live css editor for the customizer that I use on literally every site.  It currently uses Kirki for the controls and I wrote custom functions to pass post meta to the customizer controls in which I provide live css and js editing via codemirror integration w/ user definable breakpoints and drag resize of the customizer preview window.  The core ability is to provide quick access to site-wide css/js, page specific custom css/js and also woocommerce shop/product custom css real-time during the design process.  All of which can be converted easily to static files after development and I have future plans to automate toggling loading of dynamic styles vs static and adding things like a floating color palette picker for rapid access to common hex/rgba values.

I'd like to port this over if possible to eliminate the back and forth when editing the front end since Elementor is so awesome but for some reason decided not to use the front end customizer backbone.js control system that WP provides already for live front end editing purposes.

Is this something you would take into consideration?

This could be a really great example of a feature rich 3rd party integration to promote other developers to do the same and while I have interest in monetizing my efforts somewhere down the road, my idea is to first release this into the wild as an open source offering.  Design tools should be free!!!

**Comment by yehudah** [comment]
Hi,

Thanks for the great feedback.

We want to develop something more solid and less dependent on the core changes.
For now I don't believe that change will happen.

We hope to release in the next weeks our API so can check it and see if the port work for you with our existing development.

**Comment by pingram3541** [comment]
I think as long as I have access to post meta and wp_options I'm good.  Admittedly I was also probing to see if something along this lines was already underway and whether to holster my efforts =)

Once I have something to prototype I'll share back on this thread.
