### ISSUE TITLE
Columns width bug in tablet mode

### ISSUE THREAD

**Issue by NailKhalimov** [pojome/elementor#2260]
Column width settings don`t work correctly in tablet mode
You can see the bug, after this steps:

1. Create a section with 2 columns and set structure 33% to 66%. After this, choose columns and do this: 

2. Set column width of these columns to:
     mode: Desktop
     1st column, width: 33 %
     2nd column, width: 66%

     mode: Tablet
     1st column, width: 100 %
     2nd column, width: 100%

3. After this look at the generated page. Resize the window to laptop(smaller than 1024 px). Now you can see, that first column is 33% and second column is 66%. But we have set them to 100% and 100%. Please, fix it.

**Comment by arielk** [comment]
This problem rarely occurs only in older PHP versions (<7), please update to PHP 7+ and this should work correctly.
