### ISSUE TITLE
Entrance animation issue

### ISSUE THREAD

**Issue by Zarioza** [pojome/elementor#2265]
## Description

Problem is on the Entrance animation for fadeIn, bounce etc. effects in **edit mode**. When the animation is finished the whole section disappears. Some effects such as Slide in  works fine in edit mode.
This bug doesn't exist on the frontpage.

## Steps to reproduce

Select some section end add Entrance animation effect fadeIn Down.

## Environment

WordPress: 4.8.1
Elementor: 1.6.5

## Suggestion
I  found the problem is in editor-preview-rtl.css file at line 74.
```
#elementor .animated {
  -webkit-animation-fill-mode: none !important;
          animation-fill-mode: none !important; }
```
If  animation-fill-mode is set to both everything works fine.

**Comment by arielk** [comment]
Which browser are you using?

**Comment by Zarioza** [comment]
Browser: Chrome Version 60.0.3112.90 (Official Build) (64-bit)

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.18 (Ubuntu)
	MySQL version: 5.7.19
	PHP Version: 5.6.31-2+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	Elementor Library: Connected

**Comment by arielk** [comment]
Can you share with us a link to this page?

**Comment by Zarioza** [comment]
No, It is on localhost :(

**Comment by Zarioza** [comment]
It works good on frontend only problem is in editor mode.

**Comment by arielk** [comment]
Sorry, couldn't replicate the issue. Might be a theme or plugin conflict...

In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by joshmarom** [comment]
I was trying to replicate this issue with no success.

**Comment by educaaccioninteligente** [comment]
The problem appears when you select you select an template that is "elementor canvas", if you do that whe animations does not function, but if you select another template like "frontend" of "fullwidth" the animatios looks good.

I think the template "elementor canvas" disable by mistake this options, that is clearly a problem of the plugin.

What do you think, do you can replicate?

**Comment by greenhat13** [comment]
I did have the same problem but turned out to be a conflict of page builders. If you have other page builders installed, deactivate them and try loading the page in incognito.

**Comment by educaaccioninteligente** [comment]
It was solutioned doing this things.
1 Deactivate all the plugins Including Elementor and Elementor Pro
2 Start activating again elementor and elementor pro
3 Now function well the animations
4 After the problem solved activate the other plugins 1 by 1 and checking everything is ok
5 If you find there is a problem with some plugin maybe that plugin will not be compatible with Elementor
