### ISSUE TITLE
Images doesn't resize well in Caroussel while responsive

### ISSUE THREAD

**Issue by Nat-Faeeria** [pojome/elementor#227]
I'm trying to use the Elementor caroussel element to display some images. When I resize my screen, the images doesn't always resize well. Sometimes I only have one slide (as I have precised while configuring the element), but on others screen sizes I have multiple images displayed.
My images are all 1500px wide. From 480px to 766px (included), two images are displayed, the images doesn't resize (I tried to precise "stretch" to see if it would work, but the behaviour is the same). 
I have tested on Mozilla Firefox, Chrome and Mozilla Firefox for mobile.

**Comment by yehudah** [comment]
Hi,

Really hard to produce the problem from your description.

What image size did you choose ?
can you create a page that show the problem you talking about ?

**Comment by Nat-Faeeria** [comment]
To reproduce the problem, use images 1500px wide in the Caroussel element, and put it in a full width section on a page.
Then, use your navigator responsive mode, and try any screen size between 480px and 766px in width.

I think it is a problem in the responsive rules. I saw that the screen width settings in Elementor's responsive mode are set precisely around this zone (480px-766px) that doesn't work.

**Comment by yehudah** [comment]
I think you talking about a few issues I will try to make them clear:

- Just under 768px the carusel doing internal calculate and ignoring the number in the settings.
- If you used our responsive emulator ( bottom left panel ), he does have a problem showing the correct resizing. You can try from a chrome emulator ( F12 and then Ctrl & Shift & M ) or real mobile.

Hope this will help.

**Comment by Nat-Faeeria** [comment]
No, what I mean is that : 
    - under 768px and above 480px, the caroussel is doing internal calculate
    - this issue is not shown by the responsive emulator, because it is just 1px above and under the critical values, which leads me to think the problem may come from css media queries. It may be that a new breakpoint should be added.

**Comment by arielk** [comment]
Fixed https://github.com/pojome/elementor/commit/2677b9d04f1ceaca45a311f230d39b255024650d 
https://github.com/pojome/elementor/commit/eebaf0a2e4445f86318d4080e128dc342789d18c
