### ISSUE TITLE
Keyboard control for the lightbox swiper

### ISSUE THREAD

**Issue by Hilal-r** [pojome/elementor#2270]
Added a gallery with elementor. When I click an image and the lightbox pops up I can't navigate using the arrow keys. This is an option that comes built in in the swiper you are using, it just needs to be enabled.
There should be an option to enable it, or a way to access the swiper instance so I can code it myself.

Additionally, in WordPress Theme Options > Lightbox,  there’s an option called “Arrow Key” and it’s enabled but it doesn’t seem to be working.

**Comment by arielk** [comment]
Fix for v1.7.3

Thanks for your feedback!
