### ISSUE TITLE
Feature Request: delay functions (ms) for background images hover effects

### ISSUE THREAD

**Issue by guaser** [pojome/elementor#2271]
First time on github so sorry if I did not successfully tag or used the appropriate format for a Feature Request ...

I just wanted to suggest the possibility to add a "delay" option/field for sections / elements Style>background hover effects, so we can set a delay in ms before the hover transitions trigger...

It's not really a vital request, but it adds nice animation/interaction possibilities when used along elements animations :)

Thanks and congrats for such an awesome tool!

**Comment by arielk** [comment]
We have no plan at the moment to add this possibility, but maybe in the future.

Thank you for your feedback!

**Comment by guaser** [comment]
:)

Sergio Gabriel Durré Irizar.

es.linkedin.com/pub/sergio-durre/a1/7a1/255/es
https://gabirizar.myportfolio.com/ <https://www.behance.net/gabidurre>

2017-09-08 16:18 GMT+02:00 Ariel Klikstein <notifications@github.com>:
