### ISSUE TITLE
Slides element performance on mobile

### ISSUE THREAD

**Issue by nicomollet** [pojome/elementor#2274]
## Description

I am using the Slides element for a slideshow.

Images are applied to the background. They are big images for desktop (2500 px wide).
But on mobile it's the same images that are used. The performance on mobile is bad.

Do you consider adding options to have responsive background images, for a better mobile performance?

Thank you.
Nico

## Steps to reproduce

See it in action on my website https://www.saintmalogolf.com/
And the pagespeed report (https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=saintmalogolf.com).

**Comment by arielk** [comment]
I merged this issue with another issue #2355 in the same subject so we could deal with it more efficiently.

Thanks for your feedback!
