### ISSUE TITLE
Animated Headline Spacing Problem

### ISSUE THREAD

**Issue by cavalierlife** [pojome/elementor#2277]
Rotating Headline Style has an issue:

If using the Typing animation, everything is fine, but if any of the other animations are used, and multiple words are used that are of differing lengths from one another, Elementor will use the longest word to split the Before and After text, and the shorter words will be followed by a large space.

Below are some screenshots, and you can see a screencast at http://screencast-o-matic.com/watch/cbjuoolWFF

<img width="431" alt="bigspace" src="https://user-images.githubusercontent.com/28687464/29780373-2c28d5f8-8bdb-11e7-8813-1d80d2aff60f.PNG">

<img width="421" alt="nospace" src="https://user-images.githubusercontent.com/28687464/29780375-2c2d630c-8bdb-11e7-9dd4-caaa08f09d51.PNG">

## Environment

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | 10.0.31 |  
PHP Version: | 7.0.22 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
Elementor Library: | Connected |

**Comment by arielk** [comment]
This issue already fixed in the latest version 1.6.1 
Please update, and let me know if it solved the problem!
