### ISSUE TITLE
DATE_TIME not working.

### ISSUE THREAD

**Issue by chayaneng** [pojome/elementor#2278]
## Description
I am building custom plugin based on Elementor. I had to use the DATE_TIME control to develop a module count down timer. when I use DATE_TIME I can see it is not working. In the input field it is showing nan-nan value and on the console of google chrome "dtpicker- Call the onHide handler".

![capture](https://user-images.githubusercontent.com/14146133/29780540-04419a54-8c38-11e7-8728-b14ec112cb13.PNG)

I am really messed up with. Can you please check on it.

This is my codes 
              `$this->add_control(
			'pcdt-date-time',
		  	array(
		     	'label'			=> __( 'Target Data and Time', 'premium_elementor' ),
		     	'type' 			=> Controls_Manager::DATE_TIME
		  	)
		);`

**Comment by arielk** [comment]
I merged this issue with another issue #2095 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
