### ISSUE TITLE
[Enhancement Request] checkbox custom icon

### ISSUE THREAD

**Issue by dabouncer071** [pojome/elementor#2279]
Hi Guys,

I have used your email module in the pro options and added my own custom images to the check box instead of the normal tick.

My issue is, with your current code in "elementor-pro/modules/forms/classes/form-base.php" on line 122 you have `id="' . $this->get_attribute_id( $item_index ) . '-' . $key . '"`.

With the above line of code it wont add pair the Label and Text Input together (needed to make it work), I have to alter the `get_attribute_id( $item_index )` to `get_attribute_id( $item )`.  This little change always seems to work.

Is there a chance this can be made as default? 

https://www.geesactive.co.uk (near bottom) is where i am using this, if you would like to look to see what I mean.

**Comment by arielk** [comment]
Fixed for the next version of E-Pro 1.8.0

Thanks for your feedback!
