### ISSUE TITLE
Add Registration Form for Email Marketing

### ISSUE THREAD

**Issue by moskoweb** [pojome/elementor#228]
It would be interesting to have an element that was possible to paste the HTML code of a form of email marketing system, and could edit the form with the Elementor design.

**Comment by luizeof** [comment]
@moskoweb you can use the HTML Widget to paste any HTML, CSS or Javascript code.

**Comment by moskoweb** [comment]
Yes, but not is all email marketing system have form builder.

**Comment by yehudah** [comment]
Hi,

Thanks for your feedback.

This not fitting for what we plan for the builder.

**Comment by moskoweb** [comment]
Thanks.
