### ISSUE TITLE
Post grids: More meta data please

### ISSUE THREAD

**Issue by zaehlpixel** [pojome/elementor#2288]
At the Moment, the Post grids Element lets me integrate Date, Time, Author and Comments and Meta Data below my Post title. What about category or special other taxonomies? They're missing. Please add the options, also for custom post types, to add taxonomies in the Meta data.

(Example: I have an overview of portfolio projects shows as post grids, but I want to show the category, too).

**Comment by arielk** [comment]
I merged this issue with another issue #1071 in the same subject so we could deal with it more efficiently.

Thanks for your feedback!
