### ISSUE TITLE
[Feature Request] The ability to edit text directly on the page

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#2289]
At the moment to edit the text in a 'Text Element' you have to select the text element then move to the text editor window in the Elemetor side bar to edit the text. It would be a) more efficient and b) more convenient to be able to "double click" on the text in the text element and to be able to edit the text 'on the page' rather than in the sidebar.

**Comment by WPDevHQ** [comment]
Time to explore editable modules :)

**Comment by arielk** [comment]
I merged this issue with another issue #437 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
