### ISSUE TITLE
Pro elements are not initated if i make my custom elements

### ISSUE THREAD

**Issue by markusila** [pojome/elementor#2291]
## Description
If i create custom element and then enable elementor pro - most of the pro elements are not initiated. My custom element is initiated normally, but not the pro ones

## Steps to reproduce
```

class ElementorCustomElement {
	private static $instance = null;

	public static function get_instance() {
		if ( ! self::$instance )
			self::$instance = new self;
		return self::$instance;
	}

	public function init(){
		add_action( 'elementor/init', array( $this, 'widgets_registered' ) );
	}

	public function widgets_registered() {



		if ( defined( 'ELEMENTOR_PATH' ) && class_exists( 'Elementor\Widget_Base' ) ) {

			if ( class_exists( 'Elementor\Plugin' ) ) {
				if ( is_callable( 'Elementor\Plugin', 'instance' ) ) {
					$elementor = Elementor\Plugin::instance();
					if ( isset( $elementor->widgets_manager ) ) {
						if ( method_exists( $elementor->widgets_manager, 'register_widget_type' ) ) {

								require_once plugin_dir_path(__FILE__).'widgets/donation-widget.php';
								

						}
					}
				}
			}
		}






	}
}
ElementorCustomElement::get_instance()->init();


```

**Comment by WPDevHQ** [comment]
That is not the way to create Custom Elements for Elementor! The correct way is to extend the Widget_Base class.

Either follow the method in the Hello World sample plugin: https://github.com/pojome/elementor-hello-world

Or use the Starter plugin found here: https://github.com/norewp/elementor-starter

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
