### ISSUE TITLE
Mobile responsive modifications issues

### ISSUE THREAD

**Issue by fimason** [pojome/elementor#2296]
I have an issue with creating mobile responsive modifications for tablet.

Layout mods for tablet and mobile look great in preview, but are not reflected on my iPad mini, which has bunched sections, squashed columns and unhelpful gaps. I'm getting around the issues through trial and error, preview is not providing an accurate rendition. However, as I don't have an iPad or another tablet, I am not confident about the appearance across platforms, which makes me very nervous about going live with the site.

Some page & site builders I've looked at provide desktop, mobile and two other tablet options. 

Is this something that can be looked at?

Thanks.
~ Fi

p.s. the site is www.wordafterword.org.uk and the pages two elementor created pages in questions are homepage and Retreats

**Comment by arielk** [comment]
I merged this issue with another issue #2043 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
