### ISSUE TITLE
Popup Maker window close after form submit

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2298]
Hello! There is one of the best popup plugin Popup Maker. And now it integrates with Contact Form 7 and others with on submit events.
The first is — open another popup after submit, for example — thank you popup. The second is — close popup after submit with delay.
It will be nice to see the same function in Elemenor Pro forms.

Thanks!

**Comment by arielk** [comment]
Is there any official trigger for this? API or something like this

**Comment by parfilov** [comment]
Maybe [here](http://docs.wppopupmaker.com/category/325-on-form-submit-actions)

**Comment by bainternet** [comment]
You can catch the for submitted event and close the popup according to this: 
https://docs.wppopupmaker.com/article/46-how-to-close-a-popup-when-form-is-submitted

```JS
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		// Form has been submitted  
		// Set cookie
		jQuery('#popmake-SELECTOR').trigger('pumSetCookie');
		// Close popup
		jQuery('#popmake-SELECTOR').popmake('close');
	});
});
```

**Comment by viveksingh4045** [comment]
in which file I need to add this jquery code, sry I am new to this thing
