### ISSUE TITLE
[Feature request]  Independent show/hide control for portrait/landscape layouts in tablets

### ISSUE THREAD

**Issue by Xtrelia** [pojome/elementor#2299]
Elementor's responsive show/hide control is very useful to fit contents for any device.

There is a clear difference when displaying content in a desktop or a mobile device. However, tablets are in an intermediary step between desktops and mobile devices.

When displaying contents in a tablet landscape mode this is more like to display them on a desktop but in portrait mode, the look should be close to mobile devices.

So, it could be useful to have a better control on the Responsive section of each Elementor widget having different show/hide control for portrait/landscape modes on tablets.

Jorge

**Comment by arielk** [comment]
I merged this issue with another issue #2043 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

More ref: #78
