### ISSUE TITLE
[Bug] Ctrl + Z doesn't restore custom elements like Elementor Devices

### ISSUE THREAD

**Issue by CiriousJoker** [pojome/elementor#2301]
My setup:

[section]
[section]
two columns with an Elementor Device in one of them
[/section]
[/section]

**Comment by arielk** [comment]
Sorry but I don't understand exactly, please try to explain better that we can check it out.

**Comment by CiriousJoker** [comment]
Here's what it looks like:
https://gyazo.com/561e6547b18c90cee9f88fac8d1fc001

Seems like buttons are gone too.

I did the following there:
- Create a section with two columns
- Remove the whole section
- Press ctrl + z

**Comment by arielk** [comment]
Fix https://github.com/pojome/elementor/commit/e181dc4be29ab0b33d90fb26d654860fa42b94b2

Thanks for your feedback!
