### ISSUE TITLE
[Feature Request] Center the whole list instead of list items

### ISSUE THREAD

**Issue by CiriousJoker** [pojome/elementor#2305]
Lists look a bit weird on tablets if the list has to start at the same x coordinate and the columns is way broader than the list.
Centered buttons below that list are displayed centered, but the list is too far left.

**Comment by arielk** [comment]
What list are you talking about?

It would be nice if you could better clarify the point. 

> If you're requesting a new feature, explain why you'd like it to be added. Try to add as much detail as you can, and be specific. (From the guidelines)

Thanks.
