### ISSUE TITLE
[Feature Request] Draggable Slider Control

### ISSUE THREAD

**Issue by CiriousJoker** [pojome/elementor#2306]
You can drag over a number picker (up and down) to change its value, similiar to Photoshop and Thrive Architect.

**Comment by arielk** [comment]
Do you mean something like that? https://github.com/pojome/elementor/issues/1165

**Comment by CiriousJoker** [comment]
Nope, but that one would be amazing as well (if it was accessible via shortcut and not the usual editing screen).

What I mean is that you can click on a numpicker and drag up and down to change its value. This functionality is available in the Thrive Architect.

Here's a .gif of what it looks like:
https://gyazo.com/afe16430815fdcc3a29046110eebaa43

The preview updates while dragging

**Comment by arielk** [comment]
This is something completely different than I thought :)

Thanks for your feedback!

**Comment by maxwellhibbert** [comment]
I second this!

**Comment by bainternet** [comment]
You can already drag the range control left/right and you can even scroll up/down inside the input which gives the same effect.

thanks for the suggestion.
