### ISSUE TITLE
custom form using html like optimizepress does

### ISSUE THREAD

**Issue by csp10** [pojome/elementor#2307]
Hi it will be great if you can create a custom form field like Optimizepress does as well video overlay widget. It will encrease all capabilities of this greate builder

thanks

**Comment by arielk** [comment]
Have you tried [Elementor Pro](https://elementor.com/pro-v140-form-integrations/)?

Can you give an example of what you mean?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
