### ISSUE TITLE
How do I make it so the google bot doesn't count my empty design element section as the first section?

### ISSUE THREAD

**Issue by cedri7c** [pojome/elementor#2313]
Hi,
I've added a section in light grey right under my main menu on top, on the frontend it creates a nice thin line that splits my content site from the header so I'd like to keep it.
The problem is that my SEO plugin obviously treats this painted section that serves as a header style element as a normal empty section.

So when I optimize the site for SEO I get the following message:
"The focus keywoard doesn't appear in the first section of the text"

I'm not sure how this will affect my SEO but how can I make that line without having an empty section?
I'd prefer it if I wouldn't have to do the whole site over ofc.

**Comment by arielk** [comment]
I don't think there's any problem in this case, but you'd better consult with SEO experts about it.

Thanks
