### ISSUE TITLE
Toggle items not expanding in Chrome or Firefox

### ISSUE THREAD

**Issue by mertxu** [pojome/elementor#2314]
I have several toggle menus/lists on my site. They work on some devices but seem to be bugged in Chrome and Firefox.

The list appears but when an item is clicked, it doesn't expand.

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by peterskaife** [comment]
Done all this. Toggle plugin still does not open.
I added Accordian plugin and it ALSO does not open.
I have contacted support at Elementor, and am waiting for help.
