### ISSUE TITLE
Feature request: show related posts

### ISSUE THREAD

**Issue by lucyinsisu** [pojome/elementor#2316]
It will be handy if related work could be shown at the end of each portfolio post. I'm using yuzo plugin to solve the problem but it conflicts with elementor.

**Comment by parfilov** [comment]
You can do this now with [Elementor Pro](https://wplovers.pw/r/elementor/) using portfolio widget. Show related by tags, categories or by hand. Just create the template, save it and reuse.

**Comment by amindiary** [comment]
@parfilov it not works like that! in single page of portfolio, how can I set that widget show other posts that listed in same category? 
for example, I want in single post X that are in category Y, related posts with SAME CATEGORY OF POST X show. how can I reach that?

![image](https://user-images.githubusercontent.com/2544046/44463373-2d103000-a620-11e8-8361-e14daace337f.png)

**Comment by parfilov** [comment]
@amindiary It looks like I made a mistake. Clearly, we need to create new issue and ask developers to add "Same as current" option to Categories and Tags fields. Can you do this?

**Comment by amindiary** [comment]
@parfilov yeah
