### ISSUE TITLE
some items are missing from the dashboard after installing the theme 

### ISSUE THREAD

**Issue by seengafus** [pojome/elementor#232]
Hi , I activated BUZZ theme from pojo ... I wanted to change the header for quite a time , now I realized that some items are missing from the normal dashboard ...    is there a way to have them back?
![06-10-37 02-41-22](https://cloud.githubusercontent.com/assets/20388105/16716932/371792fa-4713-11e6-84f0-84b2516198c9.jpg)

**Comment by seengafus** [comment]
and when I go to customize header , I can't change text...   I can only change colors !
![header_cus](https://cloud.githubusercontent.com/assets/20388105/16717147/d7d162fc-4718-11e6-8d5b-8f4200738006.jpg)

**Comment by yehudah** [comment]
Hello,

The **"Header"** option allow to change image based on site design.
You can change text on **"Site Identity"**.

This is support issues to the Elementor plugin from Pojo,
to get support to other products please use the support forums in this link:
[http://support.pojo.me/forum/support/](url)

Thanks

**Comment by seengafus** [comment]
I relized that I have to remove the logo first ,
