### ISSUE TITLE
Social Icons Spacing not working

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2321]
Hello! Subject. They just stick to each other and no margins.

Thanks!

**Comment by arielk** [comment]
Can you share with us a link to this page or steps to reproduce this situation?

**Comment by parfilov** [comment]
Here it is https://wplovers.pw/elementor-rus/#ready Cache cleared. The Spacing is 30.

Also, pay attention how are progress bars works at the same section. They are late when scrolling and works almost at the top of page.

**Comment by arielk** [comment]
I see that there is a `<noindex>` tag where does it come from?

Anyway you can add this CSS to solve the problem:
```
.elementor-social-icons-wrapper {
    font-size: inherit;
}
```

**Comment by parfilov** [comment]
Oh! It's WP No External Links plugin.  I'll have to look for another solution for hiding links from indexing.

Thanks!
