### ISSUE TITLE
[Feature Request] Set separate page title in Elementor

### ISSUE THREAD

**Issue by CiriousJoker** [pojome/elementor#2322]
I know, I can set the page name/page title in Elementor, but that also changes the name shown in Wordpress>All Pages.

I want to be able to set a page name (eg. "Freebie") and a separate page title (eg. "Your free gift is here").

I don't know if this is technically possible, but if it was, it would be amazing!
I haven't found anything to solve this issue on the internet though :(

**Comment by arielk** [comment]
You can hide the title and choose which title you want and add another title using a Heading widget.

You can learn more about the subject here: https://docs.elementor.com/article/193-page-settings

**Comment by CiriousJoker** [comment]
This is not what i wanted. I don't mean the h1 heading of the page, but the actual page title shown in the tab.

I want to have something like this:

Wordpress > All Pages > Something:

<title>Something else</title>
