### ISSUE TITLE
[Feature Request] Code Editor for html elements

### ISSUE THREAD

**Issue by CiriousJoker** [pojome/elementor#2323]
I'd love to have a code editor with syntax highlighting instead of the normal html editor. A bonus would be if this editor could be opened as a popover when clicking on the html element.

**Comment by arielk** [comment]
This is something we already have in an HTML widget. I've included a screenshot with an example code editor: http://i.imgur.com/zKshjSR.png

You can also expand the panel and the code editor as much as you want.

Thanks for your feedback.
