### ISSUE TITLE
Accordion widget looses some of its content while editing.

### ISSUE THREAD

**Issue by lukasalperowitz** [pojome/elementor#2324]
## Description

Accordion widget looses some of its content while editing.

## Steps to reproduce

* Add an accordion widget
* Add 8-10 entries
* Fill in header and content
* Save the page

Exspected behavior:
* All entries with header and contents are stored and visible on page

Actual behavior:
* Headlines of all entries are stored and visibile
* Content of some (2-3) elements is empty, content entered before is gone.

## Environment
		
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.27 (Unix)
	MySQL version: 5.5.5
	PHP Version: 5.6.31
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.1
	Site URL: http://new.nightoftheprogfestival.com
	Home URL: http://new.nightoftheprogfestival.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 128M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Active

== Theme ==
	Name: Twenty Seventeen Child-Theme
	Version: 1.0
	Author: Lukas Alperowitz
	Child Theme: Yes
	Parent Theme Name: Twenty Seventeen
	Parent Theme Version: 1.3
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

== Active Plugins ==
	Custom Facebook Feed
		Version: 2.4.6
		Author: Smash Balloon

	Custom Twitter Feeds
		Version: 1.2.6
		Author: Smash Balloon

	Easy Google Fonts
		Version: 1.4.3
		Author: Titanium Themes

	Elementor
		Version: 1.7.1
		Author: Elementor.com

	Instagram Feed
		Version: 1.4.9
		Author: Smash Balloon

	Jetpack by WordPress.com
		Version: 5.2.1
		Author: Automattic

	Polylang
		Version: 2.2.1
		Author: Frédéric Demarle

	YouTube
		Version: 11.8.2
		Author: EmbedPlus Team

== Debug ==
	Errors: 
		TypeError: Cannot read property 'errors' of undefined
			at http://new.nightoftheprogfestival.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.1 - 2:111772
			2017-09-02 14:37 +00:00
			x 2 times

		TypeError: Cannot read property 'removeClass' of undefined
			at http://new.nightoftheprogfestival.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.1 - 2:105283
			2017-09-02 14:27 +00:00
			x 4 times

		TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
			at http://new.nightoftheprogfestival.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.1 - 2:50451
			2017-08-31 18:26 +00:00

		TypeError: Cannot read property 'style' of undefined
			at http://new.nightoftheprogfestival.com/wp-admin/js/editor.min.js?ver=4.8.1 - 1:693
			2017-08-31 14:20 +00:00
			x 17 times

		TypeError: Cannot read property 'reset' of undefined
			at http://new.nightoftheprogfestival.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.1 - 2:50374
			2017-08-31 09:25 +00:00

**Comment by arielk** [comment]
This is something that was fixed in the latest versions, try updating to version 1.7.2 and let me know if it works out for you

**Comment by lukasalperowitz** [comment]
I upgraded to 1.7.2 and its even worse, adding content via the whsiwyg editor is most the time not shown and saved

**Comment by arielk** [comment]
I'm afraid there is a conflict between Elementor and other plugins.

Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
