### ISSUE TITLE
Notices when using elementor with Polylang translation plugin

### ISSUE THREAD

**Issue by jonatascabral** [pojome/elementor#2328]
## Description
I noticed some bugs when using elementor with polylang plugin active:
- When the page or post don't have the polylang translation it return "Notice: Trying to get property of non-object in wp-content/plugins/elementor/elementor.php on line 65";
- When try to save the page or post, the ajax loading don't stop, in console it returns the JSON correctly, but, it have the same notice above and "Notice:  Undefined index: post in wp-content/plugins/elementor/elementor.php on line 64";

## Steps to reproduce
- Install the Polylang plugin and activate it;
- Try edit a page or post and don't create the polylang translation;
- If you inspect the page or include a die, exit on a custom widget you will see the first notice;
- When you try the save on post or page, the ajax loading don't stop, but the things are saved correctly, if you inspect the console, the notice was there and the JSON too;

#### Server Environment
	Operating System: Linux
	Software: nginx/1.6.2
	MySQL version: 5.7.17
	PHP Version: 7.0.19
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	Elementor Library: Connected

#### WordPress Environment
	Version: 4.8.1
	Site URL: http://pj76.localhost:8080/wp
	Home URL: http://pj76.localhost:8080
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Debug Mode: Active

#### Theme
	Name: Base theme
	Version: 1.0.0
	Author: Challenge Creative
	Child Theme: No

#### User
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

#### Active Plugins
	ACF: Better Search
		Version: 2.0.7
		Author: Mateusz Gbiorczyk

	Advanced Custom Fields PRO
		Version: 5.6.1
		Author: Elliot Condon

	Easy Updates Manager
		Version: 6.4.0
		Author: Easy Updates Manager Team

	Elementor
		Version: 1.7.1
		Author: Elementor.com

	Elementor Custom Elements
		Version: 0.0.1
		Author: Chall Creative

	Elementor Pro
		Version: 1.6.1
		Author: Elementor.com

	Lightweight Social Icons
		Version: 0.9
		Author: Thomas Usborne

	Polylang
		Version: 2.2.1
		Author: Frédéric Demarle

	WordPress Exporter
		Version: 0.0.4
		Author: zourbuth

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WPBruiser
		Version: 3.1.8
		Author: Mihai Chelaru

	WP Mail SMTP Plugin by Mail Bank
		Version: 3.0.13
		Author: Tech Banker

	WP Original Media Path
		Version: 2.1.1
		Author: studio RVOLA

#### Debug
	Errors: There are no errors to display

**Comment by arielk** [comment]
I tried to reproduce but I couldn't to find any problem. 

Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
