### ISSUE TITLE
Facebook widgets are awesome do the same for VK

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2329]
Hello! I'm glad to see the FB widgets! Do the same please for VK — the most popular Russian social net.
Here is the API https://vk.com/dev If not in English, scroll down and select.

Share Link (button) — https://vk.com/dev/Share
Like Widget (button) — https://vk.com/dev/Like
Post widget — https://vk.com/dev/Post
Community Widget — https://vk.com/dev/Community
Comments Widget — https://vk.com/dev/Comments

Let me to know if you need some help.

Thanks!

**Comment by MaskaZan** [comment]
+1

**Comment by ShialMeth** [comment]
+1

**Comment by ravilrrr** [comment]
+1

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
