### ISSUE TITLE
[Bug] Space in a column applied to the last element

### ISSUE THREAD

**Issue by CiriousJoker** [pojome/elementor#2331]
The space between widgets in a column is applied to the bottom of every element. Is this intended? To me, it would make more sense, if it was at the bottom of every element but the last one. If I want space below the last one, I have the margins of that element for that (or column padding)

**Comment by arielk** [comment]
I'm not sure I understood. The space between widgets is applied to the bottom of each element **except** the last element in the column.

I would be happy if you could better explain the issue.

**Comment by katart** [comment]
I've noticed the same bug. The default widget spacing within a column is 20px except for the `:last-child` widget. BUT when I manually override the default spacing (example: 16px), all widgets now have a 16px `margin-bottom` even the `:last-child` element. 

The `:last-child` element should still keep the default `margin-bottom:0` even when the column's widget spacing is specified in the settings.

I hope this makes sense.

**Comment by arielk** [comment]
Can you share with us a link to this page?

**Comment by katart** [comment]
http://fny.fnytesting.com/ 

Check out the section with the View Our Work button (near the bottom)

**Comment by arielk** [comment]
This is something that should not happen, in order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by arielk** [comment]
Fix for v1.7.4

Thanks for your feedback!
