### ISSUE TITLE
[Bug] Margin of <p> is hardcoded and can only changed via custom css

### ISSUE THREAD

**Issue by CiriousJoker** [pojome/elementor#2332]
Title says it all, I guess. The value is 20 px I believe

**Comment by sgrenzh** [comment]
Yep, noticed that too. Would be good to get this looked at, unless it's 'feature' 😛

**Comment by arielk** [comment]
This default behavior of WordPress, you can learn more about the subject here:
https://codex.wordpress.org/Function_Reference/wpautop

You can also turn it off using the following function:
`remove_filter( 'the_content', 'wpautop' );`
