### ISSUE TITLE
[Bug + Feature Request] Weird behaviour when interacting with text boxes

### ISSUE THREAD

**Issue by CiriousJoker** [pojome/elementor#2334]
Expected behaviour:
- Click on the text field
- The view I chose last time is selected
- Nothing happens until I change its content

Actual behaviour:
https://gyazo.com/3cdcb0cf6fdf21e171de7de17b367ce9

Would be cool if this thing doesn't automatically update the preview even when nothing happens and it would be cool if it remembered the mode (visual/text), that I chose last time for that element.

Also, it would be cool if the default mode for new textboxes would adapt to my most used mode automatically or if I could set it somewhere.

By the way, I open a lot of issues and it might seem like I don't like this thing, but you guys are doing an amazing job! Keep up the good work!

**Comment by sgrenzh** [comment]
This has been my main gripe with Elementor since the beginning.

Very annoying and should be addressed.

**Comment by CiriousJoker** [comment]
The problem is, that the visual mode seems to use <p> tags. This messes with the layout however, as <p> has an automatic margin as I've pointed out here: #2332

**Comment by bainternet** [comment]
Not a real issue in our view, since nothing is saved, and in text mode, you are missing the `p`,`br` tags so it's functioning ok. closing for now.

thanks.
