### ISSUE TITLE
better Countdown please :)

### ISSUE THREAD

**Issue by magicountdown** [pojome/elementor#2336]
Hello from France !

I read this on one page :

"Evergreen countdown timers are a bit trickier. They use the power of cookies and other tracking to display different timers for each visitor. So if you set an evergreen countdown timer for seven days, each one of your visitors will have seven days from the first time they visit your page."

I think its very important for sellers to have this option. For now, i use thrive themes to do that. Elementor can do that very soon ?

Thanks for the answers !

**Comment by arielk** [comment]
Our countdown is according to the time zone defined on your site.

This allows you to set an exact time for: Expiration of sale, launch time, etc.

We don't have a plan to change it soon, sorry.

Thanks for your feedback!

**Comment by afroniquely** [comment]
I agree we NEED an evergreen/scarcity countdown effect or make a ticker where it can be set to a specific time, and is not date dependent.
