### ISSUE TITLE
Link to Page or Post for Image Gallery

### ISSUE THREAD

**Issue by hansnolte** [pojome/elementor#234]
First of all ...
Absolutely great plugin.
It's really fun to work with.

But a few things I still needed.

For example, Images from the gallery with a link to pages or posts.
![link-to-page](https://cloud.githubusercontent.com/assets/7922627/16729700/61548c20-476e-11e6-8469-d012659444c4.jpg)

Floating of elements.
Example: I want to get an icon and a text in a row
(Within a column)

Looking forward to the next version

Hans

**Comment by yehudah** [comment]
Hi,

The image galley use wordpress builtin gallery and there isn't option there to use links.

You can can use Icon Box to get icon and a text in a row.

**Comment by hansnolte** [comment]
Hi yehudah,

thanks for your answer.

This is of course bad that there is no option for links.
The Gallery is best for a Portfolio or References Site.
Hopefully another solution for a Gallery with links in Elementor become added.


Thanks for the  Icon Box Tip!
