### ISSUE TITLE
[Bug] New Facebook widgets breaking mobile layout

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#2340]
I noticed on the latest Elementor blog post that some of the new Facebook widgets aren't responsive. They break the page on mobile (I was using an iPhone SE with Safari). Here are a couple screenshots:

https://www.dropbox.com/s/15zn83x8sq2zro4/File%20Sep%2005%2C%209%2046%2051%20AM.png?dl=0
https://www.dropbox.com/s/m4z2ubbwo07z63p/File%20Sep%2005%2C%209%2046%2033%20AM.png?dl=0

**Comment by arielk** [comment]
Fix v1.7.2

Thanks for your feedback
