### ISSUE TITLE
CSS Autocomplete and easy breakpoints

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#2343]
Elementor is awesome, but sometimes I need to write some custom CSS, which is a bit of a drag when there's no autocomplete to speed things up. The ultimate setup would be to have emmet like completions, to enable shorthand like bgc -> background-color, dib -> display: inline-block;, p0 -> padding: 0;  etc. etc.  I've seen this implemented in the Yellow Pencil plugin, so I know it's possible... it's a hard thing to live without once you get used to it :)

Also, having a separate input for each breakpoint for custom device specific styles would be really handy also.

**Comment by arielk** [comment]
I merged this issue with another issue #2212 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
