### ISSUE TITLE
UI-suggestion: bigger Scrollbar

### ISSUE THREAD

**Issue by hannesgrebin** [pojome/elementor#2345]
As you see the cursor would switch into a drag arrow while trying to scroll down, maybe you could implement a normal scrollbar. 
Middle click scroll wouldn't apply in the sidebar area, as default. I would like to use it as I'm constantly work with a pen. but never mind. bigger scrollbar would be a help.

https://i.imgur.com/Oq1cwTx.png

Thanks a lot for considering

**Comment by arielk** [comment]
You can just use the mouse's wheel to scroll in the panel area.

Thanks for your feedback, we will consider this in the future.

**Comment by hannesgrebin** [comment]
I have no mouse wheel. :(

Hannes
(Sent from my phone)

—

HANNES GREBIN STUDIO
Systemic Design & Product Centered Brand Development

Große Hamburger Straße 15 | 10115 Berlin
M +49 (0) 176 235 212 09
T  +49 (0) 30 226 851 08
www.hannesgrebin.com
