### ISSUE TITLE
Elementor set global styles for image

### ISSUE THREAD

**Issue by Simpleqode** [pojome/elementor#2347]
I am writing a couple of custom widgets for the Elemenetor, and faced some issues with Elementor setting all images responsive:

.elementor img {
   max-width: 100%;
   height: auto;
}

So I have to overwrite those values where I don't need that. I think that can be corrected to be more specific.

**Comment by bainternet** [comment]
We do this for most of our needs in elementor, so if your widgets need something else simply overwrite it in them.
