### ISSUE TITLE
Order in which multiple items are selected in SELECT2 control

### ISSUE THREAD

**Issue by imfaisalkh** [pojome/elementor#2348]
I'm using SELECT2 control in my custom widget for elementor with `multiple` values enabled. However the order in which multiple values are selected is important, in my specific case. Now, by default, this order is not respected. My question is, is there any way I can make sure that the array returned follow the same order in which the values are selected by the user in the SECLECT2 control?

**Comment by bainternet** [comment]
@imfaisalkh 

You have two options:

1) extend the `ControlSelect2ItemView` once it's available, which is defined [here](https://github.com/pojome/elementor/blob/master/assets/dev/js/editor/views/controls/select2.js) with one of the solutions defined [here](https://github.com/select2/select2/issues/3106).

2) which will guarantee to give you the correct order is to use a non-multiple select inside a repeater control.

Hope this help.

**Comment by kowsar89** [comment]
Is it possible to add this custom ordering feature in future? I need this in like every project.

**Comment by wpsoul** [comment]
The same. Currently, there is option to control select2 order. This is critical when you select Posts by ID and you want to keep selected order
