### ISSUE TITLE
WPML compliance

### ISSUE THREAD

**Issue by ianstudio** [pojome/elementor#2349]
Hi,
I just realized that third party plugins like:

https://shop.namogo.com/product/elementor-extras/
https://www.livemeshthemes.com/elementor-addons/

are not WPML-compliant. Making their elements that are text-based useless for WPML-requiring sites. 

Is there any way to.. either..

Help them or even "force them" ?! (I guess that's bit authoritarian) to be WPML-compliant to be referenced as truly Elementor-supported?

I guess I'm stuck with Elementor's elements for now, which thankfully are already not too bad..

**Comment by arielk** [comment]
You need to ask the authors of these plugins, unfortunately there is nothing on our side that we can help on the issue.
