### ISSUE TITLE
trying to remove posts section

### ISSUE THREAD

**Issue by seengafus** [pojome/elementor#235]
I want to remove the section saying : Breaking news , New posts ...
but the only option that I found was  removing all the header including the menu ...
I want to keep the menu , and remove this empty ( breaking news sections ) 
![unwanted section](https://cloud.githubusercontent.com/assets/20388105/16730389/5674461c-477b-11e6-92b5-eb18d901dfc0.jpg)

**Comment by yehudah** [comment]
This is a widget area,

Go to Apperence --> widgets --> Sub Header Left, and remove the widget.

**Comment by seengafus** [comment]
it worked ... thanx 
![224](https://cloud.githubusercontent.com/assets/20388105/16732833/ae79972a-4787-11e6-8dda-811083161a0a.jpg)
