### ISSUE TITLE
[BUG] The Text Editor Widget is causing Elementor to 'Hang' and Stop Working

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2351]
EDIT - assuming by the no response here, I'm the only one so I've created a technical support ticket!

Hey,

Since updating to the latest versions of the Elementor and Elementor Pro plugins, I'm having issues with the text editor.

If I open an existing page and click into the text editor, the elementor left panel just hangs. You can't select anything else, like the styling or Advanced tabs within the text editor widget, or any other part of the Elementor editor. I have to reload the page to get anything to work again

I've tested other widgets and they work fine, it's just the text editor.

https://www.youtube.com/watch?v=5-5e6agzJbA&feature=youtu.be

To confirm, I've tried deactivating/reactivating the plugin, I've cleared cache and cleaned up other parts of the website like DB entries and past revisions, but the problem remains.

Anyone else have this issue?

P.S. I also tried on a brand new page and it's an issue here too.

**Comment by enviedbymost** [comment]
Turns out there were issues with my php.ini file that was causing 500 errors with TinyMCE.

Fixed!

**Comment by clondon** [comment]
@enviedbymost
Would you  like to help other by saying what the issue was?

**Comment by garrocko** [comment]
I am having this same issue. How did you fix the issue?
