### ISSUE TITLE
Changing basic font color for all paragraphs in the site

### ISSUE THREAD

**Issue by benosx** [pojome/elementor#2353]
I use the starter theme BlankSlate. This theme is best by means of performance in my liking but it doesn't give you an option to change the basic font color of the site.

Doing either;
`
p {color: #000 !important}`
XOR
`.elementor-widget-text-editor {color: #000 !important}`

Doesn't help, because it changes it for everything and Elementor won't be able to rewrite these because they come after Elementor in the CSS hierarchy.

How could I make sure Elementor is the last in the CSS hierarchy, even after my child theme?

There should be given an option to do so, from within Elementor, I think.

Given I use starter themes, the current situation doesn't allow me to work with Elementor smoothly.

**Comment by benosx** [comment]
I think one should have the option to change it from the Elementor Style options.

**Comment by enkota** [comment]
If you go into Elementor -> Settings ->Disable Global Colors/Fonts you can revert back to your themes styling. Might be what you are after?

**Comment by benosx** [comment]
Sadly it isn't. What I'm after is just loading Elementor CSS after any CSS whatsoever, so it will have "the last word " on everything (including the child theme).

An ideal state would be Elementor adding `!important` CSS declarations in cases of conflict.

**Comment by arielk** [comment]
As we discussed, we will change this to Default Colors and Fonts instead of "Global" to be more clear.

Thanks for your feedback!
