### ISSUE TITLE
Global Settings > Add Typography Style

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#2354]
I know there's currently a global fonts area, but I'd love to see that section include all global typography options, like font size, line height etc. And for those options to be responsive.

Having a typography test view in the main area while setting these values would be the icing on the cake :)  so you can dial everything in nice and easy.

**Comment by ramonztro** [comment]
This is one thing I would love to stop coding in my style.css. +1

**Comment by arielk** [comment]
Ref for developers: #534

**Comment by bainternet** [comment]
I merged this issue with  #3345 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by dotpdesign** [comment]
+1
