### ISSUE TITLE
Feature Request Ability to preview different post formats in the Post Widget

### ISSUE THREAD

**Issue by ugene1992** [pojome/elementor#2358]

**Comment by arielk** [comment]
Do you have an example of this feature?

**Comment by bellamystudio** [comment]
It would be great if the posts (pro) widget looked at the post format before determining certain things - eg if it's a link post, the URL should try to use get_url_in_content() to grab the first link and fall back to the permalink if there isn't anything.  If it's a video post, could potentially grab a thumb from youtube/vimeo?

**Comment by SidianMSJones** [comment]
I second this. Lack of post formats is a downer indeed. Examples of how Divi handles it: https://www.elegantthemes.com/documentation/divi/post-formats-divi/

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
