### ISSUE TITLE
disabling the wheeled chair option ...

### ISSUE THREAD

**Issue by seengafus** [pojome/elementor#236]
I want to disable the blue wheel chair option ..
 how can I do that please
![xxx](https://cloud.githubusercontent.com/assets/20388105/16730439/ad26c80e-477b-11e6-8273-d4871b908f45.jpg)

**Comment by cobicarmel** [comment]
Hi seengafus,

The wheeled chair is part of the [pojo accessibility plugin](https://wordpress.org/plugins/pojo-accessibility/). You can disable it from the plugins page in the admin panel.

**Comment by seengafus** [comment]
it worked , thanks 
![223](https://cloud.githubusercontent.com/assets/20388105/16732452/f564735a-4785-11e6-9258-48fed4f74346.jpg)
