### ISSUE TITLE
text wrap around image

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#2362]

**Comment by JosiahCarberry** [comment]
Although it is possible to wrap text around an image by embedding the medium within a text object, all of the features that Elementor adds to the image are then lost, notably, the caption, formatting, etc. Furthermore, it is extremely tedious to try to simulate wrapping by creating multiple sections and multiple columns in those sections, not to mention the unpredictable results depending on the client used.
Therefore, it would be very, very nice if Elementor were able to combine the features of the image object with having text wrap around that object.

**Comment by arielk** [comment]
Can you share with us a link to this page or steps to reproduce this situation?

**Comment by JosiahCarberry** [comment]
I am asking to do something which is not currently possible, so far as I can see, so I cannot provide a link to demonstrate it. But just look at any elementor page where an image is embedded within a text block - no chance to add a caption. Otherwise, take a look at https://www.3cs.ch/manifesto-agile-service-management-2/ , in particular, in the area around Fig. 1. I would have wanted the text to simply wrap around that image and its caption. Instead, I have to go through all sorts of gymnastics, using a new section with two columns, and a negative top margin for the text block on the left, none of which works very well on anything but a wide screen laptop or desktop.

**Comment by arielk** [comment]
Sorry, but for now this is not possible, maybe in the future we'll add this feature.

Thanks for your feedback!

**Comment by JosiahCarberry** [comment]
Yes, I am aware it is not possible now. I just wanted to get my 2 cents into the hopper of possible future enhancements.
Can people vote for different enhancements?

**Comment by dbjpanda** [comment]
@arielk Has this feature already been added to the latest version of Elementor? I am still not able to wrap text around an absolute positioned widget placed inside the content of post widget. Is it even possible ?
