### ISSUE TITLE
Elementor different image sizes

### ISSUE THREAD

**Issue by igaloly** [pojome/elementor#2365]
in elementor builder, when you apply the widget of PORTFOLIO, in the settings there is an option to choose your image size - thumbnail, medium, medium large, large. it's all different version of the same image.

 for the purpose of speeding up my website i want that in the desktop version the image size will be MEDIUM and in the mobile version the image size will be THUMBNAIL. how can i do that?

**Comment by arielk** [comment]
Sorry, for now it's not possible, maybe we'll add it in the future.

Thanks for your feedback!
