### ISSUE TITLE
Toolset Type, Layout compatibilies

### ISSUE THREAD

**Issue by c6410** [pojome/elementor#2367]
**## Description**

Elementor does not work toghether with toolset plugins, 
please check some info/thread here:

https://wp-types.com/forums/topic/toolset-and-elementor-bugs/
1.https://wp-types.com/forums/topic/conditional-code-is-outputting-raw-code/page/2/
2. https://wp-types.com/forums/topic/elementor-text-editor-bug/
3. https://wp-types.com/forums/topic/theres-a-bug-when-using-layouts-plugin-with-the-elementor-builder/

**## Steps to reproduce**

Install toolset plugins and try to edit the layout it create raw code.

**## Environment**

Operating System: | Linux |  
Software: | Apache |  
MySQL version: | 5.6.37 |  
PHP Version: | 7.1.9 |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 512M |  
GD Installed: | Yes |  
Elementor Library: | Connected

---- 

I understand the toolset theme is in touch with Ben and some others, appreciate all follow up on this.
I have bought the pro licence .

Thank You.

**Comment by c6410** [comment]
Hi, Ben and team, nothing on this so far?
Do you need more images and information?

**Comment by c6410** [comment]
no comment on this guys ?

**Comment by bainternet** [comment]
answered in #2506

thanks
