### ISSUE TITLE
Background video (Youtube recommended videos)

### ISSUE THREAD

**Issue by TomWe** [pojome/elementor#2372]
## Description

I have noticed that sometimes the youtube clip, which I use as a background (not the widget), ends or halts after quite some time, and some of Youtube's recommended clips shows up at the bottom. 

I have not yet been able to find an exact way of reproducing the problem.

![youtube_clips_bottom](https://user-images.githubusercontent.com/31881216/30314318-a9a386e2-97a0-11e7-819a-9369908065ab.jpg)

Please see attached screengrab (and the small images at the bottom)

## Environment

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | 5.5.5 |  
PHP Version: | 7.0.23 |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 96M |  
GD Installed: | Yes |  
Elementor Library: | Connected |  

WordPress Environment |   |  
-- | -- | --
Version: | 4.8.1 |  
Site URL: | http://www.westermann.se |  
WP Multisite: | No |  
Max Upload Size: | 96 MB |  
Memory limit: | 64M |  
Permalink Structure: | /%postname%/ |  
Language: | en-GB |  
Timezone: | Europe/Copenhagen |  
Debug Mode: | Inactive

**Comment by arielk** [comment]
What is the full link you've entered for a video background?

**Comment by TomWe** [comment]
Hi

The link: <https://www.youtube.com/embed/MypUe4x9ous>



Den 14. september 2017 kl. 08.29.21 +02.00, skrev Ariel Klikstein <notifications@github.com>:

**Comment by arielk** [comment]
Please try this instead: https://www.youtube.com/watch?v=MypUe4x9ous

**Comment by TomWe** [comment]
Hi,

I have just noticed on my ipad that the issue is still there with the recommended ".../watch?v=..." function.

Any other advice? Or a preferable a vimeo or mp4 function! Because it is a very annoying bug.


Regards
Tom

Den 15. september 2017 kl. 15.51.40 +02.00, skrev Ariel Klikstein <notifications@github.com>:

**Comment by arielk** [comment]
Fixed in 1.8.5

Thanks for reporting!
