### ISSUE TITLE
It's not possible drag&drop Widgets with IE 11 + Edge

### ISSUE THREAD

**Issue by xelaz** [pojome/elementor#2373]
## Description
It's not possible use Elementor v1.7.3 with IE 11 and Edge 1x. The problem is, that we can't drop widgets to sections or columns.

In IE 11 you can't select columns grid as graphics, because you can only select the grid.

## Environment
We have test it with IE11 and Edge 14+15 on Windows 10

![screenshot](https://user-images.githubusercontent.com/3328062/30322128-bab56a96-97b8-11e7-9d85-60122d243aee.png)

**Comment by kobizz** [comment]
Hi @xelaz,
Currently Elementor doesn't support editing with IE / Edge.

**Comment by denisgomesfranco** [comment]
Hey @kobizz ,
How come Elementor can't be supported on IE and Edge? All functions work on these browsers EXCEPT adding new elements. I can also create and duplicate sections, and duplicate already placed elements.

I've known Elementor for quite a while now, I just can't wrap my head on why such a simple operation cannot be completed on these browsers - even more so knowing that every other operation in Elementor is working as expected.
