### ISSUE TITLE
WC and EDD cart widget or Elementor menu widget option

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2379]
Hello! In light of recent events it's would be usefull to show the WooCommerce and Easy Digital Downloads cart in menu bar. It can be a menu widget option but separately widget will be better because we can place it anywhere independently of menu.

Thanks!

**Comment by bainternet** [comment]
Both EDD and WooCommerce do have this as native fanctionalty,

For Woo you can use "custom html" and add 

``` HTML 
<div class="hide_cart_widget_if_empty">
    <div class="widget_shopping_cart_content"></div>
</div>
```

and For EDD you can use the `[download_cart]` shortcode.

You would need to wrap this in some kind of dropdown but it should be a start, for now, until we get to it.

Thanks for the suggestion.
