### ISSUE TITLE
Elementor Export

### ISSUE THREAD

**Issue by GraphanixDziner** [pojome/elementor#238]
Hi

I am using elementor on a site. When Moving the site from one server to another all the pages break and none of the elementor layouts come through. Is there an option to download current page layouts or export elementor pages? If not this will aid alot in exporting elementor layouts and importing them into new or cloned site.

**Comment by yehudah** [comment]
Did you export all db ? Changed all links ?

**Comment by GraphanixDziner** [comment]
HI

Yea I did a full database export, uploaded to new server phpmyadmin and edited url links within the database.

I thought maybe to go into the page and just do a page update to see maybe if this updates but nothing happens either. Its like a blank slate.

**Comment by hansnolte** [comment]
Hi GraphanixDziner,

you can try Duplicator.
https://wordpress.org/plugins/duplicator/

**Comment by paaljoachim** [comment]
If you want a run through of how Duplicator works then check out: 
http://easywebdesigntutorials.com/duplicator-tutorial-videos/

**Comment by salvimateus** [comment]
This option would be wonderful to create pages on localhost and export one page via "ctrl c ctrl v" to the production site.

Creates blank page in the production site > opens the Elementor editor > "Button" Import Data > Paste code > Renders structure and content exported of that page

Ps. the images were off, but that's the least of it. Just add them again. What matters is a complex structure created on localhost be easily exported.

**Comment by arielk** [comment]
Hi everyone

We're working on this feature for the next release. You can follow on this feature here: #132 

Feel free to reopen the issue when you have some new with this issue
