### ISSUE TITLE
The 'Nav Menu' widget centering bug in tablet mode

### ISSUE THREAD

**Issue by ShialMeth** [pojome/elementor#2380]
Setting 'align center' with 'Nav Menu' widget works in desktop mode, but doesn't work in tablet mode, menu elements still get aligned to the left.

**Comment by AsyrafMukhtar** [comment]
Mine works well with these settings. 

Layout=Vertical
Align=Center
Pointer=None
Submenu Indicator=Classic
__________________________________
Mobile Dropdown
breakpoint = 767>px
Align=center
toggle button= None

But the only problem i have now is that in Mobile view. The Nev Menu won't stay in its section. Is anyone experiencing the same problem?

Below is attached screen caps of Desktop view(how is should look like) and Mobile view(the problem)

![desktop view](https://user-images.githubusercontent.com/31975658/30462859-061bafd8-99fb-11e7-9d13-95548ce43b70.PNG)

![mobile view](https://user-images.githubusercontent.com/31975658/30462858-0619ee32-99fb-11e7-8736-2195cfdbd6cb.PNG)

**Comment by arielk** [comment]
Please go to the settings of the menu widget > Content > Mobile Dropdown > Align > Aside / Center

Thanks
