### ISSUE TITLE
[Bug Report] Mobile Menu Appears between changing pages

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#2381]
With the new Navmenu Element when clicking between pages the mobile menu 'renders' before the desktop menu in the desktop view. So you get a brief flash of the mobile bar and hamburger before the desktop menu appears. I have experienced this on a site I am rebranding http://dev.dreamscoffeelounge.co.uk the same happens on a localhost install. Other users are seeing the same effect on their browsers and Lyle Chamney has also experienced the same problem on a 'clean install' on a local host with only: GP, Elementor and E Pro installed.

**Comment by SniffleValve** [comment]
Adding to what Nick has said, I am experiencing the same behavior on two separate hosted installs with only the mentioned items installed. I have tried various themes as well, (GP, OceanWP, Astra, 2016 and 2017) all with the same "hamburger flash" on reload or going to a new page via the menu. 

I would really like to get going and create some tutorials on this new feature but I am unable to do so ... well, unless I do like Dave Foy did and stayed in the editor/preview for the whole video! LOL :) 

Cheers!
Lyle

**Comment by arielk** [comment]
Fix for v1.8.1

Thanks for your feedback!
