### ISSUE TITLE
[Feature Request] Several widgets - Get link to file via searching in media libary

### ISSUE THREAD

**Issue by kai2018** [pojome/elementor#2382]
Hello,
if using image box (same for button widget, image widget and many more) it is very uncomfortable to find the http/https link to a media file that should be opened if you click on the image. You always must switch to media libary and copy the https link and then paste it in the image box.
A great solution would be that the image box widget can browse the media libary and after the media file is selected it is pasted. Most users of my blog have not so much experience in Wordpress and this would be a great update.

**Comment by arielk** [comment]
I merged this issue with another issue #255 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
