### ISSUE TITLE
[Feature Request] Defaults for elements

### ISSUE THREAD

**Issue by jacobopolavieja** [pojome/elementor#2383]
Hello,

Several members have debated on the different Facebook groups about the possibility of setting default styles for elements.

Defaults would be applied to each element that we specify, except when overriden. This would allow to avoid LOTS of unnecessary repetition, as well as easier transitions if we need to modify something sitewide.

Any chance this gets implemented? Would be a massive addition now that Elementor is being used for mostly all parts of a site, not just individual pages.

Thanks!

**Comment by arielk** [comment]
I merged this issue with another issue #965 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
