### ISSUE TITLE
[Feature Request] Schema.org support

### ISSUE THREAD

**Issue by ramonztro** [pojome/elementor#2385]
It would be great to be able to set [schema.org](http://schema.org/) on elements. 

## Why it would be nice:
- SEO boosting
- Rich snippets

## How could it work:
- On each widget editor, on "Advanced" tab, could be a "Schema.org" section;
- On the "Schema.org" section, could be a general dropdown selector (e.g. "What kind of Thing is this?");
- On the "Schema.org" section, could be a dropdown selector for each part of the widget (e.g. "What the description field is for the Thing?")
- Widgets, could have a default when obvious (e.g. Testimonials)

Thank you!

**Comment by Basilakis** [comment]
Here is a sample function that can be enhanced and used, based on widget ( and also devs can after use into their own widgets + themes ;) )
https://gist.github.com/Basilakis/7df5e62cb59aa83910dc0324176cf35f

**Comment by ramiy** [comment]
Nice idea, can be developed as an addon.

**Comment by unclerom** [comment]
This would be a great addition

**Comment by usmanlatif** [comment]
This would be a great addition. Elementor has become my favorite page builder. Like it is fast and responsive by default, it should also be schema.org friendly by default, or at least for the most of the elements. Please add this.

**Comment by kovou** [comment]
+1

**Comment by themedleb** [comment]
+1

**Comment by quantumleap33** [comment]
+1

**Comment by mikesale** [comment]
+1

**Comment by mylimoproject** [comment]
+1

**Comment by quantumleap33** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by theamazingaustin** [comment]
++

**Comment by Noz5** [comment]
+1
whats the status on this request ?

**Comment by GreenballParis** [comment]
+1 ! ONE YEAR and still not developed while it's one of the best SEO optimizations out there ?!

**Comment by bentalgad** [comment]
Still Waiting..

**Comment by silvioghedin** [comment]
+1 waiting...

**Comment by valentincauro** [comment]
+1 😒

**Comment by black-eye** [comment]
I'm baffled - is it implemented or not?
It doesn't seem so, at least for a footer...

**Comment by GreenballParis** [comment]
Yes but doesn’t working correctly for SEO 👎🏻

Envoyé depuis un iPhone

**Comment by Cileone617** [comment]
+1

**Comment by masoudahmadpour** [comment]
+1
