### ISSUE TITLE
Image height issue

### ISSUE THREAD

**Issue by vencoder** [pojome/elementor#2386]
Hi, 
I am trying to add an image to a section in Elementor.
There is only one section with an image. 
Using the TwentySeventeen Wordpress template.

Though the image appears on full screen, on mobile, it only occupies the top 1/4th of the screen. I have used "Min Height" feature to set the height of the image and the column in which it is saved. 

As you can see, the image is reduced in the mobile view but the column height covers the whole screen which is evident from the black background I had set for the column. 

Any suggestions/workarounds to this situation would be invaluable. 

If not, is there a way to create an basic Elementor template with a Hero image or is a custom made Wordpress theme the only way out? 

Am preparing a demo prototype so buying a premium theme is, kind-of, out of question for now. 

Thank you. 

![3](https://user-images.githubusercontent.com/24566642/30430389-bc9fa72e-9978-11e7-857e-f8e782406ec6.jpg)

**Comment by arielk** [comment]
You can set the image as background of the column, and set the background size: Cover, and let me know if it works for you
