### ISSUE TITLE
[Feature Request] Use Elementor to Change the Design of the Default Wordpress Category Page

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2387]
Hey Elementor community,

I've been searching Google for what feels like hours and I can't find a reasonable solution for any wordpress theme!

I currently use the GeneratePress Pro theme and Elementor Pro to design my site.

I want to completely redesign a new custom page using GP & Elementor, so I can add additional widgets to the page such as CTAs and other content related to the category, and not just a list of previously published posts.

I know there are some settings within customize>blog from GeneratePress Pro, but the controls here are more about what to display (like full post vs. exerpt), rather than the actual design itself.

Does anyone here know how I can do this in Elementor?!?!

The 'edit with elementor' button is disable for the category pages, so I assume this isn't currently possible.

I'd really appreciate your input.

Cheers, Jamie.

**Comment by arielk** [comment]
I merged this issue with another issue #543 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
