### ISSUE TITLE
Any way to give a name to the Basic elements category in the widgets section?

### ISSUE THREAD

**Issue by Simpleqode** [pojome/elementor#2389]
I've created a dozen of custom widgets from within my custom plugin, put them in a new category and placed that on the top of everything else in the widgets section. However, due to the first Basic elements category's heading is hidden (the one that is under the search bar), my widgets get mixed with those from the Basic elements category. If the Basic elements category had a visible name, that would solve the problem. Is there any way to name it / show it's name from within a custom plugin? Thanks in advance!

**Comment by KingYes** [comment]
You can create your own category like this:

```
add_action( 'elementor/init', function() {
	// Add element category in panel
	\Elementor\Plugin::$instance->elements_manager->add_category(
		'custom-category-name',
		[
			'title' => __( 'Custom Category', 'elementor-pro' ),
			'icon' => 'font',
		],
		1
	);
} );
```

**Comment by Simpleqode** [comment]
Yes, that's how I created a new category that I've put on top of everything else. But due to the Basic widgets category got no name and is UNDER my custom category now, their widgets get Mixed. I also tried to create an empty category inbetween them, but it doesn't display because it has no widgets in it.

**Comment by notrealdev** [comment]
Same issue here, did you solve your problem @Simpleqode ?

**Comment by Simpleqode** [comment]
@notrealdev, no I didn't unfortunately.

**Comment by notrealdev** [comment]
I added new css file via hook `'elementor/editor/before_enqueue_scripts'`

My custom category
```php
add_action( 'elementor/init', 'Elementor\theme_widget_category' );
function theme_widget_category() {
    Plugin::instance()->elements_manager->add_category(
        'this-is-my-category',
        array( 'title' => esc_html__( 'Theme Widgets', 'text' ) ),
        0 // 0 to TOP
    );
}
```

Then elementor create a class with name: `panel-elements-category-title-` + `this-is-my-category`
In my custom css file:
```css
.panel-elements-category-title-this-is-my-category+div{ margin-bottom: 30px }
```
Now, i have spacing is 30px with Basic category of elementor
