### ISSUE TITLE
Pattern suggestion

### ISSUE THREAD

**Issue by luizbills** [pojome/elementor#239]
Instead of:
```
// somewhere in the class Preview (just a example)
add_filter( 'body_class', [ $this, 'body_class' ] );
```

use a Singleton:
```
add_filter( 'body_class', [ self::get_instance(), 'body_class' ] );
```

# Why?
To make possible hack/extends the plugin more easily (e.g. removing some actions or filters).

**Comment by KingYes** [comment]
You don't need that. You can just this:

`remote_filter( 'body_class', [ \Elementor\Plugin::instance()->frontend, 'body_class' ] );`
