### ISSUE TITLE
[Enhancement/BUG] Nav widget is not W3C-compliant - duplicated ID's for items

### ISSUE THREAD

**Issue by ramonztro** [pojome/elementor#2390]
Nav widget markup uses the same HTML id twice in different menu items (I guess it duplicates the original items to create the mobile dropdown). It would be nice if they had different ids so the site could pass clean through [validator.w3.org](validator.w3.org), which means, be W3C-compliant.

![screen shot 2017-09-14 at 18 42 44](https://user-images.githubusercontent.com/3981052/30457610-5ac6c734-997e-11e7-87cd-06fc86cc631a.png)

Thanks!

**Comment by KingYes** [comment]
Hey @ramonztro 

We fixed this, and will release in next version of EPro. Thanks!
