### ISSUE TITLE
[Enhancement/BUG] Form widget is not W3C-compliant - bad value for "required" attribute

### ISSUE THREAD

**Issue by ramonztro** [pojome/elementor#2391]
Form widget markup uses "1" for "required" attributes on input fields instead of "required". The [W3C spec](https://www.w3.org/TR/html5/forms.html#the-required-attribute) uses only "required" without value, but, as far as I know, it could be "required=required" as well.
 
![screen shot 2017-09-14 at 18 43 01](https://user-images.githubusercontent.com/3981052/30457923-bda5abf8-997f-11e7-9e87-8941eadc20a0.png)

Elementor's non-W3C-compliant markup: 
`<input id="username" name="un" required="1">`

W3C-compliant markup:
`<input id="username1" name="un1" required>`
`<input id="username2" name="un2" required="required">`

Thank you!

**Comment by arielk** [comment]
Fix for v1.8.1

Thanks for your feedback!
