### ISSUE TITLE
JS Error in Version 1.73 with Pro 1.8.0

### ISSUE THREAD

**Issue by cfreak** [pojome/elementor#2393]
## Description
There is an JS Error in the Console:
```javascript
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.getCurrentDeviceMode (frontend.min.js:2)
    at u (frontend.min.js:2)
    at HTMLDocument.init (frontend.min.js:2)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.K (jquery.js:2)
```

## Steps to reproduce
         
Visit the Sie onverso.de, open the console and change the window size.

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25
	MySQL version: 5.6.19
	PHP Version: 7.0.6
	PHP Max Input Vars: 1000
	PHP Max Post Size: 204M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.1
	Site URL: //www.onverso.de
	Home URL: //www.onverso.de
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: onverso
	Version: 1.1
	Author: mke-media
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 3.3.4
		Author: Automattic

	BackupGuard Pro
		Version: 1.1.53
		Author: BackupGuard

	Black Studio TinyMCE Widget
		Version: 2.4.2
		Author: Black Studio

	Custom Sidebars
		Version: 3.0.9
		Author: WPMU DEV

	Elementor
		Version: 1.7.3
		Author: Elementor.com

	Elementor Pro
		Version: 1.8.0
		Author: Elementor.com

	Google XML Sitemaps
		Version: 4.0.9
		Author: Arne Brachhold

	Mailgun
		Version: 1.5.8.5
		Author: Mailgun

	Planet Forms
		Version: 1.0.0
		Author: Danny Stey

	Redirection
		Version: 2.7.3
		Author: John Godley

	Regenerate Thumbnails
		Version: 2.2.6
		Author: Alex Mills (Viper007Bond)

	Remove HTTP
		Version: 2.1.1
		Author: Fact Maven

	Shariff Wrapper
		Version: 4.3.0
		Author: Jan-Peter Lambeck & 3UU

	Social Media Feather
		Version: 1.8.4
		Author: socialmediafeather

	Wordfence Security
		Version: 6.3.18
		Author: Wordfence

	Wp-Image-Optimizer
		Version: 1.0.1
		Author: mke-media - Digitalagentur

	WP-PostRatings
		Version: 1.84.1
		Author: Lester 'GaMerZ' Chan

	WP Broken Link Status Checker
		Version: 1.0.4
		Author: Pau Iglesias, SeedPlugins

	WP Fastest Cache
		Version: 0.8.7.2
		Author: Emre Vona

	WP Fastest Cache Premium
		Version: 1.4.2
		Author: Emre Vona

	WP Insurance Calculator
		Version: 1.0
		Author: 

	wpSEO
		Version: 4.3.0
		Author: Team wpSEO

	WP Sitemap Page
		Version: 1.6
		Author: Tony Archambeau

== Debug ==
	Errors: There are no errors to display

**Comment by arielk** [comment]
I don't see any error on your homepage. 

Please try deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

And let me know if the error still exist.

**Comment by cfreak** [comment]
its on the subpages 
for example: https://www.onverso.de/berufsunfaehigkeitsversicherung/

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by rawzone** [comment]
Same error here on multiple pages. (Non public environment).

**Comment by bainternet** [comment]
@cfreak, @rawzone 
Please reopen if issue still persists in latest version 1.8.5

**Comment by luglio7** [comment]
same error in local environment.

**Comment by soyket** [comment]
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
http://localhost/wordpress/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.8.12 line 2

**Comment by kefiras** [comment]
Same stuff here.

Please check on my website:
https://pracowniazdrowegostylu.pl/
