### ISSUE TITLE
Inline CSS and Section background

### ISSUE THREAD

**Issue by x10sys** [pojome/elementor#2394]
I'm trying to use inline CSS for multiple reasons.

I made a template in Ocean WP Library, placed it with a shortcode on a page. 

When using external CSS option in Elementor - it all works ok. When i switch to internal CSS option in Elementor and resave that template the problem occurs: a section doesn't display the background image.
The image url is not shown in source at all.

Hope you will correct this bug.

**Comment by x10sys** [comment]
These are the differences:

## Taken from external file
`.elementor-element.elementor-element-qioxlbl{
background-image:url("https://server/wp-content/uploads/beaches/opatija/lido.jpg");
background-position:center center;
background-repeat:no-repeat;
background-size:cover;
transition:background 0.3s, border 0.3s, border-radius 0.3s, box-shadow 0.3s;}`

## Taken from inline css
`<article data-id="qioxlbl" class="elementor-element elementor-element-qioxlbl elementor-section-full_width elementor-section-height-min-height elementor-section-height-default elementor-section-items-middle elementor-section elementor-top-section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}" data-element_type="section" style="">`

As you can see, style is set to nothing in inline css :\

**Comment by arielk** [comment]
Fix for v1.7.4: https://github.com/pojome/elementor/pull/2410

Thanks for your feedback!
