### ISSUE TITLE
Elementor is stripping HTML widget of <script> code

### ISSUE THREAD

**Issue by chanceimages** [pojome/elementor#2395]
I'm trying to embed a 3rd party custom code into an Elementor HTML widget or the native "Custom HTML" widget, and the <script> is being removed, only on the frontend view without being logged in (logged in on the frontend, it's working fine). 

Steps to recreate:
Open Elementor editor, drag in an HTML widget or 'Custom HTML' widget, paste in:

    <script src="http://www.avvo.com/assets/badges-v2.js" type="text/javascript"></script>
    <div class="avvo_badge" data-version="1" data-target="http://www.avvo.com/professional_badges/322409" data-specialty="9" data-type="rating">
    <div class="avvo_content"><a href="http://www.avvo.com/attorneys/93003-ca-christina-stokholm-322409.html?utm_campaign=avvo_rating&amp;utm_content=322409&amp;utm_medium=avvo_badge&amp;utm_source=avvo" target="_blank" rel="me">Lawyer Christina Stokholm</a> | <a href="http://www.avvo.com/business-lawyer/ca/ventura.html?utm_campaign=avvo_rating&amp;utm_content=322409&amp;utm_medium=avvo_badge&amp;utm_source=avvo" target="_blank">Top Attorney Business</a></div>
</div>

Click "View Page"

It shows when logged in. 

Open a Private Window in the browser, view the page there.

When not logged in, it shows incorrectly - doesn't render.

**Comment by arielk** [comment]
Please try to use in HTML widget by Elementor, like this screenshot: http://i.imgur.com/EvU05Eq.png

And let me know if it works for you!

**Comment by chanceimages** [comment]
That's what I was trying - it was stripping the <script></script> tags out. Seems it's not working with more complicated code in general. 

I relied on this feature for an embed code from a popular lawyer rating site - I could not find a way to display it properly.

**Comment by arielk** [comment]
It's very weird, I tried it myself and it works great. Perhaps there is another plugin that is causing this conflict.

**Comment by niknah** [comment]
I have this problem too.  Add a html widget, add <script> somewhere.
View the page, the <script> tag is there.

Now log out of .../wp-admin/...
and view the page again.  The <script> tag is gone.

**Comment by niknah** [comment]
Thanks.  As the image says, there're two html widgets.  "HTML" and "Custom HTML".  "HTML" doesn't have this problem.  

"Custom HTML" has the problem as described, <script> tag appears when logged in, disappears when logged out.
