### ISSUE TITLE
Feature Request: Squeeze Page Improvement

### ISSUE THREAD

**Issue by carbonemt** [pojome/elementor#2397]
I am not really sure what effect i'll have on the development of this plugin, but I thought Id at least get a seed planted.

Elementor is an awesome plugin for building websites, but it serious falls short in creating landing and squeeze pages in ONE area. **Mailing Integration**. It does not do well with capturing leads, besides the 3 mailing list options currently available in the forms builder.

There is money in web design, but there is significant profit in marketing. That's why there is a huge industry right now for landing/squeeze page options like leadpages and ConvertKit.

I believe my request could easily be implemented and significantly increase your sales by doing this ONE this thing. Adding more mailing integration options. For example:

Hubspot CRM
MailerLite
Emma
AWeber
Active Campagin
GetResponse
iContact
etc etc

I know there is a zapier option, but to spend time implementing that for every landing and squeeze page I build, is frustrating and time consuming.

Additionally, designing a few **high converting squeeze pages** for your template database adds significant value to your plugin. When I look for a landing page app to use, I look at the templates. Not because I can't create them myself, but because I am looking for the least amount of work I have to input into projects.

I get it. Elementor is a website builder. But with a few additions it can cross the line into a revenue generating powerhouse for marketers. I have read hundreds of articles on _Elementor Vs the Competition_ and every article concludes the samething. **Elementor needs to a stronger lead capturing option** to be a contender.

**Comment by atMaarten** [comment]
Agree. Implementing more marketing intergrations would add a huge value to the editor! 

Adding a solid GravityForms intergration (#2404) would be a fast way to do this. Since they already have a ton of intergrations.

**Comment by parfilov** [comment]
MailerLite and GetResponse. I need them too. Now i do integrations via Zapier webhook but there are only 5 zaps on free account.

**Comment by silvioghedin** [comment]
Please don't forget infusionsoft .

I think would be a game changer and modal options

**Comment by jayalove** [comment]
Amen!! I agree wholeheartedly. Thrive is amazing at this and it’s what I really miss from their pkatrmform. 

Active campaign
ConvertKit
ConvertFox
Infusionsoft
Aweber

And yes, some landing pages would be awesome. Let me know if you want me to design some.

**Comment by bainternet** [comment]
Little clean up:

Done:
----------
- [x] ActiveCampign
- [x] ConvertKit
- [x] GetResponse
- [x] Drip
- [x] Hubspot support
- [x] ConvertFox - [Guide](https://github.com/pojome/elementor/issues/2996#issuecomment-353318331)
- [x] OntraPort - [Guide](https://github.com/pojome/elementor/issues/3001#issuecomment-353844190)
- [x] Sendy - [Guide](https://github.com/pojome/elementor/issues/3157#issuecomment-357465095)
- [x] Zapier - [Guide](https://docs.elementor.com/article/263-zapier)

Open Requests:
-----------------
- [ ] Infusionsoft
- [ ] Aweber
- [ ] MailerLite

**Comment by themedleb** [comment]
Mailster please.

**Comment by maxwellhibbert** [comment]
Mailster!

**Comment by jayalove** [comment]
@Bainternet. Wow thanks that was amazingly fast!!!

**Comment by bainternet** [comment]
Mailster should be fairly easy to implement using the provided hooks ex:

```PHP

add_action( 'elementor_pro/forms/new_record', function( $record ) {
	if ( ! function_exists( 'mailster' ) ){
		// Mailster missing!!!
		return;
	}
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );

	// Ref: https://kb.mailster.co/mailster-for-developers/
	$fields = [
		'email' => $submmited_fields['ID_OF_YOUR_EMAIL_FIELD']['value'],
		'firstname' => $submmited_fields['ID_OF_FIRSTNAME_FIELD']['value'],
		'lastname' => $submmited_fields['ID_OF_LASTNAME_FIELD']['value'],
		'status' => 1, //1 = subscribed (default) , 0 = pending, 2 = unsubscribed, 3 = hardbounced
		'custom-field' => 'Custom Value',
	];
	// Add subscriber
	$subscriber_id = mailster( 'subscribers' )->add( $fields );
	if ( ! is_wp_error( $subscriber_id ) ) {
		$lists = [1,23]; // Array of list ids
		$success = mailster( 'subscribers' )->assign_lists( $subscriber_id, $lists);
	}
});
```

**Comment by bainternet** [comment]
MailRelay should also be easy to implement, ex:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record ) {
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );

	// Ref: https://mailrelay.com/en/api-documentation/function/addSubscriber
	$fields = [
		'email' => $submmited_fields['ID_OF_YOUR_EMAIL_FIELD']['value'],
		'name' => $submmited_fields['ID_OF_NAME_FIELD']['value'],
		'groups' => [ 1, 3, 5 ],
		'function' => 'addSubscriber',
		'apiKey' => 'YOUR_API_KEY',
	];
	// Add subscriber
	wp_remote_post( 'https://your_address/ccm/admin/api/version/2/&type=json', [
		'body' => $fields,
	]);
});

**Comment by bainternet** [comment]
MailerLite ex:

```PHP

add_action( 'elementor_pro/forms/new_record', function( $record ) {
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );

	// Ref: https://developers.mailerlite.com/v2/reference#create-a-subscriber
	$fields = [
		'email' => $submmited_fields['ID_OF_YOUR_EMAIL_FIELD']['value'],
		'name' => $submmited_fields['ID_OF_NAME_FIELD']['value'],
		'fields' => [
			'FIELD_KEY' => $submmited_fields['ID_OF_A_FIELD']['value'],
		],
	];
	// Add subscriber
	// Use //https://api.mailerlite.com/api/v2/groups/{Group_ID}/subscribers to add directly to a group
	$url = 'https://api.mailerlite.com/api/v2/subscribers'; 
	wp_remote_post( $url, [
		'headers' => [
			'content-type' => 'application/json',
			'x-mailerlite-apikey' => 'API_KEY',
		],
		'body' => $fields,
	]);
});

//or if you have MailerLite PHP SDK :
add_action( 'elementor_pro/forms/new_record', function( $record ) {
	if ( ! class_exists( '\MailerLiteApi\MailerLite' ) ) {
		// Mailerlite SDK Missing
		return;
	}
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );

	// Ref: https://developers.mailerlite.com/v2/reference#create-a-subscriber
	$fields = [
		'email' => $submmited_fields['ID_OF_YOUR_EMAIL_FIELD']['value'],
		'name' => $submmited_fields['ID_OF_NAME_FIELD']['value'],
		'fields' => [
			'FIELD_KEY' => $submmited_fields['ID_OF_A_FIELD']['value'],
		],
	];
	// Add subscriber
	$subscribers_api = ( new \MailerLiteApi\MailerLite( 'API_KEY' ) )->subscribers();
	$added_subscriber = $subscribers_api->create( $fields ); // returns added subscriber

	/*
	 * You can add directly to a group
	    $groups_api = (new \MailerLiteApi\MailerLite('API_KEY'))->groups();
	    $group_id = 123;
	    $added_subscriber = $groups_api->addSubscriber($groupId, $fields ); // returns added subscriber
	 *
	 */
});

**Comment by bainternet** [comment]
AWeber:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record ) {
	if ( ! class_exists( 'AWeberAPI' ) ) {
		// Aweber SDK Missing
		return;
	}
	$consumer_key    = '***'; # put your credentials here
	$consumer_secret = '***'; # put your credentials here
	$access_key      = '***'; # put your credentials here
	$access_secret   = '***'; # put your credentials here
	$account_id     = '***'; # put the Account ID here
	$list_id        = '***'; # put the List ID here


	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );

	// Ref: https://labs.aweber.com/snippets/subscribers#subs
	// Ref: https://labs.aweber.com/docs/reference/1.0#subscriber_collection
	# create a subscriber
	$params = [
		'email' => $submmited_fields['ID_OF_YOUR_EMAIL_FIELD']['value'],
		'ip_address' => \ElementorPro\Classes\Utils::get_client_ip(),
		'name' => $submmited_fields['ID_OF_NAME_FIELD']['value'],
		'ad_tracking' => 'elementor_pro_form', //Customer Ad Tracking Field
		'misc_notes' => 'From Elementor Pro ' . $form_name . ' form',
		'custom_fields' => [
			'FIELD_KEY' => $submmited_fields['ID_OF_A_FIELD']['value'],
			'FIELD_KEY2' => 'HARD-CODED-VALUE',
		],
		'tags' => [
			'HARD-CODED_TAG',
			$submmited_fields['ID_OF_A_TAG_FIELD']['value'],
		],
	];

	$aweber = new AWeberAPI( $consumer_key, $consumer_secret );

	try {
		$account = $aweber->getAccount( $access_key, $access_secret );
		$list_url = '/accounts/' . $account_id . '/lists/' . $list_id;
		$list = $account->loadFromUrl( $list_url );


		$subscribers = $list->subscribers;
		$new_subscriber = $subscribers->create( $params );
	} catch( AWeberAPIException $exc ) { }
});
```

**Comment by bainternet** [comment]
Closing as all requests were either implemented in Pro or have an example/guide and any other should work just the same.

**Comment by stevecopeza** [comment]
Hi @bainternet, 

Apologies if I'm not using this correctly.
The request https://github.com/pojome/elementor/issues/3125 requesting Agile CRM integration was merged with this, and I'm battling to understand what the solution is. Im assuming that it's do-abe (hence being closed), but I cant figure out how.

Are you able to guide me please ?

Cheers,
Steve

**Comment by collizo4sky** [comment]
If anyone is looking to integrate Elementor form with any email service provider or CRM not natively supported, you can use [MailOptin](https://mailoptin.io) to bridge the gap. For example, a lot of folks uses it to integrate with Klaviyo, MailerLite etc.

And it's free https://wordpress.org/plugins/mailoptin/

More info at https://elementor.com/email-marketing-integration/

**Comment by amoyastudio** [comment]
witch files do change and to add the code ?
I need to implement mailster integration

**Comment by NEILBATCHELOR** [comment]
For Mailster is this added to the functions.php in child theme please:

If its added on the form - where please? Thanks 

add_action( 'elementor_pro/forms/new_record', function( $record ) {
	if ( ! function_exists( 'mailster' ) ){
		// Mailster missing!!!
		return;
	}
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );

	// Ref: https://kb.mailster.co/mailster-for-developers/
	$fields = [
		'email' => $submmited_fields['ID_OF_YOUR_EMAIL_FIELD']['value'],
		'firstname' => $submmited_fields['ID_OF_FIRSTNAME_FIELD']['value'],
		'lastname' => $submmited_fields['ID_OF_LASTNAME_FIELD']['value'],
		'status' => 1, //1 = subscribed (default) , 0 = pending, 2 = unsubscribed, 3 = hardbounced
		'custom-field' => 'Custom Value',
	];
	// Add subscriber
	$subscriber_id = mailster( 'subscribers' )->add( $fields );
	if ( ! is_wp_error( $subscriber_id ) ) {
		$lists = [1,23]; // Array of list ids
		$success = mailster( 'subscribers' )->assign_lists( $subscriber_id, $lists);
	}
});

**Comment by vmachado007** [comment]
@bainternet could you add integration with MailWizz?

**Comment by spac-em** [comment]
HI @bainternet  ,You mention "done" means will be in elementor pro soon ?

**Comment by AkhilAniyan** [comment]
> Mailster should be fairly easy to implement using the provided hooks ex:
> 
> ```
> 
> add_action( 'elementor_pro/forms/new_record', function( $record ) {
> 	if ( ! function_exists( 'mailster' ) ){
> 		// Mailster missing!!!
> 		return;
> 	}
> 	// Make sure this is the correct form
> 	$form_name = $record->get_form_settings( 'form_name' );
> 	if ( 'MY_FORM_NAME' !== $form_name ) {
> 		return;
> 	}
> 	$submmited_fields = $record->get( 'fields' );
> 
> 	// Ref: https://kb.mailster.co/mailster-for-developers/
> 	$fields = [
> 		'email' => $submmited_fields['ID_OF_YOUR_EMAIL_FIELD']['value'],
> 		'firstname' => $submmited_fields['ID_OF_FIRSTNAME_FIELD']['value'],
> 		'lastname' => $submmited_fields['ID_OF_LASTNAME_FIELD']['value'],
> 		'status' => 1, //1 = subscribed (default) , 0 = pending, 2 = unsubscribed, 3 = hardbounced
> 		'custom-field' => 'Custom Value',
> 	];
> 	// Add subscriber
> 	$subscriber_id = mailster( 'subscribers' )->add( $fields );
> 	if ( ! is_wp_error( $subscriber_id ) ) {
> 		$lists = [1,23]; // Array of list ids
> 		$success = mailster( 'subscribers' )->assign_lists( $subscriber_id, $lists);
> 	}
> });
> ```

Can someone assist me how to integrate this?

I already added the code to functions.php, and updated the "MY_FORM_NAME" and list IDs.

What is the next step?

Thanks.

**Comment by collizo4sky** [comment]
@AkhilAniyan just use MailOptin as a bridge. And it's free https://wordpress.org/plugins/mailoptin/

**Comment by NEILBATCHELOR** [comment]
Thanks I will test it - I don’t want to use plugins.

**Comment by NEILBATCHELOR** [comment]
@AkhilAniyan I have added the code to my child functions.php do I need any action after submit please? I don't have any settings for that.

**Comment by feperrella** [comment]
Better Mailster Integration

https://github.com/elementor/elementor/issues/10871#issuecomment-670994144

**Comment by maurocarreraok** [comment]
There is anything for Salesforce/Pardot? Thanks!
