### ISSUE TITLE
Elementor "Comments" Element

### ISSUE THREAD

**Issue by grafx77** [pojome/elementor#2398]
I would LOVE to see a "Comments" Elementor element in the near future. Whenever I use the Elementor Canvas, which I use 99% of the time, we lose WP comments. Why not include it as an element??

**Comment by arielk** [comment]
I merged this issue with another issue #543 in the same subject so we could deal with it more efficiently.

You can also use Facebook Comments by E-Pro.

Thanks for your feedback!
