### ISSUE TITLE
Clickable Column request

### ISSUE THREAD

**Issue by domgro** [pojome/elementor#2399]
I would like to see this feature in the future.
Columns should have the same feature for setting links for images,text,buttons etc.  (if a background image is selected)

I want to use an image with text on it. normally I use margin to get the text in the right place. but the section is relatively packed and the elements get displaced on smaller screens or mobile devices.

using the button and spread it over the column is a possibility,but you cant use anything else on it.

**Comment by atMaarten** [comment]
I agree! It would be so much easier if you could click anywhere inside a column or section to go to the settings.

The current section and column settings button is very small and you need to hover over it to see it. Also you need to be very precise in clicking on it. 

Clickable columns and sections would boost the workflow a lot!

**Comment by arielk** [comment]
Unfortunately this is not possible, please read the following discussion: https://github.com/pojome/elementor/issues/351

**Comment by domgro** [comment]
what about layers?
this way you can solve the button,text and image issue without the elements interfering each other
