### ISSUE TITLE
Image Box size is quirky on Chrome

### ISSUE THREAD

**Issue by Nat-Faeeria** [pojome/elementor#240]
On Chrome, the Image of an image box doesn't always keep the same size. On Firefox/Iceweasel it is ok.
Here's a screenshot on Chrome, and on Iceweasel : 
![capture du 2016-07-12 11 37 12](https://cloud.githubusercontent.com/assets/9194688/16753454/11138da8-4825-11e6-9924-57e25ccbcc81.png)
![capture du 2016-07-12 11 38 25](https://cloud.githubusercontent.com/assets/9194688/16753483/3cd737fa-4825-11e6-83e2-bccb5612c384.png)

**Comment by Nat-Faeeria** [comment]
Adding a condition of "max-width: 60%;" to the class .elementor-image-box-content fix the issue.

**Comment by yehudah** [comment]
What is your layout ?  Images inside a double section (right and left) ?

**Comment by Nat-Faeeria** [comment]
I have two section (the two rows for the images), each containing two columns. Each column contains an image box.

The issue is present only on Chrome, and only when the image of the Image Box element is put left or right from the text (if you choose to have the image on top of the text, there's no problem).

The issue can be fixed by adding a condition "max-width: 60%" to the .elementor-image-box-content class. Only problem is, this condition mess up the layout for Image box where the image is on top of the text.

**Comment by yehudah** [comment]
Please try the same page with wordpress default theme.

**Comment by Nat-Faeeria** [comment]
Same problem.
On Chrome, you have to precise the maximum width of the image box's content when it is left or right from the image, since you precise the size of the image box's image, else the content will take as much width as it can, and since the height of the image is auto, it'll will reduce its size.

**Comment by yehudah** [comment]
@arielk

**Comment by arielk** [comment]
Fixed https://github.com/pojome/elementor/milestone/17
