### ISSUE TITLE
[Feature request] Import user templates within the editor

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2402]
**Currently:** When you want to import an template you received from a other user, you now need to go to: WP Dashboard > Elementor > Library > Import Templates.

**Suggestion:** Import user templates within the editor.
It would save a lot of time and new tabs / screens if you could import templates directly from the user template overview. A button could be added that toggles the file upload. Or a drag and drop section would be also very nice. 

![templateoverview](https://user-images.githubusercontent.com/5883842/30520710-c9caf542-9bb3-11e7-843c-c420d1ce27ee.png)

**Comment by ataniker** [comment]
+1
Hello, thats exactly the same Feature we need in our Web Team. We creating a big real estate and banking website with Elementor Pro and we predefine all Template Layouts for the Content Team. So viewing the Templates via Screenshot and adding them in an easier Way would provide a good support.
