### ISSUE TITLE
[Feature request] Option to enable/ disable Wordpress widget elements

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2403]
**Currently**: Every widget type is displayed in the elements overview. There are 20+ elements in the list and lots of them are duplicates from the elementor elements. (For example text, image, video, recent posts). I never use these elements. 

I like that the editor is so clean and professional. However I think that these Wordpress widgets are noise between the well crafted elements from the editor itself.

**Suggestion**: I think working with the Wordpress core elements is more a advanced user feature. The elements should not been displayed on default I think. It would be a lot better if you could activate or deactive these Wordpress widgets in the Elementor settings.

The best place for this option in my opinion would be: WP Dashboard > Elementor > Settings.

**Comment by arielk** [comment]
I merged this issue with another issue #1314 in the same subject so we could deal with it more efficiently.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello @atMaarten!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.18.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
