### ISSUE TITLE
[Enhancement] Searching for elements

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2405]
**Currently:** When clicking on the elements tab, you can search for elements. However you first have to click on the search tab, which slows down the workflow of building the page.

**Suggestion:** It would be nice if you can start typing directly. Or that there would be a hotkey to jump to the search elements box right away.

**Comment by arielk** [comment]
I merged this issue with another issue #2333 in the same subject so we could deal with it more efficiently.

Thanks for your feedback!
