### ISSUE TITLE
[Enhancement / Feature Request] Global widget edit content only

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2406]
**Currently:** Elementor has so many features that it's taking **a lot of time** to style an element. Especially if you need to design the same things over and over again.

With global widget you can quickly design elements that you use often. For example a Primary CTA, secundairy CTA, etc. Now you can use these elements on all pages, which is great.

However if you want to change the text on a button, you have to unlink the element from the global version. Which means that if you want to edit the style later you still have to restyle all unlinked buttons.

**Suggestion:** It would **be awesome** if you could only edit the content of a Global widget (without unlinking it). In this way you can keep the style but edit the text on the button, link it's pointing to edit. This be a HUGE time saver, your style would be consistent in all places and it would make things so much easier :)

![global style](https://user-images.githubusercontent.com/5883842/30521239-fb4d32b6-9bbc-11e7-9d78-bb23640f7de7.png)

**Comment by atMaarten** [comment]
See also [the post in the Elementors Community](https://www.facebook.com/groups/Elementors/permalink/1264869156972201/).

**Comment by enviedbymost** [comment]
Good idea.

+1

**Comment by arielk** [comment]
I merged this issue with another issue #965 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by iangoh414** [comment]
Is this being developed? I wanted to post this feature request and found this. I am looking for a global widget that can edit the content only.

**Comment by Mramorov** [comment]
+1
