### ISSUE TITLE
Best Practises to Optimise Padding/Margins across Multiple Browsers?

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2408]
This is an area I've always struggled with with Elementor.

Despite trying to keep my widgets as consistent as possible, they still display differently across browsers. And I'm talking more specifically around widget spacing.

Here's an example screenshot of how the same widget as different spacing between firefox and chrome

https://s26.postimg.org/yhaka28bd/Chrome_Padding.png
https://s26.postimg.org/9cjjwn8ux/Firefox_Padding.png

This is just desktop. Mobile is MUCH worse! Ironically, the elementor mobile view looks different to BOTH the above.

Is there any way round this?

Making a small change to make it look good on one browser, breaks another. It's a vicious cycle of tweaking and breaking to get all recent browsers and devices to look 'good'.

To confirm, before writing this post, I cleared all database and browser cache, revision history etc to see if it was an issue with caching

**Comment by arielk** [comment]
Can you share with us a link to this page or steps to reproduce this situation?

Please also read this issue: https://github.com/pojome/elementor/issues/2370

**Comment by enviedbymost** [comment]
Hey,

It's on the homepage of www.jamiecoleiro.com.

The screenshots from my previous post are under the 'YouTube Tutorials' section.

If you view the same page on both desktop and mobile versions of Firefox/Chrome, you'll see they look different!

**Comment by arielk** [comment]
Please change all Margin controls from percent to pixels.

Firefox does not deal well with percentages margin.
