### ISSUE TITLE
[Enhancement] Better feedback where an element will be placed

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2409]
**Currently**: It's not very clear where an element will be placed when draggin it. The lines are very small and when you have a background color on a section it's almost impossible to see. Also there is an animation (the bar expands slowly) to show there the element will be placed. This slows the process, because you have to wait for the bar to expand to see it more clearly.

Also it's pretty hard to place an element under colomns if there are no element under it yet.

**Suggestion**:  Make it easier to see where elements will be placed. This can be done in a few ways:
- When draggin an element, fase all elements a bit and highlight the sections and columns where the element could be placed.
- Use bigger borders, so it's easier to see the different area (even when the section has a background color). The bigger the better.
- Delete the expanding animation
- Make the "here it will be placed" bar bigger
- Show within "here it will be placed" bar text with if it's placed in a section or column.

Here is an GIF to show what I mean. Also compared it with two other builders.

![highlights](https://user-images.githubusercontent.com/5883842/30521761-072d99c4-9bc5-11e7-9844-2020b8a95b5a.gif)

**Comment by bainternet** [comment]
@atMaarten 

Thanks for the suggestion, We keep updating the Editor's UI all the time and we will look back at this in the future.

thanks again.
