### ISSUE TITLE
Multiingual pages ?

### ISSUE THREAD

**Issue by Nat-Faeeria** [pojome/elementor#241]
How should I do to translate a page ? I can't seem to integrate with Polylang or such. What would you recommend in order to create a multilingual website with Elementor ?

**Comment by yehudah** [comment]
Hi,

Please read this:
http://docs.elementor.com/article/42-translate

**Comment by Nat-Faeeria** [comment]
It doesn't really answer my question. I don't want to translate the Elementor plugin, but to translate the pages I make with it, the content of my pages.

**Comment by Nat-Faeeria** [comment]
Hmm I managed with Polylang in the end.

Elementor is really great, but it really need an "export" feature, for multilingual websites it will be really useful.

**Comment by yehudah** [comment]
Great, 
Can you tell more detailes what was the issue ?

Export is in our roadmap, so subscribe for updates.

**Comment by Nat-Faeeria** [comment]
The issue wasn't really with Elementor in the end, but I thought so.

I had made a static front page with Elementor (in english), and I needed to translate it in korean. I tried to use Polylang, but it is a bit tricky to allow a static front web page with this plugin, and the display was quirky because of it (and Elementor was working ... weirdly). 

In the end, I tried with a fresh install, reproducing my page step by step, but with Polylang and Elementor from the start. It is working, it seems. 
The problem is, it is mandatory to redo the whole page layout for each page for each new language. That's why having export will be great ! =)

When do you think this feature will be released ?
