### ISSUE TITLE
[Enhancement] Click within section / column to go to the settings

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2411]
**Currently**: To go the section or column settings, you have to hover over the section and than go to the top. The button is very small and tiny. And if there are elements in the section, the hover often changes to the element. You have to be very precise with where you click. And it is a bit hard finding to option for the first time. Clicking within the section would be more intuitive. 

**Suggestion**: When you are with your mouse in the section it's highlighted (with a blue border). Click anywhere within a section / column to go to the settings of it. Just as with the elements only now for sections and columns.

Clickable columns and sections would boost the workflow a lot!

**Comment by atMaarten** [comment]
Also see [the post in the Elementor Community](https://www.facebook.com/groups/Elementors/permalink/1262274093898374/) about this.

**Comment by jacobopolavieja** [comment]
Yes please... When I play with negative margins and z-index, I find myself often having to modify an element's DOM with Chrome dev tools so I can click the section button.
Having its properties show up when clicking the border or area of a section/column would be much appreciated.

That or a skeleton view as X Theme/Pro have, if that serves for reference. It's one of the few pieces I miss.

**Comment by atMaarten** [comment]
Indeed. X theme  has a great way to quickly edit the settings. Clicking on the sections makes the process so much faster and easier to understand for users. Hope to see this in the coming update!

**Comment by bainternet** [comment]
The most common action after adding or entering a section/column is to add widgets to it that is why when you do click inside a column/section you get the widgets list.

Sadly currently there is no way to define the desired behaviour you describe per installation, but maybe we will look in to it in the future.

Thanks for the feedback.
