### ISSUE TITLE
[Enhancement] Sticky Header Navigation

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2412]
LOVE the new navigation menus from release 1.7. Great job.

What would make them even more epic (and to be able to remove my desktop burger icon nav) is the ability to stick the header navigation to follow users down the page as they scroll. :)

**Comment by parfilov** [comment]
Usually you place the menu to the block (section) and this is no longer menu this is section/div/nav. You can do sticky menu with plugin myStickymenu. Use my [videoguide](https://www.youtube.com/watch?v=HQO4qrHzhP0). it's in Russian but visual and intuitive understandable.

**Comment by srcek** [comment]
Sticky headers are now about the only feature I use from the theme rather then Elementor itself. It would be a really nice addition to the Elementor Pro 2 now that we can create headers and footers for the entire site.

**Comment by arielk** [comment]
Closing in favor of #3826

Thanks everyone.
