### ISSUE TITLE
Padding & Margin Setting not separately modified?

### ISSUE THREAD

**Issue by shangdev** [pojome/elementor#2413]
need to buy advanced version?

**Comment by marriott79** [comment]
I agree. It would be very helpful if we could modify them separately without the other values defaulting to 0 and overriding the defaults.

**Comment by bainternet** [comment]
You can define them separately by disabling the "Link values together". 
![screen shot 2017-11-07 at 12 51 02](https://user-images.githubusercontent.com/660572/32490005-603bfc50-c3ba-11e7-8fbf-eb307cd02271.png)
