### ISSUE TITLE
Ability to pin favourite elements to the top

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#2415]
Thrive architect has a handy feature where you can pin elements to the top. Seeing how they completely ripped your UI, I'm sure you could borrow a few of their ideas :)

**Comment by bainternet** [comment]
@maxwellhibbert 

We are always looking to improve the editor and we do have plans to add this in some manner in the next few relases.
Maybe not "pin to top" but recently/frequently used widgets or "favorite widgets". 

thanks for the feedback.

**Comment by ravilrrr** [comment]
+1
I'm tired of using search, but I use a maximum of 10 widgets
)))

**Comment by bainternet** [comment]
I merged this issue with  #3805, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
