### ISSUE TITLE
Use codemirror for CSS input areas

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#2416]
Code autocomplete and other advanced features (like multiple cursors etc) found in CodeMirror are really handy to have. Would make editing much faster inside elementor.

**Comment by arielk** [comment]
We are using the [Ace Editor](https://ace.c9.io/) for this, for now it's good for us, maybe in the future we'll use CodeMirror for it 

Thanks for your feedback!

**Comment by maxwellhibbert** [comment]
Okay, no worries. Ace Editor supports all of those things anyway. Would it be possible to switch on these features for Elementor?

**Comment by arielk** [comment]
We added autocomplete for the next version :)
https://github.com/pojome/elementor/pull/2487/commits/a009a93024a1fda872a92299812c81c28d8592c5

Thanks

**Comment by maxwellhibbert** [comment]
Awesome, thanks!

**Comment by arielk** [comment]
We just released a beta release (v1.8) which includes this feature, read more here: https://github.com/pojome/elementor/issues/2666/

Thanks for your feedback!
