### ISSUE TITLE
Always expanded side panel tabs

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#2417]
It would be cool if the 3 tabs of the side panel could be expanded to all be open at the same time. I'm one of the many people with a large display for design/development and having to constantly click around to open those panels each time I select a new element feels tedious after a while.

**Comment by bainternet** [comment]
Kind of missing the point of tabs...

Currently, this feature is not supported, but we may look into it in the future.

Thanks for the feedback.
