### ISSUE TITLE
WYSYWG font display: Style > Typography > Family - FEATURE REQUEST

### ISSUE THREAD

**Issue by RocketGS** [pojome/elementor#2425]
Font names typically have no coalition to what they actually look like. In many design applications your font selection provides the font name in the actual font itself. If this would be possible in Elementor that would be a huge time saver.

So often we get stuck using the same font over and over simply because we don't have the time to go out and research what other fonts might look like. Wouldn't it be nice to be able to see in advance what Hebo or Ovo looked like in advance of applying them?

Another less valuable but helpful option would be to add a (s) for serif styles and (ss) for sanserif styles. While not as useful as the above, at least it would narrow the selection process down some.

**Comment by ramonztro** [comment]
I think this would add some overload to the editor, as it would have to do 800+ requests and to render that many the fonts. Some sites get slowed down by 4 or 5 different font familys, so I guess that it wouldn't be preety with 800+ font familys.

Anyway, one option would be to do it by lazy loading, in the way that fonts only get rendered as the drop down is scrolled. But even this way, I feel like I would prefer a lightweight experience than having the option too preview font familys.

Break font familys into categories would be nice, though.

You can preview fonts in a more complete way on https://fonts.google.com/.

**Comment by bainternet** [comment]
@RocketGS  

what @ramonztro is saying is correct, preloading over 854 just for preview will make it unusable.

as for "lazy loading" its is already lazyloaded upon selection.

so it would be nice to have but will sadly kill the editor experience.

thanks for the suggestion.

**Comment by RocketGS** [comment]
So Google can load all their fonts onto a webpage instantly but it would be too much for Elementor? Okay you’re the engineers not me but that just seems a bit odd.

Maybe rather than a WYSIWYG maybe there’s a pop up window option or something that displays the font as the Google page you reference. And you could click on a selection to choose.

I use Indesign, Illustrator, etc with lots of fonts to choose from. It’s very helpful to be able to see the font. Especially if you have a large number to choose from. 

What about having a Favorites option? A place where you can quickly access those you use most often.

**Comment by folivio** [comment]
I agree with RocketGS. Loading font previews does not require downloading the font file. Google provides previews through their display engine.

Elegant Themes' Divi has this feature. The way they handle the load drag is by loading the preview when the font is hovered over. It's instantaneous. If that's the only thing blocking Elementor from taking the next step to becoming a professional development tool, then I think it's solved.
