### ISSUE TITLE
FEATURE REQUEST - "Hide" button in section/widget controls.

### ISSUE THREAD

**Issue by theNathanBaker** [pojome/elementor#2426]
Basically just a simple option to hide the section while in the visual editor. (Include the button in the [Duplicate | Edit | Add | Remove] control panel.

**Comment by bainternet** [comment]
@theNathanBaker 

You can do that, already, Head over to the advanced tab >> responsive and set hide on desktop/tablet/mobile (whichever you are on) and toggle the panel close.

that should give you the effect you are asking for.


If this is not what you are after please feel free to reopen and provide a detailed description.

**Comment by idmadj** [comment]
@bainternet The responsive controls do not work in the visual editor, only in the live site.

I think what @theNathanBaker is suggesting is a visibility toggle similar to the "eye" toggle in Photoshop, or, more closely, the "hide" functionality in Sketchup.

This can be very useful if, for instance, two widgets are overlaid (meaning they have the same size and position). Currently there's essentially no way to select and edit the bottom-most one. In Chrome it is possible to inspect the topmost widget, then hide the DOM element using the dev panel. The bottom widget is then accessible, but the process is obviously less than ideal. 

With the suggested functionality, once a widget is hidden, it could be either added to a list of hidden widgets from where they could be unhidden individually, or there could be a "reset visibility" button to unhide all widgets.
