### ISSUE TITLE
issue with new menu widget

### ISSUE THREAD

**Issue by dabouncer071** [pojome/elementor#2427]
The issue i  seem to be having here is the original menu label is "Pinball Machines at Fort Lauderdale Florida" but i have a navigation label called "Fort Lauderdale Florida".

Elementor is not showing navigation label just the original menu label which is now too long for the dropdown box.

You can see what i mean here: https://ibb.co/kdwNuQ

any thoughts to fix?

Kind Regards,
Paul.

**Comment by arielk** [comment]
It looks like you have some kind of cache plugin that makes it.
So make sure you deactivate it, or even better – purge the cache before.

**Comment by dabouncer071** [comment]
Hi there,

No I have cleared all cache, on both the browser and cloudflare(even setting it to dev mode so it dont cache at all).

I have also deactivated all plugins bar the theme so i can place it, I even temp took it out of maintenance mode so i could try in a different browser i hadn't used yet for that site... Still has the same issue.

**Comment by dabouncer071** [comment]
== Server Environment ==
    Operating System: Linux
    Software: Apache
    MySQL version: 5.5.57
    PHP Version: 7.0.23
    PHP Max Input Vars: 5000
    PHP Max Post Size: 64M
    GD Installed: Yes
    Elementor Library: Connected

== WordPress Environment ==
    Version: 4.8.1
    Site URL: http://pinballamerica.com
    Home URL: http://pinballamerica.com
    WP Multisite: No
    Max Upload Size: 64 MB
    Memory limit: 40M
    Permalink Structure: /%postname%/
    Language: en-GB
    Timezone: Europe/London
    Debug Mode: Inactive

== Theme ==
    Name: Pinball America
    Version: 1.0
    Author: SP Computers
    Child Theme: Yes
    Parent Theme Name: GeneratePress
    Parent Theme Version: 1.4
    Parent Theme Author: Tom Usborne

== User ==
    Role: administrator
    WP Profile lang: en_GB
    User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

== Active Plugins ==
    Elementor
        Version: 1.7.4
        Author: Elementor.com

    Elementor Pro
        Version: 1.8.1
        Author: Elementor.com

    GP Premium
        Version: 1.4.3
        Author: Tom Usborne

    InfiniteWP - Client
        Version: 1.6.5.1
        Author: Revmakx


== Debug ==
    Errors:
        TypeError: Cannot read property 'removeClass' of undefined
            at http://pinballamerica.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.6.4 - 2:111050
            2017-08-13 09:51 +00:00
            x 4 times

        TypeError: Cannot read property 'cid' of undefined
            at http://pinballamerica.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.5.4 - 2:2458
            2017-06-29 00:58 +00:00
            x 2 times

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
