### ISSUE TITLE
How to add custom class on render

### ISSUE THREAD

**Issue by phpbits** [pojome/elementor#2429]
Hi,

Checked the API and I can't figure out how to add custom class to elements when rendered on frontend. Thanks!

**Comment by KingYes** [comment]
https://github.com/pojome/elementor/blob/master/docs/content/controls/controls-and-the-editor.md#adding-a-class-to-the-element-template-wrapper

**Comment by phpbits** [comment]
@KingYes I'm looking for a filter to add class to existing elements. Thanks!
