### ISSUE TITLE
Developer documentation for new features

### ISSUE THREAD

**Issue by anandau** [pojome/elementor#2432]
In a recent release V 1.7.2, it was mentioned in changelog 
"Added API option for developers to insert controls between preexisting controls"

Is there any developer documentation available for this?

**Comment by anandau** [comment]
Hi @arielk 
Can you help me with my query?

**Comment by arielk** [comment]
Please go to the code and see the notes: 
https://github.com/pojome/elementor/blob/master/includes/base/controls-stack.php#L1160
