### ISSUE TITLE
Feature Request Folders for Templates

### ISSUE THREAD

**Issue by ryantoth2410** [pojome/elementor#2438]
Love the plugin.

I have hundreds of templates I was wondering if it would be possible to come up a system for organizing them into folders.

Nothing that different than windows/ mac folder or , [wp media folder](https://www.joomunited.com/wordpress-products/wp-media-folder). 

Thanks

**Comment by arielk** [comment]
I do not think we'll do something like that, but we're working on something similar, you can read this issue: https://github.com/pojome/elementor/issues/1711

Thanks for your feedback!
