### ISSUE TITLE
Feature: Header and Footer with Elementor

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2439]
Hello! Now we can do header and footer with plugin "Header Footer Elementor" but it works ugly. We also can implement them with do_shortcode but it will be difficult for non-technies.

It would be nice to see this functions in Elementor and we will not themes needed. Only basic empty theme because WordPress need =)

**Comment by bainternet** [comment]
I merged this issue with  #417 , which are in the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
