### ISSUE TITLE
Image Border Radius not working on image

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#244]
Seems that the border radius is only working on borders - but not on images.

**Comment by yehudah** [comment]
Can you screenshot or give more details about what you defined ?

**Comment by Luxamman** [comment]
When you put a "Image Widget" into an area, you can only style the element but not the image with a boarder and a boarder radius. so the images are sometimes smaller than the boarder and the corners are not "rounded" (boarder radius). 
workaround is to set the picture as a section background and round the corners with the "boarder radius", but that way brings also problems with it.

![prob](https://cloud.githubusercontent.com/assets/20417555/16769676/f94f443a-4849-11e6-87df-231abe52c417.png)

**Comment by yehudah** [comment]
You are correct,

The border options will be added in future versions.

**Comment by arielk** [comment]
Done https://github.com/pojome/elementor/commit/76560288580044f6128c692efc00c5856074adaa

**Comment by yt5ytt** [comment]
Yeah... I had same issue right now... Don't add image on it, but add background-image on empty widget and then go to border option and use border-radius on that widget.

**Comment by sussexslanter** [comment]
Same issue I think, in this case the image is larger than the border, and therefore the border effects are out of step with the image that is supposed to be highlighted on hover. Brown border, left image. Can't imagine this is difficult to resolve, what do I need to do?

![Border Issue 2](https://user-images.githubusercontent.com/9845933/149520622-5ac6713a-ebd7-4849-ab43-2e81060dd370.jpg)

**Comment by emre-edu-tech** [comment]
The easiest way to solve this problem (This is a problem because for Elementor every widget is in one or more div tags so you can set a class from the Advanced tab like img-container then you can put the CSS below in your child theme Style.css file.
`
.img-container img {
     border-radius: 10px;
}
`
