### ISSUE TITLE
Get section_id on elementor/widget/render_content

### ISSUE THREAD

**Issue by phpbits** [pojome/elementor#2441]
Hi,

Does the API support the return of section_id on `elementor/widget/render_content` action? $widget->get_section_id is not working. Thanks!

**Comment by KingYes** [comment]
Can you explain yourself?

**Comment by phpbits** [comment]
@KingYes I'll be adding switcher option for each widgets under the "Advanced" section. Then when switcher is one, a CSS class will be added on the widget.

<img width="773" alt="screen shot 2017-09-25 at 10 28 24 am" src="https://user-images.githubusercontent.com/3365507/30789814-b2fb1a0e-a1da-11e7-950b-0f76cd1ead5d.png">

**Comment by soyket** [comment]
Something I have been looking for an answer to !

**Comment by bainternet** [comment]
No need for the Section ID for that,

simply use the prefix_class argument of the control eg:
```php
$this->add_control(
	'add_css_class',
	[
		'label' => __( 'Show Title', 'your-plugin' ),
		'type' => Controls_Manager::SWITCHER,
		'default' => '',
		'label_on' => __( 'Show', 'your-plugin' ),
		'label_off' => __( 'Hide', 'your-plugin' ),
		'return_value' => 'CSS_CLASS_TO_ADD',
		'prefix_class' => 'elementor-'
	]
);
```

So when it's on you should see a CSS class named `elementor-CSS_CLASS_TO_ADD`
