### ISSUE TITLE
Elementor\Controls_Manager::CHECKBOX [deprecated?]

### ISSUE THREAD

**Issue by phpbits** [pojome/elementor#2442]
Hi,

I'm getting this error when using `Elementor\Controls_Manager::CHECKBOX`:

**PHP Notice:  Elementor\Control_Checkbox is <strong>deprecated</strong> since version 1.5.4 with no alternative available. in /app/public/wp-includes/functions.php on line 3962**

Thanks!

**Comment by KingYes** [comment]
Yes, it's not official release, and get deprecated for now.

**Comment by phpbits** [comment]
@KingYes I use switcher for now. Thanks!
