### ISSUE TITLE
Predefined Template Library Is Not Working After 4.8.2 WP-Update

### ISSUE THREAD

**Issue by ladetryne** [pojome/elementor#2443]
## Description

When inserting from the predefined template library I get a 500 server error. This does not happen when I insert one of my own elementor templates. 

![elementor error](https://user-images.githubusercontent.com/25879066/30645574-6f5ee9fa-9e16-11e7-86a9-09cebd51aee6.PNG)

Problem started after I updated wordress to 4.8.2 today, and the issue is the same for all my websites, and they are running on different servers.

## Steps to reproduce

1. update elementor and wordpress to latest version
2. create a new elementor template, or, edit any existing site with elementor
3. insert any predefined template

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.13.3
	MySQL version: 5.7.19
	PHP Version: 7.1.8-2+ubuntu16.04.1+deb.sury.org+4
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: https://wordpress.gantic.no
	Home URL: https://wordpress.gantic.no
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: nb-NO
	Timezone: Europe/Oslo
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child Theme
	Version: 1.0.0
	Author: Robin Foldnes
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 1.4
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: nb_NO
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.4
		Author: Elementor.com

	Meta Slider
		Version: 3.5.1
		Author: Team Updraft

== Debug ==
	Errors: 
		TypeError: Cannot read property 'removeClass' of undefined
			at https://wordpress.gantic.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.3 - 2:104205
			2017-09-19 12:32 +00:00

		TypeError: Cannot read property 'removeClass' of undefined
			at https://wordpress.gantic.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.3 - 2:104204
			2017-09-16 10:34 +00:00
			x 2 times

**Comment by arielk** [comment]
This is something that was fixed in the latest versions, try updating to version 1.7.5 and let me know if it works out for you
