### ISSUE TITLE
Feature request: Option for standard top/bottom padding on sections

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2446]
**Currently:** When you create an section it gets 0px padding on the top and bottem. Because of this all the sections are very close to eachother. In order to change this, you need to edit the padding for every section, every time. Which is a lot of work to do. 

**Suggestion:** It would be very nice to set an standard padding for the sections. Just like for the space between colums.

Of course it's possible to do this with CSS in the theme, however then I will be applied to all sections and it's harder to overwrite it. So being able to set it up in elementor itself would make more sence and save a lot of time.

Thanks!

**Comment by dave-hiddendepth** [comment]
It would be great for this to be part of the Global Settings

**Comment by arielk** [comment]
I merged this issue with another issue #965 so we could deal with it more efficiently. 

Thanks for your feedback!
