### ISSUE TITLE
[FR] Connect EP Forms Widget to CPT's

### ISSUE THREAD

**Issue by Ver3** [pojome/elementor#2447]
### Specific use case, to clarify Feature Request

We are building a gallery site that showcases Sites built with OceanWP Theme and Elementor. Designers can submit their website filling in a Form and attach an image. After submit, one of the Admins reviews the entry and pushes it live.

In the background, we'd like the info from the form to fill an entry in a Custom Post Type we've made. From there it gets shown using the Portfolio Widget (or something similar with AJAX loading).

Resulting in users being able to see actual live sites built with Elementor and OceanWP. This is all done non-profit. We're just doing it to support both Elementors Community and OceanWP Community Facebook groups.

### The question

Is there any way to have the form 'talk' to our CPT? If not, please consider this as a future request.

Any answer or suggestion is most welcome!

**Comment by Ver3** [comment]
Also -just curious and asking any other user- what would be the best CPT plugin in combination with Elementor?

**Comment by bainternet** [comment]
@Ver3 

There are many hooks in place to do something like that very easily, just catch the 
`elementor_pro/forms/valid_record_submitted` action hook and you will have the valid record which you can save as your custom post type.

check [this for example ](https://github.com/yehudah/elementor-pro-forms-leads/blob/master/plugin.php).

As for CPT plugin in the link from above you can see a very simple example of how to register a post type without a plugin.
