### ISSUE TITLE
When it loads the shortcode it looks ugly

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#2448]
Hello guys, I'm using shortcode to use a header that I built with elementor, but when is loading it looks ugly

Print: http://prntscr.com/gnmylf

link: https://aprendapiano.com/contato-teste/

**Comment by bainternet** [comment]
Read this guide and see if it helps you
https://docs.elementor.com/article/249-embedded-template-css-loading

please feel free to reopen if issue persists.
