### ISSUE TITLE
Full page height video

### ISSUE THREAD

**Issue by vencoder** [pojome/elementor#2449]
Hello,

How can I add a full page Youtube video that can be played upon clicking? 

The other option is to set the video as a section background but youtube starts to play automatically which is far from ideal. 

I tried the VH/VW option to set the height of the section but that hasn't helped as the column stacks up when the page is resized or viewed in the mobile. 

Any help, pointers would be of great help.

![ss1](https://user-images.githubusercontent.com/24566642/30666027-a9e69262-9e70-11e7-8312-19ad045fe316.jpg)

Kind Regards!

**Comment by arielk** [comment]
Please watch this video: https://www.youtube.com/watch?v=KZVVaeil1rM
