### ISSUE TITLE
Image carousel won't fande

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#245]
the image carousel is only sliding pictures, but not fading them

**Comment by yehudah** [comment]
Can you screenshot or give more details about what you defined ?

**Comment by Luxamman** [comment]
Well - it is about the"Image Carousel widget". 
In the options, you can define that it fade between the pictures instead of sliding. You can change the option to fade, but it still slides the pictures.

**Comment by yehudah** [comment]
Can you go the elementor menu --> sys info and paste it to a service like pastebin.com ?

**Comment by Luxamman** [comment]
== Serverumgebung ==
	Betriebssystem: Linux
	Software: Apache/2.4.20
	MySQL Version: 5.6.19
	PHP-Version: 5.6.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD installiert: Yes

== WordPress Umgebung ==
	Version: 4.5.3
	Site URL: http://---
	Home URL: http://---
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Struktur: /%year%/%monthnum%/%day%/%postname%/
	Sprache: de-DE
	Zeitzone: Europe/Berlin
	Admin E-Mail: ---
	Debug Modus: Inactive

== Theme ==
	Name: Zerif Light
	Version: 0.1
	Autor: ---
	Child Theme: No

== Benutzer ==
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

== Aktive Plugins ==
	Elementor
		Name: Elementor
		Version: 0.4.1
		Author: Elementor.com

	Livemesh SiteOrigin Widgets
		Name: Livemesh SiteOrigin Widgets
		Version: 1.3
		Author: Livemesh

	Password Protected
		Name: Password Protected
		Version: 2.0.3
		Author: Ben Huson

	SiteOrigin Widgets Bundle
		Name: SiteOrigin Widgets Bundle
		Version: 1.6.2
		Author: SiteOrigin

	SiteOrigin Widgets by CodeLights
		Name: SiteOrigin Widgets by CodeLights
		Version: 1.1.1
		Author: CodeLights

	Visual Slide Box Builder
		Name: Visual Slide Box Builder
		Version: 1.3.4
		Author: Enmanuel Corvo

**Comment by yehudah** [comment]
Sorry for the trouble
I just noticed a bug and I just sent a fix.

When you update your version, just notice the effects work on one slide mode only.

Thanks for the input.

**Comment by yehudah** [comment]
The fix still not available, hope in 2-3 hours.

**Comment by yehudah** [comment]
#253
