### ISSUE TITLE
Accordion widget looses its content while editing.

### ISSUE THREAD

**Issue by ryanlabelle** [pojome/elementor#2450]
## Description

When adding and editing the Accordion widget, the content disappears and it's not retrievable.

Related to: https://github.com/pojome/elementor/issues/2324

## Steps to reproduce

1. Fresh install of WordPress 4.8.2
2. Fresh install of Elementor  1.7.4
3. Activate Twenty Seventeen Theme
3. Edit Sample Page with Elementor
4. Drag Accordion Widget onto screen.
5. Start adding content to content area, adjusting sort order of accordions while editing and expanding / contracting boxes. Just play around with it. 

It's intermittent but there is something going on for sure. I took a video: https://cl.ly/1X0M1d2B2A1F

I also didn't see any javascript errors in the console. 

## Environment

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.23 (Unix) PHP/5.6.28 LibreSSL/2.2.7
	MySQL version: 5.7.16
	PHP Version: 5.6.28
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://local/elementor
	Home URL: http://local/elementor
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Twenty Seventeen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.4
		Author: Elementor.com

== Debug ==
	Errors: There are no errors to display

**Comment by ryanlabelle** [comment]
I've noticed that when switching the text control from WYSIWYG to TEXTAREA the content is not lost. Any idea when you'll be looking into this? Thank you for your awesome support.

**Comment by bainternet** [comment]
If issue persists please contact our support at support@elementor.com
