### ISSUE TITLE
Two the_content() on a page.

### ISSUE THREAD

**Issue by rushijagani** [pojome/elementor#2451]
## Description

I have created custom post type(hooks) to add content conditionally in the various hook areas of the theme.
I have created a hook lets say **above footer** (which shows the content above the footer), to get the content I used **the_content()** on a page.
It works perfectly on the front end and there are two the_content() on a page but when I open the Elementor editor only the main page content is visible, the other custom post type(hooks) content is not visible.
Couldn't find any solution for this issue.
Thanks in advance.

## Steps to reproduce
On a page add two the_content(), one for actual content and the other one from any custom post type.

## Environment
I am using WordPress 4.8.2

**Comment by norewp** [comment]
Although it may work perfectly on the frontend it is not the correct method of doing things!

To add your extra hooked content use page panels instead - fetch the desired content via ID and hook it via the add_action() function. For example code see TwentySeventeen theme!

Elementor works by filtering the_content() function and it will only pick the first function it finds!

**Comment by bainternet** [comment]
@norewp is correct it may work on the frontend but its really not the correct way of doing it, and also about Elementor using `the_content` filter witch is triggered by `the_content`.  

When you open Elementor it is tied to a single post type id, so it will only work with the content of the first ID.
