### ISSUE TITLE
[Enhancement] Different colors for section and elements settings (hover)

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2453]
Currently: In a previous update there has been made a color difference between rows and sections. I think this was a great move, now the difference between sections and columns are more clear.

However elements and sections still have the same color. Since the settings-hover icons all look the same it's not clear right away which tab is for what settings.

Suggestion: Change the color of the elements to a very different color, like green for example. Than you willl see in a split second which buttons are for which settings. This will also help to get a better overview of what you are placing where (#2409) 

![highlight-colors](https://user-images.githubusercontent.com/5883842/30685801-67fb4942-9eb6-11e7-81c3-f509a9b5635f.png)

**Comment by bainternet** [comment]
@atMaarten 

In the next release, we should have a better handling, probably context menu.
