### ISSUE TITLE
Accordion - allow other Elementor widgets to be placed inside each accordion area (nested)

### ISSUE THREAD

**Issue by davidmcc3** [pojome/elementor#2455]
## Description

The content area for each Accordion item is just a text box. Would like to have other Elementor widgets inside each accordion item ... e.g. Columns, Image Box, Image, Heading, Button.

Don't know how difficult it would be to achieve this, but it would greatly improve the usefulness of the Accordion.

**Comment by bainternet** [comment]
I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by victorsalmon** [comment]
Yes please! This feature would save me a lot of time ^.^ - even if it's only offered to paid clients (I'm a paid user)

**Comment by autumncorvus** [comment]
Yes please! Will need this if I'm going to consider building any further sites using Elementor.

**Comment by RobinKMullins** [comment]
Would love to be able to drop a button into an accordion row. Yes, I can create a text link which does the same thing but it changes the user's experience. Being able to use a button will provide consistency across the site.

**Comment by aspoonemore** [comment]
+1

**Comment by designworksinteractive** [comment]
yes please really need this feature for project

**Comment by dimoteca** [comment]
+1

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Core= v3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
