### ISSUE TITLE
Template library - display 'My Templates' before 'Pre-defined Templates'

### ISSUE THREAD

**Issue by davidmcc3** [pojome/elementor#2456]
## Description

I don't know if my use of templates is unusual ... but I usually want to access one I've saved, not one of Elmentor's pre-defined templates.

It would be nice if the library selection started with 'My Templates' instead of 'Pre-defined Templates'.

Or maybe you could give us the choice to set which displays first.

**Comment by atMaarten** [comment]
+1! Would like to see this as well. Or the ability to disable the pre-designed template library would also be great.

**Comment by l3enito** [comment]
+1

**Comment by Choufourax** [comment]
+1 for the ability to disable the pre-designed template library.

**Comment by ataniker** [comment]
+1

**Comment by JuTu83** [comment]
+1

**Comment by Jaska** [comment]
+1

**Comment by quantissimo** [comment]
+1

**Comment by ravilrrr** [comment]
+1

**Comment by jayalove** [comment]
I second this request 😉

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
So this has been partially implemented, Both in admin, the first link is now "My library" and in the editor, the library modal opens with the last viewed tab open.

thanks everyone for the suggestion.
