### ISSUE TITLE
Animated Headline Do Not Loop?

### ISSUE THREAD

**Issue by Creativenauts** [pojome/elementor#2457]
How can i make the animated headline not loop? I see no option for it.

**Comment by arielk** [comment]
Unfortunately there is no such possibility for now, we will probably add in the future.

Thanks for your feedback!

**Comment by idealsud** [comment]
+1 , is it possible to disable the loop for the underline option ?

**Comment by Turanligil** [comment]
+1

**Comment by shilo-ey** [comment]
@StartupSam 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Deralict** [comment]
+1

**Comment by richardfila** [comment]
Ditto to animation control requests above.

**Comment by dumbledorian** [comment]
Play it once, Sam! And adjustable letter speed,. Yes please. That would be great.

**Comment by gaintap** [comment]
Not the most graceful solution, but you can do this with some CSS. 

Here's a working example using the underline animation (illustrated on [this page](https://www.gaintap.com/what-we-do/)):

**Keyframes adjustment to remove opacity**
`@keyframes elementor-headline-dash {
		0% {
    stroke-dasharray: 0 1500;
}
	15% {
		stroke-dasharray: 1500 1500;
	}
100% {
    stroke-dasharray: 1500 1500;
}
}
`

**Animation adjustment to remove infinite loop**
`.elementor-headline--style-highlight svg path {
animation-iteration-count: 1!important;
}
`

**Comment by MichaelDarko** [comment]
Two and a half years and still waiting for this simple thing. Why is this closed? :-/ There should definitely be an option to disable repeating animation. Most people don't want a repeated underlining animation, makes no sense.

**Comment by wildmercury** [comment]
+1

**Comment by musicmxn** [comment]
agreed

**Comment by UberNerdBoy** [comment]
Still no word on being able to stop looping animations?

**Comment by aaronkine** [comment]
+1 agreed. need more control.

**Comment by karlv-79** [comment]
+1 
btw. thank you gaintap for the CSS. That did the job. 
@ Elementor team - maybe add gaintap's solution to your documentation in the meantime.

**Comment by musicmxn** [comment]
+1 Please add this feature!

**Comment by gaintap** [comment]
> +1
> btw. thank you gaintap for the CSS. That did the job.
> @ Elementor team - maybe add gaintap's solution to your documentation in the meantime.

No problem, thanks for commenting - you reminded me to remove the example link in my comment that is no longer live.

**Comment by kaelhoel** [comment]
+1 There should be an option to stop the infinite loop of the animated headline.

**Comment by musicmxn** [comment]
Hi All, 
Does anyone know if it's possible to stop animated loops for elementor's rotating style text as well?

Thanks in advance!

**Comment by musicmxn** [comment]
Two things: 
1) we need to be able to stop animated loops for elementor's rotating style text.
2) Animated text should be adjust properly with the accessibility feature of "increase text size". Currently the text gets hidden when you try doing that.

**Comment by sebasttti** [comment]
> 
> 
> Not the most graceful solution, but you can do this with some CSS.
> 
> **Keyframes adjustment to remove opacity**
> `@keyframes elementor-headline-dash { 0% { stroke-dasharray: 0 1500; } 15% { stroke-dasharray: 1500 1500; } 100% { stroke-dasharray: 1500 1500; } } `
> 
> **Animation adjustment to remove infinite loop**
> `.elementor-headline--style-highlight svg path { animation-iteration-count: 1!important; } `

It works, thank you man. Please implement it officially

**Comment by enfeitador** [comment]
> Not the most graceful solution, but you can do this with some CSS.
> 
> **Keyframes adjustment to remove opacity**
> `@keyframes elementor-headline-dash { 0% { stroke-dasharray: 0 1500; } 15% { stroke-dasharray: 1500 1500; } 100% { stroke-dasharray: 1500 1500; } } `
> 
> **Animation adjustment to remove infinite loop**
> `.elementor-headline--style-highlight svg path { animation-iteration-count: 1!important; } `

I wasnt able to make this work, can you explain in detail? Just pasting the code on the CSS field doesnt work.

**Comment by v8ive** [comment]
Could use this option....how come it still isn't a thing? Plenty of requests from years ago to even now....Please fix!

**Comment by newminya** [comment]
Please add this functionality!

**Comment by itsViney** [comment]
+1 for this

**Comment by yoruyenturk** [comment]
+1

**Comment by jeffro84** [comment]
+1
Please add this feature!

**Comment by seDomhag** [comment]
Yes, please add this control! Thx!

**Comment by shilo-ey** [comment]
> Yes, please add this control! Thx!
This feature is available in Elementor Pro - dev version 3.1.0

Get it using [Elementor Beta - developer edition](https://wordpress.org/plugins/elementor-beta/), until released in a stable version

**Comment by TheLunchLotterist** [comment]
Where can I find this in the elementor beta version? Got it installed, but can't find it anywhere

**Comment by KeviNmp4** [comment]
+1
