### ISSUE TITLE
Display Postlist (image+text/excerpt) in portfolio, carroussel, slides

### ISSUE THREAD

**Issue by golf1025** [pojome/elementor#2459]
The postlist element cannot be included in elements where multiple elements van be displayed: slides, portfolio carroussel.
It is desirable that the postlist can be displayed in portfolio, slides, carroussel
see: https://newfw.quitewrite.nl/ons-portfolio

**Comment by bainternet** [comment]
I merged this issue with #2458 , which are on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!
