### ISSUE TITLE
Set link to 'none' for (featured) images = no back-linking to post

### ISSUE THREAD

**Issue by golf1025** [pojome/elementor#2461]
In all elements that use a (featured) image,  clicking on the image/title links back to the post. Where the post sometimes contains no extra information, this back-linking is undesirable and frustrating for the visitor and results in the visitor leaving the site. 
Therefore and option set the link to 'none' or 'no' is urgently requested. This is applicable to the portfolio element, the slides element, the iamge box and the carroussel.
see: https://newfw.quitewrite.nl/ons-portfolio.

**Comment by bainternet** [comment]
For that you can use the Gallery widget.
