### ISSUE TITLE
Fatal error: Class not found loading custom widgets

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#2465]
Hi, I'm building some little custom widgets. I added one without any problems. Then I'm adding a second one, a super-super simple one. But I keep getting an error when loading elementor editor:

`Fatal error: Class 'LR\VerticalSeparator' not found in [path]/wp-content/plugins/lr-elementor-addons/plugin.php on line 41`

Now, I've checked 1000 times the names and the paths and it --should-- find the class. Why not?

I'm attaching the plugin. Am I doing something wrong with the Elementor inner syntax maybe?

Thank you

[lr-elementor-addons.zip](https://github.com/pojome/elementor/files/1324586/lr-elementor-addons.zip)

**Comment by norewp** [comment]
You are missing `use LR\Widgets\VerticalSeparator;` at the top of plugin.php

**Comment by stratboy** [comment]
Great! Thank you very much!

Zulfikar Nore ha scritto:
