### ISSUE TITLE
Google webfont  loading improvement 

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#2467]
The selected font family's all font weight is loaded. I think its better to load only the used font weight. 

![capture](https://user-images.githubusercontent.com/7946657/30748370-f1581550-9fd1-11e7-8dc7-3b82920aa817.PNG)

**Comment by arielk** [comment]
I merged this issue with another issue #2088 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
