### ISSUE TITLE
Columns not inheriting parent section's min-height in IE

### ISSUE THREAD

**Issue by ge022** [pojome/elementor#2472]
## Description
Columns on Internet Explorer, version 11 and down, do not inherit their parent section's min-height.
In Chrome:
![image](https://user-images.githubusercontent.com/23706821/30777504-68fce45c-a070-11e7-9c9a-871195bd97f9.png)

Problem in Internet Explorer: 
![image](https://user-images.githubusercontent.com/23706821/30777496-41b32528-a070-11e7-8192-17c1c1b21dfc.png)

## Steps to reproduce

1. Add the columns element to a new section
2. Apply a min-height to the new section and or the columns' section
3. Apply a background style and add a heading element to the columns

## Environment
			
```
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.4
	MySQL version: 5.5.5
	PHP Version: 7.1.4
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://localhost/wordpress
	Home URL: http://localhost/wordpress
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: mortar-child
	Version: 
	Author: 
	Child Theme: Yes
	Parent Theme Name: MORTAR THEME
	Parent Theme Version: 
	Parent Theme Author: 

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.4
		Author: Elementor.com

== Debug ==
	Errors: 
		ReferenceError: MasterSlider is not defined
			at http://localhost/wordpress/wp-admin/post.php?post=29&action=elementor - 6:29
			2017-09-13 21:02 +00:00
```

**Comment by bainternet** [comment]
@ge022 

This is kind of a known issue with IE11 and `min-height,flex,align-items...`

The quickest and simplest way around it is to set the `height` the same as the `min-height`.

https://css-tricks.com/snippets/css/cross-browser-min-height/

**Comment by pulla** [comment]
It doesn't work in IE 11. It's a modern browser. That means we can't use "position" middle with min-height.

So do we need to add a custom css code for this issue?
There is no field to add a height.
There is no a custom field in normal version.

**Comment by julianxhokaxhiu** [comment]
Exactly as said in https://github.com/pojome/elementor/issues/3005#issuecomment-359363447 I have the same issue. Can't set an height manually. Only min-height option is there.
