### ISSUE TITLE
[Feature Request] 'Posts' Widget - Excerpt Length & Configuration 

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2478]
Hey,

Would be really awesome if we could configure the length of the excerpt per card, rather than all the cards together. It's really difficult to tailor the length for each card when every post has different content.

What tends to happen is some excerpts will cut off mid-sentence, making it look broken; which leads onto my next request... 

Adding an elipsis (...) to the end of the excerpt if the full content is not retrieved.

Thanks for your consideration!

**Comment by arielk** [comment]
Unfortunately we cannot set the length of words per card, you can use the box of the excerpt in the post to give the exact length that suits you.

Anyway I hope we will add ellipsis for the excerpt in the future.

Thanks for your feedback!

**Comment by enviedbymost** [comment]
RE: your comment above, this doesn't work.

Let's say I have 2 posts in the post widget.

1st post is 2,000 words and I want the excerpt to be 20 words
2nd post is 1,000 words and I want the excerpt to be 10 words.

Because I cannot set the excerpt length for each post, I end up retrieving 10 extra words from post 2 that I don't want in the excerpt.

If I go into the 2nd post and try to separate the text so that the 10 words I want is in it's own text box and section, the Posts widget automatically pulls text from other sections on the post so there's literally no way of me retrieving the exact text excerpt I want per card.

This becomes increasingly difficult to manage with multiple posts of different content.

Unless the content of each post starts identically, this feature is useless in it's current implementation.

Hope that makes sense!

**Comment by sarahdenise** [comment]
Hi, Is there any update regarding the ellipsis?
It would really be helpful.

Thank you!

**Comment by ddelker** [comment]
I would echo that request to add an ellipsis. I just started using the widget today, and found that the excerpt ended abruptly with no ... following the last word, which looks really incomplete. I hope to see that change soon! Thanks!

**Comment by gopirates612** [comment]
Also looking for the ellipsis. This seems like a really strange thing to overlook. As ddelker said, the excerpt looks incomplete without it. I've never seen an excerpt without one until now, and it is borderline unusable in the current state.

**Comment by enviedbymost** [comment]
@arielk - there appears to be a fair amount of appetite for the suggestions I made.

Could you please re-open this thread?!

**Comment by eblosch** [comment]
This seems to work as a quick CSS workaround:
```
.elementor-post__excerpt p:after {
    content: ' ...';
}
```

**Comment by gopirates612** [comment]
Thank you!

**Comment by hilli006** [comment]
Yeah, thanks! I was hoping to find the custom CSS to add an ellipsis after the excerpt. Works like a charm
