### ISSUE TITLE
[Feature Request] Use the standardized JavaScript ObserverIntersection API

### ISSUE THREAD

**Issue by csmit195** [pojome/elementor#2479]
Hi there, I'm a website developer with high focuses on front end optimization. I personally love your plugin and feel that this feature would seriously increase the efficiency of how you handle objects that are in viewports. This is exceptionally great for Lazy Loading images (that'd be a cool native elementor feature) and google maps. You can read about IntersectionObservers on David Walshes blog: https://davidwalsh.name/intersection-observers

Essentially its a standardized API for tracking when objects go in and out of the viewport, and it runs on an entirely seperate CPU thread eliminating render blocking entirely. For google maps, you'd create the map via the JS API once the callback is called for when the map div would come into view. Take a look around, it has many potentials for websites, you may also need to load the polyfill for it, as Safari and IE11 are slow, as always.

Cheers,
Chris.

**Comment by bainternet** [comment]
thanks for the suggestion, we are aware of the ObserverIntersection API and if we feel the need we will use it.

thanks for the suggestions.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.22.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
