### ISSUE TITLE
FR: Layers panel for better elements navigation

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2485]
Hello! Layers panel would be nice feature for better usability. Sometimes we need to use negative margins and z-index and it's very difficult to access to the bottom elements.

Another good feature — draging element from layer to another. Here is my story scenario for better understand:
I have landing page ~8000px long. And I need copy the phone number from header to the footer. 20 seconds of draging from top to bottom and it's in place. The laugh and sin =)

The best example that I ever use — webflow page builder.

Thanks!

**Comment by gahawkey** [comment]
Another example of functionality that could be connected with this feature request is the breadcrumb. Thrive Architect uses a breadcrumb across the top of the edit UI enabling easy selection of parent elements :)

**Comment by parfilov** [comment]
@gahawkey Smart Slider 3 plugin has it too and layers are amazing in it too.

**Comment by Fxcrafter** [comment]
I'm about 50% with a plugin for this, but struggling with the js side of things. If anyone with backbone/marionette experience wants to help me out, it won't take much effort at all to get a basic version out. #1165

**Comment by fxaviers** [comment]
I have a header over a row with a negative margin and it is simply impossible to select it. That would help a lot!

**Comment by Fxcrafter** [comment]
@fxaviers I've just released a [plugin](https://wordpress.org/plugins/navigation-tree-elementor) for this , I hope it helps.

Let me know if you run into any issues with it, I know there are many improvements but I am happy to start a wishlist as well.

**Comment by parfilov** [comment]
I don't want to use side solutions. There are endless troubles with them.

**Comment by fxaviers** [comment]
@Fxcrafter I also prefer to use a native solution instead of third-party plugins. However, as soon as possible I will test the plugin.

**Comment by bainternet** [comment]
I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
