### ISSUE TITLE
Background Overlay border radius 

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#249]
"Background Overlay" in sections, don't react with the border radius - sample pictures shows the rounded corner of the picture, but the "Background Overlay" (blue) is still reaching the corners

![prob2](https://cloud.githubusercontent.com/assets/20417555/16770814/8683f324-484e-11e6-9e5a-3b37b6d08156.png)

**Comment by KingYes** [comment]
@Luxamman Thanks!
