### ISSUE TITLE
Class New_Widget extends Posts with skins

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#2492]
When I make a new class that extends the Posts class

because of this in Skin_Base class:

add_action( 'elementor/element/**posts**/section_layout/before_section_end', [ $this, 'register_controls' ] );
add_action( 'elementor/element/**posts**/section_query/after_section_end', [ $this, 'register_style_sections' ] );

..the skin in the New_Widget is not working.

Can you please fix this?

**Comment by KingYes** [comment]
You need to override the `Skin_Base` class and change this for your own used.

**Comment by seksitha** [comment]
For those who want the syntax  of the hook. this code is in the line `controls-stack.php`
`do_action( "elementor/element/{$stack_name}/{$section_id}/before_section_end", $this, $args );`
`stack_name` is `widget name` `section_id` is `section name`
