### ISSUE TITLE
[New Feature] Easy Client Page Building

### ISSUE THREAD

**Issue by MarioStart** [pojome/elementor#2495]
Hi, 
I have many wordpress clients and would be a great feature to have a feature that allow them only to add pages from a set template and restricting access to other areas of the page build. 
This would help stop having the site being broken.
Just text and image very simple to add blog/pages.
White labeling it would be great also a separate login.

Big fan of elementor.
Thanks

**Comment by bainternet** [comment]
I merged this issue with  #417  , which are in the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
