### ISSUE TITLE
Bug in "testimonials widget" on skin "bubble"

### ISSUE THREAD

**Issue by salvimateus** [pojome/elementor#2497]
- I have the Elementor updated
- I have only the Elementor e ElementorPRO activated
- I am using the default WordPress Theme "Twenty Fifteen"

## Description

When switching to the "bubble" skin, the carousel does not work.

## Steps to reproduce

![animacao](https://user-images.githubusercontent.com/10764410/30888269-f1d34726-a2f5-11e7-816c-08f443309122.gif)

## Environment

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.23 (Win64) PHP/7.0.10
	MySQL version: 5.7.14
	PHP Version: 7.0.10
	PHP Max Input Vars: 2500
	PHP Max Post Size: 100M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://localhost/wp/
	Home URL: http://localhost/wp/
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: -3
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Fifteen
	Version: 1.8
	Author: wordpressdotorg
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.6
		Author: Elementor.com

	Elementor Pro
		Version: 1.9.0
		Author: Elementor.com

== Debug ==
	Errors: 
		TypeError: Cannot read property 'size' of undefined
			at http://localhost/wp/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.9.0 - 2:9864
			2017-09-26 22:57 +00:00
			x 27 times

		ReferenceError: acfw is not defined
			at http://localhost/wp/plugin-elementor/?elementor - 1:2
			2017-06-14 02:56 +00:00
			x 2 times

**Comment by arielk** [comment]
Fix for v1.9.1

Thanks for your feedback!
