### ISSUE TITLE
Specify which typography option to show

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#2500]
Is there any filter to show only specific typography options? Say I want to show only font-family while skipping other options.

**Comment by arielk** [comment]
Do you want to use this control on your own widget?

Related issue: https://github.com/pojome/elementor/issues/2491

**Comment by bainternet** [comment]
Late to the party, but anyway, you can specify which fields to remove using the `exclude` parameter ex:

```PHP
$this->add_group_control(
	Group_Control_Typography::get_type(),
	[
		'name' => 'typography_field',
		'label'    => __( 'Typography', 'elementor' ),
		'selector' => '{{WRAPPER}} .some_class',
		'exclude' => [ 'font_size', 'line-height' ],
	]
);
```

to see the list of fields included in the Typography field group take a look at [source](https://github.com/pojome/elementor/blob/release/1.8.9/includes/controls/groups/typography.php#L111).

Hope this helps.

**Comment by djekanovic** [comment]
How to extend Hello World sample plugin with that Group Control? I Guess that 
`class Group_Control_Typography extends Group_Control_Base` 

needs to be implemented somewhere?

**Comment by djekanovic** [comment]
Found solution here. 
https://github.com/pojome/elementor/blob/1b9044ebd84d86ef1402a8997d4fed1c7ae72a84/docs/content/controls/_group_control_typography.md
