### ISSUE TITLE
Accordion and Toggle does not unfold when Elementor PRO enabled #bug 

### ISSUE THREAD

**Issue by rizny77** [pojome/elementor#2503]
Accordion and toggle widgets does not work when PRO enabled. Usually these widgets works on live editor with Elementor PRO enabled but does not work when i test it on the browser . If i disable the PRO a strange thing happens , the accordion widget i added disappear even though its from the free plugin.

After that i added an accordion without PRO enabled and it's working now.
I checked the html of the live editor

But "style="display: block; " does not appear on the page.

**Comment by bainternet** [comment]
We did a little rework and minor fixes to the Accordion/Toggle widgets in 1.8 which should sove the issue described. 

If not feel free to re open.

**Comment by DerekBess** [comment]
just updated and toggle content is missing.

**Comment by bainternet** [comment]
@DerekBess 

"toggle content is missing"? can you elaborate?

**Comment by DerekBess** [comment]
the content is no longer there. We went back and added the content in the accordions prior to the website launch and will keep a close eye to see if this continues to be an issue.

**Comment by bainternet** [comment]
Thanks for reporting.

**Comment by ibes** [comment]
This still is broken for me. 

The toggle element works in the preview/editor. 
But it doesn't work in the live version of the site. 

Disable Elementor Pro doesn't make a difference for my page. 

The display:none is not toggled and it's just the toggle-title that is shown the toggle-content is not shown. 

Any updates on that one?

**Comment by skrubbeltrang** [comment]
Same problem, toggle was initially working but now clicking toggle simply reloads the page.

**Comment by freelinemike** [comment]
I am having this problem.  The toggle does not work to display my text.  It just reloads the page.  I have Elementor Pro.
