### ISSUE TITLE
Lightbox for Video from Text link

### ISSUE THREAD

**Issue by waltark** [pojome/elementor#2505]
## Description

I love the LIghtbox for Video, but need to be able to launch the Lightbox from a Text link, in the same way.

I've installed a Plugin to attempt this, but it doesn't seem to work either.

## Steps to reproduce

Not a bug report, just a Feature Request

## Environment

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.2.22
	MySQL version: 5.1.63
	PHP Version: 7.0.6
	PHP Max Input Vars: 1000
	PHP Max Post Size: 99M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://claimingradiance.com
	Home URL: http://claimingradiance.com
	WP Multisite: No
	Max Upload Size: 99 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: wordpress@novelwebsitedesign.com
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.3.9
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

== Active Plugins ==
	Admin Page Spider
		Version: 3.11
		Author: J7Digital

	Akismet Anti-Spam
		Version: 4.0
		Author: Automattic

	BackUpWordPress
		Version: 3.6.4
		Author: Human Made Limited

	Contact Form 7
		Version: 4.9
		Author: Takayuki Miyoshi

	Elementor
		Version: 1.7.6
		Author: Elementor.com

	Flamingo
		Version: 1.7
		Author: Takayuki Miyoshi

	Google Analyticator
		Version: 6.5.4
		Author: SumoMe

	Maintenance Mode
		Version: 5.4
		Author: Michael Wöhrer

	Ocean Extra
		Version: 1.3.2
		Author: OceanWP

	Ocean Modal Window
		Version: 1.0.9
		Author: OceanWP

	Ocean Sticky Header
		Version: 1.0.9
		Author: OceanWP

	Responsive YouTube & Vimeo Video Popup
		Version: 1.1.1
		Author: MapSteps

	Testimonial Rotator
		Version: 2.2.4.1
		Author: Hal Gatewood

	Wordfence Security
		Version: 6.3.19
		Author: Wordfence

== Debug ==
	Errors: 
		TypeError: Cannot read property 'removeClass' of undefined
			at http://claimingradiance.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.5 - 5:11873
			2017-07-29 15:13 +00:00

**Comment by billyhoiler** [comment]
+1 and please also for buttons and not just text 
(was really surprised I cannot open a video in a lightbox triggered by a button)

**Comment by bainternet** [comment]
This can be easily done with some minor Javascript something like:

```JS
jQuery( document ).ready(function($){
    $('.BUTTON_LINK_SELECTOR').on('click',function( event ){
        event.preventDefault();
        elementorFrontend.utils.lightbox.showModal({
	        url: 'https://www.youtube.com/embed/9uOETcuFjbE?feature=oembed&rel=0&controls=0&showinfo=0&mute=0&wmode=opaque',
        	videoAspectRatio: '169',
	        type: 'video',
        });
    });
});

**Comment by besweeet** [comment]
@bainternet I added that JavaScript to my theme and replaced .BUTTON_LINK_SELECTOR with my div's class. Nothing happens.

**Comment by harunalikadic** [comment]
Where to find reference to all parameters of lightbox showmodal?

**Comment by swinggraphics** [comment]
Here is my simple version, which handles YouTube only, but that's all I need for now:

```
$('.elementor-widget-button.lightbox').click(function(event){
	var videoLink = $(this).find('a').attr('href');
	var videoID = elementorFrontend.utils.youtube.getYoutubeIDFromURL(videoLink);
	if( ! videoID ) return;
	event.preventDefault();
	var iframeSrc = 'https://www.youtube.com/embed/' + videoID + '?feature=oembed&rel=0&controls=1&showinfo=1&mute=0&wmode=opaque';
	elementorFrontend.utils.lightbox.showModal({
		url: iframeSrc,
		videoAspectRatio: '169',
		type: 'video'
	});
});
```

**Comment by Prankscl** [comment]
this works with self hosted videos??

**Comment by shaneonabike** [comment]
The suggestion above didn't work for me. For whatever reason the youtube.getYoutubeIDFromURL was throwing errors.

Here's my version for folks using ACF oEmbed fields (cause it already generates the proper link normally). As well, for self-hosted it should technically work because it just throws up the iFrameSrc as the embed link, but I haven't _tested_ it.

`jQuery(document).ready(function ($) {
  $('.elementor-widget-button.lightbox').click(function(event){
    var videoLink = $(this).find('a').attr('href');
    if (videoLink.indexOf("youtube") !== -1) {
      iframeSrc = videoLink.replace("www.youtube.com","www.youtube-nocookie.com");
      iframeSrc += '?feature=oembed&rel=0&controls=11&showinfo=0&mute=0&modestbranding=1&wmode=opaque&origin=http
s://www.yoursite.org';
    } else if (videoLink.indexOf("vimeo") !== -1) {
      iframeSrc = videoLink.replace("//vimeo.com","//player.vimeo.com/video");
      iframeSrc += '?autoplay=1&color=ff456d&title=0&byline=0&portrait=0';
    } else {
      // Another type of embed
      iframeSrc = videoLink;
    }

    // Stop current action and invoke lightbox
    event.preventDefault();
    elementorFrontend.utils.lightbox.showModal({
      url: iframeSrc,
      videoAspectRatio: '169',
      type: 'video',
      id: 'yourid',
      entranceAnimation: 'bounceInDown',
    });
  });
});
`

**Comment by rafaelhsouza-dev** [comment]
jQuery('.lightbox-youtube').click(function(event){
	var videoLink = jQuery(this).find('a').attr('href');
	var idyoutube = videoLink.match(/(^|=|\/)([0-9A-Za-z_-]{11})(\/|&|$|\?|#)/)[2];
	event.preventDefault();
        elementorFrontend.utils.lightbox.showModal({
	        url: 'https://www.youtube.com/embed/'+ idyoutube +'?feature=oembed&rel=0&controls=0&showinfo=0&mute=0&wmode=opaque',
        	videoAspectRatio: '169',
	        type: 'video',
        });
});

add css class (lightbox-youtube) in you target :)
