### ISSUE TITLE
Elementor and Toolset Plugins conflicts.

### ISSUE THREAD

**Issue by c6410** [pojome/elementor#2506]
## Description

Hi guys , Elementor and Pro does not work together with Toolset Plugins,
please check some info/thread here:

https://wp-types.com/forums/topic/toolset-and-elementor-bugs/
1.https://wp-types.com/forums/topic/conditional-code-is-outputting-raw-code/page/2/
2. https://wp-types.com/forums/topic/elementor-text-editor-bug/
3. https://wp-types.com/forums/topic/theres-a-bug-when-using-layouts-plugin-with-the-elementor-builder/

## Steps to reproduce

Install Toolset plugins and try to edit the layout .   Output is Only raw codes. 

## Environment

Operating System: | Linux |  
Software: | Apache |  
MySQL version: | 5.6.37 |  
PHP Version: | 7.1.9 |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 512M |  
GD Installed: | Yes |  
Elementor Library: | Connected

**Comment by c6410** [comment]
update from Amir the  owner of Toolset 

> The issues between Elementor and Toolset come because **Elementor, purposely, re-registers all Javascript.** We understand why it does that, but this makes compatibility very problematic. Imagine, if you write some code to achieve compatibility and the other plugin forces WordPress not to load it, it’s going to be pretty difficult to be compatible. Right?
> 
> There’s a very simple solution, but Elementor folks need to want it. They **need to have a whitelist of Javascript files that they DON’T kill when launching their editor.** Have you tried to suggest this to them?

**Comment by c6410** [comment]
another reply  from Amir

> Sure, thanks for helping and for being involved. There’s no need for a glue plugin. We’re interested. When also Elementor folks will be interested, we can resolve everything in a day. The more of their clients ask for it, the faster it will happen.

**Comment by c6410** [comment]
KingYes  any comment on this please...

**Comment by MarioCipo** [comment]
i guess it would be a powerfull dreamteam Elementor Pro with Toolset. Would really love it.

**Comment by bainternet** [comment]
@c6410 @MarioCipo 

We already allow scripts to be inserted, a 3rd party plugin that is interested in working in elementor has to enqueue his the scripts to Elementor in the Elementor accepted way in order for it to work.

as for integration with Elementor Pro, In V2.0 we added partial support for toolset fields only to extend it in coming versions.

thanks for the feedback.
