### ISSUE TITLE
[Feature Request] 'Posts' Widget - Excerpt Length & Configuration

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2509]
REOPENING this as this post was closed unresolved.

**Original comment:**

Hey,

Would be really awesome if we could configure the length of the excerpt per card, rather than all the cards together. It's really difficult to tailor the length for each card when every post has different content.

What tends to happen is some excerpts will cut off mid-sentence, making it look broken; which leads onto my next request...

Adding an elipsis (...) to the end of the excerpt if the full content is not retrieved.

Thanks for your consideration!

**Dev Reply**

Unfortunately we cannot set the length of words per card, you can use the box of the excerpt in the post to give the exact length that suits you.

Anyway I hope we will add ellipsis for the excerpt in the future.

Thanks for your feedback!

**My Reply**

RE: your comment above, this doesn't work.

Let's say I have 2 posts in the post widget.

1st post is 2,000 words and I want the excerpt to be 20 words
2nd post is 1,000 words and I want the excerpt to be 10 words.
3rd post is 1,500 words and I want the excerpt to be 20 words

Because I cannot set the excerpt length for each post, I end up retrieving 10 extra words from post 2 that I don't want in the excerpt, as I want 10, not 20.

If I go into the 2nd post and try to separate the text so that the 10 words I want is in it's own text box and section, the Posts widget automatically pulls text from other sections on the post so there's literally no way of me retrieving the exact text excerpt I want per card.

This becomes increasingly difficult to manage with multiple posts of different content.

Unless the content of each post starts identically, this feature is hard to use in it's current implementation.

Hope that makes sense!

**Comment by enviedbymost** [comment]
Hopefully the re-explanation made sense!

**Comment by enviedbymost** [comment]
To confirm, I've spoken with the support team (support@elementor.com) and they've confirmed this is an issye.

**Comment by bainternet** [comment]
@enviedbymost 

Your explanation was fine the first time, I just think you misunderstood the dev suggested solution.

What the dev said was to set the excerpt manually in the excerpt box in the post edit screen.

this works well if you set the limit to 20, you only have to go to the second post and enter 10 words you want manually in the excerpt box, then when you use the posts widget it will show up with these 10 words.
