### ISSUE TITLE
I can't customize the font on my menu

### ISSUE THREAD

**Issue by seengafus** [pojome/elementor#251]
Hi , I work on an Arabic website , I spent days trying to customize the menu font , font size and alignment without real progress , in the next picture  I compare one good website menu vs mine !
help please ...
![225](https://cloud.githubusercontent.com/assets/20388105/16775066/992c05a2-4867-11e6-884b-2fbd92471557.jpg)

**Comment by yehudah** [comment]
Hello

As I all ready told you, Here it's only to Elementor plugin from Pojo.
To get support for themes go here:
[http://support.pojo.me/forum/support/](url)
