### ISSUE TITLE
JavaScript issue with the global variable `elementor`

### ISSUE THREAD

**Issue by merianos** [pojome/elementor#2510]
## Description

Recently I read that HTML `id` attribute, in all modern browsers registering a global variable in the JavaScript window.

For example, if we have the following HTML:

```
<div>
    <span id="name">My name</span> and my <span id="address">address</span>
</div>
```

It is possible to run the following code using `JavaScript`:

```
window.name.innerText = 'My Age';
address.innerText = 'eye color;;
```

Due to this feature of the HTML5, it is not possible to run the following:

```
elementor.hooks.addAction( .... );
```

because it seems like you already have an HTML element in the editor using the attribute `id` with the value `elementor`.

If I try to run the following script:

```
$ ( window ).on (
        'load',
        function () {
            elementor.hooks.addAction(
                'panel/open_editor/widget/follow-os-on-instagram',
                function( panel, model, view ) {
                    // run some code
                }
            );
        }
)
```
I get the following error in my browser console:

```
Uncaught TypeError: Cannot read property 'addAction' of undefined
```

which is correct as the `elementor` global variable is pointing to the HTML element using it as `id`.

in addition, if I run the following code:

```
console.log( typeof elementor );
```

The output in my browser is this:

![elementor](https://user-images.githubusercontent.com/1220823/31016123-267cf53e-a52c-11e7-8789-7a9a0fe49867.jpg)

Which is also correct, as initially the global variable `elementor` points to the element with the attribute `id="elementor"` and then it points the `elementor` global object.

## Steps to reproduce

Try to run the code examples I have place above.

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.13.0
	MySQL version: 5.7.18
	PHP Version: 7.0.21
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://localhost:8000
	Home URL: http://localhost:8000
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Custome Made Theme
	Version: 2.0.0
	Author: Merianos Nikos
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.79 Chrome/61.0.3163.79 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.6
		Author: Elementor.com

	Regenerate Thumbnails
		Version: 2.3.1
		Author: Alex Mills (Viper007Bond)

== Debug ==
	Errors: 
		ReferenceError: tab_title is not defined
			at http://localhost:8000/wp-admin/post.php?post=107&action=elementor - 6:9
			2017-09-28 10:27 +00:00

		SyntaxError: Unexpected token )
			at http://localhost:8000/wp-includes/js/underscore.min.js?ver=1.8.3 - 5:15110
			2017-09-25 07:50 +00:00

		SyntaxError: Invalid or unexpected token
			at http://localhost:8000/wp-includes/js/underscore.min.js?ver=1.8.3 - 5:15110
			2017-09-21 13:49 +00:00
			x 25 times

**Comment by joshmarom** [comment]
I don't think it has to do with the reasons you mentioned, but rather it is probably because you are trying to interact with `elementor` too early - before it exists (`$ ( window ).on ('load' ... `).

Instead, try to run your code at the `'elementor:init'` hook.
```javascript
$ ( window ).on (
        'elementor:init',
        function () {
            elementor.hooks.addAction(
                'panel/open_editor/widget/follow-os-on-instagram',
                function( panel, model, view ) {
                    // run some code
                }
            );
        }
);
```
Let me know if that worked for you.

**Comment by merianos** [comment]
@joshmarom I am very new to Elementor, and to be honest, I didn't mention this event ( `elementor:init` ), and I guess this it could help a lot.

For now, I am not going to use it as I found another solution to my problem.

But in meanwhile, many other devs will try to run editor hooks on `document ready`. I guess a reference in the documentation will solve that issue. :)

Thank you again.

**Comment by Payaspx** [comment]
> ## Description
> Recently I read that HTML `id` attribute, in all modern browsers registering a global variable in the JavaScript window.
> 
> For example, if we have the following HTML:
> 
> ```
> <div>
>     <span id="name">My name</span> and my <span id="address">address</span>
> </div>
> ```
> 
> It is possible to run the following code using `JavaScript`:
> 
> ```
> window.name.innerText = 'My Age';
> address.innerText = 'eye color;;
> ```
> 
> Due to this feature of the HTML5, it is not possible to run the following:
> 
> ```
> elementor.hooks.addAction( .... );
> ```
> 
> because it seems like you already have an HTML element in the editor using the attribute `id` with the value `elementor`.
> 
> If I try to run the following script:
> 
> ```
> $ ( window ).on (
>         'load',
>         function () {
>             elementor.hooks.addAction(
>                 'panel/open_editor/widget/follow-os-on-instagram',
>                 function( panel, model, view ) {
>                     // run some code
>                 }
>             );
>         }
> )
> ```
> 
> I get the following error in my browser console:
> 
> ```
> Uncaught TypeError: Cannot read property 'addAction' of undefined
> ```
> 
> which is correct as the `elementor` global variable is pointing to the HTML element using it as `id`.
> 
> in addition, if I run the following code:
> 
> ```
> console.log( typeof elementor );
> ```
> 
> The output in my browser is this:
> 
> ![elementor](https://user-images.githubusercontent.com/1220823/31016123-267cf53e-a52c-11e7-8789-7a9a0fe49867.jpg)
> 
> Which is also correct, as initially the global variable `elementor` points to the element with the attribute `id="elementor"` and then it points the `elementor` global object.
> 
> ## Steps to reproduce
> Try to run the code examples I have place above.
> 
> ## Environment
> == Server Environment ==
> Operating System: Linux
> Software: nginx/1.13.0
> MySQL version: 5.7.18
> PHP Version: 7.0.21
> PHP Max Input Vars: 1000
> PHP Max Post Size: 100M
> GD Installed: Yes
> Elementor Library: Connected
> 
> == WordPress Environment ==
> Version: 4.8.2
> Site URL: http://localhost:8000
> Home URL: http://localhost:8000
> WP Multisite: No
> Max Upload Size: 100 MB
> Memory limit: 40M
> Permalink Structure: /%postname%/
> Language: en-US
> Timezone: 0
> Debug Mode: Inactive
> 
> == Theme ==
> Name: Custome Made Theme
> Version: 2.0.0
> Author: Merianos Nikos
> Child Theme: No
> 
> == User ==
> Role: administrator
> WP Profile lang: en_US
> User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.79 Chrome/61.0.3163.79 Safari/537.36
> 
> == Active Plugins ==
> Elementor
> Version: 1.7.6
> Author: Elementor.com
> 
> ```
> Regenerate Thumbnails
> 	Version: 2.3.1
> 	Author: Alex Mills (Viper007Bond)
> ```
> 
> == Debug ==
> Errors:
> ReferenceError: tab_title is not defined
> at http://localhost:8000/wp-admin/post.php?post=107&action=elementor - 6:9
> 2017-09-28 10:27 +00:00
> 
> ```
> 	SyntaxError: Unexpected token )
> 		at http://localhost:8000/wp-includes/js/underscore.min.js?ver=1.8.3 - 5:15110
> 		2017-09-25 07:50 +00:00
> 
> 	SyntaxError: Invalid or unexpected token
> 		at http://localhost:8000/wp-includes/js/underscore.min.js?ver=1.8.3 - 5:15110
> 		2017-09-21 13:49 +00:00
> 		x 25 times
> ```
