### ISSUE TITLE
Problem with multiple Group_Control_Background

### ISSUE THREAD

**Issue by roythuis** [pojome/elementor#2511]
## Description

While developing a custom widget, a navigation bar to be specific, I encountered a problem while adding a second `Group_Control_Background`.

The first `Group_Control_Background` controls the background for the navigation bar itself and works perfectly fine. 

With the second `Group_Control_Background` I mean to change the background of the navigation buttons with.

The problem with the second control group is that the "Classic" and "Gradient" buttons do show up, but clicking them doesn't do anything.

Here is a part of my code, the only part that does anything with the background:

```
		$this->add_group_control(
			Group_Control_Background::get_type(),
			[
				'name' => 'background',
				'selector' => '#event-page-nav',
			]
		);

		$this->end_controls_section();

		$this->start_controls_section(
			'navitem_settings',
			[
				'label' => esc_html__( 'Buttons', 'elementor' ),
			]
		);

		$this->add_group_control(
			Group_Control_Background::get_type(),
			[
				'name' => 'background-navitems',
				'selector' => '.event-nav-item',
			]
		);
```

## Environment

https://pastebin.com/Pja0k2i3

**Comment by KingYes** [comment]
This is a bug indeed. Thanks.

**Comment by KingYes** [comment]
Change the `name` to `'background_navitems'` and it's will be work for you.

**Comment by roythuis** [comment]
@KingYes  Thank you, this solved my problem!

So the only difference is the underscore in the name. Does that mean I need to use underscores in my group control names?

**Comment by KingYes** [comment]
All your controls need to register with underscore only.
