### ISSUE TITLE
[FEATURE REQUEST] Change Tabs Layout on Mobile Devices

### ISSUE THREAD

**Issue by afroniquely** [pojome/elementor#2512]
## Changing the tab layout on mobile phones.

===== The Idea ====

Have the Elementor tabs widget show the tab titles next to each other instead of active tab title and content then next tab title underneath?
Would love instead to get a mobile layout similar to the photo. 

## Photo Example

![Image of Tabs Example](https://i.imgur.com/IZXyWwB.jpg)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a growing demand for it.

Thanks for the feedback.
