### ISSUE TITLE
[Feature Request] Border options for forms on tablet and mobile

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#2513]
It would be nice to be able to adjust the borders on tablet and mobile with the form widget. For example, if I wanted to create an opt-in form where the form field and submit button are connected, it's not really possible because it won't fit on mobile. When I then try to put the form on two rows, the borders can't be changed. 

Desktop version:
![image](https://user-images.githubusercontent.com/29379115/31023664-31b885be-a502-11e7-9a07-8d43aab62abb.png)

Mobile version:
![image](https://user-images.githubusercontent.com/29379115/31023681-3f7c3330-a502-11e7-80ae-855380652469.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see more demand for this.

Thanks for the feedback.
