### ISSUE TITLE
Body class don't match 

### ISSUE THREAD

**Issue by thorbenschmitt** [pojome/elementor#2514]
Especially problems when setting Background-Images

https://github.com/pojome/elementor/blob/364a718a6e61fc16f846e116eb51ba839065e304/includes/frontend.php#L67
https://github.com/pojome/elementor/blob/364a718a6e61fc16f846e116eb51ba839065e304/includes/css-file/post-css-file.php#L47

**Comment by KingYes** [comment]
Can you explain yourself?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
