### ISSUE TITLE
[BUG] Animated Headline colour

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#2516]
Hi, 

Animated Headline has a bug when applying a custom colour to the animated text of the headline in the following environment:

>Style Rotating

>Animation
- Typing
- Swirl
- Blinds
- Wave

Then go to **style**, **animated text** and choose a different colour to that of the headline text. It only happens on the above listed animation types, the rest are normal.

When you look at the source you will see that each letter is a span, the class applied to that span is the same as the normal header text and this is over riding the colour style of the animated text

Also, the above animation types are inheriting extra left margin/padding from somewhere as the spacing between the animated text and the rest of the headline is about 10px extra, so its a noticeable gap between the animated word and the rest of the non-animated headline. This doesn't happen on the other animation types.

**Comment by bainternet** [comment]
Thanks for the feedback, we are aware of it and we already fixed it in next release.
