### ISSUE TITLE
Background video in Elementor with youtube videos - playing on tablets has a bug

### ISSUE THREAD

**Issue by exploredesign** [pojome/elementor#2517]
Hi, 
Background video has a bug when you view a Youtube video with tablet. When the video loops the video shows an advertisement which isnt viewabe when you view the webpage with the background video on a laptop or desktop. I thought this was a Youtube account issue at first but I tried with different videos from my Youtube account and videos form random Youtube accounts but the same thing occured.

I have the most update Elementor and Generatepress theme.
Hopefully this issue can get sorted soon as the background video 
is very important for my website.

Thank you.

**Comment by bainternet** [comment]
@exploredesign 

We had some updated to the video backgrounds which should fix this in  1.8.5 
related to #2372
