### ISSUE TITLE
I receive an error message when trying to customize the page 

### ISSUE THREAD

**Issue by seengafus** [pojome/elementor#252]
I used to be able to press on customize the page ... now I receive this error message ::

## Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 12288 bytes) in /home/engsamig/public_html/wp-admin/includes/post.php on line 1741

any help ?
![226](https://cloud.githubusercontent.com/assets/20388105/16775344/d7920d04-4868-11e6-8219-40fca7bfcdb6.jpg)

**Comment by yehudah** [comment]
Hello

As I all ready told you, Here it's only to Elementor plugin from Pojo.
To get support for themes go here:
[http://support.pojo.me/forum/support/](url)

**Comment by seengafus** [comment]
ummm   ....     thanks
![09-10-37 04-31-21](https://cloud.githubusercontent.com/assets/20388105/16841190/ba51500a-49e0-11e6-8578-9d25e66ad2a2.png)

**Comment by yehudah** [comment]
The link didn't paste good you can check it now
