### ISSUE TITLE
Icon and text in the same line(section) !? For example phone icon + phone number(text)

### ISSUE THREAD

**Issue by Makedonec115** [pojome/elementor#2521]
I am asking if elementor allows two elements to be in the same line in mobile preview?
I am trying to get the same effect as on the second picture, but I cannot connect the icon with the phone number on the mobile preview as you can see on the first picture.
Any solution?
![screenshot_5](https://user-images.githubusercontent.com/32446644/31065081-b55a3bd2-a742-11e7-9bee-21c4d634c06c.png)

![screenshot_6](https://user-images.githubusercontent.com/32446644/31065137-6d68d940-a743-11e7-84d7-518d94375150.png)

**Comment by Makedonec115** [comment]
@joshmarom Your help is appreciated here

**Comment by bainternet** [comment]
that shouldn't be too hard to do.

contact our support at support@elementor.com.
