### ISSUE TITLE
Tablet Viewport is not rendering properly.

### ISSUE THREAD

**Issue by DerekBess** [pojome/elementor#2523]
Everything is 100% up-to-date and I have elementor pro as well.

This is how it looks within elementor.

![elementor-tablet](https://user-images.githubusercontent.com/4481041/31090989-8ac5db62-a777-11e7-95c3-dd5c29e7239b.jpg)

This is how it it is rendering within browser.

![elementor-tablet-render](https://user-images.githubusercontent.com/4481041/31091004-942dee6a-a777-11e7-8955-4ea64b0d1f31.jpg)

**Comment by DerekBess** [comment]
This is an issue with styles being overwritten due to hierarchy order.

.elementor-2 .elementor-element.elementor-element-ymsiolh {
    width: 40%;
}

That is not being placed in the correct order.

**Comment by black-eye** [comment]
Same here:

![obrazek](https://user-images.githubusercontent.com/5634870/31190271-f05d26d2-a93a-11e7-81c4-27e1c52a209b.png)

![obrazek](https://user-images.githubusercontent.com/5634870/31190600-d53bd19a-a93b-11e7-92df-2804d4a5f367.png)

**Comment by DerekBess** [comment]
@black-eye what I did was used important declaration. But the issue is they are not in the correct order.

**Comment by dabouncer071** [comment]
+1 here too, as @DerekBess says, looks like mobile is over riding tablet view.

**Comment by arielk** [comment]
This problem rarely occurs only in older PHP versions (<7), please update to PHP 7+ and this should work correctly.

**Comment by DerekBess** [comment]
I l like how you close when I'm on php7 wtf????

**Comment by arielk** [comment]
This is a known issue that occurs in older versions of PHP, so I closed the issue.

In order for us to look into this matter, please contact support@elementor.com, with a link to this page and complete login information to your website, and our support team will try to assist.

Thanks
