### ISSUE TITLE
Hide default Elementor templates

### ISSUE THREAD

**Issue by dabouncer071** [pojome/elementor#2528]
Is there a way or possible option for the future to disable the Predefined Templates from the anyone other than admin or of a certain level?

I think this could be an option in the settings, so users to a certain level can only see my custom templates.

Regards,
Paul.

**Comment by atMaarten** [comment]
Would be great indeed. However there already is an other topic with the same request.

**Comment by ataniker** [comment]
+1

**Comment by bainternet** [comment]
We are working on something that will allow/disallow editing and importing capabilities.

**Comment by parulgarg2** [comment]
+1
Would love to have this feature.

**Comment by IDESIGNSTUDIO** [comment]
+1 for that. 

Our customers speak German. Elementor templates library with templates in English is not what they can work with (plus it doesn't speak 'professional' about us as a web design company selling websites in German). 

I would like to be able to give an option **"Show only 'My Library' in Templates"** in the Elementor Settings for different user roles.

Or **"Hide Elementor's default Templates in Library"** for specific user roles.

Thanks.

**Comment by bainternet** [comment]
I merged this issue with  #454, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by s-hussein** [comment]
+1 . We need this feature

**Comment by lae-qguiraudie** [comment]
Hey guys,
quick solution : 
elementor/includes/template-library/manager.php
line 212 : add new filter for $templates array
![image](https://user-images.githubusercontent.com/50097352/60331378-d89eb500-9994-11e9-8b97-5d7551d7456a.png)
Now in your custom module or theme :
![image](https://user-images.githubusercontent.com/50097352/60331457-04ba3600-9995-11e9-923d-8c3a7e5c3fc8.png)

think about adding the changes again when you update (maybe they'll add this filter one day..)

**Comment by ioelada** [comment]
+1

**Comment by ioelada** [comment]
try this css rule: 

`.elementor-add-section-area-button.elementor-add-template-button {
	display: none;
}`

**Comment by artifex-media** [comment]
+1

**Comment by webinsightin** [comment]
+1

**Comment by latheeshvmv** [comment]
remove_menu_page(  'edit.php?post_type=elementor_library');

**Comment by artifex-media** [comment]
> remove_menu_page( 'edit.php?post_type=elementor_library');

Bad answer, we're talking about hiding the templates IN the library, not hiding the library menu item.

**Comment by latheeshvmv** [comment]
@artifex-media ah sorry

**Comment by via-lars** [comment]
in your theme js:

```
var elementorEditorCSS = top.document.createElement("link");
elementorEditorCSS.href = "/wp-content/themes/hello-elementor-child/elementor-editor.css";
elementorEditorCSS.rel = "stylesheet";
elementorEditorCSS.type = "text/css";
top.document.body.appendChild(elementorEditorCSS);
```

adjust for your theme folders name


in your theme folder create file `elementor-editor.css`:

```
.elementor-template-library-menu-item[data-tab="templates/blocks"],
.elementor-template-library-menu-item[data-tab="templates/pages"],
#elementor-template-library-templates[data-template-source="remote"] {
	display: none;
}
```

**Comment by YoChes** [comment]
> in your theme js:
> 
> ```
> var elementorEditorCSS = top.document.createElement("link");
> elementorEditorCSS.href = "/wp-content/themes/hello-elementor-child/elementor-editor.css";
> elementorEditorCSS.rel = "stylesheet";
> elementorEditorCSS.type = "text/css";
> top.document.body.appendChild(elementorEditorCSS);
> ```
> 
> adjust for your theme folders name
> 
> in your theme folder create file `elementor-editor.css`:
> 
> ```
> .elementor-template-library-menu-item[data-tab="templates/blocks"],
> .elementor-template-library-menu-item[data-tab="templates/pages"],
> #elementor-template-library-templates[data-template-source="remote"] {
> 	display: none;
> }
> ```

This works great. Thanks! - Any ideas how to remove the "Add template" button instead? (.elementor-add-section-area-button elementor-add-template-button)

**Comment by via-lars** [comment]
> Any ideas how to remove the "Add template" button instead? (.elementor-add-section-area-button elementor-add-template-button)

No, not the solution I currently now but if you add 

```CSS
.elementor-add-section-area-buttonXXelementor-add-template-button {
    display: none;
}
``` 
adjust `XX` to `_.` (`_` = replace by space in front!) or `.` as required

does this do it?

**Comment by kalissta** [comment]
> in your theme js:
> 
> ```
> var elementorEditorCSS = top.document.createElement("link");
> elementorEditorCSS.href = "/wp-content/themes/hello-elementor-child/elementor-editor.css";
> elementorEditorCSS.rel = "stylesheet";
> elementorEditorCSS.type = "text/css";
> top.document.body.appendChild(elementorEditorCSS);
> ```
> 
> adjust for your theme folders name
> 
> in your theme folder create file `elementor-editor.css`:
> 
> ```
> .elementor-template-library-menu-item[data-tab="templates/blocks"],
> .elementor-template-library-menu-item[data-tab="templates/pages"],
> #elementor-template-library-templates[data-template-source="remote"] {
> 	display: none;
> }
> ```

Hello,
i tested the code and it works. Thanks.

I have the following question: can this code be bound to a specific role, for example ''custom-author''.
"Administrator" should be able to see and use the templates, but "custom-author" should be restricted.

**Comment by via-lars** [comment]
the solution is based on JS and CSS. To have it depend on a role the role would have to be present inside the DOM for example as a body class "role-administrator"  or queryable from a function made available from WP. I am not aware of either being available.

**Comment by kalissta** [comment]
> the solution is based on JS and CSS. To have it depend on a role the role would have to be present inside the DOM for example as a body class "role-administrator" or queryable from a function made available from WP. I am not aware of either being available.

Thanks

**Comment by via-lars** [comment]
@hiredgeek the / a JS file which is run on the webpage in the frontend you are opening in Elementor Editor. (Elementor loads the frontend page containing all references as would be viewed from outside WP-Admin in a webbrowser.)

By default such a file does not exist. You can add it and reference it from functions.php of your active (child-) theme if your theme or your templates use the PHP wp_head method or from your themes head / footer template as a ususal HTML script element.

**Comment by hiredgeek** [comment]
@via-lars Thanks for the help. I was misinterpreting what the JS was supposed to do. I see now that the JS is only used to call the CSS.  A simpler method without JS is to use "wp_enqueue_style" in a plugin. That could also be an answer to @kalissta 's question, where the enqueue function can be conditional using "wp_get_current_user" or "current_user_can".

However, this code only hides the library and it doesn't load the custom templates tab. So the popup looks blank and users might get confused. Below is what it looks like. Any suggestions on how to use JS to select the My Templates tab by default? Thanks!

![image](https://github.com/elementor/elementor/assets/6766559/b588e7bd-5140-4b83-99a1-5cb15c6fe0ba)

**Comment by via-lars** [comment]
@hiredgeek you can look for an identifying id/class/DOM structure of the element you want to click and write code like `document.querySelector("THAT_IDENTIFYING_THING(S)").click()`. But if the code is run in the frontend JS you need to use `top.` to exit the iframe(s).
