### ISSUE TITLE
Some testimonials carousel bugs: navigation and viewing

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2529]
Hi! Making review I've created a page with some testimonials carousels and there is a problem.

I can't get a screenshot of the full editor preview. See about all what I mean in 1,3min video https://youtu.be/SqguJFy0u-8 and here is the result https://wplovers.pw/otzyvy/

Thanks!

**Comment by arielk** [comment]
Please update Elementor Pro to v1.9.3 and let me know if it solve the problem

**Comment by parfilov** [comment]
It's allright now after 1.9.3. Thank you!
