### ISSUE TITLE
Sync up version number for Elementor and Elementor Pro

### ISSUE THREAD

**Issue by gravnetic** [pojome/elementor#2532]
I'd like you to consider keeping the version of Elementor and Elementor Pro sync'd so that I know I have the correct versions installed.

Modern Tribe does this with their Events Calendar Pro plugin and I've found it to be really quite useful in quickly identifying if I have the current and correct versions of plugins installed.

**Comment by KingYes** [comment]
This is diffrent products, so each product get own version.. Thanks for your suggestion but it's relevant here.
