### ISSUE TITLE
[feature/strategy suggestion] Widget amalgamation - too many similar widgets

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#2533]
Don't get me wrong, I love Elementor, but...

In last update, there came 2 new carousels (media and testimonial), we already have got the image carousel and maybe more content specific carousels are coming. Testimonials have their's own specific widget alone.

Wouldn't it be better to have just one "section" carousel (or maybe slider) with optional content (and multiple columns)? The section content would be nice for the tabs and maybe toggle and accordion too.

Inglorious Visual Composer has this feature, so why not Elementor...? ;)

And one more: the toggle and the accordion. They are basically the same, except one can have multiple items open and the other not (if I'm getting it right, that's the only difference). Moreover, if you change your mind and you want to change this behaviour, you should start from the scratch with a new widget. It would be better to have only one widget with this option switchable.

Just my 2 cents, though.
What do you think?

**Comment by bainternet** [comment]
@black-eye 

Short answer I agree, (with most of what you wrote).
The long answer is we actually do have something in plan to allow a better grouping of widgets but we do like keeping the widgets apart because of the nature and data source of them.

thanks for the suggestion.
