### ISSUE TITLE
Loading Screen does not disappear v1.78

### ISSUE THREAD

**Issue by casperroux** [pojome/elementor#2534]
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.18 (Win32) OpenSSL/1.0.2f PHP/7.0.3
	MySQL version: 5.7.11
	PHP Version: 7.0.3
	PHP Max Input Vars: 2000
	PHP Max Post Size: 100M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://localhost
	Home URL: http://localhost
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Africa/Johannesburg
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.0.21
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
	Anywhere Elementor
		Version: 0.5
		Author: WebTechStreet

	Astra Customizer Reset
		Version: 1.0.0
		Author: Brainstorm Force

	Astra Hooks
		Version: 1.0.1
		Author: Brainstorm Force

	Astra Pro
		Version: 1.0.0-rc.6
		Author: Brainstorm Force

	BAW Login/Logout menu
		Version: 1.3.3
		Author: Juliobox

	Caldera Forms
		Version: 1.5.6.1
		Author: Caldera Labs

	Custom Fonts
		Version: 1.0.2
		Author: Brainstorm Force

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.6.5
		Author: Elementor.com

	Menu Icons
		Version: 0.10.2
		Author: Dzikri Aziz

	Nav Menu Roles
		Version: 1.8.6
		Author: Kathy Darling

	Sidebar Manager
		Version: 1.0.1
		Author: Brainstorm Force

	Smart Slider 3
		Version: 3.2.8
		Author: Nextend

	WP-Mail-SMTP
		Version: 0.10.1
		Author: WPForms

	WP HTML Mail
		Version: 2.7.1
		Author: Hannes Etzelstorfer

== Debug ==
	Errors: 
		NoTemplateError: Could not find template: "#tmpl-elementor-repeater-row"
			at http://localhost/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:17423
			2017-10-03 12:21 +00:00
			x 6 times

		TypeError: Cannot read property 'style' of undefined
			at http://localhost/wp-admin/js/editor.min.js?ver=4.8.2 - 1:694
			2017-09-27 07:33 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at http://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.6 - 2:110750
			2017-09-26 21:54 +00:00
			x 4 times

**Comment by nmasoud5** [comment]
Same issue...

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.27 (Win64) PHP/5.6.31
	MySQL version: 5.7.19
	PHP Version: 5.6.31
	PHP Max Input Vars: 2500
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://localhost/wordpress-advcec/wordpress
	Home URL: http://localhost/wordpress-advcec/wordpress
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 64M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 3
	Debug Mode: Active

== Theme ==
	Name: GeneratePress
	Version: 1.4
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.8
		Author: Elementor.com

	GP Premium
		Version: 1.4.3
		Author: Tom Usborne

	Smart Slider 3
		Version: 3.2.8
		Author: Nextend

	WP Log Viewer
		Version: 1.2.1
		Author: Maxwell Berkel


== Debug ==
	Errors: 
		NoTemplateError: Could not find template: "#tmpl-elementor-repeater-row"
			at http://localhost/wordpress-advcec/wordpress/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:17423
			2017-10-03 12:53 +00:00
			x 25 times

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 1:1
			2017-10-03 08:42 +00:00
			x 62 times

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 7:2
			2017-10-03 06:23 +00:00
			x 4 times

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 3:30
			2017-10-03 06:21 +00:00

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 7:2
			2017-10-03 06:21 +00:00

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 6:2
			2017-10-03 06:21 +00:00

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 3:30
			2017-10-03 06:18 +00:00

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 6:2
			2017-10-03 06:18 +00:00

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 3:30
			2017-10-03 06:17 +00:00

		SyntaxError: Unexpected token <
			at http://localhost/wordpress-advcec/wordpress/wp-admin/post.php?post=202&action=elementor - 6:2
			2017-10-03 06:16 +00:00
			x 3 times

**Comment by Lennuj420** [comment]
i would like to tell you guys, if you are trying elementor in a localhost, dont bother its not working. its an old problem. but if you have a live server. everything should fine. :)

**Comment by casperroux** [comment]
v1.7.6 is working fine within my localhost

**Comment by nmasoud5** [comment]
Hi Lennuj...

Was working perfectly fine on a localhost till update 1.7.7... Currently rolled back my installation to v1.7.6 and everything is working fine...

**Comment by norewp** [comment]
Elementor works perfectly fine on localhost and has been for a long time.

Set your PHP version to 7.x.x and bump your memory limit to 256M - also set your permalinks to /%postname%/ - don't forget to flash your browser cache and test again

**Comment by nmasoud5** [comment]
Thanks norewp... Will try in a bit and get back to you guys on the results...

Any specific reason for the permalink change (already had it set to postname but want to know the reason if any)...

**Comment by norewp** [comment]
Different permalinks have different rewrite rules set in the htaccess - for me having at /%postname%/ on all my sites (live or local) has never given me any issues. So the advise here is just incase the rewrite in combination with other factors is adding to the problem maybe?

**Comment by casperroux** [comment]
re-saving permalinks, did the trick
Working Now ;)
Thanks

**Comment by nmasoud5** [comment]
Good to know Casper... Was your PHP version already at 7+?

**Comment by casperroux** [comment]
Yes, v7.0.3

**Comment by norewp** [comment]
Also v1.7.9 has been released that aims to fix the Wondows loading issue

**Comment by casperroux** [comment]
I will update as soon as it is available, and let you know

**Comment by nmasoud5** [comment]
Just updated to v1.7.9 and all works but I do believe that was due to the permalink update I did earlier per norewp's suggestion so thank you norewp

Point of note: I left my PHP version at 5.6.31 to see if going to 7.x.x was also needed - turns out it isn't needed so this issue seems permalink related as confirmed by the fact that Casper was already at 7.x.x...

Thanks gents for the support and feedback... Happily now on the latest version of Elementor...

**Comment by casperroux** [comment]
1.7.9 is good

**Comment by norewp** [comment]
Cool @casperroux - could you mark the thread as resolved and close it please :)

**Comment by casperroux** [comment]
resolved... Thanks
