### ISSUE TITLE
Fadein animation breaks editor

### ISSUE THREAD

**Issue by dave-hiddendepth** [pojome/elementor#2543]
## Description

Once an element has an animation on it the page will freeze when I select Advanced for that elemet.

## Environment

TypeError: Cannot read property 'fadeIn' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:139887
2017-10-04 03:50 +00:00

TypeError: Cannot read property 'data' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:140089
2017-10-04 03:49 +00:00
x 2 times

TypeError: Cannot read property 'fadeIn' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:139887
2017-10-04 03:49 +00:00
x 7 times

TypeError: Cannot read property 'data' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:140089
2017-10-04 03:31 +00:00

TypeError: Cannot read property 'fadeIn' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:139887
2017-10-04 03:30 +00:00
x 2 times

TypeError: Cannot read property 'data' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:140089
2017-10-04 00:16 +00:00

TypeError: Cannot read property 'fadeIn' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:139887
2017-10-04 00:16 +00:00
x 2 times

TypeError: Cannot read property 'data' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:140089
2017-10-04 00:14 +00:00
x 2 times

TypeError: Cannot read property 'fadeIn' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:139887
2017-10-04 00:13 +00:00
x 2 times

TypeError: Cannot read property 'data' of undefined
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.10 - 2:140089
2017-10-04 00:09 +00:00

**Comment by ibes** [comment]
Same as #2541

**Comment by dave-hiddendepth** [comment]
Latest update seems to have fixed this.
