### ISSUE TITLE
[Bug/Request] Color Picker

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#2548]
When I'm using the color picker, as soon as I enter 3 digits it super quickly converts it to 6-digits. This makes it extremely hard to enter any colors manually.
![cant-enter-colors](https://user-images.githubusercontent.com/29379115/31183747-1fae35be-a8ed-11e7-9ab6-a110ab78a35f.gif)

When I choose my color picker settings, the order does not match the order seen in the actual color picker. It seems to change based on some algorithm, maybe popularity? This may not seem like a big deal, but it's super difficult when you're dealing with colors that are very similar to each other (with gradients for example). It would be more helpful if the colors were displayed in the same order I chose in the color picker settings.

Color picker settings:
![color-picker-global](https://user-images.githubusercontent.com/29379115/31183971-cb4543f4-a8ed-11e7-986f-1e7287cff1b6.png)
Actual color picker:
![color-picker-wrong-order](https://user-images.githubusercontent.com/29379115/31183977-cf63fd7c-a8ed-11e7-9732-eb6cfa09bf07.png)

Picky point, but when editing a page, if I stretch the sidebar and then click on the color picker, the color picker jumps to the left side of the screen. Seems like it would be better if it was right justified.
![color-picker-left-justified](https://user-images.githubusercontent.com/29379115/31184471-17be16d8-a8ef-11e7-83cc-070f3a5103f4.gif)

**Comment by arielk** [comment]
The color picker in Elementor is the native WordPress color picker ([Iris](https://github.com/Automattic/Iris)), so it's a little complicated to solve it..

About the extended panel, I just fixed it for the next version (https://github.com/arielk/elementor/commit/bf05635c19225e7458b2f871bbe6d6858ca0b43e).

Thank you for pointing out those issues.

**Comment by nepa** [comment]
@arielk: What about the order of the custom colors defined in the Elementor settings (issue #2 mentioned by @avermat)? Today, I also stumbled upon the fact, that the actual order of the colors does not match my initial order in the settings.

I arranged the colors by priority for my design, but ended up with all items being mixed wildly.

This is not very beneficial for my workflow, even though, I appreciate that I can define custom colors in the first place.

**Comment by cstibi** [comment]
I have sent my question about random order of custom colors to Elementor support.
They answered a link to this topic. I can't find a solution for it :((

I think, this is not a feature request! Elementor has a feature, but working bad.

Formerly it was working fine. Later it became random: sometimes the color order was shown in the right order, and next click in random order.
And nowadays I can't bring the right order :((

This Github post was created in october of 2017. Where is the solution?
The proper functioning of existing features is at least as important as the introduction of new Elementor features.

Waiting for a solution in next udates!
Best regards 
Tibor
