### ISSUE TITLE
WordPress Autocomplete for URL Control

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#255]
Hey

In the existing link box in the WordPress content creation one can begin writing content and the page or post will show up in a drop down so one can easily link to it. I would like to also extend this to also categories. As in begin writing cat and the categories show up by post then other types of categories below.

![screen shot 2016-07-13 at 10 38 09](https://cloud.githubusercontent.com/assets/5323259/16797029/ebeda948-48e5-11e6-837c-831ea222a300.png)

In a link one knows the name of the post and begins to write the name and in the drop down one can select it. 

Used only in the Elementor Text Editor
![screen shot 2016-07-13 at 10 43 18](https://cloud.githubusercontent.com/assets/5323259/16797209/c3ae2d8a-48e6-11e6-8fde-4ede27d5d69f.png)

Go through all the places where you add links for instance Heading link, Image link, Button link, Image Box link, etc. Add the WordPress automatic drop down list when the user begins typing.

**Comment by CiblesDEV** [comment]
![screenshot-09-19-16-08h49am](https://cloud.githubusercontent.com/assets/22288446/18624401/b4718a88-7e47-11e6-84e7-870193d97291.JPG)

Not in button, etc...

**Comment by arielk** [comment]
It's definitely an interesting feature, I would consider also add more capabilities through the Settings button, such as `rel="nofollow"`

**Comment by sebschaeffer** [comment]
Is there an update on the rel="nofollow" option? This is not only relevant for the normal link functionality in the text editor (where you can easily add it via the text view). It is WAY more important on images and buttons.

To give you some background on this feature - for everyone doing SEO nofollow is essential to control flow of linkjuice. Right now my site is leaking link juice since button and image links can't be nofollowed. This is a MAJOR issue not just for SEOs but for companies in general who rely on SEO to get traffic. Especially affiliate links need to be nofollowed according to Google which just is not possible with Elementor at this point.

So at this point it is not possible to build a page that includes affiliate links which does not violate Googles best practices.

**Comment by sebschaeffer** [comment]
@arielk Should this ticket be split up since "nofollow" also includes buttons and images and not just hyperlinks in the text editor?

**Comment by carasmo** [comment]
+1 nofollow and link picker

**Comment by Twisterking** [comment]
As mentioned in #1440 this feature is definitely needed for pretty much ALL "linking possibilities" or where the user can enter a URL somewhere. This is such a common task for e.g. buttons that frankly speaking this is currently a dealbreaker for me, as I can not expect my customers to be able to link to other pages (if they want to make changes) by finding out the proper URL themselves. I tried that and normal users can't do that.

**Comment by carasmo** [comment]
Any news on the link picker ETA? Thanks!

**Comment by KingYes** [comment]
No for now..

**Comment by Twisterking** [comment]
Guys ... just saying ... this is such a core feature that you WILL lose many potential customers due to that, just saying. Please fix this asap! just my 2 cents ...

**Comment by ianstudio** [comment]
+1 @Twisterking I was rather disturbed when I realized this core feature indeed was not present in Elementor. I also feel a few "core features" are missing and much more important than "text shadows etc.. Don't get lost in gimmicks please ;0)

**Comment by enviedbymost** [comment]
Damn, I'm surprised Elementor doesn't have this.

We neeeed this. As people have previously mentioned, it's an essential feature to have.

**Comment by CiblesDEV** [comment]
We neeed this too ! Go go elementor team ! ;)

**Comment by arielk** [comment]
Related issue (Just for the developer team): https://github.com/pojome/elementor/issues/1071

**Comment by dabouncer071** [comment]
HI All,

I certainly can continue the conversation here.

Is there any news or movement on this one, i agree with comments above, this option isn't a gimmick it what us customers would like.

**Comment by black-eye** [comment]
+1 for me too. It's hard to explain to the customers, that this core feature is missing... I find this feature quite essential!

**Comment by enviedbymost** [comment]
Is this still a no? :( @KingYes

**Comment by grrog** [comment]
Is there news about this?

**Comment by denishacquin** [comment]
This is a dealbreaker... I was very disappointed when I noticed that feature is not implemented. Nobody wants to copy URLS manually and I can't expect a customer to do that. This is already in core wordpress and in every page builder out there but elementor. This is very serious and should be top 1 priority IMO, especially when you see non-essential features are added.

**Comment by CiblesDEV** [comment]
When doing a training to the client, it is not professional to tell him to copy the url link to the pdf file! It is urgent to correct this problem!
-----------------------------------------------------------
Quand on fait une formation au client, ce n'est pas professionnel de lui dire de faire un copier coller de l'url vers le fichier pdf ! Ca deviens urgent de corriger ce problème !

**Comment by denishacquin** [comment]
So I saw on another issue that you said you were working on it for the next versions and it was back in May.

I cannot emphasize enough how important this feature is. I am an elementor pro customer and I want to push elementor pro to my company and clients but this is a simple yet huge downside.

Please, this needs your attention ASAP in my opinion.

**Comment by htaaning** [comment]
This is a real dealbreaker for me. My customers can´t figure out url's in that way, and it is way faster just searching for the posts or pages. When this feature is implemented, i´ll go and buy the Elementor Pro. Hope it will be soon, as im really looking forward to moving away from Visual Composer (WPBakery Composer) on upcoming projects.

**Comment by ianstudio** [comment]
@htaaning I'm afraid the Elementor team is deaf on this one (and a few other points).. am considering moving TO Visual Composer Website Builder (their new offer.. not Page Builder).

**Comment by denishacquin** [comment]
It's been a year and a half since this issue has been opened. You guys are going to lose existing and potential customers if you don't implement this...

**Comment by bainternet** [comment]
We are working on something, no ETA yet.

**Comment by htaaning** [comment]
Sounds good. Since this issue has been open for more than a year, are we talking week, months or years? ;-)

**Comment by Bannerman** [comment]
Any update on this?

**Comment by mountaineer20** [comment]
Just wondering when this feature [existing content link selection] will be added? This is something basic that I expected out of the box when I purchased Elementor.

**Comment by bodhi1970** [comment]
Version 2.0 and this is still not implemented in all places where one can add a link.

**Comment by CiblesDEV** [comment]
Hi ! Why i can’t select id of post/media, more stable than url who can change !


Cordialement,

Arnaud Colléter
Développeur Web

[Cibles & Stratégies]<http://www.cibles-strategies.com/>



www.cibles-strategies.com<http://www.cibles-strategies.com/>

Suivez-nous sur

[Facebook]<https://www.facebook.com/ciblesetstrategies>



SAINT-BRIEUC
24 bis, Bd Charner
22000 Saint-Brieuc
T 02 96 68 43 43
F 02 96 61 96 92

NANTES
1 rue Du Guesclin
BP 61905
44019 Nantes Cedex




De : bodhi1970 [mailto:notifications@github.com]
Envoyé : vendredi 13 avril 2018 13:46
À : pojome/elementor <elementor@noreply.github.com>
Cc : Arnaud COLLETER <A.COLLETER@cibles-strategies.com>; Comment <comment@noreply.github.com>
Objet : Re: [pojome/elementor] WordPress Autocomplete for URL Control (#255)


Version 2.0 and this is still not implemented in all places where one can add a link.

**Comment by tristanleboss** [comment]
+1

**Comment by denishacquin** [comment]
Seriously... I am paying for Pro and pushing Elementor to my clients but this basic feature missing is a DEAL BREAKER. Please fix this ASAP

**Comment by CiblesDEV** [comment]
Yes, please fix this ASAP too ! It is essential !


Cordialement,

Arnaud Colléter
Développeur Web

[Cibles & Stratégies]<http://www.cibles-strategies.com/>



www.cibles-strategies.com<http://www.cibles-strategies.com/>

Suivez-nous sur

[Facebook]<https://www.facebook.com/ciblesetstrategies>



SAINT-BRIEUC
24 bis, Bd Charner
22000 Saint-Brieuc
T 02 96 68 43 43
F 02 96 61 96 92

NANTES
1 rue Du Guesclin
BP 61905
44019 Nantes Cedex




De : denishacquin [mailto:notifications@github.com]
Envoyé : dimanche 22 avril 2018 23:51
À : pojome/elementor <elementor@noreply.github.com>
Cc : Arnaud COLLETER <A.COLLETER@cibles-strategies.com>; Comment <comment@noreply.github.com>
Objet : Re: [pojome/elementor] WordPress Autocomplete for URL Control (#255)


Seriously... I am paying for Pro and pushing Elementor to my clients but this basic feature missing is a DEAL BREAKER. Please fix this ASAP

**Comment by andrewmaney** [comment]
This feature was being worked on (according to @arielk ) 12 months ago, to be released in upcoming versions. Looks like the wheels have fallen off the wagon.... 

![screen shot 2018-05-07 at 1 31 32 pm](https://user-images.githubusercontent.com/7564708/39683883-6742bf96-51fb-11e8-9fc9-919c4e3e1050.png)

**Comment by tristanleboss** [comment]
Yup. I think, since version 2, they have a timeline of things to do and do nothing else outside of it (they stick to their timeline).

Using GitHub issues to track suggestion seems to be not well suited too: they should do something like Dell IdeaStorm. Most users will never come here because it's way to geeky and so, can't embrace an idea.

**Comment by themedleb** [comment]
+1

**Comment by bainternet** [comment]
@richcb7 thanks for your opinion.

**Comment by breath-ee** [comment]
+1, for this request. :)

Other page builders have this feature for linking. I know when I first used the button widget I expected the input field to drop a list of posts/page or filter search as I typed, not knowing I needed to have a copy & paste workflow in order to create the link.

**Comment by grrog** [comment]
Please, do it :)

**Comment by mepfaff** [comment]
+1
I don't like being negative, but wow. I agree this is a really basic, essential feature, and I wouldn't have chosen Elementor at all if I'd known this wasn't included. :/

**Comment by black-eye** [comment]
Well, today it's exactly 2 years from opening this issue. Happy birthday Autocomplete!

C'mon- you have built Elementor Themer, you can design Archive page or Single Post Template (where you can even select a post or page to preview actual data, which is quite close to the function we want here), but after 2 years of developing you are unable to add a core WP functionality? :-(

Personally, I don't get this - you could gain so much by doing so little - so many happy people, so little work to be done... Or am I missing something, is there some other technical obstacle?

**Comment by ianstudio** [comment]
@benpines Seriously !!!!! Get you act together, this is not a cosmetic feature we're talking about here, @black-eye is right this situation makes no sense whatsoever.
If visualcomposer.io can do it why can't you ?!? This is insane.
<img width="398" alt="capto_3" src="https://user-images.githubusercontent.com/935706/42712666-c4fe651a-86ec-11e8-87a1-cf7f3b5eca8e.png">

**Comment by CiblesDEV** [comment]
It must be develop ! it not professional to explain to customer a copy paste url !

**Comment by andrewmaney** [comment]
Happy 2'nd Birthday missing autocomplete URL feature!

![2cfa9cde9f295d8eb72eb010bcea959e--smarties-cake-nd-birthday-cakes](https://user-images.githubusercontent.com/7564708/42791372-aa008da0-89b3-11e8-833e-663a311ece29.jpg)

**Comment by grrog** [comment]
It's a joke? This story could make a good movie…
& Happy Birthday Mr Basic AutoComplete !
See you next year ;)
Regards

**Comment by CiblesDEV** [comment]
Hi !
I make yesterday a code to have alternative of missing url and IT WORKS !

But i have a problem for repeater, i think it dont have hook for repeater
Exemple : il call like this :
add_action('elementor/element/icon-list/section_icon/before_section_end', 'custom_selectcontent', 10, 2);
=> works but on in element
how to have it on each element, like this ?
add_action('elementor/element/icon-list/section_icon/repeater/before_section_end', 'custom_selectcontent', 10, 2);
add_action('elementor/element/icon-list/section_icon/repeaters/before_section_end', 'custom_selectcontent', 10, 2);
I have nothing...

An idea ?

**Comment by arielk** [comment]
In honor of the 2'nd birthday of this feature request, we are pleased to launch the AutoComplete URL for the next version 2.2 :)

Thanks everyone for the feedback.

Happy Birthday!

**Comment by grrog** [comment]
Luxury feature! Congrats :D

**Comment by ianstudio** [comment]
F I N A L L Y !!!!!!

**Comment by markhagemann** [comment]
@arielk when do you roughly see 2.2.0 being released? If it's more than a month away is there any chance of it being included in a minor release?

**Comment by arielk** [comment]
@markhagemann I hope it will be released in beta in a week or two.

**Comment by olabre** [comment]
good news, is there any download available?

**Comment by markhagemann** [comment]
@arielk this week then :D?

**Comment by olabre** [comment]
excellent, good news, thanks

**Comment by olabre** [comment]
Hi, linking works now very good, there is only a problem left if you work with WPML. If I have tanslated a page and want to modify the link (e.g. English and German language) I only get English pages in the selection box when editing the German page. Is there any solution?

**Comment by tristanleboss** [comment]
@olabre For better visibility, you should open a new issue.

**Comment by hostmate** [comment]
can we get this working for other file types like pdf and doc in the media library folders

**Comment by ARAGATO** [comment]
> can we get this working for other file types like pdf and doc in the media library folders

Yes, that is what I was looking for in the first place. A direct link to a file. Right now it is somewhat possible via the internal url,but only with a step inbetween and an artifical dl page. A direct link to a file would be much nicer.

**Comment by apolinario** [comment]
> In honor of the 2'nd birthday of this feature request, we are pleased to launch the AutoComplete URL for the next version 2.2 :)
> 
> ![](https://user-images.githubusercontent.com/1778512/42959532-d6f25084-8b91-11e8-8447-32cf3b9f9540.gif)
> 
> Thanks everyone for the feedback.
> 
> Happy Birthday!

This is still not working for this basic "Button" element

**Comment by sslakd** [comment]
Hi, just wonder, is it relative link or absolute link ? After I select the page from the list, it show up an address that look a lot like absolute link to me.

**Comment by Merlin-the-Warlock** [comment]
> Hi, just wonder, is it relative link or absolute link ? After I select the page from the list, it show up an address that look a lot like absolute link to me.

When you use autofill it automatically populates the absolute link. You can **easily fix** this by deleting your domain name (i.e. delete everything other than the slug). 

For example, if the full link is https://elementor.com/link-to-this-page. 

Then after autofill delete the first part to leave only: /link-to-this-page.

NOTE: I don't think this will work if you're linking to a subdomain because you would be deleting the subdomain info.

Hope this helps!
