### ISSUE TITLE
[Feature Request] Blog Post Progress Bar

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2551]
Something that's becoming increasingly more popular is having a progress bar at the top of the page to indicate how far you've 'progressed' through the post.

I suspect it has something to do with a recent psychology study called 'The Endowed Progress Effect'.

https://medium.com/@davidteodorescu/design-perfect-ux-tasks-the-endowed-progress-effect-7461ca20076c

**Comment by bainternet** [comment]
@enviedbymost 
Thanks for the suggestion, but it feel more of a plugin/extension territory then something that should be native to Elementor.

So currently this feature is not supported, but we will look in to it in the future.

Thanks for the feedback.
