### ISSUE TITLE
Full screen background video does not resize correctly!

### ISSUE THREAD

**Issue by exploredesign** [pojome/elementor#2552]
Full Screen Video is not displaying correctly. This issue is related to an issue below which was posted back in May - with the same title. The person didnt get back so I am posting this as this issue is still not sorted 
https://github.com/pojome/elementor/issues/1737

When having a full width background video playing from an mp4 file playing in a section using Elementor, It displays correctly sometimes put other times the video is only stretching across 2/3 of the width of the section. This is an intermittent problem and I hope the Elementor team can fix this soon because I cant move forward with my website until its fixed.

This is most noticeable when you have a tablet where you turn the orientation from horizontal to vertical and vice versa. My tablet has a resolution of 1280px x 800px screen, when it horizontal its displaying desktop and vertical its conforms to tablet.

I am using the latest Elementor an generatepress theme. So Please sort this issue soon.

Thank you

**Comment by nolanmanning703** [comment]
I'd like to add to this issue that my video background is not being centered. You can see the problem live on [my site](https://studycrafter.com/). If the window is scaled to anything lower than 1920px wide, the video is not centered.

**Comment by exploredesign** [comment]
Hello Nolan, I have had a look at your website and although the issue is probably the same one I reported, its not exactly reacting the same way. I have noticed that the problem I encountered  is more likely to happen when you have a complicated page with lots of elements. I didn't have an issue when I was using the animated video background on very simple pages. 
Thanks for your input and hopefully Elementor sort this soon.

**Comment by Meg-Lynn** [comment]
Hi nolanmanning703!  I was wondering if you were able to figure this issue out?  I just checked your site and it looked like the clouds video was sized correctly.  Do you have any suggestions as I am having the same issue with the video not being centered or full width.  

Thanks!

**Comment by bainternet** [comment]
As far as we know it was fixed in 1.5.3
If anyone still has issues with this, please feel free to reopen.

**Comment by Gidde-Abhishek** [comment]
The issue still remains. Elementor 3.5.2.
