### ISSUE TITLE
[Feature Request] Countdown Ever Green Clock

### ISSUE THREAD

**Issue by tdamary** [pojome/elementor#2555]
Hey,

For internet marketers it would be awesome to have an EverGreen countdown clock.
Based on cookies / new from the begining, you can set a timer starting from 43 mins for examples everytime.

Hope it something you may include in your developments.

Thanks,
Tal

**Comment by atMaarten** [comment]
Would be a great marketing feature indeed!

**Comment by silvioghedin** [comment]
+1 

would be awesome

**Comment by GostkaDesign** [comment]
I think its a complex feature but o think you can mix a external service with elementor like
https://deadlinefunnel.com/wordpress
(just search on web i've not try this service)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
