### ISSUE TITLE
[FEATURE REQUEST] Mailster integration

### ISSUE THREAD

**Issue by thefurmanuk** [pojome/elementor#2556]
Mailster is one of the most popular mail plugins, would be great to have it integrated with Elementor forms.

**Comment by themedleb** [comment]
Yes please.

**Comment by c6410** [comment]
support this.  yes too.

**Comment by maxwellhibbert** [comment]
yes yes

**Comment by bainternet** [comment]
I merged this issue with  #2397, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Poltavtcev** [comment]
What about it? )

**Comment by zaehlpixel** [comment]
Any news? We need that, too

**Comment by alican532** [comment]
???

**Comment by maxwellhibbert** [comment]
@alican532 did you read this thread?

**Comment by alican532** [comment]
@maxwellhibbert Yes I have read. I wondered if there was any improvement. So I wanted to send a question mark.

**Comment by maxwellhibbert** [comment]
@alican532 follow the link to the merged issue and find Mailster in the list.

**Comment by spac-em** [comment]
hi , i am confused with the code as well.
which part of the code need to be replaced from mailster ? can someone point the "term" please. TIA ! 

`add_action( 'elementor_pro/forms/new_record', function( $record ) {
	if ( ! function_exists( 'mailster' ) ){
		// Mailster missing!!!
		return;
	}
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );

	// Ref: https://kb.mailster.co/mailster-for-developers/
	$fields = [
		'email' => $submmited_fields['ID_OF_YOUR_EMAIL_FIELD']['value'],
		'firstname' => $submmited_fields['ID_OF_FIRSTNAME_FIELD']['value'],
		'lastname' => $submmited_fields['ID_OF_LASTNAME_FIELD']['value'],
		'status' => 1, //1 = subscribed (default) , 0 = pending, 2 = unsubscribed, 3 = hardbounced
		'custom-field' => 'Custom Value',
	];
	// Add subscriber
	$subscriber_id = mailster( 'subscribers' )->add( $fields );
	if ( ! is_wp_error( $subscriber_id ) ) {
		$lists = [1,23]; // Array of list ids
		$success = mailster( 'subscribers' )->assign_lists( $subscriber_id, $lists);
	}
});`

**Comment by alican532** [comment]
@maxwellhibbert , @spac-em Thank you very much

**Comment by maxwellhibbert** [comment]
@spac-em You need to add the code to  functions.php in your theme. I'd suggest using the Snippets plugin to do this, rather than edit a theme direct or mess around with a child theme.

Snippets plugin: https://wordpress.org/plugins/code-snippets/

Code to add (make sure your field names match up etc):
```php
add_action( 'elementor_pro/forms/new_record', function( $record ) {
	if ( ! function_exists( 'mailster' ) ){
		// Mailster missing!!!
		return;
	}
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'mailster_sub_general' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );

	// Ref: https://kb.mailster.co/mailster-for-developers/
	$fields = [
		'email' => $submmited_fields['email']['value'],
		'firstname' => $submmited_fields['first_name']['value'],
		'lastname' => $submmited_fields['last_name']['value'],
		'status' => 1, //1 = subscribed (default) , 0 = pending, 2 = unsubscribed, 3 = hardbounced
	];
	// Add subscriber
	$subscriber_id = mailster( 'subscribers' )->add( $fields );
	if ( ! is_wp_error( $subscriber_id ) ) {
		$lists = [1]; // Array of list ids
		$success = mailster( 'subscribers' )->assign_lists( $subscriber_id, $lists);
	}
});
```

**Comment by segunolamidegitup** [comment]
@maxwellhibbert this is not working for me.
Have set up the script above but Once I enabled mailster to send email as deafult sending mial rather than wordpress php_mail()
 used by elementor, elementor would generate parse error  .

Any help.
![image](https://user-images.githubusercontent.com/20296468/74105462-39fb4900-4b5e-11ea-9b3c-e0b75de883d8.png)

![image](https://user-images.githubusercontent.com/20296468/74105480-631bd980-4b5e-11ea-96f3-30a6fb9fafc2.png)

**Comment by maxwellhibbert** [comment]
@segunolamidegitup check the logs? Check the form I’d and fields match?

**Comment by segunolamidegitup** [comment]
The form name and form fields matched the form field in the above script.

What I noticed is once we enabled mailster as default outgoing mail, elementor form wont work as if you try to send mail elementor form will generate **"parse error"**. 

**My question is?** How can we enable mailster for outgoing wordpress mail https://user-images.githubusercontent.com/20296468/74105480-631bd980-4b5e-11ea-96f3-30a6fb9fafc2.png at the same time elementor form should also work.

or any solution ?


![image](https://user-images.githubusercontent.com/20296468/74131064-d582cd00-4be3-11ea-83dd-a4facbdd2cda.png)

![image](https://user-images.githubusercontent.com/20296468/74130256-f5b18c80-4be1-11ea-8ea7-36b63ac6a545.png)
![image](https://user-images.githubusercontent.com/20296468/74130287-0530d580-4be2-11ea-8f95-32354455da64.png)
![image](https://user-images.githubusercontent.com/20296468/74130314-11b52e00-4be2-11ea-8d94-2d2c1ce53676.png)

**Comment by segunolamidegitup** [comment]
@spac-em  How were you able to integrate this solution successful from your side?

**Comment by spac-em** [comment]
> @spac-em How were you able to integrate this solution successful from your side?

Hi @segunolamidegitup  no i did not try. i am using mailpoet now. But i will need this soon.

can  @maxwellhibbert  assist on this please ,

**Comment by segunolamidegitup** [comment]
@spac-em I found a custom way around it. But is not the official way. creating my own PHP page that handles the posting to the mailster directly by attaching that page link to elementor form.

**Comment by maxwellhibbert** [comment]
@segunolamidegitup By the look of your screenshots, you've edited the property 'form_name' that's being referenced, instead of the string in the conditional below:

<img width="600" alt="snippet" src="https://user-images.githubusercontent.com/2948524/75203650-d0687500-57c2-11ea-89a5-3e78dcb68cab.png">

<img width="296" alt="form" src="https://user-images.githubusercontent.com/2948524/75203646-ce061b00-57c2-11ea-8e26-8cccc28c6461.png">

**Comment by spac-em** [comment]
thank you @maxwellhibbert  . will test this. i hope it works.
any example for checkbox list custom field  ?

**Comment by spac-em** [comment]
> @spac-em I found a custom way around it. But is not the official way. creating my own PHP page that handles the posting to the mailster directly by attaching that page link to elementor form.

can you share this solution as well ? thank you .

**Comment by spac-em** [comment]
i notice that elementor form id only accept "_", while mailsters field is has "-" only, so it get converted into "_" . anyone have the same issue ?
