### ISSUE TITLE
Nav Menu submenus work in Elementor Editor, but don't, when the page is rendered.

### ISSUE THREAD

**Issue by chemocool** [pojome/elementor#2557]
## Description

Can't View/Use the Submenu when Nav Menu is rendered in a Page

## Steps to reproduce

1. I create a menu with submenu in Wordpress.

2. In a page Elementor Editor, i place a Nav Menu Widget.

3. The Widget works in the Editor.

4. I Save the page.

5. Refresh the page (out of the editor), Only First Level Menu Show (without the Submenu icons)

**Comment by chemocool** [comment]
Code 18 sorry...

**Comment by p0loloop** [comment]
same problem. whats the solution for this? Elementor ver. 2.0.16 pro ver. 2.0.11

**Comment by chemocool** [comment]
It was a problem on my side, CSS rules that were overriding Elementor css.

Try removing any custom css (back it up) and try again, should work.
