### ISSUE TITLE
[Feature Request] Submenu width control for Nav Menu (Pro)

### ISSUE THREAD

**Issue by chemocool** [pojome/elementor#2558]
Submenu items with long name overflow the width of submenu.

Would it be possible to control the width of the submenu with an option to allow for wordwrap (long text on 2 lines) or 1 line with ellipse.#

Thanks

**Comment by arielk** [comment]
Can you share with us a link to this page with the bug?

**Comment by chemocool** [comment]
nvm, it's my mistake
