### ISSUE TITLE
Text Widget does not respond to Section / Column Content Position

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#2559]
Elementor 1.7.11 (also tried 1.7.4 and 1.4.7 with same results)

Steps to replicate:
- add a Section
- add a Text Widget to it
- set the Section Content Position to Middle or Bottom
- no change
- set the Column Content Position to Middle or Bottom
- no change

Cheers!
Lyle

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.27 (Win64) OpenSSL/1.0.2l PHP/7.1.7
	MySQL version: 5.7.19
	PHP Version: 7.1.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://localhost/wptest1
	Home URL: http://localhost/wptest1
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 1.4
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.11
		Author: Elementor.com

== Debug ==
	Errors: 
		TypeError: Cannot read property 'size' of undefined
			at http://192.168.0.98/wptest1/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=1.9.2 - 2:9865
			2017-10-02 17:17 +00:00
			x 2 times

**Comment by arielk** [comment]
Can you please share with us a link to the page with this situation?

**Comment by GostkaDesign** [comment]
It's not a bug it's cause by the minium height's value who's not set

**Comment by GostkaDesign** [comment]
in fact it's cause by the <p> margin that's all

**Comment by vantageventures** [comment]
Hello I have the same problem. Mine doesn't align to top, it's defaulted to the middle. You may see the problem here - http://opusstrategic.business if you look below the Contact Us section. Thanks.
