### ISSUE TITLE
Define a Post page template

### ISSUE THREAD

**Issue by Nat-Faeeria** [pojome/elementor#256]
I love more and more working with Elementor ! It's amazing ^^

Still, I was asking myself how I could design a page to display a post, and not have to redo the page building for each post. Is there such a feature in Elementor ?

**Comment by cobicarmel** [comment]
Hi Nat-Faeeria, thank you for your feedback.

As you can see [here](https://github.com/pojome/elementor/pull/132), we are working for this feature right now. It will be released soon.

**Comment by paaljoachim** [comment]
That is great! The issue I created extends what Nat-Faeeria mentions.

**Comment by arielk** [comment]
Dupe #132
