### ISSUE TITLE
Hide Control

### ISSUE THREAD

**Issue by dave-hiddendepth** [pojome/elementor#2560]
I'm looking into creating a plugin so I can enable a client mode that prevents clients from editing most styling features within Elementor, so they don't break things. 

Using _remove_control_ I can remove sections like _text_color_ but when I do this it disables that feature so the colour reverts to what is in my standard stylesheet.

I want to remove/hide a control but keep whatever value (colour, font size, etc.) I have set for that control. Is this possible?

**Comment by arielk** [comment]
I merged this issue with another issue #1314 in the same subject so we could deal with it more efficiently. 

Thanks for your feedback!
