### ISSUE TITLE
Form Redirect URL with Form Values

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#2564]
It would be nice to create a thank you page with the data from the form http://www.mywebsite.com/thank-you/[name].
Also we can use the form widget for the search form: http://www.mywebsite.com/s/[searchword]
The posibilities are endless.

**Comment by joffcrabtree** [comment]
+1 - THIS and I can FINALLY get rid of CF7. Just the ability to transcode field shortcodes into the URL redirection and we're good to go...

**Comment by andjules** [comment]
+1 - I know it seems old-fashioned, but there are still use cases to **actually _submit_ forms (incl redirecting browser) to a non-ajax POST url**. Shouldn't have to write a plugin to process a webhook response as a complex-workaround.

**Comment by pingram3541** [comment]
+1

**Comment by bainternet** [comment]
@pingram3541 @dudaster 

This should be out with Elementor Pro 2.2.0 but untill then you can try this snippet:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $ajax_handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	// Set the redirect URL with the form fields shortcodes
	$redirect_url = 'https://www.google.com/search?q=[field id="name"]';

	// Convert fields shortcodes to form values
	$redirect_to = $record->replace_setting_shortcodes( $redirect_url );

	// Set redirect action
	$ajax_handler->add_response_data( 'redirect_url', $redirect_to );
}, 10, 2);
```

**Comment by Vexander** [comment]
+1

**Comment by aag-hyau** [comment]
would be even better if we can POST to a URL while transferring the URL query parameters
form page: example.com/form/?query1=value1&query2=value2
post page: example.com/thank-you/?query1=value1&query2=value2

**Comment by bainternet** [comment]
[**@useyourblinker**](https://github.com/useyourblinker) commented on [Sep 16, 2018, 9:24 PM GMT+3](https://github.com/pojome/elementor/issues/2564#issuecomment-421808348 "2018-09-16T18:24:05Z - Replied by Github Reply Comments"):
> I didn't quite gather how the PHP code above resolves the issue.
> 
> For example, integrating with Pardot Form Handlers requires you to go to formsomething.pardot.com/form129419414/?(Name:Name)&(Email:Email)&(Country:Country) etc. I think that this could work, but the current shortcode for the fields have a space such as [field id="4"]. When there is a space in the URL, it won't go anywhere in Elementor's Redirect feature.
> 
> I think that all that is needed in most cases is to be able to do what aag-hyau is saying above. A custom URL with the fields as part of the URL, to work for redirecting.
> 
> This would create integration with hundreds of things (not to mention Pardot) that we can't currently do without other form plugins.

The solution offered would work for this URL just fine, the shortcodes are replaced (including the spaces in them) 
```
http://formsomething.pardot.com/form129419414/?(Name:[field id="name"])&(Email:[field id="email"])&(Country:[field id="country"]) 
```

The only problem that its not a POST redirect, its a GET request.


### Posting to External URL
Redirecting Via POST to any URL, makes no sence in Elementor, making an ajax request to the server only to build/format the url with the form data. But it would make much more sence to Post it via the server and for that you can use a custom web hook for any kind of integration you want.

```PHP
// Elementor forms custom webhook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
		'body' => $fields,
	]);
});
```
[many examples here](https://github.com/pojome/elementor/issues/2397), [another one here](https://github.com/pojome/elementor/issues/4218)

**Comment by parfilov** [comment]
Hello guys! It's now released in Pro 2.2.0 How to use it?

**Comment by ramiy** [comment]
@parfilov In the **Redirect URL** use the field ID.

https://example.com/thanks?email=[field id="email"]

**Comment by tomas-eklund** [comment]
@Vexander It would be `www.g.com/booking?from=[field id="strDate"]&to=[field id="endDate"]`

`www.g.com/booking` is the URL
`from=[field id="strDate"]&to=[field id="endDate"]` is the Query String

The `?` separates the URL and the Query String.

The `&` separates the different parameters within the Query String.

**Comment by Vexander** [comment]
Thank you Tomas.  I see my typo sorry was on my phone.  Just a follow up, is there some way to change the format to of a date field, e.g. from dd/mm/yyyy to mm/dd/yyyy

Thanxs

**Comment by Mannyj2609** [comment]
Hi guys sorry for my stupid question, but how do you then get the data from the URL onto the new webpage?

The information is pulling into the URL - but I am confused by how to then get the data onto the webpage.

**Comment by carlosaceros** [comment]
Hi, sorry for late answer, you can use this tutorial : https://www.youtube.com/watch?v=CBLIWeSmz30

**Comment by nbi1** [comment]
Is there a way to use the ajax_handler to print a message, delay for a few seconds, and then redirect? I've seen code to issue a message and also code to redirect (as shown above), but haven't seen code to execute all three of these with one invocation. Seems like this would be something of interest to plugin authors.

**Comment by thecreativeoffices** [comment]
> @parfilov In the **Redirect URL** use the field ID.
> 
> [https://example.com/thanks?email=[field](https://example.com/thanks?email=%5Bfield) id="email"]

Is there any reason why this wouldn't work? I'm on 2.7.5 and the shortcode itself being appended to the URL instead of the field value. 

This is what I have in my Redirect To box:
`/redirect/?q=[field id="selecteditem"]`

**Comment by DismalSoul** [comment]
Hello guys,

Can you give me a hand?

I'm trying to create a simple form on the page that the user fills and after clicking submit it will open the popup with another form. The popup form needs to populate info from the simple form. 

I tried playing around with popup and redirect actions after simple form submit but was not able to solve this.

Any advice here?

**Comment by pingram3541** [comment]
@DismalSoul Using Pro forms you can choose popup as the action after submit to trigger your popup from the first form.  To pass field data you'd need to use a javascript eventListener for "onchcnage" events or similar to store the field data from form #1 to a global object of which is later used to fill in fields of the form #2 that exists in your popup (which is also loaded on the same page during initial page load which is why we can't use "that" mechanism to POST data from one form to the next, i.e. dynamic population of form #2 fields on page load, form #1 hasn't been filled in yet).

Other ways to pass data are...

- redirect (send to specific url passing data via query vars in the url, aka field shortcodes)
- webhook (send POST data to a specific url but not redirect) 
- Form API ajax method POST (pass to php back end to do something)
- Form API ajax method GET (pass from PHP back back to javascript in front end - round trip)
- 3rd party integrations provided, i.e.MailChimp etc.

I don't see any of these working except maybe the API ajax might be useful, i.e. pass data back to PHP which then does something with the data (if needed) and then passes back to the popup form via javascript.

For example, I used the Forms API to create a playlist creator.  One of the form's fields was an HTML field, modified to allow a shortcode to render a thumbnail gallery of tracks.  Custom javascript was used to track click events on each thumbnail selected building a CSV string into another hidden field which is passed on form submission via the Forms API to the back end PHP that then validates the data and then creates a custom user_meta db field storing an array that includes the track title, tracklist etc. and if validation fails, returns an ajax event to provide a descriptive error so the fields can be fixed and resubmitted.

**Comment by DismalSoul** [comment]
Thank you for your reply.

I have now more clear vision that I can not create this with my skills set :)

**Comment by nicmare** [comment]
> Hi, sorry for late answer, you can use this tutorial : https://www.youtube.com/watch?v=CBLIWeSmz30

thats a complete different topic. its not about prefilled form fields. its about redirect to a custom page and pass the values

**Comment by pingram3541** [comment]
> > Hi, sorry for late answer, you can use this tutorial : https://www.youtube.com/watch?v=CBLIWeSmz30
> 
> thats a complete different topic. its not about prefilled form fields. its about redirect to a custom page and pass the values

"prefilled" form fields can be done by adding a default value to each field in the form editor.  If you'd like them prefilled from a previous form entry, the same steps in the video apply and the default value would use the dynamic "request parameter" with the query var option.

![Screen Shot 2020-12-23 at 11 24 12 AM](https://user-images.githubusercontent.com/319284/103030873-84d14580-4511-11eb-980c-b5afdb34a545.png)

**Comment by webtulya** [comment]
Hello Namaskar

Am using Elementor Pro, facing issue to get button id in elementor form text field.

I have created 4 packages like basic, bronze, silver and gold…(it’s not pricing table widget) there are 4 separate button for all 4 packages… (https://shine1home.com/#offerings)

Here I want when someone click on any button like on Basic's **Get in Touch**, then package name basic should be bind on same page form text field… (https://shine1home.com/#getintouch).

Please guide.

Thanks

The page I need help with: https://shine1home.com

**Comment by majidpk** [comment]
Can't you use field shortcodes?

Get shortcode from field's advanced tab:
![image](https://user-images.githubusercontent.com/16562792/169809823-4c6b54c6-8882-4ac1-85f7-c695e06dfd17.png)

Then use it in redirect action box:
![image](https://user-images.githubusercontent.com/16562792/169809993-f2cae3dd-0286-4e45-83ea-de30519bd987.png)


Checkout this [link](https://theadminbar.com/using-elementors-request-parameters-for-a-personalized-thank-you-page/) for detailed instructions.

**Comment by spencershepard** [comment]
Using field shortcodes as @majidpk suggested does work.

**Comment by luminmike** [comment]
Hello,Majidpk
I set up the jump in Elementor with the same settings as your screenshot, but when I test it the jump comes up with a 404 page. Do you know how to solve this problem please?
![fb09ef89bfc0698099368f0a5d48769](https://github.com/elementor/elementor/assets/131432537/49310f5b-331b-453b-bcb7-71fbc92c72bf)

Thank you

**Comment by tycoonster** [comment]
@luminmike had this issue as well, what solve my problem was changing the variable name so it wont be the same as the field.
for example:
https://www.website.com/redirect?Fname=[field id="name"]&Femail=[field id="email"]
on the landing page use the variables names not the field names as well.

**Comment by hepsein** [comment]
> +1
> 
> Here's my use case: I have a form where the visitor can make a charitable donation (for medical research). They select an amount to donate, enter their address, choose method of payment, accept some terms etc. The form is made with Elementor Pro. Two actions after submit are required:
> 
> 1. A webhook makes sure that the posted data is collected, processed and saved to a database. Two e-mails are sent as well. If an error happens here, there's really no solid way to let the user know.
> 2. A redirect is made to a payment page, where instructions for the chosen payment method is displayed. For credit card payments there is logic and a button which integrates with the payment provider.
> 
> The problem is that, by default, the payment page gets NO information about anything posted by the form. Nothing! It would be impossible to show the right payment info without some "hacking".
> 
> My solution (hack) is to have JavaScript create a GUID on the form page, set a cookie with this GUID and inject the GUID into a hidden form field. By reading the cookie on the payment page and looking in the database for a donation with that GUID, I can pull the right data for the payment.
> 
> But it is not a stable solution. The unnecessary reliance on cookies, the JavaScript, the browser caching, all poses problems.
> 
> Two different solutions would be acceptable for me:
> 
> * The posibility to actually POST the form to a given URL.
> * The option to have Elementor generate a GUID in a hidden form field and also send this GUID as a GET parameter to the redirection page.
> 
> The first solution would be preferable as we could then implement server-side data validation, and not have to write two different scripts for data processing (webhook) and user communication (redirect).

Same problem, looks like it's still not implemented, how did you do it? Does anyone have a solution?

**Comment by maximilien-leleu** [comment]
Hi,

I'm using elementor form shortcodes to redirect to a specific url using form field values (as explained above) and it works well.
Spaces (when there are spaces in field values) are automacally replaced by "+" symbol in the redirected/generated link/url.

However, I want to add the same exact link (redirect link) in my email and I built it the same way but in the email sent, the spaces that come form field values broke my link when it is received.


Redirect link : https://mywebsite.com/form?param1=Text1+Text2+Text3 >> OK
In my email : https://mywebsite.com/form?param1=Text1 Text2 Text3 >> (link is broken because of spaces : link only applies to https://mywebsite.com/form?param1=Text1 then it's broken)

Does anyone has a solution to fix this ?
Thanks for helping
