### ISSUE TITLE
[Feature Request] EP Forms Widget | Expansion | Connect checkbox to mailservice

### ISSUE THREAD

**Issue by Ver3** [pojome/elementor#2565]
We'd like to add a checkbox "Click here to subscribe to our Newsletter" under all forms. The user should only be added to our MailChimp list if the box is checked.

### IF/THEN

ONLY IF user checks checkbox THEN add user to mailing list of selected service.
IF NOT, only send contents of form to designated email address.

### Currently only possible with other forms plugins

Currently you can either get an email after a user fills in a form, or they get added to (for example) MailChimp. But not only when a box is checked.

I hope this makes any sense.

**Comment by bainternet** [comment]
Currently this feature is not supported, but we will look in to it in the future.

However you can catch the submit of a form and check for that checkbox, and based on that register the user to your mailing list.

see this doc https://github.com/pojome/elementor/blob/master/docs/content/pro/forms.md

Thanks for the feedback.

**Comment by Ver3** [comment]
Hi @bainternet I looked at the info you provided, but that goes beyond my abilities. We hope you'll add the function to the forms widget as suggested. Many European users will thank you for it. By law, we are not allowed to add people to mailing lists if that box is not checked.

**Comment by aromawater** [comment]
Thanks to @Ver3! I would love to have that feature in Elementor Pro.

**Comment by RoosaYade** [comment]
Agreed! I don't know how to solve this at the moment and the given link  https://github.com/pojome/elementor/blob/master/docs/content/pro/forms.md is invalid at this moment.

Any solutions? My goal is to send a free guide to a given email anyway (doesn't require the checkbox to be checked) and additionally IF they tick the check box then they would be signed to MailChimp-list.

**Comment by Talco100** [comment]
We would also like that option:
The ability to trigger each form action ONLY if checkbox [the one relevant] is checked.
