### ISSUE TITLE
Front-end hooks aren't firing in editor

### ISSUE THREAD

**Issue by mickrip** [pojome/elementor#2567]
```
add_action( 'elementor/frontend/element/before_render', function ( \Elementor\Element_Base $element ) {
   echo "Fired";
}
```

This does not fire within the Elementor editor, but fires everywhere else. Is this a feature, or a bug? Is there an alternative section hook that works within the editor? It's breaking WYSIWYG.

**Comment by bainternet** [comment]
The hooks is working fine but you should not echo out data in it.... maybe that's why you think it's not firing....

**Comment by stevecove** [comment]
As far as i can tell, this action is Not fired in the editor. It is mentioned elsewhere here:

https://github.com/pojome/elementor/issues/2588

And can checked by inserting a breakpoint. 
Is there an equivilent hook that does fire in the editor?

**Comment by atashinbar** [comment]
I have same problem and it is NOT fired in the editor.

**Comment by mmaumio** [comment]
Has anyone been able to fire the frontend hook in the preview?
I have been working on something that'll require this.

Thank You
