### ISSUE TITLE
[Feature Request] Post Widget: allow posting of full content, not just excerpt

### ISSUE THREAD

**Issue by enricofrascati** [pojome/elementor#2569]
Hello,
I need to make text contents (text blocks and titles) on the home page editable by a non-technical person. This person should be able to edit the home page content without direct access to the elementor editor but just editing single pages (where she can create limited problems).

It would be pretty easy if the Post Widget allowed me to publish:
1. no content text
2. content excerpt
3. content full text

It looked very simple until I found out that option 3 is not present, of course.

While I can tell this person to put content into the excerpt field, and not into the main content area, it's not a valid solution since the excerpt field doesn't allow text styling and carriage return in the text, making it not useful for sales and presentation texts.

**Comment by bainternet** [comment]
Currently this feature is not supported, but we will look in to it in the future.

Thanks for the feedback.

**Comment by AmyCelona** [comment]
Any update on this?

**Comment by enricofrascati** [comment]
@AmyCelona Looks like it has been ignored. 
I still think this would be a great power-up for Elementor. 
I had this function in Headway years ago and I built complex layouts using contents extracted from posts and pages which the client could easily edit through the backend text editor, without messing my work. 
I'm not a PHP developer and I can just guess that probably there are some problems with the way Wordpress works, but if the guys from Headway solved this problem in 2010 it should not be so difficult. 
Hope that sooner or later someone adds this feature to Elementor!
