### ISSUE TITLE
Starting out with a premade layout

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#257]
Hey

It would be great to start out with a premade layout the user can choose from to have as a starting point.

- Having a specific section to look at premade layout thumbnails. Clicking a thumbnail seeing it live in the right page/post area. Having a button above the thumbnails that says something like use this layout? Click the button to activate the layout.  

- Bottom of template/premade layout section there can be a save layout button, load layout and export layout. Save the layouts one wants to reuse. Load layout others have created or one has made for other sites. Export layouts to share with others or to load into another site.

As it takes time before understanding how Elementor user interface works having a premade layout can really get one going. It shows samples of what can be done using Elementor and also motivates the user by starting out with a layout and modifying it instead of starting with a blank page having to create the layout.

Ps
I notice similar ideas are mentioned in multiple issues. I am glad to hear your working on this feature!

**Comment by arielk** [comment]
As you seen we are working for this feature right now. It will be released soon. You can follow on this feature here: #132
