### ISSUE TITLE
[Feature Request] Background opacity 

### ISSUE THREAD

**Issue by qwik3r** [pojome/elementor#2570]
It would be nice if you could change the opacity of a background image for a column.

**Comment by bainternet** [comment]
You can actually already do that in two ways:

The first is to set your  background as you normally do, and then set "Background Overlay" to the "Opacity" color you want.

The second option is to simply set background to classic and use the "Background Overlay" to actually insert and define your background, and there you already have an "Opacity" control.

**Comment by qwik3r** [comment]
Thanks!
