### ISSUE TITLE
[BUG] White Space at the top of Card - 'Post' Widget

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2572]
Hey,

Not sure why, but as you'll see from the screenshot, there's a 1px white space at the top of the bottom 3 cards.

![elementor bug](https://user-images.githubusercontent.com/31274564/31409619-73c4e6e0-ae04-11e7-91d2-d400e80b7c98.PNG)

Each image used and card are exactly the same size. 

You can't control each card individually so in theory, they should all be the same.

Any ideas?

**Comment by bainternet** [comment]
@enviedbymost 

can you provide a URL so will have a look, even better would be a copy=paste of your "system-info"

**Comment by enviedbymost** [comment]
Hey bainterest.

The URL is https://www.jamiecoleiro.com/recommended-hip-hop-songs/ and the system info is attached!

Look forward to hearing from you on what the issue could be!

Cheers.

[system-info-www.jamiecoleiro.com-06-11-2017.txt](https://github.com/pojome/elementor/files/1480735/system-info-www.jamiecoleiro.com-06-11-2017.txt)

**Comment by bainternet** [comment]
@enviedbymost 

seems like a CSS issue more than a bug.

Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by Greeps** [comment]
Hi enviedbymost ,
I have the same problem, how did you solve it?
best
Carlos

**Comment by enviedbymost** [comment]
I didn't unfortunately.

As seems typical of the Elementor team, they just close issues when they aren't resolved. Happened to me a few times...
