### ISSUE TITLE
Question : HOW TO Group_Control_Image_Size in Controls_Manager::REPEATER

### ISSUE THREAD

**Issue by GostkaDesign** [pojome/elementor#2574]
Someone know how to use a **Group_Control_Image_Size** or other Group_Control in a **Controls_Manager::REPEATER** ?

And how ? :)

Thanks

**Comment by bainternet** [comment]
Currently this feature is not supported, but we will look in to it in the future.

Thanks for the feedback.

**Comment by GostkaDesign** [comment]
ok thank you
