### ISSUE TITLE
Elementor Pro: Possible bug with WooCommerce Modules

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#2577]
## Description

There is a possible bug with WooCommerce product render in edit mode on page reload.

Please see this video for visual: https://app.hyfy.io/v/abljSu7Y5iU/

## Steps to reproduce

Add either the Woo - Products or the Woo - Categories module to a page and save.

Refresh the page and the content disappears. Frontend is unaffected!

## Environment

WordPress 4.8.2
Elementor 1.7.11
Elementor Pro 1.9.3
WooCommerce 3.2.0
Theme: GeneratePress 1.4 - Also tested with Storefront 2.2.5

Tested on both Localhost and Live server

Live Server:
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | 5.7.17 |  
PHP Version: | 5.6.22

Localhost:
Operating System: | Windows |  
Software: | Apache |  Via Wampserver64
MySQL version: | 5.7.14 |  
PHP Version: | 7.0.10

**Comment by arielk** [comment]
Fixed Pro v1.9.4!

Thanks for your feedback!
