### ISSUE TITLE
[Feature Request] [Enhancement] Pricing Table Toggle

### ISSUE THREAD

**Issue by BradleyDB** [pojome/elementor#2578]
Add the option of a pricing toggle to the Pricing Table widget. For example, this will allow you to display multiple plan levels at monthly or yearly billing intervals. This is great for highlighting savings between a monthly and yearly subscription.
This would entirely eliminate the need for other Pricing Table plugins that may or may not be compatible with Elementor Pro.

**Comment by bainternet** [comment]
@BradleyDB can you provide examples?

**Comment by BradleyDB** [comment]
Sure @bainternet https://fatcatapps.com/easypricingtables/demo/ is an easy one, just ctrl+f "Pricing Toggle" and there are a few examples. If you're looking for coded examples, someone on your support team might have a copy of the pro plugin for EPT Pro.

**Comment by bainternet** [comment]
Currently, this feature is not yet supported, but may will look into it in the future.

Thanks for the feedback and suggestion.

**Comment by BradleyDB** [comment]
@bainternet I know, that's why I tagged it as a feature request :)

**Comment by bainternet** [comment]
@BradleyDB :) I know you did and that's why I labeled it as such so will know to get back to it.

**Comment by muthali** [comment]
@BradleyDB you need not wait for elementor team to release this... I found some other wesbites selling addons for elementor. I think this might help you. https://powerpackelements.com/variable-dual-pricing-table-elementor/ https://uaelementor.com/widgets/content-toggle/ https://essential-addons.com/elementor/content-toggle/

**Comment by hbryanjones** [comment]
Any updates on the pricing toggle? It's something I need too. I'm sure there are a lot of other people wanting this as well. Otherwise I'm off to one of the addons muthali recommended above. Thanks!
