### ISSUE TITLE
Editing Global Widget Template Uncaught TypeError

### ISSUE THREAD

**Issue by DerekBess** [pojome/elementor#2579]
When editing global widget template elementor does not load with newest version.

editor.min.js:2 Uncaught TypeError: Cannot read property 'init' of undefined
    at n.initFrontend (editor.min.js:2)
    at n.onPreviewLoaded (editor.min.js:2)
    at HTMLIFrameElement.dispatch (load-scripts.php:9)
    at HTMLIFrameElement.r.handle (load-scripts.php:9)

TypeError: Cannot read property 'init' of undefined
at wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:27488

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
