### ISSUE TITLE
Global sections

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#258]
I love your plugin. It's so awesome. I've used it on two sites now and plan to use it as my default page builder. 

Is it, or will it be, possible to create global sections (e.g. footers) that be applied to all pages? Elegant Themes' Divi plugin has a Library feature where you can save rows to the library and reuse them on any page. Something similar would be great. Even if there was the ability to copy sections from other pages.

**Comment by arielk** [comment]
Hi 

We are working for this feature right now. It will be released soon. You can follow on this feature here: #132
