### ISSUE TITLE
[Feature Request] A 4th Viewport (Laptop)

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2581]
Right now, we have desktop, tablet and mobile.

Desktop monitors are getting larger, whereas laptops are staying fairly static around the 11-17inch mark. 

Therefore, the visual differences between desktop and laptop screens is growing in size (pun not intended) ;)

A 4th viewport would be an amazing addition to Elementor.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future.

In the meantime, you can use 3rd party "Resizer" like [this one](http://lab.maltewassermann.com/viewport-resizer/) to test your layout in may display proportions, it won't give you the same editing experience but you'll get the same results.

Thanks for the feedback.

**Comment by mstudioIL** [comment]
Are you going to add the laptop viewport?
