### ISSUE TITLE
[Feature Request] Update the design of all elements with the same CSS class name or "Linked widget name"

### ISSUE THREAD

**Issue by andrerademan** [pojome/elementor#2582]
When I set the same CSS Classname (under Advanced) on 4 different widgets or a section or column, then if I made a change to the design of one of the widgets then it would be VERY NICE if all the widgets with the same CSS Classname also updated to the same properties.

Using "CSS Classname" might have unintended consequences for someone already using it for their own styling. Maybe it is better to create a new property "Linked widget name" or similar.

It does not seem like a massive change, i.e. loop through all widgets and update the widget properties if the "Linked widget name" matches, but it would be extremely useful. Also, it might shorten the resultant CSS as styling would only need to be declared once for all the widgets.

For example, if you look at this page: https://library.elementor.com/homepage-app/, in the "Our experts" section, if I change the heading style, then I now have to make the change 3 times. But if I added a class to the heading e.g. "expert-heading" and I change one then it would be a huge time saver if all the styles were updated.

Another example is if I have section headings multiple times per page on multiple pages. If the design on one is updated (any visual property) it would be a massive time saver if the design on all was updated.

It would save a huge amount of time keeping all the elements within a site looking the same.

**Comment by arielk** [comment]
I merged this issue with another issue #1479 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
