### ISSUE TITLE
Styling issue with responsive color controls

### ISSUE THREAD

**Issue by tudormnt** [pojome/elementor#2583]
When adding a responsive COLOR control, the styling in the panel makes it difficult to reach the picker trigger when the breakpoint icons are expanded.

![screen shot 2017-10-13 at 11 26 28](https://user-images.githubusercontent.com/3028412/31537057-8510926c-b009-11e7-8671-024b6c8ad3e4.png)

**Comment by arielk** [comment]
I think this issue has been fixed in one of the latest versions. Feel free to reopen the issue and we'll be happy to help you further.
