### ISSUE TITLE
[FR] Toggle widget collapsed or not control

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2584]
Hi! We need to control the collapsing of the Toggle widget items. Please don't advice the Accordeon their have other logic of work.

It would be nice to set count of uncollapsed items in order. 1 — first, 2 — second etc.

Thanks!

**Comment by jayalove** [comment]
I second this request 😉

**Comment by jonathanasbell** [comment]
On both Toggle and Accordion widget we should be able to determine that the widget not begin in the "open" position

**Comment by black-eye** [comment]
+1

**Comment by zefflubrano** [comment]
+1

**Comment by bainternet** [comment]
I merged this issue with  #2756, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by ZambraDesigner** [comment]
+1
