### ISSUE TITLE
Bug with Image Box

### ISSUE THREAD

**Issue by lamiastartup** [pojome/elementor#2586]
Hi guys, 

Spacing for mobile does not work for **Image Box**

I attached a gif to show the problem.

![bug](https://user-images.githubusercontent.com/31349279/31564537-798e4a60-b063-11e7-9b7c-38d98c342aa4.gif)

**Comment by GostkaDesign** [comment]
look at your inspector(F12) and focus on the ig container (figure)

`<figure class="elementor-image-box-img"><img src="YOURDOMAINE/wordpress/wp-content/plugins/elementor/assets/images/placeholder.png" alt="" title=""></figure>`

The figure class="elementor-image-box-img" is affect by the slider did his margin bottom is moving when you slide?

**Comment by Malkalypse** [comment]
This issue has still not been fixed

**Comment by StaniKub** [comment]
still not fixed
