### ISSUE TITLE
Elementor hangs opening page for editing after installing Cue audio plug-in

### ISSUE THREAD

**Issue by kgwphoto** [pojome/elementor#2589]
Description

Elementor hangs loading a page for editing after installation of Cue audio plug-on

Steps to reproduce

Install and activate Cue audio plug-in then choose to edit a page with Elementor. At that point Elementor hangs

Environment

2 system reports are included. One for editing my live site and one for Serverpress test site. Both have similar errors after installing Cue audio plug-in
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 7.0.12
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: https://www.isindigo.com
	Home URL: https://www.isindigo.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: kgwhite@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: TESSERACT
	Version: 3.7.6
	Author: Tesseract Theme
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.11
		Author: Elementor.com

	Jetpack by WordPress.com
		Version: 5.4
		Author: Automattic

	OptinMonster API
		Version: 1.2.2
		Author: OptinMonster Team

	W3 Total Cache
		Version: 0.9.5.4
		Author: Frederick Townes

	WPForms Lite
		Version: 1.4.1.1
		Author: WPForms

== Must-Use Plugins ==
	Endurance Browser Cache
		Version: 0.4
		Author: Mike Hansen

	Endurance Page Cache
		Version: 1.1
		Author: Mike Hansen

	Endurance PHP Edge
		Version: 0.1
		Author: Mike Hansen

	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen

== Debug ==
	Errors: 
		ReferenceError: DialogsManager is not defined
			at https://www.isindigo.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:26739
			2017-10-15 17:50 +00:00
			x 2 times

		TypeError: Cannot read property 'removeClass' of undefined
			at https://www.isindigo.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:104207
			2017-10-15 14:48 +00:00
			x 2 times

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.5.24
	MySQL version: 5.6.24
	PHP Version: 5.5.24
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: http://www.isindigo-2.dev
	Home URL: http://www.isindigo-2.dev
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: kgwhite@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: TESSERACT
	Version: 3.7.6
	Author: Tesseract Theme
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
	Cue
		Version: 2.2.1
		Author: AudioTheme

	Elementor
		Version: 1.7.11
		Author: Elementor.com

	W3 Total Cache
		Version: 0.9.5.4
		Author: Frederick Townes

	WooCommerce
		Version: 3.2.0
		Author: Automattic

== Debug ==
	Errors: 
		ReferenceError: DialogsManager is not defined
			at http://www.isindigo-2.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:26739
			2017-10-15 18:15 +00:00

		TypeError: Cannot read property 'removeClass' of undefined
			at http://www.isindigo-2.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:104207
			2017-10-13 20:48 +00:00
			x 4 times

[system-info-www.isindigo-2.dev-15-10-2017.txt](https://github.com/pojome/elementor/files/1385694/system-info-www.isindigo-2.dev-15-10-2017.txt)

**Comment by bainternet** [comment]
@kgwphoto 

We cannot replicate the issue you are describing, but we can say its got nothing to do with Cue and probably something very specific to your case.

Please try to contact our support.

Thanks for the feedback.
