### ISSUE TITLE
Feature request to modify the search result page

### ISSUE THREAD

**Issue by lilianmurciaart** [pojome/elementor#2590]
I know of to display the search function, you can simply drag the 'search' widget which comes from wordpress default widget. But.. i want to modify the search result page instead, that this is not possible at the moment. That's what I want to do.
NOTE: I use the "Elementor canvas" function all the time
Customization of the widget is a plus..
thanks! and hope it's possible ;)

**Comment by bainternet** [comment]
@lilianmurciaart 

I can assure you this is on our roadmap.

I merged this issue with  #417, which are on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
