### ISSUE TITLE
Image sizes aren't working on new version!

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#2595]
The image size controls of drop down isn't working!! It's loading the full size image only !!

**Comment by arielk** [comment]
Which version are you using?

Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by soyket** [comment]
Hi
I am using the latest update. It was working before. after upadte I noticed that it's not working anymore. Images are not being sized ( small, large, or custom) . They are loaded with the full image only even if you choose size. I tested with no plugins. also I tested it with 3 sites. am guessing it's working fine over your end ? and I will contact support thanks !
