### ISSUE TITLE
Feature request: allow the user to design the toggle icon

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#2599]
Add few more controls to design the toggle icon:

* **Icon Position** - float to left / right.
* **Icon Color** - color picker.
* **Closed Icon** - select box with font awesome icon select.
* **Active Icon** - select box with font awesome icon select.

Currently the toggle icon positioned before the title, allow the user to move to the other side. change icon colors and select custom icons.

Current:
![togglee](https://user-images.githubusercontent.com/576623/31659156-d617243e-b33b-11e7-8f2f-bdefc46c13ad.png)

New:
![toggle](https://user-images.githubusercontent.com/576623/31658996-5a3d046e-b33b-11e7-8ccf-da9d5b85fc22.png)

**Comment by archtflirt** [comment]
YES! I would love that ability as well. Just ran into that issue when adding toggles.

**Comment by ramiy** [comment]
Seems like the **Icon Position** behavior is already implemented in **Accordion Widget** we can implements it in **Toggle Widget**.

![elementor](https://user-images.githubusercontent.com/576623/33245060-09a7f33e-d30b-11e7-9b0b-fa211ce592e2.png)

**Comment by archtflirt** [comment]
Yes, that would be extremely helpful as there is a difference between accordion and toggle. I want my customers to be able to open several questions at the same time (toggle) not one at a time (accordion). 
Also, adding the capability to choose the icon would be helpful too. I know that Divi does that already and it's one of my favorite things when building websites. They allow me to choose the icon on every feature not just some, which makes it extremely versatile. 
I use several builders according to what my clients want, so yeah. Vast experience across Divi, Cornerstone, Thrive and Fusion. I'm brand new to Elementor lol
Thanks,
Giulia Guerrero
    On Sunday, November 26, 2017, 5:39:19 PM EST, Rami Yushuvaev <notifications@github.com> wrote:  
 
 
Seems like the Icon Position behavior is already implemented in Accordion Widget we can implements it in Toggle Widget.

**Comment by ramiy** [comment]
@archtflirt I'm on it.

Currently I'm standardizing both widgets. I added a new **Icon** section. Tomorrow I'll issues a new Pull Request.

![elementor-at](https://user-images.githubusercontent.com/576623/33245413-230bb39c-d310-11e7-9cab-267c5562beea.png)

**Comment by archtflirt** [comment]
Thank you so much. 
Have a great rest of your week.
    On Sunday, November 26, 2017, 6:14:37 PM EST, Rami Yushuvaev <notifications@github.com> wrote:  
 
 
@archtflirt I'm on it.

Currently I'm standardizing both widgets. I added a new Icon section. Tomorrow I'll issues a new Pull Request.
