### ISSUE TITLE
Is it possible to create our own element?

### ISSUE THREAD

**Issue by ariona** [pojome/elementor#26]

**Comment by yehudah** [comment]
Hello,

We are working on the API documentation and hoping to release it soon.
For now you can check how internal widgets are working.

Thanks.

**Comment by ariona** [comment]
That's great, and yes, i have digging through all elementor components. Will it be class based file like internal widget? or something like options.php & view.php?

**Comment by duongancol** [comment]
The same concern, it could be code like an internal widget?
 I'm waiting to see the API documentation, hope it releases soon!

**Comment by KingYes** [comment]
@duongancol @ariona
For now you can see how we write widgets from the plugin. For example you can see the [Text Editor widget source](https://github.com/pojome/elementor/blob/master/includes/widgets/text-editor.php) (It's a very simple widget).

It's still a beta version and maybe the API will be changed, but for now you can override these methods:

`public function get_id()` - Just return your ID of your widget (unique one).

`public function get_title()` - Return the title of your widget. It will show in the Panel.

`protected function _register_controls()` - In this method you can register/un-register controls. For now you can see from other widget how to use this controls. Each control you register here will be used in the templates (see below).

`protected function render( $instance = [] )` - Here you write your PHP template. The `$instance` var will be assign to all the controls you register above.

`protected function content_template()` - Here you write your JS template. The global var `settings` will be assign to your controls.

**What is the difference between PHP and JS templates?**
To improve your speed render when any control get changed, we create two templates. While you edit any element, the JS template is in use (Using by MarionetteJS+Underscrore). When you finish editing, the builder fetch the PHP (final) template from server. The PHP template is being used in frontend as well.

**Do I have to write each widget also in JS?**
Nope. It's intended to improve your speed of the rendering process. To disable this, you need to override this method and do not print anything. The system detect this and each changes will be used by PHP template.

BTW, if you want the "easy way" to write widgets, you can write this by WordPress Widgets API, and Elementor will embed this automatically.

Cheers,
Yakir

**Comment by duongancol** [comment]
@KingYes : thanks for your info, how about creating a widget from theme, it this ready yet?

**Comment by duongancol** [comment]
and one more question, what library to make drag & drop function?

**Comment by KingYes** [comment]
We write this library for Elementor. It's for d&d from the Panel to builder (based on HTML5 API). The sortable we using with jQueryUI.

**Comment by duongancol** [comment]
thanks, it's really good

**Comment by pingram3541** [comment]
Looking at the text editor widget source I don't see the Advanced Tab defined such as:

$this->add_control( 'section_advanced', ...

Is that automatically inclusive on every widget or defined elsewhere?

**Comment by joshmarom** [comment]
Hi guys please refer to https://github.com/pojome/elementor/tree/develop/docs for developer documentation on Elementor. it is still work in progress, if you find it is missing something, please let us know.
Also see https://github.com/pojome/elementor-hello-world for an example of a simple plugin extending Elementor

> Is that automatically inclusive on every widget or defined elsewhere?
Yes, it is a inherited from Widget_Base

**Comment by mohammadmursaleen** [comment]
@joshmarom your provided link seems to be broken now. Official Elementor documentation has everything now that developers might need to start building widgets.
[https://developers.elementor.com/creating-a-new-widget/](https://developers.elementor.com/creating-a-new-widget/)

**Comment by tannerchung** [comment]
@joshmarom what's the best way for us to _extend_ one of your widgets? For example, if I wanted to add another control in the panel for the blog posts so that they show social icons for sharing?
