### ISSUE TITLE
Hooks, more hooks! And other suggestions.

### ISSUE THREAD

**Issue by marcusig** [pojome/elementor#260]
Hi there, 
First of, thanks for the great plugin. Works and looks great. 
So I'd like to contribute and share my first impressions, as I just tried it. 

If I love how it looks and feels outside, as a developper and webdesigner I'd like to have a more control over what happens under the hood. 
- First thing I tried to do, is change the default color schemes. So I looked if I could setup a hook, but couldn't. There's actually only 7 occurences of "apply_filters" in the whole plugin, which is amazingly small for a WordPress plugin of this importance. 
For example in includes/schemes/color.php, I wish that every single function would not just return an array, but apply a filter on it, to allow us to change those defaults. 
- If I'm not mistaking, the default Typography loaded is Roboto, but I think the "default" option (inheriting fonts from the theme) should be default indeed.  

And I'm sure there's a lot more features that could use a filter. 

Again this is just my opinion, maybe the performances benefit of avoiding this, but for extending / customizing the options for specific themes, I believe it would be great to add hooks (practically) everywhere.

Cheers.
Marc.

**Comment by KingYes** [comment]
You right. We should add more hooks to Elementor. For now, we don't have any Official API to extend the Elementor. But we work to get this work, and later we create more hooks.

Thanks for your feedback :)

**Comment by arielk** [comment]
merged #291
