### ISSUE TITLE
[Bug] Image gallery widget border can't be removed

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#2601]
I could be wrong, but I can't seem to remove the border on the Image Gallery Widget when I put it on a dark background. I have the border set to "None" but am still seeing a 1px white border.

![image-gallery-widget](https://user-images.githubusercontent.com/29379115/31678843-fb7f15bc-b334-11e7-9f98-aca97c1cbaae.jpg)

**Comment by norewp** [comment]
Have you checked your theme's defined CSS rules for images?

What theme are you using?
What other plugins that deal with images/galleries do you have active?
What is the site url where you are having this issue?

**Comment by avermat** [comment]
It looks to be an issue with Astra (it went away when I switched themes). I'll contact them first and see what they say.

**Comment by avermat** [comment]
Astra said their team will be fixing this issue.
