### ISSUE TITLE
Media Carousel Starting at a Random Place?

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2607]
Hey,

I've looked through all the media carousel settings, and couldn't see anything for this!

Say I have a 20 item media carousel (in my case, I'm using album covers) and I purposely have a specific ordering, whenever I load the page, the carousel starts at a random place, i.e. 7/20.

Is there a way to set the carousel so it always starts from the beginning on page load?

Thanksss

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by enviedbymost** [comment]
Hi guys,

I hope you’re well this morning! ☺

I’m replying following the email below.

Here’s an example page where the carousel begins in the middle -  https://www.jamiecoleiro.com/recommended-hip-hop-songs/weekly-playlist-8/

Expected behaviour is it starts from the first node of the carousel. Why would it start halfway? Seems odd!



Login URL: www.jamiecoleiro.com/paradise<http://www.jamiecoleiro.com/paradise>
Username: elementor
Password: O%lJPJWx5pop&V&@HhHrnuT(


I look forward to hearing about the outcome of your investigation!

Talk soon.

Cheers, Jamie.

**Comment by arielk** [comment]
I removed the login access above (it's public), please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by enviedbymost** [comment]
Crap, I emailed the auto-reply notification email by accident. What an idiot.

Teaches me for working at 1:30am (passed my bedtime lol).

Thanks for removing it!!!!
