### ISSUE TITLE
<new idea> Review widget connected with FB and Google + rich snippet 

### ISSUE THREAD

**Issue by Steve-oww** [pojome/elementor#2609]
Hi Guys,

This should be the place to drop a new idea for elementor :-) 

I have a feature that i'm missing at the moment in elementor and now i have to use a plugin. It would be great if you guys can build such a plugin in elementor. See the link below can you build such a feature (see pro version)? And is it possible to add rich snippet to the feature?

http://ljapps.com/wp-review-slider-pro/

Cheers,
Stefan

**Comment by bainternet** [comment]
Can you elaborate more about what exactly you would like to see added ?

**Comment by Basilakis** [comment]
The slider / carousel that exist, does not have a way to output richsnippet. So if a carousel is a testimonial, we can not define that on the carousel.

A way to add schema from a dropdown 
Example:
Testimonial
Blog Post
Jobs

would actually be really good. 
A sample schema function is located here:
https://gist.github.com/Basilakis/7df5e62cb59aa83910dc0324176cf35f

not all included, just what I was in need on that point.

**Comment by jayalove** [comment]
I second this request 😉

That would be amazing!

**Comment by shilo-ey** [comment]
This request has been added partially using [Reviews widget](https://www.youtube.com/watch?v=sxTXGEz1Raw).

Currently, the schema feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
