### ISSUE TITLE
Any filter to add custom animations?

### ISSUE THREAD

**Issue by guytzhak** [pojome/elementor#2612]
Hi,
 The class 'Control_Animation' has any filter to add custom animations to element instead the default animations that came with elementor?

I want to add my custom animations and don't see any filter for that.

**Comment by bainternet** [comment]
NO filters as of now but you can always create a [custom control](https://github.com/pojome/elementor/blob/6ad74c472564c712bff453cbd54eaa40fb5bb151/docs/content/controls/README.md)
