### ISSUE TITLE
Template Library Import Returns HTTP Error 500

### ISSUE THREAD

**Issue by Ratko-Solaja** [pojome/elementor#2613]
## Description

When I try to import a template on a free version on my server, HTTP Error 500 appears.
Here's the nginx error log:

`2017/10/20 14:55:56 [warn] 770#770: *1144 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000013, client: 188.2.46.29, server: vuelabs.us, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", host: "vuelabs.us", referrer: "https://vuelabs.us/wp-admin/edit.php?post_type=elementor_library"
2017/10/20 14:55:56 [error] 770#770: *1144 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /var/www/vuelabs.us/wp-content/plugins/elementor/includes/template-library/sources/local.php:362
Stack trace:
#0 /var/www/vuelabs.us/wp-content/plugins/elementor/includes/template-library/manager.php(225): Elementor\TemplateLibrary\Source_Local->import_template()
#1 [internal function]: Elementor\TemplateLibrary\Manager->import_template(Array)
#2 /var/www/vuelabs.us/wp-content/plugins/elementor/includes/template-library/manager.php(255): call_user_func(Array, Array)
#3 /var/www/vuelabs.us/wp-content/plugins/elementor/includes/template-library/manager.php(307): Elementor\TemplateLibrary\Manager->handle_ajax_request('import_template')
#4 /var/www/vuelabs.us/wp-includes/class-wp-hook.php(298): Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}('')
#5 /var/www/vuelabs.us/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#6 /var/www/vuelabs.us/wp-includes/plugin.php(453): WP_Hook->do_action(Ar" while reading response header from upstream, client: 188.2.46.29, server: vuelabs.us, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "vuelabs.us", referrer: "https://vuelabs.us/wp-admin/edit.php?post_type=elementor_library"
`

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.12.1
	MySQL version: 5.7.19
	PHP Version: 7.1.9-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: https://vuelabs.us
	Home URL: https://vuelabs.us
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Five Fatal Foods
	Version: 1.0.0
	Author: Digest MD
	Child Theme: Yes
	Parent Theme Name: Storefront
	Parent Theme Version: 2.2.5
	Parent Theme Author: WooThemes

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.7.11
		Author: Elementor.com

	Five Fatal Foods
		Version: 1.0.0
		Author: Digest MD

	Redis Object Cache
		Version: 1.3.5
		Author: Till Krüss

	Responsive Pricing Table
		Version: 4.3.2
		Author: WP Darko

	Ultimate FAQ
		Version: 1.6.5
		Author: Etoile Web Design

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WP Rocket
		Version: 2.10.9
		Author: WP Media

	WP Smush
		Version: 2.7.6
		Author: WPMU DEV

== Debug ==
	Errors: There are no errors to display

**Comment by KingYes** [comment]
You need [`ZipArchive`](http://php.net/manual/en/class.ziparchive.php) exts for your PHP.
