### ISSUE TITLE
[Feature request] Add filter to panel-elements.php tmpl-elementor-panel-elements

### ISSUE THREAD

**Issue by andreasnrb** [pojome/elementor#2614]
I think it would be great to have an action or filter added to editor-templates/panel-elements.php .
```php
<div id="elementor-panel-elements-navigation" class="elementor-panel-navigation">
    <?php $tabs = apply_filters('elementor/editor/navigation/tabs', [
    ['id'=>'all','view'=>'categories', 'label'=> __( 'Elements', 'elementor' )],
    ['id'=>'global','view'=>'global', 'label'=> __( 'Global', 'elementor' )]
]);
<?php foreach($tabs as $tab): ?>
    <div id="elementor-panel-elements-navigation-<?= esc_attr($tab['id'])?>" class="elementor-panel-navigation-tab" data-view="<?= esc_attr($tab['view'])?>"><?= esc_html($tab['label'])?></div>
<?php endforeach; ?>
</div>
```
Currently I do an ugly solution of using WordPress filter manipulation and replacing the Editor wp_footer hook and reflection to replace the editor_templates loading panel-elements.php. Also the CSS would need to be changed so it supports wrapping of new tabs. #

**Comment by bainternet** [comment]
@andreasnrb 

Thanks for your suggestion. 
Currently, we like to keep our main panel design to minimal so, for now, we will not be adding any filter in that direction but we will look into it in the future if we see a large demand and justification for it.

Can you share a use case where this would be absolutely needed? 

And Again, thanks for the feedback.
