### ISSUE TITLE
Adding text editor options to icons list

### ISSUE THREAD

**Issue by rami48** [pojome/elementor#2616]
The element "icon list" text is only plain text.
It does not have basic options for text editing.
Specifically, it would be great to have the option for bold, and the option for adding a hyper link.
Today the link is possible only for the whole item, and the viewer is sometimes not aware there are links there on some of the items. It would be good to have the option to add link to specific words, like in regular text.
Thank you.

**Comment by bainternet** [comment]
Hi Rami,

In version 1.8 we are adding inline editing which will give you the ability to set: "Bold", "Italic" and "Underline" of the text.
