### ISSUE TITLE
[Feature Request] Blog Element

### ISSUE THREAD

**Issue by lunacroft** [pojome/elementor#262]
An element to show Wordpress published posts like a Blog listing page, with image, excerpt, read more button, categories and meta info. When click at button would be opened single post page. This single post page could be designed using template feature, currently under development.

**Comment by lunacroft** [comment]
Hey guys, any news about it? =)

**Comment by arielk** [comment]
The blog widget is now available in Elementor Pro, check it out: https://elementor.com/pro/
