### ISSUE TITLE
[Feature request] More features to Posts

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#2621]
We need more meta options to Posts Widget.

Would be nice to have a Carousel Posts and on hover show the enxerpt or title.

Posts widget need to be more customizable, will be a game changer ;)

**Comment by themedleb** [comment]
+1

**Comment by bainternet** [comment]
I merged this issue with  #219, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there @silvioghedin!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.11! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
