### ISSUE TITLE
Support for wp_nav_menu()?

### ISSUE THREAD

**Issue by smpetrey** [pojome/elementor#2623]
Hello! 

First off, Elementor Pro has been amazing! It's such a useful tool for page/post layouts. Loving it!

I typically begin them development with Starter Themes such as Underscores or Sage. That being said, compatibility so far has been great and haven't had any issues. I have however ran into a small issue considering using Elementor for global navigation. Considering the fact that most global navs _live_ in the `header.php` file — can we expect Elementor to support the Wordpress function `wp_nav_menu()` in any way? If I may, I have a feature suggestion

For example, if I call upon a "Primary Navigation" menu in my `header.php`:
```
if (has_nav_menu('primary_navigation')) :
  wp_nav_menu([
    'theme_location' => 'primary_navigation',
    'menu_class' => 'nav'
  ]);
endif;
```
And (forgive the shotty Photoshop job), a user can edit a Global Nav from the appearance pane:
![example](https://user-images.githubusercontent.com/6411509/31870737-83fd6d52-b77d-11e7-92ba-362ff60d3ed6.jpg)

I'd love to see a means of managing a global nav template. That way users won't have to drag-and-drop the nav menu template on every page. The `wp_nav_menu()` function will just autoload a menu and managing it will follow the current paradigm in place set by Wordpress. I'd love to hear your thoughts and feedback!

**Comment by bainternet** [comment]
@smpetrey 

Thanks for the suggestion ( and amazing photoshop job :smile: )

We do have something similar planned on our roadmap which should provide a solution for this.

**Comment by smpetrey** [comment]
@bainternet thanks! Excited to see what comes down the pipeline 😄
