### ISSUE TITLE
[Suggestion] Fixed Image size for Image Box

### ISSUE THREAD

**Issue by katart** [pojome/elementor#2625]
I like the option to set the image size by percentage (and for each breakpoint), but there are times where I want to set a fixed width for the image in the Image Box widget.

I was wondering if there is a reason NOT to allow for a fixed image size within the Image Box, or if this is something you will consider adding to the UI?

**Comment by katart** [comment]
The Image Box widget does not have a setting for "custom". The Image widget does, but the Image Box widget does not. I should have mentioned Image Box widget in the Issue Title.

**Comment by bainternet** [comment]
Well yea that is a different widget altogether, sorry.

Anyway the only way to set a fixed width and height for an image in an image box widget is to give the widget a css class or an id and set the width and height in custom css. ex:
```
.myClass img{
   width: 250px;
   height: 180px;
}
```

**Comment by katart** [comment]
@bainternet Thanks for the response. I would like to see a "custom" option in the Style UI.
