### ISSUE TITLE
add to the class Posts, set_query() method

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#2626]
It would be nice to be able to change the query not only from the settings perspective. this is good for special filters. Something like:

	private $new_query=null;
	public function set_query($new_query) {
		$this->new_query=$new_query;
	}
	public function query_posts() {

		if ($this->new_query) $this->query=$this->new_query; 
			else{
				$query_args = Module::get_query_args( 'posts', $this->get_settings() );

				$query_args['posts_per_page'] = $this->get_current_skin()->get_instance_value( 'posts_per_page' );
				$query_args['paged'] = $this->get_current_page();

				$this->query = new \WP_Query( $query_args );
			}
	}
Or you can add a filter, your choosing.

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/pojome/elementor/issues/1748 in the same subject so we could deal with it more efficiently.

Thanks for your feedback!
