### ISSUE TITLE
[Bug] Serious issue with the tablet responsiveness

### ISSUE THREAD

**Issue by rtthemes** [pojome/elementor#2627]
## Description

The tablet column width doesn't work with real tablets ( 768px ). See the images https://imgur.com/a/2hCEO It works on Elementor because the Elementor responsive preview frame is lower than 768px. 

## Steps to reproduce

- Create a new row with two columns
- Change the column widths like 40%-60%
- Click the tablet icon and give 100% for both columns.

It will look like working on the Elementor frame but it won't work in real tablets ( 768px ) as the desktop value still overwrites.  

## Environment

Tested with 1.7.12 and Twenty Seventeen Theme.

**Comment by arielk** [comment]
This problem rarely occurs only in older PHP versions (<7), please update to PHP 7+ and this should work correctly.
