### ISSUE TITLE
Missing styles when duplicating page

### ISSUE THREAD

**Issue by stevebasford** [pojome/elementor#2630]
## Description

I seem to be experiencing an issue whereby after duplicating a page (either by duplicate post or polylang) that some Elementor implemented styles are missing.

## Steps to reproduce

1. Have a page with modified styles such as centering text & adding padding to elements.
2. Duplicate page by either of the means mentioned above.

## Environment

https://pastebin.com/mdjy8Sj8

**Comment by shapiraman** [comment]
any update about this?

**Comment by arielk** [comment]
Sorry for the delay. But we have not encountered this problem so far.

In any case according to the information you sent us it looks like you have a cache plugin that makes it, try shutting it down and check if it works out.

**Comment by bainternet** [comment]
@shapiraman, @stevebasford 

After you clone, just enter elementor and update, this should regenerate the css.

**Comment by parthasaradhis** [comment]
Please follow below steps
1.In Elementor save it as template with any of name
2. find that template in WP Dashboard>Elementor>My Library>Export Template
3.Import that file in WP Dashboard>Elementor>My Library>Import Template
4.see this link "https://www.youtube.com/watch?v=7Spk7k69WZM" you will understand

**Comment by htmlswift** [comment]
> @shapiraman, @stevebasford
> 
> After you clone, just enter elementor and update, this should regenerate the css.

Thank you for you reply, it helped me to solve the same issue I was facing.. :)

**Comment by intelink-management-office** [comment]
If this @bainternet suggestion is not working. 

Go to Elementor > Settings > Advanced 

Change the top setting "CSS writingmethod" to the one you don't have. 

Hit save. 

Change back to your original setting

Hit save. 

This generates the CSS I was missing and everything worked after that.
