### ISSUE TITLE
Trying to use Elementor if Gutenberg is active

### ISSUE THREAD

**Issue by lukecav** [pojome/elementor#2631]
Does not seem to be a way to view the **Edit with Elementor** button from the post screen. 

So with the only two active plugins being
**Elementor 1.7.12**
**Gutenberg 1.5.1** 

Active theme
**Twenty Seventeen 1.3**

WP Core being
**4.9-beta4-42021**

![new post](https://user-images.githubusercontent.com/5797332/32005449-8d82fb18-b961-11e7-8a2d-efb8620637be.png)

**Comment by arielk** [comment]
We're waiting for more stable versions to integrate with Gutenberg, for now, it's still beta version, so it's absolutely on the our roadmap.

**Comment by mario312** [comment]
Gutenberg very close, months if that.

**Comment by lukecav** [comment]
Gutenberg might well ship in WP core as early as Jan 2018.

**Comment by arielk** [comment]
I guess we'll take care of it until then :)

**Comment by norewp** [comment]
You can still access the Edit with Elementor button by sellecting Classic Editor from the dropdown next to the "Add New" button. This can be found on both the Pages/Posts list screen and is avaialbe on sites running Gutenberg v1.5.x

As @arielk said, it's too early to start hooking into the new editor

**Comment by lukecav** [comment]
@norewp 

I already now about the Classic Editor plugin, I was talking about default WP.
https://wordpress.org/plugins/classic-editor/

**Comment by renecnielsen** [comment]
Has there been any progress on this one?

**Comment by stevegibbings** [comment]
I've read that Elementor 2.0 is/will be compatible with Gutenberg but how exactly? Is there a roadmap for the detail in Gutenberg compatibility and what is available at a dev level? We are looking to upgrade but need to understand this before we make a decision.

Thanks

**Comment by lukecav** [comment]
@arielk 

So to confirm Elementor will work with the current version of Gutenberg editor [3.1.1](https://wordpress.org/plugins/gutenberg/#developers) then?
