### ISSUE TITLE
Desktop widescreen (16:9) and Desktop Square Screen (4:3) responsive views request

### ISSUE THREAD

**Issue by rammyleeds** [pojome/elementor#2634]
Hi everyone,
This issue...
I have created a website for doctors which looks great on my computer at home which is a 21-inch widescreen display. However, when I go to work and look at my website through National Health Service computers (which is what most doctors will be using), my website looks pretty ugly. The reason being is that they are using   19" non-widescreen displays.       
The request...
So, can some add another responsive view option to Elementor? Currently, it has a desktop, mobile and tablet views.   But can we split the desktop view into two further categories: Desktop Widescreen (16:9) and Desktop Square Screen (4:3)?   Is that possible?      

It would be amazing if you could. Then I can tweak it to look good. Unless you have any other workaround on how I can see how my page would look on different desktop screens to enable me to modify it accordingly.      

Many thanks   
Dr. Ramesh Mehay

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future.

In the meantime, you can use 3rd party "Resizer" like [this one](http://lab.maltewassermann.com/viewport-resizer/) to test your layout in may display proportions, it won't give you the same editing experience but you'll get the same results.

Thanks for the feedback.
