### ISSUE TITLE
[BUG] Broken Global Nav Widget

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2636]
Hey,

[Steps to Reproduce]

* Create a nav
* Save the page - looks ok.
* Save the nav as a global widget
* Save the page - navigation is broken.

Please see my screenshots.

How it should look:

<a href='https://postimages.org/' target='_blank'><img src='https://s1.postimg.org/1giamkg0en/Screen_Shot_2017-10-26_at_10.50.57.png' border='0' alt='Screen_Shot_2017-10-26_at_10.50.57'/></a>

Broken:

<a href='https://postimages.org/' target='_blank'><img src='https://s1.postimg.org/2u4tqlxa73/Screen_Shot_2017-10-26_at_10.51.06.png' border='0' alt='Screen_Shot_2017-10-26_at_10.51.06'/></a>

**Comment by arielk** [comment]
Fixed in v1.9.5 please upgrade!

Thanks for your report!

**Comment by enviedbymost** [comment]
Awesome, thanks guys!
