### ISSUE TITLE
[BUG} Broken Global widget

### ISSUE THREAD

**Issue by lilianmurciaart** [pojome/elementor#2639]
[BUG} Broken Global widget!
the affected ones are the Form widget from ELementor Pro, and the Nav widget. What i see in editor mode, is not the same to the real results.
This start to happen after the update to the recent version (1.9.4). Before this update, everythings was perfect with the global widgets.

**Comment by arielk** [comment]
Fixed in v1.9.5 please upgrade!

Thanks for your report!

**Comment by ianlee** [comment]
Not sure why, but I'm encountering this bug now.
From Wordpress repository
Elementor 1.9.3
Elementor Pro 1.9.1

I make edits to any global widget, save, no errors in developer's console.
Preview shows correct modifications. 
Refreshing the edit page, viewing page, checking other pages - none are updated.
