### ISSUE TITLE
Form shortcode not working in toggle or shortcode elements

### ISSUE THREAD

**Issue by mmaccou** [pojome/elementor#2640]
Description

What I'm trying to achieve is to have a subscribe form within a toggle element, so the full length of the form doesn't take up the page. Inserting the form into the toggle works fine as you can see in the screenshot

<img width="866" alt="screen shot 2017-10-26 at 9 23 37 pm" src="https://user-images.githubusercontent.com/32982983/32083903-17ef34aa-ba94-11e7-810a-0d643bec42a5.png">

However, when I test it out, I get the following error...

<img width="861" alt="screen shot 2017-10-26 at 9 26 27 pm" src="https://user-images.githubusercontent.com/32982983/32083945-6170d9e4-ba94-11e7-856b-56b54c30705e.png">

Steps to reproduce

1. Created a form using the forms element and saved as a template
2. Went to the elementor library and copied the shortcode for the form
3. Inserted a toggle element in the page
4. In the text editor, I entered the shortcode for the form

Environment

https://pastebin.com/zqtt6imB

**Comment by mmaccou** [comment]
One thing I forgot to mention. I tested this in the toggle with shortcode in the text editor, but also tested it in the shortcode element. Neither worked.

**Comment by bainternet** [comment]
Hi @mmaccou,

The good news is that it has nothing to do with the toggle element or the from shortcode.

That message is usually triggered by validation / action failure so make sure that all fields are field as set in requirements and that the "Actions After Submit" are setup correctly.

If you still get that message try removing the actions one by one and maybe even try the form on it own and not in a shortcode.

**Comment by mmaccou** [comment]
Hi Raz,

Thanks for the email back. I heard back from Elementor support saying that shortcode is not supported for forms


Best,

Manuel Maccou

**Comment by bainternet** [comment]
Great,
thanks for the feedback.
