### ISSUE TITLE
Bug Cum Feature Request - HubSpot Collected Forms

### ISSUE THREAD

**Issue by ashrafkamal** [pojome/elementor#2651]
Hi there,

We use Hubspot for our marketing. Hubspot has feature named collected forms that capture form submissions on website.

It technically differentiate forms based on CSS selector, I don't know what it is. Here is link for how it works: https://goo.gl/HwpWTi

By the way, our system was working perfectly before Elementor, but Hubspot identify all forms as single form. Please find attachment for reference.
![screen shot 2017-10-25 at 4 56 04 am](https://user-images.githubusercontent.com/4332412/32142634-28aea15c-bcc1-11e7-867f-be5b0f875079.png)

Or...

Please add more integrations like Drip and Hubspot, that will hit more agencies like us.

**Comment by bainternet** [comment]
@ashrafkamal 

Thanks for the feedback, we will look into it.

I merged this issue with  #2397 , which is basically the same feature request, So we could deal with it more efficiently. 

Please feel free to continue the conversation there.

Thanks for your feedback!
