### ISSUE TITLE
Button text alignment doesn't appear to work

### ISSUE THREAD

**Issue by deptgraffig** [pojome/elementor#2656]
When trying to left align my button text, the styling from within the Elementor panel does not seem to apply

**Comment by norewp** [comment]
The provided aligment is for the button itself and not the button text!

**Comment by bainternet** [comment]
@norewp is correct, the alignment control of the button widget is to set the alignment of the button itself and not the text of the button.

You can however give the button a css class and using "custom css" set the desired alignment of the button text.
