### ISSUE TITLE
Redo / Undo / History

### ISSUE THREAD

**Issue by HaveClassWillCode** [pojome/elementor#266]
Mistakes are easy to make, we're all human.
Would love to have Undo functionality, to roll back actions like adding a widget, resizing columns, changing widget properties, etc.

Tasks:
- [x] Revision History #1120 added for V1.1.0
- [x] Redo / Undo - added for v1.7.0.

**Comment by yehudah** [comment]
Sorry for the late response.

This is in our road map, can't say when exactly so subscribe to get updated :-)

**Comment by arielk** [comment]
- [X ] History #1120 added for V1.1.0
- [ ] Redo / Undo

**Comment by eligold6** [comment]
👍
