### ISSUE TITLE
Empty menu cause jquery to crash

### ISSUE THREAD

**Issue by enricofrascati** [pojome/elementor#2662]
Hello, 
I've just found a bug.
I've created a new menu and forgot to  populate it.
For some reason the new empty menu took the place of the main menu, becoming the navigation menu in my page header (which is built in Anywhere Elementor Pro, btw).
Of course I was not aware of this until, after a couple of hours, I accidentally discovered that the HP was broken: all the animated elements  were just invisible.
After some research, I found out that the empty menu I created was crashing the jquery library "SmartMenu", which runs the navigation menu in the header, and this crashed every jquery on the page, making fading-in elements invisible since there wasn't jquery to make them visible again.

Hope it's clear. And I hope to contribute to the bigger cause of an even greater Elementor (which is already pretty great, btw!) ;)

Best,
Enrico

**Comment by bainternet** [comment]
@enricofrascati 

Anywhere Elementor Pro is not affiliated with Elementor and we cannot support 3rd party plugins.

Please contact the plugin developer for support.

Thanks for the feedback.

**Comment by enricofrascati** [comment]
The bugged navigation menu is the Elementor one. So please forward the problem to whom it may concern.

Please note, Anywhere elementor is just helping me to position the Navigation menu, but it's completely neutral in this and it's not the culprit. By the way, if a problem is relative to Anywhere Elementor I'd contact Anand, the developer, which is always very kind and answers in a few hours at worst.

**Comment by bainternet** [comment]
@enricofrascati 

Thanks again for the feedback clarification, 
I can now replicate the issue you described, and we will take a look at it.

**Comment by KingYes** [comment]
We fixed this and will release in the next EPro release.
