### ISSUE TITLE
Elementor 1.8 - Beta Release (RC3 Updated)

### ISSUE THREAD

**Issue by arielk** [pojome/elementor#2666]
===========
## [RC3 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/2666#issuecomment-342169444)
===========

Hi everyone,

We have been working on version 1.8.0 for several weeks now, and we're excited to share the new Inline Editing feature and get your feedback.

Please review the new features carefully, preferably on your staging sites and not in production.

### Inline Editing
In version 1.8, we continued our focus on improving the ease of use and overall Elementor user experience. We added several inline editing options to add content directly on the frontend itself.

You can now use the Heading widget, for example, and edit the Heading text and design simultaneously, directly in the editing screen, without having to switch through tabs or other setting panels.

All previous editing controls are still available on the widget panel, but in many cases having the ability to edit a simple spelling mistake or change phrasing is much easier to do from the frontend screen.

This is a huge advancement for Elementor's page design experience, and it's an extremely helpful feature for content writers, marketers, designers and site owners alike.

### Developers in Mind

If you are a developer that develop themes, addons or extensions for Elementor, you are invited to learn more about this cool new feature of Inline Editing through the documentation we prepared. This feature has been added in the current version.

When the user edits text inline, sometimes he or she needs to be able to add <u>inline styling</u>. Elementor supports two types of <b>inline editing toolbars</b>.

The “advanced” toolbar has all the usual styling options you normally see in your editor, the “basic” toolbar has only three buttons - bold, italic and underline. When you define the toolbar as “none”, the user will be able to edit the text inline, but won’t see any styling options, as the toolbar will be disabled.

As of version 1.8.0, you can define 3 inline editing states for each textual control in the panel:
<ol>
 	<li>Inline text editing without any toolbar (just typing text inline)</li>
 	<li>Inline text editing with a basic toolbar including: bold, italic and underline buttons</li>
    <li>Inline text editing with an advanced toolbar, including: adding / removing links, H1-H6 heading, preformatting, blockqoute, paragraph and bullet or numbered list buttons</li>
</ol>

Keep in mind that we recommend to use inline editing in the following way: for wysiwyg control use the advanced toolbar, for textarea control use the basic toolbar and for simple text control you should not have toolbars (simple inline editing).

You can see an <a href="https://github.com/pojome/elementor-hello-world/blob/master/widgets/inline-editing.php">example widget</a> that uses all the new inline editing features in our Hello World plugin for Elementor.

To define a specific area in the element to be editable inline, use the newly introduced <a href="https://github.com/pojome/elementor/blob/84731d0f5d4f4f73dc8522d108f1e2e5b62f224d/includes/base/widget-base.php#L575-L596">add_inline_editing_attributes()</a> method.

More advanced widgets that use repeater fields will be able to use the <a href="https://github.com/pojome/elementor/blob/84731d0f5d4f4f73dc8522d108f1e2e5b62f224d/includes/base/widget-base.php#L547-L570">get_repeater_setting_key()</a> method to add inline editing capabilities for specific items. Both methods are well documented and has code examples.

### How to Install Beta Version

If you still haven't enabled beta testing in Elementor, please follow these steps:
<ol>
 	<li>Go to Elementor > Tools > Versions</li>
 	<li>Enable the beta tester feature</li>
 	<li>Go to Dashboard > Updates and update to the latest beta version</li>
</ol>

This will get you testing the new Elementor 1.8.0 RC3. You can also download the new version here:
https://downloads.wordpress.org/plugin/elementor.1.8.0-RC3.zip

### Notes

Designated time for release: November 7, 2017

Many thanks for your support and help!

**For bugs and remarks, please reply with a comment below!**

[Elementor Beta - Sign Up Now For Our Elite Group Of Early Access Testers](https://my.elementor.com/beta/)

**Comment by cavalierlife** [comment]
Very exciting, thank you for doing this!

I do see a bug however. I've done a quick screencast to show the problem in action. http://screencast-o-matic.com/watch/cb6wb32eq6

Basically, cannot see the toolbar options. I don't think I have any CSS setting that would be affecting this, but I'll try on a new install when I have time. I also had Gutenberg installed, but deactivating it didn't affect this problem, so that's not the cause.

I do have low resources on this test site, btw.

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.0.31
	PHP Version: 7.0.24
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.3
	Site URL: https://mydevboxx.com
	Home URL: https://mydevboxx.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 1.4
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.8.0-RC1
		Author: Elementor.com

	Elements Plus!
		Version: 1.4.0
		Author: The CSSIgniter Team

	GP Premium
		Version: 1.4.3
		Author: Tom Usborne

	Gutenberg
		Version: 1.6.0
		Author: Gutenberg Team

	HTML Import 2
		Version: 2.6
		Author: Stephanie Leary

	MainWP Child
		Version: 3.4.3
		Author: MainWP

	MainWP Child Reports
		Version: 1.7
		Author: MainWP

	WooCommerce
		Version: 3.2.2
		Author: Automattic


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP


== Debug ==
	Errors: 
		TypeError: Cannot read property 'removeClass' of undefined
			at https://mydevboxx.com/wp-content/plugins/elementor/assets/js/editor.min.js - 2:105121
			2017-08-20 16:59 +00:00

**Comment by badcat** [comment]
Inline Editing seems pretty solid on my dev site.  

Perhaps a **"remove all formating"** button would make sense too.

**Comment by arielk** [comment]
@cavalierlife please do hard refresh (ctrl+R / f5) in your browser or check in incognito mode if it loads all the new icons on the page.

**Comment by cavalierlife** [comment]
Doh! Yep, a hard refresh is all it needed. Sweet!

**Comment by anandau** [comment]
Inline editing is awesome. Just added inline editing support to one of my widgets. 
Loving it the way you guys have implemented it. Very developer friendly.

**Comment by badcat** [comment]
@anandau May I see your widget plugin?  

I'm getting an error when starting with the example Hello World plugin here:  
**'hello_world_fail_load_out_of_date' not found**

https://github.com/pojome/elementor-hello-world/blob/master/widgets/inline-editing.php

```
( ! ) Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'hello_world_fail_load_out_of_date' not found or invalid function name in /app/public/wp-includes/class-wp-hook.php on line 298
```

**Comment by norewp** [comment]
Looks good here and agree on the ease of inline editing implementation for addons/extensions - super simple, thank you :)

Now I got my work cut out with a tonne of modules to update before go live :D

**Comment by anandau** [comment]
@badcat 
I have not tried the hello world plugin. 
I just tried updating a widget of my existing plugin and it was successful. Can't show it to you as changes are not yet live. 

The error message you are getting seems to be because of you might not have upgraded Elementor to 1.8 beta.

**Comment by themedleb** [comment]
Very nice and good idea implementation , so excited for this feature and all the coming ones.

**Comment by norewp** [comment]
@badcat For now change line 34 of hello-world.php from `$elementor_version_required = '1.8.0';` to `$elementor_version_required = '1.7.12';` and you should be ok to go.

Will do a PR for the missing function in a little while.

**Comment by norewp** [comment]
[Sorry Off Topic]

@badcat Done a PR for the missing function - Note though that the declared version is 1.8.0 which will results in an Admin notice being output. @arielk could take care of the PR if it's ok please?

To mitigate that just change the version to 1.7.12 (only when testing with the RC version of Elementor) and you should be good :)

**Comment by KingYes** [comment]
@badcat This is just example plugin for developers to HOWTO write widgets to Elementor. BTW, we merged @norewp PR.

**Comment by tudormnt** [comment]
Everything works as expected. Congrats on this really important feature.

One thing that might prove to be a great addition for certain scenarios is live updating elements with the same setting key as the one which is being modified. If you're rendering the same control value in multiple places it makes sense to update it in all places while typing.

One good example would be having a text separator inside a widget which can be edited inline and should reflect on all text separators being rendered within the template (since they're the same).

In general, without this addition, any widget that renders the same text based control multiple times will fall short.

Hope this makes sense.

**Comment by SniffleValve** [comment]
Bug with the toggle widget. 

First item is open on page load.

Cheers!
Lyle

**Comment by black-eye** [comment]
Seems to work as expected. 
One minor discomfort is, that the toolbar isn't visible unless some text is selected. I would expected to be visible all the time (but I suppose you have some good reason to do it this way). 

It would be handy for 2 situations:
1. For block elements (H1, H2,...), where you wouldn't need to select (at least some of) the text to start formatting.
2. When inspecting the text structure - in long texts I'm used to click inside the headings to find out wheather it's H2 or H3 - to make one example...

No big deal, though.

For some future release It would be handy to have some classic shortcuts - e.g. ctrl+b, ctrl+i, for the starters.

**Comment by SniffleValve** [comment]
@black-eye
You can also bring up the toolbar by double-clicking any text, and triple-clicking will select all of it :)
Cheers!
Lyle

**Comment by black-eye** [comment]
@SniffleValve 
Yes, I know, but it's not that convenient - still one (or half) click more ;-)
But as I said, no big deal there, maybe I'll just have to get used to it.

**Comment by momo-fr** [comment]
I note 2 bugs for me:
- italic does not affect (in the normal editor yes)
- if I put a quote impossible to disable it

**Comment by arielk** [comment]
## v1.8 Beta Version RC2

We just released a new beta version, please update your version to v1.8.0 RC2.

This beta release includes:
- New! - Added new networks to social icons widget (#2670)
- Tweak! - Added compatibility with WP Color for WordPress 4.9 (#2550)
- Tweak! - Added WP version class to the body in the editor
- Fix! - Added Inline editing for icon list (#2616) 
- Fix! - Disable auto expanding for toggle in front-end (Thanks @SniffleValve https://github.com/pojome/elementor/issues/2666#issuecomment-341266872)
- Fix! - Removed Elementor state from My Library
- Fix! - Resolve embed template bug with new `isEdit` property

Please update or download the new version here: https://downloads.wordpress.org/plugin/elementor.1.8.0-RC2.zip

Thanks everyone for your help and feedback!

**Comment by themedleb** [comment]
It would be better to change text format to bold, italic, link, underline, ... with just clicking inside a word one time, not have to select it, that's what Wordpress text editor has natively.

**Comment by norewp** [comment]
There seems to be an assumption that when one clicks on a widget that has inline editing then one intends to change the "text" and therefore the controls should be visible. 

This is not true in all cases and having the controls visible automatically can hinder the user's ability to select the column/section controls (depending on where that text control pops up).
![badux](https://user-images.githubusercontent.com/30980808/32343635-18e44c20-bffc-11e7-9311-9153a7428cfc.png)

**Comment by avermat** [comment]
Couple comments...

1) When I click a widget I would expect the cursor to appear where I click so that I can start editing the text right away. The first time I started using the inline editing I thought it wasn't working. Because for any text block I click, the cursor goes all the way to the end of the content. In some cases, when it's a long text block, the cursor isn't even on my screen, it's below the fold at the end of the content block. The fact that I have to click twice to start editing was a little confusing (and not like other inline editors I've used).

2) There doesn't seem to be consistency with which widgets allow me to add formatting. For example, the icon box doesn't allow me to make any of the heading text or paragraph text bold, italic, or underlined. Same with the button widget (and I'm assuming other widgets). It's a little confusing for an **icon list** widget to allow formatting but not an **icon box** widget. It makes it feel like it's broken.

**Comment by vfxdude** [comment]
One issue is the copy and paste from external source which adds lots of inline styles, but those styles are not applied before clicking out of the inline editor. When I test the [Pen Editor](http://sofish.github.io/pen/), the editor you are using, this doesn't happen. It doesn't paste in any styles, so this is probably a feature you added. It would be best if the styles are applied in the inline editor, without having to click out. And it would be a good idea to have a clear formatting functionality (button in the toolbar or keyboard shortcut). And maybe an option not to copy styles at all.

**Comment by arielk** [comment]
## v1.8 Beta Version RC3 

The final release candidate before 1.8 is going live! 

Please update your beta version to RC3. This beta release includes:
- New! – Added placeholder for empty control
- Fix! - Don't clean style on paste text (thanks @vfxdude)
And a lot of fixes and tweaks for the new version
 
Link to download: https://downloads.wordpress.org/plugin/elementor.1.8.0-RC3.zip

Thanks!

**Comment by norewp** [comment]
Do we have a list of all the modules that have inline editing applied to?

**Comment by arielk** [comment]
@norewp We apply Inline Editing to all 1.8 widgets. We will do this soon as well on all the widgets of E-pro

**Comment by copen8** [comment]
Problem: 
When I choose to edit text and press the Italic button. I can't immediately see the result only when I save and preview the site the changes are visible. Furthermore when I press the italic button I can't "unselect" it if you know what I mean. 👯 

![image](https://user-images.githubusercontent.com/22563132/32458835-f71d6bf0-c32d-11e7-845f-faa5ecb096df.png)

**Comment by arielk** [comment]
@copen8 Is your heading (H2) defined with italic using CSS?

Try changing the HTML tag control to a paragraph and let me know if it resolves the problem.

**Comment by copen8** [comment]
Tried every HTML tag that is available in Elementor. No difference. It don't change and I can't deselect it. 

So if i press on italic once i can't undo it. The text is then wrap it <i> tags and cannot be unselected

**Comment by arielk** [comment]
Which theme are you using?

**Comment by norewp** [comment]
@copen8 Not having those issue on my end so it could be a theme related issue

**Comment by copen8** [comment]
OceanWP

**Comment by arielk** [comment]
Bug confirm with OceanWP :(

**Comment by copen8** [comment]
I tried  inline editing on the heading widget and the text-editor widget. Same result. Once you clicked on italic (button) using the inline-editing it won't change back. Notice I can change it the old fashion way under style  in the editor panel to the left.

**Comment by copen8** [comment]
Many Elementor users use OceanWP. 🦅

**Comment by arielk** [comment]
We added a fix for the conflict with OceanWP and other themes that are adding resets for `<i>` `<u>` `<b>` tags: https://github.com/pojome/elementor/commit/a1615735ed4b035fcf46a16edf3443eb46502501

Thanks @copen8

**Comment by silvioghedin** [comment]
I know the focus of this version is inline editing, but for me will not change anything at all :/

When you guys will update the Posts Widget with custom meta, please is one of the most important widgets, take a look, would be perfect to use ACF on it. Thanks!

**Comment by arielk** [comment]
v1.8 is LIVE!

Thanks everyone for your help!!

**Comment by simrandeep** [comment]
I tried adding inline editing feature to an addon. It works fine when I drag and drop the widget but inline editing is disabled when I click on other section on the same page or if I refresh the page. It's not the case with default Elementor widgets. Am I missing something?
