### ISSUE TITLE
Background videos do not respect YouTube query string params

### ISSUE THREAD

**Issue by Quogmole** [pojome/elementor#2668]
## Description

Adding query string parameters to a YouTube video background image does not have an effect on the video playback properties.

## Steps to reproduce

A video with the url - https://www.youtube.com/watch?v=xxx&start=7&autoplay=1&rel=0&showinfo=0&mute=0 (where xxx is the video id) plays from the beginning and shows related content.

Using the url directly in the browser gives the requested results.

## Environment

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | 5.5.57 |  
PHP Version: | 7.0.24 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 67108864 |  
GD Installed: | Yes |  
Elementor Library: | Connected

**Comment by bainternet** [comment]
Unfortunately its not currently possible to set any parameters for a background video other then the video id . By default we add these:
autoplay=1
rel=0
showinfo=0
mute=0 

And will look at allowing to set the start/end.

thanks for your feedback.
