### ISSUE TITLE
Animated Headline mirrors a letter in a blank space

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#2673]
I found a very special strange behaviour (bug?) in the animated headline widget. Style: Rotating, Animation: Wave. I haven't found this in any of the other animation option and only in Chrome and Opera, not in Firefox and Edge; can't say anything about Safari.
When having a rotating text line which contains a space " " between words, the last letter of the word before the space is displayed (flickering) in the " ". This happens only with small letters like f, i, j, l and t; with capital letter only with I and J; in additon it happens with punctuation marks like . , ; : ! ( ) ", maybe others, too. Strange and only very specific circumstances, but not nice.
![animated headline](https://user-images.githubusercontent.com/14095280/32268530-b5d456a0-beef-11e7-9b51-63f331ad8767.JPG)

**Comment by joshmarom** [comment]
The rotating headline widget was really designed to switch between a list of single words.

We will have a look at this strange issue.

Thank you for reporting.

**Comment by bainternet** [comment]
@HelmutGoebel 

can you provide more details? because we are having a hard time replicating this.

Also can you tell us if it happens only in that language? both the text in the screenshot you uploaded and the site language?

thanks.
