### ISSUE TITLE
Animated Headline - control over animation time

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#2674]
The Animated Headline is a nice widget. I would like to have control over the time the widget needs for the animation. Would that be possible?

**Comment by black-eye** [comment]
+1 for this. 
Animation time control would be very handy. 
And the delay control too. 

Sometimes you need to make a sequence of animations - e.g. underline one word in the first headline and AFTER THAT make a circle around another word in the second headline.

**Comment by arielk** [comment]
I merged this issue with another issue #2457 in the same subject so we could deal with it more efficiently.

Thanks for your feedback!
