### ISSUE TITLE
[BUG] 'Posts Widget' is Retrieving the 'Navigation Widget' Header Items as the Post Excerpt

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2678]
Hey guys,

Only just noticed this!!!

<a href='https://postimages.org/' target='_blank'><img src='https://s1.postimg.org/3w1z9bw4lr/Posts_Widget_Bug.png' border='0' alt='Posts_Widget_Bug'/></a>

<a href='https://postimages.org/' target='_blank'><img src='https://s1.postimg.org/2lz230hd1b/Posts_Widget_Bug_Part._2.png' border='0' alt='Posts_Widget_Bug_Part._2'/></a>

Is there any way around it? :(

Cheers.

**Comment by bainternet** [comment]
@enviedbymost can you provide more details and also copy-paste your system info from the admin panel >> Elementor >> System info at the bottom.

**Comment by enviedbymost** [comment]
Hey bainterest,

As you can see from the screenshots above, the navigation headings are being pulled into the posts widget excerpt. 

I'm not sure how much more detail I can provide? Please let me know.

Here's the system info as per your request.

I look forward to hearing from you!

Cheers.

**Comment by bainternet** [comment]
@enviedbymost 

Thanks but we still can't replicate this issue.

In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
