### ISSUE TITLE
Elementor Pro [BETA] Wont Update on Localhost

### ISSUE THREAD

**Issue by djekanovic** [pojome/elementor#2679]
Hi i wanted to tryout Beta Release on localhost. But i noticed that it wont let me update it. Here is screenshot.
![image](https://user-images.githubusercontent.com/23662556/32311483-20c8e29c-bf99-11e7-84e6-83c7fbb5fdbd.png)

I am running AMPPS for localhost, apache, php 5.6

**Comment by KingYes** [comment]
1) We in beta on Elementor regular not the PRO.

2) Please check your permissions on your install.
