### ISSUE TITLE
Top container element

### ISSUE THREAD

**Issue by Nat-Faeeria** [pojome/elementor#268]
I was thinking that having control over a top section by default would be great. We could precise values as default background color, default padding, etc. 

It is currently possible to do that by putting columns into a section (new sections will be created this way), but it is not that convenient to always use sections this way.

**Comment by arielk** [comment]
You can add default style for any element by custom CSS on your theme..

**Comment by Nat-Faeeria** [comment]
Yes. But we are talking about a plugin that is (if I'm not wrong) conceived not only for the developers, but also for non-technical end-users ...
I'm already using a lot of css in addition of Elementor.
