### ISSUE TITLE
HTML module annoying bug

### ISSUE THREAD

**Issue by luclessard** [pojome/elementor#2681]
## Description

Hi,  

i noticed when editing code inside the html module, that when you expand the panel at it's maximum to the right (about 670px), when i click anywhere on the right side of my code, the selection is thrown to the right making it very difficult to select code for editing.  

I have a screenrecording of the bug 

![s5zurt](https://user-images.githubusercontent.com/10204979/32352725-d1f9dc7e-bff8-11e7-945f-44b334fa3dd5.gif)

## Steps to reproduce

1- click on an html module with lot's of code so that you have to scroll horizontally.
2- Expand the panel to it's maximum width
3- click somewhere in you're code on the right side of the panel

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.1.73
	PHP Version: 7.1.4
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.2
	Site URL: https://pq.org
	Home URL: http://pq.org
	WP Multisite: Yes
	Max Upload Size: 16 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: fr-CA
	Timezone: America/New_York
	Debug Mode: Active

== Theme ==
	Name: Parti Québécois
	Version: 1.0.0
	Author: Luc Lessard
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
	Automatic Featured Images from YouTube / Vimeo
		Version: 1.0.3
		Author: WebDevStudios

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Fast Velocity Minify
		Version: 2.2.1
		Author: Raul Peixoto

	Rotating Tweets (Twitter widget & shortcode)
		Version: 1.9.3
		Author: Martin Tod

	Smart Slider 3 Pro
		Version: 3.2.8
		Author: Nextend

	WonderPlugin Gallery
		Version: 9.3
		Author: Magic Hills Pty Ltd

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

== Network Plugins ==
	Advanced Custom Fields PRO
		Version: 5.5.11
		Author: Elliot Condon

	Asset Queue Manager
		Version: 1.0.3
		Author: Nate Wright

	Captcha
		Version: 4.3.6
		Author: simplywordpress

	Code Embed
		Version: 2.2.2
		Author: David Artiss

	Collapse-O-Matic
		Version: 1.7.6
		Author: twinpictures, baden03

	Custom Favicon
		Version: 1.0.3
		Author: Harish Chouhan

	Custom Field Bulk Editor
		Version: 1.9.1
		Author: SparkWeb Interactive, Inc.

	Default featured image
		Version: 1.6.1
		Author: Jan Willem Oostendorp

	Disable Comments
		Version: 1.7
		Author: Samir Shah

	Disable Emails
		Version: 1.3.0
		Author: WebAware

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.7.12
		Author: Elementor.com

	Elementor Pro
		Version: 1.5.8
		Author: Elementor.com

	Erident Custom Login and Dashboard
		Version: 3.5.4
		Author: Libin V Babu

	Far Future Expiration Plugin
		Version: 1.4
		Author: Tips and Tricks HQ

	File Renaming on upload
		Version: 2.2.2
		Author: Pablo S G Pacheco

	GoodBarber Api
		Version: 1.0.12
		Author: GoodBarber

	Hide My WP
		Version: 5.5.5
		Author: wpWave

	Limit Login Attempts Reloaded
		Version: 2.6.1
		Author: wpchefgadget

	Max Mega Menu
		Version: 2.3.8
		Author: Tom Hemsley

	Monkeyman Rewrite Analyzer
		Version: 1.0
		Author: Jan Fabry

	MultiSite Clone Duplicator
		Version: 1.4.1
		Author: Julien OGER, Pierre DARGHAM, David DAUGREILH, GLOBALIS media systems

	Multisite Enhancements
		Version: 1.4.1
		Author: Frank Bültge

	Network Shared Media
		Version: 0.11
		Author: Joost de Keijzer

	No Browser Nag
		Version: 1.2.2
		Author: Scott Reilly

	PixelYourSite
		Version: 5.0.8
		Author: PixelYourSite

	Post Views Counter
		Version: 1.2.8
		Author: dFactory

	Re-Order - CSS and JS Loading Order
		Version: 0.3
		Author: HTML5andBeyond

	Really Simple CSV Importer
		Version: 1.3
		Author: Takuro Hishikawa

	Redirection
		Version: 2.8.1
		Author: John Godley

	Regenerate Thumbnails
		Version: 2.3.1
		Author: Alex Mills (Viper007Bond)

	Remove Query Strings From Static Resources
		Version: 1.4
		Author: Speed Up My Website, Your WP Expert

	Revision Strike
		Version: 0.6.0
		Author: Steve Grunwell

	Rotating Tweets (Twitter widget & shortcode)
		Version: 1.9.3
		Author: Martin Tod

	Simple History
		Version: 2.18
		Author: Pär Thernström

	SSL Insecure Content Fixer
		Version: 2.4.0
		Author: WebAware

	TinyMCE Advanced
		Version: 4.6.3
		Author: Andrew Ozz

	User Role Editor
		Version: 4.37
		Author: Vladimir Garagulya

	What The File
		Version: 1.5.4
		Author: Never5

	Widget Shortcode
		Version: 0.3.0
		Author: Hassan Derakhshandeh

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WP Mail SMTP
		Version: 0.11.1
		Author: WPForms

	WP User Avatars
		Version: 1.3.0
		Author: John James Jacoby

== Must-Use Plugins ==
	000-control-warnings.php
		Version: 
		Author:

**Comment by bainternet** [comment]
In 1.8 we've added soft-wrapping which should fixed and avoid this issue.

if not please fell free to reopen , and thanks for the feedback.
