### ISSUE TITLE
Request - Elementor THEME

### ISSUE THREAD

**Issue by gaellogan** [pojome/elementor#2682]
I love Elementor, am using it on my site. I would love to see it as a DIY theme too. 
I am currently using DIY Themify, and it was terrific a few months ago - now it's a nightmare. Cannot make any changes without recreating that entire segment. I tried other DIY themes as well, Themify was the best of a bad bunch. Now I have to waste days searching for another theme to replace it.

I'd happily pay for a DIY Elementor theme, because I know how well it works and that I'll get great results..

Please please consider it.

**Comment by bainternet** [comment]
We do keep a list of themes that are compatible with Elementor: https://docs.elementor.com/article/78-themes

Maybe in the future we will develop some kind of blank/skeleton theme.

thanks for the feedback.

**Comment by gaellogan** [comment]
A few weeks later and after going slowly through the list in the link you gave me - trying them out and rejecting each one for various reasons, mainly that the wysiwyg customisation is VERY limited - now I find out Elementor DOES have  exactly what I asked for - that's what Pojo is.  Sheesh, bainternet, why didn't you say so?

**Comment by shimsa** [comment]
Hello,

firstly I'd like to thank you very much for Elementor plugin - the best pagebuilder for styling whole website.
There is one problem I am facing up to. I can not find "holy grail" WordPress theme which is 100% Elementor Pro compatible and as minimalist as possible (no jQuery, Vanilla JavaScript instead), for uncompromising clean and speed.
This theme needs to have availibility for setting web icon, title and meta tag, full width streched layout, Polylang/WPML compatibility and be instalable from WordPress theme catalog. Something like "BlankSlate" theme, but from Elementor creators.

I put in a word for creating this (blank/skeleton) theme.

Thank you for your kindness,

Tom

**Comment by stickypages** [comment]
@shimsa I understand this, as I was trying to find the perfect solution for quite awhile, and none of them fit my every-day needs. That being said, I have built my own, and continually working on it. I have had solid success, with a site i'm working on right now. Every page is loading under 1.2 seconds (without any caching or cdn etc). 

I'm not marketing, i'm not selling. Just found a frustration and thought I would try to fill a need. Feel free to take a peak below. It's integration with Elementor and WP-Types mostly. It might not be all "fancy", but it's working really good for me at the moment. Most the settings are in the 'customizer'.

https://www.stickypages.ca/external_dependants/Sticky-master.zip
https://www.stickypages.ca/external_dependants/Sticky-child.zip

**Comment by shimsa** [comment]
@stickypages Thank you for the template. It's really awesome! Useful settings and does not add any unnecessary code. Works great with Elementor. Are you considering adding it to WordPress repository? That would be wonderful.

Thank you.

Tom
