### ISSUE TITLE
[BUG] Shape Divider edge not inverted in EDGE Browser

### ISSUE THREAD

**Issue by Knieselbert** [pojome/elementor#2683]
Hello hello,

There is a bug with the shape divider widget. The edges dont get inverted in the EDGE browser.

Here is what it looks like in Firefox and Chrome:
![breaker_ff](https://user-images.githubusercontent.com/33346811/32370245-9adf207a-c08c-11e7-9edb-a117d468148c.png)

Here is what i looks like in EDGE:
![breaker_edge](https://user-images.githubusercontent.com/33346811/32370249-9de3f5f2-c08c-11e7-845e-2a5727a73426.png)

Is it possible to patch this? Unfortunately my customer base uses EDGE a lot....

Thanks in advance,
Knieselbert

**Comment by bainternet** [comment]
@Knieselbert 

We are aware of "Edge" browser not being able to flip / invert the "shape dividers" simple because sadly (but not shockingly) they don't support transform/rotate.

So until they do, my best advice is not to use  "Flip" in shape dividers.


Thanks for the feedback.

**Comment by Knieselbert** [comment]
Okay, thank you!
