### ISSUE TITLE
Programatically importing and saving Templates in a page

### ISSUE THREAD

**Issue by abaicus** [pojome/elementor#2684]
Hey guys!

I'm wondering if there is any way I could Import a template inside a page programatically. 

What I want is to redirect the user to a newly created page that has an Elementor template already imported.

Have an awesome day!

**Comment by bainternet** [comment]
I merged this issue with  #417  , which are in the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
