### ISSUE TITLE
BUG: Mobile menu not showing

### ISSUE THREAD

**Issue by LaurensM** [pojome/elementor#2686]
On a clients site (reparatiedienstmpm.nl) the mobile menu was not showing.
When clicked on the 'hamburger' this link shows https://reparatiedienstmpm.nl/#.

I asked around on the OceanWP facebook group and we've come up with this.

Ramon K.
Hey! I have a clue which might lead us to the solution. No promises though. Can you create another page on your site with just the menu in an non-stretched (boxed) section?
Ramon K.
Just to clarify my line of thinking: I see on the console that JQuery points to an expression, "100%", which is breaking the code. So I searched all served scripts to see if any of them was using this expression. Turns out that elementor is using a JSON to set the layout, which contains the expression 100%.

Marva J. L.
Following as have had same issue, am about to make a copy of the site to see what happens when disabling all plugins etc.

Craig K.
You might have got it Ramon K. as the error is Uncaught Error: Syntax error, unrecognized expression: 100%

Laurens M. 
That's it guys.... that works. Just created a test page without the 100% full width setting but with a right sitebar.... mobile menu works.

Ramon K. 
Real nice to hear it! Anyway, you can warn Elementor's team about the issue on: https://github.com/pojome/elementor/issues

Laurens M. 
Ramon Kayo Thank! I will do....

Marva J. L.
Lord Thats good to know, when I raised the issue with them on WP forum they didn't seem to want to know

Can you guys look into this and get beck to me? Thanks in advance!

Kind regards

**Comment by ramonztro** [comment]
![screen shot 2017-11-03 at 13 32 43](https://user-images.githubusercontent.com/3981052/32383700-d2ebc154-c09f-11e7-93ff-b3dbc8eb1e8d.png)
![screen shot 2017-11-03 at 13 32 31](https://user-images.githubusercontent.com/3981052/32383701-d30cff22-c09f-11e7-9905-befe5b15ca92.png)

**Comment by griotsarts** [comment]
I have same error for the homepage

![javascript-error-elementor](https://user-images.githubusercontent.com/21292696/32404033-07a82f0e-c140-11e7-9df6-439b03a260a5.jpg)

**Comment by bainternet** [comment]
@LaurensM 

You seem to be using a 3rd party plugin "NavMenu Addon For Elementor" which is not affiliated with Elementor and we cant really support it.

@ramonztro can you provide more details?

@griotsarts seems like a different issue. can you provide more details?

**Comment by griotsarts** [comment]
Thanks for your reply, the mobile menu isn't working on the site's
homepage, but works on other pages. This began after the recent update of
Elementor and OceanWP There appear to be Javascript errors on homepage

The site was designed by someone else (who stopped responding to the site
owner) and they used Elementor, Beaver Builder and Ocean WP. I'm nervous to
disable any builder plugins as the site is live, so was thinking of copying
the site and then working on the copy offline.

I thought maybe it's to do with the fullwidth issue as someone else
suggested but as this is my first time using any of these builders, as use
other wordpress themes

Marva

**Comment by ramonztro** [comment]
@bainternet The printscreen I've posted is just to help @LaurensM. I've took it from his site.

**Comment by fredsky2003** [comment]
have you tried with the menu that is now embeded in elementor, and so you can disable the plugin "NavMenu Addon For Elementor" ?

**Comment by bainternet** [comment]
@griotsarts can you update your Elementor and see if that solves the problem.

**Comment by griotsarts** [comment]
Hi Raz,

I've updated and still no joy.

I've attached a copy of the screen shot of the error message I now see when
I inspect the front page.

Drop down menu works on all pages except the front page.

Marva

**Comment by bainternet** [comment]
@griotsarts 
I cant see the attached screenshot??

also, can you provide a URL? even better a copy-paste from the admin "system info: panel

**Comment by griotsarts** [comment]
Hi Raz
I will try to do tomorrow morning.
Marva

**Comment by griotsarts** [comment]
Hi Raz

The website url is https://www.womenofthelens.com/

The error only happens on the front/homepage in mobile view
The mobile menu works on all other pages. The other pages don't use
Elementor.

== Server Environment ==
Operating System: Linux
Software: Apache
MySQL version: 5.5.5
PHP Version: 7.0.24
PHP Max Input Vars: 5000
PHP Max Post Size: 96M
GD Installed: Yes
Elementor Library: Connected

== WordPress Environment ==
Version: 4.8.3
Site URL: https://www.womenofthelens.com
Home URL: https://www.womenofthelens.com
WP Multisite: No
Max Upload Size: 96 MB
Memory limit: 40M
Permalink Structure: /%postname%/
Language: en-GB
Timezone: 0
Admin Email: info@eshemedia.co.uk
Debug Mode: Inactive

== Theme ==
Name: OceanWP Child
Version: 1.0
Author: THEMEbly / cmwwebfx
Child Theme: Yes
Parent Theme Name: OceanWP
Parent Theme Version: 1.4.6
Parent Theme Author: Nick

== User ==
Role: administrator
WP Profile lang: en_GB
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

== Active Plugins ==
Advanced Custom Fields PRO
Version: 5.6.1
Author: Elliot Condon

Beaver Builder Plugin (Pro Version)
Version: 1.10.9.2
Author: The Beaver Builder Team

Beaver Themer
Version: 1.0.2.1
Author: The Beaver Builder Team

Custom Field Bulk Editor
Version: 1.9.1
Author: SparkWeb Interactive, Inc.

Customizer Export/Import
Version: 0.7
Author: The Beaver Builder Team

Custom Post Type UI
Version: 1.5.6
Author: WebDevStudios

Duplicate Post
Version: 3.2
Author: Enrico Battocchi

Elementor
Version: 1.8.3
Author: Elementor.com

Ocean Extra
Version: 1.3.7
Author: OceanWP

PowerPack for Beaver Builder
Version: 1.5.1.1
Author: Team IdeaBox - Beaver Addons

Really Simple SSL
Version: 2.5.22
Author: Rogier Lankhorst

Ultimate Addon for Beaver Builder
Version: 1.6.6
Author: Brainstorm Force

Wordfence Security
Version: 6.3.21
Author: Wordfence

WP Smush
Version: 2.7.6
Author: WPMU DEV

WP Super Cache
Version: 1.5.8
Author: Automattic

WP User Avatar
Version: 2.0.9
Author: flippercode

Yoast SEO
Version: 5.7.1
Author: Team Yoast


== Debug ==
Errors:
Error: An "el" #elementor-panel-elements-search-area must exist in DOM
at
https://www.womenofthelens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5
- 22:13466
2017-11-03 18:03 +00:00
x 2 times

TypeError: Unable to get property 'reset' of undefined or null reference
at
https://www.womenofthelens.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.6.5
- 2:55680
2017-10-17 22:07 +00:00

TypeError: Object doesn't support property or method 'showView'
at
https://www.womenofthelens.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.6.5
- 2:55763
2017-10-17 22:07 +00:00

**Comment by bainternet** [comment]
We can't really see where on that page you are actually using elementor,

please contact our support at  support@elementor.com.

**Comment by griotsarts** [comment]
So why does the page show these errors?

== Debug ==
Errors:
Error: An "el" #elementor-panel-elements-search-area must exist in DOM
at
https://www.womenofthelens.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5
- 22:13466
2017-11-03 18:03 +00:00
x 2 times

TypeError: Unable to get property 'reset' of undefined or null reference
at
https://www.womenofthelens.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.6.5
- 2:55680
2017-10-17 22:07 +00:00

TypeError: Object doesn't support property or method 'showView'
at
https://www.womenofthelens.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.6.5
- 2:55763
2017-10-17 22:07 +00:00
…

**Comment by griotsarts** [comment]
Thanks fifor r your feedback. I'm not sure where the original designer used
it for the home page. And they seem to have disappeared. I am just trying
to help the site owner. My first time actually using Elementor so learning
myself

But it's the only page element appears on. Perhaps should just clone the
page and see if I can figure out the problem offline which is what o had
thought to do originally

**Comment by jubinarora** [comment]
If you are using sg optimizer or other optimization plugins then disable Combine JavaScript Files option and purge cache.
Mobile menu will start working.

**Comment by deputt** [comment]
For my site, Combine Javascript was already disabled in SG Optimizer. I had to disable <b>Defer Render-blocking JS</b>.

**Comment by AmjadSaeeddev** [comment]
If you are using any plugin for optimization then You just need to disable Defer Render-blocking JS and CSS and your issue will be solved.

because some files execute from the header.
