### ISSUE TITLE
Support for Elementor Template Shortcode ID and Slug

### ISSUE THREAD

**Issue by smpetrey** [pojome/elementor#2688]
Incoming feature request!

Currently, the support for embedding Elementor Templates via Shortcode is great. However I'd love to see adding support for the post slug. It's a bit easier on the eyes. 

Currently, we can call upon the template via its ID:
```
echo do_shortcode(' [elementor-template id="230"] ');
```

Suggested alternative syntax to call upon the template via its slug:
```
echo do_shortcode(' [elementor-template slug="primary-navigation"] ');
```
I'd love to hear what ya'll think, and welcome any feedback!

**Comment by bainternet** [comment]
@smpetrey 

Thanks for the feedback, But we like to keep it simple and generic as possible.

You can however pull the template object by its slug and use that to get the id:

```php
if ( $template = get_page_by_path( 'YOUR_SLUG', OBJECT, 'elementor_library' ) ){	
    $shortcode = ' [elementor-template id="'.$template->ID.'"] ';
    echo do_shortcode( $shortcode );
} 
```

**Comment by smpetrey** [comment]
@bainternet Thanks for your feedback! I understand. At any rate, your snippet works like a charm. 👌
