### ISSUE TITLE
Image carousel shows red squares

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#269]
i have a image carousel with two pics, they fade and the navigation is on "dots only". But when i get to the dots - out of nowhere - there are two red little sqares (like for navigation?) showing. I think you can press them and switch the pics in the carousel. 
![redsquare](https://cloud.githubusercontent.com/assets/20417555/16878425/cc0feac8-4aac-11e6-907a-1df8c20e3572.jpg)

**Comment by yehudah** [comment]
Try to snapshot the html structure by doing this:
![inspect_element](https://cloud.githubusercontent.com/assets/1655373/16899792/2c4c57ce-4c19-11e6-84c6-c349230caae6.gif)

**Comment by Luxamman** [comment]
<button type="button" data-role="none" role="button" tabindex="0">2</button>

that is the line when chrome highlights the button, more info in the snapshot:
![button](https://cloud.githubusercontent.com/assets/20417555/16902161/dffc4f44-4c56-11e6-96b4-882f3d01b1d6.jpg)

**Comment by yehudah** [comment]
If I understand correct what you snapshot is relevant to second circle ( surround with light orange ).
Can you do it for the red square ?

**Comment by Luxamman** [comment]
`<button type="button" data-role="none" role="button" tabindex="0">2</button>`

that is what it shows me when iam selecting it

**Comment by yehudah** [comment]
Any chance that this is a live page ? really hard to understand, this is the first issue I see on this widget.

**Comment by arielk** [comment]
@Luxamman We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
