### ISSUE TITLE
Instagram to  Elementor Sharing Widget

### ISSUE THREAD

**Issue by fortunella74** [pojome/elementor#2692]
Hello,

It would be great if you could add  Instagram to  Elementor Sharing Widget.

Thanks!

**Comment by bainternet** [comment]
Hi,

can you explain what "Instagram to Elementor Sharing widget" mean??

**Comment by fortunella74** [comment]
Sure, Elemntor has a new widget with share buttons options : Facebook, google+, linkdin, pinterest etc. the only think missing is Instagram...

Thanks!

**Comment by bainternet** [comment]
Thanks for the clarification,

As far as I know Instagram doesn't have an API or anyway to post from outside the app at this point. So unfortunately there is no way to do this right now.

https://stackoverflow.com/a/30542068

However, we do have in our roadmap some kind of widget/gallery that will allow you to display images from Instagram in your site.

 thanks for your feedback.
