### ISSUE TITLE
image carrousel vertical space issue

### ISSUE THREAD

**Issue by fredsky2003** [pojome/elementor#2694]
## Description

when you add an image carousel, using Chrome or Edge (NOT firefox), then you get an HUGE vertical space after. this seem to be because of the theme i use.

## Steps to reproduce
check this page
http://mtl.jardinartcoiffure.com/zoom-sur-le-salon/

here is the trick i'm using :  
inline style with “code HTML” widget…

<style>
.elementor-image-carousel-wrapper,.elementor-slick-slider {
width: 100%;
max-height: 450px;
position: relative;
}
</style>

if you reduce the width of the page, you can see that my trick doesn't work so well in chrome, whereas it's always perfect with firefox

so please add a max-height...

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.51
	PHP Version: 5.6.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.3
	Site URL: http://mtl.jardinartcoiffure.com
	Home URL: http://mtl.jardinartcoiffure.com
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: JARDIN COIFFURE
	Version: 1.0
	Author: Valerie Billoudet
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

== Active Plugins ==
	Yoast SEO
		Version: 5.7.1
		Author: Team Yoast

== Network Plugins ==
	Add From Server
		Version: 3.3.3
		Author: Dion Hulse

	Comet Cache
		Version: 170220
		Author: WebSharks, Inc.

	Compress JPEG & PNG images
		Version: 2.2.6
		Author: TinyPNG

	Contact Form 7
		Version: 4.9.1
		Author: Takayuki Miyoshi

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.7.12
		Author: Elementor.com

	Fast Velocity Minify
		Version: 2.2.1
		Author: Raul Peixoto

	Hummingbird
		Version: 1.6.2
		Author: WPMU DEV

	Image Title Remove
		Version: 1.0
		Author: Slavisa Ristic

	Media Library Categories
		Version: 1.5.6
		Author: Jeffrey-WP

	Redirection
		Version: 2.8.1
		Author: John Godley

	Simple Social Buttons
		Version: 2.0.1
		Author: WPBrigade

	TinyMCE Advanced
		Version: 4.6.3
		Author: Andrew Ozz

	UpdraftPlus - Backup/Restore
		Version: 1.13.12
		Author: UpdraftPlus.Com, DavidAnderson

	WordPress Popular Posts
		Version: 4.0.11
		Author: Hector Cabrera

	Yoast SEO
		Version: 5.7.1
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property 'style' of undefined
			at http://mtl.jardinartcoiffure.com/wp-admin/js/editor.min.js?ver=4.8.2 - 1:694
			2017-10-09 04:39 +00:00

		TypeError: elementorFrontend is undefined
			at http://mtl.jardinartcoiffure.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.6.5 - 2:33287
			2017-08-27 22:24 +00:00
			x 6 times

**Comment by bainternet** [comment]
@fredsky2003 

The Vertical space is obviously caused from your max-height. So you you define custom max height overwrite by css you should define custom max hight for smaller devices via media queries, otherwise you end up with that extra vertical space...

**Comment by fredsky2003** [comment]
"The Vertical space is obviously caused from your max-height". hm... have you read my post : what is clear is that i HAVE TO add a css trick because of elementor issue.

so : 
- fix elementor so that : it doesn't add that extra vertical space + i do NOT HAVE TO use max-height trick to remove it (and not to add it as you responded)

again, i'm there to post relevant issues, not to post something for the fun of it

fred

**Comment by bainternet** [comment]
Thanks again for the clarification, But we cannot replicate the "Issue of HUGE vertical space after" and as you stated probably because of the theme you use.

So what exactly are you asking us to fix?

Please run this little test:
Create a new post with just image carousel widget and a text widget under it using one of the default WordPress themes and report back if you are still seeing that vertical space". and if you do please feel free to reopen this issue.

Now If you want to make sure your (theme specific) "trick" will work better in smaller devices I would suggest again to define a custom height for small viewports.

**Comment by kelnh009** [comment]
I was using a plugin called a3 Lazy Load that created this same issue with Elementor + carousel.

**Comment by walpap** [comment]
Same is happening to me. Using any kind of lazy loading plugin adds a vertical huge space after image carousel.
