### ISSUE TITLE
elementor crazy complex video plugin broke GTmetrix

### ISSUE THREAD

**Issue by fredsky2003** [pojome/elementor#2695]
## Description
hello!
why does elementor use such a complex way to create a video for you tube?
many, many entries and lines of code written: several scripts, several calls to google video, several calsl to API... for each video you add on your website !

this create a very bad score inside GTmetrix.

besides, the first page of this site is long to display
mtl.jardinartcoiffure.com

how about a SIMPLE video widget, or way to really REMOVE all options i don't want when i disable them inside the current widget ??? actually, i seem that all options are present in the code of the page, simply with a "none" attribute.

## Steps to reproduce

[gtmetrix.com](url)
enter this website :   mtl.jardinartcoiffure.com

see "F" score about : browser caching, javascript, consistent URL, request size

![gtmetrix elementor](https://user-images.githubusercontent.com/28629771/32425178-327c34b0-c27f-11e7-867d-5c8d5df15b2a.PNG)

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.51
	PHP Version: 5.6.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.3
	Site URL: http://mtl.jardinartcoiffure.com
	Home URL: http://mtl.jardinartcoiffure.com
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: JARDIN COIFFURE
	Version: 1.0
	Author: Valerie Billoudet
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

== Active Plugins ==
	Yoast SEO
		Version: 5.7.1
		Author: Team Yoast

== Network Plugins ==
	Add From Server
		Version: 3.3.3
		Author: Dion Hulse

	Comet Cache
		Version: 170220
		Author: WebSharks, Inc.

	Compress JPEG & PNG images
		Version: 2.2.6
		Author: TinyPNG

	Contact Form 7
		Version: 4.9.1
		Author: Takayuki Miyoshi

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.7.12
		Author: Elementor.com

	Fast Velocity Minify
		Version: 2.2.1
		Author: Raul Peixoto

	Hummingbird
		Version: 1.6.2
		Author: WPMU DEV

	Image Title Remove
		Version: 1.0
		Author: Slavisa Ristic

	Media Library Categories
		Version: 1.5.6
		Author: Jeffrey-WP

	Redirection
		Version: 2.8.1
		Author: John Godley

	Simple Social Buttons
		Version: 2.0.1
		Author: WPBrigade

	TinyMCE Advanced
		Version: 4.6.3
		Author: Andrew Ozz

	UpdraftPlus - Backup/Restore
		Version: 1.13.12
		Author: UpdraftPlus.Com, DavidAnderson

	WordPress Popular Posts
		Version: 4.0.11
		Author: Hector Cabrera

	Yoast SEO
		Version: 5.7.1
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property 'style' of undefined
			at http://mtl.jardinartcoiffure.com/wp-admin/js/editor.min.js?ver=4.8.2 - 1:694
			2017-10-09 04:39 +00:00

		TypeError: elementorFrontend is undefined
			at http://mtl.jardinartcoiffure.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.6.5 - 2:33287
			2017-08-27 22:24 +00:00
			x 6 times

**Comment by bainternet** [comment]
@fredsky2003 

Elementor uses the simplest method of embedding a youtube video, IFRAME.

We have no control over what happens inside the Iframe so we can't really optimize anything there.

We try to keep the widgets as generic and as light yet still powerful for the vast majority of our users, it may not fall in to all use cases but we do provide options to overcome 99.9% of cases.

You can always use an "HTML widget" and have full control over how the iframe is defined and with what attributes.

As for optimization, again we try and do optimize as much as possible but things like browser cache should be defined and controlled  at a site/server level not not from Elementor.

Thanks for the feedback.

**Comment by bainternet** [comment]
@fredsky2003 

Thanks again for posting your findings.

the implementation described in the article you linked, loads an image and not the video Iframe.
But once you click this image it is replaced by same video Iframe and the inner content of the Iframe is still the same ugly code, which again no one other then Youtube can change.

Now we do have something similar to that if you don't want the iframe to load with page load. 

Insert a video like you normally would,  then add an image overlay to that video and last enable lightbox.

![Imgur](https://i.imgur.com/Ad61afP.png)

This will tell Elementor to initiate the video Iframe only when the overlay is clicked, the only difference is that the video will be played inside a lightbox.

Hope this helps.

**Comment by HartLarsson** [comment]
the same problem if when embedding the video as a div background.
Bring a page from 1s loading to 22s loading on GTMETRIX.
