### ISSUE TITLE
elementor create un-optimized image for its thumbnails

### ISSUE THREAD

**Issue by fredsky2003** [pojome/elementor#2696]
## Description
thumbs created by elementor as jpg and png are not optimized, result in B score in GTmetrix

i guess that those thumbs are created when you add a carousel and/or gallery in a page.

some propositions :  
- use a optimized library to create those thumbs
- allow to place in a directory of my website, where they will not be seen by GTmetrix

## Steps to reproduce

[gtmetrix.com](url)
enter this website : mtl.jardinartcoiffure.com

![gtmetrix elementor thumbs](https://user-images.githubusercontent.com/28629771/32425527-aaf8019c-c281-11e7-9bab-1121283ee937.PNG)

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.51
	PHP Version: 5.6.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.3
	Site URL: http://mtl.jardinartcoiffure.com
	Home URL: http://mtl.jardinartcoiffure.com
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: JARDIN COIFFURE
	Version: 1.0
	Author: Valerie Billoudet
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

== Active Plugins ==
	Yoast SEO
		Version: 5.7.1
		Author: Team Yoast

== Network Plugins ==
	Add From Server
		Version: 3.3.3
		Author: Dion Hulse

	Comet Cache
		Version: 170220
		Author: WebSharks, Inc.

	Compress JPEG & PNG images
		Version: 2.2.6
		Author: TinyPNG

	Contact Form 7
		Version: 4.9.1
		Author: Takayuki Miyoshi

	Duplicate Post
		Version: 3.2
		Author: Enrico Battocchi

	Elementor
		Version: 1.7.12
		Author: Elementor.com

	Fast Velocity Minify
		Version: 2.2.1
		Author: Raul Peixoto

	Hummingbird
		Version: 1.6.2
		Author: WPMU DEV

	Image Title Remove
		Version: 1.0
		Author: Slavisa Ristic

	Media Library Categories
		Version: 1.5.6
		Author: Jeffrey-WP

	Redirection
		Version: 2.8.1
		Author: John Godley

	Simple Social Buttons
		Version: 2.0.1
		Author: WPBrigade

	TinyMCE Advanced
		Version: 4.6.3
		Author: Andrew Ozz

	UpdraftPlus - Backup/Restore
		Version: 1.13.12
		Author: UpdraftPlus.Com, DavidAnderson

	WordPress Popular Posts
		Version: 4.0.11
		Author: Hector Cabrera

	Yoast SEO
		Version: 5.7.1
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property 'style' of undefined
			at http://mtl.jardinartcoiffure.com/wp-admin/js/editor.min.js?ver=4.8.2 - 1:694
			2017-10-09 04:39 +00:00

		TypeError: elementorFrontend is undefined
			at http://mtl.jardinartcoiffure.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.6.5 - 2:33287
			2017-08-27 22:24 +00:00
			x 6 times

**Comment by bainternet** [comment]
@fredsky2003 

To generate thumbnails we use [BFI_Thumb](https://github.com/bfintal/bfi_thumb) script which uses the native WordPress functions to resize images. So if you want to farther optimize the generated thumbs I suggest you use a 3rd party Image Optimization plugin/service. 

Thanks for the feedback.

**Comment by fredsky2003** [comment]
hello bainternet

sorry you are wrong. it is ELEMENTOR itself that create unoptimized images, we agree on that.
now if you are not able to use a optimized library instead of the poor embeded one from wordpress then : 
- add a entry in the elementor config menu to allow me to choose the path where those thumbs are located. so that gtmetrix will not see them
- or works with tiny png author to allow an automatic optimization, again in a specific folder. but this is the last resort, because normaly those thumbnails are ONLY created by and for elementor.
- add a way to clean those thumbs and do NOT recreate them unless i edit the corresponding page.

this is  A IMPORTANT BUG, i'm not here to report something that is easy to fix. 

thanks,
fred

**Comment by bainternet** [comment]
@fredsky2003 

Thanks again for the clarification, like I said above, we use the native functions provided WordPress to generate the specific sizes needed for these widgets via BFI_Thumb script which "caches" the generated thumbs to avoid regenerating theme over and over.

So again we don't see this as a bug simply because it is working as it should.

**Comment by fredsky2003** [comment]
okay, i'm returning from vacations :) i now it is much more clear 👍
the issue is that in fact elementor does create the images in "thumbs" directory - and if you delete them, you got an empty page - which are NOT optimized.

now how can we use "tiny PNG" (or others plugins) to recognize those images... they are NOT even part of the media of wordpress!!! can you make something so that they appears, and then will be optimized by tinypng ?

fred

**Comment by krijmfresj** [comment]
Hey Fred,

Have you found a solution for this? I am also struggling with this one.
The PNGs I upload to my library are 34KB, but on the live site they become 58KB.
No idea why they become bigger true Elementor...

**Comment by fredsky2003** [comment]
Hi, Elementor and krijmfresj

exact same issue still there

![image](https://user-images.githubusercontent.com/28629771/52542331-830e9680-2d6c-11e9-9a45-ea3119cee8c6.png)

so if somebody have a trick with a free plugin to look a those bad thumbs and create good ones, please share!
