### ISSUE TITLE
Overflow: scroll issue

### ISSUE THREAD

**Issue by brianroach** [pojome/elementor#270]
Can't figure out why grid overflow: scroll is adding this white bottom and right side gutter to the Elementor element. Any ideas?
![image](https://cloud.githubusercontent.com/assets/9772694/16891462/a572497c-4aae-11e6-947a-527e754e2967.png)

**Comment by arielk** [comment]
Try to snapshot the HTML structure by doing this:
![inspect_element](https://cloud.githubusercontent.com/assets/1655373/16899792/2c4c57ce-4c19-11e6-84c6-c349230caae6.gif)

**Comment by arielk** [comment]
Hi @brianroach 
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by brianroach** [comment]
I apologize for not getting back to this sooner - was on a time constraint and had to move without Elementor unfortunately. I'll use it in my next project for sure and if I get the same issue I will re-open this one.

Thnaks!
