### ISSUE TITLE
Add RSS button/icon to Social Icon widget

### ISSUE THREAD

**Issue by thechile** [pojome/elementor#2701]
Hi, this is feature request. As well as facebook, twitter.. i want to have the RSS button show that links to my blog RSS feed. This is still a social thing... used by many people e.g. feedly. Can this be added please.

**Comment by Basilakis** [comment]
Actually best case is to have the following Structure:

1. Add Custom Social ( with a repeatable field )
2. There is an option to add Title, Link, Icon Class ( an icon selector can work also )
3. user adds theirs, press save and done.

That allows for users to add anything they want, and keep the functionality of the plugin low as to serve everyone.
