### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by miobook1** [pojome/elementor#271]
after last update doesn't work...doesn't open after clicking edit with elementor
it remains loading the image as you see in the attached snapshot:
![elementor](https://cloud.githubusercontent.com/assets/14021044/16899167/e343a95c-4bf9-11e6-97f0-3f8797957af8.png)

**Comment by yehudah** [comment]
Can you please disable all plugins and just leave elementor active, if this doesn't work activate plugins again and change the theme to wordpress default one.

**Comment by miobook1** [comment]
i've tried to deactivate all plugins, nothing...
then deactivate and reactivate elementor...notihing
do i need to change theme?

**Comment by yehudah** [comment]
Did you try with only elementor activated ?
If that doesn't work change to wordpress default theme.

**Comment by miobook1** [comment]
changed theme and rechanged to first one....doesn't work....i'll wait for next update

**Comment by yehudah** [comment]
When you edit and stuck press F12, select the console tab and refresh the page, any errors on that tab ?

**Comment by miobook1** [comment]
i've tried...on existing and new article...nothing.

**Comment by yehudah** [comment]
Can you go to the menu  - elementor --> sysinfo, and paste the output to a service like pastebin.com ?

**Comment by miobook1** [comment]
I’ve put on pastern…..

miobook

----------------------
MioBook.

Social Profile
Linkedin

Il giorno 17 luglio 2016 @ 11:32:19, Yehuda Hassine (notifications@github.com) ha scritto:

Can you go to the menu - elementor --> sysinfo, and paste the output to a service like pastebin.com ?

**Comment by yehudah** [comment]
Link ?

**Comment by miobook1** [comment]
http://pastebin.com/u/miobook/1/?guest=1


Il giorno 20 luglio 2016 @ 14:13:24, Yehuda Hassine (notifications@github.com) ha scritto:

Link ?

**Comment by arielk** [comment]
Can you please update to the latest version released today and see if it worked?

**Comment by miobook1** [comment]
It still remain in loading…doesn’t work


----------------------
MioBook.

Social Profile
Linkedin

Il giorno 25 luglio 2016 @ 19:24:39, Ariel Klikstein (notifications@github.com) ha scritto:

Can you please update to the latest version released today and see if it worked?

**Comment by yehudah** [comment]
If you can share your credentials, please write us to: support@elementor.com
and we will try to help you.

**Comment by FahadKhalique** [comment]
i was facing the same problem after updating Elementor to 0.6.1 but deactivating the Autoptimize plugin helped me out.

**Comment by miobook1** [comment]
Which is the autoptimize  plugin? 
--
Inviato da myMail per Android Mercoledì, 27 Luglio 2016, 11:55AM +02:00 da FahadKhalique  notifications@github.com :

**Comment by FahadKhalique** [comment]
@miobook1 

Please follow the link below for Autoptimize plugin
https://wordpress.org/plugins/autoptimize/

This plugin helps you to optimize all css and js into one file.
