### ISSUE TITLE
[Feature request] Inline editor image options

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#2710]
I'm really excited about this new inline editor feature! 
And I have one extra tip for another greatness improving feature > style options for inline images. :-)

No big deal I cannot insert an image using the inline editor, I can do that in the native TinyMCE box. But it would be superb, to have some styling options available in the inline editor. Alignment for the starters (yeah, I know, I could do that in the "big" editor, no big deal). But what about the margins or paddings? Or the size (in px, %, em)?

And (OH MY!), what if all these options were responsible! I would be able to set the different size, padding or alignment for every inline picture on each viewport! Wouldn't it be great? 

For now it seems, that the inline editor can realize an image somehow, it can even resize it (don't know if this feature is WP controlled or Elementor controlled). But the toolbar seems to be more text related than image related (there's a list option, for example).

![obrazek](https://user-images.githubusercontent.com/5634870/32512090-21c570dc-c3f6-11e7-97be-23d300dcfc14.png)

Excellent work, keep improving Elementor this way!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we are always looking to upgrade, tweak and evolve our features, so we will look into it in the future.

Thanks for the feedback.
