### ISSUE TITLE
Global widget: show widget name

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#2711]
Every Pro user loves the global widget feature. But sumetimes, when you click on a global widget, you don't know which one you have choosen. So it would be great to have the name, for instance, to reuse it in another section or another page. Could you display the name of the global widget, when selected? Maybe in the position, I indicated yellow. 
![grafik](https://user-images.githubusercontent.com/14095280/32519904-84a77124-c40e-11e7-99ef-939403b3ceb6.png)

**Comment by bainternet** [comment]
That would be nice and we do have some plans to extend and tweak the whole global widgets / template library on our roadmap.

thanks for the suggestion.

**Comment by bainternet** [comment]
I merged this issue with  #1578, which are on the same subject in general so we could deal with it more efficiently. 

Please feel free to continue the conversation there.

Thanks for your feedback!
