### ISSUE TITLE
[bug] Could not find template: "#tmpl-elementor-repeater-row"

### ISSUE THREAD

**Issue by andreasnrb** [pojome/elementor#2712]
## Description
Editing is broken due to Marionette not finding #tmpl-elementor-repeater-row.
	Errors: 
		NoTemplateError: Could not find template: "#tmpl-elementor-repeater-row"
		at  http://testing.test/app/plugins/elementor/assets/lib/backbone/backbone.marionette.js?ver=2.4.5 - 1627:9 2017-11-08 13:49 +00:00 x 9 times
loadTemplate @ backbone.marionette.js?ver=2.4.5:1627
load @ backbone.marionette.js?ver=2.4.5:1612
get @ backbone.marionette.js?ver=2.4.5:1574
100.elementor-behaviors/inner-tabs @ editor.js?ver=1.8.0:sourcemap:8905
s @ editor.js?ver=1.8.0:sourcemap:2
(anonymous) @ editor.js?ver=1.8.0:sourcemap:2
101.elementor-models/base-settings @ editor.js?ver=1.8.0:sourcemap:9031
s @ editor.js?ver=1.8.0:sourcemap:2
(anonymous) @ editor.js?ver=1.8.0:sourcemap:2
27.elementor-editor-utils/ajax @ editor.js?ver=1.8.0:sourcemap:1574
s @ editor.js?ver=1.8.0:sourcemap:2
e @ editor.js?ver=1.8.0:sourcemap:2
(anonymous) @ editor.js?ver=1.8.0:sourcemap:2				
## Steps to reproduce
Update to version 1.8

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website + FTP access, and our support team will try to assist.

**Comment by Klemart3D** [comment]
Similar to #2537

**Comment by bainternet** [comment]
Thanks for reporting, should be fixed in 1.8.1
