### ISSUE TITLE
Full screen background video does not resize correctly

### ISSUE THREAD

**Issue by francallen** [pojome/elementor#2713]
Hi there,

having the same problem with the fullscreen background videos in a section like [dollhauss in May (Issue 1737)](https://github.com/pojome/elementor/issues/1737),I would like to ask if there's any solution to fix this.

Background infos:
– There's a section in a page, using a Background video.
– JS full with switch is enabled.
– By resizing the window, the videos height isn't resizing to the full height of the section. The background fallback image is correctly-sized. So it doesn't look well because the overlaying video height is smaller then the background fallback image height.
– By refreshing the page the background video is allright.

I've currently updated Elementor to version 1.8.0.

Thanks a lot.

**Comment by bainternet** [comment]
The Image and the video resizing work in different manners and while the image resizing can naturally pick up the changes in the viewport for videos it's just not the same.

The ultimate fail-safe way to guarantee the video resizing working correctly would be refreshing the whole page on resize but **you really don't want that**.

So if its working fine on a  refresh it means its working as it should.

thanks for the feedback.

**Comment by shazahm1** [comment]
I fixed by adding a custom class, `header-background-video-stretch`, to the container and using this CSS

``` css
.header-background-video-stretch video.elementor-html5-video {
	width: 3425px !important;
	height: 100% !important;
}
```

Seems fine in Chrome and Firefox. Edge and IE, not so much but I do not think the video backgrounds stretch to fit in those browsers anyway.

I've noticed themes which have video background have a script that runs on resize which adjusts the video element width. Here's one example:

https://demos.churchthemes.com/saved/

**Comment by AnthonyParagon** [comment]
Hi @shazahm1 how did you add the custom class, and where?

Thanks!

**Comment by shazahm1** [comment]
@AnthonyParagon 

This is an option within Elementor. her's the link to their doc page with an example (so-yellow):

- https://elementor.com/help/how-to-use-selector-in-the-custom-css-tab/

**Comment by AnthonyParagon** [comment]
@shazahm1 Wow! Thanks for the quick response!

**Comment by miladpaak** [comment]
jsut use this css code

.elementor-widget-video .e-hosted-video .elementor-video {
    -o-object-fit: cover;
    object-fit: contain;
}

**Comment by cashox** [comment]
.header-background-video-stretch video.elementor-html5-video {
	width: 3425px !important;
	height: 100% !important;
}

this worked nicely but had to update code to match current nomenclature for elementor video box to this: 

.elementor-background-video-container video.elementor-html5-video {
	width: 3425px !important;
	height: 100% !important;
}

@miladpaak  that didnt work when i tried it - looked neater code-wise, but just didnt do anything.
