### ISSUE TITLE
External CSS Images not changing to HTTPS

### ISSUE THREAD

**Issue by katart** [pojome/elementor#2715]
## Description

I'm getting the following error in Google developer tools console:

`Mixed Content: The page at 'https://www.guill.com/staging/capabilities/engineering-capabilities/' was loaded over HTTPS, but requested an insecure image 'http://www.guill.com/wp-content/uploads/paper-1-300.jpg'. This content should also be served over HTTPS.`

I recently converted the WordPress Address and the Site Address to an HTTPS URL and also added `define( 'FORCE_SSL_ADMIN', true );` via the iThemes Security plugin.

I also clicked Regenerate Files AND Replaced URLs from HTTP to HTTPS (which affected 0 rows) within Elementor Tools

Any ideas how to resolve this?

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.18 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
	MySQL version: 5.5.5
	PHP Version: 5.6.18
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.3
	Site URL: https://www.guill.com/staging
	Home URL: https://www.guill.com/staging
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Guill Tools
	Version: 1.0.0
	Author: KatArt Graphics
	Child Theme: Yes
	Parent Theme Name: KAG Default
	Parent Theme Version: 2.0
	Parent Theme Author: KatArt Graphics

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3260.2 Safari/537.36

== Active Plugins ==
	ACF: Bidirectional Relationship Field
		Version: 0.1.0
		Author: Ben Steers

	Advanced Custom Fields PRO
		Version: 5.6.5
		Author: Elliot Condon

	AnyWhere Elementor Pro
		Version: 2.4.1
		Author: WebTechStreet

	BackupBuddy
		Version: 8.1.1.0
		Author: iThemes

	Custom Post Type UI
		Version: 1.5.5
		Author: WebDevStudios

	Easy Twitter Feed Widget
		Version: 0.8
		Author: DesignOrbital.com

	Elementor
		Version: 1.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 1.9.3
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.5
		Author: Till Krüss

	Enhanced Media Library
		Version: 2.4.5
		Author: wpUXsolutions

	Google Analytics for WordPress by MonsterInsights
		Version: 6.2.4
		Author: MonsterInsights

	Google Language Translator
		Version: 5.0.33
		Author: Rob Myrick

	Gravity Forms
		Version: 2.2.5
		Author: rocketgenius

	Gravity Forms MailChimp Add-On
		Version: 4.2.4
		Author: rocketgenius

	Guill Cards
		Version: 0.1.0
		Author: Ben Steers

	iThemes Security
		Version: 6.7.0
		Author: iThemes

	Kint Debugger
		Version: 1.2
		Author: Brian Fegter, Chris Dillon

	Master Slider Pro
		Version: 3.2.0
		Author: averta

	Max Mega Menu
		Version: 2.4
		Author: Tom Hemsley

	Nested Pages
		Version: 2.0.3
		Author: Kyle Phillips

	Nopage
		Version: 0.1.0
		Author: Ben Steers

	Redirection
		Version: 2.9.1
		Author: John Godley

	Scripts n Styles
		Version: 3.4.4
		Author: unFocus Projects

	Social Icons Widget by WPZOOM
		Version: 3.0.5
		Author: WPZOOM

	Sticky Side Buttons
		Version: 1.0.3
		Author: EnigmaWeb

	TablePress
		Version: 1.8.1
		Author: Tobias Bäthge

	The Events Calendar
		Version: 4.6.3
		Author: Modern Tribe, Inc.

	Vulnerable Plugin Checker
		Version: 0.3.11
		Author: Storm Rockwell

	wpDataTables
		Version: 2.0.1
		Author: TMS-Plugins

	WP Smush
		Version: 2.7.6
		Author: WPMU DEV

	Yoast SEO
		Version: 5.7.1
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: n.slick is not a function
			at http://www.guill.com/staging/wp-content/plugins/elementor-pro/assets/js/editor.min.js - 2:24017
			2017-11-01 16:43 +00:00
			x 13 times

		TypeError: elementor.channels.panelElements.request(...) is undefined
			at http://www.guill.com/staging/wp-content/plugins/elementor/assets/js/editor.min.js - 2:108552
			2017-11-01 16:01 +00:00
			x 20 times

		TypeError: n.slick is not a function
			at http://www.guill.com/staging/wp-content/plugins/elementor-pro/assets/js/editor.min.js - 2:24017
			2017-11-01 15:51 +00:00
			x 11 times

		TypeError: Cannot read property 'removeClass' of undefined
			at http://www.guill.com/staging/wp-content/plugins/elementor/assets/js/editor.min.js - 2:104207
			2017-10-10 18:32 +00:00

		TypeError: n.slick is not a function
			at http://67.227.192.83/~guillco/wp-content/plugins/elementor-pro/assets/js/editor.min.js - 2:24017
			2017-10-10 04:53 +00:00

**Comment by bainternet** [comment]
@katart 

Can you try to re-select/re-insert these images and saving, this should force a CSS refresh to that specific page.

**Comment by katart** [comment]
@bainternet That does work, but this is a very large site with many images. Is there a way within Elementor? or would a DB Search/Replace plugin be necessary?

**Comment by bainternet** [comment]
A DB Search-replace plugin will do about the same as the "Update Site Address" tool.

The problem is that it did not find any matches to replace "(which affected 0 rows)" which means it cannot replace the links if it cant find them.

I would advise you to try again replacing the links via Update Site Address tool and then Regenerate CSS.

If that still gets you the same result then In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
