### ISSUE TITLE
Getting elementor uinique class 

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#2720]
By default elementor add unique class like `elementor-element elementor-element-nuly0t5 lae-team-members-style-one elementor-widget elementor-widget-lae-team-members` so I guess the value is stored in {{WRAPPER}} . 
Now how can get that unique class inside content ie `elementor-element-nuly0t5` or `nuly0t5`

**Comment by bainternet** [comment]
@webangon 

The unique class is randomly generated so there is no way of knowing it in advance.
But you . can always add your own custom class to a widget.
