### ISSUE TITLE
[Bug] Can't export templates after upgrading to 1.8.1

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#2722]
I've upgraded to 1.8.1 on two different sites and am experiencing the same issue on both when trying to export Elementor templates. I get the following error:

**{"success":false,"data":[{"code":"token_expired","message":""}]}**

When I roll back to the previous version of Elementor everything works fine.

**Comment by KingYes** [comment]
Fixed by #2721

Thanks!

**Comment by WPDevHQ** [comment]
@KingYes This issue persists in v1.8.2!

**Comment by avermat** [comment]
Exporting works now, but importing does not. I'm getting the following error with 1.8.2:

**{"success":false,"data":[{"code":"token_expired","message":""}]}**

**Comment by bainternet** [comment]
Please try updating to 1.8.3 and feel free to reopen if issue persists.
