### ISSUE TITLE
Optimizing embedded Youtube element

### ISSUE THREAD

**Issue by rami48** [pojome/elementor#2724]
A video element in Elementor will load the player JS in advance.
It will add more than 500KB to the page code, though hurting the user experience and the SEO.
A solution would be to load the player heavy code only after the video is clicked.
There is a cover picture configuration in elementor for youtube video, but it doesn't prevent the heavy JS loading.
Can such optimization mode be provided?
Thanks.

**Comment by bainternet** [comment]
@rami48 

We do currently have a more "optimized" option if you define an image overlay for your video and enabled the lightbox.

let me know if that work for you.

**Comment by rami48** [comment]
It works!  Thanks.
    On Saturday, November 11, 2017, 7:44:42 PM GMT+2, raz ohad <notifications@github.com> wrote:  
 
 
@rami48

We do currently have a more "optimized" option if you define an image overlay for your video and enabled the lightbox.

let me know if that work for you.

**Comment by bainternet** [comment]
👍
