### ISSUE TITLE
Editor of widget loading limitless

### ISSUE THREAD

**Issue by Gregorianpics** [pojome/elementor#2725]
Hi, today i updated to the new version of elementor. Since the new update (1.8.2) the editor of some widget doesn't stop loading, when I click edit on the right side. How can I solve this problem? I already tried by deactivating and reactivating the plugin.

**Comment by suganyaselvakumar** [comment]
exactly I'm also facing the same problem after updating v.1.8.2.

**Comment by arielk** [comment]
Fix for 1.8.3 #2732
