### ISSUE TITLE
Form Fields only show required asterix in label, not in placeholder if label is disabled

### ISSUE THREAD

**Issue by thechile** [pojome/elementor#2726]
Hi
 
When i add a form with several fields and hide the labels.. enabling the 'Required' option does nothing because the asterix is only shown on the label. Can it be changed so if the label is hidden and  Required is enabled that the asterix can be shown within the text fields beside the Placeholder ?

Thanks

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future as we are always looking to improve.

Thanks for the feedback.
