### ISSUE TITLE
Countdown timer, allow automatic reset and triggers

### ISSUE THREAD

**Issue by thechile** [pojome/elementor#2727]
Hi

I would like to use the countdown timer as monthly prize draw countdown. As this will happen every month i would like 

a) that on the first day of each month the countdown is reset automatically 
b) that at the end of the month i can specify a trigger such as Zapier or any url 

thanks

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future as we are always looking to improve.

For now, your request is very use-case specific and you would need a 3rd party plugin or custom coding to get that done.

Thanks for the feedback.
