### ISSUE TITLE
[Feature Request] Disable Elementor post state display via filter

### ISSUE THREAD

**Issue by clickharder** [pojome/elementor#2728]
Elementor 1.8.0 introduced post states for all Elementor pages on the post/page table.  This is fine and potentially useful if you are only using Elementor on a few pages.  However, if you are using Elementor on all of your pages, it adds clutter to the post table display making it harder to find draft posts and specific pages. 

This code is found here:
/includes/admin.php on lines 198-203

It would be nice if there was a filter added to this function to hide the display of the post state. Perhaps something like this:

`public function add_elementor_post_state( $post_states, $post ) {`

        $enable_post_status_visibility = apply_filters( 'elementor_post_status_visibility', true );

        if ( User::is_current_user_can_edit( $post->ID ) && Plugin::$instance->db->is_built_with_elementor( $post->ID ) && $enable_post_status_visibility ) {

            $post_states['elementor'] = __( 'Elementor', 'elementor' );

        }

        return $post_states;

    }

This would allow us to turn off the post state from within the functions.php file of our theme using the following:

`add_filter( 'elementor_post_status_visibility', '__return_false' );`

I have tested this on version 1.8.0 and it appears to work fine.

**Comment by KingYes** [comment]
You can remove this by this code: https://github.com/pojome/elementor/blob/30a8ce5ec3a4e48b133a0ed3d4c33b72392d2ab7/includes/template-library/sources/local.php#L535-L540
