### ISSUE TITLE
WP widget are not working in elementor editor - V1.8.2

### ISSUE THREAD

**Issue by suganyaselvakumar** [pojome/elementor#2732]
Hi,

Version1.8.2 - WP widget are not working in elementor editor but elementor widget working good. if I try to edit it keep loading.

**Comment by AndersGegenstroem** [comment]
Not sure, if you mean the same, but I experienced that widget forms in elementor editor do not show up. I think it is related to the condition in "includes/managers/widgets.php:240", which says
`if ( Plugin::$instance->editor->verify_request_nonce() ) {
  die;
}`
or in other words: When you have a valid nonce, do not send any content back. I checked all nonces and they are valid.

**Comment by arielk** [comment]
I can confirm this bug, we will release a patch soon.

Thanks for your report!
