### ISSUE TITLE
Form Widget: textarea fields don't preserve line breaks

### ISSUE THREAD

**Issue by sanna-woo** [pojome/elementor#2734]
Hi!

## Description

I've a contact form with a textarea field built via the elementor form widget. After submitting the form and receiving the message, the content of the textarea lost its line breaks.

Expected behaviour: preserve the line breaks

## Environment
Wordpress: v4.8.3
Elementor: v1.8.2
Elementor Pro: v1.9.5 

Thank you!

**Comment by bainternet** [comment]
@sanna-woo 

can you copy-paste your system info from the plugin admin so we can get more info, currently we cant replicate the described issue.

**Comment by bainternet** [comment]
Also if possible, please add a screenshot of the received Email.

**Comment by sanna-woo** [comment]
@bainternet

Thank you for the reply!

Here are two screenshots (contact form, and received email)
(btw., when setting the form to "text only", the line breaks work as expected)

![eins](https://user-images.githubusercontent.com/33070450/32700121-e452fda4-c7c0-11e7-916c-436104529c85.JPG)
![email](https://user-images.githubusercontent.com/33070450/32700122-e46f5c56-c7c0-11e7-9358-1e463b512a2c.JPG)


(The Contact Form 7 Plugin listed below is used for another part of my page).
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.5
	PHP Version: 5.6.31-6+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8.3
	Site URL: http://--
	Home URL: http://--
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: --
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.0.30
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.59
		Author: ServMask

	Auto Hide Admin Bar
		Version: 1.2.4
		Author: Marcel Bootsman

	Contact Form 7
		Version: 4.9.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 1.8.3
		Author: Elementor.com

	Elementor Pro
		Version: 1.9.5
		Author: Elementor.com

	Header Footer Elementor
		Version: 1.0.5
		Author: Brainstorm Force, Nikhil Chavan

	Password Protected
		Version: 2.1
		Author: Ben Huson


== Debug ==
	Errors: 
		TypeError: Cannot read property 'removeClass' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:104207
			2017-10-12 11:00 +00:00
			x 2 times

		TypeError: Cannot read property 'errors' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:110752
			2017-10-12 08:41 +00:00
			x 8 times

		TypeError: Cannot read property 'removeClass' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:104207
			2017-10-05 10:13 +00:00
			x 2 times

		TypeError: Cannot read property 'removeClass' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.6 - 2:104204
			2017-10-03 11:21 +00:00
			x 5 times

		TypeError: Cannot read property 'errors' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.6 - 2:110749
			2017-10-02 10:14 +00:00
			x 4 times

		TypeError: Cannot read property 'removeClass' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.6 - 2:104204
			2017-10-02 08:21 +00:00
			x 4 times

		TypeError: Cannot read property 'init' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.6 - 2:27487
			2017-09-27 17:40 +00:00
			x 6 times

		TypeError: Cannot read property 'errors' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.6 - 2:110749
			2017-09-27 10:14 +00:00
			x 2 times

		TypeError: Cannot read property 'init' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.6 - 2:27487
			2017-09-27 06:33 +00:00

		TypeError: Cannot read property 'init' of undefined
			at http://--/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.5 - 2:27487
			2017-09-26 17:02 +00:00
			x 4 times

**Comment by bainternet** [comment]
Few questions:

- are you using the "Send As" with HTML or text?
- what Email client are you using?
- can you check if this happens to you when you send to a web client eg: Gmail?

**Comment by sanna-woo** [comment]
> are you using the "Send As" with HTML or text?
It only happens when using HTML Email. When using text email, the line breaks work as expected.

> what Email client are you using?
> can you check if this happens to you when you send to a web client eg: Gmail?

I'm using Mozilla Thunderbird. I've just tried gmail and another web client, where the same problem occurs.
I can also tell that the line breaks work as expected (HTML Email) when using another form plugin (contact form 7). So it probably isn't an email client issue ...

**Comment by bainternet** [comment]
@sanna-woo 

One last thing we need to debug this, can you forward the received email to our support ( support@elementor.com )  or paste here the source of the email we need to look at the headers that were sent.

Currently, we can't replicate the issue so that's why I keep asking you for more details.

**Comment by marciopraxedes** [comment]
Check https://docs.elementor.com/article/280-sending-email-confirmations

**Comment by webschmitt** [comment]
Probably simply there is missing a PHP function like nl2br($textarea_content) for the text-area-fields, if HTML is selected.
Not difficult to fix.

**Comment by mikeprince** [comment]
This problem still exists

**Comment by projectpi-ca** [comment]
Still not fixed in 2021.

**Comment by synio-wesley** [comment]
It looks like `elementor-pro/modules/forms/actions/email.php` in `replace_content_shortcodes` function does add the HTML line breaks if you add the `[all-fields]` shortcode, but it won't do it for your own fields.

The `replace_setting_shortcodes` function in `elementor-pro/modules/forms/classes/form-record.php` should also accept the `$line_break` parameter and handle it similarly...

I could add a PR to fix this if that helps... (but it's a simple enough fix...)

**Comment by synio-wesley** [comment]
Oh, and here's a workaround that I've just created and that I'm now using myself:

```
add_action('elementor_pro/forms/process/textarea', function($field, $record, $ajax_handler) {
    $settings = $record->get('form_settings');
    $send_html = 'plain' !== $settings['email_content_type'];
    if ($send_html) {
        $record->update_field($field['id'], 'value', nl2br($field['value']));
    }
}, 10, 3);
```

Basically, it adds the `<br>` HTML tags for `textarea` fields if your `email_content_type` is not `plain`

**Comment by synio-wesley** [comment]
> Novice here, where do I paste this code? Thanks

If you have a custom child theme, then a good place would be in `functions.php` of that child theme. If you don't have a child theme, you could create one. (Or you could create a small plug-in featuring this code.) An even simpler option could be a plugin that allows you to add PHP snippets. Something like this for example: https://wordpress.org/plugins/code-snippets/

**Comment by Positive-ID** [comment]
> > Novice here, where do I paste this code? Thanks
> 
> If you have a custom child theme, then a good place would be in `functions.php` of that child theme. If you don't have a child theme, you could create one. (Or you could create a small plug-in featuring this code.) An even simpler option could be a plugin that allows you to add PHP snippets. Something like this for example: https://wordpress.org/plugins/code-snippets/

That's fantastic!!! It's worked!!! Thank you so much!!! If Elementor fix this issue will this code cause problems?

**Comment by synio-wesley** [comment]
> That's fantastic!!! It's worked!!! Thank you so much!!! If Elementor fix this issue will this code cause problems?

If Elementor fixes this issue (but I doubt it, since this issue was reported back in 2017) then it would be best to remove this custom code. However, it probably won't cause a big issue (it could perhaps cause extra newlines in that case though).

**Comment by Positive-ID** [comment]
> > That's fantastic!!! It's worked!!! Thank you so much!!! If Elementor fix this issue will this code cause problems?
> 
> If Elementor fixes this issue (but I doubt it, since this issue was reported back in 2017) then it would be best to remove this custom code. However, it probably won't cause a big issue (it could perhaps cause extra newlines in that case though).

No problem, thank you very much indeed for your help!

**Comment by okkine** [comment]
> Oh, and here's a workaround that I've just created and that I'm now using myself:
> 
> ```
> add_action('elementor_pro/forms/process/textarea', function($field, $record) {
>     $settings = $record->get('form_settings');
>     $send_html = 'plain' !== $settings['email_content_type'];
>     if ($send_html) {
>         $record->update_field($field['id'], 'value', nl2br($field['value']));
>     }
> }, 10, 2);
> ```
> 
> Basically, it adds the `<br>` HTML tags for `textarea` fields if your `email_content_type` is not `plain`

Is there anything I might have to change? I get a "parsing error" when I use it....

**Comment by synio-wesley** [comment]
> > Oh, and here's a workaround that I've just created and that I'm now using myself:
> > ```
> > add_action('elementor_pro/forms/process/textarea', function($field, $record) {
> >     $settings = $record->get('form_settings');
> >     $send_html = 'plain' !== $settings['email_content_type'];
> >     if ($send_html) {
> >         $record->update_field($field['id'], 'value', nl2br($field['value']));
> >     }
> > }, 10, 2);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Basically, it adds the `<br>` HTML tags for `textarea` fields if your `email_content_type` is not `plain`
> 
> I'm having the same problem with missing line breaks. Is there anything I might have to change? I get a "parsing error" when I use it....

No, that should be it. Maybe you copy/pasted it somewhere wrong? If you get a parsing error, check the exact error and context where the error appears. Copy/paste the error and portion of the code where the error happens here if you want us to take a quick look.

**Comment by okkine** [comment]
> No, that should be it. Maybe you copy/pasted it somewhere wrong? If you get a parsing error, check the exact error and context where the error appears. Copy/paste the error and portion of the code where the error happens here if you want us to take a quick look.

Hmm... I'm pasting it exactly as is into functions.php. I've also noticed that the code is displayed in a white bar at the top of the page (even when logged out), as well as on the wp-admin page. Sometimes it's the ONLY thing displayed on the wp-admin page.

Would the theme make a difference? I'm curruntly using a Hello Elementor child theme.

Error Message
![Capture1](https://user-images.githubusercontent.com/27580256/127428620-58ad683a-e7f1-48af-8424-49cf61794ee1.PNG)

Code displayed at top of website
![Capture2](https://user-images.githubusercontent.com/27580256/127429118-3dfe9163-2055-409f-b7c0-7d7a091b1b04.PNG)
<br>
<br>


Code displayed in wp-admin.
![Capture3](https://user-images.githubusercontent.com/27580256/127429124-d5a4f4be-c19a-4a9e-8a57-142461bfab36.PNG)

**Comment by projectpi-ca** [comment]
> > No, that should be it. Maybe you copy/pasted it somewhere wrong? If you get a parsing error, check the exact error and context where the error appears. Copy/paste the error and portion of the code where the error happens here if you want us to take a quick look.
> 
> Hmm... I'm pasting it exactly as is into functions.php. I've also noticed that the code is displayed in a white bar at the top of the page (even when logged out), as well as on the wp-admin page. Sometimes it's the ONLY thing displayed on the wp-admin page.
> 
> Would the theme make a difference? I'm curruntly using a Hello Elementor child theme.
> 
> Error Message
> ![Capture1](https://user-images.githubusercontent.com/27580256/127428620-58ad683a-e7f1-48af-8424-49cf61794ee1.PNG)
> 
> Code displayed at top of website
> ![Capture2](https://user-images.githubusercontent.com/27580256/127429118-3dfe9163-2055-409f-b7c0-7d7a091b1b04.PNG)
> 
> 
> 
> 
> Code displayed in wp-admin.
> ![Capture3](https://user-images.githubusercontent.com/27580256/127429124-d5a4f4be-c19a-4a9e-8a57-142461bfab36.PNG)

Does the file start with <?php

**Comment by okkine** [comment]
> Does the file start with <?php

I can't believe that I was THAT stupid... it's been a while... working now. 🤣

Thanks!

**Comment by okkine** [comment]
> Does the file start with <?php

I can't believe that I was THAT stupid... it's been a while... working now. 🤣

Thanks!

**Comment by brettdonald** [comment]
> @sanna-woo
> 
> One last thing we need to debug this, can you forward the received email to our support ( [support@elementor.com](mailto:support@elementor.com) ) or paste here the source of the email we need to look at the headers that were sent.
> 
> Currently, we can't replicate the issue so that's why I keep asking you for more details.

@bainternet -- I was having this exact problem yesterday. Applied @synio-wesley's fix, and that resolved the problem. Anything I can do to help get this fixed in Elementor, I will do. What do you need?

**Comment by kevinee007** [comment]
Excellent code! :) Thank you very much!!
You saved my time!!!  @synio-wesley

**Comment by CharlesRakesh** [comment]
https://github.com/CharlesRakesh/Elementor-Pro-Form/issues/1

I have an issue in Elementor pro form module textarea field. Email type is HTML send as, when i am sending a mail through that form, and i am adding message in textarea and using Enter to line break it's showing in form, but when i am sending that mail there is no line break in mail.

Can anyone help me how to solve that problem.

**Comment by CharlesRakesh** [comment]
> Also if possible, please add a screenshot of the received Email.

https://github.com/CharlesRakesh/Elementor-Pro-Form/issues/1

I have an issue in Elementor pro form module textarea field. Email type is HTML send as, when i am sending a mail through that form, and i am adding message in textarea and using Enter to line break it's showing in form, but when i am sending that mail there is no line break in mail.

Can anyone help me how to solve that problem.

**Comment by mrpap** [comment]
> > Also if possible, please add a screenshot of the received Email.
> 
> [CharlesRakesh/Elementor-Pro-Form#1](https://github.com/CharlesRakesh/Elementor-Pro-Form/issues/1)
> 
> I have an issue in Elementor pro form module textarea field. Email type is HTML send as, when i am sending a mail through that form, and i am adding message in textarea and using Enter to line break it's showing in form, but when i am sending that mail there is no line break in mail.
> 
> Can anyone help me how to solve that problem.

This issue has been there for several years! With all the updates of Elementor, you would've thought this easy fix should have already been implemented! Facing the same problem and tired of adding workarounds to cope with it!!
