### ISSUE TITLE
Suggestion : Include a Analytics vision or funnel vision for Elementor Pages ?

### ISSUE THREAD

**Issue by vallsymachinant** [pojome/elementor#2738]
Hi Elementor Team.
I'm an entrepreneur and i use a Funnel Strategy.
So the Analytics it's so important for me .

**Have you plan a Analytics vision or funnel vision for Elementor Pages Pro ?**

If not, what's the best way to combine Elementors plugin and Analytics (what's the tools you use for following your visitors, the conversions, the sell, etc...)

**Comment by bainternet** [comment]
We use traditional tools like analytics.
