### ISSUE TITLE
 social share suggestion

### ISSUE THREAD

**Issue by weiqispace** [pojome/elementor#2739]
Hello~ Elementor Team

Is it possible to do as same as this site social share? 

https://www.designbombs.com/full-stack-wordpress-developer/

 I use Elementor+Elementor Pro+Elementor Extras and Theme is GP+GPP. 

There are three points about this.

1.sticky( I think it can use Elementor Extras to do that but maybe I am wrong)

2.hover effect

3. intergrate LINE network

https://developers.line.me/en/docs/

https://media.line.me/en/how_to_install

Thanks

**Comment by bainternet** [comment]
@weiqispace 

1,2) can be easily done with custom CSS.
3) we will look at adding LINE icon to the list.

**Comment by weiqispace** [comment]
Thank you

**Comment by bainternet** [comment]
@weiqispace 
The list of available icons are currently based on [FontAwesome](http://fontawesome.io/icons/) so we are waiting for them and it should be added in FA5.

[Line icon request](https://github.com/FortAwesome/Font-Awesome/issues/2631)

closing for now,

Thanks.

**Comment by weiqispace** [comment]
Do Elementor have plan to add FA5 and add LINE Social Share?

Many people in Asia area using LINE Social Share.

If you add this,I think it can boost your sales on the next level. 

Thanks
