### ISSUE TITLE
Allow "no cookie domain" for Youtube Video Element

### ISSUE THREAD

**Issue by Manuel-SG** [pojome/elementor#2741]
Right now, it is not possible to embedd a video from youtube with the "Turn on privacy-enhanced mode". If I enter an URL like:
https://www.youtube-nocookie.com/embed/UHz_9MjqjBw
the video will not be show. But if I add it without "nocookie" - it will work (https://www.youtube.com/embed/WY3HqKWgqKg).
Please allow to use the nocookie domain, too. Because for European Elementor users this will be mandatory in a few months. Because of new privacy laws.
Please have a look at the facebook group discussion here, too :  https://www.facebook.com/groups/Elementors/permalink/1312706168855166/

Thank you very much.

**Comment by bainternet** [comment]
@Manuel-SG 
thanks for reporting
we are already working on it.

**Comment by RafaelDeJongh** [comment]
This is actually still a problem when you want to use the youtube-nocookie.com domain for background video's.
