### ISSUE TITLE
Caption below image in active LightBox

### ISSUE THREAD

**Issue by LumWey** [pojome/elementor#2748]
[Feature request]
Want the possibility to add caption below an image, when image is shown in the active LightBox.
Hope this possibility will come in an updated version.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future.

Thanks for the feedback.

**Comment by bainternet** [comment]
I merged this issue with  #2502, which are on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Jaska** [comment]
+1 

Especially with Image Gallery widget, the way it puts the captions under the thumbnails would often look ugly and crowded.

**Comment by rja66** [comment]
+1
add lightbox captions for Image Gallery.

plus option to remove captions from thumbnails in Image Gallery

**Comment by jaredgeddy** [comment]
+ 1 this would be great!

**Comment by collins001** [comment]
I also wany this feature....!

**Comment by yanivs14** [comment]
+1

**Comment by Artneo7** [comment]
+1

**Comment by rohitmalakar** [comment]
+1 need caption inside lightbox for Image Gallery.

**Comment by sbshelley** [comment]
++ Would be a great add...any update on including this on a new release?

**Comment by neil2112** [comment]
+1 I need this feature!

**Comment by efc** [comment]
+1, captions under gallery images are ugly, but captions on lightbox images would be a welcome option.

**Comment by romapad** [comment]
+1

**Comment by crwzdi** [comment]
+1

**Comment by MaxZiebell** [comment]
+1

**Comment by yonifre** [comment]
+1
