### ISSUE TITLE
Viber and Facebook Messenger to the Social widgets

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2750]
Hello! Please add Viber button to the Social Icons widget. And also [Viber share](https://developers.viber.com/docs/tools/share-button/) and [Facebook Messenger](https://developers.facebook.com/docs/sharing/messenger/) to the Share Buttons widget.

Thanks!

**Comment by bainternet** [comment]
@parfilov 

The list of available icons are currently based on [FontAwesome](http://fontawesome.io/icons/) so we are waiting for them.

[Viber icon request](https://github.com/FortAwesome/Font-Awesome/issues/3554)
[Facebook Messanger icon request](https://github.com/FortAwesome/Font-Awesome/issues/6912)

closing for now,

Thanks.

**Comment by parfilov** [comment]
@bainternet Ok. Thanks!

**Comment by parfilov** [comment]
Hi @bainternet ! Font Awesome updated. When we'll see it?

**Comment by vovkasolovev** [comment]
Please add Viber to share options

**Comment by jomarieminney** [comment]
Bump for messenger icon
