### ISSUE TITLE
Devices visibility for Social Share widget

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2751]
Hi again! It would be nice to get toggle for devices visibility with every social button in Social Share widget. For examlpe: Viber, Facebook Messenger, WhatsApp, Telegram can be active only on mobile but on tablet and desktop — other share buttons.

Thanks!

**Comment by bainternet** [comment]
This can be done by using multiple widgets and only displaying one per device.

It won't give you the same editing experience as you describe but you get the same results.
