### ISSUE TITLE
Ability to set image / background focus point

### ISSUE THREAD

**Issue by fgschafer** [pojome/elementor#2752]
Hi. as a happy Elementor user, I'd like to suggest a nice feature.  I saw some Wordpress Themes with 
their own builders that makes it possible to set image focus point (with a very nice UI, just dragging a little circle avobe the image). This makes it possible to show the most important part of the image on smaller screen sizes. I hope this feature could be added at some point. Thanks!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future.

Right now you can do something similar using the native WordPress Image Editor to crop the image.


Thanks for the suggestion.
