### ISSUE TITLE
 Making tabs (and other) widget more responsive 

### ISSUE THREAD

**Issue by Svarmind** [pojome/elementor#2754]
Talked to Elementor Pro support about this, and they thought it was a great idea, and that I should submit it to GitHub such that you could do their job for free (ok, they did not say that last part) :)

"Similar to how I can specify specific typography size for desktop, tablet, and mobile; it would make it easier if I could do the same with anything. If you see in the attached images, the "tabs widget" looks good on desktop and mobile, but is cut off in tablet mode. The only solution I have found is to create a duplicate widget that I orient vertically in tablet mode, and hide in mobile and desktop. That is however cumbersome. Hence, would love if you extended our ability to specify specific settings for desktop, tablet and mobile. " 
![desktop](https://user-images.githubusercontent.com/33675117/32813422-688abd4c-c9aa-11e7-8fac-f10e7c5eb98c.JPG)
![tablet](https://user-images.githubusercontent.com/33675117/32813423-68ad4df8-c9aa-11e7-943c-4ef757e5dcc7.JPG)

**Comment by bainternet** [comment]
@Svarmind 

You can already do that for tabs,
Add a tabs widget and go to "style" tab,

there you can enable and set typography for the Tab title per device and for the tab content per device.

![umwgso0](https://user-images.githubusercontent.com/660572/32825431-ae46ee9e-c9ed-11e7-9045-f8408a01b350.png)


Thanks for the feedback.

**Comment by juliankauai** [comment]
i don't see this now in the 'edit tabs', 'style' area using elementor pro 2.2.0

any idea where it went? or how it is done now?

thanks
