### ISSUE TITLE
Style presets for elements

### ISSUE THREAD

**Issue by adrianweb** [pojome/elementor#2757]
I was wondering if elementor have support for `style presets` or if someone else had tried to implement them.

When you build an element sometimes you may want to display the content conditionally, when needed I use to add a field named `style`, where the user can chose between multiple styles, then the element render the content conditionally `if (style == 'style1')`.

Going further, each style may have it's own set of fields(`'condition' => ['style']`), and other common fields where the default value must be different for each style, and here's where the presets would be helpful.

The dirty workaround to apply let's say a color to a title is to duplicate the field and show it conditionally, `color_1` for `style 1` and `color_2` for `style 2`, but, it's not a good practice to duplicate a field, just to change it's default value.

**Comment by bainternet** [comment]
@adrianweb 

You can display controls conditionally based on a selected value (show/hide control), for example, look at these controls from the [Video widget](https://github.com/pojome/elementor/blob/master/includes/widgets/video.php#L65) 

```PHP
$this->add_control(
	'video_type',
	[
		'label' => __( 'Video Type', 'elementor' ),
		'type' => Controls_Manager::SELECT,
		'default' => 'youtube',
		'options' => [
			'youtube' => __( 'YouTube', 'elementor' ),
			'vimeo' => __( 'Vimeo', 'elementor' ),
		],
	]
);
$this->add_control(
	'link',
	[
		'label' => __( 'Link', 'elementor' ),
		'type' => Controls_Manager::TEXT,
		'placeholder' => __( 'Enter your YouTube link', 'elementor' ),
		'default' => 'https://www.youtube.com/watch?v=9uOETcuFjbE',
		'label_block' => true,
		'condition' => [
			'video_type' => 'youtube',
		],
	]
);
```

more specifically this lines:
```PHP
'condition' => [
	'video_type' => 'youtube',
],
```
in the second control, we define our `condition` by setting `field-id` => `condition-value`
meaning the "link" control will only show if the user selects "youtube" in the "video type" control.

As for changing/ updating the value conditionally, sadly there is no "Elementor native" way of doing that other than actually having multiple control. (no Yet anyway).

**Comment by smoochiecoochie** [comment]
@bainternet 

Sorry for re-opening this, but the conditions seem to no longer work?

```
        $this->add_control(
            'post-info-style',
                [
                'label'        => __( 'Post Info Style', 'elementor' ),
                'type'         => Controls_Manager::SELECT,
                'default'      => 'none',
                'options' => [
                    'none'              => __( 'Simple', 'elementor' ),
                    'info-style-1'      => __( 'Fancy White Background', 'elementor' )
                ],
                'return_value'=> 'yes'
            ]
        );


        $this->add_control(
            'show-info-style-1_animation',
            [
                'label' => __( 'Should I animate this?', 'elementor' ),
                'type'              => Controls_Manager::SWITCHER,
                'default'           => '',
                'label_on'          => __( 'Yup', 'elementor' ),
                'label_off'         => __( 'Nope', 'elementor' ),
                'return_value'      => 'yes',
                'condition'         => ['post-info-style' => 'info-style-1'],
            ]
        );
```

This should work, but it doesn't anymore.

**Comment by bainternet** [comment]
@smoochiecoochie 

use underscore for control id's.

**Comment by maxfrazeman** [comment]
Seems like this thread is closed but I'm sure this tip will help people who have the similar problem/question:

**WunderWP applies preset styling to Elementor widgets and beautifies your content in seconds.**

https://wordpress.org/plugins/wunderwp/

You can choose from dozens of readymade styles for Elementor Free and Elementor Pro elements. There are new styles adding from time to time for each element.

WunderWP preset styles **is available for free** in WordPress repository.
