### ISSUE TITLE
Accordion in tabs issue

### ISSUE THREAD

**Issue by harrispapadopoulos** [pojome/elementor#2760]
There seems to be an **accordion in tabs** bug that came up after one of the last updates (not sure which one).

In my case its about it is a FAQ page with three tabs as categories and each tab containing an accordion (added as a library sortcode) with questions and answers.

This was working fine up to some time ago.

After one of the last updates the accordions under the tabs are not opearting properly.

The open accordion is not hilighted (different color as it was set), sometimes when clicking to open a question (accordion) all the accordions dissapear and sometimes i.e. you click to open the 4th question of the 1st tab and instead of that the 6th question of the 3rd tab opens.

I guess there must be some kind of accordion javascript issue.

The same happens if you add accordion under toggle (I tried replacing tabs with toggle, but the same issue presists).

Please have a look.

**Comment by harrispapadopoulos** [comment]
Tried rolling back Elementor versions and it works properly when going back to version 1.7.12

**Comment by bainternet** [comment]
Hi @harrispapadopoulos,

thanks for reporting, this should be already fixed and should ship in the next release.

**Comment by harrispapadopoulos** [comment]
Confirming that its fixed in 1.8.5.
Thanks!

**Comment by joyloan** [comment]
Dear Friends,

I don't know any coding, today I created my first page with elementor. But Accordion / Toggle / Tab non of these 3 option is working as I want to put 6 diffrent things in 6 diffrent header and want page to look still clean.

Only first option shows open automatically. Then no button to expend / collapse etc works to open other headers. (Snapshot is as below)

Please help me
![accordion](https://user-images.githubusercontent.com/36277375/35992620-c7f87be2-0d30-11e8-81a3-02e14d647b90.png)
