### ISSUE TITLE
Filter to extend CPT's with elementor_library features automatically

### ISSUE THREAD

**Issue by FearVsFear** [pojome/elementor#2761]
Hi. 

I'm building my theme around Elementor now and checking out your docs. I don't see this, so it is a developer's feature request if not available. 

Do you have a `filter` that so I can run my custom post types through the same processes that `elementor_library` posts run through?

Example.

- Custom Post Type: `Footer` (hooked into the same processes as `elementor_library`).
- All posts in `Footer` now become available in the same places `elementor_library` does.

If you don't have a filter of such, would you recommend a good way to get started here?

**Comment by bainternet** [comment]
@FearVsFear 

Currently, there is no filter like the one you are asking for, But I can tell you that we are working on something that will allow you to build with Elementor parts of your theme like Header, Footer ....

So keep following.

**Comment by FearVsFear** [comment]
@bainternet 

Thanks! Appreciate it!

I found a much simpler way at the moment as well. I was thinking I could duplicate the **Template Widget**, but instead, I can just use shortcode `[elementor-template id="my_custom_post_id"]` instead of the post id used from the Elementor Library. This will work for now despite the UI of seeing those templates in the editor.

Thanks, about the future coming header, footer.... this is expected as this where most themes, well page builders are wanting to move because it makes sense and the customers demanding more control! :D I've always passionately hated the multiple editing experiences Wordpress has across plugins and themes. So inconsistent it's almost painful and dreadful, but I understand why it exists. It pleases my heart to hear you will be helping to alleviate that from the many many lives.

And thanks again, my theme is already built around having those options you mentioned. This is why I wanted to hook my custom post types into the processes **and UI of The Great Elementor!**

#GeneralSalute
