### ISSUE TITLE
New Search Box Improvements

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#2762]
Hello guys,

the new search box is amazing, I suggest add option to show a 'X' on fullscreen to click to close and the search field expands when you click on the icon.

Keep going ;)

**Comment by bainternet** [comment]
@silvioghedin 

Glad you like it,
clicking anywhere will close the fullscreen mode and clicking on the icon already open it, so basically you are asking to show an "X" button?

**Comment by norewp** [comment]
A "X" close button will go a long way for some users - it does give a sense of panic to some not knowing how to close the overlay. Clicking anywhere is not the first thing that comes to mind for many :)

**Comment by silvioghedin** [comment]
Exactly norewp ;)

**Comment by enviedbymost** [comment]
Agreed!

**Comment by bainternet** [comment]
Ok then,
We'll add it in some way.

**Comment by davidefiorio** [comment]
Also option to change icon before or after title...

**Comment by arielk** [comment]
Added a close button to Pro v1.11.0

Thanks for your feedback!
