### ISSUE TITLE
Certain WP Widgets to not work in E 1.8.4 in WP 4.9

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#2763]
WP 4.9 (official release) installed on local test site; E the only plugin. GeneratePress theme (free - no Premium)

The following WP Widgets (from the E panel) do not work. Their settings panels are empty.
- audio
- image
- video
- text (text can be entered, but editors are missing)
- custom HTML
- gallery (new in WP 4.9)

Cheers!
Lyle

**Comment by SniffleValve** [comment]
UPDATE:
Further testing reveals that the above-noted behavior is the same in Elementor 1.7.12 with WP 4.9.

**Comment by bainternet** [comment]
@SniffleValve 

thanks for reporting we are aware and I'll ready fixed in 1.8.5 which should be shipped very soon.

**Comment by norewp** [comment]
The same elements are forever loading for me on both WP v4.9 and v5.0-alpha

**Comment by RichardBeno** [comment]
I'm getting same problem on wp 4.8.3 (with elementor v1.8.4) - blank settings panel when editing text.

**Comment by arielk** [comment]
Fix in v1.8.5: https://github.com/pojome/elementor/commit/9d152c358593f52f14ae6af22fb30882f4fe75c0

Thanks for reporting!
