### ISSUE TITLE
[BUG] Animated Headline won't change Colour

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2766]
Hey,

Weird issue.

I've been using the animated headlines since their release. 

Whilst browsing my site today, I noticed the headline text colour was black, despite it being set to white. Testing this further, I cannot change the headline to any colour, whether red, blue, green etc; it remains black.

This is a new problem, and it wasn't present pre-v1.8.0.

To confirm, I'm now running the latest versions (v.1.8.4 and v1.10.0 (pro))

![screen shot 2017-11-17 at 01 03 36](https://user-images.githubusercontent.com/31274564/32924183-44dd4fd8-cb33-11e7-8c55-b6c7b7a98a78.png)

**Comment by bainternet** [comment]
@enviedbymost 

Please update to 1.8.5 once it comes out (later today???) 
and try re-editing your page with Elementor, this should trigger a CSS regeneration.

**Comment by enviedbymost** [comment]
Hey bainterest,

You've closed this ticket, but the issue hasn't been fixed with v1.8.5.

I've tried re-editing the page, but the issue remains.

I have these animated headlines throughout my site, it's not just on a single page. So ideally, I don't want to have to go through every single page and create new headlines and delete the old ones.
