### ISSUE TITLE
Please add being able to query post status to the posts widget

### ISSUE THREAD

**Issue by peden979** [pojome/elementor#2767]
Hello,
I'd like a way to display posts scheduled in the future aka "upcoming". According to this link the post query has a status that can be future and queried. 

https://stackoverflow.com/questions/36385479/is-it-possible-to-display-upcoming-posts-in-wordpress-blog-page

I looked at the posts widget and it doesn't support the post status. Is there another way to do this and if not can you please add it to the posts widget?

**Comment by bainternet** [comment]
I merged this issue with  #2466, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
