### ISSUE TITLE
[Enhancement Request] MailChimp api key in integrations tab

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#2769]
I created a few MailChimp forms today and it appears that I have to enter my api key EVERY time I create a new MailChimp form? It's quite inconvenient to have to log into MailChimp and get my api key every time I want to create a form.

**Request:**
It would make it a lot easier if I could enter my api key in the _Integrations tab_ in the WP admin. That way any new Mailchimp form I create would default to my api key. 

*If some users have multiple keys, they could choose from a drop-down list when creating their form.

**Comment by bainternet** [comment]
@avermat 

It would be nice but, currently, we have are more than a few customers that actually use multiple mail chimp account and that is why we have that field in place. 

I'll leave it open for now and we'll see if more people feel your need.

thanks for the suggestion.

**Comment by avermat** [comment]
@bainternet Understood. I just assumed that a majority of users only use a single api key. Users with multiple api keys would just leave that field blank in the integrations tab (so things would stay the same for people with multiple api keys, but it would be improved greatly for those with a single api key).

**Comment by bainternet** [comment]
@avermat 

As of the last version, you got your wish.
