### ISSUE TITLE
Add External Image option for Backgrounds

### ISSUE THREAD

**Issue by trchristensen** [pojome/elementor#2770]
I'm trying to extend the Group Control Base in my plugin to create an external background image option field to go with the standard classic background options. To be completely honest, I'm not sure what I'm doing. Can someone tell me if I'm on the right path? I have included this in my plugin but I'm getting errors. If i just modify the background.php file in the Elementor plugin it shows up fine.

```
<?php
namespace DesignStudioElementorAddons\Controls\Groups;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

use Elementor\Group_Control_Base;

class Group_Control_Background extends Group_Control_Base {

  $fields['ext_image'] = [
    'label' => _x( 'External Image', 'Background Control', 'elementor' ),
    'type' => Controls_Manager::TEXT,
    'title' => _x( 'Background Image', 'Background Control', 'elementor' ),
    'selectors' => [
      '{{SELECTOR}}' => 'background-image: url("{{URL}}");',
    ],
    'condition' => [
      'background' => [ 'classic' ],
    ],
  ];
}

```

**Comment by trchristensen** [comment]
bump

**Comment by bainternet** [comment]
Currently, We don't have an organized developers API to add/create custom controls but we are working on it.
As for your question, looking at this code example this will never work....
you need to extend the background control and add the field in the correct manner overloading the `init_fields` method. ex:

```php
class Group_Control_Background_trchristensen extends Group_Control_Background {
    public function init_fields() {
        $fields = parent::init_fields();
        //here you add your field
        $fields['ext_image'] = [
                'label' => _x( 'External Image', 'Background Control', 'elementor' ),
                'type' => Controls_Manager::TEXT,
                'title' => _x( 'Background Image', 'Background Control', 'elementor' ),
                'selectors' => [
                      '{{SELECTOR}}' => 'background-image: url("{{URL}}");',
                ],
                'condition' => [
                        'background' => [ 'classic' ],
                ],
         ];
         return $fields;
    }
}
```

now again since there is no real API for this yet then it's only an example... but it should get you in the right direction.
