### ISSUE TITLE
Margin & Padding - Leave Unlocked as Default - Suggestion

### ISSUE THREAD

**Issue by SpirtSoul** [pojome/elementor#2772]
Is there a way to have margin & padding options unlocked as a default?  It would cut down on may clicks to unlock as most padding and margin changes are to usually only top or bottom, or, right and left.
This would save hundreds of extra unneeded clicks.

**Comment by bainternet** [comment]
I merged this issue with  #965 , which are in the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
