### ISSUE TITLE
Typography leave as 'ON' in Styles because used soooo much

### ISSUE THREAD

**Issue by SpirtSoul** [pojome/elementor#2773]
Trying to reduce unneeded repetition of having to turn typography on when used so heavily. Can default just be left as on?  Seems odd to have to turn it on to style everything, which of course, is what everyone does.

**Comment by bainternet** [comment]
I merged this issue with  #965, which are on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
