### ISSUE TITLE
Question about layout

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#2774]
Right now I can create 2,3 or whatever column inside a row. But I can not add one full width coulmn above/below that. In order to do that I have to add another row . Is it possible to wrap these?Though there is duplicate and add column option both do the same ie add column aside. 

I think duplicate column should add column top-bottom and add column should left-right.

**Comment by avermat** [comment]
Having the ability to add a column below (like you suggest) would be amazing.

It seems like a lot of people ask for something similar to this. In addition to what you suggest, it would also be nice if the Section Selector had two row options right from the start:

![two-rows](https://user-images.githubusercontent.com/29379115/32984773-85d93200-cc72-11e7-9ddf-255c045a3d2a.png)

**Comment by bainternet** [comment]
@webangon 
It would be tricky, simply because this is not the way our section/columns work.
So you are correct that you would have to add another row. 

@avermat same thing sadly, its not the way it works.
