### ISSUE TITLE
Disable Inline Editing

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#2776]
Heyo!

Is there a function to disable Inline Editing? 

Call me old-fashioned but I prefer the "old" way of having content editing in the left hand editing pane, and being able to click anywhere in the element to drag it around rather than having to click and drag on the edit (pencil) icon. 

I've also found the text selection buggy as well. When I select some text to create a link it will deselect the text and add a paragraph to the bottom of the text element (see 
![elementor_inline_editing_bug](https://user-images.githubusercontent.com/1729832/32987786-cb5b0bf6-cd48-11e7-9e55-0c752620ff2b.gif)

Cheers!

**Comment by bainternet** [comment]
@JoelEadeDesign 

As you know you can still do your editing form the left pane, just as you normally would.

as for disabling it... we are about to add some game-changing features to the inline editing for you just might want to keep it.

As for the buggy selection, we'll fix that, so thanks for reporting.

**Comment by JoelEadeDesign** [comment]
"Game-changing" sounds intriguing. I'll stick around then ;)

Thanks for looking at the bug!

**Comment by black-eye** [comment]
I'm experiencing the same problem with the extra paragraph, even when not selecting the text, just when clicking into the widget. 

And when there are more paragpaphs in the widget, the extra space is added after each one, not only in the end. When I leave the widget, the normal setting is back and correct.

All of this happened just after updating to WP 4.9.

**Comment by bainternet** [comment]
@black-eye 
@JoelEadeDesign 

thanks, can you confirm its only at the first click?

**Comment by JoelEadeDesign** [comment]
Yep, it’s the first click when focussing on an element. Focussing elsewhere then returning to the element will again create a new paragraph and move the cursor to the bottom of the element.

Cheers!

**Comment by buzanman** [comment]
I can confirm this as well it only seems to effect the text editor widget for me on focus selection. The cursor creates a double space and starts in the centre of of the widget. (See screen shot for reference). 
![screen shot 2017-11-20 at 10 53 35](https://user-images.githubusercontent.com/6323418/33015074-5b0985d2-cde1-11e7-8a4b-6bffebea4f53.png)

**Comment by reachdigitalaus** [comment]
I'm also having issues, with inline editing, if you go an edit text, hit enter and the backspace I produce <spans> with font sizes <span style="font-size: 1rem;">. Also, the heading widget, if hit enter it produces empty divs. To test further I did a clean install for WP 4.9 and only have Twenty Seventeen theme installed and only Elementor as a plugin. Hopefully, this video can explain what I mean better.
[https://drive.google.com/file/d/14o74_SfPfqxsf9eNhLhubhM_T35-tIwM/view?usp=sharing](url)

Another thing is if you simply go back to WP editor the spans get removed, if you then go back to elemetor the spans come back.

**Comment by black-eye** [comment]
@bainternet 
mine is doing this: https://s.nimbus.everhelper.me/share/1261369/r3dfpqyedtyhqdvbto8g

**Comment by bainternet** [comment]
@black-eye, @buzanman 
Yes, it's the same issue we see working on a fix.

@reachdigitalaus what browser are you using???

@JoelEadeDesign 
The selection is not an issue as far as we can see because you tried to select before you activated the "Inline Editor". The Inline Editor Is activated on the first click so the correct flow should be : 
1) click to activate Inline Editor.
2) select your desired text.

We'll update when it's fixed.
