### ISSUE TITLE
Feature request: automatic sequential numbering and cross-referencing

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#2777]
Virtually all my posts contain illustrations that are sequentially numbered: Fig. 1, Fig. 2, Fig. 3, etc. These labels are frequently cross-referenced in the text. In the course of editing the post, the numbering often changes, making it necessary to re-number many captions and re-number the cross-references. The same situation exists for footnotes. A third example might be the numbering of sections of the text, although I do not generally do this.
It would be very useful to be able to define multiple sequences within a post (for example, one sequence for the Fig. numbering and one sequence for the notes) and be able to cross-reference them. The real value is in being able to automatically renumber them, as is generally found in any word processing software.
I note that it is not at all practical or desirable to first write posts in word processing software and then import the result into Elementor.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
