### ISSUE TITLE
Element error with the 404 page

### ISSUE THREAD

**Issue by stylethemes** [pojome/elementor#2778]
so i use the Header Footer Elementor plugin to design the header and footer in my theme but when i go to the 404 page i find this error and it shows only on the 404 page the other pages look fine
![1](https://user-images.githubusercontent.com/26869625/32995051-4692908c-cd67-11e7-973e-31e8388983c2.png)

![2](https://user-images.githubusercontent.com/26869625/32995055-5012bd1c-cd67-11e7-9fa8-da970af74a8a.png)

![3](https://user-images.githubusercontent.com/26869625/32995056-5461df42-cd67-11e7-9181-109837c9c949.png)

NB im using the latest version of elementor and header Footer Elementor

**Comment by bainternet** [comment]
header Footer Elementor is not affiliated with us and we cant really provide any support for that.
Try contacting the plugin developer.
