### ISSUE TITLE
Gutenberg wrapping elements with paragraph tag

### ISSUE THREAD

**Issue by Micemade** [pojome/elementor#2779]
Using Elementor 1.8.5 / Gutenberg (beta)

I installed and Gutenberg for testing purposes, played with it and left it. After a while I went back to my page creation process with Elementor and realized that on front page layout is all messed up.
So I went to Elementor editor (preview) and there everything was normal.
After some head scratching, I remembered I had tested Gutenberg, so I disabled Gutenberg. Everything went back to normal.

So - Gutenberg, it seems, wraps elements in additional paragraph tags `( <p> )`, in frontend.
In Elementor preview editor it doesn't.

I believe this is something you should really check. Perhaps it has something to do with wpautop()

**Comment by bainternet** [comment]
We are aware of compatibility issue with the current version of gutenberg, but we are still waiting for a more stable version to start addressing.

I merged this issue with  #2631 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
