### ISSUE TITLE
Image alignment doesn't work with Storefront theme

### ISSUE THREAD

**Issue by maartinjsh** [pojome/elementor#2783]
## Description
Image Widget Alignment doesn't work when Elementor is used with Storefront theme. When switching to default WP theme - TwentySeventeen it works again

## Steps to reproduce
- Install and activate Storefront theme
- Install and activate Elementor
- Add one section
- Add Image Widget to section
- Try to change alignment to Centered on Right - image stays aligned to Left.

## Environment
- WordPress 4.8.3
- Storefront 2.2.5
- Elementor 1.8.5

**Comment by bainternet** [comment]
@maartinjsh 

You are correct, Storefront style.css adds `display:block` property to all images and that's why the widget alignment won't work.

you can just add this snippet to custom css and you should be fine.
```CSS
img{ 
     display:inline-block;
}
```
