### ISSUE TITLE
Image "alt" in Testimonial Karussell 

### ISSUE THREAD

**Issue by WAM-Meerbusch** [pojome/elementor#2784]
Hello 
It would be great if you would install the old in the testimonial carousel.
Then you get no problem with SEO optimization here
Because now only 
`<img src = "x / y / z / round-logo8.jpg">`
 is better to see
`<img src = "x / x / z / round-logo8.jpg" alt = "some words">`

**Comment by bainternet** [comment]
@WAM-Meerbusch 

Thanks for reporting we will add alt attribute to images in testimonials carousel.

**Comment by arielk** [comment]
Fix in Pro v1.10.1

Thanks for your feedback!
