### ISSUE TITLE
MailRelay form integration

### ISSUE THREAD

**Issue by CabalTC** [pojome/elementor#2788]

**Comment by bainternet** [comment]
@CabalTC 

Assuming you are talking about the Forms widget,

Currently, this feature is not supported, but we will look into it in the future if we see more demand for it.

Thanks for the suggesiton.

**Comment by CabalTC** [comment]
Thank you Raz.

Is there any workaround I can use? Or there is no way of integrating a form
from Mailrealy.


*David Olier*
*Escritor e implementador Worpdress*
https://cabaltc.com

2017-11-21 16:19 GMT+01:00 raz ohad <notifications@github.com>:

**Comment by bainternet** [comment]
ref #2397
