### ISSUE TITLE
Responsive problems with Tabs element

### ISSUE THREAD

**Issue by Nat-Faeeria** [pojome/elementor#279]
On some displays, the tabs of the Tab element go to line if they don't have enough space to be displayed. But the design is not made with this in mind : the border breaks, and it doesn't look great.
![capture du 2016-07-18 16 05 53](https://cloud.githubusercontent.com/assets/9194688/16907871/1e2e61e8-4d02-11e6-9a18-3cae010fa15c.png)

**Comment by yehudah** [comment]
Please insert this code, and tell me if it's working
`
.elementor-tabs .elementor-tabs-wrapper .elementor-tab-title {display: table-cell;}
`

**Comment by Nat-Faeeria** [comment]
it is better but still not it (btw, I had to !important it, this rule already existed with a "display: inline-block")
![capture du 2016-07-18 17 32 46](https://cloud.githubusercontent.com/assets/9194688/16909467/e26feb8e-4d0d-11e6-92f1-5c607975c2d7.png)

**Comment by arielk** [comment]
Please check the `line-height` of the tab title, it looks like what is causing your problem

**Comment by Nat-Faeeria** [comment]
Yup, perfect ! I hadn't thought about it.
Thanks !
