### ISSUE TITLE
Export/Import problems

### ISSUE THREAD

**Issue by qoalu** [pojome/elementor#2790]
## Description

I have a website (wpold) where I have some pages I want to export to another website (wpnew). Exporting the pages in WP leaves all images in the pages with old urls. My goal is to move the pages completely with images.

## Problem

Elementor does not accept changed urls in the article.
(for example if I change something in the native editor it is not reflected in Elementor)

## Steps to reproduce

1. export the relevant pages from wpold.

2. I import the exported pages to wpnew. Then I run a plugin called Media Tools that
2.1. looks through entries for images.
2.2. downloads the images to local server
2.3. replaces the url of the image in the entry.

3. have the new updated urls in native editor but Elementor still shows old urls on wpold server.

4. This makes it impossible to move pages to another server.

## Environment

https://pastebin.com/isgqeMQZ

**Comment by bainternet** [comment]
please see this https://docs.elementor.com/article/131-replace-url-change-domain

use the URL Replace Tool.

**Comment by qoalu** [comment]
I've had some time to try the tool. And I have some feedback.

1. The URL change tool does change the URL in the elementor meta data, which is nice.
But for the Native Editor content to update as well, I need to go in the Elementor editor and trigger a save action. After that also the images in the native editor are updated. That is an inconvenience but not critical.

2. This tool does not work for the use cases where images are imported additionally to an existing site. I actually found the problem.
I am not importing to an empty site, which is where this actually would work, but I am importing to an existing second site. This causes IDs of the attachments to change and they receive a new one, when there is already an entry with the same id on the new website. Therefore those ids dont match with the one recorded in Elementor metadata. This causes this issue:
![screenelementor](https://user-images.githubusercontent.com/1624045/33380636-0cf0d458-d51c-11e7-878c-6533998bb89e.png)

Notice that the image on the left is the new correct one, the image on the right is the old image on the existing website that has the same ID as the new image had on the old site, before getting a new ID when being imported.

So the real problem is changing the IDs that a referenced in the Elementor metadata.

**Comment by qoalu** [comment]
@bainternet any comment on this?
