### ISSUE TITLE
Vertical alignment does not work in IE

### ISSUE THREAD

**Issue by LucasBRamos** [pojome/elementor#2797]
IE can not perform vertical alignment when height is set via min-height, so when I make a block that should occupy the entire screen (min-height: 100vh) and align the contents to the center it does not work.

However if the div has the height set instead of min-height the alignment works.

Information about this bug can be seen in [Can I Use](https://caniuse.com/#search=align-items) and [here](https://connect.microsoft.com/IE/feedback/details/816293/ie11-flexbox-with-min-height-not-vertically-aligning-with-align-items-center)

**Comment by bainternet** [comment]
This is more of an issue of IE then it is an Elementor Issue :) and looking at the bug report you linked, it was reported at 2014!!! if there is no fix for it by now then I would guess there never will be.

If you have to use vertical alignment in IE then I would add `height` property via custom CSS manually.
