### ISSUE TITLE
H2/H3 tags for Accordions/Toggle Titles

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#2798]
Accordion/Toggle Widgets in Elementor do not have the ability to mark the titles as H2/H3, this is a gross oversight and it is a much needed feature in a 'Mobile First World'.
An make-do option is editing the paras and wrapping them in h2 HTML but this creates a duplicate element and isn't great for  either UX or SEO.
<img width="1513" alt="accordion" src="https://user-images.githubusercontent.com/33909786/33145563-dc715f8a-cfe6-11e7-8ba2-b1d0fbd7b5b9.png">

This is a feature request.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into adding it on the next releases

Thanks for the feedback.

**Comment by davidefiorio** [comment]
....and also the ability to change symbol + / -  or arrows in Accordion/Toggle Widgets!

Tnk
Davide from Italy

**Comment by ramiy** [comment]
Related: #2836
