### ISSUE TITLE
aplle.com scroll effect

### ISSUE THREAD

**Issue by nieremeister** [pojome/elementor#2800]
Request:

It would be nice to have a functionality that mimics that of the apple.com scroll effect.

**Comment by bainternet** [comment]
Yea that would be really nice!!
Sadly, Currently, this feature is not supported, but we will look into it in the future in one way or another. It won't be like the highly customized design on the [Iphone-x salse page](https://www.apple.com/iphone-x/) but we will look at some kind of scrolling effects.

Thanks for the feedback.
