### ISSUE TITLE
Animation happens 2 times

### ISSUE THREAD

**Issue by cod3r3** [pojome/elementor#281]
Hi,

the animation happens 2 times when the page has been loaded.

Regards

**Comment by yehudah** [comment]
Can you give more details ?

what type of animation ? what widget did you use ?

So I can do the same in my install.

**Comment by cod3r3** [comment]
i think all animation types,
i hope this help : https://www.youtube.com/watch?v=ckz__XtxQHQ&feature=youtu.be

**Comment by yehudah** [comment]
Hi,

Please try to disable all plugins except Elementor and see if the problem continue.
If the problem continue, can you tell me your theme name ?

**Comment by cod3r3** [comment]
hey,

i disabled all the plugin and i changed the theme.
take a look https://www.youtube.com/watch?v=MVPGaXYKoNQ&feature=youtu.be

os: ubuntu 14.04
browser : chrome

**Comment by yehudah** [comment]
It look's like it happen only with "fade down" animation, does it happen to you in other animations ?

**Comment by arielk** [comment]
@cod3r3 We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by m-energy** [comment]
Hi, did you figure out this problem? I'm having the same issue on my client's site. The animation flashes once, then disappears, before loading correctly a second time. This is happening on all the pages when I have a background image and a background overlay coming in through the "slide up" animation, with a delay on one of the images. Also occurs without the delay. Also happens on some background images when I have a hover effect-- image flashes briefly and then the animation occurs.

Here is my site: [http://livewelldc.com](http://livewelldc.com)

I have done the following, nothing has worked so far:
Deactivated all plugins besides elementor
Disabled theme (currently customify) also tried Cactus by Vela
Activated Debug mode by altering wp_config.php root file
Tried different browsers and currently running on the most updated version of chrome. Tried deleting cache, incognito window, etc.

Any advice would be much appreciated!

M

**Comment by SamuelHumeau** [comment]
Same issue here, any help is appreciated. Maybe a caching issue ?
