### ISSUE TITLE
How about update for Developer API and Documentation?

### ISSUE THREAD

**Issue by tranlamnhatnam** [pojome/elementor#2811]
Hi, I'm a newbie and have been looking for some problems creating custom control, but most are supposed to be built in the future.

I have consulted Elementor Pro, which has some custom controls inherited from `Control_Select2` with great ajax search functionality. I also want to create a control like this but there is no document to implement.

I tried to build a similar custom control but did not understand how to use javascript to make the control use select2, as shown below.

![image](https://user-images.githubusercontent.com/1934536/33218685-ced9775a-d170-11e7-9a1e-602994bddbdd.png)

I think it will be necessary to improve the documentation more clearly and completely including features such as skin, recipe to create custom widget and some features not mentioned in the document.

Thank you.

**Comment by bainternet** [comment]
@tranlamnhatnam 

I can happily say that we are actively working on A Developer API and Developer Documentation.

**Comment by ramiy** [comment]
The new developers site: https://developers.elementor.com/

**Comment by drank** [comment]
@bainternet , could you please update the Documentation to contain the hook described in https://github.com/pojome/elementor/issues/4003#issuecomment-379688437

... and any other hook that is still not in the Doc?

Thank you.
