### ISSUE TITLE
[Feature Request] Missing Hover option for icons in Icon List Widget 

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#2812]

**Comment by bainternet** [comment]
@Mulli 

This is definitely not a bug. 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Mulli** [comment]
True. Bug or Feature can be in the eyes of the beholder…

 

But if you keep consistent with *your* other similar elements styling…

And if you think that 'mouse over a link' should get its own styling

Then it’s a bug.

 

I consider it a minor bug, not major or critical 😊

 

(you are welcome to start using this terminology – I used it a lot, its helpful)

 

Best

Mulli

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal
