### ISSUE TITLE
[BUG] Navigation widget violates layout by setting ward space 'nowrap'

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#2815]
## Description
Navigation widget set the 'a' link to ward-space:nowrap.
This may violate column layout.

As a rule: NO widget is allowed to expand beyond column layout
UNLESS specifically requested by the user.

**I suggest to add a style option in the navigation menu to allow nowrap.
The default value should allow wrapping.**

**Comment by bainternet** [comment]
@Mulli 

Can you provide an example of how it violates the layout??

**Comment by Mulli** [comment]
Hi Ohad

 

 

Very simple

 

Please look at https://ncr.site2goal.net/data_warehouse_edw_dwh_teradata/

Prior to twicking the CSS the menu items were over the text (in a separate column) to the left.

This is what I call layout violation. Since not element in one column should cover another in different column

UNLESS I specifically request for it.

Therefore I suggest that you make it an *option* for the menu.

 

Keep up the good work!

 

Best

Mulli

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal

**Comment by bainternet** [comment]
@Mulli 

thanks for the reply,
I still can't understand what exactly is the issue here,

Can you provide steps to reproduce?
Also, are you using the "Nav menu" widget? is it a WordPress Menu? or a different plugin??

**Comment by bainternet** [comment]
@Mulli 

Nevermind,

I see what you mean, ( the side menu )...

Well then, in that case, you are correct, We do try to keep our Widgets as generic and customizable as possible and we update and tweak them all the time. so, this feature is not supported, but we will look into it in the future.

Thanks for the suggestion and feedback.

**Comment by Mulli** [comment]
Hi Ohad

 

My main menu is Ubermenu plugin

But the side menu is Elementors menu

 

See the attached image that demonstrate the problem.

 

And below is the css fix (forcing white-space:normal, instead of nowrap)

 

.elementor-nav-menu--main .elementor-nav-menu a {

1.       -webkit-transition: .4s;

2.       -o-transition: .4s;

3.       transition: .4s;

4.       white-space: nowrap;

}

autoptimize_fe5…4612534a.css:5

.elementor-nav-menu--main .elementor-nav-menu a {

1.       /* white-space: normal !important; */

}

 

Best

Mulli

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal

**Comment by bainternet** [comment]
@Mulli 

Thanks again, Already got that https://github.com/pojome/elementor/issues/2815#issuecomment-346992574

**Comment by arielk** [comment]
Fix Pro v1.10.2

**Comment by Mulli** [comment]
Hi Ariel

 

I think this is the right decision.

Happy it made its way to the release.

I promise to suggest more fixes…

 

Keep up the GOOD job you are doing.

 

Best regards

Mulli 

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal
