### ISSUE TITLE
Anchoring the templates stored in the library.

### ISSUE THREAD

**Issue by ibrames** [pojome/elementor#2816]
It would be great if previously saved templates and sections, when updated individually, are also updated where they were used. Currently I have to reinsert a template or section every time I edit it.

**Comment by bainternet** [comment]
@ibrames 

We do have something like that called "[Global Widget](https://docs.elementor.com/article/100-global)":

> A Global widget gives you full control over a specific widget, that is displayed in multiple places on your site. Editing it in one place will instantly update the rest. It saves you the time and effort of going through the many pages on your site, and updating the content manually, one by one.
