### ISSUE TITLE
[Feature Request] JSON Importer (Pro Widget)

### ISSUE THREAD

**Issue by candydigital** [pojome/elementor#2817]
As a publisher we love to work with Elementor.

What we would additionally need is a "JSON Importer" Elementor Pro widget, which would allow us to pull JSON data from a external URL (RESTful webservice) and display it per drag and drop (field mapping / filter included) in an Elementor element.

Would be nice if you would consider to take this feature request on the roadmap!

**Comment by bainternet** [comment]
@candydigital 

Please provide a more detailed use-case example.

**Comment by candydigital** [comment]
For example a magazine site publishes an issue (edition) every month. The information about the issue (cover, headline, short description, price, table of contents...) is availabe from a REST-API (e.g. the publishers shop where all magazines are sold). The magazine (WordPress / Elementor) website could now be updated dynamically with additional issues (or e.g. price changes) when a new issue is ready for sale and provided by the publishers database (shop).

**Comment by bainternet** [comment]
Ok, thanks for clarifying,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
