### ISSUE TITLE
[Feature Request] Dynamic Slides with Layers (Slides Pro Widget)

### ISSUE THREAD

**Issue by candydigital** [pojome/elementor#2818]
As a magazine publisher we would like to display dynamic content (from a JSON source) on an Elementor Slider (e.g. for a Magazine the January Edition, February Edition etc...pp).

It should be possible to define a background and then display different content like "Title", "Edition Number", "Cover" etc...pp on different layers, which can be positioned per drag and drop and styled like standard elements in Elementor.

https://smartslider3.com/ can do that. Would be nice if we could do that natively inside the Elementor Page Builder.

**Comment by bainternet** [comment]
Currently, this feature (loading slider content from a json source) is not supported, but we will look into it in the future if we see a large demand for it.

You can, however, use smart slider with Elementor very nicely: [Smart Slider 3 and Elementor](https://smartslider3.com/blog/smart-slider-3-and-elementor/)

Thanks for the Suggestion.
