### ISSUE TITLE
[Request] Please add an ID Option

### ISSUE THREAD

**Issue by cod3r3** [pojome/elementor#282]
Hi,

Please add an ID option like you did with the CSS Classes ( Advanced ),
its a must for 1 page websites ( click on the menu item = scroll down to the section )

sorry for my English
Regards

**Comment by arielk** [comment]
You can use with Menu Anchor widget: 
http://i.imgur.com/Q5OeaaH.png

**Comment by cod3r3** [comment]
ah i didnt see that, 
sorry
