### ISSUE TITLE
Accomodation of WP 4.9 Improved Customizer Workflow features?

### ISSUE THREAD

**Issue by dryquart** [pojome/elementor#2824]
## Description
Will "Draft and Schedule Site Design Customizations"  be supported/accommodated by Elementor?
> "you can now tinker with your site’s design and schedule those design changes to go live as you please.... "WordPress 4.9 [also] gives you a preview link you can send to your team and customers so that you can collect and integrate feedback before you schedule the changes to go live.

Elementor does not provide an option to save design drafts (only allowing restorations from previously saved versions), so it would be a great for Elementor to take advantage of these new WP features!

**Comment by norewp** [comment]
I believe there are fundamental differences between the two.

The Customizer drafts and schedules referred to pertain to the overall Design of the Site while Elementor is an in-content design tool!

Designs like header/footer created in Elementor can be carried over into the Customizer by the theme and that is where the new features would apply and not within Elementor as things stand right now.

**Comment by dryquart** [comment]
Hmm, yes, I see what you mean. Elementor, however, can (and generally does) override the overall design (e.g., font colors and sizes, background) defined in the Customizer, and since Elementor does not support WP's native scheduling for posts and pages, there is not implementation of scheduling on any level when invoking Elementor. Leaving Elementor means either publishing changes (live!) or abandoning what you have done.

**Comment by bainternet** [comment]
@dryquart 
@norewp  is right in saying that there are fundamental differences between the two.

But we are currently working on functionality that will let you visually preview your changes before committing them. (kind of like it works with native posts editor).

**Comment by dryquart** [comment]
Yes, I understand there are fundamental differences... and yet significant similarities when it comes to seriously changing (i.e., overriding) some key design elements in the Customizer. Arguably, you can do that in the Custom CSS section of the Customizer, but at least there you can take advantage the new design scheduling and previewing features in WP 4.9. 

> But we are currently working on functionality that will let you visually preview your changes before committing them. (kind of like it works with native posts editor).

Um, Elementor already provides live "previews" instantly before saving, so @bainternet you mean there will be something along the lines of Draft and Pending Review states?

**Comment by bainternet** [comment]
@dryquart  Exactly!!!
