### ISSUE TITLE
Fixing typography selection field

### ISSUE THREAD

**Issue by Eichlig** [pojome/elementor#2826]
Hello, dear buddies!

This is more of a request than a technical issue, regarding the typography family (and related) fields.

It's pretty a hell of a pain in the ass to be forced to click typeface by typeface in order to check them out and see either they fit or not.

1) This could easily be fixed letting us change the typefaces using the keyboard arrow keys, so as we clicked up and down, it would immediately change on the canvas.

2) Just like Photoshop/Design would let us, the interface could display a preview of the typeface as we hover/scroll the typefaces (after clicking on the selection field).

There are endless fonts there, and sadly it will take me a huge while to know which are worth my attention...

Thanks!

**Comment by bainternet** [comment]
We are using [Select2](https://select2.org/) to list the fonts and sadly they have a few issues with keyboard selections. other then that if we hack our way around the native behavior of select2 we actually have a different problem of keeping the state of the current value, eg: say you have selected a font and saved. then you think about changing so you browse fonts using up and down keys but you decide to "Cancel" and stay with the selected font from previous save but by now, its nowhere in sight...

here are a few issues they need to solve before we can start thinkering our way for this:
https://github.com/select2/select2/issues/3472
https://github.com/select2/select2/issues/4068
https://github.com/select2/select2/pull/4293

So I'm closing this for now...

Thanks for the suggestion.
