### ISSUE TITLE
[Feature Request] Multisite "control panel"

### ISSUE THREAD

**Issue by tuweb365** [pojome/elementor#2827]
Hi Team,

**What is the feature we are suggesting:**
Have a "control panel" in a Multisite level to control user's capabilities for specific functions like 
 export Templates, Core or Custom templates, global settings and others. Also, the ability to activate the Elementor Pro plugin at the Network level and bypass the License request every time a client signup and create a new site.
**Why we are suggesting it:**
We host our client's sites within a Network and we would like to have more control on the capabilities the admin of these subsites can have to change global settings, export templates and other functions that can create a caos if one of our customers start playing with them. As a super admin I would like to restrict these features from subsite Administrators (clients) and the other roles below this one.
**Who else is doing it:**
A similar feature is currently in the Agency plan of Beaver Builder.

Thanks,
Phillip

**Comment by bainternet** [comment]
@tuweb365 

We are working on limiting editor capabilities for single site installations.

As for multisite level control panel its something we are talking about but not going to be implemented anytime soon and it really depends on if we see a large demand for it.

Also please make sure you are keeping in compliance with your license more specifically the "No Hosting or Resale" clause as can be seen [here](https://elementor.com/terms/) (number 3 at the bottom).
