### ISSUE TITLE
[Bug report] Hover status in NAV MENU

### ISSUE THREAD

**Issue by davidefiorio** [pojome/elementor#2828]
Hello.
I report a bug, not so bad, in NAV MENU...
I make a submenu with rounded border. 
When i go over first and last submenu the hover status lost border rounded.

See attachment to clarify you.
![screenhunter_24 nov 26 23 32](https://user-images.githubusercontent.com/33546042/33245173-280c53a8-d304-11e7-91ce-10d14158ed4f.jpg)

![screenhunter_25 nov rev](https://user-images.githubusercontent.com/33546042/33245206-a34eb7e0-d304-11e7-82f8-d5296a31b204.jpg)

Tnk
Davide from Italy - Elementor user enthusiast!

**Comment by bainternet** [comment]
@davidefiorio 

Thanks for reporting, you can add `overflow: hidden;` to your submenu ul elements and it should keep the border on hover as well.
 Currently, we feel it's not something we should add because it has potential to break too many designs.

Again thanks for your feedback.
