### ISSUE TITLE
Load External Images

### ISSUE THREAD

**Issue by ibrames** [pojome/elementor#2829]
So far I have only been able to insert images from the native Wordpress library. So all the images are served from my own server.
For example: Is there any way to insert images via URL from Google Drive?
In the same way, is there any way to insert background images that come from external servers?
As the background video option allows me to insert a YouTube URL (for example). Can I do the same with images so that they do not load from my server but from an external one?

**Comment by bainternet** [comment]
Image From a URL available via the Text Editor widget and click the "add media".

As for other widgets and background images, Currently, this feature is not supported, but we will look into it in the future.

As a side note: Hosting images for your own server but via a service like CloudFlare works perfectly fine. 

Thanks for the feedback.
