### ISSUE TITLE
Icon list alignment bug

### ISSUE THREAD

**Issue by patatus** [pojome/elementor#283]
Hi !
With the 0.5.2 update, I noticed that the icon list alignment isn't working like before.
The text-align option now acts on the icons and not on the list itslef.
Is it a bug or do we need to set it up differently ? =)

![capture d ecran 2016-07-18 a 16 55 46](https://cloud.githubusercontent.com/assets/20305403/16919122/bec050de-4d08-11e6-8e6f-d905bbfedc5b.png)

Thanks !

**Comment by arielk** [comment]
Thanks for your bug report! Seems like a bug.

**Comment by arielk** [comment]
Done https://github.com/pojome/elementor/pull/288/commits/3db469cb6f4ff2cd91d065e0a88043bed201163f
