### ISSUE TITLE
[Bug report] Compatibility with "External Media" plugin.

### ISSUE THREAD

**Issue by ibrames** [pojome/elementor#2830]
"External Media" allows me to import images directly from Google Drive or to point them with URL. Everything works perfect, except in the Elementor canvas.
When trying to bring images from an external server with a button for it, Elementor DOES NOT OPEN THE POP-UP to proceed with the import.
![sugerencia](https://user-images.githubusercontent.com/10443428/33249732-bb92d74a-d2f1-11e7-9110-f45527f8033c.jpg)

**Comment by bainternet** [comment]
@ibrames 

This plugin is not compatible as it loads its own custom JavaScript to the edit page but not to Elementor Editor. that's why it's not working.

Currently, this it is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
