### ISSUE TITLE
use fallback color for background-gradient

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#2831]
as some older android-devices have troubles with background-gradients or also rgba-backgrounds, there should be a fallback "background-color" value, which could be set automatically as the beginning or end-value of the gradient and the rgb-value of the rgba-color.

**Comment by bainternet** [comment]
@matthiaswagnerwy,

Thanks for your suggestion.

Background Gradients actually have a very wide cross-browser support [CanIUse](https://caniuse.com/#search=gradient) and implementing a solution like the one you suggested would require added JavaScript to run on each page with Elementor just to check if its a very specific UserAgent and then apply the suggested "fix/hack".

So sadly, we this is not something we are going to do, but you can always do it yourself :)

Again Thanks for you suggestion.

**Comment by matthiaswagnerwy** [comment]
hy, thank you for your quick reply :) i thought of it as a server-side solution that generates an additional css-line that is overridden by the gradient, so it would not need JS. but i understand if you do not focus on backward-compatibility for such old browsers.
