### ISSUE TITLE
[Feature Request] Close nav menu mobile clicking anywhere

### ISSUE THREAD

**Issue by jimbosonido** [pojome/elementor#2839]
Hi, I'm interested in the possibility of closing the mobile menu clicking anywhere in the site, this will be helpful if you use this kind of menu in a tablet or if you use it in a desktop version.

Regards

Jaime

**Comment by bainternet** [comment]
@jimbosonido 

In Elementor 1.9 we are adding a method "addBackgroundClickListener" which is exactly for cases like yours.

It will allow you to easily hide/close the menu on a background click...
https://github.com/pojome/elementor/blob/release/1.9.0/assets/js/editor.js#L2590
So let wait for 1.9
