### ISSUE TITLE
[BUG] Animated Headline Alingment

### ISSUE THREAD

**Issue by Eichlig** [pojome/elementor#2844]
Hello! : )

As you can see from the video below, animated headline alignment is not working properly.

https://youtu.be/a1ikMPM8_fY

**Comment by bainternet** [comment]
@Eichlig 

This was fixed in the past, make sure you have the latest version of bot Elementor and Elementor Pro.

If you have updated and still have this issue please feel free to reopen this.

thanks.

**Comment by Eichlig** [comment]
My Elementor Pro was bought last week, and Elementor itself was updated this morning.

**Comment by bainternet** [comment]
Then please contact our support via support@elementor.com and see how they can assist you.

thanks for the feedback.
