### ISSUE TITLE
Elementor breaks HTML structure

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#2850]
Why is Elementor adding extra markups to a HTML structure?

The actual HTML structure:

```
<div class="myclass active">
<div class="my-content">
	<h3>Make A Selection</h3>
	<span class="head-wrapper">
		<span data-selected="data1" class="dot data1"></span>
		<span data-selected="data2" class="dot data2"></span>
		<span data-selected="data3" class="dot data3"></span>
	</span>
</div>
</div>
```

The output on render:

```
<div class="myclass active">
<div class="my-content">
<h3>Make A Selection</h3>
<p><span class="head-wrapper"><br>
	<span data-selected="data1" class="dot data1"></span><br>
	<span data-selected="data2" class="dot data2"></span><br>
	<span data-selected="data3" class="dot data3"></span><br>
</span>
</p></div>
<p></p></div>
```

As you can see from the output - extra p tags and < br > have been inserted - this only happens on the frontend. Also, looking at the output it seems that the issue affects elements with the span tag?

Test conditions:
WordPress v4.9
Elementor v1.8.6
TwentySeventeen v1.4

**Comment by bainternet** [comment]
@norewp 

Using what widget??

**Comment by norewp** [comment]
Custom widget with no control just straight HTML in the render function and javascript that injects span tagged output depending on user selection.

The selections are 
#1: a hotspot on a specific area (data1, data2 & data3)
#2: dropdown selector revealed with data based on above selection
#3: further details revealed based on selection at #2.

Changing the span tags to divs results in no pre p tags or the < br >being added but there's still a rogue opening and closing p tag added as seen in the bellow code just before the closing div.
```
<div class="head-wrapper">
	<div data-selected="data1" class="dot data1 active"></div>
	<div data-selected="data2" class="dot data2"></div>
	<div data-selected="data3" class="dot data3"></div>
<p></p></div>
``` 

Changing all the spans in the javascript would resolve the issue for me but that's extra work and doesn't resolve the underlying bug for all concerned.

**Comment by bainternet** [comment]
This seems like the is an `autop()` in place but there is no way for us to tell for sure what's the cause without being able to replicate.... 

paste your code, and we'll give it a look.

**Comment by norewp** [comment]
I can't paste the code publicly as it a private client project.

I can however send the team a copy of the addon to have a look over - let me know where to send it to or ping me on FB and inbox it over.

**Comment by norewp** [comment]
I've narrowed this down to a conflict with Gutenberg!

If we can leave this issue open for the time being and I'll post an issue in the Gutenberg repo referencing this one to see how best to resolve it.

**Comment by norewp** [comment]
@bainternet - I'll close this one for now as the word is Gutenberg is still in beta and the issue won't get much attention for now.

Thanks for your attention and support for now - I shall be back to trouble you some more :D

**Comment by norewp** [comment]
Re-opening this in light of https://github.com/WordPress/gutenberg/issues/3901 - Although in my test there was no switching from Gutenberg to classic editor, the issue could well be with WP_Editor!

I believe this now needs further investigation to see where exactly would a fix fit in.

**Comment by bainternet** [comment]
@norewp 

send it to our support@elementor.com and tag me in the mail so the support guys will forward it to me.

**Comment by bainternet** [comment]
please reopen once you've sent it.

**Comment by ManuelRomeroLA** [comment]
I am having the same issue.  Any updates?
![2018-05-21_10-48-43](https://user-images.githubusercontent.com/37461857/40326527-64c8daa8-5cf4-11e8-988f-f7a115c694d4.jpg)

**Comment by ManuelRomeroLA** [comment]
I am having the same issue.  Any updates?
![2018-05-21_10-48-43](https://user-images.githubusercontent.com/37461857/40326574-98a4fb36-5cf4-11e8-94fe-e010e9d737cb.jpg)

**Comment by dannykater** [comment]
Same here!

**Comment by ManuelRomeroLA** [comment]
For me, the issue was tied to a custom plugin that a previous developer created.  With that plugin off, Elementor works fine.  I don't need that custom plugin anymore so I did not look into the issue further.

**Comment by wonderful123** [comment]
I have the same <br> codes in the button widget.

**Comment by pavelgarchenko** [comment]
Same here.
Any news?

**Comment by loq24** [comment]
Same here!

**Comment by ManuelRomeroLA** [comment]
> I am having the same issue. Any updates?
The cause of my issue was another plugin.  When I turned off that plugin, the html was as it was intended.

**Comment by samrae** [comment]
I'm also having this problem. <br> tags inserted in buttons on live site (not in the preview).

**Comment by ninjazaman** [comment]
Is there any solution yet? I am getting the same issue.

**Comment by elliotboney** [comment]
this just randomly started happening to our site today, came here from a google search and saw that @ninjazaman just came here after this hasn't been commented on in almost a year so wondering if maybe there was an update pushed out that did it

**Comment by khunteebwar** [comment]
Same here, the <class="font_name"> is inserting to random frontend posts. And also while I edit the post with Elementor.

**Comment by metaline** [comment]
Is there any solution yet? I am getting the same issue.
