### ISSUE TITLE
[Feature Request] Make Controls Capability(Role) Aware

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#2852]
Could the team please consider the use of or making Controls capability aware?

Much like it's done with the Customizer check on add_setting() to a section
`'capability'  => 'edit_theme_options',`

The benefits!
Addon developers can add the check to allow certain roles to perform certain action on a specific module - like admins (read designers) can create/edit the page structure while those with the editor role are allowed to only edit texts based controls.

This can be extended to the Page and Global settings too as well as other areas like the advanced/style/settings tabs.

TIA,
Zulf

**Comment by bainternet** [comment]
@norewp 

We have considered and had hours of discussions about the whole Roles/Capabilities and how to incorporate them into Elementor.

Like I mentioned in other issues, we are working on something to limit users from having full access to the editor via capabilities but not at a control level more at the Tab level.

It's kind of tricky for a few reasons:

- Elementor doesn't work on the backend like the Customizer, so we don't have access to the capabilities all the time, only on page load.

- another is that the controls loaded dynamically based on the widgets and then added based on the widgets.

And probably a few more. 

But The main reason is that widgets render is control depended and if you are missing one that can bring problems. 

So, for now, I'd say is to look out for the capabilities will integrate and see about building on top of that.

Like always,
Thanks for you suggestions.
