### ISSUE TITLE
Feature Request : Merge JavaScript and CSS assets

### ISSUE THREAD

**Issue by IamJeyLabrecque** [pojome/elementor#2857]
I want to be able to merge all the Elementor's JS and CSS assets into one file.

They have too many assets and too many HTTP requests. That's lack website speed.

**Comment by kokers** [comment]
Your best bet is to use some minnify&combine plugin which is even better for this job as it will merge css & js from all plugins.

For example:
https://wordpress.org/plugins/fast-velocity-minify/
https://wordpress.org/plugins/autoptimize/

Some caching plugins also have this functionality, so if you plan to use one, check if they have this option.

**Comment by bainternet** [comment]
@IamJeyLabrecque 

The scripts and style are loaded per need bases so we don't load them every time even if they are not needed and we don't load them all if not specifically needed.

The vast majority of sites are transitioning to HTTP2 which keeps the remote connection open and serves most the assets in that same connection.

And like @kokers as mentioned you can use a 3rd party plugin which will work just fine in merging the assets files.

Thanks for you suggestion.
