### ISSUE TITLE
Big responsive problem !

### ISSUE THREAD

**Issue by Nat-Faeeria** [pojome/elementor#286]
As I said in issue #227 , there are some responsive problems. Now I am facing the exact same issue with every element : the options "hide for mobile" and "hide for tablet" are missing a range of screen width values ([480px-766px]).

For example, in a page : 
    - I create a title with a font size of 50px, and select the options "Hide on desktop : hide, Hide on tablet : show, Hide on mobile : hide" ; 
    - just under this title, I create a title with a font-size of 30px, and select the options "Hide on desktop : hide, Hide on tablet : hide, Hide on mobile : show"
    - I then use Mozilla Firefox responsive mode, and put a screen size of 600. No title is displayed.
   - I then use my phone (5' screen) on horizontal display. No title is displayed, because I am inside the range of value [480px-766px] 

Hope you'll be able to correct this, it's kind of major.

**Comment by cobicarmel** [comment]
HI, please leave edit mode and check your page. Does the problem still exist?

Also, if you want to check responsive in the editor, you can select responsive mode from the panel footer, then enter preview mode by closing the panel.

**Comment by Nat-Faeeria** [comment]
Yes, I did it out of edit mode.

Yes I know, I just wanted to try out of edit mode

**Comment by arielk** [comment]
Mobile mean 768 and less (max-width:767px;). Are you heading not hidden in a Mobile Landscape?

This is out breakpoints:
`$breakpoints: (
	sm: 480px, // Mobile landscape
	md: 768px, // Tablet
	lg: 1024px, // Desktop
);`

**Comment by Nat-Faeeria** [comment]
Yes, I know your breakpoints. 
Did you try what I told you ?

**Comment by arielk** [comment]
Merged #141

**Comment by arielk** [comment]
Fixed #522
