### ISSUE TITLE
[Feature Request] Image field - open media from preview

### ISSUE THREAD

**Issue by kokers** [pojome/elementor#2863]
We have inline editing in preview, why not add media selection too. I find myself clicking an image in preview and expect that Media library will open and I will be able to quickly swap image. 

What would be great is, when you hover over image the "change media" big button would show up http://prntscr.com/hgw5ba media library open, select image and bum.

**Comment by bainternet** [comment]
thanks for the suggestion.

**Comment by bainternet** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

thanks.
