### ISSUE TITLE
Mysql slow query with Pro Element

### ISSUE THREAD

**Issue by nicomollet** [pojome/elementor#2865]
## Description

I am using a WordPress multisite with WooCommerce on one of the sites.
The frontend is really slow. 

With the "Query Monitor" plugin, I managed to see Mysql Slow Queries executed on the frontend.

The mysql slow query is (8 is the ID of the multisite):
`SELECT SQL_CALC_FOUND_ROWS wp_users.ID,wp_users.display_name FROM wp_users INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id ) WHERE 1=1 AND wp_users.ID IN ( SELECT DISTINCT wp_8_posts.post_author FROM wp_posts WHERE wp_8_posts.post_status = 'publish' AND wp_8_posts.post_type IN ( 'post', 'page', 'attachment', 'elementor_library', 'product', 'content_block' ) ) AND (
  ( wp_usermeta.meta_key = 'aq_8_user_level' AND wp_usermeta.meta_value != '0' )
) ORDER BY user_login ASC;`

## Steps to reproduce

I created a Elementor Library called "Offers".
In this "Offers" Elementor template, I added a Pro Element "Posts" with a simple query: display 4 posts from the post category "offers".

I put a Elementor Library Widget into my footer widget area, so it is displayed on every page of the sites. 
I selected a Elementor Library called "Offers".

On the frontend, it is slow.

Replacing the "Posts" element with other similar widgets doesn't give the same problems. For example with "Network Latests Posts" Widget.

Note that it has something to do with the number of users in WordPress. Mine has 4000 WooCommerce customers.

Thank you.

## Environment
WP 4.8.4
Woo 3.2.5
Elementor 1.8.7
Elementor Pro 1.8.2

4000 users
50 products
4000 orders

**Comment by bainternet** [comment]
@nicomollet 

please contact our support via support@elementor.com so we can investigate deeper whats the cause.

make sure to reference this issue #2865.

thanks.
