### ISSUE TITLE
Font Awesome icons are italicized in Elementor editor since Elementor 1.8

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#2873]
When one adds the FA code to an E widget (Heading, for example), it appears italicized in the E editor but displays normally on the front end of the site.

Rolling back to E 1.7.12 and the FA icon appears normally in the E editor.

Cheers!
Lyle

**Comment by bainternet** [comment]
@SniffleValve 

Thanks for reporting, should be fixed in next version.
