### ISSUE TITLE
Icon list on global widget don't update

### ISSUE THREAD

**Issue by yeahoni** [pojome/elementor#2874]
last version
Elementor- 1.8.8 / PRO - 1.10.1

Icon list saved as global widget : 
Trying change links  - it  doesn't update.
When i Roll back to 1.7.2/PRO1.9.5 It works fine.

Thnx
yoni

**Comment by bainternet** [comment]
@yeahoni 

Thanks for reporting, will take a look.

**Comment by arielk** [comment]
Fix Pro v1.10.2

**Comment by yeahoni** [comment]
I'ts back on Elementor - 2.0.0/Elementor Pro - 1.15.4
Same issue
Yoni

**Comment by arielk** [comment]
Please update to Pro v1.15.5, it will be resolved
