### ISSUE TITLE
Images Not displayed after VersionPress Clone

### ISSUE THREAD

**Issue by jt6a74** [pojome/elementor#2877]
## Description
After creating a staging version of the site with Version press (https://docs.versionpress.net/en/sync/cloning) any images used in the elementor's Image/ImageBox/carousell widgets (possibly other image related widgets, only tried these), the images used would not appear on the new staging site. 

I have tried the replace urls in the tools as the urls do end up different after the clone. That did not fix. 
I have found that the correct images do show up in the editor side bar, but not the actual page.

From what I can tell when version press creates the staging site the media/post id's end up different.
Looks like the editor side bar is following the updated img urls path but the page is trying to use wordpress media id's?

If the page is looking for ids for imgs can that be changed to urls?

Also Version press does have this plugins
https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md
Don't know if that will be of any help.

## Steps to reproduce

With a Wordpress site using elementor widget that has images.
Create staging version using Versionpress.
https://docs.versionpress.net/en/sync/cloning

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: 5.5.58
	PHP Version: 5.6.30-0+deb8u1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.1
	Site URL: http://-------.com
	Home URL: http://-------.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: Plain
	Language: en-AU
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 1.4
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

== Active Plugins ==
	Display Posts Shortcode
		Version: 2.9.0
		Author: Bill Erickson

	Elementor
		Version: 1.8.8
		Author: Elementor.com

	VersionPress
		Version: 4.0-beta
		Author: VersionPress

== Debug ==
	Errors: There are no errors to display

**Comment by bainternet** [comment]
@jt6a74 

I'm not sure what exactly happens when you create a Clone/Staging using VersionPress but if the images end up with a different attachment id then that is the reason they are not loading.

Elementor stores Images as an array of `Attachment ID` and `URL`.
Now, the URLs can be changed/updated using the search replace tool but if get a different attachment id then it will break the Image from showing up.

I feel it relates to https://github.com/versionpress/versionpress/issues/654.

Hope this helps get you in the right direction.
