### ISSUE TITLE
[Feature Request] Allow full post content in the Posts widget

### ISSUE THREAD

**Issue by mobichan** [pojome/elementor#2887]
I really love the Post widget's ability to customize the look of the posts.  I'm especially liking the card format.  But I need to be able to display posts in their entirety, not just excerpts.  Is it possible to allow the excerpts to be toggled on/off, with OFF causing the full content to be displayed?

I have spoken at length with customer support and there appears to be no current solution where images and formatted text can be shown in the Post widget.  If the current Post widget can not be altered, can a new widget be made that uses (the_content) instead of (the_excerpt)?

**Comment by bainternet** [comment]
@mobichan 

Thanks for the suggestion, we are already working on a full content solution.

I merged this issue with  #543, which is on the same subject so we could deal with it more efficiently. 

Please feel free to continue the conversation there.

Thanks for your feedback!
