### ISSUE TITLE
Question: Using a Slider Plugin 

### ISSUE THREAD

**Issue by henriharbor** [pojome/elementor#289]
I just came across Elementor in my search for a true and quality front end editor for WP ~ I am most impressed and downloaded and will start playing with Elementor very soon.  I am curious to learn more about using 3rd party plugins ~ and specifically about using a slider plugin ~ like Hero Slider ~ (yet to purchase) ~ so before I put some money down for a slider I would be interested in a more specific description about how one works with such plugins in Elementor.  Thanks!

**Comment by Nat-Faeeria** [comment]
For trying (free version of Hero Slider and others), most works well. When it is widgetized, the widgets appears on the Elementor sidebar and you can put it where you want. When it is a plugin based on a shortcode, you can add it to your page by adding support for shortcodes in your theme (if it's not the case) and put the shortcode in a Wordpress Text widget. You'll probably have to do a bit of css to have the exact design you want then, but nothing really hard, and depending on what you want, you may not even have to do it.

You can always create a mock wordpress site, and try the free version of Hero Slider in Elementor on it !

**Comment by henriharbor** [comment]
thanks so much Nat ~ good advice all ~ yes, I am diving into Elementor on my local server! And I will do as you recommend!  ;{)
