### ISSUE TITLE
Background Image Blur Addition

### ISSUE THREAD

**Issue by lokygordon** [pojome/elementor#2896]
I would like to see a new feature added to blur the background image of a section. I was able to do this in a separate plugin such as Smart Slider however I would like to keep all my contents editable within Elementor therefore I think it would be a great and helpful addition to the already marvellous plugin.

**Comment by bainternet** [comment]
@lokygordon 


Can you link an example?

**Comment by lokygordon** [comment]
The following link shows an image of a slider created within Smart Slider.
https://smartslider3.com/wp-content/uploads/2017/07/blurslider.jpg
As you can see the background image of the cliff & waterfall is slightly blurred.

**Comment by jnicotra** [comment]
I have made a plugin that adds some support for this and other things: http://bluepointdigital.com/sites/playground/

A newer, much more feature-packed plugin coming soon :)

**Comment by Basilakis** [comment]
@bainternet https://codepen.io/anthonyadamski/pen/yJBpd

Here is a sample of BLUR for you.

**Comment by jayalove** [comment]
I second this request 😉

**Comment by themedleb** [comment]
+1

**Comment by knytl** [comment]
Just found that this option for background is missing. It's must-have! :)

**Comment by arielk** [comment]
This feature is already released in v2.1 of Elementor, please update the plugin and you can set CSS filter in the Background Overlay area.

Thanks for your feedback!

**Comment by gerardreches** [comment]
> 
> 
> This feature is already released in v2.1 of Elementor, please update the plugin and you can set CSS filter in the Background Overlay area.
> 
> Thanks for your feedback!

This should also be available in the background area!

**Comment by shay1383** [comment]
+1
