### ISSUE TITLE
Tab content lost when dragging but releasing on same position

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#2897]
hy,
i see this issue when working in chrome and firefox on mac (latest versions). i use the tab-widget with a few tabs. when i start dragging one tab to another position but then release it to early, so that it jumps back to the original position, the content of this tab is lost.
this happens pretty often as sometimes when you click on it, it makes a small movement...

i have also seen it in various pages where we use elementor with different configuration of other themes/plugins/...

hope you can reproduce and fix it :)
matt

**Comment by bainternet** [comment]
@matthiaswagnerwy 

Thanks for reporting, we can replicate and try to fix it as soon as possible.
