### ISSUE TITLE
How to use column gap only between columns with Bootstrap

### ISSUE THREAD

**Issue by kevinmamaqi** [pojome/elementor#2911]
## Description

I am using bootstrap in my theme as follows:

```
.container
  .row
    .col-md-12
       the_content
```

In `the_content` Here elementor adds an external gap which I don't want. Is there a way to eliminate it? Is there a if conditional that I can use to remove the .col-md-12 from my php if elementor is being used?

**Comment by bainternet** [comment]
@kevinmamaqi 

You can set the "Columns Gap" to "No Gap" in the section settings or if you want in your theme you can use the [`is_built_with_elementor()`](https://github.com/pojome/elementor/blob/ae50c46c5fc8e46148d84f42ee078187e2f9d532/includes/db.php#L360) method to check if the current page uses elementor.

**Comment by kevinmamaqi** [comment]
Hello @bainternet it doen't work. I receive the following error: is_built_with_elementor(): 

> Call to undefined function has_elementor_in_post() in ../mytheme/template-parts/content.php 

Code included in that file
```
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<header class="entry-header">
		<?php
		if ( is_single() && !is_built_with_elementor() ) :
			the_title( '<h1 class="entry-title">', '</h1>' );
		else :
			the_title( '<h2 class="entry-title"><a href="' . esc_url( get_permalink() ) . '" rel="bookmark">', '</a></h2>' );
		endif;

....
```
