### ISSUE TITLE
Feature Request: Some way to add my custom content-boxes?

### ISSUE THREAD

**Issue by smithythemighty** [pojome/elementor#2914]
Hey.

I've searched before, but there's no clear way to how to add custom content-boxes. Say I wanna add a box like this:

[https://image.prntscr.com/image/BBc_IvIXT2G53PFvbyfeRQ.png](url)

As per Visual Composer, the 

> vc_map()

function allows me to hook into VC and add custom shortcodes so that people can use them in the builder.

I believe this is critical to the expansion of Elementor and perhaps you've already added it, but I can't see any tutorial or clear way of doing it.

Please do let me know what you think.

**Comment by bainternet** [comment]
@smithythemighty 

In Elementor we call it "Widgets" and you can add your own very easily using the provided API,
please see this "[Hello World](https://github.com/pojome/elementor-hello-world)" to understand how.
