### ISSUE TITLE
Plugin Conflict : Sublanguage version: 2.3

### ISSUE THREAD

**Issue by halest** [pojome/elementor#2915]
## Description

Elementor clashes with the plugin "Sublanguage" version: 2.3.
Elementor will always show the classic "You must call the_content function in the current template, in order for Elementor to work on this page".
Disabling "Sublanguage" makes Elementor work as expected. 
## Steps to reproduce
1. Wordpress with Sublanguage active
2. Install Elementor
3. Edit page

## Environment
Ubuntu 16 with nginx, current versions of sublanguage, Elementor and wordpress.

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.3
	MySQL version: 5.6.37
	PHP Version: 7.0.22-0ubuntu0.16.04.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.1
	Site URL: https://soup-kitchen-records.com
	Home URL: https://soup-kitchen-records.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Soup Kitchen Records
	Version: 0.1.0
	Author: SK
	Child Theme: Yes
	Parent Theme Name: Rock N Rolla
	Parent Theme Version: 1.0.3
	Parent Theme Author: Band Themes

== User ==
	Role: administrator
	WP Profile lang: de_DE_formal
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

== Active Plugins ==
	Contact Form 7
		Version: 4.9.1
		Author: Takayuki Miyoshi

	Disable Comments
		Version: 1.7.1
		Author: Samir Shah

	Elementor
		Version: 1.8.9
		Author: Elementor.com

	Sublanguage
		Version: 2.3
		Author: Maxime Schoeni

	TinyMCE Advanced
		Version: 4.6.7
		Author: Andrew Ozz

	UpdraftPlus - Backup/Restore
		Version: 1.13.16
		Author: UpdraftPlus.Com, DavidAnderson

	WordPress Easy SMTP
		Version: 1.1.1
		Author: iProDev

	WP Super Cache
		Version: 1.5.8
		Author: Automattic

== Debug ==
	Errors: There are no errors to display

**Comment by halest** [comment]
It seems like it has something to do with the language slugs in the domain. Disabling the checkbox
"Show language slug for main language in site url" makes Elementor work - as well as making the language handling not work any more :)

**Comment by halest** [comment]
It seems like it has something to do with the language slugs in the domain. Disabling the checkbox
"Show language slug for main language in site url" makes Elementor work - as well as making the language handling not work any more :)

**Comment by halest** [comment]
I just tried Polylang (300k+ installs) which interestingly has almost the same behaviour. Works on one language but will show the "the_content()"-message on a secondary one.

**Comment by bainternet** [comment]
@halest 

It works fine with Polylang or WPML, as for sublanguage, not sure about the data structure it uses but it's not going to work with Elementor Unless it has a post ID per language.

but either way the "You must call the `the_content` function in the current template" message doesn't appear when tested using both plugins and a twentyXXXX theme, so it could be related to the theme in use.
