### ISSUE TITLE
[BUG] Firefox Dev Edition - Percentage Padding not working

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#2916]
Hi,

Just been trying out the new Firefox Dev Edition and it appears `percentage` padding does not work at all. Noticed on some of our client sites today that they didn't work. Changing to `px` fixes this.

Using latest versions of Elementor + Pro.

<img width="1229" alt="screen shot 2017-12-09 at 13 05 55" src="https://user-images.githubusercontent.com/13979799/33795915-34e4e238-dce2-11e7-8ccd-a8212abf795e.png">

**Comment by bainternet** [comment]
@enkota 

This is kind of a known issue with firefox and its flex implementation 
https://stackoverflow.com/a/33503864

nothing much we can do here for now.
