### ISSUE TITLE
Storefront Theme + Elementor Canvas = Cards vertical alignment

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#2917]
Hello! There is a problem with Woo Widgers in Storefront Theme when using Elementor Canvas. If I use widgets: Woo Products and Woo Categories the cards are aligned vertically and not horizontally.

Please, do something with this.
![woocategories](https://user-images.githubusercontent.com/12493645/33803154-0492ceac-ddb3-11e7-9b55-2b174a41f166.PNG)
![wooproducts](https://user-images.githubusercontent.com/12493645/33803155-04be8a56-ddb3-11e7-85f9-19b5e64ddd88.PNG)

**Comment by bainternet** [comment]
@parfilov 

This is a known issue with Storefront overwriting Woocommerce default CSS which breaks the grid.

You can add a CSS class of `.site-main` to the section and it should work just fine.

**Comment by parfilov** [comment]
@bainternet Oh, thanks! I did not know about this and only encountered when maked the WooCommerce widgets review.
