### ISSUE TITLE
Editor not loading

### ISSUE THREAD

**Issue by schneekettchen** [pojome/elementor#2918]
I just installed Elementor on 2 websites.
On one it's working, on the other one only the left panel gets loaded but not the editor itself.

I already deactivated all plugins but without success.
My environment should match, right? Any ideas?
 					
== Server Environment ==
	Operating System: SunOS
	Software: Apache/2.2.31 (Unix)
	MySQL version: 5.6.37
	PHP Version: 5.6.32
	PHP Max Input Vars: 4000
	PHP Max Post Size: 48M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.1

	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Oria
	Version: 1.08
	Author: JustFreeThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

== Active Plugins ==
	Auto Post Thumbnail
		Version: 3.4.1
		Author: Aditya Mooley <adityamooley@sanisoft.com>, Tarique Sani <tarique@sanisoft.com>

	Elementor
		Version: 1.8.9
		Author: Elementor.com

	Google Captcha (reCAPTCHA) by BestWebSoft
		Version: 1.33
		Author: BestWebSoft

	Imsanity
		Version: 2.3.9
		Author: Shane Bishop

	Jetpack by WordPress.com
		Version: 5.6
		Author: Automattic

	Mass set Categories
		Version: 0.1
		Author: J. Frank Parnell

	WF Cookie Consent
		Version: 1.1.2
		Author: wunderfarm

	WP-SpamShield
		Version: 1.9.21
		Author: Red Sand Media Group

	WP Smush
		Version: 2.7.6
		Author: WPMU DEV

== Debug ==
	Errors: There are no errors to display
				

<img width="1680" alt="bildschirmfoto 2017-12-10 um 15 16 47" src="https://user-images.githubusercontent.com/3502136/33805906-f534c0c0-ddbf-11e7-9443-7fe3c12957e2.png">

**Comment by bainternet** [comment]
@schneekettchen 

Few issues:
The memory limit on your server Env is lower than the minimum requirement of 64MB.

Can you try a different browser? like chrome or Firefox and see if that changes anything.

And last can you check with a WordPress Twenty15-17 theme?

**Comment by schneekettchen** [comment]
@bainternet 
Changing the theme does the trick!! Thanks for the hint. It works with twenty-17 Theme.
So I need to find out why it doesn't work with the current one. I couldn't see any errors in the chrome inspector.

**Comment by bainternet** [comment]
@schneekettchen 
Its an easy fix...

The progress bar you are seeing is called "Preloader" and you can disable it from the theme customizer settings.

**Comment by schneekettchen** [comment]
Thank you so much, you made my day!!
