### ISSUE TITLE
Switch Between Pages

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#292]
I find myself switching pages pretty frequently, which involves clicking the **x** in the bottom left corner, then **Go to Dashboard**, then **Pages**, then **Edit with Elementor** for the page/post I want to edit.

Adding the ability to switch to edit any page from within Elementor would super handy. I've mocked up what I had envisioned (https://cloudup.com/cwaDlqVcTiW). Not sure how it would scale with a large page/post structure... anyway, just an idea. 

Cheers!

**Comment by dtbaker** [comment]
What about making the menu items clickable as well? Or all links on the page (e.g. footer widget menu links). If it detects this is a page that can be edited with Elementor it should ask the user if they wish to edit this page.

**Comment by arielk** [comment]
@JoelEadeDesign I like this idea, we will figure out how to include it in our roadmap

**Comment by badcat** [comment]
As it is currently, I'd expect the text to read, **"Exit Elementor"** not, **"Go to Dashboard"**.  

WordPress has a specific page called "Dashboard", so I wondered why I would want to go there instead of just exiting Elementor.

**Comment by mjflower** [comment]
+1 on this idea. Currently have to have multiple tabs open to edit multiple pages but it would be great to have a hot key that allows you to follow a link to another page (auto save the current page) and open the followed link also in elementor if on the same WordPress site.

**Comment by eplanetdesign** [comment]
+1 on this, as it is Elementor is very clunky, Cornerstorne Page Builder has a nice page switcher.

I'd be happy with just the menu items clickable with /?elementor added to the links.

**Comment by ianstudio** [comment]
+1000 @dtbaker  @eplanetdesign That would sure be a major workflow enhancement.

**Comment by jaffa2** [comment]
+1 to this, this would make the design and updating of multi page sites so much faster.  Please please consider this feature.

**Comment by simonclay** [comment]
I think for me, just having 'Exit Elementor' which then exits the editor but remains on the same page, would solve this. I can then navigate to any other page in the site and 'Edit with Elementor' again.

**Comment by Jim-E** [comment]
Admin Page Spider Pro is pretty cool, it even adds a dropdown to the editor to change pages.

**Comment by ianstudio** [comment]
Like @simonclay says that would already be a start.. could be one button with three options:
Exit to Page
Exit to Dashboard
Preview Changes
.. Right Click of course since it's all the rage ;0)

**Comment by bentalgad** [comment]
+1 btw - CSS Hero plugin made this idea very simple by adding a cursor switcher (navigate, or select) - when you choose the navigate you can press links to switch pages, and when you choose select you use the plugin's actions:
![2018-07-17 15 34 20](https://user-images.githubusercontent.com/23374215/42817510-ff9b32f6-89d6-11e8-9f7d-bfd7fa70f984.gif)

I do think having a links tab in the Elementor panel might be much faster and easier, and of course much more easy and fast to implement.

Something like that:
![elementor-pages-switcher](https://user-images.githubusercontent.com/23374215/42818740-5e78b8e0-89da-11e8-91a6-576ff6b1da8c.jpg)

**Comment by ianstudio** [comment]
@bentalgad This cool but "only" for pages, posts etc that are published and appear in your menu or next post or whatever.. We need something more global.

**Comment by ianstudio** [comment]
@bentalgad This is cool but "only" for pages, posts etc that are published and appear in your menu or next post or whatever.. We need something more global. We basically should be able to access all content form  centralized spot, but even WP does that terribly badly.

**Comment by bentalgad** [comment]
@ianstudio what do you mean "more global"? can you give a specific example?

**Comment by ianstudio** [comment]
@bentalgad By global I mean I'd like to see Wordpress show me access to ALL my content from the toolbar (top), Pages, Posts, CPT's in dropdown menus and let me decide what to do.. Edit, Edit with Elementor, edit with Microthemer or whatever tool I have could hook into these global access menus:

I sometimes create WP menus just for that (access to stuff I want to access), and populate them with stuff I need. But Elementor totally removes the Toolbar which in itself sucks. I should be able to activate Toolbar as an option. I hate having to go back and forth to Dashboard !!!

Side story.. this guy is already providing a few clever tricks in terms of Toolbar ergonomy:
https://wordpress.org/plugins/toolbar-extras/

**Comment by swakarm** [comment]
I think there is no need to add any new widget to editor. But when we click on any link in page within elementor, It should be opened in elementor. (This type of switching will be more easy)

**Comment by drawcard** [comment]
@swakarm that would make editing widgets like the nav menu nearly impossible since you'd be clicking on and launching nearly everything.

In general I think it might be a confusing user experience for a toggle to turn on / off clickability in content - really the editor window should be strictly for editing content alone. But at the same time some sort of "Jump to" mechanism would be great, outside of the editor, within easy reach at all times (1 click away). 

What if we had a "Switch to" feature, a bit like the proposal in OP's mockup but just had a text box where you can type in the page name you want to go to, and the filter system would find it? This would work for sites with hundreds of pages of content that you didn't want to hunt around in. It could also use the same filter mechanism that the Link panel uses:

![image](https://user-images.githubusercontent.com/1435638/48113237-ea1e3a00-e2a9-11e8-8e65-ffb26b142b9b.png)

It could even have a history below it, remembering the last 5 pages you visited so you wouldn't have to type the same page name over and over.

**Comment by bentalgad** [comment]
The 2.3.0 release adds a "finder" amazing feature which solves this issue perfectly! #6068

**Comment by bentalgad** [comment]
I personally think finder does the job, and need nothing more...

**Comment by gravnetic** [comment]
Finder should be the first option in an actual page link option which is shown beautifully above by bentalgad and now he says finder is good enough.  I really think that Spider Menu has it the best at this time.

**Comment by Paul-Morris** [comment]
> The 2.3.0 release adds a "finder" amazing feature which solves this issue perfectly! #6068

I didn't realize this could be used to switch pages. Thanks that saves a lot of time

**Comment by yannickh2** [comment]
Somehow the Finder does not show at my colleagues version of elementor?

**Comment by Y2KWebs** [comment]
Does not work fine with WPML
