### ISSUE TITLE
Blank space to right of drop cap is too large

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#2920]
I suppose this issue is a matter of taste, but no matter what letter is formatted as a drop cap - from I's to M's, I find that the space to the right of that drop cap is simply too wide. I use only proportionally spaced fonts. Please consider adding a parameter to adjust the spacing to the right of the block.

**Comment by bainternet** [comment]
@JosiahCarberry 

please provide an example and steps to repeat.

**Comment by JosiahCarberry** [comment]
This is not a bug that has steps to repeat. It is simply a design issue, so far as I can see. 
Here are some examples, where the first paragraph on each page has been styled to use a drop cap: 
https://www.3cs.ch/what-is-creativity/
https://www.3cs.ch/manifesto-service-management-agility-summary/
https://www.3cs.ch/multitasking-kanban-neuroscience/

**Comment by bainternet** [comment]
Well then like you said its a matter of taste.

You can overwrite it using custom CSS:

```CSS
.elementor-drop-cap{
     margin-right: 5px !important;
}
```
default is 10px.

**Comment by JosiahCarberry** [comment]
It is precisely _because_ it is a matter of taste and because different characters might require different levels of kerning that the spacing would be better set on a case by case basis, if desired, and not using a one size fits all solution.
That solution, by the way, is not in setting margin-right of elementor-drop-cap.
