### ISSUE TITLE
Can't get the widget settings with the hooks

### ISSUE THREAD

**Issue by EdenK** [pojome/elementor#2921]
Hi,

I tried to get the widget settings with the hooks and I get an error. It might help this issue too [#2034](https://github.com/pojome/elementor/issues/2034)

I think if we could get an access to the settings we could create much more dynamic elements thats based on the settings that we set earlier.

For example create repeater field and then with the hook we could create a section for each element in the repeater and its maybe remove the need for nested repeaters.

```
[11-Dec-2017 01:30:20 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::_get_items() must be of the type array, null given, called in ...\wp-content\plugins\elementor\includes\base\controls-stack.php on line 882 and defined in ...\wp-content\plugins\elementor\includes\base\controls-stack.php:191
Stack trace:
#0 ...\wp-content\plugins\elementor\includes\base\controls-stack.php(882): Elementor\Controls_Stack::_get_items(NULL, 'widgetType')
#1 ...\wp-content\plugins\elementor\includes\base\widget-base.php(488): Elementor\Controls_Stack->get_data('widgetType')
#2 ...\wp-content\plugins\my-plugin\widgets\my-widget.php(79): Elementor\Widget_Base->get_raw_data()
#3 ...\wp-includes\class-wp-hook.php(286): {closure}(Object(Widget_My_Widget), Array)
#4 ...\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 ...\ in ...\wp-content\plugins\elementor\includes\base\controls-stack.php on line 191

```

```
add_action( 'elementor/element/{element}/{section}/after_section_end', function( $element, $args ) {
	$settings = $element->get_raw_data(); // return the data but getting fatal error after too
	$settings = $element->get_settings(); // just the error
	$settings = $element->get_active_settings(); // just the error
}
```

**Comment by bainternet** [comment]
@EdenK 

can you paste my-plugin\widgets\my-widget.php here so we can see what is the reason for the fatal error.

also please check if it happens for you on a native widget, because we can't replicate.

**Comment by EdenK** [comment]
I tried with native widget to do something like this and I get the same error.
```
add_action( 'elementor/element/heading/section_title/after_section_end', function( $element, $args ) {
	$settings = $element->get_raw_data();
}, 10, 2 );
```

My plugin code

```
if ( ! defined( 'ABSPATH' ) ) exit;

define( 'MY_PLUGIN_VERSION', '1.0.0' );
define( 'MY_PLUGIN_URL', plugins_url( '', __FILE__ ) );
define( 'MY_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

add_action( 'elementor/widgets/widgets_registered', function( $widgets_manager ) {
	require MY_PLUGIN_PATH.'/widgets/my-plugin.php';
	$widgets_manager->register_widget_type( new Widget_MY_Widget() );
} );

add_action( 'elementor/element/my-plugin-elementor/tests_section/after_section_end', function( $element, $args ) {
	print_r($element->get_raw_data());
}, 10, 2 );
```
My widget code
```
if ( ! defined( 'ABSPATH' ) ) exit;

use Elementor\Widget_Base;
use Elementor\Controls_Manager;
use Elementor\Repeater;
use Elementor\Utils;

class Widget_My_Widget extends Widget_Base {

	public function get_name() {
		return 'my-plugin-elementor';
	}

	public function get_title() {
		return 'my plugin';
	}

	public function get_icon() {
		return 'fa fa-bar-chart';
	}

	protected function _register_controls() {
		Controls_Manager::add_tab('mytab', 'My Tab');

		$this->start_controls_section(
			'tests_section',
			[
				'label' => __( 'tests', 'plugin-domain' ),
				'tab' => 'mytab',
			]
		);

		$this->add_control(
			'tests',
			[
				'label' => __( 'tests', 'plugin-domain' ),
				'type' => Controls_Manager::REPEATER,
				'default' => [
					[
						'test_label' => __( 'test label #1', 'plugin-domain' ),
					]
				],
				'fields' => [
					[
						'name' => 'test_label',
						'label' => __( 'Label', 'plugin-domain' ),
						'type' => Controls_Manager::TEXT,
						'default' => __( 'test label' , 'plugin-domain' ),
						'label_block' => true,
					],
					[
						'name' => 'test_values',
						'label' => __( 'Label', 'plugin-domain' ),
						'type' => Controls_Manager::TEXT,
						'default' => __( 'test label' , 'plugin-domain' ),
						'label_block' => true,
					],
				],
				'title_field' => '{{{ test_label }}}',
			]
		);

		$this->end_controls_section();
	}

	protected function render() {
		// workaround can pass the settings like this with hook inside the render
		do_action('my_plugin_before_render', $this->get_settings());
		echo "ok";
	}

}
```

**Comment by EdenK** [comment]
What I tried not going to work for me anyway because the repeater item `_id` is changed when we change the order.

So I can't save the new section base on this `_id` and it's not dynamic enough that when I add a new item to the repeater it will create the section right away.

I need to refrash in order to see this new sections.

So I will try to find a different way to this probably will have to create alot of sections and use the condition to check how many sections to show.

**Comment by bainternet** [comment]
can you explain what exactly you are trying to do, maybe I'll be able to help in suggesting a solution.

**Comment by EdenK** [comment]
I tried to create a repeater field and each field in the repeater field should have create a new section with fields.

I end up doing field with the amount of sections that needed and I created all this sections from the start just loop section(n) and I just show or hide them with condition.

BTW you guys have to improve the docs also about the condition/conditions too much time it took me to hide the sections if the `field.amount > i`.

**Comment by bainternet** [comment]
@EdenK 

I'm happy to tell you that we are actively working on a developers API and actually the condition/conditions also got an upgrade in the next few updates.

As for your question, if I understand correctly, Then a repeater cant handle nested repeaters/fields/sections. so your solution is actually a correct one.

Glad you figured it out.
