### ISSUE TITLE
Custom CSS code field on pages or each widgets.

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#2922]
Is there any way to create a custom css code field?
I need to add a custom css field in each widgets. ( also each pages if it's possible )

I think I should use "textarea" control or "raw html"
But selector array seems to be not working for custom css. 
It seems to be css class name => values.

`'selectors' => [
            '{{WRAPPER}} .title' => 'color: {{VALUE}}',
        ],
`

Is there any way to create custom css code by textarea or raw html control? 
I know pro version has it. But not everybody uses pro version.

Thank you!

**Comment by bainternet** [comment]
The selectors array can only provide a single value and not multiple rules as key= > value.

It's not how the Custom CSS work.

So its Simple, Everybody should go pro :)
