### ISSUE TITLE
already existing 'issues' and a little big xmas whishlist ...

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#2924]
loving elementor. also loving the great work of you elementor guys and all the efforts and recent development.
you're already doing a great job, and theres a lot of nice features.

but i want to point out three missing things that i am urgently waiting for (and obviously not only me!) that would make elementor REALLY top notch.

1.: custom query options for posts and cpt. /ref. #1748 (highest recommendation!)

2.: custom fields accessibility for own cpts - no matter if hand-coded or from pods, toolset or alike. /ref. #1071

3.: custom media query breakpoints. /ref. #78 

all three whishes remaining unfulfilled for a long time, up 'till now - but as 2018 is growing near and new upcoming projects gaining shape it would be highly appreciated to have them to work with.
so please mr. santa mark my words and make my whishes come true. it will make my work fuc***g awesome at the eve of the new year!

big, big thanks in advance and cheerio 🥇 :)

**Comment by black-eye** [comment]
+1 :)

**Comment by elnipa** [comment]
+1

Support said: "These features are indeed under development."
Let's hope it won't take long anymore.

**Comment by bainternet** [comment]
As you guys know and can see here in the repo, we have many requests which we do try to implement, but as far as ETA goes we can't really commit to a date right.

But as long as the issue remains open or labeled it will get a solution/response/implementation.

Thanks for the suggestions
