### ISSUE TITLE
Load Additional Bootstrap CSS and JS in Widget Admin panel of Elementor FrontEnd.

### ISSUE THREAD

**Issue by anamwp** [pojome/elementor#2925]
Hello, 
I create a custom widget it works fine in the widget area. 
But When I add this widget to page from frontend my Bootstrap CSS and JS is not loaded in the frontend customizer panel of Elementor. Is there any proper way to solve it ? 
Here I attach my screenshot. 
https://tx-snaps.s3.amazonaws.com/anam/Elementor__Sample_Page_2017-12-11_18-41-15.png
Thanks is advance.

**Comment by bainternet** [comment]
@anamwp 

Sadly no, there is no real way to "Solve" it. the proper way would be to create an elementor Widget using Elementor's provided API and controls and not use external JS/CSS in the panel.

Please see this [demo elementor widgets](https://github.com/pojome/elementor-hello-world) to get started.
