### ISSUE TITLE
Page Jumps - Header Overlaps

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#2928]
Page-Jumps with fixed headers on scroll are currently not doable, as page jumps to the middle of the section and the headers overlap, a custom css has got to be used, all the other elements to create page jumps are there, just a section where negative height can be put is missing and would be awesome to have and would save a ton of time.

For a non coder like me, I struggled 03 days to find this simple custom css,
h2::before { 
  display: block; 
  content: " "; 
  margin-top: -150px; 
  height: 150px; 
  visibility: hidden; 
  pointer-events: none;
}

It still messes up with sections below and above and editing becomes a pain.

Kindly consider it as a feature enhancement if possible, many people like me would be well served and love working with elementor without worrying about codes.

<img width="300" alt="screenshot_11" src="https://user-images.githubusercontent.com/33909786/33838330-44f38394-deb5-11e7-9b1f-7e9cc6d3adf9.png">

![screenshot_12](https://user-images.githubusercontent.com/33909786/33861043-a75db134-df01-11e7-815e-2790754bfbb2.png)

**Comment by bainternet** [comment]
@Dentalicious 
If in "Page-Jumps" you mean internal anchor links then what you are looking for is called [Menu Anchor Widget](https://docs.elementor.com/article/62-menu-anchor).

**Comment by Dentalicious** [comment]
Yes, internal anchor links, but if one has a fixed header on scroll then the heading gets hidden and the header overlaps.
The image attached showcases.
Menu Anchor Widget doesn't negate that.
