### ISSUE TITLE
Enqueue minified and concatenated scripts

### ISSUE THREAD

**Issue by tareq1988** [pojome/elementor#293]
Right now Elementor uses few scripts and css files and it loads in the frontend. It would be nice if the Grunt task would concat and minified the styles and scripts in single files for production, it would reduce some extra HTTP requests without using any minify plugin.

**Comment by yehudah** [comment]
Hello,

Thanks for the feedback.

This is in our road map and we hope to release it in the next few weeks.

**Comment by arielk** [comment]
Fixed https://github.com/pojome/elementor/commit/daa473692d85ccf7da96b4c0655d23f0c9028ca8
