### ISSUE TITLE
Copying the markup styles while inline editing

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#2930]
When I copy and paste the text from the other page, the text editor, or even the other Elementor's inline item, the unwanted markup and styling is pasted aswell. See the screenshot - that's the dummy text copied from the Image box heading element and pasted into another heading element.

![obrazek](https://user-images.githubusercontent.com/5634870/33847165-f62abb7a-dea9-11e7-99e5-c4d4c5e8c013.png)

I think this is highly unwanted behaviour, since all the extra formatting should be stripped away. Maybe except the tags Hx, B and I tags (the ones present in the inline editor).

I know, I could use `shift+ctrl+V` instead of `ctrl+V`, but tell it to my clients... ;-)
Maybe the shortcodes should be reversed - `shift+ctrl+V` for the full paste, `ctrl+V` for the plain text.

Seems like a bit annoying "feature" in otherwise excellent inline editing experience.

**Comment by bainternet** [comment]
@black-eye 

few things, first we cant overwrite the native `ctrl+V` second I agree that its unwanted result but not unwanted behavior. 

The control lets you paste text, and we can't control the clipboard contents, if you copy and paste HTML you will get these results.

and like you said we already provide the `shift+ctrl+V`.

Thanks for the feedback.

**Comment by black-eye** [comment]
Well, let me ask you another way.
I'm using the technique for sanitizing the input pasted into TinyMCE editor, based on the post here: https://jonathannicol.com/blog/2015/02/19/clean-pasted-text-in-wordpress/

It uses the filter `tiny_mce_before_init` to strip out the unwanted markup. It works just fine, even in the TinyMCE Elementor's Edit box. Can I use something similar for the inline editor?

**Comment by black-eye** [comment]
I know, the issue is closed for a while, so I'm not sure if anybody reads it, but I'm still wondering if there is some way, how to sanitize the pasted text into the inline text editor (as it is possible for TinyMCE).

Thanks for your answer.
