### ISSUE TITLE
PHP Notice issue - $cc_header is not defined (elementor pro) 

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#2934]
## Description

Undefined variable: cc_header in /home/ncrco/public_html/wp-content/plugins/elementor-pro/modules/forms/actions/email.php on line 261

## Steps to reproduce

My usecase: Elementor Pro + Gamil SMTP plugin

## Solution

Replace line number 256 in the php file with:
		} else $cc_header = "";

**Comment by bainternet** [comment]
@Mulli 

Thanks for reporting will be fixed soon.

**Comment by Mulli** [comment]
Hi Raz

 

Thanks.

 

Please see if you can reduce the following error list
That exists for quite some time and only grows with new releases.

System info attached

 


TypeError: Cannot read property 'errors' of undefined
at https://ncr.co.il/wp-content/plugins/elementor/assets/js/editor.js?ver=1.8.5 - 7435:36
2017-11-29 19:13 +00:00
x 63 times

TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
at https://ncr.co.il/wp-content/plugins/elementor-pro/assets/js/editor.js?ver=1.10.0 - 898:49
2017-11-28 13:16 +00:00

Error: An "el" #elementor-panel-elements-search-area must exist in DOM
at https://ncr.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.js?ver=2.4.5 - 1236:11
2017-11-27 19:04 +00:00

ViewDestroyedError: View (cid: "view18819") has already been destroyed and cannot be used.
at https://ncr.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.js?ver=2.4.5 - 1810:9
2017-11-23 15:22 +00:00

Error: An "el" #elementor-panel-elements-search-area must exist in DOM
at https://ncr.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.js?ver=2.4.5 - 1236:11
2017-11-23 14:02 +00:00

Error: An "el" #elementor-panel-elements-search-area must exist in DOM
at https://ncr.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.js?ver=2.4.5 - 1236:11
2017-11-18 14:31 +00:00

TypeError: self.ui.triggerButton is undefined
at https://ncr.co.il/wp-content/plugins/elementor/assets/js/editor.js?ver=1.8.4 - 7087:5
2017-11-15 14:02 +00:00

TypeError: Cannot read property 'errors' of undefined
at https://ncr.co.il/wp-content/plugins/elementor/assets/js/editor.js?ver=1.6.5 - 7600:35
2017-08-27 12:25 +00:00
x 2 times

TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
at https://ncr.co.il/wp-content/plugins/elementor/assets/js/editor.js?ver=1.6.5 - 3176:49
2017-08-27 12:15 +00:00

TypeError: $(...).nivoSlider is not a function
at https://ncr.co.il/wp-includes/js/jquery/jquery.js?ver=1.12.4 line 2 > eval - 3:13
2017-08-26 06:33 +00:00
x 3 times

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal

**Comment by bainternet** [comment]
@Mulli 

The PHP notice is fixed and will be released with the next (Major) version.

as for the error log, I don't see anything specific. if you have a specific issue please feel free to open a new issue.

thanks for reporting.
