### ISSUE TITLE
Auto classes for own page templates?

### ISSUE THREAD

**Issue by zaehlpixel** [pojome/elementor#2936]
Hi,
I often run into the problem that I generate a page template and save it in the library, not adding classes to each and every element before. After using it on 20+ pages, the client tells me to add a margin somewhere - and I need to do it on every 20 pages. Is there a workaround to solve this problem just in my style.css and adapt the rule on all pages that are generated through this one page template? If not, is it possible to auto-add classes to page template elements on saving - and adding them to the pages DOM when a new page is filled with this template?

Or do you have a more simple solution to this - very often occuring - problem?

**Comment by bainternet** [comment]
If this is your usual workflow, then I would suggest you start to design your "page template" using [Global Widgets](https://docs.elementor.com/article/100-global).

this way you can update all pages by updating the global widget and not updating one by one.
