### ISSUE TITLE
IE11 doesn't show correctly my webpage built with Elementor on Wordpress

### ISSUE THREAD

**Issue by jcpaque** [pojome/elementor#2937]
Hello,
I have a little problem with Elementor. When I add some text in the middle or at the bottom of an element, IE11 shows the text at the top.
Also, when I set a fixed picture in an element, the picture is "jumping" when scrolling.
This only happens with IE.

Here are some webpage examples : 
http://horeca-marketing.com/
http://horeca-marketing.com/index.php/nos-services/optimisation-de-sites-web/

On chrome : 
![image](https://user-images.githubusercontent.com/18294629/33909563-56cf6b32-df8c-11e7-90de-9b21276883c6.png)
On IE : 
![image](https://user-images.githubusercontent.com/18294629/33909602-7a00acba-df8c-11e7-8c4b-9138b1bf8ca4.png)

Any solution ?

**Comment by bainternet** [comment]
This is kind of a known issue with IE11 and `min-height`,`flex`,`align-items`...

The quickest and simplest way around it is to set the `height` the same as the `min-height`.

https://css-tricks.com/snippets/css/cross-browser-min-height/

**Comment by jcpaque** [comment]
Thank you very much !

**Comment by mattmadesimple** [comment]
Hi, I have the same problem with IE11. How can I easily fix this with Elementor? I tried the link and added it to my custom css. Unfortunately it didn't work.
