### ISSUE TITLE
Inline edit doesn't work if you delete all the content

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#2948]
When you delete all the text in inline editing you cannot write inline anymore.(you can write can write in the content box thankfully)

**Comment by dudaster** [comment]
You can recreate it like this:

1. Go to a text so you can edit inline
2. Press ctrl(command) + a
3. Try to write something
4. ???
5. Make money!

**Comment by bainternet** [comment]
@dudaster please make sure you are running the latest version and test again.

If you still have this issue please feel free to reopen

**Comment by dudaster** [comment]
The issue is still there. Sorry but it's not fixed.
