### ISSUE TITLE
Elementor & Toolset Integration

### ISSUE THREAD

**Issue by DrMohamedGamal** [pojome/elementor#2949]
Hello , I'm interesting in Elementor Plugin and want to use with Toolset Suite
The problem is 
1- Elementor widget can't contain a right views shortcode
eg. When a views settings is related to the current post where the view is being viewed , no posts appear as the views grab posts that related to the widget template post ! 

2- Also , if use toolset shortcodes eg. [wpv-post-title] , [wpv-post-link] the result is the title and the link of the template page not the main post where the widget is being visible

3- I need to create a Template containg views shortcode eg. [wpv-post-title] , [wpv-post-link] with Elementor and put it in Toolset Layouts to be automatically applied for all posts

4- When I use the toolset cred if I put a report link as the current post url it also relay to the elementor template page

So Please make it compatible with toolset views especially the Elementor Pro Widgets
Cheers!

**Comment by elnipa** [comment]
A Toolset integration would be highly appreciated. Right now this incompatibility is preventing me from switching to Elementor in multiple projects.

This seems to be 4th opened thread concerning this issue. Unfortunately, there is still no official comment from the Elementor team.

**Comment by DrMohamedGamal** [comment]
I know it would be highly appreciated , as Toolset package really the best tools for WP Development and Elementor is such a brilliant Frontend editor , I hope there is a solution to make people able to do really great projects

**Comment by Nelmedia** [comment]
I totally agree... I'm working on an Astra site with Elementor Pro and Toolset... Didn't know that we couldn't use Elementor with it... That's really a shame. Knowing that, I would have gone with Thrive Architect instead of Elementor as a page builder...

**Comment by bainternet** [comment]
In Elementor pro v2 we added partial support for toolset fields.

thanks for the suggestions.

**Comment by ljubacanoa** [comment]
Can you please be kind and write what it mean "partial support for toolset fields", as even until now Toolset was fully compatible with Elementor (but not to be used in the way described at the begin of this topic). Issue was that Editor didn't supported directly shortcodes dialogue (we needed to grab it and paste).

**Comment by ljubacanoa** [comment]
**Woov!!!!** It is seriously entire new level and life for developing. Guys, you are **GENIUS**.
It works like charm. Also Gallery. I can't to believe it. However, I still can't understand, what you mean with 'partial', as I can't see that there is something what now working? We will need now Views only for 'specialities' (search, etc - when conditional is apply), but no more needs for Layouts, Content Templates, as I can't see what not working.

Yeap, it still not popup Toolset Shorcode button in Editor, but....who care.
Great job.

**Comment by ljubacanoa** [comment]
Maps not working, but not big deal as it could be done with workaround easily.

**Comment by elnipa** [comment]
Is anyone able to select custom post fields in Elementor Dynamic Tags that were created with Toolset Post Types?
The list ist empty even if the correct post type is selected in the preview settings.

Any ideas how this can be fixed?

**Comment by Nelmedia** [comment]
@elnipa They said support for ACF and Toolset will be included in the next release (minus maybe small bug fix releases)...
