### ISSUE TITLE
Bug on the Shortcode Element

### ISSUE THREAD

**Issue by rtthemes** [pojome/elementor#2951]
Hi,

Shortcode element doesn't work correctly when you edit the page. Here is a video https://cl.ly/0K2X3E463D0c

Also, post loops are missing one class name which is the post type. For example, WooCommerce posts should have "product" but it is missing. Please see https://cl.ly/1y3M1W1L2q0g

P.S. Also tested with PHP 7.0.12

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 ()
	MySQL version: 5.5.56
	PHP Version: 5.6.32
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.1
	Site URL: http://tense-plover.w6.poopy.life
	Home URL: http://tense-plover.w6.poopy.life
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.8.10
		Author: Elementor.com

	Sandbox
		Version: 1.0.0
		Author: Soflyy

	WooCommerce
		Version: 3.2.6
		Author: Automattic

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

== Debug ==
	Errors: There are no errors to display

**Comment by bainternet** [comment]
@rtthemes 

I can't replicate this issue, can you try and upgrade to 1.8.11?

**Comment by rtthemes** [comment]
@bainternet I've tried the new version but no luck.

You can try yourself;

Login: http://tense-plover.w6.poopy.life/wp-admin/ 
Username: demo 
Password: hl0e5GE7Hi8M 

Edit this page: http://tense-plover.w6.poopy.life/test-page/ 

WooCommerce products will return empty and missing "product" class name. The missing "custom post type" class name issue happens almost every post type including Elementor Pro widgets.

**Comment by norewp** [comment]
The shortcode will return whatever attributes have been assigned to it and this is handled by WooCommerce. The Elementor shortcode widget merely acts as an input box while the content is printed out by the core function do_shortcode()!

**Comment by bainternet** [comment]
@rtthemes 

Not something we can replicate,

Please contact our support and see if they can help you. support@elementor.com

**Comment by rtthemes** [comment]
@bainternet @norewp The same issue exists on the Elementor Pro's WooCommerce Element, i don't think it is just related to the do_shortcode() or WooCommerce. 

@bainternet I'm not seeking for help, just trying to contribute! Thanks anyways.

**Comment by bainternet** [comment]
@rtthemes 

And we thank you for that but again, we can't replicate this issue.
