### ISSUE TITLE
API Extending Typography

### ISSUE THREAD

**Issue by djekanovic** [pojome/elementor#2953]
Somehow i got to this file in docs. But it's not officialy visible, only via direct link, can you make it public, or whatever the problem is? I was searching for how to extend plugin with typography for an hour or so. Finally got it.
https://github.com/pojome/elementor/blob/1b9044ebd84d86ef1402a8997d4fed1c7ae72a84/docs/content/controls/_group_control_typography.md

Thanks!

**Comment by bainternet** [comment]
@djekanovic 

We currently are working on organizing and extending our Developer docs.

for now, you can access the docs that we do have from [here](https://github.com/pojome/elementor/blob/master/docs/README.md)
