### ISSUE TITLE
Elementor "hangs" ("Elementor loading") when NextGEN Gallery Plugin is installed

### ISSUE THREAD

**Issue by l3enito** [pojome/elementor#296]
deactivating NextGEN Gallery will let Elementor work again.

**Comment by gk25** [comment]
I am having the same issue - all other plugins deactivated: Elementor works, - activate NextGen: Elementor stuck in loading screen.

**Comment by KingYes** [comment]
Fixed by https://github.com/pojome/elementor/commit/a669c7b3b38836b88cdf6c28fb69a1a21a42cab5

Thanks guys :)

**Comment by Fdiversos** [comment]
ANYBODY FOUND A SOLUTION?
I've activated NGG Plugin and now i can't deactivate once after it, Elementor does not work anymore.....
So i've reactivated the plugin....
Just a few hours ago....i've inserted a Slider from NGG in a column in my main page....and now i can't edit it by elementor anymore....
The Browser shows up a clena page with the following message:
![image](https://user-images.githubusercontent.com/9354763/44615707-2992c980-a817-11e8-91b9-60969640b848.png)
