### ISSUE TITLE
Plugin Activation Syntax Error: Unexpected T_FUNCTION on line 55 of elementor.php

### ISSUE THREAD

**Issue by Zach-Toth** [pojome/elementor#2960]
Plugin Activation Syntax Error: Unexpected T_FUNCTION on line 55 of elementor.php

Elementor Version 1.8.10
Running php 5.2, Wordpress 4.9.1, Generate Press Theme

Here are lines 53-58 of my elementor.php

	// Fix language if the `get_user_locale` is difference from the `get_locale
	if ( isset( $_REQUEST['action'] ) && 0 === strpos( $_REQUEST['action'], 'elementor' ) ) {
		add_action( 'set_current_user', function() {
			global $current_user;
			$current_user->locale = get_locale();
		} );`

**Comment by bainternet** [comment]
Elementor needs PHP 7.0 or newer to work. it should also work on 5.4 and up but on 5.2 you are missing key PHP language features like Namespaces and anonymous function which Elementor utilizes.
