### ISSUE TITLE
Editor is not loading. blank.

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#2961]
Editor is not suddenly working.

After SSL was enabled, it was working fine. Because I changed mixed content or some wrong URL (http to https).
It suddenly doesn't work. 

I have tried many ways. But I can't find how to edit work. It just show a blank in the_content part.
1. Increased PHP memory, wp memory ... etc.
2. Enabled "Switch Editor Loader Method"
3. Deactivated all of plugins except elementor.
4. Replaced new URL. .

Any solution for it? 

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.27
	PHP Version: 7.0.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.1
	Site URL: https://multinetwork.abc.com/subdomain
	Home URL: https://multinetwork.abc.com/subdomain
	WP Multisite: Yes
	Max Upload Size: 256 MB
	Memory limit: 3072M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Whale/1.0.37.16 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 1.8.10
		Author: Elementor.com

== Debug ==
	Errors: There are no errors to display

**Comment by pulla** [comment]
Additionally... 
It redirects to preview page.
When you click edit page, it shows this page.
https://multinetwork.abc.com/subdomain/wp-admin/post.php?post=9289&action=elementor

and some loading... and it redirects to here.
https://multinetwork.abc.com/subdomain/?elementor-preview&1513328956098

Do you have a preview page? 

Why it redirects to preview page from editor?
Please advise and need a help.

**Comment by bainternet** [comment]
please contact our support via support@elementor.com and see how they can help you.
