### ISSUE TITLE
Hello everyone. Elementor for RTL has some problems, First of all Center Justify, it cannot have a center justify for RTL as well.

### ISSUE THREAD

**Issue by lovetoknowmore** [pojome/elementor#2963]

**Comment by bainternet** [comment]
@lovetoknowmore 

can you elaborate? provide examples? describe the actual issue?

**Comment by lovetoknowmore** [comment]
Hello, thanks for your reply,  perhaps you know justify. it's justify from left, from right, middle, and justified, it means when you have a long paragraph and you use the justified, your whole sentence from left and right will be in same vertically line. in English it can do, but for other languages which is write from Right to Left, Justified does not work

**Comment by bainternet** [comment]
@lovetoknowmore 

Thanks, As far As I know ( and just now tested again in Hebrew) justify works fine in RTL languages.

So unless you have a specific case where its not working for you, I can't replicate this issue you describe.

**Comment by lovetoknowmore** [comment]
hello, thanks for your reply. ok, now i send you a text. you can check it

این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.این یک متن برای تست کردن المنتور به زبان فارسی که از راست به چپ نوشته میشود میباشد. اگر اپشن جاستیفاید 
 بتواند روی این متن کار کند پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.پس خیلی عالی خواهد بود، اما من که امتحان کردم و نشد.
 you can check this text. and if it's work please show me picture
beside: in persian language, some widget automatically change the name from english to persian, i didn't check in another languages, and some of them still english.

**Comment by bainternet** [comment]
Again I see no issue:
I aligned the text Left -> Right -> Center -> Justify all working.
![elementor-rtl-align](https://user-images.githubusercontent.com/660572/34325283-1f5b8736-e896-11e7-89a5-41f10d849025.gif)
Thanks.

**Comment by lovetoknowmore** [comment]
hello, thanks for your reply, some question: 1- you made this video by which software, i make same and send you. 2- maybe it's because of theme? i use ocean wp. AND SORRY FOR DLEAY IN REPLY :-)

**Comment by lovetoknowmore** [comment]
do you have skype?

**Comment by lovetoknowmore** [comment]
![screen shot](https://user-images.githubusercontent.com/31369050/34411251-8d74c0ca-ec10-11e7-9194-4a40c1e50252.png)
i have not justified key in here, only : left, right, center
and i found that screen capture too.

**Comment by ericadyson** [comment]
Hi. I just can't get the full stop in the right location. ie I get right text alignment but not rtl paragraph alignment. How can I get this. I used to use a plugin WP-RTL but this doesn't seem to work with Elementor. Help please! What am I doing wrong?

**Comment by ericadyson** [comment]
You need to add css to your theme or widget

p: {direction: rtl;} and I added the same for div which seems to work for all widgets (thank goodness).
