### ISSUE TITLE
White label source-code

### ISSUE THREAD

**Issue by Tim2468** [pojome/elementor#2966]
I think, it would be a good idea, to implement the possibility to white label the source-code of elementor.
At the moment the public source-code looks like this:
![elementor-source-code](https://user-images.githubusercontent.com/34579661/34075904-768b197a-e2d5-11e7-827d-181bac114047.PNG)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but maybe we will look into it in the future.

Thanks for the feedback.

**Comment by axiomteck** [comment]
yes white label will be a great one
