### ISSUE TITLE
Is there a way to put some custom code in the head of the page?

### ISSUE THREAD

**Issue by lilianmurciaart** [pojome/elementor#2967]
Is there a way to put some custom code in the head of the page? Before Elementor you could do this by editing the header.php file of the template, but now, elementor eliminates all the code from the template, and there is no way (at least an obvious way) to do this. For me this is very important, because I like to put some <meta> tags in the code and also this is a perfect way to implement Google Analytics without using any other plugin (I'm not a fan of using many plugins when I build a site). Can you help me with this?
PD: I use Elementor Canvas
Thanks!

**Comment by bainternet** [comment]
Elementor canvas uses the `wp_head()` which calls every function hooked to `wp_head' which in turn means that every plugin like [Header footer](https://wordpress.org/plugins/header-footer/) would work just fine for adding `head` tag code.

But if you want to do it without a plugin then you can simply hook your code in the theme functions.php ex:

```PHP
add_action( 'wp_head', function(){
    ?>
    <!-- your code goes here -->
    <?php
});
```

**Comment by nohl** [comment]
Elementor is amazing, however, the authors of the Astra theme made a good point that you should not link tracking code to your theme. They recommended a free plugin that adds header and footer code regardless of selected theme. "Insert Headers and Footers"

Astra Article: https://wpastra.com/docs/add-custom-javascript-code-astra/
Wordpress repository plugin page: https://wordpress.org/plugins/insert-headers-and-footers/

**Comment by dukuo** [comment]
I agree with @nohl, but i'm looking on how to add browser color support and the only way is to put a `<meta />` tag inside the `header` `html` tag so it would be a waste to use a plugin just for that. A child theme with a functions.php seems to be the way to go, although it is a bit cumbersome though.

**Comment by shilo-ey** [comment]
ref: #10586
