### ISSUE TITLE
BUG style Gallary paddin right

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#2972]
widget Gallary
bug padding last element
if column 4 element should be style
```
figure.gallery-item:nth-child(4n) {
    padding-right: 0;
}
```

if 2 element, 2n
etc

My English is bad, but I think the meaning is clear

**Comment by bainternet** [comment]
@ravilrrr 

thanks for reporting,

Are you sure it's not coming from your theme?

**Comment by ravilrrr** [comment]
![2017-12-18_12-33-09](https://user-images.githubusercontent.com/5197026/34096782-1388f074-e3f0-11e7-9f85-c150d61b3390.png)

I understand that it was the plan, but I think it was a wrong decision.

>> Are you sure it's not coming from your theme?
Yes.

**Comment by bainternet** [comment]
@ravilrrr 

I see what you mean, anyway, we don't like changing and overloading theme styles by default that was and is still the plan.

Thanks for the suggestion.
