### ISSUE TITLE
z-index and custom css form

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#2973]
see screen

![z-index](https://user-images.githubusercontent.com/5197026/34082905-7344cb52-e380-11e7-8de6-e26b09f6e890.PNG)

**Comment by bainternet** [comment]
@ravilrrr 

Can you explain a little?

**Comment by ravilrrr** [comment]
Good
![good](https://user-images.githubusercontent.com/5197026/34097053-1924a66c-e3f1-11e7-8dcc-be7563e0d0c3.PNG)

Bad
![bad](https://user-images.githubusercontent.com/5197026/34097542-dfc12542-e3f2-11e7-8d0e-219a0885e605.PNG)

**Comment by bainternet** [comment]
@ravilrrr 

thanks, I'm asking for data like browser and how to replicate.

**Comment by ravilrrr** [comment]
browser  firefox quantum 57.0.2 (64-бит)
and chrome 63.0.3239.84

replicate
1. insert Custom CSS over 15 lines
2. Scroll Up
3. Click icon Exit

Solution:
add z-index 1 in .elementor-panel .elementor-control-type-code

**Comment by bainternet** [comment]
Thanks,
What version of Elementor and Elementor Pro are you using?

**Comment by ravilrrr** [comment]
Elementor - 1.8.10 | By Elementor.com |  
-- | -- | --
Elementor Pro - 1.11.0 | By Elementor.com

**Comment by bainternet** [comment]
Try Upgrading both and clear browser cache.

Elementor 1.8.11
Elementor pro 1.12.0

**Comment by bainternet** [comment]
@ravilrrr 

we can't replicate in the latest versions, If you still see this issue please contact our support@elementor.com.

thanks.
