### ISSUE TITLE
[Feature Request][Pro] Enhanced forms

### ISSUE THREAD

**Issue by silvascreen** [pojome/elementor#2974]
The Forms section needs help and would work better with Elementor development rather than 3rd party. I have seen a number of feature request for forms. This would be a request to have all those features and more added to the current form widget. 

1. Pop up (or light box) for forms - pop up forms for Elementor works for now but needs work
2. Ability to add page break forms to create if this/then that questionnaires
3. Required checkboxes for terms and conditions (mutliple)
4. Multiple form answer options. Eg: answer question with multiple buttons, checklist, etc. 
5. Ability to send attachment upon submission

I am using sites like lending tree or large insurance companies as an example. They have great converting lead capture forms that act like a basic questionnaire. 

They basically use the rule of investment where if someone has invested the time to answer your questions they are more likely to give their information at the end. 

Please let me know how many people would need to request these features for you to consider the making these changes.

**Comment by momo-fr** [comment]
I agree this request.

**Comment by ThrudUK** [comment]
Or better yet, styling for Gravity forms etc

**Comment by bainternet** [comment]
@silvascreen 

We are currently working on adding features to our forms, but I can tell you that we are not going to add the whole list you've listed,

1,2) Either using 3rd party elementor integration or form plugin.
3) we are adding "acceptance checkbox" field which is a single **required** checkbox and you can add as many as you like. 
4) not really sure what you mean here but you already have an option to add radio buttons and checkboxes.
5) We are also adding an upload field.

Hope this will come out soon.

**Comment by bainternet** [comment]
Acceptance checkbox and Upload fields were added in v1.13.0.

thanks for the suggestions.

**Comment by sugarchrist** [comment]
Hello,
Is it possible to make file uploaded be in the email as a attachment and not as a link please?

Thank you
