### ISSUE TITLE
Abitilty to hide hidden content in the BACKEND ( NOT PREVIEW )

### ISSUE THREAD

**Issue by lordloadalot** [pojome/elementor#2976]
I want to be able to show ONLY sections for e.g. PC version while working in the backend. ( not in the preview )
I am designing a homepage with different content to be loaded for PC and Mobile.
When dragging and editing elements for the PC version i come across all cluttering sections ment for mobile. I could change the backend order to // mobile designs first  // then PC designs - but i have sections in between wich serve both versions. It's difficult to assess paddings and amrgins and the flow of the story told.

BACKEND ( edit mode - not preview mode ) 
                   SWITCH ON ONLY MOBILE
                   SWITCH ON ONLY IPAD
                   SWITCH ON ONLY PC

Thanks for Your time.

**Comment by bainternet** [comment]
@lordloadalot 

You can already do that by selecting the viewport you want in the responsive mode at the button:
![o1f1hpp](https://user-images.githubusercontent.com/660572/34147339-0692052a-e4a6-11e7-8a3f-b92b1abdd964.png)

and then collapse the panel:
![etisrma](https://user-images.githubusercontent.com/660572/34147487-7a81964e-e4a6-11e7-9a49-5f575360ba14.png)

As for Edit mode, I'm going to leave this as a feature request

**Comment by bainternet** [comment]
I merged this issue with  #2989  , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by lordloadalot** [comment]
hi there.
i was only talking about edit mode. „Ability to hide hidden content in the BACKEND ( NOT PREVIEW ). I am familiar with your actual features ;)

martin


Von meinem iPhone gesendet
