### ISSUE TITLE
Access Images from ext. URL in EVERY module with images.

### ISSUE THREAD

**Issue by lordloadalot** [pojome/elementor#2977]
This issue seems to be stuck somewhere. We are missing the ability to use a **_CDN_**.
When opening the "Delete / Load Image" dialogue there should be a **_Field for an extrnal URL._**

OR:
the ability to access an folder **_other than the deafult WP media folder._**
Some CDN Services with WP-Plugins provide an own folder inside WP wich is permanently in sync with their service)

Thank yu for your time.

**Comment by bainternet** [comment]
I merged this issue with  #413 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
