### ISSUE TITLE
Lightbox issue

### ISSUE THREAD

**Issue by Eichlig** [pojome/elementor#2982]
I used lightbox yesterday for the first time, and I was having this issue: every time I tried to skip to the next image, it would close.

I was not understanding why, but then I realized: the arrows are too small, and clicking area is airtight, so you gotta do it precisely in order to skip.

I suggest you guys take a look at that, please!

Question: is there any way to make a lightbox link to a specific album, where arrows would display selected images? Like an inside-portfolio, if you get what I mean.

**Comment by bainternet** [comment]
@Eichlig 

I see what you mean about the navigation arrows, we'll see about that.

as for loading the lightbox from a link, you can do that by:

- adding  a gallery with the images you want;
- right click on one of the gallery images -> inspect element
- copy the link HTML ex:
![screen shot 2017-12-19 at 11 22 12](https://user-images.githubusercontent.com/660572/34149816-fd1ed78a-e4ae-11e7-8e33-4b5e4042001c.png)

```HTML
<a class="elementor-clickable" data-elementor-open-lightbox="default" data-elementor-lightbox-slideshow="b058492" href="http://pro.dev/wp-content/uploads/2017/11/25388788904_72d2f5ec6f_z.jpg">
    <img width="150" height="150" src="http://pro.dev/wp-content/uploads/2017/11/25388788904_72d2f5ec6f_z-150x150.jpg" class="attachment-thumbnail size-thumbnail" alt="" >
</a>
```

- Strip everything but the `href` and the  `data-elementor-lightbox-slideshow` attributes from the link:

```HTML
<a data-elementor-lightbox-slideshow="b058492" href="http://pro.dev/wp-content/uploads/2017/11/25388788904_72d2f5ec6f_z.jpg">
    Replace this with your Link text
</a>
```
- paste the link inside an HTML widget or text widget in text mode.
- and last Hide the galley either by adding custom CSS:
```CSS
selector { display: none;}
``` 
or using the widget > advanced > responsive and hide on all devices.

**Comment by Eichlig** [comment]
Thank you for your aid!

Could you me with these other two?
https://youtu.be/i1AL2besLjw

1. You can see the menu is my very first section, with negative margin, and I'm having a problem with its background... is it supposed to be done another way?

2. No matter what I do, animated headline want align properly, buddy... =/

**Comment by bainternet** [comment]
Hi,

1) If you set custom CSS (negative margin) you should set one for mobile as well.
2) As far as I know, that was fixed in one of the last versions.

next time please open a new issue for each issue you have, it's easier to follow and answer.

thanks.

**Comment by Eichlig** [comment]
So let's only talk about item 2 here because, as you can see, it hasn't been fixed.

I always update my Elementor every time it pops in my WordPress. How should I proceed?

**Comment by Eichlig** [comment]
**Elementor 1.8.11**

**Elementor Pro 1.11.0**

**Comment by bainternet** [comment]
@Eichlig 

If the animated headlines issue still persist please contact our support support@elementor.com
