### ISSUE TITLE
Custom lightbox

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#2984]
Is there a way I could disable Elementor's default lightbox and use a different one (on Elementor's elements)? So far, when I disable Elementor's lightbox in global settings, none other works (it just shows the media image).

When I use the standard WP gallery (even in Elementor Text widget), the non-elementor lightbox works well.

Any advice?
Thanks

**Comment by bainternet** [comment]
@black-eye 

You can but you need to take care of the lightbox trigger yourself by either settings the selector or via JavaScript.
But there are plugins that can work out of the box, for example, this plugin
https://wordpress.org/plugins/responsive-lightbox/

which lets you use many lightbox libraries like:
SwipeBox 
prettyPhoto 
FancyBox 
Nivo Lightbox 
Image Lightbox 
TosRUs 
Featherlight


Hope this helps
