### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by kowsar89** [pojome/elementor#2990]
In this page('Design attributes for a control' section): https://github.com/pojome/elementor/blob/master/docs/content/controls/controls-and-the-editor.md#design-attributes-for-a-control

Following link is used which redirects to 404 error page: https://github.com/pojome/elementor/blob/master/docs/content/controls/README.MD#settings-hierarchy

Please fix it

**Comment by bainternet** [comment]
Thanks for reporting, should be fixed soon.
