### ISSUE TITLE
Background image doesn't show fully on ipad. It just shows a small part of the image like the zoomed in

### ISSUE THREAD

**Issue by ArtyomBaykov** [pojome/elementor#2992]
All images that are set as a background are fixed and featured as a cover, while on desktop they look perfectly on ipad  they look terrible. Just small part of image is visible like someone increase the zoom 500% e.g. How can I fix this?

**Comment by bainternet** [comment]
This is a known issue with IOS mobile/tablet that can't/won't handle background image set as fixed.

There are some workarounds all over the web, but nothing formal, apparently it costs a lot to mobile browsers, so it's been disabled by them.

So unless you know of formal instruction by ios team...

**Comment by arturg-yan** [comment]
@bainternet I got it. So is there way to set it fixed  for desktop while for mobile and tablet set it scroll? Can you add that feature like for other settings that support separate configuration for desktop, mobile and tablet?

**Comment by ArtyomBaykov** [comment]
@bainternet  I got it. So is there way to set it fixed for desktop while for mobile and tablet set it scroll? Can you add that feature like for other settings that support separate configuration for desktop, mobile and tablet?

**Comment by bainternet** [comment]
This something you can do with custom CSS.
