### ISSUE TITLE
Integrations with ConvertFox - Feature Request

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#2996]
Hi,

The new update offers a bunch of integrations, which is great, kindly also consider integration with ConvertFox.

Thx.

https://convertfox.com

**Comment by bainternet** [comment]
As far as I know, the API they have is a client-side (JavaScript) so you can simply catch the `submit_success`  event and send the form data, ex:

```php
add_action( 'wp_footer', function(){
?>
<script>
      jQuery( document ).ready( function ($){
           $(document).on('submit_success',function( response ){
                  var $form  = $(this);
                  var unindexed_array = $form.serializeArray(),
                         convertfox_data_format = {};
                  $.map(unindexed_array, function(n, i){
                       convertfox_data_format[n['name']] = n['value'];
                   });
                 convertfox.identify(convertfox_data_format);
            });
      });
</script>
<?php
});
Now this is assuming you have Convertfox tracking code embedded on your site and your form has an email field named `email`.

Again this is just an example but it should get you started.

**Comment by Dentalicious** [comment]
Thx a bunch.

**Comment by fahid1** [comment]
Hi,
I am trying to do the same thing. I am not a programmer, I  would really appreciate if you can simplify the steps I need to take to make it work. 

Settings I have tested so far.
1. Added convertfox code on my website
2. Created a form in convertfox with email field
2. Posted your provided code in WordPress footer
3. Created a form in elementor with "email" field
4. Tested on webhooks and redirection action by setting URL to https://data.convertfox.com/subscribe/93391005 

screenshot of the setting.
![convertfox elementor](https://user-images.githubusercontent.com/36591557/36350636-8896101a-14bd-11e8-8263-2d740c9bd6e9.jpg)
Thanks,

**Comment by bainternet** [comment]
No need to setup webhook or redirects

**Comment by fahid1** [comment]
tried that too. but it didn't work.

**Comment by dax702** [comment]
Does anyone know what @bainternet is talking about? I'd like to use an E Pro form to connect with ConvertFox.

**Comment by mrashleyball** [comment]
So does it work?? @dax702 I'd love to start using E Pro an CF !!!

**Comment by dax702** [comment]
I haven't a clue, I don't even know what he was talking about and he didn't respond. It'd be great to be able to use an E Pro form and connect it to CF but I'm clueless on that.

**Comment by collizo4sky** [comment]
You can use E Pro form and connect it to CF via MailOptin plugin. See https://mailoptin.io/article/elementor-form-integration/

**Comment by dax702** [comment]
@collizo4sky it looks like the elementor integration is with their premium version, not the one in the repo, correct?

**Comment by collizo4sky** [comment]
@dax702 not correct. You can infact use the free version in the repo with Elementor form.

Only restriction is you are limited to 100 conversions monthly.

**Comment by dax702** [comment]
Where did you read about the 100 limit? What is a conversion, a form submission I presume?

**Comment by collizo4sky** [comment]
Conversion is a successful optin.

**Comment by jittarao** [comment]
@Dentalicious 

**Quick update:**

We released a Wordpress plugin to connect your Elementor forms to your Gist workspace. Also, you can apply tags to the contacts that submit the form.


_Note that the Form widget is part of Elementor Pro._
