### ISSUE TITLE
Plugin compatibility : WP Offload S3

### ISSUE THREAD

**Issue by architechcro** [pojome/elementor#2997]
Hi,
There seem to be an issue with WP Offload S3 - plugin to offload static content to Amazon S3 bucket ( and Amazon CloudFront ). https://deliciousbrains.com/wp-offload-s3/
In "edit with Elementor" mode images are show served from CloudFront url but in "regular" page/post view images are served from site url which results in 404 error.
Attached are screenshots of both "modes"
![2017-12-21_07h24_53](https://user-images.githubusercontent.com/591108/34243379-c3bb68a0-e620-11e7-90b6-9bf80539bed6.png)
![2017-12-21_07h24_39](https://user-images.githubusercontent.com/591108/34243381-c6c60fc8-e620-11e7-9b99-461243c193eb.png)

**Comment by bainternet** [comment]
can you provide a link?

**Comment by architechcro** [comment]
Link to page : https://test5.architech.hr/anticelulitni-program/

**Comment by bainternet** [comment]
@architechcro 

Can you please contact our support support@elementor.com and provide us with login details so we can take a better look and try to help. Also mention this issue here.

**Comment by physiostasis** [comment]
I believe I am also getting a similar problem. Sometimes I find that the pages don't upload the background images or YouTube links and I have to update a page for them to appear. Easy temporary fix but keeps happening.

**Comment by ericft** [comment]
Is there a way to add a static url for Elementor CSS? So it keeps loading from the server instead of S3?

**Comment by contempoinc** [comment]
Getting the exact same thing using Human Mades S3 Uploads, its a problem with how Elementor is generating the static CSS file, once you click "Update" when editing with Elementor you view the page the CSS will 404, the only way I've found how to fix it is to click "Exit to Dashboard" > click Update on the page itself then the CSS is generated properly and sent off to S3.

https://github.com/humanmade/S3-Uploads

**Comment by contempoinc** [comment]
This needs to be opened back up, it hasn't been resolved running the latest version of Elementor as well.

**Comment by nciske** [comment]
Still experiencing this issue... and it's 2021...
