### ISSUE TITLE
Integrate elementor form submission with any form action using POST

### ISSUE THREAD

**Issue by ashmetry** [pojome/elementor#3000]
I love the additional integration but I would like to see a "form action" integration that does not depend on any specific vendor.

Simply submit the data (name and email) to a post url providing any additional data like hidden fields 

A good example of another simple widget that does it well is https://wordpress.org/plugins/genesis-enews-extended/ 

You simply feed it the form name and the action to submit to + hidden fields and whatever form input gets submitted to the action url.

**Comment by bainternet** [comment]
@ashmetry 

This is exactly what our "Webhook" action does, all you need to do is provide it with a URL and the form will post the form data to it.

**Comment by ashmetry** [comment]
In this case then maybe the webhook needs to adjusted to allow change to the form fields that gets submitted. What if I want the label of the form input as "First Name" and "Last Name" but I want the webhook to submit the data to my API via POST (or GET) as f_name=John&l_name=Doe because that's how the backend expects the data. 

I don't see the flexibility to control how the data gets submitted via the webhook. 

According to [this article](https://docs.elementor.com/article/92-forms), The intent of the webhook seems to be focused Zapier

**Comment by bainternet** [comment]
You can change the field name and keep the field label something different.
Each field has a name field in the advanced tab.

**Comment by jhenzely** [comment]
Hello bainternet and the Elementor team.

Let's assume I have this simple HTML code:
```
<form action="https://example.com/register" method="post (or get)">
E-mail: <input type="text" name="email01"><br>
<input type="submit">
</form>
```

And this PHP code:
```
function inputform02() {
  print("INFORM_02 Output is: " . $_POST["email01"] . "<br>" );

  return ;
}
add_shortcode('inform02', 'inputform02');
```

And I need both methods, POST (for registration, etc) and GET (for search results link).
Sure, Field type could be set to "HTML", but then I will lose the possibility to use Elementor for adjusting the other form properties (font, size, colour).

Proposed solution:
Add possibility to set "form action=" and "method=" for given form (which is standard form handling procedure).

Thank You for cooperation.

**Comment by barrychapman** [comment]
Except it doesn't. I watched the request go in. You still send it to admin-ajax which gets blocked if the user is not logged in, 90% of the time.

**Comment by dread-pirate-bob** [comment]
Maybe add an option to "Actions After Submit" to specify a JavaScript event name that the form will fire once it submits?  It would be nice to be able to let the form handle validation / submission then listen for an event on the front end to perform custom logic after the quiz has been sent.

**Comment by ronaldaug** [comment]
I'm not sure if anyone else is experiencing a similar issue. You can vote for this feature here. https://github.com/orgs/elementor/discussions/24198
