### ISSUE TITLE
ONTRAPORT Integration

### ISSUE THREAD

**Issue by onyxchase** [pojome/elementor#3001]
With all the new integrations added to Elementor Pro, it would be nice to add ONTRAPORT to the list. I've been using this platform for YEARS and it would be very beneficial. They have an API which could easily be integrated with Elementor. Please add it! Thanks.

**Comment by bainternet** [comment]
I don't think there is a large demand for it for us to develop it but its something you can do very easily, something like:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $this ) {
	$fields = [];
	foreach ( $record->fields as $field_id => $field ) {
		$fields[$field_id] = urlencode( $field_id['value'] );
	}
	wp_remote_post( 'https://api.ontraport.com/1/Contacts', [
		'headers' => [
			'Api-Key' => "YOUR_API_KEY",
			'Api-Appid' => 'YOUR_APP_ID',
			'Content-Type' => 'application/x-www-form-urlencoded',
		],
		'body' => $fields
	]);
});
```

now this is just an example and it's assuming your form fields are named to match Ontraport field names.

The full list of available/required fields is listed on their [API docs](http://api.ontraport.com/doc/#create-a-contact).

Hope this helps.

**Comment by onyxchase** [comment]
Sure, but then if I edit the code I'll have to re-apply it at every update which is extremely annoying. I'm trying to avoid that at all costs.

**Comment by bainternet** [comment]
Not really. I'm not saying put this code inside elementor plugin files.

Put it in a child theme' s functions.php file or a custom plugin file.

**Comment by onyxchase** [comment]
Thank you. Do you have more documentation on how to set this up? I believe this would trigger on every form submission. It's not very practical as I don't want every form on my site to go to ONTRAPORT.

**Comment by bainternet** [comment]
Yea we do have some docs covering the [Forms here](https://github.com/pojome/elementor/blob/master/docs/content/pro/forms.md)

And like I said this is just an example, you can configure it a bit more, for example to run only on a specific form you can check the form name:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $this ) {
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$fields = [];
	foreach ( $record->fields as $field_id => $field ) {
		$fields[$field_id] = urlencode( $field_id['value'] );
	}
	wp_remote_post( 'https://api.ontraport.com/1/Contacts', [
		'headers' => [
			'Api-Key' => "YOUR_API_KEY",
			'Api-Appid' => 'YOUR_APP_ID',
			'Content-Type' => 'application/x-www-form-urlencoded',
		],
		'body' => $fields
	]);
});
```
