### ISSUE TITLE
Feature Request - Events handling

### ISSUE THREAD

**Issue by AndriSmith** [pojome/elementor#3003]
## Description

A standard block of fields for each widget, column and section with the ability to configure the response to an event.

For example, I chose the event 'page loaded' (from the list of standard events) and I add the parameter and its value to it (transparency, visibility, color, background, etc.).
Also, in addition to changing the parameter, i want to have actions, such as a redirect or something else related to the current element.

**Comment by bainternet** [comment]
@AndriSmith 

Currently, this feature is not available\supported, but we will look into it in the future if we see a large demand for it.

Thanks for the suggestion.
