### ISSUE TITLE
The border around text should have flexible Padding-Options

### ISSUE THREAD

**Issue by Nachdenker** [pojome/elementor#3004]
I'd wish more options and flexibility with "Border Spacing"; something like inner-spacing that the Frame or Border moves out and not the content within. Cause sometimes you want to have a Headline perfectly aligned with all the other content, but still want to have a border around it; but with a bit of padding - so it Looks good.

That would be cool Feature: Put a border around text and let the border have more or less padding. And currently it's a Problem, that if you select a Headline the whole row has got a border Even if the content is short.

![bildschirmfoto-2017-12-22-um-12 23 57](https://user-images.githubusercontent.com/34776835/34307505-c2cc4eae-e748-11e7-924c-04f427832224.png)

**Comment by bainternet** [comment]
@Nachdenker 

Can you explain better, or show on your image what exactly do you mean?

**Comment by Nachdenker** [comment]
@bainternet 

as in the screenshot above - I mean: If I put a border around a text and want to have a bit of padding between border and text the padding-value (let's say: 20px) then the text will move 20px within the Element, but I actually want the border to move out - in this case - 20px to the Outside. I Hope, this explains it better...

**Comment by bainternet** [comment]
@Nachdenker 
You mean negative margin??

**Comment by Nachdenker** [comment]
If that would solve my Problem, this could be it. ;)

**Comment by bainternet** [comment]
Well, its in the same place right above padding,
set it to negative value and see if that works for you.

![7ijxq1f](https://user-images.githubusercontent.com/660572/34335450-53d2555a-e957-11e7-8efc-3095b68a6b81.png)

**Comment by Nachdenker** [comment]
Hey,

that were a good starting-point!
I've Set the Margin to -10px (as you've described it) and I have also put the padding to 10px so it all Looks quite cool.
With the negative Margin the whole Element moves out, but with the opposing padding value the inline content (Heading) moves to its original place back). So in the end the border is the only thing that has moves. 

Awesome! 👍 
![bildschirmfoto 2017-12-25 um 13 57 59](https://user-images.githubusercontent.com/34776835/34340001-3cb02d8c-e97c-11e7-8893-ed0d4c00aba3.png)
![bildschirmfoto 2017-12-25 um 13 57 48](https://user-images.githubusercontent.com/34776835/34340002-3cca5720-e97c-11e7-908c-6e1e551420b1.png)
