### ISSUE TITLE
BUG: Column position 'middle' not displaying correctly in IE

### ISSUE THREAD

**Issue by robteeuwen** [pojome/elementor#3005]
In several locations on a live site I'm using sections with a minimum height set to a certain vh. When I set column position to 'middle', content is showing up vertically centered as expected in all browsers except for IE. I'm editing in chrome, and all my browsers are up to date. I'm on windows 7, and my wordpress installation and plugins are also up to date. 

For clarity I exaggerated the height of the third section on development.analogpeople.tv/about. Please view in IE and chrome to compare positioning.

**Comment by bainternet** [comment]
This is kind of a known issue with IE11 and min-height,flex,align-items...

The quickest and simplest way around it is to set the height the same as the min-height.

https://css-tricks.com/snippets/css/cross-browser-min-height/

ref:
#2472
#2797
#2937

**Comment by julianxhokaxhiu** [comment]
Well, I have the same identical issue using just internal configurations of the Elementor on the Backend ( no custom CSS on top ). The only different is that the black translucent element should be on the bottom, while on IE11 is on top.

See https://mercedes-benz.io/de/about/ on IE11.

I get it that the solution is to use `height`, but the CSS comes from Elementor directly. Shouldn't this patch come in the engine itself?
