### ISSUE TITLE
How to trigger "Change" event on editor to allow save

### ISSUE THREAD

**Issue by premitheme** [pojome/elementor#3008]
Hi,
Elementor is really a great page builder, I can comfortably recommend its free version over several paid solutions and I use it as the main page builder in a premium theme that will be for sale very soon. But - as a developer - the lack of a (complete) media control is the only downside IMO.

I have a problem as a WP theme & plugin developer, you announced that developer API is in the way several times, so I tried to find a solution until this happen but the last update evaporates my effort and now I'm back to square number one. Any advice will be appreciated.

## The problem:
I need media control that allow video and audio selection. The provided media control is limited to images only, so I needed to create a custom control.
Since there is no clear way to trigger the needed change event to activate the editor save button on input value change when media manager sends the value to the input, I ended up doing it that way below.

## My solution (imperfect):
I cloned the text control, added a button next to the text input and did the needed javascript to let it open the media manager. When you select file in the media manger instead of sending the value to the text input directly, I copy the value to clipboard, focus the text field and clear any existing value, then wait for manual paste action using keyboard shortcut. I found this way (pasting the value manually using keyboard) trigger the needed change event and make the save button active. Not a perfect solution but the best that I can came with.

The existing media (image only) control is great, why not just make the minor changes to make it accept video and audio. I will be happy to offer any contribution in this matter, but my poor Bakebone experience is holding me back.

Similar issue #2036

**Comment by bainternet** [comment]
@premitheme 

can I see your code, maybe I'll be able to help better....

**Comment by VadymPogorelov** [comment]
Elementor uses different event names for different field types (why??)
And if your data was changed in the text or hidden field - you need trigger event 'input' instead 'change' (why???)
I use next code to inform Elementor about my field is changed:

jQuery(document).ready(function(){
	"use strict";
	// Generate Elementor-specific event when field is changed:
	// input	for @ui.input, @ui.textarea
	// change	for @ui.checkbox, @ui.radio, @ui.select
	// click	for @ui.responsiveSwitchers
	jQuery('#elementor-panel').on('change', '.trx_addons_vc_param_icons input', function(e) {
		jQuery(this).trigger('input');
	});
});

P.S. Sorry for my poor English

**Comment by bainternet** [comment]
@VadymPogorelov 

- `oninput`  event occurs when the text content of an element is changed through the user interface.

- `onchange` occurs when the selection, the checked state or the contents of an element have changed. In some cases, it only occurs when the element loses the focus.

The `oninput` is useful if you want to detect when the contents of a `textarea`, `input:text`, `input:password` or `input:search` element have changed, because the `onchange` event on these elements fires when the element loses focus, not immediately after the modification. 

`input` and `change` are different events and they are used in/for different elements.

hope this answers your question.

**Comment by VadymPogorelov** [comment]
@bainternet 
Thank you very much for the detailed answer. In this case you need to add input:hidden to the list of fields as when creating custom controls often need to store the value in a hidden field, Elementor does not respond to software change the value of this field

**Comment by premitheme** [comment]
Thanks so much @VadymPogorelov & @bainternet, `input` is the answer in my case since I'm working on text field. Now the save button goes green when I send the media manager value to the text field. I were literally pulling my hair.

Maybe a more detailed developer documentation will help in similar situations. Thanks again.
