### ISSUE TITLE
Bug on anchor Widget. Sometimes it stops scrolling before the point. 

### ISSUE THREAD

**Issue by ArtyomBaykov** [pojome/elementor#3009]
We are trying to build one page website. And each section must be navigated through the link of nav-bar.  We've found that in some cases anchor Widget is not working as it should be.  The interesting factor is that all sections are built with the same approach while for couple of them scrolling works as needed but for others it stops earlier. We tried different solutions adding space removing it even adding margins and removing them. Nothing changed. When you click on the nav-link  it scrolls a bit higher to the needed point and active link on nav-bar doesn't change it's color until you don't scroll a bit manually. There is no any logic behind it.  We tried to test it on different one page templates and the results for  all of them is the same.

**Comment by bainternet** [comment]
@ArtyomBaykov 

can you provide an example? link?

**Comment by syuzanna-a** [comment]
@bainternet  unfortunately, we have exactly the same issue as it's described above.
Here is the [link ](http://suafstudio.com/)

We haven't included an anchor for home section only but other links all are configured and anchors are added. When the project is on development mode and Elementor dashboard is active on the left side of the screen, links are working correctly and it scrolls as it should be but when you save it and log out from admin panel to check it as a site visitor this issue appears.

**Comment by bainternet** [comment]
@syuzanna-a 
In your case, you have a fixed menu which causes the offset, what you need to do is offset the anchors as well via CSS ex:
```CSS
.elementor-widget-menu-anchor {
    //top should be set to negative of the fixed menu height
    top: -105px;
}
```

@ArtyomBaykov 
if its the same case for you then use the same solution. if not please feel free to reopen.

**Comment by ArtyomBaykov** [comment]
@bainternet  It looks our trouble was the same too. But Is there solution for free version of Elementor? Because it doesn't support custom CSS.
