### ISSUE TITLE
Important bug: Option for not rendering shortcodes when Live Elementor Editor is active.

### ISSUE THREAD

**Issue by salvimateus** [pojome/elementor#301]
Please add the plugin settings an option NOT to render the shortcodes from other plugins, when we are with the Live Editor **ACTIVE**.

For when I insert a shortcode plugins that have javascript, the Live Editor fully break.

There is no need to see the shortcode render in the page builder.

Thank you!

**Comment by qadriinfotech** [comment]
I have the same issue. I wanted to use click to tweet shortcode with my posts but not able to do so when live editor mode is active.

**Comment by arielk** [comment]
Added Shortcode widget for real live render https://github.com/pojome/elementor/commit/52cd0e530b48d1a4e321d1427dc5ee1cedb6935e

**Comment by salvimateus** [comment]
@arielk 
What version is it? I have the "0.7.4" and the "Text Editor" stay live rendering the shortcode in the LiveEditor, make broke the page builder, when I do this steps: save the page > back to WP panel > edit page again > shortcode is renderized

**Comment by arielk** [comment]
Yup, in V0.7.3 we added a new shortcode widget precisely because of these issues.

Please use it.

**Comment by salvimateus** [comment]
Well, I do **not want** the shortcode to be rendered on the **page builder**, because if it is rendered, break everything!
He should be rendered only on page production. Thank you!﻿

**Comment by salvimateus** [comment]
Do the test:

**• Install the plugin:**
https://br.wordpress.org/plugins/testimonial-rotator/

**• Insert the shortcode in the widget to "shortcodes" or "Text Editor" (whatever):**
[testimonial_rotator id="224" shuffle="true"]

**• Save the page and RETURN to the Wordpress dashboard**

**• Edit the page AGAIN with "Elementor" and everything will be broken**

**Comment by salvimateus** [comment]
Please, I imagine it is not difficult to make a checkbox for "Do not render this shortcode in Page Builder". He will be rendered only on page production. Thank you

**Comment by isaacsgraphic** [comment]
I'm also getting this issue. Trying to convert a page which contains a shortcode breaks elementor. I can just remove the shortcode, but it would be nice if this didn't happen.

**Comment by rameezwp** [comment]
Hi, any update on it to disable the shortcode rendering when editing the page via Elementor?

**Comment by advertiseit** [comment]
This is a must have

**Comment by MarcL85** [comment]
Hi, did anybody manage to find a solution? I have the same problem with an 'automatic redirection' shortcode...
Either in the specific Elementor shortcode widget or the standard text widget, the shortcode is automatically rendering within the edit zone.

Thank you 
Marc

**Comment by Omegatcu** [comment]
Why is this still a thing?
I have big sites where I need to use the Shortcode Widget because we use Templates (and Shortcodes are not processed if in a html Block when you include a template)
So I have the options of not using a Template or deactivating all shortcodes on the site so I can edit it.

I even Tried to do the shortcode conditionally with the preview mode - no luck because for whatever reason the shortcode gets executed one time without being processed as Elementor Preview...

**Comment by rameezwp** [comment]
Hi Michael, did you try the built-in elementor widgets? we improved them in
the last version.

**Comment by pzstar** [comment]
What i figured is that this does not happen in Elementoer Pro but only happens in free version.

**Comment by Omegatcu** [comment]
> What i figured is that this does not happen in Elementoer Pro but only happens in free version.

It happens in Elementor Pro as well - I work with sites that include advertising, and the ads kill the editor every time we move or change the short code.
This is a problem because there is no way to circumvent the re-rendering of the Shortcode

**Comment by brianhogg** [comment]
While I'd love some documentation on any hooks/filters I could use to avoid my own [The Events Calendar Shortcode Pro](https://eventcalendarnewsletter.com/the-events-calendar-shortcode-pro/) rendering and breaking Elementor, the solution seems to be using @g4rf's suggestion and using the `html </>` block rather than the shortcode one:

https://user-images.githubusercontent.com/627497/174703067-79dac3ca-c6f8-48a4-afab-5856213e2e82.mov

**Comment by chaotix359** [comment]
Experiencing similar issues. I have a bunch of custom shortcodes in the functions file. When those shortcodes are present in an elementor layout / template, elementor won't load. If I comment them out, it loads. They all function perfectly on the front end. If there was an option to deactive shortcode rendering within the editor it would really help. I have tried putting my shortcodes in the html widget as advised above but then they don't render at all.

**Comment by fernandopro** [comment]
We are at the threshold of 2024, and the situation remains the same - what a disaster!

**Comment by im-mike** [comment]
It's shocking that hasn't been resolved after 8 years... This is the only thing that worked for me:
if ( strpos($_SERVER['REQUEST_URI'], 'elementor') !== false ) {
  // you're in edit page mode

} else {
  //you're looking at published page

}

**Comment by gkhalidshah** [comment]
How you did it. can you provide more details please
