### ISSUE TITLE
Allow Flipbox state to work as a substitute for select as a form

### ISSUE THREAD

**Issue by jonathanasbell** [pojome/elementor#3011]
Form are useful but not fun. Users like to click on pretty picture and not form fields. Marketers look for ways of engaging and gathering information from users, and selecting pictures is an obvious and easy way to do this.

In a form you can select a single item in a dropdown list, or you can select one or more checkboxes if its a multi select.  Instead of this, why not allow us to create flipboxes where the state (flipped or not) represents a form item that is either selected or not.  That way if I ask you: "which country have you visited?" you can click the pretty pictures of the ones you have visited, which turns the flipbox around and shows another picture or text or the item, which is the equivilant of having selected it. That value can be sent to the CRM to be saved

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the suggestion.
