### ISSUE TITLE
Elementor stopped working, loads forever

### ISSUE THREAD

**Issue by willzurc** [pojome/elementor#3013]
## Description

Hello, 

It's been about 7 hours since I have been editing my website on WordPress with Elementor. Everything was working perfectly fine until I saved one of the pages I was on and tried to start editing another through Elementor. I tried creating new pages and it did not work. Basically, I am not able to use Elementor to edit anything as it doesn't load anymore.

Here's a screenshot of what I get when I try using Elementor now: https://i.imgur.com/1UGuygS.png

Things I have tried:

1.: Deactivating every plugin and let only Elementor active.
2.: Uninstalling and installing Elementor.
3.: Increasing PHP memory limit from 40M to 256M.
4.: Defining 'WP_DEBUG' as TRUE instead of FALSE.
5.: Switching editor loader method on.
6.: Adding SubstituteMaxLineLength 5m/10m to my public_html/.htaccess file. (this one messed up my website completely, so I took a step back).
7.: Editing with Elementor on Firefox, Chrome, Opera, Edge and even Explorer (ew).
8.: Praying for the WordPress Plugin God to perform a new year miracle.

Thanks in advance.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.54
	PHP Version: 7.1.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.1
	Site URL: http://tristaramericas.com
	Home URL: http://tristaramericas.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.4.10
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

== Active Plugins ==
	Elementor
		Version: 1.8.11
		Author: Elementor.com

== Debug ==
	Errors: There are no errors to display

**Comment by bainternet** [comment]
@willzurc 

Are you seeing any errors in the browser console or in the "Network Tab"?

because we can't really replicate what you are describing here...

**Comment by willzurc** [comment]
@bainternet , I was not, actually. But anyways, I figured that even the "Customize" tool native on WordPress wasn't working so I had everything, from the database to WordPress and Elementor wiped out and reinstalled and now I'm editing with a new theme. No problems up until now. 

Thank you for your help.

**Comment by bentalgad** [comment]
This problem happens to me almost every update. this is really annoying! makes work harder!
