### ISSUE TITLE
Create a new control type

### ISSUE THREAD

**Issue by anamwp** [pojome/elementor#3014]
How can I create this type of control. 
I attach a screenshot which will clear the concept. please take a look below screenshot. 
https://tx-snaps.s3.amazonaws.com/anam/Image_2017-12-27_10-57-58.png
Any help and fast reply is appreciated. 
Thanks.

**Comment by bainternet** [comment]
I would start by understanding how a [control works](https://github.com/pojome/elementor/blob/master/docs/content/controls/README.md), then extend the `Base_Data_Control` class and pick up from there.

If you have a specific issue or question with it then please feel free to reopen.

**Comment by anamwp** [comment]
I want to know if I want to create this then which control type should I use. Let me know. Thanks.
