### ISSUE TITLE
How to create a container element?

### ISSUE THREAD

**Issue by VadymPogorelov** [pojome/elementor#3019]
## Description

I need to create a container element that will contain other elements (widgets). Is there such a possibility in the API or containers can only be a section and column?
If only the last case - it would be nice to add that to the API

**Comment by bainternet** [comment]
Currently, this feature is not supported meaning there is no easy way to do it without rewriting major parts of elementor, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by blogohblog** [comment]
we need it.

**Comment by Pikamander2** [comment]
+1 for this feature. The limit on nested columns makes this a necessity in certain cases.

**Comment by Codevz** [comment]
+1 we need this feature to add other elements into another container element. thanks

**Comment by gerard-cuadras** [comment]
+1

**Comment by kamalahmed** [comment]
This is a very useful feature. Please add this feature. Complex widget and more dynamic widgets could be made if nested widget api was available in Elementor. Thanks.

**Comment by steve231293** [comment]
+1. I need this useful feature.
for eg: i want add Icon box widgets in Slider widget (Container) to make complex slider.

**Comment by kaoecoito** [comment]
+1. I need this useful feature.

**Comment by Alexus450** [comment]
Hi! Guys, any news about this feature?

**Comment by taurusser** [comment]
+1. I need this useful feature.

**Comment by marekmaurizio** [comment]
Since 2017, so i guess i will find a workaround.

**Comment by L-X-T** [comment]
Why is this feature still not implemented?

**Comment by caesarsamsi** [comment]
I want this too!

**Comment by JosigBarcos** [comment]
I need this feature too!!

**Comment by sunnyt7** [comment]
+1. Can't believe this isn't currently possible.

**Comment by DavidJH2** [comment]
Please, please, please add this VERY VERY IMPORTANT feature.  Plllllleeeeaaassee

**Comment by i2g-lweiss** [comment]
+1 for this

**Comment by i2g-lweiss** [comment]
Temp fix: You can use inner section module, hover over the 2nd column icon, right click and delete it.
