### ISSUE TITLE
Suggestion for improvement: carousel for simple HTML content and testimonials

### ISSUE THREAD

**Issue by salvimateus** [pojome/elementor#302]
Please add an element to create carousel / slider simple content HTML or testimonials.

With option to pause when mouse hover.

Thank you!

**Comment by walidmahade** [comment]
Currently, a user  can add only images to the carousel. 
But It would be really nice if  others widgets are enabled to be added inside carousel.
Widget inside widget.

**Comment by arielk** [comment]
We get a lot of ideas and issues and I just try to arrange them neatly.

I think that this issue is very similar #302 - I'd be happy if you add your idea as a comment to the original issue, it will be clearer. let me know what's your mind..

**Comment by WPDevHQ** [comment]
Cross posting from #613 that I've closed.
Original request:
Could you kindly consider adding options for a title text field and a content textarea for the image carousel please?

The content of both should overlay the carousel and slide/fade in sync with the image they are attached to.

I know it adds a little complication on per image bases but would a great addition :)

**Comment by arielk** [comment]
I merged it with another issue #219 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.
