### ISSUE TITLE
oceanWP hooks conflict with elementor

### ISSUE THREAD

**Issue by prodrigovieira** [pojome/elementor#3024]
I would like to use a custom header and footer for my site using the elementor or oceanWP library.

The problem is that when I change the header of my site using OceanWP library, the elementor does not load, it is stopped in the loading screen with the logo.

If I use hooks it also conflicts. This is all updated, I'm using the latest version of elementor and elementor pro, and also the latest version of OceanWP and oceanExtras.

If I use the standard OceanWP header conflict does not happen, the elementor loader page works normally, the problem is when I add hooks or change the header.

Existe alguma solução ?

here is a video with the problem: [https://www.youtube.com/watch?v=NXWgxvy6MK0&feature=youtu.be](https://www.youtube.com/watch?v=NXWgxvy6MK0&feature=youtu.be)

Thank you!

**Comment by bainternet** [comment]
@prodrigovieira 

Looking at the video, it seems the problem is caused by "Jet elements".
Try disabling that plugin and see if it works.

Please feel free to reopen if issue persists after disabling that plugin.
