### ISSUE TITLE
Group_Control_Background not working properly when i try to make new widget

### ISSUE THREAD

**Issue by bdthemes** [pojome/elementor#3026]
## Description

Hello, I am trying to make a custom widget element called slideshow. but this control not work as i expected:

```
$repeater->add_group_control(
	Group_Control_Background::get_type(),
	[
		'name'  => 'slide_background',
		'types' => [ 'classic', 'gradient', 'video' ],
		'fields_options' => [
			'background' => [
				'frontend_available' => true,
			],
			'video_link' => [
				'frontend_available' => true,
			],
		],
		'selector' => '{{WRAPPER}} {{CURRENT_ITEM}}',
	]
);
```
background color not change it's always show transparent. but i saw in column and section it's working fine there. can you tell me what i wrong or is it a bug?

When i pick background image it's working fine: http://prntscr.com/ht8dir

Please give me a right solution.

## Steps to reproduce

Look here: 
http://prntscr.com/ht8amj
http://prntscr.com/ht8dir

## Environment
Look here: https://pastebin.com/5DPf8HHq

**Comment by bainternet** [comment]
@bdthemes 

can you provide a link? the widget code? so we can take a look?

**Comment by norewp** [comment]
Group Controls do not work inside of repeaters! You'll have to use the standard Controls_Manager::COLOR for the background color.

**Comment by bdthemes** [comment]
Hello @bainternet, I am working locally. here you get the repeater code: https://pastebin.com/uiMHZ1vY

Hello @norewp, So how can i use gradient control? How can get this type of organize layout view: http://prntscr.com/htqbfy ?

**Comment by bainternet** [comment]
@bdthemes 

Like @norewp said, Group Controls don't work inside a repeater.

So in order to get the desired layout, you would need to add all tabs and controls manually.

But then again you can't have nested tabs, so I would suggest adding all fields required for all background types and only show them based on a select control which will hold the background type as a condition.

Hope this makes sense.

**Comment by Deepak8622** [comment]
Can anyone help regarding how to build custom slider using repeater with example?
