### ISSUE TITLE
Suggestion for improvement: Allow placing elements within the accordion contents / tabs / toggle

### ISSUE THREAD

**Issue by salvimateus** [pojome/elementor#303]
It would be so good to drag elements into the accordion / tabs / toggles.

Endless possibilities for creating structures.

Thank you!

**Comment by cobicarmel** [comment]
Hi @salvimateus, it's already on our roadmap. Stay tuned.

**Comment by Kaskade01** [comment]
@salvimateus 

I have the need for this feature as well. As a workaround, you can try the following:

1. create and style the widget that you want in its own section. Save the results
2. copy Section element that is generated in the HTML. You can find the element by inspecting the widget.
3. Paste the HTML in the content box of another widget.

Notes: 
A. I think you also need to create a STYLE tag with the css that controls the way your widget should look.

B. You can use this same trick to copy widgets created with elementor into parts of a theme that are not generated via THE_CONTENT()

**Comment by mizejewski** [comment]
Yes, please put this high on your list. This example would be much easier to create by just dragging in heading, text, image, and button widgets.

<img width="1017" alt="accordion content" src="https://cloud.githubusercontent.com/assets/974442/18563898/2a5d2bce-7b3e-11e6-9584-857bc6ce7195.png">

**Comment by nk-o** [comment]
Recently found your builder and it's awesome...
I vote for this feature because as theme author I can't use Elementor in my new projects, but really want...

The only this thing is needed - nested elements for the default accordions and tabs, but for custom elements to let developers create mind-blowing things.

**Comment by peepshow** [comment]
Even if this could just be a functioning **WYSIWYG** editor as opposed to a **TEXTAREA** it would be a decent improvement for the time being. 

I had a quick look through the code for the accordion and the tab widgets and changed the _tab_content_ _type_ to **WYSIWYG** and it works fine until you try and resize the WYSIWYG input window on the _frontend_, at that point things go a bit weird, content disappears from the Visual editor but is still available in the Text editor.

Other than that everything renders perfectly in the actual page. If I had any idea where to begin in solving that bug I'd be happy to assist, but it's beyond me. 

Fingers crossed we see a solution soon! 
Nice one.

**Comment by blogmom** [comment]
I logged in to suggest this feature and see it's already on the list for a few months.    THIS WILL BE EPIC!   Please implement this for Tabs (and Accordion, but especially Tabs).

**Comment by WPDevHQ** [comment]
I've implemented this for a while now - in the way @peepshow suggests but I've to encounter the issue(s) he faced.

Perhaps a conflict somewhere?

**Comment by arielk** [comment]
We checked it recently again and unfortunately for now we can not doing this request using Elementor.

But please note that similar feature is now available in Elementor Pro ([Embed Anywhere](http://docs.elementor.com/article/97-embed-templates)), check it out: https://elementor.com/pro/

Thanks for your feedback!

**Comment by salvimateus** [comment]
@arielk I have the unlimited pro version, is this already possible? Or do I have to wait for an update?

**Comment by arielk** [comment]
Sure, it's already possible, please read the tutorial about this feature: http://docs.elementor.com/article/97-embed-templates

**Comment by salvimateus** [comment]
Not really. I tried now using the pro version and could not drag any element / template into tabs. See my record in GIF:
![animation](https://cloud.githubusercontent.com/assets/10764410/22217661/08d234d2-e18b-11e6-86d8-905d4b482898.gif)

**Comment by arielk** [comment]
Sorry for the misunderstanding, my fault.

It works by inserting the Shortcode of the Template into the content tab.
It doesn't work by drag and drop into the widget as you requested.

**Comment by mjunaidit** [comment]
Was here looking for the same and it looks like we're stuck with the shortcode method for now. Which honestly sucks..

**Comment by css31** [comment]
Hi,
This is a nice solution, but it would be so good if we could act directly on the layout of a tab.

**Comment by gloriahar** [comment]
It has been four years since this was requested... Can we anticipate this feature?

**Comment by jfranger** [comment]
_> kobizz commented on 25 Jul 2016
Hi @salvimateus, it's already on our roadmap. Stay tuned._

I simply want to point out that we are in 2020 now and this has not been resolved. It would have add more flexibility to the design of several pages I've built over the past year. Would make things more dynamic... Please make this feature a priority!

**Comment by ShadowXVII** [comment]
Very cumbersome. I can't use Tabs, Accordions and such because it's not practical to use templates. They should act like Columns do -- allowing content to be dragged into them dynamically via the editor.

Tabs are layout widget.
Tabs are **more** like Columns than say, Call to action which is a content widget.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Accordion widget was released with Elementor v3.15.0! 🥳 

With this release, we finally conclude this Feature Request! 🎉

Thank you very much for all the feedback shared here, and for helping shape the future of Elementor! 🙏 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
