### ISSUE TITLE
Editing an image in a Text Editor module pops a malformed layout

### ISSUE THREAD

**Issue by hzesen1221** [pojome/elementor#3036]
## Description

Editing an image in a Text Editor module pops a malformed layout

## Steps to reproduce

Drag in a Text Editor module, then click Add Media to insert an image. Before inserting this image, try to edit it, and you will see an interface like this: http://i63.tinypic.com/29uwww1.png

After inserting, if you try to edit this image, you will see an interface like this: http://i63.tinypic.com/123bg2g.png (for this one, not sure if it also has any CSS issues or it's by design)

**Comment by bainternet** [comment]
@hzesen1221 

I do see some Minor CSS issues but its all by design,
in the second image you can click "Edit original" and you should get the same edit screen as in the first image.

Same as the native WordPress editor.

**Comment by hzesen1221** [comment]
@bainternet 

Hi, I was not saying that I couldn't get from the second image to the first. That's totally irrelavent.
What I was describing was there might be issues under both of the above scenarios:

1: for the first image (the major issue), there's gotta be something wrong. For example that 'Scale' button is too wide to even fit on screen. It is not the same as the native WordPress editor as you said. Check this comparison image: http://i65.tinypic.com/29qjd3k.jpg

2: for the second image (the minor issue), I suspect there might be some minor CSS issues since all those fields are stretching to be 100% width and it just seems weird.

Please kindly check again. Thank you!
