### ISSUE TITLE
Clicking Responsive Mode icon - frontend bottom - visual cues

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#304]
Hey

I am going through the Elements section in the frontend.
Today the icon on the bottom stays as the Desktop icon when switching to various responsive modes. Switching to for instance Tablet have the bottom icon also switch to show that Tablet mode is active and have a checkmark or something perhaps have the background color of the mode change to a redish tint background to also give the visual cue in the drop up the mode that is active.

A wireframe where one can see the mobile icon on the bottom.
A red tint background color with an opacity of 40.

![elementor-responsive-mode](https://cloud.githubusercontent.com/assets/5323259/17073620/a6c3af72-5072-11e6-9bfb-dc275a230144.jpg)

So two things.
Change the responsive icon bottom left to reflect which mode is active.
Have the selected mode in the drop up give a visual cue that it is selected.
I am thinking you have a default way of doing this that is done also in other places where visual cues are needed. For Elementor objects that are selected that need an extra visual cue I am thinking that having a background change to a reddish tint with an opacity of 40 perhaps to connect it with the Elementor red would be a good thing to use.

**Comment by cobicarmel** [comment]
Done by 292e8de0c506130fb595996c85385c5c8d7be775
