### ISSUE TITLE
Button Issue - Line Breaking!

### ISSUE THREAD

**Issue by rockyfellers** [pojome/elementor#3041]
Hey,

i using elementor since today and have a problem with the buttons. in the editor they look fine, but when i take a look at the live-page, they didnt working.

i checked the html and css and founds an error. i get there many <br> codes, so the lines are broken.

is there any solution to solve the problem?

regards

screenshot from editor:
![bildschirmfoto 2017-12-29 um 16 02 06](https://user-images.githubusercontent.com/34942341/34439904-a909160a-ecb1-11e7-934a-dbe14096f41b.png)

screenshot from live-site:
![bildschirmfoto 2017-12-29 um 16 02 14](https://user-images.githubusercontent.com/34942341/34439905-a922967a-ecb1-11e7-8428-cec14d292e79.png)

**Comment by bainternet** [comment]
@rockyfellers 

can you provide a link? or the result markup?

**Comment by rockyfellers** [comment]
hello,

the link is here: https://www.sexportal-vergleich.com/sexkontakte/berlin/

i testing now the beaver builder but there ist the problem as well.. :( only at the buttons i get a the extra <br> in the code. in the elementor (i would like to use the elementor!) is it the same problem

**Comment by rockyfellers** [comment]
So, now you see the site from the elementor page builder. the lines are broken in the buttons :(

**Comment by bainternet** [comment]
Seems like it has something to do with [`wpautop`] 
(https://codex.wordpress.org/Function_Reference/wpautop) Probably from your theme or 3rd party plugins.

Please test it after disabling other plugins and changing the theme to a default one.
This will help you find what is causing the extra line breaks (your theme or a plugin).

**Comment by rockyfellers** [comment]
this is not the Issue. at the weekend i tested to deactivate all plugins, but it didnt help...
