### ISSUE TITLE
Displaying Child Pages

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#3042]
A feature request either as an update for the pro plugin or the upcoming theme builder.

Feature: Displaying all Child Pages of a Parent page. i.e. displaying the parent and siblings and navigation within those without leaving that menu.

There aren't many great plugins (free or premium)  that do the job nicely, however, it's a much needed feature and has many applications.

A good video on how to do that with coding for reference, https://youtu.be/GHTZn3atTcM
 
Intended examples.
https://www.nobelbiocare.com/international/en/footer/warranty.html

Thx.

**Comment by shilo-ey** [comment]
Hi @Dentalicious, Thanks for your feedback.

The feature you requested has been implemented in Elementor Pro since v2.2.0

Try using [Sitemap widget](https://docs.elementor.com/article/443-sitemap) and set your terms & design.

thanks.

**Comment by 972creative** [comment]
@shilo-ey 
The initial request was Displaying all Child Pages of a Parent page. I've found the Sitemap widget, but it doesn't fulfill the original posters request, which happens to be exactly what I'm trying to do. There is no options to only display child pages.

Please advise.

**Comment by typometre** [comment]
No, I disagree.
The sitemap widget haven't any way to restrict to only show child pages. 
So there is no module actually that could display the current page and subpage and to show page and it's parents in subpage.
This is really needed.

**Comment by Felipe-NS** [comment]
Need that function. So important and so simple

**Comment by cirkut** [comment]
Wanted to toss my comment in here as well. Without doing a weird hacky workaround with the Posts widget and custom queries, we really should be able to use the sitemap widget to simply show the current sitemap in relation to the page we're on (or a manually selected page as the 'base').

For example, if I have a custom post type with a ton of hierarchy, I want to be able to show the path from the top level parent all the way down to all children of the page that I'm on. Something like below would work well in my case, though having a toggle for just current page and below is probably ideal as well.

- Parent
	- Sub-parent
		- **Current Page**
			- Page Child 1
			- Page Child 2
			- Page Child 3

I would really like to see the dev team re-open this issue for discussion or to suggest this for future use. Given all of the dynamic functionality we've been getting, it's a relatively basic feature to want to dynamically show all child posts of a current post.

**Comment by marekmaurizio** [comment]
Closed xD

**Comment by cirkut** [comment]
Wish this would be reopened. Doesn't seem unrealistic to implement and would be much appreciated.

**Comment by johngisworking** [comment]
This needs to be reopened!

It would be helpful if you could specify the parent page of the sitemap component, rather that it showing everything. You can almost achieve this by manually excluding the pages you don't want shown under Additional Options.

**Comment by djbrown** [comment]
+1 for reopening this
there is no widget for listing only the child pages of a specific parent page

**Comment by weismannweb** [comment]
+1 100000%

**Comment by TarekNabil** [comment]
As @Felipe-NS said, So simple and so important

**Comment by lucasjahn** [comment]
+1 for this from my side as well

**Comment by Visual-Digital** [comment]
Hi All, I was just searching a solution to exactly this and while I would prefer to use only Elementor, this parent child menu plugin by dynamic.ooo does the job, in case anyone else needed a solution and reads this. https://help.dynamic.ooo/en/articles/4952516-parent-child-menu
