### ISSUE TITLE
Fonts aren't loaded in font-face

### ISSUE THREAD

**Issue by benqzq** [pojome/elementor#3045]
Whenever I use Google fonts from Elementor I get a notable decrease in Google Pagespeed Insights (GPI) score (`>=30 points`).

If I disable Elementor font-load, and load fonts manually via `@font-face`, I don't have that problem.

**Why it's important to fix it**

I had a case when a site had 100/100 (and that notably gave an SEO boost) and it downgraded its GPI score from 100 to about 67/100.

I think it's the only task left to make Elementor totally SEO friendly.

**Why @font-face is the only way to go**

From my experience, loading fonts in any way which isn't `@font-face` is doomed to fail. Google only desires manual font load as with `@font-face`.

**A possible handling algorithm**

1. If the user selects a font that doesn't exist, download the font-files from Google to a dedicated directory.
2. Add a `@font-face` rule in a dedicated typography CSS file.
3. Create a `font-family` command, for the selected font.

**Comment by bainternet** [comment]
@benqzq 

please follow this PR: #2987

**Comment by benqzq** [comment]
Done, dear @bainternet .
