### ISSUE TITLE
Needs improvement - Editing controls for a column, section or element

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#305]
The weakest part of Elementor is the selecting of Columns or Sections.

Opening a page/post to add Elementor widgets.

Lets say that I open Hello world! post.

Clicking column - have the column show a outline/border color that the column button also has.
Today it is a dark grey. Then let the column box have a thin dark grey outline.

Clicking Section (row?) - have the section show a outline/border color that the section button also has. Today it is light grey. Then let the section box have a think light grey outline.

It creates a clear difference between the two.

Clicking the Welcome to WordPress. This is your first post..... etc container shows no difference visually outside of the buttons on selecting column or section.

How do I know visually that this is the column or section? (Outside of the editing controls that is.)
![screen shot 2016-07-23 at 09 29 35](https://cloud.githubusercontent.com/assets/5323259/17076636/ff74f348-50b7-11e6-8431-d0e629fe2968.png)

Creating a clear difference really help creating columns and section.

Too many options. One section/column is selected and one hovers and clicks over another area seeing two different editing controls. Please have only one set of editing controls open at once.

![screen shot 2016-07-23 at 09 45 13](https://cloud.githubusercontent.com/assets/5323259/17076731/2f15b612-50ba-11e6-9b84-b5a53c879d14.png)

![screen shot 2016-07-23 at 01 17 52](https://cloud.githubusercontent.com/assets/5323259/17076747/713bb4b0-50ba-11e6-8c7f-2d3c3039081c.png)

Click a column/section/element and have the specific controls for it show.

Resizing existing column by dragging.
The column/section as I mentioned needs a clear differentiation. Clicking the initial Welcome to WordPress column/section I would also like to be able to drag the left or right edge of the box to change the size of it. Perhaps having a new section automatically show up beside it when I drag it from 100% to for instance 30%. Meaning initial section becomes 30% and the automatically added section as 70%. If I drag the edge of section 2 so it becomes 30% then have another section fill in the missing space. Initial section 30%. Section 2 became 30% and then the automatically added is then 40%.
The bottom line have a section be automatically added when sections take less then 100%. Let them all be draggable in location and width.

![screen shot 2016-07-23 at 10 04 19](https://cloud.githubusercontent.com/assets/5323259/17076824/d86a97a8-50bc-11e6-9e61-eb3bbfead3d1.png)

**Glitchy**. Hovering over close by when there are two columns of 46.5% each can make Section jump up above Column or go to the right of the Column.

![screen shot 2016-07-23 at 09 43 17](https://cloud.githubusercontent.com/assets/5323259/17076724/eac94564-50b9-11e6-9ce6-45a07306da3e.png)

I will likely add on to this issue when additional items come up.

Bottom line is: I feel that the existing editing controls for columns/sections/elements need an enhancement making it feel less cluttered. Creating a stronger visual bond between control and the area it belongs to.

**Comment by paaljoachim** [comment]
I am looking at Beaver Builder and notice the really nice and clear how editing rows and modules work.

![screen shot 2016-07-24 at 23 10 40](https://cloud.githubusercontent.com/assets/5323259/17086498/e3118422-51f3-11e6-83a7-9f547fa3344a.png)

**Comment by arielk** [comment]
We just recently released a new version with some UI improvements have written here, please update and check if things work out for you
