### ISSUE TITLE
social login and more control over login widget

### ISSUE THREAD

**Issue by amirhoseinsalemi** [pojome/elementor#3057]
hey elementor thx for the great job you've been doing so far 
if you could add the possibility of social login within login widget it would be great 
also right now you can't edit some parts of login widget (e.g: edit "remember me" text) so if that option will be considered in future releases we all be happier customers :D 
#request

**Comment by bainternet** [comment]
@amirhoseinsalemi 

thanks for the suggestions, "remember me" text can and will be added and if you have more things like that.

as for Social login we feel its more of a 3rd party plugins territory, meaning there are already plugins that do it very well and are integrated with `wp_login_form` which is what the widget uses.

**Comment by amirhoseinsalemi** [comment]
can you tell me how i can replace "remember me" text with something else?
thanks in advance

**Comment by bainternet** [comment]
right now you can't but we will try to add it soon.

**Comment by amirhoseinsalemi** [comment]
thanx
