### ISSUE TITLE
Feature suggestion - shortcut to open Elementor edit for a page (or for all pages)

### ISSUE THREAD

**Issue by benqzq** [pojome/elementor#3059]
Sometimes I open all links in the main menu and click the "Edit with Elementor" button in the WP-admin bar **per each page**.

It would be neater to add a way to open Elementor edit screen for current wordpress page from keyboard, or maybe even for all web browser tabs that contain a Wordpress page.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the suggestion.
