### ISSUE TITLE
Margin change isn't global

### ISSUE THREAD

**Issue by benqzq** [pojome/elementor#3060]
I tried to change margin globally but global change seem not to work (if I'm not wrong it worked in the past).

I had to change margin for tablets and mobile phones separately.

Maybe there isn't global change at all and it's a good spot to say --- if there isn't I think it's worth adding it.

![a](https://user-images.githubusercontent.com/31392185/34473706-9b47f232-ef7e-11e7-9694-5b032c950881.PNG)

**Comment by bainternet** [comment]
@benqzq 
Which element? because the way it works is, once you set margin it is set for all devices unless you set specifically for tablets and then mobile.

**Comment by benqzq** [comment]
Hi @bainternet, the element is an Icon element (not an icon box but rather just an icon).

Sadly I had to change margin-bottom to 20 X3 times --- It wasn't changed globally.

**Comment by bainternet** [comment]
@benqzq 

I see what you mean, If you unlink the margin/padding controls then yea it's not global and you do need to define it manually per each viewpoint. If you don't Unlink then like I said the desktop settings are inherited to tablet and mobile unless you specify otherwise.

thanks.

**Comment by benqzq** [comment]
Hi @bainternet IIRC, for some reason it wasn't inherited. :\
