### ISSUE TITLE
Disable Nav Menu Dropdown/Toggle for Mobile/Tablet [Feature Request]

### ISSUE THREAD

**Issue by sarahdenise** [pojome/elementor#3064]
Currently the navigation automatically toggles in mobile or tablet. There is no option to disable this.
While this is awesomely responsive and helpful, I have some instances where I want my navigation to look like how it is on desktop.

Setting the 'Toggle Button' to 'None' only hides the Hamburger Icon and the nav is still essentially in a different styling on top of the page.

For now, if someone can send me some css codes to disable this, that would be awesome.

Thanks

**Comment by bainternet** [comment]
```CSS
/* You can hide the dropdown */
nav.elementor-nav-menu--dropdown.elementor-nav-menu__container {
    display: none;
}
/* and force display of menu on small devices */
@media (max-width: 1024px) {
    .elementor-nav-menu--dropdown-tablet .elementor-nav-menu--main {
        display: block;
    }
}
```
`max-width: 1024px` should match the breakpoint set in the panel + 1px.

**Comment by sarahdenise** [comment]
It didn't work for me until I put "nav" before the classes under @media (max-width: __px).

This was definitely helpful! Thanks!!

**Comment by Bobbietto** [comment]
In which section should I add that custom code? And where in the section? Sorry, but I am really new to this and I have the same problem

**Comment by sarahdenise** [comment]
Hi @Bobbietto 

Just copy-paste the above code anywhere you can put a css code. 
The code already calls the classes where it should apply to.

Sorry just saw your question

**Comment by GitStl** [comment]
I was able to hide the toggle, but I can't get the menu to display. I even added the nav components to the classes.

**Comment by 2urn** [comment]
Depending on your settings you may need to change this:

`.elementor-nav-menu--dropdown-tablet`

to this:
`.elementor-nav-menu--dropdown-mobile`

And change width to:

`(max-width: 768px)`

**Comment by knireis** [comment]
The vertical menu layout needs an option to not collapse on mobile or tablet. I use a vertical menu in a off canvas situation, and in the design there is a hamburger menu already. On mobile i now see 2 hamburgers which is not necessary. See screenshots for clarification.

![schermafdruk van 2019-02-08 09-22-14](https://user-images.githubusercontent.com/2702064/52466829-e2f61900-2b83-11e9-8d9c-9a659a7006dc.png)
![schermafdruk van 2019-02-08 09-22-08](https://user-images.githubusercontent.com/2702064/52466830-e2f61900-2b83-11e9-8847-98f9aeb2af14.png)
![schermafdruk van 2019-02-08 09-21-41](https://user-images.githubusercontent.com/2702064/52466831-e2f61900-2b83-11e9-8c01-3edc38c0ecc9.png)
![schermafdruk van 2019-02-08 09-21-37](https://user-images.githubusercontent.com/2702064/52466832-e38eaf80-2b83-11e9-8f52-8748e40169fb.png)

**Comment by rohanroy99** [comment]
i tried copying it, it didnt work i can even see the hamburger toggle even now can anyone help me with this ? i would love to look at the site as same as it looks on a full screen view from a pc

**Comment by kirstyvanacker** [comment]
If you just want the mobile to have the same menu style as the desktop you can do it with: 
`@media screen and (max-width: 767px) {

  .elementor-nav-menu--dropdown-mobile .elementor-nav-menu--dropdown {
    display: none;
  }

  .elementor-nav-menu--dropdown-mobile .elementor-nav-menu--main {
    display: block !important;
  }
}`

**Comment by sp1dev** [comment]
why is this closed? shouldn't need custom css for this.

**Comment by uschmelzer** [comment]
+1

**Comment by KingGrizzly** [comment]
+1

I encounter this need consistently across client sites.

**Comment by Freakatiki** [comment]
+1

**Comment by simonclay** [comment]
+1 need this on almost every site, usually in footer nav, quick links etc.

**Comment by soulfulwater** [comment]
+1

**Comment by mdrideout** [comment]
Also an easy solution if you want to make the CSS change directly to the element (**element -> advanced -> custom css**):
```
selector nav {
    display:block;
}

selector .elementor-menu-toggle {
    display: none;
}
```
Will ensure the nav element remains visible, will hide the mobile menu toggle. The "selector" feature in elementor ensures your style is only applied to that element.

**Comment by MaxZiebell** [comment]
+1 Mind boggling that Elementor doesn't have this basic feature.

**Comment by mbrinson** [comment]
Agreed.  Why was this closed?

Please add this basic feature elementor developers.

**Comment by mbrinson** [comment]
I opened another issue since I couldn't find any way to request to have this one re-opened.
If you agree that there needs to be a toggle option within the UI of Elementor instead of being pointed to a custom css coding solution by the developers, please go comment on the new issue:

https://github.com/elementor/elementor/issues/7916

**Comment by black-eye** [comment]
+1

**Comment by simonclay** [comment]
The classes/markup for Elementor Nav seem to have changed? The helpful solutions posted by others above, don't work now.

**Comment by heyfletch** [comment]
The following works for me:

```css 

selector .elementor-nav-menu--layout-vertical {
    display: block;
}

selector .elementor-menu-toggle {
    display: none;
}

```

**Comment by dudaster** [comment]
+1

**Comment by MaxZiebell** [comment]
A bit mind boggled that this topic is one year old and hasn’t been properly fixed. Is there an issue or logic behind not implementing this? Maybe elementor devs have some reservations? In that case Elementor team please Share.

**Comment by scott8035** [comment]
I also found it necessary to suppress the mobile nav menu container, so the CSS becomes:

```
selector nav {
    display: block;
}

selector .elementor-menu-toggle,
selector .elementor-nav-menu--dropdown {
    display: none;
}
```

**Comment by pedropiper** [comment]
Hi Scott, very helpful.  Thanks.  I'm a total noob with CSS, how do I hide the hamburger menu only on tablet?  I have added the above code but the full menu is displaying on mobile too.  Thanks.

**Comment by scott8035** [comment]
@pedropiper, you have to add a media query to make it apply to only devices of a certain width or larger. So for the example I gave, it would become:
```
@media (min-width: 768px) {
    selector nav {
        display: block;
    }

    selector .elementor-menu-toggle,
    selector .elementor-nav-menu--dropdown {
        display: none;
    }
} 
```

**Comment by pedropiper** [comment]
Magnifico!  Thank you soooo much!

**Comment by ayhanmalkoc** [comment]
+1

**Comment by qwik3r** [comment]
+1

**Comment by blinkbat** [comment]
+1 no need to use custom css for this

**Comment by kennypu** [comment]
+1

**Comment by nicholaszein** [comment]
Hello there!

This feature was added to Elementor Pro 2.6.0 - 2019-07-23.

Kind regards.
