### ISSUE TITLE
<Request>Ajax pagination for posts widget

### ISSUE THREAD

**Issue by unclerom** [pojome/elementor#3068]
Currently when using the posts widget the entire page refreshes when skipping to next post/page  which is almost annoying vs useful because it refreshes to the top of the page losing your place on the page.

**Comment by stllrnet** [comment]
Ajax pagination would be a marvelous addition to Elementor Post Widget. Hope they add it soon!

**Comment by arielk** [comment]
Merged #1284

**Comment by BoykoDim** [comment]
Just updated. How can I use the new pagination?

**Comment by hackernewbie** [comment]
Still no AJAX support for pagination? :(

**Comment by abdhannan** [comment]
We need thissss

**Comment by Kesiunas** [comment]
still need this!:)
