### ISSUE TITLE
Carrousel image problem

### ISSUE THREAD

**Issue by yogadiva** [pojome/elementor#3069]
I use  Wordpress 4.9.1–fr_FR(Virtue Theme)  Elementor Version : 1.8.11
When I use an image carroussel i have a bug when published the none of the image apear (Carroussel only) Everything else work perfectly! I tryed with my own image and even with the template unmodified it doesn't work.

**Comment by bainternet** [comment]
We can't replicate this issue, please contact our support and see how they can help you.
support@elementor.com
