### ISSUE TITLE
Gallery columns not working 

### ISSUE THREAD

**Issue by deprohoang** [pojome/elementor#307]
please check this function, it just show like default... when change column it is not effect

**Comment by yehudah** [comment]
Can you explain more ?

**Comment by deprohoang** [comment]
ah,  when i change column of gallery to 2,3,or 4 but frontend just show 1
column

2016-07-28 14:24 GMT+07:00 Yehuda Hassine <notifications@github.com>:

**Comment by arielk** [comment]
We released recently a new version (0.6 and up) please update your plugin and let me know if your bug has been resolved

**Comment by arielk** [comment]
Hi @deprohoang 

We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by DannyOutlaw** [comment]
I also have problem getting this working.  Sometimes I cant get any of the settings to work and I just have to create a new pages and start over.  Also, sometimes the images display in a masonry style layout, while other times, the rows are the height of the tallest image, leaving large gaps under shorter image sin the row.

**Comment by arielk** [comment]
@DannyOutlaw Your problem is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.

**Comment by Chosebow** [comment]
I have the same problem... Any solution?
Thanks!

**Comment by Chosebow** [comment]
Same problem! Solved by turning off some Total Theme module...

**Comment by LiadAF** [comment]
If you've got Autoptimize running on the site, try disabling it. That worked for me. There was also an issue of image gallery not displaying on the frontend (showed perfectly in the editor) and this resolved that.

**Comment by moxet** [comment]
Its not working even now

**Comment by moxet** [comment]
I fixed with this CSS not sure will work with others.

```
.elementor .elementor-widget:not(.elementor-widget-text-editor) figure
{
    display: inline-flex;
    margin:10px;
}
```
