### ISSUE TITLE
BUG: Video Lightbox / Close Button not working correctly on mobile

### ISSUE THREAD

**Issue by stevek28** [pojome/elementor#3079]
Hi,
on mobile (Android-e.g. latest chrome) the Lightbox/video close button is not working correctly. E.g. when the video in Lightbox is almost fullscreen in device landscape orientation so that the close button is over the youtube video..
Clicking it - then just stops/starts the video instead of closing it.. Guess a Z-Index issue..

**Comment by bainternet** [comment]
only in landscape orientation?

**Comment by stevek28** [comment]
..probably also in portrait mode but usually the X close button is not over the video area in portrait.. It only happens when the X is in the video area..

**Comment by bainternet** [comment]
@stevek28 

If the native lightbox don't work well for you then you can try a replacement, I know this plugin works well with elementor https://wordpress.org/plugins/responsive-lightbox/
