### ISSUE TITLE
No Padding, no column/section 

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#308]
I have a theme with no padding on the page-top - so pictures can start right under the mainmenue section. 
in elementor there is also no padding on the page-top (sure) and so the buttons for changing column or section options is hidden behind the mainmenue. i have to set a top padding in CSS to be able to reach the buttons in elementor.

Maybe the buttons should reach down into the sections in case they would be hidden behind other elements like the mainmenue section from the theme. 

Best, Luxamman

**Comment by cobicarmel** [comment]
Hi @Luxamman, this problem has resolved in  #318 and will be released soon. Thank you!
