### ISSUE TITLE
Ability to change the WP icon of widgets

### ISSUE THREAD

**Issue by haulin** [pojome/elementor#3080]
In our company, we're creating a lot of basic WP widgets that get later used in elementor sections. But all of them have the WP icon in the Elementor panel, which doesn't help finding the right one. We have our own icon set for those, but there doesn't seem to be a way of changing the icon programatically for native WP widgets:
![9fd1925f-6d43-4f77-ab15-bfee91b53395](https://user-images.githubusercontent.com/13890095/34562351-e55bf706-f145-11e7-8944-5361ed1ef9e9.png)

It'd be great if the Widget_WordPress/Widget_Base class had an action after the call to get_icon() into which we could hook and change the classname of the icon to something we want. Alternatively #tmpl-elementor-element-library-element could spit out the classname of the widget, similar to what WP does in the admin for its widgets, as these are unique and then we can target the elements with CSS or even JS.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

What you can do, Is create Elementor Native widgets in which you can set the Icon...


Thanks for the feedback.
