### ISSUE TITLE
JS error in latest version 

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#3087]
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
http://localhost/wordpress/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.8.12 line 2

**Comment by bainternet** [comment]
@soyket 

please provide more details of system info and how to replicate.

**Comment by xttn** [comment]
i have same error [#3094!](https://github.com/pojome/elementor/issues/3094)

**Comment by NJohansen** [comment]
@bainternet Im also having the same problem.
I'm capable of seeing the elementor page in incognito window in chrome but when i loging and tries to edit i get this error: 
 Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

And it says The Content Area Was Not Found in Your Page

**Comment by soyket** [comment]
The problem is that happened twice. I couldn't find specific details of the error for that.

**Comment by bainternet** [comment]
ref: #3094
