### ISSUE TITLE
Data attributes on sections?

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#3088]
Isn't there any option for making data-attributes on sections?
**<section data-color="barney" data-title="How we help" >**

**Comment by bainternet** [comment]
@amindiary 

can you explain the need and uses cases?

**Comment by amindiary** [comment]
@bainternet I was trying to convert a HTML layout to WP theme, so designer made sections have data-color and data-title, and made section headers be sticky on scroll , so title and color will change based on those attributes, however I made a custom widget and put those attributes there and changed JS to read those data from my widget, but that would be easier if this feature was there. 

<a href="https://hizliresim.com/0EVBgV"><img src="https://i.hizliresim.com/0EVBgV.png"></a>

My issue solved but still if elementor implement this feature, will be awesome.
P.S. it is awesome currently :P

**Comment by ymilhahn** [comment]
Hello,
I would like to set data attributes as well.
My use case is the Matomo (formely Piwik) [Tracking system](https://developer.matomo.org/guides/content-tracking).
There you use the data attributes to activate and adjust the content tracking.

Thank you!

**Comment by arielk** [comment]
I merged this issue with another issue #4030 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
