### ISSUE TITLE
classes not used for Nav Menu items

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#3089]
If I add classes to items in a WP menu, they're not used by Elementor.

**Comment by bainternet** [comment]
@maxwellhibbert 

Can you provide more details because we cant replicate what you are describing and we get the CSS classes defined in the admin just fine.

**Comment by maxwellhibbert** [comment]
If I add a class to a menu item using the Wordpress menu editor, when that menu is used in elementor the link class is not added to the link on the front end.

**Comment by bainternet** [comment]
@maxwellhibbert 

We can't replicate meanning the classes are added just fine.

Please contact our support and see if they can help you.
Support@elementor.com
