### ISSUE TITLE
Please add Skype to social icons widget

### ISSUE THREAD

**Issue by OffCorner** [pojome/elementor#3090]
I do need to have the skype icon in the social widget. It is in the fontawesome icon pack already, just not in the dropdown when selecting an icon from the social widget dropdown.
Thanks in advance!

**Comment by bainternet** [comment]
@OffCorner 

Thanks, we probably missed that because we do have the CSS color set for it already, so will just add icon to the dropdown.

**Comment by arielk** [comment]
Done: https://github.com/arielk/elementor/commit/99f3c5f8ec6dd06b2af0b13214b7ea2647ef589f
