### ISSUE TITLE
wp_json_encode() crashing

### ISSUE THREAD

**Issue by AnthonyIacono** [pojome/elementor#3091]
wp_json_encode() is failing and causing the editor not to load due to either:
a) the massive $options array
b) an encoding issue with terminating chunked gzip requests

I suggest breaking this into a bit more of a process that isn't so "all-at-once" for encoding the entire object. I also suggest restructuring the way that the object is rendered into the DOM. The exact location that this fails is inside editor.php right after the CDATA open tag is rendered.

## Steps to reproduce
I wish I could give exact steps to reproduce this issue, but all I can say is that it happens for me if I try to do anything on a brand new Godaddy Shared Economy hosting plan (even with upgraded resources and a memory limit of 1gb)

## Environment
See above. Notable issues include GZIP compression causing requests to be terminated incorrectly. Very difficult to debug exactly which character is causing the compression to fail due to Wordpress's chunked-HTTP nature. I was able to fix simply by purchasing a new hosting plan and canceling the old one, but I am 100% certain that this should not occur. I have setup Elementor upwards of 20 times using Godaddy Shared Hosting plans.

**Comment by bainternet** [comment]
@AnthonyIacono 

Please contact our support and see how they can help you.

support@elementor.com
