### ISSUE TITLE
is_built_with_elementor() error - Call to undefined function

### ISSUE THREAD

**Issue by kevinmamaqi** [pojome/elementor#3095]
## Description

I am using the function is_built_with_elementor() in conditionals in my theme and it doesn't work. It throws the following error:

> Call to undefined function is_built_with_elementor() in ../mytheme/template-parts/content.php 

Code included in that file
```
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<header class="entry-header">
		<?php
		if ( is_single() && !is_built_with_elementor() ) :
			the_title( '<h1 class="entry-title">', '</h1>' );
		else :
			the_title( '<h2 class="entry-title"><a href="' . esc_url( get_permalink() ) . '" rel="bookmark">', '</a></h2>' );
		endif;

....
```

## Steps to reproduce

Install elementor (and any theme, tested with twenty themes as well) and use the code in the page.php or content.php files.

**Comment by bainternet** [comment]
There is no function called `is_built_with_elementor` in the global Namspace, there is a method in the `Elementor\DB` class which accepts a post ID as a required parameter, so if you want to use it then you would need to call it correctly ex:
```PHP
Elementor\Plugin::$instance->db->is_built_with_elementor( $POST_ID );
```
