### ISSUE TITLE
Feature Request: Enhance Image Box Widget

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#3098]
## Description

The **Image** widget allows the user to select the **Image Size**:

![elementorimage](https://user-images.githubusercontent.com/576623/34644642-da02aff4-f342-11e7-9378-f7f70b5177ee.png)

The same control should be added to the **Image Box** widget:

![elementorimagesize](https://user-images.githubusercontent.com/576623/34644655-2e9603ae-f343-11e7-9bc3-b583bd91cbda.png)

I should mention that The **Image Carousel** and the **Image Gallery** widgets also allows the user to select the **Image Size**.

**Comment by bainternet** [comment]
@ramiy 

Seems fair, send PR and will have a look

**Comment by amindiary** [comment]
Can you add border radius for image too? 
to be able make this:
<a href="https://hizliresim.com/azqlbz"><img src="https://i.hizliresim.com/azqlbz.png"></a>

**Comment by ramiy** [comment]
@bainternet PR added!

**Comment by ramiy** [comment]
Closing the issue as the PR was merged.
