### ISSUE TITLE
[Idea] Default settings for each widget 

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#3101]
I was thinking it would be great if I can set default settings for an elementor widget and save it, so can make a theme with custom saved widgets and clients can simply put my custom button where they want instead of just using section templates or page templates.

**Comment by bainternet** [comment]
I merged this issue with  #965, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
