### ISSUE TITLE
Feature request - Discord and Steam Social icons

### ISSUE THREAD

**Issue by Campalo** [pojome/elementor#3106]
Could you add the "Steam icon" and "Discord icon" in the social media icons? It could be really useful for games studio website. Please add them! :)
Thanks,

**Comment by bainternet** [comment]
@Campalo 

Steam will be added, as for Discord still waiting on font-awesome to add it or until the web is ready to migrate to V5

**Comment by MaxStriebel** [comment]
FontAwesome has now added a discord icon. Would be great if you could add it.

**Comment by DevZhav** [comment]
When will we see this?

**Comment by adam-g-100** [comment]
Yes still waiting on Discord :(

**Comment by jebuske** [comment]
waiting for this as well
