### ISSUE TITLE
Bug: Mobile behaviour of nav menu widget

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#3114]
Desktop view:
![menu - desktop](https://user-images.githubusercontent.com/14095280/34697354-02287b4e-f4d3-11e7-9dd1-5bf3421d618a.JPG)
Mobile view:
![menu - mobil](https://user-images.githubusercontent.com/14095280/34697362-0f35b518-f4d3-11e7-9bbe-5c6d0c97b8dd.JPG)
The text-color of the active menu item in mobile view, which has sub menu items, is not displayed correctly.

**Comment by bainternet** [comment]
@HelmutGoebel 

can you share a link or a screenshot of the menu settings panel so we could replicate.

**Comment by HelmutGoebel** [comment]
I've changed the second color to silver-grey rather than yellow. But the result is the same:

![grafik](https://user-images.githubusercontent.com/14095280/34823570-33794f58-f6cb-11e7-87e6-2908d6ebec7a.png)

![grafik](https://user-images.githubusercontent.com/14095280/34823597-56fd96d2-f6cb-11e7-8de9-e4a5449d0e78.png)

![grafik](https://user-images.githubusercontent.com/14095280/34823624-7ceca54a-f6cb-11e7-93f7-33e6dafa2049.png)

![grafik](https://user-images.githubusercontent.com/14095280/34823644-90cb3e00-f6cb-11e7-848a-b70ce8b50cfe.png)

![grafik](https://user-images.githubusercontent.com/14095280/34823694-cb565938-f6cb-11e7-9bd5-dcc4ddf54ed2.png)
![grafik](https://user-images.githubusercontent.com/14095280/34823705-df327a04-f6cb-11e7-8ed8-87dfcc6a9e2c.png)

**Comment by bainternet** [comment]
@HelmutGoebel 

Thanks, 
Still can't replicate, can you please contact our support and see how they can help.

support@elementor.com

**Comment by HelmutGoebel** [comment]
The fact, you can't replicate, means to me, you didn't really tried.
