### ISSUE TITLE
Post Type and CPT sharing same Posts Widget

### ISSUE THREAD

**Issue by stllrnet** [pojome/elementor#3115]
I know Elementor does support CPT's. But it's only possible having one at a time in the posts widget. I think it would be a nice addition having the power to display more than one post type in the same widget. Some websites could benefit from this, as having separated sections for every CPT isn't required.

**Comment by bainternet** [comment]
Thanks for the suggestion,

we'll try to add it.

**Comment by bainternet** [comment]
Will be possible with a simple filter via #1748
