### ISSUE TITLE
Section background image should be on separate <div>

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#3116]
Elementor version 1.8.x

Currently, background image (classic) is implemented via CSS to the main `<section>` tag. I think it's better to make a separate `<div>` to wrap all background features. That way it would be easier for anyone who want to extend the background image features, like implementing parallax, etc. Currently there is no way to extend or modify element's rendered tag.

I suggest the HTML tag structure to be like this:

```
<section ...>
    <div class="elementor-background">
        <!-- If background image mode is active -->
        <div class="elementor-background-image"></div>

        <!-- If background video mode is active -->
        <div class="elementor-background-video"></div>

        <!-- If background overlay is active -->
        <div class="elementor-background-overlay"></div>

        <div class="elementor-container ..."></div>
    </div>
</section>
```

The reason I am asking for this is, I want to add a parallax feature into any type of background (video / image) via custom javascript.

A parallax feature should be by modifying CSS `transform` property not the `background-position` property ([as mentioned here](https://developers.google.com/web/updates/2016/12/performant-parallaxing)). The current implementation makes it impossible to use `transform` property (because background image is implemented directly into the `<section>` tag). The only feasible way is to implement parallax via `background-position` property, which is very bad for performance.

Let me know if there is a solution for this.

Regards

**Comment by copen8** [comment]
I think it sounds like a good idea. I think css transform would open more opportunities. For example scale background-image when hover(not scale whole section). The only way to do this right now is to use background-size and set it to a higher value than 100%. But this method cause problems then it comes to responsiveness.  So it is much more preferable to use css transform and have background-image in a separate div.

**Comment by daviedR** [comment]
Any response from Elementor team?

**Comment by bainternet** [comment]
@daviedR 

I'm glad to tell you that we are actively thinking about it, as for, how and when it's not something I answer right now.

thanks for the feedback.
