### ISSUE TITLE
Vimeography conflict

### ISSUE THREAD

**Issue by robmygriefnow** [pojome/elementor#3119]
I have a conflict with the plugin Vimeography... Please help with the below from Vimeography... thx Rob For some reason, elementor tries to parse the Vimeography shortcode on the admin editor page and the javascript fails since the gallery isn't shown on pageload. Try adding the following code to your local copy of the Vimeography Strips plugin at vimeography-strips.php and let me know if it helps to correct this issue: Change this: public static function load_scripts() { // Deregister common scripts and styles here wp_deregister_script('fitvids'); To this: public static function load_scripts() { if ( function_exists('get_current_screen') && is_admin() ) { $screen = get_current_screen(); if ( $screen->base == 'post' ) { return; } } // Deregister common scripts and styles here wp_deregister_script('fitvids'); I'll have to find a better workaround in the future, but keep this change in mind because you may need to re-add it if an update to the Strips plugin becomes available. I don't mind making a change to ensure Elementor compatibility, but I'd need to find out exactly what the conflict is. As an Elementor customer, is there any way you'd be willing to contact Elementor with a support request to determine why Elementor is parsing the shortcode in the admin, or how to otherwise prevent it from doing so? Let me know, -- Dave Kiss support@vimeography.com

**Comment by bainternet** [comment]
Thanks for opening the issue, but its .......

**Comment by robmygriefnow** [comment]
I have a conflict with the plugin Vimeography... Please help with the below from Vimeography... thx Rob For some reason, elementor tries to parse the Vimeography shortcode on the admin editor page and the javascript fails since the gallery isn't shown on pageload. Try adding the following code to your local copy of the Vimeography Strips plugin at vimeography-strips.php and let me know if it helps to correct this issue: Change this: public static function load_scripts() { // Deregister common scripts and styles here wp_deregister_script('fitvids'); To this: public static function load_scripts() { if ( function_exists('get_current_screen') && is_admin() ) { $screen = get_current_screen(); if ( $screen->base == 'post' ) { return; } } // Deregister common scripts and styles here wp_deregister_script('fitvids'); I'll have to find a better workaround in the future, but keep this change in mind because you may need to re-add it if an update to the Strips plugin becomes available. I don't mind making a change to ensure Elementor compatibility, but I'd need to find out exactly what the conflict is. As an Elementor customer, is there any way you'd be willing to contact Elementor with a support request to determine why Elementor is parsing the shortcode in the admin, or how to otherwise prevent it from doing so? Let me know, -- Dave Kiss support@vimeography.com

**Comment by robmygriefnow** [comment]
Boaz from elementor told me to post this. Why have you closed it?

**Comment by bainternet** [comment]
I was the one who told Boaz to forward you here so we can help better.

The issue was closed because of the way it was opened.

A simple copy paste of a blob of text is not helpful and you didn't even remove the guide lines from the issue or actually describe the issue with steps to reproduce.

Anyway I'll wait for Dave from Vimeography to reach out and work on a permanent solution and reopen it.

**Comment by robmygriefnow** [comment]
Ah.. Sorry for any inconvenience and thanks for taking the time to explain what I did wrong.

416-453-0646
mygriefnow.com<http://mygriefnow.com>
"Helping grief make sense... one story at a time"

On Jan 10, 2018, at 1:43 AM, raz ohad <notifications@github.com<mailto:notifications@github.com>> wrote:


I was the one who told Boaz to forward you here so we can help better.

The issue was closed because of the way it was opened.

A simple copy paste of a blob of text is not helpful and you didn't even remove the guide lines from the issue or actually describe the issue with steps to reproduce.

Anyway I'll wait for Dave from Vimeography to reach out and work on a permanent solution and reopen it.

**Comment by davekiss** [comment]
Hey guys, it seems like Elementor is attempting to render Vimeography shortcode in the admin on any page edit screen. Is there any way to prevent that?

**Comment by robmygriefnow** [comment]
-- Please reply above this line --


I have replied there, I'll let you know if I see an update (or, you
can reach out if you see a new update there as well)
--
Dave Kiss
support@vimeography.com

**Comment by davekiss** [comment]
@bainternet Can this please be reopened? Boaz mentioned to open a ticket here. Here was his message:

---
Hi Rob,

In principle, there is a solution, and not a complicated one, but it should come from Vimeography end.Please tell to David from Vimeography, to open an issue in Github and we will gladly assist him.Kind Regards,

--Boaz from Elementor

**Comment by robmygriefnow** [comment]
Hi Dave,

Did anything ever happen to fix this?

Thx

416-453-0646
griefstories.org<http://griefstories.org>
"Helping grief make sense... one story at a time"

On Feb 5, 2018, at 3:16 PM, Dave Kiss <notifications@github.com<mailto:notifications@github.com>> wrote:


@bainternet<https://github.com/bainternet> Can this please be reopened? Boaz mentioned to open a ticket here. Here was his message:

________________________________

Hi Rob,

In principle, there is a solution, and not a complicated one, but it should come from Vimeography end.Please tell to David from Vimeography, to open an issue in Github and we will gladly assist him.Kind Regards,

--Boaz from Elementor
