### ISSUE TITLE
Setting 'Overlay' to be 'Description' in 'Media Carousel' shows weird content

### ISSUE THREAD

**Issue by hzesen1221** [pojome/elementor#3120]
## Description

Setting 'Overlay' to be 'Text - Description' in 'Media Carousel' shows weird content.

Screenshot: https://ibb.co/eUkvcR

## Steps to reproduce

It's weird that if I create a brand new page and drag in a Media Carousel this bug goes away, but if I do it on an old page, it shows up. For consistency:

1: let's create a new Page and sets template to Elementor Canvas, then, loads the content of 'Homepage - App' from the remote library.

2: Drag a Media Carousel under the headline.

3: Sets 'Overlay' to be 'Text - Description'.

4: Save the page. To me, anything is still fine.

5: Reload elementor page, and now hover your mouse on an image, you should see this: https://ibb.co/eUkvcR

If you save your page after this point, the weird behavior shows up on frontend. If you need to check this online, I got a page ready here: http://wpheros.senze.co/blank

It seems like the entire page content becomes the overlay content to me.

**Comment by bainternet** [comment]
please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists, please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by AdalDesign** [comment]
I experience the same issue: if the description field on an image is empty, instead it seems to load content from the page and creates exactly what hzesen1221 showed in his screenshot. This is not an isolated issue.
