### ISSUE TITLE
Global colors should be selectable in text editors, it seems it doesn't work.

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3121]
Hi, the global color palettes seem not to be loaded in text editors. Please see attachments.

Using Elementor Pro v1.12.3 on wp v4.9.1

![schermata 2018-01-09 alle 17 53 34](https://user-images.githubusercontent.com/437598/34732729-59916470-f566-11e7-87df-7649cf14e4dc.png)

![schermata 2018-01-09 alle 17 53 49](https://user-images.githubusercontent.com/437598/34732730-59b2b86e-f566-11e7-8b7a-415d543f8f43.png)

**Comment by jayalove** [comment]
Agreed

**Comment by eplanetdesign** [comment]
+1

**Comment by arielk** [comment]
Sorry, but for now this is not possible, maybe in the future, we'll add this feature.

Thanks for your feedback!
