### ISSUE TITLE
Using CenterMode in Slick slider / Image Carousel

### ISSUE THREAD

**Issue by ryanlabelle** [pojome/elementor#3123]
I've created a custom control for the Image Carousel widget and would like to use Slick's CenterMode (centerMode: true,) as seen on http://kenwheeler.github.io/slick/

Is there a way to hook into Elementors ImageCarouselHandler or an alternate way to change options for Slick? 

Thank you very much for your time.

**Comment by bainternet** [comment]
Yes there is a way, simply get the instance of the Slick slider and apply whatever you want to it, ex:

```javascript
var slider = jQuery('.elementor-slides').slick('getSlick');
slider.slickSetOption( 'centerMode', true,true ); // last true triggers a refresh of the UI.
```

**Comment by ryanlabelle** [comment]
Thank you! That helps resolve 1 piece of the puzzle. Now I just need to dive into the fancy callback handler you have working for the image carousel widget. Once the settings are set and saved from the widget control, the JS needs to read them. I've used data attributes before but slick slider has many settings / options, I'd rather use something similar to your image carousel callback handler. 

I know your time is valuable, no worries if you don't get back. 

Thank you for your assistance already. You guys are awesome.

**Comment by amindiary** [comment]
@bainternet thank you but it not works for me. 
**Uncaught TypeError: slider.slickSetOption is not a function**
