### ISSUE TITLE
Template upload popup in Elementor has no back fuction

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#3124]
Love the new template upload popup in Elementor!

Small detail: When in you are in the upload a new template view, there is no back button to the your templates part.

You will have to close the editor. Open the template library up again and switch back to your templates.

![2018-01-09_204353](https://user-images.githubusercontent.com/5883842/34742367-df3b0c22-f57d-11e7-9820-c3505d164fb2.png)

**Comment by bainternet** [comment]
Click on "Library" on the top bar, it will take you back.
