### ISSUE TITLE
Feature Request: AgileCRM integration

### ISSUE THREAD

**Issue by vatsalt** [pojome/elementor#3125]
The new integration options launched recently are awesome. But I would have liked to see more, notably Agile CRM. Like Elementor a very fast growing platform in its sector, getting the attention of old-timers like me who used to swear by Salesforce, MS Dynamics, Hubspot, Mailchimp and ilk.

Elementor is awesome, much better than all competition! And everyone to whom I recommend Elementor quickly come to agree with me. If there is any way you could add Agile CRM to the list of integration options and I can recommend Elementor to even more people!

Kind regards

Vatsal

**Comment by bainternet** [comment]
I merged this issue with  #2397 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by MikeHendrikse** [comment]
I finally worked out how to add an. Agile CRM form to a Wordpress website using Elementor. Ny guide can be viewed here: https://www.evernote.com/l/AjeFja9j3b9NS47sPucgDK8Swe2pBLrgUG4
