### ISSUE TITLE
Keyboard "Save" (Cmd/Ctrl + S) no longer works

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#3126]
Great job on the updates in v1.9. 

One issue I have is being unable to save using the keyboard Cmd+S. I realised there's auto-save but when I have changes I want to apply I don't want to wait for the auto-save feature to run. Can this key binding be reinstated please?

**Comment by arielk** [comment]
Keyboard "Save" (Cmd/Ctrl + S) is now Save the changes to draft as autosave does. 

To better clarify this is the logic behind the new method (Autosave / Auto-Draft):

| ACTION                	| DRAFT                    	| PUBLISHED                   	|
|-----------------------	|--------------------------	|-----------------------------	|
| Autosave              	| Save to draft revision   	| Save to Auto-Draft revision 	|
| Save Draft / CTRL + S 	| Make a new revision      	| Save to Auto-Draft revision 	|
| Publish               	| Change Status to Publish 	| --                          	|
| Update                	| --                       	| Make a new revision         	|

**Comment by JoelEadeDesign** [comment]
Thanks for the clarification. Can keyboard support be added for "Update"? Perhaps Shift+Cmd+S. Personally, it's going to slow down my workflow to have to use the mouse to save the page. 

Out of interest, why was "Save Draft" was given priority over "Update"?

**Comment by maxwellhibbert** [comment]
I agree, there needs to be a dedicated publish shortcut. I downgraded a version because of this..

**Comment by xttn** [comment]
Need hotkey to Save Publish!!

**Comment by JoelEadeDesign** [comment]
Well, I guess that's the end of that conversation...

**Comment by maxwellhibbert** [comment]
So that's a "no" then?

**Comment by bainternet** [comment]
@maxwellhibbert 

Open a new issue as a request for "Shift+Cmd+S" ....
