### ISSUE TITLE
Default values to Border Group doesn't work

### ISSUE THREAD

**Issue by vrundakansara** [pojome/elementor#3128]
I need to set default values for the Border Group field. The default shown here does not quite work – http://bsf.io/7l6ae

Can you please help me find a way out.

**Comment by ramiy** [comment]
@vrundakansara It is working but you are using it the wrong way.

With group controls you can control the inner controls using `fields_options`. For example the [border group control](https://github.com/pojome/elementor/blob/master/includes/controls/groups/border.php) has 3 inner controls (`border`, `width` and `color`), you can update their values in your widget the following way:

```php
$this->add_group_control(
	Group_Control_Border::get_type(),
	[
		'name' => 'some_border',
		'label' => __( 'Some Border', 'elementor' ),
		'fields_options' => [
			'border' => [
				'default' => 'solid',
			],
			'width' => [
				'default' => [
					'top' => '1',
					'right' => '2',
					'bottom' => '3',
					'left' => '4',
					'isLinked' => false,
				],
			],
			'color' => [
				'default' => '#D4D4D4',
			],
		],
		'selector' => '{{WRAPPER}} .some-class',
	]
);
```

**Comment by huykon** [comment]
not working

**Comment by alweso** [comment]
not working

**Comment by patrickzeitz** [comment]
> not working

you have to add => \Elementor\ 

`
$this->add_group_control(
	\Elementor\Group_Control_Border::get_type(),
	[
		'name' => 'border',
		'label' => __( 'Border', 'elementor' ),
		'fields_options' => [
			'border' => [
				'default' => 'solid',
			],
			'width' => [
				'default' => [
					'top' => '1',
					'right' => '1',
					'bottom' => '1',
					'left' => '1',
					'isLinked' => true,
				],
			],
			'color' => [
				'default' => '#d4d4d4',
			],
		],
		'selector' => '{{WRAPPER}} .some-class',
	]
);

`
