### ISSUE TITLE
Bug: errors after WordPress widget form loading

### ISSUE THREAD

**Issue by MjHead** [pojome/elementor#3129]
JS error appears after standard WordPress widget form loads with Ajax - http://prntscr.com/hygib5. Looks like `self` should be instead of `this` here - https://github.com/pojome/elementor/blob/master/assets/js/editor.js#L4032 and here - https://github.com/pojome/elementor/blob/master/assets/js/editor.js#L4039

**Comment by bainternet** [comment]
@MjHead 

thanks for reporting,
Fixed in 1.9.1
