### ISSUE TITLE
Button: Color change on mouseover

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#313]
Seems that the color change on mouseover is not workting with the font color for buttons.

Luxamman

**Comment by yehudah** [comment]
Hi,

I have tested what you describe and it's working.

Try to replace to the default theme and see if the problem continue.

**Comment by arielk** [comment]
Hi @Luxamman 

We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
