### ISSUE TITLE
Feature Request for Theme Builder - Ubermenu Compatibility 

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#3131]
Can't wait for the theme builder from Elementor, Kindly consider Automatic Integration with Ubermenu as Manual integration with themes not compatible is a nightmarish process for non-coders.

http://sevenspark.com/docs/ubermenu-3/integration/automatic/requirements

Thx

**Comment by bainternet** [comment]
@Dentalicious 

After thinking about it the best way to achieve that would be to have Uber menu support Elementor with a custom Uber menu widget.

So if you have a contact there feel free to send him over here to help in any way we can.

**Comment by Dentalicious** [comment]
I have passed the msg pointing them to this link.

**Comment by sevenspark** [comment]
Hi guys,

It'd be great for Elementor and UberMenu to work seamlessly together.

Generally, we just advise adding UberMenu within Elementor by using UberMenu's shortcode inside an Elementor block.

UberMenu does ship with an UberMenu widget as well - is that what you're recommending, or does Elementor implement its own widget system that UberMenu would need to support?

For reference:

Shortcode: http://sevenspark.com/docs/ubermenu-3/integration/shortcode

Widget: http://sevenspark.com/docs/ubermenu-3/integration/widget

If there's something more specific we can be doing, let me know :)

Best,

Chris

**Comment by arielk** [comment]
It seems like everything works well so I close the issue for now. Feel free to reopen the issue and we'll be happy to help you.
