### ISSUE TITLE
update button should rigenerate css as well

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3132]
Hi, since a lot of styles can be coded on external custom css files by the developer (I personally use a library of mine, as many others I guess), the green update button should regenarate elementor's css as well (much like you can manually do from tools on elementor's dashboard).

Or, you could simply add a 'regenerate css' button aside the 'update' one.

Or, you could do things in a manner that elementor's css rules are always overridden by the developer's rules. This would be the best and most correct thing I think. Elementor's editor should always reflect the merge of elementor's css + developer overrides, without the need to regenerate css.

**Comment by bainternet** [comment]
@stratboy 

They way it should work is: when you hit the update the CSS file is removed, so next time someone loads the page the CSS file is generated newly.

if that's not happening to you please provide steps to replicate and your system info.

**Comment by stratboy** [comment]
Doing some more research here.

**Comment by bainternet** [comment]
So like I said its not something we can replicate, but if you continue to have this issue please feel free to repoen.
