### ISSUE TITLE
Price List

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#3134]
The Price List Feature is excellent; however, if there are many items and sub-items, the list becomes too long on a page, thereby having to scroll laboriously, which then gets confusing.
A useful addition/alteration feature would be to allow a function similar to that of an accordion.
i.e. 
1) Content Title > Multiple Sub Lists (price lists) 
2) Content Title > Multiple Sub Lists (price lists)
3) Content Title > Multiple Sub Lists (price lists)
4......5.....6...

So if instance for a restaurant menu, Item 1 is a Starters menu, Item 02 for Main, Item 03 for desserts and so on and each main item heading has its own drop-down lists of subitem description and price lists.

The restaurant may only have 3-5 courses or multiples of that in case of a multi-cuisine one, similarly in my instance, the requirement is for Treatment options and lists within, so General Dentistry, Cosmetic Dentistry & so on. ScreenShot attached. I have 15 Such Content titles and 2-7 Items within each, the page becomes extremely long and navigating what information one needs gets confusing.

An accordion style feature would display all 10-15 Content titles on the available screen view and then it depends on what the user is looking for and would click the drop down, the UX would be much much better.

Kindly consider it.

Thx.
![screen shot 2018-01-10 at 20 17 16](https://user-images.githubusercontent.com/33909786/34778482-772356c8-f643-11e7-83e4-5247864fad5c.jpg)
![screen shot 2018-01-10 at 20 17 25](https://user-images.githubusercontent.com/33909786/34778484-775f7a5e-f643-11e7-8bdf-3821226f0127.jpg)

**Comment by bainternet** [comment]
@Dentalicious 

what about creating a few smaller lists? won't that help?

**Comment by Dentalicious** [comment]
the individual no. of the list (3-6-... Items) would be dictated by the content title but overall when many such content titles exist, then the page becomes way too long and confusing.
Accordion style drop-down would collapse the lists and only content titles would be viewable on the screen space thereby leading to a much better ux as the visitor would click what they are looking for.

I have briefly opened the site up from "coming soon mode', the issue can be viewed here,
https://www.dentalicious.com.au/pricing/

**Comment by bainternet** [comment]
Well then again creating a few smaller lists and inserting them via shortcode to an accordion should do just that.

Or am I missing the point?

**Comment by Dentalicious** [comment]
Yeah, that would work nicely, thx for the idea, awesome.
