### ISSUE TITLE
WP Editor content missing

### ISSUE THREAD

**Issue by diggeddy** [pojome/elementor#3139]
1.9 release - content from WP Editor no longer appears in Elementor editor.

**Comment by jayalove** [comment]
Yes! I am having this problem. The old B.B. content was turned into generic wp content when I switched over to Elementor. Not though when I chose to edit the page w Elementor, I lose all regular wp editor content that was there already from B.B.

**Comment by bainternet** [comment]
@diggeddy , @jayalove Can you check if you have revisions?? and if the content is in there???

**Comment by diggeddy** [comment]
@bainternet steps as follows. Clean install. GP Theme (free). Elementor and Elementor Pro. No other plugins. Content added via WP Editor. Published. Edit in Elementor. Update page. Exit to dashboard. Content is removed but is in the WP revisions.

**Comment by jayalove** [comment]
@bainternet I'm running up to date Astra and Elementor. Yes the OG content is in WP revisions, and I can see where it went to nothing, then more revisions with my work since then.

**Comment by norewp** [comment]
Run into this issue today and I've had a look at the revisions plus reapplied them but nada!

Symptoms: 
1. Visiting a previously Elementor edited page you find the content has gone walkies somewhere.
2. Applying revisions brings back an empty placeholder(original widget?) but no content - clicking on this results in a blank side pane!
3. Exit the editor and switch back to default editor and the content is there.

NOTE: This only happened on previously edited content - new pages/templates were fine!
Everything is up to date and reverting back to previous versions of Elementor and/or Pro did not solve the issue - had to drop the database and start over.

**Comment by bainternet** [comment]
Should be fixed in 1.9.2.

thanks.

**Comment by bainternet** [comment]
We can replicate,

Working on a fix.

**Comment by bainternet** [comment]
ref: #3217

**Comment by arielk** [comment]
Fixed in v1.9.3

**Comment by jayalove** [comment]
Whoot! Thanks so much!
