### ISSUE TITLE
Can't edit WooCommerce Shop page

### ISSUE THREAD

**Issue by Nat-Faeeria** [pojome/elementor#314]
I don't know why, I can edit every pages created by WooCommerce with Elementor, but the Shop page shows the option "Edit with Elementor", when I click on it it just displays the page, I don't have elementor tools or anything.

**Comment by arielk** [comment]
WooCommerce doesn't print the the_content tag on the single product, so Elementor can't work.

I hope that in the future we will integrate with WC, maybe we'll do it pro version

**Comment by Nat-Faeeria** [comment]
Oh ok, because on your website it was saying "fully compatible" so ...
