### ISSUE TITLE
Feature Request/Enhancement: Option to Reverse Columns for Tablets

### ISSUE THREAD

**Issue by invictusdm** [pojome/elementor#3141]
Currently on the Edit Section > Advanced > Responsive menu, we have the option to reverse columns for display on mobile devices. This is a great feature I would like to see expanded to have the separate ability to perform the same for tablet devices. For now, we are stuck with column 1 always defaulting to the top if we attempt to stack the columns vertically (at 100% width) on tablet view. This limits certain layout design options since there's no control over column order when viewed vertically. Thanks!

**Comment by bainternet** [comment]
I merged this issue with  #2070, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
