### ISSUE TITLE
Bug in Elementor 1.9: Opening Elementor deletes all content

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#3144]
## Description
When I open the Elementor editor the complete content of the page gets deleted. It just opens a blank page. All plugins are disabled, still having the issue: http://somup.com/cFVXXHVUWT

The problem happens to almost all pages that not have been opened in Elementor 1.9 before. Also tried multiple websites and hosts. Did not make a difference.

**Comment by pinguinlands** [comment]
We do face that problem also.... We can't edit an article with elementor. If we did it on the beginning with elementor it's ok.
![deepinscreenshot_select-area_20180111180752](https://user-images.githubusercontent.com/35077260/34834996-34e45726-f6fc-11e7-93de-bb70fb462cd4.png)
![deepinscreenshot_select-area_20180111180911](https://user-images.githubusercontent.com/35077260/34834997-3529804e-f6fc-11e7-9248-6fa27684cfe8.png)

**Comment by arielk** [comment]
Fixed in v1.9.2
