### ISSUE TITLE
Page changes not saving when running on hosted openshift 

### ISSUE THREAD

**Issue by sharonv** [pojome/elementor#315]
Changes are not saved.
In some cases the editor is not showing with various console errors.

**Comment by yehudah** [comment]
Hi,

There is conflicts with SSL in openshift.
Just before you start edit change the protocol in the url to HTTPS and refresh.

**Comment by yehudah** [comment]
As a temp workaround, please try to add this code to your theme functions.php
`add_filter( 'admin_url', function( $url ) {
    if ( is_ssl() || force_ssl_admin() ) {
        $url = str_replace( 'http://', 'https://', $url );
    }
    return $url;
} );`

**Comment by sharonv** [comment]
This workaround seems to work. Great.
