### ISSUE TITLE
Shortcode in Flip Box

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#3154]
Accordion Shortcode gets messed up on the back side of a flip box.
Not that the accordion doesn't get displayed at all, it does but it goes out of whack.

<img width="2046" alt="screen shot 2018-01-12 at 13 18 51" src="https://user-images.githubusercontent.com/33909786/34864725-b32f1112-f79b-11e7-8dc4-46b5ff604f1c.png">
<img width="2046" alt="screen shot 2018-01-12 at 13 17 31" src="https://user-images.githubusercontent.com/33909786/34864729-b59121de-f79b-11e7-8b34-6c4ba0c40b6f.png">
<img width="2048" alt="screen shot 2018-01-12 at 13 17 19" src="https://user-images.githubusercontent.com/33909786/34864731-b6add620-f79b-11e7-9204-ea1f36a08e7d.png">
<img width="2048" alt="screen shot 2018-01-12 at 13 17 02" src="https://user-images.githubusercontent.com/33909786/34864733-b7e6c0e2-f79b-11e7-87d7-5146f4d6f3c6.png">

**Comment by bainternet** [comment]
@Dentalicious 

As far as I can tell accordion/toggels are not supported inside a Flip Box.
