### ISSUE TITLE
How to change a parent section frontend html output based on child widget settings?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3156]
Hi, I don't know if this is the right place to ask. Anyway, I'm creating a custom widget. It will have switchers inside. Based on the switcher settings, I will need to add several different classes (one per switcher) to the container section (elementor-section). I see several hooks that could maybe help, both php and js. But what's the recommended way to do it? What's the more correct way / best practice, in your (developers) opinion?

**Comment by bainternet** [comment]
Definitely PHP,

JS template is there for edit mode view so it would help if it supports the markup as well but the final render is via PHP.

**Comment by stratboy** [comment]
ok thank you, what's the best php hook then?

**Comment by stratboy** [comment]
I'm intereste in  'elementor/frontend/section/before_render', but it seems not implemented yet. I can find it on hook docs, but it seems it doesn't work. Is it true?
