### ISSUE TITLE
Feature Request: Forms - Sendy Integration

### ISSUE THREAD

**Issue by billyhoiler** [pojome/elementor#3157]
Please consider support for "Sendy" within Form submissions, so we don´t have to use another plugin for that (mailoptin).
Thank you.

**Comment by bainternet** [comment]
I don't think there is a large demand for it for us to develop it but its something you can do very easily, something like:
```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $this ) {
	$fields = [
              'email' => $record->fields['email'],
              'list' => LIST_ID_HERE,
              'name' => $record->fields['name'],
        ];
	
	wp_remote_post( 'http://your_sendy_installation/subscribe', [
		'body' => $fields
	]);
});
```
now this is just an example and it's assuming your form fields are named to match Sendy field names.

The full list of available/required/custom fields is listed in their [API docs.](https://sendy.co/api)

Hope this helps.

**Comment by billyhoiler** [comment]
Thanks for the fast response.
I am eager to try this out but since I am no expert, I wonder where I need to put this code?
Also will this create another option inside the elementor form settings?

Right now we are using the mailoptin plugin and it needs the API key. 
A little surprised that the above method does not need the API key(?)
Thank you.

**Comment by onyxchase** [comment]
I would also be interested in seeing Sendy as an option for form actions. Sendy is SO much cheaper than typical monthly autoresponders and I think most people using Elementor are also using it because it is a yearly fee versus monthly. We don't want to edit the code... We simply want to slap in our API code in the admin area and then add subscribers via forms. Can this be done?

**Comment by passionplux** [comment]
Hi guys , where am I suppose to place this code ? I don't where to post it . Please help.

--
add_action( 'elementor_pro/forms/new_record', function( $record, $this ) {
	$fields = [
              'email' => $record->fields['email'],
              'list' => LIST_ID_HERE,
              'name' => $record->fields['name'],
        ];
	
	wp_remote_post( 'http://your_sendy_installation/subscribe', [
		'body' => $fields
	]);
});
--

**Comment by blackgoku** [comment]
Many people do want this feature, a direct integration will be good.

**Comment by blackgoku** [comment]
@jim2564 lets open a new feature resquest thread on github.

**Comment by passionplux** [comment]
> I don't think there is a large demand for it for us to develop it but its something you can do very easily, something like:
> 
> ```
> add_action( 'elementor_pro/forms/new_record', function( $record, $this ) {
> 	$fields = [
>               'email' => $record->fields['email'],
>               'list' => LIST_ID_HERE,
>               'name' => $record->fields['name'],
>         ];
> 	
> 	wp_remote_post( 'http://your_sendy_installation/subscribe', [
> 		'body' => $fields
> 	]);
> });
> ```
> 
> now this is just an example and it's assuming your form fields are named to match Sendy field names.
> 
> The full list of available/required/custom fields is listed in their [API docs.](https://sendy.co/api)
> 
> Hope this helps.

Actually , there is a HUGE DEMAND FOR THIS. PLEASE INTEGRATE SENDY WITH ELEMENTOR  PLZZ

**Comment by blackgoku** [comment]
passionplux i have opened a new feature request post for this, do comment on that or open a new request post.

**Comment by JoseSoteloCohen** [comment]
Hello guys!

This plugin should help you with sending submissions from Elementor Form to your Sendy lists.

https://wordpress.org/plugins/inboundlatino-sendy-elements/
