### ISSUE TITLE
API: a way to create custom Elementor categories?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3158]
Hi, currently it seems not possible. I see the function Elements_Manager::init_categories, but it's private and without any hooks. So how can create my own widgets under a custom title/category?
Is there any way? If not, could you consider to add at least some hook?

**Comment by norewp** [comment]
https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md#elementorinit

**Comment by stratboy** [comment]
!!! :) Thanks
