### ISSUE TITLE
Feature Request: Ability to add markup comments to sections/objects

### ISSUE THREAD

**Issue by sandrop** [pojome/elementor#3160]
I am in the process of integrating a design into Elementor and it's complex enough that I needed to actually create duplicate sections and edit them for desktop/tablet/mobile rather than relying on manipulating individual objects. 

Anyway, I was thinking it would be super helpful to be able to have a comments option in the section object so that I can denote which section is which section and why things are the way they are. Maybe in the Edit Section panels?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
