### ISSUE TITLE
Email Form accepts emails without domain suffix

### ISSUE THREAD

**Issue by badcat** [pojome/elementor#3164]
Using the Form widget, I've set an email address to be Required.
If I enter the email following a pattern of:

```something@something```

This works, but it probably shouldn't   :(   It should likely be checking for a pattern that includes a domain suffix like .com, .io, .edu etc.

```something@something.xx```

or even...

```something@something.xx.xx```

thanks.

**Comment by bainternet** [comment]
The email validation is done by the browser. if you need more validation you can use the provided filter to validate, ex:
```PHP
// Validate the Ticket ID field is in XXX-XXXX format.
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {
	$fields = $record->get_field( [
    	'id' => 'eimail',
	] );
	
	if ( empty( $fields ) ) {
        	return;
        }
	
	$field = current( $fields );

	if ( ! is_email( $field['value'] ) ) {
		$ajax_handler->add_error( $field['id'], 'Invalid Email address, it must be in the format XX@XX.XX' );
	}
}, 10, 2 );

**Comment by EladGeek** [comment]
I've been using this solution, works like a charm :)

I would want to have the option to set this to apply only on selected forms (e.g. exclude webinar forms).
How can I trigger this selectively, for example only for email fields with the name "work_email"?
