### ISSUE TITLE
[Bug][Elementor 1.9] Testimonial Carousel Widget - Content tab in Style does not push other tabs down

### ISSUE THREAD

**Issue by drank** [pojome/elementor#3165]
The usual behavior when a tab is opened is to push the below tabs down, as shown in the following 2 images:
![img01](https://user-images.githubusercontent.com/1393766/34905873-7d5514d6-f86a-11e7-8345-3ad360440905.jpg)![img02](https://user-images.githubusercontent.com/1393766/34905874-7d70e472-f86a-11e7-9060-b8eeb1b952fd.jpg)

But this is not the case with the "Content" tab in the Testimonial Carousel Widget:
![img03](https://user-images.githubusercontent.com/1393766/34905875-7d8d50f8-f86a-11e7-873f-ffe63e3bec42.jpg)

**Comment by bainternet** [comment]
@drank 

thanks for reporting should be fixed in 1.9.2
