### ISSUE TITLE
[Bug] Three levels of Typography - buggy behavior in Testimonial Carousel widget

### ISSUE THREAD

**Issue by drank** [pojome/elementor#3166]
The Testimonial Carousel widget has 3 levels of Typography which work very buggy:
![img04](https://user-images.githubusercontent.com/1393766/34906309-cf45bc10-f873-11e7-9031-f8095be3f75d.png)

1. Why are these nested?
2. Is the 2nd one related to Name and the 3rd one related to Title? If so, how easy would it be to find the typography for Title (rhetorical question :-) )?
3. When I try edit a value in the 3rd level, the whole galore just closes and I need to open them one by one again just to do small edits. Happens on every edit => impossible to tweak some of the values (e.g. the text color of the Title).
4. Why are the top-level tabs "Image", "Navigation", and "Bubble" located in the 3rd level of pop-ups?

I was saying this before and will repeat this again - the whole Typography pop-up idea and implementation is a BIG step backwards in the quality of Elementor. Please consider reworking it.

**Comment by bainternet** [comment]
@drank 

thanks for reporting, should be fixed in next version, PR #3146

**Comment by drank** [comment]
Dear Elementor Team,

Thank you for fixing the above issues! I checked and now these bugs are gone.
