### ISSUE TITLE
[Feature Request] Time setting for progress bar

### ISSUE THREAD

**Issue by JayTee2312** [pojome/elementor#3168]
Hi,
I miss a time setting for progress bars. It would be nice if you could set a time in the settings how long a progress bar takes to reach the specified position, e.g. 100% to arrive. So you could, for example represent a time comparison for various transmission speeds.

Kind Regards
Jürgen

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the suggestion.
