### ISSUE TITLE
Blocks From Template Assets

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3170]

**Comment by bainternet** [comment]
@NTuneMusic 

what?

**Comment by NTuneMusic** [comment]
Funny... I cannot find what I had written.

Anyway, I wanted to suggest the idea of having drag and drop blocks from the template elements in the Elementor template library. Instead of inserting the whole template, break up the elements into blocks, similar to what Mobirise has done with their bootstrap builder. You can see what I mean by looking at our current website, built with Mobirise, ntunemusic.com

Of course this would be for the Pro version only as an added bonus for purchasing the plugin, and they would need to have responsiveness built in.

Thank you guys for making this plugin. This plugin is the only reason that I have decided to move our website to WordPress. By making pre-made drag and drop blocks, you guys are sitting on a goldmine. As far as I can tell, the only competition you have is Divi 3.0.

Thank you.

**Comment by bainternet** [comment]
@NTuneMusic 

Thanks for the reply,  In that case, you can use our [global widgets](https://docs.elementor.com/article/100-global) which is exactly what you describe.

thanks for the feedback.
