### ISSUE TITLE
Default Schemes PHP Hook

### ISSUE THREAD

**Issue by joelbqz** [pojome/elementor#3175]
Hi guys, is it possible to set default schemes(typography, color and color picker) through a php hook?

Thanks!

**Comment by joelbqz** [comment]
UPDATE: I just found global typography, color and color picker for elementor are wp options which can be accessed with get_option()

get_option('elementor_scheme_typography')
get_option('elementor_scheme_color')
get_option('elementor_scheme_color_picker')

and edited with

update_option()

**Comment by xttn** [comment]
Hi
`get_option( 'elementor_scheme_color_picker' )`
or
`get_option('elementor_scheme_color-picker')`
??

**Comment by bainternet** [comment]
- `get_option('elementor_scheme_typography')` - Is for the default typography scheme.
- `get_option('elementor_scheme_color')` - Is for the defualt colors.
- `get_option('elementor_scheme_color-picker')` - Is for the color picker palette.
