### ISSUE TITLE
[Feature Request] YP Logo

### ISSUE THREAD

**Issue by GitStl** [pojome/elementor#3176]
I've got every icon I need but the YP logo. There are a ton of reviews attached to YP.com so the logo would be helpful. Other than that, great tool! A real time-saver!

**Comment by bainternet** [comment]
@GitStl 

We use FontAwesome for our icons and currently, it's not available there but there is an o[pen request](https://github.com/FortAwesome/Font-Awesome/issues/4648) for it.
