### ISSUE TITLE
Testimonial and Testimonial Carousel styling differences

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3177]
Why there are different options for styling/skins for a simple Testimonial and a Testimonial Carousel?
Is there a reason why simple Testimonial don't have Bubble skin?

To be honest the styling options for simple Testimonial are quite basic compared to Testimonial Carousel. Why is that, it's basicaly the same widget and the styles should be the same?

**Comment by bainternet** [comment]
@black-eye 

There is are major differences between a "Testimonial" widget to "Testimonial Carousel" widget, its far from being the "same widget" and if you feel that Testimonial widget styling are basic compared to the Testimonial carousel widget then you have the right feeling.

The Testimonial carousel is a Pro widget and our Pro widgets give you just that, more styling options and elements to what we already offer for free.

thanks for your feedback.
