### ISSUE TITLE
Restrict the backspace from causing page back function when inplace text edit

### ISSUE THREAD

**Issue by jezweb** [pojome/elementor#3178]
This happens sometimes accidentally. I've noticed it more in FireFox. If editing the text in place within a page and pressing backspace a bit too quickly or maybe the cursor is not quite in the text edit box then the browser will execute a 'back' command and it can result in losing changes.

Some discussion about this type of issue can be found here https://stackoverflow.com/questions/1495219/how-can-i-prevent-the-backspace-key-from-navigating-back

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


But for now, there are many good solutions in the page you linked that you can use.


Thanks for the feedback.
