### ISSUE TITLE
More options for leaving the page

### ISSUE THREAD

**Issue by jezweb** [pojome/elementor#3179]
There's no option to leave the editor without opening a new tab.
Perhaps if there were options such as:
    finish editing (goes to the page without editor enabled, in the same tab)
    view page (opens in new tab)
    page settings (opens page in wordpress dashboard)
    go to dashboard (goes to the landing page of wordpress dashboard)
All available from the green up arrow?

![screen shot 2018-01-15 at 4 43 41 pm](https://user-images.githubusercontent.com/13249054/34928720-766622fa-fa13-11e7-8286-ca517f7a111d.png)

I've gotten into the habit of using the browser back button but that hardly seems ideal.

**Comment by bainternet** [comment]
Putting all of these on the green "Update" button can cause accidental updates which we don't want.

You have the option to view previews, which will show current editor state, and if you actually update then its the same as show page.

and as for exiting to the dashboard you have that as well [ref](https://github.com/pojome/elementor/issues/3180#issuecomment-357979435)
