### ISSUE TITLE
Settings Cogwheel not acting the way it used to..

### ISSUE THREAD

**Issue by ianstudio** [pojome/elementor#3180]
Settings Cogwheel not acting the way it used to.. We used to be able to access the regular backend  (or preview) of a page/post from it.. but it seems you guys decided to remove this option ?!? And created a little eye icon for preview.. I'm taken aback by incremental changes in UI that at times feel like a step back.

**Comment by bainternet** [comment]
The Settings Cogwheel was miss used before and now is working as we feel it should, Clicking on the settings Icon shows the Settings panel. If you are looking to go back to the regular backend you are looking for the "Edit to Dashboard" button:

![e5fivqz](https://user-images.githubusercontent.com/660572/34994244-8a250630-fadb-11e7-943c-1b0f734ce827.png)
![2ry2myc](https://user-images.githubusercontent.com/660572/34994246-8bf00ffa-fadb-11e7-9d14-8fff59baba63.png)
