### ISSUE TITLE
Typography as a popup.. why? Oh why :/

### ISSUE THREAD

**Issue by ianstudio** [pojome/elementor#3181]
Hi,
why did you guys decide to turn the Typography (style) into a popup.. to me this is rather a retropedaling decision. I actually even chose Elementor rather than Beaver builder because it did not resort to popups.. I really don't get why you would do that.. popups suck.. seriously (I find foldable sections a much much better approach).

**Comment by drank** [comment]
Please check these negative reactions to the Typography pop-up as well:
- https://github.com/pojome/elementor/issues/3166 (last sentense)
- https://github.com/pojome/elementor/issues/3067#issuecomment-355536096
- https://github.com/pojome/elementor/issues/3067#issuecomment-355544878
- https://github.com/pojome/elementor/issues/3067#issuecomment-355566303
- https://github.com/pojome/elementor/issues/3067#issuecomment-355681460
- https://github.com/pojome/elementor/issues/3067#issuecomment-355718746
- https://github.com/pojome/elementor/issues/3067#issuecomment-356055191
- https://github.com/pojome/elementor/issues/3067#issuecomment-356105961

Still no reply from the Elementor team on this. I hope they take notice of these reports.

**Comment by black-eye** [comment]
Sadly, I have to agree with the comments above. On one hand I understand the intent behind this feature, it could make the the settings cleaner, on the other hand the final result is a bit chaotic and confusing.

The main problem is that there are 3 different functions on 2 buttons:
- Edit button serves as Open Popup button and Close Popup button (when clicked again)
- BUT: the very same Edit button serves also for Typography (or Text Shadow) ON button (but not for Typography OFF)
- Back to Default button is actually Typography OFF button, not Back to default

This is really confusing and far from intuitive. When I want to check the settings in the popup, I'm actually turning on the predefined settings (which is quite a problem especially for the Text Shadow settings).

**Comment by black-eye** [comment]
And one more issue here, to keep the picture complete: #3183

**Comment by dasigna** [comment]
regardless of issues, i personally appreciate the idea of the popup(s) - simply because in most cases it saves space in the panel and helps keeping better overview.

but i am not that satified too with the button(s) itself and the behaviour...
first thought was it would be simply far better if the pencil (if it has to be one...) was grey as long as no custom changes are made to typography settings, but it appears it changes to blue even if there are no changes made - simply by clicking it. if so, then it may change to blue as an _real_ indication of custom settings ->an only then the resetting button should appear - but better within the popup and not besides the pencil. those minor changes alone would serve a far better and more intuitive ui experience alone imo.

**Comment by maxwellhibbert** [comment]
I don't like the popups at all. I don't even like the main tabs of the interface. Elementor is currently an absolute click fest of an experience. Most designers have a large display (mine's 3440x1440), let me see everything without clicking all the time, the current interface gets in my way and gives me RSI.  I understand tabs and popups for small displays, but catering for big displays would make Elementor soo much better.

**Comment by drank** [comment]
Dear Elementor Team,

Why are you ignoring this thread? Could we have a constructive discussion on the topic? Pretending that this topic does not exist will not make it go away ;)

Best regards

**Comment by bainternet** [comment]
Thanks, everyone for your feedback.

We understand that not everyone will like each update, tweak or change we make which is perfectly fine, each individual is entitled to his own opinion and I can honestly say that we value these opinions and feedbacks.

We are always looking for ways to improve and currently testing all kinds of improvements to the panel, layout and overall workflow which we hope to release in the coming versions. One of them, for example, is global typography settings so you can set your defaults for all instances of the typography control unless updated.

And thanks again for all of your feedback.
