### ISSUE TITLE
Dependency with Typography

### ISSUE THREAD

**Issue by vrundakansara** [pojome/elementor#3182]
Hi,

The dependency parameter with Typography field does not seem to work. See this video.
When Display Type "Button" is selected I need to show the Button Typography, else keep it hidden.

Here is the code - http://bsf.io/he8td
http://bsf.io/sgy5r

Let me know if I am doing something wrong.

Regards,
Vrunda Kansara

**Comment by arielk** [comment]
Fix https://github.com/pojome/elementor/pull/3186/commits/32c5b14db91765caeffcccd0e58781fef021e70c

**Comment by vrundakansara** [comment]
Thank you for the quick fix, appreciate it! 👍
