### ISSUE TITLE
wp_enqueue_scripts at 999999 priority is a bad choice

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3188]
Hi, in your code I see plenty of add_action('wp_enqueue_scripts') setted with priority == 999999.

I think is a bad choice. I know there are elementor's own actions done for placing custom scripts after yours, but you really should not take 'all the space availble'. Any plugin should let the developer to override frontend css/scripts out of the box, using standard wordpress code.

I usually enqueue all my default scripts and styles with priority == 11 and it has benn always enough with eny plugin ever used more than 10 years of wordpress custom coding. Now suddenly a single plugin (Elementor), breaks this. So I guess it's Elementor, not me :)

Why 999999? It seems I cannot simply put my things at 1000000, probably 999999 is the max priority possible, but hey, why???

Please change it.

**Comment by bainternet** [comment]
@stratboy 

Thanks for your feedback,
We do this for one simple reason and its to be the very last action that runs in order to make sure that no 3rd party script/plugin breaks the editor.

Now if there is a specific need/issue please feel free to reopen and let us know what it is?

**Comment by stratboy** [comment]
Specific need/issue is already described above. You could achieve I guess the same result by putting 999998 instead of 999999 so the developer has one chance to get its things after yours and eventually do custom overrides without using your hooks. You should let the developer override your plugin, not take all the space available as if ti was the only and last plugin on the earth deserving this super imposition. Elementor it's the first plugin I see behaving like this in more than 10 years of wordpress development.
