### ISSUE TITLE
elementorFrontend.hooks doesn't exist

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3189]
Hi,

``` php
console.log(elementorFrontend); // writes code
console.log(elementorFrontend.hooks); // undefined
```
Why? My scripts are loaded after all the others, from a custom elementor plugin i made. So it should read all.

All your js hooks examples use elementorFrontend.hooks. 

Currently using v1.9.1, latest elementor pro, latest wp.

**Comment by bainternet** [comment]
Paste your code and well have a look.

**Comment by stratboy** [comment]
It was an error by me, had to call it from elementor/frontend/init:

```
$(window).on('elementor/frontend/init', function(){
  console.log(elementorFrontend.hooks); // ok
});
```

**Comment by mapsmarketing** [comment]
The developer docs do not mention having to wrap the `elementorFrontend` hooks with a `elementor/frontend/init` prior to it: https://developers.elementor.com/docs/hooks/js/

Furthermore, it also does not mention in docs that you need to have `in_footer` set to `true` when using `elementor-frontend` as a dependent when registering custom JS: https://developers.elementor.com/docs/widgets/widget-dependencies/

```
wp_register_script( 'widget-js', 'widget.js', [ 'elementor-frontend' ], '1.0', true );
```
