### ISSUE TITLE
'prefix_class' to the elementor-section instead of inner element

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3194]
Hi, widget add_control's 'prefix_class' option is very good, but I need the very same behavior applied tp  the classes of the container section (elementor-section). This is because then I'll use the classes as selectors for some custom js filters. I think it can be a relatively frequent requirement.

Is there a way to resemble that behaviour for the section instead of the inner element?

**Comment by bainternet** [comment]
@stratboy 

can you better explain the use case so we can understand what you are asking.

**Comment by stratboy** [comment]
I built a custom widget. This widget has several switchers. In frontend, if a switcher is on, the user sees an icon on a product tech spec box. So the number of icons are variable, not fixed, the icons indicate product features. On the theme I'm building, I will code serveral content filters based on the product features. To filter the product boxes, I will use classes based on the product features, so I need to add/remove those classes to the boxes when the icons/features are added/removed (switched on/off). 

Anyway, the thing is as above, it's exactly like what your own built-in 'prefix_class' does. The only problem is that it adds classes to the single widget, not to its containter (here again I mean .elementor-section). Not much usable, in my opinion, at least in my case. I need to show/hide each entire product box based on prod features, so i need classes on the .elementor-section (the box).

Again, it's simple, more than all the words above: how to resemble the 'prefix_class' behaviour so that it adds classes to the section instead of the widget?

Is there any way? Maybe some filter/action? Maybe some hidden option?

**Comment by bainternet** [comment]
Well there is no option to set container (section) classes from within a widget, but it feels like you are simply not using it correctly, in your widget render method you can print icons based on switch controls.

**Comment by stratboy** [comment]
Hey, that's not the problem. All the icon rendering is already setted up and running, both render() and live rendering (_content_template()). Also I really don't get your previous post, prefix_class has really nothing to do with my icon rendering.

I already know that prefix_class can't set the container.. I asked the following (copy paste):

how to resemble the 'prefix_class' behaviour so that it adds classes to the section instead of the widget? Is there any way? Maybe some filter/action? Maybe some hidden option?

Speaking php here.
