### ISSUE TITLE
Cusomizable "My Library" Items shortcodes

### ISSUE THREAD

**Issue by ianstudio** [pojome/elementor#3195]
Would be much better if the shortcodes of the Library Items could be:
- either customized
- or be applied the name given to the item..

Number ID's like this 
[elementor-template id="16706"] are not intuitive, especially when you have a whole bunch.. also categories or some sort of filing in there would be appreciated.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

But for now, you can try to add your own custom shortcode which will be a wrapper for the `elelemntor-template` shortcode and give alias names to your templates, ex:

```PHP
add_shortcode('my_template_names', function ( $atts ) {
	$names = [
		'name1' => '16706',
		'name2' => '16708',
                //ad as many as you want
	];
	if ( isset( $names[ $atts['name'] ] ) ) {
		return do_shortcode( '[elementor-template id="' . $names[ $atts['name'] ] . '"]' );
	}
	return '';
});
```

and you can use it like this:
`[my_template_names name="name1"]`

remember its an example and not really tested but should get you going
Thanks for the feedback and hope this helps.
