### ISSUE TITLE
[Feature Request] Custom Search Results page / Search results Widget

### ISSUE THREAD

**Issue by Ver3** [pojome/elementor#3196]
### How this might work

One the same settings page where you find maintenance mode / coming soon (and later on 'custom 404') You select an Elementor Library item of your choosing.

This library item is a page you made but at least includes the new "Search Results"-widget. Using this Widget you can set:

- Number of Columns to display
- Number of results to display
- Infinite scroll or pagination
- Query Type (All, Post, Cat, Tag, Page, etc..)
- Filter bar on/off
- Toggle "Show 20, 40, All" on/off
- All the styling options we are used to

### For a distant future (or built into Elmentor Themer)

Something like Relevanssi built in to improve results.

**Is this even possible?**

**Comment by bainternet** [comment]
@Ver3 

This is something we are working on, not all of what you suggest will be available but it's on our roadmap.

**Comment by Ver3** [comment]
@bainternet @arielk 

Thank you for considering these options. Can't wait to get testing. Also congratulations on the latest update (better forms). I'm happy to see you're not only adding but also improving. Well done!

**Comment by webig** [comment]
yess please! this is one of the biggest issues

**Comment by bainternet** [comment]
closing in favore of #3826 

thanks everyone.
