### ISSUE TITLE
How to use get_style_depends work for new custom_widget ?! Thanks

### ISSUE THREAD

**Issue by uxdesignit** [pojome/elementor#3198]
Hi,
I'm trying to use get_style_depends for new custom_widget, same with get_script_depends way:

       public function get_script_depends() {
		return [ 'unitegallery','ug-theme-tiles' ];
	}	 
	public function get_style_depends() {		
		return [ 'unite-gallery','ug-theme-default' ];
	}
But it does not work for get_style_depends() . Please share us the way to use get_style_depends for new custom_widget.

Thanks in Advances

**Comment by bainternet** [comment]
@uxdesignit 

That is the exact way it should work, but it will only load the style in the footer and not in the `head`.

Paste your code and we'll take a look.

**Comment by LucasBRamos** [comment]
I'm having the following error when using the get_style_depends

Fatal error: Can not override final method Elementor\Element_Base::get_style_depends()

If I remove in the plugin code the ```final``` word in the function definition, the style load normally

**Comment by LucasBRamos** [comment]
One thing I've noticed is that the styles are always loaded in the footer, along with the scripts.

Is it possible to load the styles in the header?

**Comment by bainternet** [comment]
@LucasBRamos 

You don't need to overwrite it, just set the `$depended_styles` property of your class.
and Like I said 

> but it will only load the style in the footer and not in the head.

So, no currently its not possible to load it in the head.

**Comment by shamimbdpro** [comment]
get_style_depends() method still loading style in footer. 

The main problem while loading default style in the footer.
# while the user generates dynamic style then it can't overwrite the default style. 

Is there has any way to load the get_style_depends style in the header?

**Comment by toan10921** [comment]
> get_style_depends() method still loading style in footer.
> 
> The main problem while loading default style in the footer.
> 
> # while the user generates dynamic style then it can't overwrite the default style.
> Is there has any way to load the get_style_depends style in the header?

> 

In my case, my custom widget,  i enqueue style in instead of use wp_register_style and using get_style_depends in construct, after that style will load in header and script will load after widget load:
 
  public function __construct($data = [], $args = null)
    {
        parent::__construct($data, $args);

        wp_register_script("script-$this->widget_name-handle", get_template_directory_uri() . '/t888core/elementor-widget/widget/' .  $this->widget_name . '/assets/js/' .  $this->widget_name . '.js', ['elementor-frontend'], '1.0.0', true);
        // enqueue style in header
        wp_enqueue_style("style-$this->widget_name-handle", get_template_directory_uri() . '/t888core/elementor-widget/widget/' .  $this->widget_name . '/assets/css/' .  $this->widget_name . '.css');
    }
