### ISSUE TITLE
Trigger a Slide from an external link

### ISSUE THREAD

**Issue by lordloadalot** [pojome/elementor#3203]

**Comment by lordloadalot** [comment]
Hi everyone,

is it possible ( i mean by coding :) )to trigger a single slide of the slider module by an external link ( lets say a textlink )
We want to achieve something like this:
https://www.pirenko-themes.com/hook/white/  ( a navigation thru a slider with numbers sticky to the right side of the screen )

we want to use only Elmentor items and no ohter plugins or elements. A bit of code perhaps.
![bildschirmfoto 2018-01-16 um 14 43 54](https://user-images.githubusercontent.com/29510055/34992001-ee030cfc-facb-11e7-8565-717e84272496.png)

**Comment by bainternet** [comment]
You can do that using the Slick slider (which is the js library we use for slides) API ex:

```JAVASCRIPT
var slider = jQuery('.elementor-slides').slick('getSlick');
slider.slickGoTo(2);
```
