### ISSUE TITLE
Disable Elementor on particular apply_filters the_content

### ISSUE THREAD

**Issue by redpik** [pojome/elementor#3205]
Hi guys, Hi have a problem with few plugins: they have apply_filters the_content inside. Elementor is NOT activated on these plugins, but it's replace plugin contents with the last post content!
Can I disable Elementor on particular pages, plugins? For example with filters or global variables...?
Can you help me please? Thanx

**Comment by bainternet** [comment]
Can you provide an example of specific plugins?

**Comment by norewp** [comment]
@bainternet here's 1 such plugin: https://wordpress.org/plugins/hooked-editable-content/ - On normal pages/posts i.e those edited via the default editor the hooked content is applied correctly.

However, on an Elementor edited page the hooked content is replaced by Elementor content and thus resulting double render. This may well be an issue with the linked plugin and if so a confirmation together with suggestions on how it can best be avoided would be great :)

**Comment by friveraus** [comment]
I have installed a plug-in WP Customer Area, and I am having issues with the plug-in not working.  I contacted the developer and I was told the following;

> Could you first contact this plugin author to ask them how the plugin can be deactivated on certain pages? You're not using the editor but the editor is probably affecting the the_content filter and affect the render of the page even if you're not using it. It looks like a problem on your page. This plugin should not affect the content if not used on certain pages.
> 
Thanks for your attention,
Felix

**Comment by bainternet** [comment]
@friveraus 

if the page is not using Elementor then Elementor does nothing to `the_content` filter.

Elementor Uses the `the_content` filter to "Inject" itself and I don't see that changing anytime soon.
