### ISSUE TITLE
Improve efficience of render by approx 15%

### ISSUE THREAD

**Issue by milsorm** [pojome/elementor#3207]
After profiling Elementor through Tideways I found that a lot of calls go through `includes/base/controls-stack.php` function `get_active_controls()` with pretty ugly `array_reduce`.

I suggest following patch to change to `array_filter()` which helps A LOT (approx 15% in my case).

```diff
diff -Naur elementor.orig/includes/base/controls-stack.php elementor/includes/base/controls-stack.php
--- elementor.orig/includes/base/controls-stack.php     2018-01-16 20:21:05.182005728 +0100
+++ elementor/includes/base/controls-stack.php  2018-01-16 20:22:02.520880300 +0100
@@ -274,23 +274,13 @@
         * @return array Active controls.
         */
        public function get_active_controls() {
-               $controls = $this->get_controls();
-
                $settings = $this->get_controls_settings();

-               $active_controls = array_reduce(
-                       array_keys( $controls ), function( $active_controls, $control_key ) use ( $controls, $settings ) {
-                               $control = $controls[ $control_key ];
-
-                               if ( $this->is_control_visible( $control, $settings ) ) {
-                                       $active_controls[ $control_key ] = $control;
-                               }
-
-                               return $active_controls;
-                       }, []
+               return array_filter(
+                       $this->get_controls(),
+                       function ( $control, $control_key ) use ( $settings ) { return $this->is_control_visible( $control, $settings ); },
+                       ARRAY_FILTER_USE_BOTH
                );
-
-               return $active_controls;
        }
```

**Comment by bainternet** [comment]
@milsorm 

thanks we will look in to it, 

note: Foreach will actually work much faster in this case:

```PHP

		$active_controls = [];
		foreach ( $controls as $control_key => $control ) {
			if ( $this->is_control_visible( $control, $settings ) ) {
				$active_controls[ $control_key ] = $control;
			}
		}

**Comment by milsorm** [comment]
Your foreach version improve A LOT visually without any tests :-) So I am measure it during next profiling session, but seems REALLY GOOD.

Please include it into main tree and if you can improve is_control_visible which is the most called function in Elementor, I would be a really happy man :-)

Thanks.

**Comment by bainternet** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

**Comment by milsorm** [comment]
I have written that patch but the issue is that it is combined with all things necessary to use Elementor outside the US/UK environment :-) And this changes was rejected by team. So every update of Elementor means for me to go and patch all installations (otherwise it stop works due to CSS generation bug in Elementor in international environment) and I simply combined these performance patches with necessary internationalization patches together (because I want to patch only once the whole installation).

It is pity and complicated but that is how Elementor team deals with non-US/UK environment :-(

**Comment by lf-jeremy** [comment]
I'm seeing a massive speed boost by using the [foreach fix](https://github.com/pojome/elementor/issues/3207#issuecomment-358570493) above. This is a killer optimization!
