### ISSUE TITLE
Support for Czech version of WordPress

### ISSUE THREAD

**Issue by milsorm** [pojome/elementor#3208]
Elementor expect using decimal point `0.5` for every measurement unit, typically for `em` expressions. But in Czech locale we are using decimal comma `0,5`. What is pity, Elementor is not able to produce correct CSS because this decimal comma is printed to CSS files. But in CSS files only original US locale can be use (decimal point).

I am always applying this patch for making Elementor working in Czech environment. Nothing special, can be solved better through some locale functions, but works. It is really disturbing apply this patch to every site during every update of Elementor.

```diff
diff -Naur elementor.orig/includes/controls/base-data.php elementor/includes/controls/base-data.php
--- elementor.orig/includes/controls/base-data.php      2018-01-16 20:21:05.183005743 +0100
+++ elementor/includes/controls/base-data.php   2018-01-16 20:21:16.333174935 +0100
@@ -70,7 +70,15 @@
         * @return string Control style value.
         */
        public function get_style_value( $css_property, $control_value ) {
-               return $control_value;
+                $res = $control_value;
+
+               // In some locale decimal comma is used instead of decimal point, but that cannot be used in CSS files
+               // e.g. Czech, Slovak, Spanish
+                if ( is_numeric( $res ) )
+                        $res = str_replace( ',', '.', $res );
+
+                return $res;
+
        }

        /**
diff -Naur elementor.orig/includes/controls/base-multiple.php elementor/includes/controls/base-multiple.php
--- elementor.orig/includes/controls/base-multiple.php  2018-01-16 20:21:05.183005743 +0100
+++ elementor/includes/controls/base-multiple.php       2018-01-16 20:21:16.334174950 +0100
@@ -82,6 +82,13 @@
         * @return array Control style value.
         */
        public function get_style_value( $css_property, $control_value ) {
-               return $control_value[ $css_property ];
+                $res = $control_value[ $css_property ];
+
+               // In some locale decimal comma is used instead of decimal point, but that cannot be used in CSS files
+               // e.g. Czech, Slovak, Spanish
+                if ( is_numeric( $res ) )
+                        $res = str_replace( ',', '.', $res );
+
+                return $res;
        }
```

**Comment by bainternet** [comment]
This is a very server specific case and we don't want to add conditional checks by default to methods like `get_style_value` which will have an impact on performance.

maybe you can set the PHP local before and remove it after using either 
`setlocale(LC_NUMERIC, 'us_EN');` or `setlocale(LC_ALL, 'cs_CZ');`

but it's not something we would put in the core of Elementor.

thanks for the suggestion.

**Comment by milsorm** [comment]
So you have to told me that Elementor cannot be used in Czech Republic? Because I have setlocale to cs_CZ globally for collating etc. How can I involve that every output of print in Elementor will do setlocale to us_EN and revert back?

Patching every time is ugly. And CSS cannot work with decimal commas. And I cannot change rule of Czech language for the whole nation :(

Can you make it changeable some way like action/overwritable function/etc.?

**Comment by edemir206** [comment]
I have solved the problem this way:

add the following line to wp-config.php:

setlocale(LC_NUMERIC, 'en_US.UTF-8');

**Comment by milsorm** [comment]
This can help if I can do this only around Elementor generator. Because inside WP we are displaying numbers from custom attributes and inputing numbers to ACF fields in forms where end users use local conventions for numbers.

But it is good idea to try format number according to US specification instead of replacing commas. I'll try to prepare better patch using specified. 

Thanks.
