### ISSUE TITLE
Suggestion for the forms widget after release of E Pro 1.13

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#3209]
1. Add column width 10%, 13,3%, 15% and 16,6%
2. Add type "time stamp" - the combination of date and time - if possible.

**Comment by parfilov** [comment]
Password field placeholder missing.

**Comment by parfilov** [comment]
Time field 12/24 hours toggle please. In Europe and Russian language area countries 24 hours format applies.

**Comment by parfilov** [comment]
Date field. Please make Months and Days of week translatable or inherit from native HTML + browser language.

**Comment by bainternet** [comment]
@parfilov 

- Password field placeholder is updated in the next version.
- As for time and date fields, they are both using the great flatpickr library which means you can get much more out of these fields by using the [JavaScript API](https://chmln.github.io/flatpickr/instance-methods-properties-elements/), including [localization](https://chmln.github.io/flatpickr/localization/#using-modules)

@HelmutGoebel 
We will look at adding additional widths. as for the timestamp you can easily implement that again via the flatpickr API.

thanks for the suggestions.

**Comment by parfilov** [comment]
@bainternet 

> Do I need to know how to code to use Elementor?
> Absolutely not! Elementor is a live frontend page builder, that lets you reach a high end design with no need to write even a line of code or CSS.

**Comment by srcek** [comment]
I'd also like the date picker to inherit the native language of the browser or WordPress language. Or at list be possible to select or translate from the builder interface. Now I solved that issues with some code but that's not really practical to apply to every page i use the date field on. Thank you.

**Comment by bainternet** [comment]
[**@parfilov**](https://github.com/parfilov) commented on [Jan 21, 2018, 11:25 AM GMT+2](https://github.com/pojome/elementor/issues/3209#issuecomment-359234940 "2018-01-21T09:25:22Z - Replied by Github Reply Comments"):
> @bainternet 
> 
> > **Do I need to know how to code to use Elementor?**
> > Absolutely not! Elementor is a live frontend page builder, that lets you reach a high end design with no need to write even a line of code or CSS.

that is still true, if you want more than that, like custom settings on a datepicker javascript library then yea, you would nned to entry a few lines of code.


[**@srcek**](https://github.com/srcek) commented on [Jul 7, 2018, 11:09 AM GMT+3](https://github.com/pojome/elementor/issues/3209#issuecomment-403197750 "2018-07-07T08:09:36Z - Replied by Github Reply Comments"):
> I'd also like the date picker to inherit the native language of the browser or WordPress language. Or at least be possible to select or translate from the builder interface. Now I solved that issues with some code but that's not really practical to apply to every page i use the date field on. Thank you.

Not something that the [flatpickr](https://chmln.github.io/flatpickr/localization/#using-modules) supports. You can however, use the native HTML5 date picker which should inherit the browser language.

thanks.
