### ISSUE TITLE
Elementor's template library doesn't sync when I save a template

### ISSUE THREAD

**Issue by AbanobAAkram** [pojome/elementor#3210]
Hey,

I'm trying to buld my own custom widget using Elementor, my widget gets the Elementor's saved templates and show them as carousel items, so, I created a select2 control field with the templates saved, but If I tried to save the current page I'm editing as a template, I can't find it in the select box unless I refresh the page, is there anyway to use update control for this select field without refreshing the whole page ?

Thanks,
Abanob

**Comment by bainternet** [comment]
Currently, this feature is not supported in the Select2 control, but we will look into it in the future if we see a large demand for it.

For now, the only way to do that would be to extend the Select2 control to fetch the options data via AJAX.

If you have Elementor Pro then take a look at the query-control,js to see how its done there.


Thanks for the feedback.
