### ISSUE TITLE
[Feature Request] Integration with NextGen Galllery

### ISSUE THREAD

**Issue by titchpitch** [pojome/elementor#3211]
Pro user here, would love to see an integration with next gen gallery since its the most popular gallery tool used for WP sites. 

Specifically requesting a way to utilise the next gen tags with ajax filtering within next gen.

Thanks

**Comment by bainternet** [comment]
@titchpitch 

can you elaborate?

**Comment by titchpitch** [comment]
Hi - some more info.

So when you create a gallery in NextGen - next to each image you can add 'tags' to each image. These tags are a custom taxonomy. You can then display galleries made up on images matching these tags. It would be fantastic if the displaying of this taxonomy could be integrated into an Elementor widget. 

Thanks

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
