### ISSUE TITLE
How to detect page/post was built by Elementor?

### ISSUE THREAD

**Issue by xttn** [pojome/elementor#3212]
Hi, like Visual Composer, i have:
`$visual_composer = get_post_meta( get_the_ID(), '_wpb_vc_js_status', true );`

Where i can find it? Thank

**Comment by bainternet** [comment]
Two way you can check:

```PHP
if ( Elementor\Plugin::instance()->db->is_built_with_elementor( $post_id ) ) {
    //page is build with elementor
}

// or by checking directly
$elementor_page = get_post_meta( $post_id, '_elementor_edit_mode', true );
if ( ! ! $elementor_page ) {
    //page is build with elementor
}

**Comment by bcavenagh** [comment]
Quick question about your code @bainternet. What is the purpose of the double exclamations in the second if statement? Would it not work the same if you just didn't include exclamations?

**Comment by masoud202** [comment]
Is this worked for new version of elementor?
i want check page and if use elementor enqueue some css , if not use elementor dont enqueue
