### ISSUE TITLE
Border/Margin values should restore

### ISSUE THREAD

**Issue by vrundakansara** [pojome/elementor#3213]
Hey,

The values for Border/Margin (DIMENSION) does not retain when I change from PX to % or vice versa.

For example, I set it to 20px, and then switch to % and then back to PX. I expect it to remain 20 that I originally set.

Here is a small video explaining the scenario - http://bsf.io/e81mf

Probably this needs a small enhancement.

Regards,
Vrunda Kansara

**Comment by bainternet** [comment]
@vrundakansara 

We are aware of it and its simply the way that the dimension controls work, mainly because each Unit has its own range.

That is why we have History and the all mighty `Crtl + Z`.

**Comment by vrundakansara** [comment]
Alright!

Fair enough. Thank you! 👍
