### ISSUE TITLE
Show Title on Media Carousel Lightbox

### ISSUE THREAD

**Issue by russglt** [pojome/elementor#3214]
The media carousel is a really good widget for showcasing videos however, when a video starts playing and we go into lightbox mode there is no indication as to what video is actually playing as you skip though each video in turn. I'd like to see a title for each video somewhere - maybe underneath. Quite happy for this to be the title, description or caption of the cover image for the video used in the carousel.

**Comment by bainternet** [comment]
I merged this issue with  #2502, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
