### ISSUE TITLE
Minor mistake in doc.

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#3215]
I found a minor mistake in doc.
https://github.com/pojome/elementor/blob/master/docs/content/controls/_media.md

`$image = $this->get_settings( 'image' );
echo '<img src="' . $image[url] . '">';
// Get image by id
echo wp_get_attachment_image( $image['id'], 'thumbnail' );`

This should be 

`
echo '<img src="' . $image['url'] . '">';
`

Thank you for your great plugin!

**Comment by bainternet** [comment]
@pulla 


thanks, Ill fix it.
