### ISSUE TITLE
Rotate in view in Responsive Mode - Feature Resquest

### ISSUE THREAD

**Issue by davidmcc3** [pojome/elementor#3219]
It would be useful to have the Mobile Responsive Mode view rotatable or width-customisable.

This is because Mobiles in landscape are less wide than the Tablet setting of 768px.

Perhaps this doesn't lead to a new Media setting, but atleast we can see and adjust for the Mobile Landscape width.

Or maybe we can have a new Media setting at, say, 640px

This is not an issue for Tablets in Landscape.

Thanks, David

**Comment by bainternet** [comment]
I merged this issue with  #2043, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by davidmcc3** [comment]
Hi Raz
 
Apologies … I missed the other thread when I was looking.
 
Regards
David
David McCarthy
WORD-right
Copywriting, Communications, Websites
Tel: 02392 503 742 | Email: david@word-right.co.uk
http://word-right.co.uk | http://web-right.co.uk | Twitter: @WEBright 
If you absolutely must print this email, please make sure your printer is set to ‘Draft’ mode.  It's kinder to the environment and will also save you money!
WORD-right is a trading name of IDEAS-right Ltd | Company Reg. No. 5934818 | 5 Kensington Road | Gosport | PO12 1QY
