### ISSUE TITLE
When hit "create new page", redirect to settings page where TITLE can be changed

### ISSUE THREAD

**Issue by elasticeye** [pojome/elementor#3220]
## Description

When you hit "Create new page" from Dashboard, it should be redirected to settings page in builder where we can edit page name/slug. Almost all will edit this name anyway, so why not just do it at once.

**Comment by bainternet** [comment]
@elasticeye 

Currently, It's only a single click away and we find that our users either define the Title via the native edit screen or prefer to start with the content.

Now that being said, it is something to think about.

thanks for the sugestion.
