### ISSUE TITLE
not an issue but one more suggestion towards limiting editing possibilities

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#3221]
mentioned somewhere before but have to point this out another time...

just an hour ago i've had a little struggle with words with a customer who completely messed up two pages on his site just by wanting to edit some text. obviously out of fear to give a call for that and merely out of panic he did things more and more worse!
luckily thanks to saved pages as templates, elementors (new) saving capabilities and backup this was relatively easy to manage though.

and even if one might call this client stupid, the basic 'problem' is the rising possibilities of elementor that might overwhelm somebody whos not regulary working with them.
so i want to suppose the following improvements - generally called 'user capabilities'.

1. only be able to edit contents of widgets (text, images, etc.). often most sufficient for users.
2. abiltity to rearrange widgets, sections and columms in adition as well as editing them.
3. be able to edit page settings or not.
4. show only used or (by settings) enabled widgets/opitons in editor panel. (severely desired eighter way)

if we could then assign these capabilities to editor roles or even specific users it would be really a great help and improvement!

this is only some rough draft of such possibilities and no final thought! but some expansion into this direction is highly appreciated.
NOTE: in my opinion this should NOT end up in enable/disable every possible object as this would inevitably involve too much confusion and possible amount of work.
just a handful of capability roles that could be assigned to user roles or user would be really great.

thanks for considering in advance.

**Comment by bainternet** [comment]
@dasigna 

We already have something like that (Role Manager) in our roadmap.

thanks for the suggestions.

**Comment by ppweb** [comment]
How far away is it in the roadmap?

**Comment by joshallen73** [comment]
@bainternet is there somewhere we can see the official roadmap?

**Comment by bainternet** [comment]
@joshallen73 

No, not currently.

**Comment by bainternet** [comment]
ref: #1314

**Comment by Reubenlee** [comment]
@bainternet 

Hey! just wondering if this feature is out. Currently im also facing the same issue where i give a permission to my client ( Role =  Author) to edit a certain page from his side, originally wanted him to just edit stuffs like text in a widget/ change some photos. Unfortunately he messed the whole page up. Apparently even though elementor developed a function call the Role Manager, other role still can edit the 'layout' of the widget.  my client was able to change my nav menu layout in the end... 


Is there any way to limit the user to only edit the text/picture in the module? and do not allow them to change the layout of other things? 

Thanks in advance!
Reuben

**Comment by 79ho3ein** [comment]
hi @bainternet , Do you have a plan to make the official elementor roadmap visible to users in the future? Like bricks builder?
https://bricksbuilder.io/roadmap/

I love elementor and do not work with bricks, but it is a smart decision to let your users know about the roadmap. In fact a new section for the roadmap, on the official elementor website.

thank you!
