### ISSUE TITLE
Feature renquest: add ability to set where 'prefix_class' is applied

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3222]
Widget->add_control() features an interesting option 'prefix_class'. I think it would be even more useful if there where another option to set where the class should be added. Particulartly, the ability to add it to the parent section instead of the widget's element itself (or maybe both).

**Comment by bainternet** [comment]
Like I answered already in #3194. It's not possible.

**Comment by stratboy** [comment]
In this case it's a feature request.
