### ISSUE TITLE
Post widget colums not working

### ISSUE THREAD

**Issue by tamil774** [pojome/elementor#3223]
Version 1.9.2

In post widget i choose card view post..
Then column = 4
No of post = 4
In live visual it shows correct..

But if i visit that page.. only 2 column.. i think its bug..https://youtu.be/Uf6m46d2_dw

**Comment by bainternet** [comment]
@tamil774 

It's more of a feature than a bug called responsive.

Seems like your viewport is too small, in that case, you have to set 4 columns manually for all 3 device types: Desktop Tablets and Mobile.

If you still get a wrong layout after you set that, then please feel free to reopen.

**Comment by tamil774** [comment]
Its working thq so much
