### ISSUE TITLE
localhost Elementor Pro won't auto update

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#3224]
I have Elementor Pro installed on a single site install of WordPress on WAMP Server. Whenever I try to update it from within Installed plugins I get "Update Failed: Could not copy file. elementor-pro/assets/lib/smartmenus/jquery.smartmenus.min.js" - so I have to visit the Elementor site and download the plugin and install locally. Any ideas?

**Comment by bainternet** [comment]
@nickdgreen 

Can you provide more details:
 - server environment? (xamp,mamp,wamp,local)?
 - OS? (windows,macos,linux)? and version ?

**Comment by norewp** [comment]
@nickdgreen - try this plugin: https://wordpress.org/plugins/fix-windows-compatibility/

Mine never used to work till I installed that plugin when it was mentioned in the FB group.

**Comment by nickdgreen** [comment]
Zulfikar,

Yes, got that plugin - Lyle gave me the info.

 

Best Regards

Nick

 


Legal Disclaimer:

Internet communications are not secure and therefore Websites Designed 4U (a
business name of ISD Consultants Ltd.) does not accept legal responsibility
for the contents of this message. This email is confidential and solely for
the use of the intended recipient(s). If you receive this email by mistake,
please advise the sender directly, then immediately destroy this email.
Websites Designed 4U maintains security processes designed to eliminate
viruses, however, the Company is not responsible for viruses which may be
contained in the email or any attachment(s).
