### ISSUE TITLE
Feature request - Price Tables - Symmetry

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#3226]
The price Table Feature is great; however, some introduction of symmetry is desirable, depending on the number of fields chosen if many tables are to be placed in line with each other.
Screenshot attached.
Kindly consider it.
Thx.
<img width="967" alt="screen shot 2018-01-18 at 01 24 25" src="https://user-images.githubusercontent.com/33909786/35064028-b6a29d76-fbee-11e7-85d6-bd451b6c1a92.png">

**Comment by bainternet** [comment]
@Dentalicious 

can you elaborate?

**Comment by Dentalicious** [comment]
i.e. The table on the right is a derivative of the table on the left, however, symmetry is not achievable no matter which options are selected or deselected. (the bottom of the tables on the right are shorter than the table on the left, it looks odd on a page as a whole).

So what would be ideal is that there should be some overarching symmetry that should be set as constraint i.e. if all options then 100%, then what u have like for form fields, 33:33:33 or 40:40:20 or 50:50 and the likes.

So next to a 100% table, a 50:50 split-table would be possible or a 33:33:33 and the bottom and top of all of them would look in one line.

This only applies when multiple tables have to be used together to form a coherent pricing guide, not sure how many people would want to use them, but that be a nice delicate detail.

Thx.

**Comment by bainternet** [comment]
@Dentalicious 

It's a tricky one since each one is a widget if its own and not aware of other tables you have added, also it's not something I see happening anytime soon, but we do have the margin/padding controls there exactly for these cases.

thanks for the suggestions.
