### ISSUE TITLE
Font Awesome Pro

### ISSUE THREAD

**Issue by ericft** [pojome/elementor#3227]
Hi, It would be very nice to have the option to replace font awesome with the pro version with the activation licence or the option de disable Font Awesome so I can load the Pro version without having to load the standard version.

Thanks!

**Comment by bainternet** [comment]
@ericft 

Its a tricky one since both the editor and some widgets use and are depended on Font Awesome.

But we do have a plan to upgrade to Font Awesome 5 somewhere on our roadmap.

thanks for the suggestion.

**Comment by hbodell** [comment]
Why was this closed? There still isn't a way to add Font Awesome Pro.

**Comment by steve231293** [comment]
Hi there, I need convert to Font Awesome Pro too, any help?

**Comment by stevewoody82** [comment]
+1 for this

**Comment by stevewoody82** [comment]
The best solution for this at the moment - whilst not ideal is to use this 

https://anvilzephyr.com/add-fontawesome-pro-wordpress/

**Comment by jeffdodge** [comment]
I just purchased Font Awesome Pro as well, I would really like to see this implemented.
