### ISSUE TITLE
[Feature Request] Pro: Nav Menu Widget - more customization options

### ISSUE THREAD

**Issue by drank** [pojome/elementor#3228]
The current Nav Menu Widget is good but is still not great. For example it lacks options to allow menus like the one below:
![image](https://user-images.githubusercontent.com/1393766/35067478-b37f5b1e-fbdc-11e7-809b-384737cc73dc.png)

What we still need:
- More pointer options - left bar, right bar and so on - to fit to vertical menus
- Background for the main menu items
- Ability to separate menu items (this is possible in the Dropdown styling but not in the main menu)
- Borders for the main menu items

**Comment by bainternet** [comment]
I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, and add relevant information.

This is just the first phase. More customization is coming!

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
