### ISSUE TITLE
Elementor\Widget_Blogs

### ISSUE THREAD

**Issue by thefloppy1** [pojome/elementor#3229]
The website I manage www.auburnbowls.org.au  went down today displaying this error, after an update of Elementor Pro.

Elementor\Widget_Blogs::add_control: Cannot add a control outside of a section (use `start_controls_section`).

I have currently disabled all Elementor plugins, the page still has that error.
cheers

**Comment by bainternet** [comment]
@thefloppy1 

Widget_Blogs is not a class of Elementor or Elementor pro so it's probably a 3rd party plugin you have. please try to contact them for support.
