### ISSUE TITLE
Column overlay and section overlay doesn't seem to work since version  0.6 

### ISSUE THREAD

**Issue by KeithBussard** [pojome/elementor#323]
I've updated Elementor on two sites to version 0.6 today. On both sites (different themes) the column background overlay option and the section background overlay options seems to have some problems. Both on existing and on new pages the overlay doesn't seem to apply.

**Comment by KingYes** [comment]
Fixed by https://github.com/pojome/elementor/commit/285097a712af868ad5fadcc70b6c4198dcdbe3ed

Thanks!
