### ISSUE TITLE
Export template not end the JSON file correctly

### ISSUE THREAD

**Issue by descuderosanchez** [pojome/elementor#3230]
## Description

340/5000
When I try to export the Elementor template, it does not finish the keys correctly. Validating the file in any JSON validation tool gives parsing error.

This is an example of an exposed file:
{"version":"0.4","title":"breadcrumb","type":"section","content":[{"id":"b9cd170","settings":{"custom_height":{"unit":"px","size":10},"margin":{"unit":"px","top":"0","right":0,"bottom":"0","left":0,"isLinked":true},"padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true}},"elements":[{"id":"405b9b0c","settings":{"_column_size":100,"margin":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true},"padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true}},"elements":[{"id":"7a112eb1","settings":{"shortcode":"[wpseo_breadcrumb]","_margin":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true},"_padding":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true}},"elements":[],"isInner":false,"widgetType":"shortcode","elType":"widget"}],"isInner":false,"elType":"column"}],"isInner":false,"elType":"section"}

At apache error not could see any error, 

## Steps to reproduce
In My library, press Export Template.

## Environment
I have the latest version of the plugin that was released yesterday:
Elementor: Version 1.9.2
Elementor PRO: Version 1.13.1

**Comment by bainternet** [comment]
@descuderosanchez 

We can't replicate,

Please contact our support and see if they can help you.
support@elementor.com
