### ISSUE TITLE
MailChimp API Key isn't saving

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#3231]
I've applied a valid MailChimp API Key in **Elementor > Settings > Integrations**, clicked **Validate API Key**, which successfully validates, but when I return to the page it's blank. 

When editing in Elementor, if I leave the **API Key** to default in the MailChimp widget no lists are selectable. I have to choose **Custom** then paste in the same **API Key**.

![image](https://user-images.githubusercontent.com/1729832/35092234-de897a90-fc92-11e7-97b6-1553d05c73e6.png)

**Comment by bainternet** [comment]
You have to save it at the bottom of the  Elementor > Settings > Integrations page.

Validate only validates, it doesn't save it.

**Comment by JoelEadeDesign** [comment]
Thanks for the instructions. Perhaps adding a "Save" button next to each validation button would be better UX, seeing as the page is fairly long with all the integration options.
