### ISSUE TITLE
"Subscriber Already Exists Message" doesn't appear for existing subscriber

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#3232]
I've found when testing a Form that uses the MailChimp setting, that I'm able to use an email address that's already subscribed to the list. The **Subscriber Already Exists Message** doesn't appear.

A client reported this issue after receiving numerous emails. They have a large list of subscribers, and are doing pre-sales for an event. Some people don't recall that they're already subscribed so they're re-subscribing but not receiving any messages from the website that they're already subscribed, and MailChimp doesn't send a confirmation email to already subscribed users.

**Comment by bainternet** [comment]
@JoelEadeDesign 

We actually removed it intentionally, mainly for two reasons:
 - Prevent data leakage, since anyway can enter any email address if I know your email address I can find out to what lists you are subscribed to.
 - Not all Integration providers work and respond the same to a case where a user is already registered/subscribed.


But thanks for the feedback.

**Comment by JoelEadeDesign** [comment]
Thanks for the clarification. I can understand the reasoning. I've altered the confirmation message to note that if they don't receive a confirmation (double opt-in) message then they're probably already subscribed.

Could you remove the "Subscriber Already Exists Message" to avoid confusion? Seems redundant.

**Comment by bainternet** [comment]
@JoelEadeDesign 

Just removed it :)

**Comment by haynzz** [comment]
I was just about to create a ticket about this issue. 
We are using Elementor Pro Forms. For me it's a little bit undesirable that potential subscribers (not having done double-opt-in yet) they just see a red x without a message.
Can you confirm that this is how it's supposed to work right now?
I understand the security concern and it's noble. Still, I'd like to propose a solution where the server does not return an error to the form but just pretends everything worked.

**Comment by Pavithra-Rajulu** [comment]
@JoelEadeDesign , can I know where did you altered your confirmation message (to note that if they don't receive a confirmation (double opt-in) message then they're probably already subscribed.)

**Comment by JoelEadeDesign** [comment]
Sorry, @Pavithra-Rajulu. I can't recall the website I used this on. From what I can recall I may have just updated the _Custom Messages_ but I'm hazy on the details.
