### ISSUE TITLE
Padding Of Icons In Icon List

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3233]
## Description

There needs to be a way to add padding to the icons in the Icons List widget. Right now, the icons are touching the text next to them. Add the ability to add padding between the icons and the text please.

**Comment by ramiy** [comment]
@NTuneMusic Use the **Text Indent** to add space between the icon and the text.

![icon-list-text-indent](https://user-images.githubusercontent.com/576623/35156477-9b18ac16-fd39-11e7-855f-aaca57443431.png)

**Comment by NTuneMusic** [comment]
Great! Thank you.
