### ISSUE TITLE
[Form] Phone field masked input

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#3236]
Hello! It would be nice to do input mask for the phone field.

**Comment by bainternet** [comment]
@parfilov 

We are thinking about it. but for now, we'd like to keep the forms simple and generic without having to use too many 3rd party libraries.

thanks for the suggestion.

**Comment by carlosnpz** [comment]
I need this too. :/

**Comment by hitdarlan** [comment]
I need this too. [2]

**Comment by faacsousa** [comment]
I need this too. [3]

**Comment by SlavaChurinov** [comment]
When already?

**Comment by parfilov** [comment]
@SlavaChurinov never. Read upper.

**Comment by SlavaChurinov** [comment]
@parfilov can't see anything about "never", only "for now" and it was 2 years ago.

**Comment by parfilov** [comment]
@SlavaChurinov see the 2nd post

**Comment by SlavaChurinov** [comment]
@parfilov I saw it, and there is no mentioning of "never" thing. They just keep it simple for now, because of the reasons they've mentioned. So I don't see where you got that "never" part

**Comment by parfilov** [comment]
@SlavaChurinov optimist

**Comment by eduardovillao** [comment]
Use this plugin: https://wordpress.org/plugins/form-masks-for-elementor/

Form Masks for Elementor.
