### ISSUE TITLE
update_responsive_control is not updating values in Style section (Advanced tab) of a widget

### ISSUE THREAD

**Issue by hogash** [pojome/elementor#3237]
#### Description

Hey! I created a new widget and by default i wanted the Padding Top & Bottom to be 10px . I tried using `update_responsive_control` but with no luck. 

#### Steps to reproduce

```
protected function _register_controls() {

	// .. other options

	// trying to update the _padding field
	$this->update_responsive_control(
		'_padding',
		[
			'default' => [
				'top' => 10,
				'right' => 0,
				'bottom' => 10,
				'left' => 0,
				'unit' => 'px',
			],
		]
	);
}
```

I also tried hooking to `elementor/element/before_section_end` but these fields seem to belong to the 'common' widget and i can't find any way of relating the common widget with my newly added widget.

Any tips? Thanks!

**Comment by bainternet** [comment]
@hogash 

There is no way to update "Common" widget controls,
In cases like this, when we need to set defaults we define the defaults in CSS. try that.
