### ISSUE TITLE
Scroll speed/Paralax on any element

### ISSUE THREAD

**Issue by webig** [pojome/elementor#3238]
Hi,
I just got the idea to post my suggestion here. I always have to style my own css for doing this, and I think it could add many new perfect design possibilities just by adding Paralax/scroll speed to any element/background. As it is now with section background images where this is simply possible. It would be great feature to have :) 

But still, you guys are doing great job ;) 

Regards
J.Dvorsky.

**Comment by NTuneMusic** [comment]
I really like this idea too.

**Comment by bainternet** [comment]
@webig 

Care to provide an example?

**Comment by joshallen73** [comment]
Look at Jet Elements Parallax Option - it adds parallax to any items up to 10 i thing to move on mouse over, scroll etc...also elementor extras adds parallax effect to background images, although the easing could be better...

But yes this seriously needs added to elementor in backgound and overlay functions.

**Comment by NTuneMusic** [comment]
Mobirise has this function built in also. The background on the parallax scroll moves slower than the objects in front and it looks really nice. I think it's called Jarallax.

**Comment by bainternet** [comment]
I merged this issue with  #72 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
