### ISSUE TITLE
Certain plugins do not show content as soon as I edit page with Elementor

### ISSUE THREAD

**Issue by mimib1230** [pojome/elementor#3239]
I am using Elementor in conjunction with the plugin WPL by Realtyna. This is a real estate listing plugin.

The plugin works okay on pages that are not edited with Elementor, but as soon as I edit the page with Elementor to stylize the page, all of the content from WPL disappears. Before, I would see listings on my listings page, which essentially looks like an eCommerce store with item icons. 

Does anybody know what I can do?

**Comment by bainternet** [comment]
Please wait for the next version of Elementor which fixes an issue which you are describing.

1.9.3 if the issue persists please reopen this issue.
