### ISSUE TITLE
Can't edit widgets

### ISSUE THREAD

**Issue by scottclasen** [pojome/elementor#324]
When I hover in a widget box, doesn't matter if it's a text box or button, I do not see any option to edit or delete that widget. I've tried in both Firefox and Chrome. I was able to edit previously but can not now.

**Comment by arielk** [comment]
When you hover on the widget you can see the button settings on the top/right corner, It looks like this:
![feckugf](https://cloud.githubusercontent.com/assets/1778512/17165660/a36e8ab6-53da-11e6-867a-411421f15fee.png)

**Comment by scottclasen** [comment]
And that's not what I see when I hover over the widget. All I see are the column and section options in upper left corner and nothing in upper right.

Scott Clasen
Director of Marketing | TimeSolv Corporation
c: 763.232.4372 | o: 651.687.0090 x 7011

**Comment by arielk** [comment]
Which version of Elementor are you using?

**Comment by scottclasen** [comment]
Looks like version 0.6.1

 

Scott Clasen
Director of Marketing | TimeSolv Corporation
c: 763.232.4372 | d: 651.687.0090 x 7011 |  <https://apps.timesolv.com/App/Registration.aspx> Try your 30-day free trial

**Comment by scottclasen** [comment]
Here’s a screenshot of what I see when I hover over a widget.



 

Scott Clasen
Director of Marketing | TimeSolv Corporation
c: 763.232.4372 | d: 651.687.0090 x 7011 |  <https://apps.timesolv.com/App/Registration.aspx> Try your 30-day free trial

**Comment by yehudah** [comment]
No screenshot

**Comment by scottclasen** [comment]
Sorry, inserted screenshot in my email reply. 

![elementor _ timesolv certified consultants](https://cloud.githubusercontent.com/assets/20667088/17212573/af701242-5495-11e6-95f0-38f844e919f8.png)

**Comment by arielk** [comment]
Did you try with only elementor activated ?
If that doesn't work change to WordPress default theme.

**Comment by arielk** [comment]
Hi @scottclasen 
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by scottclasen** [comment]
Sorry, I’ve been crushed with some other things. I’ll try to experiment with those suggestions before end of week. Changing to WordPress default theme is not an option for us, but I’ll try deactivating the other plugins and see if there’s one that’s a conflict.

 

Scott Clasen
Director of Marketing | TimeSolv Corporation
c: 763.232.4372 | d: 651.687.0090 x 7011 |  <https://apps.timesolv.com/App/Registration.aspx> Try your 30-day free trial

**Comment by ahmadyanisbii** [comment]
can help me to solve it?
![elementor cant use](https://user-images.githubusercontent.com/48472807/54186434-13e3a980-44b4-11e9-8ca0-fe99ab4d7a0a.png)

**Comment by mralda** [comment]
I was having the same problem and solved it by going into Elementor Settings on the WP Dashboard, going into the Advanced Tab and changing the "Editing Handles" dropdown menu to "Show". Why this is set by default to "Hide" is beyond me!
