### ISSUE TITLE
Video Widget - Image Overlay Play Icon

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#3241]
## Description

The **Video Widget** allows the user to set a custom **Image overlay** with a **Play Icon**.

The play icon is based on the **Select Control** but it has only two options (Yes / No).

We should use **Switcher Control** for better UX, this way the user can change the selection with one button click instead of two.

![video-play-icon](https://user-images.githubusercontent.com/576623/35132019-da83f576-fcd1-11e7-8fe3-ca596c17df27.png)

**Comment by bainternet** [comment]
@ramiy 
PR?

**Comment by ramiy** [comment]
@bainternet PR added!

**Comment by soyket** [comment]
as far as I remember it had an option to replace the icon with other icons! where did that go! If it wasn't there you need to add that because people uses different video play icons all the time !

**Comment by soulwasted** [comment]
How to change the icon?... :)
Is there another way?

**Comment by silvioghedin** [comment]
you need to put a option to change the icon...

**Comment by reelism** [comment]
Another vote for changing icon, I also thought it was previously there.

**Comment by reelism** [comment]
Any update on changing the icon, or instructions to change default icon permanently?

**Comment by SirStancelot** [comment]
Hi all,

Not sure if it is still needed, but in case it helps someone here's my workaround to use a custom icon in the video player.

** Please note that this will affect the icons in all video players.
** I tried this in Elementor Pro 2.8.3. Not sure if it works with the free or previous versions.
** For this I'm using an image (SVG/PNG) for this in stead of an icon font or library.

Use custom CSS to hide the default icon and add new values to display your own icon. You can do this in the page's custom CSS area under settings --> Advanced, or in the section where you'll be displaying the video player go to the Advanced tab and add your CSS under Custom CSS. (Haven't tried this with site-wide custom CSS.)

Then do the following:

`/* First activate the default icon in the video player options, then hide it with custom CSS */

.eicon-play{display:none;}

/* Use this class and change/add the values to display your icon as intended */

.elementor-custom-embed-play{
    width: 100%;
    max-width: 80px;
    content: url(path-to-your/sweet-icon.svg);
    transition: 0.3s ease-in-out;
}

/* If you'd like to add a hover state - Example */

.elementor-custom-embed-play:hover{
    max-width: 90px;
}`

Hope it helps :)

**Comment by gabscoll** [comment]
> Not sure if it is still needed, but in case it helps someone here's my workaround to use a custom icon in the video player.

Yes, still needed.. and thanks!
