### ISSUE TITLE
All changes temporarily lost if clicking on Versions tab without saving.

### ISSUE THREAD

**Issue by hzesen1221** [pojome/elementor#3242]
## Description

I made an GIF animated image to illustrate: https://ibb.co/hNS5bw

Basically, I was making changes this morning, without saving at all, then I clicked on the History panel and switched to the Versions tab to see if there were any auto draft version there.

Then, I switched back to the Modules Selection page, all my changes to the page were gone. I then opened the History Panel once again and clicked on the topmost (newest) action, nothing changed. Then I proceeded down the list, some actions brought back some changes, but they only brought back the changes on that particular element only (which means changes to others elements are still lost) I then tried the last action: Editing Started. After clicking on this action, page gets back to its inital state, but clicking on all other actions above works without error again, and I got back all my work by then clicking on the topmost action again.

Actually, I remember this happened to me once before, but that time I thought it might have something to do with my own setup, and I simply started over making all changes again. 

P.S.: In the newest version, clicking on the 'Update' button does not pop out the 'Page Saved' notification anymore? Besides, Ctrl + S does not seem to do anything anymore.

## Steps to reproduce

https://ibb.co/hNS5bw

## Environment

E 1.9.2
EP 1.13.1

**Comment by bainternet** [comment]
Thanks for reporting we can replicate and working on a fix.
