### ISSUE TITLE
Add Responsive Border Width option for Column

### ISSUE THREAD

**Issue by monika-12** [pojome/elementor#3243]
## Description

Add Responsive Border Width option for column. If I don't want to display border on responsive so in this case I need to create duplicate column for responsive only.

## Steps to reproduce
1. Create 4 columns in section.
2. Add right border on column
3. There is no option to remove right border because on mobile layout column displayed in width 100% so I don't want to display this right border on mobile device.

![column-width-issue](https://user-images.githubusercontent.com/17018981/35138785-27c28fb6-fd16-11e7-99bd-8b35feb93398.png)

**Comment by ramiy** [comment]
Nice catch! Generally speaking **Padding** and **Margin** are using responsive controls, **Borders** are not.

Attaching an image for reference:

![column-border](https://user-images.githubusercontent.com/576623/35156151-9abb7394-fd38-11e7-8f12-daab8f7af592.png)

**Comment by bainternet** [comment]
Boder is a group control and changing it to a specific widget "Colum" is not easily possible right now without breaking layouts....

**Comment by wongdigital** [comment]
+1
This would be useful, particularly with vertical borders separating columns. Those can be hidden when the columns are stacked on mobile.

**Comment by odivius** [comment]
+1

**Comment by TheMangoTrain** [comment]
A trick that worked for me, although not the best:

**Use a spacer widget:**

I needed a responsive vertical border between two columns. There are no responsive controls for borders, so alternatively I created a dummy border by using a spacer widget with arbitrary height in 2%-width middle column. The spacer widget only has pixel height controls, bummer, but at least you can control it responsively (height or visibility). I styled the widget with a border on one side, but you could use a background on it alternatively. Takes some playing around with column percentages across the views (desktop/tablet/mobile). I crucially needed a responsive vertical border, so this works, although the most elegant. The end-user won't tell the difference.

**Comment by hufer** [comment]
Piotnet Addons For Elementor pro version can do it
https://pafe.piotnet.com/index.php/#responsive-border-width

**Comment by Franky-Four-Fingers** [comment]
Yes I need this and surprised it's not even an option.

It's very annoying when using for example 2 columns with a border and on desktop you keep the right border of the left column at 0px and the left border of the right column on 0px so they look good on desktop but on mobile they missing 2 borders.

At least give a code to hide the borders in mobile view.
