### ISSUE TITLE
Testimonial Image Height

### ISSUE THREAD

**Issue by fgarcia6661** [pojome/elementor#3244]
Hi,

Would be great to adjust height for testimonial image, because they are always same size on width and height.

Also, I'd like to report an issue about this. To make it manually, I have to go to the Theme CSS Files. Elementor Custom CSS Editor does not detect changes. It shows on the Elementor Page Builder, but not in the frontend.

Congratulations for your product, Elementor is really awesome, the best.
Frede.

**Comment by bainternet** [comment]
@fgarcia6661 

if the custom CSS is not working for you please contact our support support@elementor.com
