### ISSUE TITLE
Defaults to Responsive Elements

### ISSUE THREAD

**Issue by vrundakansara** [pojome/elementor#3245]
Hey,

I need to set default values for the elements that are responsive. http://bsf.io/txzgb
I need to set different values for Desktop/Tablet/Mobile version for the same.
How can I achieve that?

Regards,
Vrunda Kansara

**Comment by bainternet** [comment]
You can set defaults per device:

```PHP
[
    'default' => 'left',
    'tablet_default' => 'right',
    'mobile_default' => 'center',
]
