### ISSUE TITLE
Chopping off filters in Add Media through text editor

### ISSUE THREAD

**Issue by carasmo** [pojome/elementor#3255]
I am in the latest WordPress and latest Elementor Pro. I use Enhanced Media Library to sort by category since there are TONS of media files of many types. When I Add Media in the Editor, the fields are chopped off. See the image. Thanks! 

**Elementor**
<img width="639" alt="screen shot 2018-01-20 at 5 44 11 pm" src="https://user-images.githubusercontent.com/1124594/35188888-312c4504-fe0d-11e7-9992-34d7da239d25.png">

What it should look like:
<img width="1029" alt="screen shot 2018-01-20 at 6 13 35 pm" src="https://user-images.githubusercontent.com/1124594/35188913-b584077e-fe0d-11e7-947f-97f7faf899af.png">

**Comment by bainternet** [comment]
By default Elementor strips out any script/style that can cause it not to function correctly, now we did add support for "Enhanced Media Library" before but its code has changed lately.

To correct it use this snippet in your child theme's functions.php or a custom plugin file:
```PHP
add_action( 'elementor/editor/before_enqueue_scripts',  function(){
			global $wpuxss_eml_version,
               $wpuxss_eml_dir,
               $current_screen;

        $media_library_mode = get_user_option( 'media_library_mode', get_current_user_id() ) ? get_user_option( 'media_library_mode', get_current_user_id() ) : 'grid';

        // admin styles
        wp_enqueue_style(
            'wpuxss-eml-admin-custom-style',
            $wpuxss_eml_dir . 'css/eml-admin.css',
            false,
            $wpuxss_eml_version,
            'all'
        );
        wp_style_add_data( 'wpuxss-eml-admin-custom-style', 'rtl', 'replace' );

        wp_enqueue_style ( 'wp-jquery-ui-dialog' );

        // admin scripts
        wp_enqueue_script(
            'wpuxss-eml-admin-script',
            $wpuxss_eml_dir . 'js/eml-admin.js',
            array( 'jquery', 'jquery-ui-dialog' ),
            $wpuxss_eml_version,
            true
        );

});

**Comment by carasmo** [comment]
Thank you so much. Deeply appreciated!
