### ISSUE TITLE
Pulling In External Code

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3259]
As I have been working on my website using Localhost, I have noticed that on the pages that I am pulling in code from an external server (using the html widget,) nothing will show up on the page... it just appears blank until I preview it. Problem is, I cannot update anything else on the page because nothing appears to edit in the Elementor window. 

![elementor-edit](https://user-images.githubusercontent.com/35422914/35194142-566512d2-fe7c-11e7-9b11-f12163b8c63a.jpg)

Try to pull in script from external server using html widget.

My Localhost

**Comment by NTuneMusic** [comment]
The code I am using;

`<script type="text/javascript">document.write(unescape("%3Cscript src='http" +  (document.location.protocol == 'https:' ? 's' : '') + "://www.coffeecup.com/api/sdrive/forms/form.js?name=Online%2520Employment%2520Form%26slug=336137%26height=5363%26crossdomains=true%26rand=" + Math.floor( Math.random() * 1000000000 ) + "' type='text/javascript'%3E%3C/script%3E"));</script>`

**Comment by bainternet** [comment]
@NTuneMusic 

When you use `document.write` it clears the page HTML.

**Comment by NTuneMusic** [comment]
OK then, is there something I can do to keep it from clearing the page so that I can continue with my edits?
