### ISSUE TITLE
Horizontal Rule element not rendering

### ISSUE THREAD

**Issue by mojoomla** [pojome/elementor#326]
I upgraded to the latest  Version 0.6.1 today and all my <hr/> elements have vanished.
Elementor is not rendering the horizontal rule HTML element neither during live editor preview nor in the actual webpage.

Please fix this bug ASAP and release an update.

Thanks.

**Comment by cobicarmel** [comment]
Do you mean the divider widget?

**Comment by mojoomla** [comment]
No, the simple  <hr/> tag in the text editor area.

**Comment by mojoomla** [comment]
No the simple  horizontal rule tag < hr /   tag in the text editor area.

**Comment by mojoomla** [comment]
Hi,  I am sorry,  The culprit was a pluging.
https://wordpress.org/plugins/widget-post-slider/
I disabled it and the  < hr/  started showing.
