### ISSUE TITLE
Access array with form actions 

### ISSUE THREAD

**Issue by jojodadj** [pojome/elementor#3261]
Hi There,

We are using the forms API action hook and are having issues accessing the argument array that the forms information comes in. We cannot access the arrays that are protected and cannot find any information documenting the getter?

Joe

**Comment by bainternet** [comment]
Why do you need a getter?

what is the use case?

**Comment by jojodadj** [comment]
I'm trying to pull the form information after it submits to use elswhere. I'm using the hook elementor_pro/forms/valid_record_submitted however elements in the array are :protected

**Comment by bainternet** [comment]
you can access it via the $recond param, take a look at this https://github.com/pojome/elementor/issues/3001#issuecomment-353844190
