### ISSUE TITLE
Suggestion - better text editor?

### ISSUE THREAD

**Issue by mojoomla** [pojome/elementor#328]
I presume that the text editor element of Elementor is its own and not just a Wordpress editor reference.
If that be true, would it be possible to have a richer text editor that gives the ability to format images with  css effects like shadows and captions ?  Also if we could have free dragging and placement of images anywhere in the text area with the text fluidly wrapping around the image, it would be a super addition to layout design.
something like this one...   https://wordpress.org/plugins/richtexteditor/
That would make Elementor the ultimate page builder plugin for Wordpress !

**Comment by arielk** [comment]
We are using an ordinary text editor of WordPress: TinyMCE

So you can expand it by plugin like Advanced TinyMCE: https://wordpress.org/plugins/tinymce-advanced/

**Comment by mojoomla** [comment]
I use an excellent CSS embellishment tool for TinyMCE.
https://wordpress.org/plugins/goworks-styler/

Unfortunately Elementor is not rendering its buttons within the editor.
Only when page is edited outside Elementor the GoWorks-Styler buttons show up.

Can this be fixed at the Elementor end ?

**Comment by karstengore** [comment]
Same here.
I extended TinyMCE with the tables plugin and it shows up properly within the native WP editor. If I switch to Elementor it is gone. I've done that with previous WP/Elementor versions and it worked. Looks like there were major changes while displaying the ordinary text editor of WordPress?
