### ISSUE TITLE
FEATURE REQUEST - 4K / 5K options to cover newer resolutions coming out.

### ISSUE THREAD

**Issue by joshallen73** [pojome/elementor#3285]
Hey Guys - I was told by Elementor to leave a request here- In the responsive view tabs we have mobile, tablet and desktop -but desktop is set to 1920 width.

I have a Microsoft Surface Studio now, 4500x3000 and a imac 5k, plus a lenovo yoga laptop 15" that is 3800 width resolution.

I looked at my staffs 1388px wide 15" and the layout was crammed and squeezed together

I'm noticing layout issues and spacing on padding when i design on a 1920 desktop then look at it on 4k / 5k

I also notice glitches in Microsoft Edge

I have built 63 elementor sites and its all we use at Level

here is our site we are rebuilding - check out the cool owl on services page --any way I have uploaded screen shots - how hard would it be to add 2 more hiher width options on the elements and coloms, modules etc - maybe a 4k icon instead? you would kill the competition...
![2018-01-22 1](https://user-images.githubusercontent.com/29894450/35241388-5561077a-ff84-11e7-8830-23083adcbf81.png)
![2018-01-22](https://user-images.githubusercontent.com/29894450/35241389-556d2aa0-ff84-11e7-8055-3d6774350383.png)

you can see the spacing that i have no control over in 4500x resolution

**Comment by bainternet** [comment]
I merged this issue with  #78 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
