### ISSUE TITLE
Video Play Icon

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#3286]
In the video widget - as far as I remember it had an option to replace the icon with other icons! where did that go! If it wasn't there you need to add that because people uses different video play icons all the time !

**Comment by soyket** [comment]
Also the counter widget takes up space even if there is no prefix added. https://i.imgur.com/yu0fuH1.jpg

**Comment by bainternet** [comment]
@soyket 

Video widget has two options either to display the Play icon or not, if you want a different icon then you would have to enter it manually via CSS.

as for the counter, please open a separate issue.

**Comment by soyket** [comment]
Hello well! I know if I want I can do it with css, but wouldn't it be better for elementor to add a icon crossing option there using the icon manager !
Also I just noticed that the overlay image on video widget gives w3 validation error since there is no alt tag set for that! Can you check that out as well? !

**Comment by dddmark** [comment]
> Hello well! I know if I want I can do it with css, but wouldn't it be better for elementor to add a icon crossing option there using the icon manager ! Also I just noticed that the overlay image on video widget gives w3 validation error since there is no alt tag set for that! Can you check that out as well? !

I totally agree! for what reason css? This should be in the basic functionality!
