### ISSUE TITLE
[Feature Request] We are really missing the post control

### ISSUE THREAD

**Issue by bdthemes** [pojome/elementor#3287]
## Description

Hello, I am so much happy with elementor but I am missing the post control element and it's too must complicated to manage all post for making new post related widget. I saw in pro version have a custom post control (**Group_Control_Posts**) but If you add this post control in core elementor so we will really more happy.

## Steps to reproduce

i am talking about this type of control: http://prntscr.com/i4abc4

**Comment by bainternet** [comment]
@bdthemes 

Currently, this feature is only supported and used in the Elementor Pro.

Thanks for the feedback.
