### ISSUE TITLE
Feature Request - Copy+Paste, Undo etc.

### ISSUE THREAD

**Issue by mojoomla** [pojome/elementor#329]
IMHO, the following features would enhance the usability significantly :-
1) Copy+Paste of elements between pages. 
2) Undo button.
3) Navigating the website while remaining within the Elementor editing environment.

**Comment by cobicarmel** [comment]
Hi @mojoomla, thank you for your feedback.

All of your suggestions are already on our roadmap :) Stay tuned.

**Comment by arielk** [comment]
1.
