### ISSUE TITLE
ux issue with z-index of sections

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#3291]
facing a little 'problem' when trying to 'stack' sections...
attempting to fulfill a design need by stacking the page sections on top of each other like roof tiles and applying a (outer) box shadow to get some nice shadow right beneath (and only there) each section. this works great with the z-index-option but this has a downside - the settings panels of the lower sections cant be reached any more because in each case they're beneath the section above. *sad*

tried several ways to get this tweaked with custom code, but no luck so far, and currently running out of ideas.
somebody any suggestion how to solve this???
how am i able to get the ui **always** on top? (and only the ui...)

BTW:
this would NOT be any issue if there was another way to select elements besides the point and click option inside the preview...

**Comment by norewp** [comment]
@dasigna You might want to try these hacks to see if they help with your issue
https://www.youtube.com/watch?v=aedV5wclir8

**Comment by bainternet** [comment]
@dasigna 
If you set the section `z-index` via custom CSS then you can add a rule to that CSS not to show in edit mode, for example, if your section ID is `MY_SWCTION_ID` then your CSS should be:

```CSS
body:not( .elementor-editor-active ) #MY_SECTION_ID{
     z-index: 1234;
}
```

So it will not apply when in Edit mode.

**Comment by dasigna** [comment]
@norewp thanks for this - found a quite similar (temporary) solution meanwhile and did set the settingspanel inside of the section.
little downside to both of the solutions is that thes sectionspanel quite often might interfere with other panels of rows and widgets. so i dont see it as a final solution but acceptable workaround meanwhile.

@bainternet thanks too.
but this practically defeats the purpose of a live-view builder! you wont see the changes to the box shadow within the editor...
and: this does provide no practical solution at all because you have to take care of all the ids where it would be so much easier (and the real goal btw.) to change only the behaviour of the section settings visibility :)

Finally i really dont understand quite well why this was closed.
theres a problem behind that still exists - and that is the way the ui elements are definded. basically theyre bound to the referring section within the editor, so custom changing of the z-index of the settings panel wont have any effect at all to ALL of the sections.
(which initially was the obviously wrong thought of mine when simply trying to change the z-index of the panel and thinking this might be the solution...)

maybe this has to be considered once more. so i merely like to open it again for thinking again.

**Comment by bainternet** [comment]
@dasigna 

believe me, we have gone through this over and over here, and currently, it's not something we are going to change, we have other requests ( some even by you ;) ) that we feel we should address first.

thanks again for the feedback.

**Comment by dasigna** [comment]
@bainternet 

o.k. i wont insist - for the moment. but i wasnt shure if that was generally denied.
you are right, theres more important things to do first (including my own requests obviously :) ). focus on them and put this one furher down the list. thats alright for me, but dont forget the minor ones. 👍

thanks for clearing out.
