### ISSUE TITLE
Cannot delete widget

### ISSUE THREAD

**Issue by icecandy** [pojome/elementor#3292]
I have a problem with a Livemesh widget (Grid and Posts Block) where when I rollover the widget Elementor pencil icon top right of the widget it does not expand, and so I cannot for example delete the widget.  My only resort is to delete the parent widget which means I lose work.

Now obviously this looks like a bug with the Livemesh widget, but I have said this before to you....YOU NEED A WAY OF INTERACTING AND SELECTING OPERATIONS ON WIDGETS THAT IS NOT POINT AND CLICK!!!

The previous incidences of this being a problem were when using negative margins, a top of page section and when using custom CSS. This is yet another example.

If, for example, you supported a key selection method, one could key or tab through the elements and then ALSO use the delete key to delete the selected element. This would then solve this problem example.

Trying to layer UX in CSS on top of something that is already built with CSS is a bit of a mind blast!

**Comment by bainternet** [comment]
@icecandy 

Elementor at its core is a "Drag N Drop" page builder so it relies on point, click and drag.

Now if there are edge cases like a broken widget or negative margins then you will obviously get undesired results like you describe here.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by rathodmayur93** [comment]
Unable to delete any component :-(

**Comment by Arifi** [comment]
Same issue, i've made a widget and it's not possible to remove/delete it from the page builder :(

**Comment by fivestones** [comment]
I can't delete things from the page builder either. I see the edit (pencil) icon but no delete icon on the top right of the widget.

**Comment by Arifi** [comment]
So, still can't fix it, here is the error i get in consol : 
```
Uncaught Error: A "url" property or function must be specified
    at F (load-scripts.php?c=1…rtable&ver=4.9.8:18)
    at n.url (load-scripts.php?c=1…rtable&ver=4.9.8:18)
    at Function.m.result (load-scripts.php?c=1…ortable&ver=4.9.8:5)
    at n.e.sync (load-scripts.php?c=1…rtable&ver=4.9.8:18)
    at n.sync (load-scripts.php?c=1…rtable&ver=4.9.8:18)
    at n.destroy (load-scripts.php?c=1…rtable&ver=4.9.8:18)
    at n.destroy (agent.js:4053)
    at n.onDestroy (editor.min.js?ver=2.2.5:2)
    at _ (load-scripts.php?c=1…rtable&ver=4.9.8:18)
    at m (load-scripts.php?c=1…rtable&ver=4.9.8:18)
```

**Comment by Arifi** [comment]
@bainternet what do you mean by "broken widget or negative margins" ?

We are making widget according to Elementor's documentation, why then we make widget that we can't event delete ?

Right now there is not reference to how to write code to delete our widgets, otherwise we'll do, so we assume that it's Elementor feature (it's on its UI and we can not rewrite the delete element of Elementor)

So, where is the solution ?

**Comment by livesworks** [comment]
Right click and select delete on menu?

**Comment by Arifi** [comment]
@livesworks yes, that does not work

**Comment by i30** [comment]
@Arifi Today, I came up with that error too. The bug is caused by a mistaken control ID which prevents Backbone Model from generating `url` property. Backbone generates URLs of the form: `[collection.url]/[id]` by default.

```php
$this->add_control('id', [
    'label' => __('Foo ID', 'textdomain'),
    'type'  => Controls_Manager::TEXT,
])
```
Changed `id` to `foo_id` fix the bug for me.

**Comment by Arifi** [comment]
@i30 Thank you ! but whenre should i put the code ? before or after `$this->start_controls_section` ?
and what `foo_id ` is supposed to be ? the plugin name ?

Thanks for your help
