### ISSUE TITLE
[Bug] Shape divider "width" doesn't work when "height" has already been set

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#3294]
I'm not sure if this was always the case, but in the shape divider widget, I'm forced to set the width parameters first, and then the height parameters. Once the height is set, the width parameter no longer works as it should. The issue is actually different depending on whether you are using the top or bottom shape divider.

When using the _Top Shape Divider_ the width moves the shape along the x axis. When using the _Bottom Shape Divider_ nothing happens.

Here's a video of the issue:
https://www.dropbox.com/s/ztgx0lnqr6y1zrf/shape-divider-top-bottom.mp4?dl=0

This was on a local install with Astra, Elementor, Elementor Pro and no other plugins.

**Comment by bainternet** [comment]
@avermat 
We can't replicate the issue you are describing... please check if you have any JS errors and also check using a Twenty15-17 theme.

**Comment by avermat** [comment]
I did a fresh local Flywheel install with Twenty17 theme and Elementor and am seeing the same issues.

**Comment by bainternet** [comment]
@avermat 

can you try a different theme and see if its still there...

**Comment by avermat** [comment]
It works fine with OceanWP. 
However, it didn't work with any of the other themes I tried (Astra, Zerif Lite, and Twenty15-17).

**Comment by bainternet** [comment]
Most likely a CSS related issue but we can't replicate.

Please contact our support and see if they can help you.

**Comment by dmaziarz** [comment]
For everyone here in the future:
`svg {
	max-width: none;
}`
