### ISSUE TITLE
Social Icons Color Not Working

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3297]
## Description

Social Icons are not accepting the secondary color in my widget. See the screenshot or visit ntunemusic.com and look at the social icons in the header and footer.

![social-icons](https://user-images.githubusercontent.com/35422914/35293406-965c3b24-0041-11e8-9927-d77aa6fdabd3.jpg)

## Steps to reproduce

See screenshot

**Comment by bainternet** [comment]
Seems like You have some Javascript errors.

please paste your system-info here.

**Comment by NTuneMusic** [comment]
OS Name	Microsoft Windows 10 Pro
Version	10.0.16299 Build 16299
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 1707, 12/13/2013
Installed Physical Memory (RAM)	32.0 GB

**Comment by NTuneMusic** [comment]
I have tried deleting the social icons and rebuilding them and the problem still persists.

**Comment by NTuneMusic** [comment]
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: 5.6.37
	PHP Version: 7.1.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.2
	Site URL: https://ntunemusic.com
	Home URL: https://ntunemusic.com
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.4.12
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

== Active Plugins ==
	Elementor
		Version: 1.9.3
		Author: Elementor.com

	Elementor Pro
		Version: 1.13.2
		Author: Elementor.com

	Ocean Extra
		Version: 1.4.2
		Author: OceanWP

	WooCommerce
		Version: 3.2.6
		Author: Automattic


== Debug ==
	Errors: 
		TypeError: elementorFrontend.getElements(...).jQuery is not a function
			at https://ntunemusic.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.3 - 2:122008
			2018-01-25 11:47 +00:00
			x 4 times

		TypeError: elementorFrontend.getElements(...).jQuery is undefined
			at https://ntunemusic.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.3 - 2:78379
			2018-01-25 11:47 +00:00

		TypeError: elementorFrontend.getElements(...).jQuery is not a function
			at https://ntunemusic.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.3 - 2:122008
			2018-01-25 11:47 +00:00
			x 20 times

		TypeError: elementorFrontend.getElements(...).jQuery is undefined
			at https://ntunemusic.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.3 - 2:78379
			2018-01-23 21:15 +00:00

		TypeError: elementorFrontend.getElements(...).jQuery is not a function
			at https://ntunemusic.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.3 - 2:122008
			2018-01-23 21:15 +00:00
			x 16 times

		TypeError: elementorFrontend.getElements(...).jQuery is undefined
			at https://ntunemusic.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.3 - 2:78379
			2018-01-23 13:38 +00:00

		TypeError: elementorFrontend.getElements(...).jQuery is not a function
			at https://ntunemusic.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.3 - 2:122008
			2018-01-23 13:38 +00:00
			x 21 times

		ReferenceError: xMinicart is not defined
			at https://ntunemusic.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 line 2 > eval - 1:2
			2018-01-23 12:48 +00:00

		TypeError: elementorFrontend.getElements(...).jQuery is not a function
			at https://ntunemusic.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.3 - 2:122008
			2018-01-23 12:48 +00:00
			x 2 times

		ReferenceError: xMinicart is not defined
			at https://ntunemusic.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 line 2 > eval - 1:2
			2018-01-23 12:44 +00:00
			x 2 times

**Comment by bainternet** [comment]
@NTuneMusic 

it's not something we can replicate,
please contact our support and see how they can help you.
support@elementor.com
