### ISSUE TITLE
Page "Update" with keyboard command "Shift+Cmd+S"

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#3298]
As requested by @bainternet on issue [3126](https://github.com/pojome/elementor/issues/3126#issuecomment-359709349), can you please add keyboard support to "Update" a page using the keyboard command Shift+Cmd+S (Mac) / Shift+Ctrl+S (Windows)?

@maxwellhibbert @xttn

**Comment by drank** [comment]
+1 in support of this request.

Also to bundle some previous info/request on the topic - https://github.com/pojome/elementor/issues/3067#issuecomment-355509722.

**Comment by maxwellhibbert** [comment]
I don't mind what the shortcut is, so long as there is one :)
With some visual feedback after saving/publishing, just like the old version.

**Comment by xttn** [comment]
+1 in support of this request 😄

**Comment by black-eye** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue #3526 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
