### ISSUE TITLE
Feature request - Add a template section into another section

### ISSUE THREAD

**Issue by spit06** [pojome/elementor#3299]
Hi,
Just a quick post about adding the possibility to put a section into another section after importing it with the "Add Template" button.

## Description:

Let's say I build **PAGE 1**, I create a main section in which I will create other sections (A, B and C) with the Column widget.
So it will look like that:
MAIN SECTION:
- section A
- section B
- section C
- etc.
<a href="http://fr.tinypic.com?ref=11w4mt4" target="_blank"><img src="http://i63.tinypic.com/11w4mt4.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

If for example, I wanted to save **SECTION A** and reuse it on **PAGE 2**, I would just save it into the library. Ok, until now, everything works great!

On **PAGE 2**: The problem is that when I open the template with the "Add Template" button (next to "Add Section"), the **SECTION A** cannot be put inside a MAIN SECTION I would have created. (So, I cannot put the Section A in the same configuration as on PAGE 1: "Main Section: Section A, Section B, ...")

Note: I contacted the Elementor Support, which told me that I could use the Template Widget to resolve the problem. So I tried it.
Actually, I'm able to import SECTION A from the library into a MAIN SECTION, but with this manipulation, I cannot modify the SECTION A directly. I need to click on "Edit Template" (in the Widgets options) what redirects me to another page where I can modify the template. So much work for nothing!

##
**So my request would be the following:**
Add the possibility to put a section into another section after importing it with the "Add Template" button.

**Comment by bainternet** [comment]
A section in a section is not going to happen anytime soon, But you can currently drag section to replace a section or even columns.
