### ISSUE TITLE
image look nice in elementor but smaller viewing in page...

### ISSUE THREAD

**Issue by zackcantiqa** [pojome/elementor#3301]
hi..
I,m new to elementor but familiar with wordpress...Recently, i got a prblm with my image. header image look nice in elementor but smaller in page..I put the image at larger size but still look smaller...I no idea to fix it..

Anyone here can help me ? my web : [www.melaleucagroup.my](url)

Thanks

**Comment by bainternet** [comment]
@zackcantiqa 

Please contact our support and see if they can help you.
support@elementor.com
