### ISSUE TITLE
ReferenceError: tinymce is not defined

### ISSUE THREAD

**Issue by nullmem** [pojome/elementor#3305]
## Description

When loading Elementor on a freshly installed site, I would get loading E for infinity, producing the following debug error:

`ReferenceError: tinymce is not defined at
/wp-content/plugins/elementor/assets/js/editor.min.js - 2:71989`

My javascript console produced the following error:
`Loading failed for the <script> with source “/wp-includes/js/tinymce/wp-tinymce.php?c=1&ver=4607-20171116”.`

This gave me a clue as to the problem. For security reasons, it is common practice for security conscious hosting platforms to prevent direct execution of any PHP in the wp-includes directory. Being the owner of this particular hosting platform I temporarily disabled this restriction, and the editor loaded.

Strangely enough (maybe not so strange as it points to what is going on,) after loading the editor for the first time, I can then reapply this restriction, and all future Elementor pages will work just fine.

There have been many complaints lately on facebook recently about loading E of doom on some hosts, and maybe this will give some insight into the problem. I did not dig further into this, but I hope this helps.

## Steps to reproduce

1. Add something like this to your Nginx config:
`location ~* ^/wp-includes/.*\.(php|phps)$ { internal; }`

2. Using fresh WordPress and Elementor install try opening a page with Elementor for the first time.

## Environment
	
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.36
	PHP Version: 7.0.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.2
	Site URL: https://www.wpsec.tk
	Home URL: https://www.wpsec.tk
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.0.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

== Active Plugins ==
	Elementor
		Version: 1.9.3
		Author: Elementor.com

	MainWP Child
		Version: 3.4.5
		Author: MainWP

== Debug ==
	Errors: 
		ReferenceError: tinymce is not defined
			at https://www.wpsec.tk/wp-content/plugins/elementor/assets/js/editor.min.js - 2:71989
			2018-01-24 16:10 +00:00
			x 7 times

**Comment by bainternet** [comment]
@nullmem 

Thanks for reporting,

If I'm not wrong, we don't call that file directly, the call is generated by the native `WP_Editor::print_tinymce_scripts` method.

and is depended on `script concat settings` and server Gzip encoding.


So this seems more of a WordPress issue then Elementor, and not even an issue but more of a misconfiguration.


again, thanks for reporting.
