### ISSUE TITLE
Feature Request - Overwrite Widgets in My Template Library

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3307]
## Description

I think it would be cool if when we save a widget to our My Template Library, if there were a way to overwrite an existing widget. Maybe an "Overwrite" option from a list of existing widgets.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by pulla** [comment]
+1, yes please it should be. It's really inconvenient to keep working on templates. 
Please improve "my template" like elementor "Pages", "Blocks".
