### ISSUE TITLE
[Feature Request] Global access for ColumnView 

### ISSUE THREAD

**Issue by jegbagus** [pojome/elementor#3310]
## Description

As i previously post, i will need to modify ColumnView behavior, such as : 

- Need to make sidebar sticky (for news theme). i can make the this work with changing wrapper of container. but the problem arise when adding new element. so i need to modify `onRender` function on ColumnView. example : https://sendvid.com/zl74y7y9

- Our element will adapt with column size. for example, on 100% width column, it will look like block A. and on 67% width column, it will look like Block B. on this case i will need to modify little code on ColumnView so i can make something like this. example : http://sendvid.com/5dj8x0vf

that is why i hope you can make ColumnView have a global access. or give filter & trigger at onRender function. i made some pull request, please take a look : https://github.com/pojome/elementor/pull/3279

Thank you

**Comment by bainternet** [comment]
@jegbagus 
You can use the `elements/column/behaviors` filter to add your behavior.

https://github.com/pojome/elementor/blob/master/assets/dev/js/editor/elements/views/column.js#L31
