### ISSUE TITLE
[Feature Request] API for customizing how Elementor looks.

### ISSUE THREAD

**Issue by elementoristhefuture** [pojome/elementor#3311]
**I love Elementor. I do. I'd gift it to my kids for children, they'd have no idea what it is but I'd sush them and tell them "it's a gift from the bottom of my heart".**

But boy! **In my opinion** it looks somewhat "old". Don't get me wrong, people definitely love it. But it'd be nice to have some things of the UI re-arranged and them made look good.

Do take a look at Massive Dynamic's builder:

https://www.youtube.com/watch?v=GpGL83Vu7vQ

It seems to me this is exactly what they did. The do claim to have their own "mBuilder" but it's just too similar. Leaving this aside, it looks incredible.

I'd love to be able to add nice touches to Elementor.

I understand this is something that could create issues with consistency, but was wondering if this is something the team is looking at.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
