### ISSUE TITLE
[Feature Request] Exit to live page after editing from "Edit with Elementor" on the admin toolbar

### ISSUE THREAD

**Issue by drank** [pojome/elementor#3312]
As part of my workflow I very often enter editing a page with Elementor from the admin toolbar at the top using the "Edit with Elementor" button. After I've done my edits (including interim previews) I exit to the live page again using the following sequence of actions:
1. Click on the hamburger (top left)
2. Click on "Exit to Dashboard"
3. Click on "View Page" in the admin toolbar

These are hell of a lot of clicks :)

**Can you implement a one click exit to the page?**

PS: While we are at it, can you also rename "Exit to Dashboard" to something else (e.g. "Exit")? Clicking this currently just exits to the edit view of the page/template and never to any kind of a dashboard, so it is misleading.

**Comment by drank** [comment]
Dear Elementor Team,

There is a very nice plugin that already does what I asked - https://wordpress.org/plugins/granular-controls-for-elementor/, so you can disregard this request.

**Comment by drank** [comment]
Sorry, was fast to close the issue - reopening so that other users can benefit from the finding.

**Comment by bainternet** [comment]
they can benefit just as well if it's closed.

thanks.

**Comment by simonclay** [comment]
I also had this issue and will check out the plugin mentioned. 

I personally think that the ‘Exit’ button(s) should be at the foot, with the Publish / Update button. 

It’s great to hear that after you save the changes you can hit ‘Preview’ to take you to the live page, but it’s not obvious and a bit of a secret feature.

**Comment by soulshakepower** [comment]
I really think this feature is a must have: I believe one of the main reason we (as webmasters) use Elementor is to offer a convenient way for our customers/website owners to edit their content from the front-end. So if you follow a beginner-editor flow of actions: they will use the "edit with elementor" button from the wp top bar on a page they want to edit.. then they edit it.. hit save.. and they're stuck there! No exit button, no more top bar, clicking on menu items doesn't work, they would hit their browser's previous button and get a mess.. etc.
I believe you guys putted many thoughts into this amazing editor you created, and I definitely love it!! But I think from a beginner editor stand point, this feature is key. Thanks for considering!

**Comment by blue928** [comment]
+1 for this feature. I understand the OP found a plugin to do it, but I don't think installing yet another plugin and adding to plugin bloat would be the right approach here.  Where there is currently "Exit to dashboard" It would be great if it were:

"Exit to Dashboard"
"Exit to Page"   (Or, dynamically, exit to post depending on which one you were on.)

This removes 1 to 2 steps for a designer / developer depending on what they need to do next. Added up, this is unnecessary clicking over the course of a full project and slows down production. As others have mentioned, even having those available without having to click into that menu would yet save another step, greatly speeding up workflows.

**Comment by bjornenio** [comment]
Still no option to exit the builder and go to the actual page / post that was being edited. Seriously...

**Comment by naveenbettiah** [comment]
While searching for this solution, I found later that, while editing content using Elementor, open a single tab in its preview mode. Whenever any edit is done and Elementor is updated, the tab showing the preview refreshes automatically to display fresh edits. Worked this way on Chrome. Opening both edit and preview mode in separate windows increases the speed of work.

**Comment by scrobbleme** [comment]
+1 for 'Exit to Page'

**Comment by sandeld** [comment]
I also think this is a pretty basic feature that is included in every other drag and drop builder I've used, and I'm certainly not going to install another plugin or add-on just to get it here. So ummm.....

+1 for 'Exit to Page'

**Comment by dollhauss** [comment]
This is a major issue with the builder. Not being able to Exit the builder at all.
Granular Controls is now no longer in development and it is proving very complicated to view a live page as you first have to open a preview and then right click the logo and 'open in new tab' to actually 'Exit' the builder and get to the homepage.

Surely adding an Exit Builder / View Live Page option is not that hard to implement. It use to exist before the Preview was introduced but was then removed.
Please bring it back - maybe as an option in the Elementor settings to turn Preview off and have it just go direct to the live page?

**Comment by dotpdesign** [comment]
+1 fix this issue of exiting to page with a button and the preview issue as well.

**Comment by simonclay** [comment]
'View Page' is now a button just above 'Exit to Dashboard'. But I wish it was next to (or as a dropdown to) 'Update'.

**Comment by dollhauss** [comment]
Yes I noticed it has now been included.
I only wish it would open in a new tab - or at least give us the option to do so.
Even if you right click the link, it does not show an 'open in new tab' option. This has been removed for some reason.
