### ISSUE TITLE
Self hosted videos (Mute & autoplay)

### ISSUE THREAD

**Issue by nicooprat** [pojome/elementor#3313]
Using WordPress 4.9.2 & Elementor 1.9.3.

I'd like to better embed custom videos with Elementor, I mean videos hosted on our own WordPress and not Youtube or any other:

* Add a cover image
* Add a mute attribute toggle (especially useful for autoplay on iOS for example)
* Add a autoplay attribute toggle

Didn't find anything in the issues or in Elementor config. Did I miss something? Is this something planned? Thanks!

**Comment by michaelnorthern** [comment]
Also looking for this feature.  Related: for unknown reasons, just observed that YouTube videos are muted when used as a section background.  Elementor still needs work, hoping for improvement in 2.0, coming soon???

**Comment by 4continents** [comment]
@arielk Was the "Add an autoplay attribute" for self hosted videos removed from the milestone 2.1.0? I can't find the option in elementor right now? Would be great to see that. 

אלוהים מגן על ישראל

**Comment by Savannahwang** [comment]
Hi,
I also have the same issue right now. The self-hosted video can not autoplay. the site is here: maskskincare.com
