### ISSUE TITLE
 [Feature Request] Add Sendinblue.com API

### ISSUE THREAD

**Issue by IDESIGNSTUDIO** [pojome/elementor#3315]
This is a feature request:

Add Sendinblue.com API tot he already existing online marketing integrations as MailChimp, GetResponse, MailPoet, etc.

SendInBlue is widely used in Europe with servers on the mainland. This complies very well with the EU privacy policy and many companies work with SendInBlue instead of MailChimp.

SendinBlue has also a free plan, which is also why many small companies choose to use with for their starting online marketing.
Thanks.

**Comment by bainternet** [comment]
@IDESIGNSTUDIO 

This should be fairly easy to do with the provided hooks ex:

```PHP
<?php

add_action( 'elementor_pro/forms/new_record', function( $record, $this ) {
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	// Ref: https://developers.sendinblue.com/v3.0/reference#createcontact
	$fields = [
		'email' => $record->fields['ID_OF_YOUR_EMAIL_FIELD'],
		'emailBlacklisted' => false,
		'smsBlacklisted' => false,
		'listIds' => [1,2,3],
		'updateEnabled' => true,
		'smtpBlacklistSender' => [],
		'attributes' => [],
	];
	foreach ( $record->fields as $field_id => $field ) {
		$fields['attributes'][ $field_id ] => $field_id['value'];
	}
	wp_remote_post( 'https://api.sendinblue.com/v3/contacts', [
		'headers' => [
			'api-key' => "YOUR_API_KEY",
			'content-type' => 'application/json',
		],
		'body' => json_encode( $fields )
	]);
});
```

Now, this is assuming that your field ids match and exist in your contact database for the attributes field. And in general, this is an example.


Hope this helps

Ref: #2397

**Comment by IDESIGNSTUDIO** [comment]
Wow, that sounds very good. I will test the code and give a feedback.
Thank you!

**Comment by erubianes** [comment]
Hi bainternet,

Where do I insert this script? Can I do it in the Hooks section of my theme Generate Press or where?

Thank you :)

**Comment by Tapbeat** [comment]
> Hi bainternet,
> 
> Where do I insert this script? Can I do it in the Hooks section of my theme Generate Press or where?
> 
> Thank you :)

I am not familiar with php, but when I look at it I would put it in the functions.php of your child theme...

**Comment by PaulinHalenria** [comment]
I don't understand why this issue has been closed as there is only a workaround. A real integration like other provider is still missing.

**Comment by Ade-UI-RE** [comment]
Hi @bainternet , 
Please Where do I get the hook inserted to integrate Sendinblue with Elementor? I tried the Functions.php child theme edit with no luck. 

Can you help with the best direction please?

**Comment by collizo4sky** [comment]
If you are using MailOptin, you can integrate Sendinblue with your Elementor Forms.

See https://mailoptin.io/article/elementor-form-integration/

And it's free => https://wordpress.org/plugins/mailoptin/

Below is a screenshot of Zoho but you should get the idea.

![image](https://user-images.githubusercontent.com/4140659/72825305-15a2ff80-3c77-11ea-8907-58a5f5985e6a.png)

**Comment by erubianes** [comment]
And E-goi email marketing when?
