### ISSUE TITLE
Ecwid Messes Up Text Editor

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3316]
## Description

We use Ecwid as our online eCommerce provider. I have determined that their plugin causes my Elementor Text Editor to mess up. You can see what I am talking about in the screenshot.

![text-editor](https://user-images.githubusercontent.com/35422914/35407381-c6607bd4-01d9-11e8-86ae-e587354cd7b4.jpg)

**Comment by norewp** [comment]
This needs bringing to the attention of ECWID developers to address.

**Comment by NTuneMusic** [comment]
Thank you. I think we're going to switch to Woocommerce.

**Comment by bainternet** [comment]
More of an ecwid issue then Elementor.

**Comment by NTuneMusic** [comment]
Thank you Matt. I really appreciate you guys addressing this issue.
