### ISSUE TITLE
When selecting a color with alfa, the value is not fully visible.

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3320]
The title says it all. 
Just to add: ironically, that invisible part is the very same part, you need to see, when you're trying to set the alfa value precisely.

![obrazek](https://user-images.githubusercontent.com/5634870/35454063-cb1d8ab0-02cc-11e8-9971-817efbc335a8.png)

**Comment by dasigna** [comment]
have to second this.
already mentioned the same quite a long time ago, as its an issue right from the beginning and still not solved. really annoying little thing.

**Comment by bainternet** [comment]
@black-eye 

Thanks for the feedback.

**Comment by black-eye** [comment]
Thanks for the update, it's definitely better, but still not 100% perfect:

![obrazek](https://user-images.githubusercontent.com/5634870/36499426-7b2906c2-1741-11e8-9fa3-fa4ec8c78cea.png)

Not sure, but maybe the reason is the translated text in the button.

**Comment by dasigna** [comment]
exactly the same here - last digits still missing :/

maybe add a reset icon with tooltip instead of text and we'll have it?

**Comment by black-eye** [comment]
+1 for reset icon
If it could be used for reseting typo or box shadow settings (where it is much more confusing regarding the UX IMHO), why not here...
