### ISSUE TITLE
[Feature Request] Social Media Feed Widgets

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#3321]
I would like to see 'native' Elementor widgets for social media feeds particularly facebook and Twitter. Available plugins are limited to very primitive vertical feeds originally designed for the sidebar and have expensive pro versions that enable customisation and styling. A native Elementor widget that enabled vertical, horizontal and masonry displays of posts with the usual Elementor styling functionality would be brilliant. If implemented I could see follow-on request for other media like snapchat etc.

**Comment by bainternet** [comment]
@nickdgreen 

Elementor Pro already as Native Facebook widgets...

**Comment by bodhi1970** [comment]
@bainternet Unfortunately the visibility and design of Facebook posts is very limited to a certain width. On Firefox I don’t see the posts at all. Only fine white lines where the posts should be.
https://maggietapert.com/essays-writings/
