### ISSUE TITLE
Super-Elementor PRO

### ISSUE THREAD

**Issue by mrkiner** [pojome/elementor#3324]
Hello. I'm very attracted to Elementor as a plugin for creating sites. But I'm worried about the tightness of the plugin in some issues.

For example, what if I want to offer users and a toolbar too? Modify it and submit it to some groups of users !?
What if I want to modify the menu, add "discounted goods" there and attach the famous orange ball wp with the number of such goods.

Very often I come across the need to display a picture I did not select earlier, but to show the result, which is provided by php code.
For example, to offer an authorized user those goods that he prefers to order from me, and perhaps not with the price indicated in the store Woocomerce, but composed accordingly to my personal discount system.
Or one of the users can be a fan of my articles on the blog, and no other articles of other editors are interested in him, why should he waste time searching for my articles, if an automatic script can output what I need and where necessary?

If I am the Chief Administrator of the site, and some helpers are their moderators, maybe they do not need to see some parts of the site intended for buyers, as well as buyers probably do not need to see parts of the site for regular customers.

I support the idea that if it is necessary - the site must change itself even if there is no chief administrator in the network and, accordingly, with the needs. If the chief administrator has not opened access to anyone and accidentally got into an accident, is in hospital with a broken leg and can not tell what happened to the site's buyers, why not let the site warn visitors that something is wrong.
For this it is enough to check for example, was the Chief Administrator on the network the last 36 hours? In this case, the site on the main page apologizes instead of the Chief Administrator about technical problems and warns that the sending of the purchase can be carried out with a delay.
Block the sale of goods that require the control of the Chief Administrator, for example, because this product is exhibited in the affiliate program - ie if the goods end with the partner, the product will end on the site, while the partner can trade in the old fashion, with a pen and paper in hand.

I can expect that the product will be popular and put it on the homepage of the online store, and then it turns out that buyers from one country prefer another product, regular customers refuse to buy anything without a discount, and a certain group of users are allowed with the Gothic style of life, all the goods that I can wish them to offer.
It is very convenient with php code to go through the user's data and indicate Elementor that this user needs to show the most popular products for this tag ...

This is all online shopping, and if I sell virtual goods? I am surrounded by solid adventurers, some of them are successful in selling weapons, armor and other items in online games.
And of course I want a user who has logged into the site, which I have known for some time, to pay attention to what I want to show him.
This is if someone else's online games, and after all, I'm now engaged in my own ... and a little knowledge of php is enough for me to manipulate the field of view of website visitors since it is profitable for me ...
For example, specify the optimal outfit for his character level as soon as he enters the site under his login or habitual ip address.

In this plan and endless other situations, php in my approach is ideal, but the user codes are almost not compatible with the behavior of wordpress, except if you install the plugin ...
And Elementor is waiting for professionals that they are trying to control the CSS styles for example, and not the conditions under which the page behaves exactly like this, and not otherwise.

Reading that Elementor PRO will manage the entire site, I expected that it would literally manage everything. Set up on the site almost everything, like Artisteer and Elementor as a whole, control the width of the page, the location of the menu, the background.

"More often than not, people do not understand what they really need until they themselves show it." Approximately this I now expect from you, about this I am all this time and I'm clapping, I want to show my visitors what they want to find on my site or not, so that they do not spend their time on these searches.

And now, no matter how much it costs, will you be able to provide me with such opportunities in Elementor PRO, now or later, in the "general" development of the project or in the individual plug-in add-ons, at any time or not earlier than X years ...

For errors in the text I ask to forgive, so as not to waste a lot of time on an independent front, I used an interpreter.

**Comment by bainternet** [comment]
@mrkiner 

thanks for the feedback and time you put into this. You did bring up a few interesting points and we will have a  talk about them.
