### ISSUE TITLE
[Feature Request]Per page option for CSS Print Method

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#3325]
Would it be at all possible to implement the CSS Print Method on per page basis via the Document settings instead of it being global please?

**Comment by bainternet** [comment]
@norewp 

Whats the use cases?

**Comment by norewp** [comment]
@bainternet, thank you for the response and consideration on this request.

Currently this would solve a number of issues on client sites where headers & top bars have been built and CSS is being loaded in the footer.

This maybe an interim solution as I understand that it may not be an issue once theme builder is released but us site developer will still have custom work where it means we still have to support legacy work done prior to themer.

The other approach for me personally is the Granular Controls addon where I'm looking to implement Admin Dashboard modules and having the CSS print method for these set to inline will streamline the code and end user workflow.

Regards,
Zulf

**Comment by bainternet** [comment]
this becomes unnecessary for the vast majority of the cases now that we are releasing the theme builder.

So I'm closing this.

Thanks for the suggestion.
