### ISSUE TITLE
[suggestion] development roadmap

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#3326]
what i really want to see somewhere in this project is a roadmap as an overview whats going on actually and is under development, and what are the next steps on the road.

just for a more clear view and transparency 😎

**Comment by drank** [comment]
Now that is something that I would very much like to see too!

Dear Elementor Team, would you care to chime in into this topic? I suspect that you would rather not (https://github.com/pojome/elementor/issues/78#issuecomment-359858790) but hey, who knows... I would very much prefer to be wrong in this case :)

**Comment by bainternet** [comment]
@dasigna 

Maybe not a full roadmap and development plans but as far as what is planned ahead, I did get an answer form our CEO that we will provide a very detailed post about what is coming next to elementor and what you can expect in the following months.

As for when this post will come out, I was told in a month or so.

**Comment by mredodos** [comment]
it would be very interesting to have a roadmap for 2019 too!

**Comment by mariobarretta** [comment]
> it would be very interesting to have a roadmap for 2019 too!

me too

**Comment by moonbeetle** [comment]
I would like to hear about planned developments or improvements too. It is also very useful when deciding on wether or not third party plugins for Elementor offer added value or not.
