### ISSUE TITLE
FEATURE request

### ISSUE THREAD

**Issue by macromarkman** [pojome/elementor#3333]
We use "Remakety" in our Shopify store for email marketing. I've tried using the submit URL via the Webhook feature and the form submits successfully but the email doesn't get added to the database.  Here if the code Remarkety supplies for email integration. Is there a way to do this using Elementor's nice form widget?  Thanks.

Detailed instructions:
1. The action of your form should be:

https://app.remarkety.com/public/subscribers/createcontact/
Example:

<form action="https://app.remarkety.com/public/subscribers/createcontact/" method="post">
2. There are 3 mandatory fields you must have in your form:

[remarkety_id]: Your unique store ID is: XXXXXXXX. You should set it as a hidden field.
[form_id]: Your unique form ID is: YYYYYYYYY. You should set it as a hidden field.
[email]: A contact (person) must have an email address. Text field. Value: The customer's email address

Example:

```
<input type="hidden" name="remarkety_id" value="XXXXXXXX">
<input type="hidden" name="form_id" value="YYYYYYYYY">
<input type="text" name="email" >
```

Note that this actually does work if I embed this HTML snippet but... the form looks terrible.:

`<form action="https://app.remarkety.com/public/subscribers/createcontact/" method="post" > <input type="hidden" name="remarkety_id" value="XXXXXXXX"> <input type="hidden" name="form_id" value="YYYYYYYYY"><table width="100%" border="0" cellpadding="2" cellspacing="2"><tr><td><font size="2" face="Arial, Helvetica, sans-serif">Email: </font><font size="2" face="Arial, Helvetica, sans-serif">&nbsp; </font></td></tr><tr><td><font size="2" face="Arial, Helvetica, sans-serif"> <input name="email" type="text" size="20"> </font> </font></td></tr><tr><td><font size="2" face="Arial, Helvetica, sans-serif"> <button type="submit" value="Submit">Submit</button></td></tr></table></form>`

**Comment by bainternet** [comment]
You can do that very easily with a simple action hook, ex:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record ) {
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );


	$fields = [];
	foreach ( $submmited_fields as $field_id => $field ) {
		$field[ $field_id ] = $field['value'];
	}
	// Add subscriber
	wp_remote_post( 'https://app.remarkety.com/public/subscribers/createcontact/', [
		'body' => $fields,
	]);
});
```

Just make sure you have set the hidden fields ids correctly.
