### ISSUE TITLE
A way to add fields/options/tabs to main sections?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3334]
Hi! I would need to add custom css classes to main sections. I would need to do so using some UI, because I need to lock the class slugs and make my clients be able to insert the classes without errors. So basically I'll use switches, divided by category or tab.

One way I think it would be to create a custom 'container' widget and add switches to that widget instead of the main outer section, but from an optimisation/html point of view, it would be plain useless crap.

So, is there a way to add UI things to sections and then reflecting the values on the sections source?

Thank you

**Comment by bainternet** [comment]
@stratboy 

why can't you use the native `CSS ID` or `CSS Class` controls?
what do you mean by "So basically I'll use switches, divided by category or tab"? you mean replacing the TEXT input controls to a select dropdown?

please clarify.

**Comment by stratboy** [comment]
> why can't you use the native CSS ID or CSS Class controls?

because I need to lock the class slugs and make my clients be able to insert the classes without errors

> you mean replacing the TEXT input controls to a select dropdown?

I mean that I need people not to do write directly. I also need to add several classes, not one.

Anyway, let's concentrate on how, better the why :) Whatever is the reason, I need exactly that: is there a way other than creating a sub-container widget?

**Comment by bainternet** [comment]
@stratboy 

When I ask why its because I want to help you and maybe we can come up with a solution for you, any way you can add classes to the section wrapper easily with the provided hooks ex:
```PHP
add_action( 'elementor/frontend/element/before_render',function( $element ) {
	// Make sure we are in a section element
	if( 'section' !== $element->get_name() ) {
		return;
	}
	$element->add_render_attribute( '_wrapper', 'class', 'stratboy-elementor-class' );
});
```

Now if you want to do that based on controls in the panel, Again, something that should be even easier to do if you use the `prefix_class` parameter when you add your controls:

```PHP
add_action('elementor/element/section/section_typo/after_section_end', function( $section, $args ) {
	$section->start_controls_section(
		'section_custom_class',
		[
			'label' => __( 'My Custom Section', 'elementor' ),
			'tab' => \Elementor\Controls_Manager::TAB_STYLE,
		]
	);

	$section->add_control(
		'add_blue_class',
		[
			'label'        => __( 'Blue Background', 'elementor' ),
			'type'         => Elementor\Controls_Manager::SWITCHER,
			'return_value' => 'blue-bg',
			'prefix_class' => 'startboy-',
		]
	);

	$section->add_control(
		'add_red_class',
		[
			'label'        => __( 'Red border', 'elementor' ),
			'type'         => Elementor\Controls_Manager::SWITCHER,
			'return_value' => 'red-border',
			'prefix_class' => 'startboy-',
		]
	);
	$section->end_controls_section();
}, 10, 2 );
```
![screen shot 2018-01-30 at 16 32 34](https://user-images.githubusercontent.com/660572/35571591-42619434-05db-11e8-8d99-3b0bd0d67a57.png)


Hope this helps.

**Comment by stratboy** [comment]
@bainternet mmm interesting. That was what I was looking for, thank you!

Some other questions then: I see you're using this syntax:

`elementor/element/{element_name}/{section_id}/after_section_end`

Is there a place where we can see a list of all the section_id parameter's possible values? Or a way to retrieve them?

Also, on docs I see things like:

```
elementor/element/{$element_name}/{$section_id}/before_section_start
elementor/element/{element_name}/{section_id}/after_section_end
```

Is there a reason why the first has dollars and the second has not?

Finally, I can see now that those hooks are probably not well linked to related docs/anchors from the top menu. I already saw them, but I thought there weren't related docs because it seems they were not linked (and I didn't scroll the whole page to see).

**Comment by stratboy** [comment]
I fixed the hook links on docs and issued a pull req.

**Comment by mohanrc13** [comment]
`add_action( 'elementor/frontend/element/before_render',function( $element ) {
	// Make sure we are in a section element
	if( 'section' !== $element->get_name() ) {
		return;
	}
	$element->add_render_attribute( '_wrapper', 'class', 'stratboy-elementor-class' );
});`

is that working? I tried it's not working.

**Comment by mohanrc13** [comment]
@bainternet 
<pre><span class="pl-s1">add_action( <span class="pl-s"><span class="pl-pds">'</span>elementor/frontend/section/before_render<span class="pl-pds">'</span></span>,<span class="pl-k">function</span>( <span class="pl-smi">$element</span> ) {</span>
<span class="pl-s1">	<span class="pl-c"><span class="pl-c">//</span> Make sure we are in a section element</span></span>
<span class="pl-s1">	<span class="pl-k">if</span>( <span class="pl-s"><span class="pl-pds">'</span>section<span class="pl-pds">'</span></span> <span class="pl-k">!</span><span class="pl-k">==</span> <span class="pl-smi">$element</span><span class="pl-k">-&gt;</span>get_name() ) {</span>
<span class="pl-s1">		<span class="pl-k">return</span>;</span>
<span class="pl-s1">	}</span>
<span class="pl-s1">	<span class="pl-smi">$element</span><span class="pl-k">-&gt;</span>add_render_attribute( <span class="pl-s"><span class="pl-pds">'</span>_wrapper<span class="pl-pds">'</span></span>, <span class="pl-s"><span class="pl-pds">'</span>class<span class="pl-pds">'</span></span>, <span class="pl-s"><span class="pl-pds">'</span>stratboy-elementor-class<span class="pl-pds">'</span></span> );</span>
<span class="pl-s1">});</span></pre>

**"elementor/frontend/section/before_render<"** It was working good.
