### ISSUE TITLE
Shortcode preview does not work

### ISSUE THREAD

**Issue by prodrigovieira** [pojome/elementor#3337]
Hello
Before when we use shortcode in the elementor it immediately appears what we add, not just a gray band indicating that it has a shortcode there.

As an example I am trying to add a shortcode to add a slider revolution, but it does not appear as before, only a gray band indicating that I am adding a shortcode, this is bad, as I want to add columns and visualize how this is getting my header.

Is this an update or is it a bug? if this functionality was removed I did not like it.

Someone to help me? Thank you very much.

**Comment by bainternet** [comment]
@prodrigovieira 

as far as we know shortcode are working just as before, can you try a native shortcode and see if that works for you, ex: `[gallery]`

**Comment by prodrigovieira** [comment]
The shortcode is working perfectly, the slider works when I click on "preview changes" in the elementor. But in the construction page of the elementor it does not appear, and this is very difficult, only a gray band appears indicating that it contains a shortcode.

That's when I add the shortcode in the elementor build page.
https://i.imgur.com/Z15ZkAz.png

Here the preview operating normally.
https://i.imgur.com/2UI6kQ6.png

I do not know if the problem is the slider revolution, I believe not because it is working normally. It is fully updated.

**Comment by prodrigovieira** [comment]
Watch the video: https://www.youtube.com/watch?v=MFg7NeLnKks

As you can see in the video that I recorded, the Shortcode no longer appears on the layout building page, only in the normal view, before the new updates worked perfectly, it was only to add the Shortcode that the preview of the slider worked.

(Ja tried disabling plugins to see if it was some conflict, but the problem continues. Slider Revolution is updated and without any problems).

I noticed that now the shortcode added a spacing at the top of the page also, this did not happen before (notice the video the space between the slider and the top of the page)

**Comment by agusmu** [comment]
If a plugin/theme has some functions those are loaded on frontend only, using `if ( ! is_admin() )` for example, then it will not be loaded on the new Elementor frontend editor. 

This is the reason why some third party shortcodes do not work on frontend editor, but works on the result & preview.

I just realized this when working on WooCommerce elements for my theme and plugin.

When I checked Elementor Pro plugin, it calls WooCommerce frontend functions `wc()->frontend_includes()` to `admin_action_elementor` hook to make WooCommerce elements on Elementor Pro work on frontend editor.

This is a big challenge for Elementor to make it compatible with many third party plugins / themes.

**Comment by prodrigovieira** [comment]
I understood, but what I find odd is that it worked perfectly before some updates, so is this because of these updates? From now on it doesn't work anymore?

This is bad, because before I could add columns on top of the shortcode and put elements, now I can not anymore.

**Comment by prodrigovieira** [comment]
I understood, but what I find odd is that it worked perfectly before some updates, so is this because of these updates? From now on it doesn't work anymore?

This is bad, because before I can add columns on top of the shortcode and put elements, now I can not anymore.

**Comment by agusmu** [comment]
It started on v1.6 release (2017-08-02): 

**Tweak: The editor loading now in the wp-admin area instead of the front-end** 

But if it doesn't work for you recently, then it could be there are some changes also on the shortcode that you are currently using, not only because of Elementor update.  

On our case, we simply don't use `if ( ! is_admin() )` anymore when loading file on our theme / plugin to make it work nicely with our lovely Elementor plugin. 

Let's just wait Elementor team responding this discussion again ;-)

**Comment by bainternet** [comment]
@prodrigovieira, @agusmu 

We try to update compatibility for 3rd party plugins but it's a lost cause, we can't possibly monitor every 3rd party for changes, so sadly, any shortcode that has its own JS/CSS and is enqueued on the front end only will probably won't display correctly in Elementor.

The best solution would be to have that 3rd party plugin write an Elementor widget.

**Comment by bretweinraub** [comment]
I am a shortcode/plugin author.   Is there any sort of recipe out there that would show me how to write a shortcode that will play nice with elementor's preview functionality?   What to do ... what not to do?

**Comment by bainternet** [comment]
@bretweinraub 

any shortcode that depends on JS will probably won't play nice in elementor, the only fail-proof solution is to actually [create an elementor widget](https://developers.elementor.com/creating-a-new-widget/) instead of a shortcode with javascript handlers.

**Comment by bretweinraub** [comment]
Yeah, I'm just rendering a panel that says "cool stuff goes here" if I'm in preview mode.   Works I guess.
