### ISSUE TITLE
Default featured image and Theme Image sizes

### ISSUE THREAD

**Issue by skalanter** [pojome/elementor#3338]
Hi dear Support,

I’m building an add-on that has a problem with the default image
I followed this link: https://github.com/pojome/elementor/tree/master/docs 
Because I use those
**namespace Widgets;**
I use instead of
**namespace Elementor;**
I having trouble in this section, Can you guide me to make up for the deficiencies that are in the add-on for default image?

```
'default' => [
     'url' => Utils :: get_placeholder_image_src (),
],
```

Also one more thing, I couldn’t be included theme image cropper size I think the below code is correct; but, I returned to above issue

`Group_Control_Image_Size::get_type(),`

I appreciate your help.

https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/27332616_1545075135575062_6494311033501010903_n.jpg?oh=62d55ac76388cb51d0c5207d5373640f&oe=5B230392

Please Note: I don’t have any Error in back-end and front-end.

Many Thanks

**Comment by norewp** [comment]
To invoke the `Utils::get_placeholder_image_src()` function all you need do is add `use Elementor\Utils` just below your unique namespace - once done then your default call should just work.

**Comment by skalanter** [comment]
I appreciate so much.
Solved very simple.
