### ISSUE TITLE
How to customize search form filters / facets

### ISSUE THREAD

**Issue by MichaelMontgomery84** [pojome/elementor#3340]
I'm looking for guidance on customizing Elementor's search form's filters/facets. Documentation on it isn't clear.

Background: 
- I'm customizing a theme with filters built with Elementor and/or WP Job Manager plugin. It's not clear which the theme is using. 
- I hit the same wall customizing filters on another theme that used WP Job Manager's filters. Understanding how the plugin's queries worked enabled me to get unstuck. It uses WP_Meta_Query part of a WP_Query. 
- Do queries with Elementor filters work like this?

I'm trying to add a range slider & clickable tag checklist inside of a drop-down.

**Comment by bainternet** [comment]
@MichaelMontgomery84 

Its not really clear what you are asking for, can you please explain better? what are you trying to do?

**Comment by MichaelMontgomery84** [comment]
Hey @bainternet: 

Sure - I'm asking for directions on customizing a search form in Elementor that has different types of filters inside a drop-down.

I'm trying to customize a search form by adding a drop-down with these filters;
- Clickable checklist 
- Visual range-slider

**Comment by bainternet** [comment]
Well, Elementor search widget only prints the search form, the query is the default native WordPress query. so you might want to look at that.

good luck.
