### ISSUE TITLE
Slider Widget fixed images

### ISSUE THREAD

**Issue by bodhi1970** [pojome/elementor#3342]
I was looking for an option to fix the images in the slider widget and couldn't find that. Would be great to have that to select in the slider options. I did it with CSS.
.slick-slide-bg {background-attachment:fixed;}

**Comment by bainternet** [comment]
@bodhi1970 

what do you mean by fixed images in a slider?

**Comment by bodhi1970** [comment]
Now the images scroll with the rest of the content but my client wanted them fixed like I can fix also the background-image of a section.

**Comment by bainternet** [comment]
You mean like Parallax?
can you provide an example?

**Comment by bodhi1970** [comment]
I have done that here: http://stenzco.myhostpoint.ch/referenzen/

**Comment by bainternet** [comment]
@bodhi1970 

Yea, well that is called parallax and sadly, currently, there is no official way to do it in elementor without a 3rd party plugin or custom CSS.

I merged this issue with  #72, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
