### ISSUE TITLE
More control over Ken Burns effect

### ISSUE THREAD

**Issue by michaelnorthern** [pojome/elementor#3344]
Hi, I'd like to see more control over the Ken Burns effect in the Slider element, at least speed of the in / out motion, but also X/Y translation and rotation.  As others have said, the slide transitions do seem rough relative to more mature products. Great effort overall, just needs some refinement and a few extra controls to make using the Ken Burns effect worthwhile.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Lokavidu** [comment]
+1, the effect is practically not usable because of no controls

**Comment by ladyViolet** [comment]
Here's a workaround for at least little bit of control.. for those who are still searching for a solution:

selector .elementor-ken-burns {
  transition-duration: 30s;
}

you can add this to the custom css of the slides.. with increasing or decreasing the transition duration there's some sort of control over how quick & far the effect will zoom in before the next slide shows.
