### ISSUE TITLE
Feature Request 1388px and 4k/5k resolution need added to responsive view settings

### ISSUE THREAD

**Issue by joshallen73** [pojome/elementor#3347]
## Description

 15 inch laptops use 1388 width or they are 3840 now, and most comps coming out are 4k. Imacs are 5k...Please make this an important feature because I cant adjust for 1388 res laptops or 4k like a 15" lenovo yoga, microsoft surface, or apple...

## Steps to reproduce

designing in full width modes set to elementor desktop view then looking at site in 4k or 15" laptop

## Environment

 google chrome and microsoft edge - newest releases

**Comment by drank** [comment]
This seems related - https://github.com/pojome/elementor/issues/78

**Comment by joshallen73** [comment]
oh ok well sort of - thanks braintree for moving my original post to that thread...

sorry i thought it was deleted or lost...

i really wanted to see these responsive settings added to the mobile, tablet, and desktop circles...not sure why there isnt a laptop view or large desktop 4k monitor...useful while designing in elementor to remeber those settings...not just breakpoints into css code.

**Comment by bainternet** [comment]
closing duplicate.

thanks.
