### ISSUE TITLE
Section or Column UI

### ISSUE THREAD

**Issue by badcat** [pojome/elementor#335]
The UI for a Section seems it should show "Section" before the default "Column".  In the current version, the hierarchy makes it appear that the Column is holding the Section.  These should be reversed, no?
![section](https://cloud.githubusercontent.com/assets/26096/17200877/f5239b7c-5456-11e6-9bca-56c2d3df4ed3.png)

**Comment by FahadKhalique** [comment]
Agreed... and also a column next to a column should not show "Section" as it is the same section.

**Comment by yehudah** [comment]
Thanks for the great feedback.

Our UI team will reconsider this issues.

**Comment by paaljoachim** [comment]
Btw
It would be good with an outline similar to a thin border around the column when it is selected and around the section when that is selected. To visually also see where the column and section is located.

**Comment by arielk** [comment]
Elementor 1.5 RC2 has already been released with this enhancement, please check this issue #1827

Thanks for the feedback!
