### ISSUE TITLE
Login Widget Additional Options Problems

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#3350]
Is not customizable the login widget, heres some improvements:

- It's not possible to translate "remember" and "lost passwords"

- Option to add an Icon inside the placeholder (left and right);

- Choose the order of "remember" and "lost passwords"

**Comment by bainternet** [comment]
@silvioghedin 

* "Remember me" and "Lost password" are translatable via the Po file.
* Placeholders can hold HTML (like Icon), only strings!! so you mean prefix icon which can be done via Custom CSS (`:before`)

So currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the suggestions.
