### ISSUE TITLE
Font not loaded in edit mode if widget template

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#3352]
Hi. 
1. Create page and inset Heading widget (select font Ubuntu)
1.1 save as template as my_template
2. Create page and insert widget Template
3. Select in widget a my_template
4. We see that the font is not loaded into the editor (in preview mode loaded font)

!! The decision through the ass
4.1. We see that the font is not loaded into the editor
5. inset Heading widget (select font Ubuntu)
6. We see how the fonts are loaded !!!

test a last elementor an last firefox browser

**Comment by bainternet** [comment]
Thanks for reporting.
