### ISSUE TITLE
[issue] sections background and overlay hover

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#3353]
experiencing some weird bevahiour with hover for sections...

when defining a background hover state with simple color everything works as expexted including the transition (+duration).
theres no transition duration when applying an image, same for gradient. simply pops in suddenly.
basically same issue when applying a hover via background overlay panel. only simple color overlay has transition. even more confusing - for gradient overlay the transition seems to work backwards... theres no fade in, but the the gradient pops in full color and then slowly fades to the set transparency.

would be glad if you may have a look.

enviroment:
actual elemenor/pro
generatepress theme
latest firefox

**Comment by dasigna** [comment]
currently not possible - but i could create a test page and give you access??

**Comment by dasigna** [comment]
credentials are on the way.

**Comment by bainternet** [comment]
@dasigna 

Please contact our support and see if they can help you.

**Comment by dasigna** [comment]
... already done and has been confirmed there is an issue with gradient hover overlay.
