### ISSUE TITLE
[issue] Masonry in portfolio strange look

### ISSUE THREAD

**Issue by bodhi1970** [pojome/elementor#3355]
When ever I load the page with a portfolio on it looks totally different. Sometimes the masonry does not put the bricks together but builds a long column. See screenshots. It is not always like this but this does not look very nice. Same behaviour on Safari and Firefox.

![screen shot 2018-01-31 at 12 47 55](https://user-images.githubusercontent.com/5292941/35621690-95dd4d6a-0685-11e8-802f-a2f67cb46a14.jpg)

![screen shot 2018-01-31 at 08 51 57](https://user-images.githubusercontent.com/5292941/35621691-95f85c54-0685-11e8-8712-33cf444c2390.jpg)

**Comment by bainternet** [comment]
@bodhi1970 

Do you see any Javascript Errors in the console?

**Comment by bodhi1970** [comment]
Only one regarding the preloaded fonts. Could that be related?
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (MyFontsWebfontsKit.css, line 0)

**Comment by bainternet** [comment]
well we cant replicate,  please contact our support and see how they can help you.
support@elementor.com
