### ISSUE TITLE
When clicking "edit" button, it starts dragging widget (Chrome)

### ISSUE THREAD

**Issue by knapcio** [pojome/elementor#3363]
Almost always when I want to click "edit" button (appearing in right corner on hover), It starts dragging widget instead just clicking button. I need to try like 10 times, to finally accidentially get to edit widget.
Some people also mentioned about in on facebook group.

**Comment by knapcio** [comment]
I also see, that also from time to time the bug change. In that case, I can click edit button, but whule I want to drag something it starts selecting (highlighting) . These bugs really kill workflow.

**Comment by bainternet** [comment]
@knapcio we can't replicate this, please contact our support and see if they can help you.

support@elementor.com
