### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3367]
## Description

Is there a way to add third party javascript in the editor on an html element without it actually being rendered until the page is saved? 

This goes back to the document.write issue I have been having.

**Comment by bainternet** [comment]
not sure you can.

what are you trying to do? maybe we can help...

**Comment by NTuneMusic** [comment]
Thank you!

We have a rental application that is hosted on an SDrive account with Coffeecup. It uses a small amount of code to render the appliation on the page. But because it uses document.write in the code, that causes the rest of my page in Elementor to disappear during editing.

If there was a way that Elementor didn't render the code from the html element until after publishing, that would help. Maybe if there was a way to toggle the external code on/off during editing, the issue would be workable while the page is being finished.

I really have no idea what I am talking about, but I can see it in my head.

**Comment by bainternet** [comment]
Well,  you can create your own elementor widget and in your `render` method check if you are in edit mode or not.

other then that is to include your JavaScript code outside of elementor for example on `wp_footer` action.

Or modify the code to not use the eval `document.write`
