### ISSUE TITLE
A way to truly ensure css overrides are fully mirrored in admin preview

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3369]
Hi, referencing this other issue: #2025 

Is there any way to 100% ensure  that custom css will fully override elementor's one in admin preview? This is a crucial thing if we want our clients see exactly what the frontend will be while editing the pages in elementor's admin.

Currently, there are times when parts of the theme's css isn't fully mirrored on admin. This happens randomly so no way to reliably suggest steps to reproduce.

Sometimes is fixed by hitting the update button and then reload the page, some other times I must manually regenerating elementors css (from admin tools), some other times this isn't enough, and nothing seems to fix the issue. Maybe it has something to do with css files that aren't the main style.css. I usually load a main style file and then (after) one more css file where further custom things are needed.

Maybe you could check the way your system merges additional files (other than style.css).

**Comment by bainternet** [comment]
please provide steps to replicate.

**Comment by stratboy** [comment]
Currently, there are times when parts of the theme's css isn't fully mirrored on admin. This happens randomly so no way to reliably suggest steps to reproduce.

**Comment by bainternet** [comment]
@stratboy 

First Elementor doesn't merge any CSS files. other than that when you hit update the CSS file for that page is deleted and the next time you view/preview it is generated on the fly.

On the editor, we don't load that CSS file at all, we use inline styles. so any theme related CSS that it is not loaded is probably due to the way its enqueued maybe in `( !is_admin() )` condition. so check and make sure that it is also enqueued for the editor which is in the admin.

**Comment by stratboy** [comment]
Adding a related part of my settings. Something wrong?
Thing is, the problem appears randomly, so I don't think it's setting-related. Also, and this is even more important, what doesn't work is NOT the entire css file, but only some rules. Again, random. But anyway, here's some current code (runs always fine in frontend, doesn't fully run sometimes in elementor's admin):

```php
add_action('wp_enqueue_scripts', 'add_scripts_and_styles', 11);
//   [...]

function add_scripts_and_styles() {
  if(is_page_template('essiccatoi.php')){
    wp_enqueue_style('essiccatoi_style',CSSPATH . '/essiccatoi.css');
    wp_enqueue_script('essiccatoi_js',JSPATH . '/essiccatoi-min.js',array('jquery'),false,true);

    wp_localize_script('essiccatoi_js', 'php_data', array(
      'ajax_url' => admin_url() . 'admin-ajax.php'
    ));
  }

//   [...]
}//end add_scripts
```

**Comment by samjco** [comment]
This works for me:

```
function add_to_editor_css() {
//global $post;
//wp_dequeue_style('elementor-pro');
//wp_deregister_style('elementor-pro');
   
 $custom_css = "
:link, :visited {
text-decoration: none;
}
ul, ol {
list-style: none;
}
h1, h2, h3, h4, h5, h6, pre, code, p {
font-size: inherit;
}
ul, ol, dl, li, dt, dd, h1, h2, h3, h4, h5, h6, pre, 
form, body, html, p, blockquote, fieldset, input {
padding: inherit;
margin: inherit;
}
a img, :link img, :visited img {
border: inherit;
}
address {
font-style: normal;
}

.elementor-button {
display:inline-block !important;
/*line-height:inherit !important;*/
background-color:inherit !important;
font-size:13px;
border-radius:inherit !important;
color:inherit !important;
/*paddiing: inherit;*/
fill:inherit !important;
letter-spacing: 2px;
text-align:inherit !important;
white-space: nowrap !important;
vertical-align: middle !important;
-webkit-user-select: none !important;
-moz-user-select: none !important;
-ms-user-select: none !important;
user-select: none !important;
border: 1px solid transparent;
white-space: nowrap !important;
vertical-align: middle !important;
-webkit-user-select: none !important;
-moz-user-select: none !important;
-ms-user-select: none !important;
user-select: none !important;
-moz-transition: color 0.2s ease-in-out, background-color 0.2s ease-in-out, border-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out, -webkit-box-shadow 0.2s ease-in-out !important;
-webkit-transition: color 0.2s ease-in-out, background-color 0.2s ease-in-out, border-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out, -webkit-box-shadow 0.2s ease-in-out !important;
transition: color 0.2s ease-in-out, background-color 0.2s ease-in-out, border-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out, -webkit-box-shadow 0.2s ease-in-out !important;
box-shadow: 0px 12px 30px -12px rgba(0,0,0,0.3) !important;
font-weight: 500;
text-transform: uppercase !important;
height: fit-content !important;
}

.elementor-widget-button {
height: fit-content !important;
border-radius: 4px;
margin-right: 0.25rem !important;
}

.elementor-widget-button p, .elementor-widget-button br {
display: none;
}

.elementor-widget-wrap > .elementor-element {
width: fit-content;
float: left;
}

.elementor-widget-image a img[src$='.svg'] {
width: 400px;
}	
";

 wp_add_inline_style( 'elementor-pro', $custom_css );
}

add_action( 'wp_enqueue_scripts', 'add_to_editor_css', PHP_INT_MAX );
```

**Comment by stratboy** [comment]
I do not use elementor anymore.
