### ISSUE TITLE
2 date inputs, starting date and ending date

### ISSUE THREAD

**Issue by johntunnel** [pojome/elementor#3370]
Hi
I have CHECKIN date field and CHECKOUT date field. CHECKIN should always be smaller date value than CHECKOUT. To control this,
whenever CHECKIN is selected -> CHECKOUT minDate = CHECKIN,
and whenever CHECKOUT is selected -> CHECKIN maxDate = CHECKOUT

I tried below script, but it does not work:
```JAVASCRIPT

var min = document.querySelector("#form-field-CHECKIN")._flatpickr;

var max = document.querySelector("#form-field-CHECKOUT")._flatpickr;

max.config.onChange.push(function (selectedDates, dateStr, instance ) {
min.set('maxDate', dateStr );
});
min.config.onChange.push(function (selectedDates, dateStr, instance ) {
max.set('minDate', dateStr );
});
```
webpage is http://wordpress-132513-381868.cloudwaysapps.com/
Any suggestions?

Regards
John

**Comment by bainternet** [comment]
You have a JavaScript error which indicates you are running the code before you should, try wrapping it with `onload` or `jQuery(document).ready` ex:

```JavaScript
jQuery(document)ready(function($){
    var min = document.querySelector("#form-field-CHECKIN")._flatpickr;
    var max = document.querySelector("#form-field-CHECKOUT")._flatpickr;

    max.config.onChange.push(function (selectedDates, dateStr, instance ) {
        min.set('maxDate', dateStr );
    });
    min.config.onChange.push(function (selectedDates, dateStr, instance ) {
        max.set('minDate', dateStr );
    });
});
