### ISSUE TITLE
GREAT AWESOME FEATURE REQUEST: CLIENT LEVEL ACCESS to just text editing and image changes.

### ISSUE THREAD

**Issue by joshallen73** [pojome/elementor#3371]
IM sorry if this has been brought up - Beaver Builder has a similar function I think but would be so awesome if you could Lock/restrict edit access through wordpress level user - to just let end user clients only edit text blocks and certain features like gallery, or single images. This would give them a great sense of some control and help us sell more elementor sites! How hard would this be. I would help finance this even! 

## Description

 WHen clients want to edit thier own stuff they actually have access to all elementor controls and could screw up anything :)

## Environment

 Latest Enviroment!

KEEP UP THE AWESOME WORK I KNOW YOUR SWAMPED!

**Comment by ppweb** [comment]
This would be beyond AWESOME!

**Comment by silvioghedin** [comment]
+1

**Comment by dasigna** [comment]
according to elementor team this is something already on the roadmap ref. #3221 :)

**Comment by bainternet** [comment]
@dasigna is correct.

I merged this issue with  #3221, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
