### ISSUE TITLE
NEW FEATURE REQUEST: WeChat & Weibo Social Share buttons for Pro

### ISSUE THREAD

**Issue by Saxter1** [pojome/elementor#3372]
**Idea.**
I'd like to pitch the idea of getting a WeChat and Sina Weibo social share button as part of the Elementor Pro social share suite.

**Why?**
Because Elementor is ahead of the game as an innovator
Because it is estimated there are between 60 - 70 million Chinese nationals residing outside of China and growing. Last concrete figures were 50 mil (2012)

**The Chinese are social media and smartphone crazy!!!** However due to govt restrictions they use their own social networks. The two main networks that are appropriate for sharing content on are:
WeChat. 800+ Million daily users
Weibo. 340m monthly users

Weibo is a bit like a mix of Twitter and Facebook where-as WeChat is quite unique. A mix of Instant Messaging, shopping, gaming and WeChat 'Moments'. WeChat is personal - friends/ family etc - and has huge engagement and market share.

**Proposal.**
Wechat have published figures that **70 million of their users reside outside of China.** Roughly 20 mil of whom aren't even Chinese! Weibo's reach is smaller but when combined with WeChat it wouldn't be far away from 90 mil (and growing) who use these platforms.

It's really important to note that because their peer networks are already on these platforms most Chinese ex-pats keep using these rather than migrate over to Twitter/ Faecbook etc...

I propose to Elementor to trump the competition again by including a WeChat or both WC and Weibo share button option on your Pro offering. It would enable thousands of bloggers and websites to get their content easily shared with the click of a smartphone button to a brand-new-potential market in their home country. I have looked and seen that there are already WeChat & Weibo plug-ins out there if that helps development.

Cheers!

**Comment by bainternet** [comment]
@Saxter1 

Do you have a link to docs/API for a web share button for these networks?

**Comment by Saxter1** [comment]
Hi Bainternet,
I can't find anything current for Weibo (the much smaller of the two). There are plug ins but almost all seem outdated and not updated.

I did find this from about 6 months ago about a Wechat API thought > https://jmsliu.com/4221/connect-wechat-with-your-wordpress-website.html

Any help?
Cheers

**Comment by bainternet** [comment]
@Saxter1 

Sadly, not really, it's not what we need, and We did try to look for something but it seems like they (Wechat) don't support websites for sharing, as for Weibo again it's hard to find something official. so I'll close this for now until ......


thanks for the suggestion.

**Comment by StevePuts** [comment]
Please implement this asap, it's like one billion people don't exist to Elementor...
Here's how to do it:

For weibo:
https://service.weibo.com/share/share.php?url=https://www.woidmo.org/alerts/salmonellosis-china-hong-kong/&title=Salmonellosis+%26%238211%3B+Hong+Kong

For Wechat:
weixin://dl/chat?text=https://www.woidmo.org/alerts/salmonellosis-china-hong-kong/
