### ISSUE TITLE
Mobile menu is going full and lightbox video doenst work.

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#3373]
Hello the menu on my phone is getting full width and the video donsnt appear, if I remove the lightbox option it appears on mobile:

http://bbmarketing.cl/

**Comment by bainternet** [comment]
?

please provide a steps to replicate.

**Comment by silvioghedin** [comment]
http://prntscr.com/ibfshf

http://prntscr.com/ibfstd

**Comment by bainternet** [comment]
@silvioghedin 

we can't replicate, please contact our support and see if they can help you.

support@elementor.com
