### ISSUE TITLE
Using Font Awesome to create an own widget

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#3375]
I'm trying to create an own Elementor widget and use font awesome for the icon. I've choosen a new heading icon (https://fontawesome.com/icons/heading?style=solid), fas fa-heading. It doesn't show anything. Are you not supporting the new icons from font awesome? 
![grafik](https://user-images.githubusercontent.com/14095280/35772051-b57c029c-0937-11e8-9808-6f2125938f1d.png)

**Comment by bainternet** [comment]
@HelmutGoebel 

currently, we support and use FontAwesome 4.7 but we have plans to upgrade to 5 and we actually have our own icon in FA5 https://fontawesome.com/icons/elementor?style=brands

**Comment by HelmutGoebel** [comment]
Thanks for your quick answer. I've seen that. Could provide us with a list of your own icons? Are there more than the ones used for the todays widgets?

**Comment by arielk** [comment]
please see the icons in this link: https://github.com/pojome/elementor-icons

**Comment by bainternet** [comment]
@HelmutGoebel 

You can use any of the Icons available in E-icons ( which is what @arielk linked above ), or any of the FontAwesome [4.7 icons](https://fontawesome.com/v4.7.0/icons/). Examples:

```PHP
//font-awesome
public function get_icon() {
        return 'fa fa-header';
}

//e-icons
public function get_icon() {
	return 'eicon-type-tool';
}
``` 

To see the full list of E-icons you can download the [elementor-icons](https://github.com/pojome/elementor-icons) repo and open the index.html file.

**Comment by NgJason** [comment]
I tried several icons with the latest elementor. it doesn't work. It appears blank.
	
public function get_icon() {
		return 'fa fa-object-ungroup';
	}
