### ISSUE TITLE
[workflow improvement] Drag and drop settings/preferences on other modules

### ISSUE THREAD

**Issue by elasticeye** [pojome/elementor#3376]
[WORKFLOW IMPROVEMENT]

What if you had 3 text boxes next to each other, and you want to increase text size and make the font bold on all 3. What if, you could change the first text box, and just drag and drop the new preferences/settings from the text-box you edited, and over to the other two boxes. 
That would be awesome ;)

**Comment by bainternet** [comment]
@elasticeye 

You can do that by cloning the text widget after you have set its style.

**Comment by elasticeye** [comment]
Yes, but with alot of different text in each box, you also need to insert the text again.
