### ISSUE TITLE
Add "edit last post using Elementor"

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#3379]
I frequently write posts using Elementor over a period of several days, often returning to the same draft. It would simplify things if there were an easy way to go directly to that posting from the main admin dashboard (or even from the URL itself).
For example, my dashboard has a Quick Draft section, within which there is a list of links to "Your recent drafts". However, clicking on one of those links does not use Elementor. If there were similar functionality available, either under the Elementor menu or in a block on the dashboard, this would be very welcome.

**Comment by bainternet** [comment]
Thanks, we will try to add this teak in the next version

**Comment by bainternet** [comment]
Added in 1.9.4

Thanks for the suggestion.
