### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TTS12** [pojome/elementor#3380]
Hi,

I have built an e-commerce website using Elementor Pro. I would like to feature some of my products on my homepage, and I would like them to appear on one single line, and for people to be able to scroll from left to right (or vice-verca) so they can have easy access to more products. This is a very common feature on most big ecommerce homepages, and it would be very useful to add to Elementor Pro.

Thanks in advance for taking this into consideration.

Best

**Comment by bainternet** [comment]
I merged this issue with  #219, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.11! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
