### ISSUE TITLE
[Future Feature Request]

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#3381]
Taking a long shot here hence marking this as a "Future Feature Request".

If at all possible and this might already be on your roadmap for the theme builder (but no harm in asking) - it would be totally awesome to have any widgetised area on a given page/post template be exposed in editor view just like we have in the Customizer. Such functionality would allow for insertion of pre-built sections via the Template Module or any of the available widgets.

This can be further extended to exposing the Site Title/Description for basic manipulation via either the Global and/or Document Settings. The Customizer handles this by way of adding a "Pencil" pointer against an item and when clicked the relevant panel opens up for editing/manipulation - themes could then add in support via something like `add_theme_support( 'elementor', apply_filters( 'themename_elementor_args', array( // arguments here ) );`  function

Even if there is no direct manipulation/editing options it will still be an awesome addition just to be able to add widgets/templates which will stream line the workflow and avoid jumping to multiple places in the site build process :) 

Look forward to tour view on this and hope that can done in the future if not sooner.

Zulf

**Comment by bainternet** [comment]
@norewp 

Its already in the working :)
