### ISSUE TITLE
shortcodes in text-editor

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3388]
Feature request: I know there's already a shortcodes widget, but I'd really like the ability to put shortcodes in text editor, just like default wp behaviour.

Regards

**Comment by bainternet** [comment]
@stratboy 

You can, already.

**Comment by stratboy** [comment]
Yes now I see. It stil has some issues with live rendering, though.

**Comment by alexnl** [comment]
I'm seeing an issue with this when using the text editor in a toggle tab:
![image](https://user-images.githubusercontent.com/317587/74188551-a9377280-4c1c-11ea-9ea5-dde80a0738a0.png)
