### ISSUE TITLE
Use field Custom ID for webhook post data with Form

### ISSUE THREAD

**Issue by denishacquin** [pojome/elementor#3389]
Hello,

When using the Webhook action with the Form in the Pro version (without checking Advanced form data), I think it would make more sense to user the field Custom ID's as array keys instead of the labels.

I was having this:

Array
(
    [Prénom] => John
    [Nom] => Smith
    [Email] => ****@gmail.com
    [form_id] => 9de22fa
    [form_name] => New Form
)

So I needed to change the labels to match the keys of the API I'm posting the information to, for instance of "Prénom" (my label) I had to write "forename" (API key, no choice here).

Not only is this not really logical IMO, it also prevents me from displaying my labels since they're not pretty.

Regards.

**Comment by bainternet** [comment]
@denishacquin 

use this:
```PHP
add_action( 'elementor_pro/forms/new_record', function( $record ) {
	// Make sure this is the correct form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	$submmited_fields = $record->get( 'fields' );


	$fields = [];
	foreach ( $submmited_fields as $field_id => $field ) {
		$field[ $field_id ] = $field['value'];
	}
	// Add subscriber
	wp_remote_post( 'HTTPS://YOUR_WEBHOOK_URL', [
		'body' => $fields,
	]);
});
```
