### ISSUE TITLE
Yikes Forms are displayed inline

### ISSUE THREAD

**Issue by philippelarcher** [pojome/elementor#339]
This is what I should have on the website and what I have on the editor:
![image](https://cloud.githubusercontent.com/assets/18685558/17217058/b8591a1a-54eb-11e6-8112-3f8ef593b731.png)

This is the result on the website:
![image](https://cloud.githubusercontent.com/assets/18685558/17217038/aa92f130-54eb-11e6-83bf-462059b9ad06.png)

The inline option of Yikes Forms is disabled.

**Comment by yehudah** [comment]
Hi,

If you mean this plugin:
https://wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/

I have test it, just added the fields and used the plugin widget.

![image](https://cloud.githubusercontent.com/assets/1655373/17288466/f4efff1c-57dd-11e6-9876-66e8190a8e33.png)

**Comment by philippelarcher** [comment]
Yes this plugin, with Storefront theme.

**Comment by arielk** [comment]
We tested it again recently, seems to be working well. Feel free to reopen the issue if you're having any trouble again.
