### ISSUE TITLE
Allow option to show admin toolbar while editing with Elementor

### ISSUE THREAD

**Issue by bigwilliam** [pojome/elementor#3392]
While editing a page in elementor, I need to see the wp-admin bar because we have custom links there which our clients need to use. It would be nice to have the ability to toggle the admin bar on or off.
![wpadminbar](https://user-images.githubusercontent.com/245141/35820317-78437fe6-0a62-11e8-970a-5adce7970095.png)

**Comment by bainternet** [comment]
This won't work because elementor suppresses all link in editor.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
