### ISSUE TITLE
new feature request: title link

### ISSUE THREAD

**Issue by latoquadrato** [pojome/elementor#3394]
I need to insert the title link on an image (comic that appears when I stop on an image)
![titlelink](https://user-images.githubusercontent.com/36173817/35830703-68c24db2-0ac7-11e8-8a8f-ba7c57f6a14f.jpg)

**Comment by bainternet** [comment]
@latoquadrato 

The image title attribute was removed by [WordPress core in 3.5](https://core.trac.wordpress.org/ticket/18984) if you want them back there are 3rd party plugins that do that for you, [like this one](https://wordpress.org/plugins/restore-image-title/).
