### ISSUE TITLE
"NEW" Vital Feature Request!

### ISSUE THREAD

**Issue by jimg28** [pojome/elementor#3395]
Hello Everyone! First of all i want to congratulate Elementor team for the incredible work they are doing!

Now on point. In my opinion there is a vital feature that is missing for the editor.

This is the ability to trigger a video lightbox from a button. In modern web design it is a very often situation in order to gain some space or to make the overall design come together. I believe many will agree with me on that.

Actually you have already apllied that concept in one of your demo sites:

![sample](https://user-images.githubusercontent.com/36177033/35836012-9d5cfd96-0ae6-11e8-884b-2521dc917bbb.png)

For now the button doesn't do anything but how awesome would be to trigger a video lightbox! Hope I see this feature in the near future, thanks!!!

**Comment by bainternet** [comment]
You can already do that with very little custom JavaScript,  just give you button a CSS class you can catch, link to `#` so you wont really get directed to a different place and trigger the lightbox on that click, for example lets say that my button has a class named `play-video` then my JS code will be something like:

```JAVASCRIPT
jQuery( document ).ready(function($){
    $('.play-video').on('click',function( event ){
        event.preventDefault();
        elementorFrontend.utils.lightbox.showModal({
	        url: 'https://www.youtube.com/embed/9uOETcuFjbE?feature=oembed&rel=0&controls=0&showinfo=0&mute=0&wmode=opaque',
        	videoAspectRatio: '169',
	        type: 'video',
        });
    });
});
```
hope this helps.
ref: #2505 , #2984, #1651

**Comment by ItsmePNP** [comment]
```
jQuery( document ).ready(function($){
 var vimeoUrl = jQuery('.play-video').find('a').attr('href');
var pattern1 = /(?:http?s?:\/\/)?(?:www\.)?(?:vimeo\.com)\/?(.+)/g;
var replacement =  "//player.vimeo.com/video/$1;"
var embeddableUrl = vimeoUrl.replace(pattern1, replacement);
jQuery('.play-video').find('a').attr("href", embeddableUrl)
    $('.play-video').on('click',function( event ){
        event.preventDefault();
        elementorFrontend.utils.lightbox.showModal({
            url:embeddableUrl,
            videoAspectRatio: '169',
            type: 'video',
        });
    });
});
```

So I wanted to use your code to make my Vimeo lightbox dynamically using AFC. It's for a single Portfolio page. I have an icon, that gets URL from Custom field over feature image. `;&amp;autoplay=1`. It would have worked if this wasn't there in Iframe.

**Comment by ItsmePNP** [comment]
> ```
> jQuery( document ).ready(function($){
>  var vimeoUrl = jQuery('.play-video').find('a').attr('href');
> var pattern1 = /(?:http?s?:\/\/)?(?:www\.)?(?:vimeo\.com)\/?(.+)/g;
> var replacement =  "//player.vimeo.com/video/$1;"
> var embeddableUrl = vimeoUrl.replace(pattern1, replacement);
> jQuery('.play-video').find('a').attr("href", embeddableUrl)
>     $('.play-video').on('click',function( event ){
>         event.preventDefault();
>         elementorFrontend.utils.lightbox.showModal({
>             url:embeddableUrl,
>             videoAspectRatio: '169',
>             type: 'video',
>         });
>     });
> });
> ```
> 
> So I wanted to use your code to make my Vimeo lightbox dynamically using AFC. It's for a single Portfolio page. I have an icon, that gets URL from Custom field over feature image. `;&amp;autoplay=1`. It would have worked if this wasn't there in Iframe.

`var replacement =  "//player.vimeo.com/video/$1?"; ` solved my issue

**Comment by Prankscl** [comment]
this works for self hosted videos?

**Comment by ItsmePNP** [comment]
No.

**Comment by stevegiorgi** [comment]
Is there an update for this?  

Uncaught TypeError: elementorFrontend.utils.lightbox.showModal is not a function

It appears to be a promise but using it that way with then does not appear to work.
