### ISSUE TITLE
Text Editor - Undo Bug ?

### ISSUE THREAD

**Issue by mojoomla** [pojome/elementor#340]
When I undo any text formatting in the editor window on the left, it is not reflected in the Elementor render window on the right until the page is saved and viewed separately.

**Comment by yehudah** [comment]
I can confirm it's a bug.

Thanks

**Comment by mojoomla** [comment]
One more bug here is that when I switch from visual editing mode to text mode for the editor, the entire paragraphing and formatting of the mixed text and image contents of the block gets destroyed.  Please test it and confirm. Thanks

**Comment by yehudah** [comment]
Hi,

Sorry, working for me.

![anim](https://cloud.githubusercontent.com/assets/1655373/17289593/0aeb5faa-57e3-11e6-9245-e70ce66c27b7.gif)

**Comment by mojoomla** [comment]
Did you try editing after switching to text mode ?
Try typing a character in the text mode editor window and see.

**Comment by mojoomla** [comment]
please see this video screencast.
https://youtu.be/4CVAQPigldc

Can you tell me how you recorded the sscreencast that you embedded in your  previous comment. What file format did you use so that it could be attached to the post ?  what software did you use to grab it ?

**Comment by arielk** [comment]
1. resolved https://github.com/cobicarmel/elementor/commit/51f04ada0cc8d5e935d21ae0cc08330b29fb6aeb

2. It's not a bug, it's just rendering of the caption shortcode. Please go to front and you will see it well
