### ISSUE TITLE
Elementor anchor links are not updated

### ISSUE THREAD

**Issue by ivan133** [pojome/elementor#3400]
I have a site with elementor buttons leading to elementor anchors
Here is example: http://sandbox2.growsite.co.il/anchor-test/
To reproduce do the following:
1. Open new tab
1.  Open page http://sandbox2.growsite.co.il/anchor-test/
2. Press button "Go to anchor"
3. You will be smoothly scrolled to "Now press back button" header
4. Now press back button on browser
5. You will be redirected empty tab

I'm pretty sure it happens because of "handleAnchorLinks" function in /elementor/assets/js/frontend.js

**Comment by ivan133** [comment]
Here is example how raw html anchors work 
http://sandbox2.growsite.co.il/anchor-test-raw/

So if only we can update  urls hash updated it would be cool

**Comment by bainternet** [comment]
@ivan133 

I see what you mean, Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
