### ISSUE TITLE
Position of the Edit with Elementor button and ACF's custom meta box

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3405]
When I insert custom meta box using ACF and select position "High (after title)", it's inserted after the  Edit with Elementor button:

![obrazek](https://user-images.githubusercontent.com/5634870/35869149-b19eceb0-0b5e-11e8-8319-8e411f1942ed.png)

Moreover, when the Elementor editing is active, the custom meta field is on even a lower position (optically, I can imagine that this is actually the very same "button"):

![obrazek](https://user-images.githubusercontent.com/5634870/35868855-0de773a8-0b5e-11e8-9e10-116bf0b7bc75.png)

Any suggestions on how to move the Elementor button to lower position (or custom meta on higher)?
No big deal, though...

**Comment by bainternet** [comment]
@black-eye 
If I'm not wrong then the button is inserted using the `edit_form_after_title` action hook and the ACF field probably uses the same hook.

And I do know that we use the default priority which is 10 so anything lower then that should run first.
