### ISSUE TITLE
Separator issue in group control with popover

### ISSUE THREAD

**Issue by reardestani** [pojome/elementor#3408]
## Description

Not possible to add **separator** in group control that has popover like **Box shadow**. 

With following codes:
```
$this->add_responsive_control(
	'border_radius',
	[
		'label' => __( 'Border Radius', 'raven' ),
		'type' => 'dimensions',
		'size_units' => [ 'px', '%' ],
		'selectors' => [
			'{{WRAPPER}} .item' => 'border-radius: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};',
		],
	]
);

$this->add_group_control(
	'box-shadow',
	[
		'name' => 'box_shadow',
		'exclude' => [
			'box_shadow_position',
		],
		'separator' => 'before',
		'selector' => '{{WRAPPER}} .item',
	]
);
```

**Expectation:** http://take.ms/AD3uW
**Result:** http://take.ms/1fccw

**Comment by bainternet** [comment]
@reardestani 

You are correct, currently, the `separator` feature is not supported for popover controls group, but we will look into it in the future if we see a large demand for it.


For now, you can try to put the separator on the control before it and set it to after, maybe that will work.
Thanks for the feedback.
