### ISSUE TITLE
Author Box Widget to be made dynamic (Global Widget usage envisioned)

### ISSUE THREAD

**Issue by IDESIGNSTUDIO** [pojome/elementor#3409]
Maybe, I am missing something, but I couldn't make a global widget with dynamic Author Box info.

This means that I want to put the widget in the Sidebar of the Single Posts / or insert it via shrotcode, to show the author of the current post.

It always shows the author, who created the global widget....

Any help on this?

**Comment by KingYes** [comment]
Fixed by this PR: https://github.com/pojome/elementor/pull/3427
