### ISSUE TITLE
Not able to edit already added contents and elements

### ISSUE THREAD

**Issue by qadriinfotech** [pojome/elementor#341]
I recently updated my plugin to the latest version and suddenly all my pages stopped working. I am not able to edit contents which I already added before. Although, I am able to add and edit new element and contents. 
Is it something for you to check or I am doing wrong?

**Comment by yehudah** [comment]
Before you edit exiting elements, can you open the console, try to edit and see if any error show on the console ?

![console](https://cloud.githubusercontent.com/assets/1655373/17288278/e548d2e2-57dc-11e6-85cc-694cb22b1303.gif)

**Comment by arielk** [comment]
Hi @qadriinfotech 
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by qadriinfotech** [comment]
Hi Arielk,

Sorry for being late to reply you. Actually, the issue was fixed automatically after some time. Possibly a caching issue?

**Comment by arielk** [comment]
Possibly...
