### ISSUE TITLE
In the latest version there is an padding in the section which should be removed.

### ISSUE THREAD

**Issue by syuzanna-a** [pojome/elementor#3414]
![elementor-bug](https://user-images.githubusercontent.com/34867550/35922006-c87d6b96-0c35-11e8-9a77-819ab204d82f.png)

We have imported one of the free templates in the library and here it is. On the bottom, there was an unnecessary padding for each section which is not possible to remove all options are 0 while it still there.

**Comment by norewp** [comment]
Not seeing the extra padding on my install - have you ruled out 3rd party addons and the theme?

**Comment by syuzanna-a** [comment]
Yes, but in the past, all these are the same and this section worked perfectly. It happened after the update.

**Comment by bainternet** [comment]
@syuzanna-a 

we can't replicate. please try using a native twentyxxxx theme.
