### ISSUE TITLE
smooth-scroll plugin? 

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3417]
Hi, it seems Elementor automatically includes a smooth scrolling plugin. This also seems to override any other scolling utilities assigned to click events attached to anchor (#) links.

Is it true? If so, is there any way to modify the behaviour of that plugin? I need to add offset to the scrolled position.

**Comment by stratboy** [comment]
Found:

```js
$(window).on('elementor/frontend/init', function(){
  elementorFrontend.hooks.addFilter( 'frontend/handlers/menu_anchor/scroll_top_distance', function( scrollTop ) {
    return scrollTop - 100;
  });
});
```

**Comment by gol4nsky** [comment]
Where did you find this code ?

**Comment by stratboy** [comment]
I didn't remember, but look into javascript filters docs, or search for 'elementor/frontend/init' right in source code.
