### ISSUE TITLE
WPML Translate Management error on save  (Table "icl_string_packages" doesn't exist)

### ISSUE THREAD

**Issue by auban** [pojome/elementor#3419]
## Description

I use WPML plugin without WPML Translate management plugin. 
On save a edit page with elementor a error occure  (Table "icl_string_packages" doesn't exist).
I prefer to use WPML without the WPML Translate management, it still weighs down WordPress.

## Environment

WP 4.9.3
Elementor 1.9.3
WPML 3.9.2

**Comment by bainternet** [comment]
@auban 

This is more of a WPML issue than an elementor issue. It seems like they are trying to access a database table even if they didn't create it.

https://wpml.org/forums/topic/table-toplove_db-wp_icl_string_packages-doesnt-exist/

Try contacting them.

**Comment by auban** [comment]
OK Thanks
