### ISSUE TITLE
Light Box for Image popups

### ISSUE THREAD

**Issue by mojoomla** [pojome/elementor#342]
Hi,
I want to show an enlarged image in a lightbox popup when the image form an Image or Image Box element of Elementor is clicked on.  
Is there a way to do this from within elementor or by using another lightbox plugin compatible with Elementor ?
Have tried installing some of the popular lightbox plugins but none works on images displayed through the Elementor elements.
Would appreciate a recommendation for a compatible plugin.

Thanks.

**Comment by yehudah** [comment]
Hi,

For any lightbox to work you must link the image to it media file, and you do have this option built in each widget except the Image Box, we skipped it for some reason, but i'm sure it will be changed too.

I can confirm it fully work with WP Lightbox 2 plugin.

**Comment by hansnolte** [comment]
Hi mojoomla,

for Image or Image Box you can copy the Image-Url from the WordPress-Mediathek and paste it here.

![image-box](https://cloud.githubusercontent.com/assets/7922627/17287684/5f864186-57d1-11e6-8999-1cee5e520e5c.png)




For the Elementor-Gallery switch the link.

![gallery](https://cloud.githubusercontent.com/assets/7922627/17287690/6bf48252-57d1-11e6-86f1-7a420e365bbc.png)


Tested with Simple Lightbox.
https://wordpress.org/plugins/simple-lightbox/
