### ISSUE TITLE
Feature Request: Enable Active Campaign Double OptIn by passing Form ID to API-Call

### ISSUE THREAD

**Issue by siro83** [pojome/elementor#3422]
In Germany you have to ask your newsletter subsciber for a doubleoptin.

To use activecampaigns doubleoptin feature you have to pass the formid by the API.
Can you add a possibility to pass the custom FormID Field of the form widget with the call?

I have done this by adding some code to the function **create_subscriber_object** in the **activecampaign.php**.

**$subscriber['form'] = $form_Settings['form_id'];**

**Comment by bainternet** [comment]
@siro83 

thanks, added in 1.14.1
