### ISSUE TITLE
[Bug] Cannot click anything in elementor-inner

### ISSUE THREAD

**Issue by MincheolC** [pojome/elementor#3424]
I use Elementor Pro.
After open the page with elementor, when i add new section like below image, **i can't click everything in elementor iframe.**. How can i solve with this problem?
![2018-02-08 7 22 29](https://user-images.githubusercontent.com/22284602/35968034-0c18313a-0d06-11e8-81bf-27f802aa4b7a.png)

This problem happens when I create a new 'Anywhere Elementor' or 'Popbox Elementor'  template and edit with elementor.
![image](https://user-images.githubusercontent.com/22284602/35978499-4912b704-0d29-11e8-8e7d-42481ab781ac.png)

I have two wordpress accounts, Just one encountered with this problem. Another one works fine.

P.S This problem also happens when making 'MyLibrary'.
   1. Go MyLibrary
   2. Add new
   3. Change template to elementor canvas
   4. Click edit with elementor
   5. Add new section 
   6. ... encounter with problem 

Please help me ASAP. The deadline is short.

**Comment by bainternet** [comment]
@MincheolC 
We can't replicate,
please contact our support and see if they can help you. support@elementor.com

**Comment by MincheolC** [comment]
@bainternet 
Hi I'm really sorry to ask you again. I'm still encounter with above problem. I really need your help. Because of above problem I can't use any other elementor plugins and also 'My Library'. 
If you can't replicate, may be I can let you know my wordpress ID / PW by email.

Please help me.

**Comment by JennyLenting** [comment]
I'm having this exact same problem with the popbox. I can't select a grid. 
Do you have a solution?
