### ISSUE TITLE
Boxed Section Borders - Bug ?

### ISSUE THREAD

**Issue by mojoomla** [pojome/elementor#343]
The Borders of a Boxed section do not change with change in content width.
They remain fixed as if the section were full width section.
Is this a bug ? looks like one to me as I wanted the borders to hug the contents of the Section.

**Comment by yehudah** [comment]
Hi,

It's not a bug, to get what you want you can use the style of the widget itself or use the columns widget.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
