### ISSUE TITLE
[Feature Request] Pro: Post slider

### ISSUE THREAD

**Issue by JoeDarko** [pojome/elementor#3430]
I would love to be able to design a complete front page of a magazine/blog website only with Elementor.

The Posts widget is great for this. But no magazine front page is complete without a **post slider**, so i'm really surprised this feature is still not on offer.

I's a hassle to use other plugins for this. And it should be relatively easy to implement for you.

Just like normal slider with some extra features:

+ choose a category or latest posts
+ choose data it displays - post title, date, categories, author
+ choose number of posts
+ few styling options

Really think Elementor should have this long time ago. If you give us this one, every magazine theme will become obsolete. :) 

Love your work. Thanks!

**Comment by bainternet** [comment]
I merged this issue with   #219, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by matjazzidaric** [comment]
Any update on this? Meantime, did somebody figure out how to add this functionality manually? Thanks

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.11! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
