### ISSUE TITLE
[Bug] Counter starting number

### ISSUE THREAD

**Issue by reardestani** [pojome/elementor#3431]
When **Thousand Separator** is on, the **starting number** does not work.

Video: http://take.ms/XtTDR

## Source 
The issue probably comes from Numerator plugin when formating text. 

## Possible fix
Passing fromValue to plugin when instantiating plugin: http://take.ms/eWvQ2

**Comment by bainternet** [comment]
Seems to working fine on the front-end so its ok.

thanks.
