### ISSUE TITLE
Is it possible to create custom widgets within a theme?

### ISSUE THREAD

**Issue by rahulnever2far** [pojome/elementor#3432]
I'm trying to create and register custom widgets from within my theme. I used the exact code from https://github.com/pojome/elementor-hello-world. When it is included in a theme, the widgets don't appear in the Element Editor.

Is it possible?

**Comment by norewp** [comment]
It is possible yes but the way to register the widgets is slightly different in themes. I've done a number of modules for [Element Theme](https://elementtheme.com) - if you are on Facebook DM me ([Zulfikar Nore](https://www.facebook.com/zulfikar.nore)) and I'll try to help you out :)

**Comment by bainternet** [comment]
@rahulnever2far 

share your code and we'll have a look.

**Comment by rahulnever2far** [comment]
@bainternet 

Here's the theme [elementor-twentyseventeen.zip](https://github.com/pojome/elementor/files/1714336/elementor-twentyseventeen.zip).

As I was trying to figure out how to register custom widgets, I simply copied https://github.com/pojome/elementor-hello-world into a subfolder in twentyseventeen theme and included `hello-world.php` in `functions.php`. I didn't make any changes in the theme or the included plugin.

It should have worked but for some reason, it didn't. I didn't get any errors. Custom widgets just didn't appear in the Elementor.

**Comment by bainternet** [comment]
@rahulnever2far 

Yeah that will never work like that :), In our "Hello World" we use `plugins_loaded` hook to load the plugin class which is ok if its loaded from within a plugin but if it's in a theme file then that hook has already fired.

to get started just change the hook to something later like `init` so this line:

```php
add_action( 'plugins_loaded', 'hello_world_load' );
```
to: 
```php
add_action( 'init', 'hello_world_load' );
```

**Comment by rahulnever2far** [comment]
@bainternet 

I would have never figured it out by myself. Thank you so much for your time. I appreciate it :)
