### ISSUE TITLE
[BUG] CTRL+S disables update button 

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3434]
If I'm not mistaken shortcode CTRL+S is for saving the draft, not for Update. So If I use the shortcode CTRL+S, I'm practically blocked from saving/updating the page.

**Comment by bainternet** [comment]
correct.

ref : #3298

**Comment by black-eye** [comment]
I'm afraid, you didn't get my point. The question wasn't about what's the purpouse of the shortcode, the problem is, that after I use this CTRL+S, I'm unable to save the page (only the draft is saved and the Update button is disabled). The Update button should be disabled only after "update save", not after "draft save".

This issue is new in 1.9.4.
