### ISSUE TITLE
Feature Request: Darker more contrasted text in the edit panel

### ISSUE THREAD

**Issue by simonclay** [pojome/elementor#3435]
I find the text in the edit panel small and faint, it would be great if it could be a bit darker / more contrasted. eg. the small light grey text under Margins: TOP RIGHT BOTTOM LEFT is so small and grey I have to squint to see it.

Thanks for a great product though.

**Comment by bainternet** [comment]
@simonclay 
We are playing around with the Idea of a darker theme/UI for Elementor but for now I would suggest you try a 3rd party plugin that does that already like this one: https://www.shofar-media.in.ua/elementor-dark-ui-theme/
