### ISSUE TITLE
Is there any way to put anchor behind the nav-bar for first section (header) in free version?

### ISSUE THREAD

**Issue by ArtyomBaykov** [pojome/elementor#3436]
In the single page sites there is a trouble with first section. Let's say you create 3 sections home services and contact. When you open the page Home's nav link should be active as it's first one while because of the position of anchor it's impossible you need to scroll until will cross the anchor part. So is there any way to put first section's anchor behind the nav bar? Simple nav bar with links is usually used in the one page projects. I hope free version of Elementor supports such feature.

**Comment by bainternet** [comment]
@ArtyomBaykov 

Not sure again what you are asking, but I;ll close this since there is no issue here.

Please try one of the Facebook communities, maybe you'll get a suggestion there.
