### ISSUE TITLE
Separate text alignment for description on image box element

### ISSUE THREAD

**Issue by obe1968** [pojome/elementor#3437]
I have noticed when using an image box element and try to align the description text under style, the only option is under the content dropdown and that aligns everything. I was trying to keep the image and title centered, but needed to left align the description to make the formatting look good. The only work around I found out that worked was add some custom CSS. Can (or will) that feature be added in a future release?

Thanks, and keep up the GREAT work!!

Shawn Campbell

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
