### ISSUE TITLE
An image next to a text box

### ISSUE THREAD

**Issue by duhaussie** [pojome/elementor#344]
I'm trying to put an image next to a text box using columns (1/3 to 2/3) it all looks great in the preview 

![screen shot 2016-07-30 at 7 33 26 pm](https://cloud.githubusercontent.com/assets/20748166/17274245/448bf2b2-568d-11e6-91d5-f80c4fc2f9d7.png)

but when I go to "View Page", it looks like this

![screen shot 2016-07-30 at 7 35 19 pm](https://cloud.githubusercontent.com/assets/20748166/17274247/56ee747a-568d-11e6-980c-6ff4ee25bbb7.png)

Am I able to do what I want? (ie how it looks in preview mode)? Or is that not possible?
This is why I downloaded Elementor, and I think it's great, but it's not doing what I want it to do.

Thanks!

**Comment by yehudah** [comment]
Please paste here your system info:
![system-info](https://cloud.githubusercontent.com/assets/1655373/17287420/360dc8d6-57d8-11e6-8ce5-10998a4acfb4.gif)

**Comment by arielk** [comment]
You can use the Image Box widget, I think it'll make your job better

**Comment by duhaussie** [comment]
ArielK - thanks, but the Image Box widget seems to only allow me to put the photo ABOVE the text, but I want the photo and the text to appear side by side. Plus, no matter what what percentage size I set the photo at, it still comes out huge. This is 12%:

![screen shot 2016-08-01 at 7 10 03 am](https://cloud.githubusercontent.com/assets/20748166/17296644/230ef532-57b7-11e6-8990-6710c142094c.png)


yehudah - I'm attaching system info
[system-info-www.martinturnbull.com-01-08-2016.txt](https://github.com/pojome/elementor/files/393950/system-info-www.martinturnbull.com-01-08-2016.txt)

**Comment by arielk** [comment]
You can set the image position right/left or top like a default, look the screenshot:
![e83gkpi](https://cloud.githubusercontent.com/assets/1778512/17297080/ce022ec8-580c-11e6-87e3-e075baa6f714.png)

**Comment by duhaussie** [comment]
Well, I **_am_** making progress! I've got it to do this:

![screen shot 2016-08-01 at 11 10 31 am](https://cloud.githubusercontent.com/assets/20748166/17304114/cf7e8a78-57d8-11e6-8f6c-7c71d7cef392.png)

But when I trying and shrink the image using the "Image Size" slider, it only affects the text and I end up with this:

![screen shot 2016-08-01 at 11 09 00 am](https://cloud.githubusercontent.com/assets/20748166/17304128/e2603394-57d8-11e6-8b4a-ccd068b92706.png)

**Comment by yehudah** [comment]
@duhaussie 

Did you try it like this:
![anim](https://cloud.githubusercontent.com/assets/1655373/17321915/99accaba-58a3-11e6-9ae3-dca2130fb62b.gif)

**Comment by duhaussie** [comment]
Yes, that's exactly what I did, but the image slider moves the text, not the image. Am I supposed to do something with the image before I click in "Style"?

**Comment by yehudah** [comment]
Nope, exactly what I did.

**Comment by duhaussie** [comment]
*sigh* Well, I had high hopes for Elementor - I like the way it works...except the one thing I really wanted it to do, is isn't doing right. Thanks for your help, yehudah.

**Comment by duhaussie** [comment]
*sigh* Well, I had high hopes for Elementor - I like the way it works...except the one thing I really wanted it to do, is isn't doing right. Thanks for your help, yehudah.
