### ISSUE TITLE
Feature Request: Ability to edit text on mobile phones

### ISSUE THREAD

**Issue by simonclay** [pojome/elementor#3440]
I realise it may never be practical to do the design and layout on the phone, but to be able to edit text content on the phone would be a necessity for me and some clients.

Thanks for a great product!
@

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by simonclay** [comment]
Hi,

I am out of the country now and will be back on 26th Feb. I won’t be picking up email or voice messages. 

If there’s something you need urgently please contact Scott Clay on 07939 004255 or email him at scott@sly-design.co.uk 

Thank you,

Simon.
