### ISSUE TITLE
[Possible Breaking Change v2.0.0] PHP NOTICE & Editor does not load!

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#3441]
@bainternet - As mentioned on FB, there's a possible breaking change in v2.0.0 which is preventing the editor from loading.

`PHP Notice:  elementor/utils/exit_to_dashboard_url is deprecated since version 2.0.0! Use elementor/document/exit_to_dashboard_url instead. in C:\wamp64\www\elementtheme\wp-includes\functions.php on line 4090`

Tested with the just the bare essentials i.e. only Elementor and TwentySeveneen active with no joy!

In the Error logs I'm also seeing the following PHP NOTICE

`PHP Notice:  WP_Admin_Bar::add_node was called <strong>incorrectly</strong>. The menu ID should not be empty. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.3.0.) in C:\wamp64\www\elementtheme\wp-includes\functions.php on line 4147`

And finally, the deactivation action does not seem to be performing as expected i.e. the Feedback Modal does not fire and I'm seeing something odd in the Admin > Plugin page - see screenshot.

![deactivation action](https://user-images.githubusercontent.com/30980808/36073799-4dd0f3bc-0f2e-11e8-8266-7a8f36f8fc33.png)

**Comment by bainternet** [comment]
@norewp 

thanks, as far as I know, it was fixed by this #3404 

feel free to reopen if its still there.

**Comment by norewp** [comment]
@bainternet - Brand new install of WordPress and still won't load.

Will leave this closed for now so as not to add noise to the already busy open issues line :)

**Comment by arielk** [comment]
@norewp v2.0 It's a dev branch, so I'm not sure that is the right moment to test it.
Anyway did you try it again recently?

**Comment by norewp** [comment]
@arielk - I understand it's a dev branch but as an addon developer I have to keep up with the development so my addons don't break or have an adverse effect on Elementor.

Additionally, since this branch will usher in the themer I have to keep up with it so my theme is ready to go once themer is out of the blocks :) 

I've been trying to get it going on every update that is made and the last test done was on Alpha-2 - See video here: https://www.useloom.com/share/23ac33707d714cd8b83b92961361c81f

As you can see it's a not go on my side - bumped PHP to v7.1.x as I got an error 7.0.x..... Memory Limit bumped up to 512M from 256M which is my standard setup and still no joy.

**Comment by norewp** [comment]
OK nvm - I've figured it out.

Being a dev branch it is no longer compiled ready for production/testing so I've compiled and i'm all good :)
