### ISSUE TITLE
Video Widget Autoplay on iOS

### ISSUE THREAD

**Issue by MarcusMoeller** [pojome/elementor#3442]
When using the video widget to add a YouTube video to a page, the autoplay function is not working on iOS.

On a regular browser (tested with Firefox 58) it works as expected.

**Comment by bainternet** [comment]
@MarcusMoeller 

> It can't be done. For various reasons (including, but not limited to data usage), Apple doesn't allow auto-playing of videos.

https://stackoverflow.com/questions/15090782/youtube-autoplay-not-working-on-mobile-devices-with-embedded-html5-player
