### ISSUE TITLE
Feature Request: Hide and Schedule Individual Slides In Image Slider

### ISSUE THREAD

**Issue by MicroCzar** [pojome/elementor#3444]
Wishing the Slider allowed for "hiding" any specific slide within the slider. Would really like to additionally see showing a slide within a slider based on time and date parameters. As developers we commonly need more slides in a slider than are actually visible because at times we need to quickly have a slide become visible, but not permanently stay visible. For instance, alert messages, coupon specials, special promotions, etc.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
