### ISSUE TITLE
Typogaphy in a Repeater malfunctions

### ISSUE THREAD

**Issue by vrundakansara** [pojome/elementor#3446]
The Typography doesn't work when used in a repeater. The reset also doesn't work. Here is a small video - http://bsf.io/y-ale

Regards,
Vrunda Kansara

**Comment by norewp** [comment]
Works fine for me.

What's you add control code?

**Comment by vrundakansara** [comment]
Hey @norewp ,

I added this code - 

```php
$repeater->add_group_control(
	Group_Control_Typography::get_type(),
	[
		'name'     => 'btn_typography',
		'scheme'   => Scheme_Typography::TYPOGRAPHY_1,
		'selector' => '{{WRAPPER}} {{CURRENT_ITEM}} a.elementor-button',
	]
);
```

**Comment by norewp** [comment]
Try changing `'selector' => '{{WRAPPER}} {{CURRENT_ITEM}} a.elementor-button',` to `'selector' => '{{WRAPPER}} a.elementor-button',` and be more specific your selector i.e. `.my-widget-class a.elementor-button`

**Comment by vrundakansara** [comment]
I tried. Basically, this creates a problem only when a repeater is used.

**Comment by norewp** [comment]
The only part I can see that seems to not be working is the reset but I can live with that :)

**Comment by bainternet** [comment]
@vrundakansara @norewp 

In general, group controls are not officially supported in repeaters. (Yet anyway).
