### ISSUE TITLE
How can I have fixed position vertical column through custom css on elementor?

### ISSUE THREAD

**Issue by hidemisaito** [pojome/elementor#3448]
I have been trying to make my left hand sidebar fixed position but somehow it doesn't work....
<img width="739" alt="screen shot 2018-02-12 at 19 32 29" src="https://user-images.githubusercontent.com/34417313/36092695-9d71d8f2-102b-11e8-8a84-7123704fbff2.png">
<img width="1273" alt="screen shot 2018-02-12 at 19 32 16" src="https://user-images.githubusercontent.com/34417313/36092698-9f6bc2e4-102b-11e8-87c0-2c96a6c82d29.png">

**Comment by bainternet** [comment]
Looks like it is working form your images, it more of a CSS question then an elementor related one,

basically just give the other column a margin-left with the with of the fixed column.
