### ISSUE TITLE
How can I make the vertical navmenu's submenu to be dropdown?

### ISSUE THREAD

**Issue by hidemisaito** [pojome/elementor#3449]
How can I make the vertical navmenu's submenu to be dropdown?

Currently the submenu is on the right hand side...
but I want it to be vertically below the main menu...

HELP!!

Now it's like this:
<img width="383" alt="screen shot 2018-02-12 at 19 36 03" src="https://user-images.githubusercontent.com/34417313/36092831-172d1b34-102c-11e8-8dae-217c075691f0.png">

But I want it to be like this:
<img width="207" alt="screen shot 2018-02-12 at 19 36 25" src="https://user-images.githubusercontent.com/34417313/36092841-200d951c-102c-11e8-8df6-ea3cc052646b.png">

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
