### ISSUE TITLE
ID attribute on Section and Widgets

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#345]
Hi guys! Thanks for this awesome page builder!

I was wondering if you can add ID attribute on section and widgets? This ID attribute is useful when you have a hashtag navigation. Perhaps you could generate a default ID for each section and widget, like "elementor-section-21", "elementor-widgets-312". And user can optionally change it to something more readable, like "pricing", "gallery", "contact".

Is it possible?

**Comment by yehudah** [comment]
Hi,

There is an anchor widget you can use.
just drop it before your section.

**Comment by daviedR** [comment]
Oops, just realized it was there.. Thanks!
