### ISSUE TITLE
Typography label does not show and popup display in latest version

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#3450]
I have it fixed for previous version but latest version label does not show rather it shows only Typography. 

![capture](https://user-images.githubusercontent.com/7946657/36097637-f0b49c44-1025-11e8-9045-2dc82a90b098.JPG)

https://github.com/pojome/elementor/issues/2491

Another issue is typography popup modal positioning.
![capture](https://user-images.githubusercontent.com/7946657/36097910-102e972c-1027-11e8-82b0-0061a12cd7a0.JPG)
 
``` $this->add_group_control(
            Group_Control_Typography::get_type(),
            [
                'name' => 'pre_head_typo',
                'selector' => '{{WRAPPER}} .pre_head',
                'fields_options' => [
                    'typography' => [
                        'label' => __( 'Pre heading typo', 'webangon' ),
                        'label_block' => true,
                    ],
                ],
            ]
        ); ```

**Comment by bainternet** [comment]
@webangon 

You are correct since the last version ( popover ) the label should be at the top level of params:

```PHP
Group_Control_Typography::get_type(),
[
    'name' => 'pre_head_typo',
    'selector' => '{{WRAPPER}} .pre_head',
    'label' => __( 'Pre heading typo', 'webangon' ),
]

**Comment by webangon** [comment]
Thank you. Please keep in mind about the popup typography modal css positioning.
