### ISSUE TITLE
CTA Box - Hebrew Translation

### ISSUE THREAD

**Issue by danstramer** [pojome/elementor#3451]
In the Background area it says:
צבע לייטבוקס
which is actualy the overlay color.
I think the correct translation should be:"צבע כיסוי"
or something similar, as lightbox could be misleading.
Screenshot:
https://www.dropbox.com/s/v2e42t6ykyy92f1/cta-elementor.png?dl=0

Dan

**Comment by arielk** [comment]
Thanks for your feedback, I changed it now it will be updated in the next release.
