### ISSUE TITLE
[Inline editting] Elementor places lots of unneeded tags around unformatted text.

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#3453]
When you copy unformatted text and paste it, using the inline editor. It places lots of unneeded tags arround it. Tags like font-size, style etc.  When you do the same in the right text box, it does not accour.

Made a video, in clean WP install: http://somup.com/cFnlDHV4Yh

**Comment by black-eye** [comment]
+1 Second this. 
I've already posted an issue on this (#2930) but it was closed.

Elementor team, please consider some solution to this. This issue makes inline editing big potencional threat when used by inexperienced users/clients. You can imagine, what mess can make the markup from other page or a text editor.

And what is worse, it copies elementor's own (hidden) styles - as seen in the video above!

**Comment by bainternet** [comment]
@black-eye, @atMaarten 

What browser are you using ??

**Comment by atMaarten** [comment]
This video was recorded in Google Chrome. The main browser I use.

**Comment by bainternet** [comment]
Just as we thought, Its a known bug in Chrome and `contenteditable` (a quick search for "chrome contenteditable span" tell a lot about it). Its manly depended on the loaded style and the current editable element.

Sadly there is not a lot we can do about it right now.
 
thanks for reporting.

**Comment by black-eye** [comment]
I edit Elementor pages mostly in Firefox and it seems that this "self styled" bug is not present any more. But I'm 90% sure that I faced this problem before in some former version.

@bainternet, has Elementor team done some fixes concerning this?

On the other hand, the issue with inline styles copied from other sources (text editors, other pages) is still present.

**Comment by black-eye** [comment]
I found out, where this phenomenon appeared (even in Firefox) - copying the inline text from the button gives you this:

![obrazek](https://user-images.githubusercontent.com/5634870/36351270-9c5dfbd2-14a7-11e8-8793-13e5b54cf56b.png)
