### ISSUE TITLE
Feature Request : Populated form fields

### ISSUE THREAD

**Issue by zack-n-slash** [pojome/elementor#3454]
Hi,
I think it would be nice if the fields of the form widget could be populated with values read from the url.
For instance, if I have two fields in the form, "name" and "email", then if I could call the page with mypage.php?name=James&email=james@example.com, and the form would show those values.

Best regards,

**Comment by bainternet** [comment]
I merged this issue with  #4268, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
