### ISSUE TITLE
Disappearing owl classes when I add new item (in my own widget)

### ISSUE THREAD

**Issue by skalanter** [pojome/elementor#3457]
Hi There,

when I add a new item to the carousel in my own widget,
removed carousel classes from in editor online
and everything is disappearing in the source code.
I attached 2 images in below,
Maybe you have experience in this issue.

I appreciate you, Thanks,
and I congratulations **500,000+** active installations.

1- https://i.imgur.com/A7diAIU.jpg _(I have 3 item)_
2- https://i.imgur.com/eMiBdux.jpg _(when I clone any item or add a new item to carousel has an issue)_

**Comment by bainternet** [comment]
@skalanter 

Thanks, as for your issue we would need to see your widget implementation to be able to help.

**Comment by skalanter** [comment]
Dear @bainternet 

I attached needed files for examination, 

This is the code I tested:  [testimonial-level.zip](https://github.com/pojome/elementor/files/1719259/testimonial-level.zip)

**Comment by bainternet** [comment]
Seems like you Javascript implementation is wrong.
You are only initializing your Owl slider on page load and when you add/remove a slide then the HTML of your widget is re-fetched from the server and you do not initialize the slider again.

basically you Javascript is not listening to any changes.

I would suggest you look at some of the native sliders/carousel widgets bundled in Elementor or Elementor Pro and pick around the JS there to get a better Idea of this should be done.
