### ISSUE TITLE
Media Carousel Frontend 

### ISSUE THREAD

**Issue by pureion** [pojome/elementor#3458]
So I was asked to put this on GitHub as an option in finding a solution.  

I have been using Elementor Pro with MyListings directory theme.   Under one of the single page profile I have the option to add a box to the profile page through Advanced Custom Fields with the ability for directory listing owner to add video urls which will open up a lightbox.  The problem with this method is that it will only allow one video.  In order to add other videos I would have to make another box which does not look nice imo.   So in my search, I remembered that Elementor had a fairly new feature- Media Carousel.  

This feature has the potential to solve the issue but the problem is, it is only from admin back end that video urls can be added.   Im posting in hopes that someone can make this feature-  allow my directory listing owners add their own multiple videos by url or upload but still at the same time only see their videos as opposed to everyone's.  This will be done by the front end without needing the wordpress backend with their own video gallery management.

If anyone knows of a different workaround if this feature request is not possible, let me know!

**Comment by bainternet** [comment]
Currently, editing in Elementor with now dashboard access is not supported, but we will look into it in the future if we see a large demand for it.

But in your case, an easier solution would be to change your ACF field to a repeater and implement your own media Carousel for it.

Thanks for the feedback.
