### ISSUE TITLE
Custom Thousand Separator in Counter Widget 

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3459]
The problem with the thousand separator in Counter widget is, that for some regions coma "," is not the proper sign (e.g. in Czech Republic, which is my case, coma is used as a decimal separator).

Please consider adding the option to change the separator or use the one defined in language settings.

**Comment by stein70090** [comment]
Custom thousands separator doesn't save properly, it still uses the comma.

**Comment by edemir206** [comment]
I have solved the problem this way:

add the following line to wp-config.php:

setlocale(LC_NUMERIC, 'en_US.UTF-8');
