### ISSUE TITLE
Form checkbox ticks in wrong position

### ISSUE THREAD

**Issue by dollhauss** [pojome/elementor#3460]
https://cl.ly/1h2l302B3U2I

Form checkbox has an issue. The ticks are not placed correctly.

This can be corrected with the following CSS:

input[type=checkbox]:before {
padding: 7px 5px 0 0;
}

Hope it gets fixed soon. ;-)

**Comment by bainternet** [comment]
@dollhauss 

this styling is not coming form elementor, probably your theme or a conflicting plugin.
