### ISSUE TITLE
[Feature request] Column Width (%) would be able to go up to 0 (zero)

### ISSUE THREAD

**Issue by sarahdenise** [pojome/elementor#3461]
Hi,

Could I please request that we are able to have the column width up to 0%

This is for those times that I need a column in desktop view but want to make it as small as possible in mobile view.

Thanks

**Comment by bainternet** [comment]
@sarahdenise 

if you hide the widgets inside that column for mobile you should get the same results.

![fotiytd](https://user-images.githubusercontent.com/660572/36139188-47513b0a-10a5-11e8-9aa7-0659c46e4ad1.png)
