### ISSUE TITLE
Elementor Pro Form Widget - Styling Error Messages

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#3462]
## Description

Currently, the we can't style the error messages in the **Form Widget**.

With dark backgrounds the errors can not be seen:

![error-message-style](https://user-images.githubusercontent.com/576623/36145746-f62e7a6a-10ba-11e8-85a1-6f13823805b0.png)

It says: **The form was sent successfully!**

## Solution

In the **Style Tab**,  add a new section called **Error Messages** with the following controls:

* Background Color
* Text Color
* Typography
* Border
* Padding

**Comment by ramiy** [comment]
It should be simple to implement, copy & paste the button controls to a new section for error messages. And update the CSS selectors.

**Comment by arielk** [comment]
Duplicate #1180

**Comment by ravilrrr** [comment]
I every time  add padding, color and border through css. Why can't you do as suggested above, i.e. in widget settings?

**Comment by joexcm** [comment]
+1 don't think this should be a CSS job

**Comment by Sim2K** [comment]
This needs to be sorted .. until then in 'Edit Form' add this to the custom CSS...

`.elementor-message elementor-message-success {
font-size: 15px;
color: white;
}

[role=alert] {
font-size: 15px;
color: white;
}`

Change colour and font size and add a different font if necessary to suit.
