### ISSUE TITLE
"Server Error - Token expired"  Cannot update page

### ISSUE THREAD

**Issue by Alan5596** [pojome/elementor#3464]
Could not update web page via the Elementor Update button.

Error box appears with "Server Error - Token Expired"

![screen shot 2018-02-13 at 11 24 08](https://user-images.githubusercontent.com/36445429/36151690-2b2f3d62-10c0-11e8-9c0e-1a8f66ae14c0.png)

System Info

=============
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.1.24
	PHP Version: 7.0.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.4
	Site URL: https://XXXXXXXX
	Home URL: https://XXXXXXXXX
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: XXXXX Child Theme
	Version: 1.0
	Author: xxxxXXXXX
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.4.16
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0

== Active Plugins ==
	BackWPup
		Version: 3.4.4
		Author: Inpsyde GmbH

	Coming Soon Page & Maintenance Mode by SeedProd
		Version: 5.0.17
		Author: SeedProd

	Contact Form 7
		Version: 5.0
		Author: Takayuki Miyoshi

	Cookie Consent
		Version: 2.3.9
		Author: Catapult_Themes

	Elementor
		Version: 1.9.4
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.0
		Author: WebTechStreet

	LiteSpeed Cache
		Version: 1.9
		Author: LiteSpeed Technologies

	MainWP Child
		Version: 3.4.5
		Author: MainWP

	Ocean Elementor Widgets
		Version: 1.0.9
		Author: OceanWP

	Ocean Extra
		Version: 1.4.3
		Author: OceanWP

	Ocean Pro Demos
		Version: 1.0.1
		Author: OceanWP

	Ocean Social Sharing
		Version: 1.0.9
		Author: OceanWP

	Ocean Sticky Header
		Version: 1.0.13
		Author: OceanWP

	Optimize Database after Deleting Revisions
		Version: 4.5.1
		Author: CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands

	Really Simple SSL
		Version: 2.5.25
		Author: Rogier Lankhorst

	Wordfence Security
		Version: 7.0.4
		Author: Wordfence

	WP Google Maps
		Version: 6.4.09
		Author: WP Google Maps

	WPS Hide Login
		Version: 1.2.3
		Author: WPServeur, NicolasKulka, tabrisrp

	Yoast SEO
		Version: 6.3
		Author: Team Yoast

== Debug ==
	Errors:

**Comment by bainternet** [comment]
we can't replicate and the "Server Error - Token expired" is only shown if the 'Nonce' is not valid anymore which mean it was generated a relatively long time in advance.

If the issue still persists, please contact our support, and see if they can help you.

Support@elementor.com

**Comment by jmayoralalba** [comment]
Hi everyone,

I've found a way to reproduce the error: 
First of all you need a role with these following capabilities: edit_others_pages, edit_others_posts, edit_posts, edit_private_pages, edit_private_posts, edit_published_pages, edit_published_posts, read.
Then create a page with another user, go the elementor editor to edit this page and try to save any change.

I've been investigating and found that the nonce code it's empty when it shouldn't be. 

In the file **includes/editor.php**, the function create_nonce check for the self::EDITING_CAPABILITY (edit_posts) into the post_type_object. I think that the post_type_object itself should return the edit_posts capability, necessary at least to edit just the content of the page.

**Comment by ryross** [comment]
@jmayoralalba is right on. In our case, Store Locator Plus wasn't registering the custom post type during heartbeat ajax requests, so $post_type_object was empty.
