### ISSUE TITLE
Pro Form Section Headings/Title and Plain Text  - Please Add

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3468]
![sample-text](https://user-images.githubusercontent.com/35422914/36168324-a985696a-10c6-11e8-8c10-52263ccd52fa.jpg)

## Description

I need the ability to add section headings in complex forms. I am designing an employment application and need the ability to have section headers in the form that can be styled i.e.

Employment History
Education
Etc.

Also, there should be a way to add plain text disclaimers and other information that has to be agreed to prior to the "Submit" button such as our company drug and alcohol policy.

The plain text descriptions allow for presenting information prior to asking for information in form fields.

Section dividers would be a nice addition too.

Thank you

**Comment by bainternet** [comment]
All of these can be added via the HTML field.
