### ISSUE TITLE
Thumbnail navigation for image Carousel / Smaller columns

### ISSUE THREAD

**Issue by eyalpour** [pojome/elementor#347]
hi.
1. I would like to offer you to add to the Elementor picture carousel component, the builder gallery option  that shows the gallery pictures below in small dimensions. 
2. the Elementor add area allows to add an area with up to six columns and minimum 10% size for a column.  i would like to offer to allow more columns and especially smaller columns, like 5% for example.

**Comment by yehudah** [comment]
Hi,

1. Maybe in future releases.
2. For now there is a limit of ten columns in a row, so the size will be 10% each.

Thanks

**Comment by arielk** [comment]
@eyalpour 

We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by eyalpour** [comment]
hi ariel. what update do you need from me ?
i am waiting for your update.
for the first issue i would be happy to be updated on release.
for the second issue. its not the ten columns limit, it the size of one column that i would like to improve. it will help me design the site better, and implement smaller parts when needed.

**Comment by arielk** [comment]
Sorry, it's my mistake :(  I tagged this issue for our wishlist.

How much would you like to reduce your column?

**Comment by eyalpour** [comment]
5% would be nice :)

Will leave me enough space to manipulate.

 

Regards,

Eyal pour

 

Internet for the Business

Committed to your success

cell  : +972-52-3350154           Email :  <mailto:eyal@ep1.co.il> eyal@ep1.co.il            

fax  : +972-76-5100542            Site      :  <http://www.ep1.co.il/> www.ep1.co.il

**Comment by arielk** [comment]
In fact this is something that can cause problems for navigation interface, let us check it out ..

**Comment by eyalpour** [comment]
o.k

thx.

**Comment by arielk** [comment]
Finally Media Carousel is here with thumbnail navigation, released in E-Pro v1.9.0

Thanks for your feedback!
