### ISSUE TITLE
Elementor Elements as shortcodes as well

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#3482]
Just a thought, although it might be bloating the editor. 

Is it possible to add Shortcodes to your elements? 
Some of my 'templates' use shortcodes for displaying data. But certain designed elements, it would be awesome to use a shortcode to stay consistent with elementor's design. 

_Example, Inside 'tabs', I want to add a button to the 'content', but you can't. But if I had a shortcode, I could._ 

Thoughts?

**Comment by bainternet** [comment]
@stickypages 

You can already use shortcodes in tabs.

**Comment by stickypages** [comment]
@bainternet Yeah, but what about an Elementor Button shortcode, or a counter, etc. By having an "Elementor Button Shortcode" it would produce the same design etc.
