### ISSUE TITLE
Suggestion: Maintenace Mode

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#3483]
It would be great to update the maintenance mode options to have a 'DEV' option. 
But adjust the Who Can Access to say, "Custom URL". So if your showing a customer their website, they can just access with a unique url. 

IE: https://www.example.com?access=1234567890

Thoughts?

**Comment by bainternet** [comment]
I merged this issue with  #2687, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
