### ISSUE TITLE
Feature request: simple grid tool

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3489]
Hi, it would be great if there was a tool to build a responsive grid (where number of columns will  change with screen size) filled with static content.

I know there are already gallery, post, portfolio, widgets but they essentially get contents from queries. 

The columns widgets lets you add columns filled with static content, but every row is wrapped in a section container, so they're not suitable for responsive grids.

One way is to add an arbitrary number of single elements to a section, for ex. image-boxes, the add a class to the section, and the use that class to style the grid.

But since you already did a lot of grid coding for the tools above, maybe you could add a widget for simply build empty responsive grids, to be filled with other widgets.

Maybe I'm missing something. Otherwise, this would be a good widget.

**Comment by bainternet** [comment]
@stratboy 
can you try to explain better, provide an example?

**Comment by stratboy** [comment]
A tool like the 'columns' one, but for grids instead of only columns. Just to avoid doing all the flexbox code. It's not a plain lack though, one can just add several images and do the flex-code my himself. But it would be great to ha a flex-grid tool right out of the box (and I'm not speaking of css Grid here, since they're not fully supported yet, just flexbox grids).

**Comment by bainternet** [comment]
@stratboy 

Thanks for the clarification, 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by stratboy** [comment]
I looked into your current widgets for the 'columns' one but I can't find it. I'd like to build a grid componenent starting from the column. Where should I look? It seems it's not a 'real' widget, maybe because it build sections itself? Anyway, where shuold I look for its code?

**Comment by mgustavs** [comment]
Hi All! I would like to leave a BIG vote for this one! Seems like most of my problems with clickable visual content could be solved with just one open type grid. Instead I have been breaking my back over this for hours...

Take a look: I have several places where I have specific clickable content with picture change on hover (yes, flipbox, call to action, just column with backgrounds etc. would do) but I need that in pictures ratio so it doesn't get cut off (oops, none of them!) and in grid (portfolio grid, post grid, ...what about just ..grid?.. :) )

ATM I go with embedding Smart Slider 3 (cause it keeps ratio and has hover picture change) in two column sets - one for desktop and phone ( 4 and 2) and one for tablets (3). Not to mention that specific slider has to be copied to be placed in one page twice..

But if there was an open type grid that kept aspect ratio for each tile - where you could throw in flipboxes, call to action, shortcodes, name it - that would solve everything!

<img width="750" alt="Screen Shot 2019-04-07 at 15 44 13" src="https://user-images.githubusercontent.com/47918624/55683792-5b8f1100-594c-11e9-87b2-9fa011543b1a.png">
<img width="750" alt="Screen Shot 2019-04-07 at 15 45 31" src="https://user-images.githubusercontent.com/47918624/55683793-5b8f1100-594c-11e9-9b38-15843aeab6c2.png">

**Comment by mgustavs** [comment]
Hi Elementor! Good work so far! I would like to leave a BIG vote here for this one! Seems like most of my problems with alined clickable visual content could be solved with just one open type grid. Instead I have been breaking my back over this for hours...

Take a look at 1st pic: I have several places where I have specific clickable content with picture change on hover (yes, flipbox, call to action, just column with backgrounds etc. would do) but I need that in pictures ratio so it doesn't get cut off (oops, none of them!) and in a responsive grid that would display 4 -> 3 -> 2 or 3 -> 2 -> 1 columns on desktop -> tablet -> phone (portfolio grid, post grid, ...what about just ..grid?.. :) )

ATM I go with embedding Smart Slider 3 (cause it keeps ratio and has hover picture change) in two column sets - one for desktop and phone ( 4 and 2) and separate one for tablets (3). Not to mention that specific slider has to be duplicated to be placed in one page twice..

But if there was an open type responsive grid that kept aspect ratio for each tile - where you could throw in flipboxes, call to action, shortcodes, name it - that would solve everything in one go!

Also dividing certain grid tiles could be added for more flexibility (pic 2). ATM I have managed (was not easy) with 3 columns and negative margins for content and following block to cover gaps that kept coming up between and below the content (Issue #2042)

Thanks!
<img width="750" alt="Screen Shot 2019-04-07 at 15 44 13" src="https://user-images.githubusercontent.com/47918624/55684089-f50bf200-594f-11e9-9aa9-a4321cd1d180.png">
<img width="750" alt="Screen Shot 2019-04-07 at 15 45 31" src="https://user-images.githubusercontent.com/47918624/55684090-f50bf200-594f-11e9-8269-48339188888f.png">

**Comment by arielk** [comment]
ref: https://github.com/elementor/elementor/issues/15424

**Comment by nicholaszein** [comment]
Hello everyone!

We are happy to announce that the first beta implementation of the Grid Container is live! 🙌 

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪 

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards

**Comment by nicholaszein** [comment]
Hello, there everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the first phase of this feature was released with Elementor **v3.13.0**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
