### ISSUE TITLE
Columns resize cannot be repeated - Bug ?

### ISSUE THREAD

**Issue by mojoomla** [pojome/elementor#349]
Say, I have a section with two equal columns.
Whenever I load the page in Elementor I can resize the columns once only.
If I attempt to resize them again the resize handle fails to appear. I have to reload the page in Elementor to attempt another resize.
This looks like a bug.
I am using latest version of Chrome on Windows 7

**Comment by yehudah** [comment]
Hi,

I have tried to reproduce the problem in my side with no success. the resize working each time.

Can you give more details ? what widgets do you have ? did you did something in the settings ?

**Comment by mojoomla** [comment]
I am not using any widgets on the page.
I am only using a theme made in Artisteer v4.1   Wordpress version is latest stable version.

**Comment by mojoomla** [comment]
Please give me your mail address so I can send you login credentials to the
online site where you can login to wordpress and check this out for
yourself.

Thanks

**Comment by arielk** [comment]
Hi, released a new version, please update the plugin and check it again

**Comment by mojoomla** [comment]
Yes. This is now working .
Thanks !
