### ISSUE TITLE
Feature Request: Wrap website in an app and submit to google store and app store

### ISSUE THREAD

**Issue by rzammit** [pojome/elementor#3490]
A feature recommendation which will take Elementor to another level.. So every website you create using Eelementor, it will be automatically mobile friendly. So technically speaking, the website is like an app too.... I recommend that in the future, you can wrap the website in an app and publish it on google store or apple store..

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
