### ISSUE TITLE
"Create new page" button in dashboard widget not working if page can't use Elementor

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3491]
## Description

On the dashboard home page, there is an elementor widget. In this widget, there is a button "Create new page". When you click this button and Elementor is not enabled for the post_type = page, you get an error "Do you really want to do that?".

The best would be to show a list of post_type able to use Elementor when you click on the button; a bit like the "+ New" button on th WP admin bar.

## Steps to reproduce

Disable Elementor for the post_type = page in the "Settings" section of the plugin.
Click the "Create new page" button on the dashboard home page Elementor widget.

**Comment by KingYes** [comment]
Thanks
