### ISSUE TITLE
Youtube videos don't start at specified start time

### ISSUE THREAD

**Issue by mbettelman** [pojome/elementor#3492]
## Description

Youtube videos don't start at specified start time when using Elementor's video widget.   

## Steps to reproduce

1. Add the video widget to an Elementor page
2. In the "Link" field, add your Youtube link.
3.  Append a start time to the youtube link, for example "<Your Youtube Link>?t=4m26s"
4.  Notice that when the youtube video plays, it will always play from the beginning of the video, regardless of the specified start time.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.36
	PHP Version: 7.1.12
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.4
	Site URL: http://mattbettelman.com
	Home URL: http://mattbettelman.com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.0
		Author: Takayuki Miyoshi

	Contact Widgets
		Version: 1.4.1
		Author: GoDaddy

	Elementor
		Version: 1.9.5
		Author: Elementor.com

	Elementor Addons & Widgets
		Version: 1.1.5
		Author: ThemeIsle

	Flamingo
		Version: 1.8
		Author: Takayuki Miyoshi

	Free & Simple Contact Form Plugin - Pirateforms
		Version: 2.3.4
		Author: Themeisle

	Jetpack by WordPress.com
		Version: 5.8
		Author: Automattic

	Limit Login Attempts
		Version: 1.7.1
		Author: Johan Eenfeldt

	Mesmerize Companion
		Version: 1.2.6
		Author: Horea Radu

	NavMenu Addon For Elementor
		Version: 1.1.2
		Author: ThemeIsle

	Orbit Fox Companion
		Version: 2.3.4
		Author: Themeisle

	Sticky Menu (or Anything!) on Scroll
		Version: 2.1.1
		Author: Mark Senff

== Debug ==
	Errors: 
		TypeError: $ is not a function
			at http://mattbettelman.com/wp-admin/post.php?post=709&action=elementor - 26:9
			2018-02-15 21:08 +00:00

		TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
			at http://mattbettelman.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.4 - 2:135668
			2018-02-10 08:18 +00:00
			x 4 times

		Error: An "el" #elementor-panel-elements-search-area must exist in DOM
			at http://mattbettelman.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:13466
			2018-02-09 03:13 +00:00

		TypeError: Cannot read property 'form' of undefined
			at http://mattbettelman.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.0 - 2:64723
			2018-01-10 09:02 +00:00
			x 2 times

**Comment by bainternet** [comment]
@mbettelman 

Youtube video with start time works just fine. it will not work if you are using it as a background.

**Comment by mbettelman** [comment]
Actually this doesn't work.  I'm not trying to use the video as a background.  Did you try following my steps?  

Here's an example in action from my website.  The video at the top of this page is meant to start at 4 minutes and 48 seconds into the video.  But when I click the play button the video starts from the beginning every time:

http://mattbettelman.com/projects/transformers-war-for-cybertron/bridge-station/

Here is the youtube link I plugged into the video widget:

https://youtu.be/tjIWyq26dBo?t=4m48s

**Comment by Paul00777** [comment]
I'm having the same. But... If you're logged in to your YouTube account then it seems that the location that you last viewed the video at, takes presidency.
