### ISSUE TITLE
why get_style_depends() is final mehtod?

### ISSUE THREAD

**Issue by guytzhak** [pojome/elementor#3494]
Hi,
The method 'get_style_depends' is final methor dislike the method 'get_script_depends' that isn't final method and help to add depends foreach widget.

why is that? Why you do doesn't let to add custom styles for widgets only if they arer calling?

Thanks

**Comment by KingYes** [comment]
You need to use with `add_style_depends()` method to add styles.

**Comment by tristanleboss** [comment]
I have the same question... I don't understand why for scripts we can override `get_script_depends` but not for styles (`get_style_depends`). These methods are exactly the same: they work on two arrays `depended_styles` and `depended_scripts`. These arrays are used by two twin functions `get_style_depends` and `get_scripts_depends` which are in turn used by two twin functions `enqueue_styles` and `enqueue_scripts`. Each time on these 2 later functions is used, the other one is called right after. I didn't find a place where only one is used alone.

**Comment by guytzhak** [comment]
@KingYes 
Understand, But like @tristanleboss  said. it could make us confused when it doesn't work like 'get_script_depends' function.

Thanks!

**Comment by KingYes** [comment]
Thanks @guytzhak @tristanleboss
