### ISSUE TITLE
Best way to create custom controls or extend defaults?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3495]
As for the title: what's the current best practice for creating custom controls or edit default ones?
There are docs for widgets, but not for controls themselves. So I learned to create new widgets and mod the existing ones, but now I have some needs for adding features to existing controls. No project is the same as the previous... Always need customisations all the way...

**Comment by bainternet** [comment]
@stratboy 

Until the API/Docs are ready I can say this: Its always bad practice to edit native controls, extending is the better simpler way you should go, and if you find yourself overwriting too much of the control when extending it, then a custom control could be the right way to go in that case.

**Comment by stratboy** [comment]
After ten day you're a bit late and sure I found solutions. We use hooks to extend them. For people reading this is an example:

``` php
add_action( 'elementor/element/image/section_image/before_section_end', function( $element, $section_id ) {
  $element->add_control(
    'image_advanced_caption',
    [
      'label'        => 'Didascalia avanzata',
      'type'         => Controls_Manager::WYSIWYG
    ]
  );
}, 10, 2 );


add_action( 'elementor/widget/render_content', function($content, $element){
  if($element->get_name() == 'image'){
    $settings = $element->get_settings();
    if(!empty($settings['image_advanced_caption'])) return $content . '<div class="caption">' . $settings['image_advanced_caption'] . '</div>';
  }

  return $content;
}, 10, 2);


add_action('elementor/widget/print_template', function($template, $widget) {
  if($widget->get_name() == 'image'){
    ob_start();
    ?>

      <# if ( '' !== settings.image.url ) {
        var image = {
          id: settings.image.id,
          url: settings.image.url,
          size: settings.image_size,
          dimension: settings.image_custom_dimension,
          model: view.getEditModel()
        };

        var image_url = elementor.imagesManager.getImageUrl( image );

        if ( ! image_url ) {
          return;
        }

        var link_url;

        if ( 'custom' === settings.link_to ) {
          link_url = settings.link.url;
        }

        if ( 'file' === settings.link_to ) {
          link_url = settings.image.url;
        }

        #><div class="elementor-image{{ settings.shape ? ' elementor-image-shape-' + settings.shape : '' }}"><#
        var imgClass = '',
          hasCaption = '' !== settings.image_advanced_caption;

        if ( '' !== settings.hover_animation ) {
          imgClass = 'elementor-animation-' + settings.hover_animation;
        }

        if ( hasCaption ) {
          #><figure class="wp-caption"><#
        }

        if ( link_url ) {
            #><a class="elementor-clickable" data-elementor-open-lightbox="{{ settings.open_lightbox }}" href="{{ link_url }}"><#
        }
              #><img src="{{ image_url }}" class="{{ imgClass }}" /><#

        if ( link_url ) {
            #></a><#
        }

        if ( hasCaption ) {
            #><div class="caption widget-image-caption wp-caption-text">{{{ settings.image_advanced_caption }}}</div><#
        }

        if ( hasCaption ) {
          #></figure><#
        }

        #></div><#
      } #>

    <?php

    $template = ob_get_clean();
  }

  return $template;
}, 10, 2);
```

**Comment by techeshta** [comment]
Hey @stratboy @bainternet,

I am looking to extend the default image element and I completed almost all the steps with the help of  below link,
- https://github.com/elementor/elementor/issues/4702 (where I am adding my custom js file)

And I am looking to extend feature of the default Media Control,
\Elementor\Controls_Manager::MEDIA (Developer note:- https://developers.elementor.com/elementor-controls/media-control/)

Now, pain point is that I have a list of images from third-party resources when I click on that any image then it should select as media automatically.

Screenshot - [https://prnt.sc/mzbeq8](https://prnt.sc/mzbeq8)

Facebook community post link - https://www.facebook.com/groups/Elementors/permalink/1922420311217079/
