### ISSUE TITLE
Add a "Media (File)" control or allow "Media (Image)" to allow different mime types

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3496]
## Description

Today, there is one "Media (Image)" control. Unfortunately, it opens the media library and only displays images from it. (If you uploaded DOC/PDF/... file, they will not appear.)

It would be a super (and probbly easy) addition to either 1) add a "Media (File)" control which will display all available files in the media library or 2) add an argument to the existing "Media (Image)" control to allow either all files, all images or specific mime types. The wp.media js object does allow this, for sure.

`wp.media({title: 'Upload/Choose CSV file', library: {type: 'text/csv'}});`

I think 2) is the best choice.

**Comment by ramiy** [comment]
Maybe the media control should support new ```mime_type``` argument? This way widgets will be able to select custom file types.

**Comment by arielk** [comment]
I merged this issue with another issue #1573 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
