### ISSUE TITLE
Feature request: Add title/name for Media Carousel

### ISSUE THREAD

**Issue by twotweak** [pojome/elementor#3497]
Hello, first of all, thanks to the team for Elementor. 

We have used a lot of different WordPress themes/plugins out there, but this page builder changes the way of working, designing and developing websites.

Right now, we are using the "Media Carousel" widget to show client logos. But we run into the fact that when we have more than 5 items, it becomes unclear and quite difficult, if you use (white) transparent .png images, when you want to change the order of the images.

It would be useful (and nice to have), if there is an option to add a title/name to distinguish the "items" (images) instead of naming them "item 1", "item 2" etc. This is also in the "Form" widget and maybe in other ones as well ...

Looking forward hearing from you.

Cheers! and kind regards,
Fion

**Comment by bainternet** [comment]
How about something like this?

![ivcldja](https://user-images.githubusercontent.com/660572/37026283-9422c9ac-2136-11e8-978b-53c0eb8ef682.png)

Well, its kind of problematic for us to do but you can do it yourself with this little snippet:
```PHP
add_action( 'elementor/element/media-carousel/section_slides/before_section_end', function( $element, $args ) {
	$elementor = \Elementor\Plugin::instance();
	$control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'slides' );

	if ( is_wp_error( $control_data ) ) {
		return;
	}
	$control_data['title_field'] = '<img src="{{{ image.url || \'/wp-content/plugins/elementor/assets/images/placeholder.png\' }}}" width="48px;" height="48px;">';
	$element->update_control( 'slides', $control_data );
}, 10, 2);
```

**Comment by lwoods** [comment]
PERFECT!  Add it to Elementor!

**Comment by cydfer** [comment]
Yes, I have 25 logos in a carousel, with only 5 showing at a time. I have to click through each one to find the one I want to edit since they're labeled as #1 - #25. Would be great to be able to edit the labels (the same way we are able to do in the Navigator.) Also, if that newly entered title could be used as the text in the overlay (rather than the default title provided by WordPress, which is the filename if you forget to input a title), it would speed my workflow.

**Comment by slomeli79** [comment]
> How about something like this?
> Well, its kind of problematic for us to do but you can do it yourself with this little snippet:
> ...


You mentioned that this approach is problematic. Why is that? Is there a risk to adding this snippet?

**Comment by bainternet** [comment]
Mainly because its untested and blots up the panel.

**Comment by joetst** [comment]
Hello~ may I seek the advise as to how we can add title / caption below the images under Media Carousel.  Please refer to the attached picture. Thanks! 
![Screen Shot 2021-03-10 at 10 05 02 PM](https://user-images.githubusercontent.com/80404993/110641328-d9b95980-81ec-11eb-8e66-784167844bbe.png)
