### ISSUE TITLE
Feature Request: Link control for Call To Action widget

### ISSUE THREAD

**Issue by netgain** [pojome/elementor#3498]
## Description

Video with audio dialogue
https://youtu.be/DkahGIJ6WIs

Request to add a drop-down link control to the "link" field in the CTA widget.

**Comment by bainternet** [comment]
@netgain 

What is a drop-down link control?

**Comment by bainternet** [comment]
I merged this issue with  #255 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
