### ISSUE TITLE
[Bug] Button Text color and Border color (also hover state) in SLIDES

### ISSUE THREAD

**Issue by davidefiorio** [pojome/elementor#3505]
I think there is a bug in SLIDES, when I set a color for text and border, it doesn't work. Also in hover state.

Tnk.
Davide 
![screenshot_44](https://user-images.githubusercontent.com/33546042/36370825-5cd5e574-1560-11e8-8bfe-c7e7adcfedd3.jpg)

**Comment by bainternet** [comment]
@davidefiorio 

Seems to be working fine, when we test, could be a conflict with another plugin or your theme,
Please contact our support at support@elementor.com for guidance in resolving this issue.
