### ISSUE TITLE
Custom widgets: how to use php's $settings (no js's settings) from _content_template()?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3506]
Hi, I need to execute a php function that use settings, from _content_template(). Like this:
 
``` php
protected function _content_template() {
    // php here
    // $settings = $this->get_settings();
    // do something with $settings
    ?>

       // do javascript templating

    <?php
    // back to php
}
```

But form there, `$this->get_settings()` will break the program. So how to? I have to set a php variable based on the settings, before doing the js templating.

**Comment by bainternet** [comment]
Use `{{{ settings.var_name }}}`

also, you can always look at existing widgets to get a better idea of how they work. ex: https://github.com/pojome/elementor/blob/master/includes/widgets/button.php#L441

**Comment by stratboy** [comment]
Mmm don't think so. I need to pass the id of an image to a function of mine to get other related data.

this will break everything as well:

`$test = {{{ settings }}}; `

While this will simply output '{{{ settings }}}':

`$test = '{{{ settings }}}'; `

So for now it seems that:

- I cannot use get_settings()
- I cannot use {{{settings}}}

And currently I'm not finding any answers in the code you linked above.

**Comment by pnpetroff** [comment]
+1

I would also like to know that as I need to use it for a PHP variable too.

I have this in `render()`:
```php
$settings = $this->get_settings_for_display();
$product_category = get_term_by('id', $settings['product_category'], 'product_cat');
```
I would like to make that term query  in `_content_template()` too.

**Comment by pnpetroff** [comment]
I checked now, using the `get_settings_for_display()` in `_content_template()` gives a JS error:

![image](https://user-images.githubusercontent.com/1108563/42723710-dd6802a8-876b-11e8-92df-8fb862af9134.png)
