### ISSUE TITLE
CTA elements as a shortcode

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#3508]
[Issue - not necessarily a bug]
I created a section and placed in it (in three columns) a number of individual CTA elements. I then saved the section as a template. When viewed on the original page and as the saved template the CTAs all worked independently. When the template shortcode is placed in a section on a new page in the editor or when viewed online the hover effects for each CTA (zoom and colour overlay) all work individually but the 'content' animation is actioned for all CTA elements at the same time. A demonstration of the issue is shown here [http://elementary.websitesdesigned4u.com/testcta/]. 

It may not be possible to insert a block of CTAs as a shortcode but it would be preferable if it could.

**Comment by bainternet** [comment]
@nickdgreen 

The shortcode issue should be fixed and as for the height of the image simply lower it if you don't want the image to get cut off, this is just how the widget works.

thanks for the feedback.
