### ISSUE TITLE
Changes in page settings are saved automatically issue

### ISSUE THREAD

**Issue by kokers** [pojome/elementor#3510]
I've created "Cover" section in page settings where user can type their tagline and choose image. This is something I can't do with widget because cover is outside "the_content".

The issue is that values are saved automatically when they should be saved after hitting "Update" button. The same goes when choosing a page template or with controls in "style" tab. Users might not be aware, that all changes made in page settings are visible for viewers the moment they change something. This is a real issue, because for example user might experiment with background color, and their customers might visit website in that moment. Or with custom control like text/textarea while they are still typing, and partial content will be shown to customer. 

And there is no way to get back to previous settings because, there are no changes logged in history. So in case someone change their mind, all changes are live anyway, and there is no way to revert back.

Changes made in page settings shouldn't be saved automatically.

**Comment by tristanleboss** [comment]
Yes, I detected this too and this is clearly really dangerous: it's a **critical bug**! You don't expect Elementor to do any change to the post until you hit the "Update" button.

**Comment by norewp** [comment]
I second this request - it has been a pain to extend Elementor in these regions.

**Comment by bainternet** [comment]
We have addressed this in version 2.0.0.

**Comment by tristanleboss** [comment]
Any ETA for 2.0.0 release? If this date is not yet known or far away, couldn't this fix be backported to 1.9.6?
