### ISSUE TITLE
Toggle: unwanted open/close triggering on browser window focus

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3511]
I'm facing strange behaviour of Toggle widget. When switching between browser windows, the toggle items are uncontrollably opened and closed.

Here is the demo: http://demo.remedical.cz/toggle-test/

Steps to reproduce:
1, Open the page above
2. Toggle any item
3. Minimize the browser window or open another
4. Maximize / select the first window - the item closes itself automatically
5. Repeat no. 3 and 4 and item opens itself again.

I don't think this should be happening...

Tested on FF and Chrome, using Astra Theme.

**Comment by bainternet** [comment]
@black-eye 

This happens due to the fact that the trigger we use is `focus` and not `click` and we use `focus` instead of click for accessibility.

**Comment by black-eye** [comment]
@bainternet Can I change it to click, somehow? I find this behaviour quite inconvenient...
Thanks
