### ISSUE TITLE
Custom fonts - @font-face added many times?

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#3513]
The new custom font feature is pretty nice. 

To test it out I setup one custom font with a single weight and then set the Body Text in the Global Fonts area to that font, then had a look at the css. In the global.css file, I counted 28 identical `@font-face` declarations for that font at the bottom. I also noticed that every time a font is specified on an element, a new `@font-face` declaration is generated in the css for that post.

Is this normal?

**Comment by joshallen73** [comment]
I am also having some issues with custom fonts...when i upload into woff2 i cant see the files in media. When i go out of the custom font upload system I can see the fonts have loaded.

I am using a popular font converter to take ot and tt to woff2 - everything is latest build.

**Comment by bainternet** [comment]
@maxwellhibbert fixed in 1.15.1

@joshallen73 that's not related to the OP issue, please feel free to open a new issue.

**Comment by maxwellhibbert** [comment]
@bainternet great! 🍻
