### ISSUE TITLE
{Feature Request} Youtube background centered

### ISSUE THREAD

**Issue by Anthonywp** [pojome/elementor#3514]
Hi all,

I've been using a YouTube video in my background for a landing page and what I've noticed is that the anchor point for the video is on the left hand side. 

So the issue is that if the browser window isn't at the correct aspect ratio to the video it then gets overlapped by the browser window itself and covers the video oddly. 

What I'd like to see is the **anchor point** be changed so that the background video is always **centered** to the browser.

Please see attached images.   

![image](https://user-images.githubusercontent.com/23146126/36406475-427c678e-164b-11e8-80ce-0c0129390d2c.png)
![video not centered](https://user-images.githubusercontent.com/23146126/36406515-8cc3e16e-164b-11e8-99ce-9a1842f0ac9f.JPG)

**Comment by bainternet** [comment]
As far as we know its centered by default,

please fell free to reopen if issue persist.

**Comment by black-eye** [comment]
Following this...
As far as I know, the video background isn't centered by default, it starts on top left corner.

Recently, I have similar problem and had to move the video by custom CSS. 
( https://github.com/pojome/elementor/issues/3327)

**Comment by m0rphee** [comment]
+1 on that one.

My video is not always centered.
> If my web page is over 1550px wide, it is centered. 
> If it is between 1550px and 1024px wide it isn't (The video stops resizing itself with the page and just sticks to the left side)
> Between 1024px and 900px it goes back to resizing itself with the page. 
> Below 900px it stops resizing and sticks to the left side of the page again.

What is this weird behavior ?
You can see it on my page : [here](http://pixel-salad.com/en/home/)

![center](https://user-images.githubusercontent.com/39791995/47411556-6de40c80-d769-11e8-9867-5ea865f9a047.jpg)

**Comment by m0rphee** [comment]
+1 on that one.

My video is not always centered.

• If my web page is over 1550px wide, it is centered.
• If it is between 1550px and 1024px wide it isn't (The video stops resizing itself with the page and just sticks to the left side)
• Between 1024px and 900px it goes back to resizing itself with the page.
• Below 900px it stops resizing and sticks to the left side of the page again.

What is this weird behavior ?
You can see it on my page : [here](http://pixel-salad.com/en/home/)

![center](https://user-images.githubusercontent.com/39791995/47411637-b4396b80-d769-11e8-9331-42b6e27766ec.jpg)
