### ISSUE TITLE
Linked Styles for Elements

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#3515]
This is a big problem with Elementor, in my opinion. Duplicating elements is a great feature when you're building out a design, but then if you want to tweak something, you're going to feel some pain.. in the wrist!  while you mouse around making the same change to all the duplicates as well - or do you delete the duplicates and recreate them again based on the element you just tweaked? - neither is a good answer. The styles need to be linked somehow, hmmm.... maybe with a class!? lol :)  but seriously, elements need linked styles so that updates can be made in one place and it will effect all the other elements that are linked to it.

- The way I see the linking happening, is when an item is duplicated. So maybe a "linked duplicate" button next to the standard duplicate button
- After an item is duplicated, if an change is made to a style property on a linked element (or child of a linked element) the others are also changed
- Maybe when selecting an element with linked styles, it highlights all the linked elements too, in a different colour to the standard blue or yellow, so you know that changes will effect multiple elements.
- And an unlink option to be available on linked elements, to convert them to normal elements.

**Comment by bainternet** [comment]
I merged this issue with  #1479, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
