### ISSUE TITLE
[Feature Request] Predesigned Templates - Hide Option

### ISSUE THREAD

**Issue by Computors** [pojome/elementor#3516]
Hello Elementor! :)

Recently we created a website using your fabulous plugin and because it's a bespoke website that uses only the style and templates that we created we would really need an option to hide the "Predesigned Templates" that are usually loading as the first tab when you want to add a template. Because we will give this website to use to a different company we are a bit concerned that they will have the temptation to load one of the predesigned templates and break the design style. 

Could you add an option in the settings area where we could disable the "Predesigned Templates" when we don't need them, please?

Thank you!
Victoria

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
