### ISSUE TITLE
Add a class corresponding to the widget type to be able to style a control for a specific widget type

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3517]
## Description

Nowadays, it's impossible to apply a CSS style for a control instance belonging to one widget because in the DOM tree, there is no div containing the widget type in a class before reaching the actual control. You can apply a CSS style to a control but it will be applied every time this control is used.

![image](https://user-images.githubusercontent.com/1431508/36418453-2b90f11e-162f-11e8-9be1-e4a7f40cb7ac.png)

**Comment by bainternet** [comment]
This should be fairly easy to do with JavaScript hooks:

```javascript
//add widget type as class
elementor.hooks.addAction( 'panel/open_editor/widget', function( panel, model, view ){ 
	panel.currentPageView.$childViewContainer.addClass( model.get('widgetType' ) );
});
// Add section as class
elementor.hooks.addAction( 'panel/open_editor/section', function( panel, model, view ){ 
	panel.currentPageView.$childViewContainer.addClass( 'section' );
});
// Add column as class
elementor.hooks.addAction( 'panel/open_editor/column', function( panel, model, view ){ 
	panel.currentPageView.$childViewContainer.addClass( 'column' );
});
```

**Comment by tristanleboss** [comment]
That's indeed a solution but I think it would be even easier if it is done natively. Especially, this is already done for individual controls so doing it for widget is coherent. This is also costless to do. I can't reopen the issue though.
