### ISSUE TITLE
WebP Support

### ISSUE THREAD

**Issue by Putzzz** [pojome/elementor#3518]
Since Elementor has growing better and better everyday, I think it would be nice to have WebP Support.

It's being pushed by google these days, I created webP by using another plugin, and yet cannot display it while the content was made by elementor.

Maybe <picture> would be better, and of course the jpg fall back for unsupported browsers.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it and [better browser support](https://caniuse.com/#feat=webp).

Thanks for the feedback.

**Comment by mattbingham** [comment]
The majority of browsers now support this and it's becoming a standard employed by larger companies (Help Scout for example). Would be nice to see this added + fallback.

**Comment by gamertan** [comment]
Seems like making any image input could easily have a srcset option with mobile images just the same as different file types. If you want to include webp with the standard HTML markup, go for it, browsers not supported will use the secondary options that are compatible as fallbacks. 

Is there somewhere that we can communicate that we're interested in this feature specifically?

**Comment by erfan-ilyas** [comment]
+1

**Comment by Webtica** [comment]
+1

**Comment by kovou** [comment]
+1

**Comment by cookiesANDmilk** [comment]
+1

**Comment by Webtica** [comment]
Any news on this?

**Comment by willryanuk** [comment]
+1

**Comment by willryanuk** [comment]
Supported in about 80% of browsers now.

**Comment by jaycburton** [comment]
+1 A client asked me to download files from Airbnb and use those on their site. Airbnb uses WEBP format. First off, I could not upload them as Elementor told me it was an unsupported file type. So I uploaded them manually, and now I cannot select them in the image browser. I understand there might have been some reluctance in adding support for this in the past, but now I see it more as a requirement. WEBP format is not going away.

**Comment by bosslac** [comment]
+1

**Comment by shimsa** [comment]
+1

**Comment by ahiadh** [comment]
+1

**Comment by JBarnden** [comment]
+1

**Comment by miadelprado** [comment]
+1

**Comment by ArnauAloy** [comment]
+1

**Comment by agoc408866** [comment]
I heard images could be optimised by adding images into a subdomain and linking it from there? is that true?

**Comment by gamertan** [comment]
@agoc408866 That doesn't really make sense considering we're looking for a solution in a Content Management System way of thinking. This would be a complete anti-pattern to uploading images to the Media management system in WordPress and using the elements in Elementor. If you externally source images, you can't use elements properly. All those nice content management features, design functionality, and simplicity is thrown out the window. 

Anyone could write their own html or element and just plop it into the HTML element, or even a shortcode, but we're asking for additional feature support for existing elements in this particular software system. Specifically, whenever asked for an image source, being able to source WebP and additionally, selecting fallback file types like png, or jpg.

**Comment by pierredarrieutort** [comment]
+1

**Comment by quakeboy** [comment]
+1

**Comment by AZimmerhofer** [comment]
+1

**Comment by JBarnden** [comment]
+1

**Comment by aboooodaj** [comment]
+1

**Comment by avanish24** [comment]
+1 It's frustrating to know that it isn't added yet.

**Comment by Mulli** [comment]
+1 Still no support for WebP...

**Comment by avanish24** [comment]
That’s right.
I was going to buy elementor pro but after finding this out i had to skip the idea of using elementor completely and we’re rebuilding our site without elementor.

**Comment by PrashGupta** [comment]
+1 for webp support. I am surprised by the response from Elementor that "we will look into it in the future if we see a large demand for it and better browser support". Google has been pushing for webp and today almost half of web traffic is on webp supported browsers. Not sure what are the development team is still waiting for?

**Comment by jaycburton** [comment]
> +1 for webp support. I am surprised by the response from Elementor that "we will look into it in the future if we see a large demand for it and better browser support". Google has been pushing for webp and today almost half of web traffic is on webp supported browsers. Not sure what are the development team is still waiting for?

Excellent question! Given the delay in implementing, I am beginning to believe there must be some underlying reason(s). Or maybe the dev team needs even *more* money...

**Comment by GreenballParis** [comment]
WTF ?! Implement it !

**Comment by ridinghoodmedia** [comment]
+1

**Comment by isotropicdesign** [comment]
This is necessary.

**Comment by shanomano** [comment]
Wow, this is incredibly poor handling from Elementor and it's just shocking. It's been 2 years since this was reported and still NO-GO!...That's an absolute must-have and for Elementor being one of the industry leaders it's just shocking not to have it yet.

**Comment by jaycburton** [comment]
> Wow, this is incredibly poor handling from Elementor and it's just shocking. It's been 2 years since this was reported and still NO-GO!...That's an absolute must-have and for Elementor being one of the industry leaders it's just shocking not to have it yet.

I agree. I have no plans to renew my subscription next month, unless this is fixed. It has been my experience in the decades I have worked with myriad manufacturers that the best way to effect change is to withhold financial support until the desired changes are implemented. If enough people did that, it would be quickly implemented, I feel certain.

**Comment by GreenballParis** [comment]
> I agree. I have no plans to renew my subscription next month, unless this is fixed. It has been my experience in the decades I have worked with myriad manufacturers that the best way to effect change is to withhold financial support until the desired changes are implemented. If enough people did that, it would be quickly implemented, I feel certain.

**Same for me.**

**Comment by gamertan** [comment]
@shilo-ey webp compatibility for the Lightbox was only quietly added on April 21st:
```
2.9.8 – 2020-04-21
Tweak: Added .webp file extension support to Elementor Lightbox
```
I think we're all looking for something a little more formal than a tweak. 

We officially got an element for Lottie files, but we can't get webp compatibility? Surely, you can't be calling fowl for security reasons with webp when you're clearly not that concerned about Lottie security? 

Adding the source set html spec to the image element would fix a lot of the issues we're having with Elementor and images.

**Comment by saberlight** [comment]
+1 for webp support with fallback

**Comment by vaipandragos** [comment]
> Hi all,
> 
> Currently Elementor does not allow users to upload `webp` file extensions due to security reasons.
> 
> Having said that, Elementor uses the file extensions allowed by WordPress, and if you add a support for uploading these files you will be able to use it in our Image widget.
> 
> If you wish to add it you can either use [3rd party plugin](https://wordpress.org/plugins/webp-express/) or add custom code to your theme's `functions.php` file:
> 
> ```
>  add_filter( 'upload_mimes', 'my_myme_types', 1, 1 );
>  function my_myme_types( $mime_types ) {
>    $mime_types['webp'] = 'image/webp'; // Adding .webp extension
>    
>    return $mime_types;
>  }
>  define( 'ALLOW_UNFILTERED_UPLOADS', true );
> ```
> 
> Our Image widget and Lightbox support webp extension.
> 
> Thanks

No, your image widget doesn't support webp extension. I just tested it. An article made with Gutenberg displays webp Images, but a page made in Elementor doesn't display webp images.

**Comment by jaycburton** [comment]
> 
> No, your image widget doesn't support webp extension. I just tested it. An article made with Gutenberg displays webp Images, but a page made in Elementor doesn't display webp images.

Thanks for confirming. I did some testing before, but thought I might have simply overlooked something. It would be nice if the Elementor developers would address this.

**Comment by zatmar** [comment]
New generation formats are necessary. It is important that the support arrives as soon as possible.

**Comment by Junior9235** [comment]
You can use WP Extra File Types plugin to let wordpress uploading webp files. However, when using Elementor, the image will upload and show right on the Elementor editor but will destroy the page when you publish it. Remove the webp file and everything will work fine again. It is ridiculous that as of today (Oct 2020) Elementor does not support webp files. A professional software should support webp files!!

**Comment by senator94** [comment]
Is there a workaround to allow Elementor to use WebP images? I am trying to use a WebP image as a background and there are no options currently available.

**Comment by masoudarvishi** [comment]
Hello. 
Please install and check my plugin:
https://wordpress.org/plugins/hiwebp/

**Comment by curlygirly1** [comment]
I am using LiteSpeed enterprise server with their caching engine, WP plugin and QUIC.clioud. Quic turns my images into WebP and it does so nicely with Elementor - optimizes images and turns them into WebP - APART for any image I use in a section or column BG. Must use some image element instead, bummer. Hope BG images get supported soon!

**Comment by accesoft** [comment]
Please Elementor, add WebP support ASAP, I activated in a websited and it crashed, then I realized the issue... but such a basic thing, that I took it for granted

**Comment by kiputgalak** [comment]
+1

**Comment by gonarg90** [comment]
Hello Elementor team,

Are you planning to support this any time soon? I think the demand for this is clear now. 

Could you please share with us if it is actually planned for some of your upcoming releases?

Thanks

**Comment by diashismelf** [comment]
> Hi all,
> 
> Currently Elementor does not allow users to upload `webp` file extensions due to security reasons.
> 
> Having said that, Elementor uses the file extensions allowed by WordPress, and if you add a support for uploading these files you will be able to use it in our Image widget.
> 
> If you wish to add it you can either use [3rd party plugin](https://wordpress.org/plugins/webp-express/) or add custom code to your theme's `functions.php` file:
> 
> ```
>  add_filter( 'upload_mimes', 'my_myme_types', 1, 1 );
>  function my_myme_types( $mime_types ) {
>    $mime_types['webp'] = 'image/webp'; // Adding .webp extension
>    
>    return $mime_types;
>  }
>  define( 'ALLOW_UNFILTERED_UPLOADS', true );
> ```
> 
> Our Image widget and Lightbox support webp extension.
> 
> Thanks

++++++ works great! thnx!

**Comment by dwillitzer** [comment]
+1 👍🏼 for WebP-support with jpg-fallback!

**Comment by GALASIO** [comment]
+1 👍🏼 for WebP-support with jpg-fallback!

**Comment by benimub** [comment]
+1 👍🏼 for WebP-support with jpg-fallback!

**Comment by jonasborneland** [comment]
+1 👍🏼 for WebP-support with jpg-fallback!

**Comment by monsefsolutions** [comment]
+1 👍🏼 for WebP-support with jpg-fallback!

**Comment by pixeldesignstudio** [comment]
+1 👍🏼 for WebP-support with jpg-fallback!

**Comment by dmenshakov** [comment]
Hello everyone!

I also faced a similar issue. For generating WebP images, I use the WebP Express plugin along with Elementor. However, I noticed that the WebP Express plugin didn't automatically replace images in Elementor widgets.

Below is a code snippet that solves this problem. This code will update image URLs to their WebP counterparts if they exist.

Important: Make sure to first generate the WebP images using the WebP Express plugin. Once you have the WebP images, the code below will update the paths accordingly. Just ensure that the WebP version of the image is available on your server.

/wp-content/webp-express/webp-images/uploads/.. - your url with WebP Express Plugin.
/wp-content/uploads/.. - your initial url.

/**
 * Replaces image URLs with WebP versions in the content.
 *
 * This function scans through the content and replaces image URLs
 * with their WebP counterparts if they exist. It handles both `src`
 * and `srcset` attributes for images.
 *
 * @param string $content The content to be filtered.
 * @return string The filtered content with WebP images.
 */
function replace_images_with_webp($content) {
    // Replace `src` attribute for images
    $content = preg_replace_callback(
        '/<img[^>]+src="([^">]+)"/i',
        function($matches) {
            $src = $matches[1];
            // Convert image URL to WebP path on the server
            $webp_src = str_replace('/wp-content/uploads/', '/wp-content/webp-express/webp-images/uploads/', $src) . '.webp';
            $webp_path = ABSPATH . parse_url($webp_src, PHP_URL_PATH);

            // Check if the WebP image exists on the server
            if (file_exists($webp_path)) {
                return str_replace($src, $webp_src, $matches[0]);
            }
            return $matches[0];
        },
        $content
    );

    // Replace `srcset` attribute for images
    $content = preg_replace_callback(
        '/srcset="([^"]+)"/i',
        function($matches) {
            $srcset = $matches[1];
            // Convert srcset URLs to WebP paths
            $webp_srcset = preg_replace('/\/wp-content\/uploads\/([^ ]+)\.(jpg|jpeg|png)(\s+\d+w)/i', '/wp-content/webp-express/webp-images/uploads/$1.$2.webp$3', $srcset);

            // Check each WebP image in the srcset
            $webp_srcset_items = explode(', ', $webp_srcset);
            $valid_webp_srcset = [];

            foreach ($webp_srcset_items as $item) {
                list($url, $size) = explode(' ', $item);
                $webp_path = ABSPATH . parse_url($url, PHP_URL_PATH);
                if (file_exists($webp_path)) {
                    $valid_webp_srcset[] = $item;
                }
            }

            return 'srcset="' . implode(', ', $valid_webp_srcset) . '"';
        },
        $content
    );

    return $content;
}

// Apply the WebP image replacement filter to various content types
add_filter('the_content', 'replace_images_with_webp', 20);
add_filter('widget_text', 'replace_images_with_webp', 20);
add_filter('widget_text_content', 'replace_images_with_webp', 20);
add_filter('elementor/widget/render_content', 'replace_images_with_webp', 20);
add_filter('woocommerce_product_get_description', 'replace_images_with_webp', 20);
add_filter('woocommerce_product_get_short_description', 'replace_images_with_webp', 20);

**Comment by curlygirly1** [comment]
Thank you!
Don't seem to have issues this year with Elementor and WebP/AVIF images.

FYI, I now use Converter for Media plugin (with a $50/y generous Pro plan)
for WebP and AVIF and am no longer using LiteSpeed Cache plugin.

I replaced it with a MUCH better and easier solution - CloudFlare Super
Page Cache plugin!
With a free CF account I need to host the WebP/AVIF myself. With a CF Pro
they host all images on their edge and works wonders with these 2 plugins.
Little speed difference for page load with free CF as AVIF is super fast to
load.
