### ISSUE TITLE
Elementor load time increasing

### ISSUE THREAD

**Issue by erubianes** [pojome/elementor#3521]
Hi!

I've tested my plugins load time with P3 Plugin Profiler and Elementor Pro uses 32% of the load time (Elementor Free: 10%)

I have everything updated: WP and my GeneratePress Pro theme.

Is this normal?

Thank you!

![28167891_10216260164044921_2374032967167144393_n](https://user-images.githubusercontent.com/36669879/36432220-f9fc7634-1659-11e8-8912-226ea7e46620.jpg)

**Comment by dasigna** [comment]
i really dont know what this plugin does exactly and whats measured in detail...
but i can clearly state, that loading times _extremely_ depend on hosting! no matter if back- or frontend.
some sites of mine with gp and el pro have load times around a second and clearly beyond on dedicated wp nginx vserver hosting. others with comparable configurations taking up to four seconds on 'usual' shared hosting.
responding times when working in backend (and elementor) accordingly from really not remarkable with the first and having to wait for response all the time with the latter...

so i dont see what this plugin profiler would be useful for and what conclusion one has to fiddle out of this result. check your site with pingdom or gtmetrix and you'll likely get a far better overview whats really going on :)

**Comment by norewp** [comment]
As mentioned in the FB group, the test by the OP is inconclusive and therefore can not be taken as a benchmark.

Run multiple test with multiple combination of plugins active, run multiple tests with just Elementor core & Pro active, use multiple tools to run the tests and get an overall average and then conclude on the impact.

Until then, the information depicted above is of no value let alone give pointers on where improvements can be made!

**Comment by bainternet** [comment]
@erubianes 

What @dasigna and @norewp said is correct, no real value to this "profiling" and if you use any kind of page/memory cache mechanism then this really has no value. 

Thanks for the feedback.
