### ISSUE TITLE
Nav Menu Bug - dropdowns with rounded corners

### ISSUE THREAD

**Issue by krann** [pojome/elementor#3523]
As you can see from the pic - the rounded corners is erroneously applied to the first item on the dropdown.

![screen shot 2018-02-20 at 16 07 01](https://user-images.githubusercontent.com/33498560/36435108-a75c090e-1658-11e8-9cc7-2e8b05f27186.jpg)

**Comment by bainternet** [comment]
@krann 

can you provide steps to replicate? a link?

**Comment by krann** [comment]
Hi Raz

Create a horizontal dropdown menu using Elementor.

Make one of the dropdowns three or four items deep.

Set the dropdowns to have rounded corners in Elementor.

Divide the dropdown items with a different coloured horizontal bars (typically 1 or 2 pixels wide).

Check to see if it is working OK.

If it is working as it should, let me know and I’ll provide links and even a movie of what I’m doing!

John

**Comment by bainternet** [comment]
@krann 

again we can't replicate,

Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by krann** [comment]
Hi Raz/Support

Tricky for me to explain, so I’ve done a quickie movie on this Elementor nav menu issue.

Please have a look. (I spotted another issue too - hover shapes do not replicate rounded corners - also explained in movie)

Visit: http://www.broadstonesschool.co.uk/elementor-dropdown-issue.mp4

Thanks!

John

**Comment by krann** [comment]
-- Please reply above this line --

-----------------------------------------------------------
## Soyket replied, on Feb 28 @ 5:45 (UTC):

Hi John, 

I appreciate you took the time to write this feedback.

We will look into it and see what can be done on the subject.

Best Regards, 

--
 Soyket from Elementor 
Facebook [1] | Twitter [2] | YouTube [3]
 Join the conversation & learn from our Elementor Community [4].

 How would you rate my reply? 



Links:
------
[1] https://www.facebook.com/elemntor/
[2] https://twitter.com/elemntor
[3] https://www.youtube.com/c/elementor
[4] https://www.facebook.com/groups/Elementors/


-----------------------------------------------------------
## John Shiel - Krann Web Development sent a message, on Feb 27 @ 14:20 (UTC):

Hi Raz/Support 
 Tricky for me to explain, so I've done a quickie movie on this
Elementor nav menu issue. 
 Please have a look. (I spotted another issue too - hover shapes do
not replicate rounded corners - also explained in movie) 
 Visit:
http://www.broadstonesschool.co.uk/elementor-dropdown-issue.mp4 [1]  
 Thanks! 
 John 

 On 27 Feb 2018, at 12:25, raz ohad <notifications@github.com
[2]> wrote: 

	@krann [3] 

	again we can't replicate, 

	Please contact our support at support@elementor.com [4] for guidance
in resolving this issue. 

	-
 You are receiving this because you were mentioned.
 Reply to this email directly, view it on GitHub [5], or mute the
thread [6].     
 

Links:
------
[1] http://www.broadstonesschool.co.uk/elementor-dropdown-issue.mp4
[2] mailto:notifications@github.com
[3] https://github.com/krann
[4] mailto:support@elementor.com
[5]
https://github.com/pojome/elementor/issues/3523#issuecomment-368857128
[6]

**Comment by krann** [comment]
-- Please reply above this line --

-----------------------------------------------------------
## Boaz replied, on Feb 28 @ 13:38 (UTC):

Hi John, 

Thank you for this video - it demonstrates this bug perfectly.
We will look into it and resolve it as soon as possible.

I will keep you updated.

--
 Boaz from Elementor 
Facebook [1] | Twitter [2] | YouTube [3]
 Join the conversation & learn from our Elementor Community [4].

 How would you rate my reply? 



Links:
------
[1] https://www.facebook.com/elemntor/
[2] https://twitter.com/elemntor
[3] https://www.youtube.com/c/elementor
[4] https://www.facebook.com/groups/Elementors/


-----------------------------------------------------------
## Soyket replied, on Feb 28 @ 5:45 (UTC):

Hi John, 

I appreciate you took the time to write this feedback.

We will look into it and see what can be done on the subject.

Best Regards, 

--
 Soyket from Elementor 
Facebook [1] | Twitter [2] | YouTube [3]
 Join the conversation & learn from our Elementor Community [4].

Links:
------
[1] https://www.facebook.com/elemntor/
[2] https://twitter.com/elemntor
[3] https://www.youtube.com/c/elementor
[4] https://www.facebook.com/groups/Elementors/


-----------------------------------------------------------
## John Shiel - Krann Web Development sent a message, on Feb 27 @ 14:20 (UTC):

Hi Raz/Support 
 Tricky for me to explain, so I've done a quickie movie on this
Elementor nav menu issue. 
 Please have a look. (I spotted another issue too - hover shapes do
not replicate rounded corners - also explained in movie) 
 Visit:
http://www.broadstonesschool.co.uk/elementor-dropdown-issue.mp4 [1]  
 Thanks! 
 John 

 On 27 Feb 2018, at 12:25, raz ohad <notifications@github.com
[2]> wrote: 

	@krann [3] 

	again we can't replicate, 

	Please contact our support at support@elementor.com [4] for guidance
in resolving this issue. 

	-
 You are receiving this because you were mentioned.
 Reply to this email directly, view it on GitHub [5], or mute the
thread [6].     
 

Links:
------
[1] http://www.broadstonesschool.co.uk/elementor-dropdown-issue.mp4
[2] mailto:notifications@github.com
[3] https://github.com/krann
[4] mailto:support@elementor.com
[5]
https://github.com/pojome/elementor/issues/3523#issuecomment-368857128
[6]

**Comment by krann** [comment]
-- Please reply above this line --
-----------------------------------------------------------
## Boaz replied, on Apr 9 @ 7:27 (UTC):

Hi John, 

Just wanted to let you know that we fixed this bug and it will be
released in the next update of Elementor Pro.

Kind Regards,
--
 Boaz from Elementor 
Facebook [1] | Twitter [2] | YouTube [3]
 Join the conversation & learn from our Elementor Community [4].

 How would you rate my reply? 



Links:
------
[1] https://www.facebook.com/elemntor/
[2] https://twitter.com/elemntor
[3] https://www.youtube.com/c/elementor
[4] https://www.facebook.com/groups/Elementors/


-----------------------------------------------------------
## Boaz replied, on Feb 28 @ 13:38 (UTC):

Hi John, 

Thank you for this video - it demonstrates this bug perfectly.
We will look into it and resolve it as soon as possible.

I will keep you updated.

--
 Boaz from Elementor 
Facebook [1] | Twitter [2] | YouTube [3]
 Join the conversation & learn from our Elementor Community [4].

Links:
------
[1] https://www.facebook.com/elemntor/
[2] https://twitter.com/elemntor
[3] https://www.youtube.com/c/elementor
[4] https://www.facebook.com/groups/Elementors/


-----------------------------------------------------------
## Soyket replied, on Feb 28 @ 5:45 (UTC):

Hi John, 

I appreciate you took the time to write this feedback.

We will look into it and see what can be done on the subject.

Best Regards, 

--
 Soyket from Elementor 
Facebook [1] | Twitter [2] | YouTube [3]
 Join the conversation & learn from our Elementor Community [4].

Links:
------
[1] https://www.facebook.com/elemntor/
[2] https://twitter.com/elemntor
[3] https://www.youtube.com/c/elementor
[4] https://www.facebook.com/groups/Elementors/


-----------------------------------------------------------
## John Shiel - Krann Web Development sent a message, on Feb 27 @ 14:20 (UTC):

Hi Raz/Support 
 Tricky for me to explain, so I've done a quickie movie on this
Elementor nav menu issue. 
 Please have a look. (I spotted another issue too - hover shapes do
not replicate rounded corners - also explained in movie) 
 Visit:
http://www.broadstonesschool.co.uk/elementor-dropdown-issue.mp4 [1]  
 Thanks! 
 John 

 On 27 Feb 2018, at 12:25, raz ohad <notifications@github.com
[2]> wrote: 

	@krann [3] 

	again we can't replicate, 

	Please contact our support at support@elementor.com [4] for guidance
in resolving this issue. 

	-
 You are receiving this because you were mentioned.
 Reply to this email directly, view it on GitHub [5], or mute the
thread [6].     
 

Links:
------
[1] http://www.broadstonesschool.co.uk/elementor-dropdown-issue.mp4
[2] mailto:notifications@github.com
[3] https://github.com/krann
[4] mailto:support@elementor.com
[5]
https://github.com/pojome/elementor/issues/3523#issuecomment-368857128
[6]
