### ISSUE TITLE
Keyboard Shortcuts Cheat Sheet & More Shortcuts!

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#3526]
It would be nice if there was an info panel somewhere to view all the keyboard shortcuts. And more keyboard shortcuts! 😃 

Missing Shortcuts:
- Update (publish)
- Add a widget and focus search
- Add a global
- Open settings
- Preview changes
- Save as template

**Comment by JoelEadeDesign** [comment]
Bump

**Comment by arielk** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by bentalgad** [comment]
+1 for update (publish) shortcut. i don't get the logic of having a save draft shortcut and not having an update shortcut when (at least with my workflow) the last one is much more used then the first one.

**Comment by zevrix** [comment]
I add my voice for hotkey for the UPDATE command.

**Comment by bentographics** [comment]
Pump. 

An "Update/Publish" hotkey would really improve my productivity.

**Comment by zevrix** [comment]
> An "Update/Publish" hotkey would really improve my productivity.

This simple feature has been requested for years. But assigning a keyboard shortcut to a button is something that, unfortunately, can only be achievable by a future AI generation that will require quantum computers.

In the meantime, you can use a macro utility to assign a keyboard shortcut to a mouse click at a specific location. I'm on Mac and using Keyboard Maestro for this task for years. I'm sure there are similar tools on Windows, too. Obviously, it requires your Update button to be at the same exact location at all times.

**Comment by zevrix** [comment]
I'm curios why it's marked as 'Closed'?
