### ISSUE TITLE
Inline editing select all Bug

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#3528]
When you select all and try to wirte anything... the text dissapears but anythig you type does not appear.

https://screencast-o-matic.com/watch/cFnri9o96T

**Comment by bainternet** [comment]
@dudaster 

can you provide your system info, we can't replicate.

**Comment by dudaster** [comment]
it seems with the last update is working again

**Comment by dudaster** [comment]
It seems the problem appears only using a specific theme. Hm... I'll troubleshoot some more to see why this is happening.

**Comment by dudaster** [comment]
I've made some investigation and it was a plugin with the css
 h1:empty { display:none; } 

I fixed it with .elementor-editor-active h1:empty {
  display:block;
}
