### ISSUE TITLE
Dynamical preselected value at page enter

### ISSUE THREAD

**Issue by alessandroboabab** [pojome/elementor#3530]
## Description

Hi,
I'm using the PRO Elementor form builder and I've got a question:

I have different pages with different products into my website. I want that the user select the button "Ask for a quote" into a product page and the link open the Quotation page.

In the quotation form there's a dropdown selection with the products list.Is it possibile that the dropdown selector is already selected, based on the page where user arrived from?

For example product page is called "Volvo", when user click the CTA "ask a quote", the link open the quotation page and in the quotation form the dropdown selection called "which car are you interested in?" the selection "Volvo" is already selected.

Thank you very much
Alessandro Fornoni

**Comment by bainternet** [comment]
@alessandroboabab 

This feature is not yet possible but it's in our plans.

**Comment by bainternet** [comment]
I merged this issue with  #4934, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
