### ISSUE TITLE
Feature Request: Extend Form Widget with ActiveCampaign custom Fields

### ISSUE THREAD

**Issue by siro83** [pojome/elementor#3531]
In ActiveCampaign it is possible to create your own custom fields.
It would be great if there was a chance to map them in the FormWidget as well.

The custom fields can be read out via the ActiveCampaign API with 'list_field_views'.

https://www.activecampaign.com/api/example.php?call=list_field_view

Do you see a Chance to implement this Feature?

**Comment by bainternet** [comment]
@siro83 

should be updated in the next version or two.

thanks.

**Comment by siro83** [comment]
Perfect, thanks.

**Comment by derlanoliver** [comment]
Has this feature already been added?
Where can I find it?
