### ISSUE TITLE
Issue with Cloning Widget

### ISSUE THREAD

**Issue by vrundakansara** [pojome/elementor#3532]
Hey,

I have built a custom widget and seems like the node_id does not change on the cloning action.
In the video above I have simply fetched the node_id and echoed it in render function.

http://bsf.io/wxmnf

After the clone, I still get the same ID. Is this a known issue?

Regards,
Vrunda Kansara

**Comment by bainternet** [comment]
@vrundakansara 

Not a real issue, when you clone/duplicate a section/widget there is no server-side involved and only the HTML is cloned. If you change something that will cause the server to re-render you will see that the id of the actual clone is different, or if you just look at the markup you will see that the widget has a   unique `data-id` attribute.
