### ISSUE TITLE
Page Style - Background colour and photo not showing on live website

### ISSUE THREAD

**Issue by sarahdenise** [pojome/elementor#3534]
Hi,

I put a background photo and background colour on the (overall) page. It shows how it should be on Editing mode. I clicked update but then it wouldn't show on the live website. 

I am sure it is not a loading issue because I have been waiting for a while and I also inspected the website in Chrome and Mozilla. The css for the background is not there.

For now, I put the background on the section and the background photo is showing but could you please fix this issue. Thanks

Elementor Version 1.9.5
Elementor Pro Version Version 1.15.0

I am using GeneratePress - Child Theme.

**Comment by bainternet** [comment]
@sarahdenise 

we can't replicate this issue,
Please contact our support and see if they can help you. support@elelemntor.com
