### ISSUE TITLE
Add a way to remove the last element of a repeater field

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3536]
## Description

I use the repeater control in one of my homemade Elementor widget. I didn't find a way to allow the last remaining element to be removed. It should be possible to allow the removal of the last element. Indeed, for example, a repeater field can be an optional one. I think this should be a setting of the repeater field.

## Steps to reproduce

Add a "Tabs" widget. Remove the second tab => It's impossible to remove the remaining one.

**Comment by bainternet** [comment]
@tristanleboss 

The repeater control has a `prevent_empty` parameter which defaults to true, simply set yours to false:

```PHP
$this->add_control(
	'repeater_id',
	[
		'label'         => __( 'My Repeater', 'text-domain' ),
		'type'          => Controls_Manager::REPEATER,
		'fields'        => $repeater_fields,
		'prevent_empty' => false,
	]
);

**Comment by tristanleboss** [comment]
Thanks. Don't hesitate to add this information in the Repeater field class header... that's where people will look ;)
