### ISSUE TITLE
How to update slick js?

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3538]
Hi, I see that elementor is currently shipped with Slick js v1.6.0, which is an old one. For other things and full mobile support, I need latest 1.8.0. I'd like not to load it twice, though. Which is the best practice for override/upgrade js dependencies?

Thank you

**Comment by stratboy** [comment]
``` php
add_action('elementor/frontend/after_register_scripts', function() {
  wp_deregister_script('jquery-slick');
  wp_register_script('jquery-slick',get_stylesheet_directory_uri() . '/bower_components/slick-carousel/slick/slick.min.js',['jquery',],'1.8.0',true);
},15);
```

Probably..

**Comment by KingYes** [comment]
Thanks

**Comment by stratboy** [comment]
Mmmm I still have some doubts. When is Slick loaded in frontend?

If I just log console.log('Slick') I get undefined.

Is it always loaded or only if required by in page widgets?
