### ISSUE TITLE
Left panel is broken for some widgets on sub-sites of a multisite network

### ISSUE THREAD

**Issue by Tilmn** [pojome/elementor#3542]
I experience a strange issue: For some widgets the left panel is empty. No editing there at all.

That is the case for sub-sites of a multisite network, the main site is fine.

It happens for text editor elements, accordions and toggles. Maybe the ones that have the new inline editing? When these elements are selected on the right, the panel on the left is only grey. See screenshot.
![bildschirmfoto 2018-02-21 um 21 48 11](https://user-images.githubusercontent.com/97577/36505030-99a743fa-1752-11e8-9a07-ba562bc6e121.png)

**Comment by Tilmn** [comment]
Additional info: I deactivated all plugins and activated Elementor only for the sub-site, not network-wide. The editing panel is really not there, not just invisible because of CSS. No errors on the console.

What can I do to sort this out?

**Comment by bainternet** [comment]
@Tilmn 

please contact our support and see if they can help you support@elementor.com
