### ISSUE TITLE
No preview images for SVG after update to E Pro 1.15.1

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3543]
Very strange problem here: after update to new version of Elementor Pro (I went stright to 1.15.1., not sure about 1.15) there's no preview image for newly uploaded svg images.

In the image below, there are 2 sets of three very same images. Those with the previews are uploaded with E Pro deactivated, and those without previews with E Pro activated.

![obrazek](https://user-images.githubusercontent.com/5634870/36510226-a0dae928-1762-11e8-90dd-89b5dac1662d.png)

Have no idea where this problem came from, but it's there.
SVG support is provided by [SVG Support Plugin](https://wordpress.org/plugins/svg-support/)

**Comment by black-eye** [comment]
And just to make it clear: the problem wasn't present in the previous version.

**Comment by black-eye** [comment]
And one more update:

In the "line view" all the previews are correct (don't mind that white on white isn't visible):

![obrazek](https://user-images.githubusercontent.com/5634870/36510890-e7a00f8a-1764-11e8-9d94-ee21b17dbbf7.png)

Really strange...

**Comment by Deralict** [comment]
I've got the exact same issue. It's definitely something in Elementro Pro 1.15.1.

**Comment by Deralict** [comment]
I had to restore a previous version of the plugin to continue developing this site, but found that I had to go back to 1.14.2 to get SVG Support to work properly again. Therefore the problem was introduced in v.1.15.0 of Elementor Pro.

**Comment by bainternet** [comment]
thanks, 

should be fixed in next version.
