### ISSUE TITLE
Form Widget: Missing color settings for checkbox text when labels are hidden

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3544]
When the form labels are off, you cannot chose the color for checkbox text:

![obrazek](https://user-images.githubusercontent.com/5634870/36512592-65d7a9ca-176b-11e8-9330-b72f065a3602.png)

The text is outputted correctly (one item in the screenshot is selected to manifest that), it just cannot be seen because of the dark color. Options in Style > Field > Text Color are applied only to placeholders and options for Style > Labels are not shown.

**Comment by bainternet** [comment]
@black-eye 

thanks for reporting, should be fixed in 1.15.3
