### ISSUE TITLE
Google Fonts Inclusion Bloated

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#3545]
I love the editor. And was just looking to improve speed on the site overall. 
I created a blank page, with a single Headline using the DEFAULT FONT (which is set). It produces, this inclusion.
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic">

I checked one other setting, by actually ADDING the typography weight to "300". And it still includes the entire list. 

For performance purposes this is not ideal loading the entire font family and every weight etc. 
Is it possible to filter the ones out we don't want? Or just enable certain ones? 

Thanks.

**Comment by bainternet** [comment]
@stickypages 

Yes there is something you can do to optimize it, you can use the provided filter hook to tell elementor not to load your Google fonts for you, and instead, you manually enqueue just the font families/weights you need.

```PHP
// Tell elementor not to load google fonts for me
add_filter( 'elementor/frontend/print_google_fonts', '__return_false' );

**Comment by stickypages** [comment]
Yeah for sure we can do that. Might be something to look into for future dev to improve the way that it loads the fonts. Thanks anywho.

**Comment by the-rep** [comment]
> @stickypages
> 
> Yes there is something you can do to optimize it, you can use the provided filter hook to tell elementor not to load your Google fonts for you, and instead, you manually enqueue just the font families/weights you need.
> 
> ```
> // Tell elementor not to load google fonts for me
> add_filter( 'elementor/frontend/print_google_fonts', '__return_false' );
> ```

Hi @bainternet i've got a similar query. which file do i need to update to add this line of code in?
