### ISSUE TITLE
Add Option to accordion widget to set the first item as 'active'/'open'

### ISSUE THREAD

**Issue by guytzhak** [pojome/elementor#3546]
I add an option to choose if the first item in accordion is open by default or not.

this is the fix:
https://github.com/guytzhak/elementor/commit/0c991fb1c5a19e0020934a1cb98785c553f88ceb

**Comment by guytzhak** [comment]
Link to the commet:
[https://github.com/guytzhak/elementor/commit/0c991fb1c5a19e0020934a1cb98785c553f88ceb](url)

**Comment by arielk** [comment]
I merged this issue with another issue #2756 in the same subject so we could deal with it more efficiently. 
Thanks for your feedback!
