### ISSUE TITLE
Nav Menu Bug - Align doesn't work properly

### ISSUE THREAD

**Issue by MincheolC** [pojome/elementor#3548]
## Bug
Elementor Pro Nav Menu's layout - align doesn't work properly.
It works properly in elementor editor, but after published, it **keeps align left.**

e.g.)
![2018-02-22 5 26 39](https://user-images.githubusercontent.com/22284602/36527581-a5a56b66-17f5-11e8-8dfe-7e5933a77705.png)

## Steps to reproduce

1. edit with elementor
2. add new section
3. drag & drop nav menu widget
4. Layout - horizontal
5. Align: Right (It looks working properly in edit view)
![2018-02-26 4 25 33](https://user-images.githubusercontent.com/22284602/36657898-bf4a45f4-1b11-11e8-9e47-016a35b9ffc1.png)
6. Update
7. Check preview (Align right doesn't applied)
![2018-02-26 4 26 26](https://user-images.githubusercontent.com/22284602/36657920-cfe03c20-1b11-11e8-9af9-04041c39532b.png)

## Environment

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | nginx |  
MySQL version: | 5.5.5 |  
PHP Version: | 7.0.27 |  
PHP Max Input Vars: | 6144 |  
PHP Max Post Size: | 2047M |  
GD Installed: | Yes |  
Write Permissions: | There are some writing permissions issues with the following directories/files: 		 - WordPress root directory |  
Elementor Library: | Connected

WordPress Environment |   |  
-- | -- | --
Version: | 4.9.4 |  
Site URL: | https://enertalk.energy |  
Home URL: | https://enertalk.energy |  
WP Multisite: | No |  
Max Upload Size: | 2 GB |  
Memory limit: | 256M |  
Language: | ko-KR |  
Timezone: | Asia/Seoul |

**Comment by bainternet** [comment]
@MincheolC 

Please provides steps to replicate and your system info.

**Comment by MincheolC** [comment]
@bainternet Ok I updated issue.

**Comment by bainternet** [comment]
@MincheolC 

We can't replicate, Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by LethalRabbit** [comment]
Did you happen to find a fix for this? I'm suffering from the same problem, trying to center align my nav menu which works in the preview, but on the website it keeps aligning it to the left.

**Comment by MincheolC** [comment]
@LethalRabbit Yes. I applied class-id and custom css to nav-menu as below code.
```
#nav-menu {
    float:right;
}
```

**Comment by colourwheel** [comment]
I also have this bug, and I tried the fix sent by @MincheolC above, but I'm sure I'm not entering it in the right place, or properly. I've placed the code in the Custom CSS field for the menu widget, column and the section, but none have any effect. I added the ID  nav-menu in the CSS ID field for the each of these things as well. Can someone explain how to do it? Thanks.

**Comment by antiocol** [comment]
Same problem here. In the Elementor Editor the nav tag is decorated with the classes `.elementor-nav-menu__align-right .elementor-nav-menu` but in the published version these classes are not present.

**Comment by gbard** [comment]
Same problem here!
