### ISSUE TITLE
Progress bar bug

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3549]
Hi, I think I've just found a bug on the progress bar widget: if you set percentage to not to show, the progress bar itself will be hidden as well.

![schermata 2018-02-22 alle 12 01 34](https://user-images.githubusercontent.com/437598/36535055-ad48232c-17c8-11e8-9f5d-137083eb2c77.png)

On the picture you can see the second bar under the red one, it's not showing (greyed out). That's because I selected 'hide percentage'.

**Comment by bainternet** [comment]
@stratboy 

We can't replicate, what theme are you using?

**Comment by stratboy** [comment]
@bainternet 

A theme of mine.  I do not use 3rd party themes. I build ad hoc themes for every single project.

**Comment by bainternet** [comment]
@stratboy 

I'm asking because it looks like its caused by CSS form your theme or 3d party plugin, any link?

**Comment by stratboy** [comment]
I can't give you a link, sorry, it's still a staging project. Anyway, I managed forcing the hiding of percentage via css. This also means it weren't my styles before, I think.

**Comment by bainternet** [comment]
glad you figured it out.
