### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#3550]
When exporting a template from myTemplates the files is exported immediately with a name supplied by Elementor (page ID - date). Could a Template Export settings option be added to Elementor settings that if not set would export as now but could be set to "Title" so that the file would be exported with the page title or "Prompt" where a window would be opened to enable the entry of a file name before being exported.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
