### ISSUE TITLE
[feature request] - image preload 

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3554]
Hi, it would be great if you implemented an image preload option for images, on a per-image basis.

You could use https://github.com/aFarkas/lazysizes

It would be important that:

- It's done on a per-image basis, or maybe better, on a per-section basis so that is up to the user to decide what image(s) to preload.

- it has some an hook to respond to lazysizes's load events 

Use case:

BIG big responsive image header. It will take some time to load, and even if less time, it's enough to cause all the elements below to trigger their visualisation actions. For example counters and progress bars. The user will likely lose the animation, since it will be triggered during that fraction of time while the image is loading but without any dimension. It would be great if one can hook into its load event to show the counters, so their anymations will be delayed.

**Comment by bainternet** [comment]
@stratboy 

Feels like a 3rd party plugin territory, so currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
