### ISSUE TITLE
Create a FAQ page with code snippets / solutions provided in this issues tracker

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3557]
I think it would be a super idea to create a FAQ page with all the code snippets / solutions given on this issues tracker by plugin developpers.

For example, you gave me answers here (https://github.com/pojome/elementor/issues/3536#event-1486603668) and there (https://github.com/pojome/elementor/issues/3517#issuecomment-366994924) which may be useful to other developpers.

Creating such a page would allow people to search things inside or simply read it to see the potential behind the plugin.

Nowadays, issues with solution are closed and not that convenient to search in (by default, GitHub search in open issues). Anyway, closed issues is probably not the location people will search for.

**Comment by bainternet** [comment]
@tristanleboss 

Thanks for the suggestion, we are working on a Developers API/Docs and everything here labeled with "Developer API" will be included there.
