### ISSUE TITLE
[feature request] Can't hide Elementor from editor role

### ISSUE THREAD

**Issue by Artneo7** [pojome/elementor#3558]
Hi,

I create blog focused websites for my clients. They only should see the "Panel" and "Posts" inside WordPress admin area. Right now, it's not possible to remove the Elementor icon inside the menu of the editor role. I tried using the Adminimize plugin, but it does not work. Please, could you please add a way to hide it only for editor role, for exemple? I tried using the Adminimize plugin, but it does not work.

Images: https://imgur.com/a/QffzM

Thanks!

**Comment by bainternet** [comment]
This is not something I see happening anytime soon.

try this https://wordpress.stackexchange.com/questions/136058/how-to-remove-admin-menu-pages-inserted-by-plugins
