### ISSUE TITLE
How to change Section settings default value?

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#356]
Hi guys, is there a proper way to change the default value of Section settings?

For example, I want to change the default value of Content Width to 1080px instead of 1140px (your default). And I want to change the default value of Columns Gap to "extended" which is 15px.

**Comment by yehudah** [comment]
Hi,
For the content with we working on it.
For column gap you can do it just with custom CSS in your theme.

**Comment by qwik3r** [comment]
Was this ever implemented?

**Comment by atripolskyy** [comment]
still interesting!
