### ISSUE TITLE
Taking control of waypoints

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3560]
Hi, is there a way to take control of the elementor's instance of Waypoint and use its api?

I tried several things and look in your code but till now haven't found anything useful.

**Comment by bainternet** [comment]
Currently, You can't, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by oooh-boi** [comment]
It's possible by using 
`var waypoints = $('#element-id').elementorWaypoint({ ... });`
