### ISSUE TITLE
Is there way for display title_field with condition?

### ISSUE THREAD

**Issue by tranlamnhatnam** [pojome/elementor#3563]
I have `Repeater` control with 2 field for 2 type of Title:

- Title (id: title, type: TEXT)
- Title editor (id: title_editor, type: WYSIWYG)

And i want to display title with `title_field`.

- When `title` blank `title_field` will display content of `title_editor`.
- When `title_editor` blank `title_field` will display content of `title` . 

Can i do that?

**Comment by bainternet** [comment]
The `title_field` parameter accepts an underscore template so you can use any javascript to create you condition/logic but in your case it should be very simple for ex:

```{{{ title || title_editor }}}```
