### ISSUE TITLE
Elementor Feature Request

### ISSUE THREAD

**Issue by krann** [pojome/elementor#3564]
The Elementor widget called 'Yoast Breadcrumbs' is described on the page:
https://elementor.com/single-post-widgets/
Whoever makes the 'Yoast Breadcrumbs' widget, please can they adapt it to give us a 'Yoast Page Title' widget too? 
It would be a very useful inclusion in the Headers Footer Template plugin which lets Elementor users create a header and footer for their site. 
The reason is, there is no similar widget I can put in Headers Footer Template which can give me the Page Title. Aside from the 'Yoast Breadcrumbs' widget, all the others render the title of the header (or footer) template created within Headers Footer Template.

**Comment by stickypages** [comment]
Yoast, uses the_title() function, so if you integrated that, or added a shortcode, you would be able to use the title wherever you wanted. 

[sticky_yoast_title]
```

add_shortcode('sticky_yoast_title', function() {
	return the_title();
});
```

**Comment by bainternet** [comment]
You will be able to do that once Elementor Theme builder is out.
