### ISSUE TITLE
Elementor JS Hooks 

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#3566]
As far as I tested elementor js hook only fire if and only if any elementor widget is there. But what is the best way to fire js for both condition? 

Say I have lightbox for elementor gallery. Now I want same lightbox for default wordpress gallery shortcode,but it won't work for single post. So I am basically looking for js hook that work globally whether elementor is initiated or not. Or any js condition to check if elementor is loaded then do this else do that.

**Comment by bainternet** [comment]
@webangon 

Elementor JS hooks are only loaded if elementor is used on that page.

**Comment by webangon** [comment]
So no way to check if elementor is used or not like wordpress conditions?
