### ISSUE TITLE
Form - There's something wrong. The form is invalid.

### ISSUE THREAD

**Issue by sarahdenise** [pojome/elementor#3567]
Hello,

I keep getting 'There's something wrong. The form is invalid.' when I test out the form on my website.
Is there anything I have to set up at the back-end? There doesn't seem to be documentation for this if there is.

For now I have removed the Elementor form widget because I don't want a broken form on a live website. (Using Contact Form 7 for now - it is working)

I have been searching both here and on the Facebook group but no one else seems to have the same problem.

I only have the fields Name (Text), Email, Subject (Text), and Message (Textarea). I required all of them. I also want to try Honeypot.
Actions after submit is just email.
Under the Email tab, the 'From Email' email that I used is set up with Post SMTP. (I tried it as well before I set that email up in SMTP).
Metadata is date, time, page URL, User Agent, Remote IP, credit.
Send as: HTML
Additional Options: Custom messages YES

**Comment by bainternet** [comment]
@sarahdenise 

please contact our support and see if they can help you.
