### ISSUE TITLE
Filtered gallery request

### ISSUE THREAD

**Issue by lilianmurciaart** [pojome/elementor#3568]
Hello, I bought Elementor Pro almost a year ago, I am very happy, and I am going to renew the license soon. Working on one of my websites I am in need of a solution to my problem:  
I'm trying to make a gallery filtered by category of images. I have tried almost everything and I can not find the way. I do not need a portfolio, it is a single gallery with filters for the different categories of images that go in that gallery. Of course, I need to present the titles of these categories in a kind of menu, as they are shown in the elementor pro widget portfolio. Some images can have two or more categories, any suggestions? 
Please help, it is a service much requested by many of my clients. 
Thanks for everything, I hope you can help me.

**Comment by bainternet** [comment]
Please contact our support at support@elementor.com for guidance in resolving this issue.
