### ISSUE TITLE
Add options in colums or section.

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#3569]
As we heard we can't create a custom columns or sections.

Can we add some options in column or section?

We need to add 1 switch or 1 dropdown like this.
https://s18.postimg.org/jsibzlsy1/screenshot_553.png

Or **is it possible to create a widget which can add other widgets like column and section.**
As you may know, we can't add widgets in a widget. But columns, sections are possible.
If we can create a widget to add other widgets, it will be great!

We need to add "form" tag in column start and end "/form" ... and then add some fields widgets. we have already created others. But we haven't found how to add "form tag" before after a column.

Thank you for the great plugin.
We love it.

**Comment by bainternet** [comment]
@pulla 

You can add `form` tag to the select by updating the control options, ex:

```PHP
add_action( 'elementor/element/column/layout/before_section_end', function( $control_stack, $args ) {
	$control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), 'html_tag' );
	$control['options']['form'] = __( 'Form' );
	$control_stack->update_control( 'html_tag', $control );
}, 10, 2 );
```
