### ISSUE TITLE
"Uncommon" behavior of Content Width & Columns Gap behavior on sections

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#357]
Hi guys, this is not really an issue, but more about uncommon behavior.

Example:
- I set the Content Width to 1140px (my theme's wrapper width is 1140px).
- I have 4 columns with the same width percentage (25%).
- I set the Columns Gap to Default (10px padding on columns).

Result:
- We see 10px left padding of 1st column and 10px right padding of last column.
- The Content width will align differently from header's wrapper (which uses the same 1140px width).

![image](https://cloud.githubusercontent.com/assets/1287713/17301876/88073328-5843-11e6-91bb-47646f7de506.png)

Current workaround:
- The Content Width should be set to 1160px, which anticipated the 10px left & right padding (1140 + 10 +10).
- If I change the Columns Gap to other value, for example "no gap", I should also change the Content Width to 1140px (1140 + 0 + 0) because there is no left & right padding this time.
- If I change the Columns Gap to "wide" (20px padding), I should also change the Content Width to 1180px (1140+20+20).

On end users perspective, I think this is not effective at all.

Suggestion:
Could you programmatically add the assigned Columns Gap value to the Content Width generated CSS?
For example, user can keep the Content Width to 1140px and change the Columns Gap to whatever they want. If it's "wide" (20px padding). Your generated CSS for the Content Width is:

`max-width: 1180px;`

which is 1140 + 20 + 20.
Is it possible?

**Comment by arielk** [comment]
I merged this issue with another issue #452 in the same subject so that our Dev staff could deal with it more efficiently. So please let's continue the conversation there.
