### ISSUE TITLE
[Feature reguest] Formatting shortcuts for inline editing

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3572]
It would be really nice to have keyboard shortcuts for simple formatting like CTRL+B, CTRL+I, etc...
Again and again I'm repeatedly bookmarking the page when trying to get my text bold.

This and other imperfections of current version of inline editor (e.g.: no default WP link selector, unreliable selecting using ctrl+[something], occasional cursor disappearance, need to click twice to start editing, copying of unwanted inline styles, etc.) force me to use the native text editor in the left panel more often than I'd like to.

**Comment by bainternet** [comment]
@black-eye 

Its already implemented but I guess you are using Firefox which captures the Crtl + B ....

If you try in chrome you will see that it works.

**Comment by black-eye** [comment]
OK, thanks for clarifying, in Chrome it's OK. 
Any chance to do it correctly in FF as well? Native WP editor can do these shortcodes, so what's the problem with Elementor?

Can use Chrome for now, though.
