### ISSUE TITLE
CSS Hover Animation Doesn't Work in Templates Widget

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#3578]
This bug is shown when you use templates widget and the newly released widget "Call to Action".

See the video how to replicate:

https://youtu.be/E2Uj_sDfJZU

Doesn't matter what Wordpress theme you use.
The problem is that the template is a .elementor-widget and the CSS for , lets say "enter for right" is .elementor-widget .elementor-animated-item--enter-from-right

**Comment by bainternet** [comment]
does it happen when you insert the template not via a widget?

**Comment by dudaster** [comment]
It happens only when insert it through the template.

**Comment by bainternet** [comment]
@dudaster 
Thanks, should be fixed in 2.0
thanks.
