### ISSUE TITLE
Drop down menu stays floating on top

### ISSUE THREAD

**Issue by bitcolorine** [pojome/elementor#358]
Hi,
When adding an icon text box and choosing an icon, the icon drop down menu stays floating on top of all the other elements. I have to exit to the dashboard to get rid of it.
[](https://s32.postimg.org/5hxe0h56d/Screen_Shot_2016_08_01_at_1_35_02_PM.png)

**Comment by cobicarmel** [comment]
Hi @bitcolorine,
Does it happens also in the simple icon widget, when you choosing an icon?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
