### ISSUE TITLE
Feature Request - Option to align Pro Facebook button

### ISSUE THREAD

**Issue by mikesilve** [pojome/elementor#3581]
Hi. Would it be possible to add an alignment option for the pro Facebook button. At the moment it is only left aligned. It would be nice to be able to centre or right align.

**Comment by bainternet** [comment]
We only implement the possible settings from [Facebook ](https://developers.facebook.com/docs/plugins/like-button)

So you can either use custom CSS to align it or using columns.

thanks for the suggestion.
