### ISSUE TITLE
Adding a callback for a form submit event

### ISSUE THREAD

**Issue by eyalway2cu** [pojome/elementor#3582]
It would be a good idea to add some sort of callback for a form submit event for several purposes such as:

1. Event tracking without a thank you page.
2. Custom field validation.
3. Catching the submit event and sending an http request via AJAX.

These are just off the top of my head.

**Comment by bainternet** [comment]
All of these are available for you :)

1) Adding tracking code:
```JavaScript
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		// form has bees submitted do your tracking here...
	});
});
```

2) Custom field validation can run server-side per each field type using the `elementor_pro/forms/validation/{$field_type}` action hook, or in general (all fields)  using the 
`elementor_pro/forms/validation` action hook, ex:
```PHP
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {
	$email = $record->get_field( [
		'id' => 'email',
	] );
	
	if ( empty( $email ) ) {
		return;
        }
	
	if ( ! is_email( $email['value'] ) ) {
		$ajax_handler->add_error( $email['id'], 'Invalid Email address, it must be in the format XX@XX.XX' );
	}
}, 10, 2 );
```

3) see (1).
