### ISSUE TITLE
feature request: a way to prevent counters to execute

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3584]
Hi, I need a way to prevent counters to execute below a certain (custom) breakpoint.
Or, in other words, I need to take control over counters.

More in general, as a developer, doing custom works I'm more and more feeling the need of take control over automations, like waypoints (see previous thread). I think it's quite important.

Regards

**Comment by bainternet** [comment]
Currently, there is no way, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
