### ISSUE TITLE
Add rel attribute to Image Gallery element

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#359]
Could you add a rel attribute field to the Image Gallery element? The rel attribute value would then be applied to all the images in the image gallery so the images can be targeted by a lightbox plugin.

**Comment by yehudah** [comment]
Hi,

I know from other issues the gallery work with this plugins even without rel attribute:

- [https://wordpress.org/plugins/simple-lightbox/](url)

- [https://wordpress.org/plugins/wp-lightbox-2/](url)

**Comment by JoelEadeDesign** [comment]
Thanks for the plugin suggestions, @yehudah :) I [found a function](http://www.remicorson.com/tip-add-a-rel-attribute-to-wordpress-gallery-for-lightbox-use/) to sort it out for now.

**Comment by JoelEadeDesign** [comment]
I must've been having a "moment" earlier today, as I've re-tested my preferred gallery plugin (Responsive Lightbox) and it works without requiring the function. Apologies for wasting your time 😳

**Comment by yehudah** [comment]
We all have this moments :-)
