### ISSUE TITLE
Request: Extending Panel Options

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#3591]
Am I missing something? Is there any ability to extend the current controls/widgets?
I would like to extend the 'section' if possible by adding additional properties. REF: screenshot. 

Thanks for any direction or information. 
![2018-02-26 11_19_10-elementor _ empty](https://user-images.githubusercontent.com/658488/36690729-100c96ce-1ae8-11e8-9aa1-faf87dc5b2ba.png)

**Comment by bainternet** [comment]
@stickypages 

You are,
see [docs](https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md#elementorelementelement_namesection_idafter_section_end) or [this example](https://github.com/pojome/elementor/issues/3334#issuecomment-361611013)



And if you have a specific question we'd be happey to help.

**Comment by stickypages** [comment]
@bainternet Appreciate that, thank you. Not sure why that didn't come up in my search. 
Thanks again, will look deeper here.
