### ISSUE TITLE
Missing Docs for TYPOGRAPHY control

### ISSUE THREAD

**Issue by guytzhak** [pojome/elementor#3594]
There are no doc for the typograpthy control in your docs:

https://github.com/pojome/elementor/tree/master/docs

**Comment by bainternet** [comment]
@ramiy

**Comment by ramiy** [comment]
@guytzhak I documented all the missing controls in the new dev site!

See the full list of **[Elementor Controls](https://developers.elementor.com/elementor-controls/)** and the requested **[Typography Control](https://developers.elementor.com/elementor-controls/typography-control/)**.
