### ISSUE TITLE
No possibility to customize Css for form elementor-field-group

### ISSUE THREAD

**Issue by phdenis63** [pojome/elementor#3595]
Hello,

Is it possible to update your form-widget (next version) to **give the possibility to customize css for a specific "elementor-field-group"**?  For example (see screenshot), I want to add css for the first field-group. I can customize label and input with "field_pele_nom_groupe" reference but not the parent css (elementor-field-group). **There is not difference (class or id) from one group to another.**

![elementor-field-group](https://user-images.githubusercontent.com/36880621/36718533-72a08f06-1ba2-11e8-99d3-deff3c32604b.png)

Best Regards,

Philippe

**Comment by bainternet** [comment]
@phdenis63 

What is the use case?

**Comment by phdenis63** [comment]
I want to have a form like this (with label before fields) :
![elementor-form-expected](https://user-images.githubusercontent.com/36880621/36719508-863cc810-1ba5-11e8-9f1e-eb1f3b8e9f07.png)

**Comment by bainternet** [comment]
We have added a unique CSS class which uses the field ID and can be defined by setting the field "custom ID" in 1.15.3

**Comment by phdenis63** [comment]
Great THANKS.
