### ISSUE TITLE
Request: show/hide widgets functionality for button widget

### ISSUE THREAD

**Issue by joexcm** [pojome/elementor#3596]
Eg click "sign up to mailing list" button and mailing list form widget appears below (CSS display:none -> display: block).

Any DIY solutions welcome.

**Comment by bainternet** [comment]
@joexcm 

Give your button a CSS ID or Class and catch the click event to run your action, for example, say your button as an ID of `MY_BTN` and you have widget you want to show/hide with the ID of `MY_WIDGET` then you can catch the click event like this:

```Javascript
jQuery( document ).on( 'click',  '#MY_BTN', function( event ) {
   event.preventDefault();
   // Show/Hide the widget
   jQuery( '#MY_WIDGET' ).toggle();
});

**Comment by jcmatoskx** [comment]
Where should the jquery code be added?

**Comment by elias1435** [comment]
> Where should the jquery code be added?

you can add the jQuery code any html widget with <script></script>

<script type="text/javascript">
jQuery( document ).on( 'click',  '#MY_BTN', function( event ) {
   event.preventDefault();
   // Show/Hide the widget
   jQuery( '#MY_WIDGET' ).toggle();
});
</script>

**Comment by elias1435** [comment]
> @joexcm
> 
> Give your button a CSS ID or Class and catch the click event to run your action, for example, say your button as an ID of `MY_BTN` and you have widget you want to show/hide with the ID of `MY_WIDGET` then you can catch the click event like this:
> 
> ```js
> jQuery( document ).on( 'click',  '#MY_BTN', function( event ) {
>    event.preventDefault();
>    // Show/Hide the widget
>    jQuery( '#MY_WIDGET' ).toggle();
> });
> ```

Thanks a lot i am searching couple of hours but nothing working.. Your code worked.....
