### ISSUE TITLE
Feature request: Research Gate social media link

### ISSUE THREAD

**Issue by idontknowwhichtotake** [pojome/elementor#3597]
It would be nice if a Symbol and a Research Gate social media link could be implemented in elementor.

https://www.researchgate.net/

**Comment by bainternet** [comment]
@idontknowwhichtotake 

Currently, we use FontAwesome v4.7 for icons and is missing an icon for ResearchGate, there is an [open issue for it](
https://github.com/FortAwesome/Font-Awesome/issues/3634)  
thanks for the suggestion.
