### ISSUE TITLE
WooCommerce shortcode not work properly in editor after editor save and refresh

### ISSUE THREAD

**Issue by sandeshjangam** [pojome/elementor#3601]
## Description
WooCommerce Shortcode not working properly when the editor load. 
Here is a short video of bug.
https://goo.gl/gXSef8

It doesn't affect frontend but not working in the editor after editor update and then just refresh editor everything will mess.

## Steps to reproduce
1. Insert Shortcode widget.
2. Enter this "[products]" shortcode
3. Save / Update Editor
4. Now press F5 or refresh the editor. You will not see products properly 

## Environment

This issue will reproduce in any environment,

Theme: Twenty Seventeen
Elementor Version: 1.9.7
WooCommerce Version: 3.3.3

**Comment by rtthemes** [comment]
This one is a serious issue when working with WooCommerce products. Also missing the extra post classes added by WooCommerce like "product".

**Comment by notrealdev** [comment]
Same problem here. This is a serious issue

**Comment by shilo-ey** [comment]
This issue was solved in Elementor Pro v2.1.4.

thank you for your feedback.
