### ISSUE TITLE
Elemetor repeater field not working well with the WPML Translation Management

### ISSUE THREAD

**Issue by adiraomj** [pojome/elementor#3602]
## Description

I have added an accordion element to the page, but all the fields do not appear in the Translation Editor.

**Elementor screenshot:**
![screenshot-th local 2018-01-20 12-15-08-227](https://user-images.githubusercontent.com/3372029/36731147-d5879130-1bef-11e8-8e8b-e5bf0ca92841.png)

**Translation Editor**
![screenshot-th local 2018-01-20 12-09-04-498](https://user-images.githubusercontent.com/3372029/36731162-e064eeea-1bef-11e8-8b7c-3e9438b23a40.png)

I added an accordion with 3 tabs.. The Translation Editor only shows the 2nd tab title and 3rd content textarea. I get variations of this. Sometimes I get 2 title fields and 1 content field or vice-versa. But all the repeater fields never show up.

## Environment
WordPress 4.9.4

**Active Plugins**
Elementor 1.8.12
Formidable Forms 2.05.09
Kirki Toolkit 3.0.19
WPML Multilingual CMS 3.8.4
WPML String Translation 2.6.3
WPML Translation Management 2.4.3

**Comment by dgwatkins** [comment]
I tested this with latest WPML versions and it works correctly:
WPML Multilingual CMS 3.9.3
WPML String Translation 2.7.3
WPML Translation Management 2.5.2

Can you confirm this?

Notes:
- keep in mind that if 2 accordions have the same content, only one of them will show up in the translation editor.
- however, if you change one of them, the editor will show them both again.

**Comment by bainternet** [comment]
@adiraomj 

More of a WPML issue then an Elementor Issue.

**Comment by dgwatkins** [comment]
Let me point out that it's not an issue with current releases.

**Comment by ryanlabelle** [comment]
Thank you. All fixed up :)
