### ISSUE TITLE
[issue] Translate Pro Form Module Date Picker

### ISSUE THREAD

**Issue by Artneo7** [pojome/elementor#3605]
Hi! I need to translate the date picker inside the pro form module to the brazilian format (dd/mm/yyyy). And translate the months names. It's needed for my client's approval.

I contacted the support and they sent me this code:

```
flatpickr.l10ns.pt = {
    weekdays: {
        shorthand: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
        longhand: [
            "Domingo",
            "Segunda-feira",
            "Terça-feira",
            "Quarta-feira",
            "Quinta-feira",
            "Sexta-feira",
            "Sábado",
        ],
    },
    months: {
        shorthand: [
            "Jan",
            "Fev",
            "Mar",
            "Abr",
            "Mai",
            "Jun",
            "Jul",
            "Ago",
            "Set",
            "Out",
            "Nov",
            "Dez",
        ],
        longhand: [
            "Janeiro",
            "Fevereiro",
            "Março",
            "Abril",
            "Maio",
            "Junho",
            "Julho",
            "Agosto",
            "Setembro",
            "Outubro",
            "Novembro",
            "Dezembro",
        ],
    },
    rangeSeparator: " até ",
};
flatpickr.localize(flatpickr.l10ns.pt);
flatpickr('.flatpickr-input');
```
01. Where I need to add this custom code? 
02. How to make the date appear as **dd/mm/yyyy**?
03. There are a lot of countries that use this date format. Please, could you add it in your next update?

Love Elementor. Thanks a lot!

**Comment by bainternet** [comment]
You need to add this code to the page where you have the form, let say its page with the ID of 100, so in your theme's functions.php you can add something like this:

```PHP
<?php
add_action('wp_footer', function () {
        if ( ! is_page( 100 ) ) {
            return;
        }
        ?>
        <script>
        jQuery( document ).ready( function( $ ){
                    function waitForFlatpicker( callback ) {
                        if ( typeof window.flatpickr !== 'function' ) {
                            setTimeout( function() { waitForFlatpicker( callback ) }, 100 );
                        }
                        callback();
                    }
                    waitForFlatpicker( function(){
                        flatpickr.l10ns.pt = {
                            weekdays: {
                                shorthand: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
                                longhand: [
                                    "Domingo",
                                    "Segunda-feira",
                                    "Terça-feira",
                                    "Quarta-feira",
                                    "Quinta-feira",
                                    "Sexta-feira",
                                    "Sábado",
                                ],
                            },
                            months: {
                                shorthand: [
                                    "Jan",
                                    "Fev",
                                    "Mar",
                                    "Abr",
                                    "Mai",
                                    "Jun",
                                    "Jul",
                                    "Ago",
                                    "Set",
                                    "Out",
                                    "Nov",
                                    "Dez",
                                ],
                                longhand: [
                                    "Janeiro",
                                    "Fevereiro",
                                    "Março",
                                    "Abril",
                                    "Maio",
                                    "Junho",
                                    "Julho",
                                    "Agosto",
                                    "Setembro",
                                    "Outubro",
                                    "Novembro",
                                    "Dezembro",
                                ],
                            },
                            rangeSeparator: " até ",
                        };
                        //set translations
                        flatpickr.localize(flatpickr.l10ns.pt);
                        flatpickr('.flatpickr-input');
                        //set format
                        $('.flatpickr-input').each(function(){ flatpickr( $(this)[0] ).set('dateFormat', 'dd/mm/yyyy');});
                    });
        });
        </script>
        <?php
} );
```
The Date format default is not something we are going to change anytime soon

**Comment by Artneo7** [comment]
The calendar view inside the date picker is translated. But, the date format (yyyy/mm/dd) should be (dd/mm/yyyy).

Images: https://imgur.com/a/jqMXM

Please, help me out with this. It's very important for your brazilian clients. I usually blog about Elementor so I can share this important solution across brazilian Elementor social groups. It's a must to be fully translated to sell a professional contact form solution for brazilian companies.

Thanks again!

**Comment by Artneo7** [comment]
It's still not working. I cleaned cache and hard reloaded, but the format is not being applied.

Images: https://imgur.com/a/gmY4U

**Comment by bainternet** [comment]
it appears that the format is set to early so give it a delay: instead of:
```javascript
$('.flatpickr-input').each(function(){ flatpickr( $(this)[0] ).set('dateFormat', 'd/m/Y');});
```
try
```javascript
setTimeout( function(){
    $('.flatpickr-input').each(function(){ flatpickr( $(this)[0] ).set('dateFormat', 'd/m/Y');});
}, 1000 );
```

**Comment by Artneo7** [comment]
It's working perfectly! :)

Image: https://imgur.com/a/ZGYwZ

Thanks you @bainternet for the great support.

I'll share this solution with others.

**Comment by Artneo7** [comment]
In case someone need a full tutorial on how to change the format from (yyyy/mm/dd) to (dd/mm/yyyy) click this link: https://artneo.com.br/traduzir-data-formulario-elementor/

**Comment by PlatonSven** [comment]
Hi,
this custom code works fine for me in all browsers except with EDGE. When the setTimeout function to set the dateformat is triggered, edge reloads the page. After 2 or 3 reloads it reports an error. 

`    jQuery( document ).ready( function( $ ){
        function waitForFlatpicker( callback ) {
            if ( typeof window.flatpickr !== 'function') {
                setTimeout( function() { waitForFlatpicker( callback ) }, 100 );
            }
            console.log("tick wait");
            callback();
        }
        waitForFlatpicker( function(){
            flatpickr.l10ns.de = {
                weekdays: {
                    shorthand: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
                    longhand: [
                        "Sonntag",
                        "Montag",
                        "Dienstag",
                        "Mittwoch",
                        "Donnerstag",
                        "Freitag",
                        "Samstag",
                    ],
                },
                months: {
                    shorthand: [
                        "Jan",
                        "Feb",
                        "März",
                        "Apr",
                        "Mai",
                        "Juni",
                        "Juli",
                        "Aug",
                        "Sept",
                        "Okt",
                        "Nov",
                        "Dez",
                    ],
                    longhand: [
                        "Januar",
                        "Februar",
                        "März",
                        "April",
                        "Mai",
                        "Juni",
                        "Juli",
                        "August",
                        "September",
                        "Oktober",
                        "November",
                        "Dezember",
                    ],
                },
                rangeSeparator: " bis "
            };
            //set translations 
            flatpickr.localize(flatpickr.l10ns.de);
            flatpickr('.flatpickr-input');
            //set format - doesn't work in edge
            
            setTimeout( function(){
                $('.flatpickr-input').each(function(){ 
                    $(this).flatpickr({
                        dateFormat: 'd.m.Y',
                        minDate: '01.04.2019',
                        locale: {
                            firstDayOfWeek: 1
                        }  
                    });                         
                });
                console.log("tick date");
            }, 1000 );                       
        });
    });`

Thanks you. Btw Elementor is awesome ;)
Sven

**Comment by Artneo7** [comment]
The code above doesn't translate the strings **date, time, Site Url, IP**… is there a way to translate them? Thanks!

**Comment by pa0aer** [comment]
I need also a translation in Dutch. But I have much moren than one page can I change the row
add_action('wp_footer', function () {
        if ( ! is_page( 100 ) ) {
            return;
        }
        ?>
in
add_action('wp_footer', function () {
        if ( ! is_page( 100,220,8789,654 ) ) {
            return;
        }
        ?>

**Comment by govusfi** [comment]
Hello, I've used the code on this thread to translate date picker for a Finnish website. The client now needs the site translated to english for which I'm going to use polylang, but can I edit this code to be effective in the finnish version only with page ID or something? Also can I use the same code for the english page since the date format needs to be dd/mm/yyyy.  Thanks!

**Comment by pacotole** [comment]
Hi!
I've write a little plugin [elementor-datepicker-localization](https://github.com/creame/elementor-datepicker-localization) to load datepicker in the current site language.

Suggestions are welcome :)

**Comment by dasigna** [comment]
great work from @pacotole - but sad such is needed!!

btw: the form throws an error as soon as extending the date with the day of the week ... or even when selecting the month to be written fully. (with pacotoles plugin)

really disappointed such little things doesnt nearly work as expected ...
cant be true one have to tweak around for that.

**Comment by mrleonz** [comment]
@pacotole Worked for me THANKS!!!!
only 1 bug.

I can't click on the time. to enter the time(confirm the time). I have to press the arrows and click diffrent place. if i don't press the arrows or try to manually i get an error. 

https://imgur.com/a/K5Q26E9

Maybe press a OK or SELECT TIME button after the chosen time?

thanks in advance

**Comment by danideu** [comment]
When changing the calendar to date in Spanish, everything is correct, but the problem is when I want to change the first day of the week which in Spain is Monday. When making this change, the days (number) do not correspond to the correct calendar.

**Comment by puregraphx** [comment]
@pacotole thank you for the plugin, works perfectly for me right out of the box.

**Comment by carlos-villalba** [comment]
> When changing the calendar to date in Spanish, everything is correct, but the problem is when I want to change the first day of the week which in Spain is Monday. When making this change, the days (number) do not correspond to the correct calendar.

I Just got it! Spanish version with the first of the week as Monday:

`add_action('wp_footer', function () {
        if ( ! is_page( 888 ) ) {
            return;
        }
        ?>
        <script>
        jQuery( document ).ready( function( $ ){
                    function waitForFlatpicker( callback ) {
                        if ( typeof window.flatpickr !== 'function' ) {
                            setTimeout( function() { waitForFlatpicker( callback ) }, 888 );
                        }
                        callback();
                    }
                    waitForFlatpicker( function(){
						flatpickr.l10ns.default.firstDayOfWeek = 1;
                        flatpickr.l10ns.es = {
                            weekdays: {
                                shorthand: [ "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"  ],
                                longhand: [
									"Domingo",
									"Lunes",
                                    "Martes",
                                    "Miércoles",
                                    "Jueves",
                                    "Viernes",
                                    "Sábado",
                                ],
                            },
                            months: {
                                shorthand: [
                                    "Ene",
                                    "Feb",
                                    "Mar",
                                    "Abr",
                                    "May",
                                    "Jun",
                                    "Jul",
                                    "Ago",
                                    "Sep",
                                    "Oct",
                                    "Nov",
                                    "Dic",
                                ],
                                longhand: [
                                    "Enero",
                                    "Febrero",
                                    "Marzo",
                                    "Abril",
                                    "Mayo",
                                    "Junio",
                                    "Julio",
                                    "Agosto",
                                    "Septiembre",
                                    "Octubre",
                                    "Noviembre",
                                    "Deciembre",
                                ],
                            },
                            rangeSeparator: " hasta ",
                        };
                        //set translations
                        flatpickr.localize(flatpickr.l10ns.es);
                        flatpickr('.flatpickr-input');
                        //set format
                        $('.flatpickr-input').each(function(){ flatpickr( $(this)[0] ).set('dateFormat', 'd/m/Y');});
                    });
        });
        </script>
        <?php
} );`

**Comment by momo-fr** [comment]
Hi, what the code for french translation, that not work for me?

**Comment by RiKaZaRai** [comment]
Hello momo
For french with Monday on first day
`<script>
        jQuery( document ).ready( function( $ ){
                    function waitForFlatpicker( callback ) {
                        if ( typeof window.flatpickr !== 'function' ) {
                            setTimeout( function() { waitForFlatpicker( callback ) }, 100 );
                        }
                        callback();
                    }
                    waitForFlatpicker( function(){
                    flatpickr.l10ns.default.firstDayOfWeek = 1;
                        flatpickr.l10ns.fr = {
                            weekdays: {
                                shorthand: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
                                longhand: [
                                    "Dimanche",
                                    "Lundi",
                                    "Mardi",
                                    "Mercredi",
                                    "Jeudi",
                                    "Vendredi",
                                    "Samedi",
                                ],
                            },
                            months: {
                                shorthand: [
                                    "Jan",
                                    "Fév",
                                    "Mar",
                                    "Avr",
                                    "Mai",
                                    "Juin",
                                    "Jui",
                                    "Aou",
                                    "Sep",
                                    "Oct",
                                    "Nov",
                                    "Déc",
                                ],
                                longhand: [
                                    "Janvier",
                                    "Février",
                                    "Mars",
                                    "Avril",
                                    "Mai",
                                    "Juin",
                                    "Juillet",
                                    "Août",
                                    "Septembre",
                                    "Octobre",
                                    "Novembre",
                                    "Décembre",
                                ],
                            },
                            rangeSeparator: " até ",
                        };
                        //set translations
                        flatpickr.localize(flatpickr.l10ns.fr);
                        flatpickr('.flatpickr-input');
                        //set format
                        setTimeout( function(){
                        $('.flatpickr-input').each(function(){ flatpickr( $(this)[0] ).set('dateFormat', 'd/m/Y');});
                        }, 1000 );
                    });
        });
        </script>`

**Comment by momo-fr** [comment]
Hi @RiKaZaRai, that work fine, thank you!!
