### ISSUE TITLE
Attributes in content o advanced tab of elements

### ISSUE THREAD

**Issue by rafaramos** [pojome/elementor#3606]
Perfect for Schema.

![atributos](https://user-images.githubusercontent.com/5157155/36756774-4606f106-1c10-11e8-9656-d78401fb5fba.png)

**Comment by bainternet** [comment]
This feels more like a 3rd party plugin territory,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by rafaramos** [comment]
I don´t agree. If I can choose a HTML tag, if I can choose a ID, if I can choose a Class,...Why Can´t I add the attribute?
Not only por Schema, I could add Analytics events,...
