### ISSUE TITLE
Need to remove background image option from Group_Control_Background

### ISSUE THREAD

**Issue by Balachandark** [pojome/elementor#3607]
## Description

I want to remove background image option from Group_Control_Background
I had already created a ticket regarding this issue but someone closed the ticket #3580.

It was suggested to me in that ticket to use standard color control but I want to use both color option as well as gradient color option. I don't want to create an extra field for background color. So, I wanted to use Group_Control_Background and hide the background image option. Can you please tell me how can I achieve it?

## Issue

I am using the Group_Control_Background class and would like to use only the background color option in the classic type and not the background image. Is it possible?

Here is the code that i have used:

```PHP
$this->add_group_control(
	Group_Control_Background::get_type(),
    [
		'name'     => 'uael_feeds_on_hover',
		'title'    => __( 'On Hover Background', 'uael' ),
		'types'    => [ 'classic', 'gradient' ],
		'selector' => '{{WRAPPER}} .image-featured-container:hover .image-backdrop',
		'{{WRAPPER}} .instagram-carousel a:hover .image-featured-container .image-backdrop',
	]
);

**Comment by bainternet** [comment]
@Balachandark 

You can't, the background image is a part of the classic type along with color. and they cant be separated in that group control unless you extend it to a custom control which does just that.

**Comment by farman-topnotch** [comment]
Try this
```
$this->add_group_control(
			\Elementor\Group_Control_Background::get_type(),
			[
				'name' => 'package_title_background',
				'label' => __( 'Background', 'xpro-elementor-addons-pro' ),
				'types' => [ 'classic', 'gradient'],
				'exclude' => [ 'image' ],
				'selector' => '{{WRAPPER}} .tnit-matrix-head',
			]
		);
```
