### ISSUE TITLE
Feature Request - Breadcrumbs navigation of sections/rows/columns/widgets

### ISSUE THREAD

**Issue by jayalove** [pojome/elementor#3613]
It would be amazing to see this awesome feature from Thrive Architect implemented in Elementor. They make it so easy to click and be able to edit settings of various parts of the page heirarchy. Gone would be the issue of trying to select that section on the top that has a negative margin and you have to add a blank section and hide it just to be able to hover over the top of the section to select it.

Check out Thrive's breadcrumbs. They rock.
<img width="683" alt="screen shot 2018-02-28 at 3 47 48 am" src="https://user-images.githubusercontent.com/35327964/36786154-32ecc97c-1c3a-11e8-842c-f89d25c89904.png">
<img width="1230" alt="screen shot 2018-02-28 at 3 45 54 am" src="https://user-images.githubusercontent.com/35327964/36786155-331a27f0-1c3a-11e8-89e7-dc059bf85a2e.png">

**Comment by drank** [comment]
That is a great request indeed!

I also struggled so many times not being able to select a section just because of my "twisted" layout.

So +1 from me on this one.

**Comment by bainternet** [comment]
I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
