### ISSUE TITLE
Old YouTube logo in FA icon

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3615]
In your version of Font Awesome, there's old version of YT icon. On FontAwesome web, there seems to be the correct one:

![obrazek](https://user-images.githubusercontent.com/5634870/36803286-6941ea70-1cb7-11e8-8966-5b71b09428cd.png)

Any plans on updating FA version soon?

**Comment by bainternet** [comment]
@black-eye 

We are going to update and move to FA5 we actually have an icon there https://fontawesome.com/icons/elementor?style=brands as for ETA no idea.

**Comment by samuelcerezo** [comment]
Still using old youtube logo

**Comment by portrayaloflife** [comment]
Could we at least update youtube for now? Seems like it would be a pretty easy fix
