### ISSUE TITLE
Testimonial Carousel widget not showing testimonials+Accordion widget not closed on first item

### ISSUE THREAD

**Issue by hahahalf** [pojome/elementor#3616]
Hi. 

I have using Elementor Pro, and it has been wonderful- as many would attest, I am sure- for someone who hasn't the slightest in ability to code a website from scratch, for the most part.

1) The Accordion widget still opens on the first item when a page is first loaded- the Toggle widget does not behave as the Accordion widget does, so it makes for a poor substitute- which is why I guess there is the Toggle widget and there's the Accordion widget; apparently somewhere on Github, it's been mentioned that this issue has been fixed since version 1.8.

2) The Testimonial Carousel widget doesn't show testimonials when viewing the website in both "Preview Changes" and "Visit Site", as per the image attached below:
![image](https://user-images.githubusercontent.com/36933030/36807917-7e27dba2-1d07-11e8-9f22-cc61b8a881af.png)

It does appear to work without issue in edit mode though. As per image below:
![image](https://user-images.githubusercontent.com/36933030/36808014-b82a70d0-1d07-11e8-91cd-3505b6984284.png)

All help would be immensely appreciated. And I am sorry if I have posted my query erroneously on Github.

**Comment by bainternet** [comment]
Please contact our support at support@elementor.com for guidance in resolving this issue.
