### ISSUE TITLE
Suggestion/Bug: add_render_attribute needs a small tweak

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#3617]
I am playing around with developing a Schema Addition to elementor, and noticed in the 
`$element->add_render_attribute();`

You **cannot** add an empty attribute, (without value). It will always try to add the value, creating an empty `itemscope=""`
 
I want: `<div class="classnames" itemscope></div>`

`$element->add_render_attribute( '_wrapper', [	'itemscope' => null, 	'class' => 'classnames'] );`

Can we add this functionality?

**Comment by bainternet** [comment]
@stickypages 

For boolean attributes you can set the value to `true` which is valid and works out of the box.
```PHP
$element->add_render_attribute( '_wrapper', [ 'itemscope' => true, 'class' => 'classnames'] );
```

Or if you have another custom attribute which you are sure this will be its only value you can append `itemscope` (or any other boolean attribute) to its name ex:
```PHP
$element->add_render_attribute( '_wrapper', [ 'itemscope itemtype' => 'http //schema.org/product', 'class' => 'classnames'] );
```



thanks.
