### ISSUE TITLE
Code snippets request: developer recommended way to add JS/CSS to custom widget/control

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3618]
This is a code snippets request. Because a developer API doc will be writen, I want to ask now to plugins author what's their recommended way to include custom CSS and custom JS to a custom widget AND to a custom control.

The tricky part is that I want the snippets to cover the fact that, for a clean code, I want to separate CSS/JS between frontend and editor mode: so, imagine, I have 2 PHP classes for both a new widget and a new control along with 8 files (widget_type.editor.css, widget_type.frontend.css, widget_type.editor.JS, widget_type.frontend.JS, control_type.editor.css, control_type.frontend.css, control_type.editor.JS, control_type.frontend.JS).

I think this is really the missing thing to really unleash the potential of Elementor and to create clean control/widget.

**Comment by bainternet** [comment]
@tristanleboss 

You'll be happy to know that the docs are in the making as we speak. As for your question, everything looks about right just why would you need a `control_type.fontend.js`?

controls are not loaded in the frontend.

**Comment by tristanleboss** [comment]
I am waiting for them. You are right, I don't see a use case for this. I maybe copy/pasted this too quickly. Both the scripts and the styles are useless for the control on the front-end.
