### ISSUE TITLE
BUG: Urgent Issue with Roller Image Changing Size in SVG in Safari

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#3619]
Hello,

We have an urgent issue with a rollover image that's an SVG changing size in when its not supposed to when we roll over it and release in Safari only. Works correctly in chrome. It should not shrink at all.

The thing is, we are able to correctly get it to work in Adobe Muse on Safari AND Chrome without Elementor. 

But when we try to replicate the same rollover in Elementor instead of Adobe Muse, the image shrinks very tiny in Safari.  But works in Chrome.

Please PM us and we will send you the links to our site test built in Elementor and the one built with Adobe Muse as we are currently unreleased.

**Comment by bainternet** [comment]
PM us? it doesn't work here like that,

Please contact our support at support@elementor.com for guidance in resolving this issue.
