### ISSUE TITLE
Formspree support

### ISSUE THREAD

**Issue by shimsa** [pojome/elementor#3620]
Hello, I bought Elementor Pro and I am satisfied. But the problem is one thing. Elementor Forms do not support Formspree, which I really need, and unfortunately I am unable to set it up. Please add support for this service.

https://formspree.io

Thank you.

Tom

**Comment by bainternet** [comment]
@shimsa 

Not sure if we can implement such a thing, but you can do that yourself easily if you have Formspree Gold account and have setup a form there:

```JAVASCRIPT
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function( event, response_data ){
		// form has been submitted so send it to formspree
                var formData = new FormData( $(this) );
                $.ajax({
                    url: "https://formspree.io/FORM_ID", 
                    method: "POST",
                    data: formData,
                    dataType: "json"
                });
	});
});
```

**Comment by Erudition** [comment]
If we could just set the elementor form's URL and POST settings, it would be natively supported...  
[#4785](https://github.com/elementor/elementor/issues/4785)
