### ISSUE TITLE
[Bug] Some interface buttons are not shelded from custom external css

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3621]
Please take a look:

![schermata 2018-03-01 alle 00 06 55](https://user-images.githubusercontent.com/437598/36818244-7d6cc7b8-1ce4-11e8-854a-585a872e56fc.png)

Their styles are affected from custom theme styles. They should not.

**Comment by bainternet** [comment]
If a theme style targets an Elementor element, there is really nothing we can do about it.

**Comment by stratboy** [comment]
@bainternet 

C'mon, you're a super active developer, super active moderator on stackexchange... You're experienced enough. When you give such answers, it means you really do not want to answer.

You can use different classes for Elementor's own UI. Just namespace them.
You are currently calling them .elementor-button, exactly like the in-page ones. Just use .elementor-ui-button instead, that's all.
