### ISSUE TITLE
"Screen Options" missing in Pages / Posts... when Elementor Pro is active

### ISSUE THREAD

**Issue by badcat** [pojome/elementor#3622]
With only Elementor and Elementor Pro active, the "Screen Options" section is no longer visible in many areas of WordPress admin - namely in Pages or Posts. 

Disabling Elementor Pro and the Screen Options are again visible.

WordPress 4.9.4
Elementor Version 1.9.7
Elementor Pro Version Version 1.15.2
GeneratePress Version 2.0.2

**Comment by bainternet** [comment]
Thanks for reporting.

**Comment by JohanDavidsson** [comment]
As a temporary fix I have commented out add_filter( 'screen_options_show_screen', '__return_false' ); in fonts_manager.php in my install if anybody else needs to fix this fast as I before a fix is released.

**Comment by drank** [comment]
@JohanDavidsson, thanks for the quick find!

There is a small typo - it's fonts-manager.php :) (located in plugins/elementor-pro/modules/assets-manager/asset-types)

**Comment by bainternet** [comment]
issue fixed and will we released in next version, thanks.

@drank whats the typo?

**Comment by drank** [comment]
@bainternet, no no, it was just in the filename by @JohanDavidsson. Everything's fine :)

**Comment by arielk** [comment]
v1.15.3 has been released, please update!
