### ISSUE TITLE
[Editor feature request]: Disable Localization or choose your own independently from WP's default

### ISSUE THREAD

**Issue by zeinnicholas** [pojome/elementor#3623]
## Description

**The problem:** Currently Elementor's editor interface inherits the site default language, which is fine if you're building sites for people with the same language as yours. But if you have a different language than your client's (for example), you end up editing with a foreign language.

It would be great if:
**1 -** The editor interface could inherit the Wordpress user-specific language (for the interface only). _or_;
**2 -** We could toggle on/off the editor interface localization (ending up with only the default language); _or;_
**3 -** Each user could select their own language.

Either way this would help with foreign language limitations.

## Steps to reproduce

This could be done with a simple `get_user_locale()` for the option #1, or simply adding a conditional tag based on a setting that would disable localization in the editor interface for the option #2. For the option #3 it would require more code so it's not the most practical way. 

What do you think?

**Comment by bainternet** [comment]
Currently, this feature is not supported, and it's not as simple as you state because it's a frontal editor and it needs to know the language and the properties of that language( ex LTR/RTL). But anyway we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by zeinnicholas** [comment]
And it doesn't read it right now? How it translates to the site language? 

Being able to at least simply disable the translation would be great (option #2), instead of getting the safe localization as standard# switch the localization function for a custom function that conditionally checks for the language based on a checkbox in settings.

Having to change a site language just to be able to edit is not good if the site is live.

But thanks anyway...

**Comment by sproctorcc** [comment]
Please fix this issue. Elementor is great but trying to write a multi-language website is almost impossible!

**Comment by arielk** [comment]
Ref: #3623
