### ISSUE TITLE
Feature Request Woo-Add to Cart: Spinner, redirect and custom message

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#3624]
Hi. Please add the widget functions
1. add loading spinner when click add to cart.
2. on/off redirect to cart page or custom page when add to cart
3. add custom message for change success message add to cart

**Comment by bainternet** [comment]
@ravilrrr 

Does Woo shortcode support these features?

**Comment by ravilrrr** [comment]
No.

**Comment by bainternet** [comment]
Well then I guess we'll have to wait for them to add it, as currently, the Woo widgets are shortcode wrappers with styling options.
