### ISSUE TITLE
Feature request: generic container widget

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3626]
As for the title, a widget that creates a generic container which you can use to put other widgets inside, to move them all together, to duplicate them all together, delete and save.

Currently you can do sort of it with the columns widget by deleting 1 column so you get 1 column/box. But it can't be used inside other columns, so it's quite limited. Also, it's kind of a quirk.

Use case:

![schermata 2018-03-01 alle 11 15 45](https://user-images.githubusercontent.com/437598/36839280-f247ccba-1d41-11e8-80c2-5d48402840e8.png)

As you can see, I'm using progress bars. But in fact, I'm building composed elements, each one with 2 twicked progress bars. It would have been great if I could put them inside a container. Apart from moving, duplicating and deleting and saving, this would also make for better margin management between them. 

N.B. I'd like to do it by myself, but it's not clear what code I can use to create self-standing widget containers that inherit drag/drop and duplication tools.

**Comment by bainternet** [comment]
Currently, You can't create a container widget,but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by tristanleboss** [comment]
Why are request/feature ticket closed? Indeed, it would be better to keep them alive so people can comment or add their voice. Or even better: use a sytem like https://www.uservoice.com/?

It would indeed be awesome to be able to create containers widget...

**Comment by stratboy** [comment]
> Indeed, it would be better to keep them alive so people can comment or add their voice.

@tristanleboss: this is a strange github behaviour, you can close but still comment, so it's anyway fine they close tickets, because you can always somewhat reopen them just by commenting. :)
Thank you for the pumping up my request anyway! :)

**Comment by tristanleboss** [comment]
@stratboy Unfortunately, (or correct me if I am wrong), we have no way to reopen them :( Commenting on them doesn't reopen them.

I don't understand why some feature request are kept open and others are not (like this one).

Anyway, GitHub issues are not the best way to track feature requests...
