### ISSUE TITLE
How can't love elementor! love to see v2!

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#3627]
I am not sure where I can leave this comment. if it's out of topic in git, please forgive me. I will remove it.

But I want to say "Thank you and congrate for V2".

My question is that is it possible to join test RC version or be a tester? if so, please let us know.

Thank you for your great plugin.

**Comment by bainternet** [comment]
@pulla 

thanks for the kind words,

 you can signup for beta testing at https://my.elementor.com/beta/
