### ISSUE TITLE
Bug: Glitchy Issue with SVG Images as Rollover Buttons

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#3629]
There is a glitchy Issue with SVG Images as Rollover buttons created with Elementor. SVG Rollover Images change size and are jumpy when they aren't supposed to in Apple Safari when you mouse over the image. 

In Google Chrome, they don't change size which is better, but they still slightly jumpy when you mouse over.

**Comment by bainternet** [comment]
@smile00000 
Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by smile00000** [comment]
I have contacted them and they were not able to solve the issue and urged me to post the glitch on GitHub.

**Comment by smile00000** [comment]
@bainternet 

Video of the issue:
https://www.useloom.com/share/fd3c067cee724bb4945f8cd35539723a

support@elementor.com has no solution and said they are going to share with you the issue directly for future development (the github developers), but I want to make sure that happens so below is the video so you can see what is happening:

As you can see in the video, it is fine in Chrome but if you go to Safari, they are jumpy and it makes this second tiny rollover image when you roll over the buttons:

Please let me know your thoughts! It's the main feature of our site so would love to have a fix for this as many people are starting to use SVG instead of jpgs these days since they are scalable without pixelation! Thanks!

**Comment by smile00000** [comment]
We are just following up on this issue. Please advise.
