### ISSUE TITLE
Frontend CSS enqueued late

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#363]
In common cases, theme author will the styles from override Elementor's frontend CSS, right?

Theme's CSS is commonly enqueued using **direct** `wp_enqueue_scripts` hook from `functions.php`. I noticed you enqueue the frontend CSS when initialize the `Elementor\Frontend` class, which is called on `template_redirect` hook. I think this is too late.

Can you declare direct action on `wp_enqueue_scripts` hook for the frontend CSS? So the frontend would be enqueued before theme's CSS.

**Comment by KingYes** [comment]
Hi @daviedR 
We using `wp_enqueue_scripts` to register the frontend CSS/JS files.

Why you think we declare them in `template_redirect` action?

Reference: https://github.com/pojome/elementor/blob/master/includes/frontend.php#L21

**Comment by daviedR** [comment]
Hi KingYes,

Yes, you used `wp_enqueue_script` hook to register your CSS/JS files. But you add the action on `init` function. And your init function is called on `template_redirect` hook. It's in your `__construct` function in the class.

Ref: https://github.com/pojome/elementor/blob/master/includes/frontend.php#L361

**Comment by KingYes** [comment]
I know that.
If you want to register your `wp_enqueue_scripts` before/after our hook, you can use with [priority](https://developer.wordpress.org/reference/functions/add_action/) param.

Did I understand you correctly?

**Comment by daviedR** [comment]
Yes, the priority parameter works well. I have set the priority of my theme's `wp_enqueue_scripts` action to `20`.

But it would be great if this works by default on all themes. I meant commonly theme authors doesn't add the `20` priority into their enqueue function.

For the hierarchy, I think plugin's CSS should always be enqueued before theme's CSS unless it's a generated CSS.

**Comment by KingYes** [comment]
It's okay. The priority parameter need to used when you need the hierarchy for the files. That's is what I think about this. :|

**Comment by daviedR** [comment]
Okay then, I guest it's the best solution for now..
