### ISSUE TITLE
bug while editing using saved templates

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3631]
I get this

`<b>Notice</b>:  Trying to get property of non-object in <b>[path]/wp-content/plugins/elementor/elementor.php</b> on line <b>65</b>`

**Comment by bainternet** [comment]
@stratboy 

Do you have polylang installed on that site?

again, please provide steps to replicate.

**Comment by stratboy** [comment]
Yes, polylang is installed

**Comment by bainternet** [comment]
What versions are installed? 
E, E pro and polylang. and how can we replicate?

**Comment by stratboy** [comment]
I don't know how you can replicate. Probably just save a template (say a section), then recall it somewhere and start edit it.

Polylang is latest Pro.

**Comment by bainternet** [comment]
Fixed in 2.0.0
