### ISSUE TITLE
Feature Request: Set cookie and toggle visibility of contact form

### ISSUE THREAD

**Issue by mattkaz** [pojome/elementor#3634]
Hello,

I set up a contact form in Elementor Pro, and connected it to MailOption, so that I could add a custom field. It worked, no problem.

However, now I have no way of setting a cookie on successful form/optin submission, so that the option form does not get shown to users who have opted in/subscribed in the past. I would like to hide the form for those users.

So I'd like to suggest adding the feature of being able to set a cookie for the user upon successful form submission, so that you can control how long the form is hidden for users who have successfully subscribed or opted in. There's no need to keep showing it to them.

Thank you very much.

**Comment by bainternet** [comment]
There is an event that happens on both the server (action hook) and on the client (Javascript event) which you can use to set your cookie,

JS:
```Javascript
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		// form has been submitted Set your cookie here...
	});
});
```
