### ISSUE TITLE
Subtitles under image in portfolio widget

### ISSUE THREAD

**Issue by Tama-iris** [pojome/elementor#3637]
Hi!
I´ve tried to use the portfolio widget, with elementor pro wp plugin, but can´t set titles under image. So I used the post widget, but now I can´t use filters. I would be wonderfull if the portfolio widget could have titles under image, because sometimes it´s better for specific needs in design.
Hoping you can do that! 
thank you very much indeed.

**Comment by 77lbg** [comment]
FEATURE REQUEST (similar to comment #3637):
When displaying posts using the Elementor Pro post and/or portfolio widget(s), the ability to include BOTH:  
a) titles UNDER featured image (currently available in post widget),
b) user-clickable filters AT TOP of images (currently available in portfolio widget) .

Cheers to the Elementor developers for all the other great features currently available!

**Comment by bainternet** [comment]
I merged this issue with  #3140, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Tama-iris** [comment]
thank you!!!

2018-03-04 9:51 GMT-03:00 raz ohad <notifications@github.com>:

**Comment by tchan13188** [comment]
I was about to submit the same request, but a quick search showed it has already been submitted. Now I can see that the game of hide and seek for the post titles will hopefully end soon:-) Thank you!!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released as the Taxonomy Filter widget for the Loop Builder with Elementor Pro v3.15.0! 🥳 

You can now place a standalone taxonomy filter widget anywhere on your layout and target one of the Loop Grid widgets on the page. You can also use multiple taxonomy filters.

You can learn more about this new feature here: https://elementor.com/help/taxonomy-filter-widget/

The Loop Builder was released in version 3.8.0. You can learn more about the Loop Grid widget here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
