### ISSUE TITLE
Feature Request: Hamburger Menu Pushes Entire Page open to the left/right/up/down.

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#3639]
Feature Request: Hamburger Menu that Pushes Entire Page open to the left/right/up/down.

As well as allowing images, a search bar, etc. within the menu.

Example:
https://demo.responsive.menu/pro-example-two

Or in the meantime can you please integrate this responsive menu plugin like you did with WooCommerce into Elementor? It's amazing!
https://responsive.menu/

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by smile00000** [comment]
Thank you!

**Comment by Reubenlee** [comment]
Would love to have more flexibility over my hamburger menu +1 for this feature request

**Comment by Reubenlee** [comment]
+1 i feel that this feature would greatly enhance the visual effect for a website
