### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3640]
A "disable default stlyes" for widgets. So the styles are up to the developer. 

This could be present just in every widget. But it would be especially important for complex ones like the slideshows, where in fact we are forced to implement a slew of !important rules to just override dots and arrows...

**Comment by bainternet** [comment]
This is a very tricky one, and not something I see implemented anytime soon as you can overwrite the default anyway so ....

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


Thanks for the feedback.
