### ISSUE TITLE
Feature Request: Create Content Wrappers in Elementor

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#3641]
We need a way to Create Content Wrappers in elementor if we want to create information outside of the content wrapper .elementor-649.

Trying to use this third party responsive menu plugin with elementor because it can do a fancy push the entire page (that elementor currently doesn't offer) when it opens the hamburger...

But since the shortcode is placed inside the .elementor-649 wrapper, it pushes the plugin along with the entire page. 

So it would be great if we could create content wrappers in elementor so I can use a push wrapper to effectively achieve this:

https://demo.responsive.menu/pro-example-two

https://responsive.menu

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by smile00000** [comment]
Thanks!
