### ISSUE TITLE
Feature Request: noscript element

### ISSUE THREAD

**Issue by jokr0815** [pojome/elementor#3643]
Hi, 

please add an noscript element alternative where you use script. A simple html box would be great.

I created this post here as well: https://wordpress.org/support/topic/enh-noscript-alternative-for-js-elements/

Thanks and Kind regards
Jo

**Comment by bainternet** [comment]
@jokr0815 

Elementor uses JavaScript extensively and it's not going to be realistic to place a no script everywhere it uses it nor can we control 3rd party plugin developers to implement it for their own widgets.

Its safe to assume that if a page is build with elementor it needs Javascript so you can add a "Global" site-wide or on elementor specific pages noscript tag yourself.
