### ISSUE TITLE
[BUG?] Portfolio widget does not display Draft and Private content

### ISSUE THREAD

**Issue by drank** [pojome/elementor#3644]
The Portfolio widget is empty when the content it is configured to display is in either Draft or Private state and when I am logged in as Admin. My portfolio widget is currently configured with Manual Selection and displays only pages (no posts).

I am not sure if this is a bug but when I am logged in, WordPress displays all the pages just fine when they are either in Draft or in Private state (only when I logout then I am not able to see them), i.e. I can access these pages via my menus and links just as usual.

When I set the page status to Published (public), the Portfolio shows it.

My workflow requires working with pages without publishing them, so is it possible to make the Portfolio plugin show Draft and Private pages when logged in?

Note: I also checked that the Posts widget behaves the same with posts but I am not sure whether this should be changed as well - I think WordPress does not show Draft posts same as Draft pages, even to logged in users.

**Comment by bainternet** [comment]
@drank 

That is the desired functionality, The posts and portfolio widgets both display only `Public` available statuses which means that `draft`, `pending` or `private` will not be available.

**Comment by drank** [comment]
@bainternet 

But isn't this behavior defeating the whole purpose of having Draft pages - which is, to allow working with the pages without showing them to the public?

Imagine I have an Elementor page which is in Draft and within I have I have a Portfolio widget which is configured to display pages that are also Draft. I can normally see the Elementor page and work with it but I am not able to see the contents of the Portfolio widget unless I publish the other pages.

Doesn't this seem not normal to you?

Or alternatively, can you suggest an alternative approach, if you say that this is by design, so that I can still work and see my pages while in Draft without the need to publish them just to be able to review my results?

Best regards,
Drago
