### ISSUE TITLE
Documentation for developer is too poor

### ISSUE THREAD

**Issue by niamulrox** [pojome/elementor#3645]
I was trying to build my own elementor widgets and I did not found any proper documentation. Any idea for developer documentation or how to create own elementor widgets in theme ?

**Comment by bainternet** [comment]
@niamulrox 

We are actively working on developing and improving the developers' docs, for now, take a look at the [Hello World plugin](https://github.com/pojome/elementor-hello-world) that should get you started and if in time you have a specific question that comes up, please feel free to open a new issue and ask.
