### ISSUE TITLE
[Feature Request] Fixed width for video lightbox

### ISSUE THREAD

**Issue by rja66** [pojome/elementor#3646]
I would like to be able to fix maximum width for video when played in lightbox

Video looks best embedded @2x native resolution, which is 960px wide for 1080p 16:9 video.
(Vimeo embed videos on the Vimeo site at 960px wide for this reason)

Currently in Elementor it is possible set video size as a %, 
but i'd like a set width option in px as well.

Thanks for consideration

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
 for now, you can do that with custom CSS.
Thanks for the feedback.
