### ISSUE TITLE
Can't update E Pro on localhost

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#3648]
When I work on localhost, using laragon, I can't update E Pro. Getting this error message: 
![grafik](https://user-images.githubusercontent.com/14095280/36939762-24a8d388-1f37-11e8-9572-4c1c1293f008.png)
Any idea, what could cause the error?

**Comment by bainternet** [comment]
@HelmutGoebel 

Cloud be caused by many reasons, but the main issue you should look for is: 

* Disk space - make sure you have not run out.

* Permissions - try setting read and write permissions to "anyone" on the folder, `sudo chmod 777 -R /var/www/html/your-project-folder-name`

**Comment by HelmutGoebel** [comment]
67,8 GB free  space on the hard drive. But I have at least 15 other plugins in that installation, including Elementor Free version. They all update without any problem.

**Comment by SniffleValve** [comment]
Helmut - 
Install the Windows Compatibility Fix plugin and try again. I just successfully updated E Pro from 1.13.2 to 1.15.2 on my Laragon local :) 

https://wordpress.org/plugins/fix-windows-compatibility/

Cheers!
Lyle

**Comment by HelmutGoebel** [comment]
Lyle, you're my hero! Works! Thanks a lot!

**Comment by bainternet** [comment]
@SniffleValve thanks.
@HelmutGoebel glad you figured it out.
