### ISSUE TITLE
Preview window DOM events are not fired!

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#3649]
Hi there,

On editor, the preview iframe's window DOM events are not fired at all. This makes all frontend scripts that handle events like `$(window).on('resize', function() { ... })` and `$(window).on('scroll', function() { ... })` DOESN'T WORK on Elementor editor's preview. It seems to work fine on Frontend, but not in the editor's preview.

Please help. This is disaster to developers.

**Comment by daviedR** [comment]
@KingYes @kobizz @arielk

**Comment by bainternet** [comment]
@daviedR 
how are you enqueuing your scripts and what are you trying to do?

**Comment by daviedR** [comment]
I want to add custom element / widget handler via this hook: `elementorFrontend.hooks.addAction( 'frontend/element_ready/global', myCustomHandler );`

```
$window.on( 'elementor/frontend/init', function() {
	$( window ).on( 'scroll', function() {
		console.log( 'scroll' );
	});

	elementorFrontend.hooks.addAction( 'frontend/element_ready/section', parallaxBackgroundHandler );
	elementorFrontend.hooks.addAction( 'frontend/element_ready/global', parallaxElementHandler );
	elementorFrontend.hooks.addAction( 'frontend/element_ready/global', stickyElementHandler );
});
```

The `scroll1` check would never be logged when on Elementor editor. On frontend, it works well.

**Comment by daviedR** [comment]
Turns out I have to wrap the event handler declaration within `jQuery.ready()`.

So this code would work:

```
$window.on( 'elementor/frontend/init', function() {
	$( window ).on( 'scroll', function() {
		console.log( 'scroll1' );
	});

	$( function() {
		$( window ).on( 'scroll', function() {
			console.log( 'scroll2' );
		});
		
		elementorFrontend.hooks.addAction( 'frontend/element_ready/global', myCustomHandler );
	});
});
```

Both `scroll1` and `scroll2` check if logged on both editor and frontend.

**Comment by daviedR** [comment]
Hmm but the JS hook is too late to be added on jQuery `ready`.

**Comment by daviedR** [comment]
I guess this works:

```
var myCustomHandler = function() {
	$( function() {
		$( window ).on( 'scroll', function() {
			console.log( 'scroll2' );
		});
	});
};

$window.on( 'elementor/frontend/init', function() {
	elementorFrontend.hooks.addAction( 'frontend/element_ready/global', myCustomHandler );
});
```

**Comment by bainternet** [comment]
Glad you figured it out.

**Comment by daviedR** [comment]
This should be added to the documentation.

Also about the `elementor/frontend/init` hook which has not been covered in the documentation. I have to dig into the JS code to figure it out.
