### ISSUE TITLE
Edit panel setting save place - Make site build faster for all 

### ISSUE THREAD

**Issue by amoyastudio** [pojome/elementor#3658]
my suggestion will make the website build faster for everyone.

when you want to change the padding or color or what ever setting for multi elements it's very annoying when you  select an element you need to go the the left panel setting and select the color panel or padding panel again again for each element you select.

it would be great if you could make the edit panel save the last setting it was in the previous one so for example if you need to change the padding for multi elements the padding setting is open each time you select new element.

thank you

**Comment by black-eye** [comment]
+1
Oh yeah, this would be a great timesaver!
I've planned to suggest this feature as well, I'm toggling between elements all the time, mostly to assure which settings were made, or when making corrections for a group of elements e.g. section columns.

Each extra click counts in situations like these. Unfortunatelly this "clickfest" has gotten even more intense by introducing the typo popup - I can't help myself, I can't get used to it. The only thing it brought is one more click and hidden typo settings.

**Comment by bainternet** [comment]
@amoyastudio @black-eye 

thanks for the suggestion,

We are Working on a "copy style" feature which will improve the workflow and give an answer to the "Issue" described here.

I merged this issue with  #1479, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
