### ISSUE TITLE
Global heading fonts are not applied in editor

### ISSUE THREAD

**Issue by dtbaker** [pojome/elementor#366]
But if I go in and choose a "Custom" font style for a heading it will correctly load the "Gloria Hallelula" font and everything starts to work.

![image](https://cloud.githubusercontent.com/assets/543073/17354443/eef12712-598b-11e6-96bf-684ad128b275.png)

**Comment by arielk** [comment]
Which theme are you using?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
