### ISSUE TITLE
BUG - not scroll panel

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#3660]
Hi friends. I'm tired of reloading the page. The panel is periodically blocked from scrolling. I think all this is connected with the drop-down lists. Exactly how to catch error, I don't know ((
My browser Firefox last version

![2018-03-05_09-12-34](https://user-images.githubusercontent.com/5197026/36958509-d813f136-2055-11e8-9bf4-ad12d437fd39.png)

**Comment by bainternet** [comment]
@ravilrrr 

We can't replicate, try to click on a different widget and re-enter the widget you want to edit, see if that helps.

**Comment by ravilrrr** [comment]
Bingo ))) I replicate ))

1. Open setting widget.
2. Click for open dropdown list (animation effect)
3. Do not select and not click
4. Select another widget
5. Repeate step 1-4
6. Result.

link video http://recordit.co/OpX6RXEnyu

**Comment by bainternet** [comment]
still can't replicate :(

Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by ravilrrr** [comment]
Hi. See screen  
https://screenshotscdn.firefoxusercontent.com/images/70f0e009-caca-4c4a-8056-9a71f041cc2f.png

I already wrote you, but I didn't get an answer. Cannot updated to pro b2.

-- 
________________________
С Уважением, Равиль
