### ISSUE TITLE
Yoast SEO Premium plugin conflict with Elementor.

### ISSUE THREAD

**Issue by dbybanez** [pojome/elementor#3663]
## Description

Yoast SEO Premium plugin conflict with Elementor.

## Steps to reproduce

1. Deactivated all plugins including theme.
2. Activated plugin one by one.
3. Found out that Yoast SEO Premium is conflict with Elementor.

## Environment

WordPress: WordPress 4.9.4

## Other notes

Contacted Yoast support and they're investigating this matter. Hope you guys will too. 

Thank you.

**Comment by bainternet** [comment]
@dbybanez 

Whats the conflict??

**Comment by dbybanez** [comment]
Sorry. The issue is, when both plugins are activated, the admin page won't load most of the time. It just gives me white blank screen. 

When I enabled the debug mode, it shows this error:
Fatal error: Out of memory (allocated 1389625344) (tried to allocate 8388608 bytes) in path\to\wordpress\taxonomy.php on line 3212

**Comment by bainternet** [comment]
well, this gives us the answer, you ran out of memory...

try increasing your memory either by following [this](https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP)  or contact your host and ask them for it.
