### ISSUE TITLE
All background-images are broken in backend with custom wp-content/uploads folder

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#3666]
So, i have installed and used S3-uploads since the beginning of 2017, and it never broke anything, Elementor comprised. You can find the plugin here: https://github.com/humanmade/S3-Uploads ; the only behaviour it has is to enable Wordpress to move the entire uploads folder to Amazon S3, and then if you want you can use Cloudfront distribution system too, in the end it only replace all the calculated media endpoint with s3 or cloudfront ones.
Since last 2 or 3 versions updates of Elementor (i'm in 1.9.7 now, but i have site with 1.9.3 also) it seems ONLY THE IMAGES in css are broken (not those placed with `<img>` tag).
Let's see an example:

- The frontend shows
![image](https://user-images.githubusercontent.com/19909323/37023710-0f0d8bb2-2127-11e8-877b-5971c64e7012.png)
where the css code is
![image](https://user-images.githubusercontent.com/19909323/37023839-70a1b236-2127-11e8-8706-e6d416bb04d0.png)

- the backend shows
![image](https://user-images.githubusercontent.com/19909323/37023746-26f624e6-2127-11e8-8d16-bf29da933a90.png)
with the error here, pointing to the wrong old url ().
![image](https://user-images.githubusercontent.com/19909323/37023892-a55b789a-2127-11e8-9f16-0b1c97f95c07.png)

- also the background image selector on editor points to the wrong url
![image](https://user-images.githubusercontent.com/19909323/37023989-f01ec7ce-2127-11e8-9bc2-50d93be6fedf.png)

- all the inline <img> tags works normally both in backend and frontend, altought there are still problems in backend
![image](https://user-images.githubusercontent.com/19909323/37024181-6e0a9a5a-2128-11e8-9168-650f70f79b89.png)
![image](https://user-images.githubusercontent.com/19909323/37024254-992bb71e-2128-11e8-947d-14b991a1a156.png)

I think you are wrongly calculating the css, or better, you arent' using the usual Wordpress functions to calculate them. I'm not sure, but before debugging and create a pull request i'll ask you that developed it, maybe you're quicker in fix than me.

**Comment by bainternet** [comment]
@teolaz 
Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by teolaz** [comment]
@bainternet why? don't you think this is a bug?

**Comment by bainternet** [comment]
@teolaz 

This was closed since, we cannot replicate this issue and I directed you to our support so they could try to access your site and investigate better then what we can do here on github.
