### ISSUE TITLE
Selector option for large viewports

### ISSUE THREAD

**Issue by tr00y** [pojome/elementor#3667]
Right now, you can select _desktop / tablet / mobile_ via the little icons to set specific settings for different elements.

With the increasing popularity of large screens (4K and above), it would be really helpful to have a selector for large screens as well because right now users have to add custom CSS with "@media screen and (min-width: 1900px) {..."

**Comment by bainternet** [comment]
I merged this issue with  #78, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
