### ISSUE TITLE
JavaScript Web3.js API Conflict

### ISSUE THREAD

**Issue by JulianKlodzinski** [pojome/elementor#3668]
Hi Elementor Team,

i have an issue with Elementor and the JavaScript API to Web3.js. It works fine if i deactivate your plugin but with Elementor activated it does not work. I want to use the EthereumICO plugin. But if i activate this plugin i get an error: Uncaught Error: Cannot find module 'jquery'at o (web3.min.js?ver=0.20.2:1)at o (web3.min.js?ver=0.20.2:1)at dialog.min.js:3

Furthermore the Navbar disappears.

After a quick talk with the developer of this plugin he mentioned that the Elementor plugin cause a conflict with the API of Web3.js. Is there any settings i have to set to allow Javascript in the elementor plugin? Regards JulianYou can answer me via email oder telegram (@cashwolfDE) Julian Klodzinski

**Comment by bainternet** [comment]
@JulianKlodzinski 

what is the plugin and what is causing the conflict? steps to replicate?

**Comment by JulianKlodzinski** [comment]
EthereumICO (https://wordpress.org/plugins/ethereumico/)

Steps to replicate:

1 Set up Wordpress
2 Create a site with elementor
3 download and activate EthereumICO

thats it what i have done. Do you need all settings of my page?

**Comment by JulianKlodzinski** [comment]
Problem is solved. The disappearing header is an issue with Elementor or the OceanWP Theme and Bootstrap which uses the CSS class .dropdown-menu and changed the style of the Navbar.

The issue with the error message is fixed from the developer of the plugin.

Thank you very much for your support :)
