### ISSUE TITLE
Screen options are disabled (Pro)

### ISSUE THREAD

**Issue by nicomollet** [pojome/elementor#3669]
Hello Elementor,

The fonts manager Pro module disables the "screen options" tab.

The fonts manager has a filter `add_filter( 'screen_options_show_screen', '__return_false' );` that disabled all screen options for all post types (including posts, pages, woocommerce orders) in `clean_admin_listing_page` function.

The condition to avoid `! self::CPT === $typenow || 'edit.php' !== $pagenow` doesn't avoid restricting this filter to fonts manager.

Kind regards

**Comment by bainternet** [comment]
Duplicate of #3622

**Comment by nicomollet** [comment]
Oops sorry for the duplicate.
