### ISSUE TITLE
New Placement of Sections

### ISSUE THREAD

**Issue by yaffeweb** [pojome/elementor#367]
I'm having a difficult time dragging and dropping existing sections. If I create sections and then decide that I want a new section somewhere higher on my page, I cannot create it between 2 already existing sections, only add it to existing columns which is not what I want. Am I missing something? Right now, to get a section where I want it in the existing hierarchy, I basically have to delete all other existing sections between the bottom and where I would like my new section to be add my new section and then create everything else down the page again.

**Comment by lunacroft** [comment]
@yaffeweb you can create a new section and drag it to reposition.

**Comment by yehudah** [comment]
I hope I understand you correctly

![anim](https://cloud.githubusercontent.com/assets/1655373/17399392/802d55ca-5a4a-11e6-91e8-a9d8ecff77f4.gif)

**Comment by yaffeweb** [comment]
Thanks guys! I didn't realize that grabbing the column tab and grabbing the section tab resulted in different behavior.
