### ISSUE TITLE
Element_Base::get_style_depends() doesn't work

### ISSUE THREAD

**Issue by vrundakansara** [pojome/elementor#3670]
Hi,

The function `Element_Base::get_style_depends()` doesn't quite work for custom widgets. Like for js we register the scripts on the action specified below.
```php
add_action( 'elementor/frontend/after_register_scripts', array( $this, 'register_widget_scripts' ) );
```

I registered the styles on the below action

```php
add_action( 'elementor/frontend/after_register_styles', array( $this, 'register_widget_styles' ) );
```

And looks like the styles don't get added in the editor. Am I missing something?

Regards,
Vrunda Kansara

**Comment by bainternet** [comment]
@vrundakansara 
Yes, you are missing something,

First, to add scripts to your widget, you don't need to add an action hook, instead use the `get_script_depends` method of your widget class to specify which scripts you need and elementor will enqueue them for you:

```PHP
public function get_script_depends() {
	return [ 'jquery','other_script_handle' ];
}
```

Second, the same goes for styles:
```PHP
public function get_style_depends() {
	return [ 'MainStyleSeet','other_style_handle' ];
}
```

You only need to make sure you register your scripts and styles using `wp_register_script` and `wp_register_style`.

Side note: currently when you use `get_style_depends` it will only enqueue the styles in the footer and not in the head tag.

Hope this helps.

**Comment by vrundakansara** [comment]
Hi,

I exactly did the same thing that you specified.

It turns out that this works in frontend but not in the editor.

Can you please confirm?

Regards,
Vrunda Kansara

**Comment by bainternet** [comment]
@vrundakansara 

Not sure, 
can I see you code?

**Comment by vrundakansara** [comment]
Hi,

I added the below code -

```php
add_action( 'elementor/frontend/after_register_styles', function() {
	wp_register_style( 'hello-world-style', plugins_url( '/assets/css/hello-world.css', ELEMENTOR_HELLO_WORLD__FILE__ ) );
} );
```

And the widget class has this function -

```php
public function get_style_depends() {
	return [ 'hello-world-style' ];
}
```

The hello-world.css file goes this way -

```css
.title {
	background-color: #d6cfcf;
	font-family: "Alegreya Sans SC", Sans-serif;
	font-size: 20px;
	font-style: italic;
	padding: 10px;
	text-align: center;
}
```

The style is applied only to the frontend - http://bsf.io/h075o

But not at the Elementor editor end - http://bsf.io/rj3wd

Also, here is the zip file of the plugin. You can install at your local end and check - http://bsf.io/yvni1

I hope I was clear enough.

Regards,
Vrunda Kansara

**Comment by bainternet** [comment]
@vrundakansara 

you are correct the style needs to be enqueued "manually" for it to show in the editor but only registered once, so use `elementor/frontend/after_register_styles` to register and `elementor/preview/enqueue_styles` to enqueue. Your plugin.php `add_actions` should look like this:

```PHP
private function add_actions() {
	add_action( 'elementor/widgets/widgets_registered', [ $this, 'on_widgets_registered' ] );

	add_action( 'elementor/frontend/after_register_scripts', function() {
		wp_register_script( 'hello-world', plugins_url( '/assets/js/hello-world.js', ELEMENTOR_HELLO_WORLD__FILE__ ), [ 'jquery' ], false, true );
	} );

	add_action( 'elementor/frontend/after_register_styles', function() {
		wp_register_style( 'hello-world-style', plugins_url( '/assets/css/hello-world.css', ELEMENTOR_HELLO_WORLD__FILE__ ) );
	} );
        //this was the missing part.
	add_action( 'elementor/preview/enqueue_styles', function() {
		wp_enqueue_style( 'hello-world-style' );
	} );
}
```

Hope this helps.

**Comment by bdthemes** [comment]
But it's working fine on 1.9.7, it's little bit confusing because style need to re-enqueue for editor only! Is it not possible with load with get_style_depends() for both front-end and editor?

**Comment by bainternet** [comment]
Currently it's not possible.

**Comment by dinhtungdu** [comment]
@bainternet How about `get_style_depends` right now, can we enqueue the script in head with the current version of elementor?

**Comment by dbjpanda** [comment]
Yet we are having same problems.
