### ISSUE TITLE
Bug: Can not edit page/post using Elementor if there are other elements on frontend which are created using Elementor

### ISSUE THREAD

**Issue by sumitpore** [pojome/elementor#3671]
## Description

I am working on one theme. The theme allows creating Mega Menus using Elementor. After creating Mega Menu, when I went to edit any other page/post, I found that Elementor is not allowing to edit that page/post. It allows editing of Mega Menu instead of allowing to edit desired page/post. I am attaching a video to make myself clear.

https://drive.google.com/file/d/1PUAhL-Ys8qGwt3ejlCmH2cOCOsEglM_i/view?usp=sharing

In the attached video, submenu content of 'Some Page' menu is created using Elementor. I am trying to edit the page 'Test Page' using Elementor. This 'Test Page' does not have any relation with the submenu content. But it shows 'Add New Section' area in the submenu part instead of showing it in the main page. It happens with all pages and posts. Every time it displays 'Add New Section' area in that submenu only.

## Fix
I have made following changes in Preview::builder_wrapper() function which is present in includes/preview.php
```
public function builder_wrapper($content) {

	if( get_the_ID() === get_queried_object_id() ) {
		return '<div id="elementor" class="elementor elementor-edit-mode"></div>';
	}
		
	return $content;
}
```
Now it shows the `Add New Section` area for page/post I am trying to edit. Do you think this will have some unwanted consequences? If not, will you add this to the upcoming version of Elementor? So that theme users will not face this problem.

**Comment by bainternet** [comment]
@sumitpore 

Thanks for reporting, we do have plans to change the way its injected into that page, and will try to implement this in the next releases.

For now, your change could side effects if you have more plugin like that mega menu one which prints its content on a page using `the_content`.
