### ISSUE TITLE
Strip slashes before saving _elementor_data

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#3675]
So, i have installed and used S3-uploads since the beginning of 2017, and it never broke anything, Elementor comprised. You can find the plugin here: https://github.com/humanmade/S3-Uploads ; the only behaviour it has is to enable Wordpress to move the entire uploads folder to Amazon S3, and then if you want you can use Cloudfront distribution system too, in the end it only replace all the calculated media endpoint with s3 or cloudfront ones.
Since last 2 or 3 versions updates of Elementor (i'm in 1.9.7 now, but i have site with 1.9.3 also) it seems ONLY THE IMAGES in css are broken (not those placed with `<img>` tag).
Let's see an example:

- The frontend shows
![image](https://user-images.githubusercontent.com/19909323/37023710-0f0d8bb2-2127-11e8-877b-5971c64e7012.png)
where the css code is
![image](https://user-images.githubusercontent.com/19909323/37023839-70a1b236-2127-11e8-8706-e6d416bb04d0.png)

- the backend shows
![image](https://user-images.githubusercontent.com/19909323/37023746-26f624e6-2127-11e8-8d16-bf29da933a90.png)
with the error here, pointing to the wrong old url ().
![image](https://user-images.githubusercontent.com/19909323/37023892-a55b789a-2127-11e8-9f16-0b1c97f95c07.png)

- also the background image selector on editor points to the wrong url
![image](https://user-images.githubusercontent.com/19909323/37023989-f01ec7ce-2127-11e8-9bc2-50d93be6fedf.png)

- all the inline <img> tags works normally both in backend and frontend, altought there are still problems in backend
![image](https://user-images.githubusercontent.com/19909323/37024181-6e0a9a5a-2128-11e8-9168-650f70f79b89.png)
![image](https://user-images.githubusercontent.com/19909323/37024254-992bb71e-2128-11e8-947d-14b991a1a156.png)

Assuming it's my error, i needed to clean the db going up with all the links corrected...

After debugging a while, it seems you're saving the background images refers in db, without stripping the slashes (why?)... So you cannot use wp-cli to search-replace image url in example. 

![image](https://user-images.githubusercontent.com/19909323/37046106-cf09c1ca-2167-11e8-882e-04efbce3d4d7.png)

Can't you use a serialized data instead of a json for `_elementor_meta` postmeta? You're quite going out of the main "serialized-data" concept of Wordpress with this...

**Comment by bainternet** [comment]
@teolaz 

We prefer JSON instead of serialized data for many reasons but mainly for these:

> 
> JSON is simpler and faster than PHP's serialization format and should be used unless:
> 
>  * You're storing deeply nested arrays: json_decode(): "This function will return false if the JSON encoded data is deeper than 127 elements."
>  * You're storing objects that need to be unserialized as the correct class
>  * You're interacting with old PHP versions that don't support json_decode

Source: https://stackoverflow.com/a/804053

Now a few corrections:
 * When we save the data we escape the slashes we don't strip.
 * You cannot search and replace serialized data unless you use a "custom" tool for it (safe search and replace).
* You have a tool that comes with elementor that allows you to search and replace in the stored JSON data.
* Last even Gutenberg now uses JSON to store data structures.

try the replace url tool in elementor >> tools

**Comment by teolaz** [comment]
@bainternet 

> You cannot search and replace serialized data unless you use a "custom" tool for it (safe search and replace).

Of course, you can use the ordinary wp-cli to do so, it's not so "custom" nowadays: https://developer.wordpress.org/cli/commands/search-replace/


> You have a tool that comes with elementor that allows you to search and replace in the stored JSON data.

I the search and replace tool inside Elementor isn't so clear as UI tell different things that "Search and replace whatever you want" ... no? If you say "this is used to move a site from a url to another" how can i understand i can use the tool for different purpose?

![image](https://user-images.githubusercontent.com/19909323/37086446-df3227be-21f7-11e8-892c-2b4e4acaab28.png)

**Comment by bainternet** [comment]
@teolaz 
"custom" means not directly on with an SQL UPDATE command so WP-CLI falls into custom.

as for the "Replace tool"it's for valid URLS only.
