### ISSUE TITLE
[Feature Request] - Ultimate A/B split testing for elementor

### ISSUE THREAD

**Issue by amoyastudio** [pojome/elementor#3678]
I have a an offer for the ultimate split testing ever you can make in elementor pro.
here is the details.

**_Main idea details:_**
The idea is to make an option to make split test for each element, this is done by creating a new icon next to the icons on each element ( in the duplicate area....  the icon can be A/B )

it will give an option to duplicate the element for split test different settings and content, the original element will be always visible but when you'll press on the new A/B button you can choose to see the split test elements you created ( it can be more then one ) and also don't forget an option to hide the hole element also as split test.

**The split test is using groups to show your split elements for example:**

group A  - all split elements that will be assign to group A
group B  - all split elements that will be assign to group B
group C  - all split elements that will be assign to group C
and so on....

**Then in the final result when someone see the website with the split test it' should be something like this in the browser:**

orginal_page_A.html will show all elements that using group A and original elements
orginal_page_B.html will show all elements that using group B and original elements
orginal_page_C.html will show all elements that using group C and original elements
and so on.....

**_Split test settings in the elementor panel_**
the idea is to make redirect to different pages according to the groups and also to give control on the percentage that you want to expose each group, for example

i want to show
Orginal page - 50%
Group A - 25%
Group B - 25%

you can do with with the elementor setting for split test.

in this way we can test what ever we want and see the results as different pages.
Hope this helps

**Comment by bainternet** [comment]
@amoyastudio 

Nice idea,
I merged this issue with  #2436, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
