### ISSUE TITLE
[Important Improvement] Support for GA Enhanced Link Attribution (and for regular link click tracking)

### ISSUE THREAD

**Issue by drank** [pojome/elementor#3679]
[TL,DR:] Please add proper support for Google Analytics Enhanced Link Attribution to links created by Elementor. In short, ELA allows us to differentiate in GA between separate links that lead to the same page. For example, I you have 2 links A and B, both pointing to /products, then in GA you could have different percentages for A and B depending on number of click on A and on B separately.

The long story:
Here are the main requirements (apart from the separate configuration to enable it in GA and GTM) in order for the ELA to work - https://support.google.com/analytics/answer/7377126?hl=en&ref_topic=2558810.

Quoting:
> For Enhanced Link Attribution to work effectively, all links for which you want enhanced click attribution should have an ID attribute. If the click-target element does not have an ID, the plugin will climb the DOM up to 3 levels to find an element with an ID.

That means that all the links (the `<a>` elements) should have an ID attribute, or at least their parent (2nd level) or grand-parent (3rd level) should have an ID attribute.

Currently that does not seem to be the case with Elementor links. I did not thoroughly check all the links Elementor creates, I only checked buttons and Image Box links. None of these had an ID attribute anywhere near the `<a>` tag.

**Important**: Even if I add an id from the Advanced tab, it is too far from the `<a>` tag - 4th level for the buttons and 5th level for the Image Box.

Please consider adding the possibility to specify IDs for `<a>` tags (or close to them) so that we can benefit from GA's ELA. I consider this an important improvement, hence the title. I hope you will also agree that this is important for GA tracking.

Thanks!

PS: I just realized that we would also need to be able to specify IDs on `<a>` level for the regular link click tracking via GTM events.

**Comment by bainternet** [comment]
@drank 

for analytics Enhanced Link Attribution, you can set the number of levels that the plugin will climb up the dom :
```javascript
ga('require', 'linkid', {
  'cookieName': '_ela',
  'duration': 45,
  'levels': 5 // <== 5 should do it in most cases
});
```

[ref](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-link-attribution#customizing_enhanced_link_attribution)

as for GTM still checking.

**Comment by bainternet** [comment]
@drank 

same goes for GTM
```JAVASCRIPT
gtag('config', 'GA_TRACKING_ID', {
  'link_attribution': {
    'cookie_name': '_gaela',
    'cookie_expires': 60,
    'levels': 5
  }
});
```
ref: https://developers.google.com/analytics/devguides/collection/gtagjs/enhanced-link-attribution

So I think that this with widget custom ID should do for most cases, correct me if I'm wrong...

**Comment by drank** [comment]
@bainternet 

I see what you mean and thanks a lot for the find! Unfortunately both of the above examples are only for GA (the 2nd one as well) and do not apply to GTM. I've searched but could not find how to make GTM change the depth level.

But the ELA is only only one of the possible use cases. There are cases when we would benefit from having an ID at `<a>` level in which there will be no tracing up the DOM tree to find one. For example, I might have 2 buttons alongside and would like to distinguish clicks between the one and the other.

Additionally, there are may widgets that can have more than one links in them (e.g. Posts, Portfolio, Carousels, Icon Lists, etc.) and having one ID at the widget level might not be enough. In this case EAL will not work either without having the IDs on the `<a>` level.

I understand the complexity of the feature but IMHO it is important to be able to identify links for tracking purposes.

What do you think?
Would also be beneficial to hear other users' opinions.

**Comment by drank** [comment]
Re the ELA and GTM DOM level - https://productforums.google.com/forum/#!topic/tag-manager/VlLo7mpxudw.

Very unfortunate!

**Comment by arielk** [comment]
It's already released.
Ref: #4535

**Comment by drank** [comment]
@arielk ,

No, it is NOT released!

Have you ever read the original request? It was about having the possibility to specify IDs for ALL links created by Elementor and you closed the request only because you implemented it for Buttons?

When will you stop this practice of implementing 10% of a request and then close the whole request as implemented? And then you put a glorious release notes post saying that you have implemented the much requested feature. This is similar to lying. You are Devs not politicians, come to your senses!

I've given you all the needed information so that you could implement it properly and you failed.

Please sent this post to Ben Pines - he was asking about an example of how Elementor is failing to listen to their paying customers.

**Comment by arielk** [comment]
@drank 

I'm sorry I did not understand you well. I went over the request again and unfortunately, I do not see at the moment a way we can add it to the **ALL** links, if you have more specific places that it's necessary, we will happy to add it.

Again sorry for the mix-up.

**Comment by drank** [comment]
@arielk 

Ok, if it was closed by mistake then could you please reopen it?

I am sure that everywhere where you have this control:
![image_1](https://user-images.githubusercontent.com/1393766/42837218-1acc5878-8a06-11e8-8736-97c7e755e895.png)
you can add a simple input field for the ID attribute, shouldn't be that hard.

For the purposes of GA tracking all links are important, so there are not specific places that would require this special treatment more than some others.
