### ISSUE TITLE
Upper content trembles when scrolling up (reproducible)

### ISSUE THREAD

**Issue by HeyHeyDaniel** [pojome/elementor#3680]
When you scroll to the top, the upper boxes, headlines etc. trembles for a moment. 

This problem occurs on desktop too, not only on mobile. It doesn't occur on every page, but on the most. It seems to appear, when Elementor is used together with a theme (e.g. OceanWP) which brings a header (menu).

I discussed this topic in a Facebook-Group and there were many users, which have the same problem and there doesn't seem to be a solution to it. It seems bug in Elementor since I use it (> 6 Months).

The issue is reproducible.

Please see this GIF, where I recorded the problem: https://sellmazing.com/wp-content/uploads/2018/02/20180214_164348.gif

**Comment by bainternet** [comment]
Please contact our support at support@elementor.com for guidance in resolving this issue.
