### ISSUE TITLE
Class 'Elementor\Widget_Base' not found

### ISSUE THREAD

**Issue by niamulrox** [pojome/elementor#3681]
Hi ,

When trying to create new widget its always showing this error message. I have copied one of your widget from elementor > includes > widgets. But its not finding the Class 'Elementor\Widget_Base'.

Any guideline ?

**Comment by bainternet** [comment]
@niamulrox 

you need to make sure Elementor has included that class before you use it, please take a look at the Elementor demo [Hello World Plugin](https://github.com/pojome/elementor-hello-world).

**Comment by lanzeni** [comment]
salut,
je vient de mettre a jour elementor et je rencontre un problème  
[problème avec elementor.docx](https://github.com/elementor/elementor/files/2937458/probleme.avec.elementor.docx)
Class 'Elementor\Control_' not found
Warning: ucwords() expects exactly 1 parameter, 2 given
