### ISSUE TITLE
Column inside column issue

### ISSUE THREAD

**Issue by fbrkdals1231** [pojome/elementor#3682]
Hello,

I like your team elementor plugin very much. I think this is a really well made plugin. :)

I am currently blocked by one issue while creating a page with an elementor.
Please take a look at the screenshot below.
https://s18.postimg.org/vc3ygk4kp/screenshot_647.png
https://s18.postimg.org/kpa5bbbwp/screenshot_650.png

As you can see in the screenshot, there are two columns in a section, I would like to add a widget to each column, one vertical and the other one horizontal.

Can I add horizontal and vertical toggle to columns?
And let me know if I am using the wrong elementor.

Thank you,
Winter

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
