### ISSUE TITLE
Request - Post ordering

### ISSUE THREAD

**Issue by Lukeskygawker** [pojome/elementor#3683]
Hi, I am a big fan of Elementor. However something that is vital to my website, and restricting my use is my visitors being able to re-order/sort my blog posts by 'likes' or a rating.

I was hoping you would be able to inform me if this is currently possible? Or soon to be?
From what I am aware there is no way to set any unique ordering to the post widget, using other sets of data (ie. post likes/ comments).

Thank you,

Luke

**Comment by bainternet** [comment]
Currently no, but should be.
I merged this issue with  #1748, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
