### ISSUE TITLE
Other plugins Incompatibility (Chrono Forms)

### ISSUE THREAD

**Issue by AxelConsulting** [pojome/elementor#3688]
Good morning,

I'm writing in order to inform you that there is an incompatibility with Chrono Froms plugin.

Each time I forget this plugin enabled and I save the page edited with Elementor, I loose the whole content of the page I've just saved. Then I have to disable the Chrono Forms plugin, roll back the revision of the pages and edit them again....

If it is not possible to fix this issue, I kindly ask you to find a way to prevent opening or saving pages with Elementor when incompatible Wordpress plugins, such as Chrono Forms, are enabled.

Can you please handle my request?
I thank you in advance.

Kind regards,
Domenico

**Comment by bainternet** [comment]
@AxelConsulting 

For us to prevent conflicts with other plugins is impossible because there is no way we can monitor every plugin out there.

what exactly is the conflict?

**Comment by AxelConsulting** [comment]
If you try to edit and save a page with Elementor while the Chrono Forms 5 plugin is enabled, you'll lose all the content of the page.Elementor will say that the page has been successfully saved, but if you'll test it, you'll see it completely blank!The only way to get back the content is rolling back an older revision of the page and editing it again.
It could be suitable to display a warning like this: "Pay attention! An incompatible enabled plugin has been detected. Please disable it before to edit this page."
I thank you for your help.
Kind regards,Domenico
 

    Il Giovedì 8 Marzo 2018 13:52, raz ohad <notifications@github.com> ha scritto:
 

 @AxelConsultingFor us to prevent conflicts with other plugins is impossible because there is no way we can monitor every plugin out there.what exactly is the conflict?—

**Comment by bainternet** [comment]
@AxelConsulting 

Just installed Chrono Forms 5 plugin and my debug log is screaming of errors, I would contact the plugin developer to correct its issue first.

![screen shot 2018-03-25 at 10 19 38](https://user-images.githubusercontent.com/660572/37872690-16f517ac-3016-11e8-8f18-fb4277062b49.png)
![screen shot 2018-03-25 at 10 19 49](https://user-images.githubusercontent.com/660572/37872693-1c8bd76e-3016-11e8-9dec-d418a73fe0f9.png)


and that is just with activating the plugin.
