### ISSUE TITLE
Fatal error: Class 'Elementor\Widget_Base' not found

### ISSUE THREAD

**Issue by niamulrox** [pojome/elementor#3690]
Hi, 

I am trying with your demo plugin https://github.com/dtbaker/elementor-custom-element to include in my  extensions plugin. So I just coy all code except commented plugin part as I am going to support short-code in my own plugin and its always showing the following error Fatal error: Class 'Elementor\Widget_Base' not found . 

Just remove bellow code from elementor-custom-element.php as I am supporting it in my own plugin. Can anyone advice ?

```php
/**
 * Plugin Name: Elementor Custom Elements
 * Description: Custom element added to Elementor
 * Plugin URI: http://dtbaker.net/web-development/creating-your-own-custom-elementor-widgets/
 * Version: 0.0.1
 * Author: dtbaker
 * Author URI: http://dtbaker.net
 * Text Domain: elementor-custom-element
 */
if ( ! defined( 'ABSPATH' ) ) exit;
// This file is pretty much a boilerplate WordPress plugin.
// It does very little except including wp-widget.php

**Comment by bainternet** [comment]
@niamulrox 

This is not our demo plugin, this one is: https://github.com/pojome/elementor-hello-world

and if you are getting this error it means that you include your widgets before elementor includes his own classes.

please see our demo plugin.
