### ISSUE TITLE
Feature request: ability to manually set lat/lang on google map widget.

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3695]
I'd strongly suggest a couple of optional lat/lang text fields. Google maps is really imprecise when you simply pass an address. Needs almost always to be corrected.

Also, the ability to hide some things... Maybe our clients do not want the review box in their own site, for example...

**Comment by bainternet** [comment]
@stratboy 

We keep the maps widget as simple as possible to avoid the need for users to enter an API key. Sadly this prevents us from customizing the map as much as we/you want.

If you always find yourself correcting it anyway, you can always create the iframe yourself and embed it manually.

Last, you can use the address field to enter your lat/lang separated by a comma and that should work.

thanks for the suggestion.
