### ISSUE TITLE
Unable to open accordion, toggle and tabs elements in frontend

### ISSUE THREAD

**Issue by Gregorianpics** [pojome/elementor#3698]
## Description

When I try to use accordions, toggle or tabs, they word when I try it in the elementor-editor. Trying it frontend, those elements won't open.

## Steps to reproduce

I am using the newest version of Elementor. When I drop those elements on the page, they open in the elementor editor but not in the frontend. See http://zapperlot.ch.hobo.sui-inter.net/rahmenbedingungen-fuer-kursteilnehmer/

## Environment

Elementor 1.9.7
Wordpress 4.9.4

**Comment by bainternet** [comment]
@Gregorianpics 

On the page, you linked there is a JavaScript error that comes with your theme, please test with a native WordPress theme, if the issue still persists please feel free to reopen this issue.
