### ISSUE TITLE
Bug/Issue: Social Icons Padding is uneaven between icons. Looks sloppy.

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#3699]
Hello,

Please fix/make equal the icon padding spacing for the icons within the widget "elementor social icons" They are completely uneven depending on the icon we choose. They should all have equal padding space because right now they look very sloppy.

A few examples of the social icons looking uneven are below, but make sure you adjust your entire social icons in the kit. Thanks in advance. 

<img width="163" alt="screen shot 2018-03-07 at 4 58 13 pm" src="https://user-images.githubusercontent.com/36935915/37120649-fa7f197e-2228-11e8-9587-b2714e3b7008.png">

**Comment by bainternet** [comment]
@smile00000 

We give the exact padding to all icons, but we do not control the icon side itself. Not a real issue here.

**Comment by smile00000** [comment]
@bainternet It’s an issue because they are not spaced correctly. There is sloppy space in-between each of the icons and looks unprofessional. Please change this to a feature request to improve this. Thanks in advance.

<img width="163" alt="37120649-fa7f197e-2228-11e8-9587-b2714e3b7008" src="https://user-images.githubusercontent.com/36935915/37158979-af0076c2-22ba-11e8-885c-e8d18432a4f8.png">
