### ISSUE TITLE
Layout on Safari Not working!!

### ISSUE THREAD

**Issue by sampc** [pojome/elementor#370]
Hi guys !

Column Layout on safari not working ?
[system-info-localhost-04-08-2016.txt](https://github.com/pojome/elementor/files/400782/system-info-localhost-04-08-2016.txt)

**Comment by arielk** [comment]
Can you please send us a screenshot from safari?

**Comment by sampc** [comment]
Safari 5.xxx on windows

**Comment by arielk** [comment]
Fixed https://github.com/pojome/elementor/commit/27a276d562128c228a9f0473c577e6515c64d942
