### ISSUE TITLE
[feature request] - allow section as anchor

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#3705]
Hello,

Please do not close a ticket before you allow us to reply. We were not done with the issue.
We are referencing this ticket and our demo video:    #3630 https://github.com/pojome/elementor/issues/3630#issuecomment-371491424

We understand what you are saying about padding but we are unable to put the anchor (or even a spacer) on a section horizontally across the ENTIRE page, it only will go on top of one of the columns. That will not work it will make the rest of the section uneven.

If a column is already established on a section first, it basically prevents us from putting anything horizontally above or below that stretches the entire page...such as anchors or spacers, etc...

Please advise. Thanks in advance :).

**Comment by bainternet** [comment]
@smile00000 

Like I said, sadly, this is how Elementor works, the only workaround I can think of is to add a section above it with your anchor and adjust the padding correctly.

**Comment by smile00000** [comment]
Yes but even with these sections, you cannot add a section across the entire page. So we would have to add 2 sections, one to column a and one to column b with differing padding to even it out. I think we need a feature request to allow sections and anchors above these columns...

**Comment by bainternet** [comment]
a feature request is something else.

**Comment by smile00000** [comment]
@bainternet It is kind of a feature request but also really sort of a bug/issue:

Right now if a section is blank you can create the following:
anchor > spacer > 2 columns > Spacer.

But if a section is not blank and already has 2 columns in it, you cannot later add anchors and spacers that fit horizontally across the page.

**Comment by bainternet** [comment]
@smile00000 

Re-thinking about this, It's not an issue and is more of a request that I don't see implemented anytime soon.

Any widget, be it an anchor or a spacer ... must live inside a column, This is how elementor works.

As for section as an anchor, if you give your section a CSS ID it will act as an anchor.
