### ISSUE TITLE
Bug Report when embedding iframe

### ISSUE THREAD

**Issue by mukherjeeprem** [pojome/elementor#3708]
I believe this is a bug as we've gone through a lot of trouble shooting and help with experts on various facebook groups.  
Elementor was working fine until we upgraded to an SSL on our site.  
Since doing so, we are unable to save any pages that have an embedded iframe in any type of widget.
After doing the SSL changeover, we followed the directions to change the URL from http to https, we made sure our PHP was was updated and that our memory limit was set correctly.
We have two different iframe links that we are trying to embed, one is a link to an http form and the other is a link to an https video.  We've tried them in text widgets, short code widgets, and HTML widgets and when we do any of those options and press update, we get a 404 server error and can't save the page.  As soon as we take the iframe out, we can make whatever changes we want and save everything just fine.  Those same iframe links will embed and display properly on standard wordpress pages but on any/every elementor page, we get a 404 server error.

In addition to that, we have some pages that were completed before the SSL changeover that have the same iframes embedded.  Those pages work fine.  However, we are no longer able to modify those pages as when we do, we get the 404 server error.

This is an example of a page that has the iframe form embedded where it is working fine:
https://amalfifineart.com/contest/blm/

Here is one iframe code we tested (it's the same code that was previously embedded on the page above):
<iframe id="taveForm" src="http://tave.com/amalfifineartportraiture-inline/contact/blcontest" width="100%" height="550px" frameborder="0" scrolling="yes"></iframe>

We thought it might be an issue of an HTTPS site pulling an iframe from an HTTP site so we then tried an HTTPS iframe code and that didn't work either:
<iframe allowFullScreen frameborder="0" height="564" mozallowfullscreen src="https://player.vimeo.com/video/249858899" webkitAllowFullScreen width="640"></iframe> 

As I mentioned, both of the above iframe codes work fine on non-elementor pages and both used to work fine before the SSL was incorporated.

We have elementor installed on two other sites and have the same issue where any of the pages can be updated but as soon as we embed an iframe, they stop working.  Both other sites also have SSL certificates.

**Comment by mukherjeeprem** [comment]
Just to provide an update, we have determined that the issue is related to an interaction problem between elementor and the mod security firewall in my cpanel.  once mod security is turned off, elementor works properly.  my webhost is not comfortable keeping mod security off.  are there any other workarounds?

**Comment by bainternet** [comment]
@mukherjeeprem 

First, you simply can't embed an Iframe with `http` in an `https` page, it won't work and the browsers will block it.

as for your issue not being able to save pages with embedded iframe after your move to `https`
can you tell us what you did to migrate your site form to `https` and also what rule is triggered by Mod Swcurity.

**Comment by mukherjeeprem** [comment]
Hi, Most of the HTTPS changeover was done by my webhost.  As far as I know, she added the security certificate, changed any of the code from HTTP to HTTPS.  Then our wordpress web address was changed in settings.  Then our elementor URL was changed in the elementor settings.
In regards to the iframe not working or being blocked, that doesn't seem to be the case.  Here is an example of that on one of our other sites:
https://arisingimages.com/wedding/
The contact form at the bottom is an HTTP contact form and it displayed properly on all the browsers we tested it on.  Inside elementor, the mod security firewall is now preventing us from adding ANY iframe including an HTTPS iframe without turning mod security off first.  
On any standard wordpress pages (like the one I linked above), I can embed iframes that are both HTTP and HTTPS and they save and display with no problem.

**Comment by mukherjeeprem** [comment]
These are some of the mod security error codes.  These may not all be related to the iframes, but these are the main errors:

77138861, 77133976, 77134134, 77134556, 77136158

**Comment by bainternet** [comment]
@mukherjeeprem 

First, the page you linked with the contact form at the bottom is displayed and not blocked because the iframe of the contact form is from `https` protocol.

as for the error codes, Sadly, I have no way of telling what these rules are. 

So the best thing you can do is ask your hosting to exclude elementor from mod_sequrity.

**Comment by mukherjeeprem** [comment]
Sorry, not sure what you mean, the page I linked above is https and the iframe contact form on that page is http.  this is the code on that page:
<iframe id="taveForm" src="http://tave.com/arising-images-inline/contact/wedding" width="100%" height="650px" frameborder="0" scrolling="yes" ></iframe>

**Comment by mukherjeeprem** [comment]
Venumurthy, make sure you are not trying to embedding http content into https pages.  
Also, you need to deactivate any cpanel firewalls.  In my case, the mod security firewall was causing my elementor pages to not update/save.  Now when I make updates, I just turn off the firewall, make my updates, then turn the firewall back on.

**Comment by tamelander** [comment]
I have the same 403 error problem when trying to save an Elementor page with an iframe, in this case a https page. I used https://www.sslshopper.com to check the SSL certificate and it is valid. Any leads?

I am using the 2.7 beta 2 at the moment and try to help out squashing bugs.

**Comment by RonR-WebDesign** [comment]
I was having server error 403 and found some iframe code.  I removed it and that fixed it.  Then I tried <iframe></iframe> and got the server error.
