### ISSUE TITLE
Glitch/Bug: Elementor incorrectly recognizes the entire page of anchors as all “active” instead of when you scroll to that section of the page

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#3709]
Hello,

Elementor incorrectly recognizes the entire page of anchors as all active, instead of when you scroll to that section of the page! 

There is an active pointer color and a hover pointer color that you can specify the underline color of a menu link. They show up correctly in elementor editor view, but not live on site because the entire site is coded in such a way to make all anchor points active even if you haven't arrived at that section of the page.  

It only works if the links in wp-admin menu are set to ie. "#about" instead of "https://yourwebsite.com/#about" but that’s worthless if you have the header on another page bc then it won’t send you there.

If you have the links set to "https://yourwebsite.com/#about" and you go to that page every single link at the top is underlined aka active when it should only be underlined when you get to that section of the page. So what you see then is all white instead of the section you are on which should be black.

Example in screenshare video below:
https://www.useloom.com/share/9a5ba62de6e24d99bee92bb711162aab

Thanks in advance!

**Comment by bainternet** [comment]
@smile00000 

the issue you are describing is caused by WordPress and not Elementor as Elementor nav menu widget uses the native `wp_nav_menu`. elementor does not set the `current-menu-item` class.

**Comment by finnsbali** [comment]
I think it is now an Elementor issue since the class is .elementor-item-active example:
<li><a href="https://www.something.com/#about" class="elementor-item  elementor-item-active">ABOUT</a></li>

is somehow I can fix it or have I been doing it wrong?

**Comment by tannerchung** [comment]
I just discovered this bug as well, where the menu is showing `elementor-item-active` as a class for all of nav menu items in the Elementor Nav Menu widget; however, the weirdest thing is that this only happens on the homepage and not on other pages.

![screenshot_081918_014409_am](https://user-images.githubusercontent.com/3707037/44305871-5e9fa780-a351-11e8-9dbb-d62a9465b1f3.jpg)

![screenshot_081918_014458_am](https://user-images.githubusercontent.com/3707037/44305879-7bd47600-a351-11e8-9b8a-fd4c24082e3c.jpg)

**Comment by tannerchung** [comment]
Update

To check if this bug had anything to do with the homepage, I saved the homepage as a full template, created a new page, imported the template into the new page called "Home 1.1". I opened "Home 1.1" and it does not show the same issue where elementor-item-active is set. However, "Home 1.1" does display this behavior once I change the Hompage in /wp-admin/options-reading.php to "Home 1.1". This bug has to do with the Homepage.

I'm trying to reproduce this bug with an old backup of the site that did not display this behavior and will update once I figure out where this permanent active state is coming from - although a question of mine is, elementor is the only plugin that would add the class, elementor-item-active on hover so what else could it be coming from?

**Comment by tannerchung** [comment]
Update

I'm at a loss. I turned off every plugin except Elementor and it was still showing but my staging site that was just a older version of the site was not showing this behavior after importing a full saved template of the homepage.

**Comment by tannerchung** [comment]
Update

I installed another Elementor widget pack and used their Nav widget. Unfortunately, something keeps assigning each of the nav items with `elementor-item-active` so it isn't the nav widget either.

**Comment by tannerchung** [comment]
Update

I figured it out.. whenever you use https:// in the Menu link, some script is marking the link as active. Remove https://

**Comment by ronstall** [comment]
I've just hit the same issue as well. I've submitted a support ticket to Elementor and I'll post the fix here when I get one.
This issue shouldn't have been closed.

**Comment by ronstall** [comment]
**OK here's the solution:**

The WP menu works in such a way that the active state is determined only by the current page URL. The scroll position on a page does not affect that. Therefore, by adding #anchor menu items, your browser assumes that you are referring to the same page, and the WordPress makes them active. The Elementor widget just displays these items regarding active/inactive status.

This problem with active link state can be solved in some tricky way.

You need to 
replace links like this
`https://domain.com/#anchor`

to these
`https://domain.com/./#anchor`

They will no longer be recognized by the WordPress as active on the homepage.

**Comment by tannerchung** [comment]
I've never seen that dot notation before, what does that mean?

**Comment by vexshad** [comment]
Great solution!! Thanks

**Comment by UTF-8** [comment]
Thank you  ronstall !

**Comment by lorimgarcia** [comment]
tannerchung - you SAVED me! This problem was bugging me all day. Thanks so much for your response!

**Comment by walii06** [comment]
### **Solution**
I also faced a similar issue and the solution posted above didn't work for me.
Instead of giving IDs to sections/widgets. I used Elementor's "Menu Anchor" widget and gave an id to that widget and it resolved my issue.
