### ISSUE TITLE
Maybe add style for widget a Text editor ??

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#3711]
I am use text editor as editor full screen and bad when max-width:580px.
Please, add as default style for .elementorwpeditor max-width:100%

**Comment by bainternet** [comment]
@ravilrrr 

can you provide screenshot? steps to replicate?

**Comment by ravilrrr** [comment]
![2018-03-11_16-15-30](https://user-images.githubusercontent.com/5197026/37253170-76600640-2547-11e8-9c58-a406575581ac.png)

Create post in elementor editor.

![2018-03-11_16-17-31](https://user-images.githubusercontent.com/5197026/37253200-ed05152e-2547-11e8-9781-18316e09527e.png)

**Comment by bainternet** [comment]
@ravilrrr 

Again not something we can control if a theme registers his styles for the `WP_editor` there is nothing we can do about it.

**Comment by ravilrrr** [comment]
How can you not? The style of the widget this is your task. You just need to add
.elementorwpeditor  {max-width:100%;}

**Comment by ravilrrr** [comment]
You guys are upsetting me.  I use the default theme and have to deal with such troubles on my own.
