### ISSUE TITLE
Content-Security-Policy

### ISSUE THREAD

**Issue by shimsa** [pojome/elementor#3713]
Hello,

I'm using Security Headers for my site, but for Content-Security-Policy I have to set "unsafe-inline" that reduces security. This is because Elementor uses inline scripts. Also, most widgets (Slider, Animated Headline, Countdown, etc.) do not work without "unsafe-inline".
It would be possible to make Elementor CSP friendly, ie. without inline scripts?

Thank you.

Tom

**Comment by bainternet** [comment]
@shimsa 

As far as I know, none of the above-listed widgets or any of our widgets use an inline script. its all loaded in the frontend.js.


can you provide an example?

**Comment by shimsa** [comment]
@bainternet 
Elementor inserts an inline script on each page "<script type='text/javascript'>/* <![CDATA[ */ var ElementorProFrontendConfig..." and "<script type='text/javascript'>/* <![CDATA[ */ var elementorFrontendConfig...".
When the Content-Security-Policy header disables inline scripts, this code is not loaded at all and maybe some widgets are not working properly.

Is it possible for Elementor to add these inline scripts to a separate file like best practice method?

Thank you.

Tom

**Comment by bainternet** [comment]
@shimsa 

Ok, Your are talking about the configuration, not a script per widget.
Well sadly, if you look at the data in that script, it's all dynamic and calling it for a file makes no sense.
