### ISSUE TITLE
Notice: Array to string conversion in manager.php on line 35

### ISSUE THREAD

**Issue by anjo-branco** [pojome/elementor#3718]
Notice: Array to string conversion in D:\xampp720\htdocs\elem\wp-content\plugins\elementor.2.0.0-beta1\core\dynamic-tags\manager.php on line 35

php-version 7.2.0

**Comment by bainternet** [comment]
@anjo-branco 

can you provide steps to replicate?

**Comment by anjo-branco** [comment]
Notice: Array to string conversion in D:\xampp720\htdocs\elem\wp-content\plugins\elementor.2.0.0-beta2\core\dynamic-tags\manager.php on line 35

This error message appears 4 times between header and content, only in the customizer, customizing Astra v 1.2.3. The only part that is 4 times on the page is the footer widget area. With the Theme GeneratePress v 2.0.2 the message appears as well 4 times, but the theme has only 3 Widget areas no footer.

The messages appear with Elementor 2.0 beta 1 and beta 2. The messages don´t appear with Elementor 1.9.8.

System: Windows 10 Enterprise, Version 1709, Build 16299.125
Xampp  Version 7.2.0 with php 7.2.0
Chrome Version 65.0.3325.146 (Offizieller Build) (64-Bit)
Firefox developer edition 59.0b12 (64-Bit)
Microsoft Edge 41.16299.15.0

I hope that Elementor could fix that. Good luck!

Anjo Branco

**Comment by bainternet** [comment]
@anjo-branco 

Still can't replicate tried all 3 theme you mentioned.

Anyway, in the next beta, we did some rework on that area, so be sure to test it once it out.

I'll leave this open for now.

**Comment by anjo-branco** [comment]
After some reboots and updates of other plugins during the lst days the messages still appeared half an hour before with elementor 2.0 beta2. 

But: After updating to elementor 2.0 beta 3 the messages desappeared!!!

Resolved!

Thank you for your work!

**Comment by bainternet** [comment]
Yay us.
Thanks for reporting.
