### ISSUE TITLE
[Request] Bubble/Circular Menu

### ISSUE THREAD

**Issue by sti000en** [pojome/elementor#3719]
I don‘t know if this has already been requested but it would be nice to have a bubble/circular-menu widget.

Here some examples (since my description may be not precise enough ;) )

https://wordpress.org/plugins/bubble-menu/

https://youtu.be/kreEZ01tO2I

Thank you for your awesome work, keep it up!

Greetings
stien

**Comment by bainternet** [comment]
@sti000en 

That's a nice suggestion.
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
