### ISSUE TITLE
Image Carousel "slides to show" on tablet

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#372]
Hi guys, I just found another issue.

If you have an image carousel with `slidesToShow: 1`, and see it on live page (not in Elementor Editor mode), the slider will resize to 2 slides when on 480-766px viewport:

When on larger than 766px viewport:
![image](https://cloud.githubusercontent.com/assets/1287713/17401258/e2151d82-5a76-11e6-9514-507e6be7fe15.png)

When on 480 - 766px viewport:
![image](https://cloud.githubusercontent.com/assets/1287713/17401266/f513b15a-5a76-11e6-92f1-d6d5c1eb868c.png)

If you look at `frontend.js`, you make default configurations like this:

```
		var defaultOptions = {
				responsive: [
					{
						breakpoint: 767,
						settings: {
							slidesToShow: 2,
							slidesToScroll: 2
						}
					},
					{
						breakpoint: 480,
						settings: {
							slidesToShow: 1,
							slidesToScroll: 1
						}
					}
				]
			},

			slickOptions = $.extend( {}, defaultOptions, $carousel.data( 'slider_options' ) );
```

It seems there is no way to override this default configurations when users choose `slidesToShow: 1` on the Elementor editor.

Another question:
Could you define the table breakpoint as `768` instead of `767`? If you define `767` the layout would change when reached `766px`. It's 1 pixel difference, but seems important.

Thanks!

**Comment by Nat-Faeeria** [comment]
#227 #286

**Comment by arielk** [comment]
We're going to take care of everything related to responsive the following versions, thanks for your report

**Comment by arielk** [comment]
Fixed https://github.com/pojome/elementor/commit/2677b9d04f1ceaca45a311f230d39b255024650d
