### ISSUE TITLE
[bug] Elementor page content is duplicated in sidebar

### ISSUE THREAD

**Issue by phdenis63** [pojome/elementor#3720]
Hello,

When using plugins such as "simple links" or "content blocks" (and perhaps others), the content of an elementor page is duplicated in sidebar. 
(see http://test.banneux-nd.be/fr/test-duplicate-in-sidebar/)
If you want I can give you access to this test site to help you to investigate the problem.

Best regards,

Philippe

![elementor-duplicate-on-sidebar](https://user-images.githubusercontent.com/36880621/37242175-229ea7d8-2465-11e8-959b-61a56eeb9187.png)

![content-blocks](https://user-images.githubusercontent.com/36880621/37242177-3397862c-2465-11e8-8471-2f0ca0aac7c4.png)
![siimple-links](https://user-images.githubusercontent.com/36880621/37242178-33b68e6e-2465-11e8-9da5-499bd3a81eae.png)

**Comment by bainternet** [comment]
@phdenis63 

Please contact our support and provide them access so they will be able to investigate better.
