### ISSUE TITLE
Provide tool that adds opacity shadowing behind flipbox text

### ISSUE THREAD

**Issue by jonathanasbell** [pojome/elementor#3721]
a semiopaque box behind text that overlays an image to improve contrast and readability. See https://www.nngroup.com/articles/text-over-images/

**Comment by bainternet** [comment]
You can already do that by setting a section background image and on top of that setting the column background to a classic color with opacity lower then 1.

**Comment by jonathanasbell** [comment]
But doesn't that mean I won't be able to use a background image? Also, I don't want opacity in the ENTIRE background... Just behind the text

Sent with AquaMail for Android<https://play.google.com/store/apps/details?id=org.kman.AquaMail>
http://www.aqua-mail.com

On March 11, 2018 7:10:31 AM raz ohad <notifications@github.com> wrote:

You can already do that by setting a section background image and on top of that setting the column background to a classic color with opacity lower then 1.

**Comment by jonathanasbell** [comment]
![image](https://user-images.githubusercontent.com/31919933/37253047-b5b4a2be-2502-11e8-99e4-9cb0ec11c25c.png)
Here there is a background image already. I just want to put n opcity layer/box behind the text because of the background

**Comment by jonathanasbell** [comment]
![image](https://user-images.githubusercontent.com/31919933/37253140-ecba38ae-2503-11e8-84c9-98f9281a5a10.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


for now, you can do that only with custom CSS
Thanks for the feedback.
