### ISSUE TITLE
Style for control elements, before LI (no bug)

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#3728]
Dont default theme (vt-bloging)
See a dot cursor, before li element
I know that style can be added, but this should not be

![2018-03-11_18-02-31](https://user-images.githubusercontent.com/5197026/37254449-7a350f94-2557-11e8-83ad-8b4c80ee1ca6.png)
![2018-03-11_18-02-49](https://user-images.githubusercontent.com/5197026/37254452-7dc2ba44-2557-11e8-9681-7edf2471465a.png)
![2018-03-11_18-05-03](https://user-images.githubusercontent.com/5197026/37254455-81ab3b86-2557-11e8-9acd-98590949c983.png)

**Comment by bainternet** [comment]
@ravilrrr 

Not something we can control. If a theme overwrites our CSS using "greedy" selector there is nothing we can do about it.

This should be reported to the theme developer.

**Comment by ravilrrr** [comment]
But as same adding in css !important ?? No??

**Comment by ravilrrr** [comment]
a theme does not overwrite you CSS, but uses standard selectors.
