### ISSUE TITLE
Feature Request: Masonry Layout and Image Hover effect on "Image Gallery "

### ISSUE THREAD

**Issue by webinsightin** [pojome/elementor#3731]
Why is the "Image Gallery" widget so simple? Request you to please add more features in this widget as Image Gallery is a very important part of any website.

Features Suggestions:
1. More Layout option eg. Masonary
2. Item overlay effect

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by primaverapro** [comment]
hello,
i would like to create the image gallery with filtres (category) and pdf file download possibility.  Or pdf gallery with  thumbnails
![example](https://user-images.githubusercontent.com/48838637/55030258-417c3700-500c-11e9-945d-2631d888342b.png)
