### ISSUE TITLE
Feature Request: Allow  a slider in the background (same as image and video today)

### ISSUE THREAD

**Issue by SharonAR** [pojome/elementor#3732]
Hello

It would be great to have the option to place a simple slider in the background of a section, same as it is possible to place a video or an image today.
It is used and needed in modern sites and usually worked-around with negative margins to place other Elementor widgets over a slider. 
Working with negative margins is a pain and hard to maintain over different screen sizes, devices and clients.
It would be a great improvement if Elementor Pro supported this natively.

Thanks
Sharon

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
