### ISSUE TITLE
Bundle PHP Mustache to avoid duplicating widget code

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3735]
There is an old issue #181 regarding this same idea which was closed but I think the idea is really interesting and deserve a second chance.

Bundling PHP Mustache with Elementor is indeed a good idea. Of course, not all widgets can leverage this capability due to the fact they depend on server data but a lot can (all the design only stuffs).

Just adding a "_render_with_php_mustache" method could be enough.

```
protected function _render_with_php_mustache()
{
	$m = new Mustache_Engine;
	echo $m->render($this->_content_template(), array('settings' => /* function to grab the settings */));
}

protected function render()
{
	$this->_render_with_php_mustache();
}

protected function _content_template()
{
	?>
	Mustache code
	<?php
}
```

**Comment by bainternet** [comment]
If you want to avoid duplicating content, don't implement _content_template in your widget.

The same thing applies as before, In all cases, we must have a PHP version and in some JS will do the job. So the only required on is the PHP `render`. We add the JS version to make the editor respond faster on changes that don't require server-side rendering but you can ignore it if you choose to.
