### ISSUE TITLE
Elementor rendering not called on custom post types thru get_the_content

### ISSUE THREAD

**Issue by spirau** [pojome/elementor#3741]
I update part of a page lately with ajax with posts that have a specific post type and are designed using Elementor. On the server, I use this loop to recover the content to be sent, but despite applying the filter the-content, Elementor is not triggered so the content is not rendered correctly. 

    $wpbp = new WP_Query(['post_type' => $type, 'nopaging'=>true, 'post__in'=>$post_id]);
    $content = "";
    if ($wpbp->have_posts())
    while($wpbp->have_posts())
    {
        $wpbp->the_post();
        $content .= apply_filters( 'the_content', get_the_content() );
     }
    wp_reset_query();
    return do_shortcode($content);

**Comment by bainternet** [comment]
@spirau 

where are you running this code? inside a shortcode? because if you do then It will not work, try using the Plugin API:
```PHP
global $post;
$wpbp = new WP_Query(['post_type' => $type, 'nopaging'=>true, 'post__in'=>$post_id]);
$content = "";
if ($wpbp->have_posts())
while($wpbp->have_posts())
{
    $wpbp->the_post();
    $content .= \Elementor\Plugin::$instance->frontend->get_builder_content( $post->ID, true );
 }
wp_reset_query();
return do_shortcode($content); 
```

**Comment by spirau** [comment]
Hi

 

It’s not inside a shortcode. Here is the call stack. 

 

#1 mpPost::Render(canevas, 5150) called at [/home/marip/www.refonte/wp-content/plugins/marip-almanach/mp-metaphysic.php:52]
#2 mpMetaphysic::RenderCanevas(5150) called at [/home/marip/www.refonte/wp-content/plugins/marip-almanach/mp-almanach.php:204]
#3 mpAlmanach::AjaxRender() called at [/home/marip/www.refonte/wp-includes/class-wp-hook.php:286]
#4 WP_Hook->apply_filters(, Array ([0] => )) called at [/home/marip/www.refonte/wp-includes/class-wp-hook.php:310]
#5 WP_Hook->do_action(Array ([0] => )) called at [/home/marip/www.refonte/wp-includes/plugin.php:453]
#6 do_action(wp_ajax_almanach) called at [/home/marip/www.refonte/wp-admin/admin-ajax.php:97]

 

It’s inside an admin_ajax call, it’s directly rendering the content of a post n°5150 which is a custom type edited with Elementor.

 

I’ve changed the line :

 

                   $content .= \Elementor\Plugin::$instance->frontend->get_builder_content( get_the_ID(), true );

 

Now it’s doing something different, but the columns are not well rendered https://refonte.marip.com/outils-feng-shui-ba-zi-gratuits/tong-shu-du-jour/#

Previsions and Activities should be in 2 column like in the editor :

 



 

De : raz ohad [mailto:notifications@github.com] 
Envoyé : lundi 12 mars 2018 16:35
À : pojome/elementor
Cc : Eric Spirau; Mention
Objet : Re: [pojome/elementor] Elementor rendering not called on custom post types thru get_the_content (#3741)

 

@spirau <https://github.com/spirau> 

where are you running this code? inside a shortcode? because if you do then It will not work, try using the Plugin API:

global $post;
$wpbp = new WP_Query(['post_type' => $type, 'nopaging'=>true, 'post__in'=>$post_id]);
$content = "";
if ($wpbp->have_posts())
while($wpbp->have_posts())
{
    $wpbp->the_post();
    $content .= \Elementor\Plugin::$instance->frontend->get_builder_content( $post->ID, true );
 }
wp_reset_query();
return do_shortcode($content);

**Comment by bainternet** [comment]
@spirau 

It seems like there is a broken HTML code ( missing closing `div` ) coming from one of the shortcodes which breaks the cloumns.

**Comment by spirau** [comment]
Hi

 

In case some of my posts are not edited with Elementor, how to now it, since the get_builder_content fails to return content in such a case?

 

De : raz ohad [mailto:notifications@github.com] 
Envoyé : lundi 12 mars 2018 16:35
À : pojome/elementor
Cc : Eric Spirau; Mention
Objet : Re: [pojome/elementor] Elementor rendering not called on custom post types thru get_the_content (#3741)

 

@spirau <https://github.com/spirau> 

where are you running this code? inside a shortcode? because if you do then It will not work, try using the Plugin API:

global $post;
$wpbp = new WP_Query(['post_type' => $type, 'nopaging'=>true, 'post__in'=>$post_id]);
$content = "";
if ($wpbp->have_posts())
while($wpbp->have_posts())
{
    $wpbp->the_post();
    $content .= \Elementor\Plugin::$instance->frontend->get_builder_content( $post->ID, true );
 }
wp_reset_query();
return do_shortcode($content);

**Comment by spirau** [comment]
I’ve added this line :

 

$isElementor = get_post_meta( $id, '_elementor_edit_mode', true );

 

Is it reliable ?

 

De : Eric Spirau [mailto:eric@spirau.com] 
Envoyé : jeudi 15 mars 2018 07:08
À : 'pojome/elementor'
Objet : RE: [pojome/elementor] Elementor rendering not called on custom post types thru get_the_content (#3741)

 

Hi

 

In case some of my posts are not edited with Elementor, how to now it, since the get_builder_content fails to return content in such a case?

 

De : raz ohad [mailto:notifications@github.com] 
Envoyé : lundi 12 mars 2018 16:35
À : pojome/elementor
Cc : Eric Spirau; Mention
Objet : Re: [pojome/elementor] Elementor rendering not called on custom post types thru get_the_content (#3741)

 

@spirau <https://github.com/spirau> 

where are you running this code? inside a shortcode? because if you do then It will not work, try using the Plugin API:

global $post;
$wpbp = new WP_Query(['post_type' => $type, 'nopaging'=>true, 'post__in'=>$post_id]);
$content = "";
if ($wpbp->have_posts())
while($wpbp->have_posts())
{
    $wpbp->the_post();
    $content .= \Elementor\Plugin::$instance->frontend->get_builder_content( $post->ID, true );
 }
wp_reset_query();
return do_shortcode($content);

**Comment by spirau** [comment]
Hi Raz

 

The solution you provided is quite good. However, I get something broken when I call my ajax function on the client side. It seems that part of the content I try to retrieve is sent to output rather then passed.

 

This is my loop on the server, the content is passed back to ajax call :

 

while ($wpbp->have_posts())
{
    $wpbp->the_post();
    $id = get_the_ID();
    $isElementor = \Elementor\Plugin::$instance->db->is_built_with_elementor( $id );

    $content .= $isElementor ?
        \Elementor\Plugin::$instance->frontend->get_builder_content($id, true) :
        apply_filters( 'the_content',  get_the_content() );
}

 

this is the response on the client side. The json part is at the end. Elementor is loosing things on the road … Any idea ?

 

<style>.elementor-5238 .elementor-element.elementor-element-331a855 .elementor-spacer-inner{height:50px;}</style>
<div class="elementor elementor-5238">
    <div class="elementor-inner">
        <div class="elementor-section-wrap">
            <section data-id="393879a" class="elementor-element elementor-element-393879a elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-top-section" data-element_type="section">
                <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-row">
                        <div data-id="fd07e7f" class="elementor-element elementor-element-fd07e7f elementor-column elementor-col-100 elementor-top-column" data-element_type="column">
                            <div class="elementor-column-wrap elementor-element-populated">
                                <div class="elementor-widget-wrap">
                                    <div data-id="421668a" class="elementor-element elementor-element-421668a elementor-widget elementor-widget-shortcode" data-element_type="shortcode.default">
                                        <div class="elementor-widget-container">
{"success":true,"html":"<div class=\"type-canevas … <\/div>"}

 

 

De : raz ohad [ <mailto:notifications@github.com> mailto:notifications@github.com] 
Envoyé : lundi 12 mars 2018 16:35
À : pojome/elementor
Cc : Eric Spirau; Mention
Objet : Re: [pojome/elementor] Elementor rendering not called on custom post types thru get_the_content (#3741)

 

 <https://github.com/spirau> @spirau

where are you running this code? inside a shortcode? because if you do then It will not work, try using the Plugin API:

global $post;
$wpbp = new WP_Query(['post_type' => $type, 'nopaging'=>true, 'post__in'=>$post_id]);
$content = "";
if ($wpbp->have_posts())
while($wpbp->have_posts())
{
    $wpbp->the_post();
    $content .= \Elementor\Plugin::$instance->frontend->get_builder_content( $post->ID, true );
 }
wp_reset_query();
return do_shortcode($content);
