### ISSUE TITLE
[issue] Missing placeholder PRO form module on mobile [iOS Safari & Google Chrome]

### ISSUE THREAD

**Issue by Artneo7** [pojome/elementor#3743]
Hi,

The PRO form date and time picker doesn't appear on mobile.

Images: https://imgur.com/a/OA5sN

Check out this website on mobile.
https://pintadonabrasapiracicaba.com.br/#reserve-sua-mesa

I tested using iOS with Safari and Google Chrome browsers. Both have problems.

The **.elementor-date-field** and **.elementor-time-field** doesn't appear on mobile.

Can you replicate it?

**Comment by bainternet** [comment]
Known issue with mobile browsers implementing their own date pickers:
https://github.com/flatpickr/flatpickr/issues/1094
