### ISSUE TITLE
Full instructions for the new skin to the Posts widget (Elementor Pro)

### ISSUE THREAD

**Issue by vovagabel** [pojome/elementor#3744]
Please give full instructions how to add a new skin to the widget Posts (Elementor Pro).

My skin for Posts https://gist.github.com/vovagabel/b243f12f360166251332e803c16fc1e6

I want to place the skin in the folder wp-content/themes/my-theme/elementor/widgets/posts/skins/
How do I connect a new skin from the current directory? Please give the full working code.

**Comment by bainternet** [comment]
@vovagabel 

Same as before:

```php
add_action( 'elementor/widget/posts/skins_init', function( $widget ) {
	$widget->add_skin( new Skin_Custom( $widget ) );
});
```

The class file can sit in any folder you want, just make sure you include it before creating the instance:

```php
add_action( 'elementor/widget/posts/skins_init', function( $widget ) {
	include_once( 'path/to/your/skin/class/file/filename.php' );
	$widget->add_skin( new Skin_Custom( $widget ) );
});
```

**Comment by vovagabel** [comment]
In which file can I use this code? And how to make it work for an existing Posts widget (Elementor Pro).

```add_action( 'elementor/widget/posts/skins_init', function( $widget ) {
	include_once( 'path/to/your/skin/class/file/filename.php' );
	$widget->add_skin( new Skin_Custom( $widget ) );
});```

**Comment by menzer2015** [comment]
Hi this is exactly what I am looking for but something is not working correct, I put this code in my function.php

`add_action( 'elementor/widget/posts/skins_init', function( $widget ) {
	include_once( 'path/to/your/skin/class/file/filename.php' );
	$widget->add_skin( new Skin_Custom( $widget ) );
});

And I change the path and it find the class file which I copied and changed from Skins_Cards and also the add_skin() to the new class name. but I get the following error:

**Fatal error: Uncaught Error: Class 'Skin_Mem_Items' not found in my function file line *** **

Is there something I am missing or doing correctly....

Just to make sure my skin was working I added this 	$this->add_skin( new Skins\Skin_Mem_Items( $this ) ); in the posts.php widget and it worked so the skin I copied from Skins_Cards class works fine Not sure if it is a bug or if I am doing something wrong

Any help would be appreciated.
