### ISSUE TITLE
[PRO] How to add field type to Forms module?

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3745]
Hello,

I am searching for the way to add a new form field type to the "Forms" module available in the Pro version.

in "forms/module.php", there is a class with a constructor which call "add_form_field_type" to add the bundled types but how to use this method to add a newly created field type? What's the recommended way of doing it?

**Comment by bainternet** [comment]
@tristanleboss 

Your field type class must extend `ElementorPro\Modules\Forms\Fields\Field_Base` and to register it with the forms module use the API:

```PHP
\ElementorPro\Modules\Forms\Module::instance()->add_form_field_type( 'my_field_type', new InstanceOfFieldTpeClass() );
```

Hope this helps.
