### ISSUE TITLE
Images/Icons in tab titles

### ISSUE THREAD

**Issue by lewisdesign** [pojome/elementor#3750]
My client would like icon images inside their tab titles. How do I target that image to either add a class to it via jquery or replace it's filename like I am for hover? Whatever I try is not working!

_The second image shows the jQuery for the hover._

<img width="1010" alt="screen shot 2018-03-13 at 9 27 53 am" src="https://user-images.githubusercontent.com/28059298/37344574-1a3b7290-26a1-11e8-9aea-24abfa128ee3.png">
<img width="445" alt="screen shot 2018-03-13 at 9 29 29 am" src="https://user-images.githubusercontent.com/28059298/37344575-1a5b950c-26a1-11e8-8c4f-2baeb6e40c2f.png">

**Comment by bainternet** [comment]
@lewisdesign 

Seems like your code should work, the only issue can think of is that you are triggering your JS to early,

a simpler, less time-sensitive version could be:
```js
$(document).on( 'mouseenter', '.elementor-tab-title img', function(){
     var src = $(this).attr('src');
      $(this).attr('src', src.replace( '-off', '-on' ) );
} );
$(document).on( 'mouseleave', '.elementor-tab-title img', function(){
     var src = $(this).attr('src');
      $(this).attr('src', src.replace( '-on', '-off' ) );
} );
```

**Comment by lewisdesign** [comment]
Thanks! - That works great for the rollovers, however, that was not my issue.

I am trying to apply the "-on" state to the active tab, so the link color is not only blue, but the icon is blue which is the "-on" state.

Please help!
