### ISSUE TITLE
Add skin Hook

### ISSUE THREAD

**Issue by vovagabel** [pojome/elementor#3751]
Please try on an example in which file you use this code. What code should be used to make the current code work.

// Add a custom skin for the Google Maps widget
```
add_action( 'elementor/widget/google_maps/skins_init', function( $widget ) {
   $widget->add_skin( new MySkins\Skin_Dark_Map( $widget ) );
} );
```

**Comment by bainternet** [comment]
@vovagabel 

We have no skin for the maps widget so this will never work.
