### ISSUE TITLE
Author Box widget and WP User Avatar (not Gravatar)

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#3757]
### Feature request: 
Allow the **Author Box widget** to pull in the avatar image for current author when using something like [WP User Avatar](https://wordpress.org/plugins/wp-user-avatar). Gravatar is often not a good solution, because many users don't have one, nor do they understand why they have to create yet another account. 

### Use case:
- I've included the **Author Box widget** in an Elementor template to be used when writing blog posts, so that it will pull in the avatar and bio of the current author for each post (with no intervention by the post author.) 
- We're using [WP User Avatar](https://wordpress.org/plugins/wp-user-avatar) for profile photos 

### Problem:
The **Author Box widget** seems to only pull in Gravatar photos. How can I get it to pull in the avatars attached to our user profiles instead? (see attached)

![profile-photo](https://user-images.githubusercontent.com/974442/37375958-3f2412f4-26df-11e8-978c-c0e085acd864.png)

**Comment by bainternet** [comment]
@mizejewski 

The Author Box widget uses the native WordPress `get_avatar_url` function which the plugin you mentioned fails to filter like it does to all other native WordPress avatar related functions.


luckly this is a simple fix which you can place in your functions.php, or even better, suggest it to the plugin author:

```PHP
add_filter( 'get_avatar_url', function( $url, $id_or_email, $args ){
	if ( is_email( $id_or_email ) ) {
		$user = get_user_by( 'email', $id_or_email );
		$user_id = $user->ID;
	} else {
		$user_id = $id_or_email;
	}
	if ( has_wp_user_avatar( $user_id ) ) {
    	return get_wp_user_avatar_src( $user_id );
	}
	return $url;
}, 10, 3);
```

**Comment by mizejewski** [comment]
@bainternet thanks for that snippet! I will also suggest to the plugin author that they should make the fix.

**Comment by siberlancer** [comment]
Im facing the same problem with Elementor Pro 2.0.  The Author Box widget only pulls in Gravatar photos instead of the picture attached to our profile using the **WP User Avatar** .  I had tried the given snippet above but no luck....

**Comment by rootion** [comment]
There is another plugin that is compatible with the Author Box Widget and it works out of the box: https://wordpress.org/plugins/wp-user-avatars/

**Comment by pako69** [comment]
@rootion a big thanks for this plugin, yes it works out the box!

**Comment by 000TWD** [comment]
Hi!
Thank you for this post and plugin! I have been searching for something and am so happy to have found my answer! 『**_[LOVE GURU SPECIALIST](https://www.thewarofdestiny.com/love-guru-specialist/) TWD_**』
Thanks again!

**Comment by Phontaine** [comment]
@rootion thanks for the plugin; my author images are now showing up

**Comment by aitude** [comment]
@rootion  @fadzli-zulkefli  @mizejewski  - We have released the new version 2.2.1 so now the get_avatar_url filter is defined in the plugin and working perfectly with a custom avatar.

**Comment by bentalgad** [comment]
Btw - if anyone is using ACF field for user image profile, this is the code i use to make the author box show the ACF image instead:

`// Fix Elementor Author Gravatar
add_filter( 'get_avatar_url', function( $url, $id_or_email, $args ){
	if ( is_email( $id_or_email ) ) {
		$user = get_user_by( 'email', $id_or_email );
		$user_id = $user->ID;
	} else {
		$user_id = $id_or_email;
	}
$image_id = get_user_meta($user_id, 'acf_field, true); // Change acf_field to your field name
	return wp_get_attachment_image_src( $image_id, 'thumbnail' )[0];
}, 10, 3);`

**Comment by davidgilfillan** [comment]
@bentalgad this snippet causes the following error in latest wp 5.3 running ACF e.g. when adding a new post (at least for me!) - any ideas?


Warning: strlen() expects parameter 1 to be string, object given in /var/www/html/wp-includes/formatting.php on line 3391
--
  |  
  | Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/formatting.php:3391) in /var/www/html/wp-admin/admin-header.php on line 9

**Comment by neosaveme** [comment]
to everyone I have a solution ;
tested and work with both acf and jet-engine just put your field name.


```
/**
 * Elementor 3.0 Use ACF or jet-engine image field as avatar 
 */
add_filter('get_avatar', 'acf_profile_avatar', 10, 5);
function acf_profile_avatar( $avatar, $id_or_email, $size, $default, $alt ) {
    if ( is_numeric( $id_or_email ) ) {
        $id   = (int) $id_or_email;
        $user = get_user_by( 'id' , $id );
    } elseif ( is_object( $id_or_email ) ) {
        if ( ! empty( $id_or_email->user_id ) ) {
            $id   = (int) $id_or_email->user_id;
            $user = get_user_by( 'id' , $id );
        }
    } else {
        $user = get_user_by( 'email', $id_or_email );
    }
    if ( ! $user ) {
        return $avatar;
    }
    $user_id = $user->ID;
    $image_id = get_user_meta($user_id, 'your-field-here', true); // CHANGE TO YOUR FIELD NAME
    if ( ! $image_id ) {
        return $avatar;
    }
    $image_url  = wp_get_attachment_image_src( $image_id, 'thumbnail' ); // Set image size by name
    $avatar_url = $image_url[0];
    $avatar = '<img alt="' . $alt . '" src="' . $avatar_url . '" class="avatar avatar-' . $size . '" height="' . $size . '" width="' . $size . '">';
    return $avatar;
}



add_filter('get_avatar_url', 'acf_profile_avatar_url', 10, 3);
function acf_profile_avatar_url($url, $id_or_email, $args){
    if ( is_numeric( $id_or_email ) ) {
        $id   = (int) $id_or_email;
        $user = get_user_by( 'id' , $id );
    } elseif ( is_object( $id_or_email ) ) {
        if ( ! empty( $id_or_email->user_id ) ) {
            $id   = (int) $id_or_email->user_id;
            $user = get_user_by( 'id' , $id );
        }
    } else {
        $user = get_user_by( 'email', $id_or_email );
    }
    if ( ! $user ) {
        return $url;
    }
    $user_id = $user->ID;
    $image_id = get_user_meta($user_id, 'your-field-here', true); // CHANGE TO YOUR FIELD NAME
    if ( ! $image_id ) {
        return $url;
    }
    $image_url  = wp_get_attachment_image_src( $image_id, 'thumbnail' ); // Set image size by name
    $avatar_url = $image_url[0];
    return $avatar_url;
}
```

**Comment by violllettta** [comment]
Thank you @neosaveme-zz. It worked beautifully. 
I am using an acf field. I put your code in a snippet. 

Wow!

**Comment by fabio323ti** [comment]
many thanks,  works with JetEngine too.

**Comment by JakJakson** [comment]
Thank you @neosaveme-zz  - epic! (JetEngine)
