### ISSUE TITLE
Cursor don´t change to hand when hovering over buttons

### ISSUE THREAD

**Issue by tscheipi** [pojome/elementor#3758]
Hovering over the button e.g. in a form the curser doesn´t change to  a hand. Maybe you could implement that in your styles?

**Comment by bainternet** [comment]
@tscheipi 

This should be done by browser defaults styles unless your theme overwrites it.

**Comment by HMSuperGeek** [comment]
You can leave the theme's CSS alone and add to elementor's Site Settings -> Custom CSS:

.elementor-button {
  cursor: pointer;
  }

NOTE: This will change it globally to all buttons attributable to elementor. This works perfectly if that is all you expect from your elementor buttons.

**Comment by kalpana-kale** [comment]
Add css in button selector. It will only change the cursor for specific button.

selector .elementor-button {
  cursor: pointer;
}
