### ISSUE TITLE
Exclude Roles: Works but the buttons still show in the builder Settings Panel, this is confusing

### ISSUE THREAD

**Issue by carasmo** [pojome/elementor#3760]
When I tick the box for Editor to use Elementor, the Default Fonts and Dashboard Settings buttons here in settings should also go away. This is confusing and it's better that they are not there since they will click it and see no access. 

<img width="296" alt="screen shot 2018-03-14 at 11 20 39 am" src="https://user-images.githubusercontent.com/1124594/37411713-d5094d1c-2779-11e8-9d90-983f3d92ea99.png">

**Comment by bainternet** [comment]
@carasmo 

When you are correct and its something we'll be updating.

**Comment by bainternet** [comment]
fixed, thanks.
