### ISSUE TITLE
Feature Request: Ability to 'unpublish' a section

### ISSUE THREAD

**Issue by ceap80** [pojome/elementor#3763]
I've searched the issues for this without any luck.

Is it posible to unpublish an elementor section?

I have sections that sometimes I don't want to appear in the front-end. I know that I can use the Hide On Desktop/Tablet/Mobile controls but this controls only set the css display attribute to none.

I could also save the section as a template and remove it from the page but this workflow is a little be longer and messy.

It would be better (at least for me) to have a way to unpublish a section so that all the info is in the backend but not displayed in the frontend

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you do have a way or two to deal with it like you stated above.

Thanks for the feedback.
