### ISSUE TITLE
Feature Request: Click counter button

### ISSUE THREAD

**Issue by Mokai-Momiji** [pojome/elementor#3766]
### What it is?
A simple button! When someone click on it, add +1 to a counter, and if re-cliked -1.

### What it need?
Similar customization features to the Elementor Share Buttons;
The ability to put any fontawesome icon;
A filter for multiple clicks (IP, cookie or other alternative)

### What is the usability?
- Create simple polls with: [:+1: / like button] and [:-1: / dislike button];
- Create a reaction area: [:thumbsup: - :heart_decoration: - :cherry_blossom: - :satisfied: - :open_mouth: - :cry: - :angry:];
- Create a [:heart: / love button] or [:star: / star button], very useful for post engagement;
- And much more, your creativity is the limit.

**Comment by ravilrrr** [comment]
Use plugin and shortcode ;)
https://wordpress.org/plugins/likebtn-like-button/

**Comment by bainternet** [comment]
@Mokai-Momiji 

@ravilrrr is correct, this should stay as a 3rd party plugin territory.
