### ISSUE TITLE
Scaling Images depending on their hight

### ISSUE THREAD

**Issue by musicjunk** [pojome/elementor#3774]
Hallo, if you put a 3 column section on the page and in each a image with the same height - then scale down each p.e. 30% each image has different height. Is there a way to set elementor to scale only dependent on the heigh?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

But, we print the images with `srcset` which "scales" the images responsively.
ref: https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/
Thanks for the feedback.
