### ISSUE TITLE
Remove Font Awesome dependency on Editor

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#3775]
Hi there,

I knew the Editor use some icons from Font Awesome 4.7.0 in its default UI. Is it better to remove Font Awesome as a dependency on Elementor Editor panel? You can use WordPress's Dashicons to substitute Font Awesome. Using Dashicons are way better as it's served natively by WordPress.

This would help developers who want to integrate Font Awesome 5 into Icon control options to avoid conflict with Font Awesome 4.7.0. Currently, when Font Awesome 5 is enqueued on Editor, it breaks some of UI icons on the Editor panel.

Regards

**Comment by bainternet** [comment]
We won't remove the dependency for Font Awesome but we do have plans to update to v5.

For now is you have conflicts try using their shim
https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by rocketfarmer** [comment]
Shims don't work as far as I can tell. It's been quite a while and I can't find a fix in your docs.

**Comment by Remzi1993** [comment]
Is there any work on this? Font Awesome 5 has been released a while ago and it's very stable thus far.

**Comment by clotted** [comment]
> Is there any work on this? Font Awesome 5 has been released a while ago and it's very stable thus far.

+1

**Comment by IDESIGNSTUDIO** [comment]
I am also very interested in the topic. The full Font Awesome is big file to load - it draws back the page speed, which is sooo important for the slower mobile connections. 

Elementor can evolve.

Suggestions

1.  Font Awesome disable/enable entirely.

2. Local font awesome file embed - where we generate our own font-awesome that includes just the icons we use on the website. Additionally we can use just the .woff and minify code as well.

3.  Better integration for using SVG, even SGV sprites (additional fields to give the positioning on the sprite) in Elementor

**Comment by enkia** [comment]
Elementor is also adding Font Awesome when it's already been added by another plugin.

**Comment by holle75** [comment]
+1

**Comment by black-eye** [comment]
+1 for better FA/icons handling, the best would be to enable/disable FA completely
FA5 (non)update is a long overdue

**Comment by b0br2019** [comment]
I also would like to see disable of fa option, if not already executed. There is a huge choice of icons and methods to use them. Perhaps an option to use other icons/methods would be great, I dont care so much in the backend, but the front end - when template loads fa, google fonts etc and then elementor does too it gets a bit much when trying to get rid of them!

I ended up going into elementor/includes/managers/icons.php and removing the array for fa-solid which was still left loading for me.
