### ISSUE TITLE
Improvement request

### ISSUE THREAD

**Issue by fingers-morris** [pojome/elementor#3778]
Hi
Given the non-standard way in which Elementor saves Templates, previously made template titles cannot (easily) be seen, when about to make a save.  Also, if an existing template name is re-used, there is no ask if the original template should be overwritten. Thus, for a newcomer to Elementor, this has led to a lot of templates with the same, or very similar names - and it has proved somewhat confusing  and time consuming to get the right template from the library when needed - as well as having to  view different ones in order to decide which ones can be trashed, or saved.
Therefore, I would ask if it would 
a) Be possible to have a more windows-like saving mechanism,where existing templates can be seen, along with the question whether or not to overwrite an existing name etc etc or 
B)  While I could envisage that A) above might involve quite a bit of coding to achieve, (and it seems you already have a lot going on in that area), would you please at least consider in a future release, to add a time-stamp next to the date-stamp on each template, so it would then be easy to differentiate between various versions of a template.  I suspect you could do this easily in very little time.

Apologies if this seems like an insignificant issue to you, but as a newcomer to Elementor, this little issue   has had a disproportionate impact on the learning curve for us - otherwise, overall, a fantastic plugin - and thanks for it!
Best regards
Julia C.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

We are thinking about adding categories/taxonomy to the templates, which is something you can already do today, using a relatively simple custom code, or even 3rd party plugins. 
Thanks for the feedback.
