### ISSUE TITLE
[Feature suggestion - Nice to have] Darken content on menu hover

### ISSUE THREAD

**Issue by Ver3** [pojome/elementor#3780]
Ability to activate an option to darken the content when you hover over a menu item (like a lightbox).

- **Reason:** Visitor will have increased focus / better for conversion.
- **Example (not a very good one though:** http://jsfiddle.net/49Qvm/28/
- **Urgency:** None, it's just a so-called "nice-to-have", not a "must-have".
- **Tried this, sadly did not work:**

```
#header:hover + #main {
opacity: 0.2;
transition: all .5s linear 0;
}
```

If this idea is too silly, feel free to close or delete the entry.

**Comment by bainternet** [comment]
@Ver3 

Not sure you can get that with CSS only (need some JS, like in the fiddle). anyway: 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Ver3** [comment]
It works without JS, when written like this:

```
#masthead:hover ~ #content {
opacity: 0.1;
transition: all 0.5s linear 0.1s;
}
```

See test site here: https://www.minddump.nl/shop/
