### ISSUE TITLE
How to change background section in edit page?

### ISSUE THREAD

**Issue by notrealdev** [pojome/elementor#3782]
Hi, i can not see background color of section when change it
Please check my video, is it feature?
http://recordit.co/Vr7BUqQCO9

**Comment by bainternet** [comment]
@notrealdev 

We can't replicate this issue. 

please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

**Comment by notrealdev** [comment]
Hi, i think this issue belongs to Elementor

Only Elementor
![plugin](https://i.imgur.com/A89l5ut.png)

Twenty Fourteen theme
![theme](https://i.imgur.com/d1H6Rj9.png)

Issue:
http://recordit.co/kilIsDeuD2

**Comment by bainternet** [comment]
@notrealdev 
We can't replicate the described issue,
Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by notrealdev** [comment]
Hi, a simple question, how to change background of section in editor? The problem is very simple, but it does not work with me 😄 😄 😄 😄 😄

**Comment by bainternet** [comment]
@notrealdev 

Again it's simple and works fine for us, for some reason it's not working for you, that's why I asked you to contact our support so they could investigate your issue better and help you out.

**Comment by notrealdev** [comment]
Yes, I tried on other browsers and it worked, sorry for the inconvenience
// Current browser: Chrome Version 66.0.3359.33 (Official Build) beta (64-bit)
