### ISSUE TITLE
Post Widget Improvement

### ISSUE THREAD

**Issue by MacaRr30** [pojome/elementor#3783]
Just an opinion...
The post widget needs to have more options, share button for social networks; "read more" as a button that can be customized, posibility of center the title without doing the same with the content, etc. 

I love elementor but this widget looks not so good...please!!!

**Comment by dudaster** [comment]
@MacaRr30 try this plugin for the time being: https://wordpress.org/plugins/ele-custom-skin/

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
