### ISSUE TITLE
Nofollow 

### ISSUE THREAD

**Issue by MacaRr30** [pojome/elementor#3784]
It would be great to have the choice to add the "nofollow" label easily with a click in the Text Widget, like it is done with the "open in a new window" label.

**Comment by bainternet** [comment]
You can install this plugin https://wordpress.org/plugins/nofollow/
and to get it to work inside elementor editor just add this line:

```PHP
add_action( 'elementor/editor/before_enqueue_scripts', 'nofollow_redo_wplink', 999 );

**Comment by leecollings-sb** [comment]
Why isn't this native though? It's a fundamental part of HTML markup today and is absolutely vital for basic SEO. Can this please be added as an option in the 'Insert Link' feature of the Text Editor widget?
