### ISSUE TITLE
Column improvement: option to set column width as fixed

### ISSUE THREAD

**Issue by Dhilofe** [pojome/elementor#3787]
Hello everyone,

I was wondering if you could add an option (e.g. a check box) to set as fixed and unchangeable the length (%) parameter (currently shown in the Layout menu) of a specific column in a page.

Consider this scenario: I have a section with two small columns on a side which I consider all set and ready with a ratio of 16.5% for both, and now I am working on the remaining space of the same section, which covers the major part of the page.
Whenever I try to test an idea which implies adding or removing a column to fill this part, the overall width is automatically redistributed among all columns. Hence, the two small columns are affected as well, which means that every time I try something new in the main part of the page I have to go back to them and set again the 16.5% width for both.

I know this is nothing serious, but in similar cases I think it would be easier if there was a way to set as "fixed" the ratio or the position (length-wise) of an individual column.

What do you think?
Thanks in any case for your attention and keep up with the good work.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, you can do that with custom CSS.


Thanks for the feedback.

**Comment by monaye** [comment]
FYI: This can be achieved by adding custom CSS for now. 

I think you can use the dynamic `selector` as well. I was lazy and just get current CSS from the inspector and overwrite it. 

`.elementor-8779 .elementor-element.elementor-element-8146843 {
    width: auto;
    flex-grow: 1;
}
.elementor-8779 .elementor-element.elementor-element-3e82b1a {
    width: 140px;
}
`

**Comment by Dhilofe** [comment]
Ah, I will give it a try asap, then. Thanks a lot for your time! :)

Il gio 28 feb 2019, 19:05 Monaye Win <notifications@github.com> ha scritto:

**Comment by gTaylorRokk** [comment]
@bainternet Are there any udpates or feature enhancements coming to grids we should be aware of? Having built quite a few sites with Elementor now, I can agree with OP that the redistribution of columns is currently quite frustrating when trying out layout ideas so I too would vote to have this improved. Also I'm often findinfg scenarios where it would be really useful to be able to fix a column to a specific size or ratio too where I want maybe inner an column with content to scale but have have an outer column fixed for something like a sticky sidebar or table of contents.
