### ISSUE TITLE
Feature suggestion: Goodreads/Amazon customer reviews widget

### ISSUE THREAD

**Issue by Dhilofe** [pojome/elementor#3788]
Hello everybody,

I have not found anything similar in this forum, so here is my suggestion for a new Elementor Pro widget. In my case, the focus is on books (as a product to promote) and author websites, but I guess this could work for any kind of product, once designed.

The idea is simple: in my website I have a page dedicated to a book I authored, and in addition to its description and quotes from press reviews, I would like to add a feedback from actual readers as well, taken from its related product ID page in Goodreads and/or Amazon. Please note that this is not a commercial page where I sell the book myself, it is just to showcase the product.

The **classic 5-star meter (plus the number of reviews the rating is based on)** would be a great start, but it would be nice to also show a glimpse (at least part and/or some) of the actual user reviews directly on my page.

Book author websites are generally not particularly complex or sophisticated, in terms of structure and design, but I think a widget for reviews coming from one or two of the major platforms for books would make a great addition to the Elementor Pro widget library for this specific category of sites.

Thanks in any case for your attention.
Best regards and keep up with the good work!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
