### ISSUE TITLE
Making a global editable template

### ISSUE THREAD

**Issue by Eichlig** [pojome/elementor#3789]
#Hello, buddies!

So I'm finishing a staff page, and problem is that we have over a 100 people.
https://s17.postimg.org/j5k7kbwtr/Template.png

All I'm doing is duplicating the section (row) and editing the information, but I started to think:  what if we ever want to change this design?

We would have to edit dozens of columns, one by one! (Or we would simply give up.)
How can it global so, after I change one of the rows/sections' design, all the others will change with it?

**Comment by bainternet** [comment]
@Eichlig 

We do have plans to implement "Copy styles" and "presets" which would help you in that case, but the best solution here would be to create your own widget and use it. This way you control the style from the up most level of the widget.
