### ISSUE TITLE
Automatically created templates

### ISSUE THREAD

**Issue by shimsa** [pojome/elementor#3790]
Hello,

Elementor in my WordPress does not start and I can not figure out why. Unfortunately, I did not save my work for a long time as a template, and now I do not know how to get the created pages into another WordPress installation. Please, give me an advice.

However, I think it would be useful for Elementor to automatically export this last state as a template every time it was saved.

What do you think?

Thank you.

Tom

**Comment by bainternet** [comment]
@shimsa 

Elementor doesn't create automatic templates, it utilizes autosave so check your database for revisions.
