### ISSUE TITLE
How to clear old errors from System Info report

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#3798]
I have tons of errors from 2017 still showing, how do I clear these.  Are they stored in the database somewhere?

Checking debug.log and error_log.log both are blank.  Is there a db table I need to purge?

**Comment by bainternet** [comment]
@pingram3541 

Sadly there is no way, other than deleting the row from the database, but, You can't have a ton, you could have 10 at most, it only stores the last 10.

**Comment by pingram3541** [comment]
Thx and correct they were just really long outputs...deleted =)
