### ISSUE TITLE
Feature Request: Better widget selector

### ISSUE THREAD

**Issue by ChristianWH** [pojome/elementor#3805]
As the number of Elementor widgets get bigger and bigger, a redesign of the widget selector area (the left pane) could be helpful. I am used to desktop development (Visual Studio, Delphi) where you are also dealing with a big number of components and would like to suggest the following:  

In order to have a better overview...

- Make the images smaller

- Have the search/filter bar sticky on the top of the window

- Group the components/widgets into logical groups

- Make these groups expandable/collapsable

- Let the user group his favorite components into user defined groups or make a "Last-used group"    

E.g. on the desktop from within the Delphi environment [https://prnt.sc/it653v](url)

Christian

**Comment by bainternet** [comment]
@ChristianWH 

We do have plans, do update the panel in one way or another, but I don't see it happening anytime soon.

thanks for the suggestions.

**Comment by norewp** [comment]
A feature will be added to Granular Control to streamline the panel be it a limited implementation till core has been updated with better handling - will release the enhancement soon after v2 has landed :)
