### ISSUE TITLE
Elementor tools, Google Analytics | request/enhancement 

### ISSUE THREAD

**Issue by benedettogit** [pojome/elementor#3816]
In Elementor tools, why not add the option to put the Google Analytics code:
Allowed formats: UA-XXXXXXXX, UA-XXXXXXXX-XXXX. Eg: UA-12345678-1 is valid
So no need to add a plugin just for that.

**Comment by bainternet** [comment]
@benedettogit 

We feel its a more of a 3rd party plugin/ custom code territory.

It makes no sense to enter Analytics code in each and every page you build with elementor when you can enter it from one place to the entire site. 

And you don't really need a plugin for that :
```PHP
add_action( 'wp_head', function(){
?>
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXX-Y', 'auto');  // Replace with your property ID.
ga('send', 'pageview');

</script>
<!-- End Google Analytics -->
<?php
});

**Comment by benedettogit** [comment]
ok, i thought it could have been put in the same place as we put reCaptcha settings.

**Comment by kcrabbster** [comment]
I feel this should be an Elementor settings thing. I was very very unpleasantly surprised that the GA code that I had added to my global site files was stripped out in Elementor pages. This is a huge issue that shouldn't be buried by having to figure it out after the page you've been promoting has been out there for a week with no tracking. :/
