### ISSUE TITLE
Feature request: Multi-language support for forms / mailchimp integration

### ISSUE THREAD

**Issue by kosmik78** [pojome/elementor#3817]
I would like to add easy multi-language support for email sign-up forms to Elementor Pro. I am using an Elementor Form with Mailchimp action after submit. The site uses WPML to create several language versions.
I can translate the form description and the button labels without issues, but I can not change the mailchimp list based on language and I also did not find any other way (e.g. hidden field) to submit the language information with a translatable field.
Work-around: After WPML created the translated page, I can go in and manually change the mailchimp list or hidden attibutes, but this breaks all future WPML translation and I have two maintain each language version seperately

Feature request:
Make all relevant elements transatable (e.g. hidden field would also allow me to have the actual value submitted as a translatable string) or add an option to select the mailchimp list that is used based on site language

Thanks

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Currently, you can create a separate form per language.
Thanks for the feedback.
