### ISSUE TITLE
Elementor Pro form widget is not working using elementor button widget with modal

### ISSUE THREAD

**Issue by aleksander-lurie** [pojome/elementor#3818]
If you try to use elementor pro form widget together with elementor button (using modal and some form as template), you always get `INVALID_FORM` error.

Probably it's because of modal is not attached to the page immediately, but after clicking on button.

Please look at `ajax-handler.php:67`

![zrzut ekranu 2018-03-20 o 10 32 47](https://user-images.githubusercontent.com/32944443/37646474-1594bd62-2c2a-11e8-9139-751cdc2c995c.png)

`$form` variable will be always `false` because of missing form inside `$meta` array

**Comment by bainternet** [comment]
If the form is not attached to a page/post, it will not work.

To overcome this issue you can simply add the form to that page as hidden.

Other then that I it really depends on how the Modal work, so I would need to get more data from you.

**Comment by aleksander-lurie** [comment]
I have my own plugin which let me attach my own widgets to the elementor. My workaround for this moment is my own Modal widget.

Of course its not a solution because most of the user will be surprised the regular modal using button widget is not working correctly with the elementor form widget ;)

**Comment by bainternet** [comment]
Then In your widget, once the form is rendered, make sure that the template ID is the global `$post`, so `get_the_ID` will work correctly.

again if will see the code will probably be able to help.

**Comment by aleksander-lurie** [comment]
all code is here ;)

it's a bug of elementor/elementor pro, i have no issue with my own implementation :D

**Comment by bainternet** [comment]
@aleksander-lurie 

Elementor has no modal!!!

You are obviously using either a 3rd party plugin or custom code.

hance, not an Elementor bug, now I am trying to help you but the modal code is the missing part...

**Comment by aleksander-lurie** [comment]
It means there is possibility to change the controls of the elementor widgets via other plugin?
I though it's build-in feature in elementor button widget

![zrzut ekranu 2018-03-20 o 15 49 51](https://user-images.githubusercontent.com/32944443/37662456-5e1fb69a-2c57-11e8-885c-f95219d9ce9e.png)
