### ISSUE TITLE
A few observations

### ISSUE THREAD

**Issue by Brink67** [pojome/elementor#3827]
Pro Beta1

Very nice work folks. Looks like a lot of thought and effort went into this. Header Footer support has been needed for a while now. I have pursued several options to remedy and all have met with varying degrees of disappointment.  Given what I have seen so far with Pro Beta 1, I feel that it will be a pleasure to design with Elementor.

1) I have found no way to set what you term "Display Condition" other than on first save (Publish) after creating. My work around for this so far has been to export it, then trash it, then re-import it, then edit with Elementor and publish it again. At that point, the option to set display condition reappears and you can set a condition for display. There needs to be a better way to change the display condition for a header/footer. If one exists that I have missed, please let us know where to find it.

2) When using Pro Beta 1 with Generate Press theme Version: 2.0.2 and it's pro plugin 1.5.6: Elementor Header does not obey containment properties set in: Dashboard>Appearance>Customize>Layout>Header. No matter the setting, Elementor Header is not contained and occupies the entire width of the background. Additionally, Section properties of the  "Section" when editing the header with Elementor Editor does not contain it either. (Footer does not have this problem and behaves as expected)

3) Dynamic Content of a heading widget can be set to "Current Date Time" and has a settable property called "After". The "After" field seems to accept html (whether by design or accident). If you enter something like: "Some text in the after field.^br^Some more text that should appear on line two and does. ^a href="http://examplelink"^This link jumps back up to line one^/a^" The link jumps back up to line one. (tag opening and closing <> have been substituted with ^^ in the example) If html is supposed to be allowed here and simple tags like ^br^ and ^a^ would work as expected it would be quite useful in the footer.

Thanks for all your efforts.

**Comment by agusmu** [comment]
1) click "Update" button on bottom left, and you will see "Display Condition" menu there. 

<img width="373" alt="elementor-pro-beta1-display-condition" src="https://user-images.githubusercontent.com/1005437/37692770-709f3ef8-2ced-11e8-9ed0-7df088c6e702.png">

**Comment by Brink67** [comment]
Thank you for that.

**Comment by bainternet** [comment]
@Brink67 

thanks for reporting, please keep it up in the [Pro beta Thread](#3826), no need to re-post
