### ISSUE TITLE
Bug in FlipBox widget

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#3828]
When using rounded corners, it is only applied to the background (only visible in 3D). It should be applied to the frame (foreground and background) itself as well.

**Comment by bainternet** [comment]
@HelmutGoebel 

Use the border-radius control in the content tab>> settings section

![screen shot 2018-03-21 at 17 21 06](https://user-images.githubusercontent.com/660572/37718825-48c8a204-2d2c-11e8-97d4-558e51d3ffdc.png)

**Comment by HelmutGoebel** [comment]
Uuups. Didn't expect it there.
