### ISSUE TITLE
Shape Divider between two images or gradients.

### ISSUE THREAD

**Issue by jcmatoskx** [pojome/elementor#3829]
It would be great if we could create a shape divider between two backgrounds with images or gradients.
It seems shape dividers are only possible if one of the sections is a solid color, but it would be nice if we could select to continue the gradient from the other section, or the image.

**Comment by bainternet** [comment]
@jcmatoskx 

Can you provide an example to what you mean?

**Comment by jcmatoskx** [comment]
I have an image from my website, it's not a great example because the gradient is very subtle and the image is a dark texture,  but essentially the issue is that if the two sections are either a gradient or image, there is no way to blend their transition with a shape divider between them as the shape divider input is always a solid color. Or is there something I didn't understand?
![shapedividwe](https://user-images.githubusercontent.com/37616081/37879117-3a5bb9e4-306b-11e8-9889-23b95ef96eeb.png)

**Comment by BrookeRaraAvis** [comment]
The shape divider being a solid color is also a problem for me. I want to push the image in the second section to show in the shape divider above, and it isn't possible because the shape divider is solid. The shape divider looks silly when images are juxtaposed. Wish it could be transparent & somehow punch a shape hole through the section on which it is applied & then I could negative margin-top the section below.

![capture](https://user-images.githubusercontent.com/1435355/37980045-1d62d144-31b8-11e8-8d4b-afc8adb08f77.PNG)

**Comment by jcmatoskx** [comment]
Yup that is exactly the issue I am talking about

**Comment by bainternet** [comment]
thanks for the clarification,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by bigwilliam** [comment]
+1 for this feature!

**Comment by stijnvanouplines** [comment]
+1

**Comment by yeshansachithak** [comment]
+1
Having the same issue.

**Comment by toniodz** [comment]
+1

**Comment by nicolasteetz** [comment]
+1

**Comment by theol0403** [comment]
+1

**Comment by netbloger** [comment]
+1 for this feature also!!

**Comment by clondon** [comment]
+1

**Comment by nboaldin** [comment]
+1

**Comment by robertopib** [comment]
+1 Here, I ended up leaving a solid color in between, but it would be nice to have the two images blend.
<img width="1440" alt="screen shot 2019-02-07 at 7 35 18 pm" src="https://user-images.githubusercontent.com/18031866/52434471-b0aad400-2b0f-11e9-8048-94c791d1e5ca.png">

**Comment by clondon** [comment]
Hi,
I have been using a workaround that might help.
You set a higher z-index on the following section and then using a negative margin to move the section up until the white area is covered. 
![screenshot 2019-02-07 21 48 17](https://user-images.githubusercontent.com/887197/52445334-b78f1200-2b22-11e9-9b5d-3c40bad674a0.jpg)
  have used this on my website and the effect is quite nice.
I hope this helps.

**Comment by robertopib** [comment]
Thanks @clondon  The problem is when you have tow sections with image background. Your workaround works when you have a section  with a BG image and then a solid color, actually you don't even need to set any z-index, just change the color of the shape divider to match the color of following section.

**Comment by Aroundme12** [comment]
Saw this done on a homepage looking to pull this off anyone have an idea. 
https://dartingbasketball.com/

Thanks

**Comment by Aroundme12** [comment]
> 
> 
> Thanks @clondon The problem is when you have tow sections with image background. Your workaround works when you have a section with a BG image and then a solid color, actually you don't even need to set any z-index, just change the color of the shape divider to match the color of following section.

Correct!

**Comment by robertopib** [comment]
> Saw this done on a homepage looking to pull this off anyone have an idea.
> https://dartingbasketball.com/
> 
> Thanks

That's exactly what we need to accomplish! Nice example!

**Comment by Aroundme12** [comment]
Working on it now i'll see if I can get it. Been at for 4 hours already.

**Comment by robertopib** [comment]
Me too, did you try the `clip-path: polygon`?

**Comment by Aroundme12** [comment]
I'm okay with code not that great self taught.

**Comment by Aroundme12** [comment]
trying it now

**Comment by robertopib** [comment]
I think I have it figured out, I inspected the example you post, and I think I have it, just a minute and I'll let you know what I did.

**Comment by Aroundme12** [comment]
okay cool. i tried pulling everything apart and adding that snippet of code to the css but to no avail.

**Comment by robertopib** [comment]
So I basically created 3 classes `top-tilt, bottom-tilt, top-bottom-tilt`  and added the css as following `.top-tilt{
    clip-path: polygon(0 0, 100% 10%, 100% 100%, 0 100%);
}

.bottom-tilt{
	clip-path: polygon(0 0, 100% 0, 100% 100%, 0 90%);
}

.top-bottom-tilt{
	clip-path: polygon(0 0, 100% 10%, 100% 100%, 0 90%);
}` 
and assigned them to my elementor widgets depending on what I need and adjusting top and bottom margins for the sections to overlap.

**Comment by robertopib** [comment]
A problem with this workaround is that if you need to select a section with the top-tilt class, you would need to use the elementor navigator, because the clip-path will hide the selector.

**Comment by Aroundme12** [comment]
Did you add the snippet to the css. or do I need to add it as a class

**Comment by Aroundme12** [comment]
can you post a screenshot

**Comment by Aroundme12** [comment]
got it nevermind

**Comment by Aroundme12** [comment]
Impressive

**Comment by robertopib** [comment]
I think I will just go with the  
```
.top-tilt{
    clip-path: polygon(0 0, 100% 45px, 100% 100%, 0 100%);
}
```
And I replaced the 10%  with 45px. I have a lot of tilted sections, and the percentages will give me different angles depending on the section height.

**Comment by Aroundme12** [comment]
I'm going to roll with the bottom tilt. I'll try and play around with this for a bit.

**Comment by newflavour** [comment]
+1 for this feature

**Comment by newflavour** [comment]
as a workaround, for now, I've been finding a colour that closely matches the image.
the upper section has the shape divider in that colour
the lower section has a background gradient overlay to help blend it together

it would be amazing if there was an option for 'clip path'

![elementor-workaround](https://user-images.githubusercontent.com/4841348/53083645-0ee1a900-354b-11e9-8e99-077fdd3935a9.PNG)

**Comment by ccBaileyRob** [comment]
Would also really love this feature. Seems like an oversight seeing as a lot of the other 'style' elements can feature a gradient...

**Comment by mfainshtein4** [comment]
If you are trying to achieve this using clip-path as @robertopib suggested. Id recommend checking out: https://bennettfeely.com/clippy/

**Comment by Waleedviews** [comment]
+1

**Comment by ArekZw** [comment]
+1

**Comment by emailjough** [comment]
+1

**Comment by tracyleigh54** [comment]
+1 for this!!

**Comment by m0lt** [comment]
+1

**Comment by FrankLauda** [comment]
+1

**Comment by FrankLauda** [comment]
I worked this out with a simple bit of CSS code elaborating on @robertopib and @mfainshtein4 comments. So yes you just need to add clipping path code. In my case, I wanted to create a triangle at the bottom of my top main image.

To create the clipping shape I wanted I went to 
https://bennettfeely.com/clippy/ 
and selected the hexagon shape. This is the bit of code:

clip-path: polygon(50% 0%, 100% 0, 100% 90%, 50% 100%, 0 89%, 0 0);

Now I apply this the main section with my background image in Advanced > Custom CSS. Then apply the code to the ID of the section. You can find the ID  using your browser developer tool. So now mine was

.elementor-element-cd60891 {
    clip-path: polygon(50% 0%, 100% 0, 100% 90%, 50% 100%, 0 89%, 0 0);
}

Lastly, because the main image is underneath the second section (with background image), you just need to add a z-index to bring the top section to the front. So complete code:

.elementor-element-cd60891 {
    z-index: 1;
    clip-path: polygon(50% 0%, 100% 0, 100% 90%, 50% 100%, 0 89%, 0 0);
}

You could also apply the clipping path in reverse for the second section, then you won't need to add z-index. Hope this helps.

**Comment by bentalgad** [comment]
+1 so basic. it's just amazing they don't do those stuff.

**Comment by DaninDC** [comment]
+1 It would make life so much easier if the default of the shape is transparent. Come on Elementor!

**Comment by vind** [comment]
+1 Why has this even been neglected for so long!

**Comment by FrankLauda** [comment]
Feedback from users is perfect testing for Elementor to implement changes.
I think Elementor is good for adapting to change pretty quickly. I would
personally love it when page transitions is implemented within Elementor.

**Comment by neylwalecki** [comment]
+1

**Comment by JCD666** [comment]
+1

**Comment by abescom** [comment]
Same issue ! +1 ;-)
![screenshot-5mm3gj3b-abesfr pf6 wpserveur net-2020 01 20-16_38_53](https://user-images.githubusercontent.com/60105919/72739218-84168d80-3ba3-11ea-8a59-5de388ec083f.png)

**Comment by ethandmiller** [comment]
> It would be great if we could create a shape divider between two backgrounds with images or gradients.
> It seems shape dividers are only possible if one of the sections is a solid color, but it would be nice if we could select to continue the gradient from the other section, or the image.



> thanks for the clarification,
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> Thanks for the feedback.

+1 for this feature

**Comment by CharfishCharlie** [comment]
+1 Let's see this happen!

**Comment by dietcheese** [comment]
+2

**Comment by emailjough** [comment]
Worked out a simple solution here. No need for clip path. If you skew a background overlay and give its section negative margin top+bottom you can have adjacent angled sections with bg images. Scales well on mobile too. One line of css. The rest is all elementor. 

https://bit.ly/2wOA0lH

On my demo page you may see a part of the lower section on scroll but thats only because I set the bg image to position:fixed b/c I liked the effect. 

![screenshot-joehonzik com-2020 03 30-22_19_08](https://user-images.githubusercontent.com/28794235/77990139-72551300-72d5-11ea-9cf3-a2630e012d82.jpg)

**Comment by oooh-boi** [comment]
No need for shape dividers at all! You need a mask and a negative margin on columns/sections. I've made an add-on that can be used to mask Image widget and Background Overlays of either a column or the section. http://elementor.wpshow.me/ooohboi/ooohboi-image-mask/

**Comment by dietcheese** [comment]
> No need for shape dividers at all! You need a mask and a negative margin on columns/sections. I've made an add-on that can be used to mask Image widget and Background Overlays of either a column or the section. http://elementor.wpshow.me/ooohboi/ooohboi-image-mask/

You’ve got some great add-ons here.  Should package them and I’d buy em all.

**Comment by hungryjos** [comment]
> No need for shape dividers at all! You need a mask and a negative margin on columns/sections. I've made an add-on that can be used to mask Image widget and Background Overlays of either a column or the section. http://elementor.wpshow.me/ooohboi/ooohboi-image-mask/

@oooh-boi , once again you rescued me. As @dietcheese says: a package with all elements would be great, but I bought them all for now. Thanks!

**Comment by bentalgad** [comment]
> No need for shape dividers at all!

You right, let's add another plugin to the long list of plugins you have to load beside the Elementor plugin which adds enormous amount of DOM elements and scripts any ways and makes sites load amazingly slow. i guess that's the reason even Elementor didn't use Elementor for there new "experts" site (they used it only for header and footer so it won't be too ridiculous that they didn't use it at all :)

**Comment by oooh-boi** [comment]
> You right, let's add another plugin to the long list of plugins you have to load beside the Elementor

Is there any other way of extending Elementor but to create a WordPress plugin?

**Comment by bentalgad** [comment]
To let Elementor add this basic stuff. and not write "there no need for
that..." on the future request pull.

‫בתאריך שבת, 4 באפר׳ 2020 ב-10:53 מאת ‪Oooh Boi‬‏ <‪notifications@github.com
‬‏>:‬

**Comment by oooh-boi** [comment]
> To let Elementor add this basic stuff.

Are you being serious?!? I might get old or die before that happens. Elementor development team is not a jukebox, you can't make a wish, get the dollar and make them play for you... besides, they have made an awesome API, why not using it? Because you gonna have to install another plugin, right? Well, imagine the world without WordPress plugins or Elementor add-ons. They just wouldn't exist.

**Comment by nadworks** [comment]
+1
Geezuz, this should have been fixed from the stat, such an obvious oversight. I ran into the issue 10 mins after first using Elementor. C'mon, please.

**Comment by omartheman** [comment]
Might be easier to add a clip-path in CSS. Then you don't need to change all the colors if the background color changes.

**Comment by joexcm** [comment]
+1 for the feature please

**Comment by 5jv** [comment]
Has anyone found a solution?

**Comment by emailjough** [comment]
> Has anyone found a solution?

Yes. I posted a simple, responsive solution a year ago here (see above) that doesn't require adding another plugin or using a clip path or mask. I provided the simple css, a screenshot and link to the demo, but for some reason its been completely ignored. Is there something wrong with it? I'm just curious.

**Comment by 5jv** [comment]
> > Has anyone found a solution?
> 
> Yes. I posted a simple, responsive solution a year ago here (see above) that doesn't require adding another plugin or using a clip path or mask. I provided the simple css, a screenshot and link to the demo, but for some reason its been completely ignored. Is there something wrong with it? I'm just curious.

I tried your solution but here is for example what I am trying to do and I cannot come up with this solution
![test](https://user-images.githubusercontent.com/53080063/115999566-9c6a2900-a5ec-11eb-9666-9f4d86a257f5.jpg)

**Comment by 5jv** [comment]
The other problem with your solution is that this also skews the background image, ideally the background image should stay perfectly straight in the block, it should not be tilted with it.

**Comment by emailjough** [comment]
> The other problem with your solution is that this also skews the background image, ideally the background image should stay perfectly straight in the block, it should not be tilted with it.

Gotcha. Thanks for pointing that out. I  agree that is a flaw in my solution I hadn't noticed before.

**Comment by thorsolutions** [comment]
+1

**Comment by fxaviers** [comment]
+1

**Comment by mjflower** [comment]
+1 please elementor team

**Comment by kitsunecreativeco** [comment]
another +1

**Comment by zierbeek** [comment]
another ++

If anyone has a solution to fix this, thanks! 

![Schermafbeelding 2022-01-11 om 08 59 11](https://user-images.githubusercontent.com/58994651/148903239-01bdcc9e-8611-4a02-8744-7c8e35df95ca.png)

**Comment by Johnvrkmp** [comment]
another +1

**Comment by OnlinePirateDogFromSpaceAndBeyond2020** [comment]
+1

**Comment by SolunaCG** [comment]
+1

**Comment by khahina** [comment]
+1

**Comment by zzella** [comment]
+1

**Comment by davidamarek** [comment]
+1

**Comment by NibeluR** [comment]
6 years later and this crap still hasn't been implemented. GJ Elementor 👍

**Comment by mjflower** [comment]
yep, clearly zero 'somethings' given on this issue by them
