### ISSUE TITLE
Animated Headline Speed 

### ISSUE THREAD

**Issue by jcmatoskx** [pojome/elementor#3830]
It's been bugging me a little bit that we can't control the Speed of the transitions in the Animated Headline.
It's such a great feature but frustrating because I'm switching between a lot of different short words that are read in a fraction of a second and I would like the transition to be faster. 

I imagined other people would have the same issue but I only managed to find people talking about the same issue in the FB community (and there were no answers/solutions :( )

Isn't there any CSS code that can be used at the moment to control this?

Thank you very much in advance for the attention and advice. Much love!

**Comment by vasjanovak** [comment]
+1

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Sil-Utrecht** [comment]
Yes, I would love to be able to adjust the speed,

**Comment by heyfletch** [comment]
This issue is open over here: https://github.com/elementor/elementor/issues/4392

**Comment by pebblesque** [comment]
+1

**Comment by fragdieb** [comment]
+1
