### ISSUE TITLE
[Feature requests]: Show Social media links  in the author profile box

### ISSUE THREAD

**Issue by ZedProg** [pojome/elementor#3832]
Could you please add "social media" "website" links of the user, along with the other info in the author profile box?This seems to be missing in the current release.

**Comment by bainternet** [comment]
We are thinking about it, maybe pull form Yoast SEO but still not sure.

Thanks for the suggesiton.

**Comment by ZedProg** [comment]
Thanks for looking into it.
I believe, we can fetch this info from the "author profile"(profile.php). Since its already available there.
![github-author](https://user-images.githubusercontent.com/9676190/37783964-c6d6fa88-2e1c-11e8-8788-f9b860883b42.png)

**Comment by bainternet** [comment]
@ZedProg 

Wrong, its not native to WordPress, Its via a plugin.

**Comment by ZedProg** [comment]
@bainternet 

When I login to  WP-Dashboard and go to Users-> Your Profile, I do see the screen, which I added previously.

Which have options to add, your website info, social media profiles, short bio e.t.c

I don't understand, how you are saying this is not native.

**Comment by bainternet** [comment]
@ZedProg 

this are the native fields:
![screen shot 2018-04-30 at 12 36 40](https://user-images.githubusercontent.com/660572/39421774-387e728c-4c73-11e8-8a8c-20d37b696be4.png)


anything else is there via a plugin.

thanks

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by RadoFafo** [comment]
I would really appreciate this feature too. We have multiple authors and it would be a great way to promote them in the evergrowing digital world... Thanks!

**Comment by NStorm1984** [comment]
I would like to have this also for my Elementor Pro. I have tried a lot of plugins, but they all don't work with Elementor to have the social icons in the author box too. I even tried putting html in the biography... too bad that did not work either :p so all hope is gone now. I wanted to edit the plugin but that is out of my reach, I can't code... only what i find on the internet and put that in place on my own files... but well, for the author box i did not find anything. So would be great if you guys can put social icons (with custom styling like the Social Icons) in the author box... or... maybe built in the social icons widget that you can pull the information from the profile pages... Even better, because than you can style your on box completely :)

**Comment by bluantinoo** [comment]
+1

would not be possibile to pull just author metas from icon widget?

**Comment by JohnPixle** [comment]
This is definitely needed, +1

**Comment by eeprom-one** [comment]
total needed +1

**Comment by altuno** [comment]
Yes that'd be great.

**Comment by arjun1259** [comment]
Please add this feature it is a necessary feature to many users.

**Comment by jrothra** [comment]
Me, too.  I would love this feature!

**Comment by mfrapp20** [comment]
@bainternet this feature is definitely needed. Even if the profile.php social info is not native, I think the Elementor team could easily add additional options to the author box element to add a social icon and assign a link to it. Based on how other elements function, I think this should be possible and easy to implement.

**Comment by mfrapp20** [comment]
The links would need to be dynamic for it to work, but I think it should be possible.

**Comment by beingskyler** [comment]
We'd like this feature as well.

**Comment by andre2go** [comment]
I found a nice playaround solution for this issue. 

Lets say you have multiple authors on your website publishing stuff. Each author has fix social media links. 

You create a global Elementor widget with the social icons for each author. I used the widget "Social Icons", then defined the social media links and saved each widget as global widget with the name of the respective author.

Each global widget has a shortcode you can use across your website.

The Elementor widget "Author Box" offers the possibility to add the Biography of the respective author.

So the issue would be fixed if you could use shortcodes in the "Biographical Info" section on the profile page of each author, which is not possible by default.

With a little PHP-snippet added to your child themes functions.php you can give permission to the usage of shortcodes in that section. The PHP-snippet looks like that: add_filter( 'get_the_author_description', 'do_shortcode');

Thats it - now you can add the shortcode of you global Elementor widget to the "Biographical Info" section on the profile page of each author which will then be fetched by Elementors "Author Box" widget.

**Comment by frydhogg** [comment]
+1 for this, really needed

**Comment by zcraber** [comment]
+1 for this feature

**Comment by foxtucker** [comment]
+48 - That's how many authors I have on my sites. This is one of those things that doesn't get much attention because it's a single website designer asking for it, but affects many authors per site. Shame

**Comment by xbor17** [comment]
![Screenshot_1](https://github.com/elementor/elementor/assets/79457183/f2ffcf98-322d-4b80-a630-d2d7980a2db7)
I managed to get Elementor to show me the author meta, but not to create links using fields (which was my first idea).
I used the Icon List widget from Elementor, and on the text you have to choose Author Meta writing the name of each of those meta fields. See second snapshot for reference for the case of LinkedIN. 
![Screenshot_2](https://github.com/elementor/elementor/assets/79457183/c26d7a3e-2811-4260-91cc-e8345767558a)
You can find the name of each meta field using "Inspect" on each field in the user's profile inside WP dashboard. 
I hope this is useful for someone else. 
Elementor should be able to use as URL field the Author's meta (is already able to detect is and show it as text, so the functionality is 50% done).

**Comment by wordpressvn** [comment]
🔹 Step 1: Create Author Fields with ACF

Go to ACF → Add Field Group.

Add two fields (Field Type = URL):

facebook_url

linkedin_url

Location rule: User Form → All Users (so fields appear in User Profile).

Save.

Now, when editing a user in WordPress → you’ll see Facebook URL & LinkedIn URL fields under the profile.

🔹 Step 2: Append Social Icons below Bio

Add this to your theme’s functions.php (or a small plugin):

```
// Append ACF social icons below author bio in Elementor Author Box
function cop_append_social_icons_to_bio($description) {
    $author_id = get_the_author_meta('ID');

    // Get ACF fields for user
    $facebook = get_field('facebook_url', 'user_' . $author_id);
    $linkedin = get_field('linkedin_url', 'user_' . $author_id);

    if (empty($facebook) && empty($linkedin)) {
        return $description; // nothing to show
    }

    // Build icons
    $icons  = '<ul class="elementor-icon-list-items elementor-inline-items" style="margin-top:10px;">';
    if ($facebook) {
        $icons .= '<li class="elementor-icon-list-item elementor-inline-item">
            <a href="' . esc_url($facebook) . '" target="_blank" rel="noopener">
                <span class="elementor-icon-list-icon"><i class="fab fa-facebook-square"></i></span>
            </a>
        </li>';
    }
    if ($linkedin) {
        $icons .= '<li class="elementor-icon-list-item elementor-inline-item">
            <a href="' . esc_url($linkedin) . '" target="_blank" rel="noopener">
                <span class="elementor-icon-list-icon"><i class="fab fa-linkedin"></i></span>
            </a>
        </li>';
    }
    $icons .= '</ul>';

    return $description . $icons;
}
add_filter('get_the_author_description', 'cop_append_social_icons_to_bio');
```

🔹 Step 3: Use Elementor Author Box

In Elementor, drag Author Box widget.

Elementor will output the Bio.

Our filter automatically appends Facebook + LinkedIn icons below the Bio.

✅ Done! Now author social links are managed with ACF, and Elementor Author Box always shows them below the bio — no shortcode needed.
