### ISSUE TITLE
Is there anyway to limit of amount repeat control?

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#3833]
We are building a repeat widget.

Is there any way to limit repeat amount?

Let's say, we just want to you to be able to add only Max 4 repeats. Not more. then hide "+ADD ITEM"

Or is there anyway to hide "+ ADD ITEM" button?

https://s18.postimg.org/csn065vvt/screenshot_763.png

Thank you!

**Comment by bainternet** [comment]
There is no way to define max items, Yet
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


Thanks for the feedback.
