### ISSUE TITLE
Breaking problem if outside the loop

### ISSUE THREAD

**Issue by jpSimkins** [pojome/elementor#3835]
I have been testing this plugin out as a replacement for VC. So far, I like what I see and it's very powerful. One issue I have noticed, and it's a deal breaker for me, is that this depends on the global `$post` object. The problem with this is that it assumes you are in **the loop** which is a bad assumption. 

A simple test: On a vanilla WP install, create a few blog posts then create a `front-page.php` file and fetch your own content (use a CPT and do not use the loop) then output your data (using `the_*`). That is where this plugin fails drastically. All content will be the first post in the blog roll and not the custom query below. Now you can fix this by assigning a specific page to be the blogroll but then you are missing the point of the test (that it's using the global `$post` object to build it's content). The issue is that this appears to be using `get_the_ID()` which assumes a global `$post` object. VC handles this logic by identifying if it's in a loop or not. I see that being very valuable in this plugin as it's very limiting on what can be done otherwise.

My testing shows that:

- This plugin depends on using the loop
- This plugin depends on the global `$post` object

Due to these 2 very strict limitations, I find this to be a major issue with this plugin that I hope is resolved in future updates. I could get into how and why the plugin should allow for functionality outside the loop and avoiding the `$post` but that is outside to focus of the issues reported here and these are already reported in the bug tracker and numerous blogs already.

**Comment by bainternet** [comment]
@jpSimkins 

thanks for the feedback.
