### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by krann** [pojome/elementor#3838]
It would be great if the textbox widget had a checkbox which, when checked, took the 'Featured Image' and plonked it nicely into the text area so that the text wrapped around it. It would be like magic!
I like to 'justify-right' images. That way the text flows around it well and I like images to be about 50% of the width of the main text block. Those could be the Factory Settings.
--

**Comment by drank** [comment]
@krann 

Would you please rename the subject to something more descriptive? "Feature request" does not help - neither the Elementor devs, nor the community. Example, "[Feature request] Automatic featured image placement for the Textbox Widget".

On the topic: what's wrong with inserting the image in the textbox using the "Add Media" button above the text area?
On the other hand, this might already be part of the Dynamic Content feature in the new 2.0 Pro version - why don't you check the beta?

Regards

**Comment by krann** [comment]
Yes, you are right. Apologies.

'Add Media’ button isn’t very elegant is it?

**Comment by bainternet** [comment]
The workaround is just like @drank 

Don't see this as a must feature.


Thanks for the suggestion.
thanks for the suggestion
