### ISSUE TITLE
Menu description option [feature request]

### ISSUE THREAD

**Issue by PaulSolomon93** [pojome/elementor#3839]
## Description
[Feature request]

I would love to see the option of adding the description (pictured below) to the nav menu widget, below/above the menu item name.

![image](https://user-images.githubusercontent.com/14189230/37721071-54e49958-2d31-11e8-8bae-ab478f6fc4b7.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by genilto** [comment]
I'd love to have that available too!! Actually right now I need this and I have to create something to make it possible...
