### ISSUE TITLE
Bug submission. 

### ISSUE THREAD

**Issue by john298612** [pojome/elementor#3840]
Created new single post template and assigned a condition to display on x category. When i created a new post and i chose x category for it and i viewed it, it didn't display it with the single custom post template that i had assigned in posts for x category but with the default theme single post template layout. Local install, Astra theme, E-beta-3, EPro-beta-1, no other plugins

**Comment by bainternet** [comment]
@john298612 

Can you make sure that the archive templates are published, in the current beta that's a confirmed bug which keeps it on draft, and should be fixed in the next beta. 

If the issue still persists please please continue this conversation here: #3826

**Comment by john298612** [comment]
Posted in the main conversation. Thank you.
