### ISSUE TITLE
Suggestion: Form item name: show field id in place of "item #xx"

### ISSUE THREAD

**Issue by phdenis63** [pojome/elementor#3843]
Hello,
I have a suggestion for Form item names showed for fields with no label.
In place of showing item #xx

![elemento-form-item](https://user-images.githubusercontent.com/36880621/37730275-94c87e96-2d3f-11e8-88f7-1eb15be86457.jpg)

is it possible to show the "custom id" of the field ?

![elementor-form-no-label](https://user-images.githubusercontent.com/36880621/37730338-bace1b5a-2d3f-11e8-87ef-2b213548bec0.jpg)

I think it may be very helpfull when you have many fields to move.

Best Regards,

Philippe

**Comment by bainternet** [comment]
@phdenis63 

If you don't define the custom id and before you save the id is set to a random string of chars and numbers which would make even less sense, But, here is a snippet you can use that will give you what you want plus will give you the field type as well

```PHP
add_action( 'elementor/element/form/section_form_fields/before_section_end', function( $element, $args ) {
	$elementor = \Elementor\Plugin::instance();
	$control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'form_fields' );

	if ( is_wp_error( $control_data ) ) {
		return;
	}
	$control_data['title_field'] = '{{{ field_label || field_type.charAt(0).toUpperCase() + field_type.slice(1) + " #" + _id }}}';
	$element->update_control( 'form_fields', $control_data );
}, 10, 2);
```

![screen shot 2018-03-22 at 17 43 05](https://user-images.githubusercontent.com/660572/37780997-9065d1b4-2df8-11e8-815b-da01602586ae.png)
