### ISSUE TITLE
[Feature Request] Vertical Social Icons

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#3844]
When the social icon element is used the icons are arranged horizontally. They can be made to arrange themselves vertically but then it is not possible to adjust the space between the icons. It would be good to have the option to be able to select whether the icons are arranged horizontally {default} or vertically. If the option is to arrange them vertically then the spacing setting would set the vertical not the horizontal spacing.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
