### ISSUE TITLE
GeneratePress Child Theme Compatibility Issue

### ISSUE THREAD

**Issue by stllrnet** [pojome/elementor#3845]
Today I saw the video where Ben Pines recommends testing the new Pro features with GeneratePress theme. In my site I'm using the "official" Child Theme, where I have some code in the functions.php file to add a couple of Custom Post Types.

Anyway, when trying to create a single post template I'm getting this notification:

![elementor notificaton](https://user-images.githubusercontent.com/35221293/37736913-d02b716e-2d17-11e8-9e96-9fddb67100dd.JPG)

I followed the steps you provided in the "Learn More" link and I found that the problem is the actual Child Theme. No plugin is conflicting, and the Elementor's Editor worked well on the default GP Theme and the TwentySeventeen.

I have already reported this in the official GP forum, I'm reporting it here too as maybe you can find a solution. It's a sad as I wanted to create a Custom Layout for my Custom Post Types.

**Comment by bainternet** [comment]
@stllrnet 

we cant replicate, can you please try to turn on WP_DEBUG and  see if you are getting any server side errors, add to your wp-config.php :

define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );

**Comment by stllrnet** [comment]
@bainternet 

I checked the code in the functions.php file and found a little piece of code that was adding the CPTs to the query, this particular code wasn't provided by the developer of GP. I pulled from an article. Thanks for trying to figure out what the problem was. It wasn't neither Elementor nor GeneratePress.
