### ISSUE TITLE
Styling gets completely removed

### ISSUE THREAD

**Issue by mikeideas** [pojome/elementor#3846]
Occasionally when refreshing, the entire elementor layout breaks and looks like a text file. completely unformatted etc. 

I am also unable to get the image carousel to resize the images to 1080 on the mikeideas.com/our-services page. 

Please let me know if this is an issue with elementor or its compatibility with my theme? (tried on several others with no luck.

**Comment by bainternet** [comment]
@mikeideas 

We can't replicate the issue or help solve it without more details, 
Please contact our support at support@elementor.com for guidance in resolving this issue.
