### ISSUE TITLE
Elementor-pro : forms: A 204 response from a webhook causes error

### ISSUE THREAD

**Issue by CarlesKapy** [pojome/elementor#3847]
I've built up a form with a webhook, that sends data to an API that returns a **204 - No Content** response if everything has run fine.

But in the run function of webhook.php, if a response is not equal to 200, it adds an error (but, it's not the case). That situation leads to an (incorrect) error message to be displayed on the page.

**Comment by bainternet** [comment]
@CarlesKapy 

You can try use the provided `elementor_pro/forms/webhooks/response` action hook to alter the code if 204 is fine for you:
```PHP
add_action( 'elementor_pro/forms/webhooks/response', function( &$response ){
	if( ! is_wp_error( $response ) && isset( $response['response'] ) && is_array( $response['response'] ) && 204 === (int) $response['response']['code'] ) {
		$response['response']['code'] = 200;
	}
} );
```

Or simply create a custom webhook handler:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
		'body' => $fields,
	]);
});```
