### ISSUE TITLE
blank screen with black bars on left

### ISSUE THREAD

**Issue by jcolome** [pojome/elementor#3848]
## Description

installed beta and getting a blank screen
## Steps to reproduce

need to log in to actually see

## Environment

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | 10.0.34 |  
PHP Version: | 7.0.28 |  
PHP Max Input Vars: | 2000 |  
PHP Max Post Size: | 128M |  
GD Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

WordPress Environment |   |  
-- | -- | --
Version: | 4.9.4 |  
Site URL: | https://localmiamideals.com |  
Home URL: | https://localmiamideals.com |  
WP Multisite: | No |  
Max Upload Size: | 128 MB |  
Memory limit: | 40M | We recommend setting memory to at least 64M. For more information, read about how to Increase memory allocated to PHP.
Permalink Structure: | /%postname%/ |  
Language: | en-US |  
Timezone: | 0 |  
Admin Email: | admin@localmiamideals.com |  
Debug Mode: | Inactive |  

Theme |   |  
-- | -- | --
Name: | ListGo Child |  
Version: | 1.0.0 |  
Author: | wiloke |  
Child Theme: | Yes |  
Parent Theme Name: | ListGo |  
Parent Theme Version: | 1.6.5.8 |  
Parent Theme Author: | wiloke |  

Active Plugins |   |  
-- | -- | --
Contact Form 7 - 5.0.1 | By Takayuki Miyoshi |  
ConvertPlayer - 1.0.4 | By Goat In The Boat Software |  
Elementor - 2.0.0-beta3 | By Elementor.com |  
Elementor Pro - 2.0.0-beta1 | By Elementor.com |  
ImageSuite - 3.3.0 | By YMB Properties |  
Login With Social - 1.0.4 | By Wiloke |  
Redux Framework - 3.6.8 | By Team Redux |  
Wiloke Design AddListing - 1.0.3 | By Wiloke |  
Wiloke Listgo Functionality - 1.6.5.8 | By Wiloke |  
Wiloke Listgo Promotion - 1.1.1 | By Wiloke |  
Wiloke Listgo Widgets - 1.3.7 | By wiloke |  
Wiloke Mega Menu - 1.1.2 | By wiloke |  
Wiloke Service - 0.9.9 |   |  
WooCommerce - 3.3.4 | By Automattic |  
WooCommerce PayPal Express Checkout Gateway - 1.5.2 | By WooCommerce |  
WooCommerce Stripe Gateway - 4.0.7 | By WooCommerce |  
WP All Import - ListGo Add-On - 1.0.4 | By Wiloke |  
WPBakery Page Builder - 5.4.5 | By Michael M - WPBakery.com |  
WP Super Cache - 1.5.9 | By Automattic |  
Yoast SEO - 7.1 | By Team Yoast |

**Comment by bainternet** [comment]
@jcolome 

please go through this list https://docs.elementor.com/article/189-having-problems-using-elementor-start-here and see if you can pinpoint the cause of the issue, and also try increasing the memory.

> We recommend setting memory to at least 64M. For more information, [read about how to Increase memory allocated to PHP.](https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP)
