### ISSUE TITLE
[Feature Request] Dynamic Menu displaying Child Categories based on Current Parent

### ISSUE THREAD

**Issue by stllrnet** [pojome/elementor#3851]
Hi Elementor team, thanks for all the effort on the new features for 2.0!

I always wanted to make a secondary menu that shows only in Category pages, displaying the subcategories of the current parent category. I think that with the new conditional structure you have developed, this could be added.

You can see a live example here: https://www.vogue.com/

As you can see, in the main page there is only a main menu with the Parent Categories. It's only in the Parent Category page that a secondary menu appears, pulling the child categories from the current Parent.

This would be a killer feature, and I hope it make it into the official release.

**Comment by bainternet** [comment]
Not sure what the request here is? 

it should be easy to do with the conditions we have implemented in Pro 2

so unless I'm missing something?

**Comment by stllrnet** [comment]
@bainternet 

I'm sorry, I find hard to explain the feature, but here I go again as I think it could be an amazing feature...

I'm using the Vogue website as example because they are implementing this. You can see that in the landing page they place the main menu "below header". There you can see the parent categories...

![vogue main page](https://user-images.githubusercontent.com/35221293/37803496-abad4d7a-2df4-11e8-984c-09339dcb6403.jpg)

In the image below, we are now in the archive page, properly the "Culture" category as you can see in the url. Now the main menu is placed "above header", and a secondary menu has taken the "below header" position. This secondary menu is populated by the sub categories of the current parent category.

![vogue archive page](https://user-images.githubusercontent.com/35221293/37803650-ba1d38c4-2df5-11e8-964d-28fa9e960010.jpg)

The Nav Menu widget could have a "Dynamic" field where it can pull the sub categories from the current parent and have a display conditional to show only in category archives. About the dynamic position, IDK if this could be added, but would be really useful.

Thanks for taking the time to receive feature requests. I hope this is more clear 😄

**Comment by bainternet** [comment]
@stllrnet 

This is just as I thought, should be fairly easy to do with the new header and conditions system.
simply duplicate the header you have and replace the menu with the one you wish to at each category/other condition, and set that as the condition of the header.

Thanks for the feedback.
