### ISSUE TITLE
Ability to Randomise Carousel Images.

### ISSUE THREAD

**Issue by Duartemartins** [pojome/elementor#3853]
I would like to see the ability to randomise the order of the images in a carousel. Other slider plugins already do this, and it should be something fairly simple to do: https://www.themepunch.com/faq/randomize-first-slide-starting-point/

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, you can randomize the order using JS, [here are some suggestions](https://github.com/kenwheeler/slick/issues/359)
Thanks for the feedback.

**Comment by nivniv44** [comment]
+1

**Comment by digitalchet** [comment]
+1

**Comment by cedriclajato** [comment]
+1

**Comment by DunklerPhoenix** [comment]
+1 (yeah its old I know :D)
