### ISSUE TITLE
[New feature request]: Need New Review Element in elementor

### ISSUE THREAD

**Issue by rahul6388** [pojome/elementor#3854]
Why there is no review element in elementor. i want review element in elementor where people can give their reviews on multiple services of website or products.

**Comment by bainternet** [comment]
@rahul6388 

can you provide examples?

**Comment by rahul6388** [comment]
See these sites for examples
https://hostadvice.com/hosting-company/fastcomet-reviews/
https://www.whoishostingthis.com/hosting-reviews/siteground/

Where they have added customers reviews..pleople can give their rating on different produts..
So we can add customers reviews on any page or post.

**Comment by rahul6388** [comment]
If i wanted to that then i wont have posted request here. I want this feature to be added in elementor pro..it will give lot of flexibility to elementor. When will i expect it to be on board?

**Comment by bainternet** [comment]
@rahul6388 @eloithomaz 

thanks.

**Comment by rahul6388** [comment]
When will you add this feature?

**Comment by rahul6388** [comment]
Hello any update on this issue?
