### ISSUE TITLE
Custom Elementor Fonts not loading on Mobile

### ISSUE THREAD

**Issue by jcmatoskx** [pojome/elementor#3855]
## Description

I'm on the latest Elementor Version (beta) (however I don't know if the previous versions have or not the same issue)
and I noticed that the Custom Fonts inserted through Elementor are not loading/working on mobile. I tried different browsers and mobile devices but none loaded, it seems that the custom fonts are only loading on desktop and tablet.

**Comment by bainternet** [comment]
@jcmatoskx 

The Font loader is not aware if you are requesting the page from desktop or mobile, it works the same in all cases, please make sure you clear your cache if any both server and browser. If the issue still persists then please contact our support at support@elementor.com for guidance in resolving this issue.
