### ISSUE TITLE
Full Width Issue

### ISSUE THREAD

**Issue by aryasharma36** [pojome/elementor#386]
Chat Conversation Start

572 people like this
Product/Service
MON 8:31AM
Hi Guys,

I am a big fan of your page builder but of late have been experiencing some difficulties with the full width functionality.

I also downloaded the child theme of twenty sixteen from your website but it still doesn't work.

I tried the steps from your help page as well as the video but still unable to find the cause.

Apart from changing the "boxed" to "full width" in the section layout , are there any other settings I have to follow?

**Comment by hansnolte** [comment]
Hi aryasharma36

![full_width_page](https://cloud.githubusercontent.com/assets/7922627/17508989/fa8365f0-5e17-11e6-848d-a38eb2a8b5c8.png)

**Comment by aryasharma36** [comment]
@hansnolte already done that, still no change!

**Comment by hansnolte** [comment]
Another try.

![full_width](https://cloud.githubusercontent.com/assets/7922627/17545312/b21b83b8-5edc-11e6-8d3f-7e15865e32b2.jpg)

![full_width_1](https://cloud.githubusercontent.com/assets/7922627/17545316/b90a5424-5edc-11e6-81e9-fd599bd12827.jpg)


Do you have a Link?

**Comment by jmarshallm** [comment]
I'm having this problem but I speak and read in English... is this post solved????

**Comment by marks1974** [comment]
I am having the same problem. I have downloaded the child theme, set my template to full width but no matter what I try, the page does not go full width as shown in the [YouTube channel video](https://www.youtube.com/watch?v=ISuZCU4aKmw) or as hansnolte as posted in the above screenshot. I have even tried using some of the included page templates but the result is the same. 

I have tried this in both WP version 4.5.3 and 4.6 using the Elementor 2016 child theme. I have setup a workspace in Cloud 9 so if anyone wants to send me their email address, I will happily share the installation. It may then help others who are having the same problem if it's not a coding bug issue.

**Comment by arielk** [comment]
Please send us your problem via email: support@elementor.com

**Comment by aryasharma36** [comment]
hey marks1974,

Was your issue fixed?

**Comment by marks1974** [comment]
I have not yet had a chance to send a reply but no.

I checked earlier in the week to see if there had been an Elementor update however as far as I am aware, I still do not get full width. I will check and investigate once I am at my computer again.






On Sat, Aug 27, 2016 at 2:54 PM +0100, "aryasharma36" <notifications@github.com<mailto:notifications@github.com>> wrote:


hey marks1974,

Was your issue fixed?

-

**Comment by CrazyFrenchie** [comment]
Hey there, joining in the conversation as I'm experiencing the same issue. I went through other threads on github, the Elementor documentation, etc. but couldn't find a solution for a full-width page when editing with Elementor... :/

Did the staff or anyone can help with this? Seems like it a recurrent issue.

By the way, I'm using Elementor on my localhost for the moment but I don't think that could be the source of it.

**Comment by marks1974** [comment]
The staff at Elementor asked them to contact them direct about the issue but I have been too busy with work to send an email yet.

I also setup WP on local host and then double checked it by setting up another WP installation on Cloud 9. I came across the same problem in both. Either there is a bug somewhere or I have missed a setting.




On Sat, Aug 27, 2016 at 5:39 PM +0100, "Antoine Beauvillain" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey there, joining in the conversation as I'm experiencing the same issue. I went through other threads on github, the Elementor documentation, etc. but couldn't find a solution for a full-width page when editing with Elementor... :/

Did the staff or anyone can help with this? Seems like it a recurrent issue.

By the way, I'm using Elementor on my localhost for the moment but I don't think that could be the source of it.

-

**Comment by yehudah** [comment]
We working on a permanent solution to the full width templates.
stay updated.

**Comment by benpines** [comment]
We now have a full width stretch control: https://elementor.com/v09-think-wider/

**Comment by Himaghiri** [comment]
Elementor is the best page builders which I know at the moment. I have worked with many page builders and I can really say that Elementor is best of all. If you need a complete blank template for Elementor, what I can suggest is to customize and use blankslate theme as blankslate has very minimum css that any wordpress theme can have. Please go through this tutorial to know how to use blamkslate theme with Elementor https://www.youtube.com/watch?v=DvcAIrDIz1s     https://www.youtube.com/watch?v=aQY0lb2l0Bs&t=100s     Through this video you will learn how to make full width page with elementor. Also you will learn how to create full width background slider with elementor.

**Comment by Neillbar** [comment]
Good Day, My Full width works 100% on Desktop but on mobile it does not. 

When you load the website on a mobile device and you pull it to the side, the picture no longer is full width. The weird thing is, on the home page it works but on the rest it does not work.

Please see picture attached what i mean. 

Thanks
![why it is wrong](https://user-images.githubusercontent.com/43991798/46668247-25a2e700-cbcc-11e8-955e-98c4525e2ead.jpg)
![how it should looks](https://user-images.githubusercontent.com/43991798/46668249-263b7d80-cbcc-11e8-8e18-dfb75b859693.PNG)

**Comment by remostein** [comment]
> Good Day, My Full width works 100% on Desktop but on mobile it does not.
> 
> When you load the website on a mobile device and you pull it to the side, the picture no longer is full width. The weird thing is, on the home page it works but on the rest it does not work.
> 
> Please see picture attached what i mean.
> 
> Thanks
> ![why it is wrong](https://user-images.githubusercontent.com/43991798/46668247-25a2e700-cbcc-11e8-955e-98c4525e2ead.jpg)
> ![how it should looks](https://user-images.githubusercontent.com/43991798/46668249-263b7d80-cbcc-11e8-8e18-dfb75b859693.PNG)

I'm having the same issue.
Is it solved yet?
I noticed that when switching to tablet mode there are lots of elements that align left, or that their margins have been changed in a weird way.
For example, I have a section, that is set to full width, and "stretch section" is on (even when it's off it still happen), but the column inside it is suddenly align left when switching to tablet mode and can't be centered, only when changing from full width to "boxed" with 500 px. Soooo weird!

I also get the white background on the side like Neillbar showed.

**Comment by ramspeleo** [comment]
Hello, i tried to use the fullwidth on elementor and it is working but when you use  the tabs widget and acordion the functionality is not work. Is there anyone encounter this error? Please help...
