### ISSUE TITLE
No ability to edit the content i put in the single post template for a specific category 

### ISSUE THREAD

**Issue by john298612** [pojome/elementor#3862]
hello. i assigned a single post template for a specific post category. when i create a new post taht belongs to that category and i go to edit it i can not edit the elements i have put there in the default single post template but i can only add new elements. i dont know if that is oging to be the default behavior or notb ut it would be great if i could edit the elements that i put there in the single post template. that way i can preset the style of various elements like text editor and every time i create a new post i can just paste my text from word and it will get the styling that i had already pre set instead of having to adjust it every time.

**Comment by bainternet** [comment]
@john298612 

The template for single is something that lives above the actual post (single) itself and can only be edited in its own edit mode. not for the post edit mode.

If you want a to create an editable template for the content then you can, like any other page, and save that as a template. Then on the next page/post you create simply import that template.

Thanks for the feedback.

**Comment by john298612** [comment]
ok. i see. it would have been great if we could edit it hough. as i described you could then predefine the font style of various text elements and then just paste your text inside and they are already defined. no need to change again the font size, color etc. it would be a great time saver. i hope that you will be able to implement it. for blog posting it would be a great function. 
I had completely forgot that i had posted this here and i posted it in the front page as well.
