### ISSUE TITLE
[Feature Request] Thumbnails option on Post Navigation

### ISSUE THREAD

**Issue by rja66** [pojome/elementor#3863]
I would like option to show featured image thumbnail on Post Nav widget.
Thumbnail could be stacked with Text and Post Title, with arrow centred horizontally outside thumbnail.
This is a useful feature for portfolio sites.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by JJRobertsSex30** [comment]
This feature is badly needed

Not only that but it seems to be a bug that it does not work because using the "post navigation" widget shows the option of being able to edit the button's background image and assigning it the featured post.

It just does not do anything if you do that so it looks like a bug to me.

**Comment by JJRobertsSex30** [comment]
Seriously why would you use elementor or elementor pro if it's impossible to do something as simple as a back / next button with the featured image of the post on the button

I even tried to do it manually but the image occupied 100% of the back /  next button and not 50% like it should and this next / back widget is a PRO feature that you have to pay for when even something as basic as that does not work ?!

**Comment by JJRobertsSex30** [comment]
Does anyone know of a plugin that can do this?

**Comment by XLogus** [comment]
You can add thumb using this code
/// Previous next post thumb
add_filter('previous_post_link', 'sydney_child_post_nav_thumbnail', 20, 5 );
    add_filter('next_post_link', 'sydney_child_post_nav_thumbnail', 20, 5 );
    function sydney_child_post_nav_thumbnail($output, $format, $link, $post, $adjacent) {

    	if( !$output ) {
     		return;
      }

      $divclass = '';
      switch ($adjacent) {
    		case 'next':
    			$divclass = 'custom-nav nav-next';
    			break;
    		case 'previous':
    			$divclass = 'custom-nav nav-previous';
    			break;
    		default:
    			break;
    	}

      $arrow_prev = '';
      $arrow_next = '';
      if( 'next' == $adjacent ) {
        $arrow_next = '<span>&#10230;</span>';
      }
      if( 'previous' == $adjacent ) {
        $arrow_prev = '<span>&#10229;</span>';
      }

    	$rel   = $adjacent;
      $thumb = get_the_post_thumbnail($post->ID, array( 100, 100));
      $title = '<div class="'.$divclass.'">' . $arrow_prev . $post->post_title . $arrow_next . '</div>';

    	$class = '';
    	if( !empty($thumb) ) {
    		$class = 'post-nav-has-thumbnail';
    	}

      $string = '<a href="' . get_permalink( $post->ID ) . '" rel="' . $rel . '" class="'.$class.'">' . $thumb;
      $inlink = str_replace( '%title', $title, $link );
      $inlink = $string . $inlink . '</a>';
      $output = str_replace( '%link', $inlink, $format );

      if( !$post->ID ) {
        return;
      }

      return $output;

    }

**Comment by artemlime** [comment]
Not work for me

> You can add thumb using this code
> /// Previous next post thumb
> add_filter('previous_post_link', 'sydney_child_post_nav_thumbnail', 20, 5 );
> add_filter('next_post_link', 'sydney_child_post_nav_thumbnail', 20, 5 );
> function sydney_child_post_nav_thumbnail($output, $format, $link, $post, $adjacent) {
> 
> ```
> 	if( !$output ) {
>  		return;
>   }
> 
>   $divclass = '';
>   switch ($adjacent) {
> 		case 'next':
> 			$divclass = 'custom-nav nav-next';
> 			break;
> 		case 'previous':
> 			$divclass = 'custom-nav nav-previous';
> 			break;
> 		default:
> 			break;
> 	}
> 
>   $arrow_prev = '';
>   $arrow_next = '';
>   if( 'next' == $adjacent ) {
>     $arrow_next = '<span>&#10230;</span>';
>   }
>   if( 'previous' == $adjacent ) {
>     $arrow_prev = '<span>&#10229;</span>';
>   }
> 
> 	$rel   = $adjacent;
>   $thumb = get_the_post_thumbnail($post->ID, array( 100, 100));
>   $title = '<div class="'.$divclass.'">' . $arrow_prev . $post->post_title . $arrow_next . '</div>';
> 
> 	$class = '';
> 	if( !empty($thumb) ) {
> 		$class = 'post-nav-has-thumbnail';
> 	}
> 
>   $string = '<a href="' . get_permalink( $post->ID ) . '" rel="' . $rel . '" class="'.$class.'">' . $thumb;
>   $inlink = str_replace( '%title', $title, $link );
>   $inlink = $string . $inlink . '</a>';
>   $output = str_replace( '%link', $inlink, $format );
> 
>   if( !$post->ID ) {
>     return;
>   }
> 
>   return $output;
> 
> }
> ```

doesn't work for me

**Comment by momo-fr** [comment]
Yes, I would like that too!!

**Comment by dannyfoo** [comment]
@XLogus Thank you for sharing this. It's working for me.

And I'm re-formatting it here for anyone else who tried to copy-paste the code you wrote.

```
// Previous next post thumb
add_filter('previous_post_link', 'sydney_child_post_nav_thumbnail', 20, 5 );
add_filter('next_post_link', 'sydney_child_post_nav_thumbnail', 20, 5 );

function sydney_child_post_nav_thumbnail($output, $format, $link, $post, $adjacent) {
	if( !$output ) {
		return;
	}

	$divclass = '';
	
	switch ($adjacent) {
		case 'next':
		$divclass = 'custom-nav nav-next';
		break;
		case 'previous':
		$divclass = 'custom-nav nav-previous';
		break;
		default:
		break;
	}

	$arrow_prev = '';
	$arrow_next = '';
	
	if( 'next' == $adjacent ) {
		$arrow_next = '<span>&#10230;</span>'; // Add right arrow using UNICODE
	}
	if( 'previous' == $adjacent ) {
		$arrow_prev = '<span>&#10229;</span>'; // Add left arrow using UNICODE
	}

	$rel   = $adjacent;
	$thumb = get_the_post_thumbnail( $post->ID, array( 100, 100) ); // Adjust desired image size here 100, 100 based on Width X Height
	$title = '<div class="'.$divclass.'">' . $arrow_prev . $post->post_title . $arrow_next . '</div>';

	$class = '';
	if( !empty($thumb) ) {
		$class = 'post-nav-has-thumbnail';
	}

	$string = '<a href="' . get_permalink( $post->ID ) . '" rel="' . $rel . '" class="'.$class.'">' . $thumb;
	$inlink = str_replace( '%title', $title, $link );
	$inlink = $string . $inlink . '</a>';
	$output = str_replace( '%link', $inlink, $format );

	if( !$post->ID ) {
		return;
	}

return $output;

}
```

And here's some further reading on declaring a post thumbnail's size (https://developer.wordpress.org/reference/functions/get_the_post_thumbnail/#comment-311) for anyone looking to learn more.

**Comment by konkerdigital** [comment]
@dannyfoo thank you for this sir, working great!

**Comment by miri477** [comment]
Thanks! It works great!
Is it possible to set the right image to be to the right of the text?
