### ISSUE TITLE
[New feature request]: Custom Social Icon

### ISSUE THREAD

**Issue by pavelsiska** [pojome/elementor#3864]
Would be awesome if I could add an item in the Social Icon Widget that would include an option to load any custom image, transparent png probably, as its icon and then I could also pick a custom background color.

That would allow me to include any social profile there is without having to wait till it gets implemented (like artstation, imdb, cgsociety, etc... and other paramount art sites which are now a little bit sidelined)

**Comment by bainternet** [comment]
I merged this issue with  #110 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
