### ISSUE TITLE
REPEATER control/empty default value bug

### ISSUE THREAD

**Issue by shinTM** [pojome/elementor#3865]
since Elementor version 2.0 beta.3 I got a trouble with REPEATER control, if default is left empty [http://prntscr.com/iv8civ](http://prntscr.com/iv8civ),  id option is not saved in the post meta _elementary_ data value, therefore I get notice error here http://prntscr.com/iv8g86  https://github.com/pojome/elementor/blob/release/2.0.0/includes/base/controls-stack.php#L1714

**Comment by bainternet** [comment]
@shinTM 

can you please update to beta 4 and report back?
#3706

**Comment by shinTM** [comment]
Thanks for attention to my problem. I updated the version to beta4 http://prntscr.com/iw3brf but the problem is not solved http://prntscr.com/iw3dmp and error notice still here http://prntscr.com/iw3duj
I added a default value but for the sections that were added earlier I have an error. I fixed in my plugin http://prntscr.com/iw3gg7 (using 'wp' action) but its very very bad solution and last resort for me

**Comment by KingYes** [comment]
Fixed by this PR: https://github.com/pojome/elementor/pull/3916

**Comment by atashinbar** [comment]
@KingYes The issue is not fixed.
