### ISSUE TITLE
UI/UX - Reordering rows/sections needs improvement

### ISSUE THREAD

**Issue by asadkn** [pojome/elementor#3867]
When sections get large or have large elements, it's a painful and quirky experience to **move**/get elements where you want them to be. It's bad enough with mouse, it's worse on slow devices or when there are many elements, but it's almost impossible for trackpad users to _drag and move_. Even with mouse, reordering very long sections like blog posts is extremely difficult. 

Ideas:
- Email builders like stampready, html template builders and other page builders in WP space often have an **outline** view which shows all the sections on the page for easy re-ordering. Checkout brizy.io
- The new VisualComposer has a "tree view" of all the sections and blocks on the page. 
- SquareSpace has a "Manage Sections" view which disables all other controls and gives a zoomed out view (this still isn't ideal for really long sections)
- Simple control on context menu to move up/move down can also be helpful.

**Comment by davidmabelle** [comment]
Please make Elementor work like Brizy!!  https://brizy.io/

**Comment by arielk** [comment]
Merge  #1165
