### ISSUE TITLE
Dynamic Content - ACF Select Field Multiple Selections Enabled

### ISSUE THREAD

**Issue by twmcmahan** [pojome/elementor#3868]
Elementor Version 2.0.0-beta4
Elementor Pro Version 2.0.0-beta1

Conditions of Error
ACF - Select Field, Multiple Selections Enabled.  Whether one selection is chosen or multiple, same error.

Error:
Warning: Illegal offset type in isset or empty in /home/acmpages/elementor20/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php on line 49
Array

**Comment by bainternet** [comment]
#3826
