### ISSUE TITLE
[Feature Request] Display Sections Conditionally Based on ACF Field Values

### ISSUE THREAD

**Issue by twmcmahan** [pojome/elementor#3869]
Example:

Building a site for a talent agency.  ACF Field is "Gender" with "Male" and "Female" options.  

Women have "Dress Size" and "Bra Size" whereas men have "Pant Size" & "Shirt Size"

Would like to be able to create 2 containers, one for "Male" and one for "Female" with the appropriate sizes in each.  Container display would be conditional on values in ACF Field "Gender"

Currently I'll probably write custom javascript to read the value of the Gender div and change the display parameter in CSS at load time.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
