### ISSUE TITLE
Section Stretch Not Found

### ISSUE THREAD

**Issue by niamulrox** [pojome/elementor#3870]
Hi,

I had done Section Stretch last month but when I am trying after update its not showing any option to make section full width. 

From Your Doc
New! Option 1 - Use Stretch Section
We have added a Stretch Section feature, that bypasses the theme limitations by using JavaScript and makes the section span to full width, from left to right. Bare in mind this is not a best practice when it comes to coding standards, but can be used as a quick fix to full-width issues.

To set it, go to Section > Layout > Stretch Section and switch it to 'Yes'.

But there is now Layout Tab. 

Here is the screenshot bellow 
https://www.dropbox.com/s/d76to34nosfqq6f/Screenshot%202018-03-24%2002.57.24.png?dl=0

Please advice me how to make a section fullwidth like before by section setting ?

Thanks

**Comment by niamulrox** [comment]
Another Issue 

Really ? No one having single reply ? Started my theme with Elementor and seems now no one working for developer. After making all things now its now showing live editing mood. 

Editing mood like this 
https://www.dropbox.com/s/6dl6dq2i9qqo6rq/Screenshot%202018-03-25%2001.29.33.png?dl=0

And frontend after editing looks like this 

https://www.dropbox.com/s/jv0r8k9c1129v0w/Screenshot%202018-03-25%2001.30.10.png?dl=0

**Comment by bainternet** [comment]
@niamulrox 

In the screenshot you linked above, you are not on the section edit panel but on a 3rd party widget (slider revolution). our docs say clearly like you have stated: 

> go to **Section** > Layout > Stretch Section and switch it to 'Yes'.

![screen shot 2018-03-25 at 9 59 19](https://user-images.githubusercontent.com/660572/37872590-764ec62e-3013-11e8-81ae-c54b2ce8411d.png)

as for you second issue, please describe the issue.

**Comment by niamulrox** [comment]
Hi,

Sorry but I did not found the section settings. When creating a new section there I am not finding the settings like you show me. 

Check my screenshot bellow 

https://www.dropbox.com/s/51t3i3e4f484nya/Screenshot%202018-03-25%2014.21.02.png?dl=0

**Comment by bainternet** [comment]
@niamulrox 

Again, not section panel, its column. click on the section handle to be able to access the section panel:

![LXWzfBE](http://static.gitscout.com/939264a6d1517cbcfd638c24fe017354272934711984b593500e459dc64f6936.png)

**Comment by kanwalyaseen8** [comment]
Section Stretch   I UNBLE  TO SEE AFTER CHNGE UI CAN ANYONE TELL US  WERE THEY GONE???????
