### ISSUE TITLE
Media Carousel - Doesn't transition during editing/preview

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#3873]
It appears the slide transitions are disabled when in edit and edit-preview modes making it a tad difficult to adjust timing preferences when we can only view it working from the front end.  At least in edit-preview would could toggle quickly to see it in action as we play with the settings.  Thanks

**Comment by bainternet** [comment]
@pingram3541 

I can't replicate,

please make sure you are up to date with the latest versions.

feel free to reopen if the issue still presists.
