### ISSUE TITLE
[Version 2.0.0 Beta 4]

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#3877]
Posting a link into the link field on a button the link text is not constrained by the field and overflows over the link setting "cog" - see attached image.
![link picture](https://user-images.githubusercontent.com/22448787/37865424-28a3f8da-2f74-11e8-8433-c7e80fb007ed.png)
Found that the same Issue occurs on a social media icon link.
![social picture](https://user-images.githubusercontent.com/22448787/37865698-425d7310-2f78-11e8-9d78-4204d9de9e71.png)

**Comment by bainternet** [comment]
@nickdgreen 

Thanks, noted. please continue beta bug reports in the correct issue #3706
