### ISSUE TITLE
[Version 2.0.0 Beta 4]

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#3878]
Successfully created and applied a page header and a page footer. Both appear in the correct tabs in My Templates and both display on pages "on the front end". I can't, however, edit the templates as I get the "the_content" error message.
![error](https://user-images.githubusercontent.com/22448787/37865899-cfaf9282-2f7a-11e8-8bd7-06a4fa1ccac3.png)

**Comment by epakrat** [comment]
@nickdgreen  -The official beta issue thread is here - https://github.com/pojome/elementor/issues/3706

No need to open a separate issue for each contribution you provide like you have done with your two issues.

**Comment by bainternet** [comment]
@nickdgreen @epakrat 

This is actually related to Pro 2.0 beta. #3826 

thanks noted.
