### ISSUE TITLE
"Invalid supplied argument" warning for hidden repeater fields

### ISSUE THREAD

**Issue by tudormnt** [pojome/elementor#3886]
Hi,

Please consider adding an additional check before this loop:

https://github.com/pojome/elementor/blob/59850ebed85c2e1c57cb6f914576677851e7c67d/includes/base/controls-stack.php#L1055

to make sure that $settings[ $control_name ] is not null. This is the case when the repeater field is displayed conditionally in the editor panel. Currently it fires off an "invalid argument supplied" warning in such cases.

Thanks!

**Comment by bainternet** [comment]
@tudormnt 

Can you provide steps to replicate?

**Comment by tudormnt** [comment]
@bainternet none of the Elementor widgets have a repeater field under a condition, so this isn't a bug that appears for Elementor or Elementor Pro. In one of our Extras plugin widgets we show a repeater field conditionally. If for the same widget we activate a dynamic tag for a control, the above error appears. I don't honestly know what more I can say to replicate this :)

**Comment by KingYes** [comment]
Fixed by this PR: https://github.com/pojome/elementor/pull/3916
