### ISSUE TITLE
Bug / Enhancement: Always overwrite the sent-to fields with the admin email address

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#3890]
When importing a Elementor Template or Block with a contact form, it has "bohdan@pojo.me" as sent to field. If you forget to check this, you will miss out a lot of emails. (And the Pojo.me staff gets spammed).

**Suggestion: Please always overwrite the sent-to fields with the admin email address,** when a user imports a template or block. This way you are sure that the mails are received at the correct email address.

![2018-03-25_232852](https://user-images.githubusercontent.com/5883842/37880145-5094dfa6-3084-11e8-97e8-8f083da2eca9.png)

**Comment by arielk** [comment]
Fixed in v1.15.4

Thanks for your report!
