### ISSUE TITLE
Hope can Limit revisions history number, because Too large of database table use in revisions history

### ISSUE THREAD

**Issue by wangneo** [pojome/elementor#3892]
Hi
revisions history is great, but autosave make the database postmeta table huge, hope more control about this.
Thanks.

**Comment by bainternet** [comment]
@wangneo 

The same rules that apply to WordPress native revisions apply on elementor revisions as well ( both being the same thing), which means you can limit the max number of revisions:
```PHP
define( 'WP_POST_REVISIONS', 3 );
```
