### ISSUE TITLE
Custom elements pushed down?

### ISSUE THREAD

**Issue by SecondLineThemes** [pojome/elementor#3902]
Hey guys,

When using the elements manager to create new elements, there was previously a setting to choose the default location of those elements, seems as this is no longer working with 2.0.

Any updates on that?
```
   Plugin::instance()->elements_manager->add_category(
        'name-goes-here',
        [
            'title'  => 'title-goes-here',
            'icon' => 'icon-goes-here'
        ],
        2 // this does not work!
    );
```

**Comment by bainternet** [comment]
@SecondLineThemes 

Yes the API for adding widget categories was updated, we are working on the updating the code reference. 
thanks.

**Comment by SecondLineThemes** [comment]
Thanks @bainternet. I've been waiting to see updates on the code reference, but still nothing.
The only resource I could find somewhere was last updated in January - https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md

Could you at least point me to the doc page of the updated API or somewhere within the code reference if the actual hook/function name was changed?

No worries if it is still outdated, but this way I'll know where to start looking.

**Comment by ryanlabelle** [comment]
Here is the solution. 

https://developers.elementor.com/widget-categories/

:)

**Comment by SecondLineThemes** [comment]
@ryanlabelle - Thanks for sharing the link! 
However, I already did see this page, but not sure how a custom category can be placed above (or right after) the default (and first) Elementor widget category that currently displays first?

**Comment by ryanlabelle** [comment]
@SecondLineThemes - The closest I could get is to list our custom widgets under the General Elements Group. 

I'm sure you could hijack the function that prints out the widget sections as well. I'm happy with our just under the general block.  Look for the init_categories() function inside elementor/includes/managers/elements.php - you can probably get ahold of $this->categories and resort the arrays if you wanted to.

Cheers!

**Comment by SecondLineThemes** [comment]
@ryanlabelle - Yup. Not really ideal, as before the 2.0 update it was already supported out of the box, but I guess we'll have to hack our way around it :)

Cheers!

**Comment by notrealdev** [comment]
how to set priority for new widget category ??

```php
elements_manager->add_category(
    'fun-theme',
    array(
        'title' => esc_html__( 'Fun Theme', 'fun' ),
        'icon'  => 'fa fa-plug',
        // priority
    ),
);
```

**Comment by notrealdev** [comment]
Hi, any new?
