### ISSUE TITLE
2.0 - Can't Edit anymore

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#3904]
See - https://wordpress.org/support/topic/update-2-0-cant-edit-error-even-in-canvas/

1) I updated to 2.0 and even after purging all cache, logging out and back in, w/ no other plugins except Elementor and Elementor Pro active ands using Twenty Seventeen theme, fresh WP 4.9.4 install.

2) I also disabled Pro and confirmed same result.

3) Next I rolled back to 1.9.8 which was working prior to update and now I'm getting a js error in the console and the loader just hangs.

`Uncaught TypeError: Cannot read property 'is_administrator' of undefined - editor.min.js?ver=1.9.8:2`

4) I then tried to roll back Pro 1.15.4 (offering 1.14.2 instead of other 1.15.X versions 1-3) which had also been updated thinking this was the source of the new js error but the roll back fails - https://github.com/pojome/elementor/issues/3905

**Comment by pingram3541** [comment]
Ok, changed themes from Twenty Seventeen to Twenty Sixteen and I could access the editor again and no js error even though I didn't roll back Pro from 1.15.4

Switched back to Twenty Seventeen and same.  So very strange, all reloads were completed with "empty cache and hard reload" browser-side, server side cpanel cache and modsec is disabled site-wide and there is no DNS level caching, i.e. Cloudflare.

After updating back to 2.0 and attempting to edit a freshly created page using Canvas template results in the same "the preview could not be loaded" error and in the console I see:

`https://mydomain.com/wp-admin/undefined&1522087940552 - 404 (Not Found)`

Changing themes does not fix it.  Rolling back to 1.9.8...and this time the editor works again without having to change themes.

**Comment by kkeennaa** [comment]
Same, I can access my editor but these are the errors I find:


TypeError: undefined is not an object (evaluating 't.element')
			at https://thebrandingirl.com/wp-content/plugins/elementor/assets/js/editor.min.js - 2:138090
			2018-03-26 17:21 +00:00
			x 34 times

		TypeError: undefined is not an object (evaluating 'elementor.config.user.is_administrator')
			at https://thebrandingirl.com/wp-content/plugins/elementor/assets/js/editor.min.js - 2:154143
			2018-03-26 12:29 +00:00
			x 15 times

		TypeError: undefined is not an object (evaluating 'c.nodeType')
			at https://thebrandingirl.com/wp-admin/load-scripts.php?c=0&load%5B%5D=mce-view,imgareaselect,image-edit,quicktags,wplink,jquery-ui-position,jquery-ui-menu,jquery-ui-autocomplete,thickbox,media-uploa&load%5B%5D=d,heartbeat,wp-auth-check,jquery-ui-resizable,imagesloaded,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color&load%5B%5D=-picker&ver=4.9.4 - 16:307
			2018-03-19 06:06 +00:00

		TypeError: undefined is not an object (evaluating 't.element')
			at https://thebrandingirl.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.8 - 2:120269
			2018-03-16 11:01 +00:00
			x 32 times

		TypeError: undefined is not an object (evaluating 'j.style')
			at https://thebrandingirl.com/wp-admin/js/editor.min.js?ver=4.9.4 - 1:693
			2018-03-13 12:03 +00:00
			x 2 times

		TypeError: elementor.getPanelView().getCurrentPageView().showView is not a function. (In 'elementor.getPanelView().getCurrentPageView().showView("search")', 'elementor.getPanelView().getCurrentPageView().showView' is undefined)
			at https://thebrandingirl.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=1.15.1 - 2:30305
			2018-03-13 07:25 +00:00

I disabled all the plugins but nope.

**Comment by mabaraujo** [comment]
Same here with 2.0.1
TypeError: undefined is not an object (evaluating 'this.getRegion("panel").currentView')
			at http://unicomplementar.com.br/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.1 - 2:88074
			2018-03-27 14:55 +00:00
			x 8 times

		TypeError: undefined is not an object (evaluating 'c.nodeType')
			at http://unicomplementar.com.br/wp-admin/load-scripts.php?c=1&load%5B%5D=mce-view,imgareaselect,image-edit,quicktags,wplink,jquery-ui-position,jquery-ui-menu,jquery-ui-autocomplete,thickbox,media-uploa&load%5B%5D=d,heartbeat,wp-auth-check,jquery-ui-resizable,imagesloaded,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color&load%5B%5D=-picker&ver=4.9.4 - 16:307
			2018-03-27 14:31 +00:00

		TypeError: undefined is not an object (evaluating 'this.getRegion("panel").currentView')
			at http://unicomplementar.com.br/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.1 - 2:88074
			2018-03-27 14:31 +00:00
			x 4 times

**Comment by bainternet** [comment]
Please update to 2.0.2!!!
make sure to clear browser and server cache, 

Thanks for reporting.

**Comment by Phill** [comment]
This is back after updating to 2.3.8 and rolling back doesn't fix it. Not all pages are broken, only a few.
