### ISSUE TITLE
Form icons

### ISSUE THREAD

**Issue by nesoor** [pojome/elementor#3908]
It would be cool if I can give each form field an icon, this makes the form even more fancy !
Buttons already have an icon just the form fields don't have any :)
![form with icons](https://user-images.githubusercontent.com/19656499/37939171-a68faa5c-3161-11e8-81df-30747b202711.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by zrk4444** [comment]
+1

**Comment by IlPizza79** [comment]
+1, it would be great!

**Comment by dmeijide** [comment]
Yeessss plz

**Comment by preyes24973** [comment]
+1000

**Comment by salmanjaveed** [comment]
+1

**Comment by SanWall** [comment]
+1

**Comment by ashenoctis** [comment]
+1 YESS PLZ

**Comment by tizum** [comment]
+1

**Comment by marvtub** [comment]
+1
