### ISSUE TITLE
Please add a way to upload fonts into Elementor

### ISSUE THREAD

**Issue by bendqh** [pojome/elementor#3909]
Please add a way to upload fonts into Elementor.

Why? Well, It's just comfortable.

## Note

Please allow uploading fonts already available in Elementor. Here's an example why: Elementor loads OpenSansHebrew font from outside, but I want to load it locally from its local version for faster loading (or else I'll lose GPSI score).

**Comment by bainternet** [comment]
You mean like this: https://elementor.com/custom-fonts/

**Comment by bendqh** [comment]
Maybe, but I see it's only pro, so I can't test at the moment.
