### ISSUE TITLE
Global Element Presets and Global Colors

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#3912]
There's a major issue I have with Elementor that's putting me off adopting it for anything other than quick one page designs. There's no way to set default styles and options to keep things consistent and easy to maintain. I was hoping this would be addressed with the Elementor Pro 2.0 update, seeing how it's bringing many theming like options, but it's not looking likely.

What I really want to see is an option to save presets for element options that are saved globally. So have a 'default' preset that's used whenever you drag out a fresh element, as well as a dropdown to select any other presets you have saved. Update a preset = updating that element throughout the whole site.

Say I'm building a site for a client and their style doesn't allow for rounded buttons. The best I can do within Elementor is save a styled button as a global element and drag that out and then detach it before editing the label. But now what happens when the client decides they love round stuff and I need to tweak the button design throughout the site? - the answer is going through every single elementor entry and manually editing each button one by one - ouch!  Now, if we had global presets this would take me 2 minutes to alter the preset and I'm done.

The other thing I'd like is for the Color Picker colors to be globals. Manually changing every element throughout a site when the colors need tweaking would be a nightmare.

**Comment by bainternet** [comment]
I merged this issue with  #965, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
