### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Flipback8** [pojome/elementor#3913]
As an Elementor user, these are the features that are important to me and I would like to see implemented. 

I would like to see the "My Templates" section look like the New Block section. It would give us the ability to make our own visual blocks.

it would also be nice to have the ability to import all sections we or a third party like Katka make by importing just one file. (Visual Blocks)

I was also thinking that it would be nice to have a blocks section in the Elements section that allows us to see the blocks from there and just drag and drop the sections.

I would also like to see an online cloud all Elementor users can sign into and have blocks we can all share with a visual representation. (You get what you share)

and lastly, I would like to see an integration of the Image Element that allows you to add images directly from free image databases like Pixabay, Unsplash, etc.

Thanks for taking the time to read this! I really like Elementor and would be excited if any of these features were implemented. Thanks again!

**Comment by bainternet** [comment]
@Flipback8 

Thanks for the suggestions,

Some of these are already possible, like import many templates as a zip file at once.

Some we do have plans already in these areas and some we feel should be in a 3rd party plugin territory.

again thanks for the suggestions.
