### ISSUE TITLE
BUG align icon in select my template

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#3914]
See 
Yes - add my style

![2018-03-27_09-54-29](https://user-images.githubusercontent.com/5197026/37949309-1ed13d94-31a5-11e8-950f-59cbb08145d3.png)

**Comment by arielk** [comment]
Fix for v2.0.1 https://github.com/arielk/elementor/commit/c59ff463fafc222a368f7393098de29edd65cba0

Thanks for your report!
