### ISSUE TITLE
Store control value globally. - Feature Request

### ISSUE THREAD

**Issue by sandeshjangam** [pojome/elementor#3915]
## Description
I want store control value globally like in "get_option" or somewhere else. But It can be accessible to all instance of the same widget and can be changed from any instance of the widget. It will useful for a user to change API key from the editor itself.

Ex. recaptcha
1. Form widget with Recaptcha.
2. Recaptcha needs API key to be working.
3. Text field for recaptcha API key. ( Value will store globally for all instance of form widget  ).
4. Use can change this key from any instance of form widget.

**Comment by bainternet** [comment]
@sandeshjangam 

We use the native WordPress options API for things like that:

![screen shot 2018-03-28 at 12 05 54](https://user-images.githubusercontent.com/660572/38019512-685ed06c-3280-11e8-92b7-39a32cb8b207.png)


Other then that, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
