### ISSUE TITLE
SLIDER control doesn't work in REPEATER causes errors while editing

### ISSUE THREAD

**Issue by yawalkar** [pojome/elementor#3919]
## Description

When you add a slider control in repeater, and try to edit the element, it throws an error and causes the edit panel to not display any setting like this - 

![image](https://user-images.githubusercontent.com/4975549/37954382-3f691932-31c3-11e8-8297-40790617ec3f.png)

When I removed the slider control from repeater, it started working fine. 

## Steps to reproduce

- Add SLIDER control to tabs ( repeater )
- Add few tabs and update page ( you'll see errors in console )
- Reload the page and then try to edit the tabs element and add new tab. Here's what you'll get - 

![image](https://d2ffutrenqvap3.cloudfront.net/items/2y0V0N3U3X1K3K310X1A/Screen%20Recording%202018-03-27%20at%2001.43%20PM.gif)

## Environment

I used WordPress TwentySixteen default theme and only Elementor 2.0.0 is active. Then added "Slider" control to tabs repeater like this -

```
[
	'name' => 'slider_test',
	'label' => __( 'Slider in Repeater', 'elementor' ),
	'type' => Controls_Manager::SLIDER,
	'default' => [
		'size' => '10',
	],
	'range' => [
		'px' => [
			'min' => 10,
			'max' => 50,
		],
	],
],
```

**Comment by bainternet** [comment]
@yawalkar 

Not sure a slider control is supported in a repeater, can you provide the full code, including the hook used to add the control?

**Comment by yawalkar** [comment]
I just added the above code after the `tab_content` field in Tabs widget like in the following screenshot - 

![image](https://user-images.githubusercontent.com/4975549/38076781-481ddff8-3354-11e8-83c8-c26c53824d5e.png)

**Comment by bainternet** [comment]
@yawalkar

First of you really shouldn't change core plugin files because you will lose these changes on updates.
As for the slide inside the repeater, sadly its simply not supported.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by yawalkar** [comment]
I wasn't adding anything to the core. Just to demonstrate the issue to you, I added it to core tabs and checked if it works there or not.

No worries, I can setup custom control for it, so all good 👍

**Comment by dbjpanda** [comment]
+1
