### ISSUE TITLE
Feature Request - Post Feature Image As Section Background

### ISSUE THREAD

**Issue by richcoy** [pojome/elementor#3920]
One feature that Anywhere Elementor has that I'm missing from Elementor 2.0 is the ability to set the Post Feature Image as the background for a section. This allows me to change the hero section of each post by adding the Feature Image as the background behind the Post Title. This makes for a nice effect. 
Please consider adding this.

**Comment by bainternet** [comment]
@richcoy 

This is something we have planned but it will probably won't make it to Pro V2. so next version maybe.

thanks for the feedback.
