### ISSUE TITLE
Repeater control not working in Document Settings

### ISSUE THREAD

**Issue by MjHead** [pojome/elementor#3922]
## Description

If you try to add Repeater control into Document type settings, you'll get error in JS - http://prntscr.com/ix0ik1. Currently Repeater control is used in widgets only. But maybe in future or for third party add-ons such option will be needed.

## Steps to reproduce

For example you could try to add Repeater control into default Elementor\Core\DocumentTypes\Post (elementor/core/document-types/post.php) settings - http://prntscr.com/ix0lpn. Than open any static page in Elementor editor and click on Settings - http://prntscr.com/ix0ma1. And you will get an error - http://prntscr.com/ix0ik1

Thanks :)

**Comment by ryanlabelle** [comment]
HI @MjHead , would you please share your code for adding custom controls to the Page Settings panel? We've done this in the past but since 2.0 our existing actions don't add our controls to Page Settings as seen here: https://github.com/pojome/elementor/issues/3928

Best regards,
ryan

**Comment by MjHead** [comment]
Hi @ryanlabelle. I found this bug when playing around with new DocumentTypes API. I created new document type with custom settings then registered it on `elementor/documents/register` hook. Code for new document type are similar as for default `Elementor\Core\DocumentTypes\Post` in **elementor/core/document-types/post.php**, just with other controls.

**Comment by bainternet** [comment]
Currently, this repeater control is not supported in `document settings`, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by ryanlabelle** [comment]
Thanks @MjHead :)
