### ISSUE TITLE
WordPress Widgets don't show saved settings on front-end.

### ISSUE THREAD

**Issue by zefflubrano** [pojome/elementor#3930]
## Description

Any regular widgets (WordPress widgets, not elementor specific widgets) save, yet do not show updated values in the input/select fields. So whenever I drag a widget, fill it out and update it, the widget saves my settings and it displays correctly, but upon a reload or later access the front end editor shows the default widget values. Just to be extra clear on this, it DOES save, but the 'saved values' are not being displayed in the fields, instead the default values for the widget are shown.

I checked if this was also happening when adding widgets via the: Appearance > Widgets menu, but this was functioning as how it should. 

I went inside some of my own widgets and saw that in the function: public function form($instance) the $instance variable returned an empty array (in the front-end editor of  Elementor), so that would explain why it can't show the saved settings. I can't recall if Elementor (Free) always acted like this.

Is this a bug or a limitation of the free version?

## Steps to reproduce

1. Drag a Wordpress widget in the editor.
2. Fill out some of the settings.
3. Save it.
4. Reload/Refresh the page and the widget shows the default values again.

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 5.6.32
	PHP Max Input Vars: 1000
	PHP Max Post Size: 10M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.4
	Site URL: **************
	Home URL: **************
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: ***********
	Debug Mode: Inactive

== Theme ==
	Name: Whimsy Art Theme
	Version: 0.1
	Author: Zenigma
	Child Theme: Yes
	Parent Theme Name: Themify Ultra
	Parent Theme Version: 1.8.9
	Parent Theme Author: Themify

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

== Active Plugins ==
	Anywhere Elementor
		Version: 1.0
		Author: WebTechStreet

	Contact Form 7
		Version: 5.0.1
		Author: Takayuki Miyoshi

	Easy Testimonials
		Version: 3.1.1
		Author: Gold Plugins

	Elementor
		Version: 2.0.1
		Author: Elementor.com

	Elementor Addons & Widgets
		Version: 1.1.5
		Author: ThemeIsle

	Flamingo
		Version: 1.8
		Author: Takayuki Miyoshi

	Hide Admin Bar
		Version: 0.3.9.1
		Author: Shelby DeNike

	Image Cleanup
		Version: 1.9.2
		Author: Robbert Langezaal, Simon Duduica

	Jetpack by WordPress.com
		Version: 5.9
		Author: Automattic

	MailChimp for WordPress
		Version: 4.2
		Author: ibericode

	NavMenu Addon For Elementor
		Version: 1.1.2
		Author: ThemeIsle

	Themify Portfolio Post
		Version: 1.0.7
		Author: Themify

	WP Maintenance Mode
		Version: 2.1.2
		Author: Designmodo

**Comment by KingYes** [comment]
Thanks

**Comment by zefflubrano** [comment]
You're welcome and thank you for the quick fix!
