### ISSUE TITLE
403 error when updating / Elementor 2.0.1

### ISSUE THREAD

**Issue by samuelcerezo** [pojome/elementor#3935]
Hi,

When updating post in Elementor 2.0.1 give me 403 (Forbidden) error. I think this happens only on posts that have iframe / svg in its content.

Reverting to Elementor 1.9.8 works fine.

**Comment by bainternet** [comment]
@samuelcerezo 

Do you have Mod Security enabled? if so please try disabling it and see if you still get it. If the issue still exists, then please contact our support @elementor.com so they can investigate better.

thanks.

**Comment by welltom** [comment]
I had the same 403 error problem but only when I used the form widget. Inside the error logs I saw this: `ModSecurity: Access denied with code 403 (phase 2).`

Disabling ModSecurity (disable the SQL injection detection webfilter) is indeed a solution, but that firewall is there for a reason. So is there maybe an other (more secure) solution for this?

**Comment by dinooz-web-solutions** [comment]
Just deactivate security plugin until update page content.
Activate security plugin once complete editing.
[- dinooz web solutions](http://www.dinooz.com/)

**Comment by MuhtasimMahim** [comment]
YEAH I ALSO FACED THE SAME PROB IN IFRAME ONLY. BUT ENABLING LEARNING MODE IN WORDFENCE WORKED FOR ME NO NEED TO COMPLETELY DISABLE IT.

**Comment by alabius** [comment]
I have same issue. In my case, it happened to the clone i made with versionpress. The production is working fine, but the clone has issue with changing anything in elementor. A fix will be appreciated

**Comment by jadeye** [comment]
Had the same issue with `Wordfence security` plugin.
Just disabled it, updated and re-enabled it back...worx!!!
