### ISSUE TITLE
[bug] shadow for post widget cut off

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#3940]
when using post widget the shadows of the single boxes dont extend beyond the sides of the section container and being cut off.
see attached screenshot left and right sides of outer post boxes:

https://imgur.com/a/7G2TW

might be corrected when adding appropriate padding to the widget, but thats no real solution. the shadows should be visible anyways ...

EDIT: everythings up to date - GP and Elementor

**Comment by bainternet** [comment]
Thanks for reporting, should be fixed in next version.

**Comment by dasigna** [comment]
fixed in pro2.0 beta3 :)
