### ISSUE TITLE
UI suggestion (z-index, negative margins)

### ISSUE THREAD

**Issue by brandadesign** [pojome/elementor#3942]
Hi guys!
When I using z-index or negative margins can become a problem to select the desired section.
The ideal would be to have a **list of sections** in the left panel, **selectable with mouse and with a double click enter in its settings.**

Here a video of issue: [https://www.dropbox.com/s/lrryszp6t36myhy/VID_20180313_211457.mp4?dl=0]
Thank you so much and sorry for my english!

**Comment by bainternet** [comment]
I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
