### ISSUE TITLE
OceanWP theme incompatability. 

### ISSUE THREAD

**Issue by MediaMaidCFL** [pojome/elementor#3943]
I'm suddenly having problems with the elementor preview loading with OceanWP. 

I've tried rolling back to v1.9.8, which was working fine up until yesterday. 

I even tried rolling back to 1.8.12, that didn't work either. With each upgrade and downgrade I've cleared my cache & cookies. It didn't help, nor did using an Incognito window. 

The site uses PHP 7.1, and wordpress v 1.9.4, with OceanWP v1.5.9  

I have invested $$ into OceanWP extensions and just recently purchased Elementor pro to use on other sites. Please help, the site was just a couple tweaks away from deploying, I don't want to be out on money and time! 

Here are the errors I'm getting: 
![screenshot 2018-03-28 11 10 16](https://user-images.githubusercontent.com/37877332/38042491-88c93f66-3282-11e8-988d-ef168e064b6d.png)
![screenshot 2018-03-28 11 32 05](https://user-images.githubusercontent.com/37877332/38042492-88e4ba2a-3282-11e8-8fbc-4ab7831c8408.png)

**Comment by bainternet** [comment]
please try:

- make sure both Elementor and Elementor pro (if you have it) are updated to the last version.
- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists then please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by MediaMaidCFL** [comment]
Hi Raz. I have resolved this issue, thank you.
