### ISSUE TITLE
The preview could not be loaded issue 

### ISSUE THREAD

**Issue by uxdesignit** [pojome/elementor#3944]
Hi,
We try to use $this->get_settings() with  get_script_depends() to load depending script for some case on  new custom widget. Something like these lines of code bellow:
```PHP
public function get_script_depends() {
		$settings = $this->get_settings();
		if($settings	==	'set1'){
			return [ 'script1' ];
		}else{
			return [ 'script2' ];
		}
 
	}
```
But when we try to edit page with  elementor, it show a popup with the message:  **The preview could not be loaded.** 
Can you give me few words to help us solve the issue. 
Thanks in Advances
Harry

**Comment by bainternet** [comment]
@uxdesignit 

When `get_script_depends()` is called `$settings` will not always be available and it should be an array, not a string. Check your error log and you will probably see it there.

get_script_depends should be used without conditions, and simply return an array, so if you must have a condition, you should enqueue the script manually.

**Comment by uxdesignit** [comment]
Hi,
Thanks a lot for your message.
We still need it work with condition to create widget with dependency jQuery file. Such as with jQuery unite gallery... it will load depending js file to run corresponding gallery. Ex: Nested, Side, Tile...

Can you tell me where the error log file locate  ?!

Sorry for the example code, it's exactly is something like this :
public function get_script_depends() {
		$settings = $this->get_settings();
		if($settings['condition']	==	'set1'){
			return [ 'script1' ];
		}else{
			return [ 'script2' ];
		}
 
	}
But the issue occured when we use $settings = $this->get_settings(); with get_script_depends() 
public function get_script_depends() {
		$settings = $this->get_settings();
              //the issue "The preview could not be loaded." will be raise after this
               //other code ...
Thanks 
Harry
}

**Comment by notrealdev** [comment]
Hi @uxdesignit How did you solve your problem?
