### ISSUE TITLE
Elem 2 warning message

### ISSUE THREAD

**Issue by EdKnep** [pojome/elementor#3946]

**Comment by EdKnep** [comment]
**Warning: array_merge(): Argument #2 is not an array in /home/lititzho/public_html/wp-content/plugins/elementor/includes/managers/controls.php on line 562**

I have no idea what this means. Just began appearing this morning. I'm not a coder, just a user (beta tester).

**Comment by bainternet** [comment]
@EdKnep are you running the latest version 2.0.2?

**Comment by mawk-khan** [comment]
Same warning for me also I'm using latest version 2.0.2 only

**Comment by bainternet** [comment]
please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by EdKnep** [comment]
Bainternet,

Yes, 2.0.2.

The problem is caused by the plugin **Addons for Elementor Pro (Version 1.8.6** which I believe was updated just before the error message began appearing). Too bad since I use the LiveMesh widgets.

**Comment by EdKnep** [comment]
Bainternet,
PS - problem persists even when changing themes from GeneratePress to TwentySeventeen

There are no visible issues in terms of the appearance and functionality of the page being designed (other than the error msg while editing in Elementor).
