### ISSUE TITLE
Elementor's Frontend CSS should be enqueued before Theme's CSS

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#3948]
Hi there,

Looks like Elementor's frontend CSS is being enqueued after theme's CSS. In your current `/includes/frontend.php` (v2.0.2), you attach the enqueue action (`wp_enqueue_scripts` hook) on the `init()` function (which is called upon `template_redirect` hook). This would make Elementor's CSS enqueued after the theme's CSS.

This is a non-standard behavior. Theme's CSS should be able to override any plugin's default CSS, therefore the plugin's CSS should be enqueued before the theme's CSS.

**Comment by bainternet** [comment]
> This is a non-standard behavior.

This statement is simply wrong.

**Comment by daviedR** [comment]
> This statement is simply wrong.

???? Any reference???!!

Most themes enqueue theme's CSS in the `wp_enqueue_scripts` hook in their `functions.php`.

Elementor enqueues its CSS so late, because it add the `wp_enqueue_scripts` action inside `template_redirect` hook. This makes Elementor CSS comes after theme CSS.

Do you think all themes that want to override your default CSS have to use higher priority number??!!

**Comment by daviedR** [comment]
Most themes would use default priority number which is 10. Elementor also use the same priority number, BUT it's added so late (on `template_redirect`), this makes Elementor's CSS enqueued last, after all other CSS (including theme's CSS). That's what I think is not standard.

I think theme's CSS should be able to override plugin's default CSS in any manner.

In current situation, theme developers HAVE TO use higher priority number (e.g. 11) to make sure that Elementor's CSS enqueued before theme's CSS. I am pretty sure most themes use default priority number (10) to enqueue their theme's CSS.
