### ISSUE TITLE
Role Manager section not displaying/function as expected in WP dashboard 

### ISSUE THREAD

**Issue by reachdigitalaus** [pojome/elementor#3949]
In WP Admin - Role Manager section ( wp-admin/admin.php?page=elementor-role-manager ). My dashboard not displaying correctly or showing any options to tick like I have seen other dashboards. 

![screenshot-www reachdigital com au 2018 03 29 18-34-14](https://user-images.githubusercontent.com/17354511/38075977-e1dcaf22-337f-11e8-876c-90af405f5a7e.jpg)

**Comment by bainternet** [comment]
@reachdigitalaus 

Seems like you are missing the new CSS and JS try reinstalling the plugin and clearing browser/server cache.

**Comment by reachdigitalaus** [comment]
Thank you @bainternet . Did all that. Now I can collapse the arrows but syle still missing. Note I only deactivates and deleted elementor and not elemento pro.


![download](https://user-images.githubusercontent.com/17354511/38077100-7aa31a22-3383-11e8-94ad-963628d3f079.jpg)
