### ISSUE TITLE
Slider mobile image background 

### ISSUE THREAD

**Issue by webig** [pojome/elementor#3951]
Hi,
I was wondering if there is a possible way, to change background image or its position in a mobile/tablet layout. In many cases I get the problem, that photo/illustration used in desktop layout of slider, is cropped absolutely bad, so it sometimes shows any of "image/graphics" informations, because of the crop.
I can't see some css adjustments, if you do, any help is appreciated a lot.
Thank you a lot.

jd.

**Comment by bainternet** [comment]
Currently, this feature is not supported, only via custom CSS, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
