### ISSUE TITLE
Feature request : Portfolio Widget (PRO) more interactions

### ISSUE THREAD

**Issue by HHCarmen** [pojome/elementor#3957]
I would like in the portfolio widget more elements of interactions. Currently we can just show or not the title of the post. I would like for example to display on the image in addition to the title an excerpt from the post, the name of the author... as proposed some Wordpress plug-in like Essential Grid (premium version, argh!). Or have the title on the image and in hover more information that appears on the image (e.g.: https://www.tenk.fr/ or http://telemouche.com/)
Thank you

**Comment by bainternet** [comment]
@HHCarmen 

The Portfolio Widget would probably be merged with the posts widget so they can both benefit from each other's features.

Also, we plan to provide tutorials on creating skins so you could do whatever you want.

thanks for the suggestions.
