### ISSUE TITLE
Request for hooks in widget data fields (text, image, video etc...)

### ISSUE THREAD

**Issue by nelsonguda** [pojome/elementor#3959]
## Description

This is a feature request for hooks that developers can use to add new dynamic fields to widgets. I worked with Beaver Builder for a while, and one excellent feature of the builder was the option of pulling data from an ACF or user meta field into their various widgets. Beaver Builder had a lot of problems, and those data connections were limited. 

If Elementor widgets had hooks for data input, we could design our own functions to pull data from a variety of different dynamic sources. For example, a user meta field that has an image ID or an array of IDs. Or a field that contains a text area or url. 

This would make Elementor very powerful as a driver for dynamic websites.

Thank you!

**Comment by bainternet** [comment]
@nelsonguda 

this is something that is tested right now in the [Elementor Pro 2 beta]( //github.com/pojome/elementor/issues/3826 ) you are more than welcome to try it out.
