### ISSUE TITLE
Editor's preview "data-elementor-device-mode" doesn't respond to Responsive Mode.

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#3960]
Hi,

Elementor adds `data-elementor-device-mode` attribute to the `<body>` tag. When window is resized, the attribute value would change accordingly. This works perfectly on frontend.

Not in editor's preview. The attribute doesn't respond to the `Responsive Mode` changes from Editor.

Please fix.

**Comment by bainternet** [comment]
@daviedR 

Please provide steps to replicate

**Comment by daviedR** [comment]
You can try in your editor,

Try to switch into Tablet or Mobile view, and then you can inspect the preview `<body>` tag. You will notice that the `data-elementor-device-mode` attribute doesn't change into the selected view, it remains on `desktop`.

**Comment by bainternet** [comment]
@daviedR 

We can't replicate, the attribute is changed according to the selection. are you inspecting the body of the preview iframe? or the the main body?

the attribute and changes are applied to the iframe.

**Comment by bainternet** [comment]
Well, Like I said 

> we can't replicate, the attribute is changed according to the selection.

Thats is why i asked for steps to replicate in the first place.

please try:
- Make sure you are running the latest stable version of Elementor ( and Elementor Pro if you have it).
- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

**Comment by daviedR** [comment]
You are right, looks like there is a conflict with my theme's javascript.

Thanks!
