### ISSUE TITLE
Feature Request - Menu & links to embedded pages within Elementor interface

### ISSUE THREAD

**Issue by Paul00777** [pojome/elementor#3962]
The wordpress menu at the top of the browser web page now gives access to embedded pages (ie templates within the page referred to with shortcodes). This is so helpful.
![2018-03-30_9-42-50](https://user-images.githubusercontent.com/25090333/38120947-c8df6cd8-33fe-11e8-96a0-af924d1efbbb.jpg)

A similar feature within the Elementor interface would be very helpful. Maybe this could be in the form of an icon that displays next to the shortcode e.g. [elementor-template id="165"] (@).  So clicking on the icon (@) opens a new tab to edit this template.

Thanks.

**Comment by bainternet** [comment]
@Paul00777 

We have that already in ELementor Pro but for Template location level, and not section or widget.

thanks
