### ISSUE TITLE
New Widget: Select Box with links 

### ISSUE THREAD

**Issue by scguy** [pojome/elementor#3963]
Was trying to create a select box where a user clicks an item and is directed to that page/post. Started with a form widget and select box, but then i realized this only sends an email to me rather than acting as a nav function.

So that's the idea for a new widget.

My purpose was so visitors could select their state, and be directed to a specific page for that state. But surely a lot of people could use this. The advantage over a nav bar widget (using just one button) is that the select box opens over top of the container background with a scroll bar on the side, whereas the nav button dropdown stretches the container I place it in. (On mobile it opens in a lightbox type of appearance.)

Also with the select box, you could offer the option of a "go" button for the user to click when he selects a page/post rather than just selecting a list item. 

It should have the option of target="_blank" too.
It should also have the option of the placeholder "Select a State" (or whatever) not being linked.

A third-party plugin, like Formidable Forms can do this, but I don't want to buy another plugin and mess up the efficiency of GP and Elementor. (Plus, FF said they can do it with the "go" button; I'm not sure if that plugin would allow it without the go button.)

I found a bit of jquery code to do it, but since Elementor didn't make it, I can't easily customize it like my other buttons, nor do I know if it's current or even quality code.

`<form action="dummy" method="post"><select name="choice" size="1" onChange="jump(this.form)"><option value="">Select a State...</option><option value="https://mysite.com/alabama/">Alabama</option><option value="https://mysite.com/alaska/">Alaska</option><option value="https://mysite.com/arizona/">Arizona</option></select></form>`

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, this is something that can be done easily with some custom coding using the form widget or if you are up to it then even better simply [create your own custom widget ](https://developers.elementor.com/creating-a-new-widget/)
Thanks for the feedback.

**Comment by scguy** [comment]
I wrote in about this and wasn't advised that I could somehow customize the
existing form for this. Would I use just css?

**Comment by kennethwombat** [comment]
Please make this widget, I really want this too.

**Comment by STHLMWebDesign** [comment]
Yes, please make this!

**Comment by sparkbold** [comment]
These form components should be included in elementor or pro version (Select, Checkbox, Multiple Select, etc). It tooks so much time to customize/styling. I am a pro user and would love to continue subscription if they are included in the theme.

**Comment by amindiary** [comment]
Needed

**Comment by jacqdesign** [comment]
Would love this function.
