### ISSUE TITLE
[Feature Request] Menu Item Active when in View Pane

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#3965]
On a "single page site" or with 'in-page' navigation all ID sections (#thisIsA Section) that are included in the menu as Custom Links are shown as active. So on a single page with five sections in the menu all would be shown as active. It would be great to have an option for menu items to be flagged to be "Only Active In the View Frame". Then on a single page site, the active menu section would only be highlighted when it was in the view pane particularly important if a sticky menu is used.

**Comment by bainternet** [comment]
@nickdgreen 

Elementor Nav menu uses the native WordPress `wp_nav_menu` function, meaning the native function is the one responsible for settings the `active/current item` classes and not elementor.

maybe try following this tutorial: https://www.youtube.com/watch?v=M1mWq3kuX7s

**Comment by bainternet** [comment]
Sorry, @nickdgreen I just figured out what you are asking for.

Anyway, I don't see this being implemented in Elementor anytime soon.

thanks for the suggestion.
