### ISSUE TITLE
Warning: array_merge(): Argument #2 is not an array in ... elementor ... controls.php on line 562

### ISSUE THREAD

**Issue by anjo-branco** [pojome/elementor#3966]
Warning: array_merge(): Argument #2 is not an array in D\xampp720\htdocs\elem\wp-content\plugins\elementor\includes\managers\controls.php on line 562

Warning appears between header and content, only in edit mode with elementor, not in view mode.

Elementor 2.0.3
Theme Beaver Builder 1.6.4.1 (newest); test: it happens as well with gp-theme, newest version, but appears before the header.
System: Windows 10 Enterprise, Version 1709, Build 16299.125
Xampp Version 7.2.0 with php 7.2.0
Version 65.0.3325.181 (Offizieller Build) (64-Bit)

**Comment by KingYes** [comment]
Which widgets you used there?

**Comment by anjo-branco** [comment]
I used those widgets:

slides
image carousel
titel (various times)
text editor (various times)
image
portfolio

BUT:
I think that I didn´t change anything during the last days, but I played around - the warning doesn´t appear any more here.

But shows with others in the elementor facebook group:

"Manuel Syed on version 2.0.3 I get this visible error on front-page: 
Warning: array_merge(): Argument #2 is not an array in /home/wp_u23u5q/ms.world/wp-content/plugins/elementor/includes/managers/controls.php on line 562".

Sorry that I cann´t help more.

Best regards, Anjo Branco.

**Comment by gho5t7m** [comment]
Hello, bro
I had the same error with creating my own widget for Elementor after the last update. While adding the function REPEATER, I left the default field empty. This led to an error. Having removed this I solved this problem.
This article can help you.
https://github.com/pojome/elementor/blob/master/docs/content/controls/_repeater.md
Field default is better not to leave blank!

**Comment by ikardi420** [comment]
> Hi, gho5t7m,
> 
> thank you for your explication.
> 
> In my case it happened that the warning doesn´t appear any more here, after playing around a bit - but I think that I didn´t change anything during that time. But, the message is gone:

Still I have this issue , how can i resolve this ?
