### ISSUE TITLE
Anyone having this double editor after latest update?

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#3967]
Browser- Google Chrome. 
![edit post bari wordpress](https://user-images.githubusercontent.com/7946657/38148254-7a0ab292-3477-11e8-87ee-1c52c6a0b5c5.png)

**Comment by bainternet** [comment]
@webangon 

Do you see any errors in your console?

**Comment by webangon** [comment]
Sorry it caused by 3rd party plugin, wpide and no console error .
