### ISSUE TITLE
Can't not update/save draft 

### ISSUE THREAD

**Issue by WeAreUnique** [pojome/elementor#3968]
Version: 2.0.3 with Pro version: 1.15.6

I just updated to v2.0.3 (from 1.9.8) and when I add new post > edit with elementor > do something and press Save Draft or Publish. I got: `Server error (403 error)`

I open Inspect and go to Console tab. I saw this error: 
`POST    https://myurl/wp-admin/admin-ajax.php 403 ()`

If I rollback to v1.9.8 (from Element tools) everything work fine.

P/s: Already clear cookie, data, and try on Safari, Chrome browser

**Comment by WeAreUnique** [comment]
I figure it out.

It's conflict with Wordfence plugin (require add `request.body[actions]`  to `Whitelisted URLs`)

Thank you

**Comment by LennartdeNeef** [comment]
I have the same problem, can't edit any page. 
Everytime I try to update or edit anything I get Server Error (403 Forbidden)

I already deactivated wordfence, but still have this issue. Any ideas?
