### ISSUE TITLE
Full Width Issue - After following 40-full-width-template DOC

### ISSUE THREAD

**Issue by gotenpro** [pojome/elementor#397]
I've followed this to perfection ->(https://docs.elementor.com/article/40-full-width-template) 
But i'm still not able to make the website full width. I have also check the code and everything.. Made the green background test.. Everything.. My knowledge end, can you provide some help to my issue?

**Comment by gotenpro** [comment]
Some prints of the situation!


![captura de tela 2016-08-10 as 11 33 08](https://cloud.githubusercontent.com/assets/20951165/17557939/6dfe8fa0-5eef-11e6-899e-4ae41b05e91e.png)

![captura de tela 2016-08-10 as 11 32 49](https://cloud.githubusercontent.com/assets/20951165/17557937/6dd02228-5eef-11e6-957a-59db72cc2c24.png)

![captura de tela 2016-08-10 as 11 37 43](https://cloud.githubusercontent.com/assets/20951165/17557938/6dfb9372-5eef-11e6-9d9d-85bf265bfcf5.png)

![captura de tela 2016-08-10 as 11 43 07](https://cloud.githubusercontent.com/assets/20951165/17558025/ad19745c-5eef-11e6-884f-7d003d39ed5d.png)

![captura de tela 2016-08-10 as 11 43 19](https://cloud.githubusercontent.com/assets/20951165/17558026/ad38e1de-5eef-11e6-978f-206bd5dc50df.png)

**Comment by boazha** [comment]
Hi,
Sorry for the delay.
Please try to replace your CSS with this:

`.full-width {
	width: 100%;
}

.site-inner {
    max-width: 100%;
}

.site-content {
    padding: 0;
}

header#masthead,
footer#colophon {
	margin: 0 auto;
	max-width: 1320px;
}
 
.entry-content {
		margin-right: auto;
		margin-left: auto;
}

@media (min-width: 56.875em) {

	.no-sidebar .entry-content {
		margin-right: auto!important;
		margin-left: auto!important;
	}
}

@media screen and (min-width: 44.375em) {

	.entry-content {
		margin-right: auto;
	}
}

`

Let us know if it worked.

Best,
Boaz

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by Himaghiri** [comment]
Hi I have found an alternate method. You could install Blankslate theme customize it using custom css to create full width complete blank page templates. Please have a look at this tutorial video https://www.youtube.com/watch?v=DvcAIrDIz1s
