### ISSUE TITLE
css issues on mobile devices

### ISSUE THREAD

**Issue by RHSpencer** [pojome/elementor#3970]
I have built two elements for a page. 
One is shown on desktops and the other is for mobile devices and tablets. 

In the preview mode, everything is good.
However, on actual devices, the following elements don't work.

1. Text Color.
2. Section background image. 
3. Text margin and padding. 

url: fringestatus.com
home page. 

screenshot of elementor mobile preview: http://prntscr.com/iyunho

I hope this will be fixed. 

Thanks!

**Comment by bainternet** [comment]
@RHSpencer 

Seems like there are way too many JavaScript Errors on that page, most of which come as a "cross-origin" issue, please try fixing that so Elementor could load correctly.

If that still doesn't solve the issue, Please contact our support at support @elementor.com for guidance in resolving this issue.
