### ISSUE TITLE
[Feature Request] Use featured image as background in Single post templates

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#3971]
In the Pro Beta3 there is no dynamic option for background images. I would like to be able to use a Post's featured image as the background in the hero section of my Single post templates. 

Will this be added? It really kind of limits the design options when creating Single post templates.

**Comment by bainternet** [comment]
@avermat 

Elementor pro 2 is still in beta and we have already got this requested many times. So yeah it will be implemented, just not in v2.

thanks

**Comment by Ver3** [comment]
Any news on the arrival date of this feature? I'm really missing it and am trying to decide to wait a little longer or go with the (somewhat complicated) workaround.

**Comment by kkri** [comment]
+1 I Created a well-done post template, but if that feature was available this should be perfect, allowing to overlay any widget on the image background. Is it near to come? I see other users asking for it in the Elementor Facebook community. My site will be online in a week and I'll wait some other day if it will be done not too far. Thank you

**Comment by bellamystudio** [comment]
Yep, pretty desperate for this feature here too - any idea of ETA? Is there any way we can 'hack' it for now - in the exported JSON file for example?

**Comment by drank** [comment]
+1

**Comment by drank** [comment]
Dear @bainternet,

when you said that this will not be implemented in v2 did you mean that it will be implemented in v3 or simply that it will not be implemented in v2.0.0 (and will in some later v2 version of Elementor)?

Thanks.

**Comment by themedleb** [comment]
+1

**Comment by oshibobo** [comment]
+1

**Comment by arielk** [comment]
This is now available in v2.0.13

Enjoy and thanks for the feedback!

**Comment by oshibobo** [comment]
Thank you @arielk

**Comment by kkri** [comment]
Wow! Thank U @arielk and EPro staff!

**Comment by Ver3** [comment]
> Hi,
> I would like to be able to use a dynamic content -> Post's featured image as a page/post background of my Single post templates.
> Will this be added?

It's already there! Check the docs for details ;-)

**Comment by xcolomer** [comment]
dynamic -> featured image as a background of SINGLE/PAGE templates?
Sorry, I don't see that feature :-(

![image](https://user-images.githubusercontent.com/12183886/50104848-5c7c2580-022b-11e9-8617-f7bbd9a1cf85.png)

**Comment by Ver3** [comment]
You need Elementor Pro. When installed select a column, go to the style tab, click "Dynamic" then "Featured Image" and you're all set. Have fun! ;-)

**Comment by Ver3** [comment]
@xcolomer See my other reply, you need Elementor pro for this. Also, select a COLUMN fist.

If this still fails, you'll have to contact Elementor Support. The only other way I could help you is using Anydesk.

**Comment by xcolomer** [comment]
Hi Vedi,
I have Elementor Pro, but on  options for SINGLE/PAGE templates -> page-background -> dynamic -> featured image, this option doesen't exist :-(

**Comment by henrique-voni** [comment]
Hello, i'm trying to display an ACF image field as background of a section, but it's not showing up. See: https://prntscr.com/mx2r2t

**Comment by Ver3** [comment]
> Hi Verdi,
> I have Elementor Pro, but on options for SINGLE/PAGE templates -> page-background -> dynamic -> featured image, this option doesen't exist :-(

Only just now noticed you mentioned me. Is your problem solved by now? If so, how did you solve it?

**Comment by Ver3** [comment]
> Hello, i'm trying to display an ACF image field as background of a section, but it's not showing up. See: https://prntscr.com/mx2r2t

Hi @henrique-voni I had the same problem when using an svg-file. Might that be your case too? Did you already solve the problem and if so, how?

**Comment by henrique-voni** [comment]
@Ver3 no, i'm not using svg. I am trying to use a .png as background on a product (woocommerce) post type section.

**Comment by henrique-voni** [comment]
And it's not working yet.

**Comment by Ver3** [comment]
@henrique-voni Works fine on my end. Sorry to say this, but you need to go through the motions. This means:

1. Disable all other plugins, clear all caches (brwoser, WP, server) and see if that solves it.
2. If not, contact Elmentor Support. They're really great.
