### ISSUE TITLE
[Feature Request] Eyedropper tool

### ISSUE THREAD

**Issue by nikifffa** [pojome/elementor#3972]
Proposal. In the practice of creating pages, one tool is very lacking - eyedropper tool (analog tool in Photoshop or Corel Draw, which transfers the properties of one element to another). For example, such a tool would be useful if there are 10 different headings, and you need to change the color of all 10 elements at once. Now for this you need to change the properties of each element, but with a eyedropper tool I would simply single out the color of one and made 9 quick mouse clicks - and it's ready! I'm waiting for such an innovation in the following updates.

**Comment by bainternet** [comment]
I merged this issue with  #1479, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
