### ISSUE TITLE
Why can't we remove the last item of repeater block?

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#3973]
It seems to remove last item we need to remove widget completely . 
![1](https://user-images.githubusercontent.com/7946657/38165489-ffae8496-3535-11e8-8b91-f9da624420c2.JPG)
![2](https://user-images.githubusercontent.com/7946657/38165490-00058bba-3536-11e8-9061-a76666e65d88.JPG)

**Comment by bainternet** [comment]
This depends on the widget, but if it's a custom widget then simply set the `prevent_empty` parameter of the repeater to false:

```PHP
$this->add_control(
	'repeater_id',
	[
		'label'         => __( 'My Repeater', 'text-domain' ),
		'type'          => Controls_Manager::REPEATER,
		'fields'        => $repeater_fields,
		'prevent_empty' => false,
	]
);
```
