### ISSUE TITLE
Remove Elementor from sidebar in /wp-admin

### ISSUE THREAD

**Issue by rainwater11** [pojome/elementor#3974]
I am new to WordPress and Elementor, so please cut me some slack.

How can I remove the link to Elementor (/wp-admin/edit.php?post_type=elementor_library) in the admin sidebar.

Thanks!

**Comment by bainternet** [comment]
@rainwater11 

the same you would remove any other WordPress admin menu items:
https://wordpress.stackexchange.com/questions/136058/how-to-remove-admin-menu-pages-inserted-by-plugins
