### ISSUE TITLE
loading tab content only when clicked via ajax?

### ISSUE THREAD

**Issue by xerfilstyx** [pojome/elementor#3979]
Thanks for awesome plugin and comes straight to the point:

When using tab widget in elementor, contents of each tabs seem to be loaded fully. It's pretty bad when contents in tabs are long & complex - especially using **shortcodes** to implement section or template in each tabs.

So to ask: Is it possible to load the specific tab content only when users click it? I've googled it and AJAX seems the way to go(see [this link](https://stackoverflow.com/questions/48239740/ajax-tabs-for-wordpress-that-loads-and-runs-different-shortcodes-when-user-chang) ), but I'm not familiar with how-to apply it to elementor or something.

Any comments are appreciated. Or hopes this feature will be in future updates.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by bentalgad** [comment]
This would be amazing. the tabs also lack a lot of basic features, such as (template as content, style options, icon in title, smooth height change and more...)

**Comment by notrealdev** [comment]
+ 1 billion

**Comment by jazir5** [comment]
+1

**Comment by marowi85** [comment]
+1

**Comment by MadhouseSigma** [comment]
+1

**Comment by wursterje** [comment]
+1

**Comment by dr-waterstorm** [comment]
+1

**Comment by HalgrimThadeus** [comment]
+1

**Comment by osman-kocak** [comment]
up

**Comment by hernands** [comment]
+1

**Comment by muneeb-ashraf** [comment]
+2
