### ISSUE TITLE
[Feature Request] CSS Hero Compatiblity

### ISSUE THREAD

**Issue by snowliondev** [pojome/elementor#398]
CSS Hero plugiin let's you edit all the css from your theme and various plugins. Adding compatibility for a plugin is a simple javascript file. Just naming the CSS paths and what they control. After that CSS Hero can style any element. 

http://www.csshero.org/developers/kb/#welcome

**Comment by joshmarom** [comment]
Elementor gives you a great amount of control over the styling of the elements in your designs.
You can control the colors and and typography, both on a global level and on a per-element level.
On the Elementor settings page you can choose to disable Elementor Color Palettes and Elementor default fonts, allowing your theme to dictate these settings.
You may also add classes to widgets and sections in your designs and write css that targets them.
This level of flexibility, essentially allows you to achieve pretty much any desired result.

Given all that, we are not sure that CSS Hero is a good match for a flexible page builder like ours.
However, we appreciate your suggestion and we will look into it.

**Comment by arielk** [comment]
Thanks to the amazing team of CSS Hero there is a full compatibility with Elementor, you are welcome to try for yourself: http://www.csshero.org/plugins/elementor/
