### ISSUE TITLE
[Enhancement] Entrance Animation Numeric Duration

### ISSUE THREAD

**Issue by dtronvig** [pojome/elementor#3982]
Back in June, on [#558](https://github.com/pojome/elementor/issues/558), People were asking for numeric controls for Entrance Animation Delay and Duration.

A numeric control for Entrance Animation _Delay_ was added in Version 1.5, but the choices for Entrance Animation  _Duration_ are still just "Slow", "Normal" & "Fast". If you get into that, you may as well offer choices for animation-timing-function, though that isn't a big concern for me.

In the meantime, what would be the best way to override those Duration settings, either setting the duration for individual elements or redefining the site-wide duration associated with, say, "Slow"? (presumably via custom CSS)

Thanks,
Drew

**Comment by bainternet** [comment]
@dtronvig 

Each element you give an entrance animation gets a CSS class `.animated` and depending on the duration you choose it gets a second class `.animated-fast` or `.animated-slow` ( normal speed gets no special class).

So if you want to override these you can use the widget selector plus the animated and animated-slow/fast ex:
```CSS
selector.animated.animated-slow{
    -webkit-animation-duration: 5s;
    animation-duration: 5s;
}
```
