### ISSUE TITLE
[Question] picker_options for DATE_TIME control

### ISSUE THREAD

**Issue by notrealdev** [pojome/elementor#3983]
Hi, are there any examples of DATE options? I can not see the options
```php
$this->add_control( 'timer', array(
    'label' =>  esc_html__( 'Date', 'domain' ),
    'type'  =>  Controls_Manager::DATE_TIME,
    'picker_options' => array(
        'dateOnly' => true,
    )
) );
```

**Comment by bainternet** [comment]
@notrealdev 

The Date time control uses [flatpickr](https://flatpickr.js.org/) library and the `picker_options` accepts most if not all of the option that flatpickr can accept. here is the docs: https://flatpickr.js.org/options/

**Comment by notrealdev** [comment]
It's worked, thank you!!
