### ISSUE TITLE
Load Editor on Frontend. - Suggestion

### ISSUE THREAD

**Issue by sandeshjangam** [pojome/elementor#3984]
## Description

Right now elementor editor is loading on the backend and using an iframe to fetch the actual page.

Problem: In editor mode shortcode compatibility problems. WooCommerce shortcodes.

Solution: It would be great if we can load elementor editor on the frontend. It will solve shortcode problem very easily. No need to give custom compatibility for shortcodes in the editor.

**Comment by bainternet** [comment]
@sandeshjangam 

The editor used to be loaded in the front end but then we had `cross-origin` issues which made it impossible to work on multiple environment configurations.

We do have something else we are thinking about and that is to load the editor on the front-end via jsonP or a rest endpoint, but that's not going to be implemented anytime soon.

as for the shortcode compatibility, We will work something out soon.

thanks for the suggestion.
