### ISSUE TITLE
JS API - Get generated stylesheet for an item

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#3985]
Hello,

This is a question regarding the JS part of Elementor.

I am searching for a way to get the generated stylesheet for a widget.

If I hook to "panel/open_editor/widget/(widget_name)", I receive the panel, the model and the view objects.

In the panel object, I can browse to "control.currentView.options.controls" which contains all the widget controls along with a "selectors" property containing a Mustache code to generate a style.

In the view, I see a "controlsCSSParser" object with many interesting functions.

How to mix all these things together to get the generated style (background-color: red; color: black;, for eample) for a widget? Elementor has to generate it at some point to send it to the preview.

**Comment by bainternet** [comment]
@tristanleboss 

This is not yet documented and not a real proper API (yet) and the final stylesheet is actually generated by PHP and not JS : https://github.com/pojome/elementor/blob/master/includes/css-file/post-css-file.php

**Comment by tristanleboss** [comment]
Thanks. I think I was unclear.

When I put an "Icon" widget, rotate it and change font size, Elementor does generate (without PHP... at least, there is no Ajax request being done) a stylesheet for this widget and insert it in the preview iframe DOM.

Example :
![image](https://user-images.githubusercontent.com/1431508/38203045-1f2606dc-369e-11e8-9937-8058501bd9f4.png)

I was interested to get this stylesheet, be informed when a change is done and eventualy be able to trigger a change.
