### ISSUE TITLE
[Feature Request] masonry columns

### ISSUE THREAD

**Issue by bodhi1970** [pojome/elementor#3987]
Would be great to have a possibility for masonry columns.
Sometimes I like to have two columns of text with different height besides of each other and no blank space below one. Or an image and a text which belong together and the text is longer than the image, but I want to have more text for the next column below that first image.
It would be helpful for different things.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by hiviz** [comment]
+1

**Comment by phillipaust** [comment]
+1

**Comment by JonathanBaldwin8** [comment]
+1

**Comment by genjonakasone** [comment]
bump and +1
