### ISSUE TITLE
{Feature Request] A Complete Website Set for Editing and Translation Services

### ISSUE THREAD

**Issue by fery379** [pojome/elementor#3989]
Hi
There are numerous websites for English thesis and article editing and proofreading, and English translation services, and most of them look aweful.

Would really appreciate it if you could make  a complete website which offers the following services:
1. (English) Editing and Proofreading of articles, thesis, and books.
2. (English) Translation of articles, books, etc.
3. Plagiarism Detection Service for articles and thesis.

Regards,

PS: I am a pro customer, and I opened a ticket about this, but I was asked to request this here.

**Comment by bainternet** [comment]
@fery379 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
