### ISSUE TITLE
elementor 2.0.3 add template not loading 

### ISSUE THREAD

**Issue by jc71292** [pojome/elementor#3991]
after updating to version 2.0.3 and clicking on add template it wont load, it stays stuck on the same screen, but when i revert to the earlier version 1.9 something it works, but wont give me the blocks option :(

when i open console i get this error, not sure if its a known bug
TypeError: s.categories is null

Errors: | TypeError: s.categories is null 			at https://www. .com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.3 - 2:27439 			2018-04-03 03:40 +00:00 			x 7 times  		TypeError: Cannot read property 'indexOf' of null 			at https://www. .com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.3 - 2:27459 			2018-04-03 03:09 +00:00 			x 2 times  		TypeError: s.categories is null 			at https://www. .com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.3 - 2:27439 			2018-04-03 03:02 +00:00 			x 2 times  		TypeError: Cannot read property 'indexOf' of null 			at https://www. .com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.3 - 2:27459 			2018-04-03 02:54 +00:00  		TypeError: s.categories is null 			at https://www. .com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.3 - 2:27439 			2018-04-03 02:53 +00:00 			x 12 times
-- | --

maybe someone knows when the update will come out?

**Comment by bainternet** [comment]
@jc71292 

Please contact our support at support @elementor.com for guidance in resolving this issue.
