### ISSUE TITLE
Action to add menu Item in Elementor Global settings

### ISSUE THREAD

**Issue by sandeshjangam** [pojome/elementor#3992]
## Description
Actions to add custom menu in Elementor Global settings
[https://goo.gl/3iNZps](https://goo.gl/3iNZps)

I want to add a custom menu and the settings panel. I guess there are no actions at this moment.

It would be great if you provide actions for it.

**Comment by bainternet** [comment]
I merged this issue with  #1614, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
