### ISSUE TITLE
Feature Request: Configuration option to allow scripts to be loaded in wp_head instead of wp_footer.

### ISSUE THREAD

**Issue by AndrewPenry** [pojome/elementor#3994]
In almost all cases, you would not want to do this. But in some rare edge cases, dumping the scripts into the head (so they are blocking) instead of at the bottom solves some problems.

My edge case is that I am importing the head template of Magento 2 site. Magento 2 uses a modified version of RequireJS. So any script that is loaded after RequireJS  which includes an anonymous define function will cause problems. One solution would be rewriting WP to use require (which some have suggested). A much simpler solution is to just load all of WP and Elementor's scripts into the head as blocking scripts before Magento's. This ensures that all of WP's stuff is loaded before RequireJS gets in there.

I've modified frontend.php to register the scripts to the head, and enqueue them in the constructor. Most scripts end up in the head this way, although a few (like slick) still end up at the footer. This seems to work, and I can, of course, redo these changes when upgrading. It would be nice to have a configuration option for this.

**Comment by bainternet** [comment]
@AndrewPenry 

You can't, simply because you don't know which scripts you will need( which ones are used and required by the widgets) on that page until you get to the footer.

unless you can come up with a different solution??

**Comment by AndrewPenry** [comment]
I changed all the wp_register_script functions in frontend.php to use false for $is_footer. For example:

```
wp_register_script(
    'jquery-slick',
    ELEMENTOR_ASSETS_URL . 'lib/slick/slick' . $suffix . '.js',
    [
        'jquery',
    ],
    '1.8.1',
    false
);
```

Just by doing this, it let's me move these to the head by adding:
```
function mytheme_enqueue_scripts() {
    wp_enqueue_script( 'jquery' );
    wp_enqueue_script( 'elementor-frontend' );
    wp_enqueue_script( 'jquery-slick' );
}
add_action( 'wp_enqueue_scripts', 'mytheme_enqueue_scripts' );
```
to my own theme's functions.php

Yes, this means in the theme I have to load every script that I might need to move to the head, loading things like slick.js on every page even if it's not used in each page. It also loads all the Elementor scripts on all pages, even if they were not made with Elementor. But that's the price, I guess, of trying to combine WP and Magento. 

More importantly, changing $is_footer from true to false only provides me the OPTION of putting these things in the head. If I don't enqueue it in the theme, it still gets put in the footer. This is because functions.php does not enqueue them until wp_footer is called.

**Comment by AndrewPenry** [comment]
Sorry, that isn't quite enough. Doing it just that way means that elementorFrontendConfig is not written to the page. I'll let you know as I continue to work on a solution.

**Comment by AndrewPenry** [comment]
OK, I got it working, it took 3 changes, all in frontend.php:

First, I did the modification from above where I changed all the wp_register_script calls to use false for $is_footer.

Second, I made a new method:
```
    public function head_enqueue_scripts() {
        $post_id = get_the_ID();
        $document = Plugin::$instance->documents->get_doc_for_frontend( $post_id );

        $nq = function (Element_Base $element) use (&$nq) {
            $element->enqueue_scripts();
            foreach ( $element->get_children() as $child ) {
                $nq($child);
            }
        };
        // Run through every element in the page and enqueue the scripts needed for those elements.
        $data = $document->get_elements_data();
        foreach ( $data as $element_data ) {
            $element = Plugin::$instance->elements_manager->create_element_instance( $element_data );
            if ( ! $element ) {
                continue;
            }
            $nq($element);
        }

        // Enqueue the general Elementor scripts.
        $this->enqueue_scripts();
    }
```

This method makes it possible to enqueue scripts you need at any time that get_the_ID() is able to return the id.

Third, I added this modification to init():

`            add_action( 'wp_enqueue_scripts', [ $this, 'head_enqueue_scripts' ] );
`

Like so:

```
    public function init() {
        if ( Plugin::$instance->editor->is_edit_mode() ) {
            return;
        }

        add_filter( 'body_class', [ $this, 'body_class' ] );

        if ( Plugin::$instance->preview->is_preview_mode() ) {
            return;
        }

        $this->post_id = get_the_ID();
        $this->_is_frontend_mode = true;

        if ( is_singular() && Plugin::$instance->db->is_built_with_elementor( $this->post_id ) ) {
            add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_styles' ] );
            add_action( 'wp_enqueue_scripts', [ $this, 'head_enqueue_scripts' ] );
        }

        add_action( 'wp_head', [ $this, 'print_fonts_links' ] );
        add_action( 'wp_footer', [ $this, 'wp_footer' ] );

        // Add Edit with the Elementor in Admin Bar.
        add_action( 'admin_bar_menu', [ $this, 'add_menu_in_admin_bar' ], 200 );
    }
```

This seemed like a good place to put it, because init() already is doing a logic check to see if the page is built with Elementor. Putting it here means the Elementor scripts only get loaded on Elementor pages. I think it would be possible to make this a configuration option that is checked by init(). 

Once again, I realize that wanting to force the scripts into the head is a fringe case, but it seems the only way to get Magento 2 and WP to work together.

**Comment by bainternet** [comment]
@AndrewPenry 

What can i say, its not something we are going to implement, it simply goes against every page optimization guide out there (loading all the scripts in head).


Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
