### ISSUE TITLE
*Post Widget (Feature Request)*

### ISSUE THREAD

**Issue by soccernatic** [pojome/elementor#3995]
On the post widget, can you add more features to the image style? The same ones you have for a single image.

Here is what it has currently: https://prnt.sc/j09gan

I`m unable to add a boarder neither shadow to it like the ones in the image widget here: https://prnt.sc/j0bntz

Please please please, could you add those features?

Btw, I`m using the post skin classic!

**Comment by dudaster** [comment]
@soccernatic try this plugin for the time being: https://wordpress.org/plugins/ele-custom-skin/

**Comment by soccernatic** [comment]
Thank you, I will check it out!

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
