### ISSUE TITLE
Limiting REPEATER field

### ISSUE THREAD

**Issue by sarvesh-mru** [pojome/elementor#3997]
On implementing a custom widget for wordpress for the REPEATER field, is there a way to specify a limit for the field like for e.g, it can be added 8 times and after that you can't add new item.

**Comment by bainternet** [comment]
Sadly, not there is no way (yet anyway). So currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by bdthemes** [comment]
Please add this feature, it will be really helpful for all.

**Comment by dzmarc** [comment]
Any update on this? Our team is making the transfer over from ACF to Elementor and used this heavily in our process.

**Comment by Sharifur** [comment]
> Please add this feature, it will be really helpful for all.

i also need it very badly

**Comment by alarstyle** [comment]
Also need this feature!

**Comment by mhennessie** [comment]
How is this still not a feature? This seems kind of important when developing custom widgets.

**Comment by alarstyle** [comment]
+1

**Comment by amincharoliya** [comment]
In many scenario it is required to limit the maximum items in repeater. I hope this feature request will be taken seriously.

**Comment by VlooMan** [comment]
+1

**Comment by FlippFlopps** [comment]
+1

**Comment by hakikz** [comment]
Essential feature. I hope this feature request will be taken seriously.

**Comment by sarahspr** [comment]
Also need this!

**Comment by amir-zrn** [comment]
still nothing...
people need this

**Comment by jared-rice** [comment]
I am very surprised this is not already in place. Anyone knows a workaround for now?

**Comment by alweso** [comment]
In need of this!

**Comment by zohaib87** [comment]
feature needed.

**Comment by afrid1719-hbwsl** [comment]
I also need this feature.

**Comment by Adwait2196** [comment]
I also need this feature.

**Comment by Vibhav-Salelkar** [comment]
Feature needed

**Comment by pranayhbwsl** [comment]
Essential feature, it should be considered.

**Comment by beyondsagency** [comment]
+1 we need it

**Comment by tavonline** [comment]
+1

**Comment by thecodude** [comment]
Please add this feature.

**Comment by rtmhbwsl** [comment]
Please add this feature.

**Comment by kiddtang** [comment]
+1 we need it

**Comment by filipecsweb** [comment]
+1

**Comment by filipecsweb** [comment]
There's a way around where we can use the `default` key and set as many blank values as we want. Each value counts for an item. In this case I've also made use of the key `item_actions` to prevent the user from deleting and adding more items.

```
$this->add_control(
	'slug',
	array(
		'label'        => 'Label',
		'type'         => Controls_Manager::REPEATER,
		'fields'       => $repeater->get_controls(),
		'item_actions' => [
			'add'       => false,
			'duplicate' => false,
			'remove'    => false,
			'sort'      => true,
		],
		'default'      => [ // In my case I needed 3 items by default, no less no more.
			[],
			[],
			[]
		],
	)
);
```

See more about `default` on https://developers.elementor.com/elementor-controls/repeater-control/

**Comment by easin-xs** [comment]
+1 we need it

**Comment by u562** [comment]
+1

**Comment by shahadul878** [comment]
1+ we need

**Comment by ILYASSBENHADDA** [comment]
So important feature, I hope to work on it soon.

**Comment by YahyaTec** [comment]
Necessary feature, Consider to add.

**Comment by comicrebels** [comment]
1+ important feature

**Comment by jbehshad** [comment]
+1 important features for me as well

**Comment by amandine16** [comment]
me too

**Comment by frits000000** [comment]
I managed to do this using a Jquery script i made

`jQuery(window).on('elementor:init', function () {
    
    var repeaterControlName = 'Repeater_Limited'; // Change this to your repeater control name


    elementor.hooks.addAction('panel/open_editor/widget', function (panel, model) {

        var settings = model.get('settings');
        var MAX_ITEMS = settings.get('repeater_limit'); // ensure to create a controll in your block with the name repeater_limit or if chosen change this to your controll namev

        if (settings.has(repeaterControlName)) {
            var repeaterControlSelector = '.elementor-control-' + repeaterControlName;
            var addButtonSelector = repeaterControlSelector + ' .elementor-repeater-add';


            jQuery(document).on('click', addButtonSelector, function (event) {
                var repeaterItems = settings.get(repeaterControlName);
                if (repeaterItems.length > MAX_ITEMS) {
                    alert('You can only add a maximum of ' + MAX_ITEMS + ' items.');

                    repeaterItems.pop();
                    settings.set(repeaterControlName, repeaterItems);

                    
                    event.preventDefault();
                    return false;
                }
            });
        }
    });
});
`

**Comment by matt-camp** [comment]
I'm currently coding a masonry cta component and needed a limit on the repeater. This is not perfect but an easy CSS only solution.

Just replace 'ctas' with the name of your repeater, and the nth-child with your limit.

`
.elementor-control-ctas:has(.elementor-repeater-fields-wrapper > :nth-child(7)) .elementor-button-wrapper {
	display: none;
}
`
