### ISSUE TITLE
Is there any group controls dos?

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#3998]
I am looking for group controls dos or files to find them.

I see you already defined group controls like this.

Group_Control_Border

`
$this->add_group_control(
			Group_Control_Border::get_type(),
			[
				'name' => 'pgn_btn_border',
				'selector' => '{{WRAPPER}} #results .javo-map-box-morebutton',
			]
		);
`
Where can I find them? any docs or files?

Thank you!

**Comment by bainternet** [comment]
there you go: 

https://developers.elementor.com/elementor-controls/#Group_Controls
