### ISSUE TITLE
Nav menu issue

### ISSUE THREAD

**Issue by davideisenstadt** [pojome/elementor#4001]
We're having an issue with the new Elementor. Our "Home" text on our nav menu keeps resetting itself to "Auto Save...". See screenshot.
![screen shot 2018-04-04 at 12 33 55 pm](https://user-images.githubusercontent.com/38080314/38321277-1bc9b61a-3805-11e8-838f-f625da3c96b7.png)

**Comment by odeland** [comment]
Same issue happened to us. While doing back-end work on a page, it seems the revision overwrote our page title.

**Comment by arielk** [comment]
Thanks for reporting, fixed in v2.0.2 please update.
