### ISSUE TITLE
Feature Request: Need Link Hover Effect in Icon List Element

### ISSUE THREAD

**Issue by rahul6388** [pojome/elementor#4004]
In Icon List, links are not getting highlighted after hovering over them. Icon list links should get highlighted after hover over thek like normal link.

**Comment by ramiy** [comment]
@rahul6388 

The **Icon List** widget **Style** tab allows you to style the **Icon** and the **Text**. You have two separate sections. Each section allows you to set the **Regular Color** and the **Hover Color**.
