### ISSUE TITLE
Feature Request: Refresh interface sidebar

### ISSUE THREAD

**Issue by Paul00777** [pojome/elementor#4007]
A button to press to refresh the interface, without effecting editing.
With multiple pages open for editing a widget created in one page is not available in another, unless the page is saved and refreshed through the browser refresh option.

**Comment by bainternet** [comment]
@Paul00777 

You mean refresh the preview??

**Comment by Paul00777** [comment]
Thank you for checking with me.

There is a refresh button on the Add Template >> Library template window.
But not so on the left hand sidebar.
So if I have added a global widget on another page, I can't refresh my
current interface page to be able to see it. I have to save my work, then
refresh the page - losing my revisions.


Paul Tottle
+86-185-1606-2704
________________

“We live on a razor's edge. From one instant to another, any of us can
regress to yesterday's mindset or connect with an emerging future
possibility.”  -  Otto Scharmer

**Comment by bainternet** [comment]
Thanks for clarifying,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
