### ISSUE TITLE
[Bug] Font Awesome missing new prefixes. Request for the 4>5 shim to be added.

### ISSUE THREAD

**Issue by LukeFlego** [pojome/elementor#4008]
[See this link - https://fontawesome.com/how-to-use/upgrading-from-4](https://fontawesome.com/how-to-use/upgrading-from-4)

**My scenario:**
Brand icons (Facebook, LinkedIn, Twitter, Instagram) are being generated with the incorrect prefix, and therefore show an animated exclamation/question mark error icon.

The shim is needed to resolve this.

**Comment by bainternet** [comment]
@LukeFlego 

We do have plans to upgrade to FA 5 but until then we don't officially support FA5 so just make sure to enqueue the shim manually.
