### ISSUE TITLE
Hold Shift and arrow up/down to increment/decrement values by 10

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#4009]
In some apps (Photoshop, Chrome Inspector), one is able to focus on a number field, hold the Shift key then arrow up/down to increment/decrement values by 10. See the attached GIF. This would be a handy addition to the editor, IMO.
![elementor_steps](https://user-images.githubusercontent.com/1729832/38399598-a386bc4e-398e-11e8-8e49-58d1a2205918.gif)

**Comment by bainternet** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.
