### ISSUE TITLE
Feature Request: Wire-Frame Hide content while selecting

### ISSUE THREAD

**Issue by Paul00777** [pojome/elementor#4010]
One of the most frustrating things while editing is needing to select a section that is under another section. If there are multiple layers this becomes very difficult to access the selection handle.

One solution could be a wire-frame button in the sidebar. So that a simple click changes all content to a wire-frame around each section & widget. The content would disappear that covered any handles. This option would be solely to give easy access for selecting elements, but it would be so helpful.

**Comment by Paul00777** [comment]
For example, I just duplicated a section. However I then spent 10 minutes trying to get access to the duplicate selection handle. Actually I'm still trying to do it!

**Comment by Paul00777** [comment]
When duplicating an item the duplicate's handle can be inaccessible under other content. Another solution here would be to transfer focus to the duplicate automatically on copy.

**Comment by bainternet** [comment]
@Paul00777 

We are thinking about improving the UX by a navigation panel or breadcrumbs with a combination of context menu.

I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
