### ISSUE TITLE
Possibility to open portfolio images in lightbox

### ISSUE THREAD

**Issue by fixioneers** [pojome/elementor#4013]
Hi,

As for now we can't open images in the pro portfolio in a light box; they'll only open as a single post. It would be great to have the option to open these images in a light box. Because the portfolio offers filtering features which the galleries don't offer. Many clients demand the possibilities to filter their work as well as open it in a lightbox. Thanks!
Anne

**Comment by dasigna** [comment]
second this.

... apart from that:
it would be really nice if the possibilities of the portfolio widget could be expanded - and @fixioneers leads me back to a thought of mine where there would be more (hover) styling possibilities, and one of them might be to have the choice to open the referring post _or_ a bigger (featured?) image, represented by two different icons on hover possibly :)

**Comment by bainternet** [comment]
I merged this issue with  #3318, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by S8creative** [comment]
Hello, I am new around here, and found this post about the "portfolio" options that are missing.
I actually encountered the exact same problem as fixioneers, and was wondering if a solution was found. ?
Thanks!

**Comment by ryonwhyte** [comment]
Any update on this in here. Would be really nice to have
