### ISSUE TITLE
Enhancement: display Elementor in user language, not site language

### ISSUE THREAD

**Issue by ramonztro** [pojome/elementor#4017]
Major part of my sites are in brazilian portuguese, but me and my team prefer to use Elementor in english. Even with our profile settings set to english, Elementor still shows up in portuguese, which is the language set for the site. It would be great if Elementor showed in english.

OBS: If there is any workaround for this, I'ld be happy to know how to implement.

**Comment by CursiveQ** [comment]
@ramonztro  - I had the same thing happening... my workaround was to just delete the Brazilian Portuguese language translation files for Elementor in you wp-content folder. 

Elementor will then revert back to English.

Deleting the Elementor Lang files won't harm your website translations. It just effects the Elementor translations.

**Comment by ramonztro** [comment]
@CursiveQ Thank you for the tip! I was just testing that. Additionally, I'm adding the following snippet to my functions.php (for anyone interested):

`add_filter('auto_update_translation', '__return_false');`

**Comment by bainternet** [comment]
Seems like you already found a solution, and this has been answered a few times before here.

thanks for the feedback.

**Comment by ramonztro** [comment]
I think it would be good for Elementor to be that way natively instead of forcing users to workaround.
