### ISSUE TITLE
Webhooks - Forms

### ISSUE THREAD

**Issue by Fredtordjman** [pojome/elementor#4018]
Hi,

I would like to ask why we couldn't enter several url in the Webhook form field ?

Can you work on that ? 

Thanks a lot,

Fred

**Comment by bainternet** [comment]
If you need multiple webhooks triggered on submit you can use this snippet:

```php
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	$webhooks = [
		'HTTP://YOUR_WEBHOOK_URL1',
		'HTTP://YOUR_WEBHOOK_URL2',
		'HTTP://YOUR_WEBHOOK_URL3',
		'HTTP://YOUR_WEBHOOK_URL4',
	];

	foreach ( $webhooks as $webhook_url ) {
		wp_remote_post( $webhook_url, [
			'body' => $fields,
		]);
	}
});```

**Comment by Fredtordjman** [comment]
Ok thanks, but I don't know how to do use a snippet. Where should I copy that code ?

Thanks

**Comment by danncs** [comment]
Knowing where to use the snippet would be a great help :)

**Comment by danncs** [comment]
Hi, could you let me know exactly where to add this snippet please?

**Comment by coreaspect** [comment]
I would like to add to this for non coder Wordpress guys who come across this and find its not working... 

From the code example its missing the priority and the arguments parameters.

this will work:
`add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	$webhooks = [
		'HTTP://YOUR_WEBHOOK_URL1',
		'HTTP://YOUR_WEBHOOK_URL2',
		'HTTP://YOUR_WEBHOOK_URL3',
		'HTTP://YOUR_WEBHOOK_URL4',
	];

	foreach ( $webhooks as $webhook_url ) {
		wp_remote_post( $webhook_url, [
			'body' => $fields,
		]);
	}
}, 10, 2);`

@bainternet I believe this should be added to the following documentation here:
https://docs.elementor.com/article/281-form-faq

And there be a separation in the document for sending to multiple separate web-hooks and singular.

Thanks
