### ISSUE TITLE
Polylang Multilingual - easy page duplication ?

### ISSUE THREAD

**Issue by mojoomla** [pojome/elementor#402]
Hi,
I am using Polylang plugin to create a bilingual site.
The first and default language is English. 
All pages of the first language are already done in Elementor.
Now when I try to create the equivalent pages in second language using the Polylang plugin, the new page creation interface of Elementor does load but I have to start creating a fresh page.
Actually, for the second language pages,  I want to retain the same layout and graphic elements as they are for the first language pages and only translated the text.
Is there any way I can duplicate the first language Elementor pages and make Polylang accept them as second language equivalents ? 
Otherwise it  would be as good as creating two separate sites for the two languages.

Please let me know.

Thanks.

**Comment by joshmarom** [comment]
@mojoomla 
It seems like the new version of Polylang does not duplicate the original page's content when you create the translated page. This is the case regardless of wether you are using Elementor or not.

One way to deal with this issue is by using [Post Duplicator](https://wordpress.org/plugins/post-duplicator/) to create copies of your existing pages for the translation language.

In addition, It is worth mentioning that the new version of **Elementor**, which will be released tomorrow, Includes the **Template Library** - a new exciting feature, that allows you to easily save your page designs and reuse them. this feature could probably come in handy in situations like the one you are facing.

**Comment by mojoomla** [comment]
Post Duplicator creates a completely independent duplicate page and not its
related translation ready equvivalent within the Polylang page list.
So that won't do.

Eagerly looking forward to the new release of Elementor !

Thanks

**Comment by joshmarom** [comment]
After creating the "independent" duplicate page using **Post Duplicator** you can easily set it's language and associate it with an existing page.
![screen shot 2016-08-15 at 2 00 06 pm](https://cloud.githubusercontent.com/assets/2726148/17662814/fe5984b0-62f0-11e6-88c3-e6adbf7160f0.png)

**Comment by mojoomla** [comment]
Oh ! great !  I never new that.
The catch lies in typing the first few characters of the page title in the
Translations field of the Languages dialog before the list gets AJAX
populated.

Now the association has happened. But still in the page listing the two
pages are seen separately.
Any way that can be suppressed ?

**Comment by joshmarom** [comment]
This is the natural Polylang behavior as far as I know.

**Comment by vladislav-vladimirov** [comment]
This is the default behaviour, yes - but you have an option in the top black admin bar - "Show all languages". When pointing at it a dropdown will appear, allowing you to choose a single language to show. Once chosen, every piece of content in the admin will be filtered down to the selected language. You can always switch to another one, or to all languages.

**Comment by ilaxay** [comment]
Hi. How can I translate this into Spanish? Problema with widget "MENU CART" by ELEMENTOR There is no way to put custom text - buttons "SHOW CART" and "CHECKOUT" I need to translate to "VER CARRITO" and "COMPRAR"

**Comment by konstantinosftw** [comment]
Same problem with @ilaxay here. I use elementor pro's cart and I am not sure how to change the "SUBTOTAL", "SHOW CART" and "CHECKOUT" items to my language.

**Comment by Jaska** [comment]
https://github.com/aucor/polylang-copy-content

This plugin seems to solve the problem.

**Comment by palios23** [comment]
Hi. I have the same problem and i used the Post Duplicator Plugin but didn't work. It's like my css is not working. What i can do?
