### ISSUE TITLE
Created Custom Fonts sometimes go under regular posts, and are thus not useable

### ISSUE THREAD

**Issue by Aljook** [pojome/elementor#4021]
Elementor 2.0.3
Elementor Pro 2.0.0 Beta3
GP Premium 1.6.2
GeneratePress 2.0.2

Just before writing this I was able to add the fonts by just setting a name to an empty new font and saving. It would then open as a post edit window, but going back to Elementor - Custom Fonts, shows the created font. Then I could open it and add the ttf, woff, etc. 

A lot of times before this one however, I clicked add new font, added the name and font files, etc, then hit save, and it would just create a new post with the name in the regular posts page.

Alo

**Comment by bainternet** [comment]
Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by Aljook** [comment]
Well I got my situation sorted, just wanted to give you a heads up on possible issues.

**Comment by bainternet** [comment]
What was it?

**Comment by Aljook** [comment]
It's described in my 1st post...
