### ISSUE TITLE
How to use custom shortcode on my custom widget

### ISSUE THREAD

**Issue by princ-imran** [pojome/elementor#4025]
## Description
How to use custom shortcode on my widget. I am trying but not work.
here is my code: https://github.com/princ-imran/elementor-custom-widget

**Comment by bainternet** [comment]
@princ-imran 

Please describe which problem you've encountered. What caused the issue, and what did you expect to happen. Attach screenshots and related links to help us understand the issue in more detail.

Also provide  steps to reproduce.

**Comment by princ-imran** [comment]
Here is my plugin: https://github.com/princ-imran/elementor-custom-widget
`Group_Control_Typography::get_type(),
			[
				'name' => 'typography',
				'scheme' => Scheme_Typography::TYPOGRAPHY_4,
				'selector' => '{{WRAPPER}} .gallery-item .gallery-caption',
				'condition' => [
					'gallery_display_caption' => '',
				],
			]
		);`
Do not use on my plugin. When use it show this error: http://prntscr.com/j35sft
I am simple developer try to good learning if you help me.
Thank you

**Comment by princ-imran** [comment]
:::Problem solve:::
I am happy for elementor editor.
