### ISSUE TITLE
RTL Icon list alignment direction change

### ISSUE THREAD

**Issue by babstudio** [pojome/elementor#4026]
On the last update all icon lists on RTL sites moved to left alignment - 

The seperator line is aligned opposite to the icons and impossible to use. 

Had to change all sites manually - align icon list to the right again and remove the seperator lines from the icon lists

**Comment by bainternet** [comment]
@babstudio 

We cant replicate the issue, make sure you update to the latest version.

and please feel free to reopen if the issue persists and please provide more data with steps to replicate.
