### ISSUE TITLE
Feature Request: "Show/Hide condition"

### ISSUE THREAD

**Issue by yaquawa** [pojome/elementor#4032]
I know, this feature could be achieved by the `Widget Options` plugin([https://widget-options.com/widget-options-elementor-widgets-beta/](https://widget-options.com/widget-options-elementor-widgets-beta/)).

But I think everyone who loves elementor expects official support!

This nice little feature could make life so much easier. 
I'm wondering why the elementor team have not implemented this feature yet. There is no doubt that it's going to be a supercharge for the   elementor.

**Comment by bainternet** [comment]
@yaquawa 

We will look into it in the future if we see a large demand for it.

Thanks for the suggestion.
