### ISSUE TITLE
Add hooks to change default colors

### ISSUE THREAD

**Issue by jugheadeatsalot** [pojome/elementor#4035]
Would be great if theme developers can change default colors (i.e., Color Palette, Color Picker) using hooks.

**Comment by iamntz** [comment]
I didn't tested, but you _should_ be able to change the defaults like so:

```
add_filter('elementor/editor/localize_settings', function ($config) {
	$config['default_schemes']['color']['items'] = ['#ff0', '#f0f', '#0ff', '#00f'];
	return $config;
}, 99);
```

https://github.com/pojome/elementor/blob/master/includes/editor.php#L514
https://github.com/pojome/elementor/blob/master/includes/editor.php#L664

**Comment by jugheadeatsalot** [comment]
Missed that. Thank you.
