### ISSUE TITLE
BUG - widget template export/import

### ISSUE THREAD

**Issue by ravilrrr** [pojome/elementor#4036]
Hi.

1. Create page and insert widget "template".
2. Select in widget my template
3. Export template in 2 file. (page, column)
4. Import template in a new site.
5. Page imported, but in widget "Template" not selected my template.

**Comment by bainternet** [comment]
@ravilrrr 

This is not a bug, its simply how it works, a template on a site has a different ID than it has on a different site where it was imported, so the template widget can't guess what is the correct id.

thanks for the feedback

**Comment by ravilrrr** [comment]
I thought there was some internal ID of a template by which it can be link to a widget. 

Too bad there's no such thing. Very often you have to choose manually ((
