### ISSUE TITLE
Page Title and Page Template Change

### ISSUE THREAD

**Issue by anamwp** [pojome/elementor#4037]
Hello, 
I create a page in WordPress  then view and start editing again. Its ok. 
But when I start editing with Elementor Page builder its changes my  page title and page template. 
Here I record a video for you. Please take a look below video. 
It happens after I upgrade to the latest version of Elementor. 
Here is the video link
https://tx-snaps.s3.amazonaws.com/anam/screencast_2018-04-09_12-18-55.mp4

I appreciate fast reply and your caring support.
Thanks.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by notrealdev** [comment]
Same problem here :(
