### ISSUE TITLE
Bugs in elementor

### ISSUE THREAD

**Issue by avi-rav** [pojome/elementor#404]
Hi Kobi 
When you choose area that nested in other area you can't give to the inner area background or class & etc. the outer area get the bg-color or class!

Olso you can't edit text-editor

Avinoam

**Comment by joshmarom** [comment]
Hi Avinoam
I tried to recreate your issue but it seems to be working just fine on my end.

Use the "Columns" widget to create a section inside a section.
You shouldn't have a problem setting background properties or a class to the inner section.

Also, make sure you are using an updated version of the plugin.

Please update us if the issue has been resolved.
Josh :)

**Comment by avi-rav** [comment]
Hi josh
Thank you for your answer,
of course  i am using the latest version.
you have to change the name from area to column. right now they all have same name.

I still have a problem with edit text editor. can you check it please?!

![screen](https://cloud.githubusercontent.com/assets/17409237/17663924/04013c52-62f9-11e6-9684-50b12a77db75.png)
