### ISSUE TITLE
[Feature request] Preserve selected text and cursor position

### ISSUE THREAD

**Issue by kokers** [pojome/elementor#4045]
What makes WYSIWYG in native WP great, is that when you switch between visual and text, content you have selected or cursor position is saved. So you can continue to work where you left off. 

Video of that https://monosnap.com/file/Vkzxfl8K3uokNgUjjwi83zsM3bITjO 

This unfortunately doesn't work with WYSIWYG inside elementor. 

Furthermore, it would be awesome if the same was when switching form inline to side panel editing. For obvious reasons, options during inline editing are limited, so you have to quite often switch between them. Sure, you can start in side panel if you know you need to more advanced options, but in reality you don't always know if/when you will need this, so preserving selection/cursor position would make text formatting and editing much easier.

**Comment by bainternet** [comment]
that would be nice but not sure if it something that we will implement any time soon,

thanks for the suggestion.
