### ISSUE TITLE
Problem I have to fix every Elementor update

### ISSUE THREAD

**Issue by ericft** [pojome/elementor#4046]
Hi,

I have an issue with the this file I have to fix every update: 
/plugins/elementor-pro/modules/forms/fields/tel.php

1. I have to remove this hardcoded error text ( because our site is in french and we use jQuery Validator ):
'Only numbers and phone characters (#, -, *, etc) are accepted.', ''

2. And I have to add parenthesis in the tel field ( because I use a field mapping, ex: (514) 665-8889 ):
'0-9', '0-9()'

Is it possible add to #1 in a .pot file for translation or add in Elementor in the custom field?

And the #2 can you please add the parenthesis?

This will really help our workflow.

Thank you!

**Comment by iamntz** [comment]
As a workaround, you should be able to re-register your own class:

```
\Elementor\Plugin::instance()->widgets_manager->unregister_widget_type('tel');
\Elementor\Plugin::instance()->widgets_manager->register_widget_type(new MyOwnTelClass);
```
This new class is basically a copy/paste of the existing class, on which you can do your own tweaks.

**Comment by bainternet** [comment]
@ericft 

1) that string is already in wrapped in a translate-able function ( `__()` ) with the text domain of `elementor-pro` which you are more then welcome to contribute missing translated strings: https://translate.elementor.com/projects/elementor-pro/fr/default/

2) As of 1.5.4 version of Elementor Pro we have added support for parenthesis in tel field validation:

```PHP
if ( preg_match( '/^[0-9()#&+*-=.]+$/', $field['value'] ) !== 1 ) {
	$ajax_handler->add_error( $field['id'], __( 'Only numbers and phone characters (#, -, *, etc) are accepted.', 'elementor-pro' ) );
}
```

So you do not need to make any changes, and if you must then you should always try to use the API or action/filter hooks to make your changes and not update core plugin files.
