### ISSUE TITLE
Video Widget Doesn't Pull ACF Url or Text

### ISSUE THREAD

**Issue by stllrnet** [pojome/elementor#4047]
Since the release of the Beta versions of Elementor Pro, I couldn't get to work the ACF compatibility with the video widget. 

If I understand the integration well, basically I could add a custom field in my posts, and paste there the url for the youtube video I want. Then in the template for the CPT I just load a video widget and select ACF and then the name of the field that contains the url.

I've tried the types of field Text, Text Area and URL and none of them work. Also I've noticed that once I save the template, whenever I return to edit the template the buttons to edit the widget dissapear completely, that force me to delete the entire template and start over.

Problem with ACF: https://youtu.be/DZVtfiQa3Jw
Problem with Edit Buttons: https://youtu.be/jPBRi6zJqDE

**Comment by bainternet** [comment]
already reported, thanks.
#3826
