### ISSUE TITLE
After updating to 2.0.4 custom styles are not applied to elements

### ISSUE THREAD

**Issue by SeBastian4500** [pojome/elementor#4048]
## Description

I used the elementor page builder to create some elements with headline, text, image and applied specific styles for font-family, font-size, font-color, font-weight and so on. After updating to the newest version of page builder those custom styles are not applied on the website. They are visible in the edit and preview mode, but not on the live website. There are the default styles from the template used.

*Additional information:* The existing elements with custom styles remain as they were before the update. However, if one of these elements is copied, the custom styles are not adopted but the default values of the template are used. I hope this helps to understand the problem a little better.

## Steps to reproduce

1. Create a new section on a elementor page builder page
2. Create a new headline with the headline widget
3. Enter a headline and change font-size, font-family, font-weight
4. Save the page
5. View the edit mode and check if the changes are applied here - correct
6. View the preview mode and check if the changes are applied here - correct
7. View the page in live mode in the frontend of the website and check if the changes are applied here - fail

## Environment
			
== Server Environment ==
	
	Operating System: Linux
	Software: Apache/2.4.29
	MySQL version: 5.6.19
	PHP Version: 7.1.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	
	Version: 4.9.5

== Theme ==
	
	Name: Hestia
	Version: 1.1.71
	Author: ThemeIsle
	Child Theme: No

== User ==
	
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

== Active Plugins ==
	
	Elementor
		Version: 2.0.4
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 2.5.0
		Author: Codetic

== Debug ==
	
	Errors: There are no errors to display

**Comment by SeBastian4500** [comment]
@bainternet Yes, exactly. You edit a page with elementor and click on save (the green button). In the edit view and the preview from wordpress all looks fine, but in the frontend the styles are not applied. So yes publish / update publish.

**Comment by devbrn** [comment]
Same issue here

**Comment by bainternet** [comment]
please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And report back if the issue still persists.

**Comment by SeBastian4500** [comment]
@bainternet:
- Deactivating all plugins and activating them again does not work for me, the issue still is there even if all plugins beside Elementor is deactivated
- Switching the theme is not possible for me

**Comment by SeBastian4500** [comment]
The issue still exists even after updating to 2.0.6 today.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by pingram3541** [comment]
Curious.
