### ISSUE TITLE
slick sliders in inactive tabs

### ISSUE THREAD

**Issue by xerfilstyx** [pojome/elementor#4050]
A similar discussion was [here](https://github.com/kenwheeler/slick/issues/341) and elementor tab seems to have the same problem when loading carousel widget(which uses slick) contents via shortcode.

See [this gif(imgur gif)](https://imgur.com/a/PCBxM) for more specific : when tab is inactive - slick css defines its width to zero and when tab is active - problem occurs.

Any ideas to fix this?

**Comment by bainternet** [comment]
Yeah, its kind of a known "bug" with slick that has no way of knowing the width of the slider when its not visible. You can try to listen to the `focus` event of the tab title and "re-trigger" the slider, something like this:

```JS
jQuery( document ).ready( function( $) {
    $( document ).on( 'focus', 'elementor-tab-title-XXXX', function() {
          var slider = jQuery('.elementor-slides').slick('getSlick');
          slider. setPosition( 0 );
    } );
} );
```

**Comment by xerfilstyx** [comment]
Thanks for answers, but is .elementor-slides (class) exists in elementor? Since I can't find this on DOM I've changed the code to:

```
jQuery( document ).ready( function( $) {
$(".elementor-tab-title").on( "focus", function() {
          $(".elementor-image-carousel").slick('setPosition', 0);
    } );
}
```

But it isn't re-triggered when focus on title tab.

**Comment by xerfilstyx** [comment]
After googling a bit, slick('refresh') seems to work as intended but still delay (about .5sec) still persists.
