### ISSUE TITLE
Custom post loops in shortcodes "break" Elementor editor

### ISSUE THREAD

**Issue by emberlydigital** [pojome/elementor#4055]
## Description

I am trying to use a shortcode in Elementor to run a post loop and running into issues. I get the "Sorry, the content area was not found on your page" message as long as the shortcode and loop are present.

## Steps to reproduce

Try a post loop like this. It doesn't seem to matter if I remove the content piece of the loop.

```php
// Show latest job postings
function show_latest_job_postings(){
if(!is_admin()){

// WP_Query arguments
$cat_args = array(
'post_type' => array( 'job-posting' ),
'post_status' => array( 'publish' ),
'posts_per_page' => '3',
'category_name' => 'featured',
);
$args = array(
'post_type' => array( 'job-posting' ),
'post_status' => array( 'publish' ),
'posts_per_page' => '3',
);
// The Query
$cat_query = new WP_Query( $cat_args );
if ( $cat_query->have_posts()) {
echo 'We got em';
} else {
$query = new WP_Query($args);
// The Loop
if ( $query->have_posts() ) {
$html = '';
$html .= '<div class="archive-boxes">';
while ( $query->have_posts() ) {
$query->the_post();
$html .= '<a href="'.get_the_permalink().'">';
$html .= '<div class="archive-content">';
$html .= '<h3>'.get_the_title().'</h3>';
$content = strip_tags(get_the_content());
$html .= substr($content, '0', '210');
$html .= '<div class="archive-read-more">View Posting »</div>';
$html .= '</div>';
$html .= '</a>';
}
$html .= '</div>'; 

return $html;


} else {
// no posts found
echo "No latest job postings to show. Check back later!";
} 
}
// Restore original Post Data
wp_reset_postdata();
}
}
add_shortcode('latest_job_postings', 'show_latest_job_postings');
```

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.36
	PHP Version: 7.0.29
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: http://imperialdesigndev.emberlydigital.com
	Home URL: http://imperialdesigndev.emberlydigital.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Emberly Digital
	Version: 1.0
	Author: Emberly Digital
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.0.2
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 4.4.12
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 6.67
		Author: ServMask

	Duplicate Post
		Version: 3.2.1
		Author: Enrico Battocchi

	Elementor
		Version: 2.0.4
		Author: Elementor.com

	GP Premium
		Version: 1.6.2
		Author: Tom Usborne

	Gravity Forms
		Version: 2.2.6
		Author: rocketgenius

	Gravity Forms + Custom Post Types
		Version: 3.1.13
		Author: spivurno

	Jetpack by WordPress.com
		Version: 6.0
		Author: Automattic

	Safe SVG
		Version: 1.6.1
		Author: Daryll Doyle

	SG Optimizer
		Version: 4.0.4
		Author: SiteGround

	WPS Hide Login
		Version: 1.2.7
		Author: WPServeur, NicolasKulka, tabrisrp

== Debug ==
	Errors: There are no errors to display

**Comment by bainternet** [comment]
@emberlydigital 

A few possible issues with your shortcode:
- It is echoing in multiple places which is wrong, a shortcode should alway return a value.
- you should use `wp_reset_query();` instead of `wp_reset_postdata();` in your use case.
- You should always use `wp_reset_query();` and not only if a single condition is matched.

this seems to be working just fine:

```PHP
function show_latest_job_postings() {
	if ( ! is_admin() ) {
		// WP_Query arguments
		$cat_args = array(
			'post_type' => array( 'post' ),
			'post_status' => array( 'publish' ),
			'posts_per_page' => '3',
			'category_name' => 'featured',
		);

		// The Query
		$cat_query = new WP_Query( $cat_args );
		if ( $cat_query->have_posts() ) {
			$html = 'We got em';
		} else {
			$args = array(
				'post_type' => array( 'post' ),
				'post_status' => array( 'publish' ),
				'posts_per_page' => '3',
			);
			$query = new WP_Query( $args );
			// The Loop
			if ( $query->have_posts() ) {
				$html = '';
				$html .= '<div class="archive-boxes">';
				while ( $query->have_posts() ) {
					$query->the_post();
					$html .= '<a href="' . get_the_permalink() . '">';
					$html .= '<div class="archive-content">';
					$html .= '<h3>' . get_the_title() . '</h3>';
					$content = strip_tags( get_the_content() );
					$html .= substr( $content, '0', '210' );
					$html .= '<div class="archive-read-more">View Posting »</div>';
					$html .= '</div>';
					$html .= '</a>';
				}
				$html .= '</div>';
			} else {
				// no posts found
				$html = 'No latest job postings to show. Check back later!';
			}
		}
		wp_reset_query();
		return $html;
	}
}
add_shortcode( 'latest_job_postings', 'show_latest_job_postings' );
```

**Comment by daday-andry** [comment]
indeed, thanks <?php wp_reset_postdata(); ?> solved my problem
