### ISSUE TITLE
[BUG] Image Carousel Lightbox

### ISSUE THREAD

**Issue by carlosnpz** [pojome/elementor#4059]
Hey guys!
I have an Image Carousel widget at the end of this page: http://www.fhscoaching.com.br/cursos/o-poder-da-acao/

The problem is that clicking on an image it will open lightbox by default, but the image in lightbox is always the first and navigation arrows won't work.

Help me, pls! :/

**Comment by carlosnpz** [comment]
I found out that calling jquery inside functions.php causes this error. But I need it to make masked inputs. Any clues?

**Comment by bainternet** [comment]
@carlosnpz 

Not something we can replicate, so its probably your custom code.

just make sure its loaded correctly.

thanks
