### ISSUE TITLE
Feature Request: reCAPTCHA integration, readdressed by explanation

### ISSUE THREAD

**Issue by acmejack** [pojome/elementor#4060]
Though language is auto-detected by the system, when using a plugin as Polylang for multi-language sites, the system language is not changed so reCaptcha doesn't auto-detect because Polylang just switches to a different set of pages/posts for each language. It is essential that Elementor Pro could set reCaptcha language setting in edit for the language setting tracked with Polylang.

Changing the system language with a script to re-register ReCaptcha language setting would require a language check every time as the user may switch between languages again without changing the system language.

**Comment by bainternet** [comment]
@acmejack 

Assuming that the pages are cached the check is only once per page so i see no problem using the re-register snippet from #3756 with a little modification to work with polylang ex:

```PHP
function add_polylang_language_to_recaptcha() {
	if ( ! function_exists( 'pll_current_language' ) ) {
		return;
	}
	// Get Polylang current language:
	$current_language = pll_current_language();

	// Map polylang language code to recaptch
	// Polylang_code => recaptcha_code
	$polylang_to_recaptcha_language_codes = [
		'en' => 'en',
		'zh' => 'zh-CN',
		'fr' => 'fr',
	];
	// Only run if language is mapped, if not it will fallback to auto detect.
	if ( ! isset( $polylang_to_recaptcha_language_codes[ $current_language ] ) ) {
		return;
	}
	// Remove Elementor's script
	wp_deregister_script( 'elementor-recaptcha-api' );
	// Re-add with language param in url
	wp_register_script(
		'elementor-recaptcha-api',
		'https://www.google.com/recaptcha/api.js?render=explicit&hl=' . $polylang_to_recaptcha_language_codes[ $current_language ]
	);
}

add_action( 'elementor/preview/enqueue_scripts', 'add_polylang_language_to_recaptcha', 9 );
add_action( 'elementor_pro/forms/render_field/recaptcha', 'add_polylang_language_to_recaptcha', 9 );
```

thanks.
