### ISSUE TITLE
STILL NO EXTERNAL URL for Images from CDNs in Images Modules

### ISSUE THREAD

**Issue by lordloadalot** [pojome/elementor#4065]
Hi there!

Though elementor is rising fast we are still missing the usage of **CDN images via external URL** 
 in **ALL Modules with images** ( Content or Background ) Clients start to care about pagespeed. We want to be abe to use services as sirv or cloudinary. 

It would be enough to have one fied  under the imagethumbnail to enter an external image-url.
![imageurl](https://user-images.githubusercontent.com/29510055/38613258-98e939ca-3d89-11e8-9ed6-50fca228f3a9.jpg)

Is there any way ??
Thanks for your time.
Best MArtin

**Comment by arielk** [comment]
I merged this issue with another issue #413 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
