### ISSUE TITLE
Group_Control_Typography and Group_Control_Border

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#4067]
Is there any way to add default values in Group_Control_Typography and Group_Control_Border?

I need to add default font size, font weight in Group Typography.
And also add border bottom : 1px ....etc in Group border.

I can't find it in docs.

Thank you,

**Comment by bainternet** [comment]
@pulla 

The best way, and what we use, to set default is by CSS and this way we keep the database clean, and only save unique data. We also found that if we need to change something that has a "HardCoded" default its a mess to do so.

Thanks
