### ISSUE TITLE
Elementor always loads google font Robotor

### ISSUE THREAD

**Issue by psinger** [pojome/elementor#4075]
I am currently trying to get rid of google fonts, and I observed that elementor **always** loads the google font Robotor via 

```<link rel='stylesheet' id='google-fonts-1-css'  href='https://fonts.googleapis.com/css?family=Roboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CRoboto+Slab%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&#038;ver=4.9.5' type='text/css' media='all' />```

This also happens, if the page is empty, but is edited with elementor. On non elementor pages, this does not happen.

Any ideas on why this is the case and on how to disable this?

**Comment by arielk** [comment]
Please go to > Elementor > Settings > General > Disable Default Fonts

Thanks

**Comment by nemecky** [comment]
I've done that and it still shows up under "add expired headers" when I test my site in GTmetrix.

**Comment by mithri** [comment]
I can confirm. Disabling is not working. Google Webfonts are still showing up. It happens when you select a webfont in the typography settings of some element. Please add a feature to override this functionality. Thanks.

**Comment by filgduarte** [comment]
Same here. Fonts disabled in Admin Panel, but still loading.

**Comment by shilo-ey** [comment]
You will need to regenerate your CSS files.

Go to Elementor > Tools > General tab > Regenerate CSS

![image](https://user-images.githubusercontent.com/45009641/52346870-4881c280-2a29-11e9-842c-c1bb7c077986.png)


The other option is that you have somewhere in your page "Roboto" font set up.

thanks

**Comment by mithri** [comment]
@shilo-ey: Yes we know, that is why we want a setting to override this behaviour and disable the google webfonts the hard way. So the customer can`t use another font, other then set in our custom CSS.

**Comment by filgduarte** [comment]
> 
> 
> You will need to regenerate your CSS files.
> 
> Go to Elementor > Tools > General tab > Regenerate CSS
> 
> ![image](https://user-images.githubusercontent.com/45009641/52346870-4881c280-2a29-11e9-842c-c1bb7c077986.png)
> 
> The other option is that you have somewhere in your page "Roboto" font set up.
> 
> thanks

That worked for me. Thanks.

**Comment by iulibaciu** [comment]
> You will need to regenerate your CSS files.
> 
> Go to Elementor > Tools > General tab > Regenerate CSS
> 
> ![image](https://user-images.githubusercontent.com/45009641/52346870-4881c280-2a29-11e9-842c-c1bb7c077986.png)
> 
> The other option is that you have somewhere in your page "Roboto" font set up.
> 
> thanks

This worked for me. Thanks!

**Comment by GreyVod** [comment]
by the way, if someone is still having this issue, maybe this helps:

1. For the page in question, using the Elementor Theme builder, make sure all elements you placed have their typography set to "Default". (be very thorough here, if even only one element still uses a font specified by the element builder, the stylesheet with the handle of "google-fonts-1-css" will still load up).
2. On "Elementor" -> Settings: enable the option "Disable Default Fonts". (this will make Elementor look at your Theme to decide which styles to apply

- After this I was still having the same problem. Then I noticed I was using a Elementor header template with custom typography, so I had to set its typography to "default" as well.
- Finally, I was using a Elementor popup (also with custom typography), so I had to remove that as well.

Hope that helps.

**Comment by iulibaciu** [comment]
hi,

i solved this with regenerating css styles and library.

thank you!




În mie., 5 feb. 2020 la 19:27, GreyVod <notifications@github.com> a scris:

**Comment by AnuY89** [comment]
Yoh,
just add this in function.php:
add_filter( 'elementor/frontend/print_google_fonts', '__return_false' );

then add in header.php the font that you need ;)

works for me!

**Comment by plethoradesign** [comment]
Thanks AnuY89, for the only reasonable answer for people who have many dozens of Elementor templates, and editing them all manually just to get rid of Google fonts does not seem like fun.

**Comment by voicaandrei** [comment]
On my end, this issue is still present.

**Comment by liliang2840** [comment]
@voicaandrei from the Elementor editor panel, setting the site default font from Roboto to default, you can see the steps from the page [https://ttvps.com/elementor-slow-down-cause/](https://ttvps.com/elementor-slow-down-cause/) but only Chinese.

**Comment by AndreyUSA** [comment]
[https://www.launch2success.com/guide/5-hacks-to-speed-up-your-elementor-wordpress-website/](url)


**You can add these code to the functions.php file in your theme (note: only do this if you have a basic understanding of WordPress themes and/or child themes).

/*--- Remove Google Fonts ---*/
add_filter( 'elementor/frontend/print_google_fonts', '__return_false' );
/*--- Remove Font Awesome ---*/
add_action( 'elementor/frontend/after_register_styles',function() {
	foreach( [ 'solid', 'regular', 'brands' ] as $style ) {
		wp_deregister_style( 'elementor-icons-fa-' . $style );
	}
}, 20 );
/*---  Remove Eicons:  ---*/
add_action( 'wp_enqueue_scripts', 'remove_default_stylesheet', 20 ); 
function remove_default_stylesheet() { 
	wp_deregister_style( 'elementor-icons' ); 
}**

**Comment by greg-thrive** [comment]
^ Doesn't work

**Comment by sreekanthedayar** [comment]
I'm a yet to figure out a solution. My issue is with Single post. I'm using Astra theme and tried all the different solution mentioned above, but when i see the content in a non logged in browser I'm annoyed to see that ugly big roboto text. fed up.

**Comment by colmtroy** [comment]
Folks I've reported this as a bug here
https://github.com/elementor/elementor/issues/16023

No amount of regenerating css etc. will resolve this. 
This is tied to the default value of the `elementor_scheme_typography` DB option which doesn't appear to be interlinked with  Global Disable Default Fonts option.

Hopefully the Elementor folks will make some changes to how this works in a future release to be more logical.

**Comment by johnbrid** [comment]
I had a similar problem with Elementor pro. It was loading the Google font Montserrat which according to lighthouse was slowing things down. I am only using Tahoma. Everything was set to this and I checked and tried everything above but google appis file was still being requested. 
Solved it by using the Asset Cleanup plug in. The Google file appears in The Homepage tab under external third party files. I just set it unload site wide. It doesn't any more. Great! The asset cleanup plug in had already speeded up my home page considerably with its other setting . Well worth exploring.

**Comment by alfredonodo** [comment]
Hi,
I tried with your suggestions (@shilo-ey and @AndreyUSA ) with wordpress 6.0.1, twenty fourteen theme 2.1.1513857861 and element 3.6.8, but it still load google fonts.
Any idea?
Thank you

**Comment by michael-ritsch** [comment]
Why is this closed? The problem still exists.

**Comment by greatsomehow** [comment]
I had set Elementor to use the fonts provided by the theme but still had the same problem as described here.

What finally worked for me was to edit one of the pages with Elementor, then click the top left hamburger menu, go to Site Settings -> Global Fonts. Change all of these fonts to Default (it still said the Google Font there which I believe makes Elementor load in the Google Font API).

**Comment by TokyoFred** [comment]
Thanks, @greatsomehow. This is what worked for me (setting to Default and then regenerated the CSS)

**Comment by andrewinsidelazarev** [comment]
> **add_filter( 'elementor/frontend/print_google_fonts', '__return_false' );**

Thanks a lot!!! Works for [my website](https://andrew-lazarev.com/en/videographer-photographer-video-editor/).

**Comment by webgodo** [comment]
@greatsomehow It worked for me. Thanks.

**Comment by Michel-Jo** [comment]
actually I tried a lot / everything here but Elementor or the website still has Roboto loaded....
What actually helped me then was the following:

The design theme loaded roboto itself as the default font. So I changed the settings there. DESIGN -> Customizer -> Typography -> then change every type of text to "default system font".

Now no more roboto is loaded

**Comment by CaduWeberOficial** [comment]
Olá pessoal! tudo bem? vim aqui compartilhar a solução que serviu para mim neste caso, vale lembrar que meu problema era  o seguinte: Minhas fontes no site estavam configuradas como Poppins, porém, ao acessar meu site através de uma conta deslogada do meu perfil de Admin do Wordpress, as fontes apareciam em Sans-Serif e não importa o que eu fizesse, elas continuavam a serem mostradas. Após bater muita cabeça, consegui achar uma solução para isso. 👇

Vá até a aba de Pluguins do seu Wordpress, e baixe o pluguin chamado "Header and Footer Scripts" ao baixar vá até Configurações > Header and Footer Scripts. Quando estiver dentro do pluguin citado, irá aparecer duas caixas para escrever, e o que você precisar fazer é simples. Basta copiar e Colar (Ctrl+c / Ctrl V) o seguinte link na aba "Scripts in header"  
Este link 👉  <link rel="stylesheet" id="google-fonts-1-css" href="https://fonts.googleapis.com/css?family=Poppins%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CMontserrat%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&display=auto&ver=6.1.1"

Após colar, abaixo terá uma caixinha escrita prioridade "10" - Mude este valor para 15. Pronto! é só salvar e ser feliz.

Vale lembrar que minhas fontes eram Poppins, então, se a sua for Montserrat ou Qualquer outra, Experimente trocar o Nome "poppins" do link deixado acima e substítuia pelo nome da sua fonte.

Espero ter ajudado! Fiquem com Deus.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.10! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
