### ISSUE TITLE
Page Settings>Body Style>Background  (body.elementor bg color + bg-overlay color settings)

### ISSUE THREAD

**Issue by mylimoproject** [pojome/elementor#4077]
## Description

Page Settings>Body Style>Background  
Feature request 
=> When opting for  background type=image, need to have the option of adding "background color overlay" option.
=>Add background-color to page body (body.elementor-page-xxxx)
to get the desired results, I have to add the following "Page Settings" custom css (have not found a way to add the color overlay to bg image). I am surprised that these simple settings are not part of "Page Settings".

 body {margin-right:auto;
    margin-left: auto;
    max-width:1280px; border-style: none;
    border-width: 0px 1px 0px 1px;
    border-color: #cccccc;
    box-shadow: 1px 0px 25px 0px rgba(0,0,0,0.7);}
    
.elementor {background-color:#FFFFFF!important; background-color: rgba(255,255,255,0.60)!important}

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by cstibi** [comment]
Please create similar background settings for page background, for column background and for widget background like there is at section background.

**Comment by Beremaro** [comment]
Website background image with  tranparency options

**Comment by ScottMadore** [comment]
Can you hide the background image on Mobile? I can't see how to do that. 
That would be a good option. So the page will load quicker on mobile.

**Comment by artiemart** [comment]
And make the images dynamic, linked to a post's custom field, that would be great.
