### ISSUE TITLE
Typo: ... you can add youR own extensions

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4078]
**1**
Missing R in the very first sentence of developers Getting Started
[https://developers.elementor.com/getting-started/](url)

"Elementor Page Builder is an extendable plugin, you can add you**r** own extensions...

**2**
... coding standards ... (not codding)
[https://developers.elementor.com/creating-an-extension-for-elementor/](url)

**Comment by ramiy** [comment]
Fixed. Thank you for reporting.
