### ISSUE TITLE
REQUEST: Add HTML attribute to widget

### ISSUE THREAD

**Issue by yaquawa** [pojome/elementor#4089]
It'll be more convenient if elementor allow users to add arbitrary HTML attributes to the widget.

In my case, I want to add some `data` attributes to some specified widgets, so they are able to be selected by some other js libraries like [aos](https://michalsnik.github.io/aos/) or other ones. Not only `data` attributes but others like `ARIA` also frequently used by the web developers.

Also, if you add this feature then `id` and `class` can be removed which will simplify the whole UI a little bit I think.

By the way, if there is a hook allow me to extend elementor to add this feature to ALL widgets some how? Thanks!

**Comment by ramiy** [comment]
@yaquawa Please see PR #4030 , it should allow you to set the attributes you need.

**Comment by yaquawa** [comment]
@ramiy Thanks!!
