### ISSUE TITLE
Inconsistency with hooks for PHP vs JS element templates

### ISSUE THREAD

**Issue by hybridvision** [pojome/elementor#4092]
## Description

I have hit a wall with extending Elementor and it seems to be due to an inconsistency in the API where I can't make the PHP and JS templates behave the same way by adjusting the same elements. I will explain with some examples.

I am building a theme that has very precise spacing requirements for the design. In order to enforce consistency and make it easier for the editors, I have extended the `section` element to add two new controls: custom layout selector (controlling column widths and spacing + layout reversal (using flexbox to reverse the column order and swap the padding on the left and right to create a mirror of the design).

The issue I have is that I can't make the editor (JS template) and the frontend (PHP) output exactly the same HTML. All I need to do is add some extra CSS classes to the existing `<div class="elementor-container ...">` tag. In the JS template, I can modify the full template so this is quite easy but with the PHP hooks, I only can find the `elementor/frontend/element/before_render` hook which, as far as I can see, is limited to setting render attributes on the very top level element (ie. the main `<section class="elementor-section ...">` tag).

From the `before_render` hook, I can't access the internal HTML (ie. the `<div class="elementor-container ...">` tag) so I settled for setting the classes on the top level section tag. However, in the JS template, I can't reach the top level section tag because it seems to be added by the editor JS in a different manner (the `_content_template()` only contains the child tags of the section.

This is a frustrating situation because I can't use the same CSS rules for the editor as for the frontend and it quickly becomes a headache. I've tried other things such as adding an intermediate wrapping element around the JS template's `<div class="elementor-container ...">` tag but then I get JS errors in the editor because it expects a very specific structure to function.

I'm at a loss for how I can modify these two templates in the same way so I have equivalent CSS hierarchy between them.

See below for example code...

## Steps to reproduce

~~~php
//## 1. Add controls to section element in editor
add_action( 'elementor/element/section/section_layout/after_section_start', function( $element, $args ) {
    /** @var \Elementor\Element_Base $element */
    $element->add_control(
        'block_layout',
        [
            'label' => __('Custom Layout', 'cube'),
            'type' => Controls_Manager::SELECT,
            'options' => [
                '' => __( 'Default', 'cube' ),
                'layout-1' => __( 'Layout 1', 'cube' ),
                'layout-2' => __( 'Layout 2', 'cube' ),
            ],
            'default' => '',
        ]
    );

    $element->add_control(
        'layout_reversed',
        [
            'label' => __('Reverse layout?', 'cube'),
            'type' => Controls_Manager::SWITCHER,
            'default' => '',
            'return_value' => 'layout-reversed'
        ]
    );

}, 10, 2 );


//## 2. Override the editor template to be aware of new controls (Backbone JS template from _content_template())
add_filter('elementor/element/print_template', function ($tpl, $instance) {

    if ($instance->get_name() !== 'section') {
        return $tpl;
    }

    // Doing a simple find and replace on the template.
    // I know it's not ideal but I didn't want to duplicate the whole template 
    // and this seems like it shouldn't change often...
    // Note: in $tpl, I don't have access to the very top level section tag :(
    $extra_classes = '{{ settings.block_layout }} {{ settings.layout_reversed }}';
    return str_replace('class="elementor-container', 'class="elementor-container ' . $extra_classes, $tpl);

}, 10, 2);


//## 3. Override frontend (PHP) template to also use the classes
add_action( 'elementor/frontend/element/before_render', function ( Element_Base $element ) {

    if ('section' == $element->get_name()) {

       // Note: unlike the JS template, I have access to the top level tag attributes but not any of the internal HTML :(

        $element->add_render_attribute('_wrapper', ['class' => $element->get_settings('block_layout')]);
        $element->add_render_attribute('_wrapper', ['class' => $element->get_settings('layout_reversed')]);
    }
} );
~~~

## Environment

Elementor - 2.0.4 / WordPress 4.9.5 / PHP 7.2.4

(This is an API limitation so environment doesn't really matter)

### Notes

This seems somewhat related to the request in #3258 

I'm sorry for the long ticket but hopefully it provides enough detail to understand what I'm trying to achieve. Any help appreciated! :)

Elementor is a really well thought-out and professionally coded plugin so I'm grateful to the team for all the work so far!

**Comment by bainternet** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

**Comment by hybridvision** [comment]
Fair enough, I imagine you have lots of other things in the backlog. As a matter of interest, do you keep a list of lower priority requests somewhere? Now this ticket is closed, it seems like it will fade away.

In the end I was able to solve my problem by using the `prefix_class` setting on a control. With this, I get consistent behaviour in both contexts and it works quite seamlessly.

For more complex scenarios, it would be great if this inconsistency was resolved. If I have time in the future, I'll look at submitting a patch but I don't expect that to be anytime soon.

**Comment by oooh-boi** [comment]
I've stumbled upon this one because I'm experiencing the exact inconsistency problem. That issue must have a hell of a low priority because it hasn't been resolved until this day...

Any plans on pathing it?

**Comment by brittaweller** [comment]
Another 2 years past  and `view.addRenderAttribute('_wrapper', 'key', 'value' ); `is still not working ... :-(
