### ISSUE TITLE
Posts Widget - missing features

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#4094]
I've just tried using the Posts widget for the first time and it's pretty nice. There are a few issues I have though:

- Column and row gaps aren't responsive
- Neither is the Alignment
- Using the card skin, the second content "spacing" doesn't work. I'm assuming this is for spacing above because the first one affects the spacing below, but they're both simply labeled "spacing".
- When using the Manual Selection for the query, it would be really handy to be able to reorder the items in the search & select box.
- The card box shadow should be tweak-able
- It would be also be great if the query source could be set to an ACF relationship field

**Comment by dudaster** [comment]
@maxwellhibbert try this plugin for the time being: https://wordpress.org/plugins/ele-custom-skin/

**Comment by maxwellhibbert** [comment]
@dudaster hey wow, that's pretty tricky! 

It's a bit disjointed when designing, which goes against my whole reason for using elementor, but it does get around some of the limitations I listed.

The column and row gaps still aren't responsive though and another downside of elementor is that sections and columns can't be (or be wrapped in) links. So I'd then have to make every sub-element a link or write a css hack to position a link over all the content..

Every time I try to get into Elementor, I come up against something like this, then go back to code to get it done.

**Comment by dudaster** [comment]
The devil is in details.

**Comment by maxwellhibbert** [comment]
I found a solution to all of my issues, except reordering items when using Manual Selection.

Elementor Extras. It has a Posts Extra widget that's much better than the Elementor Pro one:
https://shop.namogo.com/elementor-extras/widgets/posts/

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
