### ISSUE TITLE
Feature Request - Breadcrumbs for nested elements

### ISSUE THREAD

**Issue by ajlcomputers** [pojome/elementor#4095]
I think it would be useful to have some breadcrumbs for the elements you are editing, for example, if I have the page split into two columns and then split the left column into 2 again and I want to edit the background of one of the columns it becomes difficult to make sure I'm on the correct one.

If there were breadcrumbs that said

Columns > Column > Columns > Column

Then I could easily click on the specific column or group of columns that I want to add the background colour to.

**Comment by bainternet** [comment]
I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
