### ISSUE TITLE
Transitions aren't properly deleted from the frontend CSS files.

### ISSUE THREAD

**Issue by squadcar** [pojome/elementor#4098]
If you add a transition to an element, save the page, then go back and delete it, the css transition rule is still there in the frontend CSS. Only the properties are removed.

Ex. Fade-in adds "transition: opacity Xs", as well as "opacity: 0/1". If you delete/remove the transition, "opacity: 0/1" is removed (or just set to "opacity: 1"), but the "transition: opacity Xs" remains.

This causes massive headaches if you're trying to do transitions/animations via external/theme css.

**Comment by bainternet** [comment]
@squadcar 

We cant replicate,
please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists feel free to reopen.

**Comment by TheMangoTrain** [comment]
Whoever may be experiencing this, make sure you're flushing WP cache before testing, or better yet, disable any WP caching while developing.
