### ISSUE TITLE
NavMenu Issues

### ISSUE THREAD

**Issue by Eichlig** [pojome/elementor#4102]
https://youtu.be/XTiX_8cTYMM

Click 1: the menu overshadows my content.
Click 2: it moves up, under my logo... which is nonsense; it should push the stuff below it instead of going up.

Isn't there are a good video tutorial on how to fix this? I've been having problems with these menus for a while; it has been very annoying to me...

**Comment by Eichlig** [comment]
Let me add a question here, because this is an emergency:
We have had a problem with our theme and we are forced to buy a new one, but then here it comes the new Elementor...
Do we have any idea of when Elementor 2.0 will be fully released? Allowing single pages, etc.

**Comment by bainternet** [comment]
@Eichlig 

Elementor 2.0 is already out, try out the new header blocks and see how they work for you.
