### ISSUE TITLE
conflict with Better WordPress Minify

### ISSUE THREAD

**Issue by eugenem** [pojome/elementor#411]
Once BWP in activated, Elementor looks like this: 
https://www.dropbox.com/s/65a3lae355zh8g0/Screenshot%202016-08-16%2018.45.02.jpg?dl=0

When BWP is desctivated, Elementor works fine

**Comment by yehudah** [comment]
Sorry for the late response,

In my local install I have excluded all the assets ( css, js ) of elementor and it worked for me.
You can try the same.
