### ISSUE TITLE
[Pro Beta] Fonts are not loading at all

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#4110]
## Description

When using any Google Font from the Elementor styles settings, the fonts load fine within Elementor but do not render at all on the production site.

Searching the source code for the usual ```<link ...>``` Google Fonts call yields nothing.

![image](https://user-images.githubusercontent.com/1435638/38779319-c33450fa-4105-11e8-95c4-c6afbd217441.png)
*Within Elementor editor (Font: Zilla Sans)*

![image](https://user-images.githubusercontent.com/1435638/38779334-f471ef9c-4105-11e8-96ca-2e7eb339cd51.png)
*On public facing page - defaults to "sans serif" CSS setting.*

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.0.34
	PHP Version: 5.6.35
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: https://www.stephendrabsch.com
	Home URL: https://www.stephendrabsch.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: Plain
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: BlankSlate
	Version: 4.0.4
	Author: TidyThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.0.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.0-beta5
		Author: Elementor.com

	Jetpack by WordPress.com
		Version: 6.0
		Author: Automattic

	Limit Login Attempts
		Version: 1.7.1
		Author: Johan Eenfeldt

	Really Simple SSL
		Version: 2.5.26
		Author: Rogier Lankhorst

	WooCommerce
		Version: 3.3.5
		Author: Automattic

	WooCommerce PayPal Express Checkout Gateway
		Version: 1.5.3
		Author: WooCommerce

	WooCommerce Services
		Version: 1.12.3
		Author: Automattic

== Debug ==
	Errors: 
		TypeError: Cannot read property 'replace' of undefined
			at http://www.stephendrabsch.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=1.13.1 - 2:4605
			2018-04-15 12:34 +00:00
			x 12 times

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by drawcard** [comment]
Cheers. I've emailed support. For now my workaround is to manually import the fonts I need from Google using the @import rule in my CSS stylesheets.

**Comment by pawelszroeder** [comment]
I've got the same problem. I've noticed that elementor is adding google fonts to source code only when you choose font for example in widget options (you need to change font from default to other you choose).
I thought that choosing default font in Elementor global options will cause adding google fonts to source code, but in that way Elementor is adding only css rule font-family.

**Comment by pawelszroeder** [comment]
I've followed by this solution: https://docs.elementor.com/article/204-my-changes-do-not-appear-online 
I've regenerated CSS and Google Fonts now appear in source code :)

**Comment by RonR-WebDesign** [comment]
It's now April 2019 and this problem persists.  We have to Regenerate CSS every time I change Default Fonts.

Versions:  Elementor - 2.5.13, Elementor Pro - 2.5.5

**Comment by designvoidnz** [comment]
having this issue too across multiple sites that I use Elementor for, plugins up to date and no plugins or themes are responsible? what do?

**Comment by oooh-boi** [comment]
"Default Fonts" feature NEVER WORKED AT ALL! You can check the page source code and you'll see that Google Fonts DO NOT LOAD and as such "Default Fonts" feature is a total disaster. Beside "Default Colors", of course.
Cmon Elementor people, face the fact, "Please contact our support" is not a serious answer.

**Comment by sandeld** [comment]
Problem is still here.
