### ISSUE TITLE
how to automatic update accordion items elementor

### ISSUE THREAD

**Issue by osmanpro** [pojome/elementor#4112]
how to automatic update accordion items elementor ,
i have many pages over 100 page and i have the same accordion menu in this all pages , i face problem that when i make change one of them , the rest didn't effect . need to effect all when i change one

**Comment by osmanpro** [comment]
how to automatic update accordion items elementor ,
i  have many pages over 100 page and i have the same accordion menu in this all pages , i face problem that when i make change one of them , the rest didn't effect . need to effect all when i change one

**Comment by bainternet** [comment]
We have Global Widget just for that : https://docs.elementor.com/article/100-global
