### ISSUE TITLE
Nav Menu - Responsive Alignment

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#4116]
I'd love it if the menu layout alignment and toggle button alignment were both responsive.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by sherlanova** [comment]
Hello.

Just going to open request and found this.

It's true, especially the Toggle Button alignment, it would be nice if we can set different alignment for Tablet and Mobile. I am currently designing mobile web and found out that the toggle button is the same in Tablet (I want the toggle button on the side) and Mobile (which usually center alignment is nice on mobile view).

Thanks.
