### ISSUE TITLE
[feature request] Blocks available for clients only

### ISSUE THREAD

**Issue by rich73625** [pojome/elementor#4118]
**Create a "Blocks section for clients".**
When a client wants to update the site themselves they may occasionally need to insert a ready made block, e.g. a 'special offer' block that they need periodically when offering such things. That way, this block can be ready made for them, and they can be shown how to insert it into the page. 
But when they come to access it, it would be good if they only see that block (or others assigned to them) so that they aren't tempted to insert loads of other things and break/mess up the design.
So, perhaps a way of allocating a block to a user or user role, and then have a separate tab/section where those blocks appear within the admin area so they can see them.

Thanks for considering,
Richard

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
