### ISSUE TITLE
Fatal Error during update to 0.7.0

### ISSUE THREAD

**Issue by dtbaker** [pojome/elementor#412]
I clicked the "Update Now" button on Elementor. It took me to this page and showed the error:

(suggestion: Hide the "Update Now" banner on the update.php page, because it has already been clicked)

Anyway this error showed up. It seemed to update fine though. 

![image](https://cloud.githubusercontent.com/assets/543073/17720107/af2774ec-6462-11e6-8792-6fbd9610e782.png)

**Comment by KingYes** [comment]
Thanks
