### ISSUE TITLE
Google reCAPTCHA v2 on the Comments widget

### ISSUE THREAD

**Issue by IDESIGNSTUDIO** [pojome/elementor#4123]
Please add reCAPTCHA control for the Comments widget.

I have to install a separate plugin just to activate reCAPTCHA for post/page comments.

If Elementor has it integrated -->> one plugin less to install on the website.

**Comment by bainternet** [comment]
@IDESIGNSTUDIO 

We don't really have control over the comment form other than design, we use the native `comment_form` function to allow 3rd party plugins to replace/extend the comments form exactly for that.

but thanks for the suggestion.

**Comment by descifixer16** [comment]
Same here.. I hope this could be integrated already. Pleeeeaaaaassse. Thanks.  =)

**Comment by pixelloop** [comment]
> @IDESIGNSTUDIO
> 
> We don't really have control over the comment form other than design, we use the native `comment_form` function to allow 3rd party plugins to replace/extend the comments form exactly for that.
> 
> but thanks for the suggestion.

If a plugin can add ReCaptcha to the form, why can't Elementor?

I really think this is a missing feature that should exist.
