### ISSUE TITLE
JS error with anchor links smooth scroll

### ISSUE THREAD

**Issue by Micemade** [pojome/elementor#4125]
## Description
EDITED:
There's an error in **frontend.min.js** producing smooth scroll to anchor points.
_Uncaught TypeError: Cannot read property 'height' of undefined_

When I format minified file, this is the line:

```0 < elementorFrontend.getElements("$wpAdminBar").length && (o -= this.elements.$wpAdminBar.height())```

Elementor v 2.0.7. / WP 4.9.5

**Comment by bainternet** [comment]
Thanks fixed in 2.0.8
