### ISSUE TITLE
Hello. Enhance or bug or tip. elementor pro 2. 

### ISSUE THREAD

**Issue by john298612** [pojome/elementor#4127]

**Comment by john298612** [comment]
When i wanted to choose the category on which my single post template will be shown i had to have a post posted that would belong to that category. If i had jsut created the category and it had no posts assigned to it then it wouldnt appear in the display conditions. 
Thank you.

**Comment by bainternet** [comment]
will be tweak in next version, thanks

**Comment by john298612** [comment]
You are welcome
