### ISSUE TITLE
Bug. elementor pro 2. 

### ISSUE THREAD

**Issue by john298612** [pojome/elementor#4128]
Hello. widgets under theme elements not appearing correctly.

**Comment by bainternet** [comment]
@john298612 

Can you provide more details?

**Comment by john298612** [comment]
Fixed in the new update of pro. A few of the widgets under theme elements like site title and post info had no titles. it could have been an astra conflict as well. today there was a new update for elementor pro and astra and astra pro and the problem no longer exists. the widgets appear as normal. Thank you.
