### ISSUE TITLE
Pods Integration

### ISSUE THREAD

**Issue by HQRaja** [pojome/elementor#4129]
With 2.0 out now along with the promise of deep integrations with ACF and Toolset, the excellent Pods shouldn't be left out of the picture.

## Description

Many developers rely heavily on building custom functionality in their projects with Pods. Beaver Themer already has an official Pods integration enabling developers to easily add Pods fields to a layout they build for a CPT, using a dropdown. Elementor users can benefit from the same integration.

Just in the [post announcing Elementor 2.0 ](https://elementor.com/upcoming-elementor-v2/), there were eight requests for Pods integration in the comments, which clearly shows user demand.

In light of the above and on behalf of all those who asked for the integration in the aforementioned comments, I'd like to officially request the integration here.

**Comment by mjunaidit** [comment]
+1 for the request. I'd very much like Pods to be officially integrated with Elementor as well.

**Comment by twotweak** [comment]
+1 for the request. Currently using ‘Pods’ on my website and I also would love to have it officially integrated with Elementor.

**Comment by srcek** [comment]
+1 for the request. Pods is completely free, well rated, solution for which you should definitely consider adding official support.

**Comment by kharysharpe** [comment]
+10 Adding Pods ( https://pods.io/ ) would support would make it the most comprehensive solution for building Wordpress websites.

**Comment by caseyfulgenzi** [comment]
+1 for the request! Pods is free, stable and loved by many. Pods integration is the one thing that keeps me holding onto BB/Themer and not going all-in with Elementor.

**Comment by paulherzlich** [comment]
+1 for Pods integration

**Comment by josecristobal** [comment]
+100 Pods integration.

**Comment by Bannerman** [comment]
Yes, please! Same deal here, I would love to fully move over from Beaver!

**Comment by Psmeg** [comment]
You can use PODS with Elementor Pro 2.0 already. Well, it can be used through the Dynamic tools; but not too sure how much deeper integration would need to go as I'm relatively new to it.

I will be uploading a video on how to use it alongside EP2 in the next day or 2.

What sort of functionality would everyone like to see?

**Comment by drank** [comment]
+1

**Comment by tristanleboss** [comment]
+1

**Comment by mikekl2** [comment]
Yup, +1 for Pods

**Comment by reachadam** [comment]
This would be a dream come true for me, support for pods relationship fields. I'll be using 2 builders in the meantime.

This can also be supported by giving the user the option to enter in the field name for dynamic fields. Sure there won't be a populated list, but this will work for my needs.

**Comment by ablewebs** [comment]
+1 for Pods integration. I have several critical CPTs created in Pods that took me ages and ages to build. So I can't switch from Beaver Builder to Elementor until Pods is fully integrated. Trying to re-do them all in ACT (which I have never used) is not an option... way too stressful even thinking about!

**Comment by usmanlatif** [comment]
+1 for Pods.

**Comment by jayalove** [comment]
+1

**Comment by aju29** [comment]
+1 Pods Please.

**Comment by zac-cmn** [comment]
+1 With Pods integration I can make a full transition from BeaverBuilder to ELementor

**Comment by quantissimo** [comment]
+1 please

**Comment by muzaffarsiddiqui** [comment]
+1 for PODs. We really need this in Elementor.

**Comment by deptgraffig** [comment]
+1 for Pods integration please

**Comment by icecandy** [comment]
+1 for pods as I found it to be the easiest (free) solution to add CPT's and I love using Elementor.

**Comment by WayneStratton** [comment]
+1 - Essential

**Comment by HQRaja** [comment]
UPDATE: @quasel (the developer of the Pods Beaver Themer Add-on) has commented on the issue linked above on Pods GitHub, mentioning (but not promising) that he'll look into building it. His concern is support, however, since in his experience, the Beaver Themer add-on already puts some load on the Pods support team. Would the Elementor support team be interested in taking care of the support?

**Comment by jimtrue** [comment]
> This can also be supported by giving the user the option to enter in the field name for dynamic fields. Sure there won't be a populated list, but this will work for my needs.

@reachadam Why wouldn't it be a populated list? Pods fields are WordPress Custom Meta. They're in the post meta for the post type. It should be able to easily populate the list of fields. The only item that would be dealt with differently is relationship fields and those are a serialized array of the post id's on the other side of the relationship.

**Comment by sc0ttkclark** [comment]
We're open to discussion with the Elementor team about official Pods integration. My e-mail is scott@pods.io

**Comment by reachadam** [comment]
@jimtrue Custom fields are now being populated, yes. It's the related fields that, in my mind, make PODS so special. That is not working for the reasons you outlined. Just need the mechanism to allow those to be used.

**Comment by serenator** [comment]
+1 for Pods integration please

**Comment by reachadam** [comment]
@jimtrue I can see in the fields drop down where all the fields are, my related posts. But there is no way to select a field from a related post. If I do select the related post, the value it displays just says Array.

**Comment by HQRaja** [comment]
@sc0ttkclark Thank you - that's awesome! With you on board already, I hope we can also get someone from Elementor on board officially. I'm super-excited!

@bainternet We'd love to hear from you (or someone else from the Elementor team) in this regard, now that Scott has offered to collaborate for an official integration.

**Comment by peterhrnciar** [comment]
+1 for Pods

**Comment by codeagencybe** [comment]
I'm already working on a project with E Pro 2 and Pods for a new client (they are informed some stuff is still in beta and some features might not work. 
So far, most things I tried already work out of the box.
I made a single-item CPT and an archive CPT, E templates for both and design them in E, custom fields, ... most things work. 
Custom fields are also recognized by Elementor and show up nice. I would say today maybe 70% already works. So for "simple" projects, no reason to hold back I would say. 

The only issue I could find so far, is that it does not support e.g. image gallery elements. Even though the dynamic field option is there, and using the correct pods image custom field with correction settings, it does not work properly (yet).
It seems Elementor can not pull the correct ID('s) to display the right images. 

So far, I could solve it by just using a text field and paste in a shortcode from Pods itself, and automagically it also nicely returns the "native" image gallery from Wordpress. 

I'm sure a lot new feats and optimizations will come in the next weeks and months, but so far I'm quite happy already how it works with Pods and I can keep working on with this combo.

**Comment by quasel** [comment]
I'll take a look at the current state start of next week - if there is an easy way to do it - the question remains if the Elementor Team want's to include it out of the box or if we need a separate plugin like done for BB! - and the rest needs to be discussed with @sc0ttkclark and the Rest of the Team ;)

**Comment by smatzis** [comment]
+1 please

**Comment by randomfreeform** [comment]
+1 Pods Please.

**Comment by EnzoTheBaker** [comment]
+1 for Pods

**Comment by OKDnet** [comment]
Yes, +++1 for native Pods integration. I think it's almost inevitable. Well maybe that's because to me it seems frankly like a no-brainer (not necessarily in the effort to, rather in the need to).

**Comment by imzeeshan** [comment]
+1 for Pods.

**Comment by jsmartin51** [comment]
+1 for Pods built in to E

**Comment by bkonia** [comment]
+1

**Comment by themedleb** [comment]
+1

**Comment by cbrcongit** [comment]
+1 full integration of Pods field types through to Elementor modules.
I love BeaverBuilder, but it seems Elementor is getting requested more often than I'd like to include, not that it isn't fantastic also; 
This would solve quite a few headaches right now 😁 Good market sense @sc0ttkclark, nice!

**Comment by stevek28** [comment]
+1 for Pods.. Thank you!

**Comment by looknear** [comment]
+1

**Comment by eddiebail** [comment]
+1 Cannot commit fully to Elementor 2.0 without Pods integration like Beaver Themer.  This should be top of the list of things to implement.

**Comment by gabrieluntura** [comment]
+1

**Comment by yoclay** [comment]
+1  Elementor 2.0 is fantastic  but without Pods integration I will continue to use  Beaver Builder  with  Beaver Themer.

**Comment by jolusadev** [comment]
+1 for the request.

**Comment by BigBearLio** [comment]
+100 for Pods :)

**Comment by ordilibre** [comment]
+1 for the request

**Comment by AllanSJ** [comment]
+1 for PODS. Please Elementor team also work on making more of the widget fields accept dynamic content such as  links and shortcode box. I have done a project using ACF (against my will) and ran into a hurdle when I needed the form redirect url to be different on each post page..

**Comment by renecnielsen** [comment]
+1

**Comment by zSeriesGuy** [comment]
+1 for PODS

**Comment by oldrup** [comment]
Mmmm. Pods...

**Comment by quasel** [comment]
We are still waiting to hear back from the Elementar Team, we got a first email but then the conversation ended ;) - they wanted to put us in contact with a developer from them ^^ the main issue is that the way we did it for BB wasn't ideal du to the added support burden on the support on our side :(

**Comment by helenryle** [comment]
+1 for Pods integration into Elementor 2

**Comment by natcreat** [comment]
+1 for Pods. ;)

**Comment by mrdavefoy** [comment]
+1 for Pods integration. Yes please please please please. Please.

**Comment by HQRaja** [comment]
@quasel Considering this is the second-most-requested feature among all the requests on Elementor GitHub, be it open or close, I'm surprised at the silence from Elementor on it, especially after you and @sc0ttkclark have offered to officially help with it from Pods side.

@arielk @kobizz @KingYes Any update from you guys?

@reachadam considering your interest in it, could you help us push for it?

**Comment by quasel** [comment]
@reachadam offered me to fund development if needed but the main point which should be settled first is wether it will be integrated with elementor or be standalone and if standalone if it's supported officialy by the pods team! As we learned from our experience with BB that this can put quite a strain on our support resources! ;)

**Comment by HQRaja** [comment]
@quasel Based on what @sc0ttkclark posted here above, it seems Pods is willing to officially help with it. Not sure if they mean to officially support it, though. With radio silence from Elementor, I'm hoping for Pods to clarify on that.

**Comment by quasel** [comment]
Well @sc0ttkclark is open to discuss it but without a commitment from the elementor team there will be no "official" add-on from the Pods-Team ;)

**Comment by angrycodepoet** [comment]
+1 for all of Elementor 2.0 to work like the Map component does now. It has a custom post field dropdown that allows you to pick "address" from your Pod and populates the Google Map accordingly. Add that to the Heading, Text Editor, etc. to allow quick and easy building of a Pod Template that can be associated with the Pod type to make it a no-brainer to add to your WordPress site. Combine Pods, Elementor 2.0, and Caldera Forms round trip front-end editing and there would literally be nothing that could compete in terms of ease-of-use and power.

**Comment by klarakalko** [comment]
+1 for Pods integration.

**Comment by joeyismusic** [comment]
+1 for official Pods x Elementor integration

**Comment by fullontom** [comment]
+1 for Pods integration. Any news on the issue?

**Comment by EdwardBurns** [comment]
+1 for Pods integration

**Comment by danadalis** [comment]
Big + for Pods in elementor. ACF is lacking the possibility to create CPT and the Elementor integration doesn't allow the use of fields in ACF Options Page. I hope you integrate PODS and make it possible to use fields from Options Page. Today i solve this by using pods shortcodes, but thats really crapy UX for my clients. So again, a +1000 for a pods integration.

**Comment by andrewvink** [comment]
+1 for Pods integration - Would be awesome to have this!!

**Comment by collindavis** [comment]
Using Pods currently but having to hack it a bit with shortcodes and another plug-in to support custom post types. +1 for this to improve the workflow!

**Comment by quasel** [comment]
it's part of the 2.1 Release - I did test it an the basics seem to work - I'm not an Elementor user ;) just a page builder user that happens to help out with pods ;) my favorite tool is still BB ;) but I love the competition!

**Comment by fyrstorm** [comment]
yes +1 for pods  integration, please!

**Comment by sushinger** [comment]
+1 for Pods integration! Thank you for you good work :-)

**Comment by collindavis** [comment]
Already included.

**Comment by ho30hero** [comment]
Hello

+1 Kindly !

To Fully support PODs relation field (to create a fully dynamic website and not only a simple call back text.) 
For example call back a featured image, title, description and other fields of related post into main post for example as a post grid.
It is really needed please, and really 

Also other fields of PODs. It is very handy, very powerful and free. 

Kind Regards
