### ISSUE TITLE
[Developer Docs] - Following custom widget documentation throws fatal error

### ISSUE THREAD

**Issue by jonathanbossenger** [pojome/elementor#4130]
Apologies for posting here, but I wasnt sure where I could post issues related to the new developer docs.

When following the developer documents to create a [new widget](https://developers.elementor.com/creating-a-new-widget/), the following error is thrown

`Fatal error: Class 'Elementor\Widget_Base' not found`

After doing some research, especially the [demo plugin](https://github.com/pojome/elementor-hello-world), I ended up triggering the includes method by using the 'elementor/widgets/widgets_registered'  action hook to my constructor, instead of calling the includes method from the init method.

```
	public function __construct() {

		add_action( 'init', [ $this, 'i18n' ] );
		add_action( 'plugins_loaded', [ $this, 'init' ] );
		add_action( 'elementor/widgets/widgets_registered', [ $this, 'includes' ] );

	}
```
Not sure if this is the correct way, but it works.

**Comment by ramiy** [comment]
@jonathanbossenger Thanks for reporting.

We have dived into this issue. Seems like the `Widget_Base` class is not loaded by the Elementor autoloader, the class is required in the class itself. It is wrong behavior. @Mati fixed it in #4133. it should fix the error you see.

Side Note: I also recommend to set your minimum required Elementor version to "**2.0.7**".

**Comment by ramiy** [comment]
I'll also [update](https://github.com/pojome/elementor-hello-world/pull/10) the [Elementor Hello World](https://github.com/pojome/elementor-hello-world) plugin to reflect the tutorial in the [developers site](https://developers.elementor.com/).

Again, thank you for your feedback.

**Comment by jonathanbossenger** [comment]
Hi @ramiy thanks for much for your fast response, feedback and the PR (thanks @mati). I'm glad I was able in some small way to help improve Elementor.

I know it's hard to tell right now, but do you have an rough ETA on the 2.0.7 release? Thanks

**Comment by DeoThemes** [comment]
Hi, I'm also having the same issue. What should I do to pass this error. I copy all the code from the docs and then receive fatal error.

**Comment by jonathanbossenger** [comment]
@DeoThemes are you using the 2.0.7 (or newer) release of Elementor?

**Comment by DeoThemes** [comment]
@jonathanbossenger I'm using the latest 2.0.11

**Comment by DeoThemes** [comment]
After some debugging I found where is the issue. Please correct me if I'm wrong.

Instead of this (fatal error):
```
public function init() {

    // Include plugin files
    $this->includes();
    
    // Register widgets
    add_action( 'elementor/widgets/widgets_registered', [ $this, 'register_widgets' ] );

  }
```
This works:
```
public function init() {
    
    // Register widgets
    add_action( 'elementor/widgets/widgets_registered', [ $this, 'on_widgets_registered' ] );

  }

  /**
   * On Widgets Registered
   *
   * @since 1.0.0
   *
   * @access public
   */
  public function on_widgets_registered() {
    $this->includes();
    $this->register_widgets();
  }
```

**Comment by bainternet** [comment]
Thanks, documentation and demo plugin have been updated.
