### ISSUE TITLE
Update 2.0 broke background color

### ISSUE THREAD

**Issue by patatus** [pojome/elementor#4134]
Hi!
It seems that with the 2.0 update, the background color option for a whole page is no longer working.
The background becomes white. A work-around is to define a background in the section instead of page wide.

To be perfectly clear, this is the setting that appears to be broken (accessed from the little gear on the bottom left corner):
![bug2 0](https://user-images.githubusercontent.com/20305403/38821340-88967626-41a0-11e8-9b0f-599f417c02f3.png)

Thanks a lot for everything else anyway!!

ps : it's even weider because it doesn't appear broken inside the edition mode.

**Comment by bainternet** [comment]
@patatus 

We can't replicate the issue, 
Please contact our support at support @elementor.com for guidance in resolving this issue.
