### ISSUE TITLE
Image Widget Custom Size Color Saturation

### ISSUE THREAD

**Issue by thetimcook** [pojome/elementor#4135]
I have noticed on some of my sites that my images are a little desaturated. This issue happens when anywhere in the Elementor Page Builder you select a custom size for an image. 

I believe the heart of this issue is with the [bfi_thumb WP Image Resizer library](https://github.com/bfintal/bfi_thumb).  I think I could manually make changes to the [bfi-thumb.php](https://github.com/pojome/elementor/blob/master/includes/libraries/bfi-thumb/bfi-thumb.php) file but these changes would only be on one site. A better solution would be to update the Image Resizing library that is being used by Elementor. 

[Aqua Resizer](https://github.com/syamilmj/Aqua-Resizer) or [OTF Regenerate Thumbnails](https://github.com/gambitph/WP-OTF-Regenerate-Thumbnails) might be better options to solve this issue. 

I hope we can find a solution for this soon so that everyone can have beautiful looking images on their sites again! 

Thanks.

**Comment by bainternet** [comment]
@thetimcook 

As far as I know, bfi_thumb uses the WordPress native defaults for cropping quality which you can alter via filters.

as for OTF it only generates based on registered image sizes and not unregistered custom image sizes so it's not  an option.

thanks
