### ISSUE TITLE
Pro 2.0 - Edit %s and weird archive posts offset?

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4136]
After update to the new Pro 2.0, now seeing this when editing any element:
![screen shot 2018-04-16 at 10 52 29 am](https://user-images.githubusercontent.com/319284/38826388-77a6cb86-4164-11e8-88e1-fda61a7d44d4.png)

[edit] Ok, this happens when you set Canvas as the template type and are editing a header/footer type template.  Also if you attempt to go back and edit it later, it gives you the error that the_content is not found, switching back to default template fixes this and I see now that Canvas is not necessary to keep from rendering the set header/footer on the same page you are editing it.

Also when using the new "archive" block there is some css that causes the "nothing found" message and possibly other things to overflow outside the container by 15px because of this rule:

```
.elementor-posts-container {
    margin-left: calc( -30px/2 );
    margin-right: calc( -30px/2 );
}
```

Which seems odd, why do the math when the answer will always be -15px?

[edit] I see now it has something to do with "columns gap" dynamically.  The pre-built block has this set to 30, setting to 0 removes it.  Also, since I will likely use this "gap" for the grid columns, to fix the "nothing found" message being pulled off the page, it would be nice if we could wrap it in a span tag and set some custom css margin but html does not render in the "advanced nothing found" message area.

**Comment by bainternet** [comment]
@pingram3541 

 * The `Edit %s` should be fixed if you refresh your js browser cache.

* The calc ( -30px/2 ) is dynamically set and generated from the SCSS files.

* as for "nothing found" we will wrap it in a container.

thanks.

**Comment by bainternet** [comment]
Should be wrapped in next Pro version.

thanks again

**Comment by pingram3541** [comment]
Confirmed this no longer occurs, thx!
