### ISSUE TITLE
[Enhancement] Pro - Post Navigation includes/excludes capability

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4137]
Currently the post navigation widget focuses on styling but not so much control over what "previous/next" posts are actually queried.  Would be great to define a set of categories, matching tags, include post/page(s) individually or by range.

One example in which I experienced this was when I was creating a "single" post-type template and applied to pages as well.  I had created a custom login page and guess what...yup, on my home page the "previous" page it linked was "Login" and the next page was "Blog".

It would be really cool to be able to define exact same page links as my main menu so you can "carousel" through the website, Home, About, Services, Contact, Home...and so forth using this nifty Post Navigation element while also hiding other pages like my custom Login page.  TY!

**Comment by bainternet** [comment]
@pingram3541 

the Post Navigation widget uses the native `previous_post_link` and `next_post_link` which weren't really meant to be used on pages. 

anyway you can try to filter the values using the "previous_post_link" and "next_post_link" filter hooks.
