### ISSUE TITLE
[Suggestion] Exclude elementor_library from being associated with builder Templates

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4138]
Upgraded a site to Pro 2.0 and created a new "Single" post type Template based of the Single Page Block example and noticed now whenever I edit any of my Elementor library templates, they all render in the editor using the "single" post-type template. The single template is applied to all "single" post types and naturally this also includes the elementor_library posts.

I can override this by setting the library item's page template to Canvas but not sure if that messes anything up and adds extra steps just to avoid what should probably already be avoided.

**Comment by bainternet** [comment]
thanks for the suggestion but currently this is the exact desired behavior.
