### ISSUE TITLE
Last Updated Date For Post & Page

### ISSUE THREAD

**Issue by justsimply** [pojome/elementor#4140]
Hi, congrats on the release of 2.0 elementor!

It is awesome so far!

I would like to know if it is possible to display the last updated date for post & page rather than the date that my page / post was created?

Reason being, I tend to create alot of posts / pages at a go when I have ideas coming before taking my time to write out the contents of each articles.

Thank you again!

**Comment by bainternet** [comment]
You can use the Dynamic data >> post date >> post modified
![screen shot 2018-04-17 at 10 43 04](https://user-images.githubusercontent.com/660572/38855470-34798754-422c-11e8-935d-02177087b92c.png)
