### ISSUE TITLE
Non-translatable strings report

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4142]
Hello. There are some strings than needs to pay attention.

- Templates library
-- Tabs
Content
Section
Global Widget
Header
Footer
Single
Archive

- Call To Action widget
-- All hover animation effects names in dropdown
-- All Blend Mode effect names in dropdown (I'll thanslate them the same as in Photoshop for more user friendly)

**Comment by bainternet** [comment]
@parfilov 

In the template library, we wrapped all strings so unless we missed something which you can point out...

as for the animations and effects, currently, we are not translating them as a decision. 
So maybe in the future.

thanks for looking up..
