### ISSUE TITLE
Enhancement request for the Elementor System Info Page

### ISSUE THREAD

**Issue by obe1968** [pojome/elementor#4145]
I was wondering why the servers current memory limit was not included in the Elementor system info page, and was wondering if it could be included in one of the next releases. I have modified my file to include it on my test server, but many times, for those of us who help support other Elementor users like in the Facebook groups, it would be beneficial to see if users who are having issues have the correct memory settings.

Although I did not include it in mine, knowing the available disk free space would also be beneficial. Hopefully these suggestions will be implemented in future releases. Very important for troubleshooting issues :)

Thanks again for a GREAT product, and all TEAM Elementor Does!!!

Cheers!!!

Shawn Campbell

**Comment by bainternet** [comment]
@obe1968 

thanks for the suggestion,
We build our system info page based on our support needs, and we haven't (till now) found the disk space to be an issue in a few or even none of the cases, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
