### ISSUE TITLE
Activate Elementor PRO through WP-CLI

### ISSUE THREAD

**Issue by franzarmas** [pojome/elementor#4149]
Hello, I do not know if there is this option currently in Elementor, but in any case take it as a request to add to future versions of Elementor.

What is required is to activate our Elementor PRO license through a command in WP-CLI ... just like the "Astra WP" theme that Elementor supports ... https://wpastra.com/docs/wp-cli-commands/

I remain attentive to your prompt response. Thank you.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by bsnjoy** [comment]
Please add this feature

**Comment by redpik** [comment]
I need it too, for automatic deployments.

**Comment by markusila** [comment]
+1 Really need it

**Comment by redpik** [comment]
"Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it."

...but the feature request is closed :/

**Comment by franzarmas** [comment]
There is already support for WP-CLI, the command is:
```sh
wp elementor-pro license activate <LICENSE>
```

**Comment by Micu22** [comment]
I'am trying to make it work, but this command doesn't work
I have connected using ssh, navigated to the directory of the wp install and now I am typing:
wp elementor-pro license activate LICENSE
![image](https://user-images.githubusercontent.com/51614436/65593865-b6b3cf00-df91-11e9-95e7-56455345cd0e.png)
It tells that the license has been activated while it isin't.
When I log into wordpress elementor isin't activated.
Everything else using ssh works perfectly, installing, activating plugins etc.

**Comment by macktic** [comment]
Still the same as above, wp-cli says activated successfully but updates are unauthorized (as are rollbacks)

**Comment by marekmaurizio** [comment]
They solved it removing the command from wp-cli altogether. But they forgot to update the documentation. Classic elementor team.

**Comment by cezarnicolescu** [comment]
I'm also in demand for this feature

**Comment by Hans-101** [comment]
Any ideas on how to make this work on a multisite subsite?
