### ISSUE TITLE
[Pro 2.0] Content duplication when using single template for All pages

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4156]
Hello. When I make Single template and condition for All pages, I see content duplication in result.
![screenshot-2018-4-18](https://user-images.githubusercontent.com/12493645/38917660-3ed9a10c-430d-11e8-939f-4af6cc15941f.png)

**Comment by joebotha** [comment]
I am getting this too.

**Comment by bainternet** [comment]
We had a bug which caused that and it was already fixed.

Please make sure you are up to date with the latest versions of Elementor and Elementor Pro.

Feel free to reopen if the issue persists.
