### ISSUE TITLE
Feature request for Tabs / Accordion / Toggle

### ISSUE THREAD

**Issue by ronaldkubo** [pojome/elementor#4157]
**Feature request** for **Tabs / Accordion / Toggle**: It would be awesome if in the toggled content it would be possible to add other Elementor widgets in stead of the standard textbox. So when you toggle a title, you could choose from a dropdown to embed the standard textbox, or an icon list, counter, heading etc. Perhaps this feature could work for other Elementor widgets as well that would allow to embed another widget.

**Comment by notrealdev** [comment]
+1

**Comment by javothemes** [comment]
+1 - or add an option to add tab id, name on section. It really needs it.

**Comment by black-eye** [comment]
+1
The best approach would be, if all these widgets (tabs / accordion / toggle and maybe also slider and flip box) worked the same was as the section does.

**Comment by bainternet** [comment]
Yes, that would be awesome, 
Currently, this feature is not possible, but we will look back into it in the future.

Thanks for the feedback.

**Comment by ShadowXVII** [comment]
The body of the tab should be its own section.
