### ISSUE TITLE
2.0 is pulling 'google verification' code from WPMUDEV's SmartCrawl plugin

### ISSUE THREAD

**Issue by kguldent** [pojome/elementor#4158]
After upgrading to Elementor Pro 2.0 I noticed that on the top of each of my pages, a code was entered and displayed. After some research, I noticed that this was (is) the Google Verification code used in the SmartCrawl plugin. I will also open a case at WPMUDEV.

Rgds
Koen
![screen shot 2018-04-18 at 11 30 20](https://user-images.githubusercontent.com/38492930/38923920-eb50ace4-42fb-11e8-8495-965ceb292b54.png)

**Comment by bainternet** [comment]
please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists 
Please contact our support at support @elementor.com for guidance in resolving this issue.
