### ISSUE TITLE
Elementor Pro Quickcode - potentially the best Feature yet to come!

### ISSUE THREAD

**Issue by MaximPro** [pojome/elementor#4160]
Hello ;)

**Pre:**

Thanks for developing this nice Theme-Builder. Finally Version 2.0 is out there.
Here is the new Introduction Video: [https://elementor.com/introducing-theme-builder](https://elementor.com/introducing-theme-builder)

You're doing great! Go for it and integrate all the best Stuff, you can get ;)

##  **Elementor Pro Quickcode - potentially the best Feature yet to come!**

So the Purpose of this post is to introduce a nice concept for Elementor, wich could be named Quickcode, because as it's name suggests, it is to quickly "code" a webpage/Element.
Just like copy, edit and paste - or Export/Import, but text based and easy (mass) editable, with sublime-Text.

Basically it should act like an more or less own coding language in Elementor, close to css.
It should be like Text-Settings for the Actual Settings of the Block and for the whole Site.

**For Example:**
Here is the Elementor Builder to configure visually...
watch here: https://youtu.be/cyVivu365wg?t=46s (only 20s, until 1m05s))

Lines could be like css with ID, but a new field, just like the custom css field, but below it.
But with some kind of extra markup, like "E!" to know it's for Elementor - this would be just an Example:

![Elementor Header Text Block](http://s1.bild.me/bilder/110417/72212822018-04-18_15-09-57.jpg)
this export to:

[Elementor]

//Comments or what kind of Element//

[ElementorBlockID]
[ElementorTextblock1]

[Content]
E!Title{Lorem Ipsum Dolor}
E!Link{https://dein-link.de}
E!Size{XL}
E!HTML-Tag{H2}
E!Orientation{Center}	
[/Content]

[STYLE]
same-concept as in [Content]
[/STYLE]

[Advanced]
same-concept as in [Content]
[/Advanced]

[CSS]
example {
    display: inline-block;
    overflow: hidden;
    line-height: 1;
    vertical-align: middle;
    border-radius: 3px;
}
[/CSS]
[/ElementorTextblock1]
[/ElementorBlockID]
[/Elementor]

You know by now, what it is and what I mean. The Code is variable, but the concept is now clear!
**Basically a Feature for Editable Import and Export Text-based Blocks.**
But this should be also possible for global sites build with elementor!
Just like the templates-feature, that already is in there, but text-based and editable!

So we can quickly add, what we need, instead of clicking trought it all, again and again.
And later it would be possible to edit it quickly! 
Just think of the nice Features of Sublime-Edit or Similar Advanced Text Editors.
You could just search and replace doesn't of lines/(quick)code and be done in 30 sec instead of 20 minutes, searching for this small value and quickly edit it in text

**Workflow like:**
Edit a Block/Page > Export / Use Text-Template > **Edit ALL quickly in Text** > Import > Edit visually (if neccesary) > Done!

**This would be a huge speed up for every Webdesigner!!!**
Especially with Bulk Editing!

Hope you like the Idea!

Please support this! @ Developers!

(And Vote for it as a User)

Thanks and have a good Day!
Best regards from Germany
MaximPro

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
