### ISSUE TITLE
editor does not work

### ISSUE THREAD

**Issue by rcasunshare** [pojome/elementor#4161]
The editor does not work for me, it remains completely blank. It only works with version 1.15.6

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache/2.2.34 (Unix) mod_ssl/2.2.34 OpenSSL/1.0.1e-fips mod_mono/2.6.3 mod_jk/1.2.37 mod_bwlimited/1.4 |  
MySQL version: | 5.5.58 |  
PHP Version: | 5.4.45 |  
PHP Max Input Vars: | 3000 |  
PHP Max Post Size: | 100M |  
GD Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

Theme |   |  
-- | -- | --
Name: | GeneratePress |  
Version: | 2.0.2

Debug |   |  
-- | -- | --
Errors: | TypeError: Cannot read property 'html' of undefined 			at http://www.radioplayer.com.ar/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.6 - 2:79706 			2018-04-16 20:24 +00:00

**Comment by bainternet** [comment]
@rcasunshare 

please update to the latest versions.

feel free to reopen if the issue presists.
