### ISSUE TITLE
Webhook Error This Message is not visible for site visitors.

### ISSUE THREAD

**Issue by SNeilson** [pojome/elementor#4162]
Hi,

I'm trying to use the Elementor Pro form widget and webhooks to post all of our form data into Pardot using a formhandler (https://help.salesforce.com/articleView?id=pardot_form_handlers_integrate_form_handler.htm&type=5).

But no matter what I do all I get is the following error which isn't much help in diagnosing what is wrong.

```
Webhook Error 
This Message is not visible for site visitors.
```
However if I copy the raw form html generated by Elementor and insert it into the page using the html widget and then add an action to the form with the correct formhandler url the form works fine and inserts the record into our crm.

Can I get the webhooks function to do the same thing as I don't want to have to copy the html and add an action every time i create a form?

**Comment by pinkwalter** [comment]
Very similar issue here @SNeilson - I just opened a similar [issue](https://github.com/pojome/elementor/issues/4210) with a suggested solution.

**Comment by bainternet** [comment]
@SNeilson 

The current Webhook sends the data in an array of fields which causes the issue ( this is my educated guess ).

You can, however, create a custom webhook where you control the way the data is sent:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
		'body' => $fields,
	]);
});
```

**Comment by SNeilson** [comment]
I've added that code to my functions file and it's still not working.
#### Form settings
![image](https://user-images.githubusercontent.com/1970183/39198553-46e0423a-47df-11e8-8553-8621c0fa6c14.png)
![image](https://user-images.githubusercontent.com/1970183/39198496-242cc380-47df-11e8-92bc-f10456d34e3a.png)
![image](https://user-images.githubusercontent.com/1970183/39198523-346b7d40-47df-11e8-9ffe-52282c490dcb.png)
#### Form html that is generated by elementor
```
<form class="elementor-form" method="post" id="ContactUs" name="ContactUs" style="opacity: 1;">
		<input type="hidden" name="post_id" value="60082">
		<input type="hidden" name="form_id" value="2a18a89">
		<div class="elementor-form-fields-wrapper elementor-labels-above">
			<div class="elementor-field-type-email elementor-field-group elementor-column elementor-field-group-email elementor-col-100 elementor-field-required">
				<label for="form-field-email" class="elementor-field-label">Email</label><input size="1" type="email" name="form_fields[email]" id="form-field-email" class="elementor-field elementor-size-sm  elementor-field-textual" placeholder="Email" required="required" aria-required="true" aria-invalid="false">				
			</div>
			<div class="elementor-field-type-textarea elementor-field-group elementor-column elementor-field-group-message elementor-col-100">
				<label for="form-field-message" class="elementor-field-label">Message</label><textarea class="elementor-field-textual elementor-field  elementor-size-sm" name="form_fields[message]" id="form-field-message" rows="4" placeholder="Message" aria-invalid="false"></textarea>				
			</div>
			<div class="elementor-field-group elementor-column elementor-field-type-submit elementor-col-100">
				<button type="submit" class="elementor-button elementor-size-sm" aria-invalid="false">
					<span>
						<span class="elementor-button-text">Send</span>
					</span>
				</button>
			</div>
		</div>
	<div class="elementor-message elementor-message-success" role="alert">The form was sent successfully!</div>
</form>
```

#### Code in functions file
```
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'ContactUs' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'https://www2.imgtec.com/l/334881/2017-06-08/lr8', [
		'body' => $fields,
	]);
	
});
```
What am I missing as I know the site can send data to the pardot form handler becuase I've used a manual wp_remote_post() to test this.

#### Working code for manual wp_remote_post()
```
if ( isset($_GET['pardot'])) {

	$url = 'https://www2.imgtec.com/l/334881/2017-06-08/lr8';
	$random_name = wp_generate_password( 8, false );
	$data = array('form_fields[email]' => $random_name .'@imagination.local',
				'form_fields[message]' => 'This is a new test post from wordpress to pardot'
				);
	
	$email = $data["form_fields[email]"];
	$message = $data["form_fields[message]"];
	
	$response = wp_remote_post( $url, array(
			'method'      => 'POST',
			'timeout'     => 45,
			'redirection' => 0,
			'httpversion' => '1.0',
			'blocking'    => true,
			'headers'     => array(),
			'body'        => array(
					'form_fields[email]' => $email,
					'form_fields[message]' => $message
			),
			'cookies'     => array()
			)
	);

	if ( is_wp_error( $response ) ) {
			$error_message = $response->get_error_message();
			echo "Something went wrong: $error_message";
	}
}
```

**Comment by WalledMahmoud** [comment]
@SNeilson Have you ever reached to the exactly right code to solve this problem ! if so, please can you provide it! Thanks.

**Comment by SNeilson** [comment]
@WalledMahmoud no we gave up on this and just use gravity forms now as their webhooks work first time.

**Comment by WalledMahmoud** [comment]
@SNeilson Can you please give some instructions on how to use gravity forms with elementor and pardot ! thanks in advance.

**Comment by Pikamander2** [comment]
@bainternet - This appears to still be an issue. Are there any plans to fix this?

**Comment by BFMarks** [comment]
This is an open issue

**Comment by Randall-Coding** [comment]
@bainternet Are you sure this is closed?  I'm still having the issue, and it appears @BFMarks is as well.
Just getting a generic webhook error that tells me nothing more specific than that?  Is the route bad?  Is the webhook doing something Elementor doesn't like?

**Comment by Elxafil** [comment]
Can someone please fix this? There's no debug in console or anything to help diagnose and it's still broken on the latest version. The fact they closed it while still broken just shows how terrible development is.

**Comment by moxet** [comment]
I am facing the issue from last few days, don't know whether someone found the answer?

**Comment by skydev2020** [comment]
I want to handle the response from Elementor Form Submit.
Where and what to write?

**Comment by collejack** [comment]
@bainternet @skydev2020 @SNeilson 
Where should we insert this code in Wordpress?
We are not necessarily a developer but many people like me, have a red X and the mention: "Webhook Error, This message is not visible for site visitors".

**Comment by EduGomes18** [comment]
Where did we should post this code:

add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
		'body' => $fields,
	]);
});

I`ve try in elementor-pro/modules/forms/classes, creating a new file and also try to put in the form-record.php file, no one works D: ( i follow the steps to substitute form name and the uri )

**Comment by bainternet** [comment]
Webhook error means the receiving server responded with response code other the 200.

As for where you can place this snippet, either in a custom plugin file or your theme's functions.php file

**Comment by xinnerz** [comment]
FYI this worked for me. I placed this in my functions.php file of my theme and updated the relevant bits of code. 
Also you have to make sure all fields match exactly ELEMENTOR FORM and PARDOT FORM HANDLER. it all worked for me, the 10, 2 is important.....don't ask me what it does though.


BUT 

Im getting the pardot notification 6 times (comments/message is posted 6 times too). I cant figure out where or why. 
Weird thing is that in the post actions I have an "email" with the results that comes to me, this only comes in once.

So why am I getting 6 Pardot notifications (exactly 6 everytime).




`//Add Webhook code

add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );

    // Replace MY_FORM_NAME with the name you gave your form
    if ( 'NAME_YOUR_FORM' !== $form_name ) {
        return;
    }

    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    // Replace HTTP://YOUR_WEBHOOK_URL with the actuall URL you want to post the form to
    wp_remote_post( ' http://go.fakefakefake.com/l/797343/fakefakefake', [
        'body' => $fields,
    ]);
}, 10, 2 );`

**Comment by robofearth** [comment]
Thanks for the solution @SNeilson. 

I can confirm this issue is still occurring as of 11 Aug 2021, making webhooks unreliable in Elementor's form submission widget.

For those wondering what @SNeilson's example does: Instead of using a webhook, this event hook can be used to capture the form submission request, then you can do your own API request using the extracted field data (see the example snippet quoted below).

For those who need the source of this solution, it's here in Elementor's developer docs:

- https://developers.elementor.com/forms-api/
- In the section "Form New Record Action", the event hook "elementor_pro/forms/new_record".

This solution works and lets you get rid of the "webhook" submission action, using this instead.

——

> @SNeilson
> 
> The current Webhook sends the data in an array of fields which causes the issue ( this is my educated guess ).
> 
> You can, however, create a custom webhook where you control the way the data is sent:
> 
> ```
> add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
> 	//make sure its our form
> 	$form_name = $record->get_form_settings( 'form_name' );
> 	if ( 'MY_FORM_NAME' !== $form_name ) {
> 		return;
> 	}
> 
> 	$raw_fields = $record->get( 'fields' );
> 	$fields = [];
> 	foreach ( $raw_fields as $id => $field ) {
> 		$fields[ $id ] = $field['value'];
> 	}
> 
> 	wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
> 		'body' => $fields,
> 	]);
> });
> ```

**Comment by noam69901** [comment]
hi I try use the code but I get other error after I use the code

**Comment by Talco100** [comment]
Same error here, February 2022

**Comment by Md-Moklesar-Rahman-Bappy** [comment]
I am also getting the same error
![Capture](https://user-images.githubusercontent.com/33512295/155033537-99a0f793-1b9b-42cd-8859-f0086e92c9cb.PNG)
.

**Comment by devfake** [comment]
Guys, have you tested setting the status code to 200? I had exactly the same problem because I returned the status code 201.

**Comment by prmarketing77** [comment]
Not Working

**Comment by vicksbr** [comment]
Anyone? Same problem hear and its so annoy to debug it

**Comment by pckz** [comment]
Same error for me. Any news?

**Comment by neoandien** [comment]
Don't use same name for label, and error in my page is gone :)

**Comment by colinmacleod** [comment]
I had a similar issue, I also got the same cryptic "This Message is not visible for site visitors" message, which turned out to be a timeout issue.

See the solution here:
https://github.com/elementor/elementor/issues/20452

**Comment by SimonKahremann** [comment]
Not sure if this is helpful to some, but I have now created a webhook for the second time that did not expect a POST request but GET, which then led to this problem. Somehow logical, but sometimes my brain doesn’t care about logic ;) So just as an idea to **check again that the webhook actually expects a POST request**.

**Comment by OmriNach** [comment]
Can confirm this solution works:
added to the functions.php in the elementor theme files editor
"""
add_action('elementor_pro/forms/new_record', function( $record, $handler ) {
//make sure its our form
$form_name = $record->get_form_settings('form_name');

if ( 'Beta_Access' !== $form_name ) {
    return;
}

$raw_fields = $record->get('fields');
$fields = [];
foreach ($raw_fields as $id => $field) {
    $fields[$id] = $field['value'];
}

wp_remote_post('url of your choice', [
    'body' => json_encode(['form_fields' => $fields]),
]);
}, 10, 2 );
"""

Note that data needs to be json_encoded with "json_encode" 

The received format is {form_fields : {field_id:value}....}

**Comment by DmitryKleshchov** [comment]
@devfake 
> Guys, have you tested setting the status code to 200? I had exactly the same problem because I returned the status code 201.

You're my savior, I've been having back and forth with this for weeks. Turns out my service returned 202 accepted, but Elementor wanted only 200!

**Comment by ilsondev** [comment]
I've solved adding this to the theme functions:

```
add_action( 'elementor_pro/forms/new_record', function($record, $handler) {

	$webhook = $record->get_form_settings('webhooks');

	$raw_fields = $record->get('fields');
	$fields = [];
	
	foreach ($raw_fields as $id => $field) {
		$fields[$id] = $field['value'];
	}
	//hook
	$body = wp_json_encode($fields);
	$response = wp_remote_post($webhook, [
		'body'   => $body,
		'method' => 'POST',
		'headers'     => [
			'Content-Type' => 'application/json',
		],
	]);
	
	if (is_wp_error($response)) {
		$error_message = $response->get_error_message();
		echo "Something went wrong: $error_message";
		echo 'Response:<pre>';
		print_r( $response );
		echo '</pre>';
	} else {
		return $response;
	}
}, 10, 2);

add_action('elementor_pro/forms/webhooks/response', function($record, $handler) {
	return true;
}, 10, 2);
```

May this help you.

**Comment by orelhassid** [comment]
For me Enable Advanced Data solve the issue on Elementor Form
