### ISSUE TITLE
Smooth scrolling to anchor, conflicts with admin bar

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4168]
Hello! Smooth scrolling to anchor doesn't work when authorized, and admin bar is enabled.

**Comment by pingram3541** [comment]
In my case, smooth scrolling no longer works.  I used to be able to add a class "scroll" to any anchor link and it would smooth scroll, now it's just a hard link.

Just checked, a few sites recently upgraded to 2.0 and they all now have no smooth scrolling =(
