### ISSUE TITLE
Swiper carouse version up to 4?

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#4170]
Hello,

Thank you for the great plugin and love your work.

I have found you are using swiper 3.4.2. But there is already Swiper 4.2.2.
Is there any plan to upgrade?
Because I was going to create a carousel widget with 4.2.2 and it might be conflict with yours.

one more question, is there any reason to use 2 slider js? you are using "slick slider" and "swiper" as well.
It doesn't much different from my poor knowledge. ;) and not sure why you are using 2 sliders. Any reason?

Thank you again,

**Comment by anandau** [comment]
@arielk 
I am also facing issues with outdated swiper script loaded by Elementor. 
Also why it is loading on all pages. 
Elementor usually loads all such scripts only if any widget on that page requires it. 
But I have found that jQuery Swiper script is loading on all page. Any specific reason for this? 

Also please update the swiper library to the latest version as soon as possible.

**Comment by allonsacks** [comment]
Would also like to know why swiper is loading on every page.

**Comment by bdthemes** [comment]
Hello admin, Please update it to latest version 4.4.1 because thumb slider (when i try to add custom widget with latest swiper doc) not working with current version :(

**Comment by TheMangoTrain** [comment]
allonsacks: I know, it sucks, doesn't it? This is typical behavior in web development, even beyond Elementor. You'll find the same situation exists with WordPress plugins too. For example, you install WooCommerce, and now it's JS/CSS files are loaded on every page of your site. Inspect any other CMS or complex system, and chances are good you'll find the same situation too.

Developers build a tool, but they have no way of knowing where the user will actually use it. So it's much safer, convenient (and/or lazy?) and cost-effective just to load it all on every page. If it becomes a problem for certain power users, let them figure it out. Anyways, in theory, after the first loading, the files get cached by the client, so from this perspective, it's not terrible (this is the discussion-closing counter-argument typically given by developers).

What is the flipside?

The developer would have to make an interface to allow the user fine-grained management of resource loading across pages and posts. Extra work. And to top it off, now you're just made support that much more of a nightmare.

Take a look at this [plugin](https://wordpress.org/plugins/plugin-organizer/), it helps you do selective-loading of WP plugins. It works. But look at its interface. It's not nice or intuitive. It could be better designed. The point is it is an interface that needs to exist and adds complexity.

Maybe in a few years you'll see a brave developer try to come up with a similar deal for Elementor. It would be easier if they could make money off it. Is the market large enough? Do enough people care about selective resource loading for Elementor?

**Comment by Fanna1119** [comment]
@arielk I also noticed that swiper.jquery.min.js is loaded without actually being in use. Any reason for this?

**Comment by bainternet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [          Swiper carouse version up to 4?         #4170](https://trello.com/c/8BEQnO3l/77-swiper-carouse-version-up-to-4-4170)
