### ISSUE TITLE
Plugin to hide rows, columns and elements

### ISSUE THREAD

**Issue by ryanaspire** [pojome/elementor#4172]
I know this isn't an issue but your support team asked me to post here... so please forgive if this isn't right.

>Please post your inquiry on our Github page found here: https://github.com/pojome/elementor/issues. Our developers will be able to see your post.

I’m interested in creating a plugin for Elementor that would hides rows, columns or elements.

Is that possible with current API?

If so, can you give me the rough sketch on how to achieve this?

I’ve had a look at the docs but couldn’t figure it out.

Thanks!

**Comment by dudaster** [comment]
I think Granular Controls For Elementor has something similar. Search it in Wordpress Plugin Directory

**Comment by arielk** [comment]
I merged this issue with another issue #1165 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
