### ISSUE TITLE
Custom Field: Link anchor text and ref

### ISSUE THREAD

**Issue by gdeldeo** [pojome/elementor#4175]
A deeper integration with Custom Fields as Links

## Description
While at the moment it is possible to retrieve the value of a custom field with the heading module (and I believe only with that module) and use it as text, it is not possible to use the custom field as link. It would be great if it was possible to define the anchor text as usual while give the link the value gathered from a custom field.

Same opportunity arises looking at the call to action module

**Comment by bainternet** [comment]
thanks, we will add the dynamic to Call to Action widget in the next versions.

**Comment by bainternet** [comment]
Currently in beta #4923 

thanks.
