### ISSUE TITLE
Make 'Post Navigation' stay in current category option

### ISSUE THREAD

**Issue by randomfreeform** [pojome/elementor#4177]
Please add option for the 'Post Navigation' Theme Element to stay in current category... 
Also option to loop last to first post.
THX!!!

**Comment by claudiacolette** [comment]
I have the same request :)

**Comment by supamonke** [comment]
Ditto! Would love to see this.

**Comment by bainternet** [comment]
We have addressed this in the next pro version

**Comment by randomfreeform** [comment]
oh please come soon! xox

**Comment by randomfreeform** [comment]
will this be coming?

**Comment by black-eye** [comment]
+1

**Comment by ianstudio** [comment]
Important! Otherwise this is once again just a gimmicky feature.. Elementor keeps ebbing and flowing between excellence and mediocrity, please stop adding features and perfect the existing ones by making them truly professional..

**Comment by randomfreeform** [comment]
ummm, are you calling this 'post-nav stay in category' a gimmicky feature?

**Comment by ianstudio** [comment]
@randomfreeform  THINK b4 you paranoid-post! I actually thumbed up your comment !
I'm calling it NOT CYCLING IN A CATEGORY a half fast gimmicky feature. Why am I even answering this.

**Comment by randomfreeform** [comment]
Oh I get it now.. wasn't trying to be paranoid or too harsh.

**Comment by JohnWestEast** [comment]
Hi,

I was wondering when this will be implemented, @bainternet could you enlighten us?

Best

JohnWestEast

**Comment by mizejewski** [comment]
@bainternet said "We have addressed this in the next pro version" on May 6. What version? Is it love yet?

**Comment by pako69** [comment]
Hi

Can't wait for this very basic features! Please give us it...
It do not make sense to see a post that is not in the same category showing up.
Worst I built a silot website site and links outside the silot breaks the silos...

Il you do not implement it quickly, at least tell us how to hack this widget to include the "in_same_term" arg.

Thanks

I love Elementor, but sometimes you push new features before basic ones...

**Comment by pako69** [comment]
BTW easy to fixed it and it works!

Look for the file: /elementor-pro/modules/theme-elements/widgets/post-navigation.php
And at the very bottom of this file, replace:
`<?php previous_post_link( '%link', $prev_arrow . '<span class="elementor-post-navigation__link__prev">' . $prev_label . $prev_title . '</span>'); ?>`
by 
`<?php previous_post_link( '%link', $prev_arrow . '<span class="elementor-post-navigation__link__prev">' . $prev_label . $prev_title . '</span>', TRUE ); ?>`

and 
`<?php next_post_link( '%link', '<span class="elementor-post-navigation__link__next">' . $next_label . $next_title . '</span>' . $next_arrow); ?>`
by
`<?php next_post_link( '%link', '<span class="elementor-post-navigation__link__next">' . $next_label . $next_title . '</span>' . $next_arrow, TRUE ); ?>`

and you are done...

refs: 
https://codex.wordpress.org/Function_Reference/previous_post_link
https://codex.wordpress.org/Function_Reference/next_post_link

**Comment by randomfreeform** [comment]
THX!!!!!!!!!!!!!!
Will try this in the morning with fingers crossed! 
(Sure wish El team would implement this though.)
R

**Comment by Overbord** [comment]
Looping as requested in the OP is still not possible.

**Comment by randomfreeform** [comment]
PLEASE ADD LOOP! 
(Otherwise thx for adding stay in cat!)

**Comment by WallnerK** [comment]
I'm also desperately looking for an option to loop post navigation. Feature request +1

**Comment by RonR-WebDesign** [comment]
Post Navigation has a problem with WooCommerce products when there is more than one Category.  And, since we did a bulk upload of products they all have essentially the same time stamp.  That's causing them to only show 3 items.  This widget still needs  so loving tweaking... !
