### ISSUE TITLE
Potential Bug with Elementor Pro 2.0 using Video Elements

### ISSUE THREAD

**Issue by chemocool** [pojome/elementor#4178]
## Description

I am creating a new "Single" page template using Elementor. When I Drag&Drop a new Video Element on the canvas, I don't have any form in Content Tab, only in Advanced.

Therefore, i cannot choose which video I want.

## Steps to reproduce

1. Create a new **single** template
2. Add a video element
3. Content tab is all grey, cannot edit anything

Also visible on existing pages that have a video embedded. (they become un-editable)

## Environment

On an undisclosed dev site hosted on WP Engine

**Comment by bainternet** [comment]
please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists, please contact our support at support @elementor.com for guidance in resolving this issue.
