### ISSUE TITLE
Responsive column settings for tablet portrait and landscape

### ISSUE THREAD

**Issue by wilthil** [pojome/elementor#418]
I am missing more control over the responsive layout for columns. Why is there no settings for tablets?

Are there any hooks/filters we can use to set new breakpoints?

Also, is there a way to filter the default section width of 1140px, and also the default columns gap?

**Comment by yehudah** [comment]
Hi,

This are stuff we are working on and your comments will be considered.

Thanks

**Comment by lunacroft** [comment]
Hey guys, do you estimate when these responsive adjusts will be launched?

**Comment by yehudah** [comment]
We getting a lot of feedback from the community and we do our best to include this comments in each release.

For now I don't have any estimate.

**Comment by andreaswilthil** [comment]
Great, thanks :-)

**Comment by andrastudio** [comment]
Hi guys,
Is there any update on this feature?

**Comment by nicolasblume** [comment]
Nice to hear, that you are working on it. Keep up the great work!

**Comment by JoelEadeDesign** [comment]
I would love this feature as it's one of only a few of my bug-bears with Elementor. I have to apply CSS to work with some content in tablet mode, as more often than not the content is squashed.

**Comment by JoelEadeDesign** [comment]
It's also quite important for a few folks in the Facebook Elementor Community: 

- https://www.facebook.com/groups/Elementors/permalink/1105079496284502/
- https://www.facebook.com/groups/Elementors/permalink/1077369832388802/?match=dGFibGV0LHdpZHRo
- https://www.facebook.com/groups/Elementors/permalink/1059430037516115/?match=dGFibGV0LHdpZHRo

**Comment by dax702** [comment]
I would like to have the option to have columns collapse and stack to 100% width in tablet mode, just as they do in mobile mode.  Like Joel said, columns in tablet mode are usually squashed too much vertically.

**Comment by maya23** [comment]
The tablet view (or lack of) is my number one feature wish for Elementor. I really want to start using Elementor for client work, but I can't until this is sorted. Hope to see it in the next release. Thanks!

**Comment by Nicoduweb** [comment]
I hope this option as a priority too, before all other things ....

Add this code to “$responsive_points” in “includes/elements/column.php”  seems to do 90% of the job : 

`'screen_md' => [
				'title' => __( 'Tablet Width', 'elementor' ),
				'class_prefix' => 'elementor-md-',
				'classes' => '',
				'description' => '',
			],
![elementor-tablet](https://cloud.githubusercontent.com/assets/22544178/24394193/49cd629e-139b-11e7-8d57-c4419703cb8e.png)
`

**Comment by chalgerro** [comment]
Tablet view is a complete mess and there's very little a designer can do about it from the front end. In other words  elementor as such is not suitable for commercial work. Please get this sorted.

**Comment by CobraClutch** [comment]
I would love this as well. I don't really understand why there is great responsive control for so many other attributes, but column widths are limited to mobile and desktop. Please add tablet breakpoint for columns!

**Comment by CobraClutch** [comment]
As @Nicoduweb pointed out, this is really easy to implement. In addition to what he added to includes/elements/column.php, you can add this to your CSS:

`@media (max-width: 1024px) {
  .elementor-row {
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;  
  }
}
`

Not sure if this will cause anything else to break, but it seems to be working fine for me so far. Shame that we have to edit core files for this though. 👎

**Comment by Nicoduweb** [comment]
Agree with CobraClutch.

And it's really more easy to use full width container with this features too.
Because 100% width on talbet is not always readable as on wild screen

**Comment by pingram3541** [comment]
I'd like to add my vote here as well.  Additionally when setting column width for sections it would be nice to  set max-width value based on desktop, tablet and mobile rather than rely on padding/margin.

**Comment by nicolasblume** [comment]
We really need responsive widths of collumns for our site. 

For example we want the split to be 33% - 66% on desktops and 50% - 50% on tablets, for the same section.

**Comment by MaskaZan** [comment]
+1

**Comment by NailKhalimov** [comment]
+1

**Comment by Nicoduweb** [comment]
+1 ofcourse !
Elementor Devs : What is the problem with integrating this feature please ?

**Comment by lolhound** [comment]
+1

**Comment by damontribble** [comment]
I am using @Nicoduweb and @CobraClutch solution for this but definitely +1 on making this part of core. Beaver Builder has this out-of-the box and it makes things much easier.

**Comment by carasmo** [comment]
+1 Very Important.

**Comment by Nicoduweb** [comment]
or at least let us tweak this by hook please.

**Comment by carasmo** [comment]
I have a decent solution where you add a select dropdown and choose the stacking breakpoint from choices you create:

https://gist.github.com/carasmo/58fb8e5ea796ec56e8cb87f1f4fc2e38

@nicolasblume 

For 33.33% and 50% at another viewport width, this is where the Custom CSS field comes in:

![screen shot 2017-05-01 at 12 43 16 pm](https://cloud.githubusercontent.com/assets/1124594/25586179/35406150-2e6c-11e7-9134-286391d7dcfd.png)

```

@media (max-width: 900px) { 
	selector .elementor-col-33  {
	    width: 50%;
	}
}

@media (max-width: 500px) { 
	selector .elementor-col-33 {
	    width: 100%;
	}
}
```

**Comment by nicolasblume** [comment]
@carasmo thanks! But unfortunately I don't have Elementor Pro.
I guess this will not work, If I paste this code into my themes custom CSS? 

Once again I wish that the developers add a native option one time.

**Comment by carasmo** [comment]
You would add a custom class to the section in the advanced tab and use the class as the selector. Make sure the priority of your css is after all of elementor's css by using the `elementor/frontend/after_enqueue_styles` hook

**However, if you are a user of Elementor, buy a Pro license. Keep them in business.**

`.my-custom-section-class .elementor-col-33 { ...`

**Comment by Nicoduweb** [comment]
Hello @ll,
I've done a plugin that seems to do the job transparently :)

Thank you @carasmo  for your help your inspired me.

![elemntor-responve-tablet](https://cloud.githubusercontent.com/assets/22544178/25854613/ed1f33cc-34d0-11e7-83bc-74feabe64cd0.jpg)

You can find my plugin here : 
[https://gist.github.com/Nicoduweb/3a4c92f83becc41c422c050d9fdc366e](url)

It can be seriously improved ;)

ps : It seems no need to add custom css now.

**Comment by Stegosource** [comment]
+1 for this feature.

As far as implementation, that was one of the few things Visual Composer did well. Their responsive column settings were set up so at each different break point you could either set a custom width, or adopt the same width as the breakpoint below. So mobile could be 100%, the next break point could be 50%. the next breakpoint up could be custom or adopt from the one before (50%), and on up the line. I felt like that was a simple and intuitive enough approach.

Any way you choose to go, this will be a very welcome feature :)

**Comment by Nicoduweb** [comment]
Hello all,

you can try my plugin here : https://fr.wordpress.org/plugins/mrt4e/#description

Have fun

**Comment by arielk** [comment]
@Nicoduweb please note that we're added a new responsive control for Column Width in the next version 1.5

You can learn more here: https://github.com/pojome/elementor/issues/1827#issuecomment-309757319

Thank you all for your valuable feedback!

**Comment by hufer** [comment]
https://pafe.piotnet.com/#custom-media-query-breakpoints Custom Media Query Breakpoints Feature in Piotnet Addons For Elementor Pro can do it for you

**Comment by redcelinc** [comment]
So on tablet responsive mode, a form looks horizontal and not sure why it wont stack?
