### ISSUE TITLE
Add possibility to flush conditional option after it's no longer displayed / used.

### ISSUE THREAD

**Issue by redlagoon** [pojome/elementor#4188]
Currently, if I have a value that resulted from a conditional option, assume I enter a number after I checked "show numbers?" this number stays even if I de-activated my "show numbers".

If I de-activated "show numbers" but had a value in "number", it should flush the value, not keep it.

Check out this recording of what happens:

https://i.imgur.com/XKQbgZY.gif

A mechanism for flush should be implemented. This is very problematic when you're doing something like this in the `render()` function:

```
<?php if( $allowed_to_display && in_array( 'post_thumbnail', $settings['additional_content'] ) ) :?>
```

That `$settings['additional_content']` will always be filled if it was filled once, regardless of if the control is now active or not.

----

To show code that I'm using:
```
        $this->add_control(
            'show_additional_content',
            [
                'label' => __( 'Show Additional Content on Each Post?', 'elementor' ),
                'type' => Controls_Manager::SWITCHER,
                'default' => '',
                'label_on' => __( 'Yes', 'elementor' ),
                'label_off' => __( 'No', 'elementor' ),
                'return_value' => 'yes',
            ]
        );
```
This is a check to ask the user if he wants to display additional content. If the user switches it, this appears:

```
        $this->add_control(
            'additional_content',
            [
                'label' => __( 'Additional Content', 'elementor' ),
                'type' => Controls_Manager::SELECT2,
                'default' => '',
                'multiple' => true,
                'options' => [
                    'post_thumbnail' => __( 'Post Thumbnail', 'elementor' ),
                    'post_meta' => __( 'Post Meta', 'elementor' ),
                    'count_number' => __( 'Count Number', 'elementor' ),
                    'read_more' => __('Read_More' ),
                ],
                'condition' => ['show_additional_content' => 'yes']
            ]
        );
```

^ This lets me allow the user to select more content to be added to a post.

Now, assume the user picked a "Post Thumbnail". The value gets put in, but let's assume now that the user toggles off `show_additional_content` -- he no longer wants the changes that he made to add any additional content and wants them removed.

The value of `additional_content` is not flushed and remains, again, this is very problematic because in my `render()`, I'll still see `$settings['additional_content'] { 'post_thumbnail' }` present, when it should be empty.

To fix this the user has to re-enable the additional content and remove the post_thumbnail setting or any other setting he chose.

All of this, once again, means I cannot ouput dynamic HTML based on settings the user chose when using conditioned controls.

**Comment by bainternet** [comment]
@redlagoon 

In your render, use `get_settings_for_display()` method which clears out values that do not pass conditions and phrases dynamic data if needed:

```PHP
$settings = $this->get_settings_for_display();
```

let me know if that works for you.
