### ISSUE TITLE
Custom Predesigned Templates

### ISSUE THREAD

**Issue by agusmu** [pojome/elementor#419]
Is there a way to add our custom templates to "Predesigned Templates" section? 

I am using Elementor to build my wordpress themes, and it is important for my theme user to see my custom templates on "Predesigned Templates" section.

**Comment by yehudah** [comment]
Hi,

Currently you can only add to "My templates" tab.

**Comment by agusmu** [comment]
@yehudah is there any plan to allow adding our own Predesigned Templates on the next update?

**Comment by arielk** [comment]
Unfortunately not soon.

**Comment by arielk** [comment]
Merge to #417
