### ISSUE TITLE
Hyperlinked content

### ISSUE THREAD

**Issue by Kandours** [pojome/elementor#4190]
Hi, I have a weird issue : When creating a post, every section seem to have a "<a>" tag attached to it, linking to my homepage. That didnt seemed to be a problem in the first place because the tag was closed, but now, and I dont really know why, the main wrapper (.element-section-wrap, which contains all the elementor sections) have open an open <a> resulting in my whole page being hyperlinked to my website homepage. I didnt tweak any of the code apart from CSS. Any idea ?

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
