### ISSUE TITLE
Flip Box - A few ideas to further increase customization

### ISSUE THREAD

**Issue by AuerMarco** [pojome/elementor#4192]
Here are a few customization options I would like to see for the Flip Box. Sorted by how important they are to me; with 1. being the most important. 

1. I really wish I could add a graphic to the backside as well.
2. I  would like to have the option to remove the button on the backside. 
3. I  would like to add an icon to the button(s). 
4. I  would like to add a button on the frontside.

**Comment by bainternet** [comment]
@AuerMarco 

> I  really wish I could add a graphic to the backside as well.

You can.

> I  would like to have the option to remove the button on the backside.

again, you can, simply clear out the button text.

> I would like to add an icon to the button(s).
> I would like to add a button on the frontside.

thanks for the suggestions,  we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by jabva** [comment]
how can you add the graphic to the backside?
