### ISSUE TITLE
Advanced filtering of pro Posts element with wp_query

### ISSUE THREAD

**Issue by joyspringmedia** [pojome/elementor#4202]
Hi, I'd like to add additional query filters to the EP posts element. Basically, there are additional conditions that a post needs to meet in order to appear on a particular posts grid. I've done this with other page builders in the past and I was wondering if there's a hook/function I can use to apply a custom wp_query on a particular Posts element. Thanks!

**Comment by joyspringmedia** [comment]
#1748 is a long post, so I don't know which part of it do you mean. I'm looking into a way to hook into a particular Posts element and use a full custom query of my own for it. Where can I find it in that thread?

**Comment by bainternet** [comment]
I merged this issue with  #1748, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
