### ISSUE TITLE
[Bug] - Creating a Custom Post Type named video breaks Elementor Video Widget Editability in Section/Header/Footer/Single/Archive types

### ISSUE THREAD

**Issue by chemocool** [pojome/elementor#4203]
## Description

Elementor Video Widget (in edit view) is broken if you have a custom post type named **video** registered.  The dialog appear but with only 2 tabs, Content & Advanced. Content tab don't display any controls and Advanced is as usual (see attached).
![videowidget_broken](https://user-images.githubusercontent.com/29230607/39104406-653a2f50-467e-11e8-9d78-92b15916be08.jpg)

I know I can just rename my custom post type to something else (which i did) to make it work. Thought you might want to be aware of this as this potentially could annoy customers.

## Steps to reproduce

Under Elementor Pro 2.0.2:

1. Create a _Custom Post Type_ named **video**
2. In **Elementor**, create a new _section_, _header_, _footer_, _single_ or _archive_ template
3. Insert a Video Widget anywhere in the Edit View
4. Settings view on the left is broken
5. Rename _Custom Post Type_ to **videoitem**
6. Refresh the Template and now the Settings controls are back

## Environment

On an undisclosed site hosted on WP Engine.

**Comment by KingYes** [comment]
Fix in next EPro update. Thanks !

**Comment by chemocool** [comment]
Awesome, thanks for fixing that.

Finding that bug was really driven by pure luck, as i already had a CPT name video before Element Pro 2.0 was released.
