### ISSUE TITLE
Page title replaced another custom post type title on re-edit

### ISSUE THREAD

**Issue by subrat-uniterrene** [pojome/elementor#4205]
I am facing problems with elementor plugin. I have created few custom post types like testimonial, board members etc for carousel and listing purpose and have created very simple shortcode to display them but every time the page is re-edited, the page title gets changed (to one of the custom post type posts) and even noticed the shortcode duplicates the data in elementor editor panel.

I have used the same codes in other wordpress site and they are all working fine. 

Here is the system info from the website i am working on; (i have removed the site url)

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.54
	PHP Version: 5.6.31
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: SITE-URL-REMOVED
	Home URL: SITE-URL-REMOVED
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: astra-child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.2.7.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 4.4.12
		Author: Elliot Condon

	Contact Form 7
		Version: 5.0.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 2.0.3
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.0
		Author: WebTechStreet

	Essential Addons for Elementor
		Version: 2.5.0
		Author: Codetic

	Header Footer Elementor
		Version: 1.0.12
		Author: Brainstorm Force, Nikhil Chavan

	NavMenu Addon For Elementor
		Version: 1.1.2
		Author: ThemeIsle

== Debug ==
	Errors: 
		ReferenceError: google is not defined
			at SITE-URL-REMOVED/wp-content/plugins/addon-elements-for-elementor-page-builder/assets/js/eae.js?ver=1.0 - 15:31
			2018-04-06 09:47 +00:00
			x 3 times

		TypeError: Cannot read property 'html' of undefined
			at SITE-URL-REMOVED/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.3 - 2:79706
			2018-04-02 06:13 +00:00
			x 2 times

				
I  am using below plugins;

Advanced Custom Fields (Version 4.4.12)
Contact Form 7 (Version 5.0.1)
Elementor (Version 2.0.3)
Elementor Addon Elements (Version 1.0)
Essential Addons for Elementor (Version 2.5.0)
Header Footer Elementor (Version 1.0.12)
NavMenu Addon For Elementor (Version 1.1.2)

![test-4](https://user-images.githubusercontent.com/23572616/39108305-31fdf33a-46e5-11e8-8ab1-b9042609f59c.png)
![test-7](https://user-images.githubusercontent.com/23572616/39108306-322bf33e-46e5-11e8-8923-05da88486f65.png)

Please help!!!

**Comment by subrat-uniterrene** [comment]
Here is the codes i am using:

Here is what I have tried for creating custom post type and shortcode:

//post type
function sb_client_testimonial_slider(){
                //logo post type
                register_post_type( 'client-testimonials',
                array(
                                'labels' => array(
                                                'name' => __( 'Client Testimonials' ),
                                                'singular_name' => __( 'Client Testimonial' )
                                                ),
                                'public' => true,
                                'has_archive' => true,
                                'menu_icon' => 'dashicons-format-status',
                                'rewrite' => array('slug' => 'client-testimonials'),
                                'supports' => array( 'title','thumbnail', 'editor' ),
                                )
                );
}
add_action( 'init', 'sb_client_testimonial_slider');

//***use shortcode: [client_testimonial counts="3"]
function sb_client_testimonial_shortcode( $atts ){
                extract( shortcode_atts( array(
      'counts' => '',
   ), $atts ) );

                ob_start(); ?>
                                
                                <div id="testimonials-carousel" class="owl-carousel">
                                                <?php
                                                                $client_query = new WP_Query( 
                                                                                array(
                                                                                                'post_type'=>'client-

testimonials',
                                                                                                'posts_per_page'=>$counts   

                        
                    ) 
                ); 
                                                
                            while ($client_query-> have_posts()) { $client_query-> the_post(); 
                        ?>
                                                <div class="item darkCyan">
                                                  <div class="home-test">
                                                                 <div class="thumb-img-wrapper">
                                                                   <div class="thumb-img">
                                                                                 <?php if( has_post_thumbnail() ){ ?>
                                                                                                <img src="<?php echo 

the_post_thumbnail_url( 'full' ); ?>" class="img-responsive">
                                                                                <?php } ?>
                                                                   </div>
                                                                </div>
                                                                 <div class="thumb-details">
                                                                                <p><?php echo get_the_content(); ?

></p>
                                                                                <h4><?php echo get_the_title(); ?

></h4>
                                                                </div>
                                                  </div>
                                                                
                                                                                                                                                

                                                                                                                
                                                </div>
                                                                <?php } //}else { echo "<p>No Testimonails!!!

</p>" } ?>

                                                <?php wp_reset_query(); ?>
                                
                                </div>
                                <?php return ob_get_clean();
    }
add_shortcode( 'client_testimonial', 'sb_client_testimonial_shortcode' );


any clues? where i am doing wrong?

**Comment by bainternet** [comment]
@subrat-uniterrene 

It could be the query in the shortcode, try returning a string before the query and see if the issue is still there.

**Comment by subrat-uniterrene** [comment]
@bainternet 

Thank you very much for the quick reply.

I am following the code reference from wordpress.org

https://codex.wordpress.org/Class_Reference/WP_Query

Can you please point out exactly where i am making the mistake?

**Comment by bainternet** [comment]
@subrat-uniterrene 

please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

We can't replicate this issue here.
