### ISSUE TITLE
Plain form submission with <form action="... without js/ajax/Webhook

### ISSUE THREAD

**Issue by pinkwalter** [pojome/elementor#4210]
Is there a way to disable elementors frontend.js code when submitting a form?

When no _"Actions after Submit"_ are set, the form should be sent without any additional js or wordpress ajax dependencies. There should be an additional field to fill in the `action="..."` in the `<form>` tag.

If there is no way, I would class this issue as a future **feature request**.

**Comment by bainternet** [comment]
The form widget works by sending an ajax request to the server for validation and sanitization, its not a "markup builder".

It's simply the way it works.

as for sending the form to a different location, you can use a native webhook or a [custom webhook](https://github.com/pojome/elementor/issues/4162#issuecomment-383959624)

thanks.

**Comment by barrychapman** [comment]
Is there anything we can do to prevent ajax submission?

**Comment by skydev2020** [comment]
How can I have my custom JavaScript handler after Form is submitted?
