### ISSUE TITLE
Applying a filter to "get_the_archive_title", is ignored

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#4211]
Using a filter on the archive title, doesn't seem to apply. Just ignores my filter. 

```
add_filter( 'get_the_archive_title', function ($title) {
     return "PREFIX:". $title;
});
```

Perhaps a bug.

**Comment by bainternet** [comment]
@stickypages 

Use this filter hook tag instead `elementor/utils/get_the_archive_title`

**Comment by stickypages** [comment]
Great thanks!

**Comment by howardjacobson** [comment]
Is this hook documented? I can't find it listed in the Elementor API / Hook / Endpoint documentation.

**Comment by Theboy017** [comment]
Great thanks!
