### ISSUE TITLE
White border on image

### ISSUE THREAD

**Issue by impurnendu** [pojome/elementor#4212]
## Description
There is a white border on any image in any section. I am unable to remove it, even after choosing the border "0".
![image white border](https://user-images.githubusercontent.com/38667159/39143621-0e8eb878-474c-11e8-9543-897683a8f162.PNG)

## Environment
I am using 'Evolve' theme.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
