### ISSUE TITLE
Feature Request: vertical section layouts and grouping/locking sections

### ISSUE THREAD

**Issue by GraemeMcG** [pojome/elementor#4215]

**Comment by bainternet** [comment]
@GraemeMcG 


can you provide examples?

**Comment by GraemeMcG** [comment]
I'll retract that request - my bad! When I tried to recreate it for you
it worked perfectly. What it was, I think I'd not made the two images
exactly the same size, hence they were running out of line when changing
screen resolution. I've attached it looking perfect :) 

On 24-04-2018 09:01, Raz Ohad wrote:

> @GraemeMcG [1] 
> 
> can you provide examples? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

-- 
 

Links:
------
[1] https://github.com/GraemeMcG
[2]
https://github.com/pojome/elementor/issues/4215#issuecomment-383840406
[3]
