### ISSUE TITLE
Post info center orientation is not working after 2.0.8 update.

### ISSUE THREAD

**Issue by arnab0207** [pojome/elementor#4216]
Hey!
Just noticed a bug after updating Elementor to 2.0.8 version. 
The center orientation of post info elements is not working. 
Here is the demo [video](https://www.screencast.com/t/NHAaZdOwz). 
I rolled back to 2.0.7 version it is working perfectly.

**Comment by bainternet** [comment]
@arnab0207 

Thanks, we are aware of it and the next pro version fixes it, should come out in a few hours.

thanks.
