### ISSUE TITLE
Feature request: Attendance plugin for event. 

### ISSUE THREAD

**Issue by Pandexe** [pojome/elementor#4217]
We use a very outdated custom plugin for registering members of our site, as attend or not attend to events. 

Would be nice to have this incorporated in elementor. 
It looks like this now could be use for inspiration. 

![2018-04-24 08_36_40-arma 3 traening danish gaming club](https://user-images.githubusercontent.com/32598869/39170135-b17ab4d0-479a-11e8-8acd-723f11502186.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
