### ISSUE TITLE
Feature Request -> woo commerce add-to-cart button element

### ISSUE THREAD

**Issue by SvenAdam** [pojome/elementor#4220]
I suggest a redirect option towards any custom page to be included with the add-to-cart button, so customers can be led to fill in a form on a custom page and select a meeting date on another page AFTER service selection via add-to-cart button, but BEFORE arriving on the cart / payment page.
Would allow for online appointment booking and questionnaire data collection as needed e. g. by medical staff thru other WP plugins.

**Comment by ljgarnes** [comment]
I want the cart button in the menu as an item in the menu. I don't think this is a duplicate request

**Comment by bainternet** [comment]
@ljgarnes 

Cart link in menu is a link like any other, simply add that link to your menu.

@SvenAdam 
this is more of a WooCommerce 3rd party feature you are asking and not Elementor.


thanks for the feedback.

**Comment by BrookeRaraAvis** [comment]
not just a link... we really need an animated add to cart icon with list in cart icon dropdown. this is standard in all wocommerce themes & visible in top right-hand corner of screen. it is visual confirmation of successful add to cart & encouragement to checkout.

<a href="https://imgbb.com/"><img src="https://image.ibb.co/kAq19d/shopping_cart.png" alt="shopping_cart" border="0"></a>

**Comment by alexptl** [comment]
Please add a cart menu icon with the number of items in it. Is it expectable any time soon?
And it would be great if it would be possible to edit woocommerce elements like single product page, checkout page and others.

**Comment by lukecav** [comment]
Cart count in header means that you will have the slow cart fragments WooCommerce call on load, which can be anywhere from 500-800ms.
