### ISSUE TITLE
[Feature Request] Disable Gutenberg

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#4223]
Until Gutenberg is more mature and stable I don't want it interfering with existing or new sites. I have installed a plugin so that I can disable it but it would be good for this to be a configurable option within the Elementor Settings along with the "Disable Default Colors" and "Disable Default Fonts" have a "Disable Gutenberg" option potentially will an "all" or certain post type advanced setting.

**Comment by redlagoon** [comment]
@nickdgreen Nick, I can't help you, but I'd like to know (perhaps others who search for this as well?) how exactly it interacts with Elementor and why it's bad / good.

I haven't seen any interaction with it so far, maybe I'm missing something.

Can you share a bit of info?

**Comment by bainternet** [comment]
I merged this issue with  #2631, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
