### ISSUE TITLE
[Bug] Divider setting in Post Info Widget Underlines the first Element instead of creating a divider between elements

### ISSUE THREAD

**Issue by chemocool** [pojome/elementor#4225]
## Description

**Post Info Widget** underlines the first Element instead of creating a divider between elements

## Steps to reproduce

1. Drag a **Post Info Widget**
2. Make sure there is at least 2 elements in it
3. Toggle the Divider switch (in Style >List)

**Comment by bainternet** [comment]
Make sure you update to the latest versions of both Elementor (2.0.8) and Elementor Pro (2.0.3).

**Comment by chemocool** [comment]
2.0.3 is not out yet, it's going to be fixed in 2.0.3 ?

**Comment by chemocool** [comment]
Thanks a lot
