### ISSUE TITLE
Source map error: request failed with status 404

### ISSUE THREAD

**Issue by lewisdesign** [pojome/elementor#4229]
I am experiencing an issue with the recent update 2.08. Since the update, console sparks a "Source m
ap error" with the editor.js file and loads the editor all wonky. Before, I could rollback to 1.9.8, but than the editor goes completely white/not visible. The client is upset and I need to resolve the issue as soon as possible. I have tried disabling plugins and switching themes to no avail.

System info and screenshot below:

<img width="884" alt="screen shot 2018-04-24 at 10 44 36 am" src="https://user-images.githubusercontent.com/28059298/39195089-0dd6fb00-47ad-11e8-9a59-87a7a811d723.png">
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
	MySQL version: 5.6.38
	PHP Version: 5.6.24
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: AG
	Version: 1.0

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0

== Active Plugins ==
	Abandoned Cart Lite for WooCommerce
		Version: 4.8
		Author: Tyche Softwares

	Addons for Elementor
		Version: 1.6
		Author: Livemesh

	AddToAny Share Buttons
		Version: 1.7.25
		Author: AddToAny

	Admin Columns
		Version: 3.1.5
		Author: AdminColumns.com

	Admin Menu Editor
		Version: 1.8.2
		Author: Janis Elsts

	Advanced Custom Fields
		Version: 4.4.12
		Author: Elliot Condon

	Advanced Custom Fields: Flexible Content Field
		Version: 2.0.1
		Author: Elliot Condon

	Advanced Custom Fields: Multiple Fields per row
		Version: 1.0.72
		Author: Unihost

	Advanced Custom Fields: Repeater Field
		Version: 2.0.1
		Author: Elliot Condon

	Advanced Custom Fields: WP WYSIWYG
		Version: 1.0.2
		Author: Elliot Condon

	Advanced Image Styles
		Version: 0.4.1
		Author: Gregory Cornelius

	Akismet Anti-Spam
		Version: 4.0.3
		Author: Automattic

	Announcer
		Version: 3.0
		Author: Aakash Chakravarthy

	AutomateWoo
		Version: 3.8.0.2
		Author: AutomateWoo

	Category Thumbnails
		Version: 1.0.6
		Author: Adrian Preuss

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Edwiser Bridge - WordPress Moodle LMS Integration
		Version: 1.3.0
		Author: WisdmLabs

	Elementor
		Version: 2.0.8
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 4.1.3
		Author: Shane Bishop

	GS Logo Slider PRO
		Version: 2.0.4
		Author: Golam Samdani

	HubSpot Tracking Code for WordPress
		Version: 1.2.1
		Author: HubSpot

	Intuitive Custom Post Order
		Version: 3.1.1
		Author: hijiri

	iThemes Security
		Version: 6.9.2
		Author: iThemes

	MailPoet 2
		Version: 2.8.2
		Author: MailPoet

	MCE Table Buttons
		Version: 3.2
		Author: Jake Goldman, 10up, Oomph

	OneLogin SAML SSO
		Version: 2.5.0
		Author: OneLogin, Inc.

	Redirection
		Version: 3.2
		Author: John Godley

	Regenerate Thumbnails
		Version: 3.0.2
		Author: Alex Mills (Viper007Bond)

	Relevanssi
		Version: 4.0.8
		Author: Mikko Saari

	Search Exclude
		Version: 1.2.2
		Author: Roman Pronskiy

	Selective Synchronization
		Version: 1.1.0
		Author: OneAcademy

	SendGrid
		Version: 1.11.8
		Author: SendGrid

	SEO Friendly Images
		Version: 3.0.5
		Author: Vladimir Prelovac

	Simple Lightbox
		Version: 2.6.0
		Author: Archetyped

	Sitelinks Search Box
		Version: 1.3
		Author: Apasionados.es

	SlideShare
		Version: 1.9.2
		Author: Team Yoast

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.14
		Author: Sucuri Inc.

	User Role Editor
		Version: 4.40.3
		Author: Vladimir Garagulya

	VenoBox Lightbox
		Version: 1.4.4
		Author: Neil Gowran

	WC Auto Complete Orders
		Version: 1.0
		Author: tehg33k

	Widget Logic
		Version: 5.9.0
		Author: wpchefgadget, alanft

	WooCommerce
		Version: 3.3.5
		Author: Automattic

	WooCommerce Bulk Discount
		Version: 2.4.5
		Author: Rene Puchinger

	WooCommerce Customer/Order CSV Export
		Version: 4.4.4
		Author: SkyVerge

	WooCommerce Integration
		Version: 1.1.7
		Author: WisdmLabs

	WooCommerce MailChimp
		Version: 2.1.10
		Author: Saint Systems

	WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway
		Version: 4.4.12
		Author: WooCommerce

	WooCommerce Zapier Integration
		Version: 1.7.1
		Author: OM4

	Wordpress Image Hover Showcase
		Version: 2.0
		Author: phpbits

	WP-PageNavi
		Version: 2.92
		Author: Lester 'GaMerZ' Chan

	WP Realtime Sitemap
		Version: 1.5.7
		Author: Daniel Tweedy

	Yoast SEO
		Version: 7.3
		Author: Team Yoast

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
