### ISSUE TITLE
Elementor editor doesn't open on wordpress multisite with domain mapping

### ISSUE THREAD

**Issue by kropsi** [pojome/elementor#423]
When you try to start Elementor it will result in showing the full page, without the editor to the left.

**Comment by lunacroft** [comment]
@kropsi I'm using Elementor with Wordpress Multisite and Domain Mapping, everything is okay here! Try testing another theme and disable plugins. :+1:

**Comment by kropsi** [comment]
@lunacroft I am using WPMU DEV Domain Mapping and when I switch that one off Elementor Editor shows up, otherwise it doesn't. I like your editor, it looks as the best on the market, even though it still lacks a lot of functionality. All others are very laggy. I hope naturally that I will be able to use it at soem point.

**Comment by lunacroft** [comment]
@kropsi so you found "the vilain" lol. Here is okay because I'm using free plugin WordPress MU Domain Mapping. There's some kind of incompatibility between Elementor and WPMU DEV Domain Mapping, but Elementor Team are better to answer you! ;)

**Comment by kropsi** [comment]
@lunacroft I had troubles with setting up WordPress MU Domain Mapping, as it told me that sunrise should be defined before requires_once, even though that was exactly how it was setup, I followed all the steps, but couldn't figure the problem. WPMU DEV team are also good by answering related questions, but Elementor is not a part of their plugin pack. So I hoped to get an answer from Elementor Team.

**Comment by lunacroft** [comment]
@kropsi did you try these 2 steps?

1. Move sunrise.php file from wp-content/plugins/wordpress-mu-domain-mapping/sunrise.php to wp-content/sunrise.php.
2. Edit wp-config.php and uncomment or add the SUNRISE definition line. If it does not exist please ensure it's on the line above the last "require_once" command. The line you need add is: define( 'SUNRISE', 'on' );

**Comment by kropsi** [comment]
@lunacroft it is exactly what I have done and it still writes the same thing, that define( 'SUNRISE', 'on' ); must be above the last "require_once" command. I have only one require_once commend which is in the bottom of the document...

**Comment by lunacroft** [comment]
It's weird... well I don't know how to solve it then, sorry =/

I don't know if it will help you, but part of my wp-config is:

define('WP_DEBUG', false);
define('WP_ALLOW_MULTISITE', true);
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', 'putyoursitehere.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
define('SUNRISE', 'on'); 
/* Isto é tudo, pode parar de editar! :) */

And I have installed multisite in root, not in subfolder.

**Comment by kropsi** [comment]
@lunacroft well it looks all the same. I will try to take it with WPMU DEV, maybe they can fix it. Thanks for your feedback!

**Comment by lunacroft** [comment]
Okay @kropsi ! I hope you find solution =)

**Comment by kropsi** [comment]
@lunacroft I didn't find a solution and I reviewed the problem with WPMU DEV Community, and here is the answer I've godt from the support. I hope it will be possible to fix the issue, as I like to use Elementor in the future togather with WPMU DEV plugins.

> I checked your site and since I found out that Elementor can be downloaded freely (I wasn't familiar with it before) I installed in on my setup. 
> I can confirm the issue but unfortunately it doesn't return any console errors that could be helpful. However, WordPress is not designed (still, despite multiple announcements made in the past by WP community) to work with multiple/mapped domains "out of the box". The Domain Mapping plugin overrides it but as a result such issues may happen. It happens rarely but it's possible. 
> I suppose that this is because the plugin seems to be heavily depending on what's defined in WP installation settings therefore an "inconsistency between that and the domain that's really used breaks its scripts. 
> Unfortunately, it doesn't produce any errors in browser console, it doesn't also produce any debug.log (WordPress debugging) output, nor it leaves any traces in an "error_log" file on my server. This makes it nearly impossible to troubleshoot without being familiar with its code. I realize it's freely available but getting to now it would take a long time. 
> Therefore, I'd suggest asking Elementor developers if they could provide help. In case they'd needed some information on Domain Mapping, let me know please and I'll provide you with all I can. Also, in case they weren't able/willing to fix their code but at least gave some advise on what can be breaking on Elementor's code side - let me please know as well and I'll investigate it further.

**Comment by paaljoachim** [comment]
If WPMU DEV has added code to their domain mapping plugin that makes it so it breaks with the Elementor plugin then it would be good to figure out what is going on.

Regarding the general domain mapping plugin issue. 
I am using the plugin Mercator made by the company Human Made. Here is a tutorial on how I made it work: http://easywebdesigntutorials.com/how-to-point-a-top-level-domain-to-a-multisite-using-domain-mapping/

I just tested Elementor in my multisite that also runs the Mercator plugin and it looks to be working nicely with it.

**Comment by yehudah** [comment]
@kropsi 
I can see from the members answers there is a more then one alternatives for the WPMU plugin.
so for now there isn't a priority to this issue.
You can post here the WPMU staff contact info to discuss this issue.

**Comment by paaljoachim** [comment]
I sent WPMU DEV a Facebook message. I am thinking they will check out this thread during the next few days.

**Comment by yehudah** [comment]
No additional comments received here, so i'm closing it.

**Comment by lippoliv** [comment]
Do I get this right: I have to leave sunrise.php and use Mercator to get Elementor done? That wouldn't be good as of I have the Network up and running for years. I would have to edit a couple of websites with the new Mapping :/

Or did I missunderstood things?

**Comment by Pagester** [comment]
We're running Elementor on a large MU deployment using the WPMU Dev domain mapping plugin and it transitions from the subdomain to the mapped domain without issue.

There is a short 2 second delay for Elementor to appear (so initially it looks like you have arrived on a normal page) but then it updates and the editor slides in.

I think your problem might potentially be related to the Cross domain auto login setting in Domain Mapping, especially if your site is running on https.

**Comment by felipe-paniago-movile** [comment]
Anyone had a fix for this? Activated subdomain on WPML and can't use elementor; If a come back to sub-folder structure, than Elementor works.

**Comment by arielk** [comment]
@felipe-paniago-movile we working on this bug, we'll update you in #473

**Comment by sadorect** [comment]
I stumbled on this thread from a google search and this is what brought me here. I have a multisite installation with domain mapping done successfully using WPMU DEV plugin ( Domain Mapping ). However, my issue is with elementor. Elementor works very well on all the mapped domain in the multisite but fails to load ( despite all debugging efforts and safe mode turned on, other themes and plugins disabled as well ) only on the base domain.

That is, the multisite base domain is basedomain.com and elementor fails to load on it. However, it loads very well and functions normally on all other subsites ( mapped domains ) in the network. Please, I need help. What could be wrong? How do I fix this?

Thank you
