### ISSUE TITLE
Feature Request: Attach Anchors to Specific Toggle Section

### ISSUE THREAD

**Issue by Raccroc** [pojome/elementor#4230]
The ability to create a link to target a Toggle Widget, opening it to a specific section.

_ #EXAMPLE_

MENU
-- **CAR**
SUBMENU
----- **#Blue Car**
----- **#Red Car**
----- **#Green Car**

PAGE
-- **CAR**
TOGGLE (somewhere on the page)
-- **Sample Car  Colors**
-----**#Blue Car**
---------- Stuff about blue cars
----- **#Red Car**  
---------- Stuff about red cars
----- **#Green Car**
---------- Stuff about green cars 

So, ideally, clicking on the  **#Red Car** menu link would take to you the **CAR** page, scroll down to  the **Sample Car Colors** Toggle, and open the **#Red Car** infobox (leaving Blue and Green stuff hidden).

Current use of Menu Anchors will get you to the correct page and scrolled to the correct Toggle, but cannot open it to show its contents without user intervention.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

but for now this can be done with some very little JavaScript similar to this: https://github.com/pojome/elementor/issues/4080#issuecomment-381403477
Thanks for the feedback.

**Comment by beezwings** [comment]
I also second this feature!
