### ISSUE TITLE
Add thumbs to Slides OR... text to Media Carousel carousel

### ISSUE THREAD

**Issue by randomfreeform** [pojome/elementor#4236]
There are so many nice ways to display an image gallery slider in Elementor... THX!
But all have a gotcha, at least for me.

I just want 1 BIG image at top, 
then thumbs (that are bullets for mobile),
then under that the  Title, Caption & Description pulled from the media file...
(The major fine artist & famous photographers I build sites for NEVER want anything on their images...)
And a lightbox or full window zoom icon on rolllover would be really nice too.

**Slides** almost fills my needs (I managed to css the overlay text to be below the image) 
but it has no thumbs or zoom.
And **Media Carousel**'s _carousel_ option has no text 
and it's _slide_ option does but has no thumbs..  LOL! 
So close but no cigar.

Thanks for any future updates

**Comment by randomfreeform** [comment]
any thoughts on this request? THX!

**Comment by arielk** [comment]
I merged this issue with another issue #219 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
