### ISSUE TITLE
Show setting if other setting has value x AND is also shown

### ISSUE THREAD

**Issue by xxtesaxx** [pojome/elementor#4237]
As requested by Ohad Raz, I ask the question from FB here again:

I have 3 switcher settings:

- custom_layout
- display_flex
- alignment

I want display_flex only to show when custom_layout is yes and it should be yes by default. I want alignment to show when display_flex is no/off independently from whether custom_layout is yes or no. Now when I use custom_layout as a condition on display_flex and display_flex as a condition on alignment, when I set display_flex to default yes, alignment does not show when custom_layout is off. Is there a condition to describe that?

Bascially I need to HIDE alignment only when custom_layout is yes AND display_flex is yes at the same time. Any ideas how to do thath?

**Comment by bainternet** [comment]
You can have multiple and nested conditions,

let us have a pick at your register controls code.

**Comment by xxtesaxx** [comment]
Okay if thats possible then lets go with an even more complex scenario. Lets assume I have 4 switchers: A, B, C and D:

        $this->add_control( 'a', [
            'label' => 'A',
            'type' => Controls_Manager::SWITCHER,
            'label_off' => 'Off',
            'label_on' => 'On',
            'return_value' => 'on',
        ]);
        $this->add_control( 'b', [
            'label' => 'B',
            'type' => Controls_Manager::SWITCHER,
            'label_off' => 'Off',
            'label_on' => 'On',
            'return_value' => 'on',
        ]);
        $this->add_control( 'c', [
            'label' => 'C',
            'type' => Controls_Manager::SWITCHER,
            'label_off' => 'Off',
            'label_on' => 'On',
            'return_value' => 'on',
        ]);
        $this->add_control( 'd', [
            'label' => 'D',
            'type' => Controls_Manager::SWITCHER,
            'label_off' => 'Off',
            'label_on' => 'On',
            'return_value' => 'on',
        ]);

Can I create the following conditions:

- A is shown always
- B is shown if A is on
- C is shown always
- D is shown if C is on AND ( (A is on AND C is off) OR (A is off) )

In an if-statement I would write that condition to show D as: if( c == true && !(a==true && b == true) )

**Comment by bainternet** [comment]
something like this:

```php
// A is shown always
$this->add_control( 'a', [
	'label'        => 'A',
	'type'         => Controls_Manager::SWITCHER,
	'label_off'    => 'Off',
	'label_on'     => 'On',
	'return_value' => 'on',
] );
// B is shown if A is on using 'condition parameter
$this->add_control( 'b', [
	'label'        => 'B',
	'type'         => Controls_Manager::SWITCHER,
	'label_off'    => 'Off',
	'label_on'     => 'On',
	'return_value' => 'on',
	'condition'    => [
		'a' => 'on',
	],
] );
// C is shown always
$this->add_control( 'c', [
	'label'        => 'C',
	'type'         => Controls_Manager::SWITCHER,
	'label_off'    => 'Off',
	'label_on'     => 'On',
	'return_value' => 'on',
] );
// D is shown if C is on AND ( (A is on AND B is off) OR (A is off) ) using conditions parameter
$this->add_control( 'd', [
	'label'        => 'D',
	'type'         => Controls_Manager::SWITCHER,
	'label_off'    => 'Off',
	'label_on'     => 'On',
	'return_value' => 'on',
	'conditions'   => [
		'terms' => [
			[
				'name'  => 'c',
				'value' => 'on',
			],
			[
				'relation' => 'or',
				'terms'    => [
					[
						'name'     => 'a',
						'operator' => '!=',
						'value'    => 'on',
					],
					[
						'terms' => [
							[
								'name'  => 'a',
								'value' => 'on',
							],
							[
								'name'  => 'b',
								'value' => 'off',
							],
						],
					],
				],
			],
		],
	],
] );
```

In *B*, using `condition` will work just fine but for *D* you need to use `conditions` which accepts nested conditions and relation param.


bare in mind that this is not test but its shows the main idea...

Hope this help.

**Comment by devrobinkroeker** [comment]
@bainternet Thank you so much! Even after two years this message helps a lot

**Comment by TheFirsh** [comment]
> @bainternet Thank you so much! Even after two years this message helps a lot

This could also be of help: [Conditional Controls](https://letswp.io/conditional-controls-in-elementor-extensions/)
