### ISSUE TITLE
Conflict: Elementor editor not working for shop pages with Ajax PHP function.

### ISSUE THREAD

**Issue by giulianorapoz** [pojome/elementor#4238]
In the woo-products widget for a given page, I am changing the text in the "Add to cart" button to "Add another one!" once the user has clicked and added the product to their cart. The page is using AJAX to add the item to the cart and not via refreshing. - This is done using a PHP function (below).

The PHP code works and runs once activated using Code Snippets...however the Elementor designer for my "shop pages" doesn't load.

**Screenshot of Elementor Editor View:**
![elementorscreen](https://user-images.githubusercontent.com/30539010/39231765-101d79be-4863-11e8-960f-f311b2c2a3de.PNG) The site does however apply the PHP function and work as expected if previewing in a browser.

If I disable the PHP script, the Elementor designer works as normal again. All other pages without the Elementor woo-products widget are unaffected. 

Seems like the Elementor editor doesn't want to play nice with the PHP function, or something in my code which is causing this?

**Conditions to relabel the buttons:**
```
add_filter( 'woocommerce_product_add_to_cart_text', 'customizing_add_to_cart_button_text', 10, 2 );
add_filter( 'woocommerce_product_single_add_to_cart_text', 'customizing_add_to_cart_button_text', 10, 2 );
function customizing_add_to_cart_button_text( $button_text, $product )
{
    $is_in_cart = false;

    foreach ( WC()->cart->get_cart() as $cart_item )
       if ( $cart_item['product_id'] == $product->get_id() ) {
           $is_in_cart = true;
           break;
       }

    if( $is_in_cart )
        $button_text = __( 'Add one more!', 'woocommerce' );

    return $button_text;
}
```

**If AJAX enabled on specific pages (denoted by Page ID):**
```
add_action('wp_footer','custom_jquery_add_to_cart_script');
function custom_jquery_add_to_cart_script(){
    if ( is_page(162) ):
        $new_text = __( 'Add one more', 'woocommerce' );
        ?>
            <script type="text/javascript">
                // Ready state
                (function($){
                    $('a.add_to_cart_button').click( function(){
                        $this = $(this);
                        $( document.body ).on( 'added_to_cart', function(){
                            $($this).text('<?php echo $new_text; ?>');
                            console.log('EVENT: added_to_cart');
                        });
                    });

                })(jQuery); // "jQuery" Working with WP (added the $ alias as argument)
            </script>
        <?php
  	endif;
}
```

Thanks in advance!
Giuliano

**Comment by bainternet** [comment]
Currently, we are working hard on supporting WooCommerce better in the theme builder, but this will only come out in v2.1 of Elementor Pro.

as for your issue, make sure you are not on the admin side when adding the hooks.
