### ISSUE TITLE
Elementor not working properly after Update

### ISSUE THREAD

**Issue by djekanovic** [pojome/elementor#4245]
Hi,

On two sites i had little bit older version of elementor i went on to update it to latest.

And things dont work as it should.

Im adding in attachment 2 screenshot. 

![2018-04-25 2](https://user-images.githubusercontent.com/23662556/39257315-8418f8cc-48b1-11e8-985f-94c5a20b62db.png)
![2018-04-25 1](https://user-images.githubusercontent.com/23662556/39257316-843443de-48b1-11e8-90ef-66d33f27c764.png)

Here you can see that templates look different and  button dosent work.

System info log -----

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.5
	PHP Version: 7.0.29
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: https://djekanovic.com/medak
	Home URL: http://djekanovic.com/medak
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.0.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.3
		Author: Elementor.com

	Slider comparison image before and after
		Version: 0.8.3
		Author: Artem Bovkun

== Debug ==
	Errors: There are no errors to display

**Comment by djekanovic** [comment]
*FIXED

Updated site url from http://djekanovic.com/medak/ to https ://djekanovic.com/medak/

Trough Elementor URL Replace Tool

**Comment by bainternet** [comment]
Gald you figured it out.
