### ISSUE TITLE
[issue] Disabling "Include Context" from "Archive Title" in "Search Results"

### ISSUE THREAD

**Issue by Artneo7** [pojome/elementor#4248]
Hello,

When I click to disable "Include Context" from "Archive Title" in "Search Results" it's not working.

Images: https://imgur.com/a/cKxLTFH

I think it's a bug, because in the category archive page it's working.

Link: https://annadecor.artneo.com.br/?s=lorem

Thanks!

**Comment by bainternet** [comment]
@Artneo7 

"Search Results" is a part of the actual title and not context.

however, if you wish to remove it you can using the `elementor/utils/get_the_archive_title` filter hook.

**Comment by soyket** [comment]
You need to add this to your themes functuon.php file like this:

add_filter('elementor/utils/get_the_archive_title','example_callback');
function example_callback( $title ) {
   if(is_search()){
	   return 'mysearch';
   }
    return $title;
}

Hope this helps.

**Comment by soyket** [comment]
Well, you obviously need to edit my giving code a bit for your work like this:

add_filter('elementor/utils/get_the_archive_title','example_callback');
function example_callback( $title ) {
if(is_search()){
return 'Search Results';  // or anything you like 
}
return $title;
}

**Comment by Artneo7** [comment]
I see. But, what I need to add to copy the same word as the user typed in the search box?
Example: the user searched for "X"
It returns "Search Results for X"

**Comment by soyket** [comment]
Use 

return 'Search Results for'.$title;

**Comment by Artneo7** [comment]
Sorry, but this code gets the "Search Results for:" string again...
Look at the image below. It should only get the word used for search.
![error](https://user-images.githubusercontent.com/17693529/39533790-5ea6c420-4e06-11e8-9c3a-5c3d2e8d1cc0.png)

**Comment by soyket** [comment]
Then just use- 
return $title;  

You can move the code around a bit and test them yourself :)

**Comment by soyket** [comment]
For those who wants to get only the query removing the stirngs- 

add_filter('elementor/utils/get_the_archive_title','example_callback');
function example_callback( $title ) {
if(is_search()){

return get_search_query();
}
return $title;
}
