### ISSUE TITLE
Testimonial & Media Carousel Bug - next controls both on single page

### ISSUE THREAD

**Issue by HayleyBaker83** [pojome/elementor#4249]
Hello,

I am using the latest version of Elementor & Pro and theres a new problem where if I have 2 media carousels on the same page the next buttons trigger both carousels at the same time. See video:
https://drive.google.com/file/d/1GLIECIzL28Y4nA-VvI9p135xTDgPWWQ1/view

I've tried adding a class to one but it still happens.

Thanks,

Hayley

Current Versions:
Elementor - 2.0.8 
Elementor Pro - 2.0.2

**Comment by bainternet** [comment]
@HayleyBaker83 

We can't replicate, make sure you are up to date with the latest versions and try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists if it does, then please contact our support at support @elementor.com for guidance in resolving this issue.
