### ISSUE TITLE
Websites created by Elementor cannot be opened in IE

### ISSUE THREAD

**Issue by leooxu** [pojome/elementor#4253]
Please who can help me, I build a website by Elementor but cannot be opened in IE.

http://www.joinsai.cn

Please Help me :(((((

**Comment by notrealdev** [comment]
Work well on my PC with IE 11

**Comment by leooxu** [comment]
Is it because of my reason in China that China’s network has limitations and I don’t know whether or not to add other link files to the remote site when the site is loaded?

**Comment by bainternet** [comment]
I see no elementor related issue here.

thanks
