### ISSUE TITLE
[Feature Request] Add "title" for Social Icon links

### ISSUE THREAD

**Issue by ShadowXVII** [pojome/elementor#4254]
The Social Icons show no information when the user hovers them. 

The "title" attribute of the underlying "href" should be editable through the Link Options to display custom text.

For example, for the Facebook icon it may say "Facebook", or "Follow us on Facebook", or "Find us on Facebook".

![image](https://user-images.githubusercontent.com/446329/39287779-a343ca76-4968-11e8-8e79-f9eddd144ada.png)

![image](https://user-images.githubusercontent.com/446329/39287804-bc50eeb8-4968-11e8-8e4d-c4ddf739dd1e.png)

![image](https://user-images.githubusercontent.com/446329/39287751-7a02795a-4968-11e8-9dd5-d28a7db6c762.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
