### ISSUE TITLE
which function using to load template from json file

### ISSUE THREAD

**Issue by adan2g2f** [pojome/elementor#4258]
> As is

Currently, from elementor editor, if you select '_add template_' button, you can import local or remote template into the editor and then **edit each elements of this template separately**.

Example of json template:
`{"version":"0.4","title":"section_lib","type":"section","content":[{"id":"b3f9cbd","elType":"section","settings":[],"elements":[{"id":"bdb6971","elType":"column","settings":{"_column_size":100},"elements":[{"id":"70c5d42","elType":"widget","settings":{"title":"XX Add Your Heading Text Here"},"elements":[],"widgetType":"heading"},{"id":"449dd5d","elType":"widget","settings":{"editor":"<p>I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.<\/p>"},"elements":[],"widgetType":"text-editor"},{"id":"b5fd94c","elType":"widget","settings":[],"elements":[],"widgetType":"icon"}],"isInner":false}],"isInner":false}]}`

> Issue

But with elementor_pro template widget  (from left widget panel), when you import the template, all elements are not editable.
This is using function : "get_builder_content_for_display"
There is a button '_edit template_' that redirect user to a new page where you can edit all elements/pieces of this template.

> Question

How can I display the template in editor with all editable elements/pieces without press the button '_edit template_' that will save a step for users?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
