### ISSUE TITLE
Issues with Elementor. Error page when using it!

### ISSUE THREAD

**Issue by lilianmurciaart** [pojome/elementor#4259]
Hello everyone.
I'm having problems with Elementor, I can not use it! When I create a page and I click on "Edit with Elementor" I get an error page like the page is not safe. When I go to "Reasons for blocking this site" it appears: The requested content could not be scanned for malware. It may be corrupted or encrypted.
What I can do? Neither I have installed any other plugin, only Elementor and Elementor Pro. The theme is Generate Press.
I send the access to edit the page to another person in another country and another error appears when you want to edit with Elementor. My error is that of the Sophos image

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.39
	PHP Version: 7.1.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: http://www.jmsolutionusa.com
	Home URL: http://www.jmsolutionusa.com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: es-ES
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.0.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.3
		Author: Elementor.com

== Debug ==
	Errors: There are no errors to display
				
![capture sophos](https://user-images.githubusercontent.com/25530766/39312331-52868fe0-493d-11e8-92fc-79dd4be29f17.JPG)

![img_26042018_162607_0](https://user-images.githubusercontent.com/25530766/39312539-d3f87b88-493d-11e8-9ab2-6e9c0d128c96.png)

**Comment by bainternet** [comment]
disable Sophos.

**Comment by albe89albe** [comment]
Hi, I am the one who also tried and I get this error about the encoding, no sophos involved.

**Comment by lilianmurciaart** [comment]
It's a little rough that you close the problem after only answering me to disable sophos. I do not have Sophos installed, or where to disable it.

As I said, I gave access to another person to try to edit with Elementor and the second error appears, attach a second photo for you to see.

Now I am accessing from a mac in another place and another computer, and it does not appear "error", when I click on Edit with Elementor a blank page appears without anything else.
