### ISSUE TITLE
[Feature Request] Social Icons Hover Controls

### ISSUE THREAD

**Issue by lunacroft** [pojome/elementor#426]
I think could have some controls to social icons hover styles. Maybe: color, bg and opacity. And maybe hover animations too, like image widget =)

Automatic social icons hover style in Elementor:
`.elementor-social-icon:hover {
    opacity: 0.5;
}`

**Comment by joshmarom** [comment]
Good Idea.
We will consider it.

**Comment by lunacroft** [comment]
Thanks @joshmarom =)

**Comment by iamdanbarrett** [comment]
Has this been implemented? The hover animations are instant on/off hover whereas it would be nice to change the easing speed?

**Comment by johngisworking** [comment]
Any updates? The social icons grow and opacity changes on hover yet there are no options to change this.
