### ISSUE TITLE
Feature Request for Image Gallery

### ISSUE THREAD

**Issue by krann** [pojome/elementor#4260]
Slider Image Carousels are often seen on the web with semi-opaque 'before' and after' images either side of the main image - the main image may be 'boxed' but the images either side of it make the carousel 'full width'. Would be nice to see this effect in Elementor Image Gallery.

**Comment by bainternet** [comment]
@krann 
can you provide examples?

**Comment by krann** [comment]
http://www.sncollection.co.uk/

**Comment by bainternet** [comment]
@krann 

thanks for the clarification.

We use Swiper for the media carousel, which currently has no such theme/effect so...

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
