### ISSUE TITLE
Elementor content encoding error

### ISSUE THREAD

**Issue by lilianmurciaart** [pojome/elementor#4262]
I have opened a previous thread (https://github.com/pojome/elementor/issues/4259) but it was closed before solved.
The problem that I am having is that I can’t edit a page with Elementor. I have had three behaviors until now:
**1**.	(first image) An advice from Sophos saying that there is a security risk and the page is blocked. But **I don’t have Sophos.**
**2**.	(second image) With Firefox on Windows. Content encoding error.
**3**.	(third image) With Chrome on iOS. Just a blank page.
I have other three installations of Elementor with the same hosting provider (GoDaddy) in the same type of plan as this one. All of them are working perfectly.
The only difference between them is the Elementor version.

**first image**
![capture sophos](https://user-images.githubusercontent.com/25530766/39323987-4265aa50-495c-11e8-8a2b-c77a8b3be335.JPG)

**second image**
![img_26042018_162607_0](https://user-images.githubusercontent.com/25530766/39324001-4d89fe04-495c-11e8-82df-f01f89133e0f.png)

**third image**
![screen shot 2018-04-26 at 2 16 47 pm](https://user-images.githubusercontent.com/25530766/39324130-b7de69e8-495c-11e8-98b4-4e0359e0dd79.png)

**Comment by lilianmurciaart** [comment]
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.39
	PHP Version: 7.1.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: http://www.jmsolutionusa.com
	Home URL: http://www.jmsolutionusa.com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: es-ES
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.0.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.0.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.3
		Author: Elementor.com


== Debug ==
	Errors: There are no errors to display

**Comment by bainternet** [comment]
@lilianmurciaart 

thank for providing this data and clarifying.  
Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by lilianmurciaart** [comment]
SOLVED!!!!
The solution is switch the loader method under Elementor - settings - advanced to enabled

**Comment by uzairlive** [comment]
> SOLVED!!!!
> The solution is switch the loader method under Elementor - settings - advanced to enabled

Love you jani

**Comment by MiesSuomesta** [comment]
How do I change the setting with wp commandline tool ?

**Comment by MiesSuomesta** [comment]
I got same issue...

**Comment by kashifmahmood47** [comment]
> SOLVED!!!! The solution is switch the loader method under Elementor - settings - advanced to enabled

This simple solution worked after spending 1 hour to solve this error. Thanks man
