### ISSUE TITLE
[Bug] Section typography color issues when background color/image is adjusted

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#4266]
I'm using the section typography settings to control the default text color of heading widgets inside my sections. When I manually override those colors in individual heading widgets I run into issues. 

Issue: 
Any time I change the section background color or add a section background image, the colors of my heading widgets revert back to the default section typography settings. Kind of hard to explain, so I made a screencast below.

How to reproduce (screencast):
https://www.dropbox.com/s/7ij3ad66bubc0gh/section-typography-color.mp4?dl=0

What I'm using:
Astra 1.3.1, Elementor 2.0.8, Elementor Pro 2.0.2, no other plugins

**Comment by bainternet** [comment]
Thanks, we can replicate.

**Comment by avermat** [comment]
This seems to have been left out of the 2.0.10 update. Not sure if that was on purpose or not.
