### ISSUE TITLE
Minor Bug - Templates Preview Missing (?) 404 error

### ISSUE THREAD

**Issue by darkbing05** [pojome/elementor#4267]
Hi, I've been using elementor and I found out that there's this bug, where on the templates library images are not found // sending 404 errors.

https://imgur.com/a/k4ss467

To re-create the issue I went to the my templates on elementor and create a page/header/footer and this is what I got.

**Comment by bainternet** [comment]
@darkbing05 

maybe, Please contact our support at support @elementor.com for guidance in resolving this issue.
