### ISSUE TITLE
[Feature Request] Add dynamic field to form element

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#4268]
I would like to make an inquiry form on a 'single' template. This form needs to have a field containing the posttitle of the actual single. 

I thought that if you add a dynamic fieldoption to the form element, this could be achieved.

**Comment by black-eye** [comment]
+1

**Comment by ecc86** [comment]
+ 1. 
Would love to use that feature.

**Comment by tucaz** [comment]
@bainternet where are the comments I added to #5590? It seems like your merge was more a "kill" than a merge. I had added a lot of important details and explanation. I digress.

After my last comment I played a bit more and I believe I'm close to a clean solution. I created a new widget that is half the way at least of where I want to be. How should I proceed to contribute it back to core?

Should I include it in Elementor basic along with other widgets and send a PR or make it an external plugin? I could potentially sell it as a plugin, but I'd like to contribute with the community (even though I'm a paying customer).

Thanks!

**Comment by bainternet** [comment]
@tucaz 

The Forms Widget is Elementor Pro which you can't create PR's to but we are working on it.

thanks anyway.

**Comment by Brrl** [comment]
You could do a workaround till they implement this feature by setting a hidden field and assigning it an ID (in this example below I set the ID to "LPForm" then Elementor tacts on 'form-field-') in the advanced field. Then call a script on page load like this:

```
function dynamicTitle() {
var pagetitle = document.title
document.getElementById('form-field-LPForm').value = page;
}
window.onload = dynamicTitle;
```

This would call the page title into the hidden field and you could use it or post it in a webhook.

**Comment by besweeet** [comment]
@Brrl Out of curiosity, do you know how to remove the "form-field-" that Elementor adds to the label (and perhaps the "form_field[XXX]" that's also added for the name)?

**Comment by Brrl** [comment]
@besweeet I'm not entirely sure you can.

**Comment by gfdesign** [comment]
> 
> 
> You could do a workaround till they implement this feature by setting a hidden field and assigning it an ID (in this example below I set the ID to "LPForm" then Elementor tacts on 'form-field-') in the advanced field. Then call a script on page load like this:
> 
> ```
> function dynamicTitle() {
> var pagetitle = document.title
> document.getElementById('form-field-LPForm').value = pagetitle;
> }
> window.onload = dynamicTitle;
> ```
> 
> This would call the page title into the hidden field and you could use it or post it in a webhook.

@Brrl Could you explain step by step how to achieve this?
I am trying to set a contact form into every single CPT post using a ACF field with the destination mail but I wasn't able yet.
I''ll be looking forward to your comments
Best regards

**Comment by gfdesign** [comment]
@Brrl, I still don't know how to use the email address I have into an ACF email field in each one of my CPT post, in order every one of them has its own recipient email address.

In other words, I want to creat a single template for my CPT where I put a contact form with a recipient email address taken from a ACF field. 

I am working on for a radio station website with a CPT for every radio show with theirs contact form. 

Will that be possible?
Regards and thanks for replying so fast

**Comment by Brrl** [comment]
@gfdesign Can you link to the radio station website. I'm curious how you have it setup so far.

**Comment by gfdesign** [comment]
@Brrl this is a [development site](https://radiomaster.pilvia.site/) yet.
Mainly will be a news portal but it will have info of each show.

**Comment by Brrl** [comment]
@gfdesign Maybe do the same thing I said to do above but instead of calling to get the title of the page; create a meta tag for each of the pages that is equal to their email address. So as an example. 

Your pages for the station have meta tags set like this:

<meta name="description" content="John Doe | Radio Station Name Page">
<meta name="email" content="johndoe@radiostation.com">

With the description being the first meta tag in the code and the second one in the code being the email meta tag, then follow the steps I put forth in the previous comment but replace the code with:

> function dynamicEmail() {
> var pageemail = document.getElementsByTagName("META")[2].content;
> document.getElementById('form-field-LPForm').value = pageemail;
> }
> window.onload = dynamicEmail;


The hidden field ID in this example is still set to LPForm, and just change the 2 after ("META") to the number of meta tags down from the top of the page you have till you get to the email meta tag. This should insert the email into the field depending on the page the form is one.

**Comment by bainternet** [comment]
Now possible by adding an hidden field and setting its value to dynamic post title, url ...

**Comment by mikeallen7** [comment]
+1

**Comment by donwattz1459** [comment]
@bainternet I am circling back to this as I am using the default field option for a message and using the dynamic tag for an ACF field to fill it in dynamically but it is not staying.

**Comment by kdub718** [comment]
Is it possible to have the email "To:" field be dynamic?

**Comment by Jordidriesen** [comment]
Dynamics fields from acf or other tools would be great! Using a dynamic field for the email or even form fields would make life a lot easier and add good functionality for scaling to Elementor forms.

**Comment by MPHood** [comment]
"Is it possible to have the email "To:" field be dynamic?"

Guys we need a dynamic field for the email recipient.

**Comment by hi0ctane** [comment]
wondering the same, is this in the works? would be really useful or if anyone knows of a plugin that can do this?

**Comment by EDaviesWork** [comment]
+1 for dynamic "to:" field in the form, populated by ACF

**Comment by joaonew** [comment]
I would love that when my user select an option on the Multiple Select field, some custom fields would pop up in the form.

**Comment by OppositeX** [comment]
add a hidden input field
go to advanced - choose "dynamic" - set you Custom field
copy shortcode to -> Email - Recipient.

and thats it.

now, how about setting the same thing for the webhook link field ?

**Comment by log-out** [comment]
Hi @OppositeX, i tried to use the shortcut code in the Email field but it doesn't work. on the front end, it error "Server error. Form not sent.". is there any alternative solution i can apply? thanks

**Comment by OppositeX** [comment]
https://www.loom.com/share/e91aef1515d64a099a2e05b9c4a46711

this is how to add the shortcode

and this is where you set the dynamic value from acf or whatever you are using

https://www.loom.com/share/ff3cc3fdef434fd1b8cc86abbd9b8178

Good Luck

**Comment by log-out** [comment]
Hi @OppositeX  thank you for your prompt reply and for sending me a detailed video. unfortunately, this is not working fine for me. please see the attached vide https://www.loom.com/share/debb3c3ee9094bf9a2dd9f247cb6cd99

Thanks

**Comment by kskonovalov** [comment]
+1 for such feature. need to add an dynamic receiver, or at least apply filter to it

**Comment by vskarleas** [comment]
+1

**Comment by its-julian** [comment]
+1

**Comment by alvaropuche-stack** [comment]
+1
