### ISSUE TITLE
Footer/Header templates are not translatable via WMPL

### ISSUE THREAD

**Issue by OrinocoDelta** [pojome/elementor#4269]
I created a new footer template (https://d.pr/i/zw6pXp), works!
Changed IconList content with our own links, works!

I see all the content from the footer in WPML string translation and I am able to translate it, also the links to other languages are translated. Example screenshots: a) https://d.pr/i/eFhQMg b) https://d.pr/i/IibLr6

But, If I save all, go to the main page and change the language to another I do not see any translations.

Mainly I want to able to translate any template into another language, would also maybe describe a best practice work-flow to do this? Many people are running multi-language pages and have problems to get things like this sorted.

Besides all this only FYI: Translating pages is working so far without any problems.
Best wishes, am.

**Comment by bainternet** [comment]
@OrinocoDelta 

We have nothing to do with translations, its all done by the 3rd party plugin.

thanks for the feedback.
