### ISSUE TITLE
Elementor adds class "elementor-invisible" to items with animation. ".elementor-invisible" hides elements on iPad.

### ISSUE THREAD

**Issue by keilorbrown** [pojome/elementor#4272]
When you add an animation (tested with fade) to a section, it adds the class "elementor-invisible", which sets the element's visibility to "hidden". 

This is a problem because iPads cannot handle animations, and the elements are hidden as a default. Without knowledge of css or inspecting a page, the average joe would be unable to make these features work for iPad. 

Please look into why you're adding a hidden visibility to tablets.

**Comment by webangon** [comment]
I have similar issue. The only fix that I applied is to delete and populate again .

**Comment by bainternet** [comment]
>  iPads cannot handle animations

We can't replicate the issue and animations are working just fine on ipad.

Please contact our support at support @elementor.com for guidance in resolving this issue.
