### ISSUE TITLE
[Feature Request] "Format Painter" to copy settings/style of an element or column to another

### ISSUE THREAD

**Issue by ignitenick** [pojome/elementor#4274]
## Description

Similar to Word's Format Painter it would be amazing if you could take one column or element, click one button on it (on the toolbar next to copy, save, delete, etc.) to "paint" its values to others.   It would only work on same elements or columns directly and only values that they share for styling - padding, margins, backgrounds, typography, etc..  

This would save from having to reproduce settings across content that was created or from having to change the content in elements after copying.  You could create all of your content, modify one of those elements to look like what you want, then paint it to all of the like elements.

**Comment by bainternet** [comment]
I merged this issue with  #1479, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
