### ISSUE TITLE
Elementor editor don't launch for a Single or Archive template

### ISSUE THREAD

**Issue by alejovargas** [pojome/elementor#4275]
## Description

I get this browser error trying to create or edit a "Single Template" at My Templates for Elemento Pro Version 2.0.3

TypeError: undefined is not an object (evaluating 'elementorFrontend.config.elements.data')

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.5
	PHP Version: 7.2.4
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: https://exergy-global.com
	Home URL: https://exergy-global.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen Child
	Version: 1.5.1524845414
	Author: the WordPress team
	Child Theme: Yes
	Parent Theme Name: Twenty Seventeen
	Parent Theme Version: 1.5
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

== Active Plugins ==
	Child Theme Configurator
		Version: 2.2.9
		Author: Lilaea Media

	Elementor
		Version: 2.0.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.3
		Author: Elementor.com

	Enable Media Replace
		Version: 3.2.5
		Author: ShortPixel

	Smart Slider 3 Pro
		Version: 3.2.14
		Author: Nextend

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	Under Construction
		Version: 1.18
		Author: Noah Kagan

== Debug ==
	Errors: 
		TypeError: undefined is not an object (evaluating 'elementorFrontend.config.elements.data')
			at https://exergy-global.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.8 - 2:107783
			2018-04-27 21:10 +00:00
			x 3 times

		TypeError: Cannot read property 'data' of undefined
			at https://exergy-global.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.8 - 2:107784
			2018-04-27 20:56 +00:00

		TypeError: undefined is not an object (evaluating 'elementorFrontend.config.elements.data')
			at https://exergy-global.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.8 - 2:107783
			2018-04-27 20:55 +00:00
			x 12 times

		TypeError: Cannot read property 'data' of undefined
			at https://exergy-global.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.8 - 2:107784
			2018-04-27 16:36 +00:00

		TypeError: undefined is not an object (evaluating 'elementorFrontend.config.elements.data')
			at https://exergy-global.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.8 - 2:107783
			2018-04-27 16:05 +00:00
			x 17 times

		TypeError: Cannot read property 'data' of undefined
			at https://exergy-global.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.8 - 2:107784
			2018-04-27 14:24 +00:00
			x 2 times

		TypeError: undefined is not an object (evaluating 'elementorFrontend.config.elements.data')
			at https://exergy-global.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.8 - 2:107783
			2018-04-27 14:02 +00:00
			x 17 times

		TypeError: undefined is not an object (evaluating 'this._parent.errors')
			at https://exergy-global.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.5 - 2:132647
			2018-04-13 15:28 +00:00
			x 2 times

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by encreinformatique** [comment]
It is referenced in this issue as well : https://github.com/pojome/elementor/issues/3926

**Comment by khalidmeraj** [comment]
Just Update the Elementor Plugin and then deactivate and activate it again... Simple
