### ISSUE TITLE
UPDATE ERROR: Server Error (500 Internal Server Error)

### ISSUE THREAD

**Issue by rcasunshare** [pojome/elementor#4276]
Since the last update of this plugin I have this error when updating and save the page when edited: UPDATE ERROR: Server Error (500 Internal Server Error)

Try everything, increase memory, disable plugins, but keep making the same mistake.

**Comment by TheMangoTrain** [comment]
This worked for me:

**Delete some old page revisions**

1. Go to Elementor / History / Revisions. Scroll down to the bottom, start hitting 'X' on old revisions; remove a bunch.

2. Hit UPDATE once again, and see if you get the 500 error.

I got '500' errors and looked at server logs and memory usage, etc. Before going down a rabbit hole, I looked at this [Elementor support page](https://docs.elementor.com/article/185-the-update-button-does-not-work) and it hinted at making a smaller page by removing sections. My page was normal, not super long or unusually heavy on content, however I've been building the page for 5 days straight with a crazy amount of revisions (like 100). So on a whim tried this; it worked.

Elementor should have a feature to clear revisions-older-than-X, just for this reason, maybe even a clue to do this if a 500 error happens.

**Comment by wwwebman** [comment]
@TheMangoTrain thanks a lot. I didn't found this 'X' in the Elementor(v 3.0.15) revisions. I installed https://wordpress.org/plugins/simple-revisions-delete instead and it works quite okay. As a result, purging revisions helped to solve the issue. It so weird Elementor has no magic 'purge/purge older than' button.
