### ISSUE TITLE
 [Feature Request] Filter to change posts css file la name

### ISSUE THREAD

**Issue by sandromattei** [pojome/elementor#4278]

**Comment by sandromattei** [comment]
Hello. I'm using Elementor on multisite with 2 blogs. these 2 blogs share the same folder uploads and this is a problem for the css files of Elementor because often the posts have the same ID. it would be useful to implement a filter to rename the css files (maybe using the blog id). thank you

**Comment by bainternet** [comment]
Duplicate of #3553
