### ISSUE TITLE
Translation strings on "Template import" screen

### ISSUE THREAD

**Issue by pedro-mendonca** [pojome/elementor#428]
Hi,
I can't find the strings "Explore..." and "No files selected" in the translation strings list.
Is this from a remote js called library or the browser itself?

Thanks

**Comment by cobicarmel** [comment]
These strings are from the browser default user agent, that couldn't be included in the translation list.

**Comment by pedro-mendonca** [comment]
I was trying to find it to correct a small issue.
Thank you :+1:
