### ISSUE TITLE
feature request:  language as template condition

### ISSUE THREAD

**Issue by JohnMulderFrance** [pojome/elementor#4280]
To me it would be a great help if i could use language as a condition. Menus, and in my case Footers, are different for each language. Now i need to list each page as a condition of its own to have the menu and footer appear in the right language. A condition like "all pages in english"  would be a great help. Especially when you have a site in 4 languages.

**Comment by bainternet** [comment]
There is no need for that as far as I know since you can simply set the language of the template and then create another one (linked) in a different language.

the language plugin should pick up the correct template based on the viewing language.

**Comment by JohnMulderFrance** [comment]
No, it does not. See https://wpml.org/forums/topic/elementor-new-footer-template-wpml/
Apparently Elementor and WPML have some synchronisation to do.
Since mono lingual sites hardly exist anymore, this looks like a serious issue to me.

**Comment by bainternet** [comment]
@JohnMulderFrance 

Sorry, you feel that way but elementor has nothing to do with translations what so ever.
