### ISSUE TITLE
[FEATURE REQUEST] Select underneath elements aside from clicking (Difficulty to select elements when using negative margins to overlap)

### ISSUE THREAD

**Issue by darkbing05** [pojome/elementor#4285]
**Hi Elementor Devs,**

Right now elementor is growing and it is now becoming really very powerful tool for wordpress. 

**But for advanced customization, such as by using overlapping elements through negative margins, it is very hard to select the layer underneath the above element.** 

I hope you could create an additional right click feature to display the list of elements that can be manually selected just like the way how underneath files / images are selected on microsoft word or like so. 

Or if you have a better idea to make selecting elements under another element would be better.

**-More power!**

**Comment by bainternet** [comment]
I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
