### ISSUE TITLE
[Feature request] Block with vertical nav menu in the Header

### ISSUE THREAD

**Issue by JohnMulderFrance** [pojome/elementor#4286]
It is a real pain to have a vertical sticky menu in the header. Special tricks are necessary and i have not been able to create a flawless vertical sticky nav menu, even with the help of your support.
Maybe it is a good idea to have a vertical header block, making it easier for non-coders to create a sticky vertical menu.

**Comment by bainternet** [comment]
@JohnMulderFrance 

We currently don't officially support vertical sticky menu, but once we do, rest assure we'll have some block for that.

thanks for the suggestion and sorry for the pain :wink:
