### ISSUE TITLE
Bug: Call To Action cell with blur hover effect flashes in Chrome

### ISSUE THREAD

**Issue by icecandy** [pojome/elementor#4288]
I am using an array of Call To Action widgets. The hover state is set to Blur using the CSS filter on the cell. This works fine in Safari and Firefox. In Chrome (version 66 latest on OS X High Sierra)) rolling out of the cell it flashes momentarily. It looks like when the blur effect is switched off there is a pixel blit that replaces the blurred image with the original image, thereby creating a flash between the states.

You can see this problem happening on the home page at https://vaneyssen.demo.site/. Just rollover the grid items which are each a Call To Action widget. The widget is set to Cover mode.

**Comment by icecandy** [comment]
I found a temporary solution that ameliorates (wow isn't that a great word :) ) the problem, but isn't perfect.
If I set the same image as the Call To Action image as the column cell background the flash isn't so prominent. It still isn't perfectly smooth though. This seems to work as normal in Safari and Firefox so it is a partial fix for Chrome.

Surely there must be a CSS fix for Chrome for this?

**Comment by bainternet** [comment]
Well, that's a nice Idea but like you said it's not perfect,  anyway feel free to reopen if you do find something we can implement on our side.

thanks.

**Comment by dp-op** [comment]
Instead of transtransition to : 
`filter: blur(0);`
you can go to 
`filter: blur(0.3px);`
