### ISSUE TITLE
Align the My Templates tab to match the Predefined Templates tab in design

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#429]
Would be totaly awesome if the Predefined and Custom Templates tabs had the same design - it is very imposrtant to give the end user a sense of look and feel of the designs available.

**Comment by cobicarmel** [comment]
It was our original plan. But we decided to use a separated look since plain custom template doesn't have a thumbnail.

We working on better solution for that.

**Comment by WPDevHQ** [comment]
Thank you for the response @cobicarmel 

Will take a look at how to go about generating a thumbnail at the dev level and how that can be pulled in to the design.
