### ISSUE TITLE
Mobile improvements and global widgets

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#4291]
Hello, a list of tiny improvements that could help us:

1 - Social share, option to disable text/label on is mobile;

2 - Posts widget, option to adjust column gap, alignment on mobile and carrousel option would be good too.

3- When I edit my global widget, I need to re-save where I have the global widget to make affect on  changes.

**Comment by bainternet** [comment]
@silvioghedin 

1) Maybe in the future.
2) Feel free to create your custom skins for it.
3) this seems like a caching issue, try clearing cache after you update a global widget and see if its updated everywhere, if not, please contact our support at support @elementor.com for guidance in resolving this issue.

thanks
