### ISSUE TITLE
Wrong float for acceptance label on mobile

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4295]
Hello!
There is wrong float for acceptance label on mobile.
![wrong_float](https://user-images.githubusercontent.com/12493645/39408469-81010f04-4bf8-11e8-9f2d-fdb24f6d7da8.PNG)
I think it's because of:
`.elementor-field-subgroup .elementor-field-option label {
    display: inline-block;
}`

The solution:
`.elementor-field-subgroup .elementor-field-option label {
    display: inline;
}`

**Comment by dasigna** [comment]
... this is even the same on desktop when having long text that exceeds one line -> relevant for new euopean data security sh*** things especially!
at the same time it would be great to have the possibility to manipulate the font settings within elementor style tab for acceptance, checkboxes and alike (and only for those alone) without sdditional css tweaking.

**Comment by arielk** [comment]
Fixed in v2.2.6, thanks for your feedback!
