### ISSUE TITLE
Column Impovement: Make columns a link

### ISSUE THREAD

**Issue by steveamazing** [pojome/elementor#4297]
## I have been asked many times to make an entire column clickable so that it is a link to another page.  For example, 3 columns that are side by side that each provide a quick overview of 3 different features.  Usually you see this with 3 items in a column ICON/HEADLINE/TEXT.   If you place a hoverover background color for the entire column, the goal is that an site visitor could click anywhere on the hoverover background color and be taken to a more in depth detail page for the feature.

Go to http://parallaxdemo.com/#services  Imagine when you over over the column that if for the "Woo Commerce" column that the user can click anywhere to go to a more detailed Woo Commerce feature page.

**Comment by arielk** [comment]
Duplicate of #351
