### ISSUE TITLE
Documentation (minor) BUG: SubstituteMaxLineLength10M

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4300]
The solution to bad gateway 502 - works fine!
But the recommendation on page [(https://docs.elementor.com/article/219-502-error-when-i-try-to-edit-with-elementor)]

has an error:
<IfModule mod_substitute.c>
SubstituteMaxLineLength10M
</IfModule>

MISSING SPACE before 10M

**Comment by bainternet** [comment]
@Mulli 

Nice catch, fixed!
