### ISSUE TITLE
Feature Request: Developer inject controls into existing widget, reuseable widget within widget. 

### ISSUE THREAD

**Issue by justpie** [pojome/elementor#4302]
Hi All, 

As a developer and themer there are times where I want to create a widget that uses other widgets i've created. There are also scenarios where I want to extend widgets and add my own controls. 

For example. My theme has a specific color palette that I want to force the users to use. These colors should apply to things such as headings and etc. Rather than creating my own heading widget which would essentially be the same as the default heading widget I would rather be given the ability to extend/inject a select control into the existing heading widget. 
 
Also lets pretend that I've made a custom anchor widget, a custom body widget,  and a  custom button widget. There are instances where I would like to use all three in a single widget that pulls all my of existing code and renders them appropriately. I know something similar can be done via custom sections but there are scenarios where sections don't work as well. 

Below is how I have currently implemented my solution, admittedly is pretty hacky but it should give you an idea of what i'm looking for. 

```PHP
protected function _register_controls() {
  $ctrls = new Widget_Heading();
  $controls = $ctrls->get_controls();
  $controls['title_color'] = [
    'label' => __( 'Color', $this->get_name() ),
    'type' => Controls_Manager::SELECT,
    'default' => 'salmon',
    'options' => $this->colors,
    'section' => 'section_title',
    'tab' => 'content'
  ];

  $this->_do_controls('widget_heading', $controls);
  $controls = new Widget_Text_Editor();
  $this->_do_controls('text_editor', $controls->get_controls());
  $controls = new Widget_Branded_Button();
  $this->_do_controls('branded_button', $controls->get_controls());
}
private function _do_controls($name, $controls) {
  if (is_array($controls)) {
    foreach($controls as $key => $control) {
      if ($control['type'] == 'section') {
        $this->start_controls_section(
          $control['name'],
          [
            'label' => __( $this->get_title() . ' - ' . $control['label'] ),
            'tab' => $control['tab']
          ]
        );
        foreach($controls as $key2 => $ctrl) {
          if( $ctrl['type'] != 'section' && $ctrl['section'] == $control['name'] && $ctrl['tab'] == $control['tab']) {
            $this->add_control(
              $name . '_' . $key2,
              $ctrl
            );
          }
        }
        $this->end_controls_section();
      }
    }
  }
}
```

**Comment by bainternet** [comment]
@justpie 

The whole idea of widgets as OOP is that you can extend them and only change what you want.

If you want to add controls of existing widget use the provided hooks:

```PHP
add_action( 'elementor/element/heading/section_title/before_section_end', function( $element, $args ) {
	// add a control
	$element->add_control( 'title_color', // update the control
		[
			'label' => 'Color' ,
			'type' => Controls_Manager::SELECT,
			'default' => 'red',
			'options' => [
				'red' => 'Red',
				'blue' => 'Blue',
			],
			'section' => 'section_title',
			'tab' => 'content',
		]
	);
}, 10, 2);
```
Same Hook applys for updating exsisting controls:

```PHP
add_action( 'elementor/element/heading/section_title/before_section_end', function( $element, $args ) {
	$elementor = \Elementor\Plugin::instance();
	// Get the control you want to update
	$control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'title_color' );

	if ( is_wp_error( $control_data ) ) {
		return;
	}
        // Alter the control
	$control_data['default'] = 'blue';
        // Update the control
	$element->update_control( 'title_color', $control_data );
}, 10, 2);
```

Other then that your code loops over the controls way too much, you should sort it once and the loop once more over it, but anyway your code can't handle control tabs.

Can you explain the use case of combaining 3 widgets in to one? seems way over loaded and messy.

**Comment by justpie** [comment]
@bainternet Hooks may be what i'm looking for. Do you by chance have an example of how I would update the output of Widget_Heading->render() using a hook? For example lets pretend that I want to wrap the Widget_Heading->render() output with a "<div class="{{{title_color}}}"> [ Widget_Heading_Render_HERE ]</div>"

As for combination of three widgets into one. When I create a website I like to create branded elements and I like to see that brand carried out through out the site. A lot of my clients want to be able to edit and modify pages as they please and I want them to be forced to use the branded elements I create. 

I understand technically I could create a branded section which includes all my custom widgets but the issue is that none if it is really required. Once they pull in a saved section they can remove / edit the widgets as they please within the saved section. I would like to create a way for them to be forced to use the sections that are defined by the designers.  

Hopefully that clarifies it better.

**Comment by bainternet** [comment]
@justpie 

You can use the `'prefix_class' parameter which will add the value as a class to the widget container:

```PHP
$element->add_control( 'title_color',
	[
		'label' => 'Color' ,
		'type' => Controls_Manager::SELECT,
		'default' => 'red',
		'options' => [
			'red' => 'Red',
			'blue' => 'Blue',
		],
		'prefix_class' => 'title-'
	]
);
```
and now the widget container will get a CSS class `.title-red` or `.title-blue` based on the selection.

as for limiting the clients editing abilities take a look at this: https://docs.elementor.com/article/329-role-manager
