### ISSUE TITLE
Form webhook request 

### ISSUE THREAD

**Issue by ericft** [pojome/elementor#4303]
Hi team,

I try to get a token from my webhook url using your pro form API but I cannot figure it out how to make a single request simultaneously with the submit. Our json is built to create a token only on new user submissions so only available on the first request.

Can you please help me with my problem or point me in the right direction? 

Additionally is it possible to make it 100% in JavaScript or I have to do it in PHP in my function.php?

Thank you for your support!

**Comment by bainternet** [comment]
our webhook is fired after the form has been submitted,

paste your code and I'll try to help.

**Comment by ericft** [comment]
I know it's wrong but this is what I am looking for:

add_action( 'elementor_pro/forms/webhooks/response', function( $response ){
	$obj = json_decode($response);
	echo $obj->response->auth_token;
} );
Then I want to put the token in a cookie in JS

Thank you

**Comment by bainternet** [comment]
Then in your case, you should use a custom webhook, for eaxample: 

```PHP

add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	$response = wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
		'body' => $fields,
	]);
	$response_json = json_encode( $response['body'] );
	$handler->data['auth_token'] = $response_json->response->auth_token;
});
```

Then on the front-end (JS) create the cookie:
```JS
<script>
	//The event is submit_success so you can catch it for example:
	jQuery( document ).ready(function( $ ){
		$( document ).on('submit_success', function( event, response ){
			if ( response.data.auth_token ) {
				var d = new Date();
				d.setTime( d.getTime() + ( 24*60*60*1000 ) );
				var expires = "expires="+ d.toUTCString(),
					cookie_name = 'MyAuthToken',
					cookie_value = response.data.auth_token;
				document.cookie = cookie_name + "=" + cookie_value + ";" + expires + ";path=/";
			}
		});
	});
</script>
```

bare in mind that tis is not tested and just an example, but it should get you started.

**Comment by ericft** [comment]
Perfect exactly what I was looking for. Thank you!

**Comment by ericft** [comment]
Hi Raz,

I'm trying to create a cookie at the same time I do the request, is there something wrong with my updated code? It seams that $cookie_value is not printing.

`add_action('elementor_pro/forms/new_record', function($record, $handler) {
	$form_name = $record->get_form_settings('form_name');
	if ('uform' !== $form_name) {
		return;
	}

	$raw_fields = $record->get('fields');
	$fields = [];
	foreach ($raw_fields as $id => $field) {
		$fields[$id] = $field['value'];
	}
	$response = wp_remote_post( 'https://staging.mysite.dev/contact', [
		'body' => $fields,
	]);

	$response_json = json_encode($response);

	$cookie_name = 'auth_token';
	$cookie_value = $response_json->response->auth_token;
	setcookie($cookie_name, $cookie_value, time() + (60), "/");
});`

Thanks in advance!

**Comment by ericft** [comment]
Hi @bainternet ,

I'm trying to create a cookie at the same time I do the request, is there something wrong with my updated code? It seams that $cookie_value is not printing.

add_action('elementor_pro/forms/new_record', function($record, $handler) {
$form_name = $record->get_form_settings('form_name');
if ('uform' !== $form_name) {
return;
}

$raw_fields = $record->get('fields');
$fields = [];
foreach ($raw_fields as $id => $field) {
	$fields[$id] = $field['value'];
}
$response = wp_remote_post( 'https://staging.mysite.dev/contact', [
	'body' => $fields,
]);

$response_json = json_encode($response);

$cookie_name = 'auth_token';
$cookie_value = $response_json->response->auth_token;
setcookie($cookie_name, $cookie_value, time() + (60), "/");
});

Thanks in advance!

**Comment by ericft** [comment]
@bainternet any idea?

Thanks
