### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by RocketGS** [pojome/elementor#4305]
To incorporate an ANIMATED HEADLINES function inside the Elementor SLIDES widget as an option.

**Comment by RocketGS** [comment]
I would like to be able to incorporate the animated headlines function inside the Elementor slide widget. 

As example you add the Elementor SLIDES widget to your page. In the slides you add your text to display but rather than it just being static text you are able to add the functions found in the Animated Headlines widget of "circle", "underline", "strikethrough", etc.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
