### ISSUE TITLE
Calendar of date field in Forms has a wrong z-index

### ISSUE THREAD

**Issue by Vadimoff** [pojome/elementor#4306]
Z-index of calendar  picker in fields "Date" (in Forms) has z-index less than forms z-index and doesn't visible: 
![1234](https://user-images.githubusercontent.com/38867852/39448063-721aa46c-4ccc-11e8-9b05-1f0b5a5c639b.jpg)
And it's impossible to change it.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
