### ISSUE TITLE
Preview broken with domain mapping again

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#4307]
Using multi-site in sub-domain mode with domain mapping the Editor does not work due to x-frame options error

**Console error**
Refused to display 'https://mapped-domain.com/?elementor-preview=1208&ver=1525119563' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

This was originally fixed with patch #2151

Has re-appeared somewhere after 2.0 - Can't give specific minor version as we upgraded to 2.0 and skipped further production upgrades until 2.0.8

**Comment by samuelcerezo** [comment]
When using diferent domain option in Polylang (domain mapping), Elementor only works in main domain.
In other languages, this error appears:

`Uncaught DOMException: Blocked a frame with origin "https://XXXXXXXXX.es" from accessing a cross-origin frame.`
