### ISSUE TITLE
Some shortcodes work in Text widget but not in the Shortcode widget

### ISSUE THREAD

**Issue by blue928** [pojome/elementor#4309]
I created a short, custom widget to display data via a shortcode within my elementor theme. The code is included at the bottom of this post for reference.

The shortcode widget is supposed to provide a live preview of the rendered shortcode. When I add my shortcode, nothing shows up. Although I can't reproduce it every time, sometimes I get a "500 internal server error" at the bottom of the Shortcode widget panel. When I save, the shortcode widget disappears; it never saves.

However, when I use the text widget as described in the shortcodes instruction video, the preview of course does not work, but after I save and view the live version of the page it works fine.

Although this is about my custom shortcode, other 3rd party shortcodes exhibit the same behavior such as Revolution Slider (but that was covered in #4131 I think.

Here is the custom code for reference:

```

function wc_get_calendar( $atts ) {

	$a = shortcode_atts( array(
		'id' => '',
	), $atts );

	if(empty($a['id'])){
		return "ID parameter cannot be empty";
	}

	$product = wc_get_product($a['id']);

	$booking_form = new WC_Booking_Form($product);



	ob_start();


	do_action( 'woocommerce_before_add_to_cart_form' ); ?>

	<noscript><?php _e( 'Your browser must support JavaScript in order to make a booking.', 'woocommerce-bookings' ); ?></noscript>

	<form class="cart" method="post" enctype='multipart/form-data'>

		<div id="wc-bookings-booking-form" class="wc-bookings-booking-form" style="display:none">

			<?php do_action( 'woocommerce_before_booking_form' ); ?>

			<?php $booking_form->output(); ?>

			<?php do_action( 'woocommerce_before_add_to_cart_button' ); ?>

			<div class="wc-bookings-booking-cost" style="display:none"></div>

		</div>

		<input type="hidden" name="add-to-cart" value="<?php echo esc_attr( is_callable( array( $product, 'get_id' ) ) ? $product->get_id() : $product->id ); ?>" class="wc-booking-product-id" />

		<button type="submit" class="wc-bookings-booking-form-button single_add_to_cart_button button alt disabled" style="display:none"><?php echo $product->single_add_to_cart_text(); ?></button>

		<?php do_action( 'woocommerce_after_add_to_cart_button' ); ?>

	</form>

	<?php do_action( 'woocommerce_after_add_to_cart_form' ); ?>

<?php
	$output = ob_get_contents();
	ob_end_clean();

	return $output;

	//return "foo = {$a['id']}";
}
add_shortcode( 'wc_product_calendar', 'wc_get_calendar' );
```

**Comment by bainternet** [comment]
Check your console and error logs to get an idea what is  the cause, but the only to ensure it will work in the Editor is to [create an Elementor Widget](https://developers.elementor.com/creating-a-new-widget/).

**Comment by blue928** [comment]
I don't mind creating a widget, but then what is the point of the shortcode widget that comes with Elementor? Is it not supposed to be for the exact purpose of displaying shortcodes in a live manner? This isn't just happening with my widget, it happens with several 3rd party widgets such as those from Themepunch and WooCommerce.

I don't think the community can be expected to _recreate_ existing third party widgets as elementor widgets.

Why would some shortcodes work with the Shortcode Widget and others not? Would such behavior not be considered a bug with the Shortcode Widget?
