### ISSUE TITLE
Blog POST - Pro - do not display an article already displayed on the same page

### ISSUE THREAD

**Issue by NAROLLES** [pojome/elementor#4312]
Hi
I'm sorry but I'm a beginner here - thank you for telling me if there is better place here to post my suggestion - I come on board of elementor support

Would it be possible to have an additional option to that of "skipping" one or more articles (which may be convenient in some cases). The addition of the option "do not display an article already displayed on the same page" (this exists at Divi and very practical,)

thanks #

**Comment by bainternet** [comment]
@NAROLLES 

Can you explain? elaborate? what are you trying to do? whats missing?

**Comment by NAROLLES** [comment]
Hi
I run an online press site
here is an example

if you see my homepage of my site (currently under renovation) https://www.jardinerie-animalerie-fleuriste.fr/
there is a bloc at the front "featured post"
thematic blocks either by theme, by chronology, or by the authors
Of course in some cases in a bloc I can use the function "jump"
but when it is with multiple blocs it is not manageable to avoid the same display of an article

on another page like those of categories
I can present first articles "featured post"
then items in the order of dates of the same category
in this case also this function is useful

For info it exists at Extra Divi
it's at least one of the few things I liked about them

The highlighting of an article is also a good thing
that is to say to be able to check that this article is remarkable
this also makes it possible to make a different classification
but I recognize that this is another less urgent problem that can be overcome by a label or another category

am I clearer
thanks

**Comment by bainternet** [comment]
I merged this issue with  #1878, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
