### ISSUE TITLE
Post Nav Widget - Pro - Nav by current category or tags

### ISSUE THREAD

**Issue by NAROLLES** [pojome/elementor#4313]
Hi
suggestions

post nav widget - If possible, provide the following options on this widget: "on all posts", "by category" or by "tags", oceanwp allows it in the single item setting but not Elementor for this same feature

thanks

**Comment by followeyes** [comment]
Hi.
Suggestions:

1- Title gradients color
2- Image galleries open on light-box with thumbnails shown for the other images.
3- Option to make footer sticky.
4- Including PWA (Progressive Web App) feature with add to Home-screen option for mobile device views.

Thanks a lot.
Kepp up the good work.

**Comment by bainternet** [comment]
Duplicate of #4177
