### ISSUE TITLE
Dynamic Resizing of Columns

### ISSUE THREAD

**Issue by moshemo** [pojome/elementor#4314]
I am wondering if there is a way to dynamically resize columns depending on the amount of content inside the column? 

For instance, imagine I have a search bar in one column next to a nav menu in the other column.  What I would like is for the two columns to automatically resize depending on the number of menu items.  I can do this with some custom-css and use flex-box -- but I was wondering if this is possible without adding any custom-css?
If not -- perhaps you could add some flex-box options in the advanced tab so that columns (or elements) can automatically resize when needed.

Thanks.

**Comment by eligence** [comment]
+1

having the option to allow flex grow and shrink on some columns while setting a flex basis on others would be a game changer. I've had to use custom css to accomplish this task and it makes working with the editor very difficult.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, only via custom CSS.

Thanks for the feedback.
