### ISSUE TITLE
[Developers] Truly reload the editor

### ISSUE THREAD

**Issue by alessandrotesoro** [pojome/elementor#4315]
Hi there,

Apologies for opening another "issue" this'll be the last one 🤞! The following question is connected to my previous one https://github.com/pojome/elementor/issues/4304

Instead of changing the preview url, I've added a new page setting and a "visibility" setting for all widgets. When that page setting is changed I'm saving the editor and then reloading the preview. This technically works as it should, in fact I'm seeing the output of the changed setting correctly in the preview, however widgets aren't being truly updated. 

I'm not sure if this is a bug with Elementor or with my code. Basically when my custom setting is changed, all widgets appear again and don't follow the given visibility setting. This only happens when the editor is reloaded internally with it's api. If I hard refresh the browser page, the conditions are working fine, which leads me to believe it could be a bug with Elementor or maybe it just isn't supported. 

This is my code for reloading the window, which again, works fine, but widgets aren't truly updated.

```
elementor.pageSettings.addChangeCallback('simulated_tab', function (newValue) {
	elementor.saver.update({
		onSuccess: function () {
			elementor.reloadPreview();
			elementor.once('preview:loaded', function () {
				elementor.getPanelView().setPage('page_settings');
			});
		}
	});
});
```

I've even tried with `location.reload(true)` but I'm getting the same result. 

Via php with `elementor/widget/render_content` I'm doing this ( the example here is only for the image box widget as I'm testing it ).

```
if( \Elementor\Plugin::instance()->editor->is_edit_mode() ) {
	$page                   = \Elementor\PageSettings\Manager::get_page( $page_id );
	$editor_active_tab      = $page->get_settings( 'simulated_tab' );
	$editor_widget_settings = $widget->get_settings();
	$editor_visibility      = isset( $editor_widget_settings[ 'selected_visible_tabs' ] ) ? $editor_widget_settings[ 'selected_visible_tabs' ]: false;
	if( $widget->get_name() == 'image-box' ) {
		if( ! in_array( $editor_active_tab, $editor_visibility ) ) {
			return false;
		}
	}
}
```

I'm guessing this is a server side thing, is there any way to completely reload everything? Alternatively is it possible to update the js preview template of all widgets to add a custom element? In this way i'll be able to tell the user that the widget has been assigned to a tab so that the preview doesn't get too confusing.

Thank you.

**Comment by bainternet** [comment]
@alessandrotesoro 

this will not work, the preview reload is meant for loading templates with a placeholder for the widgets which then the editor ( the top window which holds the widget's data and is not reloaded/changed/updated) fills the placeholder with the widget's data.

 Basically, what you are looking for is not currently possible.

**Comment by alessandrotesoro** [comment]
I understand, that's fine anyway. Thanks a lot.
