### ISSUE TITLE
Hello World Plugin Not Working

### ISSUE THREAD

**Issue by elusivethemes** [pojome/elementor#4318]
Hi,

Im trying to setup a custom element and Ive tried using the Hello World Demo Plugin by simply copying the complete plugin folder to my wordpress plugin folder but nothing happens and no custom element is added.

I've also tried using the demo code written here : 

https://developers.elementor.com/creating-a-new-widget/

But i get a  Class 'Elementor\Widget_Base' not found

Any ideas ?

Thanks.

**Comment by bainternet** [comment]
I guess you missed the last part 
https://developers.elementor.com/creating-a-new-widget/#Final_Notes

> Your plugin should only include the widget class file if Elementor is active and loaded.


Take a look at our demo plugin https://github.com/pojome/elementor-hello-world

@ramiy @matipojo

**Comment by bainternet** [comment]
The demo plugin adds two widgets: "hello world", and "Inline Editing" widgets

I guess you missed the last part :
https://developers.elementor.com/creating-a-new-widget/#Final_Notes


> Your plugin should only include the widget class file if Elementor is active and loaded.

**Comment by elusivethemes** [comment]
Thanks for the response. I did notice the last part and elementor is installed and active. Any other reasons why It might not be working ? I though the demo plugin would work straight out of the box.
