### ISSUE TITLE
Future Request

### ISSUE THREAD

**Issue by gatenet** [pojome/elementor#4322]
Hello Elementors, I first want to say that your plugin is the best ever, very nice job and keep up

I use elementor from the firsts days when it was only aboyt 1000 active installs and send you any recomendation or never had any problem with the plugin.

I think its time for me to contribute with one suggestion that maybe make the work flow even more faster.

So when we place a section in a page and then put columns and finally elements, when we want to stylize the element or the column or the whole section we must push respectively the section, column etc, how about if the user is inside the element and stylizes it, the left elementor menu presents the hole hierarchy till the section in an accordion menu that will not have to select the columns or the section to stylize it? I think it will be faster to finish stylizing a whole section without having to jump from element to column an then to section.

Just a  thought
Thank you

**Comment by bainternet** [comment]
I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
