### ISSUE TITLE
Cannot scroll in Block Categories

### ISSUE THREAD

**Issue by cavalierlife** [pojome/elementor#4325]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When trying to select a block from the templates, the scrollbar isn't working correctly, and isn't letting me view and/or select some of the available blocks. Tried in both Firefox and Chrome. Tried different domains, different servers, different hosts, incognito browsers, brand-spanking-new WP installs, adjusting the browser zoom level, with no plugins, no scripts, no additional css, no functions, no hooks running, no console errors. Tried both GeneratePress and default WP TwentySeventeen themes. 

Seems to only happen if I choose a category such as Hero. If I just leave it at All categories, then scrolling and selecting works fine.

I checked with the membersin the Elementor FB group. Most don't have the issue but a few do, so it's not just me. I posted a video in that thread to show the problem. The thread is at https://www.facebook.com/groups/Elementors/permalink/1492348637557584/

## Steps to reproduce

Install Elementor and Elementor Pro. Add from Template. Choose Blocks. Choose one of the categories such as Hero. Unable to scroll down or choose any block below the scroll's fold.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.36
	PHP Version: 7.2.4
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: https://chirocollar.com
	Home URL: https://chirocollar.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 96M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.0.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

== Active Plugins ==
	Elementor
		Version: 2.0.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.3
		Author: Elementor.com

	GP Premium
		Version: 1.6.2
		Author: Tom Usborne

	WooCommerce
		Version: 3.3.5
		Author: Automattic

	WooCommerce PayPal Express Checkout Gateway
		Version: 1.5.3
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 4.1.2
		Author: WooCommerce


== Debug ==
	Errors: 
		TypeError: this.dataAdapter is null
			at https://chirocollar.com/wp-content/plugins/elementor/assets/lib/select2/js/select2.full.min.js?ver=4.0.5 - 1:61197
			2018-05-01 23:06 +00:00
			x 2 times

				
```
</details>

**Comment by obe1968** [comment]
Confirmed having the same issue on Firefox Quantum - 59.0.2

Environment : 

Server Environment			
Operating System: Linux			
Software: Apache					
MySQL version: 5.6.36
PHP Version: 7.0.29
PHP Max Input Vars: 3000
PHP Max Post Size: 128M
GD Installed: Yes
Write Permissions: All right
Elementor Library: Connected

If adding a template from the library, with no category selected, then I can scroll the whole page. If I choose a category, the scrollbar will not work within a category.

Shawn

**Comment by iCoachLive** [comment]
Can confirm. On Hero section. Have not tested others.

**Comment by dax702** [comment]
Confirm, happening to me too, but not isolated to just Hero blocks, happens on any blocks as well as page templates too.

**Comment by bainternet** [comment]
@cavalierlife @obe1968 @iCoachLive @dax702 

Thanks we can replicate.

**Comment by obe1968** [comment]
Elementor staff...

Do we please have an update on this? The only thing we see is it is moved to the bug section. Are we going to get a resolution soon?

Please advise...

Thanks :)

**Comment by cavalierlife** [comment]
The latest update did NOT solve this problem.

**Comment by obe1968** [comment]
I have replied to the closed issue above as well. Myself and two other users who originally had this problem have confirmed that it is still not working in FF or Chrome after upgrading to 2.0.10. Please advise...

Thank you...

Shawn

**Comment by smaquilon** [comment]
The latest update did NOT solve this issue, please reopen it.

**Comment by obe1968** [comment]
Elementor 2.0.10
Elementor Pro 2.0.5

All caches have been cleared, and many others have posted on Facebook Elementor Community group that after updating and caches being cleared, the issue remains not solved.

Shawn

**Comment by pixelturm** [comment]
Still the same issue; FF and Chrome, browsers + plugins are updated, cache is cleared, in incognito-mode the same, kr

**Comment by obe1968** [comment]
Replied to ticket# 4394 as well...

Lyle posted on FB a work around for some. When you first choose a category, scrolling does not work. Then choose the same category a second time, and then you can scroll. But like I said, this workaround is not working for all users, and is still a bug.

**Comment by obe1968** [comment]
Tested earlier today on Firefox quantum, and still does not work in FF, but it does on Chrome.
