### ISSUE TITLE
Feature Request text flowing from one column to the next

### ISSUE THREAD

**Issue by insight56** [pojome/elementor#4326]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by insight56** [comment]
The ability for text to reflow in a mulit-column container is very important. The document industry utilizes this feature in word-processer to page layout applications. It is time for someone to step up. This feature would also benefit in various size display devices.

When you decide to implement this ability incorporate both a fixed image location as well as the ability to reflowing the image  and anchored to specific text selection.
