### ISSUE TITLE
Feature request: Breadcrumbs as dynamic / Pro element

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4329]
Breadcrumbs is part of theme construction.
Is it on road map?
Or did I missed it completely?

I did not find an issue about it on Github nor element in pro-elementor.
Currently, I am using my own shortcode based on Pojo theme.

**Comment by bainternet** [comment]
Look again, We have a breadcrumbs widget which is based on yoast.

**Comment by bainternet** [comment]
@Mulli 

make sure you have Yoast SEO installed and active.

**Comment by Mulli** [comment]
I guess I have to have YOAST because I do not see it without installing it.

 

AND another issue: Left bar of Elementor at the bottom:

 

NOREWP'S ELEMENTOR MODULES

 

Chane the N to M and add spaces where needed… 😊

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal

**Comment by bainternet** [comment]
Actually "NOREWP'S ELEMENTOR MODULES"  is correct and it's not native to elementor it's 3rd party plugin developed by [Nore](https://profiles.wordpress.org/norewp#content-plugins)
https://profiles.wordpress.org/norewp#content-plugins

thanks

**Comment by Mulli** [comment]
Hi  Ohad

 

I added Yoast plugin to get breadcrumbs element as you suggested.

 

After activation & before using the breadcrumbs element I started seeing:

"server error" – upon saving page/post with Elementor Pro

and the post/page was saved ok! – 

BUT sometimes

"server error 503" – upon saving with Elementor Pro, COULD NOT SAVE

 

After deactivating some plugins it was clear that adding Yoast is adding the problem.

 

Please find the attached system info file.

 

Any suggestions how to solve the issue?

http://kreston.site2goal.co/en

 

 

Thanks!!

Mulli

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal

**Comment by Mulli** [comment]
Another important issue:

 

My debug.log contains:

includes/rest-api/class-wp-rest-server.php on line 1248

[04-May-2018 07:56:45 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/site2goa/public_html/kreston.co.il/wp-content/themes/buzz/core/helpers/class-pojo-breadcrumbs.php:24) in /home/site2goa/public_html/kreston.co.il/wp-includes/rest-api/class-wp-rest-server.php on line 1248

[04-May-2018 07:56:45 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/site2goa/public_html/kreston.co.il/wp-content/themes/buzz/core/helpers/class-pojo-breadcrumbs.php:24) in /home/site2goa/public_html/kreston.co.il/wp-includes/rest-api/class-wp-rest-server.php on line 1248

 

And in my functions.php I have: (used in all inner pages, theme: buzz-child)

 

add_shortcode('get-breadcrumbs', 'get_breadcrumbs');

function get_breadcrumbs(){

     return pojo_breadcrumbs();

}

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal

 

From: mulli@site2goal.co.il <mulli@site2goal.co.il> 
Sent: Friday, May 4, 2018 9:43 AM
To: 'pojome/elementor'‏ <reply@reply.github.com>
Subject: HELP... Yoast+Elementor integration issue

 

Hi  Ohad

 

I added Yoast plugin to get breadcrumbs element as you suggested.

 

After activation & before using the breadcrumbs element I started seeing:

"server error" – upon saving page/post with Elementor Pro

and the post/page was saved ok! – 

BUT sometimes

"server error 503" – upon saving with Elementor Pro, COULD NOT SAVE

 

After deactivating some plugins it was clear that adding Yoast is adding the problem.

 

Please find the attached system info file.

 

Any suggestions how to solve the issue?

http://kreston.site2goal.co/en

 

 

Thanks!!

Mulli

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

 <https://facebook.com/site2goal> https://facebook.com/site2goal

**Comment by Mulli** [comment]
THE BUG IS MINE.

 

All is ok now

Sorry for the noise I made…

 

Best

Mulli

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal

 

From: mulli@site2goal.co.il <mulli@site2goal.co.il> 
Sent: Friday, May 4, 2018 11:06 AM
To: 'pojome/elementor'‏ <reply@reply.github.com>
Subject: RE: HELP... Yoast+Elementor integration issue

 

Another important issue:

 

My debug.log contains:

includes/rest-api/class-wp-rest-server.php on line 1248

[04-May-2018 07:56:45 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/site2goa/public_html/kreston.co.il/wp-content/themes/buzz/core/helpers/class-pojo-breadcrumbs.php:24) in /home/site2goa/public_html/kreston.co.il/wp-includes/rest-api/class-wp-rest-server.php on line 1248

[04-May-2018 07:56:45 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/site2goa/public_html/kreston.co.il/wp-content/themes/buzz/core/helpers/class-pojo-breadcrumbs.php:24) in /home/site2goa/public_html/kreston.co.il/wp-includes/rest-api/class-wp-rest-server.php on line 1248

 

And in my functions.php I have: (used in all inner pages, theme: buzz-child)

 

add_shortcode('get-breadcrumbs', 'get_breadcrumbs');

function get_breadcrumbs(){

     return pojo_breadcrumbs();

}

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

 <https://facebook.com/site2goal> https://facebook.com/site2goal

 

From: mulli@site2goal.co.il <mailto:mulli@site2goal.co.il>  <mulli@site2goal.co.il <mailto:mulli@site2goal.co.il> > 
Sent: Friday, May 4, 2018 9:43 AM
To: 'pojome/elementor'‏ <reply@reply.github.com <mailto:reply@reply.github.com> >
Subject: HELP... Yoast+Elementor integration issue

 

Hi  Ohad

 

I added Yoast plugin to get breadcrumbs element as you suggested.

 

After activation & before using the breadcrumbs element I started seeing:

"server error" – upon saving page/post with Elementor Pro

and the post/page was saved ok! – 

BUT sometimes

"server error 503" – upon saving with Elementor Pro, COULD NOT SAVE

 

After deactivating some plugins it was clear that adding Yoast is adding the problem.

 

Please find the attached system info file.

 

Any suggestions how to solve the issue?

http://kreston.site2goal.co/en

 

 

Thanks!!

Mulli

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

 <https://facebook.com/site2goal> https://facebook.com/site2goal
