### ISSUE TITLE
Fix: Height of youtube videos inside single post widget

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#4330]
Hello guys, I've open the ticket support but it seems you are not understanding the problem.

I have my posts and inside my posts I have the link of youtube, when I see the post it supposed to see the iframe video like happens with the other themes. But the height is wrong. You need to fix this.

**Comment by bainternet** [comment]
@silvioghedin 

Please follow guidelines to open a new issue,

we can't possibly help like this.
