### ISSUE TITLE
Feature request: Dynamic skins!

### ISSUE THREAD

**Issue by JustDevelop** [pojome/elementor#4331]
Hi,

I'm a developer myself (and started with Elementor a few weeks ago) and I am hoping for an awesome feature. I dived into the Elementor Pro plugin code and the posts widget is very awesome! Though it can be so much cooler than this. How?

-> There is an option to select a skin
What if there was an option under "Elementor -> templates", where you kan select the "Skin" template type? And when you edit the posts widget for example, that you can select this template as a skin?

This will give A LOT of flexibility. You can just create your card at the Elementor templates page and just select it at the widget.

The funny thing is... This way, widgets can be very generic like "Grid widget, list widget" and so on. And you can just select the correct post type and template in the widget configuration options.

I hope I can get some feedback on this feature. I think it will be a huge improvement for Elementor.

Please let me know! Thanks in advance.

**Comment by bainternet** [comment]
@JustDevelop 

Nice idea.

We do have plans to allow in one way or another to let you design/style/build your own loop Item and use that as skin (again, in one way or another )

thanks for the feedback.

**Comment by chemocool** [comment]
Like this idea too... I don't use Elementor Pro "Posts widget" for this reason.

I use "Single" templates for my custom post types (and it's awesome), but for the archive pages, i had to create my own php files to handle them since "Posts widget" lacks (for now) the flexibility i need.

Converted my whole site to use section/header/footer/single templates in less than a day of work, so i'm happy i will eventually be able to have "archives" page too ;)

Great work and great support guys.

**Comment by black-eye** [comment]
+1 Oh yes, this would be awesome!
Something similar as AEPro Blocks (https://aedocs.webtechstreet.com/article/9-creating-block-layout-in-anywhere-elementor-pro).

**Comment by dudaster** [comment]
https://wordpress.org/plugins/ele-custom-skin/

**Comment by nicomollet** [comment]
The plugin from @dudaster is excellent. Please consider designing a feature like it does. Thank you.

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
