### ISSUE TITLE
Custom Font Error in Latest Elementor Pro

### ISSUE THREAD

**Issue by ronaldkubo** [pojome/elementor#4334]
Hi there,
I noticed an error in the latest Elementor Pro in my installation when creating a custom font: when I saved the font after uploading files it would save it as a normal post, and nothing appears in the custom fonts where it should be saved. I reverted back Elementor and Elementor Pro to the rollback version and then it did work. I use GeneratePress Pro and no plugins that I would say would mess with the custom font function.

Please check if this error occurs in a clean installation as well.
Ronald

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.

Also next time please follow guidelines to open a new issue.
