### ISSUE TITLE
Sematic HTML

### ISSUE THREAD

**Issue by Basilakis** [pojome/elementor#4339]
Hi,

Can you please explain me and maybe I can understand why you do not have title links on BLOG / Posts element on PRO?
Same goes for alt / title to images.

What is the idea behind it?

**Comment by dotpdesign** [comment]
Not the only one who cares. I wonder the same myself. Make it so Elementor.

**Comment by bainternet** [comment]
@Basilakis 

If you have a specific request for enhancement please feel free to 
Thanks for the feedback, follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.

thanks.
