### ISSUE TITLE
Feature Request: The Nav widget

### ISSUE THREAD

**Issue by jus303** [pojome/elementor#4340]
**Feature Request:** The Nav widget is great but for the sticky function, we need a lot more 'functions'. For example: Opacity change 'on scroll' Say from 0% opacity to %100 at 10% down from scroll start. The nav/header should be able to sit 'over' the top content. Nav/header depth change on scroll e.g big logo on page load, 'shrinks' on page scroll... it's pretty standard. See here note the bar above the nav also hides and shows at scroll - awesome stuff and keep up the good work! http://justineasthall.com/fatbeta/   Oh and responsive logo options too!

**Comment by moseskerub** [comment]
Maybe it's possible that when the sticky header - sticks to the top, the rest of the page wouldn't go underneath it, but instead the the bottom of the sticky header would act the the highest point of the screen. this way linking to a section down the page wouldn't scroll the page to below the header, but right after the header.
