### ISSUE TITLE
Features Request : New Generation of Building Using Elementor & Elementor Pro

### ISSUE THREAD

**Issue by DrMohamedGamal** [pojome/elementor#4341]
Hello ,
I seek if it possible to add a feature to build a custom loop for posts like magazine sites
for example
#1 post is 1/2 of the row
this feature is possible when creating post loop in Toolset Views , Why not to build it visually using Elementor or E Pro ?

Why not to add some extra dynamic features like 
1- Hover Effects for buttons on posts like this
https://essential.themepunch.com/clients-grid-lyndon/
or This
https://essential.themepunch.com/masonry-blog-jimmy-carter/

2- select which field would be displayed instead of featured images and post titles ?

3- Inline Conditional Output for text , widgets and even images?

4-Add a Conditional Output Widget like shortcode widget that load any inner codes like html , shortcodes , php codes , content templates ..etc so that I can created conditional output completely easy

5- Add a Hover Effects Like FlipBox Widget with extra hovering effects like front box contain some data
the back box contain others and specify every item displaying 

6- Add Ability to hook inline related posts or implement an html or JS code within post content "in the post content widget with % scrolling or # of Paragraphs " so that I can display dynamic content contain Related Posts , Google Ads ... etc

7- The PopUp box .............
This is very very important to be included within Elementor Widgets and with more features like display every # of dayes or users roles or even page intent or exent or scrolling to specific ID or % of page
and make it possible to view the popup using an icon , button or without anything for auto display

Hope You Create these and Make Elementor The Biggest on The Planet

**Comment by deckerweb** [comment]
Maybe this goes in the right direction?
https://wordpress.org/plugins/ele-custom-skin/
@dudaster

**Comment by DrMohamedGamal** [comment]
Yes It's Good
But what about other features ?
I think anywhere Elementor does something like that but I need more features in Elementor and not to use huge set of plugins

**Comment by dudaster** [comment]
Actually I'm working on a separate plugin that adds conditional display (false will not display, true will display) for elements and widgets. First will be basic like a single text area with a condition like this: "$post_date > $current_date && $in_stock" but later on ,if it will become popular, I bet Elementor team would implement it in a much elegant way. 

Stay tune next week!

I also have a working plugin that creates dynamic content for image galleries, flipboxes, image background etc. but it is optimized for Eletheme and it is not release ready. Hopefully Elementor would release this kind of features in the near future (dynamic value for every widget). Here are some examples of Eletheme and so called Eleplug module that does al this possible: http://motiko.1002.ro/deserturi/ , http://www.echipamente-termice.ro/produs/5mxm90m-unitate-exterioara-aer-conditionat/

The above examples don't have any custom code, every page was made with elementor, everything with elementor and they were made a year ago.

**Comment by DrMohamedGamal** [comment]
@Dudaster
Ok I agree with you , then can you create such plugin with these requests ?

**Comment by dudaster** [comment]
https://github.com/dudaster/ele-conditions

I need to do some tests and I'll submit it in wordpres plugin repository. Conditions section you'll find in Style tab for every element.

**Comment by DrMohamedGamal** [comment]
Just imagine if We have a plugin that is 
Elementor Toolkit

That adds the following features :

1- Copy & Paste Elements and Styles
2- Full Comperhensive Condtional System for widgets e.g.
* Post meta values ( date , text ...etc)
* Term meta value 
* Parent Post type meta value
* Parent Post type category

3- Link option to column or widget

4- Custom query builder for posts or any cpt

5- Multiple selection of post types and display posts according to the current category or Ability to query posts as related posts

6- Filtering options for posts according to meta values , terms ..etc

7- Animated text in placeholder forms

8- Display fields of parent poalst types

9- Display Fields from selected term

This would be great for any Plugin created to be rich based on Elementor Toolkit

**Comment by bainternet** [comment]
Thanks for the suggestions.

Closing as most of these were already asked and managed on different issues.

Also, next time please only one feature per Github issue.

thanks.
