### ISSUE TITLE
Display issue with tags in Post Info widget

### ISSUE THREAD

**Issue by Hunuke** [pojome/elementor#4342]
## Prerequisites

- [x] The issue still exists against the latest stable version of Elementor.

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

## Description

There is an issue with the display of tags in the _Post Info_ widget.

If _Link_ is enabled tags are displayed like:
tag1, tag2, tag3

If _Link_ is disabled tags are displayed like:
tag1 , tag2 , tag3
(with one additional empty space before the comma)

![elementor-meta-data-issue](https://user-images.githubusercontent.com/37901215/39619196-39566626-4f87-11e8-99a6-8a0a8ac190de.jpg)

**Comment by arielk** [comment]
Fixed for E-Pro v2.0.8

Thanks for your reporting

**Comment by Hunuke** [comment]
Thank you!
