### ISSUE TITLE
editor preview with 'content only' capabilities does not  show as expected

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#4344]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When setting a user role (editor) to only having the ability to edit content in elementor the page shows weird in wysiwyg editor -> it does not reflect any settings of padding, margins etc. which is really confusing and nearly unusable because all the content literally sticks together.

## Steps to reproduce

set role to 'edit content only' in elementor role manager and try to edit with elementor

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
