### ISSUE TITLE
Can't edit My Templates anymore

### ISSUE THREAD

**Issue by carlosnpz** [pojome/elementor#4346]
Hey guys!
I'm getting the following error when tying to edit any of the templates in Elementor > My Templates:
"The preview could not be loaded"

I'm using Elementor 2.0.9 and Elementor Pro 2.0.4 and have already deactivated all other plugins, reinstalled Elementor and Elementor Pro, cleared cache, but the error persists only in My Templates. Cen't even create new ones.

It works fine when trying to edit pages or posts with Elementor.

What may be causing this and how to solve it? I'm desperate, cause I need to lauch a website soon, but have some things to edit in Header template. :'(

Elementor Debug shows me theses errors:
`ViewDestroyedError: View (cid: "view757") has already been destroyed and cannot be used.
			at http://localhost:8012/revitaliza/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-04-24 01:43 +00:00

		TypeError: t[e.name].each is not a function
			at http://localhost:8012/revitaliza/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.8 - 2:151308
			2018-03-18 23:43 +00:00
			x 6 times

		TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
			at http://localhost:8012/revitaliza/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=1.15.3 - 2:30297
			2018-03-18 21:59 +00:00`

**Comment by bainternet** [comment]
please follow guidelines to opening a new issue, so we can help you better.
