### ISSUE TITLE
Child theme support

### ISSUE THREAD

**Issue by themedleb** [pojome/elementor#4347]
The ability to copy php/js files from Elementor & Elementor Pro to the child theme folder and customize them, like what we do with themes. It is so much useful if we want to customize existing Elementor widgets and add extra functionalities to them.

**Comment by bainternet** [comment]
@themedleb 

Elementor and Elementor pro are plugins and not a theme so they can't have a child theme, now that said you can change/extend/customize existing widgets via the provided hooks ( the old WordPress way)

**Comment by themedleb** [comment]
I know they are not themes, It's just came this way to my head since I already customized a plugin by putting its PHP functions files inside the child-theme folder.

Can you please lead me to these Elementor hooks you talked about?

**Comment by bainternet** [comment]
here you go: https://code.elementor.com/hooks/

**Comment by themedleb** [comment]
@bainternet Thank you.

**Comment by newalliancetecnologia** [comment]
Hi, I have Elementor Hello Theme installed and when trying to make a Child Theme for it I encountered difficulties, whenever active the theme my site goes out of tune, could you help me?
