### ISSUE TITLE
Elementor - Yoast (Breadcrumb) problem: SERVER ERROR

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4348]
I had a short code that used:
`add_shortcode('get-breadcrumbs', 'get_breadcrumbs');
function get_breadcrumbs(){
    return pojo_breadcrumbs();
}`
After adding Yoast - it was changed to:
`if ( function_exists('yoast_breadcrumb') ) {
         yoast_breadcrumb('<p id="breadcrumbs">','</p>');
   } `
all works well - BUT
I get SERVER ERROR on every *save* and the post is saved.
Further testing: If I comment out the `yoast_breadcrumb()` call - all is well.

Note that the "native" Yoast breadcrump element works well for me (I tested it).
I don't use Yoast breadcrump element -
Because I have no way to global change my old shortcode element with the new Yoast element... :-)
and I have over 120 posts to modify...
**REQUEST: How to global change element instance A with Element Instance B?**

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
