### ISSUE TITLE
Make the whole icon-box a link (not only icon & title)

### ISSUE THREAD

**Issue by msbt** [pojome/elementor#4351]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I'm using multiple icon-boxes as an overview of subpages and it would be nice if the whole icon box and not only the icon & title were linking to those pages. This would make it easier to navigate there (especially if you have a hover effect with border or shadow and nothing is clickable except those two smaller areas).

## Steps to reproduce
Add an icon-box widget and link to something.

I was also poking around in icon-box.php and added
`<a href="<?php echo $settings['link']['url']; ?>">`
before
`<div class="elementor-icon-box-wrapper">`
but elementor immediatly closes up the `</a>` so it can't wrap around the div, if there was a way to prohibit elementor from doing that, I would be good to go. Although, having that included in the regular release (which would also be update-safe) would be much nicer.

Best regards,
M

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by ShadowXVII** [comment]
Interested in this also. Call to Action does this, so a similar option on Icon Box would be useful.
(Call to Action doesn't support Icons, otherwise I'd use that).

**Comment by msbt** [comment]
I've manually edited elementor/includes/widgets/icon-box.php like this to achieve the link:

```
<div class="iconlink">
	<a class="exiconlink" href="<?php echo $settings['link']['url']; ?>">
		<div class="elementor-icon-box-wrapper">
		<?php if ( $has_icon ) : ?>
			<div class="elementor-icon-box-icon">
				<<?php echo implode( ' ', [ $icon_tag, $icon_attributes, $link_attributes ] ); ?>>
				<i <?php echo $this->get_render_attribute_string( 'i' ); ?>></i>
				</<?php echo $icon_tag; ?>>
			</div>
			<?php endif; ?>
			<div class="elementor-icon-box-content">
				<<?php echo $settings['title_size']; ?> class="elementor-icon-box-title">
					<<?php echo implode( ' ', [ $icon_tag, $link_attributes ] ); ?><?php echo $this->get_render_attribute_string( 'title_text' ); ?>><?php echo $settings['title_text']; ?></<?php echo $icon_tag; ?>>
				</<?php echo $settings['title_size']; ?>>
				<p <?php echo $this->get_render_attribute_string( 'description_text' ); ?>><?php echo $settings['description_text']; ?></p>
			</div>
		</div>
	</a>
</div>
```
This is not update-safe, so use that only when you're in charge so you can fix it after updates.

**Comment by daniilicic** [comment]
I agree with the OP. 
There should at least be an option/checkbox as the Call To Action element has, "Apply link on the whole box".

**Comment by badcat** [comment]
> This is not update-safe, so use that only when you're in charge so you can fix it after updates.

Could this code somehow be altered to work in a theme's functions.php file, hopefully negating any update issues.

**Comment by lucidpsimc** [comment]
I would also love for this feature to be implemented. I got user feedback of my recent site design asking why the entire icon box was not clickable.

@msbt I tried your code but I still run into the problem of Elementor/WP immediately closing my link after it loads it in my browser. Any suggestion?

**Comment by msbt** [comment]
@lucidpsimc I haven't upgraded to the latest version, but my code looks like this:
```
<a class="link" href="<?php echo $settings['link']['url']; ?>">
	<div class="elementor-icon-box-wrapper">
	<?php if ( $has_icon ) : ?>
		<div class="elementor-icon-box-icon">
			<<?php echo implode( ' ', [ $icon_tag, $icon_attributes, $link_attributes ] ); ?>>
			<i <?php echo $this->get_render_attribute_string( 'i' ); ?>></i>
			</<?php echo $icon_tag; ?>>
		</div>
		<?php endif; ?>
		<div class="elementor-icon-box-content">
			<<?php echo $settings['title_size']; ?> class="elementor-icon-box-title">
				<<?php echo implode( ' ', [ $icon_tag, $link_attributes ] ); ?><?php echo $this->get_render_attribute_string( 'title_text' ); ?>><?php echo $settings['title_text']; ?></<?php echo $icon_tag; ?>>
			</<?php echo $settings['title_size']; ?>>
			<p <?php echo $this->get_render_attribute_string( 'description_text' ); ?>><?php echo $settings['description_text']; ?></p>
		</div>
	</div>
</a>

```

**Comment by lucidpsimc** [comment]
@msbt thanks, tried your code and when it renders it immediately closes it with a '</a>'. Obviously it's not your code doing that, something else in there.

`<div class="elementor-icon-box-wrapper"><a class="link" href="/community/lookup-and-pay-bills-online/"></a>`

**Comment by msbt** [comment]
that's why I put the link outside of the wrapper, did you try that?

**Comment by lucidpsimc** [comment]
@msbt yes, I am on the newest release of Elementor though as well as Wordpress.

**Comment by msbt** [comment]
@lucidpsimc and your `<a>` starts outside of the elementor-icon-box-wrapper div?

**Comment by lucidpsimc** [comment]
@msbt here is what gets rendered.

`<div class="elementor-widget-container">
					
<a class="link" href="/community/lookup-and-pay-bills-online/">
	</a><div class="elementor-icon-box-wrapper"><a class="link" href="/community/lookup-and-pay-bills-online/">
			</a><div class="elementor-icon-box-icon"><a class="link" href="/community/lookup-and-pay-bills-online/">
			</a><a class="elementor-icon elementor-animation-" href="/community/lookup-and-pay-bills-online/">
			<i class="fa fa-money" aria-hidden="true"></i>
			</a>
		</div>
				<div class="elementor-icon-box-content">
			<h3 class="elementor-icon-box-title">
				<a href="/community/lookup-and-pay-bills-online/">Pay Online</a>
			</h3>
			<p class="elementor-icon-box-description">View a variety of bills that can be paid online.</p>
		</div>
	</div>


	
				</div>`

**Comment by msbt** [comment]
ah my bad, I forgot to add the css! try adding this to your website
```
.link {
    width: 100%;
    height: 100%;
    position: absolute;
    z-index: 9999;
}
```

**Comment by berkmh** [comment]
guys just use this plugin: [https://wordpress.org/plugins/make-column-clickable-elementor/](https://wordpress.org/plugins/make-column-clickable-elementor/) works perfectly.

**Comment by lucidpsimc** [comment]
@msbt I didn't even think to check the CSS!

@berkmh Plugin works perfectly! Thanks for the share!

**Comment by lucidpsimc** [comment]
@msbt I didn't even think to check the CSS!

@berkmh Plugin works perfectly! Thanks for the share!

**Comment by darrillouie** [comment]
I came across this very same problem and found no solution. so here is how I solved it, using elementor hooks - so I think this is update-safe. sourced from render method of icon-box.php

`function tdau_link_whole_icon_box ( $content, $widget ) {
	
    if ( 'icon-box' === $widget->get_name() ) {
        $settings = $widget->get_settings_for_display();

		$wrapper_tag = 'div';

		$has_icon = ! empty( $settings['icon'] );

		if ( ! empty( $settings['link']['url'] ) ) {
			$wrapper_tag = 'a';
		}

		$icon_attributes = $widget->get_render_attribute_string( 'icon' );
		$link_attributes = $widget->get_render_attribute_string( 'link' );

		if ( ! $has_icon && ! empty( $settings['selected_icon']['value'] ) ) {
			$has_icon = true;
		}
		$migrated = isset( $settings['__fa4_migrated']['selected_icon'] );
        $is_new = ! isset( $settings['icon'] ) && Elementor\Icons_Manager::is_migration_allowed();
		
		ob_start();

		?>
		<<?php echo implode( ' ', [ $wrapper_tag, $link_attributes ] ); ?> class="elementor-icon-box-wrapper elementor-icon-box-wrapper-tdau">
			<?php if ( $has_icon ) : ?>
			<div class="elementor-icon-box-icon">
				<<?php echo implode( ' ', [ 'span', $icon_attributes ] ); ?>>
				<?php
				if ( $is_new || $migrated ) {
					Elementor\Icons_Manager::render_icon( $settings['selected_icon'], [ 'aria-hidden' => 'true' ] );
				} elseif ( ! empty( $settings['icon'] ) ) {
					?><i <?php echo $widget->get_render_attribute_string( 'i' ); ?>></i><?php
				}
				?>
				</span>
			</div>
			<?php endif; ?>
			<div class="elementor-icon-box-content">
				<<?php echo $settings['title_size']; ?> class="elementor-icon-box-title">
					<?php echo $settings['title_text']; ?>
				</<?php echo $settings['title_size']; ?>>
				<?php if ( ! Elementor\Utils::is_empty( $settings['description_text'] ) ) : ?>
				<p <?php echo $widget->get_render_attribute_string( 'description_text' ); ?>><?php echo $settings['description_text']; ?></p>
				<?php endif; ?>
			</div>
		</<?php echo $wrapper_tag; ?>>
		<?php

		$content = ob_get_clean();

    }

    return $content;
}
add_filter( 'elementor/widget/render_content', 'tdau_link_whole_icon_box', 10, 2 );`

just put it in theme's functions.php

**Comment by Systemedic** [comment]
@darrillouie Thank you for the code. I added this in the theme functions.php but it doesn't seem to work. Is there something I should change?

**Comment by dooleyb1** [comment]
> guys just use this plugin: https://wordpress.org/plugins/make-column-clickable-elementor/ works perfectly.

Thank you man, did the job for me 🙏

**Comment by daniloso92** [comment]
> guys just use this plugin: https://wordpress.org/plugins/make-column-clickable-elementor/ works perfectly.

This is ok for column but not for the icon box, there is other solutions?

**Comment by ShadowXVII** [comment]
I've re-opened this request in #11426 for consideration.

**Comment by MattOndo** [comment]
> @darrillouie Thank you for the code. I added this in the theme functions.php but it doesn't seem to work. Is there something I should change?

+1 here @darrillouie

**Comment by JoelEadeDesign** [comment]
For a quick fix, albeit not quite what this issue is for, you can link the description to the URL as well using the below:

`jQuery(document).ready(function($) {
  $('.elementor-icon-box-description').html(function(i,html) {
    return $(this).prev('.elementor-icon-box-title').find('a').clone().html( html );
  });
});`

**Comment by GringoWhoowhere** [comment]
Would like this to be a possibility as default in elementor

**Comment by artifex-media** [comment]
+1, no 'consideration' needed.. we just want it! It makes NO sense to only have the icon clickable...

**Comment by gTaylorRokk** [comment]
+1 for this again! I've just run into the issue and was amazed neither the icon box or image box widget have this option when the call to action does. Elementor team it is a really common scenario a user would expect to click on the whole box area, particularly if presented as a card style design which I often do. Please add this as an option similar to call to action. Thanks

**Comment by djoo** [comment]
+1

**Comment by JoeMagrino** [comment]
Definitely need the ability to make the whole Icon Box clickable. When showing a site for review recently, it was the first thing the group noticed and requested for me to change. I thought it would be as simple as an option in the Editor, but no.

**Comment by barak97** [comment]
Meanwhile, it could be achieved by using this code:


`.elementor-widget-icon-box a:after {
content: "";
display: block !IMPORTANT;
position: absolute;
top: 0;
bottom: 0;
left: 0;
right: 0;
z-index: 1;
}
`

It adds a "layer" of the link above the whole icon box element, so it becomes clickable.

**Comment by bhambrabland** [comment]
> 
> 
> Meanwhile, it could be achieved by using this code:
> 
> `.elementor-widget-icon-box a:after { content: ""; display: block !IMPORTANT; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1; } `
> 
> It adds a "layer" of the link above the whole icon box element, so it becomes clickable.

This did exactly what I needed it to do, thank you Barak97.

**Comment by darrillouie** [comment]
> > @darrillouie Thank you for the code. I added this in the theme functions.php but it doesn't seem to work. Is there something I should change?
> 
> +1 here @darrillouie


sorry, the whole code needs to be inside a conditional
`if ( did_action('elementor/loaded') ) { /* the code */ }`

**Comment by immdraselkhan** [comment]
> I came across this very same problem and found no solution. so here is how I solved it, using elementor hooks - so I think this is update-safe. sourced from render method of icon-box.php.
> 
> ```
> function tdau_link_whole_icon_box ( $content, $widget ) {
> 	
>     if ( 'icon-box' === $widget->get_name() ) {
>         $settings = $widget->get_settings_for_display();
> 
> 		$wrapper_tag = 'div';
> 
> 		$has_icon = ! empty( $settings['icon'] );
> 
> 		if ( ! empty( $settings['link']['url'] ) ) {
> 			$wrapper_tag = 'a';
> 		}
> 
> 		$icon_attributes = $widget->get_render_attribute_string( 'icon' );
> 		$link_attributes = $widget->get_render_attribute_string( 'link' );
> 
> 		if ( ! $has_icon && ! empty( $settings['selected_icon']['value'] ) ) {
> 			$has_icon = true;
> 		}
> 		$migrated = isset( $settings['__fa4_migrated']['selected_icon'] );
>         $is_new = ! isset( $settings['icon'] ) && Elementor\Icons_Manager::is_migration_allowed();
> 		
> 		ob_start();
> 
> 		?>
> 		<<?php echo implode( ' ', [ $wrapper_tag, $link_attributes ] ); ?> class="elementor-icon-box-wrapper elementor-icon-box-wrapper-tdau">
> 			<?php if ( $has_icon ) : ?>
> 			<div class="elementor-icon-box-icon">
> 				<<?php echo implode( ' ', [ 'span', $icon_attributes ] ); ?>>
> 				<?php
> 				if ( $is_new || $migrated ) {
> 					Elementor\Icons_Manager::render_icon( $settings['selected_icon'], [ 'aria-hidden' => 'true' ] );
> 				} elseif ( ! empty( $settings['icon'] ) ) {
> 					?><i <?php echo $widget->get_render_attribute_string( 'i' ); ?>></i><?php
> 				}
> 				?>
> 				</span>
> 			</div>
> 			<?php endif; ?>
> 			<div class="elementor-icon-box-content">
> 				<<?php echo $settings['title_size']; ?> class="elementor-icon-box-title">
> 					<?php echo $settings['title_text']; ?>
> 				</<?php echo $settings['title_size']; ?>>
> 				<?php if ( ! Elementor\Utils::is_empty( $settings['description_text'] ) ) : ?>
> 				<p <?php echo $widget->get_render_attribute_string( 'description_text' ); ?>><?php echo $settings['description_text']; ?></p>
> 				<?php endif; ?>
> 			</div>
> 		</<?php echo $wrapper_tag; ?>>
> 		<?php
> 
> 		$content = ob_get_clean();
> 
>     }
> 
>     return $content;
> }
> add_filter( 'elementor/widget/render_content', 'tdau_link_whole_icon_box', 10, 2 );
> ```
> 
> just put it in theme's functions.php

This code is working fine. Thanks!

**Comment by mikanero** [comment]
+1

**Comment by frankb75** [comment]
@barak97 thank you! your solution worked beautifully!

**Comment by AdrianPaulV** [comment]
+1
It makes no sense NOT to have this option. Thanks!

**Comment by Keven6077** [comment]
+1

**Comment by Xavvi** [comment]
+1

**Comment by cidapple** [comment]
@bainternet tread started in 2018 and we are now in 2022... Dosent seem to been fixed. can you advise? i really need it to work

**Comment by puregraphx** [comment]
+1 from me.
@bainternet how many upvotes does it take to implement this?

**Comment by GiuMagnani** [comment]
+1

**Comment by benwhit** [comment]
+1

**Comment by puregraphx** [comment]
Found a workaround, use the CTA box instead of the Icon box. You can even use your own SVG icons.

**Comment by speedxcz** [comment]
+1

**Comment by gerardreches** [comment]
+1

**Comment by jivaneo** [comment]
+1 Still waiting...Is there any elementor team member able to tell us more about this?

**Comment by afruit** [comment]
+1 on this.

I Feel like this should be the default behavior of this widget.

I can understand if there is no background on the list item that one would assume that the actual text becomes the link target, but having the whole thing clickable wouldn't negate that. At the same time, once you put a background on the list time, it looks like you should be able to click it like a button, which you can not. Hence the desire for this feature.

**Comment by nicholaszein** [comment]
Hello everybody!

I wanted to give you an update. If you have Elementor Pro, you can use the **Call to Action** widget as an Icon Box, and it already has an option to make the whole widget clickable.

This feature is currently not on our plans for the time being.

Best regards

**Comment by actualvirtual** [comment]
The CTA widget does not allow for icon positioning and styling like an Icon box does. @immdraselkhan's code worked great for me, with a little CSS to manage text underlines on hover making it all work nicely. 

Would still be a good addition to the Icon Box functionality.

**Comment by jivaneo** [comment]
> The CTA widget does not allow for icon positioning and styling like an Icon box does. @immdraselkhan's code worked great for me, with a little CSS to manage text underlines on hover making it all work nicely.
> 
> Would still be a good addition to the Icon Box functionality.

Absolutely! Guys stop saying "use CTA instead" cause those 2 widgets don't have the same options.
Otherwise why Elementor propose 2 widgets?
Whole icon box linking is still missing...

**Comment by xolesteroll** [comment]
> Meanwhile, it could be achieved by using this code:
> 
> `.elementor-widget-icon-box a:after { content: ""; display: block !IMPORTANT; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1; } `
> 
> It adds a "layer" of the link above the whole icon box element, so it becomes clickable.

GENIUS! Thank you!! i had to write some cryptic JS before

**Comment by Meppyman** [comment]
If you are reading this thread wondering which of the above solutions to try...  This one is the way to go: It's just CSS and works without fuss and without risk of complicated code breaking. I just added it to the page I needed it on in the page settings -> Advanced -> Custom CSS and it worked instantly.

Simple solutions are always best! Thanks @barak97 !!

> Meanwhile, it could be achieved by using this code:
> 
> `.elementor-widget-icon-box a:after { content: ""; display: block !IMPORTANT; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1; } `
> 
> It adds a "layer" of the link above the whole icon box element, so it becomes clickable.

**Comment by therealsimwoe** [comment]
Thanks to @barak97! Your solution worked perfectly. Simply adding this to your Custom CSS for the whole page and the problem is solved. It is really great so see such "Community Solutions" come to life when the Elementor team does not seem to be interested...

> Meanwhile, it could be achieved by using this code:
> 
> `.elementor-widget-icon-box a:after { content: ""; display: block !IMPORTANT; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1; } `
> 
> It adds a "layer" of the link above the whole icon box element, so it becomes clickable.

**Comment by EdwardBlack** [comment]
> .elementor-widget-icon-box a:after { content: ""; display: block !IMPORTANT; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1; }

The CSS works really well, but Elementor should make it a feature!

+1

**Comment by ThatGirlSlays** [comment]
Also expressing my interest in the feature. For now, I implemented the "Make Column Clickable Elementor" plugin but I'd like to cut down on the number of plugins I use.

**Comment by jivaneo** [comment]
I'm leaving this thread.
Switching to flex container (box or grid), which is much powerful option to build content and future-proof.
I can now create custom icon-box myself easily and containers are whole clickable...
Cheers!

**Comment by Eetheart** [comment]
> I came across this very same problem and found no solution. so here is how I solved it, using elementor hooks - so I think this is update-safe. sourced from render method of icon-box.php.
> 
> ```
> function tdau_link_whole_icon_box ( $content, $widget ) {
> 	
>     if ( 'icon-box' === $widget->get_name() ) {
>         $settings = $widget->get_settings_for_display();
> 
> 		$wrapper_tag = 'div';
> 
> 		$has_icon = ! empty( $settings['icon'] );
> 
> 		if ( ! empty( $settings['link']['url'] ) ) {
> 			$wrapper_tag = 'a';
> 		}
> 
> 		$icon_attributes = $widget->get_render_attribute_string( 'icon' );
> 		$link_attributes = $widget->get_render_attribute_string( 'link' );
> 
> 		if ( ! $has_icon && ! empty( $settings['selected_icon']['value'] ) ) {
> 			$has_icon = true;
> 		}
> 		$migrated = isset( $settings['__fa4_migrated']['selected_icon'] );
>         $is_new = ! isset( $settings['icon'] ) && Elementor\Icons_Manager::is_migration_allowed();
> 		
> 		ob_start();
> 
> 		?>
> 		<<?php echo implode( ' ', [ $wrapper_tag, $link_attributes ] ); ?> class="elementor-icon-box-wrapper elementor-icon-box-wrapper-tdau">
> 			<?php if ( $has_icon ) : ?>
> 			<div class="elementor-icon-box-icon">
> 				<<?php echo implode( ' ', [ 'span', $icon_attributes ] ); ?>>
> 				<?php
> 				if ( $is_new || $migrated ) {
> 					Elementor\Icons_Manager::render_icon( $settings['selected_icon'], [ 'aria-hidden' => 'true' ] );
> 				} elseif ( ! empty( $settings['icon'] ) ) {
> 					?><i <?php echo $widget->get_render_attribute_string( 'i' ); ?>></i><?php
> 				}
> 				?>
> 				</span>
> 			</div>
> 			<?php endif; ?>
> 			<div class="elementor-icon-box-content">
> 				<<?php echo $settings['title_size']; ?> class="elementor-icon-box-title">
> 					<?php echo $settings['title_text']; ?>
> 				</<?php echo $settings['title_size']; ?>>
> 				<?php if ( ! Elementor\Utils::is_empty( $settings['description_text'] ) ) : ?>
> 				<p <?php echo $widget->get_render_attribute_string( 'description_text' ); ?>><?php echo $settings['description_text']; ?></p>
> 				<?php endif; ?>
> 			</div>
> 		</<?php echo $wrapper_tag; ?>>
> 		<?php
> 
> 		$content = ob_get_clean();
> 
>     }
> 
>     return $content;
> }
> add_filter( 'elementor/widget/render_content', 'tdau_link_whole_icon_box', 10, 2 );
> ```
> 
> just put it in theme's functions.php

Works really well, even in 2023! Thank you! Why this isn't a core feature of Elementor is beyond me.

**Comment by LolaMeppy** [comment]
> > I came across this very same problem and found no solution. so here is how I solved it, using elementor hooks - so I think this is update-safe. sourced from render method of icon-box.php.
> > ```
> > function tdau_link_whole_icon_box ( $content, $widget ) {
> > just put it in theme's functions.php
> 
> Works really well, even in 2023! Thank you! Why this isn't a core feature of Elementor is beyond me.

Thanks, but if you looked back a couple of posts, you will see that this is already solved using just CSS. No need for code at all.  Unless there is something I'm missing here?

**Comment by brent-e** [comment]
The CSS provided above is a great workaround. I did notice that it disabled the hover colour change on the icon; this resolved it, in my case anyway:

.elementor-widget-icon-box a:after { 
content: ""; 
display: block !IMPORTANT; 
position: absolute; 
inset: 0; 
z-index: 1; 
} 

.elementor-icon-box-icon {
z-index: 2; 
}

**Comment by Meppyman** [comment]
@brent-e thanks for the changes. Going to test those out! :)
