### ISSUE TITLE
[Feature Request] Include default/optimised CSS

### ISSUE THREAD

**Issue by TerenceMilbourn** [pojome/elementor#4355]
Can you please provide some Default CSS code to go with the Elementor Hello Theme? 

I use "Generate Press Pro" currently, and I've found that their basic CSS works quite well, but imagine it can be further optimised when their theme or plugin is not in the frame. 

I realise your Hello theme is intended for developers, but it would be very helpful if you could include the basic Elementor CSS, because using almost any other theme, no matter how good, when only the Elementor plugin and Hello Theme is involved, results in additional cycles and unnecesary database calls, which of course makes it slower than it needs to be.

Many thanks for a truly great plugin and perhaps the most innovative change to WordPress theme development I have ever seen.

**Comment by bainternet** [comment]
"Hello Theme" is meant more of a starter/template theme, that's why it's "missing" styling,

anyway 
I merged this issue with  #1324, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
