### ISSUE TITLE
[Feature Request] Select next/previous section

### ISSUE THREAD

**Issue by Jackpedleham** [pojome/elementor#4356]
It would be great to have the function to select the next or previous section on a page thus removing the issue with selecting overlapping sections. They could maybe also be assigned names per section and could be selectable from a dropdown list

**Comment by bainternet** [comment]
I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
