### ISSUE TITLE
Elementor+ACF+WPML Help Wanted

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4361]
Hello!
I'm making multilingual website using Elementor+ACF+WPML. I make a frontpage template with Elementor, where I'm use ACF with dynamic field Elementor feature.
I don't want to use WPML translation feature for Elementor because it breaks the template logic. WPML creates different pages with different Elementor layouts for each language. When I need to correct design I should do this on each page.
That's why I use ACF. I did page markup with Elementor and its' dynamic feature, and then fill the fields with the native WordPress editing mode, for each translation.

The question is how to translate the contact form in this case. There is no dynamic opportunity in Shortcode widget. I tried to use Heading widget, but the styles was brake.
Any ideas?

**Comment by parfilov** [comment]
Works using dynamic Post Content widget and shortcode but this issue https://github.com/pojome/elementor/issues/4363 disturbs.

**Comment by bainternet** [comment]
The fix here should come from the translation plugin, 
the idea here is that each language should have its own template ( all connected via the translation plugin) and the translation plugin should catch the correct language template.

We have no control over what happen now.
