### ISSUE TITLE
Content duplication when using single template AGAIN

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4363]
Hi. Here is mu closed issue https://github.com/pojome/elementor/issues/4156
But the problem is still present.
![duplicate_content](https://user-images.githubusercontent.com/12493645/39675600-322f0584-517f-11e8-8d85-ad6be22a1c90.PNG)
Elementor 2.0.9
Elementor Pro 2.0.4

This case I made a frontpage template and used Post Content widget.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
