### ISSUE TITLE
BUG - When Scrolling Effect>Sticky=YES, page auto scrolls up.

### ISSUE THREAD

**Issue by mylimoproject** [pojome/elementor#4364]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
A) Page will auto scroll up whenever Scrolling Effect>Sticky=YES
B) If clicking on anchor link. It will slowly scroll back up.

## Steps to reproduce

just login to dclimolinks.com (under development) and either scroll down of click on "Fleet" menu item.

Before Elementor came up with header, footer and Sticky option, I was using used same collection of plugins on other sites but using "MyStickyMenu" plugin and "Header Footer Elementor".
I guess I will have to keep doing that until menu & sticky issues are resolved.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Tested with Astra and Twenty Seventeen
<details>
<summary>[system-info-dclimolinks.com-06-05-2018.txt](https://github.com/pojome/elementor/files/1977854/system-info-dclimolinks.com-06-05-2018.txt)</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by pingram3541** [comment]
Same, I noticed when I set some custom css to reduce my logo size by 50% when .elementor-sticky--active is set, it results in an unnamed DIV being placed just after the section which seems to fire on every scrollTop iteration causing the page to jump up/down and almost impossible to scroll back up.

**Comment by pingram3541** [comment]
Preferably we need a way to make an element sticky but only when scrolled, not when its in it's normal flow.  I see have a non-sticky state and a sticky state identified at least by a class so I can apply custom css to both conditions.

The way it is currently, the condition is sticky all the time, even on page load and the dynamically added DIV is used to push the immediately following content in flow down as many px in height the sticky element is, so as to not let the content hide under the sticky element.

This approach is what is causing the fuss.  The dynamically added DIV needs to be aware of "size" changes while also providing some "state" control for conditions like:

- default page load (not sticky)
- while scrolling/scrolled down (sticky)
- while scrolling/scrolled up, but not at top (sticky-reverse)

This would allow us more granular control with custom css so we can hide the header when scrolled down and reveal a shrunk down size while scrolling back up and then finally back to normal when scrolled to the top or at least where it is in normal document flow.

**Comment by bainternet** [comment]
@mylimoproject 
we can't replicate.

@pingram3541 
as for reducing sizes and other customizations, give it time.

**Comment by pingram3541** [comment]
Oh and I forgot to mention that I also have to tuck the "main content" under the header enough to hide the "spacer" div that gets added while scrolling.

Once you know the quirks you can get around it.

**Comment by Manusan42** [comment]
I fight with this bug too. As soon the sticky header is active, I get this scroll up effect sometimes, which seems to be triggered by multiple things.

One thing which I could consistently identify is that it happens as soon I have a section with a bullet points list in it which has no text before, so the section starts directly with bullet list.
If I write text before the bullet list, then all is fine.

Another time I detected this auto scroll if I apply custom styles to images. When I set a width but no height for image in section, then some height detection algorithm seems to fail and this annoying scrolling happens.

So this auto-scroll seems to happen always when there is some not default behavior in vertical space.

**Comment by LatitudeNick** [comment]
@Manusan42 Interestingly enough, my scenario/use-case of the bug existing causes a downward scroll at about the halfway mark on my page. I still have yet to have any luck trying to resolve the issue and have been in contact with support as well. It's an especially frustrating situation!

**Comment by Manusan42** [comment]
@LatitudeNick  I have a page where I can't get rid of this problem too. If you get any information from support I would really appreciate it if you can share it here, thanks.
Seems some JS related bug in relation to the sticky-kit they use. Tried a bit debugging, but with minified files this is not that fun ^^

**Comment by mylimoproject** [comment]
The easy solution.... disable the Sticky function and install MyStickymenu plugin until Elementor staff is convenienced this is a bug needing priority attention.

**Comment by Manusan42** [comment]
@mylimoproject I can't describe how much I like you right now.
This plugin is my life-saver, works with no problems.
Thanks

**Comment by pingram3541** [comment]
Glad the plugin works for you.  For anyone else...

I had to use a little bit of finesse and got it working within Elementor+Pro.

1) Had to create a new section ABOVE my header section
  -set it to No Gap (it will be empty and unseen)

2) Set/create header section
  -set as sticky
  -set w/ -1px top margin

3) Provide whatever custom css you'd like for the sticky effect

**Comment by vincentjflorio** [comment]
@Manusan42 THANK you:

> So this auto-scroll seems to happen always when there is some not default behavior in vertical space.

That was it for us on a header template we were using. I tried watching it in DevTools thinking it might be an animating or scripted positional property change, just to see what was going wonky, and because it kept updating whatever value was being messed up, it wouldn't even let me open the elements to watch the change. 

We didn't have a minimum height set, but when we added one -- setting it to the height it was "naturally" at the top of the page before the class gets added, in our case just under 100px, the scrolling went away.

In hindsight it makes a lot of sense, since so many of these scripts take a look at how big the container is that is being made sticky and use that to determine when to kick in (meaning, how far has the person scrolled down and is it past where they would otherwise no longer see the section). Without a value I can only imagine what computations it's trying to arrive at.

For us it only happened in Chrome as well, but it even was happening in the preview mode; if it's at all possible for the plugin to assume a default in those cases, or in some other way require a height, that might go a long way to eliminating the issue.

**Comment by misegamaeya** [comment]
I am in trouble with the same problem. In my environment, this bug seems to appear when using Chrome. It works normally in Firefox. I pray for early response.

**Comment by mylimoproject** [comment]
@bainternet 
This auto-up-scroll bug has become very, very annoying and at this stage of Elementor, we shouldn't be begging for an ASAP fix of an obvious and documented bug. Elementor PRO subscribers shouldn't have to be resourcing to third party plugin or piggy backing scrips/hacks to solve a main header "feature" bug of builder's theme option. I am requesting this ticket is reopen and a solution found asap.

**Comment by misegamaeya** [comment]
It worked normally by reducing the elements of the header and recreating it. However, it is not possible to investigate with cause. Because I am not a person familiar with the system (^ _ ^;)

**Comment by booyen** [comment]
i clear the cache and things works like it should.. no more auto scrolling when using sticky header options. Dont know if related to js cache conflict bug or just my web

**Comment by vincentjflorio** [comment]
Just as a follow-up to this comment: https://github.com/pojome/elementor/issues/4364#issuecomment-397086185

we had to make a change to the header, and wound up setting a minimum height, but even with it set it was lower than the rendered size of the header. We had it set for 68px just to have something on there, and because that was all the taller it looked like it needed to be perceptually, but it was 81.67something px on the front end, and after setting it to a minimum of 82 it worked.

Someone mentioned before there's a second, internal, generated container and that is what receives the height. That's how I spotted the issue; the generated container still had the 82 as an inline style but our actually-set one was lower. When they matched, problem disappeared again.

This was in Chrome and Safari.

**Comment by pingram3541** [comment]
@vincentjflorio Yes I mentioned it in my previous comment above.  Create a new empty section above your sticky header, set it to full width and no gap (it will be invisible).  Then on your actual sticky header section, give it a -1px top margin.

This has been the fix for me on countless websites.  Cheers!

**Comment by vincentjflorio** [comment]
@pingram3541 The one I was referring to is created by Elementor itself, not a manually-created duplicate.

For context: https://ibb.co/bKuY78 

I don't have to make anything new in my version of the issue, just a tweak to what's already there, and blissfully I don't have to mess with paddings and margins. (Too easy to forget about for the fog-headed people among us =)

**Comment by pingram3541** [comment]
Yes that is exactly what I am talking about.  If you see my earliest comments on this issue you'll see I mention the auto-generated div that doesn't recalculate height on sticky and causes the undesired effect if something, anything, changes the height of the header that is sticky.  I my case it's typically the logo, i.e. 50% height or similar.

The solution of adding an empty div above the header section is what has always worked for me.  Please, be skeptical, I was too, but just try it out at least.

**Comment by vincentjflorio** [comment]
Ah, apologies @pingram3541, when you said previous I thought you meant the comment of yours immediately preceding.

I have neither the inclination nor need for skepticism nor was my message intended to undermine what you were saying. Just was trying to add to the pot what I believed was an alternative experience corroborating your earlier sentiment. 

In other words, like you, encouraging people to explore all avenues of resolution by mentioning that it could both come about and be solved in different ways. I am probably just getting a away with a simpler fix that only happens to work, and actually relies on what you're talking about.

**Comment by CvS-W** [comment]
Googling for the problem scrolling pages on my website using Elementor I found that more people have the same problem.
The issue on my sites was a header with a negative bottom margin. Setting this to 0 fixed my problems.
Maybe helpful for others?

**Comment by webinsightin** [comment]
The issue was fined by Elementor but it has come again with new update of Google Chrome. @pixelcollective

**Comment by kellymears** [comment]
I get a report once every couple weeks from one of the admins of the sites I manage asking why their screen is scrolling. The workaround I posted in https://github.com/pojome/elementor/issues/4542 seems to work for the most part -- but good luck explaining any of that to a person who doesn't even know what CSS is. 😞  @webinsightin

**Comment by jacopobonomi** [comment]
Any news about that issue?

**Comment by digoartmusic** [comment]
I was having the same error, after inspecting it a lot, I found that this error occurs when you have an absolute position object with Scrolling Effects enabled on the mobile version

**Comment by reachdigitalaus** [comment]
I had a similar issue with iPad. We had a sticky nav and had a negative margin BG below it to get a transparent nav effect.

Issue was nav on iPad would appear and disappear/flash  on off scroll which looked like a bug.

Doing th above solution of adding an empry div above the nav with a negative margin worked. It's seems like a hack to make this work. Would be great if Elementor fixes this.

**Comment by pingram3541** [comment]
While we wait to see if there will be any response about re-opening this thread, if it helps, here's an alternative I've been using for those that like the sticky effect only when scrolling back up - https://wplovr.com/sticky-scrollup-menu/

**Comment by digoartmusic** [comment]
> I had a similar issue with iPad. We had a sticky nav and had a negative margin BG below it to get a transparent nav effect.
> 
> Issue was nav on iPad would appear and disappear/flash on off scroll which looked like a bug.
> 
> Doing th above solution of adding an empry div above the nav with a negative margin worked. It's seems like a hack to make this work. Would be great if Elementor fixes this.

**SOLUTION** I was having the same error, after inspecting it a lot, I found that this error occurs when you have an absolute position object with Scrolling Effects enabled on the mobile version
