### ISSUE TITLE
Form widget shortcode editing

### ISSUE THREAD

**Issue by shimsa** [pojome/elementor#4367]
Hello,

please enable shortcode editing in form widget settings. I need to be able to set my own shortcode.

Thank you.

Tom

![form-shortcode](https://user-images.githubusercontent.com/7617350/39685271-a544b586-51c1-11e8-80da-ab74f336c92b.png)

**Comment by bainternet** [comment]
@shimsa 

that field is simply there for preview and not something that is saved or editable...

what are you trying to do, maybe I can help??

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
