### ISSUE TITLE
blocked content

### ISSUE THREAD

**Issue by isanlab** [pojome/elementor#4369]
A widget that allows put blocked content. 
That such content is only displayed when the user makes an action. For example, put your email address, and have it saved in an external tool. Or enter a password. Or click on share on social networks

**Comment by bainternet** [comment]
I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

This means you could hide content for logged out users, and show a Login Form widget for them to see the content.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
