### ISSUE TITLE
[Feature Request] Inline editing

### ISSUE THREAD

**Issue by vfxdude** [pojome/elementor#437]
![image](https://cloud.githubusercontent.com/assets/20110677/17810637/a4044866-661e-11e6-944c-446f4cb88b09.png)

https://www.tinymce.com/docs/demo/inline/
http://getcontenttools.com/demo

**Comment by paaljoachim** [comment]
Hey

The inline editing feature is on their roadmap. (I have myself also added a request for this feature..:)

**Comment by zu** [comment]
fyi, maybe you already know, but I guess, what Weston Router and xwp accomplished with [Customize Inline Editing](https://wordpress.org/plugins/customize-inline-editing/) is close to what you need.

And it's on Github: [https://github.com/xwp/wp-customize-inline-editing](https://github.com/xwp/wp-customize-inline-editing)

**Comment by black-eye** [comment]
+1 This would be very handy, especially when editing long text.

**Comment by MaximPro** [comment]
Please add this to the next release!
Maybe get help from a pro developer who already did this...
Get going - you are rich now, get more bright minds and hands to work on Elementor ;)
To fulfill all the nice users wishes. ;)
Thanks in Advance and have a great day :1st_place_medal:

**Comment by vfxdude** [comment]
![chrome_2017-10-29_14-33-30](https://user-images.githubusercontent.com/20110677/32144244-40b5ae7c-bcb6-11e7-8f5f-7ea55ebea0bd.png)

This is good news!!

**Comment by arielk** [comment]
We just released a beta release (v1.8) which includes this feature, read more here: https://github.com/pojome/elementor/issues/2666/

Thanks for your feedback!

**Comment by vfxdude** [comment]
Good work!!

One issue is the copy and paste from external source which adds lots of inline styles, but those styles are not applied before clicking out of the inline editor. When I test the [Pen Editor](http://sofish.github.io/pen/), the editor you are using, this doesn't happen. It doesn't paste in any styles, so this is probably a feature you added. It would be best if the styles are applied in the inline editor, without having to click out. And I would request a copy/paste feature like OneNote has, where you choose (after each paste) if you want to include the styles or not (or this can be a setting). Personally I would prefer a copy paste without the styles, just the markup, like the Pen Editor does. The theme should do the styling.
