### ISSUE TITLE
Image Gallery Responsive Mode

### ISSUE THREAD

**Issue by nlewis18** [pojome/elementor#4373]
Please add a column width adjustment feature when image gallery grid  is applied to the mobile device. When I switch to responsive mode, my image gallery with 4 columns gets reduced to one long column of images. 
Customer support has suggested that I insert each image into columns, however this is time consuming,  inconvenient and finicky. 

Nicky.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, you can only overwrite it via Custom CSS.

Thanks for the feedback.
