### ISSUE TITLE
Feature Request: Custom Font Icons

### ISSUE THREAD

**Issue by JumaDM** [pojome/elementor#4377]
As a feature natively available within Beaver Builder and other themes.  The feature to upload custom font icons is paramount with Icon Moon compatibilty or similar.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by JumaDM** [comment]
This feature exists in other builders and is paramount to web designers /end users in offering a unique design/experience.

**Comment by bentalgad** [comment]
Great plugin that will let you add any custom icons font to elementor core options:
https://wordpress.org/plugins/custom-icons-for-elementor/
