### ISSUE TITLE
Can no longer edit Section type templates

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4379]
E - v2.09
Epro - v.204

Using the base Hello theme, and when defining the following template assignments:

- header - entire site
- footer - entire site
- archives - include all archives
- post - single - include all singular - exclude all pages
- page - single - include all pages

One cannot edit a "section" type template.  The result is the dreaded "Sorry, no content was found on your page message" and I can't seem to find a way to map it out properly within the current display conditions.

Update - if I manually edit my database and change the post_meta's `_elementor_template_type` from "section" to "single", "header", "footer" or "page", I can edit it.  When it is set at "section" it fails with the no_content error.

**Comment by pingram3541** [comment]
Updated to:

E - v2.10
Epro - v2.0.5

Same.

**Comment by pingram3541** [comment]
Changed to:

post - single - ~~include all singular~~ include all posts - exclude all pages

And now I can edit "section" type templates again.  Thx

**Comment by ankitmishra88** [comment]
where to do this change?
