### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by ahmednet0001** [pojome/elementor#4381]
I cannot create new sections 
Error :Cannot read property 'data' of undefined
after updating to v 2.0.9

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
