### ISSUE TITLE
How to Map Custom Post Type to Single Template?

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4382]
Searched all over https://developers.elementor.com but cannot seem to find how in my theme I can map a custom post type to a specific single template when that post type does not list within Elementors display conditions...specifically your own elementor_library custom post type since it is currently broken and cannot find the_content.

**Comment by bainternet** [comment]
This was solved in the latest version, please make sure you are up to date and remove any "all singular" conditions you have.

let me know.

**Comment by pingram3541** [comment]
I think you might be confusing this with another topic where I mentioned the "all singular" assignment but I did not mention that here.  I was actually seeking an answer, not necessarily a "fix" per se.

I've noticed that on some themes that register their own custom post type(s), they do not always show up in the list (within display conditions) so I was wondering if there is a hook/action/filter that can be used to designate this from within our themes?

**Comment by bainternet** [comment]
Well, in that case, the only filter we use when calling the `get_post_types` to the conditions list is `'show_in_nav_menus' => true` so if the don't show up on the list, they are probbably set to `'show_in_nav_menus' => false`.

hope this helps

**Comment by pingram3541** [comment]
Yes indeed that is the answer I was seeking thank you so much!
