### ISSUE TITLE
GiveWP Plugin Issues

### ISSUE THREAD

**Issue by Raccroc** [pojome/elementor#4383]
Starting with Give version 2.1.x, Give is causing the TinyMCE  to display Give's shortcode drop down menu while in Edit Page mode in Elementor. This dropdown covers the formatting options and make the text editor almost impossible to use.
The issue is being worked on by the Give team here...
[https://github.com/WordImpress/Give/issues/3171#issuecomment-386567500](url)

The reason I bring this up...it does not appear like this is an isolated case and it has(is) happened(ing) with other software. 
I don't know if Elementor can do anything about it is doable or not (like creating a method to detect and optionally remove shortcode entries from the TinyMCE)

**Comment by bainternet** [comment]
I don't think there is something we can do about it.

thanks.
