### ISSUE TITLE
How to set up Full height image with free Elementor that will cover all screen without scrolling?

### ISSUE THREAD

**Issue by ArtyomBaykov** [pojome/elementor#4385]
Hi,

I want to get something like this:
https://demo.kallyas.net/comingsoon3/

As you see image covers all screen and without scrolling. While when I put section fit to screen it has extra space for scrolling.  How can I get the above mentioned result like in the demo for background image?
I am using free Elementor.

**Comment by obe1968** [comment]
This is a question that would be better off asked in one of the Elementor Facebook groups as this is not a bug issue, but a design question.

**Comment by bainternet** [comment]
This is a question that would be better off asked in one of the [Elementor Facebook groups](https://www.facebook.com/groups/Elementors/) as this is not a bug issue, but a design question.
