### ISSUE TITLE
BUG: Dynamic Post Terms has no taxonomies if taxonomy is used on 2 post types

### ISSUE THREAD

**Issue by xxtesaxx** [pojome/elementor#4386]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I tried to use the Dynamic feature to show Post Terms I noticed that the list of taxonomies was empty. After digging around I noticed that as soon as a taxonomy is used on more than one post type it is not available in the list anymore

## Steps to reproduce

Use a plugin like Toolset or use code to make a taxonomy available on two or more post types

![image](https://user-images.githubusercontent.com/3000808/39744945-20a94f40-52a6-11e8-9837-d3a3a3f3ca6c.png)

![image](https://user-images.githubusercontent.com/3000808/39744875-ec1d87a0-52a5-11e8-863c-8c1ca4c37e0b.png)

## Isolating the problem
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by xxtesaxx** [comment]
How about the suggested solution using `get_object_taxonomies()`? I quickly hacked something together and it works as expected. Simply use this in `post-terms.php` -> `_register_controls()` :

        // $taxonomies = get_taxonomies( $taxonomy_filter_args, 'objects' );
        $options = [];

        if (!$taxonomy_filter_args['object_type'] || empty($taxonomy_filter_args['object_type'])) {
            $taxonomies = get_taxonomies($taxonomy_filter_args, 'objects');
            foreach ($taxonomies as $taxonomy => $object) {
                $options[$taxonomy] = $object->label;
            }
        } else {
            $taxonomies = get_object_taxonomies($taxonomy_filter_args['object_type'], 'objects');
            foreach ($taxonomies as $taxonomy) {
                if ($taxonomy_filter_args['show_in_nav_menus'] && !$taxonomy->show_in_nav_menus) {
                    continue;
                }
                //TODO: apply additional filtering if necessary or remove 'elementor_pro/dynamic_tags/post_terms/taxonomy_args' filter 
                $options[$taxonomy->name] = $taxonomy->label;
            }
        }

        // $options = [];

        // foreach ( $taxonomies as $taxonomy => $object ) {
        //     $options[ $taxonomy ] = $object->label;
        // }

**Comment by bainternet** [comment]
Fixed in E-Pro 2.0.10

thanks
