### ISSUE TITLE
[Feature Request] Change control options according to previous control value 

### ISSUE THREAD

**Issue by ashishsthanp** [pojome/elementor#4388]
I have a SELECT2 control ( _taxonomies_ ) with multiple selections and another SELECT2 _taxonomies_inclusion_ with multiple selections. I want to change _taxonomies_inclusion_ values according to taxonomies selected.

For example, I want to get selected values form _taxonomies_ control in _$taxonomies_selected_ in line number 21 in the following code:
https://pastebin.com/iefpPvSY

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by ashishsthanp** [comment]
Thanks for the response,
I hope for this feature adding soon. I think it would be a good feature for developers. :)

**Comment by sabbiseaan** [comment]
Ya boss it has demand.

**Comment by AmibeWebsites** [comment]
Hi @ashishsthanp and @sabbiseaan, have you been able to do this yet?

I'm also needing to do this as I've described in #6308. In theory the following code should get the **saved** value of the prior control (i.e. it's not dynamic as such - you need AJAX for that) but it generated a fatal error which I'm unable to fix :-(

```
$this->get_data()['settings']['taxonomies']
```

**Comment by dbjpanda** [comment]
+1
