### ISSUE TITLE
[Feature Request / Enhancement] GDPR premission for opt-in forms.

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#4389]
With elementor you can make opt-in forms that are connected you your maillist (like Mailchimp / ActiveCampaign). In Europe we get the GDPR on May 25, by this law you need to ask the visitors premission to put them on a mailing list. Right now that is not possible in Elementor. You can make a checkbox that asks for premission. However the after sent fuctions always will kick in when set up, even if the user does not give premission.

Suggestion: Introduce a new checkbox-element inside forms. Only when checked, the after form action (Mailchimp or ActiveCampaign puts the user on the maillist).

**Comment by bainternet** [comment]
we have an acceptance field:

> 
> The Acceptance field ensures your users accept certain requirements of your choosing. This requirement can be your Terms Of Use, authorization to send them emails, or any other approval, offering you future protection as a site owner. 
> 
> As expected from an acceptance field, you can set it to be a required field. You also have the option to set the acceptance field as checked by default.

**Comment by IDESIGNSTUDIO** [comment]
Checked by default is against the GDPR! Never do checked by default from today on!
