### ISSUE TITLE
Full Width (edge to edge to browser) image 

### ISSUE THREAD

**Issue by jmarshallm** [pojome/elementor#439]
First off, is this a support forum? If so, I cannot for the life of me figure out how to add an image or background image in Elementor, edge to edge of the browser window. It always seems to be contained in a box with a left and right margin. So in other words...it's never a "background" image, it's just an image floating in the middle of the page. I've changed every setting that I can think of inside and outside of Elementor. Could this be my theme? I'm using "A Very Simple Start Pro". I hope someone can help, I've been stuck on this thing for 3 days now getting nowhere. Thanks, John.

**Comment by arielk** [comment]
You can read more about Full-Width here: https://docs.elementor.com/article/40-full-width-template

**Comment by yehudah** [comment]
@jmarshallm 
I just answered in the same issue you opened, please don't double post !
