### ISSUE TITLE
Broken - Image Element setting as Custom Size

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4390]
E v2.10
Epro v2.05

Verified on 2 separate installs, different hosts.

When choosing a custom image size instead of the default sizes, it adjusts on the back end while within the editor as desired but on the front end, the image is just the default image with no size modifications.

**Comment by bainternet** [comment]
We cant replicate,

Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by pingram3541** [comment]
Wow, I can duplicate this on every site, now tested hosted w/ Godaddy, Fastcomet, HostGator, SiteGround and now tested on Web.com, some entirely different themes and plugins (one is your Hello theme unmodified), only common plugins (not disabled) is Elementor and Elementor Pro and their versions.  All sites are wp 4.9.5

E v2.11
Epro v2.05

Did you duplicate it like this?

1) Elementor Image Widget
2) Set it to custom size, say 450px x 450px
3) Click "apply" and watch before your eyes it is resized. (except one of my sites)
4) Now preview it on the front end. It is never resized for me. (all of my sites)

Some of these sites use Cloudflare in which I also cleared all cache and put site in development mode and then reload of the website using chrome's inspector "empty cache and hard reload" while also adding a test text element each time to verify cache is busted and also inspecting css modifications via the inspector's prettyfy filter so I know for a fact it's not browser cache or Cloudflare.

**Comment by pingram3541** [comment]
When editing inside Elementor the custom image url is:
`/wp-content/uploads/elementor/thumbs/...`

When viewing on the front end the image url is:
`/wp-content/uploads/2018/5/...`

**Comment by pingram3541** [comment]
Still reproducible...

E v2.0.12
Epro v2.0.7

**Comment by AlexTangloveKevin** [comment]
it's elementor plugins' problem

**Comment by mountaineer20** [comment]
Hi Elementor team. I am also having this exact issue. I described it here - https://wordpress.org/support/topic/custom-image-size-only-works-in-editor-not-public-page/#post-10362036

 Can you please re-open this bug item so that this error can be fixed?

Thanks, 

![Uploading Screen Shot 2018-06-03 at 8.02.56 PM.png…]()
![Uploading Screen Shot 2018-06-03 at 8.03.43 PM.png…]()

**Comment by pingram3541** [comment]
@bainternet Still a major problem across all of my sites running what is now current E-v.2.0.16 and Epro-v.2.0.11, fyi.

**Comment by drawcard** [comment]
I am also having this issue. 

**Appearance in the backend:**
![image](https://user-images.githubusercontent.com/1435638/41754113-26a75c10-7610-11e8-8de8-c2e02ef231cd.png)

**Appearance in the frontend:**
![image](https://user-images.githubusercontent.com/1435638/41754131-3d389610-7610-11e8-9f37-6d3bd7a412d4.png)

System info: 
https://pastebin.com/j5GZrYDt

**Comment by pingram3541** [comment]
updated #4679

**Comment by drawcard** [comment]
Cheers @pingram3541 - Funnily enough my host uses CloudFlare too. So that could be part of it.

**Comment by pingram3541** [comment]
see #4679 for an update on one possible way to fix this - CORE EDIT!
