### ISSUE TITLE
Elementor Ajax Page Transitions

### ISSUE THREAD

**Issue by TylerOlthuizen** [pojome/elementor#4391]
Hi,

I'm using Barba.js which uses PJAX page transitions, it will just grab the content in the barba container on the requested page and loads it into page. For each of these pages i'm using Elementor to build the content. The issue with this is that it is not loading in wp_head(), so the styles are scripts aren't loading in for the new PJAX content. Is there a better solution to this, can I re-init the scripts and styles somehow?

Thanks!

**Comment by bainternet** [comment]
Are you asking about the editor?

please explain better.

**Comment by TylerOlthuizen** [comment]
Yes
