### ISSUE TITLE
Re: Cannot scroll in Block Categories #4325 - update 2.0.10 did not fix

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#4394]
As the title suggest, the latest update did not solve this issue.

However, I was able to scroll all categories that have enough content to scroll after I selected the category for the second time :) 

Hope this helps resolve this issue.

Cheers!
Lyle

**Comment by bainternet** [comment]
@SniffleValve 

Please make sure you are updated and clear browser cache.

let me know.

**Comment by pixelturm** [comment]
Still the same problem - everything is updated, cache is cleared (FF and Chrome with Win10) - also tested like Snifflevalve mentioned above, but does not work for me, also can`t scroll through the pages-library, kr

**Comment by smaquilon** [comment]
I updated to Elementor 2.010 and Pro 2.0.5, but the issue persist and is not possible to scroll down after a filter of block category is selected.
I have cleared everything: cache, browsing data..., etc and restart the browser but does not works.

**Comment by obe1968** [comment]
Lyle posted on FB a work around for some. When you first choose a category, scrolling does not work. Then choose the same category a second time, and then you can scroll. But like I said, this workaround is not working for all users, and is still a bug.

Shawn

**Comment by SniffleValve** [comment]
@bainternet 
This is happening on a fresh WP install Elementor as the only plugin and the default 20117 theme. 
- install WP 4..9.5
- delete Akismet and Hello Dolly
- install and activate Elementor 2.0.11
- browser (latest Chrome on Win 10) cleared
- attempt to scroll a block category: no scroll
- select the same category the second time: it will scroll :)

**Comment by TerenceMilbourn** [comment]
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.3
	MySQL version: 5.5.5
	PHP Version: 7.0.30-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: https://edd.press
	Home URL: https://edd.press
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 0.1
	Author: Tom Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.1.1
	Parent Theme Author: Tom Usborne
== ==

Add Template > Blocks ... scrolls OK.
> Any Category ... will not scroll.

**Comment by iCoachLive** [comment]
Sniffle Valve (Lyle) Solution worked for me. 
Select 2 x. Then able to scroll all the way through.

**Comment by bainternet** [comment]
@SniffleValve 

Please make sure you are on 2.0.11 and 2.0.5

let me know.

**Comment by JoelEadeDesign** [comment]
I have v2.0.11 installed. I can scroll the list of **Blocks** as long as I don't choose one of the drop-down _Category_ options.

Here's a video of what I'm experiencing:

<iframe width="630" height="394" src="https://www.useloom.com/embed/3797e556bf2c47d08c9e699aac0caa13" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

**Comment by TerenceMilbourn** [comment]
Yes, same here. As long as no category is selected I can scroll. However, if a category is selected, neither the slider or mouse wheel works.

**Comment by bainternet** [comment]
Thanks guys, please make sure to update to 2.0.12.

**Comment by obe1968** [comment]
Tested earlier today on Firefox quantum, and still does not work in FF, but it does on Chrome.

**Comment by JoelEadeDesign** [comment]
2.0.12 works for me in Chrome v66 and FF v60.0 :)

**Comment by pixelturm** [comment]
Same, 2.0.12 works now in Chrome 66 and FF 60 (worked in 59 too) ;)
