### ISSUE TITLE
Conflict between Elementor/Ajax/Masonry/Search filter 

### ISSUE THREAD

**Issue by Anaon** [pojome/elementor#4395]
Hi, I installed this plugin : https://www.designsandcode.com/wordpress-plugins/search-filter-pro/

I worked with their support to configure it and make it work properly.

It's working well on this page : https://www.bonsbaisersdetaghazout.com/test/
until you change the category. The images doesn't charge and the template comes from AE Template.

We worked on it this morning and they gave me this topic : https://www.designsandcode.com/forums/topic/reload-masonry-grid-after-ajax-call/#post-165867

They told me to contact the elementor support to check with you the right classes to add in this code.

**Comment by bainternet** [comment]
Please follow the guidelines for opening a new issue.

**Comment by Anaon** [comment]
What is wrong?

**Comment by Anaon** [comment]
Oh, I think I understand, I should have edit the last line. I talked with the support, they told me to come here for this request
