### ISSUE TITLE
custom skin

### ISSUE THREAD

**Issue by networking-web** [pojome/elementor#4397]
I need to view recent posts. You will also see a picture that belongs to the same category.
To do this I installed the plugin:
"Categories Images"
And insert the following code in the skin-base.php file:
```HTML
<ul style = "display: block; list-style-type: none; padding-right: 0px;">
<? php foreach (get_categories () as $ cat):?>
<li>
<img src = "<? php echo z_taxonomy_image_url ($ cat-> term_id);?>" />
</ li>
<? php endforeach; ?>
</ ul>
```
In: protected function render_post_footer ()
When I make the change in this plugin code is excellent.
But I can not make a run in a bat pattern.
Boaz asked me to open a request here so that you could help
Thank you

**Comment by bainternet** [comment]
@networking-web 

It's never a good idea to overwrite plugin files, you will lose your changes in the next update.

What you need to do is create a "custom skin" which extends the skin you are using and simply overwrite the `render_post_footer()` method.

something like: 

```PHP
class My_Custom_Posts_Skin extends \ElementorPro\Modules\Posts\Skins\Skin_Base {
	public function get_id() {
		return 'my-custom-skin-id';
	}
	public function get_title() {
		return __( 'My Custom Skin' );
	}

	public function render_post_footer() {
		?>
			<ul style = "display: block; list-style-type: none; padding-right: 0px;">
				<?php foreach ( get_categories() as $cat ) : ?>
					<li>
						<img src="<?php echo z_taxonomy_image_url( $cat->term_id ); ?>" />
					</li>
				<?php endforeach; ?>
			</ul>
		</article>
		<?php
	}
}
```

Register your skin in the posts widget:

```PHP
add_action( 'elementor/widget/posts/skins_init', function( $widget ) {
      require( 'path/to/skin-custom.php' );
      $widget->add_skin( new My_Custom_Posts_Skin( $widget ) );
 } );



The just make sure you pick that skin in the posts widget.

**Comment by networking-web** [comment]
Thank you!!!!!  :)

You are a champion!

**Comment by bainternet** [comment]
No, You are :)

**Comment by Mulli** [comment]
Thanks. I shall try it, although I am feeling uncomfortable to hack that way.
I have generated my own php/js/css shortcode....
Dont like it either, but it works ...

**Comment by sododesign** [comment]
@bainternet How can we replicate this to create a customized Skin for the archive? 

Currently the snippet is valid for the Post Widget, but not for the widget that shows the archive loop

**Comment by onepoint0** [comment]
Hi @sododesign try hooking it to archive-posts:

add_action( 'elementor/widget/archive-posts/skins_init', 'add_skin' ); 

function add_skin( $button ) {
      require( 'path/to/skin-custom.php' );
      $widget->add_skin( new My_Custom_Posts_Skin( $widget ) );
}

**Comment by rafael-figueiredogluz** [comment]
Hi,

When I tried to extend through my plugin I have this error:

**Comment by symplTech** [comment]
When using @bainternet code it works just perfect except the Load More button functionality (or even the infinite loading option)... for some reason the Load More button is visible but no js events are fired after I click it.. When I switch back to the classic skin it works.
Any suggestions why this happens?

**Comment by brittaweller** [comment]
> When using @bainternet code it works just perfect except the Load More button functionality (or even the infinite loading option)... for some reason the Load More button is visible but no js events are fired after I click it.. When I switch back to the classic skin it works. Any suggestions why this happens?

I have the same Problem. 

Probably connected to this issue: [#16731](https://github.com/elementor/elementor/issues/16731)
