### ISSUE TITLE
Conflict between Elementor/Ajax/Masonry/Search filter

### ISSUE THREAD

**Issue by Anaon** [pojome/elementor#4398]
First : The support told me to post this request on the GitHub, don't close it without reason

Hi, I installed this plugin : https://www.designsandcode.com/wordpress-plugins/search-filter-pro/

I worked with their support to configure it and make it work properly.

It's working well on this page : https://www.bonsbaisersdetaghazout.com/test/
until you change the category. The images doesn't charge and the template comes from AE Template.

We worked on it this morning and they gave me this topic : https://www.designsandcode.com/forums/topic/reload-masonry-grid-after-ajax-call/#post-165867

They told me to contact the elementor support to check with you the right classes to add in this code.

**Comment by bainternet** [comment]
@Anaon 

The right class would be the class of the container which you want this to run on, not something we can anticipate.

Closing as this is not an issue with elementor.

I would try asking in Elementor [Facebook community](https://www.facebook.com/groups/Elementors/)
