### ISSUE TITLE
Scrolling to anchor tags does not work when header section set to "Sticky"

### ISSUE THREAD

**Issue by 1sourceweb** [pojome/elementor#4399]
This was supposed to be fixed last update but still not working.
To Reproduce:
1.  I have a header block with scrolling set to "sticky". 
2.  The section below contains your slider widget. The button link in that slider widget links to an anchor 
     tag in the section below. 
However, when button is clicked, the screen slides past the top of the section it is linked to. I am using Astra theme with all of its options turned off. 
NOTE: If I take the sticky setting off the header section, scrolling to tag works perfectly.

**Comment by bainternet** [comment]
Thanks for reporting,

Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Isolating the problem.
* System info.
