### ISSUE TITLE
Someone please help! I want to use this plugin but it doesn't support FULL WIDTH images!

### ISSUE THREAD

**Issue by jmarshallm** [pojome/elementor#440]
Can someone please test a theme that works with which allows full width background images? Does anyone know if this plugin has a support team?

**Comment by yehudah** [comment]
You can't do it if your theme doesn't support full width template.

read here: [http://docs.elementor.com/article/40-full-width-template](url)

**Comment by hansnolte** [comment]
Hi yehudah,
your Link doesn't work.

@jmarshallm 
try this one.
https://docs.elementor.com/article/40-full-width-template

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
