### ISSUE TITLE
huge problem that prevents moving from staging to live with https

### ISSUE THREAD

**Issue by emworx** [pojome/elementor#4400]
We have noticed a big issue in elementor , that is whenever we add a slider image to our website using elementor it creates a css file in wp-content\uploads\elementor\css with a hardcoded link i.e. in our case it was http://oursitename.wpengine.com , kindly also check the screenshot https://www.screencast.com/t/P0Yo6Ko4o2aB , so the problem started when we went live to https://www.oursitename.com (SSL) , the database changes were handled using the search & replace tool but we were facing hardcoded links issue and we spent hours on fixing that as we never knew that it could be in css files, later on on investigation we reveal that its the css files created dynamically by elementor plugin, so my point was that can we use relative background urls instead of absolute urls?i mean can we adjust the plugin code to create relative urls in the css files i.e. ../wp-content/uploads/2018/05/sim_05-1.jpg instead of http://oursitename.wpengine.com/wp-content/uploads/2018/05/sim_05-1.jpg
? 

Its a very big problem if you are using it on a live site, i think this problem can be handled using relative links instead of using hardcoded?

Thanks & Regards,
Haider Khan

**Comment by bainternet** [comment]
@emworx 

Did you try using the "Regenerate CSS" tool? after moving?
