### ISSUE TITLE
Rich Text Editor in Slider Widget

### ISSUE THREAD

**Issue by netinstinct** [pojome/elementor#4401]
Hi,
Can you look at adding a Rich Text editor to this section. I find as a I had over to the client for their own work and additions, they can't do simple tasks such as bold, italic, underline, stroke or specific font colour in the Slides widget because they don't know coding. I have attached a screenshot for reference. 
Thanks. 
![2018-05-09_6-56-08](https://user-images.githubusercontent.com/8513781/39822392-72935b70-5378-11e8-9866-a392c1d687c8.jpg)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
