### ISSUE TITLE
Let me to decide about button transparency on hover

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4406]
Hello!
This "feature" makes me nervous. I have to write code every time:
`.elementor-button:focus, .elementor-button:hover, .elementor-button:visited {
 opacity: 1;
}`
So let me to decide about button transparency on hover please!

**Comment by chemocool** [comment]
You can set the hover color in the UI.

**Comment by parfilov** [comment]
@chemocool Color but not transparency. Check yourself.
![button_transparency](https://user-images.githubusercontent.com/12493645/39889866-e2108f20-54ba-11e8-9a13-ca8d12dc88c3.png)
The hover background is #ffffff

**Comment by chemocool** [comment]
Check the screenshot... the red bordered section let you select opacity in the button editor

![untitled-1](https://user-images.githubusercontent.com/29230607/39891795-947b3bf0-546c-11e8-9504-2e157a8cc6f5.jpg)

**Comment by parfilov** [comment]
@chemocool 
![color_100](https://user-images.githubusercontent.com/12493645/39892006-063e81bc-54c1-11e8-81cd-2657caa44b43.PNG)
I have 100+ videos about Elementor on my YouTube channel and I'm about one year with it. I'know what I say.
Please, check your hover button color with colorpicker browser extention.

**Comment by chemocool** [comment]
Pick a color, and use the slider to change opacity (drag it down).

Top position is Opacity: 1, Bottom Position is Opacity: 0.

If that doesn't solve your issue, it's because i don't understand what you want to do.

**Comment by parfilov** [comment]
@chemocool I know how to use rgba slider.
Just try to put a button before image background, then choose hover background  #ffffff and you'll see the 0.1 transparency effect.

**Comment by chemocool** [comment]
Ok, i understand what you mean and I was able to reproduce it.

You should make a proper bug report about it, it's clearly not intended.

This is in no way a "feature" :)

**Comment by pingram3541** [comment]
This is truly intentional so I would agree with the OP that it is a fixed feature and not a bug.

The .9 opacity has been there for quite some time and didn't get there by accident.  I just never got around to making a formal complaint about it being forced on us (without custom css override) but when I saw this title I was like "yeah, that thing needs to go!"

Glad this is labeled for review =)

**Comment by parfilov** [comment]
@pingram3541 I almost year with Elementor and I already don't remember about hover states. I think that transparency was added as temporary replacement of hover effect. Now, it's not actual because we have hover.

**Comment by drewclifton** [comment]
Just discovered this. Is there a fix coming down the pipe? Buttons are kind of important! :)

**Comment by fenglisch** [comment]
Is there a solution for this problem now?
I found one by adding some simple CSS to remove the effect from all buttons on my website. Just in case this is helpful for others too, I show it in this short video: https://youtu.be/8o6xfijIuN8
