### ISSUE TITLE
Elementor Role Restrictions for Admin

### ISSUE THREAD

**Issue by dotpdesign** [pojome/elementor#4410]
Need to add an Elementor restriction for Administrator role by user. Clients are also site owners so one cannot give them any less than an Admin role in WordPress . Yet, in that role, they often mess up the design of the site and would greatly benefit from the new Elementor role restrictions capabilities. If role restrictions were blanketly applied it to Admin role then no admin could see Elementor style elements, but a by user restriction would work nicely.

**Comment by bainternet** [comment]
@dotpdesign 

I Already responded in the support thread.

thanks.
