### ISSUE TITLE
Issue with Elementor and Cloudflare's Rocket Loader

### ISSUE THREAD

**Issue by obe1968** [pojome/elementor#4418]
Just a general inquiry on behalf of MANY Elementor users who are having the "Preview Cannot be Loaded" error message. There was also a ticket opened some time ago that was never actioned (responded to) Ticket# 2101

So yesterday a lot of people were getting this error, and another user in the group posted to disable Rocket loader in Cloudflare which fixed the issue for the users who are running Cloudflare. So is this all a Cloudflare issue, or something the way Elementor is loading the js files? 

Here are two links to Cloudflare that speak on the issue, and how Cloudflare needs to be configured along with the code in the js files for it to work properly. Is this something Elementor is going to fix, or are users going to just keep plugging up the Facebook community group posts with the preview cannot be loaded issues and the community is going to have to keep supporting. I have also added the find to an ongoing Elementor troubleshooting document that I have posted and maintain in the FB groups file section, and maybe the troubleshooting doc on the Elementor site could be updated as well.

https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-

https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-

I hope this will be fixed in the Elementor code :)

Sincerely,

Shawn

**Comment by bainternet** [comment]
I merged this issue with  #2101, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
