### ISSUE TITLE
Sticky header keeps stuck after scrolling back to the top

### ISSUE THREAD

**Issue by danielhoegel** [pojome/elementor#4421]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After scrolling down and up again, the header keeps stuck. The class `elementor-sticky--active` gets not removed from the Elementor header.

Example: http://homepage.hhc-duesseldorf.de/
<sup>
Wordpress: 4.9.5  
Elementor: 2.0.11  		
Elementor Pro: 2.0.5  
</sup>
## Steps to reproduce

* Create a new header template in Elementor Pro
* Activate the sticky scrolling option for the header section
* Open the page in a new tab and scroll up and down
* Watch the class `elementor-sticky--active` in the header (e.g. with Chrome Inspector)

### Expected behavior
* the class appears on scrolling down
* the class disappears on scrolling back to the top

### Actual behavior
* the class appears on scrolling down and stays

**Comment by bainternet** [comment]
@danielhoegel 

That's is the expected behavior, as long as that section is the top sticky section it will always have that class once it's activated.

thanks for the feedback

**Comment by danielhoegel** [comment]
@bainternet Thanks for your fast response. Is there any intent to change this behavior or do you have any other solution to target different styles for the sticky and non sticky header?

**Comment by lupetalo** [comment]
@bainternet @danielhoegel  This might be expected, but it is not a good behavior. It would be beneficial to have a class that appears on scrolling active, and another class when the header is at the top. Useful for example adding a subtle shadow when user scrolls and removing it when the header is at the top. Sure I can make a section below have a negative margin (as long as the shadow on the header) and higher z-index, but this feels like not the best solution...
