### ISSUE TITLE
section & image margin settings keep changing every time after being saved

### ISSUE THREAD

**Issue by huanna1994** [pojome/elementor#4422]
I have SERIOUS problems with image and section's margins. 
I changed a lot of image margins on my website, however everytime after i clicked the "save" button, those settings seemed only stay there for one day, and when i go back and changed something else on that page tomorrow (and didn't even touch that image part) ALL of those settings automatically goes back...so i have to write down all of those data and changed those image margins again and again! It's so annoy.
Sometimes, i was lucky, the margin settings were still there, but i will have to click that small icon on the right side of margin setting to unlink all the values so that the previous settings i made will show up again...
Am i the only person who's having this issue right now? 
How did you guys solved this issue?
ps. I'm using the free version.

- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
