### ISSUE TITLE
Locations Manager >> print_content()

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#4423]
I am developing a site, which _elementor_ has worked great with, but, just noticing, I didn't have older versions to test with, but it seems to have changed. 

The Print_Content() seems to throw the 'placeholder' when it should be showing get_content(); This is happening while editing an 'archive' page on a woocommerce store.

I can edit a regular "page", and the header/footer show fine. But if I do this on an "archive" page, it just shows the placeholder text "Content Area".

![2018-05-11 11_33_43-elementor _ archive product](https://user-images.githubusercontent.com/658488/39940936-ce1c3d98-550f-11e8-9b3e-f350e901d740.png)

INFO:
Latest versions of all plugins as of (2018-05-11)
Shows header/footer on edit of regular 'page'
Shows 'Content Area' on archive edit instead of header/footer

IF I just place in `$content = $document->get_content();` IN _**locations-manager.php LINE 270**_.
```
elseif ( 'placeholder' === $print ) {
   $content = $document->get_content();
   #$content = '<div class="elementor-theme-builder-content-area">' . __( 'Content Area', 'elementor-pro' ) . '</div>';
}
```
It shows the content just fine.... but I know this isn't a solution, but feel the "params" here don't quite line up..... Let me know if you need more info.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
