### ISSUE TITLE
Google Maps Widget Stopped Working On All Sites

### ISSUE THREAD

**Issue by ideasandpixels** [pojome/elementor#4424]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

All implementations of Google Maps widget on all of our clients' sites just stopped working. I've confirmed it on six sites so far. I'm assuming it's because of changes to the Maps API system (requiring an API key now). I believe we need a field for this API integration then.

## Steps to reproduce

Add the Maps Element to an Elementor page and it appears blank.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
	
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.3
	MySQL version: 5.7.22
	PHP Version: 7.0.28-0ubuntu0.16.04.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.5
	Site URL: http://ww.iandpdev.com
	Home URL: http://ww.iandpdev.com
	WP Multisite: Yes
	Max Upload Size: 34 MB
	Memory limit: 64M
	Permalink Structure: /blog/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Warped Wing
	Version: 1.0.0
	Author: Ideas and Pixels
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.5.7
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.5.8
		Author: WebDevStudios

	Easy Instagram Feed
		Version: 2.1.5
		Author: priyanshu.mittal,a.ankit

	Elementor
		Version: 2.0.8
		Author: Elementor.com

	Elementor - Template Element
		Version: 1.0.0
		Author: Ideas and Pixels

	Elementor Pro
		Version: 2.0.3
		Author: Elementor.com

	Enable Media Replace
		Version: 3.2.5
		Author: ShortPixel

	Gravity Forms
		Version: 2.2.5.21
		Author: rocketgenius

	Max Mega Menu
		Version: 2.4.1.5
		Author: Tom Hemsley

	Slider Revolution
		Version: 5.4.6.4
		Author: ThemePunch

	SSH SFTP Updater Support
		Version: 0.7.3
		Author: TerraFrost

	UpdraftPlus - Backup/Restore
		Version: 2.14.5.24
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 3.3.5
		Author: Automattic

	WooCommerce Services
		Version: 1.12.3
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.2
		Author: WooCommerce

	Yoast SEO
		Version: 7.3
		Author: Team Yoast


== Network Plugins ==
	The Events Calendar
		Version: 4.6.14.1
		Author: Modern Tribe, Inc.

	Ultimate Social Media PLUS
		Version: 2.8.4
		Author: UltimatelySocial


== Debug ==
	Errors: There are no errors to display
				
```
<details>

**Comment by bainternet** [comment]
@ideasandpixels 

We can't replicate and the maps widgets work just as before.

Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by panfanky** [comment]
This happens to me with Advanced map widget, map shows error dialog and console says: 
You have exceeded your request quota for this API. See https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors

"Google Maps" widget seems to be working fine.
(Btw. I still don't understand which google map services I can use without providing credit card)

**Comment by sunflowerspiral** [comment]
This happens to me still with the Google Maps block. Is there any way to enter an API key?
