### ISSUE TITLE
After role exclusion the Elementor admin-menu with "My Templates" still accessible

### ISSUE THREAD

**Issue by Manusan42** [pojome/elementor#4425]
Just checked "No access to editor" for the Author role and mostly all access seems restricted/items vanished.

But I still can see the main admin menu "Elementor" entry and the "My Templates" page, even if I get a "The link you followed has expired." error when I try to add a new template with the "NEW TEMPLATE" dialog.

**Comment by bainternet** [comment]
@Manusan42 

The Idea of "Content only Mode" is just as it sounds, it limits the user to edit content only in Elementor Editor. In the future, we will add more feature to the role manager, like limiting access to different sections in the admin( my templates ....)

**Comment by vovkasolovev** [comment]
I second this. Please, hide "Templates" group from the admin menu for selected users. Simple like remove_menu_page(…) for now, until implementation of other features. Right now users see a lot of horrifying information for developers and in the same time it's closed and don't allow them to work with it.
