### ISSUE TITLE
Multiple post types for a module. Need custom query

### ISSUE THREAD

**Issue by bfrye26** [pojome/elementor#4426]
Looking to move from Beaver Builder to elementor, but we have it so BB pulls from both Posts and Reviews when sorting out a query. I for the life of me can not find the hooks to do this with elementor. 

This is the query we have for BB:

function fl_builder_loop_query_args_filter( $query_args ) {
$query_args['post_type'] = array( 'post', 'reviews' );
return $query_args;
}
add_filter( 'fl_builder_loop_query_args', 'fl_builder_loop_query_args_filter' );

Any help would be amazing!

**Comment by bainternet** [comment]
We do have some filters and maybe even a custom query string feature coming up in the next version or to.

**Comment by bainternet** [comment]
I merged this issue with  #1748, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
