### ISSUE TITLE
Elementor Pro: When ACF Field Groups are Empty

### ISSUE THREAD

**Issue by crebacz** [pojome/elementor#4428]
If using ACF, and there are any registered field groups without any associated fields, there is an 'Invalid argument supplied for foreach()" warning thrown.  A suggested solution: 

In dynamic-tags/acf/module.php (~line 40),  wrap the foreach($fields as $field) within a conditional after setting options to an empty array: 

```
$options = [];
if (is_array($fields)) {
 foreach($fields as $field) {
    ...
 }
}
```

---
A separate question:  
This issue came up for me because I had an inactive field group without any fields associated with it (for reasons that aren't relevant here).  It made me wonder why fields from inactive field groups are included in the list of available ACF fields. Is there a particular use case where one would want to have fields from inactive field groups available inside elementor? If not, it wouldn't be too bad to filter those out within the same method discussed above since the field groups include an 'active' setting that you can check before running through the group's acf fields.

**Comment by bainternet** [comment]
Thanks for reporting, we'll add validation.

as for your question, we use `acf_get_field_groups` to get the groups so that question should be addressed to ACF author.

Thanks again.

**Comment by bainternet** [comment]
Validation added in Pro 2.0.6

thanks again.
