### ISSUE TITLE
How to add elements to Posts element card? (layout configuration/changes)

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4429]
Post elements is bound to the existing layout.
I wish to add "social share icons/elements", post tag and/or categories, etc...
Relocation items within the layout (Example: date at the top and the like).

Can I use shortcode to add new elements?
Is there another way to do that?

**I think that a general way to modify/configure ANY Elementor's element CONTENT will bring fantastic
required flexibility - since every designer needs it a "little different"...**
But please focus on Posts element first...

**Comment by bainternet** [comment]
This is currently only available via extending one of the posts skins
see this example on getting started: https://github.com/pojome/elementor/issues/4397#issuecomment-387680792
