### ISSUE TITLE
Feature Request: multiscroll hero images

### ISSUE THREAD

**Issue by hello2021** [pojome/elementor#4432]
I'm interested in using Elementor to create a multiscroll hero image slider as seen in this example: https://choosesantacruz.com/

Here is a multiscroll plugin for WordPress: 
https://codecanyon.net/item/multiscroll-wordpress-plugin/16025240

Would love it if we could create multiscroll hero images via Elementor.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Also next time please follow guidelines for opening a feature request.
Thanks for the feedback.
