### ISSUE TITLE
Timed content

### ISSUE THREAD

**Issue by lobogc** [pojome/elementor#4433]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently, the degree of content publishing automation with Elementor is nearly zero. There are solutions in Wordpress that allow timed content to be easily delivered. For example, certain plugins and shortcodes allow for some content to be shown on certain weekdays, or between two dates or two hours. Think about a homepage offerting offers, promotions, regular events, or pre-written content only shown when that information is relevant. 

**Describe the solution you'd like**
The simplest implementation would be a "timed content" category on the editing panel that allowed any content (or at least sections) to be shown/hidden between two different dates. More advanced options (maybe for PRO users) could extend this into a complete schedule: days of the week, different times...

**Describe alternatives you've considered**
There's a plugin for Beaver page builder allowing for this, and other plugins offerting shortcodes for regular WP pages and posts.

**Comment by bainternet** [comment]
I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
