### ISSUE TITLE
Font colors for Arabic site won't show fully on the Elementor update

### ISSUE THREAD

**Issue by seengafus** [pojome/elementor#444]
on the older version I can choose the color of the text... now I can't see all the colors, I guess it happens only for RTL  like Arabic sites. 

![19-11-37 01-33-34](https://cloud.githubusercontent.com/assets/20388105/17852018/a7ef1018-686d-11e6-8494-7c63bac5e499.jpg)

**Comment by joshmarom** [comment]
Thank you @seengafus for pointing out this glitch. We will take care of it soon.

In the meanwhile, I would like to suggest a workaround: you may expand the elementor panel:
![image](https://cloud.githubusercontent.com/assets/2726148/18091488/7d37d12e-6ed1-11e6-8aeb-d307de1cff85.png)

**Comment by cobicarmel** [comment]
Fixed by #467
