### ISSUE TITLE
Redirection after Logout for login widget

### ISSUE THREAD

**Issue by benzlim** [pojome/elementor#4447]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Redirect after logout.

**Describe the solution you'd like**
The current login widget support the ability to redirect to a different URL after successful login
Can we have the feature to allow similar redirection after successful logout in the login widget

**Describe alternatives you've considered**
This should be quiet straight forward for implementation since similar code is there for login. development team can build and allow this feature to be available help.
This would help address the requirement of  for example user after logout is suppose to go to a different page. E.g.: Customer login and after that logout goes to customer logout page whereas when vendor login and after that logout goes to a vendor logout page. 

This will then help to reduce user having to install additional plugin to facilitate such requirement and a single elementor widget would handle the full need.

**Comment by smile00000** [comment]
+1

**Comment by smile00000** [comment]
Also would like to be able to have Login / Logout feature on menu so it knows when a user is Logged In or Logged out and reflects that.
