### ISSUE TITLE
WPML and elements translation

### ISSUE THREAD

**Issue by ianstudio** [pojome/elementor#4448]
Hello,
as Boaz confirmed to me by mail support, you are aware certain elements do not comply with this WPML translation tool.

https://elementor.com/translate-elementor-with-wpml/

Could you provide a list of the elements that are compliant and those that are not.. yet ?!
So it'd be easier to decide on which to use or not, in a layout.. and also know it is an understood issue of Elementor/WPML and not some random bug on our side..

For example I just realized your Call to Action does not work.. WPML is central to some of us..

__________________

PS: What I find odd is that I use Jet Elements too (https://codecanyon.net/item/jetelements-addon-for-page-builder-elementor/20407053) and all their Elements work fine with WPML.. and so do Namogo's (https://shop.namogo.com/product/elementor-extras/)...

**Comment by JStumpp** [comment]
The "Tabs" element seem to work on the first look, but when you change the content of one tab, all the translations are gone and replaced with the new content.

**Comment by bainternet** [comment]
@ianstudio @JStumpp 

We do not provide the translation UI nor the translation functionality, its all done by WPML so we have no control over how and what works there.

meaning you are better off getting them to answer this kind of question.


thanks.

**Comment by ianstudio** [comment]
@bainternet 

Well, I'm sure there must be some liaising between each Page Layout maker and GoSystems to make sure their support of Page Layout tools work correctly.. I cannot imagine it's a one size fits all on their side.. (I am ALSO in contact with WPML).

And please read this:

Boaz repliedApr 29, 10:56

Hi Ian, Thank you for your feedback.I'm afraid you are right - at this point, the new features of Elementor Pro 2.0, i.e. the theme elements, are not fully compatible with WPML.This is something we are working to resolve, but it might take a little while.I'm sorry for the inconvenience.
Kind Regards, --Boaz
