### ISSUE TITLE
Where to import templates .json to library?

### ISSUE THREAD

**Issue by iCoachLive** [pojome/elementor#445]
Hi, Can't see where to import .json templates from one site to another. Could someone provide a link or explanation? Thanks.

**Comment by joshmarom** [comment]
In the admin panel, under Elementor > Library

Please refer to this tutorial for detailed information : https://youtu.be/7Spk7k69WZM
(around the 3:30min mark).

**Comment by redlagoon** [comment]
@joshmarom Josh, I'm a developer looking to create an automated way for me to insert templates via code. How would I tell Elementor "hey, I want to give this template for you to load" from the outside?

**Comment by crazypsycho** [comment]
Yes, there is a way to import the .json templates programmatically.

`function importTemplate( $file ) {  
        $fileContent = file_get_contents( $file );  
        \Elementor\Plugin::instance()->templates_manager->import_template( [  
                'fileData' => base64_encode( $fileContent ),  
                'fileName' => 'test.json',  
            ]  
        );  
    }`

**Comment by luqmanrom** [comment]
@crazypsycho Do you know any way to set rules after importing the template programmatically?

**Comment by crazypsycho** [comment]
I spend some hours to search for a method to set conditions and location, lot of debugging, but without a working result...
Than i´m asking me where elementor will save conditions and locations and searched in the datebase.
Both are just post_meta values, so it is very simple :-)

```php
update_post_meta( $result[0]['template_id'], '_elementor_location', 'myCustomLocation' );
update_post_meta( $result[0]['template_id'], '_elementor_conditions', [ 'include/general' ] );
```

The full code:
```php
function importTemplate( $filepath ) {
    $fileContent = file_get_contents( $filepath );
    $fileJson = json_decode( $fileContent, true );

    $result = \Elementor\Plugin::instance()->templates_manager->import_template( [
            'fileData' => base64_encode( $fileContent ),
            'fileName' => 'test.json',
        ]
    );

    if ( empty( $result ) || empty( $result[0] ) ) {
        return;
    }

    update_post_meta( $result[0]['template_id'], '_elementor_location', 'myCustomLocation' );
    update_post_meta( $result[0]['template_id'], '_elementor_conditions', [ 'include/general' ] );
}

**Comment by luqmanrom** [comment]
@crazypsycho Yep, I figured out that as well. Just need to know the string for each conditions Elementor provides. Thanks!

**Comment by crazypsycho** [comment]
I think you can find the conditions here:
wp-content/plugins/elementor-pro/modules/theme-builder/conditions
Every file is a condition. It should work like

```php
update_post_meta( $result[0]['template_id'], '_elementor_conditions', [ 'include/archive' ] );
update_post_meta( $result[0]['template_id'], '_elementor_conditions', [ 'include/in-taxonomy' ] );
update_post_meta( $result[0]['template_id'], '_elementor_conditions', [ 'include/singular' ] );

**Comment by techeshta** [comment]
> Yes, there is a way to import the .json templates programmatically.
> 
> ```
> function importTemplate( $file ) {  
>         $fileContent = file_get_contents( $file );  
>         \Elementor\Plugin::instance()->templates_manager->import_template( [  
>                 'fileData' => base64_encode( $fileContent ),  
>                 'fileName' => 'test.json',  
>             ]  
>         );  
> }
> ```

I'm using this code snippet and noticed that I can't import images with the same domain where images should be download and added with the media library too but it's not working like same.

For example, I have json link - dev.example.com/..../test.json and importing json on site - example.com.

So, images should be uploaded with the site example.com to avoid any SEO conflicts or third-party URLs.

**Comment by hotelpress** [comment]
Would this work for a Multisite?

Im looking for a way to store elementor templates in a child theme as json, and tell each page template to load that local template.

The reason: is so I can update all subsites templates together from updating files.

I cant find another way to sync/update templates across multisite

**Comment by contempoinc** [comment]
@crazypsycho Know this is a little old and this could be due to changes in Elementor but I'm using your snippet (slightly modified).

```
public function importTemplates() {  
        $fileContent = file_get_contents( __DIR__ . '/templates/elementor-demo-two-neighborhood.json' );  
        \Elementor\Plugin::instance()->templates_manager->import_template( [  
                'fileData' => base64_encode( $fileContent ),  
                'fileName' => 'elementor-demo-two-neighborhood.json',  
            ]  
        );  
}
```

Its throwing "Fatal error: Uncaught Error: Call to a member function import_template() on null" for the line:

```
'fileData' => base64_encode( $fileContent ),  
```

If I do a print_r or echo on $fileContent it dumps the proper JSON, screenshot https://share.getcloudapp.com/KourQOzj — maybe I'm missing something simple?

**Comment by crazypsycho** [comment]
That´s weird. The errors says that templates_manager don´t exists. But it should exists.
Did you use latest elementor-version?

**Comment by contempoinc** [comment]
@crazypsycho Yeah, running the latest of Elementor (free) and Elementor Pro, tried just free and Pro both ended in the same error.

**Comment by crazypsycho** [comment]
I think there is something broken or you calling the function to early.

**Comment by contempoinc** [comment]
@crazypsycho I'm running the function in __constuct(), same area I'm registering custom widgets, should be the proper place, no? Screenshot https://share.getcloudapp.com/2Nuy5YQv

Reached out to Elementor teir 3 support on this and they couldn't comment on when they'll be adding official filters for adding your own templates, also couldn't even comment on the current situation. Little disappointing that's for sure.

**Comment by crazypsycho** [comment]
@contempoinc 
You could try `plugins_loaded` instead of `upgrader_progress_finished`

Your pro-license is activated for your website?

**Comment by contempoinc** [comment]
@crazypsycho Switched to plugins_loaded and nothing happens if I deactivate/activate, if I try and access it directly with $this->importTemplates within the __construct — I get the null error which explains why nothing is happening with add_action either I'm assuming?

https://share.getcloudapp.com/z8uZ8wdw

Really just looking for this to work with the free version of Elementor, but it does the same thing with Pro and an active license.

Appreciate the help btw!

**Comment by crazypsycho** [comment]
@contempoinc 
I seen that you are using/devoloping contempo real estate custom posts.
It happens nothing, because the __construct is already called within plugins_loaded.
Here on line 63
https://plugins.trac.wordpress.org/browser/contempo-real-estate-custom-posts/trunk/ct-elementor-widgets/ct-elementor-widgets.php

The direct call of importTemplates in your __construct should be the right position.
So i don´t know why this will not work.

But a workmate found another way to create a template:
```php

    /**
     * Import an Elementor Template from an local file
     *
     * @param string $filepath
     */
    public static function importTemplateFromFile( $filepath ) {
        require_once WP_PLUGIN_DIR .
            '/elementor/includes/template-library/sources/local.php';

        $filename = pathinfo( $filepath, PATHINFO_BASENAME );

        $local = new Elementor\TemplateLibrary\Source_Local();

        $local->import_template( $filename, $filepath );
    }
```

It seems that this is not the cleanest way, but the required local.php exists also in elementor 3.0 beta, so it should work also with 3.0.

**Comment by contempoinc** [comment]
@crazypsycho Yeah, its odd I'm stumped.

For the workaround and the require_once what would be the best way to reference that from the Elementor plugin itself and not copying files? Or am I misreading?

**Comment by crazypsycho** [comment]
@contempoinc 
I'm not sure why local.php is not always included at this point. Actually it should be that in plugins_loaded.
But it doesn't have to be copied. Require just means that the file will be loaded at this point. And once that it is only loaded if it is not already loaded.
So I think there is no problem doing it like in the example.

I am not a freelancer. I do this professionally as an employee. And when I have the time and inclination, I also help out whenever I can.

**Comment by contempoinc** [comment]
@crazypsycho Gotcha, thanks for the clarification on that, now I'm getting a different error https://share.getcloudapp.com/NQur7wr6 also went ahead and printed $filepath and $filename make sure those were being retrieved and its working, but seems to be similar to the problem I was having before? Screenshot of the functions for posterity https://share.getcloudapp.com/9ZuXRx8L

Appreciate the time as well, honestly thanks so much!
