### ISSUE TITLE
Integration with IFTTT

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#4451]
I know I can do an integration between Elementor and my email capture tool through Zapier.
But you guys could also do this integration with the IFTTT.

Thanks,
Rodrigo Carlos

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

for now, you can create a custom webhook for that.

Thanks for the feedback.

**Comment by chandlerbing26** [comment]
Yeah Badly need this feature
