### ISSUE TITLE
POPUP functionality

### ISSUE THREAD

**Issue by uxdsaine** [pojome/elementor#4453]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Lead generating forms or a images are a great examples why a popup function will be helpful. 

**Describe the solution you'd like**
I'm personally interested in a contact form set by a number of triggers, when they intend to leave the page, after a few seconds of visiting such page, etc. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bainternet** [comment]
@uxdsaine 

I can happily say that we are actively developing this functionality.

**Comment by arielk** [comment]
I merged this issue with #628 , which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!
