### ISSUE TITLE
Before & After Photo

### ISSUE THREAD

**Issue by uxdsaine** [pojome/elementor#4454]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When showing the progress or an existing project and want to showcase the development, a before and after photo functionality will be helpful. 

**Describe the solution you'd like**
When you grab (click and hold) the handle you can swipe left and right to view the before and after of the image. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bainternet** [comment]
can you provide an example?

**Comment by uxdsaine** [comment]
Example 1:
https://codecanyon.net/item/before-after-image-slider-for-visual-composer/9978381?ref=wpbakery&vc_outbound=true
Example 2: https://revolution.themepunch.com/before-after-slider/

Hope this helps.


*UXD Saine*
*{User Experience Design}*
Jonatan Saine | Owner
Web & Brand Consultant

*p. *(949) 292.0185
*e.* uxdsaine@gmail.com
*w.* uxdsaine.com

**Comment by bainternet** [comment]
You mean like this http://jetelements.zemez.io/image-comparison/

well its already available via a 3rd party plugin, 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
