### ISSUE TITLE
[BUG] Elementor + Polylang, Autosave resets Template

### ISSUE THREAD

**Issue by kokers** [pojome/elementor#4458]
When editing some elementor pages, "Template" keeps reverting back to "Default Template". 

This only happens when opening standard WordPress edit view, via "Edit" or title link on page list. The only thing you have to do is open standard wp edit and wait. There is an autosave in the background and Template is reset to Default template during that action. Once template is reset there is no way of changing it. Not with wp edit, not with elementor edit mode in page settings. Only using "quick edit" on page listing will save selected template. 

When going directly to edit mode via "Edit with Elementor" template value is preserved. But once we use "Exit to dashboard" we are back to WP standard edit mode and there is 50% chance it will be reset again.

This doesn't happen for pages that use standard WP editor. Only for some of those created with Elementor editor when opening standard view. I assume that there is some hook during Autosave that is used by elementor that cause this.

WordPress: 4.9.5
Elementor: 2.0.11
Polylang: 2.3.5

Theme: Twenty Fifteen
Switching template to Elementor Full Width

All other plugins disabled.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by kokers** [comment]
Because this bug was fixed via mail support, to anyone with the same issue message from Elementor Team:
"This issue is resolved and will be released in Elementor (free) version 2.1"
