### ISSUE TITLE
Access to custom variables

### ISSUE THREAD

**Issue by timschaaf** [pojome/elementor#446]
It would great to be able to pull custom variables into Elementor for use in the sections / elements. It appears that custom PHP (using something like EXEC_PHP) is not accessible to Elementor. 

For example:

eg. <?php $example_var = 25; ?>

And then in the Elementor 'Counter' element, use $example_var instead of a fixed digit.

**Comment by mediaworksmt** [comment]
Could you simply use the [PHP Code Widget](https://wordpress.org/plugins/php-code-widget/) along with the [get_post_meta()](https://developer.wordpress.org/reference/functions/get_post_meta/) function to accomplish this?

**Comment by yehudah** [comment]
I think it's really bad practice to include php code like EXEC_PHP.

if you still want this, use what @mediaworksmt offered.

**Comment by mediaworksmt** [comment]
I'd agree with @yehudah , anything which uses PHP `eval()` is territory for a security issue. Bad practice.

Creating a shortcode like [get-meta key="some_meta_key"] and using that within a Text Editor widget would be much better.

I'm experimenting with creating Elementor widgets right now and hope to contribute something that can easily pull a list of meta keys for a Post and display string/comma-separated/serialized/JSON meta values in the near future.
