### ISSUE TITLE
Sticky Navigation Menu that Changes Background Color on Scroll

### ISSUE THREAD

**Issue by VictorAlianich** [pojome/elementor#4460]
Please add the ability to create sticky navigation menus that change background color on scroll.

**What problem is your feature request going to solve? Please describe.**
This let's the users navigate the site better and see the menu options more clearly no matter what section of the page they are on.

**Describe the solution you'd like**
Same behavior as in example: https://avada.theme-fusion.com/header-transparent/

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


Only via custom CSS.

Thanks for the feedback.

**Comment by quantumleap33** [comment]
+1 one for this. This is standard behaviour for all sites. There should be an option to style it from inside Elementor.

**Comment by IamSiddharth** [comment]
Please add this feature

**Comment by apollollc** [comment]
+1 ...this is the biggest negative to an otherwise amazing page builder.

**Comment by beziehungsweise** [comment]
+1 ... very much needed!!!
