### ISSUE TITLE
Modal Popup on Button Click

### ISSUE THREAD

**Issue by VictorAlianich** [pojome/elementor#4461]
Please add the ability to display modal popup window on button click.

**What problem is your feature request going to solve? Please describe.**
This allows to better convert users into subscribers as they won't have to leave to another page to fill in their details.

**Describe the solution you'd like**
Same behavior as in example plugin: https://wordpress.org/plugins/modal-for-elementor/

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by bainternet** [comment]
I merged this issue with  #4453 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
