### ISSUE TITLE
Integrate Forms with MailerLite

### ISSUE THREAD

**Issue by VictorAlianich** [pojome/elementor#4462]
Please add the ability to integrate forms with MailerLite.

**What problem is your feature request going to solve? Please describe.**
This allows to register all subscribers in MailerLite.
MailerLite is the most user-friendly email automation tool. 
Elementor is the most user-friendly Wordpress page builder.
It's a match made in heaven. 

**Describe the solution you'd like**
Same as integrating with Mailchimp, but using MailerLite, which is better. 

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by bainternet** [comment]
guide here: https://github.com/pojome/elementor/issues/2397#issuecomment-361185892

**Comment by cobusvanvuuren** [comment]
As a non-technical guy can we still ask for a integration with Mailerlite or is that should I try to work around it?

**Comment by parfilov** [comment]
+1 for native support

**Comment by arielk** [comment]
This integration is now available in Elementor Pro v2.3.0

Thanks for your feedback!
