### ISSUE TITLE
on Hover Card or DIV box with button similar to Flip Boxes

### ISSUE THREAD

**Issue by strategicweblabs** [pojome/elementor#4465]
The only post I could find here was referring to a Portfolio Widget, however, in this request, I don't need the meta data...

I'm calling this a Hover Card, as I'm not sure of the technical term to give it.

This element is essentially a basic div box with Title, brief description text and List items, what I'd like to add to this is when a user hovers over the box, the box 'lifts off the page' (for lack of better terminology) and a button link shows at the bottom.

An example of this can be viewed on semperhomeloans.com (I'm not affiliated, nor do I endorse this site in any way)

Half way down the page you can see examples of this element I'd like added to Elementor when you see the "mortgage options".

I know this is some simple CSS coding, but I've looked around the net to do this manually and could not find it anywhere, unless I'm using the wrong search parameters.

If someone has the CSS I need to make this happen, by all means, feel free to send it my way!!  But I know this is a feature that I'd like to use on a number of client websites.

Thank you.

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Currently only via custom CSS.

Thanks for the feedback.

**Comment by strategicweblabs** [comment]
Thank you for your response bainternet!

Is there anyone that wouldn't mind helping me with custom CSS coding this element?  I know some, but not enough to make this happen.

Thank you!
