### ISSUE TITLE
[Feature request] Stick the toggle to the top of the page

### ISSUE THREAD

**Issue by oshibobo** [pojome/elementor#4466]
Hi, Would be nice if we have the Option to stick the Toggle burger menu at the top regardless where we position the menu navigation, We should have the option to enable the toggle for desktop or small devices,  stick the toggle to the top of the page and style to position to | Canter | Left | Right | Bottom. And the option to change the icon to Menu text 👍 

Thanks

**Comment by bainternet** [comment]
Thanks for the feedback
,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This request is missing key information: 

* Prerequisites.
* Examples.

**Comment by oshibobo** [comment]
Like What?
