### ISSUE TITLE
[Feature Request] Publish Posts within Elementor

### ISSUE THREAD

**Issue by mediaworksmt** [pojome/elementor#447]
Currently when writing a new Post (or Page, Custom Post Type, etc.) clicking the green Save button only saves the new Post to a draft.

Would be nice to have a "Publish" option somewhere. 

Perhaps when hovering over the Save button, a Publish button could appear? Visual idea attached below, although there may be a more elegant solution. 

![elementor_publish_button_idea](https://cloud.githubusercontent.com/assets/17885355/17912900/d7ca6e72-6953-11e6-87f6-acd473d811e4.png)

**Comment by yehudah** [comment]
Hi,

Your great feedback forwarded to the right person.

Thanks

**Comment by toderash** [comment]
Is this being added to a milestone anywhere? I want to install and train users on this, but the lack of a publish button will be a showstopper for them since it's too convoluted a process for them to find the post and publish it as a completely separate step. Big +1 for this feature.

**Comment by arielk** [comment]
@toderash Hopefully, the upcoming versions, it is definitely an interesting feature

**Comment by arielk** [comment]
1.4.0 released
