### ISSUE TITLE
Ability to hide areas & widgets when ACF value is empty

### ISSUE THREAD

**Issue by Jaska** [pojome/elementor#4472]
Now with theme builder it's very handy to create page templates which bring values from ACF (Advanced Custom Fields).

Usually with ACF, I create logic e.g. 
```
if (get_field('caption'){
echo '<div class="caption">'.get_field('caption').'</div>';  }
```

That way I don't get an empty .caption box if the field is empty.

If think Elementor could do this logic quite easily - just add a dynamic field value into "advanced" > "responsive" area. The place where there are "hide from desktop…" buttons.
"Hide when field X is empty"?

This could be done with javascript but I'd like to know your opinion.

Thanks!

**Comment by bainternet** [comment]
Duplicate of #4246

**Comment by portrayaloflife** [comment]
+1
