### ISSUE TITLE
Drag and drop bug

### ISSUE THREAD

**Issue by ericft** [pojome/elementor#4474]
Hi,
When I try to move a section, the section disappear and the console gives a backbone error
https://screencast.com/t/9hpbi7OJByqD
https://screencast.com/t/rjC5em8e6
Thank you

**Comment by ericft** [comment]
I think it's caused by ACF.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
