### ISSUE TITLE
WooCommerce "Products" Single template does not show up as option

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#4475]
I tested with different themes, disabled all plugins. 
This 'was' working, but I cannot seem to find out why WooCommerce CPT "products" is not showing up. 

**Story:** 
I was developing a site, designing Single Product Pages, and all was working great. I was making some changes to the base of the theme. And I broke something in the theme. After fixing it, I was not able to get the "products" to show up. I tried a new theme, and still the same issue, disabled plugins, still not showing up. 

**Issue:**
When selecting, Archive/Single on a new 'template', it is now showing up as an option to select Product. 

**System:**
I have all latest plugins of Elementor installed. I did try to downgrade to .11, but didn't seem to solve it either.

I have attached two images for reference showing which items are available. 

![2018-05-16 12_50_32-my templates candy club wordpress](https://user-images.githubusercontent.com/658488/40141050-6b7b322c-5909-11e8-87d8-1cf356ee9d1b.png)
![2018-05-16 12_53_27-elementor candy club wordpress](https://user-images.githubusercontent.com/658488/40141051-6b9b69d4-5909-11e8-88f8-7bc438244d55.png)

**Comment by bainternet** [comment]
Not a bug, a feature since v2.0.7 

preparing for 2.1.0 with full Woocommerce support.

thanks for the feedback.

**Comment by stickypages** [comment]
@bainternet Oh... it WAS working through, so why remove it? When will 2.1.0 be out? I was developing accordingly, with it working... Thanks!
