### ISSUE TITLE
AUTOMATIC Elements Orientation (ltr/rtl) to support translators

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4476]
Related issue: #4471

I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The problem: How do I translate (Hebrew to English) the following:
```
<span class="elementor-button-icon elementor-align-icon-left"> 
    <i class="fa fa-caret-left" aria-hidden="true"></i> 
</span>
```
To 
```
<span class="elementor-button-icon elementor-align-icon-**RIGHT**"> 
    <i class="fa fa-caret-**RIGHT**" aria-hidden="true"></i> 
</span>
```

**Describe the solution you'd like**
Allow AUTOMATIC  **Orientation** is_rtl/ltr() behavior.

A simple CHECKBOX telling Elementor how to behave in rtl/ltr direction.
Using **predefined** rules. As described above. As this should cover IMHO 95% of cases...

**Describe alternatives you've considered**
1. Using jQuery/CSS is ugly.
2. Letting WPML and others is messy and its NOT their job!!!
    Its page builder responsibility to support "dynamic"/"on-the-fly" rtl/ltr directions.
3. Duplicating element under is_rtl() condition is complex and wrong UI solution.
4. Using shortcode - makes Elementor redundant & its time comnsuming.

**Additional context**
The benefit is also by keeping plugin translators OUT of Elementor internals...

**Comment by bainternet** [comment]
@Mulli this is not something we can anticipate or control.

What if the icon is a star? then what happens in ltr/rtl??

as long as the icon is a user selection it's not translatable or bound to document direction ( ltr/rtl ).

If the icon is something we set (none user selection) its wrapped in an is_rtl() to output the correct direction but this is only done on "hardcoded" strings and not user selection.

Also, as a side note, Elementor is not a translation plugin.

thanks for the feedback.
