### ISSUE TITLE
Not displaying Updated Content.

### ISSUE THREAD

**Issue by SanthoshOutright** [pojome/elementor#4477]
## Description
After editing with elementor Couldn't See changes made up by wordpress editor in single ( Updated Post ) Page .

## Steps to reproduce
- [ ] Dashboard -> Add New Post -> With Dummy title and content -> Publish as  Default Template

- [ ] Edit or Update the Content by using Elementor  -> publish it.
-- ( Elementor Revision )
- [ ] Edit or Update the Content by using wordpress editor -> publish it.
-- ( Wordpres Revision )
- [ ] View the Post in Site.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Isolating the problem.
* System info.
