### ISSUE TITLE
Not displaying Updated Content.

### ISSUE THREAD

**Issue by SanthoshOutright** [pojome/elementor#4478]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description
After editing with elementor Couldn't See changes made up by wordpress editor in single ( Updated Post ) Page .

## Steps to reproduce
- [ ] Dashboard -> Add New Post -> With Dummy title and content -> Publish as  Default Template

- [ ] Edit or Update the Content by using Elementor  -> publish it.
-- ( Elementor Revision )
- [ ] Edit or Update the Content by using wordpress editor -> publish it.
-- ( Wordpres Revision )
- [ ] View the Post in Site.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
``` Wordpress  4.9.5 and  Elementor  2.0.12
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Isolating the problem.
* System info.
