### ISSUE TITLE
Bug: Woo Products manual selection does not show more than 10 items

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#4479]
It's not possible to show more than 10 items with the WooCommence Product element on Manual selection.

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
I have lots of Woocommerce products and want to highlight some of them. Thats why I wanted to use a manual selection of 12 products. However it only displays 10 of them.

## Steps to reproduce
Create lots of products in Woocommerce (minimum 12)
Create new page and use Woo - Products element
Set layout to items per column: 6 and Product counts 12
Set Query to manual selection
Select 11 or 12 products and only 10 will show.

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
Thanks for reporting, this should be fixed in the next Pro version.

**Comment by arielk** [comment]
Fixed for E-Pro v2.0.8

Thanks
