### ISSUE TITLE
[Feature Request] Show a list of Pages, Posts, CPTs, etc. with the Elementor link URL field

### ISSUE THREAD

**Issue by mediaworksmt** [pojome/elementor#448]
One of the most helpful things added to WordPress in the past years has been the "Link to existing content" option when creating links.

It would be nice to see similar functionality carried into Elementor.

For example, when someone clicks the Link field while editing an element (i.e. a heading, an image, etc.) and types in "About", all of the WP Posts which match the string _About_ would show in a list below. The user could then simply click the desired one, and it's URL would be added to the Link field.

Visual attached below. Thanks!

![elementor_select_content_link_idea](https://cloud.githubusercontent.com/assets/17885355/17913333/734fd894-6956-11e6-9b13-9bce4cd0446e.png)

**Comment by yehudah** [comment]
Thanks for your feedback.
we considering this feature but maybe in the future.

**Comment by arielk** [comment]
Duplicate #255

**Comment by htaaning** [comment]
This is an essential feature. Any idea how far away this is? 
It´s a dealbreaker for me, and I really want to start using Elementor (Pro)
