### ISSUE TITLE
ACF shortcodes not working in Elementor?

### ISSUE THREAD

**Issue by codeagencybe** [pojome/elementor#4482]
Hi guys,

I'm trying to build a dynamic custom post type with a call to action widget + ribbon/lint on it. 
The text in the lint needs to be dynamic, and it's saved as a simple text custom field made with ACF Pro. 

So far, Elementor Pro has "limited" support for loading ACF fields directly via the dynamic button into several widgets, but what about ACF shortcode support? 
I want to go a little bit further, even though the dynamic button is not available yet so I don't mind pasting the shortcodes myself. But at minimum they should work this way, no?

According to ACF documentation, the below shortcodes should work fine, but in my end nothing is loading at all, or it outputs the code instead of rendering it. 

     [acf field="{$field_name}"]
OR

     [acf field="{$field_name}" post_id="{$post_id}"]

I tried adding the field also in a simple text field, but the output is completely empty. 
This is the most basic method, and this also does not work. 
Any idea why it's not pulling my custom field data? 

I've been searching, and trial and error for hours straight, but nothing comes out how I want it. 

Any feedback and a workaround on this is greatly appreciated.

**Comment by ljubacanoa** [comment]
It works well with Toolset and I don't see any reason why would not to work with ACF. You probably (actually, 101% sure) did not set everything right. 

- Did you set all what you need in Elementor settings (Elementor support for pages/posts)?
- Did you set all what you need in 'Single Settings' (bottom left button on your Elementor edit page), primary 'Preview Settings' (that is your complaint and probably the issue)?

**Comment by codeagencybe** [comment]
@ljubacanoa 

1. Yes, my settings are correct. 
I have build an entire custom CPT archive page and single CPT page. All "normal" fields show up perfectly fine. 
I'm trying to output some other fields that I can't do with the available "dynamic" button from Elementor itself, so I'm using a text field and put inside the "text" view the official ACF shortcode like  [acf field="{$mycustomfield}"] but the text field just remain completely empty. 

2. Yes, that is set correctly, like said above, all other fields are rendered all fine. 
I tried in a another test setup with Pods, and that works fine. Strangely, just not with ACF (pro). 

I'm scratching my head as something "obvious" as the official shortcodes should work just fine. 
I didn't try yet in other types of widgets because I thought with a regular text field, it should work best.

**Comment by bainternet** [comment]
Glad you figured it out.

**Comment by bulutemre** [comment]
That is but really crazy. I also couldn't figure it out without your comment. Why they wrote $ inside the code in Documentions?

**Comment by codeagencybe** [comment]
@bulutemre
I have no idea but I wasted a lot of hours on that stupid mistake in the documentation.
