### ISSUE TITLE
Feature request: Add ability to create custom/extend sections and columns

### ISSUE THREAD

**Issue by andreasnrb** [pojome/elementor#4489]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
**Describe the solution you'd like**
I would like to have the ability to create my own predefined sections and columns. For example I want to have premade sections that already contain certain widgets. Or the ability to create my own templated columns where perhaps one column is empty and can be filled. This would really help with reuse and remove need for templates and enable updates of sections without readding a template.
Currently I can't figure out how to add my own sections except by forking the Elementor plugin and add more sections to the JavaScript source.

**Describe alternatives you've considered**
Premade section templates.

**Comment by arielk** [comment]
Sorry, but for now this is not possible, maybe in the future we'll add this feature.

Thanks for your feedback!
