### ISSUE TITLE
Vertical tabs?

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#449]
It would be great if the tabs widget had to option to display horizontal or **vertical.** Here's an example using Beaver Builder. Is this feature on the way?
<img width="656" alt="vertical-tabs" src="https://cloud.githubusercontent.com/assets/974442/17913999/537ecb0e-6953-11e6-892c-41df850449f9.png">

**Comment by yehudah** [comment]
Thanks,
I have send your issue to the right person and it will be considered.

**Comment by mizejewski** [comment]
Thanks Ariel and Yehuda

**Comment by mizejewski** [comment]
@arielk is this slated for the Pro release?

**Comment by arielk** [comment]
@mizejewski Not sure, we didn't get a decision on this issue

**Comment by mizejewski** [comment]
Please DO include it -- I think a lot of Elementor users need this and are trying to force workarounds.

**Comment by mizejewski** [comment]
This is great news! Thanks.
