### ISSUE TITLE
How can I check if the user is currently editing using Elementor?

### ISSUE THREAD

**Issue by redlagoon** [pojome/elementor#4491]
Akin to `is_customize_preview`, I'd like to know if Elementor has a function to check whether or not the user is editing a page using Elementor. I want to use this to either display some stuff or not.

Any help?

**Comment by bainternet** [comment]
Elementor has a method called `is_edit_mode()` in the `Editor` class so you can use that ex:

```PHP
if ( \Elementor\Plugin::$instance->editor->is_edit_mode() ) {
     // do stuff for edit mode
} else {
    // not edit mode
}
```

There is also a method called `is_preview_mode` in the `Preview` class which lets you know if its currently a preview or not ex:

```PHP
if ( \Elementor\Plugin::$instance->preview->is_preview_mode() ) {
     // do stuff for preview
} else {
    // not preview mode
}
```

**Comment by DevinWalker** [comment]
Just wanted to chime in this has worked nicely for me:

```
function givewp_check_is_elementor(){
    global $post;
    return \Elementor\Plugin::$instance->db->is_built_with_elementor($post->ID);
}
```

Note: add you own prefix in place of `givewp`. :)

**Comment by Nazrinn** [comment]
I'd like to add that if you want to detect if you are in preview/editor mode in Elementor (2021), you can use this snippet:
````
$current_url = $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
$is_preview = \Elementor\Plugin::$instance->preview->is_preview() ?? false;

if(strpos($current_url, 'preview=1') !== false || $is_preview !== false) {
   //You are either editing this page with Elementor or previewing the page.
}
````

**Comment by unikforceit** [comment]
> Just wanted to chime in this has worked nicely for me:
> 
> ```
> function givewp_check_is_elementor(){
>     global $post;
>     return \Elementor\Plugin::$instance->db->is_built_with_elementor($post->ID);
> }
> ```
> 
> Note: add you own prefix in place of `givewp`. :)

This one is really helpfull what we are looking for
