### ISSUE TITLE
Theme builder disables ad injection to pages

### ISSUE THREAD

**Issue by yoavshai** [pojome/elementor#4493]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
As a small publisher that uses Google's out ads + ad injection plugins, I have encountered a problem with Elementor pro theme builder and ad injection. When the theme builder is activated on a page, both ad injection methods are disabled. The only ads that appear on pages are ones that are placed on the page via shortcode, or with Google auto ads - before or after the content, instead of throughout the content.
Before theme builder
https://drive.google.com/file/d/1OGDVF6v92Q4n3La_nfMyF9fUOQcYKL0z/view?usp=sharing
After theme builder
https://drive.google.com/file/d/1x-bcZgChZHREqrezID-tFbS2vAts8qgf/view?usp=sharing

## Steps to reproduce

Use ad injection plugins such as Advanced Ads to inject an ad into a post in the original theme. You can inject the ad between paragraphs or before/after the content, It doesn't really matter. Publish the post and see that the ads are injected properly. Use Elementor pro 2.0 to redesign the posts on your site. Publish the new design and preview the post. You will see that the ads don't load. From my checkups, their code doesn't appear on the page's source.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.33 (cPanel) OpenSSL/1.0.2o mod_bwlimited/1.4 Phusion_Passenger/5.1.12
	MySQL version: 5.6.39
	PHP Version: 7.0.30
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: XXX
	Home URL: XXX
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Jerusalem
	Debug Mode: Inactive

== Theme ==
	Name: Buzz Child
	Version: 1.0.0
	Author: Pojo
	Child Theme: Yes
	Parent Theme Name: Buzz
	Parent Theme Version: 5.0.0
	Parent Theme Author: Pojo Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by arielk** [comment]
Please try to change the priority of the content, The content filter priority of Elementor is = 9

**Comment by yoavshai** [comment]
@arielk Thanks for your reply. I might be missing something, how can I change the priority of an element in Elementor?

**Comment by arielk** [comment]
This is something that you need to change in your injection plugin not in Elementor.

Which plugin are you using?

**Comment by yoavshai** [comment]
At the moment I am using [Advanced Ads](https://wpadvancedads.com/).

**Comment by bainternet** [comment]
@yoavshai 

You need to change the priority of `the_content` hook of Advanced Ads to something higher then Elementor so that it will run after elementor has build the content. 

Thanks.
