### ISSUE TITLE
Elementor template - Archive posts customization missing features

### ISSUE THREAD

**Issue by Hanleymade** [pojome/elementor#4499]
When creating a new "archive" template using Archive post" elements there a few features that would be useful:

- No option to add the category or tags next to the other meta data. In the layout below the blog post title one can pick: author, date, time, comments but not category or tags.

- No option to show "full post" rather than excerpt for each post. If one chose to display one column with X number of blog posts, only option of display is to change excerpt length. 

Note: I tried the Premium Addons for Elementor plugin and they provide both of these options in the settings. Can't we put ithem in the Elementor options as well?
![image](https://user-images.githubusercontent.com/39174715/40324961-11d33ed8-5cef-11e8-8558-3e25b08752fc.png)
![image](https://user-images.githubusercontent.com/39174715/40324995-24f4121c-5cef-11e8-90d9-af479e26abaf.png)

**Comment by Hanleymade** [comment]
Anyone looking at these?

**Comment by klarakalko** [comment]
Of course. Even if they don't reply right away, they do pay a lot of attention to feature requests and reported bugs.

**Comment by HmCody** [comment]
I would also like to see the feature of being able to include the full post with HTML in the archive!

**Comment by pawelszroeder** [comment]
I agree, in Elementor Anywhere Pro there is option to create post block and use it on Archive page. I think Elementor should add this feature, because I'd like to use only this plugin without other addons.
I also creater feature request: https://github.com/pojome/elementor/issues/4667

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by cvansas** [comment]
I was wondering if it would also be possible to add a condition to the short introductary text. Wordt count is a good criterium but what if you only want to show the Header text of an article? I dont want to show the articles content after an introduction of 30 words if the header text is only 20 words.
