### ISSUE TITLE
Slider & Carousel wdigets - Randomize Slides

### ISSUE THREAD

**Issue by Richardsi3000** [pojome/elementor#4500]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We have a large number of pictures of children and we'll like not to have any of the pictures
be emblematic of our site. Having many images randomized will help not having any of the pics be
automatically associated with our site.
**Describe the solution you'd like**
Add the feature to randomize images and slides to slider and carousel widgets. Every time the page
is loaded the slides should be randomly showen automatically by the slider.
**Describe alternatives you've considered**
If elementor can't add this feature I will have to use an alternative plugin

**Additional context**

**Comment by arielk** [comment]
Sorry, but for now this is not possible, maybe in the future we'll add this feature.

Thanks for your feedback!

**Comment by Claus-Springborg** [comment]
Hi Elementor

I have the same request ;-)
It would be nice if you could choose a random option in the Image Carousel   Widget ;-)
Regards
/Claus

**Comment by vasnakos** [comment]
Hi Elementor Team,

I'd like to have a randomize option for Media Carousel items too.

Best

**Comment by dimoteca** [comment]
+1

**Comment by vasnakos** [comment]
I managed to achive this with some suggestions found [here](https://github.com/kenwheeler/slick/issues/359)

**Comment by Code711** [comment]
+1

**Comment by Code711** [comment]
I found a workaround: you can use the slider widget of JetElements from Zemez, there is a shuffle-feature: https://zemez.io/wordpress/support/knowledge-base/slider-jetelements-module-elementor/

**Comment by adamshand** [comment]
I would also love the ability to chose a random starting point for sliders or a random set of images for an image gallery.

**Comment by kneops** [comment]
+1 Just got this request from a client

**Comment by digitalchet** [comment]
Count me in for this one.

**Comment by bkwineper** [comment]
Me too! It would be a very big improvement of of the Image Carousel widget.

**Comment by emsi68219** [comment]
Yes, I agree. I also would like to see this "ramdom feature" in carousel

**Comment by artscan** [comment]
Count me in!!! This request has been open for a while now. I don't want these bloated 3rd party plugins.

**Comment by warudin** [comment]
This would be a real nice addition.

**Comment by zpetricevic** [comment]
+1
much needed option

**Comment by sh1va73** [comment]
Yes me too I am looking for this feature.

**Comment by Anoobis117** [comment]
Count me in :)

**Comment by huriprod** [comment]
Me too, I need this option please.

**Comment by rohilv** [comment]
+1

**Comment by jpgif** [comment]
Hi guys, any of you have found a workaround, would be perfect if we could have a "random" or "shuffle" switch or just a piece of code,  I think having random pictures spice things up on any design, it keeps it fresh! 
Thank you!

**Comment by OpenDoorMarketingES** [comment]
This key feature is needed

**Comment by speedxcz** [comment]
Although it probably doesn't matter, it seems to me that no one looks here, but I'll give +1 anyway

**Comment by vgstef** [comment]
It seems that a lot of people would like this feature! Car Elementor team add this to the Roadmap?

**Comment by zpetricevic** [comment]
I managed to get this effect with this:
https://element.how/elementor-slider-random/
