### ISSUE TITLE
Error When Updating Pro

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#4502]
**Update Failed: Could not create directory. elementor-pro/modules/countdown**

I get the above error when updating to the latest version of Pro on my dev site at my localhost.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

So we are only left with guessing whats wrong, please refer to this guide: https://docs.elementor.com/article/235-update-issues
