### ISSUE TITLE
Transition duration is not working in gradient background

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#4503]
Hello,

I have tried to use "transition duration". But it's not working in gradient background and background overlay.

![image](https://user-images.githubusercontent.com/5612050/40353687-0bb25fe4-5ded-11e8-9f9e-d3e5d8de6cb6.png)

Can you please check it out? It should be opacity transition, isn't it?

I use all the newest version of elementor / pro

Thank you for a great plugin,

**Comment by joshmarom** [comment]
Hi @pulla 
This is a CSS limitation.
Gradient is using the `background-image` property. Unfortunately, this property is not animatable.

Here's a list of [animatable CSS properties.](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)

**Comment by sabbir1339** [comment]
Well, I tried with animatable properties "background" in custom CSS. It's not working either.

**Comment by SpinDreams** [comment]
This is a bug, but a workaround is if you set the normal overlay colour to fully transparent then the transition works.
