### ISSUE TITLE
Post Gallery Dynamic Content

### ISSUE THREAD

**Issue by ljubacanoa** [pojome/elementor#4504]
Elementor Support point me to make 'Feature Request', but I rather think that it is the **BUG** (as Elementor not '_working as expected_').

From my point of view (I could be wrong), 'Post Gallery Dynamic Content' feature is **for some reasons** (I guess) disabled from option to select 'field key' (as for Post Custom Field > Settings > Key), what makes 'Dynamic Content' essentially completely useless, as it 'pull' **ALL IMAGES** from the page/post.

So, I'm wandering about what possible page/post scenario can be (can to exists) where developer/author want to make gallery of all images from the page/post?

Examples, City (attractions, parks, city flag, city shield, city representatives, .... ALL IN SAME GALLERY - ???), Hotel (outdoor, personnel, logo, room one, room two, King Suite, ..... ALL IN SAME GALLERY - ???), Restaurant (interior, street view, kitchen, bar, personnel, menu/dishes, ... ALL IN SAME GALLERY - ???), ....

I can agree about 'feature request' vs. possibility that with 'field key' option will be possible to get more galleries on same page/post, but here is primary issue that I cannot imagine (indeed, I can, but very rare cases) why anybody will want all images from page/post in same gallery (so, to not exclude neither one single image). For such reasons, I believe that we should to talk about the **BUG** ('_something is forgotten to be included for usual functionality of the complete feature_').

If there is some reason that 'field key' is disabled (or more precise, not included), this is the **FEATURE REQUEST**, but I doubt that exists some reasonable explanation. Probably nobody seriously thought about logical functionality of such '_barebone_' 'Post Gallery Dynamic Content', what makes it **BUG**.

**Comment by Hanleymade** [comment]
Does Elementor actually check their github to provide feedback?

**Comment by bainternet** [comment]
@ljubacanoa 

Thank you for your opinion, it is dynamic because if it is used in a "Single" template it pulls the images from that post.

I understand that it doesn't meet your use case needs but that does not define a *BUG* (. 

As for the "key" field, can you explain how would that help you? because "key" is used to pull data for a  custom field and as far as I know, you can't create a gallery and store it in a custom field without custom coding or a 3rd party plugin.

**Comment by ljubacanoa** [comment]
"_As for the "key" field, can you explain how would that help you? because "key" is used to pull data for a custom field and as far as I know, you can't create a gallery and store it in a custom field without custom coding or a 3rd party plugin._"

That's true, but it looks that somebody (me or you) miss something.

As far I understand English, you claim that "dynamic" is intentionally created by Elementor **only for standard post content** (see part - 'without custom coding or a 3rd party plugin'), as well that gallery exist only for standard post content (I don't think so, as there is only one image - featured, plus images inserted via editor - what is kind of custom content).... it will look complicated. Let's go briefly, as I don't want to argue about usage scenarious.

If I (anybody) create Custom Post Type, there is mostly ZERO chance that such CPT will not contain (mostly) custom fields. So, if I create any kind of custom field (supported via key in Elementor Dynamic), why you (Elementor) make difference regards **image custom field**???? They (image custom fields) are also custom fields and also with keys (slugs).

EXAMPLE (very common)

Restaurant custom post type - images (separate galleries) for outdoor/indoor, for stuff/kitchen, for dishes, .....sounds natural and 'normal scenario' or not? 

Hotel CPT - images (separate galleries) for outdoor/indoor, for stuff/facilities, for room (types), .....sounds natural and 'normal scenario' or not? 

But we should not about scenario's, right?

**AND ANSWER IS - YES**, I will use it for such purpose ACF, Pods, Toolset, ...., but for separate galleries, I must to use manually created gallery (ie with Toolset Views), as Elementor is decided for some reasons to support **ALL CUSTOM FIELDS KEYS** (slugs) except images.

Keys are for custom fields, right? And data, time, number, .... are with slugs (3rd party plugins) and keys (Elementor) support, but images are only supported with slugs, but for unknown reasons not with keys, as they supposingly are only standard content of the post and should not to be in position to be displayed in custom way (like other custom content).

It is possible that I miss something, but I can't see consistency in approach to keys (they are for slugs or not? - if they are, why some of slugs are not supported?) like way to display custom content of the post (that is why you created Dynamic, right?).

I only asked - why image custom fields are discriminated by Elementor (as all other are supported)? Elementor spent more resources to exclude support for keys only for images, than to make it same as other custom field types.

**Comment by bainternet** [comment]
> As far I understand English, you claim that "dynamic" is intentionally created by Elementor only for standard post content (see part - 'without custom coding or a 3rd party plugin'), as well that gallery exist only for standard post content (I don't think so, as there is only one image - featured, plus images inserted via editor - what is kind of custom content).... it will look complicated. Let's go briefly, as I don't want to argue about usage scenarious.

This is not what I'm trying to explain to you (and in no way am I "claiming" anything).

> I only asked - why image custom fields are discriminated by Elementor (as all other are supported)? 

Dynamic was designed in away for it to work for both strings (including WordPress native custom fields  ) and arrays ( which is what the gallery, image or url controls in elementor accept) but for array to work there should be a custom formating in the background, which we can't possibly guess in which structure you store your gallery data in a custom field so its simply not avialable.

> Elementor spent more resources to exclude support for keys only for images, than to make it same as other custom field types.

🧐 that is simply not true!!! where are you getting this data from??

In your reply you fail to explain how would a custom field would help you or how would it even work.
The post image attachment gallery tag dosn't even work with custom fields so a key would be useless.

> It is possible that I miss something, but I can't see consistency in approach to keys (they are for slugs or not? - if they are, why some of slugs are not supported?) like way to display custom content of the post (that is why you created Dynamic, right?).

Again this dynamic tag dosn't pull data from custom fields so no key is needed. please have a look at its code maybe it will help you understand better.

> AND ANSWER IS - YES, I will use it for such purpose ACF, Pods, Toolset... 

Greate we already have support for ACF gallery field and in Elementor Pro v2.1.0 we are adding support for Toolset repeatable image field and pods multiple image field.

thanks.
