### ISSUE TITLE
[Feature request] New Post Loop Item template

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4505]
Hello!
We have Posts widget but there are still have troubles with read more tag and of course, customization.
I mean that I want to place some custom content into the posts loop item like custom field, button etc.

That's would great to make new template type for Posts Loop Item that will replace default theme loop items and can be queried with Posts widget.

How do you like this? Place 👍🏻 if you do!

**Comment by danielhoegel** [comment]
@parfilov Until it is implemented in Elementor, ýou can try this awesome Plugin: https://wordpress.org/plugins/ele-custom-skin/

**Comment by parfilov** [comment]
@danielhoegel thanks! Sounds good but I think that it should be a native feature. Don't like side addons, there are a lot of troubles with them.

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
