### ISSUE TITLE
Reset Elementor's preset to custom preset.

### ISSUE THREAD

**Issue by mad99** [pojome/elementor#4509]
Hi,
we are looking for a simple solution to reset Elementor's presets at one point to our agency- or client-/project-Presets.
We have searched in GitHub, FAQ's, Documentation and asked Elementor's support: 
**Ricardo from Elementor told me to open this feature request.**

So:
## Prerequisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In the current version it is only possible to correct basic settings set by Elementor with difficulty using the VisualEditor.
For responsive elements it's troublesome and annoying to do this three times.

![edit-in-visualeditor](https://user-images.githubusercontent.com/6169308/40367877-b5ca7006-5dda-11e8-9ee1-9f22ad0d05bd.png)

Or we use Elementor's long CSS selectors and overwrite them with our own statements. However, this makes the CSS files unnecessarily long and changing them is very time-consuming and error-prone. Like `.elementor-column-gap-default>.elementor-row>.elementor-column>.elementor-element-populated { padding: 10px; }`
Therefore, we are currently moving to a more efficient but no less error-prone one:
We add a add_action('wp_enque_scripts', 'design-style', 999). So we can overwrite Elementor presets with ease, because our css is read after elementor's styles. 
But this workaround is quite tricky, because it is not side-effect-free.
Sometimes
- a «padding-right: 0 !important;» also overwrite some not needed parts.
- the elementor's editor is influenced from.

**Describe the solution you'd like**
I guess there would be different approaches for. But the easiest way would be (IMHO) to have the ability to exclude elementor's preset in the default/automatic way with one click in the settings (for advanced users - or something similar).
On other place like Github or Elementor docs (or in the settings as an copy-paste solution) it would be great to have all elementor's presets collected in css (best also in sass) as a «default-preset template» for custom css/sass. 
- This could be added in the own css/sass. 
- Change/overwrite the particular part with own/custom css/sass directly (hardcoded) 
- or better with some prebuild mixins (or own of them) to set the particular preset within variables to output custom stylesheets.

**Describe alternatives you've considered**
Maybe a hook in wordpress to set to false and also a hook to input own/custom css.

I hope, and I am almost certain, that this feature improve elementor for agencies daly work a lot!
Kind reagards
Martin

**Comment by bainternet** [comment]
@mad99 

I merged this issue with  #965, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
