### ISSUE TITLE
Need API soon

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#451]
Hi guys, I have been following the development of this awesome plugin. I am really grateful that you guys have created and keep developing this FREE plugin. This is certainly the best page builder ever!

I am just curious, when will the API would come out? Currently your control and widget options let us customize the styles and it works well. But as theme authors we need to hack onto something more, like:
- adding custom icons into the list
- adding new option to the widget options panel
- filter the widget HTML output
- adding new widgets using defined controls and elements

Is there any estimation release date on this?

**Comment by FrankM1** [comment]
Another addition to the api should be a way to trigger javascript once a custom widget is added to a page. For example, this will be used to a slider or video player once it is added to the page.

**Comment by WPDevHQ** [comment]
@FrankM1 the widgets init for the specific widget class should already be taking care of the required css/js files. Or am I missing the point?

**Comment by FrankM1** [comment]
@WPDevHQ I'm referring to the time when a widget is added to a page using elementor. During the preview phase. Before you save the page and refresh. The default elements re-initialize javascript by default since the behaviour is built in. I haven't yet found a way to do this with custom widgets.

**Comment by yehudah** [comment]
Hi @daviedR ,

We working very hard on the API and I Hope in the weeks it will be released.

**Comment by daviedR** [comment]
@yehudah thanks for the heads up! Glad to know it's coming soon.

**Comment by FrankM1** [comment]
@yehudah Thank you. We are eagerly waiting the release.

**Comment by devGrzegorz** [comment]
@yehudah any news on the API? Is the release a matter of days, weeks or months? 
I'd love to use Elementor in my next project, but I'll need some custom elements for it. So I'd be grateful for any info 👍

**Comment by daviedR** [comment]
Totally agree with @devGrzegorz, I would use Elementor on my next project and really looking forward to see the API coming. I don't want to put pressure on you guys. But the API is definitely something all of us have been waiting for :)

**Comment by pingram3541** [comment]
👍

**Comment by teolaz1990** [comment]
The same as @devGrzegorz , @daviedR ... guys you've done a quite good job, but please as any existent decent open source plugin provide the documentation to extend it.

**Comment by devGrzegorz** [comment]
Sorry guys, but I'd already changed the engine to BeaverBuilder, and bought the agency license for it. And I think I'm not the only one. No support and no information from you guys cost you money. Please be aware of it. 

Regards

**Comment by nicolas92** [comment]
Any news on this?
Thank you for your great work guys :)

**Comment by iamntz** [comment]
Bumpy bump.

I'm trying to do some custom stuff and I need some documentation (both php and JS). Any news on that API? Thanks!

**Comment by Grafikart** [comment]
I'm also interested by this feature and I have implemented custom widget editing this class https://github.com/pojome/elementor/blob/develop/includes/managers/widgets.php

Is there a roadmap on the developer API, maybe we could help :) 
Adding a hook here https://github.com/pojome/elementor/blob/develop/includes/managers/widgets.php#L58 with the Widgets_Manager would allow us to easily add Widget

```
do_action( 'elementor/widgets/widgets_after_register', $this )

// In our code
add_action('elementor/widgets/widgets_after_register', function ($manager) {
    $manager->register_widget_type(new Custom/Widget/Extending/Base());
    $manager->register_widget_type(new Another/Custom/Widget/Extending/Base());
}, 10, 1);
```

Can do a PR if needed

**Comment by Grafikart** [comment]
After diving a bit deeper I found you can already extend Elementor using the add_action. You can get the widget manager doing : Elementor\ Plugin::instance()->widgets_manager

```php
add_action('elementor/widgets/widgets_after_register', function ($manager) {
    $manager = Elementor\ Plugin::instance()->widgets_manager;
    $manager->register_widget_type(new Custom/Widget/Extending/Base());
    $manager->register_widget_type(new Another/Custom/Widget/Extending/Base());
}, 10, 0);
```

**Comment by pingram3541** [comment]
I'm also very interested in being able to access the css compiler print_css.  Unfortunately the class function is private =(

**Comment by WPDevHQ** [comment]
`<?php`
`namespace Elementor;`
`class Widget_New_Widget extends Widget_Base {`
`// Create your wudget stuff here`
`}`
`Plugin::instance()->widgets_manager->register_widget_type( new Widget_New_Widget() ); // Extend Widget_Base with your new widget`

**Comment by joshmarom** [comment]
Still work in progress, but you are welcome to check out the dev docs and API:
https://github.com/pojome/elementor/tree/develop/docs

You are also welcome to send your corrections suggestions contributions on that matter.
