### ISSUE TITLE
Widgets Space option not working

### ISSUE THREAD

**Issue by Pirenko** [pojome/elementor#4510]
Hi,
Title says it all. Option located on the Global Settings does not seem to be working. I tested with multiple themes... Am I doing something wrong or is there a bug indeed?
Thanks!

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
