### ISSUE TITLE
Feature request - seperator line but with text

### ISSUE THREAD

**Issue by polartim** [pojome/elementor#4514]
![line-break](https://user-images.githubusercontent.com/8557202/40386646-9b0228b0-5e0a-11e8-8682-a7c3323bf2ab.png)

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I'm looking for a simple line-seperator feature. The line with thickness and seperator editing is already there. However I cannot put some text inside. I would really like this feature.

**Comment by bainternet** [comment]
@polartim 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, you can use 3 column with

| col-1 | col-2 | col-3 |
| ----- |:-----:|  -----:|
|Devider widget| Heading Widget| Devider Widget|

Thanks for the feedback.
