### ISSUE TITLE
[Feature Request] Create a style for a widget and then distribute the style to other widgets

### ISSUE THREAD

**Issue by dotpdesign** [pojome/elementor#4515]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

When you want to edit just the text in a specific global widget on a page, you have to unlink it. If you want to then go back and make style changes to the global widget, those style changes will not apply to the global widget that you unlinked.    

**Describe the solution you'd like**
We need to have the ability to change text in a global widget (Unlink) and yet still have the widget take on any style changes you may make to that global widget. In other words, set up global widget style templates that you can apply globally to other widgets. Then the style of the widget could be selected as a global template each time you create the widget and editing the text wouldn't impact the style. Conversely, you can edit the global widget specific style template and all of those widgets with that style will change even though the text inside them is unique.

**Describe alternatives you've considered**
Create classes in CSS serves as the global widget "template" style and then style them with custom CSS. Old school way of styling global widgets.

**Comment by bainternet** [comment]
@dotpdesign 

We do have plans for something like that.

thanks for the suggestion.

**Comment by klarakalko** [comment]
+1

**Comment by Hanleymade** [comment]
I hope this option comes soon.

**Comment by themedleb** [comment]
+1

**Comment by bainternet** [comment]
I merged this issue with  #1324, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
