### ISSUE TITLE
Define what to show when you click on the "Add Template" button

### ISSUE THREAD

**Issue by franzarmas** [pojome/elementor#4516]
By default when you are editing with Elementor and you click on the "Add Template" button .. by default the first thing that shows is the "Pages" section.

I would like that when you click on "Add Template" the first thing that shows is the "blocks" section since it is what is most used.

Maybe you could add an option in the wp admin to define what you want to be shown by default when you click on the "Add Template" button.

This would be very useful and increase my productivity.
I leave capture.

![screen recording 2018-05-22 at 06 03 24 pm](https://user-images.githubusercontent.com/36080351/40394872-038c13e8-5deb-11e8-9c40-5842a45c8faf.gif)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


but if you click on add template >> blocks >> do whatever you want.... then go back to add template, it will open blocks. it saves the last view that was open.


Thanks for the feedback.

**Comment by franzarmas** [comment]
@bainternet  Where is the last view saved? .. in the Database ?? .. in a cookie ?? in the variable $ _SESSION ?? ..

maybe I can intervene in it by code ...

Please, could you tell me where it is stored, I would really appreciate it !!!
