### ISSUE TITLE
Feature suggestions - element pinning and element breadcrumbs

### ISSUE THREAD

**Issue by gahawkey** [pojome/elementor#4517]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
My first feature suggestion is to allow pinning of elements/modules to the top of the elementor panel. Thrive Architect does this, allowing users to 'favorite' the elements they use most frequently. This means less scrolling or searching when building out a page :)

My second feature suggestion is adding a breadcrumb (also as done in Thrive Architect) which simplifies understanding the nesting structure, and also makes it much easier to select elements if negative margins or z-indexing hides the controls on hover.

Thanks for an awesome product (dev license holder and loving it) and keep up the top work team!

Cheers from Australia.

## Steps to reproduce

No bugs, just two feature suggestions :)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
N/A
```
</details>

**Comment by bainternet** [comment]
@gahawkey 

Thanks for the feedback, as for your suggestions, they have both already been requested more then once, in one way or another: #3805, #1165

thanks again.
