### ISSUE TITLE
[Feature Request] HTML Email Optin Form availability

### ISSUE THREAD

**Issue by mduphiney** [pojome/elementor#4519]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe...**
Suggesting that Elementor include a feature just like Thrive Architect has built in to it's plugin....HTML Autoresponder intergation.

**Describe the solution you'd like**
Please know that I know that Elementor already has a great Email Form Contact Us form and I love it!, but my request sways more towards the marketer that would like to integrate more option to built email optin lists (specifically HTML Forms).

I feel that if people that use Elementor like me could have an HTML Email
Form Integration link in this video that I am again attaching, it could
help people like me that like me that use Thrive Theme, that would rather
use the Elementor PRO plugin, the ability to build Email lists using HTML
code provided by autoresponder services.

I am hoping that this video will make it to the department that can view
this and view it and have Elementor be able to create EMAIL SUBSCRITION
FORMS using HTML code just like the Thrive Theme plugin does. Below is the
video that I created showing what I mean.

Please note that I made this video to explain my question to the Elementor Customer Support group, but they recommended that I forward the video and my request to this GitHub group.

Test Page 1 | Thrive Architect Watch Video
https://www.useloom.com/share/314772221d7641c08f32df871bcd403b

I feel that if Elementor had this HTML Form option, it would allow online marketers that want to build an email list that doesnt use one of the top autoresponders (aweber, getresponse, mailchimp, etc) thus giving your users more options.  

It would also be great if we could API sendgrid and others like it.

**Additional context**
https://www.useloom.com/share/314772221d7641c08f32df871bcd403b

I hope my feature suggestion description made sense and that the video was helpful.

I would rather not have to keep the Thrive Architect plugin installed on my WP site so when I have to create an email optin form I use Thrive and to build my site I use Elementor.

Thank you in advance for your time and seriously consider integrating my feature request.

Kind Regards,
Mark D

**Comment by bainternet** [comment]
@mduphiney 

You can use the HTML widget to insert your HTML forms and as for other autoresponders like sendgird refer to this guides: https://github.com/pojome/elementor/issues/2397#issuecomment-357495616


other than that I don't see built-in autoresponder any time soon.


thanks for the suggestion.

**Comment by mduphiney** [comment]
@bainternet 

Yes you can, but there is no Formatting functionality like the option in Thrive Architect.  The purpose is to have your forms look good...like they're part of the site itself.  When you just copy & paste the form code into the current html widget, you get this awful looking, bland form that looks like a 5th grader created it and just plopped it into the website.

Might I ask, what is the reasoning that you wouldn't want to include my suggestion into the BEST page builder on the planet?

Thank you again for your time :-)

**Comment by bainternet** [comment]
We already have a form widget that lets you build and style the form, you can either use that or like you said, use an HTML widget to insert HTML. I see no need/reason to add an HTML generator wor the form widget, simply because the two options above with the provided action and filter hooks cover about 99% of the use cases.

thanks again.
