### ISSUE TITLE
Media Carousel Cube Chrome bug

### ISSUE THREAD

**Issue by odedta** [pojome/elementor#4522]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If you use the Media Carousel Cube with image and lightbox on Chrome it doesn't work for all items, it works well in Mozilla.

All latest versions of WP, Elementor Pro, Browsers.

## Steps to reproduce

Create a Media Carousel Cube style and make the image link to media file, try to click on each image in the front end, some of the lightboxes don't open, usually only the first one opens.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/aLDRHNQc
```
</details>

**Comment by bainternet** [comment]
@odedta 

thanks for reporting, we cant replicate the issue, Please contact our support at support @elementor.com for guidance in resolving this issue.
