### ISSUE TITLE
Second toggle content does not start from top page

### ISSUE THREAD

**Issue by HikmetSener** [pojome/elementor#4523]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by HikmetSener** [comment]
When using multiple toggle windows and if you have long content within the toggles... When you read toggle 1 content and would scroll down, after switching to toggle 2 the content does not start from top and you have to scroll to the top op page.
