### ISSUE TITLE
Support Child Categories for Posts Widget

### ISSUE THREAD

**Issue by razvanwaterford** [pojome/elementor#4527]
Add ability to select a Child Category in the Query area of the Posts Widget. Currently only Parent Categories work, which is insane.

https://codex.wordpress.org/Function_Reference/get_taxonomies
https://developer.wordpress.org/reference/functions/get_terms/

**Comment by bainternet** [comment]
@razvanwaterford 

Thanks for reporting, its obviously a bug which only happens in some conditions where the terms are empty. should be fixed in next version.

Next time please follow the guidelines and template to open an issue.

thanks again.

**Comment by arielk** [comment]
Fixed for E-Pro v2.0.8

Thanks!
