### ISSUE TITLE
Main Post

### ISSUE THREAD

**Issue by BorjaAV** [pojome/elementor#4539]
I want to give you a suggestion for your next release. In the post widget I never find an option to highlight the last post (doin a lit bit bigger than the rest). 

So, I thin that this option will give you an extra very usefull for bloggers/customers like me.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by BorjaAV** [comment]
Sorry but i dont understand the info that i have to give your.

I just suggest an extra option in the Elementor widget post. i use this widget in my blog (https://borjaarandavaquero.com/blog/) and I want to have an option to show which off my posts is the last. You can show an example here (https://blogger3cero.com/) The last post its bigger than the rest.

 I use Elementor Pro 2.0.9 and wordpress 4.9.6

Sorry for my english, its so bad. If you need more information just reply this post. Thanks!
