### ISSUE TITLE
Feature request: Interactive Sections loading via Ajax

### ISSUE THREAD

**Issue by hello2021** [pojome/elementor#4540]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Description
Sections on an Elementor page are currently static. I can imagine a future release of Elementor where Sections change within a Page and load via Ajax depending on user activity. It could allow a new level of interactivity on a Page.

Specifically, I would like to save re-usable Sections and have them load onto a page as needed, depending on user activity.

For example, if a user interacts with an element in a Section, I would like to automatically load new content via Ajax into that same Section. Using pre-saved Sections, it could be possible to choose which Section should load.

Rather than auto-scrolling to a different location on the page or sending the user to a new page, automatically load a new Section via Ajax into the current Section.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by bentalgad** [comment]
+1
