### ISSUE TITLE
Mobile Menu Slide & Full Page

### ISSUE THREAD

**Issue by J33139** [pojome/elementor#4541]
It would be awesome to have the option to change the mobile menu to full page mode or slide to the side instead of dropdown only. I hope this will be added soon:)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
