### ISSUE TITLE
Scrolling Effect - 'Sticky enabled' causes page to scroll on it's own.

### ISSUE THREAD

**Issue by teke-colin** [pojome/elementor#4542]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
**But I have seen multiple users complain about the same issue in the Facebook group 'Elementor Community' - no fixes reported in the group yet.**
- [X] The issue still exists against the latest stable version of Elementor.

## Description

**When 'Scrolling Effect - Sticky' is enabled for a header section, the page begins to scroll on it's own after scrolling about 25% of the way down the page and there is no way to stop it once it has started. Disabling the 'Scrolling Effect - Sticky' option removes this behavior.**

## Steps to reproduce

Enable 'Scrolling Effect - Sticky' on a header section. <-- causes the issue.
Disable 'Scrolling Effect - Sticky' on header section. <-- removes the issue.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
**Yes with Pro.**
- [X] This bug happens with a default WordPress theme active.
**Yes with 'Twenty Seventeen'.**
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: 5.5.5
	PHP Version: 7.1.17-1+0~20180505045956.17+jessie~1.gbpde69c6
	PHP Max Input Vars: 2500
	PHP Max Post Size: 50M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: https://gtail.ca
	Home URL: https://gtail.ca
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Teke Child
	Version: 
	Author: Teke Support
	Child Theme: Yes
	Parent Theme Name: Teke
	Parent Theme Version: 1.0.0
	Parent Theme Author: Underscores.me

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 4.4.12
		Author: Elliot Condon

	All In One SEO Pack Pro
		Version: 2.6
		Author: Michael Torbert

	Elastic Email Sender
		Version: 1.1.0
		Author: Elastic Email

	Elementor
		Version: 2.0.12
		Author: Elementor.com

	Elementor Extras
		Version: 1.9.7
		Author: Namogo

	Elementor Pro
		Version: 2.0.7
		Author: Elementor.com

	iThemes Security Pro
		Version: 5.2.0
		Author: iThemes

	ManageWP - Worker
		Version: 4.5.0
		Author: ManageWP

	Smush Pro
		Version: 2.7.9
		Author: WPMU DEV

	WPMU DEV Dashboard
		Version: 4.5.2
		Author: WPMU DEV


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP


== Debug ==
	Errors: 
		TypeError: Cannot read property 'errors' of undefined
			at https://gtail.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.12 - 2:132494
			2018-05-23 15:17 +00:00
			x 10 times

```
</details>

**Comment by bainternet** [comment]
We cant replicate this issue, 
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by teke-colin** [comment]
You know that's bullshit that you just close a reported bug without really
looking into it. There are many people experiencing this issue, not just me.
Check the FB community and you will see.
Colin VallanFounder & CEO


www.wpteke.com
5348 Vegas Dr. - Suite 1686 - Las Vegas - Nevada - USA - 89108  





On Mon, May 28, 2018 3:53 PM, Raz Ohad notifications@github.com  wrote:
We cant replicate this issue,
Please contact our support at support @elementor.com for guidance in resolving
this issue.

**Comment by aalani95** [comment]
i have that issue as well after enabling the sticky effect, will contact support, thanks!

**Comment by kellymears** [comment]
I'll need to contact support as well. It's driving me insane. See also #4421

**Comment by kellymears** [comment]
In my case this seemed to be related to an element within my sticky nav that was hidden on mobile device sizes. Steps to replicate this behavior and a potential end-user solution as follows:

***Replicate:***
- Decrease the height of a sticky navigation element.
- Increase vertical padding of interior elements.
- Set an interior element to be hidden on mobile, tablet, or desktop (in my case I was hiding a button on mobile). 
- Set min height of section to default or a value less than the height of the element.
- Scroll past an element that does not have a min height set on _itself_. 
- Screen will begin scrolling. Sometimes it scrolled down for me but mainly it scrolled up. I do not know why but It would stop on an element that did have a min height property. If there is no element with min height it will scroll to the top of the page.

***Potential Solution (worked for me!)***
- Increase min height of sticky section to account for hidden element and padding set on interior elements. 

I really wanted a super skinny top bar on mobile but I can live with this as a compromise. I'm just happy it isn't scrolling any more 😂

**Comment by veryxcit** [comment]
Definitely a bug, definitely should not be closed since this and https://github.com/pojome/elementor/issues/4364 are full of users experiencing the same issue -- as I am as well.

**Comment by webinsightin** [comment]
Yes. Please reopen this bug and fix it. You can't close this like this... thousands of users are facing it.  @bainternet
