### ISSUE TITLE
[Bug] Global widgets don't update if editing from template file

### ISSUE THREAD

**Issue by avermat** [pojome/elementor#4543]
I've been using a template (my-widgets.json) to store all of my pre-styled widgets and save them as global widgets. However, if I _edit_ a global widget from within this _template_, the widget doesn't get updated on other live pages of my website.

(Editing a global widget only works when I edit a global widget from within a _page_ on my website.)

**Steps To Reproduce:**
1. Create a new template and add a widget to the template
2. Save that widget as a global widget
3. Add the new global widget to other live pages on your website
4. Go back to the template and edit the global widget and make some adjustment
5. Refresh the other live pages on your website (you will notice that the global widget has not been updated on the live pages).

**System:**
E latest, E Pro latest, Astra 1.3.2, no plugins

**Comment by patrickkoulalis** [comment]
Why was this closed?

**Comment by avermat** [comment]
Are you having the same issue? I think I closed it myself b/c I wasn't able to reproduce the error consistently. I haven't tried to replicate it recently.

**Comment by patrickkoulalis** [comment]
I thought I was but it just took forever for the changes to propagate. Even after a hard reload and cache clear.
