### ISSUE TITLE
Elementor confusing error mesages

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4546]
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

New installation wp 4.9.6 & Elementor 2.0.12
I guess PHP version is 5.2.something

Elementor plugin activated OK
With Error message at the top:
"Elementor requires PHP version 5.4+, plugin is currently NOT ACTIVE."
and no entry for Elementor in admin menu

IT SHOULD NOT GET ACTIVATED!

## Steps to reproduce

1. Install WP with PHP version < 5.4
2. Install Elementor from repository

## Environment

NA
Screenshot attached
![elementorconflict](https://user-images.githubusercontent.com/765651/40572217-b37346c6-60ae-11e8-900f-abdedd35de3a.png)

**Comment by bainternet** [comment]
Thanks for reporting.
