### ISSUE TITLE
Header Template: Call Background Image Dynamically

### ISSUE THREAD

**Issue by completeinnovation** [pojome/elementor#4547]
**Image background for header template built with Elementor Pro**
I have a header which displays across every page except the landing page. I'm working with a brand that uses imagery and video a lot and I would like to ability to call the background image dynamically if the current post/page it is on has a featured image attached.

**Could we something similar to the the image element, with the dynamic option**
See the screenshot below. The solution shows the ability to select the dynamic option > post > featured image. 

![screen-shot-2018-05-25-at-2 34 24-pm](https://user-images.githubusercontent.com/39644910/40574365-bba58e54-60d0-11e8-89d9-fd6b36d2b21e.jpg)

Great plugin btw, even better with Elementor Pro! :)

Thank you

**Comment by jornmo** [comment]
Yes! This would be totally awesome!

**Comment by bainternet** [comment]
I merged this issue with  #3971, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
