### ISSUE TITLE
[Bug] Tablet Responsive Issue

### ISSUE THREAD

**Issue by lunacroft** [pojome/elementor#455]
I know you are working in responsive adjusts, but there's an issue that makes it impossible to launch a website. So I do this request.
Currently, tablet extension 768px - 1024px is not working and behave like desktop extension. The look is weird. I think for a while you could set tablet look equal smartphone, just to you take some time to do all adjusts, because view in tablet like smartphone is not weird.

**Comment by arielk** [comment]
I think that it already fixed in v0.11.1 please check this issue #860 

Thanks!
