### ISSUE TITLE
Bugs Menu

### ISSUE THREAD

**Issue by xcullx** [pojome/elementor#4550]
<a href='https://hostingkartinok.com/show-image.php?id=b0f3e83bc60dad32b42d6e132c40e49e' title='загрузить селфи'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2018/05/b0f3e83bc60dad32b42d6e132c40e49e.jpg' alt='Yes'  /></a>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by xcullx** [comment]
You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.
