### ISSUE TITLE
Wishes to change .... Color docker

### ISSUE THREAD

**Issue by xcullx** [pojome/elementor#4551]
I think it will be much better.

<a href='https://hostingkartinok.com/show-image.php?id=8e5cd4e1e89d324b4b9f9d275bf30d2c' title='загрузить фото'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2018/05/8e5cd4e1e89d324b4b9f9d275bf30d2c.png' alt='Yes'  /></a>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by xcullx** [comment]
You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.

You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.

You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.

You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.

You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.

You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.

You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.
