### ISSUE TITLE
New design panel

### ISSUE THREAD

**Issue by xcullx** [pojome/elementor#4552]
I think it will be much better.
p.s. Tired of constantly opening the menu  )))

<a href='https://hostingkartinok.com/show-image.php?id=fa1d88726d5be41082f748569f92e80e' title='загрузить изображение'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2018/05/fa1d88726d5be41082f748569f92e80e.png' alt='design.png'  /></a>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by xcullx** [comment]
You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.
