### ISSUE TITLE
indents

### ISSUE THREAD

**Issue by xcullx** [pojome/elementor#4553]
Hi.
See the picture. Please correct. Thank you.

<a href='https://hostingkartinok.com/show-image.php?id=c32ef0575c93bfd5afa848e23fef5694' title='хостинг изображений'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2018/05/c32ef0575c93bfd5afa848e23fef5694.png' alt='Yes'  /></a>

**Comment by bainternet** [comment]
Duplicate of #452

**Comment by xcullx** [comment]
You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.
