### ISSUE TITLE
Nav Menu - more settings

### ISSUE THREAD

**Issue by xcullx** [pojome/elementor#4554]
Make more settings for visualizing the MENU.

<a href='https://hostingkartinok.com/show-image.php?id=0447186cf4fc6021a29e0bf795702bbf' title='разместить картинку'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2018/05/0447186cf4fc6021a29e0bf795702bbf.png' alt='Yes'  /></a>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by xcullx** [comment]
You idiots
I was trying to help. Make the product better.
And you have closed my application.
Go to hell.
