### ISSUE TITLE
[Feature Request]  Make the input type="file" stylized by settings

### ISSUE THREAD

**Issue by Alecto** [pojome/elementor#4555]
Now the form element input type="file" is not stylized by the settings and looks like this

![image](https://user-images.githubusercontent.com/8464662/40579011-598b1e30-6127-11e8-97d8-12a26224e083.png)

![image](https://user-images.githubusercontent.com/8464662/40579026-a3fe5b1c-6127-11e8-924b-f556631d293d.png)

I ask you to make the stylization of this field according to the settings, as well as other fields.

PS: I made a request to help solve the problem, but you could not help me and advised me to create this request.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
