### ISSUE TITLE
i have some Questions

### ISSUE THREAD

**Issue by lodesign-st** [pojome/elementor#456]
hi 

your plugin is hot and very good for me .

1. can i add it to empty templats and manage the hader footer and all by your plugin ?

2.if i build website not by wordpress , in adobe muse , thay have someting that call musexpress 
that convert muse to wordpress , but i dont now how to conect your plugin .

can you help me pls ?

thanks
shlomi

**Comment by yehudah** [comment]
1. No, you can only mange content and you template must have the line <code>the_content</code> in it.
2. After converting to wordpress just install it from the plugins menu.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
