### ISSUE TITLE
Customize Lightbox fade-back duration on close

### ISSUE THREAD

**Issue by Atair1** [pojome/elementor#4560]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
While i can replace the lightbox with other plugins, the closing of the lightbox fades the page back into view, and it takes very long from full black. Other effects already have a animation speed, and for portfolio pages that rely heavily on the lightbox it is a important little feature.

**Describe the solution you'd like**
simple dropdown or even better a seconds input field.

**Describe alternatives you've considered**
I tried the 'Responsive LightBox & Gallery' plugin, that takes care of the lightbox, but cant change the fade back effect from elementor.

**Additional context**
While i am super-new to webdesign (2 days now), but i code half my life - so if there is anything i can do to get this temporary working please point me in the right direction.

**Comment by arielk** [comment]
I merged this issue with another issue #2502 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
