### ISSUE TITLE
Page not loading due "Cannot read property 'get' of undefined"

### ISSUE THREAD

**Issue by Alexandero89** [pojome/elementor#4568]
Hello,
Right now i'm not able to edit one of my Pages via Elementor.
The Elementor Loading-screen just keeps showing.
CPU and RAM are not used while page is loading, so it is just crashing somewhere and not doing hard work in the background.

My Setup:
Wordpress 4.9.6
Elementor 2.0.12
Elementor Pro 2.0.7

When i debug the site while its loading i can see that he has an Exception at this part:
`            initSettings: function() {
                var e = this.get("templateID")
                  , t = elementorPro.modules.globalWidget.getGlobalModels(e);
                elementorFrontend.config.elements.data[this.cid] = t.get("settings"),
                elementorFrontend.config.elements.editSettings[this.cid] = t.get("editSettings")
            },`

t is undefined because the method 'getGlobalModels(e)' does not exist in the globalWidget Array. 

Would appreciate your help
Thanks in regard

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
