### ISSUE TITLE
Nav Menu Toggle - Set Custom Breakpoint

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4569]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Often I would like to use the mobile menu toggle button of the menu at much higher breakpoints, such as 1239px or even just make it use of it ALL the time

**Describe the solution you'd like**
The ability to set a breakpoint value in px w/ default being 1023px.  Rather than being a drop down with only two fixed choices.

**Describe alternatives you've considered**
Custom css for now but it is a bit of work.

**Additional context**
I believe this is a good compromise where the advanced nature is attained but by providing the default value keeps it easy at the novice level and it is pretty self explanatory, a simple field type change in which javascript and css respond or are generated from, returning a single value the code effort is minimal.

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
we tied it with #78 which is in the working now.

thanks.

**Comment by PwrSrg** [comment]
How is this STILL not a thing?  I would also like to change the default "Boxed" width.

**Comment by fippy** [comment]
what is the custom css you use to fix this?

**Comment by fippy** [comment]
At the moment the options are Mobile (<768px), Tablet (<1025px) & None. 

Is there any reason why you coudn't offer "Custom" as an option and then enable an input.

+1 to wanting this done
