### ISSUE TITLE
Mobile Responsive Issue

### ISSUE THREAD

**Issue by aryasharma36** [pojome/elementor#457]
Hi Guys,

So I din't use the twenty sixteen child theme as it was not working with a full width layout. I contacted the elementor team on facebook and they suggested I use The Generate Press theme, which is a fabulous theme and worked for my full width design which I wanted to create.

All was well, until I noticed something when switching to mobile view, I also check the site on an Ipad and on different browsers and noticed a white vertical line on the right hand side of the screen.(Screen shot attached
![elementor mobile screenshot](https://cloud.githubusercontent.com/assets/20917837/18027892/17c45bc8-6c8d-11e6-8213-0b42cf492d06.png)
) 

Now I wouldn't be concerned about it but on a mobile screen it doesn't look good and is completely out of proportion in a mobile browser called "Dolphin Browser" on android. 

Now thats a real bummer, but I a big fan of elementor and I don't want to change it. Please send me a fix as soon as possible.

**Comment by yehudah** [comment]
In chrome can you right click this area and from the menu select inspect,
can you screenshot or paste the html ?

**Comment by aryasharma36** [comment]
@yehudah here's the design I made for the website www.yontent.in

**Comment by yehudah** [comment]
test it with emulator

![image](https://cloud.githubusercontent.com/assets/1655373/18044028/3168122a-6dd4-11e6-9866-9c828c2f9eda.png)

**Comment by aryasharma36** [comment]
Looks the same in emulator, have tried it on multiple websites, emulator and phones as well, both android and iphones, the problem is still there @yehudah

**Comment by arielk** [comment]
Fixed #522
