### ISSUE TITLE
Template for archive page post details view

### ISSUE THREAD

**Issue by BenBroide** [pojome/elementor#4570]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There isn't a simple way to add Elementor Widgets with post details (ex: custom fields values) in archive page 

**Describe the solution you'd like**
Add a template "archive post" which will look and act like the single page template. This template would be used in the archive page post display on each post in loop.
The preview will show the changes live on a archive page with last n posts depending on set of items per page.

**Describe alternatives you've considered**

**Additional context**
This request is similar to this request https://github.com/pojome/elementor/issues/4440
This request is about the built-in WordPress archive page, not the posts widget.

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
