### ISSUE TITLE
drop down filters

### ISSUE THREAD

**Issue by brother1** [pojome/elementor#4574]
Can we please, please introduce some page filters? Really want to make a press page for cloacaprojects.com and be able to filter by tags (i.e. date, artist name, year, other criteria). If this is not in a forseeable update, would you send me a way to do this? Drop down filters would be a major plus to filter the post data taxonomy by tags, vs having hacky plugins and custom post types. 

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brother1** [comment]
This would also be super valuable to other sites that have any wealth of content... Probably a big feature bonus. Predictive search would also be awesome in terms of tags on site.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
