### ISSUE TITLE
Free Wordpress Themes

### ISSUE THREAD

**Issue by aryasharma36** [pojome/elementor#458]
Hi Team Elementor,

This was a quick question, hoping you could answer, can you suggest any free full width themes apart from Your Twenty Sixteen Child theme and generate press which works perfectly with elementor.

Try many "full" width themes but apparently none work with elementor but some of them work with site origin and others.

**Comment by WPDevHQ** [comment]
@aryasharma36 - Not a theme as such but I'm working on a plugin that will add the fullwidth template to any theme and include the required css. There will be two templates available, a fullwidth with header/footer and a full without the header/footer.

Do you have a specific theme in mind? I'm going to attempt to support as many themes as possible.

**Comment by yehudah** [comment]
We are working on permanent solution to enable full width.

**Comment by luizeof** [comment]
@aryasharma36 we make an naked theme fully compatible with Elementor https://github.com/orangeweb/elementor-naked-wp-theme

**Comment by WPDevHQ** [comment]
@yehudah - that would be totally awesome :)

@aryasharma36 and anyone else interested here's a plugin I've put together that hopefully addresses the issue (temporilly) for some of the popular themes on WordPress.org https://github.com/WPDevHQ/ElemenTemplater

**Comment by arielk** [comment]
@WPDevHQ Wow!! It looks very cool add-on for Elementor

**Comment by aryasharma36** [comment]
@WPDevHQ I will surely check it out , Ideally I was having a look at the popular themes in the wordpress popular themes section so can't name a specific theme, if it does what you say, it will be fabulous!

@yehudah will look forward to it, hope it will be free too :smiley: 

@luizeof checking it out!

Thanks for the replies

**Comment by aryasharma36** [comment]
@WPDevHQ can you update your plugin to work the Dispatch theme free version, I am planning to set up my website on it. Please let me know as soon as the plugin is updated.
