### ISSUE TITLE
Option to Change colour of Title Bar text or hide per page/post

### ISSUE THREAD

**Issue by aahkendall** [pojome/elementor#4580]
Given the ability exists to set a custom background for the titlebar of each page/post (great feature), it makes sense also to allow the text colour to be changed or hidden completely since different images require different colours and some are too complex to allow any text.

With the customizer it's obviously possible to change the colour, but for ALL pages and posts/post types and it is also possible to hide, using custom CSS, again for ALL.

Logically there should be an **option in the custom background feature within _each page's settings_ to set the colour and/or hide the text**.

It would also be nice to have an option to hide the border without needing custom CSS, as on smaller screens it often breaks/looks terrible, especially for longer titles (though on mobile, anything longer than a single (shortish) word breaks it too. I realise that's two requests but actually it was already two, so I thought I'd squeeze this in as a third since it's relevant, rather than create three separate yet related feature requests.

Thanks!
Arthur

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
