### ISSUE TITLE
Feature Request: Shortcode Mapper similar to WP Bakery.

### ISSUE THREAD

**Issue by tannerchung** [pojome/elementor#4581]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The Shortcode Widget for Elementor is a good hacky solution to add shortcodes, but it doesn't provide native Elementor interfacing to the shortcode. It'd be awesome to have a more integrated solution so that pretty much all plugins work with Elementor.

**Describe the solution you'd like**

WPBakery has this really awesome solution to create custom widgets based on the shortcodes of other plugins: https://kb.wpbakery.com/docs/learning-more/shortcode-mapper/. It maps attributes to the WPBakery interface so you can change properties with their GUI

**Describe alternatives you've considered**

I've tried the Shortcode Widget and the Template Widget, but this new method would reduce the amount of friction and insulation from the Elementor ecosystem.

**Additional context**

**Comment by bainternet** [comment]
@tannerchung 

That is a nice Idea but we do find that most shortcodes that use custom CSS and JavaScript don't work smoothly in the editor unless some Elementor compatibility tweaking is done.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the suggestion.
