### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by paolo-fasola** [pojome/elementor#4586]
I'd like to ask you for some updates to column management.
Will it be possible to set columns like fluid, rest and quarter parameters?
I find it a little hard to set a well-balanced width now and I'd wonder to know if an update to that feature is planned to be done.
Another improvement I'd like to have is the "columns in columns", I'd like to include the column widget in other columns like having nested div's with flexbox.
Thank you for your support.
Paolo

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
