### ISSUE TITLE
Media carousel: Let me to decide show player controls or not

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4587]
In Media Carousel widget we can place YouTube or Vimeo links but we have no opportynity to choose some video options as we can do in Video widget. In particular, I want to turn player controls on and disable advanced statistics.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.

thanks again.

**Comment by parfilov** [comment]
@bainternet users may want to know how many time of video is left and the second reason is more users privacy.

Shoot a dislike for better guidelines description first. You closed some of my usefull issues extrajudicially and my motivation to help is melting away. I have ~6000 subscribers that love Elementor and some ideas comes from them too. We all want to make Elementor better. Please, help us to help you.

**Comment by bainternet** [comment]
@parfilov 

We love that you post your requests, I'm just saying there is a correct way to do that.
please see these examples:
#4518
#4515
#4484
#4489

All are using and following the template with a clear description, some with examples and images which we can work with. We made the template just for that (helping you help us).

please feel free to open as many requests as you want, some will get shut down (we can't implement every single request) and some will get implemented, but first let's make sure we can understand them clearly, and to do that is to follow the template.

thanks again.

**Comment by typometre** [comment]
**What problem is your feature request going to solve? Please describe.**
The media carousel take decision which I would change on how to embed a youtube video. Specially it hides control by default whereas it is sometimes useful or needed.

**Describe the solution you'd like**
Which there is options to customize settings for the embedded player like choosing if I prefer controls as controls=0, controls=1 or controls=2. 

**Describe alternatives you've considered**
Can't see an alternative other than changing the default elementor module behaviour in core files which will break at next update. In case adding more options is not your choice for bloating purpose, making youtube player parameter a possible custom attribute to the media carousel would provide users which want this feature a way to interact without changing core files and without adding any gui options to use them.

**Additional context**
Other options as provided by [youtube parameters](https://developers.google.com/youtube/player_parameters) would be great as color, autoplay, fullscreen button etc…

**Comment by danstramer** [comment]
Is there an update? No video controls are shown in the media carousel videos - progress bar, volume, time remaining etc...

**Comment by codingguru101** [comment]
I really need a solution to this issue, has anyone got any suggestion? perhaps a way to have the iframe control changed from 0 to 1 dynamically?

**Comment by asafmoraz** [comment]
I'm also looking on a solution for this.

**Comment by DeanRatzon** [comment]
+1

**Comment by mexophantes** [comment]
@bainternet Would be great to reopen this issue. Youtube videos show no controlbar in the media carousel.

**Comment by Oshika35** [comment]
I agree with mexophantes, the issue is still there.

**Comment by Chertii** [comment]
Not even the YouTube control parameter is working to fix this issue.

+1

**Comment by AscentBen** [comment]
This truly needs to be resolved

**Comment by MatthewWillHammer** [comment]
A fix to this needs to come ASAP

**Comment by joenammour** [comment]
I would just like to add that it is really important to provide these options because we should be able provide the closed captioning option. It is really necessary from an accessibility standpoint to provide that option. I can't use your widget, as much as I would like to, because I need to make the videos as accessible as possible.

**Comment by cedricDevWP** [comment]
Up, has anyone found a way around the problem?

**Comment by peterforensys** [comment]
+1

I can't believe this is still a problem.

**Comment by parfilov** [comment]
> +1
> 
> I can't believe this is still a problem.

I can no longer believe how competing builders with smaller teams and budgets release updates and fix bugs faster.

Apparently the cloud and AI are more important for capitalization and "playing the corporation" than important features for working with the builder here and now.
