### ISSUE TITLE
Segment the Header and Footer templates

### ISSUE THREAD

**Issue by jaredgeddy** [pojome/elementor#4591]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When using the library to create a footer in elementor it removes my themes header forcing me to create my header using elementor's library. This is not a desired workflow because I may be using a 3rd party plugin to create a fancy menu that is not capable in Elementor. Or I may just not want Elementor handling my header because I wan't to hook code through my header.

**Describe the solution you'd like**
When creating a footer or header template in Elementor's library and applying it sitewide segment the two so that one does not force me to use Elementor to create the other. Only apply a footer when I create a footer and only apply a header when I create a header. The logic being something to the effect of - is there a site wide header applied? Yes/No, apply header or not. Is there a site wide footer applied? Yes/No, apply footer or not.

**Describe alternatives you've considered**
Currently I cannot use the cool feature of creating my footer in Elementor because I don't intend to use Elementor for my header.

**Comment by bainternet** [comment]
@jaredgeddy 

This only happens if your theme doesn't define a location for the footer via the [Theme Location API](https://developers.elementor.com/theme-locations-api/), so Elementor can't guess the correct location of your footer or if your theme's HTML tags are balanced.

So in your case simply register and display your locations.

thanks for the feedback.
