### ISSUE TITLE
Author Archive Template not working when Author condition is set to 'All'

### ISSUE THREAD

**Issue by Ver3** [pojome/elementor#4593]
Elementor Version 2.0.14
Pro Version 2.0.9

Not working: display condition author-all 
Result: https://lagant.co/author/verdi/

Works: author set to specific author
Result: https://lagant.co/author/racollaris/

Works: same template but with display condition category-all or tag-all
Works: display condition all

Adding a specific author solves it for that author, but somehow not all authors can be added. They simply do not show up in the list.

For now, I'll leave it with the bug active, please let me know as soon as you've checked so I can set the display condition to all. Currently, there is only one archive page with only two display condition active: author-all + author-racollaris (specific author). Leaning only author-all does not help.

**Comment by Ver3** [comment]
Update, I have to set the condition to all for now, complaints came in. If you need a staging area with the problem still visible, please let me know.

**Comment by ikovalyov** [comment]
same here

**Comment by notechup** [comment]
Also have this problem. Is it somehow related to the fact that the Author needs to have posts published? But it would be great of we could select All Authors, and it would actually be All Users,
Or even better, if we can add a condition of specific user roles, including all users of that role regardless of posts.

**Comment by bainternet** [comment]
Fixed in version Elementor Pro 2.0.11.

thanks
