### ISSUE TITLE
[Feature Request] Contact form with selectable recipient

### ISSUE THREAD

**Issue by stijnvanouplines** [pojome/elementor#4594]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
If you want to build a contact form which will allow the sender to select an email recipient. Let’s say that the options are Sales (sales@mycompany.com), Technical Support (support@mycompany.com) and General (info@mycompany.com). So we add a select box and give it an id of `department` we can use the shortcode `[field id="department"]` as the send to field. By using this procedure, the email addresses are revealed and anyone can add/edit email addresses by editing the html source.

**Describe the solution you'd like**
A good options could be to list the options as `label|value` (pipe character between label and value), each option on a separate line.
```
Sales Questions|sales@mycompany.com
Technical Support|support@mycompany.com
General Questions|info@mycompany.com
```
Only the part before the pipe will be printed on the frontpage, and the part after the pipe will be used to replace the label with the value. Then the value will be used to send the mail to.

**Describe alternatives you've considered**
Adding a select box and hope not getting spammed :)

**Comment by muazzami** [comment]
Can someone explain how to use this feature for Beta 4. 

I have drop-down with label and email values but when I enter field shortcode into To field of Email it doesn't work.

Thanks in advance.

**Comment by Ben-2043** [comment]
Hi, I have the same problem. A little help please.

**Comment by kaelhoel** [comment]
I have the same problem. How does it work?

**Comment by YoramBo** [comment]
hi 

> I have the same problem. How does it work?

you have to separate the "label| value " - as mentioned above and in the "Email" you set the shortcode of the "select" field

**Comment by graf1x** [comment]
Does this [conditional recipient] function actually work now?

I contacted Elementor Support regarding this in January 2020 and got the following reply:

> I'm afraid this isn't currently possible within Elementor/Elementor Pro. Something like this will require some Custom code that falls outside of the scope of our support

**Comment by davidamarek** [comment]
+1

**Comment by davidamarek** [comment]
Works for me!

**Comment by CSALucasNascimento** [comment]
It does work!!!

Field id: 
[field id="option_x"]

On your field on the options you do as following below:
-------------------------------------------
Select |
Label 1 | email1@domain.com
Label 2 | email2@domain.com
Label 3 | email3@domain.com
-------------------------------------------

On the Email ( you use the same format as in your shortcode field advanced tab:
[field id="option_x"]

**Comment by sebas-web** [comment]
@CSALucasNascimento Hi Lucas

I´m trying on my website with Elementor Form, but doesn´t work, can you help me please

Thank you so much
 
![Captura de pantalla 2020-08-28 a las 14 34 07](https://user-images.githubusercontent.com/48029856/91561274-9a57a980-e93b-11ea-9a93-b83b8b02df72.png)
![Captura de pantalla 2020-08-28 a las 14 34 15](https://user-images.githubusercontent.com/48029856/91561277-9af04000-e93b-11ea-896d-56e84f9a380c.png)
![Captura de pantalla 2020-08-28 a las 14 34 22](https://user-images.githubusercontent.com/48029856/91561278-9b88d680-e93b-11ea-838d-dcdad075b85d.png)

**Comment by Fleshbleue** [comment]
Hi, it does work, although the email addresses appear in the html code of the page. So it is a risk of being spammed.
I've tested with email cloaking plugins, but then the form does not work anymore.
I hope we get a safer solution soon, for this must-have feature. Thanks

**Comment by claralinda** [comment]
It does work for me as well! Does anyone know how to show the label value in the text of the email sent?
The form arrives to a different office based on the school grade chosen, but each office manages more grades so he needs to knows the grade chose. The options are:
Grade1 | email1
Grade2 | email1
Grade3 | email2
Grade4 | email2
Thanks!

**Comment by jamc92** [comment]
I can't beleive how hard is to find this! This isn's even in the docs or maybe I couldn't find it. When you search for this kind of solution everything you get are addons and paid plugins to solve this.

**Comment by mizzinc** [comment]
Is there a solution on how to change the email_to setting with add_filter( 'elementor_pro/forms/record/actions_before', function( $record, $handler ) { 

} ); ?

Rather than outputting email addresses into HTML.

**Comment by Fleshbleue** [comment]
The issue should not be "closed". The emails are still revealed in the html code.
Back-office Elementor : 
![Capture d’écran 2023-02-21 091251](https://user-images.githubusercontent.com/61308829/220286224-2000c3df-9cf5-4860-ae72-07d8a2e61cba.jpg)
Front-office Html code : 
![Capture d’écran 2023-02-21 091055](https://user-images.githubusercontent.com/61308829/220285894-5acfa13c-203a-4d6c-93cc-33893d08d7f6.jpg)

**Comment by mp3por** [comment]
Hello, 

How do I use the Select LABEL and not the value in the email HTML ?

**Comment by thewebdiner** [comment]
How do I use the Select LABEL and not the value in the email HTML ?

This sort of solves one problem but creates another...

**Comment by furtive-one** [comment]
I have a form setup as detailed above and it works, but when looking in the Elementor submissions, the select field does not show the option that the user selected when the submitted the form. Is there a way to fix this?

**Comment by renzosalvador** [comment]
How do I retrieve the VALUE, not the email, on the email submitted?

**Comment by tomslominski** [comment]
For those comfortable with custom code, I've written the following to add a new settings section to the form widget to handle this without outputting emails in the page source code.

```php
/**
 * Add Conditional Recipient section to settings of Form widget.
 */
add_action( 'elementor/element/form/section_form_options/after_section_end', function( \ElementorPro\Modules\Forms\Widgets\Form $widget ): void {
	$widget->start_controls_section(
		'section_namespace_conditional_recipient',
		[
			'label' => esc_html__( 'Conditional Recipient', 'namespace' ),
		]
	);

	$widget->add_control(
		'namespace_conditional_recipient_help',
		[
			'type' => \Elementor\Controls_Manager::RAW_HTML,
			'content_classes' => 'elementor-descriptor',
			'raw' => __( 'Use this section to determine the email recipient based on submitted form data. Set the Form Field ID to the ID of one of the fields from the Form Fields section, and use the Emails setting to set the recipient emails which correspond to each value of that field.<br><br>If the options do not match, the email will be sent to the usual recipient sent in the Email section.', 'namespace' ),
		]
	);
	
	$widget->add_control(
		'namespace_conditional_recipient_form_field_id',
		[
			'label' => esc_html__( 'Form Field ID', 'namespace' ),
			'type' => \Elementor\Controls_Manager::TEXT,
			'ai' => [
				'active' => false,
			],
		]
	);

	$repeater = new \Elementor\Repeater();

	$repeater->add_control(
		'form_field_value',
		[
			'label' => esc_html__( 'Form Field Value', 'namespace' ),
			'type' => \Elementor\Controls_Manager::TEXT,
			'ai' => [
				'active' => false,
			],
		]
	);

	$repeater->add_control(
		'email_address',
		[
			'label' => esc_html__( 'Email Address', 'namespace' ),
			'type' => \Elementor\Controls_Manager::TEXT,
			'ai' => [
				'active' => false,
			],
		]
	);
	
	$widget->add_control(
		'namespace_conditional_recipient_emails',
		[
			'label' => esc_html__( 'Emails', 'namespace' ),
			'type' => \Elementor\Controls_Manager::REPEATER,
			'fields' => $repeater->get_controls(),
			'title_field' => '{{{ form_field_value }}} &rarr; {{{ email_address }}}',
		]
	);

	$widget->end_controls_section();
} );

/**
 * Filter the email recipient if Conditional Recipient settings are set.
 */
add_filter( 'elementor_pro/forms/record/actions_before', function( $record ) {
	/** @var \ElementorPro\Modules\Forms\Classes\Form_Record $record */
	$form_field_id = $record->get_form_settings( 'namespace_conditional_recipient_form_field_id' );

	if( $form_field_id ) {
		$form_field = $record->get_field( ['id' => $form_field_id] )[$form_field_id] ?? null;

		if( $form_field ) {
			$form_field_value = $form_field['value'];
			$email_settings = $record->get_form_settings( 'namespace_conditional_recipient_emails' );

			foreach( $email_settings as $setting ) {
				if( $form_field_value === $setting['form_field_value'] && $setting['email_address'] ) {
					$settings = $record->get( 'form_settings' );
					$settings['email_to'] = sanitize_email( $setting['email_address'] );
					$record->set( 'form_settings', $settings );
				}
			}
		}
	}

	return $record;
} );
```

Once added you can set the ID of the field and field value -> email pairs for determining which email address to send the email to. If the value is not found, it'll fall back to the default email address set in the usual way.

Hope somebody else finds this useful until this functionality is hopefully added into Elementor!

**Comment by gennyx93** [comment]
Hi @tomslominski can you share a screenshot on how to set on Elementor side the form fields?

Thank you in advice

**Comment by dev-remake** [comment]
@tomslominski  my man! Dziekuje Bardzo

**Comment by willi-mueller** [comment]
> Hope somebody else finds this useful until this functionality is hopefully added into Elementor!

This really works, thank you very much for sharing it here with everyone @tomslominski !

Here is how I configured it:
1. Set the select field ID to "topic". The final HTML ID from the DOM, e.g. "form-field-topic", will not work.
<img width="273" alt="Image" src="https://github.com/user-attachments/assets/3a53e977-63aa-48a2-93d5-905fd00c6202" />
2. Refer to "topic" and then copy & paste the strings from the select options:
<img width="284" alt="Image" src="https://github.com/user-attachments/assets/38165014-94b7-4d54-907a-d30328d46e79" />

**Comment by djaysan** [comment]
For those not comfortable using Php or code snippet, i made a plugin for personal use using @tomslominski snippet above (Thanks dude!) 
https://github.com/djaysan/conditional-recipient-for-elementor/

**Comment by BradFoote** [comment]
@tomslominski Trying to et your code to work instead of using plugins so I can learn more as a dev but I can't get it to go through. I copied the same format as @willi-mueller above but no matter what I do the form just gets sent to the default email set in the form widget. Am I supposed to edit something in the code to get this to work? I've got the options and the emails I want to send to created in the new setting area created from your code and I'm at a dead end.

**Comment by djaysan** [comment]
@BradFoote the cleaned up code is also available on the link provided above + there is explanation on how it works. no need to download the plugin

**Comment by BradFoote** [comment]
@djaysan You're amazing I got it working no problem after using your code. Thanks for the fast response!

**Comment by djaysan** [comment]
Thanks! All the credits go to @tomslominski 🚀
