### ISSUE TITLE
[Feature Request] Add a "Last Updated Date" in the "Post Info" widget

### ISSUE THREAD

**Issue by Elementalel** [pojome/elementor#4597]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Ability to let users know when you last updated your page, so they know whether this information is still up to date or not.

**Describe the solution you'd like**
Add a way to add "Last Updated" feature in the "Post Info" widget, where the last time (date) you updated your post would be visible if needed.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by bainternet** [comment]
@Elementalel 

Its already implemented and waiting for the release of E-Pro 2.1

**Comment by parfilov** [comment]
Whare is it now? Do you see it?

**Comment by sp1dev** [comment]
A workaround could be to edit the published date on the page or post and just use that as the last updated.

**Comment by robert1112** [comment]
Hi @bainternet I cannot find the option on the latest. Can you help confirm? Thank you.

**Comment by robert1112** [comment]
> Hi @bainternet I cannot find the option on the latest. Can you help confirm? Thank you.

In case anyone is looking for the solution. 

**Meta Data > Custom > Post Date > Post Modified**

**Comment by LetsPrint3D** [comment]
> > Hi @bainternet I cannot find the option on the latest. Can you help confirm? Thank you.
> 
> In case anyone is looking for the solution.
> 
> **Post info > Meta Data > Custom > Dynamic > Post Date > Post Modified**

Do you know if this was removed? I have the latest version of Elementor and Elementor Pro but the Post Modified option isn't there

**Comment by mareklexuan** [comment]
No, it is still there. Just click on the field with dynamic content, in this case, "Post Date".

![image](https://user-images.githubusercontent.com/25111994/67527039-4db99700-f6b6-11e9-9d73-a92d3d1be6ee.png)

**Comment by knev** [comment]
Your documentation: https://docs.elementor.com/article/431-post-info-widget
... says Type: Custom is available, but it is not to be found on the latest (non-Pro) version of Elementor .
![Screen Shot 2020-02-20 at 09 31 22](https://user-images.githubusercontent.com/9315808/74915029-c827c880-53c3-11ea-8c4b-6b060f90e3b9.png)
