### ISSUE TITLE
Customise Woocommerce Cart Widget with Elementor Page Builder

### ISSUE THREAD

**Issue by giulianorapoz** [pojome/elementor#4600]
## **The Problem...**
Elementor is great for designing Wordpress sites, but **lacks design functionality for Woocommerce sites**.

Currently Elementor allows importing of Woocommerce elements, but **no direct customisation**. You cannot take advantage and use Elementors awesome page builder! :(

## **The Solution:**
To be able to **customise the Woocommerce widgets** (e.g. The Woocommerce cart widget) OR **create BRAND NEW Woocommerce widgets** using the Elementor Page builder.

- Embed these widgets anywhere on the page directly within Elementors page builder.

To enable **proper customisation of Woocommerce elements**. Such as creating brand new Product Archive Pages with the Elementor page builder.

- e.g. Change buttons, product image size and layout

## **Woocommerce store example showing Widgets & Product Archive**
Currently there is no way to modify the below areas, apart from writing custom code and PHP hooks. Why not take advantage of the fantastic Elementor page & element builder and enable customisation of these Woocommerce areas - the end result would be a truly awesome Woocommerce site!

![woocommerce](https://user-images.githubusercontent.com/30539010/40720570-1e614ee8-640f-11e8-9660-c37dab2c224b.PNG)

More than happy to discuss & clarify :)

## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by bainternet** [comment]
Product archive should be out, in E-pro 2.1 as for cart not sure yet.

**Comment by giulianorapoz** [comment]
Thanks @bainternet Great to hear that product archive is coming in 2.1!

In terms of cart, it would be awesome to add in a designer element which would allow it to be fully customized...e.g. something along the lines of below:

![screenshot](https://user-images.githubusercontent.com/30539010/40918251-a853e0ce-67fd-11e8-90fc-f8c0d09e5ee7.jpg)

**Comment by seanvandermolen** [comment]
I came here to complain about this too.  Mostly the cart element missing from the menu.  That's pretty big.  But while you're at it, wish list, log in/ register, cart.  These should all be elements that can be used when building a custom header.

**Comment by BrookeRaraAvis** [comment]
<a href="https://imgbb.com/"><img src="https://image.ibb.co/kAq19d/shopping_cart.png" alt="shopping_cart" border="0"></a>

**Comment by zrk4444** [comment]
Also need a way to completely customize the checkout via Elementor. AKA, I should be able to make my checkout look like Shopify's without any custom code.

**Comment by peepersqueaker** [comment]
Has any progress been made on this?
