### ISSUE TITLE
Controls_Manager::REPEATER has bug on editor.min.js 

### ISSUE THREAD

**Issue by batnyam** [pojome/elementor#4601]
Repeater has bug. https://pastebin.com/Ky5fvQXY it's my widget code. i have this error on browser console.

WordPress version : 4.9.6
Elementor version : 2.0.13

`Uncaught TypeError: Cannot read property 'each' of undefined
    at Object.<anonymous> (editor.min.js?ver=2.0.13:2)
    at Function.each (load-scripts.php?c=0&load[]=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.6:10)
    at n.getStyleControls (editor.min.js?ver=2.0.13:2)
    at n.renderStyles (editor.min.js?ver=2.0.13:2)
    at n.renderUI (editor.min.js?ver=2.0.13:2)
    at n.onRender (editor.min.js?ver=2.0.13:2)
    at n.onRender (editor.min.js?ver=2.0.13:2)
    at load-scripts.php?c=0&load[]=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load[]=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.6:5`

How to fix this error.

**Comment by bainternet** [comment]
@batnyam 

Your code is wrong.
You are using `start_controls_section` to add the repeater instead of `add_control`

you should start a section >> add the repeater >> close the section, ex:

```PHP
$this->start_controls_section(
	'section_clients',
	[
		'label' => __( 'Clients', 'elementor' ),
	]
);
$this->add_control(
	'clients',
	[
		'label' => __( 'Tabs Items', 'elementor' ),
		'type' => Controls_Manager::REPEATER,
		'default' => [
			[
				'tab_title' => __( 'Tab #1', 'elementor' ),
				'tab_content' => __( 'I am tab content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.', 'elementor' ),
			],
			[
				'tab_title' => __( 'Tab #2', 'elementor' ),
				'tab_content' => __( 'I am tab content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.', 'elementor' ),
			],
		],
		'fields' => [
			[
				'name' => 'tab_title',
				'label' => __( 'Title & Content', 'elementor' ),
				'type' => Controls_Manager::TEXT,
				'default' => __( 'Tab Title', 'elementor' ),
				'placeholder' => __( 'Tab Title', 'elementor' ),
				'label_block' => true,
			],
			[
				'name' => 'tab_content',
				'label' => __( 'Content', 'elementor' ),
				'default' => __( 'Tab Content', 'elementor' ),
				'placeholder' => __( 'Tab Content', 'elementor' ),
				'type' => Controls_Manager::TEXT,
				'show_label' => false,
			],
		],
		'title_field' => '{{{ tab_title }}}',
	]
);

$this->end_controls_section();
```

**Comment by insignia92** [comment]
Hi there, the issue still exists not sure why it's happening here's my code: https://pastebin.com/Pr5XiXjQ
