### ISSUE TITLE
Hover Effect for Video to allow Text and Image controls.

### ISSUE THREAD

**Issue by ljgarnes** [pojome/elementor#4605]
I need the ability to add a video using a background overlay.  On Hover it changes photos and has a button with a video lightbox feature.

See this website as an example.  I can't convert it currently to give the same exact behavior.

https://www.resipsamarketing.com/about/

Media Carousel nor the Video widget gives enough options to obtain the exact results.  The above website is currently in Divi and I'm stuck and unable to convert to Elementor.  

I was able to get far enough using columns and such with javascript but the video lightbox doesn't work because I can't add a css class to the link to initiate the javascript.

Example.
http://awebsitedemo.com/resipsamarketing/about/

So I guess they stay with Divi?

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
