### ISSUE TITLE
Cannot have 2 fixed background sections on 1 page with shape divider label:bug 

### ISSUE THREAD

**Issue by unclerom** [pojome/elementor#4606]
I have a page with 2 separate sections with fixed backgrounds the first one has a bottom shape divider and displays normally but the second just displays no image background but in inspector the url is there. i am using oceanwp for the theme. if i remove the bottom shape divider from the 1st section higher on the page then then 2nd section image displays? Also just above the 2nd section there is an icon box with grow animation on the icon when i hover on the icon the background of the fixed section below flashes the overlay color. if i remove the grow animation the flashing stops.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
