### ISSUE TITLE
Elementor form says "error"when a guest(someone that's not logged in) submits the form.

### ISSUE THREAD

**Issue by elementorlover121** [pojome/elementor#4607]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Simply when any guest tries to submit the form it says "error". I tried to deactivate all the plugins but elementor and elementor pro, removed all the required fields,edited the send and receive emails and its still the same issue.
this is my website to test it.
## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

Operating System: | Linux |  
-- | -- | --
Software: | LiteSpeed |  
MySQL version: | 10.1.31 |  
PHP Version: | 7.2.5 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected


```
</details>

**Comment by bainternet** [comment]
@elementorlover121 

We can't replicate
Please contact our support at support@elementor.com for guidance in resolving this issue.
