### ISSUE TITLE
[Feature Request] More blog archive options

### ISSUE THREAD

**Issue by daconix** [pojome/elementor#4610]
It would be great to have more layout options for blog archive. I would like the option 
similar to this https://www.screencast.com/t/qQJq4CsO5R drag & drop option for the title, image, text, category and so on so we can reorder them as we want.

Anyone sharing same thoughts with me?

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
