### ISSUE TITLE
ACF Custom Fields are Not Displayed at RUNTIME

### ISSUE THREAD

**Issue by arifonline007** [pojome/elementor#4612]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arifonline007** [comment]
Dear Support Team,

I had Created Custom Post Type (Holidays) & Its Categories (Holidays Categories).

I had made ARCHIVE TEMPLATE & assigned to Custom Post Type (Holidays).

My Issue:

In Elementor Environment Categories (Holidays Categories) are displayed in Preview. But When I go Live the Fields are NOT Displayed.

Please find the attached Images for Reference.

**Comment by arifonline007** [comment]
![cpt-category outside elementor](https://user-images.githubusercontent.com/39792897/40771479-1d3674a0-64c6-11e8-98b3-6bc9088f85fa.jpg)
![cpt-category in elementor](https://user-images.githubusercontent.com/39792897/40771480-1d72b8ac-64c6-11e8-8a9b-862acd72dab6.jpg)

**Comment by bainternet** [comment]
We cant replicate.

Please contact our support at support @elementor.com for guidance in resolving this issue.
