### ISSUE TITLE
[BUG][PRO] Cannot see background image set on content using Elementor Template widget

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#4614]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I was trying to create a "global" content, to incorporate into all pages as a "post-header".
So i set up one of the sections to have title centered and background image which cover the entire section, and i created the business logic for the image which allow me to show the post thumbnail if present, otherwise a generic image.

![image](https://user-images.githubusercontent.com/19909323/40774879-03bf05f4-64c7-11e8-99cc-161d99b14caf.png)

![image](https://user-images.githubusercontent.com/19909323/40774936-25b4f4ca-64c7-11e8-9998-d05293c2f3f9.png)

When i try to add the content using Elementor Template Widget, everything is imported fine except the business logic applied to background-image of the section.

![image](https://user-images.githubusercontent.com/19909323/40775123-946922a6-64c7-11e8-9846-7d2b94aa9141.png)

Inspecting the generated code, it seems background specs are correctly printed, except the background-image.

![image](https://user-images.githubusercontent.com/19909323/40775365-2bebe01e-64c8-11e8-953b-a7833062c3de.png)

![image](https://user-images.githubusercontent.com/19909323/40775334-167f184a-64c8-11e8-85ef-28f597a336f0.png)

## Steps to reproduce

- Create a content with a dynamic background image and a fallback image
- Try to import the content using the Elementor Template widget
- See if the background image is still present

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Manusan42** [comment]
Hmm, I have something similar. 
Dynamic background image from featured image does not work on live site but does in Elementor build mode. The code is like in your example, on build mode all fine and on live site only the background-image property is missing.

**Comment by teolaz** [comment]
@Manusan42 seems the opposite in my case, live sites are showing correctly images, Elementor edit mode does not.

**Comment by bainternet** [comment]
should be fixed by #4707 

please make sure to update.

**Comment by fxaviers** [comment]
I'm having this same problem.
A dynamic background image for the featured image does not work on the production site, only on the builder.
I've cleaned all caches, recreated CSS, and still no display.
Elementor: 2.2.7 and Pro: 2.1.11
