### ISSUE TITLE
Have post grid use the last category

### ISSUE THREAD

**Issue by jornmo** [pojome/elementor#4620]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Showing the top category for blog posts on the posts grid (The "Posts" element) is very general. I'd like it to be more descriptive using the deepest one in the category hierarchy. 

**Describe the solution you'd like**
Either have the option to chose whether the displayed category should be the topmost or the bottom most, and/or utilising Yoast's "Primary Category" feature (which should have been a core feature of WP IMHO). 

![cat](https://user-images.githubusercontent.com/6152248/40850711-a4a5ccf6-65c5-11e8-86c9-cac8428a693a.png)

**Describe alternatives you've considered**
Leaving it as it is :)

**Comment by bainternet** [comment]
@jornmo 

Thanks for your suggestion, can you please explain better what you are suggesting.

**Comment by jornmo** [comment]
Say you have a category called "News". News has some sub-categories: "Domestic news", "Foreign news" and "Sports". If I now place a post grid widget on my frontpage, and enable the category badge - all posts are getting the badge "News", i.e. the topmost category. However, I'd think it would be better if the posts received the bottmmost category as a badge, i.e. "Domestic news", "Foreign news" or "Sports".

Hope that was clearer? :)

**Comment by bainternet** [comment]
@jornmo 

We can't replicate.

Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by jornmo** [comment]
It is not a bug, but a feature requstest :)
