### ISSUE TITLE
Adding Elementor Page Builder as a Custom Field in ACF

### ISSUE THREAD

**Issue by DavvaM** [pojome/elementor#4621]
I want the ability to add a section where it calls in the Elementor Page Builder. For example when I open up the page template in Wordpress I have a load of Custom Fields I would like the Elementor Page Builder to come after a series of images.

I know there is a plugin for visual composer called acf bridge to visual composer or something like that and within your acf fields you can select visual composer as a custom field add the code to the template and in backend the visual composer builder appears where you added it within the template

**Comment by bainternet** [comment]
You can already do that, 
Using posts field with post type `elementor_library` and to render the the ID of the selected template and call 
```PHP
echo \Elementor\Plugin::$instance->frontend->get_builder_content_for_display( $template->ID );
```
