### ISSUE TITLE
Remove Elementor menu

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#4622]
Hello guys,

For non-administrator access levels (subscriber, collaborator, author, publisher, ...) I deactivated all the options in the function manager in the Elementor. But when I access an Author-level account, it still shows me the Elementor menu (https://screenshot.net/pt/9k51eu8).

The Author level account can not edit any page and has no access to the settings of the Elementor. But he sees the Elementor menu.

So I suggest removing this menu when the Elementor option is disabled for the user.

Thanks,
Rodrigo Carlos

**Comment by bainternet** [comment]
@proddigital 

thanks for the suggestion but this is more of a 3rd party plugin territory than Elementor core like any other WordPress admin menu.

thanks again.

**Comment by proddigital** [comment]
Hello @bainternet

What you wanted to say is that it is not the Elementor that puts the Elementor menu on the side of the Wordpress admin, and so it is not the Elementor that can remove it?

**Comment by bainternet** [comment]
@proddigital 

How did you get that from what I said?? Where did I say that It's not Elementor that adds the menu item?

`elementor_library` is a custom post type and acts like a custom post type which authors can see.

**Comment by proddigital** [comment]
Hello @bainternet

I'm sorry, but maybe I misunderstood. I thought you had said that the Elementor menu had been placed by another plugin.

But anyway... I have how to remove the menu or is it only with you guys?

**Comment by bainternet** [comment]
A simple WordPress hook would do the job ex:

```PHP

add_action( 'admin_menu', function () {
	$current_user = wp_get_current_user();
	// Add/Remove roles as you see fit
	$roles_to_remove = [ 'author', 'contributor' ];
	foreach ( $roles_to_remove as $role ) {
		if ( in_array( $role, $current_user->roles ) ) {
			remove_menu_page( 'elementor' );
			return;
		}
	}
}, 999 );
```

**Comment by proddigital** [comment]
Hello @bainternet

Should I put this code in the functions.php of the theme?
If so, then I put it and it did not work.

I also have WPBakery Page Builder and to remove it I found this code below that worked:

```
function custom_menu_page_removing() {
    remove_menu_page('vc-welcome');
}
add_action( 'admin_init', 'custom_menu_page_removing' );
```

https://screenshot.net/pt/novgdso


I tried doing the same with the Elementor menu, but it did not work. When placing the code below the admin page is inaccessible:

```
function custom_menu_page_removing() {
    remove_menu_page('elementor_library');
}
add_action( 'admin_init', 'custom_menu_page_removing' );
```

I tried changing "custom_menu_page_removing" to "custom_menu_post_type_removing" but it also did not work:

```
function custom_menu_page_removing() {
    remove_menu_page('elementor_library');
}
add_action( 'admin_init', 'custom_menu_post_type_removing' );
```

https://screenshot.net/pt/x24pgir
