### ISSUE TITLE
[Feature request] Custom fonts loaded from a theme

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#4624]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I believe that the best place to define theme fonts is in the theme. But If I do so, I'm unable to select these fonts from Elementor's Typography menu. This issue is mostly concerning self hosted fonts, but it has some consequences even when using Google Fonts (see below).

On the other hand, if I define my custom fonts in Elementor, they are not visible in my Theme Customizer. I'd have to define (and load) them twice, which is neither ellegant, nor effective. 

Similar problem goes even with Google Fonts. Sometimes you need to select just some of the weights or styles, sometimes you need to select special encoding, so again, it's mostly better to let the theme to define the Google Fonts. In this case you can, of course, see the Google font in Elementor Typo, but when you select it, Elementor adds an extra Google Font call with the maximum settings available.

**Describe the solution you'd like**
The best solution would be to add an extra font group (e.g. "Theme Fonts"), where it would be only the name of the font and CSS font-family string. I'm not sure, maybe this is already doable by using some filter (e.g. elementor/fonts/additional_fonts), but in docs, there is no special info on how to do it.

And maybe it would be useful, to let the developer remove all the Google Fonts from the Typo menu completely and use only those defined by the theme (commonly a developer doesn't want to give users a chance to mess up with so many fonts).

**Describe alternatives you've considered**
I've tried to add self hosted custom font (using Elementor > Custom Fonts) and filled in just the name and weights and styles (without loading any files). It actually worked, but I'm not convinced, that it would work for all cases and I feel, it's more a hack than the intended way, how to use this feature.

I could also use a custom css class with the name of the font, but it's not that intuitive.
**Additional context**

**Comment by bainternet** [comment]
This is a bit tricky but doable,

To add your theme fonts first you need to add the Font group:
```PHP
/**
 * Add Font Group
 */
add_filter( 'elementor/fonts/groups', function( $font_groups ) {
	$font_groups['theme_fonts'] = __( 'Theme Fonts' );
	return $font_groups;
} );
```
Then add your fonts to the fonts control:
```PHP
/**
 * Add Group Fonts
 */
add_filter( 'elementor/fonts/additional_fonts', function( $additional_fonts ) {
	// Key/value
	//Font name/font group
	$additional_fonts['Theme Font Name'] = 'theme_fonts';
	$additional_fonts['Theme Font Name2'] = 'theme_fonts';
	return $additional_fonts;
} );
```

Now if they are included by your theme, you are done.
if not you can hook in to the `elementor/fonts/print_font_links/{$font_type}` action hook to enquque your theme fonts, ex:

```PHP
add_action( 'elementor/fonts/print_font_links/theme_fonts', function( $font_name ) {
  // Enqueue your font
} );
```

as for Google fonts, Elementor enqueues the Google font in a generic manner to cover 99% of the uses cases. If you need something other than that you can tell Elementor not to include the google fonts:

```PHP
add_filter( 'elementor/frontend/print_google_fonts', '__return_false' );
```

and then enqueue the fonts yourself with only the weights and styles you need.

**Comment by reelism** [comment]
> Hello,
> the above filter does not seem to work anymore:
> `add_filter( 'elementor/frontend/print_google_fonts', '__return_false' );`
> 
> I added this filter to my functions.php, but Elementor still lists the Google fonts in the editor. Has something changed and is there now a new way to remove the google fonts?

Any updates to this?

**Comment by SNeilson** [comment]
I'm also looking for a way of removing both the google and system fonts from the dropdown to stop users using any other fonts than the ones in our brand guidlines, is this possible?

**Comment by prashantcs8** [comment]
This is a bit tricky but doable, 
for example I added "danielblack" custom font
Step 1 created fonts folder in the child theme folder and paste font files (.eot, .woff, .ttf).
Step 2 in the child theme folder add css in style.css
```
@font-face {
    font-family: 'danielblack';
    src: url('Daniel-Black-webfont.eot');
    src: url('fonts/Daniel-Black-webfont.eot?#iefix') format('embedded-opentype'),       
         url('fonts/Daniel-Black-webfont.woff') format('woff'),
         url('fonts/Daniel-Black-webfont.ttf') format('truetype');       
    font-weight: normal;
    font-style: normal;

}
```
Step 3 add code in functions.php
```
/**
 * Add Font Group to Elementor
 */
add_filter( 'elementor/fonts/groups', 'prefix_elementor_custom_fonts_group', 10, 1 );
function prefix_elementor_custom_fonts_group( $font_groups ) {

	$font_groups['danielblack'] = __( 'Daniel Black' );
	return $font_groups;
}
/**
 * Add Group Fonts to Elementor
 */
add_filter( 'elementor/fonts/additional_fonts', 'prefix_elementor_custom_fonts', 10, 1 );
function prefix_elementor_custom_fonts( $additional_fonts ) {
	// Key/value
	//Font name/font group
	$additional_fonts['danielblack'] = 'danielblack';
	return $additional_fonts;
}
```
then you will find "Daniel Black" group "danielblack" fonts in Typography > fonts dropdown

**Comment by mdisseny** [comment]
Hi there,
Thank you @bainternet for the code snippets, work like a charm. 
Following the @SNeilson question, I'm aldo interested in this feature, it would be great to have the ability to remove system fonts or at least push them to the end of the list.
