### ISSUE TITLE
Buttons Missing in Safari Revisited

### ISSUE THREAD

**Issue by klopfer** [pojome/elementor#4629]
I'm submitting a new issue as I see the previous one is closed.  #4512.  Fine to merge with that one.  

Description:
The problem is that the editing buttons don't appear in Safari 11.1 on a Mac.  When mousing over the sections in Elementor, only the edit section icon appears.  Delete, move, etc. do not appear.  

Prerequisite.
Mac running Safari 11.1 (Mac OS 10.13.4).  
Website on try.getpojo.com

Steps to Reproduce.
In Safari 11.1 create a demo site on try.getpojo.com (can really be any elementor based site but this is convenient).
Create a new page.
Create a new section
Mouse over the "edit section" icon.  Only the edit section icon appears.  Not the delete, move, etc.  The other buttons should appear as they do on Chrome and Firefox.  

This seems to be a client side problem.  I've replicated on other servers but this one is easy to access and run by pojo, so is easy to replicate.

**Comment by bainternet** [comment]
@klopfer 

I can't replicate, can you send a screenshot? even better a screen capture?

**Comment by klopfer** [comment]
@bainternet Thanks for looking into it.  I think I have determined the conditions under which this happens.  I made a screencast of the problem here https://www.dropbox.com/s/9yzhl15k43szfzs/ElementorSafari.mp4?dl=0

The issue seems to be when two things coincide. 

 First, under settings->general turn on Show Scroll bars "always".  This doesn't have to be set, but makes it easier to replicate.  Otherwise it depends on a lot of other factors as to whether the scrollbars appear.

Second, the window needs to be small enough to require the scrollbars to show.  That is, the window needs to be narrower than the page, which forces a horizontal scrollbar to appear.  Easy way to do this is make the window a reasonable size and then view->zoom in using safari until it requires scrolling.  

This is what I replicated in the video.  It starts off by making a new page and a new section.  Everything is fine.  Turn on scroll bars appear always.  Still fine.  Zoom in on the page so that it scrolls off horizontally.  Now the buttons don't appear.  Then I undo some of those changes so that the scrollbars disappear and all is ok again.  

So, this seems to happen when the horizontal scroll bar needs to appear.  Don't know why that causes it, but hopefully this can help replicate and make it easier to debug.  I'm happy to test.

**Comment by bainternet** [comment]
@klopfer 

Thanks for the video, that helped a lot.
The reason you are only seeing the Edit icon is that when the screen resolution of the preview window is at a tablet resolution we only show the edit icons. It has nothing to do with a scroll-bar but it gave us an Idea where to look.

This is more of a feature than a bug.

Thanks for reporting and feedback.
