### ISSUE TITLE
Construction mode + Impressum & Datenschutz pages

### ISSUE THREAD

**Issue by aarontgrogg** [pojome/elementor#4633]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The problem is described in this forum post:
https://wordpress.org/support/topic/construction-mode-impressum-datenschutz-pages/

**Describe the solution you'd like**
Website owners should be able to select pages that can be "bypassed" when in Construction or Maintenance mode.

**Describe alternatives you've considered**
Currently I have to create flat HTML versions of these pages and link to those from the Construction/Maintenance page.  This is a waste of time and resources.

**Additional context**
Otherwise, really love this plugin.  Thanks!

**Comment by bainternet** [comment]
I merged this issue with  #2687, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
