### ISSUE TITLE
Gallery, colums amount not changing on mobile

### ISSUE THREAD

**Issue by Solowebmaster** [pojome/elementor#4635]
![image](https://user-images.githubusercontent.com/37866162/40889371-224b5b54-676e-11e8-85d9-2bf3dced2d47.png)

Can't change number of colums in gallery widget when editing mobile version

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
