### ISSUE TITLE
condition and repeater issue

### ISSUE THREAD

**Issue by skalanter** [pojome/elementor#4636]
Hello,
In my own widget, wherever I want to use foreach it gives the error in log file 
`[04-Jun-2018 07:27:12 UTC] PHP Warning:  Invalid argument supplied for foreach() in root~\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1102`
and the following error in Front-End 
`~root\wp-content\plugins\elementor\includes\base\controls-stack.php on line 1129
`
it seems this issue is for 
`Controls_Manager::REPEATER`
when we use
`condition
`
How can we fix the issue?

**Comment by bainternet** [comment]
@skalanter 

We can't possibly help if you don't provide details.

Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

And in your case, the custom code is missing as well.

please feel free to reopen correctly, thanks.
