### ISSUE TITLE
[Dev] How would I register my own Pages / Blocks?

### ISSUE THREAD

**Issue by redlagoon** [pojome/elementor#4637]
Hey.

How would I go about registering my own Pages / Blocks? 

I have built the mechanism for adding new templates from a JSON, but it's not really useful as there's no visual way of telling what is what, because they're put inside the "My Own Templates":

http://prntscr.com/jql5gw

Naturally, the "Pages" option looks way better and is exactly what I'd need. Also the blocks page. A visual way to parse through things and even a search!

Can this be done?

Thanks.

**Comment by bainternet** [comment]
Currently, this feature is not supported.

I merged this issue with  #3127, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
