### ISSUE TITLE
Pages for Post Widgets

### ISSUE THREAD

**Issue by Perchpole** [pojome/elementor#4638]
Can we get the Post Widget to work with pages? I know a number of other developers have expanded the default Posts widget to do this but the application is limited. In Elementor Extras, for example, it is possible to select Pages but in order for it to work properly it is then necessary to manually exclude all of the pages you don't want to show. Apparently this is due to Elementor's "predefined query posts control" - so I'm told!

Being able to select specific Pages to show would be incredibly useful - especially on home pages where you want to direct visitors to important pages on the site.

**Comment by bainternet** [comment]
@Perchpole 

Yes you can, set the query source to "manual selection" and select the pages you want.
