### ISSUE TITLE
[Bug] Select options default value not showing

### ISSUE THREAD

**Issue by batnyam** [pojome/elementor#4639]
Select tags default value not showing in SELECT control manager. How to fix it.

First screenshot is my code. 
Second screenshot is $categories array.
Third screenshot is editor.

<img width="468" alt="screen shot 2018-06-04 at 9 18 40 pm" src="https://user-images.githubusercontent.com/7379389/40919717-e2253728-683c-11e8-87c1-be88741165ef.png">
<img width="232" alt="screen shot 2018-06-04 at 9 19 05 pm" src="https://user-images.githubusercontent.com/7379389/40919733-e89f7c80-683c-11e8-92e0-06fbe22f4c50.png">
<img width="297" alt="screen shot 2018-06-04 at 9 19 13 pm" src="https://user-images.githubusercontent.com/7379389/40919738-ed689120-683c-11e8-9cbf-202a20834048.png">

**Comment by bainternet** [comment]
@batnyam 

Select control accepts its `options` as an associative array of value => label in your case its a numeric array, so it won't work unless you set the default to "0".

for reference: https://developers.elementor.com/elementor-controls/select-control/#Arguments
