### ISSUE TITLE
[Feature Request] Filter Taxonomy Archive Posts filtered by CPT

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#4640]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I've got a custom taxonomy shared by 2 CPT's. On the archive page of the taxonomy term, I want to have the posts from these 2 taxonomies sepatated in 2 different columns. Unfortunatelly this is impossible, the posts from both CPT's are mixed together.

**Describe the solution you'd like**
Add a field to Posts Query to filter (or exclude) posts by specific CPT.
Or maybe (hopefully) it would be doable by  #1748.

**Describe alternatives you've considered**
Custom coding.

**Comment by bainternet** [comment]
Sadly, this feature is not supported,  not without some major custom coding.

But wait for  #1748 which will help in a better starting position.
Thanks for the feedback.
