### ISSUE TITLE
Favicon not working on the elementor editor

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#4641]
The site's favicon doesn't appear on the tab when using Elementor page builder which is very inconvenient when working with tabs.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by bentalgad** [comment]
It's a very simple problem so i didn't thought i should make it too long.

To replicate the problem you just have to set a favicon for your site, then enter the elementor visual editor to edit one of the sites pages and see that the favicon won't appear on that browser tab.

I use the lastest chrome for mac version (66.0.3359.181) and the latest wordpress version (4.9.6) and the latest elementor (2.0.14) version with the latest version of astra theme (1.4.0)

**Comment by PortalPacific** [comment]
Wow this isnt fixed yet?  Facing the same issue. And this was brought up over 7 months ago. =/

**Comment by jasonb4u** [comment]
Watching

**Comment by bentalgad** [comment]
Still???

**Comment by Neuliaus** [comment]
Yeah im in the same boat

**Comment by forusak** [comment]
How is this not yet fixed? Cmon, I panic so often that I closed the tab, but it is just without favicon...

**Comment by Steve-Lowrey** [comment]
Easy to do, forget using Elementor! Use your WP Dashboard.
Go to Appearance, then Customise. Scroll down to Site Identity and add it here,

**Comment by rcbal** [comment]
Can't do via WP dashboard if you are using a theme, in my case Astra.
Can't believe Elementor is hiding favicon setting under appearance/customize.  WHY??

**Comment by gaddox** [comment]
I have a solution for anyone using the Astra theme:

Appearance -> Customize

Header -> Site Identity

Astra, and some other themes, have unique menus that hide a lot of options.

**Comment by ikef** [comment]
Another reason to hate Elementor / page builders

**Comment by PortalPacific** [comment]
> Another reason to hate Elementor / page builders

Thats pretty silly because if you wernt so reliant on them you wouldnt be here crying about a very simple issue any developer could solve. Silly silly

**Comment by Chris29888** [comment]
Still doesn't work... It's a really minor issue, but it's annoying nonetheless.

**Comment by ikef** [comment]
> > Another reason to hate Elementor / page builders
> 
> Thats pretty silly because if you wernt so reliant on them you wouldnt be here crying about a very simple issue any developer could solve. Silly silly

Certainly not reliant on them. It's you yourself who was complaining it wasn't fixed!

**Comment by JohnnyBravoTheBest** [comment]
This issue is still present. Favicon won't show if Elementor Canvas is set as page template.

**Comment by RomainLaf** [comment]
Using Hello Elementor Theme. My Favicon is setup on both Wordpress > Theme > Customize and Elementor > Site Settings.
It's showing well on any Front pages or Wordpress Admin pages. But the favicon is not showing on any Elementor Edit pages. 

It seems like the <link rel="icon"> tag is placed inside the <body> tag instead of <head> tag inside any Elementor Editor Pages : 
![Screenshot-Arc-28-11-10 11](https://github.com/user-attachments/assets/cc66c595-76ac-4a74-99f6-9685a8f890a5)
![Screenshot-Arc-28-11-10 13](https://github.com/user-attachments/assets/f7c18f17-1219-4895-a8e8-fc3bbf105036)
