### ISSUE TITLE
Incompatibility of Global Widgets and Polylang

### ISSUE THREAD

**Issue by rootion** [pojome/elementor#4652]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

There is an incompatibility with Global Widgets & Polylang (and I assume WPML, but didn't test it).

Global Widgets can be translated, but if you try to translate a Global Widget the frontend will enter a never ending loading loop.

If you use a Global Widget in a Template you want to translate, the frontend will also experience the same loading loop. The only way to translate a Template is to not to have a Global Widget in there.

## Steps to reproduce

- Create a Global Widget
- Create a translation for the Global Widget
- Edit with `Edit with Elementor` 

Elementor Editor will not load.

- Create a Template that has a Global Widget inside
- Create a translation for the Template
- Edit with `Edit with Elementor` 

Elementor Editor will not load.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

In Polylang, translation of My Templates is currently active under:  
Language > Settings > Custom post types and Taxonomies > My Templates

## Environment
Wordpress 4.9.6
Elementor 2.0.14
Elementor Pro 2.0.9
Polylang Pro 2.3.6

**Comment by Prakhar236** [comment]
Dealing with the same issue. Please fix it.

**Comment by touchestudio** [comment]
@Prakhar236 from what I read in the Elementor Change Log, they did an update that is supposed to resolve this. Now the translation plugin companies need to do an update as well. I contacted Polylang and they said nothing was ever reported to them, and no update is planned for this. WPML said they will get an update out eventually. We all hate it when that happens.

A temporary workaround is this:
- Go to the original language page. Edit and UNLINK all the global widgets. 
- Go to the second language, overwrite with 1st language content (if you're keeping the same design and just changing the text). 
Now you can edit the content of the second language. As long as there are no global widgets when duplicating.

Hope this helps for now!

**Comment by bainternet** [comment]
Filter already exists in Pro.

thanks for reporting.

**Comment by DrMartinGonzo** [comment]
Unfortunately I too am stilll experiencing the issue.
@bainternet Sorry for replying to a closed issue, but what filter are you mentionning ?

**Comment by rskonieczka** [comment]
+1

**Comment by vayurobins** [comment]
> Filter already exists in Pro.
> 
> thanks for reporting.

@bainternet would you please elaborate? Do you mean there is filter hook in Elementor Pro or Polylang Pro? Would you mind referencing it, that would clarify things? :-)
