### ISSUE TITLE
Section video background is not viewed in Google Chrome

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4655]
Hello.
**Bug info**
I don't see video background in Chrome, no matter in editor or on page view. Cache is cleared.
Edge, Firefox, Opera and other webkit based browsers, works well.

**Versions info:**
Chrome 67.0.3396.62
Elementor v2.0.14
Elementor Pro v2.0.9

**Comment by bainternet** [comment]
A fix is already merged and waiting for release which should be out in a few hours.
#4626

**Comment by bainternet** [comment]
released! :)
