### ISSUE TITLE
Switching tabs causes a selected accordeon/toggle item to open/close again.

### ISSUE THREAD

**Issue by zefflubrano** [pojome/elementor#4656]
_First and foremost, I'm really bad at explaining an issue in short in the title. So apologies for that, hehe. 
This is not a serious issue, but as I don't see the purpose for this type of behavior, I'd label it more of a bug rather than a feature request or suggestion for something to tweak._

**Bug**
Switching tabs (in the browser) while an accordion/toggle item is active fires the open/close event for that particular item again. This also happens if I minimize/maximize. 

**Request/fix**
It would be awesome if these items only responded on click events.

**Browser**
I'm using the latest version of Firefox Quantum, but I've had this issue as well in Chrome.

I know that events can be really annoying to fix, but this might just be a case of being more specific on when to fire the open/close event for each item.

Thanks for being such lifesavers with Elementor,
Zeff

**Comment by bainternet** [comment]
@zefflubrano 

We use the `focus` event in our tabs/accordion/toggle for accessibility reasons instead of `click`.

so it's not something we need to fix, Its the desired behavior.

thanks for the feedback.

**Comment by Haloan** [comment]
I noticed this behavior as well and was going to log it as a bug but I see someone else already did.
