### ISSUE TITLE
[BUG][PRO] Featured image as dynamic background for column not showing on live site

### ISSUE THREAD

**Issue by Manusan42** [pojome/elementor#4662]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If I set a featured image as a dynamic background for a column in a single post template, it is only shown in editor mode:
![elementor_featuredimage_columnbackground_bug_1](https://user-images.githubusercontent.com/12750571/40992397-fe26dd86-68f6-11e8-8bed-66f93995286d.png)

... but not in preview or live mode:
![elementor_featuredimage_columnbackground_bug_2](https://user-images.githubusercontent.com/12750571/40992400-007affa4-68f7-11e8-8260-8ee1ae4ae0b6.png)

## Steps to reproduce

1. Happens consistent, so first step can be fresh WordPress install.
2. I used Twenty Fifteen default theme.
3. Make a test post with featured image.
4. Make a Single Post template.
5. Put some stuff into section and place featured image to column with content as dynamic background  "Style > Background > Normal > Background Type Classic > Image > Dynamic > Post Featured Image".
6. Save or preview. In editor the image is shown, in preview or live site not (background-image property is missing).

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
	MySQL version: 5.6.36
	PHP Version: 7.0.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: https://www.[[censored]]
	Home URL: https://www.[[censored]]
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 128M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Fifteen
	Version: 2.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.0.15
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.10
		Author: Elementor.com

== Debug ==
	Errors: 
		ViewDestroyedError: View (cid: "view334") has already been destroyed and cannot be used.
			at [[censored]]/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-05 17:10 +00:00
			x 2 times

		ViewDestroyedError: View (cid: "view4187") has already been destroyed and cannot be used.
			at [[censored]]/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-05 17:04 +00:00
</details>

**Comment by drawcard** [comment]
I can confirm this issue is happening here as well, at first I thought it was a CPT-related issue but it seems like it affects all uses of Dynamic Featured Images on column backgrounds whether it's a post, page, or CPT item.

One workaround is the set the Dynamic Featured Image on the section background (not the column) but that's not an ideal solution.

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.0.35
	PHP Version: 7.1.18
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: http://www.drawcard.com.au/dev/alexthomas
	Home URL: http://www.drawcard.com.au/dev/alexthomas
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Thematic for Wordpress
	Version: 1.0.0
	Author: Automattic
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

== Active Plugins ==
	AceIDE
		Version: 2.6.1
		Author: AceIDE

	Elementor
		Version: 2.0.15
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.10
		Author: Elementor.com

	Limit Login Attempts
		Version: 1.7.1
		Author: Johan Eenfeldt

	Pods - Custom Content Types and Fields
		Version: 2.7.4
		Author: Pods Framework Team


== Debug ==
	Errors: 
		ViewDestroyedError: View (cid: "view415") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 04:13 +00:00

		ViewDestroyedError: View (cid: "view912") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 03:50 +00:00

		ViewDestroyedError: View (cid: "view374") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 03:49 +00:00

		ViewDestroyedError: View (cid: "view373") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 03:47 +00:00

		ViewDestroyedError: View (cid: "view371") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 03:44 +00:00

		ViewDestroyedError: View (cid: "view370") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 03:35 +00:00

		ViewDestroyedError: View (cid: "view1999") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 03:31 +00:00

		ViewDestroyedError: View (cid: "view370") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 03:30 +00:00
			x 2 times

		TypeError: Cannot read property 'errors' of undefined
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.15 - 2:132497
			2018-06-07 01:10 +00:00
			x 8 times

		ViewDestroyedError: View (cid: "view355") has already been destroyed and cannot be used.
			at http://www.drawcard.com.au/dev/alexthomas/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-07 01:03 +00:00

**Comment by donwattz1459** [comment]
I can confirm this on a section background that dynamic does not work either.

**Comment by bainternet** [comment]
Fixed in 2.0.16
thanks

**Comment by henrique-voni** [comment]
Hello, i'm trying to display an ACF image field as background of a section, but it's not showing up. See: https://prntscr.com/mx2r2t

**Comment by mbenba01** [comment]
> Hello, i'm trying to display an ACF image field as background of a section, but it's not showing up. See: https://prntscr.com/mx2r2t

Hi Henrique-voni
It's 2021 and I am experiencing the exact same issue. I was just wondering if you found the solution to your problem?

Thanks!

**Comment by KPC4** [comment]
> > Hello, i'm trying to display an ACF image field as background of a section, but it's not showing up. See: https://prntscr.com/mx2r2t
> 
> Hi Henrique-voni It's 2021 and I am experiencing the exact same issue. I was just wondering if you found the solution to your problem?
> 
> Thanks!

Hi, 

Have you resolved this yet? I am having the same issue!

Thanks
