### ISSUE TITLE
Plugin Widget 3rd party or designer name displayed while creating content in Elementor

### ISSUE THREAD

**Issue by Giffordcl** [pojome/elementor#4664]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
While adding or editing content in elementor or pro it is difficult because some widgets have the same names across designers or 3rd parties, to know which one your actually using sometimes. Even if it is initials or something, a way to distinguish which one your using or have used while in process or going back and editing a page or post. Plugin Widget 3rd party or designer name displayed while creating content in Elementor not just on the widget selector section but somewhere either in content, style, or advanced tab.  I have 2 hotspots, 3 timelines, 5 buttons, too many carousels. :)

**Describe the solution you'd like**
Just a maybe authored by info box somewhere internally.

**Describe alternatives you've considered**
Keeping an actual log file of what ones I've  used with what elements....very time consuming. 

**Additional context**

**Comment by bainternet** [comment]
@Giffordcl 

We already group our widgets by name "Basic" and "Pro" anything else should be in its own group, Other than that we can't control the way 3rd party developers name their widgets.

thanks for the feedback.
