### ISSUE TITLE
[Bug] Imported pages' widgets don't show up correctly after initializing Elementor unless at least one change has been applied to them.

### ISSUE THREAD

**Issue by redlagoon** [pojome/elementor#4665]
I've used the WXR Importer to import pages. Naturally, Elementor's awesomeness came into play and it went smoothly.

Except that the widgets' styling is not applied immediately:

http://prntscr.com/jrd0zd

But in the front-end, it looks all fine:

http://prntscr.com/jrd1ee

And now, going back to re-editing after refresh still shows the editor view as broken.

I'm using `get_style_depends` to enqueue my styles.

Any ideas on what to do?

**Update: This happens on everything now, not just older, imported pages. Can't get the styling to work in the editor. It seems the get_style_depends is just not being called in the editor.**

For reference, this is what my full function looks like:

```
    /**
     * Get style dependencies.
     *
     * Retrieve the list of style dependencies the element requires.
     *
     * @since 1.9.0
     * @access public
     *
     * @return array Element styles dependencies.
     */
    public function get_style_depends() {
        $current_file = basename( __FILE__, '.php' );
        $template_style_css = THEME_DIR_URI . "/Inc/Elementor/Widgets/{$current_file}_styling.css";
        $handle = $this->get_name() . '-style';

        wp_register_style( $handle, $template_style_css );
        return [$handle];
    }
```

**Comment by bainternet** [comment]
@redlagoon 

Currently `get_style_depends` only works for the front end, not the editor, so need to enqueue your style in the editor manually:

ref: #3670 

thanks for reporting.
