### ISSUE TITLE
Backend UI Element Needs Name Change: Elementor > My Templates

### ISSUE THREAD

**Issue by BrookeRaraAvis** [pojome/elementor#4666]
**Elementor > My Templates**

The the tab labeled "Content" should be relabeled to say "Page". The other tabs (Section, Header, Footer, Single, and Archive) are all already labeled to match their template types.

Templates weren't making any sense to me until I realized this UI mistake.

# CIRCLED IN PINK

![elementor](https://user-images.githubusercontent.com/1435355/41020900-8f3a68d4-6932-11e8-807c-fe5fc91a035f.PNG)

**Comment by bainternet** [comment]
@BrookeRaraAvis 

We are thinking about reworking this whole section,

thanks for reporting.

**Comment by BrookeRaraAvis** [comment]
This still hasn't been addressed.
