### ISSUE TITLE
[Feature Request] Archive - own post layout 

### ISSUE THREAD

**Issue by pawelszroeder** [pojome/elementor#4667]
I is it possible to change layout of post in Archive? For example I would like to have title above image and meta data under excerpt. I see that I cannot change layout order or I don't know how to do it. 

It would be perfect if there was an option to create post block layout and use it in Archive page. 
Or create own skin with Elementor Theme Builder and use it with Archive Posts.

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
