### ISSUE TITLE
Rendering content via Ajax - slider etc not working

### ISSUE THREAD

**Issue by ccdw** [pojome/elementor#4670]
Hey - Elementor support suggested I ask this question here.

I am rendering pages ( Elementor content) via Ajax. These pages include Elementor content.

Am using:

`$content = \Elementor\Plugin::$instance->frontend->get_builder_content( $post_id, true )`

Content and css is returned perfectly via Ajax for simple, passive Elementor content and it renders perfectly on the page. 

But, if contents contain more complex objects such as sliders, the sliders don't render properly and slider controls don't respond. Also, formatting not correct as it seems like some elements are  missing width and height styles too, which on normal pages are rendered inline in the style tag.

I am wondering, do I need to run some Elementor init code on the front end after I have added the template/page via Ajax?

Many thanks

**Comment by bainternet** [comment]
@ccdw 

It's not working probably because you are missing the slider CSS and Javascript which are enqueued when needed and triggered on load.

so you need to make sure your scripts and styles are loaded and trigger the JS initiate for your slider.

**Comment by ccdw** [comment]
Thanks @bainternet.

I can't find any front end JS documentation. Any ideas what JS function(s) I should be calling.

Currently calling:

elementorProFrontend.init()

Almost works, but video etc not formatting correctly. CSS and JS files loaded.

**Comment by ccdw** [comment]
@bainternet 

Can we reopen this please? Simply want to load Elementor pages via AJAX. You are doing it in the editor so I know it's possible. Just need some simple documentation.

**Comment by iShubhamRaj** [comment]
I am also facing same situation. Would like to know if there's a way to do it!

**Comment by zak87** [comment]
The same situation here. I don't know how to re-call JS after ajax load - without this carousel image, toggle widget. etc.. will not work.

**Comment by bentalgad** [comment]
Same Here! Big Problem :)

**Comment by willryanuk** [comment]
I'd also like some simple steps of how to load an elementor page dynamically over ajax, including how to get depending js/css, and then how to initiate everything on the client.

**Comment by zak87** [comment]
I have "almost" found a solution.

After Ajax return, if I call:

`elementorFrontend.init();`	

it works, but only if I call that function 1 time. If I call it multiple times, there are "troubles" - for example, Accordion widget is opening and closing the tab on 1 click. 

If I could call that function only "over the ajax returned html" probably it will work all fine.

**Comment by jazir5** [comment]
> I'd also like some simple steps of how to load an elementor page dynamically over ajax, including how to get depending js/css, and then how to initiate everything on the client.

Has anyone found a solution to do this?

**Comment by maxjutras** [comment]
elementorFrontend.init will break other feature such as the hamburger menu or any js event listeners. You should not use elementorFrontend.init()

Unfortunately, I didnt find any alternatives yet. We are screwed. 

Does anyone found a workaround for this?

**Comment by betzebu** [comment]
I created a own AJAX Filter and want to set the results in Elementor Posts Widget with Custom Query Filter Action. Everythings works fine, but I have to rerender the Posts Widget in Frontend to see the new results. 

Does anyone have a solution for this?

**Comment by m16averick** [comment]
Same problem here. :p I will write here after finding workaround, good case

**Comment by alexvibealex** [comment]
This is not working anymore , we want to load the elementor content via ajax call but the scripts and styles and configuration of elementor does not load for the page and  blocks on page does not work .

**Comment by alexvibealex** [comment]
anybody here ?????? 

We are getting Uncaught TypeError: Cannot read property 'tools' of undefined : 
at this line : StretchElement: elementorModules.frontend.tools.StretchElement,

elementorFrontend.init(); This is not working anymore , we want to load the elementor content via ajax call but the scripts and styles and configuration of elementor does not load for the page and blocks on page does not work .

**Comment by Faisalawanisee** [comment]
> I have "almost" found a solution.
> 
> After Ajax return, if I call:
> 
> `elementorFrontend.init();`
> 
> it works, but only if I call that function 1 time. If I call it multiple times, there are "troubles" - for example, Accordion widget is opening and closing the tab on 1 click.
> 
> If I could call that function only "over the ajax returned html" probably it will work all fine.

Works for me, 
Thanks alot @zak87

**Comment by alexvibealex** [comment]
elementorFrontend.init();
does not work each time , it needs some configuration data as well to work

**Comment by coadr93** [comment]
No fix for this still Elementor?
