### ISSUE TITLE
Portfolio Query - specific tags / categories instead of all

### ISSUE THREAD

**Issue by ShiftyTugboat** [pojome/elementor#4671]
I'm trying to filter out specific posts that relate to a certain topic for my site, but don't want to show the other tags/categories that don't relate to that portfolio.

Ex: I have 4 tags, "Gold,' "Silver," "Green," and "Blue," and want to have two portfolios on my page that distinguish between the full set, so that one portfolio only shows the metals, "Gold," and "Silver", while the other portfolio only shows colors. 

Currently, the portfolio query bar shoes every tag / category, regardless of input - it's all or nothing. 

Any way we can use the "Tags" or "Categories" entries to choose specific queries?

**Comment by Hanleymade** [comment]
It would seem that custom Portfolio template pages would be a need. No idea if anyone from Elementor is listening though?

**Comment by ShiftyTugboat** [comment]
Hmmmm.... Have you posted here before / know where else I could turn?

**Comment by ShiftyTugboat** [comment]
Still no word

**Comment by Hanleymade** [comment]
I just saw your comment. I would also look at Crocoblock or other plugins. It seems you have to look to 3rd party for more options.
