### ISSUE TITLE
[Question] How to change the prefix "elementor-" in all the class names?

### ISSUE THREAD

**Issue by reddykvishal** [pojome/elementor#4677]
I have been working with a client who doesn't want the elementor prefixed classes in the source code. 

I see that most of the classes with the prefix "elementor-" are in frontend.css but was wondering if there was an elegant way out to replace it rather than manually changing them all.

**Comment by bainternet** [comment]
Currently, this feature is not supported.

Thanks for the feedback.

**Comment by reddykvishal** [comment]
Thanks for your response!

Is this something the team is considering to add in future?
