### ISSUE TITLE
[Feature Request] Option to disable "Entrance Animations" on mobile devices 

### ISSUE THREAD

**Issue by hotboxprintstudio** [pojome/elementor#4678]
The option to have entrance animations is a great addition to Elementor... however, those animations are often not wanted when viewing on a responsive layout... anything below tablet size is usually where I want to disable the feature. -- It would be great to have the option to selectively add responsive styles entrance animations just like you can already do with margins, padding, etc.

**Comment by parfilov** [comment]
+1

**Comment by bainternet** [comment]
I merged this issue with  #1639, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by MacherTVPeter** [comment]
+1

**Comment by Tripples** [comment]
+1 Can anyone tell when the option will be available.
