### ISSUE TITLE
[Feature Request] Add all posts by author condition

### ISSUE THREAD

**Issue by ikovalyov** [pojome/elementor#4681]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to have unique post designs depending on authors

**Describe the solution you'd like**
I would be good to have option to check All posts by Author when publishing template. Right now I have to add every newly created post to the condition.

**Comment by bainternet** [comment]
We added By author condition in 2.1 Pro.

**Comment by ikovalyov** [comment]
@bainternet awesome, thanks.
