### ISSUE TITLE
Upload File form problem

### ISSUE THREAD

**Issue by ericft** [pojome/elementor#4682]
Hi,

The upload file form input is not working, any idea why?
Here's the error message:

_Upload directory is not writable or does not exist.
This Message is not visible for site visitors._

The directory used I assume is the wp-content/uploads? My permissions are 775

Thanks for your help

**Comment by bainternet** [comment]
The reason why is clear: "Upload directory is not writable or does not exist."

make sure that this path is writeable by your server
'wp-content/uploads/elementor/forms/'

**Comment by CUBICinfinity** [comment]
Thank you.
