### ISSUE TITLE
Unable to Display Dynamic Data from custom field groups located on ACF Pro Options pages.

### ISSUE THREAD

**Issue by notechup** [pojome/elementor#4683]
Not sure if this is possible due to the nature of the fields placed on the extra ACF Options pages, since they are stored in the wp-options DB (if I understood it right) instead of linked to a page or post.

I can assign the dynamic fields to the custom fields, however they don't display anything saved on the Options page.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


only options fields returned by `acf_get_field_groups` for v > 5.0.0 or via `apply_filters( 'acf/get_field_groups', [] );` for lower version.


Thanks for the feedback.

**Comment by danadalis** [comment]
I have the same issue as @notechup and i sure like to see you add this. In the meantime do you know any workaround to use get_field() from options 

This is syntax i belive

```
<?php

$variable = get_field('field_name', 'option');

// do something with $variable

?>
```

**Comment by bentalgad** [comment]
ACF Options page fields don't show nothing. tested with two different sites (latest version of Wordpress and Elementor).

**Comment by azlanjamal** [comment]
Hi, is there any update on this? I would like to see Options page fields be shown in Elementor as well. Thanks

**Comment by drewclifton** [comment]
Hi not 100% sure this is the same thing, but might be.

I have created a Group type ACF field, and would like to use data within that. In my case I have a text type subfield called "Resource Name" and a URL type subfield called "Resource URL" that I would like to use to create links to file resources.

**Comment by timotep87** [comment]
> Hi not 100% sure this is the same thing, but might be.
> 
> I have created a Group type ACF field, and would like to use data within that. In my case I have a text type subfield called "Resource Name" and a URL type subfield called "Resource URL" that I would like to use to create links to file resources.

I have the same problem here. If I have an ACF field (e.g. text) is inside an ACF of type 'group', then it is not visible from Elementor page builder in Dynamic Content.
Is it planned to fix this little issue?

**Comment by Computerbuddha** [comment]
> Hi not 100% sure this is the same thing, but might be.
> 
> I have created a Group type ACF field, and would like to use data within that. In my case I have a text type subfield called "Resource Name" and a URL type subfield called "Resource URL" that I would like to use to create links to file resources.

Yes, same issue here. Custom fields contained in an ACF type 'group' are unavailable in dynamic content.

**Comment by Foxgerman** [comment]
Same issue here. Need this functionality asap:-(

**Comment by alriksson** [comment]
What is the status on this? Group type is still unavailable and this is what we want to use to structure the meta fields in the cms.

**Comment by alriksson** [comment]
Come on guys, group fields and repeater fields! We need it to build the dynamic websites, dynamic is the future of wordpress!

**Comment by RoelofOtten** [comment]
Same issue here. Really need this functionality to make the backend more suitable for my customers

**Comment by luispedrogithub** [comment]
Same to me! 
+1 on this and also be able to use other ACF fields like the value of a group button ...

**Comment by andcha** [comment]
Wasted an hour making few groups and adding tons of fields only to realize elementor doesn't support this. Almost an year and no proper solution, why is elementor getting shi**y everyday?

**Comment by otobongarchibong** [comment]
It doesnt work. Group doesnt show up in elementor.

**Comment by austenosborne** [comment]
This is definitely needed.

**Comment by yourapiexpert** [comment]
Still within my grace period.  Just about to ask for a refund.  Elementor?  Come on guys...

**Comment by austenosborne** [comment]
Fwiw, I used accordions to group my acfs. Not ideal, and my setup wasn’t complex, but it did the job and the data became accessible to me in Elementor. HTH.   
  

  
  

  
  
>

**Comment by djekanovic** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> only options fields returned by `acf_get_field_groups` for v > 5.0.0 or via `apply_filters( 'acf/get_field_groups', [] );` for lower version.
> 
> Thanks for the feedback.

"Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it."

Jun 7, 2018

**Comment by Computerbuddha** [comment]
Please add this feature! Still not available? What is a "large demand"? Thanks!

**Comment by mjb2000** [comment]
Yep - This is needed. When can we expect it?
