### ISSUE TITLE
Change Pages within Elementor

### ISSUE THREAD

**Issue by wharminda** [pojome/elementor#4684]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
having to close Elementor to edit another page is frustrating

**Describe the solution you'd like**
An option to change to another page from within Elementor

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
