### ISSUE TITLE
Proper HTML Edit from Text Box

### ISSUE THREAD

**Issue by wharminda** [pojome/elementor#4685]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Inline HTML is a problem with Elementor

**Describe the solution you'd like**
There are 2x options currently if you want to add Inline HTML - use the Text box widget and in the Text tab, type your html - however, this is often lost when you change back and forth between the tabs or you can use an HTML box, but then you don't get to quickly add in text and format with things like hitting enter to add paragraphs or Shift+Enter for line breaks etc. It would be great to combine these and have the HTML tab as an option in the Text box widget.

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
