### ISSUE TITLE
Problem with translated Elementor

### ISSUE THREAD

**Issue by JoeDarko** [pojome/elementor#4686]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Recently Elementor started to display in my local language (Czech). The problem is, the translation is absolutely terrible. It makes Elementor much worse. I swear, it looks like it was translated with Google Translator. Or more like Bing translator.

And to add to that, some words don't fit into the interface, so its all broken.

I've contacted Elementor support and it seems like there is really no will to do anything about this and we, who are stuck with terribly translated versions or who prefer to use Elementor in english,  just have to live with it.

Forcing translated versions to non-english users, has, i think, two major problems.

1. Lot of people and most of the developers are used to english when it comes to web developement
2. Translated versions can be shockingly badly translated (Mine is.)

I understand using translated versions as defaut. Lot of people don't speak english, so badly translated version is better than english version.

But to force the translated version on everybody without giving them a choice to switch to the original english version is, at least for me, a huge pain.

## Solution

It would be SO easy to just add an option to the settings section to switch to English. It would just disable the translated language files or something like that and that would be it.

## Moaning

This is kinda making me hate working with Elementor. You have this amazing tool but somehow it was allowed to accept terrible translation with a ton of mistakes and there is no option to get rid of it.

And even if the translation was correct, it would still be a pain, because a lot of people are used to terms like "Border, Margin, Padding etc." and suddenly it's in my local language and i have to mentally switch from writing these terms in CSS to then seeing different terms in Elementor. 

There must be a ton of people who would prefer the english version but are forced to use translated version. And it would be so easy for you to just add one checkbox "Switch to English" and all the trouble would be gone.

**Comment by black-eye** [comment]
+1 
Same problem here (see #4653).
Czech translation is really bad, there should be some possibility to turn it off, at last until some revisions are made. 
Actually, now I can use this version only because I remember the original settings from before.

**Comment by srcek** [comment]
Croatian is also terrible. It would be so much better if I could choose the language I want to use. Something like selector 'Use system language', 'Choose your language' or 'Default (English)'.

**Comment by JoeDarko** [comment]
Ok, so today i tried to use some more intricate Elementor features and widgets and it was basically unusable, because i had absolutely no idea what half of the translated fields mean. PLEASE give us an easy option to switch to English.

**Comment by bainternet** [comment]
You can disable translations from loading via a filter but it must load before Elementor and Elementor Pro, so either via a [Must-use plugin](https://codex.wordpress.org/Must_Use_Plugins) or a plugin named something like: aaaa.php

```PHP
<?php
/*
Plugin Name: Force Lang
Plugin URI:
Description: Force Elementor panel Language
Version: 0.0.1
Author: Bainternet
*/
add_filter( 'plugin_locale', function( $locale, $domain ) {
	if ( in_array( $domain, [ 'elementor', 'elementor-pro' ] ) ) {
		return 'en_US'; // Or any other language you wish to force the panel in
	}
	return $locale;
}, 10, 2 );

```



Other than that, there is not much we can do about it unless WordPress changes the way it pulls/loads translations to let you select which translation to install and which one not to install. Which means the only solution I can suggest is to disable translations via a filter as described at: https://codex.wordpress.org/Configuring_Automatic_Background_Updates#Translation_Updates_via_Filter

```PHP
add_filter( 'auto_update_translation', '__return_false' );
```

But this means that all translations will not update and not only Elementor but you wont have to delete the files every time there is an update.

As for 

> PLEASE give us an easy option to switch to English.

Even If was not simple but at least possible we would have implemented it, but currently its just not possible, for all of the reasons mentiond here so many times.

Hope this helps.

**Comment by black-eye** [comment]
Honestly, I think the solution would be not to publish the translations that are made in a great hurry and just for the sake of placing a check mark beside the next laguage. Recently, there was a post on Elementor's Blog summing up Elementor's 2 years history with one hightlight saying that it's in 10 most translated plugins. I'm afraid, that this statement was the main reason, why there was the need to publish these new translations as soon as possible no matter what the quality was.

Please consider postponing these translations until they get mature. I also think that it would be usefull to start a discussion whether we need to translate technical terms like CSS attributes, which is sometimes very confusing. I went to plugin's translation page but didn't find a place, where I could start such a discussion or to comment approved translated terms.

Elementor is a great tool, but sometimes you add new stuff too fast, when it's not ready for a production yet.

**Comment by JoeDarko** [comment]
All the chalenges you had to overcome and you can't come up with a solution to switch Elementor back to English? If you can translate plugins by other translation plugins, why can't Elementor translate itself? If you delete the translation files, Elementor reverts back to English. So can't you just add some function that blocks these files if the user prefers English?

For many people Elementor is a developer tool that is closely related to other web technologies. Forcing translated versions onto every user is like telling coders that from now on they have to start using programming languages in their native language and relearn all the terms they were using for years.

If you guys had to use some non-english version as developers, i'm sure you would find a sollution pretty quickly.

**Comment by bainternet** [comment]
Thank you for your feedback.

**Comment by srcek** [comment]
Would it be possible for Elementor to choose it's interface language from the language set on the profile page of each user? That way, globally, Elementor would use site language but individual users could change that in their profile according to their personal preference.

**Comment by black-eye** [comment]
@bainternet Unfortunately your mini plugin didn't work for me, I don't know why.

Fortunately I've found something else:
```
function bleye_unload_textdomain_elementor() {
	unload_textdomain( 'elementor' );
	unload_textdomain( 'elementor-pro' );
}  // end function
add_action( 'init', 'bleye_unload_textdomain_elementor', 100 );
```

This worked for me, I hope it's not something of bad habit.

**Comment by margu9** [comment]
I tried all the solutions, and they didn't work. I.e. I deleted .po/.mo files and Elementor was still in the wrong language. How the hell was that possible, I asked myself...

After extensive fiddling, I found out that it's because I use WPML plugin, and that "it keeps it's own translations somewhere"; in lack of a better way to express myself.  **I went to _WPML->String translations_ page and deleted all strings under _elementor_ and _elementor-pro_ domain, and that fixed it.** 
Elementor was English only from that point on. So, If you use WPML and these solutions have not worked, try it. :)

**Comment by lirdis** [comment]
> @bainternet Unfortunately your mini plugin didn't work for me, I don't know why.
> 
> Fortunately I've found something else:
> 
> ```
> function bleye_unload_textdomain_elementor() {
> 	unload_textdomain( 'elementor' );
> 	unload_textdomain( 'elementor-pro' );
> }  // end function
> add_action( 'init', 'bleye_unload_textdomain_elementor', 100 );
> ```
> 
> This worked for me, I hope it's not something of a bad habit.

I've been living with this problem for ages - following the other issue (#5148 ), and finally tried this - Works like a charm! Thank you thank you thank you :-)

**Comment by vsosp16** [comment]
Provided solutions seems to working at first **but no**. There are some translations in local language and there some english original texts in the elementor editor. When i activate a plugin or mu plugin. Or i add the other snippet to funcitons.php of helle child theme.

I will give an example of bad translation and you will unterstand it better.
I saw a translation of "Breadcrumbs" to "Sümüklü böcek" which means "escargot" in my language. We are hangin out with Escargots instead of divs and css properties or "how to design this" we see escargot there...

Please bring a proper fix for that crazy problem.

**Comment by amelsens** [comment]
Hi,
I found myself the following solution that works for me.
Anyway, if you want to use Elementor in the standard English language, you don't need any translation files at all.
So, why not simply delete all the Elementor translation files?
I tried it with the simple PHP code below:
`$files = glob('wp-content/languages/plugins/elementor-*.*'); // get all file names
foreach($files as $file){ // iterate files
	if(is_file($file)) {
		unlink($file); // delete file
	}
}
`
You can put this code in a plugin in the mu-plugins folder or as I do, using the great free Snippets plugin.
Even after an update or an upgrade of Elementor, the next time you will use Elementor should work in English.

**Comment by Czechu1992** [comment]
The following code turns off the editor language for a specific language. In my case it's Russian. Now when editing Russian pages, the editor is in English, other languages are normal e.g. Polish.

`function cs_unload_textdomain_elementor() {
	if ( is_admin() ) {
		$currentLanguage  = get_bloginfo('language');
		if ( $currentLanguage == 'ru-RU') {     //Replace the language code
			unload_textdomain( 'elementor' );
			unload_textdomain( 'elementor-pro' );
		}
	}
}
add_action( 'init', 'cs_unload_textdomain_elementor', 100 );`

**Comment by TedChenNZ** [comment]
hi @nicholaszein 
I saw that you closed https://github.com/elementor/elementor/issues/9147#issuecomment-1322916231 and merged it with this ticket, however they seem to be unrelated?

This ticket is around translations, whereas 9147 is around keeping the original filename of attachments.

**Comment by nicholaszein** [comment]
Hello @TedChenNZ,

yes, I made a mistake. My inner dyslexic self took in for a moment and I ended up mixing #4868 with #4686. 😅

I fixed the mistake right away, but GitHub made sure it would be displayed for eternity. 🤦‍♂️

Sorry for that! All good now. Thanks for the feedback though! I appreciate it! 🙂
