### ISSUE TITLE
[BUG] Possible CSS bug when 2 adjacent sections have fixed backgrounds in Chrome 67+

### ISSUE THREAD

**Issue by hotboxprintstudio** [pojome/elementor#4692]
## Problem:
After the latest update to `Elementor v2.0.15`, I am noticing a new issue with my sections that contain fixed backgrounds while scrolling in `Chrome Version 67.0.3396.79 (Official Build) (64-bit)`. This issue seems to be isolated to Chrome only as far as I can tell via my testing. 

What happens now is a small white gap will appear when scrolling back up the page where the sections with fixed backgrounds meet one another... Since this is virtually impossible to explain without documentation Ive created a small screen recording of what I mean. I hope this helps to illustrate my problem.

```
Wordpress Version 4.9.6
Elementor v2.0.15
Chrome Version 67.0.3396.79 (Official Build) (64-bit)
```
## Documentation: 
Chrome Example - https://youtu.be/E_M5w9l4we0
Firefox Example - https://youtu.be/lRgJXEcx9R0

> As you can see, everything behaves as it should in the current version of Firefox. This is how it used to behave as well in Chrome 66+... after the 67+ update and the new Elementor update is when the issue arose.

*Disabling `background-attachment:fixed;` in Chrome - https://youtu.be/dJpCWhLMxqw

> To help illustrate why I believe this is a CSS / Chrome related issue now, here is a video displaying how the issue goes away if I disable background-attachment:fixed; ... While I was able to discover this, I could not really find what the opposing CSS or element was that is causing this. Hopefully someone much smarter than myself that actually knows web development can sort this out!

*Hovering over a button causes even LARGER issues in Chrome! - https://youtu.be/SLIOVnRNc9c

> Upon doing more testing I discovered that the bug is far worse than it originally appeared.... 
> If I hover over a button in another section it seems to exacerbate the issue even more and cause the white bar to completely take over the background of the fixed background section. You'll see it also causes the adjacent section with a fixed background to shift the background around while hovering. 

Thanks for the help! 
-SB

**Comment by srcek** [comment]
I have similar problem. Background fixed image doesn't display at all in desktop mode. But when media query switches to tablet or mobile css it's visible again. Only on latest Chrome. Other browsers are fine.
Also had a white bar on one site as you described above.

**Comment by hotboxprintstudio** [comment]
Yeah, the only way I can find to fix the issue temporarily is to set the background images to scroll or default instead, but of course that ruins the entire aesthetic of the section and kills the effect your trying to achieve. Hopefully this will be addressed in the next update. I cannot find an offending plugin either. Im pretty certain that this a combination of the two new updates between Chrome and Elementor.

**Comment by bainternet** [comment]
Seems like a Chrome bug:

> It is an issue specific to only Chrome 67 (I have Version 67.0.3396.79 (Official Build) (64-bit)). Validated by going back to previous version and vice versa.  So basically any site you designed with parallax effect is going to look like crap in chrome (used by 62% of users by the way) when users receive the 67 version (which is occuring now). 
> I only noticed this as I was in the midst of launching a site, and it worked great, then with no changes, it didn't.  Found out browser got the 67 and is why. 
> Unless Google fixes this in there browser you will need to go back to every site you produced and add that silly css to it. 

```CSS
 transform: translate3d(0,0,0);
-webkit-transform: translate3d(0,0,0); 
```
from stackoverflow:

> Using -webkit-transform: translate3d(0,0,0); will kick the GPU into action for the CSS transitions, making them smoother (higher FPS).Note: translate3d(0,0,0) does nothing in terms of what you see. it moves the object by 0px in x, y and z axis. It's only a technique to force the hardware acceleration


 By the way, you can download older versions here https://www.chrome-portable.com/index.php/google-chrome-offline-installer.  Just do a search for how use an older version once downloaded. 

Ref: https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chrome/DC4IFvGXdIA/2iySIb1oAgAJ

**Comment by hotboxprintstudio** [comment]
So this issue is actually caused by the _CSS transitions_??
Where exactly are you recommending the use of: ???
```
 transform: translate3d(0,0,0);
-webkit-transform: translate3d(0,0,0); 
```

Just a global style on across the site on something like the `body` tag? 

Thanks for the help.
Shaun

**Comment by hotboxprintstudio** [comment]
So for future reference, I can confirm this does seem to remedy the problem.. but its def more of a bandaid than it is a solution obviously. Also, it causes scrolling to seem less smooth and kinda choppy now, but the flickering is gone finally. Im probably going to opt to just remove background fixed instead for performance reasons. Im not using a true parallax effect for those sections, its only set to fixed.

**Comment by anthonyryanrusso** [comment]
Why is this issue closed if it's not fixed?

**Comment by amindiary** [comment]
yeah, agree, **Why is this issue closed if it's not fixed?**

**Comment by bainternet** [comment]
Because it's a bug in chrome and not Elementor.

**Comment by amindiary** [comment]
@bainternet fair enough. understood
