### ISSUE TITLE
Blocking activation, updates and templates from Russia

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#4694]
Hello!
You maybe already know about this issue but I get a lot of messages from my subscribers almost every day and I think that we should think about it together.

## The beginning of the story
On the April, 16 2018, Russian government has [begun to block](https://en.wikipedia.org/wiki/Blocking_Telegram_in_Russia) Pavel Durov's (vk.com founder) Telegram messenger. Over 10000 IP were blocked because Telegram uses Amazon and Digital Ocean platform for it's work.

## Essence of the problem

- Elementor cannot be activate;
- Pro updates are invisible;
- Templates are unavailable and besides even in free Elemetor and even from own templates library. Only library modal with Elementor's logo and endless loading. No tabs with blocks and templates. (Unfortunately I have no screenshot. Lost them in dozens of subscriber's messages).

## Official data 
When I check myElementor's IP 104.18.42.228 in Russian state organization service
blocklist.rkn.gov.ru I see that this IP is in blocklist.

## Hosting issues
On the first days of blocking I had all the above troubles with my hosting in Russia and thought to move my project in Europe. I negotiated for a week with my hosting CEO and support. As the result, they changed traffic routes and everything worked. I think that it may be unlawfully and that it works is a matter of time. Also I think that they cooperate thanks to that I have the audience and I valuable partner for them.

Now I advice my subscribers to move to this hosting but not everyone wants and can to move. People says that want to get their money back for Elementor license and it's sadly.

## Possible solution
Maybe it can looks as utopia but... What if we'll make a plugin which will proxy my.elementor.com queries and can to bypass this blocks? I'll handle all Russian tutorials, if needed.

What do you think about it?

**Comment by bainternet** [comment]
@parfilov 

Thanks for reporting,
We are aware of this and still looking for a helpful solution.

As for proxy, there is no need for a plugin since its already built-in WordPress via wp-config.php

```
/* Configure proxy Server */
define('WP_PROXY_HOST', 'HOST');
define('WP_PROXY_PORT', 'PORT');
define('WP_PROXY_USERNAME', 'USERNAME');
define('WP_PROXY_PASSWORD', 'PASSWORD');
define('WP_PROXY_BYPASS_HOSTS', 'localhost');
```

which is currently the only real solution, untill Russia desides otherwise.

thanks again for reporting.

**Comment by parfilov** [comment]
@bainternet I tried this and maybe I've got bad proxy server, but it doesn't worked for me. I'll try with another. Thanks!
