### ISSUE TITLE
Option to see post source code / text view to manage template and CSS

### ISSUE THREAD

**Issue by Hanleymade** [pojome/elementor#4695]
Currently Elementor only allows Admin / post creators to look at either Elementor front end or Wordpress Editor backend views.
There are instances where I actually would like to see and manage the Elementor code in a text format. 
For example, 

1 - There is a section or column I want copy & paste into another page. Currently I have to save that section or column as a template, then insert into another page. I would also like the option to copy a code snippet to paste elsewhere.

2 - there is some CSS code and I want to adjust in text format and not using the Elementor front end element widgets. I could adjust and copy CSS text quickly and easily this way.

3 - there is a layout issue which I could fix if I were looking at the actual CSS and move around or delete CSS as well. Additionally, it would show the Developer the Elementor CSS page hierarchy / structure.

Currently I would have to use a 3rd party plugin like YellowPencil to determine specific CSS areas in the layout to adjust and that's just another place to put more CSS rather than keep it in one central location.

Could there be a 3 button which allows Admin / post creators to look at code directly that include Elementor code.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Also next time,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.


Thanks for the feedback.

**Comment by Phill** [comment]
I currently have a problem where there are a bunch of <b> between sections causing problems. In Elementor there is no way to fix them. I think it was causes from saving the page in the WordPress editor to update a plugin that doesn't update from Elementor.

So I have to edit the data in the database directly to fix it.
