### ISSUE TITLE
Video-Post-Widget

### ISSUE THREAD

**Issue by tscheipi** [pojome/elementor#4696]
Hi,
what about a  video-post-widget: I´d like to have the post-widget extended with the ability  to show the video of the post instead of the featured image and by clicking on it the video opens in the lightbox.
Cheers

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
