### ISSUE TITLE
[Feature Request] Ability to set conditions for Woocommerce Product Post Type

### ISSUE THREAD

**Issue by Ver3** [pojome/elementor#4697]
Use case: I need to create a less distracting header for WooCommerce Products only. "Posts" and "Pages" are in the list "Products" (or other CPT's) are not there (yet).

Strangely I'm able to get get a customer header for products by setting conditions to 'entire site' then other conditions for the other post types. This is not a clear and clean way to do it though.

Please consider this for the upcoming big Woo update for E-Pro (or just the conditions sooner).

Cheers!

**Comment by Hanleymade** [comment]
Definitely need more integration with Woocommerce by Elementor.

**Comment by bainternet** [comment]
Duplicate of #4475
