### ISSUE TITLE
[BUG?] Fail to re-enable Elementor's defualt fonts & colors

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4698]
## Prerequisites

 - [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
 - [x] The issue still exists against the latest stable version of Elementor.

## Description
Default Elementor fonts & colors do not recover after uncheck.
1. Using Elementor & Pro with Elementor Hello Theme.
By default Elementor's defualt fonts & colors ARE ENABLED
2. Modify default color plate to my need.
3. Uncheck - just to see what other definitions are there
4. Check again

The color plate shows my definitions (step 2)
BUT the post/pages on site takes color from frontend-rtl.css
And NOT from global.css (if I remember the file name corectly)

## Steps to reproduce

See above.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
[https://pastebin.com/0wDzfWn3](url)
</details>

**Comment by bainternet** [comment]
@Mulli 

We can't replicate.

Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by Mulli** [comment]
Thanks.

I will.

Also added a new issue (in my mail- not Github) that Sticky option for Header area does NOT appear.

 

Best

Mulli

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal
