### ISSUE TITLE
Event Calendar

### ISSUE THREAD

**Issue by get8bit** [pojome/elementor#4700]
I've been trying to use The Event Calendar by Moderntribe plug-in with Elementor, and it looks terrible.

I have to pay a developer to fix it for me. Elementor is supposed to be easy for non-developers.

I really believe Elementor should have their own built in event calendar.

**Comment by Hanleymade** [comment]
Event plugins are complicated. Elementor is just starting to offer dynamic integration, so not surprised that this is still not integrated.

I doubt that Elementor will offer a built in calendar, but maybe a 3rd party will find a way to build a plugin that works with Elementor.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by get8bit** [comment]
Still no way to add a Calendar? Events Calendar has 700,000+ active installations. I can't be the only one with clients that advertise events.
