### ISSUE TITLE
How to enqueue scripts (JavaScript files) in the Elementor edit page screen?

### ISSUE THREAD

**Issue by mdjwel** [pojome/elementor#4702]
I wanna enqueue some scripts (JavaScript files) in the Elementor edit page screen. Probably there are available hooks to do that. But I couldn't find it.
Can you help me, please by referring the way?

**Comment by bainternet** [comment]
here you go:

https://github.com/pojome/elementor/blob/master/includes/editor.php#L475
and 
https://github.com/pojome/elementor/blob/master/includes/editor.php#L706

enjoy.
