### ISSUE TITLE
Show what user edits using the inline editor in the side editor

### ISSUE THREAD

**Issue by ArekZw** [pojome/elementor#4704]
## Prerequisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It makes it easier for users to know which field (and context, field description with tips and instructions) they are editing. Some fields are not available for editing as an inline editor (like thumbnails). By clicking the box next to the thumbnail, you can easily edit the thumbnail in the side editor.

It also helps in editing fields that are not available for the inline editor for technical reasons (e.g. to field is assigned "click" event as in accordions, tabs) and it is not possible to open the inline editor.

**Describe the solution you'd like**
When user click item element to inline editor, in sidebar:
1. If field is in repeater -> item in repeater opens and the field is highlighted for a moment. 
2. If field not in repeater -> field is highlighted for a moment

+ if it's possible, user should be scrolled to field or item

**Describe alternatives you've considered**
I do not have any alternative ideas

**Additional context**
![zrzut ekranu z 2018-06-09 13-22-00](https://user-images.githubusercontent.com/11788346/41191342-45229c80-6bee-11e8-9f61-4f533a54d02a.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
