### ISSUE TITLE
I want to make my theme compatible with Elementor.

### ISSUE THREAD

**Issue by zeetheme** [pojome/elementor#4705]
# I want to make my theme compatible with Elementor.

Hello, 

I am Vishal Ranjan. I am a WordPress theme developer.

I have been working on a WordPress Theme for 5 months - [WhiteDot](https://whitedot.zeetheme.com)
WhiteDod is a free and open source theme. Here is the [Github Link](https://github.com/zeetheme/whitedot).

I have submitted the theme to be included in the official WordPress Theme directory. And the theme is under review, and will be approved in a few weeks.

## I want WhiteDot to be 100% competeble with elementor
I want to included Elementor built-in with my theme. And i have read this article on Elementor Docs - [Article](https://docs.elementor.com/article/124-is-elementor-compatible-with-all-wordpress-themes).

I have previously sent an e-mail regarding this, and I got this answer -

```
Hi Vishal,

Thank you for contacting us. 

Since this is more of a development question you should check with our Github project page a developer there should be able to provide you with those answers.

Kind Regards
```

So please provide me assistance in getting compatibility for my theme.

**Thank You**

**Comment by bainternet** [comment]
@zeetheme 

You are more than welcome to make your theme Elementor compatible.

here is our developer docs on theme locations api
https://developers.elementor.com/theme-locations-api/

**Comment by rkrules** [comment]
I don't get Elementor options on this theme, but I see the theme description includes that it is compatible with Elementor

**Comment by zeetheme** [comment]
Hello @rkrules 
Are you talking about customizer options?

You do not need any options for the Elementor Plugin to work in a theme to make it compatible. My theme is compatible with Elementor. Just install the plugin and start creating beautiful pages with the page builder.

**Comment by rkrules** [comment]
Hi .. I have installed Elementor plugin and activated. I updated whitedot.  When I add page or edit page, I don't get option to edit with Elementor, only the WP editor (gutenberg). I have self hosted and logging in through that portal. Any pointers to how to debug.
