### ISSUE TITLE
not full page

### ISSUE THREAD

**Issue by acrnium** [pojome/elementor#471]
Hello.
Help set up the plugin. When you create a page Elementor, the page itself with a standard template head. How can I get rid of it?
![6](https://cloud.githubusercontent.com/assets/21347115/18107260/e7e06c28-6f0f-11e6-9143-daa9d1387522.jpg)

**Comment by WPDevHQ** [comment]
This can be marked as resolved by: [WPORG Forum Thread](https://wordpress.org/support/topic/not-full-page)
