### ISSUE TITLE
Changing the column width in tablet and smartphone mode

### ISSUE THREAD

**Issue by Tim2468** [pojome/elementor#4714]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Unfortunately, in tablet and smartphone mode, the width of columns cannot be adjusted visually by moving them with the mouse. You must use the input fields instead

I think it's very good that the width of the columns can be moved visually with the mouse when you're in desktop mode.
Unfortunately, this is not possible in tablet and smartphone mode. Here you have to estimate and use the input fields for the column width.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
