### ISSUE TITLE
Columns Element - Cannot re-use inner-columns-section template as inner-section again

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4715]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When saving an inner-section as a template you can only use that template as an outer-section as there is not option to import within a section.

So let's say I create a 2-column section and add inside the first column another 2-column inner section using the "columns" element. I add elements like some text and a few buttons and I style the inner-columns with some padding/margin and background colors.  I then choose to save the inner 2-columns as a Template but if I want to use this elsewhere there is no way to get this inside an existing section and only imports as an outer section.

## Steps to reproduce

1. Create a section
2. Drag in Columns
3. Save the columns section as a template
4. Try to import that template and get it back inside another section, impossible (unless you use the template widget elements instead of course)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

All environments

**Comment by bainternet** [comment]
@pingram3541 

Currently, this feature is not supported, when you can only save sections or widgets, not columns.
look at your step 3:

> Save the columns **section** as a template

Which means you are saving a section, not columns and section can't be inserted inside a section.

But in next version (major 2.1) we are addressing this via a simple copy & paste.


Thanks for the feedback.

**Comment by pingram3541** [comment]
Thx for the response.  Totally get it but still, when using columns, there ARE sections within sections (only 1 level deep of course) and those sections within sections allow to be saved as a template so that is what's misleading.

If the objective is to use the template just as it was saved, as an inner template, it cannot be done unless you saved the entire outer section instead containing the target "inner" section that is truly desired, then import that template, move the inner section where desired and delete the shell it came in.

I thought I'd mention at least this work around for any others that may stumble.  Super excited for the copy feature!
