### ISSUE TITLE
Toolset Responded To Elementor Integration

### ISSUE THREAD

**Issue by DrMohamedGamal** [pojome/elementor#4716]
This is a response from Toolset side

Please cooperate to achieve the integration as fast as possible
 
![34859475_2028029467446136_8428982131396444160_n](https://user-images.githubusercontent.com/34522710/41206204-f70cb31e-6d00-11e8-9ed1-7aea19928036.jpg)

**Comment by bainternet** [comment]
@DrMohamedGamal 

I just came out of a very productive meeting with a few guys (and a lady) from toolset and we are working together to provide an integration on one level or another.

thanks for your feedback.
