### ISSUE TITLE
Select a Section with a double click

### ISSUE THREAD

**Issue by Tim2468** [pojome/elementor#4717]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

It should be possible to select a section by double clicking on it.
If I set a negative margin-top on a section so that it can be above another section, I can no longer reach the options bar of the lower section, so it would make sense to be able to call a section alternatively with a double click.

**Comment by bainternet** [comment]
@Tim2468 

In the next version (major 2.1) we are addressing that via right click.

thanks for the feedback.

**Comment by Tim2468** [comment]
Thank you :)
