### ISSUE TITLE
Post Archive Page Builder: Use certain amount of the Post Content if there is no Post Excerpt

### ISSUE THREAD

**Issue by haemeulrich** [pojome/elementor#4721]
Most of the themes I know are using the first to be defined amount of characters in the Post Archive Page if there is no Excerpt within a post. This would be a great option to have also in the Archive Page Builder. Today you get no content if there is no excerpt within a post.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As far as we know, We use the same function as any WordPress theme to get the Auto-generated excerpt `the_excerpt()`.

which means as long as you have text content in your post you should get an excerpt.

**Comment by haemeulrich** [comment]
Thank you @bainternet for your information! And I'm so sorry that I gave not all the required information.
I wanted to make a screen recording for you then I found that I didn't understood the widget. The Post Excerpt widget is not for building archive pages only for single posts. So my request doesn't make sense.
