### ISSUE TITLE
heading widget not displaying dynamic content in single template

### ISSUE THREAD

**Issue by fontaholic** [pojome/elementor#4724]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
first time bug reporter, so excuse my innocence. 

I have created a single template using the beta ACF integration. When I try to put dynamic content into a heading widget, it does not appear in the preview or on the site. When I try to put the same content in with a text widget, it works.

<img width="1762" alt="elementor-heading-widget-bug" src="https://user-images.githubusercontent.com/5061292/41243514-5350964e-6d70-11e8-8e47-f110dcf87167.png">

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Other than that, it looks like you are actually setting the Link field instead of the Title.
