### ISSUE TITLE
Vertical column text boxes.

### ISSUE THREAD

**Issue by scorpiknox** [pojome/elementor#4727]
Best practice for UI limits designers to ~65 characters for text. Right now we do this by adding 2 or more columns in a section and adding separate text widgets, one per column. This can cause layout issues if the text is later edited. 

It would be nice if we could split up a single text widget's content by columns. I know I could do this by adding a table to the text field, but that is not a great solution.

Thanks!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
