### ISSUE TITLE
Allow icons to be added to menu items

### ISSUE THREAD

**Issue by ShadowXVII** [pojome/elementor#4729]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Not able to easily add icons to menu items.
Icons allow for more customizable menus.

**Describe the solution you'd like**
An icon should be assignable to menu items in the standard Wordpress Menu editor.

**Describe alternatives you've considered**
Using HTML in the description is dirty and doesn't display properly.
CSS on each item is difficult to maintain and still suffers from layout issues.

**Additional context**
Other themes leverage the CSS Class feature, but this is dirty.
Perhaps something similar to https://wordpress.org/plugins/menu-icons/? The plugin could work, but it'll include more icons sets than necessary.

**Comment by bainternet** [comment]
You can already add Icons if you manually add the markup in the menu Item navigation label, ex:

![ok2auyx](https://user-images.githubusercontent.com/660572/41283184-9b2d03b6-6e3e-11e8-9948-5ccb2cf8a947.png)


![87lhwha](https://user-images.githubusercontent.com/660572/41283193-9dc5b5a0-6e3e-11e8-8475-74f05bb4285b.png)


Or use the plugin you mentiond and if you use FontAwesome icons then you can deregister the plugin's FontAwesome style so you wont have unnecessary icon sets.

other than that, currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by ShadowXVII** [comment]
Both aren't great implementations and have their own limitations.

Keen to see something with a bit more polish and continuity from the elementor team.

**Comment by PieterT2000** [comment]
Thanks @bainternet !

**Comment by AlfaBlue** [comment]
This is a very limited way to add an icon to a menu item. What about the item changing color on hover?
It would be a great idea for the Elementor team to add this to the "Nav" Element.

**Comment by webenadam** [comment]
+1 To add this feature and not reply with ways that aren't really supported by the plugin.

**Comment by MustafaBKLZ** [comment]
Still wait

**Comment by phkoon** [comment]
@nicholaszein Hello! 
bainternet closed the thread, but it's not resolved. Could you inform us if Elementor's team has acknowledged this to be implemented or if there's any feature request being worked on for this to be implemented?

Thanks in advance and merry christmas!
