### ISSUE TITLE
Fallback image background is not working.

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#4732]
Is it just me or this is a general issue?

I set up a dynamic image background with fallback image, it shows in edit mode but when I preview it is not showing.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by jonathanarbely** [comment]
This still doesn't work in combination with ACF. The fallback background image never shows. This has been an issue for months now.

**Comment by mattskeoch** [comment]
Still not working when using with ACF.

**Comment by jthouse27** [comment]
Dang it. Good to know that I can stop searching for a solution, but I really wish there was a solution…

**Comment by jason3by2** [comment]
Amazed that this is still an issue and not resolved.

**Comment by kostasmichalaros** [comment]
WOW..... still nothing...

**Comment by costaDario** [comment]
I discovered what was wrong in my case. 
In ACF, you can choose if the image is an array, an URL or an ID. 
The first one will make Elementor work when setting a fallback image, while the other two won't. I have no idea about why it happens. 
Tested with Wordpress 6.2.2, Elementor 3.15.3, Advanced Custom Fields 6.2.0

**Comment by jthouse27** [comment]
> I discovered what was wrong in my case. In ACF, you can choose if the image is an array, an URL or an ID. The first one will make Elementor work when setting a fallback image, while the other two won't. I have no idea about why it happens. Tested with Wordpress 6.2.2, Elementor 3.15.3, Advanced Custom Fields 6.2.0

That makes a lot of sense!

**Comment by mainiomooses** [comment]
> I discovered what was wrong in my case. In ACF, you can choose if the image is an array, an URL or an ID. The first one will make Elementor work when setting a fallback image, while the other two won't. I have no idea about why it happens. Tested with Wordpress 6.2.2, Elementor 3.15.3, Advanced Custom Fields 6.2.0

Confirmed this behaviour. Seems Elementor, when considering whether or not the fallback image is required, assumes that the ACF image field would always return an Object. If you set the image field to return just the file URL or the attachment ID, Elementor stumbles and does not resolve to the fallback image if the image field is left empty. 

Note: Elementor correctly uses the image set in the field even if you use id/URL as the return, but the fallback of falling back on the fallback falls... on it's back.
