### ISSUE TITLE
Portal Tabs and Accordions Unique ID

### ISSUE THREAD

**Issue by anupamapadma** [pojome/elementor#4734]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anupamapadma** [comment]
Would like to add unique link IDs for each Tab or Accordion. This would be useful so we can link to certain sections of content rather than link to the entire page. I read it's somewhere in the roadmap... I'm wondering when exactly it's planned to launch.

**Comment by bainternet** [comment]
@anupamapadma 

Don't know where you have read it, but it is currently only possible via some custom JS,
ref: https://github.com/pojome/elementor/issues/2993

as for accordion should be the same but trigger `focus` event on the desired accordion item.

thanks.

**Comment by cleverstas** [comment]
For this you need to know the id of the tab title.

![image](https://user-images.githubusercontent.com/34838337/50040644-acef5980-0058-11e9-99ad-2222618d175d.png)

Next you need to copy it and make an anchor link.

![image](https://user-images.githubusercontent.com/34838337/50040652-e758f680-0058-11e9-91b2-84c9530c55e5.png)

Easy!)
