### ISSUE TITLE
Manually Select Specific Tags for Portfolio Query

### ISSUE THREAD

**Issue by ShiftyTugboat** [pojome/elementor#4735]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm trying to filter out specific posts that relate to a certain topic for my site, but don't want to show the other tags that don't relate to that portfolio. Ex: I've got a parent category for content, called "style," which has two sub-categories of sorts, 'colors' and 'metals.'

I have 4 tags, "Gold,' "Silver," "Green," and "Blue," and want to have two portfolios on my page that distinguish between the full set, so that one portfolio only shows the metals, "Gold," and "Silver", while the other portfolio only shows colors.

Currently, the portfolio query bar shoes EVERY tag / category, regardless of input - it's all or nothing.

Any way we can use the "Tags" query entry to choose specific tags without needing to create duplicate posts?

**Describe the solution you'd like**
Selective query based on on individual/manually selected tags

**Describe alternatives you've considered**
I've made duplicate posts with different tags, but the tag title and duplicate post always show up in any portfolio I attempt to make.

**Additional context**
I had this as a previous post, but was unsure that I had created it in the correct fashion, so this **is a repost** of my previous attempt.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
