### ISSUE TITLE
Portfolio Pagination

### ISSUE THREAD

**Issue by vopulo** [pojome/elementor#4736]
Hi, please add portfolio pagination.. i have hundreds image portfolio, and my web become slow when accessed that. I think pagination will reduce and make more faster load. Thanks

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by SniffleValve** [comment]
There is really no need to to provide the requested information.
It is a very simple and obvious request.
The request is to provide pagination on the Portfolio widget as is provided on the Posts widget, for the exact same reason :) 
Simple :) 

Cheers!
Lyle

**Comment by BarbWolfe** [comment]
@SniffleValve Did you ever get an answer from them? I'm having the same issue.
Barb

**Comment by BarbWolfe** [comment]
@bainternet 
What's the answer to the Elementor Portfolio Pagination question?  How do we make multiple pages on one portfolio category type?

**Comment by senator94** [comment]
This seems like a no-brainer. We need pagination for the portfolio widget. I have clients with massive photo galleries.
