### ISSUE TITLE
[Feature request] Ability to export code generated for single page/post or element

### ISSUE THREAD

**Issue by srcek** [pojome/elementor#4743]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
My feature request would enable designers to use Elementor for generating code for sites or pages not based on WordPress.

**Describe the solution you'd like**
It would be awesome if I could export static code for posts/pages or elements I built in Elementor. Interface would function exactly like it is now with the added option to "Save as HTML/CSS" or something similar. Code would be downloaded in a single structured zip file with all the assets necessary to display static design.  

**Describe alternatives you've considered**
Alternative would be to use such generator on your latest builder competitors site. But, I'd prefer if you would offer similar option. 

**Additional context**
I love to work with your builder. Such capability would be great in situations when I have to create some design not related to WordPress and I'd still like to use Elementor.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by cWatto** [comment]
+1 being able to export specific templates like header/footer to HTML would be great.
Say you have different sites and want to keep the header the same across non-wordpress installations to create a cohesive viewing experience. This definitely feels like a necessary feature.

**Comment by salvimateus** [comment]
it is a must have
+1

**Comment by fal90210** [comment]
Definately must have feature!
