### ISSUE TITLE
Metabox on templates disappear when activating PRO 

### ISSUE THREAD

**Issue by Kru-x** [pojome/elementor#4747]
Themes meta-box on Elementor templates disappear as soon as Elementor PRO is activated and I have been told by support that it is turned off. Not good if the PRO version mess with WP core functions  in this case the (GeneratePress) themes functions! I paid to make it more functional not less!

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
