### ISSUE TITLE
Metabox disappear when Elementor pro activated

### ISSUE THREAD

**Issue by Kru-x** [pojome/elementor#4749]
Prerequisites:
Themes meta-box on Elementor templates disappear as soon as Elementor PRO is activated and I have been told by support that it is turned off. Not good if the PRO version mess with WP core functions in this case the (GeneratePress) themes functions!

Installation environment:
1. WP with theme GeneratePress
2. Elementor plugin
3. Elementor PRO
All installed on a "clean" install 

Steps to replicate:
Open a Elementor template when Elementor PRO is activated and GeneratePress's layout metabox is shown, a WP core function on all pages and posts and templates and even Elementors "non" pro templates.

Activate Elementor PRO and the layout meta box disappear!

Isolating the problem:
??? The above is the problem!

System info:
Below is my server environment, but I do not believe that is an issue as I have tried other environments and the same thing happens there!
Operating System: Linux
Software: Apache/2.4.10 (Debian) 
MySQL version: 5.6.34 
PHP Version: 7.2.0

**Comment by bainternet** [comment]
@Kru-x 

thanks for clarifying,

We have done compatibility work with GeneratePress and since our templates don't use his layout settings it is removed.

So not a bug, more of a feature.

thanks.

**Comment by Kru-x** [comment]
Hi Raz,

Feature? I don’t get it, GP uses standard Wordpress layout’s and is one of the popular theme out there. In Elementor free I can use it but not in PRO, something I have paid for? So what theme do Elementor suggest we should use with Elementor PRO? Is there a compatibility chart where I can see what theme is working with the PRO version? How can in Elementor PRO I adjust my site in one place when I have different layouts on different pages without going in to each template to change?

In your home page is says "One of the truly great things about Elementor Pro 2.0 is that it works with any WordPress theme”,

Don’t take me wrong I am impressed by Elementor but I get annoyed when I pay for something and then I have to run around in circles to try to find the problem just to find out that the theme I also have bought is not working with a PRO version when it says it should!

I think you have to do better then that if you want to keep your paying customers,

R
J


On 14 Jun 2018, at 8:09 pm, Raz Ohad <notifications@github.com<mailto:notifications@github.com>> wrote:


@Kru-x<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKru-x&data=02%7C01%7C%7C312e3cf682a9470ce77f08d5d1dee4a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636645677600799792&sdata=1d6x3isZ3yh%2BAD27aHcTkvDgT8zBOwxM3eP%2ByJ6ACoI%3D&reserved=0>

thanks for clarifying,

We have done compatibility work with GeneratePress and since our templates don't use his layout settings it is removed.

So not a bug, more of a feature.

thanks.
