### ISSUE TITLE
[Feature request] - HTML confirmation emails

### ISSUE THREAD

**Issue by AndersJpg** [pojome/elementor#4757]
Send more advanced confirmation emails
would be lovely if we could design html pages  and send those out to the customer as a confirmation

i just designed a HTML  page with inline style and using some of the ID fields to make it more personalize, but it sadly does not work

**Comment by AndersJpg** [comment]
i got it to work suddenly, so thats pretty awesome :) keep up the amazing work

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
