### ISSUE TITLE
Disable Elementor on other apply_filters the_content

### ISSUE THREAD

**Issue by htmldiz** [pojome/elementor#4758]
Hi. If i use apply_filters the_content for enother metabox its also display elementor code.
I use 2.0.16 version and Elementor Pro 1.15.2 version to.
Can you please fix that?

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by htmldiz** [comment]
Hi so what? You just close issue and don't do nothing or what? you can write me something like "Done.","Already fix" or "We waiting new issue with Prerequisites, Steps, Isolating and with System info ". I dont understand what you problem?
