### ISSUE TITLE
[Feature Request] Add custom shapes

### ISSUE THREAD

**Issue by olivierchauveau** [pojome/elementor#4759]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Add custom shapes to Elementor that don't be erase by next update.

**Describe the solution you'd like**
I would like to get a hook in shapes.php so we could add our own shapes with the functions.php child theme file for example or any other solution that can solved this issue.

**Describe alternatives you've considered**
I add my own custom shapes by adding my svg to /assets/shapes/ and add lines to /includes/shapes.php in order to be able to choose my custom shapes in Elementor section shape options. It works well but the svg files are always erased and the shapes.php is reinitialized when I update Elementor. I'm forced to upload again the svg and shapes.php after each uptades. And Elementor is often updated.

**Additional context**
The custom lines are added to shapes.php under 
```
private static function init_shapes() {
	self::$shapes = [
```
Exemple of custom shape lines
```
'mycustomshapesvgfilename' => [
	'title' => _x( 'My custom shape displayed name', 'Shapes', 'elementor' ),
	'has_flip' => true, /* or false */
	'has_flip' => true, /* or false */
	'height_only' => true, /* or false */
],:
```

**Comment by bainternet** [comment]
@livierchauveau 

We have added a new filter hook in v2.1.0 so you to add your custom shapes and also a path parameter so you don't have to add your svg in to the plugins folder, ex:

```PHP
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
	$additional_shapes['mycustomshapesvgfilename'] = [
		'title' => _x( 'My custom shape displayed name', 'Shapes', 'elementor' ),
		'has_flip' => true,
		'height_only' => true,
		'path' => 'PATH/TO/YOUR/SVG', //cpuld be in your theme/child/plugin
	];

	return $additional_shapes;
});
```

**Comment by BrookeRaraAvis** [comment]
Can we get an easier way to use custom shape dividers? I added this to my functions.php and can't get it to work.

**Comment by MajesticSJ** [comment]
> @olivierchauveau
> 
> We have added a new filter hook in v2.1.0 so you to add your custom shapes and also a path parameter so you don't have to add your svg in to the plugins folder, ex:
> 
> ```
> add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
> 	$additional_shapes['mycustomshapesvgfilename'] = [
> 		'title' => _x( 'My custom shape displayed name', 'Shapes', 'elementor' ),
> 		'has_flip' => true,
> 		'height_only' => true,
> 		'path' => 'PATH/TO/YOUR/SVG', //could be in your theme/child/plugin
> 	];
> 
> 	return $additional_shapes;
> });
> ```

Hi , i test this code but get error in console for not found svg (jquery error) .
my code :
```define("THEMEURLL", get_template_directory_uri());
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
	$additional_shapes['madona'] = [
		'title' => _x( 'My custom shape displayed name', 'Shapes', 'elementor' ),
		'has_flip' => true,
		'height_only' => true,
		'path' => THEMEURLL.'/includes/elementor/shapes/madona.svg', //could be in your theme/child/plugin
	];

	return $additional_shapes;
});

not found url error : 
GET http://localhost/test/wp-content/plugins/elementor/assets/shapes/madona.svg 404 (Not Found)

**Comment by MajesticSJ** [comment]
> @olivierchauveau
> 
> We have added a new filter hook in v2.1.0 so you to add your custom shapes and also a path parameter so you don't have to add your svg in to the plugins folder, ex:
> 
> ```
> add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
> 	$additional_shapes['mycustomshapesvgfilename'] = [
> 		'title' => _x( 'My custom shape displayed name', 'Shapes', 'elementor' ),
> 		'has_flip' => true,
> 		'height_only' => true,
> 		'path' => 'PATH/TO/YOUR/SVG', //could be in your theme/child/plugin
> 	];
> 
> 	return $additional_shapes;
> });
> ```

when i use this code in my plugin i get not found svg in this url (jquery error):
GET http://localhost/test/wp-content/plugins/elementor/assets/shapes/madona.svg 404 (Not Found)

my code :

```
define("THEMEURLL", get_template_directory_uri());
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
	$additional_shapes['madona'] = [
		'title' => _x( 'My custom shape displayed name', 'Shapes', 'elementor' ),
		'has_flip' => true,
		'height_only' => true,
		'path' => THEMEURLL.'/includes/elementor/shapes/madona.svg', //could be in your theme/child/plugin
	];

	return $additional_shapes;
});

**Comment by patrick-wyzorski** [comment]
I'm having a hard time getting this work.

Has this hook been implemented?

**Comment by AndersJpg** [comment]
any news on this really need a simple way to add like svg shapes in

**Comment by sermalefico** [comment]
this no work

**Comment by bellamystudio** [comment]
The path is being ignored and the svg is being requested from the elementor/assets/shapes directory. My path is set to '/wp-content/themes/adventure/svgs/ta-wavy.svg' but the xhr request is going to '/wp-content/plugins/elementor/assets/shapes/ta-wavy.svg' (and so is getting a 404). 

Is this a simple fix? It would be great to extend these shapes.

**Comment by bellamystudio** [comment]
Further to this, if I add my SVG to the core elementor directory I can see it and manipulate it in the editor, but when I save and look at my page in another browser it doesn't show. I can see reference to it in the source, but there are no console errors or xhr requests, I just can't see the shape.

**Comment by DrumFredo** [comment]
Hi! I'v got this work by passing an another var to the array. Besides the 'path' variable there seems to be necessary to pass a variable for 'url' as well. Elementor shape widget function seems to use the   var 'url for locate the custom made shape folder:

Ex.
add_filter( 'elementor/shapes/additional_shapes', function( $additional_shapes ) {
	$additional_shapes['opacitywaves'] = [
		'title' => _x( 'MyCustomWave', 'Shapes', 'elementor' ),
		'has_flip' => true,
		'height_only' => false,
		'has_negative' => false,
		'url' => get_template_directory_uri() . '/images/svg-shapes/mycustomwave.svg',
		'path' => get_template_directory() . '/images/svg-shapes/fp-mycustomwave.svg',
	];
	return $additional_shapes;
});

**Comment by unclerom** [comment]
Any way to get the color picker to work with custom shape divider?

**Comment by DrumFredo** [comment]
Yes, I think you have to add css class "elementor-shape-fill" to the path elements in the SVG fil for colors to work.

ex.

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 10" preserveAspectRatio="none">
<path class="elementor-shape-fill" d="M360 0L350 9.9 340 0 0 0 0 10 700 10 700 0"/>
</svg>

**Comment by jeromevalette1** [comment]
Hi,

Today i use this and it's work great. 

`add_filter('elementor/shapes/additional_shapes', function( $additional_shapes ){

  if(is_front_page()) {
    $additional_shapes['rounded-triangle'] = [
      'title' => _x('Rounded Triangle', 'Shapes', 'elementor'),
      'has_negative' => true,
      'url' => get_template_directory_uri() . '/images/rounded-triangle.svg',
    ];
  } else {
    $additional_shapes['rounded-triangle'] = [
    'title' => _x('Rounded Triangle', 'Shapes', 'elementor'),
    'has_negative' => true,
    'path' => get_template_directory() . '/images/rounded-triangle.svg'
  ];
  }
  

  return $additional_shapes;
});`

**Comment by ScottKemp** [comment]
There is a bug in elementor\plugins\elementor\assets\frontend.js which prevents you from previewing the custom dividers in the editor.

Find the following section:

    key: "getSvgURL",
    value: function getSvgURL(shapeType, fileName) {
      var svgURL = this.getSettings('svgURL') + fileName + '.svg';

      if (elementor.config.additional_shapes && shapeType in elementor.config.additional_shapes) {
        svgURL = elementor.config.additional_shapes[shapeType];

        if (-1 < filename.indexOf('-negative')) {
          svgURL = svgURL.replace('.svg', '-negative.svg');
        }
      }
		console.log( svgURL ); 
      return svgURL;
    }

and change:
        if (-1 < filename.indexOf('-negative')) {
to
        if (-1 < fileName.indexOf('-negative')) {

**Comment by max991** [comment]
After updating elementor to 2.8.2 my shape was no longer showing this is due to 'has_negative' => true and in the latest update it tries to find a file with example-negative.svg so to fix the issue just copy your current shape divider and use the same name with -negative.svg on the end.

Thanks

**Comment by jsuch11** [comment]
Hi,

I tried the code from @jeromevalette1 and followed @max991's recommendation, but I can't get it to work. I also formatted my svg file with the same structure as other shapes in elementor but it only shows me the option for my custom shape in Elementor but doesn't display it when I click on it. 
Do you have any idea to help me.

Thanks !
