### ISSUE TITLE
+1 for Pods integration

### ISSUE THREAD

**Issue by EdwardBurns** [pojome/elementor#4760]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EdwardBurns** [comment]
+1 for Pods integration

**Comment by bainternet** [comment]
Duplicate of #4129
