### ISSUE TITLE
Price List Widget (Pro) | Show images on top

### ISSUE THREAD

**Issue by ABLEMED** [pojome/elementor#4762]
Hey, im using this Element: 

Elementor Price List Widget (Pro) 
https://docs.elementor.com/article/94-price-list

This widget colud use the function to display the images on top. this could be very useful for mobile users. Right now it shrinks the image too much and the header, price & content are pushed together and get unreadable, especially in phone layout.

I alredy wrote a support ticket...and so i got here. Hope someone can help.

thanks

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
