### ISSUE TITLE
Template with dynamic elements import issues - ViewDestroyedError

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4763]
When importing an Elementor template that has a section with the background set as the featured image, and other dynamic elements such as post title, template widget for dynamic section or two and a global here and there, I often get an error when importing saying the "View" has already been destroyed.  If I persist, sometimes refreshing the page or logging out and back in, I can successfully import.

```
ViewDestroyedError: View (cid: "view426") has already been destroyed and cannot be used.
			at https://blahblahblah.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-15 02:22 +00:00
```

**Comment by bainternet** [comment]
@pingram3541 

Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by pingram3541** [comment]
- I cannot duplicate it on command.
- has happened on multiple sites, diff system info
- was hoping the error itself gave a clue but...

I'll report back the next time I encounter this and hopefully have more information to provide. Thx

**Comment by bainternet** [comment]
Thanks, closing for now.

**Comment by ofmarconi** [comment]
I'm facing a similar problem, any ideas on how to debug?
