### ISSUE TITLE
Please consider working on the ability to allow end users to specify multiple options on the portfolio filter bar - it would need to show if the option was added as an "and" or an "or" though

### ISSUE THREAD

**Issue by CSWood** [pojome/elementor#4764]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
