### ISSUE TITLE
Fonts are not working with "Elementor Nav Menu Widgets" & "WooCommerce Storefront Theme"

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#4769]
Fonts are not working with "Elementor Nav Menu Widgets" & "WooCommerce Storefront Theme"

The "Elementor Nav Menu Widget" fonts are not overriding the WooCommerce Storefront theme fonts, while your other Elementor widgets such as the "Elementor Link Widget" DO override theme fonts with the Woo Storefront Theme. Fix your code...it is not consistent.

You are missing code in your widget to allow this, because the font works in other spots on the site with this theme such as the "Elementor Link Widget." Your link widget allows fonts to work correctly with the WooCommerce Storefront Theme. The "Elementor Nav Menu Widget" does not show the fonts properly with this theme.

Steps to Replicate using Elementor Pro, WooCommerce and WooCommerce Storefront Theme:

Step 1: Create a "Navigation Menu Widget" in Elementor. (all of the Navigation Menu Widgets dont work)
Step 2: Change font to Poppins.
Step 3: You will notice that Poppins DOES NOT work in this widget. It works everywhere else such as the "Elementor Link Widget" or "Txt Widget", but not with your menu navigation widgets.

Isolating the problem: Above. Fix your code to override Theme Fonts for the "Elementor Nav Widgets" like it does for the "Elementor Text or Link Widgets"

System Info: Most updated version of Wordpress & WooCommerce Storefront & Elementor Pro.

Videos:

Video of Storefront Theme Turned on & off. Poppins font NOT working with "Elementor Nav Menu Link Widget" in Storefront Theme:
https://www.useloom.com/share/e5f7c13e05c34393915b7d8f65d98754

Video of Poppins font that IS working with Storefront Theme with "Elementor Link Widget"
https://www.useloom.com/share/866f93742bc64c7aa01de241e7c31000

Video showing Poppins font NOT working with Storefront Theme with "Elementor Nav Widget"
https://www.useloom.com/share/7e777533c6e845c19cb28a1f63db4de2

This should be fixed. You even advertise Storefront Theme with Elementor on your site. That's how I got to you and bought your plugin:
https://elementor.com/create-ecommerce-website/

Thanks in advance.

**Comment by bainternet** [comment]
@smile00000 

Thanks for the clarification, we can't replicate, 
Please contact our support at support @elementor.com for guidance in resolving this issue.
