### ISSUE TITLE
Documentation for Dynamic Tags

### ISSUE THREAD

**Issue by iamntz** [pojome/elementor#4771]
I'm trying to add dynamic tags on my custom widgets and i'm not sure how to do it in an efficient manner.

Documentation is very scarce and up until now I relied only on diging into existing code, but this can be very time consuming. There is a „hidden” documentation that I didn't find it yet?

Thanks!

**Comment by bainternet** [comment]
@iamntz 

not yet but we are working on it.
Any specific question?

**Comment by iamntz** [comment]
@bainternet sure: so i have this repeater with multiple fields and I want to have any of the fields within repeater to be dynamic. Or even the repeater itself!

How I did it:  I've added  these keys to my field (inside of the repeater field):

```
		$repeater->add_control('subtitle', [
			'label' => __('Subtitle'),
			'type' => Controls_Manager::TEXT,
			'label_block' => true,
			'condition' => [
				'inherit_content!' => 'yes',
			],
			'dynamic' => [
				'active' => true,
				'categories' => [ TagsModule::TEXT_CATEGORY ],
			],
		]);
```

While the `dynamic` menu works, when I hit save, it doesn't save the right thing. Or anything for that matter :)

**Comment by bainternet** [comment]
@iamntz 

I can only guess that in your `render` method you are not using `get_settings_for_display`.

can you post your render method? or the part where you pull the widget settings.

**Comment by iamntz** [comment]
It's not an issue on render, not yet.  

Changing the above field to _dynamic_, saving & refreshing the page will make the field text again (i.e. NOT dynamic).

**Comment by bainternet** [comment]
Well without seeing your code, I can't really tell.

But I would wait for V2.1.0 where we implemented a few fixes and tweaks for repeater and dynamic tags.

closing for now.

thanks

**Comment by marekmaurizio** [comment]
Still working on it?
