### ISSUE TITLE
BUG? Redudant add_action call in Elementor/includes/managers/image.php

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#4773]
Just from reading the code in:
Elementor/includes/managers/image.php (latest release)

```
public function __construct() {
		add_action( 'wp_ajax_elementor_get_image_details', [ $this, 'get_image_details' ] );
		add_action( 'wp_ajax_elementor_get_images_details', [ $this, 'get_images_details' ] );
	}
```

But there is no `get_image_details` only `get_details` - called in line #33.
Could not find  `get_image_details`  anywhere else in the code

What am I missing? Or I can simply comment out the line.

Well, I did comment out and all seems OK, but your testing is better.

**Comment by KingYes** [comment]
Thanks

**Comment by Mulli** [comment]
Maybe you would consider a cosmetic change:
Change get_details() to get_image_details()
Two places: function definition and single call at line #33.

Simply because "get_details()" is not self explanatory as "get_image_details()"

**Comment by bainternet** [comment]
@Mulli 

Thats the beauty of OOP its incpsulated in a class named `Images_Manager` and called only via `Images_Manager` so that kind of redundant it self.

thanks again.

**Comment by Mulli** [comment]
Note that this is readability issue - not OOP.
If you look at the comment of `get-details()`  you will see that
this was the initial idea...
But that your code & your call.
Best
