### ISSUE TITLE
 [Feature Request] Robust WooCommerce Product Single Page Support

### ISSUE THREAD

**Issue by BrookeRaraAvis** [pojome/elementor#4774]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Searched for similar, but similar ( #4697 , #4475 , #3252 ) were all closed and/or combined with other posts without a proper answer from Elementor support.

**Problem**: You led me to believe (in a YouTube teaser on Feb 27, 2018) that Elementor 2.0 would provide a way to edit WooCommerce product single pages. I committed to Elementor & made my purchase under the impression that your very robust WooCommerce support was imminent. Nearly 4 months later, I still don't see it & I can't seem to find any information pertaining to when I can expect that to happen.

**Solution**: Please give me an update about when this is actually going to happen so that I can decide what I need to do and move forward with my website build.

**Comment by bainternet** [comment]
@BrookeRaraAvis 

> Preparing for 2.1.0 with full Woocommerce support.

ref: https://github.com/pojome/elementor/issues/4475#issuecomment-389781774

Thanks you.
