### ISSUE TITLE
Fixed Background Image Issue

### ISSUE THREAD

**Issue by unclerom** [pojome/elementor#4776]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Fixed background image flashes if i hover over button in row above. I have a section-#1 with some text and a button, he button **has a grow animation** on it. Below that is another section-#2 with a fixed image background. If hover on button in section-#1 the fixed background below in section-#2 flashes and moves. If i remove the grow animation the problem goes away.
Have the problem in default theme as well as oceanwp

## Steps to reproduce
- add hero or other large block to push test sections below the fold
- create an empty section, add button with grow/shrink animation on hover
- create another section below, add fixed background image and random widget inside- to make it visible
- save and view page
- hover over button

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.36
	PHP Version: 7.0.30
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: http://.com
	Home URL: http://.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

== Active Plugins ==
	Duplicate Page
		Version: 2.6
		Author: mndpsingh287

	Elementor
		Version: 2.0.16
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.11
		Author: Elementor.com

	Ocean Elementor Widgets
		Version: 1.0.16
		Author: OceanWP

	Ocean Extra
		Version: 1.4.14
		Author: OceanWP

	Ocean Hooks
		Version: 1.0.6
		Author: OceanWP

	Ocean Side Panel
		Version: 1.0.10
		Author: OceanWP

	Ocean Sticky Header
		Version: 1.1.8
		Author: OceanWP

	Photo Gallery by Supsystic
		Version: 1.12.1
		Author: supsystic.com

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	Yoast SEO
		Version: 7.6.1
		Author: Team Yoast



				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@unclerom 

Thanks for reporting, we can't replicate the issue described, can you please add a screen capture of the issue?

**Comment by unclerom** [comment]
i updated the steps to reproduce. the fixed section must be below the fold to recreate bug i just did these exact steps on a fresh wp install with only elementor and 2017 no other plugins

**Comment by CobraClutch** [comment]
I have the same issue. jQuery animations seem to be making fixed/cover background images jumpy. I've even seen some background images completely unrendered because of this.

**Comment by ideasandpixels** [comment]
Can confirm this issue. I was forced to remove fixed backgrounds because of it. Two successive sections having fixed background and hovering the first will cause the second to disappear.

**Comment by kiouz** [comment]
Same bug here. I have a section with two columns, one picture at the left. The next section has only a spacer and a fixed background image.
If the picture of the first section is too large, the fixed background of the second section "disappears".
In fact, the background has moved at the top of the page (under the first content).

This behavior is present since the last update (2.0.16) and breaks the old layouts.

**Comment by bainternet** [comment]
Thanks, everyone,


Seems like a Chrome bug:

> It is an issue specific to only Chrome 67 (I have Version 67.0.3396.79 (Official Build) (64-bit)). Validated by going back to previous version and vice versa. So basically any site you designed with parallax effect is going to look like crap in chrome (used by 62% of users by the way) when users receive the 67 version (which is occuring now).
> I only noticed this as I was in the midst of launching a site, and it worked great, then with no changes, it didn't. Found out browser got the 67 and is why.
> Unless Google fixes this in there browser you will need to go back to every site you produced and add that silly css to it.


Adding:
```CSS
selector {
   transform: translate3d(0,0,0);
   -webkit-transform: translate3d(0,0,0); 
}
```

from stackoverflow:

> Using -webkit-transform: translate3d(0,0,0); will kick the GPU into action for the CSS transitions, making them smoother (higher FPS).Note: translate3d(0,0,0) does nothing in terms of what you see. it moves the object by 0px in x, y and z axis. It's only a technique to force the hardware acceleration

By the way, you can download older versions here https://www.chrome-portable.com/index.php/google-chrome-offline-installer. Just do a search for how use an older version once downloaded.

Ref: https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chrome/DC4IFvGXdIA/2iySIb1oAgAJ

thanks for reporting.

**Comment by crystalpulse** [comment]
I'm having the same issue, adding the CSS hasn't fixed it

**Comment by untouchableweb** [comment]
Try giving the problem element a higher Z-index.  I was having similar button issues and that fixed it for me.
