### ISSUE TITLE
Section can't be selected in the editor because of previous element's z-index

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#4780]
Hi there,

On the editor, when you click a widget, the side panel would change to the widget settings. This is very nice to quickly switch and edit between widgets. However this behavior is not applied to sections & columns. I totally understand that this is for good user experience. User can still reach the section /or column settings by clicking the section or column icon.

BUT

In the case when you have an element in the previous section that overlays the next section, the section icon (which is to activate the section settings panel) is overlaid by the element. And there is no way we can hover to that section icon. Because when you try to hover the section icon, it hovers that overlaying element instead.

<img width="1190" alt="screen shot 2018-06-18 at 17 02 23" src="https://user-images.githubusercontent.com/1287713/41530150-81d1f64e-7319-11e8-83b1-b48078746d82.png">

Please fix this.

**Comment by bainternet** [comment]
@daviedR 

Thanks for reporting,
Next time, please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
