### ISSUE TITLE
Full Screen Nav Menu

### ISSUE THREAD

**Issue by fadyr** [pojome/elementor#4782]
Hello, first of all I want to say I am a happy Elementor user, you guys are always improving your services and that’s awesome. I also wanted to ask if you are considering to enable an option that let customers deploy the navigation menu in a full screen mode, something very common in modern websites. Thank you and keep up the good work!

![image](https://user-images.githubusercontent.com/40359367/41537790-7c4e4c0a-72d7-11e8-86e1-f9f839510671.png)

**Comment by bainternet** [comment]
I merged this issue with  #4787, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Aisha56** [comment]
Definitely +1
And besides that a request to have the menu openened fully immediately. So after click on toggle__> all main menu and submenu items open and are visible.

**Comment by apollollc** [comment]
+1
