### ISSUE TITLE
 When Sticky is turned on, the site screen automatically scrolls upward.

### ISSUE THREAD

**Issue by misegamaeya** [pojome/elementor#4783]
A bug occurs in either editing mode or public view in Chrome.

Bugs will not occur if you turn off Sticky.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
