### ISSUE TITLE
[Elementor Pro Forms] GET and POST actions

### ISSUE THREAD

**Issue by jhenzely** [pojome/elementor#4785]
Dear Elementor team.

Let's assume I have this simple HTML code:
```
<form action="https://example.com/register" method="post (or get)">
E-mail: <input type="text" name="email01"><br>
<input type="submit">
</form>
```

And this PHP code:
```
function inputform02() {
  print("INFORM_02 Output is: " . $_POST["email01"] . "<br>" );

  return ;
}
add_shortcode('inform02', 'inputform02');
```
I would like to achieve the same functionality using the Elementor Form widget.

Both methods are required, POST (for registration, etc) and GET (for search results link).
Sure, Field type could be set to "HTML", but then I will lose the possibility to use Elementor for adjusting the other form properties (font, size, colour).

Proposed solution:
Add possibility to set "form action=" and "method=" for given form (which is standard form handling procedure).

Thank You for cooperation.

BTW: You have mentioned Webhook as proposed solution ( https://github.com/pojome/elementor/issues/3000 ) , then;
Can you please provide end-to-end example for my usecase ?

**Comment by bainternet** [comment]
@jhenzely 

All Elementor Pro forms work as POST via AJAX request which means the page is not refreshed.

Which in turn means that the response should be handled via Javascript and your shortcode won't help.

Then in your case, you should use a custom webhook, and pass the output to the ajax handler, for eaxample:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $ajax_handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	//normalize the fields
	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	$ajax_handler->data['output'] = 'INFORM_02 Output is: ' . $fields['email_field_id'];
});
```

Then on the front-end  you can use that data via JavaScript: 

```Javascript
<script>
	//The event is submit_success so you can catch it for example:
	jQuery( document ).ready(function( $ ){
		$( document ).on('submit_success', function( event, response ){
			if ( response.data.output ) {
				alert( response.data.output  );
			}
		});
	});
</script>
```

Now bare in mind that tis is not tested and just an example, but it should get you started.

Side-note: your shortcode should alway return a value and not output it to the buffer.

**Comment by sashad2003** [comment]
> All Elementor Pro forms work as POST via AJAX request

Hi, 
What if I can not use ajax when sending a letter?
Is it possible to change this?
Thanks

**Comment by jhenzely** [comment]
@bainternet 
Hello, thank you for reply.

This procedure with Webhook is more suitable for submitting the structured data to some database (like user registration).

**Comment by jhenzely** [comment]
Hello @sashad2003 
Here is very simple (and crude) script which shows how to get data from Elementor for when using webhook method (classic POST).

It will get the data from the form and write it to the file.

Hope it helps.

```
<?php
$file01 = "fwr.text"; // Name of the file to write the output
$curr01 = file_get_contents($file01); // Load current content of the file into variable

  foreach($_POST as $unit01 => $unit01_value ) { // $_POST is an array
      $curr01 .= ("Key: $unit01 Value: $unit01_value \n");  // Append new values to variable
  }

$curr01 .= ("\n");
file_put_contents($file01, $curr01); // Write contents of the variable to file
?>
```

**Comment by NJseo** [comment]
Yeah, well you should add ability to post through rest.

**Comment by jhenzely** [comment]
NJseo
Yes. Currently I have to use custom HTML code instead of Forms Elementor feature just to make forms work the way I need.

Adding POST and GET methods would be great.


Thank You.

**Comment by jhenzely** [comment]
Thanks, NJseo.
Yes, but this is just a workaround  :-/

**Comment by jhenzely** [comment]
Exactly, in a lot of cases it just makes the code much more complex for no reason.
Thank you @bkjproductions for saying that loud :)
I don't understand why developers closed this request and do not want to implement this essential "feature". @bainternet 

I had to code the forms by myself, it's not a problem and only took me a few minutes, but the Forms feature from Elementor Pro is therefore useless in my case.

**Comment by scott8035** [comment]
I don't know why it took so long for me to find, but I believe people visiting this topic will find this useful: https://developers.elementor.com/forms-api/

**Comment by trendco** [comment]
A Selection Option in the Settings would be the perfect Solution:

1. Use AJAX (as it is in the Moment)
2. Use POST to Customer File
3. Use GET to Customer File

And everyone would be happy -:)

**Comment by scott8035** [comment]
I was able to make sense out of the doc once @bainternet narrowed the field for me. I aim to post a simplified, well-explained example on my blog in the near future. I'll post the link here when I do.

> Hi @scott8035 ,
> Not sure I can follow the forms-api documentation. Nowhere do I see how to change the form ACTION. If you can point that out with a code example it would be greatly appreciated by my tiny brain.

**Comment by jhenzely** [comment]
> A Selection Option in the Settings would be the perfect Solution:
> 
> 1. Use AJAX (as it is in the Moment)
> 2. Use POST to Customer File
> 3. Use GET to Customer File
> 
> And everyone would be happy -:)

Exactly, I don't understand why there are no replies from the Elementor team.
It should not be that hard to implement, and clearly, there is considerable demand for this feature.

@arielk 
@kobizz

**Comment by jmanningppbh** [comment]
@bkjproductions - not sure if you are still looking for this, but others might be... (I was trying to find this POST solution for the forms widget too)

> Is there some way to have a javascript "listener" that waits for the ajax response, and then I can do a basic javascript **window.location.href = "https://newlocation.com/processor.php?value1=a&value2=b&value3=c"** type of thing?

This code seemed to work for me as a workaround - you don't need to add any actions to the "Actions after Submit' in the widget dashboard - just can add this to your functions.php


/* form widget redirect hack for getting to a page with some keyword set in GET var */

function my_search_aftervalidation( $record, $ajax_handler ){

	// get fields using method in Form_Record class
	$fields = $record->get('fields');

	// get my search keyword from the form record (submission)
	$searchKey = $fields['search_keyword']['value'];
	
	// set up my redirect url with my GET var
	$redirect_url = 'https://mysite.com/somepage/?search_keyword=' . $searchKey;
	
	// add the redirect to ajax handler
	$ajax_handler->add_response_data( 'redirect_url', $redirect_url );
	
}

add_action( 'elementor_pro/forms/validation', 'my_search_aftervalidation', 10, 2 );

**Comment by saif-rehman** [comment]
I am doing following thing in my custom plugin but it's not working . 

`// Validate the Ticket ID field is in XXX-XXXX format.
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {
    $fields = $record->get_field( [
        'id' => 'ticket_id',
    ] );

    if ( empty( $fields ) ) {
        return;
    }

    $field = current( $fields );

    if ( 1 !== preg_match( '/^\w{3}-\w{4}$/', $field['value'] ) ) {
        $ajax_handler->add_error( $field['id'], 'Invalid Ticket ID, it must be in the format XXX-XXXX' );
    }
}, 10, 2 );`
please help

**Comment by scott8035** [comment]
Describe the symptoms you're having...what is wrong, what is broken?

I will say you should add something like this right at the top of your routine:
```
    $form_name = $record->get_form_settings( 'form_name' );
    if ( $form_name != 'Add User' ) {
        return;
    }
```

**Comment by NicolaCavallazzi** [comment]
What I'm doing at the moment, waiting to find a better solution is create a HTML widget right after the form with the following code in it:

`<script type='text/javascript'>
  document.addEventListener("DOMContentLoaded", function(event) {
      
    /* The ID assigned to the form widget via Elementor */
    var formID = "#gatto-form";
    /* The URL to which you want to send the data */
    var actionURL = "https://cosmo.cat/params";
    
    var $jq = jQuery.noConflict();
    $jq("#form-super-gatto").html($jq(formID).html());
    $jq("#form-super-gatto").attr("class", $jq(formID).attr("class"));
    $jq(formID).hide();
    $jq("#form-super-gatto form").attr("action", actionURL);
    $jq("#form-super-gatto form").find('input, textarea, select').each(function(){
        var matches = $jq(this).attr("name").match(/form_fields\[(.*?)\]/);
        if (matches) {
            var submatch = matches[1];
            $jq(this).attr("name", submatch);
        }else{
            $jq(this).remove();
        }
    });
  });
</script>
<div id="form-super-gatto"></div>`

It just copies the form in a new element and hides the original, tweaking a bit the names of inputs.
Disclaimer: not very tested.

**Comment by KimchaC** [comment]
Can this please be reopened? It's really an essential feature.

**Comment by NicolaCavallazzi** [comment]
If anyone interested: I wrote a tiny plugin that does hack the form to get this functionality, basically integrating the previous code. You can give it a try [here](https://github.com/NicolaCavallazzi/elementor-super-cat)
Not super straightforward, but if you follow the Readme you should be fine. If you need help ring a bell 😸

**Comment by bkjproductions** [comment]
@bainternet can you re-open this issue?

**Comment by BumperTDM** [comment]
I thought I was going entirely insane this whole time but good old Googling your specific issue brought me to this thread about why my custom Elementor form wouldn't post, I thought the Javascript validation was the issue and could not wrap my head around why I could just register users. Please, pleeease reopen this as I don't want to have to learn more scripting to post a form I know to already work

**Comment by nbi1** [comment]
I must be the only person on earth who doesn't have complete knowledge of the $ajax_handler API. Where is this documented in detail? I apologize  for being daft, but I really have tried to find the info and have come up empty. What little I know about the $ajax_handler I gleaned from limited code examples. There has got to be a complete reference somewhere, no?

**Comment by scott8035** [comment]
@nbi1 : https://developers.elementor.com/forms-api/ is a good place to start, but quite honestly, the last time I looked at the API doc it was pretty spartan, making it difficult to figure out how to do things.

**Comment by nbi1** [comment]
Thanks Scott, I already looked at that. Your assessment is spot on. I've 
scoured the Elementor docs, but just cannot find anything helpful. 
What's so aggravating is that I'm a developer who knows to RTFM first, 
but in the case of Elementor that doesn't mean a thing. I guess no good 
deed goes unpunished.

**Comment by ZambraDesigner** [comment]
> @bkjproductions - not sure if you are still looking for this, but others might be... (I was trying to find this POST solution for the forms widget too)
> 
> > Is there some way to have a javascript "listener" that waits for the ajax response, and then I can do a basic javascript **window.location.href = "https://newlocation.com/processor.php?value1=a&value2=b&value3=c"** type of thing?
> 
> This code seemed to work for me as a workaround - you don't need to add any actions to the "Actions after Submit' in the widget dashboard - just can add this to your functions.php
> 
> I'm my example I just have one text field in the form and the ID of the field is 'search_keyword'
> 
> ```
> 
> /* form widget redirect hack for getting to a page with some keyword set in GET var */
> 
> function my_search_aftervalidation( $record, $ajax_handler ){
> 
> 	// get fields using method in Form_Record class
> 	$fields = $record->get('fields');
> 
> 	// get my search keyword from the form record (submission)
> 	$searchKey = $fields['search_keyword']['value'];
> 	
> 	// set up my redirect url with my GET var
> 	$redirect_url = 'https://mysite.com/somepage/?search_keyword=' . $searchKey;
> 	
> 	// add the redirect to ajax handler
> 	$ajax_handler->add_response_data( 'redirect_url', $redirect_url );
> 	
> }
> 
> add_action( 'elementor_pro/forms/validation', 'my_search_aftervalidation', 10, 2 );
> ```

how can i say that this script is active only specific form?

**Comment by jmanningppbh** [comment]
@ZambraDesigner - this is how I did it - inside the my_search_aftervalidation() you just check the ID of the form and then do the redirect hack if it matches..   You need to make sure your form has an ID set in the Elementor dashboard side of things too.

This is the basic idea - 

function my_search_aftervalidation( $record, $ajax_handler ){

	$form_settings = $record->get('form_settings');
	$form_id = $form_settings['form_id'];
	
	if( $form_id == 'my_form_id' ){
          // do redirect stuff
	}
        else{
             return;
        }
}

**Comment by ZambraDesigner** [comment]
> @ZambraDesigner - ecco come l'ho fatto - all'interno di my_search_aftervalidation () devi solo controllare l'ID del modulo e quindi eseguire l'hacking di reindirizzamento se corrisponde .. Devi assicurarti che il tuo modulo abbia un ID impostato nella dashboard di Elementor anche di cose.
> 
> Questa è l'idea di base -
> 
> funzione my_search_aftervalidation ($ record, $ ajax_handler) {
> 
> ```
> $form_settings = $record->get('form_settings');
> $form_id = $form_settings['form_id'];
> 
> if( $form_id == 'my_form_id' ){
>       // do redirect stuff
> }
>     else{
>          return;
>     }
> ```
> 
> }

Fantastic.

I had tried discriminating for form_name but it gave conflict.

Thank you very much.

**Comment by ranjitc** [comment]
Got an easy solution working thanks to the comments in this thread, especially by @dettogatto 
If you do not want to use ajax, or muck around with custom hooks, what you need to do is ..
1. set the default action (under "actions after submit" in form settings) to blank. remove the email option if it is there by default.
2. set a form id. do NOT set it under advanced->cssid but under content->additional options (this is what had me tripping up for a bit)
3. then add an html block and add the following code:

`<script>


jQuery(document).ready(
    
    function(){
    

    var form = document.getElementById('my-custom-form');

if (form.attachEvent) {
    form.attachEvent("submit", processForm);
} else {
    form.addEventListener("submit", processForm);
}
    
function processForm(e) {
    if (e.preventDefault) e.preventDefault();

    /* change form method if required */
    /* form.method = 'GET'; */
    /* do what you want with the form */
        form.action='/my-custom-script.php';
        form.submit();

 
    
    // You must return false to prevent the default form behavior
    return false;
}
    
    
    
});


    
</script>`

Redirect or other complicated flow can be handled in your custom php action without having to edit any core files.

**Comment by DavHobbs** [comment]
@bainternet 

Any suggestions on how to hook up Elementor Forms with the following API? Is this possible?
[https://support.clio.com/hc/en-us/articles/360014305753#h_7878163631071545178724033]

**Lead Inbox API Endpoint**
If you need to create your own integration to submit leads to the Lead Inbox, you can do this using our API Endpoint.

Clio Grow's Lead Inbox API endpoint enables you to submit leads into Clio Grow via a simple web form or other source using a POST request in JSON format. Sound like Greek to you? Your webmaster can probably help to add this to your website.

There are 5 basic data fields, 2 URL/source parameters (to track the source of the lead), and an API authorization token that connects the request to the appropriate user’s account in Clio Grow.

**Sample JSON Parameters**
POST URL:
https://grow.clio.com/inbox_leads
 
**HEADERS:**
Content-Type: application/json
Accept: application/json

```
BODY:
{
"inbox_lead" : {
  "from_first" : "John",
  "from_last" : "Doe",
  "from_message" : "I have a DUI and I need a lawyer",
  "from_email" : “johndoe@email.com”,
  "from_phone" : "8987648934”,
  "referring_url" : "http://lawfirmwebsite.com/dui”,
  “from_source” : “DUI Landing Page”
},

“inbox_lead_token" : "ABCDEFGHIJKL0123456789”

} 
```
**Fields to include in a POST:**

- First Name (required)
- Last Name (required)
- Email (optional)
- Phone Number (optional)
- Message (required)

URL & Source (these should be hidden fields on a web form, and both are required):
Referring URL: intended to be the URL of the webpage where the lead was submitted; you can pass in some static text, e.g. “Call handled by virtual receptionist” if it is not submitted via a web form

Source: intended to be the name of the service submitting the lead; this will be used to identify the source and distinguish it from any other integrations, e.g. “XYZ Virtual Receptionist” or “Leads for Lawyers”, etc.

**API Token**
The API token should be a hidden field if you are submitting the lead from a web form. It’s by itself in the JSON object with the parameter name “inbox_lead_token” - users will generate their unique API token from their Clio Grow account settings under the “Integrations” tab. Have your client generate the token and email it to you to connect to their account.

Note: you must add an “Accept” Header of “application/JSON” in order to accept a JSON response. You should receive a 201 response message with the JSON parameters of the lead that was created in Clio Grow.

Additional web form fields can be combined and submitted as part of the "from_message." All message field data gets created as a Note in Clio Grow.


`  "from_message" : "field 1: | field 2: | field 3",`

**Comment by kkleeez** [comment]
In case you are looking for Elementor ajax handler class information, it is defined in this file "/elementor-master/core/common/modules/ajax/module.php".

**Comment by yoedy108** [comment]
@ranjitc 
> Got an easy solution working thanks to the comments in this thread, especially by @dettogatto
> If you do not want to use ajax, or muck around with custom hooks, what you need to do is ..
> 
> 1. set the default action (under "actions after submit" in form settings) to blank. remove the email option if it is there by default.
> 2. set a form id. do NOT set it under advanced->cssid but under content->additional options (this is what had me tripping up for a bit)
> 3. then add an html block and add the following code:
> 
> ```
> <script>
> 
> 
> jQuery(document).ready(
>     
>     function(){
>     
> 
>     var form = document.getElementById('my-custom-form');
> 
>     if (form.attachEvent) {
>         form.attachEvent("submit", processForm);
>     } else {
>         form.addEventListener("submit", processForm);
>     }
>     
> function processForm(e) {
>     if (e.preventDefault) e.preventDefault();
> 
>     /* change form method if required */
>     /* form.method = 'GET'; */
>     /* do what you want with the form */
>         form.action='/my-custom-script.php';
>         form.submit();
> 
>  
>     
>     // You must return false to prevent the default form behavior
>     return false;
> }
>     
>     
>     
> });
> 
> 
>     
> </script>
> ```
> 
> Redirect or other complicated flow can be handled in your custom php action without having to edit any core files.

Seems the easiest way currently to send a GET request on submit to replace the form's POST,
Can you show an example of such a custom php script and where to put it in the file system?
Also how can I use the fields from the form to send a GET request that way, and after that redirect to a thank you page?
I don't have much experience coding php at all, and I'm looking for a way to send GET with the fields, instead of having to create my own custom webhook for the form, the Elementor docs didn't help me...

**Comment by peterjaffray** [comment]
I was caught up on how to do something with the response on the JS side (I'm new to ajax) but I found that by dumping the $record values to the error log on the PHP side I could then pass a lot of stuff to the client JS library through the "add_response_data" thing.

I'm a self-study so this might not be the best way, but once you start dumping things to the logs you can hack your way to what you are looking for. 

I learned a lot from the logs:


PHP
```
add_action( 'elementor_pro/forms/new_record', function( $record, $ajax_handler ) {
	error_log(print_r($record, TRUE);
        $form_name = $record->get_form_settings( 'form_name' );
	$ajax_handler->add_response_data( 'form_name', $form_name );
}, 10, 2);

```


JS
`<script>
	$( document ).on('submit_success', function( event, response ){
			if ( response.data ) {
				console.log( response );
				console.log( response.data );
				console.log( response.data.form_name );
			}
		});
</script>`

**Comment by kippoulet** [comment]
@ranjitc  Thank´s for your solution, works great! Although it should not be necessary (I am looking into your direction, Elementor!).

One additional remark: If jquery does not work for some reason, the script can be turned into vanilla js with a few simple tweaks:

- replace document ready (there are a few ways to do this, DOMContentLoaded works for me so far)
- change "function()" into  "function myformsubmit()" and invoke it below its definition explicitly

```
<script>

document.addEventListener("DOMContentLoaded", function(event) {
    
    function myformsubmit(){
    
        var form = document.getElementById('myform');
    
        if (form.attachEvent) {
            form.attachEvent("submit", processForm);
        } else {
            form.addEventListener("submit", processForm);
        }
    
        function processForm(e) {
            if (e.preventDefault) e.preventDefault();
        
            /* change form method if required */
            /* form.method = 'GET'; */
            /* do what you want with the form */
                form.action='myindividualurl';
                form.submit();
            
            // You must return false to prevent the default form behavior
            return false;
        }    
    
    }

    myformsubmit();

});

</script>
```

**Comment by nicmare** [comment]
yet another addition from me. for some reason the field names of elementor form get put in an array like name=form_fields[first_name] which is not good if you want to pass the form data to an external service like pardot. before sending them you need to iterate through each field and rename it to get rid of it. this works for me:
```javascript
<script>
    document.addEventListener("DOMContentLoaded", function(event) {

        function myformsubmit(){

            var form = document.getElementById('elementorform');

            if (form.attachEvent) {
                form.attachEvent("submit", processForm);
            } else {
                form.addEventListener("submit", processForm);
            }

            function processForm(e) {
                if (e.preventDefault) e.preventDefault();
                form.action = 'https://go.pardot.com/l/900541/2020-12-16/2ych';

                var elements = form.querySelectorAll("[type=text],[type=email],[type=hidden],select");

                for (var i = 0, element; element = elements[i++];){
                    element.name = element.name.replace('form_fields[','').replace(']','');
                }

                form.submit();
                return false;
            }

        }

        myformsubmit();

    });
</script>
```

**Comment by bkjproductions** [comment]
Thanks! I think I will take that and add a hidden field with the ACTION url that I want (in your case you're setting it hard-coded) so that I can use this javascript more universally.  (Then, if the hidden Action field is _not_ there, Elementor will just do its annoying ajax thing.) In your example, are you IDing the form "elementorform"?

**Comment by nicmare** [comment]
i improved further by removing form action in the widget entirely. then i placed the action url in the Formname field on top of form field editor. in the javascript code, i fetch that field name and place it as form action:
```javascript
<script>
    document.addEventListener("DOMContentLoaded", function(event) {

        function myformsubmit(){

            var form = document.getElementById('elementorform');

            if (form.attachEvent) {
                form.attachEvent("submit", processForm);
            } else {
                form.addEventListener("submit", processForm);
            }

            function processForm(e) {
                if (e.preventDefault) e.preventDefault();
                form.action = 'https://go.pardot.com/l/900541/2020-12-16/2ych';

                var elements = form.querySelectorAll("[type=text],[type=email],[type=hidden],select");

                for (var i = 0, element; element = elements[i++];){
                    element.name = element.name.replace('form_fields[','').replace(']','');

                }

                form.submit();

                // You must return false to prevent the default form behavior
                return false;
            }

        }

        myformsubmit();

    });
</script>
```

**Comment by Syed-Wajahat-Ali** [comment]
hello I want to send my elementor form entry to my  second website through API

**Comment by kalindigital** [comment]
it's easier to use Gravity Forms, it has a plugin that adds this external API function

**Comment by nicmare** [comment]
> it's easier to use Gravity Forms, it has a plugin that adds this external API function

why purchasing an additional expensive plugin when you could have the functionality for free?

**Comment by ftmicrowave** [comment]
You can use the code below. Tested and works fine.

` <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

<script>
$(document).ready(function () {
  $("form").submit(function (event) {
    var formData = {};
        $.each($(this).serializeArray(), function(i, field){
            formData[field.name.replace('form_fields[', '').replace(']', '')] = field.value;
        });

    $.ajax({
      type: "POST",
      url: "#your page abc.php",
      data: formData,
      dataType: "json",
      encode: true,
    }).done(function (data) {
      console.log(data);
    });

    event.preventDefault();
  });
});
</script>`

**Comment by nicmare** [comment]
this is so wrong in many aspects: 
1. better do not use jquery 
2. when you use js, enqueue and register it. but don't embed it plain
3. this code is very fragile and has no nonce check. security is weak
4. to run an additional ajax request is redundant. the elementor hook already is a ajax request. so simply use it

**Comment by ftmicrowave** [comment]
> 4\. additional

Thank you for your advice.
If I do not use ajax, I am redirected to the page where I posted the data, which is not what I want. How can we do this with the solution you suggested?

**Comment by ftmicrowave** [comment]
> this is so wrong in many aspects:
> 
> 1. better do not use jquery
> 2. when you use js, enqueue and register it. but don't embed it plain
> 3. this code is very fragile and has no nonce check. security is weak
> 4. to run an additional ajax request is redundant. the elementor hook already is a ajax request. so simply use it

Thank you for your advice.
If I do not use ajax, I am redirected to the page where I posted the data, which is not what I want. How can we do this with the solution you suggested?
