### ISSUE TITLE
Polylang: template copied in wrong language

### ISSUE THREAD

**Issue by Chrystll** [pojome/elementor#4786]
## Plugins and theme activated
Polylang 2.3.7
Elementor 2.0.16
Twenty Seventeen 

## Issue description

When creating a new translation the translated template is copied from the source page while it should be translated. 

## Steps to reproduce

1. Activate the translation for "My Templates" by going to Languages > Settings > Custom post types and Taxonomies as shown here:
![activate-the-templates-translation](https://user-images.githubusercontent.com/19824724/41547010-64eb180c-731f-11e8-8dc4-44bb6e3d0e14.png)

2. Then go to Elementor > My Templates: then add a new template and translate it into another language as here:

![the-templates-list](https://user-images.githubusercontent.com/19824724/41547036-6e80d74e-731f-11e8-83e8-470405332657.png)

This is how looks my English and my French template:
![english-template](https://user-images.githubusercontent.com/19824724/41547056-761389d4-731f-11e8-9db8-30f9b12842c2.png)
![french-template](https://user-images.githubusercontent.com/19824724/41547057-76374a04-731f-11e8-9db2-0c8c42313f93.png)

3. Then go to Pages > Add a new Page as here:

![add-a-new-english-page](https://user-images.githubusercontent.com/19824724/41547077-8996bc9c-731f-11e8-9db2-43da3e67fc8f.png)

4.Then insert the English template as shown below and save your changes:

![insert-english-template](https://user-images.githubusercontent.com/19824724/41547093-941adad6-731f-11e8-80c4-e0f866a1b3b4.png)

5. Then translate your English page in French by clicking on the plus sign as here:

![add-the-french-page-translation](https://user-images.githubusercontent.com/19824724/41547099-9903c13e-731f-11e8-8649-4f281a56e4e2.png)

6. Save as draft you just created French page then edit your page with Elementor: the English template has been copied inside the French page as shown below. The template is copied while it should be translated.
![the-english-template-is-copied-into-thefrench-page](https://user-images.githubusercontent.com/19824724/41547116-9f3971b6-731f-11e8-8c27-7b25d895a1f3.png)

**Comment by bainternet** [comment]
@Chrystll 

Thanks for reporting,

Once you insert a template via the template dialog, it inserts the sections/columns/widgets of the template to the page and loses its connection with the template.

This is why it won't translate.

And in any case, the translation/copy of templates or pages are done via the 3rd party plugin and not Elementor so we basically have no control over it.

thanks again.

**Comment by Chrystll** [comment]
>And in any case, the translation/copy of templates or pages are done via the 3rd party plugin and not Elementor so we basically have no control over it.

Could you consider reopening the issue? The copy is in fact done by Elementor when you use the 'pll_copy_post_metas' filter, see: https://github.com/pojome/elementor/blob/v2.0.16/includes/compatibility.php#L254
and https://github.com/pojome/elementor/blob/v2.0.16/includes/compatibility.php#L278

I don't know why you created your own copy function and did not use the way provided natively by Polylang, but Polylang allows you to select the metas to copy and then provides a way to modify the value with the 'pll_translate_post_meta' filter. See: https://polylang.pro/doc/filter-reference/#pll_translate_post_meta

To give you an example of use the 'pll_copy_post_meta' and 'pll_translate_post_meta' filters, here is how Polylang uses them to translate the Yoast primary category when creating a new translation, see: https://github.com/polylang/polylang/blob/2.3.7/modules/plugins/wpseo.php#L310-L338

At worst, if you don't want to implement the 'pll_translate_post_meta' filter, you should deactivate the copy when the templates are translatable.
