### ISSUE TITLE
Create custom widget that locates inside theme 

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#479]
Hi 

Thank you for this great plugin !! I have just checked it . If I want to create custom widget that locates inside theme folder,is it possible?

I do not want to create custom one inside plugin as plugin update will delete that custom widget.

**Comment by Grafikart** [comment]
I comment on this issue since my idea is related.

I had the same problem and here is my idea (I can do the PR myself, but I need to know if @arielk thinks it's a good idea or not). 

```
add_action('elementor_init_widgets', function () {
    return [
        MyWidget::class,
        MyWidget2::class,
        'MyWidgetWithoutAutoload' => 'file/path/for/this/widget.php' // for class without autoload
    ]
});
```

I work using composer for my themes (using wordplate) so I think this approach is quite convenient ^^

**Comment by joshmarom** [comment]
We have an API for this kind of thing. Unfortunatly I don't have a documentation on that yet (there will be soon), but  you can try to follow this plugin example:

https://github.com/pojome/elementor-hello-world/blob/master/plugin.php#L35-L49

**Comment by Grafikart** [comment]
Oh nice ! I think we can close this issue since this hook solves the problem.
