### ISSUE TITLE
Page name changes automatically after editing page with Elementor

### ISSUE THREAD

**Issue by Elementalel** [pojome/elementor#4795]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I use an existent page with a certain link name, and change that name to something else, update it, then do some work in Elementor and save, the page name will reverse to the page link name. See below for more in-depth info

## Steps to reproduce

1. Use existent page with same name as link page **(Example: Link Name is website.com/link and pagename is Link)**. If you have no page, create a new one with the same name and same link. Then update.
2. Edit the page with Elementor Pro, and use Elementor Full Width canvas
3. Use the Post Title widget. Save page, and check if it works.
4. Go on your page, and edit the page name, and make it different than the link name **(Example: Link Name is: website.com/link and new pagename is This is a Link)**
5. Update page, and check if the Post Title widget has updated correctly (it should have)
6. Edit your page again with Elementor Pro. Add a widget, or edit some text or upload a picture, do whatever you want, even change the settings on the Post Title widget. The point is you have to change something so you can save. Now save.
7. Check your page, and the new title **(This is a Link)** has been changed to the original page link title **(Link).**

Additional info: If you keep the page you are editing open while you edit with Elementor, after changing the title, the title will not change on the edit page until you refresh. If you click on update, it will update accordingly.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Everything is updated to the latest version. I used Chrome as my browser.

Elementor version 2.0.16
Elementor Pro version 2.0.11
Wordpress version 4.9.6
Theme: Twenty Seventeen version 1.6
Chrome version 67.0.3396.87 (Official Build) (64-bit)

**Comment by bainternet** [comment]
@Elementalel 

We can't replicate the issue, 
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by Elementalel** [comment]
@bainternet 

I have no idea what happened in the first place, but I tried again today, and I cannot reproduce this either. I have not updated anything or changed anything since then, but it was only a one-time bug. If it happens again I'll contact support. Thanks!
