### ISSUE TITLE
Theme compatible with Elementor

### ISSUE THREAD

**Issue by ashokmhrj** [pojome/elementor#4798]
I am trying to make theme compatible with Elementor plugin. 
Are there points that I need to follow while making theme compatible.

Any help would be greatly appreciated.
Regards

**Comment by bainternet** [comment]
@ashokmhrj 

We have a documentation for that, https://developers.elementor.com/theme-locations-api/

other than that please feel free to open a new issue with a specific integration/code related question.

thanks.
