### ISSUE TITLE
Sticky Footer?

### ISSUE THREAD

**Issue by PwrSrg** [pojome/elementor#4799]
HOW do I create a Sticky Footer?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by giulianorapoz** [comment]
Is this now possible? I would also like to know how to achieve this.

**Comment by askab66** [comment]
Please add this feature especially when content of the page is short.

**Comment by kingdomkome** [comment]
Please add this feature, my pages with little content look ugly with a flying footer!

**Comment by shimsa** [comment]
+1
