### ISSUE TITLE
Compatibility with our plugin

### ISSUE THREAD

**Issue by rmorse** [pojome/elementor#4800]
Hi there I [opened a ticket here](https://wordpress.org/support/topic/integration-with-our-plugin/) and got referred to github.

Basically, [we have a plugin](http://searchandfilter.com), which filters any `wp_query` and gives the user a nice ui to do so.

I have got it working well with your post widget so no issues there.

However, we also have an ajax feature in our plugin, so the results can be reloaded without refreshing.  This is the thing I can't get working with Elementor.

Essentially, our plugin, via js/ajax will replace the whole elementor post widget with new html (new results), which is great - but I don't know/can't figure out the javascript you use to initialise this the layout of the post widget - without it, the new results remain hidden.

If I knew that snippet of code, I could get this working fully - do you think you can point me in the right direction?

I have a few customers asking for the at the moment.

Thanks

**Comment by bainternet** [comment]
@rmorse 

We don't use JavaScript to initialize the layout, we print the layout via PHP.

The only way I can think of to make it work would be to extend our Posts widget and customize it to your needs,

If you have a specific question, feel free to ask.

thanks.

**Comment by rmorse** [comment]
@bainternet, thanks for the message.

I meant your posts widget in Pro, not "Recent Posts" - which has a "masonry" checkbox option.

It looks like I've kindof figured this out:

`(function ( $ ) {
	"use strict";
	
	// detects when the S&F ajax request has finished and the content has been updated
	// - add scripts that apply to your results here
	$(document).on("sf:ajaxfinish", ".searchandfilter", function(){
		elementorFrontend.init(); //relayout elementor, we actually only want masonry, perhaps overkill?
	});
	
}(jQuery));`

Can you see any potential issues calling `elementorFrontend.init();`?  I only need to relayout the masonry  / post widget area, is there something a little more targeted?

Thanks
@bainternet, thanks for the message.

I meant your posts widget in Pro, not "Recent Posts" - which has a "masonry" checkbox option.

It looks like I've kindof figured this out:

`(function ( $ ) {
	"use strict";
	
	// detects when the ajax request has finished and the content has been updated
	// - add scripts that apply to your results here
	$(document).on("sf:ajaxfinish", ".searchandfilter", function(){
		elementorFrontend.init(); //relayout elementor, we actually only want masonry
	});
	
}(jQuery));`

Can you see any potential issues calling `elementorFrontend.init();`?  I only need to relayout the masonry  / post widget area, is there something a little more targeted?

Thanks
