### ISSUE TITLE
Additional Page filters for Portfolio and Posts

### ISSUE THREAD

**Issue by ShadowXVII** [pojome/elementor#4802]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The page filters for Portfolio and Posts widgets are limited. At the moment the only options are by Author or manually selecting pages are the only two options.

![image](https://user-images.githubusercontent.com/446329/41631855-492c3586-747a-11e8-9ac7-bd2cd3d84845.png)

**Describe the solution you'd like**
Additional filters based on Page metadata, e.g. Parent Page, limiting to Children or Descendants.

**Describe alternatives you've considered**
Using custom post types. Though this is overkill for simple scenarios.

**Additional Info**
🐞 Private pages aren't shown to a logged in user, even if the user has permission. Of course, Public shouldn't show.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
