### ISSUE TITLE
Audio overlay in "Posts" widget in Pro

### ISSUE THREAD

**Issue by chcover** [pojome/elementor#4803]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I am working on an audio-based project and would love to see an Elementor Posts project where audio can be overlayed on images featured in the Posts widget. 

**Describe the solution you'd like**
I think that an audio player option for the bottom of photos, and the ability to choose which post (with audio) is featured from a drop-down menu, is an addition to the Posts widget that would be beneficial to all Elementor users. 

**Describe alternatives you've considered**
I have attempted to align audio with posts manually, but they become misaligned on mobile. 

**Additional context**
![elementor custom page](https://user-images.githubusercontent.com/40412769/41632803-a5971ed8-7409-11e8-84a7-bacd34acdbcf.JPG)
How this audio/photo combination looks on a theme I purchased (outside of Elementor, but missing the custom page settings from Elementor that I love!)
![bask self hosted audio](https://user-images.githubusercontent.com/40412769/41632804-a5a59e4a-7409-11e8-9efe-0f337813bf9f.JPG)

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
