### ISSUE TITLE
Add lazy load to all widget.

### ISSUE THREAD

**Issue by zoom20092** [pojome/elementor#4806]
**Prerequisites**
- Lazy Load will improve loading time , useful for page speed.
- If Elementor able to custom lazy load on widget will improve site performance .

**Example**

- Add lazy load option on widget.

- ![lazy](https://user-images.githubusercontent.com/40418134/41642966-1aae2c0e-7494-11e8-8981-503e0fc31bdd.png)

     Thank you.

**Comment by bainternet** [comment]
@zoom20092 

You can use a 3rd party lazy load plugin which should work fine for images ex: 
a3 Lazy Load : https://wordpress.org/plugins/a3-lazy-load/
