### ISSUE TITLE
Change position of save and save as draft

### ISSUE THREAD

**Issue by tscheipi** [pojome/elementor#4807]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

Creating a post or page I´d like to save my work from time to time. But I only can do this after a klick on the options to save as draft. This is always an unnecessary step. And imho save means save and not publish! I come to you with this because now in additon one client was confused that his page was publishd when he clicked at save. He was of the opinion that save means save and for publishing he uses the publish button of WP.

Maybe you can change the positions and/or at least translate the english "save" into "Veröffentlichen" (in english publish) instead of "Speichern" (save)

Regards
Johannes

**Comment by bainternet** [comment]
@tscheipi 

> Introducing Elementor v1.9: Never Lose Momentum With Autosave

https://elementor.com/autosave/

As for the terms(save draft/publish/update), It's the exact same terms WordPress uses.

Now if you find the translation wrong or have improvement suggestion, please let the guys at [Elementor Translators](https://www.facebook.com/groups/elementortranslators/) know.

Thanks.
