### ISSUE TITLE
Integrate with 404 Redirected

### ISSUE THREAD

**Issue by robert-hopla** [pojome/elementor#4809]
https://wordpress.org/plugins/404-redirected/#installation

I need to add this code to 404.php but how?

<?php if (function_exists( 'wbz404_suggestions' ) ) { wbz404_suggestions(); } ?>

and how to get the suggestions to show on my 404 page?

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support,  Please try the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/


Thanks.
