### ISSUE TITLE
Elementor "Edit with Elementor" Upload to Media Library Causes Mixed Content Issues

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#4811]
Hello we have determined with our host flywheel that elementor is causing mixed content errors when we upload images to the media library via edit with elementor.​

It seems that when you upload an image from Elementor Editor vs uploading via wp-admin > media library, we run into mixed content issues. Especially if later we switch our domain name.  It seems like all the images we upload to wp-admin media library are fine when we changed our domain name, but the ones we uploaded via Elementor editor were not ok..they caused mixed content errors.

Uploading an image to Elementor editor > media library should be the SAME as uploading from wp-admin > media library.

​We ​Can't Change URL Name in Elementor URL Editor:
Also we should be able to manually change the url in elementor editor > media library if we ever change our url..but right now you have it greyed out so we can't​. 

Watch video I made of my screen for this issue: https://www.useloom.com/share/8a5afd716dc54b4c92fbd967baad6d6d

Specs:
Most updated wordpress
Most updated elementor
Most updated woocommerce & storefront theme

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
