### ISSUE TITLE
https://www.useloom.com/share/c55d63bcc36c492a99aea33c2dff6f95

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#4814]
Elementor Can't Bypass Theme Fonts For Certain Widgets only

You need to code all of your widgets the same to effectively bypass theme fonts...some you have done correctly, some have not.

Here is a video I made with steps to replicate. The first part shows you that the top part font doesn't work, the bottom font does work.

https://www.useloom.com/share/c55d63bcc36c492a99aea33c2dff6f95
Elementor nav menu widget- 
Does not properly display the font Poppins 700. This navigation menu should be bold.

Elementor menu widget: 
Displays the font Poppins 700 properly.​ 

​*This is on the SAME PAGE using the SAME FONT, but one widget works and the other doesn't.​
This is our page: https://bit.ly/2tafOp8
I've sent this back to you bc the support team cannot understand what I'm talking about..and its more of a developer issue.

Specs
Newest Version of Elementor Pro
Newest Version of Wordpress
Newest Version of Woocommerce
Newest Version of Woo Storefront theme

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines template for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
