### ISSUE TITLE
Exclusive Publishing Role

### ISSUE THREAD

**Issue by branfacab** [pojome/elementor#4820]
Hi guys, Would it be possible to have exclusive publishing rights for a user role.

The scenario is based on User A being able to edit add modify all pages but only be able to save those changes across all content on the website.

User B would be able to publish those pages apart from having all of the privileges of User A.

For a business website that uses only pages, it would be real helpful to have such a feature to have certain users just for content updates offline and another user group with additional privileges of being able to publish.
Thanks.

**Comment by bainternet** [comment]
Elementor gets and respects the publishing rights from WordPress so it should be possible already via 3rd party plugins.

thanks.
