### ISSUE TITLE
[FEATURE REQUEST] Events Calendar Integration

### ISSUE THREAD

**Issue by qwik3r** [pojome/elementor#4821]
It would be great to be able to use Events Calendar specific widgets and put them wherever you want on the page. Since the Event's Calendar doesn't presently have shortcodes for every single widget it's not possible to move things like tickets, or event dates and time or organizer around. Integration with Modern Tribe's Event's Calendar Pro is much needed.

**Comment by bainternet** [comment]
@qwik3r 

This should be requested from the 3rd party plugin authors, which we would love to help if they need. 


thanks.

**Comment by qwik3r** [comment]
Plugin authors don't care, so the people have to ask to do it. Especially Event's Calendar, they rarely support anything.

**Comment by drawcard** [comment]
Does it show up as a draggable widget in the sidebar? Sometimes 3rd party widgets will appear there. Or you can call the widget (or its PHP code) using a custom shortcode you've written, and use the Elementor Shortcode widget to embed it.

![image](https://user-images.githubusercontent.com/1435638/41754442-7b7257c6-7611-11e8-83dc-1d36cafed680.png)

**Comment by qwik3r** [comment]
Unfortunately not. There is zero integration right now and the shortcodes don't really work too well. It would require a real integration where the developers on both ends I guess decide to work with each other to make this happen.

**Comment by davidmabelle** [comment]
I would pay for such an integration.  Please consider having a way to crowdfund integrations so the community can vote and pay for suggestions.
