### ISSUE TITLE
How get mobile setting in $this->add_responsive_control()?

### ISSUE THREAD

**Issue by shangdev** [pojome/elementor#4822]
This is my code:
```
$this->add_responsive_control(
	'slidesPerView',
	[
		'label'              => 'Slides to Show',
		'type'               => Controls_Manager::SELECT,
		'options'          => [
			 '' => __( 'Default', 'elementor' )
		 ],
		'default'            => '3',
		'frontend_available' => true,
	]
);
```
Now, I want get this setting value.
In PC, I use 👍 
```
$settings      = $this->get_settings();
$slidesPerView = $settings['slidesPerView'];
```
But in mobile, how to get?

**Comment by bainternet** [comment]
@shangdev 

When you use `add_responsive_control` then in your $settings you should see 3 elements for example for this:

```php
$this->add_responsive_control(
	'slidesPerView',
	[
		'label'              => 'Slides to Show',
		'type'               => Controls_Manager::SELECT,
		'options'          => [
			 '' => __( 'Default', 'elementor' )
		 ],
	]
);
```
you get:

```PHP
$settings = $this->get_settings();
$desktop = $settings['slidesPerView']; // default name is always desktop
$tablet = $settings['slidesPerView_tablet']; // _tablet is added to the tablet value
$mobile = $settings['slidesPerView_mobile'];  // _mobile is added to the _mobile value

good luck.

**Comment by hmbashar** [comment]
> @shangdev
> 
> When you use `add_responsive_control` then in your $settings you should see 3 elements for example for this:
> 
> ```
> $this->add_responsive_control(
> 	'slidesPerView',
> 	[
> 		'label'              => 'Slides to Show',
> 		'type'               => Controls_Manager::SELECT,
> 		'options'          => [
> 			 '' => __( 'Default', 'elementor' )
> 		 ],
> 	]
> );
> ```
> 
> you get:
> 
> ```
> $settings = $this->get_settings();
> $desktop = $settings['slidesPerView']; // default name is always desktop
> $tablet = $settings['slidesPerView_tablet']; // _tablet is added to the tablet value
> $mobile = $settings['slidesPerView_mobile'];  // _mobile is added to the _mobile value
> ```
> 
> good luck.

Thank you, It's working.
