### ISSUE TITLE
.entry-title class in Elementor H1 titles

### ISSUE THREAD

**Issue by karlsan** [pojome/elementor#4823]
We’re adding page and post H1 titles with Elementor, getting output like this:

`<h1 class="elementor-heading-title elementor-size-default">TITLE</h1>`

We need to add “entry-title” as an additional class to all H1 elements added via Elementor and would like to find a global solution. Is there anyway this can be done through Elementor?

**Comment by bainternet** [comment]
Not really.

also, Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support,  Please try the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/


Thanks.

**Comment by karlsan** [comment]
Hi @bainternet, appreciate the reply. We were already in touch with support, they told us this is not current functionality, support can only offer help with current functionality and we should post it as a feature request on GitHub.

Perhaps my phrasing above made it sound like a plain support request rather than a feature request, but it's a bit frustrating being told by support that it's not a support request and then here being told that it's not a feature request, additionally in bold that these issues "**ARE NOT FOR SUPPORT**".

As for my **feature request**, since Elementor passes its own classes to the H1 tags it adds, my wish would be for a filter/function to add additional classes. I don't know how Elementor passes these classes, but ideally there would be a way to add additional ones.

If this is technically not possible, or you don't think it's a useful function, then by all means keep this issue closed. Otherwise I would very much appreciate some feedback.

**Comment by karlsan** [comment]
In case someone else comes across this issue, for now we added the class with a bit of JavaScript in the footer, checking first if Elementor is used on the page:

```
<?php
$elementor_page = get_post_meta( get_queried_object_id(), '_elementor_edit_mode', true );
if ( ! ! $elementor_page ) { ?>
    <script type="text/javascript">
    $(function(){
        $('h1').addClass('entry-title');
    });
    </script>
<?php } ?>
```

Perhaps not very elegant, but seems to work OK for us.
