### ISSUE TITLE
Image Alignment is being bypassed by WooCommerce Storefront Theme

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#4825]
Prerequisites:
Wordpress, Elementor Pro, Woo Storefront Theme, Woo commerce, 

Steps to replicate:
Create a page
Add a section
Add an image (svg is what we used also try jpg)
Click Center
You will notice that you cannot center.
Video I made for you here shows this: https://www.useloom.com/share/f0dae85c54e94d12afdae1460d868e9d

Isolating the problem:
Storefront bypasses our alignment. The only way around this is to write code in custom css 
"selector img{display: initial;} " which Elementor support told us to do, but we think it would be BETTER if you have an on off switch in the widgets to allow us to bypass theme code or just code in the widget to force bypass. Much cleaner and more efficient that way.

System info:
Newest Update of Wordpress
Newest Update of Storefront
Newest Update of WooCommerce
Newest Update of Elementor Pro

**Comment by bainternet** [comment]
@smile00000 

thanks for reporting.

**Comment by smile00000** [comment]
@bainternet  @KingYes Thank you for taking the time to read our request. Please let us know when you have included the fix in an Elementor update. Cheers.  :)
