### ISSUE TITLE
Font Weight is being bypassed by WooCommerce Storefront Theme in certain Widgets ONLY

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#4826]
Prerequisites:
Wordpress, Elementor Pro, Woo Storefront Theme, Woo commerce,

Steps to replicate:
First Set of steps to see when it does not work with certain widgets:
Create a page
Add a section
Add a nav menu widget
Add some menu items
Make Font Poppins 700 
You will notice that the font is not bold
https://www.useloom.com/share/c55d63bcc36c492a99aea33c2dff6f95

Second set of steps to see when the font does work
Create a page
Add a section
Add a list widget
Add some list items
Make font Poppins 700
You will notice that this widget correctly displays the font in BOLD.

Isolating the problem:
Storefront bypasses our font weight on the "elementor menu link widget", but does not bypass the font weight in "elementor list widget" . The only way around this is to write code in custom css
".elementor-nav-menu a {font-weight: inherit;}" which Elementor support told us to do, but we think it would be BETTER if you have an on off switch in the widgets to allow us to bypass theme code or just code in the widget to force bypass. Much cleaner and more efficient that way. All of your widgets should be able to bypass weight and other font styles not just some.

System info:
Newest Update of Wordpress
Newest Update of Storefront
Newest Update of WooCommerce
Newest Update of Elementor Pro

**Comment by arielk** [comment]
Does the problem still occur?

In order for us to look into this matter, please contact support @ elementor.com, with complete login information to access your website, and our support team will try to assist.
