### ISSUE TITLE
SoundCloud misses the dynamique function

### ISSUE THREAD

**Issue by logobby** [pojome/elementor#4827]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi,

Like I did with the Video Widget I wanted to get a custom field from ACF, a link for SundCloud, to display it in my custom Single Template Page built in Elementor Templates but the SoundCould Widget misses the dynamique function.

For the moment I'm using the Text Editor Widget but it's not the best solution for me.

I need this function for a client this month if it's possible.

Thanks a lote.

Best,
Sam
![image](https://user-images.githubusercontent.com/40466413/41818282-16f88da2-77b4-11e8-93ae-94e504cd920a.png)

## Isolating the problem
<!-- MARK COMPLETED ITEMS WITH AN [x] --

>
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
ref: #4889
