### ISSUE TITLE
Elementor Dynamic Widget Internet Explorer Bug

### ISSUE THREAD

**Issue by anupamapadma** [pojome/elementor#4829]
When I use the Display Conditions feature on the Navigation Bar Widget so that it displays on the search result page. The search results no longer show up. Is there a way to fix this so I can have the nav bar at the top of the search results.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
