### ISSUE TITLE
Override/extend widget render();

### ISSUE THREAD

**Issue by justpie** [pojome/elementor#4830]
Hi All, 

Is it possible to override or change the output of a widgets render() function?

In my scenario I'm trying add anchor elements to every instance of the accordion.  I glanced through the documentation and the before_ and after_ hooks didn't work for my specific use case. 

Thanks!

**Comment by bainternet** [comment]
@justpie 

You can unregister the widget extend its class with overwriting the render method to your needs and register your own.
