### ISSUE TITLE
Element meta - widget post - elementor pro

### ISSUE THREAD

**Issue by NAROLLES** [pojome/elementor#4833]
I publish here at the request of the support of elementor

I would like to add a meta data element that does not exist as :

- update date of an article
- shortcode - number of wiews
etc ...

how create it
thanks

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by NAROLLES** [comment]
Hi
it's not a new feature request
I publish here at the request of the support of elementor
i'm not one developper and expert
thanks
