### ISSUE TITLE
[Feature Request] Elementor Pro: Paypal Email Action

### ISSUE THREAD

**Issue by Source3Media** [pojome/elementor#4835]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In a lot of form builders, you're able to have a PayPal form action for things like donations. I've done a lot of digging today and I can't seem to find that ability or a plugin that adds that ability to Elementor(Pro). 

**Describe the solution you'd like**
So what I am asking is, could it be added to Elementor Pro to be able to have a Paypal form action. It's a consistency issue when someone has to use two+ different plugins for forms across their website.

**Comment by bainternet** [comment]
For things like donations via PayPal, you can create a donation link in PayPal and use the redirect after the submit.

You can also create deeper integration via the provided PHP and JavaScript hooks if you code.

Other than that, Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
