### ISSUE TITLE
Menu – add active state for child pages within menu

### ISSUE THREAD

**Issue by christiaank** [pojome/elementor#4837]
Add an active state for parent nav element when viewing child pages below that page. So for example in the below, viewing any child page should display the "Parent Page" as having an active state to visually show users they are within that section / structure.

ie.

Parent Page (should be active when viewing child pages below)
 - child page
 - child page
 - child page

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
Elementor uses the WordPress native wp_nav_menu, so you can use the hooks and filters provided to add classes as needed.

not something that will be controlled via Elementor anytime soon.

thanks.

**Comment by black-eye** [comment]
Well the classes are already there from WP (current-menu-parent, current-menu-ancestor). The problem is, that I'm unable to style them via Elementor. Even simple chekbox ala "Use Current Active State Also for Parent Menu Items".

Unfortunatelly your answer is one of the reasons I won't be able to use Menu Widget "any time soon".  :-(

**Comment by jklovance** [comment]
This only works if sub-menu urls are in the form '/menu1/sub1', '/menu2/sub1', etc.

There is a js way to do this based on the URL and the menu item;
`   const pages = ['menu1','menu2','menu3'];
    const menuItems = ['menu-item-111', 'menu-item-2222', 'menu-item-333'];
    const url = window.location.href;
    jQuery.each(pages, function( index, page ) {
        if (url.search(page) > -1) {
            const search = '.'+menuItems[index]+' a';
            jQuery(search).addClass('elementor-item-active');
        }
    });`
The variable 'pages' is the list of url fragments to look for. The variable 'menuItems' is the class of the <li> tag for the top menu item All this does is finds the URL of a page from a menu and then added the active class to the top menu anchor.

Hope this helps

**Comment by wangstein** [comment]
@jklovance Thank you for this! Totally worked for me.
