### ISSUE TITLE
Set predefined colors/fonts using a hook/filter.

### ISSUE THREAD

**Issue by DeoThemes** [pojome/elementor#4838]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I can't find any hook/filter that allows to set predefined colors and fonts. The way how Elementor handles global colors and fonts is pretty good, but we need to control it's default output.

It would be great to have a filter to set a custom colors/fonts.

**Comment by Micemade** [comment]
Hook / filter would be really great, but I have another idea - create Customizer control for global color and fonts ( and in Elementor sidebar as well ). :)

**Comment by bainternet** [comment]
@DeoThemes 

The is no need for a filter, they are saved in the options table using the Options API, so you can use the native WordPress filter `pre_update_option_{$option}` hook for these options:

- elementor_scheme_color
- elementor_scheme_typography
- elementor_scheme_color-picker

@Micemade 
Follow #3345

thanks.

**Comment by Micemade** [comment]
Yeah, that's also a way to go (I know about the options API possibility), but moving these settings to Customizer (via theme_mod) would be better in a way - since themes should be more about styles (including color palete,  fonts), global colors/fonts would be more interchangeable when switching themes ...
Adding something like "Elementor globals" section (with global colors/fonts) via Customizer API would make possible themes to hook to that settings, and use same style settings. Customizer settings would be easy fallback to existing options table values.
Just my (humble) opinion ... ;)

**Comment by DeoThemes** [comment]
No matter how many times I tried, it's always failed. Still can't set predefined fonts and colors.
When using **pre_update_option** filter it updates colors every time you hit save button.

Instead I try to use **update_option** function, but additionally check if the colors are not yet saved:

`
add_option( 'deo_elementor_colors', 0 );

function deo_update_elementor_defaults() {
	if ( get_option( 'deo_elementor_colors' ) != 1 ) {
		update_option( 'elementor_scheme_color', array(
			1 => '#49484F',
			2 => '#908E99',
			3 => '#908E99',
			4 => '#FF7070'
		) );
		update_option( 'deo_elementor_colors', 1 );
	}
}
add_action( 'init', 'deo_update_elementor_defaults' );
`

It works, the values are being updated in the DB only once, but they are not updated in the front-end because of CSS with old values. As I understand the new CSS is only generated after you hit **save button**. So how can I update these values and regenerate new CSS?

**Comment by TinBoyko** [comment]
According to [https://github.com/pojome/elementor/blob/0cfd51b929e9bbd8ddcd495350d443767a863124/includes/managers/schemes.php#L233](url)
You can do it in this way:
```php
add_action('after_switch_theme', function () {
	$theme_color_scheme = array(
		"1" => "#111111",
		"2" => "#222222",
		"3" => "#333333",
		"4" => "#444444"
	);
	$schemes_manager = new Elementor\Schemes_Manager();

	$scheme_obj = $schemes_manager->get_scheme('color');
	$scheme_obj->save_scheme($theme_color_scheme);
});
```

**Comment by gerardreches** [comment]
> 
> 
> According to [elementor/includes/managers/schemes.php#L233](https://github.com/pojome/elementor/blob/0cfd51b929e9bbd8ddcd495350d443767a863124/includes/managers/schemes.php#L233)
> You can do it in this way:
> 
> ```
> add_action('after_switch_theme', function () {
> 	$theme_color_scheme = array(
> 		"1" => "#111111",
> 		"2" => "#222222",
> 		"3" => "#333333",
> 		"4" => "#444444"
> 	);
> 	$schemes_manager = new Elementor\Schemes_Manager();
> 
> 	$scheme_obj = $schemes_manager->get_scheme('color');
> 	$scheme_obj->save_scheme($theme_color_scheme);
> });
> ```

Is this for default colors or for the color picker?

**Comment by Gnodesign** [comment]
Hi,

Is there any easy implementation to do this with the global colors now that the schemes are deprecated? This will be an issue with a lot of customers and I need to fix this asap.

**Comment by gerardreches** [comment]
> Hi,
> 
> Is there any easy implementation to do this with the global colors now that the schemes are deprecated? This will be an issue with a lot of customers and I need to fix this asap.

+1, I need a way to fix this also

**Comment by DeoThemes** [comment]
+ 1

**Comment by gerardreches** [comment]
Maybe we should open this issue again instead of hoping that they will take a look again at a closed issue while there are so many open issues in this repository.

**Comment by igorchernenko92** [comment]
+1

**Comment by gerardreches** [comment]
Almost one year later and we haven't gotten any solution.

**Comment by Vik2Ree** [comment]
> > According to [elementor/includes/managers/schemes.php#L233](https://github.com/pojome/elementor/blob/0cfd51b929e9bbd8ddcd495350d443767a863124/includes/managers/schemes.php#L233)
> > You can do it in this way:
> > ```
> > add_action('after_switch_theme', function () {
> > 	$theme_color_scheme = array(
> > 		"1" => "#111111",
> > 		"2" => "#222222",
> > 		"3" => "#333333",
> > 		"4" => "#444444"
> > 	);
> > 	$schemes_manager = new Elementor\Schemes_Manager();
> > 
> > 	$scheme_obj = $schemes_manager->get_scheme('color');
> > 	$scheme_obj->save_scheme($theme_color_scheme);
> > });
> > ```
> 
> Is this for default colors or for the color picker?

I did it just that way but after the recent update rolled out (ver. 3.15.1); $scheme_obj started giving off "bool(false)" which in turn makes my wordpress site crash. Although it seems this particular method is now outdated; what is the better way to do it now?
