### ISSUE TITLE
My templates -> Display Conditions: support polylang for localisation

### ISSUE THREAD

**Issue by ziogaschr** [pojome/elementor#4839]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In one of my clients' site, I am using Polylang to translate the content. In Polylang I enabled support for **My Templates** Custom post type, so as to translate both **Header** and **Footer** templates. At the end elementor only loads the EN template, as there is no way to set a **display condition** in order to either select a Polylang language or set a regex to catch the language in URL or something similar. 

**Describe the solution you'd like**
**My Templates** to have a **disaply condition** for matching Polylang languages.

**Describe alternatives you've considered**
For now I dealt with it, by setting a parent page for translated items. The parent page and the Elementor templates had to be in EN language, no matter I wanted to use them for DE.

**Comment by bainternet** [comment]
@ziogaschr 

Elementor can't guess which multilingual 3rd party plugin you are using and we don't want to keep the conditions system light as possible.

You can, however, extend the conditions system and add your own (like Polylang language based condition ).

But that will not help you in your case because the conditions system currently only supports "OR" between its rules which in your case will limit the condition to language-based only. 

A better approach is to use the provided hooks by elementor and Polylang.
The workflow should be to only define the conditions on the main/default language and not on the connected translation templates.

then you can use this hook `elementor/theme/get_location_templates/template_id` to change the id of the template based on the language, ex:

```PHP
// Polylang
add_filter( 'elementor/theme/get_location_templates/template_id', function( $post_id ) {
	if ( function_exists( 'pll_get_post' ) ) {
		$translation_post_id = pll_get_post( $post_id );
		if ( null === $translation_post_id ) {
			// the current language is not defined yet
			return $post_id;
		} elseif ( false === $translation_post_id ) {
			//no translation yet
			return $post_id;
		} elseif ( $translation_post_id > 0 ) {
			// return translated post id
			return $translation_post_id;
		}
	}
	return $post_id;
} );
```

**Comment by ziogaschr** [comment]
Thanks a lot for your great solution @bainternet.

Your remark about 3rd party plugin support is very accurate. I searched in your `conditions_manager.php` to find any hooks or filters that I could use to add the functionality I needed, but with no luck.

Thanks for letting me know about the `elementor/theme/get_location_templates/template_id` hook as I hadn't found this out myself. Your code worked like a charm.

**Comment by Webtica** [comment]
Sorry to reopen this. 
I am not sure how to get this to work. 
@ziogaschr can you send your code as example? I am not sure what  ID to put where. 

Thanks

**Comment by ziogaschr** [comment]
Just copy the code above in `functions.php` of your template.

Then in Polylang settings enable `Custom post types and Taxonomies` -> `My templates`.

Last in `Elementor` -> `My templates`, create translated content for the template you want.

**Comment by Webtica** [comment]
@ziogaschr 
Okay thanks i see! 
What did you pick for conditions? 
As i got to translate it but when i choose whole site it shows 1 language on all.

**Comment by ziogaschr** [comment]
I had the same, but the code snippet above fixed it.

**Comment by Webtica** [comment]
Did you have problems when loading the editor on normal pages after this? 
I have Pro 2.1.0 Beta 2 and latest Elementor 2.1.1 when i try to load the editor it keeps showing the loading screen.

**Comment by Webtica** [comment]
Sorry! I found the issue. It seems to be every Template used on that specific page needs to be in a language.

**Comment by Webtica** [comment]
Hey @ziogaschr  & @bainternet 
Sorry to reopen this. I seem to have trouble with the code posted above. 
IT works but I need to recreate every template again 4 times for all languages even if it is the same for all Langs. When I want to insert a template i made for EN lang and insert it on a FR page it doesn't show anything. 

So any idea how i can make 1 template (1lang) and use it on all languages in polylang?

**Comment by Webtica** [comment]
Hi @ziogaschr & @bainternet

Followup of my post before. 
It seems to be an issue with woo archive templates in the latest 2.1.0 Beta 2. 
As when i just create a normal section template in 1 language i can insert the shortcode on all pages even other languages. 

You can see here: 
https://raramurisandals.webticastage.be/linten/sales/ 
and here: 
https://raramurisandals.webticastage.be/en/ribbons/sales/

As you see the Circles are normal section templates.
I inserted these in the english version of the page as shortcodes 
I also inserted the product archives as shortcodes and they don't show up on the english page. 

Any ideas what this could be? 
Thanks

**Comment by Webtica** [comment]
Another reply. 
I just tested on a non polylang site just Elementor and E Pro beta 2.10 v2 
Product Archive shortcode not working on beta 2 when inserting with shortcode widget. 
The HTML is there but it doesn't display anything. Just some whitespace. 

I also posted this on the Beta post thread.

**Comment by nicomollet** [comment]
Conditions still don't work with Polylang.

It looks like, when saving a conditions, that a cache is created in the option `elementor_pro_theme_builder_conditions`.
And when doing that only the templates in the language of the edited condition are generated and saved in the option.

So the consequence is, the option never have all the languages at the same time.

**Comment by Infestix** [comment]
Yeah, I hate to reopen this case. But it seems i cant resolve this problem. 
I have to languages defined in Polylang, Estonian and English.
In my testbed i have Elementor archieve template targeted to custom post type. That same template is also translated to both languages. And it still shows all the content in english.

In estonian> 
http://www.vuron.ee/kirjak/?elementor_library=esinejad-2018-est
In english>
http://www.vuron.ee/kirjak/en/?elementor_library=esinejad-2018-eng 

I tried everything mentioned above, but none of that worked.

**Comment by EdenK** [comment]
In WPML it is possible to set `suppress_filters` to true in `pre_get_posts` action to fix the problem with the conditions cache regenerate function. Probably can used for Polylang as well to set the lang to ''.

```
function wpml_elementor_library_conditions( $query ) {
    if( $query->query_vars['post_type'] === 'elementor_library' && $query->query_vars['meta_key'] === '_elementor_conditions' ) {
        $query->set( 'suppress_filters', true );
    }
}
add_action( 'pre_get_posts', 'wpml_elementor_library_conditions' );
```

**Comment by nicomollet** [comment]
Thank you @EdenK you inspired you to make it work for Polylang. 

```
<?php
/**
 * Fix for Elementor template conditions not compatible with Polylang (you need to save again one of your templates conditions to make it work, after putting this function in your plugin/theme)
 * Needs to be priority 1, since Polylang uses the action parse_query which is fired before pre_get_posts
 *
 * @link https://github.com/polylang/polylang/issues/152#issuecomment-320602328
 *
 * @param WP_Query $query
 */
function polylang_elementor_library_conditions_parse_query( $query ) {
	if ( is_admin() && $query->query_vars['post_type'] === 'elementor_library' && $query->query_vars['meta_key'] === '_elementor_conditions' ) {
		$query->set( 'lang', '' );
	}
}
add_action( 'parse_query', 'polylang_elementor_library_conditions_parse_query', 1 );
```

**Comment by Tristan29photography** [comment]
Yep, 
I've been struggling to make it work, but the trick of @bainternet worked.
 I didn't work at first, but tweaking around, emptying caches, It started to show correctly in all languages. Elementor Support was not abble to give me this solution in direct messages...

as @ziogaschr said, the order for saving the templates matters. In my case I had to save first the translated version, and Finally to resave the display conditions of the template in main site language. 

@gratitudegraphics To be able to edit the templates that are not in the default language, the only trick I found is to temporarily deactivate the translations  in Polylang 
(Settings Disabled. Polylang-> Custom post types and Taxonomies -> My templates.) Then You can edit your template and reactivate translations later...

**Comment by deckerweb** [comment]
Yes, we released the plugin for free on .org repo which contains the above code - plus: the Elementor My Templates are automatically added for Polylang CPT support :-)
Thanks to Elementor developers and the awesome community contributors. You'll find the plugin here: https://wordpress.org/plugins/connect-polylang-elementor/

We also added a native Elementor Language Switcher Widget for Polylang, plus full Elementor Finder integration. Special thanks to Brad Johnson @madbradj

**Comment by Webtica** [comment]
@deckerweb thanks! Just tested it on a staging site and it works amazing. Will post bugs if there :-) was looking forward to a solution like this.

**Comment by chaubaolong2003** [comment]
With Elementor, in Templates ->Theme Builder: a Single template have Instances (In Category #89); with Category #89 is English.
if you want create an other Single template with condition have an other language:
- you first create a new Category (#100) in English. 
- create a new Single template and set condition to Catagory (#100)
- then change language of Category (#100) to your language you want.
- Done!

**Comment by vojjin** [comment]
All of this is not working as I really need. I have 14 languages on website. I had to create different 14 menus and 14 headers. However, whenever I open, for example, search page, or category list page, conditions are not applied and I cannot set appropriate header, it is using templates default header (and footer and everything else...)

**Comment by Nathblack** [comment]
Hi there,
i have the same problem,
did activate the polylang elementor connect plug in,
did change functions.php and conditions-cache.php,
BUT i still have only one theme builder (header/footer) workin, when i switch languages.

Any other idea ?
Thks everyone.

**Comment by Nathblack** [comment]
Hello

**Comment by erayaksoy** [comment]
> Hi there, i have the same problem, did activate the polylang elementor connect plug in, did change functions.php and conditions-cache.php, BUT i still have only one theme builder (header/footer) workin, when i switch languages.
> 
> Any other idea ? Thks everyone.

i solved in edit elementskit (header/footer) list. Change the template settings > conditions > entire site and make activate and save.

**Comment by Caesaremp** [comment]
> Hi there, i have the same problem, did activate the polylang elementor connect plug in, did change functions.php and conditions-cache.php, BUT i still have only one theme builder (header/footer) workin, when i switch languages.
> 
> Any other idea ? Thks everyone.

I solved assigning the page to another user (who has assigned only this page) and setting the visualization condition on that user.
