### ISSUE TITLE
column & row layout 

### ISSUE THREAD

**Issue by bimalchettri** [pojome/elementor#484]
hi i just came to know about elementor and  tested its the functionality, column and row worked fine in chorme & IE but having issue with safari 5.1.7 on windows 7, column showing as in mobile device.
test site here www.the-himalayas.co.nf

**Comment by joshmarom** [comment]
Safari 5.1 is a relatively old version that only has partially supports css flexbox.
Considering that it is used just by a decreasing 0.09% of the users globally, I am not sure resolving this compatibility issue is one of our top priorities, nevertheless, we will look into it.

Thank you for your feedback.

**Comment by arielk** [comment]
Fixed https://github.com/pojome/elementor/commit/27a276d562128c228a9f0473c577e6515c64d942
