### ISSUE TITLE
nav widget scrolling on mobile

### ISSUE THREAD

**Issue by Aisha56** [pojome/elementor#4840]
Nav widget menu on mobile.
When scrolling through a menu with dropdown openened on mobile,  touching the screen to scroll triggers items to have a background highlight (hover). This is very confusing. Pls make sure "hover' on mobile can be disabled. Pls make sure only when item gets selected it gets a background hightlight (if chosen).

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
