### ISSUE TITLE
Shortcut key to show "widgets list"

### ISSUE THREAD

**Issue by michellepace** [pojome/elementor#4841]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated at the number of times I have to click the little widgets button (see screenshot). For example, when I drag and drop a new widget to my page, to add a new little widget I have to re-click that button. 

**Describe the solution you'd like**
A simple keyboard shortcut key which will display the widgets in the builder no matter where you are in the builder. eg "Ctrl +Q"

![screenshot](https://user-images.githubusercontent.com/512813/41815635-596ee3cc-7771-11e8-96d9-7f4669c179f1.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
