### ISSUE TITLE
Condition for a specific control

### ISSUE THREAD

**Issue by AbanobAAkram** [pojome/elementor#4843]
Hello Elementor's Team :)

I'm working now on developing a new custom widget for Elementor, and I need to put some conditions for specific controls, I found that 'condition' parameter in "add_control" function is actually an array, but I need to make the control to appear if one of the conditions is true not both of them, I'm not sure how this can be done in the code, so may I ask you to help me with that ? 

Have a great day!!

Thanks,
Abanob

**Comment by bainternet** [comment]
There are two parameters you can use:

 * `condition` which is a flat array of key-value with an AND between each of the conditions.
 * `conditions` ( mind the "s" ) which is used for more complex conditions where you can define relations and nested conditions.

See this issue for reference: https://github.com/pojome/elementor/issues/4237

**Comment by AbanobAAkram** [comment]
It worked !!

Really thanks bainternet :)

**Comment by babakfp** [comment]
Thank you "bainternet"

**Comment by babakfp** [comment]
> There are two parameters you can use:
> 
> * `condition` which is a flat array of key-value with an AND between each of the conditions.
> * `conditions` ( mind the "s" ) which is used for more complex conditions where you can define relations and nested conditions.
> 
> See this issue for reference: #4237

Thank you "bainternet"

**Comment by TheFirsh** [comment]
I wrote extensively about [control conditions](https://letswp.io/conditional-controls-in-elementor-extensions/), hopefully someone can learn from it.
