### ISSUE TITLE
Elementor Portfolio widget request: place post title under image, not on hover. 

### ISSUE THREAD

**Issue by JohnWestEast** [pojome/elementor#4844]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
If you use the portfolio widget as a related posts functionality underneath your posts. Having the titles only show up on a hover is not so efficient. 

It would be better and more clear if there was a possibility to put the titles beneath the images. So readers can instantly see what the related posts are about. 

**Describe the solution you'd like**
I'd like to have a feature for the text to appear underneath the images fixed, instead of on top of the images on a hover. 

**Describe alternatives you've considered**
It's not possible to adjust this in the post widget. 

**Additional context**
<img width="930" alt="screen shot 2018-06-24 at 12 02 18" src="https://user-images.githubusercontent.com/39887660/41818009-8a892334-77a6-11e8-8408-abf77b9cc3a3.png">
Difficult to instantly see what posts are about
https://www.youtube.com/watch?time_continue=421&v=W8Bpez7SVdg

**Comment by bainternet** [comment]
I merged this issue with  #1922, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
