### ISSUE TITLE
[Bug] Background-attachment: fixed. Not working in the version 2.0.16

### ISSUE THREAD

**Issue by romeladlib** [pojome/elementor#4845]
Hi,  Background-attachment: fixed is not working as well as when adding a texfield.Upon saving, the default styling is the one reflecting in the live site.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by romeladlib** [comment]
**Prerequisites.**
Just a usual creation of a section.

**Steps to replicate.**
1. Create a section.
2. add text and image
3. once you change the background attachment to fixed - boom! background is gone
![image](https://user-images.githubusercontent.com/39505976/41818827-c00e2e72-77e8-11e8-8896-9506eec182d3.png)
4. hit Save.
5. Preview - you can see that the headline's styling is also broken:
![image](https://user-images.githubusercontent.com/39505976/41818845-0454604c-77e9-11e8-9679-94def7423f81.png)

Isolating the problem.
Tried activating/deactivating plugin, install /uninstall both elementor & elementor pro but still no luck.

**This should be the look. This is before the latest update to  2.0.16**
![image](https://user-images.githubusercontent.com/39505976/41818869-614b828a-77e9-11e8-9f5f-8b721018c147.png)

**System info.**
![image](https://user-images.githubusercontent.com/39505976/41818872-724a5fc0-77e9-11e8-9df1-360f269a4f31.png)
