### ISSUE TITLE
[ Feature request ] Support the YouTube Playlist in the Video Widget

### ISSUE THREAD

**Issue by logobby** [pojome/elementor#4846]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
At the moment the Video Widget doesn't support playlist from YouTube. We can see the playlist url only.

**Describe the solution you'd like**
As it's working in the text editor - why we can't support the playlist link also in the video widget?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can use the HTML widget to embed the playlist.

Thanks for the feedback.
