### ISSUE TITLE
Elementor does not save default value in the database

### ISSUE THREAD

**Issue by hamid159** [pojome/elementor#4851]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I created a custom widget with some fields. Also some fields had default value. But when I added the widget in my page without changing the values of fields (so some fields had their default values) and clicked on save button. Elementor didn't save the default values in "_elementor_data" post meta. It should save the value in db even thought we have not changed the default value.

Assume that we have a date dropdown (from 1 - 31). And we give it a default value as current date in php as `date('d')`. If user do not change the default value in his page or post, and directly save the page/post, then there would be problem. As Elementor didn't save the value in the database (because it was default value and user didn't change the value while editing the widget), next day the value of that specific field will automatically change because now the date has increased by 1. 

So, Elementor should save all field values no matter it is default value or user has changed it.

## Steps to reproduce
- Create a custom widget with dropdown field of date (from 1 - 31) and give it default value as `date('d')`
- Add that widget in a page and directly save the page without doing anything.
- See the Elementor has saved the value in database or not.

**Comment by bainternet** [comment]
@hamid159 

That is correct, we don't save un-necessary default values unless the user triggers a "Change" event.
