### ISSUE TITLE
Unique ID resetted into Form Widget

### ISSUE THREAD

**Issue by marcopeca** [pojome/elementor#4852]
If I change fields order with drag and drop into form widget the unique ID is resetted.

Maybe it's better that, if I customize this Unique ID, it will be unchanged.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
