### ISSUE TITLE
Document Elementor css grid

### ISSUE THREAD

**Issue by sf-steve** [pojome/elementor#4854]
## Prerequisites

- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

**What problem is your feature request going to solve? Please describe.**
As a theme developer, Elementor is great, allowing clients to build complex layouts without additional dev time, and the developer docs make creating custom widgets a breeze. 

However, in order to maintain layout consistency, custom widgets and non editable page elements (headers, footers, custom templates) should follow the same grid.
Since elementor allows customization on a per section basis, it will still be possible for a site editor to break the consistency, but having it work by default is better the not.

**Describe the solution you'd like**
Documentation of the CSS grid used by elementor, including default padding, margins and responsive flow.

**Describe alternatives you've considered**
Adopt a popular grid system that is already well documented, such as Bootstrap 4 or Foundation 6.
As much as i would like this to happen, i realize it is not really feasible. 
As a side note, negative margins for 'rows' would be a huge improvement - the current setup makes consistent layout with nested columns a royal pain in the ****

**Comment by black-eye** [comment]
Following this. You mention some of the problems I'm struggling with too (and so do my clients).
Not sure, how to solve them, though (on Elementor level).

Maybe it would be usefull to have some level of the main grid customisation - e.g. ability to set the different values for basic column padding defaults (I mean values like: 50px for wider and 80px for wide), and maybe different for top/bottom and left/right.

As for the negative margin rows, it's really long-time pain (#452) - sad bat true... :(

**Comment by DeoThemes** [comment]
Exactly what I was thinking and I wanted to publish about this issue, but you did it first :) Currently Elementor grid system is so uncomfortable for the devs and users. Why reinventing the wheel when perfect grid system already exist ( ex.: Bootstrap 4)

**Comment by moseskerub** [comment]
Maybe Elementor could use the CSS Grid Grid-Gap feature? meaning that the assigned gap would only occur between rows and columns, and not on the "outer frame" e.g. a grid gap of 40px wouldn't add 40px margin before the first column and after the last column.

IMO a setting like that should be default, and fairly hard for the end user to break (though the ability to "break" it should exist)

**Comment by arielk** [comment]
This is an important issue that we are checking all the time, in the meantime, please note to this discussion: https://github.com/pojome/elementor/issues/965

**Comment by bainternet** [comment]
Thanks, everyone for contributing to this discussion.


Currently, this is not a priority for many reasons, but mainly because the whole point of using a page builder like Elementor is to have the ability to break out of girds and each column width is (or at least, can be) dynamic.

We do have plans a for developers partially in this area.

thanks again.

**Comment by londonpete1958** [comment]
Elementor has taken the Flex-box route with it's container based approach. But what I don't understand is whey they would want to generate far more css taking this route rather than CSS Grid.
