### ISSUE TITLE
[Feature Request] Bookbub added to social icons widget

### ISSUE THREAD

**Issue by catetayler** [pojome/elementor#4862]
## Prerequisites

 [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
 [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As an author, having the Bookbub social icon to use with the widget would be extremely helpful. Bookbub is quickly growing as a place to connect with readers and gain followers and reviews. Most authors I know are trying to increase their Bookbub following and being able to add the icon to the widget with our other social icons would be great for connecting with our readers.

**Describe the solution you'd like**
Add the Bookbub icon to the choices within the social icons widget.

**Comment by bainternet** [comment]
@catetayler 

Thanks for the suggestion, we currently use FontAwesome 4.7 for our social icons widget and sadly they don't have an Icon for BookBub yet.

Here is the request in their repo: https://github.com/FortAwesome/Font-Awesome/issues/9496

Once it's included, we could add it.

thanks again.
