### ISSUE TITLE
Trying to display a single product page after saving it brings out an error

### ISSUE THREAD

**Issue by babstudio** [pojome/elementor#4865]
Fatal error: Uncaught Error: Call to a member function has_attributes() on string in /home/babstudi/public_html/tozeret-hasade.co.il/wp-content/plugins/woocommerce/includes/wc-template-functions.php:1658 Stack trace: #0 /home/babstudi/public_html/tozeret-hasade.co.il/wp-includes/class-wp-hook.php(286): woocommerce_default_product_tabs(Array) #1 /home/babstudi/public_html/tozeret-hasade.co.il/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /home/babstudi/public_html/tozeret-hasade.co.il/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/product-images.php(112): apply_filters('woocommerce_pro...', Array) #3 /home/babstudi/public_html/tozeret-hasade.co.il/wp-content/plugins/elementor/includes/base/widget-base.php(474): ElementorPro\Modules\Woocommerce\Widgets\Product_Images->render() #4 /home/babstudi/public_html/tozeret-hasade.co.il/wp-content/plugins/elementor/includes/base/widget-base.php(597): Elementor\Widget_Base->render_content() #5 /home/babstudi/public_html/tozeret-hasade.co.il/wp-cont in /home/babstudi/public_html/tozeret-hasade.co.il/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1658

SYSTEM INFO

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.36
	PHP Version: 7.0.30
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: http://tozeret-hasade.co.il
	Home URL: http://tozeret-hasade.co.il
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.1.2
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 2.10.1.1
		Author: Shea Bunge

	Coming Soon Page & Maintenance Mode by SeedProd
		Version: 5.0.20
		Author: SeedProd

	Easy Smooth Scroll Links
		Version: 2.1.1
		Author: pandasilk

	Elementor
		Version: 2.1.0-beta1
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.0-alpha1
		Author: Elementor.com

	GP Premium
		Version: 1.6.2
		Author: Tom Usborne

	Loco Translate
		Version: 2.1.4
		Author: Tim Whitlock

	SG Optimizer
		Version: 4.0.7
		Author: SiteGround

	WooCommerce
		Version: 3.4.3
		Author: Automattic

	WooCommerce Checkout Manager
		Version: 4.2.3
		Author: Visser Labs

	Woocommerce Products List
		Version: 1.1.15
		Author: Spyros Vlachopoulos

	Woo Floating Cart Lite
		Version: 1.0.9
		Author: XplodedThemes

	Wordfence Security
		Version: 7.1.7
		Author: Wordfence

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
