### ISSUE TITLE
Elementor + Astra bug

### ISSUE THREAD

**Issue by SylviaRodin** [pojome/elementor#4866]
Installed the beta and get blank site. No stress, I can waiting for the release. 

My config, Astra, Elementor Extras, Elementor Pro. 

Thanks for a good job!

**Comment by stevecove** [comment]
Elementor extras is not compatible with the latest beta, see #4861 comments, user who made comment has reported issue to elementor extras dev

**Comment by bainternet** [comment]
Duplicate of #4861

**Comment by SylviaRodin** [comment]
Big thanks for the info. No stress and no panic :-) Wish you all a beautiful day.
