### ISSUE TITLE
Feature request - expand / contract sections ( was toggle row in VC )

### ISSUE THREAD

**Issue by Hanleymade** [pojome/elementor#4867]
In Visual Composer if the layout was long and complicated I could minimize any rows that I wasn't looking at so I could focus on the section or row I was working on.

Imagine the layout sections or rows being tabs that expand or contract ( or max or minimize ). Instead of scrolling down a long layout everytime I want to view different sections of the layout, so I can keep most of the layout contracted and scroll less often.

![image](https://user-images.githubusercontent.com/39174715/41880718-77641d10-7894-11e8-8735-d929a3837b50.png)

![image](https://user-images.githubusercontent.com/39174715/41880804-eca089e2-7894-11e8-9c04-1a79abd8349d.png)

**Comment by PavloGor** [comment]
Feature request add rows like https://www.elegantthemesdemo.com/?et_fb=1 
or https://siteorigin.com/page-builder/documentation/prebuilt-layouts/

**Comment by bainternet** [comment]
@Hanleymade

The Whole Idea of a frontal editor is that you see it as it displays, you can simply scroll.

@PavloGor 
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by Hanleymade** [comment]
@bainternet Not only did you close my feature request but also managed to be dismissive and arrogant in your comments.

Please don't forget who is buying your products as your product grows. Bad customer support is one of the main reasons customers move to different companies.

In addition to having to scroll down the entire length of a monitor sometimes, and then back up again there are other scenarios as well.

What if I want to hide a section because it is a variation that I'm not wanting to see what I will work on another variation? I could minimize section 1A while focussing on section1B and then I don't have to create two templates just to testing section variations.

IF the section variations were long, then it would completely change the overall layout one would be editing / looking at. 

Why make Builders have to create multiple pages just to test out variations???

**Comment by Hanleymade** [comment]
Please REOPEN this thread.

Consider that Elementor 2.1 panel now has collapsible / moveable elements. Why? Because it's quicker to find elements and less visual clutter.

Why have Collapsible Sections / Rows - Same reasons - quicker to move around and less visible clutter!
