### ISSUE TITLE
[Feature Request] Download and Install Elementor PRO From WP-ADMIN

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#4872]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We want an easy way to install Elementor Pro. It would be great to install it directly from wp-admin.

**Describe the solution you'd like**
It would be nice when you push [ Get PRO ] button to prompt you with [ Enter License Key ], if it's valid download and install Elementor Pro.

**Describe alternatives you've considered**
Or you can add the credentials of the My Elementor account and then download and install Elementor Pro.

**Additional context**
Also it could be nice to be able to buy a License Key from Elementor [Get PRO] Page in wp-admin.

**Comment by bainternet** [comment]
@dudaster 

We do have plans for this, but not anytime soon.

thanks.
