### ISSUE TITLE
Blog Archives: Include Categories in Meta Data

### ISSUE THREAD

**Issue by hubmacfan** [pojome/elementor#4878]
When designing an Archive Page, currently, a user can choose between Author, Date, Time, and Comments. I would like the option to display categories as well. Many blog templates include this in their archive posts.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Duplicate of #4440
