### ISSUE TITLE
Does the plugin support Google's AMP?

### ISSUE THREAD

**Issue by shangdev** [pojome/elementor#4879]
Can I support mobile AMP browsing when I enable elementor? If so, how?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future and we do have plans for this.

Thanks for the feedback.

**Comment by robert1112** [comment]
@bainternet Is it supported right now? When will it be implemented? Thank you.

**Comment by alriksson** [comment]
+1 Would be great if Elementor adds a function for AMP. And an AMP mode builder. A native function in the PRO version that works perfectly with Elementor. And users can build and customize the AMP version of the templates/header/footers etc when enabling AMP mode and have AMP enabled in Elementor pro settings.

This would be a great future for a faster world wide web.

**Comment by Josimarcsilva** [comment]
@bainternet 

Compatibility with AMP

The world is mobile. Mobile first then.
It would be amazing to have compatibiliade with AMP to make our projects incredibly fast.

There are already solutions in the market that promise this:
https://ampforwp.com/amp-pagebuilder-compatibility/

But I would like to see this in the core of Elementor

**Comment by jazir5** [comment]
Agreed, desperately need this feature.

**Comment by dylanmhowell** [comment]
After seeing the latest google webmaster conference, they're going to be pushing AMP very hard in the near future. It's time to jump on their ship. Functionality with the official AMP plugin or outputting valid amphtml is necessary for the future.

**Comment by WrongGuy** [comment]
@dylanmhowell Any link to Webmaster Conference?

**Comment by blueforce** [comment]
Yes I need ist too.. Hope that will be done in a future version of elementor...

**Comment by dylanmhowell** [comment]
This was an in person conference and they aren't likely to release video
from the presentations (unfortunately). Since they knew they wouldn't be
publicly released, the presentations were much more open and insightful
than the typical Google company positions.
