### ISSUE TITLE
CSS_File class outputs empty style tags when in CSS_STATUS_INLINE mode

### ISSUE THREAD

**Issue by lf-jeremy** [pojome/elementor#4881]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Using the latest version of Elementor (v2.0.16) and Elementor Pro (v2.0.11), using a template widget to embed a saved section from "My Templates", sections that have no styling will still output an empty `<style id="..."></style>` tag if Elementor is configured in inline css mode.

There are no hooks to change this behavior manually, but editing `includes/css-file/css-file.php` to check `if ( wp_styles()->query( $dep, 'done' ) && $meta['css'] ) {` instead of `if ( wp_styles()->query( $dep, 'done' ) ) {` resolves the problem of unnecessary style tags being output.

## Steps to reproduce

1. In elementor's settings, select `Internal Embedding` for the `CSS Print Method` inside the *Advanced* Tab.
2. Create a section and save it.
3. Create a page, select the `Template` widget, select the section you created, save the page, and view source. If the section that was embedded had no styling, it will output an empty style tag.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>				
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.4.6
	MySQL version: 5.5.49
	PHP Version: 5.5.9-1ubuntu4.21
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: [REDACTED]
	Home URL: [REDACTED]
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive
</details>

**Comment by bainternet** [comment]
@lf-jeremy 

Thanks for reporting, it related to the Dynamics and not the template itself, we will update with a fix soon.
