### ISSUE TITLE
Unique ID on individual Slides for the Slides Widget

### ISSUE THREAD

**Issue by luclessard** [pojome/elementor#4882]
Hi, it would be super nice if there was **the possibility to add a unique ID on each slides** so we could style them individually.

Right now i can use the index but sometime that can change and the styles get transfered to the wrong slide.

Thanks and i love your power tools!

**Comment by luclessard** [comment]
Just found a quick workaround (won't stay if the file is updated, i know :-/ )

Now with that modification, it adds a class to the slide and stays with it even if the slide position is changed.

Inside the slides.php

// line 188 add this code
$repeater->add_control(
			'unique_id',
			[
				'label' => __( 'Slide ID', 'elementor-pro' ),
				'type' => Controls_Manager::TEXT,
				'default' => '',
				'label_block' => true,
			]
		);

// line 1157 change the line to that
$slides[] = '<div class="elementor-repeater-item-' . $slide['_id'] . ' ' . $slide['unique_id'] . '">' . $slide_html . '</div>';

// line 1248 change the line to that
<div class="elementor-repeater-item-{{ slide._id }} slick-slide {{{slide.unique_id}}}">

**Comment by pingram3541** [comment]
This was a good suggestion, too bad it never got a push to core.
