### ISSUE TITLE
javascript in link not possible

### ISSUE THREAD

**Issue by bodhi1970** [pojome/elementor#4884]
I need to implement a "print this page" button on a clients website, but if I try to use "javascript:window.print()" either in an a-link with the HTML widget or directly in the link field in the Icon widget I always get "Server Error (403 error)." when I try to save the page in Elementor.

Is that an error in Elementor?
Can we have an easy option like a widget for that?

**Comment by bainternet** [comment]
@bodhi1970 

I see no reason you can't save that with elementor. Just tested it and its working just fine.

The only thing I can think of is that the server is blocking it for some reason.
but without details its a shot in the dark.

Next time, please follow guidelines for opening a new issue, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by bodhi1970** [comment]
I opened a ticket for Elementor support and we found it was problem of the firewall from Wordfence plugin. I switched it to Learning Mode for a moment then I could save the Elementor page. After switching back to Enabled in Wordfence everything was fine.
