### ISSUE TITLE
Broken pages after import

### ISSUE THREAD

**Issue by igor-manuilov** [pojome/elementor#4886]
Hello guys, 

I import files from another site and noticed that some of my pages are displayed without structure. That is, some pages were imported with splitting into widgets and are perfectly managed by the Elementor, but other pages are displayed as a plain text widget. 

I will attach screenshots, link to the site - http://whitero-tst.pixel-show.com/freelancer/

![screenshot_1](https://user-images.githubusercontent.com/19627558/41983218-19ae494a-7a36-11e8-8ccc-8b30438ede87.jpg)

crashed widget:
![screenshot_2](https://user-images.githubusercontent.com/19627558/41983273-3f57d3dc-7a36-11e8-883f-d015a1abd4bf.jpg)

Most likely this is not due to the incorrect widget, because for example the Portfolio widget displayed on some pages correctly, while on other pages it is broken. 

All the main pages of my site are imported completely broken.

Help please understand why.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
