### ISSUE TITLE
WooCommerce Integration of Product Metall fields

### ISSUE THREAD

**Issue by isolaniso** [pojome/elementor#4887]
would be very powerful to integrate Product Attributes and meta fields in the new WooCommerce feature

**Comment by isolaniso** [comment]
Meta fields of course not Metall fields 😊 typo

**Comment by bainternet** [comment]
Its coming in Elementor Pro v2.1.

Next time, please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
