### ISSUE TITLE
3 Features Request - Woocommerce Custom link field / Modal Element /  Preloader

### ISSUE THREAD

**Issue by jpgif** [pojome/elementor#4888]
Hi, Elementor team you are making an incredible work !!!

Small list of Requests: (i think a small list it's better than separate threads)

1 - Woocommerce add to cart button, would be nice if instead of go to cart / checkout
we could for example "add your link" in a field so if some of us are part of I.E. Amazon Associates program we can put our link there and the checkout would be completed in Amazon (or other affiliate program) automatically.  This would be very good for affilates.

2 - Modal Box or Popup Element : This would be so handy to create our "Subscribe to newsletter" box or modal in a nice Lightbox style.

3 - Fade In / Fade out / Preloader between pages: Not sure how to call this effect but i've seen
some templates in the past that when you jump from one page to another link the content
fades out (or some kind of overlay fades in) the link changes and then a preloader appears and then
the contents fades in (or most likely the overlay fades out and voila you are in the new page.

Hope i explain myself, thank you once again!

**Comment by bainternet** [comment]
@jpgif 

> Small list of Requests: (i think a small list it's better than separate threads)

We don't!

1) It's coming out in Elementor Pro v2.1.
2) Already In our plans.
3) Nice Idea but for now I don't see it happening anytime soon.


Next time, please follow guidelines for opening a new feature request, so we can help you better and only ONE request per issue.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Thanks for the suggestions and feedback.
