### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by aryasharma36** [pojome/elementor#489]
While I was working on my page with Elementor, I tried something out of curiosity, i disabled the elementor plugin and had a look at the pages which I had created using elementor and to my surprise, the design had VANISHED leaving just the text and images in a messed up way.

A question for the makers, don't you think that pages should be there, even if the plugin is deactivated by mistake or deleted, causing a problem to website owners who will try to figure out what is wrong with the website?

**Comment by joshmarom** [comment]
Technically, what you are expecting is virtually impossible.
Pages built with Elementor relay on CSS loaded by the plugin, no plugin = no CSS.
Additionally, the page design settings are saved by the plugin and can only be read and processed by Elementor.
This is the case with any page builder, not just Elementor.

As a matter of fact, Elementor is probably the only Page builder out there, that handles deactivation in such a graceful manner. Deactivation of other page builders will typically result in complete loss of the page content or even worse: will leave you with a pile of ugly shortcodes.

Thank you for using Elementor.

**Comment by aryasharma36** [comment]
@joshmarom Thank You Josh for the detailed explanation. I am not a developer or even a designer, I wanted to make my own website and had tried a few page builder but couldn't invest much time in learning them, tried elementor and fell in love with 2 things, the ease and its free!

I will still continue to use Elementor as I simply love it!
