### ISSUE TITLE
video embeds

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#490]
I want to be able to embed videos in an accordion dropdown, using embed codes like

https://youtu.be/mtcrMxtn9H8

or

`<iframe src="https://archive.org/embed/AHistoryOfNeurologicalSurgeryAtUCSF19122015" width="640" height="480" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>`

How can I make this work?

It looks like this one **does** work. What's the secret?

`<iframe src="https://player.vimeo.com/video/116294517" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

**Comment by WPDevHQ** [comment]
Currently only YouTube and Vimeo are supported via an emebed code like below...
`<iframe width="640" height="360" src="https://www.youtube.com/embed/6u45V2q1s4k?rel=0" frameborder="0" allowfullscreen></iframe>`

**Comment by joshmarom** [comment]
Technically you can use html tags freely in the accordion widget, thus you can embed media using an iframe.

**Comment by mizejewski** [comment]
Ahh...I see, Josh.  This does work in the accordion.
```<iframe src="https://archive.org/embed/AHistoryOfNeurologicalSurgeryAtUCSF19122015" width="640" height="480" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>```

However, the same video does no work when the URL is pasted in the video widget. 
https://archive.org/details/AHistoryOfNeurologicalSurgeryAtUCSF19122015?

**Comment by arielk** [comment]
Added oEmbed functionality for Accordion/Tabs/Toggle widgets : https://github.com/pojome/elementor/pull/524/commits/6eee94245fa37ddd275b9bd601834d62d935c014 https://github.com/pojome/elementor/commit/1f0ad0f1996df18c4bbe653713ce90febb7c0512
