### ISSUE TITLE
Default expand submenu in nav-menu

### ISSUE THREAD

**Issue by lukaszlatacz** [pojome/elementor#4900]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

**What problem is your feature request going to solve? Please describe.**

Hi,
in vertical menu with submenu,  I would like the submenu to be expand by default

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
