### ISSUE TITLE
How to interact with Repeater control UI using JavaScript

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#4902]
I need to interact with a Repeater control UI from one of my custom Elementor widget using JavaScript.

I created a custom widget with 2 fields: a repeater one and a custom one which add a button to grab  data from Ajax and add it to the repeater field.

I planned to use jQuery to trigger click on delete buttons to first empty the repeater field and then to click on the "+ add an item" button to add a new item.

The click on the add button works but the click on the delete buttons doesn't.

`jQuery('.elementor-repeater-row-tool.elementor-repeater-tool-remove').click()`

`jQuery('.elementor-repeater-row-tool.elementor-repeater-tool-remove').each(function(){jQuery(this).click();});`

For some unknown reasons, the click event only works on the first item even though the jQuery selector returns all items.

**Comment by bainternet** [comment]
@tristanleboss 

Why use the ui via JavaScript and not modify the data model directly?

Can you explain the use case? provide code?

**Comment by tristanleboss** [comment]
@bainternet The use case: I have a widget with a repeater field. The data used to populate this repeater come from an external API.

First, these data can disapear or be updated on the API but I don't want them to be updated on my site: I want them like they were when the widget was put on the page. My editor may also need to update some data pulled from the API. => Hence the fact I need to store them locally

Second, I need to allow my editors to pull items from the API automaticaly because this API can return 10's of results: I don't want my editors to copy/paste each field one by one :D

Today, I have this UI:

![image](https://user-images.githubusercontent.com/1431508/42367149-805bdfe4-8103-11e8-91f0-614e488195c9.png)

The JS code is simple:

`
// We add an element to the repeater by simulating a click on the add button
jQuery('.elementor-button.elementor-button-default.elementor-repeater-add', jQuery_scope_control_repeater).click();
// We grab the latest item of the Repeater field (the one we just triggered the creation of
var jQuery_scope_repeater_row = jQuery('.elementor-repeater-fields-wrapper .elementor-repeater-fields:last-child', jQuery_scope_control_repeater);
// We set the value of the input field
jQuery('.elementor-control.elementor-control-MY_FIELD_IDelementor-control-type-text input[data-setting="MY_FIELD_ID"]',  jQuery_scope_repeater_row).val(MY_FIELD_VALUE);
// We trigger the input event to ask Elementor to update the widget preview
jQuery('.elementor-control.elementor-control-MY_FIELD_IDelementor-control-type-text input[data-setting="MY_FIELD_ID"]', jQuery_scope_repeater_row).trigger('input');
`
It would be awesome if Elementor can add an API for manipulating Repeater fields! My wmethod works but rely on you not updating the field classes.

**Comment by bainternet** [comment]
@tristanleboss 

I see and still feel that working with the data modal directly is the correct way of doing that. As for an API, it exists if you talk directly with the data modal but currently we have no docs for that.

Also maybe using dynamic tags can help in this case but the Best approach here is a custom widget that will save and loop over the API response data. which for that we do have an API doc:

https://developers.elementor.com/creating-a-new-widget/

thanks.

**Comment by tristanleboss** [comment]
The lack of documentation is clearly the weakpoint of Elementor. Features suggestions accumulates on this issue tracker (when they are not closed) but are impossible to implement easily and properly because the documentation is lacking. Why not taking the time to write this doc so people can really leverage the full potential of Elementor?

Closing this issue is a way to hide the problem because, for me, due to the lack of documentation, this is  not a solved issue: I mean, it may be possible for you to do it because you know how the data modal works but not for me.

**Comment by ccdw** [comment]
Agree with the above comment. A few pages of client side API docs would help immensely!

But nobody listens.

**Comment by saurab1996** [comment]
Update repeator fields option by js

<code>
(function () {
    /**
     * shallowEqual - Compares two objects for shallow equality.
     * @param {Object} obj1 - The first object to compare.
     * @param {Object} obj2 - The second object to compare.
     * @returns {Boolean} - Returns true if both objects have identical key-value pairs, otherwise false.
     */
    const shallowEqual = (obj1, obj2) => {
        // If either is not an object or is null, return false
        if (typeof obj1 !== 'object' || typeof obj2 !== 'object' || obj1 === null || obj2 === null) {
            return false;
        }

        // Get keys of both objects
        const keys1 = Object.keys(obj1);
        const keys2 = Object.keys(obj2);

        // If objects don't have the same number of keys, return false
        if (keys1.length !== keys2.length) {
            return false;
        }

        // Compare values for each key in both objects
        for (let key of keys1) {
            if (obj1[key] !== obj2[key]) {
                return false;
            }
        }

        return true; // If no mismatch is found, return true
    };

    const treeViewEditor = {
        panel: '', // Holds the reference to the editor panel
        model: '', // Holds the model of the widget's settings
        editor: '', // Holds the reference to the current editor view
        levelNodesName: {}, // Stores node names for each level, used for shallow comparison

        /**
         * onSettingChange - Updates the options in child repeaters when settings change.
         */
        onSettingChange: () => {
            const settings = treeViewEditor.model.get('settings'); // Retrieve widget settings
            const nodeCount = parseInt(settings.get('node_count')) || 0; // Get the number of nodes

            // Loop through each node level
            for (let i = 1; i <= nodeCount; i++) {
                const repeaterId = `node_data_level_${i}_items`; // Construct repeater ID for the current level
                const nodeRepeater = treeViewEditor.getEditorControlView(repeaterId); // Get the repeater view
                const nodeRepeaterSettings = settings.get(repeaterId); // Get the current settings for the repeater

                // If the repeater exists and has data
                if (nodeRepeater && nodeRepeaterSettings?.length) {
                    const currentLevelNodeNames = {}; // Object to store node names for current level

                    // Populate currentLevelNodeNames with the 'name' property from each repeater item
                    nodeRepeaterSettings.each((repeaterModel, key) => {
                        currentLevelNodeNames[key + 1] = repeaterModel.get('name');
                    });

                    // If the node names have changed, update levelNodesName and child options
                    if (!shallowEqual(treeViewEditor.levelNodesName[repeaterId], currentLevelNodeNames)) {
                        treeViewEditor.levelNodesName[repeaterId] = currentLevelNodeNames; // Update stored node names

                        const nextIndex = i + 1; // Move to the next level
                        const nextRepeaterId = `node_data_level_${nextIndex}_items`; // Construct next repeater ID
                        const nextNodeRepeater = treeViewEditor.getEditorControlView(nextRepeaterId); // Get next repeater view

                        // If there's a next repeater, update its parent node options
                        if (nextNodeRepeater) {
                            const nextNodeRepeaterFields = nextNodeRepeater.get('fields'); // Get the fields for the next level

                            // If the next level has a 'parent_node' field, update its options
                            if (nextNodeRepeaterFields?.parent_node) {
                                nextNodeRepeaterFields.parent_node.options = currentLevelNodeNames; // Set the parent options to current node names
                                nextNodeRepeater.set('fields', nextNodeRepeaterFields); // Update the fields in the repeater
                            }
                        }
                    }
                }
            }
        },

        /**
         * init - Initializes the tree view editor, setting up event listeners and initial settings.
         * @param {Object} panel - The current panel view of the widget editor.
         * @param {Object} model - The settings model of the widget.
         */
        init: (panel, model) => {
            treeViewEditor.panel = panel; // Store the reference to the editor panel
            treeViewEditor.model = model; // Store the model containing widget settings
            treeViewEditor.editor = panel.getCurrentPageView(); // Get the current page view in the editor

            // Bind 'before:remote:render' event to trigger option updates before the view is rendered
            treeViewEditor.model.on('before:remote:render', treeViewEditor.onSettingChange);

            // Call onSettingChange to initialize with current settings
            treeViewEditor.onSettingChange();
        },

        /**
         * getEditorControlView - Retrieves the control view for a specific repeater by its name.
         * @param {String} id - The name of the control view (repeater) to retrieve.
         * @returns {Object} - Returns the control view if found, otherwise undefined.
         */
        getEditorControlView: (id) => {
            // Search for the control view by its name within the current editor's panel
            return treeViewEditor.editor.collection.findWhere({ name: id });
        }
    };

    // Hook into Elementor's panel open event for the 'tree-view-graph' widget, initializing treeViewEditor
    elementor.hooks.addAction('panel/open_editor/widget/tree-view-graph', treeViewEditor.init);

})();

</code>
