### ISSUE TITLE
Re - WooCommerce Builder - Option to include SKU

### ISSUE THREAD

**Issue by vandanga** [pojome/elementor#4904]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Missing Feature
**Lack of Ability to include SKU field and rename its Title in the Post, Archive and the Cart pages.
SKU or Part No. is often used for industrial/electronic components.**

Request
**Not sure what the features will be include in WooCommerce Builder but I would like to see an Element or Widget that would allow SKU to be inserted, formatted and Titled**

**Previously I have needed to create a Child Theme just for this and then update templates as WooCommerce was updated which makes it maintenance heavy.**

**Comment by bainternet** [comment]
It's there already.
 
Thanks.
