### ISSUE TITLE
ACF - Dynamic video url not working in post template.

### ISSUE THREAD

**Issue by Webtica** [pojome/elementor#4906]
## Prerequisites
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description
I made a custom field in ACF latest version with setting field type text.
In my post i link a youtube video url full with https:// etc then i go to the post template builder and i add the video widget to then dynamic get the ACF video field in the post. The placehlder flashes for 3-4 times but then no video displays.  I tried both with Latest elementor & Pro version. ALso with the beta version 2.1.0 beta 2

## Steps to reproduce
All of the above.

## Isolating the problem
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@Webtica 

We can't replicate the issue,
Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by gangesh** [comment]
Having similar issue, only different is player shows "video unavailable". Something to do dynamically loading URL?

**Comment by gangesh** [comment]
For someone facing similar issue. It was bcoz of I was working temporary url and without SSL certificate. All good now.
