### ISSUE TITLE
Load more

### ISSUE THREAD

**Issue by networking-web** [pojome/elementor#4907]
Peace,
I need to show last posts.(Vigdet Recent posts)
But I do not want all posts to be seen at once (there are many posts).
I want to have the option of clicking "Load More".
(There is an option to select "Pagination" but it does not work on a specific page).
I would be very happy to take the request quickly because I have been waiting for it for a month.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by networking-web** [comment]
on Widget Recent posts.
You can choose how many posts are displayed on the page and if there
are additional posts you need to browse to the following pages.
I asked that instead of going to the next page will appear a button
"Upload More" (as I added a picture).
Then more posts will be discovered and so on.
I do not want one page to appear immediately 200 posts long loading time.
But will be able to determine how many posts will be visible as they
exist on this page. <https://netw.co.il/%D7%91%D7%9C%D7%95%D7%92/>
It's an Atlanta format.
Archived are shown in 10 posts and each time there is another load.
Thank you

if i can write on hebro i can explain mor.


[image: https://netw.co.il/] <https://netw.co.il/>

2018-07-01 15:11 GMT+03:00 Raz Ohad <notifications@github.com>:
