### ISSUE TITLE
Editing accordions

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#491]
The ability to nest elements inside accordions and tabs would be very useful. For example: images, columns, video, html, maps, etc. 

This only meets some of those needs, but note that when editing tabs in Beaver Builder plugin, both visual and text tabs (allowing for html) are available and the add media button. Basically standard WP editing.
<img width="595" alt="accordion-edit" src="https://cloud.githubusercontent.com/assets/974442/18176025/ba386df6-7028-11e6-9a49-2924dce8e009.png">

**Comment by arielk** [comment]
Dup #176
