### ISSUE TITLE
Add Exit to Page

### ISSUE THREAD

**Issue by seanvandermolen** [pojome/elementor#4914]
When you're done editing a page your only option is to exit to the dashboard.  It would be more convenient to exit back to the pageview for many peoples workflow. 

Divi works like this as well.  It's not like there is much you can do in the dashboard with Elementor anyways.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
