### ISSUE TITLE
ACF not SHOW in DYNAMIC FIELD

### ISSUE THREAD

**Issue by sododesign** [pojome/elementor#4917]
When ACF fields are included via PHP (therefore not created by UI interface) they are not shown in the selection DYNAMIC field.

This example applies when, for example, we export fields from a DEV installation to import them into a LIVE installation. Many times you prefer to import fields using PHP to reduce calls to the server.

Please check this problem.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Anyway we cant replicate, just tested with ACF Version 5.6.10 fields defined via PHP working fine.

thanks.
