### ISSUE TITLE
Enable Sticky header styling with custom CSS

### ISSUE THREAD

**Issue by JoeDarko** [pojome/elementor#4918]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

At this moment Elementor doesn't have an option to style header while it's sticky(when scrolling). Many people already proposed this and person from your team was always saying to them that you are considering this feature and that for now the sticky header can be styled with custom CSS.

So i looked into this and i encountered a problem.

When you set your header as sticky and you start to scroll, Elementor applies this selector to the sticky header: ".elementor-sticky--active"

This is great and this is what i tried to use to style the header while its sticky on scroll.

The problem is, the selector ".elementor-sticky--active" appears when you start to scroll but doesen't disappear when you scroll all the way back to the top. 

This means that the custom CSS is applied when you start to scroll but stays applied even when you scroll back to the top and will stay applied until you reload the page. Therefore can't be used to style header while it's sticky on scroll.

**Describe the solution you'd like**

This is the goal (every other website has this):

1. Normal header
2. Start scrolling -> Custom CSS is applied to the header
3. Scroll back to the top -> Normal header

Current situation (while using ".elementor-sticky--active" selector):

1. Normal header
2. Start scrolling -> Custom CSS is applied to the header (Good)
3. Scroll back to the top -> Custom CSS is still applied until site is refreshed (This ruins everything :-/)

There should be some selector that appears when you start to scroll and disappears when you scroll back to the top. This would allow us to style the sticky header with custom CSS. At this point the selector appears on scroll but stays there until you refresh so it can't be used because the header will not switch back to normal when you scroll back to the top.

So am i missing something or the sticky header can't be styled with custom CSS at this moment?

Thank you for your answer. :)

**Comment by JoeDarko** [comment]
Great. Looking forward to it. :)

**Comment by neoset** [comment]
Also it would be nice if we had the option that the sticky menu by scrolling down would hide and scroll up will show, especially for the mobile theme and desktop.
