### ISSUE TITLE
Theme Problem FYI

### ISSUE THREAD

**Issue by iCoachLive** [pojome/elementor#492]
I'm using a theme called "Elegant Tube Press." http://BestOnlineTools.net
When I added Elementor, the hamburger menu on mobile disappeared.

The theme developer wrote back the following:
---------------------------------------------------------------------------------------
So here is the problem, The Elementor adding same JS library to the website ( looks like the Elementor developer didn't registering the script properly ). This double source of JS breaks the queue of script, so it's throwing JS error which make the theme script don't work.

My solution is to put my script queue at very last. open up functions/cssjs.php line 16. You'll find this code below :
`add_action('wp_enqueue_scripts' ,array(&$this,'_action_vasq_register_script'));`

Simply change that code to this
`add_action('wp_enqueue_scripts' ,array(&$this,'_action_vasq_register_script'),9999);`

Thanks
-------------------------------------------------------------------------------------------
Not sure if this is a real issue -Just forwarding for your info-

**Comment by WPDevHQ** [comment]
I can confirm that this is an issue as I'm having problems implementing the template support for the Sydney theme - switching priority resolves the issue.

It looks like some the Elementor JS are not being loaded in a non conflicting mode.

A temporary solution would be for Elementor to switch its priority to 1 @ line 21 of frontend.php like so..
`add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_scripts' ], 1 );` - but the frontend.min.js will need to be looked at in order to permanently resolve the conflict.

**Comment by KingYes** [comment]
@iCoachLive Did you try the @WPDevHQ temporary solution if it's fix your issue?

**Comment by iCoachLive** [comment]
Yes I am using  @WPDevHQ and with the solution the developer provided: My solution is to put my script queue at very last. open up functions/cssjs.php line 16. You'll find this code below :
add_action('wp_enqueue_scripts' ,array(&$this,'_action_vasq_register_script'));

Simply change that code to this
add_action('wp_enqueue_scripts' ,array(&$this,'_action_vasq_register_script'),9999);

It works-However the new issue is when I try to save a section to the library, it crashes me out of wordpress entirely. Haven't had that happen yet on any other theme. And, I have tested quite a few.
If you need access to the site let me know-

**Comment by iCoachLive** [comment]
https://app.hyfy.io/v/abEDCEJabh/
Here's a screen recording of the issue.

**Comment by arielk** [comment]
It looks like the code of the theme made it, please contact their support with this issue.
