### ISSUE TITLE
placeholder in forms not showing

### ISSUE THREAD

**Issue by AndersJpg** [pojome/elementor#4920]
placeholder in forms not showing on different browsers(ex chrome)  on(tablet - asus & phone - Samsung)
it is working perfectly on chrome browser on desktop
https://i.imgur.com/kZ81Ak6.png

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue/feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by sirucato** [comment]
I have the same problem. I open ticket here with all the details requested.
https://github.com/elementor/elementor/issues/10527
