### ISSUE TITLE
Last posts view source

### ISSUE THREAD

**Issue by networking-web** [pojome/elementor#4921]
Peace,
my site has some custom post type.
When viewing last posts, I want the posts from **some** custom post type to be displayed.
Today there is no option to display from multiple sources - just one source.

Or option to select a parent category -That the posts belonging to the category are in the custom post type
![2](https://user-images.githubusercontent.com/39119112/42166567-1b4f839a-7e14-11e8-95a5-5cbde0fba42c.JPG)
![default](https://user-images.githubusercontent.com/39119112/42166568-1b8e66a0-7e14-11e8-9df5-ed4a3b19c201.JPG)
tank you

**Comment by bainternet** [comment]
@networking-web

Thanks for the suggestion, In Elementor Pro V2.1 which is now in alpha and should go into the beta phase in a day or two, you can use an action hook to modify the query and define multiple/custom post types ex:

```PHP
add_action( 'elementor_pro/posts/query/query_id', function ( $wp_query, $posts_widget ) {
	$wp_query->set( 'post_type', [ 'post', 'cpt', 'cpt2' ] );
}, 10 ,2 );
```

I merged this issue with  #1748, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by networking-web** [comment]
I added the code to a sub-template -function .

And ... nothing.
Why?



[image: https://netw.co.il/] <https://netw.co.il/>

2018-07-02 17:00 GMT+03:00 Raz Ohad <notifications@github.com>:

**Comment by networking-web** [comment]
![ele](https://user-images.githubusercontent.com/39119112/42316182-d6b8bd60-8051-11e8-98c8-97039e8b495d.JPG)
As you can see in the picture nothing was added.
Please if you can guide me why?
