### ISSUE TITLE
Allow Button Widget to change its HTML tag?

### ISSUE THREAD

**Issue by hzesen1221** [pojome/elementor#4927]
Hi, I am wondering if it is possible to change Button Widget's HTML tag, just like you could change the HTML tag for a Heading Widget.

For consistency with pages not using Elementor, we generally prefer disabling the default fonts and default fonts color features in Elementor and let our theme (Astra) handle the default typography. However, I noticed that changing the font family for Buttons in Customizer does not update the default font family of my Elementor Button Widgets. After some inspections I noticed that the Button Widget is actually formulated by <a> instead of <button> tag in Elementor, while most of the WP themes that handle buttons typically target <button> tag instead. The implementation of Button Widget in Elementor totally makes button styling in Customizer useless.

Is it possible to add such a feature? Thanks.

**Comment by arielk** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
