### ISSUE TITLE
Moving a New Section

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#493]
With Add a New Section anchored at the bottom, it can be difficult to create one and drag it up to the top of the page (upon realizing a new section is needed up there.) Some ideas:
1. Make it easier the create and move up even when there is scrolling involved
2. Put Add New Section and Add Template buttons above Elements in the left palette, so they can be dragged where needed?

**Comment by mizejewski** [comment]
Just some addition info: As I've been building more pages, I wanted to note that even dragging an existing section can be difficult if there is a need to scroll to get to the new location.

**Comment by arielk** [comment]
@mizejewski What do you think about this idea for a new section? #576

**Comment by mizejewski** [comment]
Looking to BB for inspiration is a good idea, but in my opinion, it has some really confusing and clunky aspects like the overlaid panel positioning, and the fact that templates are separate from "saved rows" and "saved modules." I would like to see you keep the more intuitive approach of Elementor but perhaps change the way section/template is added in a way similar to the mockup here: 

![ui-suugestion](https://cloud.githubusercontent.com/assets/974442/18645582/9c8559a2-7e62-11e6-92c8-adcf2ba66a32.png)

The new section or template option is dragged into place from there. Once on the layout, the user can still click the plus sign to add a template or drag a widget into place. Thanks!

**Comment by arielk** [comment]
Elementor 1.5 RC2 has already been released with this enhancement, please check this issue #1827

Thanks for the feedback!

**Comment by mizejewski** [comment]
These changes are monumental! Thank you :)

**Comment by jorgebarrero** [comment]
There are a few ergonomic issues here to be considered. The first is consistency. Elementor has a toolbox. I should have a proper standard tool for inserting sections, not a weird purple button right on top of the design that uglifies de design on the visual panel. The next thing is that sections and columns should be side by side in a section of its own. Titles and text boxes on the next row. Templates on the very bottom. It is a matter of how many clicks are needed and how visual space is used. Wasting the visual for a task is unfrequented used is not a good ergonomic practice. 
![image](https://user-images.githubusercontent.com/3620375/28490141-5f497d28-6ea0-11e7-9eef-bae2c49582d5.png)
