### ISSUE TITLE
Feature Request: Add query vars to dynamic content

### ISSUE THREAD

**Issue by EdenK** [pojome/elementor#4934]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Add some query vars in dynamic content**
It would be helpful if we can choose from dynamic content query vars as well `get_query_var()` because we have some pages that create a virtual pages of the same page just with different content depend on the query var and it could be helpful to change the heading or some content base on this query var.

For example /page-slug/query-var/value
So we could use the **value** like it some custom field in the dynamic content.

**Comment by bentalgad** [comment]
+1
