### ISSUE TITLE
Updated to Elementor v 2.1.0

### ISSUE THREAD

**Issue by DoddeYO** [pojome/elementor#4935]
Hello!

I just updated to Elemèntor v 2.1.0 and now I get two warning messages. 

The first one is: "Warning: array_filter() expect at most 2 parameters, 3 given in /home2/dodde/public_html/wp-content/plugins/elementor1/includes/base/element-base.php on line 756"

The second one is: "Warning: Invalid argument supplied for foreach() in /home2/dodde/public_html/wp-content/plugins/elementor1/includes/base/element-base.php on line 758"

How do I fix this issue?

**Comment by arielk** [comment]
Hi @DoddeYO 

This error came from old versions of PHP, please update to the latest version (v2.1.1) to fix this issue.
