### ISSUE TITLE
update to elementor 2.1 problem

### ISSUE THREAD

**Issue by backtoback1** [pojome/elementor#4936]
Hi i update the elementor free plugin to the new version 2.1 
but after activate it my website is down and can't access my 
wordpress panel . 
i delete the elementor from cpanel and the website back on 
the previous version (2.016) working fine but the new one is not 
wordpress version : 4.9.6
PHP version:  7.0

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by backtoback1** [comment]
@arielk the problem because the elementor extra add-ons latest version

**Comment by backtoback1** [comment]
update: now all us fine i tried the new version Elementor Extras v1.9.10
and there is no problem at all .
