### ISSUE TITLE
Header and Top Bar Messed Up

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#4939]
Since the latest update, my website header and top bar are messed up. An additional navigation section is showing up vertically now (see the screenshot.) The top bar items are no longer centered in the page but are riding the margins. The below is the Live page;

![elementor-header](https://user-images.githubusercontent.com/35422914/42224280-b05ca074-7ea7-11e8-9a8e-751de547dd02.jpg)

This screenshot shows what it looks like in the editor;

![elementor-header-editor](https://user-images.githubusercontent.com/35422914/42224650-9c057906-7ea8-11e8-80c2-75765b85665c.jpg)

I had to roll back to the previous version because my whole site was messed up. So sad that this is happening...

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
