### ISSUE TITLE
elementor library in posts

### ISSUE THREAD

**Issue by isanlab** [pojome/elementor#4942]
Hi

A suggestion. 

Add in the text editor of the posts a drop-down list with the elements of the library. When you select one, it adds the corresponding shortcode to the text. 
In this way can create, for example, subscription boxes, cta's, etc. and easily add to the posts

Regards

**Comment by bainternet** [comment]
@isanlab 

Why not use the Template widget which is the preferred method to insert dynamic templates.


thanks

**Comment by isanlab** [comment]
I don't think you understand me.
