### ISSUE TITLE
Significant UI bug with 2.1

### ISSUE THREAD

**Issue by wmassjct** [pojome/elementor#4943]
There is a huge problem with the new release. When I use control-click to open the popup (I'm on a macbook with no right click) it starts dragging the element around with the cursor. Also when I click directly on an element it does the same thing. Esc key does not drop it and sometimes I can't even drop it into a section without it getting picked up again. This makes elementor unusable on a laptop. Please fix it.

**Comment by bainternet** [comment]
@wmassjct 

Most of us here have MacBooks and we all manage just fine, if Crtl + Click is not working for you there are other ways to right-click in a MacBook. 

- **Click with two fingers** : You can simply use your two fingers to click the trackpad.
- **Assign the bottom-left/right corner** : You can assign the bottom-left/right corner as a right-click zone in System Preferences.

thanks for the feedback.

**Comment by katart** [comment]
@bainternet I'm noticing the same issue with Ctrl+Click on an iMac. 

Most designers/developers have their computer tuned for performance and efficiency, so I don't think suggesting we change those settings for your plugin is the best answer.
