### ISSUE TITLE
Feature Request: Configure conditions based on language in Polylang or Body class

### ISSUE THREAD

**Issue by Webtica** [pojome/elementor#4944]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be good to display different headers or footers based on the language or body class on a page.

**Comment by bainternet** [comment]
Duplicate of #4839
