### ISSUE TITLE
Version 2.1.0 & 2.1.0 Control_Base is deprecated Warning 

### ISSUE THREAD

**Issue by AppGrind** [pojome/elementor#4945]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
After Updating to version 2.1.0 the below warning appeared at the top of the site, along with other PHP errors/warning that I believe were fixed in 2.1.1
Server is running PHP 5.5.9-1ubuntu4.25. I'd upgrade to PHP 7.0+ as I there error is does not appear on that version (I've tested) but it's beyond my powers.

Both sites on PHP 5.5.9 and 7.0+ are running the same theme, same child-theme and same WP version.

##WARNING MESSAGE
Notice: Elementor\Control_Base is deprecated since version 1.6.0! Use Elementor\Base_Data_Control instead. in /var/www/html/site_folder/wp-includes/functions.php on line 3968

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

Operating System: | Linux |  
-- | -- | --
Software: | Apache/2.4.7 (Ubuntu) |  
MySQL version: | 5.5.60 |  
PHP Version: | 5.5.9-1ubuntu4.25 |  
PHP Max Input Vars: | 3000 |  
PHP Max Post Size: | 10M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@AppGrind 

please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists then please reopen.

thanks.

**Comment by AppGrind** [comment]
Thanks.

I was able to narrow it down to Livemesh Addons for Elementor version 2.0.2
Because I need some of it's widgets, I will turn off debugging from wp-config instead.

Thanks again, your prompt response was very much appreciated
