### ISSUE TITLE
Elementor 2.1.1 + XML Demo Import Bug

### ISSUE THREAD

**Issue by DeoThemes** [pojome/elementor#4947]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
After recent update from version 2.0.16 to 2.1.1 the XML demo content import is broken. It was working well with 2.0.16

## Steps to reproduce
1. Tools > Export
2. Import to another domain address using One Click Demo Import plugin.
3. Layout is broken

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Unix)
	MySQL version: 5.7.21
	PHP Version: 7.0.19
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1047527424
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: http://demo.deothemes.com/test
	Home URL: http://demo.deothemes.com/test
	WP Multisite: No
	Max Upload Size: 999 MB
	Memory limit: 40M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Margin
	Version: 1.0.0
	Author: DeoThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Advanced WordPress Reset
		Version: 1.0.1
		Author: Younes JFR.

	Deo Elementor Extension
		Version: 1.0.1
		Author: DeoThemes

	Elementor
		Version: 2.1.1
		Author: Elementor.com

	One Click Demo Import
		Version: 2.5.0
		Author: ProteusThemes


== Debug ==
	Errors: There are no errors to display
				
```
</details>

**Comment by bainternet** [comment]
@DeoThemes 

can you upload the xml?

**Comment by DeoThemes** [comment]
Native WP importer seems to be working fine. So it's the conflict of recent version of Elementor and One Click Demo Import.

Here is the XML:
https://www.dropbox.com/s/oxz435plv83fqxp/demo-content.xml?dl=0

**Comment by tomusborne** [comment]
I'm also noticing this with our Site Library in GP. When an Elementor site is imported, it's importing the Elementor content without any of the section containers/HTML.

**Comment by nishant-t** [comment]
Facing the exact same issue when importing with One Click Demo Import for the latest version. Tested with 2.0.16 and it works absolutely fine. Normal WordPress Import works fine.

**Comment by tomusborne** [comment]
So what's happening is `_elementor_data` is coming out of the importer as `NULL`.

In version 2.0.16, this data is being added to the database with tons of backslashes. In 2.1, those backslashes are gone. That's the only difference I'm seeing when debugging the data.

**Comment by tomusborne** [comment]
It did have to do with slashing.

If the metadata is ran through `wp_slash()`, it works in 2.1. However, this makes it fail in 2.0.16.

@bainternet Any idea what changed here? I'm happy to `wp_slash()` it, but want to make sure it's a permanent fix and not something I'll have to undo at some point?

**Comment by bainternet** [comment]
@tomusborne 

We are looking at it.

**Comment by tomusborne** [comment]
That commit fixes the issue. Thanks for looking into this!

**Comment by pulla** [comment]
I still have the problem. I use the newest elementor and used WordPress import. 
But still having a problem. It comes with text not elementor data.

**Comment by stylethemes** [comment]
I'm facing the same problem here when importing the XML data using the one-click demo import plugin the content do get imported but  global elementor settings don't example (custom breakpoints, global colors and global fonts)

is there is fix to this

**Comment by Gnodesign** [comment]
Did anybody find a fix on this? The content gets imported but the global settings do not get imported. I would appreciate if somebody could provide a solution to this. :)

**Comment by riyasrahman** [comment]
Dear all i am using one click demo import plugin. I created website with elementor pro. When i am importing the demo its emporting everything except elementor site settings and templates. How can i import xml file with elemenotor templates and site setting
