### ISSUE TITLE
Elementor 2.1.1 + Elementor Pro 2.0.13 fails

### ISSUE THREAD

**Issue by Bernietorras** [pojome/elementor#4949]
When you install Elementor 2.1.1 + Elementor Pro 2.0.13, the Elementor editor gives an error: Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Memory configuration: 110 of 1024 MB (11%) | WP LIMIT: 1 GB

I have disabled addons, cache, all other plugins disabled, without results.

The only result, deactivating the Elementor Pro version, then I can edit the web page using the Elementor editor.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.
