### ISSUE TITLE
Turn on lightbox locally for media carousel

### ISSUE THREAD

**Issue by Alecto** [pojome/elementor#4951]
**What problem is your feature request going to solve? Please describe.**
There is a possibility of global disabling of the elementor lightbox.
Then we can turn it on locally for images and for the galleries.
But, there is no such possibility in the media-carousel.

This is a flaw and bug of the existing functionality of the elementor plugin.

Make it possible to turn the lightbox for the media carousel locally .

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by Alecto** [comment]
the answer of a typical formalist and paper-man.
the problem is described, this is enough.

**Comment by bainternet** [comment]
@Alecto 

Sorry, you feel that way, but we like to work in an organized manner.

thanks.

**Comment by Alecto** [comment]
if you like to work in an organized way and in a team - study the scrum manifesto.
person, the client should always stand above any of your rules.
otherwise you are not working for people, you are ineffective.

**Comment by bainternet** [comment]
Thanks for your opinions.
