### ISSUE TITLE
Allow for vertical scroll in the carousel

### ISSUE THREAD

**Issue by aliasbody** [pojome/elementor#4953]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The actual image carousel has a lot of options but none of them enables a vertical scroll (where the images go from bottom to top or vice-versa. Which is something that we need in our website.

**Describe the solution you'd like**
A simple option to not only allow horizontal normal or inverted scroll but vertical as well.

**Describe alternatives you've considered**
The only alternative we've considered is to develop our own widget but it would be a pure copy of this one just to add a functionality.

**Additional context**
N/A

**Comment by arielk** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
