### ISSUE TITLE
Allow to preview name of saved/global widget in Elementor editor while on the page to know which ones to search for and duplicate

### ISSUE THREAD

**Issue by jmedia123** [pojome/elementor#4954]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A clear and easy way to know which global widgets are currently on your site so you can duplicate them throughout your site by just scrolling over the widget and seeing the name you placed on them. This would be extremely helpful without guessing what the name was of that saved/global widget is. 

**Describe the solution you'd like**
Scroll over with your mouse over a global widget and the name you saved that global or saved widget is shown.  

**Describe alternatives you've considered**
There really isn't an alternative to this feature. 

**Additional context**
![cta form](https://user-images.githubusercontent.com/40833413/42293453-5524b244-7fa8-11e8-80a2-dafc940ae0ef.png)

**Comment by bainternet** [comment]
I merged this issue with  #1165, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
