### ISSUE TITLE
[Feature Request] Shortcodes for templates

### ISSUE THREAD

**Issue by LearnWPBasics** [pojome/elementor#496]
Shortcodes for templates will be a very welcome addition to the Elementor arsenal. With them, one will be able to place Elementor created layouts/sections/library items easily into any area within WordPress where shortcodes are accepted. 

One of the first areas to come to mind is to replace one's theme's footer widgets and footer with sections created with Elementor which will provide for a much richer user experience.

Cheers!
Lyle

**Comment by WPDevHQ** [comment]
Wouldn't wrapping the desired Elementor content in a function callback and then hooking that in to the desired theme location with `add_action()` be a better solution? 

The only downside to this approach will be to rely on themers to properly provide hookable locations in their themes - which they should be doing and not relying on Elementor to be the do all things kind of a plugin!

**Comment by LearnWPBasics** [comment]
@WPDevHQ - possibly for a developer, but I cannot see this as being "easy to use" for a designer/site owner - could you imagine trying to explain how to do so to this type of user? :) Not sure if you are aware of how "the other" page builder does this, but it's as easy as - and as equally easy to explain to the user - adding this to wherever it is needed: [name_of_bulder_insert_layout slug="name-of-template"] Easy-peasy :) No risk of the dreaded white screen of death :)

**Comment by m9n** [comment]
I can forsee some issues with this - particularly around responsiveness.  For example, you can't easily know (without some kludgey javascript) how wide the container is that the user is adding the shortcode to.

And I think this has the potential to repeat functionality provided by WordPress core.  Theme designers have already defined spaces for Widgets and footers, assuming that each of those areas is going to contain a standard single-column widget.  These widget areas have already been designed to work well with the layout of the overall theme - including some that do unusual/interesting things with layout, like TwentyFifteen putting the sidebar into the hidden mobile menu.

I guess you could add some CSS such that any Elementor layout in a widget should break down to its single-column version.  But this feels messy, as the user creating the layout in Elementor may be expecting to get columns that actually they don't.

Honestly, I feel a better solution would be just to provide some kind of "Elementor Widget" wrapper.  You'd choose "Elementor Widget" from the list of widgets under Appearance, and then you'd choose what type of element you want that widget to contain before adding your content.  You might want to disable changing the type of Widget once content is added to it, as it would be impossible to remap most content if the element type was changed.

The advantage of this is that it removes any layout problems you might have, and works gracefully with core WordPress behaviour.  If site owners wish to place one of your Elements inside other content, there are already plugins to do this - eg [Widget Shortcode](https://wordpress.org/plugins/widget-shortcode/).

**Comment by nicolas92** [comment]
Any news on this?

**Comment by arielk** [comment]
The feature is now available in Elementor Pro, check it out: https://elementor.com/pro/
