### ISSUE TITLE
Javascript issue

### ISSUE THREAD

**Issue by Veri21** [pojome/elementor#4965]
I have a question, I created a widget here a little snippet.

$slides_to_show = range( 1, 3 );

$this->add_responsive_control(
‘slides_to_show’,
[
‘label’ => __( ‘Slides to Show’, ‘elementor’ ),
‘type’ => Controls_Manager::SELECT,
‘options’ => [
” => __( ‘Default’, ‘elementor’ ),
] + $slides_to_show,
‘frontend_available’ => true,
]
);
I would like to use the $slides_to_show variable in my javascript code like this.
$(‘.owl-screenshot’).owlCarousel({
loop:true,
responsive:{
1000:{
items:$slides_to_show
}
}
})
How is it possible to use the $slides_to_show in my js file? Can’t find a solution hopefully you can give me a tip.

**Comment by bainternet** [comment]
@Veri21 

Hard to tell without minimal formatting, but you could add the value as data-* attribute in the render method and use that value ex:

```PHP
public function render() {
    $settings = $this->get_active_settings();
    $default = 10;
    $slides_to_show = empty( $settings['slides_to_show'] )? $default : $settings['slides_to_show'];
    ?>
    <div class="my-widget-wrapper" data-slides-to-show="<?php echo $slides_to_show; ?>">
        widget content
    </div>
    <?php
}
```

and in the JS:
```JS
$(‘.owl-screenshot’).owlCarousel({
    loop:true,
    responsive:{
        1000:{
            items: $( '.my-widget-wrapper' ).data( 'slides-to-show' )
        }
    }
});
```

Not tested but should get you started.
