### ISSUE TITLE
WooCommerce widget don't use templates files in theme

### ISSUE THREAD

**Issue by shetil** [pojome/elementor#4967]
Found that the new Woocommerce Widgets in the beta don't use Woocommerce templates files overwritten in the theme directory.

I added the following code to elementor-pro/modules/woocommerce/widget/widget-base.php:include_wc_template() to make it work:

```php
if(file_exists( get_template_directory() . '/woocommerce/' . $template_name ) ){
  include( get_template_directory() . '/woocommerce/' . $template_name );
} else {
  include( WC()->plugin_path() . '/templates/' . $template_name );
}
```

**Comment by bainternet** [comment]
thanks for reporting should be fixed in next beta.
