### ISSUE TITLE
Call javascript in the live preview

### ISSUE THREAD

**Issue by d-to-the-g-to-the-danny-g** [pojome/elementor#4968]
I'm building my own element based on slick.js. Everything works on the frontend but I need to call my js file in the elementor live preview. 

Is there a way to call my js in the preview?

**Comment by Veri21** [comment]
I solved this problem like this:
	protected function render() {
		// get_settings() gets all data associated with the instance of this Widget (values for controls, etc)
		$sample_pricing = $this->get_settings();
		
		// Separate out my PHP template into it's own file
		include( get_template_directory() . '/template-parts/pricing.php' );

		 if ( Plugin::$instance->editor->is_edit_mode() ) : ?>



		<script>	
		$('.owl-screenshot').owlCarousel({
			loop:true,
			autoplay:true,
			margin:10,
			nav:false,
			dots:true,
			navText : ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
			responsive:{
				0:{
					items:2
				},
				600:{
					items:3
				},
				1000:{
					items:4
				}
			}
		})
		</script>
		
		<?php endif; 
	}
and on top you have to add <?php use Elementor\Plugin;

but i have a question is it possible to use defined variables in javascript?

		$('.owl-screenshot').owlCarousel({
			loop:true,
			responsive:{
				0:{
					items:2
				},
				600:{
					items:3
				},
				1000:{
					**items: $slides_to_show**
				}
			}
		})
if i defined it in my own widget

		$this->add_responsive_control(
			'slides_to_show',
			[
				'label' => __( 'Slides to Show', 'elementor' ),
				'type' => Controls_Manager::SELECT,
				'options' => [
					'' => __( 'Default', 'elementor' ),
				] + $slides_to_show,
				'frontend_available' => true,
			]
		);
Did you solved this problem?

**Comment by sf-steve** [comment]
You can use elementors js hooks:

`$( window ).on( 'elementor/frontend/init', function() {
        //hook name is 'frontend/element_ready/{widget-name}.{skin} - i dont know how skins work yet, so for now presume it will
        //always be 'default', so for example 'frontend/element_ready/slick-slider.default'
        //$scope is a jquery wrapped parent element
        elementorFrontend.hooks.addAction( 'frontend/element_ready/slick-slider.default', function($scope, $){
            $scope.find('.js-slick-slider').slick({
                arrows: false,
                autoplay: true,
                autoplaySpeed: 3000,
            });

        });
    } );`

**Comment by dimative** [comment]
@sf-steve OMG. Your comment saved my day. Thank you very much.

**Comment by dbjpanda** [comment]
An example [here](https://github.com/elementor/elementor-hello-world/blob/master/assets/js/hello-world.js) . 

Just change 

`elementorFrontend.hooks.addAction( 'frontend/element_ready/hello-world.default', WidgetHelloWorldHandler );`

 to 

`elementorFrontend.hooks.addAction( 'frontend/element_ready/YOUR_WIDGET_NAME.default', WidgetHelloWorldHandler );` 

Widget name can be found from [here](https://github.com/elementor/elementor-hello-world/blob/09839c53401534e6a33d597be0e0de633c14c8da/widgets/hello-world.php#L28)

**Comment by Sakib3s** [comment]
You can follow this video.
https://www.youtube.com/watch?v=_T3RagcM67I
Thanks.
