### ISSUE TITLE
Elementor Pro/GeneratePress | Post Template Conflicts

### ISSUE THREAD

**Issue by weldon2k** [pojome/elementor#4969]
Started to create Post template with Elementor Pro . . . 

Retreated to create standard Post with GeneratePress.

Header and graphic from the DELETED plus PURGED FROM CACHE of Elementor Pro template persists.

Cannot seem to start a clean post with GeneratePress?

Version 2.0.13 Elementor Pro
Version: 2.1.3  GeneratePress.

**Comment by bainternet** [comment]
@weldon2k 

Thanks for reporting, We can't replicate this issue,
Please contact our support at support@elementor.com for guidance in resolving this issue.
