### ISSUE TITLE
Add Predefined Templates

### ISSUE THREAD

**Issue by atashinbar** [pojome/elementor#4970]
Hi,
I am developing a WordPress theme. I want to add my template as predefined templates inside your templates in new tab (for example : "Theme Template"). Do you have documentation about that? I did search in you developer documentation, but can not find any solution in this regard. https://developers.elementor.com/  Thank you

**Comment by atashinbar** [comment]
Anyone don't answer about it?

**Comment by bainternet** [comment]
Our templates are simple custom post type, which can be exported/imported via the native WordPress functionality or via Elementors template export/import as json/zip files.

take a look at the source to see how it works
https://github.com/pojome/elementor/blob/master/includes/template-library/sources/local.php
