### ISSUE TITLE
JavaScript Bug with Repeater Field after upate to 2.1

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#4972]
I detected a bug witht the latest version of Elementor (2.1.1).

I have a widget with a repeater field set this way:

```
		$this->add_control(
			'mis_a_lhonneur',
			[
				'section'       => 'section_file',
				'label'         => 'Mis à l\'honneur',
				'type'          => Controls_Manager::REPEATER,
				'fields'        => [
					[
						'name'        => 'prenom_et_nom',
						'label'       => 'Prénom et Nom',
						'label_block' => true,
						'type'        => Controls_Manager::TEXT,
					],
				],
				'title_field'   => '{{{ prenom_et_nom }}}',
				'prevent_empty' => false,
			]
		);
```

This code worked perfectly up to Elementor 2.0.16 (+ Elementor Pro v2.0.13).

![image](https://user-images.githubusercontent.com/1431508/42366358-45b856da-8101-11e8-947a-1c17a81f733c.png)

Now, once I click on the "+ Add an element" button, I get a JS error:

![image](https://user-images.githubusercontent.com/1431508/42366602-dfaf35ce-8101-11e8-8340-80a94e4e92a2.png)

This JS error is due to the templating system which resolves the new item title using the "title_field" setting. My "prenom_et_nom" field - which is used for the item title - have no default value: the templating system get an object with only the value of a select field (entite) also part of the repeater... we clearly see there is no 'prenom_et_nom' property on the object passed to the templating system.

Before, in such a case, "Item #" was automaticaly used for the new item title; as seen on the first screenshot of this page. Setting a default valyue is not an option: it's clearly more user friendly not to have a prepoluated value in a field that need to be filled.

**Comment by therealgilles** [comment]
I am also seeing this with the Ultimate Addons Google Map widget.

**Comment by j-arens** [comment]
+1 I'm also having the same problem.

**Comment by sandeshjangam** [comment]
@bainternet Is it required to set a default value in repeater field. Add new item throwing an error?

**Comment by bainternet** [comment]
@sandeshjangam @therealgilles @j-arens @tristanleboss 

Please updated according to this doc:
https://developers.elementor.com/elementor-controls/repeater-control/

thanks

**Comment by tristanleboss** [comment]
I don't understand what has been updated on the doc?

Anyway, breaking compatibility is not that cool. WordPress try to avoid it to a maximum.

Also, throwing a big JS error because a field is missing a default value is not really a solution to me.
