### ISSUE TITLE
Icon list needs responsive controls for list or inline

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#4976]
The icon list element can use some responsive controls to show the list inline or as a list. On desktop inline is nice but on mobile a list view is more desirable.
Also the separation line should have an responsive option for on/off. 
See attached screenshots
Regards
![schermafdruk van 2018-07-06 13-32-40](https://user-images.githubusercontent.com/2702064/42377041-dd5f98fc-8121-11e8-8001-1bd724f5ddf6.png)
![schermafdruk van 2018-07-06 13-32-55](https://user-images.githubusercontent.com/2702064/42377042-dd7ccff8-8121-11e8-9f6e-c8ad45637aed.png)

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
@knireis 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, I can only suggest a different section one per desktop/tablet inline and on for mobile as a list

Thanks for the feedback.
