### ISSUE TITLE
Bring Back Delete & Duplicate Buttons

### ISSUE THREAD

**Issue by dihetherington** [pojome/elementor#4981]
Elementor is excellent but can you please reinstate the Delete & Duplicate Buttons so people can either using the buttons or the right click option. Using right click for delete requires 2 button clicks.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by black-eye** [comment]
+1

**Comment by quinnfive** [comment]
+1

**Comment by StreetDog1971** [comment]
+1

**Comment by bainternet** [comment]
thanks for the feedback,

For now, this is the way we feel is best for Elementor, you may need to click one more click to duplicate or delete but you gain much more with the functionality the context menu introduces and enables us to add to it.

Also, you can delete with the delete key.

Thanks again for the feedback.

**Comment by quantumleap33** [comment]
+1

**Comment by StreetDog1971** [comment]
You might feel is the best for Elementor, but apparently a lot of users don't.
With so many builders competing out there, I'd think twice before ignoring what the community is telling you guys.

**Comment by black-eye** [comment]
Well, there's no need for chosing EITHER "quick buttons" OR right click menu. Why just don't keep them BOTH?

After several hours there're already 6 people supporting this feature here, and there are several much more crowded thread on this subject in FB group as well (e.g. https://www.facebook.com/groups/Elementors/permalink/1568824263243354/).

Hope you are listenning to such feedback even when this issue is closed now...

**Comment by Hanleymade** [comment]
This is becoming a very BAD trend from Elementor to ignore the feedback from it's existing customers. As black-eye has said and MANY others both here and on FB, we want BOTH features. 
No one has said eliminate the right click, but give Visual based User a way that works for them.

I'm really starting to consider if Elementor is the tool for me, based on the way the Elementor team is handling customer relations. I just watched a thread in FB where the Crocoblock Developer not only listened to his customers feedback, commented on it in FB, but also said he would implement it into their roadmap.

When is the last time anyone can say that Elementor is doing that? 

You are NOT listening to your customers.

**Comment by PP100** [comment]
Agree with above in giving users more than way to do the same action 
Also for users you currently have ambiguity in the context menu along with the limited inline editing.
eg I can select text but if I then select the context menu "delete" - it doesnt delete the selected text (as I first expected) but the section,widget or column?
So I think the context menu needs to specify delete column/section or widget
which ever is correct or selected at the time, not just say "delete"

**Comment by dollhauss** [comment]
Elementor stopped listening to the community some time ago. It all started when they thought it would be a good idea to remove the View Live Site option and hide the Exit to Dashboard button. Now they constantly remove features providing no legacy support.

This is a HUGE problem for agencies building sites for clients. 
I personally spent a long time and lots of money teaching clients how to use Elementor - making them nice tutorial videos etc.
Now none of my clients know how to use Elementor anymore and my inbox is flooded with confused clients.

Elementor team - you need to stop making changes based only on what you think may be best and start listening to the community who actually use Elementor before you start to lose customers. It's starting to get pretty ridiculous now. If you want to make wild changes this is fine - but please include legacy support for the original options / workflow.

**Comment by ewokee** [comment]
how to not listen to the community. not even try to :) - congrats.

**Comment by quantumleap33** [comment]
Disappointing...

**Comment by Hanleymade** [comment]
@ramonztro It was closed within two days. Zero chance for customer feedback. Apparently you have start a customer support ticket individually for them to even consider it, unless it's a bug.

**Comment by bentalgad** [comment]
+1 The new right click thing is just the worst decision ever. it makes the workflow so unintuitive. Bring back the hover controls (and like enough users already commented it doesn't have to be instead of the right click, it can be both).

Also i agree that it really seems your ignoring a lot of requests even though they have a lot of users intrest and positive opinions. i know you can't add every feature the users ask, but you really can't do the opposite either.

**Comment by DanGitOnline** [comment]
I like the right click option when on a desktop, but I'm looking for support to copy paste del duplicate from ipad and a single button from the edit panel, the object itsself, somewhere, for popping up the context menu would be great
