### ISSUE TITLE
[FEATURE REQUEST] Role manager (Pro) access to background images

### ISSUE THREAD

**Issue by vsimon51** [pojome/elementor#4982]
The role manager in Pro is useful to limit the options for non-admin users. Text items seem to be universally available. Images in specific widgets (Image; Portfolio; Gallery) are available to be changed *but* images loaded as section or table backgrounds cannot be changed unless you are logged in with full admin rights.
As the background images are often the main header items on pages or a hero page, ability to have non-admin users access those images to change content would be very useful in allowing non-admins to adapt the site.

**Comment by bainternet** [comment]
@vsimon51 

This is how "Content only mode" works, it lets the user with that level of access edit only controls in the widget/column/section content tab.

**Comment by vsimon51** [comment]
As my message indicates, I get that! But think logically please. If the aim is to allow a lower level of access and that is basically limited to text and images, would it not be logical to allow changes to all images including one that is used as a background and very often is the main header visual on a page?

**Comment by avitorio** [comment]
I totally agree with @vsimon51. This is definitely something that should be added to Role Manager. The ability to change backgrounds is paramount. A lot of new designs require full cover backgrounds for sections and columns. Please consider this. Thank you.

**Comment by NickDowns55** [comment]
* following

**Comment by ruturaaj** [comment]
I agree and fully support this Feature Request.

As a work-around, I use Advanced Custom Fields; make the Meta Boxes and Fields and then use the ACF image field as Background image in Elementor sections. This way, my clients set the images they want in normal WordPress Editor whilst they open Elementor to change the text. It still confuses many as they go directly into Elementor and search for the way to change the background image; then shoot email to me asking for "how to change that image".
