### ISSUE TITLE
General support for shortcodes in widget settings

### ISSUE THREAD

**Issue by adrianrosca** [pojome/elementor#4983]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Many times I need to pull some dynamic data into widget settings that doesn't support Dynamic Content.

In most cases I cannot use Global Widgets because there's one setting that needs to be different depending on the page I put them on.

E.g. I have a situation where I need to put the exact same form on many pages. The only thing that differs between them is the "tags" settings for the ActiveCampaign action.

Now I have to put copies of the same form on all pages because of that single setting.

**Describe the solution you'd like**
Shortcodes should be supported for all settings that take text values. Then [pods] or [act] (or some other shortcode) could be used where needed.

It could be limited to text lookup. So it doesn't have to support all complex field types.

**Describe alternatives you've considered**
I have no good alternatives to solve this, except copying the same widget to many locations.

**Additional context**
![image](https://user-images.githubusercontent.com/394825/42409295-9afc97d2-81d8-11e8-9b82-1dcca3c0cf75.png)

**Comment by bainternet** [comment]
@adrianrosca 

Currently, this feature is not supported, but I've added a method to allow this customization in the forms field, which should be out in the next versions of Elementor Pro

Once it's released you could apply the shorcode to the value via an action hook, ex:
```PHP
<?php
/**
 * Elementor form process.
 *
 * Fires when form fields are being processed.
 *
 * @param Form_Record  $record         An instance of the form record.
 * @param Ajax_Handler $ajax_handler An instance of the ajax handler.
 */
add_action( 'elementor_pro/forms/process', function( $record, $ajax_handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	// If its our form then apply the shortcode on the desired field
	$form_settings = $record->get( 'form_settings' );
	if ( isset( $form_settings['activecampaign_tags'] ) ) {
		//apply shortcode
		$form_settings['activecampaign_tags'] = do_shortcode( $form_settings['activecampaign_tags'] );
		$record->set( 'form_settings', $form_settings );
	}
}, 10, 2 );
```
I'll keep this open until its released.

Thanks for the feedback.

**Comment by adrianrosca** [comment]
@bainternet I put your example in functions.php, but neither [acf] or [pods] seem to parse like expected. Maybe the reason could be that [acf] and [pods] are dependent on the current page/post? Is that avaliable in functions.php?

Do you know a better place to put the code than the functions.php?

Thanks for your quick response on this.
