### ISSUE TITLE
Ability to select page for editing inside the editor

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#4986]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**The problem is moving from page to page is too long**
When you edit your homepage (just an example) and then you want to edit your contact page (just an example) you have to 1. Click the hamburger menu 2. Click "EXIT TO DASHBOARD" 3. Click "Pages" 4. Click "Edit with elementor" on the page you want to edit now (the contact page for example) - which is 4 clicks and a lot of loading waiting time (Waisting time).

**While it can be so simple to fix**
By just adding a simple dropdown menu with the pages / and posts of the site (just like you have with the dynamic content dropdowns) that let's you jump to another page / post edit.

Which make's it only 2 click's and a lot faster (no unnecessary waisted loading time).

**Another note**
It can be also a great idea to add header, footer and other template parts in that drop menu also, so you can get to edit them faster.

I think it will generally make a site building faster by far then it is right now and it will make the workflow so much more convenient.

Thanks!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by PP100** [comment]
I agree the basic WP move between edit pages/option  is very cumbersome. 
For now 
 I use a plug in called Admin Page Spider 
https://wordpress.org/plugins/admin-page-spider/

but its only one way it could be implemented, there's another plug in that adds a drop down menu for ELementor  options
https://wordpress.org/plugins/toolbar-extras/
 but incorporating something like the options above  into EL would reduce the need for yet another plug in to improve workflow
You could maybe have the option of turning it on or off.

**Comment by bentalgad** [comment]
That's great for people that choose to display the toolbar, but i prefer saving my screen for my site and the Elementor tools, and i don't have a need for the other tools the toolbar gives, so it's just distracting me from my site design. i think having this dropdown inside Elementor's sidebar is a very basic need.

**Comment by arielk** [comment]
Ref: https://github.com/pojome/elementor/issues/292
