### ISSUE TITLE
Elementor NavMenu Drop-Down Disappearance Delay Time

### ISSUE THREAD

**Issue by dramirvf** [pojome/elementor#4989]
Hello,
There is an annoying default Animation set for Elementor Dropdown in NavMenu which sets a long delay for disappearance of Dropdown on Mouse Out. This makes the menu look lagging or resembles a very slow website.

**I have explained and shown the issue in the following video:
https://amirvf.synology.me/amirvf/elementorvideos/#dropdowndelay**

Customer service of Elementor Pro has referred me to post here so Elementor Developers could look into it.

This delay animation is an event listener on the "Nav Menu" which is being called from the following JavaScript: **"\elementor\assets\js\frontend.js"**

**I have 2 request from Elementor Developers:**
1. Add the "Drop-Down Disappearance Delay Time" as a feature to be customized by users in Elementor.
2. Let me know how to manually remove or reduce this animation at the moment?

**Thanks,
Amir**

**Comment by bainternet** [comment]
@dramirvf 

The delayed hide is actually a feature from the SmartMenus jQuery library used in the nav menu widget, which currently you can only modify via Javascript ex:

```JS
//get menu instance
var $menu = $( '#menu_id' );
// destroy the menu
$menu.smartmenus('destroy');
//re- instantiate the menu with no delay settings
$menu.smartmenus( { 
    subIndicatorsText: '',
    subIndicatorsPos: 'append',
    subMenusMaxWidth: '1000px',
    hideFunction: null,
    hideDuration: 0,
    hideTimeout: 0,
});
```

This is an example but should get you started.

thanks.

**Comment by dramirvf** [comment]
Hi,
It needed some modifications in the code to get it working. Anyways, it was a great hint and worked for me.
Thanks

**Comment by TheMangoTrain** [comment]
This worked for me as well, thx.

**Summary:**
To change Elementor drop-down menu fade timing, or other related properties, the menu needs to be re-invoked with new properties. The menu is based on SmartMenus, find the documentation [here](https://www.smartmenus.org/docs/).

The script bainternet provided goes into your theme (or child theme) JS file, here it is with some changes:

```
jQuery(document).ready(function($) {

   // Get the menu instance
   // The id you want is from the <ul> of the drop-down menu
  var $menu = $('#menu-1-a84052f');

  // Get rid of the existing menu
  $menu.smartmenus('destroy');

  // Re-instantiate the new menu, with no delay settings
  $menu.smartmenus( {
      subIndicatorsText: '',
      subIndicatorsPos: 'append',
      subMenusMaxWidth: '1000px',
      hideFunction: null,
      hideDuration: 0,
      hideTimeout: 0,
  });

});
```

**Comment by gau124berwal** [comment]
where I have to change these setting
can u tell me the exact location for this setting

**Comment by fippy** [comment]
Hi, this is really helpful. However, how can you ensure you copy over ALL of the instantiated settings and only then change the ones you want or add new ones?
