### ISSUE TITLE
[Enhancement] New Page Carousel widget

### ISSUE THREAD

**Issue by dtbaker** [pojome/elementor#499]
I just created a simple Page Carousel plugin for Elementor. 

It's a little rough but works well. Basically you design each of your "slides" as individual private pages, then you select which page to show in the slider. It has all the same configuration options as the current Image Carousel widget. 

Is this something that could be included as a new core widget? There are a few core changes required to make this work smoothly. 

![image](https://cloud.githubusercontent.com/assets/543073/18237653/787535a0-7377-11e6-9331-99734b761c1d.png)

**Comment by joshmarom** [comment]
Hi @dtbaker  
Thank you for your interest in Elementor.
We like what you are doing. Although we are working on our own version of a "rich slider", your approach is creative and we would love to take a closer look at it.

- When you say you are using other pages as slides, you mean you use "the_content" of the other page as a slide?
- How is the result rendered in the live view editor? does it show the actual result or just a placeholder?

**Comment by dtbaker** [comment]
At the moment it's just showing a placeholder in the live view. I will
probably leave it that way for my purpose.

Yes I use content of other pages ( or custom post types ) as slides. This
lets me design the individual sides using elementor, page by page. The
slide content is run through the_content filter so that elementor renders
easy slide layout correctly.

There are a few issues around these nested elementor css styles, but they
are easy to fix in core if needed.

Looking forward to seeing your rich slider!

**Comment by bainternet** [comment]
closing as already implemented https://docs.elementor.com/article/93-slides
