### ISSUE TITLE
Bug in Elementor Pro Responsive Header

### ISSUE THREAD

**Issue by dramirvf** [pojome/elementor#4992]
Hi,
There is a bug in the Elementor Responsive Header. I have explained this issue to Elementor Support Team and they told me that they have escalated this issue to Developer Team but there has been no solution or contact for a long time. So I decided to mention the issue here as well.

I have set a header with Elementor Pro. To make the header Responsive, I have created different sections and in the "Advanced/Responsive" menu of each Section, I have defined whether this section is shown in Desktop, Tablet, or mobile.

There is a critical bug here at very specific widths, when all sections are shown together!!!! This specific width is relevant to different browsers / different zooms in browsers / and different responsive checker tool that you are using.

**I have explained the issue in the following video:**
https://amirvf.synology.me/amirvf/elementorvideos/#responsiveheader

**I have also provided some snapshots here:**
**1. For example here is a good behavior in responsive mode for "Galaxy Tab 3" with the width of 800px, Browser Firefox, Zoom 90% (Sections for Tablet is shown).**
![header 1](https://user-images.githubusercontent.com/40552131/42418301-0ca19288-826b-11e8-9c4b-064a24f4fe0e.jpg)

**2. But here is the strange behavior in responsive mode for "Apple iPad 3, or 4, or Air, or Air2" with the width of 768px, Browser Firefox, Zoom 90% (All sections for Desktop/Tablet/Mobile are shown together).**
![header 2](https://user-images.githubusercontent.com/40552131/42418302-13d34c68-826b-11e8-9919-bb4c96986f80.jpg)

**3. Again here is the Good behavior in responsive mode for "Apple iPad 3, or 4, or Air, or Air2" with the width of 768px, Browser Firefox, Zoom 110% (Sections for Tablet is shown).**
![header 3](https://user-images.githubusercontent.com/40552131/42418305-1947bbca-826b-11e8-978a-df4755e5473a.jpg)

**4. But here is the strange behavior in responsive mode for "Apple iPad 3, or 4, or Air, or Air2" with the width of 768px, Browser Firefox, Zoom 80% (Sections for Mobile is shown).**
![header 4](https://user-images.githubusercontent.com/40552131/42418306-1e81b8ac-826b-11e8-883a-7d13f65d9fe4.jpg)

As there are many "Apple iPad 3, or 4, or Air, or Air2" tablets in the market (which has width: 768px), this issue could be very serious. I have checked this issue and have seen that in Google Chrome/Firefox and using many different responsive checker tools. The issue is very PERSISTENT and present but you should find that particular width at which the issue occurs!

I really like to hear the comments from Elementor Developers.

**Thanks,
Amir**

**Comment by bainternet** [comment]
@dramirvf 

Why would you check with zoom other than 100% ??? please check with an actual device and feel free to re-open if the issue actually exists.

**Comment by bainternet** [comment]
@dramirvf 

We can simulate as well but playing with the zoom will not work and doesn't actually simulate real device behavior.

We checked your site and the 3 default breakpoints work just fine.

thanks

**Comment by dramirvf** [comment]
So you mean that this is only seen in the simulations on desktop and won't
appear in the real device?
