### ISSUE TITLE
Field validation is not working well with new_record

### ISSUE THREAD

**Issue by odedta** [pojome/elementor#4994]
I use both functions:
elementor_pro/forms/new_record
elementor_pro/forms/validation

On the validation function I use your sample code to check the phone number field to have 9 digits minimum

On the new record function I post the fields to zapier for integration.

I would like to know how to stop the post to zapier (stop the function new_record) if the validation isn't successfull.

Does it have anything to do with the functions priority?

Thanks

**Comment by bainternet** [comment]
@odedta 

Paste your code and I'll have a look.

**Comment by odedta** [comment]
`/*
 * Start session
 */
function my_start_session() {
    if ( ! session_id() ) {
		session_start();
    }
}
add_action( 'init', 'my_start_session', 1 );

/*
 * Post leads to Zapier
 */
function manipulate_form_submission( $record, $ajax_handler ) {

    $form_data = $record->get_formatted_data();

    if ( isset( $form_data[ 'form_name' ] ) && 'first_form' === $form_data[ 'form_name' ] ) {
		$_SESSION[ 'full_name' ] = isset( $form_data[ 'name' ] ) ? $form_data[ 'name' ] : '';
		$_SESSION[ 'email' ]	 = isset( $form_data[ 'email' ] ) ? $form_data[ 'email' ] : '';
		$new_data = array(
			'full_name'		 	 => $_SESSION[ 'full_name' ],
			'phone'			 	 => isset( $form_data[ 'phone' ] ) ? $form_data[ 'phone' ] : '',
			'email'			 	 => $_SESSION[ 'email' ],
			'country_of_birth'	 => isset( $form_data[ 'country_of_birth' ] ) ? $form_data[ 'country_of_birth' ] : '',
			'utm_source'		 => isset( $form_data[ 'utm_source' ] ) ? $form_data[ 'utm_source' ] : '',
			'utm_campaign'		 => isset( $form_data[ 'utm_campaign' ] ) ? $form_data[ 'utm_campaign' ] : '',
			'utm_medium'		 => isset( $form_data[ 'utm_medium' ] ) ? $form_data[ 'utm_medium' ] : '',
		);
		$url = 'https://hooks.zapier.com/hooks/catch/3436463/wt8mab/';
    }
    if ( isset( $form_data[ 'form_name' ] ) && 'second_form' === $form_data[ 'form_name' ] ) {
		$new_data = array(
			'full_name'		 	 => $_SESSION[ 'full_name' ],
			'email'			 	 => $_SESSION[ 'email' ],
			'current_country'	 => isset( $form_data[ 'current_country' ] ) ? $form_data[ 'current_country' ] : '',
			'marital_status'	 => isset( $form_data[ 'marital_status' ] ) ? $form_data[ 'marital_status' ] : '',
			'monthly_income'	 => isset( $form_data[ 'monthly_income' ] ) ? $form_data[ 'monthly_income' ] : '',
			'level_of_education' => isset( $form_data[ 'level_of_education' ] ) ? $form_data[ 'level_of_education' ] : '',
		);
		$url = 'https://hooks.zapier.com/hooks/catch/3436463/w1l0un/';
    }

	// Client wants 3 seconds delay before redirecting to next page.
	sleep( 3 );
		
	$response = wp_remote_post( $url, array( 'body' => $new_data ) );

	//if the failure of our additional webhook should prevent the form from submitting...
	if ( is_wp_error( $response ) ) {
		$msg = 'There was a problem launching the rocket. Please check with mission control.';
		$ajax_handler->add_error( $form_data[ 'id' ], $msg );
		$ajax_handler->add_error_message( $msg );
		$ajax_handler->is_success = false;
	}
}
add_action( 'elementor_pro/forms/new_record', 'manipulate_form_submission', 10, 2 );

/*
 * Validate form fields: Phone field should contain at least 9 digits
 */
function check_form_fields( $record, $ajax_handler ) {
	$fields = $record->get_field( [
		'id' => 'form-field-phone',
	] );

	if ( empty( $fields ) ) {
		return;
	}
	
	$field = current( $fields );
	
	if ( 1 !== preg_match( '/[0-9]{9,}/', $field['value'] ) ) {;
		$msg = 'מספר טלפון יכיל לפחות 9 ספרות';
		$ajax_handler->add_error( $field[ 'id' ], $msg );
		$ajax_handler->add_error_message( $msg );
		$ajax_handler->is_success = false;
	}
	else {
		$ajax_handler->is_success = true;
	}
}
add_action( 'elementor_pro/forms/validation', 'check_form_fields', 10, 2 );`

**Comment by bainternet** [comment]
You made a big mess of things,

First, you start with the validation, if you only validate on field use the correct hook:
`add_actionelementor_pro/forms/validation/{$field_type}` so:

```PHP
add_action( 'elementor_pro/forms/validation/tel', function( $field, $record, $ajax_handler ) {
	if ( 1 !== preg_match( '/[0-9]{9,}/', $field['value'] ) ) {
		$msg = 'מספר טלפון יכיל לפחות 9 ספרות';
		$ajax_handler->add_error( $field['id'], $msg );
		$ajax_handler->add_error_message( $msg );
	}
}, 10, 3 );
```

anything else is not needed including `	$ajax_handler->is_success = true/false;`

next if no errors were found, elementor starts running the actions after submit one by one and only then the `elementor_pro/forms/new_record` action hooks run so in your code:

```PHP
//if the failure of our additional webhook should prevent the form from submitting...
if ( is_wp_error( $response ) ) {
	$msg = 'There was a problem launching the rocket. Please check with mission control.';
	$ajax_handler->add_error( $form_data[ 'id' ], $msg );
	$ajax_handler->add_error_message( $msg );
	$ajax_handler->is_success = false;
}
```
is useless and you can't stop the proccessing which is already done.

Also in your code:
```PHP
// Client wants 3 seconds delay before redirecting to next page.
sleep( 3 );
```

This code is run in an ajax request so it makes no sense to delay the response. If you want to delay the redirect use JavaScript `setTimeout` for that.

**Comment by odedta** [comment]
Thanks a lot for the explanation!!!
