### ISSUE TITLE
Countdown's "Date set according to your timezone" does not account for Daylight Saving Time (DST)

### ISSUE THREAD

**Issue by mylimoproject** [pojome/elementor#4997]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
Countdown setup does not account for Daylight Saving Time (DST). So, it will create a +1 hour difference which is not ideal and "Fake News" as Donald Trump will call it. 
For example: I am trying to set a countdown for the 2018 International Soccer Cup match in Miami's Hard Rock Stadium. The first game that starts on July 28th at 1900 hrs, but widget is auto applying UTC zone (UTC -05:00  Eastern Time for US & Canada) and because it's not accounting for DST, it's adding an extra hour (8:00 PM). 
This is where countdown is being used => https://123corporatetransportation.com/black-car-service-miami-airport-transfers-bus-rentals-limo-hire/
This is the URL to related DST in order to apply widget fix => https://www.timeanddate.com/time/change/usa

## Steps to reproduce
Self explanatory as per bug/issue description

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
N/A
<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.5
	PHP Version: 7.2.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: https://123corporatetransportation.com
	Home URL: https://123corporatetransportation.com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Anti-Malware Security and Brute-Force Firewall
		Version: 4.17.58
		Author: Eli Scheetz

	Automatic Copyright Year
		Version: 1.0
		Author: WPSOS

	Better Font Awesome
		Version: 1.7.1
		Author: Mickey Kay

	Easy 301 Redirects
		Version: 1.33
		Author: Odihost.com

	Elementor
		Version: 2.1.1
		Author: Elementor.com

	Elementor Addons & Templates - Sizzify Lite
		Version: 1.2.1
		Author: ThemeIsle

	Elementor Pro
		Version: 2.1.0-alpha1
		Author: Elementor.com

	Health Check
		Version: 1.1.2
		Author: The WordPress.org community

	Heartbeat Control
		Version: 1.2.3
		Author: Jeff Matson

	Really Simple SSL
		Version: 3.0.2
		Author: Rogier Lankhorst

	SiteOrigin CSS
		Version: 1.2.3
		Author: SiteOrigin

	SiteOrigin Widgets Bundle
		Version: 1.11.8
		Author: SiteOrigin

	Squirrly SEO 2018 (Briefcase)
		Version: 8.3.21
		Author: Squirrly SEO

	Travelpayouts
		Version: 0.7.6
		Author: travelpayouts

	W3 Total Cache
		Version: 0.9.7
		Author: Frederick Townes

	Windows Compatibility Fix
		Version: 1.0.1
		Author: Dave Jesch

	WP OPcache
		Version: 2.4.2
		Author: Infogérance Linux

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.4
		Author: 

== Debug ==
	Errors: 
		TypeError: Cannot read property 'on' of null
			at https://123corporatetransportation.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-25 02:01 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://123corporatetransportation.com/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-25 02:01 +00:00

		TypeError: Cannot read property 'on' of null
			at https://123corporatetransportation.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-25 02:01 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://123corporatetransportation.com/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-25 02:01 +00:00

		TypeError: Cannot read property 'on' of null
			at https://123corporatetransportation.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-25 01:54 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://123corporatetransportation.com/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-25 01:54 +00:00

		TypeError: o.attributes[t.name].each is not a function
			at https://123corporatetransportation.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:103947
			2018-06-24 00:26 +00:00

		TypeError: Cannot read property 'on' of null
			at https://123corporatetransportation.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.15 - 2:82365
			2018-06-12 06:43 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://123corporatetransportation.com/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-12 06:43 +00:00

		TypeError: Cannot read property 'get' of undefined
			at https://123corporatetransportation.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.15 - 2:119957
			2018-06-05 22:35 +00:00

				
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by mylimoproject** [comment]
@bainternet 

Issue remains: I just checked to verify if in fact DST offset adjustment is being applied, but nothing has changed from my original feedback (see screen-shot taken just a few minutes ago).
![countdown-feedback](https://user-images.githubusercontent.com/29313121/43095967-838347ae-8e85-11e8-9ded-94996d0d2787.JPG)

**Comment by bainternet** [comment]
@mylimoproject 

seems . to be working fine now,

please feel free to reopen if the issue persists.

thanks
