### ISSUE TITLE
Dynamic value within add_control

### ISSUE THREAD

**Issue by kiarashi** [pojome/elementor#4998]
Is it possible to support dynamic values within the `options` parameter based on another control that's inside the same section?
Or more simply put, how to get the value of a control within another control? 

A sample code I created:
```
$this->add_control(
				'wp-product-taxonomy',
				[
					'label' 		=> __( 'Taxonomy', $this->textdomain ),
					'type' 			=> \Elementor\Controls_Manager::SELECT,
					'options' 		=> $this->taxonomy_list(),					
				]
			);
			
								
			
			$this->add_control(
				'wp-product-terms',
				[
					'label' 		=> __( 'Select Terms', $this->textdomain ),
					'type' 			=> \Elementor\Controls_Manager::SELECT,
					//'options' 		=> $this->taxonomy_terms( xxx ),	// xxx should be the value of 'wp-product-taxonomy'				
				]
			);
```

**Comment by bainternet** [comment]
@kiarashi 

You can't because the code you have run on the server side before the user selects 'wp-product-taxonomy'.

To do that you would need to create a custom AJAX handler which will get the values of `wp-product-terms` based on the selection of `wp-product-taxonomy`.

We have a few AJAX handlers you can look at in our pro plugin.

**Comment by AmibeWebsites** [comment]
Hi @kiarashi, were you able to do what you were trying to do? I'm able to get something working on the client side using AJAX as @bainternet suggested but I also need to get the value on the server side in the way you were suggesting.

There's a valid use case for it as I've described in #6308. In theory the following code should get the **saved** value of the prior control (i.e. it's not dynamic as such - you need the AJAX for that) but it generated a fatal error which I'm unable to fix :-(

```
$this->get_data()['settings']['wp-product-taxonomy']
```

**Comment by kiarashi** [comment]
Unfortunately not. I can't force my customers to use the pro version... Instead 
I simply created 2 controls (one for tags and one for categories and then use the 'condition' to display either one of them. Downside is that custom taxonomies aren't supported. 

Through hooks/filters I can easily modify every aspect of my plugin, so if a customer of mine wants their own custom taxonomy supported, this can still be done (through customization services). It's not the ideal solution, but it works. 

Sorry I couldn't be of any help.

**Comment by AmibeWebsites** [comment]
Hi @kiarashi, I found a way to do it... take a look at the #6308 thread.
