### ISSUE TITLE
ACF fields not selectable in 2.1.0-beta2

### ISSUE THREAD

**Issue by ShadowXVII** [pojome/elementor#5001]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I can't pick ACF fields once I upgraded to 2.1.0-beta2. Is this ACF field feature only in the stable branch? The beta post (#4923) suggests it should be.

![image](https://user-images.githubusercontent.com/446329/42434727-8a4128f2-8397-11e8-8a9f-90abedb183fd.png)

## Steps to reproduce
See screenshot above.

## Isolating the problem
Rolling back to Elementor Pro stable (2.0.13) restores the option.

![image](https://user-images.githubusercontent.com/446329/42434647-4c125470-8397-11e8-83a3-ed5d7fceb77b.png)

**Comment by bainternet** [comment]
@ShadowXVII 

We can't replicate,
Please contact our support at support@elementor.com for guidance in resolving this issue.

**Comment by temonich** [comment]
I have the same problems.
@ShadowXVII, you were able to solve your problem?
My version Pro is 2.1.4

**Comment by ShadowXVII** [comment]
Sorry, no. I ended up downgrading back to non-beta to restore ACF functionality.

**Comment by ShadowXVII** [comment]
This is broken in 2.1.0 still... any text field, button, image etc are all missing their ACF field and I can't assign new ones. The option is simply just missing from the dropdown.

I have to revert back to v2.0.18. Breaks too much.

Not the only one having issues with this feature; https://www.facebook.com/groups/Elementors/permalink/1618976314894815/

**Comment by ShadowXVII** [comment]
Resolution posted here: https://www.facebook.com/groups/Elementors/permalink/1616845841774529/?comment_tracking=%7B%22tn%22%3A%22R9%22%7D

Must use ACF v5 and above. Move to Elementor Pro v2.1 then ACF v5 (free/early access works too).
Not sure why there's zero doco on this in the change log.
