### ISSUE TITLE
columns and cross-platform 

### ISSUE THREAD

**Issue by xcullx** [pojome/elementor#5004]
Hello.
What do you think about this comparison?
I would like to see Elementor in this list with the inscription Good

![12](https://user-images.githubusercontent.com/39651342/42449594-f0bf5648-8389-11e8-9848-c2ae51d0a27b.png)

**Comment by bainternet** [comment]
@xcullx 

Elementor columns use Flexbox CSS which covers about 96.68% of global browsers according to CanIUse: https://caniuse.com/#search=flex

thanks.
