### ISSUE TITLE
How to export a specific page?

### ISSUE THREAD

**Issue by mdjwel** [pojome/elementor#5005]
I want to export a specific page with all the Elementor contents to a new website. How can I do that?

**Comment by odedta** [comment]
You can save the rows as Templates and export them one by one, then import to the new site, not the best solution but that's what I could find, as far as I know, there is no option to export an entire page but I could be wrong.

**Comment by Webtica** [comment]
You can save a page by doing the following:

1. go to the page and edit with elementor.
2. Next to the Save/update button there is a small arrow button. Click that. 
3. Now click save as template.
4. Give the template a name.
5. Now go to the wp dashboard and go to my templates.
6. Export the page template you just made. 
7. On the new site go to the my templates section and import the page template you made.

**Comment by bainternet** [comment]
@mdjwel 

You can either save the page as a template and use the export/import in Elementor template listing or use the native WordPress Export/import.

thanks.

**Comment by rwillox** [comment]
> You can save a page by doing the following:
> 
> 1. go to the page and edit with elementor.
> 2. Next to the Save/update button there is a small arrow button. Click that.
> 3. Now click save as template.
> 4. Give the template a name.
> 5. Now go to the wp dashboard and go to my templates.
> 6. Export the page template you just made.
> 7. On the new site go to the my templates section and import the page template you made.

That's is the procedure used but the template is being saved with the default header and footer although the page created with elementor canvas as base template! Tried a number of times but each time if template is viewed the header and footer show as part of the page.

**Comment by webspotpl** [comment]
Do I have to buy Elementor Pro to be able to save page as template? Currently i don't see anywhere "save" option.

**Comment by odedta** [comment]
Hmm, I haven't used Elementor (Free) in a very long time so I really don't know but if your plugin is updated and you don't see that option then I guess it's a Pro version feature.
To be honest, Elementor is one of the best WP plugins out there so I think if you would have invested money at all in a Wordpress website, Elementor is a perfect bet!

**Comment by Dilned** [comment]
Hi... I was same problem, but trying I found where upload the theme saved at **Elementor** **Free**.
open a page and edit with Elementor and click in **file** icon at new block, and My themes, in top right side exist a up arrow icon
![Captura de Tela 2019-04-04 às 12 26 00](https://user-images.githubusercontent.com/49282905/55567890-01384b00-56d5-11e9-8110-cd4d43e00c5b.png)
.

**Comment by themadhatmedia** [comment]
Is there a way or a plug-in that will allow me to expert the page without needing to save as a template?

**Comment by jawhalen8463** [comment]
Better yet, how about implement "Save As" the way all software does it. Simply save it as a template (of the same type please, where possible) and then let me open it directly with Elementor later (without the import procedure.) Any other attempt at this is simply wrong.

**Comment by Stevemoretz** [comment]
> @mdjwel
> 
> You can either save the page as a template and use the export/import in Elementor template listing or use the native WordPress Export/import.
> 
> thanks.

With native WordPress Export import.on import it defaults back to WordPress and the whole content gets in wysiwyg in elementor on clicking edit with elementor button.Please help

**Comment by Systemedic** [comment]
What you can do is under tools (general WordPress menu) choose export. Set the files you want to export as waiting so can you only export those pages that you want. Go to the other site and choose import and select the xml file. Don't forget to import the media as well. Works for me!

**Comment by KHRifat** [comment]
> You can save the rows as Templates and export them one by one, then import to the new site, not the best solution but that's what I could find, as far as I know, there is no option to export an entire page but I could be wrong.

You are right @odedta, I can't find any other solution to download the entire page. But DIVI providing this feature, It's very handy & easy to export & import everything in few clicks.

Elementor should have this handy Export & Import Facility like DIVI. I request Elementor to Get this Feature in the nearest future.

**Comment by KHRifat** [comment]
> You can save the rows as Templates and export them one by one, then import to the new site, not the best solution but that's what I could find, as far as I know, there is no option to export an entire page but I could be wrong.

You are right @odedta, I can't find any other solution to download the entire page. But DIVI providing this feature, It's very handy & easy to export & import everything in few clicks.

Elementor should have this handy Export & Import Facility like DIVI. I would request @elementor to Get this Feature in the nearest future.

**Comment by aronr** [comment]
Coming very late to this discussion. (And this is entirely untried by moi.) But noting that Elementor now offers an Export Kit feature that could possibly be useful for copying selected pages and/or other content between sites?

https://elementor.com/help/export-kit/

**Comment by codewizard13** [comment]
> Set the files you want to export as waiting so can you only export those pages that you want.

Can you elaborate the steps you are talking about?

**Comment by Systemedic** [comment]
> > Set the files you want to export as waiting so can you only export those pages that you want.
> 
> Can you elaborate the steps you are talking about?

Sure. Login to your WordPress Dashboard. Go to pages and quick edit the page you want to export. Set the status to Draft.
Go to Tools->Export and select pages -> Status Draft and hit export.
![image](https://github.com/elementor/elementor/assets/58505361/0a275ec1-16f9-43f8-9f85-84e383c53e1f)
