### ISSUE TITLE
Problems with translation using plugin TranslatePress

### ISSUE THREAD

**Issue by Zexler** [pojome/elementor#5007]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

I need to translate the form (in the PRO version), specifically the drop-down list (<option> tag). Other places in the form are translated correctly. I contacted the author of the plugin TranslatePress, gave him the code of your plug-in, and he wrote me the following:

> I managed to reproduce the issue and look a bit into it. Unfortunately, there's nothing we can do from our side to make this translation possible.
> As you noticed, it picks up only the Label for a translation because this is the only element that they run through a translation function.
> 
> These are user inputted options, but before they show them in the form, they should just run them once through the __() function from WordPress: > https://codex.wordpress.org/I18n_for_WordPress_Developers#Translatable_strings
> Once they'll do this, you will be able to find the strings in the dropdown I indicated in my initial response.
> 
> The change should be straightforward
> - Support for the TranslatePress plugin

Can you fix what he asks for? I really want to be able to translate own sites with your product. And the plugin TranslatePress suits me the most. It's sad to give it up.

## Steps to reproduce

- Create a blank page
- Edit it with elementor
- Create a form with a field, with type "Select", and add a few Options with text (without numbers)
- Save this page
- Go to this page
- in admin bar from the top choose "Translate Page" (This button appears when the PlugPress plugin is installed)
- And there, in the left column there are no necessary lines that are in the form that are in the "Select"

![screen45](https://user-images.githubusercontent.com/15948443/42453141-80a8da5e-8394-11e8-9ada-80548ec31678.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.7.16
	PHP Version: 7.0.30
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: http://new.ibs-edu.com.ua
	Home URL: http://new.ibs-edu.com.ua
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: ru-RU
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: IBS Education Template
	Version: 1.0
	Author: Zexler
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: uk
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 4.4.12
		Author: Elliot Condon

	Autoptimize
		Version: 2.3.4
		Author: Frank Goossens (futtta)

	Crop Thumbnails
		Version: 1.1.2
		Author: Volkmar Kantor

	Elementor
		Version: 2.1.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.14
		Author: Elementor.com

	Enhanced Text Widget
		Version: 1.4.6
		Author: Boston Dell-Vandenberg

	Remove Category Base
		Version: 1.0.5
		Author: LittleBizzy

	Slide Anything - Responsive Content / HTML Slider and Carousel
		Version: 2.1.5
		Author: Simon Edge

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	TinyMCE Advanced
		Version: 4.7.11
		Author: Andrew Ozz

	TranslatePress - Multilingual
		Version: 1.2.5
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	WP Translitera
		Version: p1.2.5
		Author: Evgen Yurchenko

== Debug ==
	Errors: 
		TypeError: o.attributes[t.name].each is not a function
			at http://new.ibs-edu.com.ua/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:105550
			2018-07-06 12:57 +00:00
			x 2 times

		TypeError: o.attributes[t.name].each is not a function
			at http://new.ibs-edu.com.ua/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:103947
			2018-07-03 15:32 +00:00

		ViewDestroyedError: View (cid: "view551") has already been destroyed and cannot be used.
			at http://new.ibs-edu.com.ua/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-06 11:06 +00:00

		ViewDestroyedError: View (cid: "view2418") has already been destroyed and cannot be used.
			at http://new.ibs-edu.com.ua/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-05 18:17 +00:00

		SyntaxError: Unexpected token }
			at http://new.ibs-edu.com.ua/wp-admin/post.php?post=282&action=elementor - 8:1
			2018-06-04 10:00 +00:00

		SyntaxError: Unexpected token .
			at http://new.ibs-edu.com.ua/wp-admin/post.php?post=8&action=elementor - 6:99
			2018-06-02 12:01 +00:00

		SyntaxError: Unexpected token }
			at http://new.ibs-edu.com.ua/wp-admin/post.php?post=8&action=elementor - 8:1
			2018-06-01 18:29 +00:00
			x 4 times

		SyntaxError: Invalid or unexpected token
			at http://new.ibs-edu.com.ua/wp-admin/post.php?post=8&action=elementor - 6:1
			2018-06-01 18:29 +00:00

		SyntaxError: Unexpected token ;
			at http://new.ibs-edu.com.ua/wp-admin/post.php?post=8&action=elementor - 5:32
			2018-06-01 18:29 +00:00

		SyntaxError: Unexpected token var
			at http://new.ibs-edu.com.ua/wp-admin/post.php?post=8&action=elementor - 4:1
			2018-06-01 18:29 +00:00

				
</details>

**Comment by bainternet** [comment]
@Zexler 

Thanks for reporting,

We don't run any label via a translateable function because that would cause a major performance hit,
so I'm not sure why he is saying that the label is translatable.

What you can do is duplicate the Form Widget per language and translate it via the Elementor Panel.

If the developer of TranslatePress has a specific issue we would be more than happy to help.

thanks.
