### ISSUE TITLE
Color change on section when using HOVER ANIMATION on image

### ISSUE THREAD

**Issue by elasticeye** [pojome/elementor#5009]
When I use a hover animation on an image, all the sections under the current section turn to gray. See here:
https://www.useloom.com/share/f9abbd8b52a94fdebdc5893ffc30fbad

I use Astra, latest versions of both Astra and Elementor.

**Comment by bainternet** [comment]
@elasticeye 

We can't replicate this, 
Please contact our support at support @elementor.com for guidance in resolving this issue.
