### ISSUE TITLE
Bug Report: Content Width

### ISSUE THREAD

**Issue by atashinbar** [pojome/elementor#5011]
My theme has max-width option for sections and rows. I enabled it and set it to 1660px. But when using elementor, elementor-container has max-width:1140px by default and it breaks my website. Please change field number to text that we can put it "none" as text or set an option to disable this in hole website.
![image](https://user-images.githubusercontent.com/19619864/42493059-9757fc20-8430-11e8-93a0-f93cea6fb6f9.png)
Thank you.

**Comment by bainternet** [comment]
@atashinbar 

Elementor must have a max with, so if your site is set to 1660px, then set it to 1660px.

thanks
