### ISSUE TITLE
Make post object accessible in form action

### ISSUE THREAD

**Issue by adrianrosca** [pojome/elementor#5012]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I've tried different ways to lookup the post id in this action, but none of them works.

	add_action('elementor_pro/forms/process', "process_elementor_form");

	function process_elementor_form($record, $ajax_handler) 
	{
		// try 1
		$post_id = get_the_ID();

		// try 2
		global $wp_query;
		$post_id = $wp_query->post->ID;

		// try 3
		global $post;
		$post_id = $post->ID
	}

**Describe the solution you'd like**
I would either like the post object to be accessible or get the $post as a parameter:

`function process_elementor_form($record, $ajax_handler, $post)`

**Describe alternatives you've considered**
I'm pretty stuck with this one

**Additional context**
-

**Comment by bainternet** [comment]
@adrianrosca 

Global $post, $wp_query are not populated in AJAX requests, and the form is submitted via AJAX so that will never work for you.

However, we do set the current post id as a $_POST variable so you can use that, ex:

```PHP
add_action('elementor_pro/forms/process', function( $record, $ajax_handler ) {
	$post_id = $_POST['post_id'];
}, 10, 2 );
```
