### ISSUE TITLE
Forms API: Paypal integration

### ISSUE THREAD

**Issue by odedta** [pojome/elementor#5015]
I've been trying to think of a few ways to integrate my donation form with paypal donate button or basically to redirect the user with the right data to the paypal donation page but I can't seem to figure out a way to make it happen.

Is it even possible? what would you recommend I try in order to achieve that?

Thanks.

**Comment by bainternet** [comment]
@odedta 

What have you tried? what is " with the right data"?

and yes it possible.

**Comment by odedta** [comment]
@bainternet Thanks for replying.

I would like to create a simple donation form, similar to this for example (taken [from](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/formbasics/#auto-fill-forms-with-html-variables) ):
```
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
  <input type="hidden" name="cmd" value="_cart">
  <input type="hidden" name="business" value="seller@designerfotos.com">
  <input type="hidden" name="item_name" value="hat">
  <input type="hidden" name="item_number" value="123">
  <input type="hidden" name="amount" value="15.00">
  <input type="hidden" name="first_name" value="John">
  <input type="hidden" name="last_name" value="Doe">
  <input type="hidden" name="address1" value="9 Elm Street">
  <input type="hidden" name="address2" value="Apt 5">
  <input type="hidden" name="city" value="Berwyn">
  <input type="hidden" name="state" value="PA">
  <input type="hidden" name="zip" value="19312">
  <input type="hidden" name="night_phone_a" value="610">
  <input type="hidden" name="night_phone_b" value="555">
  <input type="hidden" name="night_phone_c" value="1234">
  <input type="hidden" name="email" value="jdoe@zyzzyu.com">
  <input type="image" name="submit"
    src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif"
    alt="PayPal - The safer, easier way to pay online">
</form>
```

I want to create the form with Elementor so I can save the leads using the Lenix plugin, after the user clicks the Donate button (submit) he will be redirected to Paypal page to pay.

There is no option to change the form action in Elementor.
The redirect option only redirects.
The WebHook option returns some error I can't figure out, basically I couldn't figure out how to use that.
I also tried to use the function `manipulate_form_submittion` and post the variables to Paypal then redirect but wp_redirect() didn't work inside `manipulate_form_submittion`.

Finally, I got this to work by removing all actions after submit and then writing some JS to create the form and dynamically post it to Paypal, but this is a workaround and I'd like to know what would be the right approach to create a donation form and redirect the user to Paypal with all the form data.

I would like to use Elementor Forms, first of all because it's awesome :-) but mostly because if the user wants to save some other data of the donor sometime in the future, they can simply add more inputs and they will be saved using Lenix plugin.

Thanks

**Comment by bainternet** [comment]
Ok then,

> There is no option to change the form action in Elementor.

Changing the Form action won't submmit the form to the server it would submit it to paypal's server so you won't store the lead. Also elementor's froms work via AJAX so for action is not relevent here.

> The redirect option only redirects.

As expacted!

>The WebHook option returns some error I can't figure out, basically I couldn't figure out how to use that.
The webhook is transparent to the user it happens in the server side so the user will never be directed to paypal.

The form you are showing is not a valid paypal donation form, its a cart from.

A few options:

* You can use the actual donation LINK url as a redirect after submit in Elementor Form Settings, eg:
```
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=PAYPAL_EMAIL_HERE&item_name=DONATION_NAME_HERE&cy_code=USD&bn=PP%2dDonationsBF
```

* You can add the paypal form not the one you have (cart form)  in an HTML WIDGET and set it to display none, and add ID to the form for easy access, eg:

```HTML
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" id="PAYPAL_FORM" style="display:none">

    <!-- Identify your business so that you can collect the payments. -->
    <input type="hidden" name="business" value="YOUR_PAYPAL_EMAIL">

    <!-- Specify a Donate button. -->
    <input type="hidden" name="cmd" value="_donations">

    <!-- Specify details about the contribution -->
    <input type="hidden" name="item_name" value="Donation reason">
    <input type="hidden" name="item_number" value="1">
    <input type="hidden" name="currency_code" value="USD">

    <!-- Display the payment button. -->
    <input type="image" name="submit"
    src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif"
    alt="Donate">
    <img alt="" width="1" height="1"
    src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >

</form>
```
Then catch the submit success event and submit the paypal form:

```JS
jQuery( document ).ready( function( $ ) {
    $( '#ELEMENTOR_FORM_ID' ).on('submit_success', function() {
        $( '#PAYPAL_FORM' ).submit();
    } )
} );
```

**Comment by odedta** [comment]
Thank you very much for the detailed answer!
