### ISSUE TITLE
Woocommerce widget add-to-cart: Fatal error

### ISSUE THREAD

**Issue by shetil** [pojome/elementor#5017]
Get an fatal error when I try to use the add-to-cart widget on a single-product template in Elementor Pro beta.

> Fatal error: Uncaught Error: Call to a member function get_type() on string in /var/www/doya/123fest/wp-content/plugins/woocommerce/includes/wc-template-functions.php:1497

I have traced the error to widget/product-add-to-cart.php:render():

`$product = wc_get_product();`

This line creates a local variable called $product but is not available when trying to render the WooCommerce template.

Doing it like this solved the issue:

```
global $product;
$product = wc_get_product();
```

**Comment by bainternet** [comment]
Please make sure to update to Beta3.

thanks
