### ISSUE TITLE
contact_sync option for the Active Campaign integration

### ISSUE THREAD

**Issue by adrianrosca** [pojome/elementor#5020]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Right now only contact_add is supported and requires a list to be selected. That really limits the automation capabilities if a contact submits more than one form.

**Describe the solution you'd like**
It would be really good to be able to choose between "add" and "sync" as a form setting, where "add" can be default. Then it works like it does today. 

I changed the activecampaign-handler.php to call `?api_action=contact_sync` instead. It takes the same parameters, so it makes no difference for the rest of the logic.

**Describe alternatives you've considered**
Change the code myself, but then I will not be able to receive updates.

**Additional context**
![image](https://user-images.githubusercontent.com/394825/42540515-ffe77400-849e-11e8-97a4-49be778b35e4.png)

**Comment by bainternet** [comment]
ref: https://www.activecampaign.com/api/example.php?call=contact_sync

**Comment by adrianrosca** [comment]
@bainternet The simplest option here is ofcourse to just call contact_sync instead of contact_add and don’t change anything else.

The implication of that would be more flexibility without breaking the existing code.

**Comment by unclerom** [comment]
@bainternet Was this fixed? When i use active campaign in elementor forms it will only add duplicate contacts it does not update existing ones

**Comment by zrk4444** [comment]
+1

**Comment by ag-skyler** [comment]
+1 Any update on this?
