### ISSUE TITLE
Feature Request: Dynamic Flip Box

### ISSUE THREAD

**Issue by jameswilliams90** [pojome/elementor#5021]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'd like to be able to dynamically add content and images to the Flip Box element from posts. 

**Describe the solution you'd like**
Add Dynamic options to the Flipbox

**Describe alternatives you've considered**

**Additional context**

**Comment by peteralewis** [comment]
@bainternet How come this is showing as accepted on the v2.1.0 Pro milestone (see above), then marked as pull request, then merged, yet it's not in v2.2.0 Pro...? Did it get added?
