### ISSUE TITLE
Bug Report: Padding and Margin

### ISSUE THREAD

**Issue by atashinbar** [pojome/elementor#5026]
Hi,
When I select unlinked "Link values together" option in padding and margin, default value is zero and I can not remove them. 0 is force. My columns and section have default padding and margin and I don't want they convert to zero. Please fix it. 

![image](https://user-images.githubusercontent.com/19619864/42555878-ee75f876-84fe-11e8-8ca4-3748d98aff6c.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As for what you call a "bug", this is how Elementor works, the defaults are defined in CSS to not store default values in the database. 

thanks.
