### ISSUE TITLE
Woocommerce template part issue

### ISSUE THREAD

**Issue by notrealdev** [pojome/elementor#5030]
Hi, i have issue with woocommerce template, the code below not working after reload page
Specifically: `wc_get_template_part( 'content', 'product' )` not working after reload page
But it works well with Elementor Pro

You can see more on my video:
https://youtu.be/tsBXa4dEvXc

// This is my custom widget, not Elementor Pro

```php
render(){
    global $woocommerce_loop;

    woocommerce_product_loop_start();

    while ( $products_query -> have_posts() ) :
        $products_query -> the_post();
        wc_get_template_part( 'content', 'product' );
    endwhile;

    woocommerce_product_loop_end();

    woocommerce_reset_loop();

    wp_reset_postdata();
}
```

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by notrealdev** [comment]
Yes, can you reopen this issue? @bainternet
