### ISSUE TITLE
Run jQuery to be able hide form after submit

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5031]
A client asked 
_I would suggest that once the form has successfully submitted, the 'thank you' message replaces the form so they cant fill it out again. Its not very obvious and if they aren't good with computers they might think that it hasn’t submitted or not see the message_

Maybe adding an option to allow run jQuery after submittion be a good idea! so can do many things here.

![image](https://user-images.githubusercontent.com/2544046/42620877-ed0088b4-85c4-11e8-962c-4f00a82a4e7e.png)

**Comment by bainternet** [comment]
You can,

There are JavaScript Events we trigger on form submission, but in your case this should work:

```JS
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		// form has been submitted Set your cookie here...
	});
});
```

**Comment by amindiary** [comment]
@mikeys4u in any JS of your theme. 
or use this one in your **function.php** file
add_action('wp_footer', 'your_function_name');
```
function your_function_name(){
?>
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		// form has been submitted Set your cookie here...
	});
});
<?php
};
```

**Comment by remingtonchan** [comment]
@amindiary Hi, I was wondering if you could share how you exactly hid the form. Specifically how you would use declared variables(?) to hide the form. 

Newbie user here and zero experience in jQuery (and tinkering with WordPress elements), so not even sure how to exactly declare "cookies" to use for the logic. 😓 

The behavior you described is the ideal behavior for me as well. Hide form after submit.

**Comment by AdventurouslySocial** [comment]
I found this thread and the suggested code snippet from @bainternet which works wonderfully to run js on a successful form submit of _**any**_ form. I would like to take this one step further and differentiate between forms.

What would be the correct way of running javascript on successful form submission of a form with the ID of #Form1 while not running the code on a successful form submission of #Form2 ?

I have tried the following and it does not seem to work. I have also tried a variation of the below code where I have substituted 'jQuery' with '$'. Neither has worked for me.

    //The event is submit_success so you can catch it for example:
    jQuery( document ).ready(function( $ ){
    	$( #Form1 ).on('submit_success', function(){
    		// form has been submitted Set your cookie here...
    	});
    });

Any helpful insight is greatly appreciated. Thank you.

**Comment by ryonwhyte** [comment]
@AdventurouslySocial in case someone stumbles across this. for a specific form I do this.
`$( document ).on('submit_success', function(event, response){
		if (event.target.id == "form_id_goes_here"){
//do something
}
});`

The form ID I set in elementor form additional options
