### ISSUE TITLE
Make workflow keyboardless as possible

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#5035]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**The Problem: using keyboard numbers makes the workflow a lot less fluent **
When you have to hit the keyboard to set border-radius, border-width, margin, padding and so... it makes work very slow.

**The solution is:**
**Sliders** (like those in the typography size, line-height...).
![slider1](https://user-images.githubusercontent.com/23374215/42633794-33c122d4-85ea-11e8-8d60-761d987678dc.gif)

although you can also make them like the photoshop ones (that you press on then drag) so they take less ui space.
![photoshop sliders](https://user-images.githubusercontent.com/23374215/42633877-61fb3900-85ea-11e8-9538-8a57044bfe64.gif)

**Margins and paddings on place**
![42633181-4fcfdaee-85e8-11e8-935a-490210eedf6e](https://user-images.githubusercontent.com/23374215/42633956-99c3e530-85ea-11e8-9bcb-821907c54432.gif)
(like mentioned here: #5018 )

**Maybe some corner dots**
![2018-07-12 15 48 17](https://user-images.githubusercontent.com/23374215/42634127-0cc31f38-85eb-11e8-811f-d5f6d4b2a16d.gif)

Maybe other stuff, i don't know. just not the keyboard please :)

**Comment by bentalgad** [comment]
Another great idea to add is the brizy style background image position and zoom:
![2018-07-15 16 14 16](https://user-images.githubusercontent.com/23374215/42734308-532be49e-884a-11e8-848c-af94018a5fb3.gif)
(Same thing with background image position...

**Comment by joshallen73** [comment]
I would love to see the image system like brizy - can this be made its own thread? I will post.

**Comment by bentalgad** [comment]
Any news with that? do you think your going to implement that some time in the near future?

**Comment by bentalgad** [comment]
Still Waiting :)
