### ISSUE TITLE
Iframe Pages

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#5041]
Hello guys,

You could give the possibility to use Elementor to create pages with Iframe, whether it is a page with an integer or partial iframe.

This is the suggestion.
Rodrigo Carlos

**Comment by proddigital** [comment]
Hello,

My suggestion for you guys is basically this, being able to create pages with an iframe, ie when creating a page, I would select an iframe widget where I would place a URL from another page to be loaded on this page being created .

It could by default set a width and height of 100%, but could also determine a custom width and height.

So that's basically it, a widget that creates an iframe window.

Thank you!
Rodrigo

**Comment by bainternet** [comment]
@proddigital 

You can use an HTML widget for that.

thanks.

**Comment by proddigital** [comment]
Yes @bainternet
With the html code I know it's possible. But for this I need to always be collecting the iframe code, and know what attributes I should use. And when we use the code, it does not get exactly as we want it, for example, the height of the iframe window does not stay 100% (at the same time as the external page) and ect. We need to be good at code to figure out what to do.

So Elementor could make it easier to just put the URL and that's it.
If someone wants to customize the iframe window, then they would have options to change the height, width, and even the edge of the window.

This is the suggestion.

Thanks.
Rodrigo

**Comment by MrAmazing** [comment]
I get a server error, 403, when I use the HTML Code option if it contains <iframe> </iframe>  any suggestions on how I might correct this?  What information do I need to provide to help diagnose this issue?
