### ISSUE TITLE
Disable "Meet Right Click" Popup

### ISSUE THREAD

**Issue by eplanetdesign** [pojome/elementor#5047]
Is there a way to disable that annoying "Meet Right Click" popup?

**Comment by Jim-E** [comment]
+1

**Comment by bainternet** [comment]
@eplanetdesign 
@Jim-E 
simply click on "Got it" which will tell elementor not to load it anymore.

**Comment by eplanetdesign** [comment]
Clicking "Got It" doesn't work, I've clicked "Got It" probably 50 times, this thing just won't go away and stay away!!! Using OceanWP. I finally resorted to hiding it with CSS.

**Comment by td75** [comment]
How can I hide this with CSS please it won't go away for me either:(

**Comment by black-eye** [comment]
I have this issue too. 
Every time I reaload the page and click the new Edit Section button, the popup is there again, no matter how many times I've "Got it". After a 100 times I'm really imformed enough. ;)

**Comment by eplanetdesign** [comment]
Here's a simple plugin that should hide it.

[elementor-meetrightclick-hider.zip](https://github.com/pojome/elementor/files/2241350/elementor-meetrightclick-hider.zip)

**Comment by blueskyted** [comment]
Thanks @eplanetdesign  your plugin works a treat. 
Initially after install of the plugin it appeared not to work.
Just had to manually enter the included css in my themes additional css area and no more annoying meetrightclick messages.

**Comment by Pikamander2** [comment]
@bainternet - This isn't resolved. Clicking "Got It" only hides the popup until the page is refreshed.

It needs to either go away permanently after clicking "Got It", or there needs to be an option to disable it somewhere.
