### ISSUE TITLE
Option to add text shadow on text on image box widget

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5048]
Isn't there any way to add text shadow to title and body text? **image box widget**

![image](https://user-images.githubusercontent.com/2544046/42693726-b8c49b72-86b8-11e8-8e68-4756cc2ee76b.png)

**Comment by bainternet** [comment]
@amindiary 

There is by simple code snippet,

```PHP
add_action( 'elementor/element/image-box/section_style_content/before_section_end', function( $widget, $args ){
	$widget->add_group_control(
		\Elementor\Group_Control_Text_Shadow::get_type(),
		[
			'name' => 'title_text_shadow',
			'selector' => '{{WRAPPER}} .elementor-image-box-title',
		]
	);
}, 10, 2);
```

**Comment by amindiary** [comment]
@bainternet  thank you, is there any documentation for this type of hacks?
