### ISSUE TITLE
The preview mode is not showing text

### ISSUE THREAD

**Issue by mmaffia1992** [pojome/elementor#5049]
So this is what the live version looks like: 
![image](https://user-images.githubusercontent.com/41164357/42698089-e36d6a62-868a-11e8-908c-5b3cd2ddd507.png)

And this is the back-end:
![image](https://user-images.githubusercontent.com/41164357/42698130-fc2575f4-868a-11e8-8c99-4bbb6d2ad798.png)

All of my plugins are disabled and my Wordpress is up to date. I can't find anything on this issue and it makes it difficult to build a page when I can't see exactly what I'm dragging or dropping or how it looks.

Any suggestions would be appreciated!

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

We can't replicate, so we can't really help.

Please contact our support at support @elementor.com for guidance in resolving this issue.
