### ISSUE TITLE
Dinamic content and Custom Querie on Elementor Pro widgets

### ISSUE THREAD

**Issue by raphaelfiga** [pojome/elementor#5051]
The best widget on Elementor Pro is Posts, because is possible construct layout with the other contents on wordpress and customize it. So, other widgets like a Slides or Testimonial Carousel not is possible get data of wordpress database. This could be a design premise, the widget get posts from WordPress API.

Other feature that I use a lot when create a custom layout is custom queries, mixing posts types (posts, pages,and custom posts e.g. portfolio, etc.) and filter by custom fields and all rules of WordPress API.
You could have a field for these custom queries.

**Comment by bainternet** [comment]
@raphaelfiga 

Thanks for feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

duplicate #4440
