### ISSUE TITLE
request feature 

### ISSUE THREAD

**Issue by jenzo585** [pojome/elementor#5058]
Elementor - would like to have a feature that would allow the user to click on an image and a different image would open up and expand-- like the images at this link https://www.anastasiabroadway.com/
Many requests to add this feature when designing for entertainment industry. Thank you very much

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
