### ISSUE TITLE
Archive Posts Pagination doesn't work

### ISSUE THREAD

**Issue by keitan0011** [pojome/elementor#5063]
I am a Pro User
There is issue with Pagination in the Archive Posts Widget
it doesn't work
but when i use Posts Widget it work
is it a bug?

Archive Posts Widget
![001](https://user-images.githubusercontent.com/41243315/42728884-adff9746-87f8-11e8-9234-a4c6e681ba0d.JPG)

Posts Widget
![002](https://user-images.githubusercontent.com/41243315/42728912-2686e7fa-87f9-11e8-83af-5f9ffd997674.JPG)

**Comment by bainternet** [comment]
@keitan0011 

Thanks for reporting,
Please follow guidelines for opening a new issue, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
