### ISSUE TITLE
Multiple dynamic pages/posts on the same page/template

### ISSUE THREAD

**Issue by LMStudioArt** [pojome/elementor#5064]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am limited to pulling content dynamically for only one page per single page template using the Post Content and Featured Image widgets.

**Describe the solution you'd like**
Pages with small amount of content don't need a full page and I want to combine them onto the same single page, but do it dynamically, then apply menu anchors. 1) If a site is very large, automating content-to-page is essential and 2) I want to leave the content in the WP editor so the client doesn't have to edit in Elementor.

**Describe alternatives you've considered**
Using the Posts widget with a manual page query. I tried this, but the excerpt doesn't hold the styling from the WP editor. And it seems like a sloppy workaround.

**Additional context**
I previously worked in Headway which is no longer being updated, but I still have a couple of sites I haven’t converted to Elementor yet. In Headway, you can place multiple Content blocks on a single page layout and pull the page content from any page into each block using a custom query filters. I’ve attached screen shots from one of my Headway sites to show you how they do it. As I am now learning, the big difference between Headway and Elementor in this respect is that they allow more than one Content block on a single layout. Attaching some screen shots from the Visual Editor in Headway that demonstrate this.
![headway1](https://user-images.githubusercontent.com/41243431/42729013-7f6aab1a-8798-11e8-9859-f7c93fbc4993.jpg)
![headway3](https://user-images.githubusercontent.com/41243431/42729012-61dbe42e-8798-11e8-8135-bf5385f265e6.jpg)
![headway2](https://user-images.githubusercontent.com/41243431/42729014-8474b6c8-8798-11e8-8b02-d75c403cb0ed.jpg)

**Comment by bainternet** [comment]
@LMStudioArt 

You can use multiple Posts Widgets in a template, so unless I'm missing something, what is the request?

https://docs.elementor.com/article/101-posts

**Comment by LMStudioArt** [comment]
Yes, you are missing something. The Posts widget is intended for excerpts, NOT full page content. It does not handle the page content in the same way as the Post Content widget + Featured Image widget. Believe me, I tried it. 

What I want to do is dynamically call FULL page content and featured images from multiple pages onto a single page layout, as demonstrated by the Headway screenshots. Right now, we are limited to ONE Post Content widget and ONE Featured Image widget per single template. I want to have more than one and specify which page or post is called in.

I’ve explained all of this to Elementor support and was directed  by Andri to post this as a feature request.

**Comment by bainternet** [comment]
@LMStudioArt 

Thanks for clarifying.

Now that I understand you, this should be possible with #4440 

closing in favor of #4440 

thanks again.
