### ISSUE TITLE
Replace wp-login.php with own template

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#5069]
My hoster enforces a login always via the wp-login.php page, so creating a custom login page only works efficiently if the wp-login.php page can be replaced by my self designed template.

So in these situations it is convenient to be able to replace the wp-login.php with a custom template. Like i am able to replace the 404 page with a template.

**Comment by bainternet** [comment]
@knireis 

Thanks for the feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for the actual request, currently, wp-login.php is not a part of the WordPress template hierarchy which means you can only apply some level of styling but not overwrite like a single/archive or a 404 template.

For now, you can use Elementor Pro's login form widget.

thanks again.

**Comment by smile00000** [comment]
+1 This is very much needed!

**Comment by smile00000** [comment]
@bainternet I have created a login form widget, but it doesn't seem to replace the wp-admin login page just the my-account login. Can you please provide steps so the elementor pro login to bypass all instances of wp-admin login page?
