### ISSUE TITLE
Exit to Page

### ISSUE THREAD

**Issue by simonclay** [pojome/elementor#5071]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It takes so many clicks to get back to the live page you were editing.

**Describe the solution you'd like**
A button to 'Exit Elementor' that takes you to the live page you were editing without opening new tabs.

**Describe alternatives you've considered**
Granular controls plugin helped a little, but still does not exit to the page that was being edited without opening a new tab.

**Additional context**
It's a function that is performed so often that it's frustrating to not have a quick solution.

**Comment by arielk** [comment]
I merged this issue with another issue  #292 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
