### ISSUE TITLE
Column : Cannot set column width to 100% on desktop breakpoint

### ISSUE THREAD

**Issue by Jonathlee** [pojome/elementor#5072]
![elementor-column](https://user-images.githubusercontent.com/696956/42735204-921b4b9e-8882-11e8-884a-9d4be27d5c08.png)

Objective. In Blue section, I have 2 columns. In desktop breakpoint, I need column 1 and column 2's width to be 100%. 

While during in Tablet breakpoint, I can set column 1 and column's width to 50% to be shown side by side.

Currently I cannot set the column's width to 100% to push the second column to below.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by leolux** [comment]
It is till not working. After entering "100" into the elemntor field for column widht (%) the input disappears after 2 seconds and the column has an unkown width.

**Comment by mjohnson-ionline** [comment]
so how are we meant to stack two columns on top of each other in desktop?

**Comment by T4ngml** [comment]
+1 : I can' make a text block stick to the right of the screen tablet and mobile, but as explain, the % value can't be set on desktop: it just disappears after a couple on seconds.

And... Why only percentages are allowed here ? I'd be glad to be able to set a px width.

**Comment by bigwilliam** [comment]
I could also use this feature and here's why:

We have a setup where the website Logo and Navigation are stacked on desktop. However, on mobile the navigation turns into a hamburger menu, and we no longer wish it to remain below the logo, but beside it on the same "row". 

At first, it would seem obvious to start with a 2-column layout, and on desktop set each width to 100% in order to stack them. Then on tablet and mobile, change the widths to the desired size next to each other. 

That's our use case right now, and in order to get this scenario to work, we have to either write custom CSS or show/hide separate elements based on screen size.

**Comment by mjohnson-ionline** [comment]
Probably dont have to write custom cas. Can just use the hide show functions in elementor but yea it's still a hack
________________________________

**Comment by bigwilliam** [comment]
@mjohnson-ionline We did consider that as well - which I mentioned at the end of my comment. It does work. Elementor does it right - where you always see the hidden content while editing the page - that way content is not missed. Other page builders I've used don't do this, and sometimes you go in and update content and forget to check mobile, where a "hidden" element shows up still if you don't specifically check. 

But if we could have stacked columns on desktop, that would be nice also - and I prefer that over duplicating content and showing/hiding it.

**Comment by pensierinmusica** [comment]
@kobizz @KingYes @matipojo @arielk any update on this?

https://github.com/elementor/elementor/issues/5072#issuecomment-420955303

**Comment by kowsar89** [comment]
I need this feature too!

**Comment by black-eye** [comment]
+1

**Comment by deniskern** [comment]
+1

**Comment by kreasIT** [comment]
+1

**Comment by KeviinCosmos** [comment]
So simple update .. come on :)

**Comment by KeviinCosmos** [comment]
So far you can maybe use this:
https://stackoverflow.com/questions/47800803/css-flexbox-float-elements

**Comment by JamesJosephFinn** [comment]
+💯^💯! Please make this happen.

**Comment by Bugreal** [comment]
I found a great video that explains the issue and how to deal with it https://www.youtube.com/watch?v=jUodbTSfBCk @mjohnson-ionline It is a bit lengthy but it is worth it

**Comment by elbotho** [comment]
Still demand for this in 2020.

**Comment by r0b1n1sl4m** [comment]
The surprising fact about element is you guys never implements what your customer needs. The same thing you did for nested inner section. Come one now, it's not gonna take you years to implement 100% column width on desktop.

**Comment by swinggraphics** [comment]
This is still badly needed. Was really hoping 3.0 would fix this issue. :(

**Comment by leonfilser** [comment]
Why is this closed? The issue still exists

**Comment by moealmaw** [comment]
Any update on this?

**Comment by black-eye** [comment]
Basically the same feature request is open here: https://github.com/elementor/elementor/issues/2218
Please add your comment there, to let the developers know your demand.

**Comment by mjohnson-ionline** [comment]
This has been kicking around for years!

Kind Regards,
Matthew Johnson

Phone: 1800 466 546
Website: www.ionline.com.au<http://www.ionline.com.au>
Email: matthew@ionline.com.au<mailto:matthew@ionline.com.au>


[cid:new-2019v3(003)_c7a3c7c1-5fd7-4393-a2fa-1e8f6b81cc9a.png]

**Comment by ijjimem** [comment]
C'mon, its not hard

**Comment by kippoulet** [comment]
+1

**Comment by biocas** [comment]
+1

**Comment by ofmarconi** [comment]
No news on this?

Really Elementor?

**Comment by Eetheart** [comment]
Yeah, seriously, this is a most basic mundane function that should be implemented. I cannot believe we pay $$ for the Pro version and it is not even possible to do 100% width columns *before* the tablet breakpoint.

**Comment by MoltenMango** [comment]
Hello? Elementor? Come on. I'm with @ofmarconi, this is downright silly that we don't have this after 3 years.

**Comment by Reichbaum** [comment]
I have encountered this too. It's a strange decision that it can't be done.

**Comment by bluefuze** [comment]
I really need to echo the previous requests here. I would really like to be able to set a column width to 100% on desktop. Such an obvious thing that would be really helpful.

**Comment by ofmarconi** [comment]
> Eu realmente preciso ecoar os pedidos anteriores aqui. Eu realmente gostaria de poder definir uma largura de coluna para 100% na área de trabalho. Uma coisa tão óbvia que seria realmente útil.

see: https://elementor.com/help/container-element/
