### ISSUE TITLE
Website Banner Popup that tells customers to opt in and out of cookies for new Privacy Laws

### ISSUE THREAD

**Issue by themoodmachine** [pojome/elementor#5073]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Protect our customers from cookie New Privacy Laws, so they can opt in and out.

**Describe the solution you'd like**
A popup we can add to the front page of our site to tell customers to opt in or out to cookies.

Here's an example of a site that has it at the bottom:
https://bit.ly/2NkSQDM

**Describe alternatives you've considered**
Not sure there are any others.

**Additional context**
N/A

**Comment by bainternet** [comment]
@themoodmachine 

Thanks for the suggestion, we are already working on implementing something like that.

I merged this issue with  #628, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
