### ISSUE TITLE
Custom Countdown Counter

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#5074]
Hello guys,

A suggestion for the Elementor's countdown timer.
You guys could be able to set the start of the countdown timer and the possibility of repeating based on day and time.
For example:
Let's say I publicize a course and that registration is open every Monday and runs through Wednesday. So I wanted to put a countdown timer that starts counting on Monday and ends on Wednesday, then next Monday the contact starts counting again and goes through Wednesday and so on ... without that I have to keep programming manually.

Another thing ... this countdown timer activation could be activated individually by user as well.
In that case, if I want the countdown timer to be activated all Monday, but the count is 10 days, then the countdown will end on Wednesday of the other week. However, on Monday of the other week the countdown timer must already be enabled for other users who have entered my mailing list this week.

If the countdown timer is not individual, then these new users who receive the sign-up email open the other Monday and will appear 3 days remaining to end the countdown. Therefore, for these new users, the countdown timer must be enabled separately from the countdown timer that was enabled for previous users.

Monday - activate the 1st countdown timer (10 days)
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
Monday - activate the 2nd countdown timer (10 days)
Tuesday
Wednesday - end of the 1st countdown timer

A third suggestion ... at the end of the countdown, instead of just getting 00:00:00, it could automatically redirect to a new page. Then, as soon as the countdown ended, a redirector code would be activated. End the link from the other page could be customized.

And a fourth suggestion ... this countdown timer could generate a code where I could put it in the texts of my emails. So the user upon opening the email, he would see a countdown timer and on going to the page, he would also see the countdown timer (both with timed counting)

Guys, it's 4 suggestions that look a bit complicated, but I'm just leaving it here for you guys to consider it or not in a future update.

Appreciate.
Rodrigo Carlos

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
