### ISSUE TITLE
Background of search form not correct on woocommerce pages

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#5075]
The background of the search form is correct on woocommerce pages. 
See the search form in the topbar in the attached screenshots.
e:  2.1.2
![schermafdruk van 2018-07-15 22-47-51](https://user-images.githubusercontent.com/2702064/42738282-959fc85e-8881-11e8-88b2-133c3fa2e06d.png)
![schermafdruk van 2018-07-15 22-47-41](https://user-images.githubusercontent.com/2702064/42738283-95d4a600-8881-11e8-9bac-53f36a2425db.png)

ep: 2.0.15

**Comment by arielk** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by bainternet** [comment]
@knireis 

Sorry, but we can't help you like this,
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me.
