### ISSUE TITLE
Not Loading on custom post type

### ISSUE THREAD

**Issue by varomix** [pojome/elementor#5076]
Hello
I run a training courses site and the LMS system uses Buddypress, whenever I edit my custom post type with elementor, I see Elementor working as is should, when I see the post live it just doesn't load elementor, I look at the source and there's no Elementor JS files loaded, I searched and found a few issues that relate to Buddypress.

I'm using Buddypress 3.1 and latest Elementor Pro

seems like is just NOT Loading the the JS and CSS files
is there a way I can force it to load them?

thank you

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by varomix** [comment]
They sent me here hahaha

> 

Shawon replied | Jul 14, 6:54
-- | --
Hi Alvaro,Thank you for your reply.I am afraid, through this channel we provide support to existing Elementor features only.To get code related help,You can post this on our GitHub project and our developers will look into this.Best Regards,--Shawon from Elementor

**Comment by varomix** [comment]
somebody needs to do something right? I paid for support so, where is that?
