### ISSUE TITLE
 link to a post digest Also

### ISSUE THREAD

**Issue by networking-web** [pojome/elementor#5078]
Hello Today In all the advanced sites when the posts are displayed in the blog or as recent posts there is a possibility to click on the summary and it is forwarded to the full post.
This greatly improves the user experience, especially in mobile.
How do I add this option to the "Recent posts" widget?
Thank you very much!!!
שלום היום בכל האתרים המתקדמים כשמוצגים הפוסטים בבלוג או כפוסטים אחרונים יש אפשרות לחיצה על התקציר וזה מועבר לפוסט המלא. 
זה משפר מאוד את חווית המשתמש ובמיוחד במובייל.
כיצד אוכל להוסיף אפשרות זאת לוידג'ט "פוסטים אחרונים" ?
Thank you very much!!!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
