### ISSUE TITLE
Cannot Open Elementor Editor

### ISSUE THREAD

**Issue by ricardocici** [pojome/elementor#5084]
Hello, 

I cannot open my Elementor Editor, I keep getting this console error:

![image](https://user-images.githubusercontent.com/13444028/42761106-f4566fe0-88e2-11e8-96c9-8cd792992437.png)

I'm using the lastest version of Elementor (2.1.3) with OceanWP Theme.

Can you help me?

Best,
Ricardo

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
