### ISSUE TITLE
Post Cards appear differently on Chrome and Safari

### ISSUE THREAD

**Issue by DigitalVeer** [pojome/elementor#5087]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The post-cards on the post-display widget showcase themselves in different sizes on Chrome and Safari. On Chrome, as intended, all the cards are the same height. However, in Safari, they all adjust their heights based on the amount of text in the cards.

[Chrome](https://gyazo.com/f32bb34b4f84273b123ea804944031df)
[Safari](https://gyazo.com/a89607f83d0da87d58367dbd9945eecf)

The universal behavior we would like to achieve is the one displayed on Chrome - where all the post-cards are the same height.

## Steps to reproduce

This occurs every-time with the post-widget in Safari and Chrome.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@DigitalVeer 

thanks for reporting, should be fixed in next version.
