### ISSUE TITLE
Compatibility with The Events Calendar from Modern Tribe

### ISSUE THREAD

**Issue by cbernhard22** [pojome/elementor#5088]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor **( Elementor Pro. )**

**What problem is your feature request going to solve? Please describe.**
Currently, Elementor Pro does not work with The Events Calendar plugin from Modern Tribe. (Free version of Elementor works though)

**Describe the solution you'd like**
I would like to be able to activate Elementor Pro and still be able to view my events. 

**Describe alternatives you've considered**
I am considering another Events Calendar but this would cost us more. So fixing Elementor Pro would be a better solution.

**Additional context**

**Comment by mylimoproject** [comment]
+1

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by alfasino9** [comment]
I have the same problem as @cbernhard22 .



## Prerequisites


- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor. ( Elementor Pro. )


## Description



Currently, Elementor Pro does not work with The Events Calendar plugin from Modern Tribe. (Free version of Elementor works though)

## Steps to reproduce



Only install the "The Events Calendar" free version in a WP site with Elementor PRO. Then go to your events page ( /events ).

Then, you will see a message "We didn't find anything, please search again.".

If you deactivate the PRO plugin, and refresh the events page, now it works correctly,

## Isolating the problem

- [x] This bug happens with **only Elementor PRO** plugin active
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 5.6.41
	PHP Version: 7.1.22
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://XXX
	Home URL: http://XXX
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: es-ES
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.5.27
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.9
		Author: Elementor.com

	Ocean Demo Import
		Version: 1.0.9
		Author: OceanWP

	Ocean Extra
		Version: 1.4.28
		Author: OceanWP

	The Events Calendar
		Version: 4.6.23
		Author: Modern Tribe, Inc.

	WP File Manager
		Version: 3.1
		Author: mndpsingh287

	WPML Multilingual CMS
		Version: 4.0.7
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.6.7
		Author: OnTheGoSystems


== Debug ==
	Errors: 
		TypeError: setting getter-only property "type"
			at http://XXX/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.3 - 2:86630
			2018-09-18 16:32 +00:00
			x 5 times

		TypeError: Cannot read property 'errors' of undefined
			at http://XXX/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:173847
			2018-09-06 16:52 +00:00
			x 10 times

		TypeError: Cannot read property 'query' of null
			at http://XXX/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1 - 1:60824
			2018-09-06 15:50 +00:00

				
```
</details>

**Comment by apollollc** [comment]
no solution?

**Comment by mrwconnected** [comment]
Any solution yet?

**Comment by nichweb** [comment]
I am searching for the solution to this issue as well. Anyone have answers? Thanks in advance.

**Comment by dcambria** [comment]
+1
