### ISSUE TITLE
MyFonts compatibility

### ISSUE THREAD

**Issue by SLS2018** [pojome/elementor#5089]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
MyFonts is a service similar to Adobe Typekit. Could you integrate MyFonts as you did with Typekit? Right now, within Elementor I cannot directly call the fonts loaded with MyFonts. Instead, I need to override the font-family by using custom CSS.

**Describe the solution you'd like**
Similar integration as with TypeKit.

**Describe alternatives you've considered**
Currently I am using custom CSS to override Elementor's fonts with MyFonts. #

**Comment by bainternet** [comment]
@SLS2018 

You have two options:

1) Upload the fonts using Elementor's Pro custom font feature: https://docs.elementor.com/article/276-custom-fonts

2) Simply tell elementor to add your font family to the Typography font family control:

```PHP
/**
 * Add Font Group
 */
add_filter( 'elementor/fonts/groups', function( $font_groups ) {
	$font_groups['my_fonts'] = __( 'MyFonts' );
	return $font_groups;
} );
/**
 * Add Group Fonts
 */
add_filter( 'elementor/fonts/additional_fonts', function( $additional_fonts ) {
	// Key/value
	//Font name/font group
	$additional_fonts['MyFont Font Family Name'] = 'my_fonts';
	$additional_fonts['MyFont Font Family Name2'] = 'my_fonts';
	return $additional_fonts;
} );
```

Now if they are included by your theme or 3rd party plugin, you are done.
if not you can hook in to the elementor/fonts/print_font_links/{$font_type} action hook to enquque your fonts, ex:

```PHP
add_action( 'elementor/fonts/print_font_links/my_fonts', function( $font_name ) {
  // Enqueue your font
} );
```
