### ISSUE TITLE
evaluate/help/reuse grapesjs

### ISSUE THREAD

**Issue by pierreozoux** [pojome/elementor#509]
We need to let user be able to create nice website/pages, without technical knowledge. A lot of project are reinventing the wheel, and I really think we should mutualize effort around a nice library and reuse that library.

Please see this issue:
https://github.com/artf/grapesjs/issues/20

**Comment by joshmarom** [comment]
Thank you @pierreozoux .
Grapesjs does indeed look like a promising and inspiring project. The developers managed to tackle many of the challenges page builders need to face, and they have done so in a very elegant way.

Having said that, I would like to point out some of the differences in the focus of our project.

- While Grapes focuses on giving the user maximum control over the elements in the document, to the smallest details, Elementor is much more "Widget oriented" - we want to offer purpose-driven  components and not necessarily to provide the ultimate html/css live studio.  

- Elementor's development team is now focusing on the development of a whole set of widgets and features that will be included in our Pro version. these are mostly **WordPress** related features.

Unfortunately, given these points, and considering our limited development resources, we currently cannot shift our efforts towards active contribution to the Grapes project.

We do however, appreciate your invitation and we wish you best of luck. Maybe at a later point down the road, we will be able to contribute.

**Comment by pierreozoux** [comment]
Thanks for your kind answer.

I do agree with you on the "purpose-driven components".

This issue is more like a "Hey page builder people, it would be nice if you collaborate :)"

Text editor is already done, look at http://quilljs.com/ for instance.
What about "html editor" :)

Do you think you would be able to componentize your elementor? Then if I want to reuse it to build static site I could easily. And then, you can build on top for wordpress specific?

I know collaboration is more expensive on short term. But it is amazing on the long term :)

Let me know if/where I can help (I'm not much developer, more devops guy :) ).
And please close / rename the issue as you feel!

Best!
