### ISSUE TITLE
Exclude from search breaks posts & portfolio blocks

### ISSUE THREAD

**Issue by mrben522** [pojome/elementor#5091]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
Manual selection in Posts and Portfolio widget breaks if post type added has `exclude_from_search` set to `true`

## Steps to reproduce

1. create custom post type
2. set `exclude_from_search` to `true`
3. create new elementor page
4. add posts or Portfolio widget
5. change query source to "Manual Selection"
6. search for title of post from search excluded post type
7. add said post to widget

Post shows up as an option to add to block but then will not show in block and will not stay in selection on save and reload

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.1
	MySQL version: 5.6.37
	PHP Version: 7.1.7
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: http://elementor-bug-test.local
	Home URL: http://elementor-bug-test.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.42 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.0.16
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.10
		Author: Elementor.com

== Debug ==
	Errors: There are no errors to display
				
</details>

**Comment by bainternet** [comment]
fixed, thanks.

**Comment by pinguluk** [comment]
I still have this issue with the last version
