### ISSUE TITLE
Feature Request: Sales Funnel Capabilities 

### ISSUE THREAD

**Issue by zrk4444** [pojome/elementor#5093]
Please add order bumps and the ability to use elementor to create order forms for custom Woocommerce checkouts. 

Or, just make it so that Elementor can create order bumps, order forms, (like the 2 step order form or shopify checkout) have one-click upsell ability and integrates with payment processors like Stripe, Paypal, Authorize.net , NMI etc. Also, add integrations with companies like Shipstation and Amazon FBA if you decide to not make a custom Woocommerce checkout solution.

Thanks.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by carpas** [comment]
I'd love to have that feature. That'd beat Clickfunnels as a funnel builder. I'd reckon thought Elementor + Custom Forms 7 would do great part of this.

**Comment by unclerom** [comment]
I would love to see payments added to the forms! Also maybe the ability to cookie users on submit and block content based on those cookies/sessions This would talk elementor into the sales funnel game. And would be amazing...
