### ISSUE TITLE
Share Buttons - Column and Row gaps setting not working

### ISSUE THREAD

**Issue by JoeDarko** [pojome/elementor#5094]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Share Buttons widget 

When you set "Number of columns" to anything other than "Auto", the Column and Row gaps setting stops working. Started happening after update. 

**New version of Elementor is generating this CSS for gaps:**

grid-column-gap: 30px; 

(Not working)

**Older version of Elementor is generating this CSS for gaps:**

margin-right: calc(15px / 2);
margin-left: calc(15px / 2);

(Working)

**Comment by arielk** [comment]
This is something that has been fixed in the latest versions of Pro.
What is your Elementor + Elementor Pro version?

**Comment by bainternet** [comment]
@JoeDarko 

We moved from using margin to grid-CSS,
Can you please test the latest Elementor Pro Beta #4923

**Comment by acornavi** [comment]
This problem is still persistent after five years.
