### ISSUE TITLE
Region's controller constantly disappears 

### ISSUE THREAD

**Issue by bendqh** [pojome/elementor#5095]
Win 10 home build 17134.165 with Chrome 67.0.3396.99 (Official Build) (64-bit) with WP 4.9.7 and Elemnetor 2.12.

Time and again I'm having the following region-controller disappearing. It doesn't happen in all regions, it happens basically only in the uppermost regions on a page.

I navigate to it with the mouse and it disappears. I found no way to make it stay there.

![1](https://user-images.githubusercontent.com/31392185/42795714-758a55ee-898e-11e8-94e9-9510c7a091a7.PNG)

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by bendqh** [comment]
@bainternet I had a bad feeling about your advice, but I still did that and got a very unprofessional, angrying reply from some guy which I wonder if I should mention his name. Me going through this isn't fit for you, for Ariel, or Ben. This is NOT your standards of quality in Pojo. You are welcome to read the email, having basically identical text to the message here, and you'll understand.
