### ISSUE TITLE
Unable to change the typography and text color of submission notice text of Form module

### ISSUE THREAD

**Issue by hzesen1221** [pojome/elementor#5097]
Hi, I am using the form module on a black background section and I noticed that after submitting the form the submission success message is invisible because its color is also black by default, and there is no way to change it.

I noticed this problem by importing an official CTA section which has a form on a black section.

Could you please check?

**Comment by bainternet** [comment]
This feature is currently in beta of Elementor Pro 2.1 #4923 

I merged this issue with  #1180, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
