### ISSUE TITLE
Elementor Menu Widget - Center the dropdown container & add a top center pointer & info in columns

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#5098]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Adding esthetic improvement and functionality to Elementor Menu Widgets.

**Describe the solution you'd like**
Center the dropdown container & have a top center pointer & info in columns

Here is a great example of a nice looking dropdown with a top center pointer and info in columns reflecting our feature request from this business we found:

https://www.useloom.com/share/04b594cc3df04a54b46a15cf97179bf1

**Describe alternatives you've considered**
Anything else would be an improvement

**Additional context**
N/A

**Comment by bainternet** [comment]
I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
