### ISSUE TITLE
Changing img src, text color and background color on scroll with sticky headers

### ISSUE THREAD

**Issue by johnkakuk** [pojome/elementor#5103]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm having issues in applying JavaScript to change the img src of a logo image I've applied in my website's header; the end goal is a sticky header that starts transparent. On scroll, the background would become white, the white logo would be switched with a black logo, and the color of the menu text and search icon would switch from white to black as well.

**Describe the solution you'd like**
Native support for this feature built into the sticky header widget would be hugely useful.

**Describe alternatives you've considered**
I've considered switching to a theme that natively supports this function (as my client is pretty set on his desire for it), but it throws a hell of a monkey wrench into the rest of the site. I've also tried to write a little JavaScript that would accomplish this, but I'm not sure where to put the code.

**Additional context**
An example of what I have in mind can be seen here:
https://wpastra.com/ready-websites/?website=author-04

**Comment by bainternet** [comment]
@johnkakuk 

With Elementor Pro 2.1 new sticky library you can do all that simple CSS, because the container changes class names. 

#4923

**Comment by thkishor** [comment]
I am able to change the color of the **menu item** from Black to white and change the background color when sticky  effect applied but i am still struggling in Changing the logo . 

And here my Tutorials too on How to do it[https://foxscribbler.com/sticky-transparent-header-elementor/](url)
