### ISSUE TITLE
CarbonFields Integration

### ISSUE THREAD

**Issue by gschoppe** [pojome/elementor#5105]
Can we get an integration for [CarbonFields](https://carbonfields.net/), like the integration provided for ACF, PODs, and Types Toolset?

**Comment by bainternet** [comment]
As far as I know, CrabonFields use the WordPress native Custom Fields so they should work out of the box.

As for adding a full integration, not sure if we will at this point but if the developers of CarbonFields are interested we would be more than happy to help them develop the integration.

thanks.
