### ISSUE TITLE
Forms - Option

### ISSUE THREAD

**Issue by networking-web** [pojome/elementor#5107]
Forms - Option You can select the first option in the list.
Which is usually a title or instruction on how to choose or "Select"
In Pogo forms you can mark "Do not allow the first option to be selected".
I would appreciate your prompt attention
![elementor](https://user-images.githubusercontent.com/39119112/42839437-68106b28-8a0c-11e8-9f27-7fec7144a53c.JPG)
Thank you
on pojo form
![pojo](https://user-images.githubusercontent.com/39119112/42839546-bc889eaa-8a0c-11e8-88ae-990b1eff37c4.JPG)

This is really a bug and can not be used that way

**Comment by bainternet** [comment]
@networking-web 

It's already available in the Elementor Pro 2.1 beta #4923 

thanks.

**Comment by networking-web** [comment]
*Thank you very much*, waiting.
I installed the beta version and still have not seen this possibility.

Adds a picture where you can see that the first option has been
selected and the form has been sent



2018-07-18 10:32 GMT+03:00 Raz Ohad <notifications@github.com>:

**Comment by bainternet** [comment]
@networking-web 

If you have the latest beta of Elementor pro 2.1 you should see a long description under the options control in the panel that says you can set label and values split by a pipe char "|". so make the field required and leave the first option empty after the pipe:

![r07wyhb](https://user-images.githubusercontent.com/660572/42937775-b53bc95e-8b58-11e8-900b-6475e9cdb8e0.png)
