### ISSUE TITLE
Converting a non-nested column into a nested one - undoing deletes content within.

### ISSUE THREAD

**Issue by goluclear** [pojome/elementor#5108]
For example, I dragged a nested column into a different nested one to create an additional nested column.  Undoing this using Cmd+Z or using the history tab will move the column back, but any content within is permanently deleted (unless you use revision history).  Using latest version of Firefox on macOS 10.13.4

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
