### ISSUE TITLE
Smart Forms

### ISSUE THREAD

**Issue by IamSiddharth** [pojome/elementor#5109]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This Feature will add more capability to Forms

**Describe the solution you'd like**
Ability of Calculate value between field & Ability of smart conditions 
- UPDATE / CALCULATE FIELD
- SHOW / HIDE FIELD
- CONDITIONAL LOGIC

**Describe alternatives you've considered**
http://jotform.com

**Comment by bainternet** [comment]
Duplicate of #2638

**Comment by IamSiddharth** [comment]
Calculate value between field 
*UPDATE / CALCULATE FIELD

Is not in #2638
