### ISSUE TITLE
Version 2.1.0-RC1 - Template for Custom Post Type Created with Toolset - Post Body not an option

### ISSUE THREAD

**Issue by dmccan** [pojome/elementor#5111]
I created a simple custom post type with latest Toolset, "Books". I then went into Elementor Pro to create a single template for Books.  In the text widget list of dynamic fields, the Post Body does not show as an option.  It was also missing when creating the archive. 

Trying the Post Content widget did not render any content when previewed. 

![e-pro-toolset](https://user-images.githubusercontent.com/2622805/42850417-20ab83a4-89ed-11e8-9dbd-b76f5208a229.png)

**Comment by bainternet** [comment]
@dmccan 

"Post Body" can't be an option in a dynamic tag, that is why when you edit a single template you have a **Post Content** widget. And if it dosn't render any content, it means that you need to correct your "Preview As" settings and/or missing content for that Post type.
Here is a guide:
https://docs.elementor.com/article/354-creating-a-single-post-template-with-elementor-pro

thanks.
