### ISSUE TITLE
Version 2.1.0-RC1 - Latest Toolset - Not all Toolset field types are available to insert

### ISSUE THREAD

**Issue by dmccan** [pojome/elementor#5112]
When selecting custom on the text module, only Toolset custom field types of text and dates are options to select.  For example, in my custom post type I added a URL type field and it was not an option to select. Will you be supporting these?

**Comment by bainternet** [comment]
All Dynamic tags support the correct field type per a category, in Toolset, any Dynamic control expecting a string/text supoprt these toolset field types:

- textfield
- phone
- textarea
- checkbox
- select
- numeric
- email
- embed
- google_address
- wysiwyg
- radio

And any Dynamic control expacting a URL supports these  toolset field types:

- email
- image
- file
- audio
- url

So to answer your question, A URL field type is already supported but in url controls ( as it should ).

Thanks.
