### ISSUE TITLE
Version 2.1.0-RC1 - Empty tab style for "Posts" pro widget

### ISSUE THREAD

**Issue by herewithme** [pojome/elementor#5115]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Tab style for "Posts" pro widget is empty.

## Steps to reproduce

- Activate 2 plugins (Elementor + Elementor Pro)
- Add a pro "posts" widget on a new page
- Try to display tab "Style"
https://snag.gy/KcBl47.jpg

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```		
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: 5.7.22
	PHP Version: 7.1.17
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: https://devlocal.lndo.site
	Home URL: https://devlocal.lndo.site
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Permalink Structure: /blog/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.0-RC1
		Author: Elementor.com

== Debug ==
	Errors: There are no errors to display			
```
</details>

**Comment by bainternet** [comment]
@herewithme 

We can't replicate this issue,
Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by herewithme** [comment]
OK, i will try with the support.
