### ISSUE TITLE
Use WooCommerce category images as dynamic backgrounds/images

### ISSUE THREAD

**Issue by markusreklambyra** [pojome/elementor#5117]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I've given my WooCommerce product categories their own thumbnails/featured images with the built in WC function. I would love too use these images as dynamic backgrounds/images in my Elementor Product Archive templates. Right now I just can choose product images and not product category images. Thanks in advance!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arielk** [comment]
This feature has been added to E-Pro v2.1.6, please update.

Thanks for your feedback!
