### ISSUE TITLE
Post Content widget not working for custom post type in Version 2.1.0-RC1

### ISSUE THREAD

**Issue by dmccan** [pojome/elementor#5121]
The post content widget doesn't seem to be working. Here is a short video trying it for a single template:

https://cl.ly/431G3k2z2N0U

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

From the video, we can't tell your environment settings or Isolate the problem.
