### ISSUE TITLE
Elemetor crushes in Edit

### ISSUE THREAD

**Issue by HenkDz** [pojome/elementor#5126]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
Try to edit an elementor page. I get the message "The preview could not be loaded". I tried all the suggested solution on the site. This only Occurs on new Versions of Elementor it used to work well.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
WordPress 4.9.7.
Elementor v2.1.4
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@HenkDz 

We really can't help with this little data.
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and this issue number.

thanks.

**Comment by HenkDz** [comment]
I have sent a message and tried my best to explain the issue further.
