### ISSUE TITLE
elementor issue with mobile version

### ISSUE THREAD

**Issue by itagren** [pojome/elementor#513]
שלום לכם... קודם כל רציתי לומר שהאלמנטור מדהים ולמרות שאין לי שום ידע בבניית אתרים הצלחתי לבנות אתר לבד. תודה.  יש לי בעיה בגרסת מובייל - כשאני עם הלפטופ האתר עולה מעולה אבל במובייל מופיע לי מסך שחור ורק כשאני "מושך" שמאלה את המסך עם הטאצ' מופיע האתר . אני עובד עם התבנית שלכם twentysixteen Child Theme והאתר הוא בעברית. יש פתרון?﻿

**Comment by arielk** [comment]
היי שלח לנו את הקישור לאתר במייל אל support@elementor.com ונעזור לך
