### ISSUE TITLE
Translucent Header + Hyperlink/page redirect on widgets (Elementor Pro)

### ISSUE THREAD

**Issue by Innogrid** [pojome/elementor#5131]
Hi,

I would like to see an option to make the headers translucent. 
Also, I would like to see the feature to click on a widget to redirect me to a different page or website!
For example; The 'counter' widget, it would be nice you could click the widget when it's done counting to go to a different page where more information is shown. (If there is a way to do this already I would like to hear)

I love Elementor already! But the small things make it perfect. 

Regards,

Bob

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

- Translucent headers currently can be done via Custom CSS only.
- Click to redirect is possible with every widget that has a link/url control other than that we risk breaking the page structure (anchor inside an anchor) or generating invalid HTML.

thanks again.
