### ISSUE TITLE
Sticky header for 2 sections?

### ISSUE THREAD

**Issue by falken83** [pojome/elementor#5133]
Hi,
I can add 2 section as sticky header (so that for example I have a banner with logo and address on top and below of that the horizontal navigation).
But when I do this and scroll down the navigation goes over the header also to the top of the page.

I guess it would make sense that the lower sticky navigation only goes up until the first sticky part?.
Am I doing something wrong or is it nothing that can be done?
Thanks!

**Comment by lucafagherazzi** [comment]
+1

**Comment by kelvinlamyou** [comment]
+1

**Comment by sco2tbold** [comment]
+1

**Comment by pingram3541** [comment]
The only way I've been able to successfully do this is with nesting.  If you can't get the perfect design with 2 levels, you might have to use the template widget:

section (sticky top)
    -- inner section (columns)
    --    --template widget (which may have 1 + 1 nested section)
    -- inner section (columns)
    --    --template widget (which may have 1 + 1 nested section)

**Comment by arielk** [comment]
Sorry, but for now this is not possible, maybe in the future we'll add this feature.

Thanks for your feedback!

**Comment by Sataptech** [comment]
Generally, more control with the header is a must-have, without having to write CSS or using third-party-  plugins.

- Set sticky position
- Shrink header
- Shrink logo
- Change header color
- Change logo color
- Blur background
- Apply sticky and effects to multiple sections.

**Comment by mucheroni** [comment]
@arielk  +1 still having problems also with sticky menu when i have 1 section above.
when we have a section above the menu for example with the Telephone, and i want to sticky the section below with the menu... everything break
