### ISSUE TITLE
Creativity Increaser by page changing

### ISSUE THREAD

**Issue by CoronaDesignGroup** [pojome/elementor#5134]
One of my all time biggest bitches about Wordpress is the manner in which you move from page to page when you are doing page editing. It can be a real damper on the creative process to have to click - wait - click - wait - click - wait your way to the next page – really an interruption to your thought process. Multiply that by a slow server and an old brain (I’m 57) and it can be quite a true impediment to one’s creativity. 

How about including a pull-down right from the Elementor editing page that allows a selection of the next page (or Elementor template or popbox, etc) which you want to edit next. One click and you’re there. Maybe Wordpress could get a hint as well on this.  

After I hit the update button on Elementor, it takes me 4 clicks to get to the next page – one click would really be much better.  You already have something similar in the top bar of the frontend with “Edit with Elementor” pulldown. Just increase it's scope to also include pages and duplicate on the editing page. Done deal, big help.

![edt with elementor pulldown](https://user-images.githubusercontent.com/40642349/42952479-666d4076-8b2d-11e8-8393-b0fac5d49df7.JPG)

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/pojome/elementor/issues/292 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
