### ISSUE TITLE
FEATURE REQUEST:  Fix one bullshit feature!

### ISSUE THREAD

**Issue by gravnetic** [pojome/elementor#5136]
I have to say that your team is doing great work and the title of this feature request is to get as much attention as possible in hope that you really make it happen.

**FEATURE:  Agency accounts get wildcard licensing, never see the 'update your license' dialog again, BOOM!**

If I have an Agency account please wildcard my license for all sites.  I am really tired of updating my license every time I migrate, and I know you have the URL change...but you can do even better with barely any development work.  In fact, depending on if you are using EDD or not this is an administrative request. 

Agency members pay a premium so give us this one premium feature...quit worrying about your license.  Pay your bill and enjoy!

**Comment by arielk** [comment]
What is mean *wildcard licensing*?

**Comment by gravnetic** [comment]
Not assigned to a URL.  Since the subscription level of the plugin at this point is unlimited why are you checking the license against a URL.  This causes people to have to deal with entering the URL every time I push up a site, move it to staging, or migrate.  Very annoying to people working on many websites.

**Comment by joshallen73** [comment]
But then people could use your code and you would never know. I had a few sub workers who knew the lic. number...and found they were using it for personal gain without purchasing.

But i do agree it get tiring.

**Comment by gravnetic** [comment]
It's a feature that is sorely needed.  I am not sure what the exact implementation options are for Pojo, but it is a feature I dearly need to see happen and expect some effort to resolve.  I can't clone, push, or migrate a site without having to spend 20 minutes updating all my licenses.  I am asking the same thing of Gravity Forms, Brainstorm Force, and a few other developer keys I own.

**Comment by arielk** [comment]
If there is no license key we will not be able to identify the sites that are running your license. We must get the license key to identify the user and send them version updates and access to the template library.

In any case, we may make a change on this issue in the future, but in the meantime I do not see any other way to deal with it, so I close the issue for this moment.

Thanks for your feedback.

**Comment by gravnetic** [comment]
The assumption that you need to get the license to send them version updates is an inaccurate assumption.  I am assuming our using EED License which can be authenticated with a physical file drop in a plugin for agency licenses.  This is an open issue even if you close it.  It's terribly annoying and there are better solutions when a license verification is not needed.  Which is the case here...

**Comment by arielk** [comment]
If I understand you correctly, you mean that the plugin file will already have the license key, so that the license will no longer have to be manually activated?

**Comment by gravnetic** [comment]
That is just one way to handle this, but sure.
