### ISSUE TITLE
Bug with TOC+ plugin and Elementor PRO

### ISSUE THREAD

**Issue by daniboy92** [pojome/elementor#5141]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

**I checked the other posts with issues like mine and there are not solution for my bug.**

I'm having problems with the plugin TOC+ and Elementor PRO. When i use **Elementor PRO builder** and use the shortcode function ( [view here](http://prntscr.com/k8lvb9) ), I insert the shortcode '[toc]' [view here](http://prntscr.com/k8lw79) and then go to **Preview Mode** [view here](http://prntscr.com/k8lx0x) but nothing is inserted (checked the source code and it doesn't appear at all). However using the Wordpress Builder this shortcode '[toc]' works perfectly [viewhere](http://prntscr.com/k8lz2u) because if i publish and go to preview mode [view here](http://prntscr.com/k8lznk) this works perfectly. The only way to get a working table of contents is using the widget, however it looks so ugly [view here](http://prntscr.com/k8m0fj).

I'm using a Template for all posts.

## Steps to reproduce

1.- Create a post.
2.- Trying to use shortcode [toc] using Elementor PRO builder.
3.- Doesn't work at all

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>Environment</summary>
```

**Server Environment |   |**  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | 5.5.5 |  
PHP Version: | 7.0.30 |  
PHP Max Input Vars: | 8000 |  
PHP Max Post Size: | 100M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected | 
Permalink Structure: | /%postname%/ |  
-- | -- | --

Language: | es-ES |  
Timezone: | 0

**Theme |   |**  
-- | -- | --
Name: | Astra |  
Version: | 1.4.1 |  
Author: | Brainstorm Force |  
Child Theme: | No |

**Active Plugins |   |**  
-- | -- | --
All In One WP Security - 4.3.6 | By Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy |  
Astra Pro - 1.4.0 | By Brainstorm Force |  
Conditional Menus - 1.0.9 | By Themify |  
Custom Fonts - 1.0.4 | By Brainstorm Force |  
Elementor - 2.1.4 | By Elementor.com |  
Elementor Extras - 1.9.11 | By Namogo |  
Elementor Pro - 2.0.16 | By Elementor.com |  
GDPR Cookie Consent - 1.6.2 | By webtoffee |  
Google Analytics for WordPress by MonsterInsights - 7.0.9 | By MonsterInsights |  
Livemesh Addons for Elementor (Premium) - 2.2 | By Livemesh |  
Really Simple SSL - 3.0.3 | By Rogier Lankhorst, Mark Wolters |  
Smush Pro - 2.7.9.2 | By WPMU DEV |  
Table of Contents Plus - 1601 | By Michael Tran |  
Ultimate Addons for Elementor - 1.5.0 | By Brainstorm Force |  
W3 Total Cache - 0.9.7 | By Frederick Townes |  
WPMU DEV Dashboard - 4.5.2 | By WPMU DEV |  
Yoast SEO Premium - 7.6 | By Team Yoast


<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by MiMoHo** [comment]
True. However, an own widget from Elementor for Table of Contents would be much appreciated!

**Comment by daniboy92** [comment]
Come on! help us with this!

**Comment by bainternet** [comment]
@daniboy92 

After a quick look at the plugin's code, It is simply not compatible, The Plugin author would need to add compatibility to Elementor.

If you think about it, The way it works is that the plugin runs after the content has been generated and out of that it creates the TOC, but with a shortcode widget in the editor, when rendered, it has no awareness of the rest of the content.

as For @MimoHo Idea, that would be a great widget, feel free to Open a new [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md)

thanks.
