### ISSUE TITLE
Sticky Needs Better/More Positioning Options

### ISSUE THREAD

**Issue by BrookeRaraAvis** [pojome/elementor#5143]
[ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

It is very frustrating to be unable to create a simple side navigation for a one page tutorial in a blog post. There are currently only options for top and bottom sticky & very limited options for placing the sticky element vertically. Offset can only be set in pixels & does not have any breakpoints:

![need-left-right](https://user-images.githubusercontent.com/1435355/42982826-36c503ac-8bb1-11e8-9004-141d018b6770.png)

**Describe the solution you'd like**

I'd like more options for sticky placement. Please add sticky % percentage % to OFFSET to achieve this look for sticky sidebar navigation. **Offset also needs breakpoints — different setting for mobile, tablet, desktop.** Essentially I'd like a "sticky left middle" SECONDARY navigation for a page (not primary site nav) centered vertically on the page except on mobile. **Offset Top: 50%** should achieve this? Maybe you have a better solution to get this:

![sticky](https://user-images.githubusercontent.com/1435355/42982818-3173f28c-8bb1-11e8-840d-14fb939e350e.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
