### ISSUE TITLE
wp-content/uploads/elementor/css/post-x.css?ver=x

### ISSUE THREAD

**Issue by bendqh** [pojome/elementor#5144]
I don't use FB and didn't find anything on a Google search. I use latest WP, Astra and Elementor and the only problem in GooglePageSpeedInishgts is this:

> Eliminate Render Blocking CSS (ERBC):

```
wp-content/uploads/elementor/css/post-10.css?ver=1532075853
wp-content/uploads/elementor/css/post-14.css?ver=1532075853
wp-content/uploads/elementor/css/post-16.css?ver=1532075853
```

Autoptimize takes care of everything of the same error (ERBC) besides this.

What causes this in Elementor?

**Comment by bainternet** [comment]
I'm not really sure if you are reporting something? Or what you are asking.

**Comment by bendqh** [comment]
@bainternet I'm trying to understand where is it coming from in my site with uncustomized PHP or JS. Given I found no documentation on this GPSI "error", I ask here, so more people with this problem could know where it's coming from in Elementor.

**Comment by teolaz** [comment]
@bendqh there's a function i requested some times ago and the reason you are asking was exactly one of the points of discussion...
you have the possibility to include the single post style directly in wordpress body. You can switch to the internal embedding in settings page:

![image](https://user-images.githubusercontent.com/19909323/43085305-f373f0d0-8e9a-11e8-923d-0a6644e19fa2.png)

then, in mod_pagespeed, you can outline css if you want, even if i wouldn't advise that cause it's good for less requests done to have all inlined: https://www.modpagespeed.com/doc/filter-css-outline

**Comment by bendqh** [comment]
It helped @teolaz , thx.
