### ISSUE TITLE
FEATURE REQUEST: Ability to Edit/Style Custom Post Types

### ISSUE THREAD

**Issue by jameskatt** [pojome/elementor#5145]
I wish Elementor can edit/style all custom post types like Divi Builder can. This would allow me to edit LearnDash pages, for example, without having to use another plugin.

**Comment by smile00000** [comment]
+1

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for the request, Elementor already lets you edit/style custom post types.
