### ISSUE TITLE
Feature request: Shortcut to media library

### ISSUE THREAD

**Issue by MiMoHo** [pojome/elementor#5149]
## Prerequisites

- [x] I have searched for similar feature requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As of now, the only way to access the media library is using a second tab or clicking on an image widget to get there.

**Describe the solution you'd like**
A shortcut to the media library that appears as a pop-up would save me some clicks.

**Comment by bainternet** [comment]
The media Library needs "context" like an Image control or text editor in the panel.
which is where you have the option to open it. Opening it without a context is useless unless I'm missing something?

**Comment by MiMoHo** [comment]
Captions are automatically inserted below an image in a text box, when a description is specified in the media library. When you have inserted a picture and change the caption in the text box afterwards, you may wanna change the image's description as well in the media library to match both. To do this, you currently have to do the steps for inserting a new image. This is an example why there could be a short cut.

**Comment by bainternet** [comment]
@MiMoHo 

Thanks for clarifying, so basically you are asking for a shortcut to open the media library from any image in the preview?

**Comment by bainternet** [comment]
@MiMoHo 

Again opening it without a context is useless it must be connected to an image/placeholder.

**Comment by bainternet** [comment]
@MiMoHo 

Apparently this can already be implemented with the given context menu API, ex:

![image](https://user-images.githubusercontent.com/660572/48004734-7699f280-e11a-11e8-96b8-92e4b2dcd6d1.png)

```JS
elementor.hooks.addFilter( 'elements/widget/contextMenuGroups', function( groups, element ) {
	try {
		if ( 'image' === element.options.model.attributes.widgetType ) {
			
			groups.push(
				{
					name: 'image_actions',
					actions: [
						{
							name: 'set_image',
							title: 'Set Image',
							callback: function() {
								element.model.trigger( 'request:edit' );
								setTimeout( function() {elementor.getPanelView().currentPageView.getControlView('image').openFrame();
								}, 100 );

							}
						}
					]
				}
			);
		}
	} catch (e) {
		console.log( e, element );
		return groups;
	}

	return groups;
} );
```

this adds a right click element to the image widget so when you right click the image you can open the media library from there.
