### ISSUE TITLE
[Feature request] Widget to list posts

### ISSUE THREAD

**Issue by borekb** [pojome/elementor#515]
Say that at the bottom of my page, I'd like to display a list of my 3 most recent blog posts (or podcasts or whatever). It would be good to have a widget for that. (The current WordPress widgets don't support filtering, limiting etc.)

**Comment by WPDevHQ** [comment]
@borekb would something like the following meet your needs? If so I can get a plugin out in a day or so :)

Editor view:
![recentpostsineditor](https://cloud.githubusercontent.com/assets/16872407/18296838/60aa9a72-74a4-11e6-9d23-661b21955a2f.png)

Frontend view
![recentpostfrontend](https://cloud.githubusercontent.com/assets/16872407/18296847/7849bbd6-74a4-11e6-9983-3f77a58d89cb.png)

**Comment by lunacroft** [comment]
I'm waiting for it too #262 
+1

**Comment by borekb** [comment]
@WPDevHQ Very nice! In practice, I'd need some light querying capabilities like telling the widget to pull "latest 5 posts from the podcast category" but this is a great start!

**Comment by hansnolte** [comment]
@WPDevHQ 
This looks very good.
I am looking forward to it.

**Comment by saskiawe** [comment]
That's just thing I was missing: a nice blog/post list with featured image and excerpt. Would be great if you can add this! :)

**Comment by WPDevHQ** [comment]
Just pushed the latest version live. Download: [Elementor Addon Widgets](https://github.com/WPDevHQ/elementor-addon-widgets)

Please note that is currently an addon plugin and a work in progress. Hopefully once the API is out it can be clossely intergrated with Elementor.

@borekb - its a starting base. Hope to add more features to the plugin.
On the TODO list is the option to select posts by category and layout options.

**Comment by joshmarom** [comment]
A Posts widget , as well as a many other new widgets will be included in the upcoming Pro version of Elementor. 

Stay tuned!
