### ISSUE TITLE
Feature request: World country map

### ISSUE THREAD

**Issue by MiMoHo** [pojome/elementor#5150]
## Prerequisites

- [x] I have searched for similar feature requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I can link a certain area into my post by using Snazzy Maps. However, I'd prefer to insert an entire continent or the world by using a widget.

**Describe the solution you'd like**
Wish to color certain territories or countries with a typical RGB color kit.

**Describe alternatives you've considered**
At this stage, the only solution is to use the world country map from Wikipedia and do so manually, then insert the vector graphic into Elementor. However, svg files are not recognized reliably and may not be displayed. Thus, I have to use a rendered png image.

**Comment by bainternet** [comment]
@MiMoHo 

Cna you provide examples as of what you mean.

**Comment by MiMoHo** [comment]
Every map on Wikimedia is an example: https://commons.m.wikimedia.org/wiki/File:Jus_soli_world.svg
If you are not using the template World Country Map from Wikimedia, one can use HTML maps like here: https://drone-traveller.com/drone-regulations-worldwide/

**Comment by bainternet** [comment]
@MiMoHo 

Thanks for clarifying. 

We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

Thanks for the feedback.
