### ISSUE TITLE
Detect Section > Layout > Content Width selector change

### ISSUE THREAD

**Issue by mondrey** [pojome/elementor#5153]
The Section > Layout > Content Width selector adds a class fullwidth/boxed to the preview.

Need to detect selector change for a jQuery function.

Thank you

**Comment by mondrey** [comment]
Right now i'm working on something like this to refresh the window which works

'if ( elementorFrontend.isEditMode() ) {
    elementor.channels.editor.on( 'status:change', function(e) {
        // only if widget is detected
        if ( $scope.find( '.widget-class-name' ).length ) {
            $(window).trigger('resize');
        }
    });
}'

**Comment by mondrey** [comment]
@bainternet 

Thank you for creating this plugin.

I've got an isotope masonry gallery as a widget which needs a 'relayout'  after the  'Content Width' changes from Boxed/Fullwidth or vice-versa.

In non-editor mode , the 'relayout' is done whenever the browser window resizes. In the editor mode it fails to get this since only the 'Div' is changing.

So i was looking to trigger the window resize on selector change from Boxed/Fullwidth to readjust the elements in isotope gallery.

Thanks

**Comment by bainternet** [comment]
@mondrey 

Thanks for claryfing, you can listen to a change event on the editor channel: 

```JS
elementor.channels.editor.on('change',function( view ) {
    var changed = view.elementSettingsModel.changed;
    console.log( changed );
});
```
and "changed" is an object containing the changed controls and thier values.
