### ISSUE TITLE
It is possible to add a mouse icon ? 

### ISSUE THREAD

**Issue by danieljunco** [pojome/elementor#5157]
I'm trying to add a mouse icon but I can't find it. Do you think it will be possible to add this type of icon? Something like this http://freeiconshop.com/icon/mouse-icon-outline/

**Comment by bainternet** [comment]
Currently, this feature (adding custom icons) is not supported, but we will look into it in the future 

I merged this issue with  #110, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

Thanks for the feedback.

**Comment by bentalgad** [comment]
Great plugin that will let you add any custom icons font to elementor core options:
https://wordpress.org/plugins/custom-icons-for-elementor/
