### ISSUE TITLE
Elementor Bug: Creating an Elementor Template with a Shortcode in it completely destroys the style of the shortcode

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#5158]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor Bug: Creating an Elementor Template with a Shortcode in it completely destroys the style of the shortcode

## Steps to reproduce:

See view I made of this reflecting shortcode broken when using template widget in another page:
https://www.useloom.com/share/65d707bc686c476fb7588e94605ed163

And yes, shortcode works when not in a template widget:
https://www.useloom.com/share/7238e5b34b8541e0bcb30e5459c2da81

Steps:
Pt. 1 
Create Template
Add Shortcode widget to a section
Type in shortcode
Hit Safe

Pt. 2 
Create new page
Add section
Add Template Widget
Select the template with the shortcode
You will see it show up properly....

But then...view the page a web browser, the style is completely removed!

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

<details>
<summary>System Info</summary>
## Environment
Lastest Version of Wordpress
Latest Version of Elementor & Elementor Pro
Latest Version of WooCommerce Storefront theme

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: 5.6.32
	PHP Version: 7.1.18-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Storefront
	Version: 2.3.3
	Author: Automattic
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.16
		Author: Elementor.com

	GPL Kit
		Version: 2.0.0
		Author: GPL Kit

	Groups
		Version: 2.3.1
		Author: itthinx

	Groups WooCommerce
		Version: 1.12.2
		Author: itthinx

	If Menu - Visibility control for menu items
		Version: 0.10
		Author: Layered

	MailChimp for WooCommerce
		Version: 2.1.9
		Author: MailChimp

	Responsive Menu Pro
		Version: 3.1.14
		Author: Peter Featherstone

	Safe SVG
		Version: 1.6.1
		Author: Daryll Doyle

	Storefront Powerpack
		Version: 1.4.9
		Author: WooCommerce

	Tidio Chat
		Version: 3.3.0
		Author: Tidio Ltd.

	WooCommerce
		Version: 3.4.3
		Author: Automattic

	WooCommerce Bookings
		Version: 1.11.2
		Author: Automattic

	WooCommerce Frontend Manager
		Version: 4.2.2
		Author: WC Lovers

	WooCommerce Frontend Manager - Analytics
		Version: 1.2.1
		Author: WC Lovers

	WooCommerce Frontend Manager - Groups & Staffs
		Version: 2.1.0
		Author: WC Lovers

	WooCommerce Frontend Manager - Product Hub
		Version: 1.0.1
		Author: WC Lovers

	WooCommerce Frontend Manager - Ultimate
		Version: 4.2.0
		Author: WC Lovers

	WooCommerce Google Analytics Pro
		Version: 1.5.1
		Author: SkyVerge

	WooCommerce Multivendor Membership
		Version: 2.1.0
		Author: WC Lovers

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.1
		Author: WooCommerce

	WooCommerce Product Vendors
		Version: 2.1.6
		Author: WooCommerce

	WooCommerce Services
		Version: 1.15.1
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.8
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 2.3.2
		Author: Prospress Inc.

	WP Job Manager
		Version: 1.31.2
		Author: Automattic

	WP Job Manager - Resume Manager
		Version: 1.16.1
		Author: Automattic

	Yoast SEO: WooCommerce
		Version: 7.8
		Author: Team Yoast

	Yoast SEO Premium
		Version: 7.8.1
		Author: Team Yoast
</details>

**Comment by bainternet** [comment]
@smile00000 

Is it that shortcode specifically or any shortcode? and what is that shortcode?

**Comment by smile00000** [comment]
It happens with all shortcodes.  The widget in the thread above was for the wcfm dashboard https://wordpress.org/plugins/wc-frontend-manager/

Here is an example with the woocommerce checkout shortcode:
https://www.useloom.com/share/17b312a1c7484de891616f97bc1790be

It shows:
Page with shortcode in template widget
VS
Page with shortcode directly on page.

As you can see, the version with shortcode in template widget removes all image styling of credit card images just like it did for our other widget.

**Comment by bainternet** [comment]
Please contact our support at support@elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
