### ISSUE TITLE
There are two problems what are changed soon.

### ISSUE THREAD

**Issue by vns-tvh** [pojome/elementor#5159]
For Image Gallery widget and Progress Bar Widget, look two attached images.
![image gallery widget](https://user-images.githubusercontent.com/41528220/43041355-10340296-8d88-11e8-819d-a222620ba072.jpg)
![progress bar widget](https://user-images.githubusercontent.com/41528220/43041356-106a198a-8d88-11e8-81a7-9bb15023e2d1.jpg)

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
