### ISSUE TITLE
Wrap text around an embedded video in a text box

### ISSUE THREAD

**Issue by MiMoHo** [pojome/elementor#5160]
## Prerequisites

- [x] I have searched for similar feature requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently one can only insert and resize images into text boxes. Adding the code of a YouTube video to embed, results in a full screen image that I cannot resize with the curser to wrap text around it. The predefined height of 315px gets adjusted but the width of 560px is ignored.

**Describe the solution you'd like**
Inserting a YouTube link, optional with the exact time to start at, just as an external image and wrap text around it while being able to resize with the curser proportionally.

**Describe alternatives you've considered**
Creating columns is the only solution right now, however not satisfying as the text paragraph beside the video widget may be shorter in height than the video itself which results in a gap to the next paragraph.

**Comment by bainternet** [comment]
The embedded video is a result of WordPress native [Embeds](https://codex.wordpress.org/Embeds) which we have no control over but you can try the suggested native [Embed Shortcode](https://codex.wordpress.org/Embed_Shortcode) eg:

```
[embed width="123" height="456"]http://www.youtube.com/watch?v=dQw4w9WgXcQ[/embed]
```

thanks.
