### ISSUE TITLE
Left Side Filter bar on the SHOP page. 

### ISSUE THREAD

**Issue by jatinmalik87** [pojome/elementor#5163]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Left Side filter bar on WooCommerce Shop page.

**Describe the solution you'd like**
I came to know that lot of new woocommerce widget are going to be introduced in 2.1 pro version . I wanted to have widget to have 'left side filter bar' on SHOP page. Default or archive woocommerce pages don't  provide left side filter in my theme. Please confirm about same if we can have it in 2.1 release?

**Comment by Webtica** [comment]
+1

**Comment by bainternet** [comment]
@jatinmalik87 

No, we don't have something like that in Elementor Pro 2.1

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

for now, there are already a few 3rd party plugins that do that for you.

Thanks for the feedback.

**Comment by Webtica** [comment]
Sorry to ask. 
Do you have any examples of these 3th party plugins? 

Thanks
