### ISSUE TITLE
Bug: Reduce file paths to minimum length 

### ISSUE THREAD

**Issue by MiMoHo** [pojome/elementor#5167]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache
	MySQL version: 5.6.38
	PHP Version: 7.2.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: http://localhost:8888/pfiffikus.info
	Home URL: http://localhost:8888/pfiffikus.info
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.5.20
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:61.0) Gecko/20100101 Firefox/61.0

== Active Plugins ==
	Advanced Database Cleaner
		Version: 2.0.0
		Author: Younes JFR.

	Amazon Associates Link Builder
		Version: 1.7.0
		Author: Amazon Associates Program

	Anti-spam
		Version: 5.2
		Author: webvitaly

	Conditionally display featured image on singular pages and posts
		Version: 1.3.0
		Author: Cyrill Bolliger

	Contact Form 7
		Version: 5.0.3
		Author: Takayuki Miyoshi

	Dynamic Featured Image
		Version: 3.6.5
		Author: Ankit Pokhrel

	Easy Table of Contents
		Version: 1.7
		Author: Steven A. Zahm

	Elementor
		Version: 2.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.16
		Author: Elementor.com

	External Thumbnail
		Version: 1.2.1
		Author: MrTaiw

	Media Library Folders for WordPress
		Version: 4.2.4
		Author: Max Foundry

	Ocean Demo Import
		Version: 1.0.9
		Author: OceanWP

	Ocean Extra
		Version: 1.4.18
		Author: OceanWP

	Ocean Posts Slider
		Version: 1.0.11
		Author: OceanWP

	Ocean Social Sharing
		Version: 1.0.12
		Author: OceanWP

	UpdraftPlus - Backup/Restore
		Version: 2.14.1.22
		Author: UpdraftPlus.Com, DavidAnderson

	WP File Manager
		Version: 2.8
		Author: mndpsingh287

	Yoast SEO Premium
		Version: 7.8.1
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: e is undefined
			at http://localhost:8888/myserver.info/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.0.13 - 2:26865
			2018-07-17 21:58 +00:00

		TypeError: e.editor is null
			at http://localhost:8888/myserver.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:82859
			2018-07-08 11:45 +00:00

		TypeError: j is undefined
			at http://localhost:8888/myserver.info/wp-admin/js/editor.min.js?ver=4.9.7 - 1:681
			2018-07-08 11:45 +00:00

		TypeError: this._parent is undefined
			at http://localhost:8888/myserver.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:138408
			2018-07-08 10:18 +00:00
			x 56 times

		TypeError: e.editor is null
			at http://localhost:8888/myserver.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:82859
			2018-07-08 10:11 +00:00

		TypeError: j is undefined
			at http://localhost:8888/myserver.info/wp-admin/js/editor.min.js?ver=4.9.7 - 1:681
			2018-07-08 10:11 +00:00

		TypeError: e is undefined
			at http://localhost:8888/myserver.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:212991
			2018-06-21 14:42 +00:00

		TypeError: e.editor is null
			at http://localhost:8888/myserver.info/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82356
			2018-06-19 17:06 +00:00

		TypeError: j is undefined
			at http://localhost:8888/myserver.info/wp-admin/js/editor.min.js?ver=4.9.6 - 1:681
			2018-06-19 17:06 +00:00

```
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
