### ISSUE TITLE
Compatibility with Smart Offers

### ISSUE THREAD

**Issue by dare-devil-arrives** [pojome/elementor#5169]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We would like to make our plugin [Smart Offers](https://www.storeapps.org/product/smart-offers/) compatible with Elementor.

**Describe the solution you'd like**
We would like your help as to what changes are needed to make both plugins work together.

Thanks in advance :)

**Comment by bainternet** [comment]
@dare-devil-arrives 

That sounds great,
here is our API Docs https://deevlopers.elementor.com

and feel free to open a new issue if you have a specific question.

**Comment by dare-devil-arrives** [comment]
@bainternet 

Thank you for getting back.

But looks like the link is broken as it is redirecting me to the 404 page. Can you check?

**Comment by bainternet** [comment]
@dare-devil-arrives 

sorry, typo
https://developers.elementor.com/

**Comment by mansi-shah-2248** [comment]
Hi,

Just wanted to let you know, Smart Offers is now compatible with Elementor. [Read more](https://www.storeapps.org/smart-offers-elementor-integration/).

Thank you for your help.
