### ISSUE TITLE
Focus on the custom css textarea

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#5172]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Custom css doesn't get focus automatically**
When choosing the advanced tab and choosing "custom css". you need to click the custom css textarea to start typing which is really another unnecessary click to add to the workflow because if you choose custom css the only thing you want to do is to write a custom css.

**So please make it auto!**
It's really simple to implement and it will save a lot of time to your wonderful users.

**Comment by bainternet** [comment]
@bentalgad 

Currently, there is only the Custom CSS code editor there but there are 3rd party plugins that add controls to that section and we may want to add some in the future...

thanks for the suggestion.

**Comment by bainternet** [comment]
@bentalgad 

Also, you can click the TAB key and start typing if its the only control you have there.
