### ISSUE TITLE
Margin/Padding more simple

### ISSUE THREAD

**Issue by CaptainJakethe1st** [pojome/elementor#5174]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
NOTE: Intuative margin and padding #5018 -> same "problem" but different solution
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
simplify margin padding, either in that way (Intuative margin and padding #5018) or in my way, see despription...

**Describe the solution you'd like**
See picture
![image](https://user-images.githubusercontent.com/41577927/43077079-a18e6bba-8e86-11e8-9324-4261cb8a9a92.png)

**Describe alternatives you've considered**
Intuative margin and padding #5018

**Comment by bainternet** [comment]
I merged this issue with  #5018, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
