### ISSUE TITLE
Toolset Views Complete Integration

### ISSUE THREAD

**Issue by DrMohamedGamal** [pojome/elementor#5176]
Elementor <3
Is it possible to complete integrate Toolset Views within elementor ?

1- Conditional html output within wysiwigg editor or links ?

2- Conditional display widgets , sections or even content template by adding additional tab in edit panel with
Condtional display for every thing
like device , post id , parent id , category id , user role and full toolset views condtions ?

3- display custom field from parent post - category selected from current postmeta or custom post id entered
<img src="https://i.imgur.com/wd9GA95.jpg">

**Comment by bainternet** [comment]
@DrMohamedGamal 

We are in contact with the guys form Toolset and they are working on a deeper integration with Elementor.

As for conditional display there are already a few requests here and it is something we are thinking about.

thanks
