### ISSUE TITLE
Elementor Pro  2.1 RC1 -  Pods Integration broken 

### ISSUE THREAD

**Issue by quasel** [pojome/elementor#5181]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description
Pods integration doesn't work - you can select a field but it's not output because the configuration is missing the pod name! 

Thank's too @reachadam  ( https://adampreiser.com, https://www.wpcrafter.com ) I got my hand of copy of Elmentor Pro 2.1 RC 1 and we did just a very quick glance on the code from the Pods Team ( thx @sc0ttkclark ) 

To get it working at all it needs the following change:
`$key = $group['name'] . ':' . $field['pod_id'] . ':' . $field['name'];`
in modules.php to Line 36 - change object_name to just name!

Object_name is currently not used and a left over from early 2.0 days - i know the configuration array can be a bit huge until a full pods object is implemented in a planned future release.

A little feedback from the team - loading all pod fields seems like it could not be performant for large sites with big configs, they might consider caching their controls method.

## Steps to reproduce
Just test the integration

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
related #4923 #4129

**Comment by bainternet** [comment]
@quasel @sc0ttkclark @reachadam

Thanks for taking a look at the code, Not sure why you are saying it's broken because its working fine on our end.

Anyway, If using `name`  instead of `object_name` is the correct way to go then consider it done.

This will be patched in the next RC.

Thanks again.

**Comment by quasel** [comment]
hum that's weird can't imagine how it would work on your end as object_name is not populated by pods and hence your configuration misses a part of it - didn't work for me until I made that change! 

Still leaves the issue of caching / performance - @sc0ttkclark offered help and sent an mail - we never heard back from your team after our initial reply an the information that he would be put into contact with a dev! 

I would have summated a PR for the initial issue but without access ;) anyway let's see how it play's out!

**Comment by bainternet** [comment]
@quasel 

Again, thanks a lot.

As for the caching, this currently only effects the editor but it is something we will look into in the future.

**Comment by quasel** [comment]
I'm happy you integrated it, thanks for that!  We are just trying to get our users a good experience! And we have done similar stuff already for the Beaver integration

**Comment by prasanthcpgithub** [comment]
Yes, faced the same issue. Fields are not fetching data. So the output is not visible.

Default WordPress theme is used

**Comment by prasanthcpgithub** [comment]
Just installed fresh copy of Wordpress 4.9.7  default theme with pods and Elementor 2.1 RC2.
and tested. But still the same issue as specified by @quasel.
Data is not fetched .

**Comment by quasel** [comment]
@prasanthcpgithub  not sure that fix was part of RC2 but its part of RC3! and works
