### ISSUE TITLE
Cannot deactivate Elementor pro - w/o license

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#5185]
## Prerequisites

- [YES] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [YES ] The issue still exists against the latest stable version of Elementor PRO.

## Description

Problem:
No option to deactivate Elementor Pro w/o license in WP Multisite

How did I got this:
While configuring WPML, in initial phase, SUDDENLY my Elementor Pro
**lost** the license... and started asking for license to activate the plugin.
Clearly its a WPML bug.

BUT - I wanted to deactivate Elementor Pro to proceed with WPML
and could not deactivate Elementor Pro

## Steps to reproduce

1. Latest WP multisite, Elementor Pro & WPML.
2. Set Elementor Pro license
3. Configure WPML - on third step Elementor Pro looses its license
Note: debug.log - empty, no error.log files

## Another Integration issue
4. I removed (compress & delete folder) Elementor Pro files from server - to deactivate it
5. WPML bug appears w/o Elementor Pro
6. I recovered Elementor Pro ** NO NEED TO ACTIVATE ** 
    Meaning: I assume the entry/ies in the data base are NOT corrupted
## Isolating the problem

- [ +-] This bug happens with only Elementor plugin active (and Elementor Pro).
  You MUST have some tool (WPML w/bug) to remove the license...
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.36
	PHP Version: 7.1.18
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: https://best-vpn.today
	Home URL: https://best-vpn.today/?lang=en
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Twenty Seventeen
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

== Active Plugins ==
	Elementor Pro
		Version: 2.0.16
		Author: Elementor.com

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

	WP Facebook Auto Publish
		Version: 1.4.9
		Author: xyzscripts.com

	WPML Multilingual CMS
		Version: 4.0.4
		Author: OnTheGoSystems


== Network Plugins ==
	Better Search Replace
		Version: 1.3.2
		Author: Delicious Brains

	Elementor
		Version: 2.1.4
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	Jetpack by WordPress.com
		Version: 6.3.2
		Author: Automattic

	MailChimp for WordPress
		Version: 4.2.4
		Author: ibericode

	Redirection
		Version: 3.4
		Author: John Godley

	SG Optimizer
		Version: 4.0.7
		Author: SiteGround

	WPML CMS Nav
		Version: 1.4.23
		Author: OnTheGoSystems

	WPML Media
		Version: 2.3.4
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.0.4
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.4.4
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.8.4
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.6.4
		Author: OnTheGoSystems

	Yoast SEO
		Version: 7.8
		Author: Team Yoast


== Debug ==
	Errors: 
		ReferenceError: tinymce is not defined
			at https://best-vpn.today/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.4 - 5418:26
			2018-07-22 11:57 +00:00

		TypeError: Cannot read property 'add' of null
			at https://best-vpn.today/wp-content/plugins/elementor/assets/lib/slick/slick.js?ver=1.8.1 - 1307:13
			2018-07-19 22:04 +00:00
			x 170 times

		ViewDestroyedError: View (cid: "view10850") has already been destroyed and cannot be used.
			at https://best-vpn.today/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.js?ver=2.4.5 - 1810:9
			2018-05-18 00:12 +00:00

				
```
</details>

**Comment by bainternet** [comment]
@Mulli 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
