### ISSUE TITLE
How can I enqueue a script for a specific Elementor widget?

### ISSUE THREAD

**Issue by mdjwel** [pojome/elementor#5186]
I want to enqueue a script for a specific Elementor widget only. 
How can I do that?

**Comment by bainternet** [comment]
If its a custom widget then in your widget class you can specify the scripts depandancy and elementor will enqueue them for you using the`get_script_depends` method, e.g:

```PHP
// in your widget call add
public function get_script_depends() {
	return [ 'script-handle-1', 'script-handle-2 ];
}
```

Just make sure you register them first:
```PHP
wp_register_script( 'script-handle-1', 'url-to-script.js' );
wp_register_script( 'script-handle-2', 'url-to-script.js2' );
```
