### ISSUE TITLE
Getting this error on reloading

### ISSUE THREAD

**Issue by nageshwadhera** [pojome/elementor#5188]
Notice: Undefined index: align_submit in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: align_submit_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: row_gap in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_spacing in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_color in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: mark_required_color in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_font_size in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_font_size_tablet in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_font_size_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_font_weight in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_text_transform in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_font_style in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_text_decoration in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_line_height in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_line_height_tablet in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_line_height_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_letter_spacing in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_letter_spacing_tablet in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: label_typography_letter_spacing_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: align_field_text in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: align_field_text_tablet in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: align_field_text_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field-text-padding in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field-text-padding_tablet in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field-text-padding_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_border_color in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_border_style in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_border_width in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_border_radius in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_focus_text_color in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_focus_border_color in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_focus_border_style in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_focus_border_width in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: field_focus_border_radius in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_text_color in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_font_family in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_font_size in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_font_size_tablet in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_font_size_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_font_weight in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_text_transform in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_font_style in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_text_decoration in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_line_height in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_line_height_tablet in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_line_height_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_letter_spacing in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_letter_spacing_tablet in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_typography_letter_spacing_mobile in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_border_border in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_background_hover_color in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

Notice: Undefined index: button_hover_color in C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\files\css\base.php on line 605

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
