### ISSUE TITLE
Youtube / google map embed pretty big pageload -> performance issue of widget

### ISSUE THREAD

**Issue by CaptainJakethe1st** [pojome/elementor#5189]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
The pageload of your youtube-embed-widget is pretty big with 250-500kB... 
I did run pingdow several times on that... 
![image](https://user-images.githubusercontent.com/41577927/43137726-df1515da-8f4c-11e8-8f9e-93c8425c1fed.png)

## Solution
The VideoPlugin of Ultimate Addons for Elementor has somehow a much smaller pageload... 
Adam from WPCrafter did a Youtube Video about the solution to this problem:
[https://www.youtube.com/watch?v=vlvch1ENQOk](url)

This would be awesome if you can fix this performance issue with the next update!

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29
	MySQL version: 5.6.19
	PHP Version: 7.1.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: https://praxis-heiler.de
	Home URL: https://praxis-heiler.de
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.4.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Analytify - Google Analytics Dashboard
		Version: 2.1.18
		Author: Analytify

	Astra Hooks
		Version: 1.0.1
		Author: Brainstorm Force

	Astra Pro
		Version: 1.4.0
		Author: Brainstorm Force

	Autoptimize
		Version: 2.3.4
		Author: Frank Goossens (futtta)

	Elementor
		Version: 2.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.16
		Author: Elementor.com

	GDPR Cookie Compliance
		Version: 1.1.1
		Author: Moove Agency

	Smush
		Version: 2.7.9.1
		Author: WPMU DEV

	UpdraftPlus - Backup/Restore
		Version: 1.14.12
		Author: UpdraftPlus.Com, DavidAnderson

	WP-Optimize
		Version: 2.2.4
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Mail SMTP
		Version: 1.3.3
		Author: WPForms

	WPML Multilingual CMS
		Version: 4.0.4
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.8.4
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.6.4
		Author: OnTheGoSystems

	WP Super Cache
		Version: 1.6.2
		Author: Automattic

	Yoast SEO
		Version: 7.8
		Author: Team Yoast

== Debug ==
	Errors: 
		ViewDestroyedError: View (cid: "view17226") has already been destroyed and cannot be used.
			at https://praxis-heiler.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-07-13 08:25 +00:00

		ViewDestroyedError: View (cid: "view19731") has already been destroyed and cannot be used.
			at https://praxis-heiler.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-07-13 08:25 +00:00

		ViewDestroyedError: View (cid: "view20688") has already been destroyed and cannot be used.
			at https://praxis-heiler.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-07-13 08:25 +00:00

		TypeError: Cannot read property 'statusText' of undefined
			at https://praxis-heiler.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.2 - 2:17387
			2018-07-12 13:38 +00:00

		TypeError: Cannot read property 'behavior' of undefined
			at https://praxis-heiler.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.2 - 2:224081
			2018-07-10 16:21 +00:00

		TypeError: Cannot read property 'get' of undefined
			at https://praxis-heiler.de/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.0.11 - 2:34035
			2018-06-29 12:41 +00:00
			x 13 times

		TypeError: Cannot read property 'on' of null
			at https://praxis-heiler.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-25 08:22 +00:00
			x 4 times

		TypeError: Cannot read property 'style' of undefined
			at https://praxis-heiler.de/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-25 08:22 +00:00
			x 4 times

		ViewDestroyedError: View (cid: "view585") has already been destroyed and cannot be used.
			at https://praxis-heiler.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-01 12:29 +00:00

		ViewDestroyedError: View (cid: "view15551") has already been destroyed and cannot be used.
			at https://praxis-heiler.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-06-01 11:04 +00:00

				
```
</details>

**Comment by bainternet** [comment]
@CaptainJakethe1st 

We already have that option if you use lightbox, and we will add it in the next major version.

**Comment by bainternet** [comment]
As for google maps you can always revert to an image for now.
