### ISSUE TITLE
Responsive previews

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#519]
Perhaps I'm missing some functionality? But it seems that the only way to have a large header that gets smaller on mobile screens is to create two of them and use the show/hide controls. The problem is, while it works when I preview the live page with an actual device, to mobile preview does not work. It still shows both headings which is not so helpful. 
<img width="931" alt="example" src="https://cloud.githubusercontent.com/assets/974442/18277311/d9fe1ce8-7402-11e6-8a40-92422e07c760.png">

**Comment by arielk** [comment]
Please click on the button "Preview" to hide this element, see the screenshot:
![fiuf3to](https://cloud.githubusercontent.com/assets/1778512/18279758/50488986-745f-11e6-9826-c06f5873c492.png)

In any case we are going to release a new mobile editor tomorrow !!!! I think it will solve your problem

**Comment by mizejewski** [comment]
Thanks -- that does work for mobile, but desktop still shows both.

I am **really** excited to see the new mobile editor though. That area was ripe for improvement.

**Comment by arielk** [comment]
Fixed #522
