### ISSUE TITLE
Drag-able / movable image placement and zoom for backgrounds and images. 

### ISSUE THREAD

**Issue by joshallen73** [pojome/elementor#5198]
Another comment was made on this but I thought it should be its own thread.

This is a very huge design feature that caused me to download brizy. Can this type of thing be added asap to elementor?

![42734308-532be49e-884a-11e8-848c-af94018a5fb3](https://user-images.githubusercontent.com/29894450/43163135-28bd7d0e-8f5b-11e8-9d22-bc2c0a97f5b6.gif)

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
