### ISSUE TITLE
Video background and Image fallback shows loader

### ISSUE THREAD

**Issue by odedta** [pojome/elementor#5200]
## Description

I have a video background with an image fallback, after page is loaded, it takes about 1 second for the image to switch to the video but during that switch the user is shown a loader, is it possible to get rid of it? it it possible to start the video loading 1 second earlier?

## Steps to reproduce

1. Create a row with a video background from Youtube.
2. Add an Image fallback
3. Load the 

page and see the loader

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.1
	MySQL version: 5.5.41
	PHP Version: 7.0.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: https://venncity.ussl.blog
	Home URL: https://venncity.ussl.blog
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Jerusalem
	Admin Email: oded@hdigital.co.il
	Debug Mode: Active

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.5.20
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.16
		Author: Elementor.com

	Full Screen Menu for Elementor
		Version: 1.0.1
		Author: Solitweb

	Ocean Extra
		Version: 1.4.18
		Author: OceanWP

	Ocean Modal Window
		Version: 1.0.13
		Author: OceanWP

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

	TinyMCE Advanced
		Version: 4.7.11
		Author: Andrew Ozz

	Tracking Code Manager
		Version: 1.11.7
		Author: IntellyWP

	WPML Multilingual CMS
		Version: 4.0.4
		Author: OnTheGoSystems

	Yoast SEO
		Version: 7.9
		Author: Team Yoast


== Debug ==
	Errors: 
		TypeError: Cannot read property 'errors' of undefined
			at https://venncity.ussl.blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.4 - 2:138622
			2018-07-22 10:53 +00:00
			x 27 times

		TypeError: Cannot read property 'stretch' of null
			at https://venncity.ussl.blog/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.0.16 - 2:23414
			2018-07-19 05:08 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://venncity.ussl.blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.3 - 2:138568
			2018-07-18 13:36 +00:00
			x 26 times

		TypeError: Cannot read property 'errors' of undefined
			at https://venncity.ussl.blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.2 - 2:138433
			2018-07-16 05:57 +00:00
			x 2 times


```
</details>

**Comment by bainternet** [comment]
@odedta 

This is how the background video works, we use the fallback image until the video is loaded and ready to play, and the video starts loading on page load which is as soon as possible.
So no there is no way to load the background video one second earlier.

**Comment by odedta** [comment]
I see, that's what I thought so how come I see the loader? it happens on any website, where is this loader coming from?

**Comment by bainternet** [comment]
Wait, what do you call a loader ?

**Comment by odedta** [comment]
https://www.useloom.com/share/38257ceb8b47402bbda68e7e9e9d1d69

When the screen goes black when it's switching from the fallback image to the video. It would be ideal not to see a black screen and a video loader
![loader](https://user-images.githubusercontent.com/13570550/43242600-a2fe9af8-90aa-11e8-8bc7-1a57bc0640c8.gif)
