### ISSUE TITLE
Clarity on registering and outputting theme locations

### ISSUE THREAD

**Issue by willcitizen** [pojome/elementor#5202]
Hi . This is essentially a support request, which your guidelines say doesn't belong here, but I was directed to github when I logged a ticket so here you go:

I've been building out my own version of the elementor hello theme with additional custom locations.  I have it working, but encountered some points which need clarity/improvement

Your example of registering a custom location below for reference:

	$elementor_theme_manager->register_location(
		'main-sidebar',
		[
			'label' => __( 'Main Sidebar', 'theme-name' ),
			'multiple' => true,
			'edit_in_content' => false,
		]
	);

First question : what is the theme-name parameter for?  It's not described in the document and doesn't appear to have any function - I currently have it set to the same as the location slug and it appears to be working?

Second question : I understand that multiple = true allows one to effectively overload a theme location with multiple templates which is great, but at display time there doesn't appear to be any way to determine the order they are rendered in - is there an undocumented trick to this as it's not really useful in this state.

Third question : your document indicates that edit in content => true would make that location editable on the page/post.  I was half expecting to see multiple edit with elementor buttons appear on my pages with the custom location assigned to them, or to see some additional edit space appear within the live editor, but there doesn't appear to be any of this - can you please clarify how this works, or is it not fully implimented yet?

Thanks
Will

**Comment by bainternet** [comment]
@willcitizen 

Sorry for the late replay,

To answer your questions:
* `theme-name` is just a placeholder for the translation [Text Domain](https://codex.wordpress.org/I18n_for_WordPress_Developers#Text_Domains) used by WordPress.

* Sadly, you are correct in your understanding that currently there is no way of prioritizing multiple templates in a location.

* It is implemented and accessible in the admin bar when you are viewing the page on the frontend:


![screen shot 2018-08-16 at 18 04 04](https://user-images.githubusercontent.com/660572/44216946-e1243d80-a17e-11e8-8a13-20a1df6c6cde.png)


thanks.
