### ISSUE TITLE
Clicking on Posts Widget Pagination's Last Page in Custom Archive Template Redirects to 404 Page Not Found

### ISSUE THREAD

**Issue by abvlbcpa** [pojome/elementor#5203]
I am using Elementor Pro with Astra Theme, both latest versions.
I wanted to make a custom Archive Page template so I created an Archive Template using Elementor Template Builder and used the Posts Widget for this. Once done, I tested pagination, but clicking on the last numbered page redirects to 404 Page Not Found.

Steps to replicate:
1. Create an Archive Template from scratch (i.e not using prebuilt templates) and use Posts Widget.
2. Set Pagination settings to 
Numbers: Previous + Next
Leave other settings to default

3. Set Layout Setings to 
Columns: 1
Posts: 3

4. Set Query Settings to
Source: Posts
Category: All
Query enough posts to have at least 3 pages.

5. Save page and open.

6. Click on Page 2. Should work as expected.
Click on Next. Should work as expected

7. Click on last numbered page. 404 page error occurs.
If you click Next when you are before last numbered page, the error also occurs.

I repeated the same steps, this time not in Archive Template Creator but just by creating a normal page. 
But the 404 Page Not Found Error does not occur.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Isolating the problem.
* System info.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
