### ISSUE TITLE
Text Editor Widget Inconsistencies between sidebar and inline editor

### ISSUE THREAD

**Issue by simonclay** [pojome/elementor#5208]
When using the Text Editor widget: 

Editing via the sidebar clicking Bold or Italic wraps the selected word(s) with `<strong>` and `<em>` respectively.

When editing on page/inline clicking Bold or Italic wraps the selected word(s) with `<b>` and `<i>`

I noticed this when trying to use Additional CSS to change the way Bold and Italic items are displayed.

Not a massive issue for most users, but wanted to mention it for consistency and because occasionally like me, people will need to style bold/italic items in a certain way. Currently need to write CSS rules for both `<b>` and `<strong>` and `<i>` and `<em>`.

![screen shot 2018-07-25 at 11 59 49](https://user-images.githubusercontent.com/2143351/43198010-f90909de-9004-11e8-8e10-7ac8655e9f0e.jpg)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.56
	PHP Version: 7.1.18
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.4.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.72
		Author: ServMask

	Astra Pro
		Version: 1.4.0
		Author: Brainstorm Force

	Elementor
		Version: 2.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.16
		Author: Elementor.com

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	iThemes Security
		Version: 7.0.4
		Author: iThemes

	Yoast SEO
		Version: 7.9
		Author: Team Yoast


== Debug ==
	Errors: There are no errors to display
				
```
</details>

**Comment by black-eye** [comment]
Following this

**Comment by bainternet** [comment]
@simonclay 

We are aware of this, and  currently, there is nothing we can do about it without replacing the whole inline-editing module, which is something I don't see happening anytime soon

thanks for reporting.
