### ISSUE TITLE
Can't delete a custom widget

### ISSUE THREAD

**Issue by spirau** [pojome/elementor#5209]
I have developed a certain number of widgets for my website that work perfectly. But for the last one, the Remove action of the menu is not working. The remove action can be seen in the history panel, but the right-click menu doesn't disappear, nor the widget. The rendering and all dynamic features of the widget are working, the structure of the widget in the postmeta in correct.
Any idea about this behaviour?

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without seeing your code, its impossible for us to know.

Any console errors?

**Comment by spirau** [comment]
Nothing on the console. As it is a custom widget, it’s not possible to give you steps for replicate.

My question was in case you had such situations during development and remember what was the cause.

 

De : Raz Ohad [mailto:notifications@github.com] 
Envoyé : jeudi 26 juillet 2018 12:30
À : pojome/elementor
Cc : Eric Spirau; Author
Objet : Re: [pojome/elementor] Can't delete a custom widget (#5209)

 

Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information:

*	Prerequisites.
*	Steps to replicate.
*	Isolating the problem.
*	System info.

Without seeing your code, its impossible for us to know.

Any console errors?

**Comment by spirau** [comment]
Here is the content of the elementor postmeta for a page build with just this widget that can be seen here : https://refonte.marip.com/test-elementor/

[
  {
    "id": "68527a9",
    "elType": "section",
    "settings": [],
    "elements": [
      {
        "id": "70071a0",
        "elType": "column",
        "settings": {
          "_column_size": 100
        },
        "elements": [
          {
            "id": "bdccae0",
            "elType": "widget",
            "settings": [],
            "elements": [],
            "widgetType": "mp-hexagramme"
          }
        ],
        "isInner": false
      }
    ],
    "isInner": false
  }
]

**Comment by bainternet** [comment]
@spirau 

Sadly, I can't help and have no clue why that is happening to you.

**Comment by spirau** [comment]
I come back to give the solution of this issue : don't use "id" as a control name, elementor is trapped by it.

**Comment by bainternet** [comment]
Ok then it would have seen the code we could catch that.

Anyway glad you figured it out.
