### ISSUE TITLE
ACF Gallery Field using Dynamic Link not working

### ISSUE THREAD

**Issue by crispee2000** [pojome/elementor#5212]
Was really excited to see the ACF linking in beta so tried out using the Gallery field since that relates to what i'm doing now.  Unfortunately, it doesn't work.  

I've tried with the standard Elementor gallery and the Namogo Gallery Extra.

This applies to the images in the Gallery and even simple text fields don't get pulled in to the Heading of the Gallery.

**Comment by crispee2000** [comment]
Yes I know.  Elementor support says that the standard gallery is listed as working and in my test it does not.  They asked that I add this to GitHub to get it on the radar.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
