### ISSUE TITLE
Add Target parameter in Elementor Posts

### ISSUE THREAD

**Issue by MAthez** [pojome/elementor#5217]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The Posts widget has become incredibly powerful, however, one option is missing: the ability to open the post in a new window. It can be useful for using Posts with a CPT for external web sites for example, where such posts do redirect to the external web site. 

**Describe the solution you'd like**
Please just add an option toi set target.

**Describe alternatives you've considered**
I have tried a redirect plugin that uses JQuery to enable opening in new window, but 1> it does not always work 2> it may cause jquery mess and conflicts. 
I guess skins moight be an option... bbut still complicate to implement for most users.

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
