### ISSUE TITLE
Single Page Templates and Wordpress Page Templates

### ISSUE THREAD

**Issue by bsmalldesign** [pojome/elementor#5222]
It would be awesome if when you're choosing your conditional display options for single page templates if you could associate it to pages that have a certain wordpress page template (for example, if I create a duplicate php template of a page and name it something different, like 'right sidebar', then I create a single page template in elementor and assign it to all pages that have that php template). I feel like that would make it easier to assign single page templates to pages in less steps or at least from the wordpress page menu. Thoughts?

**Comment by bainternet** [comment]
@bsmalldesign 

This kind of goes under custom conditions which can be achieved easily with the template conditions API but it has no docs yet so I'll leave this open for now.

**Comment by bsmalldesign** [comment]
Ok thanks! Does that mean it's currently possible or not yet?

**Comment by bainternet** [comment]
@bsmalldesign 

Currently possible.

thanks.

**Comment by bsmalldesign** [comment]
Is it possible through the interface or does it require me to know some programming to make it possible?

**Comment by bsamarketing** [comment]
I am interested in this too. I would live to be able to control which elementor template was used based on a call from the theme_page_templates filter

add_filter('theme_page_templates', 'choose_template');
function choose_template () {
if(a=1){
Use elementor template A
} else {
Use Elementor Template B
}
I think you are suggesting this is possible via the conditions API, but that this is currently documented.

Are there any plans to document, or resources to get support in using it?

Where is the API located in the elementor code?
