### ISSUE TITLE
Error in developer docs - group controls

### ISSUE THREAD

**Issue by pmallek** [pojome/elementor#5224]
Apologize if this is wrong place for reporting docs problems but couldn't find better place.

There is mistake in group controls "Usage" section (for every group control).

```
		$this->add_control(
			Group_Control_Typography::get_type(),
			[
				'name' => 'content_typography',
				'label' => __( 'Typography', 'plugin-domain' ),
				'scheme' => Scheme_Typography::TYPOGRAPHY_1,
				'selector' => '{{WRAPPER}} .text',
			]
		);

```
While it should be:

`$this->add_group_control` - found in source code

Example: https://developers.elementor.com/elementor-controls/typography-control/

**Comment by bainternet** [comment]
Thanks, updated.
