### ISSUE TITLE
PNG Images Are Showing with "Secondary" Default Color as Background

### ISSUE THREAD

**Issue by navaweb** [pojome/elementor#5226]
Elementor 2.1.5

If you have Default Colors > Color Palette setup with a SECONDARY color, this is being used in the global.css for "img" tag.. so it is adding this colour to ALL image file backgrounds. See CSS code for global.css. img is setup with backgound color #000000 ... if I change SECONDARY color to green, then all images update with this as well.

I disabled all plugins and re-activated one by one. Elementor 2.1.5 is faulty plugin that causes this.

![elementor___home](https://user-images.githubusercontent.com/41243376/43306542-65a05b84-9130-11e8-8454-5f764c78d203.png)

![37853962_1863749933692979_1120217038044790784_n](https://user-images.githubusercontent.com/41243376/43306547-693100fa-9130-11e8-9468-5c03ee0c671a.png)

Hope this can be fixed soon. Thank you!
Elyssa

**Comment by navaweb** [comment]
Disable Default Colors in Elementor Settings fixes this issue... but it's not a solution...

**Comment by navaweb** [comment]
I am using Astra Theme + Astra Pro (forgot to mention)

**Comment by navaweb** [comment]
I installed TwentySeventeen, deactivated Astra Pro, and deactivated all other plugins one by one.. the issue continues to persist, until I deactivate only Elementor

Only if I go to Elementor > Settings > Disable Default Colors then the issue stops... because then this way, Elementor does not use The colour picker to set default colours...

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support @ elementor.com, with complete login information to access your website, and our support team will try to assist.
