### ISSUE TITLE
Ability to make a template for printing content

### ISSUE THREAD

**Issue by slwirth** [pojome/elementor#5230]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Several of us have issues printing Elementor pages consistently across browsers, and with a nice layout. The worst issue is worst with FF as it only prints the first page.

**Describe the solution you'd like**

It would be awesome to be able to create a print Elementor template in a similar way we can do it for archives or single posts.

**Describe alternatives you've considered**
I tried to set up a media query, but couldn't come up with a good one. I ask in the Facebook group, but no other suggestion come up (see https://www.facebook.com/groups/Elementors/permalink/1567928859999561/). 

Thanks for your work and for considering this feature :).

**Comment by bainternet** [comment]
@slwirth 

As far as I know, it should and does work out of the box, if have a specific problem please feel free to reopen and provide examples.

**Comment by vgstef** [comment]
I also have many issues with printing pages. 

One problem is the sticky header. It gets printed on each page and over the content of the page.

Another issue is that the URL of each html links in the page are shown (ex. https//....).

In the end, it gets unreadable, ugly and takes too many pages.

**Comment by jasonb4u** [comment]
This would great to have, whats the status on this?

**Comment by jasonb4u** [comment]
exactly 1yr from my last comment and still no-one knows anything... sad

**Comment by foligo** [comment]
Any news on that? Printed Elementor pages still look like ... not good.
