### ISSUE TITLE
Bug: Icon List alignment

### ISSUE THREAD

**Issue by siro83** [pojome/elementor#5232]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I found a bug with the icon list. In certain constellations it can happen that the icon is no longer aligned correctly.

This seems to be the case for multiline entries, but not for all.

![bildschirmfoto 2018-07-27 um 19 28 04](https://user-images.githubusercontent.com/36258023/43337623-c1f3d006-91d4-11e8-8a6f-adfdf11995b8.png)

## Steps to reproduce

I cannot describe the steps exactly, because the error does not always occur.
It occurs sporadically for lists entries with several lines.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@siro83 

We can't replicate, 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
