### ISSUE TITLE
Any widget you can add a link prefixes with the pages url it was created on

### ISSUE THREAD

**Issue by knightknight** [pojome/elementor#5233]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Any widget you can add a link prefixes with the pages url.

## Steps to reproduce

On any page use a widget that has link ability, eg. button. Add a link to page or post. When you preview the page the widget with the url will show the page the buton was created / the actual page you linked.

Eg:  Button linking to a portfolio page from the about page shows as _about/portfolio_ when I would be expecting it to show as _/portfolio_ or _portfolio/my-themes_.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.34 (Unix) OpenSSL/1.0.2o PHP/7.1.14
	MySQL version: 5.5.5
	PHP Version: 7.1.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 48M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: https://domain.test
	Home URL: https://domain.test
	WP Multisite: No
	Max Upload Size: 48 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.5.21
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:61.0) Gecko/20100101 Firefox/61.0

== Active Plugins ==
	All In One WP Security
		Version: 4.3.6
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Carbon Fields
		Version: 2.2.0
		Author: htmlburger

	Contact Form 7
		Version: 5.0.3
		Author: Takayuki Miyoshi

	Elementor
		Version: 2.1.5
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	Ocean Extra
		Version: 1.4.19
		Author: OceanWP

	Publications
		Version: 0.1
		Author: 

	Under Construction
		Version: 1.18
		Author: Noah Kagan

	What The File
		Version: 1.5.4
		Author: Never5

	WP Mail SMTP
		Version: 1.3.3
		Author: WPForms

**Comment by bainternet** [comment]
We can't replicate the issue.

Our URL control accepts relative URL ( '/portfolio' ) and prints it just as you enter eg:
```HTML
<a href="/portfolio">button</a>

please make sure this is not caused by a 3rd party plugin.

**Comment by knightknight** [comment]
No issue with third party plugins installed.

I needed to add the `/folder` part for the link within the widget. Looking forward to when the link dropdown selector is added.
