### ISSUE TITLE
YouTube video title visible when loading in Firefox 61.0.1 (64-bit)

### ISSUE THREAD

**Issue by hotboxprintstudio** [pojome/elementor#5235]
Just discovered Chrome seems to ignore this, but Ive found Firefox reveals the video title while loading.... anyway to hide this??

Elementor 2.1.4 (2.1.5 was causing me a server error so rolled back)

Example:
https://youtu.be/0qfYi0gYIpE

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
