### ISSUE TITLE
Bug: Elementor pro and Toolset Layouts don't work after update latest versions of Elementor

### ISSUE THREAD

**Issue by TheNits** [pojome/elementor#5237]
I downloaded the latest elementor and pro versions today.
Suddenly the website stopped showing the backend content on the front end.
After trouble shooting, de-activating plugins and deleting elementor and pro and downloading fresh new installs from elementor the problem occurs when Toolset Layouts is activated.

When i deactivate toolset layouts the content shows on the front-end, when activated then nothing shows.

Any idea's how to solve this?

Cheers

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
