### ISSUE TITLE
[Feature Request] Global Design Template

### ISSUE THREAD

**Issue by OCpublishing** [pojome/elementor#5240]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hi

Sorry if I missed it already but couldnt find it anywhere.

### Here is my request:
I would like a '_Global Section Design Template_'

**Example:** 
For example lets say I have a 'recipe recap box' at the end of my recipe pages on my website.

I created a specific design in a template with images and text contents, icons...
I saved it and used for evey recipe.

Now lets say i want to redesign my website by removing one of the image of this template and changing the background color of this template.

Unless I missed something, the only option I have today is doing it manually on each and every page. (thanks for implementing the copy and paste style btw)

My request:
I would like to be able to create a ### 'Global Design Template' that would only update the design and the styling but NOT the content and allow us to insert content.

global widget - its only for widgets and it updates design AND content
Templates - If inserted from library, specific text can be inserted but deisgn cant be updated globaly
Template if used my the template widget - content cannot be changed for each page

Thanks for your help guys and your tremendous work on Elementor

Thanks for tremendous job guys

**Comment by bainternet** [comment]
This is already possible with Elementor Pro theme builder form v2.0
[Creating a single post template with Elementor Pro](https://docs.elementor.com/article/354-creating-a-single-post-template-with-elementor-pro?source=github&medium=link)

**Comment by OCpublishing** [comment]
Hi Raz / bainternet

And thank you for this fast answer.
But its not quite why I was asking for.

I dont need a single post template. For example, lets say that I want to create a page about recipe done with chickens.

I will create my page/ post as a regular one using elementor but lets say every two or three paragraph I wan to add a _module_ (wich would be an elementor template) with a specific design that I could fill with my own content.

Module 1 would be fried chicken
text / content
Module 2 : Chicken à la sauce bearnaise
texte / content
.....

As you can see a single post template does not do the job because it has a definitive place and number of specific _modules_

Here is an example of the sections I designed.
![capture](https://user-images.githubusercontent.com/41859489/43366329-9d206708-933c-11e8-89b7-2ca2626a08af.JPG)

I want to be able to put it where I want, the number the time I want, with a specific content everytime, but the design would be saved under the template and when i change the original template design it updates everywhere.

Think of it as a 'CSS design template for placeholders'

I hope I was more clear this time

Thanks for your help Raz
