### ISSUE TITLE
Actions for Countdown Timer

### ISSUE THREAD

**Issue by hanovent** [pojome/elementor#5242]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

There are no actions for the countdown timer.  It just counts down and then resets itself.  There is no point to it.

**Describe the solution you'd like**

1. I would like to see a setting for Actions that can chosen when the timer counts down to zero.
    a. Hide timer or display timer at 00:00
AND one of these
    b. Display a message
    c. Make another element disappear (like order button - it disappears when timer reaches zero AND a custom message can be displayed like "Sorry... This offer has expired)  Timer can be chosen to display at 00:00 or be hidden
    d. Sales price gets an "X" through it and regular price appears
    e. Timer resets (For example, regular price $100 - First counter offers sale price of $29... after counts down second timer offers for $59)
        1. Need to be able to set days, hours, minutes, seconds for 2nd timer
        2. Ability to have new message to appear (that could say for example... "SECOND CHANCE! You missed your chance to get the deal but you can still take advantage of this deal) This makes buyers believe the timer consequences are REAL!
        3. Price for first timer gets crossed (e.g. $29) out and new price appears (e.g. $59)
        4. Action when this second timer counts down (e.g. $100 price appears with $29 and $59 crossed out)
  
ALSO... IT WOULD BE GREAT TO JUST BE ABLE TO SET THE HOURS AND MINUTES INSTEAD OF WORKING WITH THE CALENDAR TO TRY TO FIGURE IT OUT.  For example... hours can be set to 3 and minutes to 59 (or whatever...)

**Describe alternatives you've considered**

Buying plug ins that aren't specifically made to work with Elementor or ones like this :  https://powerpackelements.com/elementor-countdown-timer-widget/

**Additional context**

![image](https://user-images.githubusercontent.com/8518990/43369584-daad672c-9325-11e8-8acb-828fcf99970e.png)

**Comment by drewclifton** [comment]
+1,000

But you missed possibly one of the most important actions on timer expiry:

*Redirect to another URL!!!* :)

Thanks.

**Comment by hanovent** [comment]
You're right!  I hadn't even thought of it.  ADD THIS TOO!
