### ISSUE TITLE
Custom Script Feature not Working

### ISSUE THREAD

**Issue by thepiemaster6000** [pojome/elementor#5244]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I have a simple script that should add a class to an element when it scrolls to a certain spot on the page. For some reason it's not working and would appreciate any help with this issue. 

## Steps to reproduce
Here is the script pasted into Custom JS feature, screenshot link attached for reference:

$(window).scroll(function(){
    if ($(this).scrollTop() > 50) {
       $('#dynamic').addClass('newClass');
    } else {
       $('#dynamic').removeClass('newClass');
    }
});
[http://wearestarke.com/rebel/wp-content/uploads/2018/07/Untitled-1.jpg](url)

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@thepiemaster6000 

No idea why or whats not working for you, but you should check the console to see if you have any errors.
