### ISSUE TITLE
Ability to translate form dynamic error messages (tooltips)

### ISSUE THREAD

**Issue by wojtekkutyla** [pojome/elementor#5246]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

The website that I am running is in Polish. Whilst I am able to translate form error and success messages that are displayed in the form editing widget, I cannot translate or even find tooltip messages that appear dynamically over the fields in the form.

## Steps to reproduce

Create a form.
Make at least one field mandatory.
Try submitting.
Notice the tooltip appearing over erroneous fields. The message is in English — and that cannot be changed anywhere, thus making the site inaccessible to localised audiences.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>Syste
<img width="283" alt="2018-07-28_18-22-45 939" src="https://user-images.githubusercontent.com/17164438/43386455-8d726ba4-93db-11e8-9bba-1d35dae32de1.png">
m Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 5.6.39
	PHP Version: 5.6.37
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: -
	Home URL: -
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Graphy
	Version: 2.1.2
	Author: Themegraphy
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 2.1.5
		Author: Elementor.com

	Elementor Extras
		Version: 1.9.12
		Author: Namogo

	Elementor Pro
		Version: 2.0.18
		Author: Elementor.com

				
```
</details>

**Comment by arielk** [comment]
We use HTML5 fields and all errors come by browser language, not something that can be controlled by Elementor. If you change the browser language, the error message will also change.

Thanks for your feedback!

**Comment by toibry** [comment]
> With the following Script you are able to customize it.
> 
> ```
> document.addEventListener("DOMContentLoaded", function() {
>     var elements = document.getElementsByTagName("INPUT");
>     for (var i = 0; i < elements.length; i++) {
>         elements[i].oninvalid = function(e) {
>             e.target.setCustomValidity("");
>             if (!e.target.validity.valid) {
>                 e.target.setCustomValidity("This field cannot be left blank");
>             }
>         };
>         elements[i].oninput = function(e) {
>             e.target.setCustomValidity("");
>         };
>     }
> })
> ```

Hi, could you please tell me where to put this code? I'm using WordPress with Elementor builder and I l know little about coding, so if there's strait forward way to use this code any where in my system please let me know. Appreciated

**Comment by Lari540** [comment]
> > With the following Script you are able to customize it.
> > ```
> > document.addEventListener("DOMContentLoaded", function() {
> >     var elements = document.getElementsByTagName("INPUT");
> >     for (var i = 0; i < elements.length; i++) {
> >         elements[i].oninvalid = function(e) {
> >             e.target.setCustomValidity("");
> >             if (!e.target.validity.valid) {
> >                 e.target.setCustomValidity("This field cannot be left blank");
> >             }
> >         };
> >         elements[i].oninput = function(e) {
> >             e.target.setCustomValidity("");
> >         };
> >     }
> > })
> > ```
> 
> Hi, could you please tell me where to put this code? I'm using WordPress with Elementor builder and I l know little about coding, so if there's strait forward way to use this code any where in my system please let me know. Appreciated

Hey!

As far as I know, you can use the Elementor HTML widget add the:
`<html> 
<script>
//Your code goes here
</script>

</html>`

And then paste the JS code at the bottom of the page or just above the widget you need or use a plugin for that matter like - https://wordpress.org/plugins/header-footer-code-manager/

**Comment by FlexxAlex** [comment]
Maybe a bit late to the party, but..

I have multiple fields, how can I target just a specific one?
