### ISSUE TITLE
image carousel lightbox bug

### ISSUE THREAD

**Issue by hineedhelp** [pojome/elementor#5249]
hello, I need help my elementor image carousel lightbox is being weird, when I click on the image it will show the lightbox then when I close it, it won't go back to the page but instead be stuck in a black screen I need help.
<br/>
<br/>
<br/>
1.
![1](https://user-images.githubusercontent.com/41904559/43396407-1990bb6c-940a-11e8-935c-daa11adb20ca.JPG)
<br/>
2.
![capture](https://user-images.githubusercontent.com/41904559/43396409-19c5369e-940a-11e8-9815-06a555ac6d92.JPG)
<br/>
3.
![capture1](https://user-images.githubusercontent.com/41904559/43396410-19f910a4-940a-11e8-8edc-d0d2642eb4fe.JPG)
<br/>

**Comment by hineedhelp** [comment]
Its all good now

**Comment by ClassActHarris** [comment]
Hi @hineedhelp , how did you fix this issue? I'm receiving the same issue.
