### ISSUE TITLE
Allowed types filter for file uploads is case-sensitive

### ISSUE THREAD

**Issue by curiouslychris** [pojome/elementor#5254]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When allowed file types are set in Elementor forms for file upload fields, validation fails if an allowed file type is uploaded with an all-caps extension and the allowed type is set as lowercase, or vice-versa.

## Steps to reproduce

1. Create a form on an Elementor-built page.
2. Add a file upload field to the form, and set the allowed type to an extension in lowercase, e.g. "jpg".
3. Save the page and load the live view.
4. Choose a file to upload with the same extension, but in all caps, e.g. "JPG".
5. Attempt to submit the form. Assuming the rest of the form (if any other fields exist) validates, the upload field will fail validation and the error message will display (either the default, or the one set in Additional Options).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
We just released a patch for this issue, please update!

Thanks

**Comment by emtiyazchowdhury** [comment]
For some reason I cannot get elementor to upload doc or docx documents. I always receive an error. Can anyone help with this? Pdf works fine. I've got the following in the allowed file types: pdf, doc, docx
