### ISSUE TITLE
[REQ] Border color for 4 sides

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#5256]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Can't change color for border sides separately**
If i want the widget to have a border color blue and the bottom border color red i can't. i don't even know if it's possible with the custom css thing because if i try `selector{border-bottom-color:red;}` it doesn't work.

**Add this option**
Even if it can be done with custom css i think nowadays web designers use this ability a lot and it should be a built in option.

**Comment by arielk** [comment]
Try to use this code, it should work for you in the frontend:

`selector > .elementor-widget-container {
    border-bottom-color: red;
}`

**Comment by bentalgad** [comment]
Thanks, but let my quote my self :)

> Even if it can be done with custom css i think nowadays web designers use this ability a lot and it should be a built in option.
