### ISSUE TITLE
Cannot specify separate margin/padding values in Advanced UI

### ISSUE THREAD

**Issue by twiginteractive** [pojome/elementor#5270]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
![pad2](https://user-images.githubusercontent.com/3949309/43474687-8b3dce64-94c1-11e8-94fd-04324be3b4ee.jpg)

The Advanced CSS UI tab (for any element) doesn't allow for entering values into just some of the 4 param fields (top|right|bottom|left). Even when these inputs are 'unlinked' , the other fields auto-update to integer 0.

This means that it's impossible to use the UI to generate the inline CSS like:
`margin-top: 7px`

Instead we get
`margin: 7px 0 0 0`

which will mistakenly override values we want to cascade.

## Steps to reproduce

- Fresh WP install, install + activate Elmentor
- Edit any page with Elementor, add any element (Text Editor etc.)
- Go to Advanced tab, unlink the params (CHAIN ICON)
- Try to enter a value in just ONE field, leave the others blank
- Example: 7 BLANK BLANK BLANK
- It will get updated to 7 0 0 0

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Hanleymade** [comment]
Good catch and an important one to fix.

**Comment by twiginteractive** [comment]
Somehow I missed that a similar issue had already been logged, despite searching for "margin padding"
See https://github.com/pojome/elementor/issues/2219

Also, that issue references another good point - being able to enter 'auto' and perhaps even mixing units
See https://github.com/pojome/elementor/issues/3319

**Comment by twiginteractive** [comment]
Any update / comment from the Elementor authors please? Seems like this is kinda a big deal for a plugin that is so amazingly flexible in other areas...

**Comment by black-eye** [comment]
+1

**Comment by mblack777** [comment]
+1

The inflexibility is frustrating.

**Comment by twiginteractive** [comment]
It is strange that 2 minor updates have been released since I reported this issue, fixing (IMHO) less important bugs... the other (less complex) builder apps like VC, Divi etc. have no problem with separate padding/margin/border controls.

**Comment by blackb2b** [comment]
I am also confused why we can not change the padding/margin- top/right/bottom/left separately. It indeed  is an important bug and need to fix as soon as possible. Waiting for the fix. Thanks.

**Comment by bainternet** [comment]
I merged this issue with  #2219, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
