### ISSUE TITLE
Click to Popup

### ISSUE THREAD

**Issue by cobusvanvuuren** [pojome/elementor#5271]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A clear and concise description of what the problem is. It is painful (I am not tech savvy) and difficult to figure out how to link a button to a popup lightbox that has a form that collects data like email address etc. It is a better conversion option than to have the form embedded on the site. 

**Describe the solution you'd like**
A customizable button that is connected to the forms functions in Elementor so that when you click the button a popup comes up that will collect data like, email, name, phone etc (all the functionality of current forms). 

**Describe alternatives you've considered**
I have tried Zapier integration but it only does normal embedded forms. I also tried to incorporate Mailerlite's internal click to popup codes. They give you a which looks like javascript code to use and there is no functionality within the button function of Elementor to insert code. If you only use the code there is no way to design the button which looks terrible just as is.
![mailerlite 2](https://user-images.githubusercontent.com/41963845/43487091-d0f02cb4-9515-11e8-8b19-da04fece5e3e.png)
![mailerlite](https://user-images.githubusercontent.com/41963845/43487092-d12b8aac-9515-11e8-8024-cfddcbd52e91.png)

**Additional context**

**Comment by bainternet** [comment]
I merged this issue with  #628, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
