### ISSUE TITLE
Post Widget width issue between 797 and 1024

### ISSUE THREAD

**Issue by philrp** [pojome/elementor#5272]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

With the Posts widget set to 1 column and 1 post per page, the width gets set to 50% (should be 100%) if the window is between 767 and 1024 pixels wide.  (Works fine for 1 column and 2 or 3 posts per page)

It seems the following CSS gets called:
@media (max-width:1024px) {
.elementor-grid-tablet-2 .elementor-grid-item {
        width: 50%
    }

Thanks. Hope I did this right.

## Steps to reproduce

-Install clean Wordpress with TwentySixteen
-Edit the Sample page and add the Posts Widget set to 1 column and 1 post per page.
-Resize your browser window to between 767 and 1024 pixels wide

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache
	MySQL version: 5.6.38
	PHP Version: 7.1.12
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: http://testtest:8888
	Home URL: http://testtest:8888
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Sixteen
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.18
		Author: Elementor.com


== Debug ==
	Errors: There are no errors to display
				
</details>

**Comment by arielk** [comment]
You can just change the default for the tablet to 1 column by clicking on the device icon > change to a tablet. let me know if it works for you.

**Comment by philrp** [comment]
That works. I get it now.

In most cases in Elementor, the desktop setting is the default behaviours for tablet and mobile.

Your default settings of 3, 2, 1 for number of columns is logical, but not so intuative, given the above.

Thank you.

**Comment by arielk** [comment]
Thanks. We will look into it.
