### ISSUE TITLE
Feature Request: Scarcity Countdown Timer

### ISSUE THREAD

**Issue by zrk4444** [pojome/elementor#5273]
If you could make it so the countdown timer would start at the same time when a user appears on the page, that would be great.

Example, userA subscribes to newsletter and lands on sales page with countdown timer with 3 hours left.
The same thing happens to userB and C etc. even though they all landed on the page on different days.

This would allow you to use tags within your CRM to control when the user gets locked out of a page, effectively making an evergreen scarcity countdown timer.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
