### ISSUE TITLE
Background video stops music on mobile (even when only fallback image is shown)

### ISSUE THREAD

**Issue by suiluj** [pojome/elementor#5275]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I use a background youtube video at the beginning of my home page.
On desktop it is shown. on mobile and tablet not (as expected only fallback image).

**The problem:**  
On android chrome browser an audio notification is shown (with the name of the video).
Even if you cannot see the video running, it still stops music which was played before on that mobile.

## Steps to reproduce

Create a section with background youtube video and view on android chrome browser.
After a while (not always/at once) the notification appears and music stops if played before.  

Here is a link to my current page with the bug:  
[aquaplant-shop.de](https://aquaplant-shop.de/)

At the moment i tried to duplicate the section and disable the one with the video background for tablet and mobile and change the duplicate to image background only and disable it on desktop. But that did not help.

**Update:**  
I uploaded the video to my wordpress media and now use the local url instead of the youtube video.
It seems that now there is no music stopping and no notification.  
Only new problem: the fallback image which is the first frame of the video and the local video are not aligned. So when the video starts there is a jump. Before with the youtube video they were perfect aligned.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

Elementor free plugin
Astra free theme

```
</details>

**Comment by bainternet** [comment]
@suiluj 

There is no sound for background videos in mobile, so its not an issue,
as for the self-hosted video, we have added a poster option in v2.2.4 so make sure to update.

thanks.

**Comment by suiluj** [comment]
By the way since a few weeks the problem started again

**Comment by cecofuli** [comment]
Hello,

same problem here. 

I have a Youtube video as background and no fallback image.
On the mobile (tablet) I don't see nothing (obviously), but I'm able to hear the music and I see the audio notification  on Chrome browser... 

I don't remember such behavior in the past... 

Can you fix it?
