### ISSUE TITLE
Facebook widget to "like" individual posts with dynamic URLs taken from a Facebook page

### ISSUE THREAD

**Issue by Carlos-Azuaje** [pojome/elementor#5278]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
1) Having to manually insert a widget to each individual post after publishing.
2) Provide a better user experience for the reader.

**Describe the solution you'd like**
To be able to use this widget on the Elementor single post template so that it pulls URLs of each post from my Facebook page.

**Describe alternatives you've considered**
Manually insert the Facebook Embed widget to each post (so not very efficient). Also, this displays the entire post details (title, excerpt, featured image) and only at the very bottom, the "like", "comment" and "share" options (so not a very good experience for the reader).

**Additional context**

**Comment by bainternet** [comment]
@Carlos-Azuaje 

Can you explain better? provide examples?

**Comment by bainternet** [comment]
@Carlos-Azuaje 	

This already exists in Elementor Pro, https://docs.elementor.com/article/237-facebook-like-button

thanks.

**Comment by Carlos-Azuaje** [comment]
Hi, oh Gosh... so much time since I asked.

Where is this information taken from? Or how does it work? I have been
checking my posts and some coincide with my data on Facebook, but some
others don't.

**Comment by Carlos-Azuaje** [comment]
By the way, this does not accomplish the action that I was talking about.
If you "like" a post on a blog through the Facebook Like Button Widget,
that doesn't get reflected on the original Facebook post; it only works
backwards.

So not resolved yet.
