### ISSUE TITLE
Add align-justify option to text-editor elements

### ISSUE THREAD

**Issue by bendqh** [pojome/elementor#5279]
Elementor 2.16 lacks align-justify option in text-editor elements. I suggest adding it.

![a](https://user-images.githubusercontent.com/31392185/43518919-377cdd4e-9596-11e8-9c22-a771e4bbbac1.PNG)

**Comment by arielk** [comment]
Please read this article: https://www.wpbeginner.com/plugins/how-to-add-underline-and-justify-text-buttons-in-wordpress/

Or install this plugin: https://wordpress.org/plugins/tinymce-advanced/
