### ISSUE TITLE
[Enhancement] More Image Hover Effects

### ISSUE THREAD

**Issue by lunacroft** [pojome/elementor#528]
There're some beautiful image hover effects that could be applied to Elementor. I have tried using css but I think html structure needs to be changed to work it.

One of more beautiful and simple effects is this one, take a look at "What we offer" section, and hover images http://themes.muffingroup.com/be/webdesign/#
![image](https://cloud.githubusercontent.com/assets/20448621/18312465/4fb247ce-74e0-11e6-8fa0-ea60c2e45465.png)

In this example, image, title and link are fields inside Elementor image widget. It needs just an icon field and another to set additional effects like background color + grow, blur + grow, grayscale + grow, opacity + grow, so on.

There're other beautiful image hover effects here http://tympanus.net/Development/HoverEffectIdeas/index.html with demo and tutorial.

It would be wonderful if we could find these and other effects inside of Elementor along the time. Please think about it =)

**Comment by copen8** [comment]
I agree that hover effects would really a welcomed feature to  Elementor. I really hope that it will be added in the near future. 

=)

**Comment by KingYes** [comment]
We added in `1.5.0` Hover Effects.. For more examples go do: https://elementor.com/v150-hover-effect/
