### ISSUE TITLE
Feature request: Woocommerce attributes on Single Product Page

### ISSUE THREAD

**Issue by SebCardozo7** [pojome/elementor#5280]
Hi! First time here (on Github).

Just made an account to say that Woocommerce attributes are really needed for the Single Product Page.

Examples of product attributes: size of product (small, medium, large), dimensions of the product.

I think this would be a huge step for all the designers using Elementor and Woocommerce! 

(I know its early to ask it but I think it's really important to add it).

Thanks!

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
