### ISSUE TITLE
Feature Reinstatement: View Page Button

### ISSUE THREAD

**Issue by jaredgeddy** [pojome/elementor#5287]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Every time I go from editing a page to viewing a page it takes an additional 30 seconds to load a new tab of the website and navigate to the live page. This takes even longer if the page is not a part of the main navigation. This is a big waste of time that could be solved by a view page button that opens the page in a new tab. It used to be a part of the UI but was removed in previous versions.

**Describe the solution you'd like**
A button to quickly open the live page in a new tab in the Elementor page editor screen.

**Describe alternatives you've considered**
There is no substitute or alternative for this "feature". Either add it below "Exit to dashboard" or make it a selectable tab instead of preview. Just having a way to quickly go to the live page would save me so much time over the span of creating a website.

**Additional context**
I'm not a fan of using preview on new builds. Too many times I've spent countless minutes troubleshooting why I am not seeing my changes only to realize I'm looking at a preview, not the live version of the page. So I rarely use preview to view my pages, instead I use the live view and update as I build. There is not an quick way to currently get to this from the Elementor page editor screen. Even the url isn't easily copy/pasted and extra variables removed because it doesn't have the page's url in the editor screen's url. Instead I have to exit to dashboard, then click view page and wait for it to load. This is not effecient in the least bit and this feature used to be a part of the standard UI of Elementor. It's still a standard part of WordPress' UI. Please bring it back.

**Comment by fxaviers** [comment]
But, you just remove the "?preview_nonce=xxxxxxxxxx&preview=true" from the new tab open for preview.

**Comment by bainternet** [comment]
@jaredgeddy 

If it takes 30 seconds to load a page then something is wrong with your site/server and that's not normal.

as for the "Live page", If you update and publish the page, the preview shows the live page.

thanks.
