### ISSUE TITLE
Elementor 0.8.0 Missing Tablet Control

### ISSUE THREAD

**Issue by lunacroft** [pojome/elementor#529]
I've just have tested new version of Elementor and I think is missing a responsive column tablet control, like responsive mobile in this page:
![image](https://cloud.githubusercontent.com/assets/20448621/18311115/f1a7bc88-74d8-11e6-8a2b-e955fc1149e4.png)
![image](https://cloud.githubusercontent.com/assets/20448621/18311372/49b20d10-74da-11e6-82b4-aea255890fca.png)

So we can control 4 columns for desktop (or 25% wide - it's okay), 2 columns for tablet (or 50% wide) and 1 column for smartphone (or 100% wide - it's okay).

In this case I would put tablet version equal smartphone:![image](https://cloud.githubusercontent.com/assets/20448621/18311401/78445bb0-74da-11e6-946d-dfa2b406eb2d.png)
![image](https://cloud.githubusercontent.com/assets/20448621/18311447/aeec98b2-74da-11e6-8ee3-1bc11c67c111.png)

**Comment by arielk** [comment]
For now you can not control the columns in tablet separately. I guess we'll take care of columns on tablet in the next updates.

**Comment by lunacroft** [comment]
Thanks @arielk

**Comment by arielk** [comment]
I merged this issue with another issue #418 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.
