### ISSUE TITLE
Section menu z-index is very low (3) and often get's hidden behind a header

### ISSUE THREAD

**Issue by Jaska** [pojome/elementor#5291]
The blue menu that shows when editing a section gets hidden very easily if the section is right after a header (or any element) which usually has a higher z-index than 3.

Suggestion, just change:

.elementor-element>.elementor-element-overlay {
…
z-index: 3; (to)
z-index: 1111; (Or whatever you think is suitable.)
}

Note, this problem only came up with recent Elementor updates.

**Comment by bainternet** [comment]
@Jaska 

Thanks but with the right click and the navigator coming up we see no need for that.
