### ISSUE TITLE
After importing page on site A created using elementor plugin on site B - Images are not getting imported

### ISSUE THREAD

**Issue by kajalmasal** [pojome/elementor#5292]
1. Created the website with the help of elementor elements.

2. exported the data, replaced the link of images with the server links.

3. Imported that the on the other website.

4. all elements of elementor are imported properly expect the images. I can see the images in the customizer part of elementor but not on the page.

Please Help.

**Comment by jstillings1** [comment]
Try this [https://www.jeremiahstillings.net/laura-help-for-wordpress-org/](url) if that method does not work please reply.

**Comment by bainternet** [comment]
@kajalmasal 

Don't replace the images links,

Simply import and it will pull the images for you.
