### ISSUE TITLE
Better icons preview

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#5294]
**The icons are so small! and you have scroll for an hour if you have a lot of icons**
How can you even choose the right icon like that?
![2018-08-03 17 09 01](https://user-images.githubusercontent.com/23374215/43647318-fbfe43ba-973f-11e8-9bff-55c75537c2ad.gif)

**You have to change it to something like that:**
![screen shot 2018-08-03 at 17 04 17](https://user-images.githubusercontent.com/23374215/43647187-9107584e-973f-11e8-87da-9e7a2ba67043.png)

**And yes you can do it without effecting the performance!**
You can load it ajax style only when needed and you can find other simple creative ways to that if you care for your users experience!

**Comment by ArekZw** [comment]
+1

**Comment by bentalgad** [comment]
Thanks @ArekZw. please add thumbs up to the original comment so it would get more attention maybe... :)

**Comment by black-eye** [comment]
+1

**Comment by bentalgad** [comment]
Still Waiting for this!

**Comment by ArekZw** [comment]
@bentalgad - why you closed issue? Now it's not visible.

**Comment by bentalgad** [comment]
Sorry, didn't mean to :)

**Comment by shilo-ey** [comment]
I merged this issue with  #110 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
