### ISSUE TITLE
New Media Break Queries not responding as expected with Nav Menu

### ISSUE THREAD

**Issue by twerkema** [pojome/elementor#5295]
I'm very pleased with the new media query options in the settings. I wrongly expected the nav menu to respond to my new media queries. It does not. It still breaks at 1024 and 768, which I find confusing. Some things break at my new media query numbers but my nav menu breaks elsewhere. It makes designing confusing because now there are 4 break points I have to take into account. I'm sure this is just an oversight.

**Comment by jstillings1** [comment]
Menu is controlled by theme css and unless your using PRO and using the Header builder feature with the dynamic nav menu then you will not be loading the elementor custom break points.  Great reason to upgrade to pro and use the header builder.

**Comment by twerkema** [comment]
I am using pro. I'm using a header template. When it loads in a browser it does not use the theme nav breaks but uses the default.

**Comment by bainternet** [comment]
Please make sure to update Elementor Pro to version 2.1 and see if the issue still persists.

if it does feel free to reopen.

**Comment by twerkema** [comment]
Nav menu is fixed. Thanks very much. One other spot where the numbers appear not to match. It might be showing the right size in the preview pane or perhaps this is intentional. See attached screen shot. My break points are set to 500 for mobile and 850 for tablet. The preview options show 500 for tablet and 360 for mobile.

<img width="289" alt="screen shot 2018-08-07 at 11 36 15 am" src="https://user-images.githubusercontent.com/41759677/43786284-4924c788-9a36-11e8-861c-f56bf3d1dc1c.png">
