### ISSUE TITLE
Testimonial Carousel image dimensions

### ISSUE THREAD

**Issue by odedta** [pojome/elementor#5297]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
![screenshot_1](https://user-images.githubusercontent.com/13570550/43037084-97eb1a66-8d11-11e8-91e4-fa67e158f8ca.jpg)

Hello, how can I fix the image dimensions of the person who wrote the testimonial? Thanks.
I tried all the different settings, also some CSS, couldn't get the image to look as it does/should.
If you look at the original image I posted (imgur), you can see that the image in the Carousel is not the same. Thanks.

## Steps to reproduce
1. Create a Testimonial Carousel
2. Set the image to be aligned to the right
3. Upload an image [(https://imgur.com/a/sbEDCxP)](https://imgur.com/a/sbEDCxP)

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
[system-info-nivbook.odedta.com-24-07-2018.txt](https://github.com/pojome/elementor/files/2238133/system-info-nivbook.odedta.com-24-07-2018.txt)
</details>

**Comment by bainternet** [comment]
@odedta 


Your image size is set to 200 and in imgur the image is about 125.  So try there first.

**Comment by odedta** [comment]
![hello](https://media3.giphy.com/media/dzaUX7CAG0Ihi/200.gif)
