### ISSUE TITLE
Elementor page embedding

### ISSUE THREAD

**Issue by ikovalyov** [pojome/elementor#5298]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have elementor pro with elementor head, page and footer template. I have a link to this page in the bbpress. It's trying to load page and embed preview using "{page_url}/embed/#?secret=GTX4BzpkLX" iframe. Elementor loads full version there instead of preview one. It breaks the page layout.
Example: https://magic-forum.club/forums/topic/%D0%90%D1%82%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D1%8C/

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

I guess solution is fallback to default layout if embed option exist

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
