### ISSUE TITLE
Double Scrollbars bug

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#530]
The latest release is causing double scrollbars within the editor.

This is being caused by "overflow:hidden" being left out of the style class .elementor-device-desktop #elementor-preview-responsive-wrapper

**Comment by arielk** [comment]
Which browser? 
Can you please upload screenshot with the problem?

**Comment by Pagester** [comment]
Chrome v52 and Firefox v48

Currently displaying on 16 separate client installations in both browsers.

Will upload screenshot shortly once I'm back at my desktop

**Comment by Pagester** [comment]
Attached screenshots of Firefox and Chrome from our sandbox install
![chrome-double-scroll-bars](https://cloud.githubusercontent.com/assets/20524372/18320592/7434ba90-7522-11e6-915c-603203213309.jpg)
![firefox-double-scroll-bars](https://cloud.githubusercontent.com/assets/20524372/18320593/743648b0-7522-11e6-80b1-454bf6fe515e.jpg)
