### ISSUE TITLE
Not working {{CURRENT_ITEM}} CSS selectors

### ISSUE THREAD

**Issue by shaddam** [pojome/elementor#5300]
Hello 
I fill all requirement for post new issue. 
Now working {{CURRENT_ITEM}} CSS selectors in repeater field . 
this is my code: '{{WRAPPER}} {{CURRENT_ITEM}} .single-slide h2' => 'background-color: {{VALUE}};'

When i use this code :  '{{WRAPPER}} .single-slide h2' => 'background-color: {{VALUE}};'
than working . 

But it's not my solution . I want to pass different value each ( single-slide h2 )  in repeater field . 

Please solve the issue . 

Thanks

**Comment by bainternet** [comment]
@shaddam 

I need to see the whole code for the repeater in order to help.
