### ISSUE TITLE
Include HTML option in "Actions after submitting" of the Elementor Pro form widget

### ISSUE THREAD

**Issue by GGustavoGuerra** [pojome/elementor#5301]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The inability to use other email marketing services not yet integrated into Elementor Pro via API, webhook or Zapier.

**Describe the solution you'd like**
By adding this option, you could paste the form HTML code of your email marketing service, needing to only configure the field IDs in Elementor Pro, without the need for native or third-party integration.

**Describe alternatives you've considered**
I found no viable alternative to improve the Elementor Pro Form widget. Although this function can be used in page builder plugins competitors such as OptimizePress.

**Additional context**
The purpose of the HTML option is to ensure that any email marketing service can be integrated with Elementor Pro, allowing you to use the plugin to create lead capture pages with the form widget itself.

**Comment by bainternet** [comment]
@GGustavoGuerra 

You can use the HTML Widget for that. Or am I missing the point?

**Comment by GGustavoGuerra** [comment]
@bainternet 

With the HTML widget it is possible, however the embedded form has its own styles (or even in some cases), which breaks all the customization of the Elementor on the page.

The purpose of adding this option within the form widget is to be able to integrate any email marketing service, and still have 100% control over the form, being able to change its size, styles, colors, etc.

**Comment by bainternet** [comment]
@GGustavoGuerra 

If you would paste a from in Elementor you will not have the option to control or design it, it just doesn't work like that.

Your only option is to recreate the form with Elementor forms and either use the native webhook action or create a custom webhook handler to submit the form to the 3rd party service.

thanks.
