### ISSUE TITLE
Video Bookmarks

### ISSUE THREAD

**Issue by OldSchool80s** [pojome/elementor#5303]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm new to github stuff, so let's see if you even get this, since it's closed. :)

I like how you have the ability to set the start position of a video for Vimeo/YouTube.
(Known as a video bookmark)

What I'd like to be able to do (which I can do with the ProgressAlly plugin) is use a link or button to jump to certain sections of a video (in essence setting the play head at a certain time stamp.)

This is used for allowing people to jump to certain segments they want to see. Think of a long video, say 30 minutes and you want to have 3 parts that people can jump to instead of having to watch the whole video or scrubbing. So, you set up 3 separate text links/buttons that will move the to timestamp selected for each.

34 Minute video of Glass Blowing class:
See glass preparation [Click Here] (say starts at 7:22 into video)
See glass shaping techniques [Click Here] (say starts at 14:01 into video)
See glass cool down techniques [Click Here] (say starts at 23:00 into video)

**Additional context**
I had added this to comment on to this related Github:
New: Added start/end controls for Video widget (#3565)
https://github.com/pojome/elementor/issues/3565

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
