### ISSUE TITLE
condition not working in repeater field from parent selector 

### ISSUE THREAD

**Issue by shaddam** [pojome/elementor#5304]
I want use condition in repeater field from parent selector . 
e.g. my parent field has 2 item in select type : 
1. Layout One
2. Layout Two. 

In my repeater field has a image type . I want when select ( Layout 2 ) then image upload  will be visible in only Layout 2 and it will be hide Layout 1 

        $this->add_control(
            'slider_layout',
            [
                'label' => __( 'Slider Layout', 'jantrik' ),
                'type' => Controls_Manager::SELECT,
                'default' => 1,
                'options' => [
                    1 => __( 'Layout One', 'jantrik' ),
                    2 => __( 'Layout Two', 'jantrik' ),
                ]
            ]
        );  
        $repeater = new Repeater();
            $repeater->add_control(
                'slide_image',
                [
                    'label' => __( 'Background Image', 'jantrik' ),
					'condition' => [
	                    'slider_layout' => '2',
	                ],
                    'type' => Controls_Manager::MEDIA,
                    'default' => [
                        'url' => Utils::get_placeholder_image_src(),
                    ],
                ]
            ); 

Please help me how can i fix it  ?

Thanks

**Comment by bainternet** [comment]
@shaddam 

Make sure the values are the same.

in `slider_layout` the value is an integer and in the condition its a string.
