### ISSUE TITLE
Javascript tracking of form submissions

### ISSUE THREAD

**Issue by tomaswisten** [pojome/elementor#5305]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
After a form is submitted, I'd like to trigger a custom javascript event. For example, for tracking a subscription, lead generation or sale, and report it to Google Analytics and Facebook.

**Describe the solution you'd like**
"Actions After Submit" should include the option "Custom Javascript event".

**Describe alternatives you've considered**
I considered using the redirect URL for setting a goal instead of using Javascript events, but it's far less stable and precise (the thank you page could be visited several times, bookmarked by the visitor, displayed by web editors making changes to it, etc). 

**Additional context**
It would be great if Wordpress users (maybe certain roles) could be excluded, so web editors don't pollute the tracking. It would also be great to see a log of the tracking events for debugging.

Thanks for a great product!

**Comment by bainternet** [comment]
@tomaswisten 

The Elementor Pro form triggers a custom JavaScript event named `submit_success` so you can to your tracking or anything else you want on that event
```JS
//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	$( document ).on('submit_success', function(){
		// form has been submitted do your thing
	});
});
```

As for excluding users form tracking, not really realted to Elementor Since elementor has no tracking.

Thanks.

**Comment by IanJSaul** [comment]
For anyone banging their head against this in the future like I was, the following code inserted into custom HTML element, or into a GTM tag on All Pages, will result in a correct push to the Data Layer, and you can name the forms separately (if you put this after the form), and then track WHICH form is leading to conversion actions.

Now, if someone could help me figure out a way to pull the Form Name or CSS ID and insert it as a data layer variable I can then feed to Analytics, that would be amazing.

<script type="text/javascript">
 jQuery(document).ready(function($) {
   jQuery(document).on("submit_success", function(event, formID) {
     window.dataLayer = window.dataLayer || [];
     window.dataLayer.push({
       event: "formSubmission",
       formID: "#Test Form"
     });
   });
 });
</script>

And as I'm not 100% sure what I'm doing, the closest I've managed to get the elementor-form id as a variable is this (which does not work)...

function() {
  var formName = {{elementor-form}}.querySelector('#id');
  return field ? field.value : undefined;
}

**Comment by jpacey** [comment]
@IanJSaul did you ever have any luck getting the form id into the data layer? I'm currently struggling to find a way to differentiate between different types of form submission in GTM.

Thanks

**Comment by timanrebel** [comment]
The get the ID of the form that was submitted, use the following code:

```//The event is submit_success so you can catch it for example:
jQuery( document ).ready(function( $ ){
	jQuery( document ).on('submit_success', function(evt) {
		// form has been submitted do your thing
                console.log(evt.target.id);
                // for example, to submit an event to Google Analytics
                ga('send', 'event', evt.target.id, 'Submit);
	});
});```

**Comment by 9mm** [comment]
For anyone not using pro:

```
jQuery('form[name="Quote"]').submit(function() {
  gtag('event', 'conversion', {'send_to': 'xxxxx'});
  fbq('track', 'Lead');
});
```

**Comment by sbontheroad** [comment]
Hi, can someone please tell me where you are placing this code when using elementor? Are you putting it in the custom code section? Or where are you placing it or how are you inserting it? Thank you very much for any feedback. I'm trying to figure out the best practices for where to put the tracking code/custom code in elementor.
