### ISSUE TITLE
Wordpress hooks for handling form submissions

### ISSUE THREAD

**Issue by tomaswisten** [pojome/elementor#5306]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When developing custom plugins for Wordpress, I need to use the data submitted by Elementor forms.

**Describe the solution you'd like**
After a form is submitted, I'd like the data to be handled by other Wordpress functions, using a Wordpress hook.  

**Describe alternatives you've considered**
Generating the form from scratch inside my own plugins, but that's quite time-consuming.

**Comment by bainternet** [comment]
@tomaswisten 

there are hooks,
the docs need a little update but you can read here and see [many examples](https://github.com/pojome/elementor/issues?q=label%3Acomponent%2Fforms%2Factions+is%3Aclosed)
