### ISSUE TITLE
Print name of template you choose to delete to prevent wrongful deletion of templates

### ISSUE THREAD

**Issue by bendqh** [pojome/elementor#5309]
Print name of template you choose to delete to prevent wrongful deletion of templates.

When you delete templates you don't see the name of the template you asked to delete and this could lead to deleting the wrong templates (which cannot be recycled by Elementor).

Please print the name of the template scheduled for deletion.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Not really sure where you are trying to the delete the template from, inside the Editor, from the WordPress Dashboard?

**Comment by bendqh** [comment]
From inside Elementor: From the modal in which you manage templates.
