### ISSUE TITLE
Image Box Element <a> element CSS bug

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#531]
The image box element, when you set a custom font colour and add a link, the custom font colour is ignored as there is no css style referencing the <a> element of the class for the widget. So it default to blue or the theme default

The below class controls the font settings applied to the Title of the image element without a link, to render this class when a link is added you need to add an additional style for the <a> 

Current:
.elementor-image-box-content .elementor-image-box-title 

Required:
.elementor-image-box-content .elementor-image-box-title a

**Comment by arielk** [comment]
Thanks for your reporting!

**Comment by mmichalak2** [comment]
I am having the same issue. how do I fix this issue. Where would I add the class?

**Comment by DaraEWien** [comment]
OH wow! thanks. When I put a link in the typestyle changes and I have spent endless hours trying to find out why. This is the CSS for that?
