### ISSUE TITLE
Set a background slider

### ISSUE THREAD

**Issue by Vexander** [pojome/elementor#5310]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The ability to add an image slider as a background to an Elementor section, row or column both normal and full screen
**Describe the solution you'd like**
I would like to be able to set a section, row or column to have an image slider as a background.  This slider should be responsive and be able to be set to full screen

**Describe alternatives you've considered**
CSS and negative margins

**Additional context**

**Comment by bentalgad** [comment]
+1 This would be wonderful!

**Comment by silvioghedin** [comment]
+1

**Comment by arielk** [comment]
I merged this issue with another issue #2898 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
