### ISSUE TITLE
Safari not rendering all options

### ISSUE THREAD

**Issue by ianstudio** [pojome/elementor#5311]
I just realized quite a bit of the "eye-candy designy" work I put into creating a lovely website this past week, with new stuff like blend-mode, is pretty much lost on Safari.. Example: background hover animation "kills"  border-radius settings and blend-mode does not get applied to Call to action blocks (so I end up with flat colors instead of colored images), easily resolved by removing the hover animation.. but still sad to feel one has a toolbox and is restricted as not all tools function properly or can be trusted (I don't especially enjoy feeling like a Beta tester..). From now on I will alway use Safari.. if it works in Safari it works elsewhere, the other way around (say using Chrome to dev) is not so true.

**Comment by bainternet** [comment]
@ianstudio 


Is there any specific issue you want us to help/fix/do here?

**Comment by ianstudio** [comment]
Look more closely at Safari compatibility I guess..

**Comment by khayford** [comment]
+1 Border radius does not work in safari

**Comment by bainternet** [comment]
ok, thanks.

If we miss something and you do happen to spot it please feel free to let us know and we'll correct what we can.

**Comment by roykamen** [comment]
I now have an issue with Safari or iPhone not rendering anything past the menu and background video.
www.marinakamen.com
works on Chrome Firefox and Opera
