### ISSUE TITLE
swiper.min.js.map 404 error in Elementor

### ISSUE THREAD

**Issue by ZedProg** [pojome/elementor#5313]
When checked in fiddler, i found a 404 error which states the file swiper.min.js.map is missing in my site.

The page i checked: http://travelmeout.com/darjeeling-the-queen-of-hill-stations/
The missing file path: http://travelmeout.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map

System Info: WordPress 4.9.8 / Elementor 2.1.6 / Elementor Pro 2.0.18

**Comment by bainternet** [comment]
@ZedProg 

We removed the mapping so the file should be called anymore. 
Make sure you clear your caches server and client side.

**Comment by askwpgirl** [comment]
I am on Elementor 2.9.3 and still see the 404 /wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map This is a new site, so no cache files would apply in this case. It's causing issues and needs to be resolved.

**Comment by heyfletch** [comment]
+1 this is an issue in 2.9.4.  uploading [swiper.min.js.map](https://github.com/elementor/elementor/issues/5151) stops the error messages, for now.

**Comment by tonydehnke** [comment]
@bainternet - Still seeing this issue today in 3.27.2

<img width="623" alt="Image" src="https://github.com/user-attachments/assets/eed8aa40-bd38-45d9-9aaa-61d17e0fa8b7" />

**Comment by trinermedia** [comment]
@bainternet – Still seeing this issue today in 3.31.3

Caches cleared.

System Info: WordPress 6.8.2 / Elementor 3.31.5 / Elementor Pro 3.31.3

**Comment by cirrus3d** [comment]
Still seeing this after the latest update to 3.32
/wp-content/plugins/elementor/assets/lib/swiper/v8/swiper-bundle.min.js.map

**Comment by SV-Zanshin** [comment]
I'm still getting this error with Version 3.34.1. This has now been open for over 5 years...
