### ISSUE TITLE
Elementor load all font weights on the page if we use custom weight from the widgets.

### ISSUE THREAD

**Issue by aniljadhavmca** [pojome/elementor#5315]
If use font-family from the elementor widgets with some of it's weight, It loads all font weights on the pages which is not required, It makes a heavy request while loading the HTML on front-end.

https://fonts.googleapis.com/css?family=Poppins%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&#038;

Step to Reproduce:

1) Create a new blank page
2) Drag any widgets from the list and select font family with wight.
2) Now if CTR+U your page you will see font requiest like above

This should like if use font-weight 100.

https://fonts.googleapis.com/css?family=Poppins%3A100%2C400italic;ver=4.9.8

**Comment by bainternet** [comment]
@aniljadhavmca 

For now see: https://github.com/pojome/elementor/issues/3545#issuecomment-367622129

Other than that,
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.
