### ISSUE TITLE
WooCommerce: Filter by name (wildcard)

### ISSUE THREAD

**Issue by Henry00IS** [pojome/elementor#5316]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Ability to filter products by name.

**Describe the solution you'd like**
I am working on a page that has alphabetical sections "A", "B", "C", ... and it would be nice if there was a search string filter of sorts where I could specify "A*" to find all products that start with an A.

**Describe alternatives you've considered**
I have created 26 categories, one for each character in the alphabet in order to get the functionality I need.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
