### ISSUE TITLE
Save Section as Global

### ISSUE THREAD

**Issue by adrianrosca** [pojome/elementor#5317]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I often create templates that only consist of layout + ACF fields.

If a section could be global then it could be populated with ACF fields and work as a general top section for e.g. all blog posts for an entire site.

**Describe the solution you'd like**
When right clicking section, there should be "Save as global".

**Describe alternatives you've considered**
Now I must save a section as a template an replace on all pages if the "global" section template changes.

**Additional context**

**Comment by willcitizen** [comment]
All templates are effectively global.

Instead of inserting the template From the library use the template widget,
or the elementor shortcode to embed a template elsewhere in your design.

**Comment by twmcmahan** [comment]
Except they're not global, they're templates that can be changed per page.  What OP is asking for is a universal (global) that can be edited in one place and change throughout the site.

**Comment by adrianrosca** [comment]
@willcitizen Using the shortcode in a widget in a section wouldn’t be same thing.

If a section could be global, then also its own settings would be included.

**Comment by willcitizen** [comment]
It is the same thing.  If you create a template which can have any number of sections in it for more complex includes you can use either [elementor-template id="1234"] or the template widget from the pro section to display that template.  
This is not the same as inserting the template from the library and edits to that template will reflect in every version where you have embedded it.
You are right that you cannot make direct edits on the section in place, but the template widget does have an edit button which launches the embedded template in a new tab.
One problem here is that the template widget has to be wrapped in its own section and if you like to design 'from the outside in' with reusable layouts and dynamic content you can end up with a dizzying amount of unnecessary wrappers, which is possibly my biggest gripe about working with Elementor.

**Comment by adrianrosca** [comment]
@willcitizen Global sections would eliminate that wrapping that you describe. Which would be a clean solution for many situations.

Even if you don’t have dynamic content, like in my case.

You could have a composition of blocks that can be reused.

So I would still argue that global sections is not be the same as putting a shortcut widget into a section.

**Comment by willcitizen** [comment]
I agree.  I'm not a developer by trade actually a business analyst and using Elementor for my own side projects so I spend a lot of time disagreeing with developers about solution design :D I feel like Elementor is going through an awkward transition at the moment with the addition of the Themebuilder functionality.  What started as an incredible tool for casual enthusiasts to throw together good looking sites with no real understanding of the underlying code has grown into something that's very close to being a really powerful rapid development tool for probably almost any project when you start combining it with things like ACF.
However that dumbing down of the underlying code to make it easy to use is also a stumbling block for power users who *want* control of the underlying structures, how wrappers get output, or fine tuning flexbox behaviour.
I guess that this is the price you pay for adopting a toolset which is very much under active development and why it's important that those of us who are pushing it the edge of it's capabilities and exploring the new features discuss our experiences here in the hopes that it helps the devs take the project in the right direction.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by aamirmotiwala4** [comment]
i found this step by step guide to save sections globally https://bit.ly/2Sy3UlB
