### ISSUE TITLE
Body Class input field: 

### ISSUE THREAD

**Issue by mrtolix** [pojome/elementor#5319]
I'm trying to create an input field for adding a class to the body \, so I successfully created the field in the page settings
```PHP
	$document->add_control(
		'Body_Class',
		[
			'label' => __( 'Body Class', 'plugin-name' ),
			'type' => Controls_Manager::TEXT,
			'placeholder' => __( 'Enter CSS Classes without .', 'plugin-name' ),
		]
	);
```

However, I'm having problems adding the field to the canvas and full-width template.

I think would be cool to have and explain this a little bit better, this would avoid the need of 3rd party plugins that arent a 100% compatible with elementor like ACF.

Keep doing a great work with elementor

**Comment by bainternet** [comment]
@mrtolix 

You need to hook into the `body_class` filter and add your classes, ex:

```PHP
add_filter( 'body_class', function( $classes ) {
	global $post;
	if ( ! is_singular() ) {
		return $classes;
	}

	$document = \Elementor\Plugin::$instance->documents->get( $post->ID );
	if ( $document ) {
		$my_classes = $document->get_settings( 'Body_Class' );
		if ( $my_classes ) {
			$classes[] = $my_classes;
		}
	}
	return $classes;
} );
```
