### ISSUE TITLE
Templates display conditions "Child of (recursive)"

### ISSUE THREAD

**Issue by sco2tbold** [pojome/elementor#5321]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

When saving a Elementor-Footer-Template I can choose "Singular">"Child of" in the display conditions. This way the footer is only displayed on direct child pages from the page I choose. 

It would be great to have a option "Child of (recursive)" with which the condition reaches down the entire branch of pages. 

Example page structure: 
`Home`
`Products`
`- Product A`
`-- References`
`--- Case Study A`
`--- Case Study B`
`-- Modules`
`- Product B`
`- Product C`
`About us`

I want the footer template to appear on all product pages and all of their subpages down to the Case Studies. With the current implementation of "Singular">"Child of">"Products" its only displayed on the pages "Product A", "Product B" and "Product C". Not on the pages "Refernces", "Modules", "Case Study A" and "Case Study B".

**Comment by kristiangl** [comment]
Seconded. This seems relatively easy to implement, but would make a massive difference for clients.

**Comment by BrookeRaraAvis** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by MrJoax** [comment]
+1

**Comment by paradisiacor** [comment]
+1
