### ISSUE TITLE
Call REST API

### ISSUE THREAD

**Issue by Riko37** [pojome/elementor#5323]
Hi,
After speaking with the support I understood there is no option to call a REST service?
For example, I want to have few input text fields and a 'SEND' button, that will call an external REST service, and return a Json. The response will be parsed and populate an OutputText field.
It looks to me really straight foreword, 
If it's really not yet supported by Elementor, how can I achieve that, and can you add this feature?

Riko

**Comment by bainternet** [comment]
@Riko37 

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.


Not really clear what you are trying to do or how Elementor is even related here?
