### ISSUE TITLE
Slide Widget pulling from posts

### ISSUE THREAD

**Issue by carmdq** [pojome/elementor#5326]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I'd like to have a Slider widget that pulls dynamically from posts but also has a text field and a clickable button like the current Widget slider.

**Describe the solution you'd like**

The current Slider widget requires the user to manually go through each slide and modify it, Having a dynamic Slider that pulls from a post would allow the less tech savvy users to modify an image from a post without the risk of modifying anything from the layout.

**Describe alternatives you've considered**

 I managed to create and export a template containing: a portfolio widget, a Heading, a Text Editor and a Button to replicate the look of the Slides widget. However, I was advised by the support team to skip this solution, since the amount of negative margins needed and overall CSS tinkering, would probably cause many layout issues,

**Additional context**

The idea for this, came from the request of having a featured product section for a site, that could easily be updated within the Wordpress interface.

**Comment by willcitizen** [comment]
Busy with this exact functionality at present and finding myself frustrated by noticing how many widgets, even in the pro category have not had dynamic content implemented yet.

Honestly Elementor is fantastic in many respects, but working on the edge of current pro functionality and actually trying to use the themebuilder capabilities feels like being a fat guy at a fashion show.  Everything looks amazing, but nothing actually fits your needs so you end up wearing clothes you made yourself out of old sheets.

**Comment by bainternet** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
