### ISSUE TITLE
Encoding Emails

### ISSUE THREAD

**Issue by deanovo** [pojome/elementor#5328]
Hi, I was told to post this here. In my websites I usually add [email] [/email] around email addresses to stop them being harvested.

I have this code either in functions.php or in a plugin...
```PHP
function wpcodex_hide_email_shortcode( $atts , $content = null ) {
if ( ! is_email( $content ) ) {
return;
}

return '<a href="mailto:' . antispambot( $content ) . '">' . antispambot( $content ) . '</a>';
}
add_shortcode( 'email', 'wpcodex_hide_email_shortcode' );

add_filter( 'widget_text', 'shortcode_unautop' );
add_filter( 'widget_text', 'do_shortcode' );
```
However it doesn't work when I create an icon list. I'm using the icon list to create a section above a main header showing telephone number, email address and opening times. I know I could do this via text/html in a widget but I'm trying to keep everything consistent for my clients to be able to edit if need be. 

The code above works for content within the text editor in Elementor.

Thanks

**Comment by bainternet** [comment]
@deanovo 

The above code is a shortcode handler, which means it will only work where shortcodes are supported.

This part:

```PHP
add_filter( 'widget_text', 'shortcode_unautop' );
add_filter( 'widget_text', 'do_shortcode' );
```
has no effect on elementor widget only on WordPress native widgets.

For now you can just encode the email address manually using a tool like this: http://ctrlq.org/encode/

**Comment by deanovo** [comment]
Thank you!

**Comment by reachdigitalaus** [comment]
Hi guys, was there ever a clean solution to encode emails? I tries using the encoded email in the contact URL option but does not work. Any ideas?
