### ISSUE TITLE
Heading widget HTML Tag setting

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#533]
When using the Heading widget, how are the HTML Tag and Size settings supposed to work? If all my theme styles are passed through, why doesn't choosing H2 look different than choosing H5? (see images) I can't find any documentation.

I've already set all my size and color preferences for fonts including H1-H6 in my theme: Dynamik (Genesis child theme.) I also have disabled styles in Elementor settings.

<img width="633" alt="disable styles" src="https://cloud.githubusercontent.com/assets/974442/18325132/e44d2eda-74f4-11e6-8e6c-247bd75f2cc7.png">

-------------

<img width="668" alt="h2" src="https://cloud.githubusercontent.com/assets/974442/18325130/e4499874-74f4-11e6-977f-4245eed4bc17.png">

-------------

<img width="660" alt="h5" src="https://cloud.githubusercontent.com/assets/974442/18325131/e44ba25e-74f4-11e6-9c40-8eb318ed176a.png">

**UPDATE**

I don't see a way to turn off the size dropdown. Perhaps that is getting in the way of the theme styles passing through? I fixed my situation by adding these custom styles that required including important!, but it seems like a bug. 

```
/* Type Heading Styles ---------------------- */

h1 {
font-family: 'Crimson Text';
font-size: 30px !important; 
  font-style: normal;
  font-weight: 400;
}

h2 {
font-family: 'Crimson Text';
font-size: 24px !important; 
  font-style: normal;
  font-weight: 400;
}

h3 {
font-family: 'Crimson Text';
font-size: 20px !important; 
  font-style: normal;
  font-weight: 400;
}

h4 {
font-family: 'Crimson Text';
font-size: 18px !important; 
  font-style: italic;
  font-weight: 400;
}

h5 {
font-family: 'Crimson Text';
font-size: 16px !important;
  font-style: normal;
  font-weight: 700;
}

h6 {
font-size: 14px !important;
font-variant: small-caps;
}

```

**Comment by arielk** [comment]
The size of the heading come from the "size" control in the widget.

We'll fix it by adding a new size option: Inherit

**Comment by mizejewski** [comment]
Yes, it's nice that the user can just set a size locally for that widget, if desired. But if H1-H6 are chosen, I think the expectation is that it will use a central stylesheet that can be updated in a single place. 

Sounds like the new size option: Inherit will fix? I'm not quite clear on how it would work. Happy to test though.
