### ISSUE TITLE
Add adaptive height to the carousel slider

### ISSUE THREAD

**Issue by mrtolix** [pojome/elementor#5330]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When I create a testimonial slideshow takes the size of the largest one and leave white space on smaller slides

**Describe the solution you'd like**
Like Slick.JS you can add a parameter of adaptive height to change the height depending of the slide height

**Describe alternatives you've considered**
Add adaptive height switch to the module.

**Comment by ramonztro** [comment]
The funny thing is their slider is built with slick.js. On the matter, I agree it should allow adaptive height.

**Comment by mrtolix** [comment]
I was expecting that, just a switch in the module would solve the issue

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


for now, you can simply get an instance of Slick slider and set any option you want, eg:

```JS
// Get instance
var slider = jQuery('.elementor-slides').slick('getSlick');
// Set option
slider. slickSetOption( 'adaptiveHeight', true );
```
Thanks for the feedback.

**Comment by andpiechota** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> for now, you can simply get an instance of Slick slider and set any option you want, eg:
> 
> ```js
> // Get instance
> var slider = jQuery('.elementor-slides').slick('getSlick');
> // Set option
> slider. slickSetOption( 'adaptiveHeight', true );
> ```
> 
> Thanks for the feedback.

Hello! Thanks for the advice. Could you possibly show how to implement that into the Wordpress page?
