### ISSUE TITLE
After 2.1.0 update, posts widget in pro version started skipping the first post.

### ISSUE THREAD

**Issue by relima** [pojome/elementor#5332]
It is pretty much what the title says. All of the posts widgets I am using on my site started showing nothing on the place where first post was supposed to be present.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
