### ISSUE TITLE
Custom Page Templates - Preview not updating

### ISSUE THREAD

**Issue by asadkn** [pojome/elementor#5333]
## Description

Changing page template  ("Page Layout") in Elementor Settings is not reflecting on the preview pane. It does refresh but comes back with the page template originally set.

Note: Works fine for Elementor's built-in page templates "Elementor Canvas" and "Elementor Full Width" but not for any other page templates. 

## Steps to reproduce

1. Add a custom page template in the theme.
2. Go to page settings in Elementor (cog icon). Select the custom page template in "Page Layout".
3. Notice that everything refreshes, but it's not the right page. It goes back to default or whatever was originally set. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Tried on fresh WP install on LAMP, and multiple remote environments on PHP 5.6 and 7.0.x.

**Comment by bainternet** [comment]
@asadkn 

We can't replicate the issue. 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by pegues** [comment]
I have this same issue. During the current, active preview session for editing a page, I'll switch to a different page template. The elementor preview does not update with the newly selected page template. After I hit update then refresh the page, the newly selected page template from the previous previous session now shows up. But the problem remains, such that if I now switch to another custom page template or even default, the elementor preview does not reflect the change until I hit the green update button to save my change, then refresh the page.
