### ISSUE TITLE
Hook for after Meta Data in Template

### ISSUE THREAD

**Issue by NateUnbridledWorld** [pojome/elementor#5334]
I am using Elementor Pro with WP Page Builder Framework Theme. I coded some actions in the functions.php to display certain info below the metadata (publishing date) through tags. I did this by using my theme's hooks and it worked perfectly. However, when I created a blog post template with Elementor, these are obviously gone now because Elementor uses its own metadata field. I checked the hooks: https://wp-pagebuilderframework.com/docs/hooks/
But I cannot find one that is actually working for me. It's also a bit overwhelming... so many... Anyways, I want it to be displayed either above the text content (blog post) OR - preferably - below the metadata (Post Info, date). Can anyone help me out?

When I asked the Elementor Support I was sent here...

**Comment by bainternet** [comment]
@NateUnbridledWorld 

>Anyways, I want it to be displayed either above the text content (blog post) OR - preferably - below the metadata (Post Info, date)

I have no way of understanding what you mean.

can you explain a little, what you are trying to do? what have you tried?

**Comment by NateUnbridledWorld** [comment]
Sorry about that! I'll try to explain it better this time.

I used this code in my functions.php:
function affiliate_disclosure() {
	if ( has_tag('affiliate') ) {
    echo '<div class="affiliatebox">This article contains affiliate links. If you click them and book or purchase something through them, I will receive a small commission. No extra costs for you, but you would support this blog with your action. Read more in my <a href="/en/affiliate/">Affiliate & Ads Disclosure</a>!</div>'; 
	}
}
add_action( 'wpbf_after_article_meta', 'affiliate_disclosure' );

wpbf_after_article_meta is the hook of my theme. You can take a look here to see how amazingly straightforward this works: https://wp-pagebuilderframework.com/docs/hooks/ - To see how it looks like on the website, check this photo:
![screenshot 135](https://user-images.githubusercontent.com/42195348/43841003-f850ac40-9ad6-11e8-9acc-70945e378c17.png)

When I created a template for blog posts it uses the "Blog Info" from Elementor and not the theme's meta. Therefore, this code doesn't work. 
![screenshot 134](https://user-images.githubusercontent.com/42195348/43841147-4f1f254c-9ad7-11e8-9fb4-b9a6bc171270.png)

I was wondering if there is an Elementor hook that I can use to make this happen. I hope this is now more understandable.

**Comment by NateUnbridledWorld** [comment]
Oh, sorry I just noticed that I haven't added the link of the Elementor php hooks in my first message, but instead my theme's. I meant that I checked this information: https://code.elementor.com/php-hooks/
But I couldn't figure out which one would work in this case. I tried a couple but it wouldn't work the way I want it as shown in the first screenshot (message above).

**Comment by bainternet** [comment]
@NateUnbridledWorld 

Thanks for the clarification,
There is no specific hook which is the one I should tell you to use because it really depends on your design and where you want to place the notice. 

A quick solution would be to wrap your code in a shortcode and place it in the template you have built with elementor in the place you want via the Shortcode Widget, eg:

```PHP
function affiliate_disclosure( $atts = [], $content = null, $tag = '' ) {
	if ( has_tag('affiliate') ) {
		return '<div class="affiliatebox">This article contains affiliate links. If you click them and book or purchase something through them, I will receive a small commission. No extra costs for you, but you would support this blog with your action. Read more in my <a href="/en/affiliate/">Affiliate & Ads Disclosure</a>!</div>'; 
	}
	return '';
}
add_shortcode( 'affiliate_disclosure', 'affiliate_disclosure' );
```


and in your shortcode widget place `[affiliate_disclosure]`

thanks.
