### ISSUE TITLE
Can't edit shop page with elementor 2.0.18

### ISSUE THREAD

**Issue by amertatradn** [pojome/elementor#5336]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello everyone. I've installed the latest version of elementor pro and yet I can't edit shop page with it. I've seen this issue before but it was posted in 2016 and I assume the problem is resolved by now (also I've seen many youtube videos editing shop pages with elementor). I've tried all the guides on this matter except for changing my theme which is oceanwp because I know it is compatible with the plugin. However I can edit it when I deactivate woocommerce but as soon as I reactivate it the shop page goes back to the way it was before.
I would really appreciate if anyone could help I'm really in a pinch.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Update to Elementor Pro 2.1

**Comment by amertatradn** [comment]
@bainternet still can't edit
