### ISSUE TITLE
Pagination is not working properly for posts widget.

### ISSUE THREAD

**Issue by jainnidhi** [pojome/elementor#5340]
Hi,

I am little bit confused about the posts widget.

When I drag two posts widget with pagination on the same page and click on the next page then page is refresh.

Both the widgets show the posts of the next page.

All I want is that only the posts of the widget change which click on the pagination and not the other widget.

How can it be possible?

Thanks in advance!

**Comment by bainternet** [comment]
@jainnidhi 

This will only be possible once we implement #1284.

Thanks.

**Comment by vickistull** [comment]
I have the exact same problem.  I am using the post widget with different 4 different tags on the same page.  The page looks great but when I hit the pagination button on the bottom of one it changes the pages on all the post widgets for the different tags.  I guess I don't understand what "this will only be possible once we implement #1284"  .  Is that a new update to elementor pro or what?  and when is it happening?
