### ISSUE TITLE
Search and Replace for elementor Pages

### ISSUE THREAD

**Issue by ivex001** [pojome/elementor#5343]
Hi,
I read somewhere here that i could use a plugin called Search & Replace to search on elementor pages because they are saved serialized on db. But i try it but it didn't found anything. Why?

**Comment by BenBroide** [comment]
Which string you're trying to search and replace?

**Comment by ivex001** [comment]
I was searching for "Rua da moeda" tp replace with "Rua da Moeda" (Just UpperCase). Its an address present in every page on the website and i didn't want to go through changing them one by one in two different language.

**Comment by ivex001** [comment]
Scratch that please. It worked now, i really don't know why.
see: https://drive.google.com/file/d/1CizWaM92vypviKA9IXdrEn3ImgxqgU31/view?usp=sharing

thanks anyway

**Comment by arielk** [comment]
We do not keep the data as serialized we use JSON, So please use with a tool that supports this method. Unfortunately, I don't have a specific plugin to recommend you, but you can ask about it in the Elementor community on Facebook.

Thanks
