### ISSUE TITLE
Animated Headline Broken with Pro 2.1.0 update

### ISSUE THREAD

**Issue by cavalierlife** [pojome/elementor#5345]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Animated Headlines are no longer working with the new 2.1.0 update. The highlighted words disappear on the front end. If you edit them on the back end, it fools you into thinking it's fixed, as the preview suddenly starts showing the highlighted words, but as soon as you leave the editor, it disappears again.

## Steps to reproduce

Look at an animated headline that used to work. Notice that the highlighted words are blank now.
Edit the animated headline, making any small change. Notice that it looks fixed. Save and leave.
Notice the highlighted words are blank again.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 10.0.34
	PHP Version: 7.1.20
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://litloudlife.com
	Home URL: https://litloudlife.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Indiana/Tell_City
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.1.3
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36

== Active Plugins ==
	Better Search Replace
		Version: 1.3.2
		Author: Delicious Brains

	Central Color Palette
		Version: 1.12.5
		Author: Gáravo

	Classic Editor
		Version: 0.4
		Author: WordPress Contributors

	Code Snippets
		Version: 2.11.0
		Author: Shea Bunge

	DX Delete Attached Media
		Version: 1.0
		Author: nofearinc

	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.0
		Author: Elementor.com

	GP Premium
		Version: 1.6.2
		Author: Tom Usborne

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	Lightweight Social Icons
		Version: 1.0.1
		Author: Thomas Usborne

	Login LockDown
		Version: v1.7.1
		Author: Michael VanDeMar

	ManageWP - Worker
		Version: 4.6.1
		Author: ManageWP

	Post Snippets
		Version: 3.0.5
		Author: David de Boer

	PW WooCommerce Bulk Edit
		Version: 2.47
		Author: Pimwick, LLC

	Sassy Social Share
		Version: 3.2.3
		Author: Team Heateor

	Simple CSS
		Version: 1.1
		Author: Tom Usborne

	Simple Lightbox
		Version: 2.7.0
		Author: Archetyped

	WooCommerce
		Version: 3.4.4
		Author: Automattic

	WooCommerce - Store Toolkit
		Version: 1.9.2
		Author: Visser Labs

	WooCommerce Cloak Affiliate Links
		Version: 1.0.15
		Author: datafeedr.com

	WooCommerce Predictive Search LITE
		Version: 4.2.1
		Author: a3rev Software

	WooCommerce Product Categories Selection
		Version: 2.0
		Author: PluginForage.com

	Woo Title Limit
		Version: 1.4.1
		Author: Dima W.

	WP Force SSL
		Version: 1.3
		Author: Kostas Vrouvas

	WP Show Posts
		Version: 1.1.3
		Author: Tom Usborne

	Yoast SEO
		Version: 7.9.1
		Author: Team Yoast


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP


== Debug ==
	Errors: There are no errors to display
				
```
</details>

**Comment by BrookeRaraAvis** [comment]
![animated](https://user-images.githubusercontent.com/1435355/43855975-2e8969d0-9b15-11e8-83b5-3f939c122971.gif)

**Comment by deckerweb** [comment]
I can verify it's broken with Pro 2.1.0
When tweaking in Elementor it shows in the live editor and the panel preview - but not live on the site.

**Comment by whwi** [comment]
I can verify it's broken with Pro 2.1.0

**Comment by bainternet** [comment]
Thanks for reporting should be fixed in next update.

**Comment by GGSimpson21** [comment]
This appears still broken

**Comment by GGSimpson21** [comment]
> Thanks for reporting should be fixed in next update.

**Comment by GGSimpson21** [comment]
never mind - sorry - a conflict it seems with another plugin.. if I figure out which one I will report back
