### ISSUE TITLE
Flip Box Back side overlaid Front side when hovering

### ISSUE THREAD

**Issue by siro83** [pojome/elementor#5348]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The front of the Flibox remains visible when the back is to be displayed when the effect slide is used

## Steps to reproduce

- Create a flipbox with front and back side
- Add a text on both sides
- Set effect to slide

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by peterbujok** [comment]
I am having this same issue, please let me know if there is a temporary patch.

**Comment by peterbujok** [comment]
Thank you, this has been resolved in the last update.
