### ISSUE TITLE
Elementor Pro with Astra Pro Issues

### ISSUE THREAD

**Issue by coloradoweb** [pojome/elementor#5349]
TIP HERE!

If you use Astra (theme) Pro Modules, you might get conflicts that cause style or formatting errors like column widths not displaying correctly.

All the information I could find indicated that Elementor and the Astra theme are 100% compatible. This is not so, if you enable the Astra Pro Modules.

I was using the Archive Template in Elementor Pro, and columns of posts were hopelessly squished. I finally discovered that the CSS inserted by the Blog Pro Module in Astra Pro (located in “Astra Options”) which I had enabled, was overriding the Elementor Template CSS.

Everything worked fine again once I disabled the Blog Pro Module in the Astra Options.

There are a number of other such Modules in Astra Pro which I imagine could cause similar formatting problems if enabled and used along with Elementor Templates.

I hope this helps someone else!

**Comment by midihead7** [comment]
I too have been having issues with columns being squished with Astra Pro active along with Elementor 2.1.0 and 2.1.1. In my case, the Elementor Pro Products widget columns are badly squished. I have ticket #94246 open with Astra Support to try to get this issue addressed as soon as possible. They provided this CSS to temporarily fix my squishing issues:

`.woocommerce.columns-5 ul.products li.product {
width: 100%;
}`

This, of course, is a band-aid fix and doesn't really correct the problem with Astra Pro. I'm sure they'll get it resolved, hopefully very soon.

**Comment by bainternet** [comment]
@coloradoweb 

Thanks for that.
