### ISSUE TITLE
[bug] Image inside post module jumping after 2.1.0 update

### ISSUE THREAD

**Issue by Artneo7** [pojome/elementor#5350]
![jumping-blog-bug](https://user-images.githubusercontent.com/17693529/43872659-14866d82-9b59-11e8-84fc-f20c87005367.gif)

Link: https://novo.artneo.com.br/blog/

**Comment by SniffleValve** [comment]
This is not late loading CSS and it also is happening on the Portfolio widget,  It is an animation effect that was added in E Pro 2.1. This behavior is not present in 2.0.18.

Please provide a method to disable effect.

Cheers!
Lyle

**Comment by mcrowell** [comment]
The following CSS is a temp fix to disable the animation:

.elementor-posts-container.elementor-has-item-ratio .elementor-post__thumbnail img {
 height:auto;
 position:absolute;
 top:0;
 left:0;
 -webkit-transform:none;
 -ms-transform:none;
 transform:none;
}

**Comment by Artneo7** [comment]
Thanks @mcrowell! This disables the animation, but align the featured image to the left. I'm sure the Elementor team is already working on it too. Thank you again!

**Comment by arielk** [comment]
We just released a patch for this issue, please update!

Thanks

**Comment by footslogger** [comment]
fyi
https://wordpress.org/support/topic/elementor-2-1-7-incompatibility/
