### ISSUE TITLE
Typography (most likely group controls) popup not showing up

### ISSUE THREAD

**Issue by pmallek** [pojome/elementor#5351]
Hello,

Today i faced quiet interesting and tricky to debug issue when registering typography group control (most likely issue is related to group controls but i didn't make more tests).

Example:

```
$this->add_group_control(Group_Control_Typography::get_type(),
    [
        'label' => esc_html__('Typography', 'digital-atlas-core'),
        'name' => 'menu_main-menu_typography',
        'scheme' => Scheme_Typography::TYPOGRAPHY_1,
        'selector' => '{{WRAPPER}} .do-menu__link--main',
        'fields_options' => [
            'font_size' => [
                'default' => [
                    'unit' => 'px',
                    'size' => 20
                ]
            ],
            'line_height' => [
                'default' => [
                    'unit' => 'px',
                    'size' => 22
                ]
            ]
        ]
    ]
);
```
It seems like there is nothing interesting in this code. However when i try to activate popup it doesn't show up - popup is indeed opened however controls inside still have class "elementor-hidden-control".

Finally i discovered that the only difference between my other typography fields and this one is name attribute. Whole issue is caused by using "-" in name.

So in provided example: 
` 'name' => 'menu_main-menu_typography',`
doesn't work but when changed to:
` 'name' => 'menu_main_menu_typography',`
everything works like a charm.

Overall this behavior should be documented or fixed. Most likely fixed because it's very unexpected and will cause many developers to waste time:)

Have a nice day!

**Comment by bainternet** [comment]
@pmallek 

Thanks, I updated the docs.
https://developers.elementor.com/add-group-controls-to-widgets/
