### ISSUE TITLE
The preview could not be loaded

### ISSUE THREAD

**Issue by xperter** [pojome/elementor#5352]
After updating Elementor v2.1.6, I am unable to edit page with elementor. It show's 'Preview Could Not Be Loaded' message. I've tested in several server and the problem is same.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

https://docs.elementor.com/article/245-preview-could-not-be-loaded
