### ISSUE TITLE
Export template does not retain (child) template elements setting

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#5353]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I have a template with several "child" templates as regular "Template elements" in it.
I do export and later import and all Template elements exist BUT empty.
I did perform export all for all the templates PRIOR to this export-import operations

## Steps to reproduce
[I am extracting a site from WPMU to standalone site - the hard way due to other problems...]

1. Clean WP installation w/ 2017 theme. Elementor & Elementor Pro.
2. Export all templates to json & load in new site
2.1 Copy all upload dir. including Elementor's files from old to new.
3. WP export all (posts, media, etc...) &  import to new site
[BUG 1: elementor does not recognize the templates]
4. For each page in WPMU sub site 
4.1 Old site: Enter Elementor, Save page as template, Export to Json (works nice!)
4.2 New site: Enter page, Remove single sections (result of WP import, see BUG 1)
                     Load json template & add to page

**BUG 2:**
ALL template elements have no value in them. I have to do it manually 
since ALL those templates exists! (result of step 2) 

This is painful for ~20 pages with ~5 such elements, its 100 times!!! :-(

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.40
	PHP Version: 7.0.31
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://bv.site2go.co.il
	Home URL: https://bv.site2go.co.il
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.7
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

== Active Plugins ==
	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.0
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	Jetpack by WordPress.com
		Version: 6.4.1
		Author: Automattic

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

	Redirection
		Version: 3.4
		Author: John Godley

	SG Optimizer
		Version: 4.0.7
		Author: SiteGround

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WP Facebook Auto Publish
		Version: 1.4.9
		Author: xyzscripts.com

	WPML CMS Nav
		Version: 1.4.23
		Author: OnTheGoSystems

	WPML Media
		Version: 2.3.4
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.0.5
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.4.4
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.8.5
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.6.4
		Author: OnTheGoSystems

	Yoast SEO
		Version: 7.9.1
		Author: Team Yoast


== Debug ==
	Errors: 
		TypeError: i is undefined
			at https://bv.site2go.co.il/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.1.6 - 2:7417
			2018-08-09 03:18 +00:00
			x 40 times

		TypeError: elementorFrontend.getElements(...).jQuery is not a function
			at https://bv.site2go.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:147779
			2018-08-09 03:18 +00:00
			x 2 times

				
```
</details>

**Comment by bainternet** [comment]
@Mulli 

Can you provide the JSON export or zip of JSON's for us to check?

**Comment by Mulli** [comment]
Hi Ohad

 

Please find 3 zip files:

"separate.." – are the page templates as exported from existing site.

THIS IS WHAT YOU ARE LOOKING FOR.
When I load them – no name for the inner template element is found.

 

For complete view, please find the other two zip. Its the result of "export all" that I generated BEFORE

Of all templates that my client generated as templates.

 

My understanding is the following:

1.	WordPress export/import fail to work properly. The new page whole text is under single section with one text element
2.	Therefore I have to export/import every page, one by one – this works OK apart from the template elements.

 

Side note:

When I export ALL templates – I hade header & footer assigned to all pages/posts in site.

THIS ALSO GOT LOST on the way, so this is issue #3.

 

Good luck!

Mulli

 

 

 

בברכה

מולי באהר

050-9262025

 

 <http://site2goal.co.il/> 

https://facebook.com/site2goal

**Comment by bainternet** [comment]
@Mulli 

I got nothing. You do know that this is not my personal Email and when you reply it is sent to the GitHub issue you opened?

**Comment by Mulli** [comment]
I did not know...
Now I see.
I will forward to  support with reference to you.

**Comment by Mulli** [comment]
Any updates?

**Comment by bainternet** [comment]
@Mulli 	


Sorry for the late reply,

After checking and rechecking this is simply how it works.

each template has an ID assigned by WordPress posts table and the Template Widget uses that ID to pull the template. But once you Import the template/child templates to another site there is no way to control that ID and that is why the template widgets are empty.


For now, sadly, this is how it works, and to change that we would need to rework the export/import functionality in order to get it to import the child templates along with it.

thanks again.
