### ISSUE TITLE
Customized Form

### ISSUE THREAD

**Issue by Riko37** [pojome/elementor#5357]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to add a customize form with x inputText fields, an action button, and x outputText fields. 
Pressing the action button will call a rest api service, send the data from the intputText fields, and present the response in the outputTexts field.
Also, I want an option to dynamically add/remove inputText fields from the form.
As for now, Elementor allows a strict "Form" element and "Html/Text" elements. Customize the Html element "enforces" me to develop html/js/css code.

**Describe the solution you'd like**

1. More customized Form element
    I can write the REST api code, but I need a way to perform actions and get/present fields.
2. Access to the css classes (that way I can develop the html/js part and use the existing style)
3. A dedicated widget for calling REST(json) api

**Describe alternatives you've considered**
As for now I'm using Jquery and Html element for that, but it requires more development.

**Additional context**
Writing code for a customized Form, is missing all of Elementor's benefits...

Thanks
Riko

**Comment by bainternet** [comment]
@Riko37 

1. Using the Current forms you can create an action hook which will run once the form is submitted and even redirect it to a rest service. and control the output of the form message.

2. Not sure how would that work, but we are working on global styles an presets where you can define/style your defaults and Elementor will inherit that.

3. A dedicated widget for calling REST(json) API is a nice Idea but not sure if and when we will implement something like that, so you are more than welcome to create your own [custom widget](https://developers.elementor.com/creating-a-new-widget/)


thanks
