### ISSUE TITLE
Bug: 2 Missing Spanish translations in the Login Widget.

### ISSUE THREAD

**Issue by JulimanS** [pojome/elementor#5358]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Hello!

I don't know if this is the correct place, sorry if not, as the wordpress support forum is for bugs that are on plugin in the repository and this is a issue with pro widget.

The problem is that there are 2 string that are missing translation to Spanish in the Login Widget of Elementor.

The strings are:

-> "Remember me" 
-> "Lost your password?"

![38801252_1813760388693491_4853263974478643200_n](https://user-images.githubusercontent.com/34061710/43893199-5e4ff080-9bce-11e8-810f-17dcb91195b3.jpg)

That strings are in English but the rest of the widget shows everything in Spanish.

Also is not possible to change that labels in Elementor (without entering into the code)

It's possible to change it using translation plugins but this is a workaround.

Thanks!

## Steps to reproduce

Just use the Login Widget of Elementor PRO in Spanish.

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

I didn't put this info because I think the bug is translation department and is not required.

**Comment by bainternet** [comment]
Missing translations is not something we consider a "Bug"

thanks for reporting, and I understand our support already replayed on this.

**Comment by JulimanS** [comment]
Thanks Raz.
