### ISSUE TITLE
Extend "Post Widget" with content

### ISSUE THREAD

**Issue by iMiek** [pojome/elementor#5359]
Extend the "Post Widget" with at least "display content". So the full content of a post can be displayed on a laid out page.

**Describe the solution you'd like**
I build my sites "dynamic". Pages are based on elementor lay-outs with the use of posts (based on categorie, tags, post-ID etc.) I use the Post Widget a lot ;-) Editors/Authors are not allowed to change pages, only posts.

**Describe alternatives you've considered**
I use "WP show posts plugin" from Tom (GeneratePress) with use of shortcodes in elementor. But I want to build the pages with "Post Widgets", because it has more nice layout options and it easier to use within elementor.

- [x] The feature is missing in the latest stable version of Elementor Pro

**Comment by bainternet** [comment]
Duplicate of #4440

**Comment by shaneonabike** [comment]
@iMiek How did you get this working WP show posts. This never seems to work for me as the_content is never properly output
