### ISSUE TITLE
New features to improve elementor

### ISSUE THREAD

**Issue by Capitemflam** [pojome/elementor#5362]
Hi, firstly sorry for my english but i'm a Belgian user of elementor. I use it every day at work (we created website with elementor for our clients.) and I have two feature (easy) to add in elementor. First, when you add a background image, you can adjust it to: top center, top bottom, etc. Can you add to posibility to adjust it with 0-100% like in css. Secondly, I created a food blog for my mother and when i try to create a dynamic home page (https://lacuisinedelaude.be) I think in "post" widget, add the possibility in meta, add the category of the post can be a real good add for this widget.

That's all :) Thanks for reading. 
Capitemflam.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
