### ISSUE TITLE
Background position

### ISSUE THREAD

**Issue by Capitemflam** [pojome/elementor#5363]
**What problem is your feature request going to solve? Please describe.**
Hi, I'm creating a lot of website with elementor and I have a simple idea for improve the background tab. Add the posibility to change background position with 0-100% (because now it's only top/center/bottom) to move our covered background.

**Describe the solution you'd like:** 
Add a choice in background-position : "personalize" when background-size is 'cover', where you can add "0-100% for X" and "0-100% for Y".

**Comment by willcitizen** [comment]
yes thats the smartslider 3 implimentation with x and y 0-100% - works well

**Comment by arielk** [comment]
I merged this issue with another issue #2571 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
