### ISSUE TITLE
Improve post widget

### ISSUE THREAD

**Issue by Capitemflam** [pojome/elementor#5364]
**What problem is your feature request going to solve? Please describe.**
Hi, i'm currently creating a blog for my client. And in the "post" widget, I want to show 4 last post but I only can show title/text/meta but we can't show the "category." Can it's possible the add this feature in the meta?

**Describe the solution you'd like:** 
 Add "category" in meta data of "Post" widget.

Thanks :)

**Comment by bainternet** [comment]
Duplicate of #4440
