### ISSUE TITLE
Featured Post for Posts Element

### ISSUE THREAD

**Issue by vershimajr** [pojome/elementor#5365]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I would like to list the posts of my client's website, with the most recent post being a " featured" post, offset from the reset. 

I've been able to manage by creating two Posts elements - the first with only the most recent post, and the second with a grid of the subsequent posts, using the offset parameter. But I would like to have this accomplished with one Posts element.
The reason is that, I would like the "featured" or offset post, to be dynamic with the pagination of the subsequent posts.  Currently when I navigate to the next page to load older posts, the "featured" or offset Post remains static. 

I've considered using JetBlog addons. They have a 'Smart Posts List' element that I have been intrigued by, but haven't yet been able to configure to accomodate my 16:9 youtube thumbnails I have for featured images. I also think the Elementor cards look a bit nicer.  The JetBlog "smart posts list element" allows for a dynamic "featured" post
.

**Comment by bainternet** [comment]
@vershimajr 

Sadly, This is not possible with the current implementation of Posts Widget.

The only way to achieve that is by custom code using the [Custom Query Filter](https://developers.elementor.com/custom-query-filter/)

and the native WordPress `found_posts` filter hook.

thanks
