### ISSUE TITLE
Error when opening Elementor editor after update

### ISSUE THREAD

**Issue by Webtica** [pojome/elementor#5367]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
After updating to Elementor pro 2.1.1 I get an Fatal error : 

Fatal error: Uncaught Error: Call to undefined function ElementorPro\Modules\DynamicTags\ACF\acf_options_page() in /public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/module.php:31 Stack trace: #0  /public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php(109): ElementorPro\Modules\DynamicTags\ACF\Module::get_control_options(Array) #1  /public/wp-content/plugins/elementor/core/dynamic-tags/base-tag.php(169): ElementorPro\Modules\DynamicTags\ACF\Tags\ACF_Text->_register_controls() #2  /public/wp-content/plugins/elementor/includes/base/controls-stack.php(495): Elementor\Core\DynamicTags\Base_Tag->init_controls() #3  /public/wp-content/plugins/elementor/includes/base/controls-stack.php(288): Elementor\Controls_Stack->get_stack() #4  /pub in  /public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/module.php on line 31

## Steps to reproduce

Open editor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.33 (Unix) OpenSSL/1.1.0g
	MySQL version: 5.7.23
	PHP Version: 7.2.8
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://allyours.webticastage.be
	Home URL: https://allyours.webticastage.be
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: Webtica Theme
	Version: 1.0.0
	Author: Webtica
	Child Theme: Yes
	Parent Theme Name: Twenty Seventeen
	Parent Theme Version: 1.7
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.7.1
		Author: Elliot Condon

	BackupBuddy
		Version: 8.2.8.2
		Author: iThemes

	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.1
		Author: Elementor.com

	ManageWP - Worker
		Version: 4.6.1
		Author: ManageWP

	Ultimate Addons for Elementor
		Version: 1.6.0
		Author: Brainstorm Force

	Wordfence Security
		Version: 7.1.10
		Author: Wordfence

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

== Debug ==
	Errors: 
		TypeError: Cannot read property 'length' of null
			at https://allyours.webticastage.be/wp-content/plugins/ultimate-elementor/assets/min-js/uael-google-map.min.js?ver=1.5.1 - 1:16678
			2018-07-25 07:01 +00:00

				
</details>

**Comment by ideasandpixels** [comment]
Happening to me, too. Site completely uneditable. :(

**Comment by arielk** [comment]
Please update to v2.1.1+

Thanks

**Comment by francisconetolg** [comment]
Fatal error: Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, null given, called in /home/jfmarketingdigit/public_html/wp-includes/class-wp-hook.php on line 288 and defined in /home/jfmarketingdigit/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1027 Stack trace: #0 /home/jfmarketingdigit/public_html/wp-includes/class-wp-hook.php(288): Elementor\TemplateLibrary\Source_Local->on_save_post(0, NULL) #1 /home/jfmarketingdigit/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /home/jfmarketingdigit/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /home/jfmarketingdigit/public_html/wp-includes/post.php(3951): do_action('save_post', 0, NULL, false) #4 /home/jfmarketingdigit/public_html/wp-admin/includes/post.php(666): wp_insert_post(Array) #5 /home/jfmarketingdigit/public_html/wp-admin/post-new.php(66): get_default_post_to_edit('post', true) #6 {main} thr in /home/jfmarketingdigit/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php on line 1027
