### ISSUE TITLE
Feature Request: Choose image size, not just dimensions.

### ISSUE THREAD

**Issue by iamcanadian1973** [pojome/elementor#537]
Allow for image size to be selected, maybe even default it to "large" instead of "full".

When you use other page builders such as Divi, they don't have this, and clients are constantly inserting photos that are much too large.

**Comment by arielk** [comment]
Done https://github.com/pojome/elementor/pull/690

**Comment by willryanuk** [comment]
You have marked this as closed, and it was meant to encompass srcset functionality. We find our clients aren't good at choosing the correct size, so supporting the native Wordpress srcset functionality would be great and prevent editors from creating pages that are absolutely huge. Can you reopen #559 and consider it for a future release. Would much appreciate.

**Comment by arielk** [comment]
We fully support the WordPress srcset function, what is the problem exactly?

**Comment by willryanuk** [comment]
Oh, that is strange... so it is generating srcsets for some images but not others... For example, this is a simple image alone in a single column:
![image](https://user-images.githubusercontent.com/374656/27865364-3c475034-618a-11e7-98dd-feee0d089871.png)

However, the image does not have a srcset:
![image](https://user-images.githubusercontent.com/374656/27865456-85190ea6-618a-11e7-9072-e1495eb47b1e.png)

Even though there are other sizes that have been generated...
![image](https://user-images.githubusercontent.com/374656/27865489-a89d05da-618a-11e7-97bb-c8e4c1795684.png)

So it seems a tiny bit sporadic, but maybe I'm doing something wrong?

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by zaehlpixel** [comment]
Can we have the image sizes selector for all modules, i.e. for the Flip Box? It's only possible to take the fullsize image there....
->
![image](https://user-images.githubusercontent.com/16705004/29521778-344964f4-8687-11e7-981d-3dc7d996b18c.png)
