### ISSUE TITLE
E Pro 2.1.1 Products and Archive Products not displaying correctly on front end

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#5370]
Product and Archive Product widgets do not display all the styling that has been set in the Elementor editor.

This happens regardless of the theme. This example is using the Elementor Hello theme.

Elementor Editor:
![image](https://user-images.githubusercontent.com/23441664/43954607-5f24e538-9c5a-11e8-820d-b6b52ab4d65d.png)

Front End:
![image](https://user-images.githubusercontent.com/23441664/43954631-7403d82e-9c5a-11e8-9f17-3d9fa72a6c37.png)

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.29 (Win64) OpenSSL/1.1.0g PHP/7.2.2
	MySQL version: 5.7.19
	PHP Version: 7.2.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://wctest1.test
	Home URL: http://wctest1.test
	WP Multisite: No
	Max Upload Size: 80 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.1
		Author: Elementor.com

	WooCommerce
		Version: 3.4.4
		Author: Automattic

== Debug ==
	Errors: There are no errors to display
				

Cheers!
Lyle

**Comment by midihead7** [comment]
I'm seeing the same issues.

**Comment by black-eye** [comment]
Here is an example of very specific WPBF theme problem: duplication of some of the attributes (only in edit preview):

![obrazek](https://user-images.githubusercontent.com/5634870/43990363-78cc718e-9d5b-11e8-8d04-3c74f0a2380c.png)

**Comment by Kronan** [comment]
Same here..

**Comment by stllrnet** [comment]
Confirming this issue!
![backend](https://user-images.githubusercontent.com/35221293/44134427-80a41d72-a02a-11e8-907f-eb6a4b2e6ed9.png)
![frontend](https://user-images.githubusercontent.com/35221293/44134428-80b9a002-a02a-11e8-9aab-abb303c38eaa.png)
