### ISSUE TITLE
Multiple shadows

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#5371]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Multiple shadows**
It's very popular this days to use multiple shadows to create some specific design and fill shadows and it's very annoying to use the custom css for each shadow like that.

**Idea for the interface**
I think the interface should be something like the photoshop's one:

![2018-08-10 13 58 09](https://user-images.githubusercontent.com/23374215/43954543-8e07909e-9ca5-11e8-8d06-3a614328aeb5.gif)

(Just a plus sign to add another one and another...)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
