### ISSUE TITLE
Improvement for the Social Share Buttons widget

### ISSUE THREAD

**Issue by Sekhemty** [pojome/elementor#5372]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I think it would be nice to have some more styling options on the Social Share Buttons widget, in particular, I'd like to have the ability to:

- prepend a text label to the actual buttons (I'd like to add a small "share" text before them), i.e.
`Share: [F facebook] [T twitter] [P pinterest]`

- ability to display the label text only when the cursor is hovering the button: so, display a square button containing only the icon, and horizontally expanding it to display the label only when hovering.

Maybe some inspiration could be taken from this plugin https://wordpress.org/plugins/shared-counts/

Thank you!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
