### ISSUE TITLE
Social Share Buttons: auto columns for mobile views

### ISSUE THREAD

**Issue by Sekhemty** [pojome/elementor#5375]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When setting the "auto" number of columns, only one row of buttons appear on screen; this is fine on desktop views, where there is space to display them all (consider i.e. a standard number of 5 or 6 buttons); when switching to a mobile view, buttons are non rearranged on an appropriate number of columns, the text label is partially unreadable and the last buttons are completely invisible.

When trying to use a manual workaround, by setting "auto" on desktop view and specifying a fixed number of columns for mobile views, this does not work, and the buttons always stay on a single row. 

## Steps to reproduce

- Simply set up a default Social Share widget, insert 5 or 6 buttons, and switch to mobile view.
- Try to set a specific number of columns on mobile views while leaving "auto" on desktop view.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
We just released a patch for this issue, please update!

Thanks
