### ISSUE TITLE
Color switching/swapping (background/foreground) like Adobe does

### ISSUE THREAD

**Issue by d-marvin** [pojome/elementor#5377]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It'd just be super handy to be able to swap colors in any instance where a widget property uses two colors. The same way Adobe let's you swap foreground and background colors with a clickable double arrow icon.

![swap](https://user-images.githubusercontent.com/42273482/43962731-6e06269e-9c86-11e8-99fb-d2beb81218be.jpg)
Clicking that arrow in the example mockup would swap the blue and white colors.

Thank you!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
