### ISSUE TITLE
Fixed Image Broken By Animations

### ISSUE THREAD

**Issue by briggly** [pojome/elementor#5378]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.39
	PHP Version: 7.0.31
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.360rize.com
	Home URL: https://www.360rize.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.4.8
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Advanced WordPress Backgrounds
		Version: 1.4.5
		Author: nK

	Akismet Anti-Spam
		Version: 4.0.8
		Author: Automattic

	Alexa Certify
		Version: 4.1.2
		Author: Alexa Internet

	All In One SEO Pack Pro
		Version: 2.8.2
		Author: Michael Torbert

	Astra Pro
		Version: 1.4.5
		Author: Brainstorm Force

	Broken Link Checker
		Version: 1.11.5
		Author: Janis Elsts, Vladimir Prelovac

	Contact Form to Email
		Version: 7.3.7
		Author: CodePeople.net

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.18
		Author: Elementor.com

	Events Manager
		Version: 5.9.5
		Author: Marcus Sykes

	Forget About Shortcode Buttons
		Version: 2.1.1
		Author: Designs & Code

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	Google XML Sitemaps
		Version: 4.0.9
		Author: Arne Brachhold

	Header Footer Elementor
		Version: 1.0.15
		Author: Brainstorm Force, Nikhil Chavan

	Jetpack by WordPress.com
		Version: 6.3.3
		Author: Automattic

	ManageWP - Worker
		Version: 4.6.1
		Author: ManageWP

	P3 (Plugin Performance Profiler)
		Version: 1.5.3.9
		Author: GoDaddy.com

	Pretty Links
		Version: 2.1.6
		Author: Blair Williams

	Really Simple SSL
		Version: 3.0.5
		Author: Rogier Lankhorst, Mark Wolters

	Redirection
		Version: 3.4
		Author: John Godley

	Redux Framework
		Version: 3.6.9
		Author: Team Redux

	Simple History
		Version: 2.26.1
		Author: Pär Thernström

	Super Socializer
		Version: 7.11.16
		Author: Team Heateor

	TablePress
		Version: 1.9
		Author: Tobias Bäthge

	VaultPress
		Version: 1.9.5
		Author: Automattic

	Visitor Maps and Who's Online
		Version: 1.5.8.14
		Author: fastsecure

	Visitor Maps Extended Referer Field
		Version: 1.2.6
		Author: Jason Lau

	Visitor Maps Geolocation Addon
		Version: 1.0
		Author: Mike Challis

	W3 Total Cache
		Version: 0.9.7
		Author: Frederick Townes

	Wordfence Security
		Version: 7.1.10
		Author: Wordfence

	WP Mail SMTP
		Version: 1.3.3
		Author: WPForms

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

	p3-profiler.php
		Version: 
		Author: 

== Debug ==
	Errors: 
		TypeError: Cannot read property 'errors' of undefined
			at https://www.360rize.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:139163
			2018-08-06 12:58 +00:00

		TypeError: Cannot read property 'currentView' of undefined
			at https://www.360rize.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:157928
			2018-08-01 19:14 +00:00
			x 2 times

		TypeError: o.attributes[t.name].each is not a function
			at https://www.360rize.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:106066
			2018-08-01 16:53 +00:00
			x 9 times

		TypeError: Cannot read property 'html' of undefined
			at https://www.360rize.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.4 - 2:80103
			2018-07-30 12:44 +00:00

		SyntaxError: Unexpected token <
			at https://www.360rize.com/wp-admin/post.php?post=42049&action=elementor - 2:1
			2018-07-25 18:25 +00:00

		SyntaxError: Unexpected token <
			at https://www.360rize.com/wp-admin/post.php?post=42049&action=elementor - 5:8
			2018-07-25 18:25 +00:00
			x 2 times

		SyntaxError: Unexpected token <
			at https://www.360rize.com/wp-admin/post.php?post=42049&action=elementor - 2:1
			2018-07-25 18:25 +00:00

		SyntaxError: Unexpected token <
			at https://www.360rize.com/wp-admin/post.php?post=42049&action=elementor - 5:8
			2018-07-25 18:25 +00:00

		SyntaxError: Unexpected token <
			at https://www.360rize.com/wp-admin/post.php?post=42049&action=elementor - 2:1
			2018-07-25 18:24 +00:00

		SyntaxError: Unexpected token <
			at https://www.360rize.com/wp-admin/post.php?post=42049&action=elementor - 3:1
			2018-07-25 18:24 +00:00

				</summary>
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* A clear description of the problem.
* Steps to replicate.
* Isolating the problem.
