### ISSUE TITLE
New lines

### ISSUE THREAD

**Issue by GENERAIL** [pojome/elementor#5379]
I hope you add Arabic fonts
So we can use it and improve Arabic characters

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for the font available, Elementor supports over 880 Google fonts. With Elementor Pro Custom fonts you can add your own custom fonts, TypeKit fonts. And Elementor Fonts API lets you add your own Theme/Plugin fonts to Elementor as well.

thanks.
