### ISSUE TITLE
Font awesome 5 

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#5380]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
*There's no icon for instructor or teacher*

**Describe the solution you'd like**
*Please add the latest Font-Awesome additions to the icons available in Elementor*

**Describe alternatives you've considered**

**Additional context**

*Font Awesome recently added a much-requested icon of an instructor. https://github.com/FortAwesome/Font-Awesome/issues/4079*

**Comment by black-eye** [comment]
+1
Updating FontAwesome was mentioned in several other tickets (both open and closed), some of them quite a long time before (including mine here: #3615). Hopefuly it will be resolved soon.

**Comment by arielk** [comment]
I merged this issue with another issue #4430 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
