### ISSUE TITLE
Plugin extension questions 

### ISSUE THREAD

**Issue by michaelowenrich** [pojome/elementor#5382]
I have extended your plugin, and want to know how to: 

1) disable/unregister all current widgets and categories, and only display the 2 or 3 custom widgets i've created.

2) customize the panel Elements

I have been using the pro api extensively, but was unsure on these items 

Thanks, 

-mike

**Comment by bainternet** [comment]
@michaelowenrich 

1) To remove Widgets you need to unregister them using the provided API eg:

```PHP
add_action('elementor/widgets/widgets_registered', function ( $widgets_manager ){
	$widgets_manager->unregister_widget_type( 'image' ); // This removes the Image widget
});
```
2) Customize how?

**Comment by michaelowenrich** [comment]
1) thank you for your comments, and i did see how to unregister one at a time, but it doens't seem incredibly resource friendly if i only want to show  5 widgets (for my client).   Register 50+ (pro version) and then unregister all of them before initializing my custom widgets.  

So my main question is how can i unregister all (or override the initial init for categories and widgets) within my extension?

2)   for example, disable/hide items that are not pertinent to my client (global tab, advanced settings, font/titles/headers/etc.

thanks!

-mike

**Comment by bainternet** [comment]
@michaelowenrich 

It's not meant to be resource friendly nor is a widget meant to be unregistered, Widgets are one of the main components of Elementor. This is just the API.

as for 2 there is no API for that.

thanks.
