### ISSUE TITLE
Pagination 'Next' Does Not hide or deactivate when posts have not populated page

### ISSUE THREAD

**Issue by vershimajr** [pojome/elementor#5384]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am having issues with the pagination of 'Archive Posts' and 'Posts' elements. These issues I experience when using the Numbers+Next/Previous pagination option. When a page is not fully populated, or if there is no 'next' page available, I expect that the next link should be inactive, and there should be no numeration past that of the current page.

This is not what happens. The numeration, goes one number past the last page, and the 'next' link is active. Clicking the next link takes you to a blank page.

## Steps to reproduce

Simply create an 'archive posts' or 'posts' element with 'Numbers+Next/Previous' selected as pagination option. Make it such that fewer posts are pulled from the query than the capacity of the widget. Please note that the numeration will include page 2, and the 'Next' link will be active (taking you to an empty page).

Or consider the page of my client's site: https://empressive.tv/posts. This page consists of a 'Posts' element with capcity of 15 posts. Note that this page is populated with only 10 posts, yet there is still option to navigate to the next page, either through clicking 'Next' or clicking the '2' page number.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 5.5.37
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://empressive.tv
	Home URL: https://empressive.tv
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child Theme
	Version: 1.0.0
	Author: Vershima Ajo
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.5.22
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Automatic Featured Images from YouTube / Vimeo
		Version: 1.1.1
		Author: WebDevStudios

	Disqus Conditional Load
		Version: 10.2.4
		Author: Joel James

	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.1
		Author: Elementor.com

	Instagram Feed
		Version: 1.9.1
		Author: Smash Balloon

	JetBlog For Elementor
		Version: 2.1.3
		Author: Zemez

	Jetpack by WordPress.com
		Version: 6.4.2
		Author: Automattic

	LoginPress - Customizing the WordPress Login
		Version: 1.1.8
		Author: WPBrigade

	Postie
		Version: 1.9.24
		Author: Wayne Allen

	Really Simple SSL
		Version: 3.0.5
		Author: Rogier Lankhorst, Mark Wolters

	Reset WP
		Version: 1.4
		Author: WebFactory Ltd

	WP AutoTerms
		Version: 2.1.3
		Author: WP AutoTerms

	wpForo
		Version: 1.5.1
		Author: gVectors Team (A. Chakhoyan, R. Hovhannisyan)

	WPS Hide Login
		Version: 1.4.3
		Author: WPServeur, NicolasKulka, tabrisrp


== Must-Use Plugins ==
	Endurance Page Cache
		Version: 1.1
		Author: Mike Hansen


== Debug ==
	Errors: There are no errors to display
				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@vershimajr 

We can't replicate,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
