### ISSUE TITLE
edit page with wordpress after using elementor

### ISSUE THREAD

**Issue by jots** [pojome/elementor#539]
I edited a page with elementor.  Now when I go back to edit it within wordpress, it only gives option to edit with elementor.  Is there a way to edit it in normal fashion (with "visual" and "text" tabs), i.e. not edit it with elementor?

**Comment by arielk** [comment]
You can choose only one way to edit your post: WordPress editor or Elementor editor. Once your page is not defined under Elementor, your page will not show the design of Elementor

**Comment by WPDevHQ** [comment]
Any chance of adding a column to the Pages list to indicate which pages are attached to elemntor?

Also is there scope to remove the edit with elementor link from the page list? - This can be problematic for some users.....

Say for example I have a page attached to a specific plugin i.e the Checkout page for WooCommerce. By mistake I happen to click on "edit with elementor" then that page is now technically an Elementor page and there would be no going back!

**Comment by arielk** [comment]
@WPDevHQ good points!

**Comment by harunalikadic** [comment]
Come on, this is basic. I have to be able to get back to the original state of things. If I choose to edit with Elementor and then want to get back to be able to edit with WP I have to be able to.

Is there a feature request you can link this issue to? If not create one.

Thank you.

**Comment by vjcmacrury** [comment]
Still seems to be an ongoing issue? :-/

**Comment by nelitow** [comment]
Is there any hardcode/db solution to this while they don't solve it?

**Comment by Fridgecrisis** [comment]
I found a way to do this! From WordPress, when I go to edit my page, there was a "Back to WordPress Editor" button in the top left area that removed Elementor from it.

![image](https://user-images.githubusercontent.com/1045795/60681764-ac2fe080-9e4d-11e9-8ed5-20c27b36d070.png)

**Comment by hannahbflynn** [comment]
> I found a way to do this! From WordPress, when I go to edit my page, there was a "Back to WordPress Editor" button in the top left area that removed Elementor from it.
> 
> ![image](https://user-images.githubusercontent.com/1045795/60681764-ac2fe080-9e4d-11e9-8ed5-20c27b36d070.png)

I know this is an old thread but it isn't appearing on my website, so I can't go back to the WordPress editor.

**Comment by bkno** [comment]
Same issue here - 'Back to WordPress Editor' is missing.

**Comment by bentalgad** [comment]
That would be a nice to have to let us revert to regular wordpress post / page.

**Comment by bentalgad** [comment]
This is really crucial. some client's of mine added a lot of posts using Elementor and to convert theme to regular posts  i have to go one by one: 1. copy post content. 2. delete old post. 3. add new post (remember the old title and slug to keep seo). 4. past the content. really annoying and time consuming.

**Comment by ThomasAnonymous** [comment]
Just spent an hour trying to figure this out. If you open your page/post using the wordpress 'Edit' link there will be a button at the top of the page that says "back to wordpress editor" and it will remove Elementor changes from that page.

**Comment by curiocityguide** [comment]
So, I clicked the Back to "Wordpress Editor" button, but now when i got back to edit with elementor, I can't update or publish anything. Did it break my elementor template? If so, how can I get the elementor functionality back and publish?

**Comment by daytonbrock** [comment]
I think this issue would still be valuable to be resolved, and I cannot find an answer anywhere else. My client added Elementor to our homepage, which is extensive and was built a while ago with an older page builder. I am unable to go back to view the old editor and will most likely have to convince my client to rebuild the home page. If anyone has found a solution to this, please reach out!
