### ISSUE TITLE
Insert custom code before a Single Page Template using hooks

### ISSUE THREAD

**Issue by formulaclick** [pojome/elementor#5394]
Hi

I'm using elementor's single page template. I'd like to insert some php code before this template, based on conditions, so I found this:

`add_action( 'elementor/frontend/the_content', function( $content ) {
	$content .= 'custom code';
	return $content;
} );`

If I try this, it works, but it is applied to all Elementor templates used on webpage, I'm not able to filter it to work only with the Elementor template ID that I want. The only argument in function is $content, so how could I filter it?

Thanks

**Comment by bainternet** [comment]
@formulaclick 

The best way would be to have a placeholder on that template, either a shortcode widget or a custom widget where you can run your PHP code and it will match the display conditions for you as it is a part of the template.
