### ISSUE TITLE
Modify output of widgets

### ISSUE THREAD

**Issue by owiekindisch** [pojome/elementor#54]
I would like to modify the html output of existing widgets and the core elements "column" and "section" to make use of frameworks like Bootstrap or ZURB Foundation.

Visual Composer does this for example with its function `vc_set_shortcodes_templates_dir` to view the custom folder for template files.

**Comment by aheinze** [comment]
I would recommend to look in the current theme if there is an override for an element .... otherwise render the default one.

```php
// determine if override is available
if ( $override = locate_template('elementor/icon.php' ) ) {
    include($override); // use include to have all context variables available
} else {
    // default output
}
```

**Comment by KingYes** [comment]
Hi @aheinze @owiekindisch 
Please continue this issue here: #291
