### ISSUE TITLE
Can't page-down in Mac Safari using Magic Trackpad 2

### ISSUE THREAD

**Issue by chris-brighton** [pojome/elementor#540]
Hi,

Ever since the last update (0.8.0), I've had this issue:
## Repro
1. On a Mac, open up WP site with Safari.
2. In WP, select a page designed by Elementor and click "Edit with Elementor"
3. When the page opens up in Elementor, use the Magic Trackpad 2 two-finger swipe to scroll down.

## What happens:
the page doesn't move, as if it is locked. Sometimes it moves a little, then stops.

## What should happen:
Page should scroll down as before.

## This problem only affects:
- Safari on Mac. (Firefox on Mac works fine.)
- version 0.8.0 (0.7.4 works fine on the same page which I have on a cloned WP staging site)
- swiping *down* on Magic Trackpad 2. (Swiping *up* works fine.

## Additional info:
- I have disconnected and reconnected Trackpad bluetooth, and battery charge was 40%
- using a mouse's scroll-button to scroll down works.
- I'm using WP 4.6.0

Thanks for looking into this!

**Comment by arielk** [comment]
Thanks for your reporting, we working on it.
