### ISSUE TITLE
Alt Tags

### ISSUE THREAD

**Issue by Roberto909** [pojome/elementor#5400]
Hi all,
I might be missing something here. When using the Image Widget, Alt tags do not show on hover unless you set the image to custom and choose a width or height value. If you pick one of the options the alt tag doesn't show. I've tested with a few themes including the Hello theme.  Thanks.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by mylimoproject** [comment]
@bainternet 

I will follow-up on this. Do I open a new ticket or do you want to re-open this one?

Personally,  I really don't mind for the "ALT TAG" value not showing upon hover on image (i.e you must set a custom image width & height so the value will show upon image hover). 
I found this closed ticked while searching open/closed threads for "ALT TAG". My issue is that I will use the "same image" over and over again on multiple pages trough my limo websites (vehicle/fleet images), but every page belongs to different service area (i.e Boston, Miami, New York, etc..). What I need, is to add different "ALT TAG" values to same image when used in multiple pages for SEO reasons. It would be great if in addition to the "Caption" option, we could also have an "Alt Tag" option on the image widget (when used, this "Alt Tag" value will override image upload/library value.

Jose
