### ISSUE TITLE
Push to bottom

### ISSUE THREAD

**Issue by Vexander** [pojome/elementor#5402]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Describe the solution you'd like**
A way to push the last element in a column to the bottom of a full height column so that it is always at the bottom of the landing page not matter what the resolution of the screen

**Describe alternatives you've considered**
CSS hacks

**Additional context**

**Comment by Sekhemty** [comment]
+1

**Comment by Vexander** [comment]
@bainternet Hi Raz, I am not CSS jedi, but I would look at three possible implementation methods

1. There could be a float to bottom on a element that will send it to the bottom of its parent column
2. There could be a push to bottom spacer that pushes the elements below it to the bottom of the column it is in.
3. There could be a setting on the column that pushes the last element to the bottom of itself.

I am not sure of the limitations of CSS but that would be my starting point

**Comment by bainternet** [comment]
@Vexander 

Not really what I asked, but thanks anyway.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can either use CSS "hacks" or a [Divider Widget](https://docs.elementor.com/article/113-divider).
Thanks for the feedback.

**Comment by Vexander** [comment]
@bainternet What were you asking then if my answer is not really what you asked?
