### ISSUE TITLE
Animated Headline typing animation: change colors

### ISSUE THREAD

**Issue by Artneo7** [pojome/elementor#5403]
The selection color is black by default (#0d0d0d), but I couldn't find where to change it inside the design tab. So, after some search using the inspection tool I found a way to edit the colors using CSS.

![greenshot 2018-08-13 17 44 44](https://user-images.githubusercontent.com/17693529/44057129-9f8455d2-9f20-11e8-807c-79a8c02d8e8d.png)

This is the CSS if someone is going through the same problem:

_selector .elementor-headline-typing-selected, .elementor-headline-animation-type-typing .elementor-headline-dynamic-wrapper:after {
    background-color: #33a1fd;
}_

It would be nice to have a visual configuration for the Animated Headline rotating animations.

Thanks!

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by Artneo7** [comment]
Ok @bainternet, now I followed the guidelines for opening the feature request. Thank you for your support!

**Comment by qdl2020** [comment]
@bainternet Hi Raz. Would you share how we can change the default black background as @Artneo7 detailed above? I haven't found any documentation via Elementor's Knowledge Base or on the threads here.

**Comment by Artneo7** [comment]
Hey @qdl2020. Try the CSS I described above. You just need to change the background-color: #33a1fd; to your needs.

**Comment by qdl2020** [comment]
Hi @Artneo7. First, thank you for responding in less than 24 hours! I tried the suggested solution you had shared first before commenting; alas, it did not work. I've also tried adjusting various classes found in the console (i.e. in Chrome's Developer Tools). Nothing has worked so far. 

Side note: Strange how Elementor wouldn't offer users to adjust this element...

**Comment by Artneo7** [comment]
Maybe because Animated Headline is not a popular widget… but for sure they'll add this option in the future. I'm using the CSS in my current website and it's working fine. Maybe there could be some CSS conflict.

**Comment by qdl2020** [comment]
I agree that it may not be a popular widget. 

Glad that it's working for you; always helps to know the various approaches available. At least I have a clearer context of what has/hasn't worked for some of us. I may email the support team. 

Thanks again!

**Comment by croquetaspodcast** [comment]
Hello @Artneo7 , I tried your CSS to add a transparent effect to the typing animation and it work well for the selector (little horizontal line), thanks for that! but it didn't work for the black background highlighting the words when rotating, any idea if I'm may be missing something? 

+1 for those customization options on that widget!

**Comment by Artneo7** [comment]
@croquetaspodcast try adding the !important after the `background-color: #33a1fd !important;`
You could also try to inspect the element with Google Chrome and see what color is being used to overwrite it with your own CSS.

**Comment by g2creative** [comment]
Thanks for this - works like a charm! Question, though. I want to use "clip" version of the animated headline widget. This version shows the text getting backspaced and deleted (not highlighted and selected) while the cursor stays in place. I want to change the cursor color (not the background color) on the selector .elementor-headline-animation-type-clip ... but I'm super new to all of this and can't figure out how to target just the cursor. Any tips?

**Comment by Bexolo** [comment]
@g2creative I have managed to target the cursor colour. See below:

```
.elementor-headline-animation-type-clip .elementor-headline-dynamic-wrapper:after {
    background-color: white;
}
```

**Comment by IMTanuki** [comment]
@Bexolo - many thanks. That cursor's default color was hideous...looks awesome with your CSS!

**Comment by tuc0001** [comment]
Hi! Can someone check if this is still working? Because for me: it isn't, but maybe I did something wrong.

I pasted the code from @Bexolo and into the css selector and I tried it on every possible option in the navigator. Thanks for the help!

**Comment by Bexolo** [comment]
> 
> I pasted the code from @Bexolo and into the css selector and I tried it on every possible option in the navigator. Thanks for the help!

Try adding an **!important** at the end of the rule. There might be a theme blocking/overriding it. Typing this on mobile so apologies for the bad formatting:

`
.elementor-headline-animation-type-clip.elementor-headline-dynamic-wrapper:after {
background-color: white !important;
} `

**Comment by tuc0001** [comment]
@Bexolo Thank you so much for your answer! Sadly it did not work for me 💢 
I'll try again tomorrow on a blank canvas to see if it's working there. (Using OceanWP fyi)
