### ISSUE TITLE
Call to Action widget should be able to get dynamic values from another post besides itself

### ISSUE THREAD

**Issue by Jaska** [pojome/elementor#5405]
It's cool that the Call to Action widget got the same dynamic options as the other widgets (https://github.com/pojome/elementor/issues/4767)

But I think call to action really doesn't need to get content from the page it's on.

Example: https://elementor.com/call-to-action/
All those links showcase different locations, not the current page.

So would it be possible to get the dynamic values from another post (article, page, custom post…)?

Edit:

## Prerequisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When creating a visually impressive grid with the Call to Action -widget, It is frustrating to insert the picture, the title, the description and the url of the post when all that info has already been put into the post the Call to Action links to.  

Recent example here: https://tanssittamo.fi/palvelut/tanssipalvelut/
I wished I've could just pointed the Call to Action -widget to the certain page, so that it would have dynamically got the content from there - rather than me having to maintain 2 places with the same content.

**Describe the solution you'd like**
Internal URL Dynamic Tag feature in 2.1.0 already allows this for URL's. 
The solution would be just to expand this to cover other fields and values besides URL.

**Comment by Jaska** [comment]
Internal URL Dynamic Tag feature in 2.1.0 allows this for URL's. The same UI could be expanded for the other values?

**Comment by bainternet** [comment]
@Jaska 

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

It's not clear what you mean. Dynamic takes data for where ever you tell it to take the data.

Can you please explain better.

**Comment by Jaska** [comment]
@bainternet Ok thanks, I've edited the post. Hopefully it's more clear now.

**Comment by bainternet** [comment]
So basically you want the call to action to pull its data for a post and not by creating a single template, more of a posts widget which will display a "grid" of "call to actions".

In that case, we have a request like that already #4440

thanks for clarifying.

**Comment by Jaska** [comment]
No, I don't mean a posts widget template. 

I would just like the ability to have one Call To Action widget that would point for example a subpage (products) and it would use the subpages featured image, title, description (whatever field I use).

It already does what I want with the new "Internal URL Dynamic Tag" feature in 2.1.0.

The feature would just need to be expanded for other fields besides button URL.

**Comment by bentalgad** [comment]
It's funny that you have for dynamic content in every field separately instead of just having the option to add dynamic fields any where just like in beaver builder which lets you add it even inside text and even multiple dynamic content's in one field. a lot of posts on how to do fancy effects but basic features are still missing from the beginning of this plugin.
