### ISSUE TITLE
Elementor's UI language

### ISSUE THREAD

**Issue by rimvydukas** [pojome/elementor#5408]
Hi,
My site's language is Russian. My profile's language is English. When I try to edit page with Elementor - all elementor GUI is in Russian. How can I have this UI in English language? Thanks.

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support,  Please try the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/


Thanks.

**Comment by rimvydukas** [comment]
Ok, lets change this to a bug or feature request, because it seems that there is no such option to change Elementor's UI language
