### ISSUE TITLE
Support for ACF field types such as links and group fields

### ISSUE THREAD

**Issue by willcitizen** [pojome/elementor#5409]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I know that ACF support is still 'in beta', but we really need to get some understanding out here of what the roadmap is for additional support.  currently you can't use any fields that are part of  a group in ACF and the only 'link' field type that is supported is the URL field - this is huge problem as field type link is a label-> url pair that allows relative links and allows you to populate a button from a single field URL is basically useless as dynamic content to use for links within your site.

**Describe the solution you'd like**
I understand that the todolist for Elementor Pro is huge at the moment, but could we please see some sort of development roadmap transparent to this community indicating if not when, but at least in what order you plan to introduce these features.

**Describe alternatives you've considered**
I just saw that Anywhere Elementor will be introducing support for ACF repeater fields in their next release, currently their support for custom fields is I'm sad to say streets ahead of Elementor Pro and can't see a choice but to keep using it in my current solution designs.

**Additional context**

**Comment by bainternet** [comment]
@willcitizen 

ACF is not in beta anymore, and as for 
>the only 'link' field type that is supported is the URL field 

not really sure way you say that, beacuse Elementor Pro `ACF URL` dynamic tag supports this ACF fields:

* text
* email
* image
* file
* page_link
* post_object
* relationship
* taxonomy
* url

so ....

As for road map in regards to ACF, no major improvment is palnned any time soon.

and if all that is not enugh you can always write your own [Dynamic Tags](https://developers.elementor.com/dynamic-tags/)

thanks again.

**Comment by willcitizen** [comment]
Ok perhaps don't brush me off quite so hastily - remember this is the only forum where your team *allows* customers to engage on any more advanced technical queries and remember that I am a customer who bought your product, not an opensource collaberator.

I clearly recall reading that ACF support was limited and it was flagged as beta - so perhaps I missed the release notes where you changed this? 

I'm working actively on a project making extensive use of ACF and I don't see these options appear or I wouldn't be asking about them so perhaps there are constraints as to how they become available in context?

You have extremely limited documentation on any aspect of using dynamic content at this point, it's pretty unreasonable to just expect everyone to 'figure it out' and I can assure you that if I try any of your other support channels they'll send me back here.

I have to actually point out that this is a terrible support experience in many respects to assume that every user you have that wants to explore the more advanced functionality should become a github subscriber and engage directly with your dev team.

Either focus on getting your documents up to scratch or put a proper support team in place that knows your product inside out and can field questions like this.

**Comment by willcitizen** [comment]
@bainternet 

Just want to  illustrate an incredibly simple use case here in terms why your implimentation isn't 'end user' ready:  

Attempting to use an ACF field to populate a standard elementor button widget with dynamic data - I'm presented with 2 dynamic fields a label and a url.

I can either define 2 fields one to carry the label and one the carry the url and that works fine except it requires I use the generic acf url field which is not user friendly on data capturing side.

Attempting to use acf field type link in this context in both fields simply returns array is this field contains a key value pair, whereas all the acf page link returns is a post-id and acf relationship returns an array of post ids.  

I can't see how you claim to have implimented support for this capabilties when you haven't built any functionality into the widget ui to interpret, or render the data returned by these fields - unless I'm missing something incredibly obvious - in which case please explain to me how you would use the returned data to populate a widget?

**Comment by bainternet** [comment]
@willcitizen 

> "remember this is the only forum where your team allows customers to engage on any more advanced technical queries."

**This is not a forum!** This is where we collect Bug reports and feature requests, manage Elementor Core development and on the way answer technical code-related questions.

No one is expecting anyone to 'figure it out' nor do we assume 
>"that every user you have that wants to explore the more advanced functionality should become a github subscriber and engage directly with your dev team".


The Dynamic tags in general and more specifically the ACF integration are relatively new and the docs for that are in the making. Other than that there are [more than a few tutorial videos](https://www.youtube.com/results?search_query=elementor+acf&page=&utm_source=opensearch) made but the great Elementor community not to mention [Elementors own video tutorials](https://www.youtube.com/channel/UCt9kG_EDX8zwGSC1-ycJJVA/videos) which we constantly update and add to.


As for your "simple use case", you seem to miss understand (which is understandable due to the current lack of documentation) how dynamic tags work. 

Each control in Elementor's panel can hold data: 
* Static - manually entered values.
* Dynamic - a placeholder with a location to pull the data from (eg: custom fields named "my_field")

So our dynamic capabilities are set to a control and not to a Widget level, meaning that using an ACF LINK field can only populate A URL control and not the Text value of a different control automatically.

Thanks

**Comment by willcitizen** [comment]
@bainternet 
@bainternet 

I completely understand that this isn't a forum - that's my frustration.  You don't provide a clearly defined space where users of your product (not plugin developers, or collaborators directly on the project) can actually engage with helpful and knowledgable members or your team, or community champions to discuss more advanced use cases, or flesh or working examples of solutions.

When i first came to github it was because my support ticket was brushed off with a reference to an incomplete document and a suggestion to come here - your own team is sending users here to be supported.

 If you look at any of the other successful and mature wordpress addons these things are an integral part of their success and because you don't provide the space the support for *your product* is actually scattered all over community youtube channels and pages (I'm talking David Foye, Snifflevalve etc), but none of these guys are pushing the envelope of what dynamic content can do and taking it apart so the use cases I'm attempting and finding are flawed simply arent being discussed by more than a few and when we come here every question must be posed as a bug, or a feature request or we don't get to engage.

I do completely understand how dynamic tags work and that they are placeholders for the field content, but when the underlying field is returning an array not a single value which is the situation with many use cases for relationship fields, or for fields such as the acf link field you have not provided a mechanism to allow for individual key value pairs to be referenced within that array.  

I can also fully appreciate the added complexity this brings but you really do need to consider that certain common uses like acf relationship fields as a query source and link fields need to be addressed.

**Comment by spatialy** [comment]
Hi @willcitizen @bainternet 

Come here after hours searching for documentation on ACF support.

My problem here is that when we select a dynamic tag to use ACF, not advance fields like relationships/post_objects are showed to select. What am I missing?

@bainternet, until the proper docs are in place this forum is the only point to obtain support on functionalities directly from you guys.

My setup: WP 4.4 + Astra Pro + ACF Pro 5.7.1 + Elementor Pro

Any help is very appreciate

**Comment by joeczucha** [comment]
@spatialy Did you have any luck getting this to work?

I'm trying to do something similar: I have a `Trip` CPT with a `location` field (of type Post Object)  and a `Trip Location` CPT with a `details` field.

I'd like to display some info relating to the `Trip Location` on the `Trip` page, so would need to be able to access the `Trip Location` ACF field and then hopefully pull through the data from that.

Not sure it's possible though?
