### ISSUE TITLE
Mega menu

### ISSUE THREAD

**Issue by isanlab** [pojome/elementor#5411]
It would be interesting to build a menu with more options than the current ones. To be able to build a mega menu. To be able to put different columns, images into the menu, etc.

Regards

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
