### ISSUE TITLE
New page error

### ISSUE THREAD

**Issue by Felipe-NS** [pojome/elementor#5413]
When I try to create or edit a new page with Elementor PRO and Woohocomerce plugins activeted I receive an error message from my hostgator
My home page is the only page working fine when both plugins are activeted
If I disable the Woohocomerce or Elementor PRO things return to the normal with the new pages
Elementor PRO version: 1.1.2_(but I have faced this since previous versions)_

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
