### ISSUE TITLE
Add context menu hooks

### ISSUE THREAD

**Issue by thenovacreator** [pojome/elementor#5419]
As a plugin developer for elementor i want to make use of the new context menu to add own options into it.

## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor

**What problem is your feature request going to solve? Please describe.**
I want to improve the workflow of a split test plugin for elementor and therefore gain access to the context menu throught hooks. 

**Describe the solution you'd like**
In the first place there have to be a function to register custom options into elementor. Something like this.

```
elementorFrontend.hooks.addAction('editor/menu/render', function( menu ) {
    menu.addItem({
         'label': 'Setup split test',
         'callback': function (element, model, view) {
             // Do some stuff here
         }
    });
    menu.addItem({
         'label': 'Show test variation',
         'items': [{   
             'label': 'Variation 01'
             'callback': function (element, model, view) {
                 // Do some stuff here
             }, {   
             'label': 'Variation 02'
             'callback': function (element, model, view) {
                 // Do some stuff here
             }]
    });
} );
```

On top of that it should be possible to manipulate the parent elements in the model too.

**Describe alternatives you've considered**
Right now the split test are setup using the sidebar witch leads to a lot of clicks and user feedback that think that this is way to complicated.

**Comment by thenovacreator** [comment]
PS: We are planning to implement this feature ourselfs into Elementor. There question asked here is if a pull request would be accepted since we have no idea about your pull request policies.

**Comment by bainternet** [comment]
@thenovacreator 

There is already a filter hook on the menu item groups `elements/widget/contextMenuGroups`
which accepts two parameters:

* groups - (Array) an array of group items.
* element - the current target element (section/column/widget)

So you can add your own group of action items or add items to an existing group, ex:


```JS
elementor.hooks.addFilter( 'elements/widget/contextMenuGroups', function( groups, element ) {
	groups.push(
		{
			name: 'split_test',
			actions: [
				{
					name: 'setup',
					title: 'Setup split test',
					callback: function() {
						// do your stuff, element should be available here
						console.log( 'hello Right Click' );
					}
				}
			]
		}
	);
	return groups;
} );
```

Thanks.

**Comment by r0b1n1sl4m** [comment]
> @thenovacreator
> 
> There is already a filter hook on the menu item groups `elements/widget/contextMenuGroups`
> which accepts two parameters:
> 
> * groups - (Array) an array of group items.
> * element - the current target element (section/column/widget)
> 
> So you can add your own group of action items or add items to an existing group, ex:
> 
> ```js
> elementor.hooks.addFilter( 'elements/widget/contextMenuGroups', function( groups, element ) {
> 	groups.push(
> 		{
> 			name: 'split_test',
> 			actions: [
> 				{
> 					name: 'setup',
> 					title: 'Setup split test',
> 					callback: function() {
> 						// do your stuff, element should be available here
> 						console.log( 'hello Right Click' );
> 					}
> 				}
> 			]
> 		}
> 	);
> 	return groups;
> } );
> ```
> 
> Thanks.

The problem with this method is the new context item is only available after inserting the element. If you save the page and right-click on the same element after a page load the new context menu is no longer available.

Any solution with this problem?

**Comment by akashxyz** [comment]
This works fine for the section, widget, and column level context menu.

Need help with adding options in the **Choose Action's** Context menu.

![image](https://user-images.githubusercontent.com/61490132/82427560-e4accd00-9aa6-11ea-8d62-bb7c8f2518e5.png)

**Comment by drinkmaker** [comment]
> Is there any other filter for this?

@akashxyz  Did you find the filter name for that?

**Comment by akashxyz** [comment]
Not at the moment @drinkmaker.

Still looking out for that.

>
