### ISSUE TITLE
Elementor Nav menu won't show dropdowns on menus on tablets

### ISSUE THREAD

**Issue by tampainternet** [pojome/elementor#5420]
I have tried multiple times creating new nav menus, both in wordpress and then trying multiple instances within the elementor pro nav menu tool. No matter what I try, the menu's drop-downs do not work on a tablet, I would even settle for a hamburger menu. I have tried this on both iPad and Android tablets. You can see this at https://polkeldercare.com and look at the top menu on a tablet and you will see that the nav menus do not work. Does anyone know of a fix for this? Thank you in advance.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Please contact our support at support @elementor.com for guidance in resolving this issue.
thanks.
