### ISSUE TITLE
mobile column width percentage doesn't work with reversed columns

### ISSUE THREAD

**Issue by moseskerub** [pojome/elementor#5421]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

1. add a new section with 3 columns
2. switch to mobile editing
3. set the first column width to 100%, and the other two 50%
4.watch the 50% columns next to each other
5. turn on reverse mobile columns in section settings
6. watch the two 50% columns one above the other instead of next to each other.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by moseskerub** [comment]
Sadly I'm not a developer of any sort, just an happy end user. But this bug didn't exist in earlier versions If I'm not mistaken

I can't add any details, but maybe the solution is to revamp the reverse columns mechanism?
maybe use an ordering system (flex allows that I think) so you could select the precedence for each column - and this could solve tablet reverse as well - which doesn't exist today

Hope it can help

**Comment by arielk** [comment]
@moseskerub Thanks for your idea, we just fix this issue for next version and we added an option to reverse columns for tablet also: https://github.com/pojome/elementor/issues/2070
