### ISSUE TITLE
[Feature Request] Add a frontend/{$element_type}/should_render filter

### ISSUE THREAD

**Issue by Kilbourne** [pojome/elementor#5424]
What i'm trying to do?
I added a control to standard section element and, based on this control, i want to not render the element.

```
public function print_element() {
		$element_type = $this->get_type();

+               if( !apply_filters( 'frontend/{$element_type}/should_render', true, $this ) ) return;

		/**
		 * Before frontend element render.
		 *
		 * Fires before Elementor element is rendered in the frontend.
		 *
		 * The dynamic portion of the hook name, `$element_type`, refers to the element type.
		 *
		 * @since 1.0.0
		 *
		 * @param Element_Base $this The element.
		 */
		do_action( "elementor/frontend/{$element_type}/before_render", $this );
```

**Comment by bainternet** [comment]
@Kilbourne 

We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

**Comment by Kilbourne** [comment]
I added a pull-request for this more than 2 months ago. But i can't understand what is preventing the merge...

**Comment by Kilbourne** [comment]
@bainternet  could you check what is missing about the pull request ? thanks
