### ISSUE TITLE
custom field-- Field Type: repeater 

### ISSUE THREAD

**Issue by networking-web** [pojome/elementor#5425]
Hey,
Thank you very much for the new Elementor Pro 2.1 with **all the important developments** !!

When the field type is: repeater
The element does not recognize the field and displays it.
Thanks

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
