### ISSUE TITLE
[BUG] Pagination in Posts with Custom query

### ISSUE THREAD

**Issue by bfrye26** [pojome/elementor#5429]
I seem to have found a rather notable issue. The new query is a fantastic addition and gives Elementor Pro a fair deal of power. The issue I am facing has to do with Arcive Pages, and when I set up paginatgion for a page with a custom post type. It will work flawlessly for the first page, but when you click on any subsiquent page we are presented with this error: Oops! That page can’t be found.

I am thinking it has to do with it not being the Archive block, although I am open to suggestions!

**Comment by bfrye26** [comment]
It should also be noted that the Archive block simply does not work with Custom post types at this time. It is possible there is a query that needs to be used to get it to work, although all pre-get queries cause a major 500 error.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
