### ISSUE TITLE
Post Elements - Page Title, Content, Etc

### ISSUE THREAD

**Issue by misfist** [pojome/elementor#543]
I'd like to layout pages using Elementor. Part of the layout should include the page title. Is there a way to have the page title automatically displayed within the layout. 

For instance, I have a page called About Us. The top of the content area will have the title About Us on a full-width black background.

All other pages will look the same, but the title (and content) will be different.

Is this possible?

![new york city network of worker cooperatives](https://cloud.githubusercontent.com/assets/709248/18366553/2c9cafc6-75e5-11e6-9fc9-a620aedfb5b9.png)

**Comment by arielk** [comment]
Currently this feature is not supported, but this really cool feature that we think about it, we call it: Global Template (temporary name)

**Comment by lunacroft** [comment]
Another simple solution is implement inside title widget an option to display WordPress page title the_title. So we could use native page title or custom. What do you think @arielk ?

**Comment by misfist** [comment]
I was imagining having something like a widget called "post element" (or some such) that would enable you to insert common things like title (`the_title`), content (`the_content`),  featured image (`the_post_thumbnail`), etc.

**Comment by peepshow** [comment]
@arielk is this something you guys are still considering? I think @misfist is right on the money. 
It's probably one of the most vital missing piece for me right now. 

If we could pull in bits post data one by one including custom fields it would allow us to pretty much assemble custom loops, these could then be saved as section templates or global widgets.

👌

**Comment by dudaster** [comment]
I've made a very simple template https://wordpress.org/themes/download/eletheme.0.0.1.zip
Curently works with {title} and {content} inserted as shortcode. The thumbnail is added over a empty image.

Check the Elementor Template Library for what it can do.

I'm working on an elaborate version of it with many more Elementor Widgets.

**Comment by ramiy** [comment]
@misfist @peepshow @dudaster 

the features you described are exist on **[Press Elements](https://wordpress.org/plugins/press-elements/)**  plugin. I have the same issues. This is why I developed this plugin.

It has many Elementor widgets that act like theme-functions.

![cpt-posts](https://cloud.githubusercontent.com/assets/576623/24584440/e2e79cea-1776-11e7-986e-aa26e7eb1daa.png)

**Post Elements:**

- Post Title - `the_title()`
- Post Excerpt - `the_excerpt()`
- Post Date - `the_date()`
- Post Author - `the_author()`
- Post Terms
- Post Featured Image
- Post Custom Fields
- Post Comments

**Site Elements:**

- Site Title
- Site Description
- Site Logo
- Site Counters

**Comment by parfilov** [comment]
Ineed this features too for unique post design. I tried to use Press Elements and after adding Post Autor Widget, my post stopped be editable with Elementor 👎

**What I need:**
- Post Title - the_title()
- Post Excerpt - the_excerpt()
- Post Date - the_date()
- Post Author - the_author()
- Comments Number - comments_number() with get_comments_link() _(Press Elements hasn't it)_
- Post Terms
- Post Featured Image
- Post Custom Fields
- Post Comments (form and list)

**Good if for:**
- Post Date - the_date()
- Post Author - the_author()
- Comments Number - comments_number() with get_comments_link() _(Press Elements hasn't it)_
- Post Terms
I could set an FA icon

And i dont want to use third-party buggy solutions. Do it in Elementor please!

**Comment by Ver3** [comment]
Text below came from my original ticket. Just adding it here to make this thread complete:

---

When you currently try to Edit a Woo Product, you can only edit the description. It would be very useful for shop owners to be able to edit and style all elements on a product page.

Several plugins (Like Elementor Anywhere, WooStore for Elementor and Press Elements) have proven it to be possible. But none hit the mark just right or come with a lot of other stuff you don't need (even Widgets already in the Pro Version).

### My ideal would be this (for Elementor Pro version)

- Go to a product and Edit with Elementor.
- All Woo Elements (like Title, Price, Add to Cart button, etc..) will be 'transformed' to an upgraded version of the current Woo Elements Widget.
- Now simply style the page as you please.

This would prevent the need for separate info-, and product pages. It will also open possibilities no other builder currently offers. This would make Elementor a MUST for shop builders/owners.

**Comment by rurik06** [comment]
I'm with you, Ver3. I'm surprised how little attention the issue of woocommerce layout customization receives from page-builders. Woocommerce is so powerful in its functionality and application potential, yet the styling is very ugly and generic out of the box

The approach you describe is spot-on, everything about Woo should be customizable - from layout to buttons, colors/fonts, check-out fields, etc.

Divi builder with its addition of "shop" widget comes is so far the best option (for those who wants to use Divi theme/builder). Also, Generate press theme does allow to customize certain global design and layout elements of Woo

**Comment by Ver3** [comment]
Thanks @rurik06 Let's hope the awesome people at Elementor feel the same way. Although I could understand their hesitation, as they would effectively support a third party plugin. Albeit one used by MANY.

**Comment by themedleb** [comment]
I would love for the section background image to get the page/post's featured image automatically.

**Comment by matthiaswagnerwy** [comment]
+1 for featured image

**Comment by enviedbymost** [comment]
The 'edit with elementor' button is disable for the wordpress category/archive pages.

Will we ever be able to redesign these pages using Elementor? By default (from Wordpress), they look terrible lol.

**Comment by MTraveller** [comment]
1+ for woo pages

**Comment by dudaster** [comment]
I'm working on a woocommerce http://termice.1002.ro/
Everything is done in elementor:header, footer, thumb, content, add to cart button, description, meta_data, product attritbutes, etc.

I'm still working on it but it's going well so far.

I'll make a video tutorial to get the idea.

Also you can define templates for single and archive for every taxonomy term or post type, header, footer, 404, search etc.

For the archives I'm using Posts widget with a custom skin you can load from another elementor template, and the query is rewrite with the global query.

I think Woocommerce should make widgets available for Elementor. This way it wouldn't be compatibility issues.

**Comment by kokers** [comment]
What I would imagine for global templates is for example create basic structure for specific CPT or Post format (like title, sidebar, columns ratio) with one field "content" left for user to edit. This would allow user to have a free will on what to use in the content itself and would act a bit like global widget. So that when I change structure in that global template (like for example remove sidebar) all posts with that would update.

The simple example of use case is during black friday. It would be great to change structure a bit  for all CPT, add a banner for a week or so, and then remove it. Now when using elementor you need to edit all of the posts. I know I can code it to the single-cpt.php but with "global template" client could do it without devs help. And currently he did it "by hand" anyway ;o)

**Comment by parfilov** [comment]
The other good things are the custom fields. Just look how does Adam doing it at the Beaver Themer https://youtu.be/R9K2VWuUkwE?t=48m31s
I think It's amazing like a Bever Themer by itsel. I want to see something like the same in Elementor =)

**Comment by parfilov** [comment]
Some other ideas for custom fields.

1. Label.
Show/hide;
From custom fields or custom, written by hand;
Label separator ":", "/", "*", "—" etc.

2. Scema.org markup for better indexing.
Dropdown list with markup options.

**Comment by dudaster** [comment]
After a year in the making and before the official release from the elementor guys you can try this: https://github.com/dudaster/eletheme/
It's nothing fancy but it does it's job... combine it with other elementor addons and you'll like it.
It's made by me, and I used it in a dozen of websites.

**Comment by forcedlogic** [comment]
With Elementor publicly stating they are releasing a full theme builder this month, I am confused. Why would you think anyone would try this and not wait for an official release from Elementor.

**Comment by dudaster** [comment]
Because it's free and you can use it now?

**Comment by themedleb** [comment]
@forcedlogic I think he was working on it for a year now, before the official announcement of Elementor, so it's like too late to stop the hard work of a whole year even after the official announcement. Plus it's free, since Elementor are going to include this feature only for the paid version (Pro).

**Comment by bainternet** [comment]
closing in favore of #3826 

thanks everyone.
