### ISSUE TITLE
Incompatible with seo-optimized-images-business-woocommerce

### ISSUE THREAD

**Issue by kevin25** [pojome/elementor#5431]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Seo-optimized-images-business-woocommerce was enabled before. I installed a brand new theme built with Elementor. I created a new page and used Elementor to edit that page. On Elementor editor, i imported the template for that page and saved it. The frontend was messed. It didn't show the page correctly. No footer and header. Only 2 images. 

I had to disabled all plugins except for WooCommerce. Then enabled one by one. I found out that was Seo-optimized-images-business-woocommerce. When I disabled it, that page was normal. I re-enabled it and got the same issue. Then I checked the error log and found the error log.

`Stack trace:
#0 /home/domain/wp-includes/class-wp-hook.php(286): soi_load_custom_widget_output('<h3>Men's Shirt...', Array)
#1 /home/domain/wp-includes/plugin.php(203): WP_Hook->apply_filters('<h3>Men's Shirt...', Array)
#2 /home/domain/wp-content/plugins/elementor/includes/base/widget-base.php(388): apply_filters('widget_text', '<h3>Men's Shirt...', Array)
#3 /home/domain/wp-content/plugins/elementor/includes/widgets/text-editor.php(360): Elementor\Widget_Base->parse_text_editor('<h3>Men's Shirt...')
#4 /home/domain/wp-content/plugins/elementor/includes/base/widget-base.php(474): Elementor\Widget_Text_Editor->render()
#5 /home/domain/wp-content/plugins" while reading upstream, client: xxx.xxx.xxx.xxx, server: www.domain.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "www.domain.com"
2018/08/15 08:15:18 [error] 28644#0: *33558 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function soi_load_custom_widget_output(), 2 passed in /home/domain/wp-includes/class-wp-hook.php on line 286 and exactly 3 expected in /home/domain/wp-content/plugins/seo-optimized-images-business-woocommerce/seo-optimized-images.php:247`

Seo-optimized-images-business-woocommerce can be founded here. I'm not sure about the community version. 

Free version: ( Seems not to be affected)
https://wordpress.org/plugins/seo-optimized-images/
Paid version (Version 1.5.2):
https://webriti.com/seo-optimized-images/

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>system info</summary>
### WordPress Environment ###

Home URL: https://www.domain.com
Site URL: https://www.domain.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 5.6.36-0+deb8u1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30000
PHP Max Input Vars: 2000
cURL Version: 7.38.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.35-MariaDB-0+deb8u1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: ag_
MaxMind GeoIP Database: ✔
Total Database Size: 162.11MB
Database Data Size: 93.59MB
Database Index Size: 68.52MB
ag_woocommerce_sessions: Data: 0.31MB + Index: 0.02MB
ag_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ag_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ag_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
ag_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB
ag_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.42MB
ag_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ag_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
ag_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ag_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
ag_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ag_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ag_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ag_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ag_adsw_activities: Data: 0.13MB + Index: 0.00MB
ag_adsw_ali_meta: Data: 0.02MB + Index: 0.03MB
ag_commentmeta: Data: 0.05MB + Index: 0.03MB
ag_comments: Data: 0.42MB + Index: 0.38MB
ag_failed_jobs: Data: 0.02MB + Index: 0.00MB
ag_iconic_woo_linked_variations: Data: 0.02MB + Index: 0.00MB
ag_jitso_offer_accepts: Data: 0.09MB + Index: 0.00MB
ag_jitso_offer_conversions: Data: 0.02MB + Index: 0.00MB
ag_jitso_offer_declines: Data: 0.02MB + Index: 0.00MB
ag_jitso_offer_views: Data: 0.13MB + Index: 0.00MB
ag_links: Data: 0.02MB + Index: 0.02MB
ag_mailchimp_carts: Data: 0.06MB + Index: 0.00MB
ag_options: Data: 14.02MB + Index: 2.16MB
ag_postmeta: Data: 62.63MB + Index: 56.11MB
ag_posts: Data: 12.36MB + Index: 7.91MB
ag_queue: Data: 0.02MB + Index: 0.00MB
ag_rac_abandoncart: Data: 0.11MB + Index: 0.00MB
ag_rac_email_logs: Data: 0.02MB + Index: 0.00MB
ag_rac_templates_email: Data: 0.02MB + Index: 0.00MB
ag_social_users: Data: 0.02MB + Index: 0.02MB
ag_termmeta: Data: 0.11MB + Index: 0.19MB
ag_terms: Data: 0.13MB + Index: 0.17MB
ag_term_relationships: Data: 0.38MB + Index: 0.20MB
ag_term_taxonomy: Data: 0.16MB + Index: 0.17MB
ag_usermeta: Data: 0.17MB + Index: 0.16MB
ag_users: Data: 0.02MB + Index: 0.05MB
ag_wc_download_log: Data: 0.02MB + Index: 0.03MB
ag_wc_webhooks: Data: 0.02MB + Index: 0.02MB
ag_wof_optins: Data: 0.02MB + Index: 0.00MB
ag_xyz_ihs_short_code: Data: 0.02MB + Index: 0.00MB
ag_yith_wcwl: Data: 0.02MB + Index: 0.02MB
ag_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB
ag_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
ag_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB
wp_pinterest_automatic: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3204
blocks: 3
cpt_iconic_wlv: 6
custom_css: 1
customize_changeset: 27
elementor_library: 1
jit_sales_offer: 1
mb_woc_wheel: 1
nav_menu_item: 70
page: 20
post: 28
product: 341
product_variation: 19123
pys_fb_event: 2
raccartlist: 58
racemailtemplate: 3
racmaillog: 429
racrecoveredorder: 2
revision: 27
shop_coupon: 11
shop_order: 355
shop_order_refund: 3
was: 5
wcst_trigger: 10
wpcf7_contact_form: 2
yith-wcpsc-wc-chart: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Contact Form 7: by Takayuki Miyoshi – 5.0.3
Elementor: by Elementor.com – 2.1.6
Google Authenticator: by Henrik Schack – 0.48
WooCommerce Linked Variations (Premium): by Iconic  – 1.0.0 – Not tested with the active version of WooCommerce
Kirki Toolkit: by Aristeides Stathopoulos – 3.0.33
PayPal for WooCommerce: by Angell EYE – 1.4.14 – Not tested with the active version of WooCommerce
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.3.9 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
WooCommerce Facebook Conversion Pixel: by Seravo Oy – 0.1 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.8 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.5.1 – 1.6.0 is available – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by Bolder Elements – 4.1.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.4
Yoast SEO Premium: by Team Yoast – 8.0
WP Rocket: by WP Media – 3.1
WooCommerce Variation Swatch: by WPAddon – 1.0.6 – Not tested with the active version of WooCommerce
Yoast SEO: WooCommerce: by Team Yoast – 8.0 – Not tested with the active version of WooCommerce
XL WooCommerce Sales Triggers: by XLPlugins – 2.7.0 – Not tested with the active version of WooCommerce
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.5.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist: by YITHEMES – 2.2.3 – Not tested with the active version of WooCommerce
Zendesk Chat Widget: by Zendesk – 1.4.12

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #203 - /terms-conditions/

### Theme ###

Name: Shoptimizer Child
Version: 1.0.0
Author URL: http://www.commercegurus.net
Child Theme: ✔
Parent Theme Name: Shoptimizer
Parent Theme Version: 1.1.3.1
Parent Theme Author URL: https://www.commercegurus.com/
WooCommerce Support: ✔

### Templates ###

```
</details>

**Comment by bainternet** [comment]
@kevin25 

Thanks for the detailed report,
Sadly, we can't really help, without seeing the code of the widget.

You should try asking the rd3 party plugin developers for guidance and they are more than welcome to contact us if needed.

thanks.
