### ISSUE TITLE
Login Widget

### ISSUE THREAD

**Issue by ThrudUK** [pojome/elementor#5436]
I'll assume this is a bug...

If a user get their credentials wrong when using the login widget they are redirected to the default WP login page rather than staying on the page with the widget.

**Comment by Jwalking26** [comment]
+1, I've tried to fix this myself, but coding is still fairly new. What you could do if you're in a pinch is customize the wordpress login page so users dont know you are using wordpress to build your site. The only thing is you'd need a plugin for that. I can't wait till they get this resolved.

**Comment by bainternet** [comment]
@ThrudUK 

This is not a bug this is how WordPress Login Form works.

Thanks.
