### ISSUE TITLE
[Feature Request] A visual way to create Font Groups that would not need to load font asset, just set the CSS property/declaration.

### ISSUE THREAD

**Issue by calebweeks** [pojome/elementor#5438]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

### What problem is your feature request going to solve? Please describe.
Elementor already integrates perfectly with Google Fonts and Typekit, but with "streaming only" font services like typography.com's [Cloud Typography](https://www.typography.com/cloud/welcome/) (which doesn't offer webfont downloads), the process of adding a Custom Font "Group" to the Elementor Typography font-family controls is somewhat non-visual/technical. It can be done, but requires some (basic) PHP knowledge to define and run the following functions: 

```
/**
 * Add Font Group
 */
add_filter( 'elementor/fonts/groups', function( $font_groups ) {
	$font_groups['my_fonts'] = __( 'MyFonts' );
	return $font_groups;
} );
/**
 * Add Group Fonts
 */
add_filter( 'elementor/fonts/additional_fonts', function( $additional_fonts ) {
	// Key/value
	//Font name/font group
	$additional_fonts['MyFont Font Family Name'] = 'my_fonts';
	$additional_fonts['MyFont Font Family Name2'] = 'my_fonts';
	return $additional_fonts;
} );
```
@bainternet describes this process in #5089 ("MyFonts compatibility") and in #4624 ("Custom fonts loaded from a theme").

### Describe the solution you'd like
_A visual way to create Font Groups:_ Since the above functions are already available in Elementor, would the Elementor team ever consider introducing a "visual" way (Elementor's greatest strength!) to add Custom Font "Groups", perhaps by enhancing the already created Custom Fonts workflow (see the _SPECIFIC DETAILS_ section below)?

This might be cool because it would allow typography.com Users (as well as future streaming-only webfont services) and 3rd-party plugins or themes that enqueue certain fonts already to have a visual way to include the font family into Elementor's Typography font family controls without actually uploading any of the fonts.

_SPECIFIC IMPLEMENTATION IDEA:_ Maybe Elementor could introduce the ability to create or define a Custom Font "Group" within the way we already create/define Custom Fonts. The Custom Fonts interface is already built, so rather than request a whole _new_ process for Custom Font "Groups", maybe there could just be a checkbox to say, "I do not need to upload this font" that, when checked, just has us define the Font Group name(s), etc. like in the functions above. In essence, this would allows us to "add" our font family to the Typography font-family controls without actually uploading any files (since our particular webfont service does "streaming only"). 

This ability would be perfect for us and would satisfy the need for Elementor to integrate with current or future webfont services, plugins, themes, etc. that enqueue a custom font by some other means. By piggy-backing on the Custom Font workflow and simply creating a Custom Font "Group", our work in Elementor would be done, and the fonts could be loaded/used in design. I do recognize there is a lot of technical, backend magic that would have to happen, but this would be cool and is Solution No. 1.

_Direct Integration with Typography.com:_ This is not a solution as typography.com has no API (see thread below). But because the typography.com integration is handled outside of Elementor, all we would need is the ability to set the CSS font-family property. I am just dreaming of a way to do this visually. 

### Describe alternatives you've considered
The only current alternative that I know of is using the functions above and manually defining the Field Groups and font families in the code.

Thanks for considering this either way! :-)

**Comment by calebweeks** [comment]
Hey @bainternet,

### Quick Background on why no API (adapted from super helpful comment [here](https://forum.webflow.com/t/how-to-use-fonts-from-typography-com-hoefler-co/16806/10))
In our case (to expand a little bit) Hoefler & Co. does not offer downloadable versions of their font-families as they are very, VERY, preoccupied with their webfonts being re-distributed. They have high prices for their fonts, which are considered first-class. Their webfont service is custom-made by them (without an API), and it is the only option available.

**Popularity**
They are highly regarded in the design community, and their designs quite coveted (commissioned by editorial, corporate, and institutional organizations we all know like Sports Illustrated, The New York Times, The Wall Street Journal, Tiffany & Co., Nike Inc., The United Nations, The Guggenheim Museum, etc.) which is why they have such security measures. Since they do not offer low prices or free fonts, and only distribute their own designs (they are a design studio), they are not as widely known as Typekit or Google Fonts, who aim to make many designs accessible.

However, within the niche of design, and especially premium design, they are regarded as among the best of the best.

### So can we integrate _without_ an API?
In short, yes, I think we can (already do)! The main way I could see Elementor being "compatible" is by giving Elementor Users the ability to create "Font Groups" in the "Custom Fonts" UI. Creating Font Groups can already be done with the code provided above, so in a sense we already are compatible (see below), but this request is more for the ability to create Font Groups visually.

There would be no additional "backend" work necessary (prone to produce errors, as far as I can tell) for a typography.com "integration" as the fonts are enqueued by the CSS Key/snippet we place (separately) in the head of the document. Literally, we just add the provided CSS Key to our pages, and the font declarations to our stylesheets, and we're ready to go.

In our case, with the Gotham font, we are instructed to use the _font-family: "Gotham A", "Gotham B";_ declaration (via CSS) to define our font-families ([screenshot](https://cl.ly/3v1k0T1S0w1Y)). Their "Delivery Agent" totally takes care of the rest ((see [How It Works](https://www.typography.com/cloud/how-it-works/)). 

I do see that being able to allow two font-family names may require an additional step to building all of this, but I bet the Elementor team could figure that out, too?

Thanks for reading if you made it this far. I know this is likely lower on the priority list(!), but it might be actually a quick and easy thing to do, so I just wanted to get the discussion started. It's just one more layer of credibility for Elementor amongst premium brands and designers. 

Thanks for an awesome tool in Elementor! :-)

**Comment by calebweeks** [comment]
P.S. Another way to say this is: "Elementor would not need to load the font asset, just set the CSS property."

**Comment by bainternet** [comment]
@calebweeks 

thanks,Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by portrayaloflife** [comment]
+1
