### ISSUE TITLE
[bug] Flip box 'apply link on whole box' animation issue

### ISSUE THREAD

**Issue by Artneo7** [pojome/elementor#5439]
![flip-box-apply-link-on-whole-box-bug](https://user-images.githubusercontent.com/17693529/44163005-6e409700-a098-11e8-8cb7-a1f76ef6062b.gif)

• Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

• Description
There's an issue with the animation when the Flip Box is set to 'apply link on whole box'.

• Steps to reproduce
Gif above explain the steps to reproduce this issue.

• Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

• Environment
<details>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.33 (Unix) OpenSSL/1.0.2g
	MySQL version: 5.7.23
	PHP Version: 7.2.8
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://dev.artneo.com.br
	Home URL: https://dev.artneo.com.br
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: pt-BR
	Timezone: -3
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.7
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	BackupBuddy
		Version: 8.2.8.2
		Author: iThemes

	Elementor
		Version: 2.1.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.3
		Author: Elementor.com

	Really Simple SSL
		Version: 3.0.5
		Author: Rogier Lankhorst, Mark Wolters

== Debug ==
	Errors: There are no errors to display
				
</details>

**Comment by arielk** [comment]
I can not restore this bug, please update to the latest version of Elementor Pro 2.1.5 and let me know if this solved your problem.

**Comment by Artneo7** [comment]
Yes, it's still happening (Elementor Pro 2.1.5).

**Comment by arielk** [comment]
Does this happen to you only in the editor or at the front of the site also?

**Comment by Artneo7** [comment]
It happens at the front of the website too. You can test it hovering on the 1 and 2 boxes (set to whole box). The 3 and 4 are fine (set to button only).
Link: https://dev.artneo.com.br/

**Comment by arielk** [comment]
We can't replicate this in our environment, so its got to be something in your setup (cache?), please contact our support at support @elementor.com with complete login information to access your website and reference to this issue and our support team will try to assist.

Thanks.
