### ISSUE TITLE
Images exported with templates

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#544]
I am able to easily save a template and export it, then import into another site. However, the images should go with it. They are often a key part of the template.

**Comment by arielk** [comment]
Of course, the images are supposed to go through with the content

**Comment by mizejewski** [comment]
That was not the case for me. I exported a template (json file) from my local dev site, then uploaded it to a live site. When I created a new page using that template, there were only placeholders. I had to track down and upload copies of all the images separately. Did I miss a step somewhere?

**Comment by mizejewski** [comment]
That was not the case for me. I exported a template (json file) from my local dev site, then uploaded it to a live site. When I created a new page using that template, there were only placeholders. I had to track down and upload copies of all the images separately. Did I miss a step somewhere?

**Comment by joshmarom** [comment]
The exported json contains the url references for all images in the page.
When json is imported to another, Elementor retrieves all those images from their original location and inserts them into the new site's media library.

If the original location is local, it will not be accessible by a remote site.

**Comment by mizejewski** [comment]
OK, makes sense. Thanks for clarifying.

**Comment by shimsa** [comment]
Hello,

when importing custom templates, Elementor looks for the location of images (or other media files) in the original location. If it is not available, it inserts a placeholder.png image instead. But images (with the same name) may already be located in the target WordPress library, but are unfortunately not used.

Please add, when importing a template, a check on the location of the image (by its name) in the target WordPress media library. That's the first check in the original location and the second checking the location in your own media library.

That would be very useful.

Thanks for consideration.

Tom

**Comment by BrookeRaraAvis** [comment]
+1
I also like to build on local and then upload to live.

**Comment by joshmarom** [comment]
Hi @shimsa Tom,

The concept of locating a media attachment by its file name, is not supported by WordPress, and could lead to unexpected results.

If you have a better idea on how that can be achieved technically, please tell me about it...

**Comment by techeshta** [comment]
> The exported json contains the url references for all images in the page.
> When json is imported to another site, Elementor retrieves all those images from their original location and inserts them into the new site's media library.
> 
> If the original location is local, it will not be accessible by a remote site.

I have json contains the live URL of other websites where I created page setup with elementor, then exported json and then importing with other URL and I'm getting any images with the media library. I can see images when trying to edit with elementor but that contains the original old URL of the website.

That should not be there.

**Comment by lupetalo** [comment]
I am having the issue with all images getting imported as placeholders even dought they do exist in the original website. In JSON file I can see the direct link to them and they are opening correctly. both locations are live websites.
