### ISSUE TITLE
How and where to use add_style_depends method

### ISSUE THREAD

**Issue by premitheme** [pojome/elementor#5447]
Hi,
Please is there any advice on how and where to use `add_style_depends`?
And why `get_style_depends` the same way `get_script_depends` work in preview?

In #1636 you announced that `get_style_depends` is added to do do the same job as `get_script_depends` but for styles, but it looks like it doesn't.

By the way, the scripts/styles I need to enqueue are registered by`wp_enqueue_scripts` action outside my plugin class (in functions.php) because I use them for other purposes not only the Elementor widget.

Thanks in advance.

**Comment by premitheme** [comment]
I get confused because `get_style_depends` doesn't work with preview mode unlike `get_script_depends `.

Then I found this comment https://github.com/pojome/elementor/issues/3670#issuecomment-372118400 which addressed my problem.

I think it would be nice if the developer documentation clearly mentions this difference between `get_style_depends` and `get_script_depends`, and include an example of usage in "Elementor Hello World" sample plugin.

Thanks anyway,
Ahmed

**Comment by Spartanace1024** [comment]
I have to agree here. I found this really confusing.
