### ISSUE TITLE
Be able to set positioning absolute | relative ... for each element

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5449]
No sure why there is no option for each element for this feature.
it is possible to do it via custom css, but I think its a MUST like margin / padding in advanced tab for each element.

There is a z-index already, but why no set position?

![image](https://user-images.githubusercontent.com/2544046/44204896-28013b80-a15d-11e8-906f-a12f9aff3f5b.png)

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by amindiary** [comment]
Sorry if my request was not clear enough.
I want to be able to set **position:absolute** for elements and enter values for **top/bottom/right/left**

something like this:
![image](https://user-images.githubusercontent.com/2544046/44399374-0b477800-a550-11e8-82c5-a669d44d1119.png)

**Comment by ideasandpixels** [comment]
Love this idea. If we could get to a place where editing is similar to Webflow, with complete control over all CSS for each element, we would be in a great position.

**Comment by AmibeWebsites** [comment]
Can this be added in one's own functions code by hooking into elementor/element/{$section_name}/{$section_id}/before_section_end?

**Comment by hufer** [comment]
Piotnet Addons For Elementor can do it for you
https://pafe.piotnet.com/#absolute-positioning
