### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by creizic** [pojome/elementor#545]
I have 2 problems on 2 websites
mine :) https://creizic.com as you can see i have a code error, coming from elementor, but I am not a developper, so I don"t know how to solve it.

The other problem is with this other website http://www.aepuc-formation.org/, I can"t open elementor anymore, it doesn't charge, as anyone allready meet this problem ? 

Thanks, sorry for my english doing my best...

**Comment by joshmarom** [comment]
Hi.
Your first issue seems to be related with wp-rocket plugin.
Elementor generally works well with wp-rocket.
Try playing with rocket's settings or contact their support.

Regarding the other issue, You may contact support@elementor.com with detailed info about your issue and our support team will try to assist.
