### ISSUE TITLE
Section Controls Changes Don't Trigger JS Hooks

### ISSUE THREAD

**Issue by pnpetroff** [pojome/elementor#5452]
It seems the section controls don't triggerd JS functions hooked to 'frontend/element_ready/section'.

If I extend the widget and adding new controls, all of them trigger the above hook on change.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
