### ISSUE TITLE
Expert Mode

### ISSUE THREAD

**Issue by willcitizen** [pojome/elementor#5455]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have experienced a few frustrations myself with some aspects of the elementor flexbox implimentation and I've seen discussions about absolute positioning and loading other attributes etc and even questions about css grid vs flexbox and just had the thought that perhaps there is a way to make elementor please everyone by exposing an expert mode which can be toggled on and off.  

**Describe the solution you'd like**
In expert mode additional controls would be exposed and some of the 'dumbed down' ones might be deprecated.  those additional controls at the style and layout level might allow you to directly manipulate flexbox behaviour to your liking, or even choose between flexbox and css grid implimentations (after all we're just assigning classes and css  to nested divs here people :D

While on the other side in the data and dynamic tags space you could allow direct embedding of small loops scripts using markdown (twig?), or even perhaps a visualized ui (ala pods templates and widgets) as query sources that would allow you to work with more complex data structures and issues like acf relationship and link fields returning arrays

**Describe alternatives you've considered**
Obviously many, but I like this :D

**Additional context**
This may sound like a massive shift in direction, but actually if I look at what the themebuilder aspects of elementor have brought and the sense I have at very least that the solution is almost fighting with itself at times to provide power and flexiblity without giving up it's end user charm and ease of use this approach to layers of complexity being exposed in the UI based on the level of expertise of the user, or access level, is something that you could introduce almost immediately as you add new functionality and start portioning them out into expert, or basic roles.  You could also shift this in the other direction and use this as a permissions model to create content editor roles with very limited functionality to only change content fields of the design, or only have basic style features like font and colour available to them.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
