### ISSUE TITLE
Elementor/Gravity Forms/Toolset Forms

### ISSUE THREAD

**Issue by HmCody** [pojome/elementor#5456]
This is probably not your issue entirely, but I thought you should be aware of it. I will also report to Gravity Forms and Toolset.

If I have both Gravity Forms and Toolset Forms activated on my site, I cannot edit a page with Elementor that has a Toolset view included. I get the "Preview could not be loaded" error. Disabling either plugin seems to fix the issue.

Also, if I have Gravity Forms activated, I get a server error 500 message if I try to save a page with a Toolset view, though the page actually seems to save and displays correctly on the front end. It is almost as if the highlight on the Update button is the only thing that is not happening.

Let me know if there is other info I can provide.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
