### ISSUE TITLE
Dynamic Author for the posts widget

### ISSUE THREAD

**Issue by ProckStar** [pojome/elementor#5457]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently there's no way to grab posts based on the author, such as on the author's profile page. I have seen this asked in Facebook groups, and while there's several widgets that allow you to dynamically handle authors information there's not an option on the posts widget, only a static author box exists.

**Describe the solution you'd like**
I would like the ability to set the author to be dynamically pulled in. Currently the only option in the content section of the posts widget is a static author. I have the ability to pull in any Elementor template into the customizer via widgets. I thought this would be a great way to create an Elementor section or block template that pulls in the recent articles of the user's profile being viewed.

**Describe alternatives you've considered**
I've tried using other elements to target the author (such as headline), and while they work for said elements, it does not for the posts widget.

**Additional context**
I'm including a screenshot of the static author box that would benefit from a dynamic author seting.

![elementor___author_recent_articles](https://user-images.githubusercontent.com/10425680/44246960-4d626980-a19e-11e8-806f-510cd4e593d7.jpg)

**Comment by bainternet** [comment]
@ProckStar 

This can be easily done with the new [Custom Query Filter](https://developers.elementor.com/custom-query-filter/)

eg:
```PHP
add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
 	// Pull your author dynamically however you would
	$author_id = 12;
	$query->set( 'author' $author_id );
} );
```

**Comment by ProckStar** [comment]
@bainternet, I'm confused as to why this wouldn't be considered a feature request. The solution you provided is a developer resource and not something I could see a typical end user doing.

I thought since Elementor is adding dynamic features, the one I have suggested would add value to Elementor.

To make my point ;-) ... I have no idea where I would add the code. I have looked at the linked page for the custom query filter, but the best guess I have is it's some sort of extension or plugin I would be creating.

Also, wouldn't your code example only pull in a static author? (author id of 12) Am I not understanding the code correctly?

Thank you ... Scott

**Comment by bainternet** [comment]
@ProckStar 

First, no one said it's not considered as a feature request, exampt you can alreay setup and define an author archive using the Archive posts widget which will pull the author's posts dynamiclly and automaticly for you.

> the best guess I have is it's some sort of extension or plugin I would be creating.

That and also in your theme's functions.php file would work as well.


>Also, wouldn't your code example only pull in a static author? (author id of 12) Am I not understanding the code correctly?

You misset the comment above that line `// Pull your author dynamically however you would` 

meaning the `12` i put in the example, is just that, an example and you should/could set it to what ever you want. If for example you want to set it up in an author archive you could use the the native WordPress `get_queried_object_id()` method to get the user id.

But if you are on a custom "profile" page, you would need to provide the author id yourself.

thanks.

**Comment by free2shout** [comment]
Good thread. Few errors though:

`elementor_pro/posts/query/my_custom_filter` is deprecated. Use `elementor/query/my_custom_filter` instead. 

There's one missing comma in: ´$query->set( 'author' $author_id );` right between the parameters.

`get_queried_object_id()` will return the current's post ID, not the author's. Use `get_the_author_meta('ID')` instead. 

So final Custom Filter will be: 

```php
add_action( 'elementor/query/my_custom_filter', function( $query ) {
        // The author of the current post
	$author_id = get_the_author_meta('ID');
	$query->set( 'author', $author_id );
} );
```

**Comment by kurosato** [comment]
> Good thread. Few errors though:
> 
> `elementor_pro/posts/query/my_custom_filter` is deprecated. Use `elementor/query/my_custom_filter` instead.
> 
> There's one missing comma in: ´$query->set( 'author' $author_id );` right between the parameters.
> 
> `get_queried_object_id()` will return the current's post ID, not the author's. Use `get_the_author_meta('ID')` instead.
> 
> So final Custom Filter will be:
> 
> ```
> add_action( 'elementor/query/my_custom_filter', function( $query ) {
>         // The author of the current post
> 	$author_id = get_the_author_meta('ID');
> 	$query->set( 'author', $author_id );
> } );
> ```

Thanks, this works and saved me tons of time :-) cheers

**Comment by violllettta** [comment]
The Archive Posts widget doesn't have a section for setting a query of any kind, let alone dynamic.

**Comment by artfauxlive** [comment]
So adding this to any of the WP code plugins would be sufficient for the "Posts" widget?
