### ISSUE TITLE
Ninja Forms Widget Conflict

### ISSUE THREAD

**Issue by lukecav** [pojome/elementor#546]
If you create a new page, then add a Ninja Forms widget to a section and hit save. The form will load fine on the layout. But when you go back to edit the layout, the section using the NF widget can not be edited.

The only active plugins where Elementor 0.8.0 and Ninja Forms 3.0.2, active theme was Twenty Sixteen.

**Comment by arielk** [comment]
I tried to check it, but it seems that everything works well :(

**Comment by arielk** [comment]
We released a new version, please update your plugin and let me know if your bug has been resolved

**Comment by bishgop** [comment]
@arielk The issue is still on; can't edit the page that has Ninja Forms short-code.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by arielk** [comment]
As it seems the conflict with Elementor began on the new version of Ninja forms (3.x.x), we try to figure out what has changed.

**Comment by bishgop** [comment]
After updating Elementor to Version 0.9.3, the issue with Ninja forms persists.

**Comment by arielk** [comment]
We still testing it, probably we will release it in the next version

**Comment by bishgop** [comment]
I am hoping the work is in progress; curiously waiting to use Elementor on Ninja Form pages.

**Comment by arielk** [comment]
Of course, we hope to release the update really soon

**Comment by lukecav** [comment]
@arielk 

Thanks!

**Comment by arielk** [comment]
New version released!
