### ISSUE TITLE
[PRO][BUG] Price Table - Dynamic Tag on URL field doesn't work

### ISSUE THREAD

**Issue by ludyamano** [pojome/elementor#5460]
Hi,

i've tested the dynamic tag for the URL button in the Price Table, but it doesn't work.

I compared the code with the Button module wich works fine with dynamic tag. Here's what i found:

The price-table.php code uses on render():
```
$settings = $this->get_settings();
```
but if you change that to:
```
$settings = $this->get_settings_for_display();
```
Then, dynamics tags will work fine and all the rest too.

Please, fix this for the next release. : )

**Comment by bainternet** [comment]
Fixed in 2.1.4
