### ISSUE TITLE
Setting a control's value from the click callback of a button control

### ISSUE THREAD

**Issue by kmgalanakis** [pojome/elementor#5461]
I have a button control and I've set a button click callback to do something upon button click.

Is it possible, in that callback to change the value of another hidden control using a model or something? 

I've tried to use `data.model.setSetting` (assuming that `data` is the callback argument) but it didn't work.

Any ideas? 

Thanks in advance.

**Comment by bainternet** [comment]
Not really sure what you are trying to achieve... can you add your code so we can take a peak?

**Comment by kmgalanakis** [comment]
Yeah, sure, let me explain what I'm trying to do.

I have this button control:

```
$this->add_control(
	'lorem_btn',
	array(
		'label' => __( 'Lorem ipsum', 'my_plugin' ),
		'type' => \Elementor\Controls_Manager::BUTTON,
		'separator' => 'default',
		'button_type' => 'default elementor-button-success',
		'text' => __( 'Add results', 'wpv-views' ),
		'event' => 'myPlugin:pageBuilderWidgets:elementor:editor:loremIpsum',
	)
);
```

and also this control

```
$this->add_control(
	'dolor_amet_hidden,
	array(
		'label' => __( 'Dolor sit amet', 'my_plugin' ),
		'type' => \Elementor\Controls_Manager::HIDDEN,
		'default' => 'false',
	)
);
```

Then in my JS file I'm doing

```
elementor.channels.editor.on( 'myPlugin:pageBuilderWidgets:elementor:editor:loremIpsum', self.loremIpsum);
```

and in `self.loremIpsum` I'm trying to do something like 

```
self.loremIpsum= function( data ) {
	data.model.setSetting( 'dolor_amet_hidden', 'true' )
};
```

but `setSetting` is not available. What am I missing?

**Comment by bainternet** [comment]
@kmgalanakis 

Thanks,

Well first, the event gets the control view as an argument and not data. So you can access the rest of the controls in that widget via the parent model something like:

```JS
self.loremIpsum= function( view ) {
	view._parent.model.setSetting( 'dolor_amet_hidden', 'true' )
};
```

Thanks.

**Comment by kmgalanakis** [comment]
It works great, thanks!

Another small question. Is the value of the `\Elementor\Controls_Manager::HIDDEN` control saved on the database?

**Comment by Paras16699** [comment]
@kmgalanakis Yes.

**Comment by dbjpanda** [comment]
Can we change the button control value itself. May be label, or event or text?
```
self.loremIpsum= function( view ) {
	view._parent.model.setSetting( 'lorem_btn', 'Connected' )
};
```

**Comment by yunhthemes** [comment]
Could you please say how to use it in repeater control? @bainternet

**Comment by nimaaminz** [comment]
Hi , thanks a lot guys , but I have a problem , 
I want to use setSetting to update control value of my widget . when in my container user move mouse (or any events) 
how I can do this ?
