### ISSUE TITLE
Feature Request: Randomize Background Image on Page Load

### ISSUE THREAD

**Issue by riverharbor** [pojome/elementor#5462]
When adding a background image to an element, would like to be able to load multiple images. 
Then Website randomly serve one image for the background per page load. This would be ideal in hero  sections.  Thanks.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by ipokkel** [comment]
@riverharbor see https://aedocs.webtechstreet.com/article/17-background-slider

Anywhere Elementor Pro has that functionality for sections where you can choose either a manual selection of bg images or from an ACF gallery (ACF pro required)

**Comment by joblux** [comment]
a part from the Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information:  where are we with this ?

**Comment by gdford** [comment]
Yes - this would be a welcome feature....
Is there a status on when this feature might be implemented?

**Comment by webdevs-pro** [comment]
If some one interest I developed similar functionality for client website
```
class BS_Random_Background_Slideshow_Images {

   const CONTAINER_ID = 'bg_slideshow';

   public function __construct() {
      add_action( 'elementor/frontend/container/before_render', array( $this, 'before_render' ), 10 );
   }

   function before_render( $widget ) {
      $settings = $widget->get_active_settings();

      if ( $settings['_element_id'] == self::CONTAINER_ID ) {
         $gallery = $settings['background_slideshow_gallery'];
         $rand_gallery = $this->shuffle_array( $gallery );
         $widget->set_settings( 'background_slideshow_gallery', $rand_gallery );
      }
   }

   private function shuffle_array( $array ) {
      if ( ! is_array( $array ) ) 
         return $array;

      $keys = array_keys( $array );
      shuffle( $keys );
      $random = array();
      foreach ( $keys as $key )
         $random[$key] = $array[$key];

      return array_values( $random );
   }
}
new BS_Random_Background_Slideshow_Images();
```
I use container and background slideshow to set images array. The container must have ID `bg_slideshow` or you can change it in class constant `CONTAINER_ID `

Every page load images will be shuffled

**Comment by iveyopt** [comment]
@webdevs-pro, thank you for providing that! Any ideas why it might not be working, other than not having the ID bg_slideshow on the container in question?

**Comment by gdford** [comment]
I dont think you understood my question.
The load gallery with random images works fine...
What I want to do is have the images from a folder fill the gallery with
rerandomized images everytime the page loads or the page is refreshed.
Lets say there are 100 images in the folder and 10 images in the gallery.
Everytime you open the page I want 10 images pulled from 100 to fill the
gallery.
*Thanks,*

*Gary Ford*
*254.631.8562*
*---*
*"Remember, if all you have is a hammer then everything looks like a nail"*
      Bernard Baruch

**Comment by webdevs-pro** [comment]
@gdford please check one of my website: https://cerkva-hsd.info/
on hero section of home page there is always random around random 100 images from over 5000 uploaded in WP media gallery.

**Comment by qoqnus13** [comment]
@webdevs-pro thank you for your code. if i want to choose one background only from a gallery and keep elementor background setting (as overly, mause effect, transition ,...) what changes I must do? and sorry, but where do i use this code?

**Comment by dfranz1** [comment]
I can't seem to get the code working, the slideshow is just playing normally. I put the code in my Functions file so I'm not sure where else it would go. Any ideas?

**Comment by webdevs-pro** [comment]
@dfranz1 Hey, @dfranz1 you have to set section ID to `bg_slideshow`

**Comment by dfranz1** [comment]
@webdevs-pro Thanks, I double checked and I had in the Class instead of ID. Thanks it working now!

**Comment by voxoff79** [comment]
Hi guys, this code its not working anymore with the new Elementor 3.26.0. Can anyone confirm this please?
Thnks
