### ISSUE TITLE
Suggestions for Ads and Popups

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#5463]
Hello guys,

I use "AdRotate" and "Advanced Ads" plugins to insert ads. I created a template (section) with the Elementor and inserted the shortcode in those two plugins, but both plugins do not read the shortcode of the Elementor. This is normal?

And I wanted to take advantage of the contact to give 2 suggestions:

1- Elementor could give you the ability to create ad schemes just like these plugins (AdRotate and Advanced Ads, for example).
These ads, we could create designs with Elementor and select where we want it to be viewed (start, middle, end of content, header, footer, sidebar and ect); could also select which pages the ad should be viewed (categories, custom categories, pages, posts and ect); and also be able to put the start and end date view; it could also join more than 1 ad into ad groups (this allows the ad group to be placed in a certain place, only once, and then just go through changing the ads in a center pane).

2- Another suggestion ... you could give the possibility to create popup, as well as the Ninja Popup plugin.
In these popup, could also determine in which categories, custom categories, pages, posts and ect should be shown the popup; and also be able to put the start and end date of the popup.

This would help to decrease the number of plugins we use.

Thank you.
Rodrigo Carlos

**Comment by bainternet** [comment]
@proddigital 

1) This should be a 3rd party plugin and not something inside Elementor.
2) A popup is something that is currently under active development here.

thanks.
