### ISSUE TITLE
Open cart off canvas widget when product is added to cart

### ISSUE THREAD

**Issue by sammyjeanmarc** [pojome/elementor#5465]
Hey guys, just using the Elementor Woocommerce setup and the new cart side bar widget and was wondering how I could achieve the cart sidebar to open when a new product is added? Any thoughts

I noticed this was a good UX point that Nike stores and other brands seem to use as it can be confusing when a user adds a product to the cart and nothing happens except an ugly Woocommerce alert notification that most get rid of.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
