### ISSUE TITLE
Accessiblity issue: Elementor creates empty links

### ISSUE THREAD

**Issue by bendqh** [pojome/elementor#5466]
Sometimes, and maybe for various reasons, Elementor creates empty links (usually contentless HTML tags with empty href attributes). I copy a detailed [discussion](https://stackoverflow.com/questions/51906185/whats-the-most-general-way-to-find-all-empty-links-empty-tags-containing-an-hr) I started at StackOverflow regarding this:

> I scanned the homepage of my website through a **[accessibility][1] problem scanner**; A tool I use to find problems in my markup and information-presentation, in the context of *web accessibility*.
>
> Using the [WAVE report tool][2], I found two problems: Both of which are "empty links".
> 
> Maybe I missed that but I don't get from the tool what these links are and how to find them so I would delete them via my *WordPress* **page builder** (*Elementor*), the tool with which I created the markup for this site.
> 
> An accessibility specialist told me that doing CTRL+F then searching in source for say `<a href=""></a>` isn't efficient as there can many biases and AFAIK an empty link doesn't even have to be a `a` tag.
> 
> My question is how to find empty links, do you know a general, reliable technique I could use to gather reasonable data about these links and remove them.

---

As this is an accessibility problem, you will likely consider how to cope with this.

  [1]: https://en.wikipedia.org/wiki/Accessibility
  [2]: http://wave.webaim.org/

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Out of the box, Elementor doesn't create anything so without replication steps we can't really help here.
