### ISSUE TITLE
Make text editing consistent

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#547]
I'm wondering why all areas that allow text editing don't offer both the visual/text option? Making it consistent across widgets would be helpful. 

![text-editor](https://cloud.githubusercontent.com/assets/974442/18404058/277afc10-769d-11e6-8e0a-88bc618d566e.png)

---------------

![text-editor2](https://cloud.githubusercontent.com/assets/974442/18404057/2779da88-769d-11e6-8dca-65dc1bc98be1.png)

**Comment by joshmarom** [comment]
We will consider adding rich text editor in all text areas.

Thanks for the feedback.

**Comment by mizejewski** [comment]
Thanks Josh

**Comment by arielk** [comment]
Merged #176
