### ISSUE TITLE
Custom post types & fields

### ISSUE THREAD

**Issue by gatenet** [pojome/elementor#5470]
I have tested elementor pro with ACF & CPT UI (dosen't show the ACF label in dynamic)
Also with Pods (shows the label but not the key)
With toolset (works fine and shows all fields, but not some like checkboxes) and the problem is that when i exit from the template and try to re enter then this is what happens
Fatal error: Uncaught Error: Call to undefined function ElementorPro\Modules\DynamicTags\Toolset\Tags\types_render_field() in C:\laragon\www\toolsettest\wp-content\plugins\elementor-pro\modules\dynamic-tags\toolset\tags\toolset-text.php:39 Stack trace: #0 C:\laragon\www\toolsettest\wp-content\plugins\elementor\core\dynamic-tags\tag.php(33): ElementorPro\Modules\DynamicTags\Toolset\Tags\Toolset_Text->render() #1 C:\laragon\www\toolsettest\wp-content\plugins\elementor\core\dynamic-tags\manager.php(206): Elementor\Core\DynamicTags\Tag->get_content() #2 [internal function]: Elementor\Core\DynamicTags\Manager->get_tag_data_content('2c16495', 'toolset-text', Array) #3 C:\laragon\www\toolsettest\wp-content\plugins\elementor\core\dynamic-tags\manager.php(99): call_user_func_array(Array, Array) #4 C:\laragon\www\toolsettest\wp-content\plugins\elementor\core\dynamic-tags\manager.php(64): Elementor\Core\DynamicTags\Manager->parse_tag_text('[elementor-tag ...', Array, Array) #5 [internal function]: Elementor\Core\DynamicTags\Manager- in C:\laragon\www\toolsettest\wp-content\plugins\elementor-pro\modules\dynamic-tags\toolset\tags\toolset-text.php on line 39

Then i have to delete it and recreate it again.

**Comment by levi-beers** [comment]
Not sure if related, but there's definitely unresolved issues with ACF, specifically [#5344](https://github.com/pojome/elementor/issues/5344) which was closed and remains an issue.

**Comment by bainternet** [comment]
@gatenet 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Also, I know this was fixed in an earlier version 2.1.2 so make sure you update.

@levi-beers not related, thanks
