### ISSUE TITLE
Improve section handle behavior

### ISSUE THREAD

**Issue by reardestani** [pojome/elementor#5473]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Based on this function(http://take.ms/Ju15X), the section handle goes inside only if the first section offset is less than 25px and it works well but the problem is that when we have a header(it has high z-index for some reasons) in page (http://take.ms/JbIWF), the handles should go inside so we can see handles.

## Steps to reproduce

Create a page that header has high z-index and the content has no padding so it sticks under the header with no spacing.

## Isolating the problem
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@reardestani 

Thanks for reporting, we are aware of that and that's why we are pushing #1165 which should provide a solution. should be out in 2.2 beta in a few days.


thanks.
