### ISSUE TITLE
HOW TO POST TO acf-to-rest-api, if all the posts are forced ajax?

### ISSUE THREAD

**Issue by NJseo** [pojome/elementor#5478]
Here is what I need to post to rest end points for search results but forced ajax is throwing me for a loop?

This is how I need to post. If I use a redirect, I loose that post data.
action: http://localhost/wp-json/wp/v2/posts/1

<form action="http://localhost/wp-json/wp/v2/posts/1" method="POST">
  <?php 
    // https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
    wp_nonce_field( 'wp_rest' ); 
  ?>
  <label>Title: <input type="text" name="title"></label>
  <h3>ACF</h3>
  <label>Site: <input type="text" name="fields[site]"></label>
  <button type="submit">Save</button>
</form>

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@NJseo 

Assuming you are talking about the Forms widget, it was never meant for that.

However, you can create a webhook that will run on ajax submit and from there get your data via the PHP API instead of the REST API.

Other than that, its simply not meant for this kind of things. I can be done but with some major custom coding.
