### ISSUE TITLE
scrollTop conflict with 3rd party addon

### ISSUE THREAD

**Issue by bdthemes** [pojome/elementor#5479]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When i implementing a scroll button with my own javascript (we implimenting scrollTop with more features not only scroll) it's not work properly because it's only work the elementor scrollTop function (http://prntscr.com/kkshdl). 

So is it possible to change the selector **elementor-element** to any specific class so if anybody need the scrollTop so they can use that class? 

## Steps to reproduce

Please look here: https://bdthemes.net/demo/wordpress/element-pack/elements/scroll-button/

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>				
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.19
	MySQL version: 5.5.5
	PHP Version: 5.6.19
	PHP Max Input Vars: 3000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://192.168.1.100/element-pack
	Home URL: http://192.168.1.100/element-pack
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 6
	Debug Mode: Active

== Theme ==
	Name: Quick
	Version: 1.0.0
	Author: BdThemes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Anywhere Elementor
		Version: 1.0
		Author: WebTechStreet

	bbPress
		Version: 2.5.14
		Author: The bbPress Community

	BdThemes FAQ
		Version: 1.0.0
		Author: bdthemes

	BdThemes Portfolio
		Version: 1.0
		Author: bdthemes

	BdThemes Testimonials
		Version: 1.1.0
		Author: bdthemes

	Booked
		Version: 2.0.9
		Author: Boxy Studio

	BuddyPress
		Version: 2.9.3
		Author: The BuddyPress Community

	Caldera Forms
		Version: 1.6.0
		Author: Caldera Labs

	Contact Form 7
		Version: 4.8
		Author: Takayuki Miyoshi

	Download Monitor
		Version: 4.0.6
		Author: Never5

	Duplicator Pro
		Version: 3.5.7
		Author: Snap Creek

	Easy Digital Downloads
		Version: 2.9.1
		Author: Easy Digital Downloads

	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.0
		Author: Elementor.com

	Element Pack
		Version: 2.5.3
		Author: BdThemes

	Instagram Feed
		Version: 1.4.9
		Author: Smash Balloon

	MailChimp for WordPress
		Version: 4.1.3
		Author: ibericode

	Meta Box
		Version: 4.14.11
		Author: MetaBox.io

	Ninja Forms
		Version: 3.2.21
		Author: The WP Ninjas

	Optimize Database after Deleting Revisions
		Version: 4.4.2
		Author: CAGE Web Design | Rolf van Gelder, Eindhoven, The Netherlands

	Quform
		Version: 2.1.0
		Author: ThemeCatcher

	Regenerate Thumbnails
		Version: 3.0.2
		Author: Alex Mills (Viper007Bond)

	SMTP Mailer
		Version: 1.0.5
		Author: naa986

	SVG Support
		Version: 2.2.11
		Author: Benbodhi

	TablePress
		Version: 1.9
		Author: Tobias Bäthge

	TablePress Extension: Responsive Tables
		Version: 1.4
		Author: Tobias Bäthge

	The Events Calendar
		Version: 4.6.1
		Author: Modern Tribe, Inc.

	WooCommerce
		Version: 3.4.4
		Author: Automattic

	WPForms Lite
		Version: 1.4.4.1
		Author: WPForms

== Debug ==
	Errors: 
		SyntaxError: Unexpected token ,
			at http://192.168.1.100/element-pack/wp-admin/post.php?post=28006&action=elementor - 6:23
			2018-08-01 06:21 +00:00
			x 2 times

		SyntaxError: Unexpected token <
			at http://192.168.1.100/element-pack/wp-admin/post.php?post=28006&action=elementor - 6:23
			2018-08-01 06:20 +00:00
			x 2 times

		SecurityError: Blocked a frame with origin "http://192.168.1.100" from accessing a cross-origin frame.
			at http://192.168.1.100/element-pack/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.2 - 5853:24
			2018-07-24 02:39 +00:00

		SyntaxError: Unexpected token <
			at http://192.168.1.100/element-pack/wp-includes/js/underscore.min.js?ver=1.8.3 - 5:15110
			2018-07-17 09:05 +00:00
			x 4 times

		SyntaxError: Unexpected token <
			at http://192.168.1.100/element-pack/wp-includes/js/underscore.min.js?ver=1.8.3 - 5:15157
			2018-07-17 08:51 +00:00

		TypeError: Cannot read property 'match' of undefined
			at http://192.168.1.100/element-pack/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.1 - 10936:32
			2018-07-12 07:05 +00:00

		TypeError: Cannot read property 'statusText' of undefined
			at http://192.168.1.100/element-pack/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.1 - 1042:22
			2018-07-12 05:59 +00:00

		TypeError: Cannot read property 'statusText' of undefined
			at http://192.168.1.100/element-pack/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:17387
			2018-07-09 11:52 +00:00
			x 10 times

		SyntaxError: Unexpected token var
			at http://192.168.1.100/element-pack/wp-admin/post.php?post=28004&action=elementor - 20:6
			2018-07-09 05:10 +00:00

		SyntaxError: Unexpected token }
			at http://192.168.1.100/element-pack/wp-admin/post.php?post=28006&action=elementor - 14:44
			2018-07-09 05:08 +00:00
			x 6 times
</details>

**Comment by bainternet** [comment]
@bdthemes 

Not sure what you are asking but looking at the page you linked, I see it working just fine.


thanks.
