### ISSUE TITLE
Padding & margin setting

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#548]
1. Can you clarify something? Margin and padding settings are blank by default, but what _is_ the default? In some cases adding 0 to a blank field suggests that blank does not equal zero.
2. Related to that, I would like to be able to tighten up my pages. Even if I set margin and padding to zero for section, column, and widgets, there is still a lot of extra space. See https://beta.library.ucsf.edu/ask-an-expert/ and the attached image. For example, I'd like to lessen the space between the Lit Search/Publishing section and the Faculty/Data Science section. **How can I affect that space?** I'm having a similar problem trying to lessen the padding on the Meet Our Experts icon box widget (lower part of page and styled like a button)

![margin-padding](https://cloud.githubusercontent.com/assets/974442/18405014/4f0c4274-76a3-11e6-8bf8-ee29b6af5720.png)

---

![tighten](https://cloud.githubusercontent.com/assets/974442/18405015/4f0c39c8-76a3-11e6-9c9e-e42340cd36b5.png)

**Comment by joshmarom** [comment]
Did you try to edit "Columns Gap" in the section?

**Comment by mizejewski** [comment]
Yes, but that only affects the space **between** columns. As #2 above says, I am concerned with all the extra space between **sections**. Also, what's the answer to #1 as they may be related? Basically it seems like even when I set everything to zero margin and padding, a lot of space remains and I'd like to know how to lessen it. Thanks

**Comment by mizejewski** [comment]
Let me try to explain more clearly. Elementor defaults to blank fields for all margin and padding. Can you make all those defaults transparent? The blank default does not always seem to be zero (see attached examples.) The ability to affect the margin/padding for the section, column, and widget promises great control, but the mystery defaults make it confusing.


Suggestion: add a top level setting where the user could choose the preferred default to make all margin/padding default = 10px or 2% for example.

**Elementor mystery default**

![zero_padding_column](https://cloud.githubusercontent.com/assets/974442/18562743/ea7ea6d0-7b39-11e6-93b3-a07256752b16.png)

-------------------------------------------------------
**Set padding to zero**

![blank_default](https://cloud.githubusercontent.com/assets/974442/18562742/ea7c0268-7b39-11e6-9022-504a10e65099.png)

**Comment by dreweastmead** [comment]
yes i have this same question too!

**Comment by mizejewski** [comment]
Any clarification or planned improvements @joshmarom?

**Comment by arielk** [comment]
Unfortunately we can not add to the current value of the margin or the padding because it depends on other settings of the section. So I close the issue for now.

Thanks for the feedback, we'll consider this issue in the next changes made in the future.

**Comment by mizejewski** [comment]
So in the example above, how can I make the text block closer to the image? Margin and padding appear to be blank (?) or zero but there is still a space between the elements.

**Comment by mauryparra** [comment]
I had the same issue, you can solve it by going to column settings and in custom css put:

selector .elementor-widget:not(:last-child) { 
    margin-bottom: VALUE;
}

where VALUE is the margin you want between the elementor widgets.

@arielk Would be great if in the column settings we could specify this, since even when using no gap on section, still uses a 20px margin on the widgets
