### ISSUE TITLE
No fallback image for video widget (as for background video)

### ISSUE THREAD

**Issue by Caroline-Elisa** [pojome/elementor#5485]
A fallback image can be set for background videos but not the video widget.

This is a big issue for Chrome, mobiles and other browsers without autoplay as the widget just shows a blank box.

e.g. https://monosnap.com/direct/9NU4hzj1GM3ZDjZ6Y0xE2EnGs4QLgz

**Comment by bainternet** [comment]
added in v2.2.4 

> Tweak: Added Poster option for Self Hosted in Video widget

thanks.

**Comment by puregraphx** [comment]
@bainternet Could you please show me where the fallback field is for the Video Widget?
