### ISSUE TITLE
Timeline feature in Elementor

### ISSUE THREAD

**Issue by knutkl** [pojome/elementor#5487]
Hi!
I'm looking for a timeline feature in Elementor, but it seems not to include that. 
Can you consider to implemnet that? 
I find others plugins for wordpress that offer a timeline functionality, but it would be a great thing to have it direcctly into Elementor. 

Best regards
Knut Klevstad

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, there are 3rd party plugins that give you this functionality.

Thanks for the feedback.
