### ISSUE TITLE
Live editor not showing sections for editing

### ISSUE THREAD

**Issue by olaweb** [pojome/elementor#549]
I have  a problem using the elementor, after a while using it,  i discovered some sections become invisible on the live editor, that means i can't edit these sections any more even though they still exist when i view the live page. Please do you know what the problem is? 
I have tried deactivating all my plugins and it didn't solve the problem, when it was first occurred i updated to the latest elementor plugin and that still didn't solve the problem

Thanks

**Comment by joshmarom** [comment]
Please contact support@elementor.com with a detailed description of your issue.
