### ISSUE TITLE
Show widget per breakpoint

### ISSUE THREAD

**Issue by benhartwich** [pojome/elementor#5490]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For now I see all widgets, which I´ve set to the different devices / breakpoints. It should be possible to see only the widgets and settings, which I´ve set for the current breakpoint I´m viewing.

**Describe the solution you'd like**
Whenever I use the Advanced => Responsive options, the widgets should be only possible at the set breakpoint not every widget at every breakpoint. Also there should be an optical hint at the settings and the breakpoints at the bottom that there are settings set, which are related to another breakpoint. UXBuilder of flatsome has solved this very nice.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
