### ISSUE TITLE
 Elementor 2.2.0 - Beta Release

### ISSUE THREAD

**Issue by bainternet** [pojome/elementor#5493]
Hey Elementor testers!

Congratulations! You are the first to receive Elementor version 2.2 — the latest version that includes a handful of useful, innovative features. Please go over the list below, one by one, and help us test this version for bugs and conflicts.

In this release, we put the emphasis first and foremost on improving Elementor’s workflow. We focused on expanding the editing capabilities for advanced designs, as Elementor keeps growing, along with the needs and demands of our users.

**Please go over each new feature detailed below, and test it out on your dev environment.**

## Introducing Navigator
The Navigator is a navigation tree window providing easy access to every element in the editor (#1165). Navigator enables the user to drag elements throughout the page and edit them, quickly and easily.

Navigator is particularly useful for long pages or pages with complex multi-layered design, and for elements combining Z-Index, negative margin, position absolute, etc. It enables you to gain full control of the editing process.
![unnamed](https://user-images.githubusercontent.com/660572/44403403-03420500-a55d-11e8-8d16-f8804f3efcfd.gif)

Using Navigator, you can access every element with just a click and easily change the order of the elements on your page. You can also give names to elements to quickly identify and edit them.

What’s more, we added the ability to hide a specific element so you can better focus on the design. And of course, the right-click options will be functional for the elements appearing in the Navigator window.

You can drag the Navigator window anywhere on the page, or pin it to the side of the screen by dropping it inside the blue line indicator.

To open the Navigator you have three simple options:
1. Click on the layers icon in the footer of the panel.
2. Use the keyboard shortcut Cmd/Ctrl + I
3. Right-click any element and then click on Navigator. This automatically redirects you to the specific element in the navigation tree.

## Autocomplete URL for Internal Linking
In version 2.2, we added the Autocomplete feature to all URL fields in the panel. From now on, once you start typing in the URL field, the system will search for the text throughout all pages, posts, and media files in your WordPress. Then simply choose the relevant links from the search results.

The Autocomplete feature is, in fact, one of the oldest feature requests (#255), actually, it is celebrating two years now! We are certainly happy to finally release it and thank everyone who kept pushing for it.

![unnamed-1](https://user-images.githubusercontent.com/660572/44403448-22409700-a55d-11e8-957f-ac2e84128240.gif)

## Handles Are Back!
In the previous version, we changed the way elements are edited. We replaced the old edit buttons with a right-click to provide more advanced editing capabilities — including adding access to copy/paste and direct access to the navigator.

Immediately after the release, we received countless requests to restore the previous capabilities of the edit buttons. Therefore, in this version, we added the option to restore the old edit buttons (#4981). This means that if you want to work with both methods you can set the display of these buttons in Settings > Advanced > Editing Handles > Enable.

![unnamed-2](https://user-images.githubusercontent.com/660572/44403472-371d2a80-a55d-11e8-911f-04eb12d7fabd.gif)

## Debug Bar
In this version, we added the ability to better debug the pages you load, generally in the development environment but not exclusively.

The Debugger will help you understand why a particular template or theme file is being loaded, or whether they conflict with each other. It will also help you understand the hierarchy of files and locations that generate the page. The Debugger is located in the admin bar throughout your WordPress site.

How to activate the Debugger?

1. If you are working in a development environment where the `define( 'WP_DEBUG', true );` in `wp-config.php`, then the Debugger is automatically active.
2. To manually activate the Debugger, go to the settings area of Elementor, under Tools> Debug Bar > Enable.

## More Improvements
* Added Getting Started page after the first install
* New interface for Filter CSS control
* Added Reverse Columns for tablet (#2070)
* Added an additional aspect ratio (21:9) for the Video widget
* Added a “Lazy Load” option for the Video widget (#5189)
* Remember panel width when switching to preview mode (#2414)
* Added `Cmd/Ctrl + I` hotkey for the Navigator
* Added `Cmd/Ctrl + Shift + V` hotkey for paste style

## How to Install Beta Version
If you still haven't enabled beta testing in Elementor, please follow these steps:
1. Go to Elementor > Tools > Versions
2. Enable the beta tester feature
3. Go to the Dashboard > Updates and update to the latest beta version.

You can also download the new version here: https://downloads.wordpress.org/plugin/elementor.2.2.0-beta1.zip

## Notes
[Elementor Beta - Sign Up now for our elite group of early access testers](https://my.elementor.com/beta/)

**Designated time for release**: August 28, 2018 (Estimated)

**For bugs and remarks, please reply with a comment in this issue here on GitHub.**

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Many thanks for your support and help!

**Comment by Jorihlen** [comment]
Thank you very much for this new set of functions, the improvements are always very welcome.
I think that it would be very opportune to be able to name / rename the sections for a better identification, especially in long pages and in the cases that appear collapsed in the Browser.
Thanks again ... great job !!

**Comment by nickdgreen** [comment]
The new Navigation functionality will be incredibly useful for fine-tuning the design a page. I was expecting that by giving a section a CSS ID that the ID would appear in the navigation pane in place of the "Section" designation. Is that not the case or is there some other means of naming sections so they are easily identified in the Navigation pane?

**Comment by willcitizen** [comment]
I second @nickdgreen's suggestion - they navigation pane looks incredibly useful, but you need a mechanism to identify elements and using assigned css ids seems a great way to facilitate that.  If you've ever worked with complex photoshop layers, or vector design apps like Inkscape you will understand how necessary this becomes.

**Comment by obe1968** [comment]
Having a toggle on off for css class names and ids would be VERY cool. David Beckwith did a video back in the day showing that information, but never released the hack. That would be a helpful feature ;)

**Comment by bentalgad** [comment]
I think simple sections, columns and elements naming in the new amazing navigator is a must! the idea in that navigator is to easily navigate through the different sections and elements of your page and it's not very useful when you see a long list of "section, section, section" tabs (do i suppose to count them to know which one is the one i'm looking for?).

I personally think it should be easy as clicking on the section again and change it's name.

**Comment by SniffleValve** [comment]
So far, so good!  ... all is working as expected on my local test site :) 

For all those wanting the ability to rename the items in the navigator, please watch the vid from @sododesign above ... it's there already! :) 

On Windows, I just triple-click the title and start typing my own names :)

Cheers!
Lyle

**Comment by willcitizen** [comment]
Confirming @shenickisland 's feedback double-click to name items in the navigator is awesome, but is not working on Safari (version 11.1.1)

**Comment by bainternet** [comment]
Thanks, everyone.

Yes, you can set the name of the Element in the Navigator by "double click" on it, We'll try to make it more intuitive.

[**@willcitizen**](https://github.com/willcitizen) commented on [Aug 22, 2018, 12:44 PM GMT+3](https://github.com/pojome/elementor/issues/5493#issuecomment-414975848 "2018-08-22T09:44:32Z - Replied by Github Reply Comments"):
> Confirming @shenickisland 's feedback double-click to name items in the navigator is awesome, but is not working on Safari (version 11.1.1)


[**@shenickisland**](https://github.com/shenickisland) commented on [Aug 22, 2018, 5:19 AM GMT+3](https://github.com/pojome/elementor/issues/5493#issuecomment-414885404 "2018-08-22T02:19:11Z - Replied by Github Reply Comments"):
> Double clicking the section etc name in the navigator does not work in Safari. Works fine in Chrome.

Safari bug confirmed, should be fixed soon.

thanks.

**Comment by obe1968** [comment]
I think it works fine, but did not even know you could do it, and not all
details are released with beta releases. I wish when Elementor releases the
beta versions to include a well descriptive write of what features or
sub-features of a feature are in the beta, so beta testers know what to
look for. And include a conditional statement, all features may not be in
the full version after testing.

Just a thought ;)

Sincerely,

Shawn

**Comment by lucafagherazzi** [comment]
Hi everyone, I really appreciate the navigator: great job guys!

Same problem as @Perchpole

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to v2.2.0 Beta 2.

This beta release includes:

Tweak: Added icon for the Debugger in the admin bar

- Fix: Different videos with the same image showing the same video
- Fix: Responsive controls hiding elements in edit mode
- Fix: Inline editing in Progress Bar widget
- Fix: Increase `z-index` value for dynamic tag settings popup
- Fix: Rename elements in the Navigator for Safari browser
- Fix: Minor CSS glitch in add new section component
- Fix: IE11 bug in case of `min-height` mixed with `align-items: center`

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Thanks again to everyone.

**Comment by donwattz1459** [comment]
I agree. Template links aren't necessary in the URL. Was very confusing and I know one of my clients is going to be rushing and click the wrong one.

**Comment by Perchpole** [comment]
Dynamic content does not render ACF date field in correct format. Even if the date field is set to display as d/m/y, Elementor renders it as ymd.

**Comment by shenickisland** [comment]
@bainternet The issue with renaming items in Safari persists with beta2. Both in Safari 11.1 and 12 (with the Mojave beta).

**Comment by black-eye** [comment]
Agreed with @avermat and @donwattz1459 on the templates links.
Fortunately, Elementor link autocomplete uses WP native engine, so we can use wp_link_query_args filter https://codex.wordpress.org/Plugin_API/Filter_Reference/wp_link_query_args to modify the query.

On the other hand, it's really not necessary (IMHO it's even dangerous) to list the templates there. I can imagine what mess could be done by referencing those by unexperienced users. My clents actually shoudn't even know, there's such a thing as Elementor Template.

So it would be a good behavoiur to hide them in link list (both WP native & Elementor's) by default.
I can make a new issue on that, if you want, since this is not a strictly 100% E 2.2 beta issue.

**Comment by redlagoon** [comment]
@bainternet Lovely udpates as ever, but...

It's clear you guys know about the developers that wanna work with Elementor, since you put things here and there, but it's been too long and we still don't have a way for developers to register their own blocks / templates in the "Insert from Library" screen.

That one thing alone is what makes VC better in terms of actually building pages.

Please do reconsider it.

**Comment by SniffleValve** [comment]
@bainternet 

Re: E 2.2 beta 3

Curious as to why the renaming of Columns to Inner Section.

In addition to confusing those recent to Elementor, it renders yours, mine and everyone else's tutorials obsolete! :) 

I humbly suggest you reconsider.

Cheers!
Lyle

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to v2.2.0 Beta 3.

This beta release includes:

- Tweak: Changed the name of Columns widget to Inner Section to reduce confusion
- Tweak: Polish for 'E' icon loader style
- Fix: Added compatibility for IE11+ by adding IE CSS via JS (#5510, #5530)
- Fix: Added `nowrap` for custom name element in the navigator
- Fix: Hide Elementor Library CPT from Autocomplete URL (thanks for the heads up)

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Thanks again to everyone.

**Comment by SencilloDS** [comment]
By using navigator it would be nice when click to make some widget, column or section invisible all other elements stay on their position and not move up to have a better possibility for designing in real "wysiwyg".

**Comment by willcitizen** [comment]
**PROBLEM WITH CUSTOM LOCATIONS**

I've noticed an issue I assume that it was introduced in the beta as I have not touched this portion of my project for about 2 weeks.   I have just upgraded to beta 3 and can confirm that the problem persists there.

I have written my own functions and an acf options page to register custom locations (as per the documentation). This was working perfectly however all  templates assigned to one of my custom locations now say unsupported, as per the screenshot below)

![image](https://user-images.githubusercontent.com/41669565/44657858-b350bb80-a9fe-11e8-9be3-7d1d4e7a0aff.png)

The locations drop down is also not available when I choose section from add new.

However all of my content assigned to custom locations is still rendering in the correct positions and when I access locations settings from within the editor my locations are all still there.

![image](https://user-images.githubusercontent.com/41669565/44658301-9b7a3700-aa00-11e8-881c-6f3c0fe73314.png)

**Comment by nickdgreen** [comment]
The issue with duplication posted by KiQdev is still present in Version 2.2.0-beta3 - I Title element dragged from the Section into a column in an Inner Section is duplicated.

**Comment by silvioghedin** [comment]
I think the change of the name of Columns widget to Inner Section is going to confuse more

**Comment by arielk** [comment]
@SniffleValve @silvioghedin Please read the discussion about this change in our FB group:
https://www.facebook.com/groups/Elementors/permalink/1649282135197566/

@KiQdev Thanks for your feedback, we'll look into it.

@willcitizen I'm not sure it's related to this version, so open up a new issue and we'll check it out.

**Comment by BrookeRaraAvis** [comment]
Could you please provide the file download for v2.2.0 Beta 3? For some reason, my local beta install isn't receiving pushed updates.

**Comment by arielk** [comment]
@BrookeRaraAvis Try this link: https://downloads.wordpress.org/plugin/elementor.2.2.0-beta3.zip

**Comment by bainternet** [comment]
Elementor 2.2.0 is now live!!

thanks, everyone.
