### ISSUE TITLE
Background picture is insecure element

### ISSUE THREAD

**Issue by WarnerV** [pojome/elementor#5494]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor (v2.1.8).

## Description

Using a background picture in a new Elementor page results in the https:// website reporting that 
> "parts of this page are not secure (such as images)" (Firefox)
> "Your connection to this site is not fully secure" (Chrome)

## Steps to reproduce

1. On a site with default TwentySeventeen theme and Elementor plugin, create a new Page
2. Edit with Elementor
3. Click 'Add new section' 
4. Click Style -> Background -> Background type 'normal' -> Select one of the default pictures
5. Click 'Update' in the bottom of the page
6. Browse to the published new page and observe the security warnings in Chrome and Firefox

For an example see https://www.elenatalenti.com/hometester/
 
## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: 5.7.23
	PHP Version: 5.6.37-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.elenatalenti.com
	Home URL: http://www.elenatalenti.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.7
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.1.8
		Author: Elementor.com

	Nginx Helper
		Version: 1.9.11
		Author: rtCamp

	W3 Total Cache
		Version: 0.9.7
		Author: Frederick Townes

	Wordfence Security
		Version: 7.1.10
		Author: Wordfence

== Debug ==
	Errors: There are no errors to display
				

```
</details>

**Comment by WarnerV** [comment]
--> Updating the 'home URL'  to https (and re-adding the background) resolves the issue. However, the behavior is inconsistent with the rest of Elementor.

**Comment by bainternet** [comment]
@WarnerV 

Thanks for reporting, we are aware of this behavior.

Elementor requires `site url` and `home url` to match when it comes to image backgrounds and "on the fly" generated thumnails.

I don't see that changing anytime soon.

thanks again.
