### ISSUE TITLE
Translation WooCommerce Widgets

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#5495]
Seems that not every widget is translation ready in the pro version like the "Menu Cart" and the shown cart-preview shown by this widget. 

Maybe it is hard-coded because i even can't translate it via Loco Translate.

Hope this is fixed soon since we build our first shop for a customer with elementor!

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Also, it's not clear in what language.

**Comment by Luxamman** [comment]
I can make it more clear:

Elemtentor Pro 2.1.6 and Elementor 2.2.0
WordPress 4.9.8 and PHP 7.2.3
Theme is custom Astra Pro
Language used: German

Problem: Not everything is translated in WooCommerce "Menu Cart" Elementor element.

Description: When using the "Menu Cart" element with Elementor Pro in the header, the element is working fine, but there is not German translation for the text shown to the end-user. Maybe there is no translation at all.

I tried to translate them on https://translate.wordpress.org/projects/wp-plugins/elementor but the words are not present and I could not find them. 

Especially it is about "Subtotal" - "Show Cart" - "Checkout"

Thanks

**Comment by Felipe-NS** [comment]
Agree

**Comment by pr0pre** [comment]
Hey ! Did you found something to translate it ?  
Still got :  "Subtotal" - "Show Cart" - "Checkout"
Would love translate it quickly

**Comment by JoeDarko** [comment]
#6406

**Comment by bainternet** [comment]
I merged this issue with  #5695, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by xhostAB** [comment]
+1 here too. Need to translate it to swedish

**Comment by sopingdonlot** [comment]
+1 too

**Comment by addekk** [comment]
Hi Elementor Crew. Two weeks later there is still no solution?

**Comment by MarciosilK** [comment]
Também gostaria muito de saber como traduzir.

**Comment by Felipe-NS** [comment]
Try to use this code from Tomek Stępień
`/*Change text strings */
function my_text_strings( $translated_text, $text, $domain ) {
    switch ( $translated_text ) {
        case 'Subtotal' :
            $translated_text = __( 'Your text here', 'woocommerce' );
            break;
            case 'Checkout' :
            $translated_text = __( 'Your text here', 'woocommerce' );
            break;
            case 'Show Cart' :
            $translated_text = __( 'Your text here', 'woocommerce' );
            break;
    }
    return $translated_text;
}
add_filter( 'gettext', 'my_text_strings', 20, 3 );`

**Comment by daniele8808** [comment]
I tried to translate it using loco translate as you said but nothing. I find the string but the translated text is not taken...

**Comment by UnrealPixel** [comment]
Problem still exists!

**Comment by Viktor-as** [comment]
Had the same problem. I was using TranslatePress to make my website multilingual. Tried everything here but nothing worked. So finally I found that I can change those translations in database, in wp_trp_gettext_lt_lt table (the table end depends on your language).

But to see the changes I also had to enter my website in incognito mode. Maybe this php code above works, just have to test it in incognito mode.

**Comment by ello-lithuania** [comment]
this problem is still exists

**Comment by Willcss5** [comment]
I used TranslatePress and it worked really well. So I installed it and made the default configuration. Automatically corrected. 

Ideal in these specific cases to use TranslatePress as a last resort. Where Loco Translate is unable to translate.

**Comment by rafamuz** [comment]
Year after year and a very simple thing is still an issue. what the heck Elementor is doing? they want only money, but work on little issues, nothig!

**Comment by rafamuz** [comment]
> I used TranslatePress and it worked really well. So I installed it and made the default configuration. Automatically corrected.
> 
> Ideal in these specific cases to use TranslatePress as a last resort. Where Loco Translate is unable to translate.

so do you recommend uninstall loco and replace to TranslatePress instead? or to have both plug-ins? I ask because I'm trying to have the less plug-ins as possible.
