### ISSUE TITLE
ShortCode Widget

### ISSUE THREAD

**Issue by krann** [pojome/elementor#5498]
The Elementor Shortcode widget could include, in the large amount of space available in the bottom of its left hand column,  a list of common shortcodes, such as Page Title, Author, Site Name etc. etc. It would be handy.

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Also all of these you listed are available as Dynamic tags.
