### ISSUE TITLE
Elementor pro single product page errors

### ISSUE THREAD

**Issue by hello0035** [pojome/elementor#5499]
I noticed that the woocommerce functions are now missing from elementor pro plugin.  It has been a very buggy plugin and causing a lot of problems with very little support from their team-they seem overwhelmed taking 3+ days to answer simple queries with no fixes and now woo functions have disappreared, or am i just lucky.  Has anyone else had these issues?

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
