### ISSUE TITLE
When importing a saved template widget from my library the page refreshes and resets the page template to default

### ISSUE THREAD

**Issue by Aldian1** [pojome/elementor#5503]
## Description

When importing a saved template widget from my library the page refreshes and resets the page template to default.

## Steps to reproduce

Create a template widget. Set the page template to the canvas. Import the template widget you created. Wait for page to refresh. Observe page template has now been reset to the theme one. 

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

Operating System: | Linux |  
-- | -- | --
Software: | Apache/2.4.18 (Ubuntu) |  
MySQL version: | 5.7.23 |  
PHP Version: | 7.0.30-0ubuntu0.16.04.1 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

WordPress Environment |   |  
-- | -- | --
Version: | 4.9.8 |  
Site URL: | http://63.142.250.91/northdevonchangeovers |  
Home URL: | http://63.142.250.91/northdevonchangeovers |  
WP Multisite: | No |  
Max Upload Size: | 2 MB |  
Memory limit: | 40M | We recommend setting memory to at least 64M. For more information, read about how to Increase memory allocated to PHP.
Permalink Structure: | Plain |  
Language: | en-US |  
Timezone: | 0 |  
Debug Mode: | Inactive |  

</details>

**Comment by bainternet** [comment]
@Aldian1 

We can't replicate, Your report is missing data like Plugin versions and themes used.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by Aldian1** [comment]
@bainternet 
Here is a video: https://www.youtube.com/watch?v=C6zLF5VPqK4&feature=youtu.be
#Plugins and Themes used
![capture2](https://user-images.githubusercontent.com/1427504/44532724-b7719600-a6eb-11e8-97da-e48b87d7b717.PNG)
![capture](https://user-images.githubusercontent.com/1427504/44532726-b7719600-a6eb-11e8-8047-e84cae4b6cd4.PNG)
