### ISSUE TITLE
"Current category" Option to show related posts in single page

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5505]
I want to be able to set **current category** in posts widget (elementor pro) to be able to show posts that are in SAME category of current post (in single post page)

![image](https://user-images.githubusercontent.com/2544046/44463373-2d103000-a620-11e8-8361-e14daace337f.png)

**Comment by bainternet** [comment]
@amindiary 

This is possible via [Custom Query Filter](https://developers.elementor.com/custom-query-filter/#Related_Posts_by_Tags_in_Posts_Widget) for example:

```PHP
// Showing related posts by current post category in Posts Widget
add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
	// Get current post category
	$current_post_id = get_queried_object_id();
	$current_cat = get_the_category( $current_post_id );

	if( empty( $current_cat ) ) {
		return;
	} 

	// Modify the query
	$query->set( 'category__in', [ $current_cat[0]->term_id ] );

	// Make sure we don't get current post
	$not_in = $query->get( 'post__not_in' );
	$not_in[] = $current_post_id;

	// Modify the query
	$query->set( 'post__not_in', $not_in );
} );
```

thanks.

**Comment by amindiary** [comment]
wow thank you

**Comment by MarcDethmers** [comment]
Hi Bainternet,

Tried your code for my query, however this does not work. 
What I want is similar to the code provided by Elementor for displaying related posts by TAG, to display by CATEGORY. So if the single post has a category, the related posts query at the bottom shows related post with that category. I do not know what will happen if the single post in question has more then 1 category???

Code provided by elementor for TAGS (which works!)

// Showing related posts by tag in Posts Widget
add_action( 'elementor_pro/posts/query/Related-Posts', function( $query ) {
// Here we set the query to fetch posts with
// the same tags as the current post

// Get current post tags
$tags = wp_get_post_terms( get_queried_object_id(), 'post_tag', [ 'fields' => 'ids' ] );

// Get current tax_query
$tax_query = $query->get( 'tax_query' );

// Add our tax query
$tax_query[] = [
'taxonomy' => 'post_tag',
'terms' => $tags,
];

// Modify the query
$query->set( 'tax_query', $tax_query );

// Make sure we don't get current post
$not_in = $query->get( 'post__not_in' );
$not_in[] = get_queried_object_id();

// Modify the query
$query->set( 'post__not_in', $not_in );
} );

**Comment by Fonnte** [comment]
what if the case is custom taxonomy?

**Comment by vasjanovak** [comment]
> @amindiary
> 
> This is possible via [Custom Query Filter](https://developers.elementor.com/custom-query-filter/#Related_Posts_by_Tags_in_Posts_Widget) for example:
> 
> ```
> // Showing related posts by current post category in Posts Widget
> add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
> 	// Get current post category
> 	$current_post_id = get_queried_object_id();
> 	$current_cat = get_the_category( $current_post_id );
> 
> 	if( empty( $current_cat ) ) {
> 		return;
> 	} 
> 
> 	// Modify the query
> 	$query->set( 'category__in', [ $current_cat[0]->term_id ] );
> 
> 	// Make sure we don't get current post
> 	$not_in = $query->get( 'post__not_in' );
> 	$not_in[] = $current_post_id;
> 
> 	// Modify the query
> 	$query->set( 'post__not_in', $not_in );
> } );
> ```
> 
> thanks.

Hi.
I used this query on my page and it does filter posts by current category in elementor editor but when i preview page in the browser it doesn't work. Any idea what is wrong? Thank you for your help.

**Comment by irineltraista** [comment]
```
add_action( 'elementor/query/my_custom_filter', function( $query ) {
	//get ID of current post
	$id = get_queried_object_id();
	// get current taxonomy - in this case the category
	$tax = get_the_terms( $id, 'category');

	$tax_query = array(
		array(
			'taxonomy' => 'category',
			'field' => 'slug',
			'terms' => $tax[0]->slug,
		),
	);

	$query->set( 'tax_query', $tax_query );

} );
```

**Comment by MegoSoft** [comment]
> Here is a piece of code that works.
> 
> ```
> add_action( 'elementor/query/my_custom_filter', function( $query ) {
> 	//get ID of current post
> 	$id = get_queried_object_id();
> 	// get current taxonomy - in this case the category
> 	$tax = get_the_terms( $id, 'category');
> 
> 	$tax_query = array(
> 		array(
> 			'taxonomy' => 'category',
> 			'field' => 'slug',
> 			'terms' => $tax[0]->slug,
> 		),
> 	);
> 
> 	$query->set( 'tax_query', $tax_query );
> 
> } );
> ```

Your solution works mate. Thank you!

**Comment by KumarOfficial** [comment]
> Hi all (replied on this thread and started a new)
> 
> Tried the code provided within this topic for my query, however this does not work; it shows the current post also.
> 
> What I want is similar to the code provided by Elementor for displaying related posts by TAG (below, and works for TAGS).
> 
> So, to display by CATEGORY; if the single post has a category, the related posts query at the bottom showing related post with that category. I do not know what will happen if the single post in question has more then 1 category, which also occurs for some posts???
> 
> Code provided by elementor for TAGS (which works!)
> 
> // Showing related posts by tag in Posts Widget add_action( 'elementor_pro/posts/query/Related-Posts', function( $query ) { // Here we set the query to fetch posts with // the same tags as the current post
> 
> // Get current post tags $tags = wp_get_post_terms( get_queried_object_id(), 'post_tag', [ 'fields' => 'ids' ] );
> 
> // Get current tax_query $tax_query = $query->get( 'tax_query' );
> 
> // Add our tax query $tax_query[] = [ 'taxonomy' => 'post_tag', 'terms' => $tags, ];
> 
> // Modify the query $query->set( 'tax_query', $tax_query );
> 
> // Make sure we don't get current post $not_in = $query->get( 'post__not_in' ); $not_in[] = get_queried_object_id();
> 
> // Modify the query $query->set( 'post__not_in', $not_in ); } );

Tags filter not working, I added this code in functions.php and used Query ID = Related-Posts

**Comment by Anteroriihimaki** [comment]
Are there any update as to how to fix this to work with the latest version of Elementor Pro?

**Comment by Anteroriihimaki** [comment]
Replying to myself, got it working with the following code:

`add_action('elementor/query/latest_category_products', function($query) {
    if (!is_product()) {
        return;
    }

    global $post;
    
    $terms = get_the_terms($post->ID, 'product_cat');
    
    if ($terms && !is_wp_error($terms)) {
        $category_ids = wp_list_pluck($terms, 'term_id');

        $query->set('post_type', 'product');
        $query->set('orderby', 'date');
        $query->set('order', 'DESC');
        
        $query->set('post__not_in', [$post->ID]);

        $query->set('meta_query', [
            [
                'key'     => '_stock_status',
                'value'   => 'instock',
                'compare' => '='
            ]
        ]);

        $query->set('tax_query', [
            [
                'taxonomy' => 'product_cat',
                'field'    => 'term_id',
                'terms'    => $category_ids[0],
            ]
        ]);
    }
});
`
