### ISSUE TITLE
Feature Request - WooCommerce Single Product on any page 

### ISSUE THREAD

**Issue by T-Mac31** [pojome/elementor#5507]
Sometimes I would like to place a WooCommerce product onto a page or post. It would be great to have a widget that allowed you to choose a product by name or id and place some or all of its elements on a normal page.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
