### ISSUE TITLE
Run code that can check if it is in editor mode or not - Add_Action - Hooks

### ISSUE THREAD

**Issue by Bahamutho** [pojome/elementor#5509]
I want to add some simple functionality via a plugin to elementor which only runs if it is not in editor mode. However I cannot seem to figure out where to actually hook my function to. I have tried to add the action to the wp_footer and check if it is in editor mode following  [https://github.com/pojome/elementor/issues/4491#issuecomment-390666686](https://github.com/pojome/elementor/issues/4491#issuecomment-390666686), however at that stage it does not know it is in editor mode yet. I have tried to check the body for .elementor-editor-active, this however has the same issue as that it gets added later than the wp_footer. How should I hook up my function?

Thanks!

Sample code:
``` php
add_action('wp_footer', 'ClickChild');
function ClickChild()
{    
    if ( \Elementor\Plugin::$instance->editor->is_edit_mode() ) {
        // do stuff for edit mode
        echo "<script>console.log('EDIT');</script>";
    } else {
        // not edit mode - always logs frontend
        echo "<script>console.log('FRONTEND');</script>";
    }
    
    if ( \Elementor\Plugin::$instance->editor->is_edit_mode() ) {
    ?>
    <script>
        jQuery("body").on("click", ".click-child", function() 
        { 
            var href = jQuery(this).find("a").attr('href'); 
            window.location = href; 
        });   
    </script>
    <?php
    }
}
```

**Comment by bainternet** [comment]
@Bahamutho 

What are you trying to do?

**Comment by Bahamutho** [comment]
I am trying to make to add a link to a column and make it clickeable like #351. When you add the click-child to a column this script adds a link to that column, it will make it a link instead. Combined with some cursor:pointer css, it gives the desired result. 

``` css
<style>
    .click-child { cursor:pointer }
</style>
```

The only unfortunate part is that it messes with the editor functionality and makes elementor behave loopy (as in you cannot click the element anymore without it taking you to the page). So ideally I would want to disable this behavior in edit mode. Hence the need to know when the script is in edit mode so that it does not add the on click functionality.

**Comment by bainternet** [comment]
For that you can use the `is_preview()` method:

```PHP
if ( \Elementor\Plugin::$instance->preview->is_preview_mode() ) {
     // dont print link
} else {
    // print link
}
```

Thanks.

**Comment by Bahamutho** [comment]
Amazing thanks! That totally works! 👍

**Comment by dudaster** [comment]
Unfortunatly if the theme doesn't have a wp_footer hook it won't work :( we should have hooks for elementor editing where we can add stuff.

**Comment by bentalgad** [comment]
Why is there "elementor/editor/wp_head" and no "elementor/editor/wp_footer" ?

**Comment by dcooney** [comment]
You can use `  \Elementor\Plugin::$instance->editor->is_edit_mode() ` to determine if the site is in Elementor edit mode.

**Comment by 27concepts** [comment]
@dcooney @bainternet It would be useful to know in what scenarios these functions can be used (is_edit_mode() and is_preview() ).

I recently needed to check if Elementor was in edit mode inside a (page) template file. I tried both is_edit_mode() and is_preview() and they both failed the checks (they were unable to determine that I was actually in preview or edit mode).

After spending time debugging it, I realized it was because $_GET['action'] (or $_REQUEST['action']) was not available at that time. The function is_edit_mode() relies on checking those parameter to determine whether it is edit mode or not.

When I dumped $_GET, the only available parameter were 'elementor-preview' and 'ver'. I ended up making my own function that checks whether $_GET['elementor-preview'] is set and I call it from within the template file - that seems to work.

`if ( isset( $_GET['action'] ) && in_array( $_GET['action'], $actions ) || isset($_GET['elementor-preview']) ) {

return true;

}
`

I am open to any other suggestions on how to check whether Elementor is in edit mode from within a template file.

NOTE: I need to check from within a template file because I do not want this check to happen on every page or post on the site - only on those using a specific template (at the time the template is being used).

**Comment by dcooney** [comment]
@27concepts I'm actually using this conditional in a elementor widget.php, not in a page template. Not sure about using this in a front end template.

**Comment by joychetry** [comment]
> You can use ` \Elementor\Plugin::$instance->editor->is_edit_mode()` to determine if the site is in Elementor edit mode.

This worked perfectly for me. Thanks you @dcooney

**Comment by DeoThemes** [comment]
I found that is_edit_mode and is_preview_mode not working in all cases. Instead of is_preview_mode, what worked is this code:

`if ( isset( $_GET['preview'] ) )`

**Comment by DrLightman** [comment]
@27concepts 

The actual page been previewed runs inside an iframe with a src such as this one and you need to explore the html source to spot it:

```html
<iframe id="elementor-preview-iframe" src="https://www.example.org/?elementor-preview=5671&amp;ver=1611158205" allowfullscreen="1"></iframe>
```

Therefore, in that context, you must test the not emptiness of the query variable $_GET['elementor-preview'].

In the admin dashboard context instead, the one holding the iframe, you can test the $_GET['action'] === 'elementor' instead, the one that you can see by eye in the address bar of the browser at that moment.

**Comment by musosoft** [comment]
`.elementor-editor-active` CSS selector does the job for me :)

`<script>
  jQuery(document).ready(function () {
    jQuery("body")
      .not("body.elementor-editor-active")
      .on("click", ".click-child", function () {
        var href = jQuery(this).find("a").attr("href");
        window.location = href;
      });
  });
</script>
<style>
  body:not(.elementor-editor-active) .pointer {
    cursor: pointer;
  }
</style>
`

**Comment by awesomedan93** [comment]
Maybe that can be helpful for someone
`function_exists()`

**Comment by koolmind** [comment]
Ho ancora bisogno di aiuto. Cerco di essere più chiaro.
Il mio plugin crea uno shortcode che usa dei parametri prelevati da $_POST e $_GET. Ovviamente, quando apro la pagina su elementor, questi parametri non sono impostati, perché derivano dalla navigazione dell'utente sul frontend. Come posso fare in modo che lo shortcode non venga eseguito lato admin sull'editor di elementor?
