### ISSUE TITLE
Elementor Functionality Query

### ISSUE THREAD

**Issue by reemadsouza** [pojome/elementor#551]
Hi,

I don't have an issue but a query. . .

I really like your plugin, the best editor I have come across, better than visual composer.
The only missing part is to add own functionality to the editor. For basic websites, this works so well. I mostly work on websites where I use Custom Post where I use ACF(elementor won't work in editor there :( ) now, I understand I create a template and use these in custom post but I cannot populate the archive pages since I am not able to create widgets like all custom posts and also will not be able to use in search functionality. 

Is it possible to create our own functional elements like Team and add on pages ?

Thank You.

**Comment by WPDevHQ** [comment]
You can technically use any native WordPress widgets including those geberated by themes and plugins to populate the Elementor page.

Take a look at [Elementor Addon Widgets](https://wordpress.org/plugins/elementor-addon-widgets/) (they are technically WordPress widgets) where I pull in posts and Woo products. The same concept can be employed for any other custom post type that can be queried.

What would be neat is to be able to pull in Elementor sections in to custom post types :) - hopefully some kind of shortcode mechanisim can achieve that.

**Comment by reemadsouza** [comment]
I understand the use of widgets. But I would want to use the data so query meta fields is easier and more efficient with acf especially when I need to use in custom searches and in some cases I autopopulate fields in custom post from another custom post so cannot use element as i understand its main function is to be used as an editor. I would really want this to be used with acf. Currently, it does not work.

**Comment by joshmarom** [comment]
Hi @reemadsouza.
I am sorry but I'm not sure I understand what exactly is the use case you are describing.
Would you please try to clarify?
