### ISSUE TITLE
Posts and Call to Action widgets in IE

### ISSUE THREAD

**Issue by srcek** [pojome/elementor#5510]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

There seems to be a problem with Posts widget in the Internet Explorer. 
Whatever number of columns I set, posts are displayed in a single column without spacing. 

Also, Call to Action widget doesn't vertically align content properly. Everything is pushed to the top of the box.

All other browsers are displaying content correctly.

## Steps to reproduce

Open the page with the problematic widgets in Internet Explorer.
Unfortunately "who uses Internet Explorer anymore!" attitude won't help me with this client.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

I'm using the Astra theme with the Astra Pro plugin.

**Comment by joshmarom** [comment]
An IE compatibility fix for posts widget grid will be included in the next update (both free and pro).
We will also investigate the reported CTA issue
