### ISSUE TITLE
Add Discord to Social Icon List

### ISSUE THREAD

**Issue by mattssn** [pojome/elementor#5513]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like to have a Discord Icon to use in the Social icons Widget, I saw on another post you stated people can request icons to be added, Discord is a pretty large platform, and I think this would benefit a lot of people, This Icon is not provided on Font Awesome. 
**Describe the solution you'd like**
Add the Discord icon to the social icons to be used. 

**Describe alternatives you've considered**
N/a

**Additional context**

**Comment by bainternet** [comment]
Thia will only be possible with ##4430
