### ISSUE TITLE
Can you test the drop-down menus on an iPad in portrait mode and see why these buttons menus made in Elemetor are not functioning?

### ISSUE THREAD

**Issue by tampainternet** [pojome/elementor#5519]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
At www.polkeldercare.com I have created primary menu buttons that work on every device except for iPads in landscape mode, they work in portrait mode fine, but they will not work properly in landscape mode, I have tried many solutions and tested it on multiple iPads from ones that were brand new to older ones and get the same results.

Thank you,

Mark

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
