### ISSUE TITLE
Custom Fields - Select for page templates

### ISSUE THREAD

**Issue by Webdeern** [pojome/elementor#5522]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

My suggestion relates to Custom Fields from Custom Post Types and their use in templates.

If you work with CPTs you want to create page templates to display their values.
This is not possible in the moment. 

**Describe the solution you'd like**
Dropdown-Lists in the "advanced"-part of a text-block:
a) List of CPTs
b) List of the Custom Fields of the CPT which you selected  (maybe with the descriptions of the the CFs)

Pick one of the CFs from the dropdown to enter it into your text

**Describe alternatives you've considered**
until now it is only possible manually:
keep a list of the CFs in another tab of your browser
search for the relevant one
type that into your text, preferably in HTML-mode

**Comment by collindavis** [comment]
This is already possible with ACF or Pods or Toolset plugins.

**Comment by Webdeern** [comment]
How is it possible with ACF?  Edit an elementor page template by ACF?

I need it in an elementor page template and my idea was to avoid working offline and adding the template by FTP...

**Comment by bainternet** [comment]
@Webdeern 

@collindavis is correct you can do that with Elementor Pro since V2.0
https://www.youtube.com/watch?v=ruMtMAVVF_Y
