### ISSUE TITLE
Inserting a header inside an existing text editor object

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#5524]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The structure I give to posts often evolves as I write the copy. That structure is marked by the introduction of headings into the text. However, suppose I have a text editor element with 5-6 paragraphs that I want to split into two sections, with a new header element introduced in the middle. This requires, for example, that I duplicate the text editor object, delete the second part of the text in the first copy and delete the first part of the text in the second copy and then introduce the new header between the two. This procedure is cumbersome, error prone and time consuming.

**Describe the solution you'd like**

A simpler way would be to be allowed to insert a header element at any place within existing text editor object, rather than be limited to placing new headers _between_ objects.

**Describe alternatives you've considered**

An alternative would be to have a method to split an existing text editor object into two objects. Then the header could be inserted between them.

**Additional context**

Since I do this all the time, it would be of great benefit.

**Comment by collindavis** [comment]
Why not take advantage of the WYSIWG editor by creating a Heading 1 tag inline with your text? Why must you use Elementor heading widget?

**Comment by JosiahCarberry** [comment]
I often reorganize sections of the post. Or I decide to add an image or break the section into two columns. If you just format a paragraph as a header then the underlying cumbersomeness still exists.
It is important to view a page as the result of a creative, iterative, mind-changing process, not just in terms of the final result. Be agile.

**Comment by willcitizen** [comment]
@JosiahCarberry I agree with you that software constraints shouldn't be intruding on your creative process, but we also have to consider at times that our workflow might be flawed, or we are using the wrong tool for the job.  There are many ways combining tools like ACF with Elementor to create a variety of creative post templates that you could mix and match and apply to your work.
If that isn't enough then you probably need to be working in a visual editor not a wordpress post form - why not just write your posts directly in the elementor editor, where you will be free to drag and drop and restyle elements as you see fit, or perhaps this is a case for using Gutenberg with Elementor (not something I've tried yet myself)

**Comment by bainternet** [comment]
@joshmarom 

This is currently not possible.

thanks for the suggestion.
