### ISSUE TITLE
Actionable Radio Buttons in the Contact Form

### ISSUE THREAD

**Issue by mitrandatastat** [pojome/elementor#5525]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

> A functionality of using multi-radio buttons that can link to different pages upon clicking the "Next" button at the bottom of the form. Please see below for feature depiction below:

> In a given form, let's say we have five radio buttons. We need these buttons to lead to five different web pages upon clicking the next button at the bottom of the form:

- Radio Button 1: link to PageUrl_1
- Radio Button 2: link to PageUrl_2
- Radio Button 3: link to PageUrl_3
- Radio Button 4: link to PageUrl_4
- Radio Button 5: link to PageUrl_5

> "Next" Button 

**Describe the solution you'd like**

> Upon clicking the "Next" button, we should be brought to the page 1/2/3/4/5 depending upon the selection of the above radio button. This  way we can control the navigation to the next page based on the radio button selection in the current form page.

**Describe alternatives you've considered**

> Alternatively, we can have this page navigator activated upon the selection of the radio  button with no need to click the "Next" button. More precisely, once the user select 'Radio Button 1', he would be driven to the PageUrl_1 and so on. This  way we can control the navigation to the next page based on the radio button selection in the current form page.

**Additional context**

**Comment by mitrandatastat** [comment]
Request to add a useful but unavailable feature

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, This can be done either via custom JavaScript code, or using the PHP AJAX handler to add a redirect_url based on the button selection.


Thanks for the feedback.
