### ISSUE TITLE
Facebook Comments widget - comments count

### ISSUE THREAD

**Issue by LucVanGeyte** [pojome/elementor#5528]
Facebook Comments widget - comments are not counted in the overview. See images. The comments is properly published and visible (also in facebook), but displayd as 0 reactions.

Actualy this is not possible in Elementor. It will be great if this is also possible.

![schermafbeelding 2018-08-22 om 22 53 30](https://user-images.githubusercontent.com/42676635/44590672-fc64fd80-a7bb-11e8-8e1a-ddcc651c64b3.png)
![schermafbeelding 2018-08-22 om 22 54 04kopie](https://user-images.githubusercontent.com/42676635/44590673-fc64fd80-a7bb-11e8-986a-a737d3e14c05.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by srcek** [comment]
I'd like to see that feature too. Facebook comments should be visible on posts.

**Comment by LucVanGeyte** [comment]
Yes, but till now it is not in case. Hope that this feature will be implemented!

Luc Van Geyte
Mobiel account
