### ISSUE TITLE
IE11 product visualization shown incorrect, other browsers are ok

### ISSUE THREAD

**Issue by timmeah2018** [pojome/elementor#5530]
I got the latest version of WooCommerce, Elementor, Elementor Pro, and everything updated.

However the products are shown very weird lateley in internet explorer. As you can see www.polarict.nl/gmv in Chrome is shown correctly, in IE11 not.

Is this a known issue, or can I fix it myself (with a workaround) ?

**Comment by Basilakis** [comment]
IE11 is not supported from Microsoft, we shouldnt also.

**Comment by arielk** [comment]
An IE compatibility fix for products widget grid will be included in the last update (both free and pro). Please update!
