### ISSUE TITLE
Accordion addon which extends from the default Accordion, does not toggle

### ISSUE THREAD

**Issue by ShariqKhan2012** [pojome/elementor#5533]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am trying to create an accordion element with some custom functionality. I extended the Accordion class, the UI and the controls come up fine, but the accordian element don't toggle i.e they remain in closed state. There are no JS errors in console

## Steps to reproduce
1. This is the code of my Accordion-child class. Please note than I have not included the unrelated code and the comments.
```
class Elementor_Test_Accordion_Widget extends \Elementor\Widget_Accordion {

	public function get_name() {
		return 'test_accordion';
	}

	public function get_title() {
		return __( 'Test-Accordion', 'elementor-test-accordion-extension' );
	}

	public function get_icon() {
		return 'eicon-accordion';
	}

	protected function _register_controls() {
		parent::_register_controls();
		
		$this->start_controls_section(
			'section_general',
			array(
				'label' => __( 'Test section', 'elementor-test-accordion-extension' ),
			)
		);

		$this->add_control(
			'test_field',
			array(
				'label'   => __( 'Test Field', 'elementor-test-accordion-extension' ),
				'type'    => \Elementor\Controls_Manager::TEXT,
				'default' => 'Default Value',
			)
		);
	
		$this->end_controls_section();
	}
}
```
2.  The 'Test Accordion' widget comes up fine in the Editor, and am able to use the different controls, and the values are getting saved too. However, the elements do not toggle at all.

3. If I change the following function:
```
	public function get_name() {
		return 'test_accordion';
	}
```
to return the slug  _'accordion'_ instead of _'test_accordion'_, my extension starts working perfectly, with the tradeoff being that the default accordion is bumped off from the widgets list.

4. I compared the markup of the default accordion as well as my test accordion, and it looks like there is some difference between the class names that are assigned to the elements. 
For eg. the markup of the default markup is:
```
<div data-id="850e590" class="elementor-element elementor-element-850e590 elementor-widget elementor-widget-accordion" data-element_type="accordion.default">
....
</div>
```
while that of test accordion is:
```
<div data-id="e51631b" class="elementor-element elementor-element-e51631b elementor-widget elementor-widget-test_accordion" data-element_type="test_accordion.default">
....
</div>
```
The difference being the _data-element-type_ attribute, and the classes _elementor-widget-accordion_ and _elementor-widget-test_accordion_

5. This leads me to think that possibly these differences are causing some JavaScript to not work on my test accordion.

6. Even if I remove the custom control I have added in register_controls, it does not help

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.41
	PHP Version: 7.0.19
	PHP Max Input Vars: 8000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://serenitycamps.shariqkhan.in
	Home URL: http://serenitycamps.shariqkhan.in
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 158M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Serenity
	Version: 1.0.0
	Author: Shariq Khan
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.1.8
		Author: Elementor.com

	Elementor Test Accordion Extension
		Version: 1.0.0
		Author: Shariq Khan


== Debug ==
	Errors: 
		TypeError: o.attributes[t.name].each is not a function
			at http://serenitycamps.shariqkhan.in/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.7 - 2:106066
			2018-08-22 11:35 +00:00

				
```
</details>

**Comment by bainternet** [comment]
@ShariqKhan2012 

The Elementor native accordion handler looks for `data-element_type="accordion.default"`

if you want to use that handler for anything else you would need to register it something like:

```JS
// Register the handler for custom element
elementorFrontend.hooks.addAction( 'frontend/element_ready/YOUR_CUSTOM_ELEMENT', Element_Handler );
```

and in your canse the element is `test_accordion.default` so:
```JS
// Get accordion handler
var accordionHandler = elementorFrontend.elementsHandler.getHandlers('accordion.default');
// Register the handler for custom element
elementorFrontend.hooks.addAction( 'frontend/element_ready/test_accordion.default', accordionHandler );
```

Thanks.

**Comment by ShariqKhan2012** [comment]
Thank you @bainternet  for your reply. I figured that out from the JS_Hooks documentation that I can use the code you outlined above to add my custom handlers.
But I was wondering if my test accordion are inherited from the default accordions, shouldn't their events be inherited too?
Since I am not adding any custom functionality for toggling, expanding and collapsing, and I want my accordions to be toggled the same way as the default accordions do, is there a way I can tell the code to use the same handlers as that of default accordion.

My JavaScript is not that great, especially when 'require' comes into the picture.
If you could give me some pointers that would be great.

I am trying something with:
`window.elementorFrontend.elementsHandler.getHandlers('accordion.default')`

but not sure if I am proceeding in the right direction, and how to go further.

**Comment by ShariqKhan2012** [comment]
Woops!

I somehow managed to totally miss that you have already provided the code I need to write there.
Thanks!

I tried this code :
$( window ).on( 'elementor/frontend/init', function() {
	if (elementor ) {
		// Get accordion handler
		var accordionHandler = elementor.elementsHandler.getHandlers('accordion.default');
		// Register the handler for custom element
		elementor.hooks.addAction( 'frontend/element_ready/test_accordion.default', accordionHandler );
	}
});

But it seems elementor.elementsHandler is not available at this point, though elementor.hooks is.
This seems reasonable as elementsHandle is added in the function _initOnReadyComponents_ which is run **after** _elementor/frontend/init_ has been triggered.

If I call the code inside _$(document).ready_ (instead of _elementor/frontend/init_ ), then no errors are thrown but it does seem to have any effect of actually registering the handler. Perhaps, it is a little late by then?

**Comment by ShariqKhan2012** [comment]
Okay, I confirmed that _elementor/frontend/init_ is indeed not the correct place to add my custom handler, as elementorHandler is not available at that time.
I managed to do it in _$(document).ready_.

Not sure if it is the right way, but seems good to me and is working fine too.
I am pasting my code here in case it may be helpful to someone else.

```
( function( $, elementor) {
	$(document).ready(function() {
		if (elementor ) {
			// Get accordion handler
			var accordionHandler = elementor.elementsHandler.getHandlers('accordion.default');
			// Register the handler for custom element
			elementor.hooks.addAction( 'frontend/element_ready/test_accordion.default', accordionHandler  );

			var testAccordions;
			if ( elementor.isEditMode() ) {
				// Elements outside from the Preview
				$testAccordions = jQuery( '[data-element_type="test_accordion.default"]', '.elementor:not(.elementor-edit-mode)' );
			} else {
				$testAccordions = $( '[data-element_type="test_accordion.default"]' );
			}

			$testAccordions.each( function() {
				 elementor.elementsHandler.runReadyTrigger( $( this ) );
			} );

		}
	});
}( jQuery, window.elementorFrontend  ) );
```
@bainternet Many thanks for your help. 

Do you think it would be a good idea to add this in documentation for people who are looking to extend existing widgets?

**Comment by drinkmaker** [comment]
More modern way to do same:
```js
jQuery( window ).on( 'elementor/frontend/init', () => {

    /**
     * Get accordion handler.
     * @see https://developers.elementor.com/experiment-optimized-asset-loading/
     **/
    elementorFrontend.elementsHandler.getHandler( 'accordion.default' )
    .then( ( accordionHandler ) => {

        /**
         * Attach handler for our custom accordion widget.
         * @see https://developers.elementor.com/a-new-method-for-attaching-a-js-handler-to-an-element/
         **/
        elementorFrontend.elementsHandler.attachHandler( 'rsg-accordion', accordionHandler );

        let $RSGAccordions;
        if ( elementorFrontend.isEditMode() ) {
            /** Elements outside from the Preview. */
            $RSGAccordions = jQuery( '[data-widget_type="rsg-accordion.default"]', '.elementor:not(.elementor-edit-mode)' );
        } else {
            $RSGAccordions = jQuery( '[data-widget_type="rsg-accordion.default"]' );
        }

        /** Run the handler for each rsg-accordion widget. */
        $RSGAccordions.each( function () {
            elementorFrontend.elementsHandler.runReadyTrigger( jQuery( this ) );
        } );

    } );

} );
```
Here, for my custom rsg-accordion used the handler of the standard accordion.

P.S. Sorry for the necrophilia of the issue. Your old discussion helped a lot in finding a solution to my problem. Perhaps my answer will be helpful to someone.
