### ISSUE TITLE
Slides with custom content

### ISSUE THREAD

**Issue by simonemontrucchio** [pojome/elementor#5534]
I would like to have the possibility to put whatever widget I want inside the Slide widget (in which now it is only possible to edit text and image and button)

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by lordloadalot** [comment]
https://www.livemeshthemes.com/elementor-addons/generic-carousel/

**Comment by black-eye** [comment]
Honestly, I think @simonemontrucchio 's request is quite clear even without extra prerequisites or description. 

I can definitely understand that there should be some rules to start an issue to make it easy to manage and understand. But I don't get this approach when it comes to closing absolutely obvious requests just for the sake of formal insufficiencies. I think most of the people here are trying to help to make Elementor better and these kind of reactions are not very stimulating.

I thought there was a similar request somewhere around here, but I haven't found it right now. There is one for tabs/toggles/accordion thought: #2587. IMHO, it's practicaly the same situation.

**Comment by lordloadalot** [comment]
you will get a shortcode out of any global section (combination of stacked modules) in elementor. you put the shotcode into the html bucket of the livemesh slide. that's the way. that's what elementor shortcodes are made for. 

just imagine the clutter of a backend interface if you should be able to directly drag and drop every single item into a slide frame when designing 6 or 8 slides ( skip next right  / then drag items and so on ?? )

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the new Nested Carousel in Elementor Pro v3.14.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
