### ISSUE TITLE
SKU in permalinks not working with Single Product Template

### ISSUE THREAD

**Issue by Misanek123** [pojome/elementor#5546]
Hi, 

I used the following code within my functions.php to add SKU number to product permalinks. But now because of this code the preview of the Elementor Single Product Template does not load. Anybody please have a way around this?
```PHP
/**
* Add SKU to product permalinks.
*/

function append_sku_string( $link, $post ) {
	$post_meta = get_post_meta( $post->ID, '_sku', true );
	if ( 'product' == get_post_type( $post ) ) {
		$link = $link . '#' .$post_meta;
		return $link;
	}
}
add_filter( 'post_type_link', 'append_sku_string', 1, 2 );
```

**Comment by bainternet** [comment]
@Misanek123 

Not sure whats not working for you but the code you posted is incorrect, you should always return a value from a function hooked to a filter, and not only if its post of type product, ex:

```PHP
/**
 * Add SKU to product permalinks.
 *
 * @param $link
 * @param $post
 *
 * @return string
 */
add_filter( 'post_type_link', function ( $link, $post ) {
	if ( 'product' == get_post_type( $post ) ) {
		$post_meta = get_post_meta( $post->ID, '_sku', true );
		$link .= '#' . $post_meta;
	}

	return $link;
}, 1, 2 );
```

**Comment by Misanek123** [comment]
Thank you!!! Fixed! Big thanks once again!

**Comment by starpainttech** [comment]
Thanks this function adds the Sku number twice to the permalink, how to fix ?
