### ISSUE TITLE
Feature request: Please add border radius to Nav Menu.

### ISSUE THREAD

**Issue by NanaDada** [pojome/elementor#5548]
It would be nice if the **Nav Menu** would provide a border radius setting in case **Pointer** is set to **Framed** or **Background**. This would enable us to create a menu similar like this one:

![navmenu](https://user-images.githubusercontent.com/2156073/44650045-e3d82b80-a9e5-11e8-986e-1e6fae38f54d.png)

Thank you.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

I merged this issue with  #4787, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
