### ISSUE TITLE
Problem with Nav Menu widget - Elementor Pro

### ISSUE THREAD

**Issue by olipalan** [pojome/elementor#5550]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I need website users browsing through mobile phones and tablets to navigate the page using the main menu located in the footer of the website.

But the elementor pro nav menu widget has a problem. The menu should be shown up to display the menu items, however it does not. It shows down. It is a usability error that has not been taken into account and is important for the user experience on mobile devices and in my case it is very important. I need that functionality for my projects. Please, if you are so ambles, you can provide me with a provisional solution, I am not a developer, but I do not think it is very complicated.

Thanks.

Regards

**Describe the solution you'd like**
That the menu options can be displayed upwards. (it shows correctly).

My goal is to obtain a similar result:

http://bonfirethemes.com/touchy-by-bonfire/index-two.html

and currently with elementor pro should be able to be done without problems. :(

**Describe alternatives you've considered**

**Additional context**

![screenshot_2018-08-26-elementor-pie-movil](https://user-images.githubusercontent.com/6698917/44650377-b6d84880-a9e6-11e8-8776-3e2cc88af6a9.jpg)

**Comment by bainternet** [comment]
I merged this issue with  #4787 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
