### ISSUE TITLE
Elementor Contact Form -custom JS Add/Remove field - not sending emails.

### ISSUE THREAD

**Issue by DenisBotic** [pojome/elementor#5551]
In elementor form I have used HTML field to add custom input field/s which I would clone by clicking add one more field buttn. Cloned filed/s values for ID-s, names, and attribute FOR in labels would be replaced with new indexed values. 

Problem is that if I send that form, I get the message that form is sent but it actually isn't.
Thing is that you are probably doing some kind of verification in php according to field ID which is randomly created probably by nonce to secure the form.

Here is code example:
```
<div class="elementor-field-type-checkbox elementor-field-group elementor-column elementor-field-group-1010 elementor-col-100">
    <label for="form-field-1010" class="elementor-field-label">moj label</label><div class="elementor-field-subgroup  ">
    <span class="elementor-field-option">
        <input type="checkbox" value="opcija 1" id="form-field-1010-0" name="form_fields[1010][]" aria-invalid="false"> 
    <label for="form-field-1010-0">opcija 1</label>
    </span>
    <span class="elementor-field-option">
        <input type="checkbox" value="opcija 2" id="form-field-1010-1" name="form_fields[1010][]" aria-invalid="false"> 
    <label for="form-field-1010-1">opcija 2</label>
    </span>
    <span class="elementor-field-option">
        <input type="checkbox" value="opcija 3" id="form-field-1010-2" name="form_fields[1010][]" aria-invalid="false"> 
    <label for="form-field-1010-2">opcija 3</label>
    </span>
</div>	
```

You can see an example of what I am trying to achieve on this link:
http://elem.developmentofcustom.website/contact-content-writing/

There you will see + button and additional field will appear when you click that button.
You can inspect elements to see how new id, name, for values are applied dynamically.

I am wondering, is there an option for me to finish this with elementor form or I should build my own form from scratch to achieve this?

**Comment by bainternet** [comment]
@DenisBotic 

You can only do that with some major custom coding on `elementor_pro/forms/validation` and `elementor_pro/forms/process` action hooks.

thanks

**Comment by DenisBotic** [comment]
Thank you for your answer. I think that I will build my own plugin for that.
