### ISSUE TITLE
[Feature Request] Woocommerce product carousel.

### ISSUE THREAD

**Issue by id820** [pojome/elementor#5552]
I found it on third parties websites and they are charging a lot for it, would be nice to have that built-in with Elementor PRO.

**Comment by arielk** [comment]
I merged this issue with another issue #4490 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Carousel widget released with Elementor Pro v3.11.0! 🥳 

With the new Loop Carousel widget, you can customize your post listings with custom templates (including WooCommerce Products)! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Carousel layout, design, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-carousel/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
