### ISSUE TITLE
Sample code for Forms, editor parts

### ISSUE THREAD

**Issue by odoremieux** [pojome/elementor#5558]
I'm trying to integrate a new CRM into the Form in the Pro version.
I have made good progress, but I have some issue to add dynamically the tags into the editor part.
Any code sample?

**Comment by bainternet** [comment]
@odoremieux 

What are the tags you want to add dynamically and where in the editor part?

also please share your code it would help understand better.

**Comment by bainternet** [comment]
@odoremieux 

Thanks for clarifying,

To update panel controls at run-time (dynamically) you will need to create an ajax handler that will fetch and populate the control values.

Or create a [custom control](https://developers.elementor.com/creating-a-new-control/) that will know to fetch the values on its own.

thanks.
