### ISSUE TITLE
Integration with ProfileGrid

### ISSUE THREAD

**Issue by davidmabelle** [pojome/elementor#5559]
- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would love to be able to use Elementor to style ProfileGrid
https://profilegrid.co/

**Describe the solution you'd like**
I would like Elementor to recognize and integrate with ProfileGrid 

**Describe alternatives you've considered**
Please take a look at two of your competitors who appear to be copying and improving on Elementor
Both are about to launch Pro (paid) versions
https://brizy.io/ 
https://www.themeum.com/introducing-wp-page-builder/

**Additional context**
<img width="1235" alt="profile grid" src="https://user-images.githubusercontent.com/997504/44676702-47b42180-a9f1-11e8-8f0e-82cf62b29677.png">

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
