### ISSUE TITLE
Section > Style > Typography > Heading color

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#556]
Hi guys, I tried to change the value of `Section > Style > Typography > Heading color`, but looks like it targets the `.elementor-heading-title` not normal headings like `h1`, `h2`, `h3`, etc. The generated CSS is:

```
#elementor-element-a95zkoq > .elementor-container .elementor-heading-title{color:#00ad82;}
```

And then I tried to add `Heading widget` to the section and change the heading color from `Heading Widget > Style > Title > Text color`. It doesn't work! The generated CSS is:

```
#elementor-element-w0i8ihv .elementor-heading-title{color:#7c7c7c;}
```

Don't you think it's weird, because heading color should be specified from the `Heading widget` own setting, not the section's style. And the section's generated CSS also has higher priority, so the `Heading widget` settings doesn't work in this case.

The `heading color` on the section's settings should target normal headings like `h1`, `h2`, `h3`, etc.

What do you think?

**Comment by arielk** [comment]
For now, this feature works only if global colors are disabled, we've added a note for this: http://i.imgur.com/WHgL0aJ.png

Thanks for your feedback!

**Comment by kokers** [comment]
@daviedR I know this is old, but in case someone will get here from google and needed option to set heading colors for whole section/column (targeting h1...h6), here is a simple code that can be used just for that https://gist.github.com/kokers/3f00c72752e52cc5d6249ebe715b3008
