### ISSUE TITLE
Feature Request: Forms Widget - Auto fill name and email in Forms for registered members

### ISSUE THREAD

**Issue by Jwalking26** [pojome/elementor#5560]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have looked through elementor documents and github and haven't found what I'm looking for. Is there any shortcode that can auto fill form fields with the name and email for a registered member? 

**Describe the solution you'd like**
If a registered member of the Web site creates a form, the name and email be auto filled so they don't have to type it in, it's already there once they the form pops up.

**Describe alternatives you've considered**
A shortcode of some sort to retrieve customer name and their email. 

**Additional context**
This would be convenient for a returns form for WooCommerce, if a customer wants to return an order, have their info already filled, and maybe if it's possible, have a drop down of the customer's latest purchases.

I apologize if there is a duplicate but I've dug through the elementor documents and this github forum and didn't see anything.

**Comment by bainternet** [comment]
I merged this issue with  #4268, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
