### ISSUE TITLE
Displaying posts of (then) currently logged in user

### ISSUE THREAD

**Issue by Henry8493** [pojome/elementor#5561]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

My feature request is actually the same as this one: 
https://github.com/pojome/elementor/issues/4352
I feel that the above FR was a little misunderstood. My problem is that I´d like to display posts on a page dynamically depending upon the logged in visitor (not the user creating the query). 

**Describe the solution you'd like**

A "logged in user" tag for the author query would be perfect.

**Comment by bainternet** [comment]
@Henry8493 

This can be easily done with [Custom Query Filter](https://developers.elementor.com/custom-query-filter/) eg:

```PHP
add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
	if ( is_user_logged_in() ){
		$query->set( 'author', get_current_user_id() );
	}
} );
```

thanks

**Comment by adcadesigns** [comment]
> @Henry8493
> 
> This can be easily done with [Custom Query Filter](https://developers.elementor.com/custom-query-filter/) eg:
> 
> ```
> add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
> 	if ( is_user_logged_in() ){
> 		$query->set( 'author', get_current_user_id() );
> 	}
> } );
> ```
> 
> thanks

Hello @bainternet , is this still working for the latest elementor version? i cant seems to make it work. Am i missing something please? thank you.

**Comment by jeffcdavis** [comment]
For anyone coming across this. The below code works as of 1/2023

add_action( 'elementor/query/my_custom_query', function( $query ) {
	if ( is_user_logged_in() ){
		$query->set( 'author', get_current_user_id() );
	}
} );

Change "my_custom_query" as needed and make sure you add that to the query ID on the posts widget in Elementor.
