### ISSUE TITLE
Add the option the set the page scroll up offset before displaying the sticky menu.

### ISSUE THREAD

**Issue by vgstef** [pojome/elementor#5563]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

When scrolling down, I'd like to have a sticky menu that is different than the menu on the page. My standard menu has a big logo in the center and different links/icons in it, but for the sticky menu, I'd like a small one with only a few links.

**Describe the solution you'd like**

One solution could be to set an alternate header/menu for the sticky menu or the header.

**Describe alternatives you've considered**

A workaround I found is to add a script that displays the sticky section only if the page is scrolled up a certain number of px. 

To achieve this, I've set an ID (ie #menu-collant) to my sticky section.

I loaded a custom script in my theme:
`jQuery(window).scroll(function(){
		if (jQuery(window).scrollTop() >= 150) {
			jQuery('#menu-collant').removeClass('hidden-menu');
		}
		else {
			jQuery('#menu-collant').addClass('hidden-menu');
		}
	});`

and a CSS class : 
`.hidden-menu {
	display: none;
}`

That works, but I'm stuck with the value set in the script and with a specific ID.

I think it could be easy to simply add a field under the "Offset section" where we could set how much pixel the page should be scrolled up before the sticky section appears.

**Comment by bainternet** [comment]
@vgstef 

This is already possible, we are working on the docs for that.

thanks
