### ISSUE TITLE
Toolset view incompatibility

### ISSUE THREAD

**Issue by benhartwich** [pojome/elementor#5565]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I´ve identified an incompatibility with toolset views. I´ve informed toolset, but perhaps the problem is on your site. 

When I create a toolset view for a custom post type and every post content of this custom post type is created with elementor the view displayed the whole content although only title or image is selected to be displayed at the view. 

Everytime I create content at this post type with the default editor only all works great. Can you please check, if this error is on your site? 

## Steps to reproduce

Install Toolset and Elementor + Elementor Pro
Create a page with elementor
Create a view to list only the link and title of this page 
Insert this view and you will see the whole content instead of url and title

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.3
	MySQL version: 5.7.21
	PHP Version: 7.2.4
	PHP Max Input Vars: 10000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://xy.net
	Home URL: https://xy.net
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Test 123
	Version: 1.0
	Author: Tester
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.5.25
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	AnyWhere Elementor Pro
		Version: 2.10.1
		Author: WebTechStreet

	Disable Comments
		Version: 1.7.1
		Author: Samir Shah

	Elementor
		Version: 2.1.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.5
		Author: Elementor.com

	InfiniteWP - Client
		Version: 1.8.5
		Author: Revmakx

	Ocean Cookie Notice
		Version: 1.0.4
		Author: OceanWP

	Ocean Elementor Widgets
		Version: 1.1.0
		Author: OceanWP

	Ocean Extra
		Version: 1.4.22
		Author: OceanWP

	Ocean Hooks
		Version: 1.1.1
		Author: OceanWP

	Ocean Sticky Header
		Version: 1.1.11
		Author: OceanWP

	Toolset Types
		Version: 3.0.7
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.6.3
		Author: OnTheGoSystems

	WPML CMS Nav
		Version: 1.4.23
		Author: OnTheGoSystems

	WPML Media
		Version: 2.3.6
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.0.6
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.4.4
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.8.6
		Author: OnTheGoSystems


== Debug ==
	Errors: 
		TypeError: this.search is undefined
			at https://xy.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.8 - 2:157916
			2018-08-24 20:28 +00:00

		TypeError: Cannot read property 'attributes' of undefined
			at https://xy.net/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.1.8 - 2:7460
			2018-08-21 09:21 +00:00

				
```
</details>

**Comment by bainternet** [comment]
@benhartwich 

Elementor has no control over what is displayed via a Toolset view, so this should be directed to them.

We will also inform them.

thanks.
