### ISSUE TITLE
Elementor for non-content element

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#557]
Hi guys, I tried something which is a bit complex.

I created a new custom post type named "Footer". The idea is to create dynamic footer which you can build using Elementor (so it is **Footer Builder**!). This will allow user to select different footer on specific pages (I have a custom metabox on page editor to choose the Footer post type).

On my theme file, I can render the Footer post type, using the custom `$wp_query` and `the_content` functions. All is well except the stylesheets, which are not included.

Do you think you have a solution for this?

**Comment by WPDevHQ** [comment]
Are you doing this via a child theme or a plugin?

Can you share them so that we can test and see what would be the best solution?

**Comment by daviedR** [comment]
Okay, first you need to register a custom post type "footer". Create a new footer post using Elementor, you can create columns and add widgets, let's name the post ID as `YOUR_FOOTER_POST_ID`.

And then in your `footer.php`, you can use this query:

```
global $wp_query; $temp = $wp_query;
$wp_query = new WP_Query( array( 'post_type' => 'footer', 'p' => YOUR_FOOTER_POST_ID ) );

if ( have_posts() ) :
    while ( have_posts() ) {
        the_post();
        the_content();
    }
endif;

$wp_query = $temp; wp_reset_postdata();
```

This will sucesfully print your footer post. However the CSS from the Elementor is not included, is there any functions we can use to manually include the CSS?

**Comment by daviedR** [comment]
The post type configuration I use:

```
register_post_type( 'footer', array(
		'public'              => true,
		'hierarchical'        => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_nav_menus'   => false,
		'show_in_admin_bar'   => false,
		'menu_icon'           => 'dashicons-screenoptions',
		'has_archive'         => false,
		'query_var'           => true,
		'rewrite'             => false,
		'menu_position'       => null,
) );
```

You may need to add a new single post template file, `single-footer.php` which pretty much looks like this:

```
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
	<head>
		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="profile" href="http://gmpg.org/xfn/11">
		<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">

		<?php wp_head(); ?>
	</head>

	<body <?php body_class(); ?>>
		<div id="page" class="site">
			<?php
			while ( have_posts() ) : the_post();
				the_content();
			endwhile;
			?>
		</div><!-- #page -->

		<?php wp_footer(); ?>
	</body>
</html>
```

This will make your footer post type page blank and only the builder itself (no header).

**Comment by daviedR** [comment]
I found a solution, but not sure if it's a proper method to use. I added:

```
Elementor\Plugin::instance()->frontend->print_css();
```

just right after the `the_content()` call in the `footer.php`. Is it okay?

**Comment by WPDevHQ** [comment]
Is the css coming from Elementor or is it custom css that you wish to enqueue in support of the section?

If its custom the you can use `wp_add_inline_style()` and do something like this: https://github.com/WPDevHQ/ElemenTemplater/blob/master/inc/themes/genesis.php

If its from Elementor then I'll leave that to the team to advise on the best aproach.

**Comment by daviedR** [comment]
It is Elementor's generated CSS. Currently, in your `Frontend` class, you use `wp_head` hook to `print_css()`.

In my case, I used Elementor for footer builder with the custom `$wp_query` as shown above. `wp_head` hook is already passed, that's why my footer generated CSS from Elementor doesn't printed anywhere on the page. So I just did manually call the `print_css()` function on my footer.

**Comment by arielk** [comment]
Merge #496
