### ISSUE TITLE
Buttons bar

### ISSUE THREAD

**Issue by hamadesign** [pojome/elementor#5571]
Hi there,

I have a suggestion about making buttons' bar in Elementor? 
like this buttons' bar: 
https://image.ibb.co/gb8nxp/Untitled.png 
Source website: 
https://www.mannheim-business-school.com/de/mba-master/mannheim-part-time-mba/

Best,

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
