### ISSUE TITLE
Portfolio - Widget: Filterbar for detail-page

### ISSUE THREAD

**Issue by Webdeern** [pojome/elementor#5572]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The portfolio-filterbar is a handy navigation tool. 
When the user opened one of the portfolio-item-detailedpages, there is no chance to keep this navigation at hand, because the filterbar is not a standalone-widget which can be added to single-page-templates as well

**Describe the solution you'd like**
I would love to have the same filterbar-integration in detail-pages as in the portfolio itself. 
This could be easily integrated into the templates

**Describe alternatives you've considered**
I created a menue for just the categories of that special CustomPostType, but this needs one more template to create

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
