### ISSUE TITLE
WooCoomerce: Product widget sale badge

### ISSUE THREAD

**Issue by benhartwich** [pojome/elementor#5573]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When I enter a sale´s price the most page builder offer an automatically / dynamically generated sale´s badge. The products widgets of elementor has no such setting.

**Describe the solution you'd like**
An extra option at this widget would be helpfull: display badges.

**Describe alternatives you've considered**
There are no alternatives.

**Comment by arielk** [comment]
It already exists, see the screenshot:
![screen shot 2018-08-28 at 15 10 01](https://user-images.githubusercontent.com/1778512/44722048-82db5100-aad4-11e8-8e43-fbfe4e5ca828.png)
