### ISSUE TITLE
elementor pro phpmyadmin data

### ISSUE THREAD

**Issue by onurkiyak23** [pojome/elementor#5575]
![40244688_250792625576409_4057627463352582144_n](https://user-images.githubusercontent.com/42773922/44725292-9dfe8e80-aadd-11e8-924f-c3233120b036.png)

How can I find the data in the elementor pro database.

**Comment by bainternet** [comment]
Elementor saves the data in the post meta table.

**Comment by onurkiyak23** [comment]
all data ?
