### ISSUE TITLE
Adding Mix blend mode for images

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5578]
Adding Mix Blend mode just like CSS filter for single images. not just background images.

**mix-blend-mode: normal|multiply|screen|overlay|darken|lighten|color-dodge|color-burn|difference|exclusion|hue|saturation|color|luminosity;**

```
.normal {mix-blend-mode: normal;}
.multiply {mix-blend-mode: multiply;}
.screen {mix-blend-mode: screen;}
.overlay {mix-blend-mode: overlay;}
.darken {mix-blend-mode: darken;}
.lighten {mix-blend-mode: lighten;}
.color-dodge {mix-blend-mode: color-dodge;}
.color-burn {mix-blend-mode: color-burn;}
.difference {mix-blend-mode: difference;}
.exclusion {mix-blend-mode: exclusion;}
.hue {mix-blend-mode: hue;}
.saturation {mix-blend-mode: saturation;}
.color {mix-blend-mode: color;}
.luminosity {mix-blend-mode: luminosity;}
```

![image](https://user-images.githubusercontent.com/2544046/44730070-ca6bd800-aae8-11e8-924f-b918fda1a6a6.png)

**Comment by bainternet** [comment]
@amindiary 

We are thinking about it, but it not a top priority right now.

thanks.
