### ISSUE TITLE
[Enhancement] Entrance Animation

### ISSUE THREAD

**Issue by lunacroft** [pojome/elementor#558]
Elementor already has entrance animation effects and we can control duration. To become complete, you could implement delay time too, and maybe change duration (slow, normal, fast) to numeric controls.

With these enhancements we could create blocks with images/icons/texts with different entrance time, similar to slideshows.

**Comment by icarolmelo** [comment]
It would be perfect for me if it exists..

**Comment by vanlong441** [comment]
it has been a while. Is there any update on this feature?

**Comment by ehausen** [comment]
So two things:
* Delay for entrance animations
* Make time settings numeric (seconds, allowing decimals)

Should we split up issue?

**Comment by arielk** [comment]
In Addition:
- Entrance Animation: Top to Bottom / Bottom to Top / Both

**Comment by nicolasblume** [comment]
What's the differnce between speed and duration?
If I choose a longer animation the speed is slower and vice versa.

By the way: maybe the german translation is not correct - the name of the setting means "duration of animation" but the different settings translate to "slow, normal, fast".
That would fit for a speed but not a duration

**Comment by nicolasblume** [comment]
For my problem (#1523) the easiest solution would be to to turn off animations on mobile devices.
A fade in effect makes less sense on a phone, where you have to scroll more, which already looks a bit like a fade in effect.

So it would be awesome to have a full responsive control over anymations. Then you can set a different animation (or no animation) for every screensize

**Comment by soyket** [comment]
yes! this would be perfect ! any update on this yet !?

**Comment by arielk** [comment]
Designed for the upcoming version 1.5
Please register for our beta program on the following page: https://my.elementor.com/beta/

**Comment by arielk** [comment]
Elementor 1.5 RC2 has already been released, please check this issue #1827
