### ISSUE TITLE
Html in Nothing Found Message for Archives

### ISSUE THREAD

**Issue by wmassjct** [pojome/elementor#5580]
It would be great to be able to use html in the "Nothing Found Message" in the archive widget.  Rather than leaving a visitor at a dead end it could be used to redirect to a similar archive or elsewhere.  I specifically use the archives for custom taxonomies which sometimes return a blank query.  Formatting that message would be great too but really I just want to throw in a link or maybe even a shortcode to redirect the visitor.

Thanks

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
