### ISSUE TITLE
Posts are not responsive anymore

### ISSUE THREAD

**Issue by HuthDev** [pojome/elementor#5583]
Steps to reproduce:

Download newest version of elementor and elementor pro.

1) Create page
2) Add full width section
3) Add "Posts" element
4) Choose three column layout
5) Choose 3 posts per page

Notice the posts are set to 33% instead of 100% therefore causing them all to be extremely narrow.

**Comment by HuthDev** [comment]
This change fixed our issue: 

` article.elementor-post.elementor-grid-item {
   width: 100%;
}`

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
