### ISSUE TITLE
Can't "Edit With Elementor" Anymore

### ISSUE THREAD

**Issue by tannedtoni** [pojome/elementor#5585]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Going to a page and clicking the "Edit With Elementor" button results in a blank white page. Nothing happens. This is after latest update. Using Safari & Chrome browsers and get the same white page each time.

## Steps to reproduce
Just attempt to edit a page with Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
I have attempted to roll back the versions but I'm still having the same problems.  Here's the system info currently:

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.40
	PHP Version: 7.1.21
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://tea-biotics.com
	Home URL: http://tea-biotics.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Page Builder Framework
	Version: 1.8.2
	Author: David Vongries
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

== Active Plugins ==
	Contact Form 7
		Version: 5.0.3
		Author: Takayuki Miyoshi

	Elementor
		Version: 2.2.0
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.6
		Author: Elementor.com

	Flamingo
		Version: 1.9
		Author: Takayuki Miyoshi

	Page Builder Framework Premium Addon
		Version: 1.8.1
		Author: MapSteps

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

	SmartCrawl
		Version: 2.2.2.1
		Author: WPMU DEV

	WP Google Maps
		Version: 7.10.28
		Author: WP Google Maps

	WP Google Maps - Pro Add-on
		Version: 7.10.25
		Author: WP Google Maps

	WPMU DEV Dashboard
		Version: 4.5.2
		Author: WPMU DEV

	WP Store Locator
		Version: 2.2.16
		Author: Tijmen Smit

	WP Store Locator - CSV Manager
		Version: 1.2.0
		Author: Tijmen Smit

	WP Store Locator - Widget
		Version: 1.1.1
		Author: Tijmen Smit

== Debug ==
	Errors: 
		TypeError: this.ui.apply.add is not a function. (In 'this.ui.apply.add(this.ui.discard)', 'this.ui.apply.add' is undefined)
			at https://tea-biotics.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:233308
			2018-07-03 17:22 +00:00
			x 3 times

		TypeError: undefined is not an object (evaluating 'n.ui.form.html')
			at http://tea-biotics.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.14&nocache=1 - 2:79513
			2018-05-31 15:52 +00:00

		TypeError: null is not an object (evaluating 'this.dataAdapter.query')
			at http://tea-biotics.com/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1&nocache=1 - 1:60823
			2018-05-30 23:51 +00:00
			x 3 times

		TypeError: undefined is not an object (evaluating 'this._parent.errors')
			at http://tea-biotics.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.7&nocache=1 - 2:132925
			2018-04-22 17:10 +00:00
			x 6 times

		TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
			at http://tea-biotics.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=1.15.6&nocache=1 - 2:30322
			2018-04-15 18:11 +00:00
			x 2 times

				

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by obe1968** [comment]
tannedtoni;

Good morning!!! :o)

I do not see in your comments where you have tried to disable all of your plugins but Elementor and Elementor Pro and see if the issue goes away as well as switching your theme temporarily, both of which Elementor always suggests doing in their troubleshooting documentation located at docs.elementor.com

If you disable all of your plugins with the exception of the Elementor ones mentioned above, and it works, re-enable your plugins one at a time, re-checking for the issue after each re-enable, and if it breaks again, you found the plugin causing the conflict. If that does not work, try switching your theme.

Sincerely,

Shawn

**Comment by bainternet** [comment]
@tannedtoni 

We can't replicate this, 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by tannedtoni** [comment]
@obe1968 - I did turn off plugins - it didn't change.  It's now happening on another site and I'm getting the issue in both Chrome and Safari.

**Comment by tannedtoni** [comment]
@bainternet - will do, thanks!

**Comment by tannedtoni** [comment]
Here’s the link to the thread: https://github.com/pojome/elementor/issues/5585 <https://github.com/pojome/elementor/issues/5585>

This has happened on tea-biotics.com <http://tea-biotics.com/> and diamondgirlsbartenders.com <http://diamondgirlsbartenders.com/>. I haven’t checked any other sites yet, but these two for sure.  These sites have been up and running for some time now - and this just started but I’m not sure why.  Any assistance would be appreciated because I can’t edit or add any pages to these sites.

Thanks, 

Toni Taylor
Web Designer/Developer
Office: 913.221.0737
Email: toni@toniswebdesign.com <mailto:toni@toniswebdesign.com>
Web: toniswebdesign.com <https://toniswebdesign.com/>
Social: Facebook <https://www.facebook.com/toniswebdesign/> | Twitter <https://twitter.com/toniswebdesign> | Google+ <applewebdata://005F65FB-2880-4541-B726-9C04309B046B/plus.google.com/109059406926074695845> | Pinterest <applewebdata://005F65FB-2880-4541-B726-9C04309B046B/www.pinterest.com/toniswebdesign>
DOUBLE Your Website Leads in as Little as 7 Days
With My FREE 47-Point Checklist!
DOWNLOAD NOW <https://toniswebdesign.com/47-point-homepage-checklist/>
Confidentiality Statement and Notice: This email is covered by the Electronic Communications Privacy Act, 18 U.S.C. 2510-2521 and intended only for the use of the individual or entity to whom it is addressed. Any review, retransmission, dissemination to unauthorized persons or other use of the original message and any attachments is strictly prohibited. If you received this electronic transmission in error, please reply to the above-referenced sender about the error and permanently delete this message. Thank you for your cooperation.

**Comment by tannedtoni** [comment]
-- Please reply above this line --
-----------------------------------------------------------
## Elementor replied, on Aug 31 @ 5:26 (UTC):

Hi Toni,

Thanks for reaching out to us! Sorry for the inconvenience you've had
in using Elementor.

Firstly, please make sure you are using the latest version of
Elementor and Elementor Pro! 

If the issue with the blank white page still persists, please take a
look at this article below, and follow the methods listed under the
"My page is blank" section:
Can't Edit with Elementor [1]

If the methods don't help, could you send us an admin login and
password so we can have a closer look?

Let me know how it goes.

Best regards,
Ferry


Links:
------
[1] https://docs.elementor.com/article/184-cant-edit-with-elementor

--
Elementor Technical Support
Facebook [1] | Twitter [2] | YouTube [3]
 Join the conversation & learn from our Elementor Community [4].

 How would you rate my reply? 



Links:
------
[1] https://www.facebook.com/elemntor/
[2] https://twitter.com/elemntor
[3] https://www.youtube.com/c/elementor
[4] https://www.facebook.com/groups/Elementors/


-----------------------------------------------------------
## Toni Taylor sent a message, on Aug 30 @ 16:59 (UTC):

Here's the link to the thread:
https://github.com/pojome/elementor/issues/5585 [1] 
 This has happened on tea-biotics.com [2] and
diamondgirlsbartenders.com [3]. I haven't checked any other sites yet,
but these two for sure. These sites have been up and running for some
time now - and this just started but I'm not sure why. Any assistance
would be appreciated because I can't edit or add any pages to these
sites. 
 Thanks,    
TONI TAYLOR
WEB DESIGNER/DEVELOPER
OFFICE: 913.221.0737
EMAIL: toni@toniswebdesign.com [4]
WEB: toniswebdesign.com [5]
SOCIAL: Facebook [6] | Twitter [7] | Google+ [8] | Pinterest [9]
 DOUBLE Your Website Leads in as Little as 7 Days
 With My FREE 47-Point Checklist!
DOWNLOAD NOW [10]  

	Confidentiality Statement and Notice: This email is covered by the
Electronic Communications Privacy Act, 18 U.S.C. 2510-2521 and
intended only for the use of the individual or entity to whom it is
addressed. Any review, retransmission, dissemination to unauthorized
persons or other use of the original message and any attachments is
strictly prohibited. If you received this electronic transmission in
error, please reply to the above-referenced sender about the error and
permanently delete this message. Thank you for your cooperation. 

 On Aug 29, 2018, at 2:48 PM, Raz Ohad <notifications@github.com
[11]> wrote: 
support @elementor.com   


Links:
------
[1] https://github.com/pojome/elementor/issues/5585
[2] http://tea-biotics.com
[3] http://diamondgirlsbartenders.com
[4] mailto:toni@toniswebdesign.com
[5] https://toniswebdesign.com
[6] https://www.facebook.com/toniswebdesign/
[7] https://twitter.com/toniswebdesign
[8] /plus.google.com/109059406926074695845
[9] /www.pinterest.com/toniswebdesign
[10] https://toniswebdesign.com/47-point-homepage-checklist/
[11] mailto:notifications@github.com

**Comment by genctasbasi** [comment]
For me the problem was "Essential Addons for Elementor" plugin. Deactivated and white page problem resolved.

**Comment by napokleon** [comment]
I work Divi and individual themes for years. I never liked elementor but i neve tested either :) Those days i strugle with it... imo:crap! the worst ever. Full of problems and the their forum / support answers are totally useless.. a big huge zero.

**Comment by Romi229** [comment]
Hello everyone
You can fix it by disabling one by one all plugin installed
In my case, it was due to one plugin installed: Premium addons for elementor
Hope it will help you
