### ISSUE TITLE
Products Not Showing Properly on Mobile after update to 2.2.0 (using Astra Theme)

### ISSUE THREAD

**Issue by getflipstik** [pojome/elementor#5586]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
We use astra theme so that we can have the hover image functionality with our Items. However, with the latest update to Elementor and Elementor Pro, It has broken the layout for products on mobile. We have isolated this is as the issue as we updated all other plugins one by one and activated one by one. The issue only occurs when we update either Elementor or Elementor Pro to the latest version (see screenshots:

### Current Versions of Elementor/Pro 

![2018-08-28 at 2 50 pm](https://user-images.githubusercontent.com/42784699/44747218-40187980-aad2-11e8-8f32-308e9916b623.jpg)

### Before we update it looks like this:

![image](https://user-images.githubusercontent.com/42784699/44747279-663e1980-aad2-11e8-8384-975ce1243ad6.png)

### After we update it looks like this:

![image](https://user-images.githubusercontent.com/42784699/44747529-06943e00-aad3-11e8-92c5-1f9096975e2a.png)

We have set up the woocommerce produc widget to view 6 items per line so that it looks proper on desktop. However it generally used to auto layout to 2 items on mobile.

## Steps to reproduce

Using the Woocommerce Products Widget > Display 6 Items per line > View on Mobile

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [n/a] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.40
	PHP Version: 7.1.21
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.getflipstik.com
	Home URL: http://www.getflipstik.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: -6
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.4.5
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	AddToAny Share Buttons
		Version: 1.7.28
		Author: AddToAny

	Akismet Anti-Spam
		Version: 4.0.8
		Author: Automattic

	AMP
		Version: 0.7.2
		Author: WordPress.com VIP, XWP, Google, and contributors

	Astra Starter Sites
		Version: 1.2.7
		Author: Brainstorm Force

	Booster for WooCommerce
		Version: 3.8.0
		Author: Algoritmika Ltd

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Easypost WooCommerce Extension (BASIC)
		Version: 1.2.1
		Author: XAdapter

	Elementor
		Version: 2.1.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.0-RC4
		Author: Elementor.com

	Enhanced E-commerce for Woocommerce store
		Version: 2.1.1
		Author: Tatvic

	Facebook for WooCommerce
		Version: 1.9.5
		Author: Facebook

	Imagify
		Version: 1.8.1.1
		Author: WP Media

	Jetpack by WordPress.com
		Version: 6.4.2
		Author: Automattic

	PW WooCommerce Bulk Edit
		Version: 2.50
		Author: Pimwick, LLC

	Redirection
		Version: 3.4
		Author: John Godley

	SG Optimizer
		Version: 4.0.7
		Author: SiteGround

	SSL Insecure Content Fixer
		Version: 2.7.0
		Author: WebAware

	UpdraftPlus - Backup/Restore
		Version: 1.14.13
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 3.4.4
		Author: Automattic

	WooCommerce Extended Coupon Features FREE
		Version: 2.6.4
		Author: Soft79

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.3
		Author: WooCommerce

	WooCommerce Services
		Version: 1.15.1
		Author: Automattic

	WooCommerce Square
		Version: 1.0.32
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 4.1.9
		Author: WooCommerce

	WPS Hide Login
		Version: 1.4.3
		Author: WPServeur, NicolasKulka, tabrisrp

	Yoast SEO
		Version: 8.1
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property 'select2' of undefined
			at https://www.getflipstik.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:76870
			2018-07-31 23:28 +00:00
			x 3 times

		TypeError: Cannot read property 'html' of undefined
			at https://www.getflipstik.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:80110
			2018-07-31 22:47 +00:00

		TypeError: elementorFrontend.getElements(...).jQuery is not a function
			at https://www.getflipstik.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:147819
			2018-07-31 22:45 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://www.getflipstik.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.4 - 2:138622
			2018-07-24 01:30 +00:00
			x 4 times

**Comment by bainternet** [comment]
please update your elementor pro.
