### ISSUE TITLE
An option to apply templates to sub-categories

### ISSUE THREAD

**Issue by BrockwayProd** [pojome/elementor#5587]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

When publishing and activating a template you have to enter display condition, it could be very usefull to have an option to include (or not) sub-categories of the category you specify. Fopr a number of reasons :

1- It save times if you have a lot of subs
2- It is more dynamic and flexible, let say you add (you or your client) a sub-category, you dont have to go back to your template and add it too.

**Describe the solution you'd like**
Add a checkbox to the category selector to include sub-categories as well.

**Comment by bainternet** [comment]
related to #5321

**Comment by mylimoproject** [comment]
+1

**Comment by dudaster** [comment]
+1

**Comment by MrJoax** [comment]
+1

**Comment by BrockwayProd** [comment]
Ticket have been closed, but not been added to the product, weird.

**Comment by joshtorres** [comment]
Where can this be found? I've been looking for this exact feature and don't see it anywhere

**Comment by BrockwayProd** [comment]
@joshtorres i dont think closed issue are read anymore, we should probably open a new one

**Comment by paradisiacor** [comment]
Will this be available any time soon?

**Comment by MaximMatrosov** [comment]
Hi comrades! Tonight I spent some time and wrote this one. Add this to functions.php and you will have a condition for subcategories of a special product category:

```
class Subcategory_Archive extends ElementorPro\Modules\ThemeBuilder\Conditions\Taxonomy {
	private $taxonomy;

	public function get_name() {
		return 'child_of_' . $this->taxonomy->name;
	}

	public function get_label() {
		return sprintf( __( 'Direct Child %s Of', 'elementor-pro' ), $this->taxonomy->labels->singular_name );
	}

	public function __construct( $data ) {
		parent::__construct( $data );

		$this->taxonomy = $data['object'];
	}

	public function is_term() {
		$taxonomy = $this->taxonomy->name;
		$current = get_queried_object();
		return ( $current && isset( $current->taxonomy ) && $taxonomy === $current->taxonomy );
	}

	public function check( $args ) {
		$id = (int) $args['id'];
		$current = get_queried_object();

		return $this->is_term() && $id === $current->parent;
	}
}
$taxonomy = get_taxonomy('product_cat');
$conditions_manager->get_condition( 'product_archive' )->register_sub_condition( new Subcategory_Archive([ 'object' => $taxonomy ]) );
}, 100 );
```

**Comment by medicamin** [comment]
> **DONE!!!**
> 
> Hi comrades! Tonight I spent some time and wrote this one. Add this to functions.php and you will have a condition for archive of subcategories of a special product category

Hi,
I copied this code to the functions.php file, but I got fatal error, something about unexpected } at the latest line. I need to apply the elementor template to all subcategories of a product-category.

**Comment by MrOizo79** [comment]
So embarassing, 2024 and it's not been done officially yet.
