### ISSUE TITLE
ACF + Elementor with Templates

### ISSUE THREAD

**Issue by RipGill** [pojome/elementor#5588]
I have been pillar-to-post with support on this issue and am looking for a definitive answer please. Also posted on the FB communities with no luck at all.

Using ACF V5 Pro and Elementor Pro (theme GP Premium), all updated.

I created a footer template and attached some ACF fields to it.  The populated fields show in the back-end, but not the front.

Having sent this query to Elementor support (together with a login to my site), they suggested that GP Premium was at fault. Looking into this a little more (and having contacted GP), it appears that Elementor support simply moved the ACF fields from the template to a single page.,

Are ACF fields attached to templates not being parsed to the front-end?

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As far as we know ACF fields render just fine on the front end, I can only guess that you are misunderstanding how ACF fields work in elementor templates.

The data of the fields in the templates are pulled from the "currently" viewed page/post and not the template itself.

thanks.
