### ISSUE TITLE
Image element does not support srcset

### ISSUE THREAD

**Issue by heddesheimer** [pojome/elementor#559]
When adding an image element, the image will always be included with an img-tag in full size. It would be much better regarding performance if the element could use the WP standard behavior (adding a set of srcset attributes in the img-tag), so that the image will load the smaller files on smartphone devices.

You have already implemented it correctly in the image gallery, where it shows several thumbnail sizes.

**Comment by Stegosource** [comment]
This would be a great feature to include. If it help, the function I use a lot to make this easy is wp_get_attachment_image(). You can read more on it here: 
https://developer.wordpress.org/reference/functions/wp_get_attachment_image/

Hope this is helpful.

**Comment by arielk** [comment]
Thanks for you feedback. We will consider it in future releases
Right now I merge it to previous issue in the same subject #537
