### ISSUE TITLE
Feature request: make server variables available as values for widgets

### ISSUE THREAD

**Issue by tucaz** [pojome/elementor#5590]
Hi!

I have a signup workflow in three steps that will offer a PayPal button at the end of the process for the user to pay. My problem is that there is no way for me to co-relate my sign ups with Elementor forms and PayPal unless they use the same email on both ends (which is not always the case).

I could easily figure this out if there was a way to make some server side functions available for Elementor widgets. For example:

1. During the first step I ask for the user email
  - I could add a hidden form field with the user session id (from PHP server)
  - When the user submits the form and goes to the next step the hidden field with the session id would be submited as well
2. On the second step where I ask for the user name and more details
  - Once again I would add a hidden field with the session id that would be the same value since the user is still on the same session (I'm assuming no load balancers are being used or server affinity is on)
3. In the last step, through an HTML field I present the user with an HTML form from paypal
  - In this particular case, I would need to be able to use some sort of Elementor syntax to include the server variable (session ID, once again) in the PayPal form
  - Assuming I had access to this value PayPal would receive it as a custom value that I could later use to correlate if the emails used on both sites don't match
  
I could find a somewhat related question, but the proposed solution is too much of a workaround and rely too much on the client which isn't optimal -> #2017

Also, other variables or even custom functions could be made available for widgets offering more flexibility for the user.

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by tucaz** [comment]
After a couple of hours of research I was able to find dynamic tags and created one. However, I learned that those apply only to "standard" widgets and I can't use them inside form fields or as values inside HTML fields.

**Comment by bainternet** [comment]
I merged this issue with  #4268, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
