### ISSUE TITLE
Form cant't be sent when wp-admin folder is password protected

### ISSUE THREAD

**Issue by tibor-banfalvi** [pojome/elementor#5592]
Hi,

I faced a strange behavior of Elementor Pro: If the wp-admin folder is password protected, users can't send a form built with elementor pro because the web page requests user name and password. For obvious reason users don't have password for wp-admin but without this noone can send the form.

The password protection is set with the "standard" Linux/Apache way and the support team said that Elementor has not been tested in this environment and I should report the issue here in github.

We usually protect wp-admin with password against unauthorized manipulation and it would be very useful if form sending could work with password protected wp-admin folder.

Many thanks in advance,

Tibor

**Comment by bainternet** [comment]
@tibor-banfalvi 

Elementor depends heavily on the WordPress native ajax endpoint which is `admin-ajax.php` under the wp-admin folder.

the only thing I can suggest (maybe) is to whitelist the admin-ajax.php from you Apache basic authentication via a `SetEnvIf` rule something like:
```
SetEnvIf Request_URI "(admin-ajax\.php)$"  allow
```

thanks.
