### ISSUE TITLE
Add content snippet to navigator entries

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#5595]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The navigator is a useful tool for large and complex pages. However, because they are large and complex, seeing a list of widget types (section, heading, text editor, etc.) is of very little use for getting to the precise place to which you want to go.

**Describe the solution you'd like**

Keep the widget type labels, but add to them snippets of the content of the widget - wherever feasible. For example, instead of "Heading", see "Heading-Start of heading..." Similarly, many other widgets contain text that you can easily extract to help see exactly where you are.

**Describe alternatives you've considered**
A more sophisticated approach could put the text in a balloon that appears during mouse over. Thumbnails of images could be shown if the widget is of a graphic or video type.

**Additional context**

Seeing a simple list of sections doesn't help very much:
![image](https://user-images.githubusercontent.com/13927067/44773651-67725380-ab71-11e8-8622-e78f80af76a7.png)

Opening up a section gives a complexity of detail that is even less easy to navigate:
![image](https://user-images.githubusercontent.com/13927067/44773726-94266b00-ab71-11e8-8c76-d99bc6be8b0a.png)

**Comment by bainternet** [comment]
We did some thinking in this area but it came down to the fact that all widgets contain textual data and we wanted it to work with all widgets and not just our own. 

So the best next thing was to allow renaming of each node in the tree, which we did implement by a double-click.

thanks for the suggestion.
