### ISSUE TITLE
Clients keep messing up individual pages by clicking Back to Wordpress editor

### ISSUE THREAD

**Issue by Jaska** [pojome/elementor#5597]
## Prerequisites
- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Clients keep messing up the site when they click "back to wordpress editor" on a page that has been created with Elementor. 

I think the problem is that the "back to the wordpress editor" button text doesn't only change the editor but changes the layout of the page, since it disables elementor.

**Describe the solution you'd like**
Change "back to wordpress editor" -text to "Remove Elementor layout and go back to Wordpress editor"
After clicking maybe some sort of "Warning - this might break the page"?

**Describe alternatives you've considered**
In the role manager, the ability to disable "back to wordpress editor" button on pages created with elementor. However, that might cause more problems. (Users could create elementor pages but not transform them back to regular)

**Comment by Sekhemty** [comment]
Use a template and apply it to that particular page, and couple this with dynamic fields, instead of editing the actual page with Elementor; if you have to let the client edit the content this is the best solution.

**Comment by Jaska** [comment]
@Sekhemty Thanks! That's a good idea. 

Elementor's dynamic fields seem still to be so much in development that not all content can be edited with them. E.g user selects posts with ACF post filter > but there is no place in the posts -widget to put an array of ID's.

I think a better text might at least alert some clients that by clicking the button they are not only changing the editor but disabling all the Elementor layout stuff.

**Comment by srcek** [comment]
In addition to removing "Back to WordPress editor" button for Editor account and lower it would be very useful to have an option to remove "Edit with Elementor" button for pages and posts that were not created using Elementor (that doesn't include templates in Elementor wp-admin options). I often have a situation that client unnecessarily clicks that button and overrides content in native WordPress editor. That would eliminate the problem of an user creating Elementor page or post without an option to go back. "Edit with Elementor" overlay button would, of course, still be available for content editing on pages and post that were previously created by Admin.

Also, it would be useful if we could remove Elementor wp-admin menu item for non-admin users. I'm worried that clients will mess up the templates. There are plugins for such functionality but it would be nice if such option would be included in Role Manager.

**Comment by KingYes** [comment]
Ref: #6588
