### ISSUE TITLE
How to add a new widget?

### ISSUE THREAD

**Issue by nicolas92** [pojome/elementor#56]
Hello, first of all, great plugin, I rated 5 stars :)
I would like to add a new widget, but I can not declare my file, I use the following code:

<pre>function new_widget() {
	
	$build_widgets_filename = [
		'widget1',
		'widget2',
	];

	foreach ( $build_widgets_filename as $widget_filename ) {
		include( $this->plugin_path . 'includes/widgets/' . $widget_filename . '.php' );

		$class_name = ucwords( $widget_filename );
		$class_name = str_replace( '-', '_', $class_name );
	}

}
add_action( 'init', 'new_widget', 20 );</pre>

But this code does not work, can you help me?
Thank you a lot :)

**Comment by yehudah** [comment]
Hi,

We still don't have official API, but you can write a regular WordPress widget and he will be available in builder widgets.

**Comment by KingYes** [comment]
@nicolas92  Fast example:
`
add_action( 'elementor/widgets/widgets_registered', function() {
	\Elementor\Plugin::instance()->widgets_manager->register_widget( 'WIDGET_CLASS' );
} );
`

Change the `WIDGET_CLASS` to your own class of the widget.

BTW, as @yehudah say, it's not official API to register widgets, so maybe it's can to change in later versions of the Elementor. But for now it's need to be work for you.

**Comment by nicolas92** [comment]
Ah thin, I thought it was possible, prévoyer you do it in long time?
I think your plugin will cartoning, so many dévelloppeur will want to integrate their own widgets like visual composer.

**Comment by nicolas92** [comment]
Thank you very much @KingYes, but it is not urgent, I'll wait for the official API, thank you :)

**Comment by KingYes** [comment]
No problem :)
Thanks for your review and 5-stars 👍

**Comment by nicolas92** [comment]
You deserved, amazing plugin :)

**Comment by jonathanbossenger** [comment]
@KingYes I hope you don't mind me commenting on this, but it would be helpful to get this added to the newly created developer portal - https://developers.elementor.com/creating-a-new-widget/

**Comment by shangdev** [comment]
@jonathanbossenger Hello,when I created customize new widget，There are some Widget Controls not  working, E.g： SLIDER/COLOR/SWITCHER, 

Have you encountered this problem?

**Comment by vollyimnetz** [comment]
I used the following code inside my functions.php to add an elementor-widget.
```
add_action( 'elementor/widgets/widgets_registered', function($elementorWidgetManager) {
	include_once __DIR__.'/path-to-my-widget-file.php';
	$elementorWidgetManager->register_widget_type( new MyCustomElementorWidget() );
});
```
By making the include of the code inside the action-hook, i can make sure elementor is installed, active and already loaded.
