### ISSUE TITLE
Adding a custom social icon

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#560]
You've got all the usual suspects covered in the widget, but I'd like to be able to upload a custom social icon for a more specialized audience. If this cannot be done, please consider it a feature request.

The icon can be seen here: https://twitter.com/Historypin, and the account I want to link to is https://www.historypin.org/en/person/51745

**Comment by arielk** [comment]
We are considering it for the future, right now I merge it to previous issue in the same subject #110
