### ISSUE TITLE
Empty link in header

### ISSUE THREAD

**Issue by bendqh** [pojome/elementor#5600]
I use latest WP and Elementor.

Headings that are linked to somewhere are found as empty links (empty a tags) by the WAVE accessibility tool.

The reason is because the `a` tag as no text.

It happens with heading tags that are links.

**Or I'm wrong and the problem is with Header-Footer-Elementor**.

---

![1](https://user-images.githubusercontent.com/31392185/44786788-e67d8100-ab9d-11e8-9d53-fb1a7a2cc29c.PNG)
![2](https://user-images.githubusercontent.com/31392185/44786790-e7161780-ab9d-11e8-88a7-63d57a7de367.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
