### ISSUE TITLE
Dynamic Content => ACF is missing since newest update

### ISSUE THREAD

**Issue by Hetim** [pojome/elementor#5604]
Hey. We´ve update to the newest elementor pro version. In the prior version there was an option within dynamic content fields called "ACF (Beta)". This is missing now leading to missing content within our templates. Was this feature removed?

Thank you!

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

as for ACF Dynamic tags, they recently came out of beta but require ACF 5+

thanks.

**Comment by Djimusic** [comment]
@bainternet ACF5+ is in early access. It is not out of beta. https://www.advancedcustomfields.com/resources/upgrade-guide-version-5/

It requires you to go into the code to enable it, and after enabling it, it still does not work with Elementor. List is still empty.
