### ISSUE TITLE
Add option to set border padding in image widget

### ISSUE THREAD

**Issue by vgstef** [pojome/elementor#5606]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This option would make it possible to change the distance between the image and the border.

**Describe the solution you'd like**
In the image widget, in the style tab, under border type, I'd like a field to enter the padding for the border.

![image](https://user-images.githubusercontent.com/5083355/44801640-94c9fc00-ab87-11e8-9eba-86204b83af55.png)

**Describe alternatives you've considered**
I can use custom CSS, but that's less convenient.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, You can give the widget a border instead of the image and set the widget padding


Thanks for the feedback.

**Comment by vgstef** [comment]
Thanks for the reply. But just to say that your proposition doesn't work if we add a radius to the image. See image. First one is with custom CSS on the image, second is with widget border.
![image](https://user-images.githubusercontent.com/5083355/44855173-78d26300-ac38-11e8-9d20-5f272f8f7110.png)
