### ISSUE TITLE
Unable to get drop downs from menu on iPad

### ISSUE THREAD

**Issue by tampainternet** [pojome/elementor#5607]
Prerequisites.
You must go to www.polkeldercare.com on an iPad

Steps to replicate.
Once you open the site, you can see the menu created with Elementor, try to click on the links to open the sub-menus, they do not open on multiple iPads we have tried. This only happens in landscape mode, when you hold the iPad in portrait, it will work.

Isolating the problem.
The problem seems to be something with the way that the Elementor menu is handling the drop-downs. They work fine on a computer and a mobile phone (hamburger menu) but in landscape mode on iPad they do not work.

System info.
iPad 9.7 inch 32GB 2018 model also tried on an iPad Pro 1.29 inch

**Comment by bainternet** [comment]
We can't replicate,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
