### ISSUE TITLE
Feature Request: Custom Loop with custom key sort and custom field (ACF)

### ISSUE THREAD

**Issue by carasmo** [pojome/elementor#5608]
I was instructed to create a feature request:

This is what feature I want:

Elementor Pro pull a custom loop using a custom sort key and also use a custom field inside that loop instead of the standard (Title, content, Featured image).

Generally, if I'm using elementor to build a page so that the client can move stuff around later, but they have a custom request, I build a loop, create a shortcode and stick that in a plugin and then use that in the Elementor shortcode area. Also, many times there are situations where the page title is super long and there needs to be a short title, so I create an ACF field and use that short title instead.

So both a custom key, like featured to use and then also the menu order (the order they've dragged the post order with something like Intuitive CPT order) and then a loop that uses instead of the standard fields, you can choose which ones you want to grab:

Excerpt OR
Content truncated and the more setting (choose the character length and the more)
The Post Title on or off
other fields that are inside that post type.

Thanks!

**Comment by bainternet** [comment]
@carasmo 
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

as for a custom query based on a custom field and custom order you can use the [Custom Query filter](https://developers.elementor.com/custom-query-filter/)

and the custom elements in the loop item it was already requested here #4440

thanks.
