### ISSUE TITLE
[Slides Widget] Option to disable all interaction

### ISSUE THREAD

**Issue by SirWellington** [pojome/elementor#5614]
## Prerequisites

- [ X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I am using the Slides widget on the front page of our site. It works well on the desktop, but there is an issue on mobile devices.

Whenever I use the site on a mobile the slide pauses whenever you scroll down. Actually, whenever you touch or click on the slides, it pauses. 

Basically here is how you reproduce:

1. Create a slides widget with 3-5 slides
2. Enable autoplay
3. Disable controls
4. Disable option to pause on hover
5. Load the page
6. Wait a few seconds and watch as the slides go by.
7. Click/tap/drag on the slides. 

Do all the above and you will notice the slides have now paused.

In the meantime, I have fixed this with this custom css:

```css`
selector
{
  pointer-events: none;
  touch-action: none;
}
```

But it would be nice to have this option on the widget itself.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by rinibak** [comment]
I would love to have this feature and also to make the slider completely non interactive in any way. It just runs and never stopps, not with hovering or grabbing with the mouse, not with anything. This way I can have 2 sliders side by side, starting together when the page loads and moving forward at the same time. That would be great to see. 

But even better than this, for my own purposes, would be to have the option to have the slider widget time together with a second slider widget on the same page. That would be perfect!

**Comment by Arkwell** [comment]
This option should definitely exist

**Comment by nviitala** [comment]
Yep, there could be a easier way to disable the interactions eg. for desktop only, while keeping those for mobile.
