### ISSUE TITLE
Blacklist domains in Contact form

### ISSUE THREAD

**Issue by janicek01** [pojome/elementor#5616]
Elementor is the best :-)
I would like to have an opprtunity to block email addresses (from senders) from for example @gmail.com, @yahoo.com, etc.
Maybe you could add text-box named company-mail and there will be posibility to add domain to be blocked.
Thanks 
Piotr Janicki

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

as for your request, you can already do that with the provided filter hooks, eg:

```PHP
add_action( 'elementor_pro/forms/validation/email', function( $field, $record, $ajax_handler ) {
	// validate email format
	if ( ! is_email( $field['value'] ) ) {
		$ajax_handler->add_error( $field['id'], 'Invalid Email address, it must be in the format XX@XX.XX' );
		return;
	}

	$black_list_domains = [
		'gmail.com',
		'domain.com',
	];

	$email_domain = explode( '@', $field['value'] )[1];

	if ( in_array( $email_domain, $black_list_domains ) ) {
		$ajax_handler->add_error( $field['id'], 'Invalid Email address, emails from the domain ' . $email_domain . ' are not allowed.' );
		return;
	}
}, 10, 3 );
```

thanks.

**Comment by janicek01** [comment]
Thanks for your reply

**Comment by KingGrizzly** [comment]
This is very helpful. Is there a way to run this selectively? I'm wondering about the instance where a client might only want to run this function against certain forms but not all. Thanks!

**Comment by gilreyesdesign** [comment]
> Thanks for the feedback,
> Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
> This report is missing key information:
> 
> * Prerequisites.
> * Description and examples.
> 
> as for your request, you can already do that with the provided filter hooks, eg:
> 
> ```
> add_action( 'elementor_pro/forms/validation/email', function( $field, $record, $ajax_handler ) {
> 	// validate email format
> 	if ( ! is_email( $field['value'] ) ) {
> 		$ajax_handler->add_error( $field['id'], 'Invalid Email address, it must be in the format XX@XX.XX' );
> 		return;
> 	}
> 
> 	$black_list_domains = [
> 		'gmail.com',
> 		'domain.com',
> 	];
> 
> 	$email_domain = explode( '@', $field['value'] )[1];
> 
> 	if ( in_array( $email_domain, $black_list_domains ) ) {
> 		$ajax_handler->add_error( $field['id'], 'Invalid Email address, emails from the domain ' . $email_domain . ' are not allowed.' );
> 		return;
> 	}
> }, 10, 3 );
> ```
> 
> thanks.


Just following up on this, I can't get it to only work on specific forms. Is there something I am missing?

Thank you so much

**Comment by ncumrktng** [comment]
Where do I put this code so that it works? Does it go on the custom css of the form?

**Comment by KingGrizzly** [comment]
@ncumrktng It needs to go in your theme's (or child theme's) functions.php file. Careful, this can crash your site if you do it wrong. Look for wp-content/themes

**Comment by ncumrktng** [comment]
@KingGrizzly Oh snap, thanks for the warning.

**Comment by rcholsk** [comment]
> This is very helpful. Is there a way to run this selectively? I'm wondering about the instance where a client might only want to run this function against certain forms but not all. Thanks!

Hi do you have an answer for the question?

**Comment by johnehshankar** [comment]
This stopped working after (either) Wordpress 5.5+ or Elementor 3.1+

Somebody provide a solution! I checked the php file, the code is still there, but form is accepting all domains.

**Comment by EladGeek** [comment]
I've been using this solution, works like a charm :)

I would want to have the option to set this to apply only on selected forms (e.g. exclude webinar forms).
How can I trigger this selectively, for example only for email fields with the name "work_email"?

**Comment by johnehshankar** [comment]
This code now blocks legit customer emails as well. Any solution found?

**Comment by SergioTijero** [comment]
> This code now blocks legit customer emails as well. Any solution found?

This code is for blocking every email that ends in a specific domain, it does not allow "legit emails or sth"

**Comment by SergioTijero** [comment]
Hey Y'all

I read some of you were asking to put this code in a specific form, well i managed to get this on a specific page/post:

`//Hook para evitar correos que no son corporativos UwU

	add_action( 'elementor_pro/forms/validation/email', function( $field, $record, $ajax_handler ) {
	// for specific post:
	global $post;
	if( $post->ID == 149622) {

		$black_list_domains = [
			'gmail.com',
			'domain.com',
		];


		$email_domain = explode( '@', $field['value'] )[1];

	
		if ( in_array( $email_domain, $black_list_domains ) ) {
			$ajax_handler->add_error( $field['id'], 'Lo sentimos, correos como ' . $email_domain . ' No están permitidos, intenta usar tu correo corporativo.' );
			return;
		}
	}
}, 10, 3 );`

So this code just works only on post ID 149622 and does not affect any other form outside that post. 
Sorry for my bad english.

**Comment by tedidimbg** [comment]
Hello,
This doesn't work for me. Is there something new this year? I usually use Code Snippets plugin for my WordPress site and when I tried to add the code above nothing happened. Still the free emails can be submitted. Can you help me here? I use Elementor Multi-step form. 
Thanks

**Comment by SergioTijero** [comment]
> Hello, This doesn't work for me. Is there something new this year? I usually use Code Snippets plugin for my WordPress site and when I tried to add the code above nothing happened. Still the free emails can be submitted. Can you help me here? I use Elementor Multi-step form. Thanks

You should add the code snippet on functions.php

**Comment by tedidimbg** [comment]
> > Hello, This doesn't work for me. Is there something new this year? I usually use Code Snippets plugin for my WordPress site and when I tried to add the code above nothing happened. Still the free emails can be submitted. Can you help me here? I use Elementor Multi-step form. Thanks
> 
> You should add the code snippet on functions.php of your theme (or you could make it a plugin located on /wp-content/mu-plugins)

Hello SergioTijero,
I don't have an access to functions.php and the files in general. I though it would work with code snippets. Any other suggestions from you without control panel access? Thank you.

**Comment by SergioTijero** [comment]
> > > Hello, This doesn't work for me. Is there something new this year? I usually use Code Snippets plugin for my WordPress site and when I tried to add the code above nothing happened. Still the free emails can be submitted. Can you help me here? I use Elementor Multi-step form. Thanks
> > 
> > 
> > You should add the code snippet on functions.php of your theme (or you could make it a plugin located on /wp-content/mu-plugins)
> 
> Hello SergioTijero, I don't have an access to functions.php and the files in general. I though it would work with code snippets. Any other suggestions from you without control panel access? Thank you.

You need to have access to functions.php in order to use this function, maybe do you have access to files via FTP? Can you add plugins to your wordpress site?

**Comment by tedidimbg** [comment]
> > > > Hello, This doesn't work for me. Is there something new this year? I usually use Code Snippets plugin for my WordPress site and when I tried to add the code above nothing happened. Still the free emails can be submitted. Can you help me here? I use Elementor Multi-step form. Thanks
> > > 
> > > 
> > > You should add the code snippet on functions.php of your theme (or you could make it a plugin located on /wp-content/mu-plugins)
> > 
> > 
> > Hello SergioTijero, I don't have an access to functions.php and the files in general. I though it would work with code snippets. Any other suggestions from you without control panel access? Thank you.
> 
> You need to have access to functions.php in order to use this function, maybe do you have access to files via FTP? Can you add plugins to your wordpress site?

Yes, I can add plugins. Usually 'code snippets' plugin is for that, to add custom code css php javascript. You mean to install files via plugin?

**Comment by SergioTijero** [comment]
It seems like it should work on code snippets plugin, I do not know
whats wrong (maybe you should contact your plugin support).

May I ask why don't you have access to files / functions.php?

**Comment by tedidimbg** [comment]
Hi SergioTijero,
I finally made it. thank you

**Comment by johannameng** [comment]
> Hi SergioTijero, I finally made it. thank you

hi, could you tell me how to do this? I want to allow customers to fill in only business email addresses on certain form, and i also use plugin"code snippets" to add custom code. thanks!

**Comment by caspervoogt** [comment]
the [Email Blacklist For Elementor Forms](https://wordpress.org/plugins/email-blacklist-for-elementor-forms/) does this
