### ISSUE TITLE
Link height of multiple inner sections

### ISSUE THREAD

**Issue by pb52** [pojome/elementor#5618]
I have a site where there are three central columns, created as inner sections.  I want to have them all of equal height regardless of the fact that they have differing amounts of content.

I would like to be able to choose an option in the outer section properties to "Link inner section height" or words to that effect, that will tie the inner sections together so that the height of all of the them is dependent of the length of content in the highest one

Thanks for listening

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.


Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
