### ISSUE TITLE
Elementor Flip Box Color Issue

### ISSUE THREAD

**Issue by Momenti88** [pojome/elementor#5625]
I'm trying to change the description color for my  "back box" text. It doesn't seem to be changing and this makes it very difficult to read on dark color backgrounds. Although I don't have any text in the "front box," it still seems to be an issue. I'm not sure if this has something to do with my website code or a problem with the Flip Box plugin. 

Any advice is appreciated. 

http://www.martinfoods.com/subdomain/test/

**Comment by carnationrose** [comment]
I'm having the same problem. Whatever I do, the flip boxes don't change and stay with default settings.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
