### ISSUE TITLE
Show Delayed Content

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#5627]
Hello guys,

On the Elementor, I can create a button and insert an amount in seconds for that button to appear.

In this same scheme you guys could give the possibility of putting an amount of time in arrears to show an entire content.

See an example on this page https://ingleswinner.com/site/aula-memorizacao/. Only one video is shown and after 28 minutes an entire content is displayed.

https://drive.google.com/open?id=1GuUIV7V4pbdHDLfhqcZRCkQJ6JwHvH-P

Thank you.
Rodrigo

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
