### ISSUE TITLE
Bug: ACF Field shortcode breaks entire Template Editor

### ISSUE THREAD

**Issue by collindavis** [pojome/elementor#5629]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When adding ACF Field shortcode [acf field="fieldname"] to Elementor Text Field widget it breaks the entire Elementor Edit Template page.

## Steps to reproduce

1. Create a new template.
2. Add a text field widget or shortcode widget.
3. Add [acf field="fieldname"] shortcode. Use a valid fieldname that is setup with ACF.
4. Click publish. Now refresh the Edit Template page or exit the editor and go back to it. It will be blank. Only way to correct is to delete template altogether.

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 5.5.5
	PHP Version: 7.1.17
	PHP Max Input Vars: 3000
	PHP Max Post Size: 55M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://app-5b73b442f911c811445125f2.closte.com
	Home URL: https://app-5b73b442f911c811445125f2.closte.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.1.4
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Adminimize
		Version: 1.11.4
		Author: Frank Bültge

	Admin Menu Editor
		Version: 1.8.4
		Author: Janis Elsts

	Advanced Custom Fields
		Version: 5.7.2
		Author: Elliot Condon

	Custom 404 Pro
		Version: 2.1.3
		Author: Kunal Nagar

	Custom Post Type UI
		Version: 1.5.8
		Author: WebDevStudios

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Ele Custom Skin
		Version: 1.0.5
		Author: Liviu Duda

	Elementor
		Version: 2.2.0
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.6
		Author: Elementor.com

	GP Premium
		Version: 1.7.2
		Author: Tom Usborne

	LiteSpeed Cache
		Version: 2.4.3
		Author: LiteSpeed Technologies

	WP Custom Login Page Logo
		Version: 1.4.8.3
		Author: Lars Ortlepp

	WP Google Analytics Events Pro
		Version: 2.2.9
		Author: PineWise

== Must-Use Plugins ==
	closte-requirements.php
		Version: 
		Author: 

== Debug ==
	Errors: 
		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=608&action=elementor - 2:2
			2018-08-24 07:14 +00:00

		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=544&action=elementor - 2:2
			2018-08-24 07:14 +00:00

		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=225&action=elementor - 2:2
			2018-08-24 07:13 +00:00

		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=371&action=elementor - 2:2
			2018-08-24 02:07 +00:00

		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=225&action=elementor - 2:2
			2018-08-24 00:02 +00:00

		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=626&action=elementor - 2:2
			2018-08-23 23:41 +00:00
			x 3 times

		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=544&action=elementor - 2:2
			2018-08-22 22:06 +00:00

		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=608&action=elementor - 2:2
			2018-08-22 07:44 +00:00
			x 4 times

		ReferenceError: CTMVP is not defined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-admin/post.php?post=544&action=elementor - 2:2
			2018-08-21 22:29 +00:00
			x 5 times

		TypeError: Cannot read property 'select2' of undefined
			at https://app-5b73b442f911c811445125f2.closte.com/wp-content/plugins/elementor/assets/js/editor.min.js - 2:76870
			2018-08-21 20:06 +00:00
				
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
