### ISSUE TITLE
Menu cart widget refresh without re-loading page (Ajax)

### ISSUE THREAD

**Issue by Federicro** [pojome/elementor#5634]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Allow the page not to reload every time a product is added or deleted from the cart.

**Describe the solution you'd like**
Avoiding page reload, probably using Ajax.
So far I used [this plugin](https://wordpress.org/plugins/side-cart-woocommerce/) (WooCommerce Cart, By XootiX) and it worked flawlessly, with Ajax functionality.

**Describe alternatives you've considered**
I understand that some could find this solutions could slow down the website, thus it could be set as  optional.

**Comment by bainternet** [comment]
@Federicro 

The menu cart widget works with AJAX out of the box.

thanks

**Comment by Federicro** [comment]
@bainternet 

The issue I reported is not related to the use of Ajax, but to the fact that **the webpage reloads every time an item is added or deleted from the cart**.
The reason why I'm leaving both the elementor cart plugin and the WooCommerce Cart by XootiX working on the page is to give you and other people willing to contribute examples to understand what I'm saying.

Thanks
