### ISSUE TITLE
Request Spacing Tab

### ISSUE THREAD

**Issue by Xanemi** [pojome/elementor#5635]
I have a hard time moving around ( padding, marging ) sections, columns and widgets.

Elementor's customers would increase simply by adding freedom of movement. Just by adding a useful yet powerful spacing tab. Also seen in Webflow or Css Hero.  

Reference.

![spacing tab](https://user-images.githubusercontent.com/42873960/44925816-70a02380-ad1d-11e8-9ad3-10f4eab4a398.png)

**Comment by bainternet** [comment]
I merged this issue with  #5018, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
