### ISSUE TITLE
[Feature Request] Custom post & taxonomy options for header display rules 

### ISSUE THREAD

**Issue by awisechoicecomm** [pojome/elementor#5637]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I can't see a way to apply custom post taxonomy archive display rules to my header/navigation templates. The only display rules options I can see are for standard post and event archives. As a result, certain custom post taxonomy archive/query pages do not show the correct header/navigation.     

**Describe the solution you'd like**
I'd like to see custom posts and taxonomies included in the display rule options for header and footer templates. Elementor does include custom post and taxonomy query options in the Posts element, so I'm hoping it can be extended to header display rules.

**Describe alternatives you've considered**
I tried using the "Elements" feature of GeneratePress -- which does list custom post types and taxonomies in their display rules --  to override my Elementor headers where desired. That didn't work. I also tried applying the standard post categories and tags to the desired custom posts with the hope that I could create some combination of standard post rules that would somehow make my custom post/taxonomy query page show with the right header. That didn't work either.

**Additional context**
I've been at this for several hours and am a bit sleep deprived. I would love to discover that I am missing something obvious in my addled state. But if not, please consider this as a future enhancement. Thank you.

**Comment by donwattz1459** [comment]
You can already do this. At least I see it on my version.

In my case "Services" is a CPT and "In Service Type" is the taxonomy.

![screenshot at sep 05 15-49-19](https://user-images.githubusercontent.com/16137152/45117364-63bb6f80-b123-11e8-9b9c-d741b4fb05a0.png)

**Comment by awisechoicecomm** [comment]
Thanks for responding, @donwattz1459! I know it's available for singular page or post types. I'm looking to apply a specific navigation header to an **archive** query page for a particular CPT taxonomy. As far as I can tell, that same ability to designate a CPT and taxonomy is not available for archive queries. I've attached a screenshot of the selection options for applying a header to an archive. It's limited to just standard post archives and event archives.

Would love to know of a way to select CPT taxonomy archives!
![screen shot 2018-09-05 at 3 40 15 pm](https://user-images.githubusercontent.com/42885843/45120152-f1e32600-b122-11e8-9ac2-0da9312618cc.png)

**Comment by donwattz1459** [comment]
I see my CPT archive in the header builder conditions. When building your CPT, make sure you enable Archives for the CPT. Especially when using CPT UI plugin.

![screenshot at sep 05 16-49-56](https://user-images.githubusercontent.com/16137152/45120331-c87ac800-b12b-11e8-9717-a7ca5f6aaed3.png)

**Comment by awisechoicecomm** [comment]
THAT'S IT! I had not enabled archives in CPT UI. **I love it** when the solution is as easy as that. Thank you SO MUCH, @donwattz1459! Really appreciate your taking the time. Made my day. :)

**Comment by donwattz1459** [comment]
My pleasure! :)
