### ISSUE TITLE
Product Page Builder + Woocommerce Extra product Options

### ISSUE THREAD

**Issue by gelebrin** [pojome/elementor#5638]
Hi there, I am using Plugin Woocommerce Extra product Options

(https://codecanyon.net/item/woocommerce-extra-product-options/7908619?_ga=2.57127786.1556676578.1535535284-1291958338.1525985732)

And Created Product Page using Elementor builder but those options not showing up.(When using Woocommerce Pages Widget also those options not appear) Please Make it happen I am really in need)

To understand my issue more deeply please check this threat(I had conversation with plugin author)

https://support.themecomplete.com/forums/topic/elementor-compatability/

Thanks

**Comment by bainternet** [comment]
Try to figure out what hooks the plugin is using and you can add theme using the solution suggested [here] (https://github.com/pojome/elementor/issues/5574#issuecomment-417086857)
which is basically have a shortcode wrapper to allow placement of hooks when and where needed.

```PHP
/**
 * Usage: [do_hook hook="hook_name"]
 **/
add_shortcode( 'do_hook', function( $atts = array(), $content = null, $tag = ''){
	if ( isset( $atts['hook'] ) ) {
		ob_start();
		do_action( $hook );
		return ob_get_clean();
	}
	return;
});
```
