### ISSUE TITLE
Safari Reader-View

### ISSUE THREAD

**Issue by monimor** [pojome/elementor#5639]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Safari for Mac has a feature called Reader-View, which reduces the content of a site to the content of interest only - removing headers, sidebars, footers, ads etc. just presenting the article with title, text and pictures of interest for the viewer. The Text is presented in an easy to read format, font and size.
Reader view can be started by clicking a symbol in the adress-line.
Unfortunately Elementor does not seem to work with reader view - the only content presented is H1 Title.
The implementation of Reader view compatibility would be great.

Kind Regards,
Michael

<img width="933" alt="bildschirmfoto 2018-09-01 um 20 55 11" src="https://user-images.githubusercontent.com/42897416/44949066-2789c580-ae2a-11e8-8827-f2c1b5d19842.png">

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.


Thanks for the feedback.

**Comment by elaine-fabrica** [comment]
Hi, any update on this issue. Accessibility standards are gaining momentum. I have only seen 1 article from Elementor mentioning accessibility, but no comment on the reader's view

**Comment by hollistergj** [comment]
Still getting the same answer from Elementor support. 

> _I've inspected this further and sadly, it seems that Safari reader functionality is not supported within Elementor. I have tagged this ticket as a feature request so that this option can be considered by our development team and possibly added into one of the next updates. I cannot make promises whether this feature will be implemented and when..._
