### ISSUE TITLE
Numbered item list

### ISSUE THREAD

**Issue by vgstef** [pojome/elementor#5641]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to make a list of numbered items. Similar to the icon list, but with number starting at 1 and going up as I add items.

**Describe the solution you'd like**
The ideal solution would be a widget similar to the icon list (or an option in the icon list widget) that would automatically show the item number next to it.

**Describe alternatives you've considered**
I've considered using a text block with a list of numbered items, but it's not convenient to customize. I could also use the icon list widget and set a different icon showing a number for each item, but it's really cumbersome.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by ChriKn** [comment]
One more demand

**Comment by rajjys** [comment]
It sucks not to have this feature

**Comment by joaonew** [comment]
agreed. Sucks doesn't having it.

**Comment by GreyVod** [comment]
Yes please. Add another user request here. It shouldn't be that difficult to implement, and it really seems like something that should be there from the ground up.

**Comment by pdmwu** [comment]
We need customization options for the list: numbered list / unordered list (potentially more options)
