### ISSUE TITLE
Social Sharing Widget: Don't show numbers until threshold met.

### ISSUE THREAD

**Issue by mikesale** [pojome/elementor#5648]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Clients do not want to show zero or low social mention numbers, but want to share when they reach a threshold, ideally specific to each network.

**Describe the solution you'd like**
Client has been using Social Warfare Pro and would like to be able to only show mention count for each widget if threshold has been crossed (i.e. never show zero shares, only show when greater than X where X is a positive integer)

**Describe alternatives you've considered**
Don't use Elementor sharing widget

**Additional context**
Feature common in Social Welfare sharing

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


But seeing that [more](https://twittercommunity.com/t/a-new-design-for-tweet-and-follow-buttons/52791) and [more](https://plus.google.com/110610523830483756510/posts/Z1FfzduveUo) social networks are removing the count option it's not likely.

Thanks for the feedback.
