### ISSUE TITLE
Image size options

### ISSUE THREAD

**Issue by Stegosource** [pojome/elementor#565]
This is just a feature request.

Currently the image element does not give the option to select from the various image sizes available (ie. thumbnail, medium, medium_large, full). Currently it only includes the full size by default. 

It would be nice to have the option to select image sizes for a scenario like this: 

Let's say I build a page that requires a very large image. I can upload something very large and use it. No problem. Next, I build a page with several smaller thumbnail images, one of which links to that first page. And I want to use the same image, but I only need a small version. I will either have to use the full size image, or upload a new, small image. If I had the option to select sizes, it would be a bit easier.

**Comment by arielk** [comment]
We plan to add this improvement in the next versions.
Right now I merge it to previous issue in the same subject #537

**Comment by Stegosource** [comment]
Ah sorry. I tried searching before posting, I promise. Just used the wrong keywords I guess :/

**Comment by arielk** [comment]
It's OK :)
