### ISSUE TITLE
[Feature Request] Add link to whole box of image box element

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#5650]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I used many image box elements in a mega menu and i notice that the image and the title only are clickable to follow the link specified. It would be nice if there could be a setting to link the whole box to the url.

You'll see the example here: https://test.lisskids.nl

**Comment by bainternet** [comment]
@knireis 

You can do that with the provided hooks, simply strip the current links and wrap the widget in a link, ex:

```PHP
add_action( 'elementor/widget/render_content', function( $output, $widget ) {
	//make sure its an image box widget
	if ( 'image-box' !== $widget->get_name() ) {
		return $output;
	}
	$settings = $widget->get_settings_for_display();
	// Strip current links
	$output = preg_replace( '/<a[^>]+>([^<]+)<\/a>/i', '\1', $output );
	// Wrap widget out put with a link
	$output = '<a ' . $widget->get_render_attribute_string( 'link' ) . '>' . $output . '</a>';
	return $output;
}, 10, 2 );
```

**Comment by knireis** [comment]
thanks, and i guess this is not a support forum, but with this code only the image gets the link

**Comment by AlexVonB** [comment]
Can confirm @knireis issue, the snippet above only works on the `h3` element, and only when there are no HTML tags in the header text; the regex matches on 'not <', which fails when any HTML tag is inside a link (as with the `img` tag inside the figure link).

This snippet finds the `p` tag (when there are no `<` in it) and wraps it with a link:
```php
add_action( 'elementor/widget/render_content', function( $output, $widget ) {
	//make sure its an image box widget
	if ( 'image-box' !== $widget->get_name() ) {
		return $output;
	}
	$settings = $widget->get_settings_for_display();
	// Strip current links
	$output = preg_replace( '/<p[^>]+>([^<]+)<\/p>/i',
		'<a ' . $widget->get_render_attribute_string( 'link' ) . '>\0</a>', $output );
	return $output;
}, 10, 2 );
```

Dirty hack, but does the job.

**Comment by vgstef** [comment]
I also have this issue. I tried both codes (from bainternet and from AlexVonB) and none works for the whole image box. Maybe it's because I have animations on the image.

So any other workaround?

I really think Elementor should add the option to apply the link to the whole imagebox. In fact, I don't understand why it isn't already the case.

**Comment by DaninDC** [comment]
+1

**Comment by daviedR** [comment]
Hi all, I tried to do some modifications to both frontend markup and editor's JS template. Here is the snippet:

https://gist.github.com/daviedR/bbde49c0e1a32f4866d2479c2b2e5d2d

This will remove the original link on image and title and then add a link on the wrapper tag. Now the whole element becomes a link.

Let me know if what you think.

**Comment by lifecarewebsite** [comment]
> 
> 
> Hi all, I tried to do some modifications to both frontend markup and editor's JS template. Here is the snippet:
> 
> https://gist.github.com/daviedR/bbde49c0e1a32f4866d2479c2b2e5d2d
> 
> This will remove the original link on image and title and then add a link on the wrapper tag. Now the whole element becomes a link.
> 
> Let me know if what you think.

And where exactly do we need to place this file?

**Comment by Ryan-Not-Reynolds** [comment]
> 
> 
> Hi all, I tried to do some modifications to both frontend markup and editor's JS template. Here is the snippet:
> 
> https://gist.github.com/daviedR/bbde49c0e1a32f4866d2479c2b2e5d2d
> 
> This will remove the original link on image and title and then add a link on the wrapper tag. Now the whole element becomes a link.
> 
> Let me know if what you think.

And where exactly do we need to put this code?

**Comment by daviedR** [comment]
@Ryan-Not-Reynolds you can put this on your Child Theme's `functions.php`. Or you can create a tiny custom plugin.

**Comment by vgstef** [comment]
Why is this issue closed? That was a feature request still not in Elementor. 

Strangely, a whole box link is already present for the icon box, why not add it to the image box?

**Comment by 1704eu** [comment]
there is a plugin that solves this issue. [Make Column clickable](https://wordpress.org/plugins/make-column-clickable-elementor/)

**Comment by zachkinsey** [comment]
> 
> 
> there is a plugin that solves this issue. [Make Column clickable](https://wordpress.org/plugins/make-column-clickable-elementor/)

That plugin doesn't solve the issue. That plugin only works with columns, not image box widgets.

**Comment by viveknath322** [comment]
Add the below code in custom css of imagebox or icon box widget
`selector a:after { content: ""; display: block !IMPORTANT; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1; }`

**Comment by Zach-Toth** [comment]
> selector a:after { content: ""; display: block !IMPORTANT; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1; }

This works great! Nice simple solution. Thanks!

**Comment by je-vallejo** [comment]
> Hi all, I tried to do some modifications to both frontend markup and editor's JS template. Here is the snippet:
> 
> https://gist.github.com/daviedR/bbde49c0e1a32f4866d2479c2b2e5d2d
> 
> This will remove the original link on image and title and then add a link on the wrapper tag. Now the whole element becomes a link.
> 
> Let me know what you think.

@daviedR Thanks! This kinda works, but it changed the position of my images. They were centered over the title and now they are left and up in the container. Can't change it back using the elementor editor. Any ideas?

Still +1 on a proper implementation on Elementor... Issue should be reopened

**Comment by je-vallejo** [comment]
> Add the below code in custom css of imagebox or icon box widget
> `selector a:after { content: ""; display: block !IMPORTANT; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1; }`

This won't work if you're not using Elementor Pro... correct?

**Comment by soyrubio** [comment]
The plugin Essential Addons for Elementor (https://wordpress.org/plugins/essential-addons-for-elementor-lite/) solved the issue for me (even the free version). It adds a Wrapper Link option in the Advanced tab for all building blocks.

**Comment by sriramgroot** [comment]
When this feature request will addressed, because we are also facing this issue.
