### ISSUE TITLE
option to limit Title widget characters / words

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5652]
I need to be able to limit dynamic [heading widget](https://docs.elementor.com/article/46-heading) characters  / words.
using this maybe?
https://codex.wordpress.org/Function_Reference/wp_trim_words

![image](https://user-images.githubusercontent.com/2544046/44983000-4d28e300-af80-11e8-961f-c715845410c2.png)

**Comment by bainternet** [comment]
@amindiary 

There are many ways you can achieve that:

* [Custom dynamic tag](https://developers.elementor.com/dynamic-tags/) which will limit the output.
* Use [Elementor hooks](https://code.elementor.com/php-hooks/#elementorwidgetrender_content) to modify the output.
* Via [ACF validation](https://www.advancedcustomfields.com/resources/acf-validate_value/).
* [Custom widget](https://developers.elementor.com/creating-a-new-widget/) which extends the Heading widget.

**Comment by amindiary** [comment]
if someone needed:

 ```
  function summary($content, $limit = 200) {
    $content = strip_tags($content);
    // Take the existing content and return a subset of it
    $end = '';
    if (strlen($content) > $limit) {
        $end = '...';
    }
    return substr($content, 0, $limit) . $end;
} 
    
add_action( 'elementor_pro/posts/query/custom_query_ID', function( $query ) {
    
    
    
function trimTitle( $title, $id = null ) {
 
         $title= str_replace("‘", '', $title);
      return summary($title,80);
 
}
add_filter( 'the_title', 'trimTitle', 10, 2 );


} );



} );
```

[custom-query-filter](https://developers.elementor.com/custom-query-filter/)

**Comment by maxcondor** [comment]
> if someone need:
> 
> ```
>  function summary($content, $limit = 200) {
>    $content = strip_tags($content);
>    // Take the existing content and return a subset of it
>    $end = '';
>    if (strlen($content) > $limit) {
>        $end = '...';
>    }
>    return substr($content, 0, $limit) . $end;
> } 
>    
> add_action( 'elementor_pro/posts/query/custom_query_ID', function( $query ) {
>    
>     function trimTitle( $title, $id = null ) {
>        return summary($title,80);
> }
> 
> add_filter( 'the_title', 'trimTitle', 10, 2 );
> 
> } );
> ```
> 
> [custom-query-filter](https://developers.elementor.com/custom-query-filter/)


I'm using your code.
On my home I have many post widgets, each with a different id query with a different trim. I uploaded the code using the "Snippet" widget but I noticed that all the titles are truncated following the last loaded snippet.
How can I specify in the code that the title trim should only be performed in a specific elementor widget?

Thanks for the attention!
