### ISSUE TITLE
Override nav menu widget

### ISSUE THREAD

**Issue by aksld** [pojome/elementor#5653]
Hi,

I'm trying to create new nav menu widget.
I took yours and it works well in the display.

But I have the impression that there is a problem with javascript because the dropdown does not work. As if the js was not loaded.

May I have to do something more ?

Here the code : https://pastebin.com/Vqjd2W63

Thanks for your help.

**Comment by bainternet** [comment]
@aksld 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

as for your issue, you are changing the widget name and our JS handler is not aware of it. you need to register the nav menu handler to your widget name. same as [here](https://github.com/pojome/elementor/issues/5533#issuecomment-416026739)
