### ISSUE TITLE
posts in a new tab

### ISSUE THREAD

**Issue by MaraRita** [pojome/elementor#5658]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
when I use post widget posts always open on top of my page

**Describe the solution you'd like**
can you please just add a feature "open post in a different tab" like you have with links mabe near "read more" settings
![image](https://user-images.githubusercontent.com/42947847/45001368-352f7e80-afd5-11e8-85fb-5f05c4a86870.png)

**Describe alternatives you've considered**
or wherever 

**Additional context**

**Comment by bainternet** [comment]
related #4440

**Comment by bainternet** [comment]
should be available with #4440 


thanks.
