### ISSUE TITLE
Posts widget issue with WPML

### ISSUE THREAD

**Issue by sushmak02** [pojome/elementor#5660]
## Description

I have added Posts widget on my page.  But when I translate the page to another language using WPML.
There is nothing at the front end of the translated page.

## Steps to reproduce

Add Posts widget on a new page.
Edit page and translate it to some language.
Open that translated page link.
Posts widget is not working.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Isolating the problem.
* System info.

Also, this should probably be directed at WPML.

thanks
