### ISSUE TITLE
Hide image background for mobiles option

### ISSUE THREAD

**Issue by itolimp** [pojome/elementor#5661]
Please add option to hide image background on mobile devices. Enabling it for desktop, disabling for mobiles if needed.. Very useful option in my opinion
In many cases I need color background on mobiles and picture background on desktops. 
Hope you will add it

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

I merged this issue with  #2355, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
