### ISSUE TITLE
The background image is not displayed in mobile/tablet if the elementor website is moved from dev to production server

### ISSUE THREAD

**Issue by ridua** [pojome/elementor#5663]
Steps to reproduce:

1. Create a website/webpage using elementor and set the background image using elementor
2. migrate the website from dev server to production server

issue: if you open the responsive page in mobile/tablet and website background image was set in desktop, the background image is not displayed

Root cause: in the css files that elementor creates, it adds a static url (with dev-host ip) for access the background-image something like http://localhost:8888/website/wp-upload/....

**Comment by ridua** [comment]
system config:



Elementor - 2.2.0 | By Elementor.com |  
-- | -- | --
Elementor Addon Elements - 1.1 | By WebTechStreet |  
Elementor Addons & Templates - Sizzify Lite - 1.2.5 | By ThemeIsle |  
Essential Addons for Elementor - 2.7.8 | By Codetic |  
Header Footer Elementor - 1.0.16 | By Brainstorm Force, Nikhil Chavan

**Comment by bainternet** [comment]
@ridua 

That's why we added the Replace URL and the Regenerate CSS tools [docs here](https://docs.elementor.com/article/330-tools) 

thanks.

**Comment by ridua** [comment]
big thumbs up!!!
