### ISSUE TITLE
[Feature Request] Enable shortcodes in Icon Box-Widget (Toolset)

### ISSUE THREAD

**Issue by MarioCipo** [pojome/elementor#5664]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Looks like no shortcode in title and description fields of icon box widget currently is supported. Would be nice if shortcodes would be supported to get more dynamic data.

Problem was: Want to use Toolset shortcodes like [wpv-post-taxonomy type="..."] because of missing dynamic field support for taxonomies.

**Comment by servitiumpl** [comment]
+1
Please better integration with the Toolset

More information:
https://toolset.com/2018/07/toolset-elementor-integration/#comment-357899
"The rest of the issues are “how Elementor team chose to implement it”. We also wanted to see a tighter integration, where Elementor respects the output options of different fields. Eventually, Elementor treats all fields as “text”, which limits the possibilities significantly. There’s also no integration between Elementor and Toolset’s taxonomy. This causes additional issues to clients."

**Comment by mathieuades** [comment]
If a developper has an idea to do a "dirty" workaround, I'd love to have a clue. I'm a developer myself, so I can apply a temporary patch if needed. 

That would help. And by the way, congrats for all the good job accomplished in elementor's plugin !

Thank you !

**Comment by scarydakis** [comment]
Try this:

`add_filter( 'elementor/widget/render_content', 'do_shortcode');`

**Comment by shilo-ey** [comment]
@MarioCipo 

Thanks for your feedback,

You can add shortcode using Dynamic > Shortcode and adding your shortcode.

If the output of your shortcode "breaks" (Elementor escapes self enclosed HTML tags) try adding this line to your theme's `function.php` file:
```PHP
add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );
```

**Comment by lioncatde** [comment]
+1 yes please!
