### ISSUE TITLE
Content Lock In #Feature Request

### ISSUE THREAD

**Issue by Gwellins** [pojome/elementor#5667]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

**Content Lock-In**
This is a feature request. If removing Elementor, Elementor isn't updated, or a client decides that they no longer want to use it, currently, there is no option to remove Elementor, but keep the pages as is. 

Thrive Themes does pretty well with this and describes the issue in detail [here](https://thrivethemes.com/content-preservation/). 

It would be an amazing feature, simply to put client's minds at rest, that if, for whatever reason, Elementor cannot be used any longer, there is an option to "Deactivate but Retain Content/Layout".

**Comment by arielk** [comment]
The content of Elementor is already locked in the page after the plugin is deactivated without any shortcodes.

Thanks
