### ISSUE TITLE
[Feature request] Transformations

### ISSUE THREAD

**Issue by kkeennaa** [pojome/elementor#5668]
First of all, thank you for all the amazing work!

It would be awesome to have transformations on items individually. Things like rotation, translation etc. You can see an example [here](http://demo.cantothemes.com/wp/glamour-pro/?glamour=edit&glmrmode=single), just click on an element and then transformation. Of course with responsive features :)

Thank you!

**Comment by bainternet** [comment]
@kkeennaa 

Thanks for the suggestion, We are thinking about it, not sure when and what will come out of it.
