### ISSUE TITLE
Query Posts using hierarchical parent > child relationship

### ISSUE THREAD

**Issue by srcek** [pojome/elementor#5669]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I think that it would be useful to extend Query for Posts widget with an option to create a query based on hierarchical parent > child relationship. Posts widget has an option to use Categories and Tags for posts but options for pages and CPTs are a bit limited. 

**Describe the solution you'd like**
I'd like an option to create query for pages parent > child relationship so I could display, for example, all the pages that are the children of specific parent.

**Describe alternatives you've considered**
I think that such query would be possible to build using Toolset. But it doesn't have widgets or any other easy way for creating styled output.

**Comment by bainternet** [comment]
@srcek 

thanks for the suggestion, sadly with the current query control is waaaay to complicated to implement this since not all post types are hierarchical.

But for now, you can use the [custom query filter](https://developers.elementor.com/custom-query-filter/) to achieve that very easily, eg:

```PHP
add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
	$parent_id = 11;
	$query->set( 'post_parent', $parent_id );
} );
```

thanks.
