### ISSUE TITLE
Backend editor 

### ISSUE THREAD

**Issue by axiomteck** [pojome/elementor#567]
it will be nice if elementor can let us customize the backend wordpress specificly for our custommers like if is a restaurant all the pages and post is all related about restaurant. and work just a very custom back end Thank you very powerfull "ELEMENTOR"

**Comment by arielk** [comment]
I am not sure I completely understand what you mean, but Elementor is first and foremost a page builder, a live plugin to help you design pages, posts and custom post types. It is not targeted towards backend design.
