### ISSUE TITLE
How get each post ID in custom query filter for posts widget and modify returned posts base on a condition

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5670]
is there any way to hide or show an element based on a condition?
I tried to add a condition field to widgets and check while rendering. but not worked

```

if ( !function_exists( 'condition_visible_elementor_controls' ) ) {
	add_action( 'elementor/element/before_section_end' , 'condition_visible_elementor_controls', 10, 3 );
	function condition_visible_elementor_controls( $element, $section_id, $args ) {
		

			$element->add_control(
				'visible_condition',
				[
					'label' => __( 'Condition', 'elementor' ),
					'type' => Elementor\Controls_Manager::TEXT,
					'default' => '',
					'prefix_class' => 'elementor-',
					
					
				]
			);

			
	
	}

}

        add_action( 'elementor/widget/render_content', function( $content, $widget ) {
          
   	$settings = $widget->get_settings();
         //   var_dump($settings);
           
   	if ( ! empty( $settings['condition'] ) ) {
            if(eval($settings['condition'])){
             return $content;
            }else{
                 return '';
            }
   		
        }else{
  return $content;
        }
  
}, 10, 2 );
```

also tried to get each post id in query and check the condition **(get_field('variable',$postID))** but just can get included page id, not each of posts id. how I can do this?

`add_action( 'elementor_pro/posts/query/testimonials_query',`

I simply want this:
_IF ACF FIELD CHECKBOX CHECKED FOR A POST, IN POSTS WIDGET SHOW THIS BUTTON, ELSE DONT SHOW_

**Comment by bainternet** [comment]
Currently, there is no way to do it.


I merged this issue with  #4246, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
