### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by jv-BB** [pojome/elementor#5674]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**
Video - here it would be fine to have some more options: 
1. for example to load additional file-formats like ogv or webm to the standard mp4-format for browsers which don't support it, 
2. the option to load a separate video-file with smaller dimensions and smaller filesize for mobile devices, 
3. the option to build playlists and very important, so when I start a video -> it plays and I start a second video on the page, the first one should stop. -> see the FV Player for WP!

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
