### ISSUE TITLE
Custom Animations

### ISSUE THREAD

**Issue by jv-BB** [pojome/elementor#5675]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**
Custom Animations: It would be a very helpfull feature, when I could also create my own animations whith Elementor. For example I have a button and I click on it, an infobox opens by sliding down or fading in or animates from off-canvas. Whith this option, you will give a lot of possibilities to the developer!

With these additional capabilities, this plugin in combination whith Wordpress has even the potential also to become a very, very good (rapid-)prototyping-tool. Better than invision, Adobe XD, ProtoPie, Webflow etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by wayheming** [comment]
+ 1 Need this feature
