### ISSUE TITLE
Background on empty Column

### ISSUE THREAD

**Issue by dax702** [pojome/elementor#568]
Maybe a bug - Added a PNG file image 
![usa-map](https://cloud.githubusercontent.com/assets/19275233/18533413/e205bd6c-7a9f-11e6-8c9c-cf189ab4d207.png)
to function as the background image for a column and it's not displaying, even after configuring the position, attachment, repeat and size settings.  For reference, I attached the PNG I'm trying to use. Note that I can insert that image as an image element in the column and it displays. But it won't display if I try to add it as a background image.

**Comment by arielk** [comment]
Very strange. I downloaded the image and it worked great for background.

Please try another image for the background for the column and check it.

**Comment by dax702** [comment]
I've discovered what the problem is, and it's probably still worth correcting because I think others will ask. The background image does not show up in the column until you add some other element like Text to the column.  As soon as I added text, I saw the background image appear in the column on both the live page and within Elementor.  So it's probably a good idea to make the background image show up as soon as it's added and not wait until after there is another element added to the column

**Comment by arielk** [comment]
You right, the column will not print anything on the page until you add some content into it. 

Maybe we should change it to avoid mistakes of users.

**Comment by wonderment** [comment]
> I've discovered what the problem is, and it's probably still worth correcting because I think others will ask. The background image does not show up in the column until you add some other element like Text to the column.

+1

This seems odd to have min-height available on the Row but not the Column as well. It's understandable why it wouldn't show by default given box model properties but the Column module itself doesn't output the CSS for the background image attached to it _at all_.

Because of this, adding a class name and adding a minimum height declaration is useless given the absence of the background rendering.

**Comment by bainternet** [comment]
Seems like there is no easy way around this.

I'm closing this for now and will try to tackle it in the future if we see a large demand for it.

**Comment by Brink67** [comment]
It's an easy work around by adding a text widget who's content is a space.

**Comment by Anaon** [comment]
Got this today, someone in my office lost an hour trying to understand what was happenning.

Any fix in the future ?

**Comment by assadnazar** [comment]
I dont know what elementor team is doing... When content is added, the wrap div gets another class "elementor-element-populated" which gets the background image css... If the column is empty, this class is not applied

**Comment by brucetm** [comment]
This is very strange.  Why would they close this pending "large demand"?  Why would anyone not expect, and desire, added content to render?  What would be the reason not to fix it?  How many hours are collectively lost because of this bug?  Who could be expected to know to add a dummy element?

**Comment by Anaon** [comment]
@brucetm it's not the first time an issue is closed and they stop answering, event if they said it's fixed and we show them wrong.

That's sad

**Comment by yudayuda** [comment]
Guess I'll add myself to "increase the demand".

Having a bg image on empty columns is a common practice, don't understand why they think otherwise.

**Comment by kate-ann** [comment]
You can add a Spaced element and the background will show up. Though I agree, columns would benefit from adding a min-height property, giving them a full rich editing capability.
