### ISSUE TITLE
Custom Locations still showing as unsupported  - please re-open #5566

### ISSUE THREAD

**Issue by willcitizen** [pojome/elementor#5683]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

@bainternet  please refer to our previous discussion in #5566 and re-open this as a bug.
The issue persists exactly as described there in the latest release and I have provided screenshots of the experience a system dump and my function code which is I can guarantee you working as expected.

My custom locations are very definitely correctly registered as I use a combination of shortcodes and global widgets to output them within various core location templates and this is all working. However the problem with the locations being flagged as unsupported in the library list and not showing up for use in the new template modal when you choose a template type of section persists.

I am nearing the end of my current project and unfortunately do not have time to step through your code myself and try and isolate the cause of the issue, but this worked I estimate prior to release 2.1.5 and therefore you must have made changes in this area, because I did not.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by willcitizen** [comment]
This issue persists in the latest release - could I get an update, or some feedback as to how I might proceed in identifying the source of the problem myself.

**Comment by bainternet** [comment]
@willcitizen 

Like I said,

> Unsupported is shown once a template is set to a location that is not registered anymore.

and

> We can't really see from your code the location settings for each of the custom location which makes it impossible to replicate or debug. So I can only suggest you look in that area.

I can only add that you should check the load/include sequance of your custom code to make sure it run on time.

but other then that it would be gussing.

**Comment by willcitizen** [comment]
@bainternet 

Thanks for all of your hard work investigating the issue.  

I'm afraid that this and many other examples I see here of terrible customer engagement and an unwillingness to acknowledge issues raised by multiple users have all contributed to my decision to cut my losses on investing in elementor and complimentary plugins and move to a platform where customer engagement is understood and practiced
