### ISSUE TITLE
Errors (Elementor System Info)

### ISSUE THREAD

**Issue by michelleist** [pojome/elementor#5684]
Can anyone help to explain what all these errors here mean on my site?
How to fix this?

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 5.6.39
	PHP Version: 7.1.21
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.cocoonstyling.ch
	Home URL: https://www.cocoonstyling.ch
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Zurich
	Debug Mode: Inactive

== Theme ==
	Name: Cocoon Styling
	Version: 1.0.0
	Author: Cocoon Styling
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.4.10
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Astra Pro
		Version: 1.5.2
		Author: Brainstorm Force

	Classic Editor
		Version: 0.4
		Author: WordPress Contributors

	Custom Icons for Elementor
		Version: 0.1.2
		Author: Michael Bourne

	Duplicate Page
		Version: 2.7
		Author: mndpsingh287

	Elementor
		Version: 2.2.1
		Author: Elementor.com

	Elementor Extras
		Version: 1.9.14
		Author: Namogo

	Elementor Pro
		Version: 2.1.7
		Author: Elementor.com

	Element Pack
		Version: 2.5.3
		Author: BdThemes

	Enable Media Replace
		Version: 3.2.7
		Author: ShortPixel

	Essential Addons for Elementor - Pro
		Version: 2.11.0
		Author: Codetic

	Imagify
		Version: 1.8.1.1
		Author: WP Media

	ManageWP - Worker
		Version: 4.6.2
		Author: ManageWP

	Nest by Bonfire
		Version: 2.0
		Author: Bonfire Themes

	NinjaFirewall (WP Edition)
		Version: 3.7
		Author: The Ninja Technologies Network

	NinjaScanner
		Version: 1.2.4
		Author: The Ninja Technologies Network

	PowerPack Elements
		Version: 1.3.5.1
		Author: Team IdeaBox - PowerPack Elements

	Really Simple SSL
		Version: 3.0.5
		Author: Rogier Lankhorst, Mark Wolters

	Text Selection Color
		Version: 1.6
		Author: Nazmur Rahman

	Ultimate Addons for Elementor
		Version: 1.6.0
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 2.14.8.24
		Author: UpdraftPlus.Com, DavidAnderson

	White Label Branding for Elementor
		Version: 1.0.3
		Author: IdeaBox Creations

	WP Meta SEO
		Version: 3.7.6
		Author: JoomUnited

	WP Real Media Library
		Version: 4.0.6
		Author: Matthias Günter

	WPS Hide Login
		Version: 1.4.3
		Author: WPServeur, NicolasKulka, tabrisrp

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

== Debug ==
	Errors: 
		TypeError: Cannot read property 'statusText' of undefined
			at https://www.cocoonstyling.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:230018
			2018-09-06 07:40 +00:00
			x 5 times

		TypeError: Cannot read property 'add' of null
			at https://www.cocoonstyling.ch/wp-content/plugins/elementor/assets/lib/slick/slick.min.js?ver=1.8.1 - 1:19335
			2018-09-05 10:08 +00:00

		ReferenceError: heading is not defined
			at https://www.cocoonstyling.ch/wp-admin/post.php?post=2163&action=elementor - 6:9
			2018-09-05 10:05 +00:00
			x 7 times

		TypeError: Cannot read property 'statusText' of undefined
			at https://www.cocoonstyling.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:230018
			2018-09-04 09:10 +00:00

		TypeError: Cannot read property 'currentView' of undefined
			at https://www.cocoonstyling.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:239133
			2018-09-04 09:08 +00:00
			x 2 times

		TypeError: undefined is not an object (evaluating 'n.statusText')
			at https://www.cocoonstyling.ch/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:230017
			2018-09-03 19:58 +00:00

		TypeError: Cannot read property 'add' of null
			at https://www.cocoonstyling.ch/wp-content/plugins/elementor/assets/lib/slick/slick.min.js - 1:19335
			2018-09-03 07:31 +00:00

		TypeError: Cannot read property 'add' of null
			at http://xyobqnxmg.cyon.link/wp-content/plugins/elementor/assets/lib/slick/slick.min.js?ver=1.8.1 - 1:19335
			2018-08-27 12:29 +00:00

		TypeError: Cannot read property 'on' of null
			at http://xyobqnxmg.cyon.link/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.8 - 2:82961
			2018-08-27 12:21 +00:00

		TypeError: Cannot read property 'style' of undefined
			at http://xyobqnxmg.cyon.link/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-08-27 12:21 +00:00

**Comment by SMakgare** [comment]
Hi there,

I'm getting the same problem. I've tried everything, even contacted Elementor for assistance but everything I try keeps that error there:

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 5.6.37
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://acolourfulmind.com
	Home URL: https://acolourfulmind.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-ZA
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.5.27
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_ZA
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.0.8
		Author: Automattic

	All In One WP Security
		Version: 4.3.6
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Elementor
		Version: 2.2.1
		Author: Elementor.com

	Jetpack by WordPress.com
		Version: 6.5
		Author: Automattic

	Maintenance
		Version: 3.6.1
		Author: fruitfulcode

	Ocean Extra
		Version: 1.4.26
		Author: OceanWP

	Really Simple SSL
		Version: 3.0.5
		Author: Rogier Lankhorst, Mark Wolters

	Redirection
		Version: 3.4.1
		Author: John Godley

	WPForms Lite
		Version: 1.4.8.1
		Author: WPForms

	WP Super Cache
		Version: 1.6.4
		Author: Automattic

	Yoast SEO
		Version: 8.2
		Author: Team Yoast


== Must-Use Plugins ==
	SSO
		Version: 0.3
		Author: Garth Mortensen, Mike Hansen


== Debug ==
	Errors: 
		TypeError: n is undefined
			at https://acolourfulmind.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:229998
			2018-09-08 04:36 +00:00
			x 3 times

Can someone please assist. I can't continue with my project, it's been almost a week now. 	

It seems the only time I receive the error is when I use my OceanWP Child Theme. Every other theme and it's child works. 	

Help would be highly appreciated.

Thanks

**Comment by bainternet** [comment]
@michelleist 

Elementor logs errors or "small" fails so when you have an actual issue we can get a better understanding of what it is.

But it's not something you should look to fix.

@SMakgare 
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

thanks.

**Comment by edsmskinner** [comment]
Not helpful
