### ISSUE TITLE
Related Posts query by CATEGORY

### ISSUE THREAD

**Issue by MarcDethmers** [pojome/elementor#5687]
Hi all (replied on a similar thread and started this new thread)

What I want is, similar to the code provided by Elementor for displaying related posts by TAG (below, and works for TAGS), as giving on their site, the query code for displaying related posts by CATEGORY;

So, if the single post has a category, the related posts element (and query) at the bottom showing related post with that same category. I do not know what will happen if the single post in question has more then 1 category, which also occurs for some posts???

Code provided by elementor for TAGS (which works!)

// Showing related posts by tag in Posts Widget
add_action( 'elementor_pro/posts/query/Related-Posts', function( $query ) {
// Here we set the query to fetch posts with
// the same tags as the current post

// Get current post tags
$tags = wp_get_post_terms( get_queried_object_id(), 'post_tag', [ 'fields' => 'ids' ] );

// Get current tax_query
$tax_query = $query->get( 'tax_query' );

// Add our tax query
$tax_query[] = [
'taxonomy' => 'post_tag',
'terms' => $tags,
];

// Modify the query
$query->set( 'tax_query', $tax_query );

// Make sure we don't get current post
$not_in = $query->get( 'post__not_in' );
$not_in[] = get_queried_object_id();

// Modify the query
$query->set( 'post__not_in', $not_in );
} );

Anyone?

Thx.

Marc

**Comment by bainternet** [comment]
@MarcDethmers 

Simply change every occurrence of 'post_tag' to category:

```PHP
add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
	// Here we set the query to fetch posts with
	// the same categories as the current post

	// Get current post categories
	$tags = wp_get_post_terms( get_queried_object_id(), 'category', [ 'fields' => 'ids' ] );

	// Get current tax_query
	$tax_query = $query->get( 'tax_query' );

	// Add our tax query
	$tax_query[] = [
		'taxonomy' => 'category',
		'terms' => $tags,
	];

	// Modify the query
	$query->set( 'tax_query', $tax_query );

	// Make sure we don't get current post
	$not_in = $query->get( 'post__not_in' );
	$not_in[] = get_queried_object_id();

	// Modify the query
	$query->set( 'post__not_in', $not_in );
} );
```

**Comment by MarcDethmers** [comment]
Hi Raz,

 

This code works like a charm. Thank you very much for helping me out!

I know my request may be outside the scope of support, so again thanks!

 

Elementor rocks!

 

Marc Dethmers

 

Van: Raz Ohad <notifications@github.com> 
Verzonden: woensdag 12 september 2018 15:03
Aan: pojome/elementor <elementor@noreply.github.com>
CC: MarcDethmers <info@hetveenhuus.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [pojome/elementor] Related Posts query by CATEGORY (#5687)

 

@MarcDethmers <https://github.com/MarcDethmers> 

Simply change every occurrence of 'post_tag' to category:

add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
        // Here we set the query to fetch posts with
        // the same categories as the current post
 
        // Get current post categories
        $tags = wp_get_post_terms( get_queried_object_id(), 'category', [ 'fields' => 'ids' ] );
 
        // Get current tax_query
        $tax_query = $query->get( 'tax_query' );
 
        // Add our tax query
        $tax_query[] = [
               'taxonomy' => 'category',
               'terms' => $tags,
        ];
 
        // Modify the query
        $query->set( 'tax_query', $tax_query );
 
        // Make sure we don't get current post
        $not_in = $query->get( 'post__not_in' );
        $not_in[] = get_queried_object_id();
 
        // Modify the query
        $query->set( 'post__not_in', $not_in );
} );

**Comment by unimini** [comment]
Where should I enter the code above?
