### ISSUE TITLE
Name of Global widget in navigator

### ISSUE THREAD

**Issue by ajlcomputers** [pojome/elementor#5689]
**What problem is your feature request going to solve? Please describe.**
I use a number of different global widgets to insert adverts into my pages and I can't tell which ones which without seeing the name of the global widget. This means I currently have to delete the widget and add it back in, even if it was the correct one as I have no way of knowing if it's the correct one currently in place.

**Describe the solution you'd like**
Insert the name of the global widget into the navigator or somewhere in the elementor sidebar when editing / right clicking on the widget so that it can be identified.

**Describe alternatives you've considered**
I am currently having to use a shortcode plugin to insert the adverts as then I can see the name of the shortcode in the elementor editor.

**Comment by arielk** [comment]
Fixed in Pro v2.1.9

Thanks
