### ISSUE TITLE
Reload options panel or whole widget via JS method?

### ISSUE THREAD

**Issue by greynor** [pojome/elementor#569]
Hi there,

I've created a custom widget having 2 select inputs in the admin panel on the left side for customizing the content of the widget.
The second select's content depends on the first one's selection.

I want to refresh the options panel after selecting an option in the first select input.
Is there a method that I can call to refresh the widget after changing the first option?

The workaround currently is to change the first select box, select another widget in the content area, re-select the one I want to edit. Then the second select box' content is updated with new options. That's not that comfortable.

Thank you for the awesome work you've put in Elementor.

Robin

**Comment by arielk** [comment]
Sorry, but right now you can't do something like this with the panel.

We're currently working on the API for the plugin, I think it will give you a solution for it.

**Comment by greynor** [comment]
allright, thank you for the info

**Comment by joshmarom** [comment]
I know it's an old one, but still thought I could maybe help... 
Maybe you could create a set of "second" select boxes.
Then you can show each one depending on a condition based on the first box.

**Comment by bainternet** [comment]
No need to reload,

like @joshmarom said to create multiple selected with a show condition and they will only be visible based on the other selection, ex here https://github.com/pojome/elementor/issues/2757#issuecomment-344536372
