### ISSUE TITLE
Add the parent widget pack name to the advanced tab for identification purposes

### ISSUE THREAD

**Issue by Perchpole** [pojome/elementor#5690]
If you have several widget plugin packs installed it's becoming impossible to distinguish individual widgets. Each pack might include the same type of widget or use a similar name. There are, for example, lots of "Slider" widgets. When you edit the slider, however, you have no way of knowing which parent pack the widget belongs to. This situation is needlessly confusing.

Suggestion: Add the parent widget pack name to the advanced tab for identification purposes. That way, users will know which pack the selected widget belongs to.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
