### ISSUE TITLE
Copy doesn't bring id, class name in advance tab

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#5691]
Copy, duplicate don't bring id, class name in advance tab

It used to bring id, class names in advance tab when we duplicate, copy, paste or get templates.
But it's not copying id, class names at this moment. 

Can you please check it out?

1 more question, Elementor works with the_content(). 
Is there any way to have 1 more the_content()? We create a textarea ( by ACF or custom field..etc) and use Element on front end. I know it sounds not common. But we need 1 more place ( content area ) to use Elementor. 

Thank you!

**Comment by bainternet** [comment]
@pulla 

We removed the ID property from copy/paste because it would create multiple elements with the same ID which is simply invalid markup.

As for,
>Is there any way to have 1 more the_content()? We create a textarea ( by ACF or custom field..etc) and use Element on front end. I know it sounds not common. But we need 1 more place ( content area ) to use Elementor.

nope, not without some major custom coding.

thanks.

**Comment by bkjproductions** [comment]
You should notify the user when the paste occurs... if you had an ID or class. Also when pasting from page to page there would be no conflict, in all likelihood, so why not keep it then?

Otherwise it seems like a bug..  :)

**Comment by betterdesign** [comment]
> You should notify the user when the paste occurs... if you had an ID or class. Also when pasting from page to page there would be no conflict, in all likelihood, so why not keep it then?
> 
> Otherwise it seems like a bug.. :)

This is a good idea. Shouldn't be too hard to code either.
