### ISSUE TITLE
CSS Classes added to wrong element

### ISSUE THREAD

**Issue by trainbolt** [pojome/elementor#5693]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When you add an element like a Heading or Button to your page and need to add a specific class it appears you can do so by going to the Advanced tab and enter the classes in the CSS Classes input box. However, the classes get added to a wrapper that is sometimes far away up the chain from the actual element. See example below.

## Steps to reproduce

1. Add Heading, Button or other single element to the page. 
2. Click to edit new element.
3. Go to Advanced tab.
4. Enter class in the CSS Classes input.
5. Save.
6. Load page in new tab.
7. Inspect element (H1-6, Button etc.)
8. Class does not exist on the correct element, it is applied to a wrapper sometimes 2, 3, 4 elements up the chain.

**Example: Add class 'text-pop-up-top' to Heading h1**

**Result**
```html
<div class="elementor-column-wrap elementor-element-populated">
  <div class="elementor-background-overlay"></div>
  <div class="elementor-widget-wrap">

    <!-- AS YOU CAN SEE IT'S ADDED TO THIS DIV  -->

    <div data-id="aeabe99" data-element_type="heading.default" data-model-cid="c92" id="" class="elementor-element elementor-element-edit-mode elementor-element-aeabe99 elementor-element--toggle-edit-tools elementor-widget elementor-widget-heading elementor-element-editable text-pop-up-top">
      <div class="elementor-element-overlay">
        <ul class="elementor-editor-element-settings elementor-editor-widget-settings">
          <li class="elementor-editor-element-setting elementor-editor-element-edit" title="Edit">
            <i class="eicon-edit" aria-hidden="true"></i>
            <span class="elementor-screen-only">Edit</span>
          </li>
        </ul>
      </div>
      <div class="elementor-widget-container">
        <h1 data-elementor-setting-key="title" class="elementor-heading-title elementor-size-default elementor-inline-editing">Truly painless e-commerce is <br>just around the corner.​</h1>
      </div>
    </div>
  </div>
</div>
```

**Intended Result**
...
```html
<h1 data-elementor-setting-key="title" class="elementor-heading-title elementor-size-default elementor-inline-editing text-pop-up-top">Truly painless e-commerce is <br>just around the corner.​</h1>
```
...

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: 8.0.12
	PHP Version: 7.1.21
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://www.getfreeway.com
	Home URL: http://www.getfreeway.com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.7
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

== Active Plugins ==
	Elementor
		Version: 2.2.0
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.6
		Author: Elementor.com


== Debug ==
	Errors: 
		TypeError: setting getter-only property "type"
			at http://www.getfreeway.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.0 - 2:84996
			2018-09-07 00:23 +00:00
			x 12 times

				
```
</details>

**Comment by bainternet** [comment]
@trainbolt 

This is how it works, the CSS classes and ID are added to the widget's top main HTML tag.

We do have [something planned](https://github.com/pojome/elementor/pull/4030) to allow more control over parts of the element.

thanks.
