### ISSUE TITLE
elementor not working with chorme Version 69.0.3497.81 (Official Build) (32-bit)

### ISSUE THREAD

**Issue by Ersonusaini** [pojome/elementor#5696]
elementor element not working with chorme Version 69.0.3497.81 (Official Build) (32-bit).

example : media gallery not proper working 

Please fix issues as soon

thanks 

ersonusaini

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
