### ISSUE TITLE
Text settings in Image box widget

### ISSUE THREAD

**Issue by smokingbehind** [pojome/elementor#5697]
Hi,

In Image box widget, if you choose ACF(custom field) for description, then settings for description font will not work.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
