### ISSUE TITLE
Can't access video settings after a video is added

### ISSUE THREAD

**Issue by budda** [pojome/elementor#5698]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

After adding a video - youtube in my case - i am unable to access the setting again as Youtube has taken over the click and right mouse click events for itself. 

## Steps to reproduce

Insert a video. add a youtube url. try sand edit it.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Integrated with Drupal CMS using the https://www.drupal.org/project/elementor project.
</details>

**Comment by bainternet** [comment]
@budda 

That's because the right click is caught by the video frame and not Elementor, its the expected behavior.

You need to hover over the widget/video and right-click on the edit handle (the little pencil) or you can use the Navigator.

thanks.

**Comment by budda** [comment]
You cannot see the pencil icon. As you correctly pointed out - the video covers everything and eats clicks for itself.
