### ISSUE TITLE
Alerts: Rich Text Editing

### ISSUE THREAD

**Issue by pb52** [pojome/elementor#5699]
Can we please have the ability to add a user defined icon to the Alert boxes?  I like the option to add a font awesome icon for info, success, warning danger.  The colour of the icon should match the attributes of the Title of the alert box

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
