### ISSUE TITLE
White Page Problem

### ISSUE THREAD

**Issue by ShaoboZhangProduction** [pojome/elementor#5700]
Situation: 
My Elementor is really unstable after 2.2.1 update. It's been one week now. At the beginning, it was server storage problem. I cleared some backups in my Disk Storage. Then, the Elementor works again. (Redirection is also activated). However, one day later, the Elementor is not working again. Today I deactivate Redirection, the page back to normal. 

Troubleshooting:
- Updated the Elementor and Redirection to the Latest Version
- Enabled Switch Editor Loader Method
- Deactivated Every plugins and reactivated them (Found Only Redirection has problem with it)

The problem: 
- Is Redirection's problem? 
- Any other possibilities? (Because Redirection was working with Elementor before the update)

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: 5.6.40
	PHP Version: 5.6.37
	PHP Max Input Vars: 1000
	PHP Max Post Size: 4M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://mahbobaspromise.org/afghanistan
	Home URL: https://mahbobaspromise.org
	WP Multisite: No
	Max Upload Size: 4 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: 10
	Debug Mode: Inactive

== Theme ==
	Name: Philanthropy Child
	Version: 2.0
	Author: ThemeFuse
	Child Theme: Yes
	Parent Theme Name: Philanthropy Parent
	Parent Theme Version: 2.0.7
	Parent Theme Author: ThemeFuse

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.0.8
		Author: Automattic

	Contact Form 7
		Version: 5.0.3
		Author: Takayuki Miyoshi

	Disable WooCommerce Reviews
		Version: 1.1
		Author: pipdig

	Elementor
		Version: 2.2.1
		Author: Elementor.com

	Give - Donation Plugin
		Version: 2.2.3
		Author: WordImpress

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	iThemes Security
		Version: 7.1.0
		Author: iThemes

	Less & scss PHP Compilers
		Version: 2.0.1
		Author: Aristeides Stathopoulos

	MailChimp for WordPress
		Version: 4.2.4
		Author: ibericode

	Media from FTP
		Version: 9.61
		Author: Katsushi Kawamori

	Pixel Cat Lite
		Version: 2.2.0
		Author: Fatcat Apps

	Press Elements - Widgets for Elementor
		Version: 1.7.2
		Author: Press Elements

	Really Simple SSL
		Version: 3.0.5
		Author: Rogier Lankhorst, Mark Wolters

	Regenerate Thumbnails
		Version: 2.2.6
		Author: Alex Mills (Viper007Bond)

	Simple Custom CSS
		Version: 4.0.1
		Author: John Regan, Danny Van Kooten

	Simple Social Icons
		Version: 2.0.1
		Author: Nathan Rice

	Smart Slider 3
		Version: 3.3.7
		Author: Nextend

	Unyson
		Version: 2.7.19
		Author: ThemeFuse

	UpdraftPlus - Backup/Restore
		Version: 1.14.13
		Author: UpdraftPlus.Com, DavidAnderson

	W3 Total Cache
		Version: 0.9.7
		Author: Frederick Townes

	WooCommerce
		Version: 3.4.5
		Author: Automattic

	WP Maintenance Mode
		Version: 2.2.1
		Author: Designmodo

	WP Progress Bar
		Version: 1.0.0
		Author: Alobaidi

	Yoast SEO
		Version: 8.1.2
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property 'ui' of undefined
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.0 - 2:217067
			2018-09-03 02:30 +00:00

		TypeError: Cannot read property 'query' of null
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1 - 1:60824
			2018-09-03 01:47 +00:00
			x 2 times

		TypeError: Cannot read property 'html' of undefined
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.0 - 2:178830
			2018-09-03 01:22 +00:00
			x 3 times

		TypeError: Cannot read property 'html' of undefined
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:80110
			2018-08-21 03:04 +00:00
			x 2 times

		TypeError: Cannot read property 'attributes' of undefined
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.1.4 - 2:7460
			2018-08-06 03:07 +00:00

		TypeError: Cannot read property 'html' of undefined
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.4 - 2:80103
			2018-08-06 01:49 +00:00
			x 2 times

		TypeError: Cannot read property 'errors' of undefined
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.4 - 2:138622
			2018-08-06 01:32 +00:00
			x 9 times

		TypeError: Cannot read property 'html' of undefined
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.4 - 2:80103
			2018-07-30 04:44 +00:00

		TypeError: Cannot read property 'on' of null
			at https://mahbobaspromise.org/afghanistan/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.4 - 2:82954
			2018-07-30 01:34 +00:00

		TypeError: Cannot read property 'canvas' of undefined
			at https://mahbobaspromise.org/afghanistan/wp-admin/load-scripts.php?c=0&load%5B%5D=editor,quicktags,wp-a11y,wplink,jquery-ui-menu,jquery-ui-autocomplete,thickbox,media-upload,wp-embed&ver=4.7.11 - 2:7714
			2018-07-30 01:34 +00:00

**Comment by ShaoboZhangProduction** [comment]
Sorry, one more thing. The debug errors only recorded the problem occurred before I fixe the Server Storage Problem. There are no error detected after I fixed Server Storage Problem.

**Comment by SMakgare** [comment]
I've got the exact same problem. 

Could it be the child theme perhaps?

**Comment by bainternet** [comment]
@ShaoboZhangProduction 

We can't replicate. 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by IPhk** [comment]
Same issue problem

**Comment by ShaoboZhangProduction** [comment]
No idea what happened? What theme are you using?

**Comment by ShaoboZhangProduction** [comment]
No idea what happened. I deactivated my redirection. What theme are you using?
