### ISSUE TITLE
Rename Navigator Section / Item

### ISSUE THREAD

**Issue by pb52** [pojome/elementor#5701]
Throughout the computing world double-click means "execute" and right click means "display context menu"

Navigator uses the latter but the context menu does not include the "rename" option.  For that you have to use double-click.

This is counter-intuitive.  Please could you add "rename" to the context men

**Comment by bainternet** [comment]
Throughout the design world (ex: photoshop), double-click is used to name/rename an element, actually the same in the computing world (most of it).



But thanks, we're thinking about it.

**Comment by feidaman** [comment]
> FWIW, "rename"'s absence from the context menu led me to believe it was not possible to rename sections. I discovered the double-click method by reading this issue.

This. I just double-clicked a section by chance and that's how I learned they could  be renamed. The absence of "rename" in the context menu also led me to believe it was just not possible.

**Comment by simonv74** [comment]
It's taken me ages to work this out, glad I found this thread! It's really odd that it's not an option in the right click menu.
