### ISSUE TITLE
Text in Testimonial carousel appearing blurry

### ISSUE THREAD

**Issue by heenaab** [pojome/elementor#5702]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by heenaab** [comment]
Hi,
There seems to be an issue with the testimonial carousel widget, all text is appearing blurry on my site (pic '1'). I tried using a ready block from elementor library to redo the slider, but the issue seems to be there on that one as well (pic '2'). Is this a bug or something? I have downloaded the latest version of elementor but this has been going on for a while now. 

Your help would be appreciated, thank you.

![1](https://user-images.githubusercontent.com/42366682/45284708-cf745280-b4fe-11e8-8d88-1e4799ed461e.png)
![2](https://user-images.githubusercontent.com/42366682/45284709-cf745280-b4fe-11e8-92a1-a9c79cc29d02.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

but mostly missing a link to actually see it.
