### ISSUE TITLE
Style -> Image -> Spacing for Archive Posts and Posts widgets

### ISSUE THREAD

**Issue by srcek** [pojome/elementor#5703]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

20px bottom margin is consistently added to elementor-post__thumbnail__link class for Archive Posts and Posts Widgets. I can't determine where's the control for that margin. It appeared after I updated some of my staging/test sites. 

## Steps to reproduce

I tried setting Style -> Image -> Spacing for Archive Posts and Posts widgets to zero but the margin remains. Any other number gets added to that margin.

Is that new behaviour intended? I'd like to know before I start updating production sites.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@srcek 

This is depended on the skin you use but it is actually dynamically calculated based on the avatar size:
```PHP
'{{WRAPPER}} .elementor-post__thumbnail__link' => 'margin-bottom: calc({{SIZE}}{{UNIT}} / 2)',
```

or based on the image spacing in the base skin:
```PHP
'{{WRAPPER}}.elementor-posts--thumbnail-top .elementor-post__thumbnail__link' => 'margin-bottom: {{SIZE}}{{UNIT}}',
```

thanks

**Comment by srcek** [comment]
@bainternet I forgot to mention that behavior I encountered is present only if Cards Skin is selected.
