### ISSUE TITLE
I can't edit global Widgets, the page freezes on load.

### ISSUE THREAD

**Issue by smalonso** [pojome/elementor#5705]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
We can't edit any Global Widget created when we click the link Edit with Elementor the screen are freeze. But we can edit another type of Template. 

When we check the browser console errors, it shows an error related with editor.js 

```
editor.js?ver=2.2.1:3998 Uncaught TypeError: Cannot read property '0' of null
    at n.addChildElement (editor.js?ver=2.2.1:3998)
    at n._checkIsEmpty (editor.js?ver=2.2.1:4253)
    at n.initialize (editor.js?ver=2.2.1:4155)
    at n.e.View (backbone.min.js?ver=1.2.3:1)
    at n.constructor (backbone.marionette.js?ver=2.4.5:1693)
    at n.constructor (backbone.marionette.js?ver=2.4.5:2174)
    at n.constructor (backbone.marionette.js?ver=2.4.5:2879)
    at n [as constructor] (backbone.min.js?ver=1.2.3:1)
    at n [as constructor] (backbone.min.js?ver=1.2.3:1)
    at new n (backbone.min.js?ver=1.2.3:1)
addChildElement @ editor.js?ver=2.2.1:3998
_checkIsEmpty @ editor.js?ver=2.2.1:4253
initialize @ editor.js?ver=2.2.1:4155
e.View @ backbone.min.js?ver=1.2.3:1
constructor @ backbone.marionette.js?ver=2.4.5:1693
constructor @ backbone.marionette.js?ver=2.4.5:2174
constructor @ backbone.marionette.js?ver=2.4.5:2879
n @ backbone.min.js?ver=1.2.3:1
n @ backbone.min.js?ver=1.2.3:1
n @ backbone.min.js?ver=1.2.3:1
buildChildView @ backbone.marionette.js?ver=2.4.5:2669
addChild @ backbone.marionette.js?ver=2.4.5:2579
(anonymous) @ backbone.marionette.js?ver=2.4.5:2418
(anonymous) @ underscore.min.js?ver=1.8.3:5
m.each.m.forEach @ underscore.min.js?ver=1.8.3:5
showCollection @ backbone.marionette.js?ver=2.4.5:2416
_renderChildren @ backbone.marionette.js?ver=2.4.5:2399
_renderChildren @ backbone.marionette.js?ver=2.4.5:2943
render @ backbone.marionette.js?ver=2.4.5:2933
_renderView @ backbone.marionette.js?ver=2.4.5:1220
show @ backbone.marionette.js?ver=2.4.5:1150
onPreviewLoaded @ editor.js?ver=2.2.1:7061
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3

```

## Steps to reproduce
We go to Elementor > My Templates and we click edit with Elementor in a Global Widget item previously created.
Aditionally we tested the same steps with a new Global Widget object and doesn't work.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.7.23
	PHP Version: 7.2.9
	PHP Max Input Vars: 5000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://englishmontessorischool.com.dedi1162.your-server.de
	Home URL: http://englishmontessorischool.com.dedi1162.your-server.de
	WP Multisite: Yes
	Max Upload Size: 20 MB
	Memory limit: 20MB
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: The English Montessori School Theme
	Version: 1.0.0
	Author: Season
	Child Theme: Yes
	Parent Theme Name: Cognita Schools Spain Theme
	Parent Theme Version: 1.0.0
	Parent Theme Author: Season

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Network Plugins ==
	Cognita News Import
		Version: 1.0.0
		Author: Season

	Cookie Notice
		Version: 1.2.44
		Author: dFactory

	Elementor
		Version: 2.2.1
		Author: Elementor.com

	Elementor Extras
		Version: 1.9.14
		Author: Namogo

	Elementor Google Map Extended
		Version: 1.1.0
		Author: InternetCSS

	Elementor Pro
		Version: 2.1.7
		Author: Elementor.com

	Gravity Forms
		Version: 2.3.3.6
		Author: rocketgenius

	Gravity Forms Multilingual
		Version: 1.3.17
		Author: OnTheGoSystems

	myStickymenu
		Version: 2.0.5
		Author: m.r.d.a

	Regenerate Thumbnails
		Version: 3.0.2
		Author: Alex Mills (Viper007Bond)

	reSmush.it Image Optimizer
		Version: 0.1.16
		Author: reSmush.it

	UberMenu 3 - The Ultimate WordPress Mega Menu
		Version: 3.4.1.1
		Author: Chris Mavricos, SevenSpark

	W3 Total Cache
		Version: 0.9.7
		Author: Frederick Townes

	WP All Import Pro
		Version: 4.5.4
		Author: Soflyy

	WPML All Import
		Version: 2.0.7
		Author: OnTheGoSystems

	WPML CMS Nav
		Version: 1.4.23
		Author: OnTheGoSystems

	WPML Media
		Version: 2.3.6
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.0.6
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.4.4
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.8.6
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.6.6
		Author: OnTheGoSystems

	Yoast SEO
		Version: 8.1.2
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property '0' of null
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.2.1 - 3998:23
			2018-09-10 10:59 +00:00
			x 10 times

		TypeError: childTypes is null
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.2.1 - 3998:5
			2018-09-10 10:27 +00:00

		TypeError: Cannot read property '0' of null
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.2.1 - 3998:23
			2018-09-10 10:27 +00:00
			x 4 times

		TypeError: Cannot read property 'select2' of undefined
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.7 - 4768:18
			2018-09-06 17:03 +00:00

		TypeError: Cannot read property 'add' of null
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/lib/slick/slick.js?ver=1.8.1 - 1307:13
			2018-08-22 09:56 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.7 - 8625:36
			2018-08-19 18:18 +00:00
			x 26 times

		TypeError: Cannot read property 'currentView' of undefined
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.6 - 9683:15
			2018-08-10 15:11 +00:00
			x 4 times

		TypeError: Cannot read property 'forEach' of undefined
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.6 - 13385:17
			2018-08-06 16:34 +00:00
			x 3 times

		TypeError: Cannot read property 'currentView' of undefined
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.6 - 9683:15
			2018-08-06 16:34 +00:00
			x 8 times

		TypeError: Cannot read property 'forEach' of undefined
			at http://englishmontessorischool.com.dedi1162.your-server.de/wp-content/plugins/elementor/assets/js/editor.js?ver=2.1.6 - 13385:17
			2018-08-06 15:50 +00:00
			x 4 times

</details>

**Comment by bainternet** [comment]
We can't replicate this issue,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
