### ISSUE TITLE
Responsive layout not works for tablet (elementor pro)

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5706]
Elementor pro responsive mode  breaks in tablet mode.
I just set values for column width, not changes in view (realtime) but works in frontend. its  ok for mobile and desktop.

any idea why? and How I can fix it?

![image](https://user-images.githubusercontent.com/2544046/45295392-3433ab00-b507-11e8-954b-36c4c3239de6.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
