### ISSUE TITLE
Bug related to nav menu hamburger on mobile

### ISSUE THREAD

**Issue by shimonshomron** [pojome/elementor#5711]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description
nav menu widget on mobile display - the first tap the hamburger jumps the page to a random upper place on the page. This is noticeable especially on sticky header situations (when I have scrolled the page and yet have the menu on top). It happens on mobile (on agent level) and only once after page load. 
After the first occurrence it behaves nicely.

The function causing this to happen is:

jQuery(".elementor-nav-menu__container.elementor-nav-menu--dropdown").animate( {height:"show"})

when I run it on console after page loaded it reproduces the bug (once per page load)

## Steps to reproduce
add nav menu widget that is not on top of the page (you can add it to the end of the page)
add some content to the page (for vertical scroll)
on desktop - open chrome, 
open developer tools (debugger)
toggle device toolbar and choose mobile device
scroll down to the menu widget
tap the hamburger button
see the jump occur

alternatively open console and after page loads scroll down and run this function (the function is by elemntor):

jQuery(".elementor-nav-menu__container.elementor-nav-menu--dropdown").animate( {height:"show"})

you'll se the jump up occur

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.15.1
	MySQL version: 5.5.60
	PHP Version: 7.0.9
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://p3647-48-5511.s48.upress.link
	Home URL: http://p3647-48-5511.s48.upress.link
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Lemonade studio Child template
	Version: 1.0.0
	Author: Lemonade studio
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.4.10
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.4.1
		Author: Yakir Sitbon, Maor Chasen, Ariel Klikstein

	Admin CSS MU
		Version: 2.5
		Author: Arun Basil Lal

	Akismet Anti-Spam
		Version: 4.0.8
		Author: Automattic

	Astra Customizer Reset
		Version: 1.0.0
		Author: Brainstorm Force

	Astra Pro
		Version: 1.5.2
		Author: Brainstorm Force

	Central Color Palette
		Version: 1.12.5
		Author: Gáravo

	Convert Pro
		Version: 1.2.6
		Author: Brainstorm Force

	Convert Pro - Addon
		Version: 1.1.3
		Author: Brainstorm Force

	Custom Icons for Elementor
		Version: 0.1.2
		Author: Michael Bourne

	Elementor
		Version: 2.2.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.7
		Author: Elementor.com

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	JetBlog For Elementor
		Version: 2.1.6
		Author: Zemez

	Jet Elements For Elementor
		Version: 1.12.2
		Author: Zemez

	JetThemeCore
		Version: 1.1.1
		Author: Zemez

	Jet Tricks
		Version: 1.1.1
		Author: Zemez

	Pods - Custom Content Types and Fields
		Version: 2.7.9
		Author: Pods Framework Team

	Schema Pro
		Version: 1.1.7
		Author: Brainstorm Force

	SEOPress
		Version: 3.1.1
		Author: Benjamin Denis

	ShortPixel Image Optimizer
		Version: 4.11.2
		Author: ShortPixel

	Simple CSS
		Version: 1.1
		Author: Tom Usborne

	Ultimate Addons for Elementor
		Version: 1.7.1
		Author: Brainstorm Force

	Ultimate Category Excluder
		Version: 1.1
		Author: Marios Alexandrou

	UpdraftPlus - Backup/Restore
		Version: 1.14.13
		Author: UpdraftPlus.Com, DavidAnderson

	WeSafe by uPress
		Version: 1.7.1
		Author: uPress

	WP Rocket
		Version: 3.0.4
		Author: WP Media

== Debug ==
	Errors: 
		TypeError: Cannot read property 'select2' of undefined
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.0 - 2:13071
			2018-08-31 22:59 +00:00

		TypeError: Cannot read property 'select2' of undefined
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.8 - 2:76870
			2018-08-20 16:45 +00:00

		ViewDestroyedError: View (cid: "view606") has already been destroyed and cannot be used.
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-08-20 16:44 +00:00

		ViewDestroyedError: View (cid: "view605") has already been destroyed and cannot be used.
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-08-20 10:51 +00:00

		ViewDestroyedError: View (cid: "view1453") has already been destroyed and cannot be used.
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-08-20 10:40 +00:00

		ViewDestroyedError: View (cid: "view600") has already been destroyed and cannot be used.
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-08-20 10:38 +00:00

		ViewDestroyedError: View (cid: "view596") has already been destroyed and cannot be used.
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-08-20 10:27 +00:00

		ViewDestroyedError: View (cid: "view671") has already been destroyed and cannot be used.
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-08-20 09:18 +00:00

		ViewDestroyedError: View (cid: "view2728") has already been destroyed and cannot be used.
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-08-20 09:16 +00:00

		TypeError: Cannot read property 'select2' of undefined
			at http://p3647-48-5511.s48.upress.link/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.8 - 2:76870
			2018-08-20 09:13 +00:00
</details>

**Comment by arielk** [comment]
We can't replicate the issue you described, can you share with us a link to this page?

**Comment by shimonshomron** [comment]
> We can't replicate the issue you described, can you share with us a link to this page?

you can use this page for reference:
http://p3647-48-5511.s48.upress.link/lab/

There is a menu at the bottom of the page for testing purposes.
Please use mobile agent on chrome browser --> reload the page --> scroll to the bottom and open the menu (click the hamburger).
you'll see the jump up occur

alternatively open console and after page loads scroll down and run this function:

jQuery(".elementor-nav-menu__container.elementor-nav-menu--dropdown").animate( {height:"show"})

you'll see the jump up occur

**Comment by arielk** [comment]
Please contact our support at support @ elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

**Comment by arielk** [comment]
We just release an update for this issue, please update to v2.1.10

Thanks for your feedback!
