### ISSUE TITLE
Recently Used

### ISSUE THREAD

**Issue by pb52** [pojome/elementor#5712]
Please can we have a section above the "Basic section" in the left hand panel called "Recent" which contains the last 12 items used, in alphabetic order?

Alternatively call it "Favourites" and provide a mechanism to place / remove items

I spend a lot of time scrolling / searching to find, again, the few items I have used before

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

You can use the search to finds widgets/elements faster and as for "favorites" we already have something like that requested #2184

thanks
