### ISSUE TITLE
וויגט כותרת

### ISSUE THREAD

**Issue by brzil** [pojome/elementor#5713]
יש בעיה שאין משהו מאוד בסיסי בוויגט של כותרת
אין דרך לשנות את צבע הטקסט שעומדים עם העכבר על הכותרת.
אשמח לטיפולכם בעדכון הבא

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by brzil** [comment]
שלום רז

לא הבנתי כל כך מה אני צריך לרשום

רשמתן לי בכרטיס תמיכה שאני ירשום לכם מה חסר כדי שתוכלו לבדוק האם להוסיף בעדכון הבא אז רשמתי

עומר

 

בברכה,
הכל לים – ב.מ.טק בע"מ
עומר גלבר - מנהל מכירות
נייד: 052-9777886 , פקס: 053-7970725
דוא"ל:  <mailto:omer@brz.co.il> omer@brz.co.il אתר:  <http://www.brz.co.il/> www.brz.co.il 
פייסבוק : לחץ כאן! <http://www.facebook.com/wwwbrzcoil> 
4Z7GEL
