### ISSUE TITLE
Medium.com logo in icon list widget is old and out-of-date

### ISSUE THREAD

**Issue by adammorenberg** [pojome/elementor#5714]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

In the icon list widget, the logo used for Medium.com is their old one. The current Medium logo is available here:

https://medium.design/logos-and-brand-guidelines-f1a01a733592

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
I merged this issue with  #4430, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
