### ISSUE TITLE
Elementor Pro & Yoast - Not playing nicely

### ISSUE THREAD

**Issue by digitalinksol** [pojome/elementor#5715]
Versions:

Elementor 2.2.1
Elementor Pro 2.1.7
Yoast 8.1.2 _and_ 8.2

Looks like there is an issue with Elementor and Yoast playing nicely together. I believe the more recent versions of Yoast are experiencing problems working together. When all three are enabled, users see the following error:

https://www.dropbox.com/s/z9b09ww2ienz9vd/Screenshot%202018-09-11%2019.18.10.png?dl=0

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info** which contains browser Console errors which without it we can't really help.

thanks
