### ISSUE TITLE
can't see acf image dynamically.

### ISSUE THREAD

**Issue by arnonalex** [pojome/elementor#5718]
I created a picture field but I can't import it into a template that I created.
Text fields work correctly. I was able to.
![sdfzdfv](https://user-images.githubusercontent.com/43205863/45422152-0fbb0880-b698-11e8-8bdd-26cca18233c4.JPG)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
