### ISSUE TITLE
Add option to change hover color posts widget

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5721]
Not only posts widget, every text widget (like header) need to have option to change hover color when posts link! isnt it?

![image](https://user-images.githubusercontent.com/2544046/45435313-faa2a180-b6b8-11e8-9d20-4c905f12c96e.png)

**Comment by bainternet** [comment]
Thanks for the feedback,
**Please follow guidelines** for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by sonicviz** [comment]
Is it possible to add a hover effect to posts at all? 
I just upgraded to Elementor Pro, and I am seriously surprised there are no hover effects on either Title or Image.
This seems pretty standard behavior, it's in Essential Addons.
