### ISSUE TITLE
[Feature Request] Use Post/Page ids in Widget Link boxes

### ISSUE THREAD

**Issue by GK1960** [pojome/elementor#5722]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Add the ability to use page or post ids in Elementor widget links, thereby avoiding hard-coded urls for internal links.

**Describe the solution you'd like**
I'd like to be able to enter the post or page id of an internal page/post in widgets that have link boxes. 

Currently you can only enter a url. If you were to allow post/page ids (i.e. numbers) as well, Elementor could detect numerical input and return get_permalink($post->ID) at execution time. 

This would avoid the user having to manually edit all widgets if they change a slug or implement HTTP SSL etc. etc.

I have sites where I don't currently use Elementor and on these I use a shortcode to achieve the same result. I hardly ever change a post/page id, but changing slugs is done quite often i.e. for SEO purposes.

**Describe alternatives you've considered**
I can't think of any!

**Additional context**
None

**Comment by bainternet** [comment]
@GK1960 

We already have that feature in Elementor Pro since v2.1 and its called "Internal URL Dynamic Tag"

thanks

**Comment by GK1960** [comment]
@bainternet 

Thanks, but it doesn't seem to enable me to use links to other **_specific_** internal posts/pages.

I'm using the button widget and the Post-Id is an option for the button text but not the link. 

So I can't make the button link to post id "13" - all I can do is make it link to:

- a post custom field
- this post's url
- the site's url
- this post's comment anchor
- this post's author website/archive

Am I missing something or is the functionality I require missing?

Thanks.
