### ISSUE TITLE
Feature Request - Mark, Flag, or List Widgets with Custom CSS

### ISSUE THREAD

**Issue by Airbear737** [pojome/elementor#5724]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I often forget that I have added custom CSS to a widget and can't understand its behavior until I remember to open the CSS settings. The Custom CSS is usually down the window and out of sight unless scrolled to it. This is especially true when coming back to a project after some time or doing maintenance work on someone else's project.

**Describe the solution you'd like**
The widgets containing custom CSS should be marked, flagged, and or listed somehow. Examples would be a change in color of a portion of the widget control icons, the Custom CSS title, or flag in the widget settings window. Whatever method used, it needs to readily visible to the developer.

**Describe alternatives you've considered**
The only way I know to track Custom CSS is keep a paper list of widgets with Custom CSS. This prone to being outdated and or lost.

**Additional context**

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/pojome/elementor/issues/2180 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
