### ISSUE TITLE
Make the Pro version GPL too

### ISSUE THREAD

**Issue by fernandotellado** [pojome/elementor#5728]
I've recently bought your Pro version of the plugin and have noticed that it isn't under GPL licence as the free version available at wordpress.org, the pro plugin have a limited license that doesn't offer the GPL freedoms.

By GPL, every derivative work would be GPL too, so you must extend the GPL v3+ of the free version to the pro one.

Thanks!

**Comment by bainternet** [comment]
@fernandotellado 

Closing this as not related in any way to our development. 

thanks.

**Comment by planetahuevo** [comment]
+1

**Comment by fernandotellado** [comment]
And Which is the adequate channel?

**Comment by Paramaconny** [comment]
Good afternoon, I am a developer and I believe that free software is the evolution of proprietary software. All software development must be free. Sharing knowledge makes us free and evolved ... Let's move forward ... Thank you for your time.

**Comment by machelinos** [comment]
+1

**Comment by mizejewski** [comment]
@bainternet the code license is very relevant to development, but if there is better place to discuss this, please direct me to it.
