### ISSUE TITLE
Image caption background color

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#573]
Feature request: 
It would be great to have the option of a basic caption under the image or a caption that appears as a text overlay (as in example.) Please also add the ability to set a background color on the caption (as in other widgets) to make the text readable over the image. Example shows a text widget with background color rgba(0,0,0,0.38) applied, but that cannot be done for the caption text.

![caption_background](https://cloud.githubusercontent.com/assets/974442/18563725/9e97074a-7b3d-11e6-8558-a99d19b8432c.png)

**Comment by arielk** [comment]
@mizejewski Is this issue similar to the concept in this issue #528 ?

**Comment by KingYes** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by mizejewski** [comment]
Sorry for the late reply. the 1.5 update added great hover effects, but the caption placement can still not be set to overlay the image.
