### ISSUE TITLE
Slide Widget pulling from posts in Elementor

### ISSUE THREAD

**Issue by karramax** [pojome/elementor#5731]
Yes, the elemental is excellent, but from what I've seen, something is missing for it to be perfect - A Widget with a Posts slide, like the one we developed and that can be seen here on this site: [http://www.educadorafm.net/](http://www.educadorafm.net/)  or Youtube [https://youtu.be/i997J7gx7Rg](https://youtu.be/i997J7gx7Rg)

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
