### ISSUE TITLE
Copy and Paste via multisite

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#5736]
I have a multisite and I need to copy some pages ( whole pages ) or some elements to another multisite.

"Copy" and "Paste" seem don't work among multisite.

I also tried some multisite post duplication plugins. but it's not working.

Is there any way to do? only save as template and import it to the multisite?

And 1 more another question.  
Is there any way to make our (plugin or theme author ) own library like yours?
You have "blocks", "pages" in Library. "My templates" is really a headache if you have more than 10. 
Any plan or any idea to make our own library?

Thank you for super plugin!

**Comment by bainternet** [comment]
@pulla 

Copy/Paste works by saving the data to localStorage which is only available in the same domain scope, so only if the multi-site is using a sub-folder setup it should work but even then it could have some problems. It was never designed for that.

And yes, "save as template and import it" is the way to do it.


as for the library, there is a different issue for it #454 and there is the one opened by you #4166

thanks.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.11**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
