### ISSUE TITLE
Form element number and tel field validation for mobile number/all other fields - Elementor PRO

### ISSUE THREAD

**Issue by manojp05** [pojome/elementor#5738]
Hi there,

Greetings!!!

Thanks for this great page builder. I am using your page builder since it's released and made many websites using your page builder.

I am facing same issues multiple time with this plugin when I use a contact form from PRO version of an Elementor. It's a very minor issue I don't know how you missed this.

When I select any type of input field it should validate them as they require. For example:
Mobile field.
Input type number or tel.

When I use this field, it's not validating the value as a mobile number can be. There are many types of validation for a mobile number like it should able to only able to input a specific amount to input. Where mobile number should enter till 10-12-13 digits. it not able to input text type while using number and tel input type.

I know that I'm not a good English speaker. So please pardon my typos mistakes if I did.

I hope you'll take a review of it and solve this issue in your next release.

Best of luck for your future achievements...........

Regards,
Manoj

**Comment by bainternet** [comment]
@manojp05 

We don't see this as an issue, Elementor is used all over the world and each part of the world has a different type/format for phone/mobile number, which is something we can't possibly cover.

We only validate that the chars that were inputted are valid for a phone number field eg:
`0-9, (, ), #, &, +, *, -, =, .`

We do, however, provide an option to run your own validation for each field and in your case, it should be something like:

```PHP
<?php
add_action( 'elementor_pro/forms/validation/tel', function( $field, $record, $ajax_handler ) {

	// Match this format XXX-XXX-XXXX, 123-456-7890

	if ( preg_match( '/[0-9]{3}-[0-9]{3}-[0-9]{4}/', $field['value'] ) !== 1 ) {
		$ajax_handler->add_error( $field['id'], 'Please make sure the phone number is in XXX-XXX-XXXX format, eg: 123-456-7890' );
	}
}, 10, 3 );
```

thanks for the feedback.

**Comment by manojp05** [comment]
Hi Bainternet,

Thanks for your reply.

I agree with your thought but one thing you also should add to this form element. When you select input type <b>tel element</b> to enter the phone number from the users, it allows you to entering alphabet characters in the field. You should filter it like user cannot input alphabet.

Also as per my research, no country has more than 13 digits in the number of mobile numbers. So you can add a condition that the user can not enter more than 13 digits. If they try then input value is not visible after 13 digits.

I am requesting you to add these limitations/validations to your form element for a mobile number.

I am asking this because my client has asked me to add this validation in the field two times. I hope you understand.

Looking forward to hearing your thoughts.



Best Regards,
Manoj

**Comment by robert1112** [comment]
> @manojp05
> 
> We don't see this as an issue, Elementor is used all over the world and each part of the world has a different type/format for phone/mobile number, which is something we can't possibly cover.
> 
> We only validate that the chars that were inputted are valid for a phone number field eg:
> `0-9, (, ), #, &, +, *, -, =, .`
> 
> We do, however, provide an option to run your own validation for each field and in your case, it should be something like:
> 
> ```
> <?php
> add_action( 'elementor_pro/forms/validation/tel', function( $field, $record, $ajax_handler ) {
> 
> 	// Match this format XXX-XXX-XXXX, 123-456-7890
> 
> 	if ( preg_match( '/[0-9]{3}-[0-9]{3}-[0-9]{4}/', $field['value'] ) !== 1 ) {
> 		$ajax_handler->add_error( $field['id'], 'Please make sure the phone number is in XXX-XXX-XXXX format, eg: 123-456-7890' );
> 	}
> }, 10, 3 );
> ```
> 
> thanks for the feedback.

@bainternet That should fit my needs. Where should I put this file? functions.php or ? Thank you.

**Comment by mumtazmd** [comment]
Yes Manoj i agree with this request. Few clients are asking only mobile numbers should be only 13 digits not more than that....

If any one know solution for this give reply.

**Comment by ammy-kang2989** [comment]
I am also facing same issue, I need to validate my number for 13 digits, how can I do this?

**Comment by gerardreches** [comment]
> @manojp05
> 
> We don't see this as an issue, Elementor is used all over the world and each part of the world has a different type/format for phone/mobile number, which is something we can't possibly cover.
> 
> We only validate that the chars that were inputted are valid for a phone number field eg:
> `0-9, (, ), #, &, +, *, -, =, .`

@bainternet Could you explain to me why this isn't working?


<img width="684" alt="Screen Shot 2021-06-05 at 17 49 56" src="https://user-images.githubusercontent.com/7549815/120889269-73df4100-c626-11eb-9cd9-ce94df7f4ff0.png">

**Comment by vahidgoudini** [comment]
_Hi There,_
not working this role, please check and have question.

How set validation "**by character**" in phone field in Elementor Pro.
Example: 09056025697
