### ISSUE TITLE
Elementor Pro does not seem to work with YITH Woocommerce Request A Quote 

### ISSUE THREAD

**Issue by markusreklambyra** [pojome/elementor#5739]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi! I tried to use YITH WooCommerce Request A Quote on my Elementor Pro website. My problem is that my "Add to quote" button from YITH plugin is not displayed as it should be when I have Elementor Pro active. If I deactivate Pro it works.  

## Steps to reproduce
1. Install Elementor + Pro
2. Install YITH WooCommerce Request A Quote 
3. Add "Add to quote" button to single product page
4. Button is not shown
5. Deactivate Pro and look again. The button is now back as it should be. 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
Everything is  up to date. 

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@markusreklambyra 

Can you check the [debug log](https://codex.wordpress.org/Debugging_in_WordPress) for errors as well as the browser console?

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by marameodesign** [comment]
Apologies to comment on a closed matter - but I am having exactly the same issue and I was wondering how it was solved. Thanks

**Comment by thematsanity** [comment]
@markusreklambyra another that works fine with woocommerce+elementor?

**Comment by markusreklambyra** [comment]
@thematsanity It's not perfect, but works for me: https://wordpress.org/plugins/quotes-for-woocommerce/

**Comment by marameodesign** [comment]
@bainternet which is the official response from Elementor? Elementor Pro and Request a Quote plugin do not work together and we just need to find a different plugin?

There is no way to get it to work? 

This is rather important to understand. Thank you

**Comment by bainternet** [comment]
The issue here is that the plugin relays on a hook which is missing when using elementor WooCommerce builder, due to the fact that Elementor doesn't need the native WooCommerce hooks to place elements (product image, price, description...), it uses Drag n Drop.

A quick look at the code of the plugin can suggest that `YITH_YWRAQ_Frontend->add_button_single_page()` is not called when using Elementor so a solution cloud be a custom shortcode to call the method manualy, ex: 

```PHP
/**
 * usage: add [yith_requet_quote_elementor] shortcode
 */
add_shortcode( 'yith_requet_quote_elementor', function(){
    if ( ! class_exists( 'YITH_YWRAQ_Frontend' ) ) {
        return '';
    }
    ob_start();
    YITH_YWRAQ_Frontend::get_instance()->add_button_single_page();
    return ob_get_clean();
} );
```

After you paste this snippet in your theme's functions.php file, edit your single product template with elementor and add `[yith_requet_quote_elementor]` as a shortcode in the location you want the button to appear.

Thanks.

**Comment by C-Nog** [comment]
I FOUND THE SOLUTION

After hours of research I finally found the solution. So fu**** simple.

You dont need custom code, you dont need any different shortcode.

You just have to use the default shortcode of the plugin [yith_ywraq_button_quote] in a TEXT Element (in text tab) instead of using Shortcode Element.
![image](https://user-images.githubusercontent.com/39405601/73280934-fef82d80-41cd-11ea-8fd1-589163751e6b.png)

Thank me later
Cheers from UpSites (https://upsites.digital)

**Comment by juniorinvernizzi** [comment]
> I FOUND THE SOLUTION
> 
> After hours of research I finally found the solution. So fu**** simple.
> 
> You dont need custom code, you dont need any different shortcode.
> 
> You just have to use the default shortcode of the plugin [yith_ywraq_button_quote] in a TEXT Element (in text tab) instead of using Shortcode Element.
> ![image](https://user-images.githubusercontent.com/39405601/73280934-fef82d80-41cd-11ea-8fd1-589163751e6b.png)
> 
> Thank me later
> Cheers from UpSites (https://upsites.digital)

it's working perfectly!!!!

**Comment by joefclarin** [comment]
> I FOUND THE SOLUTION
> 
> After hours of research I finally found the solution. So fu**** simple.
> 
> You dont need custom code, you dont need any different shortcode.
> 
> You just have to use the default shortcode of the plugin [yith_ywraq_button_quote] in a TEXT Element (in text tab) instead of using Shortcode Element.
> ![image](https://user-images.githubusercontent.com/39405601/73280934-fef82d80-41cd-11ea-8fd1-589163751e6b.png)
> 
> Thank me later
> Cheers from UpSites (https://upsites.digital)

doesn't work now. tried with Shortcode, Text Editor, Heading and Text (native WordPress)

**Comment by LucianoCT** [comment]
WORKS FINE 
Thank you very much "bainternet". Your code into the theme's functions.php works fine for me.
![botão Adicionar Orçamento](https://user-images.githubusercontent.com/91859481/158080131-bbe1215a-dd04-43af-b0a5-009c490313f7.jpg)

**Comment by sddesigns7** [comment]
For anyone who is still trying like me... I got this working by adding the "summary hook" widget to the product page template, which loaded the quote button!


I hope it helps someone :)

Stay safe and happy!
==
<img width="425" alt="Screen Shot 2023-02-16 at 6 52 34 PM" src="https://user-images.githubusercontent.com/14974434/219433490-7013c660-45bc-429a-a657-82212ea49e0e.png">
==
<img width="349" alt="Screen Shot 2023-02-16 at 6 50 38 PM" src="https://user-images.githubusercontent.com/14974434/219433056-1082a034-4311-4d12-ac7d-85d339bf7b1a.png">

**Comment by Dspink** [comment]
> For anyone who is still trying like me... I got this working by adding the "summary hook" widget to the product page template, which loaded the quote button!
> 
> I hope it helps someone :)
> 
> Stay safe and happy!
> 
> # ==
> <img alt="Screen Shot 2023-02-16 at 6 52 34 PM" width="425" src="https://user-images.githubusercontent.com/14974434/219433490-7013c660-45bc-429a-a657-82212ea49e0e.png">
> <img alt="Screen Shot 2023-02-16 at 6 50 38 PM" width="349" src="https://user-images.githubusercontent.com/14974434/219433056-1082a034-4311-4d12-ac7d-85d339bf7b1a.png">

Where do I find this widget please?

**Comment by andreagrillo** [comment]
Hello everyone,
a customer reported to us the existence of this thread and we believe it is appropriate to clarify some aspects that can still generate confusion among users.
The YITH Request a Quote for WooCommerce Premium plugin is designed to work, in the first instance, with WooCommerce hooks. However, by activating Elementor (whether Free or Pro) the hooks used by the plugin are no longer available.
From version 3.1.0, released in February 2021, our plugin offers a series of widgets that can be used within the layout of the pages that you will create with Elementor and you can find them all documented on this page: https://docs.yithemes.com/yith-woocommerce-request-a-quote/premium-version-settings/elementor/
 
It is therefore no longer necessary to use the shortcode or create custom snippets to show the "Add to quote" button.
 
We hope this can clarify any doubts, in any case our support is always available for any problem.
 
(Note: the Free version of Request a Quote does not currently support Elementor)
