### ISSUE TITLE
Compatible form plugins

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#574]
Just wondering if anyone can say whether these top three form plugins will work well with a site using Elementor?

1. Gravity Forms
2. Ninja Forms
3. WPForms

_from: http://www.wpmayor.com/wpforms-review/_
> The WordPress Contact Form market is currently dominated by **Gravity Forms** and **Ninja Forms**, with both plugins having been established for a number of years. Although it is interesting to note **WPForms**’ late entry in the market (launched in March 2016), one has to keep in mind is that it has been developed by Syed Balkhi, the founder of WPBeginner, which certainly adds clout to the plugin.

**Comment by arielk** [comment]
In our experience, Ninja Forms, Contact Form 7 and WPForms work well with Elementor, We didn't check compatibility with Gravity Forms yet.

**Comment by mizejewski** [comment]
Thanks!
