### ISSUE TITLE
Page Scrolls to Bottom when Resizing Window When Sticky Header Active

### ISSUE THREAD

**Issue by katart** [pojome/elementor#5740]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I have the Site Header template/section set to Sticky => Top, the entire site scrolls to the bottom as I resize the browser window. See this video that shows what is happening: http://files.katart.com/bYI3AHA

This also happens when Chrome Developer Tools is not open.

## Steps to reproduce

1. Select Scrolling Effect => Top to the Section Element in the Header Template
2. View Front End of the site, scroll halfway down the page and then resize the browser window

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.12.1
	MySQL version: 5.6.41
	PHP Version: 7.2.9-1+ubuntu14.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://myghf.ts7gcre7-liquidwebsites.com
	Home URL: https://myghf.ts7gcre7-liquidwebsites.com
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.7
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.2.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.8
		Author: Elementor.com

== Must-Use Plugins ==
	Liquid Web Managed WordPress
		Version: 1.4
		Author: Liquid Web <support@liquidweb.com>

	Liquid Web Update Manager
		Version: 1.0
		Author: Liquid Web <support@liquidweb.com>

== Debug ==
	Errors: 
		TypeError: Cannot read property 'currentView' of undefined
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:239133
			2018-09-12 19:22 +00:00
			x 2 times

		TypeError: Cannot read property 'hoverIntent' of undefined
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:27609
			2018-09-12 18:29 +00:00
			x 2 times

		ReferenceError: TweenMax is not defined
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor-extras/assets/lib/parallax-element/parallax-element.min.js?ver=1.0.0 - 1:2992
			2018-09-12 18:12 +00:00
			x 12 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:239133
			2018-09-12 16:30 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:173847
			2018-09-12 13:16 +00:00
			x 6 times

		ViewDestroyedError: View (cid: "view420") has already been destroyed and cannot be used.
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-09-11 21:35 +00:00
			x 2 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:239133
			2018-09-11 21:32 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:173847
			2018-09-11 21:25 +00:00
			x 8 times

		TypeError: Cannot read property 'on' of null
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:213049
			2018-09-10 20:09 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://myghf.ts7gcre7-liquidwebsites.com/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-09-10 20:09 +00:00

				
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
fixed, thanks.
