### ISSUE TITLE
Please fix development api

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#5743]
https://developers.elementor.com/elementor-controls/number-control/

There are 2 "min"s there. I like the old one. this one has many mistakes. I wasted some time with some mistakes.
I hope all fixes soon.

$this->add_control(
			'price',
			[
				'label' => __( 'Price', 'plugin-domain' ),
				'type' => \Elementor\Controls_Manager::NUMBER,
				'min' => 5,
				'min' => 100,
				'step' => 5,
				'default' => 10,
			]
		);

**Comment by bainternet** [comment]
@pulla 

Thanks, fixed.

If you can point out the mistakes, it would help.
