### ISSUE TITLE
Flex Column

### ISSUE THREAD

**Issue by ljgarnes** [pojome/elementor#5745]
Need the ability to order columns on mobile. The reverse column on sections doesn't allow for column ordering when 3 or more columns.

I have a header with 3 columns. I want column 2 to be the last column on mobile. Reverse column for the section doesn't allow this.

And when 4 columns have the ability to arrange as needed...

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by willcitizen** [comment]
Why close this? 

It's a perfectly understandable and valid request - is it a duplicate?

Is it already on your roadmap?

**Comment by grrog** [comment]
I have the same request.
The reverse-column option is not enough when there are 3 or more columns.

With CSS flexbox layout, there is the _order_ option to reorder the elements individually…

**Comment by black-eye** [comment]
+1 Not sure, why this was closed. The description is completely understandable and the columns (re)ordering feature would be priceless.
