### ISSUE TITLE
badges clickable

### ISSUE THREAD

**Issue by cocob35** [pojome/elementor#5746]
Hello,

how can I make badges clickable in an archive page, or a block blog post ?

https://imgur.com/a/xaoJv0Z

Best Regards,
Johann

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for your request, it should be possible with #4440 

thanks
