### ISSUE TITLE
make goodreads icon exist in social icons widget

### ISSUE THREAD

**Issue by angelealynn** [pojome/elementor#5748]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm frustrated that I can add all of the social icons needed, except goodreads. I understand the icon is available in awesome fonts, but the option to use those fonts are not available in the social icons widget.

**Describe the solution you'd like**
I'd like to be able to add goodreads as a social icon.

**Describe alternatives you've considered**
Linking each social button by hand outside of elemental and rebuilding in order to create the widget to look as needed.

**Additional context**
none.

**Comment by bainternet** [comment]
@angelealynn 

This should be possible once #4430 is implemented.
