### ISSUE TITLE
[Feature Request] Integration of custom fields created with CMB2

### ISSUE THREAD

**Issue by ipokkel** [pojome/elementor#5749]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When using dynamic fields in Elementor Pro I can retrieve custom fields created with CMB2 for textual type fields only but not for media fields, i.e. image or gallery.

**Describe the solution you'd like**
Can you please add integration support for CMB2's custom fields, if possible even those type of custom fields that's set to not show up in a post's custom fields in the post creation pages.

**Describe alternatives you've considered**
I've used ACF PRO as an alternative to create custom fields for the templates and plugin I'm creating for Elementor Pro successfully, unfortunately the license terms for ACF Pro prohibits you from distributing/sharing free plugins/themes with ACF Pro incorporated.

**Additional Information**
CMB2 https://wordpress.org/plugins/cmb2/

**Comment by bainternet** [comment]
@ipokkel 

CMB2 uses the WordPress native custom fields API which means they should be supported out of the box with the "Post Custom Field" dynamic tag provided in Elementor Pro.

> if possible even those type of custom fields that's set to not show up in a post's custom fields in the post creation pages.

For that, You would need to create a [custom dynamic tag](https://developers.elementor.com/dynamic-tags/)

thanks.
