### ISSUE TITLE
[Enhancement] Support Greater Number of Global Colours & Color Picker Entries

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#5750]
Hey,

Please consider allowing us to add more colours to the Global Colours and Color Picker panels.

I dunno about you guys, but when coupling with shades and different tones for light/dark pages, I have a combined total of circa 16-20 primary/second/tertiary colors I use on my site.

Thanksss.

**Comment by bainternet** [comment]
@enviedbymost 

We have considered it but we feel that we need to replace the whole color picker component before we can advance in that direction.

So, We do see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

thanks.
