### ISSUE TITLE
Replace URL doesn't replace Custom Fonts URLs

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#5757]
Howdy!

I've just migrated a site from its cPanel Temporary URL to production. I've used Elementor's `Replace URL` tool to update the references to the temporary URL, which worked for the content, but the URLs in the `Custom Fonts` area didn't update. This results in cross-origin errors in the browser.

I suspect it's because the URL the `Replace URL` tool looks for have escaped forward-slashes but that's a guess.

It's easy enough to manually update the URLs but it'd be good to get fixed. Ta!

**Comment by bainternet** [comment]
@JoelEadeDesign 

The Replace URL tool is for Elementor Data and not native WordPress. If you migrated from temp to production that should have changed with your migration process like all other posts/pages/attachments URLs.

So without knowing what was actually done in you migration process... there is nothing really to fix.


thanks for reporting.

**Comment by JoelEadeDesign** [comment]
Hey @bainternet. I'm referring to the Elementor Pro Custom Fonts feature.

**Comment by erfan-ilyas** [comment]
Yes I think @JoelEadeDesign is right.
The Replace URL dosen't replace the custom fonts managed using Elementor and Also doesn't replace the page background image.

**Comment by taropaa** [comment]
I can confirm this is the case. This should be fixed/added.
