### ISSUE TITLE
Add Section Element to Element panel

### ISSUE THREAD

**Issue by LearnWPBasics** [pojome/elementor#576]
[Feature Request/Enhancement]

As it is now, there is no way to easily add a new section to an existing layout. The only options are adding a new one to the bottom of the layout and then dragging it up, but that doesn't always work out either as there is nowhere to "drop" it properly. The other is to duplicate one near the one you want to add and then replace the contents; not very elegant.
Again, I implore you to check out how your "BB-iggest" competitor does this in allowing one to add a new  row (Elementor Section) to wherever one wants. 
Along this line, it would be beneficial from a UI/UX perspective to eliminate the Section tab from next to the Column tab; confusing. 
You have a Section (row) and then within that, Column(s). That easy :)

Cheers!
Lyle

**Comment by arielk** [comment]
I merged this issue with another issue #493 in the same subject so that our UI staff could deal with it more efficiently. So please let's continue the conversation there.
