### ISSUE TITLE
Custom Post Type Filtering

### ISSUE THREAD

**Issue by bnruane** [pojome/elementor#5762]
I am trying to follow the instructions on this post:
https://developers.elementor.com/custom-query-filter/

But I have not been able to make it work. I check with support and they told me to post here. 

I have two custom post types recipes and wellness. I am trying to pull the most recent post to show as a feature article on my site. I know that I can accomplish the filtering to most recent but have been unable to get it to pull from the two different post types. 

How do I get the posts query to pull from two custom post types?

**Comment by pixelsock** [comment]
You have to add this code to your functions.php file or you can use a plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/). Create a new snippet and just drop the following code into the Snippet. 

`add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
	$query->set( 'post_type', [ 'recipes', 'wellness' ] );
} );`

**Comment by bnruane** [comment]
I have added this but I am still not getting the desired result. What does
the setting need to be in the editor? Does the dropdown need to be set to?
Thanks for your help with this matter.
Brendan

**Comment by bnruane** [comment]
Any follow up to this?

**Comment by pixelsock** [comment]
@bnruane can you provide a screenshot of your elementor settings?

**Comment by bnruane** [comment]
Since my custom post types show in the dropdown list and are not under
posts, I am not sure what needs to be selected to make this work. The two
post types that I am trying to filter from are Recipes (slug: recipes) and
Wellness Articles (slug: wellness). I left the filter named
my-custom-filter as I wanted to make sure my naming did not cause any
issues for the query. I have tried setting the dropdown to both recipes and
wellness articles and neither returns the desired result.

**Comment by bainternet** [comment]
@bnruane 

You can set the drop-down to either one and the filter will make sure both types are selected.

without knowing more I can only direct you to make sure the filter name in the panel is an exact match to the snippet filter name:

```PHP
    add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
        $query->set( 'post_type', [ 'recipes', 'wellness' ] ); 
    } );
```

`my_custom_filter` is not the same as `my-custom-filter`.

**Comment by lauranunez** [comment]
it works fine. But in badget is not possible show the taxonomy?
