### ISSUE TITLE
Image Box Widget does not honour spacing when left aligned

### ISSUE THREAD

**Issue by simonclay** [pojome/elementor#5763]
With the Image Box Set to 'Left align', while editing in Elementor, there is space between the image and the title to the right. But when leaving Elementor and viewing the actual page, there is no spacing. It is being overridden.

![screen shot 2018-09-18 at 10 10 54](https://user-images.githubusercontent.com/2143351/45677274-b2a5d380-bb2b-11e8-9614-379ddcde3ff4.png)
![screen shot 2018-09-18 at 10 10 57](https://user-images.githubusercontent.com/2143351/45677277-b33e6a00-bb2b-11e8-86a2-228e9e73fb75.png)

**Comment by stylethemes** [comment]
same problem here

**Comment by amarnegi** [comment]
I'm also facing this issue since a couple of days
