### ISSUE TITLE
Custom Fonts not workin after update

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#5764]
Hello, the custom fonts are not working on single pages after the new update...

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

With this little information, we can't possibly help.
