### ISSUE TITLE
Cannot put a negative sign for adjusting margins unless a positive value has already been entered

### ISSUE THREAD

**Issue by jazir5** [pojome/elementor#5765]
when attempting to adjust margins inside the advanced settings panel, i cannot make a margin negative unless a positive value is already entered. Would it be possible to make -0 have the same function as 0 so to allow assigning a negative value to a margin without already typing a positive value? it's very frustrating, time consuming and unintuitive to require the current method

**Comment by JoeDarko** [comment]
+1

**Comment by bainternet** [comment]
I merged this issue with  #5018, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
