### ISSUE TITLE
Post Info Widget -> Custom -> Link : Open in New Window bug 

### ISSUE THREAD

**Issue by jmanningppbh** [pojome/elementor#5766]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Description

I'm trying to provide links to open some PDF files by using the Post Info widget.  The URLs are stored in ACF file fields which are set to return the 'URL' only (not an array).  But ACF doesn't seem to be the issue - this seems to happen on non-dynamic links I'm trying too.

When I select the 'Open in a new window' checkbox I'm getting the text string 'on' added to the end of the HREF URL and it's breaking my links.  It's like the data being returned is just the checkbox value instead of the target="_blank".

## Steps to reproduce

1) Add a Post Info Widget to a section on a 'single' page template
2) Choose type 'custom'
3) Enter some custom text (non-dynamic)
4) Set Link to YES
5) Paste a URL
6) Click the gear icon to the right of the URL to open options
7) select 'Open in a new window'
8) Check the preview window and you'll see the HREF is point to your URL appended with the string  "on" instead of proper URL

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
	MySQL version: 5.6.35
	PHP Version: 7.0.15
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://localhost
	Home URL: https://localhost
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.7
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.9
		Author: Elementor.com


== Debug ==
	Errors: 
		TypeError: Cannot read property 'select2' of undefined
			at https://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.3 - 2:13065
			2018-09-17 21:37 +00:00

		TypeError: Cannot read property 'select2' of undefined
			at https://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:13071
			2018-09-07 15:00 +00:00
			x 5 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.7 - 2:157928
			2018-08-17 18:53 +00:00

		TypeError: Cannot read property 'html' of undefined
			at https://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:80110
			2018-08-15 20:17 +00:00

		TypeError: Cannot read property 'forEach' of undefined
			at https://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:206285
			2018-08-15 17:00 +00:00
			x 6 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://localhost/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:157928
			2018-08-15 16:55 +00:00
			x 2 times

				


```
</details>

**Comment by dmwsites** [comment]
I'm having the same issue with a link to a pdf.

**Comment by Maroin** [comment]
Hi,
I have the same issue for a custom field, which is an URL. "on" string is appened at the end 
I guess it's still in progress, I won't find it on the 2.3.0 version of Elementor pro ?

Regards
