### ISSUE TITLE
Control Popover - reset to default

### ISSUE THREAD

**Issue by pmallek** [pojome/elementor#5767]
Hello,

I'm facing problem with popover control. All functionalities related to this control work just fine but reset to default button. It simply doesn't reset fields which are inside popover.

Basic example:
```PHP
        $this->add_control(
            'test_1',
            [
                'label' => esc_html__('Test', 'digital-atlas-core'),
                'type' => Controls_Manager::POPOVER_TOGGLE
            ]
        );
        $this->start_popover();
        $this->add_control('test_2',
            [
                'label' => esc_html__('Test control', 'digital-atlas-core'),
                'type' => Controls_Manager::TEXT,
                'default' => 'test text'
            ]
        );
        $this->end_popover();
```

Test scenario:

1. Open popover
2. Change 'test text' to something else
3. Close popover
4. Press reset to default button
5. Open popover - text_2 control value isn't 'test text' (which is defined as default), it's still untouched, modified value

There is no php errors and no errors on console.

**Comment by bainternet** [comment]
@pmallek 

This is just how the popover toggle works.

It acts as a "toggle" of on -> custom settings, off -> default values which means that all of its "sub" controls will have the default value in the render method.

As for the controls in the panel that are not reverted to default, this is intentional and desired behavior to avoid losing all custom settings once you click the "back to default".

You just need to check in your render method if the popover toggle control has a value of `"yes"` and only if it does you should act on the custom settings from the "sub" controls. which in your example that would be the `test_1` control.

thanks.

**Comment by kamalahmed** [comment]
If someone is looking for an answer to revert the changes when the 'back to default' button is clicked, then you can follow this code. You just need to add condition to all the controls inside the popover. You can see how typography control works. this solution will work exactly like that. I wish this was mentioned above. I had to stumble and think a lot to fix this simple issue. I think someone may be facing same problem as documentation is lacking such information on popover control.

` $this->add_control(
            'test_1',
            [
                'label' => esc_html__('Test', 'digital-atlas-core'),
                'type' => Controls_Manager::POPOVER_TOGGLE
            ]
        );
        $this->start_popover();
        $this->add_control('test_2',
            [
                'label' => esc_html__('Test control', 'digital-atlas-core'),
                'type' => Controls_Manager::TEXT,
                'default' => 'test text',
                'condition' => [
				'test_1' => 'yes', // by adding condition to popover switch, we are limiting this settings effect only when the popover is active.
		],
            ]
        );
        $this->end_popover();`

**Comment by kamalahmed** [comment]
If someone is looking for an answer to revert the changes when the 'back to default' button is clicked, then you can follow this code. You just need to add condition to all the controls inside the popover. You can see how typography control works. this solution will work exactly like that. I wish this was mentioned above. I had to stumble and think a lot to fix this simple issue. I think someone may be facing same problem as documentation is lacking such information on popover control.

```php
$this->add_control( 'test_1', [
                'label' => esc_html__('Test', 'digital-atlas-core'),
                'type' => Controls_Manager::POPOVER_TOGGLE
            ]
        );

$this->start_popover();

$this->add_control('test_2', [
                'label' => esc_html__('Test control', 'digital-atlas-core'),
                'type' => Controls_Manager::TEXT,
                'default' => 'test text',
                'condition' => [
				'test_1' => 'yes', // by adding condition to popover switch, we are limiting this settings effect only when the popover is active.
		],
            ]
        );

$this->end_popover();
```

**Comment by oooh-boi** [comment]
@kamalahmed - thanks a bunch for this one, been banging my head for a while with this one! 
@bainternet - how come so many trivial questions are answered _that wrong_ by the chief developer?

**Comment by oooh-boi** [comment]
One little exception though...

```
$this->add_control( 'test_1', [
        'label' => esc_html__('Test', 'digital-atlas-core'),
        'type' => Controls_Manager::POPOVER_TOGGLE, 
        'return_value' => 'yes', /* must return 'yes' */
        'default' => 'yes', /* this one is important, it prevents initial JS undefined */
    ]
);

$this->start_popover();

$this->add_control( 'test_2', [
        'label' => esc_html__('Test control', 'digital-atlas-core'),
        'type' => Controls_Manager::TEXT,
        'default' => 'test text',
        'condition' => [
            'test_1' => 'yes', 
	],
    ]
);

$this->end_popover();
```
