### ISSUE TITLE
How to remove scroll wheel/bar in elementor Iframe

### ISSUE THREAD

**Issue by Christiaan99** [pojome/elementor#5769]
I made a review page and want it to import to Wordpress with a Iframe but it shows a scroll wheel on the side. I want the full content to show on the page and not only 4 and then scroll down. 

Website: https://autorijschoolwezemer.nl/reviews/

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


As for your question its more of an html/css than an Elementor question.
try this:
https://stackoverflow.com/questions/10082155/remove-scrollbar-from-iframe


thanks.
