### ISSUE TITLE
page content repeating (doubles) on scroll

### ISSUE THREAD

**Issue by bishgop** [pojome/elementor#577]
I have created a few pages of my site with Elementor. Just this day, I checked the pages to see that the content within the page are doubling up.  For example; if I created two sections in  a page, it becomes four sections (copy of the two sections) on scrolling down the page.

Have a look at this page: http://www.littlebighappiness.in

How to fix this?

**Comment by arielk** [comment]
I don't see this page built with Elementor.
If you edit the page with Elementor it still happens to you?

**Comment by bishgop** [comment]
Hi,

I tried multiple fixes and troubleshooting for my site, I went on to deactivating and reactivating plugins to check if any of it is the culprit; I think it's some other issue which I have no clue about.

I reactivated Elementor too, the issue persists : http://www.littlebighappiness.in/

Researching!

**Comment by arielk** [comment]
Can you try to replace the theme or deactivate other plugins?

**Comment by WPDevHQ** [comment]
Check your template file as you seem to have a double output of elementor instances.
One instace is nested inside the #primary div and the other is outside it - see below
`<div class="main-content-inner col-sm-12 col-md-8 full-width>`
`<div id="primary" class="content-area"></div>` the below div is repeated inside here!
`<div id="elementor" class="elementor"></div>`

Do you have a full-width template in your child theme? If so what is the code?

If you'd like to share a copy of your child theme we can take a look and see where things are going wrong for you.

**Comment by bishgop** [comment]
@arielk If I replace the theme, I will lose all my work, styles, which I do not want to, at this stage. Plugins aren't the issue as I tried deactivating all of them.

@WPDevHQ Would you help me with possible solution if I share my site login, etc? I am sure I will not be able to implement the solutions shared by you by myself.

Thanks much.

**Comment by WPDevHQ** [comment]
@bishgop - thanks for the child theme. Is the aim of the child theme just to add WooCommerce support?
If yes then start by removing all of the files in the child theme other than style.css, functions.php and the templates folder.

A quick scan of code I don't see what could be throwing things off - any chance for the json file of the template? I do see the parent theme using `wp_reset_query()` in extras.php for the slide which is a no no - should be using `wp_reset_postdata()`.

If you can provide the json file I'll try and see if I can replicate the issue locally.

**Comment by bishgop** [comment]
@WPDevHQ Firstly, thanks much for making time; I really appreciate it.

Actually, I wanted to use the child theme to keep my site safe from parent theme upgrades; WooCommece will be independent of any theme that I use, as I want to have Shop section in my site. If I remove all the files as you said, won't it change the look and feel of the site?

Please find attached the JSON files - I am not sure if I have done it the right way!
- 
[bishgop_wp1.zip](https://github.com/pojome/elementor/files/483029/bishgop_wp1.zip)
[information_schema.zip](https://github.com/pojome/elementor/files/483030/information_schema.zip)

**Comment by WPDevHQ** [comment]
No problem :) 

Sorry didn't make myself clear on the json file. What I'm looking for is the template you created in Elementor for this page: http://www.littlebighappiness.in/

If you go in to the Elementor editor and click on the folder icon at the bottom left it will give you the option to save the template. Save and exit the editor. Then go to Dashboard >> Elementor >> My Library and hover over the template you save - you will see the option to export template. That's the file I need :) 

P.S. You can edit the above and remove those zip files!

**Comment by bishgop** [comment]
Oh! Here it is.

[elementor-746-2016-09-20.zip](https://github.com/pojome/elementor/files/483080/elementor-746-2016-09-20.zip)

**Comment by WPDevHQ** [comment]
OK had a look at all things and don't see any anormalies on my setup.

I can take a look from your side if you are still ok with giving access. Find me on Facebook, Twitter or email zulfnore @ hotmail.co.uk (Zulfikar Nore)

**Comment by bishgop** [comment]
Thank you Zulfikar. I want the issue resolved because I have not been able to make any progress setting up my site due to this issue.

I just followed you on Twitter from my account @ohmycork.

**Comment by WPDevHQ** [comment]
@bishgop follow @WPDevHQ on twitter instead of @zulfnore - I'm always on the first one!

**Comment by bishgop** [comment]
Sure. I just did that.

**Comment by bishgop** [comment]
Can you help me fix that issue?

@arielk 
Now a new issue with Elementor: page edits are not showing any change after saving!

**Comment by WPDevHQ** [comment]
I can take a look for you yes.

DM the details on twitter or email me

**Comment by arielk** [comment]
Is this issue still needs further handling?
Feel free to reopen the issue and we'll be happy to help you further.

**Comment by bishgop** [comment]
Sure.

I have resolved the issue.

**Comment by arielk** [comment]
@bishgop excellent!

**Comment by VasiLucky** [comment]
How you fixed it??????????

**Comment by VasiLucky** [comment]
ok, I fix it, in my case was double function "the_content();"

**Comment by Assiad95** [comment]
I have the same problem of duplicating Elementor pages, and I have no idea how to fix this issue!
only pages that I build with elementor it's duplicated!

@VasiLucky sorry could you please explain more how did you fix it?

**Comment by saveedshah** [comment]
how you guys fixed it i am facing same issue please help!

**Comment by saveedshah** [comment]
> OK had a look at all things and don't see any anormalies on my setup.
> 
> I can take a look from your side if you are still ok with giving access. Find me on Facebook, Twitter or email zulfnore @ hotmail.co.uk (Zulfikar Nore)

Hi please help me i am facing same issue

**Comment by sarvesheb** [comment]
This issue is still happening. Everything looks fine while editing. But when I preview the page or even directly visit the corresponding page link, the entire site content is repeated 3 times.

**Comment by sarvesheb** [comment]
@arielk Kindly reopen the issue

**Comment by saveedshah** [comment]
> This issue is still happening. Everything looks fine while editing. But when I preview the page or even directly visit the corresponding page link, the entire site content is repeated 3 times.

just change the theme this will solve this problem

**Comment by sarvesheb** [comment]
> > This issue is still happening. Everything looks fine while editing. But when I preview the page or even directly visit the corresponding page link, the entire site content is repeated 3 times.
> 
> just change the theme this will solve this problem

I have tried multiple themes and it's happening on each and every one. Someone suggested OceanWP theme, I have tried it on that as well, still the same.

**Comment by LuckyJocker** [comment]
> > > This issue is still happening. Everything looks fine while editing. But when I preview the page or even directly visit the corresponding page link, the entire site content is repeated 3 times.
> > 
> > 
> > just change the theme this will solve this problem
> 
> I have tried multiple themes and it's happening on each and every one. Someone suggested OceanWP theme, I have tried it on that as well, still the same.

I have the same issue. Now I have fixed it. I deactivated a plugin in my web (Own is Paperlayer Plugin). I think you can solve it by deactivated one by one plugin and load the web to find out the conflict plugin.

**Comment by rvadhvana** [comment]
I have the same issue , can someone answer it how to fix it ?

**Comment by gameofjones117** [comment]
I am also having the same issue with my site. However, it is only some of my pages that repeat and not all of them. Here is the link for my site. I went back and disabled plugins 1 by 1 and determined that it is elementor that is causing the issues.
https://ballthingsandwheretofindthem.com/
@WPDevHQ @saveedshah

**Comment by alcapri** [comment]
> Is this issue still needs further handling? Feel free to reopen the issue and we'll be happy to help you further.

Hello, I am having the same problem, but I cannot see the answer.... could you describe how did you solve it please?

**Comment by scanansee** [comment]
Same issue. Page repeating 3 times...any video link on how to fix this issue? Please share. Thanks

**Comment by scanansee** [comment]
Just found out the solution.

1)  I install new theme from elementor, link here https://elementor.com/products/hello-theme/
2) I activate the installed elementor theme.
3) I disabled all Pagelayer, Pagelayer Pro and PopularFX Website Templates plugin.
