### ISSUE TITLE
Single Post Featured Image Widget Caption should not be included

### ISSUE THREAD

**Issue by cavalierlife** [pojome/elementor#5770]
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

When using the Single Post Featured Image Widget to create a single post template, the Caption field doesn't make sense there. It expects text to be input such as "This is my caption". But the whole point of this widget is to be dynamic, and entering anything into the caption field results in the same caption being displayed under every post's Featured Image. I think the caption field should be removed from the widget.

**Comment by MaxZiebell** [comment]
Here is a temporary fix using a custom shortcode for anybody in need and with a bit of coding experience. 

Put this in your functions.php (best you have a child theme

`
function output_featured_image_caption_func( $atts ) {
	if ( $caption = get_post( get_post_thumbnail_id() )->post_excerpt )
		return '<p class="caption-fix">'.$caption."</p>";
}
add_shortcode( 'output_featured_image_caption', 'output_featured_image_caption_func' );
`
Now add a shortcode in your single page template and add 
`[output_featured_image_caption]`

To style your caption use custom CSS on the class "caption-fix"

**Comment by amindiary** [comment]
@MaxZiebell Thank you for hack.

+1 I have this issue too! caption field must be dynamic, or , simply allow using dynamic tags (featured image caption / title / alt description)

![image](https://user-images.githubusercontent.com/2544046/46071835-9b00c780-c189-11e8-9583-992ee7f29cc2.png)

**Comment by amindiary** [comment]
My solution for this. if someone needs it.
```
add_action('elementor/widget/render_content', function( $content, $widget ) {
  
    if ('theme-post-featured-image' === $widget->get_name()) {
        $settings = $widget->get_settings();

           $caption=get_the_post_thumbnail_caption(get_the_ID());
            $content .= '<figcaption class="widget-image-caption wp-caption-text">' . $caption . '</figcaption>';
      
    }

    return $content;
}, 10, 2);
```
need to add in **functions.php**
and renders image caption

**Comment by mylimoproject** [comment]
Can anyone provide a solution for dedicated image alt tags? I've been looking for a solution and it looks like Elementor deprecated this function (closed ticket #1053). 
My issue is that the same image is used over and over again for "Vehicle Types" block in different pages and I need to have a different item ALT Tag for every page/post the image is used-on for SEO reasons.

This is for a nationwide limo service and on every city page (i.e NYC, Miami, Los Angeles, Chicago, etc..), there is a vehicle fleet gallery and what I need to do is to add the city name either at the beginning or end of alt tag (i.e. Miami limo Service, Chicago Black Car Services, Sprinter Van Hire Manchester).

example => https://airportspickup.com/miami-airport-car-service-naples-florida-limo-service-mia-taxi-rsw-shuttle/#Vehicle-Types

**Comment by black-eye** [comment]
+1

**Comment by sillestadtkowsky** [comment]
Hi,
is it possible to add the caption to the respective image of the post widget as well?
Similar to the example from here: https://github.com/elementor/elementor/issues/5770#issuecomment-424848710

greetingxxx from Germany.

**Comment by sriramgroot** [comment]
> My solution for this:
> 
> ```
> add_action('elementor/widget/render_content', function( $content, $widget ) {
>   
>     if ('theme-post-featured-image' === $widget->get_name()) {
>         $settings = $widget->get_settings();
> 
>            $caption=get_the_post_thumbnail_caption(get_the_ID());
>             $content .= '<figcaption class="widget-image-caption wp-caption-text">' . $caption . '</figcaption>';
>       
>     }
> 
>     return $content;
> }, 10, 2);
> ```
> 
> need to add in **functions.php** and renders image caption


@temsool  Whether this works for "featured image" widget in elementor pro ?
