### ISSUE TITLE
Form submission issue - Refreshes page instead of submitting form

### ISSUE THREAD

**Issue by kalenaf** [pojome/elementor#5773]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
         -----> Updated on our dev site to test the issue, still experiencing it. 

## Description

I am experiencing an issue on one of our sites https://countableaction.com where one of our forms is not properly being submitted and instead it just refreshes the page. There are two forms on most of the page and the first form (red get started button) is working properly, while the second one (blue get started button) is refreshing the page instead of sending off the information. 

## Steps to reproduce

On any page (i.e. the homepage [https://countableaction.com](url)) enter an e-mail and press "get started" on the form at the bottom of the page.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/43250598/45779760-c37c4500-bc10-11e8-80b6-39afd91239fe.png">

Instead of submitting the form the page just refreshes.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Also to note: This bug only happens on the live site, when trying out the forms in "Edit in Elementor" they function properly and I receive e-mail conformation 

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.40
	PHP Version: 5.6.38
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://countableaction.com
	Home URL: https://countableaction.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.4.8
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

== Active Plugins ==
	Addendio PLUS
		Version: 1.1.1
		Author: Addendio

	BackupGuard Pro
		Version: 1.1.25
		Author: BackupGuard

	Broken Link Checker
		Version: 1.11.5
		Author: Janis Elsts, Vladimir Prelovac

	Devices for Elementor
		Version: 1.0.4
		Author: Namogo

	Duplicate Page
		Version: 2.7
		Author: mndpsingh287

	Elementor
		Version: 2.2.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.8
		Author: Elementor.com

	Featured Video Plus
		Version: 2.3.3
		Author: Alexander Höreth

	Google Analytics
		Version: 2.1.4
		Author: ShareThis

	Header and Footer Scripts
		Version: 2.1.0
		Author: Digital Liberation

	Header Footer Code Manager
		Version: 1.0.6
		Author: 99robots

	Mailchimp Forms by Optin Cat
		Version: 2.2.1
		Author: Fatcat Apps

	Ocean Extra
		Version: 1.4.26
		Author: OceanWP

	Ocean Sticky Header
		Version: 1.0.5
		Author: OceanWP

	Onclick show popup
		Version: 7.3
		Author: Gopi Ramasamy

	Page Builder by SiteOrigin
		Version: 2.8.2
		Author: SiteOrigin

	Page Templater For Elementor
		Version: 1.2.5
		Author: ThemeIsle

	PixelYourSite
		Version: 5.3.2
		Author: PixelYourSite

	Popup Maker
		Version: 1.7.30
		Author: WP Popup Maker

	Popups, Lead Forms, Surveys, Live Chats WordPress Plugin - GetSiteControl
		Version: 2.2.3
		Author: getsitecontrol

	SG Optimizer
		Version: 4.0.7
		Author: SiteGround

	SiteOrigin Widgets Bundle
		Version: 1.12.1
		Author: SiteOrigin

	Use Any Font
		Version: 4.9.2
		Author: Dinesh Karki

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WP Reroute Email
		Version: 1.3.4
		Author: Sajjad Hossain

	WP Rocket
		Version: 2.10.10
		Author: WP Media

	Yoast SEO
		Version: 8.2
		Author: Team Yoast

== Debug ==
	Errors: 
		ReferenceError: Can't find variable: imagesLoaded
			at https://countableaction.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.1.8 - 2:30540
			2018-09-19 20:11 +00:00
			x 56 times

		ReferenceError: imagesLoaded is not defined
			at https://countableaction.com/wp-admin/post.php?post=2613&action=elementor - 1:157981
			2018-09-18 18:46 +00:00
			x 2 times

		ReferenceError: Can't find variable: imagesLoaded
			at https://countableaction.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.1.8 - 2:30540
			2018-09-18 18:45 +00:00
			x 3 times

		ReferenceError: imagesLoaded is not defined
			at https://countableaction.com/wp-admin/post.php?post=2613&action=elementor - 1:157981
			2018-09-18 16:47 +00:00
			x 4 times

		ReferenceError: imagesLoaded is not defined
			at https://countableaction.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.1.8 - 2:30528
			2018-09-18 01:10 +00:00
			x 14 times

		ReferenceError: imagesLoaded is not defined
			at https://countableaction.com/wp-admin/post.php?post=2613&action=elementor - 1:157981
			2018-09-17 20:12 +00:00
			x 2 times

		ReferenceError: imagesLoaded is not defined
			at https://countableaction.com/wp-admin/post.php?post=4370&action=elementor - 1:157981
			2018-09-17 18:52 +00:00
			x 2 times

		ReferenceError: imagesLoaded is not defined
			at https://countableaction.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.1.8 - 2:30528
			2018-09-17 18:43 +00:00

		ReferenceError: imagesLoaded is not defined
			at https://countableaction.com/wp-admin/post.php?post=6450&action=elementor - 1:157981
			2018-09-16 15:47 +00:00

		ReferenceError: imagesLoaded is not defined
			at https://countableaction.com/wp-admin/post.php?post=6433&action=elementor - 1:157981
			2018-09-16 15:36 +00:00

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
