### ISSUE TITLE
Elementor CSS file of inside page is not loaded

### ISSUE THREAD

**Issue by shiran1989** [pojome/elementor#5774]
Hello,
I am using the newest version of **Elementor**.
I have an issue with loading pages from the navigation.
if i refresh a single page -> everything is ok . but the css file that this page generates is only for the current page.
if i pass to another page in the navigation menu - > the css of the old page stays and the new page css is not loaded (only if i refresh it)

I don't know if I am doing something wrong because I am new at this.
will appreciate your help. 
Thanks

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
