### ISSUE TITLE
CSS BUG IN GRID Elements

### ISSUE THREAD

**Issue by ElchananLevavi** [pojome/elementor#5776]
The elementor-grid-item class is set the width of column to 50%/33.3% (accordding to the number of columns that chosen), and it's break down the layout, cause the parent element (elementor-posts elementor-grid) has also set the columns:
    grid-template-columns: repeat(3,1fr);
    display: grid;
The frontend-rtl-min.css is the guilty. Its contain the css to both of the elments.
The view is good when the width of any column (Every <ARTICLE> tag) is 100%, but now I need to set it manualy In Custom CSS.

Elementor - 2.2.3
Elementor Pro - 2.0.16
I cleared chece & all the other ordinary things...

First image: The bug.
![-](https://user-images.githubusercontent.com/43437749/45816963-ec223e80-bce5-11e8-8931-4b0684b0f33a.png)

Second image: How it shuld look like.
![- 2](https://user-images.githubusercontent.com/43437749/45817020-1b38b000-bce6-11e8-8e79-f04c483d26ba.png)

**Comment by arielk** [comment]
Can you share with us a link to this page or steps to reproduce this situation?

**Comment by ElchananLevavi** [comment]
Grid of 2 col.
http://www.nura-cooking.co.il/
Grid of 3 col.
http://www.nura-cooking.co.il/%D7%9E%D7%AA%D7%9B%D7%95%D7%A0%D7%99%D7%9D/

They now fixed by writing custom css, but in the DevTool you can see the wrong styles that Elementor pro Manufactured.
Thanks!

**Comment by arielk** [comment]
Please update Elementor Pro to the last version v2.1.9 and after that go to Elementor > Tools > Regenerate CSS,

Thanks
