### ISSUE TITLE
Meta Field values disappear if Elementor is updated

### ISSUE THREAD

**Issue by Bhuvaneswari96** [pojome/elementor#5777]
In Custom Post Type, I have created a Metafield (Example: Name)  where the editor area i use is Elementor.
I added my Title, Featured image and metafield and published the CPT post and all the details were present. But after selecting "Edit with Elementor" added my contents and selected update. When i returned to WordPress Backend of the post I noticed my metafield value became NULL. Can anyone tell why the metafield value disapears and a solution for it.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
