### ISSUE TITLE
Delay of elements but no space

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#5780]
Hello guys,

I know it is possible to insert an element with delay where the delay time I can determine as I want in milliseconds, just like I did on this page:

On the page, I inserted an element below the video with a delay of 10 seconds, and it appears normally. Perfect.
However, before the element appears, it shows an empty space that is reserved for the element to appear. And the size of that empty space is the size of the element that will appear.

But the correct thing would be to have the possibility of not appearing this space. Then, in the case of the test page above, when loading the page, the video would appear and just below, along with the video, would appear the footer element (gray and white color). And after 10 seconds, the delay element, when appearing, would push the footer down.

I've seen this schema in other builders, so I know this is possible.

I leave here the suggestion for you.

Thank you.
Rodrigo Carlos

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
