### ISSUE TITLE
Change control type of an existing widget (pro)

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5785]
I need more flexible content for Slide widget in elementor pro. 
So I had to create a custom plugin and custom widget, copy the whole widget code to just be able change one line

```
$repeater->add_control(
			'description',
			[
				'label' => __( 'Description', 'elementor-pro' ),
				'type' => Controls_Manager::TEXTAREA,
				'default' => __( 'I am slide content. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.', 'elementor-pro' ),
				'show_label' => false,
			]
		);
```

I mean change the `'type' => Controls_Manager::TEXTAREA,` to `'type' => Controls_Manager::WYSIWYG,`

my question is, isn't there any easier way to do this? like filter or any hook?
I read documentation [here](https://code.elementor.com) but I was not successful to achieve this.
any idea how can make this?

I need this be HTML editor so I can put images / videos etc there. also I tried many 3rd party plugins, so many time wasted and nothing good found.

![image](https://user-images.githubusercontent.com/2544046/45915227-8efbc980-be5a-11e8-8fe3-e4114f1ad10d.png)

**Comment by bainternet** [comment]
@amindiary 

There is a way to update a control via the API and its the [update_control](https://code.elementor.com/methods/elementor-controls_stack-update_control/) method.

there are a few places in the Pro version where we use it and there are a few examples here: [`update_control search`](https://github.com/pojome/elementor/search?q=update_control&type=Issues)

**Comment by sebinievas** [comment]
@bainternet how can we add a control to a repeater field? For example, I'm trying to add a simple `tab_id` text field to each tab from the core `tabs` widget so that I can use a custom hash to focus on for readability.

Any help here much appreciated!

**Comment by Ragapriyaait** [comment]
Hello team,
How can we change the default custom_id(ID) dynamically?

I have added new select field inside the advanced tab, i  need to send Custom_id value based on select field value,

attached screenshot for reference can any have any idea please share,


https://prnt.sc/117acdm
