### ISSUE TITLE
before_render after_render widget/column Issue in Backend Editor

### ISSUE THREAD

**Issue by sagarpatel124** [pojome/elementor#5786]
We are adding one function for each widget. Which works properly using before_render and after_render functionality. 

It has one default wrapper which is just one Div. We need to have multiple div so We have added above and closed them using after render. All works fine. Works in Frontend too.

**ISSUE: We have an issue to make them working at the backend. I mean in the editor. We want it to work it there, So users can view the while update. As It's main functionality of Elementor.** 

_Note: Wrapper Div works fine even in the backend/editor. Just that extra div(s) are not working._ 

**We have the same question for a column.**

Link We have used as a reference : https://code.elementor.com/php-hooks/#elementorelementbefore_section_start

```

add_action( 'elementor/frontend/widget/before_render', [ $this, 'widget_tooltip_before_render' ], 10, 1 );
add_action( 'elementor/frontend/widget/after_render', [ $this, 'widget_tooltip_after_render' ], 10, 1 );


```

**Comment by bainternet** [comment]
@sagarpatel124 

It's not really clear what you are asking, or trying to do.

I can only guess that some of the widgets you are referring to have `_content_template()` method which is used to generate the live preview and you would need to use the `elementor/{$element_type}/print_template` filter https://github.com/pojome/elementor/blob/master/includes/base/controls-stack.php#L1679
