### ISSUE TITLE
[Bug] Image Caption not Respecting the Column Width

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#5787]
Hey guys and gals,

Image speaks for itself! The image caption is overlapping the column, and not wrapping.

![elementor image caption margin](https://user-images.githubusercontent.com/31274564/45920433-e1a9a580-be9b-11e8-99c1-1d653038960f.png)

**Comment by drawcard** [comment]
This isn't a bug as such, it's standard behavior when you have an unbroken word that's too long for the DIV that it's constrained in. There is some CSS you can use on the caption element to force word breaks however:

```css
.foo-bar {
    word-break: break-all;
}
```

 Demo - https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_word-break

**Comment by bainternet** [comment]
@drawcard 

Is correct, 

thanks.
