### ISSUE TITLE
Pass PHP variables to elementor widget (accordian)

### ISSUE THREAD

**Issue by JayHoppy** [pojome/elementor#5791]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I cannot find a way to pass PHP variables (eg a product ID) from my customised PHP snippet into elementor widgets for use inside another PHP snippet - eg. I have an elementor designed page which has columns - the first column contains a PHP snippet loop which displays purchased items, & the second column contains an accordian for each item displayed in the first column. I need each accordian to contain product information for the corresponding item in the first column.

**Describe the solution you'd like**
Being able to pass PHP variables through elementor shortcodes - eg - 
echo do_shortcode('[elementor-template id="1950" product_id="' . $_product->id . '"]');

**Describe alternatives you've considered**
I haven't found an alt solution.

**Additional context**

**Comment by bainternet** [comment]
@JayHoppy 

It's not really clear what you are trying to do, or even what you are asking.

can you provide more details? code snippet mentioned?

**Comment by JayHoppy** [comment]
never mind.... I found a work-around.

**Comment by MrBruno666** [comment]
Dear JayHoppy,
Can you please elaborate on how you solver this?
I am looking for a solution to pass a category name variable down to an elementor widget. I have a wp+woocommerce site + elementor builder, and I would like to display elements in a post gallery, but only in the given product's category. There are hundreds of categories, and the categories are password protected.
Any idean on how I might be able to solve this?

**Comment by JayHoppy** [comment]
Hi MrBruno666,

I solved it with terrible, crappy code! Here's what i did -

   - I created an elementor template which had nothing in it but an empty
   accordian.
   - Then I went into the programmers console in chrome, & copied the outer
   html of the accordian from the page it is on.
   - I could then use the elementor accordian html inside of a PHP snippets
   'snippet' (https://wordpress.org/plugins/insert-php/), & add the extra
   items I needed inside the accordian by using html & PHP to get items from
   the WP database.

Does that make sense? You will need to have some skill in PHP, HTML & CSS
to be able to adjust it to your liking.
Cheers
JayHoppy

**Comment by MrBruno666** [comment]
Hey Jay,
Thank you for your response! Will try to make sense of it with my developer
friend, thank you! :)
Barna

Tűzkő Barnabás - Ügyvezető - GetSmart kft.
-----------------------------------------------------------
Barnabas Tuzko - CEO - GetSmart ltd.

bruno@getsmart.hu
www.getsmart.hu
+3670-1997-445
