### ISSUE TITLE
Sorry the content area was not found

### ISSUE THREAD

**Issue by assadnazar** [pojome/elementor#5794]
hi developers,
I recently installed elementor and i liked it very much. However, I am facing this annoying issue which occurred yesterday and disappeared in the morning.

Here is the scenario, when we first create the page with a template even if it is Elementor Full Width, it loads elementor fine. After I close elementor and re-open it then the error shows up and does not let me edit through elementor.

I have tried clearing cache, using incognito mode and going through frontend, pages and specific page. I also have tried on chrome and firefox.

I am using free version of elementor with self developed theme.

Thanks

**Comment by orvn** [comment]
What does your page template look like? 
Make sure it: 

- Uses the standard Wordpress loop (no custom `WP_Query`)
- Uses the`wp_head` and `wp_footer` actions
- Loads `the_content` within the loop, in your main content element

**Comment by bainternet** [comment]
@assadnazar 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
