### ISSUE TITLE
[Pro] Improve Testimonials widget to allow the use of queries

### ISSUE THREAD

**Issue by ShadowXVII** [pojome/elementor#5797]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I use a custom post type to maintain the list of Testimonials with ACF fields to hold specific details about a testimonial (Company, Job Title, Link Text, Link). Currently there's no way to integrate this to the Testimonial Carousel.

This is a similar issue that faces other Pro widgets which aren't as dynamic (e.g. tabs).

**Describe the solution you'd like**
The Testimonial Carousel should be allowed to use a custom query to display information.

**Describe alternatives you've considered**
Using the Posts or Portfolio widget allows the use of a query to seed contents. Perhaps Testimonials should just be a skin of the "posts" base?

**Additional context**
#5051 was the closest related issue I could find.

**Comment by bainternet** [comment]
should be possible with #4440 

thanks.

**Comment by ShadowXVII** [comment]
Cool that should work for lists.

How about Testimonial Carousel?

**Comment by ShadowXVII** [comment]
Hmm, trying to configure this for the single Testimonial widget;

- The image can't be set dynamically
- The post body/content can't be used as dynamic content field (workaround might be to use acf field for that too)

Am I configuring it wrong?

Can live without these;
- The Link can't be set dynamically
- The link text can't be set either manually or dynamically

**Comment by bainternet** [comment]
@ShadowXVII 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Also, next time, please open a new issue if the issue is closed.

thanks
