### ISSUE TITLE
Server Error pop up

### ISSUE THREAD

**Issue by carasmo** [pojome/elementor#5799]
In the latest version of Elementor, since yesterday, I get this when clicking update. 

<img width="373" alt="screen shot 2018-09-25 at 5 58 55 pm" src="https://user-images.githubusercontent.com/1124594/46045857-edd87180-c0ec-11e8-8446-092d65929c23.png">

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
