### ISSUE TITLE
last update 2.2.4 -> page builder not loading in backend (white screen)

### ISSUE THREAD

**Issue by codeagencybe** [pojome/elementor#5802]
Since update 2.2.4 I'm having a problem with editing pages. 
They just turn completely white only. 

When I check frontend, I can see the below error. 
Notice: Undefined index: _id in /home/runcloud/webapps/molsnv/wp-content/plugins/elementor/core/files/css/base.php on line 661

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by yanmorinokamca** [comment]
I got the same problem with version 2.7.5 and jet-elements 2.1.4 that initialize an Elementor\Repeater() in class-jet-elements-ext-section.php. After adding the controls and all properties like jet_parallax_layout_image, the $repeater_values[$index] is the list of properties, but doesn't contains '_id'. The new line number is on 724.

array_merge( $replacements, [ '.elementor-repeater-item-' . $repeater_values[ $index ]['_id'] ] ),

Using the line with ?? ''
array_merge( $replacements, [ '.elementor-repeater-item-' . ($repeater_values[ $index ]['_id'] ?? '') ] ),
will fix it by removing the notice, and you won't be able to get that bug again (I guess the structure will be cached). Not sure where the _id  should be set (maybe in the editor in JS?)
