### ISSUE TITLE
elementor/editor/before_enqueue_scripts hook priority issue

### ISSUE THREAD

**Issue by Micemade** [pojome/elementor#5806]
Hi there,

When using hook **`elementor/editor/before_enqueue_scripts`** and don't add the priority parameter, the Pro feature Global widget is not registering Pro activation (still showing "Go Pro" message).

Perhaps you should update your documentation on https://code.elementor.com/php-hooks/#elementoreditorbefore_enqueue_scripts to make `add_action` **`$priority`** parameter as required.

Best regards,
Alen

**Comment by bainternet** [comment]
@Micemade 

The hook documented is an Elementor hook and not Elementor Pro hook.

Elementor Pro uses this hook in the Priority it needs and that should not affect any other 3rd party code using the same hook unless that code causes issues, which in my guess is what's going on here.

Also, the `add_action` function is a WordPress native function which we have no control over so we can't really make a parameter required.

thanks.
