### ISSUE TITLE
Gradient background button

### ISSUE THREAD

**Issue by toton333** [pojome/elementor#5818]
Gradient background of buttons is necessary in any modern styling of website. Currently the workaround is making button background 100% transparent and then use the column's gradient background.
Also transition duration doesn't work on gradient background on hover.
So a gradient button background and transition effect on gradient background(ofcourse gotta use alternative way, as it is not supported atm) would set elementor on a pretty high level from the rest.

**Comment by arielk** [comment]
Duplicate of #3142
