### ISSUE TITLE
[Feature Reguest] Responsive Alignment for Share Buttons

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#5821]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Sometimes you need to align share buttons differently on desktop and mobile. 

Example: footer of a post detail.
- on a large screen I have 2 separate columns for author and social icons 
- on a mobile the columns are stacked on each other 
- on a large screen I want the buttons right aligned, on a mobile centered.

**Describe the solution you'd like**
Add responsive options for alignment, same way as for e.g. Headings.

**Describe alternatives you've considered**
Custom CSS: not very user friendly

**Comment by arielk** [comment]
We just released an update for this issue, please update to v2.1.10

Thanks for your feedback!
