### ISSUE TITLE
Widget works only after refreshing the page.

### ISSUE THREAD

**Issue by Dizi7** [pojome/elementor#5823]
Hello!
Now I'm doing a widget with an OWL carousel. I have a problem. In the editor, when I add a widget with the OWL carousel, it does not appear and the script itself does not work.
After updating the page in the editor, the carousel works. But after moving the carousel to another block Elementor, it does not work again. What could be the problem?

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* System info.
