### ISSUE TITLE
Additional Dynamic Options or PHP Hook for Button Widget

### ISSUE THREAD

**Issue by katart** [pojome/elementor#5824]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm working on a Single Post Template within Elementor Pro and came across the need to include a Next Post link. I know there is a Next Posts Link Widget (notice the difference between "Next Post" and "Next Posts"), but I want a single button to only go Forward through the posts and NOT Backward (or previous).

**Describe the solution you'd like**
I believe there are 3 possible solutions... 1. Create a Next Post Widget, or 2. Add a Next Post dynamic option to the existing Button Widget Links control, or 3. create a PHP hook that allows developers to hook into the Button Widget controls (like the Link control).

**Describe alternatives you've considered**
Currently, I created a [next-post] shortcode and inserted it into the page via the Shortcode Widget.

**Additional context**
N/A

**Comment by bainternet** [comment]
@katart 

> 1. Create a Next Post Widget

A better option here would be to add a control to hide perv/next links of the "Post Navigation" widget. which curently can be done via CSS.

> 2. Add a Next Post dynamic option to the existing Button Widget Links control

You can create the dynamic tag yourself following the guide "[Dynamic tags](https://developers.elementor.com/dynamic-tags/)".

> 3. create a PHP hook that allows developers to hook into the Button Widget controls (like the Link control).

There are already hooks in place for you to modify the widget output, eg:
[`elementor/widget/render_content`](https://code.elementor.com/php-hooks/#elementorwidgetrender_content)

thanks.
