### ISSUE TITLE
Remove form_fields[] from field name?

### ISSUE THREAD

**Issue by besweeet** [pojome/elementor#5825]
When using a webhook to post to Jotform, I need the field names to match up with what is on Jotform as those cannot be adjusted. For example, a Jotform field has the name of q3_name. In my Elementor form, the full field name is form_field[name]. Can form_field and the brackets be removed?

I attempted this myself by modifying form-base.php, but the form acts as though nothing is entered into the fields. Perhaps validation also has to be updated to accommodate the updated field name?

**Comment by bainternet** [comment]
@besweeet 

You can't remove the `fields` array using the native webhook.
What you can do is create a just webhook and post the data however you want/need to any service like Jotform.

eg:
```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
		'body' => $fields,
	]);
});
```

**Comment by besweeet** [comment]
@bainternet - I saw that code elsewhere, added it to my functions.php, replaced MY_FORM_NAME with the name of the form, replaced HTTP://YOUR_WEBHOOK_URL with the POST address of Jotform and nothing changes.

**Comment by besweeet** [comment]
@bainternet Any ideas?
