### ISSUE TITLE
Placeholder text for SELECT element

### ISSUE THREAD

**Issue by scott8035** [pojome/elementor#5828]
It would be most aesthetically pleasing if we could make dropdown menus with the equivalent of placeholder text...dimmed out, shown by default, not a valid choice upon form submission. See this post for detailed discussion: https://stackoverflow.com/questions/5805059/how-do-i-make-a-placeholder-for-a-select-box

I think this is a duplicate of [#4748](https://github.com/pojome/elementor/issues/4748) but that was closed stating it would be available in Pro 2.1.0...Pro is now at v2.1.9.

**Comment by bainternet** [comment]
@scott8035 

This is already possible using "[Custom Labels & Values](https://docs.elementor.com/article/371-custom-labels-and-values-in-the-form-widget)" where the first label is the place holder and the value should be left empty. eg:

```
Placeholder|
Label One|value1
Label Two|value2
```

**Comment by maynor96** [comment]
> @scott8035
> 
> This is already possible using "[Custom Labels & Values](https://docs.elementor.com/article/371-custom-labels-and-values-in-the-form-widget)" where the first label is the place holder and the value should be left empty. eg:
> 
> ```
> Placeholder|
> Label One|value1
> Label Two|value2
> ```

It is right!
