### ISSUE TITLE
Automatically switch off coming soon or maintenance mode by timer.

### ISSUE THREAD

**Issue by stebla27** [pojome/elementor#5829]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Currently it's possible to design a coming soon page with a countdown timer. But it would be also nice if the coming soon mode will be switched off automatically when the countdown has finished. So the admin does not have to switch off it manually.
It's especially useful for coming soon pages.

**Comment by bainternet** [comment]
I merged this issue with  #2687, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
