### ISSUE TITLE
Responsive Alignment for Add to Cart Button Doesn't Work

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#5830]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The title and the picture below, says it all. When I use an alignment for a desktop, the lower settings are not working. Strangely enough, it happens the other way around as well: when I select the alignment for a mobile, the higher settings don't work either. I'm not sure about the mechanism here, but it seems that the first selected, takes it all. 

![obrazek](https://user-images.githubusercontent.com/5634870/46247974-699b2c80-c413-11e8-9b7f-afa0fcfe9e36.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@black-eye 

Thanks for reporting a fix should be released next version.

**Comment by arielk** [comment]
We just released an update for this issue, please update to v2.1.10

Thanks for your feedback!
