### ISSUE TITLE
New pages created with elementor are not added to the "pages" section of the wordpress admin panel

### ISSUE THREAD

**Issue by jazir5** [pojome/elementor#5831]
I don't know why this is happening or how to fix it. Help would be appreciated.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
