### ISSUE TITLE
Rate request alert in dashboard

### ISSUE THREAD

**Issue by reardestani** [pojome/elementor#5832]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I'm getting this alert (http://take.ms/pBN8r) in dashboard after every reload. Note of the actions button dismiss it forever. Already rated but I am considering to change it to 1 star because of this annoying alert.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@reardestani 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
