### ISSUE TITLE
Show Padding and Margin Box as dashed box like Content Box

### ISSUE THREAD

**Issue by anthonypero** [pojome/elementor#5834]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Using the Edit Pane to adjust Margin and Padding can be cumbersome and time-consuming. Its also not immediately apparent when looking at the Preview screen how much padding and margin has been applied to a content box.

**Describe the solution you'd like**
It would be a better user experience to provided a dotted box demonstrating the padding and the margin on hover, like you do for the content box. I would suggest using the same conventions as the Chrome Inspector and make the padding box border green and the margin box border red/orange. Furthermore, it would be awesome if we could change the padding and the margin by dragging on green or red border to increase or decrease padding and margin.

**Comment by alpha-leonis** [comment]
I had a similar idea recently, I think they will merge you too to the same issue :)

**Comment by anthonypero** [comment]
My search-fu skills must be erroding :)

**Comment by bainternet** [comment]
I merged this issue with  #5018, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
