### ISSUE TITLE
Drop shadow on hover

### ISSUE THREAD

**Issue by knobless** [pojome/elementor#5836]
It could be cool if i could change the shadow while im hovering elemnts.
Think about this one: image while im hovering it has a growing up and i could add a bigger shadow while hovering it could give the floating feeling to it.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
