### ISSUE TITLE
[Feature Request] Copyright Disclaimer in Footer

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#5840]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Please allow for adding a 'Copyright' disclaimer in the footer. It's something supported by the GeneratePress theme (as an example), but when using a native Elementor footer, it removes this feature.

**Describe the solution you'd like**
Similar to GeneratePress [screenshot attached]

![copyright feature](https://user-images.githubusercontent.com/31274564/46350353-79ea1c00-c64c-11e8-9cdf-e44c50f97589.png)

**Comment by bainternet** [comment]
@enviedbymost 

You can do that with Elementor Pro using A footer Template.

thanks.

**Comment by enviedbymost** [comment]
How lol? I don't see anywhere in Elementor to do this, nor a tutorial on it.
