### ISSUE TITLE
ACF outputting Label, not value

### ISSUE THREAD

**Issue by mskks64** [pojome/elementor#5841]
When creating a select field you can specify both a value and label like this:
red : Red

However Elementor does not output the value, it is outputting the label.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
