### ISSUE TITLE
How to re-init frontend?

### ISSUE THREAD

**Issue by TheoKoenig** [pojome/elementor#5843]
Hello, I would like to load my website's pages with PJAX (with barba.js for example) but I don't know how to re-init all the scripts from Elementor's frontend when my new PJAX content is loaded. Obviously my whole page is broken without re-initializing the scripts...
What can I do? Thanks !

**Comment by bainternet** [comment]
@TheoKoenig 

Currently, this feature is not supported, nor is it a quick "Fix" to implement,but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by wayheming** [comment]
+ 1

**Comment by seriusokhatsky** [comment]
Hi,

This option is vital for me. Will you consider adding it in the nearest future? We need to use elementor interface for custom post types like "HTML Blocks" and display them in different places like menu dropdowns for example.

Regards

**Comment by MrBushid0** [comment]
Is there any update on this? Is it being considered or will it never see the day?

Please add this feature! 

It would be a game changer if we can implement barbajs on sites built with Elementor. Other than cool page transitions, from an agency perspective that also host clients websites, using PJAX will reduce the load on our servers, which equates to faster sites and $$$$ of savings for us. 

Best regards

**Comment by nickmadedesign** [comment]
Has anyone had success with this yet?

Other WP sites in the wild are using Barba.js w/their own respective themes.

**Comment by LaConfiserie** [comment]
Hi !
Some news for the possibility to use Elementor with Barba.js ?

**Comment by dngraphisme** [comment]
Hello 8

Please make barbajs compatible elementor ....

**Comment by songyingg** [comment]
Hi, Everybody

I had a problem with compatibility between barba.js and elementor page builder.
Is there any person who can help this problem?

Thanks

**Comment by maxjutras** [comment]
+1 for barba

**Comment by drawcard** [comment]
I would love to be able to use Elementor + Barba.js to create an SPA like frontend for websites while having the ease of use of a page builder in the backend. Adding my +1 to this.

**Comment by balapa** [comment]
Hey, I also need this feature

**Comment by webkonditorei** [comment]
I’m also interested in this feature!

**Comment by Pistil-Studio** [comment]
Need this :)

**Comment by Afplaktape** [comment]
Still needed!

**Comment by ArekZw** [comment]
+1

**Comment by gitgudcameron** [comment]
+1

**Comment by rossib94** [comment]
+1 I'm trying to integrate my site with Swup.js and having similar issues. Swup has a plugin option for reloading scripts. However, when all scripts are reloaded it causes issues. I just need to know which scripts to reload. Swup will take care of the actual process.
My post:
#10798

**Comment by jazir5** [comment]
+1, this would be great to have

**Comment by indurango** [comment]
I also want to use page transitions with Elementor Pro but since I am not a coder its very difficult to use JS libraries with WP + Elementor. You should add page transition effect feature to Elementor pro when there are so many themes already started to use them. 

Is there any one who can help whether it is possible to add page transitions to Elementor Pro website ? I tried the plugin Page Transition that uses animisition but it conflicts with pop-ups and breaks pop-up links.

**Comment by drawcard** [comment]
I've used this guide in the past to set up a basic transition handled by the theme: https://webdesign.tutsplus.com/tutorials/how-to-integrate-smoothstatejs-into-a-wordpress-theme--cms-26610

You will need intermediate to advanced knowledge of HTML / CSS / JS to achieve this however.

**Comment by TheoKoenig** [comment]
> I've used this guide in the past to set up a basic transition handled by the theme: https://webdesign.tutsplus.com/tutorials/how-to-integrate-smoothstatejs-into-a-wordpress-theme--cms-26610
> 
> You will need intermediate to advanced knowledge of HTML / CSS / JS to achieve this however.

@drawcard I don't think you understand the actual request. This ticket is about a way to re-init Elementor's scripts, not how to set-up AJAX page transition... But still, thanks for the guide.

**Comment by drawcard** [comment]
@TheoKoenig I was responding to @indurango

**Comment by TheoKoenig** [comment]
> @TheoKoenig I was responding to @indurango

@drawcard Ok thanks! 😌 Unfortunately, that will not work (at the time of writing). See my original post

**Comment by aryan3650** [comment]
+1 Barba.js + Elementor

**Comment by hubertq** [comment]
+1 for barba.js

**Comment by doruradu** [comment]
+1 for barba.js

**Comment by gitgudcameron** [comment]
For those of you wanting to get Barba.js working with Elementor, I finally figured out how to make it work 🎉. 

I spent way too long on this, and i'm sure there are ways to improve on it but I put together a [quick guide](https://thisisadvantage.com/page-transitions-using-barba-js-wordpress-elementor/) on how we pulled it off incase it's helpful to anyone. This covers how to get Barba.js working with Elementor, Gravity Forms and Sage ✌️

**Comment by TheoKoenig** [comment]
> For those of you wanting to get Barba.js working with Elementor, I finally figured out how to make it work 🎉.
> 
> I spent way too long on this, and i'm sure there are ways to improve on it but I put together a [quick guide](https://thisisadvantage.com/page-transitions-using-barba-js-wordpress-elementor/) on how we pulled it off incase it's helpful to anyone. This covers how to get Barba.js working with Elementor, Gravity Forms and Sage ✌️

Looks promising! Thank you for sharing your approach 👌🏻 I'm hopeful that Elementor will support that kind of transitions in the near future.

**Comment by gitgudcameron** [comment]
Same @TheoKoenig. This approach is far from perfect so it would be amazing if Elementor could support this.

**Comment by maxjutras** [comment]
> For those of you wanting to get Barba.js working with Elementor, I finally figured out how to make it work 🎉.
> 
> I spent way too long on this, and i'm sure there are ways to improve on it but I put together a [quick guide](https://thisisadvantage.com/page-transitions-using-barba-js-wordpress-elementor/) on how we pulled it off incase it's helpful to anyone. This covers how to get Barba.js working with Elementor, Gravity Forms and Sage ✌️

Great job. It's a great starting point. 
Unfortunately, I don't think this would work for anyone using elementor pop-ups, or animations,. Especially with elementor pro. Also, it would breaks the Elementor Pro's menu, especially on mobile.

Wont work neither for anyone using woocommerce, but that's another thing (not related to elementor). 

We're also in the same boat and have hit a brick wall.

**Comment by gitgudcameron** [comment]
> Great job. It's a great starting point.
> Unfortunately, I don't think this would work for anyone using elementor pop-ups, or animations,. Especially with elementor pro. Also, it would breaks the Elementor Pro's menu, especially on mobile.
> 
> Wont work neither for anyone using woocommerce, but that's another thing (not related to elementor).

Yeah true @maxjutras we use GSAP for all our animations so never needed to get this working. You might be able to have some luck by searching the specific Elementor JS/CSS files for popups and animations and adding them to the barba configuration, similar to the Gravity Forms files in my example. We are using an Elementor Pro footer and haven't experienced any dramas yet so I assume it would be the same for headers/menus but i could be wrong.

**Comment by aliboy08** [comment]
+1

**Comment by jpgif** [comment]
We need this !!!!
Would be so amazing to have the ability to fade in, out our content in  a  smooth way!

**Comment by SuperstrongBE** [comment]
+1 for me !

**Comment by SuperstrongBE** [comment]
@gitgudcameron, thank for the quick guide it's perfect ! 
PS: The bonus for sage is priceless for me

**Comment by willryanuk** [comment]
+1. I want to be able to use Elementor within a Single Page Application (SPA).

**Comment by SuperstrongBE** [comment]
@willryanuk after your content is loaded and injected in you page container just call the init method
```
function applyElementorControllers (){

// Important line, because if there is no widget with JS, there is no elementorFrontend instance
if (window.elementorFrontend) return;
// Where the magic hapen
window.elementorFrontend.init() 

}

//Bonus to apply css of the loaded page
 applyViewCss (cssUrl) {

        if (!cssUrl) return;
        const cssNode = document.createElement('link');
        cssNode.setAttribute("href", cssUrl);
        cssNode.setAttribute("rel", "stylesheet");
        cssNode.setAttribute("type", "text/css");
        document.head.appendChild(cssNode);

    }

```

**Comment by SuperstrongBE** [comment]
Hi, i have opened a new feature request for AJAX handling, please comment, vote, share 
https://github.com/elementor/elementor/issues/13252

**Comment by m16averick** [comment]
I found solution, but it is less agressive than frontent init

<script>
	jQuery('.elementor-element').each(function() {

		elementorFrontend.elementsHandler.runReadyTrigger( jQuery( this ) );

	});
	</script>

It triggers every element back to work :) I've put it in my theme, but you can implement it anywhere you like ^^

**Comment by hiviz** [comment]
@m16averick do you mind if I contact you directly? I think your solution is what I'm looking for, but I have some lingering questions. Many thanks!

**Comment by m16averick** [comment]
Ok so every elementor-element has a trigger, which starts its' functions bundle. Feel free to ask questions at my nickname @gmail.com

**Comment by m16averick** [comment]
> @m16averick do you mind if I contact you directly? I think your solution is what I'm looking for, but I have some lingering questions. Many thanks!

Ok so every elementor-element has a trigger, which starts its' functions bundle. Feel free to ask questions at my nickname @gmail.com

**Comment by hiviz** [comment]
> > @m16averick do you mind if I contact you directly? I think your solution is what I'm looking for, but I have some lingering questions. Many thanks!
> 
> Ok so every elementor-element has a trigger, which starts its' functions bundle. Feel free to ask questions at my nickname @gmail.com

Many thanks, have sent you an email!

**Comment by ofmarconi** [comment]
+1

**Comment by acornavi** [comment]
That would be awesome!

**Comment by ofmarconi** [comment]
@loganvenderlic Any progress?
