### ISSUE TITLE
Elementor  Image Carousel picuture size issue

### ISSUE THREAD

**Issue by krann** [pojome/elementor#5850]
When the 'Image Size: Custom' is selected, the source version of the image seems to be the smallest one - so any custom size that is large is very low-res and bitmapped.

It would be better if the user could define the custom size and then choose which version to use (or better still, have Elementor select the most appropriate version for >72dpi resolution).

Secondly, when the  'Image Size: Custom' is chosen - it would be nice to have a 'cropped' checkbox so that all the images are the same size & shape. (You might also want to have a 'cropped vertically and cropped horizontally' options)

The reason is, usually carousel images will always be the same size & shape so the images look neat when the carousel is operating.

Also, I can set the 'min height' of the carousel so I always get the photos buttimg right up to the edge of the box.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
