### ISSUE TITLE
More meta info for posts widget (pro) + More control in style

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5855]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Need to be able to ad tags / categories or even custom meta fields (ACF for instance) there. 

Also, need to be able to set color for hover state of title / meta data

![image](https://user-images.githubusercontent.com/2544046/46497647-d81d2780-c823-11e8-9e37-ee499f010234.png)

**Comment by bainternet** [comment]
Duplicate of #4440
