### ISSUE TITLE
Cannot set template display condition due to JS errors, always display 'All' only

### ISSUE THREAD

**Issue by zbwziete** [pojome/elementor#5858]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

It is not possible to configure template display conditions due to following JS errors:

Uncaught TypeError: Cannot read property 'select2' of undefined
    at n.onReady (editor.min.js:2)
select2.min.js:1 Uncaught Error: No select2/compat/dropdownCss
    at c (select2.min.js:1)
    at h (select2.min.js:1)
    at select2.min.js:1
    at T.apply (select2.min.js:2)
    at new i (select2.min.js:2)
    at new i (select2.min.js:2)
    at HTMLSelectElement.<anonymous> (select2.min.js:3)
    at Function.each (load-scripts.php:8)
    at a.fn.init.each (load-scripts.php:8)
    at a.fn.init.e.fn.select2 (select2.min.js:3)

## Steps to reproduce

1. Create single template
2. Attempt to save it
3. Set display conditions: select "In Category" or any other condition where you should be able to select individual item. The drop down always displays "All" only, it is not possible to select any category, etc.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>				
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10
	MySQL version: 5.5.5
	PHP Version: 5.6.33
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Debug Mode: Inactive

== User ==
	Role: administrator
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.0.8
		Author: Automattic

	Autoptimize
		Version: 2.4.0
		Author: Frank Goossens (futtta)

	Cherry Projects
		Version: 1.2.13
		Author: Cherry Team

	Cherry Services List
		Version: 1.4.6
		Author: Zemez

	Cherry Sidebars
		Version: 1.1.2.4
		Author: Zemez

	Cherry Socialize
		Version: 1.1.3
		Author: Jetimpex

	Cherry Trending Posts
		Version: 1.0.1
		Author: Zemez

	Contact Form 7
		Version: 5.0.4
		Author: Takayuki Miyoshi

	Custom Category Template
		Version: 0.4
		Author: Bainternet

	Customize Admin
		Version: 1.7.4
		Author: Johan van der Wijk

	Custom Sidebars
		Version: 3.2.1
		Author: WPMU DEV

	Duplicate Page
		Version: 2.7
		Author: mndpsingh287

	Elementor
		Version: 2.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.7
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	Jet Elements For Elementor
		Version: 1.13.1
		Author: Zemez

	Loco Translate
		Version: 2.1.5
		Author: Tim Whitlock

	One-Click Child Theme
		Version: 1.6
		Author: tychay

	Quick Featured Images
		Version: 13.3.2
		Author: Martin Stehle

	Recent Posts Widget With Thumbnails
		Version: 6.2.1
		Author: Martin Stehle

	Remove Dashboard Access
		Version: 1.1.3
		Author: Drew Jaynes (DrewAPicture)

	Search Exclude
		Version: 1.2.2
		Author: Roman Pronskiy

	Shortcode Widget
		Version: 1.5.1
		Author: Gagan Deep Singh

	Simple File Downloader
		Version: 1.0.4
		Author: eugenealegiojo

	The Events Calendar
		Version: 4.6.24
		Author: Modern Tribe, Inc.

	The Events Calendar Extension: Calendar Customizer
		Version: 1.0.0
		Author: Modern Tribe, Inc.

	The Events Calendar Extension: Custom Datepicker Start Date
		Version: 1.0.1
		Author: Modern Tribe, Inc.

	The Events Calendar Extension: Instructor Linked Post Type
		Version: 1.0.1
		Author: Modern Tribe, Inc.

	Theme My Login
		Version: 7.0.11
		Author: Theme My Login

	Theme My Login Moderation
		Version: 1.0.2
		Author: Theme My Login

	Theme My Login Notifications
		Version: 1.1
		Author: Theme My Login

	Theme My Login Profiles
		Version: 1.0.6
		Author: Theme My Login

	Theme My Login reCAPTCHA
		Version: 1.0.1
		Author: Theme My Login

	Theme My Login Redirection
		Version: 1.0.1
		Author: Theme My Login

	Theme My Login Security
		Version: 1.1.2
		Author: Theme My Login

	TM Mega Menu
		Version: 1.1.4
		Author: TemplateMonster

	TM Photo Gallery
		Version: 1.1.2
		Author: JetImpex

	Tribe Extension: Dequeque Assets
		Version: 1.0.3
		Author: Modern Tribe, Inc.

	Ultimate Category Excluder
		Version: 1.1
		Author: Marios Alexandrou

	Wordpress Comments Manager
		Version: 1.6
		Author: kn007

	WordPress Social Login
		Version: 3.0.1
		Author: Miled

	WP Ajaxify Comments
		Version: 1.6.0
		Author: weweave UG (limited liability)

	WP All Import
		Version: 3.4.9
		Author: Soflyy

	WP First Letter Avatar
		Version: 2.2.8
		Author: Dev49.net

	WP GDPR Compliance
		Version: 1.4.2
		Author: Van Ons

	WP Mail SMTP
		Version: 1.3.3
		Author: WPForms

	WP Super Cache
		Version: 1.6.4
		Author: Automattic

	Yoast SEO
		Version: 8.3
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property 'select2' of undefined
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13065
			2018-10-04 22:03 +00:00
			x 3 times

		TypeError: this.ui.select2 is not a function
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13058
			2018-10-04 21:26 +00:00
			x 2 times

		TypeError: Cannot read property 'select2' of undefined
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13065
			2018-10-04 21:24 +00:00
			x 2 times

		TypeError: Cannot read property 'md' of undefined
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:170942
			2018-10-04 21:15 +00:00
			x 2 times

		TypeError: Cannot read property 'select2' of undefined
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13065
			2018-10-04 21:09 +00:00
			x 7 times

		TypeError: Unable to get property 'select2' of undefined or null reference
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13050
			2018-10-04 19:57 +00:00

		TypeError: Cannot read property 'select2' of undefined
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13065
			2018-10-04 19:53 +00:00
			x 3 times

		TypeError: n.attributes[t.name].each is not a function
			at /wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:9152
			2018-09-13 21:34 +00:00

		TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
			at /wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=1.15.5 - 2:30300
			2018-08-13 14:54 +00:00

		Error: An "el" #elementor-panel-elements-search-area must exist in DOM
			at /wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:13466
			2018-08-13 12:36 +00:00
			x 2 times
</details>

**Comment by zbwziete** [comment]
I hope for some quick solution, really

**Comment by bainternet** [comment]
@zbwziete 

Glad you figured out it was a conflicting plugin, as for your suggestion, we can't really enforce other 3rd party elementor plugins to "play by the rules" changing the priority is just a patch and what happens when a new plugin uses an even later priority? we would need to the priority again...

thanks anyway.
