### ISSUE TITLE
Compatibility problem with Elementor & Woocommerce composite products

### ISSUE THREAD

**Issue by Webtica** [pojome/elementor#5864]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hello, 

It seems there is a compatibility problem with Elementor & Woocommerce composite products.
When I enable both Elementor & Elementor Pro with Woocommerce composite products all on the latest versions, when I want to edit a single product template i get the Preview Could Not Be Loaded error. Only with the single product template. all others work fine.

Any idea how I can debug this issue more and find a solution? 

Thanks
Dieter

## Steps to reproduce

1. Install Elementor 2.2.4 & Elementor pro 2.1.9 with Composite products 3.13.11
2. Go to Elementor Templates make a single product template and you get the error.

## Isolating the problem
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: 5.5.60
	PHP Version: 7.0.20-1~dotdeb+8.2
	PHP Max Input Vars: 2000
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://smoet.dazzle-qa.be
	Home URL: https://smoet.dazzle-qa.be
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: Smoet Thema
	Version: 1.0.1537346799
	Author: Surepress
	Child Theme: Yes
	Parent Theme Name: Twenty Seventeen
	Parent Theme Version: 1.7
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.7.7
		Author: Elliot Condon

	BackupBuddy
		Version: 8.3.0.0
		Author: iThemes

	Child Theme Configurator
		Version: 2.3.0.4
		Author: Lilaea Media

	Elementor
		Version: 2.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.9
		Author: Elementor.com

	Mollie Payments for WooCommerce
		Version: 4.0.2
		Author: Mollie

	Q2W3 Fixed Widget
		Version: 5.1.4
		Author: Max Bond

	Ultimate Addons for Elementor
		Version: 1.7.3
		Author: Brainstorm Force

	WooCommerce
		Version: 3.4.5
		Author: Automattic

	WooCommerce Composite Products
		Version: 3.13.11
		Author: SomewhereWarm

	WooCommerce Product Bundles Premium
		Version: 3.2.1
		Author: WPclever.net

	WooCommerce Product Filter
		Version: 6.6.0
		Author: Mihajlovic Nenad

	WP All Import - ACF Add-On
		Version: 3.1.9
		Author: Soflyy

	WP All Import - WooCommerce Add-On Pro
		Version: 3.0.4
		Author: Soflyy

	WP All Import Pro
		Version: 4.5.5
		Author: Soflyy


== Debug ==
	Errors: 
		TypeError: Cannot read property 'select2' of undefined
			at https://smoet.dazzle-qa.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13065
			2018-10-06 09:34 +00:00
			x 7 times

		TypeError: Cannot read property 'select2' of undefined
			at https://smoet.dazzle-qa.be/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.3 - 2:13065
			2018-09-19 16:05 +00:00
			x 5 times

				
```
</details>

**Comment by Webtica** [comment]
I enabled WP Debug and got the following output: 

`[06-Oct-2018 10:18:49 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_type() on boolean in /app/public/wp-content/plugins/woocommerce-composite-products/includes/class-wc-cp-display.php:404
Stack trace:
#0 /app/public/wp-includes/class-wp-hook.php(286): WC_CP_Display->add_edit_in_cart_notice('')
#1 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /app/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /app/public/wp-content/plugins/elementor-pro/modules/woocommerce/documents/product.php(138): do_action('woocommerce_bef...')
#4 /app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(218): ElementorPro\Modules\Woocommerce\Documents\Product->print_content()
#5 /app/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(171): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location('single')
#6 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->ElementorPro\Modules\ in /app/public/wp-content/plugins/woocommerce-composite-products/includes/class-wc-cp-display.php on line 404
`

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by Webtica** [comment]
Hi @bainternet ,

I got the following reply from the woocommerce composite product support:

> 
Hey Dieter,

Thanks for reaching out!

We have received similar compatibility issue reports in the past weeks and in most cases when trying to edit Composite single product pages with Elementor Pro, a fatal error was triggered. This error indicates that the code that's displaying the product content is failing to populate the global $product variable, which must exist in all single-product templates.

This is not something we can solve on our side -- we could perhaps add a sanity check there, but the problem is that this error is triggered by code that must be functional. In other words, that variable needs to be populated -- if it's not, then the best thing to do would be (unfortunately) to trigger a fatal error.

Moreover, the reason why this error does not show up with the WooCommerce core products is that WooCommerce does not have any functions attached to the woocommerce_before_single_product action -- Composite Products, however, hooks into this action, since it's the earliest one in single-product templates.

WooCommerce does utilize the global $product variable in the action that runs right after it --woocommerce_before_single_product_summary.

Both are in the same template, and in a default WooCommerce / WordPress setup the global $product variable is already populated long before this template is rendered.

For reference, please take a look at this template: https://cl.ly/d2f6b46d25e9

We would recommend contacting the Elementor Pro developers with this information and hopefully they will be able to provide a fix! :) 

>

**Comment by RomainJM** [comment]
Hi @Webtica and @bainternet,

Exactly the same here. @Webtica Did you find a solution, Elementor team answer you ?

Thanks

**Comment by derweltbuerger** [comment]
I'm experiencing the same issue. Only when trying to create or load a Single Product Template I get one of the following:
- The "Preview Could Not Be Loaded error" or
- Elementor trying to load indefinitely
First it was the former error. Then I updated Elementor and Elementor Pro to the latest version and now it gets stuck loading.

Creating or editing a Product Archive Template, for instance, works fine.

I'm using the following setup:
- Elementor 2.3.2
- Elementor Pro 2.2.0
- WooCommerce Composite Products 3.14.6

Please fix this, Elementor team... Did anyone else find a solution?

Thanks!

**Comment by SampieEls** [comment]
same issue here when i activate WooCommerce Product Bundles... when i deactivate i can edit the single product pages

**Comment by pdunbar** [comment]
Bump!  Having the same issue. Rather for me, the conflict is with the WooComm Product Configurator by Iconic.   

Any updates on the conflict? My error is the same while trying to edit single product templates.  When disabling, it works beautifully.

**Comment by derweltbuerger** [comment]
Can you both report this to support@elementor.com please? They need to be made aware of this issue. I haven't found a solution so far...

**Comment by StudioChevalking** [comment]
Same issue here... I've send an message to Elementor and Woocommerce...

**Comment by SampieEls** [comment]
Thanks @StudioChevalking , i have a new project ridig on this working ;)

**Comment by StudioChevalking** [comment]
…Also on the frontend where some issues. I did not completely test it out but the page I was working on turned white when I put thing into the cart.


Greets Wilfred

> Op 30 nov. 2018, om 19:24 heeft Peter Dunbar <notifications@github.com> het volgende geschreven:
> 
> I did hear from elementor that the plugin can be deactivated, build the
> template, and then turn the plugin back on. Trying today when I get out of
> work to see if it works!
> 
> 
>

**Comment by btrfabrications** [comment]
Same issue here as well, for both Composite Products and Bundled Products (both developed by 'SomewhereWarm').

Seems like you only need to deactivate the plugin(s) in question to load the single product template; you can then reactivate the plugin(s), and edit as normal.

For whatever reason though, the 'Add to Basket' widget/section doesn't display properly on a composite product through Elementor, for me, so I think I'll need to find a different way.

Would be super useful if Elementor/SomewhereWarm/Woocommerce could make their products work with each other properly in future.

**Comment by pdunbar** [comment]
I solved the problem finally!

I switched plugins :).  Check out WP visual product Configurator by
orionorigin. Took a little tweaking but their support was ridiculously
awesome. Live chat on their website.

Way faster help response than waiting on here for a solution.

**Comment by derweltbuerger** [comment]
Hi everyone,

Today I received the following news from Elementor support:

"Sorry for the wait.

The fix has been sent to the beta version of Elementor pro which is already available:
https://github.com/pojome/elementor/issues/6663

The fix will be naturally added to the upcoming version of Elementor pro too which is scheduled for this month.

If you have a staging website to test the beta version let us know if it works fine for you."

The final will probably be released on 21 Jan. Unfortunately I cannot test the beta. Can someone here please test the beta in a staging environment and report whether the fix actually works? The following needs to be tested:

**Is it possible to create or edit a Single Product Template with Elementor (Pro) when WooCommerce Product Bundles or WooCommerce Composite Products plugins, or both, are activated at the same time?**

Please let the rest of us know :) Thanks!

**Comment by btrfabrications** [comment]
Also received that today, but can't yet figure out how to install the beta version to test it.... I've enabled the beta tester setting in elementor tools, but now what? Hopefully Elementor support, or one of you, will get back to me soon so I can check it out!

**Comment by btrfabrications** [comment]
OK, figured it out, just needed to recheck for updates.....sigh.

So far the single product template loads without disabling the composite product or product bundles plugins - great. Though one heading on my main menu is now out of alignment with the rest...weird. 

I'll report back once I've had time to build a basic layout and see what happens.

**Comment by btrfabrications** [comment]
And here's the menu misalignment for what it's worth. Note that the item in question is the only one without a dropdown...

![btr elementor pro 24 beta menu display issue 14012019](https://user-images.githubusercontent.com/44300682/51148097-c270c280-1854-11e9-81c9-d75581b8395e.jpg)

@smile00000 I had noticed issues like that too. Just assumed I'd need to play with settings more, which I hadn't done due to the issues of this thread. Looks like I'll just go back to using Elementor for everything but Woocommerce pages, unless Elementor can get it all under control.

**Comment by smile00000** [comment]
@bainternet elementor support said the following "I have marked the ticket as a feature request and bug report, so our developers can check this and see what we can do to make it looks better."

**Comment by btrfabrications** [comment]
So I've left a comment on the Elementor 2.4 Beta thread (https://github.com/pojome/elementor/issues/6663#issuecomment-455134005) and they requested I start a new thread with the issues, but I really don' have the time to set up the problem - I need to work on other things. Anyone else here seeing the formatting issues in the 'add to cart' section of a composite product, with Elementor 2.4 Beta? And can you take the time to work through it with them?

**Comment by btrfabrications** [comment]
@BestCellular The issue addressed by the EPRO 2.4 Beta update is specifically the single product template not loading with Woocommerce Composite Products and/or Woocommerce Product Bundles (official Woocommerce extensions) active - not necessarily the YITH plugin. The update has meant that the Elementor Pro template editor now loads, so that's something.

However I have issues with the formatting of the 'add to cart' section of composite products, with items lacking padding, etc...and no way to adjust that in the Elementor settings/template. Is that what you mean when you say it still doesn't offer compatibility?

As per my previous post, I highlighted the layout issues to them, and they requested I start a new thread and provided a link to a live site with the issue visible so they can inspect...which I don't have time to do. Maybe you could do that, if you have the time?

**Comment by btrfabrications** [comment]
@smile00000 Yeah, it works with official Woocommerce Composite Products and Product Bundles now.

I still (with beta 4) have the same issues with lack of padding and dropdowns only being half visible in the add to basket section...but I guess that's just me. I can't think what I've got installed, or set, which would be affecting it though. Anyone else seeing this issue? https://github.com/pojome/elementor/issues/5864#issuecomment-454202927

**Comment by btrfabrications** [comment]
@smile00000 I have no idea, sorry; I don't use visual products configurator. Perhaps @pdunbar knows?
