### ISSUE TITLE
Problem with 3rd party upsell slider and Elementor Pro

### ISSUE THREAD

**Issue by markusreklambyra** [pojome/elementor#5869]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi, 

I use Elementor Pro and a [3rd party plugin](https://shapedplugin.com/plugin/woocommerce-product-slider-pro/) for upsell products slider. It seems to work fine on most pages, but on some products it breaks the layout. The products are all using the same single product template. What do you think could be the problem? Can you see anything that I cant?

Thanks in advance, 
Daniel

## Steps to reproduce
Please go to https://hallins.com/produkter/produkter/lyftvagnar/lyftvagn-newton-50/ for see a working page, and then https://hallins.com/produkter/produkter/lyftvagnar/lyftvagn-newton-70/ to see a broken page.

## Isolating the problem

- [] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Elementor Pro, WooCommerce, WP and all other plugins updated. 

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@markusreklambyra 

Its impossible to know why from just looking at the pages you linked, but I do see that on the 2nd page you get a 500 server error so I can only recommend you check your error/debug log.

thanks

**Comment by markusreklambyra** [comment]
@bainternet 

Thanks for quick reply. Here's both WC and WP errors from today: https://pastebin.com/3EVWScXr
