### ISSUE TITLE
Bug at the Video-Element

### ISSUE THREAD

**Issue by jv-BB** [pojome/elementor#5871]
I found a Bug at the Video-Element:
When using the source "selfhosted" I get a JavaScript Error "ResizeObserver loop limit exceeded  /sydney-elementor/content-elemente/". The reason is not the theme. When I use the theme "wp-ocean" it's just the same.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
