### ISSUE TITLE
Single custom post type problem with dynamic slug rewrite

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#5872]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If I have a custom post type and use slug rewriting option, for example:
`$rewrite = array(
		'slug'                  => sanitize_title(get_field('single_title, 'option')),
		'with_front'            => true,
		'pages'                 => true,
		'feeds'                 => true,
);`

And then create a template for this custom post type single. it won't work.

Changing the rewrite rule to a static one (for example: `'slug' => 'some_title'`) fixes it (make's the template work). changing back to dynamic breakes it again (the single template won't work. the theme's template file will be used instead.).

## Steps to reproduce

Create a post type and create a dynamic rewrite.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.6.41
	PHP Version: 7.0.32
	PHP Max Input Vars: 10240
	PHP Max Post Size: 24M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: he-IL
	Debug Mode: Inactive

== Theme ==
	Name: twentyseventeen-child
	Version: 1.0
	Author: Me
	Child Theme: Yes
	Parent Theme Name: Twenty Seventeen
	Parent Theme Version: 1.7
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

== Active Plugins ==

	Benadam Postype, Taxonomy and tags
		Version: 1.0.0
		Author: Me

	Elementor
		Version: 2.2.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.9
		Author: Elementor.com

				
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
