### ISSUE TITLE
Create a custom post type or custom taxonomy Archive

### ISSUE THREAD

**Issue by alexatoxy** [pojome/elementor#5882]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I've searched other issues but I can't seem to find the same problem. I would like to be able to create an archive for custom post types and filter them by category.

**Describe the solution you'd like**
For example, I have a sub-menu with different categories of custom post types and I would like to make an archive template for these categories. I've searched and AE Pro has a similar feature:

https://aedocs.webtechstreet.com/article/10-create-category-or-custom-taxonomy-archive-layout

This would be very useful since I'm currently using several custom post types and I would like to have an archive template by category without having to create a template every time I create a new custom post or category.

**Comment by bainternet** [comment]
Creating archive templates (custom post type archive/taxonomy archive) is already possible in elementor Pro since V2.0.0

**Comment by javiercriado** [comment]
I'm sorry but I've looked everywhere and can't find how to create archive templates (custom post type archive/taxonomy archive).

the same issue is here: closed but not solved: #605 
with other users asking until three weeks ago for a solution

at the end of this article, [https://elementor.com/blog/wordpress-custom-post-types/#42f4ccc](url) there's a vague explanation of how to do it. then there's a link to create a custom query that works for customizing the query in a post loop widget, but doesn't solve this issue.

when creating an archive template you don't have the option to choose taxonomy. You can choose Archive but then in the visualization conditions you can't choose Taxonomy

I'm a regular paying customer, have the Elementor Pro 2.5.1 version, I really need this and I think others need this too. 

There are external plugins, like toolset, who afirm this can't be done in Elementor:
[https://toolset.com/documentation/user-guides/using-toolset-with-elementor-page-builder/design-archive-pages-for-custom-post-types/](url)

> Elementor templates do not allow you to design the archive pages for custom post types. However, you can easily do this with Toolset.

The other option to get this working is to buy and install crocoblocks jetengine:
[https://crocoblock.com/school/articles/how-to-create-an-archive-page-for-the-custom-taxonomy/](url)

or anywhere elementor pro:
[https://aedocs.webtechstreet.com/article/10-create-category-or-custom-taxonomy-archive-layout](url)

Thanks for the support

**Comment by adrianrjones** [comment]
It would be nice to have query filters applied to archives. Right now they only work with the posts widget and the portfolio widget.

**Comment by javiercriado** [comment]
theme builder: archive, header and footer template: display conditions for custom taxonomy (including custom taxonomy terms selector) please!

**Comment by freelancesam** [comment]
This needs to be added!

**Comment by tonyDevCro** [comment]
I have two Archive pages (one for the blog, second for tutorial page ). The first archive page (blog) is a standard archive page. Second with custom code in child theme. [https://stackoverflow.com/questions/44626650/archive-page-for-custom-post-type]

Instead of creating archive-{post_type}.php, I created a template for the new page.

```
<?php
	/*
	Template Name: Page for Archive
	*/
?>
```

Myb this help somebody.
Sry for my bad english

**Comment by TomRaraAvis** [comment]
#4440 [Feature request] Posts / Archive loop item template designer

**Comment by ayoubkhan558** [comment]
Duplicate of #20247
