### ISSUE TITLE
Full width on mobile does not work

### ISSUE THREAD

**Issue by Neillbar** [pojome/elementor#5883]
Good Day, My Full width works 100% on Desktop but on mobile it does not.

When you load the website on a mobile device and you pull it to the side, the picture no longer is full width. The weird thing is, on the home page it works but on the rest it does not work.

Please see picture attached what i mean.

Thanks
![why it is wrong](https://user-images.githubusercontent.com/43991798/46671674-a6b2ac00-cbd5-11e8-8b35-5bdfcb1a7c0e.jpg)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
