### ISSUE TITLE
Setting utm params on "Share buttons" widget

### ISSUE THREAD

**Issue by j2logo** [pojome/elementor#5888]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Analyzing traffic from social networks.

**Describe the solution you'd like**
I would like to set utm params to buttons on "share buttons" widget for the current page. The available options for the "Target URL" are "Current Page" and "Custom" right now. It would be nice to set a magic word for custom urls such as "%current_page%?utm_source=xxx&&umt_medium"

**Comment by bainternet** [comment]
@j2logo 

Thanks for the suggestion.
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks again.
