### ISSUE TITLE
Prefill custom fields for Twitter share button

### ISSUE THREAD

**Issue by j2logo** [pojome/elementor#5889]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Customization of the Tweet shared by the "Social share" button with fields such as post title and @via

**Describe the solution you'd like**
More options for the button such as "Add post title", "Add via" and so on.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
