### ISSUE TITLE
Update and remove Group Controls

### ISSUE THREAD

**Issue by hemanttejwani2610** [pojome/elementor#5891]
Hi,

Is there any function to remove(remove_group_control) and update(update_group_control) Group Controls same as like update_control and remove_control.

Or how can I update and remove group controls?

**Comment by bainternet** [comment]
Using `update_control` and `remove_control` should work just fine.

**Comment by hemanttejwani2610** [comment]
I have tried but not getting the desired result.

If you have any sample code or you can tell me how you can achieve this.

**Comment by hemanttejwani2610** [comment]
@bainternet @iamntz @rsiddall @pingram3541  Please suggest some solution.

**Comment by jphilung** [comment]
I have the same problem. For example, if the control is added in the following way:
```
$this->add_group_control(
	Group_Control_Image_Size::get_type(),
		[
			'name' => 'thumbnail_size',
			'default' => 'medium',
			'exclude' => [ 'custom' ],
			'condition' => [
				$this->get_control_id( 'thumbnail!' ) => 'none',
			],
			'prefix_class' => 'elementor-posts--thumbnail-size-',
		]
	);
```

How do I target the control to remove or update the group control ?

**Comment by nicolas-jaussaud** [comment]
Maybe I'm a little late, but it looks like you need to add a suffix to the end of the control name (it's the case with the typography group control at least).

```
$element->add_group_control(
    Group_Control_Typography::get_type(),
    [
        'name'     => 'control_name',
        'selector'  => '{{WRAPPER}} .class',
        'scheme'  => Scheme_Typography::TYPOGRAPHY_4,		
    ]
);

// Remove the group control
$element->remove_control( 'control_name_typography' );
```

**Comment by kamalahmed** [comment]
I have a group control in parent class like this: 
`		$this->add_group_control(
			Group_Control_Typography::get_type(),
			[
				'name' => 'typography',
				'scheme' => Scheme_Typography::TYPOGRAPHY_1,
				'selector' => '{{WRAPPER}} .elementor-heading-title',
			]
		);
`

I want to change the selector of the above group control in a child class. I used the following code and it does not work.
`
$this->update_control( 'typography', [
	        'selector' => '{{WRAPPER}} .one-elements-element__content',
 ]);
`


What am i missing here?

**Comment by gaambo** [comment]
I read through the source code and finally came up with a solution to update the typography control group to change the selectors.

all controls of a control group get added as single controls with a prefix. I looped through them by getting all base control names of the typography control group: 

```
// updating the typography control to apply typography changes to long-text div as well
// a bit hacky, because update_control does not work for group_controls
// because they are stored as single fields with a prefix
// 
// also: the selectors array get's build in control_groups handle_controls (from prepare_fields) 
// which only gets called on first adding the controls_group
// so first get the old data to set selector_value correctly
$controls_manager = Plugin::$instance->controls_manager;
$typographyGroup = $controls_manager->get_control_groups('typography');
foreach ($typographyGroup->get_fields() as $field_key => $field) {
    $control_id = "desc_typography_{$field_key}";
    $old_control_data = $controls_manager->get_control_from_stack($this->parent->get_unique_name(), $control_id);
    $this->parent->update_control($control_id, [
        'selectors'  => [
            '{{WRAPPER}} .uael-infobox-text' => $old_control_data['selector_value'],
            '{{WRAPPER}} .uael-infobox-text-long' => $old_control_data['selector_value'],
        ]
    ]);
}
```

Also to change selectors you first have to get the old control data, because the selectors array gets build/changed only on the first initialising (adding) of the controls group. 

This may be a bit hacky and should be tested.
