### ISSUE TITLE
Image carousel next/previous image

### ISSUE THREAD

**Issue by yannischas** [pojome/elementor#5892]
I am only able to flick through images in an image carousel by clicking the right or left arrows and the dots (or put it on autoplay).

It would be nice if there was an option to move to the next image if I clicked anywhere on the right half of the image (instead of just the arrow) and similarly for the left side.

**Comment by Matherone** [comment]
+1.

Probably a good idea. It would then apply to other images-displaying widgets that also use arrow navigation, such as "Slides". 

On bigger desktop screens, arrows often become minuscule and hard to see on when image backgrounds vary, as they do almost by definition in carousels and slides. Elementor should instead make a larger widget area susceptible for advancing images by standard click.

Please consider adding making left-clicking on some larger area to the left or right of widgets using arrows advance to the next image to the left or right.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
