### ISSUE TITLE
Memory Exhausted when accessing ACF fields in custom query

### ISSUE THREAD

**Issue by vercotux** [pojome/elementor#5896]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

As reported in "Elementor Pro 2.1 (Release Candidate)" by @joyspringmedia: https://github.com/pojome/elementor/issues/4923#issuecomment-402507918 https://github.com/pojome/elementor/issues/4923#issuecomment-404206853

When using the new wp query action hook, I am unable to use get_field() to get an ACF relationship field. Once I use it:

    $post = get_post(); $relposts = get_field('reciprocal',$post->ID);

...the page either doesn't load or I get this error message:

    Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /app/public/wp-includes/functions.php on line 3594 Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

sometimes the error message is different:

    Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /app/public/wp-includes/class-wp-hook.php on line 269 Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

*Note: I have tried increasing the memory_limit to 2GB! and yet all of it still gets exhausted.*

## Steps to reproduce

1. In ACF add a custom field to your post (e.g. "mood").
2. In Elementor create a single page template, place a Posts widget, and give it a query ID (e.g. "my_query").
3. Attach the following query hook callback for that query ID:

```php
add_action('elementor_pro/posts/query/my_query', function($query) {
    get_field('mood'); // <-- this is where all your memory will get drained
});
```

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro). -- We need at least ACF to run along with it.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

```
Operating System: | Linux |  
-- | -- | --
Software: | nginx/1.14.0 |  
MySQL version: | (Ubuntu) v5.5.61 |  
PHP Version: | 7.2.10-0ubuntu0.18.04.1 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | No |  
Write Permissions: | All right |  
Elementor Library: | Connected
```

</details>

**Comment by bainternet** [comment]
@vercotux 

Apperently `get_field` makes a query for some reason which resluts in infinity nested loops.

You can easly get around it by removing the action once you are in the hooked function ex:
```PHP
// add hook
add_action( 'elementor_pro/posts/query/acf_relationship_filter', 'acf_relationship_filter' );

function acf_relationship_filter( $query ) {
    // remove hook to avoid nested calls
    remove_action( 'elementor_pro/posts/query/acf_relationship_filter', 'acf_relationship_filter' );
	$related  = get_field( 'related' );
	$query->set( 'post__in', $related );
}
```

thanks.

**Comment by shaneonabike** [comment]
Wow life saver! Although in our case we needed this for the following scenario

`add_action( 'elementor/query/campaign_publications', 'campaign_publications_filter');
function campaign_publications_filter( $query ) {
  // Prevent nested loops
  remove_action( 'elementor/query/rclalq_campaign_publications', 'campaign_publications_filter');

  // Modify the articles associated term to this campaign
  $ids = get_field('publications');
  if (empty($ids)) $ids = array(0 => -1);
  $query->set('post__in', $ids);
}   
`

**Comment by pinguluk** [comment]
> @vercotux
> 
> Apperently `get_field` makes a query for some reason which resluts in infinity nested loops.
> 
> You can easly get around it by removing the action once you are in the hooked function ex:
> 
> ```
> // add hook
> add_action( 'elementor_pro/posts/query/acf_relationship_filter', 'acf_relationship_filter' );
> 
> function acf_relationship_filter( $query ) {
>     // remove hook to avoid nested calls
>     remove_action( 'elementor_pro/posts/query/acf_relationship_filter', 'acf_relationship_filter' );
> 	$related  = get_field( 'related' );
> 	$query->set( 'post__in', $related );
> }
> ```
> 
> thanks.

2021 and still not fixed? Isn't this a bug?

**Comment by mattloker** [comment]
Spend days dealing with this issue before i came across this stupid bug. Can't believe this still isn't fixed. It is 2022!!!!!

**Comment by yabwee** [comment]
2023 now and still not fixed :) The above suggestion is indeed a lifesaver though!

**Comment by milan-ematic** [comment]
This is still not resolved in 2024, but I found another workaround.

We can use `get_post_meta()`, but make sure to set the last parameter to `true`.

    function custom_query( $query ) {
        $custom_field = get_post_meta($post_id, $filed_name, true); // important to set last parameter as true
    }
    add_action( 'elementor/query/custom_query', 'custom_query' );`

Disclaimer: This should work for most cases, but you might need to adjust it a bit in certain situations, you can find more info here:

- https://support.advancedcustomfields.com/forums/topic/want-to-use-get_post_meta-instead-of-get_field-for-array/
- https://www.timjensen.us/acf-get-field-alternative/

**Comment by adamr415** [comment]
Ya, this is still a problem. This seems truly basic and solvable. I was able to work around after finally realizing this was the issue.

**Comment by edrob** [comment]
2025 & this still saved my day!

**Comment by kevanbulmer** [comment]
2025 & this still saved my day!
