### ISSUE TITLE
Image link spanning full width of the widget container

### ISSUE THREAD

**Issue by Paras16699** [pojome/elementor#5897]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When adding a link to an image, the link spans to to the full width of its parent block (the image widget) irrespective of the image size.

The problem comes when I use an image that does not take the full image widget space (the most common example being the Site Logo), and assign a link to it, the link is clickable outside of image in the black space which is not the expected behaviour. This is coming from `.elementor-widget-image .elementor-image>a` set to `display: block;`

I'm not sure why an anchor tag's display property is set to block.

## Steps to reproduce

1. Insert a section or a column.
2. Add the image widget inside it.
3. Choose an image and set its width to less than 100%
4. Assign a link to it
5. The pointer cursor would show and the link would be clickable outside (besides) that image.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by arielk** [comment]
Which theme are you use?

**Comment by Paras16699** [comment]
Elementor Hello Theme. The CSS rule I mentioned above is coming from the Elementor plugin.

**Comment by gaambo** [comment]
Hi there, I don't know about the original problem but the fix from 105c5d2b5e5c01aa76e1576b901e9afa756246a8 (changing `block`  to `inline-block`) leads to problems in Internet Explorer 11. I've had that request in a WordPress support group on Facebook. Changing the style back to `block` fixes the `a` + `img` elements getting wider than its parent (overflowing) in IE.
![grafik](https://user-images.githubusercontent.com/5585580/70782235-cbc91e80-1d86-11ea-8e49-0293fc457f48.png)
