### ISSUE TITLE
Elementor - Slow to open

### ISSUE THREAD

**Issue by curtds** [pojome/elementor#590]
I have to say that Elementor is the best Drag and Drop Page Builder I have come across and it is fast.  It's fast once it opens up, some times it takes forever to open if at all.  Anyone have a solution to this?

**Comment by arielk** [comment]
Do you receive any Error message?
Please try to disable all your plugins and check if it helps.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
