### ISSUE TITLE
Full width sticky header leaves scrollbar space on right

### ISSUE THREAD

**Issue by chrolm** [pojome/elementor#5901]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When using a sticky header, the header leaves room for the scrollbar on the right even when the scrollbar is removed by enlarging the window.

The problem has happened sometimes during 2.1 Pro - it wasn't present on 2.0. I downgraded to 2.0 and can see you solved the width differently.

On 2.0 it looks like you guys didn't set the width of the section in Javascript, which is where the problem lies. From what I can tell, the browser doesn't report the new viewport width correct once the scrollbar is gone, so in 2.1 the width is rendered with whitespace on the right once the scrollbar is gone. Even when reloading afterwards, the whitespace still persists. 

I'm attaching pics with the relevant section highlighted in the source.

![scrollbar-present](https://user-images.githubusercontent.com/24466749/46822300-ff05bd00-cd3f-11e8-9bc4-218d8105da13.jpg)
![scrollbar-gone](https://user-images.githubusercontent.com/24466749/46822381-35dbd300-cd40-11e8-88e2-cfb7497e1a85.jpg)

## Steps to reproduce

1. Set up new WP installation
2. Install Elementor and Elementor Pro
3. Create new full width header
4. Make it sticky
5. Go to home page
6. Make the window short
7. Now make the window long, so the scrollbar disappears

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

PHP 7.2, Centos 7, MariadDB.

This only happens on Windows clients - Chrome/Firefox/IE - since Mac doesn't doesn't take the scrollbar into consideration when calculating width.

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6
	MySQL version: MariaDB Server v5.6.39-83.1
	PHP Version: 7.2.11
	PHP Max Input Vars: 2500
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.clusterwp.com
	Home URL: https://www.clusterwp.com
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.7
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

== Active Plugins ==
	BackWPup Pro
		Version: 3.6.0
		Author: Inpsyde GmbH

	Elementor
		Version: 2.2.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.10
		Author: Elementor.com

	MainWP Child
		Version: 3.5
		Author: MainWP

== Debug ==
	Errors: There are no errors to display
				

```
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by webcreativeng** [comment]
How was this resolved? I'm having the same issue.

Thanks.
