### ISSUE TITLE
How can I disable/enable accordion widget functionality by JS?

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5902]
How can I disable/enable accordion widget functionality by JS?
I want all be open on desktop (done via CSS)
and disable click on heading of accordion (cant done by preventDefault)

and enable it on mobile / tablet.

**Comment by bainternet** [comment]
@Alimir 

you can try to remove the "onFocus" handler, ex:
```JS
$( '.elementor-tab-title' ).prop('onfocus', null).off( 'focus' );
```

**Comment by amindiary** [comment]
@bainternet not works, can you check this videocast?
<div style="width:100%;height:0px;position:relative;padding-bottom:48.913%;"><iframe src="https://streamable.com/s/ftvwx/buorfv" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by bainternet** [comment]
There is no api for that it would have to be a hack along the lines of the snippet I provided with css customization.
