### ISSUE TITLE
[Elementor Pro] To put the tittle on top of the images in the posts

### ISSUE THREAD

**Issue by GaragemOnline** [pojome/elementor#5903]
Hi ! 

I talked to Pepe, the technical support and he said me that the feature does not exist and that is very interesting.

I would like to put the title on top of the images in the posts, just like the annexe example.

[example](https://user-images.githubusercontent.com/44071600/46830518-3b084480-cd77-11e8-8951-a8632a5e35a5.png)

Att,

Tiago Maia

**Comment by bainternet** [comment]
Should be possible once we implement #4440 

thanks.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
