### ISSUE TITLE
Google fonts injected in preview (editor) but not in frontend

### ISSUE THREAD

**Issue by a-camacho** [pojome/elementor#5905]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description and steps to reproduce

Using Elementor (and Elementor Pro) we created various child themes, using the same parent theme. Since last updates or Elementor we observed a strange behaviour : 

- Setting up fonts in Elementor Global Fonts works
- Both fonts are displayed in Elementor Preview (page builder, see screenshot1.png)
- Both fonts are displayed because they are enqueued correctly (see inclusion1.png)
- **When loading front-end (with any theme, even WP default ones) heading font is correctly displayed (even if I find no mention of it in source code) but body text tries to use Google font defined but can't. In fact, in source code, no Google Font can be loaded. (see screenshot2.png)**

![screenshot2](https://user-images.githubusercontent.com/29976133/46860139-12805900-ce10-11e8-8641-bda684f06555.png)
![screenshot1](https://user-images.githubusercontent.com/29976133/46860140-12805900-ce10-11e8-9afe-7a27736ca7b8.png)
![inclusion1](https://user-images.githubusercontent.com/29976133/46860141-12805900-ce10-11e8-97eb-7e81d2ce53b6.png)

_It seems that when in preview Elementor is able to inject a `css?family=Playfair` when seeing frontend the parameters seem to not be passed : `css` only which gives 404 error._ 

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
OS : Debian Stretch
Elementor versions : last (both normal and pro plugin)
Wordpress version : last
```
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
