### ISSUE TITLE
Please make widget class methods more overridable and not always private/protected 

### ISSUE THREAD

**Issue by spencer-j** [pojome/elementor#5906]
Hello Elementor Team,
For example, i want to extend/override methods of the video widget, the most methods are private or protected.
Widget_Video
: private function get_hosted_params()
: private function get_hosted_video_url()
So please more hooks or extendable through php OPP
Thanks spencer-j

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
