### ISSUE TITLE
content in editor preview vanishes when dynamic elements are edited

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#5908]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

when editing practically any element with dynamic content on pages, templates or whatever the content of the dynamic fields disappear on nearly every automatic refreh of the editor.
quite annoying because one have to save and manually refresh the editor tab to see the content again.

## Steps to reproduce

choose any page or template with dynamic content, edit some dynamic fields (settings or whatever) and see your content vanish when the editor preview should update.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.33
	PHP Version: 7.2.4
	PHP Max Input Vars: 1500
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: -
	Home URL: -
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: -
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 1.1
	Author: -
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.1.4
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

== Active Plugins ==
	Admin Columns
		Version: 3.2.7
		Author: AdminColumns.com

	Admin Menu Tree Page View
		Version: 2.7.1
		Author: Pär Thernström

	Advanced Custom Fields
		Version: 5.7.7
		Author: Elliot Condon

	BackWPup
		Version: 3.6.1
		Author: Inpsyde GmbH

	Cache Enabler
		Version: 1.3.1
		Author: KeyCDN

	Custom Archive Titles
		Version: 1.1
		Author: ThemeZee

	Custom Post Type UI
		Version: 1.5.8
		Author: WebDevStudios

	Ele Custom Skin
		Version: 1.0.5
		Author: Liviu Duda

	Elementor
		Version: 2.2.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.10
		Author: Elementor.com

	Enable Media Replace
		Version: 3.2.7
		Author: ShortPixel

	GP Premium
		Version: 1.7.2
		Author: Tom Usborne

	Physical Custom Upload Dir for Real Media Library
		Version: 1.0.4
		Author: Matthias Günter

	Simple CSS
		Version: 1.1
		Author: Tom Usborne

	Widget Visibility Time Scheduler
		Version: 5.3.1
		Author: Martin Stehle

	WP Author Slug
		Version: 2
		Author: Konstantin Obenland

	WP Real Media Library
		Version: 4.0.7
		Author: Matthias Günter

== Debug ==
	Errors: 
		TypeError: setting getter-only property "type"
			at https://-/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:86630
			2018-10-12 15:01 +00:00

		TypeError: this.ui.select is undefined
			at https://-/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:13050
			2018-10-10 09:06 +00:00

		TypeError: o.collection is undefined
			at https://-/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.1.9 - 2:48714
			2018-10-09 13:42 +00:00
			x 4 times

		TypeError: setting getter-only property "type"
			at https://-/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:86630
			2018-10-06 18:38 +00:00

</details>

**Comment by bainternet** [comment]
@dasigna 	

We can't replicate the issue you are describing, I am only aware that it happens to ToolSet fields if you are using the toolset Free version. if its something other than that
