### ISSUE TITLE
elementor archive collides with generatepress blog ???

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#5910]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

using generepress with premium and using it to standard blog posts as well as the respective archive. this ist set up to show three columns withh bigger first post, and as whole shown as masonry
now i am trying to use elementor to show the search results... with separate template and post archive widget. sadly this seems to interfere with grid-classes of unsemantic grid from GP. as a result the columns of the archive widget are stripped and the content does not take the full width - regardless of selected numbers of columns.

## Steps to reproduce

just set up as described above and youll see :)

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
