### ISSUE TITLE
Vertical Menu without Mobile and Submenu Dropdowns and with More Options

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#5912]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Current implemantation of a vertical menu uses dropdown behaviour for the submenu items. It also switches to "hamburger" menu on mobile. This is not always wanted, for example when used in a footer or sidebar menu.

**Describe the solution you'd like**
Add an option to:
1. Output menu as a simple list of items, including submenu items
2. Output menu as a simple list of items, without submenu items (the root level only)
3. Output menu with submenus items as the pulldown blocks (now are output as drobdowns, or "dropsides")
4. Output submenu items of specified parent (including parent name as a heading)
5. Output menu including submenus up to specified submenu level.

**Describe alternatives you've considered**
Make my own custom shortcodes

**Additional context**
There is a similar, but more general request here #3275. Some of the options mentioned here are described there as well, but I think it would be nice to have it summarized in extra issue. 

Usecases:
- footer menus
- sidebar menu
- sidebar submenu

**Comment by bainternet** [comment]
@black-eye 	

To output a menu as a simple list you can use the native WP menu widget, as fro the rest follow #3275 


thanks.
