### ISSUE TITLE
Dynamic Data Tables

### ISSUE THREAD

**Issue by sann1432** [pojome/elementor#5922]
Use case: I'm currently using WPDataTables, but the forms integration is lacking.

FEATURE REQUEST: integrate Elementor with WPDataTables or provide similar capability 
 - dynamic data tables, data input & recall, table lookup.

Forms
1) Provide a way to link the form fields with database tables.
2) provide a call back function to pull data from the DB to the original submission form. 
3) provide conditional formatting for forms. 
3) provide a capability for multi-page forms. 

DB tables
1) provide a foreign key lookup for information in other tables 
2) integrate data tables js plugin  - ref= https://datatables.net/

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
