### ISSUE TITLE
Image Widget Alignment when using caption field

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#5923]
When using the Image widget, if you set a Caption the Image itself ignores its Alignment setting and always centers itself. Remove the caption and it obeys the set alignment.

But the caption alignment works fine obeying its alignment setting but the image remains centred regardless.

This appears to be a bug and not intended behaviour.

**Comment by arielk** [comment]
It works perfect for me, which theme are you using?

**Comment by Pagester** [comment]
> It works perfect for me, which theme are you using?

Ariel, you are correct, it is the theme causing it. We were using Elementor Canvas template so incorrectly assumed nothing in the theme would be used for styling.

It was the "Page Builder Framework" theme. When we tested with the Elementor Hello theme it worked as expected.
