### ISSUE TITLE
Problem with posts element Image Position 

### ISSUE THREAD

**Issue by Alipio123** [pojome/elementor#5924]
Plugin name: Elementor Pro
Version: 2.1.10 

Description:
I was trying to create a custom blog archive using the Post Element. 
I drag and drop the Post element in a row and set this following setting

1. Skins = Classic
2. Columns = 1 (desktop, tablet and mobile)
3. Post per page = 6
4. Image position = Left
5. Image width = 100%

Now when I tried viewing it on mobile the title and excerpt was gone because the div that wrapping the Title and excerpt didnt go down. 

The work around I made is to change the Image width in mobile view. The Layout Looks weird if the title and excerpt need to be shown and readable. 

I hope you fix this problem.

**Comment by bainternet** [comment]
@Alipio123 	

Can you provide a screencast so we could understand better?
also when you create an archive template you should use "Archive Posts" widgets and not the "Posts" widget.

**Comment by Alipio123** [comment]
hi @bainternet 

Yes, I know I should just use the Archive Template features but I was building my own archive page in certain page.. 

Anyway here's please see attached for the screenshot.
![post-element](https://user-images.githubusercontent.com/2425234/47154988-63afb180-d316-11e8-9be8-ddd9e279e3c8.jpg)


There should be an option for image position in mobile view.

**Comment by bainternet** [comment]
Ok, I see what you mean. Then this should be possible once we implement #4440 so you should follow that issue.

Thanks again.

**Comment by simonclay** [comment]
Still the same problem in 2022

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
