### ISSUE TITLE
custom query for post navigation widget

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#5925]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
as we now have the great custom query and custom fields features, it is a real pleasure to build loops with them.
but if i want to set up a navigation for custom cpts with custom query i am stuck with the post navigation widget as it wont be able to follow the given (custom) query for the post loop.

**Describe the solution you'd like**
just the post navigation widget with same custom query option as posts and portfolio widget.

**Describe alternatives you've considered**
only complicated workarounds - being hard to maintain ...

**Remark**
this is no duplicate of nothing i have found so far!

**Comment by dasigna** [comment]
thanks @bainternet, glad you're asking,

its quite simple:
in a current case e.g. i've set up cpts as future posts (for events) and showing them via custom query in post grid. great thing! then i've created a single view for those cpts to show their details - again great.
BUT - now trying to insert the post navigation widget into the single view to cycle between those future events... and it doesnt work. simply because the nav widget is trying to pull the 'normal' ones of those cpts - in this case the past (for wp the already published) ones.
and i currently have no option to assign the same custom query to the nav widget to navigate forth or back to the next future post (event) which is currently shown. the nav widget in this case simply wont follow the given custom query. but obviously it should be able to.

does this make sense for you?

**Comment by seanvandermolen** [comment]
Makes sense to me.  It's like the next post widget defaults to the current query which is whatever WP returns for the custom post type. 

It's the same reason why I would like to see custom query tabs for Post and Archive post Widget using current query.  The only way to solve this problem is to set the query for the CPT in functions.  Then defaults in Elementors widgets will return the archive based on whats set been configured in functions.

**Comment by bainternet** [comment]
@dasigna 	

thanks for clarifing,

Well in that case, Elementor's Post Navigation uses the native WP `previous_post_link` and `next_post_link` which both are passed through a filter

```PHP
 
/**
* Filters the adjacent post link.
*
* The dynamic portion of the hook name, `$adjacent`, refers to the type
* of adjacency, 'next' or 'previous'.
*
* @since 2.6.0
* @since 4.2.0 Added the `$adjacent` parameter.
*
* @param string  $output   The adjacent post link.
* @param string  $format   Link anchor format.
* @param string  $link     Link permalink format.
* @param WP_Post $post     The adjacent post.
* @param string  $adjacent Whether the post is previous or next.
*/
return apply_filters( "{$adjacent}_post_link", $output, $format, $link, $post, $adjacent );
```
`$adjacent` can be either `previous` or `next`.

So you can use that.
