### ISSUE TITLE
Post excerpt limiter

### ISSUE THREAD

**Issue by LukasBlumer** [pojome/elementor#5926]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We're having an issue where we would like to limit the excerpt that is shown in the preview of a post to a certain text field. Currently the only way to influence the excerpt is the excerpt length in words. That is not sufficient in our case, because what we would like to show varies in length. After the text element we want to use as an excerpt, there is further text that should not be used. Thus, we cannot simply set the excerpt to be longer.

**Describe the solution you'd like**
An option to either set the excerpt to only pull from the first text element in the post or to have it not pull text past a spacer. Or to have a dedicated element to limit the size of the excerpt.

**Describe alternatives you've considered**
The way we are currently getting around this is to have a text element with just spaces in it. The spaces are somehow counted as words and it prevents the excerpt to show further text as a result. But this is very hacky - the spaces get deleted with every update to the post unless just that text element was updated. Further, it messes with the formatting of the excerpt.

**Additional context**
Example of the formatting issue with spaces: https://imgur.com/99qum8r (it is aligned to the middle, not the right side)

**Comment by bainternet** [comment]
Same thing as https://github.com/pojome/elementor/issues/6400#issuecomment-446211498
