### ISSUE TITLE
Review Nag showing constantly

### ISSUE THREAD

**Issue by doffine** [pojome/elementor#5927]
The following issue is opened on request of @boazpojo in wordpress.org forum.
The original issue description below is copied from Shahjahan Jewel's original entry in wordpress.org forum.

Issue description:
It’s showing the review nag constantly even I try to click “Hide Notification” or “x” button thousands of time. This is very frustrating. A plugin developer can request to write a review but it should be dismissible permanently.

**Comment by bainternet** [comment]
@doffine 	


thanks for reporting, 
We are having a hard time replicating this,
Can you please contact our support at support @elementor.com and mention that you were directed by me and reference this issue, I'll try to continue this with you there.

thanks.

**Comment by arielk** [comment]
Fixed in v2.2.7 

Thanks for your feedback!
