### ISSUE TITLE
Dynamic content for post archive 

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#5928]
## Prerequisites

[x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

When creating an archive, you can add an text excerpt within the Elementor post archive element. But when using ACF (Advanced Custom Fields) for example, this option is invalid, because you only have custom fields and no text excerpt is defined. But this is a very helpful function to list more details on archive pages.

**Describe the solution you'd like**

Adding dynamic content to the text excerpt of the post archive element to be able to use the archive page in a more detailed way, instead of only having a picture and a title when using ACF plugins.

**Describe alternatives you've considered**

**Additional context**

**Comment by dasigna** [comment]
+1

**Comment by bainternet** [comment]
Please follow #4440

**Comment by papplebee** [comment]
+1

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
