### ISSUE TITLE
Shortcodes are not evaluated in a certain number of widgets

### ISSUE THREAD

**Issue by spirau** [pojome/elementor#5929]
If one uses the widget Title or Quote for example, nor the _field_ or the _content_ are processed against shortcodes inside. Shortcodes can be used inline, not only for big blocks. So it would be nice to do_shortcode on widget contents before returning.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by spirau** [comment]
What else do you need ? You do not process shortcodes in all the Title and Quote Widgets. That's it.

Quite easy to close all the issues you don't want to ear about. That's a good support. Thank you.
