### ISSUE TITLE
PRO PHP warning with Mailchimp form when no groups in the selected list

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#5931]
Hello,

PHP issues a warning during the Ajax `wp_ajax_elementor_pro_forms_send_form` request of a Mailchimp form,

Waring: Invalid argument supplied for foreach()
File: wp-content\/plugins\/elementor-pro\/modules\/forms\/actions\/mailchimp.php
Line: 176

How to reproduce :

Create a form and set it to use Mailchimp. Input a custom API key, choose a list (preferably a newly created one with no groups). No need to do anything else.

If you have QueryMonitor and submit the form, you will notice the PHP warning in the response headers `X-QM-`.
The form works anyway.

**Comment by bainternet** [comment]
@tristanleboss 

Thanks for reporting, that line handles the groups you have selected so check that you have and we will add a validation to avoid warning.

**Comment by bainternet** [comment]
Fixed in v2.1.11
