### ISSUE TITLE
Modal Editor Window

### ISSUE THREAD

**Issue by burbridgeconsulting** [pojome/elementor#5932]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Working on a 13.3" laptop the editor area being non-modal pushes the width of the layout area to like 980px, creating an unnatural environment where I have to hide it to see what it will really look like. When I hide it it turns off the editing too, which makes it very awkard.

**Describe the solution you'd like**
This is an area where BB is better—by default its editor area is modal—either when adding new modules or when editing options. This is of benefit to those on smaller screens. (See screenshot.)

**Describe alternatives you've considered**
Stay with BB for a while longer. Bring my iPad with me as external monitor. Buy a larger monitor (hassle for coworking!).

**Additional context**

![2018-10-17_09-45-05](https://user-images.githubusercontent.com/178848/47102366-64025c80-d1f1-11e8-8012-5b9a7ed2c62a.png)

**Comment by bainternet** [comment]
@burbridgeconsulting 

you can simply resize the panel.
and also there is this: https://wordpress.org/plugins/flexible-elementor-panel/

thanks for the feedback.
