### ISSUE TITLE
wp_trim_words for WooCommerce Archives

### ISSUE THREAD

**Issue by Perchpole** [pojome/elementor#5935]
It would be useful to add a wp_trim_words funtion for product titles in WooCommerce archives. This would limit titles to a single line - thus eliminating the up-down-up appearance of product grid displays.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
