### ISSUE TITLE
Fix your documentation links.

### ISSUE THREAD

**Issue by barrychapman** [pojome/elementor#5942]
This document in now available on Developer API for Elementor

The link is broken.

**Comment by barrychapman** [comment]
All the docs on the site are out of date also. Is there a way to get up to date docs? Your docs state this:

    elementor_pro/forms/valid_record_submitted

But I do not see a `do_action` for that ANYWHERE in the source. What gives?

**Comment by bainternet** [comment]
@barrychapman 

thanks for reporting, docs updated.
https://developers.elementor.com/forms-api/#Form_New_Record_Action
