### ISSUE TITLE
[Feature] Add a control to select a Widget instance of the current page / Link widgets togethers

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#5948]
Hello,

The need is simple: I want to link 2 widgets togethers. For example, imagine a page with multiple caroussel of pictures: I want to add a Download button widget on this same page to download all the pictures of one of these widgets.

For this to work, I need to have a control that can list all the widgets instance of the current page. I envision a select list with the content of the Navigator. The values of the `option` would be the widget instance id (the div `data-id attribute`). An amazing option for this control would be to limit the select to specific widget types.

```
Section
-- Column
---- Button
```

So my first question is: how can I get the page tree programaticaly in JS without having to resort to doing it with jQuery myself? Is there a way to do it from the `onReady` method of the control "class" exting the `elementor.modules.controls.BaseData` one?

My second question is: how can I get the linked widget settings from the `render` and `_content_template` methods of the PHP class of a block using this control? The value saved by the control will be "0f72c5f", for example. So, I need to be able to do something like $this->getSettingsForAnotherPageWidget("0f72c5f") in `render` and the same thing in the mustache code of `_content_template`.

Thanks.

**Comment by bainternet** [comment]
@tristanleboss 

Currently, There is no to get the current element tree, so i can't really suggest one way or another.

thanks.
