### ISSUE TITLE
Block iOS mobile animations

### ISSUE THREAD

**Issue by MATFUN** [pojome/elementor#5955]
Theme OceanWP + Elementor Pro (last version)
–––––
Request to add a global function:
Ability to block all Elementor Pro animations on Android and iOS mobile.

Request to add a global function:
Ability to block all Elementor Pro animations on Android and iOS devices.

This is the first time I use github, it is not easy, because I connect to Google Translate for the French> English translation! Sorry…

It misses an important option in Elementor Pro: block all animations on mobile.

Elementor support gave me the CSS code below, but it only works on Android mobile phones. Do you have CSS to add so that the function also extends to iOS, waiting for the new feature?

–––––
@media only screen and (max-width : 480px)
{ .animated { animation: none !important;
}
}
–––––

**Comment by bainternet** [comment]
@MATFUN 

The code you have works on any device with a `max-width` of `480px` regardless of which OS (Android, IOS, something else?) it has.

Which is not really relevant to iPhone 6 and newer because they have a higher `max-width`.

Try to look for the right media query that works for you: http://stephen.io/mediaqueries/#iPhone

**Comment by MATFUN** [comment]
Thank you for your return, but you made a mistake, even with this wide code, it does not remove animations on iOS (example iPhone 4S):

@media only screen and (min-device-width : 320px) and (max-device-width : 812px)
{ .animated { animation: none !important;
} 
} 

It must be added for this to work, this:

-webkit-animation: none !important;
-moz-animation: none !important;
-ms-animation: none !important;
-o-animation: none !important;

---
Avec mes cordiales salutations.
Mathieu Funk | graphic studiofunk | https://graphicstudiofunk.ch <http://www.graphicstudiofunk.ch/> | graphic@studiofunk.ch <mailto:graphic@studiofunk.ch>
---
