### ISSUE TITLE
WooCommerce single product dynamic CSS styles are being stripped

### ISSUE THREAD

**Issue by andrewmaney** [pojome/elementor#5957]
If you create a single product template using Elementor Pro, when it renders on the frontend all the usual dynamic CSS styles for that product are stripped.

Usually a WooCommerce single product page will output various CSS styles depending on tax, stock, product type settings. These are stripped from single product pages when building templates with Elementor Pro.

Normal single product page output:
![screen shot 2018-10-22 at 12 57 47 pm](https://user-images.githubusercontent.com/7564708/47275392-a6190d00-d5fa-11e8-861d-9b3d2922f517.png)

Note: The related products widget, and product archive widget both seems to be able load these dynamic CSS styles onto the page.

*Have tested with fresh install of WooCommmerce, default Wordpress theme, latest version of plugins + WordPress.

**Comment by bainternet** [comment]
closing in favor of #5959
