### ISSUE TITLE
Idea: "Convert to Elementor" in WP Admin Bar

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#5960]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
At the moment, the only way to convert an existing WP page to Elementor is via the "Edit" page in the backend. There's no ability to do this on the front-end via the WP Admin Bar when viewing a page - you have to click "Edit Page" and then "Edit Elementor" which is time consuming on multiple pages.

To add further confusion, the text "Edit in Elementor" is visible in the WP admin bar even when the page is not converted, and clicking the text does nothing.

**Describe the solution you'd like**
It would be nice if the "Edit in Elementor" text allowed the page to open in Elementor regardless of the state of the page. To avoid confusion, the text could read "Convert to Elementor" if the page is yet to be converted.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/1435638/47279305-8e9c4d00-d617-11e8-80f0-add8b6f3727b.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by drawcard** [comment]
That's fine @bainternet - I might create something for myself and submit a PR if it works well.
