### ISSUE TITLE
column resizing after css file is loaded 

### ISSUE THREAD

**Issue by joshcorti11** [pojome/elementor#5962]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Styling my header/menu with elementor caused this issue. I know this because the menu did not do this when it was styled with my theme; Ocean WP.

I expected the menu and drop down arrows to load smoothly without flashing or flickering like they did when I used Ocean WP to build my menu.

Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action. 

## Steps to reproduce
1.) go to www.sportsmensoutpost.com

2.) the home page will load correctly sometimes so try clicking around some of the different pages while keeping a close eye on the main menu's drop down arrows.

3.) you will see the main menu drops down arrows quickly disappear and then reappear when a new page is first being loaded by the user. 

4.) please take the time to click through the different pages a couple of times. I have thought this issue was resolved in the past because it did not happen right away. A couple minutes into browsing through the website and specifically looking/trying to reproduce the issue is when I saw it happen. (I have tried using Wordpress twenty seventeen).

5.) please see the attached screen shots to find out how one of your Colleagues tried to diagnose the issue.

![screen shot 2018-10-22 at 11 39 55 am](https://user-images.githubusercontent.com/44182023/47302370-5a149b00-d5ef-11e8-8af8-56154029d2c9.png)
![screen shot 2018-10-22 at 11 40 47 am](https://user-images.githubusercontent.com/44182023/47302371-5a149b00-d5ef-11e8-88da-2e5414dfac99.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
[system-info-sportsmensoutpost.com-22-10-2018.txt](https://github.com/pojome/elementor/files/2502065/system-info-sportsmensoutpost.com-22-10-2018.txt)

<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@joshcorti11 	

can you link pages you are sure it happens and even better create a screen capture so we can understand better the issue you are describing.

**Comment by joshcorti11** [comment]
![screen shot 2018-10-23 at 6 51 49 pm](https://user-images.githubusercontent.com/44182023/47395439-c88f5100-d6f4-11e8-965b-53901db72586.png)
![screen shot 2018-10-23 at 6 52 00 pm](https://user-images.githubusercontent.com/44182023/47395440-c88f5100-d6f4-11e8-91b9-f270195c7b1b.png)

Here are two screen shots of the issue. You can see that the drop down arrows are non existent (this is only for a split second while the menu is shrinking/the page is first loading). After a couple milliseconds the menu will expand and turn back to its original size. Is their anyway I can send you a video of this issue? Do you have an email address?

**Comment by bainternet** [comment]
Try this https://www.useloom.com/

**Comment by joshcorti11** [comment]
sure here is a link to the video https://www.useloom.com/share/6ac9e358ad6245ca85b5928df5316e66

**Comment by joshcorti11** [comment]
Hi,

Has your team made any progress on this issues?

**Comment by bainternet** [comment]
No issue here, It's simply the way the nave menu with submenus works.

thanks
