### ISSUE TITLE
Container Element

### ISSUE THREAD

**Issue by Codevz** [pojome/elementor#5963]
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Almost all page builder have container element which allows us to add other elements inside it like columns, sections, etc. Different is, container element can move everywhere but columns can't. Currently I'm using both elementor and WPbakery page builder, in WPBakery I can create container element but in Elementor there is not such feature.

I discovered elementor columns element codes and I think it will be easy for elementor developers for adding this feature like column element. Why we need this? We have over 10k customers and currently all of my themes developed with wpbakery and we wants to convert our elements into elementor, this also can be a big advertisement for emenetor page builder in my opinion.

Thanks in advance.

**Comment by bainternet** [comment]
I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by bainternet** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.

**Comment by Codevz** [comment]
Thanks for your reply, If you have any assist, suggestions or guide about container element it would be great if you share with us then we can start working on it and we will share result with elementor developers, My email: codevzz@gmail.com, Thanks in advance.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.6**, and is now a stable experiment since version 3.8! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
