### ISSUE TITLE
Examples of Pro forms integration with a user-written webhook

### ISSUE THREAD

**Issue by scott8035** [pojome/elementor#5964]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Has anyone had success with Elementor Pro forms integrating with user-written webhooks? There's some brief documentation at https://developers.elementor.com/forms-api/, but it just doesn't go far enough. Examples would be wonderful. I'm trying to do the basics: display a form, submit it for validation, and either process it or reject it with error messages back to the browser.

**What problem is your feature request going to solve? Please describe.**
From the limited documentation available at https://developers.elementor.com/forms-api/, I can't figure out how to do basic form validation and error response.

**Describe the solution you'd like**
I'd like to see some examples of all the coding required to submit a form, validate the response, and based on the validation, either execute an action or return errors back to the browser.

**Comment by bainternet** [comment]
@scott8035 

Not sure what more you need other then the examples on the docs,

To display a form you use Elementor form widget.

Validating form fields:

```PHP
// Validate the Ticket ID field is in XXX-XXXX format.
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {
    $fields = $record->get_field( [
        'id' => 'ticket_id',
    ] );

    if ( empty( $fields ) ) {
        return;
    }

    $field = current( $fields );

    if ( 1 !== preg_match( '/^\w{3}-\w{4}$/', $field['value'] ) ) {
        $ajax_handler->add_error( $field['id'], 'Invalid Ticket ID, it must be in the format XXX-XXXX' );
    }
}, 10, 2 );
```

this shows how to handle validation and reject and display an error on faild validaiton.

as for procceing it, if all validation is passed correctly then its submitted to the actions defined in the form and you can also see the example from the docs to do basically anything you cant with it:

```PHP
// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );
    if ( 'MY_FORM_NAME' !== $form_name ) {
        return;
    }

    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
        'body' => $fields,
    ]);
});
```

this example shows how to pass the submitted data to an external service but you can use the data to do what ever you want.

**Comment by scott8035** [comment]
If all the form processing is performed in these hooks, what do we specify as the webhook URL? Or do we simply omit any Actions After Submit when handling a form this way?

**Comment by scott8035** [comment]
We have:

> Form Submission Action
> elementor_pro/forms/form_submitted
> After the forms module is loaded and it’s a POST request with the form action. This is the place to add a form handlers.

...and:

> Form New Record Action
> elementor_pro/forms/new_record
> After the form actions have run. This is the place to add custom form handlers.

What's the difference, when would we use one vs. the other?

**Comment by scott8035** [comment]
...and one final question: wouldn't you need to do:
```
$form_name = $record->get_form_settings( 'form_name' );
if ( 'MY_FORM_NAME' !== $form_name ) {
    return;
}
```

...in the "elementor_pro/forms/validation" hook(s) as well?
