### ISSUE TITLE
Slides Widget Enhancement

### ISSUE THREAD

**Issue by zSeriesGuy** [pojome/elementor#5965]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I love the image handling in the slides (pro) widget.
But I would like to have the ability to dynamically populate the slide using post data (featured image, content). An example is events.

I have made the changes to my copy of the Elementor Pro slides.php widget to implement this capability.
**Is this something you would be interested in?**
If so, I would be happy to send you the code as I would like this to be a built in function of Elementor Pro.

The implementation is that the slide repeater works exactly the same as it currently does. But I added a Slide Type control that allows you to choose Image or Post. If Post is selected, the Content tab changes to add Query functions similar to what is in the Posts widget.
If the selected posts do not have a featured image, then the image defined on the Background tab is used.

It looks like this "enhancement" will satisfy [issue 5326](https://github.com/pojome/elementor/issues/5326)

**Comment by zSeriesGuy** [comment]
It looks like this "enhancement" will satisfy [issue 5326](https://github.com/pojome/elementor/issues/5326)

**Comment by bainternet** [comment]
I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!
