### ISSUE TITLE
How to force the use of <p> in the text-editor

### ISSUE THREAD

**Issue by spirau** [pojome/elementor#5969]
I can't understand the behavior of the text-editor widget. Sometimes there's no tag, sometimes it's a p and most of the time now the paragraphs are enclosed in div. I don't want the div as they are removed from the saved post content while p are not.
I use the post saved content in the wp_posts table to analyse the text against my keywords. Removing the divs without adding a space concatenate the text and it's not usable.
So, I can I force the text-editor to use <p> for the paragraphs?
Or how to have a space inserted for the divs in the post saved in wp_posts?

**Comment by chris-warren** [comment]
you could use an html widget and just write a paragraph tag and put your text in it.

**Comment by spirau** [comment]
Hi

 

Well, this is not a valid answer. It’s just a trick.

 

Usually the text editor uses p tags. But the one that’s runs in Elementor is just chaotic. Depending upon the fact that I’m editing in the left bar or in-line, the behavior is not the same. Sometimes all the text is collapsed without taking into account the \r. Because sometimes it’s a div and sometimes it’s a p, the margins are not the same. All is random.

 

De : Chris Warren [mailto:notifications@github.com] 
Envoyé : vendredi 26 octobre 2018 23:10
À : pojome/elementor
Cc : Eric Spirau; Author
Objet : Re: [pojome/elementor] How to force the use of <p> in the text-editor (#5969)

 

you could use an html widget and just write a paragraph tag and put your text in it.

**Comment by ocbroadband** [comment]
Maybe update the editor to tinymce or another flavor?  I use TinyMCE myself and it works great.  The advanced plugin configuration plugin allows you to change behaviors to your requirements as well.

http://www.laptoptips.ca/projects/tinymce-advanced/

http://www.laptoptips.ca/projects/advanced-tinymce-configuration/

**Comment by spirau** [comment]
Well I'm quite disappointed. Finally, the goal is to put text in the front page to deliver informations, not just titles, flip boxes and images. So Elementor's text editor should provide the basic functions correctly. The more add-on I use, the more fragile it is.
I'm tired to click 10 times on the right and on the left to get correct paragraphs.
Elementor is not up to the point here and they should start from this instead of adding sophisticated tricks.

**Comment by ocbroadband** [comment]
You realize the default text editor is just the editor from Wordpress, right?

**Comment by spirau** [comment]
Not exactly. In the left panel maybe, but not inline editing. I expect elementor to provide something coherent, not to have 2 behaviours and the requirement to add another plugin to get a decent text edition.

**Comment by bainternet** [comment]
@spirau 
No need to hack around or install 3rd party plugins.
A simple "Enter" in the panel's TinyMCE should produce a `<P>` tag.

if not then you have a filter disabling it in your setup (plugins/theme).


thanks.

**Comment by theavic** [comment]
I am still facing the same issue

**Comment by JohnnyBravoTheBest** [comment]
Hi. I don't understand why issues like these are closed without  being solved first ?! 

Why text editor removes html tags like <p> or <div> ? There should an option that allows toggling of it.

**Comment by phkoon** [comment]
Absolutely not resolved, as there are three conflicting behaviors.

One for the "visual" tab;
One for the "text" tab;
One for inline editing.

The text editor widget is a complete mess until this day.
