### ISSUE TITLE
MultiStep Form for Elementor 

### ISSUE THREAD

**Issue by Dzirt07** [pojome/elementor#5975]
Hello, 

It would be a great feature to have the ability to create a multi-step contact from 
With 
- status bar
- with checkbox 
It's a great option for marketers and other people who involved in the lead generation process 

Something similar to Contact Form 7 Multi-Step Forms
[https://wordpress.org/plugins/contact-form-7-multi-step-module/](url)

**Comment by bainternet** [comment]
Duplicate of #3911

**Comment by Seifertson** [comment]
I would also like this feature, please :)

**Comment by squasha4416** [comment]
Another strong vote for multistep form with status/selection feedback bar. 
This is a beautiful example of what would be very helpful - selections are logged at the top and provide the ability to jump back and forth within the form. https://www.travelguard.com/buy/default#tripinfo

**Comment by firededge** [comment]
A must have!! got my vote

**Comment by BetsyBurke** [comment]
How close are we to getting this multi-step form? I saw Ben Pines saying in the Facebook group that they were working on it last February. Looking forward to it too.

**Comment by sp1dev** [comment]
yes! this is a really important part of making user-friendly forms

**Comment by herooftheday77** [comment]
+1 any news to this?

**Comment by kemeny** [comment]
would be nice
