### ISSUE TITLE
Show taxonomies on custom post type

### ISSUE THREAD

**Issue by mgdgpt** [pojome/elementor#5976]
Hello guys,

I'm trying to filter my categories(Taxonomies) using your template but is not showing. 
Can you help me please?

Thanks.

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
