### ISSUE TITLE
ACF gallery field

### ISSUE THREAD

**Issue by PabloLombriz** [pojome/elementor#5977]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have a Custom post type with 2 picture galleries. When I try to design the single post I can't define which gallery to select. When I add Image Gallery, I select "Dynamic" and then select ACF Gallery Field, but "KEY" is empty! I can't select the gallery I want.
In this proyect I need to show before gallery and after gallery

**Describe the solution you'd like**
When you select ACF Gallery Field you should be able to select which gallery do you want to use.

**Describe alternatives you've considered**
I will try with other custom post type plugin.

**Additional context**

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

We can't replicate the issue you are describing,
Please contact our support at support @elementor.com for guidance in resolving this issue.

thanks.
