### ISSUE TITLE
Help!  Elementor stopped working.

### ISSUE THREAD

**Issue by betodero** [pojome/elementor#598]
Everything was working and one hour to the next, the Elementor stopped working.
Now, every time I try to create a new page comes this message:

"Loading
Close window
The session has expired

Sign in again. The login page will open in a new window. After login, you can close it and return to this page. "

What procedure should I take to re-access the Elementor?

Please...

**Comment by arielk** [comment]
Did you install any new plugin?
Please try to deactivate other plugin and let me know if your bug has been resolved

**Comment by betodero** [comment]
Hello good afternoon!

I am Brazilian and my name is Eri Ferreira, I am in Brazil and my English is not that great, but ...

Yes, there were some installed yesterday and before their valuable feedback, I was uninstalling one by one until you reach the problematic ...

This here >> Better WordPress Minify

Basically it does the following:

Allows you to minify your CSS and JS files for faster page loading for visitors. This plugin uses the PHP library Minify and Relies on WordPress's enqueueing system rather than the output buffer (will not break your website in most cases). This plugin is very customizable and easy to use.

Now everything is settled and the Elementor returned to work right.

So, I apologize and thank you also for your prompt help.

Health, wisdom and success, always!

Hug!

**Comment by arielk** [comment]
Great! thanks for sharing.

Another issue about Better WordPress Minify conflict: #411
