### ISSUE TITLE
Elementor v2.2.7 issue with SVG sizes

### ISSUE THREAD

**Issue by dollhauss** [pojome/elementor#5981]
Heya,

I just updated some sites to v2.2.7 and all the SVG images on the sites disappeared.

The SVG's are still there but the size settings on the image widget no longer works correctly.
Rolled back to v2.2.6 and all is fine.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
