### ISSUE TITLE
Elementor Editor language settings set incorrectly

### ISSUE THREAD

**Issue by woodynco** [pojome/elementor#5986]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

There is probably a bug with the Elementor Editor language settings. 
Under Elementor -> System Info -> WordPress Environment -> Language, it shows: en_US , BUT under Settings -> General -> Site Language, I have actually set my native language (Slovak).

Also under Elementor -> System Info -> User -> WP Profile lang: it says I have sk_SK (Slovak), BUT under Users -> Your Profile -> Language: I have set English (United States). 

As a result, I have my WP admin dashboard in English (which I prefer), but my Elementor editor in Slovak (which I do not prefer). 

**Describe the solution you'd like**

I want Elementor Editor language to be set based on specific user's profile preferences.

**Describe alternatives you've considered**

Settings whole Site Language to English, but it might effect SEO. (The main site language is Slovak, even if there is an English translation. Also I want my client's Elementor Editors under their user profiles to be in Slovak, so that does not work either.

**Additional context**

**Comment by bainternet** [comment]
I merged this issue with  #5148, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
