### ISSUE TITLE
Testimonial Carousel BUG, when direction=RTL

### ISSUE THREAD

**Issue by gilrahimi** [pojome/elementor#5988]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I have two pages with same elements, one in English, the other in Hebrew.
The carousel on the English page works fine.
On the Hebrew page, the carousel goes crazy. Missing texts, missing images, and cutting the "card" in two (vertically, as if the right half is just cut. you see the background colors).

![image](https://user-images.githubusercontent.com/42710330/47497335-65233180-d862-11e8-91ad-3597af3a3900.png)

## Steps to reproduce
This problem happens when visiting the site with Google Chrome browser (it does NOT happen with Firefox, and NOT with Edge !). Haven't tried it with other browsers.

to make the whole Hebrew page RTL, I set the page itself:
1) Click Settings (gear at bottom left) - opened Page Settings
2) Click: STYLE
3) Select: Custom CSS
4) Entered: "selector {direction: rtl;}"

I tried also to negate the TRL influence on the carousel by adding 
"selector {direction: ltr;}"
to the Carousel's Custom CSS. Same problem.
Tried the same with the INNER SECTION in which the carousel is, but still the same problem.

Note that the carousel has 8 "cards". I tried removing the problematic card (the one that was "cut"). but the cutting appeared now on the next card

After I gave up trying to fix this, I said maybe something went wrong with the carousel itself. decided to create a new carousel from scratch (not copying, created everything new!). again, the problem returned, exactly the same. Now I have a page with TWO exactly the same carousels, but strangely, one is moving to the left and the other to the right (LOL)

**IMPORTANT! 
Lastly, I removed the custom CSS from the page > the carousel is working fine in all three browsers (no cutting, all cards appear). So this is clearly due to the direction!!!**

## Isolating the problem
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.6.39-83.1
	PHP Version: 7.2.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://emu.org.il
	Home URL: https://emu.org.il
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Jerusalem
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.5.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.0.8
		Author: Automattic

	Elementor
		Version: 2.2.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.11
		Author: Elementor.com

	Extra Shortcodes for WP eStore
		Version: 5.1.9
		Author: Tips and Tricks HQ, Ruhul Amin

	Popup Maker
		Version: 1.7.30
		Author: WP Popup Maker

	Really Simple SSL
		Version: 3.1.1
		Author: Rogier Lankhorst, Mark Wolters

	WP Affiliate Platform
		Version: 6.2.1
		Author: Tips and Tricks HQ, Ruhul Amin

	WP eMember
		Version: v10.1.4
		Author: Tips and Tricks HQ

	WP eStore
		Version: 8.0.5
		Author: Tips and Tricks HQ, Ruhul Amin

	WP PDF Stamper
		Version: 4.6.2
		Author: Tips and Tricks HQ

== Debug ==
	Errors: 
		TypeError: Cannot read property 'errors' of undefined
			at https://emu.org.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:173895
			2018-10-14 07:35 +00:00
			x 14 times

		TypeError: Cannot read property 'on' of null
			at https://emu.org.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:213094
			2018-10-09 10:46 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://emu.org.il/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-10-09 10:46 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://emu.org.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:173895
			2018-10-08 10:30 +00:00
			x 26 times

		TypeError: Cannot read property 'get' of undefined
			at https://emu.org.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.3 - 2:217460
			2018-09-21 06:30 +00:00
			x 2 times

		TypeError: n.attributes[t.name].each is not a function
			at https://emu.org.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:9152
			2018-09-18 15:45 +00:00
			x 2 times

		TypeError: Cannot read property 'on' of null
			at https://emu.org.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:213049
			2018-09-18 15:44 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://emu.org.il/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-09-18 15:44 +00:00

		TypeError: Cannot read property 'on' of null
			at https://emu.org.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:213049
			2018-09-18 15:44 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://emu.org.il/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-09-18 15:44 +00:00

				
</details>

**Comment by arielk** [comment]
WordPress detects whether your chosen language is an RTL language then your website will be displayed in RTL, so please don't add this custom code.

to change your language please go to Settings > General in your WordPress dashboard and select the preferred RTL language such as Hebrew.
   
If you want to keep the dashboard in English, you can change your dashboard language under your profile.

Please let me know if it solves the problem.
