### ISSUE TITLE
Not really an issue but..

### ISSUE THREAD

**Issue by JeanPierreFig** [pojome/elementor#599]
Is there any way I can use this in a normal website. My website is a content management site and would like to let my users edit a html file that will be showed on a tv like a digital signage.

thank you very much.

**Comment by joshmarom** [comment]
Hi @JeanPierreFig. Thank you for your interest in Elementor.

Elementor is a WordPress plugin and will not work on a different CMS.

Check out http://grapesjs.com/ it is still in alpha but looks very promissing.
