### ISSUE TITLE
Using a custom header or footer overrides both the default header and footer of the theme

### ISSUE THREAD

**Issue by albionselimaj** [pojome/elementor#5991]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Using a custom header or footer with Elementor Pro (only one of them) seems to override both the theme's default header.php and footer.php file.

I tracked the problem down to `elementor-pro/modules/theme-builder/classes/theme-support.php` file on this part:

```php
$conditions_manager = Module::instance()->get_conditions_manager();
$headers = $conditions_manager->get_documents_for_location( 'header' );
$footers = $conditions_manager->get_documents_for_location( 'footer' );

if ( ! empty( $headers ) || ! empty( $footers ) ) {
	add_action( 'get_header', [ $this, 'get_header' ] );
	add_action( 'get_footer', [ $this, 'get_footer' ] );
}
```

This condition evaluates to true if only a custom header or only a custom footer is used, but will override both of them. I'd expect this to be:

```php
$conditions_manager = Module::instance()->get_conditions_manager();
$headers = $conditions_manager->get_documents_for_location( 'header' );
$footers = $conditions_manager->get_documents_for_location( 'footer' );

if ( ! empty( $headers ) ) {
	add_action( 'get_header', [ $this, 'get_header' ] );
}

if ( ! empty( $footers ) ) {
	add_action( 'get_footer', [ $this, 'get_footer' ] );
}
```

Is this a bug? Or is this the intended behavior?

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@albionselimaj 

This is the intended behavior and This only happens if your theme doesn't define a location for the footer via the [Theme Location API](https://developers.elementor.com/theme-locations-api/), so Elementor can't guess the correct location of your footer or if your theme's HTML tags are balanced.


thanks for the feedback.

**Comment by saigonosenpai** [comment]
Thank you @albionselimaj I am using Stike theme and they haven't done as @bainternet said. As soon as i installed elementor pro, it removed my header and footer. So i contacted the theme developers and made the change as you suggested as a temporary fix. :D

**Comment by feperrella** [comment]
> 

This is still no implemented in the Elementor Pro plugin, why?
