### ISSUE TITLE
call ‘the_content’ function error

### ISSUE THREAD

**Issue by cguntur** [pojome/elementor#5992]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

We are using Elementor with the Chamber Dashboard Business Directory. When we add the [business_directory] shortcode to an Elementor page, we get the following error: **You must call 'the_content' function in the current template, in order for Elementor to work on this page**. 

We have run thru all of Elementor's suggested fixes - https://docs.elementor.com/article/56-content-area-not-found

We have done a fresh install of WordPress and are using the TwentySeventeen theme. We have tried the TwentySixteen theme as well, same result.

## Steps to reproduce

- Install Chamber Dashboard Business Directory Plugin and elementor
- Add a couple of business listings
- Create a page with elementor and add the shortcode [business_directory] to the page using Elementor.
- Save the page.
- Exit the page.
- Click on Edit with Elementor.
- The error shows up.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 7.0.32
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://lisakdigitalmedia.com/dem04
	Home URL: http://lisakdigitalmedia.com/dem04
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -6
	Debug Mode: Inactive

== Theme ==
	Name: Chamber Beautiful
	Version: 1.2.1
	Author: Nichole Betterley
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

== Active Plugins ==
	BackWPup
		Version: 3.6.2
		Author: Inpsyde GmbH

	Better Font Awesome
		Version: 1.7.1
		Author: Mickey Kay

	Better Search
		Version: 2.2.0
		Author: Ajay D'Souza

	Chamber Dashboard Business Directory
		Version: 3.0.2
		Author: Morgan Kay, Chandrika Guntur

	Chamber Dashboard CRM
		Version: 1.4.9
		Author: Morgan Kay

	Chamber Dashboard Events Calendar
		Version: 2.2.6
		Author: Morgan Kay, Chandrika Guntur

	Chamber Dashboard Member Manager Pro
		Version: 1.3.6
		Author: Chandrika Guntur

	Chamber Dashboard Member Updater
		Version: 1.3.5
		Author: Chandrika Guntur

	Chamber Dashboard Recurring Payments
		Version: 1.5.5
		Author: Morgan Kay, Chandrika Guntur

	Column Shortcodes
		Version: 1.0
		Author: Codepress

	Contact Form 7
		Version: 5.0.4
		Author: Takayuki Miyoshi

	Contact Form 7 Honeypot
		Version: 1.13
		Author: Nocean

	Easy Google Fonts
		Version: 1.4.3
		Author: Titanium Themes

	Easy WP SMTP
		Version: 1.3.7
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 2.2.7
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.7
		Author: Till Krüss

	Login Security Solution
		Version: 0.56.0
		Author: Daniel Convissor

	ManageWP - Worker
		Version: 4.6.3
		Author: ManageWP

	PHP Compatibility Checker
		Version: 1.4.6
		Author: WP Engine

	Responsive Lightbox & Gallery
		Version: 2.0.5
		Author: dFactory

	WooCommerce
		Version: 3.5.0
		Author: Automattic

	WooCommerce Extended Coupon Features FREE
		Version: 3.0.4
		Author: Soft79

	WooCommerce Stripe Gateway
		Version: 4.1.12
		Author: WooCommerce

	WP Client Logo Carousel
		Version: 3.0.0
		Author: Aftab Husain

	WP Help
		Version: 1.5.4
		Author: Mark Jaquith

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

== Debug ==
	Errors: There are no errors to display
				
</details>

**Comment by bainternet** [comment]
I see you have contacted our support, so please continue the discussion about this with our support.

**Comment by cguntur** [comment]
Hello Raz,

 

When we wrote to support, they asked us to open a ticket in Github and now we are being told to go to support. Can one of you please help us fix the issue?

 

Chandrika Guntur

WordPress Developer

 <http://www.gcsdesign.com/> www.gcsdesign.com

**Comment by crestwebsolutions** [comment]
> 
> 
> I see you have contacted our support, so please continue the discussion about this with our support.

hey i am also facing the same issue... can you please give some fix on this... i have searched every where still getting the same error...

**Comment by cirkut** [comment]
@crestwebsolutions Please contact support for this issue. This GitHub issue was closed nearly 3 years ago. If you have specific information, please open a new GitHub issue.
