### ISSUE TITLE
Add button for CSS selection background-color to the Global Colors

### ISSUE THREAD

**Issue by shimsa** [pojome/elementor#5994]
Please add button to the Global Colors for set background color:

::selection {
  background-color: #05bf01;
  color: #ffffff;
}

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
