### ISSUE TITLE
Image lightbox - disable the lightbox if href img has a download attribute

### ISSUE THREAD

**Issue by titchpitch** [pojome/elementor#5996]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This is not a bug but more a feature enhancement. If I have Elementors image lightbox enabled, anything that is linking to an image opens in the lightbox. Even if the link has a 'download' attribute.

**Describe the solution you'd like**
When a download attribute is there to not open the lightbox but download as intended.
`<a href="xxx.jpg" download></a>`

**Describe alternatives you've considered**
Contacted Elementor Pro support and suggested to open an issue here.

**Comment by bainternet** [comment]
@titchpitch 

You can exclude links from opening in a lightbox by adding the `data-elementor-open-lightbox="no"` attribute to your link.

**Comment by sermalefico** [comment]
Please add a custom attribut to image link in Gallery pro widget to disable light box when put link to media option, i would like to use another ligthbox like Fancybox 3. Is imposible to disable lightbox without lose the href link...

**Comment by engrrajonahmed** [comment]
> > @titchpitch
> > You can exclude links from opening in a lightbox by adding the `data-elementor-open-lightbox="no"` attribute to your link.
> 
> 2020 based on new documentation, I wrote : `data-elementor-open-lightbox|no, download|true` but it doesn't work. any suggestion, please?

You used comma to separate attributes which is incorrect.
1 attribute each line.
For example,
`data-elementor-open-lightbox="no"`
`download|true`
