### ISSUE TITLE
Better Error message for the Shop Page

### ISSUE THREAD

**Issue by zeinnicholas** [pojome/elementor#5999]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I've been reading a lot of people misunderstanding the differences between Elementor and Elementor Pro, and how to build a Shop page properly for WooCommerce. I thought that it would be really good for UX if Elementor could detect when people try to edit the Shop page directly, and instead of receiving the usual error of not being able to edit the page, they could have a more specific response. 

**Describe the solution you'd like**
The solution would be to detect that the person is trying to edit the Shop page directly and properly guide them to a tutorial of Hou to create the layout using the Elementor library, or if they are not using Elementor Pro, they should be guided to purchase Elementor Pro and use the WooCommerce Archive template function. 

**Describe alternatives you've considered**
1. Using WooCommerce hooks and filters to detect the intention to edit the Shop page directly and guide the user to install Elementor Pro and follow a guide to build WooCommerce archive pages.
2. If the user already has EPro installed, guide them to use the Archive template functionality directly or through a user guide.
3. Add a simple warning that says the user can't edit that page directly. 

**Additional context**
Users that are not familiar with how Elementor or WooCommerce behave, won't know what the standard warning means. For example: 
https://m.facebook.com/groups/916625091796611?view=permalink&id=1721440371315075

**Comment by bainternet** [comment]
@zeinnicholas 

Thanks for the suggestion, we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
