### ISSUE TITLE
Update "Wider full width" problem

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#600]
I am using the newest update with the feature: "Think wider. Get full width with one click"

So i thought, it would be good, to get rid of the "Elementor Templater plugin" - because less is more (when it comes to plugins in wordpress^^). 

But it wont just work. When i open the page, then chance from "Elementor Fullwidth" to "Standardthemplate", Elementor won´t open the page. Seems no other template is working, only the "Elementor Templater plugin".

Error: "Sorry, the content area was not found in your page"

Do you have an idea or a workaround? Or do i need to delete and make the page new?

thanks for the great work! steven

**Comment by arielk** [comment]
You need to ask @WPDevHQ (the author of templater plugin) about this problem.

You can always save the page as a template and insert it in other page.

**Comment by WPDevHQ** [comment]
Hello Steve,

> So i thought, it would be good, to get rid of the "Elementor Templater plugin" - because less is more (when it comes to plugins in wordpress^^). 

Deactivating and removing the ElemenTemplater plugin will also remove the included templates. Try reactivating the plugin, change to the theme specific template and then proceed to edit the page.

If that works then you can safellly  remove ElemenTemplater and use the Elementor full width option :)

**Comment by Himaghiri** [comment]
Hi there, here is a nice tutorial for you on creating a complete full width blank page template for elementor. Actually I have used Blankslate theme and did a little customization using custom css. Its very easy. You can have a look at the css code in my tutorial https://www.youtube.com/watch?v=DvcAIrDIz1s
