### ISSUE TITLE
Blog Post module feature request: open blog articles in pop out.

### ISSUE THREAD

**Issue by marka33** [pojome/elementor#6002]
I would like to see these features in the elementor post widget:
https://diviplugins.com/downloads/portfolio-posts-pro/
These are really terrific features, especially the post opening in a lightbox.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
