### ISSUE TITLE
Ability to select a different language for Elementor in the back end to the website default language

### ISSUE THREAD

**Issue by MayaNikolova** [pojome/elementor#6003]
Web designers often work for customers all over the world. Often a website we work on is in a language that is foreign to us. WordPress allows a user to define the language they wish to see in the Dashboard in User > user language. This allows a logged in user to see the Dashboard in a language that is different from the website default set in "Settings > General". 
Elementor however displays its editor in the website default, so if a user had a different language, they are unable to understand the options in the Elementor Editor.
There is a way to have the Elementor editor revert to the default language (=English) by removing the plugin language files from the wp-content > plugins > language files.
While this fixes the Editor language, it displays all the automatic messages on the website in English instead of the website default.

Is it possible to  introduce an option to have Elementor editor (only) display in the logged in user language, while the website front end still displays the website default language, similarly to how WP manages the Dashboard.

Thank you for your consideration. Kind regards

Maya

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
I merged this issue with  #5148, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
