### ISSUE TITLE
How to change an element for all languages

### ISSUE THREAD

**Issue by mammadkoma** [pojome/elementor#6007]
Hi
I have home page that starts with a slides element.
When I change background image for a slide , this changing not appear in another languages that translated by WPML.
What should I do?
I installed these plugin : elementor , elementor pro , WPML Multilingual CMS , WPML String Translation , WPML Media , WPML Translation Management

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
