### ISSUE TITLE
Add an additional Google Font

### ISSUE THREAD

**Issue by TymC** [pojome/elementor#6009]
Hi,
I apologies for opening a new thread but the last was closed whilst not being resolved.

I am trying to write a site in Traditional Chinese, and Elementor Pro gives support for the following fonts
Noto Sans
Noto Sans JP
Noto Sans KR
but not
Noto Sans TC
Which is what I would need to use! 

I was told to convert it myself (its and OTF file which Elementor does not support) I cannot do this as conversion tools either don't support characters or don't support large file types!
You could pull the font directly from Google, as I know "Smart Slider 3" does exactly that! 

So, yes this feature would be a brilliant addition!

Kind Regards,
Tym

**Comment by bainternet** [comment]
@TymC 	

Simply add it using the provided filter hook:

```PHP
<?php
add_filter( 'elementor/fonts/additional_fonts', function ( $additional_fonts ) {
	$additional_fonts['Noto Sans TC'] = 'earlyaccess';
	return $additional_fonts;
} );
```

Elementor will do the rest.
