### ISSUE TITLE
Ability to have an Elementor section template displayed on every page

### ISSUE THREAD

**Issue by JohnMulderFrance** [pojome/elementor#6010]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

According your support this feature request is already marked as such internally, but as per his request i also post it here.
It would be nice if an elementor section template could be displayed on every page of the site in a similar fashion as headers and footers. e.g. I want a sticky button on the bottom right of every page. When pushed, this is to,open a popup where visitors can e.g. fill in a contact form. Exactly like the button you have on your site.
As a workaround is have to copy this template manually on every page of the site. Can be done oofcourse, but takes some time.

**Comment by bainternet** [comment]
This can already be done using the [Locations API](https://developers.elementor.com/theme-locations-api/)

You need to register your theme location, ex above footer:
```PHP
add_action( 'elementor/theme/register_locations', function( $elementor_theme_manager ) {

	$elementor_theme_manager->register_location(
		'above-footer',
		[
			'label' => __( 'Above Footer', 'theme-name' ),
			'multiple' => false,
			'edit_in_content' => false,
		]
	);

} );
```

then just make sure you display that in your theme, say at the top of `footer.php`:

```PHP
// Elementor `above-footer` location
if ( ! function_exists( 'elementor_theme_do_location' ) || ! elementor_theme_do_location( 'above-footer' ) ) {
	// fallback if not found or passes display conditions
}
```

thanks.
