### ISSUE TITLE
Got 502 Bad request, Nginx while opening Elementor

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#6017]
The problem is resolved with adding to .htaccess:
```
LimitRequestBody 99999999999
SubstituteMaxLineLength 10m

```
Some background: (server - SiteGround/ Geek account)
1. New installation WP 4.9.8, OceanWP latests, Elementor & Pro latest (no more plugins)
2. All system info OK, no errors.
3. Perform: New Post ==> Edit with Elementor ==> BOOOM! (502 Bad request, Nginx)
4. No error in account error log NOR WP error.log

FYI - if it helps
Any idea what is wrong??

**Comment by bainternet** [comment]
@Mulli 	

Glad you figured it out, just one correction, Nginx has no `.htaceess` support so you probably mean in the `.conf` file.
