### ISSUE TITLE
Registered locations show as unsupported - 3rd attempt to report

### ISSUE THREAD

**Issue by willcitizen** [pojome/elementor#6018]
This is now the 3rd time I am raising this issue.   This time I have had some time isolate the scenario more specifically:

Using the example code here I am able to register new locations into my project :

[https://developers.elementor.com/theme-locations-api/registering-locations/]

If the locations are created as a single item, hardcoded values, or with variable names they are fully supported as in this screenshot:

![new-template](https://user-images.githubusercontent.com/41669565/47721686-591be300-dc59-11e8-8a24-3b1b79f0c534.png)

However in my solution I am looping through values populated in an acf options page to create the locations.

As soon as I call $elementor_theme_manager->register_location from inside the foreach loop the locations that are created are only partially supported - by partially I mean that the still work and can be selected inside the template editor, but they do not show up in the add new section drop down and are labelled as unsupported in the library.

![locations-in-template](https://user-images.githubusercontent.com/41669565/47721916-d6475800-dc59-11e8-85a6-70182da707bf.png)

Here is my function that created the locations in the screenshots above - you can see both the location defined singly and the ones populated from acf in the loop do get created, so this is not an error in the function.  

@bainternet This a replication of the issue you closed twice previously which I've now replicated on a clean wordpress install with minimum installations of elementor pro and acf pro.

`function showup_register_custom_locations( $elementor_theme_manager ) {

	
	$custom_locations = get_field('theme_custom_locations', 'option');
	$custom_theme_name = get_field('custom_theme_name', 'option');

				$elementor_theme_manager->register_location(
			'main-sidebar',
			[
			'label' => __( 'Main Sidebar', 'theme-name' ),
			'multiple' => true,
			'edit_in_content' => false,
			]
			);
    	
    		foreach ($custom_locations as $custom_location) {
    		
    			$elementor_theme_manager->register_location(
				$custom_location['location_slug'],
					[
					'label' => __( $custom_location['location_label'], $custom_theme_name ),
					'multiple' => true,
					'edit_in_content' => false,
					]
				);
			}
}
`

**Comment by bainternet** [comment]
@willcitizen 	

Again, nothing has changed on our end, and you have pretty much found the issue:

>If the locations are created as a single item, hardcoded values, or with variable names they are fully supported

So it must be something in your loop.

Please contact our support at support @elementor.com with a site you have this "issue" accruing and login details, I'll try to help. Also, mention that you were directed by me and reference this issue.

thanks.
