### ISSUE TITLE
 html and visual content editor only

### ISSUE THREAD

**Issue by GlauberF** [pojome/elementor#6021]
Hello, I'm in love with the elemental hehe.
But I would like only html and visual content editor, to be able to work with my backend, out of the worpress.

is there any version or how could I do to get only the front (html and visual content editor)?

**Comment by bainternet** [comment]
@GlauberF 	

Sadly, no, not without some major custom coding.

**Comment by GlauberF** [comment]
@bainternet as much as it has a bit of coding I would like to do this, how to make this my doubt?

**Comment by bainternet** [comment]
You are more than welcome, it is open source.

Good luck.
