### ISSUE TITLE
Disable Getting Start After activating Elementor

### ISSUE THREAD

**Issue by duongancol** [pojome/elementor#6022]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi! I've sent the support request before to asking how can disable redirecting Behavior when activating Elementor. I don't want to redirect to Getting Start Page because it affects to my theme installation wizar. 
I added the code below to theme function and it didn't work
```
add_action( 'elementor/init', function() {
remove_action( 'admin_init', [ \Elementor\Plugin::$instance->admin, 'maybe_redirect_to_getting_started' ] );
} );
```
Can you check the code again?
Thanks!

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@duongancol 

use this:

```PHP
add_action( 'admin_init', function() {
	if ( did_action( 'elementor/loaded' ) ) {
		remove_action( 'admin_init', [ \Elementor\Plugin::$instance->admin, 'maybe_redirect_to_getting_started' ] );
	}
}, 1 );
```

**Comment by FlippFlopps** [comment]
Same problem, solution not working.
