### ISSUE TITLE
Add background color to Main Menu in Nav Menu widget (Elementor Pro)

### ISSUE THREAD

**Issue by WildEyedWonder** [pojome/elementor#6027]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

In the Nav Menu widget, please add Background Color to Main Menu. Dropdown has the Background Color setting but it's not there for Main Menu. See attached snapshots.

![main menu](https://user-images.githubusercontent.com/44644600/47795923-b8313480-dcf9-11e8-955f-9d547e3963f7.jpg)

![dropdown menu](https://user-images.githubusercontent.com/44644600/47795936-bbc4bb80-dcf9-11e8-9ffe-4edc9a6d6460.jpg)

**Comment by bainternet** [comment]
@WildEyedWonder 

There is a background control for the main menu in the widget level. go to advanced tab you will see it there.

**Comment by WebMagi** [comment]
> 
> 
> @WildEyedWonder
> 
> There is a background control for the main menu in the widget level. go to advanced tab you will see it there.

This is not a solution for adding a background color to individual buttons, whereby we can then control the background color for each button. The current solution in Advanced only ads a background color to the entire bar. If I'm creating a tabbed look for the menu, such as this: https://webmagi.com/clients/ufs/ , I have to hack the CSS to make it work.

Is this feature request fully covered in another issue? If not, I will create a new feature request.

**Comment by tperke** [comment]
I have the same problem. Maybe it's my bad english. But I do not see a serious solution here.

**Comment by jackbalageru** [comment]
In the main menu tab, right under ”typography” go to hover->pointer color and you can change the color.


![pointer](https://user-images.githubusercontent.com/10925005/61143649-79d05400-a4db-11e9-9bef-fefa0256ccbe.PNG)

**Comment by WebMagi** [comment]
Normal tab (not Hover tab) - this is where I need a background color.

**Comment by bizactuator** [comment]
I am trying to do this too.

I added the primary navigation menu in the "header" template for "all pages" instance...

My client wants the background color of the active page to be a solid color for each page they are on, so it is uniform across the entire website.

but I don't see a active background color for the main menu.
only hover.
and "Typography" does have an "Active" on the "Menu Menu".
but no background color for that "Active". Only "Text" color.

Can you please add a "background color" for the Active area of "Main Menu"?

![image](https://user-images.githubusercontent.com/13607432/62826804-ec3e5d80-bb87-11e9-808e-c301bf65be4b.png)

**Comment by davidamarek** [comment]
Same for me, can you please add a "background color" option for the Active area of "Main Menu" so that the currently selected menu item can have an individual background color that is separate from th entire menu background ?

**Comment by davidamarek** [comment]
Does anyone have the CSS for this that can be used until a proper solution is in place? Thanks!

**Comment by jackbalageru** [comment]
1st  Step.  Go to 'content' 'Layout' -> 'Pointer' select 'Background'
2nd Step. Go to 'style'  'Active' and Select 'pointer Color' then you'll see active menus with that background color.

I hope that helps.


![1 content -Pointer - background](https://user-images.githubusercontent.com/10925005/63372429-c2a6e280-c38e-11e9-8f5f-5f1996696967.PNG)

![2 style active menu background](https://user-images.githubusercontent.com/10925005/63372481-dd795700-c38e-11e9-8beb-797924a7fd3f.PNG)

**Comment by davidamarek** [comment]
Thanks - works great!

**Comment by thewizster** [comment]
@jackbalageru this doesn't appear to work after I upgrade a site to WP 5.4.2

**Comment by websseo** [comment]
How is this not solved after 2 years?!?!
Adding a background color to the normal menu item is still not possible. When adding your own css for menu item background, its damn hard to keep the hover background of the parent item when hovering over a sub menu item. Haven't had this much trouble adding a simple background to a nav element in a longggg time.

**Comment by dougm1966** [comment]
Still not resolved? This is a joke.

**Comment by thewizster** [comment]
I am running WP 5.5.3 and Elelmentor Version 3.0.11 and Elementor Pro Version 3.0.4 and this is available through the advanced settings now.

![elementor-nav-bgcolor](https://user-images.githubusercontent.com/1342438/98969655-ae3f9000-24d4-11eb-9fd6-1ce0b1c40462.PNG)

**Comment by davidamarek** [comment]
That's for the whole nav bar, we need to be able to set it on individual menu items in the normal state. This can be done in the hover and active states - just need it on the normal state!

**Comment by davidamarek** [comment]
Does anyone have CSS they can share for this please?

**Comment by WebMagi** [comment]
This is an example solution I used to gain control of this missing feature:

.menu-item-658 {
    background-color: #14682f !important;
    border-radius: 8px 8px 0px 0px !important;
}
.menu-item-658:hover {
    background-color: #228642 !important;
}
.menu-item-659 {
    background-color: #14682f !important;
    border-radius: 8px 8px 0px 0px !important;
}
.menu-item-659:hover {
    background-color: #228642 !important;
}
.menu-item-660 {
    background-color: #14682f !important;
    border-radius: 8px 8px 0px 0px !important;
}
.menu-item-660:hover {
    background-color: #228642 !important;
}
.menu-item-661 {
    background-color: #14682f !important;
    border-radius: 8px 8px 0px 0px !important;
}
.menu-item-661:hover {
    background-color: #228642 !important;
}
.menu-item-662 {
    background-color: #14682f !important;
    border-radius: 8px 8px 0px 0px !important;
}
.menu-item-662:hover {
    background-color: #228642 !important;
}

You just have to determine what your menu items are, the colors to use, and of course remove border radius if not needed.

**Comment by davidamarek** [comment]
Thanks!

**Comment by soxhi8** [comment]
Still a relevant problem. It is currently not possible to create menu options with a margin in between because of this. "Pointer Color" already is available for "Hover" and "Active", please just add it to "Normal" as well.

**Comment by sermalefico** [comment]
Background Normal state color for items IS BASIC all nav menus in wordpress has this. please improve nav widget. Now only can change entire nav background color.

**Comment by JennyPower** [comment]
This can be achieved by setting the background colour under Advanced tab. 

Does make sense to have it under Style though

**Comment by herooftheday77** [comment]
> This can be achieved by setting the background colour under Advanced tab.
> 
> Does make sense to have it under Style though

Did you read the whole thread...? This is not what we are searching for :) And was pointed out now several times.

Still missing a simple feature here.

**Comment by JennyPower** [comment]
@herooftheday77 My bad! The solution had worked for me, but I realise now it was just because that particular menu had only one item

**Comment by fwylo** [comment]
Hi I actually found a sort of solution for this.

If you go in to the wordpress theme customizer and customize the primary colour in your theme it will change your hover and active colour in your menu to whatever the primary colour is.

**Comment by Avinuseo** [comment]
I have the same problem trying to create a TSplus pricing floating menu https://tsplus.me/pricing/
and still dont see a solution for the original problem which is as follows:
![nav](https://user-images.githubusercontent.com/46705572/161697962-68221ce7-20ae-4286-af29-4b2dabebb2ea.png)

**Comment by Toracsrezo** [comment]
I Found this workaround to add the same background color to all menu items in the **NORMAL** state :


```
.elementor-item:not(:hover):not(:focus):not(.elementor-item-active):not(.highlighted):after, .elementor-item:not(:hover):not(:focus):not(.elementor-item-active):not(.highlighted):before{
	opacity: 1!important;
	background-color: red!important;
}
```

**Comment by medleyelite** [comment]
Another way I found to do this is by adding the background color under the Advanced tab, then adding a white (or background colored) border using CSS. This Youtube video has great instruction on how to do that: https://www.youtube.com/watch?v=fuSFaozNBGQ

The custom CSS should look something like this, added under the Advanced tab for the nav menu widget:

.elementor-3782 .elementor-element.elementor-element-ce07698 .elementor-nav-menu--main .elementor-item {
    border: solid 3px white;
}

**Comment by rvscc** [comment]
Pfffff......... just go for the new 'astra spectra' page builder. The whole takeover of the cms, the errors, and not even a normal  way to set the nav background color is making me crazy.

**Comment by DownHouse** [comment]
6 years have passed. Developers are still unable to implement this complex feature.

`selector a:not(:hover):not(:focus):not(.elementor-item-active):not(.highlighted){
	background-color: #000;
}`

**Comment by vgstef** [comment]
> 1. Advanced / Background / Color
> 
>     2. Diveder / ON
> 
>     3. Diverder  Height 50 - 100 %
> 

Sorry, but this doesn't work if we want rounded borders.

Why isn't Elementor fixing this simple issue dating back 2018 ? I'm speechless...

And more over, why is this thread closed?
