### ISSUE TITLE
Elementor doesn't finish loading

### ISSUE THREAD

**Issue by J-Elledge** [pojome/elementor#603]
Just downloaded and installed Elementor, and I'm unable to get it working.  When I click Edit with Elementor, it does open up, but the main window never pulls up, I only get the spinning wheel (bad description, see image).  I've turned off W3 Total Cache, but no luck there.

![screen shot 2016-09-21 at 10 53 55 am](https://cloud.githubusercontent.com/assets/22350246/18718617/ccb3fbf0-7fe9-11e6-816b-b67c2652e97a.png)

**Comment by J-Elledge** [comment]
Actually, just tested with all my plugins turned off, but no dice.

**Comment by joshmarom** [comment]
It might be a a conflict with your theme. 
Which theme are you using?

**Comment by J-Elledge** [comment]
I'm using the Business theme from Graph Paper Press.  I actually found out about Elementor from their blog, so I would imagine that it would integrate well.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
