### ISSUE TITLE
Change dropdown choices programmatically

### ISSUE THREAD

**Issue by scott8035** [pojome/elementor#6030]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Need a way to change the valid choices in a select dropdown programmatically. For example, I may want a dropdown to list only the forums a user has subscribed to rather than all forums.

**Describe the solution you'd like**
A filter for select values (and other control values) in the forms API.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by bainternet** [comment]
@scott8035 

There is a filters for you to use already:

```PHP
/**
 * Render form field.
 *
 * Filters the field rendered by Elementor Forms.
 *
 * @since 1.0.0
 *
 * @param array $item       The field value.
 * @param int   $item_index The field index.
 * @param Form  $this       An instance of the form.
 */
$item = apply_filters( 'elementor_pro/forms/render/item', $item, $item_index, $this );
```
which runs before each field is rendred, or:

```PHP
/**
 * Render form field.
 *
 * Filters the field rendered by Elementor Forms.
 *
 * The dynamic portion of the hook name, `$field_type`, refers to the field type.
 *
 * @since 1.0.0
 *
 * @param array $item       The field value.
 * @param int   $item_index The field index.
 * @param Form  $this       An instance of the form.
 */
$item = apply_filters( "elementor_pro/forms/render/item/{$field_type}", $item, $item_index, $this );
```
Which runs per each field type.

so for example:

```PHP
add_filter( 'elementor_pro/forms/render/item/select', function( $item, $index, $form ) {
	// make sure it the correct form
	if ( 'My_Form' === $this->get_settings_for_display( 'form_name' ) ) {
		// make sure it the select field
		if ( 'My_select_field_id' === $item['_id'] ) {
			// Set whatever options you want in the accepted format
			$item['options'] = "Label1|value1\n
			LabelTwo|val2\n
			User-X|user_id";
		}
	}
	return $item;
}, 10, 3 );

thank.

**Comment by scott8035** [comment]
Thanks for your quick and thorough explanation, Raz.

---scott

Contact info: scott8035@gmail.com | 414-469-8241 | LinkedIn
<http://www.linkedin.com/in/scottthomason>

**Comment by scott8035** [comment]
Note to others: in the filter above, the third line should read:

`$form->get_settings_for_display( 'form_name' )`

...if you're adding this filter in the normal context of functions.php (or other global context).

**Comment by andersonmichel** [comment]
Is this hook still working? elementor_pro/forms/render/item

I cant see it in documentation site...

Have tested here but look likes didnt work

**Comment by bennol** [comment]
Here's an updated example that is working for Elementor `v2.9.4`:
- `$item['_id']` changed to `$item['custom_id']`
- `$item['options']` changed to `$item['field_options']`

Replace `YOUR_FORM_NAME` with the name of your form and `YOUR_FIELD_ID` with the id you specified for your select field.

```
add_filter( 'elementor_pro/forms/render/item/select', function( $item, $index, $form ) {
    if ( 'YOUR_FORM_NAME' === $form->get_settings_for_display( 'form_name' ) ) {
        if ( 'YOUR_FIELD_ID' === $item['custom_id'] ) {
            // Set whatever options you want in the accepted format
            $item['field_options'] = "Please select a value:|\nLabel 1|value_1\nLabel 2|value_1";
        }
    }
    return $item;
}, 10, 3 );
```

**Comment by GitHubington** [comment]
The following works for my use case (_form id, item id_)...
```
add_filter("elementor_pro/forms/render/item/select", function($item, $index, $form) {
	$form_id = "TEST_FORM";
	$item_id = "TEST_ITEM";
	if ($form_id === $form->get_settings_for_display("form_id"))
		if ($item_id === $item["custom_id"]) 
			$item["field_options"] = "Please select a value:|\n" . "Label 1|value_1\n" . "Label 2|value_1";
	return $item;
}, 10, 3);
```
