### ISSUE TITLE
Add "Child Pages of Parent" To "Posts" Widget

### ISSUE THREAD

**Issue by stevenmonson** [pojome/elementor#6031]
It would be so nice if the **_"Posts"_** element could automatically display **all children of a specific parent page.**

For example, sometimes I have a _"Services"_ page with 10 child-pages.  I'll add a _**Posts**_ Element to the _Services_ page, with link to each of its children. 

Right now, I have to select each child-page via **"manual selection"**.  This is fine when there are just a few pages.  But when the list is long or frequently updated, it can be tedious.  

I frequenltly find myself wishing I could just say **_"display all children of the Services page"_**  and have it automatically update as I add more pages. 

Perhaps you could add a field above (or below) the _**Exclude**_ field (under **_Query_**) that says **_"display child pages of..."_** and then let the user choose a page, and filter the query accordingly.

Could this be added?  I'd love to hear your thoughts.

**Comment by black-eye** [comment]
+1
It would be so handy for index pages.

**Comment by black-eye** [comment]
+1
It would be so handy for index pages.

**Comment by bainternet** [comment]
@stevenmonson 	

This can be easily done using [Custom Query Filter](https://developers.elementor.com/custom-query-filter/) ex:

```PHP
// Showing children of current page in Posts Widget
add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query ) {
	// Get current post tags
	$current_page = get_queried_object_id();
	// Modify the query
	$query->set( 'post_parent', $current_page );
} );
```

**Comment by stevenmonson** [comment]
Do I need to add this to the functions.php file or somewhere else?

**Comment by stevenmonson** [comment]
One more similar question... What query would I use to get siblings pages (pages that share the same parent page)?

**Comment by valentincauro** [comment]
Hi folks, you saved my life !
I don't understand why those kind of query aren't in the theme builder, but nevermind 😅

**Comment by valentincauro** [comment]
> One more similar question... What query would I use to get siblings pages (pages that share the same parent page)?

+1 would love the query for sibling :'( 

Could you help us @bainternet plz ?

Thx

**Comment by BorjaAV** [comment]
I have a couple of questions:

1- I have to paste the code in functions.php?
2- If I want to get pages and not post what is the code?

Thanks

**Comment by stevenmonson** [comment]
@BorjaAV 
1. Yes, you'll need to edit the functions.php file to add this code. But I'd only recommend doing so if you have some knowledge about editing template files.
2. The same code will work for both pages and posts.

**Comment by BorjaAV** [comment]
> @BorjaAV
> 
> 1. Yes, you'll need to edit the functions.php file to add this code. But I'd only recommend doing so if you have some knowledge about editing template files.  Don't edit the parent theme (in most cases), make sure you create a child theme.
> 2. The same code will work for both pages and posts, so no problem there! :)

Thank you so much. This is exactly what i want

**Comment by BorjaAV** [comment]
Hello Again! Just one more Question

If I want to use the same method to show the posts/pages that they have the same level/patern? What will be the code? I am so amateur with the wordpress code...Thank you so much!!

**Comment by vgstef** [comment]
Me too, I'd like to know want code to use for child/sibling pages for the custom query.

**Comment by megabrian** [comment]
Elementor team has deprecated the previous code:
`elementor_pro/posts/query/`

Should be written like this in functions.php now:

`add_action( 'elementor/query/children_filter', function( $query ) {
	$current_pageID = get_queried_object_id();
	// Modify the query	
	$query->set( 'post_parent', $current_pageID );
} );
`
That uses children_filter in the custom query ID field of the posts widget.

**Comment by andyslack** [comment]
+1 to the original suggestion of having this option build in.

I tried the above suggestion @megabrian but its not working frustratingly, also followed: https://developers.elementor.com/custom-query-filter/

But for some reason my custom filter is not showing 

![Screenshot 2020-04-28 at 15 24 36](https://user-images.githubusercontent.com/3747768/80492528-72900f00-8964-11ea-9170-9dc30c5908a2.png)

**Comment by ruelluna** [comment]
As of today,

It works with Source: Pages or Source: Related.

![Screenshot 2020-06-07 19 56 19](https://user-images.githubusercontent.com/982036/83968112-7b77e700-a8f9-11ea-91ec-e4244bdb2073.png)

**Comment by ex-avenger** [comment]
+1

**Comment by gotravelnow** [comment]
Thanks for the code for child pages, worked like a charm. I would really like to be able to list archive pages that are of a specific taxonomy (traveljournals) connected to a page with the help of Advanced Custom Fields. To give an example, I've been to New York a number of times and written travel journals, for each there's an archive page that I want to list on the New York page. 
I've tried to understand how to do that from several sources but can't figure it out. Would be really grateful for any suggestions and ideas.  

add_action( 'elementor_pro/posts/query/my_traveljournals', function( $query ) {
	
	$traveljournals = get_queried_object();
        $taxonomy = $traveljournals->taxonomy;
        $term_id = $traveljournals->term_id;  
	
	$query->set( 'post_id', $term_id);

} );

**Comment by JDBem** [comment]
This is definitely something Elementor should have natively as a drop-down option. 

I've tried everything @andyslack did but it still doesn't seem to work at all. 

```
// Showing children of current page in Posts Widget
add_action( 'elementor/query/my_custom_filter', function( $query ) {
    // Get current post tags
    $current_page = get_queried_object_id();
    // Modify the query
    $query->set( 'post_parent', $current_page );
} );
```

Any ideas of what could be wrong @bainternet?

**Comment by RigasIliopoulos** [comment]
what [megabrian] meant, and it works is that:

// Showing children of current page in Posts Widget
    add_action( 'elementor/query/my_custom_filter', function( $query ) {
	// Get current post tags
    $current_pageID = get_queried_object_id();
	// Modify the query
    $query->set( 'post_parent', $current_pageID );
} );

**Comment by jedihacks** [comment]
Thanks everyone!   

If anyone has custom post types, I was having difficulty implementing this at first but then I realized we must select the Source to be that custom type first.

Then the query provided by @megabrian @bainternet works.  Tested on v5.9 Wordpress

<img width="829" alt="Screen Shot 2022-02-12 at 11 43 01 AM" src="https://user-images.githubusercontent.com/996175/153720032-2d5fae5b-f601-42f5-8f6a-5742eace12d3.png">

**Comment by DigitalBerry** [comment]
I can't get this working, anyone able to help?

I tried this code...
`// Showing children of current page in Posts Widget
add_action( 'elementor/query/my_custom_filter', function( $query ) {
// Get current post tags
$current_pageID = get_queried_object_id();
// Modify the query
$query->set( 'post_parent', $current_pageID );
} );`

What needs editing in that to connect to my child pages? I used "my_custom_filter" in the Query ID, that correct?

Thanks

**Comment by stevenmonson** [comment]
> I can't get this working, anyone able to help?
> 
> I tried this code... `// Showing children of current page in Posts Widget add_action( 'elementor/query/my_custom_filter', function( $query ) { // Get current post tags $current_pageID = get_queried_object_id(); // Modify the query $query->set( 'post_parent', $current_pageID ); } );`
> 
> What needs editing in that to connect to my child pages? I used "my_custom_filter" in the Query ID, that correct?
> 
> Thanks

I'm not sure if this is happening in your actual code or not, but **the code that you pasted doesn't have any line breaks** which means  the "//"  is commenting out the entire code.

For what it's worth, here's the code that I use:  

```
// Shows children of current page in Posts Widget. 
// Put the word 'children' in the 'Query ID' field.
// Read more at: https://developers.elementor.com/custom-query-filter

add_action( 'elementor/query/children', function( $query ) { 
	$current_pageID = get_queried_object_id(); 
	// Modify the query	
	$query->set( 'post_parent', $current_pageID ); 
} );
```
It's basically the same code as above but I renamed it "children" and included some more instructions in the comments to make it easier to follow.

**Comment by MartyFly** [comment]
@stevenmonson this one works for me (using Pages as source)

**Comment by ChobPT** [comment]
Just expanding upon the above example a bit:

This will get all pages that share the same parent:

`
add_action( 'elementor/query/get_siblings', function( $query ) { 
	$current_pageID = get_queried_object_id(); 
	// Modify the query	
	$query->set( 'post_parent', wp_get_post_parent_id($current_pageID) ); 
} );
`

Add this to your functions.php file on the theme folder. Use get_siblings as the Query ID on the element.

Cheers

**Comment by Mengokai** [comment]
Tweaking the Elementor slug worked for me. 

> add_action( 'elementor_pro/posts/query/my_custom_filter', function( $query )

-> add_action( 'elementor/query/my_children_filter', function( $query )

Reference: https://developers.elementor.com/docs/hooks/custom-query-filter/  

Working example based on first suggestion:

```
// Showing children of current page in Posts Widget
add_action( 'elementor/query/my_children_filter', function( $query ) {
	// Get current post tags
	$current_page = get_queried_object_id();
	// Modify the query
	$query->set( 'post_parent', $current_page );
} );
```

**Comment by ribrafaella** [comment]
Any of that is working for me :(
I'm using a CPT, but elementor is showing all the posts, not filtering.

I've used all examples here, none of them seem to work. Perhaps is it because I'm using CPT UI to create the CPT?

![image](https://github.com/elementor/elementor/assets/41843475/800bf44f-d5b7-4347-b691-a54e8b9584eb)

**Comment by robwent** [comment]
@Moreit11 

Try this:

```php
/**
 * Elementor filter to show only children of the current page
 * https://developers.elementor.com/docs/hooks/custom-query-filter/
 *
 * @param WP_Query $query
 */
add_action( 'elementor/query/post_child_filter', function ( $query ) {
	$query->set( 'post_type', 'any' );
	$query->set( 'post_parent', get_queried_object_id() );
} );
```
