### ISSUE TITLE
Tabs Rendering Race Condition

### ISSUE THREAD

**Issue by pcfreak30** [pojome/elementor#6032]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

When loading js  and/or css async, the default tab being opened if configured can break. This appears to be because `.show()` does not do anything very early in the page load (doesnt set any styles). This should be changed to `css('display','block')` and `css('display','none')` calls instead. It may be a certain version of jquery but it is the latest version of WordPress so its an edge case and a pretty simple fix.

## Steps to reproduce

Thus bug would be hard to reproduce given the context and nature of it as it relies use of other plugins to cause the bad browser behavior with jquery itself.

**Comment by bainternet** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.
