### ISSUE TITLE
Different images for Desktop, Tablet, and Mobile (for design options and mobile speed)

### ISSUE THREAD

**Issue by JonB7** [pojome/elementor#6034]
Speeding up mobile website and choosing different images.

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Speeding up a website for mobile use.

**Describe the solution you'd like**
I'd like the option of choosing different images for desktop, tablet, and mobile. This would include anything that has a place to put an image, including the image element, banners, section backgrounds, column backgrounds, etc. This would allow us to have high-quality images for desktop, and medium quality for tablets and smaller size images for mobile to speed up the website for mobile users.

**Describe alternatives you've considered**
So far I have duplicated images and banners, uploaded a mobile sized image and then used the hide feature. This is okay, but if a client wants changes, then changes need to be made to both instead of just one.

**Additional context**
Here is an email I sent to your team:
I have one feature request that has been bugging me for a while and decided I might as well say something. So, when it comes to mobile websites, we want our clients' websites to load fast and one way to do this is to use smaller sized images for mobile than we use for desktop view. Currently, I do this by duplicating a banner or image and then uploading another sized image and using the "hide on mobile, tablet, desktop" feature to hide the desktop image and show the mobile. 

Feature Request: Looking at how well y'all have already added many areas in the settings panel for us to change the look for desktop, tablet, and phone, I was wondering if you would consider adding this to images; the little icon where we can choose different images. That way we can upload our great quality images for desktop, a medium sized for tablet and a small size for mobile.

**Comment by bainternet** [comment]
You can add a widget for each device and set the which one to show on which device, as for backgrounds follow this: #2355

thanks.

**Comment by kate-ann** [comment]
I agree with Jon on this. I custom themes we can set which image will be loaded per device and for retina displays too. Duplicating images and hiding them on mobile, tablet devices are duplicated content which is not good for SEO and doubles or triples the page load times.

**Comment by patmatt69** [comment]
Hi kate-ann. I would like to understand your comment better. In the 1st sentence you say "I custom themes we can set which image will be loaded per device and for retina displays too". In your 2nd sentence you say "Duplicating images and hiding them on mobile, tablet devices are duplicated content" 

The two seem to conflict with each other. Are you saying you do have different image sizes for each devise or no? Sorry. I'm confused. Thanks in advance for your feedback!

**Comment by samuelgoldenbaum** [comment]
> You can add an image widget for each device and set the which one to show on which device, as for backgrounds follow this: #2355
> 
> thanks.

This is not quite accurate. Simply hiding the parent via `display:none;` does not guarantee the img src is not downloaded. This issue should not be closed and image widgets should allow multiple responsive images set via `srcset`

**Comment by samuelgoldenbaum** [comment]
I have started a [Custom Widget](https://github.com/samuelgoldenbaum/elementor-responsive-image) for this.
