### ISSUE TITLE
Login Widget Request

### ISSUE THREAD

**Issue by KOHPM** [pojome/elementor#6035]
Hi 

with elementor login widget When clicked on login button while fields are empty it redirects to /wp-login page instead or requiring fields to be filled

Need 2 features

1- fields to be required, and not to redirect to wp-login page

2- and need also to hide widget to logout users

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by KOHPM** [comment]
## Prerequisites
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )


**What problem is your feature request going to solve? Please describe.**
Prevent Login widget to redirect users to WP-login default, and allow user to hide/show widget to login/logout users

**Describe the solution you'd like**
1- login widget to include feature to require fields, and not to redirect to default wp-login page

2- feature to show/hide widget to login/logout users

*Describe alternatives you've considered**
None

**Additional context**
None
