### ISSUE TITLE
New Google ReCaptcha v3 not working?

### ISSUE THREAD

**Issue by Matherone** [pojome/elementor#6039]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

Google recently (apparently late October 2018) launched reCaptcha v3. 

ReCaptcha version 3 seems **not to work** on the latest version of Elementor (2.2.7). I have tried to use it in the Elementor contact form widget.

Expected result: nothing visible, Recaptcha v3 magic happening in background.

Actual result: red error text messages displayed on live site.

Old Recaptcha version two **works just fine**. Using it is a workaround. However, most Elementor users will naturally choose the latest Recaptcha version and may thus encounter this error. 

## Steps to reproduce

1) Apply for a reCapcha version three account at:
https://www.google.com/recaptcha/admin
...and get the new v3 keys (they are different from v2 keys).

2) Paste the reCapcha version three site key and secret key into:
WP Dashboard  >  Elementor  >  Settings  >  Integrations  >  Recaptcha

3) Use an Elementor Contact form widget on a web page. In the contact form widget, activate a Recaptcha module. Save.

4) Observe red text error messages appear live on the site where the recaptcha box would have been (hidden).

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

Please note that I'm using a live production site only, so I have **not** disabled theme or plugins. But I suspect the problem would prevail.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v
	PHP Version: 7.0.6
	PHP Max Input Vars: 1000
	PHP Max Post Size: 52428800
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://holygon.com
	Home URL: https://holygon.com
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Stockholm
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.5.31
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

== Active Plugins ==
	Elementor
		Version: 2.2.7
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.0-beta1
		Author: Namogo

	Elementor Pro
		Version: 2.1.11
		Author: Elementor.com

	Ocean Extra
		Version: 1.4.29
		Author: OceanWP

	Slimstat Analytics
		Version: 4.7.8.3
		Author: Jason Crouse

	WP Mail SMTP
		Version: 1.3.3
		Author: WPForms

== Debug ==
	Errors: 
		TypeError: setting getter-only property "type"
			at https://holygon.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.7 - 2:86630
			2018-11-01 12:55 +00:00

		TypeError: this.search is undefined
			at https://holygon.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.7 - 2:239282
			2018-11-01 12:31 +00:00

		TypeError: setting getter-only property "type"
			at https://holygon.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.6 - 2:86630
			2018-10-24 14:41 +00:00

		TypeError: setting getter-only property "type"
			at https://holygon.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:86630
			2018-10-18 11:16 +00:00
			x 9 times

		TypeError: Cannot read property 'pageYOffset' of undefined
			at https://holygon.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 - 4:30810
			2017-07-30 13:31 +00:00
			x 13 times

		TypeError: Cannot read property 'removeClass' of undefined
			at https://holygon.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.3 - 5:11873
			2017-07-12 11:44 +00:00

		TypeError: Cannot read property 'add' of null
			at https://holygon.com/wp-content/plugins/elementor/assets/lib/slick/slick.min.js?ver=1.6.0 - 17:18995
			2017-07-09 14:01 +00:00

		TypeError: Cannot read property 'pageYOffset' of undefined
			at https://holygon.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 - 4:30810
			2017-06-24 09:41 +00:00
			x 51 times

				
</details>

**Comment by bainternet** [comment]
@Matherone 	

This is not an issue, more of a feature request, Elementor supports Recaptcha V2 for now and we are looking at implementing V3 support in the future if we see a large demand for it.

thanks.

**Comment by Matherone** [comment]
Thank you. 

That makes sense – if you work as an Elementor coder. 

If you are an Elementor user – how are you supposed to know which Recaptcha versions are supported and wich ones are not?

If Elementor supports certain versions of Recaptcha only, and not other versions of Recaptcha, please **clearly state so** somewhere in the widget and in the integration UI. Just writing a line of text will suffice.

That way, you will help attentive Elementor users to not have to go through error searching, emailing Elementor, and so on.

**Comment by DoctorMicro** [comment]
I have been getting a lot of Contact Spam and found that Google admits that the reCaptcha v2 is no longer able to combat spam as well so they created [reCaptcha version 3](https://developers.google.com/recaptcha/docs/v3) and are suggesting if we need **to stop the Contact Spam to update all our sites to V3.**

I ask support about this and my reply was: 

> I am afraid this is not possible at this time to use reCaptcha 3 for the Elementor form widget and that your request requires custom codes or modifying the existing ones which actually is beyond the scope of our support. We provide support for existing features only.

I looked around and I found this thread and one on adding reCaptcha to the Login also. 

**Is there any timeframe on when this will be added?**

**Comment by StephDLaw** [comment]
I have the same problem and would very much like to see a resolution as soon as possible. We have created a new website and the keys we generated are invalid in Elementor. Therefore, we have no possibility to filter spam. Please update Elementor to recognize v3.

**Comment by plxrisa** [comment]
+1

**Comment by IanJSaul** [comment]
+1

**Comment by p3k1n0** [comment]
The Font Awesome 5 integration, a thread that I followed in the past 3 months, was opened in november 2017... and after A LOT of requests and 18 months of waiting, seems like it will be part of 2.60
The Elementor team gave an answer in the thread, after a lot of time, only when a developer from Font Awesome showed up saying that he would have liked to help with the integration.
Don't give up, but don't expect too much. Exèect nothing, in fact.

That said, an update to reCaptcha v3 would be VERY appreciated

**Comment by ituk** [comment]
+1

**Comment by benravetta** [comment]
It makes logical sense to upgrade to v3, please do this ASAP. Most contact form plugins in the repo now support v3, Elementor should be leading the way for innovation.

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v2.6.0

Feel free to update

Thanks!
