### ISSUE TITLE
Main Menu Design & slideshow

### ISSUE THREAD

**Issue by axiomteck** [pojome/elementor#604]
how can i edit or style the main menu with elementor and how can i create a slideshow. also is elementor is going to be white paper rebrand

**Comment by arielk** [comment]
Usually you can edit the menu using the theme. You can create a slideshow, please read the following guide: http://docs.elementor.com/article/52-image-carousel

The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/
