### ISSUE TITLE
Global Element Management + Make Only Their Content Editable Without Unlinking

### ISSUE THREAD

**Issue by willtaylordesign** [pojome/elementor#6044]
The following feature requests are so closely related and sequential that I fear separating them would cause confusion.

**Request** - 
1. Without unlinking a global element from its master, be able to alter only its text content while stylistic attributes (such as colors, fonts, shadows, and more) remain dynamically associated with the master. Global elements to behave more like style templates that can be edited, applied, and assigned to any given element id with matching type. To additionally maintain the support of its current behavior, a checkbox could perhaps be added when naming a new global element that gives the option to "save text content with this global element."
2. Ability to set and update an element type's "default style." Ex: currently, when placing a new button on the screen, its default "style" has a green background.
3. For global elements of the same type to be grouped together in the global elements selection list. Each sort of "sub-list" could simply be separated by a title line.

*Use Case - Quickly making universal (but simple) changes at a client's request. Ex: The same global button is added in two different sections of the same page. The first button needs to read "request a demo" and the other "learn more." To accomplish this, both will have to be unlinked from the master. Now, when a non-text aspect of these similar buttons needs to be changed, the change has to be manually made on each individual element manually, taking twice the amount of time as it would to simply change the global while maintaining the elements' text.

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
