### ISSUE TITLE
Enable Elementor Editor for Archive Pages

### ISSUE THREAD

**Issue by nspell** [pojome/elementor#605]
Hi Elementor crew,

Firstly, I want to say that I just downloaded Elementor a couple days ago and I love it! Already moving away from Divi and Page Builder Sandwich because I love it so much.

I hope that I'm going through the appropriate channels to ask this question. I've been digging for over an hour and haven't found a clear answer on this, so I'm asking here:

Is there a way to enable Elementor editing features on archive pages—blog archive, custom post type archives (e.g. Jetpack-enabled portfolio archive), etc.? I'm aware that Elementor can be enabled on custom post types, but so far I haven't found a way to use it to construct an archive.

Does this feature exist? If not, will it exist in the future?

If it helps, I'm using GeneratePress (saw Ben Pines suggest it in a few comments on various blogs and Youtube). 

Thanks, and again hope that this is the correct place to ask. If not, sincere apologies.

**Comment by arielk** [comment]
For now this feature does not exist yet, but we're working on it.
You can read more about this request here: #262

**Comment by remyrichard** [comment]
Hi !
I'm searching a way to design archive pages with elementor.
Maybe it would be possible with this plugin (https://fr.wordpress.org/plugins/enhanced-category-pages/) but it seems not to be compatible...
What do you think about this way ? Possible one day ? Or do you have another solution ?

I know posts widgets exists but if we use on a page type, i think it's not the right way becaus template hierarchy and seo will not be good.

Thank you

**Comment by carasmo** [comment]
Right now you can create your CPT as usual and make your posts for that CPT. Then create a Elementor template and bring in your stuff, use the Posts Widget (pro) to create your grid with pagination and other Elementor elements. Save it. Then in pro grab that shortcode (pro) and on the cpt-archive.php in your theme folder ([read more here](https://developer.wordpress.org/themes/basics/template-hierarchy/)), use the do_shortcode(); function.

**Comment by remyrichard** [comment]
Hi Christina ... thank you ... I will try this

**Comment by dudaster** [comment]
you can try to use my theme, i used it on a dozen of websites so far and perfected it over a year now: https://github.com/dudaster/eletheme/

**Comment by TheCrystalRose** [comment]
Is there any updates on Elementor creating an Archive builder for Custom Post Types and Taxonomies?

**Comment by michelmarcondes** [comment]
> Is there any updates on Elementor creating an Archive builder for Custom Post Types and Taxonomies?

Same issue here....
Updates?

**Comment by shirokoweb** [comment]
Seems they are more focused on high candy stuff 'aka Divi style' rather than real stuff.
No support yet for this request after nearly 3 years...

**Comment by javiercriado** [comment]
why is this closed?
this is a very important feature missing in Elementor

I don't know why Elementor moderators keep closing this unsolved issue

**Comment by barrychapman** [comment]
what the heck?! Why was this closed?

**Comment by TheCrystalRose** [comment]
I wish I knew why this was closed. It was originally brought to their attention over 2 years ago. I really enjoy using Elementor, but it’s upsetting that some really important features aren’t being addressed, and I could really use the ability to design the Archive pages according to Custom Post Types.

**Comment by TomRaraAvis** [comment]
#4440 [Feature request] Posts / Archive loop item template designer
