### ISSUE TITLE
ACF issue: errors showing up in error log with acf-image.php

### ISSUE THREAD

**Issue by bkjproductions** [pojome/elementor#6051]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
While we love the Advanced Custom Fields (ACF) integration with Elementor, it doesn't seem to want to show images for some reason. Looking at PHP error log there are a couple of errors within the acf-image.php file that must be the problem?

The error is:
PHP Warning:  Illegal string offset 'id' in /home/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php on line 84
PHP Warning:  Illegal string offset 'url' in /home/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php on line 85

## Steps to reproduce
Create ACF field for an image
Create a Product in WooCommerce.
Insert an image into the ACF field.
Use Elementor to define where the "dynamic content" (that ACF field) should show up in your layout
View the Product. 
Image does not appear.
The URL-as-text seems to come across but for whatever reason the image won't show up.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 5.6.38
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.example.com/site
	Home URL: https://www.example.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Storefront
	Version: 2.3.5
	Author: Automattic
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 4.3.8
		Author: AdminColumns.com

	Admin Columns Pro - Advanced Custom Fields (ACF)
		Version: 2.3.2
		Author: Admin Columns

	Advanced Custom Fields PRO
		Version: 5.7.7
		Author: Elliot Condon

	Better Search Replace
		Version: 1.3.2
		Author: Delicious Brains

	BKJ Functions
		Version: 1.1.4
		Author: Various

	Classic Editor
		Version: 0.5
		Author: WordPress Contributors

	Conditional WooCommerce Checkout Field
		Version: 1.0.16
		Author: Scott DeLuzio

	Contact Form 7
		Version: 5.0.5
		Author: Takayuki Miyoshi

	Contact Form DB
		Version: 2.10.36
		Author: Michael Simpson

	Custom Related Products for WooCommerce
		Version: 1.3
		Author: Scott Nelle

	Elementor
		Version: 2.2.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.11
		Author: Elementor.com

	GDPR Personal Data Reports
		Version: 1.0.5
		Author: Willows Consulting Ltd.

	GitHub Updater
		Version: 8.4.1
		Author: Andy Fragen

	Jetpack by WordPress.com
		Version: 6.6.1
		Author: Automattic

	Login Logger
		Version: 1.2.1
		Author: Stephen Merriman

	ManageWP - Worker
		Version: 4.6.3
		Author: ManageWP

	Misc
		Version: 1.3
		Author: BKJ Productions

	Simple Optimizer
		Version: 1.2.7
		Author: MyWebsiteAdvisor

	User Switching
		Version: 1.4.0
		Author: John Blackbourn & contributors

	White Label CMS
		Version: 1.6.4
		Author: www.videousermanuals.com

	Woo Checkout Field Editor Pro
		Version: 1.2.9
		Author: ThemeHiGH

	WooCommerce
		Version: 3.5.1
		Author: Automattic

	WooCommerce Colors
		Version: 1.0.7
		Author: WooThemes

	WooCommerce Direct Checkout
		Version: 1.1.2
		Author: Terry Tsang

	WooCommerce Email Test
		Version: 1.10
		Author: RaiserWeb

	WooCommerce Services
		Version: 1.17.1
		Author: Automattic

	WooCommerce Smart Collection
		Version: 1.0.13
		Author: Down Town

	WooCommerce Stripe Gateway
		Version: 4.1.12
		Author: WooCommerce

	Woo Terms & Conditions Text
		Version: 1.0.3
		Author: Raaj Trambadia

	WP Client Reference
		Version: 0.42
		Author: Steve Grunwell

	WP GDPR Compliance
		Version: 1.4.2
		Author: Van Ons

	WP Migrate DB
		Version: 1.0.4
		Author: Delicious Brains

	WP Version in Query String Modifier
		Version: 1.0.0.7
		Author: joesat


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP


== Debug ==
	Errors: 
		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0101540938655 - 1:563
			2018-10-30 22:31 +00:00

		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0101540938574 - 1:563
			2018-10-30 22:30 +00:00

		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0101540937824 - 1:563
			2018-10-30 22:17 +00:00

		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0101540936136 - 1:563
			2018-10-30 21:49 +00:00

		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0101540936111 - 1:563
			2018-10-30 21:49 +00:00

		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0101540936012 - 1:563
			2018-10-30 21:47 +00:00

		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0101540935585 - 1:563
			2018-10-30 21:40 +00:00

		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0081540574591 - 1:563
			2018-10-26 17:23 +00:00

		TypeError: Cannot read property 'toString' of undefined
			at https://www.example.com/site/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=0081540573073 - 1:563
			2018-10-26 16:57 +00:00

		TypeError: Cannot read property 'currentView' of undefined
			at https://www.example.com/site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=0081540571629 - 2:239323
			2018-10-26 16:51 +00:00

				
```
</details>

![image](https://user-images.githubusercontent.com/4551281/47876893-d332a000-ddf0-11e8-827c-717d2fcba85d.png)

**Comment by bkjproductions** [comment]
It is possible that the code around line 74 is not correct. 
I have been able to get rid of the error with this revision starting at line 74, though I still cannot get my image to display, at least the error is not generated (and the $image_data array on lines 84-85 then has some data, though I am not sure if the "id" value that I am substituting with the meta_key is correct.

`			if ( ! isset( $value ) ) {
				// Field settings has been deleted or not available.
				$value = get_field( $meta_key );
				if (  ! empty( $value ) &&  ! is_array($value )   ) {
					$value = [
						'id' => $meta_key,
						'url' => $value
					];
				}
			}
`

**Comment by bkjproductions** [comment]
OK, after looking a little further, it seems like user error on my part...
Apparently when you define the custom field for an image, you want the **Return Value** to be **image array**
as I suppose that 'id' is very important, probably the image ID from the Media Library, so that you're able to select the size of the image you want....

Still, it would be good to clean up that error message, maybe have it print out something like "Make sure the Return Value of your ACF image is set to Image Array, dummy!"

**Comment by tristanleboss** [comment]
If the problem is the one you describe, it would be better if Elementor could detect the type of return value of the image field. 
I don't want my users to call me because each time they want to use an ACF image field...
I think they can do it by using get_field_object or checking the type of the value returned by get_field... (is_array, is_interger or ctype_digit).

**Comment by bainternet** [comment]
The ACF integration actually supports all (array,id,url) formats but apparently, the field that stores the data type was renamed from `save_format` to `return_format`

a patch with an update to support but names should be released soon.

thanks for reporting 
related #5344
