### ISSUE TITLE
Allow relative URLs everywhere

### ISSUE THREAD

**Issue by scott8035** [pojome/elementor#6052]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When developing a site it is useful to use relative URLs so you don't have to change links when moving from dev to staging to prod. Some places within Elementor don't allow this, for example, the Redirect action of the Form widget.

**Describe the solution you'd like**
Allow relative urls starting with "/" to be used.

**Comment by bainternet** [comment]
Currently, this feature is not supported or even possible, but we will look into it in the future if we see a large demand for it.

For now, we added the "Replace URL" tool which was made exactly for these reasons.

Thanks for the feedback.
