### ISSUE TITLE
Support HTML in custom Nothing Found Message

### ISSUE THREAD

**Issue by besweeet** [pojome/elementor#6053]
Created a custom search results archive. HTML doesn't appear to be supported when filling out the Nothing Found Message box. Would be great if it did.

**Comment by Joe-Bloggs** [comment]
Any update on this? HTML still not supported in the Nothing Found Message.

**Comment by lacikawiz** [comment]
I'm using Elementor v2.9.7 & Elementor Pro v2.8.4
The HTML in the Nothing Found Message is still being escaped.

**Comment by besweeet** [comment]
I see that this feature was added to the 2.4.0 beta release 4. I'm using the latest version of Elementor + Elementor Pro yet HTML tags still aren't working correctly.

Sample:
`<p>No results found.</p>`

Result: Actual paragraph tags being displayed.

**Comment by asanger** [comment]
Is there an update for this? The above filter doesn't seem to be working for me.

**Comment by moreevilthanyou** [comment]
Do you have the same or similar feature for archive products?
