### ISSUE TITLE
Mailchimp Error/Notification Messages for Deleted and Already Subscribed Emails

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#6059]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When I delete a subscriber from a Mailchimp list and try to subscribe him once more, I receive a blank error message like this:

![obrazek](https://user-images.githubusercontent.com/5634870/47964709-f0a87980-e03d-11e8-865f-81bc8cb91761.png)

I also feel a bit inconvenience,, there's no notification/error message, when the user is already suscribed. I know there's closed issue on that - #3232. Since I understand the reasons given there for removing this functionality, what do you think about adding this feature as an option for those who need it?

## Steps to reproduce
1. Create a Mailchimp list
2. Create a subscribe form in Elementor and connect it with Mailchimp.
3. On the frontend, fill in an email and subscribe.
4. Check the Mailchimp list if the user is there.
5. Delete the user from the list.
6. Try to subscribe the same user again - in the form you'll see the blank error, in Mailchimp no user is added.

This error seeems to be Elementor specific - when I use Mailchimp's native subscribe form, the once deleted user is processed with no errors.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Debian) v5.6.39-83.1
	PHP Version: 7.0.32
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.bioapoteka.cz
	Home URL: https://www.bioapoteka.cz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: cs-CZ
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: Bio Apotéka WPBF
	Version: 1.0.0
	Author: Petr Jandák
	Child Theme: Yes
	Parent Theme Name: Page Builder Framework
	Parent Theme Version: 1.10.1
	Parent Theme Author: David Vongries

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

== Active Plugins ==
	Activity Log
		Version: 2.5.1
		Author: Activity Log Team

	Admin Menu Editor
		Version: 1.8.5
		Author: Janis Elsts

	Advanced Custom Fields PRO
		Version: 5.7.7
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 6.77
		Author: ServMask

	Central Color Palette
		Version: 1.12.6
		Author: Gáravo

	Clean Image Filenames
		Version: 1.2.1
		Author: Upperdog

	Cookie Notice
		Version: 1.2.44
		Author: dFactory

	Customizer Export/Import
		Version: 0.8
		Author: The Beaver Builder Team

	Custom Order Numbers for WooCommerce
		Version: 1.2.3
		Author: Algoritmika Ltd

	Disable Comments
		Version: 1.7.1
		Author: Samir Shah

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.2.5
		Author: Elementor.com

	Elementor Extras
		Version: 1.9.15
		Author: Namogo

	Elementor Pro
		Version: 2.1.10
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	Intuitive Custom Post Order
		Version: 3.1.1
		Author: hijiri

	iThemes Security
		Version: 7.1.0
		Author: iThemes

	Nested Pages
		Version: 3.0.6
		Author: Kyle Phillips

	Page Builder Framework Premium Addon
		Version: 1.9.1
		Author: MapSteps

	Perfect WooCommerce Brands
		Version: 1.6.5
		Author: Alberto de Vera Sevilla

	ShortPixel Image Optimizer
		Version: 4.11.3
		Author: ShortPixel

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	The SEO Framework
		Version: 3.1.4
		Author: Sybre Waaijer

	TinyMCE Advanced
		Version: 4.8.0
		Author: Andrew Ozz

	Ultimate Addons for Elementor
		Version: 1.7.3
		Author: Brainstorm Force

	User Profile Picture
		Version: 1.5.5
		Author: Ronald Huereca

	Woo Checkout Field Editor Pro
		Version: 1.2.8
		Author: ThemeHiGH

	WooCommerce
		Version: 3.4.5
		Author: Automattic

	Woo Doprava
		Version: 1.5.6
		Author: Vladislav Musílek

	Woo GoPay Inline
		Version: 1.6.3
		Author: Vladislav Musílek

	WP Media folder
		Version: 4.7.0
		Author: Joomunited

	Zalomení
		Version: 1.4.7
		Author: Honza Skypala


== Debug ==
	Errors: 
		TypeError: setting getter-only property "type"
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:86630
			2018-10-11 16:02 +00:00

		TypeError: this.ui.select is undefined
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13050
			2018-09-30 23:27 +00:00
			x 3 times

		TypeError: r.get(...).models is undefined
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:217419
			2018-09-29 13:23 +00:00

		TypeError: n.attributes[t.name].each is not a function
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:9130
			2018-09-29 13:23 +00:00
			x 2 times

		TypeError: this.ui.select is undefined
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:13050
			2018-09-29 11:48 +00:00
			x 2 times

		TypeError: setting getter-only property "type"
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.3 - 2:86630
			2018-09-21 15:25 +00:00
			x 4 times

		TypeError: this._parent is undefined
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.3 - 2:173870
			2018-09-21 01:52 +00:00
			x 6 times

		TypeError: this.ui.select is undefined
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.3 - 2:13050
			2018-09-21 00:42 +00:00

		TypeError: setting getter-only property "type"
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.3 - 2:86630
			2018-09-20 02:12 +00:00
			x 2 times

		TypeError: this._parent is undefined
			at https://www.bioapoteka.cz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.0 - 2:192295
			2018-08-30 14:57 +00:00
			x 8 times

				
```
</details>

**Comment by bainternet** [comment]
@black-eye 

This is a limitation of mailchimp API:

> When a contact who unsubscribed themselves decides to resubscribe, they need to sign up again on your **Mailchimp-hosted signup form**. Our forms capture the date and time the contact gave you permission to send them emails.

source: https://mailchimp.com/help/resubscribe-a-contact/#Resubscribe_with_the_Signup_Form

Not really much we can do about it.

thanks.

**Comment by black-eye** [comment]
@bainternet Please read the description carefully. The problem isn't caused by unsubscribing the user. It's caused by deleting the user. And again - this issue is related to Elementor form only - the problem isn't present when using native mailchimp form.

Please try the steps to reproduce given above before closing the issue. 
And why there is a blank error message there? There should be at least some info, what's going on.

Thanks again

**Comment by black-eye** [comment]
OK, with stackoverflow link, I understnad the problem better now.

On the other hand, the problem with the blank error message is still there. This is definitelly something that should be corrected somehow. At least using some kind of universal notice like "Error adding to a Mailchimp list occured." Now the user/developer has no hint what has happened and what part of the sending process caused the problem.

E.g. in this case there are 3 actions after submit in this form:
1. Send an email to the admin that - user has subscribed
2. Send the Welcome email to the user.
3. Add the user to a Mailchimp list.

In this situation I'm not able to deduce what part of the process triggered the error.

And for the second part: any chances you may reconsider not showing "Subscriber Already Exists" message? E.g. as a special option with a warning about data leakage risks etc.

**Comment by umairqureshi6** [comment]
i am facing this issue, looking for a solution
