### ISSUE TITLE
Global Fonts Don't Show Up on Elementor Live Preview Screen

### ISSUE THREAD

**Issue by jj43116** [pojome/elementor#606]
I am using the Generate Press theme with Elementor and I don't have any other active plugins.  When I open up the Elementor edit screen for a given page, the Elementor global fonts that I have specified do not show up in the live preview but they always correctly show up on the frontend of the site.  

When they don't show up in the editor, I am able to get them to show up by going back to the global font settings, changing them to a different font then changing them back again to the specified font.  

When I do this, they show up on the live preview correctly but it is time consuming to do every time I want to make edits and look at previews.

Thanks!

**Comment by arielk** [comment]
I'm not sure I understand, Do you want to use in the Global Fonts or use a font by your theme?

You can disable the Fonts Global feature by settings page of Elementor

**Comment by jj43116** [comment]
Thanks for the reply.  I've attached some screen shots to illustrate the situation. This issue occurs with any font (I'm using "Lobster" to illustrate) and it occurs when using or not using pre defined templates -  some templates have custom fonts, the one pictured does not.)

1. You can see here, the front end is displaying the heading font correctly (the Lobster font is already setup in the Elementor Global font settings as the primary headline font) .
<img width="1440" alt="1" src="https://cloud.githubusercontent.com/assets/11823789/18759506/fcd32a1a-80b9-11e6-8e30-fcc330122eb6.png">

2.  Next, when I go to edit the page by opening it up and using the Elementor Editor, you can see that even though I had previously already set the global primary headline font to "Lobster" it doesn't show up in the editor preview.  
<img width="1440" alt="2" src="https://cloud.githubusercontent.com/assets/11823789/18759505/fcd1c986-80b9-11e6-92f2-2ba0ba5ccd16.png">

3. To get the "Lobster" font to show up in the preview, I have to switch the global font to something else:
<img width="1440" alt="3" src="https://cloud.githubusercontent.com/assets/11823789/18759508/fcd97dde-80b9-11e6-870a-35f624ebab3f.png">

4.  And then I can switch it back to the font I want ("Lobster") and it then displays in the preview correctly. 
<img width="1440" alt="4" src="https://cloud.githubusercontent.com/assets/11823789/18759507/fcd39f18-80b9-11e6-81fe-5e435285252b.png">

The same issue happens with the global body font.

**Comment by arielk** [comment]
1. Please deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

2. If you have a caching plugin, make sure you deactivate it, or even better – purge the cache.

3. Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, please send a email support [at] elementor.com
