### ISSUE TITLE
Forms WebHooks - Fields Names

### ISSUE THREAD

**Issue by starshunter88** [pojome/elementor#6064]
Hello,

I post on GitHub as suggested by your Support Team.

Elementor uses Field Labels as Field Names for Webhooks. This is not ideal because my email marketing app doesn't allow to customize form names. So I should use some Labels that are not really user friendly, such as FNAME or LNAME in capital letters in my web pages.

Is there a way to set field names separately? Otherwhise could I use Field IDs instead for all my fields in all my forms?

Thanks a lot for the support!

**Comment by bainternet** [comment]
@starshunter88 

The current implementation of Webhooks are a little limited in the way they work so you might need to create a custom webhook handler as explained on our [Form API docs](https://developers.elementor.com/forms-api/#Form_New_Record_Action).

The exact example there is what you need.
thanks.

**Comment by bainternet** [comment]
simply remove the check for a specific form ex:

```PHP
// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
   
    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
        'body' => $fields,
    ]);
});
```

**Comment by starshunter88** [comment]
Thanks! Very last question, I promise. Why do I have to put the web hook
address in the function? Will it override the web hook url that I put in
the widget builder?

Il giorno mar 6 nov 2018 alle ore 13:45 Raz Ohad <notifications@github.com>
ha scritto:
