### ISSUE TITLE
[Feature Request] Add action hook in Post Comments Widget to make Comments Template filterable/customizeable

### ISSUE THREAD

**Issue by deckerweb** [pojome/elementor#6065]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently as of Elementor Pro 2.1.11 the Elementor Pro Post Comments widget is NOT compatible with themes/frameworks that use a slightly different comments template loading - this is currently true for the popular Genesis Framework.

That means: Though Elementor (Pro) is compatible with Genesis in general, the comments display is not possible in Elementor Theme Builder.

**Describe the solution you'd like**
An action hook would do fine and allow developers to modify the comments template/loading as needed and make comments display in Elementor Pro Theme Builder.

There could be changed one section in Elementor Pro:
/modules/theme-elements/widgets/post-comments.php - instead of line line 112: `comments_template();`

I propose the following change:
```
do_action( 'elementor_pro/widgets/post-comments/comments-template' );
add_action( 'elementor_pro/widgets/post-comments/comments-template', 'comments_template' );
```

This was tested with current Elementor Pro and Genesis and the action hook provides the possibility to unhook the default (as above, proposed change) and instead hook in another custom function, like `genesis_get_comments_template()`.

**Describe alternatives you've considered**
I considered using a filter insteand of an action but this doesn't work. An action works and is developer friendly and adds no bloat either.

**Additional context**
The Genesis Framework is one of the most popular themes around and making it even more compatible with Elementor (via plugins etc.) is helping broading the Elementor user base.

If this proposed change gets implemented I already have a free "Genesis Connect for Elementor" plugin completely ready for release to give Genesis users the ready feature in their hands to use Elementor Pro with Genesis - also for post comments.

Thanks in advance!

**Comment by bainternet** [comment]
@deckerweb 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now you can actually use the provided hooks to get around it:

```PHP
add_action( 'elementor/frontend/widget/before_render', function( $widget ) {
	if ( 'post-comments' !== $widget->get_name() ) {
		return;
	}
	ob_start();
	add_action( 'elementor/frontend/widget/after_render', function( $widget ) {
		ob_get_clean();
		genesis_get_comments_template();
	});
} );
```

Not the prettiest solution, but it should work just fine.  
Thanks for the feedback.

**Comment by deckerweb** [comment]
@bainternet Thank you for the feedback and the snippet!
Yeah, I could live with that in general.
However, the snippet is not working as of now - comments are not displayed. I've tried also with another Genesis developer and couldn't get to work yet.
We keep on experimenting, though. But if you might have another idea, any tip in the right direction will help us.
Thanks so much in advance!

**Comment by bainternet** [comment]
I'll take another look.

**Comment by bainternet** [comment]
@deckerweb 

You were correct, it only addressed the frontend, not the editor, anyway, here is a quick utility that will allow you to replace the output of any widget, both preview, and frontend and as a bonus, it adds hooks before and after the render.

```PHP
/**
 * Class Elementor_Widget_Render_Replacement
 * @author Ohad Raz
 */
class Elementor_Widget_Render_Replacement {
	/**
	 * @var string
	 */
	private $widget_name = '';
	/**
	 * @var callable
	 */
	private $callback = null;

	/**
	 * Elementor_Widget_Render_Replacement constructor.
	 *
	 * @param $widget_name
	 * @param $callback
	 */
	public function __construct( $widget_name, $callback ) {
		$this->callback = $callback;
		$this->widget_name = $widget_name;

		// Frontend
		add_action( 'elementor/frontend/widget/before_render', [ $this, 'before_render' ] );

		// Editor Preview
		add_filter( 'elementor/widget/render_content', [ $this, 'preview_render_content' ], 10, 2 );
	}

	/**
	 * is_correct_widget
	 * @param \Elementor\Widget_Base $widget
	 *
	 * @return bool
	 */
	public function is_correct_widget( $widget ) {
		return $this->widget_name === $widget->get_name();
	}

	/**
	 * before_render
	 * handles frontend render
	 * @param \Elementor\Widget_Base $widget
	 */
	public function before_render( $widget ) {
		if ( ! $this->is_correct_widget( $widget ) ) {
			return;
		}
		ob_start();
		add_action( 'elementor/frontend/widget/after_render', [ $this, 'after_render' ] );
	}

	/**
	 * after_render
	 * removes widget original output and  calls replacement
	 * @param \Elementor\Widget_Base $widget
	 */
	public function after_render( $widget ) {
		ob_get_clean();
		$this->execute_callback( func_get_args() );
		remove_action( 'elementor/frontend/widget/after_render', [ $this, 'after_render' ] );
	}

	/**
	 * preview_render_content
	 * handles preview render
	 * removes widget original output and  calls replacement
	 * @param string $widget_content
	 * @param \Elementor\Widget_Base $widget $widget
	 *
	 * @return false|string
	 */
	public function preview_render_content( $widget_content, $widget ) {
		if ( ! $this->is_correct_widget( $widget ) ) {
			return $widget_content;
		}
		ob_start();
		$this->execute_callback( func_get_args() );
		return ob_get_clean();
	}

	/**
	 * execute_callback
	 * @param array $args
	 */
	public function execute_callback( $args ) {
		// Extra hook before replacement render
		do_action( 'elementor/widget/render/replacement/before', $args, $this );
		if ( is_callable( $this->callback ) ) {
			call_user_func_array( $this->callback, $args );
		}
		// Extra hook after replacement render
		do_action( 'elementor/widget/render/replacement/after', $args, $this );
	}
}
```

So in your case the usage should be something like:
```PHP
new Elementor_Widget_Render_Replacement( 'post-comments', 'genesis_get_comments_template' );
```

Let me know.

**Comment by filipe-q** [comment]
Hello!

This seems to be exactly what I was looking for but unfortunately it's not working.

System info:
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.2.31 (Win32) DAV/2 mod_ssl/2.2.31 OpenSSL/1.0.2e mod_fcgid/2.3.9 mod_wsgi/3.4 Python/2.7.6 PHP/7.1.7 mod_perl/2.0.8 Perl/v5.16.3
	MySQL version: MySQL Community Server (GPL) v5.6.34
	PHP Version: 7.1.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: http://localhost/
	Home URL: http://localhost/
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Genesis Sample
	Version: 3.0.1
	Author: StudioPress
	Child Theme: Yes
	Parent Theme Name: Genesis
	Parent Theme Version: 3.0.2
	Parent Theme Author: StudioPress

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.1
		Author: Elementor.com
