### ISSUE TITLE
Forms Integration with Google Spreadsheet

### ISSUE THREAD

**Issue by starshunter88** [pojome/elementor#6066]
Hi there,

since a database to easily store forms leads is not available, would you consider an integration with Google Spreadsheets?

Thanks,
Antonio

**Comment by bainternet** [comment]
@starshunter88 	

We are strongly thinking about it, for now look at:
https://github.com/pojome/elementor/issues/5894#issuecomment-429601355

**Comment by CSWood** [comment]
I'd like to add my voice in support of this feature. An integration to send form data to a Google sheet would be just awesome.
