### ISSUE TITLE
Elementor 2.3.0 - Beta Release (Beta 4 UPDATED)

### ISSUE THREAD

**Issue by bainternet** [pojome/elementor#6068]
===========
## [Beta 4 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/6068#issuecomment-437190594)
===========

Hey Elementor testers,

You are the first to receive Elementor version 2.3 — the latest version that includes a handful of useful, innovative features. Please go over the list below, one by one, and help us test this version for bugs and conflicts.

In this version, we focused on improving the interface, as well as adding shortcuts that make working with Elementor even easier and more convenient.

**Please go over each new feature detailed below, and test it out in your dev environment.**

## Introducing Finder (Ctrl/Cmd+E)
Elementor has become an integral part of the website creation process for many professional designers. 
With the evolution of our product, we see a growing need to speed up workflow-related processes.

Meet Finder, a new search bar that pops up on click, giving you easy access to literally every area of your site - all from within one_ single_ window. These areas include the WordPress admin, the front end of your site, other pages and more.

### Edit: One-Click to Edit a different page/template
Think of this scenario: While editing your homepage you suddenly spot a problem with your site’s header. What do you do?

Simply press `CMD + E` to open Finder, then write the name of the header template and BAM - 
you’re editing it. No more ‘exit to dashboard’ > Dashboard > Elementor > My Templates and so on…

![switch-between-pages](https://user-images.githubusercontent.com/660572/47998758-164e8500-e109-11e8-9b08-b9fb97ac148d.gif)

### Create: Something New
You’re editing a page, and want to start working on a different one? Now it’s possible! / It’s a snap! 
Search for Post, and you’ll get the option to open a new post. This works for every post type, page, product, and so on…

This option is only available to users with Admin access to the site. So you don’t have to worry about users with lower user roles accessing the administrator areas of your site.

![new-template](https://user-images.githubusercontent.com/660572/47998787-2a928200-e109-11e8-83c4-0ad7aeba5c32.gif)

### Go To: Maneuver throughout your site (Switch between WordPress admin, Elementor editor, and Settings)
By using Finder, you can easily locate any area of your interface without any redundant menu clicks.

This works not only in Elementor. Let’s say you’re viewing the frontend of your site, and you want to reach the custom font settings page. Use the same shortcut, search for the relevant place, and be seamlessly transported to the right destination.

### More Options to Explore
Use Elementor Finder, to quickly reach the documentation area where you can get help solving problems or learn about different Elementor features.

The ‘Switch between pages’ feature request was one of our most sought-after features. Users want to access and edit different pages without having to exit the current one. Elementor Finder solves this very issue and makes the overall Elementor experience smoother and more fun.
 
## Meet Keyboard Shortcuts (Ctrl/Cmd+?)

Elementor Finder, Navigator and other recent interface improvements we made, puzzled our users in terms of how to reach them quickly. 

![keyboard-shortcuts](https://user-images.githubusercontent.com/660572/47998670-d8516100-e108-11e8-97c9-c9e9736da552.png)

This is why we have added a new keyboard shortcut window that pops out when you press `CMD / CTRL + ?`
If there’s one keyboard shortcut worth remembering - it’s this one!

There’s a keyboard shortcut for nearly everything; using them will significantly speed up your workflow.

## New Star Rating Widget
It’s been a while since we last added a whole new widget to the base version of Elementor. With this version, we are introducing a new widget called Star Rating.

![star-rating](https://user-images.githubusercontent.com/660572/47998645-c8398180-e108-11e8-9c7e-a56f6aef4f40.png)

This widget lets you add star ratings to different elements of the page, letting you add social proof that has become a necessary part of the user experience. 

Browse through the new Elementor site to see how we’ve incorporated it into various parts of our design.

## Font Family Preview

Two years ago, Google fonts only included a few hundred fonts. Today, the list has grown to over 1,100 different fonts. Add to this Elementor’s Adobe Typekit integration and custom fonts feature, and you have a neverending list of fonts difficult to choose from.
![font-family-preview](https://user-images.githubusercontent.com/660572/47998634-bce65600-e108-11e8-9f7e-7de95d29bb7b.gif)

This is exactly why we added the option to preview fonts, making it easier to browse through the list and pick just the right font for your needs.

Notice that the preview only works when scrolling through the fonts. This way all the fonts are not loaded on page load rather only on demand. After selecting a font, only that specific one will load.

## More Improvements for Developers

- Tweak: Added compatibility for WordPress v5.0 Beta (#6019)
- Tweak: Added `Esc` shortcut for opening the settings menu
- Tweak: Added filter to rename external CSS files (#5968)
- Tweak: Added a general hook `elementor/frontend/after_render` to element-base
- Tweak: Added `elementor/element/before_attribute_render` hook before attributes are rendered
- Tweak: Added `elementor/element/after_attribute_render` hook after attributes are rendered
- Tweak: New `elementor/editor/init` action
- Tweak: A new `get_post_type_title` method for document
- Deprecated: `Source_Local::TYPE_META_KEY` is no longer supported
- Deprecate: `save_type` is replaced by `save_template_type` 

## How to Install the Beta Version
If you still haven't enabled beta testing in Elementor, please follow these steps:

1. Go to Elementor > Tools > Versions
1. Enable the beta tester feature
1. Go to the Dashboard > Updates and update to the latest beta version

You can also download the new version here: https://downloads.wordpress.org/plugin/elementor.2.3.0-beta4.zip

## Notes
[Elementor Beta - Sign Up now for our elite group of early access testers](https://my.elementor.com/beta/)

**Designated time for release: November 18, 2018 (Estimated)**
**For bugs and remarks, please reply with a comment on this issue here on GitHub**.

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Many thanks for your support and help!

**Comment by silvioghedin** [comment]
I'm testing right now. 

Just a little disappointed, I was expecting other new features like the top bar in the new Elementor website.

Therefore , let's test and try to find some bugs ;)

**Comment by cavalierlife** [comment]
I have tried the beta on both a local and a remote host, running various tests, and the problem below exists throughout. All handles (section, column, widget) are no longer showing icons, only text. Here is a screenshot.
![noicons](https://user-images.githubusercontent.com/28687464/48000298-a9b49580-e0ca-11e8-8d64-d5fe2826efcb.JPG)

**Comment by KiQdev** [comment]
Same problem with the handles icons, only text.

**Comment by black-eye** [comment]
I was also hoping for something different than Finder, as @silvioghedin mentioned (in a comment that was just deleted). Some feature which would show complete page structure rather than finding pages/posts/CTP by name. You're almost there, but not completely - is something like this on the way?

Something similar as suggested here: #292 (https://cloudup.com/cwaDlqVcTiW). Sometimes you need to see the whole site structure rather than try to recall the page's name.

**Comment by bainternet** [comment]
@cavalierlife 

Thanks, we can replicate and will correct this.

@black-eye thanks, but it's not related.

please keep this only for reporting issues with the current beta.

Thanks.

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to v2.3.0 Beta 2.

This beta release includes a fix for missing icons and CSS glitches.

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Thanks again to everyone.

**Comment by jazir5** [comment]
Question, with the addition of finder, will this have side benefits of improving elementors search function? I am struggling with implementing a search bar on my site, and would love it if the search functionality integration with elementor could be improved. In my experience it does not allow you to find content edited with elementor in pages created outside of the "My templates" section, which i am hopeful that the finder will help rectify in some way.

I'm specifically referring to live sites created with elementor.

**Comment by lucafagherazzi** [comment]
The widget template does not work with new templates.

**Comment by bainternet** [comment]
@jazir5 

The finder has nothing to do with the search widget, which is essentially a native WordPress search form. But we do plan to add hooks to it to allow customizations so follow #5598

@lucafagherazzi 
can you elaborate? "widget template"?

thanks

**Comment by jazir5** [comment]
@bainternet

Do you guys have a timeframe planned for implementing that? I've tried to use other live search plugins to integrate with elementor, and none of them work. Search is pretty major functionality, so I'd be very grateful if you guys could tackle this issue. If you have any suggestions for 3rd party plugins to use in the meantime, i'd be grateful. I would like to implement live search functionality into my sites and the pro search widget at this point is so lacking to the point of being essentially unusable.

**Comment by lucafagherazzi** [comment]
[Template widget.zip](https://github.com/pojome/elementor/files/2552390/Template.widget.zip)

**Comment by bainternet** [comment]
@jazir5 

Its planned for upcoming Pro version or next one, please keep this related to issues with the beta.

thanks.

@lucafagherazzi 
thanks for clarifying, We can't replicate this on our end. make sure you have the latest pro version installed which is 2.1.12 and let me know.

thanks.

**Comment by benstone326** [comment]
Hello!

It's a bit OFF topic but can you please update the Font Awesome list with the new icons? I can see that FA has a tons of new FREE icon that not included in elementor.

Thank you very much!

**Comment by Rafava** [comment]
With Finder; Can we have an option to open the searched element in the same tab?

**Comment by bainternet** [comment]
@Rafava 

Currently its new tab only but we might add an option to configure it in the future.

thanks.

**Comment by dotpdesign** [comment]
Finder will be useful, I think. Good work.

What I can't understand is how a single user submits a request 14 days ago to Add filter to rename external css files, and it get's added to the beta, while pro users have been asking for universal CSS editing capability within Elementor for ALMOST A YEAR (https://github.com/pojome/elementor/issues/3345#issuecomment-436057850) and still nothing! Prioritize your user requests appropriately. And +1 for the need to upgrade to font Awesome 5.

**Comment by bainternet** [comment]
@SniffleValve 

Thanks for reporting. will be fixed.

@dotpdesign 

Thanks for the kind words, I think. :) 
anyway as for your observation, search the issue here and you will see the hook was requested more than a few time before. And you can't compare adding a simple hook to building a feature from the gorubd up with UI and functionalty.

As FontAwesome 5, not related to this Beta and we already have an issue open about it.

thanks.

**Comment by lucafagherazzi** [comment]
Yes, I have the latest pro version installed. I did some tests and I realized that the widget works well when it is inserted in a post. It no longer works when it is inserted into a template in my library.

**Comment by TamarynT** [comment]
I have mine installed on a live site. Yes, yes. I know this is not recommended, but the updates come through anyway and we updated all the plugins at the same time. I'm not alarmed by this. It's not that big of a deal for us.

But, one bug I found in addition to the ones reported above is that New Section Templates are being saved as blank and thus will not insert. Old templates will insert just fine. 

While copy/paste is a workaround for now, long term this will prove to be an issue.

**Comment by TamarynT** [comment]
Also just found we're not able to pull up the edit history on a page edits or go back to previous versions w/i the elementor editor.

**Comment by JuanmaAranda** [comment]
Hello! I have not been able to show the list of shortcuts on the screen by pressing Cmd? on Mac. I tried to press the capital letter too, but in that case the Google Chrome help opens ...

**Comment by Jorihlen** [comment]
I can not access the shortcuts page with Ctrl +? with my Latin American keyboard still using Ctrl + Shift +? (Shift is required to reach the sign?).
Will it be possible to add that feature (Ctrl + Shift +?) To make it compatible with our keyboard? 
Or simply the ability to create customized new short keys.

**Comment by pcoovert** [comment]
Having trouble with the star rating widget. When I  put 5 in the rating box I get 5 stars in a nice row. When I put in 1 or 2, I get 5 vertical stars. When I put in 3, I get two rows with 2 stars and one row with 1 star. When I  put in 4, I get one row of 3 stars and one row of 2 stars.

For what it is worth, I am running an Ubuntu Mate operating system, I don't think that should make any difference.

**Comment by nickdgreen** [comment]
Star Rating Widget - Suggestions:
Extend the setting to allow setting both the number of stars (you might want a score out of 10) as well as the score.
Allow the choice of the icon and not limit it to just stars - you might want to use check marks or cars or users.

**Comment by TamarynT** [comment]
New Bug:

Section background with a dynamic featured image (with & fallback) does not display.
![screen shot 2018-11-07 at 3 38 38 pm](https://user-images.githubusercontent.com/37632728/48159486-521d5200-e2a3-11e8-9f51-60534960762d.png)

Neither does section background static image.

Can be seen by clicking through to any of our blog posts www.spectaclecreative.com/blog

**Comment by nickdgreen** [comment]
In the Demo Paul did on WPTuts about finder when he opened a page from the finder it kept the page he was 'editing open' as well so there was the ability to edit two pages. This is also stated in the documentation above. When I open a page and then for example "find" the pageHeader template - clicking on the template opens the template in the current tab not in a new tab so you can't edit the header whilst having another page open. This is the same on Chrome and Firefox.

**Comment by SniffleValve** [comment]
Gutenberg Editor - page/post - Edit with Elementor button after editing with Elementor

WP 5.0-beta 3-43876
Elementor 2.3 beta 3

Steps to reproduce
- create a new page/post and publish
- click the Edit with Elementor button at the top of the page (this one is fine)
- add some Elementor content, Update and exit back to the GB editor

Bug
The Edit with Elementor button's icon is slanted and small, the text is grey and small and is at the bottom of the button.

Cheers!
Lyle

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to v2.3.0 Beta 3.

This beta release includes:

- Tweak: Open Finder links in the same tab
- Tweak: Added tips bar for Finder
- Fix: Save templates with slashes
- Fix: CSS glitch in Star Rating widget

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Thanks again to everyone.

**Comment by jazir5** [comment]
Could you add a keyboard shortcut to go back to the elements sidebar? You have a shortcut for collapsing and uncollapsed the panel, but I'd like one to jump back to the element list. Would be very useful and save me some time when I am editing an element. Thanks.

**Comment by bainternet** [comment]
@lucafagherazzi, @TamarynT 	

Please test the template issue with beta 3.

@Rafava, @bentalgad, @nickdgreen 

We changed the Finder to open in the same tab and if needed you can simply right click >> open in a new tab.

@SniffleValve, @pcoovert

The star rating CSS issues should have been fixed, please test with beta 3.

@nickdgreen 	

As for stars vs something else and the number of starts we are thinking about it.
thanks.

@Jorihlen

We'll see what we can do about it.

@TamarynT 	

We can't replicate the section background issue you described, can you please [open a new bug report issue](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) with as many details as possible.
thanks.

@SniffleValve 
We can't replicate the Gutenberg issue you described, can you please [open a new bug report issue](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) with as many details as possible.
thanks.

thanks, everyone.

**Comment by lucafagherazzi** [comment]
Installed beta 3: same problems as before.
After some tests I found that it does not work with dynamic content.
There is also the problem that does not show the chosen template (see attached image).
![template](https://user-images.githubusercontent.com/40598133/48193643-366d8680-e34b-11e8-82a3-39a2c3b3c77c.jpg)

**Comment by Jorihlen** [comment]
>> I can not access the shortcuts page with Ctrl +? with my Latin American keyboard still using Ctrl + Shift +? (Shift is required to reach the sign?).
> Will it be possible to add that feature (Ctrl + Shift +?) To make it compatible with our keyboard?
> Or simply the ability to create customized new short keys.

**Comment by Jorihlen** [comment]
Is there a chance to use the question opening sign (¿) on Latin American keyboards?
I know that in English speech that sign is ignored using only the closing (?)

**Comment by nickdgreen** [comment]
Raz,

Right click to open a page from the "Finder" in a new tab does not work. I
have found Shift+Click opens the page in a new window and Ctrl+click opens
it in a new tab (I actually prefer the Ctrl+click).

 

 

Best Regards

Nick

 


Legal Disclaimer:

Internet communications are not secure and therefore Websites Designed 4U (a
business name of ISD Consultants Ltd.) does not accept legal responsibility
for the contents of this message. This email is confidential and solely for
the use of the intended recipient(s). If you receive this email by mistake,
please advise the sender directly, then immediately destroy this email.
Websites Designed 4U maintains security processes designed to eliminate
viruses, however, the Company is not responsible for viruses which may be
contained in the email or any attachment(s).

**Comment by cavalierlife** [comment]
Right click for new tab via Finder works well for me (Windows). I like it.

**Comment by nickdgreen** [comment]
Right-click works when you are on the dashboard but not when you have a page open for editing.

**Comment by cavalierlife** [comment]
Nick, which browser / OS? Works fine for me when using it with a page open for editing in both FF and Chrome.

**Comment by nickdgreen** [comment]
Chrome on Windows 10

**Comment by titelas** [comment]
> I can not access the shortcuts page with Ctrl +? with my Latin American keyboard still using Ctrl + Shift +? (Shift is required to reach the sign?).
> Will it be possible to add that feature (Ctrl + Shift +?) To make it compatible with our keyboard?
> Or simply the ability to create customized new short keys.

Same problem with a Spanish layout keyboard. I am not able to access the Shortcuts modal.

**Comment by SniffleValve** [comment]
@bainternet 
I updated the post to say that it was theme-specific to the latest Astra theme 1.5.5. Works fine on the other themes mentioned  :)  I will let the Astra folks know.
Cheers!
Lyle

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to vXXX Beta X.

This beta release includes:

- Tweak: Added rating scale to Star Rating widget
- Tweak: Removed tips bar from Finder
- Tweak: Changed YouTube related videos control type and labels due to YouTube’s API changes
- Fix: Lightbox images links detection (#6103)

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Thanks again to everyone.

**Comment by jazir5** [comment]
@bainternet 

Could you add a keyboard shortcut to go back to the elements sidebar? You have a shortcut for collapsing and uncollapsing the panel, but I'd like one to jump back to the element list. Would be very useful and save me some time when I am editing an element. Thanks.

**Comment by reachadam** [comment]
The new Star Rating is awesome but I am always curious why these awesome modules that involve numbers never have dynamic field integration. Literally, nothing involving numbers in Elementor has dynamic field integration. This includes pricing tables, progress bars, and counters.

**Comment by bainternet** [comment]
@reachadam 	

Simply because it's not implemented yet, but it's on our todo list.

**Comment by bainternet** [comment]
Elementor 2.3.0 is now live,

Thanks, everyone for helping.

Please feel free to open a new issue if needed.

thanks again.

**Comment by bentalgad** [comment]
Just wanted to comment again about this finder add-on: it is one of the best things ever happened to Woedpress and it make's the Elementor workflow amazingly much more convenient! i just love it! Thank you thank you thank you!
