### ISSUE TITLE
[Enhancement Request] Switch "ADD TEMPLATE" to "REMOVE TEMPLATE"

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#607]
Hey guys,

Hopefully you will consider ths enhancement request: could the button "ADD TEMPLATE" switch to "REMOVE TEMPLATE" once a template has been inserted and act as a removal action? See image.
![elremovetemplate](https://cloud.githubusercontent.com/assets/16872407/18730559/e4bda42a-804e-11e6-98be-22b445f11fdc.png)

This will help with development speed should the wrong template be inserted or if one changes their mind.

**Comment by arielk** [comment]
Added a new button for this: https://github.com/pojome/elementor/commit/af6e37b6182dc03efa19e674c9826b9c94f96028
