### ISSUE TITLE
Options for styling readmore button in posts widget

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#6073]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Card style needs more options to allow change style of readmore link ,you can simply make it button with options. or at least hover color option! it's very raw!
to achieve this simple style, we need to use custom CSS!

Posts widget is most important widget in elementor, but very limited (dont want mention custom skin that still nothing done about it)

![image](https://user-images.githubusercontent.com/2544046/48024635-3f473800-e152-11e8-8b20-668d3914bea0.png)
![image](https://user-images.githubusercontent.com/2544046/48024737-7584b780-e152-11e8-9f76-862ef824bd57.png)

**Comment by bainternet** [comment]
Should be possible with #4440 

and as for 
>Dont want mention custom skin that still nothing done about it

which you did mention, saying nothing was done about it, is just simply **Wrong**.

thanks.

**Comment by amindiary** [comment]
well, it opened in may 2018 and still not assigned to any milestone, that's why I said nothing done!
![image](https://user-images.githubusercontent.com/2544046/48059293-cf749400-e1c9-11e8-853f-cfe1576c8d2e.png)

Thank you

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
