### ISSUE TITLE
Feature Request: Accordion Widget Sorting / Grouping

### ISSUE THREAD

**Issue by wpinfos** [pojome/elementor#6074]
Hello,

i like to suggest / request the following feature:

Add  the possibility to add tag(s) to accordion widgets and use them for a sorting / grouping feature.

If you have for example 4 Accordions with tag1 tag2 tag1 tag1 you can have a tag list above the accordions. If you click on tag1 - you than would only see accordion 1,3,4.

I hope that makes sense.

Thanks!

**Comment by jazir5** [comment]
I'd like to add to this. The way elementor's side bar editor currently functions, each element is sorted according to it's addon pack. I.e. Elementor pro widgets are all grouped together, Ultimate elementor addons together etc. The ability to create a custom widget grouping in the sidebar, as well as reordering element groupings via drag and drop would improve my workflow immensely. I don't want to make every widget a global to easily access them, so custom grouping them would be fantastic.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
