### ISSUE TITLE
Feature request: Keyboard shortcut to jump to sidebar widget panel

### ISSUE THREAD

**Issue by jazir5** [pojome/elementor#6076]
Currently there is a keyboard shortcut for collapsing/expanding the panel, which basically takes the editor into preview mode, with ctrl+ p. What i would like is an additional shortcut which immediately takes you to the element panel. If i'm editing an element, column or section i am currently required to click on the dialpad icon at the top right of the sidebar. I'd like a keyboard shortcut to eliminate that step.

![sidebar](https://user-images.githubusercontent.com/31750063/48046194-60a32680-e148-11e8-9c18-f9fcd3e5bd91.PNG)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

As far as I know, Crtl + P is the browser's native print shortcut.


Thanks for the feedback.

**Comment by jazir5** [comment]
Ctrl+ p is the close panel shortcut
![hide panel](https://user-images.githubusercontent.com/31750063/48687312-9a772280-eb75-11e8-9e8d-bebb027c36c0.PNG)
