### ISSUE TITLE
How to import regenerated CSS?

### ISSUE THREAD

**Issue by duongancol** [pojome/elementor#6077]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hi! I have the same question here but still need some detailed instructions. https://github.com/pojome/elementor/issues/1537
Basically, I'm building importing demo function for our theme and don't know how to move or import the generated css file: global, post css
How can I have the Json on DB?
And How can I regenerte the CSS? What's the hook/function?

Thank you!

**Comment by bainternet** [comment]
@duongancol 

For Post CSS, you don't need to import the generated CSS, Elementor renders/regenerates it for you.

As for Global CSS, currently its not possible to export/import it.

thanks.

**Comment by duongancol** [comment]
Hi! @bainternet Sorry! I sent wrong the issue, here is the correct URL https://github.com/pojome/elementor/issues/1790
After importing xml, elementor doesn't import the generated css, so I'm finding a way to have these files. 
Hope you understand my question!

**Comment by bainternet** [comment]
@duongancol 

again, For Post CSS, you don't need to import the generated CSS, Elementor renders/regenerates it for you.

and again for Global CSS, currently its not possible to export/import it.

only by exporting it yourself from the options table and importing it manually.

thanks.

**Comment by duongancol** [comment]
@bainternet I tried to follow the solution here to set the default value of color scheme. https://github.com/pojome/elementor/issues/4035
The problem is that it doesn't change the default color, I've to click the reset button here https://prnt.sc/lfi996
is there another hooks so it can change global color without reset button? 
Thanks!

**Comment by duongancol** [comment]
Sorry! Any updates?

**Comment by kevanbulmer** [comment]
Can someone tell me where I find the json in the db, which tbl or key is it under?
