### ISSUE TITLE
YouTube Autoplay option doesn't work. 

### ISSUE THREAD

**Issue by h71** [pojome/elementor#6078]
## Prerequisites

- [* ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [* ] The issue still exists against the latest stable version of Elementor.

## Description
Autoplay option for YouTube video is not working.

## Steps to reproduce
1. Add a page.
2. Add a video element.
3. Set autoplay to true.
4. Check it in editor and front-end.

## Isolating the problem

- [* ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [* ] This bug happens with a default WordPress theme active.
- [* ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@h71 	

Works just fine, depending on video mute status, browser, media engagement index and a few more factors.

meaning its defined correctly by elementor, so this is not an issue.

thanks.
