### ISSUE TITLE
Increase maximum width of elementor panel from 680px

### ISSUE THREAD

**Issue by pb52** [pojome/elementor#6082]
**Problem Statement:**
My sites use a maximum content width of 1100px. I write a lot of technical documentation as posts, with a blend of text and pictures, dividers, accordions, CTA's and all sorts.   I write this content using a 2K monitor and the classic text editor box within the Elementor panel is too narrow.  Editing in the body of the post is not always possible because that area is not so fully featured as the classic editor window. 

I have made the Elementor panel as wide as I can, but there seems to be a hard stop at 680px.  This means that I have two columns of unusable white space either side of the content which total 820 px - nearly one third of the screen

**My Request**
Please change the hard coded 680px Elementor Panel width to a percentage of the screen width.  I'd suggest allowing a maximum of 50%  This image shows the before and after effects:

![image](https://user-images.githubusercontent.com/30155991/48073209-3435eb80-e1d6-11e8-890f-3b58d6babbd3.png)
 (apologies - it's a crude design, but I hope it makes sense.)

**Alternatives**
I have tried using the classic editor instead of Elementor, but I need so many widgets from Elementor that that just doesn't work,  The constant switching back and forth is just too cumbersome

I have tried editing the text in the main body widget, but it is not as good as the classic editor in the Elementor panel - there are some things you can only so in that panel, especially if you want to add some simple media in to a body of text

**Comment by bainternet** [comment]
@pb52 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

But there is a 3rd party plugin you can try which lets you extend the with of the panel, https://wordpress.org/plugins/flexible-elementor-panel/

Thanks for the suggestion.

**Comment by pb52** [comment]
@bainternet 

Thanks for your fast response.

I have tried the Flexible Elementor Panel plugin, and it too has a hard stop at exactly the same place so, regrettably, does not cure my problem.
