### ISSUE TITLE
Feature request: provide inline code-based icons as an alternative to Font Awesome icons

### ISSUE THREAD

**Issue by TheMangoTrain** [pojome/elementor#6083]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Drop-down icons for menu's have delayed loading in relation to the rest of the page. When the icon finishes downloading, it gets injected onto the page, but when that happens the surrounding interface shifts accordingly. Users get a bad experience because they see a sharp 'jump' in the interface as the menu icons get rendered, even though to them the page has already finished loading.

Update: The JS library SmartMenus seems to be the main culprit here (see below thread), however I believe loading of FA icons probably doesn't help. In any case, no matter how much you tweak your site speed, it will never come close to code-based inline icons (which have instant rendering).

**Describe the solution you'd like**
Across Elementor widgets, wherever there's an option to use Font Awesome icons, please make an alternative option for **_inline icons_** made purely with CSS, HTML code or SVG (pre-made by Elementor). Or perhaps just make a field for users to input custom HTML. Anyways ideally these code-based icons would use the widget styling of Default/Hover/Active. There would be difficulty building that up, but not impossible. I stress the word **_inline_** code-based icons because it occurs in code, not a file to be downloaded, and loads instantly with no shifting of the page.

A response to the above might be "Well, just build a custom HTML widget then, or do it all in the theme with whatever customization you want". Yes yes yes that's the obvious thing to do... that is what we all do already. That strategy works well for some one-off situations, but for Elementor's nav-menu widget in particular, is it not a high-use widget that does a lot of complex things and should have extra features and tiny refinements.

Currently, if you want to avoid FA icons, but still have drop-down menu icons, you're forced to do custom HTML and never make practical use of the nav-menu widget. This seems like going backwards and defeats the purpose of page-builders (and paying for page builders). Convenience and efficiency are the whole point.

Moreover, currently we are limited to choose from only 4 basic FA icons as drop-down indicators, so to begin with it's not as if you're getting FA super-powers here. It's more like "Hey, FA is used elsewhere, so may as well use it here" lazyness. Is it any stretch to just put 4 code-based icons in place of the FA icons, just for the nav-menu widget?

Ultimately, my belief is that FA icons are only good for random decorative items sprinkled here and there, but for crucial interface icons, FA should be a secondary option after nicely prepared super efficient inline-code icons.

**Describe alternatives you've considered**
As an experiment to get an instant-loading drop-down menu indicator, I've put a custom CSS down-chevron in my first menu item title. It works but is very hacky. It means wherever my menu item gets rendered in WP, the chevron is there. It's not semantic at all. Moreover I have to make custom hover rules to coordinate the styling with the nav-menu widget. Still doesn't look right after X hours. So I'm fuming that I may have to make a custom HTML menu (which I've done 100's of times in my life), defeating the purpose of a quick convenient page builder nav widget. Or I just live with interface shifts, and ignore it when clients bring it up?

A CSS-only down chevron arrow, placed in my menu item text via WP/Appearance/Menus:
`My Menu <i style="margin-left: 1em;width: 0.45em;height: 0.45em;border-right: 0.1em solid rgb(255, 255, 255);border-top: 0.1em solid rgb(255, 255, 255);transform: rotate(135deg);margin-top:-0.1em;"> </i>`

**Inline code-based icon opportunities:**

CSS-only icons:
 http://nicolasgallagher.com/pure-css-gui-icons/demo/#non

HTML special characters: https://dev.w3.org/html5/html-author/charref

Also SVGs can be used for much more complex designs and have negligible browser compatibility issues in this modern day: https://codepen.io/johnasp/pen/KdVLzb

**Comment by TheMangoTrain** [comment]
Update:

Exploring another CSS workaround for my specific circumstance, using position:absolute to the FA icon, which would alleviate interface shifting once the FA icon gets rendered. However not it occurs outside of the hover effect for the main link.

With this CSS, the menu won't shift when the FA icon appears later than the main page rendering, but the icon now occurs outside of the hover color. Which means maybe having to cheat with padding on the hover. It's getting weak and complex.
```
.elementor-nav-menu--indicator-chevron .elementor-nav-menu .sub-arrow {
 position: absolute;
 right: 1em;
 top: 1.75em;
}
```

I also tried to force a width of 16px to the FA icon container _<span class="sub-arrow">_, but this seems to have no effect. Also, it's interesting to see this code exist in the page code even when choosing None for drop-down indicator. So in theory, even if there's no icon selected, and no FA being loaded, the HTML structure for the icon is still being sent to the client =/.

**Comment by ianlee** [comment]
Yes, I had the same issue, the menu jumps even with all resources browser cached.  Try my suggested edits to insert the chevron server side and disable the smartmenu's insertion.  (im the author of the linked issue)


For your custom icons without editing elementor pro , I think the filter I used above can be repurposed for that, and set the drop down indicator to None.
```

add_filter("nav_menu_item_title","wp_nav_menu_add_subarrow",100,3);
function wp_nav_menu_add_subarrow($title, $item, $args){
	$arrow = '<i style="margin-left: 1em;width: 0.45em;height: 0.45em;border-right: 0.1em solid rgb(255, 255, 255);border-top: 0.1em solid rgb(255, 255, 255);transform: rotate(135deg);margin-top:-0.1em;"> </i>';
	if(in_array("menu-item-has-children", $item->classes) ){
		$title .=$arrow;
	}
	return $title;
}
```

**Comment by TheMangoTrain** [comment]
Hi thanks for the input!

Your script functions well as-is and is indeed a better hack than placing inline CSS within the menu item title.

However the icon styling still ends up divorced from the styling of the nav-menu widgets' Default/Hover/Active colors, required manual CSS styling to overcome that. I'm unable to nicely synchronize the hover style. The nav-menu operates not with the basic CSS in-and-out hover timing, but with delays here and there.

Anyways, what I see now, beyond these hacks, this styling coordination would be difficult if dealing with this on the widget level. The custom icon I use is CSS border trickery. Border colors are not the same as font-colors for HTML codes, or fill colors for SVGs. This is a lot of fine-grained work. With this in mind I can understand the temptation to use FA icons and an existing jQuery menu library... but if they always shift the interface when loaded, what's the point of using them. Why have people accepted this all along, or not notice? I can only think of fading in the entire Section to hide the interface shift, but that's just masking the problem.

My current best working preferred solution: I keep the arrow selection in the nav-widget options, then in CSS I set the icon to position:absolute to knock it out of the page flow, so whenver it loads it'll never shift the interface. Using some padding here and there I make space in the menu bar for it. This gives me a non-shifting interface, with full colors and hover styling all looking natural. You do see the arrow pop-in late, as always, but the interface does not shift.

**Comment by ianlee** [comment]
Just thought of this... untested but should work cleanly.

Use my original filter to insert the sub-arrow dropdown indicator serverside (function from related topic)
```
add_filter("nav_menu_item_title","wp_nav_menu_add_subarrow",100,3);
function wp_nav_menu_add_subarrow($title, $item, $args){
	$arrow = '<span class="sub-arrow"><i class="fa"></i></span>';
	if(in_array("menu-item-has-children", $item->classes) ){
		$title .=$arrow;
	}
	return $title;
}
```

then in css add:
```
.sub-arrow + .sub-arrow {
  display:none;
}
```

This should prevent 2 indicators showing up, and there should always be a space for that indicator. (non shifting interface)
Colors and hover stuff should work as normal. (based on widget)
Arrow wont disappear on a page refresh, but may be delayed by a slow font-awesome (if browser cache works you're good, while with your solution you still have that issue of waiting for the JS to run)


Hope that helps, Cheers,
Ian

**Comment by TheMangoTrain** [comment]
Ah dude that is genius! It's the most elegant fix so far.

Below are the steps; anything incorrect?

**Summary:**
**1 - Choose an icon**
In the nav-menu widget, select a drop-down indicator like usual.

**2 - Inject the icon element before the SmartMenus library**
In your theme's functions.php, add the following to inject the icon structure regardless of what the SmartMenus JS library does client-side:

```
add_filter("nav_menu_item_title","wp_nav_menu_add_subarrow",100,3);
function wp_nav_menu_add_subarrow($title, $item, $args){
	$arrow = '<span class="sub-arrow"><i class="fa"></i></span>';
	if(in_array("menu-item-has-children", $item->classes) ){
		$title .=$arrow;
	}
	return $title;
}
```

**3 - Hide the original SmartMenus icon when it eventually appears on page**
In your theme's style.css, add the following to hide the original icon when it eventually appears on-page:

```
.sub-arrow + .sub-arrow {
  display:none;
}
```

**Comment by ianlee** [comment]
Looks correct to me.  Thanks for putting in the summary.

Can we get some of this added to pro core? 


If the filter or css affects other things, I'm sure some if statements/increase in specificity for css would fix any issues.

**Comment by TheMangoTrain** [comment]
Here's my specific targeting that works, the "elementor-global-1992" being my particular instance of navigation (my main menu):

.elementor-global-1992 .elementor-nav-menu .sub-arrow + .sub-arrow {
  display:none;
}

Also, I noticed in Chrome, on uncached first-visit, the interface still shifts very very slightly but I believe this is due to the actual legitimate download delay for FA and not JS processing. This seems to be resolved with the following additional CSS: making 'fa' as position:absolute within a relative 'sub-arrow'. This trick would have worked originally if not having to overcome SmartMenus JS delay.

.elementor-global-1992 .elementor-nav-menu .sub-arrow {
  position: relative;
}

.elementor-global-1992 .elementor-nav-menu .fa {
  position: absolute;
  top: -0.5em;
}

**Comment by bainternet** [comment]
Follow #5973

**Comment by yorkfrog** [comment]
have just run in to this on one of my sites.  But it seems that this is very old so wondering if I am missing something that has been fixed in the last 2 years?
-C
