### ISSUE TITLE
Feature Request: Add WooCommerce Product Bundle Compatibility

### ISSUE THREAD

**Issue by Source3Media** [pojome/elementor#6084]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
With the newer capabilities of editing WooCommerce product templates, which is amazing by the way, comes another issue. For those who use the WooCommerce Product Bundle plugin, elementor will not load, I have tried the typical disable this and that and test until you find an issue. So far, that is the only plugin giving this issue.

What happens when you enable the plugin? Well that's simple. It gives you an error stating that this content can't be loaded and to check for solutions.

And again, this only happens for this plugin.
I have tried to change the loading methods and all the typical fixes for issues like this with no solution as of yet.

**Describe the solution you'd like**
I would like to be able to use WooCommerce premium plugins without loading issues, in particular this one.

**Describe alternatives you've considered**
I have tried alternative plugins but they either dont work properly or the cost money that I've already paid.

**Additional context**
To reproduce this issue, I simply applied the WooCommerce Product Bundles plugin from WooCommerce to my site, opened a template in Elementor and it showed the issue.

**Comment by bainternet** [comment]
We can't replicate this issue,
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
