### ISSUE TITLE
Can you suggest a good mockup/wireframing sotware (Mac) which will play well with subsequent Elementor (Pro) implementation?

### ISSUE THREAD

**Issue by rjalexa** [pojome/elementor#6085]
I'd like to build a quick wireframe/mockup of a website, test its flow and features before I actually get to develop it with Elementor.

What MacOS tool would you suggest? Something that easily mapped to Elementor widgets aspect and behaviour would be super !!!

Thank you

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
