### ISSUE TITLE
WP 5.0 Beta 3: No "Edit in Elementor" button?

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#6088]
The ["Edit in Elementor"](https://docs.elementor.com/article/317-create-new-page) button is missing in the latest WP 5.0 beta 3.

![image](https://user-images.githubusercontent.com/1435638/48114064-7d0ca380-e2ad-11e8-8ec9-ff2a9665da4c.png)
		
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29
	MySQL version: (Ubuntu) v5.7.24
	PHP Version: 7.2.11-2+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0-beta3-43876
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.2.7
		Author: Elementor.com

	Elementor Blocks for Gutenberg
		Version: 1.0.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.12
		Author: Elementor.com

	WordPress Beta Tester
		Version: 1.2.3
		Author: Peter Westwood

== Debug ==
	Errors: There are no errors to display

**Comment by arielk** [comment]
We added a patch for this to the next version https://github.com/pojome/elementor/issues/6019

Thanks for your report
