### ISSUE TITLE
BUG: Archive Posts Widget displays 5 posts no matter how many columns are set

### ISSUE THREAD

**Issue by mxbc4806** [pojome/elementor#6089]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by mxbc4806** [comment]
I am building a site that will be using many post categories which I need to display on separate pages. To do so, I have set up an Archive Template and used the Archive Posts widget to display the posts for a given category.

In the layout, the widget will let me select from 1 to 6 columns to display. I want to use 4 columns, with pagination to display the next set of 4. The layout does adjust to display 4 columns but it also displays a 5th post below the first row, i.e., the display doesn't just show 4 posts with pagination below it for displaying the next 4 posts. For some reason, it wants to display 5 posts no matter what.

To get around this bug, I decided just to select a 5-column layout. However, even doing this doesn't work because I have to set a different number of columns to display on tablet and mobile. If I set the display for 2 columns on mobile, it displays 2 rows of 2, with that 5th post below on a 3rd row. If I set the display for 3 columns on tablet, same issue: it displays the first row with 3 posts with a second row below it containing 2 posts. Elementor insists on displaying exactly 5 posts before the pagination starts, no matter the layout chosen. Maddening.

The Archives Widget is extremely important to my design and organization of posts because I will have literally hundreds of posts that will need to be displayed by category.

I am running the most current version of Elementor/Elementor Pro and the most current version of WordPress. I am also using the OceanWP theme.

I have tried disabling all plugins, one by one, with no effect on this issue.

To see an example page showing the problem, please go here:

https://www.iloveoldgalveston.com/category/postcards-collection/

**Comment by bainternet** [comment]
[**@mxbc4806**](https://github.com/mxbc4806) commented on [Nov 7, 2018, 9:09 AM GMT+2](https://github.com/pojome/elementor/issues/6089#issuecomment-436526016 "2018-11-07T07:09:44Z - Replied by Github Reply Comments"):
> I am building a site that will be using many post categories which I need to display on separate pages. To do so, I have set up an Archive Template and used the Archive Posts widget to display the posts for a given category.
> 
> In the layout, the widget will let me select from 1 to 6 columns to display. I want to use 4 columns, with pagination to display the next set of 4. The layout does adjust to display 4 columns but it also displays a 5th post below the first row, i.e., the display doesn't just show 4 posts with pagination below it for displaying the next 4 posts. For some reason, it wants to display 5 posts no matter what.
> 
> To get around this bug, I decided just to select a 5-column layout. However, even doing this doesn't work because I have to set a different number of columns to display on tablet and mobile. If I set the display for 2 columns on mobile, it displays 2 rows of 2, with that 5th post below on a 3rd row. If I set the display for 3 columns on tablet, same issue: it displays the first row with 3 posts with a second row below it containing 2 posts. Elementor insists on displaying exactly 5 posts before the pagination starts, no matter the layout chosen. Maddening.
> 
> The Archives Widget is extremely important to my design and organization of posts because I will have literally hundreds of posts that will need to be displayed by category.
> 
> I am running the most current version of Elementor/Elementor Pro and the most current version of WordPress. I am also using the OceanWP theme.
> 
> I have tried disabling all plugins, one by one, with no effect on this issue.
> 
> To see an example page showing the problem, please go here:
> 
> https://www.iloveoldgalveston.com/category/postcards-collection/

**Comment by wesm912** [comment]
I'd like to re-open this issue. I have a 3 -column layout and using the latest and greatest Elementor + Pro.  At least four or five posts are displayed on the archive page.
 See https://fiddlerstest.org/newsletters/

**Comment by meghart** [comment]
I have the same issue. It's clearly a bug.

**Comment by mikemonty** [comment]
I have this issue too.

**Comment by mikemonty** [comment]
Are we going to fix this or respond to people? I've been waiting more than a year apparently. I just searched for a solution to this and hey look, there I am ^

**Comment by mikemonty** [comment]
Okay on a whim I went to the settings > reading, and changed "Blog pages show at most", that fixed the issue.
