### ISSUE TITLE
Column margin-right doesn't seem to take effect

### ISSUE THREAD

**Issue by r-emarketing** [pojome/elementor#6090]
If you check https://teamkilimanjaro.com/_cpanel/test/, you should notice that there are no margins between Hotels 1 and 2, and Hotels 3, 4 and 5

However, I added a 20px right margin to Hotels 1, 3 and 4.

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.6.38 mod_python/3.5.0- Python/2.7.5
	MySQL version: MariaDB Server v5.5.59-MariaDB-38.11
	PHP Version: 5.6.38
	PHP Max Input Vars: 1000
	PHP Max Post Size: 5G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://teamkilimanjaro.com/_cpanel
	Home URL: https://teamkilimanjaro.com/_cpanel
	WP Multisite: No
	Max Upload Size: 5 GB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.1.4
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

== Active Plugins ==
	Add Categories to Pages.
		Version: 1.1
		Author: a.ankit

	Classic Editor
		Version: 0.5
		Author: WordPress Contributors

	Custom Functions
		Version: 1.0
		Author: Jansie Blom

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Easy WP Cleaner
		Version: 1.5
		Author: Nikunj Soni

	Elementor
		Version: 2.2.7
		Author: Elementor.com

	Elementor Contact Form DB
		Version: 1.2
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 2.1.12
		Author: Elementor.com

	Essential Addons for Elementor - Pro
		Version: 2.12.4
		Author: WPDeveloper

	GDPR Cookie Compliance
		Version: 1.1.7
		Author: Moove Agency

	GP Extender
		Version: 1.0.6
		Author: The Cobalt Apps Team

	GP Premium
		Version: 1.7.3
		Author: Tom Usborne

	Jetpack by WordPress.com
		Version: 6.7
		Author: Automattic

	Post Type Switcher
		Version: 3.1.0
		Author: John James Jacoby

	Really Simple SSL
		Version: 3.1.1
		Author: Rogier Lankhorst, Mark Wolters

	Redirection
		Version: 3.6.1
		Author: John Godley

	Search Meter
		Version: 2.13.2
		Author: Bennett McElwee

	Shortcoder
		Version: 4.1.8
		Author: Aakash Chakravarthy

	Simple Custom CSS and JS
		Version: 3.19
		Author: SilkyPress.com

	Simple History
		Version: 2.28.1
		Author: Pär Thernström

	TablePress
		Version: 1.9.1
		Author: Tobias Bäthge

	The GDPR Framework
		Version: 1.0.19
		Author: Data443

	Title and Nofollow For Links
		Version: 1.05
		Author: WPKube

	WP Mail SMTP
		Version: 1.3.3
		Author: WPForms

	WP Pixabay
		Version: 1.6.1
		Author: WPclever.net

	WP Retina 2x
		Version: 5.4.3
		Author: Jordy Meow

	Yoast SEO
		Version: 9.1
		Author: Team Yoast

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by r-emarketing** [comment]
Thanks Raz!

Best,

Jansie Blom
Rees-Evans Marketing
