### ISSUE TITLE
slider Elementor not shown as in the edit screen

### ISSUE THREAD

**Issue by chenravid1** [pojome/elementor#6093]
hello
iv'e set an elemntor slider widget template and use it in the homepage
i changed the backgruod slides , but it doesnt change on site - only on the editor
what could be the problem?
thanks

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
