### ISSUE TITLE
Dragging elementor element below a section.

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#610]
Hey

I made an icon list in one section and to the right of it I have an image.

![screen shot 2016-09-21 at 20 33 49](https://cloud.githubusercontent.com/assets/5323259/18733637/b88608a2-803a-11e6-8145-8ff587f7d26e.png)

What I want to do is drag another elementor box to right below the icon list but I am not able to drop it right below the visible text.

I can drop it right above the icon list.
I can not drop it to the left, right or below the icon list.
As there should be a blue bar in all different directions.

I dropped it below and a new column was created. It would also be nice to click in the top border in the middle to split the one column into two.

I did a preview of the icon list. There are bullet points to the left of the icon list. These bullet points should not be there. The text below the icon list would be nice to have higher up. As it is too far below right now.

![screen shot 2016-09-21 at 20 43 15](https://cloud.githubusercontent.com/assets/5323259/18733798/1f9f25c2-803c-11e6-8a6e-1f49eacb01de.png)

**Comment by arielk** [comment]
I close this issue, because in the new version of Elementor (1.5) we have improved the whole interface of the editor.

Thanks for your feedback!

**Comment by paaljoachim** [comment]
That sounds great Ariel!
