### ISSUE TITLE
ADA Compliance with Elementor on WordPress

### ISSUE THREAD

**Issue by TsterRM** [pojome/elementor#6102]
So I recently started working on a WordPress website where the author used Elementor to build practically everything. The Website looks beautiful however they are trying to get it published on their school website and they need AAA rating for that to happen. 

The issue I'm having is that I do not know how to edit the auto-generated code to satisfy the ADA Act.
Is this possible? If so, where do I go to access the code?
Sorry if this is something that has been addressed but I just couldn't find the right resource for help.

**Comment by drawcard** [comment]
What sort of code are you trying to edit, can you provide specific examples? Can you also provide info about the ADA act (eg a link to some dev guidelines for it)? 

When you say "AAA" rating are you referring to WCAG AAA standards? I don't think Elementor would stand in the way of achieving that, it would come down to planning and design considerations for your site to meet the guidelines, for example you can pick your own colour combinations that meet contrast requirements. You might need a bit of extra custom coding done for things like keyboard / audio accessibility etc, or look for Wordpress plugins to help with that.

**Comment by bainternet** [comment]
@TsterRM 

Anything generated by Elementor runs through a few actions and filters hooks which you can use to catch and alter/modify the output to meet your needs.

If you have a specific question please feel free to open a new issue.

thanks.

**Comment by TsterRM** [comment]
@drawcard  @bainternet Thank you both for your responses. I'll see if I can try to find these actions and filters hooks as well as other plugins that may help!
