### ISSUE TITLE
How do I resolve this issue for ADA Compliance?

### ISSUE THREAD

**Issue by TsterRM** [pojome/elementor#6108]
![screen shot 2018-11-08 at 10 46 17 am 2](https://user-images.githubusercontent.com/43476830/48209725-d1626280-e343-11e8-92de-0fd36948f039.png)

Require some assistance. I'm using the Elementor plugin with Astra theme.
Where would I go to try and resolve this problem?

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

Like I answered on your earlier issue if you have a specific question we would be happy to assist.
thanks.
