### ISSUE TITLE
White text on white background

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#611]
Hey

I added the text editor and selected to use white text. I went to Style ->Text color and changed it to white. The text did not change from the black color to the white.

I went to the Content -> In the tinyMCE editor I changed the text color to white and it turned white so that I was not able to see the text in the left Text Editor (I selected some of the text to show it):

![screen shot 2016-09-21 at 21 01 26](https://cloud.githubusercontent.com/assets/5323259/18734090/e38a58d8-803e-11e6-9ca1-4202d2f545a5.png)

Having a white text the background should automatically change to a light grey keeping the white text visible in the Text Editor box.

**Comment by joshmarom** [comment]
> I added the text editor and selected to use white text. I went to Style ->Text color and changed it to white. The text did not change from the black color to the white.
This issue could not be replicated on our end. You can send us a link to a page that has this issue to support@pojo.me and we will try to help.

Regarding TinyMCE editor, we do not think that we should interfere with it's design.

**Comment by paaljoachim** [comment]
It did not change right away it changed after I did a few other things.
It seems the reaction was  bit slow for the change to come into affect.

**Comment by paaljoachim** [comment]
I should probably have just posted here first, but I happen to open a new issue: #679

The bottom line is what is the CSS tag I need to use to change the background color of the Elementor text editor widget?

**Comment by WPDevHQ** [comment]
By default the text editor background color is transparent and the white color you are seing is that of the section. Changing the column color in which the the text editor is place should work too.

I've not come across this issue but have seen it being reported a few times now so it would be interesting to know the theme in use and what other plugins are active.

**Comment by paaljoachim** [comment]
Adjusting the column color only adjusts the color in the preview on the right not directly in the text editor on the left. The problem is the invisible text in the left side text editor is not seen.

It is the typical way the wp editor is laid out. Transparent/white background. If one uses white text one can always add the  add_editor_style code to the functions file and then also copy editor-style.css as can also be seen in Twenty Sixteen to ones own theme. Adding a color background to the body tag of the editor-style.css.

I am writing a tutorial about this as well.

```
body {
color: #1a1a1a;
font-family: Merriweather, Georgia, serif;
font-size: 16px;
font-weight: 400;
line-height: 1.75;
margin: 20px 40px;
max-width: 600px;
vertical-align: baseline;
/* ADDED */
background-color: #0066bf;
}
```

**Comment by JackyDahlhaus** [comment]
I use Storefront and have the same issue: when I change the text in Text Editor to white (to stand out on my dark colored webpage), I can't see the text in the Text Editor anymore. 
![image](https://user-images.githubusercontent.com/47500070/52535915-f358f000-2d4b-11e9-8a23-9a6474a37326.png)
Also, changing the text color option in the style tab doesn't do anything. I need to change the text color in the text editor which is a pain if you have multiple sections with text.
