### ISSUE TITLE
Duplicate CSS with PRO and custom templates

### ISSUE THREAD

**Issue by scarydakis** [pojome/elementor#6113]
I have searched for similar issues in both open and closed tickets and cannot find a duplicate. The issue still exists against the latest stable version of Elementor.

Using latest versions of both Elementor and Pro I see duplicate custom CSS. What I mean is that it is both in-lined and included as a file. If you view the HTML source for post-25 you will see it is both inline and included at post-25.css.

[post-25.css.txt](https://github.com/pojome/elementor/files/2564122/post-25.css.txt)
[ssa-source.html.txt](https://github.com/pojome/elementor/files/2564123/ssa-source.html.txt)
[system-info-spinesociety.local-09-11-2018.txt](https://github.com/pojome/elementor/files/2564124/system-info-spinesociety.local-09-11-2018.txt)

I just wanted to add I have tried disabling plugins and switching the twenty seventeen theme and same happens. I've also pushed to a different dev environment (Cpanel LAMP stack) and the same happens.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by scarydakis** [comment]
@bainternet I've attempted to contact support 3 times. Twice they asked for site details which I provided. I have attempted a 3rd contact but no one's home! This is not great for paying customers. I just wanted to know what is going on with this issue. Can you provide any information?
