### ISSUE TITLE
Edit elementor row and columns

### ISSUE THREAD

**Issue by starterthemesnyc** [pojome/elementor#6115]
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I'm theme developer. In visual composer we're using vc_set_shortcodes_templates_dir and overriding main vc files. We can edit main rows, columns html css with vc_row.php, vc_column.php etc.. template and add settings for theme. But I didn’t find any solution for elementor. For theme developers this is really important feature. We can't edit main plugin file(includes/elements/column.php). If we do this we need to give plugin file with our theme and track all updates. 
We need a hook or template for this.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Simply not clear what you are asking?
