### ISSUE TITLE
Elementor conflict/bug with Lifter LMS

### ISSUE THREAD

**Issue by LearnWPBasics** [pojome/elementor#612]
When using Elementor to layout the Lesson content or Course description in Lifter LMS, Elementor does not render the Lesson and Course navigation items that should be below these items. Note that all of these post types are enabled in Elementor > Settings. It should also be noted that Beaver Builder correctly displays these items.

I am (im)patiently waiting for this issue to be resolved so that I can start creating the Lesson content and Course descriptions on a site where I will be selling tutorials for a few WP products, including Elementor. Imagine the irony in creating tutorial content for Elementor using Beaver Builder! LOL :)

If this issue is not addressed soon, I will have no choice but to switch out Elementor for Beaver Builder for my page builder tutorials at http://learnwpbasics.com 

Cheers!
Lyle

**Comment by joshmarom** [comment]
Hi Lyle.
We are not familiar with Lifter LMS. We would like to examine this issue, but we might need some clarification. Could you please add a screenshot of the problem?

**Comment by LearnWPBasics** [comment]
Hi Josh,

I have put together a screencast to show you what's happening; hope this 
helps resolve the issue :)

http://www.screencast.com/t/5bt7jxKlh8eT

Cheers!
Lyle Chamney
Calgary, Alberta, Canada

**Comment by joshmarom** [comment]
Thank you Lyle for taking the time to demonstrate the problem.
We have made some changes to allow better plugin compatibility. It seems like this LifterLMS compatibility issue, is resolved now.

We will probably release the official update on sunday, but would appreciate if you could test our updated master beforehand. Let us know what's the conclusion.

Thank you.

**Comment by LearnWPBasics** [comment]
AWESOME!!! :)

You guys (gals too?) are the BEST!

Works PERFECTLY!

Now I have got some work to do in creating some tutorial content with 
ELEMENTOR! :)

Cheers!
Lyle

**Comment by arielk** [comment]
Fix https://github.com/pojome/elementor/commit/97dec6ef1ab604947c646e4ade39381244adf420
