### ISSUE TITLE
ACF Non text field not showing up in Elementor.

### ISSUE THREAD

**Issue by ericadyson** [pojome/elementor#6126]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by ericadyson** [comment]
Hello. I still can't get non-text fields to show when I am creating an Elementor single template for my custom post type. I want a url or link added. The field just doesn't show.  Text fields do show and also date picker. Can you help.. it's really holding me back. Thanks

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* System info.
