### ISSUE TITLE
[Enhancement] Title and text overlay for image carousel

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#613]
This has been somehow eluded to here #302 but I feel it deserve its own request.

Could you kindly consider adding options for a title text field and a content textarea for the image carousel please?

The content of both should overlay the carousel and slide/fade in sync with the image they are attached to. 

I know it adds a little complication on per image bases and would a great addition :)

**Comment by arielk** [comment]
We get a lot of ideas and issues and I just try to arrange them neatly.

I think that this issue is very similar #302 - I'd be happy if you add your idea as a comment to the original issue, it will be clearer. let me know what's your mind..

**Comment by WPDevHQ** [comment]
Yes happy to move this to #302 :)
