### ISSUE TITLE
After update to version 2.3.0 all empty columns are disappear in the Frontend

### ISSUE THREAD

**Issue by VadymPogorelov** [pojome/elementor#6134]
After update to version 2.3.0 all empty columns are disappear in the Frontend!!!
Turn it back, please!

You have conceived a good thing - do not display the wrapper with empty content. But this approach should be applied only to widgets, but not in any case not to columns! Because empty columns are often used as a design element to indent left or right or between elements.

In general, this update has a lot of problems - for example, the parameter "Caption" = "none" does not work for the "Image" element: an empty tag "figcaption" appears in Frontend anyway.

**Comment by Matherone** [comment]
We can replicate this problem. Thousands of live sites are now broken.

Pojome had better fix this soon or it may be a "game changer".

**Comment by Darthmaul** [comment]
Major issue for my sites, would love to know if this was intentional or accidental

**Comment by arielk** [comment]
We just released a patch version (v2.3.1) for this issue, please update your site and let me know if it solves your problem

Thanks everyone for your feedback!

**Comment by born2gursikh** [comment]
After update to version 2.3.1 my global widgets pedding not working please fix it because my site stuck
