### ISSUE TITLE
Virtual Reality 360 Image viewing capability

### ISSUE THREAD

**Issue by nathan15065** [pojome/elementor#6138]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
**It will allow users to add images to their website that has a 360 view so that similar to the phone app veer.tv, you can scroll around the image in a 360 view.**

**Describe the solution you'd like**
I would like this feature of being able to click on the image and pan around in 360 as an add 360 image option.

**Describe alternatives you've considered**
360 video works if I plug it into youtube but images are different and have no way of putting on the website.

**Additional context**

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
