### ISSUE TITLE
[Request/Featured] Unified Social Feed

### ISSUE THREAD

**Issue by slowaways** [pojome/elementor#6140]
![screenshot-1](https://user-images.githubusercontent.com/9668277/48379803-25f33e00-e6b4-11e8-878d-de3b09cf88a4.png)

## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Join in a single page the social networks of an account: 
Facebook, VK, Instagram, Twitter... as a unified feed.

**Describe the solution you'd like**
Features could be based on the wp-social-feed plugin.

**Describe alternatives you've considered**
\-None-

**Additional context**
\-None-

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
