### ISSUE TITLE
arrows media carousel outside the carousel 

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#6146]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

In a creative mood i used the 'media carousel' widget for a menu. Looks cool and works nice, however I would like an option for the navigation arrows to be outside the carousel. Like you have an option for the dots to be outside the carousel. You can see a demo here: https://www.movehr.nl.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

for now, you can do that with custom CSS.

Thanks for the feedback.

**Comment by speedxcz** [comment]
Hello, we are probably in the minority, but maybe someone else will join. +1
