### ISSUE TITLE
Dynamic tags MEDIA_CATEGORY is not working

### ISSUE THREAD

**Issue by sushmak02** [pojome/elementor#6147]
Hello,

I am trying to use a CSV file in our widget uploaded from ACF custom field "file" by using the dynamic feature.
Below is the code for the same  - 
```
$this->add_control(
	'file',
	[
		'label'     => __( 'Upload a CSV File', 'myplug' ),
		'type'      => Controls_Manager::MEDIA,
		'dynamic'   => [
			'active' => true,
			'categories' => [
				TagsModule::MEDIA_CATEGORY,
			],
		],
	]
);
```
Am I missing something or this is not supported by dynamic feature?

Thanks!

**Comment by bainternet** [comment]
ACF File field in Elementor Pro defaults to `URL_CATEGORY` so try that.
