### ISSUE TITLE
Finder - Favorites & Recent

### ISSUE THREAD

**Issue by vfxdude** [pojome/elementor#6149]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
To make it easier to access frequently used links in the finder it would be nice to have favorite and recent sections (see image below).

**Describe the solution you'd like**
Possibility to add any link as favorite (maybe with a favorite button icon behind each link that show on hover, see image), and then the favorite and recent links will show when the search field is blank (see image). An alternative is to only show recent links and a button at the top for showing favorites.

**Describe alternatives you've considered**
It's possible to bookmark these links in the browser, but then they will not be synced between different browsers types. Having the links stored on the server (per user) is useful when testing recent edited pages/templates in different browsers, and also for not having to retype the same thing many times.

**Additional context**
![image](https://user-images.githubusercontent.com/20110677/48414246-75844900-e74a-11e8-971b-374ec38f4c0e.png)

![elementor-finder-favorites-recent](https://user-images.githubusercontent.com/20110677/48414296-98166200-e74a-11e8-9ad5-5680f4562388.jpg)

**Comment by bainternet** [comment]
@vfxdude 

thanks for clarifying,

So here is a quick Pro tip: Open Finder and click space and you will get the recently edited items. 

as for Favorites, we are thinking about it but for now, you can take a look at our [Developers docs](https://developers.elementor.com/elementor-finder/) and maybe implement it yourself.


thanks for the feedback.

**Comment by vfxdude** [comment]
Thanks for the tip.  I guess it's no use writing more here when the thread is closed? I just wish this worked more like a forum. It would be useful for others to get this tip too, but I guess you have documented it somewhere, just did not see it in the blog post.

**Comment by black-eye** [comment]
+1 even though it's closed now.
Ehm, and when it's claimed as "we are thinking about it", why was it closed anyway...?
