### ISSUE TITLE
Custom Element based on Slick.js don't work

### ISSUE THREAD

**Issue by devGrzegorz** [pojome/elementor#615]
Hi, 

I'm building my own element, based on `slick.js`. 
Everything seems to work just great on the output, but the elementor live preview ignores the slick.js library, and it's declaration from the footer. This makes my whole layout fall apart. 

I didn't declare any handler for this element in `elementor/assets/js/frontend.min.js`, and I think this may be the issue. But honestly, I don't want to edit the core files and deal with editing it after every single plugin update. 

Is there a way to make it work (and others .js files as well)?

**Comment by KingYes** [comment]
You need to override `get_script_depends()` method and return which JS lib you need from elementor. You can this example: https://github.com/pojome/elementor/blob/c2eaa742ea61fdb2670276b84f39103661f1ccf4/includes/widgets/image-carousel.php#L24
