### ISSUE TITLE
Sticky header on chrome mobile

### ISSUE THREAD

**Issue by shetil** [pojome/elementor#6150]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

This bug is not Elementor specific but I have submit it here because this will effect a larger number of using sticky scrolling effect.

The symptoms for this bug is that part of the sticky header dissappears when scrolling down using Chrome for Android.

It seems this is caused by Chrome chancing the viewport height when scrolling and will try to automatic 
fit the content inside.

Setting the viewport meta tag with  "minimum-scale" will fix the problem. Like this:

`<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
`

This means changing the theme or using php hooks for fixing the issues. Solution for generatedpress:

```
add_filter( 'generate_meta_viewport', 'ya_disable_mobile_zoom' );
function ya_disable_mobile_zoom() {
    return '<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">';
}
```

But if would been better if this could be fixed using css and therefore fixable for Elementor. There seems to be two alternative css solutions:

- backface-visibility: hidden. 
- position: sticky.  

## Steps to reproduce
-  Use GeneratedPress theme 
- Create a header template
- Activate sticky on the section
- Scroll down on Chrome for Android

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

**Comment by bainternet** [comment]
@shetil 

Not really something we can control since each theme has a different master to answer to.

thanks anyway.
