### ISSUE TITLE
Google Maps textbox

### ISSUE THREAD

**Issue by Seifertson** [pojome/elementor#6153]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

It would be nice to have a textbox widget that interacts with Google Maps and auto-populates typed in addresses.

An example of this: http://f4d.nl/super-forms/example-forms/#google-address-autocomplete

**Comment by bainternet** [comment]
@Seifertson 

We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.
