### ISSUE TITLE
image

### ISSUE THREAD

**Issue by clnx** [pojome/elementor#6154]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have image  as my site logo.  From last update i see a grey area under my logo. I was trying to delete and load my logo again but after update page grey are under logo is is back. While im editing page the grey area is missing after I reload page problem is back on page and in editor too.

![image](https://user-images.githubusercontent.com/23277529/48429042-9a89b380-e76c-11e8-9115-0d8350a7f946.png)
 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v5.6.38-83.0
	PHP Version: 7.1.22
	PHP Max Input Vars: 1000
	PHP Max Post Size: 48M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://algotrading.sk
	Home URL: http://algotrading.sk
	WP Multisite: No
	Max Upload Size: 48 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Refur
	Version: 1.0.5
	Author: teFox
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

== Active Plugins ==
	Block Bad Queries (BBQ)
		Version: 20180821
		Author: Jeff Starr

	Elementor
		Version: 2.3.0
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.9
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 4.5.0
		Author: Exactly WWW

	Google Analytics for WordPress by MonsterInsights
		Version: 7.3.0
		Author: MonsterInsights

	W3 Total Cache
		Version: 0.9.7
		Author: Frederick Townes

	Wordfence Security
		Version: 7.1.17
		Author: Wordfence

	Yoast SEO
		Version: 9.1
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: Cannot read property 'on' of null
			at http://algotrading.sk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:213094
			2018-11-03 13:24 +00:00

		TypeError: Cannot read property 'style' of undefined
			at http://algotrading.sk/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-11-03 13:24 +00:00

		TypeError: Cannot read property 'on' of null
			at http://algotrading.sk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:213094
			2018-11-03 12:41 +00:00

		TypeError: Cannot read property 'style' of undefined
			at http://algotrading.sk/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-11-03 12:41 +00:00

		TypeError: Cannot read property 'on' of null
			at http://algotrading.sk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:213094
			2018-10-01 15:42 +00:00

		TypeError: Cannot read property 'style' of undefined
			at http://algotrading.sk/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-10-01 15:42 +00:00

		TypeError: Cannot read property 'on' of null
			at http://algotrading.sk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:213094
			2018-09-24 15:52 +00:00

		TypeError: Cannot read property 'style' of undefined
			at http://algotrading.sk/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-09-24 15:52 +00:00

		TypeError: Cannot read property 'currentView' of undefined
			at http://algotrading.sk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:239133
			2018-09-11 14:01 +00:00
			x 7 times

		TypeError: Cannot read property 'behavior' of undefined
			at http://algotrading.sk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.8 - 2:224496
			2018-09-05 10:37 +00:00

**Comment by clnx** [comment]
algotrading.sk is my page

**Comment by bainternet** [comment]
@clnx 

Please update Elementor to 2.3.1, this was fixed.

thanks.
