### ISSUE TITLE
ONE CLICK NAV BAR PAGE SWITCHING

### ISSUE THREAD

**Issue by tarantino** [pojome/elementor#6155]
Finder is pretty cool! However, as brilliant as you guys obviously are, I'm wondering… 
why haven't you figured out a way to switch between edit pages simply by clicking on any menu item on the Nav bar with one click?
Nothing would be faster or easier than ONE CLICK!!! I have no doubt you can figure it out! Thanks for your consideration!

**Comment by black-eye** [comment]
+1 Well, I wouldn't say it better. 
(Even though you haven't filled in Prerequisites and Description and examples.) ;-)

Finder seems to be quite a usefull feature and I will propably get used to it in the future, but simple page list could be more useful in some cases. E.g. when you dont remember the page name and want to see the whole sitemap.

Also, if I've understood it right, this function is available for Admins only. I'm sure my clients, with Editor rights, would love to switch between the pages or posts as well.

For now I feel, that Finder is a nice feature with many usefull functions, except the one I wanted the most - clickable sitemap.

**Comment by bainternet** [comment]
@tarantino 	

If it was something as simple and easy as "ONE CLICK" we would have done it already.

Currently the Way Elementor Loads simply doesn't allow it, but we are looking at a few possible directions to enable it.

thanks for the feedback.
