### ISSUE TITLE
accordion titles are now links (to the page where they're located in)

### ISSUE THREAD

**Issue by invictadigital** [pojome/elementor#6156]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active: elementor's hello theme actually
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 7.1.23
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.invictadigital.pt
	Home URL: https://www.invictadigital.pt
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: pt-PT
	Timezone: Europe/Lisbon
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

== Active Plugins ==
	All In One SEO Pack
		Version: 2.9.1
		Author: Michael Torbert

	Elementor
		Version: 2.3.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.13
		Author: Elementor.com

	Elements Plus!
		Version: 1.9.3
		Author: The CSSIgniter Team

	GDPR Cookie Consent
		Version: 1.7.0
		Author: WebToffee

	Google Tag Manager for Wordpress
		Version: 1.9
		Author: Thomas Geiger

	Granular Controls Elementor
		Version: 1.0.5
		Author: Zulfikar Nore

	LoftLoader
		Version: 2.1.5
		Author: Loft Ocean

	Machete
		Version: 3.2.3
		Author: Nilo Velez

	Machete PowerTools
		Version: 3.0
		Author: Nilo Velez

	NavMenu Addon For Elementor
		Version: 1.1.2
		Author: ThemeIsle

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

	Press Elements - Widgets for Elementor
		Version: 1.7.2
		Author: Press Elements

	Simple CSS
		Version: 1.1
		Author: Tom Usborne

	Swift Performance Lite
		Version: 1.8.5
		Author: SWTE

	UpdraftPlus - Backup/Restore
		Version: 1.15.3
		Author: UpdraftPlus.Com, DavidAnderson

	WPML Media
		Version: 2.3.8
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.0.8
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.4.4
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.8.8
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.6.8
		Author: OnTheGoSystems

== Must-Use Plugins ==
	Swift Performance Lite early loader
		Version: 
		Author: 

== Debug ==
	Errors: 
		TypeError: Cannot read property 'hoverIntent' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.1 - 2:33345
			2018-11-12 23:38 +00:00

		TypeError: Cannot read property 'children' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.1.11 - 2:26864
			2018-11-07 15:48 +00:00
			x 2 times

		TypeError: Cannot read property 'groups' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.1.10 - 2:23280
			2018-10-20 20:16 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:173895
			2018-10-20 20:14 +00:00
			x 3 times

		TypeError: Cannot read property 'children' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.1.10 - 2:26864
			2018-10-20 20:06 +00:00

		TypeError: n.attributes[t.name].each is not a function
			at https://www.invictadigital.pt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:9151
			2018-10-09 12:30 +00:00
			x 9 times

		TypeError: Cannot read property 'get' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:217460
			2018-10-08 08:42 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:173895
			2018-09-29 01:56 +00:00
			x 6 times

		TypeError: Cannot read property 'children' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.1.9 - 2:26864
			2018-09-28 22:45 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://www.invictadigital.pt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:173895
			2018-09-28 19:55 +00:00
			x 6 times

				</summary>
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by DOrtiz4387** [comment]
Good afternoon-

I have the same issue.  Also, the "hyperlink" scenario skips every other row.  This is odd, and I'm trying to make every row behave this way as I need the ability to tab into each row.

I have the pro version of Elementor.
