### ISSUE TITLE
Add percent to inner section min-height option

### ISSUE THREAD

**Issue by eligence** [pojome/elementor#6157]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The inner section's layout only allows for a min-height in pixels. Allowing percents to be used would give the designer greater flexibility and in creating a properly responsive design. For example: setting an outer section with a min-height of 80vh and then setting inner-sections a percentage of that thus allow inner sections to respond to the height of the view port as well.

**Comment by bainternet** [comment]
@eligence 

First, setting a `min-height` of inner section in percentage won't actually give you the height you are looking for because percentage in height simply doesn't work like that. 

Why not use `vh` in the inner section?

**Comment by eligence** [comment]
@bainternet 

It's actually a quirk of flexbox and the markup layout you're using that allows for this "hack."

https://codepen.io/eligence/pen/xQpRxj

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by erizone** [comment]
> @bainternet
> 
> It's actually a quirk of flexbox and the markup layout you're using that allows for this "hack."
> 
> https://codepen.io/eligence/pen/xQpRxj

This helped me out a ton! Would be cool to add this to Elementor's inner section natively though.

**Comment by jmak35** [comment]
Please include this feature in the next release! Thank you.
