### ISSUE TITLE
Text Background, border and heading colors Not Working! 

### ISSUE THREAD

**Issue by caelhorta** [pojome/elementor#6159]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

I'm working on a institutional website. Now, i'm trying to add a color background at a text box but its not working, as same as the text color at the "heading" element. i've tryed everything, but seems like the data its not being saved, since I inspect the page and no signal on the background. So, Now i've add manually the background collor at the element, because the data was empty, and finally worked. So, background, border, and text color not working. pls help me! thanks!

<img width="860" alt="screen shot 2018-11-13 at 22 29 07" src="https://user-images.githubusercontent.com/45020678/48451901-b6548000-e793-11e8-8e93-2789421a315d.png">

<img width="1125" alt="screen shot 2018-11-13 at 22 22 43" src="https://user-images.githubusercontent.com/45020678/48451691-b2742e00-e792-11e8-86cf-a3a4bad120bd.png">
<img width="1027" alt="screen shot 2018-11-13 at 22 22 54" src="https://user-images.githubusercontent.com/45020678/48451692-b30cc480-e792-11e8-8df1-a6bf791eb08d.png">

## Steps to reproduce

Simply change the background text with any color or the text color for the "headings" elements. Not wokring, at all. 
## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by caelhorta** [comment]
Thanks, we were able to resolve this issue. we needed writing permission at the "elementor" directory that was inside the upload folder. :-) Thanks!
