### ISSUE TITLE
Increase the Menu cart

### ISSUE THREAD

**Issue by corke** [pojome/elementor#6160]
Hello all,

Menu cart actually is not bad, but it's not good for me...In my opinion this canvas menu is not good for ecommerce.

I would prefer just something more easy like :  when we hover the cart we got a small window show the cart content(No need to click for just show the cart, I know it's ajax but it's will be better with just an hover for me and a smaller window) and when we click on the cart we directly go on the cart page. 

At this moment, users want go to their cart and start manage (Add more quantity / Delete products) have to do 2 click not only 1...

Thanks !

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
