### ISSUE TITLE
Update to v2.3.1 has many console error !

### ISSUE THREAD

**Issue by shangdev** [pojome/elementor#6161]
![image](https://user-images.githubusercontent.com/15621520/48463167-21469b00-e816-11e8-8ca7-3724a51e5b12.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
