### ISSUE TITLE
Adding Slack icons as pre-defined options for the Social Icons Widget.

### ISSUE THREAD

**Issue by nadavlevyme** [pojome/elementor#6162]
Following my email to the support, please consider adding Slack icons as pre-defined options for the Social Icons Widget.

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
@nadavlevyme 

We will, once we move to FA5
I merged this issue with  #4430 	, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
