### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by wayheming** [pojome/elementor#6163]
In the documentation says that the standard `toogle` option is turned off but in fact it works and you need to specify `false`.
https://developers.elementor.com/elementor-controls/choose-control/

http://prntscr.com/li5kk3

elementor\includes\controls\choose.php

http://prntscr.com/li5l7o

**Comment by bainternet** [comment]
@wayheming 

thanks for letting us know, fixed!

**Comment by wayheming** [comment]
@wayheming thanks for the quick response!
