### ISSUE TITLE
ACF non-text type field data not showing up in dynamic widgets like Icon URL or Image Src.

### ISSUE THREAD

**Issue by Anaon** [pojome/elementor#6164]
https://github.com/pojome/elementor/issues/5344 is still not fixed and asked to open a new ticket.

Nothing changed, exactly the same issue

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

The issue that was reported in OP of #5344 Is fixe, now without any information, we cant help.

thanks

**Comment by Anaon** [comment]
Come on, you can't be serious. It is EXACTLY the same issue not fixed, that's what we are telling you, even the author of the ticket.

**Comment by davidamarek** [comment]
Any update on this? URL fields are still not showing up in the ACF dropdown options under dynamic content.

**Comment by sermalefico** [comment]
wtf!?

**Comment by sermalefico** [comment]
Still no fix
