### ISSUE TITLE
In Post Grid when I add MetaData why I can´t choose tags too

### ISSUE THREAD

**Issue by lauranunez** [pojome/elementor#6165]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Normally in MetaData you can show your tags.
Author, Date, Comments and Tags. In Elementor Pro Grid Post I haven´t how to show my tags.
In my web is very important these tags

**Describe the solution you'd like**
In the Box where I can add MetaData. I could choose tags too.

**Describe alternatives you've considered**
A solution for I can show my metatags in Post Grid.

**Additional context**
Thank you

**Comment by bainternet** [comment]
Please Follow #4440 

thanks.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
