### ISSUE TITLE
MAJOR BUG: CSS in Tablet Mode completely crashed and not editable after update... (site on tablet also no longer live...)

### ISSUE THREAD

**Issue by CaptainJakethe1st** [pojome/elementor#6168]
Hey, 

after the latest update of elementor and elementor extras, the CSS of tablet mode of the site is completely crashed. Also all elementor site who use to be online, are no longe reachable with tablet. 

I also can not edit anything in tablet mode, it just doesn't change anything. 

Domain: brainboost.de

Best 
Jakob

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by jpiscool** [comment]
i am having an issue where tablet mode is effecting desktop layout
