### ISSUE TITLE
Git version control for Elementor

### ISSUE THREAD

**Issue by ahm-3d** [pojome/elementor#6169]
My question is not much of an issue but maybe a feature request or perhaps your professional expertise to point me to the right direction.

I am a senior web developer / digital manager at the company i work for. i have been exploring elementor since it has been in production, i was one of the first 200 people who downloaded elementor from the wordpress repo and since then i fell in love with it and for so long i been trying to push the idea of using elementor as the ultimate page builder for all web projects. Having all the most common and various page builder elements already included does speed up the development process and avoids re-inventing the wheel and the developer api available does allow to create bespoke solutions as of when it is required.

All that in mind, as a developer it does change the prespective of how a developer should use version control as most of the changes that are made is effecting the database more than the actual code within the theme.

My question, is there a suitable or recommended way to use version control to complement web development using elementor?

Based on my knowledge and research, i believe there needs to be away to be able to version control the database, preferably using git as it is the most common standard in this day and age to version control your development process.

I have come across version press which seems to be a good bet after few trials however according to version press this solution is still incomplete as it is currently under development.

Will or does elementor have any plans in not too distant future to implement a feature that will make version control using git possible? if not then can you advise of a solution or a workflow that can be used for elementor. this will help me to push the idea to my director for using elementor for all our projects.

**Comment by bainternet** [comment]
@ahm-3d 

Elementor is just like any other WordPress Plugin (well other than the fact that its "The World's Leading WordPress Page Builder") 

We use the native post revision to save changes just like WordPress does, so to answer your question,

We don't have any plans to implement a built-in git version control system anytime soon.


thanks for the feedback.

**Comment by rw215** [comment]
Been thinking about this a good deal myself. For a complete way to track wouldn't something like versionpress work?

**Comment by doodirock** [comment]
So how is version control handled around dev -> stage -> production?  If I make changes in dev and want to push them to production I have to go into each instance and make all the updates again for all instances?
