### ISSUE TITLE
Feature request: Custom options for basic widget, row and column

### ISSUE THREAD

**Issue by wayheming** [pojome/elementor#6171]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hello, I am a theme developer and now our team have a new project with which we need your help.
Previously, we used WPBakery Page Builder as the main page builder but now we have decided to switch to the Elementor which we believe is more promising and really easy to use for the end-user.
For now, we had a problem with changing the base widgets (elements) more simply, we need to add custom settings for basic widgets for example such as (Button, Image) and also we need to add options to the Row and Column.
WPBakery Page Builder has a mechanism to rewrite basic widgets or add custom options.
I searched for a quiet time on the Internet and read a lot of the issues on this subject but I did not find the exact answer. Is there such a mechanism in the Elementor?
If so, how does it work? Preferably with an example or a link to the documentation. If not, is it possible to add such feature in the near future?

Kind Regards

**Comment by bainternet** [comment]
@wayheming 

Yes its possible to extend any element(section columns or widget) in elementor.

If you want to add controls of existing widget use the provided hooks:
```PHP
// Add select dropdown control to button widget
add_action( 'elementor/element/button/section_button/before_section_end', function( $element, $args ) {
	// add a control
	$element->add_control(
		'btn_style',
		[
			'label' => 'Button Style',
			'type' => \Elementor\Controls_Manager::SELECT,
			'options' => [
				'fancy' => 'Fancy',
				'stylish' => 'Stylish',
				'rounded' => 'Rounded',
				'square' => 'Square',
			],
			'prefix_class' => 'btn-style-',
		]
	);
}, 10, 2 );
```

Or maybe update an exsisting control: 
```PHP
// Update html tag control of section and add "form" tag as an option
add_action( 'elementor/element/section/section_layout/before_section_end', function( $control_stack, $args ) {
	// Get existing control
	$control = \Elementor\Plugin::instance()->controls_manager->get_control_from_stack( $control_stack->get_unique_name(), 'html_tag' );
	// Add new option
	$control['options']['form'] = __( 'Form' );
	// Update the control
	$control_stack->update_control( 'html_tag', $control );
}, 10, 2 );
```


Basiclly you can do a lot if you understand the way it works.
We have a lot covered in our [Developers Docs](https://developers.elementor.com/)

Feel free to open a new issue if you have a specific question.

**Comment by wayheming** [comment]
@bainternet thank you!
