### ISSUE TITLE
the_content filter not triggering on Post Content widget in custom template

### ISSUE THREAD

**Issue by nosegraze** [pojome/elementor#6173]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

NOTE: I believe this issue is the same as https://github.com/pojome/elementor/issues/5800 I'm creating a new issue because that issue was closed.

I believe `the_content` filter is not running on post/page content in Elementor Pro when using a custom template. This is not an issue when just using the free plugin without custom templates; it only happens with a custom post template. This is causing a conflict with the Restrict Content Pro plugin, which uses `the_content` filter to hide/restrict access to posts based on membership status.

This is NOT a duplicate of https://github.com/pojome/elementor/issues/4493 . Restrict Content Pro uses priority `100` on the filter, which is higher than what you said Elementor uses, and I can confirm RCP's function on the filter isn't running at all.

With a guest viewing a restricted post, this is the expected result:

![elementor-rcp-full-width-template](https://user-images.githubusercontent.com/6324272/48489200-5fde5480-e81a-11e8-9fe2-2f29d7be73a3.png)

The content has been removed/hidden by RCP.

With a restricted post, this is the actual result with Elementor Pro:

![elementor-rcp-custom-template](https://user-images.githubusercontent.com/6324272/48489213-6cfb4380-e81a-11e8-881f-9c88509ba13a.png)

The post content is visible to guests when it shouldn't be.

## Steps to reproduce

1. Activate Elementor, Elementor Pro, and Restrict Content Pro.
2. Create a new Elementor Template with these settings:
![elementor-template-settings](https://user-images.githubusercontent.com/6324272/48489251-87352180-e81a-11e8-9d67-64acd3b2172e.png)
Display conditions set to "All Posts".
3. In the template, add a "Post Content" widget. This is the main concern for this issue. I also have a "Post Title" widget in mine, but that's not particularly relevant.
4. Create a new post and set up Restrict Content Pro restrictions like this:
![rcp-restrictions](https://user-images.githubusercontent.com/6324272/48489343-bb104700-e81a-11e8-8f93-cc2059ba9852.png)
Any restriction will do, but that's what I'm using.
5. Edit with Elementor and insert anything at all. I'm personally just using a simple Text Editor widget with text.
6. Save.
7. View the post as a guest. The content should be hidden/restricted, but it's not. It's visible.
8. Edit the post again and change the "Template" to "Elementor Full Width". This fixes the issue. This tells me that the problem specifically lies with _custom_ Elementor templates.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro). --- NOTE: I also have Restrict Content Pro active, but no other plugins.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/XMVxXjJf

---

I believe the problem is in the file `elementor-pro/modules/theme-builder/widgets/post-content.php`. Specifically this block:

```php
// Print manually (and don't use `the_content()`) because it's within another `the_content` filter, and the Elementor filter has been removed to avoid recursion.
$content = Plugin::elementor()->frontend->get_builder_content( $post->ID, true );

// Restore edit mode state
Plugin::elementor()->editor->set_edit_mode( $is_edit_mode );

if ( empty( $content ) ) {
	Plugin::elementor()->frontend->remove_content_filter();

	// Split to pages.
	setup_postdata( $post );

	/** This filter is documented in wp-includes/post-template.php */
	echo apply_filters( 'the_content', get_the_content() );

	wp_link_pages( [
		'before' => '<div class="page-links elementor-page-links"><span class="page-links-title elementor-page-links-title">' . __( 'Pages:', 'elementor-pro' ) . '</span>',
		'after' => '</div>',
		'link_before' => '<span>',
		'link_after' => '</span>',
		'pagelink' => '<span class="screen-reader-text">' . __( 'Page', 'elementor-pro' ) . ' </span>%',
		'separator' => '<span class="screen-reader-text">, </span>',
	] );

	Plugin::elementor()->frontend->add_content_filter();

	return;
}
```

The issue I'm encountering is that `$content` is NOT empty, so we never make it into the `if` statement where `the_content` filter is applied. So from what I can gather, `the_content` filter is never applied at all.

---

I'm a developer for Restrict Content Pro and we have several customers using these two plugins together so I'm keen to find a solution for them. If you need access to our RCP GitHub repo for testing I am happy to provide it.

**Comment by brunocerq** [comment]
Finally someone make Raz Ohad look into this, I got so frustrated by his opinion that this was a duplicate issue from another thread, and it was not, maybe I did not explain the issue so well has you did nosegraze.
Really waiting for this to be fixed, there are other plugins that don't work with custom single post template until they fix the "the_content" issue.

**Comment by arielk** [comment]
This tweak is now available in Elementor Pro v2.3.0

Thanks for your feedback!

**Comment by fgriffin125** [comment]
I'm having the same problem and I'm on  Elementor Pro v2.6.2 and Restrict Content Pro Version 3.1.1.

**Comment by sdenengelsman** [comment]
We're having exactly the same issue where the Archive Posts shows posts that are actually restricted to the user using RCP.
The result is annoying and ugly:
![image](https://user-images.githubusercontent.com/8897678/109575758-bdcdfd80-7af2-11eb-8251-46e2fcd9b533.png)

@arielk -> you said "this tweak is now available". Can you elaborate? How do we fix this?

Thanks!
