### ISSUE TITLE
Update to v2.3.1 has many console error !

### ISSUE THREAD

**Issue by shangdev** [pojome/elementor#6174]
## Prerequisites
The issue only exists against the latest stable version of Elementor v2.3.1.

## Description
When i login admin, press F12
I saw that the console has two errors caused by Elementor, two errors caused by wordpress, and the error comes from some JS in Elementor. I didn't have these errors until I upgraded to the latest version.

![image](https://user-images.githubusercontent.com/15621520/48490495-8921d380-e860-11e8-920d-7190bcd90f15.png)

![image](https://user-images.githubusercontent.com/15621520/48490462-7ad3b780-e860-11e8-801f-77e123a1b728.png)

When i deactive elementor plugins, Error only one:
![image](https://user-images.githubusercontent.com/15621520/48490685-e74eb680-e860-11e8-80a8-b8ded2744a69.png)

## Steps to reproduce
This bug only happens in the admin.

## Environment
Home URL: http://dev.xx.com
Site URL: http://dev.xx.com
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: zh_CN
External object cache: –

**Comment by bainternet** [comment]
@shangdev 	

We can't replicate this issue, please try reinstalling elementor an also try adding `define( 'SCRIPT_DEBUG', true );` to your wp-config.php so it will force Elementor and WordPress to use the "dev" versions of some core CSS and JavaScript so you could get a better idea what's causing the error.

**Comment by shangdev** [comment]
@bainternet 

I noticed that this problem only exists when I use vuejs, so maybe it is a conflict between js?
And I also used [iview](iviewui.com), 
But I found that it should not be caused by iview.

**Comment by bainternet** [comment]
Probably,
