### ISSUE TITLE
Section editor tab hidden behind elements with high z-index

### ISSUE THREAD

**Issue by eligence** [pojome/elementor#6175]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

When editing designs the webpage often has elements with a high z-index (for example a sticky nav bar). This results in the Section Layout Editor Tab being hidden behind the element forcing the user to inspect the page to change the z-index. Please set the z-index higher (if not as high as possible) for this tab.

**Comment by bainternet** [comment]
@eligence 	

For these exact reasons we created the [Navigator](https://elementor.com/blog/introducing-navigator/)
