### ISSUE TITLE
Publish and Display Conditions in editor throws: Uncaught TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by davingreen** [pojome/elementor#6177]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

The editor is throwing an error when I attempt to Publish a template or set display conditions. Video of issue: https://drive.google.com/file/d/1TAtpDRu0No6YfwMcnFWryuiRnXmq_ism/view?usp=drivesdk.

```
VM3709:8 Uncaught TypeError: Cannot read property 'add' of undefined
    at eval (eval at m.template (underscore.min.js?ver=1.8.3:5), <anonymous>:8:19)
    at c (underscore.min.js?ver=1.8.3:5)
    at Object.render (backbone.marionette.min.js?ver=2.4.5:22)
    at n._renderTemplate (backbone.marionette.min.js?ver=2.4.5:23)
    at n.render (backbone.marionette.min.js?ver=2.4.5:23)
    at n.renderChildView (backbone.marionette.min.js?ver=2.4.5:22)
    at n._addChildView (backbone.marionette.min.js?ver=2.4.5:22)
    at n.addChild (backbone.marionette.min.js?ver=2.4.5:22)
    at n.<anonymous> (backbone.marionette.min.js?ver=2.4.5:22)
    at underscore.min.js?ver=1.8.3:5
```

No plugins are enabled and current theme is Twenty Seventeen. I've disabled caching and script concatenation with no change to the issue. However, I was using the eletheme theme when the error first occurred.

## Steps to reproduce
1. Open or create a new template. (In this case, a 404 template.)
2. Make changes to content.
3. Attempt to Publish (error thrown)
4. Attempt to open Display Conditions (error thrown)

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '23', Revision '500fcf5' v5.7.23-23
	PHP Version: 7.2.11-4+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://beta.staffwrx.com
	Home URL: https://beta.staffwrx.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Eletheme
	Version: 1.1.0
	Author: Liviu Duda
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.3.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.4
		Author: Elementor.com


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	Stop long comments
		Version: 0.0.4
		Author: WPEngine

	WP Engine System
		Version: 3.2.1
		Author: WP Engine


== Debug ==
	Errors: 
		TypeError: Cannot read property 'add' of undefined
			at https://beta.staffwrx.com/wp-admin/post.php?post=148&action=elementor - 8:19
			2018-11-14 17:15 +00:00
			x 6 times

		TypeError: Cannot read property 'add' of undefined
			at https://beta.staffwrx.com/wp-admin/post.php?post=148&action=elementor# - 8:19
			2018-11-14 17:09 +00:00
			x 3 times

		TypeError: Cannot read property 'add' of undefined
			at https://beta.staffwrx.com/wp-admin/post.php?post=147&action=elementor# - 8:19
			2018-11-14 17:02 +00:00
			x 7 times

		ReferenceError: editModel is not defined
			at https://beta.staffwrx.com/wp-admin/post.php?post=54&action=elementor - 12:12
			2018-11-14 17:00 +00:00
			x 2 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://beta.staffwrx.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.7 - 2:239323
			2018-11-08 19:54 +00:00
			x 6 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://beta.staffwrx.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:239178
			2018-09-22 21:32 +00:00

		ReferenceError: gformInitSpinner is not defined
			at https://beta.staffwrx.com/wp-admin/post.php?post=36&action=elementor - 1:36
			2018-09-22 19:48 +00:00
			x 2 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://beta.staffwrx.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:239178
			2018-09-22 19:26 +00:00
```
</details>

**Comment by bainternet** [comment]
@davingreen 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by Bugreal** [comment]
Make sure that you are using the latest version of Elementor Pro (2.2.0) to solve this issue. The pro version does not self-destruct. It will work with old versions of Elementor. The current version of Elementor is not compatible with old versions of Elementor Pro and it is not written in the docs that the developers guarantee backwards compatibility between old versions of Elementor pro and new versions of Elementor. This is why you experience this editing issue, however, your website project is intact.

**Comment by AresLee** [comment]
downloaded the 2.2.0 manually instead of the using the previous version 2.1.9. Problem solved....

**Comment by aronmoshe-m** [comment]
Updating to current issue of Pro plugin solved this exact issue for me. Make sure that your plugins (both Elementor and Elementor Pro) are up to date.
