### ISSUE TITLE
Disqus comments can't synchronize after use elementor single post template

### ISSUE THREAD

**Issue by Rayner33** [pojome/elementor#6178]
I changed my site theme to new one (OceanWP) and now I can use Elementor Single Post Template. I created one but now have a problem with comments from Disqus. Every posts what was made before without elementor, have comments, but every post made by elementor have no my old comments and 
I can't synchronize them to my posts, after I changed single post view to template from elementor? Why is this problem if I still have the same permlinks in posts?

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
