### ISSUE TITLE
Elementor template missing some screen options

### ISSUE THREAD

**Issue by besweeet** [pojome/elementor#6184]
I'm using [the All In One SEO plugin](https://wordpress.org/plugins/all-in-one-seo-pack/). I have a post archive template configured in Elementor and would like to update its meta description and some keywords. With this SEO plugin, those options would be available as a screen option, but when at the WordPress editor for the template / archive, the SEO options aren't available. Is this the fault of Elementor or the SEO plugin?

**Comment by bainternet** [comment]
@besweeet 

Not sure I understand what you are saying I would suggest to take a look at this
https://semperplugins.com/missing-all-in-one-seo-pack-2-6-post-and-page-meta/

**Comment by besweeet** [comment]
When editing an Elementor page in the WordPress editor, the SEO option is available: https://i.imgur.com/FGKnNFh.png

When editing an Elementor archive template in the WordPress editor, the SEO option is not available: https://i.imgur.com/5qgUnWP.png

So I don't know if this is a limitation with the plugin not hooking into custom post types or other page templates properly or if it's a limitation with Elementor not allowing plugins in.
