### ISSUE TITLE
Lightbox effect with post widget pro

### ISSUE THREAD

**Issue by MirkoH17** [pojome/elementor#6190]
Hi,
coming recently from VC to Elementor and compared to VCs post grid options I miss one smart feature within posts widget pro:

I would like to have an option for lightbox functionality of my post image. 
So far I could not find any workaround by custom code or a plugin

Thanks,
Mirko

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

this will be possible once #4440 is implemented.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
