### ISSUE TITLE
WPGlobus id class lost from one language to another

### ISSUE THREAD

**Issue by jcmanso** [pojome/elementor#6191]
## Description

 I'm making a page in two languages: Spanish and Portuguese. Spanish is the main language.

## Steps to reproduce

First I used the WPML plugin, but it gave me problems. I deactivated it and installed the WPGlobus plugin.
I duplicated all the pages. When I update and save them, only the classes of the last page made are saved. That is to say, if I make a duplicate from Spanish to Portuguese, guardo, only the Portuguese version is correctly seen in the browser, although the two versions are correctly seen in the elementor editor. When you see the pages in a browser you only see the last saved version correctly, if I have worked on the Portuguese version, that's the one you see correctly, the Spanish version is no longer seen correctly. If I update the Spanish version of that page with the elementor editor, the Spanish version looks good in the browser, but the Portuguese version no longer looks correctly. And so on to infinity.
Asked to the programmers they have told me that it is due to that when saving the page in a language, the identifier of the class in the other language is lost.

## Isolating the problem
- [ ] WPGlobus id class lost from one language to another (Elementor pro)

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.59-MariaDB-38.11
	PHP Version: 7.1.22
	PHP Max Input Vars: 4000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://encompania.sjdigitaldemo.ovh
	Home URL: https://encompania.sjdigitaldemo.ovh
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: es-ES
	Timezone: Europe/Madrid
	Admin Email: info@sjoficinadigital.com
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.3.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.1.13
		Author: Elementor.com

	EventON
		Version: 2.6.13
		Author: AshanJay

	WPGlobus
		Version: 1.9.26
		Author: WPGlobus

	WP Post Page Clone
		Version: 1.0
		Author: Gaurang Sondagar

== Debug ==
	Errors: 
		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=1151&action=elementor# - 8:19
			2018-11-13 11:24 +00:00
			x 18 times

		TypeError: elementorFrontend.getElements(...).jQuery is not a function
			at https://encompania.sjdigitaldemo.ovh/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.1 - 2:226007
			2018-11-13 11:24 +00:00
			x 2 times

		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=1127&action=elementor&lang=pt-pt - 8:19
			2018-11-13 10:42 +00:00
			x 3 times

		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=685&action=elementor - 8:19
			2018-11-13 10:05 +00:00
			x 11 times

		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=1100&action=elementor&lang=pt-pt - 8:19
			2018-11-13 09:52 +00:00

		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=685&action=elementor - 8:19
			2018-11-13 09:52 +00:00
			x 14 times

		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=1100&action=elementor&lang=pt-pt - 8:19
			2018-11-13 09:46 +00:00
			x 2 times

		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=1100&action=elementor - 8:19
			2018-11-13 09:45 +00:00
			x 4 times

		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=1100&action=elementor&lang=pt-pt - 8:19
			2018-11-13 09:45 +00:00
			x 9 times

		TypeError: Cannot read property 'add' of undefined
			at https://encompania.sjdigitaldemo.ovh/wp-admin/post.php?post=685&action=elementor - 8:19
			2018-11-13 09:31 +00:00
			x 2 times

```
</details>

**Comment by AiratHalitov** [comment]
I have the same issue on ENG-RUS website with Elementor (free) plugin.

**Comment by bainternet** [comment]
@jcmanso 

Please contact WPGlobus with this issue, since elementor has nothing to do with translations or they way the pages are duplicated by the translation plugin.

thanks.
