### ISSUE TITLE
Elementor 2.3.1 + Woocommerce - Issue in the Checkout Page

### ISSUE THREAD

**Issue by JulimanS** [pojome/elementor#6192]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

There is a bug with the latest version of Elementor 2.3.1 in the checkout page of a Woocommerce.
When the user tries to make a purchase, it prompts an empty error.

The user thinks the purchase couldn't be done but in a backend level everything goes well, so the store owner receives the order and the payment, thinking everything goes well.

Each time the user clicks on the "Finish Order" button on the checkout page, is triggering a new order, causing a high level of copies and payments form the same client.

## Steps to reproduce

1. Add an item to the cart.
2. Go the checkout page.
3. Fill the data.
4. Press the "finish order" button.

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active. (Couldn't check yet)
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Wordpress 4.9.8
Theme: GeneratePress 2.18
Plugins active:
Code Snippets 2.12.1
Elementor 2.2.7
Facebook for Woocommerce 1.9.7
FacetWP 3.2.5
FacetWP - Load more 0.4.1
GP PRemium - 1.7.2
Mailpoet 3.14
MonsterInsights Pro 7.0.18
MonsterInsights - Ecommerce Add-on
Payment Gateway Based Fees and Discounts for Woocommerce 2.5.5
Menu Roles 1.9.2
Woo Checkout Field Editor Pro 1.3
Woocommerce 3.5.1
Woocommerce Advanced Product Labels 1.1.4
Woocommerce Product Add-ons 2.9.6
Woocommerce Push Over Integration 1.0.14
Woocommerce Stripe Gateway 4.1.12
WP HTML Mail 2.8.3.1
Wp HTML Mail - Woocommerce 2.8
WP Mail SMTP
Yoast SEO
Yoast SEO - Woocommerce

</details>

**Comment by Nashoot** [comment]
I had the same Issue here and wasn't sure it comes from Elementor or Toolset Layout Plugins. i just updated the plugin to the latest version of elementor 1 hour ago and this has fixed the Issue.

https://toolset.com/forums/topic/layouts-plugin-elementor-syntaxerror-unexpected-token-in-json-at-position-0/

**Comment by arielk** [comment]
Hi

Sorry for the inconvenience, we just released a patch for this issue (v2.3.2), please update the plugin and let me know if it fixes your problem.

Thanks

**Comment by asdownload** [comment]
i have a big problem with elementor pro with woocommerce

when active elementor pro the pages such as add to car and checkout dont show.

https://chalik.net/product-category/robot-pack/
for test add to cart on of products 

i use other version of elementor and update woocommerce and wordpress
