### ISSUE TITLE
Integrate Elementor widgets into my widget

### ISSUE THREAD

**Issue by wayheming** [pojome/elementor#6193]
Hello, thank you very much for your help in my previous questions, you helped me a lot.
I created issue #6148 earlier and asked about the integration of your basic button widget into my widget in order not to duplicate the code.
You answered me that I can extend my widget by inheriting the widget button class.
Could you give me an example or give a link to the documentation I will be very grateful.

**Comment by bainternet** [comment]
@wayheming 	

Here is a link to our [developer's docs](https://developers.elementor.com/)

and here is a demo [Plugin/Elementor Widgets](https://github.com/pojome/elementor-hello-world) you can learn a lot from.

thanks.
