### ISSUE TITLE
Custom Add To Cart

### ISSUE THREAD

**Issue by simonclay** [pojome/elementor#6194]
I have added the Custom 'Add to Cart' button onto a regular page and selected the Product required.

After saving the page and visiting it:

When clicking the 'Add to cart' button, you are taken to the top of the page, with no feedback as to whether it has been added to the cart (it had been added, just no indication).

Secondly, afterward, when visiting the shop archive page I suddenly see a load of 'indicators' saying 'You added this to your basket'
![screen shot 2018-11-16 at 17 41 02](https://user-images.githubusercontent.com/2143351/48640298-2ea68580-e9ce-11e8-8704-df8ef01b4441.png)

So, to recap, my 2 issues are:

1) when adding to basket there is no feedback to say it has been added.
2) on the shop archive page, 'You added this to your basket' notices start to build up.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@simonclay 

We can't replicate, once you click "Add to cart" you see a little "View cart" right next to the add to cart button.


Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by simonclay** [comment]
RESOLVED: 
I found that the issue was due to my setting the shop page as a 'Single' Elementor template, rather than a 'Single Product' template. I didn't realise there were those 2 distinctions.
