### ISSUE TITLE
WP gallery and elementor galery

### ISSUE THREAD

**Issue by Podtwal** [pojome/elementor#62]
Hi, I'm test Elementor Version 0.2.3 and Wordpress 4.5.2.

First: I tried to insert the default WP gallery in the frontend editing process, but only the shorcode is rendering. Is that a knowing Bug?

Second: Where can I find the elementor gallery widget? It isn't listed in the widget pallet.

**Comment by arielk** [comment]
1. Thanks for your reporting. Fixed (c625d81)

2. We're working on it for the next version (#35) please keep updated
