### ISSUE TITLE
Documentation needed 

### ISSUE THREAD

**Issue by hillofbeans** [pojome/elementor#6200]
Hi,

Apologies in advance I don't even know what GitHub is, but I was told I had to come here to ask my question, even though I know nothing about coding.

This was after I posted a question in Elementor Pro support and said my issue falls outside their remit of only dealing with 'front-end support issues.'

Frankly I find this quite shocking, as I have no idea if this is part of my support package, who populates these forums, or if my posts are treated with confidentiality or with any security in mind.

I thought I was paying Elementor Pro for support, but evidently, that's is the case....

Regardless, rant over, here's my question:

I'm using a script manager plugin to selectively load javascript and css files on individual pages, according to which plugins are being used.

For instance, things like tablepress, amazon plugins, sliders, related posts - I have disabled the corresponding js and CSS files using https://wordpress.org/plugins/gonzales/ script manager and only enable them in the pages that need them.

With Elementor however, I've noticed tons of files are loaded, and I'm pretty sure that all of these are necessary. For instance, stuff like fancy text animations, particle effects, filter/blend modes, sticky scrolling, I'm not using any of this stuff but there's no documentation to tell me exactly which files Elementor is loading and which ones I'm actually using

All I need is some basic documentation that tells me what each Elementor js/CSS file does, and then I can do my own research and see if it needs loading. The script manager is pretty good at showing dependencies, I've attached a screenshot.

I'm just trying to optimize my site, reduce load times etc. Any help would be greatly appreciated.
![screen shot 2018-11-17 at 01 34 23](https://user-images.githubusercontent.com/45131285/48665873-70a6f880-eaae-11e8-95a5-0aaecf1bd4e9.png)

**Comment by bainternet** [comment]
@hillofbeans 	

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

thanks.

Now that we got out of the way,

Elementor tries to load only the needed JS and CSS, by deafult the script loaded on a page that uses Elementor are:

* `elementor-dialog`, `jquery-swiper` - used for lightbox.
* `elementor-waypoints` - used for animations, sticky and few other things.
* elementor-frontend - Used to manage everything Elementor Elements need to display corectly.

Anything other than that is based on your use case and elements used.

thanks.
