### ISSUE TITLE
Self Hosted Video with Overlay and Lightbox Doesn't Work

### ISSUE THREAD

**Issue by wwaag76** [pojome/elementor#6201]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

For self-hosted videos, if you have an Image Overlay and Select Use Lightbox, only the audio plays.  There is no video.  It works OK for Vimeo but not for self-hosted videos.  Andri from the support staff verified the problem and suggested that I create a bug report.

## Steps to reproduce

Add video widget.
Select self-hosted.
Select video from media library.
Add an Overlay Image
Select UseLightbox.
Then play.
The result--only audio--no video.  Works OK with Vimeo.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 7.0.32
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://tools4vegas.com
	Home URL: https://tools4vegas.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.5.31
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

== Active Plugins ==
	Cookie Notice
		Version: 1.2.44
		Author: dFactory

	Dark Mode
		Version: 3.1
		Author: Daniel James

	Download Manager
		Version: 2.9.82
		Author: Shahjada

	Elementor
		Version: 2.3.1
		Author: Elementor.com

	Elementor Contact Form DB
		Version: 1.2
		Author: Sean Barton - Tortoise IT

	Elementor Pro
		Version: 2.1.13
		Author: Elementor.com

	Enable Media Replace
		Version: 3.2.7
		Author: ShortPixel

	External Media
		Version: 1.0.18
		Author: Minnur Yunusov

	Force Refresh
		Version: 2.1
		Author: Jordan Leven

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	Simple Download Monitor
		Version: 3.6.9
		Author: Tips and Tricks HQ, Ruhul Amin, Josh Lobe

	Temporary Login Without Password
		Version: 1.5.12
		Author: StoreApps

	UpdraftPlus - Backup/Restore
		Version: 1.15.3
		Author: UpdraftPlus.Com, DavidAnderson

	WPDM - Dropbox Explorer
		Version: 1.2.0
		Author: Shaon

	WP Extra File Types
		Version: 0.4.1
		Author: Davide Airaghi

	WP Fastest Cache
		Version: 0.8.8.7
		Author: Emre Vona

== Debug ==
	Errors: 
		TypeError: this.search is undefined
			at https://tools4vegas.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.7 - 2:239282
			2018-10-31 02:30 +00:00

		TypeError: t is undefined
			at https://tools4vegas.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:159374
			2018-10-19 20:14 +00:00

		TypeError: this.search is undefined
			at https://tools4vegas.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:239282
			2018-10-19 19:46 +00:00

		TypeError: t.data.list_details is undefined
			at https://tools4vegas.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.0.10 - 2:23228
			2018-06-06 21:20 +00:00

		TypeError: o.attributes[t.name].each is not a function
			at https://tools4vegas.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.15 - 2:103926
			2018-06-06 02:14 +00:00
			x 4 times

		TypeError: t.data.list_details is undefined
			at https://tools4vegas.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.0.7 - 2:23228
			2018-05-31 03:05 +00:00

		TypeError: e is undefined
			at https://tools4vegas.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.14 - 2:212807
			2018-05-30 19:05 +00:00

		TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
			at https://tools4vegas.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.9.6 - 2:135814
			2018-03-08 23:25 +00:00

**Comment by bainternet** [comment]
@wwaag76 	

We can't replicate this issue, 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
