### ISSUE TITLE
Imported pages, posts data. But not showing elementor data

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#6202]
I have imported posts, pages to another site. 

But it doesn't call elementor edit data. **They are all text editor.**
Some of them are showing properly. But some of them are not showing like this. 
<br/>
![image](https://user-images.githubusercontent.com/5612050/48668181-a7baef80-eb2a-11e8-955b-e906631d8d80.png)
<br/>
<br/>
**This is the original page which should look like this.**
<br/>
![image](https://user-images.githubusercontent.com/5612050/48668190-ecdf2180-eb2a-11e8-9763-8d86ab959e45.png)

I had a look at database to compared posts ( these are actually pages) 
between showing properly page and not showing ( only show content. not elementor data) page.

post_id : 15237 is working properly
post_id : 15205 is only showing a edit widget and showing "post_content". not elelementor widgets.

This is the post meta 
![image](https://user-images.githubusercontent.com/5612050/48668292-fec1c400-eb2c-11e8-9dec-8bc9b8a4a2f0.png)

I don't see any different. I can't find any other data for these pages.

Did I miss something?

Does it related "post_content" in wp_posts table? I thought that you are using elementor_data instead of post_content. I also checked post_content. It looks not different and fine.

![image](https://user-images.githubusercontent.com/5612050/48668332-10f03200-eb2e-11e8-977e-50bc0960739b.png)

I use all up to date plugins, wordpress.  Elementor plugins are the best page builder in WordPress. However, it needs some features to import and export.. not like templates only. it takes super much time and messy in my templates.

Please have a look and help us. 

Thank you!

**Comment by bainternet** [comment]
@pulla 

Steps to replicate?

We made sure that even native WP export/import works correctly.

**Comment by pulla** [comment]
@bainternet 

I tried many plugins such as duplicate, clon plugins.  I know we don't really need as long as you have copy & paste feature.

I also tried bulk plugins and this one used "wp all import, wp all export" which I can pick up specific posts or pages. This feature is actually I need.
I have tested so many times.  so far, this is how it shows.

**Did I miss any fields in post-meta? or do I need to import any other tables, fields?**

Thank you for your great work and support!

**Comment by bainternet** [comment]
Well Elementor Saves its data in the post meta so make sure you import that as well. Other than that, I don't know what to tell you I just did a small test using [WP migrate DB](https://wordpress.org/plugins/wp-migrate-db/)

and it worked just fine, also the native WordPress Import export, same thing, all working just fine.
