### ISSUE TITLE
Populating select list with database values elementor pro.

### ISSUE THREAD

**Issue by udaysinhk** [pojome/elementor#6203]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by udaysinhk** [comment]
I am using elementor pro. Is it possible to run some custom PHP to populate a drop down list, based on the selection of the first value in another form field.  For example, If the user select US in the country field, we show New York, Houston. And if the user selects UK, we show the UK cities in the second dropdown (programmatically loading the cities from PHP, based on the country)

**Comment by bainternet** [comment]
@udaysinhk 

Not possible out of the box, only with some custom coding, especially if you want one dropdown to be based on the selection of another one which is done on the frontend and you want to run PHP so that means Ajax, so again, its only possible by custom code.

**Comment by udaysinhk** [comment]
Thank you I will give a try with ACF OR GF

**Comment by lupetalo** [comment]
any news on this?

**Comment by nashmiweb** [comment]
Any update on this?
