### ISSUE TITLE
Hitcounter Widget

### ISSUE THREAD

**Issue by MPHood** [pojome/elementor#6207]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Would be nice to have a Hit-Counter Widget in Elementor.  The widget should count the Visitors of a page and display the number in the frontend. A possible solution would be to integrate this functionality in to the actual Counter widget (an select visitos /pagevies or something like that) so that when a new user visits a Page or a post the Counter widget would show the number of pagehits for this specific post (animated like the counter widget already is). I hope you get what i mean.  PS-I added this as a feature Request- bit I cant see the label after its published

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by sherlanova** [comment]
Emmm... Does this ticket actually open? Need hit counter, like, badly? :D
