### ISSUE TITLE
Fixed background effect is ignored in Firefox

### ISSUE THREAD

**Issue by m0rphee** [pojome/elementor#6208]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I'm setting up images as fixed background on my website. They work fine in Chrome, Edge and opéra, but firefox shows the image as if on "scroll" setting.
See on this page : http://pixel-salad.com
On the first and second section, the image in the background is set on "fixed"

## Steps to reproduce

Just set a background image on a section, and put it on "fixed", then view it on firefox

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Wordpress : 4.8.9
Elementor Pro : 2.1.13
Firefox : 63.0.3
</details>

**Comment by bainternet** [comment]
@m0rphee 

You have custom CSS there, removed it and it works.
