### ISSUE TITLE
product select and category select in costume WP file structure 

### ISSUE THREAD

**Issue by AmmarAbuQoura** [pojome/elementor#6209]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

we install Elementor in a costume WordPress file structure (for security and our work flow we are not using the default file structure)

this tow line from the config file may explain that more 

define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/content' );
define( 'WP_CONTENT_URL', 'http://' . $_SERVER[ 'HTTP_HOST' ] .WP_FOLDER_NAME.'/content' );

our issue is when we trying to add a Product element we can't select any product in Select Product list with the following error in the console 

GET http://localhost/etloob/app/wp-json/ajaxselect2/v1/product_list/?ids=0 404 (Not Found)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

as for your problem described here, The get request is sent to `/wp-json/` and Elementor currently doesn't use `wp-json` at all so it must be coming from somewhere else and not from Elementor.
