### ISSUE TITLE
Widget with option to close

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#6210]
Hello guys,

You could provide a resource where the user could close a particular section/widget.

For example, I created a top banner, above the header, and attached to the browser window (https://screenshot.net/pt/0d59ouw). However, if you want to close this range, you do not have the option to do so.
So it could have a feature where I would put an option (button/image with an X in the corner) so the user could close the widget, especially on the cell phone where the widget would get in the way.

Here is the suggestion.

Appreciate.
Rodrigo Carlos

**Comment by bainternet** [comment]
@proddigital 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, this can only be done via custom coding.

Thanks for the feedback.
