### ISSUE TITLE
Media Attachment Page

### ISSUE THREAD

**Issue by Chris-La-Nauze** [pojome/elementor#6211]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
@Chris-La-Nauze 


You can already design your attachment pages, simply create a new Single template for Type Media.

**Comment by Chris-La-Nauze** [comment]
Great Show me a working example of this, any help docs, Because there is no working MEDIA archives page. I’ve copied all archive tags from the Elementor builder and put these on a single page with the media attachment, when I view media’s (attachment page) there are no images shown.

Kind regards,

Chris La Nauze
