### ISSUE TITLE
Checkboxes are display:inline instead of inline-block

### ISSUE THREAD

**Issue by tomas-eklund** [pojome/elementor#6216]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor applies a non-standard rule of `display: inline` to checkboxes. This makes Elementor forms incompatible with certain themes, such as OceanWP, which applies some custom styling to checkboxes. The result is that checkboxes disappear from screen, or are shown as thin vertical bars.

The user agent default CSS rule of Chrome, Firefox and Edge is `display: inline-block`. This is also the CSS rule for checkboxes of OceanWP. Furthermore it is the [W3C HTML 5.2 Recommendation](https://www.w3.org/TR/html5/rendering.html#the-input-element-as-a-checkbox-and-radio-button-widgets). 

## Possibly a regression

I believe this to be a regression, because a few months ago the site on which I discovered the problem looked fine. Now, suddenly the checkboxes are unusable. The site uses Elementor Pro and OceanWP and I believe updating either might have caused the problem. I have not yet had the time to investigate where and when the change was introduced.

## Steps to reproduce

Use the latest version of OceanWP (1.5.31) together with the latest version of Elementor Pro (2.2.0) and create a form with checkboxes. The checkboxes will appear as thin vertical bars instead of boxes. 

Alternatively use [Elementor Hello Theme](https://github.com/pojome/elementor-hello-theme) and create the following custom CSS for checkboxes:

```
input[type="checkbox"] {
  background-color: white;
  width: 30px;
  height: 30px;
  border: 1px solid black;
  -webkit-appearance: none;
}
```

Here's a live demo of the problem: 
http://www.elementor-demo.eu/bug-reports/checkboxes-that-disappear/

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

The bug happens when a theme tries to apply certain styling to checkboxes.

## Why I think the problem lies with Elementor and not the theme

The default CSS `display` rule for `input[type="checkbox"] `is `display: inline-block`. You can verify this by inspecting the User Agent style sheet of Firefox or Chrome, or by reading the [W3C Recommendation](https://www.w3.org/TR/html5/rendering.html#the-input-element-as-a-checkbox-and-radio-button-widgets). 

Elementor needs a good explanation for overriding this with the non-standard `display: inline`.

## Screenshot

![image](https://user-images.githubusercontent.com/1409791/48715275-e7f69c80-ec14-11e8-87ab-cda06a536856.png)

**Comment by tomas-eklund** [comment]
I have now checked a backup of the site, reinforcing my belief that this problem is due to a recent change in the CSS of elementor. 

**No problem** with frontend.min.css?ver=2.2.4
**Problem** with frontend.min.css?ver=2.3.2

The problematic CSS rule:

```
.elementor-field-type-acceptance .elementor-field-subgroup .elementor-field-option input, 
.elementor-field-type-acceptance .elementor-field-subgroup .elementor-field-option label, 
.elementor-field-type-checkbox .elementor-field-subgroup .elementor-field-option input, 
.elementor-field-type-checkbox .elementor-field-subgroup .elementor-field-option label, 
.elementor-field-type-radio .elementor-field-subgroup .elementor-field-option input, 
.elementor-field-type-radio .elementor-field-subgroup .elementor-field-option label {
    display: inline;
}
```

**Comment by bainternet** [comment]
@tomas-eklund 	

yep this is why,: https://github.com/pojome/elementor/issues/4295

thanks for reporting.

**Comment by tomas-eklund** [comment]
I see you closed the issue. Will the CSS be fixed? The way I read [parfilov's comment on #4295](https://github.com/pojome/elementor/issues/4295#issue-318728373) only the label needed to be inline, not the checkbox itself.

Please not that unless the CSS is fixed this bug breaks Elementor's compatibility with OceanWP, and possibly other themes.

**Comment by tomas-eklund** [comment]
Aw, come on now! This is a decently well-researched bug report. I've probably spent a good couple of hours testing, researching and making a demo page to illustrate the issue. It's pretty frustrating to see you dismiss it like this without even taking a minute to try and fully understand the problem. 

You've tried to solve another problem **[the wrong way](https://www.w3.org/TR/html5/rendering.html#the-input-element-as-a-checkbox-and-radio-button-widgets)** and introduced new and bigger problems. 

Check boxes are supposed to be `inline-block` according to the specs. All theme authors will rightfully assume they are. You can't just go and change that to `inline` in all Elementor installations around the world.

**Comment by LydiaLab** [comment]
Is there a resolution to this issue?? I would like to use the Elementor Pro Form with OceanWP and have the same issue. 
![screen shot 2019-02-08 at 12 51 34 pm](https://user-images.githubusercontent.com/26798478/52500234-80b10e80-2bab-11e9-8297-0365ede807a9.png)

**Comment by tomas-eklund** [comment]
@LydiaLab Great that you found the workaround. 

You could try to contact OceanWP and see if they will update their CSS, making sure that their CSS overrides that of Elementor.

**Comment by LydiaLab** [comment]
Ty for reaching out. As you know, there is an ongoing dialog between the two as too who should alter the code since Elementor is not following w3 standard on this one. My take is that if OceanWP changed there code it will poorly effect non-Elementor users who are complying with w3 standards — but I’m not an expert and would hate to be asked to get in the middle of this.





Lydia Latocki
Owner, Creative Director
lydia@lydialatocki.com
248-396-4552




Design for Marketing

**Comment by tomas-eklund** [comment]
@LydiaLab: I was not aware that there was an ongoing dialog between Elementor and OceanWP. Did Nicolas say so?

Honestly, I have difficulties believing there is a dialog between them considering how quick @bainternet was to adamantly dismiss and close this issue. I've been semi-active here on the Elementor Github tracker for a while now and my impression is that the Elementor team just don't seem to be open to discussion.

Also, OceanWP don't need to make big changes to their code. They just need to make sure that their CSS overrides that of Elementor, either by [specificity](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance#Specificity) or [loading order](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance#Source_order).

**Comment by bbdstar** [comment]
I have the same issue as well.

**Comment by invictusdm** [comment]
Same issue persists in Elementor 2.5.15 + OceanWP 1.6.7. Very annoying.

**Comment by mstudioIL** [comment]
It is still happening
using
`input[type="checkbox"] {
-webkit-appearance: checkbox;
}`
is not working, when this bug will be fixed?

**Comment by antongitnow** [comment]
Still experiencing this issue today.

**Comment by shynepo** [comment]
still there 

- [ ]

**Comment by Glen-Dango** [comment]
> Is there a resolution to this issue?? I would like to use the Elementor Pro Form with OceanWP and have the same issue. ![screen shot 2019-02-08 at 12 51 34 pm](https://user-images.githubusercontent.com/26798478/52500234-80b10e80-2bab-11e9-8297-0365ede807a9.png)
> 
> ```
> I found the work around by adding this custom CSS:
> .elementor-field-type-checkbox .elementor-field-subgroup .elementor-field-option input {
>     display: inline-block !important;
> }
> ```

this worked for me as well. using pop up in elementor with standard form. 2020 theme. absolute nightmare of a plugin.

**Comment by buckmanhands** [comment]
Same problem even when you use Hello Elementor theme. They truly could care less about anything besides $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
