### ISSUE TITLE
Agenda or schedule widget for conference sites

### ISSUE THREAD

**Issue by finid** [pojome/elementor#6219]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm begining to use Elementor to build sites for conferences and events, but there's no feature that can be used to add a conference agenda or schedule into a template.

**Describe the solution you'd like**
I'll like to have a widget that can be used to add a single-day or multi-day agenda to a template. So I drag a widget into a template, which adds a 3-tab element, each tab representing a day. In the Pro version, each tab will have a subtab for adding events in multiple rooms.

**Describe alternatives you've considered**
An example is [here](http://preview.themeforest.net/item/ventcamp-event-and-conference-theme/full_screen_preview/14637006?_ga=2.206583187.1072559170.1542649466-541992597.1542649466)

**Additional context**

**Comment by finid** [comment]
Used the accordion widget for a very simple agenda (here)[https://opportunityzonessuperconference.com]. I think a 3-panel tab might work better, so I'll give that a try.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
