### ISSUE TITLE
[Enhancement] Show element after certain time

### ISSUE THREAD

**Issue by icarolmelo** [pojome/elementor#622]
Hello,

Is there any plan to develop a hidden feature that appears based in a counter? 
(like hidden button that appears minutes after).

Elementor is a great tool, I'm very impressed

**Comment by arielk** [comment]
I'm not sure I understood, can you explain more about this feature? 

Link will be great

**Comment by icarolmelo** [comment]
Hi Ariel,


I found an example from other tool. Look this short vídeo that explains the feature

**Comment by icarolmelo** [comment]
Hi Ariel,

I found an example from other tool. Look this short vídeo that explains the feature
https://www.youtube.com/shared?ci=bCNFjrWCK-Y

**Comment by arielk** [comment]
Thanks for the sharing. It's really an interesting idea.

**Comment by icarolmelo** [comment]
You're welcome. It's so important for who works selling products using vídeo sales letter in affiliate market. 

Thanks for the attention

**Comment by bainternet** [comment]
I merged this issue with  #628, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by trendco** [comment]
Any news about "Show element after certain time"?
I need that feature also for a video with later button below.
Is there an easy way to solve this in advance with javascript?
