### ISSUE TITLE
Responsive color control styling issue still exists in latest Elementor version

### ISSUE THREAD

**Issue by pkvillanueva** [pojome/elementor#6227]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

As the title explains, here is the screenshot:

![2018-11-20 18 25 09](https://user-images.githubusercontent.com/4774295/48767420-adaefd00-ecf1-11e8-9614-2bab90ade683.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

[https://pastebin.com/APefwWuN](https://pastebin.com/APefwWuN)

**Comment by bainternet** [comment]
@pkvillanueva 	

Which widget is it? where can I see it?

**Comment by pkvillanueva** [comment]
@bainternet 

The screenshot given is from my personal custom widget that I was working on. Unfortunately, there's no similar widget case in Elementor and Elementor Pro that I could share to you. You can simply replicate this issue by adding this code to any widget.

```
$this->add_responsive_control(
	'responsive_color',
	[
		'label' => __( 'Color', 'elementor' ),
		'type' => 'color',
	]
);
```

**Comment by bainternet** [comment]
@pkvillanueva 

What you can do is add `'label_block' => true` to your control:

```PHP
$this->add_responsive_control(
	'responsive_color',
	[
		'label' => __( 'Color', 'elementor' ),
		'type' => 'color',
		'label_block' => true,
	]
);
```

And then with a little CSS:

```CSS
.elementor-control-responsive_color .elementor-control-input-wrapper {
    width: 100% !important;
}
```

You should get something like this:
![t0hp5p1](https://user-images.githubusercontent.com/660572/50075400-8c093e80-01e7-11e9-9a87-0ef163e7615b.png)
