### ISSUE TITLE
Background images not being offloaded to Jetpack / Photon

### ISSUE THREAD

**Issue by createandcode** [pojome/elementor#6229]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Any images added as background images in Elementor are not being offloaded to the Jetpack CDN servers. (Regular images are fine).

## Steps to reproduce
1. Clean WP install with just Jetpack and Elementor activated
2. Activate Photon
3. Add background image to an element in Elementor
4. Load page frontend - observe that the background image loaded via external Elementor CSS (default) references the site domain rather than the Jetpack CDN.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
That's because Photon looks inside the content for Images and not in the CSS.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
