### ISSUE TITLE
Any place where one can add a link - add a link accordion tab

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#623]
I added a Title and a link.

The title I selected a color for. When I added a link it changed to whatever default link color I am using.

It would be good to have a link section to any element where one can create a link. 
Where one can adjust the various link attributes.
As well as create whatever hover effect one wants to use.

Example...
In the title element this means an accordion named Link.
Link color:
Hover link color:
Hover link effects:
Visited Link color:
etc.

**Comment by arielk** [comment]
Dup #176 ?

**Comment by paaljoachim** [comment]
Hey Ariel

I think a stand alone Link section is needed perhaps under style along with whatever styling areas are in it. I noticed a lot of issues are "attached to 176" so I believe your devs just need to go through the various issues and see what would be natural to do.

**Comment by arielk** [comment]
We get a lot of ideas and I'm just trying to understand the issue better, so that we can arrange neatly issues.

Please take a look at this issue #534, I think it's the same

**Comment by paaljoachim** [comment]
My issue is a duplicate of 534. So I will close this so we can focus on 534 instead.
