### ISSUE TITLE
is elementor planning to have back-end editing? this is the only draw back I see. 

### ISSUE THREAD

**Issue by csceasyest** [pojome/elementor#6234]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
not anytime soon, no.

thanks.
