### ISSUE TITLE
Filtering Selector attribute of a control?

### ISSUE THREAD

**Issue by dtmgs** [pojome/elementor#6238]
Shortcode
==========				
	# Control 1
		$this->add_control( 'type', array(
			'type'    => Controls_Manager::SELECT,
			'label'   => __('Style', 'elementor'),
			'default' => 'type1',
			'options' => array(
				'type1' => __('Type 1', 'elementor'),
				'type2' => __('Type 2', 'elementor'),
			)
		) );

	# Control 2
		$this->add_control( 'color', array(
			'type'      => Controls_Manager::COLOR,
			'label'     => __('Color', 'elementor'),
			'default'   => '#000000',
			'selectors' => array(
				'{{WRAPPER}}** .sc-type1 span' => 'color:{{VALUE}}',
				'{{WRAPPER}}** .sc-type2 sup' => 'background-color:{{VALUE}}',
			) 
		) );

Here i've given the Structure of the shortcode i'm trying to add above, which results the output as following,

Output
=======

	type = type1
	<div class="sc-type1">
		<span> Text </span>
	</div>

	type = type 2
	<div class="sc-type2">
		<span> Text </span>
		<sup>sup</sup>
	</div>

If i use this shortcode to create an element( say eg: type1 element ), it will produce 2 lines of css ( for type1 and type2 ) as shown bellow.

post-10.css
===========
.elementor-10 .elementor-element.elementor-element-d3bf61b .sc-type1 span { color:#000000;}
.elementor-10 .elementor-element.elementor-element-d3bf61b .sc-type2 sup { background-color:#000000;}

Question
==
In the above example, i'm getting a grouped style results while adding any one of the 2 types, as i've defined 2 different selectors in the elementor control-2. So i would like to know that, 

**Is there any possibilities of filtering a selector attributes of control-2, based on the value of control-1?**

**Comment by bainternet** [comment]
@dtmgs 

you cant filter the Selectors, but you can use a 3rd control and utilize controls conditionally in order to include only the selector you want, ex:


```PHP
$this->add_control(
	'type',
	[
		'type'    => Controls_Manager::SELECT,
		'label'   => __( 'Style', 'elementor' ),
		'default' => 'type1',
		'options' => [
			'type1' => __( 'Type 1', 'elementor' ),
			'type2' => __( 'Type 2', 'elementor' ),
		],
	]
);

# Control 2
$this->add_control(
	'color_type1',
	[
		'type'      => Controls_Manager::COLOR,
		'label'     => __( 'Color', 'elementor' ),
		'selectors' => [
			'{{WRAPPER}}** .sc-type1 span' => 'color:{{VALUE}}',
		],
		'condition' => [
			'type' => 'type1',
		],
	]
);

# Control 3
$this->add_control(
	'color_type2',
	[
		'type'      => Controls_Manager::COLOR,
		'label'     => __( 'Color', 'elementor' ),
		'selectors' => [
			'{{WRAPPER}}** .sc-type2 sup' => 'background-color:{{VALUE}}',
		],
		'condition' => [
			'type' => 'type2',
		],
	]
);
```

Also don't set defaults beacuse they will always be used in the css.

**Comment by dtmgs** [comment]
:thumbsup:
