### ISSUE TITLE
more than 1 columns in img gallery

### ISSUE THREAD

**Issue by borisiceman** [pojome/elementor#624]
Problem with folowing. Theme [pluton](plutonwp.com/) At image gallery made by elementor (last ver) img placed only in one column.  No matter what number I made (2,3,4), they placed in 1 column in post 
Theme developer have no idea about issue, cause  theme have compatibility with Elementor.

**Comment by arielk** [comment]
Hi

I just tried Pluton theme and it looks great. Could you please add a link of your page with the gallery?

**Comment by borisiceman** [comment]
Link to [gallery ](http://pamjatnik78.ru/granitnye-pamyatniki-prostye/)

**Comment by arielk** [comment]
It looks like that has a custom code that comes from your theme (or other plugin) and disrupts the WP gallery layout, please contact their support with this issue.

**Comment by Chosebow** [comment]
Same problem! Solved by turning off some Total Theme modules.
