### ISSUE TITLE
Grouped controls within custom grouped controls

### ISSUE THREAD

**Issue by stianjaco** [pojome/elementor#6240]
There should be possible to add grouped controls within grouped controls.
I made this possible by adding the following to includes/controls/groups/base.php on line 124

```
elseif ( ! empty( $field_args['group_control'] ) ) {
    $group_type = $field_args['group_control'];
    unset( $field_args['group_control'] );
    $element->add_group_control( $group_type, $field_args, $options );
}
```

**Comment by bainternet** [comment]
@stianjaco 	

A change like this can have a major impact on many aspects of the editor and frontend rendering, and its currently not in our plans to implement that.

If your use case can't be handled differently, then you can always extend it your self.

thanks.

**Comment by stianjaco** [comment]
But the method is final, so it cannot be changed.
