### ISSUE TITLE
Manipulating multiple CSS values with the use of one SWITCHER Control's 'selectors' field.

### ISSUE THREAD

**Issue by iamzenigma** [pojome/elementor#6241]
Hi,

I've been looking around and I can't find anything concerning this topic. I've been working on a widget and I'm trying to create a SWITCHER-control that lets, _let's say_, sibling B 'inherit' values from the controls that belong to sibling A.

**A More In-Depth Sketch Of The Problem**
Sibling A is a container that holds its own CSS-properties and values which the user can define. For example the font size, width, height, padding etc. Now I want sibling B to be able to inherit these properties and values which are defined in A to make it more time-efficient for the user if he or she is planning to style both the same way.

Now I've almost made this work with the use of the 'selectors' key. There's just one problem. I'm able to copy over all the values from multiple controls by defining selectors in the SWITCHER-control, but if one of the values that I'm copying over is 'undefined' the whole 'selector-rule' isn't applied anymore.

**An Example Might Be A More Suitable Explainer**
I'll try to make it more clear by sharing code.

Here are two controls for sibling A:

```
$this->add_responsive_control(
    'a_alignment',
    [
        'label' => __( 'Alignment', 'your-text-domain' ),
        'type' => Controls_Manager::CHOOSE,
        'options' => [
            'left' => [
                'title' => __( 'Left', 'your-text-domain' ),
                'icon' => 'fa fa-align-left',
            ],
            'center' => [
                'title' => __( 'Center', 'your-text-domain' ),
                'icon' => 'fa fa-align-center',
            ],
            'right' => [
                'title' => __( 'Right', 'your-text-domain' ),
                'icon' => 'fa fa-align-right',
            ],
        ],
        'default' => 'center',
        'selectors' => [
            '{{WRAPPER}} .sibling-a' => 'text-align: {{VALUE}};',
        ],
    ]
);

$this->add_responsive_control(
    'a_spacing',
    [
        'label' => __( 'Spacing', 'your-text-domain' ),
        'type' => Controls_Manager::SLIDER,
        'range' => [
            'px' => [
                'min' => 0,
                'max' => 100,
            ],
        ],
        'selectors' => [
            '{{WRAPPER}} .sibling-a' => 'margin-bottom: {{SIZE}}{{UNIT}};',
        ],
    ]
);
```

These controls both manage a different CSS rule, but notice that they both point towards the same element. Also, they are both responsive controls, so for Sibling B to correctly inherit the values in the next step requires 6 CSS rules in total (for tablet 2x, mobile 2x and desktop 2x).

Here's the SWITCHER control for sibling B's inheritance.

```
$this->add_control(
    'b_inherits_a',
    [
        'label' => __( 'Inherit From Sibling A?', 'your-text-domain' ),
        'type' => Controls_Manager::SWITCHER,
        'default' => 'yes',
        'selectors' => [
            '(desktop){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment.VALUE}}; margin-bottom: {{a_spacing.SIZE}}{{a_spacing.UNIT}};',
            '(tablet){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment_tablet.VALUE}}; margin-bottom: {{a_spacing_tablet.SIZE}}{{a_spacing_tablet.UNIT}};',
            '(mobile){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment_mobile.VALUE}}; margin-bottom: {{a_spacing_mobile.SIZE}}{{a_spacing_mobile.UNIT}};',
        ]
    ]
);
```
So the problem arises when one of the values of sibling A's controls is undefined (corresponding to the device we're in). So if no value is given for the 'tablet alignment' of A, but a value for A's 'tablet spacing' is given, then B won't inherit the intended A's 'tablet spacing', because 'tablet alignment' causes an error in the syntax of the given CSS rule. (I assume the CSS rule looks something like this: 'text-align: UNDEFINED; margin-bottom: 199px;', but the whole CSS rule gets discarded for the error that arises.

**The question**
Is there a way to tackle multiple CSS rules on the same element in one selector?

Maybe it's a nice idea to allow an array as a value.

Like so:
```
'selectors' => [
    '(desktop){{WRAPPER}}` .sibling-b' => [
        'text-align: {{a_alignment.VALUE}};', 
        'margin-bottom: {{a_spacing.SIZE}}{{a_spacing.UNIT}};'
    ]
]
```

I hope this was somewhat comprehensible!

Thanks in advance.

**Comment by iamzenigma** [comment]
Hi again,

I've found a workaround for this. For anyone who bumps against the same issue, a solution is to let the individual controls of A (in my example: the controls with ID's 'a_spacing' and a_alignment' also manipulate sibling B's values. This lets the controls manipulate A and B's values. These controls are actually defining both siblings A and B, therefore for naming conventions it might be best to call them something like 'global_spacing' and 'global_alignment' now.  After you have done this create sibling B's controls: 'b_spacing' and 'b_alignment' after defining the now global controls. This way you could change the values individually if there's ask for this.

Now define a SWITCHER and for naming conventions name it something like 'b_style_unlock' and only show all of B's styling controls if this SWITCHER is set to yes.

To wrap things up, here's an example on how I made it work, continuing on the example I gave above.

```
//a_alignment became global_alignment
$this->add_responsive_control(
    'global_alignment',
    [
        'label' => __( 'Alignment', 'your-text-domain' ),
        'type' => Controls_Manager::CHOOSE,
        'options' => [
            'left' => [
                'title' => __( 'Left', 'your-text-domain' ),
                'icon' => 'fa fa-align-left',
            ],
            'center' => [
                'title' => __( 'Center', 'your-text-domain' ),
                'icon' => 'fa fa-align-center',
            ],
            'right' => [
                'title' => __( 'Right', 'your-text-domain' ),
                'icon' => 'fa fa-align-right',
            ],
        ],
        'default' => 'center',
        'selectors' => [
            '{{WRAPPER}} .sibling-a .caption, {{WRAPPER}} .sibling-b .caption' => 'text-align: {{VALUE}};',
        ],
    ]
);

//a_spacing became global_spacing
$this->add_responsive_control(
    'global_spacing',
    [
        'label' => __( 'Spacing', 'your-text-domain' ),
        'type' => Controls_Manager::SLIDER,
        'range' => [
            'px' => [
                'min' => 0,
                'max' => 100,
            ],
        ],
        'selectors' => [
            '{{WRAPPER}} .sibling-a .caption, {{WRAPPER}} .sibling-b .caption' => 'margin-bottom: {{SIZE}}{{UNIT}};',
        ],
    ]
);

//b_inherits_a became b_style_unlock
$this->add_control(
    'b_style_unlock',
    [
        'label' => __( 'Unlock Styling For B?', 'your-text-domain' ),
        'type' => Controls_Manager::SWITCHER,
        'default' => 'no',
    ]
);

// The controls for b will only be visible if the SWITCHER is turned on.

//this is the control for b alignment, as this is declared later on it will overwrite the global alignments value if a value is set.
$this->add_responsive_control(
    'b_alignment',
    [
        'label' => __( 'Alignment', 'your-text-domain' ),
        'type' => Controls_Manager::CHOOSE,
        'options' => [
            'left' => [
                'title' => __( 'Left', 'your-text-domain' ),
                'icon' => 'fa fa-align-left',
            ],
            'center' => [
                'title' => __( 'Center', 'your-text-domain' ),
                'icon' => 'fa fa-align-center',
            ],
            'right' => [
                'title' => __( 'Right', 'your-text-domain' ),
                'icon' => 'fa fa-align-right',
            ],
        ],
        'default' => 'center',
        'selectors' => [
            '{{WRAPPER}} .sibling-b .caption' => 'text-align: {{VALUE}};',
        ],
        'conditions' => [
            'b_style_unlock' => 'yes'
        ]
    ]
);

//the spacing for b.
$this->add_responsive_control(
    'b_spacing',
    [
        'label' => __( 'Spacing', 'your-text-domain' ),
        'type' => Controls_Manager::SLIDER,
        'range' => [
            'px' => [
                'min' => 0,
                'max' => 100,
            ],
        ],
        'selectors' => [
            '{{WRAPPER}} .sibling-b .caption' => 'margin-bottom: {{SIZE}}{{UNIT}};',
        ],
        'conditions' => [
            'b_style_unlock' => 'yes'
        ]
    ]
);
```

So I only had to change my approach. I feel quite stupid that I didn't come up with this earlier on, but yeah, my problem is solved. Though the only setback is that B now always inherits the values of A. In my case this was actually a +, but this might not be the case for others, therefore I'm leaving this issue open as I think that the problem I described above might be a potential feature or improvement in Elementor's infrastructure!

**Comment by bainternet** [comment]
@iamzenigma 	

A Workaround is a nice approach, But I'm happy to tell you that in the next version we have added a built-in way to overcome this by defining a fallback to the CSS value which can either by a static (hardcoded value) or a controls default value. So something like:

```PHP
$this->add_control(
	'b_inherits_a',
	[
		'label' => __( 'Inherit From Sibling A?', 'your-text-domain' ),
		'type' => Controls_Manager::SWITCHER,
		'default' => 'yes',
		'selectors' => [
			'(desktop){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment.VALUE || a_alignment.DEFAULT}};', //controls default value
			'(tablet){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment_tablet.VALUE || "center" }};', //hard coded value
			'(mobile){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment_mobile.VALUE || "left" }};',
		],
	]
);
```

The only limitation is that the `DEFAULT` token won't work for multiple value controls.

Thanks.

**Comment by iamzenigma** [comment]
That sounds like a great idea!

Thanks for taking the time to read and reply!

**Comment by dimative** [comment]
Hello.
Is this feature already added in Elementor latest version?
How can i get responsive default value?

```
$this->add_control(
	'b_inherits_a',
	[
		'label' => __( 'Inherit From Sibling A?', 'your-text-domain' ),
		'type' => Controls_Manager::SWITCHER,
		'default' => 'yes',
		'selectors' => [
			'(desktop){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment.VALUE || a_alignment.DEFAULT}};', //controls default value
			'(tablet){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment_tablet.VALUE || "center" }};', //hard coded value
			'(mobile){{WRAPPER}} .sibling-b' => 'text-align: {{a_alignment_mobile.VALUE || "left" }};',
		],
	]
);
```
in this example i can got default value. ```a_alignment.DEFAULT```
I don't know to can i get Mobile, Tablet value when i using responsive control?
Thanks.

**Comment by TheFirsh** [comment]
@dimative You can get tablet and mobile default values like this:
```
a_alignment_tablet.DEFAULT
a_alignment_mobile.DEFAULT
```
See more info about this topic at [selectors in Elementor](https://letswp.io/selectors-elementor-control-css-values/).

@iamzenigma Was [this](https://wordpress.org/support/topic/using-selectors-and-condition-in-a-repeater-control/) your thread? If so, I'd like to point you to [control conditions](https://letswp.io/conditional-controls-in-elementor-extensions/). If you now know more about conditions vs repeater, tell me so I can improve it.
