### ISSUE TITLE
Translate Single Page of elementor pro

### ISSUE THREAD

**Issue by jcmanso** [pojome/elementor#6245]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

We are making a web page in wordpress using elementor pro and wpml Multilingual CMS’s plugins, in Spanish and Portuguese, Spanish is the main language. The templates work perfectly for pages, sections, header and footer. But the templates for individual type in different instances (single post template) does not work in Portuguese. If I translate those templates they appear empty, without any element. The Portuguese post entries are seen without any style. If I edit the template in Portuguese, it is theoretically saved, but it does not have any content. The template is completely empty. If I make changes to the Portuguese templates of pages, sections, headers, footers... they are saved and work. The problem is only with individual templates. 

## Steps to reproduce

In the description section

## Isolating the problem
- [ ] Single page translator doesn't work for elementor

## Environment

Las version of elementor pro

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* Isolating the problem.
* System info.

As for what we can understand for the information you did provide, we can't really help as Elementor has nothing to do with translations or how they are handled.

thanks.
