### ISSUE TITLE
Override Elementor Canvas Template

### ISSUE THREAD

**Issue by nnnswordfish** [pojome/elementor#6246]
I'm a PRO user. Asked support for help and they redirected me here.

Is there any way to override the Elementor Canvas template content with a built-in hook? I want to display my custom(let's say static) content instead of Post/Page content which comes from the content editor. I'm pretty sure that there is a hook but can't find it in anywhere so far.

Thanks!

**Comment by bainternet** [comment]
@nnnswordfish 

You can using the native WordPress Hooks. Elementor uses `template_include` filter hook to return the path of the canvas template at the priority 11 so anything after that would work, ex:

```PHP
add_filter( 'template_include', function( $template ) {
	if ( false !== strpos( $template, '/templates/canvas.php' ) ) {
		// this is where you can override it
		$template = 'YOUR_CUSTOM_TEMPLATE.PHP';
	}
	return $template;
}, 12 );
```
