### ISSUE TITLE
Show ACF fields as a list with bullets

### ISSUE THREAD

**Issue by rvlak** [pojome/elementor#6249]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In a Single Post template, I would like to dynamically display several ACF fields as a list with bullets. However, with Elementorr I can only display them as regular paragraphs, not as a <ul> list. 

**Describe the solution you'd like**
A widget that allows for dynamic listing the contents either from native WP fields or ACF fields as an unordered list (bullets)

**Describe alternatives you've considered**
Wrapping HTML around widgets (which does not work), or programming the template with PHP (but that is not an option for me).

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


for now, I can only suggest you create a shortcode that will create that list for you out of the ACF fields and insert it to the template either via shortcode widget or shortcode dynamic tag. 

Thanks for the feedback.

**Comment by mattiebrownoz** [comment]
Got it, thank you.   
  
  
  

  
  

  
  
>

**Comment by kaelhoel** [comment]
I'm very interested in having this feature as well.

**Comment by JeremyCarlsten** [comment]
Also interested

**Comment by josephki** [comment]
I need it. Pronto!
