### ISSUE TITLE
Custom widgets with Elementor Fields.

### ISSUE THREAD

**Issue by rahulnever2far** [pojome/elementor#625]
I'm a theme author. I came across Elementor today and I already knew I want to Build my next using it.

I went through the documention, it is mentioned that all widgets (even the custom ones) show up in the Page Builder. My question is, would it possible to code a custom widget utilizing the fields and panels used in the Elementor?

PS: Thank you so much for developing lighting fast page builder. It so much better than other options, even the paid ones. Keep it up 👍

**Comment by joshmarom** [comment]
Hi @rahulnever2far.
Thank you for your kind feedback.
Your question has been asked before (#26), along with a bunch of other [Developer API](https://github.com/pojome/elementor/labels/developer%20api) related issues.
We are working on the API and hopefully it will be released in a couple of months.
