### ISSUE TITLE
Disable theme builder

### ISSUE THREAD

**Issue by franzarmas** [pojome/elementor#6250]
Hi, I wanted to know if there is any elementor hook (filter) that allows to disable the Theme Builer options .. that is, it does not allow to create templates such as Header, Footer, Archive, etc ...

Only sections or pages like before version 2.0 ... I think that not all of us need those options, so disabling would be a great saving of resources on the part of the server when not loading php code.

In case that filter does not exist, please request that you add it since it would be very useful.

Thanks, I'm listening.

**Comment by bainternet** [comment]
@franzarmas 	


There is no way to "disable" it, its the same mechanism that drives the page and section templates. If its performance you are worried about, then simply don't use it and it will not be invoked.

thanks.
