### ISSUE TITLE
Multiple dynamic image galleries on page combined in the lightbox

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#6252]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have a loop which shows posts using an Elementor template.

In this template i use the "Image Gallery widget" and for the content i use Dyanmic -> attachments of current post.

That works great. in my page i see each post with this template structure and inside it the image gallery showing the attachments of that post.

When i click an image in that gallery the lightbox pop up and show the image (Full size).

That's all great!

**The problem is:**
If i use the lightbox navigation arrows it should cycle through all the images attached to this post, but instead it cycles through the attachments of all the posts!

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.

**Comment by bentalgad** [comment]
I guess this problem has to do with the fact all images get the same value for the "data-elementor-lightbox-slideshow" attribute (in there lightbox warrper div).

**Comment by bainternet** [comment]
@bentalgad 	

If I understand correctly you are looping over the posts with a template via a `do_shortcode` of Elementor template shortcode? if that is it, paste your loop, I might have a solution for you using the new Lightbox Dynamic tag.

**Comment by bentalgad** [comment]
correct.

`while ( have_posts() ) { the_post();

// Show post
echo '<div class="proCard">'.do_shortcode('[elementor-template id="300"]').'</div>';

} // End of while Post`

**Comment by bentalgad** [comment]
Btw - could be related to this issue:  #5253 ?

**Comment by bainternet** [comment]
[**@bentalgad**](https://github.com/bentalgad) commented on [Nov 23, 2018, 11:38 AM GMT+2](https://github.com/pojome/elementor/issues/6252#issuecomment-441193249 "2018-11-23T09:38:48Z - Replied by Github Reply Comments"):
> I guess this problem has to do with the fact all images get the same value for the "data-elementor-lightbox-slideshow" attribute (in there lightbox warrper div).

This is correct because the ID of the widget form the template is printed over and over but never changes. we could change the ID to something unique each print like `time()`

but for now you can try to replace it for each iteration of your loop: 
```PHP
global $post;
while ( have_posts() ) {
	the_post();
	// Show post
	$card = '<div class="proCard">' . do_shortcode( '[elementor-template id="300"]' ) . '</div>';
	$pattern = '/data-elementor-lightbox-slideshow=\\"(.*)\\"/';
	$replacement = 'data-elementor-lightbox-slideshow="gallery-' . $post->ID . '"';
	echo preg_replace( $pattern, $replacement, $card, -1 );
} // End of while Post
```

**Comment by bentalgad** [comment]
Wow, great idea! didn't even think that road...

For some reason it removes the images and leaves only the link warper (`<a data-elementor-open-lightbox="default" data-elementor-lightbox-slideshow="gallery-1561" role="link"></a>`), but i guess that's just refining... ill try to fix it.

Thanks you very much!

**Comment by bentalgad** [comment]
can't get it to work. the image is removed and the href attribute is removed from the wrapper link. i can't understand why.

**Comment by bainternet** [comment]
@bentalgad 

The regex pattern was incorrect, try this:

```PHP
global $post;
while ( have_posts() ) {
	the_post();
	// Show post
	$card = '<div class="proCard">' . do_shortcode( '[elementor-template id="300"]' ) . '</div>';
	$pattern = '/data-elementor-lightbox-slideshow="([^"]*)"/';
	$replacement = 'data-elementor-lightbox-slideshow="gallery-' . $post->ID . '"';
	echo preg_replace( $pattern, $replacement, $card, -1 );
} // End of while Post
```

**Comment by bentalgad** [comment]
Wow, thanks that works great! (embarrassed to say i used jQuery meanwhile)

**Comment by bentalgad** [comment]
@bainternet Is this hack still needed or was it fixed in some version?

Thanks!

**Comment by bentalgad** [comment]
I see it is still needed. will it be fixed in the future?

**Comment by JeffPlo** [comment]
I extended the Widget_Image_Gallery and Widget_Image_Carousel in my Theme.
Carousel as example:

`namespace WidgetImageCarousel;

use Elementor\Widget_Image_Carousel;

class WidgetImageCarousel extends Widget_Image_Carousel {

    private $newUniqueID;

    public function get_id() {
        if ( !isset( $this->newUniqueID ) ) {
            $this->newUniqueID = uniqid();
        }

        return parent::get_id() .' '. $this->newUniqueID;
    }

}`

**Comment by hirenshah** [comment]
@bentalgad - Any chance you can provide more information on how you actually achieved this please?

**Comment by bentalgad** [comment]
I'm really sorry, it's been a while and this project is not using Elementor anymore (because of the lack of some basic features in Elementor that need's to be added with complicated code which is missing the point of using a page builder which is suppose to make to work easier and not harder) so i don't really remember or have a way to see the code to tell you how it's been done.

**Comment by blaue-mango** [comment]
Here's a jquery snippet to fix this behaviour. Make sure you're loading this after the gallery has loaded (make sure your custom JS is loaded after Elementor's).

What this basically does, it increments the attribute on the lightbox link for each gallery.

```javascript

// mbc Only show the lightbox items corresponding to the currently clicked gallery

jQuery(function ($) {
    $(document).ready(function ($) {
        
        // set incrementing counter:
        var i = 0;
        // loop through the galleries:
        $('.e-gallery-container').each(function () {

            // get the current id of the lightbox gallery link
            var oldAttrLightbox = $(this).find('a').attr('data-elementor-lightbox-slideshow');

            // add the incrementing number to it:
            var newAttrLightbox = oldAttrLightbox + i;

            // replace the old gallery link attr with the new one generated above
            $(this).find('a').attr('data-elementor-lightbox-slideshow', newAttrLightbox);
            
            // increment the counter
            i = i + 1;

        })
    })
});
```

**Comment by maudic** [comment]
Hi guys, see if you can help me!
I use Elementor Pro as the OceanWP theme.
I have buttons on a page, where each one displays a jpg image. When I click this button, the image is displayed through the lightbox.
So far everything is working fine. However, some buttons must display an image gallery (2 to 6). So, I created a pop-up with the Media Carousel Widget, but when I click the button, the first image is displayed, but in a different format. Only after clicking on this image the lightbox format is displayed.
How to fix this? Thanks!

**Comment by Fabioxpto** [comment]
> Here's a jquery snippet to fix this behaviour. Make sure you're loading this after the gallery has loaded (make sure your custom JS is loaded after Elementor's).
> 
> What this basically does, it increments the attribute on the lightbox link for each gallery.
> 
> ```js
> // mbc Only show the lightbox items corresponding to the currently clicked gallery
> 
> jQuery(function ($) {
>     $(document).ready(function ($) {
>         
>         // set incrementing counter:
>         var i = 0;
>         // loop through the galleries:
>         $('.e-gallery-container').each(function () {
> 
>             // get the current id of the lightbox gallery link
>             var oldAttrLightbox = $(this).find('a').attr('data-elementor-lightbox-slideshow');
> 
>             // add the incrementing number to it:
>             var newAttrLightbox = oldAttrLightbox + i;
> 
>             // replace the old gallery link attr with the new one generated above
>             $(this).find('a').attr('data-elementor-lightbox-slideshow', newAttrLightbox);
>             
>             // increment the counter
>             i = i + 1;
> 
>         })
>     })
> });
> ```

@blaue-mango how i can add you jquery snippet?
Sorry, im newbie. I try to add this code on Plugin called "Snippets" and give me error 
**"The code snippet you are trying to save produced a fatal error on line 3:
syntax error, unexpected '$', expecting variable (T_VARIABLE)"**
You can help me pls?

**Comment by sercanvirlan** [comment]
Thanks!

**Comment by kennymcnett** [comment]
**Thank you @blaue-mango !!!**


### Target update (June 9, 2022)
I updated the target selector from **.e-gallery-container** to **.elementor-image-carousel-wrapper** and the solution from @blaue-mango worked perfectly.

### Where to put it
If you're not sure how to add this to your theme files, then you can also...

1. Go to Elementor > Custom Code
2. Add New
3. From the Location dropdown, select </body> - End
4. Copy/paste the code below
5. Publish

_Note:_ The code below is wrapped in a <script></script> tag for the purpose of using it inside the Elementor custom code section. 

### Final answer (as of 6/9/2022):

```
<script>
jQuery(document).ready(function ($) {
  
	//Limit carousel lightboxes to opening only the images within the carousel (instead of all the carousels on the page)
	
	// set incrementing counter:
	var i = 0;
	// loop through the galleries:
	$('.elementor-image-carousel-wrapper').each(function () {

		// get the current id of the lightbox gallery link
		var oldAttrLightbox = $(this).find('a').attr('data-elementor-lightbox-slideshow');

		// add the incrementing number to it:
		var newAttrLightbox = oldAttrLightbox + i;

		// replace the old gallery link attr with the new one generated above
		$(this).find('a').attr('data-elementor-lightbox-slideshow', newAttrLightbox);

		// increment the counter
		i = i + 1;

	})
	
});
</script>
```

**Comment by mikeecho2** [comment]
Awesome, thanks, it worked. Too bad ELEMENTOR seems to not care much about this issue

**Comment by theavic** [comment]
Is this issue going to be fixed?

**Comment by DanReising** [comment]
> **Thank you [@blaue-mango](https://github.com/blaue-mango) !!!**
> ### Target update (June 9, 2022)
> 
> I updated the target selector from **.e-gallery-container** to **.elementor-image-carousel-wrapper** and the solution from [@blaue-mango](https://github.com/blaue-mango) worked perfectly.
> ### Where to put it
> 
> If you're not sure how to add this to your theme files, then you can also...
> 
>     1. Go to Elementor > Custom Code
> 
>     2. Add New
> 
>     3. From the Location dropdown, select  - End
> 
>     4. Copy/paste the code below
> 
>     5. Publish
> 
> 
> _Note:_ The code below is wrapped in a <script></script> tag for the purpose of using it inside the Elementor custom code section.
> ### Final answer (as of 6/9/2022):
> 
> ```
> <script>
> jQuery(document).ready(function ($) {
>   
> 	//Limit carousel lightboxes to opening only the images within the carousel (instead of all the carousels on the page)
> 	
> 	// set incrementing counter:
> 	var i = 0;
> 	// loop through the galleries:
> 	$('.elementor-image-carousel-wrapper').each(function () {
> 
> 		// get the current id of the lightbox gallery link
> 		var oldAttrLightbox = $(this).find('a').attr('data-elementor-lightbox-slideshow');
> 
> 		// add the incrementing number to it:
> 		var newAttrLightbox = oldAttrLightbox + i;
> 
> 		// replace the old gallery link attr with the new one generated above
> 		$(this).find('a').attr('data-elementor-lightbox-slideshow', newAttrLightbox);
> 
> 		// increment the counter
> 		i = i + 1;
> 
> 	})
> 	
> });
> </script>
> ```

Hey Kenny, not sure if you will see this as I realize it's old. I'm facing this same issue, even with Elementor fully updated. I posted this as a custom code per above but the behavior persists on certain pages. It defintely worked in specific areas but not in others. Very strange behavior with Lightbox in general and I'm having trouble trying to pin down what's actually happening. Was there a determination that this was a bug with Elementor? A conflict between plugins or themes? What is actually causing this to happen where it was not an issue in the past? 

Dan

**Comment by kennymcnett** [comment]
@DanReising Definitely a bug, but I'm not sure if the Elementor team squashed it. I haven't tested it recently. If you read up higher in the thread you'll see discussion about the IDs getting repeated, which is output from Elementor. You could try re-opening this issue or submitting a new one if it's persisting for you. Be sure to test on a clean install to rule out plugin conflicts.
