### ISSUE TITLE
Reload widget when I change color

### ISSUE THREAD

**Issue by wayheming** [pojome/elementor#6253]
Hello, how can I start reloading a widget when I change color with color picker as with any other action?
The problem is that in my widget the widget's class depends on whether the color is specified.
And without reloading the widget, the editor displays an incorrect style.

**Comment by bainternet** [comment]
@wayheming 	

paste your code, I'll try to help you.

**Comment by wayheming** [comment]
Hello! Thanks for the answer. I don’t know what kind of code I should show you, but I think that this will make it clear.

Map part.
```
$this->add_control(
	'icon_color',
	[
		'label'     => esc_html__( 'Icon color', 'theme' ),
		'type'      => Controls_Manager::COLOR,
		'scheme'    => [
			'type'  => Scheme_Color::get_type(),
			'value' => Scheme_Color::COLOR_1,
		],
		'selectors' => [
			'{{WRAPPER}} .box-icon' => 'color: {{VALUE}}',
		]
	]
);
```

Render part
```
$settings = $this->get_settings_for_display();

if ( $settings['icon_color'] ) {
	$icon_classes = ' with-color';
}

<div class="box-icon<?php echo esc_attr( $icon_classes ); ?>"></div>
```

**Comment by wayheming** [comment]
up👍

**Comment by wayheming** [comment]
@bainternet Hello, can you help me?

**Comment by ArekZw** [comment]
I need it too

**Comment by bainternet** [comment]
@wayheming 	

In that case, you can add `render_type` parameter to your control and set it to `template` which in turn will for a re-render of the widget and as long as you don't have a `_content_template` method in your widget it will render form the PHP `render` method of the widget so in your case it will should be: 

```PHP
$this->add_control(
	'icon_color',
	[
		'label'     => esc_html__( 'Icon color', 'theme' ),
		'type'      => Controls_Manager::COLOR,
		'scheme'    => [
			'type'  => Scheme_Color::get_type(),
			'value' => Scheme_Color::COLOR_1,
		],
		'selectors' => [
			'{{WRAPPER}} .box-icon' => 'color: {{VALUE}}',
		],
		'render_type' => 'template',
	]
);
```

**Comment by wayheming** [comment]
@bainternet Thank you!
