### ISSUE TITLE
ACF support for Grouped Fields

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#6254]
It would be cool to allow using grouped fields in ACF.

I understand, it may be complex to allow Elementor use repeater fields or flexible fields.

But grouped fields are just unique fields located in a group. It's mostly a feature that's used to enhance the UI of the post edit screen.

But, nowadays, using ACF 5.7.7 and Elementor Pro 2.2.0, fields inside a group doesn't appear in Elementor.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
