### ISSUE TITLE
nav menu vidget

### ISSUE THREAD

**Issue by MaraRita** [pojome/elementor#6256]
Hi,
I want the sub menu to fold/unfold if I click on the indicator (mobile version). Now it just unfold. Tried to do the custom code but js event to unfolding the sub menu linked to the block (the link takes the whole block and not only text). Can it be fixed of can I do something else to make it fold? Thanks in advance! 
![image](https://user-images.githubusercontent.com/42947847/48960906-ac7f0980-ef57-11e8-9db9-4e416d9f65b0.png)
![image](https://user-images.githubusercontent.com/42947847/48960917-db957b00-ef57-11e8-8bec-f4c90514f36f.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.


Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
