### ISSUE TITLE
Check if page built with Elementor without checking meta

### ISSUE THREAD

**Issue by DeoThemes** [pojome/elementor#6257]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I can't pass ThemeForest review because of one issue. To check if the page is built with Elementor I use **if** condition to check Elementor post meta. The problem is that reviewer activated Elementor and clicked Edit With Elementor (so the meta created). After this, without any changes he got back to default page editor and clicked **View Page**. Then the page looks like this - https://envato.d.pr/K8D2nY

To give more flexibility to the customers I don't wrap Elementor content with container, so people can utilize Elementor grid system with full-width or container page layouts.

Is there any other way to get around this issue? Maybe some other way to check if page was created with Elementor?

**Code reference:**
```
<?php
        // Check if the page built with Elementor
        $elementor_page = get_post_meta( get_the_ID(), '_elementor_edit_mode', true );

        if ( (bool)$elementor_page ) : ?>
            <div class="main-content">
                <?php the_content(); ?>
            </div>
        <?php else : ?>
            <section class="section-wrap pb-40">
                <div class="container">
                        <?php the_content(); ?>
                </div>
            </section>
    <?php endif; ?>
```

**Comment by bainternet** [comment]
@DeoThemes 	

If he clicks on the "Edit With Elementor" the meta is saved, what he does with it after that doesn't matter as long as he doesn't click the "back to WordPress editor" the meta will still exist.

Now if you want to fully support Elementor and its locations API take a look at this: https://developers.elementor.com/theme-locations-api/

**Comment by DeoThemes** [comment]
My issue is that the meta still exists after he clicks the "back to WordPress editor". If he doesn't save the post after this, the meta is still there and layout is broken. I can't find another way around it, because the only way is to test post meta with this condition.
