### ISSUE TITLE
Keyboard shorcut to open finder result in new tab

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#6258]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I think it would be great if pressing cmd + ENTER or ctrl+ENTER (Is it? in pc) would open a finder result link in a new tab.

**Comment by bainternet** [comment]
@bentalgad 	

The finder provides links, so you can use the browser's native shortcuts to open in anew tab, for example in chrome it's (Crtl/CMD + Left Click).


But we will look at adding (Crtl/CMD + ENTER).


thanks.

**Comment by bentalgad** [comment]
Yes i know that. but when you use regular web links you usually use your mouse alone, but when you use finder you use your keyboard to write what you search for and it's very ui logically to be able to end the process with the keyboard.

**Comment by bentalgad** [comment]
Great! Thanks! will it work also with cmd on mac?

**Comment by bentalgad** [comment]
I updated just now works great on mac! Thanks you very much! this will make work even more easy! This finder add-on is just the best! Thank you very much! you are the best!
