### ISSUE TITLE
Css rotation (feature request)

### ISSUE THREAD

**Issue by MPHood** [pojome/elementor#6259]
Would be nice if you could add rotation to the "Advanced" settings of widgets/columns/sections . 

Could be something like an Input field (or range bar from -360 to 360 degree, right under the margin/padding fields.

I know that is easy with custom css. But it would be a Timesaver.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
