### ISSUE TITLE
The same query settings in Sitemap widget as in Posts widget

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#6262]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Feature request**
Some situations we need to make a page like "Begin here" or something like this, where we can write about project and place lists of relevant posts and pages. It's almost the same that sitemap, but more advanced.
The best examples of this case are:
https://cheeseweb.eu/start-here/
https://michaelhyatt.com/about/
https://planningwithkids.com/2010/04/08/getting-organised-at-home/

**What do I need to customize query**
- Select by: author, category, tag, format
- Manual selection (even more important than previous)

**Alternatives**
Of course, we can use the Posts widget instead, but the Sitemap is more simple and don't need to disable image, excerpt and meta.

What do you think?

**Comment by bainternet** [comment]
@parfilov 	

Thanks for the suggestion, we might consider it if we see a large demand for it.

For now, you can simply create a custom posts skin that will only display the data you want, ex:
![image](https://user-images.githubusercontent.com/660572/48978485-b8cca900-f0b4-11e8-92ac-0ae0d4790860.png)

```PHP
add_action( 'elementor/widget/posts/skins_init', function( $widget ) {

	class My_Sitemap_Posts_Skin extends \ElementorPro\Modules\Posts\Skins\Skin_Base {
		public function get_id() {
			return 'sitemap-skin';
		}
		public function get_title() {
			return __( 'SiteMap Skin' );
		}

		//remove thumbnail controls
		protected function register_thumbnail_controls() {}
		// remove excerpt controls
		protected function register_excerpt_controls() {}
		// remove read more controls
		protected function register_read_more_controls() {}
		//remove meta data controls
		protected function register_meta_data_controls() {}

		// Set container tag to UL instead of div
		protected function render_loop_header() {
			$this->parent->add_render_attribute( 'container', [
				'class' => [
					'elementor-posts-container',
					'elementor-posts',
					'elementor-grid',
					$this->get_container_class(),
				],
			] );
			?>
			<ul <?php echo $this->parent->get_render_attribute_string( 'container' ); ?>>
			<?php
		}

		// Set container tag to UL instead of div
		protected function render_loop_footer() {
			?>
			</ul>
			<?php
		}

		// Print only what we need for each post
		protected function render_post() {
			?>
			<li class="elementor-post__text">
				<?php $tag = $this->get_instance_value( 'title_tag' ); ?>
				<<?php echo $tag; ?> class="elementor-post__title">
					<a href="<?php echo get_permalink(); ?>">
						<?php the_title(); ?>
					</a>
				</<?php echo $tag; ?>>
			</li>
			<?php
		}
	}

    // register the skin to the posts widget
	$widget->add_skin( new My_Sitemap_Posts_Skin( $widget ) );
} );
```

**Comment by reelism** [comment]
@bainternet thanks for this, but there's no styling options in 'content'?
