### ISSUE TITLE
Sendy Integration

### ISSUE THREAD

**Issue by jmcst24** [pojome/elementor#6266]
I am interested in Pro Forms Integration with Sendy.  This is something I would be very interested in having as a standard. 

I am trying the following code - but when changing function.php file it crashes site.  I am thinking I am in the wrong file.  What file should I be changing and can I control this based on different forms?

```PHP
 /** Sendy Submit **/

add_action( 'elementor_pro/forms/new_record', function( $record, $this ) {
	$fields = [
              'email' => $record->fields['email'],
              'list' => LIST_ID_HERE,
              'name' => $record->fields['name'],
	      'message' => $record->fields['message']
        ];
	
	wp_remote_post( 'https://mydomain.com/sendy/subscribe', [
		'body' => $fields
	]);
});
```

**Comment by bainternet** [comment]
Looking at this code, functions.php should be just fine just make sure you replace `LIST_ID_HERE` with your actual list ID.

**Comment by jmcst24** [comment]
Thanks, it is causing my site to not load.  I did change the list ID and the url.  I added it to the ASTRA theme functions.php file and restarted apache. I tried it in different places and also through there was an extra comma after the last variable - but still no luck.

**Comment by jmcst24** [comment]
I found it to be a problem with $this - PHP 7.1 is throwing a fatal error - how can this be changed to work in 7.1?

**Comment by bainternet** [comment]
This code should work on php 5.4-7.4 so it's probably  not an issue with php 7.1.

Check your error log and see what is the Fatal error .

**Comment by jmcst24** [comment]
Here is the error message from apache log: 

'PHP message: PHP Fatal error:  Cannot use $this as parameter in /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/astra/functions.php on line 141\n'

Here is the line 
add_action( 'elementor_pro/forms/new_record', function( $record, **_$this_** ) {

**Comment by JoseSoteloCohen** [comment]
Hello guys!

This plugin should help you with sending submissions from Elementor Form to your Sendy lists.

https://wordpress.org/plugins/inboundlatino-sendy-elements/

**Comment by jmcst24** [comment]
Thanks.
