### ISSUE TITLE
Content template function

### ISSUE THREAD

**Issue by batnyam** [pojome/elementor#6267]
Can I using WP_Query in content template function of custom Widget. I wish to display queried posts on elementor editor.

**Comment by bainternet** [comment]
@batnyam 

You have to options, either using only `render()` method with no `_content_template()` method in your widget class. Or you can write a custom JavaScript handler to load the posts via AJAX in for your `_content_template()`.

**Comment by eece** [comment]
hi @bainternet , my scenario is same with @batnyam . What is the aim of usage to _content_template() if render() method is doing all job? I removed the _content_template() and all things is working well which I except.
