### ISSUE TITLE
How to store dynamically created elements in elementor.

### ISSUE THREAD

**Issue by asoni7039** [pojome/elementor#6268]
![01](https://user-images.githubusercontent.com/39119567/48997527-4c19e300-f176-11e8-82bc-eaf43eb81523.jpg)

Hello There, I am trying to develop a widget for elementor. It is an image pointer. I am attaching an image for example. These pointers on image are basically div's , which are added dynamically wherever user clicks. I am able to add these div's on the frontend. How can i store these div's from frontend to the backend of elementor.
So that it permanently gets stored and does not get lost on page refresh.

This is the screenshot url :-  https://prnt.sc/lmzaz6

**Comment by bainternet** [comment]
Have a look at our docs and see how to create a widget and add controls( which save and manage the data ) to it.

https://developers.elementor.com/

**Comment by asoni7039** [comment]
Thanks @bainternet for responding. I know all the basic stuff. I just want to know if  i add an element on any event from jquery in frontend, how can i store it to the backend in elementor. So that it stays permanently and remains there even after page refresh.
