### ISSUE TITLE
Lightbox on Text

### ISSUE THREAD

**Issue by Laneida** [pojome/elementor#6269]
Hi Elementor Team!

We work with the elementor wordpress plugin for quite some time and are very pleased with it. 
Besides small bugfixing all the time. :-)

I think we found a problem with the lightbox widget:
We tried to apply the elementor lightbox to a simple text. 
But the widget applies it only to an image. 
I am sure there is a way around this, but it would need us some time to code our way around it for every single project / customer. So we would rather prevend this.

Will there be a solution for this widget soon? 
So we could be able to use the lightbox widget for multiple customer requests.

Your sincerely,
Dany and Birgit

(english is not our first language and we are not sure if there is another request poll for this issue - we have limited time for research at work)

**Comment by bainternet** [comment]
Elementor's Lightbox works out of the box for 4 content types:

* Image:
```JS
elementorFrontend.utils.lightbox.showModal( {
	type: 'image', 
	url: 'https://example.com/image-file.jpg'
} );
```

* Video:
```JS
elementorFrontend.utils.lightbox.showModal( {
	type: 'video', 
	url: 'https://www.youtube.com/watch?v=cyVivu365wg',
	videoType: 'youtube',
} );
```

* Slideshow:
```JS
elementorFrontend.utils.lightbox.showModal( {
	type: 'slideshow', 
	slideshow: {
		slides: [
			{
				image: 'https://example.com/image-file.jpg',
				index: 0,
			},
				{
				image: 'https://example.com/image-file2.jpg',
				index: 1,
			},
		],
	},
} );
```

* HTML Content:
```JS
var HTMLContent = '<h1>Hello Lightbox</h1>';
elementorFrontend.utils.lightbox.showModal( {
	'html': HTMLContent, 
} );
```

**Comment by Laneida** [comment]
Hi there! 

Thank you for your reply. 
I am sure it would be very useful.

But thanks to my limited english language skills you misunderstood. Sorry for that!

We want it the other way around.
Basically: There is a textlink (styled as button for ex) onclick it will open a video in the lightbox.
In the widget tool, we can only add a static picture as button.

Or do you mean we should write our own function with js?
Applying the Video script for ex.

Cheers!
Dany

**Comment by bainternet** [comment]
In that case, in Elementor pro v2.2.0 we added a  lightbox dynamic tag that let's you open a lightbox from any link control in Elementor, like button.

Thanks.

**Comment by Laneida** [comment]
Thanks to you too.

Cheers!
Dany

**Comment by Dkogan90** [comment]
@bainternet 
For the lightbox, can you tell me where I can find the documentation to that? I want to add a Vimeo video via `elementorFrontend.utils.lightbox.showModal` but it doesn't have the right origin.
I need to see what attributes the object has.

**Comment by Micu22** [comment]
_elementorFrontend.utils.lightbox.setHTMLContent_ is hard deprecated since 3.1.4
How can we use custom html for the lightbox now?
