### ISSUE TITLE
Hiding the default WP header and footer

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#627]
What about hiding the default header that contains the title/logo and perhaps a menu, and then hide the footer that might contain various widgets.

Hiding the default WP header and footer opens up to the possibility to only use Elementor header with a logo a menu and an Elementor footer containing various widgets.

**Comment by WPDevHQ** [comment]
You would need to use a blank template for that.

Both [Blank Slate](https://wordpress.org/plugins/blank-slate/) and [Elementor Templater](https://wordpress.org/plugins/elementor-templater/) plugins give the options for that.

**Comment by paaljoachim** [comment]
Hey Zulfikar

That is very interesting! Right now I used CSS to hide the header and footer, but I will test out your Elementor Templater and see how it works.

I am hoping that the Elementor devs will add these directly into their own Predesigned Templates section!

Thanks for sharing!

**Comment by WPDevHQ** [comment]
Would be totally awesome if Elementor came with the page templates included.

**Comment by paaljoachim** [comment]
The concept of having Elementor removing the default header and footer is a good one.
But having a page template the user will need to adjust inside the edit page is not great.

Here is a concept of having the option when using Elementor on a page/post:

![elementor-hide-header-hide-footer](https://cloud.githubusercontent.com/assets/5323259/18803663/13d70cf2-81c0-11e6-917d-cdf8e6965a2e.jpg)

**Comment by WPDevHQ** [comment]
The only issue I see with this approach is having to know every theme's header/footer selector.

**Comment by paaljoachim** [comment]
That can be tricky. There might be a default naming for the header and footer that many follow.... but some will have their own names.

For instance I am using a child theme from Genesis. They use the class names of site-header and site-footer. There might be other ways of doing this that would make it easier for Elementor....

**Comment by WPDevHQ** [comment]
A standard way would be nice yes, but....not all developers use those selectors. 

And of those that do use them some nest inside their choice of framework selector so target those selectors may remove the content it will still leave the framework divs/sections in place.

**Comment by paaljoachim** [comment]
I just compared your plugin Elementor Templater to just hiding the header and footer through CSS and visually they look the same.

**Comment by paaljoachim** [comment]
Actually a much better way of hiding the header and footer is to just add a background color right behind all the Elementor elements hiding everything below it. One does not need to know the header or footer or the name of any CSS theme tag/name as it would be hidden behind the background color of the Elementor page/post.

This means the Page Settings the devs are working on. I will create another issue in regards to the Page Settings.

**Comment by joshmarom** [comment]
@paaljoachim thank you for your insights.
We don't think it is Elementors' responsibility to alter the theme's page template.
Many themes allow hiding the header and footer and this is a much more reliable way to achieve that.
At this point we do not intend to add this kind of feature to elementor.

**Comment by paaljoachim** [comment]
I agree there is no need to alter the page template. Hopefully Elementor can instead just add a body background color to a global setting and a page setting that can automatically hide everything below it (if the user decides on hiding everything below it that is).

**Comment by mharyam** [comment]
> Hey Zulfikar
> 
> That is very interesting! Right now I used CSS to hide the header and footer, but I will test out your Elementor Templater and see how it works.
> 
> I am hoping that the Elementor devs will add these directly into their own Predesigned Templates section!
> 
> Thanks for sharing!

Hello, Please how can i remove header from WordPress using CSS
