### ISSUE TITLE
Rating Widget Bug - SEO EXPERT

### ISSUE THREAD

**Issue by GreenballParis** [pojome/elementor#6276]
Hello,

Your new rating widget "ratings" is not supported / badly supported by Google because visitors do not have the opportunity to put their reviews (1 to 5 or 1 to 10 stars), it misses the bill of "average on x reviews". The best current plugin to be inspired on is https://en.wordpress.org/plugins/kk-star-ratings/ - There is not much left for your widget to be perfect, but currently it is useless ...

I am an SEO expert trust me. :)

**Comment by joshmarom** [comment]
@GreenballParis Thank you for your input.

The main purpose of the rating widget is to display user reviews on the page in a visually pleasing way.
I believe it fills this purpose quite well.
Additionally, the HTML markup of the widget includes schema.org structured data and is, to my understanding, compliant with Google's developer guidelines.

In conclusion, I do not think there is a bug with this widget, and I am closing this issue.

If you have any feature requests for this widget, please open a new issue with an appropriate title and a clear description of the requested feature and we will evaluate your request.

Thank you
