### ISSUE TITLE
[Feature Request] Pop up widget (click/scrolling)

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#628]
Could you please consider the addition of a pop up widget that would be triggered upon a button click?

Would need to have a(n) (including the usual goodies)
- text field for the title
- html input textarea for code insertion i.e. email signup form
- extra textarea(wysiwyg) for footer details i.e. disclaimer

Thanks,
Zulf

**Comment by joshmarom** [comment]
A pop-up widget will probably be a part of our upcoming PRO version.

**Comment by DaviDH15** [comment]
Also very interested in this question.
Could you please consider the addition of a pop up widget that would be triggered upon a button click?

**Comment by WPDevHQ** [comment]
@joshmarom - I have the bases for this widget and finalising it.

Just wanted to know if this is still on the roadmap for the Pro version before going all in and releasing to then have a conflict of choice for users later on?

Or better still, if you are not there yet I can contribute my code :)

**Comment by ramonztro** [comment]
+1

**Comment by kadso** [comment]
I'm with ramonztro...

I'm not sure why this was closed?

Is there a popup widget yet?

**Comment by silvascreen** [comment]
[Feature Request] Pop ups, sliders and triggers. I tried Modal for elementor and it has some flaws. Since you already have a lightbox I don't think its too far away. We need to add forms to the lightbox, animations like slide in, and to select times trigger or click trigger.

**Comment by parfilov** [comment]
In addition to the popup trigger for clicking, scrolling, time on the site or exit intent, I would like to offer one more — show popup on link follow.
Show popup when user opens website exactly by link, where in the end will be present code like – #e-popup-123.
And I'm really looking forward to the popup in Elementor!

**Comment by justsimply** [comment]
+1 +1 +1 +1 +1

**Comment by cobusvanvuuren** [comment]
I also would like to request this feature.  It would be great to use on landing pages and home pages to get a click to popup form that collects subscriber information etc.  This type of button or link click option converts much.

**Comment by falken83** [comment]
Im not sure if this is already included in Elementor (Pro):
Cookie banner like mentioned above so that visitors can accept Cookies in accordance to european law.
Please anyone say if this is already possible or still on the timeline.

**Comment by BrookeRaraAvis** [comment]
+1

**Comment by fxaviers** [comment]
A request so old ... Any milestone? Can we hope?

I am not demanding anything, but it would be great if we were to get a position if the resource is at least being developed.

**Comment by fxaviers** [comment]
A request so old ... Any milestone? Can we hope?

I am not demanding anything, but it would be great if we were to get a position if the resource is at least being developed.

**Comment by Recover-Zone** [comment]
This is a great Idea we would love to see incorporated into Elementor! There are many types of pop ups that could be useful for websites:
- Exit intent pop ups
- Button triggered pop ups
- Timed pop ups
- Etc. 

These would all expand to the already vast Elementor interface and capability. Currently the only solutions we are aware of are third party companies like Ultimate Add-ons for Elementor who provide a pop up element or linking through Elementor template Id to yet again third party plugins designed for pop ups. 

Adding a feature like this to Elementor could revolutionize the page builder market, as it seems there is a void left in page builders for marketing content capabilities like this one. Hope to see some work on developing a solution to this.
