### ISSUE TITLE
add_render_attribute "_inner_wrapper"

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#6287]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When using php hook 'elementor/frontend/element/before_render' with the example add_render_attribute( '**_wrapper'**,array()); like in the example below:

```
add_action( 'elementor/frontend/element/before_render', function ( \Elementor\Element_Base $element ) {
	if ( ! $element->get_settings( 'my-custom-settings' ) ) {
		return;
	}

	$element->add_render_attribute( '_wrapper', [
		'class' => 'my-custom-class',
		'data-my_data' => 'my-data-value',
	] );
} );
```
It's a very neat feature, but incomplete in my opinion.

Instead of just "**_wrapper**" it would be nice to have and the other "wrappers" for the html tags like:

- `<div class="elementor-widget-container">`
- `<div class="elementor-column-wrap">`

Because most of the CSS is applied to those classes and if you want to add inline attribute to them you can't.
 

**Describe the solution you'd like**
It will be nice to have another attribute like "**_inner_wrapper**" to affect those divs from above so we can write a code like:

```
add_action( 'elementor/frontend/element/before_render', function ( \Elementor\Element_Base $element ) {
	if ( ! $element->get_settings( 'my-custom-settings' ) ) {
		return;
	}

	$element->add_render_attribute( '_inner_wrapper', [
		'class' => 'my-custom-class',
		'data-my_data' => 'my-data-value',
	] );
} );
```

This can be achieved by adding for example in **/includes/elements/column.php**:

`894			<div class="<?php echo $column_wrap_class; ?>">`

like this:

`894			<div class="<?php echo $column_wrap_class; ?>" <?php echo $this->get_render_attribute_string( '_inner_wrapper' ); ?>>`

Of course the same should be done and for the widget and section.

**Comment by bainternet** [comment]
@dudaster 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by danielporto** [comment]
Man, don't you get on your nerves when they *close* an issue on the standard argument of:

"Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it."

Seriously. This is the main reason why I don't even bother to try to contribute with code to elementor. I honestly never seen such an attitude in any of the other opensource projects I submitted patches.

@dudaster you are a great man. Thanks for all your contributions.

@ elementor folks, that's exactly the way you bring a community down. Specially those that officially supports your work. I'm not saying you must accept every patch and idea. I'm saying that there are better ways to interface with the community.

**Comment by black-eye** [comment]
+1

**Comment by dudaster** [comment]
Thanks for the changes!
