### ISSUE TITLE
Elementor Conditions + WPML

### ISSUE THREAD

**Issue by shaneonabike** [pojome/elementor#6290]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Essentially, I discovered an interesting little problem with Elementor conditions, templates, and WPML. If you create a page template, for example, that includes all pages, but then you add additional pages to exclude it functions properly in the default language. After translating said page to another language then it does not exclude that page. In speaking with the WPML team (https://wpml.org/forums/topic/wpml-elementor-conditional-exclusions-do-not-work/page/2/#post-2945725) they indicated that in fact the problem lies in the Include All as it will no longer determine if there are any exclusions. I believe this is strictly to do with translations.

## Steps to reproduce

- Create a special page
- Create a new page template
- Set a condition to include all pages
- Exclude a certain page you wish to test (the special page from above)
- Create a new test page like Home
- Test that it works - yes it does
- Translate the page to another language - Should also work fine
- Translate the special page - It will display hte content of the page template and the content within the actual page

## Isolating the problem
- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
`

Custom Icons for Elementor - 0.1.4 | By Michael Bourne |  
-- | -- | --
Ele Conditions - 1.0.5 | By Liviu Duda |  
Ele Custom Skin - 1.0.9 | By Liviu Duda |  
Elementor - 2.3.2 | By Elementor.com |  
Elementor Inline SVG - 1.2.0 | By Namogo |  
Elementor Pro - 2.2.0 | By Elementor.com

``

```
</details>

**Comment by bainternet** [comment]
@shaneonabike 

thanks for reporting,

as you know elementor has nothing to do with translations or how they work for WPML, but we do try to work closely with the WPML team, and just now (in Elementor Pro v2.2.0) we have added a new filter `elementor/theme/get_location_templates/condition_sub_id` which was requested by WPML which allows them to filter the id's of objects with their translations. 

For cases like this.

thanks again.
