### ISSUE TITLE
Button shadow state [BUG]

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#6295]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When setting button's shadow the normal state and the hover state are the same.
Even then they both have this shadow dialog box so it seem's to have the option to set it for each state separately. 

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.

**Comment by bainternet** [comment]
@bentalgad 

The shadow control is not a part of the state controls, its general for the button.

the state control tabs are for colors and animation:
![hlfzx9f](https://user-images.githubusercontent.com/660572/49220577-46730600-f3df-11e8-8dd8-ad5f70c66680.png)


anything below that is not a part of the state.

thanks.

**Comment by bentalgad** [comment]
Oh, sorry, that is not so clear in the ui. so does it mean you can't change the button's shadow on hover state? (Btw i think buttons should have click state also, but's a feature request i guess).

**Comment by bainternet** [comment]
@bentalgad 	

correct and correct :)
