### ISSUE TITLE
Box content with scroll bar

### ISSUE THREAD

**Issue by ironarmi** [pojome/elementor#6298]
Good morning, take a look at this link:
http://theporndude.com

As you can see there are many boxes with content and a scroll bar to see all the content in the same box by using the scroll bar, otherwise it would be necessary an insanely long text box.

It would be nice to have a content box like this because in this way the navigation, for customers, would be more comfortable because they could have a quick view of topic's lists instead of switching page from page to page, to search what they want in a "post content" for example.

Is there a way to have the same in Elementor ?

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now its only possible via Custom CSS
Thanks for the feedback.

**Comment by ironarmi** [comment]
Hello, ok, so, can you please provide me the CSS ?
