### ISSUE TITLE
Control typography inside repeater

### ISSUE THREAD

**Issue by wayheming** [pojome/elementor#6299]
Control typography inside repeater not working correctly.

Map code:
```
$repeater = new Repeater();

$repeater->add_group_control(
	Group_Control_Typography::get_type(),
	[
		'name'     => 'title_typography',
		'scheme'   => Scheme_Typography::TYPOGRAPHY_1,
		'selector' => '{{WRAPPER}} .banner-title',
	]
);

$this->add_control(
	'content_repeater',
	[
		'type'        => Controls_Manager::REPEATER,
		'title_field' => esc_html__( 'Banner item', 'theme' ),
		'fields'      => array_values( $repeater->get_controls() ),
	]
);
```

Result:
https://gyazo.com/82d4e3c10bdb4c6065e658aa9c820bc9

Problem:
Closing the typography on the next click on the call button does not work. Also, the fields that appear do not differ in the background color as in the normal mode and merge with the other fields.

**Comment by wayheming** [comment]
I found the similar issue #3446 if this is not possible now do you planed add this fix or feature in the nearest update? I work with the new project and this feature a very need for me.

**Comment by bainternet** [comment]
@wayheming 	

you are correct:
> group controls are not officially supported in repeaters. (Yet anyway).


Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by wayheming** [comment]
@bainternet Thanks

**Comment by dtmgs** [comment]
Looking for this update.

**Comment by latheeshvmv** [comment]
+1

**Comment by webdevs-pro** [comment]
Can we have some updates here?

**Comment by comicrebels** [comment]
Inside repeater, global argument does not apply by default. Also I found if I click on the edit typography button, popover toggle and set the values from the default global settings values.

Since group control typography works inside repeater, is this a bug or it is not supported jet?

Thanks.

```
$repeater->add_group_control(
        \Elementor\Group_Control_Typography::get_type(),
        [
            'name' => 'control_name',
            'selector' => '{{WRAPPER}} {{CURRENT_ITEM}} .class',
            'global' => [
               'default' => \Elementor\Core\Kits\Documents\Tabs\Global_Typography::TYPOGRAPHY_TEXT
            ],
        ]
    );
```
