### ISSUE TITLE
Text/Visual editor

### ISSUE THREAD

**Issue by djmtype** [pojome/elementor#63]
Some of my shortcodes need to be included as inline elements within paragraphs. Elementor's version of TinyMCE(?) seems more custom than WP's implementation, so shortcode buttons which normally allow me to place shortcodes are not being included. 
Also, please allow full screen in the Text editor view. Consider manual control over adjusting the width of Elementor's toolbar – so constraining. Thanks!

**Comment by arielk** [comment]
Thanks for your reporting. Fixed (c625d814af38cebdb834061372b87d6f6e933241)
