### ISSUE TITLE
Entrance Animation when opacity is set to another value

### ISSUE THREAD

**Issue by Turanligil** [pojome/elementor#6301]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When an element for example an image wanted to be shown with an opacity of 50% there is a visual problem when the same element has an entrance animation with fade. The element is fading up to 100% and then gets his set opacity of 50%.

The animation should first check the opacity value and then fade it up to this value (not to 100%)

## Steps to reproduce
see above on description

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>Windows 10, Chrome Browser</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

Operating System: | Linux |  
-- | -- | --
Software: | Apache/2.4.35 |  
MySQL version: | Source distribution v5.6.19-67.0 |  
PHP Version: | 7.2.11 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

```
</details>

**Comment by bainternet** [comment]
@Turanligil 	

Thanks for reporting,

Sadly, currently, this is how our animation (which is mostly CSS based) work.

I don't see it changing anytime soon.

thanks again.

**Comment by Turanligil** [comment]
wow ... thats a very clear answer for (in my opinion) a bug ... to an pro user 👎
