### ISSUE TITLE
Toggle widget; #elementor-tab-title-6341 

### ISSUE THREAD

**Issue by Rafava** [pojome/elementor#6307]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Rafava** [comment]
I have a site with Elementor version 2.2.7 and I can't update to newer version because of this issue. 
I use a CTA widget and the url to a page with a toggle widget. I use the tab-tittle-id to open the intendend "tab"/toggle. It works like a charm. The live site would be on Ocean WP and I have tried with GP as well with newer versions of Elementor, but this does not work. The tabs are just closed.

**Comment by bainternet** [comment]
@Rafava 	

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* Isolating the problem.
* System info.
