### ISSUE TITLE
Control options based on previous control value

### ISSUE THREAD

**Issue by AmibeWebsites** [pojome/elementor#6308]
I've been trying to find a solution that leads on from the requests in #4998 and #4388.

I have two select controls where the second dynamically updates based on the choice of the first using AJAX. This works great.

The issue is that at a later time when editing the widgit the value of the second select is 'lost' because when rendering the correct options are not there yet.

I've attempted to get the current value of the first select control to prepopulate the options of the second select but it generates a fatal error (even though the code actually works).

Here's the example code:
```
// First selection control FOO
$this->add_control(
  'foo',
  [
    'label' => esc_html__( 'Foo', 'x' ),
    'type' => Controls_Manager::SELECT,
    'options' => get_foo_options(),                                
  ]
);

// echo $this.get_data('elements')['settings']['foo']; wp_die();

// Second selection control BAR - options determined by FOO
$this->add_control(
  'bar',
  [
    'label' => esc_html__( 'Bar', 'x' ),
    'type' => Controls_Manager::SELECT,
    'options' => get_bar_options( $this.get_data('elements')['settings']['foo'] ),
  ]
);
```

If I uncomment the line that echo's $this.get_data('elements')['settings']['foo'] the correct value (previously saved for the widget) displays.

However, Elementor doesn't load and the following error is logged:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Elementor\Core\Base\Base_Object::get_items() must be of the type array, null given, called in /www/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1023 and defined in /www/wp-content/plugins/elementor/core/base/base-object.php:95
```
What am I doing wrong? Is there a better way?

Thank you.

**Comment by bainternet** [comment]
if you uncomment that echo line you will get a syntax error beacuse you cant use don notation in PHP.

and the fatal error you are getting is caused by the `options` param not being set correctly as an array.

it looks like you are mixing PHP and JavaScript.

**Comment by AmibeWebsites** [comment]
Syntax error aside (it was a late night), if I adjust the code as follows I still get the fatal error i.e. it is not a problem with the options param not being set correctly as an array (as you can see from the output). It's a problem in $this->get_data().
```
// First selection control FOO
$this->add_control(
  'foo',
  [
    'label' => esc_html__( 'Foo', 'x' ),
    'type' => Controls_Manager::SELECT,
    'options' => get_foo_options(),                                
  ]
);

print_r( get_bar_options( $this->get_data('elements')['settings']['foo'] ) );

// Second selection control BAR - options determined by FOO
$this->add_control(
  'bar',
  [
    'label' => esc_html__( 'Bar', 'x' ),
    'type' => Controls_Manager::SELECT,
    'options' => '',
  ]
);
```
Outputs:
```
Array
(
  [keyx] => Value x
  [keyy] => Vakue y
)
```
In /www/wp-content/plugins/elementor/includes/base/controls-stack.php line 1023 (ver 2.3.2) is:
```
return self::get_items( $this->data, $item );
```
The fatal error says $this->data is null and should be an array.

I don't know where $this->data is set and whether this is a bug or I've done something incorrect.

And I don't understand that, despite the fatal error, the correct value for $this->get_data() is returned.

**Comment by AmibeWebsites** [comment]
Hi @bainternet, when Elementor opens, is it possible that Elementor\Controls_Stack->init_controls() is called twice?

The first time my code works (I can see the correct result printed on the screen) but the second time the fatal error occurs.

**Comment by AmibeWebsites** [comment]
I found a hacky solution:
```
$control = (array) $this;
$options = get_bar_options( $control['\0Elementor\Controls_Stack\0data']['settings']['foo'] );
```

**Comment by YarinAyash1** [comment]
Can you add the full code?

**Comment by AmibeWebsites** [comment]
This is my code, which worked in isolation BUT it's commented out... if I recall I ditched it because then there was another issue with the JavaScript side #4941
```
function udc_get_terms_for_taxonomy( $control ){
  $control = (array) $control;
  $post_type = isset( $control["\0Elementor\Controls_Stack\0data"]['settings']['post_type'] ) ? $control["\0Elementor\Controls_Stack\0data"]['settings']['post_type'] : false;
  $taxonomy = isset( $control["\0Elementor\Controls_Stack\0data"]['settings']['post_type_taxonomy'] ) ? $control["\0Elementor\Controls_Stack\0data"]['settings']['post_type_taxonomy'] : false;

  return $post_type && $taxonomy ? udc_get_terms( $taxonomy ) : [];
}
```
What I ended up doing instead was to load each post type's terms as separate controls using conditions to display the correct terms depending on which post type is selected.

**Comment by themedev2019** [comment]
` $this->add_control(
			'nextaddons_blog_categories',
			[
				'label' => __( 'Select Categories', 'next-addons' ),
				'type' => Controls_Manager::SELECT2,
				'multiple' => true,
				'options' => NX_Config::get_category(),
				'default' => [],
			]
		);
		$control = (array) $this;
		$categoris = isset( $control["\0Elementor\Controls_Stack\0data"]['settings']['nextaddons_blog_categories'] ) ? $control["\0Elementor\Controls_Stack\0data"]['settings']['nextaddons_blog_categories'] : [];
		
		$this->add_control(
			'nextaddons_blog_post',
			[
				'label' => __( 'Select Posts', 'next-addons' ),
				'type' => Controls_Manager::SELECT2,
				'multiple' => true,
				'options' => NX_Config::get_post( $categoris ),
				'default' => [],
			]
		);`

**Comment by stormit** [comment]
Hi @themedev2019, 

It does not work with me. Does it still work with you?

Anyone has other ideas?

**Comment by spatton99** [comment]
following. trying to do something similar, return a dynamic list of titles and ids so that the user can choose from the most recent 10 of each post type. i was hoping to use an <optgroup> instead of using separate controls, but the select control only accepts a one-dimensional array. as of right now, i just have it compiling them into a single select menu.
