### ISSUE TITLE
Typekit Support

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#631]
Been following Elementor since the start and currently thinking about including it in an upcoming theme. It would be awesome to include Typekit support!

**Comment by drawcard** [comment]
Have you tried setting up CSS selectors in your Typekit installation, and then using those custom classes on your Elementor text?

https://helpx.adobe.com/typekit/using/css-selectors.html

**Comment by enkota** [comment]
@drawcard That is a good idea, didn't realise there were custom classes available!
