### ISSUE TITLE
CSS folder filter

### ISSUE THREAD

**Issue by mapwork** [pojome/elementor#6310]
Hello and sorry for my english.
I state that I have modified the general upload folder and now all the blogs of my multisite have the same uploads folder.
The filter "elementor/files/file_name" is really a very useful feature but still causes problems working in multisite mode (passing from one blog to another the css files are overwritten).
I was wondering if it was possible to add a filter to change the upload folder of css files according to the blog of the network.
Thank you

**Comment by bainternet** [comment]
@mapwork 	

the whole idea of this filter is that you can modify the file name and add the blog id to it, so it wont get overwritten.

but anyway you can always modify the upload directory using the WP native `upload_dir` filter https://codex.wordpress.org/Plugin_API/Filter_Reference/upload_dir

thanks for the feedback.
