### ISSUE TITLE
Video element - Multiple video sources

### ISSUE THREAD

**Issue by T4ngml** [pojome/elementor#6312]
I'm looking forward to build an optimized homepage from Elementor.

I need to implement a video, for desktops only on that page, and want to offer multiple sources, for different resolutions and formats).
Elementor seems to work fine for the "desktop only" aspects, as hiding the video on mobile/tablets seems to prevent loading the video on such devices (very important for mobile optimization).

However, I can't seem to find any option to declare different video sources, as I used to do:
```
<video playsinline="" muted="" loop="" poster="https://domain.com/wp-content/themes/mytheme/assets/images/home-video-poster.jpg">
    <source src="https://domain.com/wp-content/2018/11/video_1080.mp4" type="video/mp4" media="screen and (min-device-width:769px)">
    <source src="https://domain.com/wp-content/2018/11/video_1080.webm" type="video/webm" media="screen and (min-device-width:769px)">
    <source src="https://domain.com/wp-content/2018/11/video_768.mp4" type="video/mp4" media="screen and (max-device-width:768px)">
</video>
```
Any fine way to do achieve this with Elementor ?

Thanks!

**Comment by bainternet** [comment]
@T4ngml 	

You can do tat via an HTML widget.

thanks.

**Comment by T4ngml** [comment]
Hmm... Good tip, unfortunately, if the poster appears, the video won't show up, whenever I can see from the Dev. Tools> Network Chrome's panel that it loads properly.
