### ISSUE TITLE
Add filter for page dynamic CSS output file

### ISSUE THREAD

**Issue by Codevz** [pojome/elementor#6313]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Please add filter for page dynamic CSS output file, I want to filter some CSS selectors inside generated dynamic CSS

**Comment by bainternet** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.
