### ISSUE TITLE
Force Refresh controls

### ISSUE THREAD

**Issue by nnnswordfish** [pojome/elementor#6314]
Hi, I'm a PRO user and support team redirected me here.

While creating custom controls, I've noticed that some controls Refresh the preview iFrame while some of them (which have "selectors" or "prefix-class" parameters) don't.

For example, I want Responsive Slider control to always refresh the preview iFrame when the slider value is changed.

Is there any way (parameter) to force controls always refresh? Or is there a JavaScript action hook to bind on control change?

Thanks!

**Comment by nnnswordfish** [comment]
Already waiting for 3 days, maybe anyone will answer this simple question, please?

**Comment by nnnswordfish** [comment]
Maybe There is a trick to run this function somehow?

`	getDynamicParsingSettings: function getDynamicParsingSettings() {
		var self = this;

		return {
			onServerRequestStart: function onServerRequestStart() {
				self.$el.addClass('elementor-loading');
			},
			onServerRequestEnd: function onServerRequestEnd() {
				self.render();

				self.$el.removeClass('elementor-loading');
			}
		};
	`},``

**Comment by bainternet** [comment]
@nnnswordfish 

you can add `render_type` parameter to your control and set it to `template` which in turn will for a re-render of the widget and as long as you don't have a `_content_template()` method in your widget it will render form the PHP `render()` method of the widget.

thanks.

**Comment by webdevs-pro** [comment]
I put this to _content_template() and IF statement contains controls names that require reload of widget
```
         var changed = Object.keys(view.model.attributes.settings.changed)[0]; 
         if(changed == "aew_as_stack" ||
            changed == "aew_as_enabled") {
            view.model.attributes.settings.changed = {};
            view.model.renderRemoteServer();
         }
```
