### ISSUE TITLE
User details in dynamic form field

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#6315]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Some form fields can now have dynamic content. But i am missing user details as option for the dynamic content. 
So if a wordpress user opens the form, some of the fields like name, emailaddress should be filled in automatically if possible.

**Comment by bainternet** [comment]
I merged this issue with  #6322, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
