### ISSUE TITLE
Remember active tab on side panel when switching element

### ISSUE THREAD

**Issue by hybridmuse** [pojome/elementor#6318]
Side panel tab always goes back to first one (Content/Layout) when switching element or section in the editor. This is annoying as oftentimes similar work is being done across multiple elements (say, modifying style).

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by black-eye** [comment]
+1
This would be a great timesaver. I hope it will get some bigger support even though it's closed now.
