### ISSUE TITLE
Invalid file when import

### ISSUE THREAD

**Issue by ericcasaselementor** [pojome/elementor#6320]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by bainternet** [comment]
@ericcasaselementor 

Probbably not, the import export we developed works from and to WordPress, and we have nothing to do with the Prestashop fork or how it works.

thanks.

**Comment by ericcasaselementor** [comment]
Hi bainternet, thanks for your kind reply. This is a section exported, there's some difference with the .json from Wordpress. It´s possible to modify just to make it compatible? Thanks again, have a nice week.
[iqitelementor_template_id_17.json.zip](https://github.com/pojome/elementor/files/2638984/iqitelementor_template_id_17.json.zip)
