### ISSUE TITLE
Counter start automatically

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#6321]
Hello guys,

Great new redirection feature after finalizing the countdown timer. This will make it much easier not to have to do the manual process.

Now ... I wanted to leave a suggestion to develop a feature to also automatically start the countdown timer.

For example, in my case, I have a sales page for a course, and registration always opens on Mondays at 8:00 AM and ends on Wednesdays at 11:59 PM.
So, every Sunday I manually set the countdown timer to start on Monday at 8:00 AM and end on Wednesday at 11:59 PM. And so I do not have to do this process manually, before Monday, Elementor could have a resource where I set up for the countdown timer to always start every Monday.
That way, when arriving on Monday at 8:00 AM, the counter starts counting down with the time interval I had already set before (until Wednesday). When finished, it will be redirected to a 2nd page. And next Monday, that 1st page (sales page) is back to accessible (redirection turns off) and the counter returns to its countdown.

I leave here the suggestion.
Rodrigo

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by blackgoku** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> Thanks for the feedback.

+1 for this feature
