### ISSUE TITLE
 Terms and Users fields for Dynamic content

### ISSUE THREAD

**Issue by vovkasolovev** [pojome/elementor#6322]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate (Nearest #6315).
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

In addition to **Post** fields in WP there are similar fields for other records — **Terms** and **Users** fields.
Please add these Fields to use them in Templates construction to mention categories and users, like:
Category fields: _Main category title, slug link, parent category, category description_.
User fields: _Name, role, contacts, bio, userpic_.

It's will be very helpful in construction of Dynamic content for Post and Portfolio Widget and Skins.

Also note, that Toolset Types is able to add Custom Fields for both Terms and Users, but right now Elementor is able to take only CPF.
https://toolset.com/documentation/user-guides/term-fields/
https://toolset.com/documentation/user-guides/user-fields/

**Comment by tristanleboss** [comment]
+1

**Comment by zeinnicholas** [comment]
When I saw that this was introduced in 2.4 I was really happy that I wouldn't need to create shortcodes to display User data on my sites anymore. But it seems we didn't get to also pull up the User Avatar on image fields... Why?
