### ISSUE TITLE
How do I create a Gallery Dynamic Tag?

### ISSUE THREAD

**Issue by benkol** [pojome/elementor#6323]
I am creating an extension and I managed to create a custom text dynamic tag.
I understand that in order to create custom gallery dynamic tag I need to extend DynamicTags\Data_Tag but I couldn't find any documentation on how to do that.
Can you please help me?
You are welcome to reply in Hebrew if you find it easier.
(I tried contacting the support but they pointed me here)

**Comment by bainternet** [comment]
@benkol 	

Basiclly there are many dynamic tags that already extend `DynamicTags\Data_Tag` which you can look at for examples, Like "Post Image Attachments" tag or "Product Gallery" tag.


If you have a specific question feel free to ask.
