### ISSUE TITLE
Ability to extend form onError/onSuccess callbacks

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#6324]
Hello,

I want to add some code to the onError/onSuccess jQuery.ajax callbacks of the Forms module.
These functions are located in `elementor-pro/assets/js/frontend.js` in a function named `handleSubmit`.

Indeed, I need to implement kind of a captcha system: the user first fill the form and submit it. If all validation pass, I need to add a field (I plan to CSS unhide a field added in the form widget) asking for a code we send on the user mobile phone. Then, the user will submit the form a second time and, this time, if the entered code is correct, the form should submit successfully.

The code from the `onSuccess` JS function is not flexible enough to do that perfectly. Indeed, if I send an error, it will trigger the "error" event for each error but I don't receive the error data... and it will add a big error message, anyway.
If I send a success, it will call the "submit_success" but I have no way to stop Elementor from calling the  "reset" and "form_destruct" events...

Is there a way to replace overide these callabacks functions?
Idealy, I would love to be able to do: `function onSuccess(){ if( form_id === 'my_form_id' ){ myOnSuccess(); } else { elementorDefaultOnSuccess() } };` 

**At least one thing can be done:** add the error to the "error" trigger: `$form.trigger( 'error' );`. It's in a loop against `response.data.errors` so you can pass the `form_id`, `key` and `title` as arguments. This way we can do some specific code depending on the impacted field.

In WordPress they sometime use `$continue = apply_filter('filter_name', true, $somedata); if( $continue !== true ) return( $continue );` to allow us developpers to stop a function execution or override its behavior: maybe, something similar can be done in JS on the `submit_success` event.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
Its too hard to understand what you are asking/saying/requesting.

Now if I do understand you correctly, then you can already do that beacuse we are using jQuery AJAX to send the form, so you can use jQuery API to overwrite the behavour : [Global Ajax Event Handlers](https://api.jquery.com/category/ajax/global-ajax-event-handlers/)

And, There are already action and filter hooks in place for you to do that:

ex:

```PHP
// Use the Validation hook to stop the form subbmition
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );
    if ( 'MY_FORM_NAME' !== $form_name ) {
        return;
    }
	// this should be empty at first submittion
	$field_mobile_code = $record->get_field( [
        'id' => 'mobile_code',
    ] );

    if ( empty( $field_mobile_code ) ) {
        // Send mobile code to the user mobile
		

		// add data to response so you'll know to show the mobile field (via js/css)
		$ajax_handler->add_response_data( 'mobile_code_sent',  'Please check your mobile phone for code' );
		// Then return ajax handler with error to stop the for submission
  		return $ajax_handler->add_error( 'fake_id', 'Please check your mobile phone for code' );
    }

	// if you got this far then the user has submitted a mobile code so validate it:
	if ( ! $field_mobile_code['value'] ) {
		// in this example its just checking if there is a value, so make sure you validate it corrected.
		return $ajax_handler->add_error( 'fake_id', 'Please re check your mobile phone code you entered' );
	}
}, 10, 2 );
```

and the JavaScript part to show the mobile code field:
```JS
jQuery( document ).ready(function( $ ){
	$( document ).ajaxSuccess(function( event, request, settings, response ) {
		if ( response.data.mobile_code_sent ) {
			alert( response.data.mobile_code_sent  );
			//show your hidden field here
		}
	});
});
```

this is just an example, but it shows that its possible.
