### ISSUE TITLE
Adaptive Height for Testmonial Carousel

### ISSUE THREAD

**Issue by IdioticDoodler** [pojome/elementor#6327]
I have searched for similar features requests in both open and closed tickets and cannot find a duplicate. The feature is still missing in the latest stable version of Elementor ( Elementor Pro. ). My client wants to have an aauto height testimonial slider but the current version still doesn't have it, so I began my research your using a swiper slider. I read in Swiper slider that you can make it adaptive in height by putting this script
`  <script>
    var swiper = new Swiper('.swiper-container', {
      autoHeight: true, //enable auto height
    });
</script>`|
when I tried it and check the console the class container have a new class for auto height and it already have height, but the thing is when the it slider slides to next slider it doesn't change the height it still have the height of the first slider. I think the code od swiper and elementor is conflicting with each other. This an issue or we can just make a new functions for testimonial carousel to have an adaptive height. Thanks because I have a very long testimonial and short one, the short one having a large space because of the long one. Thank you for reading this

**Comment by shilo-ey** [comment]
I merged this issue with  #2539, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Damian2Cubed** [comment]
Hi guys, just like rest of you I was looking for this feature.

I did little workaround:
`testimonialsAutoHeight('.elementor-swiper-button-next');
  testimonialsAutoHeight('.elementor-swiper-button-prev');
  
  function testimonialsAutoHeight(btn) {
	  $('body').on('click', btn, function() {
		  console.log('Clicked');
		  
		  var testimonial_height = $('.swiper-slide-active .elementor-testimonial').height();
		  testimonial_height = testimonial_height + 80;
		  
		  $('.elementor-widget-testimonial-carousel .elementor-widget-container').css('height', testimonial_height);
	  });
  }`

**Comment by magriguez** [comment]
> Hi guys, just like rest of you I was looking for this feature.
> 
> I did little workaround:
> 
> ```
> testimonialsAutoHeight('.elementor-swiper-button-next');
> testimonialsAutoHeight('.elementor-swiper-button-prev');
>   
> function testimonialsAutoHeight(btn) {
> 	  $('body').on('click', btn, function() {
> 		  console.log('Clicked');
> 		  
> 		  var testimonial_height = $('.swiper-slide-active .elementor-testimonial').height();
> 		  testimonial_height = testimonial_height + 80;
> 		  
> 		  $('.elementor-widget-testimonial-carousel .elementor-widget-container').css('height', testimonial_height);
> 	  });
> }
> ```

@Damian2Cubed could you point a non-developer on where to insert this? Thank you.

**Comment by restalfep** [comment]
Any update on this? I couldn't figure out the code @Damian2Cubed provided, when trying to insert it I got a fatal error.

**Comment by salvia34** [comment]
Really want update for this too. Thank you very much in advance, because auto height doesn't works by default in Elementor Pro :(

**Comment by meganjoell** [comment]
> Really want update for this too. Thank you very much in advance, because auto height doesn't works by default in Elementor Pro :(

me too, this issue is ruining my workflow!

**Comment by MuhAwais7** [comment]
Worked for me.

Add this in your footer.php or your main JS file.

<script>
jQuery(document).ready(function($) {
testimonialsAutoHeight('.elementor-swiper-button-next');
testimonialsAutoHeight('.elementor-swiper-button-prev');
function testimonialsAutoHeight(btn) {
	  $('body').on('click', btn, function() {
		  console.log('Clicked');
		  
		  var testimonial_height = $('.swiper-slide-active .elementor-testimonial').height();
		  testimonial_height = testimonial_height + 10;
		  
		  $('.elementor-widget-testimonial-carousel .elementor-widget-container').css('height', testimonial_height);
	  });
}
  });
</script>

**Comment by weblink-hr** [comment]
Here is function that I use.

```
(function() {
        $(document).ready(function() {
            if(jQuery('.elementor-widget-testimonial-carousel .swiper-container').length) {
                const mainNode = jQuery('.elementor-widget-testimonial-carousel .swiper-container')[0];
                function callback(mutationsList, observer) {
                    mutationsList.forEach(mutation => {
                        if (mutation.attributeName === 'class') {
                            if( jQuery('.elementor-widget-testimonial-carousel .swiper-container').hasClass('swiper-container-initialized') ) {

                                // Defaults
                                const swiper = document.querySelector('.elementor-widget-testimonial-carousel .swiper-container').swiper;
                                var currentSlideIndex = swiper.activeIndex;
                                jQuery(swiper.slides[currentSlideIndex]).css('height', 'min-content');
                                var actualHeight = jQuery(swiper.slides[currentSlideIndex]).height();
                                jQuery('.swiper-wrapper,.swiper-slide').css({ height : actualHeight })
                                swiper.update();

                                testimonialAutoHeight();
                            }
                        }
                    })
                }

                function testimonialAutoHeight() {
                    if( jQuery('.elementor-widget-testimonial-carousel .swiper-container').hasClass('swiper-container-initialized') ) {
                        const swiper = document.querySelector('.elementor-widget-testimonial-carousel .swiper-container').swiper;
                        swiper.on('slideChange', function () {
                            var currentSlideIndex = this.activeIndex;
                            jQuery(this.slides[currentSlideIndex]).css('height', 'min-content');
                            var actualHeight = jQuery(this.slides[currentSlideIndex]).height();
                            jQuery('.swiper-wrapper,.swiper-slide').css({ height : actualHeight })
                            this.update();
                        });
                    }
                }

                const mutationObserver = new MutationObserver(callback);
                mutationObserver.observe(mainNode, { attributes: true });
            }
        });
    })();
```

**Comment by MichaelDarko** [comment]
3.5 years since the request a still no fix. You create multiple crappy carousel / slider widgets and then you barely maintain them because there is too many of them. Can't you just create one universal carousel / slider builder? We would be able to build whatever we need and you would be able to maintain it.

**Comment by safwanafridi** [comment]
I did some changes in @weblink-hr code.  It is already well written but didn't work for me because of the immediate invoking function approach. If you are using any code inserting plugin which is already adding the <script> tag in the code then you can remove the <script> from the below code.

```
<script>
jQuery(document).ready(function(){
            if(jQuery('.elementor-widget-testimonial-carousel .swiper-container').length) {
                const mainNode = jQuery('.elementor-widget-testimonial-carousel .swiper-container')[0];
                function callback(mutationsList, observer) {
                    mutationsList.forEach(mutation => {
                        if (mutation.attributeName === 'class') {
                            if( jQuery('.elementor-widget-testimonial-carousel .swiper-container').hasClass('swiper-container-initialized') ) {

                                // Defaults
                                const swiper = document.querySelector('.elementor-widget-testimonial-carousel .swiper-container').swiper;
                                var currentSlideIndex = swiper.activeIndex;
                                jQuery(swiper.slides[currentSlideIndex]).css('height', 'min-content');
                                var actualHeight = jQuery(swiper.slides[currentSlideIndex]).height();
                                jQuery('.swiper-wrapper,.swiper-slide').css({ height : actualHeight })
                                swiper.update();

                                testimonialAutoHeight();
                            }
                        }
                    })
                }

                function testimonialAutoHeight() {
                    if( jQuery('.elementor-widget-testimonial-carousel .swiper-container').hasClass('swiper-container-initialized') ) {
                        const swiper = document.querySelector('.elementor-widget-testimonial-carousel .swiper-container').swiper;
                        swiper.on('slideChange', function () {
                            var currentSlideIndex = this.activeIndex;
                            jQuery(this.slides[currentSlideIndex]).css('height', 'min-content');
                            var actualHeight = jQuery(this.slides[currentSlideIndex]).height();
                            jQuery('.swiper-wrapper,.swiper-slide').css({ height : actualHeight })
                            this.update();
                        });
                    }
                }

                const mutationObserver = new MutationObserver(callback);
                mutationObserver.observe(mainNode, { attributes: true });
            }
        });
	
	</script>
```

**Comment by wandersonce** [comment]
> Here is function that I use.
> 
> ```
> (function() {
>         $(document).ready(function() {
>             if(jQuery('.elementor-widget-testimonial-carousel .swiper-container').length) {
>                 const mainNode = jQuery('.elementor-widget-testimonial-carousel .swiper-container')[0];
>                 function callback(mutationsList, observer) {
>                     mutationsList.forEach(mutation => {
>                         if (mutation.attributeName === 'class') {
>                             if( jQuery('.elementor-widget-testimonial-carousel .swiper-container').hasClass('swiper-container-initialized') ) {
> 
>                                 // Defaults
>                                 const swiper = document.querySelector('.elementor-widget-testimonial-carousel .swiper-container').swiper;
>                                 var currentSlideIndex = swiper.activeIndex;
>                                 jQuery(swiper.slides[currentSlideIndex]).css('height', 'min-content');
>                                 var actualHeight = jQuery(swiper.slides[currentSlideIndex]).height();
>                                 jQuery('.swiper-wrapper,.swiper-slide').css({ height : actualHeight })
>                                 swiper.update();
> 
>                                 testimonialAutoHeight();
>                             }
>                         }
>                     })
>                 }
> 
>                 function testimonialAutoHeight() {
>                     if( jQuery('.elementor-widget-testimonial-carousel .swiper-container').hasClass('swiper-container-initialized') ) {
>                         const swiper = document.querySelector('.elementor-widget-testimonial-carousel .swiper-container').swiper;
>                         swiper.on('slideChange', function () {
>                             var currentSlideIndex = this.activeIndex;
>                             jQuery(this.slides[currentSlideIndex]).css('height', 'min-content');
>                             var actualHeight = jQuery(this.slides[currentSlideIndex]).height();
>                             jQuery('.swiper-wrapper,.swiper-slide').css({ height : actualHeight })
>                             this.update();
>                         });
>                     }
>                 }
> 
>                 const mutationObserver = new MutationObserver(callback);
>                 mutationObserver.observe(mainNode, { attributes: true });
>             }
>         });
>     })();
> ```

This worked for me. Thanks!

**Comment by mirajadesign** [comment]
This is working for me. Thank you! @safwanafridi

> I did some changes in @weblink-hr code. It is already well written but didn't work for me because of the immediate invoking function approach. If you are using any code inserting plugin which is already adding the <script> tag in the code then you can remove the <script> from the below code.
> 
> ```
> <script>
> jQuery(document).ready(function(){
>             if(jQuery('.elementor-widget-testimonial-carousel .swiper-container').length) {
>                 const mainNode = jQuery('.elementor-widget-testimonial-carousel .swiper-container')[0];
>                 function callback(mutationsList, observer) {
>                     mutationsList.forEach(mutation => {
>                         if (mutation.attributeName === 'class') {
>                             if( jQuery('.elementor-widget-testimonial-carousel .swiper-container').hasClass('swiper-container-initialized') ) {
> 
>                                 // Defaults
>                                 const swiper = document.querySelector('.elementor-widget-testimonial-carousel .swiper-container').swiper;
>                                 var currentSlideIndex = swiper.activeIndex;
>                                 jQuery(swiper.slides[currentSlideIndex]).css('height', 'min-content');
>                                 var actualHeight = jQuery(swiper.slides[currentSlideIndex]).height();
>                                 jQuery('.swiper-wrapper,.swiper-slide').css({ height : actualHeight })
>                                 swiper.update();
> 
>                                 testimonialAutoHeight();
>                             }
>                         }
>                     })
>                 }
> 
>                 function testimonialAutoHeight() {
>                     if( jQuery('.elementor-widget-testimonial-carousel .swiper-container').hasClass('swiper-container-initialized') ) {
>                         const swiper = document.querySelector('.elementor-widget-testimonial-carousel .swiper-container').swiper;
>                         swiper.on('slideChange', function () {
>                             var currentSlideIndex = this.activeIndex;
>                             jQuery(this.slides[currentSlideIndex]).css('height', 'min-content');
>                             var actualHeight = jQuery(this.slides[currentSlideIndex]).height();
>                             jQuery('.swiper-wrapper,.swiper-slide').css({ height : actualHeight })
>                             this.update();
>                         });
>                     }
>                 }
> 
>                 const mutationObserver = new MutationObserver(callback);
>                 mutationObserver.observe(mainNode, { attributes: true });
>             }
>         });
> 	
> 	</script>
> ```

**Comment by mirajadesign** [comment]
@safwanafridi @weblink-hr - I just realized that it works for some testimonials but not others, depending on the design. Do you or anyone know how to add the ability to exclude this script from affecting specific widgets with CSS ID?
