### ISSUE TITLE
New social icon for Bandcamp

### ISSUE THREAD

**Issue by JoeyDodson** [pojome/elementor#6329]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The Social Icons widget currently lacks an icon for Bandcamp, a popular music downloading and streaming site. 

**Describe the solution you'd like**
The icon for Bandcamp as found on Font Awesome can be added to the Social Icons widget. 
https://fontawesome.com/icons?d=gallery&q=bandcamp

**Describe alternatives you've considered**
Alternatively, I would have to manually build a social icon section, individually placing one icon at a time and formatting each separately, when they should really be consolidated as the Social Icons widget is intended. 

**Additional context**
N/A

Thank you!

**Comment by bainternet** [comment]
I merged this issue with  #4430 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
