### ISSUE TITLE
Updating meta data _elementor_data crash the UI of the page

### ISSUE THREAD

**Issue by daljeet19881119** [pojome/elementor#6333]
I was updating one of the icon link in the json stored in the meata data field _elementor_data  using the str_replace. string replace work fine but after udpate data on the meta fields again spoil i am using the method udpate_post_meta.  

Before update: https://prnt.sc/lq1zuc
After update: https://prnt.sc/lq1x5s

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Without seeing the meta value (the actual JSON) We can't really help. But its most likely a broken JSON format which is causing it.

**Comment by daljeet19881119** [comment]
Okay so if the issue is broken JSON can you share some methods or code i can use to update the JSON in meta and replace string in json string.

**Comment by bainternet** [comment]
This has nothing to do with Elementor:

```PHP
// Get the meta
$meta = get_post_meta( $post_id, 'meta_key, true );
// Decode the json
$meta_json = json_decode( $meta, true );

// Update what ever you want
$meta_json['what_i_want_to_update'] = 'New value';

// Encode json back to string
$meta = json_encode( $meta_json );
// Update meta
update_post_meta( $post_id, 'meta_key', $meta );
```
