### ISSUE TITLE
Blockquote widget doesn't pull ACF Content or Author

### ISSUE THREAD

**Issue by ai-wintermute** [pojome/elementor#6334]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When I'm adding ACF fields for the Blockquote's widget (text and author), the fields' content displays in the Elementor's editor as expected. But after updating, the changes don't appear on the page. I see only the default text for both fields (or a blank block is I remove the blockquote default text and author).

## Steps to reproduce
Add 2 ACF text fields for blockquote text and author.
Go to the 'Edit with Elementor' (I'm using a Pro version 2.2.3) -> select 'Blockquote' widget -> Add a dynamic content for each Content and Author -> Select previosly created ACF fields (changes will be displayed as expected) -> Update -> Visit the page - no content will be displayed.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

[https://pastebin.com/4pqd8js5](https://pastebin.com/4pqd8js5)

**Comment by bainternet** [comment]
@ai-wintermute 

thanks for reporting, should be fixed in next version.

**Comment by bainternet** [comment]
Fixed in Elementor pro 2.24 thanks
