### ISSUE TITLE
Advanced Options in Archive Posts Widget

### ISSUE THREAD

**Issue by Alok-S-Sharma** [pojome/elementor#6336]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have created a Custom Post Type and accordingly created an Archive Template in Elementor Pro. Now when I added the Archive Posts Widget, I couldn't find the following advanced options to customise the template:

1. Change Order By
2. Change Order
3. Posts per Page

My requirement is to display certain contents like Custom Post Type in different styles and format. For eg., I have created a list of courses and would like to display them all at once in alphabetical order.

**Describe the solution you'd like**
The above settings are available in Post Widget and I believe the same should be made available in Archive Post Widget also.

**Describe alternatives you've considered**
I have discovered that these advanced settings are present in Post Widget.

For the time being, I have achieved what I was looking for by using the Post Widget.

Another alternative is to create a Page rather than Archive Template and then add the Post Widget.

But both the alternatives completely kill the purpose of creating a Custom Post Type Archive Template and the Archive Posts Widget.

**Additional context**

**Comment by bainternet** [comment]
@Alok-S-Sharma 

Archive Posts Widget widget uses the current native WP query to select the posts, including the settings you have for "Blog pages show at most" (a.k.a posts per page) in the native WP settings >> reading panel.

And the Order, Order by are also WP defaults. The Whole Idea of that widget is to simply allow you to place and style the archive posts without the need to define the query.

Now there is an up side for you in this, beacuse it uses the native WP Query, all of the native filters are applied to it so you can easly modify the query using these filters that have nothing to do with elementor, e.g:

```PHP
add_action( 'pre_get_posts', function ( $query ) {
	// Only modify the query we want
	if ( ! $query->is_main_query() || ! $query->is_archive() ) {
		return;
	}

	// set posts per page
	$query->set( 'posts_per_page', 3 );
	// set order by
	$query->set( 'orderby', 'title' );
	// set order
	$query->set( 'order', 'DESC' );
} );
```

**Comment by Alok-S-Sharma** [comment]
If all that I wanted to write lines and pieces of code, I wouldn't have purchased Elementor Pro, not even used Elementor at all. I could build my own custom theme from scratch and achieve what all I wanted.

I left behind coding years ago to make my life simpler so that I can get more time to travel, photograph, build clean, minimalistic & mobile-friendly websites (leaving behind the hassles of writing & updating codes for every small reason) and still get plenty of time to live life.

**Comment by Luxamman** [comment]
Referenced this to https://github.com/elementor/hello-theme/issues/84, because if the Hello Theme cannot handle this, most of the people using Elementor Pro with Hello Theme, won't be able to handle that (yes, code is not a solution for most people, sorry... especially when I have a payed version)

Thanks!

**Comment by birdbrainsolutions** [comment]
> @Alok-S-Sharma
> 
> Archive Posts Widget widget uses the current native WP query to select the posts, including the settings you have for "Blog pages show at most" (a.k.a posts per page) in the native WP settings >> reading panel.
> 
> And the Order, Order by are also WP defaults. The Whole Idea of that widget is to simply allow you to place and style the archive posts without the need to define the query.
> 
> Now there is an up side for you in this, beacuse it uses the native WP Query, all of the native filters are applied to it so you can easly modify the query using these filters that have nothing to do with elementor, e.g:
> 
> ```
> add_action( 'pre_get_posts', function ( $query ) {
> 	// Only modify the query we want
> 	if ( ! $query->is_main_query() || ! $query->is_archive() ) {
> 		return;
> 	}
> 
> 	// set posts per page
> 	$query->set( 'posts_per_page', 3 );
> 	// set order by
> 	$query->set( 'orderby', 'title' );
> 	// set order
> 	$query->set( 'order', 'DESC' );
> } );
> ```

Where does this code go? I'm using custom post type called 'my_events' and have created an archive template in elementor pro called 'Event Archive'. I would like to change the order of the posts from descending to ascending. 

I can see this option in the regular blog archive, but not for the custom post archive for some reason.

Please help, thanks!

**Comment by Alok-S-Sharma** [comment]
> Where does this code go? I'm using custom post type called 'my_events' and have created an archive template in elementor pro called 'Event Archive'. I would like to change the order of the posts from descending to ascending.
> 
> I can see this option in the regular blog archive, but not for the custom post archive for some reason.
> 
> Please help, thanks!

@birdbrainsolutions 

Regarding the code, I never understood where to insert this piece of code. Actually, Elementor is all about building & designing websites all without writing a single piece of code. At least this is what it is intended to do.

But since the developers are not willing to co-operate or even listen to the voice of their customers, we are left with very little options. Either build the website with what all they offer or research custom solutions.

I would suggest you try https://toolset.com/. Unlike Elementor, their support is awesome.

I am using it and it is perhaps one of the best and easiest set of plugins to create custom post & archive templates. Actually, you can do a lot more than just create custom post & archive templates.

I understand it might not fit into your budget, but if it does, then this is the last plugin you are ever going to need to have complete control over your posts and custom post types templates.

Do let me know if you need any further help.

**Comment by birdbrainsolutions** [comment]
@Alok-S-Sharma

My apologies, I was trying to reply to the person who posted the code. 

I do know what Elementor is, and I finally used the posts widget as well. It's weird that they included it in one widget, but not the other. 

Are you using toolset instead of elementor or as an alternative to ACF pro?

**Comment by Alok-S-Sharma** [comment]
@birdbrainsolutions

I am using Toolset in addition to Elementor.

It allows me to design custom templates for posts, custom post types &
archive pages presicely the way I want it to be.

I suggest you have a look at their demos and videos.

Thanks,

Alok Sharma
(aloksharma.in)

**Comment by nicknoidea** [comment]
It is a real shame that this feature request is not being added to elementor. This seems like a solid piece of functionality that many users would benefit from. 

I have tried the above code and it works on my site but when I try to use 'Rand' to display the posts in random order it doesn't work. This is what I tried. 


`add_action( 'pre_get_posts', function ( $query ) {
	// Only modify the query we want
	if ( ! $query->is_main_query() || ! $query->is_archive() ) {
		return;
	}

	// set posts per page
	//$query->set( 'posts_per_page', 3 );
	// set order by
	$query->set( 'orderby', 'title' );
	// set order
	$query->set( 'order', 'Rand' );
} );`


I have a custom post type 'Course'

And I want to display the courses sorted by a taxonomy field free and not fee but in random order. so that the free courses are always at the top of the results like the below. what does the PHP need to be to achieve this?



<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

taxonomy | course
-- | --
free | Random
free | Random
free | Random
free | Random
free | Random
free | Random
free | Random
Not free | Random
Not free | Random
Not free | Random
Not free | Random
Not free | Random
Not free | Random
Not free | Random
Not free | Random


</body>
</html>

any help appreciated :)

**Comment by Alok-S-Sharma** [comment]
@nicknoidea

There is a small issue with your code, you have specified order parameter twice, either it can be title or rand:

```
// set order by
$query->set( 'orderby', 'title' );
// set order
$query->set( 'order', 'Rand' );
```

It should be something like this:

```
$args = array(
    'orderby'        => 'rand',
    'posts_per_page' => '3',
 
);
$query = new WP_Query( $args );
```

Please see this article https://developer.wordpress.org/reference/classes/wp_query/#order-orderby-parameters

Not trying to criticize anyone but Elementor people are having ego issues, and they will delete anything that they feel is against them, at least in their blog post comments and I have had this experience.

That's why I switched to Beaver Builder & Beaver Themer and my experience has been far better than my expectations.

Apart from that, I am using Toolset which is a wonderful solution for creating dynamic content and once you know the basics, then sky is the limit. I am building a site that involves a lot of post relationships, custom post types etc and the Toolset support has been very helpful in providing all the valuable support. Just give it a try.

**Comment by agw421** [comment]
Just posting to say this article does help solve the problem if users are willing to go to the functions.php and paste in the beautiful code above posted by @Alok-S-Sharma.
