### ISSUE TITLE
Blog/Portfolio Layout with Badge and Taxonomy

### ISSUE THREAD

**Issue by MarcJames1** [pojome/elementor#6337]
Hi there,

I'm currently designing a news layout page for a client and am trying to work out the best way to achieve what they're requested. If you the following link, you'll get an idea of the type of layout and they want: 

https://www.dropbox.com/s/red06s9cjchsubj/Website%20Mock-Ups_NEWS_IDEAL%20OPTION.png?dl=0

From what I can tell, I can get almost 85% there using the 'portfolio' widget as it allowed me to use taxonomy to switch categories which they have requested. However, I'm unable to get the badge overlay onto each post as well. Is there any way to do this? Or even a better way I'm not thinking of? 

Thanks!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

But follow #4440 

Thanks for the feedback.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
