### ISSUE TITLE
Save as global not working in pro.

### ISSUE THREAD

**Issue by miriksbm** [pojome/elementor#6338]
Ha everyone,

I'm running into a problem on my website, with a specific plugin.  

Whenever i disable the plugin, and reload the editor... saving as global becomes an option. when i enable the plugin again, the option says " Get Pro " 

Please help.

Cheers

**Comment by bainternet** [comment]
I merged this issue with  #6340, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
