### ISSUE TITLE
Inactive widget area - holding area for widgets/columns/sections not in use

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#634]
Sometimes we test out various widgets and see what works and not.
We fill in a widget then over time figure that it might be better to use another widget. A bit hesitant we go ahead and delete the one widget in favor of the new widget we believe will fit in better.

Instead of having to delete a widget we spent time filling out with information it would be great to have a widget saving/holding location. Perhaps even dragging columns/sections or widgets to a holding location. Kinda like the inactive widgets in WordPress.

![screen shot 2016-09-24 at 17 16 44](https://cloud.githubusercontent.com/assets/5323259/18811346/b1dd2ed0-827a-11e6-8255-f6936fe65add.png)

The area could be just called holding - for holding elements we are not ready to delete yet.

**Comment by LDX1** [comment]
Maybe another way to do that could be a simple flag in any widget you are using setting if you would show it or not:

Display mode:
[x] show (default)
[  ] hide

I don't know if this could reach the same result you want.

**Comment by paaljoachim** [comment]
Just yesterday I added a video using the video element and had to delete it again as it did not fit into the specific location I had it in. Having a way to hide the element would help a lot. So that if I decide to use it in another location I could just drag it there. So yes just a simple flag for hiding it would be of help. Clicking the hide option the element could perhaps in edit mode change to an opacity of .5. Showing that something is there but not active. When viewing the site it could have a CSS of display none. I think that might be easiest way of handling it.

**Comment by parfilov** [comment]
I need it too. Let hidden section, column or widget be grey in editor when hidden f. ex., but in frontend is absent at all.
Thanks!

**Comment by bainternet** [comment]
This can be done by saving the widget as global or even the section since Elementor Pro 1.9 and importing it anywhere you want.


thanks.
