### ISSUE TITLE
Global widget will not update in version 2.2.3 PRO

### ISSUE THREAD

**Issue by elasticeye** [pojome/elementor#6340]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

In version 2.2.3 PRO, when editing a global widget and click update, the change will not happen on front-end. 
When roll-back to version 2.1.13, it works fine. I have version 2.3.4 of Elementor installed.

## Steps to reproduce

Please see this video for further explanation:
https://www.useloom.com/share/aef8de32a9b34b1191097e264597a249

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [Astra ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.23
	PHP Version: 7.2.12
	PHP Max Input Vars: 12000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://belldesign.no
	Home URL: https://belldesign.no
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: nb-NO
	Timezone: Europe/Oslo
	Debug Mode: Inactive

== Theme ==
	Name: astra
	Version: 1.6.0
	Author: Bell design
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.6.0
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: nb_NO
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.3.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.2.3
		Author: Elementor.com

== Debug ==
	Errors: 
		TypeError: Cannot read property 'on' of null
			at https://belldesign.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.2 - 2:223303
			2018-11-25 10:06 +00:00
			x 12 times

		TypeError: Cannot read property 'style' of undefined
			at https://belldesign.no/wp-admin/js/editor.min.js?ver=4.9.8 - 1:694
			2018-11-25 10:06 +00:00
			x 12 times

		TypeError: e.ui.loading.addClass is not a function
			at https://belldesign.no/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.2.0 - 2:36216
			2018-11-25 09:54 +00:00
			x 2 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://belldesign.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.5 - 2:239323
			2018-10-16 20:55 +00:00
			x 2 times

		TypeError: Cannot read property 'on' of null
			at https://belldesign.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.14 - 2:82365
			2018-06-04 05:45 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://belldesign.no/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-04 05:45 +00:00

		TypeError: Cannot read property 'on' of null
			at https://belldesign.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.14 - 2:82365
			2018-06-04 05:40 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://belldesign.no/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-04 05:40 +00:00

		TypeError: Cannot read property 'label' of undefined
			at https://belldesign.no/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.0.2 - 2:45725
			2018-04-20 08:17 +00:00
			x 28 times

		TypeError: e.ui.itemTitle.html is not a function
			at https://belldesign.no/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.7 - 2:70468
			2018-04-20 08:03 +00:00
			x 7 times

**Comment by bainternet** [comment]
Fixed in Elementor pro 2.24 thanks.
