### ISSUE TITLE
Multiple widgets inline arrange. 

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#6342]
Hello,

Let's say I have 3 icon widgets on header nav.  
( maybe it looks like this :  )
![image](https://user-images.githubusercontent.com/5612050/49417728-4d748c80-f7c2-11e8-89d4-13bbb9a114a6.png)

- a user icon : it's for login
- a bell icon : it's for notification, it should be showing when user's logged in.
- a search icon : it's for search

I want to add them inline arrangement. 
If we work on html / css, you can simply add "float:right or left".

Currently, I need to add an inner section and make 3 cols.  (or just add 3 cols in parent section ).
And add 33.3% each in inner section.

But it's a little bit problem now. 

1. When browser is smaller and become narrow, then it jams the 3 icons.  

2. the bell icon needs to be showing when you logged in only.
If you have to make 3 columns then there will be an empty column when you are not login.

I understand that it might be a case for these specific issues.

But when you add buttons, you just want to make the arrange beside of each buttons. But it's not possible. You need to make columns.

Is there anything I have missed? or any solution for it?

Thank you for the best of best plugin in WordPress,

**Comment by bainternet** [comment]
@pulla 	

Specifically for icons, you can use the Icon list widget to display them side by side( inline arrangement). But as for showing/Hiding elements based on user/guest status its something that we don't support yet. (follow #4246 )

But your best would be to create a custom widget with that functionality.

thanks

**Comment by nicholaszein** [comment]
Hi, the ability to align widgets inline was implemented in version 2.5, and with version 3.6 Flexbox Containers were introduced and are now, with version 3.20 fully functional.

The ability to show/hide elements based on logged in/out conditions was also added in version 3.19, and enhanced in version 3.20.

You can learn more about Flexbox Containers in the [Help Center](https://elementor.com/help/elementor-editor/creating-a-page-layout/flexbox-containers/).

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
