### ISSUE TITLE
Compatibility of Smart Offers?

### ISSUE THREAD

**Issue by mansi-shah-2248** [pojome/elementor#6343]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
This is continuation of [Compatibility with Smart Offers](https://github.com/pojome/elementor/issues/5169)

## Steps to reproduce

I'm getting the error shown in screenshot here: https://docs.elementor.com/article/245-preview-could-not-be-loaded
I also tried steps mentioned in the same article but it is not loading.

Can you let me know how to troubleshoot further? We would like our plugin to work with Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by **me** and reference this issue.

thanks.

**Comment by mansi-shah-2248** [comment]
Hi,

Just wanted to let you know, Smart Offers is now compatible with Elementor. [Read more](https://www.storeapps.org/smart-offers-elementor-integration/).

Thank you for your help.
