### ISSUE TITLE
Hello..I cant make it work , button read more or less in same page 

### ISSUE THREAD

**Issue by Spilver2050** [pojome/elementor#6344]
i cant configure the read more button on exist page on elementor..i find one guy she/he explain the provlem exacly..i have the same provlem..and i think a lot ppl more.

I have a large number of items that I am displaying in columns on a page. Some items are very short and fit fine. Some items have a lot of text and are just to long. I realize I can create a separate page and let people ink to that extended page but I don’t want to create 25 more pages. I would like to display the first 50 words of the text and then have a “Read More” button show at the bottom. When someone clicks the “Read More” button the column would just expand and show the extra text. Is this possible in Elementor.

![untitled](https://user-images.githubusercontent.com/45594705/49440877-8d8d3c80-f7cd-11e8-97fb-123de33b634d.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
