### ISSUE TITLE
Repeater control "condition" based on external control

### ISSUE THREAD

**Issue by dtmgs** [pojome/elementor#6345]
###### Please refer, below code snippet. *condition attribute not working in REPEATER* 

	$this->add_control( 'use_icon', array(
		'label'        => 'Enable Icon',
		'type'         => Controls_Manager::SWITCHER,
		'default'      => 'yes',
		'return_value' => 'yes',
	) );

	/**
	 *  Condition attribute works good
	 */
	$this->add_control( 'icon_position', array(
		'label'     => 'Icon Position',
		'type'      => Controls_Manager::SELECT,
		'default'   => 'inline',
		'condition' => array( 'use_icon' => 'yes' ),
		'options'   => array(
			'inline'  => 'Inline',
			'stacked' => 'Stacked',
		),
	) );

	$this->add_control( 'tabs', array(
		'type'   => Controls_Manager::REPEATER,
		'fields' => array(
			array(
				'type'  => Controls_Manager::TEXT,
				'name'  => 'title',
				'label' => 'Title',
			),
			/**
			 * Same condition attribute not working here.
			 */
			array(
				'name'      => 'icon',
				'label'     => 'Icon',
				'type'      => Controls_Manager::ICON,
				'default'   => 'fa fa-home',
				'condition' => array( 'use_icon'  => 'yes' ),
			),
		)
	) );

**Is there any possibilities of filtering a control ( named = icon ) located in repeater , based on control ( named == use_icon )?**

**Comment by bainternet** [comment]
@dtmgs 	

Currently, this feature is not supported, meaning you can't have a repeater field conditon based on an external field.

Thanks for the feedback.

**Comment by bainternet** [comment]
@dtmgs

I don't see this being implemented anytime soon.
