### ISSUE TITLE
Elementor Editor Panel Unexpected Scroll with Wacom Device

### ISSUE THREAD

**Issue by bbdstar** [pojome/elementor#6350]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor Editor Panel scrolls unexpectedly when hovering over panel with Wacom graphics tablet. The issue is with using an outdated version of perfect-scrollbar.js. 

## Steps to reproduce
Any installation of Elementor
1. Edit Page/Post/anything with elementor
2. Hover over Elementor Editor Panel with Wacom device
3. Scrolling starts on hover and you can't get to top or bottom elements.

Fix is in here:
[perfect-scrollbar.jquery.min.txt](https://github.com/pojome/elementor/files/2646867/perfect-scrollbar.jquery.min.txt)

You need to check for pointer type === 'pen'

`function p(t){
	if (t.pointerType && t.pointerType === 'pen' && t.buttons === 0) {
		return false;
	}
	if (t.targetTouches && t.targetTouches.length === 1) {
	    return true;
	}
}`

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@bbdstar 	

can you please provide more details like what device model, what browser and version?

better yet can you provide a screen capture?

**Comment by bbdstar** [comment]
It happens on every browser, with 2 type of tablets I own. This has been occurring ever since I started using Elementor, over a year ago.

The issue lies with Elementor using an outdated version of perfect-scrollbar.

As you can see this is a hover only. No clicking.

[Screen Recording 2018-12-06 at 10.25.25 am.zip](https://github.com/pojome/elementor/files/2651151/Screen.Recording.2018-12-06.at.10.25.25.am.zip)

**Comment by bainternet** [comment]
Thanks,

We can see that.
