### ISSUE TITLE
Feature request: Action links also connectable with images

### ISSUE THREAD

**Issue by JohnMulderFrance** [pojome/elementor#6351]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Really like the new action links in Elementor Pro. Just saw they can be used with both buttons as icons, but not with an image. I would really like if action links could also be associated with images.

Thanks,
John

**Comment by bainternet** [comment]
@JohnMulderFrance 

You can already use Actions links (a.k.a Contact URL) with images:

![igrwozy](https://user-images.githubusercontent.com/660572/49508059-76605480-f88a-11e8-830c-1fffe26588d0.png)


thanks for the feedback.
