### ISSUE TITLE
Dynamic Tag causes null pointer exception or no rendering

### ISSUE THREAD

**Issue by andreasnrb** [pojome/elementor#6352]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
**Special case scenario.** If a Dynamic tag is added but not properly added on editor rendering it causes a null pointer exception.
https://github.com/pojome/elementor/blob/51107dd9ba29cf9f5ed19c002d848780e65e0b31/core/dynamic-tags/manager.php#L372

## Steps to reproduce
Add a dynamic tag on editor but fail to add on ajax rendering request.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Solution
Add a check for null. Potentially write error message when using WP_DEBUG.

## Environment

<details>
<summary>System Info</summary>
* Using Elementor.
* Default theme.
* Custom plugin
</details>

**Comment by bainternet** [comment]
@andreasnrb 	

We can't replicate, is this a custom dynamic?

**Comment by andreasnrb** [comment]
Yes its a custom dynamic. It only occurs if for some reason the registering
of the tag fails in the ajax rendering phase. Simple null check in the
function referenced solves it. Since create_tag can return null its just as
good to check for null.

Den tor 6 dec. 2018 09:59 skrev Raz Ohad <notifications@github.com>:

**Comment by bainternet** [comment]
[**@andreasnrb**](https://github.com/andreasnrb) commented on [Dec 6, 2018, 1:01 PM GMT+2](https://github.com/pojome/elementor/issues/6352#issuecomment-444833786 "2018-12-06T11:01:00Z - Replied by Github Reply Comments"):
> Yes its a custom dynamic. It only occurs if for some reason the registering
> of the tag fails in the ajax rendering phase. Simple null check in the
> function referenced solves it. Since create_tag can return null its just as
> good to check for null.

Thanks for clarifing, that's what we figured beacuse if you create your dynamic correctly you are not suppose to get the null pointer exception.

**Comment by bainternet** [comment]
@andreasnrb 

Thanks again, closing.
