### ISSUE TITLE
Enable or Disable Elements

### ISSUE THREAD

**Issue by fbc** [pojome/elementor#6353]
It would be nice to enable or disable elements as needed. For Example: Enabling the Summer pricing table and disabling the Winter pricing table or temporarily enabling a section that says: Due to weather conditions we will not be operating until X date.

**Comment by bainternet** [comment]
I merged this issue with  #4246 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
