### ISSUE TITLE
Header/footer script injection

### ISSUE THREAD

**Issue by diegovogel** [pojome/elementor#6355]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I often find myself needing to insert custom scripts or resources into my site header/footer. Like for adding a Google font that I can reference in custom CSS or for writing some JS to do something. It would be great if Elementor Pro had a spot to put this stuff, like in Tools or something. Then I wouldn't need to download a plugin just for this.
To me this would be the last piece of the puzzle that would make Elementor Pro a truly all-in-one theme builder.

**Describe the solution you'd like**
I would like to have a header/footer script injector in Elementor >> Tools.

**Describe alternatives you've considered**
I currently install a header/footer script plugin to do this. It works fine, but it would be nice if I didn't have to install another plugin just for that. Header/footer script injection seems like a simple feature that would add a lot of value to Elementor.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
