### ISSUE TITLE
Elementor Templates Condition Page, Add Unique Identifier

### ISSUE THREAD

**Issue by rudeone** [pojome/elementor#6362]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have a site with > 50 Pages. There are several pages with the same name in different hierarchy. When trying to assign the right pages in the conditions window, i have to go by try and error. or i have to change the page title temporarily so i know which is which. 

**Describe the solution you'd like**
maybe add the full URL of the page on hover or below. or add the parents page name.

**Describe alternatives you've considered**

**Additional context**
Screenshot below
![2018-12-06 13_27_34-elementor _ nieswandt 2 col](https://user-images.githubusercontent.com/807843/49585509-d45e6c00-f95e-11e8-8718-26621fca931a.png)

**Comment by bainternet** [comment]
Thanks tweaked in Elementor Pro v2.2.5
