### ISSUE TITLE
Coming Soon page not being properly redirected if "wp_reset_query" gets called in the middle of the way

### ISSUE THREAD

**Issue by adrianosferreira** [pojome/elementor#6365]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I've detected this issue while fixing a compatibility issue between WPML and Elementor. If you have the Coming Soon feature active and somewhere in the code (even in a template file such as `single.php`, as long as it gets called after the `template_redirect` hook) calls the `wp_reset_query`, then the Coming Soon page is not displayed at all.

## Steps to reproduce

- Enable Coming Soon feature
- Open the `single.php` file of your current theme and add this:

```php
get_header();

wp_reset_query();
```
- Access the site as a visitor and notice that the Coming Soon page is not displayed

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
https://github.com/pojome/elementor/pull/6366#issuecomment-445531522

**Comment by adrianosferreira** [comment]
https://github.com/pojome/elementor/pull/6366#issuecomment-445782543
