### ISSUE TITLE
Collision with BigCommerce

### ISSUE THREAD

**Issue by topher1kenobe** [pojome/elementor#6368]
## Description

Editing any post type with the editor (post, page, product, etc) with both BigCommerce and Elementor Pro (NOT the free one) causes a fatal error.

<b>Fatal error</b>:  Uncaught Error: Call to a member function frontend_includes() on null in /home/natur314/kates.naturenurturecreative.com/wp-content/plugins/elementor-pro/modules/woocommerce/module.php:207

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
