### ISSUE TITLE
When Wordpress Interface is in Russian Language - Elementor editro change Brackets "text" to «text» 

### ISSUE THREAD

**Issue by KoshaK0** [pojome/elementor#6369]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Website is using Russian Langiage for Admin Panel and User Profile. When Editing the Post and typing "text" in brakets, wordpress changes them to «text» 
This looks like commont prublem with WordPress, well it's not a problem, it's usual thing. But I would like to remove such behavior, I want to write "backets" and see them the way I have typed them. 

Using the PHP code inserted into functions.php or Snippets Plugin I have managed to fix it on pages and post with WerdPress editor, but it's still doing the same for the pages edited with Elementor. I belive the Filter used blow in the code need to be applied to Elementor editor aswell, but I don't know which one to use. Please advice.
the code used:
```
//Remove in Post and Pages
remove_filter('the_content', 'wptexturize');

//Remove in Title
remove_filter('the_title', 'wptexturize');

//Remove in Comments
remove_filter('comment_text', 'wptexturize');
```

## Steps to reproduce

Set Wordpress to Russian Language. Type the text using "brakets"

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
not requared - not system dependand...
</details>

**Comment by bainternet** [comment]
@KoshaK0 	

You can use the native WP `run_wptexturize` filter to disable it ex:

```PHP
add_filter( 'run_wptexturize', '__return_false' );
```

thanks.
