### ISSUE TITLE
Is it possible to use Elementor editor without wordpress ?

### ISSUE THREAD

**Issue by francoisandre** [pojome/elementor#637]
Hi,

My question is surely stupid.
Elementor is really impressive and I'd like to embed in non wordpress application.
Is it possible to use javascript widgets such as editor.js in a neutral environnement,  mocking wordpress ajax services ?
Are you working on splitting more clearly your widgets and the wordpress API ?
Do you know if someone has already done such a thing  ?

Great work.

François

**Comment by joshmarom** [comment]
Hi @francoisandre. Thank you for your interest in Elementor.

Elementor is a WordPress plugin and will not work on a different environment.

Check out http://grapesjs.com/ it is still in alpha but looks very promissing.

**Comment by bhanukaran** [comment]
Hi Joshmarom,

You are a savior. It's amazing solution. I am gonna use it in my web application.

Thanks a ton.

**Comment by becauro** [comment]
Hey, guys!

I found the [tooljet](https://www.tooljet.com/) project interesting as well.
It's FOSS.
