### ISSUE TITLE
Add New Custom HTML Tag for Section

### ISSUE THREAD

**Issue by UsmanShahzad** [pojome/elementor#6374]
Hi,
How can i add new **custom html tag** in **html tag** dropdown for section? e.g `<fieldset>`

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
