### ISSUE TITLE
Toolset Views 2.7 Content gone away on frontend

### ISSUE THREAD

**Issue by DrMohamedGamal** [pojome/elementor#6377]
When I update to toolset views 2.7 the pages using views widgets content can't be displayed on the frontend
while everything goes well on building !!
I cleaned the cache , tried from another browser , proxy , everything but no change
Header and footer loads well but content area not displayed or even loaded 

I deactivated all plugins except for 
Toolset + Elementor + Elementor Pro
But nothing new

**Comment by bainternet** [comment]
@DrMohamedGamal 

This seems like something you should let Toolset guys know about.

thanks.
