### ISSUE TITLE
Custom Footer and Header 

### ISSUE THREAD

**Issue by nguyendttn** [pojome/elementor#6379]
Hi,
I'm WordPress developer and I'm using Elementor in my theme. Some customers are facing an issue with Custom Footer & Header with Elementor. 
When they use Custom Header only, the Footer is gone. I checked your code and I'm seeing 
`if ( $overwrite_header_location || $overwrite_footer_location ) { 
....
}`
under elementor-pro -> modules -> theme-builder -> class  -> theme-support.php
Could you please replace
OR conditional with And Conditional. I explained it to my customers here https://documentation.wilcity.com/knowledgebase/why-menu-does-not-appear-when-using-elementor-footer/ You can read it to understand my question more.
Thanks

**Comment by bainternet** [comment]
@nguyendttn 

This is how Elementor Pro works, unless you register and define in your theme both header and footer locations, the theme builder will take control over both to avoid breaking the HTML. So to make your theme compatible with elementor and allow to overwrite only header or footer use the [Theme location API](https://developers.elementor.com/theme-locations-api/)

thanks

**Comment by LeonSkrilec** [comment]
See https://github.com/elementor/elementor/issues/15391 for my solution.
