### ISSUE TITLE
Hide header option in editor mode

### ISSUE THREAD

**Issue by mr-sparks** [pojome/elementor#6385]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mr-sparks** [comment]
**Q: What problem is your feature request going to solve? Please describe.**

A: In some design cases, for example, if you manually set your header to position absolute or fixed and a high z-index, which is necessary for certain types of websites, the page content in the editor flows below it. This is of course technically perfectly logical but makes it impossible to use the elementor editor for content that is now "below" the header. Mostly prominent this comes when you edit elementor templates that only contain a little bit of content.

**Q: Describe the solution you'd like**

A: A simple checkbox or a button somewhere else, that shows/hides the header (or maybe even the footer as well) in editor mode. nothing more - but it would help a lot! 

**Q: Describe alternatives you've considered**

A: Currently one has to open the browsers developer mode, select the header item in source code and delete it, so it disappears and its possible to edit elements underneath it. Of course you can access the properties with the new navigator but you're working completely blind then. And most important: Clients without knowledge of source-code and browsers developer console, can't edit certain pages anymore..

**Q: Additional context**

A: I think there's an easy fix for this problem with a simple option to show / hide the header. 
![example](https://user-images.githubusercontent.com/4228061/49699839-93708c80-fbd6-11e8-897c-a181637fd06b.jpg)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, you can use the Following bookmarklets to toggle the visibility of the header and footer in the editor:

Toggle Header:
```
javascript:(function()%7Belementor.%24previewContents.find(%20'.elementor-type-header'%20).toggle()%7D)()
```

Toggle Footer:
```
javascript:(function()%7Belementor.%24previewContents.find(%20'.elementor-type-footer'%20).toggle()%7D)()
```

![screen recording 2018-12-10 at 15 48 45](https://user-images.githubusercontent.com/660572/49736679-73eb6980-fc93-11e8-98b7-7ac22e50bf1f.gif)


Thanks for the feedback.
