### ISSUE TITLE
Right Click Copy And Paste Elementor Panel Elements 

### ISSUE THREAD

**Issue by zrk4444** [pojome/elementor#6387]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Many times I'll have a semi buggy and/or bad user experience with Elementor's drag n' drop functions. Example, I'll try to drag and drop elements from the Elementor panel into tiny columns, and sometimes, it just doesn't want to work. Other times, it'll take multiple times until I can get an element placed.

**Describe the solution you'd like**
I'd like to be able to right-click and Copy Elements straight from the panel itself and proceed to paste them where ever I see fit. This will increase the accuracy of applying Elements from the panel and will better the user experience with Elementor.

**Describe alternatives you've considered**
I haven't considered any except this one.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by black-eye** [comment]
+1
