### ISSUE TITLE
Section Entrance Animation runs twice.

### ISSUE THREAD

**Issue by h71** [pojome/elementor#6389]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Section Entrance Animation runs twice in front-end if the page load takes long time.
I have searched  issues to find related issues, but they have no clear description. Please see **Steps to reproduce** to see how you can replicate it.

In other word, i think it runs again after image loads.

## Steps to reproduce

1. Add a section with any custom widget on it.
2. Add a background image for section in: Edit Section->Style->Background->Image. (Is is great if you are able to use a big image that takes more time to load)
3. See the preview with a slower internet connection. Or use Chrome dev tools to set Network throttling to slow **3G**. (Clear cache before test)
4. See the preview or saved page in front-end.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

```					

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.34 (Win32) OpenSSL/1.1.0h PHP/7.2.8
	MySQL version: mariadb.org binary distribution v5.6.39-83.1
	PHP Version: 7.2.8
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0
	Site URL: http://localhost
	Home URL: http://localhost
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 40M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Twenty Nineteen
	Version: 1.0
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.3.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.2.4
		Author: Elementor.com


== Debug ==
	Errors: There are no errors to display
				
```

</details>

**Comment by bainternet** [comment]
@h71 

We can't replicate,
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
