### ISSUE TITLE
Some elements not loading in Safari

### ISSUE THREAD

**Issue by NetworklinkHaarlem** [pojome/elementor#6394]
Hi!

I noticed 3 elements doesn't show up in Safari. They do in Chrome, Firefox and IE. 
I can't figure out what the problem is:(
Can you help me out?
Attached are the screenshots of the website in Safari, you see the elements are missing..
Below that are the same places of the website, but in Chrome.
The url is https://networklink.nl

Many thanks in advance!

![whatsapp image 2018-12-10 at 12 38 32](https://user-images.githubusercontent.com/38694326/49752557-fe8e9180-fcb0-11e8-94aa-8930ea62ac7e.jpeg)
![whatsapp image 2018-12-10 at 12 38 34](https://user-images.githubusercontent.com/38694326/49752558-fe8e9180-fcb0-11e8-82c8-861158bea625.jpeg)
![whatsapp image 2018-12-10 at 12 38 33](https://user-images.githubusercontent.com/38694326/49752559-ff272800-fcb0-11e8-8eae-294ea892a2b8.jpeg)

![example 3 in chrome](https://user-images.githubusercontent.com/38694326/49761542-b75fcb00-fcc7-11e8-89a3-1d70f1bad77b.JPG)
![example 1 in chrome](https://user-images.githubusercontent.com/38694326/49761543-b75fcb00-fcc7-11e8-858c-70c3c14bb46d.JPG)
![example 2 in chrome](https://user-images.githubusercontent.com/38694326/49761545-b75fcb00-fcc7-11e8-92d6-501f22ea68a2.JPG)

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
