### ISSUE TITLE
Box Shadow Control not working.

### ISSUE THREAD

**Issue by rafiul** [pojome/elementor#6397]
## Description
- [ ] I add a  box shadow control in my plugin but that is not working.

**My code is given below:**

```
$this->add_control(
	Group_Control_Box_Shadow::get_type(),
	[
		'name' => 'box_shadow',
		'label' => __( 'Box Shadow', 'plugin-domain' ),
		'selector' => '{{WRAPPER}} .wrapper',
	]
); 
```
## Screenshot
![Image of boxShadow](https://drive.google.com/thumbnail?id=1XiEjFjs8cfLfdzpWOkKQvzR41ddtpwKc 
)

## Environment

<details>
<summary>System Info</summary>

- WordPress 4.9, 5.0
- Elementor Page Builder 2.3.4 (Latest)

</details>

**Comment by bainternet** [comment]
@rafiul 	

We can't replicate, please provide more information.

**Comment by rafiul** [comment]
@bainternet  I developed a plugins/widget, there is lots of control like text shadow, typography, colors etc. everything is working perfect.  Now I want to add **box shadow control** on my widget.  I use a code which I given on my first comments. Problem is on my given screenshot. It is show text box only. 

thanks

**Comment by rafiul** [comment]
I solved my problem

Add 
` $this->add_group_control(`

instead 
`$this->add_control(`

**Comment by DeoThemes** [comment]
I've also had the same issue until I discovered this thread. It's a typo in documentation, and it's still not fixed.

**Comment by latheeshvmv** [comment]
Need to fixed in doc

**Comment by rafiul** [comment]
> I've also had the same issue until I discovered this thread. It's a typo in documentation, and it's still not fixed.

Yes it's a typo in documentation 👎

**Comment by shilo-ey** [comment]
Thanks! we've updated it.
