### ISSUE TITLE
Uncaught TypeError: Cannot read property 'i18n' of undefined

### ISSUE THREAD

**Issue by dtbaker** [pojome/elementor#6398]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

On WordPress network mode, an editor cannot edit any content and receives a javascript error. The page just loads and loads. Super administrators can edit the page just fine.

![image](https://user-images.githubusercontent.com/543073/49795838-c22d6500-fd86-11e8-9226-226bd4d393ce.png)

The error is

```
Uncaught TypeError: Cannot read property 'i18n' of undefined
```

This error is caused because the javascript is trying to read the finder/connect i18n variables. These are not available because the components only appear for users with `manage_options` permissions:

```
if ( current_user_can( 'manage_options' ) ) {
			$this->add_component( 'finder', new Finder() );
			$this->add_component( 'connect', new Connect() );
		}
```

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

WordPress multi site
Elementor

**Comment by bainternet** [comment]
@dtbaker 

can you provide steps to replicate and more detail, because we can't replicate.

**Comment by dtbaker** [comment]
@bainternet it might be to do with our hosts custom security policy around multisite, it messes with roles a bit. If I can replicate this on a normal host then I'll re-open it.
