### ISSUE TITLE
Using Elementor with front page widget locations in Genesis child themes?

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#64]
(Edit)

What about adding Elementor widgets to widget locations in a theme?
Meaning use it as a page builder and as a widget builder like https://wordpress.org/plugins/so-widgets-bundle/ It would have a nice double function. Elementor widgets would be available in multiple ways.

The thought is that Genesis has a lot of widget locations for the front page. Using Elementor to add widgets directly into the widget locations would be great.

An example from Genesis is the following tutorial I have been readjusting: http://easywebdesigntutorials.com/customizing-altitude-pro-genesis-child-theme/

It is a popular one page Child theme named Altitude Pro. It contains multiple front page widget locations and it contains multiple background images one can insert through the customizer. Insert the background images and these show up in the front page widget locations (as long as there is a widget in the specific location).

It would be great to insert Elementor widgets into widget locations of the front page of Altitude Pro.

This would mean having an additional tabbed panel inside the Appearance -> widgets settings.
Which could say Elementor. Click it to see the various widgets available. Click or drag it to a widget location in whichever theme your using.

(A use case.)
Today many of the Genesis child themes have a documentation for setting up the demo content. Usually a text widget using html for creating a button, links and more. Not easy for a beginner to get into. It would be a lot easier to use Elementor to add widgets instead of using text widgets.

**Comment by arielk** [comment]
As I wrote to you in #306 - we're working with a different method, you can read more about this here: https://docs.elementor.com/article/56-content-area-not-found
