### ISSUE TITLE
write a blog

### ISSUE THREAD

**Issue by acrnium** [pojome/elementor#640]
How to configure a shared template child theme for WordPress records? Now write at the top, the pattern on the bottom. геонис.рф
http://savepic.ru/11547943.jpg

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
