### ISSUE TITLE
Better text excerpts content selection

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#6400]
**What problem is your feature request going to solve? Please describe.**
When working with archive or post elements, the text excerpts are very important for many circumstances. But when also styling the post single template with Elementor, the text excerpts takes whatever it can get from the post, starting from above.

That means, that the text excerpts are often just repeating the post title, because they are the first text element in the post. This is sadly not a very good handling. 

**Describe the solution you'd like**
Not 100% sure, but maybe an option for the text excerpts to ignore formats like H1, H2, H3 and so on, also "elementor-heading-title" and to jump directly into the real content. 

**Describe alternatives you've considered**
Alternative would be to set a text element in the post template as the "text excerpt" which will be shown in archive and post elements text excerpts.

**Comment by bainternet** [comment]
@Luxamman 	

The Excerpt follows and tries to act as close to the native excerpts as possible and this is the exact behavior of the "auto" excerpt (take the first xx from the post content).

So you can always set an excerpt (avoid using the auto-generated).

I don't see that changing anytime soon.


Thanks.
