### ISSUE TITLE
Tabs Widget miss-behaving when conforming to mobile Device

### ISSUE THREAD

**Issue by Rockpointpro** [pojome/elementor#6402]
There is an issue when viewing the tabs widget on mobile devices - as normal, the tabs widget automatically changes to an accordion when viewed on a mobile device - - but there is a problem.. . .
When selecting a different tab from the one being viewed the Widget should navigate you to the TOP of the selected tab - but it doesn't -it seems to dump the viewer in some random place on the page leaving them to scroll up and down to find the top of the newly selected tab content.

This needs to be addressed - its very annoying for any user

(Tested on a range of recent iphones)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by Rockpointpro** [comment]
## Prerequisites


- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.


## Description



## Steps to reproduce


- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment - iPhone models - all systems - all browsers

**Comment by Rockpointpro** [comment]
Okay i might not be a programming genius, I'm just a simple designer - but I don't know why you have treated my request so offhandedly - why is it closed?? who closed it and why? it was a simple cry for help from a beginner in this field.

Why are you so mean - behaving like a Hitler ?
