### ISSUE TITLE
Figure Margin: 0 - issue with shortcode and wp-widgets

### ISSUE THREAD

**Issue by diggeddy** [pojome/elementor#6403]
This fix does not address problems with content added via shortcodes or wp-widgets. It would make sense to exclude those element also.

https://github.com/pojome/elementor/pull/5778/commits/9e71cd23834d1d3448c9723e4f158d5029bc4200

_Originally posted by @arielk in https://github.com/pojome/elementor/pull/5772#issuecomment-423251956_

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

hard to understand what you mean.
