### ISSUE TITLE
Feature Request - Add Globe icon or website icon to Social Icons

### ISSUE THREAD

**Issue by ajohnson88** [pojome/elementor#6405]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Problem: 
We would like to provide a link to a website with a social icon under our team members profile to sit next to their linkedin and github (ect.) icons.  It would be great to have a generic globe or www icon available for this button.

**Comment by arielk** [comment]
I added link & globe icons for the next version,

Thanks for your feedback!
