### ISSUE TITLE
Elementor Template Editor crashes after deleting taxonomie

### ISSUE THREAD

**Issue by julian-stark** [pojome/elementor#6408]
I created a custom taxonomy via CPT UI.
I used it in an Elementor template.

Then I deleted the taxonomy: Now Elementor stops working for the template if the taxonomy is still being used.

The template can only be "rescued" by: Again creating the same taxonomy, deleting it inside the template and then deleting it again.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
