### ISSUE TITLE
Elementor Pro 2.3.0 Beta Release

### ISSUE THREAD

**Issue by bainternet** [pojome/elementor#6411]
Hi Elementor Testers,

Elementor Pro 2.3.0 Beta has been released and includes a long list of updates and new features - including new integrations into 3 extremely popular platforms: Slack, Discord & MailerLite.

For the past recent releases, you've helped locate several issues, and I'd like to thank you for your help and support.

I hope we can do the same for this beta release of Pro v2.3.0, and ensure a safe and stable official release.

Here are the new features that have been introduced:

### Slack Integration
![roywmok](https://user-images.githubusercontent.com/660572/49863470-082b0d00-fe09-11e8-85d0-28d414a91b8b.png)

The benefit of using the Slack integration is when users submit a form, you can be notified about it through slack and all submissions can be gathered in one place.

Like all integration, connecting Slack to Elementor forms is super-easy and intuitive.

### Discord Integration (#4218)
![roywmok](https://user-images.githubusercontent.com/660572/49863928-09a90500-fe0a-11e8-9a1c-7f5e7041270f.png)

If you are one of the "Discord is better than Slack", Then we have you covered as well. Much like the new slack Integration, you can be notified about it through discord and all submissions can be gathered in one place.

### MailerLite (#4462)
<img width="1543" alt="screen shot 2018-12-12 at 12 40 47" src="https://user-images.githubusercontent.com/660572/49865335-59d59680-fe0d-11e8-8d31-451e1cc9c29e.png">

MailerLite is an email marketing platform that seems to be quite popular among Elementor users and which has a very nice set of features.

### Other Updates:

* a new `elementor_pro/utils/get_public_post_types` filter hook to allow non-supported post-types to be added to Elementor (#5900), Usage example:

```PHP
/**
 * Add lifterlms lesson post type support
 */
add_filter( 'elementor_pro/utils/get_public_post_types', function() {
	$post_types['lesson'] = 'Lessons';
	return $post_types;
} );
```

* Added support for `loop_start` and `the_content` based filter for single templates #6173).
*
 
 
### How to Install Beta Version
If you still haven't enabled beta testing in Elementor, please follow these steps:

1. Go to Elementor > Tools > Versions
2. Enable the beta tester feature
3. Go to Dashboard > Updates and update to the latest beta version.
This will get you testing the new Elementor Pro 2.3.0 Beta

Many thanks for your support and help!
For bugs reports **Only**, please reply with a comment below!

Cheers,

**Comment by brunocerq** [comment]
Hi there,
Just tested it, and I can confirm the issues I previously had with "the_content" on single templates not allowing the injection of ads with hooks is fixed in this beta version.
This issue was reported on these posts: #6173 #5800 
I'm glad this issue has finally been addressed and covered.

**Comment by arielk** [comment]
Elementor 2.3.0 is now live.
