### ISSUE TITLE
Exclude a widget from Elementor widgets

### ISSUE THREAD

**Issue by hoseinrafiei** [pojome/elementor#6414]
Hi,

Can someone please read this thread and reply it?!
https://wordpress.org/support/topic/exclude-a-widget-from-elementor-widgets/

I want to exclude one of my plugin widgets from Elementor widgets.
I already tried following code but it doesn't work.

`add_action('elementor/widgets/widgets_registered', function($widgets_manager)
{
	$widgets_manager->unregister_widget_type('name_of_my_widget_class');
});`

Regards,
Hossein Rafiei

**Comment by bainternet** [comment]
@hoseinrafiei
