### ISSUE TITLE
Form Element: Add the sender email address to the E-Mail 2

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#6416]
**What problem is your feature request going to solve? Please describe.**
The problem is, that you can send emails (actions after sending) to specific recipients with the "Form" element, but you cannot send an email to the one, who just send you the inquiry. 

This is often helpful, because you can confirm the inquiry again via email. 

**Describe the solution you'd like**
You should be able to choose the inquiry used email-address to send them a confirmation.

**Comment by bainternet** [comment]
@Luxamman 	


You can, just use the field shortcode as the `To` address , ex: `[field id="email"]`

thanks.

**Comment by Luxamman** [comment]
Thanks, still I would suggest to implement it in a way, because this is very common and as for my understanding of Elementor, not the user-friendy way. At least in the description nearby a hint, that the shortcode is not only working in the text-field, but also in other fields - with you example.

Thanks a lot!
