### ISSUE TITLE
All  Elementor Icons Missing/Showing Squares after Updating to 2.2.5 & WP 5.0

### ISSUE THREAD

**Issue by Zach-Toth** [pojome/elementor#6419]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After updating a development site to Wordpress 5.0, updating Elementor to 2.2.5 then updating the Woocommerce database, all icons related to Elementor are missing and just displaying squares. Icons are missing from icon widgets, social icons and even the edit with Elementor button in the admin tool bar is missing its icon. All other non-Elementor related icons are displaying fine. I have tried deactivating all plugins, reverting back to WP 4.9.8, reinstalling Elementor and Elementor Pro and switching themes with no success. 

![elementor-icon-bug-screenshot](https://user-images.githubusercontent.com/32491990/49896313-978bec80-fe18-11e8-9644-fd23a24aa6d2.png)

## Steps to reproduce

1) Updated to Wordpress 5.0
2) Update Elementor & Elementor Pro to latest versions
3) Update Woocommerce database

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above. (The bug has never gone away since it arose)
^ I have not been able to get Elementor icons displaying again even after deactivating all plugins, reverting back to WP 4.9.8, reinstalling Elementor and Elementor Pro or switching themes. 
## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: (Ubuntu) v5.6.32
	PHP Version: 7.1.24-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0
	Site URL: https://newheadwink.flywheelsites.com
	Home URL: https://newheadwink.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Active

== Theme ==
	Name: Headwink Child Theme
	Version: 1.0.0
	Author: Toth Digital
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.6.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

== Active Plugins ==
	Astra Pro
		Version: 1.6.7
		Author: Brainstorm Force

	Elementor
		Version: 2.3.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.2.5
		Author: Elementor.com

	WooCommerce
		Version: 3.5.2
		Author: Automattic


== Debug ==
	Errors: 
		TypeError: Cannot read property 'currentView' of undefined
			at https://newheadwink.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.2 - 2:250400
			2018-11-28 17:52 +00:00
			x 2 times

				
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@Zach-Toth 	


We can't replicate, 
Please make sure you have no loading errors (404) in your console.

and let us know.

**Comment by Zach-Toth** [comment]
Turns out it was my CDN somehow blocking Elementor from calling the font awesome style sheet. 

Disabling and re-enabling the CDN fixed the issue.

**Comment by BilalAmeen-dev** [comment]
I am facing the same problem with my three sites. Somehow, they were working perfectly fine, but after I started working on the pages, they are now showing errors. I am using WordPress 6.5.3 and Elementor 3.21.7 with the PRO version. The theme I am using is Astra. Additionally, I have the Elementor Header Footer and Happy Elementor Addons plugins installed on my site. Please help me identify the issue and provide guidance on how to solve it. Thank you.


<img width="805" alt="image" src="https://github.com/elementor/elementor/assets/70202335/564b708c-32e4-46c4-9538-1e4df5a1789c">

<img width="805" alt="image" src="https://github.com/elementor/elementor/assets/70202335/2bfc25a7-965f-4540-bb6d-8c7e85233301">
