### ISSUE TITLE
Newbie.  time estimate

### ISSUE THREAD

**Issue by leonardelem** [pojome/elementor#642]
Sorry to bother.  i am a newbie, have not used wordpress before.  

i do not sell websites or design, just looking for way to design my own website.

Can someone please estimate how much time it might take me to redesign my site WeHelpDoctors.com  with Elementor.  I designed the current site with Wix.com [host and design].  Wix is not too difficult, but has problems, so i would prefer to switch.

I know someone will say "just try" but i am in a time pressed situation, and cannot afford to invest time, just to try.  thats why i would like an estimate for a newbie.  
[i ended up wasting a lot of time with programs that were sold on jvzoo that were time consuming, then ended up not being able to do what they were marketed to do.  and with Serif's webplus 8 [that requires a total new seperate design for mobile, and with xara, which is adaptive, not responsive]

thanks very much. i really appreciate your help.  i am open to buy your paid version when released.
As you can guess, i am frustrated.

**Comment by leonardelem** [comment]
addendum. my site is multipage and must stay that way.

the header must be able to be shown on all pages, and all pages must be updated when homepage header is updated

**Comment by arielk** [comment]
The issue you opened is more suited for our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports. Group members will be happy to help you with any questions of this type.

**Comment by leonardelem** [comment]
thanks, i did not know about that, just sent a request to join

i did not see on elementor.com about that, i tried finding any type of support

**Comment by arielk** [comment]
Right, we will improve it soon
