### ISSUE TITLE
Display Condition Singular does not get saved

### ISSUE THREAD

**Issue by rudeone** [pojome/elementor#6428]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
When creating a Template for Single Pages and selecting "Singular" as Display Condition it gets overridden by (standard?) all posts condition

## Steps to reproduce
as above

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
We can't replicate,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
