### ISSUE TITLE
Template Display Condition "Any Child of Page" not working with WPML Plugin (but Direct Child does)

### ISSUE THREAD

**Issue by rudeone** [pojome/elementor#6429]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I made translations with WPML for Child Pages like: "https://myurl.com/parent/child-page1
When switching languages i was wondering why it didnt display the proper Template. After testing i found out; it shows the desired template when using "direct child of" instead of the "any child of" display condition. so im pretty sure its a bug right?

hope this helps.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
Not sure what you mean, `Any Child of` must get an ID of a subject to test against, without it the rule is broken.

And without steps to reproduce, we can't really check.


`Direct Child of` -  accepts an ID of a parent to test if the current is a child of it.

`Any Child of` - when configured correctly, accepts an ID of a parent, then uses the native get_post_ancestors() WP function which retrieves the list of ancestors of the current post and then checks if the provided ID is in that list.

as for looking for translations or translating the conditions, that is not something we do but WPML.

thanks.

**Comment by rudeone** [comment]
how can i send you (privatly) access to a test system. i can give you more details and you can check for yourself?
