### ISSUE TITLE
Text & Headline Max Width

### ISSUE THREAD

**Issue by beauwalsh** [pojome/elementor#6430]
**What problem is your feature request going to solve? Please describe.**
One of the things to look out for in good typography is awkward rows and lines of text with orphans and widows—it's best to balance them in a way that looks more intentional.

Otherwise you end up with sentences that sometimes look like
this

So the text might only look good in some device widths. And you can't add line breaks to the text because if that box shrinks at all, the lines get even more jumbled up.

**Describe the solution you'd like**
If we could have a max-width px setting for text, it would give us a little bit more control on how it looks in various dimensions. It would need to be a setting with the responsive options so that we could change it especially if using em for font-size.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can set it via Custom CSS
Thanks for the feedback.

**Comment by Flipback8** [comment]
I agree you should be able to adjust the text width to whatever you want. The Oxygen Builder has this built in. How many people need to request this when it is something that should already exist in Elementor. Writing CSS to control text width on a page builder is silly.

**Comment by Flipback8** [comment]
CSS 
https://www.w3schools.com/cssref/pr_dim_max-width.asp
