### ISSUE TITLE
xml demo import is not working. 

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#6435]
Hello,

I am having the same issue as this one.

https://github.com/pojome/elementor/issues/4947
https://github.com/pojome/elementor/pull/4961

It has been working fine. But some how it didn't work. 
I have multisites and other were ok. But the last one I exported with wordpress import as xml.
And imported other site. But it doesn't work.

Do I need to setup some options as default? like style, inter or external style..etc?
Others solved this issue. But not me.
I feel like I missed something.

Thank you,

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
