### ISSUE TITLE
Reset Timer option for Countdown

### ISSUE THREAD

**Issue by blackgoku** [pojome/elementor#6436]
Timer reset option is necessary and is requested many times here, are you guys planning to bring it?
I cant install/buy a addon pack just for a reset option.
only Evergreen option was added few days ago, but reset option is also a need for a countdown element.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by rafaelfigueiredo-l** [comment]
+1 wanting this feature.

**Comment by BobbyRobillard** [comment]
Seriously, how is recurring not a thing... +1 for 100% needed
