### ISSUE TITLE
Animation issue: element flashes on entrance and animation duplicate

### ISSUE THREAD

**Issue by Ricarditu** [pojome/elementor#6439]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Hi!

I animated a section and it flashes before it animates. If I apply some delay, it appears for a while longer (maybe 200/300ms) and then it animates normal. But the fact of appearing before the animation completely spoils the effect.

Please, check the video at the link below:
https://drive.google.com/file/d/18KC9asJ-Muubb-mFXs4-GX1GSyPGwo-C/view

Another detail, I also enabled the scrolling effect to Sticky Upper and Effects offset s now, besides the previous issue, I also have a duplicate in the element animation.

Please, check the video at the link below:
https://drive.google.com/file/d/1cNfeBGjCv8pQlUIq7wcHlNFeM_WS8jft/view

I'm using:

WP 5.0.1
Astra 1.6.1
Elementor 2.3.5
Elementor Pro 2.2.5
all other plugins disabled
on Chrome 71.0.3578.80.

Thank you!

## Steps to reproduce

Animated this section and the issue started right away. About the animation duplicate, as soon as I enable the sticky and the effects offset, it happens.

You can check it at:
https://www.lsr.pt.94-126-173-37.publab.pt/

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.59-MariaDB-38.11
	PHP Version: 7.1.25
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.1
	Site URL: https://www.lsr.pt.94-126-173-37.publab.pt
	Home URL: https://www.lsr.pt.94-126-173-37.publab.pt
	WP Multisite: No
	Max Upload Size: 5 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: pt-PT
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.6.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_PT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.3.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.2.5
		Author: Elementor.com


== Debug ==
	Errors: 
		TypeError: Cannot read property 'currentView' of undefined
			at https://www.lsr.pt.94-126-173-37.publab.pt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.4 - 2:250776
			2018-12-11 00:59 +00:00
			x 3 times

		SecurityError: Blocked a frame with origin "https://www.lsr.pt.94-126-173-37.publab.pt" from accessing a cross-origin frame.
			at https://www.lsr.pt.94-126-173-37.publab.pt/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.2 - 2:99032
			2018-11-28 01:55 +00:00
			x 12 times

```
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
