### ISSUE TITLE
Custom Menu Cart Lightbox behaviour

### ISSUE THREAD

**Issue by guerre64** [pojome/elementor#6440]
Howdy Elementoreans!!

I am wondering if there is a way to make the Menu Cart lightbox appear when a customer clicks the Add To Cart button, as well as clicking the Menu Cart button? I just want the lightbox with the cart items to appear as soon as someone adds something to it.

Any help much appreciated.

Cheers,
Phil.

**Comment by bainternet** [comment]
You can trigger a click on the menu item once an item is added to cart, for example something like this:

```JS
$( document.body ).on( 'added_to_cart', function() {
 $( '.elementor-menu-cart__toggle .elementor-button' ).click();
});
```

**Comment by guerre64** [comment]
Howdy.

Thanks for your reply - so I'm assuming this code would be added to the child themes functions.php, is that correct?

If that's the case it doesn't seem to work :-(
