### ISSUE TITLE
Iconbox fully clickable hyperlink

### ISSUE THREAD

**Issue by debritde** [pojome/elementor#6442]
Hello,
it would be awesome if there is a feature to make the icon box fully clickable as a hyperlink.
I think it would be usefull if every element has this functionality.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
