### ISSUE TITLE
Zalo Social media icon

### ISSUE THREAD

**Issue by edbraz** [pojome/elementor#6443]
Hi folks, 

Can you include a Zalo social media icon in Elementor - it's the most popular messaging app in Vietnam.  I sent an email to elementor and they suggested also posting the feature request here on github - so I have!

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
I merged this issue with  #4430, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
