### ISSUE TITLE
Support Pods Color-Picker field for background color

### ISSUE THREAD

**Issue by evij-g** [pojome/elementor#6444]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Allow the user to change the background color of a particular section in nested layouts without touching the structure

**Describe the solution you'd like**
I would love to choose the Background-Color in combinatin with the Color-Picker PODS field.

**Describe alternatives you've considered**
Elementor Pro + ACF Pro supports it

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
