### ISSUE TITLE
Add hook for third party Form action handlers

### ISSUE THREAD

**Issue by verygoodplugins** [pojome/elementor#6446]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This feature would allow other plugins to register their own form actions to appear in the Actions After Submit dropdown.

**Describe the solution you'd like**
In the constructor for class Module (/elementor-pro/modules/forms/module.php) I'd like the line added

`do_action( 'elementor_pro/forms/add_form_actions', $this );`

**Describe alternatives you've considered**
I've tried quite a few ways to get the instance of the module and add the form action that way, without any success. If I've missed something and there's a way to do it without any changes in your code please let me know.

**Additional context**
[You can see here](https://wpfusion.com/documentation/lead-generation/elementor-forms/) what we've done with WP Fusion. Elementor already supports several marketing automation systems, but we support close to 30 of them, and we have customers who would like to connect their Elementor forms to platforms you don't yet support.

I know of other developers who would like this functionality as well.

**Comment by bainternet** [comment]
There is a hook there already:

`do_action( 'elementor_pro/forms/form_submitted', $this );`

and `$this` is the module instance which has the `add_form_action` method.

thanks

**Comment by verygoodplugins** [comment]
@bainternet That action is only triggered during the form submission process:

`if ( Classes\Ajax_Handler::is_form_submitted() ) {`

I'd like to be able to hook into form initialization and add my own Actions into the Actions After Submit dropdown.

This is the code I'm using in my own plugin file:

    function wpf_add_form_actions( $module ) {
	    $module->add_form_action( 'wpfusion', new WPF_Elementor_Forms() );
    }

    add_action( 'elementor_pro/forms/add_form_actions', 'wpf_add_form_actions' );

**Comment by designsbytrey** [comment]
+1 

Yes, I second that. ^^

WPFusion is absolutely essential for marketing automation and enabling this will open Elementor up to a TON more opportunities.  Please add this in! Thanks!

**Comment by Bannerman** [comment]
+ 1 
Please reopen this one

**Comment by jeremiahwolfe** [comment]
+1

**Comment by tristanleboss** [comment]
+1 I really need this too and this is super easy to implement by Elementor dev ;)

**Comment by verygoodplugins** [comment]
Thanks. That works.

Sorry you guys had to wait a month. We'll have Elementor Forms support out in the next update.

**Comment by bainternet** [comment]
We've updated our docs on adding a custom action
We've added an example to add Sendy as a form action integration https://developers.elementor.com/forms-api/custom-form-action/

**Comment by yoedy108** [comment]
> Again, no need for additional hooks,
> 
> ```
> add_action( 'elementor_pro/init', function() {
> 	\ElementorPro\Plugin::instance()->modules_manager->get_modules( 'forms' )->add_form_action( 'action_name', ActionClassInstance );
> });
> ```

I have the same issue as the OP, followed the custom-form-action doc, but it won't mention where to put this "elementor_pro/init" snippet.
Where should I put it?

**Comment by yoedy108** [comment]
> Again, no need for additional hooks,
> 
> ```
> add_action( 'elementor_pro/init', function() {
> 	\ElementorPro\Plugin::instance()->modules_manager->get_modules( 'forms' )->add_form_action( 'action_name', ActionClassInstance );
> });
> ```

I have the same issue as the OP, I followed the custom-form-action doc but it won't mention where to put the "elementor_pro/init" snippet. 
Where should I put it to initialize the action?

**Comment by verygoodplugins** [comment]
@yoedy108 There's an example at the bottom of https://developers.elementor.com/forms-api/custom-form-action/

The snippet needs to be in your main plugin file (or somewhere else outside of the form integration class)

**Comment by yoedy108** [comment]
Yeah that's exactly the doc I followed, but the example at the bottom only shows the snippet itself but there's no directions on where to put it...
I wrote just a custom webhook action class, not a new plugin, so when you write outside of the form integration class, it means that I can just put it in the functions.php and it should instantiate the custom action?

**Comment by verygoodplugins** [comment]
If it's not a custom plugin then you can put that part in your functions.php

**Comment by yoedy108** [comment]
Great thanks!
