### ISSUE TITLE
{{CURRENT_ITEM}} Not working in CSS selectors 

### ISSUE THREAD

**Issue by sinashamsizadeh** [pojome/elementor#6448]
Hi,
I have same problem like this issue https://github.com/pojome/elementor/issues/5300
Example code : https://prnt.sc/lv25ar
Example View: https://prnt.sc/lv25aj
Example css generated file: https://prnt.sc/lv25el
What is the problem. It's a bug or I made a mistake?

**Comment by bainternet** [comment]
@sinashamsizadeh 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As for your issue, the `{{CURRENT_ITEM}}` token is only used inside a repeater control. in a regular control, it has no meaning.

thanks.
