### ISSUE TITLE
Relationship between 2 custom widgets

### ISSUE THREAD

**Issue by CodeCurosity** [pojome/elementor#6451]
I have created two custom widgets and i have a text field in widget one, i would like to get the saved values of that field on widget two in a selector?

**Comment by bainternet** [comment]
@CodeCurosity 

Currently, this feature is not supported, Each widget is a standalone object, you can, however, play around with a JavaScript handler which will Identify that Widget One is in the page and update the settings of widget Two accordingly.

Thanks for the feedback.
