### ISSUE TITLE
Bug on search algo for Template Widget, "Choose template"

### ISSUE THREAD

**Issue by leocrespo** [pojome/elementor#6452]
Replicate the bug:

1) Create a section template with an unique misspelled word in the title like "girraffe". Save it. 

2) Open another elementor page and drag the Template widget.

3) On the "Choose Template" field, type "girraffe". You will see it bring up every template you have, instead of just one that contains the word you're looking for. 

This behavior is incorrect. The correct behavior is the one Elementor has in its Finder. Press Cmd+E to invoke Finder and type "girraffe". Only the correct section template will come up. This is the correct behavior. 

Please fix this for the next release.

**Comment by bainternet** [comment]
@leocrespo 	

This is the correct behavior, the templates in the Template widget are ordered by type to allow better grouping of the templates, which has nothing to do with the Finder functionality.

Now if you don't see your template there is a different issue, even a bug, but we can't replicate, so please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by leocrespo** [comment]
Templates in that search box do not follow any order whatsoever. Not alphabetically, not by type, and you can type “Jupiter” and it will return a template with a chocolate recipe. In fact, you can type anything and it will return all templates anyway. It is absolutely disfuncional.

**Comment by leocrespo** [comment]
We are probably talking of different areas. 
<img width="292" alt="template search" src="https://user-images.githubusercontent.com/1483902/50058823-c369e380-0132-11e9-837f-3771de39d69a.png">

This search box is utterly useless. The search criteria is ignored altogether, results that don't contain the criteria are returned, there is no order whatsoever, it just returns everything in a random order. 

This is a 100% reproducible bug. It returns everything in god knows what order, no matter what you typ. Just try it out.
