### ISSUE TITLE
Global widget shortcodes and other shortcodes are not working in single template.

### ISSUE THREAD

**Issue by denizcibal** [pojome/elementor#6462]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

You asked from me for my #6453 report to add Steps to replicate. Then here you are, I hope you will solve it asap because it creates mess in my website.

When I am adding shortcodes in text/content areas, are not working with **single templates** when I am adding wysiwyg editor boxes it works. For example I would like to display ACF field with shortcode or global widget shortcode but none of them is working in single elementor templates.
## Steps to reproduce

- Create single template.
- Add Heading widget ( also same issue added jetelements table widget )
- Add shortcode inside title box ( also same issue when added shortcode inside jetelements table cell )
- And set display conditions for one of custom post type and check post
And instead of shortcode content, displaying shortcode text on post. Means it is not producing content of shortcode it is displaying shortcode code.

Shortcode examples in title area : for example ACF shortcode is :  This is a story about a boy named [acf field="herefieldname"]
Another example in title area : Created global text or button widget and added shortcode of global widget inside title area.

Note: If shortcode is added inside wysiwyg editor boxes it works but if shortcode added in text, title, content areas it is not working.
Note: If shortcode is added directly to another custom post type posts, which is not setted and related with single template then shortcode is working in text, title, content areas without any problem.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->						
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Debian) v5.6.39-84.1
	PHP Version: 7.0.33
	PHP Max Input Vars: 1000
	PHP Max Post Size: 4M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.1
	WP Multisite: No
	Max Upload Size: 4 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: tr-TR
	Timezone: 3
	Debug Mode: Active

== Theme ==
	Name: JupiterX Child
	Version: 1.0.0
	Author: Artbees
	Child Theme: Yes
	Parent Theme Name: JupiterX
	Parent Theme Version: 1.0.2
	Parent Theme Author: Artbees

== User ==
	Role: administrator
	WP Profile lang: tr_TR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.8
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.6.1
		Author: WebDevStudios

	Elementor
		Version: 2.3.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.2.5
		Author: Elementor.com

	Jet Elements For Elementor
		Version: 1.14.7
		Author: Zemez

	Jupiter X Core
		Version: 1.0.0
		Author: Artbees

	Raven
		Version: 1.0.2
		Author: Artbees

	Simple Custom CSS and JS
		Version: 3.22
		Author: SilkyPress.com

	WP-Sweep
		Version: 1.0.12
		Author: Lester 'GaMerZ' Chan

	Yoast SEO
		Version: 9.2.1
		Author: Team Yoast

== Debug ==
	Errors: 
		TypeError: n.attributes[t.name].each is not a function
			at https://example/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.5 - 2:9465
			2018-12-15 23:13 +00:00

		ViewDestroyedError: View (cid: "view1121") has already been destroyed and cannot be used.
			at https://example/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-12-15 19:45 +00:00
			x 2 times

		TypeError: Cannot read property 'currentView' of undefined
			at https://example/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.5 - 2:250827
			2018-12-15 16:04 +00:00

		ViewDestroyedError: View (cid: "view1121") has already been destroyed and cannot be used.
			at https://example/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-12-15 16:03 +00:00

		ViewDestroyedError: View (cid: "view1116") has already been destroyed and cannot be used.
			at https://example/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-12-15 15:05 +00:00

		ViewDestroyedError: View (cid: "view2090") has already been destroyed and cannot be used.
			at https://example/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-12-15 12:21 +00:00

		ViewDestroyedError: View (cid: "view1182") has already been destroyed and cannot be used.
			at https://example/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-12-15 11:22 +00:00
			x 2 times

		SyntaxError: Unexpected token )
			at https://example/wp-admin/post.php?post=13080&action=elementor - 2:28
			2018-12-13 07:26 +00:00
			x 8 times

		ViewDestroyedError: View (cid: "view1182") has already been destroyed and cannot be used.
			at https://example/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-12-11 14:18 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://example/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.4 - 2:182221
			2018-12-11 12:27 +00:00
			x 5 times

				
```
</details>

**Comment by denizcibal** [comment]
Also adding screenshot. 
<img width="1422" alt="ekran resmi 2018-12-17 09 33 08" src="https://user-images.githubusercontent.com/45330663/50070536-65470a00-01df-11e9-8819-ec04ac3cf9ff.png">

**Comment by bainternet** [comment]
@denizcibal 

Thanks for clarifying, 
This is the normal behavior, not all fields can accept and render shortcodes, but for these fields, we've added a "Shortcode Dynamic tag" which is what you should use if you want the shortcode to render.

![ox0iwuh](https://user-images.githubusercontent.com/660572/50074129-96c1d480-01e3-11e9-8884-b199ca4df037.png)


also, you should know that these shortcodes are escaped, but you can disable that by adding this to your functions.php, 

```PHP
add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );
```

thanks again.

**Comment by bainternet** [comment]
P.S we have nothing to do with jetelements table widget or how it works.

**Comment by denizcibal** [comment]
But I didn't understand that when I am using it posts directly without creating relation with single template it works perfect. But it is not working with single templates. So I create post everything works and after I saved as template then stop works. If I would know that when I am editing post before then I could try to find another solution. But after I build lots of posts and save them as template then I see that it is not working.
