### ISSUE TITLE
How to write multiple conditions for a control

### ISSUE THREAD

**Issue by CodeCurosity** [pojome/elementor#6463]
How come there is nothing in documentation for conditions?

I want to hide a control for one of the options in select and show the control for the rest of the options.

e.g Select has option 1, option 2, option 3, option 4

I have a text field which i want to hide if option 4 is selected and show if option1, option2 & option 3 is selected.

Thanks.

**Comment by bainternet** [comment]
There are two parameters you can use:

* `condition` - which is a flat array of key-value with an AND between each of the conditions.
* `conditions` - ( mind the "s" ) which is used for more complex conditions where you can define relations and nested conditions.


For example lets create the following conditions:

 - A is shown always
 - B is shown if A is `on`
 - C is shown always
 - D is shown if C is `on` AND ( (A is `on` AND B is `off`) OR (A is `off`) )

```PHP
// A is shown always
$this->add_control( 'a', [
	'label'        => 'A',
	'type'         => Controls_Manager::SWITCHER,
	'label_off'    => 'Off',
	'label_on'     => 'On',
	'return_value' => 'on',
] );
// B is shown if A is on using 'condition parameter
$this->add_control( 'b', [
	'label'        => 'B',
	'type'         => Controls_Manager::SWITCHER,
	'label_off'    => 'Off',
	'label_on'     => 'On',
	'return_value' => 'on',
	'condition'    => [
		'a' => 'on',
	],
] );
// C is shown always
$this->add_control( 'c', [
	'label'        => 'C',
	'type'         => Controls_Manager::SWITCHER,
	'label_off'    => 'Off',
	'label_on'     => 'On',
	'return_value' => 'on',
] );
// D is shown if C is on AND ( (A is on AND B is off) OR (A is off) ) using conditions parameter
$this->add_control( 'd', [
	'label'        => 'D',
	'type'         => Controls_Manager::SWITCHER,
	'label_off'    => 'Off',
	'label_on'     => 'On',
	'return_value' => 'on',
	'conditions'   => [
		'terms' => [
			[
				'name'  => 'c',
				'value' => 'on',
			],
			[
				'relation' => 'or',
				'terms'    => [
					[
						'name'     => 'a',
						'operator' => '!=',
						'value'    => 'on',
					],
					[
						'terms' => [
							[
								'name'  => 'a',
								'value' => 'on',
							],
							[
								'name'  => 'b',
								'value' => 'off',
							],
						],
					],
				],
			],
		],
	],
] );
```
In B, using condition will work just fine but for D you need to use conditions which accepts nested conditions and relation param.

bare in mind that this is not test but its shows the main idea...

Hope this help.
