### ISSUE TITLE
WPML Translation

### ISSUE THREAD

**Issue by Boffice** [pojome/elementor#6466]
Hello,

As i see from your newsletters you are open for new ideas and constantly are adding new features. i believe bellow can help and make life easy to lots of your customers including me:

i do understand that this should be more WMPL concern than yours but anyways i hope that you will be interested and can support bellow on your end as well.

This was sent to WPML:
> Hello,
> 
> I was not able to find and am very confused why very simple but yet must have function is not available in WPML yet.
> 
> there is very easy solution for all the pain and problems with integration issues. you can just simple develop option which will allow us to create special tags like {title}.
> 
> Lets say my page builder (Elementor) 3rd party element plugin doesn't support WPML, and i am creating slider which consists of: Title,Description,button.
> 
> so instead of filling it with text:
> Title: Special Offer
> Description: Today and tomorrow you can purchase HP notebooks with 50% disscount
> Button: View All
> I can just add custom tags which will be pre translated in WPML dashboard and will display value based on active language:
> Title: {title}
> Description: {Description}
> Button: {Button}
> 
> Same thing can be very useful in lots of other cases with various themes and plugins.

**Comment by bainternet** [comment]
@Boffice 	

Sadly, not everything is that simple. 
Anyway thanks.
