### ISSUE TITLE
Pro Form Webhook Question *File to URL PATH*

### ISSUE THREAD

**Issue by Dssii3056** [pojome/elementor#6467]
Hello Everyone,

I am trying to create a webhook in functions.php for Elementor Pro. I found this link here on Git that helped tremendously, https://github.com/pojome/elementor/issues/4218 but I have a further question with it.

The service I'm attempting to map my fields to does not except Files, but I noticed that the default response emails in Elementor Pro convert the FILE to a PATH and display the link, how can I achieve this result if I want to integrate it into a custom webhook via functions.php? 

My code is below **working except for the file field** form_fields[file_report_upload]' => $submmited_fields['Client File Link']['value'],
```PHP
/** Elementor to Pardot PHP hook with file
 */
/** Function must be unique name and match call at end of function */
function submit_form_to_pardot1($record, $handler) 
{
  $form_name = $record->get_form_settings('form_name');
/** Funding Inquiry is Form Name NOT ID */
  if ('%%FORM-NAME%%' !== $form_name ) {
    return;
  }

  $raw_fields = $record->get('fields');

  $fields = [ 
  /** 'wpfieldname => --- ['Pardot PROSPECT Field Name']['value'], */
  
  'form-field-email' => $submmited_fields['Email']['value'],
  'form-field-first_name' => $submmited_fields['First Name']['value'],
  'form-field-last_name' => $submmited_fields['Last Name']['value'],
  **'form_fields[file_report_upload]' => $submmited_fields['Client File Link']['value'],**

];
  
  foreach ( $raw_fields as $id => $field ) {
    $fields[ $id ] = $field['value'];
  }
    /** pardot form handler web hook */
  $endpoint = '%%ENDPATHURL%% ';

  $response = wp_remote_post($endpoint, array(
    'body' => $fields
  ));
}

add_action('elementor_pro/forms/new_record', 'submit_form_to_pardot1');
```

**Comment by bainternet** [comment]
@Dssii3056 	

Your code is a bit messy and there are missing variables but anyway you shuold access the fields via the field ID and the file url is in the field value:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}
	
	$raw_fields = $record->get( 'fields' );
	$sent_fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$sent_fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
		'body' => $fields,
	]);
});
```

**Comment by Dssii3056** [comment]
Hi bainternet,

Thank you for taking the time to post and help me with this. It actually led me to a bug...

When I add an HTML element/field to a form in Elementor and attempt to use a webhook in functions.php. I am unable to post the data.

My code worked just fine after I removed the HTML fields from the form.

Is this a known issue?
