### ISSUE TITLE
Insert PHP

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#647]
Feature Request
Introduce an Isert PHP element similar to the shortcode and html elements to allow the addition of custom php code to pages.

**Comment by KingYes** [comment]
Sorry, from security reasons, we don't allow this widgets.

BUT -
1. You can wrap you code inside you custom shortcode
1. You can create custom widget for Element (We don't have official API yet).

**Comment by nickdgreen** [comment]
Yakir,

 

I am at the bleeding edge of my understanding with this and have created a
widget that appears in the menu but when inserted in a page I get nothing.
On the existing WordPress site I have used the insert_php plug in that
enables you to add code framed in [insert_php][/insert_php] but the plugin
doesn't work with Elementor. So now I'm completely stuck - solution?

 

Best Regards

Nick

 


Legal Disclaimer:

Internet communications are not secure and therefore Websites Designed 4U (a
business name of ISD Consultants Ltd.) does not accept legal responsibility
for the contents of this message. This email is confidential and solely for
the use of the intended recipient(s). If you receive this email by mistake,
please advise the sender directly, then immediately destroy this email.
Websites Designed 4U maintains security processes designed to eliminate
viruses, however the Company is not responsible for viruses which may be
contained in the email or any attachment(s).

**Comment by bentalgad** [comment]
+1 This will make this plugin the plugin i will use forever! adding php code like the oxygen page builder let's you is amazing and the you can use the plugin to actually make a professional complex Wordpress sites and not only design nice pages.

![2018-07-11 16 13 01](https://user-images.githubusercontent.com/23374215/42573666-6b0df34a-8525-11e8-9e69-d1d00df3fe0f.gif)
