### ISSUE TITLE
Custom options for basic widget, row and column

### ISSUE THREAD

**Issue by wayheming** [pojome/elementor#6470]
Hello @bainternet, you helped me with [this](https://github.com/pojome/elementor/issues/6171) topic and showed how to add custom settings fields to standard widgets, but you didn’t show me how I can use them. I studied code Elementor a little and found how I can add a class for a section if the custom option is enabled but my method only works on the front. Tell me how I can add a class to a section so that the changes can be seen immediately in the editor.

My code:

```
add_action(
	'elementor/element/section/section_layout/before_section_end',
	function( $element ) {
		$element->add_control(
			'section_fullwidth',
			[
				'label'        => esc_html__( 'Stretch Section CSS', 'theme' ),
				'type'         => \Elementor\Controls_Manager::SWITCHER,
				'default'      => 'no',
				'return_value' => 'yes',
				'render_type'  => 'template',
			]
		);
	},
	10
);

add_action(
	'elementor/frontend/section/before_render',
	function( $widget ) {
		$settings = $widget->get_active_settings();
		if ( 'yes' === $settings['section_fullwidth'] ) {
			$widget->add_render_attribute( '_wrapper', 'class', 'section-fullwidth' );
		}
	},
	10
);
```

Frontend: http://prntscr.com/lw3sso
Editor: http://prntscr.com/lw3t7r

I will be very grateful for the help or sample code.

**Comment by bainternet** [comment]
@wayheming 	

If you want to add a CSS class to a section, use 'prefix-class' parameter in your control, ex:

```PHP
$element->add_control(
	'section_fullwidth',
	[
		'label'        => esc_html__( 'Stretch Section CSS', 'theme' ),
		'type'         => \Elementor\Controls_Manager::SWITCHER,
		'default'      => 'no',
		'return_value' => 'fullwidth',
        'prefix_class' => 'section-',
	]
);
```

Which will add the class to the section wrapper for you for both editor and frontend. And like I have said last time, we have a lot covered in our [Developers Docs](https://developers.elementor.com/).
