### ISSUE TITLE
Columns messed up when updating from V 2.7 to V 3.xx

### ISSUE THREAD

**Issue by claudemichaud** [pojome/elementor#6474]
I have a problem with all releases of elementor since version 2.3, it changes the columns position, as shown in the two pictures. Anybody has seen the same problem?
The first picture is a page before the update from 2.2.7 to 2.3.5. The second shows what happened to the same page after the update.
<img width="1077" alt="with_elementor_2 2 7" src="https://user-images.githubusercontent.com/45961731/50139144-1b265d00-02a1-11e9-805d-50a204a32ef0.png">
<img width="1076" alt="with_elementor_2 3 5" src="https://user-images.githubusercontent.com/45961731/50139160-24afc500-02a1-11e9-82cf-9fd39c0ad99c.png">

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

And as far as I know, we don't have version 3.xx
