### ISSUE TITLE
How can you add class to the control

### ISSUE THREAD

**Issue by CodeCurosity** [pojome/elementor#6475]
```
		$this->add_control(
			'placeholder',
			[
				'label' => __( 'Placeholder', 'elementor-forms' ),
				'type' => Controls_Manager::TEXT,
				'label_block' => true,
				'class' => "mycustomclass",
				'id' => "mycustomid",
			]
		);
```

Is this possible? how can we add custom classes or id to the control?

**Comment by bainternet** [comment]
@CodeCurosity 	

Each control has automatic classes on the wrapper based on the control name:  `elementor-control-{CONTROL_NAME}` and based on the control type: `elementor-control-type-{CONTROL_TYPE}`. Other than that you can add custom classes via the `classes` parameter, so:

```PHP
$this->add_control(
	'placeholder',
	[
		'label' => __( 'Placeholder', 'elementor-forms' ),
		'type' => Controls_Manager::TEXT,
		'label_block' => true,
		'classes' => "mycustomclass",
	]
);
```

this will give you ca control with a div wrapper that has these classes:
`elementor-control-placeholder elementor-control-type-text mycustomclass`

**Comment by CodeCurosity** [comment]
I don't want to give the class to the wrapper i want to add the class to the actual input class e.g `class="tooltip-target elementor-control-tag-area mycustomclass"`

**Comment by webdevs-pro** [comment]
Any updates?
