### ISSUE TITLE
"elementor/editor/localize_settings" filter not Firing after Elementor 2.2.3

### ISSUE THREAD

**Issue by jm124y** [pojome/elementor#6477]
We've recently upgraded our Elementor version from 2.2.3 to 2.3.5 and I noticed that the filter "elementor/editor/localize_settings" we use to change our default colors is no longer firing. It only happens after I've upgraded past Elementor 2.2.3. An example of a code snippet we use to fire the filter is below:

![image](https://user-images.githubusercontent.com/37160325/50160512-2d070080-029f-11e9-82d2-09a8c41184d9.png)

When I do a die and dump in 2.2.3, here is what I get below:

![image](https://user-images.githubusercontent.com/37160325/50160634-75beb980-029f-11e9-9ac5-da7022ef2fde.png)

Performing a die and dump after 2.2.3 though does not dump anything.

I noticed that there was some refactoring in the following files and I'm wondering if maybe this contributed to the issue:

-modules/history/module.php
-modules/library/module.php

**Comment by bainternet** [comment]
@jm124y 

we can't replicate and a simple check you can run is to see if you have "History" in the editor, if you do then the filer is running.

if not, then please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
