### ISSUE TITLE
MailerLite Rest Client Error: response code 400

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#6478]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor v2.3.6 Pro v2.3.0 and WP 5.0.1

## Description
When I use MailerLite integration in general or custom mode, I'm getting Rest Client Error: response code 400 trying to send form. When I turn the Double opt in option, the error disappears but I get nothing in my mailing list in MailerLite. The conformation email either don't come.

## Attempt to solve by myself
- [x] I tried to make integration via Zapier to check my MailerLite API for correct work. All works good
- [x] I've made ticket to MailerLite to check the API and they say that all works fine and there is no matter the double opt in is on or off

## Steps to reproduce

1. Copy an api key from here https://app.mailerlite.com/integrations/api/
2. Paste into /wp-admin/admin.php?page=elementor#tab-integrations MailerLite field and check it
3. Create form with Name, Email and Acceptance fields
4. Set action after submit: MailerLite and Email
5. Set the group in MailerLite
6. Save document and check

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Unix)
	MySQL version: (LTD BeGet) v5.7.21-20
	PHP Version: 7.2.5
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1047527424
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.9
	Site URL: http://elementor.wplovers.pw
	Home URL: http://elementor.wplovers.pw
	WP Multisite: No
	Max Upload Size: 999 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: ru-RU
	Timezone: 3
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.8
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: ru_RU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 YaBrowser/18.10.2.172 Yowser/2.5 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.3.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.3.0
		Author: Elementor.com


== Debug ==
	Errors: 
		TypeError: Cannot read property 'query' of null
			at http://elementor.wplovers.pw/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1 - 1:60824
			2018-12-12 20:44 +00:00
```
</details>

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by Arahis** [comment]
Hi! Have the same issue! How can I resolve it?

**Comment by Arahis** [comment]
> Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.
> 
> thanks.

Hi! Have the same issue! How can I resolve it?
