### ISSUE TITLE
Pro Forms / Webhook / and HTML field 

### ISSUE THREAD

**Issue by Dssii3056** [pojome/elementor#6481]
Hi Support,

I noticed that when I attempt to add an HTML field to a form in Ele Pro and submit the data via a webhook in functions.php, I receive an error.

The HTML fields were purely aesthetic, and were not defined within functions.php in any way (or required by the form in Ele Pro)

Steps to recreate:

1. Create a basic contact form in Ele Pro which contains HTML elements

2. Create a function in functions.php that submits the data to an external URL

3. Attempt to submit form.

**Comment by bainternet** [comment]
@Dssii3056 

We can't replicate, and the HTML "field" is not a real field, its plain HTML which is never actually submitted unless you have INPUT elements which are conflicting.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
