### ISSUE TITLE
Can't import templates after update (Error - "Invalid template type")

### ISSUE THREAD

**Issue by JoeDarko** [pojome/elementor#6483]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have a problem with importing Elementor templates after the last update.

If i try to import templates i get this error: "Invalid template type "footer".."

It only happens when importing templates that have a template type assinged to them - like header, footer etc.

Importing other templates (page or section) works normal.

Two days ago everything worked fine. It started happening after the latest update, but i'm not sure if it's related to the Elementor or Elementor PRO plugin. 

## Steps to reproduce

1. Update to the latest version of Elementor and Elementor PRO.

2. Ty to import header, footer or single template type (Section or page templates work fine.)

3. You get an error "Invalid template type"

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.6.38-83.0
	PHP Version: 7.1.5
	PHP Max Input Vars: 10000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.1
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: cs-CZ
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.2.1
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.3
		Author: WordPress Contributors

	Elementor
		Version: 2.3.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.3.0
		Author: Elementor.com

	GP Premium
		Version: 1.7.7
		Author: Tom Usborne

== Debug ==
	Errors: There are no errors to display

```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by JoeDarko** [comment]
Also just noticed that after the update it is not possible to save a global widget. Other people on Facebook are reporting the same problems.

**Comment by Magnethi** [comment]
Same here, can't uploade templates (Footer & Header) gets: "elementor Invalid template type", after update to Elementor 2.3.6 an Pro 2.3.1

**Comment by blaisck** [comment]
I have the same problem.

**Comment by seanbperiod** [comment]
Was this ever resolved? I'm unable to import an archive template. I get Invalid template type "archive".. when uploading the json file.

**Comment by akaobelo** [comment]
Hi! I have this issue with the newspaper theme. I'm trying to import footer from cloud templating and this is popping on my console. Wordpress beginner, Thank you! 
![Screenshot_1](https://user-images.githubusercontent.com/35630421/121975609-973b8600-cdb4-11eb-9afe-033dfbcd723a.png)

**Comment by kwdigi** [comment]
I have the same issue.   Elementor versions are the same on both hosts.
