### ISSUE TITLE
CPT UI conflict with Pro

### ISSUE THREAD

**Issue by dammittman813** [pojome/elementor#6487]
Seems there is a conflict or bug with CPT UI (Custom Post Types). When I update Elementor Pro to 2.3.0, the Post Content does not display on Elementor templates / pages. But it works fine with prior Elementor Pro version.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

anyway, make sure to update Elementor Pro
