### ISSUE TITLE
Content Lock

### ISSUE THREAD

**Issue by artconic** [pojome/elementor#6489]
Content Lock

A great way to add an opt-in incentive right inside your content. 
Reveal it once the visitor signs up!

How Can I add this to a profile page?

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
