### ISSUE TITLE
"Sticky" Ribbon

### ISSUE THREAD

**Issue by artconic** [pojome/elementor#6490]
"Sticky" Ribbon

Add a ribbon type form which shows at the top of the screen and remains "sticky" as the visitor scrolls down the page.

Not working....

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
