### ISSUE TITLE
Custom Control not working

### ISSUE THREAD

**Issue by CodeCurosity** [pojome/elementor#6492]
Hi,

So no matter what i try, it always says this control not found, i even tried the sample emojiarea control, it still doesn't work, i maybe including it wrong, can you give me an example of how would you register the sample emojiarea control you have in documentation.

I tried this https://developers.elementor.com/creating-a-new-control/ to create control.

And this to register control.

```
<?php
final class Elementor_Test_Extension {

	public function init() {

		// Include plugin files
		$this->includes();

		// Register controls
		add_action( 'elementor/controls/controls_registered', [ $this, 'register_controls' ] );

	}

	public function includes() {

		require_once( __DIR__ . '/controls/test-control-1.php' );
		require_once( __DIR__ . '/controls/test-control-2.php' );

	}

	public function register_controls() {

		$controls_manager = \Elementor\Plugin::$instance->controls_manager;
		$controls_manager->register_control( 'control-type-1', new Test_Control1() );
		$controls_manager->register_control( 'control-type-2', new Test_Control2() );

	}

}
```

**Comment by bainternet** [comment]
@CodeCurosity 	

where is your [control JS file](https://developers.elementor.com/creating-a-new-control/#Control_JS_file)?

When and when are you instantiating the class?

**Comment by CodeCurosity** [comment]
My custom control is very simple all i need is a <select class="mycustomclass"></select> with some javascript and i was just testing the emojiarea to see if control actually shows up in settings, i am including the class in my final class of a custom widget.

Do you have a simpler way for me to simply include this select as a custom control?

**Comment by bainternet** [comment]
If all you need is just to add a CSS class then you can use our select control and pass `classes` parameter ex:

```PHP
$element->add_control(
	'control_id',
	[
		'label' => 'my control',
		'type' => \Elementor\Controls_Manager::SELECT,
		'options' => [
			'value' => 'label',
			'value2' => 'label2',
			'value3' => 'label3',
		],
		'classes' => 'mycustomclass',
	]
);
```

this will add the class to the control wrapper.

thanks.

**Comment by bschulz87** [comment]
I have a similar problem: Undefined class constant error when registering custom control.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I tried to register a custom control like in the docs: https://gist.github.com/bschulz87/3fc4744a72c15cc0b9daf7da25e66d5c 

When i want to register the control in my widget (which works fine with the default controls) i get a fatal error Fatal error: Uncaught Error: Undefined class constant 'CUSTOM' 

## Steps to reproduce

1. Add a custom control 
2. Register Control in Widget
3. Open a page to edit with elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by techsaqib** [comment]
yes i am facing the same problem not find any solution , i was thinking i am making some mistak , its took my lots of time , i was trying to create my own iconpicker :( ,

**Comment by fhfournier** [comment]
Same thing here, i can add new control but can't add it to my widget

$this->add_control(
	'testnewcontroll',
	[
		'label' => __( 'testnewcontroll', 'plugin-name' ),
		'type' => \Elementor\Controls_Manager::{WHAT GOES IN HERE?},
	]
);

**Comment by techsaqib** [comment]
> Same thing here, i can add new control but can't add it to my widget
> 
> $this->add_control(
> 'testnewcontroll',
> [
> 'label' => __( 'testnewcontroll', 'plugin-name' ),
> 'type' => \Elementor\Controls_Manager::{WHAT GOES IN HERE?},
> ]
> );

they do it for a reason , so developer become useless and there pro version make sales 👎

**Comment by danyj** [comment]
your control type is assigned via this

`$controls_manager->register_control( 'control-type-2', new Test_Control2() );`


so to use it it would be 

```
$this->add_control(
    'testnewcontroll',
    [
        'label' => __( 'testnewcontroll', 'plugin-name' ),
        'type' =>'control-type-2',
    ]
);
```

note that these 

`Controls_Manager:: ANY ELEMENTOR CONTROL`

have assigned constants here https://github.com/elementor/elementor/blob/45eaa6704fe1ad18f6190c8e95952b38b8a38dc7/includes/managers/controls.php  thus they can use them

**Comment by iqbalrony** [comment]
I think <code>Controls_Manager::</code> will not goona work for custom control. I created a custom control and its work fine. Here is the link of my created file. https://gist.github.com/iqbalrony/4372a12f994c3215041680e0075d083f

I applied custom control in the following way.
<pre>
<code>
$this->add_control(
	'page_layout',
	[
		'label' => esc_html__('Layout', 'text-domain'),
		'type' => \Elementor\CustomControl\ImageSelector_Control::ImageSelector,
		'options' => [
			'left-sidebar' => [
				'title' => esc_html__('Left', 'text-domain'),
				'url' => 'http://localhost/test/wp-content/themes/test/assets/images/left-sidebar.png',
			],
			'right-sidebar' => [
				'title' => esc_html__('Right', 'text-domain'),
				'url' => 'http://localhost/test/wp-content/themes/test/assets/images/right-sidebar.png',
			],
			'no-sidebar' => [
				'title' => esc_html__('No Sidebar', 'text-domain'),
				'url' => 'http://localhost/test/wp-content/themes/test/assets/images/no-sidebar.png',
			],
		],
		'default' => 'right-sidebar',
	]
);
</code>
</pre>

**Comment by dbjpanda** [comment]
Follow this example https://developers.elementor.com/creating-a-new-control/  with some modification as below 

```
const emojionearea = 'emojionearea';

    /**
     * Get emoji one area control type.
     *
     * Retrieve the control type, in this case `emojionearea`.
     *
     * @since 1.0.0
     * @access public
     *
     * @return string Control type.
     */

    /**
     * Set control type.
     */
    public function get_type() {
        return self::emojionearea;
    }

```
Then register your control
```
include_once( 'classes/emojionearea-control.php' );
add_action( 'elementor/controls/controls_registered', function ( $manager){
        $manager->register_control( 'emojionearea', new EmojiOneArea_Control());
} );
```
Use it in your control now
```
$widget->add_control(
            'emoji_control',
            [
                'label' => __( 'Content', 'elementor-hello-world' ),
                'type' => EmojiOneArea_Control::emojionearea,
                'default' => '',
            ]
);
```

**Comment by lscorrea** [comment]
> ```
> ns' => [
> ```
'classes' => 'mycustomclass', nao tem funcionado para mim.
