### ISSUE TITLE
Exit icon needed in Elementor Editing mode

### ISSUE THREAD

**Issue by miklos7** [pojome/elementor#6494]
It needs add an exit icon to the bottom bar on the left side - so after you hit publish - you could click to the dashboard.  Control E takes you to a page search box - that is 2 steps to the dashboard

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* **Prerequisites**.
* Description and examples.
