### ISSUE TITLE
Passing image ids by dynamic shortcode to image gallery

### ISSUE THREAD

**Issue by Zjadlbymcos** [pojome/elementor#6496]
- Wordpress 5.0.1
- Elementor 2.3.6
- Elementor Pro 2.2.0

I'm pretty sure that I found problem with typing data. Correct me if I'm wrong :)

I'm try to use Dynamic Shortcode option in Image Gallery widget. No matter what shortcode I prepare always return that warnings:

```
Warning: Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 148

Warning: implode(): Invalid arguments passed in /var/www/html/wp-content/plugins/elementor/includes/widgets/image-gallery.php on line 370
```

I analysed Elementor code and `Elementor\Widget_Image_Gallery` except `$settings['wp_gallery']` to be and array. But `ElementorPro\Modules\DynamicTags\Tags\Shortcode` **always** returns string.

**Comment by bainternet** [comment]
No real Yes/No answer here.

Shortcodes in their true purpose should always return a string, no with that being said, you can manipulate and use them to return an array which in a galley control is an array of arrays with 'id' => 'value'

ex:
```PHP
$gallery_data = [
	[ 'id' => 1 ],
	[ 'id' => 2 ],
	[ 'id' => 3 ],
];
```

Now even if you do return a value from your shortcode that matches this data structure, there is still the issue of the shortcode dynamic being escaped which will break the structure. 

But not all is lost 🤪,
We added a filter for these cases to allow bypassing the escaping function, so add this snippet you your functions.php :
```PHP
add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );
```

and your dynamic shortcode won't be escaped and will keep the structure.


thanks.

**Comment by Zjadlbymcos** [comment]
Ok, sure. But how it can help me if Image Gallery accepts only Array on input? 

I would be grateful if Elementor Image Gallery will have posibility to accept string "1,2,3,4" as input. There's no other possibility to pass ids throught shortcode.

**Comment by jnicotra** [comment]
I need some help with this one also. I created a real estate plugin and am looking to have the home images displayed in an elementor gallery (rather than creating the gallery myself)

I simply cannot figure out how to pass the correct type of data to elementor for it to handle it (I get the same error that Zjadlbymcos got)

I dont think i'm understanding exactly WHAT the data structure elementor is looking for. Do I need to structure the data in the way you have displayed above?
```
$gallery_data = [
	[ 'id' => 1 ],
	[ 'id' => 2 ],
	[ 'id' => 3 ],
];
```
Is there a more preferred way?

To be clear, I am pretty new at plugin development & php coding. But here is what I have:


```
function bpd_image_ids( $atts ){
$images = bpdi_meta( 'bpd-property-images' );
$image_ids = array_keys( $images );
	/*
ob_start();

echo do_shortcode( $shortcode );
ob_get_clean();
*/
var_dump($image_ids);
return [225,89,118];
}
add_shortcode( 'bpd-image-ids', 'bpd_image_ids' );
add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );
```
I keep testing data trying to get a response but I dont really know where to begin.

Any info is seriously helpful!

**Comment by Zjadlbymcos** [comment]
@jnicotra there is a workround to this.

Just copy `elementor/include/widgets/image-gallery.php` to your theme/plugin according to tutorials:

- https://developers.elementor.com/creating-an-extension-for-elementor/
- https://developers.elementor.com/creating-a-new-widget/

and replace

```php
$ids = wp_list_pluck( $settings['wp_gallery'], 'id' );
$this->add_render_attribute( 'shortcode', 'ids', implode( ',', $ids ) );
```
with
```php
if (is_array($settings['wp_gallery'])) {
	$ids = wp_list_pluck( $settings['wp_gallery'], 'id' );
	$this->add_render_attribute( 'shortcode', 'ids', implode( ',', $ids ) );
} else {
	$this->add_render_attribute( 'shortcode', 'ids', $settings['wp_gallery'] );
}
```

I really don't like this solution but it works.. :)

**Comment by stickypages** [comment]
> I need some help with this one also. I created a real estate plugin and am looking to have the home images displayed in an elementor gallery (rather than creating the gallery myself)
> 
> I simply cannot figure out how to pass the correct type of data to elementor for it to handle it (I get the same error that Zjadlbymcos got)
> 
> I dont think i'm understanding exactly WHAT the data structure elementor is looking for. Do I need to structure the data in the way you have displayed above?
> 
> ```
> $gallery_data = [
> 	[ 'id' => 1 ],
> 	[ 'id' => 2 ],
> 	[ 'id' => 3 ],
> ];
> ```
> Is there a more preferred way?
> 
> To be clear, I am pretty new at plugin development & php coding. But here is what I have:
> 
> ```
> function bpd_image_ids( $atts ){
> $images = bpdi_meta( 'bpd-property-images' );
> $image_ids = array_keys( $images );
> 	/*
> ob_start();
> 
> echo do_shortcode( $shortcode );
> ob_get_clean();
> */
> var_dump($image_ids);
> return [225,89,118];
> }
> add_shortcode( 'bpd-image-ids', 'bpd_image_ids' );
> add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );
> ```
> Normally I just return $image_ids, but I have been testing a bunch of things, so that's my current code (which I'm aware wont work as expected).
> I keep testing data trying to get a response but I dont really know where to begin.
> 
> Any info is seriously helpful!

Did you get this shortcode to work?

**Comment by Zjadlbymcos** [comment]
I'll prepare repo with better and working solution in couple days. :)

śr., 13 mar 2019 o 01:55 Justin <notifications@github.com> napisał(a):

**Comment by Zjadlbymcos** [comment]
I'll prepare repo with better and working solution in couple days. :)

**Comment by Zjadlbymcos** [comment]
> Did you get this shortcode to work?

Unfortunetly elementor gallery widget doesn't support shortcode anymore. Easier way to handle displaying dynamic gallery is using PODS instead of ACF.

PODS have got better support in elementor. Dynamic gallery work out of the box.
