### ISSUE TITLE
Extend Widget by Adding Control in Tab

### ISSUE THREAD

**Issue by pnpetroff** [pojome/elementor#6499]
It appears that there are only hooks to add widget controls before/after sections when extending a widget. For example - **elementor/element/column/section_style/before_section_end**

A hook to add control in a tab (like Hover) will be very nice.

**Comment by bainternet** [comment]
@pnpetroff 

for cases like that, we have the `start_injection` and `end_injection` methods which let you insert a control at the position you want ex:

```PHP
add_action( 'elementor/element/button/section_style/before_section_end', function( $element, $args ) {
	$element->start_injection( [
		'at' => 'before',
		'of' => 'button_text_color',
	] );
	// add a control
	$element->add_control(
		'btn_style',
		[
			'label' => 'Button Style',
			'type' => \Elementor\Controls_Manager::SELECT,
			'options' => [
				'fancy' => 'Fancy',
				'stylish' => 'Stylish',
				'rounded' => 'Rounded',
				'square' => 'Square',
			],
			'prefix_class' => 'btn-style-',
		]
	);

	$element->end_injection();
}, 10, 2 );
```

**Comment by dimative** [comment]
How can i add control to all existing widgets? What action should i use? @bainternet

**Comment by eduardovillao** [comment]
@bainternet 

the start_injection and end_injection dont work with tabs, like tabs in form repeater. 

how to add custom control to tabs in form repeater? (ex in tab advanced with shortcode, value...)

> @pnpetroff
> 
> for cases like that, we have the `start_injection` and `end_injection` methods which let you insert a control at the position you want ex:
> 
> ```
> add_action( 'elementor/element/button/section_style/before_section_end', function( $element, $args ) {
> 	$element->start_injection( [
> 		'at' => 'before',
> 		'of' => 'button_text_color',
> 	] );
> 	// add a control
> 	$element->add_control(
> 		'btn_style',
> 		[
> 			'label' => 'Button Style',
> 			'type' => \Elementor\Controls_Manager::SELECT,
> 			'options' => [
> 				'fancy' => 'Fancy',
> 				'stylish' => 'Stylish',
> 				'rounded' => 'Rounded',
> 				'square' => 'Square',
> 			],
> 			'prefix_class' => 'btn-style-',
> 		]
> 	);
> 
> 	$element->end_injection();
> }, 10, 2 );
> ```

**Comment by rb-ar** [comment]
> @pnpetroff
> 
> for cases like that, we have the `start_injection` and `end_injection` methods which let you insert a control at the position you want ex:
> 
> ```
> add_action( 'elementor/element/button/section_style/before_section_end', function( $element, $args ) {
> 	$element->start_injection( [
> 		'at' => 'before',
> 		'of' => 'button_text_color',
> 	] );
> 	// add a control
> 	$element->add_control(
> 		'btn_style',
> 		[
> 			'label' => 'Button Style',
> 			'type' => \Elementor\Controls_Manager::SELECT,
> 			'options' => [
> 				'fancy' => 'Fancy',
> 				'stylish' => 'Stylish',
> 				'rounded' => 'Rounded',
> 				'square' => 'Square',
> 			],
> 			'prefix_class' => 'btn-style-',
> 		]
> 	);
> 
> 	$element->end_injection();
> }, 10, 2 );
> ```

@bainternet could you add that somewhere on developers.elementor.com?
I've just spent a couple of hours on searching how to do this, even started reading the source code before I found this.

**Comment by bdkoder** [comment]
> @pnpetroff
> 
> for cases like that, we have the `start_injection` and `end_injection` methods which let you insert a control at the position you want ex:
> 
> ```
> add_action( 'elementor/element/button/section_style/before_section_end', function( $element, $args ) {
> 	$element->start_injection( [
> 		'at' => 'before',
> 		'of' => 'button_text_color',
> 	] );
> 	// add a control
> 	$element->add_control(
> 		'btn_style',
> 		[
> 			'label' => 'Button Style',
> 			'type' => \Elementor\Controls_Manager::SELECT,
> 			'options' => [
> 				'fancy' => 'Fancy',
> 				'stylish' => 'Stylish',
> 				'rounded' => 'Rounded',
> 				'square' => 'Square',
> 			],
> 			'prefix_class' => 'btn-style-',
> 		]
> 	);
> 
> 	$element->end_injection();
> }, 10, 2 );
> ```

great solution. Thanks.

**Comment by ramiy** [comment]
Hi @rb-ar ,

The developer docs has the [control injecting](https://developers.elementor.com/docs/hooks/injecting-controls/) docs.

**Comment by bdkoder** [comment]
@ramiy ,
How possible to inject a Tab item within a Tab?
The below code not working - 

add_action('elementor/element/carousel/section_style_category/before_section_end', function ($element, $args) {
    if ('carousel' == $element->get_name()) {

        $element->start_injection([
            'at' => 'after',
            'of' => 'tabs_category_style',
        ]);

        $element->start_controls_tab(
            'tab_category_active',
            [
                'label' => esc_html__('Active', 'kit'),
            ]
        );

        $element->add_control(
            'category_active_color',
            [
                'label' => esc_html__('Color', 'kit'),
                'type' => Controls_Manager::COLOR,
                'selectors' => [
                    '{{WRAPPER}} a' => 'color: {{VALUE}};',
                ],
            ]
        );

        $element->end_controls_tab();

        $element->end_injection();
    }
}, 20, 2);

**Comment by udzrbarik** [comment]
> 

Hello. Is it possible to hook into the Advanced tab? I'm trying but I'm failing miserably.

``
add_action( 'elementor/element/button/section_advanced/before_section_end', function( $element, $args ) {
	$element->start_injection( [
		'at' => 'before',
		'of' => '_element_width',
	] );
``
