### ISSUE TITLE
[bug] color transparency selector off canvas

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#6501]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

when selecting color (no matter where) the slider for transparency selection is off canvas and not in the place where expected ... see screenshot

![screenshot_2018-12-19 elementor home](https://user-images.githubusercontent.com/22448174/50235775-fa512b00-03b8-11e9-9f62-115f4962861c.png)

## Steps to reproduce

just try to select a color anywhere and see

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* System info.

we simply can't replicate. 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by dasigna** [comment]
... meanwhile found out it only occurs with firefox dev edition. o.k. with other browsers.
still cant find out why, but sorry for bothering. for sure no issue with elementor :)
