### ISSUE TITLE
Select Multiple Sources in Post Widget Query

### ISSUE THREAD

**Issue by Recover-Zone** [pojome/elementor#6503]
## Prerequisites

- [*] I have searched for similar features requests in both open and **closed (Closed ticket #4952 provides solution, but not directly)** tickets and cannot find a duplicate.
- [*] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
During the creation process of our website we ran across an issue that we would love to see addressed by the Elementor team. That issue relates to being able to selected multiple sources for the post widget query. This addition would be a great feature as our currently situation is as follows. Our website offers multiple types of posts (recipes, articles, etc.). For our recipe posts we specifically wanted custom fields, so we created a custom post type for recipes. On our page we have a latest posts page which we desired to include all types of post we produced, showing our latest. When we posted our first recipe we realized it was not showing on our latest post page. Come to understand now, you can only select one type of source for post queries on the Elementor post widget, which we were using. This put us in the dilemma what type of post did we want to show more.

**Describe the solution you'd like**
A great solution we would love to see Elementor implement is the ability to select multiple sources in the post widget query section. This would make the post widget more dynamic and flexible to use in all scenarios. 

**Describe alternatives you've considered**
As of now our solution is using tags rather than custom post types and we have duplicated the recipe post we have created in the post category and tagged them recipes that way we can show all of our latest post on the latest post page. This solution sadly does not allow for us to using custom fields to these special types of post. 

**Additional context**
Hope to see some awesome features like this one implemented into Elementor. Thanks for taking time to review this request.

**Comment by Bey13** [comment]
+1 this feature - I am in the process of deciding a similar build as to which route to take with tags/cpt.

**Comment by bainternet** [comment]
@Recover-Zone 

This can already be done easily using a [Custom Query Filter](https://developers.elementor.com/custom-query-filter/#Multiple_Post_Types_in_Posts_Widget)

thanks.
