### ISSUE TITLE
Need Pagination for Elementor Pages

### ISSUE THREAD

**Issue by tim777z** [pojome/elementor#6509]
Currently Elementor has only got addons/plugins for **Post** Pagination, but no support for dividing a **Page** using tags like {break} <!-nextpage-> etc. This is terrible really, as wordpress has had support for these tags for years. I'm in deep trouble as I am unable to complete my clients website due to this problem, I wish I hadn't bought elementor pro... Please pull up your socks dear elementor team 👎 👎 👎

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
