### ISSUE TITLE
Editor only loads in draft mode

### ISSUE THREAD

**Issue by jayarnielsen** [pojome/elementor#651]
The elementor editor is only showing when a post/page is in draft mode. Once it is published, the editor sidebar won't show up. I'm using the Foundationpress theme and WP Bedrock
https://roots.io/bedrock/
https://foundationpress.olefredrik.com/

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
