### ISSUE TITLE
global widget create : js error c is undefined "isotope.min.js"

### ISSUE THREAD

**Issue by JessicaIpo** [pojome/elementor#6516]
## Description
When i want to create a global widget, i have this javascript error " c is undefined". in isotope.min.js file. 
My global don't be created.
And when i create a 'modele' or "elementor template" i have the same error, but my template is also created..
I upgraded to the last version of Elementor Pro but bug isn't fixed

Best regards

**Comment by crazypsycho** [comment]
I think it is not an elementor issue. Elementor doesnt include Isotope. 
So isotope ist embed by an other plugin or theme.

**Comment by bainternet** [comment]
@JessicaIpo 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.


Without it, we can't replicate and help.
