### ISSUE TITLE
[Feature Request][Pro]: Switch Template Type

### ISSUE THREAD

**Issue by ianlee** [pojome/elementor#6517]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I work in an agency and my designers often create their designs for archives/single pages/templates/etc as a "page".  Converting their designs to the correct type of elementor theme builder template takes a few more steps than is convenient:

1. Go to page and save as template. (saved as "page" template
2. Create New blank template with correct type (single?)
3. import saved template(page) into the blank template  and save template.

Duplicating a template also has to do steps 2 and 3 - if not, then the duplicate is useless and has to be deleted.

**Describe the solution you'd like**

I'd like a way to change the above steps to something like this:

1. Go to page and save as template. (saved as "page" template
2. Go to saved template, go to page settings
3. change dropdown between page, header, section, archive, single, header, footer.  
4. if it has conditional display terms, set them up now.
5. save
6. proceed with differentiating edits.

**Describe alternatives you've considered**

**Additional context**

Thanks

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


And If your designers work in that workflow, then they are using it wrong. When you create a page template in elementor (single for example) you have extra settings and widgets that only appear on a single template editor mode (same goes for archives) so they should really use that to design the templates.

and then you'll have no steps at all :)
Thanks for the feedback.
