### ISSUE TITLE
[Feature Request] Elementor Blocks for Gutenberg with dynamic content decided on block insertion

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#6518]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
You made an excellent job allowing templates to become Gutenberg blocks ( Elementor Blocks for Gutenberg ), but this brings us another fact to solve... When inserting a block inside a page, the template has still "static" content, decided prior in Elementor visual composer page, when you select a text, a background or a link to be loaded statically or dinamically using meta_fields. 
Now, let's say i want a semi-REAL Model-View-Whatever system, where my clients shouldn't touch graphic but **ONLY** data... I should use the old ACF PRO metaboxes or similar ( placed after the gutenberg content, making it almost a failure ) to add dynamically content to that block. And what happens if those blocks to insert are 100 for a page? Should i create 100 ACF Fields? How can i create dynamic fields if i even dont' know how many Elementor templates will be imported as blocks?

**Describe the solution you'd like**
Find a proper way to enable and show also the block fields you want to dynamicize on template (block) insertion inside Gutenberg editor. 
I think you should better separate the 2 contexts, separating **data** from **graphic**.

**Additional context**
I can only speak with a good example...

![image](https://user-images.githubusercontent.com/19909323/50335791-afe0c300-050c-11e9-8ce3-57aed34afea1.png)

This is one of your payoff templates... I want the client to touch only the text of this payoff, which has been inserted as template block in Gutenberg. Fonts and background colour are decided by graphic designer.

By now, you can inserted this as a template block, that's it... But what if...

![image](https://user-images.githubusercontent.com/19909323/50335945-2d0c3800-050d-11e9-8b60-19ff5de31db4.png)

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
