### ISSUE TITLE
WYSIWYG Pods field is not well formatted when used in textfield on single template

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#6519]
## Description
The text format from pods WYSIWYG fields is not 1:1 transferred to Elementor text field. Seems the problem is primarily with breaks and text paragraphs. 
Could be a problem from pods framework? When using "plain text" in pods, the line breaks are used normally. 

Here a picture of the WYSIWYG pods field:
![podswysiwyg](https://user-images.githubusercontent.com/20417555/50339980-5b901000-0519-11e9-9204-67d558fc2fa9.jpg)

And here the final output:
![podsfieldelementorsingle](https://user-images.githubusercontent.com/20417555/50339977-57fc8900-0519-11e9-8900-d11cd609e9ca.jpg)

You can see, the simple line breaks are ignored, also double breaks are converted in white space between words. 

## Steps to reproduce
Create a pod, create a single template and include the WYSIWYG pods field into a Elementor single site text field. 

## Isolating the problem
Not sure if the problem is Elementor or Pods related, but having the same issue on a different instance. 

## Environment
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.35
	MySQL version: Source distribution v5.6.19-67.0
	PHP Version: 7.2.3
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.2
	Site URL: http://dev.stadtquartier.at
	Home URL: http://dev.stadtquartier.at
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 96M
	Permalink Structure: /%category%/%postname%/
	Language: de-DE
	Timezone: Europe/Vienna
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.6.2
	Author: Brainstorm Force
	Child Theme: No

**Comment by bainternet** [comment]
@Luxamman 

This could be due to the fact that by default we run all Pods field output via `wp_kese_post()` for obvious reasons.

However, you can use the native Pods shortcode and use the dynamic shortcode tag for it. Still, a problem since we also run the output of the shortcode tag via `wp_kese_post()` but here you can disable it via a filter:

```PHP
add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );
```

thanks.

**Comment by Luxamman** [comment]
Isn't this a mayor problem when working with Pods and Elementor and the WYSIWYG Pods editor? Because it makes the WYSIWYG editor quite useless and going back to plain paragraph text is much more difficult for the normal user to format. 

I added the 
`add_filter( 'elementor_pro/dynamic_tags/shortcode/should_escape', '__return_false' );`
with Code Snippets, but wont work. 

Thanks!

**Comment by jimtrue** [comment]
Is this a Pods Issue or an Elementor Issue? Since the displaying is being handled by Elementor _not_ Pods in this particular case?

**Comment by kroeberk** [comment]
This issue is sadly not solved with the dynamic pods shortcode, because that does not work on templates for post types. In my opinion this bug is still open, the suggested fix also does not work.

**Comment by HmCody** [comment]
I am running into this issue as well. The temporary fix that seems to work is to create a pods template for the field and then insert the template shortcode in an Elementor Edit Text widget.

**Comment by youliaaa** [comment]
Can someone please provide an example of the type of shortcode that works for them as a workaround in an edit text field? I've tried the field shortcode [pods field=""], which shows the content correctly in the elementor template preview of the custom post, but if I preview or publish the actual custom post it's not loading the field content for me. Shows up blank instead. I've spent hours trying to fix this issue, so any help here would be much appreciated!!

**Comment by AASkidkin** [comment]
Hi all!

Currently, you can try to use it in a different way to get it to work as expected. I have just tested on my testing site and I see if I'm using the PODs field shortcode instead in Elementor Single template (like this - http://prntscr.com/rwyxkv) then it works well and keeps the original formatting given in Pods field.

Simply change your field name in the shortcode (you can take it here in your custom field settings - http://prntscr.com/rwyzm5) and it should work well on your end too.

I hope this helps!
Best.

**Comment by noisybird** [comment]
@AASkidkin Thank you so much, it works great!

**Comment by Heinzdsf** [comment]
This problem still persists. I'm on the latest version of PODS and Elementor Pro and <p> tags are not rendered on the frontend even though the formatting displays correctly on the backend.

**Comment by HmCody** [comment]
I fixed the problem by switching from Elementor to Oxygen.

**Comment by simonclay** [comment]
This is still a problem in 2022.

**Comment by fwunder** [comment]
This is still a problem

Wordpress 6.1
Elementor Pro 3.8.1
PODS 2.9.9

**Comment by joaopedrofrech** [comment]
They just released a big update and the problem still persists.

Pods 3.2.0 
Elementor 3.20.2
