### ISSUE TITLE
[Feature Request] Custom Animations

### ISSUE THREAD

**Issue by wayheming** [pojome/elementor#6520]
Hello, I know that similar topics have already been created and you said that if there is interest in this feature, then you will add it. Tell me how many queries you need to add a feature like this. Just add a filter so that you can add your CSS animation classes. I can make a pull request if this helps to take a feature. Thank you.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
