### ISSUE TITLE
template not loading

### ISSUE THREAD

**Issue by alexkid2001** [pojome/elementor#6521]
hello.
I have bug with themplate.
After click "Add template"
http://prntscr.com/lxwmp1
show windows with loader, but nothins loding
http://prntscr.com/lxwnbj

in console I have error 
http://prntscr.com/lxwobz

**Comment by YuanZhencai** [comment]
always loading
![image](https://user-images.githubusercontent.com/4961592/50376223-53cd8a00-0645-11e9-8c97-13a7074aa38b.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
