### ISSUE TITLE
Vertical Positioning of Images in the Gallery Widget

### ISSUE THREAD

**Issue by jakedeg** [pojome/elementor#6522]
I am trying to make a grid of client logos. They are image files but are always different dimensions and aspect ratios from each other. I want a grid that is easy to modify the column count and easy to re-arrange the clients as necessary. I would like to use the Image Gallery widget, but the problem is that it does not allow me to vertically-center images of various heights. So when I have a row with 4 different images at 4 different heights, the shorter ones float to the top and look bad.

So, I'm having to settle for just using image blocks within columns with the content middled. But this is really bad for re-arranging or changing column count. 

Please add a "vertical placement" property for the image gallery widget.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, This can be easily done via Custom CSS, for example:
```CSS
.gallery figure.gallery-item {
    vertical-align: middle;
}
```
Thanks for the feedback.

**Comment by musback** [comment]
+1 for this one, very handy when you're posting a bunch of logo's or icons
