### ISSUE TITLE
css in image widget not executed

### ISSUE THREAD

**Issue by FORTE-WP** [pojome/elementor#6523]
Today's new update (2.3.8) made some changes to my website. Trying to correct it, I found that the css in the image widget was not executed anymore (selector {float: left;}). Strangely the preview is OK, but the live website does not have the same css. For this bug I made a work around in the containing inner section for now, with reference to the exact element number, but that is not how it is supposed to be :-)  I also work with pro 2.3.1, and the 'Hello' theme.

**Comment by FORTE-WP** [comment]
Today's new update (2.3.8) made some changes to my website. Trying to correct it, I found that the css in the image widget was not executed anymore (selector {float: left;}). I made a work around in the css of the containing inner section for now, with referance to the exact element number, but that is not how it is supposed to be :-) I also work with pro 2.3.1, and the 'Hello' theme.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
