### ISSUE TITLE
Stretched sections cause jump issue in mobile 

### ISSUE THREAD

**Issue by golamminoo** [pojome/elementor#6524]
Dear Valued Developers,
Hello,

I have an issue with Elementor and would like kindly request for your assist to fix it. I've designed a page using Elementor and in my designed page I've placed stretched section, my goal was to have wider image looks that my theme's width didn't let to do that. My theme's maximum width allows me to add 1360 px images in width, since I wanted to go beyond that size i used Elementor's stretch section option to be able to add wider images in my desired page. After designing the page and checking it in all devices I noticed that in mobile when I scroll up or down the page has tiny jumps in the screen that doesn't look professional. especially it happens and starts mostly from the middle to end of the page. 

I noticed that first and second section even despite having stretch enabled, don't cause jumps and the jump issue starts from the third section to the end of the page. To find the issue I put all the sections to full width and disabled the stretch option, then I checked the page in mobile, the jump issue had been fixed! So I noticed that when I enable stretch option for a section it causes screen jumps in mobile version. 

Maybe it's a bug or something is going wrong somewhere, I just wanted to request for your support that how we can fix this issue? 

Also my important question is if we can leave the stretch option in Elementor for a section OFF and we stretch the section with CSS rules up to the width that we desire? I guess if we can stretch the width of a section with CSS rather than using Elementor's stretch option then the issues can be fixed. 

Here is the link for the page:
https://marionmag.com/gallery

I've recorded a video for demonstrating the issue:

Here is the link for the video:
https://marionmag.com/Page-jump-in-mobile.mp4

Any support from you is Highly appreciated. 
Merry Christmas and Happy New Year to everybody here! 

Best Regards,
Ali

**Comment by artconic** [comment]
This is good feature, adding CSS UI scripting in section template for a global setting, for a consistent layout design

**Comment by golamminoo** [comment]
> This is good feature, adding CSS UI scripting in section template for a global setting, for a consistent layout design

Dear artconic,

Thanks for your quick reply. Adding any width in Global Setting wider than my theme's maximum width only will be effective in designing pages using Elementor? and My theme will be intact in other pages?

Thank you for your further assist.

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
