### ISSUE TITLE
directional control on "media Carousel widget" and "slides"

### ISSUE THREAD

**Issue by Dippytop** [pojome/elementor#6525]
hi i would like to see a control for the slides to automate to the left or to the right, at the moment there is no control at all it is set to run in one direction.

i wondered what it would look like to have several slide frames stacked on top of each other and then each row would sliding in alternate directions.  it would be like an animated gallery....

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
