### ISSUE TITLE
Trying to append to a select control when iframe is loaded.

### ISSUE THREAD

**Issue by CodeCurosity** [pojome/elementor#6526]
Hi,
I am trying to append new options to a select control when editor or iframe is completely laoded, i have tried everything but it always says :` Uncaught TypeError: Cannot read property 'contentWindow' of null`
I need to populate a select with the content of iframe, any ideas how can i make it work?

**Comment by bainternet** [comment]
@CodeCurosity 

Without seeing your code, there is no way for us to help you.

thanks
