### ISSUE TITLE
Editor Role 

### ISSUE THREAD

**Issue by DesignGeek2** [pojome/elementor#653]
Hi, i have started using Elementor for all my websites however, i just hit a issue, i need to give editors permission to edit text and change images but not add widgets or change any of the settings. i have used VC in the past and i can give them the permissions to just edit the elements. 

is this something that can be done? 

thanks

**Comment by arielk** [comment]
We call it "Advanced Role manager". This feature is probably going to be a part of the upcoming Elementor PRO. Stay tuned!

**Comment by DesignGeek2** [comment]
is there any way we do this with the current version? or have you any update on the pro version being available?

**Comment by arielk** [comment]
For now, unfortunately not, I hope the pro revision will be released in the coming months
