### ISSUE TITLE
Not loading templates

### ISSUE THREAD

**Issue by alexkid2001** [pojome/elementor#6532]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor v2.3.8
when I try to open templates, opens  load window and nothing heppen. always loading
http://prntscr.com/lxwnbj

in the object inspector has error 
http://prntscr.com/lxwobz

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.13-6
	PHP Version: 7.2.9
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 7: Failed to connect to my.elementor.com port 443: Connection timed out)

== WordPress Environment ==
	Version: 5.0.2
	Site URL: http://irkremont.ru
	Home URL: http://irkremont.ru
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: ru-RU
	Timezone: 3
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.9
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: ru_RU
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

== Active Plugins ==
	Elementor
		Version: 2.3.8
		Author: Elementor.com

== Debug ==
	Errors: 
		TypeError: l.categories is null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.8 - 2:141590
			2018-12-23 14:18 +00:00

		TypeError: Cannot read property 'indexOf' of null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.8 - 2:141610
			2018-12-22 07:17 +00:00
			x 3 times

		TypeError: l.categories is null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.8 - 2:141590
			2018-12-22 06:38 +00:00

		TypeError: Cannot read property 'indexOf' of null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.6 - 2:141544
			2018-12-21 06:38 +00:00
			x 3 times

		TypeError: l.categories is null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.6 - 2:141524
			2018-12-20 19:51 +00:00

		TypeError: Cannot read property 'indexOf' of null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.6 - 2:141544
			2018-12-20 07:27 +00:00

		TypeError: l.categories is null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.6 - 2:141524
			2018-12-20 07:09 +00:00
			x 9 times

		TypeError: t is undefined
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.6 - 2:167659
			2018-12-20 06:45 +00:00

		TypeError: l.categories is null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.6 - 2:141524
			2018-12-20 06:45 +00:00
			x 2 times

		TypeError: Cannot read property 'indexOf' of null
			at http://irkremont.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.6 - 2:141544
			2018-12-20 06:44 +00:00

				
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@alexkid2001 

We can't replicate,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
