### ISSUE TITLE
elementor page builder not opneing showing error

### ISSUE THREAD

**Issue by ranjit7** [pojome/elementor#6535]
I do all the changes as suggested in tiger721.com/frozen and learn more option but this “”Preview could not be loaded’?”” the problem is still happening.
how to resolve it….?

debug error at elementor siteinfo showing this–> siteurl/wp_content/plugins/elementor/assets/js/editor.min.js?ver=2.3.1 – 2:250371
2018-11-18 11:44 +00:00

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
