### ISSUE TITLE
Compatibility issue with Tickera plugin

### ISSUE THREAD

**Issue by artscan** [pojome/elementor#6541]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

With Tickera plugin installed and activated, when I try to edit any pages created with Elementor, it shows the "Preview could not be loaded" message. If I deactivate Tickera, Elementor loads normally. 

## Steps to reproduce

Install and activate/deactivate Tickera plugin

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Latest Wordpress version 5.0.2
```
</details>

**Comment by bainternet** [comment]
We can't replicate,

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by artscan** [comment]
It turned out to be a server memory limit issue. Had to bump it up substantially, though.
