### ISSUE TITLE
Header Template is causing conflicts

### ISSUE THREAD

**Issue by CodeCurosity** [pojome/elementor#6544]
As soon as i activate header template my JavaScript function throws an error that it is not a function, when i disable header template it works fine, how can i make sure this doesn't happen?

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
