### ISSUE TITLE
Is it possible to add a custom class to the section dynamically?

### ISSUE THREAD

**Issue by CodeCurosity** [pojome/elementor#6546]
Is it possible to do this.

`$this->add_render_attribute( 'section', 'class', 'my-wrapper' );
`

I know we can do this in a section but i want this to be added dynamically once my custom widget is added to that specific section.

**And by section i mean `<section> `not the widget wrapper.**

**Comment by bainternet** [comment]
@CodeCurosity 	

No, the widget is not aware to the section it's in, so there is no way, other than JavaScript.
