### ISSUE TITLE
Things not closing automatically [BUG/FEATURE REQUEST]

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#6547]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## The problem:
A lot of things in the ui won't close automatically after you done with them (let's say you click outside of them.

**For example:**
The color pickers:
![2018-12-25 17 47 20](https://user-images.githubusercontent.com/23374215/50424482-35e26e00-086d-11e9-8953-cf9121a6dc7f.gif)

The conditions window:
![2018-12-25 17 44 55](https://user-images.githubusercontent.com/23374215/50424461-e0a65c80-086c-11e9-9786-b585e5dfb11f.gif)

I Think it's a basic ui behaviour that when missing makes you click a lot more then you should and makes the workflow less fluent. 

And if you type a color in the color picker and press enter for example i think it also should close the color picker box.

## Steps to reproduce
Use Elementor for some time... :)

**Comment by shilo-ey** [comment]
Hi @bentalgad,

Thanks for your feedback.

the color picker issue is something that we are aware of, and currently trying to resolve, including replacing the color picker control altogether.


As for the bottom settings drawer, it's working as it should, and not supposed to collapse when clicking outside of it.

thanks,

**Comment by bentalgad** [comment]
Ok, I think it should (If i user clicks on a widget for example, it means is not active on the bottom setting now, and he probably want's to dee the full area, i know i do), but that's your decision of course! Thanks anyway! i think there are a few other stuff that should collapse and don't but i don't have the time right to know to search, if i will notice something else i will update here.
