### ISSUE TITLE
Eye Dropper [FEATURE REQUEST]

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#6548]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Please Add Eye Dropper to the color pickers so you can easily add colors which are used on the site, like chrome dev tools has (and a lot of other apps of course).

![2018-12-26 09 17 44](https://user-images.githubusercontent.com/23374215/50436547-2b68b880-08ef-11e9-8903-8bbbff027687.gif)

Now i know there is the options the use the color preset with the colors you set, but:
1. It is limited to 8 colors only.

2. Some times it's just more intuitive to use the eye dropper. that's why google has it even though they also let you set preset colors.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

We are thinking of implementing a new color picker control that will be more flexible.

Thanks for the feedback.
