### ISSUE TITLE
How to default value for setting in "Advanced Tab" of a widget?

### ISSUE THREAD

**Issue by dtmgs** [pojome/elementor#6549]
Hi There,

Kindly refer the below screenshot,
http://prntscr.com/lzn7x5

My question is, How to set default value for a setting in "Advanced Tab" of a widget?

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


Thanks.

**Comment by dtmgs** [comment]
Thank you :)
