### ISSUE TITLE
Developer API

### ISSUE THREAD

**Issue by Nirvsoner** [pojome/elementor#655]
Hi guys, I really love this new pagebuilder, would like to know what is the estimate for Developer API launch? I would like to do some premium wordpress themes for sale and I think elementor is great for this, things I want to achieve:

Create my own Elementor native widgets,
Set some default settings like colors and fonts when the user actives the plugin + theme.

Is there a way(hook/function) to set some defaults of the widget inside my theme?

Regards
Joel

**Comment by arielk** [comment]
Hi @Nirvsoner Thank you for your kind feedback!

Your question has been asked before (#26, #291), along with a bunch of other [Developer API](https://github.com/pojome/elementor/labels/developer api) related issues. We are working on the API and hopefully it will be released in a couple of weeks.

**Comment by arielk** [comment]
We have recently released the official Elementor API documentation, available here: https://github.com/pojome/elementor/tree/master/docs

The API includes an explanation about how to extend Elementor.
