### ISSUE TITLE
[Feature Request] Post widget image size settings

### ISSUE THREAD

**Issue by joexcm** [pojome/elementor#6551]
As we know, the post widget is still in early days.
However I need the image: 'size: default/auto/cover/contain' option for my post images, otherwise I get white bars due to narrow images on mobile. See example:
![screenshot_2018-12-26-18-34-39](https://user-images.githubusercontent.com/28928683/50454075-0d29a980-093d-11e9-8791-d3a1e887e9d3.png)

**Describe the solution you'd like**
I'd like to see the much more mature 'background image' settings transferred to the posts widget.

**Comment by bainternet** [comment]
should be possible with #4440 
thanks.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
