### ISSUE TITLE
 Endless loading of Elementor

### ISSUE THREAD

**Issue by aesaulov** [pojome/elementor#6553]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

Endless loading of Elementor.

console:
SyntaxError: missing ) after argument list[Подробнее] wp-tinymce.php:2:259044
ReferenceError: tinymce is not defined[Подробнее] post.php:31:1
SyntaxError: unexpected token: keyword 'var'[Подробнее] load-scripts.php:26:418
ReferenceError: jQuery is not defined[Подробнее] mediaelement-migrate.min.js:1:1
ReferenceError: jQuery is not defined[Подробнее] wp-mediaelement.min.js:1:1
ReferenceError: jQuery is not defined[Подробнее] api-request.min.js:1:1
ReferenceError: jQuery is not defined[Подробнее] media-views.min.js:1:974
ReferenceError: jQuery is not defined[Подробнее] media-editor.min.js:1:1
TypeError: wp.media is undefined[Подробнее] media-audiovideo.min.js:1:1663
ReferenceError: jQuery is not defined[Подробнее] media-widgets.min.js:1:1
TypeError: wp.mediaWidgets is undefined[Подробнее] post.php:2392:1
TypeError: wp.media is undefined[Подробнее] media-audio-widget.min.js:1:37
TypeError: wp.mediaWidgets is undefined[Подробнее] post.php:2397:1
ReferenceError: jQuery is not defined[Подробнее] media-image-widget.min.js:1:1
TypeError: wp.mediaWidgets is undefined[Подробнее] post.php:2405:1
TypeError: wp.media is undefined[Подробнее] media-gallery-widget.min.js:1:37
TypeError: wp.mediaWidgets is undefined[Подробнее] post.php:2413:1
TypeError: wp.media is undefined[Подробнее] media-video-widget.min.js:1:37
TypeError: wp.mediaWidgets is undefined[Подробнее] post.php:2421:1
TypeError: a is not a function[Подробнее] editor.min.js:1:10883
TypeError: b is not a function[Подробнее] wp-a11y.min.js:1:448
ReferenceError: jQuery is not defined[Подробнее] text-widgets.min.js:1:1
TypeError: wp.textWidgets is undefined[Подробнее] post.php:2434:1
ReferenceError: jQuery is not defined[Подробнее] custom-html-widgets.min.js:1:1
TypeError: wp.customHtmlWidgets is undefined[Подробнее] post.php:2439:1
ReferenceError: Backbone is not defined[Подробнее] load-scripts.php:1:1746
TypeError: a is undefined[Подробнее] backbone.marionette.min.js:22:348
TypeError: right-hand side of 'in' should be an object, got undefined[Подробнее] backbone.radio.min.js:3:661
TypeError: a.extend is not a function[Подробнее] dialog.min.js:3:204
ReferenceError: Marionette is not defined[Подробнее] common.min.js:2:36188
ReferenceError: jQuery is not defined[Подробнее] heartbeat.min.js:1:1
ReferenceError: jQuery is not defined[Подробнее] wp-auth-check.min.js:1:1
ReferenceError: jQuery is not defined[Подробнее] resizable.min.js:11:52
ReferenceError: jQuery is not defined[Подробнее] tipsy.min.js:1:1
ReferenceError: jQuery is not defined[Подробнее] e-select2.full.min.js:1:168
window.controllers/Controllers является устаревшим. Не используйте его для определения UA. ace.js:1:18446
ReferenceError: jQuery is not defined[Подробнее] jquery-hover-intent.min.js:1:1
ReferenceError: jQuery is not defined[Подробнее] editor.min.js:2:81468
ReferenceError: jQuery is not defined[Подробнее] slider.min.js:11:52
ReferenceError: jQuery is not defined[Подробнее] jquery.ui.touch-punch.js:11:2
ReferenceError: jQuery is not defined[Подробнее] iris.min.js:4:1
ReferenceError: jQuery is not defined[Подробнее] color-picker.min.js:1:1
ReferenceError: jQuery is not defined[Подробнее]

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Unix)
	MySQL version: (LTD BeGet) v5.7.21-20
	PHP Version: 7.1.11
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1047527424
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.2
	Site URL: http://new.rawi.ru
	Home URL: http://new.rawi.ru
	WP Multisite: No
	Max Upload Size: 999 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: ru-RU
	Timezone: 3
	Debug Mode: Inactive

== Theme ==
	Name: Sydney RAWI
	Version: 
	Author: RAWI
	Child Theme: No
	Parent Theme Name: Sydney
	Parent Theme Version: 1.53
	Parent Theme Author: aThemes

== User ==
	Role: administrator
	WP Profile lang: ru_RU
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

== Active Plugins ==
	Elementor
		Version: 2.3.8
		Author: Elementor.com


== Debug ==
	Errors: 
		TypeError: this.search is undefined
			at http://new.rawi.ru/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.8 - 2:250852
			2018-12-23 21:32 +00:00
			x 2 times

				
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 


* Steps to replicate.
* Isolating the problem.


please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.
