### ISSUE TITLE
Icon List element causes horizontal scroll

### ISSUE THREAD

**Issue by h71** [pojome/elementor#6558]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Setting space between option for icon list element causes horizontal scroll on mobile.
Screenshot: https://monosnap.com/file/Fzn4wRwA0UVGY7FKCLDy61u3QmKIdW

## Steps to reproduce
1. Add icon list element.
2. Switch to mobile view.
3. Change space between option from zero to 50 and see the horizontal scroll.

Note: This issue is visible on front-end after saving the changes.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Tested in Twenty-Sixteen theme & WordPress 5.0.2.

**Comment by shilo-ey** [comment]
Hi @h71 

This has been fixed in Elementor 2.4.6.

Feel free to update!

thanks.
