### ISSUE TITLE
Wrong selector in products element

### ISSUE THREAD

**Issue by h71** [pojome/elementor#6559]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Elementor Pro:
modules\woocommerce\widgets\products-base.php Line 444.

There is 2 dots instead of only one in selector and because of it we miss the border color for hover state of buttons.

https://monosnap.com/file/jci7Pr4BmhpzNSSaSRoiXIpUX1zzwV

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @h71 ,

Thanks for your feedback,

We will look into it and patch it as soon as possible.
