### ISSUE TITLE
Pages not saving

### ISSUE THREAD

**Issue by samidesign** [pojome/elementor#656]
The green saving bar across the top reaches about 98% before it freezes. Working from a saved page, this happens with the addition of section or a color change. 

The wordpress site is hosted on Enom and is currently using the provided domain that they gave.

*note: I am new to wordpress and elementor.

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
