### ISSUE TITLE
[Feature Request] Text Area Character Count Limit

### ISSUE THREAD

**Issue by dasignlady** [pojome/elementor#6561]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

I would like to see a  max character count option for the message / text area portion of the form widget. This would greatly limit spammers from using our forms to sell their products and services.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


For now, you can use this snippet to have server-side validation for a Textarea char count limit,

```PHP
add_action( 'elementor_pro/forms/validation/textarea', function( $field, $record, $ajax_handler ) {

    // make sure ts the correct textarea field
	if ( 'YOUR_FIELD_ID' === $field['id'] ) {
		return;
	}

    if ( strlen( $field['value'] ) > 250 ) {
        $ajax_handler->add_error( $field['id'], 'The max number of chars allowed is 250' );
    }
}, 10, 3 );
```
Thanks for the feedback.
