### ISSUE TITLE
what is the elementor hook after loaded preview?

### ISSUE THREAD

**Issue by mohammadamindeldari** [pojome/elementor#6562]
I use elementor-plugin and I want to add script after loaded all widgets and preview page. I use owl-carousel Jquery plugin in elementor. But my codes don't get any element in elementor preview page. 
Below is function.php file code:-
```

function load_custom_script() {
    wp_enqueue_script(
        'custom',
        get_template_directory_uri() . '/assets/js/custom.js',
        true
    );   
}

add_action( 'elementor/preview/enqueue_scripts','load_custom_script');

```

**Comment by bainternet** [comment]
You mean in JS?
https://code.elementor.com/js-hooks/

**Comment by JonathanAlumbaugh** [comment]
Updated URL for future visitors is https://developers.elementor.com/docs/hooks/js/ (doesn't appear in docs when searching "hooks", only when searching "JS hooks").
