### ISSUE TITLE
MetaSlider and Elementor 

### ISSUE THREAD

**Issue by medieskolenlyngby** [pojome/elementor#6564]
The SlideShow-plugin MetaSlider works with Elementor BUT for some reason the WYSIWYG-feeling in the backend is lost (I use the MetaSlider block).

instead of the first image the settings of the plugin are displayed …. any chance that this could be fixed?

The MetaSlider works fine “frontend”

You can see a screenshot of the problem here

![metaslider-elementor-problem](https://user-images.githubusercontent.com/17617010/50542540-1eceb380-0bc0-11e9-8052-e82f6de54f92.jpg)

I've asked on [wordpress' support-forum ](https://wordpress.org/support/topic/elementor-metaslider-not-wysiwyg-but-works/)and the Plugin Contributor ( kbatdorf(@kbat82) ) answered:

> That page should only show if the conditional is_admin() is true. It might be something to show the Elementor creators as I don’t think they want that to happen. We basically only use that to determine if the plugin should show an admin built slide or a public facing slide:
> 
> if ( is_admin() && current_user_can( $capability ) ) {
> 	return $this->get_admin_slide();
> }
> 
> return $this->get_public_slide();
> 
> If you know of a similar conditional for Elementor I could add it in to add an extra check, something like:
> 
> if (!is_elementor() && is_admin() && current_user_can( $capability ) ) {
> 

I hope someone will fix this :-)

**Comment by joshmarom** [comment]
Elementor provides two methods that can be used to determine weather the post is currently in the editor.
[is_edit_mode()](https://code.elementor.com/methods/elementor-editor-is_edit_mode/) and 
[is_preview_mode()](https://code.elementor.com/methods/elementor-preview-is_preview_mode/)

**Comment by shilo-ey** [comment]
Hi @medieskolenlyngby ,
Thanks for your feedback.

As @joshmarom mentioned, Elementor uses different methods to identify if the user is in editing mode.

The MetaSlider widget is a WordPress widget which not fully compatible with Elementor. 
You can contact MetaSlider developers and direct them here or better yet, ask them to create an Elementor dedicated widget for full compatibility.

Thanks.

**Comment by KevinBatdorf** [comment]
Hi @shilo-ey,

Kevin from MetaSlider here. The reason this is happening is because when inside Elementor's "preview mode" `is_admin()` is `true` and therefore MetaSlider renders slides as if it's on an admin page. I believe Elementor used to render on the front end but seems that has changed to admin context? 

If I add a filter to the part of our code that determines this, can you add this to your plugin?

Something like:
```php
if ( is_admin() && !apply_filters('metaslider_force_public_slide', true) ) {
     return $this->get_admin_slide();
}
return $this->get_public_slide();
```

Thanks

**Comment by KevinBatdorf** [comment]
On second thought this wont be necessary. I'll just limit the admin calls to our specific page and render the public slides everywhere else.
