### ISSUE TITLE
[bug] Unable to edit pages - ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by alpha-leonis** [pojome/elementor#6569]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After updating to newest Elementor + Elementor Pro I am unable to edit any of pages. After clicking on "Edit with Elementor" I get white page and no loading screen. I tried it on different browsers. I tried to search issue in Google, disabled any other plugins, flushed dns, incrased memory limit etc.

There is following error in Console.
Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR    post.php?post=5&action=elementor:1 

This is the source code of blank page:
`<html lang="pl-PL"><head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Elementor | Strona głowna</title>
	<link rel="stylesheet" id="dashicons-css" href="https://****.pl/wp-includes/css/dashicons.min.css?ver=4.9.8" type="text/css" media="all">
<link rel="stylesheet" id="editor-buttons-css" href="https://****.pl/wp-includes/css/editor.min.css?ver=4.9.8" type="text/css" media="all">
		<script type="text/javascript">
		window.wp = window.wp || {};
		window.wp.editor = window.wp.editor || {};
		window.wp.editor.getDefaultSettings = function() {
			return {
				tinymce: {theme:"modern",skin:"lightgray",language:"pl",formats:{alignleft: [{selector: "p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li", styles: {textAlign:"left"}},{selector: "img,table,dl.wp-caption", classes: "alignleft"}],aligncenter: [{selector: "p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li", styles: {textAlign:"center"}},{selector: "img,table,dl.wp-caption", classes: "aligncenter"}],alignright: [{selector: "p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li", styles: {textAlign:"right"}},{selector: "img,table,dl.wp-caption", classes: "alignright"}],strikethrough: {inline: "del"}},relative_urls:false,remove_script_host:false,convert_urls:false,browser_spellcheck:true,fix_list_elements:true,entities:"38,amp,60,lt,62,gt",entity_encoding:"raw",keep_styles:false,cache_suffix:"wp-mce-4800-20180716",resize:"vertical",menubar:false,branding:false,preview_styles:"font-family font-size font-weight font-style text-decoration text-transform",end_container_on_empty_block:true,wpeditimage_html5_captions:true,wp_lang_attr:"pl-PL",wp_keep_scroll_position:false,wp_shortcut_labels:{"Heading 1":"access1","Heading 2":"access2","Heading 3":"access3","Heading 4":"access4","Heading 5":"access5","Heading 6":"access6","Paragraph":"access7","Blockquote":"accessQ","Underline":"metaU","Strikethrough":"accessD","Bold":"metaB","Italic":"metaI","Code":"accessX","Align center":"accessC","Align right":"accessR","Align left":"accessL","Justify":"accessJ","Cut":"metaX","Copy":"metaC","Paste":"metaV","Select all":"metaA","Undo":"metaZ","Redo":"metaY","Bullet list":"accessU","Numbered list":"accessO","Insert\/edit image":"accessM","Remove link":"accessS","Toolbar Toggle":"accessZ","Insert Read More tag":"accessT","Insert Page Break tag":"accessP","Distraction-free writing mode":"accessW","Keyboard Shortcuts":"accessH"},content_css:"https://polskiinstytutmody.pl/wp-includes/css/dashicons.min.css?ver=4.9.8,https://****.pl/wp-includes/js/tinymce/skins/wordpress/wp-content.css?ver=4.9.8",toolbar1:"bold,italic,bullist,numlist,link",wpautop:false,indent:true,elementpath:false,plugins:"charmap,colorpicker,hr,lists,paste,tabfocus,textcolor,fullscreen,wordpress,wpautoresize,wpeditimage,wpemoji,wpgallery,wplink,wptextpattern"},
				quicktags: {
					buttons: 'strong,em,link,ul,ol,li,code'
				}
			};
		};

					var tinyMCEPreInit = {
				baseURL: "https://****.pl/wp-includes/js/tinymce",
				suffix: ".min",
				mceInit: {},
				qtInit: {},
				load_ext: function(url,lang){var sl=tinymce.ScriptLoader;sl.markDone(url+'/langs/'+lang+'.js');sl.markDone(url+'/langs/'+lang+'_dlg.js');}
			};
					</script>
		<script type="text/javascript" src="https://****.pl/wp-includes/js/tinymce/tinymce.min.js?ver=4800-20180716"></script></head></html>`

## Steps to reproduce

I updated Elementor to v. 2.3.8, opened any page from "Pages" and clicked "Edit with Elementor".

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.36-83.0
	PHP Version: 7.0.30-dh10
	PHP Max Input Vars: 6000
	PHP Max Post Size: 8192M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://****.pl
	Home URL: https://****.pl
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: 0
	Admin Email: ****
	Debug Mode: Inactive

== Theme ==
	Name: ****
	Version: 1.0.0
	Author: ****
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.4.10
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	404page - your smart custom 404 error page
		Version: 7
		Author: Peter Raschendorfer

	Advanced Custom Fields
		Version: 5.7.9
		Author: Elliot Condon

	Advanced Custom Fields PRO
		Version: 5.7.9
		Author: Elliot Condon

	Advanced Forms
		Version: 1.5.5
		Author: Fabian Lindfors

	Anywhere Elementor
		Version: 1.1
		Author: WebTechStreet

	Contact Form 7
		Version: 5.1.1
		Author: Takayuki Miyoshi

	Custom Fonts
		Version: 1.0.6
		Author: Brainstorm Force

	Custom Post Type UI
		Version: 1.6.1
		Author: WebDevStudios

	Elementor
		Version: 2.3.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.3.1
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.7
		Author: ExactMetrics

	Header, Footer & Blocks for Elementor
		Version: 1.1.1
		Author: Brainstorm Force, Nikhil Chavan

	JetBlog For Elementor
		Version: 2.1.9
		Author: Zemez

	Jet Elements For Elementor
		Version: 1.14.8
		Author: Zemez

	JetMenu
		Version: 1.5.4
		Author: Zemez

	Jet Tabs For Elementor
		Version: 1.1.3
		Author: Zemez

	JetTricks
		Version: 1.1.6
		Author: Zemez

	LiteSpeed Cache
		Version: 2.8.1
		Author: LiteSpeed Technologies

	Loco Translate
		Version: 2.2.0
		Author: Tim Whitlock

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

	Smush
		Version: 3.0.2
		Author: WPMU DEV

	Use Any Font
		Version: 5.0
		Author: Dinesh Karki

	WP Config File Editor
		Version: 1.6.7
		Author: AHMeD SAiD


== Debug ==
	Errors: 
		TypeError: Cannot read property 'children' of undefined
			at https://****.pl/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.1.10 - 2:26864
			2018-10-12 14:55 +00:00
			x 2 times

		ViewDestroyedError: View (cid: "view551") has already been destroyed and cannot be used.
			at https://****.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-10-12 10:39 +00:00

		TypeError: n.attributes[t.name].each is not a function
			at http://****.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:9151
			2018-10-04 20:17 +00:00
			x 2 times

		ViewDestroyedError: View (cid: "view527") has already been destroyed and cannot be used.
			at http://****.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-10-04 17:14 +00:00

		ViewDestroyedError: View (cid: "view580") has already been destroyed and cannot be used.
			at http://****.pl/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-10-04 17:00 +00:00

		TypeError: n.attributes[t.name].each is not a function
			at http://****.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:9151
			2018-10-04 15:24 +00:00
			x 2 times

		TypeError: Cannot read property 'currentView' of undefined
			at http://****.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:239133
			2018-09-21 13:21 +00:00

		TypeError: Cannot read property 'on' of null
			at http://****.pl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.11 - 2:82298
			2018-05-11 18:02 +00:00

		TypeError: Cannot read property 'style' of undefined
			at http://****.pl/wp-admin/js/editor.min.js?ver=4.9.5 - 1:694
			2018-05-11 18:02 +00:00

		TypeError: Cannot read property 'query' of null
			at http://****.pl/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1 - 1:61214
			2018-05-11 15:55 +00:00


```
</details>

I appreciate any help :)

**Comment by bainternet** [comment]
@alpha-leonis 	


We can't replicate, 
`ERR_SPDY_PROTOCOL_ERROR` is an error in the Chrome browser which can appear for some different reasons, but elementor has no control over it nor can it cause this error, possible solutions:

### 1. Restarting your browser
When you face this error, you can close your chrome browser and start it again. It should fix ERR_SPDY_PROTOCOL_ERROR. While this is a simple fix, it is the quickest way to solve this error.


### 2. Make sure your Chrome browser is up to date
You can easily update your Chrome browser via the settings menu on the upper right of your browser window, and selecting "About Chrome".


### 3. Use Chrome’s Incognito Mode
If you face ERR_SPDY_PROTOCOL_ERROR for any specific website, you can try to access that website in incognito mode.

### 4. Flushing DNS and Renewing IP
Flushing DNS and Renewing IP can solve ERR_SPDY_PROTOCOL_ERROR sometimes.

#### To flush DNS:

Open Command Prompt.
Type ipconfig /flushdns and press Enter.
To Renew IP:

#### Open Command Prompt.
Type ipconfig /release and press Enter.
Again type ipconfig /renew and press Enter.
Note: You may need to also configure your internet connection.


### 5.  Flushing SPDY Sockets
To flush SPDY sockets:

Go to chrome://net-internals/#events&q=type:SPDY_SESSION%20is:active from your chrome browser.
Then click on the arrow of the top right corner.
From the drop-down menu select Flush Sockets.

thanks.
