### ISSUE TITLE
Editing a page with Elementor - not visible in the edit page screen

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#657]
One edits a page with Elementor.
One sees this in the edit page screen.

![screen shot 2016-09-27 at 15 54 24](https://cloud.githubusercontent.com/assets/5323259/18889545/6b853e98-84cb-11e6-8069-f05ffbb55e3a.png)

Meaning there is no sign in this edit page screen that the page has been edited with Elementor.
- I am missing a preview or somekind of screen seen in the edit area giving a clear signal that this page has been edited with Elementor.
  Either a preview or a default "this page is made with Elementor" - construction sign -.

Here is a preview:

![elementor-edited-with](https://cloud.githubusercontent.com/assets/5323259/18889630/c8d29316-84cb-11e6-8cab-62269841319b.jpg)
1. The text in the Elementor button has changed.
2. I added a preview of the Elementor page into the edit area of the page. (Or add the Elementor construction sign saying that the contents of the page is edited with Elementor click to edit or something like that.)

If the user clicks into the edit area of the page it automatically launches Elementor so the user can edit the page.

**Comment by WPDevHQ** [comment]
If the page had already been edited with Elementor the screenshot below is what you should have 

![editedwithelementor](https://cloud.githubusercontent.com/assets/16872407/19006266/8b9b76e2-8756-11e6-9df9-1165567ecab8.png)

Looking at your first screenshot it appears as though the page hasn't been edited by Elementor yet. If it has, were you getting the image I posted before or not at all? 

Or have you clicked on "Back to WordPress editor" and are therefore suggesting that the Elementor button should be enhanced to reflect what you stated. Just trying to get some clarification as the first impresion I got was that's how it is either way.

**Comment by paaljoachim** [comment]
I made a wireframe showing a preview of the content + the text in the button "edited with Elementor"... 

Caldera Forms after having added the form to a page shows a preview of the form inside the page/post content area. It would be nice to get a preview of the Elementor page inside the backend content area.

**Comment by arielk** [comment]
Unfortunately we don't plan to do this feature, so I closed this issue for now.

Thanks for your feedback!
