### ISSUE TITLE
Global Widgets: Allow renaming of widget

### ISSUE THREAD

**Issue by wooge** [pojome/elementor#6583]
Would be great if one could rename a Global Widget after it was created — through the admin interface.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by plucker** [comment]
I would like to be able to have this ability too

**Comment by ellroberts** [comment]
just been searching for this option and ended up here. I'd also find this helpful to have

**Comment by groovybluedog** [comment]
This really would be helpful, fustrating they closed this though. 

So I made a new one.

https://github.com/elementor/elementor/issues/11208

**Comment by jess8bit** [comment]
Still not possible :(

**Comment by RickMyles99** [comment]
Yes, and also open up a global widget independent of any page.

**Comment by groovybluedog** [comment]
One day... :c

**Comment by global-H** [comment]
Honestly, this is clearly a simple and very much wanted feature -- please Elementor, stop closing issues without at please replying to your customers!

**Comment by amigoow** [comment]
Please add this simple feature.

**Comment by Franz333** [comment]
I am in !
