### ISSUE TITLE
Contact Form in "elementor fullwidth blank" template

### ISSUE THREAD

**Issue by OseekerM** [pojome/elementor#659]
Hello, 

there is a situation with a contact form, i use the Caldera Forms, when the page template elementor fullwidth blank, upon successful completion of the form by clicking on the send button, the page scrolls to the top, and the user does not see a successful message filling the form.

How is it possible to solve this situation, the form is in the bottom of the page.

Thanks

**Comment by WPDevHQ** [comment]
Unable to replicate the issue on my install.

Could I ask to provide an export file of your form please? Aditional information as theme in use, addon caldera form plugins and settings will also be of great help in debugging the issue

**Comment by OseekerM** [comment]
Of course, here is a link to the site and configuration, and screenshots. http://landing.aimart.me
![forms](https://cloud.githubusercontent.com/assets/22492121/19012262/aaa890f6-87b0-11e6-91f0-69d18c02194e.png)
![settings](https://cloud.githubusercontent.com/assets/22492121/19012261/aaa473a4-87b0-11e6-97e6-59f10aeb898c.png)
![theme](https://cloud.githubusercontent.com/assets/22492121/19012263/aaa9bbe8-87b0-11e6-82f3-a444b93a6380.png)

[Uploading test-export.zip…]()

**Comment by WPDevHQ** [comment]
I've had issues with some of the library templates on the Sydney theme and one of those is se the lodo slider section as youcan see on your site - the columns are stucked up instead of being next to each other and the they are not sliding. This is down to how Sydney loads its assets namely the javascripts and I'm still trying to figure out a solution for it.

Can you see if you get the same problem with the default theme?

**Comment by WPDevHQ** [comment]
BTW, that zip file did not upload correctly.

**Comment by OseekerM** [comment]
Right, I assumed that the situation in the incompatibility of the theme because when elementor editor viewed in mobile mode, the whole layout in place, but it is worth to see the site (another project) on a device such as nexus4, the layout is already floating.

tested on Twenty Sixteen, the form is working correctly and the slider also displays correctly,
can you tell me what theme besides "default" there are no such situations?


[test-export.zip](https://github.com/pojome/elementor/files/504905/test-export.zip)

Thanks

**Comment by WPDevHQ** [comment]
Sorry for the delay - been supper busy weekend and still going. Will take a closer look at the plugin and Sydney later this week to see what can be done to fix the issue.

As for themes, [GeneratePress](https://wordpress.org/themes/generatepress/) comes highly recommended by the [Elementor Community](https://www.facebook.com/groups/Elementors/) group on FB. If you are looking for a base theme that you can build upon with a child theme then I'd recommend my own theme: [Actions](https://wordpress.org/themes/actions/) - comes with a tone of action hooks as the name suggests :)

For a paid theme then you really cant go wrong with Genesis - the Elementor Templator plugin fully supports Genesis and Elementor.

**Comment by OseekerM** [comment]
Thank you for your help.
