### ISSUE TITLE
Frontend post submission

### ISSUE THREAD

**Issue by moshe-yanai** [pojome/elementor#6590]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

It is not always good for a user to login to your blogs dashboard in order to post an article,
especially if you want to encourage post contribution.

**Describe the solution you'd like**

I would like blog users to be able to publish a post without logging in to the dashboard, an elementor form widget similar to the contact form, to enter the post title, post image, content, category etc. 
and a publisg button to publish or submit for approval. 

**Describe alternatives you've considered**

there is a 3rt party plugin caller "Elementor Frontend Post" I tried using it, It works but has bugs and lacks options. here is their page on wordpress.org - 

https://wordpress.org/plugins/dj-elementor-frontend/

they no longer maintain it unfortunately.

**Additional context**

Thank you, I hope someone sees how much this featue is needed.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by stefanolodola** [comment]
I also want that!
