### ISSUE TITLE
Elementor Pro is not compatible with RankMath Seo.

### ISSUE THREAD

**Issue by anhtuanht** [pojome/elementor#6593]
I use:
WordPress v5.0
Elementor Pro v2.3.4
RankMath Seo v1.0.9
These are the latest versions

But, Elementor Pro is not compatible with RankMath Seo.
I deactivated Elementor, RankMath Seo will work.
Please fix it!
Thanks!

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
