### ISSUE TITLE
3.Post Queries To Show Taxonomies As A Whole Not The Categories and Tags

### ISSUE THREAD

**Issue by willowen100** [pojome/elementor#6594]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve?**
This will allow someone to display all categories/tags within a taxonomy. This will be very effective for those who have setup custom post types and taxonomies and have many categories/tags listed underneath these.[...]

**Describe the solution you'd like**
A user would select the CPT (custom post type) from the 'Post Types' dropdown menu and then based on what was selected in this first dropdown menu would change what is displayed under the 'Taxonomies' dropdown menu. In my case the taxonomies associated with the CPT from the 'Post Types' dropdown menu will selectable in the 'Taxonomies' dropdown menu.

In my example I have a CPT called 'Entertainment'. Under this I have five taxonomies.

```
Entertainment
    TSN Live Battles
    Surge Moments
    Live Streams
    Vlogs
    Q&A's
```
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/93450701@N07/32694653468/in/dateposted-public/" title="Elementor Idea"><img src="https://farm8.staticflickr.com/7924/32694653468_4683869521_b.jpg" width="349" height="731" alt="Elementor Idea"></a>

I would select 'Entertainment' from the 'Post Types' dropdown menu and then select the five taxonomies from the 'Taxonomies' dropdown menu. Currently I have a very long list of categories and tags I have to select. Of course with many CPT's, associated taxonomies and their categories/tags this list becomes very long and confusing. If I were to able to select the taxomony as a whole the categories/tags linked to them will be all added rather having to individually select each one.

<a data-flickr-embed="true"  href="https://www.flickr.com/photos/93450701@N07/44750622520/in/dateposted-public/" title="Elementor Idea 2"><img src="https://farm5.staticflickr.com/4915/44750622520_ac3cee695e_z.jpg" width="298" height="636" alt="Elementor Idea 2"></a>

Hope to hear from someone soon.

Many thanks

Will

**Comment by shilo-ey** [comment]
@willowen100 

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Please be specific with your description, what is the desired output?

**Comment by willowen100** [comment]
I've updated my post.

**Comment by shilo-ey** [comment]
Hi @willowen100, 

We are actively working on this feature.

thanks for your feedback.
