### ISSUE TITLE
Slider Control: style out of range values

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#6605]
The **[Control_Slider](https://code.elementor.com/classes/elementor-control_slider/)** class displays a beautiful range slider next to an `input` field with a `min` and `max` attributes.

### The Problem

The problem is that the user can manually change the value outside of the range.

### The Solution

It would be very nice if Elementor will display some warning when the value is outside the range limits specified by the min/max attributes.

The long/hard way is to validated the field using JS. But the easy solution (one line) is to use the **[:out-of-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:out-of-range)** CSS pseudo class.

```css
input[type=number]:out-of-range {
   background-color: red;
}
```

**Comment by bainternet** [comment]
@ramiy,

We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.
