### ISSUE TITLE
Option for no image in testimonials and testimonial carousel

### ISSUE THREAD

**Issue by iankh1** [pojome/elementor#6606]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It is not practical to assume that a business's customers will want their photo in a testimonial. Need the ability to set up both a testimonial and testimonial carousel with no image. 

**Describe the solution you'd like**
Add an option to the drop down for image size for "None" or "No Image"

**Describe alternatives you've considered**
I have changed the image size in the style tab to zero. This provides a cosmetic solution to the problem but the page is still calling the placeholder.png image. Unnecessary server calls hamper performance, however small.

**Additional context**
Suggested implementation -  screenshot attached

![add no image option](https://user-images.githubusercontent.com/46299702/50614649-760da600-0e96-11e9-9447-0d7124c98148.png)

**Comment by bainternet** [comment]
@iankh1 	

You can simply delete the image and no image will show.

**Comment by iankh1** [comment]
Does it still make calls for the placeholder.png?

**Comment by gwmbox** [comment]
+1

Need this as well please.  I do not want and image at all in my testimonials, but there is no option for none.  If google etc visit the site they will see the placeholder.png file, that needs to be removed not just hidden via CSS.

**Comment by gwmbox** [comment]
Maybe I am a bit dumb, where do I remove the placeholder image?

When I add a testimonial it has an option for an image, but it does not have an option to NOT use an image.  So how do I stop the placeholder.png from being used?

**Comment by gwmbox** [comment]
Some example code I have

`<section class="elementor-element elementor-element-bcf330a testimonial elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-top-section" data-id="bcf330a" data-element_type="section">
--
  | <div class="elementor-container elementor-column-gap-default">
  | <div class="elementor-row">
  | <div class="elementor-element elementor-element-d646d91 elementor-column elementor-col-100 elementor-top-column" data-id="d646d91" data-element_type="column">
  | <div class="elementor-column-wrap  elementor-element-populated">
  | <div class="elementor-widget-wrap">
  | <div class="elementor-element elementor-element-5d3f963e elementor-widget__width-auto testimonial-content elementor-widget elementor-widget-testimonial" data-id="5d3f963e" data-element_type="widget" data-widget_type="testimonial.default">
  | <div class="elementor-widget-container">
  | <div class="elementor-testimonial-wrapper elementor-testimonial-text-align-left">
  | <div class="elementor-testimonial-content">Not just a photo but a real piece of art! Very special work that Michelle produces.​</div>
  |  
  | <div class="elementor-testimonial-meta elementor-has-image elementor-testimonial-image-position-aside">
  | <div class="elementor-testimonial-meta-inner">
  | <div class="elementor-testimonial-image">
  | **<img src="https://mysite.com/wp-content/plugins/elementor/assets/images/placeholder.png" title="" alt="" />**						</div>
  |  
  | <div class="elementor-testimonial-details">
  | <div class="elementor-testimonial-name">Rachel</div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </section>

`

**Comment by gwmbox** [comment]
Some Sample code that shows the placeholder image being used
`<div class="elementor-element elementor-element-43a88fc1 elementor-widget__width-auto testimonial-content elementor-widget elementor-widget-testimonial" data-id="43a88fc1" data-element_type="widget" data-widget_type="testimonial.default">
	<div class="elementor-widget-container">
		<div class="elementor-testimonial-wrapper elementor-testimonial-text-align-left">
			<div class="elementor-testimonial-content">Michelle is not only an amazing photographer and artist, but a simply lovely human who goes out of her way to make sure you are fully happy.​</div>
			
			<div class="elementor-testimonial-meta elementor-has-image elementor-testimonial-image-position-aside">
				<div class="elementor-testimonial-meta-inner">
					<div class="elementor-testimonial-image">
						<img src="https://mysite.com/wp-content/plugins/elementor/assets/images/placeholder.png" title="" alt=""></div>
					
						<div class="elementor-testimonial-details">
							<div class="elementor-testimonial-name">Jo</div>
						</div>
					</div>
				</div>
			</div>
		</div>
</div>`
