### ISSUE TITLE
Form element time with 24h option

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#6610]
When building a form with Elementor and choose the "Time" form-element, there is a AM/PM time switcher in the front-end, but this is not very common in Europe/DE/AT because we are not used to AM/PM but to the 24h system.

Alternative is to switch back to HTML5 but this is not as nice as the input given by Elementor.

**Comment by bainternet** [comment]
@Luxamman 

You can set the time picker to use 24 hours format via JavaScript:

![](https://i.imgur.com/BUJmThd.png)

```JavaScript
// First destroy the instance of current time-picker
var picker = flatpickr( jQuery('.elementor-time-field')[0] );
picker.destroy()

// Then re invoke with new settings:
jQuery('.elementor-time-field').flatpickr(
	{
		noCalendar: true,
		enableTime: true,
		allowInput: true,
		dateFormat: "H:i",
		time_24hr: true
	}
);
```

You will need to wrap this in jQuery Document ready event and wait for flatpickr to load, ex:
```JS
ar timePickerHelper = timePickerHelper || {};
jQuery( document ).ready( function( $ ){
	timePickerHelper = {
		defaultSettings: {
			selector: '.elementor-time-field',
			pickerSettings:{
				noCalendar: true,
				enableTime: true,
				allowInput: true,
			},
		},
		settings: {},
		init: function( options ) {
			this.settings = $.extend( true, {}, this.defaultSettings, options );
			this.waitForFlatpickr( this.callback );
		},
		waitForFlatpickr: function( callback ) {
			if ( typeof window.flatpickr !== 'function' ) {
				setTimeout( function() { timePickerHelper.waitForFlatpickr( callback ) }, 100 );
			}
			callback();
		},
		modifyPicker: function( $element, picker, settings ) {
			flatpickr( picker ).destroy();
			$element.flatpickr( settings );
		},
		callback: function() {
			var self = timePickerHelper;
			$( self.settings.selector ).each( function() {
				var $element =  $( this ),
					picker = $element[0],
					pickerSettings = self.settings.pickerSettings;

				self.modifyPicker( $element, picker, pickerSettings );
			} );
		}
	}
} );
``` 
and Use it like this:
```js
timePickerHelper.init( { pickerSettings: { time_24hr: true } } );
```

**Comment by Luxamman** [comment]
Thanks for your input, I'm not too much into programming and so it is not easy for me or a lot of other people to make that work. 

Also, like said with the datepicker, I would love to see a overall solution, because also this is a "problem" will always reappear because it is handled differently in many countries and regions. So a built-in solution would be much better and more elegant.

Thanks!

**Comment by PVTD** [comment]
Hello,
So where do I put this script stuff? I bought elementor cuz it's easy to use, but don't forget about us europeans :P

**Comment by dasigna** [comment]
oh my gosh ...

you have to fiddle around with java to get the right time format in time picker??
seriously?
cant be true  - isnt it?

come on ...

**Comment by mrleonz** [comment]
> Hello,
> So where do I put this script stuff? I bought elementor cuz it's easy to use, but don't forget about us europeans :P

Did someone already figured out?? :(

**Comment by JoeyBol** [comment]
@mrleonz there is an option in Elemnentor to select Native HTML5. This makes the field look like this

https://user-images.githubusercontent.com/85613438/174619551-748ff4a3-da50-43a8-95ad-a60c1ba96f86.mp4

This will make the time format look like 14:00 instead of 2:00 PM.

**Comment by MohFarawati** [comment]
> @mrleonz there is an option in Elemnentor to select Native HTML5. This will make the time format look like 14:00 instead of 2:00 PM.

Its working, Thanks a lot

**Comment by aspect-vs** [comment]
Both provided solutions (Native HTML5 & JavaScript implementation) doesn't work on my end unfortunately... Any updates?

**Comment by ITS360** [comment]
@aspect-vs you could achieve it in javascript implementation, by adding this code to the end of body
`<script>
	window.addEventListener("load", (event) => {
			if (typeof flatpickr !== 'undefined') {
				let fields = flatpickr(".flatpickr-input", {
					enableTime: true,
					noCalendar: true,
					dateFormat: "H:i",
					time_24hr: true
				});
			}
	});
</script>`
