### ISSUE TITLE
Form element date with translations and regions

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#6611]
When building a form with Elementor and choose the "Date" form-element, the calender in the front-end is not translated and the week starts with sunday, but this is not very common in Europe/DE/AT.

Alternative is to switch back to HTML5 but this is not as nice as the input given by Elementor.

There is a issue at https://github.com/pojome/elementor/issues/3605#issuecomment-370373072 but seems not to be solved.

**Comment by srcek** [comment]
I'd also like for this to be added. Elementor has a very nice visual form builder, why not make it more powerful and versatile.

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
@Luxamman 	

look again, at  #3605 it provides a solution.

**Comment by Luxamman** [comment]
Thanks, but I try not to push "one time one man" solutions, because this is important to a lot of countries and regions out there... would be nice to have a implementation in Elementor to not just solve a one time problem.

**Comment by RenatoPesaro** [comment]
Hello Bainternet,
regarding issue #3605 >> where should I place the translation code in the function.php?
I placed it on the buttom but it doesn't accept. What 

BDW  -  also in Italy we use the date format d/m/Y  so if it would be realizable for you to change the date format in one of your future version, would be great. Thank you very much.
