### ISSUE TITLE
Make the button scale to XX% width of parent/column

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#6617]
One thing that has long been important to me and can only be solved with padding (not perfect) or CSS, is that buttons can not be scaled to 100% width as an example. Or 50%, or 80%...

The padding is also depending on the text and icon inside the button, which makes it even harder to display two buttons one above the other in the same width.

I need that for example for show a mobile menu with 5+ buttons one after another - and every button seems to have a different width.

Thanks!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Specifically, 100% you can, via align -> Justify
as for 50%,80% you can use margin instead of padding.

or via custom CSS.


Thanks for the feedback.
