### ISSUE TITLE
Filter by attribute in the WooCommerce Products widget.

### ISSUE THREAD

**Issue by wordxpression** [pojome/elementor#6618]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to filter the products in with similar attributes/attribute values. There is no such possibility, the only way to do it now is to clutter the categories with this kind of stuff.

**Describe the solution you'd like**
In the Query section of the widget i would like the possibility to select an attribute / attribute value pair to filter products.

**Describe alternatives you've considered**
As mentioned, alternatively the categories could be 'abused' to get the same functionality, but it would clutter the categories and make navigation harder.

**Additional context**
N/A

**Comment by bainternet** [comment]
@wordxpression 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

However, you can add a custom taxonomy to your product and use them to filter, this way you won't clutter your categories.

Thanks for the feedback.
