### ISSUE TITLE
ACF - User Profile Field Does Not Load On Single Template 

### ISSUE THREAD

**Issue by websitehelperuk** [pojome/elementor#6619]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

User profile advanced custom fields data not being pulled. 

## Steps to reproduce

Create new AFC field for user roles -> ALL, add data in new user profile field, try to load field in Elementor single post template.
[https://i.gyazo.com/36eeae31168650ec8717bb6364823698.png](url)

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by erzawansyah** [comment]
The same issues also occurred in Pods Framework. When i was add a custom fields in users profile, elementor can't load that on user archive template. I tried to search for the issues in here, and i found this thread. Then, i tried to load the custom field user in single template, but its not work too.

Btw, i also tried shortcode method in this template. But, its still not work..

**Comment by bainternet** [comment]
@websitehelperuk @erzawansyah 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

As for User info such as, Name, Email, Bio, Meta and more, we have a new dynamic tag that will be in the next version.

Thanks for the feedback.

**Comment by riverharbor** [comment]
Having the same issue.  Both on PODs and ACF.

Both PODS and ACF allow an image field to replace WP's core "Gravatar" image field within user profiles.  Elementor, however will not render the image when supplied by Pods or ACF in the Author Box Widget or Image widget.

Oddly Enough, if creating an Elementor archive template, it actually _does_ render the PODS or ACF image when "Show Avatar" selection is active.  So it appears that it's entirely possible to implement if you could expand the functionality on image and author box widgets. 

Thanks

**Comment by websitehelperuk** [comment]
@erzawansyah had come to the same conclusion. Temp fix won't do any harm.

**Comment by mymlen** [comment]
I have the same problem. I was creating a custom user profile page and wanted to display some custom fields on it. Looks like Elementor can't pull custom fields that are located under users.

**Comment by x5hwuk7nc6jsudcc** [comment]
This is marked as resolved but it still doesn't seem possible to pull through ACF user fields into Elementor templates?

**Comment by plethoradesign** [comment]
This is still an issue. On a single post template I am able to select Author ACF fields, but they don't actually work. I think they should be fixed so they do in fact pull the field data, or they should not be shown as an option when editing a single post template. As it stands right now it's a bug.

**Comment by robtucker168** [comment]
Another request for this function. I am trying to create a user profile page, But I can't pull ACF images (main issue), or ACF numbers for the likes of range slider or counter. In fact, the only way to pull ACF user data is if it's text and use the dynamic 'User Meta' and the ACF 'Name' Field.

**Comment by ficjosi** [comment]
It's unfortunate that this is still not working. I'm another one in need of this feature.

**Comment by LinusB** [comment]
I'm very confused! This thread is more than 5 years old and there is still no fix for this issue.
Elementor works great with custom fields in posts, but can't handle custom fields with users. I thaught it was my fault.
I can't believe that it's so hard to fix this, that it takes 5 years?!

**Comment by moshiurshimul** [comment]
This issue is still present.

**Comment by ghost** [comment]
still same, need custom developement -------------------------------------?
