### ISSUE TITLE
Image Carousel Bug

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#662]
When using the Image Carousel widget, if you choose Image Size = Custom and set a custom height, the height does not get parsed into the CSS

Custom height or width should be getting added to this css class **.slick-slide img** when they are set in the editor panel

**Comment by arielk** [comment]
@Pagester There is a reason why it is necessary to add the height of the image to the CSS class?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
