### ISSUE TITLE
Embed YouTube channel

### ISSUE THREAD

**Issue by PLAYLUXE** [pojome/elementor#6620]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'd like to embed whole YouTube or Vimeo playlists on a site instead of embedding every single video.

**Describe the solution you'd like**
Being able to decide between different styles. Like displaying all videos as masonry, carousel, changing columns etc. (like a portfolio)

**Describe alternatives you've considered**
I may have purchased this plugin: https://elfsight.com/youtube-channel-plugin-yottie/wordpress/?reset_frame=true

But since I'm already a paying Elementor Pro customer and think that I'm not the only one who might miss this feature: Why not suggesting it?

Also it seems like those third party solutions aren't supported anymore by devs.

**Additional context**
I and maybe most of your customers would be really greatful for integrating this solutions into Elementor Pro!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
