### ISSUE TITLE
Elementor Custom Attributes

### ISSUE THREAD

**Issue by mbgraphicdesign** [pojome/elementor#6622]
I am trying to change an attribute within the wrapper element. Specifically, on the login widget I would like to change the User field text placeholder to "Username" instead of "Username or Email address" because I am using this page as a private page with no email address login, just a username. I see exactly where to do this within the html code but cannot figure out how to change it within Elementor. 

Any help is greatly appreciated.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* Isolating the problem.

As for your question if I've understood correctly - you are trying to change the label and the placeholder of the login form widget.

Please make sure you use the "Additional Options" > "Custom Label".

Best regards.
