### ISSUE TITLE
Hidden Stretch section missing left attribute

### ISSUE THREAD

**Issue by dhirnitish** [pojome/elementor#6623]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

If a fullwidth stretch section is hidden or display:none during pageload then Elementor does not set the left attribute and there is white space to the left pushing that section to the right. 

For the time being I did the following right after I add display block to element using jQuery.
$(window).trigger('resize');

## Steps to reproduce
Set a Stretch section to display none or not visible on desktop.
After pageload add display block to that section using jQuery

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@dhirnitish 

We can't replicate,

please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists, contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
