### ISSUE TITLE
CSS Blur on BG overlay causes image to bleed beyond shape dividers

### ISSUE THREAD

**Issue by Jackpedleham** [pojome/elementor#6626]
When using a shape divider with an image in the Background overlay slot if you use CSS blue the image bleeds beyond the shape divider edge.

![image](https://user-images.githubusercontent.com/37905475/50725465-ca629100-10f5-11e9-8453-ca8c5aa4b798.png)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
