### ISSUE TITLE
elementor add to cart wigget

### ISSUE THREAD

**Issue by lodesign-st** [pojome/elementor#6627]
hi 

elementor add to cart wigget

i need to change the text and the link to View Product how can i do this ?
![image](https://user-images.githubusercontent.com/21275648/50679032-4bdcf500-100a-11e9-98b5-e71d90aec8f5.png)

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
