### ISSUE TITLE
 Elementor 2.4.0 Beta Release 4

### ISSUE THREAD

**Issue by bainternet** [pojome/elementor#6630]
===========
## [Beta 4 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/6630#issuecomment-453130568)
===========

Hi Elementor testers!

Elementor v2.4 Beta is out, and we would appreciate it if you could install it and test it out. Following is a description of what's new.

In the upcoming version, we focused on strengthening and foolproofing Elementor’s infrastructure. We added a new “Safe Mode” feature, a log of PHP errors, and a new Async Updating Module.

-----------

### Safe Mode Feature

Safe Mode helps identify any issue that interferes with Elementor loading. In most cases, loading issues are caused by conflicts between plugins or themes.

![safe mode](https://user-images.githubusercontent.com/45009641/50733273-6b535980-1193-11e9-8279-606794e5aa54.png)

Using 'Safe Mode' opens the Elementor editor on a clean version of WordPress, without loading a theme or any plugins. All plugins are deactivated and an empty theme file is loaded.

Please note! Safe Mode only affects logged in users while they are using the editor, and has NO effect on site visitors or other logged in users. For them, the site will operate as usual, with the regular theme and plugins activated.

**Test flow:**

* Go to > Tools > Enable Safe mode.
* Open new page > Edit with Elementor.
* Make sure the Safe Mode notice appears.

### Async Database Upgrade System

In the past, certain upgrades required database changes to occur behind the scenes. For larger sites, this posed a problem which sometimes caused timeouts.

With the new Async Database upgrade system, we split the DB updates into chunks that run in the background in order to avoid these timeouts.

### PHP Logger for System Info

Many support issues can be identified by following the PHP log file. By adding this log to the System info, we can empower our users and support staff to better understand the issue at hand, its root cause and relevant solution.

**Test flow:**

* Go to Elementor Dashboard > System Info.
* Notice the new Log area.

### Respect the WP `<!--more-->` Tag (#462)

Until now, Elementor did not support the WordPress `<!--more-->` tag, which helps determine the preview text that is shown for blog posts in archive pages (not built using Elementor's archive template). While this is not commonly used on modern themes, it provides backward compatibility for this functionality.

Added Read More Widget for Themes that Support This Feature
Following the previous mentioned feature, you can now add the ‘Read More’ widget to your posts, to set the text cut-off point in archive pages.

**Please note:** This widget only affects themes that use `the_content` in archive pages.

## Background & Border Customization

![custom responsive](https://user-images.githubusercontent.com/45009641/50733275-760dee80-1193-11e9-8022-8cd82ef56c9f.png)

### More Responsive Controls of Background & Borders (#2355, #3243, #5284)

We’ve added the maximum flexibility for responsive design. The new version of Elementor lets users have complete control over the background and border design on desktop, tablet and mobile devices.

This control includes device-specific settings over background controls (image, position, attachment, repeat and size) and border controls (border-radius and width).

**Test flow:**
* In Elementor, go to Section > Style > Background.
* Add a background image.
* Play around with the new responsive controls of background settings and border settings.

### Add custom options for Background Size & Background Position (#2571)

You now have much more control over the background design. We are now adding two new custom controls for the background size and position options.

With custom position, you can manually set your desired background position on an X & Y axis. Instead of setting a general position like 'Top Left', you now have the option to set the exact point that the background will align to.

Besides position, you can also set custom background image size. Choose ‘Custom’ and set an exact width for your background image.

**Test flow:**
* Under the previous background image, go to ‘Size’ / 'Position' and choose ‘Custom’.
* Play around with the different custom sizes and positions.

## Revamped Admin Menu

![library](https://user-images.githubusercontent.com/45009641/50733278-7f975680-1193-11e9-83e9-5454787b3394.png)

#### Re-Organize the Templates Library Screens

To make it easier to handle the different Elementor dashboard screens, we’ve separated the previously named ‘My Templates’ menu and renamed it as ‘Templates’.

We’ve also positioned the Elementor & Library side menus higher up on the dashboard, to make it more accessible.

One of the reasons for the separation of the library is its expansion - a super-exciting new direction that is coming soon.

### Add Categories Taxonomy for Templates Library (#886)

Now you can add different categories to your templates, making the workflow more efficient and better organized. Simply group templates by relating them to the desired category.

### Restored Quick Edit for Templates

In the new version of Elementor, you can Quick Edit saved templates in order to instantly edit the template name, slug, status and categories without hassle.

## More Improvements

**Tweaks:**

* Tweak: Added External URL source for Video widget
* Tweak: Added Link & Globe for Social icons (#6405)
* Tweak: Added a warning when clicking on Back to WordPress editor button (#5597)
* Tweak: Added attributes for column wrappers (thanks @thenovacreator)
* Tweak: Exclude library CPT from Yoast SEO sitemap
* Tweak: Added `autocomplete` parameter for URL control
* Tweak: Added sanitize data on Menu Anchor ID
* Tweak: Added dynamic options for Testimonial widget
* Tweak: Rename "Content" tab in Templates Library to "Page"
* Tweak: Added `elementor/controls/animations/additional_animations` hook for adding custom Entrance Animations (#6545)(thanks @wayheming)
* Tweak: Added `elementor/controls/hover_animations/additional_animations` hook for adding custom Hover Animations (#6545)(thanks @wayheming)

**Fixes**

* Fix: Inline editing issue for repeater controls (#6445)
* Fix: Footer menus not closing after background clicks (#6547)
* Fix: Typography control doesn't generate default CSS (#6500)

## How to Install the Beta Version

If you still haven't enabled beta testing in Elementor, please follow these steps:
Go to Elementor > Tools > Versions
Enable the beta tester feature
Go to the Dashboard > Updates and update to the latest beta version
 

You can also download the new version here: [https://downloads.wordpress.org/plugin/elementor.2.4.0-beta4.zip](https://downloads.wordpress.org/plugin/elementor.2.4.0-beta4.zip)

## Notes

For bugs and remarks, please reply with a comment on this issue here on GitHub.

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

**Designated time for release:** _January 14, 2019 (Estimated)_

Many thanks for your support and help!

Cheers,

**Elementor Team**

**Comment by parfilov** [comment]
Templates section disappeared

**Comment by parfilov** [comment]
Templates cannot be edit. WSOD and nothing. Even if Safe Mode is off.

**Comment by donwattz1459** [comment]
Choosing "Custom" for the background size while in tablet mode does not show the settings. It does when in desktop mode though. Complete clean install of E and E Pro with WP 5.0.2 using Twenty Nineteen theme. No other plugins.

![screen shot 2019-01-06 at 9 39 42 am](https://user-images.githubusercontent.com/16137152/50737422-0bf74880-1197-11e9-8ef4-e1542968d92e.png)

**Comment by donwattz1459** [comment]
Same as @parfilov. Cannot edit templates once they are saved.

**Comment by parfilov** [comment]
@donwattz1459 New can't be edit too.

**Comment by parfilov** [comment]
Safe Mode window international compatibility trouble

ScreenShot https://www.dropbox.com/s/ugx8qh44pv1nfrc/safemode.png)

**Comment by parfilov** [comment]
I think that to choose the images sizes for background will be more effective. WP slices thumbnails and why not to choose from them instead of uploading smaller/bigger duplicates and consume the filesystem.

**Comment by shilo-ey** [comment]
@parfilov @donwattz1459 

Thank you for bringing this issue to our knowledge, we've released beta2 (updated link above), please update and let us know if the editing issue persists.

@parfilov 
> I think that to choose the images sizes for background will be more effective. WP slices thumbnails and why not to choose from them instead of uploading smaller/bigger duplicates and consume the filesystem.

In the new background setup you have complete and precise control over the dimensions of your background, using the uploaded image and not it's duplicates.


@donwattz1459 
> Choosing "Custom" for the background size while in tablet mode does not show the settings. It does when in desktop mode though. Complete clean install of E and E Pro with WP 5.0.2 using Twenty Nineteen theme. No other plugins.
> 
> ![screen shot 2019-01-06 at 9 39 42 am](https://user-images.githubusercontent.com/16137152/50737422-0bf74880-1197-11e9-8ef4-e1542968d92e.png)

Thank you, we are looking into this and will update soon.

**Comment by taminoferrari** [comment]
Great work elementor team! Please add responsive images also for the image widget and the media carousel widget. Retina support would also be great as the WP Retina 2x plugin does not work with elementor. For this reason currently I need to upload the images with a much bigger resolution if I want them to look good on retina displays which goes on the costs of page speed. The suggestion of parfilov to use automatically sized images is also great as it takes much time and space to resize all the images and upload them for each device.

**Comment by pingram3541** [comment]
Updated to 2.4.0-beta2 trying to edit any pre-existing page I get this error:

`JS: 2019-01-06 23:38:00 [error X 3][https://mysite.com/wp-content/plugins/elementor/assets/js/editor.min.js:2:35839] Cannot read property \'get\' of undefined`

Access a page's back end (even with safe mode enabled) and NOT trying to use the Elementor editor I get this in the console:

```
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2 Uncaught Error: Syntax error, unrecognized expression: #/
    at Function.fa.error (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at fa.tokenize (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at fa.compile (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at fa.select (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at fa (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at Function.fa.matches (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at Function.n.filter (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at z (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at a.fn.init.filter (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.2:2)
    at o.goToSettingsTab (admin.min.js:2)
```
Then trying to access the Elementor editor it fails with the following regardless of safe mode enabled or not:

```
redux-routine.min.js:1 Uncaught (in promise) Error: [object Object] at redux-routine.min.js:1
redux-routine.min.js:1 Uncaught (in promise) Error: [object Response] at redux-routine.min.js:1
data.min.js:1 Uncaught (in promise) TypeError: Failed to fetch Promise.then (async)
```

**Comment by pingram3541** [comment]
Rolling back to 2.3.8 and still broken.  Wonder if a database restore is the fix...we'll see.

`frontend.min.js:2 Uncaught ReferenceError: elementorModules is not defined`

**Comment by DoctorMicro** [comment]
_Here is a small one_. It would be nice if under the new Admin Menu the "**Knowledge Base**" Menu Link would open in a **New Window** for a better workflow.

**Comment by avermat** [comment]
I'm not sure if this is related to the new template library changes or not, but I thought I would mention it just in case. When I first tried to add a saved template to a page, I see this screen:

![saved-templates](https://user-images.githubusercontent.com/29379115/50750696-1261ef00-1281-11e9-8962-5c559ee6d82e.png)

I have lots of saved templates in my library so it seems "Haven't Saved Templates Yet?" is incorrectly being displayed. Also, the "Blocks" tab is highlighted, but the blocks are all hidden.

**Comment by parfilov** [comment]
@avermat How about My Templates tab?

**Comment by parfilov** [comment]
Agree with @taminoferrari Retina option is also needed.

**Comment by jazir5** [comment]
Would it be possible to apply the system you have created to resizing the background to column structure? That method would make it so much simpler to position elements on the page compared to the current margin system. It would allow visual placement of elements, rather than guess working it by changing the margin numbers. 

Thank you guys for all your hard work.

**Comment by nickdgreen** [comment]
Bug with Background Image custom Positioning.
Process:

- Added a new section with 3 columns
- Added a spacer the centre column set to 260 px to "expose" background
- Added background image
       + Position Custom: X Position 50%, Y Position 10
       + Attachement: Default
       + Repeat: No-repeat
       + Size: Custom - 50%
- Selected Column "tablet view" without changing the image
- Position: Custom
- X Position Slider works
- Y Position Slider works 

Having moved the Y Position Slider, however, the X Position Slider no longer works.
Additionally, the 'usual' Elementor user interface with something with a value is "highlight and delete" to restore the parameter to its default value. This does not work in the sliders and they have to be set to zero.

**Comment by ShadowXVII** [comment]
@parfilov #3722

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to v2.4.0 Beta 3.

This beta release includes:
	* Tweak: Updated Finder according to admin menu changes.
	* Fix: Responsive background positioning issue.
	* Fix: Connect Admin Submenu hook for Non-English sites.
	* Fix: `device_args` selectors and conditions in group control
	* And a few more...

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Thanks again to everyone.

**Comment by deckerweb** [comment]
Hi there - impressive work again with 2.4.0, congrats to the whole team!

I have the following issue:
My plugin "Builder Template Categories" is adding an additional taxonomy to your post type and for various reasons also using `add_submenu()` function for that (I am currently tweaking for your changes in 2.4.0).

This leads to an PHP Error Notice in Elementor 2.4.0 Betas - it happens consistently since Beta 1 until now (Beta 3).

`PHP Error Notice: Undefined offset: 15 in wp-content/plugins/elementor/includes/template-library/sources/local.php:336`

In the last days I tried everything on my end to solve this on my end in my plugin - with no success.
I tracked it down to a missing check, because the `array key 15` is **not existing in this submenu array** - no matter under which circumstances.

**Following solution:**
in wp-content/plugins/elementor/includes/template-library/sources/local.php:336
**replace**
`$library_submenu[800] = $library_submenu[15];`

**with this:**
```if ( isset( $library_submenu[15] ) ) {
	$library_submenu[800] = $library_submenu[15];
}```

This works for me under all circumstances - no matter if my plugin is active or not. The order of your submenu items always keeps the same then, and no more notice :)

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to v2.4.0 Beta 4.

This beta release includes:
 - Fix: On create save the template-type immediately (#6648)
 - Fix: Style glitch issues in Safe Mode window (thanks @parfilov)

Please keep this related to the Current beta Only! any other issue, feel free to open a new issue.

Thanks again to everyone.

**Comment by thkishor** [comment]
1. It require some css to add padding to the close button when user added background color-

![screenshot_10](https://user-images.githubusercontent.com/39625343/50983829-5b869d00-1526-11e9-9aae-f0ccc6fb4632.jpg)

2. This is not the part of Elementor pro update that are listed above but there is bug on review widget. When i add rating to it shows 5 star 5 star and it is really annoying

![screenshot_9](https://user-images.githubusercontent.com/39625343/50984192-465e3e00-1527-11e9-8ff8-8a2110f06b61.jpg)

**Comment by deckerweb** [comment]
@bainternet 
The latest Beta 4 fixed my submenu issue from above, thanks a lot! 👍

**Comment by nickdgreen** [comment]
@taminoferrari works OK without being set to scroll on my Samsung using chrome.

**Comment by taminoferrari** [comment]
So maybe it is an IOS/Safari issue. I need to set it to scroll to make it work on my Iphone X.

**Comment by black-eye** [comment]
Nice addition with the backround. Right now I'm playing with this feature for a while and I have 2 questions, maybe feature requests:

1. Is it possible to set position with the offset (e.g.: background-position-x: right -250px)?
2. Is it possible to have some backround image on the desktop and NONE image (just color) on the mobile?

**Comment by shilo-ey** [comment]
[**@taminoferrari**](https://github.com/taminoferrari) commented on [Jan 13, 2019, 10:26 PM GMT+2](https://github.com/pojome/elementor/issues/6630#issuecomment-453862620 "2019-01-13T20:26:50Z - Replied by Github Reply Comments"):
> @shilo-ey Could you replicate my issue or am I the only one who has it? Thanks in advance!
> 
> > Mobile Background image does not work on mobile devices when the background image is set to cover and fixed on desktop device. If I set it to scroll on mobile then it works, but I guess it inherits the scroll attribute and therefor does not work if you do not set it on scoll on mobile devices. Can somebody replicate this issue? I tried it with an Iphone X.

Hi @taminoferrari , 

This is not Elementor related issue. Apple blocks the ability to use fixed background position in their iOS mobile devices.

Simply use scroll position for this BG in mobile.

thanks.

**Comment by bainternet** [comment]
Elementor 2.4.0 Is now **live**.

thanks, everyone for your help.

**Comment by taminoferrari** [comment]
@shilo-ey I think many elementor users does not know that the background image does not look good on ios devices if they just set it to fixed for desktop devices. Additionally it is much work to change it for every background picture on mobile from default to scroll just to make look on ios devices. This issue has not been there before the update. Before the update if I had set the background image to fixed it also looked automatically good on ios devices. So why did that change? Please have a look at the images which I attach to the comment. img_1638 shows the background image as it should look like. I achieve this only if I set it to scroll for mobile. img_1639 shows the background image if I only set the background image to fixed for desktop devices. Could you please have a look at it again? I think it is an important issue. 
![img_1638](https://user-images.githubusercontent.com/46429041/51138645-f2629a80-1841-11e9-9a07-4efdaff313f3.PNG)
![img_1639](https://user-images.githubusercontent.com/46429041/51138646-f2629a80-1841-11e9-9e1c-6d05deb96e32.PNG)

**Comment by HorvathDavid** [comment]
Hi @pingram3541,
Make sure you clear your server side cache. We just resolved this issue by clearing WP Fastest Cache and it got back to working again.

**Comment by stefanpejcic** [comment]
Having the same problem as @pingram3541 has, but his solution do the work for me..

**Uncaught ReferenceError: elementorModules is not defined** - when trying to edit a page in Elementor.

Disabled wp-rocket and cleared Cloudflare cache, DB and even re-installed the plugin.

Is there anything else I could give a try?
Its been a few days and I'm really worried now, any suggestion is welcome.

**Comment by mstudioIL** [comment]
Can I use the `<!--more-->` to split pages?
