### ISSUE TITLE
A new Flip Box Background Type: Box to create a box behind the text to make it more visible

### ISSUE THREAD

**Issue by myBCN** [pojome/elementor#6634]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When placing texts over a picture in the Flip Box it is sometimes very hard to read the text

**Describe the solution you'd like**
If you could place a customisable Box behind the text you can make sure that the text is always visible.

**Describe alternatives you've considered**
Today I am using the **Background Type**: _Gradient_ **Type**: _Radial_ **Position**: _Center Center_ to achieve something similar. This works for now but does not always solve the problem and the Radial function covers a lot of the picture itself.

**Additional context**
You can see how I use it on [the site](https://barcelonafreewalkingtour.com/) especially in the "Gallery of Medieval Times"

//Matthias

**Comment by shilo-ey** [comment]
@myBCN 

Hi, thanks for your feedback,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.


for now, you can use Custom CSS in order to achieve your request.

```CSS
.elementor-flip-box__layer__inner {
    background: rgba(86, 86, 86, 0.47058823529411764);
    padding: 10px;
}
```

Thanks.
