### ISSUE TITLE
A new Countdown function that Restarts every time it reaches Zero

### ISSUE THREAD

**Issue by myBCN** [pojome/elementor#6636]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We run tours every day and would like to show how long it is until the next tour starts.

**Describe the solution you'd like**
I would like to see the Counter restart when it reaches Zero, that is all.

**Describe alternatives you've considered**
#5074 Requests something similar. I have not found this in any Elementor or WP plugin, I have spent way too much time looking for it.

Thank you for considering.

//Matthias

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by blackgoku** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> Thanks for the feedback.

Looking for this same function from a year and the demamd for this function is high.

**Comment by blackgoku** [comment]
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> Thanks for the feedback.

actually if you type in the github search 'countdown' you will notice this same feature request in 30+ threads.

**Comment by rafaelfigueiredo-l** [comment]
+1 needing this function.

**Comment by blackgoku** [comment]
@rafael i have found the solution to this problem, need to add some custom codes.
If you need help with it contact me on skype or gmail - swapnilsbl17@gmail.com (same id for both)

**Comment by rafaelfigueiredo-l** [comment]
Hi @blackgoku send me here in github please.
