### ISSUE TITLE
[Feature Request] Support for ACF Gallery field

### ISSUE THREAD

**Issue by bart-prosite** [pojome/elementor#6639]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description
It would be great if Elementor (Pro) would support ACF Gallery Fields out of the box. There is another plugin that does provide this functionality (I can't remember which one), but since Elementor supports ACF I think it's weird that I cannot use the ACF Gallery field.

**Comment by shilo-ey** [comment]
Hi @bart-prosite 

Elementor **does** support ACF Gallery field out of the box.

(Click here to learn more)[https://docs.elementor.com/article/381-elementor-integration-with-acf], or add image gallery widget, select Dynamic > ACF Gallery field > set the key.

Thanks.

**Comment by bart-prosite** [comment]
Hi,

Thanks for the very quick response! I must have overlooked this. But this isn't working for me.
ACF Photo Gallery Field 1.6.3
ACF 5.7.9
Elementor 2.3.8
Elementor Pro 2.3.1
GeneratePress Premium 1.7.7

Steps:
* Create new Custom Post Type (I called it Gallery Test)
* Create new custom field group, add field type Photo Gallery
* Create new content and add images to the Gallery field
* Create single post template in Elementor for the new Post Type
* In Preview settings select one of the new Gallery posts
* Add Image Gallery, choose Dynamic, select ACF Gallery Field
* Click on spanner, the Key dropdown is empty. I cannot select anything.

I added two separate image gallery fields to one CPT and none of them are showing. I must be missing something.

**Comment by shilo-ey** [comment]
@bart-prosite 

You need to use ACF Pro in order to use its' native gallery feature.
We are currently not supporting `ACF Photo Gallery Field` plugin.

Cheers,

**Comment by bart-prosite** [comment]
Ah, okay. So that's the problem. Any chance of adding support for this in the future?

**Comment by shilo-ey** [comment]
Currently no, but we will look into it in the future if we see a large demand for it.

We recommend using the well-known and not 3rd-party plugins for better compatibility.

Thanks,
