### ISSUE TITLE
Feature Request - Ability to edit permalink of template

### ISSUE THREAD

**Issue by Webtica** [pojome/elementor#6643]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello, 
After import of a template i can see it takes the permalink of the old template. 
Sometimes I wish to use a old template to make a new one under a diffrent name. 
So changing the permalink would keep thing organised. 

## Steps to reproduce
Go to templates and make a template. 
Export that template and re-import it and you will see the permalink wil take the old one. 
or if double add a -2 to it. 

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @Webtica 

In order to change the permalink go to Screen options > check the "Slug" checkbox

Now you can see that a Slug meta box has been added. change it to whatever you want and click update.

Thanks.
