### ISSUE TITLE
After submit a form, the url redirection doesn't get the correct language.

### ISSUE THREAD

**Issue by gorgulius** [pojome/elementor#6644]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
After submit a form, the url redirection doesn't get the correct language.

**Describe the solution you'd like**
Put the redirection url dynamic, so we can choose one Wordpress link

**Describe alternatives you've considered**
Hard coded every page (different idioms) with the correct Url.

**Additional context**

**Comment by bainternet** [comment]
@gorgulius 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

This is not something we control and should be up to the translation/multilanguage plugin.

thanks.

**Comment by gorgulius** [comment]
Hi Raz,

Sorry, but I must disagree. Because the dynamic content already exists on elementor.
I only need to be available on the url form after submission, to another page of the Wordpress.
Right now we only can write it, like static text.
Normally should be the same code to implement it.
See what You can do.

Gorgulius
