### ISSUE TITLE
Timeline icon

### ISSUE THREAD

**Issue by jilljoyce** [pojome/elementor#6646]
The possibility to change the connector icon in the timeline is not there anymore.

**Comment by shilo-ey** [comment]
@jilljoyce 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
