### ISSUE TITLE
Elementor block for using Woocommerce coupons

### ISSUE THREAD

**Issue by Vostok8** [pojome/elementor#6647]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
At the moment, you can use Woocommerce coupons only on the cart page and on the checkout page.
It would be cool to have a coupons input widget. This will make even more creative pages to increase conversion.

**Describe the solution you'd like**
Elementor block for using Woocommerce coupons.
And / or add the coupon form in the sidebar cart before buttons.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
