### ISSUE TITLE
Changing to HTTPS results in Mixed Content issue with JQuery Woocommerce Cart Button

### ISSUE THREAD

**Issue by shaneonabike** [pojome/elementor#6651]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

We added a woocommerce cart button (that uses Jquery) into a top menu item. Previously, the site was set to http, but we are now forcing the site to https. We changed the default domain and site name properly to use https. Furthermore, we used Search and Replace to modify the domain on certain places which are not elementor.

For the most part this is working perfectly! One issue is that I keep getting Mixed content issues specifically with the  jquery plugin :/

`jquery-migrate.min-1.4.1.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
jquery-1.12.4.js:3 Mixed Content: The page at 'https://www.dada.com/en/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://www.dada.com/cart/'. This endpoint should be made available over a secure connection.
ja @ jquery-1.12.4.js:3
Ha @ jquery-1.12.4.js:3
replaceWith @ jquery-1.12.4.js:3
(anonymous) @ cart-fragments.min-3.5.2.js:1
each @ jquery-1.12.4.js:2
(anonymous) @ cart-fragments.min-3.5.2.js:1
i @ jquery-1.12.4.js:2
fireWith @ jquery-1.12.4.js:2
ready @ jquery-1.12.4.js:2
K @ jquery-1.12.4.js:2
jquery-1.12.4.js:3 Mixed Content: The page at 'https://www.dada.com/en/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://www.dada.com/cart/'. This endpoint should be made available over a secure connection.
ja @ jquery-1.12.4.js:3
Ha @ jquery-1.12.4.js:3
replaceWith @ jquery-1.12.4.js:3
(anonymous) @ cart-fragments.min-3.5.2.js:1
each @ jquery-1.12.4.js:2
success @ cart-fragments.min-3.5.2.js:1
i @ jquery-1.12.4.js:2
fireWith @ jquery-1.12.4.js:2
y @ jquery-1.12.4.js:4
c @ jquery-1.12.4.js:4
XMLHttpRequest.send (async)
send @ jquery-1.12.4.js:4
ajax @ jquery-1.12.4.js:4
r @ cart-fragments.min-3.5.2.js:1
(anonymous) @ cart-fragments.min-3.5.2.js:1
dispatch @ jquery-1.12.4.js:3
r.handle @ jquery-1.12.4.js:3
trigger @ jquery-1.12.4.js:3
a.event.trigger @ jquery-migrate.min-1.4.1.js:2
(anonymous) @ jquery-1.12.4.js:3
each @ jquery-1.12.4.js:2
each @ jquery-1.12.4.js:2
trigger @ jquery-1.12.4.js:3
(anonymous) @ cart_widget.min-4.3.7.js:1
i @ jquery-1.12.4.js:2
fireWith @ jquery-1.12.4.js:2
ready @ jquery-1.12.4.js:2
K @ jquery-1.12.4.js:2
`

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.37 (Ubuntu)
	MySQL version: (Ubuntu) v5.7.24
	PHP Version: 7.1.25-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.9
	Site URL: https://www.dada.com
	Home URL: https://www.dada.com
	WP Multisite: No
	Max Upload Size: 4 MB
	Memory limit: 128M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: en-US
	Timezone: America/Halifax
	Debug Mode: Inactive

== Theme ==
	Name: Dada
	Version: 1.0
	Author: Bees on a Bike
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	ACF Content Analysis for Yoast SEO
		Version: 2.1.0
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Advanced Custom Fields
		Version: 5.7.9
		Author: Elliot Condon

	Advanced Custom Fields Multilingual
		Version: 1.0.2
		Author: OnTheGoSystems

	Advanced Custom Fields PRO
		Version: 5.7.8
		Author: Elliot Condon

	Better Search Replace
		Version: 1.3.2
		Author: Delicious Brains

	Caldera Forms
		Version: 1.7.5.1
		Author: Caldera Labs

	Caldera Forms Anti Spam
		Version: 0.1.1
		Author: YooHoo Plugins

	Crop Thumbnails
		Version: 1.2.2
		Author: Volkmar Kantor

	Custom Icons for Elementor
		Version: 0.1.4
		Author: Michael Bourne

	Ele Conditions
		Version: 1.0.5
		Author: Liviu Duda

	Ele Custom Skin
		Version: 1.0.9
		Author: Liviu Duda

	Elementor
		Version: 2.3.4
		Author: Elementor.com

	Elementor Inline SVG
		Version: 1.2.0
		Author: Namogo

	Elementor Pro
		Version: 2.2.3
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.7
		Author: ExactMetrics

	Google Captcha (reCAPTCHA) by BestWebSoft
		Version: 1.39
		Author: BestWebSoft

	Max Mega Menu
		Version: 2.5.3.2
		Author: megamenu.com

	Redirection
		Version: 3.6.3
		Author: John Godley

	reSmush.it Image Optimizer
		Version: 0.1.21
		Author: reSmush.it

	Simple Image Sizes
		Version: 3.2.0
		Author: Rahe

	Toolbar Extras
		Version: 1.3.10
		Author: David Decker - DECKERWEB

	UpdraftPlus - Backup/Restore
		Version: 1.16.0
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 3.5.2
		Author: Automattic

	WooCommerce Accommodation Bookings
		Version: 1.1.5
		Author: WooCommerce

	WooCommerce Bookings
		Version: 1.12.2
		Author: Automattic

	WooCommerce Google Analytics Integration
		Version: 1.4.7
		Author: WooCommerce

	WooCommerce Multi-Step Checkout
		Version: 1.14
		Author: SilkyPress

	WooCommerce Multilingual
		Version: 4.3.7
		Author: OnTheGoSystems

	WooCommerce PDF Invoices & Packing Slips
		Version: 2.2.5
		Author: Ewout Fernhout

	WooCommerce Square
		Version: 1.0.34
		Author: WooCommerce

	Wordfence Security
		Version: 7.1.18
		Author: Wordfence

	WP Mail SMTP
		Version: 1.4.1
		Author: WPForms

	WPML CMS Nav
		Version: 1.4.24
		Author: OnTheGoSystems

	WPML Media
		Version: 2.4.0
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.1.1
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.4.5
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.9.0
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.7.0
		Author: OnTheGoSystems

	WP Rocket
		Version: 3.2.3.1
		Author: WP Media

	Yoast SEO
		Version: 9.4
		Author: Team Yoast


== Debug ==
	Errors: 
		TypeError: Cannot read property 'prev' of undefined
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.4 - 2:219473
			2018-12-13 15:21 +00:00

		TypeError: Cannot read property 'select2' of undefined
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.4 - 2:20729
			2018-12-12 20:27 +00:00
			x 4 times

		ViewDestroyedError: View (cid: "view651") has already been destroyed and cannot be used.
			at http://www.dada.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5 - 22:19954
			2018-12-06 15:55 +00:00

		TypeError: Cannot read property 'select2' of undefined
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.4 - 2:20729
			2018-12-06 15:47 +00:00
			x 5 times

		TypeError: Cannot read property 'select2' of undefined
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.3 - 2:20729
			2018-11-28 20:01 +00:00
			x 2 times

		TypeError: Cannot read property 'select2' of undefined
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.2 - 2:20690
			2018-11-27 19:26 +00:00

		TypeError: this.ui.apply.add is not a function
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.2 - 2:160150
			2018-11-20 13:44 +00:00

		TypeError: this.jqueryXhr.abort is not a function
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.2 - 2:162097
			2018-11-20 13:44 +00:00

		TypeError: Cannot read property 'html' of undefined
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.2 - 2:220509
			2018-11-19 16:08 +00:00
			x 4 times

		TypeError: Cannot read property 'select2' of undefined
			at http://www.dada.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.1 - 2:20690
			2018-11-17 19:12 +00:00
			x 7 times

				
```
</details>

**Comment by shilo-ey** [comment]
Hi @shaneonabike ,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


As for your issue, the elementor log issues are from a month ago, therefore not necessarily related to the domain change.

The jQuery issue might be caused by improper URL change or missing Force SSL rule on admin.

thanks.
