### ISSUE TITLE
get_render_attribute_string ret empty params

### ISSUE THREAD

**Issue by AntonRzevskiy** [pojome/elementor#6652]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

### Does not comply with the documentation!
https://github.com/pojome/elementor/blob/0da1fc6b8ee8f2cc968f9bac0fdbb40d0f7ce104/includes/base/element-base.php#L600-L601

It returns like `<div data-test>`
If `add_render_attribute( 'data-test', '' );`

Coz:
https://github.com/pojome/elementor/blob/0da1fc6b8ee8f2cc968f9bac0fdbb40d0f7ce104/includes/utils.php#L619
Don't care about)

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@AntonRzevskiy 

`get_render_attribute_string` looks at the entire string, not if a specific attribute is empty. So simply by calling `add_render_attribute()` the string will never be empty. Which seems to comply with the documentation.

thanks for the feedback.
