### ISSUE TITLE
Design single course page and course archive with elementor pro on learndash plugin

### ISSUE THREAD

**Issue by mossiplayer** [pojome/elementor#6654]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
with this feature users can design single course page on learndash plugin
like single product page and etc...

**Describe the solution you'd like**
add this feature like single product page designer

**Comment by bainternet** [comment]
@mossiplayer 

In Elementor Pro V2.3.0 we've added a `elementor_pro/utils/get_public_post_types` filter hook to allow adding "Non-supported" custom post types,
ex:
```PHP
/**
 * Add Learndash lesson post type support
 */
add_filter( 'elementor_pro/utils/get_public_post_types', function() {
	$post_types['sfwd-courses'] = 'Courses';
	$post_types['sfwd-lessons'] = 'Lessons';
	$post_types['sfwd-quiz'] = 'Quizzes';
	$post_types['sfwd-topic'] = 'Topics';
	return $post_types;
} );
```

thanks.

**Comment by mossiplayer** [comment]
no, I mean how to add Learndash support to elementor library not only post types
