### ISSUE TITLE
add_template_type() doesn't work like expected

### ISSUE THREAD

**Issue by value32** [pojome/elementor#6662]
Hi Folks,

Custom Templates Types created via \Elementor\TemplateLibrary\Source_Local::add_template_type( 'custom' ); show up correctly in the tabs section under "My Templates" but they won't be displayed in the Add new -> "Select Template Dialog". So there is no way to select this type of template when creating a template. A workaround is to create a term equally named in the elementor_library_type taxonomy. Would be great if this would be fixed. if bet it is because the lack of template properties "show_in_library" and "is_editable"..

**Comment by bainternet** [comment]
@value32 	

This is not the way to add a document type, you need to create and register a document type in order for that to work, take a look at how we do it:

https://github.com/pojome/elementor/blob/0da1fc6b8ee8f2cc968f9bac0fdbb40d0f7ce104/modules/library/module.php#L46-L53
