### ISSUE TITLE
Elementor Pro 2.4.0 Beta Release 4

### ISSUE THREAD

**Issue by bainternet** [pojome/elementor#6663]
===========
## [Beta 4 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/6663#issuecomment-455876344)
===========

Hi Elementor testers!

The biggest release since Theme Builder is almost here - meet **POPUPS**!

We would appreciate if you could help test the Popups feature before release.

## Introducing Elementor Popup Builder 
![gif](https://user-images.githubusercontent.com/660572/50906582-17b06c80-142e-11e9-8537-d1fcb31a5d71.gif)

Advanced popups, seamlessly built into Elementor Pro, is a true game-changing feature.

Popups are one of the most useful tools to engage users, increase sales and conversions and deliver important messages to visitors based on their actions and interactions on your site.

As you will see, Elementor Popups are extremely powerful in terms of design, triggering and targeting options. Follow the next steps to learn how we made popups flexible yet super-easy to use.

### 1. Getting Started With Elementor Popups
What’s great about Elementor Popups is that everything is built in the same way any other content is built.

Follow these steps to get your first popup set up:

1. **Make sure you have both Core v.2.4 Beta & Pro v2.4 Beta installed!** Without installing the beta of Core v2.4, which was released a few days ago, **the beta Pro version won’t work**.

1. Go to Dashboard > Templates > Popups > Add New
1. Name your template and click ‘Create Template’
1. Choose a template from the Library, or built your popup from scratch

### 2. Customize Popup Style & Layout

The next step is to customize the layout and design options for the popups.

Please go through the different Popup Settings screen. This screen is available through the bottom left gear icon, like any other document settings.

**Layout Settings**

With Elementor Popups, you have complete control over the layout of the popup. You can position the popup to the left, right, top, bottom, and other positions of the screen.

Easily customize the width and height of the popup window. For height, you can set it to either fit to content, fit to screen or custom height.

The layout settings also include an option to hide or show the close button or show it a set time after the popup loads. 

**Advanced** 
In the Advanced tab, you will find other settings that might come in handy when customizing popups: Prevent Closing on Overlay, Automatically Close After Set Time, Disable Page Scrolling and Avoid Multiple Popups.

### 3. Publish Settings

Click ‘Publish’, and notice the publish settings window that pops up. 

You can set off popups either by customizing triggers (as described in the next section) or by setting a manual trigger through a link.

To manually set off a popup:

1. Click Publish
2. Click ‘Save and Close’
3. Create a new page in Elementor
4. Drag-in a button widget
5. Under layout, choose Link > Dynamic > Actions > Popup
6. Click Popup > Open Popup > Select the popup you created
7. Go to the live page, click on the button and see the popup appear

### 4. Conditions, Triggers & Advanced Rules
![popupsetting](https://user-images.githubusercontent.com/660572/50906878-bd63db80-142e-11e9-84a2-d1ab2dd6c245.png)
If you don’t want to manually set off popups

Now we get to the advanced triggering and targeting options. This is perhaps the most **important** feature we need you to test.

When you hit ‘Publish’, the Publish Settings screen opens up. This window includes Conditions, Triggers, and Advanced Rules.

**Conditions**
Conditions are pretty straightforward and work for popups in the same way they do for all other templates in Elementor. Choose which pages, posts, and areas your popups will be shown in. 

Note that by selecting the location, it doesn't mean that the popup will instantly appear. For that to happen, you will need to set a trigger (‘On load’ for instance).

**Triggers**
Browse around the different triggers: On page load, on scroll, on scroll to element, on click, after inactivity and on page exit intent.

**Advanced Rules**
Differentiating between Triggers and Advanced Rules can be confusing. Triggers function as direct ‘triggers’ for popups (i.e. click to open popup). Advanced Rules determine the requirement that must be met for the popup to appear (i.e. user visited page at least two times)

- Show only if the user visited a certain number of pages
- Show only if the user had a certain number of sessions
- Show or hide only if the user arrived from a specific URL (or regex)
- Show only if a user arrived from a certain source (search engines / external links / internal links)
- Hide for all logged in users or select certain user roles
- Show only if it’s seen on certain devices (desktop / tablet / mobile)

___________________________
## Other Updates:

- New: Introducing Popup builder (#628)
- New: Added User Info dynamic tag (#6322)
- Tweak: Added dynamic capabilities for "Nothing Found"
- Tweak: Added `elementor_pro/theme_builder/archive/escape_nothing_found_message` Filter to avoid HTML escaping in "Nothing Found" message (#6053)
- Fix: `z-index` issue with CTA widget (#6486)
- Fix: Hide the Post Content widget and show it only in a Single document
- Fix: `selector` replacement in Custom CSS
- Fix: Apply `the_content` on the real content only
- Fix: CSS for WC products selector (#6559)
- Fix: Odnoklassniki share URL (#6638)
- Fix: Custom link new tab in Post Info widget (#5766)
- Fix: Post Terms in Post Info widget
- Fix: `nofollow` link in Flip Box & CTA widgets
- Fix: Added screen reader to some icons & buttons for better accessibility (#5386)
_______________________________

### How to Install the Beta Version

If you still haven't enabled beta testing in Elementor, please follow these steps:

1. Go to Elementor > Tools > Versions
2. Enable the beta tester feature
3. Go to Dashboard > Updates and update to the latest beta version.

This will get you testing the new Elementor Pro 2.4.0 Beta

**Designated time for release**: January 21, 2019 (Estimated)

For bugs reports Only, please reply with a comment below!

Many thanks for your support and help!

Cheers,
Elementor Team

**Comment by reachadam** [comment]
Been testing for the past hour. I think there is 1 big thing missing. Before I get to that, I want to say that I am amazed at this when you consider all of the Elementor modules that allow you to pull in data. 

The one thing that may have been overlooked is the ability to embed what you create in a sidebar, above post content, below post content, etc (as content not a popup). There are tons of use cases for this when you mix in the advanced rules that can be implemented. 

A real basic example is having an embedded popup (but the content does not popup) in your sidebar for traffic coming from Facebook. 

Or having an optin form in your sidebar if someone is not logged in, and if they are, have some sort of other CTA. The options are limitless. 

Oh and the dynamic content from users just unlocked personalization features.

**Comment by HQRaja** [comment]
While they wouldn't exactly be popups in that case, I agree with the gist of what @reachadam just said. We should basically have these display conditions and triggers available at section-level, so that we can have a non-popup section added anywhere (be it from within Elementor or through a shortcode), and have them show up based on these conditions or triggers, like in the use cases Adam just mentioned.

**Comment by emailjough** [comment]
From Templates -> Popups ->  edit with Elementor I am taken to Popup Settings and can adjust my popup. However, as soon as I click on a section, column, the navigator or anywhere else I can find no way to get back to Popup Settings. I have to exit elementor and reopen.

**Comment by emailjough** [comment]
I am using an Icon (bars to mimic a hamburger) in my Header as my trigger for my popup (to open a fullscreen html menu).  I can fade in the opening of the pop up, but wish I could also fade out when you close or click outside the modal window. Close is very abrupt.

**Comment by reachadam** [comment]
> From Templates -> Popups -> edit with Elementor I am taken to Popup Settings and can adjust my popup. However, as soon as I click on a section, column, the navigator or anywhere else I can find no way to get back to Popup Settings. I have to exit elementor and reopen.

Of you click on the settings icon on the very bottom left, it will take you back to the popup settings. At least it did for me in a video tutorial I just released on this feature. 

https://www.youtube.com/watch?v=xeFkhhshvvk

**Comment by emailjough** [comment]
> > From Templates -> Popups -> edit with Elementor I am taken to Popup Settings and can adjust my popup. However, as soon as I click on a section, column, the navigator or anywhere else I can find no way to get back to Popup Settings. I have to exit elementor and reopen.
> 
> Of you click on the settings icon on the very bottom left, it will take you back to the popup settings. At least it did for me in a video tutorial I just released on this feature.
> 
> https://www.youtube.com/watch?v=xeFkhhshvvk

Worked for me, thanks very much.

**Comment by emailjough** [comment]
(Is this is the correct place to post this?)

- brand new wordpress install 5.0.3, Cloudways host
- using Phlox theme (free)
- elementor pro 2.4 beta1
- creating a site-wide elementor header, added an icon widget in header to serve as popup trigger
- dynamically link icon to popup
- popup opens while editing header in elementor but on front end get following js console error when icon is clicked; popup doesnt open
- removing dynamic link to popup and reloading on front end clears error, re-add dynamic link and error reappears

jquery.js?ver=1.12.4:2 Uncaught Error: Syntax error, unrecognized expression: #elementor-action%3Aaction%3Dpopup%3Aopen%20settings%3DeyJpZCI6IjEzNzczIn0%3D
    at Function.fa.error (jquery.js?ver=1.12.4:2)
    at fa.tokenize (jquery.js?ver=1.12.4:2)
    at fa.select (jquery.js?ver=1.12.4:2)
    at Function.fa (jquery.js?ver=1.12.4:2)
    at Function.a.find (jquery-migrate.min.js?ver=1.4.1:2)
    at n.fn.init.find (jquery.js?ver=1.12.4:2)
    at n.fn.init.a.fn.find (jquery-migrate.min.js?ver=1.4.1:2)
    at a.fn.init.n.fn.init (jquery.js?ver=1.12.4:2)
    at new a.fn.init (jquery-migrate.min.js?ver=1.4.1:2)
    at n (jquery.js?ver=1.12.4:2)

**Comment by emailjough** [comment]
> I really like the idea of building a popup directly in Elementor. One use case that seems to be overlooked (unless I've missed it) is the ability to trigger a popup after clicking on a specific element, for example, a button or a link. I use these types of popups all the time for login forms, contact forms and as opt-ins.

Elementor widgets with the dynamic link option (buttons, icons, images, CTA, and many others) now have option to trigger popup.

**Comment by JayOkey** [comment]
> > I really like the idea of building a popup directly in Elementor. One use case that seems to be overlooked (unless I've missed it) is the ability to trigger a popup after clicking on a specific element, for example, a button or a link. I use these types of popups all the time for login forms, contact forms and as opt-ins.
> 
> Elementor widgets with the dynamic link option (buttons, icons, images, CTA, and many others) now have option to trigger popup.

I spoke too soon, figured it out literally 5 seconds after posting.

**Comment by bainternet** [comment]
@reachadam @HQRaja @parfilov @emailjough 	

Thanks for the suggestion we will look into it.

### A few notes and clarifications:

* You can set a trigger to show or close a popup via a Popup Dynamic Tag from every dynamic supported link control.
![image](https://user-images.githubusercontent.com/660572/50957187-41b56d80-14c6-11e9-9290-f904164a4e92.png)


* You can set a trigger to show or close a popup as an Action After Submit in forms widget.
![image](https://user-images.githubusercontent.com/660572/50957352-b2f52080-14c6-11e9-82c0-32ac22d54943.png)
![image](https://user-images.githubusercontent.com/660572/50957373-c1dbd300-14c6-11e9-8269-1afae147d10a.png)


* You can always edit popup settings by clicking the cog/gear icon at the buttom
![xy8sufy](https://user-images.githubusercontent.com/660572/50958054-7a564680-14c8-11e9-896e-e12f018739a4.png)


Thanks everyone for the feedback, 

Please keep this related to the Current beta Only! any other [Issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.

Thanks again to everyone.

**Comment by shimonshomron** [comment]
Hi elementor team,
I am super excited for the pop ups integration and the possibilities it hides within.
I have updated elementor to the beta version(2.4.0-beta3), and then the pro to the beta version(2.4.0-beta1).
Sadly all my front end went white-blank for all the pages on the site (admin-panel works propely). I have rolled back the pro.beta and everything works fine (without the popups obviously)
I tried to update the pro.beta again + disabled all my other plugins (only elementor+ pro active) still get dead white across all frontend site. 
I would really glad to play around with the popups however can't get the beta release of e.pro not to break completely my site :(
Thanks, and keep up with the excellent work 

wordpress 5.0.3

**Comment by pritcham** [comment]
Hi

Excited to hear about the popups feature - can't wait until it's ready for release.

Just tried to use it on my site though, and when attempting to create a new popup I receive the following error:

>  Cannot use ElementorPro\Modules\DynamicTags\Module as Module because the name is already in use in /var/sites/xxxxxxx/public_html/wp-content/plugins/elementor-pro/modules/popup/tag.php on line 7

Let me know if you need more info

Cheers
Martin

**Comment by slewisma** [comment]
Made a test popup using the last "Fight With Us" template and set it to exit intent, desktop and mobile, show up to 2 times. Otherwise the only things I changed were backgrounds and text.

Worked great the first time I tried it except for one issue:
Clicking the X in the popup doesn't close it. Pressing escape works fine. 

After that I went back to the site and could not get the popup to show a second time (I didn't submit it the first time and it was set to show up to 2 times with no other trigger conditions and no other advanced settings). 

It would be helpful to hear some detail on what exit intent actually means in this implementation.

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to Elementor Pro v2.4.0 Beta 2.

This beta release includes:
	
* New: Added new toast for Popup Settings panel
* Tweak: Added responsiveness ability for border radius control
* Tweak: Added `elementor-pro/forms/rest_client/init` action hook
* Tweak: Changed Automatically Close After control from `ms` to `sec`
* Fix: Share Button email with custom URL issue (#6653)
* Fix: Update field shortcode on change.
* Fix: PHP Error "Cannot use ElementorPro\Modules\DynamicTags\Module as Module" ... (Thanks @pritcham )

Please keep this related to the Current beta Only! any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.

Thanks again to everyone.

**Comment by pritcham** [comment]
Confirmed that the PHP error has been fixed (checked on 5.6 and works fine).

Would suggest that there's an option on how popup can be closed - i.e. on button click, ESC key etc. I say this as one of the templates is around cookie consent which requires active consent - clicking anywhere on screen (or pressing ESC etc) closes the popup so consent can't be claimed as being given.

Cheers

**Comment by srcek** [comment]
@pritcham Closing the Popup by clicking on overlay can be disabled in Popup Settings > Advanced > Prevent Closing on Overlay. Button can be used to close Popups by setting the link to Dynamic > Popup > Close Popup and enabling Don't Show Again. 
I don't know how to disable the ESC key. It would be great if we could prevent closing Popups with ESC key.

**Comment by estraatios** [comment]
Very nice features.

I would really like to have an extra display contition. When the visitor close a popup I would like to be able to set it to not display again for an amount of days. It is used mostly in optin popups.
Thanks again.

**Comment by ocbroadband** [comment]
I notice there's an option to specify an entrance animation.  However, there is no 'exit' animation.  Would be nice to have balanced.  It's rather abrupt when clicking out of the popup.

**Comment by cjmetacrawler** [comment]
is this included on the beta version ?

https://github.com/pojome/elementor/issues/4440

**Comment by jbsurveyer** [comment]
Elementor Popups resembles Thrive Leads and Astra Probundle Convert Pro... but has more conditions and controls for  positioning and appearance/disappearance

**Comment by SniffleValve** [comment]
So far, so good :) Everything is working as intended for what I have tried. 

A couple questions whether or not these will be in the final release:
- on the Advanced tab, there are no CSS Class Name nor CSS ID fields
- a way to specify the X and Y position of the popup

An AMAZING addition to an already amazing product!

Cheers!
Lyle

**Comment by humemedia** [comment]
So excited to move away from 3rd party popup plugins and use Elementor. Sadly, Beta install killed my site. :( Going to have to revert and hope the stable version works out.

**Comment by fatsandrew7** [comment]
**creating a trigger based popup visible on every page i found this issue on the front end display of the page**
- upon first load, the popup triggers when clicking anywhere (any other link as well as the established trigger link) instead of only the established trigger

**backend/elementor editor requests**
- add full border radius control for the base popup styles as opposed to setting only the same border radius for all corners
- option to animate the closing of the popup

**Comment by fatsandrew7** [comment]
> * New: Added new toast for Popup Settings panel

what does this mean?

**Comment by tristanleboss** [comment]
Developer request : we need ways (and documentation) to add conditions, triggers and advanced rules.

**Comment by fatsandrew7** [comment]
> Developer request : we need ways (and documentation) to add conditions, triggers and advanced rules.

this already exists here:
![image](https://user-images.githubusercontent.com/1708488/51041890-e304f800-1588-11e9-8d6a-ccfbce7baeaa.png)

**Comment by donwattz1459** [comment]
I added one of the pre built popups to a test site and this is what it looks like when i view it live.

![Uploading Screen Shot 2019-01-11 at 10.41.23 AM.png…]()

**Comment by toniubeda** [comment]
There is no possibility of an event onclick through a .css selector.
![onclick-selector-css](https://user-images.githubusercontent.com/6292847/51071753-6b9d9a00-1656-11e9-957a-d104842fa7b8.png)

**Comment by Hansol69** [comment]
In Advanced Rules - have an option for hiding for logged out users as well. In membership websites, this can be very useful.

**Comment by parfilov** [comment]
How about multistep popups? Should I create a individual suggestion issue for this feature?

**Comment by shilo-ey** [comment]
[**@pritcham**](https://github.com/pritcham) commented on [Jan 10, 2019, 5:51 PM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453145134 "2019-01-10T15:51:43Z - Replied by Github Reply Comments"):
> Confirmed that the PHP error has been fixed (checked on 5.6 and works fine).
> 
> Would suggest that there's an option on how popup can be closed - i.e. on button click, ESC key etc. I say this as one of the templates is around cookie consent which requires active consent - clicking anywhere on screen (or pressing ESC etc) closes the popup so consent can't be claimed as being given.
> 
> Cheers
@srcek

Thanks for this report, we've already added it to the next release.


[**@cjmetacrawler**](https://github.com/cjmetacrawler) commented on [Jan 11, 2019, 3:08 AM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453328254 "2019-01-11T01:08:42Z - Replied by Github Reply Comments"):
> is this included on the beta version ?
> 
> https://github.com/pojome/elementor/issues/4440
> 
> I already purchase the plugin and I need this feature. thanks

No.


[**@SniffleValve**](https://github.com/SniffleValve) commented on [Jan 11, 2019, 8:03 AM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453388426 "2019-01-11T06:03:14Z - Replied by Github Reply Comments"):
> So far, so good :) Everything is working as intended for what I have tried. 
> 
> A couple questions whether or not these will be in the final release:
> - on the Advanced tab, there are no CSS Class Name nor CSS ID fields

Each popup gets an automatic ID attribute which is set by:
`elementor-XXX elementor-location-popup` 
and a data-attribute which is:
`data-elementor-id="XXX"`
where XXX is the popup post ID.

> - a way to specify the X and Y position of the popup
> 
> An AMAZING addition to an already amazing product!
> 
> Cheers!
> Lyle

Currently, we enable using alignment and padding/margin.





[**@humemedia**](https://github.com/humemedia) commented on [Jan 11, 2019, 12:13 PM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453465451 "2019-01-11T10:13:34Z - Replied by Github Reply Comments"):
> So excited to move away from 3rd party popup plugins and use Elementor. Sadly, Beta install killed our site. :( Going to have to revert and figure out what plugins are not playing nice.
> 
> UPDATED: We tried disabling most of our plugins, still no dice. We use a template section for the menu of each page and a template section for the footer of each page, both of those disappear when we update to the beta version. Now we're concerned about what's going to happen when the stable release comes out. Going to have to call it a day, unfortunately. :(

Please open a separate issue with detailed information as possible using our [issue template](https://github.com/pojome/elementor/issues/new?template=Bug_report.md)

Thanks.


[**@fatsandrew7**](https://github.com/fatsandrew7) commented on [Jan 11, 2019, 4:37 PM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453536829 "2019-01-11T14:37:28Z - Replied by Github Reply Comments"):
> **creating a trigger based popup visible on every page i found this issue on the front end display of the page**
> <strike>- upon first load, the popup triggers when clicking anywhere (any other link as well as the established trigger link) instead of only the established trigger</strike> -- this was due to choosing "on page click trigger" thinking that was required to activate a click based trigger from another element
> - delay close button appearance only works on first popup interaction. closing and reopening the popup shows the close button immediately


Thanks for reporting, we will take a look.



[**@fatsandrew7**](https://github.com/fatsandrew7) commented on [Jan 11, 2019, 4:39 PM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453537538 "2019-01-11T14:39:39Z - Replied by Github Reply Comments"):
> > * New: Added new toast for Popup Settings panel
> 
> what does this mean?

![image](https://user-images.githubusercontent.com/45009641/51086985-04670f00-1756-11e9-998b-bdcb1eb151e3.png)


**Please keep this related to the Current beta Only! any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.**

Thanks again to everyone.

**Comment by silvioghedin** [comment]
The close button doesnt work on gym template pop-up.

Would be good to have the multistep popup, I've created a way to accomplish this but its not intuitive, hope you guys make it easier ;)

**Comment by nelgster** [comment]
where do i find  Core v.2.4 Beta ?

**Comment by SniffleValve** [comment]
Popups set to Draft still appear when conditions met/triggered.

Cheers!
Lyle

**Comment by shilo-ey** [comment]
[**@silvioghedin**](https://github.com/silvioghedin) commented on [Jan 13, 2019, 9:01 PM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453856254 "2019-01-13T19:01:59Z - Replied by Github Reply Comments"):
> The close button doesnt work on gym template pop-up.


Thanks, we will look into that.


[**@nelgster**](https://github.com/nelgster) commented on [Jan 14, 2019, 1:02 AM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453873945 "2019-01-13T23:02:08Z - Replied by Github Reply Comments"):
> where do i find  Core v.2.4 Beta ?

[Right here](https://github.com/pojome/elementor/issues/6630)


[**@SniffleValve**](https://github.com/SniffleValve) commented on [Jan 14, 2019, 4:34 AM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-453889810 "2019-01-14T02:34:51Z - Replied by Github Reply Comments"):
> Popups set to Draft still appear when conditions met/triggered.
> 
> Cheers!
> Lyle

Thanks @SniffleValve for bringing this to our attention, we are working on a way to solve it.


**Please keep this related to the Current beta Only! any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.**

Thanks again to everyone.

**Comment by parfilov** [comment]
Form widget Mark Color option is absent.

**Comment by legion1978** [comment]
Hello. will it have the option to reopen after a determined amount of time? hours, days? thanks.

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to v2.4.0 Beta 3.

This beta release includes:
- New: Added “Toggle” option for Popup dynamic tag
- New: Added prevent closing on ESC key option
- Fix: Search results for Popups in Dynamic tag
- Fix: Accessibility labels in Reviews widget
- Fix: Link to cart page not working when WooCommerce Subscriptions is active
- Fix: MailChimp Selected list not showing on reloading in Form widget
- Fix: Sub-menu arrow causes unwanted additional padding in Nav Menu widget


**Please keep this related to the Current beta Only! any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.**

Thanks again to everyone.

**Comment by parfilov** [comment]
@bainternet why did you delete my post about form Required Mark color?! It relates directly to this release. I don't see this issue in Elementor Pro v2.3.1

**Comment by bainternet** [comment]
[**@parfilov**](https://github.com/parfilov) commented on [Jan 14, 2019, 8:30 PM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-454110430 "2019-01-14T18:30:16Z - Replied by Github Reply Comments"):
> @bainternet why did you delete my post about form Required Mark color?! It relates directly to this release. I don't see this issue in Elementor Pro v2.3.1

Accidentally 🤪, 
![image](https://user-images.githubusercontent.com/660572/51133655-45d2e980-183e-11e9-9a8a-6794c69ef415.png)

but anyway, we can't replicate so please open a separate issue following our 
[Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) 


Thanks.

**Comment by parfilov** [comment]
@bainternet this is my fault. I didn't switch the required toggle on the form content tab. It seems I need a little bit more sleep and a little less Elementor 😂

**Comment by ocbroadband** [comment]
Not sure if this existed in the previous beta's, but I've found that the 'Nav Menu' when selecting a submenu indicator, it offsets that specific menu item vertically down within the menu.  In my case, it's a horizontal menu.  I have another site that has v2.3.1 still, and this behavior does not occur and this only appeared once I updated.  If I remove the submenu indicator, then the menu items are aligned.

**Without Submenu Indicator**
![chrome_nkb7vuuchy](https://user-images.githubusercontent.com/13633011/51159804-d8c05380-183f-11e9-8ffd-deabbc121625.png)

**With Submenu Indicator**
![chrome_q1etyxk68y](https://user-images.githubusercontent.com/13633011/51159814-e1188e80-183f-11e9-83ee-2c3f0729778c.png)

**Comment by ocbroadband** [comment]
Also, see there are double 'Editing Handles' in the "Edit Post Content" Widget.  I did not see this in the previous beta versions.  This is a simple Section with an inner and 3 columns.  The Post Content widget placed, and it shows multiple Handles as you pass over the upper right portion of the widget.

![chrome_ral2eyte9h](https://user-images.githubusercontent.com/13633011/51160306-3eadda80-1842-11e9-8a7d-d0e05c856737.png)

**Comment by shilo-ey** [comment]
[**@ocbroadband**](https://github.com/ocbroadband) commented on [Jan 15, 2019, 7:05 AM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-454268414 "2019-01-15T05:05:15Z - Replied by Github Reply Comments"):
> Not sure if this existed in the previous beta's, but I've found that the 'Nav Menu' when selecting a submenu indicator, it offsets that specific menu item vertically down within the menu.  In my case, it's a horizontal menu.  I have another site that has v2.3.1 still, and this behavior does not occur and this only appeared once I updated.  If I remove the submenu indicator, then the menu items are aligned.
> 
> **Without Submenu Indicator**
> ![chrome_nkb7vuuchy](https://user-images.githubusercontent.com/13633011/51159804-d8c05380-183f-11e9-8ffd-deabbc121625.png)
> 
> **With Submenu Indicator**
> ![chrome_q1etyxk68y](https://user-images.githubusercontent.com/13633011/51159814-e1188e80-183f-11e9-83ee-2c3f0729778c.png)


[**@ocbroadband**](https://github.com/ocbroadband) commented on [Jan 15, 2019, 7:22 AM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-454270692 "2019-01-15T05:22:13Z - Replied by Github Reply Comments"):
> Also, see there are double 'Editing Handles' in the "Edit Post Content" Widget.  I did not see this in the previous beta versions.  This is a simple Section with an inner and 3 columns.  The Post Content widget placed, and it shows multiple Handles as you pass over the upper right portion of the widget.
> 
> ![chrome_ral2eyte9h](https://user-images.githubusercontent.com/13633011/51160306-3eadda80-1842-11e9-8a7d-d0e05c856737.png)

Thanks for reporting. we are looking into these issues.

**Comment by bekreative** [comment]
Hi, 

Since Elementor 2.4 stable released there seems to be an issue with popup height settings and negative margins relation (using EPRO beta-3):

![screen recording 2019-01-15 at 10 42 03 80 am](https://user-images.githubusercontent.com/46710195/51175518-78b6c500-18b2-11e9-83e0-7e6f305bf599.gif)

**Comment by shilo-ey** [comment]
[**@bekreative**](https://github.com/bekreative) commented on [Jan 15, 2019, 12:45 PM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-454347968 "2019-01-15T10:45:01Z - Replied by Github Reply Comments"):
> Hi, 
> 
> Since Elementor 2.4 stable released there seems to be an issue with popup height settings and negative margins relation (using EPRO beta-3):
> 


From the screenshot you are editing the section height and not the Popup document height.

thanks.

**Comment by humemedia** [comment]
The menu issues shown by @shilo-ey are occurring in the stable release as well. We had to revert to a previous version. We found it also broked our humburger menus on mobile. The menu was visible, but the drop-down didn't work when tapping the menu.

**Comment by parfilov** [comment]
@bainternet Sub-menu arrow causes unwanted additional padding in Nav Menu widget issue is still exists

<img width="883" alt="menu_issue1" src="https://user-images.githubusercontent.com/12493645/51212046-81a2a780-1941-11e9-8936-2e238eab509a.png">


WordPress 5.0.3
Elementor - 2.4.1
Elementor Pro - 2.4.0-beta3
Astra 1.6.4
Tried to deactivate all plugins. No cache.

**Comment by humemedia** [comment]
@bainternet I don't see it listed in fixes for 2.4.1, so I'm assuming it hasn't been released yet. Incidentally, we're using Astra as well, so I wonder if it's an Astra issue. It seems like every time I update Astra, something goes out of whack (margins, padding, etc.).

**Comment by btrfabrications** [comment]
Thanks for the fix on loading single product templates with WC Composite Products and Product Bundles. However, the formatting of the 'add to cart section' for composite products is bad - and no options to edit it - with dropdown menus only half visible and insufficient padding between sections. This needs to at least be fixed, but preferably editable. 
![btr elementor 24 beta composite product display problems](https://user-images.githubusercontent.com/44300682/51283899-7d2dcb80-19e1-11e9-9415-a588a8143bcf.jpg)

I also get the same nav menu misalignment as @parfilov.

WP 5.0.3
Elementor 2.4.1
Elementor Pro 2.4.0-beta3
Generatepress 2.2.1
Generatepress Premium 1.7.7

**Comment by shilo-ey** [comment]
[**@parfilov**](https://github.com/parfilov) commented on [Jan 15, 2019, 11:49 PM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-454564689 "2019-01-15T21:49:06Z - Replied by Github Reply Comments"):
> @bainternet Sub-menu arrow causes unwanted additional padding in Nav Menu widget issue is still exists
> 
> <img width="883" alt="menu_issue1" src="https://user-images.githubusercontent.com/12493645/51212046-81a2a780-1941-11e9-8936-2e238eab509a.png">
> 
> 
> WordPress 5.0.3
> Elementor - 2.4.1
> Elementor Pro - 2.4.0-beta3
> Astra 1.6.4
> Tried to deactivate all plugins. No cache.

Will be fixed in the next Pro release.




[**@btrfabrications**](https://github.com/btrfabrications) commented on [Jan 17, 2019, 12:56 AM GMT+2](https://github.com/pojome/elementor/issues/6663#issuecomment-454975978 "2019-01-16T22:56:09Z - Replied by Github Reply Comments"):
> Thanks for the fix on loading single product templates with WC Composite Products and Product Bundles. However, the formatting of the 'add to cart section' for composite products is bad - and no options to edit it - with dropdown menus only half visible and insufficient padding between sections. This needs to at least be fixed, but preferably editable. 
> ![btr elementor 24 beta composite product display problems](https://user-images.githubusercontent.com/44300682/51283899-7d2dcb80-19e1-11e9-9415-a588a8143bcf.jpg)

Please open a new issue with the full details and please provide link to a live website.

Thanks.

**Comment by zeinnicholas** [comment]
Please consider this issue to complement the popup builder: #6779

**Comment by bainternet** [comment]
We just released a new beta version, please update your version to v2.4.0 Beta 4.

This beta release includes:
- Fix: Sub-menu arrow position in Nav Menu widget

Please keep this related to the Current beta Only! any other [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) or [Feature Request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md) feel free to open a new issue.

Thanks again to everyone.

**Comment by bainternet** [comment]
Thanks everyone for your help and feedback.

Elementor Pro v2.4.0 is now live.

please feel free to let us know of any [Issue Report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Thanks again to everyone.

**Comment by santoluis** [comment]
> Hi elementor team,
> I am super excited for the pop ups integration and the possibilities it hides within.
> I have updated elementor to the beta version(2.4.0-beta3), and then the pro to the beta version(2.4.0-beta1).
> Sadly all my front end went white-blank for all the pages on the site (admin-panel works properly). I have rolled back the pro.beta and everything works fine (without the popups obviously)
> I tried to update the pro.beta again + disabled all my other plugins (only elementor+ pro active) still get dead white across all frontend site.
> I would really glad to play around with the popups however can't get the beta release of e.pro not to break completely my site :(
> Thanks, and keep up with the excellent work
> 
> wordpress 5.0.3
 i have this same problem with the latest wordpress and elementor al feature work fine donde al the trobleshooting advised by elementor and still white page could you resolve this?
