### ISSUE TITLE
Add a "switch" for temporary hiding a section 

### ISSUE THREAD

**Issue by reinhardkonrad** [pojome/elementor#6666]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Sometimes I want to hide for example a complete section or maybe a field or a text item for some time. At the moment I need to delete the section or object. Later I have to rebuild that element.
When I use a theme template or single template form the global library, sometimes I don't need all Elements at the moment, but maybe later. So in this case it would be great to have a switch to turn a section for example on and off.

**Describe the solution you'd like**
Add to sections and maybe all widgets a switch to turn them on and off.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can set the visibility of the section to hidden for desktop, tablet and 
mobile so it will not show.
![image](https://user-images.githubusercontent.com/660572/50954840-352e1680-14c0-11e9-8dba-2470836d7e86.png)

Thanks for the feedback.
