### ISSUE TITLE
Archive Posts Display number per page on different break points

### ISSUE THREAD

**Issue by ivyliups** [pojome/elementor#6668]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For Desktop display, I am using 3 columns display, 1 row, to show 3 posts by page.
But for tablet, I want to use 2 columns display, but then I cannot change the posts by page to 4, so it always had a missing posts on the 4th post.
I am a bit frustrated that there is always an empty space on tablet as it can only display 3 posts.

**Describe the solution you'd like**
May I ask is it possible to set the posts per page display differently on desktop and tablet?

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
