### ISSUE TITLE
Missing "Query" option for "Archived Products"

### ISSUE THREAD

**Issue by thread404cp** [pojome/elementor#6671]
Hello there,
I'm setting up a webshop using a product archive template with Elementor Pro. I'm trying to set the "Archive Products" widget to only show products in a specific category. I've watched videos on YouTube and they all show the widget having a "Query" option where this can be done.

For some reason I only have "Content" and "Advanced", only the "Products" widget has the Query option, but lacks some of the visuals Archive Products has.

**Comment by bainternet** [comment]
@thread404cp 	


It's not missing, this is by design, the "Archive Products" widget uses the "current" query. Much like "Archive Posts" widget.


thanks.

**Comment by grzesir** [comment]
What is the "current" query?

**Comment by grzesir** [comment]
By the way, this is the video he is referring to. In the video it shows the "query" tab, but it is not in the actual elementor product: https://elementor.com/blog/customize-woocommerce-product-page/
