### ISSUE TITLE
Sub-Menu entry not reachable in landscape mode on mobile phone

### ISSUE THREAD

**Issue by Thotti79** [pojome/elementor#6674]
Note: Andri from your support team could reproduce this error on his test site (mail from 4th January 2019).

On a client site (and generally) we have a menu entry with 6 sub-menu entries. The sixt (last) sub-menu entry is not reachable if you use your mobile phone in landscape mode.

Please fix this.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
