### ISSUE TITLE
[Feature Request ] WooCommerce Variations widget

### ISSUE THREAD

**Issue by Source3Media** [pojome/elementor#6675]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A popular part of WooCommerce is product variations and when I was building a product page for my clients whom have variable products in their WooCommerce stores and realized that there isn't a widget specifically for it or one that works with it.

**Describe the solution you'd like**
I would like a widget or an element added to a widget that would allow the use of variable products in the single product template.

**Additional context**
I am trying to avoid work-arounds for this but if there are any, I would be open to testing them.

**Comment by AndersJpg** [comment]
+1

**Comment by bainternet** [comment]
@Source3Media 

It's already working in single product templates out of the box:

![image](https://user-images.githubusercontent.com/660572/51086666-03cc7980-1752-11e9-8980-909af50426b1.png)


thanks.
