### ISSUE TITLE
Sub-Menu entry not reachable in landscape mode on mobile phone

### ISSUE THREAD

**Issue by Thotti79** [pojome/elementor#6677]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

If you have more than 6 SUB-menu entries, the sixth sub-menu entry is not reachable in landscape mode on mobile phones. You can try to scroll with your fingers to reach it, but it doesn't work.

## Steps to reproduce
1. Create a menu with at least 6 sub-pages
2. Create a sub-menu for one main-menu entry with at least 6 sub-menu entries
3. Use Elementor Menu Widget to build a menu
4. Save created menu with elementor
5. Use your mobile phone in landscape (horizontal) mode and try to reach the sixth sub-menu entry from one main menu-entry.
6. The sixth sub-menu entry is not reachable

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v5.6.36-82.2
	PHP Version: 7.2.14
	PHP Max Input Vars: 5000
	PHP Max Post Size: 96M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.9
	Site URL: https://www.birkenhof-mueden.de/new_wp
	Home URL: https://www.birkenhof-mueden.de/new_wp
	WP Multisite: No
	Max Upload Size: 96 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: SeproWeb Child-Theme
	Version: 1.0.0
	Author: Thorsten Sebode
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.6.2
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.9
		Author: Elliot Condon

	Akismet Anti-Spam
		Version: 4.1
		Author: Automattic

	All In One WP Security
		Version: 4.3.8.3
		Author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy

	Astra Premium Sites
		Version: 1.2.9
		Author: Brainstorm Force

	Astra Pro
		Version: 1.6.9
		Author: Brainstorm Force

	Borlabs Cookie - Cookie Opt-in
		Version: 1.9.7
		Author: Benjamin A. Bornschein, Borlabs

	Breadcrumb NavXT
		Version: 6.2.1
		Author: John Havlik

	Code Snippets
		Version: 2.13.0
		Author: Shea Bunge

	Convert Pro
		Version: 1.3.1
		Author: Brainstorm Force

	Convert Pro - Addon
		Version: 1.1.5
		Author: Brainstorm Force

	Elementor
		Version: 2.3.8
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.6
		Author: Namogo

	Elementor Pro
		Version: 2.3.1
		Author: Elementor.com

	eRecht24 Rechtstexte
		Version: 1.1.0
		Author: Weslink

	Essential Addons for Elementor - Pro
		Version: 2.13.2
		Author: WPDeveloper

	Favicon by RealFaviconGenerator
		Version: 1.3.14
		Author: Philippe Bernard

	JetBlocks For Elementor
		Version: 1.1.4
		Author: Zemez

	Jet Elements For Elementor
		Version: 1.14.7
		Author: Zemez

	JetEngine
		Version: 1.2.4
		Author: Zemez

	Microthemer
		Version: 5.5.1.4
		Author: Themeover

	Quotes Collection
		Version: 2.0.10
		Author: Srini G

	RSS Feed Widget
		Version: 2.7.2
		Author: Fahad Mahmood

	Schema Pro
		Version: 1.1.11
		Author: Brainstorm Force

	ShortPixel Image Optimizer
		Version: 4.12.3
		Author: ShortPixel

	Smart Slider 3 Pro
		Version: 3.3.11
		Author: Nextend

	TinyMCE Advanced
		Version: 4.8.2
		Author: Andrew Ozz

	Toolset Access
		Version: 2.6
		Author: OnTheGoSystems

	Toolset Forms
		Version: 2.2.1.1
		Author: OnTheGoSystems

	Toolset Layouts
		Version: 2.5.1
		Author: OnTheGoSystems

	Toolset Maps
		Version: 1.7.1
		Author: OnTheGoSystems

	Toolset Types
		Version: 3.2.3
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.7.1
		Author: OnTheGoSystems

	Ultimate Addons for Elementor
		Version: 1.8.4
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 2.16.0.24
		Author: UpdraftPlus.Com, DavidAnderson

	WP Cerber Security, Antispam & Malware Scan
		Version: 7.9.3
		Author: Gregory

	WP Rocket
		Version: 3.2.3.1
		Author: WP Media

== Debug ==
	Errors: 
		TypeError: Cannot read property 'html' of undefined
			at https://www.birkenhof-mueden.de/new_wp/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.3.1 - 2:220509
			2018-11-16 16:23 +00:00

		TypeError: setting getter-only property "type"
			at https://www.birkenhof-mueden.de/new_wp/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:86630
			2018-10-08 13:40 +00:00
			x 3 times

		TypeError: Cannot read property 'on' of null
			at https://www.birkenhof-mueden.de/new_wp/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:213094
			2018-10-02 20:46 +00:00
			x 2 times

		TypeError: Cannot read property 'style' of undefined
			at https://www.birkenhof-mueden.de/new_wp/wp-admin/js/editor.min.js?ver=b06a58973a2e07d275c1d1099f953f35 - 1:694
			2018-10-02 20:46 +00:00

		TypeError: Cannot read property 'on' of null
			at https://www.birkenhof-mueden.de/new_wp/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:213094
			2018-10-02 20:46 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://www.birkenhof-mueden.de/new_wp/wp-admin/js/editor.min.js?ver=b06a58973a2e07d275c1d1099f953f35 - 1:694
			2018-10-02 20:46 +00:00

		TypeError: Cannot read property 'on' of null
			at https://www.birkenhof-mueden.de/new_wp/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:213094
			2018-10-02 20:46 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://www.birkenhof-mueden.de/new_wp/wp-admin/js/editor.min.js?ver=b06a58973a2e07d275c1d1099f953f35 - 1:694
			2018-10-02 20:46 +00:00

		TypeError: Cannot read property 'on' of null
			at https://www.birkenhof-mueden.de/new_wp/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.4 - 2:213094
			2018-10-02 20:46 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://www.birkenhof-mueden.de/new_wp/wp-admin/js/editor.min.js?ver=b06a58973a2e07d275c1d1099f953f35 - 1:694
			2018-10-02 20:46 +00:00

				
</details>

**Comment by shilo-ey** [comment]
Hey @Thotti79 ,

Thanks for your feedback.

This issue cannot be replicated with other themes. This is happening because of the theme's setting to scroll the body while the menu is open.

Try to disable it via your theme settings/custom CSS.

Thanks.
