### ISSUE TITLE
[Feature Request] - Integration with leadlovers (email mkt solution)

### ISSUE THREAD

**Issue by robsonferrll** [pojome/elementor#6678]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

We're a brazilian email marketing solution and a lot of our customers are asking for integration with Elementor.
Our customers misses a native integration with Elementor. A increase number of them are using Elementor as a page builder and we're receiving a a lot feature requests about this.

**Comment by bainternet** [comment]
@robsonferrll 

You are more than welcome to create that integration, and we'd be happy to assist when needed.

API Docs: https://developers.elementor.com

good luck.
