### ISSUE TITLE
How to link new Pop Up builder with email marketing tools

### ISSUE THREAD

**Issue by jeansaldana** [pojome/elementor#6681]
Hi!

I would like to know if there is already a feature to connect Elementor pop up builder with email marketing tools as Active campaign to integrate wtih html code.

Thanks!

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
