### ISSUE TITLE
Can`t translate the title "Search Results for:" on the Search Results Page is an Archive

### ISSUE THREAD

**Issue by kvorus** [pojome/elementor#6685]
Probably the phrase is not ready for translation.  
It is also not clear how to translate the phrase: "It seems we can't find what you're looking for."

**Comment by bainternet** [comment]
@kvorus 	


"Search Results for: %s" is a string wrapped in `__()` function meaning it is translatable.

look for:
```PHP
__( 'Search Results for: %s', 'elementor-pro' )
```

thanks.
