### ISSUE TITLE
Variety in "social icons" widget

### ISSUE THREAD

**Issue by Andreugg** [pojome/elementor#6687]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hi guys,

I would like to make a little request: in the social icons widget, could you please add the different versions of the icons for the social networks? For example, Youtube has a couple of different icons: one with text and another without it (see image). In the icon widget, appear all of them and I can choose so that's great, but in the social icons widget only appears one version.

I know that this isn't a big issue but we found on our agency that some clients ask for a specific icon and sometimes it's not the one in the social icons widget. So... could you please add the same social network icon variety that we already have on the icon widget to the social widget please?
  
Thanks in advance,

Andreu

![socialicons](https://user-images.githubusercontent.com/42344881/51033729-9e875580-15a4-11e9-81fd-ec32c3b8cc88.png)

**Comment by shilo-ey** [comment]
I merged this issue with  #110 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
