### ISSUE TITLE
Flexible "submit" button position on forms

### ISSUE THREAD

**Issue by Andreugg** [pojome/elementor#6688]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hi guys,

In the forms widget we have a little issue regarding the submit button position. With the GDPR we have to add the "acceptance" field and that messes around with some form designs, for example, if we want the classic design with all the fields (name, email and submit) in the same line, we can't add the acceptance field. That is because it is located BEFORE the submit button, so when I add that field, button is not going to be in the same line anymore and goes below. See image attached for a visual understanding:

![forms](https://user-images.githubusercontent.com/42344881/51034168-15711e00-15a6-11e9-81cf-19a50c9e9351.png)

In this example I want the button right next to the email field where the arrow is pointing, but I can't do it. I know this is possible with CSS, but this kind of design is very popular and our agency uses it a lot, so it would be great to have a native solution without messing around with code everytime.

Could you please consider to make some adjustments on this please?

Thanks in advance.

Andreu

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, you can do that with custom CSS, like setting the order of the acceptance field:

![image](https://user-images.githubusercontent.com/660572/51083856-74ab6b80-1729-11e9-908d-d127f00d852e.png)

Thanks for the feedback.

**Comment by LRA1** [comment]
> 
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> For now, you can do that with custom CSS, like setting the order of the acceptance field:
> 
> ![image](https://user-images.githubusercontent.com/660572/51083856-74ab6b80-1729-11e9-908d-d127f00d852e.png)
> 
> Thanks for the feedback.

I need this in PRO version.
Thank you!
