### ISSUE TITLE
Conflict between Elementor Pro and Sticky Plugin v1.0.4 for jQuery

### ISSUE THREAD

**Issue by Barinburo** [pojome/elementor#6689]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor Pro have the conflict with the Sticky Plugin v1.0.4 for jQuery ( https://github.com/garand/sticky )

please, any tips.

sticky header doesnt work

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Barinburo** [comment]
Hello , 
Elementor Pro have the conflict with the Sticky Plugin v1.0.4 for jQuery  ( https://github.com/garand/sticky ) 


please,  any tips.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by pitus** [comment]
Why is this issue closed if it's unresolved even Today?
I keep getting errors about the sticky conflict (WP is trying to call an "update" method on the stickyHeader, but the Elementor's version of jquery.sticky library doesn't have that method, hence the error.
Also, the gallery doesn't work - it shows thumbnails but when I click on any one of them, the large image never shows up, only navigation arrows - that's when I saw the js error about the sticky conflict.
