### ISSUE TITLE
Onepage scroll navigation

### ISSUE THREAD

**Issue by zimmiel** [pojome/elementor#6692]
Hello! I want to do onepage scroll navigation. Only use Elementor (without additional plugins)
you are planning add this features?
[like here](https://jetelements.zemez.io/scroll-navigation/#Scroll_Section_1)

it would help a lot

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
