### ISSUE TITLE
Responsive Images 

### ISSUE THREAD

**Issue by dhirnitish** [pojome/elementor#6695]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor does not do responsive images based on the device width right now. 

However wordpress core does provide that functionality by default but it gets lost when you add images through Elementor. 

When a larger image from desktop is being loaded on a mobile device the full image is being loaded. If responsive images is supported then size of the image loaded would be based on the screen. 

**Describe the solution you'd like**
With responsive images supported only the most relevant size of the image is loaded based on the device width. Your site stays faster and you don't have to worry about image quality and sizing. 

**Additional context**
Wordpress: https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/

Google Pagespeed: https://developers.google.com/web/fundamentals/design-and-ux/responsive/images

**Comment by bainternet** [comment]
@dhirnitish 


Elementor does use `srcset` for image widget by default:

![image](https://user-images.githubusercontent.com/660572/51083567-1da39780-1725-11e9-9466-9296eb13e528.png)


thanks.
