### ISSUE TITLE
Custom Query for WooCommerce Products?

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#6696]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Maybe I'm missing something, but is there a way I can set custom query filter on Products? I know there's one for posts and portfolio, but it doesn't seem, there is one for Products.

**Describe the solution you'd like**
Make a custom query for Products. Lets say, I want to have a section with best selling products on HP.

**Additional context**
There's a closed issue on similar problem here: #6025. But it was closed without any sign of a solution, the author just decided to do it another way, without using Elementor.

**Comment by smile00000** [comment]
Bump~

**Comment by bainternet** [comment]
@black-eye 	

We kept the native Woocommerce `woocommerce_shortcode_products_query` filter for query args which you can use, ex:

```PHP
add_filter( 'woocommerce_shortcode_products_query', function( $query_args, $attributes, $type) {
	// modify the query args.
	return $query_args;
}, 10, 3);
```

thanks.

**Comment by black-eye** [comment]
@bainternet ok, thanks for your advice.

But what about, when I want to target one specific widget, moreover when I want to have 2 widgets with 2 differet custom queries on one page? Can I target your widget more exactly?

**Comment by IlPizza79** [comment]
Hi @black-eye, 
did you find a way to use a custom query for a specific Products widget?
Thanks
