### ISSUE TITLE
Multiple Simultaneous Background Types 

### ISSUE THREAD

**Issue by taropaa** [pojome/elementor#6698]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I cannot set both a background image and a gradient for elements that support it. 

**Describe the solution you'd like**
I would like to set BOTH a background image and a gradient. For example, I have a transparent PNG as a background, and I set a background gradient to be behind it.
In standard CSS you can have:

- Background Color
- Background Gradient
- Background Image

at the same time. I don't see why using the elementor interface I have to only be restricted to using one of these. 
A possible way to implement this is to introduce a clear/or none option to each background type. At the same time when switching between the background types, instead of removing the background from the element, it can simply remain there. 
Alternately you could introduce multiple stacked background types, but that may create some confusion. 

**Describe alternatives you've considered**
I can declare a background through the CSS panel, but the point of Elementor is to provide an easy to use interface for such edits.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
