### ISSUE TITLE
Show popup on any page (from Elementor or not)

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#6700]
Hello guys,

The new Elementor popup feature, I checked with support from you and they informed me that the popup will only appear on the pages created with Elementor itself.

But I leave here as a suggestion for Elementor to give the possibility to show popup for any page of my site, whether created with Elementor or not.

Thank you,
Rodrigo Carlos

**Comment by bainternet** [comment]
@proddigital 

Popup will appear on any page that matches the conditions and rules, regardless of page being build with elementor or not.

thanks.
