### ISSUE TITLE
Can query ID be used to display a custom pagination like a grouping of posts by date published?

### ISSUE THREAD

**Issue by Jonyorker** [pojome/elementor#6701]
Hi Everyone,

I was told by support to post this here, so hopefully this was the right place.

I have a post block that uses a QueryID to further filter by custom ACF fields and that's working fine as is.

Now the client wants to further group things in a pagination style, but every link is a grouping of posts by published date, basically 1 section per year. So I guess my question is twofold.

1 - Can queryID be used to output custom code or is it only for enhanced filtering of the query?
2- Is it possible to use AJAX to update/change the filters in queryID?

Thanks!

**Comment by bainternet** [comment]
@Jonyorker 

1) Query Id simply lets you filter/modify the query parameters.
2) Probably, but it won't cause the widget the re-render the posts, that would have to be done via custom code.


thanks.
