### ISSUE TITLE
Vertical red line to right of added sections

### ISSUE THREAD

**Issue by deangg98** [pojome/elementor#6702]
Here is a video of the issue

https://www.useloom.com/share/16cb9b21516d4891a030d3a297720e0a

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
