### ISSUE TITLE
Instantiated "disabled" field in a form does not reach client

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#6704]
## Prerequisites

- [+ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ +] The issue still exists against the latest stable version of Elementor.

## Description

My site visitor may wish to send the site owner a link to a product which is created on the fly.
The link is generated and injected into a regular input form field by the site software. 
The visitor adds personal data and the form is sent. All works well. 

The problem: When I set the input field to "disabled" to make sure that its content cannot be modified,
it is not sent properly. 

I used jQuery to disable the input field.

## Steps to reproduce

Reproduce is easy: comment / comment out the jQuery disable request

## Isolating the problem

- [+] This bug happens with only Elementor plugin active (and Elementor Pro).
- [not applicable] This bug happens with a default WordPress theme active.
  I use child theme of default 2017. Single page. And use Ajax to grab the form template!
- [+] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/SkhCnD68
```
</details>

FINAL NOTE:
There might be a better way of adding a link to a user form.
Example: using simple text element in a from (not supported by Elementor)
or some other way.
I am open for suggestions - thanks!
Mulli

**Comment by bainternet** [comment]
@Mulli 	

We use the FormData API to get the form values, which means this is totally standard behavior for HTML forms. Disabled fields are not processed.

What you can try is set the field to `readonly` instead of disabled, or use a hidden field instead.

thanks.

**Comment by Mulli** [comment]
You are right! HUGE thanks!
