### ISSUE TITLE
Custom CSS to sub menu opening upwards

### ISSUE THREAD

**Issue by Tony19955** [pojome/elementor#6706]
Dear Github, I would like to know how to edit nav menu with CSS (I think it is the best way) to get sub menu opens upwards, not standard downwards. I want this feature because it is menu in the footer and logically sub menu of parent need to be opened to upwardds. Also I would like to now how to edit CSS to stretch sub menu to whole site width. I purchased Elementor PRO and browsed whole internet to find this and I just stuck at this point, thanks for any help .

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by Tony19955** [comment]
Hello bainternet, I wrote to Elementor Community - no answer. I wrote to Elementor support - they redirect me here. Now you want to redirect me to other links. I paid 49$ for customer support as well, not only for premium widgets and themes. This issue is about 10-15 lines of CSS code and I can't move up with my online store because people care more about when to put my issue than how to solve it.
