### ISSUE TITLE
Pages with Animation are slow on scroll, not smooth.

### ISSUE THREAD

**Issue by KoshaK0** [pojome/elementor#6707]
Hi,

there sims to be a problem with Entrance Animation on Google Chrome. Any page I have Entry animation enabled are struggling when scrolling. Animation itself just jumps half way in, not smooth. The Same pages works all well on Edge and Firefox. This is also confirmed by other users in Elementor Facebook Group. I don't really know if this Chrome or Elementor issue... But I can see other pages not made with Elementor working well on Chrome with Entrance Animation.
Can you please check?
All versions of Chrome and Elementor are up-to-date...
Regards,
Kos

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
