### ISSUE TITLE
Support rest api

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#6708]
## Prerequisites

- [+ ] I have searched for similar features requests in both open and closed tickets and cannot find an OPEN duplicate.
- [+ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I wish to use Elementor as "widget generator" for my application(s).
The first is a Tile Simulator where I use a template widget 
You may look at [https://wordless.co.il](https://wordless.co.il) and perform the folowing steps:
1. Select a tile on the right handside (mouse click)
2. Put the selected tile on the left handside (mouse click)
3. Click open send mail - YOU WILL SEE the Elementor template used

**Describe the solution you'd like**
Just provide rest-api end point & access to Elementor templates.
I think I can build a plugin, but this is realy Elementor basic api

**Describe alternatives you've considered**
Ajax is an option, but rest api is better.

**Additional context**
It will require HTTPS.

**Comment by bainternet** [comment]
@Mulli 

You can add rest support yourself:

```PHP
/**
 * allow show in rest elementor_templates
 */
add_action( 'init', function () {
	global $wp_post_types;
	$type = Elementor\TemplateLibrary\Source_Local::CPT;

	if ( isset( $wp_post_types[ $type ] ) ) {
		$wp_post_types[ $type ]->show_in_rest = is_user_logged_in();
		$wp_post_types[ $type ]->rest_base = $type;
		$wp_post_types[ $type ]->rest_controller_class = 'WP_REST_Posts_Controller';
	}
}, 250 );
```

which is exactly what we use in [Elementor Blocks for Gutenberg](https://wordpress.org/plugins/block-builder/).

In other words, you can install that plugin and it will add rest support for you. without the above snippet.

Or, you can wait until we merge that plugin into Elementor and you will have Rest support out of the box.

Good luck.

**Comment by Mulli** [comment]
You are a champ! thanks.
At this point I do not need Gutenberg at all.
Does the plugin have any other advantage(s) over the simple snippet above?
Apart from you maintaining the plugin...?

**Comment by bainternet** [comment]
It adds an Elementor template block to gutenberg

**Comment by Mulli** [comment]
Can I replace the specific Gutenberg parts with my app (Tilesim) parts?
Are you guys thinking of opening it to any app and not only Gutenberg??
