### ISSUE TITLE
Popups Close button border radius and separate size for container and icon

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#6714]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For more design adaptivity, there would be great to have in Popup's close button:
- border radius for more variants of it's design;
- separate size for close button container and "x" icon for more size control.

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
