### ISSUE TITLE
Multistep popups

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#6716]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Multistep popups helps to improve the conversion with showing more relevant offers base on user reaction. The simple example is Yes/No question popup. For Yes we can show one result (subscribe form, promocode etc.) and for No — another result or close the popup (close feature is present with dynamic feature).

**Describe the solution you'd like**
I want the next steps appear at the same popup window as the main content from the first action (main popup).

**Describe alternatives you've considered**
I created 3 popups. One main with Yes/No buttons, one for Yes and another one for No. Then I mapped buttons on main popup with dynamic feature. The next popups opened over the top of main but it's not right. Another steps content should appear in the same window as main popup content.

**Additional context**
Another reason is popup forms. I've made form in popup and set the popup action after submit with another "thank you" popup which said that form was sent successful. All works fine but I've seen the "thank you" popup over the top of popup with form. The right solution is to show "thank you" content instead of form content.

**Competitor's solutions**
Optin monster
Ninja popups
Convertpro

**Comment by bainternet** [comment]
@parfilov 	


As you know the Popup feature is new and we are currently collecting feedback, so for now, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by SergeyCorpus** [comment]
I also often need Toggle Popup  after submit form in popup with another "thank you" popup which said that form was sent successful.
