### ISSUE TITLE
render same content in _content_template()

### ISSUE THREAD

**Issue by mattiasghodsian** [pojome/elementor#6719]
Im working on a few widgets but i cant really figure out how to render out PHP code in the _content_template() so the user can view the changes instead of moving to the frontend?

I would also like to know what template engine _content_template() has?

PHP example in render() i want to render in _content_template() 

    if( $settings['user'] != '' ){
        try {
    		echo $this->execShortcode($settings['user']);
    	} catch (Exception $e) {
    		
    	}
    }

**Comment by bainternet** [comment]
@mattiasghodsian 

`_content_template` runs in the editor only and is [Underscore template engine](https://underscorejs.org/#template) (JS) so PHP won't work here.
