### ISSUE TITLE
Regarding Featured Posts Widget

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#672]
I read that you guys are working on a (featured) posts widget. That is great news! 

Here is what the one by Genesis looks like:
![genesis-featured-posts](https://cloud.githubusercontent.com/assets/5323259/18958169/bf71c32c-862f-11e6-85ab-7f8ffbc9423b.jpg)

I am thinking you could actually just release a regular featured posts widget into the WordPress repository, and give some promotion to Elementor as the same time. + Have a featured post widget element in Elementor.

**Comment by whatsnewsisyphus** [comment]
There are many such widgets available in the repo, but if you could make it well integrated with custom post type support and autofilling custom taxonomies, that would be really nice

**Comment by arielk** [comment]
Merged to #262
