### ISSUE TITLE
Fonts – Showing in real-time

### ISSUE THREAD

**Issue by Olikub** [pojome/elementor#6720]
**Problem:**
When I open the fonts family now, than I see just the names of the fonts like here: https://prnt.sc/ke3hl1
The problem is, that I don't know many of them or can't imagine how they look like. 
→ Right now, I need to apply the fonts to see what they look like. And only then can I decide whether I want the font or not. This process is very time consuming. 

**Solution:** A real-time view of the fonts would fix this problem. Example as in Powerpoint: http://prntscr.com/m6w40d

**Comment by bainternet** [comment]
@Olikub 

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.


**Solution:** 
scroll a little

![image](https://user-images.githubusercontent.com/660572/51106221-c9b3b400-17f3-11e9-830f-6dba97e16997.png)
