### ISSUE TITLE
Dynamic content functions missing

### ISSUE THREAD

**Issue by alriksson** [pojome/elementor#6721]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm frustrating that Elementor PRO still does not have:
1. All widgets supporting dynamic content.
2. Dynamic colors (mainly background colors).

**Describe the solution you'd like**
Add function for dynamic content to all widgets
Add support for dynamic colors.

**Comment by shilo-ey** [comment]
Hi @alriksson,

1. If there's any specific dynamic feature you wish to add, please request it specifically. 
2. Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

We are thinking of implementing a new color picker control that will be more flexible.

Next time please open issue per request.

Thanks for the feedback.

**Comment by alriksson** [comment]
@shilo-ey 

1. I did specify all widgets. Why not add the functionality to use dynamic content which is the future to all widget elements. Right now it's too limited, e.g icon list does not have support for dynamic and many many more widget.

2. I clicked feature in GitHub so I should Have been a feature request? Can you move this to feature request then?


Ok, that would be good but just dynamic color for a background would make me happy to start with. I can use background but not color..?

**Comment by shilo-ey** [comment]
There are guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.

In addition, you need to ask for one in a thread with Prerequisites, Description and examples.

As for your questions:
1. Request specifically. we do not add support for all widgets and controls for a reason. If we will be able and decide to add the dynamic functionality for your request we will do so.
2. Feature requests are being added after our review and after we see a large demand for it. Currently, this feature is not supported.
