### ISSUE TITLE
Restore list in the template widget

### ISSUE THREAD

**Issue by lucafagherazzi** [pojome/elementor#6725]
In reference to issues #6655  I ask if it is possible to restore the list (sorry for my error (pop-up)) that appeared in the template widget.
Thank you.

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

as for the request, the change we made was a fix to an incorrect search mechanism, 
please refer to #6473

thanks.
