### ISSUE TITLE
Elementor uses domain name in CSS URLs

### ISSUE THREAD

**Issue by efc** [pojome/elementor#6727]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I build WordPress sites using Local by FlyWheel and noticed that many Elementor items do not display properly when the site is being accessed with FlyWheel's "Live Link" service.

Then I noticed the same issue after migrating a site with Elementor to a new domain name, even though I used `wp search-replace` to change all occurrences of the domain name.

I finally realized that Elementor includes the domain name of the host in URLs that are saved to the CSS files in the uploads folder. This is totally unnecessary and causes a lot of problems. Since those CSS files are being loaded by the WordPress plugin or theme, the correct default domain will be in force. These URLs in the CSS files should start with the initial "/" not with "http". In other words, they should only include the absolute path, not the scheme or authority portions of the URL.

As it currently works, Elementor can easily be in a state where it's CSS files are referring to a local server that does not exist for the remote user. This is because some systems (like Local) will rewrite URL's on the fly, but do not know to rewrite the URLs in the Elementor uploads directories. This problem would be very easy to resolve by just using the path portion of URLs in CSS files, and this would probably also reduce the necessity of syncing the CSS files with changed settings.

## Steps to reproduce

Add an image to the background of an Elementor element.

Look for any line in the resulting Elementor-generated CSS files with "background-image:url" and note that the domain name appears there. It should not.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

I noticed this while working with Elementor in Local by FlyWheel, but it is an issue in the core of Elementor, not related to the environment.

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: (Debian) v5.5.60
	PHP Version: 7.0.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: http://shf.local
	Home URL: http://shf.local
	WP Multisite: No
	Max Upload Size: 1,000 MB
	Memory limit: 40M
	Permalink Structure: /archives/%post_id%
	Language: en-US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: Neve
	Version: 1.0.27
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15

== Active Plugins ==
	BackWPup
		Version: 3.6.6
		Author: Inpsyde GmbH

	Change Table Prefix
		Version: 1.4
		Author: Manish Kumar Agarwal

	Elementor
		Version: 2.4.0
		Author: Elementor.com

	Orbit Fox Companion
		Version: 2.7.3
		Author: Themeisle

	Simple Custom CSS and JS
		Version: 3.22
		Author: SilkyPress.com

	Simple Lightbox
		Version: 2.7.0
		Author: Archetyped

	Simply Static
		Version: 2.1.0
		Author: Code of Conduct LLC

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg


== Must-Use Plugins ==
	Local by Flywheel Relative URL (for Live Links)
		Version: 1.0
		Author: Flywheel


== Log ==
	: 
Log: showing 1 of 12019-01-14 10:11:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.8',
  'to' => '2.4.0',
)]

PHP: showing 1 of 1PHP: 2019-01-14 11:20:47 [warning X 2][/app/public/wp-admin/includes/file.php::168] closedir() expects parameter 1 to be resource, boolean given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by shilo-ey** [comment]
Hi @efc, 

Elementor uses WordPress's native `wp_get_attachment_image_src ` function to get the image URL. 

As for your issue, use elementor "[Replace URL](https://docs.elementor.com/article/218-i-changed-the-url-of-my-website-and-elementor-does-not-work-anymore)" tool in your `wp-admin/admin.php?page=elementor-tools#tab-replace_url`


thanks.

**Comment by efc** [comment]
I understand Elementor may use `wp_get_attachment_image_src` to get the URL... I am simply asking that you remove the scheme and authority from that URL before writing it to the CSS file.

In my case I cannot use the Replace URL tool because the site is being used from two different URLs *at the same time*. Local provides a local and remote URL silmultaneously. Whichever URL the browser has is correct, but any one browser may not be able to reach both.

**Comment by efc** [comment]
For example, could Elementor please use `wp_make_link_relative` before writing a link out to CSS? This would not harm current functionality and would make the CSS files usable from multiple domains at the same time without the need of Replace URL.

**Comment by therealgilles** [comment]
I agree with @efc. Elementor should use relative urls.

**Comment by dinusuresh** [comment]
Facing the same issue on elementor pro. Would be great if elementor could use relative urls. The support says replace url is the alternate option for now, but I am hesitant to use it as it will replace all urls in the database as well, right ?

If this is a minor effort, kindly request this be pushed ahead priority and released asap. Thanks.
