### ISSUE TITLE
elementor server showing not connected

### ISSUE THREAD

**Issue by topdog1965** [pojome/elementor#673]
hello

i cannot view the UI header kit in the template section when you go to elementor on the right then system info it shows Elementor Library: 	not connected (HTTP Error (403)) i have reinstalled elementor and pressed the sync button but still no luck i have contacted my host to see if they are blocking elementor  but they need the ip address.  please help thankyou

regards kev

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
