### ISSUE TITLE
A way to override a method on elementor/assets/js/editor.js

### ISSUE THREAD

**Issue by emascarinas** [pojome/elementor#6730]
Apologies but I'm a newbie on JS. Is there a way to override the onRender function below? I trying to override the line of code:

`self.$el.attr('data-element_type', editModel.get('widgetType') + '.' + skinType).removeClass('elementor-widget-empty').children('.elementor-widget-empty-icon').remove();`

To

`self.$el.attr('data-element_type', 'someclass.' + skinType).removeClass('elementor-widget-empty').children('.elementor-widget-empty-icon').remove();`

I'm using the hello-world boilerplate on creating custom widgets. How will I achieve this under hello-world.js?

Full section of the code (editor.js):

```
	onRender: function onRender() {
		var self = this;

		BaseElementView.prototype.onRender.apply(self, arguments);

		var editModel = self.getEditModel(),
		    skinType = editModel.getSetting('_skin') || 'default';
		    alert('skye');

		self.$el.attr('data-element_type', editModel.get('widgetType') + '.' + skinType).removeClass('elementor-widget-empty').children('.elementor-widget-empty-icon').remove();

		// TODO: Find better way to detect if all images are loaded
		self.$el.imagesLoaded().always(function () {
			setTimeout(function () {
				if (1 > self.$el.height()) {
					self.handleEmptyWidget();
				}
			}, 200);
			// Is element empty?
		});
	},
```

**Comment by shilo-ey** [comment]
@emascarinas 	

there is no API in place to override Elementor native JS but you can always do it on the client side once elementor has loaded.
