### ISSUE TITLE
Listener event by click to Repeater title?

### ISSUE THREAD

**Issue by notrealdev** [pojome/elementor#6731]
Hi, how to Listener event by click to Repeater Title?
I have the same custom widget, when click to Repeater Title ( control in Panel ) i want switch to corresponding slide ( in preview ).
Can you give me the ducument for this issue?
See the gif image.
https://i.imgur.com/DeVWuty.gif

**Comment by bainternet** [comment]
@notrealdev 

You need to extend `elementorFrontend.Module` and implement its `onEditSettingsChange` which receives a property and if the proprty is `activeItemIndex`, ex:


```JS
elementorFrontend.Module.extend( {
	onEditSettingsChange: function( propertyName ) {
		if ( 'activeItemIndex' === propertyName ) {
			// do your thing;
		}
	},
} );
```

**Comment by emascarinas** [comment]
hi @bainternet 

Should we place it under `$( window ).on( 'elementor/frontend/init', function() {` as shown below?

```
	$( window ).on( 'elementor/frontend/init', function() {

	 	elementorFrontend.Module.extend( {
	 		onEditSettingsChange: function( propertyName ) {

	 			if ( 'activeItemIndex' === propertyName ) {
	 				// do your thing;
	 			}
	 		},
	 	} );
```

I tried this and its seems its not triggering the event.

Thanks.

**Comment by notrealdev** [comment]
Hi @bainternet @emascarinas
How i can implement its, i tried some hooks but its not working.
Sorry for the late reply

**Comment by notrealdev** [comment]
Hi, any suggestion?

**Comment by EnjeruTantei** [comment]
@bainternet
