### ISSUE TITLE
SubMenu In 2.4B3 Alignment issues and submenu visibility with a pro header template.

### ISSUE THREAD

**Issue by Worldwebscapes** [pojome/elementor#6738]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Worldwebscapes** [comment]
I am seeing a issue with the alignment on submenu items in a E header template in the new Beta release. See attached Image.  This seems to be in the CSS for the following.  .elementor-nav-menu .sub-arrow I can make my menu align by applying the following CSS
`.elementor-nav-menu .sub-arrow {
    padding: 0 0 0 0;
    margin-left: 5px;
}`
However, I cannot see my dropdown items at all. This may be a Z index issue or another problem.  If I delete my header template and only use my theme headers (Layers Theme) My submenus align and dropdown as expected.

This image shows my alignments issue but does not address that you cannot access submenu links.
![elementor-submenu-fix](https://user-images.githubusercontent.com/7572038/51182109-156d6880-189b-11e9-967a-8080018eb9d2.jpg)

**Comment by Worldwebscapes** [comment]
This is a screen shot with same environment and the native lavers header. Menu works as designed.
![image](https://user-images.githubusercontent.com/7572038/51182703-02f42e80-189d-11e9-9454-6be4e4cee6bb.png)

**Comment by Worldwebscapes** [comment]
Same environment with only the Layers Theme header enabled.
![bug2](https://user-images.githubusercontent.com/7572038/51182821-61211180-189d-11e9-9c9b-131ce6a04465.jpg)

**Comment by shilo-ey** [comment]
Thanks for reporting, 
This issue is already reported on beta #6663 thread and will be fixed in the next release.

Thanks
