### ISSUE TITLE
Hello theme Compatibility

### ISSUE THREAD

**Issue by Mulli** [pojome/elementor#6739]
I would like to use Hello theme with Woocommerce, WPML and ACF plugins.
Is the theme "ready" / "compatible" with the above plugins or similar?

I consider it a bug that the documentation does not mention this information.

Thanks!

**Comment by shilo-ey** [comment]
Hi @Mulli 

As far as we know "Hello theme" is compatible with those plugins.

This is not a bug in any documentation.

thanks.
