### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by jimn10** [pojome/elementor#6744]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by jimn10** [comment]
I am getting a couple of errors on https://lakeforkbassguides.com when I try to save changes from the Elementor/Settings screen. I am hosted on Siteground with basic settings. I an using a child theme. I have been building this site out for a while and just noticed this error when I tried to change the screen width. I get the following 2 Warnings:

> **Warning: time() expects exactly 0 parameters, 1 given in /home/lakefork/public_html/wp-includes/class-wp-hook.php on line 288**
> 
> **Warning: Cannot modify header information - headers already sent by (output started at /home/lakefork/public_html/wp-includes/class-wp-hook.php:288) in /home/lakefork/public_html/wp-includes/pluggable.php on line 1223**


I can give you an admin login if you need it.

Thanks,

Jim

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
