### ISSUE TITLE
Elementor Button disappeared after recent elementor update, as did front page widgets

### ISSUE THREAD

**Issue by mbernstein04** [pojome/elementor#6745]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

After Elementor 2.4.1 auto-updated last night, the front page of my site, which includes an elementor button broke. 

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | nginx |  
MySQL version: | MariaDB Server v5.6.36-83.0 |  
PHP Version: | 7.0.33 |  
PHP Max Input Vars: | 6144 |  
PHP Max Post Size: | 2047M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | There are some writing permissions issues with the following directories/files: 		 - WordPress root directory |  
Elementor Library: | Connected |  

</details>

**Comment by mbernstein04** [comment]
My website is bernsteinlipsett.com

**Comment by bainternet** [comment]
@mbernstein04 	


I see you figured it out.
