### ISSUE TITLE
How to display Background Video on a custom widget?

### ISSUE THREAD

**Issue by notrealdev** [pojome/elementor#6754]
Hi, i have a custom widget using [Background Video](https://developers.elementor.com/elementor-controls/background-control/) group control.
How i can display video on my preview mode/frontend?
I am using below code and it works only frontend.

```php
<div class="elementor-element elementor-section"
	data-element_type="section"
	data-settings='{"background_background":"video","background_video_link":"<?php echo esc_attr( $settings['background_video_link'] ); ?>"}'>
	<?php $video_properties = Embed::get_video_properties( $settings['background_video_link'] ); ?>
	<div class="elementor-background-video-container elementor-hidden-phone">
		<?php if ( $video_properties ) { ?>
			<div class="elementor-background-video-embed"></div>
		<?php } else { ?>
			<video class="elementor-background-video-hosted elementor-html5-video" autoplay loop muted></video>
		<?php } ?>
	</div>
</div>
```
The code i'm using is correct or there is a document somewhere that I don't see?

**Comment by shilo-ey** [comment]
Hi @notrealdev 

Currently, background video is supported only at the section level, and cannot be used at widget level.

Thanks
