### ISSUE TITLE
UX problem in section box shadow control

### ISSUE THREAD

**Issue by obiPlabon** [pojome/elementor#6758]
## Problem:
I experienced section box shadow control is in a confusing place. As a new user, I was expecting shadow control in a separate panel like the **border**, **shape divider** and other panels. It took me a while to figure out that the shadow control is inside the **Border** panel.

![shadow-control-ux](https://user-images.githubusercontent.com/10244644/51252468-18b14300-19c6-11e9-9d87-fe6c42050f42.jpg)

## Solution:
I think the solution is pretty simple. Just rename the _Border_ panel to **Border & Shadow**.

Thanks for the amazing work! 👍

**Comment by bainternet** [comment]
@obiPlabon 

Its hard to tell which widget you are talking about.

anyway, not a real issue.

thanks for the feedback.

**Comment by obiPlabon** [comment]
@bainternet Thanks for your reply.

I mentioned it, seems you didn't notice because it wasn't highlighted. Check the first line "I experienced **section** box shadow control". Now I know almost all widgets have the same issue.

Maybe it's not an issue to you as you're familiar with Elementor so well. But for new users, it's definitely a UX issue.

Thanks
