### ISSUE TITLE
Form field validation

### ISSUE THREAD

**Issue by Federicro** [pojome/elementor#6760]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A way to set validation regular expressions in form fields, directly within Elementor, for non coders.

**Describe the solution you'd like**
Being able to validate a field content in Elementor PRO forms

**Describe alternatives you've considered**
(1) implement the feature in the form plugin, directly in each field's tab in the advanced options tab.

(2) in the meanwhile helping me and others giving more detailed instruction on how to use the example described at https://developers.elementor.com/forms-api/#Form_Field_Validation_Action:
   - where do I put the code? (child theme, in functions php?)
   - my regular expression would be 
                    if(!preg_match('/^[a-z]{6}[0-9]{2}[a-z][0-9]{2}[a-z][0-9]{3}[a-z]$/i', trim($s))) {
                     echo 'Codice fiscale non valido!';
                      }
   could someone help me with the elementor_pro/forms/validation code? This would be really appreciated. Thank you.

**Comment by bainternet** [comment]
@Federicro 

Yes, in your child theme's functions.php would be just fine.

just like the documentation you linked:

```PHP
// Validate the Tel field is in XXX-XXX-XXXX format.
add_action( 'elementor_pro/forms/validation/tel', function( $field, $record, $ajax_handler ) {

    // Match this format XXX-XXX-XXXX, 123-456-7890

    if ( preg_match( '/[0-9]{3}-[0-9]{3}-[0-9]{4}/', $field['value'] ) !== 1 ) {
        $ajax_handler->add_error( $field['id'], 'Please make sure the phone number is in XXX-XXX-XXXX format, eg: 123-456-7890' );
    }
}, 10, 3 );
```
