### ISSUE TITLE
[feature request] Duplicate templates w/out exporting

### ISSUE THREAD

**Issue by bcarney66** [pojome/elementor#6765]
Feature request: I'd like the ability to duplicate Templates within Elementor and not have to export and then re-import them.  When I re-import on the same site:

1) It re-imports all the images, causing duplicates within my media library;
2) the imported theme has the same name as the original, causing confusion.

**Comment by shilo-ey** [comment]
Hi @bcarney66 

You can re-use template you created by adding it to a new template.

Simply create a new template, from the library go to the `My Templates` tab and insert your designated template.
![image](https://user-images.githubusercontent.com/45009641/51303258-8056a500-1a3d-11e9-834b-08b0d60be2cd.png)


Afterward you can edit it as much as you want.

Thanks
