### ISSUE TITLE
Comments for design

### ISSUE THREAD

**Issue by hstanleycrow** [pojome/elementor#6766]
## Prerequisites

- [ *] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [* ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
On complex designs this will to help when the design is used for more than one person.

**Describe the solution you'd like**
Comments lines like Microsoft Excel. I 

**Describe alternatives you've considered**
Taking notes on notepad

**Additional context**
select an element, right click, create comment and this open a text box where i can add a comment for design, for example: "this spacer is used only for desktop, if you remove it, this will to move the picture".

**Comment by shilo-ey** [comment]
Hi @hstanleycrow 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
