### ISSUE TITLE
open new tab... 

### ISSUE THREAD

**Issue by keramch** [pojome/elementor#6767]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

This is a minor thing, but i find it frustrating, so I'll share! 
I don't know if it's just me, but on VIEW PAGE  i can't right click to open in new tab, and it opens in the same tab which, if i'm wanting to look at the CURRENT page for reference while i'm editing, it's just extra steps to manually open a new page and navigate to it. 
maybe i'm just blind an missing another way??

**Describe the solution you'd like**

If VIEW PAGE could - by default - open in a new tab/window from the editing screen... that would be GREAT.
even just being able to right click and get the usual contexual link menu (eg. open in new tab, open in new window...) would be great, but i get a contextual navigation menu (eg. back, reload, save as...) would be a significant workflow improvement from my perspective. 

**Describe alternatives you've considered**

currently i open a preview and then change the url to eliminate the preview string... or i just open a new window and retype the url... 

**Additional context**

**Comment by shilo-ey** [comment]
@keramch 
The option to View Page is to move from this page to another (such as exit to dashboard etc...)

Although, we will consider adding the ability to right click on the button.

Thanks for your feedback.

**Comment by shilo-ey** [comment]
Hi @keramch 

This tweak has been added to Elementor 2.4.6.

Feel free to update!

thanks.

**Comment by keramch** [comment]
sweet! that's amazing!

🤓👍

**Comment by steffanhalv** [comment]
@shilo-ey Doesnt work for me, using Elementor 2.4.6 & Elementor PRO 2.4.4.

CMD + Click View Page or dashboard only redirects the page & doesn't open in new Tab
