### ISSUE TITLE
Adjust header template on page

### ISSUE THREAD

**Issue by Wereldsmuller** [pojome/elementor#6769]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hi there!

Pro user here, have an idea which would help us designers greatly :-)

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when I can't adjust the text in the header template on a page basis. Having dynamic text fields is great, but not being able to adjust them on a page is suffering. This disables the use the header for me, as I have to resort to using section templates, which are far from optimal!

**Describe the solution you'd like**
An amazing feature would be to have a header template where you can adjust (text/certain) fields on single pages. Currently you cant 'touch' the header template outside of the template.

**Describe alternatives you've considered**
Dynamic text is a thing, but I can't insert values for each page. I'd consider to use the page title tag, but that isn't sufficient.

Many thanks.

**Comment by shilo-ey** [comment]
I merged this issue with  #4985, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by bentalgad** [comment]
That would be so much better. by the way "Brizy" does that. and the "jettabs" plugin has something and between - it adds a button to edit the template you used inside one of the tabs and opens another Elementor editor in iframe, but of course it's really not that good idea, the best thing would be just to be able to edit on any place without having to open another editor.
