### ISSUE TITLE
Text styling?

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#677]
This example is a text widget with background color inside a column that has a background image. With the text editor selected, I attempt to change the text color to white. However, nothing will apply. Is this a bug or is there a conflict here?

<img width="732" alt="screen shot 2016-09-29 at 1 46 48 pm" src="https://cloud.githubusercontent.com/assets/974442/18971807/53428184-864b-11e6-8c10-6615445c5a2f.png">

Feature request: Also, it would be excellent if there was a widget that made it easy to create a text overlay with background image. Currently, it's a bit confusing and not easily duplicated unless it spans a whole section.

**Comment by WPDevHQ** [comment]
Looks like a conflict as I'm able to style the text as normal.

What theme are you using?

**Comment by mizejewski** [comment]
I'm using a Genesis child theme called [Dynamik](https://cobaltapps.com/downloads/dynamik-website-builder/). I am able to change text color under the content tab, but *not* the Style tab. The alignment control works fine though.

**Comment by WPDevHQ** [comment]
Just tried with Genesis sample child theme and again no issues so that rules out Genesis as being the source of the conflict.

Don't have access to Dynamic so can't check on that. At this point I'll probably let the Elementor team take a closer look to see if they can resolve it for you :)

**Comment by mizejewski** [comment]
Thanks WPDevHQ!

**Comment by crackdepirate** [comment]
same here, get stuck with style->color for text element.
selection is blue, text is black. 
tried hard-refresh, flush cache.

![image](https://cloud.githubusercontent.com/assets/10081049/19293301/e4edf060-8ff0-11e6-871e-e2c9ba3c2d58.png)

my theme is 
![image](https://cloud.githubusercontent.com/assets/10081049/19293328/1798c472-8ff1-11e6-9b7f-e6fe6b1949a7.png)

**Comment by arielk** [comment]
@mizejewski @crackdepirate can you share with us a link to the page with this conflict?

**Comment by mizejewski** [comment]
@arielk you can see my example at this test page https://beta.library.ucsf.edu/test-bed-page-elementor/. The site is still private, so you'll need to enter flywheel and festive-giraffe to view. Note that the text color under the Style tab works for the heading widget, but not the text widget.

**Comment by crackdepirate** [comment]
@arielk yes, try http://jeansebastienstamour.ca/home/
do you need wp login ?

**Comment by WPDevHQ** [comment]
@mizejewski - I'm seeing the following css code which seems to be the overriding/dominant output
`.entry-content p, .entry-content ul li, .entry-content ol li, .entry-pagination {
    color: #333333;
    font-family: 'Roboto',sans-serif;
    font-size: 18px;
}`

Source: dynamic.min.css file

**Comment by WPDevHQ** [comment]
@crackdepirate  - The element with the title "Expériences" has an opacity of 0 (see code below). Is that something you set or is that how its been output(generated by Elementor)?

.elementor-element.elementor-element-soduqhg > .elementor-element-populated {
    color: rgba(140,221,46,0);
    text-align: right;
}

**Comment by crackdepirate** [comment]
@WPDevHQ you can see the bug here: http://youtu.be/NuMRJQRbEUE?hd=1

**Comment by arielk** [comment]
@mizejewski  Page is not available, I need a username and password

@crackdepirate If you replace your existing widget to the new widget, it works out?

**Comment by crackdepirate** [comment]
@arielk no, I deleted the heading element. create a new one, and it doesn't work either. 
I can provide you a user/password for my website. just let me know how can I reach you in private. 
thx

**Comment by mizejewski** [comment]
@arielk as I noted in above comment, the site is still private, so you'll need to enter credentials flywheel and festive-giraffe to view it.

**Comment by arielk** [comment]
It seems that you are setting the text color using the editor, you will see the source code: http://i.imgur.com/y5jOcxh.png

Please click on the edit button and change the mode of editor to "Text" and remove all the "span" with the custom color

**Comment by crackdepirate** [comment]
hello guyz, have you any news about that issue ?

**Comment by mizejewski** [comment]
@arielk hmmm...not sure how those spans got in there, but I just removed them:
```<h3>I am text block</h3>
Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.```

Next, I went back to Styles to set the color to #ffffff, but it still doesn't affect all text. Shouldn't it apply to everything in the text editor? Otherwise maybe a separate control for titles/headings like some other widgets have?

![style-tab](https://cloud.githubusercontent.com/assets/974442/19697511/7c56bf68-9aa0-11e6-8e1a-74962678400b.png)

**Comment by arielk** [comment]
It looks like the color of H3 comes from the CSS style of the theme, so you need to change it by the custom CSS: http://i.imgur.com/rDDnOVk.png

**Comment by WPDevHQ** [comment]
@mizejewski - The problem is the dynamik-min.css which is overriding Elementor's set color - see the screencast below for the source of the issue (sorry no sound)

https://app.blisk.io/screenRecords/shared/776e9858-3e8f-4a76-b69e-ff72eb94c83a

**Comment by mizejewski** [comment]
Yes the theme sets all headings to be #333333. However, I thought changing text color in Elementor would be more specific and therefore override the usual style? Is that not the case?

**Comment by arielk** [comment]
We are trying to create full compatibility with any themes, however we do not want to override various settings, so I do not see a way to fix it. The best way is by editing the CSS of the theme.

**Comment by mizejewski** [comment]
@arielk  I don't mean that Elementor should override styles in non-standard way. But it seems logical that styles applied at the element/widget level would be more specific in the cascade than styles inherited from he theme.  For example, all H2s may be 24px as set in the theme stylesheet, but in a given instance, the user may change that in Elementor by setting typography to custom and changing the font and size. Is that not how it is supposed to work?

**Comment by arielk** [comment]
As it appears, it happens because your title (H3) is inside the Text Editor widget. If you are using by the Heading widget It still doesn't work?

**Comment by RobertShippey** [comment]
I agree with @mizejewski - elementor should be styling with more specific selectors so that it 'overrides' the theme styles. 
"The best way is by editing the CSS of the theme" is basically admitting that any styling of html elements via elementor is useless :roll_eyes:

**Comment by carasmo** [comment]
If the theme has very specific css, what is a page builder to do? Many Genesis themes have styling in the header, footer, and section that may be different colors and font defaults. Rather than creating sectional CSS, like:

```
.site-header { background: #000; color: #fff;}
.site-header a { color: inherit; }

.site-footer, .footer-widgets { .... }
```
There's numerous filters `genesis_attr_x` to change classes and sectionalize a theme so you don't have to use specificity in the .entry-content area. However, this is not done unfortunately.

Instead they opted, in many cases, if the site has a dark header and dark footer, to use global styles and specific styles to the entry content to make that the background and foreground different colors. That is a pain with specific css for .entry-content. To get around this. On page builder pages, you can make a specific template for that use and remove the entry-content class. Works great! 

```

<?php

defined( 'ABSPATH' ) || exit;

/**
 *
 * Template Name: Page Builder Page
 * Description: Template for Page Builder
 *
 */


/** 
 *
 * Remove .entry-content class replace with .builder-content
 * @since 1.0.0
 *
 */
function yourprefix_change_entry_content_class( $attributes ) {
 
 	// removes all classes except
	$attributes['class'] = 'builder-content';
 
 	return $attributes;
 
}
add_filter( 'genesis_attr_entry-content' , 'yourprefix_change_entry_content_class' );


/** 
 *
 * Add 'themeslug-page-builder-page' body class
 * @since 1.0.0
 *
 */
function yourprefix_page_builder_body_class( $classes ) {
 
    $classes[] = 'themeslug-page-builder-page';
     
    return $classes;
     
}
add_filter( 'body_class' , 'yourprefix_page_builder_body_class' );



//* run
genesis(); 

```

**Comment by carlosnpz** [comment]
Copying and pasting texts from another places also may cause this issue.

**Comment by Phillip357** [comment]
I realize this is an old thread, but I'm having a hard time finding any other sources about this issue. As I don't see a non-techie solution, I'll just explain the conditions under which I experience the text editor color selector in the style section not functioning correctly.

When I just drag the text editor widget to my new page and directly go to the styles section, I can change the sample text color from the styles color selector without a problem and without the need to select / highlight any text. The moment I click in the text edit area on either the sidebar edit area or on the text edit area on my page, the styles color selector no longer works (not even when selecting text). No text has been added or changed at this point. I merely selected the text edit area. The font color selector on the text editor itself works (only on text selected / highlighted though) , but it changes the color in the text editor interface, which is difficult to work with if you need white as a color, given that you cannot change the color of the white background. If anybody knows how to fix this, or perhaps know of a different text editor plugin which works with elementor (with similar functionality), I would like to hear from you. Keep in mind that I am not a code guru. 

Details of my setup:
Theme: OceanWP 1.6.4
Wordpress: 5.1.1
Elementor: 2.5.13
Server: Apache
MySql: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
PHP: 7.0.33
OS: Ubuntu Linux and Windows 10 (Replicates on both systems)
User agent: Mozilla/5.0 (Not sure the windows version. Replicates there the same)

Ps. I can get the job done using other methods, but that is not the point...

**Comment by emre-edu-tech** [comment]
I can confirm that that's 90% theme issue. I have been using Elementor for a long time and I generally use Elementor with themes like Astra or OceanWP but these themes always work with Elementor quite well. Now there is a project in my hand that I need to use a theme from some company and I need to use Elementor with it. The things that you folks are mentioning here, happened to me and the only solution is to tweak the CSS from outside. Sorry!
