### ISSUE TITLE
No Way to Exit to Dasboard when Editor Has Set "Access to edit content only"

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#6771]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Today I was instructing a client on how to edit with Elementor. Editor has the access to edit content only. 

![obrazek](https://user-images.githubusercontent.com/5634870/51330110-28d52b00-1a77-11e9-8ef0-4748744ac572.png)

To my big surprise I realized, trere's no way how to exit Elementor to dashboard:

![obrazek](https://user-images.githubusercontent.com/5634870/51329911-ba906880-1a76-11e9-92ae-11d3ba15a787.png)

The only way how to finish editing is to close the window. I have to say, that it didn't make a big impression on my client... :-(

Is it intentional (hope it isn't) or a bug?

## Steps to reproduce

Just try to exit Elementor when you are Editor with limited access.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@black-eye 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* System info.


We can't replicate,

![image](https://user-images.githubusercontent.com/660572/51437193-8ea5fa80-1ca3-11e9-8d37-41755f6c4da3.png)

**Comment by black-eye** [comment]
I found out that this issue is caused by Central Color Palette (https://wordpress.org/plugins/kt-tinymce-color-grid/).

**Comment by kungtiger** [comment]
Thanks for letting me know. I'm on it.

**Comment by kungtiger** [comment]
Version 1.13.2 of Central Color Palette will remove this compatibility issue.
