### ISSUE TITLE
Off-canvas Menu and Stretch Section enabled

### ISSUE THREAD

**Issue by JoelEadeDesign** [pojome/elementor#678]
Not sure if this is a specific issue with my theme (JointsWP which is built on Foundation 6) but sections with Stretch Section enabled breaks out of it's wrapper when using the Foundation 6 off-canvas menu.

You can see it in action at https://www.happihome.com.au and in this video demo: https://lookback.io/watch/wk3LPtcQgZMHpEAzE

It occurs on mobile devices (and the XCode device simulator) as soon as you scroll. When testing in Chrome it takes about 10 seconds of scrolling up and down to cause it to occur. 

Cheers

**Comment by JoelEadeDesign** [comment]
As I need to go live with https://www.happihome.com.au/ I've changed the menu from being off-canvas to title bar, which just expands down the page. I prefer an off-canvas menu so I'd still like to resolve this issue if possible.

**Comment by WPDevHQ** [comment]
I don't see the options in the theme to set the menu to off canvas - is this the theme: http://jointswp.com/ ?

On your site you are using a modified version of the theme?

**Comment by JoelEadeDesign** [comment]
Hi Zulfikar. The off-canvas menu is one of four menu options with JointsWP/Foundation 6. I've applied CSS styling to the theme but nothing has changed in terms of functionality.

Let me set up a demo with just the unedited JointsWP theme and Elementor for you to test with. I'll post a link to it over the weekend.

Cheers!

**Comment by arielk** [comment]
Please find the `.class` container of the page, try this one: `.off-canvas-wrapper-inner`

And paste it under Elementor > Settings > Stretched Section Fit To > Save 

Let me know if it works out for you

**Comment by JoelEadeDesign** [comment]
Spot on! Thanks @arielk :) 

As an aside, I did a presentation about Elementor last night at a WordPress meetup in Melbourne. It was well received. Keep up the great work. Looking forward to the pro version.
