### ISSUE TITLE
Translate Pro Form Module Date Picker AND Time Picker

### ISSUE THREAD

**Issue by Cormick** [pojome/elementor#6781]
As I read in #3605, there is a way to translate the Pro Form Module Date Picker. Also, #3605 shows a way to change the date format.
But if I use the solution suggested there

```JS
setTimeout( function(){
    $('.flatpickr-input').each(function(){ flatpickr( $(this)[0] ).set('dateFormat', 'd/m/Y');});
}, 1000 );
```
the time picker also shows the date and not the time.

**Comment by bainternet** [comment]
@Cormick 	

With this selector, ( `$('.flatpickr-input')`) you are targetting any instance of flatpickr which means time and date. If you want to target just date field try a more specific selector, ex:

```JS
setTimeout( function(){
    $('.elementor-field-type-date input').each(function(){ flatpickr( $(this)[0] ).set('dateFormat', 'd/m/Y');});
}, 1000 );
```

**Comment by pacotole** [comment]
Hi!
I've write a little plugin [elementor-datepicker-localization](https://github.com/creame/elementor-datepicker-localization) to load datepicker in the current site language.

**Comment by dasigna** [comment]
... stumbling in, after facing that issue.
(btw. sad to see theres no native solution :( )

@pacotole - tried and works, thx - but with limitations:
- picked date in field still shows english format
- time picker still shows am/pm, no 24h-option.

this little plugin makes one step forward, but doesnt complete it.
why doesnt elementor takes care of such things???

completely dazzling me.

**Comment by pacotole** [comment]
Validation errors have been resolved and added a filter to show 24h format in time picker  😉

**Comment by scteam-de** [comment]
@ pacotole
The time remains at 00:00 - 12:00 am / pm.
What would I have to change to make the 24 hour display work?

Saludos

**Comment by pacotole** [comment]
> @ pacotole
> The time remains at 00:00 - 12:00 am / pm.
> What would I have to change to make the 24 hour display work?
> 
> Saludos

You need to add this filter in your theme functions.php:

```
// Use 24h format on time input
add_filter( 'elementor/datepicker/24h', '__return_true' );
```

**Comment by scteam-de** [comment]
it works! 
Muschas gracias!

**Comment by reachdigitalaus** [comment]
Hi @pacotole c

I would also like to have the date sent to my email as dd/mm/yy , will your solution also do this? Im using a multispet form and also chose the Native HTML5 date picker.

Thanks in advance.

**Comment by pacotole** [comment]
Hi @reachdigitalaus.

Yes, date field with datepicker preserve date format... and, now with v1.3 native date input also! 🎉

Thanks for the suggestion.

**Comment by ALVAROWEB13** [comment]
Hi @pacotole  

I have a question, if I have a date field, how can I make it take the current day and block the previous ones, can you give me some help?
