### ISSUE TITLE
Looking for Mega Menu Like Feature 

### ISSUE THREAD

**Issue by NaveenKolhe** [pojome/elementor#6787]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I actually want to display sub-menus in columns just like Flipkart, Amazon and Udemy but unable to find the style option for doing so in the existing nav menu widget.
![2019-01-19_10h55_09](https://user-images.githubusercontent.com/16379282/51422680-cc8a1c80-1bd8-11e9-83e0-f27a033df8a6.png)
![2019-01-19_10h55_36](https://user-images.githubusercontent.com/16379282/51422681-ce53e000-1bd8-11e9-8541-4ed88f101ed4.png)

**Describe the solution you'd like**
Just suggest me if the options could be added in the Nav Menu Widget or suggest me good plugin to achieve this on my site.

**Describe alternatives you've considered**
It would be great if you can suggest me a Menu plugin for now, which can work with Elementor.

**Additional context**

**Comment by bainternet** [comment]
I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
