### ISSUE TITLE
How can i change the search template query

### ISSUE THREAD

**Issue by Webtica** [pojome/elementor#6789]
Hi There,

I asked official elementor support and they redirected me here:

If I make a search template it show all posts of all authors and also pages.
Is there a way to show only posts of the current logged in author in search results?
I am making some sort of dashboard. I made this code that works on seperate pages but not on search results:

add_filter( 'uael_posts_query_args', function( $query, $settings ) {

$current_user = get_current_user_id();
$query['author'] = $current_user;
return $query;

}, 10, 2 );

Thanks
Dieter

**Comment by bainternet** [comment]
@Webtica 	

You can use the native WordPress filters for that, ex:

```PHP
add_action( 'pre_get_posts', function ( $query ) {
	// Only modify the search query when the user is logged in
	if ( ! $query->is_main_query() || ! $query->is_search() || ! is_user_logged_in() ) {
		return;
	}

	$query->set( 'author', get_current_user_id() );
} );
```
