### ISSUE TITLE
Changing the background color of the Elementor text editor widget.

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#679]
Hey

I am using white text on a blue background. Using the Elementor text editor widget makes the white text invisible because of the white background.

In standard WP one can add the `add_editor_style('editor-style.css');` in the functions file and then adjust the background CSS color of the editor to another color. Elementor does not have this option.

Add a way for the user to change the background color of the elementor text editor widget.
The easiest way would be to share the CSS needed to change the background color.

Thanks.

**Comment by paaljoachim** [comment]
Btw
Here is an example of using a larger heading and using a grey/white color:

![screen shot 2017-07-26 at 10 35 09](https://user-images.githubusercontent.com/5323259/28670008-19eecaf4-72d7-11e7-9111-b6bc1091e308.png)

Two things to notice:
1. Having a background when using grey or white does not work well with text. Having an option perhaps below the text editor to change the text editor background will help.

2. Notice that using larger headings that it takes up most of the space inside the editor.
Should there be an option to not show styling inside the text editor? So that the preview shows the color and size of the text?

**Comment by ramiy** [comment]
With [inline editing](https://elementor.com/inline-editing/) add in Elementor 1.8 you can edit the text directly on-screen.

Besides, when editing text using "Text Editor" you should not change the text color in the "Content" tab, you should do it in the "Style" tab. It has performance benefits. The style is saved in the CSS file instead of inline style.

**Comment by bainternet** [comment]
@ramiy is correct, Inline-editing solves this.
