### ISSUE TITLE
Saved Templates Menu One Slash in URL Causes Domain Error http:/ 

### ISSUE THREAD

**Issue by Vince2225** [pojome/elementor#6790]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Saved Templates and Templates link in admin menu links to http:/domain.com instead of http://domain.com. Single slash causes browser to interpret link as http://domain.com/domain.com causing error when clicked as the page doesn't exist.

## Steps to reproduce
Occurred when updated to 2.4.0 and 2.4.1.
Also occurs on staging site with all other plugins disabled.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.41
	PHP Version: 7.0.33
	PHP Max Input Vars: 2000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	Site URL: 
	Home URL: 
	WP Multisite: Yes
	Max Upload Size: 6 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-NZ
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.1.3
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: 
	WP Profile lang: en_NZ
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Network Plugins ==
Elementor
Version: 2.4.1
Author: Elementor.com

Elementor Pro
Version: 2.3.1
Author: Elementor.com

== Must-Use Plugins ==
	Disable Change Password Notification
		Version: 
		Author: 


== Log ==
```
Log: showing 1 of 12019-01-19 12:22:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.8',
  'to' => '2.4.1',
)]

```
</details>

**Comment by bainternet** [comment]
@Vince2225 

We can't replicate, nor do we set the HREF of the link manually, its done via WordPress API.

make sure your WordPress Address (URL) is set correctly in admin>> settings.
