### ISSUE TITLE
Menu in 2.4

### ISSUE THREAD

**Issue by Peak14Media** [pojome/elementor#6792]
Updated to Elementor Beta 2.4 and my main menu that has subpages have all moved down as if their is padding/margin top.
![menu](https://user-images.githubusercontent.com/46849714/51431024-8e90f680-1be0-11e9-9f04-26fc44c688d1.jpg)

**Comment by Peak14Media** [comment]
Looking at it some more before I updated to beta 2.4 The menu was aligned center with the far right button. Looks like the main menu that has the drop down stayed in place, but the other menu links with no drop down moved up.

**Comment by bainternet** [comment]
@Peak14Media 	

already reported in Beta thread.

thanks.
