### ISSUE TITLE
Dimension control - min/max argument

### ISSUE THREAD

**Issue by ArekZw** [pojome/elementor#6793]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
- Allows prevents accidental descent below 0 when the property (eg padding) does not support negative values. 
- Limit the choice to rational sizes by preventing accidental clicks that can cause the item to disappear from the screen (e.g. user want set left: 100%, when element position is absolute. User accidentally presses one zero too much. The element ceases to be visible and the user is confused.

**Describe the solution you'd like**
add min/max value argument

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
We see the value in the particular enhancement being suggested but have decided for now not to prioritize it. If you, however, decide to write a patch for it, we'll gladly include it after some code review.
