### ISSUE TITLE
Popup Click Works Only One Time - Have to Reload the Page Again

### ISSUE THREAD

**Issue by Peak14Media** [pojome/elementor#6798]
I've noticed with the Popup 2.4 set on click that it will work only one time, but once you click it, it won't work again until the page has been reloaded. This is a problem as a customer may click once close it and come back and click again.

**Comment by bainternet** [comment]
@Peak14Media 	


This is the correct behavior, 

Also, please use the #6663 for beta related feedback.

thanks.

**Comment by vgstef** [comment]
I'm also facing the same problem. I have a button that opens a popup to show specific details. But the button only works once, which is very problematic. 

@bainternet Why do you say it's the correct behavior? For an automatic popup, I understand, but for a link/button, it needs to open every time a visitor click on it! So is there a workaround/fix to make it always popup when we click a button?

**Comment by Luxamman** [comment]
Would also like to make them work more than just one time, because this behavior is disqualifying the popups for a lot of scenarios... dont see why this should be the "the correct behavior"

**Comment by garciacrew** [comment]
I have two buttons on a single page.  They trigger separate popups.  The first on the screen only works the first time I click the button, while the second one will work as many times as I click the button; no matter how I close it.  They have the same settings, just different content.  Both are email sign-up forms, but for different purposes.  Am I doing something wrong or is this correct behavior for the popups?  I even tried adding a "click" trigger at 1x and 50x.  Nothing changed either way.

**Comment by sequoi** [comment]
Well, everything is working correctly. I had the same issue, found this thread but played a bit and found the solution myself.

For a pop-up to open multiple times on a single page with the same click (or button or whatever action) you need to ensure that this value is turned off (NO).
![2022-08-03 14_45_33-Window](https://user-images.githubusercontent.com/90036056/182611580-5b29f5d1-8e99-4460-a5fb-0b3aea195739.jpg)

**Comment by jasm1nii** [comment]
the solution provided above sadly doesn't work in my case... would very much like to see support for this

**Comment by sequoi** [comment]
> the solution provided above sadly doesn't work in my case... would very much like to see support for this

How do you mean, you need to provide more details in order to help you out? "Does not work in my case" is open to a lot of interpretations and guesswork. Can you explain do you have more popups, buttons, screenshots anything? What does not work?

**Comment by jasm1nii** [comment]
okay, just discovered something else as i'm testing things now - this indeed works for elementor buttons with dynamic tags linked to a popup, but _not_ with native wordpress/gutenberg buttons in posts that are associated with a CSS ID.

**Comment by gustavocoimbradev** [comment]
Same problem here. I have two popups on the page, only the first one opens correctly, the second one opens without styles inside it. If I reverse the order of the buttons, the one that opened incorrectly now opens correctly, it doesn't make any sense.

**Comment by sardinessss** [comment]
Here's how I solved mine. Instead of pasting the ID in the **link**, paste it in the **button id**. Don't forget to remove the pound key (#).

![Image](https://github.com/user-attachments/assets/7470c602-bdb7-42b9-afb6-57663025f803)
