### ISSUE TITLE
Sticky Popup conflict

### ISSUE THREAD

**Issue by bobocop4u** [pojome/elementor#680]
Sticky Popup is a plug in that allows a popup window at the edge of the main theme outside the body of the page..
It's content is free to choose but wil appear on all desired pages.
In my case it has a shortcode for a menu.
I use the make theme.
You can see the popup and menu at work at www.dantha-photography.be
As soon as I activate Elementor on a page and fill it's content, the content of the Sticky Popup plug in is overwritten with the content of the body on the page.
On all other pages without Elementor the Popup gives the right menu content.

[system-info-www.dantha-photography.be-01-10-2016.txt](https://github.com/pojome/elementor/files/504346/system-info-www.dantha-photography.be-01-10-2016.txt)

**Comment by WPDevHQ** [comment]
IS this the plugin: https://wordpress.org/plugins/sticky-popup/ ?

**Comment by bobocop4u** [comment]
Yes, it is.

**Comment by arielk** [comment]
Sorry, but this plugin didn't support WordPress 4.5+, see the alert on the plugin page: 

> This plugin hasn’t been updated in over 2 years. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

**Comment by bobocop4u** [comment]
May I point out that "may have compatibility issues when used with more recent versions of WordPress." is not equal with "will have or shall have..." no more does it say that the issue is related to ....
