### ISSUE TITLE
Sticky Header Does Not Work With Single Product Page with WooCommerce Storefront Theme

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#6802]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Sticky Header Does Not Work With Single Product Page with WooCommerce Storefront Theme.
It works on other Elementor pages from what we can tell:

The Product Archive Page it DOES work on:
https://bit.ly/2RVGSX6

The Single Product Page it DOES NOT work on:
https://bit.ly/2FLLrfX

## Steps to reproduce
Install Elementor
Install Elementor Pro
Install WooCommerce Storefront theme
Create Single Product Page
Create Header
Add Header Template to Single Product Page
Choose Sticky at top

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active. - With WooCommerce Storefront Theme
- [x] I can reproduce this bug consistently using the steps above.

## Environment

== Server Environment ==
Operating System: Linux
Software: Flywheel/5.0.0
MySQL version: (Google) v5.7.14
PHP Version: 7.2.13-1+ubuntu16.04.1+deb.sury.org+1
PHP Max Input Vars: 4000
PHP Max Post Size: 300M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: There are some writing permissions issues with the following directories/files:
- WordPress root directory
Elementor Library: Connected

== WordPress Environment ==
Version: 5.0.3
Site URL: https://bit.ly/2JyZzaK
Home URL: https://bit.ly/2JyZzaK
WP Multisite: No
Max Upload Size: 300 MB
Memory limit: 256M
Permalink Structure: /%postname%/
Language: en-US
Timezone: America/New_York
Debug Mode: Inactive

== Theme ==
Name: Storefront
Version: 2.4.2
Author: Automattic
Child Theme: No

== User ==
Role: administrator
WP Profile lang: en_US

== Active Plugins ==
CSS Hero
Version: 3.2
Author: The CSS Hero Team

Elementor
	Version: 2.4.0
	Author: Elementor.com

Elementor Pro
	Version: 2.3.1
	Author: Elementor.com

GPL Kit
	Version: 2.0.0
	Author: GPL Kit

Groups
	Version: 2.5.0
	Author: itthinx

Groups WooCommerce
	Version: 1.13.0
	Author: itthinx

If Menu - Visibility control for menu items
	Version: 0.12.2
	Author: Layered

Mailchimp for WooCommerce
	Version: 2.1.11
	Author: Mailchimp

Responsive Menu Pro
	Version: 3.1.17
	Author: Peter Featherstone

Safe SVG
	Version: 1.9.0
	Author: Daryll Doyle

Storefront Powerpack
	Version: 1.4.13
	Author: WooCommerce

Tidio Chat
	Version: 3.4.0
	Author: Tidio Ltd.

WooCommerce
	Version: 3.5.3
	Author: Automattic

WooCommerce Bookings
	Version: 1.12.2
	Author: Automattic

WooCommerce Frontend Manager
	Version: 5.2.9
	Author: WC Lovers

WooCommerce Frontend Manager - Analytics
	Version: 1.2.1
	Author: WC Lovers

WooCommerce Frontend Manager - Groups & Staffs
	Version: 3.1.3
	Author: WC Lovers

WooCommerce Frontend Manager - Product Hub
	Version: 1.0.1
	Author: WC Lovers

WooCommerce Frontend Manager - Ultimate
	Version: 5.2.8
	Author: WC Lovers

WooCommerce Google Analytics Pro
	Version: 1.6.4
	Author: SkyVerge

WooCommerce Multivendor Marketplace
	Version: 2.0.8
	Author: WC Lovers

WooCommerce Multivendor Membership
	Version: 2.3.1
	Author: WC Lovers

WooCommerce PayPal Checkout Gateway
	Version: 1.6.6
	Author: WooCommerce

WooCommerce Product Add-ons
	Version: 3.0.5
	Author: WooCommerce

WooCommerce Services
	Version: 1.18.0
	Author: Automattic

WooCommerce Stripe Gateway
	Version: 4.1.14
	Author: WooCommerce

WooCommerce Subscriptions
	Version: 2.4.7
	Author: Prospress Inc.

WooCommerce Variation Swatches and Photos
	Version: 3.0.11
	Author: Lucas Stark

WP Job Manager
	Version: 1.31.3
	Author: Automattic

WP Job Manager - Resume Manager
	Version: 1.17.0
	Author: Automattic

WPS Hide Login
	Version: 1.5.2.1
	Author: WPServeur, NicolasKulka, tabrisrp

YITH WooCommerce Ajax Product Filter Premium
	Version: 3.6.2
	Author: YITH

YITH WooCommerce Ajax Search Premium
	Version: 1.6.5
	Author: YITH

YITH WooCommerce Category Accordion Premium
	Version: 1.0.24
	Author: YITH

Yoast SEO: Local
	Version: 9.4
	Author: Team Yoast and Arjan Snaterse

Yoast SEO Premium
	Version: 9.4
	Author: Team Yoast

**Comment by shilo-ey** [comment]
@smile00000 

Please update to the latest version of Elementor (2.4.5) and Elementor Pro (2.4.3) and let us know if that sorted the issue for you.

Thanks.

**Comment by smile00000** [comment]
@shilo-ey thanks so much this worked!
