### ISSUE TITLE
Woocommerce repeat last order widget

### ISSUE THREAD

**Issue by vinesjd** [pojome/elementor#6806]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There are an increasing number of restaurants selling over woocommerce websites these days and I keep getting requests for an "order again" button/section that shows the customers last order along with the product(s) feature image. This would be useful to literally thousands of customers.

**Describe the solution you'd like**
A widget that shows a customers last order(or last x orders) (if they are logged in) with each line item(with link to product page), thumbnail of the feature image(with link to product page) and the total. Also a button that adds everything to the cart like in the order details page that comes with woocommerce. If they user isn't logged in, it should have some customized text input and a button that takes them to log in page (or even a login form).

**Describe alternatives you've considered**
Writing my own function outside of Elementor that creates the funcitonality. This isn't ideal as the point of Elementor is that clients can have someone design their page and then they can maintain it themselves. There's isn't a good way (that I know of) to add non-elementor stuff to a page that is constantly being edited. Clients are super likely to screw up margins/spacing and such that they then won't be able to fix because there's non elementor content on the page. 

**Additional context**
There fastest growing source of work right now is from restaurants looking to get out of paying the high commisions of food services websites like pedidasya and uber eats. There is huge demand for this (even if people haven't realized they want it) and it makes using elementor with WC that much easier. 

Thanks.

**Comment by shilo-ey** [comment]
Hi @vinesjd ,
Thanks for your suggestion.

What you are describing is an E-Commerce functionality, so it needs to be incorporated in the WooCommerce plugin for example, and not in the Elementor.

Thanks for the feedback.

**Comment by vinesjd** [comment]
why? That doesn't even make sense. It's all core WC

**Comment by vinesjd** [comment]
You are not even going to respond to this? You closed it arbitrarily and you're just going to leave it at that?

**Comment by shilo-ey** [comment]
@vinesjd 

I understand what you are saying.

Exactly for these cases we've created our [Developers API](https://developers.elementor.com/), which you can use for incorporating this functionality.

Good luck

**Comment by vinesjd** [comment]
You don't think it would be useful to a have a sign in/sign out widget for
woocommerce sites that is actually relevant? This is a pretty straight
firward widget to build and it should be standardized with elementor,
should it not?
You could even just add the optional repeat order to the current sign
in/out widget.

I get it that there's a developer api, but this isn't a bespoke
customization. This is something that a significant portion of
woocommerce/elementor sites would use if it was available. And for that
reason, I think that it should be developed and released with the pro
version of the plugin.
