### ISSUE TITLE
Editor not loading

### ISSUE THREAD

**Issue by denisciumbargi** [pojome/elementor#6807]
Hi guys, **since the new update that introduced safe mode** my editor isn't working anymore except safe mode.

Tried the troubleshooting, tried deactivating plugins one by one... the only error I get is the one below.

Ideas?

```
2019-01-20 17:30:22 [info] Elementor data updater process has been completed. [array (   'plugin' => 'Elementor',   'from' => '2.4.1',   'to' => '2.4.2', )]
--
JS: 2019-01-20 17:37:08 [error X 20][/wp-content/plugins/elementor/assets/js/editor.min.js:2:82785] Cannot read property \'window\' of undefined 

```

**Comment by shilo-ey** [comment]
Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

And see if the issue still persists.

[Further read here](https://docs.elementor.com/article/471-debuging-safe-mode).
 
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
