### ISSUE TITLE
Settings for *existing* background images on tab/mobile default to Default

### ISSUE THREAD

**Issue by vsimon51** [pojome/elementor#6808]
The new background (and background overlay) image options (selectable by device as opposed to universal) puts Default settings in place on the tablet and mobile device settings and also does not show any selected image. The visible result (at least on Safari on mobiles) is to show a very small section of a massive image - as if a crop has been taken from the centre of the laptop.
My only solution at present is to open every background and manually set the image and settings for tablet and mobile.
I wish Elementor had at least ported the old universal settings into all devices instead of setting tablet and mobile to default. And I wish somebody had warned me - I only discovered the problem when updating a site's mobile settings (NB this problem does *not* show if testing on an emulator for either Chrome or Safari mobile, but *does* show when testing on an actual device - so far on iPhone 6 and iPhone X)

**Comment by bainternet** [comment]
thanks for reporting.

It's fixed in 2.4.3
