### ISSUE TITLE
Why is Yoast SEO excluded in the templates?

### ISSUE THREAD

**Issue by rcasunshare** [pojome/elementor#6809]
Why ??? Tweak: Exclude library CPT from Yoast SEO sitemap

Now you can not control each template your SEO, this negatively impacts SEO

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
