### ISSUE TITLE
Remove elementor-panel-header-menu-button for User Role

### ISSUE THREAD

**Issue by abaney** [pojome/elementor#681]
I'd like to see an option to remove the navigation bar with the ID of `elementor-panel-header-menu-button` for specific "user roles". Honestly, I don't want clients to have access to accidentally change:

- Global Colors
- Global Fonts
- Elementor Settings
- About Elementor

Not sure yet about some upcoming features "Page Settings" or "Revisions History". "Revisions History" may be handy, though, for clients to access.

Would be nice if Elementor could be white-labeled also for specific user roles.

![elementor-panel-header-menu-button](https://cloud.githubusercontent.com/assets/2255186/19018235/3c802690-8817-11e6-8cc2-42f584d201d5.png)

**Comment by arielk** [comment]
We call it "Advanced Role manager". This feature is probably going to be a part of the upcoming Elementor PRO. Stay tuned!

ref: #681 #483

**Comment by abaney** [comment]
Cool. Thanks, @arielk !
