### ISSUE TITLE
Search and Manual Page Navigation Not Working in Elementor Templates Admin

### ISSUE THREAD

**Issue by midihead7** [pojome/elementor#6810]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

In the Templates admin in the backend, the Search Template feature is not working in Elementor version 2.4.2. Regardless of the search term, no results are returned. Also navigating pages of templates by enter the page number and hitting Enter also returns no results instead of navigating to the chosen page. Other users in the Elementor Facebook group have confirmed that the same issues exist for them.

![image](https://user-images.githubusercontent.com/28960642/51449014-f594d500-1cde-11e9-8119-851c727559b5.png)

![image](https://user-images.githubusercontent.com/28960642/51449102-66d48800-1cdf-11e9-9f8d-0642d61f978e.png)

## Steps to reproduce

1. In the Search Template field, enter a search term and hit Enter or click the Search Template button. No results are returned when searching for existing template names.

2. For the navigation issue, type a number manually into the page number box and hit enter. No results are returned instead of the desired page.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.20
	PHP Version: 7.2.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://new.homewardpublishingministries.com
	Home URL: https://new.homewardpublishingministries.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.6.4
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	All-in-One Event Calendar by Time.ly
		Version: 2.5.36
		Author: Time.ly Network Inc.

	All-in-One WP Migration
		Version: 6.83
		Author: ServMask

	All-in-One WP Migration File Extension
		Version: 1.2
		Author: ServMask, Inc.

	All-in-One WP Migration Google Drive Extension
		Version: 2.43
		Author: ServMask

	Antispam Bee
		Version: 2.9.0
		Author: pluginkollektiv

	Astra Pro
		Version: 1.6.11
		Author: Brainstorm Force

	Central Color Palette
		Version: 1.13.1
		Author: Gáravo

	Custom Related Products for WooCommerce
		Version: 1.3
		Author: Scott Nelle

	Disable Gutenberg
		Version: 1.5.2
		Author: Jeff Starr

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.4.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.3.1
		Author: Elementor.com

	iThemes Security
		Version: 7.2.0
		Author: iThemes

	Popup Maker
		Version: 1.7.30
		Author: WP Popup Maker

	ShortPixel Image Optimizer
		Version: 4.12.5
		Author: ShortPixel

	SiteOrigin Widgets Bundle
		Version: 1.14.1
		Author: SiteOrigin

	SRS Simple hits Counter
		Version: 1.0.3
		Author: Atif N

	TinyMCE Advanced
		Version: 5.0.0
		Author: Andrew Ozz

	UpdraftPlus - Backup/Restore
		Version: 1.16.4
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 3.5.3
		Author: Automattic

	WooCommerce Dynamic Pricing
		Version: 3.1.10
		Author: Lucas Stark

	WooCommerce Improved External Products
		Version: 1.5.1
		Author: Ewout Fernhout

	WooCommerce Min/Max Quantities
		Version: 2.4.5
		Author: WooCommerce

	WooCommerce PDF Invoices & Packing Slips
		Version: 2.2.5
		Author: Ewout Fernhout

	WooCommerce Sequential Order Numbers
		Version: 1.8.3
		Author: SkyVerge

	WooCommerce Shipping Per Product v2
		Version: 2.2.15
		Author: WooCommerce

	WooCommerce USPS Shipping
		Version: 4.4.19
		Author: WooCommerce

	WP-UserOnline
		Version: 2.87.2
		Author: Lester 'GaMerZ' Chan

	WP Crontrol
		Version: 1.6.2
		Author: John Blackbourn & contributors

	WP Mail SMTP
		Version: 1.4.1
		Author: WPForms

	Yoast SEO
		Version: 9.4
		Author: Team Yoast


== Log ==
	: 
Log: showing 1 of 12019-01-20 16:56:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.2',
)]
```
</details>

**Comment by shilo-ey** [comment]
Hi @midihead7 

We couldn't replicate the issue you are reporting.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

And see if the issue still persists.

Thanks.

**Comment by KiQdev** [comment]
Same issue. Using Elementor Hello, latest versions of Elementor and Elementor Pro. Search in templates returns no results if Pro isn´t active. Same on all sites
