### ISSUE TITLE
Equal column spacing with more than 2.

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#682]
Not sure if this can already be done but would be nice to be able to let the user select the spacing between the first and last type of columns more than 2. So for example:

<img width="1399" alt="screen shot 2016-10-02 at 11 16 45" src="https://cloud.githubusercontent.com/assets/13979799/19019953/eb411584-8891-11e6-980a-97b8968d7ad0.png">

10px on left column - 20px between first and middle.

You can see the spacing between the middle column is double the spacing as it's taking the gutter of the left and right columns. It would be good to allow the gutters to be all the same width. I'm sure this could be done with first/last child.

Thanks!

**Comment by arielk** [comment]
I merged this issue with another issue #452 in the same subject so that our Dev staff could deal with it more efficiently. So please let's continue the conversation there.
