### ISSUE TITLE
Post FORM Data to custom URL

### ISSUE THREAD

**Issue by tcoursey** [pojome/elementor#6820]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Allow user to submit form data to a custom URL that then processes the form data how it wants to.
**Describe the solution you'd like**
Dropdown shows option on integrations to show Custom URL.  Then allows entry of that url in text box.

**Describe alternatives you've considered**
Looking into how the form data is handled currently and re-working the code, but I'm not a developer.

**Additional context**
This would be a way that diy coders could try and integrate into other systems more easily.  Create a PHP file that handles the form data from "sample code" providers and then point the form data from Elementor to this url.  This could be a band aide of sorts for much more integration options with third parties.  We use Hot Prospector for marketing and have some standard integration code we could immediatly implement if this feature was available.  Right now we will have to embed an iframe form that points to the processor.  Not a great solution and not very responsive for mobile.

**Comment by bainternet** [comment]
We have an example of custom webhooks in our [forms API docs](https://developers.elementor.com/forms-api/#Form_Processing_Action-2)

and a huge list of examples here: https://github.com/pojome/elementor/issues/2397#issuecomment-357495616


if you have a specific question, feel free to open a new issue if you have a specific question.
