### ISSUE TITLE
 Bug elementor popup + wprocket optimisation css & js

### ISSUE THREAD

**Issue by Pixtural** [pojome/elementor#6822]
Hello,

When i use the wprocket css and js optimiation feature, the popup does not display correctly. Do you have a solution for this problem? 

Sincerely,
See you

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

thanks

**Comment by walik-walik** [comment]
+1

**Comment by stasonua0** [comment]
> Hello,
> 
> When i use the wprocket css and js optimiation feature, the popup does not display correctly. Do you have a solution for this problem?
> 
> Sincerely, See you

Try adding to the exception https://prnt.sc/24i87x6

/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
/elementor-pro/assets/js/webpack-pro.runtime.min.js
/elementor-pro/assets/lib/smartmenus/jquery.smartmenus.min.js
/elementor/assets/js/webpack.runtime.min.js
/elementor/assets/js/frontend-modules.min.js
/wp-includes/js/imagesloaded.min.js
/elementor-pro/assets/js/frontend.min.js
/elementor/assets/lib/waypoints/waypoints.min.js
/elementor/assets/js/frontend.min.js
/elementor-pro/assets/js/elements-handlers.min.js
/elementor/assets/lib/dialog/dialog.min.js
elementorFrontendConfig
ElementorProFrontendConfig

**Comment by jwcrea** [comment]
I have an issue with the popup function on a button in connection with the wp Rocket Plugin. The popup function is working in the preview but not on the live system. Only after completely disabling WP Rocket the pop up function is working. I tried to enable Wp Rocket save mode and disabled all minification and caching, delaying etc. (basically disabled everything in file opimization) on css and js files with no help.Also tried https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#elementor-pro but no solution either. Right no i am working on the latest Version: 3.7.0-dev9 and Wordpress 5.9. I am not sure if this is related to this topic or an issue on its own or even an just an WP Rocket issu
[system-info-27-01-2022.txt](https://github.com/elementor/elementor/files/7949050/system-info-27-01-2022.txt)
e
