### ISSUE TITLE
CPT/Meta Query

### ISSUE THREAD

**Issue by Kpudlo** [pojome/elementor#6825]
Hello, 

I was told to post my request here after emailing your team for support:

I'm trying to create a query for a Posts Layout that connects several CPT's. 

The first CPT is called `location`, and that is where I'm trying to add the Posts Layout query.

The second CPT is called `park`, and it has a relationship field to assign it to a location. 

I'm trying to get the query to show only posts that have the same location that is being viewed right now. This is my current query:

`//Posts Widget 
add_action( 'elementor_pro/posts/query/test_query', function( $query ) { 
// Modify the posts query here 
// Get current meta Query
$meta_query = $query->get( 'meta_query' ); 
// Append our meta query 
$meta_query[] = [ 
   'key' => 'location',
   'value' => '336',
    ];
$query->set( 'meta_query', $meta_query ); } );`

When I use this setup, I'm not getting any return of value, and it seems to be messing up the layout:
![image](https://user-images.githubusercontent.com/4432822/51494344-5e835800-1d86-11e9-8601-258bbc58882c.png)

When I remove the query from the Posts Layout it sets back to default:
![image](https://user-images.githubusercontent.com/4432822/51494352-63e0a280-1d86-11e9-93e1-43e7f9d99272.png)

In the example above, I'm attempting to get Magic Kingdom to show under Walt Disney World, but not have Disneyland Park show up.

Do you have any advice on how to get this to work correctly? I appreciate it very much. 

Thank you, 
Kevin Pudlo

**Comment by bainternet** [comment]
@Kpudlo 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

but looking at the screenshots you have posted it seems like you are running in to a PHP error, so you should check your error log.
