### ISSUE TITLE
Feature request: ADD Class to Popup settings

### ISSUE THREAD

**Issue by erfan-ilyas** [pojome/elementor#6826]
Hello,

Thanks for the nice popup feature. If you can just add "Add Class" to the popup settings pages just like we can add "Add ID"/"Add Class" to any element that will be great.

I guess we cannot assign custom ID because elementor must be using it for its internal javascript functions.

But I am sure we can have add class to the popup settings panel.

![image](https://user-images.githubusercontent.com/1281946/51500192-092f6100-1def-11e9-9198-523113cd0af5.png)

**Comment by shilo-ey** [comment]
Hi @erfan-ilyas 

Thanks for your feedback.

We are adding a unique dynamic ID to the popup.
`elementor-popup-modal-XXXXX` while XXXXX is the ID of the popup.

You can easily target your popup using this rule, or use `elementor-popup-modal` Class we also added.

If this is not meeting your requirements please let us know about your desired use case.

Thanks.

**Comment by shilo-ey** [comment]
This feature has been added to the Elementor Pro v2.4.1, feel free to upgrade.

Thanks,
