### ISSUE TITLE
Elementor not displaying pagination for Product Archive Page "Shop"

### ISSUE THREAD

**Issue by cannablastcbd** [pojome/elementor#6827]
So let me start off, by stating I am a graphic designer. I have built MOST of this website with drag and drop stuff like Elementor. I have little no no coding experience. I need help! I want to learn!

Right now I am having trouble getting my pagination to display. It is showing up when editing in Elementor, but completely disappears when I preview the page. Yes it has been published.

I am editing on a product archive template to make it my shop page. Please help me get pagination!

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by cannablastcbd** [comment]
Okay well when I paid for this plugin I was promised PREMIUM support, and
I've submitted a ticket, and nobody is getting back to me.
