### ISSUE TITLE
Differences in page appearance between edit mode and page preview.

### ISSUE THREAD

**Issue by arthurmarkwill** [pojome/elementor#683]
I have a page template that has two columns, the column on the left is 40.4% and the right 59.6%

The page looks really great when editing in the elementor plugin but when I preview the page outside the plugin to see how it would look on the site the items in the left column shrink and there is a large gap between the left and right columns which is not present when editing in the plugin.

Is there a way of fixing this?

**Comment by arthurmarkwill** [comment]
![block test](https://cloud.githubusercontent.com/assets/22598460/19048192/35a88876-899d-11e6-8e23-c0d3e98b62c7.png)

**Comment by arthurmarkwill** [comment]
Is this likely to be a conflict with the theme?

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
