### ISSUE TITLE
Any page edited with Elementor clips through the headers

### ISSUE THREAD

**Issue by javaunm** [pojome/elementor#6833]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Using the Flatsome theme on Wordpress, since the recent update, if I scroll down on any page, any widget made through Elementor clips through the header/sticky header which doesn't look to appealing

## Steps to reproduce

Use Elementor and Flatsome (both latest versions).
Create a page and make sure sticky header is turned on. 
Scroll down on that page and you will see the widgets clip through the header.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.1.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://smartselect.tech
	Home URL: https://smartselect.tech
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Debug Mode: Inactive

== Theme ==
	Name: Flatsome Child
	Version: 3.0
	Author: UX Themes
	Child Theme: Yes
	Parent Theme Name: Flatsome
	Parent Theme Version: 3.7.2
	Parent Theme Author: UX-Themes

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Admin Columns
		Version: 3.3.1
		Author: AdminColumns.com

	Admin Menu Editor
		Version: 1.8.5
		Author: Janis Elsts

	Anti-Malware Security and Brute-Force Firewall
		Version: 4.18.52
		Author: Eli Scheetz

	Autoptimize
		Version: 2.4.4
		Author: Frank Goossens (futtta)

	Awesome Support
		Version: 5.8.0
		Author: Awesome Support Team

	Awesome Support: E-Mail Support
		Version: 5.7.3
		Author: The Awesome Support Team

	Call Now Button
		Version: 0.3.5
		Author: Jerry Rietveld

	Classic Editor
		Version: 1.3
		Author: WordPress Contributors

	Coming Soon Page & Maintenance Mode by SeedProd
		Version: 5.0.23
		Author: SeedProd

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.4.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.0
		Author: Elementor.com

	Email Login Auth
		Version: 0.4
		Author: Michal Stanke

	Email Subscribers & Newsletters
		Version: 3.5.17
		Author: Icegram

	Email Tracker (Premium)
		Version: 5.0
		Author: Prashant Baldha

	Email Users
		Version: 4.8.8
		Author: Mike Walsh & MarvinLabs

	Essential Addons for Elementor
		Version: 2.9.0
		Author: WPDeveloper

	Export Users to CSV
		Version: 1.1.1
		Author: Matt Cromwell

	Gravity Flow
		Version: 2.4
		Author: Gravity Flow

	Gravity Forms
		Version: 2.4.5
		Author: rocketgenius

	Gravity Forms - Uploads as Attachments
		Version: 1.2.0
		Author: Jebble

	Gravity Forms Button - An Ajax Form Loader
		Version: 0.1
		Author: stevehenty

	Gravity Forms Signature Add-On
		Version: 3.5.1
		Author: Rocketgenius

	Gravity Forms Signature Add-on by ApproveMe
		Version: 1.5.3.8
		Author: Approve Me

	Gravity PDF
		Version: 5.1.3
		Author: Gravity PDF

	Gravity PDF Developer Toolkit
		Version: 1.0.0-beta5
		Author: Gravity PDF

	Icegram - Popups, Optins, CTAs & lot more...
		Version: 1.10.25
		Author: icegram

	KB - Elegant Layouts
		Version: 1.7.1
		Author: Echo Plugins

	Knowledge Base for Documents and FAQs
		Version: 4.4.1
		Author: Echo Plugins

	Messenger Customer Chat
		Version: 1.1
		Author: Facebook

	N-Media WooCommerce PPOM
		Version: 16.4
		Author: Najeeb Ahmad

	PDF Embedder
		Version: 4.0
		Author: Dan Lester

	Peter's Login Redirect
		Version: 2.9.1
		Author: Peter Keung

	Post Expiration Date
		Version: 1.3
		Author: Huguette Inc.

	Profile Builder
		Version: 2.9.4
		Author: Cozmoslabs

	Really Simple SSL
		Version: 3.1.3
		Author: Rogier Lankhorst, Mark Wolters

	Recent Posts Widget With Thumbnails
		Version: 6.4.1
		Author: Martin Stehle

	Regenerate Thumbnails
		Version: 3.1.0
		Author: Alex Mills (Viper007Bond)

	Responsive Posts Carousel
		Version: 5.0
		Author: WebCodingPlace

	Restrict User Access
		Version: 1.0.1
		Author: Joachim Jensen

	Smush
		Version: 3.0.2
		Author: WPMU DEV

	Social Media Auto Publish
		Version: 2.1
		Author: xyzscripts.com

	SP Project & Document Manager
		Version: 3.3.4
		Author: smartypants

	Sticky Header Effects for Elementor
		Version: 1.2.2
		Author: Rwattner

	Tabs Responsive
		Version: 1.8.9
		Author: wpshopmart

	The Events Calendar
		Version: 4.7.4
		Author: Modern Tribe, Inc.

	The Events Calendar PRO |  VestaThemes.com
		Version: 4.4.23
		Author: Modern Tribe, Inc.

	The Events Calendar Shortcode and Templates
		Version: 1.3
		Author: Cool Plugins

	TinyMCE Advanced
		Version: 5.0.0
		Author: Andrew Ozz

	Username Changer
		Version: 3.1.3
		Author: Daniel J Griffiths

	User Role Editor
		Version: 4.49
		Author: Vladimir Garagulya

	User Shortcodes Plus
		Version: 2.0.1
		Author: Kyle B. Johnson

	Visibility Logic for Elementor
		Version: 1.0.2
		Author: SeventhQueen

	Webcraftic Disable Admin Notices Individually
		Version: 1.0.6
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	When Last Login
		Version: 1.1
		Author: Yoohoo Plugins

	WooCommerce
		Version: 3.5.4
		Author: Automattic

	WooCommerce Extended Coupon Features FREE
		Version: 3.0.5
		Author: Soft79

	WooCommerce Square
		Version: 1.0.34
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 4.1.14
		Author: WooCommerce

	Woo Custom Emails Per Product
		Version: 2.2.2
		Author: Alex Mustin

	Wordfence Security
		Version: 7.1.20
		Author: Wordfence

	WordPress Inspector
		Version: 1.1.0
		Author: MailMunch

	WP Crontrol
		Version: 1.6.2
		Author: John Blackbourn & contributors

	wpDataTables
		Version: 2.3.2
		Author: TMS-Plugins

	WP E-Signature
		Version: 1.5.4.3
		Author: Approve Me

	WP E-Signature Business add-ons
		Version: 1.5.4.0
		Author: Approve Me

	WP ERP
		Version: 1.4.1
		Author: weDevs

	WP Mail SMTP
		Version: 1.4.1
		Author: WPForms

	WP Statistics
		Version: 12.5.7
		Author: VeronaLabs

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 1.3
		Author: Mike Hansen

== Log ==
	: 
Log: showing 2 of 22019-01-21 08:31:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.3',
)]
2019-01-21 08:31:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]

PHP: showing 1 of 1PHP: 2019-01-21 08:31:46 [notice X 1][/home3/vr3zy791/public_html/wp-content/plugins/sp-client-document-manager/cu.php::260] Undefined index: page [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2019-01-22 01:12:45 [error X 1][https://smartselect.tech/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5699\") has already been destroyed and cannot be used. 
JS: 2019-01-22 01:14:57 [error X 2][https://smartselect.tech/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.3:2:6883] Cannot read property \'select2\' of undefined 
JS: 2019-01-22 01:15:00 [error X 1][https://smartselect.tech/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1218\") has already been destroyed and cannot be used. 
</details>

**Comment by shilo-ey** [comment]
@javaunm 

Your issue is caused by header `z-index` value of 30, and elementor container `z-index` of 99.
We cannot identify what causes this issue because you are using autoptimize cache plugin.

Try to disable it and see if the issue persists.

If not try changing the z-index of the header to 100 or above.

Thanks

**Comment by javaunm** [comment]
@shilo-ey I have no clue what that is or what your talking about. I'm not using the Elementor header either, I'm using the theme default header so how would I go about fixing this? I cleared the autoptimize cache so that should've updated everything to be current..
