### ISSUE TITLE
Multiple Canvas View Functionality

### ISSUE THREAD

**Issue by simplysianne** [pojome/elementor#6836]
Hi,

I've been testing out ShowIt and love their multiple canvas view functionality that allows the site to be more interactive and allows for multiple content to appear on a page without having to jump over to another page and without scrolling. I think it would be really beneficial for Elementor to have this type of functionality as well. 

Here's an example: https://simply-sianne-2.showitpreview.com/

The third section is the one that has multiple canvas views.

Thanks! 
Sianne

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
