### ISSUE TITLE
[RE-OPEN] Any page edited with Elementor clips through the headers

### ISSUE THREAD

**Issue by javaunm** [pojome/elementor#6838]
#6833 
@shilo-ey I have no clue what that is or what your talking about. I'm not using the Elementor header either, I'm using the theme default header so how would I go about fixing this? I cleared the autoptimize cache so that should've updated everything to be current..

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.


From the way I look at it, you figured it out.

**Comment by javaunm** [comment]
Yes, I did. Thanks..

**Comment by shilo-ey** [comment]
@javaunm 
We've encountered this issue with several users of ours.

The issue originates from Essential Add-on, setting `z-index: 99;` to the content.

Try reaching out to the Add-on developers and let them know about this issue.

Thanks.
