### ISSUE TITLE
FEATURE REQUESTS - Klicksend integration

### ISSUE THREAD

**Issue by FabioCampos65** [pojome/elementor#6839]
Integration between the Elementor-Pro and an email marketing provider. Could you make contact with this service to accomplish this integration for the contact forms? It is a Brazilian system called "Klicksend". Would you have a solution, please? Tks.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

as for your actual request, I can't seem to find their API, but if you do, you can use our [forms API](https://developers.elementor.com/forms-api/) to integrate with them, also see [many examples here](https://github.com/pojome/elementor/issues/2397#issuecomment-357495616).
