### ISSUE TITLE
Ability to add text to close button

### ISSUE THREAD

**Issue by JohnMulderFrance** [pojome/elementor#6840]
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Although it might be hard to imagine, there are still people who do not understand that clicking the close icon will close a popup. I have seen this happening more than once with older, less experienced users, panicked by the disappearance of their screen by a dark overlay, not knowing what to do.
The ability to add a text like "close" or whatever term in the native language will help the less experienced users.

**Comment by bainternet** [comment]
@JohnMulderFrance 	

You can add the text yourself using a button or text widgets and set the lick to dynamic => popup => close, instead of using the default X close button.

thanks.
