### ISSUE TITLE
Exit animations and entrance/exit animations based upon viewport

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#6843]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SniffleValve** [comment]
I absolutely love the new Popup feature! :) 

As the title suggests, it would be nice at some point to include an Exit Animation option.
Additionally, it would also be nice to be able to select which entrance/exit animation for each viewport. i.e.  Desktop, tablet, mobile.

Cheers!
Lyle

**Comment by shilo-ey** [comment]
Hi @SniffleValve 
Glad to hear you find this feature useful :)

As for your requests, as you know this feature is new and we are constantly improving it.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by black-eye** [comment]
+1

**Comment by elasticeye** [comment]
+1

**Comment by semmtex** [comment]
Yes please! This would be a very nice addition...

**Comment by JudeRosario** [comment]
+1
