### ISSUE TITLE
A way to disable new PHP logger (massive performance drain)

### ISSUE THREAD

**Issue by vladolaru** [pojome/elementor#6844]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The new PHP logger introduced in version 2.4.0 is **updating the database option** on every request since it catches everything from PHP warnings to errors. This has **serious performance implications.** 

For us, it overflowed our MySQL binary logging since the data saved in the option is **massive** (some huge array with datetimes) and updated on almost every request to PHP due to the fact that there is always a warning or a notice generated by one plugin or another.

**Describe the solution you'd like**
For less technical people, I believe this should be an opt-in in the settings, `off` by default.
But at least for developers, provide a filter or, better yet, a constant that would prevent the logger logic from activating. Or at least a way to say the type of logging to be done (just errors for example).

**Describe alternatives you've considered**
I have studied the code and there is no clean way to disable the (db) logger. I ended up filtering `get_option` and `update_option` for `elementor_log` to prevent it from touching the database.

**Additional context**
---

**Comment by shilo-ey** [comment]
Hi @vladolaru

Thanks for your feedback.

First of, Elementor logs error only when they happen and not on every page load (unless you do have errors on every page load).

Second the PHP logger has improved in version 2.4.2 with the following tweaks:
- Tweak: Better duplicate Error log entries handling
- Fix: Log only Elementor related errors

In addition, the logger is updating the database option only on [shutdown](https://codex.wordpress.org/Plugin_API/Action_Reference/shutdown) action (after the page is fully loaded), therefore it shouldn’t have any impact on the page load.

Elementor only log it’s own errors now and if there are other errors you really should resolve them.

Thanks

**Comment by vladolaru** [comment]
Hi @shilo-ey 

Thank you for taking the time to respond. Yes, limiting the logger to Elementor related errors is a good improvement. Related to performance, I am talking about MySQL performance and the fact that the option is updated on every page load (on shutdown as you said), and this can cause multiple effects with binary logging.

I am perfectly fine with logging errors, but not warnings or notices. I would fix those if they wouldn't be generated by various plugins using some functionality that is deprecated in newer PHP versions.

I will update to version 2.4.2 and see how things go.

At the same time, I would still insist that a way to disable logging entirely is warranted, especially for those of us with more technical skills.

Thanks

**Comment by black-eye** [comment]
+1

**Comment by deltafactory** [comment]
Related to MySQL performance, it also has significant impact on object caching as calls to `update_option()` resets the main options cache, resulting in additional DB queries. Please address this! I generally agree with the OP's approach to fix this.

**Comment by clonge** [comment]
We ran into the same issue, where it overflowed our MySQL binary logging. For anyone who runs into this, there's an easy solution, although a bit hacky. Simply add this filter as early as possible in your code to prevent the log from updating:

```
add_filter( 'pre_update_option_elementor_log', '__return_empty_array', 99 );
```

This effectively turns the log off. Although the log code continues to run, it does not update the database, which solves the primary performance issue.

**Comment by sun** [comment]
This performance problem still exists in the latest version of Elementor.

@clonge's suggested solution works (after clearing the log), but an official way to disable the logging - and/or at least limit it to `WP_DEBUG_LOG` being enabled - would be helpful.

Workaround:
```php
// Performance: Prevent Elementor from logging into options.
// @see https://github.com/elementor/elementor/issues/6844#issuecomment-2313053454
if ( ! defined('WP_DEBUG_LOG') || WP_DEBUG_LOG != true) {
  add_filter( 'pre_update_option_elementor_log', '__return_empty_array', 99 );
}
```
