### ISSUE TITLE
Page metaboxes inside elemetor

### ISSUE THREAD

**Issue by wayheming** [pojome/elementor#6847]
Hello, I have metaboxes for the page created using native WordPress API. Is there any way to allow metaboxes to be managed with an Elementor? http://prntscr.com/mazfie

**Comment by bainternet** [comment]
@wayheming 	

Nope, but you add sections and controls to the page setting, which is "Elementor's native MetaBoxes" if you want.

thanks.

**Comment by wayheming** [comment]
@bainternet 
Thank you. What about CMB2 for example? Will you ever add support for standard WordPress metaboxes?
