### ISSUE TITLE
Elementor Pro Form API post 

### ISSUE THREAD

**Issue by jmcst24** [pojome/elementor#6849]
I am trying the form/new record to post the form results to a URL.  

I have a basic form with a few fields and I am using the code from the API documentation and post the field data to the URL.  I am using a tool that shows any incoming request (pipedream) and it is not recieving  anything on the form submit

```PHP
// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
//make sure its our form
$form_name = $record->get_form_settings( 'form_name' );
if ( 'MY_FORM_NAME' !== $form_name ) {
return;
}

$raw_fields = $record->get( 'fields' );
$fields = [];
foreach ( $raw_fields as $id => $field ) {
$fields[ $id ] = $field['value'];
}

wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
'body' => $fields,
]);
}); 
```

The standard 'web hook' will send the results to the URL (pipedream) so the tool is working. 

I put the above code (updated form name and url) in a code snippet plugin on the page it it does not work.  I also put it in the theme's function.php code and that did not work either. 

I build a new site with nothing else on it except Astra theme, Elementor pro - 1 page 1 form on AWS Lightsail Bitnami stack and it did not work either. 

Is there a step that I am missing or why will this not post?  I have seen others that say they can't get it to post either.

**Comment by shilo-ey** [comment]
@jmcst24 Thanks for reporting this issue.

What causes this function to fail is missing arguments:
```PHP
// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );
    if ( 'MY_FORM_NAME' !== $form_name ) {
        return;
    }

    $raw_fields = $record->get( 'fields' );
    $fields = [];
    foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
    }

    wp_remote_post( 'HTTP://YOUR_WEBHOOK_URL', [
        'body' => $fields,
    ]);
}, 10, 2);

```

We will update this in our developers documentation.

Thanks.

**Comment by jmcst24** [comment]
I updated the PHP snippet from below and it is still not sending anything to the url.
https://enxxcsikqjf8j.x.pipedream.net

Can you advise what I am doing wrong?

**Comment by shilo-ey** [comment]
We can debug it using no additional information.

Use Requestbin to create a bin, and fill in your form name and endpoint URL.
https://requestbin.fullcontact.com/

After you successfully submit your Elementor form, refresh the bin page and check if anything received. 

If your form is not successfully submits, try to log your errors using WP Error debug mode + print to log file.

Alternatively, you can use our "Webhook" action after submit and set your endpoint there.

Good luck.

**Comment by jmcst24** [comment]
I was able to get it to work.

The “PHP snippet” plugin would not work, but adding it to the functions.php file did work and ‘restarting apaches’.

The PHP snippet would have been nice, not sure why it would not work.  The debug log file did not include anything.
