### ISSUE TITLE
Some popups don't show in latest version of Internet Explorer

### ISSUE THREAD

**Issue by srcek** [pojome/elementor#6850]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

I created the cookie notice popus on a few test sites. They're attached to the bottom of the page with Fade In Up transition, 100vw width and centered horizontally. Prevent closing on overlay and ESC key is on. They don't seem to show on screen for some reason. Everything works fine in modern browsers.

## Isolating the problem

- [x] This bug happens with a GeneratePress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* System info.

As for your question, IE11+ should work fine with the popups. 
Please try to use different theme and deactivate all of your plugins except Elementor

**Comment by srcek** [comment]
Tried installing 2019 theme and disabling all plugins. Problem is still there. Here's the info:
## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.35 (Win64) OpenSSL/1.1.0i PHP/7.2.11
	MySQL version: MySQL Community Server (GPL) v5.7.24
	PHP Version: 7.2.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://elementor.test
	Home URL: https://elementor.test
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Zagreb
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.4.3
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.0
		Author: Elementor.com


== Log ==
	: 
Log: showing 4 of 42019-01-20 19:07:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.2',
)]
2019-01-20 19:08:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0-beta3',
  'to' => '2.4.0-beta4',
)]
2019-01-21 13:59:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]
2019-01-21 14:00:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0-beta4',
  'to' => '2.4.0',
)]


				
```
</details>
