### ISSUE TITLE
Remove widget settings from Advanced Tab

### ISSUE THREAD

**Issue by fjpalawan** [pojome/elementor#6852]
Hi guys,

Is it possible to remove some settings from widgets advanced tab?

![image](https://user-images.githubusercontent.com/362935/51611655-b5da2180-1f5a-11e9-8ef0-a023523afe71.png)

I would like to remove some and leave Responsive and Custom CSS since other settings are not applicable on the widget im working on.

Thanks

**Comment by bainternet** [comment]
@fjpalawan 

yes there is, just like you would use `add_control()` method to add a control
https://github.com/pojome/elementor/blob/7aa486c4b0c57685ecd95d535801493ac0fc04ca/includes/base/controls-stack.php#L336-L352

 or `update_control()` to modify a control
https://github.com/pojome/elementor/blob/7aa486c4b0c57685ecd95d535801493ac0fc04ca/includes/base/controls-stack.php#L429-L449

there is `remove_control()` method to remove controls.

https://github.com/pojome/elementor/blob/7aa486c4b0c57685ecd95d535801493ac0fc04ca/includes/base/controls-stack.php#L413-L425

**Comment by dtmgs** [comment]
Hi @bainternet,

Kindly share code snippet to remove "background" section in advanced tab.

**Comment by Thelastpoet** [comment]
Is there a straight solution to this?
