### ISSUE TITLE
Integrating Theme Builder into a Custom Theme

### ISSUE THREAD

**Issue by digisavvy** [pojome/elementor#6854]
Hi there

I'm posting here because [I was directed to by support](https://digisavvycdn.s3.amazonaws.com/Re_Where_are_the_docs_to_integrate_theme_builder_with_a_custom_theme_-_alexjvasgmail.com_-_Gmail_2019-01-23_09-51-49.png).

Anyway, is there a doc or an issue that details how one integrates theme builder with a custom theme? I did not see a doc for it in the dev docs area of the site and as you can see above tech support did not know if any such doc or how-to. It's something that should be added to Elementor's documentation.

Thanks.

**Comment by bainternet** [comment]
@digisavvy 	


We do have [API docs](https://developers.elementor.com/theme-locations-api/) for Theme locations (theme builder integration) which you should follow.

We also have a [demo Theme](https://github.com/pojome/elementor-hello-theme) which you can look at.


And feel free to open a new issue if you have a specific question.

**Comment by digisavvy** [comment]
Perfect! Thank you.
