### ISSUE TITLE
503 Service Unavailable (in maintenance mode)

### ISSUE THREAD

**Issue by TimVNL** [pojome/elementor#6855]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

When I put my website in maintenance mode I get the following error

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

## Steps to reproduce

Set PHP version to PHP7.2 make a maintenance template and activate maintenance mode log out and go to the homepage.

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment
https://pastebin.com/BwrEdqWV

**Comment by bainternet** [comment]
@TimVNL 

Error 503 is a server-side error so you should check your error log and trace down the issue.

please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.
