### ISSUE TITLE
Disappearing Widgets After Paste Style

### ISSUE THREAD

**Issue by invictusdm** [pojome/elementor#6858]
Experiencing disappearing widgets on the latest builds of El & El Pro. Not just randomly, but sometimes when moving widgets and almost ALWAYS when pasting a style to an Internal Section widget or even pasting a style to a Column that contains the IS widget. If I refresh the editor page, it returns, but the moment I Paste Style to the IS widget, it disappears. Building on OceanWP as I’ve done plenty of times before. Aside from a few OWP plugins, not much else to conflict plugin-wise and this only started on the latest El/El Pro update.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
