### ISSUE TITLE
Copy Site / SRDB - does not replace the url of the background images

### ISSUE THREAD

**Issue by portanicolas** [pojome/elementor#6866]
when I copy my site, I run a SRDB to replace all the links. All the links are well changed but the site loads the photos from the old link! No system cache is activated or anything else.

It seems that the wallpaper link in elementor is not linked to a database.

Version : 
elementor 2.4.3
elementor pro 2.3.1

Theme :
 X Theme Pro / theme.co/pro

**Comment by shilo-ey** [comment]
You have to use Elemenentors' [Replace URL tool](https://docs.elementor.com/article/131-replace-url-change-domain) to correctly migrate your site.

Thanks.

**Comment by portanicolas** [comment]
thanks / i have go to WordPress Admin -> Elementor -> Tools.
And press Regenerate Files to clear the cache..

after this operation it works
