### ISSUE TITLE
Video backgrounds in Hero UI Kit

### ISSUE THREAD

**Issue by OseekerM** [pojome/elementor#687]
Hello,
there is a nuance with hero ui kit, when the video ends then displays a grid of related videos that is not quite great, how is it possible to loop video on the backgrounds of the selected video in this version section?

![hero header](https://cloud.githubusercontent.com/assets/22492121/19105193/09f02cda-8ae1-11e6-8620-b8df819df080.png)

**Comment by arielk** [comment]
Please go to the front page and check if it is still going on or that worked out.

Anyway the issue you opened is more suited for our official support forum. for the next time please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.

**Comment by OseekerM** [comment]
Hmm on the front page it works like a charm..

> GitHub issues are intended for feature requests or bug reports.
Thanks for the guidance, apologies for that.

**Comment by arielk** [comment]
Great!
