### ISSUE TITLE
[REQUEST] Is there a way to trigger a Popup from WP-menu, to behave much like Mega Menus?

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#6871]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

I'm trying to open a Popup template from within the wordpress menu to behave much like **Mega Menus.** And also would be nice to position the popup next to a class or ID (to stand next to the Main menu).

## Steps to reproduce

First I've tried to make a button and create a dynamic link and select Popup. After I created it and copied the link (that looks like:#elementor-action%3Aaction%3Dpopup%3Aopen%20settings%3DeyJpZCI6IjI4MyIsInRvZ2dsZSI6ZmFsc2V9") and paste it inside a  Custom Link menu item.

But it seems to not be working at all and in console you'll have the error:
`Uncaught Error: Syntax error, unrecognized expression: #elementor-action:action=popup:open settings=eyJpZCI6IjI4MyIsInRvZ2dsZSI6ZmFsc2V9`

**Comment by shilo-ey** [comment]
@dudaster 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

As for your question: you can still add a section of buttons/texts which will open your popups (don't use a menu to do it).

Thanks.

**Comment by iamparaic** [comment]
I don't want to create a new thread, but mega menu functionality would be awesome.
