### ISSUE TITLE
Popups using Safari

### ISSUE THREAD

**Issue by berardir** [pojome/elementor#6875]
Hello! Love the new popup feature, but I am having an issue. If I create my own (not using a predefined popup template), and drag a widget in (Accordion for example), it works fine on Chrome, but Safari looks bad. (I'm on a Mac)

I was hoping to use a popup as a navigation. Another issue I see with popups is that they do not get focus. Our website needs to be ADA 2.0 Compliant, so the end use needs to be able to navigate the website using the keyboard's Tab key - but the popup never gets focus, so I can not tab through the popup navigation options. Thanks for any help!

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
