### ISSUE TITLE
PHP warning above Products Widget after update

### ISSUE THREAD

**Issue by JoeDarko** [pojome/elementor#6877]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

After updating to the newest version of Elementor Pro there is a PHP warning above every Produsts Widget.

This is the warning:

"Warning: in_array() expects parameter 2 to be array, string given in /data/web/virtuals/201763/virtual/www/domains/topgrill.cz/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php on line 147"

## Steps to reproduce

- Update to the newest verison of Elementor PRO
- PHP warning apperas above every Produsts widget
- Revert to previous version of Elementor PRO and the warning is gone

Its happening on every single one of my Elementor Website. With or without other plugins, with default and other themes.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary></summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.6.41-84.1
	PHP Version: 7.1.26
	PHP Max Input Vars: 10000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://topgrill.cz
	Home URL: https://topgrill.cz
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: cs-CZ
	Timezone: Europe/Prague
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.2.1
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 2.4.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.1
		Author: Elementor.com

	GP Premium
		Version: 1.7.7
		Author: Tom Usborne

	Limit Login Attempts Reloaded
		Version: 2.7.1
		Author: wpchefgadget

	WooCommerce
		Version: 3.5.4
		Author: Automattic

== Log ==
	: 
Log: showing 8 of 82019-01-25 03:00:44 [info] elementor::elementor_updater Started 
2019-01-25 03:00:44 [info] Elementor/Upgrades - _v_2_3_0_widget_image Start  
2019-01-25 03:00:44 [info] Elementor/Upgrades - _v_2_3_0_widget_image Finished 
2019-01-25 03:00:44 [info] Elementor/Upgrades - _v_2_3_0_template_type Start  
2019-01-25 03:00:44 [info] Elementor/Upgrades - _v_2_3_0_template_type Finished 
2019-01-25 03:00:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.2.1',
  'to' => '2.4.4',
)]
2019-01-25 03:00:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.2.1',
  'to' => '2.4.4',
)]
2019-01-25 03:00:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.1.7',
  'to' => '2.4.1',
)]

PHP: showing 2 of 2PHP: 2019-01-25 03:02:14 [warning X 28][/data/web/virtuals/201763/virtual/www/domains/topgrill.cz/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php::147] in_array() expects parameter 2 to be array, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-01-25 03:18:13 [error X 1][/data/web/virtuals/201763/virtual/www/domains/topgrill.cz/wp-content/plugins/elementor/includes/editor.php::711] Allowed memory size of 134217728 bytes exhausted (tried to allocate 12034048 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

</details>

**Comment by JoeDarko** [comment]
Other people in the Elementor Community Facebook group are reporting the same problem. Please fix this.

**Comment by JoeDarko** [comment]
Ok, so it has been fixed right now. If anybody is having the same problem, just update to 2.4.2.

I'm really concerned about the lack of testing Elementor is doing before rolling out new updates. After any major update something basic always breaks. 

It seems like Elementor is operating on the basis of "Move fast and break things" like other startups, but when you have millions of users, maybe you should put much more effort into doing things more professionally.

**Comment by shilo-ey** [comment]
@JoeDarko 

We test our code manually and automatically, in addition we provide the core and the pro version for at least one week of beta each.

Join our beta community if you want to make an impact.

Glad the issue resolved.

Thanks.
