### ISSUE TITLE
Feature Request: Turn off Elementor canvas

### ISSUE THREAD

**Issue by joelbuckland** [pojome/elementor#6883]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Not every theme needs Elementor Canvas and Elementor Full Width. For the theme I use they just make the Page Attributes dropdown menu cluttered.  

**Describe the solution you'd like**
Can these be turned into options that people turn on rather than are there by default? Or at least a way to filter them out of the dropdown menu. This would make some themes much easier to use. 

**Describe alternatives you've considered**
The only alternative people seem to suggest is stopping users having access to page editing or the page attribute menu completely which removes a lot of useful functionality.

**Comment by bainternet** [comment]
@joelbuckland 	

The templates are added via filters which means they can be removed using the same filters, ex:

```PHP
function remove_elementor_page_templates( $page_templates, $wp_theme, $post ) {
	foreach ( $page_templates as $file => $name ) {
		if ( in_array( $file, [ 'elementor_canvas', 'elementor_header_footer' ] ) ) {
			unset( $page_templates[ $file ] );
		}
	}
	return $page_templates;
}
foreach ( [ 'page', 'post' ] as $post_type ) {
	add_filter( "theme_{$post_type}_templates", 'remove_elementor_page_templates', 20, 3 );
}
```
