### ISSUE TITLE
Newest Version of Elementor & Elementor Pro, makes a gap between Header and Section Below it

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#6884]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Newest Version of Elementor & Elementor Pro, makes a gap between Header and Section Below it

Our Site:
https://bit.ly/2JyZzaK

## Steps to reproduce
Install Elementor Pro
Install Elementor
Install Woo Storefront Theme
Create Elementor Header
Apply Header to a Page
See gap in between Header and section below it

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.0.0
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.14-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Storefront
	Version: 2.4.2
	Author: Automattic
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	CSS Hero
		Version: 3.2
		Author: The CSS Hero Team

	Elementor
		Version: 2.4.4
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.2
		Author: Elementor.com

	GPL Kit
		Version: 2.0.0
		Author: GPL Kit

	Groups
		Version: 2.5.0
		Author: itthinx

	Groups WooCommerce
		Version: 1.13.0
		Author: itthinx

	If Menu - Visibility control for menu items
		Version: 0.12.2
		Author: Layered

	Mailchimp for WooCommerce
		Version: 2.1.12
		Author: Mailchimp

	Responsive Menu Pro
		Version: 3.1.18
		Author: Peter Featherstone

	Safe SVG
		Version: 1.9.0
		Author: Daryll Doyle

	Storefront Powerpack
		Version: 1.4.13
		Author: WooCommerce

	Tidio Chat
		Version: 3.4.0
		Author: Tidio Ltd.

	WooCommerce
		Version: 3.5.4
		Author: Automattic

	WooCommerce Additional Variation Images
		Version: 1.7.13
		Author: WooCommerce

	WooCommerce Admin Custom Order Fields
		Version: 1.11.2
		Author: SkyVerge

	WooCommerce Bookings
		Version: 1.12.2
		Author: Automattic

	WooCommerce Frontend Manager
		Version: 5.3.1
		Author: WC Lovers

	WooCommerce Frontend Manager - Analytics
		Version: 1.2.1
		Author: WC Lovers

	WooCommerce Frontend Manager - Groups & Staffs
		Version: 3.1.3
		Author: WC Lovers

	WooCommerce Frontend Manager - Product Hub
		Version: 1.0.1
		Author: WC Lovers

	WooCommerce Frontend Manager - Ultimate
		Version: 5.2.8
		Author: WC Lovers

	WooCommerce Google Analytics Pro
		Version: 1.6.4
		Author: SkyVerge

	WooCommerce Multivendor Marketplace
		Version: 2.1.1
		Author: WC Lovers

	WooCommerce Multivendor Membership
		Version: 2.3.2
		Author: WC Lovers

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.6
		Author: WooCommerce

	WooCommerce Product Add-ons
		Version: 3.0.5
		Author: WooCommerce

	WooCommerce Services
		Version: 1.18.0
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.14
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 2.4.7
		Author: Prospress Inc.

	WooCommerce Variation Swatches and Photos
		Version: 3.0.11
		Author: Lucas Stark

	WP Job Manager
		Version: 1.32.0
		Author: Automattic

	WP Job Manager - Resume Manager
		Version: 1.17.0
		Author: Automattic

	WPS Hide Login
		Version: 1.5.2.1
		Author: WPServeur, NicolasKulka, tabrisrp

	YITH WooCommerce Ajax Product Filter Premium
		Version: 3.6.2
		Author: YITH

	YITH WooCommerce Ajax Search Premium
		Version: 1.6.5
		Author: YITH

	YITH WooCommerce Category Accordion Premium
		Version: 1.0.24
		Author: YITH

	Yoast SEO: Local
		Version: 9.5
		Author: Team Yoast and Arjan Snaterse

	Yoast SEO Premium
		Version: 9.5
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Log ==
	: 
Log: showing 3 of 32019-01-25 08:11:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.4',
)]
2019-01-25 08:11:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]
2019-01-25 08:12:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.2',
)]

**Comment by smile00000** [comment]
K great thanks.

**Comment by shilo-ey** [comment]
@smile00000 
This issue has been fixed in v2.4.5 
Feel free to update.

Thanks.

**Comment by smile00000** [comment]
@shilo-ey thank you it worked! = )
