### ISSUE TITLE
Missing YouTube and Instagram Share Buttons

### ISSUE THREAD

**Issue by TerenceMilbourn** [pojome/elementor#6885]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Share Buttons do not include the "YouTube" and "Instagram" networks and there's no simple way to add them when there's no built-in functionality for adding my own?

**Describe the solution you'd like**

Please add YouTube plus Instagram networks to the Share Buttons and also a way to add any new ones, or any you've not thought of, in the future.

**Describe alternatives you've considered**
None, its back to you.

**Additional context**
Everybody else does!

**Comment by shilo-ey** [comment]
Hi @TerenceMilbourn ,

Thanks for your feedback.

Please describe what is "Share" options for YouTube? for Instagram?
Can you please refer me to their API?

Waiting to hear from you soon,

Thanks.

**Comment by TerenceMilbourn** [comment]
Sorry, I should have made that clearer. 

I was talking about the missing networks on the Elementor "Share Buttons" widget.

**Comment by shilo-ey** [comment]
[**@TerenceMilbourn**](https://github.com/TerenceMilbourn) commented on [Jan 28, 2019, 12:06 AM GMT+2](https://github.com/pojome/elementor/issues/6885#issuecomment-457958700 "2019-01-27T22:06:46Z - Replied by Github Reply Comments"):
> Sorry, I should have made that clearer. 
> 
> I was talking about the missing networks on the Elementor "Share Buttons" widget.

There are no sharing options for Instagram and YouTube. 
The only way to share posts/images/videos is from the apps directly.

Thanks.
