### ISSUE TITLE
Feature Request : Need Sendy integration in forms

### ISSUE THREAD

**Issue by blackgoku** [pojome/elementor#6886]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

**What problem is your feature request going to solve? Please describe.**
A direct Sendy Integration will cause ease to connect Elementor form with Cheapest Mailing System called Sendy. Many People use Sendy and are using Elementor also, So this features is most awaited one.

**Describe the solution you'd like**
A option to add Sendy API directly to Elementor and a option to add new subscribers directly from Elementor form to Sendy's list.

**Describe alternatives you've considered** 
There are 2 alternatives but are not profitable or applicable for many elementor users.
1) Using Mailoptin, but mailoptin cost $199 yearly and its not worth to spend so much just for integration.
2) Adding codes, but mostly all elementor users have bought elementor due to lack of codinf knowledge. So its not feasible for many of us.

**Comment by jim2564** [comment]
Yes, this would be great. I have a bunch of client's using Sendy (besides myself). I'm keeping Beaver Builder installed for them, simply because all their optin-forms are connected to Sendy accounts (Beaver Builder has Sendy integration).

Please get Sendy API connected to Elementor.

Sendy's base is growing quickly (See https://sendy.co/)

**Comment by shilo-ey** [comment]
@blackgoku 
Thanks for your feedback.

We are looking into adding Sendy integration to our forms.
In the meanwhile, you can use the following custom code:

```PHP
add_action( 'elementor_pro/forms/new_record', function( $record, $this ) {
    //make sure its our form
    $form_name = $record->get_form_settings( 'form_name' );
    if ( 'MY_FORM_NAME' !== $form_name ) {
        return;
    }

    $fields = [
        'email' => $record->fields['email'],
        'list' => LIST_ID_HERE,
        'name' => $record->fields['name'],
    ];
	
	wp_remote_post( 'https://mydomain.com/sendy/subscribe', [
		'body' => $fields
	]);
}, 10, 2 ); 
```

Add this code to your themes `function.php` file and don't forget to change the `MY_FORM_NAME`, `LIST_ID_HERE` & `https://mydomain.com/` to your parameters.

Thanks.

**Comment by bainternet** [comment]
We've added an example to add Sendy as a form action integration https://developers.elementor.com/forms-api/custom-form-action/

**Comment by alexloganlee** [comment]
May I know if Sendy integration into Elementor is still ongoing? Or do we have to settle for the form action integration provided above?

**Comment by JoseSoteloCohen** [comment]
Hello guys!

This plugin should help you with sending submissions from Elementor Form to your Sendy lists.

https://wordpress.org/plugins/inboundlatino-sendy-elements/

**Comment by Paras16699** [comment]
@JoseSoteloCohen, thanks a lot for building this integration plugin. Much appreciated.

**Comment by juliankauai** [comment]
Thanks Jose, woirks great! All the best.

**Comment by collizo4sky** [comment]
You could use MailOptin to connect Elementor form to Sendy. See https://mailoptin.io/article/elementor-form-integration/
