### ISSUE TITLE
elementor blog template not showing featured image

### ISSUE THREAD

**Issue by Jeffery-777** [pojome/elementor#6887]
I used a blog post template to insert on a page and for many posts it isn't pulling the featured image. Strange enough, I'm noticing it seems to work when there is nothing much written in the post, but otherwise the image doesn't appear.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
