### ISSUE TITLE
Feature Request: Dynamic Charts

### ISSUE THREAD

**Issue by nunom4chado** [pojome/elementor#6888]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The ability to create dynamic charts on posts/custom_posts.

**Describe the solution you'd like**
It would be very nice to have an integration with Google Charts and pull data from ACF to populate it. The process might be like this:
* Create multipe Custom Fields on post (type number)
* Go to Post Template
* Drag chart widget to post
* On Layout: Chose type of chart (eg: pie)
* On Content: Add Value (with that dynamic option on top right). Bellow that, an option to add another value.

**Describe alternatives you've considered**
I believe there is no alternative at this moment. There are some plugins that work with elementor but they all have static data and they are not suitable for posts.

**Additional context**
About the data required to populate the chart, it need 2 values like the example bellow:

```
var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Work',     11],
          ['Eat',      2],
          ['Commute',  2],
          ['Watch TV', 2],
          ['Sleep',    7]
        ]);
```
I dont know if it's possible to fill the task column with the field name automaticly but that would be great. If not, manually adding it when creating the chart would be fine.

Also an option to hide the "row" if its falsy.

**Comment by shilo-ey** [comment]
Hi @nunom4chado ,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by ppeeryw** [comment]
+1 for this feature
