### ISSUE TITLE
Feature Request: Responsive look of the backend.

### ISSUE THREAD

**Issue by taminoferrari** [pojome/elementor#6891]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elements of elementor which are hidden on certain device views should not be displayed in the backend for the hidden device views. Before I used elementor I was using webflow and it was a big advantage that I could see how the page looks on the front by using the backend. At the moment I can see many duplicate elements in the backend of elementor just because I want to hide some for certain devices in order to show the right size for each device.

**Describe the solution you'd like**
If elements are hidden for certain devices they should also be hidden in the backend for certain devices too. One could either use the navigator to find the hidden items or change to other device views in the backend.

**Comment by shilo-ey** [comment]
@taminoferrari 

This is available in Elementor using preview mode (click on the collapse button to close the panel)
![image](https://user-images.githubusercontent.com/45009641/51801211-6ab65c00-2243-11e9-893d-d03b33e1e718.png)

**Comment by taminoferrari** [comment]
Ok great. I did not know that. Thank you for the fast response.

**Comment by SherrMark** [comment]
Hi,

Unfortunately this does not appear to be working for me.  If I make an element display only in mobile responsive state and then collapse the panel the mobile element still displays even when in desktop responsive mode

Likewise any elements set to only display in mobile mode still appear with the panel collapsed when in desktop mode of the editor

The editor window also states this to be the case

_"Attention: The display settings (show/hide for mobile, tablet or desktop) will only take effect once you are on the preview or live page, and not while you're in editing mode in Elementor."_

Can you advise whether this should actually be working and if so why it appears to not be the case (as advised by the accompanying text)

Another request would be to have the elements that should not be visible in the currently responsive state faded out with say a 20% opacity and maybe highlighted with a thin border in a colour to accompany the responsive state or have the column / row mouse-over border a different colour per state

For example, if I have elements set to only display on mobile and I am in desktop mode then the mobile only elements should be faded out (i.e. 20% opacity) and if I then mouse over them the column / row border would be in a different colour to quickly / visually identify the responsive state without having to select the item and expand the 'Advanced' tab

Please let me know if this does not make sense as I can put together some example images to show what I am referring to
