### ISSUE TITLE
[Feature Request] Change featured image on hover

### ISSUE THREAD

**Issue by Tony0892** [pojome/elementor#6893]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm trying to change the featured image on hover while displaying the posts widget(pro). 

**Describe the solution you'd like**
One way would be to allow for a second featured image to be inserted on the posts page. Then with an checkbox to enable the second image.

Or allow for an option that uses a gallery of 2 images, and use those to display 2 images on the posts widgets

**Describe alternatives you've considered**
There are none that I know off.

**Additional context**
None.

**Comment by shilo-ey** [comment]
I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
