### ISSUE TITLE
How to set select control option text instead of value as repeater title_field?

### ISSUE THREAD

**Issue by Peyovski** [pojome/elementor#6895]
I have a repeater control with a select sub-control that has several options listed. When I set the select sub-control as the repeater title_field, it displays the selected option value which of course is not a suitable title for the repeater item.

For example, the select control loads a list of pages with the page ID as select option value, and page title as select option text, if I set the field as a repeater title_field, the page ID is displayed, but I want the page title to be displayed.

How can I set a select control option text to show up as repeater title_field?

**Comment by shilo-ey** [comment]
@Peyovski 
Thanks for the feedback, 

We do not support this option.

thanks.
