### ISSUE TITLE
How can I fix 500 Internal Server Error in Elementor? (I cannot save the page)

### ISSUE THREAD

**Issue by nestorplatito** [pojome/elementor#6901]
The save page button in Elementor is not working because of 500 Internal Server Error. How can I fix this problem. Please help me.

[https://mega.nz/#!ra53yQ7b!pVLHQFaPYfNxZN1Eb8J4jb0XoUPJs3BB2rdvyrXwKMk](url)

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


As for your question please [visit our documentation](https://docs.elementor.com/article/300-500-error-while-using-elementor)

thanks.
