### ISSUE TITLE
Add New Popup Trigger on Woo Add to Cart button

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#6904]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
As written in the title. Such a trigger would allow us to make a popup to let user know the addition has happened, show him additional info or advice what to do next (continue shopping / go to cart). Ideally it should work both for ajax and non-ajax buttons, both for Elementor and Woo native buttons. 
It would solve one of the big drawbacks of WooCommerce.

**Describe alternatives you've considered**
There are some plugins for that, but mostly payed, and available only for ajax butttons. So why not to use this big new popup feature of Elementor for that. The "only" thing needed is the trigger. ;-)

**Additional context**
Here is the example from OceanWP Woo Popup
![woo-popup-screen](https://user-images.githubusercontent.com/5634870/51840220-c2b89580-230b-11e9-8452-5b9737eff15e.png)

**Comment by shilo-ey** [comment]
I merged this issue with  #6899 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by zeinnicholas** [comment]
+1

**Comment by ahplx** [comment]
+1
