### ISSUE TITLE
Warning: array_flip(): Can only flip STRING and INTEGER values!

### ISSUE THREAD

**Issue by ferrari-ra** [pojome/elementor#6905]
Hello! After updating the Elementor in my wordpress appeared this error message:

Warning: array_flip(): Can only flip STRING and INTEGER values! in /home/storage/1/4e/7c/grafite02/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/class-wpdev-notices.php on line 430

How to solve this problem?

Tks

**Comment by wayheming** [comment]
@ferrari-ra The error is not in Elementor files but in Essential addons plugin files. Try contacting the developers of the plugin.

**Comment by ferrari-ra** [comment]
Thanks for helping!
