### ISSUE TITLE
desktop layout in Elementor is only changing if i edit my website in tablet mode

### ISSUE THREAD

**Issue by jpiscool** [pojome/elementor#6908]
desktop layout in Elementor is only changing if i edit my website in tablet mode

**Comment by jpiscool** [comment]
now i can't edit anything,

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.
