### ISSUE TITLE
Use shortcode to trigger pop up embedded on page

### ISSUE THREAD

**Issue by qwik3r** [pojome/elementor#6914]
**What problem is your feature request going to solve? Please describe.**
The shortcode for pop up does not work if embedded on a page

**Describe the solution you'd like**
A pop up has as shortcode, therefore you should be able to override any display conditions if the pop up is embedded on a page and have it automatically load if desired. 

**Additional context**
I have other 3rd party plugins (membership plugins for instance) that offer short code if statements. Being able to use those in conjunction with embedding a shortcode in between them for a pop up would make the pop up feature more useful.

**Comment by bainternet** [comment]
The shortcode is a template shortcode, which means you can embed the content of the popup, not the actual popup or triggers/conditions.

thanks.

**Comment by qwik3r** [comment]
Not sure why this was closed. It's a legitimate feature request. Being able to embed a pop up on a page and have it automatically trigger would be useful. I even provided context in which the use case would be applicable...
