### ISSUE TITLE
Cloudinary Integration

### ISSUE THREAD

**Issue by smafilm** [pojome/elementor#6915]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I do my content management through Cloudinary and not through Wordpress.

**Describe the solution you'd like**
I would like Cloudinary integration with Elementor so I can select embed images from that gallery and/or simply assign the cloud url.

**Describe alternatives you've considered**
I'd rather not. I really like Cloudinary. Currently I duplicate my efforts by uploading again to Wordpress. It's kind of annoying.

**Additional context**
https://cloudinary.com

**Comment by shilo-ey** [comment]
I merged this issue with  #413, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
