### ISSUE TITLE
Video widget: Play video automatically when you add a play button

### ISSUE THREAD

**Issue by qwik3r** [pojome/elementor#6916]
**What problem is your feature request going to solve? Please describe.**
When you add a play button to a video as an overlay clicking it just reveals the video and does not automatically play it

**Describe the solution you'd like**
Automatically play video once you click the play button. 

**Describe alternatives you've considered**
Ultimate Addons for Elementor's video widget does this by default

**Comment by shilo-ey** [comment]
Hi @qwik3r 

This is the behavior that is applied, but due to [Google autoplay policy changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) the websites that will play autoplay websites are only the ones with high media engagement score.

Thanks.

**Comment by qwik3r** [comment]
> Hi @qwik3r
> 
> This is the behavior that is applied, but due to [Google autoplay policy changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) the websites that will play autoplay websites are only the ones with high media engagement score.
> 
> Thanks.

This isn't about auto play... it's about playing when you click the actual play button.

**Comment by shilo-ey** [comment]
The autoplay function is connected to the play button when having an overlay.
If your websites media engagement score would be higher, it would work for you.

Thanks.

**Comment by qwik3r** [comment]
Media engagement score? This very same functionality works with Ultimate Elementor Addons, a 3rd party plugin. So why does it not work with Elementor out of the box? Why would the 3rd party plugin work and not yours if my "media engagement score" had anything to do with it?

**Comment by nickmadedesign** [comment]
@qwik3r It depends on the video, I think. Autoplay isn't purely related to your media engagement score, so I'm not sure why that's suggested (as shown in the linked article). A video set to play on gesture/user action regardless of audio should play automatically.

I'm not sure why one works and the other doesn't. Do you have a public facing link?

**Comment by qwik3r** [comment]
That's where I think there might be some confusion. I never said anything about auto play, that implies you land on the page and the video plays. I said that when you click the play button on the overlay (icon/image whatever) it does not initiate playing the video. I've experienced this with vimeo videos. However the 3rd party plugin I mentioned DOES initiate the play back. So to me, it sounds like it's a or some odd reason why it was left out.

**Comment by nickmadedesign** [comment]
> That's where I think there might be some confusion. I never said anything about auto play, that implies you land on the page and the video plays. I said that when you click the play button on the overlay (icon/image whatever) it does not initiate playing the video. I've experienced this with vimeo videos. However the 3rd party plugin I mentioned DOES initiate the play back. So to me, it sounds like it's a or some odd reason why it was left out.

Ah yes,  I added 'autoplay' because it's not entirely related to media engagement score. I agree whatever the trigger/listener that's attached to hitting the play overlay isn't firing.

There are some crossover quirks in general between this and autoplay, so I think it warrants a better look than a quick issue close but I digress.

**Comment by remytesta** [comment]
Ineed, it works with youtube but not for Vimeo. Is it possivle to have this feature in the next update ?
