### ISSUE TITLE
Use hover intent to display .editor-element-settings

### ISSUE THREAD

**Issue by FrankM1** [pojome/elementor#692]
The column and section icons disappear too quickly when editing or moving things. Sometimes it is hit and miss. Using a hoverintent or a mouseout delay would make selecting the edit tools much easier. 

![eb411584 8891 11e6 980a 97b8968d7ad0 png 2798x1070](https://cloud.githubusercontent.com/assets/1177638/19124928/c8ced780-8b3d-11e6-84a5-15b18f73b0fe.png)

**Comment by FrankM1** [comment]
I've been experimenting with this and I've managed to make it work with the behaviour code below. 

`var EditToolsBehavior;

EditToolsBehavior = Marionette.Behavior.extend( {

    initialize: function() {
        this.listenTo( builder.channels.dataEditMode, 'switch', this.onEditModeSwitched );
    },

    onEditModeSwitched: function() {
        var activeMode = builder.channels.dataEditMode.request( 'activeMode' );
        this.view.$el.removeClass( 'builder-element-overlay-active', 'preview' === activeMode );
    },

    handleHover: function() {

        var $this = this;

        var hoverConfig = {
            sensitivity: 1, // number = sensitivity threshold (must be 1 or higher)
            interval: 10, // number = milliseconds for onMouseOver polling interval
            timeout: 500, // number = milliseconds delay before onMouseOut
            over: function() {
                $this.view.$el.addClass( 'builder-element-tools-active' );
            },
            out: function() {
                $this.view.$el.removeClass( 'builder-element-tools-active' );
            }
        };

        $this.view.$el.hoverIntent(hoverConfig);

    },

    onRender: function() {
        this.onEditModeSwitched();
        this.handleHover();
    }
} );

module.exports = EditToolsBehavior;
`

I can make a pull request with the full code if you wish.

**Comment by arielk** [comment]
I close this issue, because in the new version of Elementor (1.5) we have improved the whole interface of the editor, and now there is no need for this enhancement.

Thanks for your feedback!
