### ISSUE TITLE
[Feature Request] Dynamic color using custom fields

### ISSUE THREAD

**Issue by papilia** [pojome/elementor#6923]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The problem is giving the possibility to the final client to select which color a specific text, an icon or a background should show.

**Describe the solution you'd like**
Simply, add the dynamic color feature on color selection in Elementor editing mode, so the final client can select also colors from backend using ACF, Pods and so on without touching the template in Elementor.

I.e.: in this situation. where i'm showing a color picker, this exact color should appear in all texts and some backgrounds of this specific page. But, every page has its own color. I would like to be able to leave the client only to select these colors from backend

BACKEND:
![image](https://user-images.githubusercontent.com/9718447/51996193-8e340d80-24b4-11e9-93fd-3e8aa0778c22.png)

PAGE 1:
![image](https://user-images.githubusercontent.com/9718447/51996413-f125a480-24b4-11e9-8f84-423bfb084f4a.png)

PAGE 2: Same template, with shared blocks, but only different color.
![image](https://user-images.githubusercontent.com/9718447/51996356-d6ebc680-24b4-11e9-800c-90f15f1d4e6d.png)

**Comment by shilo-ey** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

ref #6485 

Thanks for the feedback.

**Comment by philmatt** [comment]
+1

I just paid for Elementor, expecting this to be integrated. This is essential to create a full template in conjunction with ACF

**Comment by erzawansyah** [comment]
+1
This feature would be very useful. I 'll be waiting for this feature...

**Comment by hi0ctane** [comment]
+1 this would be amazing

**Comment by darkben** [comment]
+1 please !

**Comment by nebaon** [comment]
Should be a given i think.

**Comment by fracii** [comment]
+1

**Comment by fracii** [comment]
Can Elementor team open this again? I think its a really useful function regarding Dynamic content. Be one step ahead to Divi etc.

**Comment by fredarend** [comment]
+1 please !
This is essential!!!!

**Comment by mak5imov** [comment]
+1

**Comment by valentincauro** [comment]
+1

**Comment by rogeriobeatz** [comment]
+1 !

This feature will decrease php customizations into Elementor core files.

**Comment by Lokavidu** [comment]
+1 definitely!

**Comment by fxaviers** [comment]
+1
And I'd like to know why it's closed, since it's a feature request, not implemented and with multiple "+1".

**Comment by flick-soft** [comment]
+1 !!!

**Comment by black-eye** [comment]
+1

**Comment by mdegembe** [comment]
+1

**Comment by aidanweltner** [comment]
+1 
I would love this! Would make life so much easier.

**Comment by yonifre** [comment]
+1
Needed!

**Comment by fvenuto** [comment]
+1!

**Comment by pise17** [comment]
+1

**Comment by stijnvanouplines** [comment]
Ok, this is a very dirty fix but it works 😅

Add a 'Shortcode' widget to your page or template and wrap your shortcode into the following code:

```
<style type="text/css">
.element-to-style {
   background-color: [my_shortcode field="color"];
}
</style>
```

Let's say you want the background color of a column to change (assuming you're using ACF and you've named your field 'color'):
```
<style type="text/css">
.elementor-123 .elementor-element.elementor-element-b9b3a8f:not(.elementor-motion-effects-element-type-background) > .elementor-element-populated, .elementor-123 .elementor-element.elementor-element-b9b3a8f > .elementor-column-wrap > .elementor-motion-effects-container > .elementor-motion-effects-layer {
    background-color: [acf field="color"];
}
</style>
```

**Comment by DIntriglia** [comment]
+1 Would be interested to see if someone could do a pull request for this. I might look into developing it if Elementor does not comment on this issue soon.

**Comment by realspiner** [comment]
> Ok, this is a very dirty fix but it works 😅
> 
> Add a 'Shortcode' widget to your page or template and wrap your shortcode into the following code:
> 
> ```
> <style type="text/css">
> .element-to-style {
>    background-color: [my_shortcode field="color"];
> }
> </style>
> ```
> 
> Let's say you want the background color of a column to change (assuming you're using ACF and you've named your field 'color'):
> 
> ```
> <style type="text/css">
> .elementor-123 .elementor-element.elementor-element-b9b3a8f:not(.elementor-motion-effects-element-type-background) > .elementor-element-populated, .elementor-123 .elementor-element.elementor-element-b9b3a8f > .elementor-column-wrap > .elementor-motion-effects-container > .elementor-motion-effects-layer {
>     background-color: [acf field="color"];
> }
> </style>
> ```

How do you "wrap" this into css code? I've tried by using the "html" widget, which sort of works when you're logged into wordpress. But when you log out it just prints out the css on the front end...

**Comment by realspiner** [comment]
@stijnvanouplines could you elaborate?

**Comment by stijnvanouplines** [comment]
> @stijnvanouplines could you elaborate?

You should use the 'Shortcode' widget.

**Comment by realspiner** [comment]
and add the html into the shortcode widget too?

**Comment by realspiner** [comment]
yes, tried it and it works! :-)

**Comment by tollube** [comment]
+1

**Comment by realspiner** [comment]
Doesn't seem to work anymore since latest update of Elementor... :-(

**Comment by kotfarepra** [comment]
+1 to have a color picker

**Comment by PwrSrg** [comment]
+1

**Comment by mat-rgm** [comment]
+1

**Comment by chloeford0** [comment]
+1 for dynamic color picker

**Comment by philmatt** [comment]
+1 _again_

**Comment by Andrea-InfinityWeb** [comment]
+1

**Comment by hcporto** [comment]
+1

**Comment by satomiao** [comment]
+1, I need this feature too.

**Comment by PixelPerfect-dot** [comment]
How is this still not a thing? Definitely needs to be implemented.

**Comment by oceandiveloper** [comment]
+1, I could really need this right now. I wish Elementor was focusing more on improving their existing functionality/user experience and providing more creative power to developers by making as many Elementor options as possible dynamic.

**Comment by pascal-parent-za** [comment]
This would be useful

**Comment by bnruane** [comment]
+1 Please add this ASAP

**Comment by manaka02** [comment]
+1

**Comment by tinocash** [comment]
+1

**Comment by joseantonnio** [comment]
+1

**Comment by darrillouie** [comment]
+1
nice to have to match ACF color picker field

**Comment by beleancristian** [comment]
+1
Please try and implement this. Thanks.

**Comment by nfischer83** [comment]
+1 please!!!

**Comment by meoled** [comment]
+1 - I especially registered here so I can +1 this request. It would be very much needed for a project.

**Comment by eSkimoweb** [comment]
Hey, Where am I wrong?

With the latest **Elementor PRO** update, I get the dynamic color option with ACF, GREAT!

It does everything great for live viewing.

But when I want to change the page as an administrator, the menu doesn't show colors.

Where am I making this mistake?

Please view video:
https://www.loom.com/share/e3348034b9a14ae3a09caacafc4a8d0c

**Comment by fippy** [comment]
+1 Integration with ACF Color picker does not give option to pull elementor color picker (to access saved color palette)

**Comment by studio-matavai** [comment]
+1 // Just add "acf select" to the dynamic color option, so we could use selectors to setup the color palette in the backoffice, like :
#000000 : black
#FFFFFF  : white 
...

**Comment by horizzons** [comment]
> Hey, Where am I wrong?
> 
> With the latest **Elementor PRO** update, I get the dynamic color option with ACF, GREAT!
> 
> It does everything great for live viewing.
> 
> But when I want to change the page as an administrator, the menu doesn't show colors.
> 
> Where am I making this mistake?
> 
> Please view video:
> https://www.loom.com/share/e3348034b9a14ae3a09caacafc4a8d0c

I have exactly the same problem. After working in my platform for some months I realised that currently dynamic color tags are useless, because I can't work in the backend with elementor considering that section backgrounds do not save / update ACF color picker field values.
