### ISSUE TITLE
Lazy Load for content

### ISSUE THREAD

**Issue by jasonb4u** [pojome/elementor#6924]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Lazy Load for Content

**Describe the solution you'd like**
Elementor can add feature to select lazyload for content!

**Describe alternatives you've considered**
other plugins, not a fan of always using other plugins to do a job when I know Elementor could add this feature

**Comment by shilo-ey** [comment]
Hi @jasonb4u ,

What do you mean by content?
Texts?

thanks

**Comment by jasonb4u** [comment]
Images, Text, widgets etc!
"Content" means anything on the website!

**Comment by shilo-ey** [comment]
@jasonb4u 

Thanks for the clarification.

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks.

**Comment by jasonb4u** [comment]
Why is this closed .

You said if theres a demand for it.  Correct me if I'm wrong, but doesnt Google demand are websites are optimized to the max for better speed and load results correct yes!

So theres your demand for it already, by the biggest search on the planet, GOOGLE wants us to have great sites and so do I, so this means YES there is a huge demand for it.

Seem yr response was lazy in saying you guys are not interested in going that extra further step to make it better!
