### ISSUE TITLE
[Feature Request] Nav Menu Missing Background Color for Normal Tab

### ISSUE THREAD

**Issue by WebMagi** [pojome/elementor#6927]
- [x] I have searched for similar features requests in both open and closed tickets and found a duplicate closed ticket (#6027), but it was closed prematurely - perhaps based on a limited view of what should be possible for this feature? Please read this feature request in its entirety!
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The problem is that Elementor does not have the ability to design menu systems with background colors for the "Normal" state of individual menu button items. With this limitation in place, Elementor can only do a very basic look and feel for the top "Normal" menu state, with the background being provided for the entire bar (under Advanced), rather than for each individual button item.

**Describe the solution you'd like**
What I'd like is the ability to build any menu system I can imagine - which includes a tabbed menu such as this: https://webmagi.com/clients/ufs/ . This site was built with Elementor Pro, but I had to hack the CSS to get the tabbed look for the menu items that the client requested.

Issue [6027](https://github.com/pojome/elementor/issues/6027) has the precise screenshots where this feature is missing. The Normal tab should have its own "Background Color", which would allow individual button items to have a background color for their "Normal State", just like they do for their "Hover" & "Active" states. This is greatly needed!

**Describe alternatives you've considered**
The only alternative at this time is to hack the CSS for each individual menu item, like so:

`.menu-item-658 {
    background-color: #14682f !important;
    border-radius: 8px 8px 0px 0px !important;
}
.menu-item-658:hover {
    background-color: #228642 !important;
}`

**Additional context**
Elementor support recommended this solution:

`.elementor-nav-menu--main .elementor-item {background-color:#169AFF!important;}`

... but if you have a secondary menu (in the footer or sidebar), then that too would use the same color changes added to "Custom CSS". So this solution has very limited use cases.

**Comment by shilo-ey** [comment]
@WebMagi 

You can target your specific main menu with adding a custom attribute to the nav menu. [read more about it here](https://docs.elementor.com/article/445-custom-attributes) (eg. `id|main-menu`).

I merged this issue with  #3275, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
