### ISSUE TITLE
Single post tags

### ISSUE THREAD

**Issue by orisica** [pojome/elementor#6928]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor Pro currently does not have a way to display WordPress tags at the end of posts. I find it very strange and frustrating that there is no support for such a fundamental WordPress feature.

**Describe the solution you'd like**
Please add a widget which displays tags, it is very simple to add since it's built into WordPress and many bloggers will appreciate it.

**Describe alternatives you've considered**
Workaround is to manually add and link tags but its a waste of time and hard to manage.

Thanks in advance!

**Comment by shilo-ey** [comment]
Hi @orisica ,

We DO have support for this:
![image](https://user-images.githubusercontent.com/45009641/52051968-c6dbf180-255d-11e9-8581-51bbce86dac3.png)

Use "Post Info" Widget inside the post template > Select Terms > Tags.

**Comment by networking-web** [comment]
The problem with tag formatting is very limited.
In the **Atlanta format**, the design is that each tag is displayed in a separate button, and in Elementor there is no such display.
But rather - the tags are separated by a comma.
I would be happy to help you change the display of the tags.
**Thank you very much, champions**

**Comment by easinwebpro** [comment]
> Hi @orisica ,
> 
> We DO have support for this: ![image](https://user-images.githubusercontent.com/45009641/52051968-c6dbf180-255d-11e9-8581-51bbce86dac3.png)
> 
> Use "Post Info" Widget inside the post template > Select Terms > Tags.

Cool

**Comment by Bruck-3** [comment]
I wanted to add a category/term meta tag to a post. Does Elementor have a feature for that?

**Comment by morgank-atl** [comment]
> I wanted to add a category/term meta tag to a post. Does Elementor have a feature for that?

Me too. I hate having to go back to the WP editor to do this.
