### ISSUE TITLE
Oasis Workflow support

### ISSUE THREAD

**Issue by dawidroz** [pojome/elementor#6929]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Oasis Workflow plugin compatibility. We can bypass the workflow by "Update" button in Elementor 

**Describe the solution you'd like**
I think that Elementor should check if Oasis Workflow is already installed, if yes - should check workflow settings and verify if the user has enough permission for publishing/saving

**Describe alternatives you've considered**

**Additional context**
Plugin: http://wordpress.org/plugins/oasis-workflow/

**Comment by bainternet** [comment]
@dawidroz 

We feel that this should be done on the 3rd party plugin side since that plugin is responsible for altering the publishing/updating flow.

thanks.
