### ISSUE TITLE
Text justify

### ISSUE THREAD

**Issue by orisica** [pojome/elementor#6930]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Global paragraph styling (justify) applies formatting to post headlines as well. It doesn't make sense and introduces display issues on mobile devices. Can you disable justifying of post headlines?

## Steps to reproduce
![2019-01-31_12-23-47](https://user-images.githubusercontent.com/42409471/52051718-9d6a9800-2554-11e9-8e4e-63673f362216.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Fresh WordPress installation with Elementor Pro.
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.


We simply can't replicate the described issue.

thanks.
