### ISSUE TITLE
Widget Layouts

### ISSUE THREAD

**Issue by jczeiger** [pojome/elementor#6933]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The widget layouts only give options for vertical section segments.   

**Describe the solution you'd like**
I would like to segment 3 sections with one larger section on either the left or right side, then two smaller sections on the adjacent side separated horizontally, similar to the options available on the Layout app for instagram.

**Describe alternatives you've considered**
I've only considered just using the widget layouts as they are available now, but if it is possible to get this update, it would be pretty rad. 

**Additional context**
See screenshots below illustrating request. 

![widget 1](https://user-images.githubusercontent.com/47221849/52071758-7c944980-2538-11e9-9a95-08070150ec49.png)

![widget 2](https://user-images.githubusercontent.com/47221849/52071775-8322c100-2538-11e9-9ff8-546fda9b643b.png)

**Comment by shilo-ey** [comment]
Hi @jczeiger 

Thanks for your feedback.

Elementor layout system works in a way that each section contains up to 100% of its width.

Therefore, if you want to add another column beneath it, just add the first one with two columns, and the other with one column.

Thanks.
