### ISSUE TITLE
Default Value for Elementor Forms Dynamic

### ISSUE THREAD

**Issue by donwattz1459** [pojome/elementor#6934]
I have a CPT called listings and a bunch of fields done with ACF assigned to the listing. One of them is a google address field for "address". I am using the elementor forms on a single post template. I looked at the textarea form field called message and i want the default value to be the ACF field "address". I assign it and it works in the editor but when I view the front end it doesn't show. So I go back to the editor and try to fix but then it doesn't show in the editor, but it is still assigned the ACF custom field...

Any thoughts on this?

![screen shot 2019-01-31 at 12 19 05 pm](https://user-images.githubusercontent.com/16137152/52072350-d0ac2780-2552-11e9-8dcb-b980c297e94a.png)

**Comment by bainternet** [comment]
@donwattz1459 

Thanks for reporting, should be fixed in the next version.

**Comment by shilo-ey** [comment]
Hi @donwattz1459 

This has been fixed in Elementor Pro 2.4.4.

Feel free to update!

Thanks.
