### ISSUE TITLE
"Button ID" for every widget with link to track clicks with Google Analytics and others

### ISSUE THREAD

**Issue by parfilov** [pojome/elementor#6935]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Now we have Button ID only in Button widget but often there are mass of things we need to track with GA besides buttons clicks:
- headings (phones and emails)
- pricing table button
- pricelist item
- slider
- flipbox
- list icon item (phones, emails, adresses)
- text/icon box
- etc...

**Describe the solution you'd like**
Here https://www.youtube.com/watch?v=wj5cBUCPp5U&t=557s I've shown the method to create a phone number and email using Button widget but it's "crutches". That would be great to have IDs for every link in Elementor.

Thank you for what you do!

**Comment by bainternet** [comment]
@parfilov 	

Adding more controls to every widget makes the panel crowded and we don't have control over every link in elementor ( 3rd party widgets...)

tracking can be done with:

* Analytics Enhanced Link Attribution: [ref](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-link-attribution#customizing_enhanced_link_attribution)
```JS
ga('require', 'linkid', {
  'cookieName': '_ela',
  'duration': 45,
  'levels': 5 // <== 5 should do it in most cases
});
```

* using GMT: [ref](https://developers.google.com/analytics/devguides/collection/gtagjs/enhanced-link-attribution)
```JS
gtag('config', 'GA_TRACKING_ID', {
  'link_attribution': {
    'cookie_name': '_gaela',
    'cookie_expires': 60,
    'levels': 5
  }
});
```

* Or manually:
```JS
jQuery( document ).ready(function( $ ){
	$( '#CSS_ID' ).on('click', function(){
		ga( 'send', 'event', 'button', 'click', 'blahblah' );
		// Or what ever other tracking or action you want on this event
	});
});
```
