### ISSUE TITLE
Media Carousel

### ISSUE THREAD

**Issue by sumel100** [pojome/elementor#6939]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Hey @sumel100 

If I get you correct - you already have this option in Elementor Pro:
![image](https://user-images.githubusercontent.com/45009641/52175113-59230600-27a7-11e9-8e7d-13793045d63e.png)

This way you can set the skin to "Slideshow" and the images will be underneath.

Thanks.
