### ISSUE TITLE
Extend or Override Widgets Elementor Pro ?

### ISSUE THREAD

**Issue by MatPain** [pojome/elementor#6941]
Hello,

I would like to extend the forms of Elementor Pro.

Not just only use the action or filter, i would like add new option opt-in.

In documentation, I can only use the API directly, nothing about extend of widget.

Thanks,

Cordially Mat.

**Comment by MatPain** [comment]
@bainternet 

An option "action" after the submit the form. I know how to hook it but i would like to add a new option with configuration inside the actuelly form in Elementor pro.

Thanks

**Comment by bainternet** [comment]
@MatPain 	

thanks for clearifing,

We've added an example to add Sendy as a form action integration https://developers.elementor.com/forms-api/custom-form-action/

**Comment by MatPain** [comment]
I dont know how i dont saw this page in your documentation.

Thanks you,
