### ISSUE TITLE
Make Elementor conditions more granular

### ISSUE THREAD

**Issue by dioxvi** [pojome/elementor#6944]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have a site with over 200 products. Every product is in one, two or three different categories or subcategories and the template for single product is basically the same for every product but there are some widget, some text boxes, some layout version I need to assign on particular product (more than one in several different subcategories) often based on tags but sometimes based on a combination of tags with a specific category or subcategory.

**Describe the solution you'd like**
A great thing would be the possibility to logically combine the conditions of including/excluding at least with the three basic logic operator AND, OR, NOT.

**Describe alternatives you've considered**
I've considered to make special tags that group combinations I need, use one of this in a product and then assign an Elementor single product template to a tag. (Currently my total combinations are 17 so I would have 17 special tags and 17 single product templates).

**Comment by bainternet** [comment]
@dioxvi 	

We are looking into a few directions, but it's not happening any time soon.

for now, I can only suggest you create a custom taxonomy (not tags) just for that and use it as a condition.

thanks for the feedback.

**Comment by dioxvi** [comment]
Ok, thanks.
I followed your tip but after creating a custom taxonomy, I can't see it over single product conditions. It's visible if I make a page, header or footer template.

I'm also sure that nav menu is visible even in front end and back end. Also I've linked my custom taxonomy to the post type "product". So, is there any snippet of code to extend the conditions filter to the linked taxonomy?
