### ISSUE TITLE
Background color percent bar mislocated

### ISSUE THREAD

**Issue by vsimon51** [pojome/elementor#6946]
Elementor 2.4.5
Background color percentage slider seems to have got itself mislocated vertically. Browser is Firefox - haven't checked on others.
![capture](https://user-images.githubusercontent.com/17190081/52133331-64f4b800-2641-11e9-87bc-a22db3c3e7e1.JPG)

**Comment by shilo-ey** [comment]
Hi @vsimon51 

We cannot reproduce your issue.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
