### ISSUE TITLE
Webhook Error and API integration with Snake Member (centralized sales and marketing system)

### ISSUE THREAD

**Issue by ZambraDesigner** [pojome/elementor#6950]
Hi Team, I ask for this integration because the WebHook function, although Snake Member supports its reception, does not seem to work.
It always comes out "Webhook Error - This message is not visible to site visitors. "

Here you can find the API documentation to register contacts to the campaigns: http://blog.snakemember.com/documentation/subscribe-user-to-a-campaign/

Snake Member is widely used in the Italian market and we are recommending Elementor to everyone for ease of use and reliability but we would like to avoid using Zapier.

More about Snake Member: https://www.snakemember.com/freetrial/?aff_id=820dfb

**Comment by bainternet** [comment]
@ZambraDesigner 

You can use a custom webhook to integrate with snakemember, ex:

```PHP
// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'MY_FORM_NAME' !== $form_name ) {
		return;
	}

	$raw_fields = $record->get( 'fields' );
	$fields = [
		'api_user' => 'YOUR_SNAKEMEMBER_API_USER',
		'api_key' => 'YOUR_API_KEY',
		'business_id' => 'YOUR_SNAKEMEMBER_PROJECT_ID',
		'listname' => 'YOUR_SNAKEMEMBER_CAMPAIGN_NAME',
	];

	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'https://areamembri.it/campaigns/subscribe.json', [
		'body' => $fields,
	] );
}, 10, 2 );
```

**Comment by ZambraDesigner** [comment]
Hi @bainternet , if I also want to send the visitor's IP address what can I do?
