### ISSUE TITLE
Global Widgets: Duplicate Visual Bug in Backend for Widget and Section in which widget is

### ISSUE THREAD

**Issue by djekanovic** [pojome/elementor#6951]
When you want to duplicate widget or section in which is the widget. It does not work in backend. Nothing happens. But if you preview in frontend its duplicated. Thats how i ended up with 20 same widgets trying to duplicate. :)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

We simply couldn't replicate this issue without further information.

Thanks
