### ISSUE TITLE
Usage of 'the_content' hook in template header of footer issue

### ISSUE THREAD

**Issue by dameer** [pojome/elementor#6952]
Scenario...

I'm using Twenty Nineteen child theme with modified "footer.php" template.

The change is that in WP Customizer you can optionally select to display either widgets section or a non-widgetized section that is supposed to render Elementor shortcode only.

So the chunk of code in footer looks like this:

```
...
$elem_sc = get_theme_mod( 'elem_shortcode', '' );
if( $show_widgets || '' == $elem_sc ) {
    get_template_part( 'template-parts/footer/footer', 'widgets' );
} else {
    echo apply_filters( 'the_content', $elem_sc );
}
...
```

Whenever the page built with Elementor is rendered in Browser, in place of the footer shortcode entire page is rendered once again. It's like having the same Elementor paged cloned in footer. The actual shortcode is ignored!

However, on all other pages which are not built with Elementor, footer shortcode gets rendered properly.

I tried to use
`echo do_shortcode( $elem_sc );`
instead of
` echo apply_filters( 'the_content', $elem_sc );`
...but all `<br />` tags are not stripped down and for instance "Social Icons" widget looks shitty.

**Comment by bainternet** [comment]
@dameer 	

Elementor Uses and relays on `the_content` filter heavily so you need to remove elementor's filter before you call `apply_filters( 'the_content', $elem_sc );`

ex:
```php
...
$elem_sc = get_theme_mod( 'elem_shortcode', '' );
if( $show_widgets || '' == $elem_sc ) {
    get_template_part( 'template-parts/footer/footer', 'widgets' );
} else {
	//remove elementor filters
    \Elementor\Plugin::instance()->frontend->remove_content_filter();
    echo apply_filters( 'the_content', $elem_sc );
	//restore elementor filters if needed down the page
    \Elementor\Plugin::instance()->frontend->add_content_filter();
}
...
```

thanks.

**Comment by dameer** [comment]
Whoops! Was celebrating to soon...

What you wrote above DOES work for shortcodes created by Elementor and "third party" when on frontend.

However, it doesn't work for Elementor shortcodes on Elementor page in edit mode!
For instance...
1. create Elementor section
2. insert that section via shortcode to site footer widget (WP's Text Widget)
3. create Elementor page
4. that Elementor page will be rendered in site footer once again, in place of the Elementor section shortcode

Hope it makes sense. I thought there's a counterpart of: 
`\Elementor\Plugin::instance()->frontend->remove_content_filter()`

...so, for the backend something like: 
`\Elementor\Plugin::instance()->backend->remove_content_filter()`

**Comment by BackuPs** [comment]
I have the same issue on the none static homepage calling a custom field and process that field by the content filter


`<?php echo apply_filters('the_content', stripslashes( $content ));?>`

This works ok until you create a post and edit and publish that post by elementor.

The moment that last post created is a elementor post the filter called above displays the content of the post and not the content parsed by  $content.

If i create a new post not using elementor its ok.  But it goes astray when the last post created is a elementor post.

The above workaround works but it looks like a bug as it only happens in a none static homepage. If i create a static homepage it does not happen at all.
