### ISSUE TITLE
display or hide on click

### ISSUE THREAD

**Issue by Zegklitz** [pojome/elementor#6954]
Hello, 

is it possible to built into Elementor some funcionality, that display or hide any object, for example, through ID or CLASS? For example, I would like to click on the button* in one section to display the entire other section, including its content, which would normally be hidden / or just some hidden content in a visible section

Something like jQuery('#X').click(function(){document.getElementById ("Y") style.visibility = "visible"; ...
or vice versa, but perhaps even in bulk for multiple IDs or classes? - By clicking on some obejct will show objects with different identifiers

*not just a buttons, but everything that has the possibility of some click function or hypertext.

Does what I have written makes sense to you?

**Comment by shilo-ey** [comment]
Hi @Zegklitz 

Thanks for your feedback.

First of, you can use custom JS code to show or hide some contents.
Second, we are looking into an overall solution for conditionals in Elementor.

You can also set a popup and trigger it by clicking on a button or a link anywhere in your website > [see more here](https://www.youtube.com/watch?v=_sJRHSmIpp8).

Thanks

**Comment by thomaswessler** [comment]
I found a solution for hiding and showing a div-section.
So the user can toggle between unvisible/visible.
(https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_toggle_hide_show)
But i have problems with the js-code in the html-code inside elementor: 
Everytime i open the elemtor-html-editor, in the specific code "<a href="#" onclick="myFunction()">Themen</a>" dissapears the part: onclick="myFunction()".
Please understand: it works fine but i have to insert it as new, if i open the editor to do some work init.
I will also post this issue.

**Comment by Zegklitz** [comment]
I am using this code anf it works fine:

<script>
document.addEventListener("DOMContentLoaded", function(event) { 
	jQuery('.ee-term--vodovody-a-kanalizace').click(function(){ 
	    document.getElementById("claim").style.backgroundImage = "url('http://zeg.cekuj.net/wp-content/uploads/2019/03/Vodovody.jpg')";
	    document.getElementById("claiminfo_uvod").style.display = "none";
        document.getElementById("claiminfo_vodovody_a_kanalizace").style.display = "block";
        document.getElementById("claiminfo_tunely_a_kolektory").style.display = "none";
        document.getElementById("claiminfo_statika_a_geotechnika").style.display = "none";
        document.getElementById("claiminfo_sanace_a_opravy_konstrukci").style.display = "none";
        document.getElementById("claiminfo_dopravni_stavby").style.display = "none";
	}); 
});
....
</script>

XY selector in jQuery('XY').click(function(){ ... can be everything and inside of this function you can hide or show also everything through other selectors (IDs or Classes or just tag's names).

This code above is part of the code from this website http://zeg.cekuj.net/referencni-projekty/ which change texts in the first row, whan clicking on filter below.

But I woluld still like to do this through Elementor builder settings, not by code.

**Comment by bentalgad** [comment]
+1

**Comment by flickdevs** [comment]
+1

**Comment by davidamarek** [comment]
+1

**Comment by developerahamed** [comment]
Elementor Pro can be added to each widget as CSS. I mean JavaScript can be added that way? If there are any options, please let me know.

**Comment by bentalgad** [comment]
This is so simple to add and would add to elementor so much.

**Comment by troytoon** [comment]
To show hide a section you can use the html widget with some javascript and CSS. Try this tutorial.
https://wpjunction.net/elementor-show-hide-sections/
