### ISSUE TITLE
Trigger pop up from cookie

### ISSUE THREAD

**Issue by qwik3r** [pojome/elementor#6955]
**What problem is your feature request going to solve? Please describe.**
Ability to trigger a pop up from a cookie

**Describe the solution you'd like**
When you configure conditions for a pop up, one should be to configure based on a valid cookie

#

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

I merged this issue with  #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by chrivand** [comment]
any newsa on this?
