### ISSUE TITLE
Form API: Submit form to Webhook

### ISSUE THREAD

**Issue by yeshansachithak** [pojome/elementor#6956]
Hi Guys,
I'm using Elementor Pro to build my custom form. Now I need to submit the Form to Webhook then I can do other functions as per my requirement. I tried to contact premium support and they asked me to post the question here in Github. Also, I have post the same in Facebook community. But no one replied to me. However, I tried few things but nothing works for me. I'm using WordPress Hello Theme. 

**Attempt 01** 
As per Forms API documentation I used below sample code. 

```PHP
// A send custom WebHook
add_action( 'elementor_pro/forms/new_record', function($record, $handler) {
echo "<pre>";
print_r($record);
echo "</pre>";
die();
//make sure its our form
$form_name = $record->get_form_settings('form_name');
if ('letter_of_guarantee' !== $form_name) {
return;
}
$raw_fields = $record->get('fields');
$fields = [];
foreach ($raw_fields as $id => $field) {
$fields[$id] = $field['value'];
}
//hook
wp_remote_post( 'http://mysamplesite.com/wp-admin/admin-ajax.php?action=rqst_form_submit', ['body' => $fields,]);
}, 10, 2);
```

And in my form widget settings I'm using Webhook on submit, Webhook URL as this - `http://mysamplesite.com/wp-admin/admin-ajax.php?action=rqst_form_submit`

But, I don't see in network console that my form is submitting to my Webhook. Requirement is to send an email with attached PDF to customer based on their inputs. 

**Attempt 02** 
As the above one didn't work, I tried to use WordPress Ajax Action to grab the form on submit as below. But didn't work either. 

```PHP
add_action('wp_ajax_rqst_form_submit', 'rqst_form_submit');
add_action('wp_ajax_nopriv_rqst_form_submit', 'rqst_form_submit');
function rqst_form_submit() {
echo "<pre>";
echo "rqst_form_submit";
echo "</pre>";
die();
}
```

Can you please support me on this?

Thank you.

**Comment by bainternet** [comment]
@yeshansachithak 

First, when you use a custom webhook via `elementor_pro/forms/new_record` you don't need to set up a webhook in the panel.

Second, you will not see that custom webhook in the network console, because it's a server-side request and not something out of your browser.

No as for what you are trying to achieve, you can use the same filter but there is no need to create a request, just send the email, ex:

```php
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
	//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'letter_of_guarantee' !== $form_name ) {
		return;
	}
	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}
	$to = $fields['email'];
	$subject = 'send email with PDF after submit';
	$message = 'this email contains a PDF';
	$pdf_path = [ 'full/path/to/pdf/file.pdf' ];
	$headers = 'From: My Name <myname@mydomain.com>' . "\r\n";
	wp_mail( $to, $subject, $message, $headers, $pdf_path );
}, 10, 2);
```

**Comment by yeshansachithak** [comment]
@bainternet Thanks! I was able to send emails in my first form. What if I have more than one form? Same add_action will trigger for the second form as well right? 

But, it seems like my OR method not support for form name. Please advice. 

`add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {`
    `//make sure its our form`
    `$form_name = $record->get_form_settings( 'form_name' );`
     `if (( 'letter_of_guarantee' !== $form_name) || ( 'documentary_credit' !== $form_name) ) {`
           `return;`
      `}`
`$raw_fields = $record->get( 'fields' );`
`$fields = [];`
`foreach ( $raw_fields as $id => $field ) {`
`$fields[ $id ] = $field['value'];`
`}`
`$to = $fields['email'];`
`$subject = 'send email with PDF after submit';`
`$message = 'this email contains a PDF';`
`$pdf_path = [ 'full/path/to/pdf/file.pdf' ];`
`$headers = 'From: My Name <myname@mydomain.com>' . "\r\n";`
`wp_mail( $to, $subject, $message, $headers, $pdf_path );`
`}, 10, 2);`

**Comment by bainternet** [comment]
Should be And instead of Or.

**Comment by alex-rankin** [comment]
Just for those that stumble on this ensure you have WordPress loaded with for this to work:

`require_once('pathtoyourfile/wp-load.php');`

**Comment by ilsondev** [comment]
I've solved adding this to the theme functions:

`add_action( 'elementor_pro/forms/new_record', function($record, $handler) {

	$webhook = $record->get_form_settings('webhooks');

	$raw_fields = $record->get('fields');
	$fields = [];
	
	foreach ($raw_fields as $id => $field) {
		$fields[$id] = $field['value'];
	}
	//hook
	$body = wp_json_encode($fields);
	$response = wp_remote_post($webhook, [
		'body'   => $body,
		'method' => 'POST',
		'headers'     => [
			'Content-Type' => 'application/json',
		],
	]);
	
	if (is_wp_error($response)) {
		$error_message = $response->get_error_message();
		echo "Something went wrong: $error_message";
		echo 'Response:<pre>';
		print_r( $response );
		echo '</pre>';
	} else {
		return $response;
	}
}, 10, 2);

add_action('elementor_pro/forms/webhooks/response', function($record, $handler) {
	return true;
}, 10, 2);`

May this help you.
