### ISSUE TITLE
Feature Request: Inserting sections into widgets + a great method to make a slide

### ISSUE THREAD

**Issue by m2sahin** [pojome/elementor#6957]
First, I must say, my English is not very good. You may not understand me exactly, so I added video. 

A short time ago, I tried a very different page builder. It has a few amazing features that attract attention. As an elementor lover, I want the elementor to have these great qualities. I think the Elementor and Elementor users deserve these wonderful things. please do not ignore it.

https://www.youtube.com/watch?v=CyTHBWY4Msw
See how to make a slide. Really very practical and very freely. Please watch

https://www.youtube.com/watch?v=IYaPYs0W908
New section can be added into widgets such as taps and accordion. Very successful.

Thanks,  I'm sorry if I was rude.

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

as for adding widgets inside widgets follow #2587

thanks for the feedback and suggestions.

**Comment by m2sahin** [comment]
https://www.youtube.com/watch?v=IYaPYs0W908

https://www.youtube.com/watch?v=CyTHBWY4Msw

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was partially introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Nested Tabs** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Feel free to check it out and update your plugin to the new version!

Stay tuned for the next versions that will introduce Nested Accordions and other elements as well. 

🗨️ Please continue the conversation in issue #2587.

Cheers 🥂
