### ISSUE TITLE
Use the display formatting of ACF Date Field

### ISSUE THREAD

**Issue by drnickyoung** [pojome/elementor#6958]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have an ACF Date field connected with a custom content type. It works fine. Now when I create a single post template I can display most things with Dynamic Field. The settings for the field are shown below. However the ACF Date when shown on the page by Elementor shows the raw value (see last image below) and not the display value of the ACF field.

**Describe the solution you'd like**
Allow the choice of raw or display value to be shown, or custom formatting.

**Describe alternatives you've considered**
Not using Elementor template for this page, but then formatting for the page will not fit in and would mean not using Elementor throughout the site or changing the layout.

**Additional context**
Date (ACF Field) settings
<img width="478" alt="2" src="https://user-images.githubusercontent.com/303739/52176327-17935a80-27a9-11e9-8c46-c10c04e37c02.png">

Selection in Elementor editor
<img width="265" alt="1" src="https://user-images.githubusercontent.com/303739/52176326-17935a80-27a9-11e9-8b39-fdf0d1f9732a.png">

Output
<img width="162" alt="3" src="https://user-images.githubusercontent.com/303739/52176328-17935a80-27a9-11e9-95de-f2466d4c91c5.png">

**Comment by bainternet** [comment]
@drnickyoung 

The ACF field returns the value in which is defined by you in the ACF field settings, Not raw value.

For date field, it's using the return format you have defined on the field settings, which in your case is `Ymd` and it translates to something like 20190207.

So simply set the "Return Format" to the format you want.

thanks.

**Comment by drnickyoung** [comment]
My mistake, I cannot change the return format as another plugin needs it in that format. Is there anyway Elementor can allow for custom field formatting? Either with a custom field or by a plug in/code?

**Comment by artifex-media** [comment]
@bainternet This actually seems like a real issue, as I am expierencing the same issue while my Return Format **is** correctly set.

I have a date field within ACF and the Return Format is set as **j M. Y**, instead of returning that value, it returns a date in dmY format.

Setting:
![image](https://user-images.githubusercontent.com/43996366/74652552-88c06880-5186-11ea-8e6e-9490b3a43f2d.png)

Output:
![image](https://user-images.githubusercontent.com/43996366/74652573-98d84800-5186-11ea-8e42-219dc5be787a.png)

**Comment by fubbi** [comment]
bump!

**Comment by artifex-media** [comment]
> bump! Same issue for me
> Elementor should definitely show the display format, why would you ever want it to show the return format. Its crazy bananas :)

Check if you use the 'ACF Field' tag and not 'Custom Field', I ran into the same issue but it appeared to be the wrong tag I used. Might be it, might not be - just wanna let u know.

**Comment by ashkan-ahmadi** [comment]
I have the same issue. It's weird because if you use Toolset and select Toolset Date, then you can format the date but if you pick ACF (there is no ACF Date on the dynamic menu), you can't format it. For example, I have events and trips on the website and I display a short version like 17 Sept on the card and Monday, 17 September on the payment page but I have had to set up 2 different field fields which is inconvenient and prone to errors (if i change one, i have to remember to change the other).
Why is it possible with Toolset and not ACF? Strange

**Comment by eddowding** [comment]
This post needs to be reopened.

**Comment by WebDragon** [comment]
I too am experiencing this with Elementor and ACF where it is respecting neither the Return format nor the Display format and returns 19:30:00 (military time) instead of 7:30 pm (both display and return are set to this) when inserting the Dynamic Tag into an elementor template. How do I fix this?

**Comment by redalto** [comment]
Bump. same issue. I've created a date field (start date) for a custom calendar. But need different date format depending on where the field is displayed (event list vs event summary vs event detail). Would be useful to have display format option.

**Comment by nasdytech** [comment]
The solution is to use a custom shortcode with formating parameter : in ly case i needed french so 
`function acf_date_shortcode( $atts ) {
	// extract attributs
	extract( shortcode_atts( array(
		'field'			=> '',
		'post_id'		=> false,
		'format_value'	=> true,
		'date_format' 	=> ''
	), $atts ) );
	$acf_date = get_field( $field, $post_id, $format_value );
	$date = DateTime::createFromFormat('d/m/Y', $acf_date);
	$formatter = new IntlDateFormatter('fr_FR', IntlDateFormatter::FULL, IntlDateFormatter::NONE);
	$formatter->setPattern($date_format);
	$date_format_fr = $formatter->format($date);
	return $date_format_fr;
}

add_shortcode( 'acf_date', 'acf_date_shortcode' );
`

**Comment by WebDragon** [comment]
> [acf_date field='date_debut' date_format='MMM']

In my case, I need to get a subfield 'time' from a field group 'general_information' and format it as `h:mm a, z`, not as a date because when Elementor extracts it, no matter what I say, it comes back in Military time. I tried a variation on your shortcode to extract the general_information field, and then get its sub-field 'time' but apparently I am 
DoingItWrong&trade; and could use a pointer, because while Elementor has no problems populating data with other ACF shortcode fields in preview mode for the custom post type I have, this one isn't.

**Comment by XoSara** [comment]
> t's weird because if you use Toolset and select Toolset Date, then you can format the date but if you pick ACF (there is no ACF Date on the dynamic menu), you can't format it. For example, I have events and trips on the website and I display a short version like 17 Sept on the card and Monday, 17 September on the payment page but I have had to set up 2 different field fields which is inconvenient and prone to errors (if i change one, i have to remember to change the other).
> Why is it possible with Toolset and not ACF? Strange

Same issue for me, did you solve it?

**Comment by WebDragon** [comment]
No, it is still unsolved and this bug still needs to be re-opened

**Comment by noelawill** [comment]
I have the same issue with both Elementor and WPForms.  

I understand that the date in the field I am creating in ACF is saved as Ymd in the database but I have the return format set to d/m/Y but in both plugins (and possibly others) the return format is showing as the d'base saved format on the frontend, however it does return correctly in the User profile.  

It is very frustrating as my users keep asking why their date of birth is backwards when displayed on the frontend.  Hoping someone can help. 

![Screenshot 2024-01-16 162851](https://github.com/elementor/elementor/assets/112880326/e5df85c1-904b-4926-bd88-1edf9a941305)
![Screenshot 2024-01-16 162940](https://github.com/elementor/elementor/assets/112880326/af9ffca9-24cc-450a-a502-435d4db0bd10)
![Screenshot 2024-01-16 163030](https://github.com/elementor/elementor/assets/112880326/0f2d87b6-7a49-4e37-abfa-8578423215e6)
![Screenshot 2024-01-16 163124](https://github.com/elementor/elementor/assets/112880326/75e65354-7a98-470b-a745-df9018c584b8)

**Comment by bopyd** [comment]
Hi All,

Lots of good advice here, thought I'd drop some  screen shots on how to solve the issue when dealing with Elementor Widgets and an ACF time picker field where you'd like to see a g:i a output format.

If are using a dynamic tag in Elementor and the dynamic tag starts with "Post Custom Field" then Elementor will ignore your ACF return and display settings.
<img width="248" alt="post-field" src="https://github.com/user-attachments/assets/b4bec387-9881-4dfc-97b8-39c23cb6a7b9" />


Instead you want your dynamic tag  to look like this.  It should start with "ACF Field"


<img width="242" alt="ACF-Field" src="https://github.com/user-attachments/assets/d9b966c5-cd5b-4ed4-aee6-3b520e99cce2" />

You'll find the "ACF field" option all the way at the bottom of the dynamic field selection.  This is probably the reason most people miss it.
<img width="267" alt="ACF_Field_Selection" src="https://github.com/user-attachments/assets/521b63d8-2fdb-4b16-8c63-8d62df31d749" />
