### ISSUE TITLE
Form Widget:  Pass Dynamic Content (Custom Field Value) Through the To: Field

### ISSUE THREAD

**Issue by wpturnedup** [pojome/elementor#6960]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Hey @wpturnedup 

You sure can do so,
Create a hidden field, assign to it the custom value you wish to have, and then take that field shortcode (e.g `[field id="email"]`) and place it in the "To" field.

Thanks.

**Comment by wpturnedup** [comment]
Thank you. I pretty much have it sorted out.  The last piece is the Page URL.  Is there a way to Pass this through as well, rather than using the Meta Data option?  Reason being that I can't change Page URL to say "Business Listing", for example.

![image](https://user-images.githubusercontent.com/35966122/52179468-9afc7e00-27a0-11e9-9cc9-fee6b2fc18f6.png)

**Comment by shilo-ey** [comment]
I don't understand your question.

What is your demand?

I would refer you to:
1. [Request Parameters docs](https://docs.elementor.com/article/451-dynamic-request-parameter)
2. [Dynamic tags docs](https://docs.elementor.com/article/310-dynamic-content)
3. [Forms docs](https://docs.elementor.com/category/404-forms)

**Comment by wpturnedup** [comment]
Please see the image below.  I was curious if we could remove the URL from the Meta Data section and display it in the Message section.  That way, we are able to add some customization (extra text, styling, etc.) around it.

I’m not sure if [field id=”url”] is even a valid field, but just threw that up there as an example.

I was able to change “Page URL” to “Listing URL”, using the Loco Translate plugin, but I’d rather be able to do this with the method I’m proposing.

Thanks!

[cid:image001.png@01D4BC60.3B62F3D0]

**Comment by benjaminadrom** [comment]
-.- "better not answer that question, it looks complicated" xD
