### ISSUE TITLE
Allow saving a section and / or inner section as a global widget

### ISSUE THREAD

**Issue by guyzamir** [pojome/elementor#6962]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
Hi @guyzamir 

### Create a Global Widget
1. Right Click the widget’s handle and click on Save as a Global
2. Name your new global template and click the Save button

[Read more here](https://docs.elementor.com/article/100-global)

**Comment by guyzamir** [comment]
This is available for elements.

Not for sections.

**Comment by bainternet** [comment]
@guyzamir 	

Sections can be saved as templates!

**Comment by guyzamir** [comment]
I understand that, but if I make a section with things like share buttons or even a form that I want to show on all posts, I’ll need to change it on every page if I change something, like, my email address or add a field to the form.

 

It should work like an Include in PHP….

**Comment by shilo-ey** [comment]
@guyzamir 
Just add dynamic content as the value of the required fields.

I suggest you to visit our [Documentation](https://docs.elementor.com) in order to learn about the full power of Elementor.

**Comment by taropaa** [comment]
@shilo-ey that is a very complicated way of getting something simple done. Just look at how the folks at Divi are doing it: they allow both sections, rows etc to be saved as global elements which update across the website, without requiring you to go across multiple screens and waste 15 minutes figuring it out and another 20 troubleshooting and trying to understand where it all went wrong. I believe this is a very big miss for Elementor.

**Comment by scottybo** [comment]
Any news on this one? I'd like to add an inner section as a global widget - we're creating a global sidebar (I don't want to use sidebar widgets) and we're putting all the contents inside an Inner Section

**Comment by mikenco** [comment]
I agree. I have just come across this issue. I can't save Inner Sections as Global. Seems like it should be common sense, but it's not.

**Comment by userisamir** [comment]
Hi @mikenco,
1- create new section in elementor theme builder.
2- copy and paste your old design in new section template.
3- use the section 'shortcode' everywhere you need.

**Comment by aamirmotiwala4** [comment]
i found this step by step guide to save sections globally https://bit.ly/2Sy3UlB

**Comment by nodex4** [comment]
How can you do this: the guide you linked is not accesible!
