### ISSUE TITLE
Disabling Entrance Animations on Print

### ISSUE THREAD

**Issue by Bonitto** [pojome/elementor#6964]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Whats the best way to disable entrance animations when a user wants to print a page. Is this something that can be controlled with css? Whenever I try to print a page, I am unable to view the entirety of the page because it has not come into view yet.

## Steps to reproduce

1. First you'll need to create sections and add entrance animations to sections that are outside of the initial viewport of a page.
2. Type CMD + P (for Mac) or CTRL + P (for PC) to bring up the print prompt.
3. Sections of the page that have not yet loaded because they have not come into view because the rest of the page has not scrolled down yet do not appear in the print preview.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @Bonitto 

This is a specific behavior that you are looking for.

Simply create media query which applies only for animated widgets (or just add `print` ID to the elements you wish to be without animation in print...)

```CSS
@media print {
    #print {
        animation: none !important;
        display: block !important;
        visibility: visible !important;
    }
}
```

Thanks

**Comment by Bonitto** [comment]
Hi @shilo-ey,

I have attempted to do this by trying to target specific data attributes that all of the animations have in common. For instance

`@media print {
          [data-settings*="fade"] { 
			-webkit-print-color-adjust: exact !important; 
			/* turn off all animations */
			-webkit-animation: none !important ;
			animation: none !important;
			-o-transition-property: none !important;
			-moz-transition-property: none !important;
			-ms-transition-property: none !important;
			-webkit-transition-property: none !important;
			transition-property: none !important;
			/*CSS transforms*/
			-o-transform: none !important;
			-moz-transform: none !important;
			-ms-transform: none !important;
			-webkit-transform: none !important;
			transform: none !important;
			/*CSS animations*/
			-webkit-animation: none !important;
			-moz-animation: none !important;
			-o-animation: none !important;
			-ms-animation: none !important;
			animation: none !important;
			opacity: 1;
			/*CSS transitions */
			-webkit-transition: none !important;
			-moz-transition: none !important;
			-ms-transition: none !important;
			-o-transition: none !important;
			transition: none !important;
			opacity: 1;
          }
}`
