### ISSUE TITLE
[Feature Request] Round / Circular layout

### ISSUE THREAD

**Issue by orenk1** [pojome/elementor#6965]
it would be nice to have an element with circular icons/pics/links/elements arrangement.
something similar to this :
![popup_ld_integration](https://user-images.githubusercontent.com/34028004/52184232-da62b300-2810-11e9-81f2-9025a44fc085.png)

https://elementor.com/wp-content/uploads/2019/01/Popup_LD_Integration.png

**Comment by shilo-ey** [comment]
@orenk1 

This is currently an image.
But we are currently working on a layout option that would enable this.

Stay tuned :)
