### ISSUE TITLE
Custom Widget misbehave

### ISSUE THREAD

**Issue by dtmgs** [pojome/elementor#6966]
Hi there,

I have created a custom widget named "Image Comparison", and it misbehaves when I place it in page.

http://recordit.co/uNbwCUm3uk

I have just attached sample file with this ticket. Kindly go through following functions to get deeper idea.
function preview_styles() {} in designthemes-elementor.php
widgets\image-comparison\class-image-comparison.php
1. render() + _content_template()
2. render_alt() + _content_template()
3. rener() only
4. render_alt() only

In above scenario, the widget output differs.

[designthemes-elementor.zip](https://github.com/pojome/elementor/files/2826739/designthemes-elementor.zip)

Note: I have posted this issue in Elementor Pro, they redirected me to github.

So kindly help me.

**Comment by bainternet** [comment]
@dtmgs 	

I just checked your widget and I don't see different output for the widget, other than not have a default width defined.

Also, I get a PHP warning: `Undefined variable: use_overlay in /wp-content/plugins/designthemes-elementor/widgets/image-comparison/class-image-comparison.php on line 202`

thanks.

**Comment by dtmgs** [comment]
@bainternet 
Hi there,
Hope you've seen the video i've given as a reference. Whereas it shows that the widget appears in different manner each time it loads, and in change of screen-size (likely with firebug), it reflects in the same way..
http://prntscr.com/mhdg26
