### ISSUE TITLE
Elementor is not checking user profile language

### ISSUE THREAD

**Issue by Applepiee** [pojome/elementor#6969]
Hello,

We users that are using WPML have been ignored for almost a whole year now.
When the main language of Wordpress isn't English however change the language of your profile to English, every single thing in Wordpress becomes English **except** the Elementor builder.

Please fix so that elementor checks the user profile for language settings. I currently have to edit pages in Japanese..

Regards,
Davy

**Comment by shilo-ey** [comment]
@Applepiee 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

In addition, I merged this issue with  #5148, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks.
