### ISSUE TITLE
Add Dynamic Content for Testimonial Carousel

### ISSUE THREAD

**Issue by MafuraG** [pojome/elementor#6970]
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I use a custom post type to maintain the list of Testimonials with ACF fields to hold specific details about a testimonial (Company, Job Title, Link Text, Link). Currently there's no way to integrate this to the Testimonial Carousel.
This is a similar issue that faces other Pro widgets which aren't as dynamic (e.g. tabs).

**Describe the solution you'd like**
The Testimonial Carousel should be allowed to use a custom query to display information / allow for use of dynamic content.

**Describe alternatives you've considered**
Using the Posts or Portfolio widget allows the use of a query to seed contents. Perhaps Testimonials should just be a skin of the "posts" base?

**Additional context**
#5797 is very close to what I need. (Closed)

![new custom post](https://user-images.githubusercontent.com/930730/52209778-feb4a300-2895-11e9-8d22-733f8e39d5a9.png)
![custom post type](https://user-images.githubusercontent.com/930730/52209782-01af9380-2896-11e9-904b-5a1a1bc7ffab.png)
![new menu for testimonial carousel](https://user-images.githubusercontent.com/930730/52209774-fa888580-2895-11e9-9cec-e0be48568814.png)

**Comment by shilo-ey** [comment]
I merged this issue with  #219 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by bentalgad** [comment]
It's funny that you have for dynamic content in every field separately instead of just having the option to add dynamic fields any where just like in beaver builder which lets you add it even inside text and even multiple dynamic content's in one field.

**Comment by jgajera** [comment]
+1 & Pro user

**Comment by ivan-vilches** [comment]
i want this feature too, what is the status of this?

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.11! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
