### ISSUE TITLE
Global background with overlay etc

### ISSUE THREAD

**Issue by TerenceMilbourn** [pojome/elementor#6972]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Provide a global background image capability for all pages.

**Describe the solution you'd like**
I want to be able to specify in one place a background image which will be used by all pages of a site and not have to edit each page to load the same image. I would also like it to have the standard section background overlay functions, gradient etc,

**Describe alternatives you've considered**
If I could find a code snippet to use in the child theme that would do, I suppose.

**Additional context**
None. Except, it really ought to have been in PRO from the beginning.  Nuff said.

**Comment by shilo-ey** [comment]
I merged this issue with  #3345, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
