### ISSUE TITLE
IE11 Edge break site

### ISSUE THREAD

**Issue by thedaviator** [pojome/elementor#6973]
I spent all weekend building what I thought was a beautiful site. But then I tested (viewed) it in IE11 and Edge and what a mess. Background images and colors are missing, text is misaligned, font colors, button styles and (some) widths are ignored. 

Yes, I know most people (developers) don't use IE/Edge but most corporations still do. How could Elementor completely ignore this browser? 

URL: http://aerorelics.com/classicairshows/

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
