### ISSUE TITLE
in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by hurnhu** [pojome/elementor#6976]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate (the one i have found is closed).
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I've just installed elementor and i get the following errors

```
Refused to display 'siteurl/?p=52&elementor-preview=52&ver=1549317616' in a frame because it set 'X-Frame-Options' to 'deny'.
Uncaught DOMException: Blocked a frame with origin "siteurl" from accessing a cross-origin frame.
```

This is not a multisite and this was on a fresh install on wordpress.
ive also tried deleting the plugin and reinstalling it
## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: Ubuntu 18.04 v5.6.39-83.1
	PHP Version: 7.2.10-0ubuntu0.18.04.1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://parsley.pw
	Home URL: https://parsley.pw
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Author
	Version: 1.37
	Author: Compete Themes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

== Active Plugins ==
	Accelerated Mobile Pages
		Version: 0.9.97.31
		Author: Ahmed Kaludi, Mohammed Kaludi

	Ad Inserter
		Version: 2.4.8
		Author: Igor Funa

	Elementor
		Version: 2.4.5
		Author: Elementor.com

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.7
		Author: ExactMetrics

	Smush
		Version: 3.0.2
		Author: WPMU DEV

	Wordfence Security
		Version: 7.1.20
		Author: Wordfence

	WP Recipe Maker
		Version: 4.2.1
		Author: Bootstrapped Ventures

	Yoast SEO
		Version: 9.5
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Log ==
	: 
JS: showing 3 of 3JS: 2019-01-26 02:06:32 [error X 2][https://mike.michaellapan.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.4:2:82281] Blocked a frame with origin \"https://mike.michaellapan.com\" from accessing a cross-origin frame. 
JS: 2019-01-31 14:40:18 [error X 2][https://parsley.pw/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:82347] Blocked a frame with origin \"https://parsley.pw\" from accessing a cross-origin frame. 
JS: 2019-02-04 21:47:03 [error X 9][https://parsley.pw/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:0] Permission denied to access property \"elementorFrontend\" on cross-origin object 

Log: showing 1 of 12019-01-30 22:48:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]


				
```
</details>

**Comment by shilo-ey** [comment]
Please try:

- Deactivate all your plugins besides Elementor. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists...

My assumption is the WordFence plugin or server related configuration is blocking X-Frames headers.

Thanks

**Comment by hurnhu** [comment]
@shilo-ey i have done that and the issue still persists

**Comment by henno** [comment]
In my case this issue was caused by the fact that the excellent [h5bp/server-configs-nginx](https://github.com/h5bp/server-configs-nginx) has this part in `nginx.conf`:

```
# Add X-Frame-Options for HTML documents.
  # h5bp/security/x-frame-options.conf
  map $sent_http_content_type $x_frame_options {
    ~*text/html DENY;
  }

```

I just had to replace `DENY` with `SAMEORIGIN` and reload Nginx.

**Comment by hokascha** [comment]
in my case there was an entry in /etc/nginx/snippets/ssl.conf:

`add_header X-Frame-Options DENY;`

change that to 

`add_header X-Frame-Options SAMEORIGIN;`

and restart nginx

**Comment by pedlima** [comment]
In my case, I just had to edit my .htaccess file because I had manually added that while trying to implement security measures.
