### ISSUE TITLE
No Results Found in Dynamic Pop up

### ISSUE THREAD

**Issue by cjmetacrawler** [pojome/elementor#6978]
No Results Found in Dynamic Pop up

![image](https://user-images.githubusercontent.com/13638097/52262018-2bd08680-2966-11e9-94f4-b6487853c14d.png)

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
