### ISSUE TITLE
Form submission (POST/GET) without AJAX

### ISSUE THREAD

**Issue by tomas-eklund** [pojome/elementor#6980]
## Prerequisites

- [x] I have searched for similar features requests in open tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What do you want?**

The ability to design a form using Elementor Pro which simply submits the form content using GET or POST _without AJAX_.

**What problem is your feature request going to solve?**

The current problem I'm facing is a simple subscription service for financial press releases. You post a simple subscription form to a remote server and depending on success or failure, the remote server will redirect back to one of two given URLs. The success/failure URLs are specified using hidden form fields. This would have taken about 10 minutes to set up (including creating the success/failure pages) if Elementor only allowed us to actually POST the form _without AJAX_. I wouldn't even have to be a developer to do it.

Now, some developer from the Elementor team will probably point me to [the Forms API](https://developers.elementor.com/forms-api/) and basically tell me to spend many hours reading the docs and writing quite complicated PHP which will need to:

* hook into the AJAX form processing action
* gather data from all the form fields
* recreate the form as a PHP object
* using a function to POST the form contents to the remote server
* parse the response (which probably is a 302 redirect - I'd have to research how to do that)
* redirect the user based on the response

So, instead of spending a few minutes setting something up that is easily administered and maintained by even a non-developer, I'd have to spend a full working day to implement and test a custom solution that is practically hard coded PHP which the client will have no control over what so ever. And where do I put the code? In the theme? That's bad form. What if the client wants to switch themes? Do I write a plugin? That would be a nicer solution, but come on! Is that really reasonable? For this?!

In practicality I would have to recreate both the form and much of the server logic using custom code. I would have to spend hours writing PHP code to accomplish things that _are already there_. The form is there. The remote server with its redirection logic is there. I'd have to duplicate all of that functionality in a hook!

**Would it solve other problems than the current one you are experiencing?**

Certainly! I've run in to this problem many times before in different circumstances. The above is just one example of many,

**Why are you not happy with the Forms API?**

I appreciate the Forms API. I'm a developer and I appreciate APIs in general. But I'm trying to think in non-developer terms. My clients are not developers, and in this case I would have to spend hours creating useless code that does not add anything but unnecessary complexity. This is a major waste of time and money.

Elementor is marketed as a _page builder for non-developers_. This feature has been requested by the community numerous times before, but has been shut down every time - _by developers_ who claim that the functionality can be accomplished using their _developer's API_. This is really sending mixed messages. As it stands, Elementor is NOT a page builder for non-developers - you actually need to be quite a good developer to use Elementor for anything but the most trivial.

**Describe the solution you'd like**

A simple option to submit the form using POST or GET to a given URL. Implementing this feature ought to be extremely simple for the Elementor developers: Two controls in the Edit Form GUI and then disabling the AJAX functionality allowing the browser to submit the form the usual, default way.

**Describe alternatives you've considered**

Not using Elementor.

Which of course is the road I'm taking until this is fixed. The form is now hard coded in a template file and the styling is in a CSS file. The client will not be able to restyle the form using the nice GUI of Elementor.

**Comment by shilo-ey** [comment]
@tomas-eklund 	

First, we don't see this as something that needs to be "Fixed".

And like you already stated, this can be achieved using the available action and filter hooks.

Other than that you can create your own action after submit, to provide to your clients that will answer your specific use cases.

thanks.

**Comment by tomas-eklund** [comment]
So, you are openly admitting that Elementor is **not**  a page builder for non-developers.

**Comment by bainternet** [comment]
@tomas-eklund 

Elementor is a page builder for non-developers. Now there are things like your specific use case that elementor doesn't cover. Hover it does provide an API in please to customize/extend to met these uses cases.

thanks.

**Comment by tomas-eklund** [comment]
@shilo-ey @bainternet 

I did not post this as a bug report (as in something to "fix"), I posted it as a _feature request_ (as in something that would _improve_ on the form feature). And based on the number of times the request has been made by others before me, I gather there is enough interest to warrant the almost insignificant development time needed to implement the feature.

I really don't understand why you shut these requests down so adamantly. Would you please elaborate on why you refuse to even consider this simple feature? You have many open feature requests - some are many years old. Why not keep this open as well? understand that it might take some time before you have a chance to get to it, but right now I just feel like I'm banging my head against a wall.

There must be a reason.
