### ISSUE TITLE
Hide controls on design changes [Feature Request]

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#6981]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**The Problem**
When you edit things like shadow or border, you can't see in live how it will look because the editor's control border is hiding some of or all of the border / shadow.

So for example:
![2019-02-05 17 43 49](https://user-images.githubusercontent.com/23374215/52285145-7e15a580-296e-11e9-90f8-e4940c55a206.gif)

Here i am trying to edit the shadow / border of a row. but i can't really fine tune it cause i can't see how the color of the border is looking exactly or how to shadow will look exactly without that blue border of the editor.

**Solution (Maybe)**
I don't know what is the best approach but the first idea that comes into my mind is just hiding those controls while you drag the controllers of such design parameters, or maybe having the option to hide those borders with some shortcut or so...

**Anyway**
I think this is a big deal for a page builder to have. because one of the main concepts of a page builder like Elementor is the "what you see is really what you get all the way to the pixel" :) and right now it's not completely true :)

**Comment by shilo-ey** [comment]
Hi @bentalgad 

As you know, the border indicates which element you are currently editing.

The cost of disabling this indicator to all of our users can make some damage, therefore we will not add this option for now.

For meanwhile you can use custom CSS to hide those borders if you wish to.

Thanks for your feedback.

**Comment by bentalgad** [comment]
@shilo-ey i really hope you didn't really read my comment because if you did and you are still writing this reply i must be the worst commenter ever :)

I didn't suggest in any way that you will remove this border indicator! of course we need this! i was suggesting that you will hide it only while the shadow controller is used for example, or as i suggested as a second option to have an option to toggle between seeing this indicators or not (just like you have this option in photoshop and other applications) with some shortcut, but definitely not losing it all together.

Now i was only suggesting two options that popped in my mine. but the main feature request is to address this problem in some way you see fit (and not necessarily in the way i suggested).

Btw - i think that closing a feature request before you even understand it, or just because the solution suggested to the problem doesn't seem to be a good one, while the problem is a serious problem (and you can try and find another solution for it) is a really really bad approach.

**Comment by tomas-eklund** [comment]
@bentalgad I share your frustration. 

> Btw - i think that closing a feature request before you even understand it, [...] is a really really bad approach.

They do this on a regular basis. I almost think the developers should not be allowed to close feature requests (unless they have implemented it). They should have a manager or a review team go though the feature requests, to review, catalog and and prioritize them. And, of course, close if it _really_ is an unreasonable request.

Right now they just shut most feature requests down, probably to keep their backlog manageable and maybe their own stress levels down. It's quite an insult to the community. Most of us are here with the goal to help making Elementor the best page builder out there. The devs don't seem to appreciate the time, thought and effort that has gone into many feature requests. 

By the way, I think your feature request is reasonable and well explained, though I wouldn't go as far as call it a "serious problem". Maybe a major inconvenience. ;-)

**Comment by bentalgad** [comment]
@tomas-eklund i absolutely agree.

There shouldn't be nothing wrong with leaving issues open and say "hey we hear you, but we don't have a great solution for that for now, we will try to address it down the road..." or "your suggestion is problematic because a. b. c.. do you have another idea?..." or so... but just closing it with some comment that really doesn't address the issue is not the way to go.

Hope they will take it into consideration.
