### ISSUE TITLE
Working with ACF json without sync not working

### ISSUE THREAD

**Issue by fhfournier** [pojome/elementor#6982]
## Prerequisites
- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

If i want to set a dynamic content like "image" its not working if my ACF field are not sync.
Normaly, if you use GIT for your theme, you should avoid synching ACF to your database and using json inside your theme for ACF.

There is my ACF field
Project (group name)
- feature image (field name)

So, the problem is, I can't see my picture inside dynamic field in elementor. If i debug the html i can see <img src="h"...> with multiple error in console log

In elementor panel. It's always said "**Option > feature image**" and should be "**Project > feature image**". If i sync my acf groups to my database. The field in elementor are working and my image are set.

## Steps to reproduce

1 : add image to elementor
2 : set Dynamic content
3  : select ACF field
4 : nothing

## Isolating the problem
- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: mariadb.org binary distribution v5.6.41-84.1
	PHP Version: 7.0.33-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 3000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: http://activis.devstack.fhfournier.activ.is
	Home URL: http://activis.devstack.fhfournier.activ.is
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%postname%/
	Language: fr-CA
	Timezone: America/Toronto
	Debug Mode: Active

== Theme ==
	Name: Activis (2017)
	Version: 1.0.0
	Author: Activis, votre agence web
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_CA
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.7.10
		Author: Elliot Condon

	Elementor
		Version: 2.4.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.3
		Author: Elementor.com

== Log ==
	: 
Log: showing 2 of 22019-02-05 13:20:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.3.8',
  'to' => '2.4.5',
)]
2019-02-05 13:22:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.3',
)]

PHP: showing 2 of 2PHP: 2019-02-05 13:21:26 [warning X 18][/var/www/activis.devstack.fhfournier.activ.is/htdocs/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::86] Illegal string offset 'url' [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-05 13:25:58 [notice X 3][/var/www/activis.devstack.fhfournier.activ.is/htdocs/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::44] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2019-02-05 18:56:43 [error X 9][http://activis.devstack.fhfournier.activ.is/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:82347] Blocked a frame with origin \"http://activis.devstack.fhfournier.activ.is\" from accessing a cross-origin frame. 

				
</details>

**Comment by shilo-ey** [comment]
Hi @fhfournier 

Quite didn't understand what you are referring to, it seems like syncing issue with ACF.

I tried to add a field group with JSON sync on.
Added a field group > added an image field > added an image to this field > went to Elementor editor and clicked on ACF image field.

The name of the field group and the image - are correct, even when I change the name of the field group.


I did notice that if you are manually editing the JSON file and changing its name - the updated name will not be shown until you will change the group file name.

If it's not answering your question, please open a new issue with steps to reproduce properly.

Thanks.
