### ISSUE TITLE
Justify - paragraph formatting

### ISSUE THREAD

**Issue by orisica** [pojome/elementor#6983]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When you apply "justify" to paragraph text it gets applied to headings as well. That introduces display issues on mobile devices and it doesn't make sense for headings to have that type of formatting. No other text editor does it that way. Please consider changing that behavior.

**Describe the solution you'd like**
Can you add an option to apply different formatting to headings? Or just make it so that headings aren't affected by that setting?

**Describe alternatives you've considered**
I can't figure out how to remove justify formatting from post headings.

**Additional context**
This is where aforementioned setting is applied:
![52051718-9d6a9800-2554-11e9-8e4e-63673f362216](https://user-images.githubusercontent.com/42409471/52306362-052b4380-2998-11e9-9d50-619b2c7f81bb.png)

**Comment by shilo-ey** [comment]
Hi @orisica ,

Thanks for your feedback.

You can either change your alignment setting per device or use `Heading` element in the Elementor editor.

If you are using Post Content widget which receives its content from the post native editor, simply do not set alignment settings in the widget level, and set it in the native WP editor.

Thanks.

**Comment by orisica** [comment]
WordPress editor does not have justify setting. How can I globally apply justify only to paragraphs? Without manually editing each and every post ever created of course.
Thanks for help.

**Comment by shilo-ey** [comment]
Simply add custom CSS via Appearance > Customizer > Add custom CSS there:

```CSS
p {
        text-align: justify;
}
```

you may have some other selectors that won't be justified, therefore you will need to add them to the rule.

Thanks.
