### ISSUE TITLE
Hide The Top Menu On Scroll Down And Show Up When Scroll Up

### ISSUE THREAD

**Issue by ofer777** [pojome/elementor#6984]
can you please add :Hide The Top Menu On Scroll Down And Show Up When Scroll Up

**Comment by shilo-ey** [comment]
Hi @ofer777 

We are working on a broader solution for this.

As for your specific request, you can achieve it by adding some custom code for now. [see here.](https://www.w3schools.com/howto/howto_js_navbar_hide_scroll.asp)

Thanks
