### ISSUE TITLE
No Results Found in Dynamic Pop up 

### ISSUE THREAD

**Issue by cjmetacrawler** [pojome/elementor#6985]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

No results found in Dynamic pop up though I created 2 Pop ups already. 

![image](https://user-images.githubusercontent.com/13638097/52310308-e94a9080-29dd-11e9-9519-c3bd9e007fed.png)

## Steps to reproduce

1. Create a Pop up
2. Create an Icon box
3. On the dynamic link, choose Pop up
4. Click Pop up and Search for the Pop up you recently created
5. The query results to No results Found and there is no Pop up listed on the list.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment]
@cjmetacrawler 

We can't replicate,
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by cjmetacrawler** [comment]
I already emailed the support and even contact them on the website as an elementor pro user but I got no reply.
