### ISSUE TITLE
Elementor Pro and WooCommerce - Changing labels 

### ISSUE THREAD

**Issue by baldino1** [pojome/elementor#6987]
Hi,

I am using Elementor Pro with wooCommerce modules. I would like to change some labels to the meta element, but I can't find how. The usual solution would be to copy and paste the meta.php file into the template directory, obviously not working for the present case.

Cheers

**Comment by shilo-ey** [comment]
Hi @baldino1 

There's an option to do so by editing the Meta > Captions section

![image](https://user-images.githubusercontent.com/45009641/52329039-553af200-29fa-11e9-946f-3eea9407dacd.png)


Thanks

**Comment by baldino1** [comment]
Ta for the quick reply.

Sorry if I insist, but the captions section doesn't happen to show on my side...should I activate it in some way? Or does it depend on the version used?

![ae6edfd3-27f4-40e1-b34d-cc175c18380c](https://user-images.githubusercontent.com/47371665/52377902-53386800-2aba-11e9-9eed-ac108eb03bbe.png)

I am using elementor 2.3.8, elementor pro Version 2.3.1 and  woocommerce extension 3.0.6.

Cheers

**Comment by shilo-ey** [comment]
Hi @baldino1 

This feature is from Elementor Pro 2.4.0

Update both of your plugins to see the changes.

Thanks
