### ISSUE TITLE
Shortcode in _content_template()

### ISSUE THREAD

**Issue by mattiasghodsian** [pojome/elementor#6988]
Is it possible to execute shortcode within **_content_template() ?**

    <# Array.from({ length: 10 }).forEach((x, i) => { #>
        <div class="">[elementor-template id="{{ settings.template }}'"]</div>
    <# }); #>

**Comment by bainternet** [comment]
@mattiasghodsian 

No, `_content_template` is executed on the client (browser) so shortcodes are not parsed in it nor are any PHP functions.

thanks.
