### ISSUE TITLE
No support for Domain Mapping and CDN

### ISSUE THREAD

**Issue by taropaa** [pojome/elementor#6989]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Elementor refuses to work with Domain Mapping Plugins or CDN Plugins. 

## Steps to reproduce

- Enable Autooptimize
- set CDN URL
- Clear all caches
- All assets will still load from the website url and not from the CDN

Or

- Use WP Ultimo domain mapping with default settings on WP Multisite

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
-- [x] This bug happens with the Hello Theme
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Google) v5.7.14
	PHP Version: 7.2.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://[removed]
	Home URL: https://[removed]
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Debug Mode: Inactive

== Theme ==
	Name:  Hello
	Version: 1.0.0
	Author: Adrian
	Child Theme: Yes
	Parent Theme Name: Elementor Hello Theme
	Parent Theme Version: 1.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.4.4
		Author: Frank Goossens (futtta)

	CAOS for Analytics
		Version: 2.0.3
		Author: Daan van den Bergh

	CDN Enabler
		Version: 1.0.8
		Author: KeyCDN

	Dynamic Animations for Elementor
		Version: 1.0.0
		Author: Dynamic.ooo

	Elementor
		Version: 2.4.5
		Author: Elementor.com

	Elementor Extras
		Version: 2.0.9
		Author: Namogo

	Elementor Pro
		Version: 2.4.3
		Author: Elementor.com

	Everest Google Places Reviews
		Version: 2.0.2
		Author: AccessPress Themes

	Gravity Forms
		Version: 2.4.5.8
		Author: rocketgenius

	Gravity Forms Event Tracking
		Version: 2.3.5
		Author: Ronald Huereca

	Mailgun
		Version: 1.7
		Author: Mailgun

	PixelYourSite PRO
		Version: 7.0.7
		Author: PixelYourSite

	PixelYourSite Super Pack
		Version: 2.0.3
		Author: PixelYourSite

	Schema Pro
		Version: 1.1.11
		Author: Brainstorm Force

	SEOPress
		Version: 3.3.7
		Author: Benjamin Denis

	SEOPress PRO
		Version: 3.3.7
		Author: Benjamin Denis

	Testimonials Showcase
		Version: 1.9.4
		Author: Carlos Moreira

	Ultimate Addons for Elementor
		Version: 1.9.1
		Author: Brainstorm Force

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WP-Cron Control
		Version: 0.7.1
		Author: Thorsten Ott, Erick Hitter, Automattic

== Network Plugins ==
	Admin Menu Editor Pro
		Version: 2.7
		Author: Janis Elsts

	Cache Enabler
		Version: 1.3.3
		Author: KeyCDN

	Defender Pro
		Version: 2.0.1
		Author: WPMU DEV

	Multisite Privacy
		Version: 1.1.9
		Author: WPMU DEV

	Safe SVG
		Version: 1.9.1
		Author: Daryll Doyle

	Smush Pro
		Version: 3.1.1
		Author: WPMU DEV

	Ultimate Branding
		Version: 2.3.0
		Author: WPMU DEV

	WPMU DEV Dashboard
		Version: 4.6
		Author: WPMU DEV

	WP Ultimo
		Version: 1.9.7
		Author: Arindo Duque - NextPress

	WP Ultimo: Ad Injector
		Version: 1.0.1
		Author: Arindo Duque - NextPress

== Log ==
	: 
Log: showing 7 of 72019-01-21 07:39:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.1',
  'to' => '2.4.2',
)]
2019-01-21 16:20:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]
2019-01-21 16:20:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]
2019-01-25 05:54:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-01-25 05:54:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.2',
)]
2019-01-30 19:52:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-01-30 19:52:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]

PHP: showing 3 of 3PHP: 2019-01-21 07:53:44 [notice X 19][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Undefined index: top [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-01-24 08:16:30 [notice X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-01-31 01:00:54 [notice X 1][/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/css/global-css.php::129] Undefined index: scheme [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2019-01-22 00:02:23 [error X 1][https://[removed]/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view799\") has already been destroyed and cannot be used. 
JS: 2019-01-23 18:32:02 [error X 1][https://[removed]/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1477\") has already been destroyed and cannot be used. 
JS: 2019-01-23 22:02:04 [error X 3][https://[removed]/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.3:2:40665] Cannot read property \'0\' of null 
JS: 2019-01-24 12:34:58 [error X 1][https://[removed]/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.3:2:206478] Cannot read property \'html\' of undefined 
JS: 2019-01-24 13:20:22 [error X 2][https://[removed]/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.3:2:6883] Cannot read property \'select2\' of undefined 
JS: 2019-01-30 01:20:49 [error X 1][https://[removed]/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view652\") has already been destroyed and cannot be used. 
JS: 2019-01-30 04:45:13 [error X 1][https://[removed]/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1695\") has already been destroyed and cannot be used. 
</details>

**Comment by shilo-ey** [comment]
Hi @taropaa ,
Thanks for your feedback.

Elementor supports CDN services which communicate through the values that the WordPress functions retrieve.

If those plugins you've mentioned are not registering the new URL paths to WordPress, you will not be able to use them.

Other services such as CloudFlare are supported.

Thanks

**Comment by taropaa** [comment]
@shilo-ey I think this issue should be reopened. All files seem to be loading correctly with mapped domains except for /plugins/elementor/... which for some reason insist on loading from the subdomain, creating a CORS issue. I was able to deploy this on a brand new server and I am able to consistently replicate the issue.

**Comment by taropaa** [comment]
I found the cause of the problem. It's not a bug per see but it may be an oversight: When a website's domain gets switched, Elementor sticks to the old domain. I understand that this is due to one of its core selling features, which uses html rather than shortcodes to build out the page, so all image URL's on there are hard coded. It would be useful to have a function to either run when a domain name is detected or manually re-build these URL's site-wide. Otherwise, I am stuck essentially re-building the entire website when I want to switch it from dev to live.

**Comment by shilo-ey** [comment]
We have a tool for changing your URL, but not sure it will solve your issue because you are using the public domain for browsing, and internal CDN domain for files.

https://docs.elementor.com/article/218-i-changed-the-url-of-my-website-and-elementor-does-not-work-anymore

As I mentioned, Elementor supports CDN services which communicate through the values that the WordPress functions retrieve. Try using those.

Thanks

**Comment by taropaa** [comment]
@shilo-ey Wow completely missed that! Exactly what I was looking for. Thank you!
