### ISSUE TITLE
Интеграция ПопПап с Таймером 

### ISSUE THREAD

**Issue by GOHA81177** [pojome/elementor#6990]
Здравствуйте
Сделайте пожалуйста интеграцию ПопПап с Таймером 
т.е. 
Делаю ПопПап, в него заношу таймер и указываю время которое (например 10 мин) после истечения времени ПопПап должен больше не показываться!

![- -1](https://user-images.githubusercontent.com/47380983/52329573-37728a80-2a04-11e9-9195-db0c536c9c21.jpg)

С уважением Игорь

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Non-English issues will be closed!
