### ISSUE TITLE
Не работает Тригер при попытке закрыть страницу

### ISSUE THREAD

**Issue by GOHA81177** [pojome/elementor#6991]
Указываю Тригер при попытке закрыть страницу, но он не работает !

все видно на скрине!

![- -3](https://user-images.githubusercontent.com/47380983/52329987-3ee66380-2a05-11e9-8546-1df949838646.jpg)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Non-English issues will be closed!
