### ISSUE TITLE
PopPap Integration with Timer

### ISSUE THREAD

**Issue by GOHA81177** [pojome/elementor#6992]
Hello
Please integrate PopPap with Timer
those.
I do PopPap, I bring a timer into it and indicate the time that (for example, 10 minutes) after the time expires, PopPap should not show again!

![- -1](https://user-images.githubusercontent.com/47380983/52330615-e1ebad00-2a06-11e9-8ad8-375e3fc045d2.jpg)

With respect, Igor

**Comment by shilo-ey** [comment]
Hi @GOHA81177 ,

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
