### ISSUE TITLE
Trigger does not work when trying to close a page.

### ISSUE THREAD

**Issue by GOHA81177** [pojome/elementor#6993]
I point Triger when trying to close the page, but it does not work!

everything is visible on the screen!

![- -3](https://user-images.githubusercontent.com/47380983/52330728-2c6d2980-2a07-11e9-80f9-5346eb517e26.jpg)

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.

As for your question, [read more about it here](https://docs.elementor.com/article/473-why-cant-users-see-my-popup)


thanks.
