### ISSUE TITLE
Sticky Scrolling Effect stop point

### ISSUE THREAD

**Issue by benstone326** [pojome/elementor#6995]
Hello there,

I was wonder that will it be available in the near future to set a stop point for the Sticky Scrolling Effects?

For example: I started scrolling my header for the section I named #form.
So in the Sticky Scrolling Effects there will be a drop down menu, where you can choose what section do you want to stop the effect or simply write the ID of the section.

I hope you understand what I ask :)

Best regards,
Benjamin

**Comment by shilo-ey** [comment]
Hi @benstone326 

Elementor Scrolling Effect uses 
```CSS
position: fixed;
```
CSS Attribute, which applies to the entire page.

The `sticky` attributes, which we do not support currently, stays sticky while you are scrolling inside a container.

You can use custom css to add this functionality.

see reference here: https://codepen.io/nyctophiliac/pen/xpmpyp
