### ISSUE TITLE
White screen of death. php error and JS errors. 

### ISSUE THREAD

**Issue by hydex80** [pojome/elementor#6996]
Since today Im encountering problems. Elementor is not starting up and gives a white screen. In safe mode is works. I'm don't know what to do. I havent change anything  The system information is giving this:

`					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v5.6.41-84.1
	PHP Version: 5.6.40
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: http://www.geestenvrij.nl
	Home URL: http://www.geestenvrij.nl
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: Europe/Amsterdam
	Debug Mode: Inactive

== Theme ==
	Name: Reykjavik
	Version: 1.4.2
	Author: WebMan Design
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

== Active Plugins ==
	Activity Log
		Version: 2.5.2
		Author: Activity Log Team

	Add-on Contact Form 7 - Mailpoet 3
		Version: 1.3.1
		Author: Tikweb

	Akismet Anti-Spam
		Version: 4.1.1
		Author: Automattic

	Black Studio TinyMCE Widget
		Version: 2.6.6
		Author: Black Studio

	Broken Link Checker
		Version: 1.11.5
		Author: Janis Elsts, Vladimir Prelovac

	Cookie Notice
		Version: 1.2.46
		Author: dFactory

	Easy Appointments
		Version: 2.3.12
		Author: Nikola Loncar

	Elementor
		Version: 2.4.5
		Author: Elementor.com

	Elementor Blocks for Gutenberg
		Version: 1.0.1
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.3
		Author: Elementor.com

	Elements Plus!
		Version: 2.1.2
		Author: The CSSIgniter Team

	Essential Addons for Elementor
		Version: 2.9.4
		Author: WPDeveloper

	Favicon by RealFaviconGenerator
		Version: 1.3.14
		Author: Philippe Bernard

	Jetpack by WordPress.com
		Version: 7.0
		Author: Automattic

	MailPoet 3 (New)
		Version: 3.19.0
		Author: MailPoet

	Moon Phases
		Version: 3.1.1
		Author: Joe's Web Tools

	Paytium
		Version: 2.1.4
		Author: David de Boer

	Premium Addons for Elementor
		Version: 3.0.7
		Author: Leap13

	Shortcodes Ultimate
		Version: 5.2.0
		Author: Vladimir Anokhin

	Simple Image Widget
		Version: 4.4.2
		Author: Cedaro

	Site Reviews
		Version: 3.2.1
		Author: Paul Ryley

	Smush
		Version: 3.0.2
		Author: WPMU DEV

	TinyMCE Advanced
		Version: 5.0.1
		Author: Andrew Ozz

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WP Maintenance Mode
		Version: 2.2.2
		Author: Designmodo

	WP Performance Score Booster
		Version: 1.9.2.2
		Author: Dipak C. Gajjar

	WP Super Cache
		Version: 1.6.4
		Author: Automattic

	WP User Avatar
		Version: 2.1.6
		Author: flippercode

	Yoast SEO Premium
		Version: 9.5
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Log ==
	: 
Log: showing 7 of 72019-01-21 09:40:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.2',
)]
2019-01-22 13:25:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]
2019-01-22 13:27:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]
2019-01-25 12:20:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-01-30 13:44:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.2',
)]
2019-01-30 20:52:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-01-30 20:53:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]

JS: showing 3 of 3JS: 2019-01-21 14:05:20 [error X 5][http://www.geestenvrij.nl/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.2:2:82645] elementorFrontend.elements is undefined 
JS: 2019-01-25 11:21:44 [error X 55][http://www.geestenvrij.nl/wp-content/plugins/elementor/assets/js/frontend.min.js:2:15761] t.attr is not a function. (In \'t.attr(\"data-element_type\")\', \'t.attr\' is undefined) 
JS: 2019-02-05 10:51:26 [error X 2][http://www.geestenvrij.nl/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.3:2:15985] undefined is not an object (evaluating \'e.model\') 

PHP: showing 1 of 1PHP: 2019-02-06 11:39:40 [notice X 2][/home/u13176p9402/domains/geestenvrij.nl/public_html/wp-content/plugins/elementor/core/logger/items/base.php::101] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				`

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

As for your issue:
Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists. If so, try to activate one by one and see the cause of this issue.

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details and send them the System Info **& your PHP error log** (if you do not have it - ask for your hosting provider)

thanks.

**Comment by shilo-ey** [comment]
Hi @hydex80 
Try updating to the Elementor Pro to the latest version (2.4.4) and check if the issue resolved.

Thanks.

**Comment by hydex80** [comment]
Hi @shilo-ey

I discovered the issue. It was the plug-in mailpoet wich gave a conflict. After disabeling the plug-in my elementor pro is working as is Should be. Thnx for the helping hand

**Comment by shilo-ey** [comment]
Hi @hydex80 
We managed to figure it out and updated the method which MailPoet deleted.

Thanks!

**Comment by hydex80** [comment]
Ok then i reinstall mailpoet en update to 2.4.4. Good work! Thnx 2
