### ISSUE TITLE
Reveal Designed Area

### ISSUE THREAD

**Issue by tcoursey** [pojome/elementor#6998]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Would like to have an area that has elements and design that can be hidden until a click on another element has happened.  Kind of like an accordian (single)  but with that effort you can't have an entire section or things laid out with design...just text or code.

**Describe the solution you'd like**
Would be able to create a link on any element/item that could reveal a SECTION of elementor.

**Describe alternatives you've considered**
plugins...but nothing works well with elementor designed elements.

**Additional context**

**Comment by shilo-ey** [comment]
Hi @tcoursey 

We are working on a broader solution for this.

As for your specific request, you can achieve it by adding some custom JS code for now. 

Give your button a CSS ID or Class and catch the click event to run your action, for example, say your button as an ID of `MY_BTN` and you have widget you want to show/hide with the ID of `MY_WIDGET` then you can catch the click event like this:

```js
jQuery( document ).on( 'click',  '#MY_BTN', function( event ) {
   event.preventDefault();
   // Show/Hide the widget
   jQuery( '#MY_WIDGET' ).toggle();
});
```

Thanks

**Comment by tcoursey** [comment]
Thank you...that sounds interesting as a work around for now.  I'm not
familiar much with jquery...and how it works inside wordpress + elementor.
Where would i put such code?  i know where the css stuff goes...

Thanks!
