### ISSUE TITLE
is_edit_mode() and is_preview_mode() are empty

### ISSUE THREAD

**Issue by gonzalesc** [pojome/elementor#6999]
Hi.
I need to know when Im editing a post with Elementor from other plugin.

Then I have this code:

```
<?php
function timersys_init() {
	update_option('test1', print_r(\Elementor\Plugin::$instance->editor->is_edit_mode(), true));
	update_option('test2', print_r(\Elementor\Plugin::$instance->preview->is_preview_mode(), true));
}
add_action('init', 'timersys_init', 11);
?>
```

When I do click in edit a post with elementor it saves a value empty! test1 and test2 have empty values.

How do you use these methods?
Regards

**Comment by shilo-ey** [comment]
Hi @gonzalesc 

The function runs too soon.

Instead of using `init` change it to `elementor/init`. [see reference](https://code.elementor.com/hooks/elementor-init/).

Thanks.
