### ISSUE TITLE
Conflict with existing theme blurb icons

### ISSUE THREAD

**Issue by pauljnye** [pojome/elementor#700]
When elementor is enabled the following page (built with Divi page builder) displays with the icons next to each blurb missing. When I disable the elementor plugin they appear. What could be the solution?
URL:
http://pastorschaller.com/site6/what-we-believe/
Screenshot:
http://screencast.com/t/QSRTeyVZ

**Comment by arielk** [comment]
Can you please attach a screenshot of the page when Elementor enabled?

**Comment by pauljnye** [comment]
Sure:
http://screencast.com/t/bpi0seiGJdwO
FYI: I received an email from 'Boaz' on your support team related to this support request. Im just saying this to avoid 2 support staff working on my situation at the same time.

**Comment by joshmarom** [comment]
@pauljnye, As it seems like our support team has resolved this issue, I'm going to close it.

**Comment by pauljnye** [comment]
Ok thanks.

**Comment by pauljnye** [comment]
Thanks a bunch, Yes this fix worked.
Paul


--
Paul Nye
GGWO AV/IT Dept
410-483-3700 (Office)
www.ggwo.org
