### ISSUE TITLE
Add JS hooks when popup open / close

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#7001]
It would be really interesting to be able to add JS actions when a popup open or close.

Adding 2 new hooks which would receive the object of the popup would be perfect.

https://code.elementor.com/js-hooks/

**Comment by bainternet** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
