### ISSUE TITLE
Feature request: Add "in tag" to the page in the template conditions.

### ISSUE THREAD

**Issue by m2sahin** [pojome/elementor#7002]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
it becomes easier to add different headers or footers to pages. (I have problems with English, it's a little hard to explain clearly.)

**Describe the solution you'd like**
It is possible to add tags to pages. there's a plugin that is made for it and works great. But adding tag to pages would be better if it was a feature of elementor. 
https://tr.wordpress.org/plugins/tag-pages/

**Comment by bainternet** [comment]
@m2sahin 	

We feel that this is more of a 3rd party plugin territory.

thanks.

**Comment by m2sahin** [comment]
I think the elementor is no longer innovative and exciting.
