### ISSUE TITLE
Webpack & post submit actions

### ISSUE THREAD

**Issue by planet108** [pojome/elementor#7005]
Hi everybody,

You have a very nice email provider integration in your post submit actions. Now I want to extend it and add a Newsletter2go Integration. So far so good, I added a forms action in my custom php Wordpress plugin, so I can already see the action in the post submit actions panel. But the big problem I have now is that I am not allowed to inject Javascript code and use your javascript api as you make excessive use of web pack modules which are wrapped into closures. So I am kind of out of the game. So what is the solution to make newsletter2go working for us properly?

Kind Regards
Andreas

**Comment by bainternet** [comment]
@planet108 	

What's not working? what happens? what have you done?

**Comment by planet108** [comment]
Hi, i have written a Forms Action looking more or less like this and a corresponding Forms Handler Class (Newsletter2go_Handler - below) all derived from your Mailchimp integraton. (note: I am conscious about that Newsletter2go will have to work different as it is OAuth Based). Now i wanted to implement the Javascript functionality but i can't because everything is wrapped into closures with webpack. So i can't reuse your Javascript API.


`<?php
namespace ElementorPro\Modules\Forms\Actions;

use Elementor\Controls_Manager;
use ElementorPro\Modules\Forms\Classes\Ajax_Handler;
use ElementorPro\Modules\Forms\Classes\Form_Record;
use ElementorPro\Modules\Forms\Classes\Integration_Base;
use ElementorPro\Modules\Forms\Controls\Fields_Map;
use ElementorPro\Modules\Forms\Classes\Newsletter2go_Handler;
use Elementor\Settings;

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

class Newsletter2go extends Integration_Base {

    const OPTION_NAME_API_KEY = 'pro_newsletter2go_api_key';
    const OPTION_NAME_USERNAME = 'pro_newsletter2go_username';
    const OPTION_NAME_PASSWORD = 'pro_newsletter2go_password';

    private function get_global_api_key() {
        return get_option( 'elementor_' . self::OPTION_NAME_API_KEY );
    }

    public function get_name() {
        return 'newsletter2go';
    }

    public function get_label() {
        return __( 'Newsletter2go', 'elementor-pro' );
    }

    public function register_settings_section( $widget ) {
        /** var $widget Skin_Base  */
        $widget->start_controls_section(
            'section_newsletter2go',
            [
                'label' => __( 'Newsletter2go', 'elementor-pro' ),
                'condition' => [
                    'submit_actions' => $this->get_name(),
                ],
            ]
        );

        self::global_api_control(
            $widget,
            $this->get_global_api_key(),
            'Newsletter2go API Key',
            [
                'newsletter2go_api_key_source' => 'default',
            ],
            $this->get_name()
        );

        $widget->add_control(
            'newsletter2go_list',
            [
                'label' => __( 'List', 'elementor-pro' ),
                'type' => Controls_Manager::SELECT,
                'options' => [],
                'render_type' => 'none',
            ]
        );

        $widget->add_control(
            'newsletter2go_groups',
            [
                'label' => __( 'Groups', 'elementor-pro' ),
                'type' => Controls_Manager::SELECT2,
                'options' => [],
                'label_block' => true,
                'multiple' => true,
                'render_type' => 'none',
                'condition' => [
                    'newsletter2go_list!' => '',
                ],
            ]
        );

        $widget->add_control(
            'newsletter2go_double_opt_in',
            [
                'label' => __( 'Double Opt-In', 'elementor-pro' ),
                'type' => Controls_Manager::SWITCHER,
                'default' => '',
                'condition' => [
                    'newsletter2go_list!' => '',
                ],
            ]
        );

        $widget->add_control(
            'newsletter2go_fields_map',
            [
                'label' => __( 'Field Mapping', 'elementor-pro' ),
                'type' => Fields_Map::CONTROL_TYPE,
                'separator' => 'before',
                'fields' => [
                    [
                        'name' => 'remote_id',
                        'type' => Controls_Manager::HIDDEN,
                    ],
                    [
                        'name' => 'local_id',
                        'type' => Controls_Manager::SELECT,
                    ],
                ],
                'condition' => [
                    'newsletter2go_list!' => '',
                ],
            ]
        );

        $widget->end_controls_section();
    }

    public function on_export( $element ) {
        unset(
            $element['settings']['newsletter2go_api_key_source'],
            $element['settings']['newsletter2go_api_key'],
            $element['settings']['newsletter2go_list'],
            $element['settings']['newsletter2go_groups'],
            $element['settings']['newsletter2go_fields_map']
        );

        return $element;
    }

    public function run( $record, $ajax_handler ) {
        $subscriber = $this->map_fields( $record );
        $form_settings = $record->get( 'form_settings' );

        if ( ! empty( $form_settings['newsletter2go_groups'] ) ) {
            $subscriber['interests'] = [];
        }

        if ( is_array( $form_settings['newsletter2go_groups'] ) ) {
            foreach ( $form_settings['newsletter2go_groups'] as $newsletter2go_group ) {
                $subscriber['interests'][ $newsletter2go_group ] = true;
            }
        }

        try {
            $handler = new Newsletter2go_Handler( get_option('elementor_pro_newsletter2go_access_token') );

            $subscriber['status_if_new'] = 'yes' === $form_settings['newsletter2go_double_opt_in'] ? 'pending' : 'subscribed';
            $subscriber['status'] = 'subscribed';

            $end_point = sprintf( 'lists/%s/members/%s', $form_settings['newsletter2go_list'], md5( strtolower( $subscriber['email_address'] ) ) );

            $response = $handler->post( $end_point, $subscriber, [
                'method' => 'PUT', // Add or Update
            ] );

            if ( 200 !== $response['code'] ) {
                $ajax_handler->add_admin_error_message( Ajax_Handler::SERVER_ERROR );
            }
        } catch ( \Exception $exception ) {
            $ajax_handler->add_admin_error_message( 'Newsletter2go' . $exception->getMessage() );
        }
    }

    /**
     * @param Form_Record $record
     *
     * @return array
     */
    private function map_fields( $record ) {
        $subscriber = [];
        $fields = $record->get( 'fields' );

        // Other form has a field mapping
        foreach ( $record->get_form_settings( 'newsletter2go_fields_map' ) as $map_item ) {
            if ( empty( $fields[ $map_item['local_id'] ]['value'] ) ) {
                continue;
            }

            $value = $fields[ $map_item['local_id'] ]['value'];
            if ( 'email' === $map_item['remote_id'] ) {
                $subscriber['email_address'] = $value;
            } else {
                $subscriber['merge_fields'][ $map_item['remote_id'] ] = $value;
            }
        }

        return $subscriber;
    }

    public function ajax_validate_api_token() {

        check_ajax_referer( self::OPTION_NAME_API_KEY, '_nonce' );

        if ( ! isset( $_POST['api_key'] ) ) {
            wp_send_json_error();
        }
        try {

            new Newsletter2go_Handler();
        } catch ( \Exception $exception ) {
            wp_send_json_error();
        }
        wp_send_json_success();
    }

    /**
     * @param array $data
     *
     * @return array
     * @throws \Exception
     */
    public function handle_panel_request( array $data ) {

        error_log("handle_panel_request");

        $access_token = get_option('elementor_pro_newsletter2go_access_token');
        if ( empty( $access_token ) ) {
            throw new \Exception( '`access_token` is required', 400 );
        }

        $handler = new Newsletter2go_Handler($access_token);

        error_log(var_export($data,true));

        if ( 'lists' === $data['newsletter2go_action'] ) {
            return $handler->get_lists();
        }

        return $handler->get_list_details( $data['newsletter2go_list'] );
    }

    public function register_admin_fields( Settings $settings ) {

        $settings->add_section( Settings::TAB_INTEGRATIONS, 'newsletter2go', [
            'callback' => function() {
                echo '<hr><h2>' . esc_html__( 'Newsletter2go', 'elementor-pro' ) . '</h2>';
            },
            'fields' => [
                self::OPTION_NAME_API_KEY => [
                    'label' => __( 'API Key', 'elementor-pro' ),
                    'field_args' => [
                        'type' => 'text',
                        'desc' => sprintf( __( 'To integrate with our forms you need an <a href="%s" target="_blank">API Key</a>.', 'elementor-pro' ), 'https://ui.newsletter2go.com/api-client' ),
                    ],
                ],
                self::OPTION_NAME_USERNAME => [
                    'label' => __( 'Username', 'elementor-pro' ),
                    'field_args' => [
                        'type' => 'text',
                        'desc' => sprintf( __( 'To integrate with our forms you need your Username' ) ),
                    ],
                ],
                self::OPTION_NAME_PASSWORD => [
                    'label' => __( 'Password', 'elementor-pro' ),
                    'field_args' => [
                        'type' => 'password',
                        'desc' => sprintf( __( 'To integrate with our forms you need your Password' ) ),
                    ],
                ],
                'validate_api_data' => [
                    'field_args' => [
                        'type' => 'raw_html',
                        'html' => sprintf( '<button data-action="%s" data-nonce="%s" class="button elementor-button-spinner" id="elementor_pro_newsletter2go_api_key_button">%s</button>', self::OPTION_NAME_API_KEY . '_validate', wp_create_nonce( self::OPTION_NAME_API_KEY ), __( 'Get Access Token', 'elementor-pro' ) ),
                    ],
                ],
            ],
        ] );
    }

    public function __construct() {

        if ( is_admin() ) {
            add_action( 'elementor/admin/after_create_settings/' . Settings::PAGE_ID, [ $this, 'register_admin_fields' ], 15 );
        }

        add_action( 'wp_ajax_' . self::OPTION_NAME_API_KEY . '_validate', [ $this, 'ajax_validate_api_token' ] );
    }
}
`

**Forms Handler Class** 
`<?php

namespace ElementorPro\Modules\Forms\Classes;

use Elementor\Settings;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

class Newsletter2go_Handler {

	private $api_base_url = '';
	private $api_key = '';
	private $api_request_args = [];
    private $acces_token = '';

	/**
	 * Newsletter2go_Handler constructor.
	 *
	 * @param $api_key
	 *
	 * @throws \Exception
	 */
	public function __construct( $acces_token = '') {
        $this->acces_token = $acces_token;
        $this->api_key = $_POST['api_key'];
        $password = $_POST['password'];
        $username = $_POST['username'];
        $this->api_base_url = 'https://api.newsletter2go.com/';

        if (empty($acces_token)) {

            if (empty($this->api_key)) {
                throw new \Exception('Empty API key');
            }

            if (empty($username)) {
                throw new \Exception('Empty Username');
            }

            if (empty($password)) {
                throw new \Exception('Empty password');
            }

            $body = new \stdClass();
            $body->username = $username;
            $body->password = $password;
            $body->grant_type = 'https://nl2go.com/jwt';


            $this->api_request_args = [
                'headers' => [
                    'Authorization' => 'Basic ' . base64_encode($this->api_key),
                ],
                'body' => $body
            ];

            $return = $this->query('oauth/v2/token');

            update_option('elementor_pro_newsletter2go_access_token', $return['access_token']);
            update_option('elementor_pro_newsletter2go_refresh_token', $return['refresh_token']);
            update_option('elementor_pro_newsletter2go_account_id', $return['account_id']);
        } else {

            $this->api_request_args = [
                'headers' => [
                    'Authorization' => 'Bearer' . base64_encode($this->acces_token),
                ]
            ];
        }
    }

	private function query( $end_point ) {

		$response = wp_remote_get( $this->api_base_url . $end_point, $this->api_request_args );

		if ( is_wp_error( $response ) || 200 != (int) wp_remote_retrieve_response_code( $response ) ) {
			throw new \Exception( 'Newsletter2go Error' );
		}

		$body = json_decode( wp_remote_retrieve_body( $response ), true );

		if ( ! is_array( $body ) ) {
			throw new \Exception( 'Newsletter2go Error' );
		}

		return $body;
	}

	public function post( $end_point, $data, $request_args = [] ) {
		$this->api_request_args += $request_args;
		$this->api_request_args['headers']['Content-Type'] = 'application/json; charset=utf-8';
		$this->api_request_args['body'] = wp_json_encode( $data );
		$response = wp_remote_post( $this->api_base_url . $end_point, $this->api_request_args );

		if ( is_wp_error( $response ) ) {
			throw new \Exception( 'Newsletter2go Error' );
		}

		$body = json_decode( wp_remote_retrieve_body( $response ), true );

		if ( ! is_array( $body ) ) {
			throw new \Exception( 'Newsletter2go Error' );
		}

		return [
			'code' => (int) wp_remote_retrieve_response_code( $response ),
			'body' => $body,
		];
	}

	public function get_lists() {

		error_log('get_lists');

	    $results = $this->query( 'lists' );

		$lists = [
			'' => 'Select...',
		];

		if ( ! empty( $results['lists'] ) ) {
			foreach ( $results['lists'] as $list ) {
				$lists[ $list['id'] ] = $list['name'];
			}
		}

		$return_array = [
			'lists' => $lists,
		];

		return $return_array;
	}

	public function get_groups( $list_id ) {
		$results = $this->query( 'lists/' . $list_id . '/interest-categories?count=999' );
		$groups = [];

		if ( ! empty( $results['categories'] ) ) {
			foreach ( $results['categories'] as $category ) {
				$interests_results = $this->query( 'lists/' . $list_id . '/interest-categories/' . $category['id'] . '/interests?count=999' );

				foreach ( $interests_results['interests'] as $interest ) {
					$groups[ $interest['id'] ] = $category['title'] . ' - ' . $interest['name'];
				}
			}
		}

		$return_array = [
			'groups' => $groups,
		];

		return $return_array;
	}

	public function get_fields( $list_id ) {
		$results = $this->query( 'lists/' . $list_id . '/merge-fields?count=999' );

		$fields = [
			[
				'remote_label' => 'Email',
				'remote_type' => 'email',
				'remote_id' => 'email',
				'remote_required' => true,
			],
		];

		if ( ! empty( $results['merge_fields'] ) ) {
			foreach ( $results['merge_fields'] as $field ) {
				$fields[] = [
					'remote_label' => $field['name'],
					'remote_type' => $this->normalize_type( $field['type'] ),
					'remote_id' => $field['tag'],
					'remote_required' => $field['required'],
				];
			}
		}

		$return_array = [
			'fields' => $fields,
		];

		return $return_array;
	}

	public function get_list_details( $list_id ) {
		$groups = $this->get_groups( $list_id );
		$fields = $this->get_fields( $list_id );

		return [
			'list_details' => $groups + $fields,
		];
	}

	private function normalize_type( $type ) {
		static $types = [
			'text' => 'text',
			'number' => 'number',
			'address' => 'text',
			'phone' => 'text',
			'date' => 'text',
			'url' => 'url',
			'imageurl' => 'url',
			'radio' => 'radio',
			'dropdown' => 'select',
			'birthday' => 'text',
			'zip' => 'text',
		];

		return $types[ $type ];
	}

}
`

**Comment by planet108** [comment]
for instance i can't retrieve the emaillists from the Forms actions panel like in the mailchimp forms action

**Comment by bainternet** [comment]
@planet108 

Thanks for clarifying, 

As for your question, in Elementor Pro form integrations we implement an AJAX handler to fetch the lists and update the panel controls accordingly.

There is no real API in place for that, which is why you can't find any docs for it.

Also as for your example, you don't really need to copy everything there is in our classes, you are much better of following the [Custom Form Action](https://developers.elementor.com/forms-api/custom-form-action/) developer Doc.

thanks.

**Comment by danvy** [comment]
Hi,
I'd like to create a SendInBlue form action and face the same problem. Any news ?
