### ISSUE TITLE
Indicators for Changed Properties

### ISSUE THREAD

**Issue by clondon** [pojome/elementor#7006]
Hi Elementor,

I have a request for adding indicator lights to Widget controls that shows whether the widget property has had any changes from its default settings.

I find it a bit frustrating when I have to make a change as I cannot see which setting I have changed previously.

Finding settings can be a particular problem when revisiting a project.

Typically I can be looking for a property which could be in a section, a column or a widget.

My suggestion is to include an indicator of change such as a  green or grey dot or a checkmark next to the property title to indicate that its property has a changed setting.

This simple idea might save developers (and me) a few minutes per item resulting in a much slicker workflow and many time-savings.

Charles.
(Love Elementor).

![elementor indicator checkmarks](https://user-images.githubusercontent.com/887197/52415611-5eea5580-2adf-11e9-923e-14c27534b69f.jpg)

**Comment by shilo-ey** [comment]
I merged this issue with  #2180, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
