### ISSUE TITLE
ACF gallery lightbox

### ISSUE THREAD

**Issue by ericft** [pojome/elementor#7008]
Hi,

I'm using ACF Pro with the Elementor Pro image gallery module, the images show up just fine but not in the lightbox (on click). The lightbox loads empty.

https://dsh.re/dc000d
https://dsh.re/4beef

Thank you

**Comment by shilo-ey** [comment]
Hi @ericft 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Therefore we cannot replicate this issue.

**Comment by ericft** [comment]
Hi,

I just tried with a clean Wordpress install and I still have this problem.

When I create a ACF gallery field I have the option in Elementor dynamic field to select this option and I can see the gallery on my page but when I click a picture I the lightbox is empty that means the lightbox do not support the dynamic field.
