### ISSUE TITLE
Bug with Button Icon

### ISSUE THREAD

**Issue by Pagester** [pojome/elementor#701]
We've found a strange bug when using the insert icon option in the button element.

## **Problem**
When you set the alignment of the icon it saves OK, but when you then view the page outside of elementor the icon is aligned to the opposite side. Refresh the Elementor page and the icon is now incorrectly aligned in the page builder aswell, despite the options alignment setting showing correctly in the editor sidebar.

Please see the screen shots for a more detailed view of whats happening.

## **Source of Problem identified**
What we have identified is that Elementor is adding in the following class, 6 times into the span style tag
`elementor-button-icon elementor-align-icon-left`

## **Observations**
We have reproduced this 3 times but every time has been different, no specific action has caused it, it just starts happening. So while we know the source of the problem we can't identify its root cause.

If I copy the button, the copy displays correctly but the original button above continues to have incorrect alignment. If I then delete the original and leave the copy, upon save the copy now starts showing with incorrect alignment.

![elementor-button-icon-alignment-bug](https://cloud.githubusercontent.com/assets/20524372/19173923/f5517002-8c22-11e6-9787-25f7d70c9d52.gif)
![elementor-button-icon-alignment-bug-cont](https://cloud.githubusercontent.com/assets/20524372/19173924/f5524428-8c22-11e6-979c-b6ffba2cf46b.jpg)

**Comment by arielk** [comment]
The code does look strange, it looks like a conflict between plugins, theme or something like that.

Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

**Comment by Pagester** [comment]
Hi, 

This installation has no plugins apart from elementor. The site is being built with GeneratePress but we have tested with the default theme and the issue remains.

We believe this is an Elementor bug as the CSS being duplicated is Elementor classes which can only be inserted by elementor.

As to why its only doing this at random is as yet unknown

**Comment by Pagester** [comment]
**New Update**

After extensive testing we have new information that correlates this to a very unusual bug within Elementor.

In the screenshot previous you will see that there are 6 additions of the class `elementor-button-icon elementor-align-icon-left` to the button span style tag.

This number equals the number of sections on the page before the button minus 1. So the page has 7 sections minus 1 equates to 6.

## **Steps done to confirm**

So we added an icon to the button in the section above, and upon save this icon aligned incorrectly but the button below now displayed correctly.

Checking the page source the span style had a total of 5 additions of the class `elementor-button-icon elementor-align-icon-left` to the button span style tag.

This sequence continued all the way up the page with the number of class additions reducing by 1 as we got to the page top.

We also replicated the same behavior by deleting each section, each time a section was deleted the class total reduced by 1.

**Comment by agusmu** [comment]
I got this issue before, but it doesn't happen on the latest version of Elementor.

**Comment by Pagester** [comment]
@agusmu Thanks for confirming we're not the only ones that have encountered this problem. Its a pretty difficult one to pin down a root cause for.

**Comment by joshmarom** [comment]
We could not replicate this issue.
Can you please test with latest version of the plugin and report back?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

You can also contact us by support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by TsuriH** [comment]
Have the same issue how did you solve it?
