### ISSUE TITLE
Feature Request: Bulk delete revisions, based on conditions

### ISSUE THREAD

**Issue by TheMangoTrain** [pojome/elementor#7010]
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Recently I had a problem with my page never saving. I always got '500' server errors every time I pressed 'UPDATE'. The size of the page being saved was the issue. My server memory limit was being hit. My page was not long and the content normal. However I accumulated at least 100 revision states over many days. After manually deleting 20-or-so older revision states, one by one, the '500' errors never occurred.

Basically getting rid of revision states made my page smaller, so it never hit my server memory limit when attempt saving. This concept was never communicated to me, and I discovered it by accident.

**Describe the solution you'd like**
At the top of History / Revisions, there should be some kind of control that allows one to delete all revision states older than X. Currently you can only delete revision states manually, one-by-one, with multiple clicks, by pressing 'X' on each, and going through a prompt.

Instead there should be one link at the top that allows you to bulk delete revisions based on conditions. For example, "Delete revisions older than 2 days". Or the deletion could be by number... like "Delete all revision states except for the last 30 items".

Going further, there should be a global revisions control... "Delete ALL revisions". This should clear up a ton of space in a database.

In any case, this whole concept of revision management could be better communicated to the user. I only came upon it by accident, even after research.

**Comment by shilo-ey** [comment]
@TheMangoTrain 

Elementor uses the native WP revisions system, which means you can either disable it or limit its to your needs:

* Disabling Post Revisions
```
define( 'WP_POST_REVISIONS', false );
```

* Limiting Post Revisions
```
define( 'WP_POST_REVISIONS', 3 )
```

Other than that, you delete revisions either via a 3rd party plugin or a simple sql query:

```SQL
DELETE FROM wp_posts WHERE post_type = "revision";
```


thanks.

**Comment by TheMangoTrain** [comment]
Thanks, I can do those things... but for non-techie users, they'd need better UI (a shortcut) or better UX (a message that indicates what to do), especially if the idea is for Elementor to be a better product, which is ultimately the point of the feature request.

**Comment by get8bit** [comment]
+1

**Comment by DanielRuf** [comment]
> ```sql
> DELETE FROM wp_posts WHERE post_type = "revision";
> ```

This isn't enough with the new revision log feature which quickly fills up databases: https://elementor.com/help/revision-history-undo-and-redo/

**Comment by DanielRuf** [comment]
> ```sql
> DELETE FROM wp_posts WHERE post_type = "revision";
> ```

This isn't enough with the new revision log feature which quickly fills up databases: https://elementor.com/help/revision-history-undo-and-redo/

For that you need:

```sql
ELECT * 
FROM wp_postmeta pm
LEFT JOIN wp_posts wp ON wp.ID = pm.post_id
WHERE wp.ID IS NULL
```

and

```sql
DELETE pm
FROM wp_postmeta pm
LEFT JOIN wp_posts wp ON wp.ID = pm.post_id
WHERE wp.ID IS NULL
```

And don't forget to run `optimize`on the database tables.

**Comment by DanielRuf** [comment]
> ```sql
> DELETE FROM wp_posts WHERE post_type = "revision";
> ```

This isn't enough with the new revision log feature which quickly fills up databases: https://elementor.com/help/revision-history-undo-and-redo/

For that you need:

```sql
SELECT * 
FROM wp_postmeta pm
LEFT JOIN wp_posts wp ON wp.ID = pm.post_id
WHERE wp.ID IS NULL
```

and

```sql
DELETE pm
FROM wp_postmeta pm
LEFT JOIN wp_posts wp ON wp.ID = pm.post_id
WHERE wp.ID IS NULL
```

And don't forget to run `optimize`on the database tables.

**Comment by hiviz** [comment]
@DanielRuf why are the modified queries you've suggested required to handle the (new) revision log feature?

**Comment by DanielRuf** [comment]
@hiviz wp_postmeta still contains entries, you have to clean up wp_posts and wp_postmeta.

The SQL command deletes all wp_postmeta entries, which have no wp_posts entry.

**Comment by hiviz** [comment]
@DanielRuf I'm scanning through the wp_postmeta table for a website, and there's no column value (specifically, the "meta_key" and "meta_value" columns) that stands out to me that suggests that it is a revision record; by comparison, the wp_posts table has a "post_type" column with the "revision" value.

Additionally, I tried removing said "revision" records in the wp_posts table. The number of records in the wp_postmeta before and after the removal remained the same, which suggests that the wp_postmeta table doesn't store any revision records.

Your thoughts?

**Comment by DanielRuf** [comment]
@hiviz only posts has `post_type = "revision"`. postmeta only links fields like IDs.

> Additionally, I tried removing said "revision" records in the wp_posts table. The number of records in the wp_postmeta before and after the removal remained the same, which suggests that the wp_postmeta table doesn't store any revision records.

No postmeta entries are automatically deleted when you delete only entries from the posts table via SQL (without any further join or select commands). There are no cascades / triggers for `DELETE` which would clean up related entries. So you need the right SQL commands.

I had a very large postmeta table due to the revision logic of Elementor. It had to be cleaned up and `optimize` command had to be used.

Still, only deleting entries from posts and not postmeta may lead to an inconsistent database and possible problems caused by this (orphaned postmeta entries).

See also https://duckduckgo.com/?q=wordpress+delete+all+revisions+postmeta&ia=qa and more. There also options like WP CLI to make this easier.

Before doing any manual cleanup, please always make a backup and test your queries.

**Comment by hiviz** [comment]
@DanielRuf 

I realise that my earlier test was somewhat flawed. 

I conducted two new tests:
1) I first observed the number of records in the wp_postmeta and wp_posts tables. I then changed the state of a Page via the Elementor Editor, thereby creating an "Action" History. I then checked the number of records again and observed that the number hadn't changed. This suggests that [Action](https://elementor.com/help/revision-history-undo-and-redo/) events do not leave any records in the wp_postmeta or wp_posts tables.

2) I first observed the number of records in the wp_postmeta and wp_posts tables. I then changed the state of a Page via the Elementor Editor, then, clicked "update", thereby creating a "Revision" History. I then checked the number of records again and observed that the number for both tables had increased. This suggests that [Revision](https://elementor.com/help/revision-history-undo-and-redo/) events leave records in both wp_postmeta and wp_posts tables. 

So it seems only Revision events are recorded in the database, and not Action events. That being said. overall, I'm in agreement with you: 

> Still, only deleting entries from posts and not postmeta may lead to an inconsistent database and possible problems caused by this (orphaned postmeta entries).

----

@shilo-ey (is there another tag that alerts the Elementor team/admin?)

As per your suggestion:

> ...delete revisions ... via a 3rd party plugin ...

I have used a [third-party plugin to clean up the database](https://wordpress.org/plugins/advanced-database-cleaner/), but observing the number of records before and after the deletion, I've noticed that only the records in the wp_posts table, and not the wp_postmeta table had been removed. The same would have resulted had your suggestion to use the SQL query:

> DELETE FROM wp_posts WHERE post_type = "revision";

...been used.

Can you please either:
* suggest a third-party plugin that will also clean up the wp_postmeta table
* provide an "official" SQL query that will clean up the wp_postmeta table (whilst I appreciate @DanielRuf 's suggested SQL query, I would still like official confirmation from Elementor)
* echoing the sentiment of @TheMangoTrain, the ticket raiser, develop an in-house tool that will also clean up the wp_postmeta table
> Thanks, I can do those things... but for non-techie users, they'd need better UI (a shortcut) or better UX (a message that indicates what to do), especially if the idea is for Elementor to be a better product, which is ultimately the point of the feature request.

**Comment by hiviz** [comment]
[Toolkit for Elementor](https://toolkitforelementor.com/) has a "Database Optimization" features that allows you to clean up Post Revisions. I have not done a thorough check, but checking the before and after count of entries in both the wp_posts and wp_postmeta tables of the cleanup suggests that this tool removes Post Revision related entries in both tables.

**Comment by hiviz** [comment]
@DanielRuf Have you found that manually deleting records / repairing/optimising tables corrupts the table? 

I'm running into an error 500 (which doesn't explain much in and of itself) on the wp_posts table, and I can't help but suspect it happened during 'revision' post_type deletion process.

**Comment by DanielRuf** [comment]
> @DanielRuf Have you found that manually deleting records / repairing/optimising tables corrupts the table?

So far I had no issues with (manually) deleting orphaned entries from both tables.

You can try to find the real error message in the errorlog of your hosting provider / server or enable WP_DEBUG to see the actual error.

If there are conflicts like "id already exists" or similar, then your table indices may have reset / be missing.

**Comment by DanielRuf** [comment]
> It's always just the generic Error 500 when trying to view the wp_posts table via phpMyAdmin.

Sounds like a phpmyadmin issue, not related to the table content or WordPress. So the general errorlog of your webhosting should be helpful. Never had this issue so far. Some security solutions like modsecurity may also trigger a 503 (service unavailable) when a security rule is triggered.

> WP_DEBUG doesn't log phpMyAdmin activity does it?

Correct.

**Comment by hiviz** [comment]
@DanielRuf Thanks kindly - following this advice:

 > So the general errorlog of your webhosting should be helpful.

...I identified the folllowing error:
"PHP Fatal error: Allowed memory size of 134217728 bytes exhausted..."

...and so it appears that this table simply had too many characters to display (in the wp_content column) and required more memory.

So as far as I can tell, no corruption to the table, due to `DELETE` or otherwise, and is a separate issue entirely. 

Thanks so for the help!
