### ISSUE TITLE
Please update Margins and Padding boxes

### ISSUE THREAD

**Issue by Flipback8** [pojome/elementor#7012]
Divi Let's you drag the margins and Padding on the front end, which is super cool, Thrive and Webflow let you drag on the boxes and you see the changes visually, Elementor...It would be nice if they updated this, what do you guys think? Do you like inserting numbers and unchecking link box all the time?

Ex: https://prnt.sc/mi74r1

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment]
I merged this issue with  #5018, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by bentalgad** [comment]
+1
