### ISSUE TITLE
Wordpress 5 causing text spacing issues on all areas of text

### ISSUE THREAD

**Issue by Jackpedleham** [pojome/elementor#7015]
The spacing on all text elements whether it be text blocks headings or the text under an icon in an icon box is broken. It starts out greyes out at default 20 but if i set it to 0 it does nothing. Ive tried the global override too and this has no effect. It only happens with text.

**Comment by Jackpedleham** [comment]
Also sometimes when dragging in elements the element doesnt appear but the blue drop indicator remains.

**Comment by Jackpedleham** [comment]
It seems this only happens with H1 and H2 elements with the default themes

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

and we can't replicate the issue described,

Thanks.
