### ISSUE TITLE
Using elementor template inside php template file

### ISSUE THREAD

**Issue by z1020** [pojome/elementor#7023]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor is great for frontend but there are limitations of what you can do with dynamic content. There are some usefull features on backend but you will never be able to cover more that just simple and basic needs.

**Describe the solution you'd like**
There should be an easy way to use templates generated in elementor inside php template file. It would be great if I could use php to print multiple media carousels and put inside as many slides as i want adding links etc.

**Describe alternatives you've considered**
I was thinking about copying html generated in elementor and putting it into template file but html generated in elementor is quite big and there would be hassle to make it all work.

**Additional context**
If there is already some way to do it that would be quicker than designing it separate from elementor then please let me know.

**Comment by shilo-ey** [comment]
Hi @z1020 
Thanks for your feedback.

Elementor is a Visual Drag & Drop Page Builder, not a page code generator and therefore cannot be used for exporting its code.

Saying that, you can either create your own PHP section and embed it by using Shortcode, or even better - create your own widget, register your own controls using our [Developers API](https://developers.elementor.com/creating-a-new-widget/)

Thanks
