### ISSUE TITLE
Open link in new tab keyboard shortcut doesn't work on sidebar

### ISSUE THREAD

**Issue by bentalgad** [pojome/elementor#7025]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Using mac chrome if i press cmd and click on the "exit to dashboard" or any other link in the sidebar it opens in the same tab and not opening the dashboard (for example) in a new tab like normally it does when you press cmd and click on a link in mac chrome.

## Steps to reproduce
Using mac, press cmd and click on the "exit to dashboard" or any other link in the sidebar.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @bentalgad 

The option to "Exit to Dashboard" and the other panel links is to move from this page to another.

Although, we will consider adding the ability to right click on the button.

Thanks for your feedback.

**Comment by shilo-ey** [comment]
Hi @bentalgad 

This tweak has been added to Elementor 2.4.6.

Feel free to update!

thanks.

**Comment by bentalgad** [comment]
Thank you very much! that was quick and right :)
