### ISSUE TITLE
Text Editor text to stay black after changing to white

### ISSUE THREAD

**Issue by JackyDahlhaus** [pojome/elementor#7029]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate. (Well, I thought I found it, but it was closed in 2016 and not solved in a way that is of use to me). 
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When I make text white in the Elementor text editor, I can't see it anymore (in the text editor). I have to make it black again to make any amendments (so I can see what I'm doing).

**Describe the solution you'd like**
I'd like the text in the text editor to stay black after making it white as the white text will be visible on the website. 

**Describe alternatives you've considered**
An alternative is that the background in the text editor gets a color so the white text becomes visible.

**Additional context**
![image](https://user-images.githubusercontent.com/47500070/52536136-66636600-2d4e-11e9-8e78-4c2f0ea75287.png)

**Comment by shilo-ey** [comment]
Hi @JackyDahlhaus 

With [inline editing](https://elementor.com/inline-editing/) add in Elementor 1.8 you can edit the text directly on-screen.

Besides, when editing text using "Text Editor" you should not change the text color in the "Content" tab, you should do it in the "Style" tab. It has performance benefits. The style is saved in the CSS file instead of inline style.

**Comment by JackyDahlhaus** [comment]
Hi Shilo-Ey,

I have Elementor version 2.4.5, and I can do certain things inline, but not
change the color of the text. As per the image below, you can see that the
text color doesn't change when using the style function. The top two lines
remain black. I'm not sure why. It's supposed to work, but it doesn't. I've
tried the change the text color in the style tab through the section, the
column, and the individual part. Nothing works. Not sure what to do about
it.

Cheers,

Jacky D.

[image: image.png]

**Comment by shilo-ey** [comment]
Maybe you're using preformatted texts, which has inline style tags.

Try using [this tool](https://htmltidy.net/) to clean the style before pasting (or just paste it to the notepad and copy it again), and then use the style tab to select your color.

**Comment by JackyDahlhaus** [comment]
Thanks, that may be it. I'll give it a try and let you know 😊

Cheers,

Jacky D.

**Comment by JackyDahlhaus** [comment]
Yup, that was it! Thanks for letting me know 😊😘

Jacky D.
