### ISSUE TITLE
Editor weird top white space on element's selector

### ISSUE THREAD

**Issue by daviedR** [pojome/elementor#703]
Hi guys,

Is there a way to get rid the top white space caused by the editor element's selector? It gives weird white space when on editor mode. In front end, it doesn't show.

![image](https://cloud.githubusercontent.com/assets/1287713/19199060/5f5af526-8cec-11e6-9915-126d029651b9.png)

Is it possible if we can move the selector somewhere else?

**Comment by joshmarom** [comment]
Currently this is the way we avoid the child-section's selectors from interfering with it parent's selector. this will only occur in the case that the child section is the first widget in the column.

Do you feel it's a serious problem?

**Comment by daviedR** [comment]
Not a serious problem. But it shows different display between editing mode and the result. It could be ambiguous to end user.

Perhaps, we can adapt Tailor page builder way to display the selector menu:

![image](https://cloud.githubusercontent.com/assets/1287713/19236425/889e8542-8f21-11e6-9d41-d792729c80af.png)

But it's for "column" and "section" selector.

**Comment by Githubhem** [comment]
Hi! It's very uncomfortable. It shows different display between editing mode and the result.
![back](https://cloud.githubusercontent.com/assets/16056748/19765144/85bdee22-9c4f-11e6-837e-bd711cb605ec.JPG)
![front](https://cloud.githubusercontent.com/assets/16056748/19765145/85c2436e-9c4f-11e6-9ae0-949027268ac9.JPG)

**Comment by daviedR** [comment]
@Githubhem exactly!

@joshmarom I think it's quite a visual problem for end users, although it's not a bug, but it always bothers me..

**Comment by arielk** [comment]
I close this issue, because in the new version of Elementor (1.5) we have improved the whole interface of the editor, and now there is no need for this enhancement.

Thanks for your feedback!
