### ISSUE TITLE
Feature Request: Hide (or "Trim") Youtube Endscreens to Prevent Losing Customers & Valuable Traffic

### ISSUE THREAD

**Issue by TomRaraAvis** [pojome/elementor#7030]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have YouTube videos on every WooCommerce product page (using the awesome Elementor video widget) to help customers better understand exactly what the product is. I have YouTube [endscreens](https://support.google.com/youtube/answer/6388789?hl=en) on all of my YouTube videos. I believe using an endscreen at the the end of every YouTube video is now standard practice for most people who wish to keep users watching their videos. This is very helpful within the YouTube app or the YouTube website.

Unfortunately, endscreens introduce a problem when shown on videos embedded (with the Elementor widget) in a website. It gives a user the opportunity to click on an endscreen thumbnail and be carried away to the YouTube website/app — potentially losing customers. This is not good practice. One never wants to lose a customer unintentionally from a click that carries them away — bye bye valuable traffic & sales funnel.

## Video Endscreen Process/Practice & YouTube Studio Editor

I use a template that has 3 placeholder images at the end of every video. Before publishing, I use the YouTube Studio Editor to place 3 endscreen video thumbnails on top of the placeholders. Each of my endscreens use the maximum allowance of 20 seconds. So, 3 video thumbnails show for the last 20 seconds of the video while music plays. Simply removing the endscreens from showing would still allow for the ugly placeholders to be shown for 20 seconds at the end of every video.

Some people do not use placeholder images, but instead show excess video footage. They then place endscreen video thumbnails on top of the excess footage. Most of the time, endscreen audio is the YouTuber's voice encouraging the viewer to "comment, like, subscribe & click on the thumbnail to watch the next video". Viewing this portion of the video on a website is unnecessary & counterproductive. So, even if a video creator / website owner doesn't use a template with placeholders at the end, they'd still need a way to chop off the last seconds of the video — keeping only the portion of the video that is relevant to the website and/or sales page. (You can't comment, like, subscribe, or watch a suggested video from the website built with Elementor. All these suggested actions carry the user away from the website.)

There is currently no solution to rid videos of endscreens. I have considered publishing 2 videos to YouTube — one without endscreens and one with endscreens. I have also considered not using endscreens at all. I have also considered creating an entirely different YouTube channel — one for publishing unlisted videos with no endscreens & keeping the original YouTube channel videos with endscreens for my audience who only views videos on the YouTube website/app. All of these considerations pose various problems & would also require a lot of wasted time and effort in editing and publishing — doubling videos with the same content. It's all silly.

## Proposed Solution

Considering endscreens can last anywhere from 5–20 seconds, I propose a new feature to "trim" the last 5–20 seconds from the end of a video in the Elementor video widget. The new feature should probably incorporate an adjustable slider ranging 5–20 seconds. We would not actually be trimming the video at all, just choosing to hide the last seconds of the video (the endscreen) to eliminate that irrelevant content. Side Note: I would still like to maintain the option to loop playback of the video without the "trimmings" (hidden end portion).

**Comment by shilo-ey** [comment]
Hi @TomRaraAvis ,

Thanks for your feedback.

We are sorry but as you know, this is simply how YouTube embed works.

We can only suggest using either self-hosted video, Vimeo or Dailymotion as an alternative to YouTube.

Thanks.
