### ISSUE TITLE
Output content inside section wraaper

### ISSUE THREAD

**Issue by webangon** [pojome/elementor#7031]
`elementor/frontend/section/before_render` output my html content just before `section` . Is there any possibility to render inside `section`? 

Currently I am using jQuery approach to do so. Similar https://github.com/pojome/elementor/issues/2875

```
add_action( 'elementor/frontend/section/before_render',  array( $this, 'column_before_render' ) );
public function column_before_render( $element ) {
   echo '<div class="mycustom"></div>';
}

```

I want this class just inside `section` but now its placed just outside.

**Comment by bainternet** [comment]
@webangon 

All you are doing is simply printing a div with a class before the section is rendered so you are getting this as a result.

if you want to alter the output of the section you need to catch it and alter it after it renders, something like this:


```PHP
add_action( 'elementor/frontend/section/before_render', function( $section ) {
    // Catch output
    ob_start();
} );
// And then
add_action( 'elementor/frontend/section/after_render', function( $section ) {
    // Collect output
    $content = ob_get_clean();

    // Alter the output anyway you want, in your case wrapping 
    // it with a classed div should be something like this
	$content = '<div class="mycustom">' . $content . '</div>';

    // make sure to echo it
	echo $content;
} );
```

but if all you want to do add your class to the section you can use the `before_render` filter to do that, ex:

```PHP
add_action( 'elementor/frontend/section/before_render', function( $section ) {
    // Add CSS class to wrapper
	$element->add_render_attribute( '_wrapper', 'class', 'mycustom' );
} );
```

thanks.

**Comment by webangon** [comment]
Thanks for your solution. But this is not what I am looking for . Your solution does this 
```
<div class="mycustom">
    <section> all elementor output </section>
</div>
```
What I am trying to achieve 
```
<section>
  <div class="mycustom"></div>
  all elementor output
</section>
```
