### ISSUE TITLE
preview for Homepage (startpage) gets 301

### ISSUE THREAD

**Issue by Enoray** [pojome/elementor#7033]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Install Wordpress, Elementor, Elementor Pro
Set a Page as Mainpage in Wordpress.
Edit the Mainpage via Elementor
Use preview to see draft changes.
preview redirects you with a 301
?preview_nonce=XXXXXXXXXX&preview=true
to
?preview_nonce=XXXXXXXXXX

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: MySQL Community Server (GPL) v5.7.25
	PHP Version: 7.2.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: http://localhost:8000
	Home URL: http://localhost:8000
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.4.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.3
		Author: Elementor.com


== Log ==
	: 

				
```
</details>

**Comment by shilo-ey** [comment]
Hi @Enoray 

This is the way Elementor works.

Thanks for your feedback.

**Comment by Enoray** [comment]
Hello @shilo-ey that could not the way Elementor works.

The Live Preview for Drafts will not work for the Homepage this way. On other pages you do not got the redirect.
Wordpress does the preview for the Homepage with 
?preview_id=X&preview_nonce=XXXXXXXXXX&preview=true
so you do not get a 301 with redirect and u can the draft changes.

I do not understand how you just can say "This is the way Elementor works" because it is just for the Homepage and its clearly something you forgot to implement, because Wordpress do it better and it works.

Or maybe you will tell me that Elementor do not work well and you can not use all features when u set a page as Homepage.
