### ISSUE TITLE
Missing IfModule tag leads to error 500 when mod_headers is misisng

### ISSUE THREAD

**Issue by tristanleboss** [pojome/elementor#7034]
Hello,

The `.htaccess` file generated in `/wp-content/uploads/elementor/forms/` folder is missing an `<IfModule mod_headers.c>` tag.

```
Options -Indexes
<Files *.*>
Header set Content-Disposition attachment
</Files>

```

Indeed, it uses the `Header` command which is not avalaible when `mod_headers` is not avalaible.

https://httpd.apache.org/docs/2.4/fr/mod/mod_headers.html

If mod_headers is not enabled, you will get an error 500 which prevents any file in the folder to be accessed from a browser. An error is also logged in Apache error log: `.htaccess: Invalid command 'Header', perhaps misspelled or defined by a module not included in the server configuration`

**Comment by shilo-ey** [comment]
Hi @tristanleboss 

This has been fixed in Elementor Pro 2.4.4.

Feel free to update!

thanks.
