### ISSUE TITLE
Review FacetWP integration plugin?

### ISSUE THREAD

**Issue by mgibbs189** [pojome/elementor#7037]
Hey @KingYes @kobizz 

Been trying to reach the "official" Elementor channels but they keep [pointing me here](https://twitter.com/elemntor/status/1094538743292325888) :)

I'm the author of FacetWP and we've built an integration plugin with Elementor. Would you be able to sanity-check our integration code briefly before we make it public?

Also, is there a better way to keep a communication channel open between us and your dev team? Perhaps there's a dev@ email or something?

Thanks

**Comment by bainternet** [comment]
@mgibbs189 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by mgibbs189** [comment]
Email sent. Thanks @bainternet
