### ISSUE TITLE
Is it possible to be a contributor to the Pro plugin?

### ISSUE THREAD

**Issue by benallfree** [pojome/elementor#7039]
I am an experienced WP programmer and Elementor Pro subscriber. I would like to make contributions to the Elementor Pro repo. Is it possible to get private repo access?

**Comment by shilo-ey** [comment]
Hi @benallfree 

We really appreciate you for willing to contribute to our development team.

Unfortunately, by our guidelines, we do not allow access to our Pro repository for public use.

If you wish to contribute to the Pro development, please open an issue here with the code modifications you would like to see embedded in Elementor Pro and we will review it and consider adding it.

Thanks!
