### ISSUE TITLE
global section template

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#704]
Being able to save a page or section as a template is great for retaining layout/styling while allowing the site author to change the content to suit that particular page.
#### feature suggestion:

A **global** section template. Imagine you have a signup callout that appears on multiple pages. It would be great to drop it in using a global template, and only edit the **master copy** if something changes (the changes are applied to all the instances.) This would be a big time saver.

**Comment by joshmarom** [comment]
Of course. This is a very useful feature and it is one of the cool features included in the upcoming Elementor Pro.

**Comment by mizejewski** [comment]
Sounds like Pro will be a must-have upgrade. What's the ETA?

**Comment by joshmarom** [comment]
Hopefully December.

**Comment by arielk** [comment]
This feature is now available in Elementor Pro, check it out: https://elementor.com/pro/

**Comment by eplanetdesign** [comment]
Elementor Pro has Global Widgets but doesn't have Global Sections. +1 for Global Sections.

**Comment by KingYes** [comment]
@eplanetdesign: You can save your section to your Library.. and just embed this when you need this.

**Comment by eplanetdesign** [comment]
I understand how to use it Library items, Even with Pro, Sections cannot be global like Widgets. It's a royal pain, I'm within the refund window.

What do you mean by "embed"?

**Comment by KingYes** [comment]
https://docs.elementor.com/article/97-embed-templates

**Comment by slomeli79** [comment]
Unsure why this was closed. The feature requested is not in Pro.

@mizejewski was clear - the idea is to save a "master copy" (AKA global section) that works just like Global Widgets do: update in one place, and the changes are reflected across the site wherever that Global Section was added.

Templates (what IS in Pro) do not update across the site when the original is modified.

**Comment by eplanetdesign** [comment]
Most builders have this feature, Beaver Builder, Divi, etc.
This and the removal of all -webkit prefixing in the css is why I got a refund on Pro.

**Comment by mizejewski** [comment]
@slomeli79 when a template is used in many places across your site [using one of the embed methods](https://docs.elementor.com/article/97-embed-templates), it **does** update all the instances when you edit that template. In some ways this can be more powerful, but it is not very intuitive. I think a global section would still be a good thing to offer, because people understand that concept based on other patterns both in and out of Elementor.

**Comment by landyrane** [comment]
I agree that this needs to be built. I'm putting together a course and would love to have a menu that I could drop on the top of page that would update when new pages are added. Doing each would be a pain

**Comment by mizejewski** [comment]
@landyrane note that the functionality **is** there -- it's just not intuitive or parallel to the global widgets. See discussion above. I am hoping that the developers will also add a basic global section/template.

**Comment by lizalizz** [comment]
@mizejewski @slomeli79  please help me with your idea on how this should work. i really dont get it.
for me it doesnt matter if i create a global widget or template... 
for example nice little image box: i create my style, save as a template
now i can add it to many pages, but if i change the text for example... or the image... and later decide that i want another line-height... i have to apply all changes to all different pages where i use the template? how is this global ??

**Comment by slomeli79** [comment]
@lizalizz it's all about how you embed the template. It's not a regular insert-from-library. You either insert the template widget, and select from the library dropdown; OR you insert a shortcode that corresponds to your template in the library.

The video covers it: https://docs.elementor.com/article/97-embed-templates

That said, it's clearly still a clunky and confusing setup.

**Comment by lizalizz** [comment]
hej there, thanks for your answer. i guess, what i am looking for is not
invented yet. in the video she explains how to insert (embed) a template,
such as a about-section in the sidebar...
but what i wanna do is, take that section as a master thing, embed in on
different pages of my website.. and change content (different site,
different content) but still have all the styles AND when i change the
master thing (backgroundcolor..) it applies to all embed templates...
because of a globale style for example...
in the video she just inserts the same thing everywhere.

2017-08-25 16:02 GMT+02:00 slomeli79 <notifications@github.com>:

**Comment by slomeli79** [comment]
@lizalizz please see the edit to my last post. I think my video clarifies what the Elementor tutorial failed to.

**Comment by lizalizz** [comment]
Hey thanks a lot. To understand my problem: put your nice green thing on
two different pages. Change the text on page 1 to "text1" and on page two
to "text2"
Now decide, that you want to have a red background on both of them :)

If it was global as in what i am looking for, i could change in the
template the color/font-styles no matter of the different content in the
used/embed templates.

You get what i mean? I dont want the same thing on every site, but the same
looking thing (same styles) with different content/text.

I appreciate your help very much, thanks

Am Freitag, 25. August 2017 schrieb slomeli79 :

**Comment by slomeli79** [comment]
Now I understand. That's doable, too, with an add-on called Anywhere Elementor that runs about $25 per license. Lets you create global/single post templates in Elementor. (I use it personally but have no affiliation with the dev or company.)

**Comment by lizalizz** [comment]
Thanks for the tipp!
I also heared about "hero css" -also costs something
And i had hope in "style press" but it made no sense for me.

Thank you!

Am Freitag, 25. August 2017 schrieb slomeli79 :

**Comment by renathosiqueira** [comment]
I'm using [Anywhere Elementor](http://www.elementoraddons.com/anywhere-elementor-pro/) to make Global Sections. 
YES, it's a PAID plugin. But works! 
This is not a **SOLUTION**, but works **GREAT** in my sites. 
While Elementor Pro don't bring this function, we can use this workaround to create Global Sections.

**Comment by danstramer** [comment]
This should really be built in into Pro.
It misses the whole point of proper page and section templates if you can't separate style from content

**Comment by luklambrechts** [comment]
I solve it this way : 
make a section with global widgets
when you copy the section your global widgets will also be copied.
then you can change the widgets globally, or locally like you wish

**Comment by therealgilles** [comment]
Using shortcodes does not work as well as a global section as Elementor always adds a section/column layout around the shortcode.

**Comment by mikesale** [comment]
Bump again. This is a bit ugly.

**Comment by enviedbymost** [comment]
Are these closed threads ever looked at again? May be worth opening a new one.

**Comment by alexwebwork** [comment]
We need a global section template!

**Comment by m2sahin** [comment]
I'll create a global section template and add it to hundreds of pages. But the content of this global section will be different on every page. When I change settings of a global section template, I want the section settings to be changed without changing the content on each page that the section is attached to. Is this possible? I don't talk about the Global widget, the section Short code and the template widget. I know these things, They can't do what I want.

If that's not possible, why is it closed?

**Comment by brunommst** [comment]
bump, this still needs fixing
