### ISSUE TITLE
<i> icon tag accessibility issue

### ISSUE THREAD

**Issue by alamas1** [pojome/elementor#7040]
I was asked by Kai from Elementor to post the below feature request here so I can receive further updates from developers. 

I'm basically getting the following error any time I test my website's HTML code markup compliance with accessibility standards via http://achecker.ca/checker/index.php :

**> Repair: Replace your i elements with em or strong.
> 
> Error Line 434, Column 8:
> <i class="fa fa-flag" aria-hidden="true"></i>
> Error Line 441, Column 8:
> <i class="fa fa-clock-o" aria-hidden="true"></i>
> Error Line 447, Column 8:
> <i class="fa fa-phone" aria-hidden="true"></i>
> Error Line 465, Column 6:
> <i class="fa fa-facebook"></i>
> Error Line 469, Column 6:
> <i class="fa fa-twitter"></i>
> Error Line 473, Column 6:
> <i class="fa fa-linkedin"></i>
> Error Line 477, Column 6:
> <i class="fa fa-youtube"></i>
> Error Line 481, Column 6:
> <i class="fa fa-tripadvisor"></i>
> Error Line 503, Column 8:
> <i class="fa fa-flag" aria-hidden="true"></i>
> Error Line 521, Column 5:
> <i class="fa fa-map-marker" aria-hidden="true"></i>
> Error Line 536, Column 5:
> <i class="fa fa-clock-o" aria-hidden="true"></i>
> Error Line 551, Column 5:
> <i class="fa fa-search" aria-hidden="true"></i>
> Error Line 556, Column 6:
> <i class="eicon-close" aria-hidden="true"></i>
> Error Line 591, Column 474:
> <i class="icon below fa fa-home" aria-hidden="true" style="font-size:2em;vertical-align:text-bottom; ...
> Error Line 592, Column 201:
> <i class="icon below fa fa-money" aria-hidden="true" style="font-size:2em;"></i>
> Error Line 602, Column 201:
> <i class="icon below fa fa-cutlery" aria-hidden="true" style="font-size:2em;vertical-align:text-bott ...
> Error Line 608, Column 204:
> <i class="icon below fa fa-diamond" aria-hidden="true" style="font-size:2em;"></i>
> Error Line 614, Column 184:
> <i class="icon below fa fa-gift" aria-hidden="true" style="font-size:2em;"></i>
> Error Line 617, Column 4:
> <i class="eicon" aria-hidden="true"></i>
> Error Line 619, Column 397:
> <i class="icon below fa fa-home" aria-hidden="true" style="font-size:2em;vertical-align:text-bottom; ...
> Error Line 620, Column 201:
> <i class="icon below fa fa-money" aria-hidden="true" style="font-size:2em;"></i>
> Error Line 630, Column 201:
> <i class="icon below fa fa-cutlery" aria-hidden="true" style="font-size:2em;vertical-align:text-bott ...
> Error Line 636, Column 204:
> <i class="icon below fa fa-diamond" aria-hidden="true" style="font-size:2em;"></i>
> Error Line 642, Column 184:
> <i class="icon below fa fa-gift" aria-hidden="true" style="font-size:2em;"></i>
> Error Line 673, Column 5:
> <i class="fa fa-search" aria-hidden="true"></i>
> Error Line 678, Column 6:
> <i class="eicon-close" aria-hidden="true"></i>
> Error Line 734, Column 16015:
> <i class="n2i fa fa-angle-double-right" style="font-size:100%;margin-left:0.3em;"></i>
> Error Line 734, Column 36344:
> <i class="n2i fa fa-angle-double-right" style="font-size:100%;margin-left:0.3em;"></i>
> Error Line 734, Column 46331:
> <i class="n2i fa fa-angle-double-right" style="font-size:100%;margin-left:0.3em;"></i>
> Error Line 734, Column 57125:
> <i class="n2i fa fa-angle-double-right" style="font-size:80%;margin-left:0.3em;"></i>
> Error Line 871, Column 5:
> <i class="fa fa-angle-double-right" aria-hidden="true"></i>
> Error Line 927, Column 10:
> <i class="fa fa-street-view"></i>
> Error Line 964, Column 10:
> <i class="fa fa-bus"></i>
> Error Line 1001, Column 10:
> <i class="fa fa-group"></i>
> Error Line 1044, Column 10:
> <i class="fa fa-car"></i>
> Error Line 1084, Column 10:
> <i class="fa fa-wheelchair"></i>
> Error Line 1121, Column 10:
> <i class="fa fa-gift"></i>
> Error Line 1239, Column 8:
> <i class="eicon-chevron-left"></i>
> Error Line 1242, Column 8:
> <i class="eicon-chevron-right"></i>
> Error Line 1324, Column 8:
> <i class="eicon-chevron-left"></i>
> Error Line 1327, Column 8:
> <i class="eicon-chevron-right"></i>
> Error Line 1366, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1373, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1380, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1387, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1394, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1413, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1420, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1427, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1434, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1441, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1460, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1467, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1474, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1481, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1488, Column 8:
> <i class="fa fa-angle-right" aria-hidden="true"></i>
> Error Line 1623, Column 6:
> <i class="fa fa-twitter"></i>
> Error Line 1627, Column 6:
> <i class="fa fa-facebook"></i>
> Error Line 1631, Column 6:
> <i class="fa fa-linkedin"></i>
> Error Line 1635, Column 6:
> <i class="fa fa-youtube"></i>
> Error Line 1639, Column 6:
> <i class="fa fa-tripadvisor"></i>
> Error Line 1729, Column 6:
> <i class="fa fa-twitter"></i>
> Error Line 1733, Column 6:
> <i class="fa fa-facebook"></i>
> Error Line 1737, Column 6:
> <i class="fa fa-linkedin"></i>
> Error Line 1741, Column 6:
> <i class="fa fa-youtube"></i>
> Error Line 1745, Column 6:
> <i class="fa fa-tripadvisor"></i>
> Error Line 1775, Column 55:
> <i></i>
> Error Line 1775, Column 62:
> <i></i>
> Error Line 1775, Column 69:
> <i></i>
> Error Line 1783, Column 3:
> <i class="icon icon-close"></i>
> Error Line 1803, Column 4:
> <i class="icon icon-magnifier"></i>**

As I was doing some research for how to fix this, I learned that Elementor is using <i> tags to display FontAwesome icons which is nonsense and confusing for any accessibility checking tool. 

Would you be able to change the <i> to an <span> tag instead? Or any other tag that doesn't come loaded with any inappropriate semantics. For instance, if a screen reader application is in use it won't read the <span> tag because it's meaningless but it may read the <i> tag to the user and cause some confusion.

**Comment by shilo-ey** [comment]
Hi @alamas1 

When inserting an icon to an HTML webpage, we use `<i>` tag. read more [here](https://stackoverflow.com/a/14555422).

In addition, we add the attribute `ARIA-HIDDEN="TRUE"` to the icon especially for accessibility reasons, in order for screen readers to ignore these elements, so while you are using these icons for decorative uses, you are fine with accessibility compliance.

Thanks.

**Comment by jessicaoddi** [comment]
I agree this is messed up because we use the icons for things we want the screen reader to read. I don't want screen readers to ignore my social icons but putting them in an i tag is ridiculous and inaccessible.
