### ISSUE TITLE
How to set an new page insite the layoutmodus without Elementor #566 etc.

### ISSUE THREAD

**Issue by kochhase** [pojome/elementor#7041]
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
How to set an new page insite the layoutmodus without Elementor #566 etc.

**Describe the solution you'd like**
If you are working with one templates and have to make some new pages it would be very usefull to give an new page a real name not that "Elementor #001". For now we have to leave the Elementor Layoutmode or have to change all the "Elementor #001" shortecodes to real names. And to think of which shortcode has to be the right name.

**Comment by shilo-ey** [comment]
Hi @kochhase 

When you create a new page while working on a template, you will be redirected to this page.

Immediately after that redirect, you can go to the page settings [as described here](https://docs.elementor.com/article/193-document-settings) and change the page title without leaving elementor editor.

Thanks

**Comment by kochhase** [comment]
Hi shilo-ey,
but have you seen the workflow, if you use the new findertool? there you can create a new page or post as well. But then a flyout should go up where you can enter the name and then confirm. Otherwise you will not notice that the page or blog has been created with shortcode. The other way works
