### ISSUE TITLE
Widget development

### ISSUE THREAD

**Issue by stefanocavaliere** [pojome/elementor#7042]
Hello, 
I'm trying to develop a custom widget to display posts with Masonry. 
I successfully created the plugin and the widget, but I'm stuck with this part of code:

```
/**
	 * Init Controls
	 *
	 * Include controls files and register them
	 *
	 * @since 1.0.0
	 *
	 * @access public
	 */
	public function init_controls() {

		// Include Control files
		require_once( __DIR__ . '/controls/test-control.php' );

		// Register control
		\Elementor\Plugin::$instance->controls_manager->register_control( 'control-type-', new \Test_Control() );

```

which seems to point to test-control.php file that I don't know how to configure. There's no reference on the developer guide about this file. 
If I remove that part, the plugin throws an error and I can't use Elementor anymore. 

Anyone can help me? 

Thank you!

**Comment by shilo-ey** [comment]
This code is responsible for registering new custom controls you've created.

You can use our pre-existing controls to use in your new widget.

Follow instructions in the following documentation: [Click here](https://developers.elementor.com/creating-a-new-widget/).

Thanks
