### ISSUE TITLE
Menu Anchor "disappears" when adding padding.

### ISSUE THREAD

**Issue by jgatlan** [pojome/elementor#7047]
I add some padding to the bottom of my anchors because otherwise the sticky header overlaps the content. however when I do so the Anchor box disappears after a page refresh and I'm left with only the padding. The anchor still works and I can still edit it, but it's not exactly clear that it's an anchor.

This is what the anchor with padding looks like.
![anchor-with-padding](https://user-images.githubusercontent.com/28867024/52633216-fd056380-2ec3-11e9-8bce-22d2d5c239ab.jpg)
And this is what it looks like after a page refresh.
![anchor-with-padding-after-page-refresh](https://user-images.githubusercontent.com/28867024/52633215-fc6ccd00-2ec3-11e9-9b79-07b42adb5740.jpg)

**Comment by shilo-ey** [comment]
Hi @jgatlan 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* Isolating the problem.
* System info.

Thanks
