### ISSUE TITLE
Image widget caption options

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#705]
<img width="741" alt="caption" src="https://cloud.githubusercontent.com/assets/974442/19202955/c1c15de4-8c89-11e6-90a7-764f98e7431d.png">
### great features

- The option to easily create an image link with text overlay
- The automatic slight darkening of the image is helpful to make the caption overlay text visible
- The ability to add a caption that is different from the one assigned to an image in the Media Library

### feature suggestions

1. Allow an option for the caption to display underneath the image, rather than as an overlay. Sometimes the text overlay is too much.
2. Provide a style control for how much the image is darkened when there is a text overlay (similar to the existing control over image opacity.)

**Comment by joshmarom** [comment]
I just created something that's pretty much what you described.
I used a "Columns" widget with a background image and a background overlay color.
Inside that, you can pretty much insert anything you like.

It might not be the quickest and easiest way to do things, but it's there.
Elementor Pro will offer some fancier elements.

<img width="810" alt="screen shot 2016-10-10 at 10 43 33 am" src="https://cloud.githubusercontent.com/assets/2726148/19229488/9a2588b0-8ed6-11e6-87ba-c27706da2a6a.png">

**Comment by mizejewski** [comment]
Yes, I've tried using a column background image too, but it doesn't seem as stable and often becomes unaligned with the text/background color upon editing or duplicating. I look forward to seeing what Pro offers. Thanks!

**Comment by arielk** [comment]
In most cases, it should work well. Thanks for the feedback

**Comment by lukecav** [comment]
This works like a charm.

http://ielementor.com/training/elementor/elementor-for-wordpress-text-overlay-tutorial/
