### ISSUE TITLE
[Feature Request] Vertical Videos

### ISSUE THREAD

**Issue by MarcusCaeruleus** [pojome/elementor#7051]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am trying to insert a video that was shot vertically on a cell phone in to an Elementor page but am being frustrated by the fact that the only aspect ratios I can choose from seem to be landscape formats which crop a good chunk of the video.

**Describe the solution you'd like**
Please add custom aspect ratio option

**Describe alternatives you've considered**
Can't really think of any. This feels like a fairly simple issue to solve.

**Additional context**
I have a vertical video embedded on this page if you want to see how they behave without being able to select a proper aspect ratio.
https://www.manlaoriver.com/en/sister-manors/yirong-coffee-manor/?v=1c2903397d88

**Comment by shilo-ey** [comment]
Hi @MarcusCaeruleus 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

As for your request, you can currently apply this ratio with custom CSS.

Simply add this CSS code to your Video widget:
```CSS
.elementor-aspect-ratio-32 .elementor-fit-aspect-ratio {
    padding-bottom: 180%;
}
```

Thanks for the feedback.

**Comment by PG248** [comment]
I'd too like to see a custom aspect ratio for videos.

**Comment by black-eye** [comment]
+1

**Comment by dbc1998** [comment]
pls add a custom aspect ratio option for video, ive just switched over to elementor and im missing this feature for my everyday work,

**Comment by endquote** [comment]
If the video widget worked by using oEmbed, you could support any aspect ratio without selecting it explicitly. https://oembed.com

**Comment by mauricev** [comment]
Why was this closed? It seems this issue is being ignored.

**Comment by Gradivis** [comment]
+1 on this - video counts for 70% of web traffic and is increasingly being used instead of GIFS which are bulky and poor quality when optimised. Custom video ratios would be a huge bonus to Elementor and I suspect many more people would use it than those inclined to leave github comments :D

**Comment by olegzvg** [comment]
Please don't limit us to predefined aspect ratios, this is weird to see in 2023. There's no Instagram AR on the list, and why we can't show videos as is, why it has to fit in any of the predefined containers?

**Comment by frm1001xplrr** [comment]
+1

**Comment by binu-mobiux** [comment]
The padding based fix using the "elementor-fit-aspect-ratio" class doesn't work with the latest Elementor versions. You will have to use custom CSS like this for custom ratios (3.7 in this example is my video's ratio) now:
```
selector .elementor-wrapper {
    --video-aspect-ratio: 3.7 !important;
}
```

**Comment by frm1001xplrr** [comment]
This Custom CSS is easier to use because you just enter the video aspect, and it handles both the wrapper and the video element

```
selector .elementor-wrapper {
    aspect-ratio: unset;
}

selector video {
    aspect-ratio: 1920  / 1080 !important;
    height: auto;
}
```
