### ISSUE TITLE
Registering Custom Styles for frontend

### ISSUE THREAD

**Issue by stefanocavaliere** [pojome/elementor#7052]
Hello, 
I'm trying to load an external css for my custom widget. 
This is the function I'm using: 

```
public function init() {
                 //STYLES IN ELEMENTOR PREVIEW
		add_action( 'elementor/preview/enqueue_styles', function() {
		wp_enqueue_style( 'portrait-style' );
		} );
		add_action( 'elementor/frontend/after_enqueue_styles', [ $this, 'widget_styles' ] );
		add_action( 'elementor/frontend/after_register_styles', function() {
		wp_register_style( 'portrait-style', plugins_url( '/css/style.css', __FILE__ ) );
		} );
		
	}

	
	public function widget_styles() {

		wp_register_style( 'portrait-style', plugins_url( '/css/style.css', __FILE__ ) );

	}
```

I can see the style on the backend on preview but not in front end. 

How can I display styles on front end? 

Thanks!

**Comment by bainternet** [comment]
@stefanocavaliere 	

For the front end, you should register your style at `elementor/frontend/before_register_styles` hook and in your widget class you can define, `get_style_depends` method which should return an array with your style handle, and elementor will enqueue that for you when the widget is used.,

ex:

```PHP
class My_Widget extends Widget_Base {
	...
	public function get_style_depends() {
		return array( 'portrait-style' );
	}
	...
}
```
