### ISSUE TITLE
Hook to footer popup fo elemntor

### ISSUE THREAD

**Issue by sbc640964** [pojome/elementor#7053]
Is there a hook after the popup to add a script,
Wo wp_footer is before the div of the popup

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

We simply cannot understand your question.
Open a new issue with the proper structure based on our guidelines.

Thanks.
