### ISSUE TITLE
Popups appear for nothing in a page preview for nothing

### ISSUE THREAD

**Issue by sbc640964** [pojome/elementor#7054]
It's hard for me to explain in English, attached a video

![popup 1](https://user-images.githubusercontent.com/46646044/52655663-5c339a00-2efd-11e9-8646-c96e79232af3.gif)

**Comment by shilo-ey** [comment]
Hi @sbc640964 

Thanks for your feedback.

If I understand you correctly, you are in preview mode.
Visit your "Live" page and all the popups will be shown by their rules.

This issue will be fixed soon.

Thanks
