### ISSUE TITLE
Amazon Logo in Review Element

### ISSUE THREAD

**Issue by philmatt** [pojome/elementor#7057]
The **Review Element in Elementor Pro** is missing the option to use the **Amazon logo** in review slides. As the biggest e-commerce site, I would love to see the Amazon logo available in the icon selection.

Amazon Logo is in the [FontAwesome collection](https://fontawesome.com/icons/amazon).
Review Element screenshot for reference:
![screen shot 2019-02-12 at 6 00 42 pm](https://user-images.githubusercontent.com/47516673/52681440-a19d9a80-2ef0-11e9-97e0-107225544ffc.png)

**Comment by shilo-ey** [comment]
Hi @philmatt 

Thanks for your feedback!

We are currently working on a broader solution, that will allow you to better select your icons.

You can follow the #4430 thread and get notified when the new solution is available.

Thanks!
