### ISSUE TITLE
TinyMce mce_buttons cannot remove/rearrange buttons

### ISSUE THREAD

**Issue by brittaweller** [pojome/elementor#7059]
Hello all,

I noticed that it is not possible to use the common wp filter mce_buttons|mce_buttons_2 to output|remove or rearrange  the buttons of the tinymce editor elementor widget. 

I figured out that I can still add custom buttons that way but how do I remove them please?

**Comment by shilo-ey** [comment]
Hi @brittaweller 

Currently, we do not allow or recommend editing the TinyMCE controls ( eg. removing selected buttons).

You can hide specific controls with Custom CSS.

Thanks.
