### ISSUE TITLE
It does not work to save properly

### ISSUE THREAD

**Issue by royelement** [pojome/elementor#706]
First of all, I am sorry about my english, it isn't my native language

For 3 days I've tried to work with Elementor but not properly saved me what I do. I made EVERY one of the suggested steps to solve this kind of problem, even I tried DIFFERENT themes and browsers, and always the same:

1) I can not insert a template
2) I can save all sections of any template for use later ... but I can only insert one and no other
3) working from scratch do not let me save some modifications such as adding a column in a section
All this has disappointed me about this plugin, but if you have any suggestions I will try one last time

I am working on Windows 10, 64 bits, x64

**Comment by agusmu** [comment]
Hi @royelement,

Usually, the problem comes from your hosting. 

You can try to increase your WordPress Memory Limit, for example to 96MB.  

https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
