### ISSUE TITLE
What is the class for an entire elementor page except the header

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#7062]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

What is the class for an entire elementor page except for the header? Elementor Support said they didn't know and told me to write this in Github.

Right now I use responsive menu plugin and I want my hamburger sidebar to push the entire page to the left, not just the top menu. They told me to "ask Elementor Support what the custom class for an entire elementor page is?"

As you can see when you go to the following link and click the hamburger sidebar, it only pushes the 
top menu not the entire page.

My Page:
https://bit.ly/2JyZzaK

When I apply ".elementor-page"  as Elementor Support Email suggested, it moves the X and the button too...

Is there a class for everything except the header on a page?

## Steps to reproduce

N/A I just want to know the class for an entire elementor page except the header

## Isolating the problem
N/A I just want to know the class for an entire elementor page except the header

## Environment
This doesn't matter, I just want to know the class.

**Comment by bainternet** [comment]
@smile00000 	


There is no class I can name for you, it depends on too many things like:

* Theme: which could set the markup for the page or if it has elementor locations support.
* Template: same as the theme and could be changed between pages( default, canvas ....) 
* Theme builder: Again it could change depending on the way you use (if you do use).

Elementor basically injects the content in specified locations (header, content, footer...) So you would need to check your markup to get this class (if there is an actual one).

thanks.
