### ISSUE TITLE
Honeycomb Widget

### ISSUE THREAD

**Issue by Mariusfellowmedia** [pojome/elementor#7065]
Hello,

i am searching for a Honeycomb Widget and can't find it in the last 2 hours. Is it missing yet? Then i would be really thankful if someone could add it to the widgets or the block section.
If its there yet and i am just to silly to find it, then i would be grateful for help.

Best regards
Marius

**Comment by bainternet** [comment]
@Mariusfellowmedia 	

what is "Honeycomb Widget"?

You can see the list of widgets available by Elementor and Elementor Pro here: https://elementor.com/widgets/

Anything else is either custom code or by a 3rd party widget.

thanks.
