### ISSUE TITLE
Popup opens after menu click and also while hidden on mobile

### ISSUE THREAD

**Issue by odivius** [pojome/elementor#7066]
1. Desktop
![popup 1](https://user-images.githubusercontent.com/29161391/52731129-484f6d00-2fbd-11e9-87e3-e5b872fbc624.gif)

2. Mobile (problem occurs like this on my smartphone)
![popup2](https://user-images.githubusercontent.com/29161391/52731131-49809a00-2fbd-11e9-94ed-332e4afd0bbc.gif)

1. The popup is linked to the hamburger icon (image). But when I click on the navigation menu, it also opens while loading.

2. The hamburger icon from the desktop version is hidden. But when I click on the mobile hamburger menu, the popup opens. After it is closed, you can see the mobile menu.

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
