### ISSUE TITLE
Icon list bulk edit

### ISSUE THREAD

**Issue by tamelander** [pojome/elementor#7070]
Searched but could not find a similar open or closed issue.

## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have icon lists with quite a few items. Sometimes I need to change the icon for all of them. And it is tedious work.

**Describe the solution you'd like**
An option to change all icons in the icon list widget to [icon list dropdown]. Or an option to edit the icons' icons (by font-icon-id) and content in a text window. I know that for instance Formidable forms have a bulk editor for dropdowns, where you can edit the options and values in a text window: move and shuffle and add in one go. I don't know if something in that direction is feasible (that would make it much easier to move icon content between icon list widgets).

**Describe alternatives you've considered**
There is no alternative to edit icons one by one (as far as I know).

**Additional context**

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
