### ISSUE TITLE
Disable Popup for Entire Site After Clicking Close Button

### ISSUE THREAD

**Issue by katart** [pojome/elementor#7071]
I would like to have a popup appear `onPageLoad` for the Entire site. If the user clicks the close button, the popup should disappear and NOT appear on any other page.

Does the new Popup Feature allow us to prevent the popup from showing throughout the entire site if the user clicks the close button?

**Comment by bainternet** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


As for your question, Yes you can do that with Elementor Popups.


thanks.
