### ISSUE TITLE
Why does elementor _content_template use <# vs <%?

### ISSUE THREAD

**Issue by Spartanace1024** [pojome/elementor#7072]
In the _content_template function the docs state in order to use JavaScript you must use `<# ... #>`. I was curious where this syntax came from, and after more investigation found that elementor uses underscores templates.

It seams that the syntax though for underscores templating is `<% ... %>`. Why is there a change with elementor? 

Thanks in advance!

**Comment by bainternet** [comment]
@Spartanace1024 

Nice observation, The reason we use `<# ... #>` instead of the usual `<% ... %>` is because we had issues early on with server configurations that run ASP as well as PHP. So to avoid issues like that we moved to `<# ... #>`.

thanks.
