### ISSUE TITLE
Add Gradient capability for Background control

### ISSUE THREAD

**Issue by arielk** [pojome/elementor#71]

**Comment by luizbills** [comment]
Background overlay will be greate too

**Comment by arielk** [comment]
@luizbills Background overlay added in V0.4.0

**Comment by netgain** [comment]
Here's a wonderfully simple but capable UI for gradient options.
https://www.minimamente.com/example/gradient-generator/

**Comment by enkota** [comment]
Would be nice to add gradients to buttons and some other elements. Going by design recently lots of people seem to be doing it hehe 👍

**Comment by pingram3541** [comment]
Gradients would be great.  It would be nice to save them in the palette as well.  For example, it would be nice to re-use the same gradient in multiple places.

**Comment by cobicarmel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gradient for Background Control](https://trello.com/c/MntyCCFf/936-gradient-for-background-control)

**Comment by pingram3541** [comment]
Thank you! =)
