### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by Nigelballa** [pojome/elementor#715]
- Option to move the image and description above the testimonial would be handy. 
- The left align sometimes takes multiple clicks to activate.
- Option to add video section

**Comment by matthiaswagnerwy** [comment]
it would also be good to choose the image source like in the galleries. by now it happens that images that are not square get stretched inside and also it is usually not necessary to have the full-size picture in this small area.
thanks and keep on your great work!

**Comment by parfilov** [comment]
I'll Say more: "Option to move the image and description" above, on the left and on the right too "the testimonial would be handy".
Testimonials slider also must have!

Thanks!

**Comment by paaljoachim** [comment]
It would also be nice to include a link. As when I have a testimonial I might want to link to someones site or whatever.

**Comment by arielk** [comment]
Testimonial Carousel is here, released in E-Pro v1.9.0

Thanks everyone for your feedback!

**Comment by adeadebimpe** [comment]
Testimonial Carousel doesn't work. I can seem to change the sliders, the arrows and dots aren't clickable. Also, it breaks other sections beneath it.  Makes them boxed width
