### ISSUE TITLE
Can't use text editor

### ISSUE THREAD

**Issue by Fyrins** [pojome/elementor#718]
When i put a block "text editor" in my section, i can't editing the default text in the sidebar. BTW i use HTML block to replace "text editor" block.

**Comment by joshmarom** [comment]
Obviously we are not aware of such a problem with the "T
Please deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

Provide an explanation of how the bug can be reproduced, add screenshots if necessary.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by Merry-Yundi** [comment]
Yes it works! I deactivate my plugins except wp-ocean and elementor, and then I can use the "Text Editor" widget again. Thanks for your help @joshmarom
