### ISSUE TITLE
Using the header

### ISSUE THREAD

**Issue by Cookie43** [pojome/elementor#719]
I followed the examples making a practice page and everything came out excellent except for one thing: when I use the "heading" and add a title I can't align the title to center it. The other three alignments work but not the center alignment.﻿

**Comment by arielk** [comment]
The issue you opened is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.
