### ISSUE TITLE
Elementor is trying to load Ninja_Forms

### ISSUE THREAD

**Issue by edwardhew** [pojome/elementor#720]
Hi guys, trying out Elementor, looking good.

I noticed that there is a call to Ninja_Forms. I'm messing around with spl_autoload_register() on some theme code I'm working on, when I activate Elementor, I see a call to Ninja_Forms, I reloaded pages, deactivated Elementor and re-activated it, definitely called by Elementor. Aside from Elementor I have zero plugins activated.

**Comment by joshmarom** [comment]
Elementor does call Ninja Forms if it is installed, to support live rendering of a form embed (see #546).

It doesn't affect a user who doesn't have NF installed.

**Comment by edwardhew** [comment]
Thank you for your reply Josh, I see this line now, this is the Ninja_Forms call that happened.
`if ( class_exists( '\Ninja_Forms' ) ) {`

My autoloader needs fine tuning.
