### ISSUE TITLE
Backend drag & drop editor option?

### ISSUE THREAD

**Issue by ovidiuvasiliu** [pojome/elementor#726]
Are you guys considering implementing an drag & drop for the backend editing of pages/posts?

**Comment by joshmarom** [comment]
We currently do not plan on having a backend editor.
What would be the reason you would want that?

**Comment by ovidiuvasiliu** [comment]
It's useful when designing your layouts for the whole page. In these situations you don't actually need to see the full outcome of all widgets so it gives you a better overview of how the whole page would be layered out. 

There are a number of other builders that support this (visual composer / divi / etc) - that's what i'm referring to. Something that would give you this overview:

![1creatingpage](https://cloud.githubusercontent.com/assets/6876257/19350096/1285b6f6-915f-11e6-9ddb-8d937c5720c0.png)

**Comment by joshmarom** [comment]
To paraphrase what you are saying: You want a "structural" view of the page, for easier structural editing.

Is that correct?

**Comment by ovidiuvasiliu** [comment]
Yes indeed. It would also be nice if it was from the dashboard. 
Imagine content writers: all they do is create lots of pages. Switching from dashboard to frontend becomes tedious. 

As an extra request, maybe implement a panel to manage the pages/posts (Create/Update/Delete). It becomes a bit frustrating when you have to go back to the dashboard then to frontend to add the widgets.

**Comment by mizejewski** [comment]
Note that Divi is moving away from the described approach to more of a front-end solution like Elementor, no doubt based on lots of user feedback.

**Comment by agusmu** [comment]
I think this is about user preference, and I believe different product will get different user feedbacks... 

For examples:

Visual Composer starts with backend editor only, and now they improve it by adding frontend editor also... 

Tx One Pager ( https://github.com/themexpert/onepager ) has opposite story. They start with frontend editor only, but now they stop updating this repo and focus on new product, Quix pagebuilder, that is focus on backend editor only.

Ideally, it is better if Elementor has both frontend and backend editor, but I believe that it will require many effort to build backend editor.

**Comment by arielk** [comment]
Of course we want to create a more convenient interface for content editors so that they will can write and create pages faster, but we do not plan to develop back-end builder for it.

Think about the future, WordPress goes to the front, you can see the progress of the Customizer recently. This is just the beginning.

**Comment by febinpm** [comment]
Most of the Developers are working with backend editor rather than drag and drop. It is very useful if u can add the option for backend editor also.

**Comment by cbmsoftware** [comment]
I am used to Back end publishers. It is intentional to know that Elementor, one of the most used editors, does not have this function. I have even researched some add-ons not found. You can use themes that use this plugin.

**Comment by cbmsoftware** [comment]
It is tedious to use the plugin.

**Comment by ovidiuvasiliu5ps** [comment]
> Of course we want to create a more convenient interface for content editors so that they will can write and create pages faster, but we do not plan to develop back-end builder for it.
> 
> Think about the future, WordPress goes to the front, you can see the progress of the Customizer recently. This is just the beginning.

You are right, but don't forget that they're going for frontend because most of them already have the backend editor. In the end both editors are desired and it would be a shame if elementor only had one.

**Comment by cbmsoftware** [comment]
Wordpress updates and new concepts are not always a bed of roses. A major example of failure is the gutenberg. The Wordpress community repudiated. The Classic Editor has more than 20 million downloads.

I'm going to Visual composer or wpbakery page builder.

Thanks!

**Comment by saadyfernando** [comment]
Definitely a backend editor is a preferred feature by many. It would be great if elementor would allow the user to create pages in the environment that is most comfortable for the user.
