### ISSUE TITLE
[Feature request] Widget templates (Skins)

### ISSUE THREAD

**Issue by ovidiuvasiliu** [pojome/elementor#735]
Widget templates are the views in an MVC pattern. The same widget can look differently depending on the template that is set for it. 

Widget templates are phtml files (or maybe widget functions if it's too hard to move to files) that a developer can create. In a raw concept they can hold php+html+css+js code that displays the widget in different layouts.

Let's take as an example an navigation menu widget that displays the wp nagivation pages/posts.
1. The basic navigation template would be a default dropdown menu where a user could hover a menu item and see the sub-items:
   ![1](https://cloud.githubusercontent.com/assets/6876257/19360846/e1c130d4-9188-11e6-844f-60d75e079909.jpg)
2. Another template would be a list style view:
   ![2](https://cloud.githubusercontent.com/assets/6876257/19360866/f7c863d4-9188-11e6-8162-1dc2ce6b1a38.jpg)
3. Again, the same widget could be displayed as a breadcrumb:
   ![3](https://cloud.githubusercontent.com/assets/6876257/19360881/07fe79fa-9189-11e6-93f9-1175d69d4502.jpg)
4. And someone could also want a tree-view display:
   ![4](https://cloud.githubusercontent.com/assets/6876257/19361078/df9b9758-9189-11e6-84aa-697ff0262b83.jpg)

As you can see, the same widget, holding the same data, can be displayed in a different way. 
This concept can be extended to any widget, giving the person much deeper customization and saving the need to create additional widgets that are basically the same as the initial widget but look different.

The widget edit screen would have a dropdown with all the templates available for it.

This functionality could be achieved in the current state by hardcoding all php+html+js+css code for all templates in the same code and doing lots of if/else checks.

**Comment by joshmarom** [comment]
Hi @ovidiuvasiliu .

We are currently working on Elementors' developer API.
One of the new features we will introduce is something we call "Skins" for widgets. Skins allow you to create different views for a widget. This seems to be the feature you are describing.

**Comment by arielk** [comment]
Developer API is here: https://github.com/pojome/elementor/tree/master/docs

Please check it out.
