### ISSUE TITLE
[Enhancement] Selective Loading on Javascript & CSS Files

### ISSUE THREAD

**Issue by agusmu** [pojome/elementor#736]
Currently, Elementor frontend output 4 CSS and 4 JS files everywhere. 

We can do some improvements:

1) Load frontend Elementor CSS & JS file only on Elementor pages, not everywhere. We can easily check if current page is on "builder" mode then output CSS & JS files.

2) Load jQuery Numerator only when it is needed

3) Load jQuery Slick only when it is needed

4) Load Youtube Iframe API only when it is needed. Currently, it always call Youtube Iframe API, also when we don't have any video widget... :-(

I am happy to send a pull request, but I see that some pull requests from outside of your members are not responded. 

I hope you can consider this enhancements because it will improve site performance by reducing unnecessary HTTP requests. 

Thank you very much.

**Comment by arielk** [comment]
Thanks @agusmu or your request. We're still working on the API under the hood, and therefore part of the Pull Request has not yet been received. But if you have a sketch of the code for your ideas we'll be happy to review it.

**Comment by BoweFrankema** [comment]
This is definitely something I'd love to see. Even though Elementor is less heavy than other page builders, further improving enqueued assets would be sweet.

**Comment by sandeshjangam** [comment]
IMO we can also do something like this.

Lets say I am using only accordion on page. But now at this moment elemetor load whole JS and CSS file which comes with CSS of other elements also. This increase code bloat.

As currently you generating css file post. If we generate css based on elements. Would be great.

Example - I have widget - Accordion

# Module Structure

#Accordion.php - Widget File

All controls html etc here,
#Frontend.css - Common css for all instance of accordion module.

This css contain common css of all accordion instance. on save we will append this this css in you current external generated css through your way. It will append only once.
#Frontend.css.php - Dynamic CSS based on settings

In this file we can access $settings variable and bases on setting will write css. Then on save we will append this this css in you current external generated css through your way. It will append as per module instance.
#Frontend.js - Common js for all instance of accordion module

We will create external generated js as same as external css way. This js contain object of module. on save we will append this js in external generated js. It will append only once.
#Frontend.js.php - Dynamic JS based on settings

In this file we can access $settings variable and bases on setting we will initiate js object and pass required $settings value which has written in Frontend.js. Then on save we will append this this js in external generated js. It will append as per module instance.
It will reduced code bloat. It will generate only required css and js. It will also reduced page load time.

**Comment by KingYes** [comment]
For now we embed JS files just when is needed. Thanks for your feedback..

**Comment by pavner** [comment]
@KingYes @arielk Why is elementor still calling YouTube API even if there's no YouTube on the page? Is there any plan to take care of the issue? Slowing [my client's site](http://smartsale.cav.co.il/he/) by Shakuf.Media down :/ Thanks in advance :)
