### ISSUE TITLE
Questions about widgets

### ISSUE THREAD

**Issue by nicolas92** [pojome/elementor#737]
Hello,

First of all I want to say congratulations for your plugin, it is incredible.

I am trying to create custom widgets for Elementor and I asked myself two questions:

1. How you doing to make the text change is instantaneous in your widgets?
For example for your Alert widget, if I change the title, the change is instantaneous, me, on my widget there waiting two seconds.

2. What is the "_content_template()" in the widgets?
Is this a mandatory function for all widgets?

Thank you a lot :)

**Comment by joshmarom** [comment]
Hi @nicolas92 .

Thanks for the positive feedback.

An Elementor Widget can have two (mirror) templates - a PHP template (which you probably already have) and a JS template.

The JS template is only used in the editor mode for fast rendering. The JS template is created using the non mandatory `_content_template()` function. 

Note: you need to wrap the js code with `<# ... #>`.
Also note you can use a mustache-like template syntax to print js vars.

Check out our widgets for reference.
https://github.com/pojome/elementor/blob/master/includes/widgets/icon.php#L314

**Comment by nicolas92** [comment]
Hello, okay, thank you very much :)
So I can close this topic.
