### ISSUE TITLE
Small issue with custom widget

### ISSUE THREAD

**Issue by nicolas92** [pojome/elementor#738]
Hello, I'm creating a post type widget only for Elementor.
But with my code, I get the following error "Class 'Elementor\WP_Query' not found."
Can you tell me how to display a custom post type with Elementor?
Thank you a lot.

Here is my code:

```
protected function render() {
    $settings = $this->get_settings();

    // Build the WordPress query
    $oew_query = new WP_Query( array(
        'post_type'         => 'my-post-type',
        'posts_per_page'    => $settings['oew_count'],
        'order'             => $settings['oew_order'],
        'orderby'           => $settings['oew_orderby'],
    ) );

    $counter = 0;

    //Output posts
    if ( $oew_query->have_posts() ) : ?>

        <div>
            <?php
            // Start loop
            while ( $oew_query->have_posts() ) : $oew_query->the_post();

                // Create new post object.
                $post = new stdClass();

                // Get post data
                $get_post = get_post();

                // Post Data
                $post->ID           = $get_post->ID;
                $post->permalink    = get_the_permalink( $post->ID );
                $post->title        = $get_post->post_title; ?>

                <?php
                // Display thumbnail if enabled
                if ( has_post_thumbnail() ) { ?>

                    <a href="<?php echo $post->permalink; ?>" title="<?php the_title(); ?>">

                        <?php
                        // Display post thumbnail
                        the_post_thumbnail( array(
                            'alt'       => get_the_title(),
                        ) ); ?>

                    </a>

                <?php } ?>

                <a href="<?php echo $post->permalink; ?>" title="<?php the_title(); ?>"><?php echo $post->title; ?></a>
                <a href="<?php echo $post->permalink; ?>"><?php echo $settings['oew_text']; ?></a>

                <?php $counter++; ?>

            <?php
            // End entry loop
            endwhile; ?>

        </div>

        <?php
        // Reset the post data to prevent conflicts with WP globals
        wp_reset_postdata(); ?>

    <?php
    // End post check
    endif; ?>

<?php
}
```

**Comment by gcorvala** [comment]
you'll probably have to new WP_Query(..) with new \WP_Query(..)

**Comment by nicolas92** [comment]
Hello, no, it does not work at all :)

**Comment by WPDevHQ** [comment]
Try this...
`$oew_query =  new __NAMESPACE__\WP_Query(...)`

**Comment by nicolas92** [comment]
Hello, thank you very much for your answer.
Unfortunately it did not work, now I have a blank page with the error "Parse error: syntax error, unexpected '__NAMESPACE__' (T_NS_C)".

**Comment by WPDevHQ** [comment]
Is the namespace declared at the top of your file?

**Comment by nicolas92** [comment]
Yes, there are "namespace Elementor;"

**Comment by nicolas92** [comment]
Here is the full code for my custom widget but I have the error mentioned above:

```
namespace Elementor;

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Widget_CPT extends Widget_Base {

	public function get_name() {
		return 'my-cpt';
	}

	public function get_title() {
		return __( 'Post Type', 'elementor' );
	}

	public function get_icon() {
		return 'favorite';
	}

	protected function _register_controls() {

		$this->start_controls_section(
			'section_cpt',
			[
				'label' 		=> __( 'Post Type', 'elementor' ),
			]
		);

		$this->add_control(
			'count',
			[
				'label' 		=> __( 'Count', 'elementor' ),
				'type' 			=> Controls_Manager::TEXT,
				'default' 		=> '6',
				'label_block' 	=> true,
				'separator' 	=> 'before',
			]
		);

		$this->add_control(
			'order',
			[
				'label' 		=> __( 'Order', 'elementor' ),
				'type' 			=> Controls_Manager::SELECT,
				'default' 		=> '',
				'options' 		=> [
					'' 			=> __( 'Default', 'elementor' ),
					'DESC' 		=> __( 'DESC', 'elementor' ),
					'ASC' 		=> __( 'ASC', 'elementor' ),
				],
			]
		);

		$this->add_control(
			'orderby',
			[
				'label' 		=> __( 'Order By', 'elementor' ),
				'type' 			=> Controls_Manager::SELECT,
				'default' 		=> '',
				'options' 		=> [
					'' 				=> __( 'Default', 'elementor' ),
					'date' 			=> __( 'Date', 'elementor' ),
					'title' 		=> __( 'Title', 'elementor' ),
					'name' 			=> __( 'Name', 'elementor' ),
					'modified' 		=> __( 'Modified', 'elementor' ),
					'author' 		=> __( 'Author', 'elementor' ),
					'rand' 			=> __( 'Random', 'elementor' ),
					'ID' 			=> __( 'ID', 'elementor' ),
					'comment_count' => __( 'Comment Count', 'elementor' ),
					'menu_order' 	=> __( 'Menu Order', 'elementor' ),
				],
			]
		);

        $this->end_controls_section();

	}

	protected function render() {
		$settings = $this->get_settings();

		// Build the WordPress query
		$oew_query = new __NAMESPACE__\WP_Query( array(
	        'post_type'         => 'my-post-type',
	        'posts_per_page'    => $settings['count'],
	        'order'             => $settings['order'],
	        'orderby'           => $settings['orderby'],
	    ) );

		$counter = 0;

		//Output posts
		if ( $oew_query->have_posts() ) : ?>

			<div class="cpt-wrap">
				<?php
				// Start loop
				while ( $oew_query->have_posts() ) : $oew_query->the_post();

					// Create new post object.
					$post = new stdClass();

					// Get post data
					$get_post = get_post();

					// Post Data
					$post->ID           = $get_post->ID;
					$post->permalink    = get_the_permalink( $post->ID );
					$post->title        = $get_post->post_title; ?>

					<?php
	                // Display thumbnail if enabled
	                if ( has_post_thumbnail() ) { ?>

	                    <a href="<?php echo $post->permalink; ?>" title="<?php the_title(); ?>">

	                        <?php
	                        // Display post thumbnail
	                        the_post_thumbnail( array(
	                            'alt' => get_the_title(),
	                        ) ); ?>

	                    </a>

	                <?php } ?>

	                <a href="<?php echo $post->permalink; ?>" title="<?php the_title(); ?>"><?php echo $post->title; ?></a>
	                <a href="<?php echo $post->permalink; ?>"><?php echo $settings['text']; ?></a>

	                <?php $counter++; ?>

				<?php
				// End entry loop
				endwhile; ?>

			</div>

			<?php
			// Reset the post data to prevent conflicts with WP globals
			wp_reset_postdata(); ?>

		<?php
		// End post check
		endif; ?>

	<?php
	}

	protected function content_template() {}

}

Plugin::instance()->widgets_manager->register_widget_type( new Widget_CPT() );
```

**Comment by agusmu** [comment]
hi @nicolas92 

On my case, I prefer to create a custom wrapper function on separated file to call WP_Query class. 

Then I only need to call this function on my custom widget.

**Comment by nicolas92** [comment]
Hello @agusmu, can you show me your function please?
Is it possible to include attributes, if so, I would try to do the same to see if it works.
For attributes, I think something like this:
```
$oew_query = custom_query_function( array(
    'post_type'         => 'my-post-type',
    'posts_per_page'    => $settings['count'],
    'order'             => $settings['order'],
    'orderby'           => $settings['orderby'],
) );
```

Thank you very much.

**Comment by WPDevHQ** [comment]
Give me a moment - I have it showing up in the editor :)

**Comment by nicolas92** [comment]
Thank you very much :)
I hope you will get there.
I spent several hours trying to find a solution, nothing worked.
Thank you again for your help :)

**Comment by WPDevHQ** [comment]
Going to need a little more time on this. Failed to save and now its returning the same error you had :(

**Comment by WPDevHQ** [comment]
OK here goes - this gets the widget on to the editor sidebar.
![new widget post](https://cloud.githubusercontent.com/assets/16872407/19461173/4fce2e16-94da-11e6-84cc-48665c8c6375.png)
![theresults](https://cloud.githubusercontent.com/assets/16872407/19461178/5772fcdc-94da-11e6-805b-079799768ccf.png)

Here's code..
`<?php
namespace Elementor;

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}
class Widget_WP_Query extends Widget_Base {

    public function get_name() {
        return 'el-cpt';
    }

    public function get_title() {
        return __( 'Post Type', 'elementor' );
    }

    public function get_icon() {
        return 'favorite';
    }

    protected function _register_controls() {

        $this->start_controls_section(
            'section_cpt',
            [
                'label'         => __( 'Post Type', 'elementor' ),
            ]
        );

        $this->add_control(
            'count',
            [
                'label'         => __( 'Count', 'elementor' ),
                'type'          => Controls_Manager::TEXT,
                'default'       => '6',
                'label_block'   => true,
                'separator'     => 'before',
            ]
        );

        $this->add_control(
            'order',
            [
                'label'         => __( 'Order', 'elementor' ),
                'type'          => Controls_Manager::SELECT,
                'default'       => '',
                'options'       => [
                    ''          => __( 'Default', 'elementor' ),
                    'DESC'      => __( 'DESC', 'elementor' ),
                    'ASC'       => __( 'ASC', 'elementor' ),
                ],
            ]
        );

        $this->add_control(
            'orderby',
            [
                'label'         => __( 'Order By', 'elementor' ),
                'type'          => Controls_Manager::SELECT,
                'default'       => '',
                'options'       => [
                    ''              => __( 'Default', 'elementor' ),
                    'date'          => __( 'Date', 'elementor' ),
                    'title'         => __( 'Title', 'elementor' ),
                    'name'          => __( 'Name', 'elementor' ),
                    'modified'      => __( 'Modified', 'elementor' ),
                    'author'        => __( 'Author', 'elementor' ),
                    'rand'          => __( 'Random', 'elementor' ),
                    'ID'            => __( 'ID', 'elementor' ),
                    'comment_count' => __( 'Comment Count', 'elementor' ),
                    'menu_order'    => __( 'Menu Order', 'elementor' ),
                ],
            ]
        );

        $this->end_controls_section();

    }

    protected function render() {
        $settings = $this->get_settings( 'el-cpt' );
		$args = array(
            'post_type'         => 'el-cpt',
            'posts_per_page'    => $settings['count'],
            'order'             => $settings['order'],
            'orderby'           => $settings['orderby'],
        );		
        // Build the WordPress query
        $oew_query = new \WP_Query( $args );

        $counter = 0;

        //Output posts
        if ( $oew_query->have_posts() ) : ?>

            <div class="cpt-wrap">
                <?php
                // Start loop
                while ( $oew_query->have_posts() ) : $oew_query->the_post();

                    // Create new post object.
                    $post = new stdClass();

                    // Get post data
                    $get_post = get_post();

                    // Post Data
                    $post->ID           = $get_post->ID;
                    $post->permalink    = get_the_permalink( $post->ID );
                    $post->title        = $get_post->post_title; ?>

                    <?php
                    // Display thumbnail if enabled
                    if ( has_post_thumbnail() ) { ?>

                        <a href="<?php echo $post->permalink; ?>" title="<?php the_title(); ?>">

                            <?php
                            // Display post thumbnail
                            the_post_thumbnail( array(
                                'alt' => get_the_title(),
                            ) ); ?>

                        </a>

                    <?php } ?>

                    <a href="<?php echo $post->permalink; ?>" title="<?php the_title(); ?>"><?php echo $post->title; ?></a>
                    <a href="<?php echo $post->permalink; ?>"><?php echo $settings['text']; ?></a>

                    <?php $counter++; ?>

                <?php
                // End entry loop
                endwhile; ?>

            </div>

            <?php
            // Reset the post data to prevent conflicts with WP globals
            wp_reset_postdata(); ?>

        <?php
        // End post check
        endif; ?>

    <?php
    }

    protected function content_template() {}

}
Plugin::instance()->widgets_manager->register_widget_type( new Widget_WP_Query() );`

**Comment by WPDevHQ** [comment]
Just noticed that there are few PHP errors in the loop on the frontend when WP_DEBUG is set to true.

**Comment by nicolas92** [comment]
Hello, yes, I see errors too.
You have solution to solve that?
Thank you very much.

**Comment by WPDevHQ** [comment]
Haven't had the chance to look at it closelly so for the time being I've replaced the loop with the following to make sure it renders correctly on the front end...
`while ( $oew_query->have_posts() ) : $oew_query->the_post(); ?>
		    <div class="eaw-recent-posts">
			    <?php 
					if ( has_post_thumbnail() ) {
	                    the_post_thumbnail('full');
			        } ?>
					<div class="eaw-content">
	        	    <h3><a href="<?php the_permalink(); ?>"><?php get_the_title() ? the_title() : the_ID(); ?></a></h3>
				    <?php the_excerpt() . ' &hellip;'; ?>
					</div>
			</div>
		<?php 
		$counter++;
		endwhile;`

Are you using a custom method to get the widget manager to include the widget or are you plugging it directly in the manager?

**Comment by nicolas92** [comment]
Hello, thank you so much, it works perfectly :)
I create other custom widgets that work, it was only with this widget I had a problem.
To register them in Elementor, I use the action "add_action( 'elementor/widgets/widgets_registered', 'my_widgets_registered' );".

**Comment by nicolas92** [comment]
I just realized that @gcorvala had found the solution from the beginning, I do not know why I had a mistake, maybe I was wrong because now entered a code that works, thank you very much @gcorvala :)

**Comment by nicolas92** [comment]
Hello, the code works perfectly, thank you very much for your help.

I just still have a little problem but I do not know if it is possible to solve it, let me explain.

The custom widget I created is to display multiple custom post types in carousel, to do this I use the js script "owl carousel", in the front end of my website, all works perfectly, but in the preview mode of Elementor the js does not work, why?
Is it possible to solve this problem?

Thank you a lot :)

**Comment by WPDevHQ** [comment]
Not having the full code to hand I can on speculate.

I'd assume that you'll need to enqueue the scripts to take in to account being in the "Edit Mode" session, probably via an enqueue function(frontend.php @line 62) together with wp_localize_script(@line 108) might be a good starting point?

**Comment by nicolas92** [comment]
Sorry, I did not think to send you the code, here is the code I use:

```
add_action( 'wp_enqueue_scripts', 'my_scripts', 99 );
function oew_scripts() {

	// Load main stylesheet
	wp_enqueue_style( 'cpt-style', plugins_url( '/assets/css/style.min.css', __FILE__ ) );

	// Load custom js methods.
	wp_enqueue_script( 'cpt-js-scripts', plugins_url( '/assets/js/main.min.js', __FILE__ ), array( 'jquery', 'main-script' ), null, true );

}
```

The css file working well but not the js file in the preview mode of Elementor.

So I have to put my js file in this way to the front end of my site and another function to the edit mode of Elementor, right?
For the edit mode of Elementor, what do I put in the "add_action" instead of "wp_enqueue_scripts"?

Thank you a lot.

**Comment by WPDevHQ** [comment]
`add_action( 'wp_enqueue_scripts', 'oew_scripts', 999 );
function oew_scripts() {

    // Load main stylesheet
    wp_enqueue_style( 'cpt-style', plugins_url( '/assets/css/style.min.css', __FILE__ ) );
    // Load custom js methods.
    wp_enqueue_script( 'cpt-js-scripts', plugins_url( '/assets/js/main.min.js', __FILE__ ), array( 'jquery' ), null, true );

}`

**Comment by nicolas92** [comment]
Hello, thank you for the code but it still does not work in the edit mode of Elementor.
I had already tried to put several "9" to "wp_enqueue_scripts".
I saw that in some widgets of Elementor the js works well, how did they do?
Thank you.

**Comment by nicolas92** [comment]
I just saw that the js file "cpt-js-scripts" is not in the edit mode of Elementor, but what I do not understand is why the css file then work, the two files are in the same function.

**Comment by WPDevHQ** [comment]
Yeap just ran into this too after I thought I had it figured out :( - this only affects the js files!

Trying to get the attention of the team to give us some pointers on the best approach.

@arielk  - you guys able to assist here, please? All works fine on the front end but not when in the editor mode!

**Comment by nicolas92** [comment]
Hello @WPDevHQ, thank you for your help.
I found how to do until you find a solution.
I entered the js code directly in the widget only for the edit mode.

**Comment by joshmarom** [comment]
Hi guys, thank you for your involvement, it's truly heartwarming to see your fine work extending Elementor. Keep it up!

As you might be aware, we are currently developing the developer-API for Elementor. It will include a standard method for enqueuing styles and scripts in a painless manner.
So stay tuned, the API is coming soon.

**Comment by nicolas92** [comment]
Hello @joshmarom, thank you very much, I look forward to seeing the API :)

**Comment by joshmarom** [comment]
https://github.com/pojome/elementor/blob/develop/docs/content/hooks/php-hooks.md#frontend-actions

**Comment by elementoristhefuture** [comment]
@nicolas92 

Would you please share the full code that's now working? Cheers!

**Comment by luisgagocasas** [comment]
Solution
`\WP_Query()`
