### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by aryasharma36** [pojome/elementor#739]
Hi Team,

Love the plugin and the ease of how we can use it, Just wanted to request 2 features which will help me and other users.

1. Using the wordpress editor in an accordion, tabs and toggle as its really difficult to format the text inside it (usually its huge)

2. A ctrl+z , ctrl + r undo & redo option in case some elements go haywire while creating a page, will be of real help to quickly revert to the changes.

**Comment by arielk** [comment]
Thanks for your feedback!

1. Merge to #176 #303 
2. Merge to #266

**Comment by nicholaszein** [comment]
Hello there @aryasharma36!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Accordion widget was released with Elementor v3.15.0! 🥳 

With this release, you can now build your own layouts by dragging and dropping widgets inside each accordion item! 🎉 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
