### ISSUE TITLE
Wrong preview url

### ISSUE THREAD

**Issue by pySilver** [pojome/elementor#743]
Somehow preview link points to some random location (it's not even page but CPT which is _excluded_ from elementor.

![bad-preview-link](https://cloud.githubusercontent.com/assets/1113925/19583398/b0b0e0c0-973c-11e6-8bd3-916ecd2ef4ca.png)

**Comment by pySilver** [comment]
it happens only when I'm trying to edit some page that weren't created by elementor initially (it was a vanilla wp page).

**Comment by pySilver** [comment]
moreover, styles (such as borders, font colors, shadows) are also not applied to that page, while works fine on a newly created pages.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
