### ISSUE TITLE
Access to apply_builder_in_content( $content ) in our plugins

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#749]
Can you provide a fast track to how we can access this function with our plugins please? 

/elementor/includes/frontend.php L315

For example, Paid Memberships Pro plugin I needed to modify it so it would restrict Elementor page content based on membership level.  This is a crude patch.

https://gist.github.com/pingram3541/831aecf628165b5f36f856303b23b5be

**Comment by matipojo** [comment]
Hi, you can just use the filter `elementor/frontend/the_content`.

See the example below:
https://gist.github.com/matipojo/2a56dcf482a3ab9482610a93653c1116

**Comment by pingram3541** [comment]
Works perfectly thank you!

**Comment by feniksdv** [comment]
Hello, please tell me how to do the same for version 1.0.4

**Comment by matipojo** [comment]
​​Hi @feniksdv​, 
It's the same.

**Comment by feniksdv** [comment]
https://gist.github.com/matipojo/2a56dcf482a3ab9482610a93653c1116
Here's the code to insert into functions.php, truth?

**Comment by pingram3541** [comment]
@feniksdv That gist is specific to what I needed for a PMPro integration.  It would have to be modified to suit your purposes but the basics would be simply as follows:

add_filter( 'elementor/frontend/the_content', function ( $content ) {
  /****
   * Your if / else or whatever goes here to determine what
   * modifications to $content is necessary or not, then don't
   * forget to return $content
   ************************************/
});
