### ISSUE TITLE
Feature suggestion: "Elementor Widget" available in WP core widgets

### ISSUE THREAD

**Issue by m9n** [pojome/elementor#752]
It's often useful to be able to reuse widgets between a page builder and WP's core widgets UI.  For example, you might want to use an Elementor Testimonial in the middle of a page created with the Elementor builder - but somewhere else, you may just want to use a single Testimonial in the sidebar.

I can think of alternative approaches to add an Elementor widget to a sidebar.  For example, take over the whole page area with Elementor, add a Sidebar widget to a column (matching page layout with "normal" pages), and then add the extra Elementor widget in the same column as the sidebar.  Or perhaps just do away with sidebars altogether, and use Elementor templates for everything.

But I still think would be super useful and expedient to be able to include Elementor's widgets into normal sidebars.

[aside: thank you, developers, for all your work to bring this wondrous plugin to the world xx]

**Comment by joshmarom** [comment]
We are actually working on a development along those lines.

**Comment by arielk** [comment]
Currently I merged this issue with original issue #496 that our Dev staff could deal with it more efficiently. So please let's continue the conversation there.
