### ISSUE TITLE
Feature request: Display Elementor rows/sections in hook locations by using shortcodes

### ISSUE THREAD

**Issue by ciaoweb** [pojome/elementor#755]
It will be great to hook Elementor sections/rows in specific hook locations in the Genesis or any other theme that use hooks. Asking because a very popular page builder allow that by rendering the section using shortcodes. Thank you.

**Comment by arielk** [comment]
It's definitely an interesting feature. I merged this issue with another issue #496 in the same subject so that our dev staff could deal with it more efficiently. So please let's continue the conversation there.
