### ISSUE TITLE
Custom CSS saved in export.

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#765]
[WordPress 4.7](https://wordpress.org/news/2016/10/wordpress-4-7-beta-1/) includes a new live custom css feature in the customizer. It would be cool if we could somehow store custom css with the JSON export of elementor. Maybe somewhere in elementor this could be added?

An example where this would be handy would be for theme developers who make multiple "template" designs and want to keep the custom css for that "template" separate from the other designs in that theme. A user would then import that elementor template along with the custom css. Would cut down a lot of bloat in the original style.css I think 👍

**Comment by arielk** [comment]
Thanks for your idea.

Unfortunately we can't do export / import of custom CSS under the customizer of the theme with the template. It's too complex and problematic.

However, we intend to introduce soon an option to add custom CSS for each element in the plugin, so of course it will come together with the import and export of the template perfectly.

**Comment by enkota** [comment]
@arielk Awesome! Custom CSS in each element will keep things organised too actually. Looking forward to it.
