### ISSUE TITLE
Portfolio [Feature]

### ISSUE THREAD

**Issue by Anthonywp** [pojome/elementor#768]
## Portfolio [Feature]

Another great enhancement would be to add a dedicated Portfolio section instead of just relying on the Post section? 

Thank you,

**Comment by drawcard** [comment]
Have you tried making a custom post type (eg using [Pods](www.pods.io)) and using the Elementor  gallery module in conjunction with it? That's what I'm doing currently and it works well.

**Comment by Anthonywp** [comment]
Thanks drawcard the for idea but It would be more convenient if it was a part of Elementor.

Lets hope it becomes a part of it in the near future.

**Comment by HackerChick** [comment]
@drawcard - what's the Elementor gallery module? i see an image gallery but that doesn't seem to have a way to pull in custom post types...?

**Comment by arielk** [comment]
This feature is now available in Elementor Pro, check it out: https://elementor.com/pro/
