### ISSUE TITLE
Elementor seems to get stuck while loading

### ISSUE THREAD

**Issue by aliashe** [pojome/elementor#77]
Been stuck on this screen for 10+ mins. Tested in firefox and chrome. Tried refreshing.

![image](https://cloud.githubusercontent.com/assets/1608591/16053848/59a7ff50-3262-11e6-9d6a-3694e79cc0bb.png)

```
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: 5.1.73
	PHP Version: 5.6.14-0+deb8u1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes

== WordPress Environment ==
	Version: 4.5.2
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Fifteen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

== Active Plugins ==
	Elementor
		Name: Elementor
		Version: 0.2.4
		Author: Elementor.com

	Localendar Calendar for WordPress
		Name: Localendar Calendar for WordPress
		Version: 1.1.9
		Author: Thomas Griffin, localendar

	Paid Memberships Pro
		Name: Paid Memberships Pro
		Version: 1.8.6.8.1
		Author: Stranger Studios

	SEO Rank Reporter
		Name: SEO Rank Reporter
		Version: 2.2.2
		Author: David Scoville

	Ultimate Under Construction page
		Name: Ultimate Under Construction page
		Version: 1.9
		Author: HappyKite, Morrowmedia

	Yoast SEO Premium
		Name: Yoast SEO Premium
		Version: 3.0.7
		Author: Team Yoast
```

**Comment by KingYes** [comment]
Fixed by https://github.com/pojome/elementor/commit/4b5b214762c806d849f8df70cc8bc2d34fe2b9d0

**Comment by aliashe** [comment]
Thanks

Bit more info on this bug - also get this on my console.

![image](https://cloud.githubusercontent.com/assets/1608591/16054189/fc882122-3263-11e6-9579-87bf2081d5be.png)

**Comment by KingYes** [comment]
Hi @aliashe 
Please upgrade to Dev version of the Elementor, and let's me know if the bug is gone, okay?

Thanks for your report !

**Comment by aliashe** [comment]
Tried updating from the wordpress site to the dev version indicated here, correct yes?

![image](https://cloud.githubusercontent.com/assets/1608591/16057651/f10846ba-3272-11e6-808f-023a4f16133a.png)

Same exact issue.

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: 5.1.73
	PHP Version: 5.6.14-0+deb8u1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes

== WordPress Environment ==
	Version: 4.5.2
	Site URL: http://alistairashe.net.yali.mythic-beasts.com
	Home URL: http://alistairashe.net.yali.mythic-beasts.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: alistair.ashe@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Fifteen
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

== Active Plugins ==
	Elementor
		Name: Elementor
		Version: 0.2.4
		Author: Elementor.com

**Comment by KingYes** [comment]
Nope. Just upgrade from Github or wait to next upgrade in WordPres.org

**Comment by aliashe** [comment]
Yes it works now thanks KingYes

**Comment by Sellutions** [comment]
I have the exact same problem. I upgraded to the latest version of elementor, but it's still loading forever.

**Comment by tuun** [comment]
Have the same issue in Safari. Works fine in chrome.

<img width="1158" alt="screen shot 2017-06-27 at 12 37 45 pm" src="https://user-images.githubusercontent.com/12246663/27606498-7441be9e-5b35-11e7-95ba-29dfca14ed72.png">

**Comment by Webdepozit** [comment]
I have this same problem right now. Tested with WP 4.7.7, 4.8.2 and 4.8.3 and Elementor 1.7.11 and 1.7.12. Maybe 1.8.0 should work fine

**Comment by cnuvasan** [comment]
Hello Guys 
Those who use elementor.  kindly listen please.
when i use elementor i found a drawbacks that the file size of the wordpress website is too large and this is because of the image is doubled and copied in differnet and this could be found those who develop owrdpress site locally in this location **Http://localhost/wordpress/wp-content /uploads/2018/01**,  this drawback will surely reduce your site performance, and this  is tested recent wordpress version and elementor.   Can any one help me in this issue

**Comment by norewp** [comment]
@cnuvasan This issue has already been closed.

If you need assistance with an issue you will need to open your and new ticket!

**Comment by xy440** [comment]
![screenshot 2018-03-24 19 52 07](https://user-images.githubusercontent.com/5780299/37864740-3c57ea7a-2f9d-11e8-9144-045480777ee7.png)

Only one page seems issue other are working fine, this page has a bit large content. I have dedicated server with all the server requirements full filled according to elementor, there are no js issue on console so please help, thanks

**Comment by borbensir** [comment]
I have the same problem,someone please help me. When i want to use elementor it just stop at loading.

**Comment by Tropyl** [comment]
I think that you all are using Cloudflare with full SSL turn the SSL to flexible. I faced the same issue and I have fixed with this technique and it took me about 1hr to figure out what was happening.

**Comment by bentalgad** [comment]
This problem happens to me almost every update. this is really annoying! makes work harder!
