### ISSUE TITLE
[Enhancement] Masonry, Infinite Scroll and Lazy Load

### ISSUE THREAD

**Issue by lunacroft** [pojome/elementor#780]
Add masonry, infinite scroll and lazy load to image gallery would be very useful.

**Comment by arielk** [comment]
Sorry, but we do not plan to add these features soon :(

In the meantime you can use other plugins to make it.

**Comment by Mulli** [comment]
Any updates on this issue, now 12-Nov-2018?

**Comment by jaredgeddy** [comment]
Adding my own vote for this +1
