### ISSUE TITLE
Bug in Editor

### ISSUE THREAD

**Issue by copywritermg** [pojome/elementor#783]
Elementor not working after installation in WP 4.6, PHP 5.6 MySQL 5.5.49, OnePress Theme. asp_... OFF. SiteOrigin Page Builder plugin is On as will use both builders at the same time in different post/pages. Button showed but when click nothing happened. There must be a bug as it should work flawless as the videos.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
