### ISSUE TITLE
Add option to enable/disable global fonts

### ISSUE THREAD

**Issue by luizbills** [pojome/elementor#79]
I need disable google fonts because my theme that controls my fonts.

**Comment by ramsaylanier** [comment]
👍 same

**Comment by arielk** [comment]
Do you want to disable the ALL typography options in the style tabs or just the global fonts?

**Comment by luizbills** [comment]
Just the global.

**Comment by ramsaylanier** [comment]
I'd like to disable all the typography styling, personally.

**Comment by arielk** [comment]
Done https://github.com/pojome/elementor/milestone/11

**Comment by netgain** [comment]
Is there an option somewhere to disable Google fonts from loading? It appears that Google fonts are loading globally, which is adding between 0.2 to 1.4 seconds to page load speed site-wide, even on pages that don't use Google fonts. According to Google, the maximum page load time to be taken seriously in search results should be kept under 3 seconds.

One issue I noticed is that when we initially set up the pages, my designer apparently defaulted to using the "Lato" font, which has to be downloaded. Changing that font value to "Default" could take several hours. I wish I had a search/replace operation for font face settings.

56 I don't see a

**Comment by carasmo** [comment]
I have fonts disabled but when I go to styles, Google fonts are there? It's very odd.
