### ISSUE TITLE
frontend rendering issue since 0.10.5 [urgend]

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#790]
with update to 0.10.5 and tweak for [this issue](https://github.com/pojome/elementor/issues/762), i am getting a rendering error on each page on frontend where the masonry gallery pluging is active on a gallery (editor renders correctly...):

having a section with two rows in it roundabout 60:40 ratio left:right; left row has single image, right row contains gallery with three images stacked in it one under another...
this section does not cover the whole width of the content any more!
the section content covers approx. 60% left (appearing smaller than expected), right 40% remains blank.

dont have any clue whats going on!! ... and its some BIG issue, because staging site should be online next day ... *panic*

EDIT:
also having serious contend rendering issues in several other places of the site - so theres something wrong with 0.10.5 it seems!!!

EDIT #2:
rollback to 0.10.4 reveals original (and intended) behaviour! error in 0.10.5 confirmed!

**Comment by arielk** [comment]
Please let's continue the discussion on the WordPress Support Forum: https://wordpress.org/support/topic/frontend-broken-since-0-10-05/
