### ISSUE TITLE
background video glitch 

### ISSUE THREAD

**Issue by Anthonywp** [pojome/elementor#793]
## Description

I've noticed with the background url video coming from Youtube there is a weird glitch when the page first loads and it's not smooth. 

Is anyone else having this issue?

**Comment by agusmu** [comment]
yup, it is not really smooth for me too...

**Comment by Anthonywp** [comment]
I'd say the dev's need to make the video delay so that it buffers for a few seconds then loads onto the page.

**Comment by arielk** [comment]
Is this template you see the problem? https://library.elementor.com/landing-page-vacation/

**Comment by Anthonywp** [comment]
HI arielk, for me it still loads an image first, then loads the youtube screen ( which goes full black background, then loads the video.

Please see the attached imges.

![screenshot 2016-11-06 at 10 35 47 am](https://cloud.githubusercontent.com/assets/23146126/20034322/b114ba86-a40d-11e6-8fee-29d9b3496b61.png)
![screenshot 2016-11-06 at 10 35 57 am](https://cloud.githubusercontent.com/assets/23146126/20034321/b1149bbe-a40d-11e6-9b74-6815fb4ab33a.png)

**Comment by Anthonywp** [comment]
For me it's not a smooth landing page because the video background looks like it loads into the background last.

Would there be a way to have the video url be loaded first before anything else on the page maybe?

**Comment by arielk** [comment]
Which browser are you using?

**Comment by Anthonywp** [comment]
The latest Chrome version arielk.

**Comment by arielk** [comment]
It is very strange, I recorded a screen on chrome: https://vid.me/I91v (Set 720p)

**Comment by Anthonywp** [comment]
Yup, that's exactly wants happening to me while using chrome.
Does this happen on other browsers arielk?

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by rawzone** [comment]
Did you ever find a fix for this? Also having this problem. And is also happening on the template that @arielk linked.

Thanks.
