### ISSUE TITLE
use gallery into a tab

### ISSUE THREAD

**Issue by mromid** [pojome/elementor#794]
Hi
at the first i need to Thank you for this useful plugin;

but my problem is : 
i added a tab widget to the content on pages of my website , then i want to add a gallery to one of my tabs, but i cant :|

**Comment by WPDevHQ** [comment]
You can not insert an element inside another element. 

Use the gallery shortcode instead like so: [gallery ids="5,8,6,7,9,10,11,12"] - the numbers there are the image ids which you can get from the Media screen. Alternatively you can temporary create a gallery in a draft status post and then copy the shortcode from there.

**Comment by mromid** [comment]
thank's for your replay
but i want insert an element inside another element :))
for example i say "gallery"

**Comment by arielk** [comment]
I think the solution is related to the following issue #496 
We plan to release this feature in the coming week

**Comment by WPDevHQ** [comment]
@arielk - that may be a solution.

But IMHO, we need to seriously consider the implication of introducing too many shortcodes in to the plugin......as that will kind of defeat one of the plugin's USP - No Shortcodes! 

Hopefully you guys can keep them to a minimal and only introduce some where its vitally necessary!

**Comment by arielk** [comment]
@WPDevHQ Sure! 

It's just ONE shortcode for ONE specific option: Insert a template into another areas in your theme (Widgets area, Footer, Inside widget etc.)
