### ISSUE TITLE
Animation Speeds & Delays [Feature] 

### ISSUE THREAD

**Issue by Anthonywp** [pojome/elementor#801]
It would be a great enhancement to have more control over the animation speeds (milliseconds) plus have a delay speed (milliseconds) added too which would greatly add to the overall effect. 

Please see attach image

![capture](https://cloud.githubusercontent.com/assets/23146126/19987447/55176c5a-a26f-11e6-8a62-970403b34cd6.JPG)

**Comment by lunacroft** [comment]
Duplicated #558

**Comment by knireis** [comment]
would love to see this implemented!

**Comment by arielk** [comment]
I merged this issue with another issue #558 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.
