### ISSUE TITLE
user control to set default button style

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#803]
Feature request: Looks like https://github.com/pojome/elementor/pull/566/commits/c89a644e9173308de05b8bd3dd240834a2e59404 makes the default button color grey. It would be great if the **user could set a default button style** that would be used for most buttons on their site.

**Comment by arielk** [comment]
That is exactly why we added the option to set the global color :)

**Comment by rrodkin** [comment]
Global color setting is not adequate - only allows for preset collections of four colors, and form buttons get the "accent" color.  Really need a full set of specific controls just for the form button and it's various sizes.

Also, disabling Elementor's global settings does not seem to work -- I have defined button styles in Generate Press, and those aren't getting picked up at all.  Have to manually include a block of CSS in "Simple CSS" to overwrite Elementor's elementor-button style, which, as the OP noted, uses a gray background color.

It's been 2.5 years . . . can this be added back as a legitimate request, please?  Thank you!!
