### ISSUE TITLE
Add Icon Position Above for Button widget

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#804]
Feature suggestion: Widgets for Icon Box and Icon widgets both give a lot of control over icon size and placement. I would like to have similar control inside buttons, to enable styles like this http://bootsnipp.com/snippets/featured/bootstrap-square-buttons

![icon_button](https://cloud.githubusercontent.com/assets/974442/20022637/ab273e8a-a298-11e6-97ce-eb776687731a.png)

**Comment by ramiy** [comment]
@mizejewski you can do that using **Icon Box** widget.

Here is a result of a section with 5 columns, in each I use the **Icon Box** widget.

For each widget I use different background color.


![222](https://user-images.githubusercontent.com/576623/36257797-02cbbd3a-1261-11e8-8aa5-47b78ad41666.png)

**Comment by ramiy** [comment]
You can also use a background color for the column and add two Elementor widget, the first for the Icon and the second for a button. You just need to play around with the widgets.

**Comment by Christianzimpel** [comment]
Hi, I have kind of the same Problem! 
But I want that the whole think is clickable and an hover effekt (shrink) 
Any solutions?
