### ISSUE TITLE
Filter for developer to new option to settings [ Feature Request ]

### ISSUE THREAD

**Issue by sandeshjangam** [pojome/elementor#820]
## Description

I want to add extra settings ( Controls ) in section Settings. I checked but didn't see any filter for this. Can you please add this filter?

Actually i want add new setting according to setting want add html in row html. Need action for this also.

In short I want to override append my setting to row with my own add html in row.

**Comment by dtbaker** [comment]
Maybe something like this @arielk ? https://dtbaker.net/web-development/creating-your-own-custom-elementor-widgets/

**Comment by arielk** [comment]
Thank you for your kind feedback.
Your question has been asked before (#291), along with a bunch of other [Developer API](https://github.com/pojome/elementor/labels/developer%20api) related issues.
We are working on the API and hopefully it will be released in a couple of weeks.
