### ISSUE TITLE
Pages created with elementor dose not apper well in IE 11.0.35 

### ISSUE THREAD

**Issue by moosalim** [pojome/elementor#828]
Pages created with elementor dose not appear properly in IE 11.0.35. especially columns alignment beside each other. If I divide the container into two columns, they appear in one below each other

**Comment by arielk** [comment]
Can you share with us a link to the page with the problem?

**Comment by moosalim** [comment]
Thanks Arielk for your reply.

I have attached here screenshots of both Internet explorer and Chrome for comparison. you can see clearly that internet explorer is not showing the pager properly. 

![google chrome](https://cloud.githubusercontent.com/assets/23354514/20334238/f0f7502a-abd1-11e6-98b9-aa5fa6412c63.png)
![ie 11 0 36](https://cloud.githubusercontent.com/assets/23354514/20334240/f49116c6-abd1-11e6-9345-e32a7b8720fe.png)

**Comment by arielk** [comment]
I see the problem but It's a little hard to test it by the screenshots. Link to a site can be more effective.

tnx

**Comment by moosalim** [comment]
This is the link:
edu.omanr.com

**Comment by moosalim** [comment]
Hello

Any update please.

**Comment by arielk** [comment]
We're sorry but we could not reproduce this bug. Does it work for you on edge?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
