### ISSUE TITLE
Parallax?? maybe via incorporating skrollr? OR allowing Div attributes and Id's to be edited?

### ISSUE THREAD

**Issue by moses5407** [pojome/elementor#831]
Would also really love to see a mobile-compatible parallax capability.

Skrollr.js and skrollr-stylesheets.js handle this well, as used in the Morpeus theme from smallfacemedia.com.

With ability to add custom div id’s and CSS classes per element this could be done semi-manually .. but something more built-in would be very nice.

**Comment by arielk** [comment]
I merged this issue with another issue #72 in the same subject so that our Dev staff could deal with it more efficiently. So please let's continue the conversation there.
