### ISSUE TITLE
Possible improvement paragraph editor widget

### ISSUE THREAD

**Issue by h4rdc0d3** [pojome/elementor#832]
In the paragraph editor widget I would like you to be adding the plugin buttons as you do with the wordpress text editor.
For example, I installed the Crayon Syntax plugin and in the wordpress editor I add a plugin button to add code, but when I want to edit text with the paragraph editor widget the plugin button does not appear.

**Comment by arielk** [comment]
Sorry, but we can't support adding capabilities to the text editor of WordPress (TinyMCE) as you're asked. If there is an additional widget or Shortcode you can do so easily.
