### ISSUE TITLE
Responsive font sizes bug

### ISSUE THREAD

**Issue by Githubhem** [pojome/elementor#833]
Hi!

For example i set font size:
1) Desktop: 48px
2) Tablet: 24 px
3) Mobile: 12 px

If i do it, mobile version will be ignore 12px option. Font size wiil be 24 px.

**Comment by arielk** [comment]
Which mobile device you checked it?

You can send us a link to the page?

**Comment by Githubhem** [comment]
Hi!

Iphone 5s. And testing tool http://lab.maltewassermann.com/viewport-resizer/

http://relfy.ru/sk/
For example phone number. It happens only if i set the font size for all devices. If i ignore tablet and set only desktop and mobile - it works.

**Comment by arielk** [comment]
It seems that Elementor is not print the CSS of the page in the right order (Desktop > Tablet  > Mobile).

In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
