### ISSUE TITLE
Inner Section Columns

### ISSUE THREAD

**Issue by mavenos** [pojome/elementor#837]
If I place a text or a header element into an inner section column, I can't see the text in the Wordpress-Editor and it's not analysed in Yoast-Seo.
Text or Header Elements are only visible in the Wordpress-Editor or analysed in Yoast-Seo, if they are placed in a normal section.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
