### ISSUE TITLE
Add Google Analytics functionality (Events) for Buttons

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#838]
There is no simple way to add the snippets of code used by Google Analytics to track various events. For example, if you want to add a snippet such as 
onclick=”ga(‘send’, ‘event’, ‘button’, ‘click’, ‘blahblah’);”
to a link, you cannot currently do it directly in the field used to define link, because the single and double quotes get rewritten by elementor with their html code equivalents.

Therefore, I suggest adding functionality to capture google analytics code (and perhaps code for other analytics services, too). Possible solutions might be:
- being able to escape characters in the link fields - for example, \" becomes ", not &quot; and \' becomes ', not  & # 0 3 9 ;
- having a separate field for additional code specific to analytics

I would be happy with either one, although adding an escape character creates the issue of handling code already recorded that includes that character.

**Comment by bmwillrath** [comment]
+1

**Comment by rwattner** [comment]
+1

**Comment by joffcrabtree** [comment]
+1

**Comment by ramiy** [comment]
+1

**Comment by r-dave** [comment]
+3

**Comment by Adiyagil** [comment]
+1

**Comment by hogash** [comment]
Hey guys! You could use this code to append an custom text field and add it as an attribute to the button eg:

```
function wp222_custom_button_field( $button, $args ) {

	$button->add_control(
		'onclick_attr',
		[
			'label' => __( 'OnClick attribute', 'text-domain' ),
			'type' => \Elementor\Controls_Manager::TEXT,
		]
	);
}
add_action( 'elementor/element/button/section_button/before_section_end', 'wp222_custom_button_field', 10, 2 );


function wp222_custom_render_button( $button ) {
	//Check if we are on a button
	if( 'button' === $button->get_name() ) {
		// Get the settings
		$settings = $button->get_settings();

		// Adding our type as an attribute to the button
		if( $settings['onclick_attr'] ) {
			$button->add_render_attribute( 'button', 'onclick', $settings['onclick_attr'], true );
		}
	}
}
add_action( 'elementor/widget/before_render_content', 'wp222_custom_render_button' );
```

eg: http://take.ms/Zrf2z and http://take.ms/8eSVf .

**Comment by Adiyagil** [comment]
@hogash good idea. Where should I implement your suggestion in order to have this field on every button on my site?

**Comment by hogash** [comment]
@Adiyagil you could try using this plugin https://wordpress.org/plugins/code-snippets/ to paste this code snippet. An alternative would be to use a child theme and add this code into its functions.php file.

**Comment by Adiyagil** [comment]
@hogash thanks! I've used the code snippet plugin to add it. Tracking how thing perform is a crucial part of any button..it's strange to me that it's not included native within Elementor.

**Comment by Adiyagil** [comment]
@hogash - would it be possible to change this snippet to include the OnClick attribute to an image widget as well? (most of my images are clickable). Thanks again for your help:)

**Comment by Adiyagil** [comment]
@arielk I think it's important (and I'm sure most would agree with me) that this ability for OnClick attribution should be added to not only for button widgets but also image widget. Any ETA for this?

**Comment by JosiahCarberry** [comment]
@hogash For those of us less technically inclined, may I ask confirmation on what needs to be done:
1) ensure that the page(s) concerned have Google's analytics.js called
2) Add the function you provided to functions.php
3) add the onclick javascript function desired for each button
I found this on the page https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs#events :
ga('send', 'event', 'category', 'action', 'opt_label', opt_value, {'nonInteraction': 1});
I presume that is the right code (assuming analytics.js, not ga.js)

Is that correct?

**Comment by drank** [comment]
Just out of curiosity - why not use Google Tag Manager for button click tracking, e.g. https://mediacause.org/track-button-clicks-google-tag-manager/ ?

**Comment by JosiahCarberry** [comment]
@drank It seems like half of one, six dozen of the other. If Elementor were to add the functionality that @hogash proposed above, it would be an elegant solution to meet the requirement. If not, well, there are other ways to skin the cat.

**Comment by eloithomaz** [comment]
@hogash how to add this custom text field in the elementor form button?

**Comment by EdenK** [comment]
+1 need to add some JS events \ hooks too.

**Comment by ramiy** [comment]
This feature can be implemented with the new **Element Attributes** planned for Elementor 2.1 (see PR #4030).

You can set a custom `onClick` attribute with the value of `ga( 'send', 'event', 'button', 'click', 'blahblah' );`.

**Comment by gravnetic** [comment]
Use Google Tag Manager it is the proper way to do this...

**Comment by bainternet** [comment]
This can be done by defining CSS ID to the button and use that as a selector  for event tracking, ex:

```Javascript
jQuery( document ).ready(function( $ ){
	$( '#CSS_ID' ).on('click', function(){
		ga( 'send', 'event', 'button', 'click', 'blahblah' );
		// Or what ever other tracking or action you want on this event
	});
});
```

Thanks for the suggestion.

**Comment by szabeee** [comment]
@bainternet where should I insert this, in Elementor?

**Comment by Testinat0r** [comment]
+99

**Comment by theDanielJLewis** [comment]
I know this is old, but is there a solution to this? Custom Attributes block Javascript events "for security."

**Comment by fxaviers** [comment]
The onclick event is not yet supported.
Is there any technical reason for this?
