### ISSUE TITLE
Elementor never loads

### ISSUE THREAD

**Issue by wonderment** [pojome/elementor#84]
We're exploring Elementor as a page builder and aren't able to work with it because upon editing the standard WordPress sample page, it hangs on the loading graphic indefinitely.

The test site is using PHP Version 5.5.35 and MySQL 5.1.73 with WordPress 4.5.2. The only outside plugin is WooCommerce with 2.6.0. Running on Media Temple on its own database.

![elementor stuck](https://cloud.githubusercontent.com/assets/2569022/16102899/09dacda0-3342-11e6-9d94-ce528822ed20.gif)

**Comment by KingYes** [comment]
Fixed here: #77

**Comment by wonderment** [comment]
Pulling the Master branch and uploading again fixed it. Thank you!

**Comment by WebDesignKinetix** [comment]
I am having this same problem.  Using Elementor 2.0.9 and Pro2.0.4.  This is on a fresh install of WordPress, 96m of memory, no other plugins loaded.
