### ISSUE TITLE
Enhancement Request - Column Width Setting

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#847]
Column widths can be changed by dragging the edges but it can be very fiddley to get the value correct. It would be great to have the column width as a parameter in the column configuration under Advanced settings.

**Comment by SniffleValve** [comment]
A big +1 to what Nick Green said! :) A place where one can enter the numerical value for the width as a percentage (no sense allowing px as that would mess up mobile :) )

Cheers!
Lyle

**Comment by sigersmit** [comment]
It would also be nice if once dragged a column into a section one would be able to change the amount of columns. If I now choose one column, but later want to have three, I see no option to increase (or decrease) the amount of columns. So now I delete the row, and drag in a new column layout.. But thats not always easy.

**Comment by arielk** [comment]
Elementor 1.5 RC2 has already been released with this enhancement, please check this issue #1827
