### ISSUE TITLE
image carousel widget [enhancement request]

### ISSUE THREAD

**Issue by LDX1** [pojome/elementor#849]
in image carousel widget, in its Content tab if I choose to link to “custom URL” I can only add one single link that will be the same for every image. It could be very useful to point differnt image to different URL links. Also, could be usefull too to have the option to show or hide the image caption (taken from media library) on the carousel.

Thank you.

**Comment by arielk** [comment]
Thanks for your feedback! 
I merged this issue with another issue #216 in the same subject so that our Dev staff could deal with it more efficiently. So please let's continue the conversation there.
