### ISSUE TITLE
Tooltip on option label hover or Click [ Suggetion ]

### ISSUE THREAD

**Issue by sandeshjangam** [pojome/elementor#850]
## Description
Tooltip on option hover will be great for end user. When user will hover on option label show tooltip bottom of panel or above label which will describe complicate options and what will the do etc. It would be time saver in designing.

It can be achieve simply passing tooltip text in control array. Control will add html in appropriate control and global js or css to show that tooltip on hover or click.

Please check below image.

[https://postimg.org/image/udl0rq8ul/](https://postimg.org/image/udl0rq8ul/)

**Comment by bainternet** [comment]
@sandeshjangam 

This is already implemented in a few control types by simply passing a title parameter to the control array.

thanks for the suggestion.
