### ISSUE TITLE
Use a custom font in texts

### ISSUE THREAD

**Issue by mrprunen** [pojome/elementor#852]
## Description
Elementor is really great. 
However sometimes you may need to utilize some of custom fonts (that not part in the google font family) for text elements.

temporary i've  found workaround using child theme with font-face and inject code into text content; 
es <p style="font-family: 'klinic_slabbook';">

Works for me, but 
It would be nice to find a solution to load webfonts in "fonts folder" of the theme and make sure that in addition to system fonts and google fonts,  "uploaded fonts" are selectable.

what do you think?
<img src="http://dev.eticru.org/tmpdocs/Immagine1.png" alt="Image1" />

<img src="http://dev.eticru.org/tmpdocs/Immagine2.png" alt="Image2" />

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.52
	PHP Version: 5.4.45
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.6.1
	Site URL: http://dev.eticru.org
	Home URL: http://dev.eticru.org
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: it-IT
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child ETICRU
	Version: 0.1
	Author: Marco Bruno
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 1.3.40
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

== Active Plugins ==
	Clef
		Name: Clef
		Version: 2.6.1
		Author: Clef

	Elementor
		Name: Elementor
		Version: 0.10.7
		Author: Elementor.com

	Elementor Templater: ElemenTemplator
		Name: Elementor Templater: ElemenTemplator
		Version: 1.0.7
		Author: WPDevHQ

	GP Premium
		Name: GP Premium
		Version: 1.2.91
		Author: Tom Usborne

	iThemes Security
		Name: iThemes Security
		Version: 5.7.0
		Author: iThemes

	Limit Login Attempts
		Name: Limit Login Attempts
		Version: 1.7.1
		Author: Johan Eenfeldt

	Polylang
		Name: Polylang
		Version: 2.0.7
		Author: Frédéric Demarle

	W3 Total Cache
		Name: W3 Total Cache
		Version: 0.9.5.1
		Author: Frederick Townes

**Comment by arielk** [comment]
Of course. This is a very useful feature and it is one of the cool features included in the upcoming Elementor Pro.

**Comment by drawcard** [comment]
You can also create a class for such fonts in your CSS stylesheet, and use the custom class on any element inside Elementor to apply a certain font.

**Comment by mrprunen** [comment]
Thank you. I had create child theme and wrote class. Work For me.
Elementor  is bellissimo!

Il 30 nov 2016 00:05, "Chris @ Drawcard" <notifications@github.com> ha
scritto:

**Comment by wonderment** [comment]
> Of course. This is a very useful feature and it is one of the cool features included in the upcoming Elementor Pro.

Is using custom fonts still upcoming? We can utilize a child theme, of course, but it'd flow better if that type of integration matched the current Google integration available in the font family list.

**Comment by mrprunen** [comment]
Exactly!! This is the right and intuiteve way. In pro version when? :-)
PS.. Pro unlimited version is much expensive for me and the middle price
with 3 sit is noto enough.
3 license is enough for deve stag and production site but if i want develop
a second site i need a fully version. Expensive. Is possibile have lifetime
full license (sites and update) like wplm?

Good work guy, elementor is growing very well and fast!

Il 04 mar 2017 16:23, "WNDRMNT" <notifications@github.com> ha scritto:

**Comment by drawcard** [comment]
> PS.. Pro unlimited version is much expensive for me and the middle price
with 3 sit is noto enough.
3 license is enough for deve stag and production site but if i want develop
a second site i need a fully version. Expensive. Is possibile have lifetime
full license (sites and update) like wplm?

It depends on how many sites you develop and build, but the Unlimited licence is the best value for money, if for example you are a web designer and you use Elementor on many client sites. The 3 site licence seems to be more appropriate for "once off" users on a single site. 

$199 per year is really not a lot to ask for, if the software saves you thousands of dollars in time and effort costs throughout the year ;) And looking at the major updates that have come out so far, they really are providing a lot of value for money.

**Comment by wonderment** [comment]
Has there been any movement with this?

P.s I agree, $199/annually is a high-value investment.

**Comment by DerekBess** [comment]
any movement on this?

**Comment by NautHnim** [comment]
+1

**Comment by merianos** [comment]
This option works for me like a charm : https://merianos.wordpress.com/2017/09/22/elementor-register-custom-font-family-in-the-fonts-control/ :smile:

**Comment by parkmap** [comment]
@merianos 

Thank you!, it works great. but the code is not adding to global fonts.

**Comment by patryk-uszynski** [comment]
@parkmap @merianos This is happening because of rendering font inputs directly in [includes/editor-templates/panel.php](https://github.com/pojome/elementor/blob/405e9105609d28b6929831b66e8d1b6903a7c91d/includes/editor-templates/panel.php) without using `Control_Font` class. I think there should be hook in [includes/fonts.php](https://github.com/pojome/elementor/blob/405e9105609d28b6929831b66e8d1b6903a7c91d/includes/fonts.php)  for registering own fonts, which would allow to create font management modules.

**Comment by adam-acosta** [comment]
FWIW I added my fonts directly in fonts.php and elementor picked it up.

**Comment by TheBigBanik** [comment]
Hey Adam, can you please provide the code you inserted in fonts.php?

**Comment by TheBigBanik** [comment]
Forget it, I manage to do it in a very simple way. Using the oceanwp template and added my custom fonts inside the template, the only thing left was to disable default fonts in elementor. Very very simple.

**Comment by bainternet** [comment]
Finally, it's here, Elementor pro 1.15.0

**Comment by KyleStank** [comment]
This shouldn't be a "Pro" feature. There are already enough features behind the paywall.

**Comment by drawcard** [comment]
@KyleStank There needs to be enough incentive to encourage monetary support of Elementor, as well as retain current subscribers. That's what keeps the project afloat. Plus Elementor have already released plenty of updates to the free plugin in the past.

If Elementor is making you (or your clients) lots of money it isn't much to ask for a subscription in return, to keep funding great additions that other builder plugins lack.

**Comment by KyleStank** [comment]
@drawcard I agree with you 100%. I have purchased Elementor Pro already. However, I just feel that custom fonts should be included in Free. Maybe that is asking a decent amount, but I don't know. That's just me maybe.
