### ISSUE TITLE
Text editor widget alignment issue on mobile

### ISSUE THREAD

**Issue by LDX1** [pojome/elementor#855]
## Description

If in a Text Editor Widget you try to change the alignment just for mobile it doesn't work.

## Steps to reproduce

I have a text element with right alignment for desktop and centered for mobile.

## Environment

Does not work on android 6.0 with Firefox app, Chrome app or Chromium app.

**Comment by arielk** [comment]
We could not reproduce your problem. Can you please share with us the link to the page with your problem?

**Comment by LDX1** [comment]
http://alberoweb.it/
http://imgur.com/a/yHB4o

thanks.

**Comment by arielk** [comment]
Please go to your dashboard> Elementor > tools > Generate CSS > and let me know if this issue has been resolved

**Comment by LDX1** [comment]
unfortunately it does not change, the problem is still there.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website + FTP access, and our support team will try to assist.
