### ISSUE TITLE
Responsive bug: Tablet in landscape 1024px is not working

### ISSUE THREAD

**Issue by Githubhem** [pojome/elementor#860]
Hello.

Tablet 768px-1024px is not working correctly and behave like desktop.
Elementor code for tablet: @media (max-width: 1023px). But ipad landscape width - 1024px.

Maybe you should replace:
1) @media (max-width: 1023px) to @media (max-width: 1024px). 
2) @media (min-width: 1024px) to  @media (min-width: 1025px) for desktop.

**Comment by arielk** [comment]
Thanks for your feedback! 
Fix: https://github.com/arielk/elementor/commit/3a6a8c749ed2e18ba93cdac4051fed058ce607bd
