### ISSUE TITLE
Importation problem

### ISSUE THREAD

**Issue by nicolas92** [pojome/elementor#861]
Hello,

I have a small problem with the import, I explain.

I created a theme with several demos, I want to create a one click demos install with the plugin "One Click Demo Import: https://github.com/proteusthemes/one-click-demo-import", I created some functions to assign menus, woocommerce pages, home, blog, widgets etc, everything works, I put a notice to say that you must import the json file of elementor via the My Library tab, but when I import, the file does not work, I am obliged to edit a page with Elementor to insert the template, how is this possible?
If I import all the files manually, I only have to upload the json file in the library and it works on all the pages created with Elementor, I do not need to go on a page, edit it with the plugin then insert the template imported.

Can you help me with this problem?

PS: I ask if it is possible but I do not think, is it possible to automatically import the json file of Elementor with the plugin "One Click Demo Import" like the customizer options, the widgets and the xml file from WordPress.

Thank you a lot.

**Comment by nicolas92** [comment]
Hello, I saw this topic on one click demo install: https://github.com/proteusthemes/one-click-demo-import/issues/60
Have you found a solution to automatically import the Elementor json file with this plugin?
It would be really great.
Otherwise, users are forced to import the file manually and in addition there is a problem as mentioned above.

Thank you very much :)

**Comment by nicolas92** [comment]
I created a Custom CSS tab, to import the css with the one click plugin, I use the following code:

```
function import_css() {

	// CSS file
	$css_file = $this->demo_url . '/custom-css.txt';

	// Get data
	$response = wp_remote_get( $css_file );

	// Check for errors
	if ( is_wp_error( $response ) or ( wp_remote_retrieve_response_code( $response ) != 200 ) ) {
		return false;
	}

	// Get remote body val
	$body = wp_remote_retrieve_body( $response );

	// Return data
	if ( ! empty( $body ) ) {
		set_theme_mod( 'custom_css', $body );
	} else {
		return false;
	}

}
add_filter( 'pt-ocdi/after_import', 'import_css' );
```

This is a similar code to import the json file from Elementor?

Thank you very much :)

**Comment by KingYes** [comment]
I don't understand what you need, but maybe is can help you: https://github.com/pojome/elementor/issues/881

**Comment by nicolas92** [comment]
Hello, this is exactly the same thing I would like to do but the given solutions do not work.
I would import the json file from elementor via a function.

If I do something like that, would it work?

```
function import_json() {

    // file
    $file = $this->demo_url . '/elementor.json';

    // Get data
    $response = wp_remote_get( $file );

    // Check for errors
    if ( is_wp_error( $response ) or ( wp_remote_retrieve_response_code( $response ) != 200 ) ) {
        return false;
    }

    // Get remote body val
    $body = wp_remote_retrieve_body( $response );

    // Return data
    if ( ! empty( $body ) ) {
        \Elementor\plugin::instance()->templates_manager->get_source( 'local', $body );
    } else {
        return false;
    }

}
```

Thank you a lot.

**Comment by KingYes** [comment]
Try change to this:

```
if ( ! empty( $body ) ) {
	$local = \Elementor\plugin::instance()->templates_manager->save_template( [
		'source' => 'local',
		'type' => 'page',
		'data' => $body,
	] );
} else {
	return false;
}
```
