### ISSUE TITLE
bug: columns widget causes search failure

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#862]
## Description

After running some test searches on our site, I realized certain sections were not being indexed or found. After much trial and error and digging around, we have determined that the problem is the columns widget. If I place a columns widget within another section, any content inside the columns widget is invisible to search. (Note that this problem exists with plain WP search, but also with the search plugin Relevanssi.)

## Steps to reproduce

You can see for yourself by [searching](http://staging.ucsflibrary.flywheelsites.com/site-search-testing/
) for the term **widget** on our site. It only exists on [this page](http://staging.ucsflibrary.flywheelsites.com/test-bed-page-elementor/), and because it is inside the columns widget, search does not see it. The below images also help explain. 

### Content as seen in the Elementor editor
<img width="822" alt="elementor-editor" src="https://cloud.githubusercontent.com/assets/974442/20336218/3b2a6204-ab7d-11e6-8537-3732eaf3ba37.png">

### Content as seen in the WordPress editor
Note that the content inside the columns widget is mysteriously missing!

<img width="750" alt="wp-editor 2" src="https://cloud.githubusercontent.com/assets/974442/20336281/cf57018a-ab7d-11e6-8d7a-99a4bef2c3aa.png">

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: 5.5.49
	PHP Version: 5.6.25-1+deb.sury.org~precise+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.6.1
	Site URL: http://staging.ucsflibrary.flywheelsites.com
	Home URL: http://staging.ucsflibrary.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Permalink Structure: /news/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Dynamik-Gen
	Version: 1.9.7
	Author: The Cobalt Apps Team
	Child Theme: Yes
	Parent Theme Name: Genesis
	Parent Theme Version: 2.4.2
	Parent Theme Author: StudioPress

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

== Active Plugins ==
	Breadcrumb NavXT
		Name: Breadcrumb NavXT
		Version: 5.5.2
		Author: John Havlik

	Elementor
		Name: Elementor
		Version: 0.10.7
		Author: Elementor.com

	Genesis Dambuster
		Name: Genesis Dambuster
		Version: 1.5.5
		Author: Russell Jamieson

	Insert Pages
		Name: Insert Pages
		Version: 3.1.8
		Author: Paul Ryan

	Relevanssi
		Name: Relevanssi
		Version: 3.5.6.1
		Author: Mikko Saari

	SAML 2.0 Single Sign-On
		Name: SAML 2.0 Single Sign-On
		Version: 0.9.4
		Author: Keith Bartholomew

	Sticky Menu (or Anything!) on Scroll
		Name: Sticky Menu (or Anything!) on Scroll
		Version: 2.0.1
		Author: Mark Senff

	User Role Editor
		Name: User Role Editor
		Version: 4.29
		Author: Vladimir Garagulya

	WordPress Importer
		Name: WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WPForms
		Name: WPForms
		Version: 1.3.0.1
		Author: WPForms

	WPForms Conditional Logic
		Name: WPForms Conditional Logic
		Version: 1.1.5
		Author: WPForms

**Comment by TQO23** [comment]
Could I ask for an update on this please. Facebook Elementor Group post refers https://www.facebook.com/groups/Elementors/permalink/989326511193135/?comment_id=992184347574018&comment_tracking=%7B%22tn%22%3A%22R4%22%7D

thanks

**Comment by arielk** [comment]
V1.0.0 has been released!
