### ISSUE TITLE
Elementor conflict with Jetpack

### ISSUE THREAD

**Issue by iameviliam** [pojome/elementor#864]
Some Jetpack functions caused conflicts in Elementor loading, it loads forever. Without Jetpack everything works fine.
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 5.5.38
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.6.1
	Site URL: http://www.sublimemilbus.com
	Home URL: http://www.sublimemilbus.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 64MB
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Parabola
	Version: 2.1.0
	Author: Cryout Creations
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

== Active Plugins ==
	Akismet
		Name: Akismet
		Version: 3.2
		Author: Automattic

	BuddyPress
		Name: BuddyPress
		Version: 2.7.2
		Author: The BuddyPress Community

	Cryout Serious Theme Settings
		Name: Cryout Serious Theme Settings
		Version: 0.5.7
		Author: Cryout Creations

	Elementor
		Name: Elementor
		Version: 0.10.7
		Author: Elementor.com

	Jetpack by WordPress.com
		Name: Jetpack by WordPress.com
		Version: 4.3.2
		Author: Automattic

	St Daily Tip
		Name: St Daily Tip
		Version: 3.7
		Author: Sanskruti Technologies

	Yoast SEO
		Name: Yoast SEO
		Version: 3.8
		Author: Team Yoast

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Name: ManageWP - Worker Loader
		Version: 
		Author: ManageWP

**Comment by iameviliam** [comment]
Also stucked at the loading screen with the plugin "shotcodes ultimate". And it have some bugs with "TinyMCE Advanced" when editing text fields.

**Comment by iameviliam** [comment]
Also if the title of the page is too short it redirects to the no result page

**Comment by iameviliam** [comment]
Another conflict with Caldera Forms

**Comment by arielk** [comment]
1. 
- Make sure you are using the most updated versions of Elementor, WordPress & your theme.
Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- If you have a caching plugin, make sure you deactivate it, or even better – purge the cache.
- Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

2. Shortcode Ultimate: Try to create a shortcode in a regular editing mode, take the shortcode and insert it inside the text editor, and see if it works.

3. What the problem with short title? 

4. Where exactly have a problem with Caldera?

**Comment by pmmueller** [comment]
About »2. Shortcodes Ultimate« 
Shortcodes Ultimate displays a button above the TinyMCE, right next to "Add media", to insert shortcodes. This button is displayed in Elementor's Text-Editor, but is not functional (nothings happens on clicking it). 

As a non-functional button is rather confusing I would suggest to remove the button from Elementor's widget (if that's possible). Shortcodes should ideally be inserted in Elementor's shortcode widget anyway if I understood it right. 

If it's impossible to remove the button from Elementor's text-editor the button should be working as expected ;-)

**Comment by arielk** [comment]
I merged this issue with another issue #1033 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your report!
