### ISSUE TITLE
Need Background overlay for Columns

### ISSUE THREAD

**Issue by WebTechStreet** [pojome/elementor#865]
Hi 

Just like sections, can Columns also have "**Background Overlay**"

It tried it and it is not much typical to be implement and will allow more flexibility in designing layouts. 

In fact i made a pull request of the changes i have made here [https://github.com/pojome/elementor/pull/810](https://github.com/pojome/elementor/pull/810)

But somehow it failed. If was my first time contributing to other's repository.  
Not sure if it was the proper way, but do consider the request.

**Comment by arielk** [comment]
Closed https://github.com/pojome/elementor/pull/1153
