### ISSUE TITLE
Enqueue Scripts for Module [ Suggetion ]

### ISSUE THREAD

**Issue by sandeshjangam** [pojome/elementor#869]
## Description
https://postimg.org/image/5mcln0305/
You can see in screenshot. It would be good if you provide function to enqueue extra required css and js files.

example
```
public function add_scripts(){
 /* Here we will add our required module script and style ( External libraries ) using WordPress functions. 
You just need to call this function of all live instance of modules on page in your appropriate way*/
}
```
If you want any extra clarification please let me know.

**Comment by joshmarom** [comment]
Thank you for your inquiry.
This function will be included in our developers API, which is almost ready.
Stay tuned!

**Comment by teolaz1990** [comment]
Up!

**Comment by joshmarom** [comment]
Please refer to: https://github.com/pojome/elementor/blob/develop/docs/content/hooks/php-hooks.md#frontend-actions

**Comment by zimbert** [comment]
Hello 
Please is there a way to add javascript to a Section of a page in Elementor yet ?
I would love to be able to display my ebay listings or spreadshirt shop or add a coinhive miner 
on the section of the page that i need the items displayed.
So far i have found it impossible to display my ebay shop or Spreadshirt shop with Elementor 
Please is there a way to do this with Elementor free version ?
Thank you

**Comment by Spartanace1024** [comment]
Would also love to know if this is possible.
