### ISSUE TITLE
0.11 update "breaks" sections and columns

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#872]
With previous versions, one was able to add multiple “rows” of columns (using the Columns widget) to a “base” section and then style these “rows” (sections) independently.

Have a look at this video to see what I mean:

https://www.youtube.com/watch?v=ZGCwhAPRyeQ

With 0.11, this is no longer possible as all the “rows” now inherit their styling from the “base” section. Perhaps this was intentional?

The way it was before was a major functionality that “another popular” builder was not able to produce 🙂

Cheers!
Lyle

**Comment by arielk** [comment]
Fix: https://github.com/pojome/elementor/commit/9eb04ed3b40b043d2a12b813754b5253847e3c8e
Version 0.11.1 has been released, please update!

**Comment by SniffleValve** [comment]
Perfect :) Elementor is the BEST! :)
