### ISSUE TITLE
Import json file via another way

### ISSUE THREAD

**Issue by oceanwp** [pojome/elementor#881]
Hello,

I have a question, is it possible to import the json file from elementor via another way than your import system?
I created a theme with several demos, and I created a plugin to import its demos with one click.

To import the content, I integrated the WordPress Import plugin.
For the customizer options, I took functions of the Customizer Export/Import plugin.
For the widgets, I took functions of the plugin Widget Importer & Exporter.
Automatically after the import, front and blog pages are assigned, as well as menus and WooCommerce pages if the imported demo uses WooCommerce.

Everything works perfectly apart from Elementor, at the moment I have to import it via your system.

I looked at your file "local.php" to decode and import the json file but it refers to other functions.
Is it possible via a simple way to import the json file?

PS: Thanks for creating such a plugin, it is great :)

Thank you a lot :)

**Comment by KingYes** [comment]
This is what you need to do:
https://github.com/pojome/elementor/blob/develop/includes/template-library/sources/local.php#L243

You can get the instance of `local` source by using `\Elementor\plugin::instance()->templates_manager->get_source( 'local' );`

Tell me if I can help you..

**Comment by oceanwp** [comment]
Hello, thank you very much for your answer, but how do I include my file elementor.json?
For example to import widgets, I do like this:

if ( $widgets_file ) {
	$widgets_importer = new ODI_Widget_Importer();
	$widgets_importer->process_import_file( $widgets_file );
}

"$widgets_file" is the url to the json file.

For elementor, I replace 'local' by the url to the json file of elementor?

Thank you very much.

**Comment by KingYes** [comment]
You need to get the content of the file and decode to array (json to array). You can see how we did this by this line: https://github.com/pojome/elementor/blob/develop/includes/template-library/sources/local.php#L237

**Comment by oceanwp** [comment]
Oh okay.
I created a class to decode and get the contents of the file but it does not work.

Here is my class:

```
class ODI_Elementor_Importer {

	/**
	 * Import file
	 *
	 * @since 1.0.0
	 */
	public function import_elementor_file( $file ) {

		// Get file contents.
		$data = ODI_Helpers::get_remote( $file );

		// Return from this function if there was an error.
		if ( is_wp_error( $data ) ) {
			return $data;
		}

		// Decode file contents.
	    $data = json_decode( file_get_contents( $data ), true );

		// Import the data
    	return $this->import_data( $data );

	}

	/**
	 * Import JSON data
	 *
	 * @global array $wp_registered_sidebars
	 * @param object $data JSON widget data.
	 * @return array $results
	 */
	private function import_data( $data ) {

		\Elementor\plugin::instance()->templates_manager->get_source( $data, 'local' );

	}

}
```

And to put my json file into the import, here's what I put:

```
// Import elementor
if ( class_exists( 'Elementor\Widget_Base' ) && $elementor_file ) {
	$elementor_importer = new ODI_Elementor_Importer();
	$elementor_importer->import_elementor_file( $elementor_file );
}
```

Can you tell me what's wrong?

Thank you so much for your help.

**Comment by dtbaker** [comment]
Hey @oceanwp I built this setup wizard here: https://github.com/dtbaker/envato-wp-theme-setup-wizard

I'm currently tweaking it to work with Elementor. Everything works except the new separate css files. I have to re-generate those or something.

Anyway check out that importer and ping me if you have any feedback/ideas.

**Comment by oceanwp** [comment]
Hello @dtbaker, thank you very much for your plugin, it looks to be great, unfortunately I tried to some functions to my plugin but it still does not work.
I think it's very simple, I know how to get the contents of the json file but I do not know how to import this content.

**Comment by oceanwp** [comment]
Hello, I upgraded Elementor to 0.11.2, now when I import the xml file, the Elementor pages are also imported, you solved the problem?
Thank you very much :)
