### ISSUE TITLE
Elementor doesn't load after editing

### ISSUE THREAD

**Issue by iameviliam** [pojome/elementor#882]
I was able to use elmentor on a page until I added an animation. After I added the animation I saved, I visited the page and it worked, when I wanted to edit it back it doesn't worked, the screen keeps loading forever

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
