### ISSUE TITLE
Editor: Hide Elementor Library CPT from “Link to existing content” Popup

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#883]
when adding a link within text blocks, the native wp popup appears thats used to offer existing pages etc. when cklicking on the cog. thats fine, but all the custom elementor templates appear in this list.
dont know if thats the way its supposed to be, but when having lots of templates its quite irritating, and i wonder whats the use of this?
would be much better they dont appear there :-).

**Comment by arielk** [comment]
If I understood you correctly, you want to hide Elementor Library CPT from “Link to existing content” popup?

**Comment by dasigna** [comment]
thats right. (too much words for simple request - sorry :-) )

**Comment by arielk** [comment]
Thanks for your feedback!
I merged this issue with another issue #417 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.
