### ISSUE TITLE
Tabs and Progress Bar Widgets aren't responsive

### ISSUE THREAD

**Issue by iameviliam** [pojome/elementor#884]
Please make the "Tabs" widget responsive, actually it looks very bad on mobile if you have more than 2 options. Same with progress bar

**Comment by SniffleValve** [comment]
@iameviliam -  could be your theme that is causing this for you. On numerous site with the GeneratePress theme, both the Tabs and Progress Bars respond nicely.  Which theme are you using?

**Comment by mizejewski** [comment]
Yes responsive tabs and accordions work fine for me too using Genesis and Dynamik theme.

**Comment by iameviliam** [comment]
I use parabola, thanks for the tip!
