### ISSUE TITLE
deactivate native templates view?

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#885]
there should be a way to deactivate (the view of) the elementor served templates for editors etc. or even globally for everyone.
more than once already had the issue, that editors 'play' around with those templates and messing things up where they shouldnt (even havent understood the use and pupose of those templates...)!

so it would be a really great thing if admins could deactivate the view and use of those templates provided by elementor - and only these, because saving custom templates for editors to use is the helpful thing that has to stay.

**Comment by mizejewski** [comment]
Yes better control over permissions would be a big help. It doesn't need to be quite so granular, but https://www.elegantthemes.com/gallery/divi/documentation/role-editor/ is a great example.

**Comment by arielk** [comment]
We call it "Advanced Role manager". This feature is probably going to be a part of the upcoming Elementor PRO.
