### ISSUE TITLE
Add tags & categories for Elementor Library

### ISSUE THREAD

**Issue by WPDevHQ** [pojome/elementor#886]
Not sure if you guys have this covered in the API or not so I'm going to make an official request.

I would like to leverage the power of WP_Query() with custom $args to generate grouped content created with Elementor.

At the moment we have the option to query elementor_library but that's limited to just the post type and everything is save in one place.

In my little thinking brain I have 2 aproaches to resolving this shortfall as follow.

1) Add a tagging method i.e tags or categories so that we can group save sections under My Library ....or
2) Allow us to create Custom Elementor Post Types where we can save our sections effectively creating multiple groups of content.

A use case for such grouped content is creating a content slider - there more use cases but I'll keep mums for now. Just think global ;)

**Comment by arielk** [comment]
I think that in the future we will add this feature. Thank you for the idea and feedback!

**Comment by soniapello** [comment]
@WPDevHQ 
You mean something like this ?
<img width="576" alt="tes" src="https://cloud.githubusercontent.com/assets/20027271/21943863/7ca79e48-d9d3-11e6-82d2-2b76abdcf49a.png">
<img width="576" alt="meta" src="https://cloud.githubusercontent.com/assets/20027271/21943878/89f4cd82-d9d3-11e6-983a-8bd92998f85a.png">

**Comment by WPDevHQ** [comment]
More of a taxonomy approach than meta data. 

Would like to be able to categorise a CPT that is inline/works with Elementor i.e. I can query and return the results say within a slider or a listing. At the moment we have the Library(My Library) CPT but this can't be segmented via either or both by categories or tags.

I know I can add a CPT as a submenu to the Elementor admin menu but I need Elementor to be able to read that CPT as it does for the Library without having to hack it. Better still would be to use the Library with taxonomies and be able to segment pages(templates) from sections(globals) for better query handling.

For most use cases we are going to want/need to return just the global sections and not the page templates.

Hope that sheds some more info on the subject :)

**Comment by OliverGilpin** [comment]
Hello is there any update on this as it is exactly what I am looking for! 

I have a client that really wants thins functionality and I am running out of options! 

Thanks
