### ISSUE TITLE
Elementor stucks on loading page

### ISSUE THREAD

**Issue by harrispapadopoulos** [pojome/elementor#897]
## Description

Hello,
Just installed Elementor. I tried to edit an existing page and it gets "stuck" to Elementor loading page.
I had a look in the issues page and I saw that you suggested to someone that had a similar problem to download the dev edition of Elementor.
I did so, but the problem presists.

## Steps to reproduce

It happens to me when I try to build a new page or article or edit an existing one
(every time Elementor needs to be started)

## Environment

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.34
	PHP Version: 5.6.16
	PHP Max Input Vars: 50000
	PHP Max Post Size: 256M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.4.5
	Site URL: http://omt100.com/wordpress
	Home URL: http://omt100.com/wordpress
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: el
	Timezone: Europe/Athens
	Admin Email: admin@omt100.com
	Debug Mode: Inactive

== Theme ==
	Name: Time Child
	Version: 1.0
	Author: Kuba Sto
	Child Theme: Yes
	Parent Theme Name: Time
	Parent Theme Version: 4.3
	Parent Theme Author: Kuba Sto

== User ==
	Role: administrator
	WP Profile lang: el
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

== Active Plugins ==
	Duplicate Post
		Name: Duplicate Post
		Version: 3.0.3
		Author: Enrico Battocchi

	Elementor
		Name: Elementor
		Version: 0.11.0
		Author: Elementor.com

	LayerSlider WP - Time Theme edition
		Name: LayerSlider WP - Time Theme edition
		Version: 4.6.5
		Author: Kreatura Media

	Lost Trail
		Name: Lost Trail
		Version: 
		Author: 

	Olympus Mythical Trail
		Name: Olympus Mythical Trail
		Version: 
		Author: 

	Olympus Mythical Trail (2015 Archive)
		Name: Olympus Mythical Trail (2015 Archive)
		Version: 
		Author: 

	Polylang
		Name: Polylang
		Version: 2.0.9
		Author: Frédéric Demarle

	WiLD Googlemap
		Name: WiLD Googlemap
		Version: 1.9.3
		Author: Studio WiLD

**The two olymus mythical trail plugins and the Lost Trail Plugin are custom plugins of ours, but they are not involved in page or articles and their editing.
I also tried to deactivate them, but the problem presisted.**

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.
