### ISSUE TITLE
Elementor post meta not correctly imported with the new WP Importer

### ISSUE THREAD

**Issue by colmtroy** [pojome/elementor#898]
Hi folks,

Thought you'd want an early heads up on this issue as it may be an Elementor bug.
Any pages with Elementor post meta don't seem to be imported correctly using the new WP Importer.

See full issue details described here
https://wordpress.org/support/topic/elementor-metadata-not-being-applied-to-content/

I've also reported the issue to the WP Importer team here
https://github.com/humanmade/WordPress-Importer/issues/93

**Comment by matipojo** [comment]
Hi, Thank you for the attention,
It's because the new importer doesn't use the original filter `wp_import_post_meta`.
See here for more details: 
https://github.com/humanmade/WordPress-Importer/issues/93#issuecomment-261998550

Thanks.
Mati

**Comment by colmtroy** [comment]
hey @arielk - was this issue fixed?

**Comment by arielk** [comment]
Sorry, my mistake.

**Comment by colmtroy** [comment]
No worries :)

Is there any indication as to when this issue might be resolved?

Colm
