### ISSUE TITLE
Elementor editor works only on draft mode

### ISSUE THREAD

**Issue by mariano** [pojome/elementor#908]
We are seeing the same issue described in #651. We are using TwentySixteen theme, and have no other plugin running but Elementor.

If a page / post is in draft mode, the editor shows up. If published, it does not load.

The only remarkable thing in our configuration is that the web server user only has write permissions to Wordpress' upload folder. We've tried setting all wp-content/ folders to 777, but issue persists.

Ways to reproduce:

1. Create new Page
2. Click Edit with Elementor -> Editor works. URL loaded is /?page_id=12&elementor
3. Publish page
4. Click Edit with Elementor -> Editor does not load. URL loaded is /test-page-m1/?elementor
5. Send page back to Draft.
6. Click Edit with Elementor -> Editor works. URL loaded is /?page_id=12&elementor

My feeling is that it has to do with the fact that 4 uses the permalink instead of the root URL.

Further information:

* Wordpress version: 4.6.1
* Web Server: NGINx

**Comment by mariano** [comment]
Upon further investigation, this is indeed a Permalinks issue. When setting wordpress to use "Plain" permalinks, editor loads regardless of publish status. If set to use any SEO friendly URL, editor only loads on draft mode (when permalink is not being used.)

This is the relevant NGINx configuration for this site (settings recommended by Wordpress itself):

```
root /apps/sites;
index index.php;

location = /robots.txt  { access_log off; log_not_found off; expires max; }
location = /favicon.ico { access_log off; log_not_found off; expires max; }
location ~ /\.          { access_log off; log_not_found off; deny all; }
location ~ ~$           { access_log off; log_not_found off; deny all; }

location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_next_upstream error;
    try_files $uri $uri/ /index.php$args;
}

location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
    #expires max;
    log_not_found off;
}

location ~ \.php(/|$) {
    fastcgi_pass sites;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    fastcgi_buffer_size 128k;
    fastcgi_buffers 256 16k;
    fastcgi_busy_buffers_size 256k;
    fastcgi_temp_file_write_size 256k;
    fastcgi_connect_timeout 3s;
    fastcgi_send_timeout 60s;
    fastcgi_read_timeout 60s;
    fastcgi_intercept_errors on;
    reset_timedout_connection on;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}

gzip on;
gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
gzip_proxied any;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_comp_level 9;
```

**Comment by mariano** [comment]
Found the issue, sorry about the noise. It was a typo in the NGINx configuration for `location /`. Where it said `try_files $uri $uri/ /index.php$args;` it should've said `try_files $uri $uri/ /index.php$args;` (notice the added `?`)

**Comment by jhit** [comment]
Had a similar problem. Got always the warning about the_content() missing (see https://docs.elementor.com/article/56-content-area-not-found) but only on the start page elementor loaded. So I was sure this was not the_content() related. I'm glad I found this issue. My nginx config was missing the ?$args part entirely. Wordpress is fine with this because it can read the values from the REQUEST_URI. Anyhow adding the ?$args seems to be the best practice as it is also described in the [NGiNX Wordpress Recipe](https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/)
Many Thanks @mariano

**Comment by szabozoltan69** [comment]
Similar for me. Many thanks!

**Comment by Siccrium** [comment]
Wow, same here, you're a LIFESAVER. THANK YOU
