### ISSUE TITLE
Progress Bar "glitch" on page load/refresh

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#909]
As the title mentions, when the page is loaded or refreshed, what appears to be the progress bar label(s) extends vertically momentarily. I have created a short screencast to illustrate the issue:

http://www.screencast.com/t/vNx6NFHy

As I mention in the video, not a show stopper, but would be nice to clean up :)

Cheers!
Lyle

**Comment by arielk** [comment]
It's not a bug is a feature :(
I try to figure out why you call it "glitch", this is regular behavior of progress bar.

**Comment by SniffleValve** [comment]
![image](https://cloud.githubusercontent.com/assets/23441664/20578684/b55c736a-b185-11e6-85c8-102cbb0e0651.png)

This can't possible be "regular behavior" :)

**Comment by arielk** [comment]
Oh, good catch! It's a really my glitch :(
