### ISSUE TITLE
Group Selection: Select elements together

### ISSUE THREAD

**Issue by iameviliam** [pojome/elementor#912]
To delete or to hide from pc/tablet/mobile sections and columns, I need to do that one by one, it will be cool to save the time doing that by selecting more than one element! Thank you

**Comment by arielk** [comment]
It may be possible to call this feature "Group Selection".

Interesting idea, We'll consider it in the future. Thanks for your feedback!

**Comment by bainternet** [comment]
I merged this issue with  #879 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
