### ISSUE TITLE
PSR-4 autoloader on used classes recommended

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#913]
As the plugin extensions are based on extending your already done classes, please provide a better ordered way to do it by using a compatible PSR-4 autoloader and with corrected namespaces. 

Now all classes you've done has the only namespace "Elementor", without dividing the domain on sub ones, as "Widgets", "Schemes" etc...

All the includes for now are forced in includes/plugin.php file.

References here http://www.php-fig.org/psr/psr-4/

**Comment by KingYes** [comment]
We start working with autoloader in `1.6.0`..

Thanks for your feedback!
