### ISSUE TITLE
[REQ] Apply filters on init_categories() on elements.php to add new categories

### ISSUE THREAD

**Issue by teolaz1990** [pojome/elementor#918]
This is quite simple, i tried to register my custom widgets under a new category i created ("Custom Widgets") overriding get_categories method on each widget and adding an action with

```
// Add a custom category for custom widgets
	add_action( 'elementor/elements/elements_registered', function () {
		
		$elementsManager = Plugin::instance()->elements_manager;
		
		$elementsManager->add_category(
			'custom-widgets',
			array(
				'title' => 'Custom Widgets',
				'icon'  => 'fonts',
			)
		);
	} );
```

I can see widgets (only after researching them by name) but i cannot see the new category, i think because i'm going into the plugin instance too late (var_dumping plugin instance on editors.php seems to not have my added category).

Could you add a simple filter please?

**Comment by teolaz1990** [comment]
PR on #920

**Comment by matipojo** [comment]
Hi, @teolaz1990 
You can use the `elementor/init` hook, It will do the same.

`add_action( 'elementor/init', function () {

		$elementsManager = Plugin::instance()->elements_manager;

		$elementsManager->add_category(
			'custom-widgets',
			array(
				'title' => 'Custom Widgets',
				'icon'  => 'fonts',
			)
		);
	} );

**Comment by burshiki** [comment]
@teolaz hello sir. sorry to bring this up i know this was last year but i'd like to know where did you put the function? i want to create custom category in my elementor with my widgets. thanks

**Comment by teolaz** [comment]
@burshiki as matipojo wrote, you can add the action below in your functions.php file to add a custom category:

```php
add_action( 'elementor/init', function () {
	$elementsManager = Plugin::instance()->elements_manager;
	$elementsManager->add_category(
		'your-custom-widgets-category',
		array(
			'title' => 'Your Custom Widgets Category',
			'icon'  => 'fonts',
		)
	);
} );
```

**Comment by burshiki** [comment]
@teolaz this is the result upon adding the method in functions.php
--------------- 
Fatal error: Uncaught Error: Class 'Plugin' not found in E:\xampp\htdocs\wordpress\wp-content\themes\omano\functions.php:58 Stack trace: #0 E:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(298): {closure}('') #1 E:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #2 E:\xampp\htdocs\wordpress\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #3 E:\xampp\htdocs\wordpress\wp-content\plugins\elementor\includes\plugin.php(192): do_action('elementor/init') #4 E:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(298): Elementor\Plugin->init('') #5 E:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #6 E:\xampp\htdocs\wordpress\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #7 E:\xampp\htdocs\wordpress\wp-settings.php(448): do_action('init') #8 E:\xampp\htdocs\wordpress\wp-config.php(89): require_once('E:\\xampp\\htdocs...') #9 E:\xampp\htdocs\wordpress\wp-load.php(37): require_once('E:\\xampp\\htdocs...') #10 E:\xampp in E:\xampp\htdocs\wordpress\wp-content\themes\omano\functions.php on line 58

**Comment by norewp** [comment]
The correct function would be as follow if you are not using the Elementor Namespace.

```
add_action( 'elementor/init', function () {
	$elementsManager = Elementor\Plugin::instance()->elements_manager;
	$elementsManager->add_category(
		'your-custom-widgets-category',
		array(
			'title' => 'Your Custom Widgets Category',
			'icon'  => 'fonts',
		)
	);
} );
```

**Comment by burshiki** [comment]
@norewp do ihave to be a premium user for me to run this? actually nothing happened when i inserted the method on functions.php. did i miss something?

**Comment by norewp** [comment]
In order to see the effect your widgets/modules need to be attached to the specified category name.

Is your code on GitHub or are the widgets from 3rd party plugins?

**Comment by burshiki** [comment]
its 3rd party plugins sir. so how going to attached it sir?

**Comment by mariovalney** [comment]
You can use `elementor/elements/categories_registered` to put your categories before "WordPress":

```
add_action( 'elementor/elements/categories_registered', function ( $elements_manager ) {
	$elements_manager->add_category(
		'your-custom-widgets-category',
		array(
			'title' => 'Your Custom Widgets Category',
			'icon'  => 'fonts',
		)
	);
} );
```

**Comment by Rowayda-Khayri** [comment]
> In order to see the effect your widgets/modules need to be attached to the specified category name

How to do so?? @norewp

**Comment by mariovalney** [comment]
@Rowayda-Khayri check this link: https://developers.elementor.com/creating-a-new-widget

In `get_categories()` you should add your new category to the returned array.

**Comment by Rowayda-Khayri** [comment]
@mariovalney I want to add existing widgets to my new category not to register a new widget
