### ISSUE TITLE
adding shortcodes into the tab doesnt work

### ISSUE THREAD

**Issue by Jasonb11** [pojome/elementor#92]
I tried adding shortcodes into the tab feature and it's not working.

**Comment by arielk** [comment]
Right now Elementor supports shortcodes in the Text Editor widget, but we working on this issue.

**Comment by arielk** [comment]
Merge #176

**Comment by thisiskiosk** [comment]
Any updates on this subject?

I am trying to load a WP Draw Attention shortcodes into tabs and it only loads the first one.
