### ISSUE TITLE
Feature Request - Global Elements

### ISSUE THREAD

**Issue by DannyOutlaw** [pojome/elementor#922]
Want a way to make elements/templates global.  As in, I can edit an element in a template and the changes cascade to anywhere I used that template.

Use case....

Say I use elementor for blog post and sidebar.  I create a elementor template for the content and sidebar.  This works fine until I want to change something in the sidebar.

I would have to manually go back to every blog post and update the sidebar.

**Comment by WPDevHQ** [comment]
The current work around is to use the AnyWhere Elementor addon: https://wordpress.org/plugins/anywhere-elementor/

You can follow some of the conversation on the plugin here: https://www.facebook.com/groups/Elementors/

**Comment by arielk** [comment]
This is a very useful feature and it is one of the cool features included in the upcoming Elementor Pro. You welcome to follow our updates in elementor.com
