### ISSUE TITLE
Feature Request - Save columns as templates

### ISSUE THREAD

**Issue by DannyOutlaw** [pojome/elementor#923]
Right now I can only save a section as a template.  Would be nice if I could save a column of elements as well.

**Comment by arielk** [comment]
You can save your column by the section. Columns cannot be saved separately, columns is part of the Section.

**Comment by aarondewindt** [comment]
The issue with this approach is that if you'd like to use the templated columns next to each other and they contain different amount of contents, then they'll have different heights. Ideally if I use the templated columns in the same section, then they should all stretch to the height of the highest one. Like when you're using the columns in a section.
