### ISSUE TITLE
space between full screen sections [issue]

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#925]
scenario:
having a page with several full width sections, each with full screen bg image.
now have to set anchors _before_ every single section to 'jump' from one to another. the anchor has to be set between the single sections in order to jump to the very beginning of every section and have the bg image really full screen. thats results in separate 'dummy'-sections for the anchor beetwen those fullscreen-sections. although theres no real content in those anchor-sections they leave a standard 20px space - you can get rit of that space via custom css - BUT: not completely! theres always a tiny little 1px space left behind that one cant get rid of and where the bg 'blinks' through ... ugly little thing.
any way to get rid of that '1px line'??? why is that thing leaving behind?

**Comment by arielk** [comment]
You can share with us a link to the page?

**Comment by dasigna** [comment]
i'll have a site online the next few days - i'll give you a link then.

**Comment by dasigna** [comment]
here we go: www.vs-mc.de
on startpage there are three sections with full screen bg image - upon scrolling a tiny 1px stripe of native bg shines through ... ???

**Comment by arielk** [comment]
@dasigna Is this issue still relevant or that it worked out already?

**Comment by dasigna** [comment]
@arielk - seems to be still relevant. interestingly not on every occasion but still to be observed ...

**Comment by arielk** [comment]
You just can add ID CSS (Under Advanced Tab) for the section, so you don't need to use with separator section for this.

Released in v1.2.0 https://github.com/pojome/elementor/issues/939
