### ISSUE TITLE
Add image size control for Image Box widget

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#928]
hy,
when using the image box it should be possible to choose the desired size like it is done when placing a single image.

thanks :)

**Comment by m9n** [comment]
Agreed! If the original image is really big, we're currently forced to use massively oversized images in the page.

For a temporary workaround, an editor element can be used, but @matthiaswagnerwy's suggestion is needed in the longer term.

**Comment by m9n** [comment]
In fact, it would also be good to see a max-width control alongside image size.

**Comment by DavidCaum** [comment]
Size control should present for all image used. In all widgets. Even background image.

**Comment by ionlantern** [comment]
I'd love that feature! Make it happen soon ;)

**Comment by grafx77** [comment]
Same here....need this feature.

**Comment by matthiaswagnerwy** [comment]
while it is great to see how you develop elementor and also react to many feature requests, i am still wondering why image size is still not available in all widgets. i just stumbled upon the testimonial widget in a project and feel forced to upload duplicate images to my library in order to optimize loading times... when can we expect to see the selection in other widgets and also for background images?
