### ISSUE TITLE
widget_display_callback support?

### ISSUE THREAD

**Issue by phpbits** [pojome/elementor#930]
Any documentation on how to incorporate widget_display_callback filter on the widget display? Thanks!

**Comment by arielk** [comment]
Your question has been asked before (#291), along with a bunch of other [Developer API](https://github.com/pojome/elementor/labels/developer%20api) related issues.
We are working on the API and hopefully it will be released in a couple of weeks.

**Comment by phpbits** [comment]
@arielk seems like elementor pro has been released. Can you please send the link or the Developer API docs? Thanks!
