### ISSUE TITLE
WP Admin (Back-End) Interface

### ISSUE THREAD

**Issue by mikhey** [pojome/elementor#931]
I have installed and tested Elementor some time ago and have just recently completed development on a client's site using it.  It's a _very nice_ product!  

I wanted to start this request to see if there would be any interest in a wp-admin (back-end) UI to elementor - eg edit the sections w/o leaving wp-admin as well.  It would be nice to be able to build the page in both front-end/back-end views.  I was wondering if this was even on the roadmap?  

I have some other ideas as well, but I want to keep this feature request strictly on a back-end interface.

**Comment by arielk** [comment]
We currently do not plan on having a backend editor. You can read more about this idea in this issue #726
