### ISSUE TITLE
Icon List Control

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#938]
More control is needed of the icons in an icon list:
Ability to choose the background color for the icon only
Ability to set the icon background form - none, rounded corners and circle

**Comment by WPDevHQ** [comment]
I thought you are already able to do all this under the style tab.....you can increase, decrease or even remove the boarder. Change shape from circle to square(none) to rounded corner with border radius.

You can set background as well as Icon color........what's missing?

**Comment by nickdgreen** [comment]
There is so much in Elementor I missed the controls

**Comment by nickdgreen** [comment]
You have all of the control you stated on an individual icon but not on the icons in an icon list as far as I can see.

**Comment by nickdgreen** [comment]
Zulfikar,

I responded on github as far as I can see you have all of those controls on
an individual icon but not on the icons in an icon list.

 

Best Regards

Nick

 


Legal Disclaimer:

Internet communications are not secure and therefore Websites Designed 4U (a
business name of ISD Consultants Ltd.) does not accept legal responsibility
for the contents of this message. This email is confidential and solely for
the use of the intended recipient(s). If you receive this email by mistake,
please advise the sender directly, then immediately destroy this email.
Websites Designed 4U maintains security processes designed to eliminate
viruses, however the Company is not responsible for viruses which may be
contained in the email or any attachment(s).

**Comment by arielk** [comment]
Icon List designed for specific needs of a feature list with an icon, it is not intended to put the icon in the center, so we just try to keep it simple.

Thanks for your feedback!
