### ISSUE TITLE
No folder for translation files

### ISSUE THREAD

**Issue by pedro-mendonca** [pojome/elementor#94]
There is no folder defined for translation files, if one would want to load its own files, it must be on the plugin root folder.

**Comment by KingYes** [comment]
Please read here how to translate the plugin: https://docs.elementor.com/article/42-translate

**Comment by pedro-mendonca** [comment]
Hi,

I' know, I'm also translating there, still, for debug purposes or translation customization one might prefer a local .mo file. A languages folder is just a cleaner organization than having it on root.

**Comment by KingYes** [comment]
I can't approve your PR. If I use that:
1) The GlotPress not work we our plugin.
2) You never touch any core files. Why? in next upgrade you will lost all your changes..

**Comment by pedro-mendonca** [comment]
GlotPress will always work.
As the moment the priority is given to local files, if they exist.
In next WP release, this will be inverted, and GlotPress downloaded files will get priority over local ones. Still I think this might get an option for it.

**Comment by KingYes** [comment]
@ramiy ?

**Comment by ramiy** [comment]
@pedro-mendonca,

if you want local translation, you can override elementor translation files from:
**wp-content/languages/plugins/elementor-LOCAL.po**

WordPress is migrating all the translation files from themes/plugins into [translate.wordpress.org](https://translate.wordpress.org/). elementor is using the latest standards.

The translation files are not gone, they are just located in a different location, in **wp-content/languages**.

**Comment by pedro-mendonca** [comment]
@ramiy **wp-content/languages** is the location for the .mo files downloaded from translate.wordpress.org for quite a while.
That is not a safe place for one to keep his own custom .mo, as it will replaced as soon as there is a new language pack available.
The .mo files are first called from the plugin root, that's ok, I just suggested a folder to keep them away from the root.

**Comment by luizeof** [comment]
@pedro-mendonca I'm translating to pt-br on glotpress and appreciate your support.

**Comment by pedro-mendonca** [comment]
@luizeof I'm not sure I can be helpful for pt_BR, maybe you can check some of my strings here and see if they apply oo help.
You can also check it on GlotPress.

**Comment by KingYes** [comment]
Guys, anyone can to finish translate the plugin in WP repo?

**Comment by pedro-mendonca** [comment]
Hi,
Yesterday I've pushed at least 95%, so now there should be language packs being sent to users all over :)
I've pushed the same I have in my localization branch, if anyone want's to test it, will need the elementor.php with textdomain loading to put it in /languages:
https://github.com/pedro-mendonca/elementor/tree/localization-pt_PT

**Comment by KingYes** [comment]
Nice !
Thank-you very much @pedro-mendonca

**Comment by pedro-mendonca** [comment]
An very straight forward article about i18n on WordPress :)
http://www.carriedils.com/wordpress-i18n/

>Tip: Any included translation files should be off the root in directory called /languages. While you can use a different name for this folder, but /languages is the standard folder.

I know it's all moving to glotpress database and language packs, but even in WP4.6beta its just a priority change. WordPress still searches the path declared for local .mo files, that should not be in the root. And again, it's quite usefull for experienced translators to keep an eye on the code and test it live.
