### ISSUE TITLE
Catchable fatal error: Argument 1 passed to Elementor\Element_Base::_get_items() must be of the type array, null given

### ISSUE THREAD

**Issue by Esperancia** [pojome/elementor#941]
## Description
Catchable fatal error: Argument 1 passed to Elementor\Element_Base::_get_items() must be of the type array, null given, called in elementor/includes/base/element-base.php on line 299  and  defined in elementor/includes/base/element-base.php on line 84

## Environment
					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
	MySQL version: 5.5.42
	PHP Version: 5.6.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.6.1
	Site URL: http://localhost/
	Home URL: http://localhost/
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Africa/Porto-Novo
	Debug Mode: Active

== Theme ==
	Name: Treeson
	Version: 0.1.15
	Author: myThem.es
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

== Active Plugins ==
	Elementor
		Name: Elementor
		Version: 0.11.2
		Author: Elementor.com

**Comment by arielk** [comment]
This error should not happen. If you are working on a local server you can please replace the theme to Twenty Sixteen and see if it happens?

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.
