### ISSUE TITLE
Checkbox_list is not working

### ISSUE THREAD

**Issue by iamntz** [pojome/elementor#943]
There are couple of issues on this control. Here is the code I use:

```
$this->add_control(
	'details_to_show',
	[
		'label' => __('Details To Show', 'elementor'),
		'type' => Controls_Manager::CHECKBOX_LIST,
		'default' => ['title', 'date', 'excerpt'],
		'options' => [
			'title' => __('Title'),
			'date' => __('Date'),
			'excerpt' => __('Excerpt'),
			'thumb' => __('Thumb')
		],
	]
);
```

Here are the issues:

- [ ] Default values are ignored;
- [ ] The values are not saved.
- [ ] Redered box cold use [some spacing](http://img.iamntz.com/jing/2016-11-27__10_43.jpg);

**Comment by joshmarom** [comment]
Unfortunately this control is not supported at the moment.
Maybe the control `select2` with the param `multiple` set to true will be suitable for your needs.
