### ISSUE TITLE
Mobile View Not rendering Correctly

### ISSUE THREAD

**Issue by aryasharma36** [pojome/elementor#945]
Hi Team,

I have been using elementor for almost 6 months now and noticed a problem in a website which I had recently built using elementor. Its a probably a bug which I thought you should know and could help me sort it out.

1. The Elementor mobile view option is showing the mobile view of my website incorrectly and is completely different from the actual mobile view of the website.

2. New sections are automatically added to the page when I check it in mobile view in elementor and it is not there when checked in desktop view

3. On changing the section type (eg: fit to screen, default etc) in the mobile view, the change takes place in desktop as well as tablet views too.

Also, the website is not rendering correctly on mobile browsers like UC browser and Dolphin Browser (Two of the most downloaded browsers on android in India )

You can have a look at the websites home page for reference www.matchsmart.in

Would really appreciate your help on getting this sorted.

**Comment by agusmu** [comment]
This is because those browsers do not fully support CSS3 "flexbox"...

http://caniuse.com/#feat=flexbox

I don't know if Elementor Team has a plan to handle this, but some css hacks is needed to make it look better on those browsers.

**Comment by aryasharma36** [comment]
Hey @agusmu Thanks, I hope the Elementor Team does something about this and other issues. I am majorly into front end designing, so I am not sure that I will be able to implement css hacks. Can you suggest a simple way or step by step instructions?

**Comment by arielk** [comment]
Sorry, but Elementor works on browsers that support Flexbox CSS3 :(
