### ISSUE TITLE
Ability to add NOFOLLOW attribute to hyperlinks

### ISSUE THREAD

**Issue by Talco100** [pojome/elementor#953]
Hi
Right now I totally cannot add nofollow attributes into hyperlinks:
– Not using the ‘ULTIMATE NOFOLLOW’ plugin which add a checkboxes for this into hyperlinks edit dialog boxes (Elementor doesn’t show this plugin checkboxes in the hyperlink edit dialog boxes inside Elementor).
– And not in other Elementor elements, such as headlines – because there is no option of adding a Nofollow to the links…

**The ability should be in text editor hyperlinks inside Elemntor and also on all other elements wElementor offer to add hyperlinks to (headlines, buttons etc...)**

It is very important to many website owners from all kinds, and very important when optimizing websites SEO wise

THANKS!
Tal

**Comment by arielk** [comment]
Hi Tal

Thanks for the feedback! 

I merged this issue with another issue #255 in the same subject so that we could deal with it more efficiently. So please let's continue the conversation there.
