### ISSUE TITLE
[REQ] PHP & JS Code Editor

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#956]
Apologies if this has already been suggested, I did run an extensive search but couldn't find the answer to this.

Currently, [Oxygen](https://oxygenapp.com/) allows full PHP and JS code editing inside their page builder, to allow things like custom Wordpress loops or Jquery statements to be run directly inside a page or template block.

I would love to see some sort of PHP & JS code editor in Elementor as well, and I note that you're already implementing custom CSS for Elementor Pro, so I've left that out of my requests.

I think this would give the page author ultimate control over the customisation of content, and would reduce the need for third party plugins to handle this. I would seriously consider buying an Unlimited Elementor Pro licence if this sort of thing was being implemented (or at least planned for a future release).

**Comment by drawcard** [comment]
I had a thought that perhaps enabling <script> tags to run in the HTML module would allow JS to be run in certain blocks like so:

![image](https://cloud.githubusercontent.com/assets/1435638/20783336/244a6e5e-b7e3-11e6-8e73-460658debbad.png)

**Comment by arielk** [comment]
Sorry, from security reasons, we don't allow this widgets.

BUT -

    You can wrap you code inside you custom shortcode
    You can create custom widget for Element (We don't have official API yet).

**Comment by drawcard** [comment]
No worries, that will do for now :)
