### ISSUE TITLE
Question: Elementor Pro licence

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#957]
Hi,

I have a couple of questions about the upcoming Elementor Pro and its licence:

Q1. I understand that if I run a design agency and want to use Elementor Pro for all our client sites, that I need to purchase a single unlimited Pro licence, and renew that each year on behalf of the client. I also understand it's not a subscription. 

Does that rule include all updates, including security patches / compliance with future WP releases? I would be worried that if I cancelled my licence at some point, that would leave all my client sites insecure or broken as the years go on. (In saying this I think the annual renewal model is totally justified when it comes to new features / other improvements.)

Q2. If I build a theme and sell it on ThemeForest, can I use the unlimited Pro licence to bundle in a version of Pro for each theme sold, or is this only allowed for the free version of Elementor? I would love to use Elementor Pro in place of [insert popular pro page builder here] but I am a bit confused as to what the ultimate licence option grants me / doesn't grant me.

Q3. If the answer to my second question is "no", would you consider an option like this for retail theme developers?

**Comment by drawcard** [comment]
Having thought about Q1 a bit more, am I correct in assuming that those critical updates would still be pushed through the free version of Elementor, which is the underlying base for the Pro version - in effect all installations would still be patched regardless of their licence status?

**Comment by arielk** [comment]
Hi @drawcard 
Thank you for sending your questions. We will be happy to answer them.

The GitHub Issue system is more directed at bugs and features queries. For questions about licenses the support email is a better suit.

Please send your questions to support@elementor.com, and our team will be happy to assist with answers.

**Comment by drawcard** [comment]
Hi Ariel, thanks for letting me know - sorry for clogging up the issue tracker :)

**Comment by arielk** [comment]
No problem 👍
