### ISSUE TITLE
Global Font settings are not working

### ISSUE THREAD

**Issue by riyaku** [pojome/elementor#96]
Updating Primary, Secondary Headline, Body text, Accent text settings make no effect

**Comment by arielk** [comment]
We released yesterday a new version with some fixes, please update and check it again. tnx

**Comment by riyaku** [comment]
It works now, but why the body text font is applied to .elementor-widget-image .widget-image-text and not the body tag? Headline font also is not applied site wide. Is there a way to modify this so the entire site is consistent?

**Comment by arielk** [comment]
#79
