### ISSUE TITLE
Idea: use a template system and filter content

### ISSUE THREAD

**Issue by iamntz** [pojome/elementor#966]
Alright, so, I'm using [Handlebars](https://github.com/XaminProject/handlebars.php)¹ for couple of years on WP projects and I didn't had any issues.  I created a [wrapper](https://gist.github.com/iamntz/81293f1dae47311a8f84f375c400912e) that will allow you to use templates even in a parent/child theme setup.

Here is an idea:

Make all `render` methods to render Handlebars templates instead of mixed php/html. This will have multiple benefits:

1. Will completely separate PHP and HTML ([SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle))
1. you can apply a filter over the rendered data
1. you can easily replace the template file
1. things are clearer and _very_ readable

--- 
I prepared a sample on how you can convert an existing module: icon list.

the *whole* render method:
```php
protected function render() {
  $settings = $this->get_settings();
  $render = [
    'settings' => $settings,
    'items' => $settings['icon_list']
  ]
  echo \iamntz\utils\Tpl::get('elementor/widgets/icon-list', apply_filters('elementor/render/widgets/icon-list', $render));
}
```

elementor/widgets/icon-list.hbs file:
```hbs
    <ul class="elementor-icon-list-items">
    {{#each items}}
        <li class="elementor-icon-list-item" >
          {{#if link.url}}
            <a href="{{ link.url }}">
          {{/if}}
            {{#if icon}}
              <span class="elementor-icon-list-icon">
                <i class="{{ icon }}"></i>
              </span>
            {{/if}}

            <span class="elementor-icon-list-text">{{ text }}</span>

          {{#if link.url}}
            </a>
          {{/if}}
        </li>
    {{/each}}
    </ul>
```

---

¹ It can be any simple, logicless template engine though.

**Comment by KingYes** [comment]
For what we need to use Handlebars templates for our widgets?

**Comment by iamntz** [comment]
@KingYes handlebars was just an example, any template engine will do, as long as it's as dumb as possible (handlebars, mustache).

I gave you four reasons above, here is one more: you can reuse templates between PHP/JS :)

**Comment by KingYes** [comment]
Hi @iamntz 

We are split the templates between PHP/JS, because it's have diff logic (connect to DB and 3th-party for example).
When we start @edirpedro open new issue about this, you can see there: https://github.com/pojome/elementor/issues/181

we'll come back here after we publish the first version of our API to create widgets. If I change the template engine right now, the API release will be delay again, and I don't want to do that for now :)

Thank you guys
