### ISSUE TITLE
[suggestion] easier editing several pages

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#967]
so for something already run across several times and actually again...

when one have to edit little things on several pages one after another it might be a big help to be able navigating from page to page within elementor!

for now xou have to open elementor to edit a page, edit, save, close elementor, choose another page, open elementor, edit ... ... ...
the ability of changing pages to edit within elementor would ease this massively.

in fact kind of more frontend-thing :-)

**Comment by drawcard** [comment]
This would be nice.

I currently hold down Command-click in the Page section of WP, and click on each title - that opens up a new tab for every item. Works for a handful of pages but it's not ideal for hundreds.

**Comment by luisvivasb** [comment]
This is a great suggestion! Maybe a bottom option with pages already converter on Elementor type.

**Comment by arielk** [comment]
Switch Between Pages? It's Already Requested https://github.com/pojome/elementor/issues/292
