### ISSUE TITLE
Does it work with Custom Post Types and Custom Fields?

### ISSUE THREAD

**Issue by ekansh005** [pojome/elementor#97]
Hi Pojo Team,

At first, thanks for gifting this awesome tool to the community.
My question is 'Does it work with Custom Post Types and Custom Fields'? To explain further, I am asking about the features that we get with wp-types Views plugin.

IMO, it would be really a great and revolutionary feature if you add this(if not already present) into elementor.

**Comment by KingYes** [comment]
Elementor support for all your CPT on your system. To enable this, just check it on Elementor setting page.

The Custom Fields, we will add this I think later..

Thanks for your feedback :)

**Comment by ekansh005** [comment]
Hi KingYes,

Thanks for the info. When can we expect the release of future roadmap for this product?
