### ISSUE TITLE
Video element does not work in Elementor 0.11.2

### ISSUE THREAD

**Issue by nedasco-mvl** [pojome/elementor#972]
## Description
I added the video element, but the video did not showed in the page preview pane. You only see the url. I tried to switch it to Vimeo, but the view remained the default Youtube video and the url did not change.

After publishing, you can see that the default url's were added, but no video tag. This way, the video element will not work.

![emelentor 0 11 2-video-bug](https://cloud.githubusercontent.com/assets/24319050/20839158/c64321ec-b8ab-11e6-9d30-97d835c22779.jpg)

## Steps to reproduce
Open a page, make a section, add a video element. Try to switch the video to Vimeo. Try to link to a different video. Safe the page and check the page in your webbrowser. Inspect the html code to see that the url is there, but no video tag.

## Environment
Server Environment 		
Operating System: 	WINNT 	
Software: 	Apache/2.4.23 (Win64) PHP/5.6.25 	
MySQL version: 	5.7.14 	
PHP Version: 	5.6.25 	
PHP Max Input Vars: 	2500 	
PHP Max Post Size: 	8M 	
GD Installed: 	Yes 	
Elementor Library: 	not connected (cURL error 7: Failed to connect to my.elementor.com port 80: Timed out) 	
WordPress Environment 		
Version: 	4.6.1 	
Site URL: 	http://localhost/besuitable

**Comment by arielk** [comment]
If you put a video inside the regular editor that works for you?

**Comment by nedasco-mvl** [comment]
Hi @arielk ,
Pasting the YouTube url in the regular visual wordpress editor is also not making the video work.
I expect that my problem has to do with my WAMP server plus the restrictions put on computers in the network of our company. 
So probably the problem is not Elementor.
