### ISSUE TITLE
Conflito.

### ISSUE THREAD

**Issue by violettwelt** [pojome/elementor#974]
Please, 
today I spent the day with the conflicting plugin.
I've done all the possible ways for it to work.
It did not appear the sidebar, from one moment to another it worked, though it is not saving anymore.
I already disabled all my plugins because I believed it was a jetpack conflict or anyone else.
Still it does not work, please help me.
I would not want to stop using it because the plugin in looks really great.

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.
