### ISSUE TITLE
Force custom post types on theme activation.

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#978]
Hey apologies if this has been asked.

Is there a way to force certain custom post types to be active upon theme activation? I see that you have to manually enable it in the Elementor settings page - would be nice to skip that step for new installs of a theme.

Thanks!

**Comment by KingYes** [comment]
Sure!
You can use [`add_post_type_support()`](https://codex.wordpress.org/Function_Reference/add_post_type_support) with `elementor`.

For example:
```
add_post_type_support( $post_type, 'elementor' );
```
