### ISSUE TITLE
TypeError: wp.media is undefined

### ISSUE THREAD

**Issue by eugenem** [pojome/elementor#979]
I get the following error while trying to set a background image for a section. Any ideas?

TypeError: wp.media is undefined   editor.min.js:5:9895
	[84]</d<.initFrame http://adigal-showroom.co.il/wp-content/plugins/elementor/assets/js/editor.min.js:5:9895
	[84]</d<.openFrame http://adigal-showroom.co.il/wp-content/plugins/elementor/assets/js/editor.min.js:5:9712
	bound  self-hosted
	n.event.dispatch http://adigal-showroom.co.il/wp-includes/js/jquery/jquery.js:3:12392
	n.event.add/r.handle http://adigal-showroom.co.il/wp-includes/js/jquery/jquery.js:3:9156

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
	MySQL version: 5.5.52
	PHP Version: 5.6.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.6.1
	WP Multisite: No
	Max Upload Size: 5 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Asia/Jerusalem
	Debug Mode: Inactive

== Theme ==
	Name: Atlanta Child
	Version: 1.0.0
	Author: Pojo
	Child Theme: Yes
	Parent Theme Name: Atlanta
	Parent Theme Version: 3.6.4
	Parent Theme Author: Pojo Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0

== Active Plugins ==
	Activity Log
		Name: Activity Log
		Version: 2.3.4
		Author: Yakir Sitbon, Maor Chasen, Ariel Klikstein

	Elementor
		Name: Elementor
		Version: 0.11.2
		Author: Elementor.com

	English WordPress Admin
		Name: English WordPress Admin
		Version: 1.5.1
		Author: khromov

	File Manager
		Name: File Manager
		Version: 4.0.4
		Author: 

	Pojo Accessibility
		Name: Pojo Accessibility
		Version: 1.1.5
		Author: Pojo Team

	Pojo Builder Animation
		Name: Pojo Builder Animation
		Version: 1.0.3
		Author: Pojo Team

	Pojo Device Widget
		Name: Pojo Device Widget
		Version: 1.1.0
		Author: Yakir Sitbon, Ariel Klikstein

	Pojo Forms
		Name: Pojo Forms
		Version: 1.4.2
		Author: Pojo Team

	Pojo Lightbox
		Name: Pojo Lightbox
		Version: 2.0.4
		Author: Pojo Team

	Pojo News Ticker
		Name: Pojo News Ticker
		Version: 1.0.3
		Author: Pojo Team

	Pojo Sharing
		Name: Pojo Sharing
		Version: 2.5.12
		Author: Pojo Team

	Slider Revolution
		Name: Slider Revolution
		Version: 5.3.0.2
		Author: ThemePunch

	Toolset Types
		Name: Toolset Types
		Version: 2.2.2
		Author: OnTheGoSystems

	Toolset Views
		Name: Toolset Views
		Version: 2.2.1
		Author: OnTheGoSystems

**Comment by arielk** [comment]
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

If you have a caching plugin, make sure you deactivate it, or even better – purge the cache before.

Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by eugenem** [comment]
it's conflicting with File Manager plugin
