### ISSUE TITLE
Community idea: use Discourse

### ISSUE THREAD

**Issue by iamntz** [pojome/elementor#995]
So yeah:

1. I'm not a big Facebook fan (as is a huge resource hog);
1. WordPress forums kind of sucks in terms of usability, utility and on anything else;
1. I wrote [here](https://forum.sublimetext.com/t/why-sublime-forum-should-be-on-discourse/14654) my reasons why Discourse would be a good idea. Yeah, is on Sublime forum, but it applies here as well.
1. You can create hidden categories (visible only by premium users) (Although I'm not really sure that I agree with this)
1. You can use a category as a documentation hub;
1. You'll get github integration, push notifications and a lot more good stuff;
1. Help is needed, I can assist on initial configuration.

Probably a lot of stuff that i miss now :)

**Comment by KingYes** [comment]
Right now we can't do that. Maybe later we try this.

Thank you :)
